### ISSUE TITLE
Problème de fonctionnement avec avec le module Conformité légale v3.0.0 - par Prestashop.

### ISSUE THREAD

**Issue by Patrice7373** [PrestaShop/PrestaShop#10039]
Bonjour,
J'ai un problème de fonctionnement avec le module Conformité légale v3.0.0 - par Prestashop.

1°) - j'active le module Conformité légale v3.0.0 
2°) - Je clique ensuite sur un produit quelconque de mon site web pour faire apparaître la fiche produit.
3°) - La fiche produit n'apparaît pas !
4°) - La page suivante apparaît à la place :

"Whoops, looks like something went wrong.
ContextErrorException in ps_legalcompliance.php line 943 :
Notice : Undefined index: delivery_str_i18n"
(voir capture d'écran ci-joint)

![00](https://user-images.githubusercontent.com/42639087/44519321-3cdd5200-a6bc-11e8-8dc2-320adb37ee25.PNG)

À noter : si je n'active pas le module Conformité légale v3.0.0, et que je clique sur un produit quelconque de mon site web, la fiche produit apparaît. 

Merci pour votre aide !...

Bien cordialement,
Patrice
---------------------------------------------------------------------------------------------
Hello,

I have a problem with the module Legal Compliance v3.0.0 - by Prestashop.

1 °) - I activate the module Compliance legal v3.0.0

2 °) - I click then on any product of my web site to make appear the product file.

3 °) - The product sheet does not appear!

4 °) - The following page appears instead:

"Whoops, looks like something went wrong.
ContextErrorException in ps_legalcompliance.php line 943:
Notice: Undefined index: delivery_str_i18n "
(see screenshot attached)

![00](https://user-images.githubusercontent.com/42639087/44519321-3cdd5200-a6bc-11e8-8dc2-320adb37ee25.PNG)

Note: if I do not activate the Legal Compliance v3.0.0 module, and click on any product on my website, the product card appears.

Thanks for your help !...

Best regards,
Patrice

**Comment by khouloudbelguith** [comment]
Hi @Patrice7373,

Your issue is a duplicate of #9587, so I close it.

Best regards, Khouloud
