### ISSUE TITLE
Ajax cart popup does not show shipping price 

### ISSUE THREAD

**Issue by espacious** [PrestaShop/PrestaShop#10037]
When adding product(s) to cart does not show Shipping cost. But if you click "Continue to payment" and go back to homepage and add another product the Shipping cost is shown.

1. Go to homepage and add some product to cart. In the ajax cart popup there is no Shipping price.
2. Click on Continue to payment (Nadaljuj na plačilo), and return to homepage.
3. Add another product. Now the Shipping cost is shown.

Screenshots attached.

PrestaShop version: 1.6.1.20
PHP version: 7.0.31
Current theme in use: community-theme-16

![1st_product_added](https://user-images.githubusercontent.com/39135335/44514614-db6bb200-a6c0-11e8-83b8-619e9e60b43e.jpg)
![2st_product_added](https://user-images.githubusercontent.com/39135335/44514622-e1619300-a6c0-11e8-944e-804c0ed3ad1e.jpg)

**Comment by khouloudbelguith** [comment]
Hi @espacious,

Have you tried to contact the theme author about your issue?
Thanks to check with them and feedback.

Best regards, Khouloud

**Comment by espacious** [comment]
No because i assumed is an PS bug. Will try to contact someone but the theme is developed by PS comunity. Any info links where to post the issue?

Ok i posted also in comunity theme git.
https://github.com/PrestaShop/community-theme-16/issues/272

**Comment by khouloudbelguith** [comment]
Hi @espacious ,

Thanks!
Waiting for the feedback.

Best regards, Khouloud

**Comment by espacious** [comment]
No one has any clue?

**Comment by khouloudbelguith** [comment]
Hi @espacious,

I don't think we can do something before their feedback.

Best regards, Khouloud

**Comment by espacious** [comment]
Hi i know/understand, but there is no reply yet from comunity theme developers.

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
