### ISSUE TITLE
inheritance: illegal '{$smarty.block.parent}' used in child template 'template_name' block 'input' #479

### ISSUE THREAD

**Issue by maxprihodko8** [PrestaShop/PrestaShop#10033]
When using the {$smarty.block.parent} in nested block the code does not work and fall with the error : 
"inheritance: illegal '{$smarty.block.parent}' used in child template 'template_name' block 'input'"
The code was working with the Prestashop 1.7.3 and was broken in Prestashop 1.7.4 when the smarty was changed from the Prestashop smarty to the smarty base repository. 

The code:
```
{block name='field'}
    {block name="input"}
        {$smarty.block.parent}
    {/block}
{/block}
```

**Additional information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @maxprihodko8,

Could please confirm this steps:
1-Create a child theme as described here: http://developers.prestashop.com/themes/smarty/parent-child-feature.html
2- In the BO, change the current theme to the childtheme
3- In the file product.tpl into the path "/PROJECT_FOLDER/themes/childtheme-example/templates/catalog/product.tpl, add the code described above.
4- try to navigate to the FO / Product Page => an error in the console is displayed & the code is not working?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @maxprihodko8,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud

**Comment by cdcvince** [comment]
Hello,

I have the same problem, I cannot use {$smarty.block.parent}
Prestashop 1.7.5.1

Regards
