### ISSUE TITLE
paypal add-on is not working

### ISSUE THREAD

**Issue by ebaubau** [PrestaShop/PrestaShop#10031]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**
Paypal payment option is not visible in the front-end.
I tried to reinstall the module, when i activate it i got this message "An error occurred. Please, check your credentials Paypal."
The api credentials are not shown.

I've already contacted the add-ons support, they say it's a bug of new prestashop version, already known.

**To Reproduce**
1. Go to 'paypal module in the BO...'
2. Click on 'modify and login paypal....'
3. see error 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![paypal](https://user-images.githubusercontent.com/37108454/44506534-17921900-a6a7-11e8-9870-a007ad628b1b.png)
![paypal2](https://user-images.githubusercontent.com/37108454/44506535-17921900-a6a7-11e8-9efa-ab9262eef85f.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

**Comment by centoasa** [comment]
are you using the latest plugin?
try to goes on your Paypal account and reinstall module, while have paypal account page opened.

**Comment by khouloudbelguith** [comment]
Hi @ebaubau ,

The Paypal module isn't developed by PrestaShop.
You can contact the developer of this module here: https://www.202-ecommerce.com/en/partners-modules/technical-support/
I close the ticket, feel free to open a new ticket, feel free to open a new one when needed.

Best regards, Khouloud

**Comment by ebaubau** [comment]
I'm using the last plugin and I've tried to do what you suggested, but I
got error

Il gio 23 ago 2018, 09:25 Remigio <notifications@github.com> ha scritto:

**Comment by ebaubau** [comment]
Hi, I've already contacted the paypal add-on support, you can read their
answer in attach.

Thanks

Il gio 23 ago 2018, 10:11 khouloudbelguith <notifications@github.com> ha
scritto:
