### ISSUE TITLE
Multistore admin - switching shop URL during module configuration

### ISSUE THREAD

**Issue by sroubekog** [PrestaShop/PrestaShop#10043]
**Describe the bug**
URL of primary shop is changed during module configuration of others then primary shops.

**To Reproduce**
I have primary shopA and others shops B, C, D. Now if i switch to shopB and go to modules the URL is OK still shopA. But when I try to change configuration of some module it will change URL to shopB and you must sign in again.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.20-1

**Comment by khouloudbelguith** [comment]
Hi,

I created 3 shops ShopA (default shop), B, C.
When I navigate to the Modules & Services Page => I have this URL => http://127.0.0.1:8081/174/1742/admin-dev/index.php/module/manage?_token= => the URL is OK, still the default one.
When I try to configure a module the URL is moved to http://127.0.0.1:8081/174/1742/ShopB/admin-dev/index.php?controller=AdminModules&configure=ps_checkpayment&token= without logging out.

PrestaShop V1.7.4.2.
Best regards, Khouloud

**Comment by sroubekog** [comment]
Without loging out, hmm. Can you try to use two different domains?

**Comment by jolelievre** [comment]
seems to be the same issue, only urls change with the folder ShopA => ShopB

**Comment by sroubekog** [comment]
So you do not need to sign in after domain change? Then I dont know where could be the problem.

**Comment by jolelievre** [comment]
if you managed your different shops urls with a folder there shouldn't be an issue, but in your case with two different domains I think you need to relog because the session cookie is likely stored by domain so there is indeed an issue
besides even without the relog problem, you usually don't want to switch your BO url/domain

**Comment by sroubekog** [comment]
> besides even without the relog problem, you usually don't want to switch your BO url/domain

Exactly! Id like to stay on my primary shop domain no matther waht I am doing in BO :)

**Comment by jolelievre** [comment]
Which is understandable ;) As I said earlier I will deal with this issue as soon as I can
I hope it does not block you for now (aside from the discomfort)

**Comment by alu-** [comment]
I'm also having this issue, would be nice to have it fixed.

**Comment by jolelievre** [comment]
Hello, there is a fix in this PR https://github.com/PrestaShop/PrestaShop/pull/10326
We will try to merge it quickly
