### ISSUE TITLE
[BOOM-3885] Stock Location field missing

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10113]
**NicholasIT**
```
Hi,
i've read about other old stock location requests and you're still planning to develop advanced stock management but i ask it again becouse we [i guess not just us but other merchants with big inventory] just need
a temporary field, anywhere in product page, where we can write the position of the product on the shelfs of our warehouse [for example "A-10"]
I guess this temporary field will help so much even advanced stock management is not complete at the moment.
Thanks for your attention and patience,
```

**PrestaShop team :**

In order to put stock location field back we should put it on several places and change some text (the field will be optional like in 1.6) :  

1) Where do we put the editable field ? :  

if the product has no combination
*Product Page > Quantity Tab*

Rename "Stock Alerts" to "Stock" and add a "Stock location" field

![nocombinaison-location](https://user-images.githubusercontent.com/35263827/44575156-a5473480-a78b-11e8-8fff-5adb900529a6.png)

if the product has combination(s) 
*Combination tab> Edit combination (pencil)*

Rename "Stock Alerts" to "Stock" and add a "Stock location" field 

![combinaison-location](https://user-images.githubusercontent.com/35263827/44575161-aaa47f00-a78b-11e8-8ea5-f7fddef3d8f0.png)

2) Where do we put the information ? 

*Order page> Order tab > Order selection*

At the bottom of the page, on the product, the information of stock location will show up.

If we click on edit (pencil), the stock location will be uneditable

![order-stock-location](https://user-images.githubusercontent.com/35263827/44575167-af693300-a78b-11e8-8609-89707a87652e.png)

**Comment by matks** [comment]
Addition from the Product Team: although the field allows 255 characters to be used, make sure if the 255 chars are used that this does not break the page display. If it does, fix it using CSS.
