### ISSUE TITLE
Shipping number is empty in {followup} if In transit email is launched with the WebService

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#10115]
When you call update OrderCarrier with Prestashop WebService, the Shipping number is empty in the {followup} URL.

The bug is in sendInTransitEmail (OrderCarrier class), $order->shipping_number is empty.

PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier, 

I manage to reproduce your issue with the last version 1.7.4.2.
We will see how to fix it.
#10069 
Previous ticket in the forge: http://forge.prestashop.com/browse/BOOM-4228

Best regards, Khouloud

**Comment by jf-viguier** [comment]
I've fixed it here https://github.com/PrestaShop/PrestaShop/pull/10117

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier ,

Thanks for your fix.

Best regards, Khouloud

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10117

**Comment by marionf** [comment]
Reopened because the PR isn't merged yet
