### ISSUE TITLE
HTML Purifier is not compatible with PHP 7.2

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#10128]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**

An update of HTML Purifier is needed. See log here http://repo.or.cz/w/htmlpurifier.git/blob/v4.10.0:/NEWS

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

Could you please add steps to reproduce your issue in a new comment.

Best regards,
Khouloud

**Comment by MathiasReker** [comment]
Hi @khouloudbelguith

HTML Purifier is not compatible with PHP 7.2 due to changelog. Please check here: http://repo.or.cz/w/htmlpurifier.git/blob/v4.10.0:/NEWS

Also some other minor bugs and improvements is added. I know IQIT asked for an update too. I think he ran into some issues.

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

Have the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9685?

Best regards, Khouloud

**Comment by MathiasReker** [comment]
Yes, same solution for both issues. HTMLPurifier should be updated :-) Hope this will be done for 1.7.5

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9685 
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #9685

**Comment by MathiasReker** [comment]
I fixed it: https://github.com/PrestaShop/PrestaShop/pull/10376
