### ISSUE TITLE
Showcase Index page in SEO & Url listing page 

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10123]
**To  be done after the page migration to Symfony.**

In the page SEO & URL (Shop Parameters > Traffic & SEO > SEO & URL), we need to better showcase the Index page (home page) to explain how to improve the SEO of merchants' homepage.

To do so, we need to add a block on top of the listing which displays information about how to configure the index page, a CTA to the index page configuration, and an external link to the documentation.

Furthermore, the Index row is showcased through a different color and new content (To be confirmed).

See screenshot for more explanation:
![showcase index page](https://user-images.githubusercontent.com/35263827/44585441-ac326f00-a7ac-11e8-94b2-5cb34d513a26.PNG)

**Comment by colinegin** [comment]
I added @CaptainYouz to this issue, he's aware of the card expected behaviour so he will be able to help you on this !

**Comment by kpodemski** [comment]
This is very cool! Small but very appreciated

**Comment by tomas862** [comment]
Hello @CaptainYouz . Nice to meet you! 
It was suggested above that I can ask you several questions regarding card behavior so here it goes:

1. From where I should get the image?

2. Where "Or learn more about SEO" will point to? Can't access this link where I believe I can find the answer https://docs.google.com/document/d/1xeiEwT02OpBxePesgdd68HxKD6XZe6PqYAT3KD76ol4/edit?usp=sharing

3. Whats the behavior of the block if I start resizing the screen - maybe on mobile view it takes full width of the page etc... ?

4. In https://projects.invisionapp.com/share/FQNYNAE6RDJ#/screens card which should be located on Seo page is different from the one which is displayed in this current issue. Which one should I use?

And if there are something more about this block let me know.

Thanks in advance! :slightly_smiling_face:

**Comment by CaptainYouz** [comment]
Hi @tomas862 ! Nice to meet you also :)

About your questions:
1: For the differents assets, you should have received an invitation to access Zeplin! You will be able to download them from there.

2: You also should have access to the doc now, but I put the links here also:
```
CONFIGURE - Shop parameters > Traffic & SEO > SEO & URLs : "Improve your SEO"
EN : http://doc.prestashop.com/display/PS17/SEO+and+URLs
FR : http://doc.prestashop.com/display/PS17/SEO+et+URL
ES : http://doc.prestashop.com/display/PS17/SEO+y+URLs
IT : http://doc.prestashop.com/display/PS17/SEO+e+URL
Others : http://doc.prestashop.com/display/PS17/SEO+and+URLs

IMPROVE - Design > Pages : "Create meaningful content"
EN : http://doc.prestashop.com/display/PS17/Pages+-+Managing+Static+Content
FR : http://doc.prestashop.com/pages/viewpage.action?pageId=51840208
ES : http://doc.prestashop.com/pages/viewpage.action?pageId=54264327
IT : http://doc.prestashop.com/display/PS17/Pagine+-+Gestione+Contenuti+Statici
Others : http://doc.prestashop.com/display/PS17/Managing+Categories

SELL - Catalog > Categories : "Set categories"
EN: http://doc.prestashop.com/display/PS17/Managing+Categories
FR: http://doc.prestashop.com/pages/viewpage.action?pageId=51840157
ES: http://doc.prestashop.com/pages/viewpage.action?pageId=54264082
IT : http://doc.prestashop.com/display/PS17/Gestire+Categorie
Others : http://doc.prestashop.com/display/PS17/Managing+Categories

SELL - Customers > Customers : "Administrate your customers"
EN: http://doc.prestashop.com/display/PS17/Your+customers
FR: http://doc.prestashop.com/display/PS17/Vos+clients
ES: http://doc.prestashop.com/display/PS17/Tus+clientes
IT : http://doc.prestashop.com/display/PS17/I+Tuoi+Clienti
Others : http://doc.prestashop.com/display/PS17/Your+customers

CONFIGURE - Advanced parameters > Team : "Manage your team" 
EN : http://doc.prestashop.com/display/PS17/Team
FR : http://doc.prestashop.com/pages/viewpage.action?pageId=51840334
ES: http://doc.prestashop.com/display/PS17/Equipo
IT : http://doc.prestashop.com/pages/viewpage.action?pageId=54266520
Others : http://doc.prestashop.com/display/PS17/Team

SELL - Catalog > Monitoring : "Monitoring your catalog"
EN : http://doc.prestashop.com/display/PS17/Monitoring+your+Catalog
FR : http://doc.prestashop.com/display/PS17/Faire+le+suivi+de+votre+catalogue
ES : http://doc.prestashop.com/pages/viewpage.action?pageId=54264096
IT: http://doc.prestashop.com/display/PS17/Monitorare+il+Catalogo
Others : http://doc.prestashop.com/display/PS17/Monitoring+your+Catalog
```

3: For the behavior in small screens, no designs have been made yet, but we talked about it with @TristanLDD and we decided that for the moment, a simple responsive behavior would be ok (meaning: have the content aligned in column, image first, then the text)

4: You should always use the ones on invision, since there are up to date!

Also, I started to work on it in https://github.com/CaptainYouz/PrestaShop/commit/85e0bccc8319784c3e0bec587144a153b667aa73. You can start with this :)

Thank you!

**Comment by matks** [comment]
Linked to https://github.com/PrestaShop/PrestaShop/pull/10529

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10529
