### ISSUE TITLE
I can not enable the certificate (SSL) prestashop 1.7.4.2

### ISSUE THREAD

**Issue by anto7880** [PrestaShop/PrestaShop#10134]
Hello everyone, I have a problem, I can not enable the certificate (SSL).
I also contact my hosting provider and told me that the certificate (Thawte SSL 123) is installed on my server.
in the back office the button (enable ssl on all pages) is not selectable.
Please help me?

**Comment by khouloudbelguith** [comment]
Hi @anto7880,

Did you click on "Please click here to check if your shop supports HTTPS"?

Best regards,
Khouloud

**Comment by anto7880** [comment]
Yes, I clicked on (Please click here to check if your shop supports HTTPS)
I get a page of my very messy site

**Comment by khouloudbelguith** [comment]
Hi @anto7880,

Return to Shop Parameters > General > Enable SSL on all pages.
Thanks to check and feedback.

Best regards,
Khouloud

**Comment by anto7880** [comment]
Resolved! it was a problem with the server

**Comment by khouloudbelguith** [comment]
Hi @anto7880,

Thanks for your feedback.

Best regards, Khouloud
