### ISSUE TITLE
After duplicating product I'm unable to upload images on the created product (PS1.7.4.2)

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#10137]
As wrote in the title, on Prestashop 1.7.4.2 if you create a new product duplicating an existing one, when you try to upload images on the new products you'll receive these errors:
PrestashopDatabaseException
Duplicate entry '45-1' for key 'id_product_cover'<br /><br /><pre>INSERT INTO `ps_image` (`id_product`, `position`, `cover`) VALUES ('45', '2', '1')</pre>

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

Here's what showed with debug mode enabled:
![senza noe-1](https://user-images.githubusercontent.com/42684711/44610816-4b338700-a7fe-11e8-8f2e-7c460f814997.gif)

PrestaShop version: 1.7.4.2
PHP version: PHP 7.2.8

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3 ,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/18Fq9h9d9gskp0TmHHwMow7TLDRKlVnaw/view
Did made any changes in the Database before?

Best regards, Khouloud

**Comment by darkf3d3** [comment]
No, but I forgot to say that I'm using multistore.
I think this could be something related to it.

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

No, multistore is enabled and I did not manage to reproduce the issue with PS 1.7.4.2.
https://drive.google.com/file/d/14FUIZBy419pPJ4oWQmiggallVXgaIqzb/view

Best regards, Khouloud

**Comment by darkf3d3** [comment]
Try duplicating a product with an image.
Then on the duplicated product, remove the image and try adding a new one.
I done the same showed on the video, with the only difference of the image, and i get the error showed on the first post.

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

I just followed your steps & everything is Ok: https://drive.google.com/file/d/1lU9eHUMdnOuJjQFPS_gHJ1LM6DIKU150/view
Thanks to navigate to your BO => IMPROVE => Design => Image Settings you can configure the IMAGE SETTINGS.
After that click on the button Regenerate thumbnails.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by darkf3d3** [comment]
EDIT:
This doesn't fixed the problem. I'm still receiving error on some products when changing image.

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by darkf3d3** [comment]
It's all disabled, It's a test website I'm using to test PS1.7 before upgrading my production website to PS1.6.
If you want, I can provide credential to access to the website.

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

I manage to reproduce the issue with PS 1.7.4.2 **randomly**.
How to reproduce the issue:
Please see screen-record:
https://drive.google.com/file/d/1iMx9OFbQ6pAe59dzbKBbFAJpR8n2rnBr/view
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment]
@khouloudbelguith 
We don't see in your video, the "Product A" is a duplicated product ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

No, Product A is not a duplicate.
I manage to reproduce this issue without duplicating also => but it occurs randomly due to the multistore context.
Also, I manage to reproduce this issue after duplicating a product, but as I said before => it is randomly.
![image](https://user-images.githubusercontent.com/16067358/44905150-7b54bb80-ad11-11e8-91e1-939b7c508f6e.png)

Best regards, Khouloud

**Comment by rflorent** [comment]
Hy, I'm facing this error with the 1.7.6.4. 
Still not fixed ?

**Comment by rmlopezcar** [comment]
Hi,
the bug still not fixed. I've a multistore ecommerce. When I duplicate a product to modify it I have the same issue that you describe above. The message that appears is "error creating additional images". I tried the above suggestions, as clean the cache or eraser all the previous photos but still not [working]

**Comment by Hlavtox** [comment]
@hibatallahAouadni @khouloudbelguith Can you check on new product page?

**Comment by MatShir** [comment]
The multistore on the product is not ready yet. So for sure, it will not work yet. But mid-release 8.1, we planned to pass on old product issue to see if we reproduced them. We hope to close many issues 🤞🤞

**Comment by xabatar** [comment]
The issue is still there in PS 1.7.8.7. And is not a random thing. And present not only when product is duplicated.
The bug will pop up if you delete all the images from a product and try to upload new images in a multistore environment. This is a normal workflow if you duplicate the product, but will give you the same issue if the product is not multiplicated and all images are deleted.
Also you can fix it. In the images table form the db, search for the product id and you will see an entry for an image set to cover image, despite you deleted all the images. This is the problem. Once you delete that remaining entry (pointing to a deleted image) you will be able to add images again to that certain product.

**Comment by blawdi** [comment]
Ok, no soluce ?

**Comment by MatShir** [comment]
It seems to be fixed in the version 8.1 that is going to be released soon.

**Comment by blawdi** [comment]
Won't it be possible to get a patch for previous versions?

**Comment by MatShir** [comment]
Hi @blawdi, 
- Version 8.1 is the latest maintained version, including bug fixes, minor feature additions and security fixes.
- Version 8.0 will no longer be maintained at the expense of 8.1 when it is released. They are very similar, and upgrading from 8 to 8.1 is relatively straightforward. This version brings no major breaking changes.
- Version 1.7.8 is maintained for security purposes only. 

The changes made to correct this bug were far too substantial and necessitated a major release.

**Comment by florine2623** [comment]
This issue is fixed with PS 8.1.0. No more exception.

I'm closing this issue.
