### ISSUE TITLE
Some PS_SHOP_ variables are not created after the installation inside ps_configuration

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10133]
Hi

**Describe the bug**
I've seen that some variables of ps_configuration are not created after Prestashop's installation:
PS_SHOP_DETAILS
PS_SHOP_ADDR1
PS_SHOP_ADDR2
PS_SHOP_CODE
PS_SHOP_CITY
PS_SHOP_COUNTRY
PS_SHOP_PHONE
PS_SHOP_FAX

they should be present even if null.
This variables will be created when in the shop information I push on the submit button submitOptionsstore

from the image you can see that these variables are put at the button of the items of the table ps_configuration

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/44590263-06d2c780-a7bb-11e8-91c4-2502adf83d40.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

How did you do to have these attributes?

Best regards,
Khouloud

**Comment by Maofree** [comment]
after pressing on this save button

![1](https://user-images.githubusercontent.com/653230/44594817-84043980-a7c7-11e8-9eb3-d345e49a6ce7.png)

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for this clarifications.
I manage to reproduce the issue with the last version 1.7.4.2.
We will see how to fix it.

Best regards, Khouloud

**Comment by aniszr** [comment]
Hello,
I think that this problem is solved,all mentioned fields are found after executing SQL query on BO Data Base.
I didn't reproduce the issue as you can see in attached video.

Additionnal information
PrestaShop version: 8.0.4

https://github.com/PrestaShop/PrestaShop/assets/92626242/68d474b1-768d-42c3-9d01-f25a299c2bd8


thanks!

**Comment by hibatallahAouadni** [comment]
Hello @aniszr 

Thanks for your feedback :rocket: 
Indeed! the issue seems to be resolved.

Thanks!
