### ISSUE TITLE
1.7.4.2 change database password error

### ISSUE THREAD

**Issue by fuga00** [PrestaShop/PrestaShop#10145]
If you change the password for the database and replace it in the parameters.php file, the backoffice part stops working, the modules, products, advanced modules, preferences are not working properly.
When you click them, you get a 500 error.
The same problem occurs on fresh installation.

**Comment by MathiasReker** [comment]
I can reproduce this one.

**Comment by MathiasReker** [comment]
@fuga00 Hot fix: You can delete cache manually: \var\cache\

**Comment by khouloudbelguith** [comment]
Hi @fuga00,

Have you tried to clear cache manually, as @Mreker just said in the last comment, by deleting the folder into var/cache?
Thanks to check and feedback.

Best regards, Khouloud

**Comment by MathiasReker** [comment]
Some php files should be deleted in cache folder. It worked for me.

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

Thanks for your feedback.
@fuga00, any news from your side? did you solve the issue?

Best regards, Khouloud

**Comment by fuga00** [comment]
Not yet, i check this today.

pon., 27 sie 2018, 12:59 użytkownik khouloudbelguith <
notifications@github.com> napisał:

**Comment by fuga00** [comment]
yes, hotfix work as well.

pon., 27 sie 2018 o 13:02 kolkin <kolkin2@gmail.com> napisał(a):

**Comment by khouloudbelguith** [comment]
Hi @fuga00,

Thanks for your feedback.
I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud

**Comment by MathiasReker** [comment]
I am not sure this should be closed, don't we need a better solution? Or documentation?

**Comment by dragonfly4** [comment]
Thanks for this thread as I had the same issue. Manually deleting the files under "<shop>/var/cache/prod/" solved my error 500.

**Comment by MathiasReker** [comment]
@khouloudbelguith what folders and files exactly are safe to delete due to cache? All folders and files in car/cache?

**Comment by fuga00** [comment]
You can del all.
I propose change folder name from cache to cache_old, PS make new folder
and files.


sob., 1 wrz 2018, 10:57 użytkownik Mreker <notifications@github.com>
napisał:

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

The folder into the path var/cache, should be deleted because there are some files are generated in the cache with the old password:
 /PROJECT_FOLDER/var/cache/prod/appParameters.php
/PROJECT_FOLDER/var/cache/prod/ContainerXo7rwkj/appProdProjectContainer.php

Best regards, Khouloud
