### ISSUE TITLE
Wrong bootstrap classes for left-column ID on contact page

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10147]
HI
**Describe the bug**

in templates/contact.tpl the right code should be this one
`<div id="left-column" class="col-xs-12 col-sm-4 col-md-3">`

to replace to this code
`<div id="left-column" class="col-xs-12 col-sm-3">`

because the contact container has these classes
`<div id="content-wrapper" class="left-column col-xs-12 col-sm-8 col-md-9">`

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/44630584-3c64e580-a960-11e8-8894-892cee066881.png)
![2](https://user-images.githubusercontent.com/653230/44630585-3c64e580-a960-11e8-8d1f-111692f7228f.png)
![3](https://user-images.githubusercontent.com/653230/44630647-37ecfc80-a961-11e8-88e9-b2200c65b936.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

thanks
bye

**Comment by mickaelandrieu** [comment]
Hi @maofree,

would you mind to make a contribution to fix this issue?

Thank you

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

Best regards, Khouloud

**Comment by Maofree** [comment]
Hi
Sorry but I need some days to understand well how to do that on a linux system from my local server
So at this moment I cannot to do that I need to do other things
Can you do that for me for the next 2 months?

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Fixed by https://github.com/PrestaShop/PrestaShop/pull/10195
Done.

Best regards, Khouloud
