### ISSUE TITLE
1.7.X : cart management function in the header & payment block

### ISSUE THREAD

**Issue by fcassado** [PrestaShop/PrestaShop#10149]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**
Payment block (or payment page) is not refreshed if you used the function of the cart in the header, so that the amount in parameters are not refreshed while transfered to certain PSP.

**To Reproduce**
1. Go through order process with 2 products in your cart (item#1 : 10€ + tiem#15 : 15€ = total 25€). You will reach the step "4. payment" with a 25€ to pay.
2. Click on "my cart" in the header, before paying. Change your order by withdrawing item#2 ! -15€. Your cart total amount should be 10€ to pay.
3. After managing your cart, page is not refreshed. click "Pay" with Ogone module or any other psp with an Iframe in payment block.
4. Error : total amount stayed at 25€, it is not refreshed to 10€

**Screenshots**
Number of items & total amount to pay are not refresehed in any PrestaShop theme using this function in the header. (even the native PrestaShop theme)

**Additionnal information**
PrestaShop version: any version 1.7 
![cartandpayment](https://user-images.githubusercontent.com/4069741/44648529-9e196400-a9e1-11e8-8774-7a818f61d12e.png)

**Comment by khouloudbelguith** [comment]
Hi @fcassado,

I did not manage to reproduce the issue with the last version 1.7.4.2, the default theme Classic & the ps_shoppingcart module v2.0.1.
You need to check the issue with the theme author.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @fcassado,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud
