### ISSUE TITLE
No overrides.css for admin new-theme

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#10143]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**
New Symfony pages in the BO use the "new-theme" instead of "default" (if someone could explain why?)
However, there is no way to ovveride styles in this new-theme, as there is no overrides.css file available.

**To Reproduce**
1. Create a style override in adimn-dev/themes/default/css/overrirdes.css
2. Check a Symfony page like "Performance" to see that your override is not used there

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

After clearing cache, could you please try to delete the app/cache/prod/class_index.php file manually and check if the overrides work.

Best regards, Khouloud

**Comment by mickaelandrieu** [comment]
Afaik it's not possible right now to override the styles of the Back Office.

Can you confirm @eternoendless?

**Comment by rdy4ever** [comment]
As far as I tried, it is possibile to override old non-Simfony pages, but not the new Symfony pages, as they use a different theme alltogether (new-theme). This is very strange and I find hard to understand the reasoning behing the back office using two themes in the same time where most of the styles are identical and duplicated.

**Comment by rdy4ever** [comment]
And not being able to ovveride the BO styles gives me a litle tiny pannic attack, as, let's face it, the BO is far from perfect and some UX/design choices are very obnoxious.

**Comment by mickaelandrieu** [comment]
Hi,

```diff
- Simphony
+ Symfony
```

please :/

The admin themes management has been removed from 1.7, and you may have noticed it but we are migrating all the back office, so, for now, it's not really in the top priority to introduce it back.

What you can do is to customize your assets directly in admin/new-theme/ folder, but you won't be able to share it in a module and you won't be able to upgrade your shop.

Regards,

**Comment by rdy4ever** [comment]
done :)

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Can I close the issue?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
