### ISSUE TITLE
contact page - full width - left column is still present without display: none;

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10140]
Hi

**Describe the bug**
if you set "full width" for the contact page, the left column is still present without display: none;
even if the block is hidden

**Steps to reproduce the issue**
Click on Design > Theme & logo
Click on "Choose layout"
For contact us page, select "Full Width - No side columns, ideal for distraction-free pages such as product pages."

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/44616462-6c24c800-a850-11e8-82d2-49b007d01820.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Could you please add steps to reproduce the issue in a new comment.

Best regards, Khouloud

**Comment by Maofree** [comment]
hi
go in the layout template in the admin page and set the full width for the contact us page look with a web tool

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Aditing this lline `<body id="contact" class="lang-en country-fr currency-eur layout-full-width page-contact tax-display-enabled" data-gr-c-s-loaded="true">` has no effects.
![image](https://user-images.githubusercontent.com/16067358/44660978-82c24f00-aa09-11e8-92da-02b2747c90bc.png)

Best regards, Khouloud

**Comment by Maofree** [comment]
hi
look my image at the top, you can see that it is different from yours
the form width is the same so the width is not full
to do that it is necessary only to go in this page and select full width, then you can see the issue

![1](https://user-images.githubusercontent.com/653230/44676404-7652ec00-aa33-11e8-8760-3f58d7e873d0.png)

in my image the form is under the logo

![11](https://user-images.githubusercontent.com/653230/44676480-b1edb600-aa33-11e8-8c56-8f4d265c6aaf.png)

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for this clarifications.
After editing the Layout of the Contact us page to "Full Width - No side columns, ideal for distraction-free pages such as product pages." the left column is still present without display: none; 
We will see how to fix it.

Best regards, Khouloud

**Comment by CaptainYouz** [comment]
The div `<div id="left-column" class="col-xs-12 col-sm-3">` should not be there in the first place when full-width mode is activated. This problem should be handled directly in the template rendering, not in css.
