### ISSUE TITLE
1.7.4.2 Edit Product: tabs are not loaded properly

### ISSUE THREAD

**Issue by twazerty** [PrestaShop/PrestaShop#10148]
A minor issue when editing products. When clicking on the tabs Combinations, Shipping, SEO, Modules etc the tabs are loaded below the contect instead of acting as tabs. Saving the product with this behavior works.

1. Go to an product in backend
2. Click on Combinations tab, then on SEO tab
3. SEO tab is below the combinations section

PrestaShop version: 1.7.4.2
PHP version: 7.1.21

**Comment by khouloudbelguith** [comment]
Hi @twazerty,

I did not manage to reproduce the issue.
I attached a video record: https://drive.google.com/file/d/1xPyL5y0kp1LP0S5N6Vkm07E397kQDRW6/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by twazerty** [comment]
After an extra Ctrl+F5 on the product edit page the problem disappeared. After upgrading from 1.7.3 I had to perform some Ctrl+F5'ing on the backend to get everything working. But this problem remained.

**Comment by khouloudbelguith** [comment]
Hi @twazerty,

Thanks for your feedback.

Best regards, Khouloud
