### ISSUE TITLE
Prestashop 1.7.3.2 - default combination image always displayed

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#10142]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**
On product page, during combination switching, always the default combination image is loaded. The URL is changing, the price is changing, everything changes without combination image. Tried on different PHP versions, disabled non-default modules, but it doesn't help.

**To Reproduce**
1. Go to product page, for a product with combinations
2. Click on any combination
3. See error

**Screenshots**
https://drive.google.com/file/d/1gsRCtqJW-BXrCivD61M92fMsZ9mawwU8/view?usp=sharing
https://drive.google.com/file/d/1Z6rh3NWcXUU2Ji4jFDjFLy79SiKvc19c/view?usp=sharing

**Additionnal information**
PrestaShop version: 1.7.3.2
PHP version: 7.0

**Comment by rdy4ever** [comment]
This must be an issue with your custom theme. Have you tried it with the default theme?

**Comment by ghost** [comment]
Yes, I just tried with the default theme and nothing changes. Same issue ...

**Comment by rdy4ever** [comment]
Any javascript errors in the console? What’s your website url?

**Comment by ghost** [comment]
No javascript errors in the console. 

URL: thenailmastershop.com

**Comment by rdy4ever** [comment]
Indeed there are no js errors but still, this issue is not present in a new Prestashop installation, so it is related to your website, theme or configuration. Maybe you should try to upgrade to the latest PS version. As I don't have access to your BO to investigate more, I cannot give any other advice,

**Comment by ghost** [comment]
Thank you for your time. About configuration, theme and other website settings, I played a lot with them and nothing helped. I will investigate more and even upgrade to the latest version. Hopefully this one will get fixed.

**Comment by khouloudbelguith** [comment]
Hi @klopp1892,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record: https://drive.google.com/file/d/1NVH9gPnelMxgn6V7yQpFpUaRBh8kZCbJ/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by ghost** [comment]
@khouloudbelguith 

Thanks for checking. I noticed that in your video, only one picture is showed per combination. In my case, all images are showed on all combinations and this gave me a reason to check a little bit deeper and discovered something which I tried in the past in the Product class override.

I wanted to display all combination images on all combinations, but in the same time be able to load the combination default image on a combination change because I will always have one image assigned per combination.

Sorry for my stupid "issue".

**Comment by khouloudbelguith** [comment]
Hi @klopp1892,

Thanks for your feedback.
I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud
