### ISSUE TITLE
Fault Zipcode in Making new order in Back Office

### ISSUE THREAD

**Issue by thegioidogiadung** [PrestaShop/PrestaShop#10159]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**

**To Reproduce**
1. Go to 'Backoffice/Orders/New order'
If you choose "new customer" then you will see error
- Step 1: fill his/her email....ok
- Step 2: his/her address form...fault "zipcode is required"
 There is no Zipcode field in this form. I can not understand why?

2. How can I fix this fault?

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

Thanks to navigate to your BO => IMPROVE => International =>Locations => Countries Tab => Edit your coutry, in the Address format, you need to add the post code field.
![image](https://user-images.githubusercontent.com/16067358/44707462-de8de600-aaa4-11e8-9ee7-4236e7ea3e3d.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by thegioidogiadung** [comment]
hi, @khouloudbelguith,

In our country, everyone has no habit of using zipcode (almost people has no idea about zipcode). They always use name of state/province in address.

it is the reason that we removed zipcode in Address format. 

How can I remove the "required" attribute of Zipcode/postcode?

Tks

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

You need to navigate to BO => SELL => Customers => Addresses.
Below the addresses table is the "Set required fields for this section" button. It opens a form where you can indicate if a database field is necessary or not by checking the appropriate boxes: this way, you can make it so fields such as "postcode" not mandatory when a customer is registering a new address on your shop
Thanks to check & feedback.

Best regards, Khouloud

**Comment by thegioidogiadung** [comment]
Hi,
Please see attached file, all of these fields were removed except phone_mobi but they are required in our address form.
How can we solve this problem?

Tks
![40244725_464445120740572_4601261192202158080_n](https://user-images.githubusercontent.com/42737230/44730307-dbc5dc00-ab0a-11e8-8023-db0d43a5608a.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

Did you use the default template of PrestaShop?

Best regards, Khouloud

**Comment by thegioidogiadung** [comment]
Hi,
No, we bought the metro template of Volty, one of the sellers in Presta marketplace ( link: https://addons.prestashop.com/en/electronics-computers-themes/30958-metro-electronic-super-store-v3.html )
How about it? maybe fault of the template?

Tks

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

Yes, it could be.
Thanks to check the issue with the theme author & feedback.

Best regards, Khouloud

**Comment by thegioidogiadung** [comment]
Hi,

Thank for your advise, I will contact them right now 

Best regards,

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

Thanks!
Waiting for your feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @Hanoician,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud
