### ISSUE TITLE
4.1.0 Module fails to load, PS 1.6.1.20

### ISSUE THREAD

**Issue by gorkij77** [PrestaShop/PrestaShop#10154]
Hi, since branching up to the 4.x.x series, i've just gotten 

"Server error!
The server encountered an internal error and was unable to complete your request.

Error message: 
Premature end of script headers: index.php

If you think this is a server error, please contact the webmaster.

Error 500"

when going to the menu for 1-click upgrade. Kindly advise as to what to do.

**Comment by khouloudbelguith** [comment]
Hi @gorkij77,

I did not manage to reproduce the issue with the PS 1.6.1.20 & the 1-click upgrade v4.1.0.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

host
server setup and configuration
PrestaShop version (source)
debug mode report
PHP error logs
apache error log
javascript console log
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by nalberto** [comment]
Same problem here running persta 1.6.1.13

Fatal error: Uncaught Error: Call to undefined method ConfigurationTest::test_curl() in /home/clients//web/modules/autoupgrade/classes/UpgradeSelfCheck.php:111 Stack trace: #0 /home/clients//web/modules/autoupgrade/AdminSelfUpgrade.php(385): PrestaShop\Module\AutoUpgrade\UpgradeSelfCheck->__construct(Object(PrestaShop\Module\AutoUpgrade\Upgrader), '/home/clients/7...', '/home/clients/7...', '/home/clients/7...') #1 /home/clients//web/classes/controller/Controller.php(209): AdminSelfUpgrade->display() #2 /home/clients//web/admin123/functions.php(430): ControllerCore->run() #3 /home/clients//web/classes/Dispatcher.php(347): runAdminTab('adminselfupgrad...', false) #4 /home/clients//web/admin123/index.php(58): DispatcherCore->dispatch() #5 {main} thrown in /home/clients//web/modules/autoupgrade/classes/UpgradeSelfCheck.php on line 111

**Comment by nalberto** [comment]
@gorkij77 check if php option fopen is enabled. That was the issue for me.
Check in Advanced Parameters > Configuration information

**Comment by khouloudbelguith** [comment]
Hi @nalberto,

What is the exact version of the 1-click upgrade did you use? & did you made the upgrade to which version?

Best regards, Khouloud

**Comment by nalberto** [comment]
The latest version.

**Comment by khouloudbelguith** [comment]
Hi @nalberto,

Thanks for your feedback.
I manage to reproduce the issue with the last version of the 1-click upgrade module v4.1.1 & PrestaShop 1.6.
Checked with PS1.7 => OK.
If the **allow_url_fopen** option is disabled, when I try to configure the 1-click upgrade module => error 500
![image](https://user-images.githubusercontent.com/16067358/45021960-45764680-b033-11e8-86b0-0a376ccdaa7a.png)
@Quetzacoalt91, what do you think about this error?

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
I can try to catch this issue before the fatal error, but fopen is a required extension of PrestaShop.

**Comment by khouloudbelguith** [comment]
Hi @Quetzacoalt91,

Thanks!
Yes,fopen is required: http://doc.prestashop.com/display/PS16/What+you+need+to+get+started#Whatyouneedtogetstarted-Quickset-upinstructions

Best regards, Khouloud

**Comment by PierreRambaud** [comment]
@Quetzacoalt91 `test_curl` was maybe added in 1.7 (https://github.com/PrestaShop/PrestaShop/commit/af602c587529ad4350d42eb47836c8260a11ea1e) you maybe need to check if method exists before running it?

**Comment by Quetzacoalt91** [comment]
Even easier. I call directly the `extension_loaded()` method. See https://github.com/PrestaShop/autoupgrade/pull/157
