### ISSUE TITLE
1.7.X : Voucher block on right column & payment block

### ISSUE THREAD

**Issue by fcassado** [PrestaShop/PrestaShop#10150]
> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**
If you use the voucher block on the right column before paying, total amount of the order is not refreshed with the discount.

**To Reproduce**
1. Create a voucher code in BO & start a new cart in front office. Go through order process with a certain amount in your cart : X €
2. Use the voucher code, by fulfilling the block in right column (cart details : link "click here if you have a voucher"). If your code is OK, then cart tolal is review from X€ to Y€. Amount is OK in the right column : Y€
3. In step "4. pay" , click "Pay" with Ogone module or any other PSP using Iframe in payment block .
4. Error : Total amount stayed at X€, it is not refreshed with the discount

**Screenshot**
See screenshot with 31,98€ and 70% of discount (it should be 10,99€ to send in parameters to pay), but the form keep 31,98€ because of page not refreshed

**Additionnal information**
PrestaShop version: any 1.7.X 
![voucher](https://user-images.githubusercontent.com/4069741/44649186-788d5a00-a9e3-11e8-8363-0c9e268330f6.JPG)

**Comment by khouloudbelguith** [comment]
Hi @fcassado,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9505
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by fcassado** [comment]
Thanks for taking it on the roadmap.
Have a good day

Cordialement, Best regards


Frédéric CASSADO

Directeur des opérations - Director of operations

Phone : +33 (0)9 72 56 28 87







Le lun. 27 août 2018 à 12:47, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
Duplicate of #9505
