### ISSUE TITLE
"Minimum quantity for sale" bug

### ISSUE THREAD

**Issue by mrttahd** [PrestaShop/PrestaShop#10162]
Hi, 
I've found a bug on PrestaShop 1.7.4.2. On cart page, the minimum purchase order quantity for a product is 4 but you can decrease product quantity and checkout normally. 

https://youtu.be/BI3s16RY53o
![b1](https://user-images.githubusercontent.com/29031285/44697040-4a238380-aaa4-11e8-94c4-515c74da1fd5.png)
![b2](https://user-images.githubusercontent.com/29031285/44697039-4a238380-aaa4-11e8-88a6-795ce0b887e2.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mrttahd,

I manage to reproduce the issue with the last version 1.7.4.2.
We will see how to fix it.

Best regards, Khouloud

**Comment by MathiasReker** [comment]
I think Thisted is a big issue. Can you add it to 1.7.
5?

**Comment by marionf** [comment]
@Mreker 
No, there are more important issues to solve before this one

**Comment by MathiasReker** [comment]
I think this is critical. It is never fun to call a customer to tell him that his order will get deleted because of a issue on the website. And that he needs to replace his order.

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

As @marionf said, there are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Best regards, Khouloud

**Comment by Naprosnia** [comment]
Hello i made this js code to fix this bug on my shop. Simply past it at the end of-> /themes/YOURTHEME/assets/js/custom.js. Enter your shop and refresh your browser (ctrl + f5) to clean old cached js file.

```javascript
/* Fix Min val on product page */
	function ControlMinValue(){
		var minVal=parseFloat($("#quantity_wanted").attr("min"));
		if($("#quantity_wanted").val() <= minVal){
			$("#quantity_wanted").val(minVal);
			$(".bootstrap-touchspin-down").prop( "disabled", true );
		}else{
			$(".bootstrap-touchspin-down").prop( "disabled", false );
		}
	}
	
	ControlMinValue();
	
	$("#quantity_wanted").change(function(){
		ControlMinValue();
	});
/* End Fix Min val on product page */
```
