### ISSUE TITLE
Cannot download language pack "en"

### ISSUE THREAD

**Issue by bensnjo** [PrestaShop/PrestaShop#10161]
Pestashop on localhost showing this error. Kindly help to resolve it.

**Comment by khouloudbelguith** [comment]
Hi @bensnjo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
 [http://build.prestashop.com/howtos/misc/how-to-create-bug-report/]

Thanks!

Best regards, Khouloud

**Comment by bensnjo** [comment]
I was able to work around it. Now am getting a list of errors on loggin in to the admin
![capture](https://user-images.githubusercontent.com/42752977/44709269-e1430800-aab1-11e8-8fc6-80a4475d4e02.PNG)

**Comment by bensnjo** [comment]
what are this errors and how do I resolve 
![1](https://user-images.githubusercontent.com/42752977/44709464-629a9a80-aab2-11e8-8108-d778e89ce4cc.PNG)
![2](https://user-images.githubusercontent.com/42752977/44709465-63333100-aab2-11e8-8685-69cdea1a438c.PNG)
![capture](https://user-images.githubusercontent.com/42752977/44709466-63333100-aab2-11e8-9708-9cf57db36aa0.PNG)


them?

**Comment by PierreRambaud** [comment]
Try to remove `./app/Resources/translations/en-US/en-US.zip` and retry. Look like something goes wrong during download :)

**Comment by antruongnguyen** [comment]
Hi @khouloudbelguith,
I also have the same issue when installing PrestaShop version 1.7.4.2
![screen shot 2018-08-31 at 11 58 51 am](https://user-images.githubusercontent.com/13411559/44893483-91fd1180-ad15-11e8-9f31-d562f50906a1.png)

**Comment by khouloudbelguith** [comment]
Hi @antruongnguyen,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by alexmano** [comment]
@khouloudbelguith This is becoming frustrating!!! Come on, it took almost 15 minutes to barely start the progress for the installation and at 23% the stupid language pack cannot be installed. Why there is no fallback plan for this stupid language pack component ? At least default to English and try afterwords to install a language pack. The entire setup cannot continue due to this elefantic proportion idiotic bullshit...

**Comment by khouloudbelguith** [comment]
Hi @alexmano,

I'm sorry to hear that you're disappointed about the installation, but could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
- The issue occurs only with the language pack "en"?; did you tried to import another language?

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by alexmano** [comment]
Hello @khouloudbelguith , sorry for the frustration...

I have found out that we are behind a proxy server and the download is somehow stopped by the proxy filters. 

  I have investigated the issue further and in order for the installation to work I have updated the file prestashop_1.7.4.2\src\PrestaShopBundle\Install\Install.php and commented from line 604, check my code below:

> 

//if (InstallSession::getInstance()->safe_mode) {
                EntityLanguage::checkAndAddLanguage($iso, false, true, $params_lang);
            /*} else {
                if (file_exists(_PS_TRANSLATIONS_DIR_.(string)$iso.'.gzip') == false) {
                    $language = EntityLanguage::downloadLanguagePack($iso, _PS_INSTALL_VERSION_);

                    if ($language == false) {
                        throw new PrestashopInstallerException($this->translator->trans('Cannot download language pack "%iso%"', array('%iso%' => $iso), 'Install'));
                    }
                }

                $errors = array();
                EntityLanguage::installLanguagePack($iso, $params_lang, $errors);
            }*/`

<

Looks like I have successfully installed Prestashop with English language and now I have to check for other issues that might appear due to my change in the code.
Have a nice day.

**Comment by khouloudbelguith** [comment]
Hi @alexmano,

Thanks for your feedback, so your issue is related to your server.
@bensnjo any news about your issue?

Best regards, Khouloud

**Comment by bensnjo** [comment]
Hi , So far so good. I was able to install and its running smoothly. Though
am getting a 'Your website is not mobile friendly' on Google. seems some
javascript files are not loading properly.  My website is www.riftmall.co.ke
Best Regards
Benson Njoroge Kamau

**Comment by khouloudbelguith** [comment]
Hi @bensnjo,

Since it is fixed, I will close the ticket.
About the second issue, it is a different one, you need to create a new ticket with specific details.

Best regards, Khouloud

**Comment by agunk31** [comment]
![2](https://user-images.githubusercontent.com/47803217/53063340-52f68e80-34f6-11e9-84a6-6ef3a5788150.png)
you have problem in install prestashop , you can try my step
![6](https://user-images.githubusercontent.com/47803217/53063540-0d869100-34f7-11e9-8165-dcd5c255405d.png)
you edit in root C:\xampp\htdocs\prestashop\src\PrestaShopBundle\Install and edit use sublime text
find line 619
![5](https://user-images.githubusercontent.com/47803217/53063386-7a4d5b80-34f6-11e9-8f05-cf5dfa42df51.png)
change this same for my picture and use "//" in front of and change "false value" to "true value" and save
next step you back to prestashop installation and "clicking here" waiting for prossing. 

thx.

**Comment by Gx-Estudio** [comment]
mi solución fue activar:


zlib.output_compression 


en el servidor

![image](https://user-images.githubusercontent.com/11979146/53290463-c7456200-3782-11e9-8bef-9e1711a4d516.png)

**Comment by AlexanderKosianchuk** [comment]
I think that issue should be reopen, because problem is really exist at least if use docker containers, that are provided in repo, and solutions above are tricky

**Comment by khouloudbelguith** [comment]
Hi @AlexanderKosianchuk,

In my case here's what I followed & I installed the PS1.7.5.0 successfully with docker containers, that are provided in the repository.
1. Download the stable version PS1.7.5.0 from this link: https://www.prestashop.com/fr/versions-precedentes
2. Unzip the folder downloaded
3. Into the Project folder, I run `docker-compose up`

=> Two containers are successfully created
1. `foldername_mysql_1` container from the image `mysql:5`
2. `prestashop-git` container from the image `prestashop/prestashop-git:7`
3. Give the write and read access is to use the same user the container image.

```
$ chown -hR www-data:www-data ./Project_Folder_name
```
4. I tried to access to http://localhost:8001/install-dev
5. I am resigned to install composer 
6. I created a file composer.json into the Project folder similar to this https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/composer.json
7. I installed the composer from this link: https://getcomposer.org/download/
8. Then I run this command: `php composer.phar install` => OK
9. I tried to access to `http://localhost:8001/install-dev `=> OK ( MYSQL_ROOT_PASSWORD = password )
10. Installation complete => access to BO via this link: `http://localhost:8001/admin-dev`

Heres' my server information
![image](https://user-images.githubusercontent.com/16067358/52851499-91670480-3116-11e9-9ec6-3f8feb4cc52c.png)

Heres' my volume for the `prestashop-git` container
![image](https://user-images.githubusercontent.com/16067358/52852809-ee17ee80-3119-11e9-947d-0b4e1837cce3.png)

Thanks!

**Comment by AlexanderKosianchuk** [comment]
@khouloudbelguith, оh, sorry, i have found i've used unstable 1.7.6.0

**Comment by khouloudbelguith** [comment]
@AlexanderKosianchuk, thanks for your feedback

**Comment by oceanshaw** [comment]
pay attention to your icu version in your system,this may be the problem

**Comment by julio899** [comment]
> ![2](https://user-images.githubusercontent.com/47803217/53063340-52f68e80-34f6-11e9-84a6-6ef3a5788150.png)
> you have problem in install prestashop , you can try my step
> ![6](https://user-images.githubusercontent.com/47803217/53063540-0d869100-34f7-11e9-8165-dcd5c255405d.png)
> you edit in root C:\xampp\htdocs\prestashop\src\PrestaShopBundle\Install and edit use sublime text
> find line 619
> ![5](https://user-images.githubusercontent.com/47803217/53063386-7a4d5b80-34f6-11e9-8f05-cf5dfa42df51.png)
> change this same for my picture and use "//" in front of and change "false value" to "true value" and save
> next step you back to prestashop installation and "clicking here" waiting for prossing.
> 
> thx.
Excellent Thanks @agunk31 to  * 25 Oct 2019 * I can solvent with it. Is Awesome that it fail 
It is surprising that at this date a follow this failure.
It has given me in different environments. and I have been able to solve it by commenting. This facment as illustrated by the images.

**Comment by phaan** [comment]
The solution from julio899  worked for me, with prestashop 1.7.6.1 on a raspberry pi (with raspbian)
Thanks julio899

**Comment by FuTuRNeT** [comment]
Hi All, 
The solution from julio899  Work for me also, 
Many Thanks :)

Best Regards
Akram

**Comment by fakhrululum** [comment]
> > ![2](https://user-images.githubusercontent.com/47803217/53063340-52f68e80-34f6-11e9-84a6-6ef3a5788150.png)
> > you have problem in install prestashop , you can try my step
> > ![6](https://user-images.githubusercontent.com/47803217/53063540-0d869100-34f7-11e9-8165-dcd5c255405d.png)
> > you edit in root C:\xampp\htdocs\prestashop\src\PrestaShopBundle\Install and edit use sublime text
> > find line 619
> > ![5](https://user-images.githubusercontent.com/47803217/53063386-7a4d5b80-34f6-11e9-8f05-cf5dfa42df51.png)
> > change this same for my picture and use "//" in front of and change "false value" to "true value" and save
> > next step you back to prestashop installation and "clicking here" waiting for prossing.
> > thx.
> > Excellent Thanks @agunk31 to  * 25 Oct 2019 * I can solvent with it. Is Awesome that it fail
> > It is surprising that at this date a follow this failure.
> > It has given me in different environments. and I have been able to solve it by commenting. This facment as illustrated by the images.

thank's dude, solved

**Comment by Sasni** [comment]
If I install Prestashop this way, how do I add the language later?

**Comment by RobertKolman** [comment]
I think that this ticket should be reopened, because i'm facing the exactly same issue also in the latest version (1.7.8.3). I don't understand why developers have not been able to add some workaround in installation flow, when the users are still facing the same issue for more than 4 years. 

<img width="984" alt="Screenshot 2022-01-30 at 16 23 13" src="https://user-images.githubusercontent.com/11886370/151705928-06a40dd9-4386-4f4d-b9c3-2b686cbcd5c2.png">

I've debug it a little bit and figured out, that install.php is trying to find .gzip translation file (row 616) in translations folder, but there are not any .gzip files. 

<img width="863" alt="Screenshot 2022-01-30 at 16 38 19" src="https://user-images.githubusercontent.com/11886370/151706437-e60b1889-75b5-4946-bf04-6ece8bd59569.png">

<img width="268" alt="Screenshot 2022-01-30 at 16 34 58" src="https://user-images.githubusercontent.com/11886370/151706446-6ff94d11-d64a-451d-8939-c282788a9313.png">

**Comment by protektwar** [comment]
Found the problem ;)

I have changed the timeouts in classes/Tools.php in function     private static function file_get_contents_curl: 
            curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 200); // here was 5 
            curl_setopt($curl, CURLOPT_TIMEOUT, 200);                   // here was $curl_timeout

![image](https://user-images.githubusercontent.com/45262264/164977878-f4fb966e-61d5-4336-8994-0eea55898997.png)

**Comment by tallesfsilva** [comment]
> Found the problem ;)
> 
> I have changed the timeouts in classes/Tools.php in function private static function file_get_contents_curl: curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 200); // here was 5 curl_setopt($curl, CURLOPT_TIMEOUT, 200); // here was $curl_timeout
> 
> ![image](https://user-images.githubusercontent.com/45262264/164977878-f4fb966e-61d5-4336-8994-0eea55898997.png)



> Found the problem ;)
> 
> I have changed the timeouts in classes/Tools.php in function private static function file_get_contents_curl: curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 200); // here was 5 curl_setopt($curl, CURLOPT_TIMEOUT, 200); // here was $curl_timeout
> 
> ![image](https://user-images.githubusercontent.com/45262264/164977878-f4fb966e-61d5-4336-8994-0eea55898997.png)

It worked for me! Thanks a lot!

**Comment by tallesfsilva** [comment]
> Found the problem ;)
> 
> I have changed the timeouts in classes/Tools.php in function private static function file_get_contents_curl: curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 200); // here was 5 curl_setopt($curl, CURLOPT_TIMEOUT, 200); // here was $curl_timeout
> 
> ![image](https://user-images.githubusercontent.com/45262264/164977878-f4fb966e-61d5-4336-8994-0eea55898997.png)

It worked for me! Thanks a lot!

**Comment by danloop88** [comment]
i try install prestashop 8 on zettahost, error in 23% Cannot donload language pack, 
any solution is working. Someone can help ?

**Comment by theFra985** [comment]
For any future lurker the issue seems to be also related to old docker daemon versions being used to run the image relating to [this](https://stackoverflow.com/questions/59911649/fatal-unable-to-access-link-getaddrinfo-thread-failed-to-start).

**Comment by matks** [comment]
Thanks for sharing @theFra985 😉

**Comment by wapophis** [comment]
Using docker-compose i solved adding to prestashop service config "  security_opt:
      - seccomp=unconfined"
