### ISSUE TITLE
How can I add compliance to GDPR law for identity form?

### ISSUE THREAD

**Issue by psoit** [PrestaShop/PrestaShop#10167]
Our version is Prestashop 1.6.1.17, we use Official GDPR Compliance by PrestaShop (1.5 & 1.6) - Order #988143

How can I add compliance to GDPR law for identity form?

If I add to template themes/theme960/identity.tpl:

                {hook h='displayGDPRConsent' moduleName='contactform'}

The consent does not appear. I thing, that reason is, that in gdpr admin module is not included this checknox. The same problem is in version Prestashop 1.6.1.20.

**Comment by khouloudbelguith** [comment]
Hi @psoit,

Thanks to follow this documentation: http://build.prestashop.com/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/.
I hope this helps you to solve your issue.
Indeed, you can contact the module author via your account: https://addons.prestashop.com/en/contact-us?id_product=32323
I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud
