### ISSUE TITLE
Chargement de polices de caractères

### ISSUE THREAD

**Issue by lerougestefan** [PrestaShop/PrestaShop#10173]
Bonjour, 

J'ai un site web qui charge à priori beaucoup de police de caractères 220.9 KB / 1.0 MB pour une page.

Est ce normal, est il possible de réduire ces chargements? Si oui comment?

![image](https://user-images.githubusercontent.com/42785695/44751355-3f0a3b00-ab18-11e8-9cff-b07b5c1494d7.png)

Vous remerciant d'avances pour votre aide,

> **Reminder**
> 
> DO NOT create security issues here, but contact security@prestashop.com instead!

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @lerougestefan,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @lerougestefan,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud
