### ISSUE TITLE
PS 1.7.4.2 - Cart icon number don't refresh when clicking on "Add to cart" button

### ISSUE THREAD

**Issue by LimousinArcherie** [PrestaShop/PrestaShop#10184]
Hello,
when my customers add articles by clicking the "add to cart" buttons, the cart icons beside the menu don't refresh immediately, so my customers don't know the quantity they add.
It refresh only when changing pages...
I searched for same issues, check the config but didn't find any documentation.
Thanks in advance for your help
Arnaud

**Comment by khouloudbelguith** [comment]
Hi @LimousinArcherie,

Did you use the default template by PrestaShop?
What is the exact version of the PrestaShop did you use?

Best regards, Khouloud

**Comment by LimousinArcherie** [comment]
Hello Khouloud, thanks for your quick reply.
I don't use the default theme, but a new one: do you think it can be a theme bug?
I'm using PS 1.7.4.2.
Regards

**Comment by khouloudbelguith** [comment]
Hi @LimousinArcherie,

Yes, it could be.
Thanks to check the issue with the theme author & feedback.

Best regards, Khouloud

**Comment by LimousinArcherie** [comment]
Ok I'll tell you.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @LimousinArcherie,

Thanks!
Waiting for your feedback.

Best regards, Khouloud

**Comment by LimousinArcherie** [comment]
Khouloud,
the theme team asked me to test with the default theme and the problem is the same...
Any idea?
Thanks

**Comment by khouloudbelguith** [comment]
Hi @LimousinArcherie ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by MathiasReker** [comment]
Do you have a cache module installed?

**Comment by rdy4ever** [comment]
If [this](https://www.limousin-archerie.fr) is your website, it works fine for me.

**Comment by LimousinArcherie** [comment]
Hello
yes, now it works.
Thanks all for your replies and help!
The problem was a module conflict, not the theme.
I deactivated the module and no it works.
Same suspect issues with the mondial relay module, so I reinstalled it and now ok too.
Hope it can helps others.
Best regards

**Comment by khouloudbelguith** [comment]
Hi @LimousinArcherie,

Thanks for your feedback.

Best regards, Khouloud
