### ISSUE TITLE
Migrate International > Localization > Currencies page

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10189]
Type: page
status : in-progress
Part of Symfony migration project

![capture d ecran 2018-11-28 a 11 27 07](https://user-images.githubusercontent.com/3830050/49145655-929b4900-f300-11e8-970d-7284f8e761c0.png)

Listing (grid) with row actions (toggle/modify/delete) and 2 configuration blocks

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/10774
- [x] Handle UX feedback https://github.com/PrestaShop/PrestaShop/pull/11877
- [x] Migrate 2 blocks about exchange rate https://github.com/PrestaShop/PrestaShop/pull/11894
- [x] Check with @MatShir for CLDR

Migrate 2 blocks: see https://github.com/PrestaShop/PrestaShop/issues/10189#issuecomment-448999300

Page hidden can be reached via admin-dev/index.php/improve/international/currencies/

**Comment by tomas862** [comment]
Hi @colinegin 

I was wondering of how two tiny blocks  in currency list should look like
![currency_list](https://user-images.githubusercontent.com/17051250/46486162-d6446b80-c805-11e8-9451-9ebbdf33d000.png)

My questions would be:

1. Should they be located in the same place on the new page?
2. Maybe there is a sketch of how they should look like on the new page?

Thank you for the answers! :slightly_smiling_face:

**Comment by colinegin** [comment]
Good question @tomas862 !
In my opinion, if we can move those blocks somewhere else on the page, it would be easier to understand.
What do you think @TristanLDD or @NadiaCamard ? Is there any sketch for that type of page ?

**Comment by TristanLDD** [comment]
Hi @tomas862, I recommend to merge the 2 blocks and to display the tab in full screen: 
![blocs_currency](https://user-images.githubusercontent.com/27484094/46529580-4222e480-c897-11e8-8058-0711c7199998.jpg)

**Comment by tomas862** [comment]
Nice - I thought about something similar but now it's very clear what to do. Thank you!

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/10774

**Comment by matks** [comment]
Status: need to review https://github.com/PrestaShop/PrestaShop/pull/10774
Does it include the 2 blocks ?

**Comment by tomas862** [comment]
Hi @TristanLDD  - 
in the comment you mentioned here https://github.com/PrestaShop/PrestaShop/issues/10189#issuecomment-427313482 you suggest by moving it below the list. But the currency list can have 50 values listed in single page.
And another question - should the "Exchange rates" block take whole page or the half page as it is in the https://github.com/PrestaShop/PrestaShop/issues/10189#issuecomment-427313482?

**Comment by TristanLDD** [comment]
Hi @tomas862, I don't think it's a problem to have the exchange rates below the table because in the vast majority of cases this list won't contain more than 3 to 5 values  
And it is ok to use half page for this bloc ;)

**Comment by matks** [comment]
@MatShir This page is now fully migrated 😄 shall we check together it works well with CLDR ?

**Comment by matks** [comment]
Validated with @MatShir for CLDR
