### ISSUE TITLE
Migrate Advanced Parameters > Database > SQL Manager > Add new SQL query

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10188]
Part of the Symfony migration project

**Comment by sarjon** [comment]
hello @colinegin , this part of migration is already done in https://github.com/PrestaShop/PrestaShop/pull/9206 :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/9206

**Comment by colinegin** [comment]
Great, thank you @sarjon !
