### ISSUE TITLE
Migrate "Catalog > Categories > Add new / edit category" page

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10194]
Type: page
Comment: blocked by TinyMCE multiling behavior (see below)

Blocked by https://github.com/PrestaShop/PrestaShop/issues/10194#issuecomment-457557961

Part of Symfony migration project

Todo:
- [x] 1st PR to migrate most of the things https://github.com/PrestaShop/PrestaShop/pull/10408
- [x] 2nd PR to handle QA validation and code review feedbacks https://github.com/PrestaShop/PrestaShop/pull/12782
- [x] Handle images deletions https://github.com/PrestaShop/PrestaShop/pull/11481
- [x] Add SEO preview as on the product page => see issue https://github.com/PrestaShop/PrestaShop/issues/13259
- [x] Update title fields length (see below) https://github.com/PrestaShop/PrestaShop/pull/13152
- [x] TinyMCE multi-lang issue => see issue https://github.com/PrestaShop/PrestaShop/issues/13206

Fields length: https://github.com/PrestaShop/PrestaShop/issues/12875
For SEO preview, see https://github.com/PrestaShop/PrestaShop/pull/9444

**Comment by mickaelandrieu** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/10408

**Comment by sarjon** [comment]
Blocking issues (as i see):
1. Make TinyMCE input compatible with multilanguage fields

It also needs small design tweaks and small changes, but that's not a blocking issue.
