### ISSUE TITLE
Migrate International > Localization > Currencies > Add new / edit currency page

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10190]
Type: page
Part of Symfony migration project

URL `/admin-dev/index.php/improve/international/currencies/1/edit`

Todo:
- [x] Migrate form https://github.com/PrestaShop/PrestaShop/pull/11894

**Comment by tomas862** [comment]
Hi @TristanLDD 

where the status block should be located on the currency form page and how should it look like?
![status_form](https://user-images.githubusercontent.com/17051250/50286951-a81c1280-0469-11e9-9f3a-bb4e1499248b.png)

maybe it should look like something like this?
![off_on](https://user-images.githubusercontent.com/17051250/50287047-f4ffe900-0469-11e9-893c-f70d80487150.png)

Update:

Never mind about this question - in theory that switch did not done any separate action, its the part of the form so I'll include it as any other form :+1:

**Comment by TristanLDD** [comment]
@tomas862  Yes it should be integrated in the form :)

**Comment by matks** [comment]
Feedback by eternoendless : use switch button from UI Kit (http://build.prestashop.com/prestashop-ui-kit/section-3.html) for currency status

**Comment by tomas862** [comment]
So this:
![love_cats](https://user-images.githubusercontent.com/17051250/52654107-fdb8ec80-2ef9-11e9-82c5-f98c0bcb446b.png)

should be used instead of status here
![currency_status](https://user-images.githubusercontent.com/17051250/52654221-3e186a80-2efa-11e9-8522-41375c2c36b0.png)

? :slightly_smiling_face:

**Comment by matks** [comment]
Yes 😄 but I was going to do it in order not to bother you (I thought it might be bothering to come back on this page)

**Comment by tomas862** [comment]
Actually I can do that if you don't have time since right now all my major Pr's are in question or blocked states 😄
