### ISSUE TITLE
MBO/ Module manager : New hierarchy

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/PrestaShop#10203]
**Is your feature request related to a problem? Please describe.**
Modules Catalog (Addons Iframe) has been removed but it's is finally better to keep it. 
**Describe the solution you'd like**
Can you add it again and move it on the Module Catalog (new menu) categories ? Then, the menu will be: 
category: Modules 
sub categories: Module Manager and Module Catalog 
tabs of Module Catalog: Module Catalog / Module Selections.
Please note (cf picture) that : Module Catalog was the Selection page seen in the previous version of PrestaSHop (where all partner and some paid modules are displayed)
Modules Selections was the Addons Iframe called Modules Catalog.
This can be confusing so be careful :) . 
<img width="733" alt="capture d ecran 2018-08-29 a 17 37 09" src="https://user-images.githubusercontent.com/13449462/44799343-fa33e200-abb3-11e8-9939-031f28f7d2b8.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by Quetzacoalt91** [comment]
Please see https://github.com/PrestaShop/PrestaShop/pull/10200
