### ISSUE TITLE
Discount in block cart

### ISSUE THREAD

**Issue by jejoe16** [PrestaShop/PrestaShop#10213]
Hi

When I add a discount code I don't see the subtotal in the blockcart changing, only in the cart summary. The blockcart should change as well.

![discount](https://user-images.githubusercontent.com/22035796/44858148-9ff95680-ac71-11e8-93c5-8e3273a039d2.png)

**Comment by khouloudbelguith** [comment]
Hi @jejoe16,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

Best regards, Khouloud
