### ISSUE TITLE
The form invoice options legal free text is not well displayed - Multilanguage

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10212]
**Describe the bug**
Multilanguage is enabled.
In the BO =>  Orders => Invoices page, the form invoice options legal free text is not well displayed.
![image](https://user-images.githubusercontent.com/16067358/44856158-0af45e80-ac6d-11e8-8723-64e6f89f55a9.png)

**To Reproduce**
1. Go to BO => Orders => Invoices Page
2. Scroll down to bottom of the page
3. The form invoice options legal free text is not well displayed

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith 
What do you mean by "Not well displayed" ?
All the multi line fields are like this on migrated pages, you can see also on Maintenance page

**Comment by khouloudbelguith** [comment]
It is a normal behavior, so I close it.
