### ISSUE TITLE
when a product image is deleted its folder is still present with index and fileType files

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10210]
Hi

**Describe the bug**
when a product image is deleted its folder is still present with these files:
index.php
fileType

in this mode the site will be full of useless files

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/44845777-bc37cc00-ac4e-11e8-9dc3-e0edbe349218.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I manage to reproduce the issue.
After deleting an image, the folder still exists contains only the fileType.
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment]
@eternoendless What do you think ?
Do we need to remove these files ?
