### ISSUE TITLE
MBO updates needed for new hierarchy

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/PrestaShop#10214]
**Is your feature request related to a problem? Please describe.**
The hierarchy has changed in the software and MBO must update it.
**Describe the solution you'd like**
The new hierarchy is : 
category: Modules
<img width="733" alt="capture d ecran 2018-08-29 a 17 37 09" src="https://user-images.githubusercontent.com/13449462/44859659-dedcdb80-ac74-11e8-9406-7e47fd91a9d0.png">

sub categories: Module Manager and Module Catalog
tabs of Module Catalog: Module Catalog / Module Selections.
Please note (cf picture) that : Module Catalog was the Selection page seen in the previous version of PrestaSHop (where all partner and some paid modules are displayed)
Modules Selections was the Addons Iframe called Modules Catalog.
**Describe alternatives you've considered**

**Additional context**

**Comment by marionf** [comment]
Issue related: PrestaShop/ps_mbo#32
