### ISSUE TITLE
Problem with e-mail validation

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10222]
> **Reminder**
> 
> DO NOT disclose security issues here, contact security@prestashop.com instead!

**Describe the bug**
Current validation method allow people to use not valid e-mails in system, for example:
twój@email.com, jakiś@email.com

we can easily use our polish special characters and they're not escaped nor validated properly, of course this can cause a lot of issues as those e-mails are not RFC 822 compilant and Swift will not send message to this kind of address

**To Reproduce**
1. Enable mailalerts module
2. Allow people to leave e-mail for notification about stock returns
3. Use wrong e-mail

**Additionnal information**
Possible solution is to replace current method of validation to FILTER_VALIDATE_EMAIL

**Comment by khouloudbelguith** [comment]
Hi @kpodemski 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9638
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #9638

**Comment by eternoendless** [comment]
Just FYI

> Possible solution is to replace current method of validation to FILTER_VALIDATE_EMAIL

`FILTER_VALIDATE_EMAIL` doesn't accept addresses according to RFC 6531 (which is why we don't use it).
