### ISSUE TITLE
Problems with units and how they are displayed PS 1.7.4.2

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10239]
If I have mm, kg, g, l etc. I'll the a first capital letter such as Kg, Mm, G, L

Why?

![skarmavbild 2018-09-02 kl 15 49 14](https://user-images.githubusercontent.com/42907000/44956683-2a3af800-aec8-11e8-98e1-7f79f173a2e9.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9
http://sjostromaudio.net

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

Could you please navigate to your BO => IMPROVE => International => Localization, check the "LOCAL UNITS" and feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
As I write I have g, km, l, mm all units with small letters.

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

It is a normal behavior in the Classic theme.
But you can modify this behavior by deleting the line 9657 `text-transform: capitalize;` into the file /Project_folder/themes/classic/assets/css/theme.css
![image](https://user-images.githubusercontent.com/16067358/44990468-62f2d400-af91-11e8-8540-9e773962e2b8.png)
You need to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Thank you! It helped but who wants this feature really. Does somebody write kg and mm as Kg and Mm?
