### ISSUE TITLE
Alt tag empty in product listing BO

### ISSUE THREAD

**Issue by gswant** [PrestaShop/PrestaShop#10236]
Good evening,
I purchased a "Prestablog" module which takes the ALT tag from imageManager, prestashop 1.7.4.
It seems however that there is a problem in the function and the alt tag is not powered.

line 89 return 'img src = "'. self :: getThumbnailPath ($ cacheImage, $ disableCache). '" alt = "" class = "imgm img-thumbnail" ;

The programmer tells me to go directly to prestashop but I do not know how.

I enclose your answer to my question;

Dear Sirs, 
After checking all prestashop's and our module datas, i found the answer. 
We use the thumbnail function from the imageManager created by prestashop. 
In this function, the alt tag is settle to empty as you can see here : 
return '<img src="'.self::getThumbnailPath($cacheImage, $disableCache).'" alt="" class="imgm img-thumbnail" />';
Since we use the thumbnails in the related products, these are empty aswell. 

And this for all thumbnails of prestashop and prestablog using this function. 
The only solution would be to modify DIRECTLY the imagemanager by adding one variable $alt and to add it in the alt tag, but this can cause several problems of recovering datas, and maybe of crashing. 
I would'nt recommend it to you, or directly contact prestashop's service. 

![58428415-499f3400-809a-11e9-8241-3bac142058e1](https://user-images.githubusercontent.com/13449658/74537081-ac42a380-4f39-11ea-832a-302597104882.png)

**Additionnal information**
PrestaShop version: 1.7.7.2
PHP version: 7.1

----------
**SPECS**

The alt of the image should be the caption saved in the product page, if the caption is empty the alt is the name of the product in the current language

**Comment by khouloudbelguith** [comment]
Hi @gswant,

Could you please provide me the Prestablog to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks & best regards, Khouloud

**Comment by gswant** [comment]
Thank you
I have turned your request to the programmer of the module to contact you

Thanks so much

**Comment by khouloudbelguith** [comment]
Hi @gswant,

Thanks!
Waiting for the feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Following the response of the module developer, there is a lack of alt is present in the back office section products, not only in their module.
`<img src="/img/tmp/product_mini_20.jpg?time=1535978614" alt="" class="imgm img-thumbnail">`
Which I manage to reproduce it with the last version 1.7.4.2

Best regards, Khouloud

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with 1.7.6.0 ?
It's on the product page in BO ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, the same issue with PS1.7.6.0beta1.
It is in the BO => Product page

![image](https://user-images.githubusercontent.com/16067358/58428415-499f3400-809a-11e9-8241-3bac142058e1.png)

Thanks!

**Comment by arouiadib** [comment]
Hi,
Could you please tell what is the purpose of having a non empty alt tag in BO product listing images?

**Comment by MatShir** [comment]
Done in 8.1 :)
