### ISSUE TITLE
"Soft URL variable" instead of "Hard URL"

### ISSUE THREAD

**Issue by twazerty** [PrestaShop/PrestaShop#10237]
**Is your feature request related to a problem? Please describe.**
When I want to link to a category/product/content page from a category or product page I am only be able to add a "a href". But when the url of the product or category changes, the url can become broken, or at least it is not up to date.

**Describe the solution you'd like**
It would be nice if you could insert an "internal link" by selecting a product-id, category-id, content-id, brand-id. Result could look something like this:
`{product id=44 text='Example'}`
instead of:
`<a href="https://example.com/44/t-shirt.html">Example</a>`
first link follows any rewrite module or url change, second link gets broken if url structure is changed or a rewrite module generates a new link. This way the url is always up2date.

Idea from: https://docs.cmsmadesimple.org/tags/cmsms-tags/cms_selflink

**Comment by khouloudbelguith** [comment]
Hi @twazerty,

Recently we have made some modifications related to the SEO OPTIMIZATION in the product page.
Thanks to follow those links & feedback: https://github.com/PrestaShop/PrestaShop/pull/9463
https://github.com/PrestaShop/PrestaShop/pull/9456

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @twazerty,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
