### ISSUE TITLE
Mailalerts and default combination.

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#10248]
Prestashop version 1.7.3.4-1.7.4.2
MailAlert version - 2.1.0

It's not a presta bug. This bug is related with MailAlert module.

If the module is enabled and the default combination is out of stock than you cannot switch to other combination those are in stock.
The form of the module is not beeing hidden.

Here is the description https://github.com/PrestaShop/ps_emailalerts/issues/5

I did a pull request that fixes that bug https://github.com/PrestaShop/ps_emailalerts/pull/11

I open this issue to pay attention to that bug of the module. I hope that the module will be updated soon.

**Comment by khouloudbelguith** [comment]
Hi @LedCloud,

I did not manage to reproduce the issue with the last version 1.7.4.2 & the ps_emailalerts module v2.1.0 - by PrestaShop.
I attached a video record: https://drive.google.com/file/d/1FHZ0NJ-wEC2LnBd4Vno69C_z4bRH0S97/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by LedCloud** [comment]
You're right. It afffects 1.7.3.4

There is no bug on 1.7.4.2

**Comment by khouloudbelguith** [comment]
HI @LedCloud,

Thanks for your feedback.

Best regards, KHouloud

**Comment by Markosaar** [comment]
Hi, @khouloudbelguith 

Can you tell wich ps version and pull contains fix for this issue?

Best Regards
Marko

**Comment by khouloudbelguith** [comment]
Hi @Markosaar,

This issue cannot be reproduced.

Thanks!
