### ISSUE TITLE
backoffice -> modules redirects to frontoffice instead display the modules page

### ISSUE THREAD

**Issue by revington** [PrestaShop/PrestaShop#10246]
> **Reminder**
> 
> DO NOT disclose security issues here, contact security@prestashop.com instead!

**Describe the bug**
On a fresh prestashop 1.7.4.2 install I just click on modules (or any url like *index.php/*) and got redirected to the frontoffice.

**To Reproduce**
1. Install prestashop 1.7.4.2
2. Go to backoffice
3. Click on modules
4. You get redirected to the frontoffice

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: php 7.0

After enabling debug mode I get this message 
```
[Debug] This page has moved
Please use the following URL instead: http://domain.com/index.php?_token=QftOPOO6CPMsRp5H_3-JrJaOjOtVxBOkvg1y-kizNl4
```

**Comment by khouloudbelguith** [comment]
Hi @revington,

I did not manage to reproduce the issue with the last version 1.7.4.2.
Could you please try to regenerate the file .htaccess
1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
I see that you're runing a Nginx server on your shop.

You may need to configure your virtual host for running properly with PrestaShop. We provide an exemple here: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist

**Comment by revington** [comment]
Thanks @khouloudbelguith, @Quetzacoalt91!
Tweaking "friendly url" did not fix the problem. Updating my nginx conf as suggested by @Quetzacoalt91 did. After that prestashop was redirecting ssl traffic to non ssl site. nginx was redirecting all non ssl to ssl :( 
So I "enabled ssl" and "enabled ssl on all pages". Then it worked as expected!

**Comment by khouloudbelguith** [comment]
Hi @revington,

Glad it is solved for you.

Best regards, Khouloud
