### ISSUE TITLE
Undefined index error for module products in the same category

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10259]
> **Reminder**
> 
> DO NOT disclose security issues here, contact security@prestashop.com instead!

**Describe the bug**
Install the module "Products in the same category" and you will see an undifined index error in FO when you click on a product

**To Reproduce**
1. Go to Modules > Modules Catalog
2. Install module "products in the same category"
3. Go in FO and click on a product

**Screenshots**
![capture d ecran_232](https://user-images.githubusercontent.com/13449658/44990360-127b7680-af91-11e8-95f6-9976e1efcac2.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
This PR should have fixed it: https://github.com/PrestaShop/PrestaShop/pull/10230. By any chance, are you sure that your `develop` is up-to-date with the remote repository?

**Comment by marionf** [comment]
@Quetzacoalt91 
Yes, sure
I don't have the error with ps_productinfo
But I have the error with ps_categoryproducts

**Comment by Quetzacoalt91** [comment]
Issue to be fixed with a module update. See https://github.com/PrestaShop/ps_categoryproducts/pull/2

**Comment by PierreRambaud** [comment]
@marionf I'm not able to add labels, but you can test the PR :)

**Comment by Quetzacoalt91** [comment]
The PR has been merged and a new version of the module has been created. I'm closing.
