### ISSUE TITLE
Notifications icons not correctly placed on module page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10251]
> **Reminder**
> 
> DO NOT disclose security issues here, contact security@prestashop.com instead!

**Describe the bug**
Notifications icons are not correctly placed on module page

**To Reproduce**
1. Go to Modules > Modules manager
2. Look notifications icons on alerts & updates tabs

**Screenshots**
![capture d ecran_226](https://user-images.githubusercontent.com/13449658/44986434-fe7d4800-af83-11e8-9bd1-c3ec8464368c.png)

Should be placed like this:

![capture d ecran_227](https://user-images.githubusercontent.com/13449658/44986447-0806b000-af84-11e8-9915-a3f0c9f16bce.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by PierreRambaud** [comment]
I'm taking it with Module Manager refactoring :)

**Comment by marionf** [comment]
@PierreRambaud I can't reproduce it today on develop branch

**Comment by marionf** [comment]
In fact, it happens only with google chrome
On Firefox it's ok
