### ISSUE TITLE
Custom zones not working 

### ISSUE THREAD

**Issue by elkeselda** [PrestaShop/PrestaShop#10266]
Hi I have a problem with zones, when I set custom zone and customer address is in custom zone, not all options are available for costumer.It also sets wrong price of the shipping method. 
This happened after I modified the custom zone. (It was working for the first time) but after modification its not working anymore. Even if I delete the zone or carrier and create new one   
Im using prestashop 1.7.4

**Comment by khouloudbelguith** [comment]
Hi @elkeselda,

What are the exact missing options? 
Which countries are selected for this custom zones?

Best regards, Khouloud

**Comment by elkeselda** [comment]
Hi selected country is Czech republic(which has its own zone), missing option is 'test' carrier created which has all information set.

**Comment by khouloudbelguith** [comment]
Hi @elkeselda,

I attached a video record: https://drive.google.com/file/d/1KwrWvDcTXSkt1_Kv4iDVe-AspZ1DFGiY/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by elkeselda** [comment]
Hi, the problem was caused by one of my shipping modules. Thank you for your time.

**Comment by khouloudbelguith** [comment]
Hi @elkeselda,

Thanks for your feedback.

Best regards, Khouloud
