### ISSUE TITLE
Google Lighthouse SEO test fails on products with attributes

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#10261]
I posted an error report directly on the Lighthouse project here:
https://github.com/GoogleChrome/lighthouse/issues/5951

I am running a vanilla installation of PS 1.7.4.2 and the Lighthouse SEO tests fails on the product pages that have attributes in the URL.

It may or may not be a Lighthouse issue but if there is any risk that a Prestashop product page is getting a 0 SEO score from a Google tool, I think it is worth investigating.

Also, in case you did not know. Lighthouse can be integrated into your CI pipeline. There is a nice package for it. I think it could be worth having for regression tests.

**Comment by khouloudbelguith** [comment]
Hi @johanlantz,

We are currently working to change this in 1.7.5 so that the canonical points to the default combination.
Thanks to check this PR: https://github.com/PrestaShop/PrestaShop/pull/9456 & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @johnstyle ,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
