### ISSUE TITLE
Friendly-url Japanese character (kanji)

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#10262]
**Describe the bug**
When we put a title in Japanese _(and I guess Chinese too)_ in the product page, the friendly-url is blank.
This blank friendly-url affect the load of the product image and of course the url of the page.

**To Reproduce**
1. Create a product with a Japanese title バナナ and upload an picture
2. Go to the SEO tab to "see" the blank Friendly-url
3. Save and try to see the page in Front-office
4. See the error

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

You need to enable the Accented URL option in the Shop Parameters / Traffic & SEO page.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by BenTen** [comment]
Ho, I didn't notice "Accented URL option" was for that too.
I'm sorry...

THANK YOU!

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your feedback.

Best regards, Khouloud
