### ISSUE TITLE
String issue with themecusto

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10269]
**Describe the bug**
The name of the module isn't displayed

**To Reproduce**
1. Go to Modules > Modules manager
2. Disable module ps_themecusto
2. Click on Design > Theme & Logo > Homepage configuration
3. The name of the module isn't displayed

**Screenshots**
![capture d ecran_242](https://user-images.githubusercontent.com/13449658/45032374-eecc3500-b051-11e8-88e6-08d8fd63a9ae.png)

**Additionnal information**
PrestaShop version: develop

**Comment by marionf** [comment]
@Adrienaddons I just found this on the develop branch (future 1.7.5.0) when testing themecusto

**Comment by Quetzacoalt91** [comment]
Fixed by https://github.com/PrestaShop/ps_themecusto/pull/5

**Comment by matks** [comment]
The PR has been merged however it requires a release of the module to be shipped with PrestaShop 1.7.5 ⚠️
