### ISSUE TITLE
UndefinedMethodException with ps_legalcompliance

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10275]
**Describe the bug**
When the module ps_legalcompliance is installed, you can see an UndefinedMethodException in Front office

**To Reproduce**
1. Go to Modules > Modules Catalog
2. Install ps_legalcompliance
3. Go to Front office

**Screenshots**
![capture d ecran_247](https://user-images.githubusercontent.com/13449658/45037208-bf6ff500-b05e-11e8-8e29-62bf26db40d3.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed, release in progress
