### ISSUE TITLE
Highlight outofstock combination

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#10289]
HI!
I offer to mark the combination that is outofstock with some markup.
![outofstock_comb](https://user-images.githubusercontent.com/37952504/45071867-71ec9a00-b0e9-11e8-8307-3dcaca0cd3fc.png)

On a attached picture, size L is marked as unavailble.

Of course it could be made only on one dimensional selects.

Two dementional lists better show as a table, but it's should be another feature request I expect.

**Comment by khouloudbelguith** [comment]
Hi @LedCloud,

Thanks for your report & your suggestion.
@marionf, what do you think about this suggestion?

Best regards, Khouloud

**Comment by marionf** [comment]
Hello @LedCloud 

When you have a combination out of stock and if you don't allow order of out of stock product, there is already a message displayed when you select the combination

![capture d ecran_258](https://user-images.githubusercontent.com/13449658/45082375-791ba400-b0f9-11e8-8166-59a8823de31e.png)

If you disable the combination, the customer can't select it and don't know why it's disabled

@CaptainYouz what do you think ?

**Comment by LedCloud** [comment]
Of course I know about that I can disable combinations those are outofstock but what if I want to let my customers know that I would have those combinations some time later and the customers will be able to order them. In that case they will have to select the combination they needed and subscribe for the notification.

On the other hand those who want to select the available item quickly could see the available items at once. They wouldn't have to select each combination to check if that is available.

![select](https://user-images.githubusercontent.com/37952504/45084637-dfabbc80-b10f-11e8-959d-44c6a25016f8.png)

**Comment by CaptainYouz** [comment]
Hi LedCloud. Unfortunately, attaching an onclick event to an `option` inside a `select` element is not supported by all browsers. Therefore, the scenario describe cannot be done properly.
