### ISSUE TITLE
Email doesn't work PS 1.7.4.2 [Solved, no bug]

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10283]
When I use the PHP email I get lot's of error messages. When I installed the shop it was OK to use PHP 7.2 but now I have 

Check your configuration
Required parameters: **Please fix the following error(s)**

Optional parameters: **OK**

![skarmavbild 2018-09-04 kl 21 03 12](https://user-images.githubusercontent.com/42907000/45052024-f60d3600-b085-11e8-8b6d-141af6ced707.png)
![skarmavbild 2018-09-04 kl 21 03 48](https://user-images.githubusercontent.com/42907000/45052067-0b826000-b086-11e8-9a3e-a28046f0d9c6.png)

**When I change order status from Payment accepted to Preparation in progress**

Unknown error on line 38 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 39 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 40 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 41 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 42 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 38 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 39 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 40 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 41 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 42 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 38 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 39 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 40 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 41 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 42 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 38 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 39 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 40 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 41 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 42 in file /home/sjostrom/public_html/cart/modules/gamification/classes/GamificationTools.php
[8192] Function create_function() is deprecated

Unknown error on line 872 in file /home/sjostrom/public_html/cart/classes/Mail.php
[8192] idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

I have also tested PHP 5.4 doesn't work at all.

From 5.6 it works but not the email.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

About the issue [Required parameters: Please fix the following error(s)], It seems that a description is missing, and that's why it could not be listed in the "following errors". 
Here's the PR about that issue in https://github.com/PrestaShop/PrestaShop/pull/9407.
If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.
About sending Email issue, to configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature.

PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 is compatible with PHP 7.2.
More than a year later, current LTS version for Symfony is 3.4, [PHP 5.4 is no longer receiving any security patches](http://php.net/supported-versions.php) and less than 10% of PrestaShop installs are on PHP 5.4 or below.
Of course, we recommend that you run your PrestaShop install on the latest version of PHP.
PrestaShop 1.7 works perfectly with PHP 7.1. I actually use it on my dev environment myself.
In fact, all contributions are tested automatically with PHP 5.6, 7.0 and 7.1. The upcoming PrestaShop 1.7.4 is also tested with PHP 7.2.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Some news: I have installed a fresh shop in parallel with the same php version (7.2) and settings on the same server. I get OK on both the requirements and the email function works so something has happened during the migration of the old data. Can you give any hint where I should compare the email functionality and settings?

I might also add that my old 1.6.1.20 shop on the same server is working with the same php settings.

**Comment by peranderssjostrom** [comment]
Solved: The store email address was a bit faked for spam protection but I'll guess you or my web hotel has a check of the "from" email address. The thing is that your software can handle this in PS 1.6.1.20. Can you confirm that you have some email cloaking function for the visible email address I have in the footer? Is the front page spambot proof?

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

Thanks for your feedback.
Glad to solve your issue.

Best regards, Khouloud
