### ISSUE TITLE
Issues in search / export feature in migrated pages

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#10293]
**Describe the bug**
Currently, the export action in Crud pages doesn't take in account the results filtered by the User.

**To Reproduce**
1. Go to one listing page migrated on SF (Categories or Customers)
2. Filter the Grid using Search form.
3. Click on the Wheel, then "Export" action
4. The generated file contains all categories.

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: whatever

**Comment by colinegin** [comment]
Hello @khouloudbelguith, do you know if this issue still occurs in the latest version ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

I manage to reproduce the issue with PS1.7.6.1 & the branch 1.7.6.x.
It was ok with PS1.7.5.2
So, it is a regression
https://drive.google.com/file/d/1WWfprXUyLRFre2GTpsgagdw5Subu9caP/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
Same issue on the Customers page
