### ISSUE TITLE
Menu animation doesn't open properly 

### ISSUE THREAD

**Issue by TristanLDD** [PrestaShop/PrestaShop#10298]
In the BO, when you open the lateral menu, the animation is not the same as when you close the menu: 
Closing animation: 1 - text disappears; 2 - menu closes
Opening animation: 1 - text appears 2 - menu opens
Opening animation should be: 1 - menu opens; 2 - text appears when menu is fully opened
This result in a bad display of the text while the menu opens.

1. Go to the back office
2. Click the icon to close the menu
3. Click on the icon to open the menu 
4. See that text appears too early and makes the animation look strange

PrestaShop version: 1.7.4

**Comment by khouloudbelguith** [comment]
Hi @TristanLDD,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2

Best regards, Khouloud

**Comment by Progi1984** [comment]
Fixed by #16543
