### ISSUE TITLE
Smarty/CCC Cache still does not update version number on recompile css

### ISSUE THREAD

**Issue by GeoTimber** [PrestaShop/PrestaShop#10303]
**Describe the bug**

When I add a custom.css file to the YAML file of the classic theme
```
  css:
    all:
      - id: custom-style
        path: assets/css/custom.css
```
and I enable SMARTY cache +  CCC cache I expect the version number of the generated combined file to change when I make a change to custom.css.

Clearing the cache, deleting, restarting it, etc has no effect as far as I can see.

The file name is always:
```
theme-2bc796.css
```

**QUESTION**
Or am I supposed to do something else to increment the version numbers of my custom.css?

**Additionnal information**
Versión de PrestaShop: 1.7.2.4
Versión PHP: 7.0.30
URL de la tienda: http://lastorcas.com/tienda/
Tema actual en uso: classic

**Comment by khouloudbelguith** [comment]
Hi @GeoTimber,

Could you please delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by GeoTimber** [comment]
Sorry for the late reply, no such file there
```
[root@boabdil public_html]# ls config/
alias.php     bootstrap.php   db_slave_server.inc.php  defines_uri.inc.php  services          smartyadmin.config.inc.php  smartyfront.config.inc.php
autoload.php  config.inc.php  defines.inc.php          index.php            settings.inc.php  smarty.config.inc.php       xml
[root@boabdil public_html]# 
```

How is the file name generation seeded?

**Comment by khouloudbelguith** [comment]
Hi @GeoTimber,

Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @GeoTimber,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
