### ISSUE TITLE
Cart rule with "exclude discounted products" do not work as expected

### ISSUE THREAD

**Issue by tomlev** [PrestaShop/PrestaShop#10300]
**Describe the bug**
In BO, an option on cart rule is "exclude discounted products". But if I add discounted product in my cart on FO, and the corresponding cart rule, discount will be applied on all cart rows

**To Reproduce**
In BO : Create 2 products, one with a discount. Create a cart rule and check the option "exclude discounted products"
In FO add the 2 products, and the cart rule. Cart total should be calculated with cart rule applying only on the not-discounted product 

comments about that issue here : https://github.com/PrestaShop/PrestaShop/pull/9383

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @tomlev,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45107035-958b0100-b138-11e8-9678-7b9742cc7a9a.png)

Best regards, Khouloud

**Comment by StarDev-it** [comment]
Hi,

I've found an operator precedence error in the file src/Core/Cart/RuleCalculator.php at row 78:

```
                    if (in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                        || in_array($product['id_product'] . '-0', $selected_products)
                           && (($cartRule->reduction_exclude_special && !$product['reduction_applies'])
                               || !$cartRule->reduction_exclude_special)) {
                        $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
                        $cartRuleData->addDiscountApplied($amount);
                    }
```
must be:
```
                    if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                        || in_array($product['id_product'] . '-0', $selected_products))
                        && (($cartRule->reduction_exclude_special && !$product['reduction_applies'])
                            || !$cartRule->reduction_exclude_special)) {
                        $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
                        $cartRuleData->addDiscountApplied($amount);
                    }
```

**Comment by hitinder** [comment]
> if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
>                         || in_array($product['id_product'] . '-0', $selected_products))
>                         && (($cartRule->reduction_exclude_special && !$product['reduction_applies'])
>                             || !$cartRule->reduction_exclude_special)) {
>                         $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
>                         $cartRuleData->addDiscountApplied($amount);
>                     }

Hello StarCod3! How do I apply these changes?
I mean after I make the changes to the code. How can I make sure my Prestashop is using the latest code?

**Comment by kokemartinez** [comment]
we found this error  in the vertion 1.7.6.3 but in the file

> src/Core/Cart/CartRuleCalculator.php
in the line 166 i try to fix it but. does not work

someone knows how to fix it?

**Comment by GIORGIOMARIO** [comment]
Discount voucher problem: The discount code applies to all products, even to discounted items with the version 1.7.6.5.

When I apply the discount code on 1 item, the code does "exclude discounted products".
But when I apply it on more than 1 item (1 normal and 1 disounted product per example), the code apply reduction on all products.


![Problème code promo](https://user-images.githubusercontent.com/75362627/100856228-70a6a500-348b-11eb-9d74-52d20eb2f621.jpg)

**Comment by khouloudbelguith** [comment]
Hi @GIORGIOMARIO,

This issue is reported here: https://github.com/PrestaShop/PrestaShop/issues/19090#issuecomment-679971538
It is added to our bug roadmap.

Thanks!

**Comment by GIORGIOMARIO** [comment]
> Hi @GIORGIOMARIO,
> 
> This issue is reported here: [#19090 (comment)](https://github.com/PrestaShop/PrestaShop/issues/19090#issuecomment-679971538)
> It is added to our bug roadmap.
> 
> Thanks!

Thank you!
