### ISSUE TITLE
Onglet "Sélection" absent (Modules et service)

### ISSUE THREAD

**Issue by fanny-echo** [PrestaShop/PrestaShop#10308]
**Describe the bug**
Version de Prestashop 1.7.0.4 - Manque la section "Sélection" pour l'installation d'un plugin natif Prestashop (mail alerts). 
J'ai besoin rapidement de paramétrer ce module pour la mise en ligne du site bache-pro.fr . Or il n'est pas possible d'installer Mail Alerts car la section "Sélection" n'est pas visible.

**To Reproduce**
1. Dans le back office
2. Modules > Modules et Services
3. Pas d'onglet "Sélection" de disponible

**Screenshots**
<img width="1865" alt="capture d ecran 2018-09-06 a 10 49 25" src="https://user-images.githubusercontent.com/43030392/45146358-05de6480-b1c3-11e8-9046-15d0c14bd293.png">

**Additionnal information**
PrestaShop version: 1.7.0.4
PHP version: 7.1
Installation "module en un clic" via OVH

**Comment by khouloudbelguith** [comment]
Hi @fanny-echo,

What is the exact version of the ps_mbo module did you use?

Best regards, Khouloud

**Comment by fanny-echo** [comment]
The exact version of ps_mbo module is : 1.0.5

Fanny

**Comment by khouloudbelguith** [comment]
Hi @fanny-echo,

You need to upgrade your module to the last version.
This issue is fixed in this PR: https://github.com/PrestaShop/ps_mbo/pull/14
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
