### ISSUE TITLE
Cron - 'MCRYPT_RIJNDAEL_128 error  1.6.1.20

### ISSUE THREAD

**Issue by RomanXT** [PrestaShop/PrestaShop#10309]
Hello,
if cron performs actions that login on to the account:

PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /var/www/vhosts/led-glass.eu/shop.led-glass.eu/classes/Rijndael.php on line 124

PHP 5.6.37
Prestashop 1.6.1.20
The old version of Prestashop does not have this error

**Comment by khouloudbelguith** [comment]
Hi @RomanXT,

Could you please add steps to reproduce the issue in a new comment.

Best regards, Khouloud

**Comment by RomanXT** [comment]
Used module Crontab 2.0.2 in Prestashop
- adding to server cron: 
 * * * * * /usr/bin/env php "/var/www/vhosts/led-glass.eu/shop.led-glass.eu/index.php" "fc=module&module=cron&controller=cron&token=vdgi9Kry"

Then adding in crontab:
https://shop.led-glass.eu/modules/prestabay/cron.php
then he gets errors on the email

I also have added task:
- indexing 
- currencies,
- comments
does not cause such errors

**Comment by PierreRambaud** [comment]
Fixes in #9251 but you can also install php-mcrypt extension to remove this error :)

**Comment by RomanXT** [comment]
Extension mcrypt in PHP is installed from the very beginning on the server
Also, that's not it

[root@led-glass ~]# rpm -qa | grep mcrypt
plesk-php71-mcrypt-7.1.21-centos7.18082011.x86_64
plesk-php56-mcrypt-5.6.37-centos7.18072013.x86_64
plesk-php70-mcrypt-7.0.31-centos7.18072012.x86_64

**Comment by khouloudbelguith** [comment]
Hi @RomanXT,

Could you please provide me the exact config of the crontab module.
You can find it into the path /PROJECT_NAME/modules/module_name/config.xml

Best regards, Khouloud

**Comment by RomanXT** [comment]
`<module>
	<name>cron</name>
	<displayName><![CDATA[Crontab for Prestashop]]></displayName>
	<version><![CDATA[2.0.2]]></version>
	<description><![CDATA[Allows modules to schedule jobs to run automatically at a certain time or date.]]></description>
	<author><![CDATA[Samdha]]></author>
	<tab><![CDATA[administration]]></tab>
	<is_configurable>1</is_configurable>
	<need_instance>0</need_instance>
	<limited_countries></limited_countries>
</module>`

**Comment by RomanXT** [comment]
Info from author Prestabay:
It's because PrestaBay module trigger changes to create the customer with password. For encode, password PrestaShop uses the mcrypt library. And as result, you get this error. 
The most simple solution it's mute that error, so you will not see it at all (that how it's work for whole PS store). But it does not solve the issue, it just ignores it.

**Comment by khouloudbelguith** [comment]
Hi @RomanXT,

You need to apply this patch https://github.com/PrestaShop/PrestaShop/pull/9251 just suggested by @PierreRambaud 

Best regards, Khouloud

**Comment by RomanXT** [comment]
Thanks, it's works without errors.

Regards
Roman

**Comment by khouloudbelguith** [comment]
Hi @RomanXT,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
