### ISSUE TITLE
Shop not found in classes/Shop.php

### ISSUE THREAD

**Issue by Prestashopnewbie** [PrestaShop/PrestaShop#10307]
Since a while,
I`m having some trouble with an exception that keeps comming back... 
There is nothing found in the logs, debug modus doesn`t give any information... Because of the fact I relly don`t have a clue wath is causing this issue.
But the shop jumps offline, sometimes a few times a day... This is not the way I could manage a professional shop... 

The exception is solved always in seconds, just changing the php version from 7.1 to 7.2 & return again ... 
But this is not a definitive solution... 

Exception log: 
```
*ERROR* 	v1.7.4.2	2018/09/06 - 09:31:56: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:32:07: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:32:18: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:34:27: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:34:28: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:34:46: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:34:54: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:34:56: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:32: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:48: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:52: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:52: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:53: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:35:55: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:36:15: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:36:34: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:37:00: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:37:29: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:37:55: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:15: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:15: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:17: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:36: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:44: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:50: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:38:51: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:40:17: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:40:49: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:40:51: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:40:52: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:41:01: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:41:43: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:41:52: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:41:54: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:42:10: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:42:14: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:42:16: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:43:50: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:43:53: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:43:57: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:44:00: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:45:33: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:46:10: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:46:18: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:47:41: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:47:45: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:48:28: Shop not found at line 363 in file classes/shop/Shop.php
*ERROR* 	v1.7.4.2	2018/09/06 - 09:48:49: Shop not found at line 363 in file classes/shop/Shop.php
```

Prestashop configuration information: 
info_outline Configuratie informatie
Deze informatie moet verstrekt worden wanneer u een probleem op onze bugtracker of forum plaatst.

info_outline Servergegevens
Servergegevens Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Server softwareversie: Apache/2
PHP-versie: 7.2.8
Geheugenlimiet: 512M
Maximale uitvoeringstijd: 10000
Maximale bestandsgrootte voor uploads: 64M

info_outline Database informatie
MySQL versie: 10.2.16-MariaDB
MySQL-server: localhost
MySQL-naam: ****_pre781
MySQL-gebruiker: *****_pre781

Tabellen voorvoegsel: psc5_
MySQL-engine: InnoDB
MySQL-driver: DbPDO

info_outline Winkel informatie
PrestaShop-versie: 1.7.4.2
Winkel-URL: http://natureldeluxe.be/

Huidig gebruikte thema: ap_olay
info_outline E-mail configuratie
Mail methode: U gebruikt de PHP mail() functie.

info_outline Uw gegevens
Uw webbrowser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
info_outline Controleer uw configuratie
Verplichte parameters: Oké
Optionele parameters: Oké

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

The SSL option is enabled?

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
SSL in enabled yes.

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Thanks to enable SSL on all page option in the Shop Parameters / General page, check and feedback.

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
SSL is & was allready enabled on all pages.

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Did you make an upgrade or it is fresh install 1.7.4.2?
Thanks to check that the demo mode is disabled: https://github.com/PrestaShop/PrestaShop/blob/develop/config/defines.inc.php#L43

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
Hi it is a one click upgrade from PrestaShop 1.6.x to 1.7.4.2, demo mode is disabled

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Could you please try to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
I already did that several times... maybe this is something important: just after the upgrade our images where not visible in te front, this had something to do with friendly url... and SSL domain (I had www.natureldeluxe.be configurated as SSL domain) but this needed to be natureldeluxe.be (without www) I dont know why, this needed to be changed... this was the first error after upgrade...

**Comment by Prestashopnewbie** [comment]
Is there really no solution?

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards, Khouloud
