### ISSUE TITLE
Zip code error in 1.6.1.20

### ISSUE THREAD

**Issue by borisdifiore** [PrestaShop/PrestaShop#10310]
Hi all,
using Prestashop 1.6.1.20 I have a error for zip code validation. The costumer is correctly registered but he see an error in the zip code
All my settings are according to zip code NNNNN 
I need to have zip code for shipping
I checked all the solutions proposed on the forge but the problem persists.
Thank you in advance

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 7.2
![zip code error](https://user-images.githubusercontent.com/12604701/45152238-21546a00-b1d9-11e8-87c3-a0344fa314a7.png)

**Comment by khouloudbelguith** [comment]
Hi @borisdifiore,

I did not manage to reproduce the issue with the last version 1.6.1.20.
![image](https://user-images.githubusercontent.com/16067358/45152493-77251400-b1d1-11e8-8944-4746c0c8dc26.png)
Could you please try to re-import the Greece pack again in the Localization page and feedback.

Best regards, Khouloud

**Comment by borisdifiore** [comment]
Khouloud,
installed. It seems to work now.
Thank you 
You can close the issue
KR
Boris

**Comment by khouloudbelguith** [comment]
Hi @borisdifiore,

Thanks for your feedback.
Since it is fixed, I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud
