### ISSUE TITLE
Quelques onglets menus du BO ne se chargent pas et affiche: http 500 error

### ISSUE THREAD

**Issue by Marwazeinoo88** [PrestaShop/PrestaShop#10315]
**Describe the bug**
Je suis en mode multiboutique 
Depuis un moment, je rencontre une erreur dans le back office : 
Impossible de traiter cette demande via domaine.fr à l'heure actuelle.
HTTP ERROR 500

Cette erreur apparaît quand je clic sur certains onglets du menu du back-Office comme(produit, modules ou paramètre avancée) 
Et ce qui est bizarre c'est que j'ai pas cette erreur en mode Debeug , en fait le mode debeug ne donne rien et n'affiche pas une erreur et les onglet se chargent normalement, Mais l'erreur apparaît seulement quand le mode debeug est déactivé.

**Console log:**  
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**SERVEUR LOG ERROR**:
[error] (9)Bad file descriptor: apr_socket_accept: (client socket)  
**INFORMATIONS** 👍 Informations sur votre serveur Linux #1 SMP Thu Jan 4 16:43:57 MSK 2018 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.1.20

Limite de mémoire : 256M

Temps maximal d'exécution : 80

Taille max. pour envoi de fichiers : 200M

Version de PrestaShop : 1.7.3.0 
Merci d'avance pour votre aide!

**To Reproduce**
1. Go to '.menu BO..'
2. Click on '..PRODUCT..'
3. See error Impossible de traiter cette demande via domaine.fr à l'heure actuelle.
HTTP ERROR 500

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
restaShop version: N/APHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - apache version 
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!
PS: Please send your request in English.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
Some of the tab menu of my BO are not accessible as (  products, menu, advanced parameter..) and can not be loaded , instead i get this error:  "Impossible de traiter cette demande via domaine.fr à l'heure actuelle. HTTP ERROR 500"
I get this error Only when DEBEUG MODE is not active
When it is active , no error display! 
**Console log:**  
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
**SERVEUR LOG ERROR:**
Thu Sep 06 11:42:15 2018] [error] (9)Bad file descriptor: apr_socket_accept: (client socket)
**version** 👍 Apache/2.2.22
**Herbergeur**: phpnet
**Prestashop log**: no recent error
Thaks for your replay

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

About this error[ [error] (9)Bad file descriptor: apr_socket_accept: (client socket)], it is a server issue, maybe you need to upgrade the apache package, you need to check your host.
Thanks to check with your host & feedback.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
My host says it's an apache bug , and they could do nothing about it until the upgrade Apache 2.4 is available. But my host also says that this bug do not cause any dysfunction :(

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
That's why we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
the debeug mode report display 0 error , the error displays only when debeug mode is not active, so the page doesn't load :(( it's very frustrating i can't keep working on debeug mode for ever ! and i have no clue

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
Hi again, finally it's working! I just had to enable and able friendly urls so prestashop automatically generate .htaccess file 👍

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud
