### ISSUE TITLE
BO: Dragging (selecting text) over e.g. the order reference in order list, should not trigger clicking it.

### ISSUE THREAD

**Issue by mortenhartvig** [PrestaShop/PrestaShop#10317]
**Describe the bug**
When you try to copy text from the order list by dragging (selecting) the text, a click should not be triggered. The order/item should not be opened.

It seems, that there needs to be a preventDefault event on the dragStart/dragEnd javascript event. Only Click/touchEnd event should open the item in the list.

**To Reproduce**
1. Go to 'AdminOrders' controller (the order list)
2. Try to copy the order reference text using the mouse
3. The order will open up, as the drag event triggers a click (which it should not, as you are trying to copy text, not click an object)

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: 7.x

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

Thanks for your report.
I manage to reproduce the issue with the last version PS 1.7.4.2.
@marionf, what do you think, it is a bug or it is a normal behavior?

Best regards, Khouloud

**Comment by marionf** [comment]
It could be an improvement

**Comment by khouloudbelguith** [comment]
Hi,

I have the same issue with the branch 1.7.7.x
![image](https://user-images.githubusercontent.com/16067358/77511731-00627100-6e72-11ea-82bc-b41e3c910fa6.png)

Thanks!
