### ISSUE TITLE
Something is wrong with the checkbox - it can't be selected for the first time

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10319]
**Describe the bug**
In the catalog => Product page, when we try to select a product, it can't be selected for the first time, we need to click double click.

**To Reproduce**
1. Go to Catalog > Products
2. Click on Filter by categories and select a category
3. Click on the Reorder button
4. Select a product => it is not selected

1.7.4.2 => OK

**Screenshots**
https://drive.google.com/file/d/1g5FFOoH6qsvQE90BnBM-kkC2KXyRGsrR/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1
Browser: Chrome Version 65.0.3325.181

**Comment by khouloudbelguith** [comment]
Hi,

I did not manage to reproduce the issue with the branch develop 1.7.5.x
I will close the issue.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @marionf,

The issue persists again in the Branch 1.7.5.x.
https://drive.google.com/file/d/1ThPzOmCU5k2TrQikRA1_b_9NYzCyn0KF/view
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 
I can't reproduce it, what is your browser ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is Google Chrome Version 69.0.3497.81.
Thanks!

**Comment by marionf** [comment]
I have the same version and can't reproduce

**Comment by khouloudbelguith** [comment]
@marionf, I have this issue only if I select a category in product page list.
![image](https://user-images.githubusercontent.com/16067358/47075636-3f13e680-d1fd-11e8-9e73-f66f9fbdf305.png)
Thanks!

**Comment by marionf** [comment]
Yes, that's what I tried

**Comment by khouloudbelguith** [comment]
Hi @marionf,

You need to click on the reorder button, before selecting a product.
![image](https://user-images.githubusercontent.com/16067358/47076811-e5f98200-d1ff-11e8-871d-c492685e5f9f.png)
This button is displayed just for the first time.
Thanks!

**Comment by marionf** [comment]
Oh yes, thank you I can reproduce :)
