### ISSUE TITLE
I can not make changes in prestashop

### ISSUE THREAD

**Issue by AdriCruz** [PrestaShop/PrestaShop#10323]
Hello, suddenly I can not modificate nothing from my Prestashop Back Office (upload or save products, delete or activate modules, etc). In some of the messages put something like "this functionality has been disabled" I do not know what I can do, can you help me? Thank you very much!

Version:1.7.4.2

![problem_image](https://user-images.githubusercontent.com/43041205/45167681-ef9fcb00-b1f9-11e8-8694-e71e5098e833.jpg)

**Comment by khouloudbelguith** [comment]
Hi @AdriCruz,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by AdriCruz** [comment]
Done, here the feedback!

![screenshot_2018-09-06 php prestashop info](https://user-images.githubusercontent.com/43041205/45169739-85d5f000-b1fe-11e8-82b0-f2a26a4a78c4.png)

**Comment by khouloudbelguith** [comment]
Hi @AdriCruz,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by AdriCruz** [comment]
![consola](https://user-images.githubusercontent.com/43041205/45172507-d56bea00-b205-11e8-84fe-257a811d8e65.png)
[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/2357985/error_log.txt)

If you need more information please tell me.

**Comment by khouloudbelguith** [comment]
Hi @AdriCruz,

Could you please try to disable the anthemeblocks module, clear cache & feedback.

Best regards, Khouloud

**Comment by AdriCruz** [comment]
I can not disable anthemeblocks because I can not made any changes from BO. I have cleared cache. Nothing change.

**Comment by sarjon** [comment]
@AdriCruz make sure you have Demo mode disabled. 

You can disable it here https://github.com/PrestaShop/PrestaShop/blob/develop/config/defines.inc.php#L43

**Comment by AdriCruz** [comment]
@sarjon thank you so much, it was that!! Everything works now. Thanks @khouloudbelguith too for your help.

**Comment by khouloudbelguith** [comment]
Hi @AdriCruz,

Thanks for your feedback.
Feel free to open a new issue when needed.

Best regards, Khouloud
