### ISSUE TITLE
Mise à jour 1.7.4.2

### ISSUE THREAD

**Issue by ComptoirCarrelage** [PrestaShop/PrestaShop#10320]
Hello,
we have a problem with the update 1.7.4.2, it shows us these problems that I attach you in attachments.
Thanks for your help.
Loïc
![erreur de mise a 1 7 4 2](https://user-images.githubusercontent.com/43040202/45166239-d47f8c00-b1f6-11e8-8326-1519a11edeae.JPG)

**Comment by khouloudbelguith** [comment]
Hi @ComptoirCarrelage,

What is the exact version of the 1-click upgrade did you used.
From which previous version did you make the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by ComptoirCarrelage** [comment]
Hi  <https://github.com/ComptoirCarrelage> @ComptoirCarrelage,

What is the exact version of the 1-click upgrade did you used.

4.2.0
From which previous version did you make the upgrade?

1.7.3.3
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt

Il n’y  a pas de fichier  log  dans /autoupgrade/tmp/log.txt

Best regards, Khouloud

 

 

De : khouloudbelguith [mailto:notifications@github.com] 
Envoyé : jeudi 6 septembre 2018 17:10
À : PrestaShop/PrestaShop
Cc : ComptoirCarrelage; Mention
Objet : Re: [PrestaShop/PrestaShop] Mise à jour 1.7.4.2 (#10320)

 

Hi @ComptoirCarrelage <https://github.com/ComptoirCarrelage> ,

What is the exact version of the 1-click upgrade did you used.
From which previous version did you make the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @ComptoirCarrelage,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by ComptoirCarrelage** [comment]
Hello,

I managed to update, but when I go on the modules I get this error message :

Directory /home/comptoirwg/www/log is not writable

and when I do not put my shop in maintenance I have the same message.
I emptied the cache and put the site in debug mode, but it does not work.

Thanks
Best regards 
Loïc

**Comment by khouloudbelguith** [comment]
Hi @ComptoirCarrelage,

This is a permission issue.
You need to check your host.

Best regards, Khouloud

**Comment by ComptoirCarrelage** [comment]
Thanks
Loïc

**Comment by khouloudbelguith** [comment]
Hi @ComptoirCarrelage,

Thanks to check with them & feedback.

Best regards, Khouloud

**Comment by ComptoirCarrelage** [comment]
Hello,
we solved the problem by creating a log directory on the ftp.
Thank you
Loïc
ctc

**Comment by khouloudbelguith** [comment]
Hi @ComptoirCarrelage,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
