### ISSUE TITLE
Shipping costs calculation problem with discounts

### ISSUE THREAD

**Issue by melmelimel** [PrestaShop/PrestaShop#10325]
Bonjour,
Je suis sur 1.7.4.1. Et j'ai un souci de calcul des frais de port quand le client a un bon de réduction.
J'ai configuré les frais de port offerts à partir de 55.-
Mais quand le client a 60.- de produits et qu'il a un bon de 10.- par exemple, les frais de ports sont gratuits alors que le total est inférieur à 55. Il se base sur le total de 60.- et non de 50.

VALEUR PRODUITS : 60.-
DISCOUNT : 10.-
SHIPPING : 0.-
TOTAL : 50.-

Au lieu de ce qui devrait être juste : 

VALEUR PRODUITS : 60.-
DISCOUNT : 10.-
SHIPPING : 8.-
TOTAL : 58.-

Comment faire pour que le panier calcule sur le montant déduit des réductions et non sur la valeur des produits de base?

Merci pour votre aide!

**Comment by khouloudbelguith** [comment]
Hi @melmelimel,

Thanks to check in the conditions tab, if the shipping is included?
![image](https://user-images.githubusercontent.com/16067358/45172250-1b747e00-b205-11e8-949f-03a20fd09049.png)

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
HI @melmelimel,

Have you the same issue with this: #9540?

Best regards, Khouloud

**Comment by melmelimel** [comment]
Hi Khouloud, yes same issue,... :(

**Comment by khouloudbelguith** [comment]
Hi @melmelimel 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9540
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #9540
