### ISSUE TITLE
Filter by category tree on catalog page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10321]
**Describe the bug**
The tree of category is expanded by default, it should be collpsed
And currently collapse/expand option are not working

**To Reproduce**
1. Go to Catalog > Products
2. Click on Filter by categories
3. Tree is expanded instead of collapsed
4. Click on Collapse
5. Nothing happpens

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10375
