### ISSUE TITLE
Refresh js when new strore's upgraded to new version

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#10330]
I offer to add the version of the store to JS and maybe css, so when the store would be upgraded the customer's browser will upgrade JS (and maybe :) css) automatically.

` <script type="text/javascript" src="https://napompe.ru/themes/core.js" ></script>`
replace with
 `<script type="text/javascript" src="https://napompe.ru/themes/core.js?1742" ></script>`

I belive this one https://github.com/PrestaShop/PrestaShop/issues/10288 is related with cached JS.

It's easy to refresh cache on the desktop browser but on mobile it's much more complicated (for common user).

```
themes/classic/templates/_partials/javascript.tpl
{foreach $javascript.external as $js}
  <script type="text/javascript" src="{$js.uri}?1742" {$js.attribute}></script>
{/foreach}

I don't know how to insert version automatically.
```

**Comment by Quetzacoalt91** [comment]
I agree with you, this wouldn't be the first time we got this issue.

This trick is already implemented on the login.js script: https://github.com/PrestaShop/PrestaShop/blob/fe7796b1b7c20080fc1c5564f2e029726f4369f2/admin-dev/themes/default/template/controllers/login/header.tpl#L50

**Comment by khouloudbelguith** [comment]
@marionf, what do you think about this issue?
As @Quetzacoalt91 said, we can add automatically the PS version in javascript.tpl

**Comment by Quetzacoalt91** [comment]
I made a pull-request which follows this request. The version was hard-coded, and we had to manually update it on each release. From now, we follow the version registered in the Kernel.

**Comment by LedCloud** [comment]
I made the suggested changes to javascript.tpl and stylesheets.tpl. Now the links to scripts and css looks like that
```
...
...themes/core.js?v=1.7.4.2" ></script>
...
...themes/classic/assets/css/theme.css?v=1.7.4.2" type="text/css"
...
```
Great!
