### ISSUE TITLE
Updating product categories through CSV import

### ISSUE THREAD

**Issue by skipy** [PrestaShop/PrestaShop#10332]
Hi there! I am running PS  1.7.3 and I really want to update the product categories through CSV.
I put the category ID in the Categories column, but the categories remain the old ones.

Is there any solution to this? Thank you!

**Comment by khouloudbelguith** [comment]
Hi @skipy,

You need to enable the "Force all ID numbers" in the Import page.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by skipy** [comment]
Hi, @khouloudbelguith !
Thank you for your reply! The thing is that I actually activated that option with the force ID, but when I import the products it creates categories with the number ID instead of the category name.

**Comment by khouloudbelguith** [comment]
Hi @skipy,

In the categories column, have you tried to put the name of the category that you want to update instead of the ID?
Thanks to check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @skipy ,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
