### ISSUE TITLE
Demo order 2 data is wrong

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10333]
**Describe the bug**

When one installs a new shop, there are demo data loaded into the shop. Order 2 for John Doe contains 2 order rows, but the SQL data is wrong.

**To Reproduce**

Order 2 contains 2 ordered items:
- mug "today is a good day"
- poster "The adventure begins Framed poster" Size : 80x120cm

If you look at `ps_order_detail` you can see the 2nd item row has `product_attribute_id` 16.
However product "The adventure begins Framed poster" has indeed 3 combinations, but size 80x120cm is the 3rd combination and has SQL ID 18 instead of SQL ID 16.

So the BO order summary page `/admin/index.php?controller=AdminOrders&id_order=2` says the order item is "The adventure begins Framed poster" Size : 80x120cm but the SQL data says it is actually "The adventure begins Framed poster" Size : 40x60cm

PrestaShop version: `develop` branch (current 1.7.5)

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with the last version 1.7.4.2.
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment]
Relates to #9733
