### ISSUE TITLE
Style issues in back office

### ISSUE THREAD

**Issue by rokaszygmantas** [PrestaShop/PrestaShop#10339]
**Describe the bug**
Noticed a few issues related to style in back office: 

1. Help box popups are remaining in the old position when the content moves (e.g. when collapsing the side menu), making them look weird (https://prnt.sc/kroltr).
2. Help box popups are overlapping on top of the page header when scrolling down (https://prnt.sc/kromsm). This happens in all new BO pages.
3. Yes/No switches are overlapping on top of the page header when scrolling down (https://prnt.sc/kromdh). This happens in all new BO pages.

**To Reproduce**

For the help box position bug:
1. Go to 'Advanced parameters -> Performance'
2. Click on the question mark next to 'Cache' setting to open the help box.
3. Collapse the side menu.
4. See that the help box position is not precise.

For the overlapping elements bug:
1. Go to 'Advanced parameters -> Performance'
2. Click on the question mark next to 'Cache' setting to open the help box.
3. Scroll down until the opened help box is at the same level as the page header row.
4. See help box and yes/no switch on top of the header row. They should be hidden below it.

**Screenshots**
Added in the description.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @rokaszygmantas,

Thanks for your report, I manage to reproduce the issue with develop branch.
![image](https://user-images.githubusercontent.com/16067358/45219510-6e087580-b2ab-11e8-9afa-f636e1a341aa.png)
For the 1,3 & 4 issues existed in the stable version 1.7.4.2.
For the 2nd issue exists only in the develop branch.

Best regards, Khouloud

**Comment by CaptainYouz** [comment]
>Help box popups are remaining in the old position when the content moves (e.g. when collapsing the side menu), making them look weird (https://prnt.sc/kroltr).

Popup or small modal usually disappear when an other click event is trigger. I changed the behavior so that when resizing the side nav, it make the popup disappear.

**Comment by khouloudbelguith** [comment]
Hi,

Also, the "buttons appear on the top layer" issue exists in those pages:
1- invoices
2- stocks
3- Modules catalog #10460
4- Module Manager
5- localization
6- geolocation
7- order-preferences
8- product-preferences
9- preferences
10- Merchant Expertise
![image](https://user-images.githubusercontent.com/16067358/45631729-d7eb0100-ba9b-11e8-93e8-7df8d3d4b4c1.png)
11- performance
12- Administration
13- E-mail page: when SMTP parameters are checked

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
Fixed by #10436
