### ISSUE TITLE
Module cross-selling bug!!

### ISSUE THREAD

**Issue by Marwazeinoo88** [PrestaShop/PrestaShop#10344]
**Describe the bug**
Hello,
When i create a new product , and i try adding some related products , they never show on Front office ! 
Module : Vente croisée configured and active.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: 7.1.20
Version du logiciel serveur : Apache
Thème actif : classic

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

I did not manage to reproduce the issue with PS 1.7.4.2 / PS1.7.3.1 & the ps_crossselling v2.0.0.
![image](https://user-images.githubusercontent.com/16067358/45229803-3c050c80-b2c7-11e8-8125-846ccc4afc2b.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
[
![capture](https://user-images.githubusercontent.com/43037924/45231025-0bbf6d00-b2cb-11e8-8c57-7ce17d607994.PNG)
![capture07](https://user-images.githubusercontent.com/43037924/45231026-0bbf6d00-b2cb-11e8-8938-0125159e5075.PNG)

](url)
I need to associate products!
 in demo BO it's ok , but in FO, associated products don't show 
(Sorry for my english)

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Thanks for your feedback.
Same, I did not manage to reproduce the issue with the PS 1.7.4.2 /PS 1.7.3.1
Have you tried to contact the theme author?
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
Hi again,
I'm using classic  theme (theme by default of prestashop1.7)

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
There is no errors in my logs (server, php, javascript console ) debeug mode doesn't display errors..
PrestaShop version : 1.7.3.0
host: phpnet.org
screenshots: already sent
On the other hand i heard that module "cross-selling"on the version 1.7 is obviously bugging: the native modules for download are available 1 time out of 2 ... Have you please any idea if it's a bug ?

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Could you please check that you added in the related product section are not out of stock (ref:Cadie5415, ref:Cadie321) & feedback.

Best regards, Khouloud

**Comment by Marwazeinoo88** [comment]
Oh thank you very much, related product was not out of stock but disabled! thanks to you i've checked it.

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
