### ISSUE TITLE
low_stock_alert allow_null

### ISSUE THREAD

**Issue by lacrm** [PrestaShop/PrestaShop#10346]
Prestashop 1.7.4.2
`'allow_null'= true` in definition fields (classes/Product.php) for low_stock_alert
![image](https://user-images.githubusercontent.com/17384523/45227692-5e942700-b2c1-11e8-842e-81a32450867d.png)
NOT NULL in CREATE TABLE (install-dev/data/db_structure.sql)
![image](https://user-images.githubusercontent.com/17384523/45227791-a74be000-b2c1-11e8-8ee8-f37c851eaac1.png)

**Comment by khouloudbelguith** [comment]
Hi @lacrm,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @lacrm,

After fresh installation 1.7.4.2, in the structure of the ps_product_shop we have this
![image](https://user-images.githubusercontent.com/16067358/45301610-9abdc680-b511-11e8-9491-4556942b7109.png)
@eternoendless what do you think about his report?
Thanks!

Best regards, Khouloud
