### ISSUE TITLE
The search after switching to the second page of the product page may cause a problem.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10343]
**Describe the bug**

The search after switching to the second page of the product page may cause a problem.
Please see screen-record.

Best regards, Khouloud

**To Reproduce**
1. Go to BO => Products page =>  ( be sure that you have more than 20 products & Items per page=20)
2. Click on the second page
3. Search within the "name" field with this expression "copy"
5. We need to refresh the page => to get the correct result

**Screenshots**
https://drive.google.com/file/d/1w3dSH4ZfgibN7O3CyLp50kEZK7_Z0l5-/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I manage to reproduce this issue in the branch 1.7.5.x.
https://drive.google.com/file/d/1e7mIKkOtPgPvRSOTLuikMgnlfLn4illF/view

Best regards, Khouloud

**Comment by marionf** [comment]
It's fixed on 1.7.5.x
