### ISSUE TITLE
Table 'ps_accessory' already exists

### ISSUE THREAD

**Issue by laurentvannereau** [PrestaShop/PrestaShop#10354]
![prestashop1 7 4 2error](https://user-images.githubusercontent.com/5227047/45259321-9fdd2180-b3fc-11e8-89e5-3ba96a64accc.jpg)

I tried many times on 2 different servers, my server is using the latest Easy Apache 4

Prestashop 1.6 can be installed but Prestashop 1.7 cannot be installed, I have tried to install Prestashop 1.7.4 and 1.7.4.2

I always get the same error.

I have tried:
- to create a new account in my server and to install
- to install using different database prefixes
- to install using different DB names and users

I of course don't have any table in my database before trying to install

RESULTS:
It always block at 12% and tells me that the table PS_accessory already exists, well this is not true.
after getting the error I check the database and I can see that all tables were created but they have 0 data inside

**Comment by khouloudbelguith** [comment]
Hi @laurentvannereau,

1. Before the installation, could you please enable the mode dev.
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:
`define('_PS_MODE_DEV_', false);`
… and change it to:
`define('_PS_MODE_DEV_', true);`
2. During the installation, thanks to untick the box "Drop existing tables (mode dev)".
![image](https://user-images.githubusercontent.com/16067358/45284906-fe300000-b4e1-11e8-8bc1-d4739926b747.png)

PS: You have to be completely sure, that the database is empty.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by disarci** [comment]
Hi,

had the same problem,
db empty, and message at 12%

dev mode with drop table works well.

**Comment by matks** [comment]
Hi,

Can you please tell us what php version you are using ?

**Comment by khouloudbelguith** [comment]
Hi @disarci,

Thanks to follow this steps:

1. Login to your phpMyAdmin or wherever you can have a look at you database: delete all the tables, to make sure the database is empty.
2. Open the file prestashop > install > data > db_structure.sql in your editor (e.g. TextWrangler)
3. 
4. Replace all a.) with b.)
4.1 CREATE TABLE
4.1 CREATE TABLE IF NOT EXISTS
6. The error messages "table ps_[...] already exists" disappear. 

Thanks to check & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @laurentvannereau 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by luke-park** [comment]
This is clearly a bug and the recommended solution is to modify the internal code of Prestashop...  Seriously?  Why not just _fix_ the bug?

**Comment by PierreRambaud** [comment]
@luke-park We are waiting for your pull request :smiley_cat:

**Comment by wahono77** [comment]
this bug still exists until now. I can not install 1.7 version
