### ISSUE TITLE
Payplug IPN error(500) if Geolocation is active 

### ISSUE THREAD

**Issue by CristianCrispini** [PrestaShop/PrestaShop#10359]
**Describe the bug**

Payplug server will receive payments but the ipn response shows error 500 as result of the transaction. This will generate a new order with no status code(--) on Prestashop BO.

**To Reproduce**
1. Go to Prestashop BackOffice 
2. Click on **International** then **localization** then **Geolocation**
3. Download component for the geolocation and Install in the app folder
4. Activate **Geolocation by IP address**
5. Go to the shop and order something with PayPlug payment method 
4. See error on order page

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2.4
PayPlug version: 2.6.0 
PHP version: 5.6.37

**Comment by khouloudbelguith** [comment]
Hi @CristianCrispini,

The PayPlug module is not developed by Prestashop, have you tried to contact the theme author?
Thanks to check with them your issue and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @CristianCrispini,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
