### ISSUE TITLE
Module not display

### ISSUE THREAD

**Issue by Francky336** [PrestaShop/PrestaShop#10355]
Hi all, 
i use prestashop 1.7.4.2, all work in back office but module page don't work.
i have search many solution but no issue.
i load many modules by ftp but never display in BO, button instal module don't work and connect to markeplace.
let me know what is this problem or what is file need mod for prestashop reconize module
Thank for your help

![presta](https://user-images.githubusercontent.com/43107123/45262372-afb52f80-b415-11e8-8292-df6a69dfe66c.jpg)
![info presta](https://user-images.githubusercontent.com/43107123/45262378-ca87a400-b415-11e8-898e-fb0251b50f3f.jpg)

[BO 1.7.4.2.zip](https://github.com/PrestaShop/PrestaShop/files/2364054/BO.1.7.4.2.zip)

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Make sure you have Demo mode disabled.
You can disable it here https://github.com/PrestaShop/PrestaShop/blob/develop/config/defines.inc.php#L43
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
Hi @khouloudbelguith 
i have checked and it's disable "define('_PS_MODE_DEMO_', false);"
Thank's for your help.
Best regards Franck

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Francky336** [comment]
here my debug mode report "missing":

Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
fr-FR | AdminAdvparametersFeature | 1 | Never recompile template files | Never recompile template files
fr-FR | AdminAdvparametersFeature | 1 | Recompile templates if the files have been updated | Recompile templates if the files have been updated
fr-FR | AdminAdvparametersFeature | 1 | Force compilation | Force compilation
fr-FR | AdminAdvparametersFeature | 1 | File System | File System
fr-FR | AdminAdvparametersFeature | 1 | MySQL | MySQL
fr-FR | AdminAdvparametersFeature | 1 | Never clear cache files | Never clear cache files
fr-FR | AdminAdvparametersFeature | 1 | Clear cache everytime something has been modified | Clear cache everytime something has been modified

**Comment by Francky336** [comment]
here my debug mode report "defined":


Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
fr-FR | AdminAdvparametersFeature | 2 | Clear cache | Vider le cache
fr-FR | AdminAdvparametersFeature | 4 | Memcached via PHP::Memcache | Memcached par PHP::Memcache
fr-FR | AdminAdvparametersNotification | 4 | (you must install the [a]Memcache PECL extension[/a]) | (vous devez installer [a]l'extension Memcache PECL[/a])
fr-FR | AdminAdvparametersFeature | 4 | Memcached via PHP::Memcached | Memcached par PHP::Memcached
fr-FR | AdminAdvparametersNotification | 4 | (you must install the [a]Memcached PECL extension[/a]) | (vous devez installer [a]l'extension Memcached PECL[/a])
fr-FR | AdminAdvparametersFeature | 4 | APC | APC
fr-FR | AdminAdvparametersNotification | 4 | (you must install the [a]APC PECL extension[/a]) | (vous devez installer [a]l'extension APC PECL[/a])
fr-FR | AdminAdvparametersFeature | 4 | Xcache | Xcache
fr-FR | AdminAdvparametersNotification | 4 | (you must install the [a]Xcache extension[/a]) | (vous devez installer [a]l'extension Xcache[/a])
fr-FR | AdminNavigationMenu | 1 | Performance | Performances
fr-FR | AdminGlobal | 1 | Help | Aide
fr-FR | AdminAdvparametersFeature | 1 | Smarty | Smarty
fr-FR | AdminAdvparametersFeature | 1 | Template compilation | Compilation des templates
fr-FR | AdminAdvparametersFeature | 1 | Cache | Cache
fr-FR | AdminAdvparametersFeature | 1 | Should be enabled except for debugging. | Devrait être activé sauf pour les tests et debug.
fr-FR | AdminGlobal | 12 | No | Non
fr-FR | AdminGlobal | 12 | Yes | Oui
fr-FR | AdminAdvparametersFeature | 1 | Multi-front optimizations | Synchronisation multi-serveurs
fr-FR | AdminAdvparametersHelp | 1 | Should be enabled if you want to avoid to store the smarty cache on NFS. | À activer si vous voulez éviter de stocker le cache smarty sur NFS.
fr-FR | AdminAdvparametersFeature | 1 | Caching type | Type de mise en cache
fr-FR | AdminActions | 6 | Save | Enregistrer
fr-FR | AdminAdvparametersFeature | 2 | Debug mode | Mode debug
fr-FR | AdminAdvparametersFeature | 1 | Disable non PrestaShop modules | Désactiver les modules non développés par PrestaShop
fr-FR | AdminAdvparametersFeature | 1 | Enable or disable non PrestaShop Modules. | Activer ou désactiver les modules non développés par PrestaShop.
fr-FR | AdminAdvparametersFeature | 1 | Disable all overrides | Désactiver toutes les surcharges
fr-FR | AdminAdvparametersFeature | 1 | Enable or disable all classes and controllers overrides. | Activer ou désactiver toutes les surcharges des classes et des contrôleurs.
fr-FR | AdminAdvparametersHelp | 1 | Enable or disable debug mode. | Activer ou désactiver le mode de débogage.
fr-FR | AdminAdvparametersFeature | 1 | Optional features | Fonctionnalités désactivables
fr-FR | AdminAdvparametersHelp | 1 | Some features can be disabled in order to improve performance. | Plusieurs fonctionnalités peuvent être désactivées afin d'optimiser les performances.
fr-FR | AdminGlobal | 1 | Combinations | Déclinaisons
fr-FR | AdminAdvparametersHelp | 1 | Choose "No" to disable Product Combinations. | Choisissez "Non" pour désactiver les déclinaisons de produits.
fr-FR | AdminAdvparametersHelp | 1 | You cannot set this parameter to No when combinations are already used by some of your products | Vous ne pouvez pas définir ce paramètre à "Non" si certains de vos produits utilisent déjà des déclinaisons.
fr-FR | AdminGlobal | 1 | Features | Caractéristiques
fr-FR | AdminAdvparametersHelp | 1 | Choose "No" to disable Product Features. | Choisissez "Non" pour désactiver les caractéristiques de produits.
fr-FR | AdminAdvparametersFeature | 1 | Customer groups | Groupes de clients
fr-FR | AdminAdvparametersHelp | 1 | Choose "No" to disable Customer Groups. | Choisissez "Non" pour désactiver les groupes de clients.
fr-FR | AdminAdvparametersFeature | 1 | CCC (Combine, Compress and Cache) | CCC (Concaténation, Compression et mise en Cache)
fr-FR | AdminAdvparametersHelp | 1 | CCC allows you to reduce the loading time of your page. With these settings you will gain performance without even touching the code of your theme. Make sure, however, that your theme is compatible with PrestaShop 1.4+. Otherwise, CCC will cause problems. | CCC vous permet de réduire le temps de chargement de vos pages en Front Office. Avec ces fonctionnalités, vous allez gagner en performances sans modifier le code source de votre Front Office. Soyez sûr que votre thème est compatible avec PrestaShop 1.4+. Dans le cas contraire, CCC peut causer des problèmes.
fr-FR | AdminAdvparametersFeature | 1 | Smart cache for CSS | "Smart cache" pour les feuilles de style
fr-FR | AdminAdvparametersFeature | 1 | Smart cache for JavaScript | "Smart cache" pour le code JavaScript
fr-FR | AdminAdvparametersFeature | 1 | Apache optimization | Optimisation Apache
fr-FR | AdminAdvparametersHelp | 1 | This will add directives to your .htaccess file, which should improve caching and compression. | En cochant cette case, votre fichier .htaccess sera complété automatiquement avec des directives améliorant le cache et la compression.
fr-FR | AdminAdvparametersFeature | 1 | Media servers (use only with CCC) | Serveurs de média (utilisé uniquement lorsque CCC est activé)
fr-FR | AdminAdvparametersFeature | 1 | You must enter another domain, or subdomain, in order to use cookieless static content. | Vous devez mettre un autre domaine ou sous-domaine, afin d'utiliser du contenu statique sans cookie.
fr-FR | AdminAdvparametersFeature | 1 | Media server #1 | Serveur de média n°1
fr-FR | AdminAdvparametersHelp | 1 | Name of the second domain of your shop, (e.g. myshop-media-server-1.com). If you do not have another domain, leave this field blank. | Nom du deuxième domaine de votre boutique, (par exemple, myshop-media-server-1.com). Si vous n'avez pas un autre domaine, laisser ce champ vide
fr-FR | AdminAdvparametersFeature | 1 | Media server #2 | Serveur de média n°2
fr-FR | AdminAdvparametersHelp | 1 | Name of the third domain of your shop, (e.g. myshop-media-server-2.com). If you do not have another domain, leave this field blank. | Nom du troisième domaine de votre boutique, (par exemple, myshop-media-server-1.com). Si vous n'avez pas un autre domaine, laisser ce champ vide
fr-FR | AdminAdvparametersFeature | 1 | Media server #3 | Serveur de média n°3
fr-FR | AdminAdvparametersHelp | 1 | Name of the fourth domain of your shop, (e.g. myshop-media-server-3.com). If you do not have another domain, leave this field blank

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Did you follow these steps?
[To turn on the Debug mode on PrestaShop 1.7, follow these steps:
Got to Advanced Parameters > Performance
In the Debug Mode section, set “Debug Mode” to “Yes”.
Click the “Save” button.]

Best regards, Khouloud

**Comment by Francky336** [comment]
yes debug mode is active

**Comment by khouloudbelguith** [comment]
@Francky336  There is no exception displayed in the modules page? There are no errors in the php_log file?

**Comment by Francky336** [comment]
here missing in module page :
Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
fr-FR | AdminActions | 71 | Disable mobile | Disable mobile
fr-FR | AdminActions | 6 | Enable mobile | Enable mobile

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Could you please check if the memcached server is running & feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
i haven't memcached server

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

This error is displayed in your debug mode report "defined":
![image](https://user-images.githubusercontent.com/16067358/45292721-52dd7600-b4f6-11e8-88f1-a6cc14b34ae9.png)
Could you please check the issue with your host and feedback.

PS: Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
i have cieared the 2 folder, but alredy load module, here report "defined"


Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
fr-FR | AdminNotificationsError | 1 | You do not have permission to add this. | Vous n'avez pas les droits suffisants pour l'ajout.
fr-FR | AdminModulesFeature | 3 | Upload a module | Installer un module
fr-FR | AdminModulesFeature | 3 | Connect to Addons marketplace | Se connecter à la marketplace Addons
fr-FR | AdminModulesFeature | 1 | Manage installed modules | Gérer les modules installés
fr-FR | AdminGlobal | 1 | Help | Aide
fr-FR | AdminModulesNotification | 1 | You need to select at least one module to use the bulk action. | Vous devez sélectionner au moins un module pour déclencher cette action.
fr-FR | AdminModulesNotification | 1 | The action "[1]" is not available, impossible to perform your request. | L'action "[1]" n'est pas disponible, impossible d'exécuter votre requête.
fr-FR | AdminModulesNotification | 1 | The action [1] is not available for module [2]. Skipped. | L'action [1] n'est pas disponible pour le module [2]. Ignorée.
fr-FR | AdminModulesFeature | 1 | Bulk action confirmation | Confirmation de l'action de masse
fr-FR | AdminModulesNotification | 1 | You are about to [1] the following modules: | Vous êtes sur le point de [1] les modules suivants :
fr-FR | AdminModulesFeature | 78 | Optional: delete module folder after uninstall. | Optionnel : supprimer le dossier du module après la désinstallation.
fr-FR | AdminActions | 228 | Cancel | Annuler
fr-FR | AdminModulesFeature | 1 | Yes, I want to do it | Oui, je veux le faire
fr-FR | AdminModulesFeature | 1 | Module verification | Vérification de module
fr-FR | AdminGlobal | 1 | Module | Module
fr-FR | AdminModulesFeature | 1 | Author | Auteur
fr-FR | AdminGlobal | 1 | Status | État
fr-FR | AdminModulesFeature | 1 | Back to modules list | Retour à la liste des modules
fr-FR | AdminModulesFeature | 2 | Proceed with the installation | Continuer l'installation
fr-FR | AdminModulesFeature | 1 | Buy module | Acheter le module
fr-FR | AdminModulesFeature | 1 | Link your shop to your Addons account to automatically receive important updates for the modules you purchased. Don't have an account yet? | Liez votre boutique à votre compte Addons : vos modules achetés seront automatiquement importés. Vous n'avez pas encore de compte ?
fr-FR | AdminModulesFeature | 1 | Sign up now | Inscrivez-vous
fr-FR | AdminGlobal | 1 | Email address | Adresse e-mail
fr-FR | AdminGlobal | 1 | Password | Mot de passe
fr-FR | AdminGlobal | 1 | Remember me | Se souvenir de moi
fr-FR | AdminActions | 1 | Let's go! | C'est parti !
fr-FR | AdminGlobal | 1 | Forgot your password? | Mot de passe oublié ?
fr-FR | AdminModulesFeature | 1 | Confirm logout | Confirmer la déconnexion
fr-FR | AdminModulesNotification | 1 | You are about to log out your Addons account. You might miss important updates of Addons you've bought. | Vous êtes sur le point de vous déconnecter de votre compte Addons. Vous pourriez rater d'importantes mises à jour pour les modules que vous avez achetés.
fr-FR | AdminModulesFeature | 1 | Yes, log out | Oui, me déconnecter
fr-FR | AdminModulesFeature | 1 | Drop your module archive here or [1]select file[/1] | Glissez l'archive de votre module ici ou [1]sélectionnez un fichier[/1]
fr-FR | AdminModulesHelp | 1 | Please upload one file at a time, .zip or tarball format (.tar, .tar.gz or .tgz). | Vous pouvez charger un fichier à la fois, au format .zip ou tarball (.tar, .tar.gz or .tgz).
fr-FR | AdminModulesHelp | 1 | Your module will be installed right after that. | Votre module sera installé juste après.
fr-FR | AdminModulesNotification | 1 | Installing module... | Installation du module...
fr-FR | AdminModulesNotification | 1 | It will close as soon as the module is installed. It won't be long! | La fenêtre disparaitra dès que le module sera installé, dans un instant !
fr-FR | AdminModulesNotification | 1 | Module installed! | Module installé !
fr-FR | AdminActions | 42 | Configure | Configurer
fr-FR | AdminModulesNotification | 1 | Oops... Upload failed. | Aïe... le chargement a échoué.
fr-FR | AdminModulesHelp | 1 | What happened? | Que s'est-il passé ?
fr-FR | AdminActions | 1 | Try again | Réessayer
fr-FR | AdminActions | 1 | Search | Rechercher
fr-FR | AdminModulesFeature | 1 | All Categories | Toutes les catégories
fr-FR | AdminModulesFeature | 2 | Show all modules | Voir tous les modules
fr-FR | AdminModulesFeature | 1 | Enabled Modules | Modules activés
fr-FR | AdminModulesFeature | 1 | Disabled Modules | Modules désactivés
fr-FR | AdminModulesHelp | 1 | Search modules: keyword, name, author... | Chercher un module : mot-clé, nom, auteur...
fr-FR | AdminGlobal | 1 | Bulk Actions | Actions groupées
fr-FR | AdminActions | 78 | Uninstall | Désinstaller
fr-FR | AdminActions | 73 | Disable | Désactiver
fr-FR | AdminActions | 6 | Enable | Activer
fr-FR | AdminActions | 78 | Reset | Réinitialiser
fr-FR | AdminModulesFeature | 1 | Enable Mobile | Activer sur mobile
fr-FR | AdminModulesFeature | 1 | Disable Mobile | Désactiver sur mobile
fr-FR | AdminActions | 1 | Sort by | Tri
fr-FR | AdminGlobal | 1 | Name | Nom
fr-FR | AdminModulesFeature | 1 | Last access | Dernière utilisation
fr-FR | AdminModulesFeature | 1 | %nbModules% installed modules | %nbModules% modules installés
fr-FR | AdminModulesFeature | 1 | Installed modules | Modules installés
fr-FR | AdminModulesHelp | 1 | These are all the modules you’ve added to your shop, either by buying it from PrestaShop Addons, or by uploading it directly. | Vous trouverez ici tous les modules que vous avez ajoutés à votre boutique, soit en les achetant sur notre marketplace Addons, soit en les chargeant directement.
fr-FR | AdminModulesFeature | 77 | v%version% - by %author% | v%version% - par %author%
fr-FR | AdminModulesFeature | 77 | Toggle Dropdown | Ouvrir/fermer la liste déroulante
fr-FR | AdminModulesFeature | 77 | Uninstall module? | Désinstaller le module ?
fr-FR | AdminModulesNotification | 77 | You are about to uninstall %moduleName% module. | Vous êtes sur le point de désinstaller le module %moduleName%.
fr-FR | AdminModulesNotification | 77 | This will disable the module and delete all its files. For good. | Cela va désactiver le module et supprimer tous ses fichiers, pour de bon.
fr-FR | AdminModulesNotification | 154 | This action cannot be undone. | Cette action est irréversible.
fr-FR | AdminModulesFeature | 77 | Yes, uninstall it | Oui, désinstaller
fr-FR | AdminModulesFeature | 72 | Disable module? | Désactiver le module ?
fr-FR | AdminModulesNotification | 72 | You are about to disable %moduleName% module. | Vous êtes sur le point de désactiver le module %moduleName%.
fr-FR | AdminModulesNotification | 72 | Your current settings will be saved, but the module will no longer be active. | Votre configuration actuelle sera sauvegardée, mais le module ne sera plus actif.
fr-FR | AdminModulesFeature | 72 | Yes, disable it | Oui, le désactiver
fr-FR | AdminModulesFeature | 77 | Reset module? | Réinitialiser le module ?
fr-FR | AdminModulesNotification | 77 | You're about to reset %moduleName% module. | Vous êtes sur le point de réinitialiser le module %moduleName%.
fr-FR | AdminModulesNotification | 77 | This will restore the defaults settings. | Cela va rétablir les paramètres par défaut.
fr-FR | AdminModulesFeature | 77 | Yes, reset it | Oui, réinitialiser
fr-FR | AdminModulesFeature | 1 | %nbModules% built-in modules | %nbModules% modules intégrés
fr-FR | AdminModulesFeature | 1 | Built-in modules | Modules intégrés
fr-FR | AdminModulesHelp | 1 | These modules from PrestaShop are preinstalled when you set-up your shop. They cover the basics of e-commerce and comes for free. | Ces modules provenant de PrestaShop sont pré-installés à l'installation de votre boutique. Ils couvrent les bases de l'e-commerce et sont gratuits.
fr-FR | AdminModulesFeature | 59 | Read More | En savoir plus
fr-FR | AdminModulesFeature | 1 | %nbModules% theme modules | %nbModules% modules de thème
fr-FR | AdminModulesFeature | 1 | Theme modules | Modules du thème
fr-FR | AdminModulesHelp | 1 | Each theme you install will come with its own set of modules. You’ll find here all the modules related to your active theme. | Chaque thème que vous installez est fourni avec son propre lot de modules. Vous trouverez ici tous les modules liés à votre thème actif.
fr-FR | AdminGlobal | 1 | Loading...

**Comment by Francky336** [comment]
and missing report:


Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
fr-FR | AdminActions | 71 | Disable mobile | Disable mobile
fr-FR | AdminActions | 6 | Enable mobile | Enable mobile

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

What is the exact name of this module?

Best regards, Khouloud

**Comment by Francky336** [comment]
colissimo simplicte or other, alredy not possible install

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
when i load this phppsinfo, it"s a file open and not dispaly value, i have use oher phpinfo:
memory_limit = -1 but i force it to 128 in index.php boutique
[phpinfo.pdf](https://github.com/PrestaShop/PrestaShop/files/2366913/phpinfo.pdf)

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

It is recommended to use 256MB =>  memory_limit
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
Hi @khouloudbelguith ,
with 256MB same problem.
I have alredy this warning :


WARNING                                                 10:54:31 | translation | Translation not found.                                   Hide context                                             [▼   "id" => "Disable mobile"   "domain" => "AdminActions"   "locale" => "fr-FR" ]
-- | -- | --


Best Regards franck

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Could you please try to navigate to the BO => IMPROVE => International => Translations => Please select the language you want to add or update( french) and click on "Add or update a language".
Thanks to clear cache, check, and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
Hi @khouloudbelguith ,

i have tried but not solve. I have reinstall prestashop and already same problem. i have try add my module in folder module/design.zip and add name in config file. module was installed but i can't add other module after this. if upload button not work i search php command line for upload it manually, save time.

Best regards
Franck

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

In the modules folder, you don't need to add the zip folder, you should unzip it and copy paste the folder of this module into the path Project_Folder/modules/
Then, you should search for it in the selection Tab & install it.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Francky336** [comment]
it's the first test i do,  and no display module in the list , clear cache not work too. module never display and upload button never work

Best regards Franck

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Could you please provide me the credentials of your shop to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks & best regards, Khouloud

**Comment by Francky336** [comment]
mail was sent
BR
Franck

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

I just received the email.
I will check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @Francky336,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards, Khouloud
