### ISSUE TITLE
Traslation module - Files can´t be written

### ISSUE THREAD

**Issue by Sergio-Fourwinds** [PrestaShop/PrestaShop#10357]
**Describe the bug**
The native module for traslations generates an error explaining the file CustomerAccountLink can´t be written due file´s permission. After checking the bugtracker I found a solution: http://forge.prestashop.com/browse/BOOM-4443

The error message has disappeared, anyway the module doesn´t load. So can´t be modified the traslations

**To Reproduce**
1. I go to international>Traslations
2. Choose Theme traslations>Alysum(My bought theme)>Spanish
3. Backoffice starts loading the traslations, but never ends

**Screenshots**
You can check the error in the Link from the last solution for this problem, is exactly the same just with ES-es instead FR-fr, appling the solution from the link doesnt appears the error message, and just keep loading.

Symfony error
![image](https://user-images.githubusercontent.com/43099430/45263364-383ccb80-b428-11e8-8f06-ef30cb85e3fa.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.17

**Comment by khouloudbelguith** [comment]
Hi @Sergio-Fourwinds,

Thanks to export the language from the translation page, Copy the file the file generated into the translation file of your theme according to this documentation: http://build.prestashop.com/howtos/translation/how-to-translate-your-theme/#case-2:-you-are-creating-new-strings-in-files-that-already-exist-in-the-default-theme, clear cache from your shop, your browser & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @Sergio-Fourwinds,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
