### ISSUE TITLE
Prestashop installation

### ISSUE THREAD

**Issue by Marg88** [PrestaShop/PrestaShop#10367]
PrestaShop version: 1.7

Hello,
I try to install Prestashop but when I'm on my localhost the auto-installer begin to load but at the beginning an error is indicated like you can see on the picture in attachment : 
"An error has occured: 
You need to grant write permissions for PHP on the following directory: /Users/lisecreationspei/Site/papa"
It's my folder with Prestashop 1.7 files.
I don't know what I need to do to solve my problem. 
Can you help me ?

BR,

Marg

<img width="1086" alt="capture d ecran 2018-09-10 a 18 44 15" src="https://user-images.githubusercontent.com/42941368/45304668-a1583800-b529-11e8-86ba-ef354dd8b9f0.png">

**Comment by khouloudbelguith** [comment]
Hi @Marg88,

Thanks for your report.
It is a permission issue.
Thanks to follow these steps:
1) Set up your database
2) Download Prestashop and extract
3) Upload Prestashop to your server using FTP
4) Change file permissions of all directories to 777 using your FTP software. In Filezilla, this is done by:
File permissions >777>tick box to do it for all subdirectories> choose directories only
 5) Go to the website in a browser and follow instructions as normal
6) Delete the install folder
7) Rename ‘admin’ folder and record the new name

Thanks to check & feedback.

Best regards, Khouloud

**Comment by Marg88** [comment]
Thank you very much, it's work :)

Kind regards

Marg

**Comment by khouloudbelguith** [comment]
Hi @Marg88,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud

**Comment by pedroscow1** [comment]
Hello.

I have an identical problem but a little bit different.

When I try to install prestashop, I see this: 
https://snag.gy/lMzpXR.jpg

I tried to change file permissions but still with the same issue.

I tried do upload the files in a different way, already unziped but appear this too: https://snag.gy/We26VM.jpg

Thanks,
Pedro

**Comment by khouloudbelguith** [comment]
@Marg88, you need to install the PHP zip extension on your server, it is required on PrestaShop.
Thanks!

**Comment by pedroscow1** [comment]
> @Marg88, you need to install the PHP zip extension on your server, it is required on PrestaShop.
> Thanks!

Thanks, it worked! However, during the installation, it happened another error: https://snag.gy/pmXGVi.jpg

:(

**Comment by khouloudbelguith** [comment]
Hi @pedroscow1,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

- Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
- Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
- Now you can view all of the information about PHP for your server for that particular directory.

 ![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by pedroscow1** [comment]
Hello @khouloudbelguith

It's being hard... I already improve all requirements: http://www.webspareparts.pt/phppsinfo.php

But the installation continues giving the error... I don't know what more can I do.

**Comment by khouloudbelguith** [comment]
@Marg88, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

**Comment by khouloudbelguith** [comment]
Hi @Marg88,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
