### ISSUE TITLE
Can't sort Reference in Stock management PS 1.7.4.2

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10369]
Stock management function

Sort order "REFERENCE" doesn't work. I can't see what kind of order I'll get. See demo_8 as reference. N/A continues and I have a couple of more demo_x.

![skarmavbild 2018-09-10 kl 19 01 25](https://user-images.githubusercontent.com/42907000/45312330-12005400-b52c-11e8-8f5e-57b19d8d7ce7.png)
**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/13tLxDqSunx0isOcuk1lHy6mRI7EOgO4O/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Could it be that N/A isn't regarded as "N"?

If I test with "A sample" on one product and demo_10 the sort order will be A sample at the top and demo_10 almost at the end.
![skarmavbild 2018-09-12 kl 18 10 18](https://user-images.githubusercontent.com/42907000/45438484-9206f500-b6b7-11e8-969f-067103267b05.png)
![skarmavbild 2018-09-12 kl 18 09 54](https://user-images.githubusercontent.com/42907000/45438483-9206f500-b6b7-11e8-8e2f-7e23839f5a96.png)

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

Yes N/A regerded as N.
It is OK.
![image](https://user-images.githubusercontent.com/16067358/45484520-b2d15800-b754-11e8-87f0-26a21b0beff5.png)
![image](https://user-images.githubusercontent.com/16067358/45484571-d98f8e80-b754-11e8-8239-8694d5028d13.png)

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Notice that I have demo_10 in between N/A. Since I don't use this feature I'll guess I'll come back when this will annoy me.

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

I did not manage to reproduce the issue with PS 1.7.4.2.
Can I close the issue?

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Yes, close it :)

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

Thanks for your feedback.

Best regards, Khouloud
