### ISSUE TITLE
Code promo non pris en compte pour les produits virtuels

### ISSUE THREAD

**Issue by juilila** [PrestaShop/PrestaShop#10362]
**Describe the bug**
Sur la dernière version de prestashop 1.7.4.2 les codes promo ne sont pas appliqués sur les produits virtuels

**To Reproduce**
Installer la version 1.7.4.2
Créer un produit virtuel
Créer une promotion
Appliquer la promo dans le panier
Total Panier non mis à jour

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![bugpanier](https://user-images.githubusercontent.com/42962850/45293133-94225580-b4f7-11e8-902d-9852a3933c58.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7

Résolu en override mais je ne sais si ça affecte autre chose
Classes/ Cart.php  Ligne 1860 
J'ai rmeplacé cette la ligne $type = Cart::BOTH_WITHOUT_SHIPPING; par celle la  $type = Cart::BOTH;

        if ($virtual && $type == Cart::BOTH) {
            //$type = Cart::BOTH_WITHOUT_SHIPPING;
            $type = Cart::BOTH;
        }

**Comment by khouloudbelguith** [comment]
Hi @juilila, 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10264
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #10264
