### ISSUE TITLE
 CData section not finished Change the product prices massivelyYou can change in must_have_module_list.xml file

### ISSUE THREAD

**Issue by shokhashaykh** [PrestaShop/PrestaShop#10364]
Modules Error in Prestashop Admin Panel

4 errors

    Error found : CData section not finished Change the product prices massivelyYou can change in must_have_module_list.xml file.
    Error found : Premature end of data in tag additional_description line 1 in must_have_module_list.xml file.
    Error found : Premature end of data in tag module line 1 in must_have_module_list.xml file.
    Error found : Premature end of data in tag modules line 1 in must_have_module_list.xml file.

Can anyone help me how to fix it?

**Additionnal information**
PrestaShop version:  1.6.1.6

**Comment by khouloudbelguith** [comment]
Hi @shokhashaykh,

Thanks to delete the must_have_modules_list.xml file into the path PROJECT_FOLDER/confix/xml, check & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @shokhashaykh,

You need to delete cache from your shop & your browser.
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
