### ISSUE TITLE
Bug on deleteing product with customization

### ISSUE THREAD

**Issue by ndkdesign** [PrestaShop/PrestaShop#10379]
**Describe the bug**
When cart has a same products multiple times with different customizations, if you try to delete one both are deleted.
deletion only take care about id_product and id_attribute

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7

**Comment by MathiasReker** [comment]
I did not manage to reproduce. Can you send a screen record?

**Comment by ndkdesign** [comment]
Did you try with a same product with 2 différents customization? Le 11 sept. 2018 10:08 PM, Mreker <notifications@github.com> a écrit :I did not manage to reproduce. Can you send a screen record?

**Comment by MathiasReker** [comment]
Yes

**Comment by MathiasReker** [comment]
Can you reproduce your issue on a fresh install?

**Comment by ndkdesign** [comment]
is it possible to have access to product on front office on your test environement ?

hendrik masson
postmaster@ndk-design.fr

**Comment by khouloudbelguith** [comment]
Hi @ndkdesign,

As @Mreker said, I did not manage to reproduce the issue with the last version 1.7.4.2.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by ndkdesign** [comment]
Hello sorry for loose time i find problem into an override on my shop.

hendrik masson
postmaster@ndk-design.fr

**Comment by khouloudbelguith** [comment]
Hi @ndkdesign,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
