### ISSUE TITLE
Bad function in Inventory

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#10386]
**Describe the bug**
I add 6 combinations -> Size: S,M,L with Color: Fucsia, White
In only 3 of this combinations, I have 1 in stock in: This way have stock = 3 but appears 7 in total

**To Reproduce**
1. Create a product "xxx" with combinations
2. Create a 3x2 combinations
3. Stock in 1 only in 3 of this combinations
4. Save and go to product list in BO
5. View the total Stock

**Screenshots**
![combinaciones](https://user-images.githubusercontent.com/16818257/45393044-7e4c8780-b600-11e8-9a67-294226c5e4cf.png)
----------------------------------------------------- TOTAL -------------------------------------------------
![captura1](https://user-images.githubusercontent.com/16818257/45393056-89071c80-b600-11e8-863c-263644d117aa.png)

------------- IT'S ONLY BAD DISPLAY IN PRODUCT LIST IN BO, I DONT KNOW IF THIS QTY IS IN THE DB OR ITS A BAD ACCOUNT IN THE VIEW------------------------------------------------------------------------
![captura de pantalla de 2018-09-11 20-50-50](https://user-images.githubusercontent.com/16818257/45393926-a4742680-b604-11e8-8b7a-f17aec6f1cec.png)

**Additionnal information**
Versión de PrestaShop: 1.7.4.2
info_outline Información del servidor
Información del servidor Linux #1 SMP Wed Oct 11 15:51:10 EDT 2017 x86_64

Versión del software del servidor: Apache

Versión PHP: 7.2.9

Límite de memoria: 256M

Tiempo máx. de ejecución: 300

Tamaño máx. para la subida de archivos: 32M

Información de la base de datos
Versión de MySQL: 10.1.35-MariaDB-cll-lve

Prefijo de las tablas: ps_

Motor MySQL: InnoDB

Controlador MySQL: DbPDo

Tus datos
Su navegador: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

Comprueba tu configuración
Parámetros requeridos: OK

Parámetros opcionales: OK

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record: https://drive.google.com/file/d/1teS3dUBZaLcSxgil8O9uFJGBAlSVMbYw/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by TecnoHands** [comment]
Hi, I have proof for this fatal mistake in the manage of the stock.
Add a video, and screen captures of db tables, BO list.
After Video - Dont have combinations and the stock is 7 for the others testings.....
![after video](https://user-images.githubusercontent.com/16818257/45491016-0173f780-b73f-11e8-8d53-ca1ab7e41f7b.png)

VIDEO:
https://drive.google.com/open?id=1dnFf-E4-dmdGSDerFkxR59k2IQDVhlCu

The product in ps_product Table is id 6 (This capture is non combinations)
![bd table product non combinations product id 6](https://user-images.githubusercontent.com/16818257/45491122-47c95680-b73f-11e8-811f-0b97c8abce4c.png)

Table ps_stock_available after add combinations
![table ps_stock_available after add combinations](https://user-images.githubusercontent.com/16818257/45491165-64658e80-b73f-11e8-86f3-4d77aef87081.png)

TABLE ps_stock_available after deleting combinations 
![table ps_stock_available after deleting combinations](https://user-images.githubusercontent.com/16818257/45491180-70e9e700-b73f-11e8-96ff-98317fde8788.png)

I have a fresh install, and my products imported with a excel.
[Listado_Productos.xlsx](https://github.com/PrestaShop/PrestaShop/files/2379482/Listado_Productos.xlsx)

Dont import combinations in the excel.. and have this BUG.

**Comment by TecnoHands** [comment]
The bug is in manage the stock of the combinations... When you select the non combination product, the stock in the table ps_stock_available use the quantity column, This is ok.
But when you delete the combinations, DONT UPDATE THE Number to 0 in the ps_stock_available 

Pls. Check well the issues. This is a important bug.

**Comment by TecnoHands** [comment]
Prestashop dont delete of this table the combination when you deleting in the BO....
For the first add of combinations, work well. But if you delete them, and create others combinations Having the error.

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

I attached a video record: 
https://drive.google.com/file/d/1eF3ESnXqOX5MrkhoBiwcoTdJs3joa70a/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by TecnoHands** [comment]
Hi!!, sorry, I truncate all tables ps_stock try again and work fine.. 
If any other people have this error, truncate all stock tables and charge again the qty for the products and combinations.

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
