### ISSUE TITLE
PS 1.7.4.2 is filling up my web hotel with Gigabyte

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10381]
public_html/cart/var/cache/dev/profiler

![skarmavbild 2018-09-11 kl 17 56 41](https://user-images.githubusercontent.com/42907000/45372012-3885c400-b5ec-11e8-889d-cdc797205e4b.png)
![skarmavbild 2018-09-11 kl 17 56 53](https://user-images.githubusercontent.com/42907000/45372041-450a1c80-b5ec-11e8-878c-dd4889a79467.png)
Yesterday I noticed that my 3 GB web hotel was filled with these cache files. Is this a bug or something I can turn off? Is there a function to clear those files after some time?

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9

**Comment by MathiasReker** [comment]
You can clear cache.

Your screenshot shows 4kb, is that after you cleared the cache? What did the folder contain?

**Comment by peranderssjostrom** [comment]
Yes, I have cleared the folder just before the screenshot.
Inside those folders you have another folders with megabyte. At this folder level I had tons of folders summing up to 1.5 GB.

**Comment by PierreRambaud** [comment]
You must run your shop in production mode instead of development to prevent useless logs, and profiling. You can turn it off in `Advanced Parameters -> Performance`.

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

it is cache file, it is saved when you set for your site is cached, you can manually remove it or go to backend >> Advance Parameters >> Performance => click to clear cache button on the top bar.
You need also to disable the dev mode as Pierre said in the comment before.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment]
Thanks, debug mode turned off. Problem solved.

**Comment by khouloudbelguith** [comment]
Hi @peranderssjostrom,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Comment by djbuch** [comment]
This is still a problem when developping a site, the profiler folder is growing very big....
