### ISSUE TITLE
Statistiques PrestaShop ne fonctionnent pas 

### ISSUE THREAD

**Issue by Iron-Technology** [PrestaShop/PrestaShop#10397]
Bonjour,

Néo-PrestaShop depuis quelques mois, au lancement des produits de mon activité, je me suis rendu compte que les statistiques ne fonctionnent pas et restent à 0. Principalement les statistiques de visites. 

Pour vous donner un exemple, j'ai réalisé une commande et il est affiché : commande 1 - visite 0. 

Pouvez vous me donner les démarches nécessaires pour corriger ce problème. Merci à vous.

**Comment by khouloudbelguith** [comment]
HI @Iron-Technology,

I did not manage to reproduce the issue with the last version 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45419664-35d8ac80-b688-11e8-9a84-8b6059177de8.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Iron-Technology** [comment]
Merci pour votre rapide retour. Avez vous assez d'informations avec celles ci dessous ?

Hote : ftp.cluster021.hosting.ovh.net
Serveur : OVH
Version Prestashop : 1.7.4.2

![journal console google chrome](https://user-images.githubusercontent.com/43203989/45421668-16dd1900-b68e-11e8-9ec5-4c2fccde7f12.jpg)
[Logs OVH - error.txt](https://github.com/PrestaShop/PrestaShop/files/2374848/Logs.OVH.-.error.txt)
[Logs OVH - FTP.txt](https://github.com/PrestaShop/PrestaShop/files/2374849/Logs.OVH.-.FTP.txt)
[Logs OVH - Web .txt](https://github.com/PrestaShop/PrestaShop/files/2374850/Logs.OVH.-.Web.txt)
![rapport debuggage](https://user-images.githubusercontent.com/43203989/45421672-180e4600-b68e-11e8-94a5-2f57b650d697.jpg)
![stats](https://user-images.githubusercontent.com/43203989/45421674-180e4600-b68e-11e8-84c6-c3bd98165294.jpg)

**Comment by Iron-Technology** [comment]
Bonjour,

Depuis que je vous ai envoyé une partie des informations demandés, mon site n'a plus d'accès. La page ci jointe s'affiche automatiquement.

Pouvez vous me dire si cela est du aux manipulations que vous avez réalisés. 

En vous remerciant.

![bug](https://user-images.githubusercontent.com/43203989/45477695-67ae4980-b742-11e8-8aae-a9c481d7c9fb.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Iron-Technology,

This issue is occurred due to the Brainify module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

Best regards, Khouloud

**Comment by Iron-Technology** [comment]
Merci à vous, problème en cours de correction avec Brainify.

Concernant le problème initiale des visites, ou en êtes vous ? 

Merci

**Comment by khouloudbelguith** [comment]
Hi @Iron-Technology,

Could you please try to re-install the dashtrends module, clear cache, check, and feedback.

Thanks!

Best regards, Khouloud

**Comment by Iron-Technology** [comment]
Manipulation effectué, sans succès, visites toujours à 0 malgré 1 visite avec mon pc principal, 1 avec mon pc secondaire et 1 avec mon téléphone.

**Comment by khouloudbelguith** [comment]
Hi @Iron-Technology ,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards, Khouloud
