### ISSUE TITLE
The help button doesn't work in the positions & logs pages

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#10403]
Describe the bug
The help message in the logs page doesn't display, it should displayed with the help button. 

To Reproduce
1. Go to B.O > Configure> advanced parameters, logs page. Click on Help button.

Additionnal information
PrestaShop version: N/A
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi,

This issue exists in 2 symfony pages

1. **positions** => the help button doesn't work: click on the help button => nothing happens
2. **Logs** => the help button doesn't work: click on the help button => nothing happens

Best regards, Khouloud

**Comment by PierreRambaud** [comment]
This is not due to Symfony or even PrestaShop open source project. The SSL certificate of https://help.prestashop.com/ is just expired. 
You can change your ticket and keep only `positions`and `Logs` pages :)

**Comment by toutantic** [comment]
The SSL certificate has been updated

**Comment by khouloudbelguith** [comment]
Hi @toutantic,

In addition to the SSL certificate problem, the button help doesn't work in the Logs & Positions pages.
https://drive.google.com/file/d/1sWuRAXlmxcXD0MEMNXan3SzPtAUfyAJa/view

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
This issue still exists in the develop branch.
