### ISSUE TITLE
Z-index problem with switch controls

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#10409]
**Describe the bug**
On the develop branch, go to Shop Parameters > General, then scroll down. The switch controls appear on top of the white bar instead of scrolling below it. See screenshot below.

**Screenshots**
![screen shot 2018-09-12 at 18 29 48](https://user-images.githubusercontent.com/1009343/45439475-270aed80-b6ba-11e8-9830-8fd180941a3a.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Duplicate of #10339
