### ISSUE TITLE
displayHeader is not available when transplanting modules/hooks

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#10405]
**Describe the bug**
Whether or not you want to add hook exceptions or transplant a hook into `displayHeader` you can not since it's not in that list.

In my case I had a module which added CSS/JS in the `displayHeader` hook, just like any other module. Since there was a couple of pages (`cart` and `order` in my case) where I didn't want it to be active I added exceptions to it. It worked just fine for the other hooks but `displayHeader` is not available.

**To Reproduce**
1. Try to transplant a module to the `displayHeader` hook
2. When you try to select it in the "Transplant to" select, it's not available. It's not in the list.

**Additionnal information**
PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

In the ps_header table & ps_hook_alias, could you please try to replace "Header" with "displayHeader"& replace "displayHeader" with "Header" in ps_hook_alias
Thanks to check and feedback.

Best regards, Khouloud

**Comment by dennispw** [comment]
@khouloudbelguith It does not work unfortunately.

In my module I tried changing between `header` and `displayHeader` (and using both).

I also updated the `ps_hook` and `ps_hook_alias` accoding to your instructions but it makes no difference. Both `header` and/or `displayHeader` is still not available using the transplant method.

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Thanks to follow this link: https://devdocs.prestashop.com/1.7/modules/creation/displaying-content-in-front-office/ & feedback.

Best regards, Khouloud

**Comment by dennispw** [comment]
@khouloudbelguith The issue is that neither `displayHeader` _or_ `header` is available when **transplanting** a module or managing **exceptions**. Please see the attached images.

* It doesn't matter if we **only** use the `displayHeader` hook. It's not available in the list.
* It doesn't matter if we **only** use the `header` hook. It's not available in the list.
* It doesn't matter if we use **both** hooks. Neither is available in the list.

![step_1](https://user-images.githubusercontent.com/5259451/45542234-829bbf00-b811-11e8-9bd1-7d06e5b2506b.jpg)

![step_2_3](https://user-images.githubusercontent.com/5259451/45542235-829bbf00-b811-11e8-9215-d5801e088af0.jpg)

![step_4](https://user-images.githubusercontent.com/5259451/45542236-829bbf00-b811-11e8-904f-238b352bdd8e.jpg)

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Thanks for this clarifications.
I manage to reproduce the issue with the last version 1.7.4.2.
We will see how to fix it.

Best regards, Khouloud

**Comment by dennispw** [comment]
Any updates regarding this?

**Comment by khouloudbelguith** [comment]
@dennispw, sorry not yet.
It is added to our bug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by dennispw** [comment]
Still present.

**Comment by jf-viguier** [comment]
I have this bug too. I think that the header hook is not displayed when module is a widget (no hook at install)

**Comment by Prestaworks** [comment]
If the module is a widget module, no other hooks than displayHooks (hookHeader is not a displayhook any more) will be visible.
The positions controller needs to add all displayhooks if it's a widget hook, and also all the hooks that the module have defined functions for. It is possible that a module is a widget on the frontend but also have action hooks for BO handling.

AdminModulesPositionsController.php
line 399
$hooks = $module_instance->getPossibleHooksList();

calls to this in module class
```

if ($this instanceof WidgetInterface) {
            return $this->getWidgetHooks();
        }

        $hooks_list = Hook::getHooks();
```

**Comment by adrien-tafftaff** [comment]
You can modify on classes/Hook.php: 
```
public static function isDisplayHookName($hook_name)
    {
        $hook_name = strtolower(static::normalizeHookName($hook_name));

        if ($hook_name === 'header' || $hook_name === 'displayheader') {
            // this hook is to add resources to the <head> section of the page
            // so it doesn't display anything by itself
            return false;
        }

        return strpos($hook_name, 'display') === 0;
    }
```

by
```
public static function isDisplayHookName($hook_name)
    {
        $hook_name = strtolower(static::normalizeHookName($hook_name));

        if ($hook_name === 'header' || $hook_name === 'displayheader') {
            return true;
        }

        return strpos($hook_name, 'display') === 0;
    }
```
Doing this, the header & displayheader will be show for widgets

**Comment by Prestaworks** [comment]
> 

Yes, but you still may need action hooks.
