### ISSUE TITLE
Clicking on orders shows an error

### ISSUE THREAD

**Issue by p2d0** [PrestaShop/PrestaShop#10404]
**Describe the bug**
Clicking on orders shows an error "Table 'u0504861_default.ps_pokupki_orders' doesn't exist"
Russian localization

[VIDEO](https://puu.sh/BtNaL/7eadd63727.mp4)

**Additionnal information**
PrestaShop version: 1.7.3.3
PHP version: 7.1.18

**Comment by khouloudbelguith** [comment]
Hi @Patriot720,

This issue occurs due to the "yamodule" module.
Have you tried to contact the module author?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @Patriot720,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
