### ISSUE TITLE
Error with stores csv import v1.7.4.2

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#10418]
**Describe the bug**
"Property Store->name is empty." when trying to upload a csv for stores addresses.

**To Reproduce**
Upload a csv.

**Screenshots**
<img width="1440" alt="screen shot 2018-09-13 at 11 09 58" src="https://user-images.githubusercontent.com/71735/45482373-c6c18d80-b745-11e8-984c-607da512fa9f.png">

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @ced--ced,

Thanks for your report.
This issue is fixed in the next release 1.7.5.0
It will be released in October.
https://drive.google.com/file/d/1tX_hpLP8kfJ7AsYBUjbvgFP1alElge64/view

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
HI @ced--ced,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9235 to solve the issue.

Best regards, Khouloud
