### ISSUE TITLE
Wrong argument order in call to Manufacturer::getManufacturers() in Manufacturer::getLiteManufacturersList() 

### ISSUE THREAD

**Issue by benwallis** [PrestaShop/PrestaShop#10417]
/classes/Manufacturer.php

In Manufacturer::getLiteManufacturersList() the call to getManufacturers() has the arguments in the wrong order:

`$manufacturers = Manufacturer::getManufacturers($idLang, true);`

Should be:

`$manufacturers = Manufacturer::getManufacturers(true, $idLang);`

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

Best regards, Khouloud

**Comment by benwallis** [comment]
Done: https://github.com/PrestaShop/PrestaShop/pull/10428

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

Thanks for your report & your fix.

Best regards, Khouloud
