### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Prestapro** [PrestaShop/PrestaShop#10413]
**Is your feature request related to a problem? Please describe.**
Accessibility for default PrestaShop theme 1.7 (PrestaShop 1.7.4.2)

**Describe the solution you'd like**
Please check the standard template for public access (all pages).
This can be done using the Chrome Dev Tools, the Audit tab.
It does not take a lot of time.

**Describe alternatives you've considered**
There are no alternatives, it just needs to be done)

**Additional context**
http://prntscr.com/ktrkhl
http://prntscr.com/ktrmsl
http://prntscr.com/ktrnl2

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Your issue should be fixed in this ticket #10366
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #10366
