### ISSUE TITLE
How to remove jquery UI from FO?

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#10429]
**Is your feature request related to a problem? Please describe.**
OK. So this might be simple but:
I don't need (and frankly don't want) to load +250kb jquery UI in the front office as my theme (a modified Classic) doesn't use it. How do I remove it without altering core code?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rdy4ever** [comment]
Ok, to answer my own question, it seems that I actually need one componetnt of jQuery UI, the "autocomplete" component to be exact, required by the search bar module. So, if anyone else is wondering if you can switch 250kb of js for 35kb - you can. To do so:
1. Go [here](https://jqueryui.com/download/#!version=1.12.1&themeParams=none&components=110000010001000000100000100000000000000000000000) and download a custom build of jqueryUI that contains only the autocomplete component (uncheck all, then check only autocomplete - dependecies will be auto selected). 
2. Download the build (I chose no theme).
3. Copy it in `themes/YOUR_THEME/js/jquery/ui/` with the name `jquery-ui.min.js`, so the final path is `themes/YOUR_THEME/js/jquery/ui/jquery-ui.min.js`
4. If you want to also remove jquery ui style sheets... well, you could copy some empty (/**/)style sheets in `themes/YOUR_THEME/js/jquery/ui/base/minified/jquery-ui.min.css` and `themes/YOUR_THEME/js/jquery/ui/base/minified/jquery.ui.theme.min.css`. Or maybe there is a better way, let me know.

**Comment by arouiadib** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/33558
:fire:
