### ISSUE TITLE
The server returned a "500 Internal Server Error"

### ISSUE THREAD

**Issue by reubensimute** [PrestaShop/PrestaShop#10425]
The system is not sending emails when the new account is created through my email settings are working fine. Can you please assist to why these are coming.?

**Describe the bug**
I am receiving the following error,
**1. When a new Order is being submitted by a customer. The Page goes black and displays**
"This page isn’t working
www.ptsdev.reveec.com.au is currently unable to handle this request.
HTTP ERROR 500"
![onnewordersubmit](https://user-images.githubusercontent.com/202356/45498469-a678e980-b7ac-11e8-8ed9-a3370dad20b8.PNG)

**2. On customer initial registration, I am receiving this error messages**
"This page isn’t working
www.ptsdev.reveec.com.au is currently unable to handle this request.
HTTP ERROR 500"
![newcustomeronaccountcreation](https://user-images.githubusercontent.com/202356/45498721-46367780-b7ad-11e8-91e8-39ad20cf183a.PNG)

**3. On the Admin side. on Order Status change, I am receiving this error message>**
"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."
![onchangingstatus](https://user-images.githubusercontent.com/202356/45498854-9dd4e300-b7ad-11e8-8d00-2bfbaebb3bdf.PNG)

**4. When I try to resend the email on Order Status changed, I get the same error 500**
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
![onemailresendsincestatuschanged](https://user-images.githubusercontent.com/202356/45498909-c65cdd00-b7ad-11e8-8670-e774bb8cc06c.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.8
![host_info](https://user-images.githubusercontent.com/202356/45498969-e8eef600-b7ad-11e8-99e9-02d59f62848f.PNG)

My email settings are correct
![emailsetting](https://user-images.githubusercontent.com/202356/45499146-5ac73f80-b7ae-11e8-9f52-adf929389045.PNG)

**_Note:
I deleted the user account including the address and then I tried to change the Order status? The Status changed correctly without any "The server returned a "500 Internal Server Error"."_**

**Comment by khouloudbelguith** [comment]
Hi @reubensimute,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by reubensimute** [comment]
![exonnewaccountcreation](https://user-images.githubusercontent.com/202356/45522309-cc29e100-b7f4-11e8-9caf-82981743b939.PNG)
![exonorderstatuschanged](https://user-images.githubusercontent.com/202356/45522310-cc29e100-b7f4-11e8-87d3-87cea239c68f.PNG)
![exonnewordersubmit](https://user-images.githubusercontent.com/202356/45522311-ccc27780-b7f4-11e8-88b0-8fa0ee4bf4da.PNG)

**Comment by reubensimute** [comment]
Hi 
I managed to resolve this issues as it only appears to be an email problem.
I enabled **### intl** PHP function, on the Hosting backend, and everything I reported appears to be working fine now.
I enabled **### intl** PHP function,
![resolvedbyenbled](https://user-images.githubusercontent.com/202356/45526625-7c561480-b80a-11e8-96c0-0fabfced9bb4.PNG)

**Comment by khouloudbelguith** [comment]
Hi @reubensimute,

Thanks!
You can also follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Best regards, Khouloud
