### ISSUE TITLE
memcached strange behaviour

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10420]
Prestashop 1.7.4.2
Linux #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 
apache+nginx
It happens to me a strange thing, only when active memcached indicating the directives of the server: very often the data of the products are not updated, such as price, description and more, and very often, after some changes to the products, I throw away from the backoffice . Return, I do not find the changes just made in the product, and even if I try again 10 times, not prejudice to my changes.
If I delete memcached server info, all works well!

**Comment by khouloudbelguith** [comment]
Hi @centoasa ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by centoasa** [comment]
host= vps Linux #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
apache+nginx (as proxy)
php 7.2.9 
memory limit: 512
memcached installed on server, as server on 11211 port and as extension.
prestashop fresh installation 1.7.4.2
I'm sorry @khouloudbelguith but there a re no errors, as via log-apache-java as with debug mode.
It is a behavior.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

This issue occurs after applying this patch: #10201?

Best regards, Khouloud

**Comment by centoasa** [comment]
@khouloudbelguith Alredy applied, but #10201 solve issue to add memcached server
Mine is issue memcached save data, and doesn't refresh data when admin change it

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

This issue occurs only when you add a server?

Best regards, Khouloud

**Comment by centoasa** [comment]
yes, it's right!

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Best regards, Khouloud

**Comment by centoasa** [comment]
I think it's related to to slowly file creation when start a script (3rd party module as https://github.com/dim00z/gshoppingflux or https://github.com/PrestaShop/gsitemap )

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Have you tried to disable those module one by one, clear cache & check?

Best regards, Khouloud

**Comment by centoasa** [comment]
without these modules, memcached have same bahaviour.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

We'll first try to reproduce it and we'll come back to you if we need more information.

Best regards, Khouloud

**Comment by sbordun** [comment]
Hi @khouloudbelguith  and @centoasa,

I experiencing the same behavior on PS 1.7.4.3 with memcached . 
As a workaround I am not using cache.

 What is the status of this issue?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @sbordun,

In your case, this issue is applied after applying this patch: https://github.com/PrestaShop/PrestaShop/pull/10201?
We need to retrieve also your PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record
https://drive.google.com/file/d/1DudWgB4_2e64mQj9anPpWBNgDbs0hgqN/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by pollat** [comment]
I have the same problem with prestashop 1.7.6 and variants quantity updating: 
if i cancel an order, the variant quantity are not right update and if I try to update the variant quantity manually (for example change 4 in 3), after saving I have green advice "Setting updated", but if I refresh a page the quantity are the same 4 like before. 

If I deactive memecached all are ok. 
Do you have solution to solve this problem with memecached?

**Comment by madkot** [comment]
I have same problem with product description PS 1.7.6.8, php 7.2, memcached enabled
after update description it not refresh on product for a some time (1min - ?).

**Comment by khouloudbelguith** [comment]
Hi!

This issue is currently closed, can you open a new one with more information about your configuration.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
