### ISSUE TITLE
Incoherence of customers firstName lastName length between customer and address forms

### ISSUE THREAD

**Issue by FranckRIBEIRO** [PrestaShop/PrestaShop#10433]
**Describe the bug**
The form for creating a new customer accept first and lastName up to 255car whereas the addressForm only accept 32car for these fields.

**To Reproduce**

1. Create a customer with a first or lastName longer than 32car
2. Add articles to cart and go to checkout
3. The address form generated is pre filled with an invalid number of car
4. Click continue and see Error Server 500

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 5.6

**Possible Fix**
Go to :
classes/Address.php
line 124 and 125
Replace :   'size' => 32  BY   'size' => 255

**Comment by khouloudbelguith** [comment]
Hi @FranckRIBEIRO,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45545031-508e5b00-b819-11e8-895c-4b4aab7e5c50.png)
https://drive.google.com/file/d/1jJ5AzZGzlNYGU9ndo6UI9QC1p1eV8IHx/view
We will see how to fix it.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @FranckRIBEIRO,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

Best regards, Khouloud

**Comment by FranckRIBEIRO** [comment]
Sure

**Comment by khouloudbelguith** [comment]
Hi @FranckRIBEIRO 

Thanks!, nice catch :)
Fixed by #10438

Best regards, Khouloud
