### ISSUE TITLE
BO: Uploading a (too large) file as a product download (e.g. a manual), provides no error to the user

### ISSUE THREAD

**Issue by mortenhartvig** [PrestaShop/PrestaShop#10432]
**Describe the bug**
When i upload a file too large (as product download), i get no error in the UI. Only the console log/inspection shows an exception going on:

The console log (chrome) shows that the XHR has failed loading the POST. Because the response is 413 (Request entity too large). I understand the error, i just think the interface has to understand it as well:)

![udklip](https://user-images.githubusercontent.com/17026838/45540301-57fb3780-b80c-11e8-8d10-a1a56551af4f.JPG)

**Additionnal information**
PrestaShop version: 1.7.2.2
PHP 7.1 (Apache)

**NGINX proxy in front** This guy is the one blockign/returning the response, in case you can't replicate the behavior (then test with NGINX)

**Comment by mortenhartvig** [comment]
The Post response is status code 413, so a simple 200 check could solve it (or something similar). This is the NGINX Response DOM

![image](https://user-images.githubusercontent.com/17026838/45540597-259e0a00-b80d-11e8-8395-e6fd3b7bf2d1.png)

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

I attached a video record.
https://drive.google.com/file/d/1aTXpbqCdvgedzFkbwVdq7ZQ9jIQE9IMp/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
