### ISSUE TITLE
ContextErrorException in CustomerFormatter.php line 215:

### ISSUE THREAD

**Issue by willy2m** [PrestaShop/PrestaShop#10439]
Hello 

I am getting this error on the confirmation page after the client make an order. 

<img width="978" alt="captura de pantalla 2018-09-14 a las 15 40 14" src="https://user-images.githubusercontent.com/43242372/45553620-b89e6a80-b834-11e8-8121-ba950545456c.png">

In the backoffice the order is received and all emails (order confirmation, paypment accepted) are sent. It is just an error in the confirmation page once the payment is completed.

PHP INFO
Host info: Linux #1 SMP Debian 3.2.82-1 x86_64
Host Sofware: Apache
PHP Version: 5.6.32
Memory limit: 320M
Max. execution time: 40
Max. file upload size: 30M

SHOP INFO
Prestashop version: 1.7.2.5
Shop URL: http://salesdeplata.com/
Theme: alysum

MYSQL Info
Versión de MySQL: 5.5.57-0+deb7u1-log
Host MySQL: localhost
Database MySQL: ps-sales
User MySQL: mysalesdep
Prefix: ps_
Motor MySQL: InnoDB
Controler MySQL: DbPDO

Doesn't matter the browser and os, tried it on different computer and methods of paypment but i get the same error.

**Comment by khouloudbelguith** [comment]
Hi @willy2m,

Have tried this issue with another user, different data?

Best regards, Khouloud

**Comment by willy2m** [comment]
Hi @khouloudbelguith 

Yes, i have tried, same error

Thankns

**Comment by willy2m** [comment]
<img width="980" alt="captura de pantalla 2018-09-14 a las 16 28 41" src="https://user-images.githubusercontent.com/43242372/45556337-4da46200-b83b-11e8-93ca-f7391a9f60d4.png">

**Comment by khouloudbelguith** [comment]
Hi @willy2m,

Have you tried to contact the theme author?

Best regards, Khouloud

**Comment by willy2m** [comment]
Hi @khouloudbelguith 
I am doing it right now, I believed it was an error regarding prestashop

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @willy2m,

Thanks!
Waiting for your feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @willy2m,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
