### ISSUE TITLE
cron with flag option

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10431]
I think it's great to have the cron options integrated into prestashop, with flags as an option for the dates / days, not as dropdown, so set the cron in your server, there is the possibility to run the script several times.
Let me explain: if I set the cron on my server / * 8 every eight hours, and set "every minute" this single script will be executed every eight hours, but the others, set at a particular time, will not be executed.
I hope I have been well explained.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

On Prestashop Addons, there is a free module called Crontab that allows a server that does not have a cron process, still be able to run a list of treatments.
https://github.com/PrestaShop/cronjobs
Thanks to check and feedback.

Best regards, Khouloud

**Comment by centoasa** [comment]
I already use it, but it’s possible set it only every hour or on every day/weekdays 
If it’s possible set it for multiple choice with flag, not with drop down with single choice

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

This issue needs to be specified by our developers.

Thanks & best regards, Khouloud

**Comment by DanielBoettner** [comment]
> ... that allows a server that does not have a cron process, still be able to run 

Are you sure about that? At least in both modes? The module offers two modes

* easy (webservice)
* advanced

Isn't the module *just* a way to  **have a module inside Prestashop to allow registering other cronjobs to this module?** or **allow registering new ones via the modules admin interface**?

As far as I can tell, the cronjobs module still needs a native cronjob.

When switching to advanced mode it specifically prompts to run something like 

 `0 * * * * curl "http://{domain}/admin/index.php?controller=AdminCronJobs&token={a secure key}" `

in the 'cronjob manager`.

Which I assume is a reference to either creating a cron with `crontab -e` or telling an external service capable of running crons to register a cron and run it.

If I misunderstood something please let me know.

And @centoasa

I currently try to adopt https://www.h-hennes.fr/blog/2017/12/01/prestashop-gestion-des-taches-cron/ (use google translate to get a translated version)

Which describes using the cronjob module to register your modules for a cronjob via a hook.

When using it in advanced mode, as described above. It should be possible to switch the timing of the main cron to go every 5-10 minutes. And then register your crons with the cronjob module.
Which in turn 

The documentation on the cronjob module is, well its non-existent. So with that said, its still a bit of guesswork on how the module actually works.

**Comment by DanielBoettner** [comment]
Also, this issue is likely better placed in the PrestaShop/cronjobs repository

**Comment by hibatallahAouadni** [comment]
Hello,

This improvement has been open since 2018 and no one is reacting to it.
Ping @PrestaShop/product-team could you please take a look. Should I close it? what do you think?

Thanks!

**Comment by matks** [comment]
The module https://github.com/PrestaShop/cronjobs is no more part of the open source project. It is now a repository from the PrestaShop company https://github.com/PrestaShopCorp/cronjobs

So we can close this issue as we are no longer in charge of the module.
