### ISSUE TITLE
Email Error version 1.6.1.20

### ISSUE THREAD

**Issue by miannaveed0123** [PrestaShop/PrestaShop#10449]
Dear Team,
I am facing email connecting error. My email sync successful but when i go to send test email on back office or use contact us page show error. Please advise how to resolve this issue.

**Comment by MathiasReker** [comment]
Do you use PHP mail function?
If not, try to switch to it.

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by miannaveed0123** [comment]
> Do you use PHP mail function?
> If not, try to switch to it.

Dear, I don't know because i never change any function after uploaded of Prestashop.

**Comment by miannaveed0123** [comment]
> Hi @miannaveed0123,
> 
> Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
> Thanks to check and feedback.
> 
> Best regards, Khouloud

I already perform, see below message i received.

Error: Please check your configuration
Connection to whuk102.redbackinternet.net:143 Timed Out

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature. The options are:
- Use PHP's mail() function. This option is recommended by default. In the event that this does not work, then use the SMPT option below.
- Set your own SMTP parameters. In this case, a new section appears, with more fields. The information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check with your host & feedback.

Best regards, Khouloud

**Comment by miannaveed0123** [comment]
> Hi @miannaveed0123,
> 
> Configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature. The options are:
> 
> * Use PHP's mail() function. This option is recommended by default. In the event that this does not work, then use the SMPT option below.
> * Set your own SMTP parameters. In this case, a new section appears, with more fields. The information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.
>   Thanks to check with your host & feedback.
> 
> Best regards, Khouloud

Thanks for your time, I have all info regarding configuration of email, POP3, SMTP. I tried my self every option but not working also i consult with hosting provider they advise problem in my script.

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Could you please check your SMTP connection in your PHP info.
https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page#gs
![image](https://user-images.githubusercontent.com/16067358/45617341-516df980-ba72-11e8-9fdc-38b67c3c1b4d.png)
Thanks to check & feedback.

Best regards, Khouloud

**Comment by miannaveed0123** [comment]
> Hi @miannaveed0123,
> 
> Could you please check your SMTP connection in your PHP info.
> https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page#gs
> ![image](https://user-images.githubusercontent.com/16067358/45617341-516df980-ba72-11e8-9fdc-38b67c3c1b4d.png)
> Thanks to check & feedback.
> 
> Best regards, Khouloud

Below is detail

Outgoing Server: mail.dxpshop.com.pk
SMTP Port: 465(SSL) or 587(TLS)

Incoming Server: mail.dxpshop.com.pk
IMAP Port: 993 POP3 Port: 995

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Try checking all your files and directories permission. If all your files and folder permission is set to 777 they can't access to SMTP config.
So reset the permission of all the files to 644 while the folders to 755.
Also, this problem may occur if your firewall does not allow connections
Thanks to check & feedback.

Best regards, Khouloud

**Comment by miannaveed0123** [comment]
> Hi @miannaveed0123,
> 
> Try checking all your files and directories permission. If all your files and folder permission is set to 777 they can't access to SMTP config.
> So reset the permission of all the files to 644 while the folders to 755.
> Also, this problem may occur if your firewall does not allow connections
> Thanks to check & feedback.
> 
> Best regards, Khouloud

If i set 644 web not working..

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by miannaveed0123** [comment]
> Hi @miannaveed0123,
> 
> Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * host
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> * screenshots
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!
> 
> Best regards, Khouloud

Hi I check myself again setting and found email now work, thanks for your time.

**Comment by miannaveed0123** [comment]
Issue resolve!

**Comment by khouloudbelguith** [comment]
Hi @miannaveed0123,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud
