### ISSUE TITLE
1.7.4.2 Email not working  completely ( SMTP) 

### ISSUE THREAD

**Issue by natarajbodhi** [PrestaShop/PrestaShop#10443]
**Describe the bug**
The out going emails are not going in the 1.7.4.2 version (SMTP). But at the same settings in 1.7.3 the smtp emails working. I even tried a fresh install, but the problem is same. Please fix it.

**To Reproduce**
1. Go to '1.7.4.2'
2. Click on 'send emails using smtp in live server or localhost development server'
3. Scroll down to ''
4. See error "check if you get emails for testing, subscriptions, user registration and others."

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6,7.0 & 7.1

**Comment by khouloudbelguith** [comment]
Hi @natarajbodhi,

Configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature.
To set my your own SMTP parameters, in this case, the information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.
In my case with PS 1.7.4.2, IT IS OK.
![image](https://user-images.githubusercontent.com/16067358/45615548-20d79100-ba6d-11e8-88ac-59639f44d4c7.png)

Best regards, Khouloud
