### ISSUE TITLE
Problems with the Prestashop 1.7.4.2 update

### ISSUE THREAD

**Issue by C-Ranalletta** [PrestaShop/PrestaShop#10457]
**Describe the bug**
I've updated my Prestashop e-commerce from 1.6 to 1.7.4.2 using 1-Click Upgrade, but when the update was over I found some errors and now my platform and my site doesn't work correctly. 
I entered the debug mode and I find these errors (they are in the screenshots below).
Could you help me to solve the problem?
Thanks

**Screenshots**

![schermata 2018-09-16 alle 17 22 46](https://user-images.githubusercontent.com/43338406/45618139-0ef9ec00-ba75-11e8-8936-993105604a28.png)
![schermata 2018-09-16 alle 17 22 57](https://user-images.githubusercontent.com/43338406/45618140-0ef9ec00-ba75-11e8-8563-2eafb76afc30.png)

**Additionnal information**
PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Could you please try to disable the PayPal module, clear cache from your shop & your browser, check and feedback.

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
When you upgrade from 1.6 to 1.7, your modules needs to be updated as well. This step is not done by the "1-click upgrade" module. Please go to the module page and check the "module to upgrade" list.

**Comment by C-Ranalletta** [comment]
I can't do this because if I open the module page I see this error (screenshot is attached below)
![schermata 2018-09-17 alle 15 06 58](https://user-images.githubusercontent.com/43338406/45624734-7884f500-ba8b-11e8-9679-0ac2fdb8c7cb.png)

**Comment by Quetzacoalt91** [comment]
You should remove the folder modules/advancedeucompliance to get rid of that issue.

**Comment by C-Ranalletta** [comment]
How can I do this? 
Thanks a lot

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

You need to delete the advancedeucompliance folder, you can find it into the path /YourProjectFolder/modules/

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Thanks, now I can see the modules page. 
But I still have a problem, when I try to upgrade a module, I see this error: 
"Warning: include_once(/homepages/12/d643640243/htdocs/clickandbuilds/PrestaShop/Gioielleria_Ranalletta/classes/../tools/pear/PEAR.php): failed to open stream: No such file or directory" 

How can I solve it?

Thanks
Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Which module did you need to upgrade it?
Could you please try to re-install it.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I've re-install, de-activated and activated 39 modules, but if I remove the mantenance mode I see all these errors in my front office site (photos are attached).
![schermata 2018-09-18 alle 09 49 26](https://user-images.githubusercontent.com/43338406/45672649-006d0c80-bb29-11e8-99ef-67913b5fed6c.png)
![schermata 2018-09-18 alle 09 49 39](https://user-images.githubusercontent.com/43338406/45672651-0105a300-bb29-11e8-8071-933e79438f0e.png)
![schermata 2018-09-18 alle 09 49 55](https://user-images.githubusercontent.com/43338406/45672652-0105a300-bb29-11e8-97f7-a726d692816e.png)
![schermata 2018-09-18 alle 09 50 09](https://user-images.githubusercontent.com/43338406/45672654-0105a300-bb29-11e8-91d8-fbdb401cef1f.png)
![schermata 2018-09-18 alle 09 50 18](https://user-images.githubusercontent.com/43338406/45672655-0105a300-bb29-11e8-90a2-2c6ce318e54a.png)

I think there are other problems to solve, but I don't know how!

Thanks 
Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Could you please try to uninstall the blockbanner module & try to install the ps_banner.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Ok I've unistall these modules, they were not compliance with 1.7 version and now I see no more error in the front end of my site but I can't see nothing on the page (photo attached). I also tried to upload my theme module compatible with 1.7 version but I can't do this, it doesn't allow me.

Thanks
![schermata 2018-09-18 alle 11 38 49](https://user-images.githubusercontent.com/43338406/45678935-c8b99100-bb37-11e8-89e9-58c2956caa30.png)

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

You need to install some native modules:

1. advancedeucompliance
2. bankwire
3. ps_contactinfo
4. ps_shoppingcart
5. ps_languageselector
6. blockcms
7. blockcmsinfo
8. blockcontact
9. blockcontactinfos
10. Currency block 
11. ps_facetedsearch
12. Newsletter
13. Customer accounts ...

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I've install some native modules and uninstall other non-compatible modules, but I think there is a problem with the theme, because I can't see nothing on the front office. Furthermore, an error appears in some modules like this: "Home slider images"
![schermata 2018-09-18 alle 18 20 31](https://user-images.githubusercontent.com/43338406/45701504-a9d6f100-bb6f-11e8-84f4-8dff85bb397a.png)

I aslo can't see information about orders and clients, because it says me that I don't have permission

I'm sorry for all these requests, but I don't know how to do it!
Best regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

It is the same problem with the homeslide module, you need to remove it & install the good one which is compatible with PS1.7.
In addition, for the second issue, could you please take a look at this solution: https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I've done it! I've remove the old module and install the new one, compatible with 1.7, but the error is the same.

For the second problem I'll take a look the the link you send me.

regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

In the version 1.7, the exact name of this module is ps_imageslider

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
I've installed this module (ps_imageslider) in my Prestashop, and I've tried to reset it, but it appears an error that says me I've no permission to reset it.

Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Could you please provide me a screenshot of this error?

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I've just resetted the image slider module, and now it seems work correctly, but I have the same problem with principal menu module. When I click on it to configure the module, I can't work with it and if I click in one categories of the site, on the front office, it appears that errors (photo attached).

In addiction I've tried to upload a new template but I didn't manage to load nothing, because the bottom "upload files" doesn't work.

![schermata 2018-09-19 alle 16 15 59](https://user-images.githubusercontent.com/43338406/45759517-5ecce480-bc28-11e8-8be1-5a389d4bd043.png)

Thanks a lot.
Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

The same issue, you need to remove the blocklayered module, you need to delete the blocklayeredfolder into Project_Folder/modules/
Try to re-install the Faceted search  module.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
I've deleted the blocklayerfolder, but now I can't find the faceted search module to download.
Do you know the correct Italian name of the module or do you have the correct link where I can download it?

Thanks
Regards

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I've found the Faceted search module and I've reinstalled it, but the problem with the main menù block remained. In fact if I try to configure the module, the bottom to select the menù voices doesn't work.
I tried to reset the module but the problem is the same.

How can I do?

Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Thanks to remove the blocktopmenu folder from /Project_Folder/modules & try to re-install the ps_mainmenu module.
Ps: You need to clear cache from your browser & your shop.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hello @khouloudbelguith 
thanks for your advice, I've cleared my cache but the problem is the same.
How can I understand what is the problem?

Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

There's no exception when debug mode is enabled?

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
No, it's the same thing. 
Even if I try to upload a new theme the "upload file" bottom doesn't answer.

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
thanks for your suggestion, but I've tried to change my browser and now it seems work correctly.
But I also have another issue, in fact if I click on one product on sale, in front office of the site, it appears this error (photo attached) 

How can I try to fix it?

Thanks a lot
Regards 
![schermata 2018-09-20 alle 10 03 37](https://user-images.githubusercontent.com/43338406/45825791-568dab80-bcf3-11e8-8427-6d79f2c65bb2.png)

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta ,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 
I'll try to do this.
In the meantime I send you this screenshot from Prestashop debug mode , I don't know if it will be useful.

![schermata 2018-09-20 alle 17 48 42](https://user-images.githubusercontent.com/43338406/45830601-cd2fa680-bcfd-11e8-89af-96e344c63b5b.png)

Regards

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Have you any previous customized module related to the product?
You need to remove it.

Best regards, Khouloud

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith 

1. no, I haven't any customized module for products, I just inserted some attributes during the product creation.
I think the problem is in the attributes and features of the catalog. 

2. I also read you suggestion #9513 (comment), but I don't know how to do. Could you help me telling how to solve the problem of forbidden access to orders and customer data?

3. I investigated in debug mode in Prestashop and I discovered this errors (photo attached). How can I solve these problems?

Thanks a lot.
Regard
![schermata 2018-09-21 alle 10 15 59](https://user-images.githubusercontent.com/43338406/45869071-c5b4df80-bd87-11e8-8b7b-5ca9f64a6941.png)

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
