### ISSUE TITLE
Bug when trying to add to cart more products than the one in stock (PS1.7.4.2)

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#10451]
If you increase quantity, to a quantity higher than the one available, the add to cart button become disabled, but this doesn't happen instantly.
So the user it's able to add to the cart a product that it's not available, so when it goes to checkout it will see red alert about product unavailable in that quantity.

You can do this with a product with stock quantity of 1, then from product page, increase quantity to 2 an just after this, click on add to cart button.

Prestashop 1.7.4.2
PHP 7.2.8

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

Yes, we are aware of this, but we have already improved this part in 1.7.3 / 1.7.4 [#8752; #8774; https://github.com/PrestaShop/StarterTheme/pull/222] and maybe we will do it later but we can't improve it right now.


Best regards, Khouloud

**Comment by darkf3d3** [comment]
That's pity because it's an annoying bug for customers.
Prestashop 1.6 add to cart work a lot better than the one actually available on PS1.7.
