### ISSUE TITLE
Internal server error 500 PayPal & Braintree official Module 4.4.2

### ISSUE THREAD

**Issue by Medaliskr24** [PrestaShop/PrestaShop#10450]
**Describe the bug**
I have installed and configured PayPal & Braintree official Module 4.4.2 , but  I can't go at the end of the purchasing procedure, because on cart page I get an Internal server error 500 !!
and  when i got this error after enabled the debug mode and don't now iF related to the instaltion of the paypal module or not .
 
![screenshot_20180915-111031_chrome](https://user-images.githubusercontent.com/41730638/45594133-6329a100-b98d-11e8-9dd1-68ab1f78b988.jpg)
images.githubusercontent.com/41730638/45594116-0cbc6280-b98d-11e8-9d4e-828e96ea44f5.jpg)
![capture](https://user-images.githubusercontent.com/41730638/45594122-1e9e0580-b98d-11e8-84af-9571d2f075aa.JPG)

shop url : http://prestashop-demo.u308051739.hostingerapp.com/en/
PrestaShop version: 1.7.4.2
PHP version: 5.6.37

**Comment by MathiasReker** [comment]
Did you ask the module developer?

**Comment by Medaliskr24** [comment]
not yet

**Comment by khouloudbelguith** [comment]
Hi @Medaliskr24,

This issue occurs only when the PayPal & Braintree official Module is enabled?
Could you please try to disable it, clear cache, check, and feedback.

Best regards, Khouloud

**Comment by Medaliskr24** [comment]
Hello
thank you for the reply
This issue occurs when the PayPal & Braintree official Module is disabled too
![capture](https://user-images.githubusercontent.com/41730638/45614788-8a05d700-ba62-11e8-9a19-44db0b9cfb48.JPG)

**Comment by Medaliskr24** [comment]
unfortunately the team support of the theme take much time to respond , they even didn't fix the earlier bugs !!

**Comment by khouloudbelguith** [comment]
Hi @Medaliskr24,

Could you please navigate to your BO => Design => Positions=> check the "Display non-positionable hooks" option & search for the "displayHome".
![image](https://user-images.githubusercontent.com/16067358/45615693-8d529000-ba6d-11e8-8a99-b705de891981.png)
Thanks to check & feedback.

Best regards, Khouloud

**Comment by Medaliskr24** [comment]
Thank you so much for your responding 
the theme team fix it now

kind regrads

**Comment by khouloudbelguith** [comment]
Hi @Medaliskr24,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
Thanks!
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
