### ISSUE TITLE
Back-Office several controller "[DOM] Found 2 elements with non-unique id" error on Devtool console

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#10469]
**Describe the bug**
By navigating on each page of the Back-Office with your DevTool panel open (F12), you can notice that many controllers contain non-unique id, and it raised as an error by the console.

**To Reproduce**
1. Just open devtool panel (F12)
2. go to 'dashboard'
3. You can see errors like "[DOM] Found 2 elements with non-unique id #addons_login_button"
4. Same casefor each pages listed below

Pages concerned:

- dashboard
- invoices
- credit slips
- delivery slips
- products
- stats
- module catalog
- module manager
- theme catalog
- positions
- preferences
- payment method
- preferences
- localization
- translations
- general
- order settings
- product settings
- customer settings
- information
- performance
- administration
- E-mail
- import
- database
- logs

**Screenshots**
![image](https://user-images.githubusercontent.com/29543279/45679995-1afbb180-bb3a-11e8-8bc6-4fbfbf832c38.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 Develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @mbadrani,

I manage to reproduce this issue with the last version 1.7.4.2. / 1.7.5.0

Best regards, Khouloud

**Comment by sitolab** [comment]
same problem with prestashop version 1.7.4.2 how to solve this problem?

**Comment by khouloudbelguith** [comment]
Hi @sitolab,

The issue is added to our bug roadmap.
We will see how to fix it.

Best regards, Khouloud
