### ISSUE TITLE
Use Puppeteer to run End to End tests

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/PrestaShop#10468]
see project [geppetto](https://github.com/mbadrani/geppetto)

**Comment by PierreRambaud** [comment]
Should we move this repository into PrestaShop organization no?

**Comment by mbadrani** [comment]
yes that's what we want finally, but we will create a parallel project repository for the moment to avoid conflicts between package.json files

**Comment by mbadrani** [comment]
As we will push PRs to migrate our Selenium tests into Puppeteer, this issue is no more relevant.
