### ISSUE TITLE
Vulnerability jQuery

### ISSUE THREAD

**Issue by Prestapro** [PrestaShop/PrestaShop#10463]
Hello,

There is a problem with PrestaShop version 1.7.4.2:
Library Version
Vulnerability:
jQuery@2.2.4 Medium
jQuery UI@1.10.3 High

The problem can be reproduced in the Chrome Dev Tools tab Audit

Screen:
http://prntscr.com/kvgdzg

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45636465-14245e80-baa8-11e8-9f5b-c88ef0ba34d2.png)
We will see how to fix it.
Related to #10366

Best regards, Khouloud

**Comment by rdy4ever** [comment]
Bootstrap will be a tough one. There are some code breaking changes in the stable release and to fix them all is alot of work. I did it for my custom Classic based theme and there are some 60 files that need to be fixed for bootstrap 4.1.x stable. The worst one would be [the new display system](https://getbootstrap.com/docs/4.0/utilities/display/).
One thing I can't figure out is how is jquery 2.2.4 compiled, as I tried to upgrade it in node_modules, package.json but still the compiled theme,js features the old 2.2.4...

**Comment by marionf** [comment]
@eternoendless what do you think ?

**Comment by eternoendless** [comment]
Unfortunately we cannot upgrade Bootstrap and jQuery on the classic theme until the next major version. As @rdy4ever said, Bootstrap changed their layout system since alpha 6, which is a backwards compatibility break that would affect all of classic's child themes.

If you are concerned about these vulnerabilities, take a look at [Classic-Rocket](https://github.com/PrestaShop/classic-rocket/), which is a community port of Classic to Bootstrap 4.1

**Comment by rdy4ever** [comment]
Hi @eternoendless
Could you please tell me how to update jquery from 2.2.4 to latest? The strange thing is that in package.json and node_modules I have updated jquery but, after the build asstest/js/theme.js still comes with 2.2.4. Is there another source used for jquery? Thanks!

**Comment by eternoendless** [comment]
Hi @rdy4ever 

jQuery is included in Core (`themes/package.json`), AND in classic (`themes/classic/_dev/package.json`).

**Comment by matks** [comment]
@matthieu-rolland is this issue fixed by latest upgrade of jQuery thanks to jquery-migrate ?
