### ISSUE TITLE
When scrolling buttons appears on the top layer

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#10460]
**Describe the bug**
When you scroll on Modules pages (module catalog or module manager) you can see "search" button appearing under the top layer header toolbar.

**To Reproduce**
1. Go to 'Modules > module catalog'
2. Scroll down
3. Look at the search button => it appears under the header toolbar

**Screenshots**
https://drive.google.com/file/d/1OOSeqmjbVdwWHRgSf_2aHxDct7_3ZXgH/view?usp=sharing

**Additionnal information**
PrestaShop version: Develop 1.7.5.0
PHP version: N/A

**Comment by PierreRambaud** [comment]
Fixed in #10440

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I make the changes of you PR: #10440.
But it looks like this: 
![image](https://user-images.githubusercontent.com/16067358/45630722-86417700-ba99-11e8-83df-23735dbda881.png)

Best regards, Khouloud

**Comment by PierreRambaud** [comment]
@khouloudbelguith PR still in WIP (we will merge wednesday I think) and assets haven't been built :)
