### ISSUE TITLE
Autoupdate fails to update module 1.7.3.3 to 1.7.4.2

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#10467]
Autoupdate module fails on updating modules when trying update 1.7.3.3 to 1.7.4.2.

It fails at FrontController.php line 358 - Trying to get property of non-object. Ajax-autoupgrade.php ends up with 503. There is no error in the PS or server log.

To reproduce the issue simply use Autoupdate v 4.2 and PS 1.7.3.3 with default theme and proceed with the update. 

PHP version: 7.1.

![update1733](https://user-images.githubusercontent.com/15078106/45674155-c43bab00-bb2c-11e8-9c67-4f9ceb323379.png)

**Comment by khouloudbelguith** [comment]
Hi @krasnycz,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by krasnycz** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2391851/log.txt)

**Comment by khouloudbelguith** [comment]
Hi @krasnycz,

Service Unavailable server error code 503 response code indicates that the server is not ready to process the request.
Typically, this occurs because the server is shut down or inaccessible due to maintenance or overhead.
Could you please check if the safe_mode is enabled on your server & feedback.

Best regards, Khouloud

**Comment by krasnycz** [comment]
Well safe_mode has been deprecated since php 5.x. I am using DO instance on cloudways only for this installation. Moreover I tried to move the instance to different server where I have working 1.7.4.2 installation that was updated correctly. There is no error log in the server log even php error reporting is enabled.

**Comment by khouloudbelguith** [comment]
Hi @krasnycz,

Thanks for your feedback.
So, can I close this issue?

Best regards, Khouloud

**Comment by krasnycz** [comment]
Well no, the issue is not resolved. I am simply stating that I tested it on different server and it did not resolve the issue.

**Comment by khouloudbelguith** [comment]
Hi @thomas what do you think about his issue?

**Comment by krasnycz** [comment]
I managed to update the PS after uninstall all 3rd party modules. However I was unable to identify the source of the issue.

**Comment by khouloudbelguith** [comment]
Hi @krasnycz,

We already got that issue in https://github.com/PrestaShop/autoupgrade/issues/87#issue-335433391, which was caused by a third-party module.

Best regards, Khouloud

**Comment by JavierEB** [comment]
> 
> 
> I managed to update the PS after uninstall all 3rd party modules. However I was unable to identify the source of the issue.

I have the same problem but I can not identify which third-party module is causing the problem, some trick or how to do it ... Thanks

**Comment by khouloudbelguith** [comment]
Hi @JavierEB,

You need to disable one by one, clear cache & check.
Thanks!
