### ISSUE TITLE
Deleting existing language in BO

### ISSUE THREAD

**Issue by CArlvJ1N0N8** [PrestaShop/PrestaShop#10466]
When having multiple languages activated in the back-office and trying to delete a language (not in use by the user connected) provides an error and the back-office is now in the language you are trying to delete. 

Prestashop 1.7.4.2

**Comment by CArlvJ1N0N8** [comment]
To Reproduce
Steps to reproduce the behavior:

The connected user is using English as the active language
Go to the back-Office - International - Localisation - Langues
And delete spanish language
See error messages returned are in the user language, but the menu and such are now in Spanish. 
And i am unable to delete spanish 

Additionnal information
PrestaShop version: 1.7.4.2
PHP version: 7.0.27-0+deb9u1

**Comment by CArlvJ1N0N8** [comment]
![delete language](https://user-images.githubusercontent.com/42921237/45660944-3f6b7580-bac9-11e8-9c4d-223c4c93094d.JPG)

**Comment by MathiasReker** [comment]
You need to chance your default/active languege to another languege than spanish before you can delete it.

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

As @Mreker said, you need to navigate to the BO => IMPROVE => International => Localization => in the CONFIGURATION part, you need to edit the Default language.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
Not sure if my explanations were clear enough. 
My user is using the english language as defined in team in the BO 
Also the default language for my prestashop store is set to English. 
![default language set to english](https://user-images.githubusercontent.com/42921237/45701306-dd4c5800-bb3c-11e8-9560-46f4248aa114.JPG)

But trying to delete the portuguese language i get the error message. 
SO i am not deleting the default language nor the language the user connect is using. 
![result as i tried to delete the portuguese language](https://user-images.githubusercontent.com/42921237/45701321-e63d2980-bb3c-11e8-92fe-af4e5d7d4396.JPG)

So i am not being helped with the answer you provide.

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

I did not manage to reproduce the issue with the last version 1.7.4.2.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
I have a dev environment where i can reproduce the issue. 
If you want i can provide you access. 

thanks,

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
Problem has been solved.
Clear cache has solved our issue. 
So pleas close this issue.

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
