### ISSUE TITLE
The brand page is not displayed correctly

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10461]
**Describe the bug**
When we try to add a new brand, the description & the logo are not aligned.

**To Reproduce**
The window size is bigger than 1197px* 981px
1. Go to BO => Catalog => Brands page => 
2. Click on 'add a new brand'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/45633261-99efdc00-ba9f-11e8-893f-702a2a411d5d.png)

**Additionnal information**
PrestaShop version: develop / 1.7.5.0.
PHP version: 7.1

**Comment by ntiepresta** [comment]
Hello, @khouloudbelguith
I manage to reproduce the issue.
Best regards, Reddy Ntie

**Comment by jolelievre** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10462
