### ISSUE TITLE
Product image does not show

### ISSUE THREAD

**Issue by marchspa** [PrestaShop/PrestaShop#10473]
Hello, 
         I can't see product images since they don't show in the product., the permissions are 0755 and images can be seen in /img/p/. it doesn't matter what format i add, they upload in jpg. 
![image](https://user-images.githubusercontent.com/33666598/45681572-381d8980-bb14-11e8-95fd-c69b47e323ce.png)
Regeneration does not bring any error, they just don't appear. 
And if i inspect, the console shows 404 error. 
I'm using PrestaShop 1.6.1.20

**Comment by khouloudbelguith** [comment]
Hi @marchspa¿

Could you please try to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

Best regards, Khouloud

**Comment by marchspa** [comment]
It works!!! I was about to give up and uninstall ps! thanks a million!!!!!!!!

**Comment by khouloudbelguith** [comment]
Hi @marchspa,

You are welcome.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
