### ISSUE TITLE
Two H1 tags in the category pages for the category names

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10470]
Hi

**Describe the bug**
in the category pages there are more than one H1 tag

http://www.suvaance.com/microblog/how-google-considers-multiple-h1-tags-in-one-page/

add 2 H1 just to set a h1 for the desktop and a h1 for mobile, it would make more sense to use only one h1 and then find changes with the css code

from that suvaance.com is written
In HTML5, the semantic elements like header, footer, section etc, help representing the hierarchy perfectly and one can use one H1 tag in each such elements safely.
So, if you think different sections need separate H1 tag, don’t worry, feel free to use.

**Just don’t add the same text in every H1.**

so repeat the same test in the same section even if the div is different it is not a great solution

so those 2 category H1 are a seo bug also in html5

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/45680776-1e903800-bb3c-11e8-95a9-92cc2d4fc5bb.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

thanks

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.2.
Related to #10444

Best regards, Khouloud

**Comment by durgaprasadkundu** [comment]
Hi @maofree ,
Thanks for linking & referring to my post.:)

As per HTML5, yes, we can add multiple H1s but in different sections in a page. We’ve been practicing the same for our clients without any issues. And recently, Google has also confirmed that.

But here in this case, H1 for two category names shouldn’t be used.

**Comment by Quetzacoalt91** [comment]
Closed by #10447

**Comment by azitafomo** [comment]
I have same problem: 2 H1 just to set a h1 for the desktop and a h1 for mobile, please help me to fix this problem in the codes
https://20bekhar.com/33-juicer
It is one example

**Comment by azitafomo** [comment]
> Hi @maofree ,
> Thanks for linking & referring to my post.:)
> 
> As per HTML5, yes, we can add multiple H1s but in different sections in a page. We’ve been practicing the same for our clients without any issues. And recently, Google has also confirmed that.
> 
> But here in this case, H1 for two category names shouldn’t be used.
I have same problem: 2 H1 just to set a h1 for the desktop and a h1 for mobile, please help me to fix this problem in the codes
It is one example, could you please help me in this case that How I can edit it well?

**Comment by azitafomo** [comment]
> Hi
> 
> **Describe the bug**
> in the category pages there are more than one H1 tag
> 
> http://www.suvaance.com/microblog/how-google-considers-multiple-h1-tags-in-one-page/
> 
> add 2 H1 just to set a h1 for the desktop and a h1 for mobile, it would make more sense to use only one h1 and then find changes with the css code
> 
> from that suvaance.com is written
> In HTML5, the semantic elements like header, footer, section etc, help representing the hierarchy perfectly and one can use one H1 tag in each such elements safely.
> So, if you think different sections need separate H1 tag, don’t worry, feel free to use.
> 
> **Just don’t add the same text in every H1.**
> 
> so repeat the same test in the same section even if the div is different it is not a great solution
> 
> so those 2 category H1 are a seo bug also in html5
> 
> **Screenshots**
> ![1](https://user-images.githubusercontent.com/653230/45680776-1e903800-bb3c-11e8-95a9-92cc2d4fc5bb.png)
> 
> **Additionnal information**
> PrestaShop version: 1.7.4.2
> PHP version: 7.0
> 
> thanks

HI
To solve I have same problem: 2 H1 just to set a h1 for the desktop and a h1 for mobile, could you please tell me which file have you changed?

**Comment by Maofree** [comment]
Hi
remove the second div  containing the second h1
at the first div remove the class "hidden-sm-down"

bye

**Comment by azitafomo** [comment]
> Hi
> remove the second div containing the second h1
> at the first div remove the class "hidden-sm-down"
> 
> bye

Thanks my friend about your help and answer
Could you tell me by removing this part mobile will be have H1 too or no?
And Is it possible for you to tell me the address of this file in server? Should I find category.tpl or something else in classic part?

**Comment by Maofree** [comment]
hi
it is necessary just one h1, the code is the same for desktop and mobile, css code is used to adapt the pages to the various devices, but the text is the same

check in the last version of classic theme, they have solved this bug, it is in catalog/listing/_partials/category-header.tpl
the theme of addons continue to have this problem and you need to edit only catalog/listing/category.tpl
the problem is not only on these h1, but in the use of these titles. The titles are used to pass important words to index the pages, but if I use them with words like Best sales or New products it has no sense (they are not bugs but it is not good for seo) the goal is to index these pages on certain keywords everything else must not hinder this goal.

bye

**Comment by azitafomo** [comment]
> 

I am sorry about many questions :) 
public_html/templates/catalog/listing/category.tpl
is this file that I can not see h1 

is it the file that should be edit?
![00000](https://user-images.githubusercontent.com/57670369/68755814-4be05500-061e-11ea-9533-1cf6ddedf9b1.JPG)

**Comment by azitafomo** [comment]
should I remove this part? but I do not see any h1 here
![00000000](https://user-images.githubusercontent.com/57670369/68755931-8a760f80-061e-11ea-97b2-cc03e4da986b.JPG)

**Comment by Maofree** [comment]
![1](https://user-images.githubusercontent.com/653230/68755925-93a8b180-0609-11ea-84c9-420c2b363c1c.png)

it is around {$category.name}
search this code in listing folder

attach here the folder in a zip file

**Comment by Maofree** [comment]
however the codes are different from your site and that file

**Comment by azitafomo** [comment]
Wwoo your language is Persian like me?

**Comment by Maofree** [comment]
no is your site
https://20bekhar.com/33-juicer

one of the sites that I development is this
https://www.lampadaribartalini.it/luce-illuminazione-vendita-online/6-lampadari-sospensione

**Comment by azitafomo** [comment]
great thank you that you are helping me. I am really in bad situation and I am confused that what is wrong in my site that my website is going back and not be stable in first page. many sites that are working in my job are really not good in content and many many items in hrefs, gtmetrix but they are  in higher position than me.
I will send you the zip now, I am searching in my server.
My friend please if you see any huge or little problem about my site that will help me, please tell me, I will be thankful really :)

**Comment by azitafomo** [comment]
[send to help.txt](https://github.com/PrestaShop/PrestaShop/files/3840768/send.to.help.txt)

it is the file :)))
![Capture](https://user-images.githubusercontent.com/57670369/68758645-6cf77480-0623-11ea-8836-8f77f169a0f8.JPG)
should I  remove this part that I show you?

**Comment by Maofree** [comment]
`    {*<div class="hidden-md-up">
        <h1 class="hrxmobile-view-category-title">{$category.name}</h1>
    </div>*}`
