### ISSUE TITLE
Language error in back-office "Uncaught ReferenceError: file_not_found is not defined at gb.js:1"

### ISSUE THREAD

**Issue by benwallis** [PrestaShop/PrestaShop#10471]
**Describe the bug**
When language being used is not English (English) the following error is shown in error console when any page in back office uses rich text editor (TinyMCE):

`Uncaught ReferenceError: file_not_found is not defined at gb.js:1`

I believe this is because the "iso_user" variable is used to load a file for TinyMCE. When the language in PrestaShop is set to "English GB", the "iso_user" is set to "gb" (the "iso_code" for English GB stored in the "ps_lang" database table). This can be seen by viewing the page source when editing a product:

`var iso_user = 'gb';`

TinyMCE tries to load the file from "/js/tiny_mce/langs" - but there is no "gb.js" in that folder. 
If you look at the top of the "en.js" file in that folder, it is "en_GB" anyway.

PrestaShop should tell TinyMCE to use the "en.js" file for the "English GB" language, as well as the "English (English)" language. 

**To Reproduce**
1. Go to International > Localization
2. Change Configuration > Default Language to "English GB (English)". 
3. Change Configuration > Set language from browser to "No"
4. Change Configuration > Set default country from browser language to "No"
5. Go to Languanges tab
6. Disable "English (English)" ID#1 by clicking green tick in the "Enabled column"
7. Make sure browser developer tools is enabled and displayed
8. Go to Catalog > Products
9. Click "+ New Product" button to create a new product.
10. The error is displayed in the error console

**Additionnal information**
PrestaShop version: 1.7.5 (develop branch)
PHP version: 7.1.12

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/11NcQaB1-muswee1LmwKyECC-Su80pMuq/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

I did not manage to reproduce the issue with the last version 1.7.4.2. / 1.7.5.0 (develop)
I attached a video record.
1.7.4.2 => https://drive.google.com/file/d/11NcQaB1-muswee1LmwKyECC-Su80pMuq/view
1.7.5.0 => https://drive.google.com/file/d/1Dn4ATOcn3gTQcJF9B0x7KALIGI0ENL92/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by benwallis** [comment]
I forgot the last step - step 9 should be:

9. Click "+ New Product" button to create a new product.

Please check again by adding a new product.

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2 / 1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/45684471-c0b51d80-bb46-11e8-95af-233ee309792e.png)
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment]
@khouloudbelguith Can you try to reproduce it with 1.7.6.0 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

No, I don't have the same error in the console as reported previously with PS1.7.6.0beta1, just 404 about CLDR.
https://drive.google.com/file/d/1nquxL3MK1UL6_QFGuKwoKqXhWP1iExrh/view
Thanks!

**Comment by marionf** [comment]
Thank you @khouloudbelguith :+1:

**Comment by itsmemukesh21** [comment]
http://prntscr.com/o00bee

**Comment by khouloudbelguith** [comment]
Hi @itsmemukesh21,

We couldn't reproduce the issue with PS1.7.6.0beta1, that's why this issue is closed.

Thanks for your understanding!

**Comment by itsmemukesh21** [comment]
So we need toupgrade our shop to latest ?

**Comment by itsmemukesh21** [comment]
we are using  1.7.4.4

**Comment by khouloudbelguith** [comment]
@benwallis, yes you can upgrade your shop.
But PrestaShop 1.7.6.0 stable version will be released soon.

Thanks!

**Comment by musicpanda** [comment]
One shop solved this by copying en.js to create gb.js in the directory /js/tiny_mce/langs. The first line of the content needs to be changed.

**Comment by gray-b** [comment]
There is still a problem, and I am using ps1.7.7.5 and 1.7.7.6

![ps-gb js-missing](https://user-images.githubusercontent.com/22105014/130081978-df049ff1-b39f-4078-ac97-554a0332a275.jpg)

I have copyied en.js to create gb.js in the directory /js/tiny_mce/langs.

First line of en.js changed to en_US
and gb.js changed to en_GB
