### ISSUE TITLE
Active facet filter even on category links !!!

### ISSUE THREAD

**Issue by sytou** [PrestaShop/PrestaShop#10476]
Hello,

All Category pages are interpreted as pages filtered by the Blocklayered module (see the result on the category page: https://www.cavesnotredame.com/3-achat-champagne). The Active Filters block appears on the left column and the module settings I left on the non-indexing of filtered pages blocked my indexing by Google.

How can I fix this bug to allow me to return to non-indexing the pages of the facet filter?

Thank you for your help.

![bug-blocklayered](https://user-images.githubusercontent.com/12085103/45686821-6bc8d580-bb4d-11e8-8b00-98f5f722a335.png)

**Additionnal information**
PrestaShop version: 1.6.1.16
PHP version: 5.4.45-1~dotdeb+6.1
Blocklayered Module Version v2.2.1

**Comment by khouloudbelguith** [comment]
Hi @sytou,

Could you please add steps to reproduce your issue in a new comment.

Best regards, Khouloud

**Comment by sytou** [comment]
It's easy: just click on one of the links in the main menu at the top right (Champagne / Bordeaux / Rhône ...). The results page is a Category page that is displayed with an empty "Active Filters" insert. This page had a No-Index meta tag because of my setting of the BlockLayered module. I changed the option so as not to penalize my SEO.

**Comment by sytou** [comment]
Here is an image when a filter is active.
![bug-blocklayered-1](https://user-images.githubusercontent.com/12085103/45698897-66798400-bb69-11e8-8364-884879060a04.png)

**Comment by sytou** [comment]
Sorry i close unfortunately the previous comment ...

**Comment by khouloudbelguith** [comment]
Hi @sytou,

What is the exact setting of the BlockLayered module did you made?

Best regards, Khouloud

**Comment by sytou** [comment]
Hi @khouloudbelguith ,

At first, I hadn't touched the setting of the facet filter. It was when GSC told me that my pages were in No-index that I suspected that the problem was the faceted filter. I just then changed the settings as on the screenshot. Nothing more than that. 

![bug-blocklayered-2](https://user-images.githubusercontent.com/12085103/45741469-ed753d80-bbf7-11e8-93eb-3a9949329db9.png)

However, I don't understand why Category links are interpreted by the faceted block as being filtered. That's the bug to look for.

**Comment by khouloudbelguith** [comment]
Hi @sytou,

Could you please try to build the URL index.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by rdy4ever** [comment]
Hi @sytou 
I don't know if this is a PS problem or a problem with your theme, but, if you'd like a quick js workaround to solve your problem, try to add this code to your theme custom.js file (just create one if not present in js/autoload folder):

```
function checkActiveFilters(){
    if ($("#enabled_filters li").length){
        $("#enabled_filters").show();
    }
    else{
        $("#enabled_filters").hide();
    }
}
$(function(){
    checkActiveFilters();
});
$(document).ajaxComplete(function() {
    checkActiveFilters();
});
```

**Comment by sytou** [comment]
Hi @rdy4ever 
Well done !!
The Activated Filters area disappears well when you click on the links in the main menu.
But I didn't find the previous behavior that allowed me to indicate that for any filter (in the configuration of the faceted module), the Meta Robots tag was at noindex, nofollow.
A regression certainly of the faceted module. 
Please do not close this ticket.

**Comment by khouloudbelguith** [comment]
Hi sytou,

I attached a video record.
https://drive.google.com/file/d/14cGmL3Gr8Aj_TvAn72m7yPuEXupGmIFG/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
