### ISSUE TITLE
The quick access new product and installed modules, they don't work

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#10480]
Describe the bug

The quick access new product and installed modules, they don’t work. If you click on the quick access new product and installed modules, these access are redirect you to Dashboard. They should redirect to new product page for new product and installed modules page for installed modules.

To Reproduce
1. Go to B.O, Dashboard > Quick Access, Click on New product and installed modules

![capture d ecran_320](https://user-images.githubusercontent.com/13449658/46002700-0aee4f80-c0af-11e8-8937-8b566a92dba9.png)

Additionnal information
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
File to update: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/quick_access.xml

**Comment by Quetzacoalt91** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10736
