### ISSUE TITLE
OnBoarding popup is not displayed in the 4/6 step - Get your shop ready for payments

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10488]
**Describe the bug**

The OnBoarding popup is not displayed in the 4/6 step - Get your shop ready for payments.

**To Reproduce**
After a fresh install 1.7.5.0, launch (or reset) the onboarding, in the 4/6 step - Get your shop ready for payments - the popup is not displayed.

**Screenshots**
https://drive.google.com/file/d/1dEwdGazas2KrTekiubKmIE8iXGylD4Ic/view

**Additionnal information**
PrestaShop version: 1.7.5.0 / develop
PHP version: 7.1

**Comment by Quetzacoalt91** [comment]
Done, see https://github.com/PrestaShop/welcome/pull/39
