### ISSUE TITLE
Google Analytics Api - 3 year old bug - Cannot retrieve test results - Multistore.

### ISSUE THREAD

**Issue by gomlers** [PrestaShop/PrestaShop#10481]
Google Analytics API v1.2.2 not working on Multistore.
3 year old bug, no one in the forums can help - and the developer seems to have gone underground.

The problem is that the backoffice panel that should show number of visits, and hence calculate the conversion rate does not work for slave-stores. Only the main stores.

The tutorial for making the correct settings in Google Console is also pretty much outdated, and it's not possible to follow.

**To Reproduce**
1. Install Prestashop 1.6.1.16 or at least 1.6 with Multistore.
2. Set up Google Analytics with Google Analytics API v1.2.2
3. Try to get Google Analytics to show statistics in the panel of BO in Prestashop for Both stores, not just "masterstore".
4. Error reads:
Google API Authorization granted
×Cannot retrieve test results

Screenshot of error in module:
https://snag.gy/Qz60Si.jpg

**Additionnal information**

PrestaShop version: 1.6.1.16 / 1.6.x.x
PHP version: 7.0

Forumposts describing the same bug:
https://www.prestashop.com/forums/topic/606739-api-google-analytics-cannot-retrieve-test-results/
https://www.prestashop.com/forums/topic/443499-cannot-retrieve-test-results/
https://www.prestashop.com/forums/topic/578483-google-api-cannot-retrieve-test-results/
https://www.prestashop.com/forums/topic/347223-module-api-google-analytics-cannot-retrieve-test-results/
https://www.prestashop.com/forums/topic/324595-cannot-retrieve-test-results-api-google-analytic/

**Comment by khouloudbelguith** [comment]
Hi @gomlers,

Thanks for your report.
I attached a video record.
https://drive.google.com/file/d/10cEau4UJt_ESzNKJU7T01UNlXo_sss4Y/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
