### ISSUE TITLE
Installing PrestaShop with SSL is complex because some settings are not acknowledged

### ISSUE THREAD

**Issue by delete13** [PrestaShop/PrestaShop#10482]
**Describe the bug**
If the user installs Prestashop directly through https, you should set PS_SSL_ENABLED and PS_SSL_ENABLED_EVERYWHERE to one at the install level. 

Otherwise, we fall down in a permanent loop and finally a fatal error : too much redirect.

**To Reproduce**

Try to install Prestashop 1.7 on a HTTP server with a permanent redirect to HTTPS

**Additionnal information**
PrestaShop version: 1.7+
PHP version: ALL

**Comment by khouloudbelguith** [comment]
Hi @delete13 ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by delete13** [comment]
There are no error. There are no required screenshot, no javascript required as well, neither apache or PHP log, neither a debug mode necessary ...

The issue is simple and I explain why and how in my initial post.

**Comment by khouloudbelguith** [comment]
Hi @delete13,

I manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/13vBUNbH_Tfq9YiCuyuB1-s-XJbXjzMTU/view
In the log I found this:

```
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:58:49 +0000] "GET /174/1742_https/ HTTP/1.1" 302 1948 "https://127.0.0.1:8090/174/1742_https/install/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:58:49 +0000] "GET / HTTP/1.0" 400 0 "-" "-"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:58:50 +0000] "GET / HTTP/1.0" 400 0 "-" "-"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:59:15 +0000] "GET /174/1742_https/admin HTTP/1.1" 301 791 "https://127.0.0.1:8090/174/1742_https/install/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:59:15 +0000] "GET /174/1742_https/admin/ HTTP/1.1" 302 880 "https://127.0.0.1:8090/174/1742_https/install/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:59:21 +0000] "GET / HTTP/1.0" 400 0 "-" "-"
apache-upgrade-presta-dev | 10.1.37.1 - - [19/Sep/2018:07:59:21 +0000] "GET / HTTP/1.0" 400 0 "-" "-"
```

We will see how to fix it.

Best regards, Khouloud

**Comment by delete13** [comment]
In addition I would like to add ;

Nginx conf 

```
server {
        listen 80;
        server_name demo.common-services.com;
        return 301 https://demo.common-services.com$request_uri;
}

server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/STAR_common-services_com.crt;
        ssl_certificate_key /etc/nginx/ssl/common-services.key;

        server_name demo.common-services.com;

        root /var/www/demo/cdiscount;
        index index.php index.html;


        location ~ \.php$ {
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        }

        location / {
                try_files $uri $uri/ /index.php?$args;
        }


        # Symfony controllers
        location /admin/ {                                  # [REQUIRED EDIT] the name of your admin directory
                if (!-e $request_filename) {
                    rewrite ^/.*$ /admin2/index.php last;   # [REQUIRED EDIT] the name of your admin directory
                }
        }

}
```
I install Prestashop through http://demo.common-services.com/install

Obviously, nginx redirect me to https://demo.common-services.com/install

The install process finished, i can reach my admin without hassle.

But once i'm logged in, if i'm clicking on any tab, for instance "modules" tab, i'm infinitely redirected (R301, R302) because PS_SSL_ENABLED and PS_SSL_ENABLED_EVERYWHERE are equal to 0 per default. 

Conclusion : PS_SSL_ENABLED and PS_SSL_ENABLED_EVERYWHERE have to be enabled if Prestashop is installed from HTTPS scheme, what will be the most frequent case in a near future.

**Comment by alx741** [comment]
Just stumbled upon this issue. The fix was to enable SSL as OP said.

```sql
update ps_configuration set value=1 where name like '%PS_SSL_ENABLED%';
```
