### ISSUE TITLE
classic theme footer block design

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#10483]
Why PrestaShop not interested in to correct the footer block's design of classic theme?

PrestaShop version: 1.7.4.2
PHP version: 7.2

![ps-classic-theme-footer](https://user-images.githubusercontent.com/40850132/45731165-c9aff880-bbf3-11e8-85fe-d1e27cad574f.png)

**Comment by khouloudbelguith** [comment]
Hi @Akashvastarpara,

Is there any bug that you manage to reproduce it in the footer block?
What kind of corrects do you propose?

Best regards, Khouloud

**Comment by rdy4ever** [comment]
I think he s reffering to the fact that the footer columns are not correctly distributed to the 12 col grid. I'll try a PR for this and revert.

**Comment by rdy4ever** [comment]
OK. Here's the PR: #10484
Screenshot:
![image](https://user-images.githubusercontent.com/12268701/45741361-0da8fa80-bc00-11e8-8906-4a0f3e4f593d.png)

**Comment by khouloudbelguith** [comment]
Hi,

Thanks @rdy4ever, 
nice catch :)

Best regards, Khouloud

**Comment by Akashvastarpara** [comment]
Good Job! @rdy4ever
