### ISSUE TITLE
Migrate "Advanced Parameters > Team > Employees > Add new employee" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10503]
Part of Symfony migration project
Type: page

Todo:
- [x] Migrate CRUD page https://github.com/PrestaShop/PrestaShop/pull/12214

**Comment by matks** [comment]
@LouiseBonnard spotted by Rokas:
https://prnt.sc/me9rq5
In the Employee form, you can choose the "default page" for an Employee and 2 of the options are displayed identical.

In fact it is 2 different pages:
- one allows to control Shop Groups for multistore management
- one allows to control Shop URLs for multistore management

We need to choose 2 different wordings to relate to them. I suggest "Multistore Groups" and "Multistore URLs", what do you think ?

**Comment by LouiseBonnard** [comment]
@matks, thanks for spotting this mistake! I'm alright with the two suggestions, are you able to let me know under what localization these strings are? Perhaps we would have to modify their domains in the meantime. :-)

Also, this double wording can be found in the 'Permission' page of the Advanced Parameters > Team section of the back office. Do you think that it can be changed here as well?

**Comment by matks** [comment]
@LouiseBonnard After checking further, I discovered these are actually the `Tabs` (1 tab = 1 item of the navbar in the backoffice) values which are translated.
The issue comes from [this file](https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/tab.xml#L428), lines 428 et 431. Two tabs who share the same id "Multistore" and consequently are translated the same.

In order to fix the translation, we need to modify the right translation file from folder `install-dev/langs/`.
@Quetzacoalt91 do you know how to modify tabs translations like this one ?

**Comment by Quetzacoalt91** [comment]
I'm afraid you have to make this update manually:

https://github.com/PrestaShop/PrestaShop/blob/018a913a1b79e56c725b7b51c5bbc37b4ab352cd/install-dev/upgrade/php/ps_1750_update_module_tabs.php#L71-L86

**Comment by LouiseBonnard** [comment]
Sorry, I might have missed something, how the module tabs could be related to the multistore management? I'm still discovering the (dark) technical side of PrestaShop, aha! Anyway, we can talk about it tomorrow, no worries. :-)

**Comment by matks** [comment]
Created https://github.com/PrestaShop/PrestaShop/issues/13166 to handle this issue so we dont forget, as this issue is now closed
