### ISSUE TITLE
Migrate "Catalog > Attributes & Features > Attributes" listing page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10511]
Type: page
Part of Symfony migration project

URL: `/admin-dev/index.php/sell/catalog/attribute-groups`

## Status

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/14040
- [x] Add helper card
- [x] Enable "export" action
- [x] Fix drag-and-drop
- [x] Check that known issues (see below) is fixed
- [x] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [x] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by marionf** [comment]
Can we solve this issue during the migration: #11217 ?

**Comment by colinegin** [comment]
This page needs a Helper card - design still needs to be provided @TristanLDD

**Comment by TristanLDD** [comment]
> This page needs a Helper card - design still needs to be provided @TristanLDD

The helper card design is now ready for integration ;)

**Comment by zuk3975** [comment]
> The helper card design is now ready for integration ;)

Attributes helper card implemented within #14040

**Comment by colinegin** [comment]
@matks it seems that this issue is done, can we close it ?

**Comment by zuk3975** [comment]
Attribute page (technically called `attribute-group`) is still missing create,edit,export actions. (check AttributeGroupController)
Attribute values page (techically called `attribute`) is missing drag and drop positioning. (check AttributeController)

**Comment by JevgenijVisockij** [comment]
@PrestaShop/prestashop-product-team 
Attribute drag and drop is working. But it works only when you are filtering by position. Default filter for attribute page is position, but for attribute values it's id_attribute. 

Should I change the default filter of attribute values to position as well?

**Comment by colinegin** [comment]
Yes I think we should change it as well. 
But have you tried using the position field to make a filter ? It does not seem to work, as explained on the issue here : https://github.com/PrestaShop/PrestaShop/issues/11217

**Comment by matks** [comment]
> Attribute page (technically called `attribute-group`) is still missing create,edit,export actions. (check AttributeGroupController)

Hi @zuk3975 I checked and for me the "Export" action works. By "Export" action are we referring to "Export to SQL" button ?

I close this issue but if you tell me something is missing I will open it again 😊
