### ISSUE TITLE
Provide TrustedProxy fields in parameters.php for reverse proxies

### ISSUE THREAD

**Issue by amtriorix** [PrestaShop/PrestaShop#10526]
Symphony needs to be informed of trusted proxies. When Prestashop is behind a rev proxy with
ssl termination, X-Forward fields should be interpreted to accept http as https on the webserver,
as the ssl sliders should also detect in that way the reversing.

SSL pass through, works. But this means loss of performance, better way is to have ssl termination
on the reverse proxy, pass further http requests to the backend, however, inform prestashop to enforce https links when X-Forward-proto is https.

That way a reverse proxy like HAproxy, pound, nginx or nuster would speed up dramatically prestashop.

Having incoming http requests means also the better way to cache with above methods.

As workarround, please post in answer how to tweak current code with this setting.

**Comment by khouloudbelguith** [comment]
Hi @amtriorix,

Have you an issue similar to this ticket: #10482?

Best regards, Khouloud

**Comment by amtriorix** [comment]
> Hi @amtriorix,
> 
> Have you an issue similar to this ticket: #10482?
> 
> Best regards, Khouloud

Dear, It is NOT there is the world SSL and REVERSE PROXY the issues are related.

Here I state something very profound in terms of reverse proxy a site with SSL termination on a
load balancer or reverse proxy (with or without cache) forwarding HTTP connections to one or more backend HTTP servers.

For this to work you need to adjust Symphony. In laravel there is the package:
https://github.com/fideloper/TrustedProxy

Similar has to be there for Symphony and Prestashop, see more:
https://symfony.com/doc/current/deployment/proxies.html

Then tune the setup screens and parameters,php ...

This is related somehow to a forge ticket that was not properly assigned either:
http://forge.prestashop.com/browse/BOOM-3406

So the goal here is to correctly inform the framework there is use of SSL Termination on a
reverse proxy that handles HTTPS  and where (a) backend server(s) handle only HTTP request,
however they should enforce https links.

Do notice, then Symphony is not informed about this, the settings screen of prestashop DOES NOT PASS the SSL test, so the sliders to enable SLL on ALL pages do not become visible as there are a issues during setup as well.

So prestashop (symphony) should take into account properly:

X-Forwarded-For
X-Forwarded-Host
X-Forwarded-Proto
X-Forwarded-Port

Directives when it is told, there is another server doing the SSL and parameters.php should define parameters for this so the code should not be patched.

More:
https://github.com/symfony/symfony/issues/25543

**Comment by khouloudbelguith** [comment]
@mickaelandrieu what do you think about this issue?

**Comment by amtriorix** [comment]
I come back to this and indeed. It seems Prestashop 1.7.x is using Symphony 3:

``
#grep 'const VERSION =' vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php
 
    const VERSION = '3.4.12';
``

And indeed there is :
``
grep 'X_FORWARDED_' vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Request.php

    const HEADER_X_FORWARDED_FOR = 0b00010;
    const HEADER_X_FORWARDED_HOST = 0b00100;
    const HEADER_X_FORWARDED_PROTO = 0b01000;
    const HEADER_X_FORWARDED_PORT = 0b10000;
    const HEADER_X_FORWARDED_ALL = 0b11110; // All "X-Forwarded-*" headers
    const HEADER_X_FORWARDED_AWS_ELB = 0b11010; // AWS ELB doesn't send X-Forwarded-Host
    const HEADER_CLIENT_IP = self::HEADER_X_FORWARDED_FOR;
    const HEADER_CLIENT_HOST = self::HEADER_X_FORWARDED_HOST;
    const HEADER_CLIENT_PROTO = self::HEADER_X_FORWARDED_PROTO;
    const HEADER_CLIENT_PORT = self::HEADER_X_FORWARDED_PORT;
        self::HEADER_CLIENT_IP => 'X_FORWARDED_FOR',
        self::HEADER_CLIENT_HOST => 'X_FORWARDED_HOST',
        self::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        self::HEADER_CLIENT_PORT => 'X_FORWARDED_PORT',
        self::HEADER_CLIENT_IP => 'X_FORWARDED_FOR',
        self::HEADER_CLIENT_HOST => 'X_FORWARDED_HOST',
        self::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        self::HEADER_CLIENT_PORT => 'X_FORWARDED_PORT',
        self::HEADER_X_FORWARDED_FOR => 'for',
        self::HEADER_X_FORWARDED_HOST => 'host',
        self::HEADER_X_FORWARDED_PROTO => 'proto',
        self::HEADER_X_FORWARDED_PORT => 'host',
``

So there is the way to implement this using Symphone 3.x : 
https://symfony.com/doc/3.4/deployment/proxies.html

As the parameters should be configurable in app/config/parameters.php
in a first phase and in a second phase also in the webgui of the setup and admin backend.

**Comment by amtriorix** [comment]
Ok and finally I found this snippet too in the admin section but seems nothing provided in the 
store itself to handle X-Forwarded-... data.

> cat adminXXXXX/index.php
> 
> //$kernel = new AppCache($kernel);
> // When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
> //Request::enableHttpMethodParameterOverride();
> $request = Request::createFromGlobals();
> Request::setTrustedProxies([], Request::HEADER_X_FORWARDED_ALL);

**Comment by khouloudbelguith** [comment]
ping @mickaelandrieu

**Comment by amtriorix** [comment]
Additionally the backend should never be cached.

proposed changes:

* classes/controller/AdminController.php

old:
```
public function initHeader()
    {
        header('Cache-Control: no-store, no-cache');
```
new:
 ```
   public function initHeader()
    {
        // header('Cache-Control: no-store, no-cache');
           header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
           header('Pragma: no-cache');
           header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
```

**Comment by khouloudbelguith** [comment]
Hi @amtriorix,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @amtriorix,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
