### ISSUE TITLE
PDF Invoice file invalid 

### ISSUE THREAD

**Issue by VytautasI** [PrestaShop/PrestaShop#10525]
When someone place an order the invoice is generated and is downloadable. But none of known PDF readers can't open it. Error messages: invalid file, damaged file, unsupported file and etc.

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
HI @VytautasI,

Thanks for your report, I did not manage to reproduce the issue with the last version 1.6.1.20.
Have you tried to open the downloadable file with another computer?

Best regards, Khouloud

**Comment by VytautasI** [comment]
Hi Khouloud
Some mystery is happening. Yesterday I changed pdf templates and some modules with original files via FTP, but nothing happened, pdf was damaged.
Today everything works fine, as nothing has happened.
Best regards,
VytautasI
