### ISSUE TITLE
Missing trophy.png image in back office on wamp64 PS installation.

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#10528]
**Describe the bug**
Hello, after fresh installation for currently newest version of Prestashop (1.7.4.2) the trophy.png icon is missing. I'm working on wamp64. The returned path is:

`http://localhost/prestashop/admin33837asx8/index.php/configure/modules/gamification/views/img/trophy.png`

**To Reproduce**
1. Just set up newest version of PrestaShop on wamp64.

**Screenshots**
![zrzut ekranu 2018-09-20 08 33 23](https://user-images.githubusercontent.com/38382175/45800178-5c15d200-bcb0-11e8-909a-d53f37730cb8.jpg)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.4

**Comment by Quetzacoalt91** [comment]
Thank you for your feedback @randompassanger 

The issue has been fixed with https://github.com/PrestaShop/gamification/pull/21, but we haven't released the 2.0.3. We expect doing it at the beginning of the next week.

I'm closing as it is already fixed.
Regards
