### ISSUE TITLE
We should update USEFUL LINKS in the Dashboard page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10534]
**Describe the bug**

The USEFUL LINKS should be updated in the Dashboard page.
```
Bug Tracker
Report issues in the Bug Tracker

```
Should be replaced by [GitHub](https://github.com/PrestaShop/PrestaShop/issues/new/choose)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/45822346-8afd6980-bceb-11e8-8a4d-995089457ee1.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 / develop
PHP version: 7.1

**Comment by MathiasReker** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/10535

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

This issue is fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/10151
You need to close your PR:

Best regards, Khouloud

**Comment by MathiasReker** [comment]
#10535 fix typo
#10151 fix url
