### ISSUE TITLE
JS error when editing a product if post_max_size is 0 - PS 1.6

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#10531]
**Describe the bug**
If you configure `post_max_size = 0` in php.ini and try to edit a product, there's a JS error in files `admin/themes/default/template/controllers/products/helpers/uploader/attachment_ajax.tpl` and `admin/themes/default/template/controllers/products/helpers/uploader/ajax.tpl` because variable `$post_max_size` is empty.

The problem is in function `getPostMaxSizeBytes()` from Uploader class.

It seems that the maximum file size limitation is 4G (https://github.com/blueimp/jQuery-File-Upload/wiki/Frequently-Asked-Questions).

**Additionnal information**
PrestaShop version: PS `1.6.1.19` and above.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report & your fix.
I manage to reproduce this issue with PS 1.6.1.20.
![image](https://user-images.githubusercontent.com/16067358/45812614-89727800-bcd0-11e8-85ec-8d1058d23708.png)
Fixed by #10532

Best regards, KHouloud

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
