### ISSUE TITLE
Migrate "Catalog > Brand & Suppliers > Suppliers" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10545]
Type : page
Part of Symfony migration project

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/11153
- [x] Add empty state https://github.com/PrestaShop/PrestaShop/pull/12498

Access: `/admin-dev/index.php/sell/catalog/suppliers/`

**Comment by BilalDr** [comment]
This page needs to have an Empty States.
refer to this issue : #10434

Thanks

**Comment by matks** [comment]
@colinegin Bilal said this page needs an Empty State, but when I look at https://github.com/PrestaShop/PrestaShop/issues/10434 I cannot see the related Empty State. Is it a mistake ?

**Comment by colinegin** [comment]
Sorry, I forgot the empty state part ! It should be fine now, I've added details in the same issue. I will update the URL document tomorrow so that you can have the correct user doc urls.

Just let me know if you need anything else !
