### ISSUE TITLE
Migrate "Catalog > Brand & Suppliers > Add new / edit supplier" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10541]
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate CRUD page https://github.com/PrestaShop/PrestaShop/pull/15650/
- [x] Add tinyMCE https://github.com/PrestaShop/PrestaShop/pull/16457
- [ ] Fix visual bug https://github.com/PrestaShop/PrestaShop/issues/15649
- [x] Un-hide listing and CRUD page (see https://github.com/PrestaShop/PrestaShop/issues/10545)

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by marionf** [comment]
Issue on supplier page: http://github.com/PrestaShop/PrestaShop/issues/13445

**Comment by matks** [comment]
@marionf This is not related to the migration, this is an old bug of TinyMCE. TinyMCE is not responsive. TinyMCE does not care. TinyMCE is wild 👹 .

**Comment by colinegin** [comment]
Can we close this issue @matks ?

**Comment by matks** [comment]
No it's not finished, I need to go through the checklist to make sure everything is right

**Comment by matks** [comment]
Closing to make it more clear, I will not forget
