### ISSUE TITLE
Migrate "Catalog > Brand & Suppliers > Brands" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10542]
Part of Symfony migration project
Type: page

Link admin-dev/index.php/sell/catalog/brands

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/9337
- [x] Make sure ps_themecustom is compatible once migration is done - see below
- [x] Fix filtering for double-grid listing https://github.com/PrestaShop/PrestaShop/pull/12928

**Comment by marionf** [comment]
We need to think to change this link in ps_themecusto module:
![capture d ecran_414](https://user-images.githubusercontent.com/13449658/46619521-91c91080-cb22-11e8-8a1e-1c44254b0ed2.png)

**Comment by marionf** [comment]
Issue related to brands address list: 
- [x] #11082

**Comment by colinegin** [comment]
I close this issue, an issue for theme custo has been created on the dedicated repo : https://github.com/PrestaShop/ps_themecusto/issues/9
