### ISSUE TITLE
Migrate "Catalog > Brand & Suppliers > Brands > Add new brand address" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10544]
Part of Symfony migration project
Type: page

Todo:
- [x] Migrate CRUD page https://github.com/PrestaShop/PrestaShop/pull/12795
- [x] Old bug #9611
- [x] Old bug #9610

**Comment by marionf** [comment]
Issues related to this page:

- [x] #9611
- [x] #9610

**Comment by matks** [comment]
> Issues related to this page:
> 
> * [x]  #9611
> * [x]  #9610

@marionf The migration fixes these 2 issues. Can we close them or do you want to check it ?

**Comment by marionf** [comment]
Thank you @matks we closed them :)
