### ISSUE TITLE
Migrate "Catalog > Monitoring" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10552]
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate all grids of the page https://github.com/PrestaShop/PrestaShop/pull/13529
- [x] Implement product actions usable in grid (see `@todo` in https://github.com/PrestaShop/PrestaShop/pull/13529/files) https://github.com/PrestaShop/PrestaShop/pull/16267
- [x] Fix monitoring grids id configuration https://github.com/PrestaShop/PrestaShop/pull/15757
- [x] Add Helper card (see below) https://github.com/PrestaShop/PrestaShop/pull/16267
- [x] Fix old issue (see below): remove a button
- [x] Unhide page https://github.com/PrestaShop/PrestaShop/pull/16588

Old issue: https://github.com/PrestaShop/PrestaShop/issues/11482

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by BilalDr** [comment]
This page needs to have an Helper Cards.
refer to this PR : #10434

Thanks

**Comment by marionf** [comment]
If during migration we can solve this issue #11482 it will be nice (just a button to remove)

**Comment by matks** [comment]
@zuk3975 1st step done, now come the others 😄 
Also we need to go through the checklist to be sure we forgot nothing

**Comment by marionf** [comment]
Improvement suggestion posted here: http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/33336487-finding-duplicate-products

**Comment by ghost** [comment]
Hi,

An issue has been reported about this page a couple of days ago. Weird behavior when applying a filter in the "product without image" block #14923 
Worth having a look at it.

**Comment by zuk3975** [comment]
Fixed some multishop behavior issues with this #14991 and noticed the following:
As a merchant in `All shops context` i would expect to see data fetched from all of my shops, but currently the data is taken from default shop (I guess this is because if we don't filter shop_id in query, we would see duplicated products) maybe its associated with improvement suggested above ? or perhaps it should be considered as a broader, Multi-shop behavior issue?

**Comment by ghost** [comment]
Hi @zuk3975,

We checked with @marionf.
- Regarding the improvement suggested, it needs more information so we won't implement it now. @marionf contacted the idea author to know more.

- Regarding the multishop behavior, we'll have to do some research about it to see how to have the best behavior possible, as you said it is a broader Multi-shop issue. We'll keep that for later.

Ok for you?
Let us know if you have more questions!
