### ISSUE TITLE
run cs fixer on root folder?

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#10561]
Can we run php-cs-fixer on the root folder of Prestashop to get code standard up to date?

**Comment by khouloudbelguith** [comment]
Hi @Mreker,

Thanks to follow this link: https://medium.com/@mickael_andrieu/chez-prestashop-on-a-fait-le-choix-de-php-cs-fixer-et-la-configuration-est-disponible-%C3%A0-la-racine-b21b9cbfa944 & feedback.

Best regards, Khouloud
