### ISSUE TITLE
Migrate "Design > Pages" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10565]
Type: page
Part of Symfony migration project

![capture d ecran 2019-01-04 a 12 10 25](https://user-images.githubusercontent.com/3830050/50685505-c19c8d00-1019-11e9-9056-d89d46a9cab9.png)

Todo:
- [x] Migrate grid 1 https://github.com/PrestaShop/PrestaShop/pull/10877
- [x] Migrate grid 2 https://github.com/PrestaShop/PrestaShop/pull/12981
- [x] Helper card https://github.com/PrestaShop/PrestaShop/pull/13404
- [x] Handle bug about positions incorrectly initialized 😞 (see below) https://github.com/PrestaShop/PrestaShop/pull/13125
- [ ] What should be done for nested URLs ? `/admin-dev/index.php/sell/catalog/categories/?id_category=3` or `/admin-dev/index.php/sell/catalog/categories/3` ?
- [x] Fixes known bugs for this page (see below)
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)  

For bug about positions: https://github.com/PrestaShop/PrestaShop/pull/10877#issuecomment-440275907

For URLs: the decision should be applied to Catalog > Categories grid too

**Comment by matks** [comment]
Needs https://github.com/PrestaShop/PrestaShop/issues/10820 to be solved first as this pages contains 2 grids

**Comment by BilalDr** [comment]
This page needs to have an Helper Card.
refer to this PR : #10434

Thanks

**Comment by marionf** [comment]
We need to think to change this link in ps_themecusto module:
![capture d ecran_413](https://user-images.githubusercontent.com/13449658/46619372-3d259580-cb22-11e8-8100-ce27a79f489b.png)

**Comment by colinegin** [comment]
@CaptainYouz are you going to finish the helper card for this page or can @tomas862 get the work you have already done ?

**Comment by CaptainYouz** [comment]
Hi @colinegin.
The work I started to do on this page (https://github.com/CaptainYouz/PrestaShop/commit/85e0bccc8319784c3e0bec587144a153b667aa73) served as a starter for the implementation of the helper card in https://github.com/PrestaShop/PrestaShop/pull/10529.
@tomas862 can use https://github.com/PrestaShop/PrestaShop/pull/10529 to continue to work on this page.

**Comment by marionf** [comment]
Can we solve this issue during the migration of the page: #11540 & #11546 ?
