### ISSUE TITLE
Migrate "Design > Pages > Add new / edit page category" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10567]
Part of Symfony migration project
Type: page

Todo:
- [x] Migrate CRUD form https://github.com/PrestaShop/PrestaShop/pull/12647
- [x] Handle drag-and-drop behavior https://github.com/PrestaShop/PrestaShop/pull/12974

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/12647

**Comment by jolelievre** [comment]
Thanks everyone!
