### ISSUE TITLE
fixed a css error on PSGDPR module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10573]
Hi

**Describe the bug**
active the psgdpr module and the newsletter block, then go to the bottom and you will see many white space

the problem is due from this css code in front.css from the float:left

`form div label {
    float: left;
}`

it is necessary to remove that float left to the gdpr label so try with this code

`#footer .psgdpr_consent_message {
    float: none;
}`

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/45831166-fac91f80-bcfe-11e8-8192-0bed580f07f6.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I did not manage to reproduce the issue with the last version 1.7.4.2 & the psgdpr module v1.1.0.
https://drive.google.com/file/d/1pmvHvvQbYMsLGqcEQv6R5GsX-47DyaGm/view
Thanks to check the video record & feedback.

Best regards, Khouloud

**Comment by Maofree** [comment]
could be
but it happens on two sites that I manage (also in a clean installation)
and if I remove that left I'll solve

check a little with the chrome web tool

**Comment by khouloudbelguith** [comment]
Hi @maofree,

![image](https://user-images.githubusercontent.com/16067358/45832878-644b2d00-bd03-11e8-809a-b6b36f2c6149.png)

Best regards, Khouloud

**Comment by Maofree** [comment]
it is strange
you have a different code for that label

**Comment by khouloudbelguith** [comment]
@maofree,

I downloaded the module from this link: https://github.com/PrestaShop/psgdpr/

Best regards, Khouloud

**Comment by Maofree** [comment]
it is due from the classic theme in front.css file
can you check if you have this code at line 102?

![1](https://user-images.githubusercontent.com/653230/45835447-741a3f80-bd0a-11e8-9de9-f163f730adf1.png)

**Comment by Maofree** [comment]
ok understood
it is due from the payplug module

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud
