### ISSUE TITLE
Migrate "Orders > Orders" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10582]
Type: page
Part of Symfony migration project

## Status

Todo:
- [x] Prepares Command API for migrating Order view page https://github.com/PrestaShop/PrestaShop/pull/13712
- [x] Migrate list https://github.com/PrestaShop/PrestaShop/pull/13988
- [x] Use icons instead of dropdown column for Orders page list https://github.com/PrestaShop/PrestaShop/pull/15808
- [x] Waiting for refacto specs and mock-ups
- [ ] Check previously known bugs (see below) are fixed
- [ ] Handle PDF refactoring (see below)
- [ ] Check there is no performance issue because of SQL sub-queries (see below)
- [x] Introduce new preview feature for grids
- [x] Enable "open in a new tab on right click" feature
- [x] Add KPI header redesigned
- [x] Make client name clickeable
- [ ] Visual enhancements https://github.com/PrestaShop/PrestaShop/issues/15971
- [ ] Improve Behat tests with additional tests (see 1st PR feedbacks)
- [ ] Refactor legacy code in Handlers (see 1st PR feedbacks)
- [ ] Document order preview hook
- [ ] Modify install-dev/data/xml/quick_access.xml file for orders links https://github.com/PrestaShop/PrestaShop/issues/27513

PDF refactoring: https://github.com/PrestaShop/PrestaShop/pull/13988/files#r288999298
SQL sub-queries: https://github.com/PrestaShop/PrestaShop/pull/13988#discussion_r302611856
Bulk change status action: https://github.com/PrestaShop/PrestaShop/issues/14743 and https://github.com/PrestaShop/PrestaShop/issues/14741
KPI header redesigned https://github.com/PrestaShop/PrestaShop/issues/15230
Client name clickeable https://github.com/PrestaShop/PrestaShop/issues/15231
Introduce new preview feature for grids https://github.com/PrestaShop/PrestaShop/pull/14682 and https://github.com/PrestaShop/PrestaShop/issues/14732
Enable "open in a new tab on right click" feature, see https://github.com/PrestaShop/PrestaShop/issues/14736
Introduce new preview feature for grids https://github.com/PrestaShop/PrestaShop/pull/14682

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by marionf** [comment]
Issue on order list:
- [x] #10317
- [x] #13275

**Comment by marionf** [comment]
Don't forget to change the link in notifications part for legacy and symfony pages

![capture d'écran_1418](https://user-images.githubusercontent.com/13449658/56281234-6ac04c80-610c-11e9-874f-057ae332caa8.png)

**Comment by matks** [comment]
Additionnal issue https://github.com/PrestaShop/PrestaShop/issues/14159

**Comment by sarjon** [comment]
> Additionnal issue #14159

List just goes on. :sweat_smile:

**Comment by matks** [comment]
> > Additionnal issue #14159
> 
> List just goes on. 😅

It's a legacy issue. I think it might be fixed by using the grid because bulk action does not trigger if nothing is selected

**Comment by MatShir** [comment]
#13890
