### ISSUE TITLE
Migrate "Shop parameters > Traffic & SEO > Search Engines > Add new / edit search engine" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10590]
Part of Symfony migration project

- [x] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)
- [x] #19417 - Add information message for multistore

**Comment by Progi1984** [comment]
@matks Can we close or does it remain some actions to finish the migration ?

**Comment by matks** [comment]
> @matks Can we close or does it remain some actions to finish the migration ?

One question for @marionf in https://github.com/PrestaShop/PrestaShop/issues/19416 to confirm 😉

**Comment by marionf** [comment]
Humm, I don't see any question in https://github.com/PrestaShop/PrestaShop/issues/19416 :thinking:

**Comment by matks** [comment]
> Humm, I don't see any question in #19416 🤔

It was https://github.com/PrestaShop/PrestaShop/issues/19417 😅

**Comment by matks** [comment]
This page is fully migrated 👍
