### ISSUE TITLE
It is impossible to delete a shopping cart from the BO - An error occurred during deletion.-

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10599]
**Describe the bug**

In the BO => Shopping Carts page, when we try to delete a shopping cart, a red alert "An error occurred during deletion." is displayed.
In the 1.7.4.2 => OK
**To Reproduce**
1. Go to BO => Orders => Shopping carts
2. Delete any shopping cart
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/45882681-2b689200-bdaf-11e8-82e4-c6de3e02fd8e.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 / develop
PHP version: 7.1

**Comment by PierreRambaud** [comment]
FYI, it's only happened with fixtures, not with customer carts. :/

**Comment by jolelievre** [comment]
The problem was not that the cart could not be deleted It is actually the appropriate behavior since the cart has an order But the button should not be displayed
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10725
