### ISSUE TITLE
Migrate "International > Locations > Add new / edit zone" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10603]
Part of Symfony migration project

- [x] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)

**Comment by Progi1984** [comment]
@matks OK for closing ?

**Comment by matks** [comment]
OK
