### ISSUE TITLE
Migrate "International > Taxes > Taxes" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10611]
Type: page
Part of Symfony migration project

Link: `/admin-dev/index.php/improve/international/taxes/`

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/12423
- [x] Migrate configuration form https://github.com/PrestaShop/PrestaShop/pull/12610
- [ ] Unhide controller
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)

**Comment by marionf** [comment]
We need to think to change the link in product page

![capture d ecran_405](https://user-images.githubusercontent.com/13449658/46617790-f5047400-cb1d-11e8-9d8f-f2d24c4c8840.png)

**Comment by sarjon** [comment]
@matks can you assign it to me? :) as well as this one https://github.com/PrestaShop/PrestaShop/issues/10612 ?

**Comment by matks** [comment]
@sarjon I like when you say this ❤️

**Comment by colinegin** [comment]
Hi @matks,

Would it be possible to change one behaviour in this page ?
If the merchant disables to option "Enable tax", then it should automatically disable "display tax in the cart" option, as it doesn't make any sense to have the 2nd option without the 1st one.

Let me know what you think !
