### ISSUE TITLE
Migrate "Shop parameters > Order settings > Statuses > Add new / edit order status" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10621]
## Status

The "Order Statuses" page has been migrated to Symfony but is hidden because there is a few remaining issues. I mistakenly tried to fix all the remaining issues in a single PR https://github.com/PrestaShop/PrestaShop/pull/20442 because each issue needs only some lines of code, so I wanted to submit one PR with medium size rather than PRs with each 10 lines of code.

**It was a mistake** because one issue was eventually found to be much complicated than expected and the PR is blocked so none of the issues are fixed. I will probably have to circle back to submit 1 PR per issue.

So this issue is blocked because of this. Work has been done in https://github.com/PrestaShop/PrestaShop/pull/20442 to fix it but QA has found issues.

<hr>

Part of Symfony migration project
Specs:
https://github.com/PrestaShop/prestashop-specs/pull/83

Todo:
- [x] Migrate page https://github.com/PrestaShop/PrestaShop/pull/17215
- [x] Removes the Icon input (as it is not used anymore)
- [x] @LouiseBonnard  rewording to do, especially on "delivery"
- [x] #19496 Add information message for multistore

**Comment by matks** [comment]
@MatShir Warning: while poking around with @sowbiba we found that enabling one checkbox shows an additional input in the form at the end, with a "preview" button. But we did not understand what it does.

**Comment by MatShir** [comment]
Hi, @matks and @sowbiba new specs of the page have been provided check it on https://github.com/PrestaShop/prestashop-specs/pull/83. If you find missing or unclear behaviors don't hesitate to comment on the PR or DM me.

**Comment by matks** [comment]
Will be done by https://github.com/PrestaShop/PrestaShop/pull/17215
