### ISSUE TITLE
Attempted to call function "idn_to_ascii" from the global namespace.

### ISSUE THREAD

**Issue by emeagenciadigital** [PrestaShop/PrestaShop#10640]
**Describe the bug**
When creating  new account or changin the order status we get error 500 on mail.php. We send emails by mailjet SMTP and testing of the email send works fine.

Attempted to call function "idn_to_ascii" from the global namespace.

**To Reproduce**
1. Create a new account
or 
2. Change order status to one that sends email

**Screenshots**

**When changing order status:**
![error1](https://user-images.githubusercontent.com/18015381/45897073-b93a8200-bd9b-11e8-8e65-4df067466672.png)

**When Creating new account**
![error2](https://user-images.githubusercontent.com/18015381/45897124-dff8b880-bd9b-11e8-8925-fd026c756894.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.25

**Comment by khouloudbelguith** [comment]
Hi @emeagenciadigital,

This issue is occurred due to php-intl extension.
Could you please try to install it, it is required.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by emeagenciadigital** [comment]
Hi, 

Yes that work. Mark it as solve.

**Comment by khouloudbelguith** [comment]
Hi @emeagenciadigital,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Comment by o-Chamie-o** [comment]
I'm sorry but during the prestashop installation, no mention of that.

During the "system checking" prestashop should shout it out that the php-intl extention is needed.
Just a though ;)

**Comment by khouloudbelguith** [comment]
Hi @o-Chamie-o,

This check is added in the next release PS1.7.5.1.
Heres' the PR: https://github.com/PrestaShop/PrestaShop/pull/11937.
Thanks!

**Comment by fahmiimadd** [comment]
thanks buddy, its really help

**Comment by alizeegtd** [comment]
I installed php-intl extension and I still have the problem, how can I check my configuration?

**Comment by khouloudbelguith** [comment]
Hi @alizeegtd,

This issue is currently closed, can you open a new one with more information about your configuration.
Thanks!

**Comment by nuonveyo** [comment]
> I installed php-intl extension and I still have the problem, how can I check my configuration?

you have to make sure that "extension=php_intl.dll" is enable in php.ini

**Comment by Joel-cardenas** [comment]
> > Instalé la extensión php-intl y todavía tengo el problema, ¿cómo puedo verificar mi configuración?
> 
> debe asegurarse de que "extension = php_intl.dll" esté habilitado en php.ini

Thanks!!!!!! You are the best.

**Comment by CASCOLOCO** [comment]
> Hola @emeagenciadigital ,
> 
> Este problema se produjo debido a la extensión php-intl. Podría intentar instalarlo, es necesario. Gracias por comprobar y comentarios.
> 
> Saludos, Khouloud

En efecto era esto lo que ocasionaba mi fallo a la hora de actualizar los estados de pedido y que se reflejarán una vez el cliente comprara
