### ISSUE TITLE
SQL Manager Form page MUST be extensible

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#10652]
**Describe the bug**
Every form in Back Office should be extensible and customizable using [Hooks and templating](https://devdocs.prestashop.com/1.7/modules/concepts/forms/admin-forms/).

But, since we have migrated SQL Manager form page, @sarjon confirmed me that for now, we have NO way to change its form content using a Form Builder as we can do for Configuration forms.

1. we need to find a solution before the release of 1.7.5 (it's a blocker for me /c  @eternoendless)
2. we must not migrate any other form page until we figure out how to fix this bug

**Additionnal information**
PrestaShop version: 1.7.5-alpha
PHP version: N/A

**Comment by sarjon** [comment]
i guess it's related to this https://github.com/PrestaShop/PrestaShop/issues/10285

**Comment by eternoendless** [comment]
@mickaelandrieu did you have a look at Modok to find out if there are modules hooking up on that page?

**Comment by mickaelandrieu** [comment]
I didn't, but it's not the point: even if no official Addons modules are hooked in this page, we can't migrate pages to something not extensible by PrestaShop developers.

More, as we must provide a consistent way to migrate all the pages, if you want to guess how many modules will be impacted, you must consider **every entity form page** :+1: 

We already have to redo Stock Management and Product page before the next major version. Believe me: migrating pages is not funny enough to be done twice per page :trollface:

**Comment by matks** [comment]
We will probably hide this page in 1.7.5 in order to have the time to handle this problem nicely during 1.7.6 work

**Comment by mickaelandrieu** [comment]
Good to me, so we can move this issue to 1.7.6 milestone?

**Comment by matks** [comment]
Yes indeed.

**Comment by matks** [comment]
Assigned to @sarjon as this is something we need to do for 1.7.6

**Comment by sarjon** [comment]
@matks I think this can be closed as SQL Manager is using new Form system.
