### ISSUE TITLE
AdminPaymentPreferences

### ISSUE THREAD

**Issue by dalyl0x0** [PrestaShop/PrestaShop#10654]
**Describe the bug**

**To Reproduce**
1. Go to 'my back-office'
2. Click on 'Payment and "preferences " '
4. See error:

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected 'const' (T_CONST) in /home/mystore/www/src/Adapter/Module/ModuleDataProvider.php(189) : eval()'d code:36 Stack trace: #0 /home/mystore/www/src/Core/Addon/Module/ModuleRepository.php(392): PrestaShop\PrestaShop\Adapter\Module\ModuleDataProvider->isModuleMainClassValid('paypal') #1 /home/mystore/www/controllers/admin/AdminPaymentPreferencesController.php(46): PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepository->getModule('paypal') #2 /home/mystore/www/classes/controller/Controller.php(138): AdminPaymentPreferencesControllerCore->__construct(false, false) #3 /home/mystore/www/classes/Dispatcher.php(358): ControllerCore::getController('AdminPaymentPre...') #4 /home/mystore/www/admin6378/index.php(95): DispatcherCore->dispatch() #5 {main} Next LogicException: Request stack is empty in /home/mystore/www/app/bootstrap.php.cache:3216 Stack trace: #0 [internal function]: Symfony\Component\Ht in /home/mystore/www/app/bootstrap.php.cache on line 3216

PrestaShop version: 1.7.0.4 
PHP version: 7.0.31
I use for modules payment : PayPal v4.4.2 - by PrestaShop and bank transfer v1.0.10

Thanks for your help!

**Comment by khouloudbelguith** [comment]
Hi @dalyl0x0,

Could you please try to disable the Paypal module, clear cache, check & feedback.

Best regards, Khouloud

**Comment by dalyl0x0** [comment]
Hi @khouloudbelguith,
I can't disable the module Paypal Module in 1.7.0.4
Because : I do not see it in the modules
Best Regards!

**Comment by khouloudbelguith** [comment]
Hi @dalyl0x0,

Could you please rename the paypal folder manually into the folder /Project_Prestashop/modules/
check & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @dalyl0x0,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by dalyl0x0** [comment]
Yes, I solved the problem by removing the Paypal module and it works now
