### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by gkanakaris** [PrestaShop/PrestaShop#10655]
Prestashop 1.7.3.4
tried to upgrade with the last 1click module.
Had php 5.4 changed it to 5.6 still nothing.
tried to rename almost every module folder in case something was failing, still nothing.

**Error at Dashboard**

Warning on line 1920 in file /var/www/vhosts/e-podies.gr/httpdocs/java/classes/Tools.php
[2] curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

**Module page error**

Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
500 Internal Server Error - FatalErrorException

Stack Trace
in modules/autoupgrade/classes/UpgradeTools/Translator.php at line 42   -
    public function trans($id, array $parameters = array(), $domain = null, $locale = null)
    {
        // If PrestaShop core is not instancied properly, do not try to translate
        if (!method_exists(\Context::class, 'getContext') || null === \Context::getContext()->language) {
            return $this->applyParameters($id, $parameters);
        }

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

Set safe_mode = Off in your php.ini file (it's usually in /etc/ on the server). If that's already off, then look around for the open_basedir stuff in the php.ini file, and change it accordingly.

Best regards, Khouloud

**Comment by gkanakaris** [comment]
I tried that and nothing changed.
Any other ideas?

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by gkanakaris** [comment]
There is no folder auto upgrade. The upgrade didn't happen.





-------- Αρχικό μήνυμα --------
Από: khouloudbelguith <notifications@github.com>
Ημερομηνία: 25/09/2018 10:46 (GMT+02:00)
Προς: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Κοιν.: gkanakaris <g.kanakaris@hotmail.com>, Mention <mention@noreply.github.com>
Θέμα: Re: [PrestaShop/PrestaShop] Errors after update (#10655)


Hi @gkanakaris<https://github.com/gkanakaris>,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

It is a server issue.
We just fixed when installing 1.7.4.2: https://github.com/PrestaShop/PrestaShop/pull/9345
Could you please check the issue with your host & feedback.

Best regards, Khouloud

**Comment by gkanakaris** [comment]
What's the issue? What should I tell them?





-------- Αρχικό μήνυμα --------
Από: khouloudbelguith <notifications@github.com>
Ημερομηνία: 25/09/2018 12:31 (GMT+02:00)
Προς: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Κοιν.: gkanakaris <g.kanakaris@hotmail.com>, Mention <mention@noreply.github.com>
Θέμα: Re: [PrestaShop/PrestaShop] Errors after update (#10655)


Hi @gkanakaris<https://github.com/gkanakaris>,

It is a server issue.
We just fixed when installing 1.7.4.2: #9345<https://github.com/PrestaShop/PrestaShop/pull/9345>
Could you please check the issue with your host & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
@gkanakaris,

[CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set]

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
About

> Module page error

> Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
500 Internal Server Error - FatalErrorException

> Stack Trace
in modules/autoupgrade/classes/UpgradeTools/Translator.php at line 42 -
public function trans($id, array $parameters = array(), $domain = null, $locale = null)
{
// If PrestaShop core is not instancied properly, do not try to translate
if (!method_exists(\Context::class, 'getContext') || null === \Context::getContext()->language) {
return $this->applyParameters($id, $parameters);
}

You got that error because an old PHP version running on your server. We published the version 4.3.0 of the module to prevent this crash to happen. On your side, removing the folder `modules/autoupgrade` will make your backoffice working again.

**Comment by gkanakaris** [comment]
I removed the folder from day one. The BackOffice has no problem except the module page brings this error.

I changed the site php to 5.6 but PrestaShop still identifies 5.4



-------- Αρχικό μήνυμα --------
Από: Thomas N <notifications@github.com>
Ημερομηνία: 25/09/2018 12:40 (GMT+02:00)
Προς: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Κοιν.: gkanakaris <g.kanakaris@hotmail.com>, Mention <mention@noreply.github.com>
Θέμα: Re: [PrestaShop/PrestaShop] Errors after update (#10655)


About

Module page error

Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
500 Internal Server Error - FatalErrorException

Stack Trace
in modules/autoupgrade/classes/UpgradeTools/Translator.php at line 42 -
public function trans($id, array $parameters = array(), $domain = null, $locale = null)
{
// If PrestaShop core is not instancied properly, do not try to translate
if (!method_exists(\Context::class, 'getContext') || null === \Context::getContext()->language) {
return $this->applyParameters($id, $parameters);
}

You got that error because an old PHP version running on your server. We published the version 4.3.0 of the module to prevent this crash to happen. On your side, removing the folder modules/autoupgrade will make your backoffice working again.

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

So, in the Advanced Parameters =>  information page, the PHP version is 5.4, but in your server PHP is 5.6?

Best regards, Khouloud

**Comment by gkanakaris** [comment]
Yes.





-------- Αρχικό μήνυμα --------
Από: khouloudbelguith <notifications@github.com>
Ημερομηνία: 25/09/2018 13:10 (GMT+02:00)
Προς: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Κοιν.: gkanakaris <g.kanakaris@hotmail.com>, Mention <mention@noreply.github.com>
Θέμα: Re: [PrestaShop/PrestaShop] Errors after update (#10655)


Hi @gkanakaris<https://github.com/gkanakaris>,

So, in the Advanced Parameters => information page, the PHP version is 5.4, but in your server PHP is 5.6?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

Thanks to follow this link: https://superuser.com/questions/969861/phpinfo-and-php-v-shows-different-version-of-php to solve your issue.

Best regards, Khouloud

**Comment by gkanakaris** [comment]
The update never took place. My prestashop is still 1.7.3.4 so php dont need to be 5.6 right? can it still work with 5.4?
The server admin remove the opebasedir security and the dashboard error gone away.
The module page error is still there.

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

You can follow this link for more details about PrestaShop 1.7 compatibility with PHP: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @gkanakaris,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
