### ISSUE TITLE
Receive customer messages via e-mail - impossible backoffice configuration.

### ISSUE THREAD

**Issue by GutImedia** [PrestaShop/PrestaShop#10659]
Module : Contact form v4.1.1 by Prestashop
Prestashop v1.7.4.2

Video in attached file.

When I try to configure this native module of prestashop, so that the owner of the shop can receive the mails of contacts of his customers, I go in "Modules and services", I search my module then I click on "Configure".

I check "Yes" for the option "Receive customer messages by e-mail" and I save. I am then redirected to the configuration page of the reCaptcha module. 

And if I go back to the configuration page of the contact form module the option automatically returns to "No". and I do not receive emails from my clients.

Can you help us ?

[20180924_103133.zip](https://github.com/PrestaShop/PrestaShop/files/2410134/20180924_103133.zip)

**Comment by khouloudbelguith** [comment]
Hi @GutImedia,

If you try to uninstall the reCaptcha module for just to test when you click save, is there any other redirections?

Best regards, Khouloud

**Comment by GutImedia** [comment]
Hi @khouloudbelguith 

When I disable the reCaptcha module, in the backoffice, I am no longer redirected to the recaptcha configuration and the configuration of the form for "Receiving customer messages by e-mail" remains on "Yes". 

However, the contact form has changed style frontoffice and when I filled the form, I click on "Send", nothing happens, I still do not receive emails from my clients. 
There are no errors in the Chrome console.

**Comment by khouloudbelguith** [comment]
Hi @GutImedia,

Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by GutImedia** [comment]
@khouloudbelguith
I tested the sending of mail via BO> Configure> Advanced Parameters> E-mail and I received the mail ...

**Comment by khouloudbelguith** [comment]
Hi @GutImedia,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by GutImedia** [comment]
@khouloudbelguith

Website URL: https://linstantbleuturquoise.fr/

Informations sur votre serveur Linux #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.0.30-0+deb9u1
Limite de mémoire : 256M
Temps maximal d'exécution : 90
Taille max. pour envoi de fichiers : 200M

See attached files...

**Comment by khouloudbelguith** [comment]
Hi @GutImedia,

Thanks for your feedback.
I you enable the debug mode, you don' have any exceptions?

Best regards, Khouloud

**Comment by GutImedia** [comment]
ok

**Comment by GutImedia** [comment]
We have updated the module in its latest version that the support has transmitted to us ... I emptied the cache ...
We just redo tests and the problem is solved ...
Thanks for your help.

**Comment by khouloudbelguith** [comment]
Hi @GutImedia,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud
