### ISSUE TITLE
Filter on Traffic & SEO migrated page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10669]
**Describe the bug**
Can't filter ASC or DESC by id, page, page title, friendly url

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Click on the arrows for the fields id, page, page title, friendly url
3. Results are not filtered

**Screenshots**
![capture d ecran_307](https://user-images.githubusercontent.com/13449658/45951287-3287de00-c003-11e8-92e6-80b7d037df67.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by jolelievre** [comment]
This is a common bug on all grids, it is fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/10656
