### ISSUE TITLE
Can't configure a module imported by zip

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10665]
**Describe the bug**
Can't configure a module imported by zip

**To Reproduce**
1. Go to Modules Manager
2. Click on Install a module
3. Upload your zip
4. Click on Configure
5. The URL isn't the good one

**Screenshots**

![capture d ecran_301](https://user-images.githubusercontent.com/13449658/45948039-c606e200-bff6-11e8-96d9-8971d3e81ed5.png)

![capture d ecran_300](https://user-images.githubusercontent.com/13449658/45948018-ad96c780-bff6-11e8-8215-83d91f4ece11.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by PierreRambaud** [comment]
I'm not able to reproduce with the module you gave me. I don't have the same generated url, look like your is generated with Symfony, mine is a legacy url :/
