### ISSUE TITLE
Deletion doesn't work on SEO & Urls page migrated

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10668]
**Describe the bug**
Deletion don't work on SEO & Urls page migrated

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Click on Delete
3. Nothing is deleted

**Screenshots**
![capture d ecran_306](https://user-images.githubusercontent.com/13449658/45950947-f738df80-c001-11e8-91d1-11b824101745.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by sarjon** [comment]
hey @marionf , its already fixed in https://github.com/PrestaShop/PrestaShop/pull/10656

**Comment by jolelievre** [comment]
This is a common bug on all grids, it is fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/10656
