### ISSUE TITLE
Some strings are not translated on module manager page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10664]
**Describe the bug**
Some strings are not translated on module manager page

**To Reproduce**
1. Go to Modules manager

**Screenshots**
![capture d ecran_299](https://user-images.githubusercontent.com/13449658/45947528-e59d0b00-bff4-11e8-9158-809be0c8a715.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by PierreRambaud** [comment]
Translations are just not yet available in Crowdin.
