### ISSUE TITLE
Product combinations won't show and can't be selected

### ISSUE THREAD

**Issue by bmagneCesi** [PrestaShop/PrestaShop#10677]
**Describe the bug**
After importing a product with some combinations, I can't do anything in the Backoffice management of combination on this product, there is an overlay and a loader that won't move : 

In the front office, when you select a combination it goes back to the original one.

**To Reproduce**
1. Import a product
2. Import some combinations of this product
3. Go to the back office management of the product

**Screenshots**
![image](https://user-images.githubusercontent.com/16189694/45955548-864cf400-c010-11e8-9420-0fb023e5505d.png)
![image](https://user-images.githubusercontent.com/16189694/45955666-cdd38000-c010-11e8-9fb0-06658ff8882b.png)

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: 5.6.32 or 7.1.0

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

Thanks for your report.
I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached the video record.
https://drive.google.com/file/d/1aQx_z6hxLnyKqgwx7C9oyMRWLc76i2D7/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by bmagneCesi** [comment]
Hi, I did the one click upgrade to the lastest version and i still have the issue : 
![image](https://user-images.githubusercontent.com/16189694/45968517-81e50300-c031-11e8-9b72-5bb99cc5d1d1.png)
![image](https://user-images.githubusercontent.com/16189694/45968546-97f2c380-c031-11e8-9734-b7cd4482ed79.png)

**Comment by bmagneCesi** [comment]
Hi khouloudbelguith,

What I tried : 

- [ ] Disabling overrides
- [ ] Disabling non native modules
- [ ] Update prestashop from 1.7.3 to 1.7.4

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

I did not manage to reproduce the issue after upgrade from 1.7.3.0 to 1.7.4.2 with the 1-click upgrade module v4.3.0.
https://drive.google.com/file/d/1xpt1b8pMXq28WtvTHzNOb56etMW1pcYH/view

Best regards, Khouloud

**Comment by bmagneCesi** [comment]
The main problem is the fact that in front when o choose a combination, it jump to the previous default one, i thaught it was the one closed by this PR https://github.com/PrestaShop/PrestaShop/pull/7775 but it doesn't work either...

Regarding the back, i really don't understang what is happening

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

Have you the same issue: #9667?

Best regards, Khouloud

**Comment by bmagneCesi** [comment]
Hi Khouloud,

I fixed my issue in front upgrading to 1.7.4.2, thanks a lot for the help.

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
