### ISSUE TITLE
Actions are not working on Traffic & SEO migrated page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10671]
**Describe the bug**
Some actions are not working on Traffic & SEO migrated page: refresh list, show SQL query, export to SQL manager

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Click on the wheel
3. Click on refresh list, show sql query, export to sql manager
4. Nothing happens

**Screenshots**
![capture d ecran_309](https://user-images.githubusercontent.com/13449658/45951691-ce661980-c004-11e8-819c-f731e9d36e05.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by jolelievre** [comment]
This is a common bug on all grids, it is fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/10656
