### ISSUE TITLE
Reset button isn't working on Traffic & SEO migrated page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10670]
**Describe the bug**
Reset button isn't working on Traffic & SEO migrated page

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Enter something in the field page for exemple and click on Search
3. Click on Reset
4. Results are not reseted

**Screenshots**
![capture d ecran_308](https://user-images.githubusercontent.com/13449658/45951472-e25d4b80-c003-11e8-8ebd-3878748e0f68.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by jolelievre** [comment]
This is a common bug on all grids, it is fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/10656
