### ISSUE TITLE
Link widget page not found

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10675]
**Describe the bug**
Link widget page not found

**To Reproduce**
1. Go to Design > Link widget
2. See the page not found

**Screenshots**
![capture d ecran_311](https://user-images.githubusercontent.com/13449658/45953694-2acc3780-c00b-11e8-9d3e-b8598b74a32b.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by jolelievre** [comment]
hello,
this bug is due to the pending module update which was delayed by a bug medhi found last friday
I updated the module branch to fix the bug, si it can be tested again
It is linked to this PR https://github.com/PrestaShop/ps_linklist/pull/48

**Comment by jolelievre** [comment]
My bad I tried with the "old" module and it still works fine for me
Which branch are you testing develop or 1.7.5.x ?

**Comment by marionf** [comment]
@jolelievre it was on 1.7.5.x but I can't reproduce it, so I close it :)
