### ISSUE TITLE
Bulk actions are not working on Traffic & SEO migrated page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10672]
**Describe the bug**
Bulk actions are not working on Traffic & SEO migrated page

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Click on 'Select all'
3. The checkboxes are not checked
4. Select 2 or more checkboxes
5. The bulk action is disabled

**Screenshots**
![capture d ecran_310](https://user-images.githubusercontent.com/13449658/45951987-d83c4c80-c005-11e8-82f0-80aad1de024a.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by jolelievre** [comment]
This is a common bug on all grids, it is fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/10656
