### ISSUE TITLE
error 500 prestashop 1.7.4.2 + php 7.2 in Request menu

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#10689]
**Describe the bug**

**To Reproduce**
1. Go to admin Menu
2. Click on Request
3. Scroll down to 

**Screenshots**
![image](https://user-images.githubusercontent.com/9163980/46003903-e3e54d00-c0b1-11e8-9219-5ce7290402a7.png)
![image](https://user-images.githubusercontent.com/9163980/46004073-48081100-c0b2-11e8-8a6b-7046a6166b98.png)
![image](https://user-images.githubusercontent.com/9163980/46004099-548c6980-c0b2-11e8-9a59-8c80671de306.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Could you please check if the package php-mbstring is installed on your server.
You can check also the mb_split function.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
