### ISSUE TITLE
BO - Movements Page - Search product & pagination

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10682]
**Describe the bug**
Try to edit the quantity of more than 20 products, so in the movements page, we should have more than one page.
1. On the first page, when we try to search for a product with (name/ reference) => ok => product found
2. Try to go to the next page => search for a product which is not displayed in the second page **only** => NOK => we have this message => No product matches your search. Try changing search terms.

**To Reproduce**
1. Go to BO => Catalog => Stocks => Movements tab ( you have more than one page)
2. Click on the second page
3. search for a product is not displayed in the second page (but it exists in the movement first page)
4. No product matches your search. Try changing search terms.

**Screenshots**
https://drive.google.com/file/d/1QczspoEplwzEe4ZYx2XXlfoYSV962h0c/view

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi,

The same issue occurs in the Stock page.
Thanks!

**Comment by Hlavtox** [comment]
@marionf Still not fixed on 1.7.6.

Also, I think there should be option to select page product count like in Product list.

**Comment by ngodefroy** [comment]
Hello @khouloudbelguith 

I could not reproduce on the 1.7 beta version.

Can I close the issue?

https://drive.google.com/file/d/1nyVzU6m4cLYp3l3wf24LCo3ajiAZf1Pt/view

Thank you

**Comment by khouloudbelguith** [comment]
HI @ngodefroy,

Yes it is ok with 1770beta2 :heavy_check_mark: 
related to this: https://github.com/PrestaShop/PrestaShop/issues/16851

Thanks!
