### ISSUE TITLE
Default action need to be "Configure" and not "Disable"

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#10688]
**Describe the bug**
While checking modules installed, the default actions are "Disable" and "Others".

**To Reproduce**
1. Go to 'Installed Modules'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/2631425/46003292-75ec5600-c0b0-11e8-8028-d5a199496e4b.png)

**Additionnal information**
PrestaShop version: 1.7.5.x

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit,

Thanks for your report.
I manage to reproduce the issue with 175x.
Some modules  => the default actions are "Disable" and "Others". for example "Contact form" module.
Some other modules  => the default actions are "Configure" and "Others". for example "Payments by check" module.
![image](https://user-images.githubusercontent.com/16067358/46004413-20fe0f00-c0b3-11e8-82e5-b69570ef5766.png)

The same issue in the Modules catalog page, when trying to install a module
![image](https://user-images.githubusercontent.com/16067358/46004665-b6010800-c0b3-11e8-9fdb-b7309852c972.png)

@marionf  what do you think of this issue?

Best regards, Khouloud

**Comment by PierreRambaud** [comment]
In fact it's not a bug, it's related to #10047 but we are planning to revert this:
> If the module is already configured then the button "disable" replaces the "configure" button. (Same behaviour as the current version).

**Comment by PrestaEdit** [comment]
Never say that it's a bug. But more that you "configure" more than you "disable" a module, there.

**Comment by PierreRambaud** [comment]
Totally agreed with you! 
Saying bug because of this sentence (:trollface:)
 
> It's not a bug, it's a feature

It will be changed for the 1.7.5

**Comment by LouToma** [comment]
Keep the same behaviour as before,
Keep 20 px between Configure and More, Align the buttons if possible

**Comment by PierreRambaud** [comment]
I change it to 10px, with 20px, buttons gone in two lines
