### ISSUE TITLE
Display issue with empty state banner on Traffic & SEO page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10683]
**Describe the bug**
Display issue with empty state banner on Traffic & SEO page

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. The empty state banner should be centered like this:
![image](https://user-images.githubusercontent.com/13449658/45965595-3169a780-c029-11e8-9424-ab97cacf4c40.png)

**Screenshots**
![capture d ecran_305](https://user-images.githubusercontent.com/13449658/45965573-20209b00-c029-11e8-8a44-c66bf3d275ff.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
I guess this PR should be on `1.7.5.x` branch?
