### ISSUE TITLE
Import form alignment issue

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10686]
**Describe the bug**
After updating forms layout Import form does not look pretty.

**To Reproduce**
Open Import page and you will see that alignment is missing.

**Screenshots**
See https://prnt.sc/kyefm7 Import form should be full width

**Additionnal information**
PrestaShop version: 1.7.5, develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @sarjon,

Thanks for your report.
I manage to reproduce the issue with the 175x branch.
Related to #10430

Best regards, Khouloud

**Comment by matks** [comment]
Linked to https://github.com/PrestaShop/PrestaShop/pull/10741
