### ISSUE TITLE
Search a module on module manager page not usefull

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10690]
**Describe the bug**
I search a module on the module manager page
I have to scroll down and click on "see more" to see my module
This is not ideal
The module should appear on the top of the page like before 

**To Reproduce**
1. Go to Modules manager
2. Search a module in the search bar
3. Scroll down ....

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by LouToma** [comment]
When the search is used : do not display the categories that do not include any results.
Display all modules that fit the query (do not use the "see more" option)
