### ISSUE TITLE
500 error with order update - error in 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#10694]
**Describe the bug**
On updating order status,  or sending mail to customer from order  results in 500 error. Error is introduced after update from PS 1.7.3.1 to PS 1.7.4.2

![500 error sending mail]

(https://user-images.githubusercontent.com/11147327/46007451-59edb200-c0ba-11e8-8bad-84741848379a.JPG)

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

This issue is occurred due to php-intl extension.
Could you please try to install it, it is required.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Peter4661** [comment]
Hi Khouloud,

Thank you for your help.  We found php-intl extension was installed, but
not activated.
Issue resolved.

Best regards,


Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op di 25 sep. 2018 om 12:16 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
