### ISSUE TITLE
Module recovery

### ISSUE THREAD

**Issue by 2018MGM** [PrestaShop/PrestaShop#10698]
I have deleted a native prestashop module that I need. How can I recover it?

**Additionnal information**
PrestaShop version: 1.5.3.1
PHP version: N/A

**Comment by DanielBoettner** [comment]
Typically, download the 1.5.3.1 source and copy the module folder to the correct spot.

**Comment by khouloudbelguith** [comment]
Hi @2018MGM,

Also, you can find it in the repository GitHub
https://github.com/PrestaShop
What is the exact module that you need to install it?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @2018MGM,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
