### ISSUE TITLE
Change the way _PS_ADMIN_DIR_ is filled

### ISSUE THREAD

**Issue by DanielBoettner** [PrestaShop/PrestaShop#10697]
# Summary
As a developer when I want to run a **cronjob**, I want to omit the webserver (apache, nginx) for this.
And register a cron that can call scripts via `php`

## How to reproduce

1. Configure the cronjob module
2. Switch to *advanced* mode
3. copy the text shown, like this
  `0 * * * * curl "http://{domain}/admin/index.php?controller=AdminCronJobs&token={my_key}" `
4. Change to
  `php -f admin/index.php "controller=AdminCronJobs&token={my_key}" `
  and run it

## What will happen currently
```
PHP Warning:  require(/var/www/html/../config/config.inc.php): failed to open stream: No such file or directory in /var/www/html/admin/index.php on line 42
PHP Fatal error:  require(): Failed opening required '/var/www/html/../config/config.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/html/admin/index.php on line 42
```
Which happens because in line 42 of the `admin/index.php` the _PS_ADMIN_DIR_ is filled with `getcwd()`.

## What should happen

If applicable switch `getcwd()` in index.php line 42 to `__DIR__`.

With the  change to `__DIR__`,  **_PS_ADMIN_DIR_** would always contain the absolute path to the admin directory.
With `getcwd()` the path returned, is the path from where the script was called and not where the script resides. 

## advantages

* allows to call cronjobs via php
* less workload for apache/nginx 
* no timeouts for long running tasks
* faster

**Comment by khouloudbelguith** [comment]
Hi @DanielBoettner,


Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @DanielBoettner,

Thanks for your contribution: #10699

Best regards, Khouloud
