### ISSUE TITLE
Links in the Module Manager page redirect to the Module Catalog page  with empty result

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10700]
**Describe the bug**

In the Module Manager page, all links displayed have no results ( redirect to the Module Catalog page that does not display any modules)

**To Reproduce**
1. Go to Module Manager page
2. Click on the link "Product Page" or any other link of the "module-search-result-wording"
3. You will be redirected to Module Catalog: with a message: "19 modules and services selected for you" but there are no modules displayed. => No results

**Screenshots**
https://drive.google.com/file/d/1syxplx6nyFs5KtyZTb8AA1ENjC4mPbDl/view

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith 
When you click on Module Catalog I think you have only 19 modules ?
It's because the compatibility of modules isn't yet update on addons.
It should be ok soon (1 day max)
And the number of modules that is not corresponding to the number of modules in the category should be solved by this PR: #10681 
Can you please retry later when the PR will be merged and in 1 day the compatibility of modules should be updated and tell me if you still have this issue

**Comment by khouloudbelguith** [comment]
Okay.
Thanks @marionf :)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

After clicking in all links, we are redirected to the Modules catalog page without any result.
![image](https://user-images.githubusercontent.com/16067358/46084105-28044a80-c1a3-11e8-874c-1fa0e0b5528a.png)
What do you think?

Best regards, Khouloud

**Comment by marionf** [comment]
How many modules do you have when you click on Module Catalog ?

**Comment by khouloudbelguith** [comment]
I have 20 modules.
![image](https://user-images.githubusercontent.com/16067358/46085341-17090880-c1a6-11e8-8ca4-c975cd6d82ae.png)

**Comment by marionf** [comment]
Me too, we should have more we need to wait the update compatibility

**Comment by marionf** [comment]
@khouloudbelguith It should be good now

![capture d ecran_346](https://user-images.githubusercontent.com/13449658/46145545-c0acd000-c260-11e8-8733-3bd8cc8d0321.png)

There is still some modules missing but it's "normal"

![capture d ecran_347](https://user-images.githubusercontent.com/13449658/46145585-df12cb80-c260-11e8-86ab-4de2aa0cee22.png)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Thanks!
