### ISSUE TITLE
Add backward compatibility for migrated controllers

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#10706]
**Describe the bug**

It could be very useful for everyone to add some redirect mecanism for controllers that have been migrated to new URL.
For example, into 1.7.5.0, AdminMaintenance has been moved to /configure/shop/maintenance/
This does affect every module that is trying to generate a link admin links using "old" controller name.

We think that despite the fact that module developers have to update their code, it can be fine to auto redirect if the requested controller does not exists anymore...

**Additionnal information**

PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @prestamodule,

Thanks for your report.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think about his suggestion?

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
Well, using `Context::getContext()->link->getAdminLink('AdminMaintenance')` as before will allow you to reach the new controller automatically.

**Comment by prestamodule** [comment]
@Quetzacoalt91 okay, I thought that it could be introduced into AdminControlller too anyway. I'm closing this one
