### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#10701]
**Describe the bug**
The save of translations seems not to be case sensitive, the display of phrases to translate is case sensitive, so if a template has for instance the texts "add to cart" and "Add to Cart" and "Add to cart" there are three fields to translate on the front-end translations, however, only one is saved.

**To Reproduce**
1. Install a new theme
2. Go to translations and locate a phrase that exists in multiple case variations.
3. change the translations and save.
4. Reload the translationspage.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.x

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Have you tried to contact the theme author about this issue?

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi Khouloud,

Yes, but the translation tools is a core feature in Prestashop, and all the phrases we want to translate are showing up in the translations tool but they are not saved on the correct place, instead they keep overwriting eachother and that issue is most likely in the translation section of Prestashop.

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Those translations are saved in the Back office? but they are not successfully saved in the Front office?
If yes, could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi Khouloud,

The translations are saved on the wrong row in the BO

I have these three rows in BO translations

add to cart
Add to cart
Add to Cart

when I open these, I have these translations
lägg i varukorgen
empty field
Lägg i Varukorgen

In the empty field, I type "Lägg i varukorgen" and click save
When the page reloads in the BO I have these translations

Lägg i varukorgen
empty field
Lägg i Varukorgen

As you can see, the text I types in the second field, is saved on the first field.

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

What is the exact name of this theme?
What is the exact position of each expression?
![image](https://user-images.githubusercontent.com/16067358/46074992-7147a080-c189-11e8-99c8-83f2bf839739.png)

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi, The theme name is autopart

See attached image for locations

![for_khalouhd](https://user-images.githubusercontent.com/2902272/46076417-c685b100-c18d-11e8-856e-ac3aea4f2cac.png)

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

I used the simplio theme with the PS1.7.4.2.
In the translation page, I found only 1 expression "add to cart" not as you 3 expressions.
I attached a video record.
https://drive.google.com/file/d/1Yb6DuL8pfCh36Z9BeybAfxaKhTEXwMLx/view

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi,

If you only get one option then I can't see how you are going to recreate the issue :(

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

As it's not the default theme, provided by Prestashop, we can't do anything with this before the feedback of the theme author.
You should contact the theme author via your addons.prestashop.com account.
Thanks!

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi,

but how is the issue in the template?
should prestashop not handle multiple phrases?

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Same issue with the "luxury" theme.
There's only one expression "add to cart".

Best regards, Khouloud

**Comment by Prestaworks** [comment]
Hi,

I have attached a childtheme for you that you can use to recreate the issue.
[child1.zip](https://github.com/PrestaShop/PrestaShop/files/2420175/child1.zip)

it is classic theme child theme, that only replace the contact form tpl so that you get 3 different translations. I hope this helps to recreate the issue for you.

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

When trying to upload your theme attached, I have this error
https://drive.google.com/file/d/14jFzlwbl2hZ_22UHYE00q1YcYFYmCVuC/view

Best regards, Khouloud

**Comment by Prestaworks** [comment]
just unzip it to your themes folder

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

No, I tried to unzip the child1 into the themes folder, but it is not displayed in the list of all the theme selected.
![image](https://user-images.githubusercontent.com/16067358/46091144-7f5de700-c1b2-11e8-902f-f9f482619824.png)

Best regards, Khouloud

**Comment by Prestaworks** [comment]
can you show how it looks inside your themes folder now?

**Comment by khouloudbelguith** [comment]
@Prestaworks,

![image](https://user-images.githubusercontent.com/16067358/46136323-9d295b80-c247-11e8-99bb-27625d7bc1f2.png)

**Comment by Prestaworks** [comment]
odd, we tried on two installations on separate machines here, works fine on both, maybe you need to clear cache?

**Comment by khouloudbelguith** [comment]
@Prestaworks, no after clearing cache, there's no success.
Same issue!

**Comment by Prestaworks** [comment]
ok, maybe you can get some support at your office on how to get the child theme to install or you may have to add your own bug report to get this fixed :)

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Could you please try with this theme: https://github.com/PrestaShop/childtheme-example & feedback.

Best regards, Khouloud

**Comment by Prestaworks** [comment]
ok, here you go.

[childtheme-example-master.zip](https://github.com/PrestaShop/PrestaShop/files/2424366/childtheme-example-master.zip)

**Comment by Prestaworks** [comment]
here is also a video of the issue
https://www.useloom.com/share/09bd7db867fc4488a37d16cd54374ae5

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Thanks for the clarifications.
Now I manage to reproduce the issue with PS1.7.4.2.
When there are 3 expressions with the same value.
Only the first expression will be edit successfully but with the third value.
https://drive.google.com/file/d/1Tx3HESPCpUzMEFzJLi_rUWAUQ_IZZIi8/view
@marionf What do you think?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.1.
[childtheme.zip](https://github.com/PrestaShop/PrestaShop/files/3606320/childtheme.zip)
https://drive.google.com/file/d/1SY_kFcIhbWLHe7cWF1adAeZyGQBBU0MR/view
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15511 to fix the issue.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15511
