### ISSUE TITLE
Changing carrier price ranges TECHNICAL ERROR

### ISSUE THREAD

**Issue by bmagneCesi** [PrestaShop/PrestaShop#10717]
**Describe the bug**
I get a 
```
TECHNICAL ERROR: 

Details:
Error thrown: [object Object]
Text status: parsererror
```
when I try to update my carrier price ranges

**To Reproduce**
1. Go to on carrier options
2. Click on delivery costs
3. Update ranges
4. Save and see the error

**Screenshots**
![image](https://user-images.githubusercontent.com/16189694/46075662-7a397180-c18b-11e8-940b-a530280b6d48.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.32 & 7.1.0

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

We did not manage to reproduce the issue with PS1.7.4.2.
But you can take a look at this ticket: http://forge.prestashop.com/browse/BOOM-5506
It could help to solve your problem.
Thanks to check & feedback.

Best regards, KHouloud

**Comment by khouloudbelguith** [comment]
Hi @bmagneCesi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by Hlavtox** [comment]
I also get this ERROR sometimes if I make more complicated carrier ranges. It happens on all 1.6 versions and obviously on 1.7 also.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Despite our several trials, we could not reproduce your issue.
https://drive.google.com/file/d/1tHRmdEVyP6iAb9-tKULNkODlwpJHelXk/view
But you can take a look at this ticket: http://forge.prestashop.com/browse/BOOM-5506
It could help to solve your problem.
Thanks!

**Comment by jmbluethner** [comment]
@khouloudbelguith The issue is still existing, even though the issue is really old by now.
![image](https://user-images.githubusercontent.com/39534549/80805182-a7e06b00-8bb7-11ea-893c-99755ff5740d.png)

I get this error on all steps when trying to create a new shipping service.

Any help?

**Comment by Matt75** [comment]
@nighttimedev What is your PrestaShop version ?
Please use your browser Devtools and Network inspection when this error appear to retrieve details about Ajax request fail. It appends when PrestaShop return HTML instead of json, in case of exception for example.

**Comment by jmbluethner** [comment]
@Matt75 Here you can see all XHR requests fired at the moment the error appears:

![image](https://user-images.githubusercontent.com/39534549/81061335-7546b300-8ed4-11ea-859b-e4c7f1353b5c.png)

My shop is running on 1.7.6.5

Edit: I'm also getting the following error message ...

![image](https://user-images.githubusercontent.com/39534549/81061431-a1faca80-8ed4-11ea-8f44-02d3eb109d97.png)
(<code>Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.</code>)

... over and over again.

**Comment by Matt75** [comment]
> @Matt75 Here you can see all XHR requests fired at the moment the error appears:
> 
> ![image](https://user-images.githubusercontent.com/39534549/81061335-7546b300-8ed4-11ea-859b-e4c7f1353b5c.png)
> 
> My shop is running on 1.7.6.5
> 
> Edit: I'm also getting the following error message ...
> 
> ![image](https://user-images.githubusercontent.com/39534549/81061431-a1faca80-8ed4-11ea-8f44-02d3eb109d97.png)
> (`Mixed Content: The page at '' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint ''. This request has been blocked; the content must be served over HTTPS.`)
> 
> ... over and over again.

Can you make a screenshot a video record to see the preview of request in Devtools and Network inspection ? Because we need to see the response to see what PrestaShop returned.

It can be an issue due to `max_input_vars` PHP configuration, because this request can send a lot of input data. Can you check the value of `max_input_vars` in your server configuration ?

Issue with mixed content is due to bad configuration of https on your shop. Please ensure you always use https protocol on BO

**Comment by Hlavtox** [comment]
@Matt75 Why does it post so many variables? Couldn't it be sent in some serialized form and "extracted" on PHP's side? 

The same goes for products - I was saving a product with 300 combinations and had to raise max_input_vars to 8000.

**Comment by Matt75** [comment]
@Hlavtox These pages will be refactored in future versions, I don't know when.

**Comment by Hlavtox** [comment]
@Matt75 Nice. 🍺 

@nighttimedev It seems not to get anything from Prestashop core due to mixed content blocking. Try to access the BO without HTTPS and maybe it will work fine.
