### ISSUE TITLE
Dedicated "Access denied" page

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10712]
### Describe the bug
For example, lets say you create new employee in Back Office and remove all permissions on "Invoices" page for this employee.
Once this employee tries to access "Invoices" page, he will get redirected to legacy "Dashboard" page and if employee does not have permissions for that either he will see empty "Dashboard" page with an error.

### Expected behavior
It would be nice to have empty "Access denied" page as fallback option on `@AdminSecurity` annotation.
Can we create new dedicated "Access denied" page that can be used as fallback?

### Steps to reproduce

1. I created a new employee in Back Office and I remove all permissions on "Invoices" page for this employee.
2. Once this employee signs in the BO, the "Invoices" sub-menu doesn't exist in the menu.
3. Once this employee tries to access "Invoices" page, he will get redirected to legacy "Dashboard" page 

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/46064973-29b51a80-c171-11e8-9b1f-c67f5a87cd93.png)
![image](https://user-images.githubusercontent.com/16067358/46065664-f83d4e80-c172-11e8-8c44-6d7de996396a.png)

### Additional infos
- PS version: 1.7.7.3
- PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @sarjon,

I created a new employee in Back Office and I remove all permissions on "Invoices" page for this employee.
![image](https://user-images.githubusercontent.com/16067358/46064973-29b51a80-c171-11e8-9b1f-c67f5a87cd93.png)
Once this employee signs in the BO, the "Invoices" sub-menu doesn't exist in the menu.
![image](https://user-images.githubusercontent.com/16067358/46065664-f83d4e80-c172-11e8-8c44-6d7de996396a.png)
Once this employee tries to access "Invoices" page, he will see an "Access denied" page.
![image](https://user-images.githubusercontent.com/16067358/46065788-523e1400-c173-11e8-8be3-27fb2000f06d.png)

Prestashop 1.7.4.2, Thanks to check & feedback.

Best regards, Khouloud

**Comment by sarjon** [comment]
hi @khouloudbelguith even though Invoices page is migrated it still uses legacy layout to display "Access denied" page.

**Comment by khouloudbelguith** [comment]
Hi @sarjon,

Yes, it is a regression.
In the 1.7.5.x, once this employee tries to access "Invoices" page, he will be redirected to the Dashboard page.
Same issue with other symfony pages.

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment]
Hi all,

Do we really deal with a regression here? The redirection to the dashboard is not a new side-effect, Symfony controller always behaved like this when the permission are not granted.

As we deal with a new page to implement, I would rather this that task for PS 1.7.6 instead of 1.7.5.

**Comment by marionf** [comment]
Yes, you are right, let's do it for 1.7.6

**Comment by sarjon** [comment]
is there any mockups for "Access denied" page? /cc @matks

**Comment by matks** [comment]
@sarjon Sorry for late answer, no mock-up right now.

@TristanLDD I know you have already a lot of work, so I will not ask you for more mock-ups 😛 
Can you just tell us if we can we reuse the "500 error" pages from https://github.com/PrestaShop/PrestaShop/pull/10780 ?

**Comment by TristanLDD** [comment]
> @sarjon Sorry for late answer, no mock-up right now.
> 
> @TristanLDD I know you have already a lot of work, so I will not ask you for more mock-ups 😛
> Can you just tell us if we can we reuse the "500 error" pages from #10780 ?

Yes let's use the 500 error page for the moment :)

**Comment by florine2623** [comment]
This is fixed on 8.1.x and 9.0.x. We are always redirected to the dashboard.


https://github.com/PrestaShop/PrestaShop/assets/16019289/794281fe-cfca-4365-bb8d-48ffabde9b3e

I'm closing the issue to avoid clogging the backlog.
