### ISSUE TITLE
File select input issue

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10715]
When developing i try to follow PrestaShop UI Kit, but when i use file select from UI Kit i lose some functionality.

For example, when using native file selector you can see selected file, but i does not work for PrestaKit file select. See image below:
 
![file input](https://user-images.githubusercontent.com/15143151/46070466-8ec73b00-c186-11e8-8488-ea4d28aba500.png)

**Comment by khouloudbelguith** [comment]
Related to: #10430

**Comment by sarjon** [comment]
@tomas862 is it done?

**Comment by tomas862** [comment]
This issue is still pending with this Pull request https://github.com/PrestaShop/prestashop-ui-kit/pull/59 and https://github.com/PrestaShop/PrestaShop/pull/12436

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/12436
