### ISSUE TITLE
Disable Show notifications option - Administration page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10723]
**Describe the bug**

In the BO => Advanced Parameters => Administration, when we disable show notifications option for new customers for example (same issue with other options), when we create a new customer, in the BO => the notification bell is displayed but we cannot show this notification because we just disabled the Customers notification. 
**To Reproduce**
1. Go to BO => Advanced Parameters => Administration
2. Scroll down to 'Notifications'
3. Disable Show notifications for new customers
4. Navigate to the FO
5. Create a new customer
6. Navigate to the BO => A notification is displayed

[Same issue for the other notifications ptions]

**Screenshots**
https://drive.google.com/file/d/1yeJ0ZH8HHviuMLVURTbFu0sF3Encs-rU/view

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by marionf** [comment]
The notification shouldn't be displayed if it's disabled

**Comment by elmanu13** [comment]
Any news ont this one ?
I don't want my sales guy to see the other's orders, and I use a module to filter this, but the notification favicon is not concerned. Even if I disable the new order notifications I have a number on the bell, and it shouldn't be.

Thanks !

<img width="463" alt="Capture d’écran 2019-03-20 à 00 12 54" src="https://user-images.githubusercontent.com/32092528/54684842-abc93f00-4b15-11e9-9eed-4fc5602628f2.png">

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

Sorry not yet.
It is added to our bug roadmap, so it will be fixed.
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks for your understanding!
