### ISSUE TITLE
Product detail - specific prices with different discount percentages -> wrong discount percentages displayed upon a quantity input changes

### ISSUE THREAD

**Issue by jancinert** [PrestaShop/PrestaShop#10730]
**Describe the bug**
Product detail - specific prices with different discount percentages -> wrong discount percentages displayed upon a quantity input changes

**To Reproduce**
Install prestashop 1.6.1.20
Edit product demo_2 from demo database in backend.
Add specific price with parameters:
combination S white
quantity from: 1
discount 10%
Add another specific price with parameters:
combination S white
quantity from: 2
discount 20%
Go to frontend product detail page and make combination S White the active one.
Change a quantity box value to 2 and see discount percentage value wrong

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jancinert,

Thanks for your report.
But in the BO => Preferences => Products, you need to edit the "Quantity discounts based on" Combinations.
Same issue here: #8609
Thanks to check & feedback.

Best regards, Khouloud

**Comment by jancinert** [comment]
Thank You for Your work.

I tried new tests, one with "Quantity discounts based on" set on and second one with "Quantity discounts based on" off.
Both tests leads to same wrong result on screen.

The root cause is that the screen value is not getting updated by any value.
It is not about getting updated by wrong number.
In other words switching the quantity from 1 to 2 keeps the discount percentage unchanged from previous state.

I also checked a pull request of #8609 and it is a different problem.

**Comment by khouloudbelguith** [comment]
Hi @jancinert,

Thanks for the clarifications.
I manage to reproduce the issue with the last version: 1.6.1.20.
Thanks for the fix: #10731

Best regards, Khouloud

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with PrestaShop 1.7.6.1 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is OK with PS1.7.6.1.
https://drive.google.com/file/d/1Jk7DaVxMxnyPGJT0pnLb9-Y0oHGyjoej/view
Thanks!
