### ISSUE TITLE
 feature_value (Duplicate entry '13-2' for key 'PRIMARY')

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10732]
Prestashop 1.7.4.2
apache+nginx
php 7.2.10
please see my video: https://www.useloom.com/share/4a238918d4a04c8eb905e30af2f1bc2b
when I try to add new features, this issue happens, and prestashop add random feature.

**Comment by khouloudbelguith** [comment]
Hi @,

I did not manage to reproduce the issue with the last version 1.7.4.2.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by centoasa** [comment]
debug mode on
Duplicate entry '16-1' for key 'PRIMARY'

INSERT INTO `ps_feature_value_lang` (`id_feature_value`, `value`, `id_lang`) VALUES ('16', 'test55', '1')
![2018-09-27](https://user-images.githubusercontent.com/5500935/46136949-0362ae00-c249-11e8-923c-fd3948262a56.png)

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Did you use the multistore context?

Best regards, Khouloud

**Comment by centoasa** [comment]
sorry what's this?
where I can find it?

**Comment by khouloudbelguith** [comment]
In the BO => Shop Parameters => General page => did you enabled the multishop option?

**Comment by centoasa** [comment]
no, it didn't enabled

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Did you delete any features from your Database?

Best regards, Khouloud

**Comment by centoasa** [comment]
no. This is a fresh installation of 1.7.4.2 directly from plesk
I've only import some tables from 1.6.1.19 (customers, order, attributes)

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

I did not manage to reproduce the issue with PS 1.7.4.2 (nginx + PHP 7.2)
https://drive.google.com/file/d/1rVOzuSNTv__osXUdyCanuuW1K-v4KDMT/view
Could you please check the ps_feature_value_lang table if you have a duplicated data?

Best regards, Khouloud

**Comment by centoasa** [comment]
But on your video it’s seems you’ve only one language, instead I’ve 2 languages ita + eng

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

No, I have 3 languages.
![image](https://user-images.githubusercontent.com/16067358/46145931-cd7df380-c261-11e8-85ed-1233b7b80d8d.png)

Best regards, Khouloud

**Comment by centoasa** [comment]
I thinnk there was a mistake on ps_feature_value_lang table
![2018-09-27 1](https://user-images.githubusercontent.com/5500935/46146400-f9e63f80-c262-11e8-8a54-0411178a9a23.png)
so I've truncate table and testing....

**Comment by centoasa** [comment]
@khouloudbelguith great, now all works great!
Thanks a lot for your fast reply and suggestions!

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks!
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
