### ISSUE TITLE
Issue with text editors

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10738]
**Describe the bug**
There is something wrong with text editors on multiple pages, see Brands for example here https://prnt.sc/kzcjnb

**To Reproduce**
Open Brands page.

**Screenshots**
n/a

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @

Here's the PR: #10462 to solve the issue.
Your ticket is a duplicate of #10461
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #10461
