### ISSUE TITLE
Reorganize tests folder

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10733]
Here is the current`tests` folder structure:

- E2E
- Integration
    - Adapter
    - classes
    - Core
    - PrestaShopBundle
- phpcs (removed in https://github.com/PrestaShop/PrestaShop/pull/10724)
- PrestaShopBundle
- resources
    - assets
    - minimal-missconfig-theme
    - minimal-missfiles-theme
    - minimal-valid-theme
    - module
    - module-self-config-files
    - modules
    - template-hierarchy
- Selenium
- TestCase
- Unit
    - Adapter
    - Classes
    - Controller
    - Core
    - PrestaShopBundle

I suggest to transform it into:

- E2E (left untouched)
- Integration
    - Controllers (php tests using WebTestCase)
    - Api (php tests using ApiTestCase)
    - Domain (domain logic behat tests / it's php tests right now and should be migrated to behat)
    - Misc (haven't found a better name so far 😩 - it's for the other kind of tests that rely on database content)
-  fixtures
    - web_assets
    - themes
    - modules
    - templates
- Unit

**And especially:**
- `Selenium` folder will be moved into`E2E` (see below)
- have only one `PrestaShopBundle` folder 🙄 
- move TestCases either in `Unit` or in `Integration`
- we would write a short README to explain this structure and a complete section on devdocs (we need the README because some people will not look at the docs)

⏩ I would perform this migration in several steps, 1 step = 1 Pull Request, and we would compare Travis builds to check nothing is broken.

**Comment by matks** [comment]
What do you think @eternoendless @mickaelandrieu ?

**Comment by fatmaBouchekoua** [comment]
Hello @matks ,
Actually, we are moving the Selenium folder under E2E tests (we are migrating them to the new architecture)

**Comment by matks** [comment]
@fatmaBouchekoua Thank you for letting me now :) so you plan to keep all E2E tests together ? You will not split them between projects (because Selenium tests are, according to the README, dedicated to StarterTheme) ?

**Comment by fatmaBouchekoua** [comment]
Yes we will keep all E2E tests together but in different campaigns (you can find all campaigns under E2E/test/campaigns)

**Comment by mickaelandrieu** [comment]
I agree we need to do something about it (I've already tried to reorganize some of them between 1.7.3 and 1.7.4) but I don't think we should consider this is part of Symfony migration 🤔

**Comment by sarjon** [comment]
>  but I don't think we should consider this is part of Symfony migration

@matks wants us to do all the work so he added it to migration :trollface:

**Comment by sarjon** [comment]
@matks i've reviewed your suggestion once again and here's what i came up with:

- **E2E**
- **Integration/**
    - **Test/** actual Integration tests
        - **Core/**
        - **PrestaShopBundle/**
    - **resources/** any static files or anything thats needed for tests
    - **fixtures/** any fixtures if needed
    - **phpunit.xml** phpunit configuration file for Integration tests
    - **bootstrap.php** bootstrap file for integration tests
- **Unit**
    - **Test/** actual unit tests
        - **Adapter/**
        - **Core/**
        - **PrestaShopBundle/**
    - **resources/** any static files or anything thats needed for tests
    - **fixtures/** any fixtures if needed
    - **phpunit.xml** phpunit configuration file for Unit tests
    - **bootstrap.php** bootstrap file for unit tests

this would clearly separate both fixtures, static files, configurations between different kinds of tests. wdyt?

**Comment by matks** [comment]
Looks good 😄 @mickaelandrieu @PierreRambaud any opinion ?

**Comment by PierreRambaud** [comment]
:+1:

**Comment by matks** [comment]
After discussing it further, here's a plan:
1) rename `tests` into `legacy-tests`, exclude `E2E` and `Selenium`
2) so we get a new empty folder Unit and a new empty folder Integration
3) new `tests/Unit` folder should only accept true unit tests: full-mocked dependencies
4) new `tests/Integration` folder should welcome component-based tests using behat

**Comment by matks** [comment]
Part 1 has been done: https://github.com/PrestaShop/PrestaShop/pull/11464
Now we have a clean `tests` folder where we can introduce modern testing :) both unit and integration
