### ISSUE TITLE
Set language from browser / Set default country from browser language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10744]
**Describe the bug**

In the International / Localization page the options "Set language from browser" & "Set default country from browser language" => Whether I activate or deactivate it, I don't see any difference. 
**First issue**
If I disable the "Set language from browser", the shop will be always displayed in the default language of the navigator.
https://drive.google.com/file/d/1ZGwVOrPtKxJZSTH30Z_5Lj_fsKGPTa69/view

**Second issue**
If we disable the "Set default country from browser language" option, in the address page, the country by default displayed is wrong.
https://drive.google.com/file/d/1tOvLidQhAZxPr69_PTQwFShBc4Eqe60g/view

**To Reproduce**
1. Go to BO => IMPROVE => International => Localization
2. In the Configuration part, try to enable & disable the "Set language from browser" & the "Set default country from browser language" options
3. Navigate to FO => There's no difference

**Additionnal information**
PrestaShop version: 1.7.4.2 / 1.7.5.x
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith I can't reproduce this issue on 1.7.6.0

https://drive.google.com/open?id=1Yv0ZlYSgHfFheva2D-mHfMTdIxYy0awW
