### ISSUE TITLE
BO - Search category does not work perfectly

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10747]
**Describe the bug**

Navigate to a category which has subcategories, then try to search with the name. On click "Search" you have redirect to list of category ...not having search results. Going back to the list, search filter works OK, reset button same work.

**To Reproduce**
1. Go to BO => Catalog => Categories 
2. Click on "View button", Check that you have more than a category
3. Search for a subcategory
4. You are redirected to the Category list page

Same issue with the Reset button

**Screenshots**
https://drive.google.com/file/d/14QsWRp2RTW4MyZmHsKo6mPQbNy6qt2vM/view

**Additionnal information**
PrestaShop version: 1.7.4.2 / 1.7.5.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Related to: #9706

**Comment by adatso** [comment]
![2019-01-23_19-40-02](https://user-images.githubusercontent.com/11773382/51629460-ef556180-1f47-11e9-9d8f-df2f72ccb050.png)
![2019-01-23_19-45-16](https://user-images.githubusercontent.com/11773382/51629464-f2505200-1f47-11e9-84a8-6433bdce749b.png)

This dreadful bug exists since version 1.6.1.2 and perhaps in earlier versions too. Did only 2 people notice this? Also, I should note that pagination did not work in categories and still does not work (redirects to the main categories page). Search only works on the main categories page.

**Comment by adatso** [comment]
Problem is hidden in the redirection: **Tools::redirectAdmin($url)**. 

When searching for subcategories, redirection is performed with status code 302. As I know, when redirecting after POST request, all data previously sent via POST (specifically -> **id_category**) will lost. So for this reason the claimed functionality does not work.

When comment out `    public static function redirectAdmin($url)
    {
        /*header('Location: '.$url);
        exit;*/
    }`
search and pagination in subcategories works fine.

Help me figure it out...

**Comment by khouloudbelguith** [comment]
Hi @adatso,

Sorry the issue is not fixed yet.
There are some major issues to solve before this one.
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks for your understanding!

**Comment by adatso** [comment]
Hi,

My client cannot wait, so I fixed this issue as follows...

**classes/controller/AdminController.php** (line 959)

replace
`$this->setRedirectAfter(self::$currentIndex.'&token='.$this->token.(Tools::isSubmit('submitFilter'.$this->list_id) ? '&submitFilter'.$this->list_id.'='.(int)Tools::getValue('submitFilter'.$this->list_id) : ''));`
by
`$this->setRedirectAfter(self::$currentIndex . (Tools::isSubmit('id_category') ? '&id_category=' . (int) Tools::getValue('id_category') : '') . '&token=' . $this->token . (Tools::isSubmit('submitFilter' . $this->list_id) ? '&submitFilter' . $this->list_id . '=' . (int) Tools::getValue('submitFilter' . $this->list_id) : ''));`

and even better create an override
```
<?php
class AdminController extends AdminControllerCore
{

  public function postProcess()
  {
    try {
      if ($this->ajax) {
        // from ajax-tab.php
        $action = Tools::getValue('action');
        // no need to use displayConf() here
        if (!empty($action) && method_exists($this, 'ajaxProcess' . Tools::toCamelCase($action))) {
          Hook::exec('actionAdmin' . ucfirst($this->action) . 'Before', array('controller' => $this));
          Hook::exec('action' . get_class($this) . ucfirst($this->action) . 'Before', array('controller' => $this));

          $return = $this->{'ajaxProcess' . Tools::toCamelCase($action)}();

          Hook::exec('actionAdmin' . ucfirst($this->action) . 'After', array('controller' => $this, 'return' => $return));
          Hook::exec('action' . get_class($this) . ucfirst($this->action) . 'After', array('controller' => $this, 'return' => $return));

          return $return;
        } elseif (!empty($action) && $this->controller_name == 'AdminModules' && Tools::getIsset('configure')) {
          $module_obj = Module::getInstanceByName(Tools::getValue('configure'));
          if (Validate::isLoadedObject($module_obj) && method_exists($module_obj, 'ajaxProcess' . $action)) {
            return $module_obj->{'ajaxProcess' . $action}();
          }
        } elseif (method_exists($this, 'ajaxProcess')) {
          return $this->ajaxProcess();
        }
      } else {
        // Process list filtering
        if ($this->filter && $this->action != 'reset_filters') {
          $this->processFilter();
        }

        // Fix for subcategories search and pagination - Andrey Datso
        if (isset($_POST) && count($_POST) && (int) Tools::getValue('submitFilter' . $this->list_id) || Tools::isSubmit('submitReset' . $this->list_id)) {
          $this->setRedirectAfter(self::$currentIndex . (Tools::isSubmit('id_category') ? '&id_category=' . (int) Tools::getValue('id_category') : '') . '&token=' . $this->token . (Tools::isSubmit('submitFilter' . $this->list_id) ? '&submitFilter' . $this->list_id . '=' . (int) Tools::getValue('submitFilter' . $this->list_id) : ''));
        }

        // If the method named after the action exists, call "before" hooks, then call action method, then call "after" hooks
        if (!empty($this->action) && method_exists($this, 'process' . ucfirst(Tools::toCamelCase($this->action)))) {
          // Hook before action
          Hook::exec('actionAdmin' . ucfirst($this->action) . 'Before', array('controller' => $this));
          Hook::exec('action' . get_class($this) . ucfirst($this->action) . 'Before', array('controller' => $this));
          // Call process
          $return = $this->{'process' . Tools::toCamelCase($this->action)}();
          // Hook After Action
          Hook::exec('actionAdmin' . ucfirst($this->action) . 'After', array('controller' => $this, 'return' => $return));
          Hook::exec('action' . get_class($this) . ucfirst($this->action) . 'After', array('controller' => $this, 'return' => $return));
          return $return;
        }
      }
    } catch (PrestaShopException $e) {
      $this->errors[] = $e->getMessage();
    }
    return false;
  }
}
```

put it into **override/classes/controller/AdminController.php**

and use this solution until better times ;)

ps 1.7.4.4, php 7.2.14

**Comment by khouloudbelguith** [comment]
@adatso,

Thanks for your fix suggestion.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by adatso** [comment]
Done https://github.com/PrestaShop/PrestaShop/pull/12288

**Comment by matks** [comment]
This is fixed by the page migration. @marionf do you want to check ?

**Comment by marionf** [comment]
Yes, it's fixed :)

**Comment by khouloudbelguith** [comment]
Hi!

This issue occurs again with PS1.7.6.1 & PS1.7.6.0.
Issue is reported here: https://github.com/PrestaShop/PrestaShop/issues/15588

Thanks!
