### ISSUE TITLE
LazyArrays on 1.7.5 - Google analytics module is incompatible

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#10742]
**Describe the bug**
When using ps_googleanalytics module on 1.7.5, going on a product page in the front office brings the following notice:

Notice: Undefined index: name

**To Reproduce**
1. Go to a product page

**Screenshots**
![capture du 2018-09-27 16-53-15](https://user-images.githubusercontent.com/6768917/46158582-1344b700-c276-11e8-80b9-6c1622294b51.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Quetzacoalt91,

Thanks for your report.
I manage to reproduce the issue with the branch 1.7.5.x & the ps_googleanalytics v3.1.1 - by PrestaShop.
PS1.7.4.2 => OK

Best regards, Khouloud

**Comment by prestamodule** [comment]
@Quetzacoalt91 LazyArrays are breaking a lot of behaviour into modules, especially when using simple checks like is_array() that is not working anymore as it's now an object... We had to make a lot of changes on our side too.

**Comment by Quetzacoalt91** [comment]
We could have made something totally transparent if a `__toString` equivalent method for arrays existed.

We did our best to keep the same behavior. Getting the properties as an array or good old Product class still works, but as soon as the variables is cast as an array, we end with a product key in the product. :/

I'll add a page about this in the dev documentation, and fixed the module by strictly checking the product class. (https://github.com/PrestaShop/ps_googleanalytics/pull/14)

**Comment by Quetzacoalt91** [comment]
See dedicated pull-request in the documentation repository https://github.com/PrestaShop/docs/pull/146

**Comment by masiorama** [comment]
I just opened an issue on the dedicated repo, since I'm having difficulties with this module.
https://github.com/PrestaShop/ps_googleanalytics/issues/29
Did anybody noticed a similar problem updating on PS 1.7.5 with Analytics module 3.1.3?
