### ISSUE TITLE
No way to update my modules: Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by Dennis002** [PrestaShop/PrestaShop#10740]
**Describe the bug**
When i try to update my module, for all modules, i got always the same error:
Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object

**To Reproduce**
1. Go to modules
2. Click on a random module that need upgrade
3. upgrade it
![immagine](https://user-images.githubusercontent.com/24193791/46146142-5301a380-c262-11e8-96cb-b2d44d01fd7f.png)

**Screenshots**
attached

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: i verified with siteground and it sint a php problem, we tried to change version too

**Comment by khouloudbelguith** [comment]
Hi @Dennis002,

Could you please check if the zip extension is enabled in your php.ini file and feedback.

Best regards, Khouloud

**Comment by Dennis002** [comment]
> Hi @Dennis002,
> 
> Could you please check if the zip extension is enabled in your php.ini file and feedback.
> 
> Best regards, Khouloud

Yes, i asked to siteground support and it is enabled in all of their servers
Best regards

**Comment by khouloudbelguith** [comment]
Hi @Dennis002,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Dennis002** [comment]
host: Siteground
server setup and configuration:  https://wegeek.shop/phpinfo.php
PrestaShop version (source): 1.7.4.2
debug mode report:

×
Error!
Eccezione lanciata dal modulo prestagiftvouchers su upgrade. Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object


PHP error logs: no errors in logs (screen attached)

apache error log: no errors in logs (screen attached)

javascript console log: no errors in logs (screen attached)

screenshots:
![immagine](https://user-images.githubusercontent.com/24193791/46149931-b0e6b900-c26b-11e8-82ee-acb3d9554ffe.png)
![cattura](https://user-images.githubusercontent.com/24193791/46149988-ccea5a80-c26b-11e8-81fa-ada34603d67f.PNG)

BEst regards



> Hi @Dennis002,
> 
> Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * host
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> * screenshots
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!
> 
> Best regards, Khouloud

host: Siteground
server setup and configuration:  https://wegeek.shop/phpinfo.php
PrestaShop version (source): 1.7.4.2
debug mode report:

×
Error!
Eccezione lanciata dal modulo prestagiftvouchers su upgrade. Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object


PHP error logs: no errors in logs (screen attached)

apache error log: no errors in logs (screen attached)

javascript console log: no errors in logs (screen attached)

screenshots:
![immagine](https://user-images.githubusercontent.com/24193791/46149931-b0e6b900-c26b-11e8-82ee-acb3d9554ffe.png)
![cattura](https://user-images.githubusercontent.com/24193791/46149988-ccea5a80-c26b-11e8-81fa-ada34603d67f.PNG)

BEst regards

**Comment by khouloudbelguith** [comment]
Hi @Dennis002,

Could you please try to upgrade the module on your PC(local) and I do the transfer with FTP on the server.
Thanks to check& feedback.

Best regards, Khouloud

**Comment by SebSept** [comment]
Hello,
This happend when trying to update a module bought on the addon store but when user is not connected to psaddon (or connected with another account).
No zip is downloaded, so it can't be extracted...

**Comment by khouloudbelguith** [comment]
HI @Dennis002,

Thanks for the clarifications.
Now, I manage to reproduce the issue.
https://drive.google.com/file/d/1DQzi8zBpjAGkko_2hHrKq9XLsW21Z--o/view
This issue occurs only when we try to upgrade a module bought by addons & we are not logged/connected with another account.

Best regards, Khouloud

**Comment by Dennis002** [comment]
Here we go! It is fixed, thanks a lot

**Comment by khouloudbelguith** [comment]
Hi @Dennis002,

Thanks for your feedback.
How did you fix the issue?

Best regards, Khouloud
