### ISSUE TITLE
Friendly URL not updated in SEO preview

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10756]
**Describe the bug**
Title says it all

**To Reproduce**
1. Go to 'Catalog -> Products'
2. Click on 'SEO'
3. Scroll down to 'Friendly URL', change it
4. See that Friendy URL is not updated in the preview

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Hi @kpodemski,

Indeed, I could not implement it only using the js `change` event, as the information is stored in a data attribute of the "Preview" link.
I'll have a look by looking at a potential JS event triggered on product save, but we won't have a link being live updated while you're typing.

**Comment by Quetzacoalt91** [comment]
Unfortunately, the preview URL is not updated when the product is saved, only when the page is refreshed. The feature is limited to the form current behavior.

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Yes, as @Quetzacoalt91 said, it is the same behavior with 1.7.4.2.
The preview URL will be updated only when we refresh the page.
@marionf @colinegin @Quetzacoalt91 what do you think? it could be an improvement?

**Comment by Quetzacoalt91** [comment]
I managed to manually update the URL, instead of relying on the core: https://github.com/PrestaShop/PrestaShop/pull/10810

**Comment by colinegin** [comment]
Great news ! Thanks a lot @kpodemski and @Quetzacoalt91
