### ISSUE TITLE
Delivery Time, confusing UI in back-office

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10759]
**Describe the bug**
Read below.

**To Reproduce**
1. Go to 'Catalog -> Product -> Edit'
2. Click on 'Shipping' tab
3. Scroll down to 'Delivery Time'
4. Fill in "Delivery time of in-stock products:" field. 

It will not show up on product page unless you'll select option "Specific delivery time to this product" from these three radio fields above. What is the point of showing these two inputs for Specific delivery time if we don't have selected proper option to use them? It's confusing.

My proposal:
- show them only if Delivery time is set to "Specific delivery time to this product" *or* someone has it already filled up for some reason

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
I manage to reproduce the issue with the 1.7.5.x branch / PS1.7.4.2.
First issue:
1. If the "**Default delivery time**" option is checked 
1.1 we have set the "Delivery time of in-stock products" & "Delivery time of out-of-stock products with allowed orders" => It will not show up on the product page => it should be **disabled**
2. If the "**Specific delivery time to this product**"  is checked
2.1 The product is out of stock 
2.2 "Delivery time of out-of-stock products with allowed orders" is not empty
2.3 "Deny orders" is the behavior checked  when out of stock =>  It will not show up on the product page => it should be **disabled**

@marionf what do you think?

Best regards, Khouloud

**Comment by marionf** [comment]
Yes, this part could be improved

**Comment by MatShir** [comment]
Fixed on the new product page 8.1 :)
