### ISSUE TITLE
Multiple features with same value are causing not described errors

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10757]
**Describe the bug**
Title says it all.

**To Reproduce**
1. Go to 'Catalog > Product -> Edit'
2. Add feature, Color: White, and below again, Color: white
3. Click the "Save" button
4. See error, it says that settings cannot be saved but there's literally no information at all about what went wrong, of course it's obvious mistake to have 2 features with same value but if someone have 20+ features it's easy to overlook it

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
I manage to reproduce the issue with the branch 1.7.5.x.
![image](https://user-images.githubusercontent.com/16067358/46278370-3c12c800-c566-11e8-8856-7353e4467681.png)
When we refresh the page, only one feature will be displayed.

In the previous version 1.7.4.2, when we have multiple features, settings will be saved successfully with **green alert** but when we refresh the page, only one feature will be displayed.
We will see how to fix it.

Best regards, Khouloud

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10956

**Comment by ezquerro25** [comment]
How did you fix it even I see this problem in my Prestashop 17.6. ????????
