### ISSUE TITLE
Category Tree module always displays latest visited category with default settings

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10763]
**Describe the bug**
Read below.

**To Reproduce**
1. Go to 'Clothes'
2. Category tree on your left starts from 'Clothes'
3. Now move to the "New products" page, still 'Clothes' on your left
4. Now go to 'Art', go once again to 'New Products', 'Best sales' or other page with a left column and you'll see that category block is now 'Art'.

Settings from category tree module should have been used only on category pages, not on any other page, we should have full category tree every time we visit page different than 'Category', there's no point of following last visited category on pages like 'New products' etc...

**Additionnal information**
PrestaShop version: 1.7.0.0 to 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
Yes, I manage to reproduce the issue with the last version 1.7.4.2.
We will see how to fix it.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4 also.
In the BO => Design => Theme & Logo => Click on "Choose layouts" => Edit CMS to `Two Columns, small left column - Two columns with a small left column`
In the FO => 
I navigate to a page first => OK.
![image](https://user-images.githubusercontent.com/16067358/53732859-74089900-3e7f-11e9-9bf3-e21b777c90cb.png)

If I navigate to a category then to a page => NOK =>  the last visited category is displayed
![image](https://user-images.githubusercontent.com/16067358/53732875-8256b500-3e7f-11e9-870d-2c66daf40a3b.png)

https://drive.google.com/file/d/1L1BkO2ruizMcVR0uOl41cbadfsPUXkOd/view
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
H!

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20947 to fix the issue.
Thanks, @jbenezech!

**Comment by jbenezech** [comment]
@khouloudbelguith I think it's actually 2 different things.  

This issue requests a change in the behaviour of the ps_categorytree module.  

Issue #20946 simply reports a bug in the current behaviour and my PR would only fix that. It will not solve this issue.

If this issue gets solved however, issue #20946 and PR #20947 will probably be irrelevant.
