### ISSUE TITLE
install bug - an error has occured - 403 on index.php

### ISSUE THREAD

**Issue by jstillings1** [PrestaShop/PrestaShop#10768]
**Describe the bug**
Hi guys, I want to report a few things to ya about installing and the 403 error I am experiencing doing so.
I have my hosting working very hard to solve this also but I figured I would reach out here.

**To Reproduce**
I am terribly bad at anything but making videos to reproduce failures( I did not overlay my normal yelling about it...) So here ya go full video very quiet of every step to reproduce failure of installer. [https://theforbiddenarts.com/walk-thru-videos/presta shop install fails.mp4](https://theforbiddenarts.com/walk-thru-videos/presta%20shop%20install%20fails.mp4)

**Screenshots**
I have a few other wild screen shots of issues. not sure related.
BTW our hosting is a preferred vendor
![imh prefered hosting](https://user-images.githubusercontent.com/29980804/46240796-c7c80100-c37a-11e8-887b-80710b9d042e.png)

So there should be no question of is your host up to it.
This was an error on our site after we forced an install using Softallicious.
https://prntscr.com/l01cc7

This is the reoccurring error on the softallicious installed shop
![403 error](https://user-images.githubusercontent.com/29980804/46240907-7d478400-c37c-11e8-951f-c2eb9f11e95b.png)

I have another shop installed and have same 403 issues. The funny thing is if i keep smacking refresh I eventually get the site and then that invalid token page.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: Little bit of info and i am aware this is very insecure posting all this...But that desperate for a fix.
PHP 7.2 (ea-php72) 
![pool options](https://user-images.githubusercontent.com/29980804/46241292-73298380-c384-11e8-91fb-0f22029a53d3.png)

This is our php -fpm INI file

[php-fpm ini.txt](https://github.com/PrestaShop/PrestaShop/files/2430264/php-fpm.ini.txt)

The  Pool ini file is this
[php-pool ini.txt](https://github.com/PrestaShop/PrestaShop/files/2430269/php-pool.ini.txt)

Apache log
[403.txt](https://github.com/PrestaShop/PrestaShop/files/2430299/403.txt)

PHP error log
[shopfth_com.php.error.log](https://github.com/PrestaShop/PrestaShop/files/2430307/shopfth_com.php.error.log)
Current Easy apache 4 profile This changes alot as the guys at the host are trying different stuff. ATM is is
[Current Apache4 profile.txt](https://github.com/PrestaShop/PrestaShop/files/2430308/Current.Apache4.profile.txt)

Let me know if I need to provide anything else

**Comment by jstillings1** [comment]
Oh server is a Centos 7.5 with CPanel 74.0.8 with WHM and NGINX installed in a reverse proxy.

**Comment by jstillings1** [comment]
I rewrote the installer a little bit to give some error messages.

[index.php.txt](https://github.com/PrestaShop/PrestaShop/files/2432000/index.php.txt)

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

Thanks for your report.
It is a permission issue.
Thanks to follow these steps:

1. Set up your database
2. Download Prestashop and extract
3. Upload Prestashop to your server using FTP
4. Change file permissions of all directories to 777 using your FTP software. In Filezilla, this is done by:
5. File permissions >777>tick box to do it for all subdirectories> choose directories only
6. Go to the website in a browser and follow instructions as normal
7. Delete the install folder
8. Rename ‘admin’ folder and record the new name

Thanks to check & feedback.

Best regards, Khouloud

**Comment by jstillings1** [comment]
Are you aware when you extract the download there is no folders and only a zip and an index.php file that unzips it on the server?
http://prntscr.com/l0w6g4

Are you also aware that unziping the zip inside the download and ftpin up will take about a day!

There is a reason the index.php uses gz to unzip it...

Are you also aware the download installs nasty .htaccess files deep inside the file structure? 
here is an example 
`# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
</IfModule>`
`# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>
`

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

Thanks to follow this link: https://www.youtube.com/watch?v=IOM9AffOa3s, check, and feedback.

Best regards, Khouloud

**Comment by jstillings1** [comment]
Thank you for trying to help @khouloudbelguith 
have a look at my issue
[video of 403](https://www.youtube.com/watch?v=rUzUABhMz-k&feature=youtu.be)

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

403 errors usually mean that the server does not have permission to view the requested file or resource. These errors are often caused by IP Deny rules, File protections, or permission problems.
In many cases, this is not an indication of an actual problem with the server itself but rather a problem with the information the server has been instructed to access as a result of the request.
**File and Directory Permissions**
The server you are on runs applications in a very specific way in most cases. The server generally expects files such as HTML, Images, and other media to have a permission mode of 644. The server also expects the permission mode on directories to be set to 755 in most cases.
File and Directory Permissions
The server you are on runs applications in a very specific way in most cases. The server generally expects files such as HTML, Images, and other media to have a permission mode of 644. The server also expects the permission mode on directories to be set to 755 in most cases.
Could you please check the issue with your host & feedback.

Best regards, Khouloud

**Comment by jstillings1** [comment]
Hi, the host IMH has been chasing this issue for about 5 days now with no clear answer. They keep closing the ticket with a we fixed it and i show them it fails right after.
They are about as frustrated as I.

After finding the dirty .htaccess files in the download i did a little cleaning of the .zip and removed the ones that block. I then modded the index to report more diag on the gz process. I am about to upload a video of yesterdays work of that. We currently have two VPS reseller hosts with them and I only tried to install this on the non PHP-FPM and could not get the allow_url_fopen to go away. I will try today on the PHP-FPM modded VPS it has 7.2 on it.

**Comment by jstillings1** [comment]
This was yesterdays work.[yesterdays work to try to get it to install](
https://www.youtube.com/watch?v=oFBbjZgypWA&feature=youtu.be)

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

Thanks to check again & feedback.
Also, you can follow this link to get PrestaShop system requirements.

Best regards, Khouloud

**Comment by jstillings1** [comment]
You do not have a list of what apache mods requried and a list of php ext required. I wish ya did.
About all i KNOW it needs at this time is apache 2.4 and GZ and Curl and ssl and pdo.

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

You can follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by jstillings1** [comment]
checking now I get a 403 after typing in the user name and password
 gonna try it on the non-php-fpm server

**Comment by khouloudbelguith** [comment]
@jstillings1, after editing the php.ini file, you need to restart apache.

**Comment by jstillings1** [comment]
On that server in the video we do not get that kind of control it is a managed vps.

**Comment by jstillings1** [comment]
Here is a video of the results on the php-fpm modded server after setting all folder permissions to 0777
[777 fails](https://www.youtube.com/watch?v=tE1U9FRXeSw&feature=youtu.be)

**Comment by jstillings1** [comment]
I completely gave up on that server I bought another server that does not use cpanel( plesk)  and am focusing on building the site there. This installed with zero issues and zero headaches. I just have to point the domain and wait for dns

**Comment by khouloudbelguith** [comment]
@jstillings1 do you have the same issue with this new server?

**Comment by jstillings1** [comment]
I have not been able to install presta shop on either of the VPS from IHM. I was able to on the plesk based server. And after 5 days of IHM telling me try this I give up.

**Comment by jstillings1** [comment]
This is the new server based on plesk. https://host.tfa.services/shopfth/phppsinfo.php
there is only 1 setting that i cant find
that is the memcached php ext
http://prntscr.com/l0y1a3

**Comment by khouloudbelguith** [comment]
@jstillings1 so did you manage to install PrestaShop now?

**Comment by jstillings1** [comment]
Not on either of the two VPS hosted at IHM no. I had to buy another one from elsewhere which installed like a champ.

**Comment by jstillings1** [comment]
Use a PLESK server problem solved.

**Comment by khouloudbelguith** [comment]
Hi @jstillings1,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud
