### ISSUE TITLE
Stock management quantity is not synced with Product quantity

### ISSUE THREAD

**Issue by niccoX** [PrestaShop/PrestaShop#10779]
**Describe the bug**
A user in the PrestaShop forum is indicating an issue with the product synchronization between Advanced Stock Management and Products> Quantities when an item is returned,

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: N/A
Link: https://www.prestashop.com/forums/topic/636109-stock-management-quantity-is-not-synced-with-product-quantity/ # #

**Comment by khouloudbelguith** [comment]
Hi @niccoX,

Have you the same issue described in this old ticket: http://forge.prestashop.com/browse/PSCSX-7764?

Best regards, Khouloud

**Comment by niccoX** [comment]
Hi @khouloudbelguith 

Yes it's the same issue.

**Comment by khouloudbelguith** [comment]
@marionf what do you think about this issue? 
This issue is added to our bug roadmap since 07/02/2017.

**Comment by niccoX** [comment]
@khouloudbelguith Do you think it's possible to assign anyone to this issue, as it affects everyone in production using ASM.

**Comment by khouloudbelguith** [comment]
Hi @niccoX,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-7764
It wasn't necessary to create a new one.
So, this one can be closed
Thanks!
