### ISSUE TITLE
Persist prestashop data using docker

### ISSUE THREAD

**Issue by soosap** [PrestaShop/PrestaShop#10771]
If you remove the container all your data and configurations will be lost, and the next time you run the image the database will be reinitialized. I wanted to mount volumes to the directories that are user-generated such as **uploaded images, configuration, etc.**. What directories in particular hold user-generated content?

Keep in mind I cannot just use a single volume for `/var/www/html`. What that would do is kind of conceal all the files that existed in this directory prior to the volume mount. More precisely, I am asking what are the directories, in which content is being written due to the user configuring stuff/uploading content via the Prestashop backend?

Here is a list of all the folders in `/var/www/html`

```
-rw-rw-rw- .htaccess
-rw-r--r-- INSTALL.txt
-rw-r--r-- LICENSES
drwxr-xr-x admin
drwxr-xr-x app
-rw-r--r-- autoload.php
drwxr-xr-x bin
drwxr-xr-x cache
drwxr-xr-x classes
-rw-r--r-- composer.lock
drwxr-xr-x config
drwxr-xr-x controllers
-rw-r--r-- docker-compose.yml
-rw-r--r-- docker_updt_ps_domains.php
drwxr-xr-x docs
drwxr-xr-x download
-rw-r--r-- error500.html
-rw-r--r-- images.inc.php
drwxr-xr-x img
-rw-r--r-- index.php
-rw-r--r-- init.php
drwxr-xr-x install
drwxr-xr-x js
drwxr-xr-x localization
drwxr-xr-x mails
drwxr-xr-x modules
drwxr-xr-x override
drwxr-xr-x pdf
-rw-r--r-- robots.txt
drwxr-xr-x src
drwxr-xr-x themes
drwxr-xr-x tools
drwxr-xr-x translations
drwxr-xr-x upload
drwxr-xr-x var
drwxr-xr-x vendor
drwxr-xr-x webservice
```

Looking forward for pointers! Thank you.

**Comment by PierreRambaud** [comment]
You need to use docker volume to keep your data when playing with docker container. Can you tell us how you use it?

**Comment by soosap** [comment]
Hi actually, I realized just persisting the `/var/www/html` directory will do the job. The docker run script checks if the destination is empty and if so will take care that a re-initialization occurs.

```
# init if empty
cp -n -R -p /tmp/data-ps/prestashop/* /var/www/html
```
