### ISSUE TITLE
BO - Modules Catalog - LayoutExtension cannot find the {$content} string in legacy layout template

### ISSUE THREAD

**Issue by scoreggino** [PrestaShop/PrestaShop#10786]
**Describe the bug:** When opening the Modules & Services tab I get an internal 500 error, this is the exception I got after enabling Debug mode: An exception has been thrown during the rendering of a template ("PrestaShopBundle\Twig\LayoutExtension cannot find the {$content} string in legacy layout template").

**To Reproduce:** BO -> modules -> Modules & Services -> error

**Screenshots:**
![schermata 2018-10-01 alle 10 30 00](https://user-images.githubusercontent.com/36135855/46278239-dd4d4e80-c565-11e8-819d-976c7360a33f.png)

![schermata 2018-10-01 alle 10 30 36](https://user-images.githubusercontent.com/36135855/46278263-f1914b80-c565-11e8-83e2-ac7ec1f60d9c.png)

![schermata 2018-10-01 alle 10 31 02](https://user-images.githubusercontent.com/36135855/46278270-f655ff80-c565-11e8-9492-75f4332f3137.png)

**Additionnal information:**  
I'm having this issue in two of the websites i'm managing and the only thing they are sharing is the theme.
This is an old forge report i found with the same exception: http://forge.prestashop.com/browse/BOOM-6130

Server: Linux # 1 SMP Tue Apr 23 19:29:00 UTC 2013 x86_64
Server software: Apache
PHP version: 5.6.37
MySQL version: 5.6.40
PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @scoreggino,

IS this a fresh install 1.7.4.2? or it is an upgrade from a previous version?
Did you installed any custom module before this issue occurs?
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Best regards, Khouloud

**Comment by scoreggino** [comment]
I recently upgraded to the latest version, i tried deleting everything inside cache but nothing changed.
I have installed a module recently, so I uninstalled and cleared cache but again no difference.

**Comment by khouloudbelguith** [comment]
Hi @scoreggino,

What is the exact version of 1-click upgrade did you use?
What is the previous version Prestashop did you use before the upgrade?

Best regards, Khouloud

**Comment by scoreggino** [comment]
I didn't use the 1-click upgrade module I updated it manually, Prestashop was version 1.7.1.1.

**Comment by khouloudbelguith** [comment]
Hi @scoreggino,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.
The solution is to add the missing columns to your database schema.
You can find the schema changes to 1.7.3.0 by looking at this file: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.4.2.sql
https://github.com/PrestaShop/PrestaShop/compare/1.7.1.1...1.7.4.2
You can find the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql
Also, you can follow this documentation: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/ for more details about to upgrade Prestashop.

Best regards, Khouloud

**Comment by scoreggino** [comment]
Yea I checked and some tables were different from the 1.7.4.2 schema, I updated them and now everything is working fine.

Thanks for the support.

**Comment by khouloudbelguith** [comment]
Hi @scoreggino,

Thanks for your feedback.
Feel free to open a new one when needed.

Best regards, Khouloud

**Comment by philoupin** [comment]
Hi @scoreggino,

do you recall which tables were different? I am in the same situation and I seem to have all tables here that are in the PS 1.7.4.4 distribution....

many thanks!
P.

**Comment by Gionny996** [comment]
@philoupin I have your same problem

**Comment by philoupin** [comment]
I am currently getting help in this thread which apparently treats the same issue: https://github.com/PrestaShop/PrestaShop/issues/10853
