### ISSUE TITLE
Unit price reset to 0 if you activate/deactivate or duplicate products in bo product list

### ISSUE THREAD

**Issue by fdelprete** [PrestaShop/PrestaShop#10792]
**Describe the bug**
The Unit price and cost price are reset to 0 if you activate/deactivate/duplicate products from the product list.

**To Reproduce**
You have a product with unit price & cost price value.
From the product list you deactivate the product (both with single action or via mass action).
You open the product form and you can see that the unit price & cost price are set to 0.

NB
If you activate/deactivate the product from the product form the unit price works well.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.22

**Comment by khouloudbelguith** [comment]
Hi @fdelprete,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.2 / 1.7.5.x / 1.7.3.4
We will see how to fix it.

Best regards, Khouloud

**Comment by centoasa** [comment]
Same issue with cost price
If you save new cost price, then  reopen product is always 0
Behaviour only on duplicated products.
Prestashop 1.7.6.1 and php 7.2.22

**Comment by khouloudbelguith** [comment]
Hi,

The cost price is ok with ps1.7.6.1.
It is ok when we duplicate or disable a product from the product list page or the product details page.
The unit price not ok as always.

Related issue: #16353 just reproduced with PS1.7.6.1 & PS1.7.6.2build1

Thanks!

**Comment by khouloudbelguith** [comment]
Hi!

This issue will be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/20680
Thanks to @artaban!
