### ISSUE TITLE
Update link to Traffic & SEO page in product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10794]
**Describe the bug**
Update link to SEO & URLs page in product page

**To Reproduce**
1. Go to Catalog > Product
2. Edit a product
3. Click on SEO tab
4. The link to the Traffic & SEO should be the one of the migrated page

**Screenshots**
![capture d ecran_361](https://user-images.githubusercontent.com/13449658/46289058-2910ef80-c588-11e8-9d87-6f0d55e637e2.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
See #10796
