### ISSUE TITLE
Empty customers orders! - need fast help

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#10805]
Hi, have big isssue from yestarday, first time have problem like that. We notice that the last two orders is empty, its look like this: 

![screencapture-tomskor-pl-admin850kwyszj-index-php-2018-10-02-09_38_44](https://user-images.githubusercontent.com/42567245/46335329-58c30480-c627-11e8-8fba-83c90ea69651.jpg)

And only one thing what changed from yesterday is install a integration module to arena.pl 

There is logs from shop:
![screencapture-tomskor-pl-admin850kwyszj-index-php-2018-10-02-09_42_17](https://user-images.githubusercontent.com/42567245/46335394-8f008400-c627-11e8-8fa5-10e362f81aab.jpg)

And when I trying to add new test order everything is fine... anyone have this problem?

**Comment by kpodemski** [comment]
This is not a place for issues like this, you should go to official forum or Facebook group and ask for help.

Probably you have some issues related to payment module and order is not validated correctly at the end of checkout. This is not a global issue, PrestaShop problem etc.

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

Best regards, Khouloud

**Comment by Tomskor** [comment]
I dont think so, problem is with your module not a payu. We have empty order with some amount to pay and when I want add missing products the amount is doubled. I update every module and for now new orders is work propetly.

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

So the issue is fixed after updating all payment modules?

**Comment by Tomskor** [comment]
@khouloudbelguith hard to tell, cuz I update a cart module too and I think its a problem. In logs there is line with "Cart cannot be loaded or an order has already been placed using this cart" and date is exact same like this empty orders.

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

About this error [Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart], you can follow this issue: #9866, it is added to our bug roadmap.

Best regards, Khouloud
