### ISSUE TITLE
Product ref with combinations

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10809]
**Describe the bug**
My product have a global ref (in basic settings tab)
My product have a specific ref for each combination (combinations tab)
In FO, the ref displayed is always the global one instead of the combination one

**To Reproduce**
1. Go to Catalog > Product
2. Edit the product Affiche encadrée Today is a good day
3. Enter a ref in basic settings tab
4. Edit each combination and add a specific ref for each
5. Go on the product page in FO and you will see always the global ref if you change combinations

**Screenshots**

![capture d ecran_362](https://user-images.githubusercontent.com/13449658/46341650-0985cf80-c639-11e8-885f-215a583a0f7d.png)

![capture d ecran_363](https://user-images.githubusercontent.com/13449658/46341655-0c80c000-c639-11e8-9842-0f38118d3602.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Here's the PR: #10812 to solve the issue.

Best regards, Khouloud
