### ISSUE TITLE
must_have_module_list.xml errors today 1 October

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10801]
Hi

**To Reproduce**
today two sites that I manage one in Italy and one in Spain in the afternoon have the same error in the admin side. Today all sites have a new must_have_module_list.xml and probably it has some error inside it

`3 errors 
Error found : StartTag: invalid element name in must_have_module_list.xml file.
Error found : Premature end of data in tag module line 1 in must_have_module_list.xml file.
Error found : Premature end of data in tag modules line 1 in must_have_module_list.xml file.`

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/46311181-aa38a880-c5c1-11e8-880f-e2caf677d6d1.png)
![11](https://user-images.githubusercontent.com/653230/46311182-aa38a880-c5c1-11e8-8430-1934ae190396.png)
![2](https://user-images.githubusercontent.com/653230/46311489-a9ecdd00-c5c2-11e8-9298-72de065d25be.png)

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 7.0

bye

**Comment by MathiasReker** [comment]
Clear cache and it is solved. It was due to API problem with prestashop. I had the same.

**Comment by Maofree** [comment]
hi
yes cleaning the cache the error goes away
thanks
