### ISSUE TITLE
Translation domains still present in translation tool even if empty

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#10807]
**Describe the bug**
If you create a theme and add a few translations witha custom domain - if you change it later so that domain is not in use anywhere in the template files, that domain still shows up when going into translations. This will return an error saying that there is no translation file available.

**To Reproduce**
1. Create a new theme
2. Add a translation with a custom domain in any `.tpl` file, i.e:<br>`{l s='My string' d='Shop.Foo'}`
3. Go into the translation tool, select theme translations and it will be displayed.
4. Go back to that same `.tpl` file and change the domain to something else, i.e.<br>`{l s='My string' d='Shop.Bar'}`
5. Go back to the translation tool, select them translations and the "new string" will be there.
6. The old domain will still be there even if there are no translations connected to it. If you select it you will get an error.

**Additionnal information**
PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

I attached a video record.
https://drive.google.com/file/d/1nFLz49daYuix4sbV06hiKSH_RvV9-FrY/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by dennispw** [comment]
@khouloudbelguith For some reason I can not reproduce the behaviour in a fresh install. It is however present in another fresh install. I guess there must be some difference in the environment but as of right now I can't figure out what.

You can close it, I'll come back to this issue if I can reproduce it more accurately.

**Comment by khouloudbelguith** [comment]
@dennispw thanks for your feedback.
I close the issue, feel free to open a new one when needed.
