### ISSUE TITLE
remove white-space: nowrap from .btn class

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10818]
Hi
I suggest you to remove the from .btn class of theme.css
white-space: nowrap
because for small devices the buttons with that class go outside the view

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/46369804-49be6f80-c684-11e8-9c03-2e2a478477a8.png)
![2](https://user-images.githubusercontent.com/653230/46369805-49be6f80-c684-11e8-9f1e-40cf3e8e161c.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree, I manage to reproduce the issue with PS 1.7.4.2.
When the resize the window less than 296px * 981px, the button goes outside the view.
We will see how to fix it.

**Comment by rdy4ever** [comment]
The `nowrap` value for the `btn` `white-space` property  comes from [bootstrap](http://getbootstrap.com/docs/4.1/components/buttons/). And I do believe it is a UX best practice not to wrap buttons. 
296px is by no mean a 2018 smarphone common width, even the 2011 budget mini-galaxy phone [Samsung Galaxy Gio](https://www.gsmarena.com/samsung_galaxy_gio_s5660-3741.php) or the 2007 [original iPhone](https://www.gsmarena.com/apple_iphone-1827.php) had a 320px horizontal resolution. So I don't see the need to suport <300px viewports.

**Comment by marionf** [comment]
I can't reproduce with PrestaShop 1.7.5.1

![capture d'écran_1397](https://user-images.githubusercontent.com/13449658/56194007-43954c80-6032-11e9-9ad1-5662c341378e.png)

![capture d'écran_1398](https://user-images.githubusercontent.com/13449658/56194062-66bffc00-6032-11e9-90f6-400cd9ced374.png)
