### ISSUE TITLE
Can't transplant a module

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10811]
**Describe the bug**
Can't transplant a module

**To Reproduce**
1. Go to Design > Position
2. Click on Transplant a module
3. You are still on the same page

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by PierreRambaud** [comment]
Will be fixed with @jolelievre changes about `_legacy_link` =)

**Comment by PierreRambaud** [comment]
this issue was introduced after this PR => https://github.com/PrestaShop/PrestaShop/pull/10796 maybe it can be fixed it this one => https://github.com/PrestaShop/PrestaShop/pull/10821

**Comment by jolelievre** [comment]
Will be Fixed by https://github.com/PrestaShop/PrestaShop/pull/10868
