### ISSUE TITLE
Order Prints show menu

### ISSUE THREAD

**Issue by GeoTimber** [PrestaShop/PrestaShop#10826]
Presashop 1.7.4.2

I have the menu appearing on Order prints as attached on all browsers

[Pedidos _ Pedido VBGCQKYFA de alberto hortelano • Las Torcas S.C.A_.pdf](https://github.com/PrestaShop/PrestaShop/files/2441436/Pedidos._.Pedido.VBGCQKYFA.de.alberto.hortelano.Las.Torcas.S.C.A_.pdf)

**Comment by khouloudbelguith** [comment]
Hi @GeoTimber,

This is the PR to fix the issue: #10135
The issue will be fixed on 1.7.5.0. I'm closing as this is a duplicate of #9527.
