### ISSUE TITLE
[SF Migration] Use a JS routing registry

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10828]
In new-theme JS code we usually provide routes to JS classes using this kind of workaround:

```
const ajaxUrl = $('.js-save-import-match').attr('data-url');
```

I'm looking for ideas to improve this 🤔

**Comment by sarjon** [comment]
this is what comes to my mind => https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/usage.html

**Comment by matks** [comment]
Implemented in https://github.com/PrestaShop/PrestaShop/pull/15814/files for 1.7.7.0
