### ISSUE TITLE
[SF Migration] Grid extension: what happens to filters, sort, search, export ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10823]
Initial topic https://github.com/PrestaShop/PrestaShop/pull/10777#discussion_r222205039

## Summary

Symfony pages using [the Grid]() allow modules to add
- new columns
- new bulk actions
- new grid actions

However, if a module adds a new column and fills it with some custom data, how should/does it handle
- filtering/searching this new column
- sorting this new column
- exporting this new column

1. What classes/services does it needs to decorate/override today to achieve it?
2. Can we make it easier to achieve it?

**Comment by matks** [comment]
To be tried:
> i think that all we have to do is pass SearchCriteria to the hook so modules can handle their filters however they want to, wdyt? (sarjon)

**Comment by hibatallahAouadni** [comment]
Hello @matks 

What is the status of this improvement?

Thanks!

**Comment by matks** [comment]
@hibatallahAouadni ToDo I think

**Comment by matks** [comment]
ping @zuk3975 @jolelievre @JevgenijVisockij if you want to add suggestions / usecases / constraints
