### ISSUE TITLE
It is impossible to import data - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10838]
**Describe the bug**
In the import page, we try to import products; categories;.., after clicking on the "Next step" button, we are redirected to an error page.

**To Reproduce**
1. Go to BO => Advanced Parameters => Import page
2. Click on Choose a file
3. Set the "Field separator" option & "Multiple value separator" option
4. Click on "Next step"
5. See error

**Screenshots**
https://drive.google.com/file/d/1kBShzFJBzMc9k6nlSmuHJXahRg8uT9HO/view

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: 7.1

**Comment by sarjon** [comment]
this issue was introduced after this PR => https://github.com/PrestaShop/PrestaShop/pull/10796 maybe it can be fixed it this one => https://github.com/PrestaShop/PrestaShop/pull/10821
