### ISSUE TITLE
Back button redirects to 'Modules & Services' instead of previous step - for 'Image Slider' Module

### ISSUE THREAD

**Issue by NadiaCamard** [PrestaShop/PrestaShop#10848]
**Describe the bug**
Wrong link on the 'Back' button in 'Image Slider' Module

**To Reproduce**
1. Go to 'Image Slider' Module
2. Scroll down to 'Slides list' block and click on any 'Edit' button
3. Once the page loaded, click on the Back button in the top-right corner
4. It redirects to 'Modules & Services' page. It should display the 'Image Slider' configuration page.

**Screenshots**
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/40669854/46461195-5fd04b00-c7be-11e8-8e4e-82e0dc50a047.gif)

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi, Image slider  v3.0.0 - by PrestaShop
Related to #10846

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith and @NadiaCamard, since it is related to all modules and already raised by PR #10846, I close this issue. Feel free to re-open it if need be!
