### ISSUE TITLE
Release 1.7.4.3 doesn't have a installation zip file

### ISSUE THREAD

**Issue by ricardo-lobo** [PrestaShop/PrestaShop#10842]
**Describe the bug**
From what I've seen recently, releases usually have a zip file attached in the form of prestashop_1.7.*.*.zip

**To Reproduce**
1. Go to https://github.com/PrestaShop/PrestaShop/releases
2. Click on PrestaShop 1.7.4.3
3. See error

![screen shot 2018-10-03 at 18 22 10](https://user-images.githubusercontent.com/21181036/46427471-6bc5f980-c739-11e8-8633-40609a45432d.png)

![screen shot 2018-10-03 at 18 22 30](https://user-images.githubusercontent.com/21181036/46427480-741e3480-c739-11e8-9b8f-aa3192ab2ef1.png)

**Additionnal information**
PrestaShop version: 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @ricardo-lobo,

If you download the last version from the official website, https://download.prestashop.com/download/releases/prestashop_1.7.4.3.zip?_ga=2.115669190.195077929.1538385031-446192319.1536843266, you will find the zip file attached in the form of prestashop_1.7...zip.
About this link: https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.4.3, you are right, the zip file is missing, @eternoendless what do you think?

**Comment by eternoendless** [comment]
Fixed! Thanks for noticing @ricardo-lobo 👍
