### ISSUE TITLE
advanced eu compliance - shipping cost

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#10866]
Hello, can you please restest if the latest version is showing shipping cost (also free shipping) correctly on the cart page... i had a shop test and this part is missing , but i noticed it worked on previous version of this module...

How to reproduce 👍 
Use latest version of prestashop 1.6 , add the advanced compliance module, add the product to cart and go to checkout

Kind regards,
jimmy

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Thanks for your report.
The "Total shipping" is missing on your cart page?
![image](https://user-images.githubusercontent.com/16067358/46490348-19074300-c808-11e8-8b38-bc925a6a09a5.png)

**Comment by demeldoo** [comment]
yes,yes,,, you saved my day :) free shipping..or total shipping... on this first step.... yes, its missing...

can you provide me some help...fix ?

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

If you are not logged, the shipping cost is not displayed.
Since you are logged, it will be displayed.
I attached a video record: https://drive.google.com/file/d/1gHFGk-xjTx1Hg7OUY2qYpVK2zzWEEUWi/view
Thanks to check & feedback.

**Comment by demeldoo** [comment]
thank you for clarification, it seems that this behaviour is not completly ok, i had an standard agency testing a shop, and they say eu laws demand that the shipping cost should be displayed (has no sense to me also, because by logging the location is set)

**Comment by khouloudbelguith** [comment]
@demeldoo thanks to check with them again & feedback.

**Comment by demeldoo** [comment]
Hello @khouloudbelguith , i belive they tested the site with Opera browser, can you please recheck.

It's not showing on my latest Opera browser, also there is a secondary bug changing the quantity in the cart (plus , minus).

Best wishes,

Jimmy

**Comment by demeldoo** [comment]
also, have you checked the v2.0.2  version of advanced eu complinace running php 7.1, file cache on, apcu cache, smart cache on, compression...move js to end...everything on

**Comment by demeldoo** [comment]
because i have tested also chrome, safari , firefox

**Comment by khouloudbelguith** [comment]
@demeldoo, it is OK with Opera browser_version=56.0
![image](https://user-images.githubusercontent.com/16067358/46619988-cbe6e200-cb23-11e8-8cb7-c64503b25621.png)

**Comment by demeldoo** [comment]
hello,

yes now it is working... does the module grabs something from the internet ??? because it started working now

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Thanks for your feedback.
It could be a browser/shop cache.
Since it is fixed I close the issue, feel free to open a new one when needed.
Thanks!
