### ISSUE TITLE
Specific Price - Catalog rules - date filtering - PrestaShopDatabaseException

### ISSUE THREAD

**Issue by Shiryu75** [PrestaShop/PrestaShop#10876]
**Describe the bug**
PrestaShopDatabaseException error on the controller AdminSpecificPriceRule. The filtering system on the dates is causing that when using arrows. 

**To Reproduce**
1. Go to admin controller AdminSpecificPriceRule (catalog -> discounts) -> Catalog rules.
2. Create at least 2 CATALOG RULES
3. After that, try to apply a filter on the dates by using the arrows

**Screenshots**
![image](https://user-images.githubusercontent.com/6507405/46536663-7a362180-c8af-11e8-881b-b5193f7bad42.png)

**Additionnal information**
PrestaShop version: 1.7+
PHP version: 5.6 but it doesn't matter. It's a code issue.

**Bug location**
./classes/controller/AdminController.php line 3164 (on 1.7.5) we have :         
$orderByClause = $this->getOrderByClause($order_by, $order_way);

While filtering, if you apply a specific date inside the inputs, it's working fine. But if you try to use the arrows, the sql request becomes : " ORDER BY from ASC" or  " ORDER BY to DESC" - causing the error.

**Comment by khouloudbelguith** [comment]
Hi @Shiryu75,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.3 / 1.7.4.2
![image](https://user-images.githubusercontent.com/16067358/46602615-f5d2e100-caf0-11e8-85db-2a83b26fd052.png)
We will see how to fix it.
Thanks!
