### ISSUE TITLE
The image on the page redirects does not scale

### ISSUE THREAD

**Issue by corsik** [PrestaShop/PrestaShop#10870]
http://prntscr.com/l2fcx3

**Comment by khouloudbelguith** [comment]
Hi @corsik,

Thanks for your report.
I manage to reproduce the issue with PS 1.7.4.3 / 1.7.5.x.
![image](https://user-images.githubusercontent.com/16067358/46600567-d3d66000-caea-11e8-94f7-3c0ed68b86f4.png)
We will see how to fix it.
Thanks!
