### ISSUE TITLE
Ajax cart first add doesnt work

### ISSUE THREAD

**Issue by itroom-agence** [PrestaShop/PrestaShop#10873]
**Describe the bug**

On a product page when you  try to add a product in the cart (before the page is fully loaded but after the DOM load) our product is not added to the cart modal.

**To Reproduce**

1. First connexion to a prestashop website
2. Go to a product page
3. Before the page is fully loaded but after the dom is load
4. Wait for ajax return of the modal
5. See error

**Additionnal information**

PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Thanks for your report.
I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1depnf_QhkBsomnM5DZZhQDLx5TiKeGrE/view
It will help us if you can attach a screen record.
Thanks!

**Comment by khouloudbelguith** [comment]
@itroom-agence, any news?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
