### ISSUE TITLE
1-click upgrade module - "Keep the customized email templates" does not work

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10886]
Hi
I've upgraded from 1.6.1.20 to 1.6.1.21 with 1-click upgrade 4.2.0 and the option "Keep the customized email templates" does not work, each time all emails inside mails/ are updated
I've no tested to upgrade the 1.7 versions but probably it does the same thing

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/46572678-5562ac80-c98a-11e8-88c2-8de5db767541.png)

**Additionnal information**
PrestaShop version: 1.6.1.21
PHP version: 7.0
Module version: 4.2.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-9782
It wasn't necessary to create a new one.
So, this one can be closed
Thanks!
