### ISSUE TITLE
Help message header isn't displayed correctly

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#10881]
Describe the bug
In BO, Attributes & Features page, Brand & Suppliers page , Discounts page (Catalog); Theme & logo page (Design) ; locations page, Taxes page(International) ; Contact page, Search page(Shop Parameters) ; and Team page(Advanced Parameters),Help message header does not displayed correctly. It should displayed like in the categories page.

To Reproduce
1. Go to in BO > SELL > Catalog > Attributes & Features , Brand & Suppliers and Discounts page. Click on help button.
2. Go to in BO > IMPROVE > Design > Theme & logo page and International > location page, Taxes page. Click on help button.
3. Go to in BO > CONFIGURE > Shop Parameters> Contact page and Search page. Click on help button.
4.Go to in BO > CONFIGURE > Advanced Parameters> Team page. Click on help button.

https://drive.google.com/open?id=1oaQ6-uHvDLM165_LYm5meI2VhMiz8nCb

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed by #10949
