### ISSUE TITLE
opera and safari quantity changing on checkout in 1.6.1.20

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#10887]
opera and safari quantity changing on checkout resulting a strange behaviour.. very bugy.

please recheck, try to change quantities in latest versions of opera and safari browser... try also from 1 to go down

kind regards,

jimmy

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

I did not manage to reproduce the issue with PS 1.6.1.21.
I attached a video record.
https://drive.google.com/file/d/1ck5gBVEVLuEs99C4zd4666hFeKEwQFvM/view
Thanks to check & feedback.

**Comment by demeldoo** [comment]
Please close this ticket, this was caused by poor internet connection.

My apologizes

**Comment by khouloudbelguith** [comment]
@demeldoo, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
