### ISSUE TITLE
safari adress on checkout

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#10888]
hello,

the adress is not showing on boxes in the checkout process...

please retry with latest version of safari browser,

thank you in advance,
jimmy

**Comment by demeldoo** [comment]
also, there is a big red warning when you go to next step

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Could you please provide us with more info? 
 - PrestaShop version (source)
 - screenshots
 - Did you use the default theme of Prestashop ?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
