### ISSUE TITLE
 Search module prestashop 1.6 does not work perfectly

### ISSUE THREAD

**Issue by RaspTLC** [PrestaShop/PrestaShop#10884]
Hello everyone and thank you in advance who will answer!
The search in my shop does not work perfectly, it does not find all the products.
Let me explain: for example, looking for the word "abito", the research should return 2 products instead it shows only one (and so also with other words).
The search is not complete!
I rebuild the entire index but it does not even work.
Can someone help me?

I use prestashop 1.6.0.14 and my website il http://romanouomo.com

Thanks

**Comment by khouloudbelguith** [comment]
Hi @RaspTLC,

In the BO => Preferences => Search page => did you enable the Search exact end match option?
Thanks to disable it, check & feedback.

**Comment by LuiMai5** [comment]
Hi khouloudbelguith,
thanks for reply!
The Search exact and match option is already disabled, and the serach don't work!
have you any other idea?
Thanks

**Comment by LuiMai5** [comment]
I think that the problem is caused by my theme:
is a free theme downloaded from templatemonsters.com and it have 4/5 language preset.
I delete it after i've added some product.
Now there is only italian language.
I've searched in Database the table ps_search_index and ps_search_word and i see that some product have an id_lang different from 6 (6 is the ID of italian language).
Can be this the problem?
What do you think?
And how can i fix it?

Thanks a lot!

**Comment by khouloudbelguith** [comment]
Hi @RaspTLC,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by LuiMai5** [comment]
Unfortunately is a free theme, and for this, templatemonster.com not support me!

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards

**Comment by manusegarra** [comment]
Hi there,

[Search.zip](https://github.com/PrestaShop/PrestaShop/files/2748659/Search.zip)

If someone is still searching for this, I have it solved for PS 1.6.0.9. You can check how it works at my site https://bouttye.com

Replace your file in httpdocs/classes/search.php with the attached file and you are done.

Kind regards.

Manuel Segarra.

**Comment by Pisanez** [comment]
> Hi there,
> 
> [Search.zip](https://github.com/PrestaShop/PrestaShop/files/2748659/Search.zip)
> 
> If someone is still searching for this, I have it solved for PS 1.6.0.9. You can check how it works at my site https://bouttye.com
> 
> Replace your file in httpdocs/classes/search.php with the attached file and you are done.
> 
> Kind regards.
> 
> Manuel Segarra.

Worked for me on Prestashop 1.6.1.24 you saved my work.

I was searching for a way to set the search bar in "AND" and not "OR", and it worked. i've got 15.000+ articles and writing blue+pen was giving me more than 500 results, now it works properly! THANK YOU
