### ISSUE TITLE
PDF attachments file can't down load

### ISSUE THREAD

**Issue by checkaxon** [PrestaShop/PrestaShop#10896]
I can't download attachments file.
https://proteushop.fr/en/oxygen-sensors/90678-oxygen-sensor-nrc-d-01-eq-r17-d.html

**Comment by khouloudbelguith** [comment]
Hi @checkaxon,

Have you tried to contact the theme author?
![image](https://user-images.githubusercontent.com/16067358/46597062-ddf26180-cade-11e8-9df6-5bf312be19e6.png)
Thanks to check with them & feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @checkaxon,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
