### ISSUE TITLE
Product availability_message incorect if order out of stock products is disabled

### ISSUE THREAD

**Issue by adctive** [PrestaShop/PrestaShop#10893]
BUG:
The $product.availability_message in product template is always displayed as "There are not enough products in stock"  if order of out of stock products is not allowed and it should display PS_LABEL_OOS_PRODUCTS_BOD

src/Core/Product/ProductPresenter.php:480
 } elseif ($product['quantity_wanted'] > 0 && $product['quantity'] >= 0) {  //this should be '>' not '>='

! notice: also availability_message that returns 'Product available with different options' on line 488 should be optional !

**Comment by khouloudbelguith** [comment]
Hi @adctive,

Thanks for your fix suggestion.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @andromaque

Thanks for the fix: #11204
