### ISSUE TITLE
Internal Server Error on [GET configurations] API call

### ISSUE THREAD

**Issue by sethsnel** [PrestaShop/PrestaShop#10900]
**Bug Description**
Our module mainly sets up a connection api authorization between PrestaShop and our system.
For most users this works perfectly fine. However, we have difficulty retrieving the shop configurations for some users.

This is an example call for a user which works fine:
https://pastebin.com/D2TJtCvz

This is an example call for a user which returns an internal server error:
https://pastebin.com/6AK3C82V

Since the server returns an internel error I have no clue whether we are doing something wrong or if there is an error on the PrestaShop side.

**Reproduction**
1. Execute GET call on configurations api method
2. Always fails for certain users

**Additionnal information**
PrestaShop version: N/A (could differ per user, but I don't know which PrestaShop version they use)

**Closing words**
Would like to know whether we are doing something wrong or of this is an error in PrestaShop API code. Thanks in advance.

Kind regards, Seth

**Comment by khouloudbelguith** [comment]
Hi @sethsnel,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sethsnel** [comment]
@khouloudbelguith I don't have acces to the users store/shop. So it is not easy to retrieve these server side logs and reports.

**Comment by khouloudbelguith** [comment]
@sethsnel The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself is vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

**Comment by sethsnel** [comment]
@khouloudbelguith Okay I'll try to gain access to their shop.

**Comment by khouloudbelguith** [comment]
@sethsnel, thanks!
Waiting for your feedback.

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
