### ISSUE TITLE
No carriers available in checkout when cart rule with a minimum amount & shipping included is not used

### ISSUE THREAD

**Issue by arisschl** [PrestaShop/PrestaShop#10903]
**Describe the bug**
When you have a cart rule that only applies from a minimum amount or quantity, no carriers are available in the checkout.

**To Reproduce**
1.Create cart rule without code

1. In the condition Tab "Minimum amount 100 EUR & Shipping included
1. In the actions tab, apply any action => Apply a discount
Go to FO, add to cart a product which price = 70 EUR < 100 EUR (must be < 100 EUR) => so the cart rule is not applied
Complete your order => in step 3: SHIPPING METHOD => Unfortunately, there are no carriers available for your delivery address.

**Additionnal information**
PrestaShop version: 1.7.4.3 & 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @arisschl,

I did not manage to reproduce the issue with the last version 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1UJHiEeXWv7x7oLbokBPaFHHtRB36LwgY/view
Thanks to check & feedback.

**Comment by arisschl** [comment]
Hi @khouloudbelguith ,

Thanks for checking, I have checked again and found that the error only occurs when the basket rule does not apply to the cart.
So can you please test again with a cart value less than specified in the basket rule?

**Comment by khouloudbelguith** [comment]
@arisschl, it is OK when the cart value less than specified in the basket rule or cart value more than specified in the basket rule
https://drive.google.com/file/d/1uW1UnlNzT_jxFWZVuKFlYz60RT2YlQeq/view
Could you please check your shipping locations & feedback.

**Comment by arisschl** [comment]
@khouloudbelguith, can you please check the video at
https://drive.google.com/file/d/1jRnBXAD5oH0U6Im3LIcmQc8Iv2PCHrMb/view

Found out that the indication "Shipping included" of the basket rule has effect on the error.

**Comment by khouloudbelguith** [comment]
@arisschl, I need permission to see the video record.

**Comment by khouloudbelguith** [comment]
Hi @arisschl,

Sorry for the delay.
I manage to reproduce the issue with the last version 1.7.4.4.
In the Cart rule" details, when "Shipping included" is selected => in FO, in the checkout process,  there are no carriers available for your delivery address.
https://drive.google.com/file/d/1EpoUOhGrSNfHcQm6p9QJ60iP9Tsq_KKf/view
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith I can't reproduce the issue, I see all carriers with a cart rule with shipping included

https://drive.google.com/file/d/1aDjGgAX2O_rGw5LMXZZe3dq6gafBPMI-/view?usp=sharing

**Comment by khouloudbelguith** [comment]
@marionf, can you please check if you have the issue when the cart rule is created without any code?
![image](https://user-images.githubusercontent.com/16067358/48429378-4f23d500-e76d-11e8-9102-e4d544cae9db.png)
Thanks!

**Comment by marionf** [comment]
Same thing

https://drive.google.com/file/d/11__YnsWpRoDhoy-nQCUDDV_z55vvKilt/view?usp=sharing

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Steps to reproduce the issue
1. Create cart rule
1.1 without code
1.2 In the condition Tab "Minimum amount 100 EUR & Shipping included
1.3 In the actions tab, apply any action => Apply a discount
2. Go to FO, add to cart a product which price = 70 EUR < 100 EUR (must be < 100 EUR) => so the cart rule is not applied
3. Complete your order => in step 3: SHIPPING METHOD => Unfortunately, there are no carriers available for your delivery address.

Thanks!

**Comment by jovh** [comment]
i also have this no carrier available for your delivery address - in the forums i found this https://www.prestashop.com/forums/topic/1027497-fix-for-unfortunately-there-are-no-carriers-available-for-your-delivery-address/

it s annoying please repair this asap - tnx !

**Comment by kijamve** [comment]
My solution is this, get this file:
`/classes/Cart.php`

Found this function:
`public function getCartRules`

And replace this lines:
```
if (!CartRule::isFeatureActive() || !$this->id) {
    return array();
}
```

for this:

```
if (!CartRule::isFeatureActive() || !$this->id || !$this->_products) {
    return array();
}
```

**Comment by jovh** [comment]
hello

tnx for this
did all but it didn t help... 🥴

bien à vous - vriendelijke groet


jo van hove
rue célestin hastir 6 bte 3
5150 floreffe

+32 475 440 454
pourquoi j écris comme j écris

**Comment by florine2623** [comment]
Hello ,

I can't reproduce this issue on POS 9.0.0 :

https://github.com/user-attachments/assets/80761741-6329-43df-968b-b7ebb8afe9ea

I'm closing the issue to avoid clogging the backlog.
Thanks!
