### ISSUE TITLE
Offical PayPal module error

### ISSUE THREAD

**Issue by febestore** [PrestaShop/PrestaShop#10907]
Hello.
I have a huge problem with official PayPal module. Module downloaded from https://addons.prestashop.com.
I have multistore with Polish and German shop.
When You try to enter German shop there are few PHP errors - screenshot in attachment. 

PayPal module is turned off at Polish shop (https://www.febe.store/sklep/pl/) - everything works fine. 

I have reinstalled the module. But the error still exists. Disabling module is fixing the issue.

Any ideas why PayPal module causes this problem?

**To Reproduce**
1. Go to https://www.febe.store/shop/de/
2. See error

**Screenshots**
![paypalerror](https://user-images.githubusercontent.com/40421616/46611276-a18a2a00-cb0d-11e8-9439-38405b58506c.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.32

**Comment by khouloudbelguith** [comment]
Hi @febestore,

The Paypal module isn't developed by PrestaShop.
You can contact the developer of this module here: https://www.202-ecommerce.com/en/partners-modules/technical-support/
Thanks for your understanding!
