### ISSUE TITLE
Wrong total and total_wt on order-confirmation with customization

### ISSUE THREAD

**Issue by lacrm** [PrestaShop/PrestaShop#10912]
**Describe the bug**
in the confirmation page, the total and the total_wt is wrong when we add a customization in the cart
![image](https://user-images.githubusercontent.com/17384523/46612653-773a6b80-cb11-11e8-8618-242858d49ad9.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

In classes\Product.php
![image](https://user-images.githubusercontent.com/17384523/46612473-ec597100-cb10-11e8-8ad3-1efb7b9d10a1.png)
$product_update['total_wt'] = 13,34  * (1 - 1); -> 0
$product_update['total'] = 13,9  * (1 - 1); -> 0

In templates\checkout\_partials\order-confirmation-table.tpl
![image](https://user-images.githubusercontent.com/17384523/46612693-976a2a80-cb11-11e8-8d26-9f2771ea16d8.png)

**Comment by khouloudbelguith** [comment]
Hi @lacrm,

I did not manage to reproduce the issue with the last version 1.7.4.3.
![image](https://user-images.githubusercontent.com/16067358/46613340-4bb88080-cb13-11e8-81ba-cd5098458840.png)
![image](https://user-images.githubusercontent.com/16067358/46613345-4f4c0780-cb13-11e8-8980-b9d2932b9e53.png)
Thanks to check & feedback.

**Comment by lacrm** [comment]
With a fresh install (1.7.4.3) : 
![image](https://user-images.githubusercontent.com/17384523/46614300-c84c5e80-cb15-11e8-94c0-e4969db5401c.png)

**Comment by khouloudbelguith** [comment]
@lacrm, thanks for this clarifications.
I manage to reproduce the issue on the order confirmation page with PS 1.7.4.2 / 1.7.4.3 / 1.7.5.x.
![image](https://user-images.githubusercontent.com/16067358/46615649-09923d80-cb19-11e8-9263-ddcc77e47366.png)
We will see how to fix it.
Thanks!

**Comment by lacrm** [comment]
You're welcome @khouloudbelguith 😉

**Comment by unlocomqx** [comment]
debug info mentioned in #12264

**Comment by khouloudbelguith** [comment]
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15171 to fix the issue.
Thanks @feyromain

**Comment by LouiseBonnard** [comment]
Dear @lacrm and @feyromain, the pull request #15171 fixing this issue is still in progress, could you please have a look at it and address last comments so that it can be merged? Many thanks!
