### ISSUE TITLE
Error 500 during installation - appParameters.php - Permission denied

### ISSUE THREAD

**Issue by lozaria** [PrestaShop/PrestaShop#10922]
Hello,

I'm getting error 500 on two different hosting companies (bluehost.com and superhosting.bg) when trying to install Prestashop 1.7.4.3 and 1.7.4.2

The error log is: [Mon Oct 08 13:11:48 2018] [warn-ioncube] mmap cache can't open /home/..../var/cache/prod/appParameters.php - Permission denied

I made 777 permissions on the whole store's files and folders..
I tried to use United States settings as well.

![image](https://user-images.githubusercontent.com/1417861/46636529-0d49b280-cb61-11e8-9184-cf051c329165.png)

**Comment by khouloudbelguith** [comment]
Hi @lozaria,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Before the installation, could you please enable the mode dev.
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:
define('_PS_MODE_DEV_', false);
… and change it to:
define('_PS_MODE_DEV_', true);
Thanks to check and feedback.

**Comment by lozaria** [comment]
Hi @khouloudbelguith, 
I'm trying new clean installation and the var/cache folder is empty.
I did enable the ps_mode_dev but I didn't see any errors on the installation screen.
Here is what I found in error_log inside /install folder:

[10-Oct-2018 00:48:43 Europe/Sofia] PHP Warning:  file_put_contents(/home/perdetat/profili/var/cache/dev/cacert.pem): failed to open stream: No such file or directory in /home/perdetat/profili/classes/Tools.php on line 1948
And the error in cPanel is still the same:
[Wed Oct 10 00:57:54 2018] [warn-ioncube] mmap cache can't open /home/perdetat/profili/var/cache/dev/appParameters.php - Permission denied (pid 42531)

**Comment by khouloudbelguith** [comment]
Hi @lozaria,

It is a permission issue.
Thanks to follow these steps:

1. Set up your database
2. Download Prestashop and extract
3. Upload Prestashop to your server using FTP
4. Change file permissions of all directories to 777 using your FTP software. In Filezilla, this is done by:
5. File permissions >777>tick box to do it for all subdirectories> choose directories only
6. Go to the website in a browser and follow instructions as normal
7. Delete the install folder
8. Rename ‘admin’ folder and record the new name

You can follow this link: https://www.youtube.com/watch?v=IOM9AffOa3s, check, and feedback.
Thanks to check & feedback.

**Comment by lozaria** [comment]
Hello,

I'm using Prestashop since version 1.3. I'm supporting dozen of stores for my customers. I know how to install it. 777 permission did not work when applied both to all PS files and folders. Also it is not good idea to use 777 permission at all.
I don't think that I need to rename install folder if the installation is failing. Did you see the screenshot attached to my first post? The installation fails at 12%.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @lozaria,

The PHP error means either the permissions are wrong on your PHP file or the user and/or group ownerships are wrong on the file.
Thanks to check the issue with your host & feedback

**Comment by lozaria** [comment]
Hi @khouloudbelguith, 

The same error occurs on two different providers. And all the permissions are set to 777. How it may be still a permissions issue? Permission of files, folders or what?

**Comment by khouloudbelguith** [comment]
Hi @lozaria,

It is a permission issue related to your server, it could be permission of your PHP file.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @lozaria,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
