### ISSUE TITLE
BO errors

### ISSUE THREAD

**Issue by fruitfreak** [PrestaShop/PrestaShop#10931]
Hi.
My BO is suddenly slow and these errors are showing everywhere in BO.

Error found : CData section not finished https://medias1.prestastore.com/ in country_module_list.xml file.
Error found : Premature end of data in tag img line 1 in country_module_list.xml file.
Error found : Premature end of data in tag module line 1 in country_module_list.xml file.
Error found : Premature end of data in tag modules line 1 in country_module_list.xml file.

**Additionnal information**
PrestaShop version: 1.6.1.19 - upgrade does not work... shows blank version info.
PHP version: 7.2.10  (also tried with other versions)

Appreciate any help :-)
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @fruitfreak,

Could you please try to clear cache from your shop & your browser.
Thanks to check & feedback.

**Comment by MaxL** [comment]
this is happening on all our prestashop shops too, versions from 1.6 and 1.7
i thinks it's related to prestashop.com being highly unresponsive and since there are so many requests to that domain this is slowing all backends down?

**Comment by fruitfreak** [comment]
Okay thanks for feedback! Seems better now. :-)

**Comment by khouloudbelguith** [comment]
@fruitfreak can I close the issue?

**Comment by fruitfreak** [comment]
Yes and thanks! .-)
the comment above is probably the reason for the 1-click-upgrade not to show anything.
Its working now and then. :-)

**Comment by TomHsiung** [comment]
1.7.5.1,

There are several errors.
Error found : CData section not finished Add a series of images to your homepage, with a sl in country_module_list.xml file.
Error found : Premature end of data in tag description_full line 1 in country_module_list.xml file.
Error found : Premature end of data in tag module line 1 in country_module_list.xml file.
Error found : Premature end of data in tag modules line 1 in country_module_list.xml file.

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

This is a cache issue.
Try to clear cache manually by deleting all the folder into var/cache (prod & dev).

Thanks!
