### ISSUE TITLE
Errors on backoffice in country_module_list.xml file

### ISSUE THREAD

**Issue by politith** [PrestaShop/PrestaShop#10935]
Hello,

Suddenly, I get these errors on backoffice:
 
Error found : CData section not finished https://addons.prestashop.com/product.php?id_produ in country_module_list.xml file.
Error found : Premature end of data in tag url line 1 in country_module_list.xml file.
Error found : Premature end of data in tag module line 1 in country_module_list.xml file.
Error found : Premature end of data in tag modules line 1 in country_module_list.xml file.

Additionally, the site and backoffice are loading forever till they open.

1. Go to backoffice
2. See error

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/42634459/46661035-15d1d580-cbc1-11e8-822f-7a79bc2b504a.png)

PrestaShop version: 1.7.3.2

I also talked to a friend who has 1.6 version and said that he sees the exact same error.

What is going on?

Thank you in advance,
Theodora

**Comment by khouloudbelguith** [comment]
Hi @politith,

You need to clear cache from your shop & your browser.
Thanks to check & feedback.

**Comment by MaxL** [comment]
this does not help for me at all - you already closed another issue, please don't close this one without actually resolving anything.
like i said in the previously closed issue, i strongly suspect this is related to requests to prestashop.com loading extremley slowly

**Comment by khouloudbelguith** [comment]
@MaxL, the other issue is closed by the user since it is fixed.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by politith** [comment]
Clearing Cache made the errors disappear but it's still loading extremely slowly as @MaxL said.

**Comment by MaxL** [comment]
right, can confirm @politith : the error disappears but loading times are unbearably slow. removing the prod and dev folders manually doesn't help either

**Comment by MathiasReker** [comment]
The problem is by Prestashop API. You can do this as a hotfix, while the issues is getting solved: https://github.com/PrestaShop/PrestaShop/commit/804272c2ec7ba2e5fc0dd836cad252fc1c396df3

To remove the errors you have to clear the cache.

**Comment by khouloudbelguith** [comment]
Hi,

We suggest you use this workaround to temporary disable API calls: http://bit.ly/2zIVejJ
The Addons API is currently having performance issues, and we are working to find a solution asap
Thanks!

**Comment by MahefaAbel** [comment]
@khouloudbelguith, i appreciate that you have propose this solution. but i have change the two modifs within http://bit.ly/2zIVejJ, then clear /var/cache/*, but i still have this error
Error found : CData section not finished Use this native module to:Establish a trust relati in country_module_list.xml file.

**Comment by matks** [comment]
> @khouloudbelguith, i appreciate that you have propose this solution. but i have change the two modifs within http://bit.ly/2zIVejJ, then clear /var/cache/*, but i still have this error
> Error found : CData section not finished Use this native module to:Establish a trust relati in country_module_list.xml file.

Did this error happen today ? This XML file is provided by Addons API. There might be a mistake in it, but we need to know the timeslot.

Also you could tell us what country you have your shop in ?

**Comment by HartLarsson** [comment]
today in all PrestaShop 1.7.6.9 country Italy ( generated on 17/02/2026 09:24:22)

we have these errors:

There are several errors.
1. Error found: StartTag: invalid element name in the file
**country_module_list.xml**.
2. Error found: StartTag: invalid element name in the file
**must_have_module_list.xml**.

both files are generated wrongly


content of: **must_have_modules_list.xml**

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="PrestaShop Marketplace is currently under maintenance. We'll be back soon!"
    />
    <title>Maintenance in Progress - PrestaShop Marketplace</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/favicon.ico"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=open_in_new"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/@prestashopcorp/puik-theme/dist/index.css"
    />
    <link
      rel="stylesheet"
      href="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/style.css"
    />
    <script
      src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/script.js"
    ></script>
  </head>

  <body>
    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <div class="logo-container">
          <!-- PrestaShop Logo SVG -->
          <img
            src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/ps_logo.svg"
            alt="PrestaShop"
            class="logo"
          />
        </div>
      </div>
      <hr class="header-divider" />
    </header>

    <!-- Main Content -->
    <main class="main">
      <div class="container">
        <div class="content">
          <!-- Title -->
          <h1 id="title" class="puik-brand-jumbotron">
            Maintenance in Progress
          </h1>

          <!-- Details -->
          <div class="details">
            <!-- Text Content -->
            <div class="text-content">
              <p id="message1" class="puik-body-large-bold">
                Hold tight! We're giving the PrestaShop Marketplace a quick
                refresh behind the scenes. We're working hard to get it running
                smoothly again.
              </p>
              <p id="message2" class="puik-body-large">
                Thank you for your patience.
              </p>
            </div>

            <!-- Illustration -->
            <div class="illustration-container">
              <img
                src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/maintenance.svg"
                alt="Maintenance illustration"
                class="illustration"
              />
            </div>

            <!-- Help Section -->
            <div class="help-section">
              <span id="helpText" class="puik-body-default"
                >Need assistance?</span
              >
              <a
                id="helpLink"
                href="https://help-center.prestashop.com/hc/en"
                class="help-link"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span id="helpLinkText">Visit our Help Center</span>
                <span class="material-symbols-outlined">open_in_new</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
```

Content of:  **default_country_modules_list.xml**

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="PrestaShop Marketplace is currently under maintenance. We'll be back soon!"
    />
    <title>Maintenance in Progress - PrestaShop Marketplace</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/favicon.ico"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=open_in_new"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/@prestashopcorp/puik-theme/dist/index.css"
    />
    <link
      rel="stylesheet"
      href="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/style.css"
    />
    <script
      src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/script.js"
    ></script>
  </head>

  <body>
    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <div class="logo-container">
          <!-- PrestaShop Logo SVG -->
          <img
            src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/ps_logo.svg"
            alt="PrestaShop"
            class="logo"
          />
        </div>
      </div>
      <hr class="header-divider" />
    </header>

    <!-- Main Content -->
    <main class="main">
      <div class="container">
        <div class="content">
          <!-- Title -->
          <h1 id="title" class="puik-brand-jumbotron">
            Maintenance in Progress
          </h1>

          <!-- Details -->
          <div class="details">
            <!-- Text Content -->
            <div class="text-content">
              <p id="message1" class="puik-body-large-bold">
                Hold tight! We're giving the PrestaShop Marketplace a quick
                refresh behind the scenes. We're working hard to get it running
                smoothly again.
              </p>
              <p id="message2" class="puik-body-large">
                Thank you for your patience.
              </p>
            </div>

            <!-- Illustration -->
            <div class="illustration-container">
              <img
                src="https://storage.googleapis.com/ps-eu-w1-addons-cdn-production/maintenance_page/maintenance.svg"
                alt="Maintenance illustration"
                class="illustration"
              />
            </div>

            <!-- Help Section -->
            <div class="help-section">
              <span id="helpText" class="puik-body-default"
                >Need assistance?</span
              >
              <a
                id="helpLink"
                href="https://help-center.prestashop.com/hc/en"
                class="help-link"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span id="helpLinkText">Visit our Help Center</span>
                <span class="material-symbols-outlined">open_in_new</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
```

**Comment by sokin100** [comment]
I have the same issue

**Comment by alejandroriosclearis** [comment]
I don't think it's the best solution, but if you need to access the BO urgently, you can modify the files that are failing and enter:

`<?xml version="1.0" encoding="UTF-8"?>
<modules></modules>`

**Comment by Alderas11** [comment]
I get the same issue here with 1.7.6.7 in one site (other site works fine right now....)
clearing the cache server Side and browser side : ko (not better)

continuing to get he :
Il y a plusieurs erreurs.
Erreur : StartTag: invalid element name dans le fichier country_module_list.xml.
Erreur : Extra content at the end of the document dans le fichier country_module_list.xml.
Erreur : StartTag: invalid element name dans le fichier must_have_module_list.xml.
Erreur : Extra content at the end of the document dans le fichier must_have_module_list.xml.

**Comment by LeonPupier** [comment]
I have the same issue on my Prestashop website now

**Comment by TobW5** [comment]
Hello, i have the same issue i have a prestashop 1.7.6.1

**Comment by alejandroriosclearis** [comment]
> I don't think it's the best solution, but if you need to access the BO urgently, you can modify the files that are failing and enter:
> 
> `<?xml version="1.0" encoding="UTF-8"?> <modules></modules>`

Are you try this?

**Comment by Nivelz** [comment]
Hello, same here, in two different prestashop

Error encontrado: StartTag: invalid element name en archivo country_module_list.xml.
Error encontrado: Extra content at the end of the document en archivo country_module_list.xml.
Error encontrado: StartTag: invalid element name en el archivo must_have_module_list.xml.
Error encontrado: Extra content at the end of the document en el archivo must_have_module_list.xml.

First xml doesnt exist and second exist with different name ( ...have_modules_...)

Tried deleting them all and cleaning cache and nothing

**Comment by LeonPupier** [comment]
I fixed the issue, Prestashop is under maintenance and the content fetched from the PS servers are HTML maintenance webpage.

To fix that, remove the xml files who have issues on your website and replace them with an empty valid xml file. And don't clear the cache after that

**Comment by Nivelz** [comment]
> I fixed the issue, Prestashop is under maintenance and the content fetched from the PS servers are HTML maintenance webpage.
> 
> To fix that, remove the xml files who have issues on your website and replace them with an empty valid xml file. And don't clear the cache after that

I created them both empty, and it still gives same error

<img width="1138" height="101" alt="Image" src="https://github.com/user-attachments/assets/51558cc9-ec89-4692-92a6-74e00de87f05" />

<img width="703" height="256" alt="Image" src="https://github.com/user-attachments/assets/ed214043-5c34-41db-a55a-b004809c0885" />

**Comment by LeonPupier** [comment]
Test with my files

[default_country_modules_list.xml](https://github.com/user-attachments/files/25362664/default_country_modules_list.xml)
[modules_native_addons.xml](https://github.com/user-attachments/files/25362663/modules_native_addons.xml)
[must_have_modules_list.xml](https://github.com/user-attachments/files/25362662/must_have_modules_list.xml)

**Comment by Nivelz** [comment]
> Test with my files
> 
> [default_country_modules_list.xml](https://github.com/user-attachments/files/25362664/default_country_modules_list.xml) [modules_native_addons.xml](https://github.com/user-attachments/files/25362663/modules_native_addons.xml) [must_have_modules_list.xml](https://github.com/user-attachments/files/25362662/must_have_modules_list.xml)

You are a life saver, it worked in one of the websites, will try in the others, THANKS!

**Comment by LeonPupier** [comment]
Haha with pleasure mate !

**Comment by D0MSdC** [comment]
> Test with my files
> 
> [default_country_modules_list.xml](https://github.com/user-attachments/files/25362664/default_country_modules_list.xml) [modules_native_addons.xml](https://github.com/user-attachments/files/25362663/modules_native_addons.xml) [must_have_modules_list.xml](https://github.com/user-attachments/files/25362662/must_have_modules_list.xml)

Merci beaucoup @LeonPupier , cela fonctionne très bien !!!!

**Comment by crishnakh** [comment]
This solve my problem:

>> Go to config > xml and rename de xml files with error.

**Comment by Rasq123** [comment]
> Test with my files
> 
> [default_country_modules_list.xml](https://github.com/user-attachments/files/25362664/default_country_modules_list.xml) [modules_native_addons.xml](https://github.com/user-attachments/files/25362663/modules_native_addons.xml) [must_have_modules_list.xml](https://github.com/user-attachments/files/25362662/must_have_modules_list.xml)

Thank you. You saved me

**Comment by shtan73** [comment]
Problem XML
Jeżeli w sklepie od strony panelu administracyjnego zaplecza pojawią się pojedyncze komunikaty (lub jeden komunikat) typu:

Error found : Extra content at the end of the document in country_module_list.xml file
Error found : Sequence ']]>' not allowed in content in country_module_list.xml file
Error found : internal error: detected an error in element content in country_module_list.xml file
Error found : Extra content at the end of the document in country_module_list.xml file
Error found : Premature end of data in tag badge line 1 in must_have_module_list.xml file
Error found : StartTag: invalid element name in country_module_list.[xml](https://prestaeticaret.com/) file
Error found : Extra content at the end of the document in country_module_list.xml file
Error found : StartTag: invalid element name in must_have_module_list.xml file
Error found : Extra content at the end of the document in must_have_module_list.xml file
Error found : Premature end of data in tag badges line 1 in must_have_module_list.xml file
Error found : Premature end of data in tag module line 1 in must_have_module_list.xml file
Error found : Premature end of data in tag modules line 1 in must_have_module_list.xml file


Spowodowane one są tym że Prestashop łączy się z Addonami każdego dnia, aby odzyskać kilka plików, w tym ten pliki typu  xml np: default_country_modules_list.xml. Jeśli połączenie zostanie przerwane z dowolnego powodu x lub y, plik może zostać załadowany niekompletnie, wtedy następuje błąd podczas próby odczytu o otrzymujemy komunikat o błędzie od strony zaplecza panelu administracyjnego sklepu.

Rozwiązanie problemu to zalogowanie się na FTP w katalogu / config / xml i usunąć plik  xml powodujący błąd czyli default_country_modules_list.xml , zostanie on ponownie pobrany w następnej kolejności.

UWAGA: przed kasowaniem zalecamy wykonanie kopii pliku i ciągnięcie z FTP

Po wykasowaniu czyścimy ceche sklepu Zaawansowane - Wydajność - Wyczyść pamięć podręczną

oraz ręcznie przed FTP cache / smarty / compile kasując wszystkie katalogi jakie się tu znajdują


jeżeli powyższa solucja nie pomoże edytujemy plik w katalogu classes / tools.php

kod

protected static $is_addons_up = true;     
public static function addonsRequest($request, $params = array())     
{         return false;         
if (!self::$is_addons_up) { 
            return false;
zmieniamy na


protected static $is_addons_up = false;     
public static function addonsRequest($request, $params = array())     
{         return false;         
if (!self::$is_addons_up) { 
            return false;
ponownie kasujemy pliki tymczasowe ceche i przeładowujemy przeglądarkę
