### ISSUE TITLE
Problème de paramétrage module PayGreen avec 1&1 Internet

### ISSUE THREAD

**Issue by Stan82085** [PrestaShop/PrestaShop#10932]
Bonjour,

Je vous contact car j'ai un hébergement chez 1&1 avec prestashop et j'ai un souci avec un module PayGreen. 
Le module ne veut pas se configurer et me dis toujours qu'il est a configurer.

J'ai essayer avec un autre hébergeur web et le module fonctionne correctement. 

J'ai aussi désinstallée et réinstaller le site prestashop et le module PayGreen et c'est toujours pareil.

J'ai déjà contacter le support 1&1 Internet et me dise de me rediriger vers vous me disant que le problème ne viens pas d'eux mais du module.

Cependant le module PayGreen qui est installer sur mon autre site Prestashop qui lui est sur un autre Hébergement Web fonctionne.

Je suis donc a me poser la question si c'est bien le module qui a un souci ou 1&1 Internet qui ne fonctionne pas.

Je vous signale également que Prestashop et le module PayGreen dispose sont a jours tout les 2.

Merci de me répondre très rapidement car je paye un Hébergement que je ne peut pas me servir.

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version : v1.7.4.2
PHP version : PHP 7.2
--

**Comment by khouloudbelguith** [comment]
Hi @Stan82085,

This is a public space.
You need to remove the credentials of your shop
Let's be safe!

Thanks & best regards, Khouloud

**Comment by Stan82085** [comment]
Bonjour,

Modification effectuer

**Comment by khouloudbelguith** [comment]
@Stan82085,

The PayGreen module is provided by Watt Is It.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

Best regards, Khouloud
