### ISSUE TITLE
Bug Persist Entity AttributeGroupLang : Bad Association Annotation

### ISSUE THREAD

**Issue by Fabuloops** [PrestaShop/PrestaShop#10937]
**Describe the bug**
When i tried to persist `PrestaShopBundle\Entity\AttributeGroupLang` entity, i had this exception 
```
Catchable Fatal Error: Object of class PrestaShopBundle\Entity\Lang could not be converted to string

```

**To Reproduce**
```
$attributeGroupLang = new AttributeGroupLang();
$attributeGroupLang->setName("Group Test");
$attributeGroupLang->setPublicName("Group Test Public Name");
$attributeGroupLang->setLang($lang);
$attributeGroupLang->setAttributeGroup($attributeGroup);

$em->persist($attributeGroupLang);
```

**Resolve this issue**
I resolved this issue by remove one line on the $lang attribute annotation in the AttributeGroupLang Entity

Before
```
    /**
     * @ORM\Id
     * @ORM\Column(name="id_lang", type="integer")
     * @ORM\ManyToOne(targetEntity="PrestaShopBundle\Entity\Lang")
     * @ORM\JoinColumn(name="id_lang", referencedColumnName="id_lang", nullable=false, onDelete="CASCADE")
     */
    private $lang;
```
After 
```
    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="PrestaShopBundle\Entity\Lang")
     * @ORM\JoinColumn(name="id_lang", referencedColumnName="id_lang", nullable=false, onDelete="CASCADE")
     */
    private $lang;
```

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: 7.1.13

**Comment by khouloudbelguith** [comment]
Hi @Fabuloops,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Fabuloops** [comment]
Hi @khouloudbelguith,

Sorry, i'm too much busy for the moment. Maybe later

I have to follow this tutorial right ?
https://devdocs.prestashop.com/1.7/contribute/contribute_using_docker/

**Comment by dineshbadrukhiya** [comment]
Hello @Fabuloops 
 You can follow the steps as mentioned here, [https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTING.md](url)
