### ISSUE TITLE
Api Prestashop 

### ISSUE THREAD

**Issue by taffe-elec** [PrestaShop/PrestaShop#10947]
Hello,

since 2 weeks, we have issues with our prestashop website : https://www.taffe-elec.com
Periodically, our website stop loading properly. The website tries to load, dosoen't succeed and we have 500 page error. The backoffice is also unreachable during this problem.
According to our developper, it's an issue coming from the api of prestashop. It's a big problem for us and a lack of profit.
Could you help us ? 

Best regards,
Taffe-elec
You can contact us on this phone number : 09 52 71 13 94

**Comment by khouloudbelguith** [comment]
Hi @taffe-elec,

We are aware of this issue.
we are working to find a solution asap, thanks to follow this link: https://twitter.com/PrestaShop
We suggest you use this workaround to temporary disable API calls: http://bit.ly/2zIVejJ
Thanks!
