### ISSUE TITLE
Many filemtime(): stat failed warnings in errors log

### ISSUE THREAD

**Issue by yardstudio** [PrestaShop/PrestaShop#10940]
**Describe the bug**
I have PrestaShop on https://autoair.sk site. I have enabled error.csv log creation according this: 
https://zemez.io/prestashop/support/how-to/prestashop-1-5-x-1-6-x-how-to-enable-error-reporting-debug-mode/
In this file I have too many warnings of "filemtime(): stat failed"... for example:

`"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blocksocial/blocksocial.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blocksocial/blocksocial.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockcms/blockcms.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockcms/blockcms.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockcontactinfos/blockcontactinfos.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockcontactinfos/blockcontactinfos.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockmyaccount/blockmyaccount.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockmyaccount/blockmyaccount.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockstore/blockstore.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockstore/blockstore.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/homefeatured/css/homefeatured.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/themeconfigurator/css/hooks.css"
"09 Oct 2018 14:44:04","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/themeconfigurator/hooks.css"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/js/modules/ganalytics/views/js/GoogleAnalyticActionLib.js"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/js/modules/ganalytics/views/GoogleAnalyticActionLib.js"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/notarobot/views/css/front.css"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/notarobot/views/front.css"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/Media.php: 
550","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/cache/v_64_2f00236bf47016af2449e7ef5b22a5b1_all.css"
"09 Oct 2018 14:44:05","/***/*****/domain_sk/classes/Media.php: 
722","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/cache/v_71_59db9724b38139a68f3bf4c40cf9e04b.js"
"09 Oct 2018 14:44:06","/***/*****/domain_sk/tools/smarty/sysplugins/smarty_resource.php: 
772","(Warning) filemtime(): stat failed for /***/*****/domain_sk/cache/smarty/compile/9e/ef/03/9eef034114acf551830416798d76592657c1fc57.file.cms.tpl.php"
"09 Oct 2018 14:44:06","/***/*****/domain_sk/tools/smarty/sysplugins/smarty_resource.php: 
772","(Warning) filemtime(): stat failed for /***/*****/domain_sk/cache/smarty/compile/a1/67/54/a16754870f3f42c307ec288d74a92eb1e58cfd33.file.breadcrumb.tpl.php"
"09 Oct 2018 15:10:36","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:11:42","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:12:01","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:12:55","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:16:14","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:23:07","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/grid_prestashop.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blocksocial/blocksocial.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blocksocial/blocksocial.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockfacebook/css/blockfacebook.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockfacebook/blockfacebook.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/js/modules/blockfacebook/blockfacebook.js"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockcms/blockcms.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockcms/blockcms.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockcontactinfos/blockcontactinfos.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockcontactinfos/blockcontactinfos.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockmyaccount/blockmyaccount.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockmyaccount/blockmyaccount.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/blockstore/blockstore.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/Media.php: 
289","(Warning) filemtime(): stat failed for /***/*****/domain_sk/modules/blockstore/blockstore.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/homefeatured/css/homefeatured.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/themeconfigurator/css/hooks.css"
"09 Oct 2018 15:23:08","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/themeconfigurator/hooks.css"
"09 Oct 2018 15:23:09","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/js/modules/ganalytics/views/js/GoogleAnalyticActionLib.js"
"09 Oct 2018 15:23:09","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/js/modules/ganalytics/views/GoogleAnalyticActionLib.js"
"09 Oct 2018 15:23:09","/***/*****/domain_sk/classes/controller/FrontController.php: 
1307","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/notarobot/views/css/front.css"
"09 Oct 2018 15:23:09","/***/*****/domain_sk/classes/controller/FrontController.php: 
1309","(Warning) filemtime(): stat failed for /***/*****/domain_sk/themes/default-bootstrap/css/modules/notarobot/views/front.css"
"09 Oct 2018 15:23:10","/***/*****/domain_sk/tools/smarty/sysplugins/smarty_internal_cacheresource_file.php: 
64","(Warning) filemtime(): stat failed for /***/*****/domain_sk/cache/smarty/cache/blockspecials/20181009/14/20181009/1/1/37/5d/d7/69/5dd76986db1efac2e05a01f280709e00f174b900.blockspecials.tpl.php"
"09 Oct 2018 15:23:10","/***/*****/domain_sk/tools/smarty/sysplugins/smarty_internal_cacheresource_file.php: 
64","(Warning) filemtime(): stat failed for /***/*****/domain_sk/cache/smarty/cache/blocktags/1/1/37/0a/d1/7b/0ad17b24eb74cc5e869c5bdfaa6a062b292da518.blocktags.tpl.php"
` 

**To Reproduce**
This warnings are only in background and are not visible on page

**Screenshots**
N/A

**Additionnal information**
PrestaShop version: 1.6.1.16
PHP version: 7.02

**Comment by khouloudbelguith** [comment]
Hi @yardstudio,

Did you installed any custom module before this issue occurs?
Could you please try to disable the notarobot module, check & feedback.
Thanks!

**Comment by yardstudio** [comment]
Hello @khouloudbelguith 

I have no idea, because error logging I have enabled only yet.

What do you mean as 
> notarobot
 ?

**Comment by khouloudbelguith** [comment]
@yardstudio, in the log that you attached.
You have this error
![image](https://user-images.githubusercontent.com/16067358/46723054-352b3a00-cc77-11e8-92dd-72c181ea2d63.png)
There are some issues with some modules, you need to disable one by one to catch the cause error.
Thanks!

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
