### ISSUE TITLE
Problem setting up Google Analytics API

### ISSUE THREAD

**Issue by Falataya** [PrestaShop/PrestaShop#10945]
I have the Google Analytics module and I'm trying to establish a connection with Google Analytics API v1.3. It requires I enter Email, password and my Google Analytics Profile ID. I am very sure I entered all the required information correctly but authentication always fails. What can I do?

Prestashop 1.6.1.1
Tried with Chrome and Firefox.

**Comment by khouloudbelguith** [comment]
Hi @Falataya,

Please be aware the Google Analytics API module will only work if you either:

- have installed and configured the “Google Analytics” module
- or have already embedded the Google Analytics script into your shop."

Thanks to check & feedback.

**Comment by Falataya** [comment]
Hi!
I'm sorry I missed that. However, I have now installed and successfully configured Google Analytics module but authentication still fails.
What else have I missed?

**Comment by khouloudbelguith** [comment]
Hi @Falataya,

Thanks for your feedback.
I manage to reproduce the issue with the last version 1.6.1.21 & the gapi module v1.2.2
![image](https://user-images.githubusercontent.com/16067358/46733329-446ab180-cc90-11e8-8a23-3cbc7b678f2b.png)
@marionf what do you think?
Thanks!

**Comment by Falataya** [comment]
I have also checked the google analytichs platform and now I can see data in real time - so that part is working.

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
