### ISSUE TITLE
Backoffice fails to fetch data from prestashop.com resulting in timeouts

### ISSUE THREAD

**Issue by Jodelautomat** [PrestaShop/PrestaShop#10941]
**Describe the bug**
Issue  reproduceable on 1.7.4.2, backoffice-page fails to load or takes several minutes to load. already happend 2-3 weeks ago.

1. Go to Backoffice/index.php
2. enter credentials and hit login
3. Backoffice-Page ist trying to fetch data from gamification.prestashop.com but fails or takes minutes
4. Backoffice Dashboard-Page runs into timeout or loads after several minutes
5. every single backoffice-page runs into timeout  or takes server minutes for loading
6. makes it impossible to work with the backofice

**Screenshots**
![image](https://user-images.githubusercontent.com/31407559/46686390-729cb280-cbf8-11e8-92df-a515e99934f9.png)

**Comment by khouloudbelguith** [comment]
Hi @Jodelautomat,

We are aware of this issue.
gamification.prestashop.com took too long to respond.
For a quick fix, you need to break gamification by renaming module and speed will be back, rename module to gamification_off.
That is really bad, but you need to apply it.
We will fix it as soon as possible.
Thanks!

**Comment by marionf** [comment]
Hello @Jodelautomat 
It's fixed now, thank for your report
