### ISSUE TITLE
Voucher are not applied "You can not use this voucher"

### ISSUE THREAD

**Issue by CArlvJ1N0N8** [PrestaShop/PrestaShop#10953]
**Describe the bug**
A promotion code is created for every customer to get a 10 % discount when using code "first10". 
Although when applying this code it says "You can not use this voucher".

**To Reproduce**
1. Go to front store
2. Click on product to add to cart
3. Create your new account
4. Proceed to checkout
5. At checkout page, apply code in coupon box "first10"
6. Press apply and see error message appearing. 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![you can not use this voucher](https://user-images.githubusercontent.com/42921237/46735904-9a762f80-cc65-11e8-9212-f7da8eba9cbe.JPG)
**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0.27-0+deb9u1

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Thanks to check the "Total available" & "Total available for each user" of this cart rule & feedback.

**Comment by CArlvJ1N0N8** [comment]
Yes sure, i forgot to paste this picture! 

![available](https://user-images.githubusercontent.com/42921237/46739693-23de2f80-cc6f-11e8-9f07-20dbf3bc1079.JPG)

**Comment by khouloudbelguith** [comment]
@CArlvJ1N0N8, I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record
https://drive.google.com/file/d/1hLIP56XvDTqCX-mIB7boW3iFnbr8ypT_/view
Thanks to check & feedback.

**Comment by CArlvJ1N0N8** [comment]
Ok, but it is the same issue on our Dev site. 

So would it be a conflict between different modules if we don't get the vouchers have the same behaviours as yours? 

You can do the same test on https://dev.easy-pharma.ca

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Could you please try to re-create another voucher, thanks to provide a screen record about it, check & feedback.
Thanks!

**Comment by CArlvJ1N0N8** [comment]
Hello, 

I recreated the 2nd10 as a new voucher, 
but same result. 

![2nd10 doesn t work](https://user-images.githubusercontent.com/42921237/46797482-49c20d80-cd1d-11e8-9463-4d4505094b01.JPG)
![2nd10 scr1](https://user-images.githubusercontent.com/42921237/46797483-49c20d80-cd1d-11e8-9846-a24fc5fd48df.JPG)
![2nd10 scr2](https://user-images.githubusercontent.com/42921237/46797484-4a5aa400-cd1d-11e8-9ed0-d4e1845f983a.JPG)
![2nd10 scr3](https://user-images.githubusercontent.com/42921237/46797486-4a5aa400-cd1d-11e8-9ae4-dbda9c316646.JPG)

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by CArlvJ1N0N8** [comment]
![first10 with default theme in dev site not working](https://user-images.githubusercontent.com/42921237/46801188-f2756a80-cd27-11e8-90bb-1a515b3bea4f.JPG)

**Comment by CArlvJ1N0N8** [comment]
"server setup and configuration"  Debian9 Ngixn + php-fpm Php7
#PHP error logs# nothing
#nginx  error log# 2018/10/11 06:36:34 [error] 19383#19383: *30460 open() "/home/live/web/easy-pharma.ca/public_html/cdn-cgi/scripts/d07b1474/cloudflare-static/email-decode.min.js" failed (2: No such file or directory), client: 142.44.160.129, server: www.easy-pharma.ca, request: "GET /cdn-cgi/scripts/d07b1474/cloudflare-static/email-decode.min.js HTTP/1.1", host: "www.easy-pharma.ca", referrer: "https://www.easy-pharma.ca/fr/module/wtblog/post?id_wt_blog_post=3&amp;;;;amp;;;;;;;;;amp;category_parent=1-are-you-subject-to"

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Your issue is related to the theme or custom module, when I enabled the mode debug, I found 3 bugs
1- 
![image](https://user-images.githubusercontent.com/16067358/46808481-bca6a500-cd6c-11e8-9119-8abae01a1dbd.png)
2-
![image](https://user-images.githubusercontent.com/16067358/46808499-cb8d5780-cd6c-11e8-8d70-39e88ba7b08e.png)
3- I tried to disable the SmartBlog Home Latest News  module & the TD - Sub Banner Block => in the cart page, I have this error
![image](https://user-images.githubusercontent.com/16067358/46808595-02fc0400-cd6d-11e8-83c6-572aa7e8f7ed.png)

You need to disable the custom modules one by one, check & feedback.

**Comment by CArlvJ1N0N8** [comment]
Hello, 

It seems we have the same issue with the default prestashop theme. 
Can you test it on your side? 

Thanks, 

Carl

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

I attached a video record.
https://drive.google.com/file/d/1sdgJHDBQp8a_sgKPloT8hUBGlfJMsonZ/view
Thanks to check & feedback.

**Comment by CArlvJ1N0N8** [comment]
Hello, 

Please close this issue since it is now working again. 

But i don't what has been changed....

Thanks,

**Comment by PierreRambaud** [comment]
Thanks @CArlvJ1N0N8 for your feedbacks. Feel free to open a new issue if you need :)
