### ISSUE TITLE
[PrestaShopDatabaseException] Unknown column 'id_shop' in 'where clause'

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#10951]
With debug mode enabled, front office displays an error:
[PrestaShopDatabaseException]
Unknown column 'id_shop' in 'where clause'

![prestashopdatabaseexception](https://user-images.githubusercontent.com/31688689/46732874-fd2ff100-cc8e-11e8-8d12-c56062c6f552.jpg)

non PrestaShop modules disabled
All overrides disabled
Debug mode enabled
Cache cleared
All CCC disabled

**To Reproduce**
See the above BO settings

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.41

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks to disable the ps_customtext module, clear cache, check & feedback.
Thanks!

**Comment by mrabsinthe** [comment]
I can confirm that the error is gone with ps_customtext module disabled and also with the latest version of ps_customtext module enabled. Thank you!
