### ISSUE TITLE
HTML editor shown in foreign characters

### ISSUE THREAD

**Issue by Falataya** [PrestaShop/PrestaShop#10952]
My HTML editor in Prestashop always shows in foreign characters that I am not able to read. Where can I change that?

![image](https://user-images.githubusercontent.com/10939572/46735381-60715180-cc96-11e8-89d0-bfb0110a230f.png)

PrestaShop version: 1.6.1.1.

**Comment by khouloudbelguith** [comment]
Hi @Falataya,

Unfortunately, we can't reproduce this. Is it on all pages or just this one? Which page this it?
Can you please try to update your translations? 
Localization > Translations > Add / Update a language, select your language and click on "Add / Update a language".
Thanks to check & feedback.

**Comment by Falataya** [comment]
Hi!
This is a product description page but it happens on all backoffice pages that include a HTML editor.

I updated my language but it didn't help.

Any other ideas what I can do?

**Comment by khouloudbelguith** [comment]
@Falataya, There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-10057
It wasn't necessary to create a new one.
So, this one can be closed
Thanks!

**Comment by khouloudbelguith** [comment]
We don't support 1.6 anymore, I will remove the Duplicate Label
