### ISSUE TITLE
The PrestaShop Image Slider is not updating image and text

### ISSUE THREAD

**Issue by oldipp** [PrestaShop/PrestaShop#10958]
**Describe the bug**
If i go to Modules >> Modules & Services >> Image Slider >> Configure... I can't add/edit my slides or new slides. If i add it I click on save, my store will not update. What's happening or what should I do?

**Comment by khouloudbelguith** [comment]
Hi @oldipp,

I did not manage to reproduce the issue with PS 1.7.4.3 & the ps_imageslider v3.0.0 - by PrestaShop.
I attached a video record.
https://drive.google.com/file/d/18Zkl-4Ih-SJ3aYBm1lnigXirtwmlO0SW/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @oldipp,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by Devcitaw** [comment]
Hi, I'm having the same issue. I'm using Prestashop 1.7.6.4 and I can see the changes in the BO but not in the site. Not even changin just the description text, picture order or link.
I've tried cleaning cache both of my explorer and prestashop, uninstalling and reinstalling the module, and nothing is helping me fix this issue.

**Comment by khouloudbelguith** [comment]
Hi @Kimcitaw,

I did not manage to reproduce the issue with PS1.7.6.4 and `ps_imageslider` v3.0.0.
https://drive.google.com/file/d/1CkORu9hfvOXUBgn7PSCkMW8YgbpDGutO/view?usp=sharing
This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
