### ISSUE TITLE
Error back office and front office

### ISSUE THREAD

**Issue by Marg88** [PrestaShop/PrestaShop#10961]
Prestashop version 1.7

Since this morning I can't access to my back office and my front office. 
On the first one this error appear like you can see in attachment : PrestaShopException
On the second one that you can see in attachement too the message is : 500 Server Error
I don't understand because I didn't change anything this morning on my website, I just added some products. 
Can you help me ?

Best regards,

Marg88

![capture d ecran 2018-10-11 a 10 22 08](https://user-images.githubusercontent.com/42941368/46785000-65d7a600-cd41-11e8-9ba2-37ce84980e68.png)

![capture d ecran 2018-10-11 a 10 22 22](https://user-images.githubusercontent.com/42941368/46785001-6708d300-cd41-11e8-9582-9da5d3cd1bd8.png)

**Comment by MathiasReker** [comment]
This looks like an error from your hosting. Try to send the same message to your hosting.

**Comment by khouloudbelguith** [comment]
Hi @Marg88,

The problem comes from your web host. You must check your `PrivateSql` instance and everything around.
Try to connect to your mysql server in command line if you can :)
Thanks!

**Comment by Marg88** [comment]
Hi,

Thanks for answers. I joined my web host but he said me that is a Prestashop problem because everything is okay on my hosting and my problem isn't solve.
Can you help me please ?

Thanks,

Marg88

**Comment by Marg88** [comment]
My problem is solve.

Thanks

**Comment by khouloudbelguith** [comment]
HI @Marg88,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
