### ISSUE TITLE
[PrestaShopException]

### ISSUE THREAD

**Issue by belpixel** [PrestaShop/PrestaShop#10963]
**Describe the bug**
Hi dears, I'm a new one in Prestashop and yesterday evening I  tried to upgrade my prestashop 1.6.1.20 to 1.7.4.3 after upgrade my prestashop wasn't visible and  I tried to  Rollback 1.6.1.20 but I recived these error and I haven't access to BO!
--

**To Reproduce**
1. Go to 'http://printpress.be/1/admin674w9kicy'
2. Cli
![screenshot001](https://user-images.githubusercontent.com/35133541/46792228-2f9b2600-cd43-11e8-87ff-9dcc6552a25a.jpg)
ck on '....'
4. See error:
[PrestaShopException]

No access reference in table module_access for id_module 121.
at line 2538 in file classes/module/Module.php

2533.                 self::$cache_permissions[$employee->id_profile][$row['id_module']]['uninstall'] = $row['uninstall'];
2534.             }
2535.         }
2536. 
2537.         if (!isset(self::$cache_permissions[$employee->id_profile][$id_module])) {
2538.             throw new PrestaShopException('No access reference in table module_access for id_module '.$id_module.'.');
2539.         }
2540. 
2541.         return (bool)self::$cache_permissions[$employee->id_profile][$id_module][$variable];
2542.     }
2543. 

    ModuleCore::getPermissionStatic - [line 3283 - classes/controller/AdminController.php] - [2 Arguments]
    AdminControllerCore->getModulesList - [line 2329 - classes/controller/AdminController.php] - [1 Arguments]
    AdminControllerCore->renderModulesList - [line 2063 - classes/controller/AdminController.php]
    AdminControllerCore->initContent - [line 136 - controllers/admin/AdminLoginController.php]
    AdminLoginControllerCore->initContent - [line 189 - classes/controller/Controller.php]
    ControllerCore->run - [line 367 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 58 - admin/index.php]

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @belpixel,

Thanks for your report.
Could you please check your Database `ps_module` table, search for the module with `id_module= 103`.
![image](https://user-images.githubusercontent.com/16067358/46793235-8144b000-cd45-11e8-80d2-8668d5adb11d.png)
After that, you need to break this module by renaming it, clear cache, check & feedback.
Thanks!

**Comment by belpixel** [comment]
![screenshot001](https://user-images.githubusercontent.com/35133541/46793838-e5b43f00-cd46-11e8-8315-8eb6c04010d1.jpg)
Hi,
Intro ps_module I've these list! which one is?

**Comment by khouloudbelguith** [comment]
@belpixel, this only the first page, you need to show all & search for this module.
![image](https://user-images.githubusercontent.com/16067358/46794425-0cbf4080-cd48-11e8-82d1-868d3d066922.png)
Thanks!

**Comment by belpixel** [comment]
![screenshot001](https://user-images.githubusercontent.com/35133541/46795163-c4088700-cd49-11e8-8f94-8b95dda049c9.jpg)
I found it. Now what can I do?

**Comment by khouloudbelguith** [comment]
Hi @belpixel,

You need to rename this module to `upgrade_off`, you can find the `upgrade` folder in your ProjectFolder/modules/
Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @belpixel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
