### ISSUE TITLE
Replace deprecated library PhpExcel by PhpSpreadsheet

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10962]
**Is your feature request related to a problem? Please describe.**

Library `phpoffice/phpexcel` is used in PrestaShop Core: https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json#L38

According to its [github repository README](https://github.com/PHPOffice/PHPExcel/blob/1.8/README.md) the library is deprecated since 2015. Using it now in 2018 is not efficient and could even introduce security flaws.

**Describe the solution you'd like**
The github repository README indicates that https://github.com/PHPOffice/PhpSpreadsheet should be used instead. So solution is to replace `PhpExcel` by `PhpSpreadsheet`.

**Comment by SharakPL** [comment]
Actually it was updated last time in 2015. It's been depreciated since December 2017 (release of first stable version of PhpSpreadsheet). Nevertheless it should replaced asap.
