### ISSUE TITLE
Hi, I can not log in into my Prestashop 1.6.9. back office.

### ISSUE THREAD

**Issue by Trsta89** [PrestaShop/PrestaShop#10960]
Hi, I can not log in into my Prestashop 1.6.9. back office..it's just loading and loading but never opens the site..
But I can log in back office at dev.mode...
Please help me. Is there also any other way to put my shop into maintenance mode..because i dont want to have my shop open for people to buy products when i can not acces my back office to handle the orders.

**Comment by TuKo** [comment]
Have you checked Issue #10941 ?

**Comment by Trsta89** [comment]
I did and it works!
Thx a lot

**Comment by khouloudbelguith** [comment]
Duplicate of #10941
