### ISSUE TITLE
Multishop : wrong tax applied to OrderSlip when Employee is not currently on the same context as the order

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/PrestaShop#10966]
**Describe the bug**
With a multistore instanceof prestashop,
When you want to generate an order slip using partial or standard refund (on One order page view), and you are on the context where the order was done, no tax is applied to the Order Slip if the product is not shared.
This seems due to the absence of passing the context from the order instead of the current context;
to the differents calculators.
as we can see on : 
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderSlip.php#L333
refering product function :
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5648

**To Reproduce**
1. First deploy a Multistore Prestashop , whith non-shared products
2. On front office place an order , ordering a non-shared-product
3. On Back office, go to the order , using another shop context than the order one
4. Try to generate an OrderSlip
5. No tax is applied

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.6 & current 1.7
PHP version: any version concerned.

**Comment by 123monsite-regis** [comment]
Maybe restrincting the order BO page to the Context the order was billied will be quicker than trying  to  solve such points ?

**Comment by khouloudbelguith** [comment]
Hi @123monsite-regis,

Thanks for your report.
Isn't the same issue described above: https://github.com/PrestaShop/PrestaShop/issues/9609#issuecomment-415048712 ?
Thanks to check & feedback.

**Comment by 123monsite-regis** [comment]
not exactly the same, but linked
 this is an other consequence of Employee who edit Orders on Multistore context or not at exactly the order Shop context.

best regards

**Comment by khouloudbelguith** [comment]
@123monsite-regis could you please provide a screenshot about your issue.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @123monsite-regis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
