### ISSUE TITLE
User image not visble in Prestashop 1.6.1.22

### ISSUE THREAD

**Issue by jameswill** [PrestaShop/PrestaShop#10965]
I have installed Prestashop 1.6.1.22 on my linux server with PHP 5.4, Mysql 5.5, and Apache 2.2. When I login into admin panel, On top right corner I didn't get user image and also just below that in "tips of the day" section another image is not loading.

1. Login into admin panel
2. Check top right corner for user image
3. Also just below user image, another image is not loading.

![prestashop](https://user-images.githubusercontent.com/6368036/46796776-14441100-cd6b-11e8-8f14-2d78c5e05346.png)

**Additionnal information**
PrestaShop version: 1.6.1.22
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @jameswill,

- Could you please navigate to BO => Preferences => Images page in the section "REGENERATE THUMBNAILS" click on the button "Regenerate thumbnails".
- Regenerate your file .htaccess ( the BO => Preferences => SEO & URLs => thanks to disable "Friendly URL" and enable it" to regenerate .htaccess)

Thanks to check & feedback.

**Comment by jameswill** [comment]
Thank you for the quick reply.

I tried Regenerating thumbnails however I did not find "BO => Shop Parameters =>Traffic & SEO=> SEO & URLs => thanks to disable "Friendly URL" and enable it" to regenerate .htaccess.

Can you please guide where it is ?

**Comment by khouloudbelguith** [comment]
@jameswill, sorry.
You need to navigate to the BO => Preferences => SEO & URLs => thanks to disable "Friendly URL" and enable it" to regenerate .htaccess.

**Comment by jameswill** [comment]
There is no option for "thanks to disable "Friendly URL" and enable it" to regenerate .htaccess" in my BO => Preferences => SEO & URLs 
There is an option to "Generate robots.txt" file and my friendly url is disables by default

**Comment by khouloudbelguith** [comment]
@jameswill,

I attached screenshots:
![image](https://user-images.githubusercontent.com/16067358/46798903-8a3c7e00-cd53-11e8-8909-dfd8d4cf3cab.png)
![image](https://user-images.githubusercontent.com/16067358/46798867-6ed17300-cd53-11e8-80f7-f7af05abce48.png)

**Comment by jameswill** [comment]
Mine is disabled

![screenshot-127 0 0 1-2018 10 11-16-17-10](https://user-images.githubusercontent.com/6368036/46798973-232dc200-cd71-11e8-9e09-de1a10bd3bb8.png)

**Comment by khouloudbelguith** [comment]
@jameswill, OK thanks.
after Regenerating thumbnails, the issue still exists?

**Comment by jameswill** [comment]
Yes. Post regenerating thumbnails. user image still not loading

**Comment by khouloudbelguith** [comment]
@jameswill, Thanks for your feedback.
@marionf, checked with 1.6.1.22 / 1.7.4.3 => When I'm trying to change my profile picture.
Clicking on this [link](http://www.prestashop.com/forums/index.php?app=core&module=usercp), I'm redirected to page not found
![image](https://user-images.githubusercontent.com/16067358/46800306-8f033100-cd57-11e8-96d6-671ff83106e7.png)
What do you think?

**Comment by jameswill** [comment]
Hi,

Should I wait for the next release ?

**Comment by PrestaEdit** [comment]
Theses part are loaded with the PrestaShop API. 
As you know, there is some issues with it from now.

I think it's not an issue, it's a tempory problem due to this incident.

**Comment by marionf** [comment]
I think it's more a page that doesn't exist anymore on prestashop.com

**Comment by marionf** [comment]
I can't reproduce with 1.7.6.0

![capture d'écran_1610](https://user-images.githubusercontent.com/13449658/58469770-73129b00-8140-11e9-9b05-38770d853964.png)
