### ISSUE TITLE
I do not access the BO (504 error)

### ISSUE THREAD

**Issue by TonystarAGB** [PrestaShop/PrestaShop#10971]
A couple of days the back office of my site has slowed down a lot, but today when I try to log in I do not have access right after so many minutes that I load, I'm left with the error 504.
I'm reading that many have this problem. Can you help me? I urgently need to access my dashboard

PrestaShop version: 1.6.1.17

**Comment by a-led** [comment]
I confirm I'm experiencing same problem on 3 different installations of 1.6.1.20 on 3 different servers. At first time admin panel became very slow, after I receive an error with file xml and at list I can't no more access admin panel. Enter button round in infinite loop.

**Comment by khouloudbelguith** [comment]
Hi @TonystarAGB,

Could you please rename the `gamification` folder to `gamification_off`, you can find it into the path Project_Folder/modules/
Thanks to check & feedback.

**Comment by TonystarAGB** [comment]
Thanks, it works properly now

**Comment by khouloudbelguith** [comment]
@TonystarAGB, I close the issue, feel free to open a new one when needed.
