### ISSUE TITLE
AdminPaymentPreferences

### ISSUE THREAD

**Issue by cgascard** [PrestaShop/PrestaShop#10972]
Describe the bug

To Reproduce

Go to 'my back-office'
Click on 'Payment and "preferences " '

See error:
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: PDO::query(): MySQL server has gone away

  at classes/db/DbPDO.php:148
  at DbPDOCore->_query('SELECT c.id_currencyFROM `ps_currency` cWHERE (deleted = 0) AND (iso_code = \'EUR\') LIMIT 1')
     (classes/db/Db.php:369)
  at DbCore->query('SELECT c.id_currencyFROM `ps_currency` cWHERE (deleted = 0) AND (iso_code = \'EUR\') LIMIT 1')
     (classes/db/Db.php:645)
  at DbCore->getRow('SELECT c.id_currencyFROM `ps_currency` cWHERE (deleted = 0) AND (iso_code = \'EUR\') LIMIT 1', true)
     (classes/db/Db.php:678)
  at DbCore->getValue('SELECT c.id_currencyFROM `ps_currency` cWHERE (deleted = 0) AND (iso_code = \'EUR\')')
     (classes/Currency.php:479)
  at CurrencyCore::getIdByIsoCode('EUR')
     (classes/module/Module.php:1466)
  at ModuleCore::getModulesOnDisk(true)
     (controllers/admin/AdminPaymentPreferencesController.php:41)
  at AdminPaymentPreferencesControllerCore->__construct(false, false)
     (classes/controller/Controller.php:190)
  at ControllerCore::getController('AdminPaymentPreferencesController')
     (classes/Dispatcher.php:420)
  at DispatcherCore->dispatch()
     (admin636lgxiq1/index.php:99)

Environment : 
Multi-shop (2)
Differents customers Groups for shop 1 et 2

PrestaShop version: 1.7.4.2
PHP version: 7.0.31
I use for modules payment : bank transfer

Thanks for your help!

**Comment by khouloudbelguith** [comment]
Hi @cgascard,

Did you import any package from the International /Localization page?
Or did you created any Currency?
Thanks!

**Comment by cgascard** [comment]
Hi, 

No, no import or currency creation, but these data comes from version 1.4 with the migration module.

1 Currency : EUR
2 Language : FR and EN

**Comment by khouloudbelguith** [comment]
@cgascard, Did make an upgrade of your shop from PS 1.4 to 1.7?
What is the exact tool did you use to do this upgrade?

**Comment by cgascard** [comment]
Tool : I used https://addons.prestashop.com/fr/migration-donnees-sauvegarde/8934-migrationpro-de-migration-prestashop-vers-prestashop.html

PS 1.4 to clean install 1.7.3  
then 1.7.4 with 1C click upgrade

I just added a new currency USD (no active) in the 2 shops and I access to payment preferences, but the loading is very long.

**Comment by khouloudbelguith** [comment]
Hi @cgascard,

Could you please try to re-import the France package & the united state's package in the International /Localization page, check & feedback.
Thanks!

**Comment by cgascard** [comment]
It's ok now !
Thanks for you help.

**Comment by khouloudbelguith** [comment]
Hi @cgascard,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
