### ISSUE TITLE
Attachments duplicated on all products

### ISSUE THREAD

**Issue by RRENOU** [PrestaShop/PrestaShop#10976]
**Describe the bug**
When a file is attached to a product through Webservice or Admin page, the attached file appears also on other products.

**To Reproduce**
1. Go to 'Catalog > products'
2. Open first product page
2. Click on 'Option'
3. Scroll down to 'Attachments'
4. Add a file as attachment
6. Go to next product page then Options tab
7. Scroll down to Attachements
8. You see the previously attached file on other product

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.8

**Comment by khouloudbelguith** [comment]
Hi @RRENOU,

Thanks for your report.
This is a normal behavior.
Each product can have files, which can be individually set in the "Options" tab, under "Attached files". That page gives you access t`o all the attached files of the shop`: if you need to apply the associated one file with this products, you need to check it.
When you go to next product page then Options tab => you scroll down to Attachments => yes you will see the previously attached file on other product, but it is not checked, this file, in fact, it is added in the files list ( you can find it in the BO => Catalog => Files)
![image](https://user-images.githubusercontent.com/16067358/46856558-0f349f80-ce07-11e8-8312-cee0ef5e50c1.png)
I close the issue, feel free to open a new one when needed.
