### ISSUE TITLE
Minimal quantity in quick view

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10984]
**Describe the bug**
I shouldn't be able to decrease the quantity under minimal quantity in quick view

**To Reproduce**
1. Go to Catalog product & edit a product
2. Click on Quantity and enter a minimal quantity > 1
3. Go to FO and click on quick view for this product
4. You can decrease the quantity under the minimal quantity defined

**Screenshots**

![capture d ecran_403](https://user-images.githubusercontent.com/13449658/46860421-b4a04100-ce10-11e8-9a69-3bdd4024d1d1.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/PrestaShop/pull/11055
