### ISSUE TITLE
Bad display on BO product page 

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10983]
**Describe the bug**
Bad display on BO product page 

**To Reproduce**
1. Go to Catalog > Products
2. Edit a product
3. Click on an image

**Screenshots**

![capture d ecran_400](https://user-images.githubusercontent.com/13449658/46859055-ffb85500-ce0c-11e8-8616-0d769c9d1126.png)

Before

![capture d ecran_401](https://user-images.githubusercontent.com/13449658/46859060-03e47280-ce0d-11e8-8af1-0ba467be814b.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed by #11032
