### ISSUE TITLE
Error as I insert password for one customer.

### ISSUE THREAD

**Issue by lucagiai** [PrestaShop/PrestaShop#10985]
Hello,

when I login with data of a client it gives error. PS: 1.6.1.18

To check error please go on www.amrita-edizioni.com, 
user: eugeen72@gmail.com
psw: amrita

Here's the error I get: 
[PrestaShopDatabaseException]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) ORDER BY `level_depth` ASC, cs.`position` ASC' at line 11

			SELECT c.id_parent, c.id_category, cl.name
			FROM `ps_category` c
			INNER JOIN `ps_category_lang` cl ON (c.`id_category` = cl.`id_category` AND cl.`id_lang` = 6 AND cl.id_shop = 1 )
			INNER JOIN `ps_category_shop` cs ON (cs.`id_category` = c.`id_category` AND cs.`id_shop` = 1)
			WHERE (c.`active` = 1 AND c.`id_category` = 6 OR c.`id_category` = 421 OR c.`id_category` = 422 OR c.`id_category` = 435 OR c.`id_category` = 419 OR c.`id_category` = 420 OR c.`id_category` = 423 OR c.`id_category` = 424 OR c.`id_category` = 546 OR c.`id_category` = 447 )
			AND c.`id_category` != 1
			 AND `level_depth` <= 3
			AND c.id_category IN (
				SELECT id_category
				FROM `ps_category_group`
				WHERE `id_group` IN ()
			)
			ORDER BY `level_depth` ASC, cs.`position` ASC

at line 791 in file classes/db/Db.php

786.         if ($webservice_call && $errno) {
787.             $dbg = debug_backtrace();
788.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] '.$this->getMsgError().'. From '.(isset($dbg[3]['class']) ? $dbg[3]['class'] : '').'->'.$dbg[3]['function'].'() Query was : '.$sql, 97);
789.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
790.             if ($sql) {
791.                 throw new PrestaShopDatabaseException($this->getMsgError().'<br /><br /><pre>'.$sql.'</pre>');
792.             }
793. 
794.             throw new PrestaShopDatabaseException($this->getMsgError());
795.         }
796.     }

    DbCore->displayError - [line 425 - classes/db/Db.php] - [1 Arguments]
    DbCore->query - [line 643 - classes/db/Db.php] - [1 Arguments]
    DbCore->executeS - [line 205 - modules/blocksearch_mod/blocksearch_mod.php] - [1 Arguments]
    BlockSearch_mod->calculHookCommon - [line 148 - modules/blocksearch_mod/blocksearch_mod.php] - [1 Arguments]
    BlockSearch_mod->hookTop - [line 591 - classes/Hook.php] - [1 Arguments]
    HookCore::coreCallHook - [line 548 - classes/Hook.php] - [3 Arguments]
    HookCore::exec - [line 580 - classes/controller/FrontController.php] - [1 Arguments]
    FrontControllerCore->initContent - [line 37 - controllers/front/IndexController.php]
    IndexControllerCore->initContent - [line 189 - classes/controller/Controller.php]
    ControllerCore->run - [line 367 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 28 - index.php]

**Comment by khouloudbelguith** [comment]
Hi @lucagiai,

Could you please try to disable the blocksearch_mod module, clear cache, check & feedback.
Thanks!

**Comment by lucagiai** [comment]
Hello khouloudbelguith, thanks for answering so quickly! :-)

I just tried to disable blocksearch_mod as suggested, I still get an error, but different. Here it is:

[PrestaShopDatabaseException]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY c.`id_category` ORDER BY c.`level_depth` ASC , category' at line 10

				SELECT c.*, cl.*
				FROM `ps_category` c
				 INNER JOIN ps_category_shop category_shop
		ON (category_shop.id_category = c.id_category AND category_shop.id_shop = 1)
				LEFT JOIN `ps_category_lang` cl ON c.`id_category` = cl.`id_category` AND cl.id_shop = 1 
				LEFT JOIN `ps_category_group` cg ON c.`id_category` = cg.`id_category`
				RIGHT JOIN `ps_category` c2 ON c2.`id_category` = 6 AND c.`nleft` >= c2.`nleft` AND c.`nright` <= c2.`nright`
				WHERE 1  AND `id_lang` = 6
				 AND c.`active` = 1
				 AND cg.`id_group` IN ()
				 GROUP BY c.`id_category`
				 ORDER BY c.`level_depth` ASC
				, category_shop.`position` ASC
				


at line 791 in file classes/db/Db.php

786.         if ($webservice_call && $errno) {
787.             $dbg = debug_backtrace();
788.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] '.$this->getMsgError().'. From '.(isset($dbg[3]['class']) ? $dbg[3]['class'] : '').'->'.$dbg[3]['function'].'() Query was : '.$sql, 97);
789.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
790.             if ($sql) {
791.                 throw new PrestaShopDatabaseException($this->getMsgError().'<br /><br /><pre>'.$sql.'</pre>');
792.             }
793. 
794.             throw new PrestaShopDatabaseException($this->getMsgError());
795.         }
796.     }

    DbCore->displayError - [line 425 - classes/db/Db.php] - [1 Arguments]
    DbCore->query - [line 643 - classes/db/Db.php] - [1 Arguments]
    DbCore->executeS - [line 585 - classes/Category.php] - [1 Arguments]
    CategoryCore::getNestedCategories - [line 5249 - modules/iqitmegamenu/iqitmegamenu.php] - [7 Arguments]
    IqitMegaMenu->makeMenuMobile - [line 4458 - modules/iqitmegamenu/iqitmegamenu.php]
    IqitMegaMenu->_prepareHook - [line 4401 - modules/iqitmegamenu/iqitmegamenu.php] - [1 Arguments]
    IqitMegaMenu->hookmaxHeader - [line 591 - classes/Hook.php] - [1 Arguments]
    HookCore::coreCallHook - [line 546 - classes/Hook.php] - [3 Arguments]
    HookCore::exec - [line 207 - config/smarty.config.inc.php] - [3 Arguments]
    smartyHook - [line - ] - [2 Arguments]
    call_user_func_array - [line 270 - config/smarty.config.inc.php] - [2 Arguments]
    SmartyLazyRegister->__call - [line 381 - cache/smarty/compile/46/ab/f6/46abf65595886dd7760859f33c169f5742a28e7d.file.header.tpl.php] - [2 Arguments]
    SmartyLazyRegister->smartyHook - [line 381 - cache/smarty/compile/46/ab/f6/46abf65595886dd7760859f33c169f5742a28e7d.file.header.tpl.php] - [2 Arguments]
    content_5bb47ae4f02083_83914930 - [line 188 - tools/smarty/sysplugins/smarty_internal_templatebase.php] - [1 Arguments]
    Smarty_Internal_TemplateBase->fetch - [line 317 - classes/SmartyCustom.php] - [7 Arguments]
    Smarty_Custom_Template->fetch - [line 303 - tools/smarty/sysplugins/smarty_internal_template.php] - [7 Arguments]
    Smarty_Internal_Template->getSubTemplate - [line 38 - cache/smarty/compile/92/a6/2a/92a62a5aee0f0d5a8a1c59ff8045d5c1834f6553.file.layout.tpl.php] - [7 Arguments]
    content_5bb47ae4c033a3_32925332 - [line 188 - tools/smarty/sysplugins/smarty_internal_templatebase.php] - [1 Arguments]
    Smarty_Internal_TemplateBase->fetch - [line 110 - classes/SmartyCustom.php] - [7 Arguments]
    SmartyCustomCore->fetch - [line 529 - classes/controller/Controller.php] - [1 Arguments]
    ControllerCore->smartyOutputContent - [line 723 - classes/controller/FrontController.php] - [1 Arguments]
    FrontControllerCore->display - [line 209 - classes/controller/Controller.php]
    ControllerCore->run - [line 367 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 28 - index.php]

**Comment by khouloudbelguith** [comment]
@lucagiai, you need to disable the iqitmegamenu module.
Thanks to check & feedback.

**Comment by lucagiai** [comment]
Nothing... here's the error:

[PrestaShopDatabaseException]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) ORDER BY `level_depth` ASC, cs.`position` ASC' at line 11

			SELECT c.id_parent, c.id_category, cl.name
			FROM `ps_category` c
			INNER JOIN `ps_category_lang` cl ON (c.`id_category` = cl.`id_category` AND cl.`id_lang` = 6 AND cl.id_shop = 1 )
			INNER JOIN `ps_category_shop` cs ON (cs.`id_category` = c.`id_category` AND cs.`id_shop` = 1)
			WHERE (c.`active` = 1 AND c.`id_category` = 6 OR c.`id_category` = 421 OR c.`id_category` = 422 OR c.`id_category` = 435 OR c.`id_category` = 419 OR c.`id_category` = 420 OR c.`id_category` = 423 OR c.`id_category` = 424 OR c.`id_category` = 546 OR c.`id_category` = 447 )
			AND c.`id_category` != 1
			 AND `level_depth` <= 3
			AND c.id_category IN (
				SELECT id_category
				FROM `ps_category_group`
				WHERE `id_group` IN ()
			)
			ORDER BY `level_depth` ASC, cs.`position` ASC


at line 791 in file classes/db/Db.php

786.         if ($webservice_call && $errno) {
787.             $dbg = debug_backtrace();
788.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] '.$this->getMsgError().'. From '.(isset($dbg[3]['class']) ? $dbg[3]['class'] : '').'->'.$dbg[3]['function'].'() Query was : '.$sql, 97);
789.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
790.             if ($sql) {
791.                 throw new PrestaShopDatabaseException($this->getMsgError().'<br /><br /><pre>'.$sql.'</pre>');
792.             }
793. 
794.             throw new PrestaShopDatabaseException($this->getMsgError());
795.         }
796.     }

    DbCore->displayError - [line 425 - classes/db/Db.php] - [1 Arguments]
    DbCore->query - [line 643 - classes/db/Db.php] - [1 Arguments]
    DbCore->executeS - [line 205 - modules/blocksearch_mod/blocksearch_mod.php] - [1 Arguments]
    BlockSearch_mod->calculHookCommon - [line 148 - modules/blocksearch_mod/blocksearch_mod.php] - [1 Arguments]
    BlockSearch_mod->hookTop - [line 591 - classes/Hook.php] - [1 Arguments]
    HookCore::coreCallHook - [line 548 - classes/Hook.php] - [3 Arguments]
    HookCore::exec - [line 580 - classes/controller/FrontController.php] - [1 Arguments]
    FrontControllerCore->initContent - [line 37 - controllers/front/IndexController.php]
    IndexControllerCore->initContent - [line 189 - classes/controller/Controller.php]
    ControllerCore->run - [line 367 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 28 - index.php]

**Comment by khouloudbelguith** [comment]
Hi @lucagiai,

You need to disable the blocksearch_mod module.
Thanks to check & feedback.

**Comment by lucagiai** [comment]
You mean both together, both disabled and check? Because I already tried to disable blocksearch_mod and it gave the error I reported previously. Thank you!

**Comment by khouloudbelguith** [comment]
@lucagiai, yes, you need to disable both, check & feedback.

**Comment by lucagiai** [comment]
@khouloudbelguith Thank you, it worked! If I disable both modules, the error is no longer there. So we know where's the issue, what can I do to solve it?

**Comment by khouloudbelguith** [comment]
Hi @lucagiai,

As they are not modules provided by Prestashop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
