### ISSUE TITLE
searchbar is not working (anymore)

### ISSUE THREAD

**Issue by Prestashopnewbie** [PrestaShop/PrestaShop#10997]
**Describe the bug**
After a instal of the community module "prosearch" link to topic: https://www.prestashop.com/forums/topic/381135-free-module-ajax-live-search-for-prestashop/

Our search is not working at all ... In backoffice the search tool tells there are no products indexed, when I check dbase, I see all the products are indexed, but not corretly (wrong link to product). I would love to know wich files are affected & how I can setup search in the original state of working again. 

**Additionnal information**
PrestaShop version: 1.7.2.4
PHP version: 7.2

**Comment by Prestashopnewbie** [comment]
Closed ... Issue is the same as: 
[BOOM-4600] Can not search product combinations with Availability date #9775

**Comment by khouloudbelguith** [comment]
Duplicate of #9775
