### ISSUE TITLE
SQL Manager - Sorting by SQL query causes an exception

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10990]
**Describe the bug**

In the BO => Database / SQL Manager page, when we try to filter by SQL query => an exception occured

**To Reproduce**
1. Go to BO => Database / SQL Manager page
2. Create at least 2 SQL Query
3. After that, try to apply a sort on SQL Query with icon
![image](https://user-images.githubusercontent.com/16067358/46876788-86862580-ce3f-11e8-94fe-1056f406cc65.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/46873867-fee8e880-ce37-11e8-89a7-67a515c8f352.png)
https://drive.google.com/file/d/1dSqKBISsiUZCFcwGS7bSE5FvlTvg4xNx/view

**Additionnal information**
PrestaShop version: 1.7.4.3 / 1.7.5.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Here's the PR: #10991 to fix the issue.

**Comment by marionf** [comment]
@khouloudbelguith 

I can't reproduce the issue

![capture d ecran_436](https://user-images.githubusercontent.com/13449658/46876524-dca69900-ce3e-11e8-84e8-33e38081f706.png)

**Comment by khouloudbelguith** [comment]
@marion, this issue occurs when we use the icon to sort
![image](https://user-images.githubusercontent.com/16067358/46876692-458e1100-ce3f-11e8-941f-2de06c0307fe.png)
