### ISSUE TITLE
Recover cart when no customer data

### ISSUE THREAD

**Issue by drpark** [PrestaShop/PrestaShop#10996]
hi,

concerning an old issue (on your previous issue system) BOOM-6147

"If you manually produce a recover cart URL, the link only works if the customer object is set. I can't see why it has to be set for cart recovery to work."

I did this via webservice to try, but it's the same direct in code

Context::getContext()->link->getPageLink('order', false, (int)$cart->id_lang, 'step=3&recover_cart='.(int)$cart->id.'&token_cart='.md5(_COOKIE_KEY_.'recover_cart_'.(int)$cart->id)), 

**Additionnal information**
PrestaShop version: 1.7

Regards

**Comment by khouloudbelguith** [comment]
Hi @drpark,

So, If you manually produce a recover cart URL where if the customer object is not set, you are redirected to an empty shopping cart page without error notification?
Thanks!

**Comment by drpark** [comment]
@khouloudbelguith exactly if no customer object , the redirection produce an empty cart without any error notification (it works perfectly if customer object is set)
regards

**Comment by khouloudbelguith** [comment]
@drpark, ok thanks!
@marionf what do you think of this improvement?
I manage to reproduce the issue.
When I manually produce a recover cart URL where if the customer object is not set, I'm redirected to an empty shopping cart page without error notification.
![sc](https://user-images.githubusercontent.com/16067358/46944287-f11ea780-d071-11e8-895c-179385388a27.png)
Thanks!

**Comment by drpark** [comment]
@khouloudbelguith i don't think it's an improvement, it works in previous versions according to my customer.
regards

**Comment by khouloudbelguith** [comment]
@drpark, what is the exact previous version?

**Comment by drpark** [comment]
i would say 1.6.1.4 but i don't believe it was working...can't test...

**Comment by khouloudbelguith** [comment]
@drpark same issue with 1.6.1.22.
![image](https://user-images.githubusercontent.com/16067358/46946461-14e4ec00-d078-11e8-8527-4ffc1a017610.png)

**Comment by drpark** [comment]
ok! customer dream ;-) but really need this feature.  thank you.

**Comment by colinegin** [comment]
@eternoendless @PrestaShop/prestashop-core-developers what do you think of this idea ? 
Would it be easy to fix it ?

**Comment by kpodemski** [comment]
It is fixed already. The error will now show that cart cannot be recovered.

Fix: https://github.com/PrestaShop/PrestaShop/pull/30075
