### ISSUE TITLE
PS 1.7.4.3 voucher used disapeared from customer order detail (AdminOrders)

### ISSUE THREAD

**Issue by mygitaccount2** [PrestaShop/PrestaShop#11001]
Hi everyone.

since update 1.7.4.3  when a customer use a voucher/cart rule , we cant see anymore in the customer order detail if a voucher has been used.
i tested with free gift voucher

1.7.4.2  we can see like here ![2018-10-13_0846](https://user-images.githubusercontent.com/38796611/46905639-b4fa1400-cec4-11e8-9b5e-9f6e06aa2722.png)

1.7.4.3 well nothing to see  so no screenshot

also the query  SELECT * FROM `ps_order_cart_rule`   do not show voucher used anymore, 
so im guessing the table disapeard or got renamed ?

So im not sure if its a bug or if the feature got removed ?
there is nothing in changelog.

This feature is very usefull, with the last version we just can see if a voucher has been used.

**Comment by mygitaccount2** [comment]
OK i found the issue,

i was offering a FREE GIFT valued at 0$ in my catalog that will trigger the "bug"

**Comment by khouloudbelguith** [comment]
Hi @mygitaccount2,

Thanks for your report & your feedback.
I close the issue, feel free to open a new one when needed.
