### ISSUE TITLE
Error with importing products Error code: error

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#11014]
I'm constantly getting Error code: error when importing products. It always manages to import exactly 5 products no matter what I set in php.ini
Tried xlsx and csv format, tried to import without image urls, tried to change from FCGId to CGI wrapper. Server is running PHP 7.0.27
Prestashop ver. 1.7.4.2
Prestashop log is not showing much info.
Chrome is showing error in this:
https://www.poppersbymail.com/admin292mqbbbp/index.php?ajax=1&action=import&tab=AdminImport&offset=0&limit=5&token=06334aa839fc81942492269e57a49260

It returns this header:
HTTP/1.1 500 Internal Server Error
Date: Mon, 15 Oct 2018 15:14:28 GMT
Server: Apache/2.4.6
X-Powered-By: PHP/7.0.27
Cache-Control: max-age=0, must-revalidate, private
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

Screenshots attached.

Thanks!

[test.xlsx](https://github.com/PrestaShop/PrestaShop/files/2479387/test.xlsx)
![error with import](https://user-images.githubusercontent.com/43558067/46960768-85533380-d09f-11e8-919a-a77a8c77b440.JPG)
![error with import2](https://user-images.githubusercontent.com/43558067/46960772-871cf700-d09f-11e8-87e7-74948c971de2.JPG)
![error with import3](https://user-images.githubusercontent.com/43558067/46960774-884e2400-d09f-11e8-95c5-e3536a9275eb.JPG)
![error with import4](https://user-images.githubusercontent.com/43558067/46960776-8a17e780-d09f-11e8-8fd5-366113875a14.JPG)

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

Have you the same issue with this ticket: #10329?
Thanks to check & feedback.

**Comment by kodarco** [comment]
No I don't have problem with the reference field, mine is very short.

**Comment by khouloudbelguith** [comment]
@kodarco, could you please provide the file.csv to test it.

**Comment by kodarco** [comment]
Can't attach csv file here, it's the same as xlsx

**Comment by khouloudbelguith** [comment]
@kodarco, you can provide me with the field by email.
My address mail: khouloud.belguith@prestashop.com

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

I just received your file test.csv.
for each line, I added the id(the first column is empty in the file that you provided me.
After that, I imported the file & it is ok for me.
I attached a video record.
https://drive.google.com/file/d/1HpQtQkD8-ozlF20CS_CimqqH9w0ndu9B/view
Thanks to check & feedback.

**Comment by kodarco** [comment]
No, when I add product IDs I still have the error. I imports 5 products and then shows the error.
In Chrome inpect, I see this link is showing error 500

https://www.poppersbymail.com/admin292mqbbbp/index.php?ajax=1&action=import&tab=AdminImport&offset=0&limit=5&token=06334aa839fc81942492269e57a49260

Isn't it strange that in this link, it says limit=5 and it always imports 5 products, could this be a problem?

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by kodarco** [comment]
Already gave you all this, see above...

**Comment by khouloudbelguith** [comment]
@kodarco, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
If you enable the mode debug, is there any exception displayed?

**Comment by kodarco** [comment]
This is all I can collect, except for the above images. When I turn on debug mode, I got error 500 in Chrome console on https://www.poppersbymail.com/admin292mqbbbp/index.php?ajax=1&action=import&tab=AdminImport&offset=0&limit=5&token=06334aa839fc81942492269e57a49260 

and these are the images of the response

![1](https://user-images.githubusercontent.com/43558067/47012446-8d18e380-d144-11e8-8c6f-ad61a2e3c135.JPG)
![2](https://user-images.githubusercontent.com/43558067/47012452-8ee2a700-d144-11e8-9fd3-38e519084f10.JPG)
![3](https://user-images.githubusercontent.com/43558067/47012457-90ac6a80-d144-11e8-8678-8cd492bf6098.JPG)
![4](https://user-images.githubusercontent.com/43558067/47012465-930ec480-d144-11e8-9e30-0b45e1783037.JPG)







OTHER LOGS:


[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/2482667/error_log.txt)



[prod.log](https://github.com/PrestaShop/PrestaShop/files/2482658/prod.log)
[dev.log](https://github.com/PrestaShop/PrestaShop/files/2482659/dev.log)

**Comment by khouloudbelguith** [comment]
@kodarco, during the import of the products, the tags column is empty in your case?
![image](https://user-images.githubusercontent.com/16067358/47019747-12f25a00-d158-11e8-9872-59e6ba69c14a.png)
Thanks!

**Comment by kodarco** [comment]
Just tried with populated tags, I get the exact same error.

**Comment by khouloudbelguith** [comment]
@kodarco, What are those exact tags?
Thanks!

**Comment by kodarco** [comment]
just one word for all rows: adult

**Comment by khouloudbelguith** [comment]
@kodarco, if you ignore this column during the import, is there any exception?

**Comment by kodarco** [comment]
Tried to ignore tag column, got exactly the same exception: updateTagCount

**Comment by khouloudbelguith** [comment]
@kodarco, it could be Block tags module causes this issue.
Could you please try to disable it, clear cache, check & feedback.
Thanks!

**Comment by kodarco** [comment]
No luck, got the same exception

**Comment by khouloudbelguith** [comment]
@kodarco, have you any others module related to the Tag?
Because in my local I did not manage to reproduce any issue with the file that provided to me.

**Comment by kodarco** [comment]
Ok, I've cloned the website to a subdirectory so I can disable stuff. First I changed theme to default, then I disabled all modules - all modules manually one by one, I also disabled all overrides. And no luck, I'm getting exactly the same error.
I can give you credentials to this test site so you can see for yourself.

We also have problem with secure key I don't know if it's related, I'm working with the developer of the migration module for weeks to resolve this. We've migrated from 1.6 to 1.7 using that migration module but some customers are experiencing the Fatal Error when they try to checkout (any payment method, any shipping) In logs I see this error: PaymentModule::validateOrder - Secure key does not match
This only affects a number of customers but we don't know which ones. So far, the solution that worked is to change customer's email (adding a letter or something) and immediately change the email back. This probably re-creates the secure key. I don't know if this is related or not.

Thanks for you time, you are very kind!

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by kodarco** [comment]
The developer of the migration module (https://addons.prestashop.com/en/data-migration-backup/32298-prestashop-migrator-safely-upgrade-prestashop-to-17.html) has checked and said that it doesn't have anything to do with the migration. How come it imports 5 products just fine and always exactly 5 products? If it's something wrong with the database it wouldn't import products at all.

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by kodarco** [comment]
After a months of troubleshooting, we finally traced this issue back to the template. Templates adds unnecessary file Tag.php to override/classes/ 
This file should be removed according to the developer of the theme posthemes. The theme is called Juvento. This solves the problem.

**Comment by khouloudbelguith** [comment]
@kodarco, thanks for your feedback.
I'm glad that you solve your issue.
Thanks!

**Comment by RainManCZE** [comment]
I had the same issue but it had nothing to do with a template. 
I have solved it by increasing max_size in php.ini on server, it appears import died on too big images.

Worked like a charm.
