### ISSUE TITLE
When Data format change, in BO orders details fail

### ISSUE THREAD

**Issue by JirkaDeLucina** [PrestaShop/PrestaShop#11017]
I use only one language: czech (cs-CZ).

When is changed short "Data format" in BO: International - Localization - Languages from default format "Y-m-d" to another, eg.: d.m.Y, than in BO in Orders in detail in any Order appears:

[PrestaShopException]
Invalid date
at line 883 in file classes/Tools.php

878.         if ($date == '0000-00-00 00:00:00' || $date == '0000-00-00') {
879.             return '';
880.         }
881. 
882.         if (!Validate::isDate($date) || !Validate::isBool($full)) {
883.             throw new PrestaShopException('Invalid date');
884.         }
885. 
886.         $context = Context::getContext();
887.         $date_format = ($full ? $context->language->date_format_full : $context->language->date_format_lite);
888.         return date($date_format, $time);

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @JirkaDeLucina,

I did not manage to reproduce the issue with the last version 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1fkz1CgJPbFzubD1KG_Bn0dJpf1le-sG0/view
Thanks to check & feedback.

**Comment by JirkaDeLucina** [comment]
Hi,
please look here on my video screen capture, there is the bug:
https://www.useloom.com/share/0ec3a56828964f72a927a16f4ae9d8a9

Thank you very much.

**Comment by khouloudbelguith** [comment]
Hi @JirkaDeLucina,

Thanks to disable the `dpcz` module, clear cache, check & feedback.
Thanks!

**Comment by JirkaDeLucina** [comment]
Hi,
thank you, you are right, proplem is in the module dpcz. Thank you very much.
JB

**Comment by khouloudbelguith** [comment]
Hi @JirkaDeLucina,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
