### ISSUE TITLE
JavaScript error in console when editing an image in TinyMCE - BO CMS Page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11011]
**Describe the bug**
issue JS when editing a CMS page with an image in the wysiwyg

**To Reproduce**

1. Go to Design > Pages
1. Edit a CMS page
1. Add an image in the wysiwyg editor & save
1. Edit the CMS page and click on the image in the wysiwyg editor
1. See error, you can't edit the image

**Screenshots**
![capture d ecran!UNITO-UNDERSCORE!437](https://user-images.githubusercontent.com/13449658/46951102-46b17f00-d087-11e8-9354-54da5ae0d6bf.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: N/A

**Comment by PierreRambaud** [comment]
It's a TinyMce bug. @eternoendless What we can do for that?

**Comment by matks** [comment]
@marionf I just checked in the migrated page and it seems to be gone (although I think it should be unrelated 😆)
So for me it's a "Cant reproduce" now

Can you check ?

**Comment by marionf** [comment]
@matks I can reproduce it with 1.7.6.x branch

![capture d'écran_1684](https://user-images.githubusercontent.com/13449658/59521152-e26fe500-8ecb-11e9-9f1f-fa621a9dfcdd.png)

**Comment by matks** [comment]
Interesting 🤔I tried with Firefox and Chrome, nothing.
Do you use the "upload an image" window, like this ?
<img width="505" alt="Capture d’écran 2019-06-14 à 17 46 48" src="https://user-images.githubusercontent.com/3830050/59521444-94a7ac80-8ecc-11e9-8d06-e47471604fbe.png">

**Comment by matks** [comment]
Also I see you have multiple languages installed, when I tried with only one. Might come from that

**Comment by marionf** [comment]
I have the same issue with only one language

https://drive.google.com/open?id=1ymPge3H4eFa-aM2IVnwGcl_a_REEbvKi

**Comment by matks** [comment]
> I have the same issue with only one language
> 
> https://drive.google.com/open?id=1ymPge3H4eFa-aM2IVnwGcl_a_REEbvKi

Thanks for the video, I understand now. I did not understand what was meant by "See error, you can't edit the image".

As Pierre said, this is an issue from TinyMCE. It seems to be fixed in TinyMCE 4.6 while we are using a modified 4.0.16 version.

@marionf I suggest we update the title of the issue as this happens in EVERY page where we use TinyMCE, including the Product page.

@PrestaShop/prestashop-core-developers  Would an update of tinyMCE to 4.6 be considered a BC break ? If yes, what about we use TinyMCE 4.6 in migrated pages ? Since the migration uses new Twig templates instead of smarty templates, we already make a BC break here. So we would use this opportunity and use an up-to-date tinyMCE version.

**Comment by simulbeni** [comment]
Is there any solution for this issue. Its coming in google chrome only and now a days 70% people using google chrome.

I see in prestashop 1.7.6.1 we using tinymce 4.0.16 which is ages old and used same version in prestashop 1.6 also. Now there is lot of new features available with new versions of tinymce.

When people use content and images rich html in description and CMS pages selecting images in text is too annoying. I had to implement a fix to use image selection but after upgrading to latest version that fix jnot working.

Please update me on this issue and its status

**Comment by khouloudbelguith** [comment]
Hi @beniwal,

This issue is added to our bug roadmap.
Sorry, it is not fixed yet.
PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by matks** [comment]
> @PrestaShop/prestashop-core-developers Would an update of tinyMCE to 4.6 be considered a BC break ? If yes, what about we use TinyMCE 4.6 in migrated pages ? Since the migration uses new Twig templates instead of smarty templates, we already make a BC break here. So we would use this opportunity and use an up-to-date tinyMCE version.

It's 2020 so I ask again 😄I think it would be nice to use TinyMCE 4.6 in migrated pages to solve this issue and move forward.
Ping @NeOMakinG @eternoendless

**Comment by NeOMakinG** [comment]
I agree, let's work on it

**Comment by matks** [comment]
@NeOMakinG Thanks !

FYI, tinyMCE is available on the following Symfony pages: (see https://github.com/PrestaShop/PrestaShop/issues/13206)
- Add/edit categories
- Add/edit CMS page
- Add/edit brands
- Add/edit a supplier
