### ISSUE TITLE
Australian Currency shows 'A$x.xx' AND can't change it in UI.

### ISSUE THREAD

**Issue by cmroanirgo** [PrestaShop/PrestaShop#11019]
**Describe the bug**
When you select Australian currency (and locale en-AU) the currency is always shown with a preceeding 'A'. This is incorrect.

I have tracked the source of the problem down to the configuration files:

1. `/translations/cldr/datas/main/en-US/currencies.json` (line 130), `"symbol": "A$"` should be `"symbol": "$"`

This trickles down into the other locales/regions, as far as I can ascertain:

2. such as `translations/cldr/main--en-AU-currencies` which also has 'AUD' with the incorrect symbol.

So, the bug is two-fold:

1. The default symbol provided is incorrect
2. I cannot find a way to change it in `International > Translations`.

PS: The correct way to display international currencies in Australia (for a multi currency shop ONLY) is to use the ISO code after the price: eg. **$123.23 USD**, but since this is a single currency setup, the ISO code shouldn't be displayed. It should be **$123.23**. So whatever PrestaShop is currently doing for currencies is simply incorrect.

**To Reproduce**

1. In 'International > Localization', change the settings to use Australian everything (en-AU, AUD currency). (See pics below)
2. All prices in Front End display as 'A$....'
3. Can't change it in Back Office

NB: Changing 'Set language from browser' and 'Set default country from browser' in 'International > Localization' has no effect on this bug.

**Screenshots**

Set everything to australian (/english)
![screen shot 2018-10-16 at 10 05 52 am](https://user-images.githubusercontent.com/15967/46983231-47035600-d12b-11e8-8af0-aadbe9b7758a.png)

Use only the one currency
![screen shot 2018-10-16 at 10 06 15 am](https://user-images.githubusercontent.com/15967/46983232-47035600-d12b-11e8-8199-5719c6c8e1da.png)

![screen shot 2018-10-16 at 10 06 31 am](https://user-images.githubusercontent.com/15967/46983233-479bec80-d12b-11e8-9367-81efbc715f90.png)

This is what the user sees
![screen shot 2018-10-16 at 10 15 46 am](https://user-images.githubusercontent.com/15967/46983492-7d8da080-d12c-11e8-8322-4b10506450bd.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @cmroanirgo,

Thanks for your report.
A$: it is not a wrong currency as you can read here: https://en.wikipedia.org/wiki/Australian_dollar
But the issue is that in the BO the Australian Dollar Symbol is $, but in FO, it is displayed in A$.
![image](https://user-images.githubusercontent.com/16067358/47007147-dd3d7900-d137-11e8-80d5-2535d384b7b8.png)
![image](https://user-images.githubusercontent.com/16067358/47007187-f21a0c80-d137-11e8-9f46-939853be3f76.png)
@marionf, what do you think?
thanks!

**Comment by cmroanirgo** [comment]
Whatever you may think to be the correct answer, I can absolutely guarantee you that as an Australian, this is NOT correct. This is NOT how we show prices. To an Australian, our prices are shown as "$123.23" without an 'A' in front of it. When we view prices on a website that has multiple currencies, we expect AUD or 'Australian Dollar' to be displayed... and NOT "A$"

The website I'm setting up using Prestashop has an unhappy Australian customer because he thought the 'A' meant American! (That's how incorrect it is!)

I'm sorry if I sound terse, but I'm trying to implore the importance of the fact that this **is** indeed a bug. I don't care if you show 'A$' if you're from anywhere else in the world, but to an Australian, it's wrong.

Edit: Here are some *very* large Australian shopping websites. Note the LACK of A$:
https://www.bunnings.com.au/
https://www.aldi.com.au/en/groceries/super-savers/
https://www.woolworths.com.au/

**Comment by MatShir** [comment]
Hi @cmroanirgo,

Thank for your feedback, we are currently reworking on the currencies management and display (CLDR). We are taking into account your comment. Don't hesitate to share more information related to this topic.

Thanks
Mateus

**Comment by MatShir** [comment]
The PR #10455 should fix this issue. It will be delivered on the 1.7.6.
Thank you
