### ISSUE TITLE
[1.7] ReferenceError: autorefresh_notifications is not defined

### ISSUE THREAD

**Issue by arsonists** [PrestaShop/PrestaShop#11016]
Enabling SSL on all pages gives me the following JQuery error and I can barely configure the backoffice.

ReferenceError: autorefresh_notifications is not defined 

![photo_2018-10-15_18-16-15](https://user-images.githubusercontent.com/22270830/46971833-62377c80-d0bd-11e8-956f-37f222e4c635.jpg)

It only skips me when I activate SSL on all pages.

It is a clean installation of Prestashop 1.7.4.3.

Greetings,

**Comment by PierreRambaud** [comment]
Hi and thanks for your feedback.
I could not find anything about `autorefresh_notifications` in the project. Did you install a custom module?
Kind regards

**Comment by khouloudbelguith** [comment]
Hi @arsonists, @PierreRambaud, it could be caused by a cached version of /js/admin/notifications.js in the browser (the 1.6 version was being loaded).
@arsonists, Did you made an upgrade from 1.6 to 1.7?
Could you please try to clear cache from your browser & your shop, check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @arsonists,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by bilavorona** [comment]
Ctrl + F5 can help
