### ISSUE TITLE
Problème avec déclinaisons, aucune par défaut parfois

### ISSUE THREAD

**Issue by GuimDotCom** [PrestaShop/PrestaShop#11029]
**Describe the bug**
Parfois côté boutique lorsque j'arrive sur une fiche produit qui a des déclinaisons cela m'affiche un prix à 0€, "Rupture de stock" et aucune déclinaison de sélectionnée (alors qu'il y a en une par défaut).

À ce moment là :
- Si j'actualise simplement la page (Ctrl + R), cela règle le souci et propose la déclinaison par défaut.
- Si je clique sur une déclinaison cela change en ajax le prix (0€ => 5,90€) et l'état (Rupture de Stock => En Stock)

**To Reproduce**
Difficile à reproduire car cela arrive aléatoirement. À noter que lorsque cela arrive, l'url du produit ne comporte pas les attributs dans l'url (exemple : /#/116-couleur-rouge )

**Screenshots**
![capture](https://user-images.githubusercontent.com/40210120/47015498-6d39ed80-d14d-11e8-9f35-4e5de602634e.png)

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 5.6.27

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
I've just done what you said and the bug always appears... :(
Is it possible that the problem is linked to a pretty url module (URLs utils by FMM Modules)? Which maybe don't reed url parameters like /#/116-couleur-rouge

**Comment by khouloudbelguith** [comment]
@GuimDotCom, to be sure that it is not the problem, you need to disable that module, clear cache, check & feedback.
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
I've disabled this module, clear cache, and problem always here...

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Could you please Navigate to the BO => Shop Parameters => Traffic & SEO and provide a screenshot of the SCHEMA OF URLS.
![image](https://user-images.githubusercontent.com/16067358/47072066-8c8c5580-d1f5-11e8-88ec-7a81af16c08e.png)
Thanks!

**Comment by GuimDotCom** [comment]
![routes](https://user-images.githubusercontent.com/40210120/47072470-5d2a1880-d1f6-11e8-9352-af1f7078d3b1.png)

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Can you change the SCHEMA OF URLS to the default Shema provided by PrestaShop?
Like described in this screenshot:
![image](https://user-images.githubusercontent.com/16067358/47073013-9911ad80-d1f7-11e8-98ce-f1325816b16b.png)
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith 
I've tested this night with default route and problem is always the same, furthermore I've just got the same problem on a product without combination... Price at 0€ and no product available, and after browser refresh, all is good. This is a real problem for our customers.

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
I have logged PHP error and activated debug mode but there is no error... 
(Except classic errors like:
[Tue Oct 23 17:14:38.144577 2018] [ssl:error] [pid 21296] AH02032: Hostname w provided via SNI and hostname www.diffuseurs-dessentielles.com provided via HTTP have no compatible SSL setup
[Tue Oct 23 17:15:04.225365 2018] [ssl:error] [pid 21286] AH02032: Hostname w provided via SNI and hostname www.diffuseurs-dessentielles.com provided via HTTP have no compatible SSL setup
)

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

The SSL mode is enabled in your BO => Shop Parameters => General?
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
SSL enabled yes, I have some news, I've just upgrade to 1.7.4.3
Seems that there are no more issue with sometimes no default combination selected...
BUT
New bug: on a product page, impossible to select other combination than the default. You can see it here: [https://bit.ly/2CGkEQT](https://bit.ly/2CGkEQT) if you want to choose "blanc" it's impossible...

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Thanks for your feedback.
Have you the same issue with this ticket: #9667.
Thanks?

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,

Almost the same except that all my combinations on this product have stock

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Can you change the SCHEMA OF URLS to the default Shema provided by PrestaShop, clear cache, check & feedback?
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,

Tested with default URL, same problem, and I have this same problem on 2 shops that are on 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

If you enable the debug mode, is there any exception displayed?
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,

I have enable debug mode, no exception. I have changed schema url to default and disabled all modules, same problem.

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Have you tried to contact the theme author?
Because this issue is fixed in the previous version 1.7.3.1: https://github.com/PrestaShop/PrestaShop/pull/7775
Thanks to check with them & feedback.

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,

Thanks but it is the same bug on official default prestashop theme... you can see it here: [https://bit.ly/2SgO5hD](https://bit.ly/2SgO5hD)

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Thanks to provide me a screenshot from this product (BO => Product page => Tab combinations).
Thanks!

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
![combination](https://user-images.githubusercontent.com/40210120/47519970-28216400-d88f-11e8-9880-e787fd1b6689.png)

**Comment by GuimDotCom** [comment]
Hi @khouloudbelguith,
I've just find the problem, if I remove a override/front/ProductController.php file writed by "FMM PrettyURLs" (which does not disappear when we disabled module) it works!
So I thnik this override controller is not compatible with 1.7.4.3
Thanks a lot for your help!

**Comment by khouloudbelguith** [comment]
Hi @GuimDotCom,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
