### ISSUE TITLE
Error 404 Page not found

### ISSUE THREAD

**Issue by andredt1980** [PrestaShop/PrestaShop#11031]
Dear install the latest version of prestashop with version 7.29 of php in windows.
The web is displayed correctly for the user that accesses but I can not access from the localhost to admin.
Other applications work even the frontend of the application.
I have not found anything specific about this.
Could you guide me?

**Comment by andredt1980** [comment]
Ok, I'm solved, install it again, a mystery.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @andredt1980,

Since it is fixed I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by Mokwa123** [comment]
Hi my client had install an SEO module on his prestashop website, and he had work on some products i.e doing the SEO, all the URL in the search result started to redirect to 404error page, please how can i correct this error.

Here is the URL https://www.lugoldstore.com

**Comment by khouloudbelguith** [comment]
Hi @Mokwa123,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Mokwa123** [comment]
Ok, thanks for your help
