### ISSUE TITLE
ERROR  /translations/cldr/datas/  "403 Forbidden "

### ISSUE THREAD

**Issue by Bartos-Pol** [PrestaShop/PrestaShop#11039]
Hi, 
Someone help with this problem?
At the store, all vat rates have been reduced from 23% to "no tax" 

Log:
"GET /translations/cldr/datas/main/pl-PL/numbers.json HTTP/1.1" 403 "
"GET /translations/cldr/datas/supplemental/currencyData.json HTTP/1.1" 403
"GET /translations/cldr/datas/supplemental/plurals.json HTTP/1.1" 403
"GET /translations/cldr/datas/main/pl-PL/currencies.json HTTP/1.1" 403"
"GET /translations/cldr/datas/supplemental/likelySubtags.json HTTP/1.1" 403

And PHP log:
 PHP Fatal error:  Uncaught ICanBoogie\CLDR\ResourceNotFound: Path not defined: main/pl_pl-PL_PL/currencies. in /vendor/icanboogie/cldr/lib/WebProvider.php:77

**Comment by khouloudbelguith** [comment]
Hi @Bartos-Pol,

Thanks for your report.
Could you please try to re-import the Poland package.
You need to navigate to the BO => International => Localization => Import a Poland localization pack, clear cache, check & feedback.
Thanks!

**Comment by Bartos-Pol** [comment]
Hi,
I am re-importing the package and adding only VAT EU for virtual products, I do not use the cache in the store but I cleaned it anyway.
Unfortunately, this did not solve the problem, you still can not change the VAT rate.

I checked on a different store PS 1.7.4.3 and there are the same mistakes but a tax change is possible.

Store hosted on VPS OVH / PHP 7.0/ Apache 2.4

**Comment by Bartos-Pol** [comment]
Hi,
I have solve the case :) 
I solved the tax problem, the error came from the store sync with MsSql and 23% is now work on shop.
The errors in php and apache still there!

**Comment by khouloudbelguith** [comment]
Hi @Bartos-Pol,

In Shop Parameters -> SEO &URL, if you switch "Disable apache mod security" to "Yes", the errors in PHP and apache still there?
Thanks!

**Comment by Bartos-Pol** [comment]
Hi @khouloudbelguith,
I have the switch "Disable Apache mod_security" set  to "No" and the errors have disappeared 👍 funny :) 
I had to turn this option off before as I was looking for a solution.
I will watch for a few days whether these errors will appear.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Bartos-Pol,

Since it fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!
