### ISSUE TITLE
[SF Migration] Improve hook.xml management ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11033]
File `install-dev/data/xml/hook.xml` contains hooks dispatched in Symfony page in order to input them into database.
This file is currently updated manually by developers who migrate pages from legacy to Symfony. I'm wondering if we can automate this.

@mickaelandrieu @Quetzacoalt91 I need your knowledge here 😉 
Can you confirm this hook.xml file kindof replaces `$this->regsiterHook()` in modules ?

**Comment by Quetzacoalt91** [comment]
>  Can you confirm this hook.xml file kindof replaces $this->regsiterHook() in modules ?

Absolutely not.

Hook.xml contains a non-exhaustive list of hooks installed at PrestaShop installation. But modules will always be required to call `$this->registerHook()` to make their module called by the core.

**Comment by matks** [comment]
@Quetzacoalt91 thank your for the answer :)

Then why do we need this hook.xml file for Symfony hooks ? what is the difference between legacy hooks and SF hooks ? I am sorry I do not get it

**Comment by sarjon** [comment]
>  what is the difference between legacy hooks and SF hooks

i dont think there is, at least there shouldnt be.

**Comment by matks** [comment]
Ping @Quetzacoalt91 do you know why do we need this hook.xml file for Symfony hooks ? what is the difference between legacy hooks and SF hooks ? I am sorry I do not get it

**Comment by matks** [comment]
Could not find a reason to keep this file. Only thing I can think of is a hook list for developers however handling it manually will lead to errors.
I'll make a PR to remove this seemingly useless file in `develop` .

🔽 https://github.com/PrestaShop/PrestaShop/pull/11187

**Comment by Quetzacoalt91** [comment]
Hmm, while I may agree about the hook.xml file, the hook_alias details seem important for me.

If you delete this file, are you sure the aliases will be properly handled?

**Comment by mickaelandrieu** [comment]
> As a note, I still don't understand why we invest time on it "right now" as the current system works and when we have so many subjects to address like the hooks on the form entities, the update of the form theme or figure out how we can migrate the AdminLegacyLayoutController.

**Comment by matks** [comment]
@mickaelandrieu This topic is indeed not important, but since it is quite easy to handle I started the topic. If the work needed behind was bigger, I would have kept it for later.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13593
