### ISSUE TITLE
Bug d'ajout au panier

### ISSUE THREAD

**Issue by itroom-agence** [PrestaShop/PrestaShop#11036]
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.x
| Description?  | Sur une page produit, lorsque l'on clique sur le bouton d'ajout au panier (avant que la page soit complètement chargée et que le javascript de la génération du pop-up panier soit chargé) nous sommes redirigé vers le panier dans lequel notre produit n'est pas ajouté. 
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Facilement reproductible avec une connexion lente (type 3G) et en désactivant le cache navigateur. Lors de la redirection, aucun paramètre "action" n'est spécifié, l'appel de la méthode "processDeleteProductInCart()" n'est pas fait. 
[cart.zip](https://github.com/PrestaShop/PrestaShop/files/2483908/cart.zip)

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Is it the same issue reported here: #10873?
Thanks!

**Comment by itroom-agence** [comment]
Hi @khouloudbelguith,

No it's not the same issue.

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Thanks for the video record.
I manage to reproduce the issue, we are redirected to an empty shopping cart.
It is difficult to reproduce the issue, The "Add to cart" button is not fully loaded => clicking on it => error => like in the video record.
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 

I can't reproduce it on 1.7.6.x, can you try to reproduce it ?

**Comment by khouloudbelguith** [comment]
@marionf, no in my case also, I did not manage to reproduce the issue with PS1.7.6.0beta1.
I tried to reload the product page many times & clicking on the `Add to cart` few times
But it is OK
https://drive.google.com/file/d/1Q7tIgDPWNNGgs8kISm7X6VcXZ9JUFvsU/view
Thanks!
