### ISSUE TITLE
Add a new discount with invalid reduction_percent => there is no alert - Order Back office

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11034]
**Describe the bug**

In the BO => Orders => Order details => we try to add a new discount with invalid reduction_percent 300% => a green alert "Successful update." is displayed => but there is no discount added.
The green alert is wrong, we should have a red alert
![image](https://user-images.githubusercontent.com/16067358/47024655-6bc6f000-d162-11e8-96f3-675db9c53144.png)

**To Reproduce**
1. Go to BO => Orders 
2. Edit any order
3. Scroll down to add a new discount ( type => percent / Value => 300%)
4. Click Add => "Successful update" is displayed => there is no discount added.

**Screenshots**
https://drive.google.com/file/d/1Alr7eqn8hNxOcBBlNXNTgdZ-KwerkV2z/view

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by colinegin** [comment]
Hello @khouloudbelguith could you please test this issue and see if it is fixed on 177x ? 
Thanks !

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

It is fixed when we add a new discount >100%
https://drive.google.com/file/d/1igte2JACrtZKEiJGvO4NR2GGJPpwtPdG/view
![image](https://user-images.githubusercontent.com/16067358/74854844-2a3eea00-5340-11ea-934c-6318f0855060.png)

But an exception detected when we add a new discount = `-10%`
![image](https://user-images.githubusercontent.com/16067358/74854942-4b9fd600-5340-11ea-811f-d4f34e51abe7.png)

![image](https://user-images.githubusercontent.com/16067358/74854891-3b87f680-5340-11ea-9b21-e82e3f0424f3.png)

Reproduced with 177x branch, PS1.7.6.3 and PS1.7.5.2

Related to #17747

Thanks!

**Comment by colinegin** [comment]
Alright so maybe we can close this issue and just have #17747 open?

**Comment by khouloudbelguith** [comment]
@colinegin, alright!
I will close this issue and update the new issue.

Thanks!
