### ISSUE TITLE
Cannot delete product combinations with prestashop 1.7.4.2

### ISSUE THREAD

**Issue by unicomprocom** [PrestaShop/PrestaShop#11048]
I Cannot delete product combinations with version 1.7.4.2

When I debug the javascript the server returns the following:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /adminxxxxxxxx/index.php/attribute/110
on this server.<br />
</p>
</body></html>

VM6683:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (product-combinations.js?1.7.0:35)
    at u (main.bundle.js:292)
    at Object.fireWith [as rejectWith] (main.bundle.js:292)
    at i (main.bundle.js:292)
    at XMLHttpRequest.<anonymous> (main.bundle.js:292)

Thanks for your help

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

It is a server issue permission.
You need to check your host about this issue.
Thanks to check with them & feedback.

**Comment by unicomprocom** [comment]
Thank you for response but i have this problem after prestashop migration , if we pick this url  /adminpresta/index.php/attribute/110 "with another prestashop website that does not contain this problem , we have also this error "The server returned a "405 Method Not Allowed"." I think that the problem is why after delete combinaison it try to go to this url.

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

What is the exact previous version Prestashop did you use before the upgrade?
What is the exact version of the 1-click upgrade?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by quendistudio** [comment]
> Hi @wajingdev,
> 
> It is a server issue permission. You need to check your host about this issue. Thanks to check with them & feedback.

No, this is a stupid functionality issue, using the http DELETE method and not giving the administrator the option to disable this is a bad idea as many hosts will not allow DELETE requests regardless of configuration.
