### ISSUE TITLE
HTTPS ERROR

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#11046]
**Describe the bug**
when i go to actívate https in a fresh instalation of prestashop 1.7.3 get this

**To Reproduce**
1. Go to 'configuration'
2. Click on 'check ssl'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/9163980/47077396-2279ad80-d201-11e8-86f1-cc1fc5ca9712.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

If you own an SSL certificate for your shop's domain name, you can activate SSL encryption (https://) for customer account identification and order processing.
you need to check your host about this issue.
Thanks to check with them & feedback.

**Comment by LinkOfLight** [comment]
if u can see i have the certificates and i have activates, have 2 more shops in this hosting and i dont have any problema
![image](https://user-images.githubusercontent.com/9163980/47078595-f01d7f80-d203-11e8-97af-31c7601d821d.png)

**Comment by khouloudbelguith** [comment]
@LinkOfLight,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by LinkOfLight** [comment]
Fixed, i reinstall prestashop and actívate ssl before change the admin directory name

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
