### ISSUE TITLE
Add ability to remove anchor from product link when using URL smarty helper function

### ISSUE THREAD

**Issue by tlhuillier** [PrestaShop/PrestaShop#11041]
When creating a product link (with product attribute) from the Smarty helper function `url`, it is not possible to define wether or not to add the anchor at the end or the URL.
`https://your-website.com/cat/1-1-product.html#/product-attribute`

It is possible to do so when using directly  the instance of `Link` object, but it's deprecated.

We should add the anchor parameter to the `url` Smarty helper function.

**Comment by khouloudbelguith** [comment]
Hi @tlhuillier,

Thanks for your report.
@eternoendless, @colinegin  @PrestaShop/prestashop-core-developers what do you think of his suggestion.
Thanks!

**Comment by tlhuillier** [comment]
Edit:
I was wrong.
We didn't have the ability to remove the anchor, even using Link::getProductLink, but only hide IDs.

**Comment by khouloudbelguith** [comment]
Hi, @tlhuillier,

So do you want to delete the IDs from the URL?
We are working on improving many of the outstanding SEO issues the community has been raising for some time.
 If you don't like having IDs at the start of the slug, you can change that on your back office so that they are at the end of the URL. Go to Shop Parameters > Traffic & Seo, scroll down the page to find the "Schema of URLs" section, then change "Route to products" to something like this:
`{category:/}{rewrite}{id}{:id_product_attribute}{-:ean13}.html`
Thanks!

**Comment by colinegin** [comment]
Hello @tlhuillier ,

Thanks for your feedback. Unfortunately, it's not easy to move from one URL format to another during minor versions as there are risks to break things down when upgrading.

We will be rethinking the URL format for the next major version. Do not hesitate to share your ideas !
In the meantime, you can find different modules available on the Addons marketplace which enable you to remove IDs from product pages.

Regards,

**Comment by khouloudbelguith** [comment]
Hi,

As suggested by @yannicka in this issue: https://github.com/PrestaShop/PrestaShop/issues/16413
>Is this anchor needed?
https://github.com/PrestaShop/PrestaShop/blob/e136975bf809f89f35fdd59a785806e3e0bf8eab/classes/Link.php#L233

I've replaced this line by:

```php
$anchor = '';
```

And everything seems to be working fine.

This anchor generates a URL that seems longer than necessary. Perhaps this anchor should be removed or an option should be given to enable/disable it globally if necessary

Thanks!

**Comment by PierreRambaud** [comment]
Hi everyone,

We should be able to remove anchor when it's not needed :+1:

**Comment by kpodemski** [comment]
@PierreRambaud you can check this PR

https://github.com/PrestaShop/PrestaShop/pull/19400

maybe you will find a way to avoid BC break 👍

**Comment by PierreRambaud** [comment]
> @PierreRambaud you can check this PR
> 
> #19400
> 
> maybe you will find a way to avoid BC break

I think I have an idea :) Thanks
