### ISSUE TITLE
Default value should be set to 0 for arithmetic operation

### ISSUE THREAD

**Issue by damiweb** [PrestaShop/PrestaShop#11050]
https://github.com/PrestaShop/PrestaShop/blob/5bb2a6c21c5384f1d738bd433c69068a29247b6d/themes/default-bootstrap/product.tpl#L730-L731

Default value should be set to 0 for arithmetic operation:

<pre><code class="language-smarty">
{addJsDef productPriceTaxExcluded=($product->getPriceWithoutReduct(true)|default:0 - $product->ecotax)|floatval}
{addJsDef productPriceTaxIncluded=($product->getPriceWithoutReduct(false)|default:0 - $product->ecotax * (1 + $ecotaxTax_rate / 100))|floatval}
</code></pre>

**Comment by khouloudbelguith** [comment]
Hi @damiweb,
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!
