### ISSUE TITLE
Error : please install composer. Then run "php composer.phar install"

### ISSUE THREAD

**Issue by sedll7809** [PrestaShop/PrestaShop#11057]
when I first  visited my server "http://192.168.0.202:6080/PrestaShop/install-dev/index.php" to install,
but prompt please install composer. Then run "php composer.phar install". I have already install composer. I use  command "composer -V" can see  version.

**Comment by khouloudbelguith** [comment]
Hi @sedll7809,

Did you clone the Project Prestashop from the [official repository](https://github.com/PrestaShop/PrestaShop)?
To download composer, you can follow this link: 
https://getcomposer.org/download/
You need to run the 4 commands:
```

1. php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
2. php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
3. php composer-setup.php
4. php -r "unlink('composer-setup.php');"

```
 before running `php composer.phar install`
Thanks to check & feedbck.
PS: this is not the stable version, it is the dev version.
For the stable version, you can download from this [link](https://www.prestashop.com/en/previous-versions), you don't need to install composer.

**Comment by sedll7809** [comment]
hi khouloudbelguith :
thanks, I have already download  stable version.thanks

**Comment by khouloudbelguith** [comment]
Hi @sedll7809,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by ghost** [comment]
The correct instruction
go to www folder in terminal (where ps files)
run command: curl -O https://getcomposer.org/composer.phar
run command: php composer.phar install
then in web go to www.website.com/install-dev
