### ISSUE TITLE
Invalid order->total_discounts after deleteting voucher from backoffice

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#11059]
Sometimes, when you delete a voucher from an order in back office, you will get an exception and the order gets messed up.

**How to reproduce:**
- Rouding setup: (mathematically up (default), each line rounding, zero decimal places.
- Make a product with price for example 5800
- Make a cart rule: 5% discount with tax for all orders
- Go to admin, delete the voucher, exception

**Cause:**
Total discounts with tax is rounded to 290; without tax to 240, 
Cart rule is NOT ROUNDED - with tax 290 and without tax 239,65.
When you delete the voucher, Prestashop does this:
`// Update amounts of order`
`$order->total_discounts -= $order_cart_rule->value;`
`$order->total_discounts_tax_incl -= $order_cart_rule->value;`
`$order->total_discounts_tax_excl -= $order_cart_rule->value_tax_excl;`

The resulting total discounts W/O TAX is 0,35, which is bigger than WITH TAX, which is invalid. Sometimes total_discounts is negative, which is also invalid.

**Possible resolution:**
Instead of subtracting the voucher value from total discounts...
1. Set total discounts to 0. 
2. Check for remaining vouchers of this order, sum their values > get 100% correct result of total_discounts. 
3. Recalculate the order total and update it.

**Versions:**
Happens in all 1.6 and 1.7 versions, the code is still the same.
PHP 5.6, 7.1 and currently 7.2

**Screenshots:**
![update - exception](https://user-images.githubusercontent.com/6097524/47141755-ae530e80-d2c1-11e8-9581-8091508f44ab.jpg)
![screenshot](https://user-images.githubusercontent.com/6097524/47141756-ae530e80-d2c1-11e8-8fd8-4d212b33bc6b.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I did not manage to reproduce the issue with the last version 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1mXcGwzr_2z5ft9RroLKm_9zvTUO_be3P/view
Thanks to check & feedback.

**Comment by Hlavtox** [comment]
Hi @khouloudbelguith :)

I just managed to reproduce it on 1.7.3.2. 

Can you check your database values for the order and the voucher?

**Order:**
![order](https://user-images.githubusercontent.com/6097524/47150518-195b1000-d2d7-11e8-9133-6e589de3e450.JPG)

**Voucher:**
![voucher](https://user-images.githubusercontent.com/6097524/47150522-1c560080-d2d7-11e8-9893-44cc7d40f376.JPG)

**Exception:**
![exception](https://user-images.githubusercontent.com/6097524/47150529-1fe98780-d2d7-11e8-87ec-a14bbcddab7a.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for this clarification ( The product should have a tax rule)
Steps to reproduce the issue:
1- Create a product 
1.1 Price (tax incl.) = 435.95 €
1.2 Tax rule = 50% => Price (tax excl.) = 290.633333 €
2. Create a cart rule 5%
3. Add the last prduct to the cart => process checkout
4. Edit the order created
5. Delete the discount
6. see the error
![image](https://user-images.githubusercontent.com/16067358/47151590-72787300-d2da-11e8-97fe-8da62d8dab03.png)


Thanks!

**Comment by Hlavtox** [comment]
Any updates on this? It's pretty important I think, if you can't manage the order.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Sorry not yet.
Thanks for your understanding and your patience.

**Comment by Hlavtox** [comment]
@khouloudbelguith Can you lift this issue somewhere higher? I think the whole "Order editing" stuff should be really, really thinked through, especially when converting the page to Symphony.

There is more stuff that is wrong. When adding or deleting a product from order, the code also subtracts or adds the product's price from total_paid, but this creates a room for rounding errors.

The order's total and taxes should be recalculated whenewer anything is changed - a product, shipping, voucher. Then these exceptions like I submitted in this issue wouldn't happen.

**Comment by marionf** [comment]
@khouloudbelguith 

I can't reproduce the issue with the following scenario on 1.7.6.x, the discount is well deleted without any error
1- Create a product
1.1 Price (tax incl.) = 435.95 €
1.2 Tax rule = 50% => Price (tax excl.) = 290.633333 €
2. Create a cart rule 5%
3. Add the last prduct to the cart => process checkout
4. Edit the order created
5. Delete the discount
6. see the error

Can you try to reproduce it ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

No, I did not manage to reproduce the issue with PS1.7.6.0beta1
https://drive.google.com/file/d/1iBJp_sigAD68RbE2xYsooK8PRh5uOo9R/view
It seems to be fixed.
I close the issue.
THanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith 

I don't know if somebody is trying to make jokes of people or WTF is happening here. I am opening this issue for second time and always somebody quiets it down or says it's fixed when it's not. 

Now there is another issue and it throws 500 even when creating the voucher.
https://youtu.be/MHbHYnx5UAo

**Comment by marionf** [comment]
Hi @Hlavtox 

[the scenario](https://github.com/PrestaShop/PrestaShop/issues/11059#issuecomment-430974697) described in this one isn't reproducible with 1.7.6.0

You have another issue, so I created a new issue for you: https://github.com/PrestaShop/PrestaShop/issues/13809

**Comment by ghost** [comment]
1.6.x

/controllers/admin/AdminOrdersController.php

~ 1317 row:
                    // Update amounts of order
                    $order->total_discounts -= $order_cart_rule->value;
                    $order->total_discounts_tax_incl -= $order_cart_rule->value;

after that put this code:

                    $round = round($order_cart_rule->value_tax_excl);
                    $order_cart_rule->value_tax_excl = $round;

That's all.
