### ISSUE TITLE
sending order message returns 500 error

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11064]
Prestashop 1.7.4.3.
PHP 7.2

Sending order message returns 500 error. 

See attached screen print debug on

![2018-10-18_16h10_42](https://user-images.githubusercontent.com/11147327/47160882-2a187f80-d2f1-11e8-91ba-6ceb791bc9c4.png)

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

This issue is occurred due to php-intl extension.
Could you please try to install it, it is required.
Thanks to check and feedback.

**Comment by Peter4661** [comment]
After installing php-intl, no issues 

Thank you for you help.  

In Prestashop  1.7.4 documentation, I could not find php-intl extension is requirement.

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!
