### ISSUE TITLE
install completed,but not open admin page

### ISSUE THREAD

**Issue by sedll7809** [PrestaShop/PrestaShop#11073]
**Describe the bug**
when I install PrestaShop  1.7.2.2  complete, but I  not open admin page ,  error:HTTP ERROR 500.
my admin page url : http://192.168.0.202:6080/PrestaShop/prestashop/admin/
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2.2
PHP version: 7.2.11

**Comment by sedll7809** [comment]
add error :
I add "admin/index.php " page php error.

Fatal error: Declaration of AdminDashboardControllerCore::setMedia() must be compatible with AdminControllerCore::setMedia($isNewTheme = false) in D:\xampp\htdocs\PrestaShop\prestashop\controllers\admin\AdminDashboardController.php on line 539

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Compile Error: Declaration of AdminDashboardControllerCore::setMedia() must be compatible with AdminControllerCore::setMedia($isNewTheme = false) in D:\xampp\htdocs\PrestaShop\prestashop\controllers\admin\AdminDashboardController.php:539 Stack trace: #0 {main} Next LogicException: Request stack is empty in D:\xampp\htdocs\PrestaShop\prestashop\app\bootstrap.php.cache:3225 Stack trace: #0 [internal function]: Symfony\Component\HttpKernel\HttpKernel->terminateWithException(Object(Symfony\Component\Debug\Exception\FatalErrorException)) #1 D:\xampp\htdocs\PrestaShop\prestashop\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(606): call_user_func(Array, Object(Symfony\Component\Debug\Exception\FatalErrorException)) #2 D:\xampp\htdocs\PrestaShop\prestashop\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(668): Symfony\Component\Debug\ErrorHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalError in D:\xampp\htdocs\PrestaShop\prestashop\app\bootstrap.php.cache on line 3225

**Comment by khouloudbelguith** [comment]
Hi @sedll7809,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

PS: 1.7.2.2 is not compatible with PHP 7.2, we recommend that you run your PrestaShop install on PHP 7.1, for more information, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to check and feedback.

**Comment by sedll7809** [comment]
hi khouloudbelguith
thanks
I have already open login page,I change php 7.1,but I input login mail and password to login,there has an 
error :The employee does not exist, or the password provided is incorrect.

**Comment by sedll7809** [comment]
hi khouloudbelguith
thanks
I can login my prestashop ,thanks

**Comment by khouloudbelguith** [comment]
Hi @sedll7809,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
