### ISSUE TITLE
Move wheel button on migrated pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11080]
**Describe the bug**

On some migrated pages, the wheel button should be placed here:

![capture d ecran_472](https://user-images.githubusercontent.com/13449658/47212643-0a3c9680-d399-11e8-8050-405a933450f0.png)

We need to change it on pages already migrated :

SQL manager
Contact
SEO & URLs
Webservice
Logs
Email

@TristanLDD & @matks FYI

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/11095
