### ISSUE TITLE
The button "Use the last registered format" doesn't work - Countries page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11088]
**Describe the bug**
When we try to create a new country ( BO => International => Locations => Countries Tab), in the Address format the button "Use the last registered format" doesn't work, the Address format use the default format
**To Reproduce**
1. Go to BO => International => Locations => Countries Tab
2. Create a new country C1 with Adress Format
2.1. firstname
2.2. company
2.3. vat_number
2.4. address1
2.5. Country:name
3. Create a second country 
4. Click on " Use the last registered format" => the Address format use the default format & not the last one registered in the C1.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith 

"Use the last registered format" works for the same country, not if you create a new one.

For example:
- Create a country with format:
firstname
company
vat_number
address1
Country:name
- Save
- Edit the created country
remove address1
- Click on "Use the last registered format" 
"address 1" is back
