### ISSUE TITLE
Prestashop install Error sfRouter

### ISSUE THREAD

**Issue by 21let** [PrestaShop/PrestaShop#11096]
**Describe the bug**
You can not install Prestashop on OS Centos 7.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 5.6.3

**Screenshots**

![image](https://user-images.githubusercontent.com/13964136/47261547-ae295d80-d4d1-11e8-984b-637c5e1603f1.png)

**Comment by khouloudbelguith** [comment]
Hi @21let,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10696 to solve the issue.
I close the ticket, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @21let,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10696 to solve the issue.
I close the ticket, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @21let,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10696 to solve the issue.
I close the ticket, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10696
