### ISSUE TITLE
State/counties missing from UK

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#11090]
**Describe the bug**
I try to import states/counties from UK like Yorkshire and others, but it's not working. 

Are there any states available for UK? 

I want to mention that I tried to import them having "english-gb" language active.

**Additionnal information**
PrestaShop version: 1.7.3.2
PHP version: 7.0.30

**Comment by khouloudbelguith** [comment]
Hi @klopp1892,

Did you try to import the "United Kingdom" pack from the Localization page?
Thanks!

**Comment by ghost** [comment]
Yeah, I tried to import the states from the Localization page but no impact (tried for about 10 times). 

I really don't know why it's not working but let me activate the debugger, check the error logs and see if I get something.

**Comment by khouloudbelguith** [comment]
Hi @klopp1892,

Yeah, after importing the Uk pack, there are no states created for this country.
But you can follow this link: https://addons.prestashop.com/en/shipping-carriers/20777-uk-counties-pack.html to add zones and states (counties) for the UK
Thanks to check & feedback.

**Comment by aksthelion** [comment]
I just downloaded v 9.0 and this issue persists. How do we add UK counties? I did add states from the localization page but it is still not showing any UK counties. How to fix it?

**Comment by aksthelion** [comment]
> Yeah, after importing the Uk pack, there are no states created for this country.
> But you can follow this link: https://addons.prestashop.com/en/shipping-carriers/20777-uk-counties-pack.html to add zones and states (counties) for the UK
> Thanks to check & feedback.

How is that link relevant to the question? Link shows shipping modules, we are looking for counties to be added. How is that relavant?

**Comment by aksthelion** [comment]
> Yeah, I tried to import the states from the Localization page but no impact (tried for about 10 times).
> 
> I really don't know why it's not working but let me activate the debugger, check the error logs and see if I get something.

Hello, Did you manage to fix this issue?
