### ISSUE TITLE
german translation bug- buy button with obligation to pay

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#11097]
the button in german is kaufen, which is forbiden since 2012...please fix the translation for the buy button 1.6. versions affected

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!
