### ISSUE TITLE
1.6.1.22 Endless Spinning Product Save Button

### ISSUE THREAD

**Issue by tpedaniel** [PrestaShop/PrestaShop#11106]
I am running prestashop for years, from v1.6.1.16. now I have 1.6.1.20 running by upgrade.
Here the problem I meet, when I edit products contents but the save button always spinning.
I had referenced some blogs and prestashop forum, then check the code file named feature.php.
It all not work. The problem is still borrowing me until now.

**Comment by tpedaniel** [comment]
update, the version now is 1.6.1.22

**Comment by khouloudbelguith** [comment]
Hi @tpedaniel,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-9042
It wasn't necessary to create a new one.
So, this one can be closed
Thanks!

**Comment by tpedaniel** [comment]
I tried following to config on backoffice panel as khouloudbelguith proposed to me. 
It has worked on that moment. But next day I would edit the products content on my site, the problem is still there.
Is there any solutions what I could use?

**Comment by khouloudbelguith** [comment]
Hi @tpedaniel,

Sorry, the issue is not fixed yet.
You need to follow this [ticket](http://forge.prestashop.com/browse/PSCSX-9042)
Thanks!

**Comment by tpedaniel** [comment]
hi, khouloudbelguith;

Thanks your comments.
