### ISSUE TITLE
Generated test directory at install step is not cleaned if github is down

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11107]
**Describe the bug**
When a PrestaShop 1.7.5+ is installed, the installer performs several checks to see whether it has been given the proper read&write rights. If these rights are available **and** the PrestaShop Zip archive is not the latest, it offers the user to download the latest Zip archive and install this one.

During these tests, fake files and folders are created. However [one of those tests](https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/Library/InstallUnpacker/classes/ConfigurationValidator.php#L100) check that PrestaShop is able to download a file from github. If this test fails, the check processing stops there. However the fake files and folders are deleted at the end of the check processing: [here](https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/Library/InstallUnpacker/classes/ConfigurationValidator.php#L109) and [here](https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/Library/InstallUnpacker/classes/ConfigurationValidator.php#L113). So if the check fails, the fake files and folders remain in the root folder of PrestaShop. They cause no harm, but they are useless.

This is not critical as this is a bonus feature that does not prevent the installation.

**TO DO**
- make sure fake files and folders are cleaned even if the check processing stops halfway
- do not rely on github to perform the "download" test (find a better test subject)

PrestaShop version: 1.7.5 at least

**Comment by jolelievre** [comment]
maybe you should have a list of candidate files to try to download, no super nice but it reduces the risk to fail the test (the chances that 5 files are not accessible is lower)

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/11206
