### ISSUE TITLE
Drag & drop on migrated positions page doesn't looks like the mockup

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11102]
type : tech-issue

**Describe the bug**

@TristanLDD made mockups for drag & drop in BO
We need to include it on migrated positions page

**Screenshots**
Currently it looks like this:

![capture d ecran_489](https://user-images.githubusercontent.com/13449658/47282846-0bf89b00-d5e1-11e8-9be7-5b880cde5b53.png)

Mockup https://zpl.io/aMvjjj7

![capture d ecran_490](https://user-images.githubusercontent.com/13449658/47282381-47926580-d5df-11e8-91a3-94e867fc0ec8.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by jolelievre** [comment]
The mockup was implemented with the new `PositionColumn` in the new Grid system (introduced in 1.7.5).
So if the migrated page uses a Grid it should work. Is there a more detailed list of pages that don't look like they should?

**Comment by marionf** [comment]
We have also the product page

![capture d ecran_740](https://user-images.githubusercontent.com/13449658/49745559-8b305400-fc9f-11e8-8c21-3b567a9ee363.png)

But I don't know if we should change something also on this one @TristanLDD ?

**Comment by jolelievre** [comment]
Yes but the product page is special as it has already been migrated once. I believe it is planned to refactor it but only once all other pages will have been migrated.

**Comment by marionf** [comment]
So, we have just positions page right now

**Comment by colinegin** [comment]
#12628

**Comment by colinegin** [comment]
#12628

**Comment by colinegin** [comment]
#12646
