### ISSUE TITLE
Error imprimir pedido

### ISSUE THREAD

**Issue by javierVP** [PrestaShop/PrestaShop#11108]
Adjunto imagen de como se me imprime el pedido, ¿
![captura de pantalla 2018-10-22 a las 17 19 31](https://user-images.githubusercontent.com/42347565/47301208-acb97b80-d61e-11e8-8dbe-c69d7ae9cfd9.png)
me podrian decir donde se puede solucionar esto?

**Comment by khouloudbelguith** [comment]
Hi @javierVP,

Here's the PR: #10135 to solve the issue.
Your ticket is a duplicate of #9527
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9527

**Comment by javierVP** [comment]
Gracias Thanks!!
