### ISSUE TITLE
Error code 500 when trying to access on Advanced Parameters>Webservice page

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#11109]
**Describe the bug**
Trying a simple access on Webservice page through an error page (code 500)

**To Reproduce**
1. Go to 'Advanced Parameters > webservice'
2. See error (as capture below)

**Screenshots**
![selection_404](https://user-images.githubusercontent.com/29543279/47302361-9c56d000-d621-11e8-8139-4dfd8335cb42.png)

**Additionnal information**
PrestaShop version: 1.7.5.0-beta1_build1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
If we enable the debug mode
![image](https://user-images.githubusercontent.com/16067358/47303003-323f2a80-d623-11e8-98a4-d0e6447c8632.png)
Thanks!
