### ISSUE TITLE
BUG in CACHE SMARTY presta 1.7.4.3 !!!!

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#11113]
**Describe the bug**
When I active cache smarty, In BO, in filesystem, the flags information (Out of stock) dont change properly, Only dissapear when clear cache files or force the update of template.

**To Reproduce**
1. Active cache in BO
2. Set FILESYSTEM and clear cache everytime some has modifyed
3. Add a product with only 1qty in stock
4. Add this item to cart (This decrease and show the flag Out of stock)
5. Delete the item of cart and press F5 (This increase the qty and Delete the flag Out of stock)
6. Repeat step 3 -> F5 -> Step 4 -> F5 ( the flag OUT OF STOCK dont deleted anymore )
7. Clean Cache -> F5 (The flag dissapears correctly)

**Screenshots**
[bug.ogv.zip](https://github.com/PrestaShop/PrestaShop/files/2503541/bug.ogv.zip)

**Additionnal information**
Información del servidor Linux #1 SMP Wed Oct 11 15:51:10 EDT 2017 x86_64

Versión del software del servidor: Apache

Versión PHP: 7.2.11

Límite de memoria: 256M

Tiempo máx. de ejecución: 300

Tamaño máx. para la subida de archivos: 32M

Versión de PrestaShop: 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

As it's not the default theme, provided by Prestashop, we can't do anything with this before the feedback of the theme author.
You should contact the theme author via your addons.prestashop.com account.
Thanks to check with them the issue & feedback.

**Comment by TecnoHands** [comment]
This is no error of the theme.
Add other problem, this problem occurs after upgrade to 1.7.4.3
I modify a table of version install prestashop to 1.7.4.3
and update all files manually, but have the same problem the modules dont update:


3 | G. Nicolás | 3 | Excepción emitida por el módulo gamification en upgrade. Error sent by Addons. You may be not allowed to download this module. |   | 0 | 0x	0 | 29/10/2018 11:51:16
-- | -- | -- | -- | -- | -- | -- | --

All this suck problems after updating to 1.7.4.3 with the 1-click-upgrade

**Comment by TecnoHands** [comment]
The front office, work well, But I having problems in modules update in the BO.
In information display:

info_outline Comprueba tu configuración
Parámetros requeridos: Por favor, corrige el (los) siguiente(s) error(es)

Parámetros opcionales: OK

Parameters required display the message error but dont display WHERE is the problem... Very very useless

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

It seems that a description is missing, and that's why it could not be listed in the "following errors". 
Here's the PR about that issue in https://github.com/PrestaShop/PrestaShop/pull/9407.
If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.
Thanks!

**Comment by TecnoHands** [comment]
> Hi @TecnoHands,
> 
> It seems that a description is missing, and that's why it could not be listed in the "following errors".
> Here's the PR about that issue in #9407.
> If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.
> Thanks!

Very thanks, With the changes in this two files, the report of necesary parameters display a error in the permissions of cache in my theme Change it to 611 and worked fine 

info_outline Comprueba tu configuración
Parámetros requeridos: OK

Parámetros opcionales: OK

And can update the modules in BO,
VERY VERY THANKS.

Can close the issue

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by TecnoHands** [comment]
Sorry, The others bugs yes solved, but When activate the smarty cache... Dont work properly BO
I click in  config for example and kick me to BO login, I clear all files in the browser and dont worked too
I click in performance and kick me too to login in BO

And, when i add my publish ip to maintenance mode, dont show me the Front

**Comment by TecnoHands** [comment]
Sorry Bad mine, jaja disable temporaly cloudflare and work fine the cache of prestashop
