### ISSUE TITLE
Reader feature

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11116]
Prestashop 1.7.4.3
Apache+nginx
php 7.2.11
https://www.useloom.com/share/8bc7a663932044af87b511ff1e0bb05a
as you can see on my video, if a customer can apply reorder feature, when last your order was shipped, reader button jump it to homepage; on other order state, red alert on top inform customer your order cannot be done.
Strange behaviour.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1B70VCyFULkbKlox_Z9DuDAdTdaWF5RA7/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by centoasa** [comment]
debug mode and php error log not show any error.
It's strange: order I can try to reorder, in the origin have item A, instead when I try to reader, cart show me item B
Maybe this reorder feature related with old shopping carts? Because I've deleted all old shopping cart.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Yes, that's exactly the issue, you have deleted carts manually from the database.
After truncating the ps_cart table options you need to set the "AUTO_INCREMENT"= 1101( = last-id-cart+1) and save, then the id of the next cart created will be 1001.
Thanks to check & feedback.

**Comment by centoasa** [comment]
and that's exactly what I did when I truncated the ps_cart table.
And now I've understand this issue: the cart related with old order no longer exists! 
Is there a way to rebuild all orders-->carts?

**Comment by khouloudbelguith** [comment]
@centoasa, did you set the AUTO_INCREMENT in the ps_cart table options?

**Comment by centoasa** [comment]
yes, it's done!
but I've imported old order from 1.6, and for sure I've truncated ps-cart table and set auto_increment to last order number on 1.7 
So now: ps_cart start from 2067 to 2132
Orders start from 10 to 2082

**Comment by khouloudbelguith** [comment]
Hi @centoasa, so you need set the "AUTO_INCREMENT"= 2133: last id_cart.

**Comment by centoasa** [comment]
The problem is that inside ps_cart all the orders are missing from10 to 2066
This is why the reorder function does not work. Is there a chance to re-enter them, or is it enough for me to add them by hand?
If so, how?

**Comment by khouloudbelguith** [comment]
@centoasa, yes you need to create it manually, if you are a developer you can create a script to insert data into the database.
Thanks!
