### ISSUE TITLE
PrestashopCollection and join method

### ISSUE THREAD

**Issue by camlafit** [PrestaShop/PrestaShop#11117]
**Describe the bug**
PrestshopCollection::join() can't do any association. In any case raise an exception

**To Reproduce**

Write any code as this : 
```
        $ordersCartRuleCollection = new PrestaShopCollection('OrderCartRule');
        $ordersCartRuleCollection->join('Order');
       echo $ordersCartRuleCollection->getAll(true);
```

Behavior waits is : 
`SELECT * FROM `ps_order_cart_rule` a1 LEFT JOIN `ps_orders` `a0` ON (a1.`id_order` = a0.`id_order`) `
Actual Result : 
Error 500 with  Association Order not found for class OrderCartRule at line 541 in file classes/PrestaShopCollection.php

**Additionnal information**
PrestaShop version: 1.6.1.x (tested on 1.6.1.4 and 1.6.1.22)
PHP version: Not Related

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

Have you the same issue with the last version 1.7.4.3?
Where can I put the code that you provided to us?

Thanks!

**Comment by azerttyu** [comment]
Hello

I don't use 1.7.x then I can't test it. I don't know if PrestashopCollection is used again in last version. But if you provide a test instance I can test my module (where I use this behavior) and check it

**Comment by camlafit** [comment]
Hello

I don't use 1.7.x then I can't test it. I don't know if PrestashopCollection is used again in last version. But if you provide a test instance I can test my module (where I use this behavior) and check it

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

Could you please provide me your custome module to test it with PS1.7.4.3.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks

**Comment by camlafit** [comment]
Hello

Thanks a lot, archive send by mail.

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
if your bug isn’t critical or a security issue, it can not be fixed.
We need to check if that error exists for the 1.7, so we can add your fix to the 1.7 version.
But your module is not compatible with PS1.7, so I can not test it.
Thanks!

**Comment by camlafit** [comment]
Hello

This bug looks more critical than some bugfixes published in last 1.6.x releases. 
As 1.6 support has been extended I propose a patch related to a real bug.

As yet said I don't/can't use 1.7 version maybe you can change compliant version to test module.

**Comment by khouloudbelguith** [comment]
Hi @camlafit, 

In the wb_exporterorder.php file, I updated the version compatibility:  `$this->ps_versions_compliancy = array('min' => '1.6', 'max' => '1.7.4.3');`
But, I did not manage to upload this module
![image](https://user-images.githubusercontent.com/16067358/47362550-ebaa0880-d6d4-11e8-9483-efee9d580480.png)
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @marionf, what do you think of this issue?
The issue occurs in the 1.6 & @camlafit can't test the module with 1.7.
He create a PR: https://github.com/PrestaShop/PrestaShop/pull/11120 to fix the issue.
Thanks!

**Comment by marionf** [comment]
@eternoendless do you think this bug is critical for 1.6 ?
We need to know if this bug happens also in 1.7 if you can take a look ?

**Comment by eternoendless** [comment]
Hi @camlafit 

This is not a bug per se, but rather you seem to be trying to use an unsupported feature of an undocumented class. Basically, the `OrderCartRule` model has no declared association with the `Order` model, so it will never be able to infer it on its own.

My advice is to try and avoid `PrestaShopCollection` it altogether. The whole ObjectModel stack is being deprecated in 1.7 and will probably be removed in 1.8.

**Comment by alisamie97** [comment]
> This is not a bug per se, but rather you seem to be trying to use an unsupported feature of an undocumented class. Basically, the `OrderCartRule` model has no declared association with the `Order` model, so it will never be able to infer it on its own.

Let me show you something documented that does not work.

As a developer, I search for this phrase in Google: "PrestaShopCollection join example" and for sure there is no example because PS is kind of dead.

Then I find the OFFICIAL documents:
https://devdocs.prestashop-project.org/8/development/components/database/prestashopcollection/#joining-to-associated-entities-join

Here is the OFFICIAL example:
```
$productCollection = new PrestaShopCollection('Product');
$productCollection->join('categories', 'id_category');
```

You are wondering what could be the result? That's simple, it does not work and raises some exceptions.
