### ISSUE TITLE
incorrect shipping cost calculation when paying with PayPal

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#11127]
![2018-10-23 13-37-48 andre s shop](https://user-images.githubusercontent.com/11665990/47357102-89e6a000-d6ce-11e8-894f-9ef471709112.png)
![2018-10-23 13-37-19 paypal - -](https://user-images.githubusercontent.com/11665990/47357112-92d77180-d6ce-11e8-9e31-764bfcd77010.png)
My PayPal configuration
![2018-10-23 14-20-52 modules services andre s shop](https://user-images.githubusercontent.com/11665990/47357306-fc578000-d6ce-11e8-8169-190efcb4b7b3.png)
**Describe the bug**
Having multiple currencies enabled in the shop get totally incorrect shipping cost calculation with PayPal. 

**To Reproduce**
Back-end steps:
1. Go to Improve-International-Localisation-Currencies and add/enable Russian Ruble and US Dollar. UPDATE EXCHANGE RATES.
2. Go to Improve-International-Localisation and set Default currency = Russian Ruble
3. Go to Improve-Payment-Preferences and set CURRENCY RESTRICTIONS for PayPal=Shop default currency.

Front-end steps:
1) Select US$ as a currency
2) Add an item with shipping required to the cart. See the correct price in US$
3) Try to pay with PayPal and see the correct price in Rubles for the goods, but crazy high price for shipping. Looks like the shipping price is multiplied by current exchange rate one extra time more.

**Additional information**
Prestashop version 1.7.4.3. Module PayPal v4.3.3 - by PrestaShop
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

Have you tried to contact the Paypal module author about this issue?
You can contact the developer of this module here: https://www.202-ecommerce.com/en/partners-modules/technical-support/
Thanks to check & feedback.

**Comment by AndreyOgleznev** [comment]
Hi, 
OK, I've sent the same request over there, looking forward for the answer.

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

Thanks!
Waiting for the feedback.

**Comment by AndreyOgleznev** [comment]
Hi guys,
by manual updating PayPal module to its latest version 4.4.2 the shipping cost calculation error was minimized to an acceptable level. 
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

Thanks for your feedback.
Feel free  to open a new one when needed.
Thanks!
