### ISSUE TITLE
Module Manager : Built in modules are not sorted out in Addons categories

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/PrestaShop#11124]
**Describe the bug**
On Module Manager page, some built in modules are well sorted in Addons categories (because the Addons product sheet is active) though most of them are sorted in "Built-in module" category. This category should not appear anymore in Module manager and all modules (even built in modules) must be sorted in Addons categories. Renaud changed Addons API so that Addons categories are sent.
http://api.addons.prestashop.com/?version=1.7.5.0&iso_lang=pl&iso_code=de&shop_url=www.gastrodomus.it&mail=info@gastrodomus.it&format=json&method=listing&action=native&

**To Reproduce**
Go to Module manager : Lots of built in modules are sorted out in "Built in modules" category = Catégorie Natif

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
In progress with #11070
