### ISSUE TITLE
/src/Core/Cldr/Composer/Hook.php: What 'cd -' is supposed to do ? 

### ISSUE THREAD

**Issue by FVolral** [PrestaShop/PrestaShop#11129]
**Describe the bug**
In `/src/Core/Cldr/Composer/Hook.php`. There is the line:
`exec("cd $cldrFolder && unzip -oqq $cldrFilePath -d .. && cd -");`

`cd -` Works for linux but not for Windows. 

**Additionnal information**
PrestaShop version: 1.7.0
PHP version: 7.2 x86
Windows 7 SP1 64bit

**Comment by khouloudbelguith** [comment]
Hi @FVolral,

No, cd works also in Windows.
![image](https://user-images.githubusercontent.com/16067358/47419023-9c6ae300-d77b-11e8-9f1a-97382fafbf15.png)
Also, you can follow this [forum](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cd)
Thanks to check & feedback.

PS: PR: https://github.com/PrestaShop/PrestaShop/pull/8719

**Comment by khouloudbelguith** [comment]
Hi @FVolral,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
