### ISSUE TITLE
Problems in the admin side on the bottom toolbar of product pages under 1039px

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11130]
Hi
if you go in a product page in the back office
try to resize the borwser's width under 1039px you will see the the bottom toolbar will not be full size
it should have ad width of 100% because the lateral menu is not visible

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/47393476-e625e000-d71f-11e8-89e3-d41d0a45de89.png)
![2](https://user-images.githubusercontent.com/653230/47393477-e625e000-d71f-11e8-85c4-8fcc4d5c3a9d.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7

bye

**Comment by dineshbadrukhiya** [comment]
Hello, @maofree 
This is bug in PrestaShop. To fix it Go to: **admin folder > themes > new-theme > public > theme.css**
At line 364, add below css.
` .page-sidebar-closed .product-page .product-footer{left: 3.125rem;}`

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by dineshbadrukhiya** [comment]
Hello, @khouloudbelguith 

I want to open pull request on my code suggestion but right now I have already opened one pull request https://github.com/PrestaShop/PrestaShop/pull/11133 and I don't know how to open new pull request and manage both the commits at same time on Github desktop. Can you help me for the same?

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

You need to create another branch "fix-11130" for example, you should make changes on this branch then you can create a new PR.
Thanks!

**Comment by dineshbadrukhiya** [comment]
Hi @khouloudbelguith 
Thanks for quick reply. I will try it.

**Comment by dbadrukhiya** [comment]
Hello @khouloudbelguith ,
 I have created new branck on Github Desktop dineshbadrukhiya. After making changes tried to open new pull request but not able to open new pull request. Can you help me?

![github](https://user-images.githubusercontent.com/40850057/47418183-3c823580-d797-11e8-8843-33b5a50895f0.png)
