### ISSUE TITLE
Transplant  a module doesn't work

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11146]
**Describe the bug**
When we try to transplant a module "Banner" par example, clicking on "save" button has no affects => it just refresh the Positions page.

**To Reproduce**
1. Go to BO => Design => Positions
2. Click on 'Transplant a module' => you are redirected to a "TRANSPLANT A MODULE" page 
3. Select the Banner module
4. Transplant to "displayLeftColumnProduct"
5. Click on save
6. The green alert "The module transplanted successfully to the hook." is not displayed
7. In the position page, select the "Banner" to show positions, you will see that the "Banner" module is not transplanted to displayLeftColumnProduct
![image](https://user-images.githubusercontent.com/16067358/47441258-07cea800-d7b0-11e8-873d-d9a4783c7482.png)

**Screenshots**
https://drive.google.com/file/d/1pTXao2299bqqGiRNkMiE3Jryg0od0K6C/view

**Additionnal information**
PrestaShop version: 1.7.5.0-build1 beta2
PHP version: 7.1

**Comment by marionf** [comment]
Maybe related to #11152
