### ISSUE TITLE
After the redirection to the home page, the language by default is changed from es to en

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11141]
**Describe the bug**
After the redirection to the home page from the product page, the language by default is changed from es to en

**To Reproduce**
1. Fresh install 1750 build1 beta2 (English language / french country)
2. Go to BO => International => Localization => Import the Spain pack
3. Go to the FO
4. Change the language to "es"
5. Go to a product page
6. Click on the "My store" logo => you are redirected to the home page & the language is changed to "en"

**Screenshots**
https://drive.google.com/file/d/1I7fOS4Kq5vMlR2mf6JfeM-Z7fRBAg5Qx/view

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by mickaelandrieu** [comment]
Hello, I'm on it.

**Comment by mickaelandrieu** [comment]
Hello @khouloudbelguith, I need help to write e2e tests: how can I start?

**Comment by khouloudbelguith** [comment]
ping @fatmaBouchekoua what do you think?
Thanks!

**Comment by fatmaBouchekoua** [comment]
Hello @mickaelandrieu ,
We are developing e2e tests on created PR in this repository https://github.com/mbadrani/geppetto with puppeteer. We don't have documentation yet but you can refer to the Puppeteer's Api docs https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md# 
You can write your test under `geppetto/test/mocha/campaigns/PR`, and you can take a look at tests that are scripted in this directory.
For any other information you can contact me, that would be a pleasure to help you.
Thanks!
