### ISSUE TITLE
if your back office email is capitalized but your email on profile.prestashop.com is not, the back office takes a full minute to finish loading

### ISSUE THREAD

**Issue by DavidEschmeyer** [PrestaShop/PrestaShop#11145]
**Describe the bug**
1.7
if your back office email is capitalized but your email on profile.prestashop.com is not or vice versa, the back office takes a full minute to finish loading

http://profile.prestashop.com/support-usa%40prestashop.com.jpg
vs
http://profile.prestashop.com/Support-usa%40prestashop.com.jpg

**To Reproduce**
1. if your picture on prestashop is bound to lowercase email... then in the store make account with capitalized email.  Log in and page takes forever to finish loading.

**Additionnal information**
PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment]
Hi @dave-ps,

Same issue with PS 1750beta1build2.
1- Back office email is capitalized but the email on profile.prestashop.com is not 
https://drive.google.com/file/d/1YElWF-OBNdpHl_OCLmNnWpRyfMytZs8j/view
2- Back office email is the same email on profile.prestashop.com
https://drive.google.com/file/d/1Tx_HGVIC4JoxbwU1sC--Ux0rFbdM9vBG/view

Thanks!

**Comment by rdy4ever** [comment]
I really think calls to profile.prestashop.com should be handled by ajax whithout impacting the BO loading time. We should not have this kind of SPOF's in the BO.

**Comment by Hlavtox** [comment]
Profile image cannot be fetched from profile.prestashop.com anymore - fixed.
