### ISSUE TITLE
PS 1.7.4.3 Encoding bug

### ISSUE THREAD

**Issue by dreamtheme** [PrestaShop/PrestaShop#11155]
**Describe the bug**
During a PS installation transfer between two servers, i noticed a bug with the encoding. So i decided that maybe my PS is corrupted or something. So i did a clean PS 1.7.4.3 installation and i have added "Bulgarian" language and nothing else. All databases and connections set to UTF8. Database is transferred via PHPMyAdmin
On server 1 (original installation) with two languages, English and Bulgarian (Cyrillic) everything works perfect.
On server 2 (new destination) the Bulgarian (Cyrillic) is broken. I did this several times with different collations but the result is always the same. 
On the destination server, if i delete the Bulgarian language and add it again seems to be working correctly. 
In the DB the Cyrillic are displayed correctly, but for some reason PrestaShop is not displaying them in UTF but in Windows-1251

If i edit the Cyrillic in the database (where it is displayed correctly) it become scrambled in PS and vice versa, if i edit it in PS admin and it is displayed correctly in PS admin, it become scrambled in Database.

**To Reproduce**
1. Install PS 1.7.4.3 with English by default and then add  Bulgarian (Cyrillic) localization pack.
2. Transfer the PS installation from one server to another. (change parameters.php and PS_SHOP_URL for new server).

**Screenshots**
![pic1](https://user-images.githubusercontent.com/17176009/47505602-1fbd2f00-d877-11e8-9cc4-e127b67f752e.JPG)

![pic2](https://user-images.githubusercontent.com/17176009/47505609-2350b600-d877-11e8-8e77-9ff28557e821.JPG)

![pic3](https://user-images.githubusercontent.com/17176009/47505617-25b31000-d877-11e8-86ac-f719cec7c877.JPG)

![pic4](https://user-images.githubusercontent.com/17176009/47505621-277cd380-d877-11e8-9864-0af373774243.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 5.6, 7.0, 7.1 (tested on those three PHP versions)

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

I did not manage to reproduce the issue with the last version 1.7.4.3.

1. I installed PS 1.7.4.3 with English by default and then I added Bulgarian localization pack.
2. I exported the Database.
3. I changed the server
4. I created a new Database on the new server with utf8_general_ci encoding, I imported the database.
5. I edited the parameters.php and PS_SHOP_URL for the new server
6. I deleted the cache manually ( by deleting all the folder into var/cache (prod & dev).

Everything is Ok.
Thanks to check & feedback.

**Comment by dreamtheme** [comment]
Hi @khouloudbelguith 
I could not reproduce it on my local machine too, only happens on hosting provider and I'm already talking with them to see where the issue is coming from, is it some hosting setting or something in PrestaShop.
On the server i manage to do it without any transfers of installations, just installed Prestashop clean, added Bulgarian and the issue is there.
![pic4](https://user-images.githubusercontent.com/17176009/47515904-b7794800-d88c-11e8-8b9b-403b4c0c546c.JPG)

 (Although i have older versions PrestaShop 1.7.3.x on the same hosting without this issue.)
I will do some more testing, and wait for the hosting admin to look deeper into the issue and will get back.

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

Since you did not manage to reproduce the issue on your local.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks to check with the host provider & feedback.

**Comment by dreamtheme** [comment]
I just spoke with the sys admin of the hosting provider, he explained that by default this server "SET NAMES" are not set to UTF8 and while is strange how old installations worked without an issue, they transferred our profile to a server with "SET NAMES" set to UTF8 by default and there is no issues there. 
Thanks for the help.

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

Thanks for your feedback.
Since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by ghost** [comment]
Noticed same issue. Migrated website loose whole translations. 
![Bez-nazwy-1](https://user-images.githubusercontent.com/8243273/64528162-1494b580-d308-11e9-80b5-224577dc687f.jpg)

Ech... to much work for me today..... Exported database have "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"

And imported database don't like this charset. So replace with "ENGINE=InnoDB DEFAULT CHARSET=utf8;" and will be just fine. Also all expressions of utf8mb4 to utf8.

**Comment by SharakPL** [comment]
@PrestaShark it's not the reason for this. You import database through phpmyadmin? From first page (top level, out of any database) you have access to Variables tab. There you should find variable `init_connect` if its value is `set names utf8` or empty (then it depends on other variables) then you can import your sql file properly, but if its value is for example `set names latin1` then you'll have problem like above.
