### ISSUE TITLE
Prestashop forum header

### ISSUE THREAD

**Issue by vlskrbek** [PrestaShop/PrestaShop#11158]
**Describe the bug**
Please who can repair the prestashop forum header? There is a bug with displaying of header that hide the right slider. It does not work in Firefox or in Chrome. On the other hand it works in IE. See the attached picture.

**To Reproduce**
1. open prestashop forum https://www.prestashop.com/forums/ in Chrome or in Firefox
2. Move or find the right slider
3. See the upper right corner, the header is hiding the slider

**Screenshots**
![prestashop forum header](https://user-images.githubusercontent.com/44057715/47525838-7e49d380-d89e-11e8-82f8-d5dbd82b501b.png)

**Additionnal information**
I used Chrome version Verze 69.0.3497.100 (Oficiální sestavení) (64bitový)
I used Firefox version 62.0.3 (64 bitů)
I used IE version 11.726.16299.0 (version of update 11.0.90

**Comment by khouloudbelguith** [comment]
Hi @vlskrbek,

We are currently testing our dev environment with the default theme. If everything is good, we will make a major upgrade of the forum (+ default theme) so these concerns will normally be resolved in the coming weeks :smile: 
Thanks for your understanding!

**Comment by vlskrbek** [comment]
Thanks for info. 
Best regards
