### ISSUE TITLE
Rollback the product canonical url

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#11150]
**Describe the bug.**
We need to rollback a modification we made for product canonical url. The actual canonical uses the default combination attribute, the problem is that if that default combination changes then the canonical will change which is bad for SEO.

**Solution**
The canonical of a product is its url without any combination id, this url is not accessible and redirects to the default combination but the canonical header keeps the `no-attribute` url.

**To reproduce**
Check in categories list that the product url doesn't include the combination, and in the product page that the canonical tag also has no combination.

**Comment by Rolige** [comment]
@jolelievre What strange, I have tested in a PS in the branch 1.7.5.x and have the same URL in the product list and product page, checked with the list of the home and category page.

**Comment by jolelievre** [comment]
yes the url itself stays the same, we only change the canonical meta tag in the product page
the modification that was previously done (use the default combination as canonical url) was a bad idea, because if you change the default combination then the canonical url changes which is not good for your SEO

**Comment by decom-media** [comment]
i understand the idea behind that change - but: is it really a good idea to have the canonical url not accessible and not indexable? in terms of SEO, as far as i did read i learned that this is not a good idea

**Comment by jolelievre** [comment]
@tom75 We fixed this quickly for `175` because the release date was close

In `1.7.6` we improved this behaviour, the "parent" product url (without attribute) is now accessible and no longer returns a redirect response, by default it displays the default combination
All the combinations urls are still accessible and keep their canonical to the "parent" url (which is now accessible) So we should have the best of both worlds
