### ISSUE TITLE
Bad SQL query PS 1.7.4.3 multishop Unknown column 'id_shop' in 'where clause'

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11159]
**Describe the bug**
I have a bug in my website in url without the slash in the end of the main category.

I get an fatal error when I remove the slash in the end of the main category.

- https://example.com/en/category/ _(ok)_
- https://example.com/en/category _(fatal error)_

` Fatal error: Uncaught Unknown column 'pl.id_shop' in 'where clause'<br /><br /><pre>SELECT `id_product` FROM `ps_product_lang` WHERE `link_rewrite` = 'cat1' AND `id_lang` = 1 AND pl.`id_shop` = 1 LIMIT 1</pre> thrown in /classes/db/Db.php on line 746 `

I posted on the forum, and a member said it's because a clean url module.

**But he said too, there is a problem with the SQL query of Prestashop.**
https://www.prestashop.com/forums/topic/912064-probleme-url-avec-et-sans-slash/?do=findComment&comment=2991656 (french)

So I post here not for my issue but for this SQL query.

`SELECT `id_product` FROM `ps_product_lang` WHERE `link_rewrite` = 'cat1' AND `id_lang` = 1 AND pl.`id_shop` = 1 LIMIT 1`

should be

`SELECT `id_product` FROM `ps_product_lang` WHERE `link_rewrite` = 'cat1' AND `id_lang` = 1 AND `id_shop` = 1 LIMIT 1`

or

`SELECT `id_product` FROM `ps_product_lang` pl WHERE `link_rewrite` = 'cat1' AND `id_lang` = 1 AND pl.`id_shop` = 1 LIMIT 1 `

**Additionnal information**
PrestaShop version: 1.7.4.3 multishop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

This SQL query is called on your module?
You need to search this expression in your project
![image](https://user-images.githubusercontent.com/16067358/47555992-91e05300-d90d-11e8-896e-481a3aa7736b.png)
It can be used in your module.
Thanks to check & feedback.

**Comment by BenTen** [comment]
Hello,
Sorry for the delay to reply.

In fact, only **/classes/Product.php** has that expression in my project.

**Comment by khouloudbelguith** [comment]
Hi @BenTen, 

In the /classes/Product.php, [first expression](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5482), [second expression](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5500), they are not the same displayed in your exception.
In your clean url module, did you use any request SQL `select` from the `ps_product_lang` table?
Thanks!

**Comment by BenTen** [comment]
I guess is in the file \override\classes\Dispatcher.php
```
    public static function isProductLink($short_link)
    {
//.....
                if (self::psversion() == 7)
                {
                    $sql = 'SELECT `id_product`
        			FROM `' . _DB_PREFIX_ . 'product_lang`
        			WHERE `link_rewrite` = \'' . str_replace('.html', '', $explode_product_link[$count - 1]) . '\' AND `id_lang` = ' . Context::getContext()->language->id;
                }
                else
                {
                    $sql = 'SELECT `id_product`
        			FROM `' . _DB_PREFIX_ . 'product_lang` pl
        			WHERE pl.`link_rewrite` = \'' . str_replace('.html', '', $explode_product_link[$count - 1]) . '\' AND pl.`id_lang` = ' . Context::getContext()->language->id;
                }
            }
            if (Shop::isFeatureActive() && Shop::getContext() == Shop::CONTEXT_SHOP)
            {
                $sql .= ' AND pl.`id_shop` = ' . (int)Shop::getContextShopID();
            }
//.....
```

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

The function isProductLink doesn't exist in the [Dispatcher class](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Dispatcher.php).
It is overridden by a custom module.
As it's not provided by Prestashop, we can't do anything with this.
I close the issue, feel free to open a new one when needed.
Thanks!
