### ISSUE TITLE
Max size of short description is equal to 0

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11164]
**Describe the bug**
When you set the Max size of the short description as 0 in BO => CONFIGURE => Shop Parameters => Product Settings, and try to save the product with (short description size > 800), an error message appears "This value is too long. It should have 800 characters or less."
In the manual is written: http://doc.prestashop.com/display/PS17/Product+Settings
" The short description, which appears in search engines and in the category description for your product, is limited to 400 characters by default, but this option enables you to change that limit. 0 means that there is no limit."

**To Reproduce**
1. Go to BO => CONFIGURE => Shop Parameters => Product Settings
2. Set the "Max size of short description" to 0 & SAVE
3. Go to the BO => Catalog => Product page => create a new product 
4. In the Summary, only 800 characters are allowed. => NOK
5. try to save the product with (short description size > 800), an error message appears.

PS: In the last version 1.7.4.3 is not allowed to set 0 in the Max size of the short description
**Screenshots**
https://drive.google.com/file/d/12OiTDVRxzCutPGrCaZzh6Fj3AaP1WXly/view

**Additionnal information**
PrestaShop version: 1.7.5.0 build1 beta2
PHP version: 7.1

**Comment by marionf** [comment]
2 options:
1) we put the behavior as in 1.7.4.3: impossible to insert 0, an error is displayed if I enter 0:  "The Maximum Size field of the Product Summary is invalid."
2) we allow to put 0 and as described in the doc, there is no limit for this field
This never worked, it was still limited to 800 chars in the product page (tested in 1.7.2.4)

As it's a regression compared to 1.7.4.3, I will say it would be good to put the behavior as in 1.7.4.3 and update the documentation

**Comment by jolelievre** [comment]
@marionf agreed, it doesn't make sense to allow infinite length for a short description even though it is allowed in the database

**Comment by jolelievre** [comment]
@marionf @khouloudbelguith The PR is pending and I already updated the doc:
http://doc.prestashop.com/display/PS17/Product+Settings
