### ISSUE TITLE
Cannot edit / add a new page in the BO => SEO & URLs page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11162]
**Describe the bug**
When we try to add / edit a page in the BO => Shop Parameters => Traffic & SEO, nothing happens
The new page is not added / a specific page is not updated. The Page SEO & URLs is just refreshed.

**To Reproduce**

1. Go to BO => Shop parameters > Traffic & SEO
2. Add a new page / Edit any page
3. Click on save
3. You are just redirected to the previous page (  SEO & URLs page) without any alert, the page is just refreshed => The new page is not added / a specific page is not updated

PS: 1.7.5.0 beta1 => NOK / 1.7.5.0 beta2 => NOK / Machine shuffle - Prestashop nightly => NOK

**Screenshots**
https://drive.google.com/file/d/1EplMB7-ZHK6GKhs0BPg_U7Crpsy5o9I_/view

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by marionf** [comment]
Maybe related to #11163

**Comment by khouloudbelguith** [comment]
Hi @jolelievre, @marionf,

In the 1.7.5.0 build4, when I create a new SEO page, the creation of the SEO page is OK, but the green alert is not displayed, as in the 1.7.4 / same issue with the edit action.
![image](https://user-images.githubusercontent.com/16067358/47924170-73ed9200-debb-11e8-95d8-0ff6d3bb4589.png)
Thanks!

**Comment by marionf** [comment]
Yes, I know, we talked about this wednesday and need to discuss to choose if we display the migrated page or the legacy one for 1.7.5.0 as this regression is minor

**Comment by khouloudbelguith** [comment]
Thanks @marionf !
