### ISSUE TITLE
Can't transplant a module

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11163]
**Describe the bug**
Can't transplant a module

**To Reproduce**
1. Go to Design > Positions
2. Click on Transplant a module
3. Select for example banner to displayfooter
4. Click on Save
5. Module isn't hooked

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by marionf** [comment]
Maybe related to #11152

**Comment by khouloudbelguith** [comment]
Hi @marionf,

This issue is duplicated of #11146
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11146
