### ISSUE TITLE
Strange behavior if put in the Min filter a character

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11167]
**Describe the bug**
In the BO => Catalog => Products page, when I put in the "Min" filter a character & click on search, this character will be automatically changed to "1000000" & the page is refreshed.
This strange behavior.
If we put a character in the "Max" filter & click on Search => The field will be displayed in **red** => this is the best behavior
Min filter => NOK
Max filter => OK

**To Reproduce**
1. Go to BO => Catalog => Products page
2. Put a character in any Min filter
3. Click on Search
4. See error ( this character is changed to "1000000"), it is not the same behavior when we put a character in the Max field.

**Screenshots**
https://drive.google.com/file/d/1mC4KNu3iigpt0FZ-swTu2Bo4C-HdhbWo/view

**Additionnal information**
PrestaShop version: 1.7.4.3 / 1.7.5.0
PHP version: 7.1

**Comment by marionf** [comment]
It changes for 1000000 only with Google Chrome
It doesn't happen with Firefox.
For all browsers, the min field should be displayed in red like the max field if we don't insert a number

**Comment by MatShir** [comment]
Seems to be fixed on the new product page :)
