### ISSUE TITLE
Fixed the getTaxesRate of carrier.php

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11180]
Hi
the method getTaxesRate of classes/carrier.php has a but, in my case I get in all sites everytime the zero value (in ajax cycles).
you should use the same solution used for the same method in product.php
the function become so:

```
    public function getTaxesRate(Address $address = null)
    {
        if (!$address || !$address->id_country) {
            $address = Address::initialize();
        }
    
        $tax_calculator = $this->getTaxCalculator($address);

        return $tax_calculator->getTotalRate();
    }
```

you have missed this condition:
```
        if (!$address || !$address->id_country) {
            $address = Address::initialize();
        }
```

![1](https://user-images.githubusercontent.com/653230/47679800-625b7000-dbc5-11e8-802f-8d12161404ae.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0

the same problem is on the 1.6.x

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
Yes, the method getTaxesRate doesn't use the same condition in [carrier.php](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Carrier.php#L1291) & [product.php](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5674).
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Maofree** [comment]
HI @khouloudbelguith 
can you do it for me?
thanks

sorry I continue to be too much busy :)
bye

**Comment by matks** [comment]
I'll do it :)

**Comment by matks** [comment]
Here you go https://github.com/PrestaShop/PrestaShop/pull/11185
