### ISSUE TITLE
a11y: checkboxes on module page aren't actual inputs

### ISSUE THREAD

**Issue by firstred** [PrestaShop/PrestaShop#11181]
![screenshot from 2018-10-29 22-40-43](https://user-images.githubusercontent.com/6775736/47682138-c4b76f00-dbcb-11e8-9a3b-917049d3d05a.png)

I would recommend to apply the same styling to a regular checkbox input. The current implementation is very bad for a11y.
Don't forget to set `box-sizing` to `border-box` for consistent cross-browser behavior.

**Comment by khouloudbelguith** [comment]
Hi @firstred,

Thanks for your report.
In the PS v 1.7.5.0 > Modules / Module Manager page, checkboxes aren't also actual inputs.
@eternoendless, @PierreRambaud, @PrestaShop/prestashop-core-developers what do you think of his suggestion.
Thanks!

**Comment by firstred** [comment]
Has it become part of the Presta UI Kit maybe? Might be easiest to create an alternative style if so.

BTW, I also can't find any attached data attributes. If we were to use jQuery for example how would we read the value? The regular `$('#checkbox').is(':checked')` call doesn't return the actual value any longer. I can imagine this is really confusing for both internal and external developers.

**Comment by firstred** [comment]
Ahh, nvm. They are inputs, but focus is not visible and there's no tabindex set, so I cannot access the inputs by pressing tab all throughout the page. So this is an entirely different issue. Closing for now.
