### ISSUE TITLE
Addresses changes not impacted when creating an order from another order

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#11199]
**Describe the bug**
In backoffice, on order X, When you change delivery or invoice address, if you create an order Y from order X, the addresses modification are not impacted.

**To Reproduce**
1. Go to an order
2. Change delivery or invoice address
3. Create a new order based on previous order
4. See that the suggested addresses are wrong

PrestaShop version: 1.6, 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.3.
Thanks for the fix.

**Comment by ntiepresta** [comment]
@jf-viguier,
Could you please provide us with more info? or a video record. We need more details to understand how we can reproduce your issue:
    - host
    - server setup and configuration
    - debug mode report /, unfortunately, doesn't exist
    - PHP error logs
    - apache error log
    - javascript console log
    - screenshots. 

Thanks.

**Comment by jf-viguier** [comment]
You don't need all of this to reproduce the error 
- Go to an order on the backoffice
- Change delivery or invoice address
- Create a new order based on previous order
- See that the suggested addresses are wrong

**Comment by ntiepresta** [comment]
@jf-viguier 
I don't know if we managed to reproduce this  error like you. I asked you provide us with more info for to be sure. Please could you provide us a video record for we can confirm your issue. 
I attached a video record. 
https://drive.google.com/file/d/1XMSbU58LzIWkuIEUMg_o4xBbdHKjPYGB/view?usp=sharing

If we manage to reproduce this error like you,  your fix (#11201)  does not correct the problem

Thanks

**Comment by jf-viguier** [comment]
I've seen your video : the adresseeeee is not selected by defaut : that's the bug.
I've made 2 pull requests for this bug, here is the other one that fix the bug in the video https://github.com/PrestaShop/PrestaShop/pull/11200/commits/87c68ceb97e7e5c756dd0f397ad6404ecdb15638

**Comment by ntiepresta** [comment]
@jf-viguier 
thanks for you reply.
Your pull request  87c68ce , well resolves the bug in the video.
I attached a video record.
https://drive.google.com/file/d/1xyRYUJWgAKkZp7lLp7ccQceIpt-ox3_m/view?usp=sharing

Thanks

**Comment by jf-viguier** [comment]
ok, I'm happy to contribute.
