### ISSUE TITLE
ps_wirepayment Fatal error at line 1035 in file classes/Tools.php

### ISSUE THREAD

**Issue by giorgiosks** [PrestaShop/PrestaShop#11197]
When i want pay witch wirepayment:

```
[PrestaShopException]
Fatal error
at line 1035 in file classes/Tools.php

1030.     * @param bool $htmlentities By default at true for parsing error message with htmlentities
1031.     */
1032.     public static function displayError($string = 'Fatal error', $htmlentities = true, Context $context = null)
1033.     {
1034.         if (defined('_PS_MODE_DEV_') && _PS_MODE_DEV_) {
1035.             throw new PrestaShopException($string);
1036.         } else if ('Fatal error' !== $string) {
1037.             return $string;
1038.         }
1039. 
1040.         return Context::getContext()->getTranslator()->trans('Fatal error', array(), 'Admin.Notifications.Error');
ToolsCore::displayError - [line 244 - classes/PaymentModule.php]
PaymentModuleCore->validateOrder - [line 64 - modules/ps_wirepayment/controllers/front/validation.php] - [9 Arguments]
Ps_WirepaymentValidationModuleFrontController->postProcess - [line 244 - classes/controller/Controller.php]
ControllerCore->run - [line 428 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]
```

**Comment by khouloudbelguith** [comment]
Hi @giorgiosks,

Could you please try to re-install the Ps_Wirepayment module.
Thanks to check and feedback.

**Comment by giorgiosks** [comment]
I did it and continue error.

**Comment by khouloudbelguith** [comment]
Hi @giorgiosks,

What is the exact version PrestaShop did you use? the exact version of the ps_wirepayment module did you installed?
Thanks!

**Comment by giorgiosks** [comment]
PrestaShop: 1.7.4.2
Wirepayment: v2.0.4

**Comment by khouloudbelguith** [comment]
@giorgiosks, after re-installing the module, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by giorgiosks** [comment]
To try i deshability cache and force compilate templates in configuration. I have deleted that folders and reinstall the module but continue the same error. 

SOLVED: I removed the folder modules/ps_wirepayment and put the new module from prestashop.zip and now working. THANKS FOR ALL @khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi @giorgiosks,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by fixo94** [comment]
It's a token security problem.
If you are connected as a user with a module (connect as user), you can have this problem.
Just change the password of your user, logout, login and have fun.
