### ISSUE TITLE
Error to upgrade modules due from missing PEAR.php

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11203]
Hi
after an upgrade from 1.6.1.22 to 1.7.4.3 all was ok but now I get this problem to upgrade some default Prestashop's modules like statsvisits v1.6.1 to v2.0.2
this happens in debug mode, if it is disabled all is ok
I've already removed the cache's folders of /var/cahce/

**Screenshots**
![2](https://user-images.githubusercontent.com/653230/47744782-7add9000-dc82-11e8-99b7-7b17533f380d.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

The statsvisits v1.6.1 is not compatible with 1.7.4.3.
Could you please try to re-install it.
So you can delete the statsvisits folder inti Project_Folder/modules/, then you need to install the latest version.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
