### ISSUE TITLE
Faceted filter doesn't shows attribute selection if category have only one product with same attribute or feature.

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11207]
When Category have only one product with same attribute or feature, It doesn't shows filter option with that attribute or feature on left-column. It's necessary to show filter option if at least one product have same attribute or feature.

**To Reproduce**
1. Add product **B** in the category **A** and assign it feature or attribute **C**.
2. Now, Go to Faceted Filters module > Configure > Filter Template > Edit.
3. Enable faceted filter option for Feature or Attribute **C**.
4. Open front-office and Category page of category **A**. Filter option of Feature or Attribute **C** will not be shown. If you assign same feature or attribute for another one product then it will be show.

**To Fix it**
1. Go to: `modules\ps_facetedsearch\src\Ps_FacetedsearchProductSearchProvider.php`

Replace the below code in line 288:
`$usefulFiltersCount > 1`

Update it to,
`$usefulFiltersCount >= 1`

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1.17

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya, 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/ps_facetedsearch
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

Thanks for the quick fix: https://github.com/PrestaShop/ps_facetedsearch/pull/47

**Comment by khouloudbelguith** [comment]
We can close this issue if your PR is merged.
Thanks!

**Comment by dineshbadrukhiya** [comment]
Sorry by mistake I have closed this issue. Thanks for reopening @khouloudbelguith .

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith What's the status?

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya, your PR should be reviewed by our developers.
Thanks!

**Comment by PierreRambaud** [comment]
Can't reproduce on the latest version :thinking:

**Comment by khouloudbelguith** [comment]
@PierreRambaud, I have the same issue with PS1.7.6.0beta1 & PS1.7.5.2 & ps_facetedsearch v3.0.5.
In fact in this category created we have only this product
![image](https://user-images.githubusercontent.com/16067358/59865106-28232680-9380-11e9-9ee3-e5c7cfc2232a.png)

There is no filter displayed
I created a second product with the same feature, but with a different value
![image](https://user-images.githubusercontent.com/16067358/59865213-6c162b80-9380-11e9-9e7f-1be5249b5ff9.png)

It is displayed.
If we create a product with the same feature & with the same value => there is no filter => we have more than one product & filter is not displayed too
https://drive.google.com/file/d/1TQN7YpitXbK5baFIAHEb37CbtNqbLOHH/view
Thanks!

**Comment by PierreRambaud** [comment]
Is it really an issue? It's actually a desired behavior in the code, why displaying a facet with only one product behind? :thinking: 
Ping @colinegin

**Comment by Hlavtox** [comment]
Whats the point of showing the filter if there is only one product?

**Comment by colinegin** [comment]
Hello @dineshbadrukhiya ,

I agree with @PierreRambaud and @Hlavtox, why do you need to display filters if there is only one product in the listing ?

**Comment by dineshbadrukhiya** [comment]
Hello @colinegin 
I agree with the @PierreRambaud as there is also no need of it. 
Sorry for the same.

**Comment by marionf** [comment]
Thank you for your answer @dineshbadrukhiya 

I close this issue

**Comment by abramofranchetti** [comment]
> When Category have only one product with same attribute or feature, It doesn't shows filter option with that attribute or feature on left-column. It's necessary to show filter option if at least one product have same attribute or feature.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Add product **B** in the category **A** and assign it feature or attribute **C**.
> 2. Now, Go to Faceted Filters module > Configure > Filter Template > Edit.
> 3. Enable faceted filter option for Feature or Attribute **C**.
> 4. Open front-office and Category page of category **A**. Filter option of Feature or Attribute **C** will not be shown. If you assign same feature or attribute for another one product then it will be show.
> 
> **To Fix it**
> 
> 1. Go to: `modules\ps_facetedsearch\src\Ps_FacetedsearchProductSearchProvider.php`
> 
> Replace the below code in line 288:
> `$usefulFiltersCount > 1`
> 
> Update it to,
> `$usefulFiltersCount >= 1`
> 
> **Additionnal information**
> PrestaShop version: 1.7.4.3
> PHP version: 7.1.17

There is another case,
when you have a feature with only one feature_value the filter doesnt show.

Whit the mod above all works.

**Comment by Hlavtox** [comment]
@abramofranchetti Once again, why the feature need to be displayed, when user selects only one option?

Maybe I am missing something. ❓

**Comment by abramofranchetti** [comment]
Not all products have this feature set. If I want to select only the products with the feature setted i have to see the filter. Dott. Franchetti Da: Daniel HlavacekInviato: venerdì 6 marzo 2020 13:03A: PrestaShop/PrestaShopCc: abramofranchetti; MentionOggetto: Re: [PrestaShop/PrestaShop] Faceted filter doesn't shows attribute selection if category have only one product with same attribute or feature. (#11207) @abramofranchetti Once again, why the feature need to be displayed, when user selects only one option?Maybe I am missing something. ❓—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by diggaoPiri** [comment]
Solution working on PS 8.1.5, thanks a lot!
