### ISSUE TITLE
Can't navigate between pages if frendly URL is disabled

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11208]
**Describe the bug**
Can't navigate between pages if frendly URL is disabled

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Disable frendly URL
3. Go to FO and click on all products link
4. Click on Page "2" or "Next"
5. You stay on the same page

The URL is 
http://localhost/prestashop_1.7.4.4-rc1/index.php?controller=category&id_category=2&id_lang=1&page=2

instead of 
http://localhost/prestashop_1.7.4.4-rc1/index.php?id_category=2&controller=category&id_lang=1&page=2

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
This will be fixed on 1.7.5.0 with https://github.com/PrestaShop/PrestaShop/pull/9214

**Comment by marionf** [comment]
I don't have it on 1.7.4.3 🤔

**Comment by marionf** [comment]
Humm in fact it happens when debug mode is enabled when debug mode is disabled it works

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Related to this issue: #9639
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9214
