### ISSUE TITLE
Font color should be consistence and visible in description tab of "Hummingbird_printed_t-shirt" in demo data.

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11211]
**Describe the bug**

**To Reproduce**
1. Go to '[Hummingbird_printed_t-shirt](http://fo.demo.prestashop.com/en/men/1-1-hummingbird-printed-t-shirt.html#/1-size-s/8-color-white)'
2. See the description tab.

**Screenshots**
![hummingbird](https://user-images.githubusercontent.com/40850057/47785472-df562900-dd2e-11e8-8188-0416ab0e9370.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

Thanks for your report & your fix.
This issue exists in the 1.7.5.0 also.

**Comment by dineshbadrukhiya** [comment]
Hello @khouloudbelguith 
There is Code Freeze for 1.7.5.0 and I don't know how to reference it for 1.7.5.0.

**Comment by khouloudbelguith** [comment]
Hi @marionf, what do you think, it should be added to the 1.7.5.?
Thanks!

**Comment by marionf** [comment]
This issue exists before 1.7.5.0, so no because we are in code freeze and we fixe only regressions of 1.7.5.0
