### ISSUE TITLE
It is impossible to filter by position in the Attributes & Features page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11217]
**Describe the bug**
In the Attributes & Features page, when we try to filter by position, the result is incorrect.

**To Reproduce**
1. Go to BO => Catalog  => Attributes & Features page ( Attributes page OR Features page: same behavior)
2. You have at least more than one attribute
3. Filter by position
4. See the error, the result is incorrect

**Screenshots**
https://drive.google.com/file/d/1UAlSKWyT7ROJFysf4qMyGiHu43K3qVEp/view

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by marionf** [comment]
@matks do you think we can solve this one during the migration of the page ?

**Comment by khouloudbelguith** [comment]
The same issue exists in the BO => Catalog => Categories page.
https://drive.google.com/file/d/1FoarYYgPiGFkkm3u3NxkQGYqvvknhIn_/view

**Comment by khouloudbelguith** [comment]
The same issue exists in the BO => Design => Pages when we try to filter the list of categories by position.
https://drive.google.com/file/d/1T0P_jqUTJpAn0k_l4BGwobCK8arD8ei3/view

**Comment by marionf** [comment]
@khouloudbelguith 
Can you please create an issue by page ?

**Comment by matks** [comment]
Fixed during the migration ✔️  https://github.com/PrestaShop/PrestaShop/issues/10511
