### ISSUE TITLE
Watermark module

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/PrestaShop#11210]
[Watermark module ](https://github.com/PrestaShop/watermark): Protect images by watermark 

- [x] Allow to upload jpg, png as watermark (check this PR : https://github.com/PrestaShop/watermark/pull/15)
- [x] Update wording in the module 
- [x] [Addons block](https://github.com/PrestaShop/PrestaShop/issues/11402)

Here is the [ZIP](https://github.com/PrestaShop/watermark/tree/cfb848a8055ed26cc0242610b9ca1db0e23a284e)

**Comment by rblaurin** [comment]
WIP? ;)

**Comment by matks** [comment]
Hi @rblaurin this is very nice work you've done here, but in 2 weeks we reach Feature Freeze period for PS 1.7.6 so it's going to get some time before we can review as we have very little time remaining. Thank your for understanding 🙏

**Comment by rblaurin** [comment]
Sure! Thanks for the feedback 👍
