### ISSUE TITLE
Specific Price Display on Product Page = 0.  UNBELIEVABLE THAT THIS PROBLEM STILL EXISTS IN V1.6.1.22!!!

### ISSUE THREAD

**Issue by sector7digital** [PrestaShop/PrestaShop#11219]
**Describe the bug**
Add a specific price (leave base price ticked) like starting at 10 pieces and get a discount of 40%. 
The product page displays 0,00 as price as soon as the spec price range is met (10 pieces). 
This problem exists now since years and it's still not fixed. What is the problem?

**To Reproduce**
Install fresh 1.6.x version, add a product and set a spec price as written above (start at qty: 10; discount: n%)

PHP version: 1.6.1.x - 1.6.1.22

Seriously you have this problem since years and haven't noticed it yet???? Can't be, or you're just not testing any software changes which I can't believe either as you're even using github. so what is the fix???

**Comment by khouloudbelguith** [comment]
Hi @oliiix,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/8099 to solve the issue.
As there are too many changes in the theme, we can't merge this to prevent breaking other themes.
Thanks!
