### ISSUE TITLE
Improvement needs on hover of "Ok" button of source code modal on product page

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11216]
Improvement needs on hover of Ok button of source code modal on product page

**To Reproduce**
1. BO > Product Page > Summary/Description Tab
2. Click on 'Sorce code icon'
3. Try to hover on "Ok" button. Background-color changes to transparent which should not be.

To fix it, We need to apply below style.
`.mce-primary.mce-btn:focus, .mce-primary.mce-btn:hover {
    background-color: #005fb3 !important;
}`

**Screenshots**
![hover-issue](https://user-images.githubusercontent.com/40850057/47838394-46c6b400-ddd5-11e8-990f-df82869f20e0.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

Thanks for your report.
I manage to reproduce the issue with 1.7.4.3 / 1.7.5.0
![image](https://user-images.githubusercontent.com/16067358/47840411-787c5280-ddb6-11e8-8420-1928fa2b068c.png)
Thanks for the fix.

**Comment by dineshbadrukhiya** [comment]
Hi @khouloudbelguith 
Does I need to open PR for this?

**Comment by khouloudbelguith** [comment]
Hi @dbadrukhiya,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
If you have problems, I can create a PR for you.
Thanks!

**Comment by dineshbadrukhiya** [comment]
Thanks @khouloudbelguith . It will be great if you open a PR for me.

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith any update for PR?

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, I did not make a PR yet.
Thanks for your understanding.
Would you be willing to make a pull request on GitHub with your code suggestion?

**Comment by dineshbadrukhiya** [comment]
Okay Np @khouloudbelguith . I will open PR in a free time.

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, thanks for your fix.
