### ISSUE TITLE
Confusing german translation 

### ISSUE THREAD

**Issue by drlogout** [PrestaShop/PrestaShop#11213]
**Describe the bug**

Confusing german translation.
Availability and delivery are both translated with "Lieferzeit", see screenshot. The first and second occurrences of "Lieferzeit" should in my opinion be replaced with "Verfügbarkeit". I would have send a PR but only found the read only TranslationFiles repo.

**To Reproduce**
1. Go to "Shop-Einstellungen -> Artikel"

**Screenshots**

<img width="588" alt="screenshot 2018-10-31 at 15 57 11" src="https://user-images.githubusercontent.com/6132191/47797027-d745bb80-dd25-11e8-96da-f212427ad27f.png">

**Additionnal information**
PrestaShop version: 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @drlogout,

Thanks for your report.
In the product page, Shipping tab, `Lieferzeit` is displayed also.
![image](https://user-images.githubusercontent.com/16067358/47799102-e7f83080-dd29-11e8-8a7f-4aff66fcede4.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @drlogout,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
