### ISSUE TITLE
[PrestaShop] Fatal error in module Gamification

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#11224]
**Describe the bug**
I try to upgrade the prestashop default module (one click, gamification ecc...) before update to the latest release 1.6.1.22.
The procedure was blocked during the update and showed the following error:
"**[PrestaShop] Fatal error in module file :domain/modules/gamification/gamification.php:
syntax error, unexpected '.', expecting ',' or ';'**"

After that was impossible to access into the BO, the browser showed "http ERROR 500".
So I had to rename Gamification in _#Gamification, after that the access was available again.
But I still have the module disabled.

**To Reproduce**
1. Go to module page 
2. Choose update all modules
3. then I've got the error
4. rename the gamification module

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 5.5

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

What is the exact version of the gamification did you use.
A new version is released in the last few days: https://github.com/PrestaShop/gamification/releases
Thanks!

**Comment by ballashop** [comment]
Hi @khouloudbelguith,
how can I discover it?
Thanks for your support.

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

You find in the BO => Modules and services page, search for the gamification module & it should be displayed.
![image](https://user-images.githubusercontent.com/16067358/47865638-02e7a500-ddfd-11e8-8314-e8b4b57b2616.png)

Thanks!

**Comment by ballashop** [comment]
:) thanks, 
I put the backuped version because, the update one gove me a "http ERROR 500".
<img width="1066" alt="schermata 2018-11-01 alle 17 52 10" src="https://user-images.githubusercontent.com/28685316/47866433-08de8580-ddff-11e8-8b2f-29acda6d565d.png">
I downloaded the 2.2 version, I've just to copy files?
Or by the Zip file?
Thanks a  lot.

**Comment by khouloudbelguith** [comment]
@ballashop, if you enable the debug mode, is there any exception displayed?
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`
Thanks!

**Comment by ballashop** [comment]
@khouloudbelguith 

Warning: Invalid argument supplied for foreach() in 
path_domain/override/classes/Dispatcher.php on line 176

Warning: Invalid argument supplied for foreach() in 
path_domain/override/classes/Dispatcher.php on line 176

this is a problem that I have for some time and concerns a module "pretty url", the developer of the module told me that this error does not affect the operation of the site.
in fact I did an update in August, it was successful.
There are no other messages.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

Could you please try to uninstall this module "Gamification", delete the "gamification" folder from your Project_Folder/modules/ path, & try to re-install the latest version of this module, you can search it in the BO => Modules and services page.
Thanks to check & feedback.

**Comment by ballashop** [comment]
Hi @khouloudbelguith
of course, I do immediately thanks

**Comment by ballashop** [comment]
Hi, the module I found is the same version of the one previously installed, do I install anyway?
<img width="1185" alt="schermata 2018-11-02 alle 09 05 43" src="https://user-images.githubusercontent.com/28685316/47900885-bd6bbc00-de7e-11e8-93af-13f3aba1b1e8.png">
Thanks

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

The "gamification" module is updated.
![image](https://user-images.githubusercontent.com/16067358/47904638-abd9e280-de85-11e8-984f-eea08a247a14.png)
Did you delete the "gamification" folder from your Project_Folder/modules/ path?
Thanks!

**Comment by ballashop** [comment]
Hi @khouloudbelguith I found the gamification module and I installed it.
No error appeared and I work without problems within the BO.
Thanks a lot.

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
