### ISSUE TITLE
Mise a jour Click Upgrade bloqué

### ISSUE THREAD

**Issue by startech-france** [PrestaShop/PrestaShop#11222]
**Describe the bug**
Hello,
trying to update prestashop,
the update remains blocked.
1.7.4.2 ----> 1.7.4.3

**To Reproduce**
1. Go to Click Upgrade
2. Click on upgrade prestashop now
3. 5 min after block

**Screenshots**
![capture](https://user-images.githubusercontent.com/43042604/47861117-5ef8fc00-ddf2-11e8-9fbe-390b23a579ae.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
Hi @startech-france,

Could you please provide what is the exact version of the 1-click upgrade did you use?
Thanks!

**Comment by startech-france** [comment]
my prestashop 1.7.4.2

1-Click Upgrade 
v4.4.0 - par PrestaShop

**Comment by khouloudbelguith** [comment]
@startech-france, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by startech-france** [comment]
I can not find the log.txt file

![capturemodule](https://user-images.githubusercontent.com/43042604/47865749-4e9a4e80-ddfd-11e8-9add-7bbdf06f274a.PNG)

**Comment by khouloudbelguith** [comment]
Hi @startech-france,

you can find it in the Project_Folder/Admin_folder/autoupgrade/tmp path.
Thanks!

**Comment by startech-france** [comment]
log.txt
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2539406/log.txt)

**Comment by khouloudbelguith** [comment]
@startech-france, there is no error in your log file, it could be a server error.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @startech-france,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
The new version 4.5.1 of the 1-click upgrade is released
https://addons.prestashop.com/en/data-migration-backup/5496-.html
Thanks!
