### ISSUE TITLE
Logger::addLog does not log from from the front office

### ISSUE THREAD

**Issue by firstred** [PrestaShop/PrestaShop#11229]
**Describe the bug**
When you call `Logger::addLog` from the front office, it will not log anything. This worked on 1.6 and in the back office.

**To Reproduce**
Grab some module that hooks to the front office. Add `Logger::addLog('message');` to the code and notice how it won't land in the database.

**Screenshots**
N/A

**Additional information**
PrestaShop version: 1.7.5, likely more affected
PHP version: 7.1

**Comment by firstred** [comment]
The bug seems to be in the AdminLogs controller. It does not list every single log entry. I wonder why...

**Comment by firstred** [comment]
![screenshot from 2018-11-01 23-00-06](https://user-images.githubusercontent.com/6775736/47882469-e746c380-de29-11e8-8901-ed664769b833.png)

Huge gap in the listing. Yuuuuuge.
![](https://media.tenor.com/images/f865c67834547565f91c7de6a346f56a/tenor.gif)

**Comment by firstred** [comment]
It should not do an `INNER JOIN` on `id_employee`, but a `LEFT JOIN` instead.

**Comment by khouloudbelguith** [comment]
Hi @firstred,

Do you have a module calling the `Logger::addLog` from the front office? It will allow us to do the regression tests.
Thanks!

**Comment by firstred** [comment]
Here's a module you could try. It logs automatically from the front office and for the back office you should visit its configuration page.
[testlog.zip](https://github.com/PrestaShop/PrestaShop/files/2541887/testlog.zip)

Notice how it lands in the database:
![screenshot from 2018-11-02 10-38-03](https://user-images.githubusercontent.com/6775736/47907424-85b74100-de8b-11e8-94d4-7d12c21c19da.png)
but it is not visible on the logs page:
![screenshot from 2018-11-02 10-39-22](https://user-images.githubusercontent.com/6775736/47907464-9bc50180-de8b-11e8-9f3d-c91bfa14e6d0.png)

**Comment by khouloudbelguith** [comment]
@firstred, thanks for your report.
In the 1.7.4.3, it is OK.
![image](https://user-images.githubusercontent.com/16067358/47913058-f1ed7100-de9a-11e8-8034-8c24349322eb.png)
But in the 1.7.5.0, it is NOK, I manage to reproduce the issue.
In the DB, I have:
![image](https://user-images.githubusercontent.com/16067358/47913079-0f223f80-de9b-11e8-818f-89fdd7fdf823.png)
But in the logs page, the `Logger::addLog` does not log from the front office.
![image](https://user-images.githubusercontent.com/16067358/47913116-311bc200-de9b-11e8-8d8f-63061c5de465.png)
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by firstred** [comment]
Hi @khouloudbelguith 

Sorry, I don't have enough time to figure out how this page has been migrated to Symfony, so I am not able to update the query to make it work.

Maybe @mickaelandrieu can chime in on this one?
