### ISSUE TITLE
Order currency different from payment currency

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#11238]
**Describe the bug**
Having multiple currencies enabled in the shop and accepting payment only in one default shop currency the order is creating with a user selected currency, which makes a huge problem with online taxation in my country and some payments modules. I think the order must be created in the same currency as the payment accepted as that was in PS 1.6.

**To Reproduce**
Back-end steps:
1. Go to Improve-International-Localisation-Currencies and add/enable Russian Ruble and US Dollar. UPDATE EXCHANGE RATES.
2. Go to Improve-International-Localisation and set Default currency = Russian Ruble
3. Go to Improve-Payment-Preferences and set CURRENCY RESTRICTIONS for payment methods=Shop default currency.

Front-end steps:
1. Select US$ as a currency
2. Buy something in the shop.
3. In the Back-end see the order created in US$ despite of payment was made in rubles.

**Additional information**
Prestashop version 1.7.4.3. 
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

Have you the same issue described in this ticket: #9850?
Thanks!

**Comment by AndreyOgleznev** [comment]
Hi, 
Puh...there is something in common, but I'm not sure that's the same issue. 
I don't care about DB fields in this case, I care about business operations to be made right.

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

After following all the steps, in the BO => Orders => Order details, in the payment par,t, I found this  
![image](https://user-images.githubusercontent.com/16067358/47918377-bc518380-deac-11e8-8974-2757f7ef36a6.png)
I used the Cash on Delivery payment module.
What is the exact payment module did you use?

**Comment by AndreyOgleznev** [comment]
Great. Looks like you were able to reproduce the issue. Since the payment was in rubles, but not in US$, right?
I used PayPal module and some Russian bank module with the same result.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, no in FO I selected the $ as a currency, then I created the order.
But, in the BO => Order details, the $ currency is displayed & not the Russian Ruble.
Thanks!

**Comment by AndreyOgleznev** [comment]
In which currency was the payment made in your case?

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, with the  $ currency.
Thanks!

**Comment by AndreyOgleznev** [comment]
and what's the shop default currency in your case?

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, it is Russian Ruble.
![image](https://user-images.githubusercontent.com/16067358/47925005-60dbc180-debd-11e8-8aac-644e8d054a54.png)
Thanks!

**Comment by AndreyOgleznev** [comment]
If I set CURRENCY RESTRICTIONS for payment methods=Shop default currency (i.e. Russian rubles) I can make payment via PayPal only in Russian rubles. That makes a difference, right?

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, yes, it is a normal behavior.
In your case, the Shop default currency is Russian rubles.
Also, you set CURRENCY RESTRICTIONS for payment methods **Paypal** to Shop default currency.
So, with Paypal, you will be allowed to use the Russian rubles currency only to make an order with Paypal.
![image](https://user-images.githubusercontent.com/16067358/47926449-de550100-dec0-11e8-94c9-0668c53a3d96.png)

**Comment by AndreyOgleznev** [comment]
Yes, that's normal. 
But why the order is created with $ but not rubles in my case? I need it to be in rubles also for taxation.
And why you can pay with $ but not rubles in your case?

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, in the FO, you select the US$ as a currency.
If I use the Cash on Delivery payment module, So I can use all the currencies, they are all checked in the currencies restrictions.
Thanks!

**Comment by AndreyOgleznev** [comment]
>>If I use the Cash on Delivery payment module, So I can use all the currencies, they are all checked in the currencies restrictions.

But we are talking about CURRENCY RESTRICTIONS for payment methods=Shop default currency, not all the currencies.

Well, how can I get orders in Shop default currency no matter which currency was selected by the user?

**Comment by khouloudbelguith** [comment]
Hi @AndreyOgleznev,

Depending upon the payment, the customer's choice of currency can differ.
With the Payment Module Restrictions on Currencies, you can limit the choice of available payment methods depending on the available currencies.
Note that currency restrictions work in different ways depending on the payment module:

- For some, such as Cash on delivery, you cannot change their default setting.
- For others, such as Wire payment, Check Payment, Skrill, Ogone, etc., you can change any of their currency settings, except for the "Customer currency" and "Shop default currency", which stay at their default state.
- Then, for other modules such as Hipay or PayPal, you can change any of their currency settings, but you can choose only one option between "Customer currency" and "Shop default currency", not both.

For more details, you can follow our documentation: http://doc.prestashop.com/display/PS17/Payment+Preferences
Thanks to check & feedback.

**Comment by AndreyOgleznev** [comment]
Hi @khouloudbelguith , 
thank you. 
The problems is that in PS 1.7 I can't afford to enable more than one currency as I could in PS 1.6. Otherwise I get problems with taxation and some local banks payment modules. Unfortunately, your explanation doesn't solve the problem. For me it stays really weird thing that payment is made in one currency but the order in BO is in the other currency.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev,  you can't afford to enable more than one currency when you are using Paypal only?
If you are using the "Bank transfer" module or the "Payments by check" you can enable more than one currency in the Payment Module Restrictions on Currencies.

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith  Hmm, I suggest you don't quite understand my problem. I don't want to enable more than one currency in the Payment Module Restrictions on Currencies. I want the orders to be in one single currency, in rubles. That is the way it did work in PS 1.6 but I can't get it to work in PS 1.7.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, It will help us if you can attach a screen record.
In my case, the 1.6 / 1.7 have the same behavior, in the 1.6, orders are not done with a single currency.
Thanks!

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith Sure thing, please have look at last days of my PS 1.6 shop activity when I had multiple currencies enabled. I miss it now.
![orders ps1 6](https://user-images.githubusercontent.com/11665990/48002244-6c7cf180-e124-11e8-9b18-43a5ceadbf62.png)
![currencies ps1 6](https://user-images.githubusercontent.com/11665990/48002256-756dc300-e124-11e8-83c8-486e2e10d549.png)

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, with the PS1.6, if you try to use another payment module & another currency.
You will see that the order will not be done with a single currency.
Thanks to check & feedback.

**Comment by AndreyOgleznev** [comment]
Ahh, that's a pity. I think that would really solve my problems.
Looks like I will have to find some workaround or change the shop engine.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, 

Do you agree with me, that in the 1.6/1.7, orders are not done with a single currency?
Thanks!

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith 
I wouldn't say so. That's 50/50. In my PS 1.6 configuration the orders were done with the single currency and I can prove it. In your configuration that may be different if you say so.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, because you are using only the PayPal module, have you tried to check if you have the same behavior if you use another payment method, like cash on Delivery?
Thanks!

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith 
No, I haven't. That's out of my scope. 
I just want to be able to keep in my PS 1.7 what I had in PS 1.6 working fine.

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, in the Payment Preferences page, if you select the `Customer currency` option for Paypal, it will be ok?
![image](https://user-images.githubusercontent.com/16067358/48054204-fc667e00-e1ac-11e8-9e22-e94199b163cd.png)
Thanks to check & feedback.

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith 
Unfortunately not. I need the payment and the orders to be in my country currency. By adding other currencies I want to let my customers to understand easily how much the price would be in their local currency. Otherwise they have to use some currency exchange calculators in the Internet.

**Comment by khouloudbelguith** [comment]
@marionf, what do you think, is it possible to get orders were done with the single currency? ( in the FO, different currencies are enabled).
Thanks!

**Comment by marionf** [comment]
Yes, it's possible if you select the currency accordingly to the payment module
This way, you won't be able to pay with this module if you don't have selected the good currency in FO

![capture d ecran_569](https://user-images.githubusercontent.com/13449658/48060699-08f2d280-e1bd-11e8-8264-033a530b7add.png)

**Comment by AndreyOgleznev** [comment]
@marionf Thank you. I think that would be an option for me if there was a proper message on that.
Something like "Dear customer, please select RUB as a currency in order to make payment. PayPal or a bank can automatically convert your local currency into rubles. PayPal or a bank may take a small fee for currency conversion."
If the customer sees the existing message "Unfortunately, there is no payment method available." he doesn't understand what's wrong and what to do and may just leave the shop.
I'm not sure I could change the message via Translations.

![2018-11-06 15-31-29 andre s shop](https://user-images.githubusercontent.com/11665990/48061898-da372500-e1d9-11e8-9915-b4157094e80a.png)

**Comment by marionf** [comment]
Yes, you can change it in your translations

**Comment by AndreyOgleznev** [comment]
@marionf I'd love too. But where (or how) can I find it in traslations?

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, Thanks to navigate to your BO => IMPROVE => International => Translations => MODIFY TRANSLATIONS
-Set "Type of translation" => Themes translations
-Select your theme
-Select your language
-Click on Modify
In Theme => Checkout you need to modify your expressions 
![image](https://user-images.githubusercontent.com/16067358/48066578-4f046200-e1ce-11e8-8c52-73099a2846d7.png)
Thanks!

**Comment by AndreyOgleznev** [comment]
@khouloudbelguith Great! Thank you! it works!
I think I can now enable multiple currencies!

**Comment by khouloudbelguith** [comment]
@AndreyOgleznev, THanks for your feedback.
I close the issue, feel free to open a new one when needed.
@marionf, thanks!
