### ISSUE TITLE
Unable to set order status template

### ISSUE THREAD

**Issue by firstred** [PrestaShop/PrestaShop#11233]
**Describe the bug**
It is not possible to set the corresponding template of an order status.

**To Reproduce**
1. Navigate to Order Settings > Statuses
2. Select a status
3. Try to change the template
4. It shows an empty dropdown

**Screenshots**
![screenshot from 2018-11-02 01-59-03](https://user-images.githubusercontent.com/6775736/47888142-0736b100-de43-11e8-91bf-67654c5f697b.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A
Debug mode: on

**Comment by khouloudbelguith** [comment]
Hi @firstred,

Thanks for your report.
I did not manage to reproduce your issue using the last update "1.7.5.x" & the PS1.7.5.0build1beta2.
I attached a video record.
https://drive.google.com/file/d/1Ubefc4hD1T17axPvsu7-sL-wdZH0KB-W/view
Thanks to check & feedback.

**Comment by firstred** [comment]
With the last update, do you mean a nightly?

**Comment by khouloudbelguith** [comment]
@firstred, I make a test on the machine shuffle, nightly Prestashop & I did not manage to reproduce the issue.

**Comment by firstred** [comment]
Default configuration works, indeed. There is something else on my test environment that breaks it. I am on the latest source and the docker configuration you provide.

**Comment by firstred** [comment]
The cause seems to be an empty language folder in the `mails` folder.

I can see that `/mails/en/` is filled, but `/mails/nl/` is just empty. Closing this issue as I can confirm the template select indeed works.
