### ISSUE TITLE
Every single click on the delivery option block causes a refresh

### ISSUE THREAD

**Issue by firstred** [PrestaShop/PrestaShop#11232]
**Describe the bug**
Every single click on the delivery option block causes a refresh (including the "Checkout" button), which makes this step in the checkout really janky. This is especially noticeable as soon as you add modules that add additional HTML.

I would recommend to only refresh when the radio inputs change.

**To Reproduce**
1. Go to the checkout, navigate to the delivery step
2. Click anywhere except the radio buttons
3. Notice how it will just refresh

**Screenshots**
![jankycheckout](https://user-images.githubusercontent.com/6775736/47881092-74d3e480-de25-11e8-9526-ff2eb0bad341.gif)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @firstred,

I manage to reproduce the issue with PS 1.7.5.0 / 1.7.4.3.
https://drive.google.com/file/d/19-QIheJgtkjHXVW-tCeXvavrGDnenozo/view
@marionf what do you think?
Thanks!

**Comment by firstred** [comment]
It looks like the event listener is being attached to the whole div, because it is hard to figure out the name of the radio button group. Before you can select the radio button group, you will have to know the address ID, which probably is unavailable during the initialization of this block.

There are likely two things we can do to fix this issue:
- wait until the address ID is known (does it get attached to the `prestashop` object?) and delay rendering in the meantime
- or add another class/data-attribute with which we can identify the radio buttons
