### ISSUE TITLE
"TECHNICAL ERROR: parsererror" when adding a carrier weight range

### ISSUE THREAD

**Issue by jachymb** [PrestaShop/PrestaShop#11240]
**Describe the bug**
When trying to add a carrier weight range and press "Finish", I get an alert with the following and no result:

    TECHNICAL ERROR: 
     
    Details:
    Error thrown: [object Object]
    Text status: parsererror

I have found this [discussion thread](https://www.prestashop.com/forums/topic/217531-help-details-error-thrown-object-object-text-status-parsererror/) where many users describe a similar problem, but no suggested solutions have helped me.

**To Reproduce**
Obvious. Note: I use czech localization and have disabled pretty urls if that is relevant in any way.

**Additionnal information**
PrestaShop version: 1.7.4.1
PHP version: 7.0.32-0ubuntu0.16.04.1

**Screenshots**
![image001](https://user-images.githubusercontent.com/1655105/47913708-63c6ba00-de9d-11e8-8a62-d42b03ce848a.png)

**Comment by khouloudbelguith** [comment]
Hi @jachymb,

We did not manage to reproduce the issue with PS1.7.4.2. / 1.7.4.3.
But you can take a look at this ticket: http://forge.prestashop.com/browse/BOOM-5506
It could help to solve your problem.
Thanks to check & feedback.

**Comment by jachymb** [comment]
Sorry, to be precise, the version I use is actually 1.7.4.1

**Comment by khouloudbelguith** [comment]
Hi @jachymb,

I did not manage to reproduce the issue with PS1.7.4.1:
https://drive.google.com/file/d/1ZtuXJMmNkXmWdewIGBU5nKuDt3E5FKH_/view
Thanks!

**Comment by jachymb** [comment]
I can provide any details from my configuration, if you could suggest what information could possibly be relevant.

**Comment by jachymb** [comment]
I tried to debug it a little in the browser console. The error happens at line 150 of `carrier_wizard.js` There is an `errorThrown` object which has the following message `"Unexpected token < in JSON at position 0"` The `responseText` field in the `XMLHttpRequest` contains some html which is apparently not what the script expects. The response status there is 200 OK, though. The html is a relatively short page fragment containing message about something called `RangeWeight->delimiter1` being empty. Could this information be helpful in any way?

**Comment by jachymb** [comment]
I discovered a workaround - deleting the carrier and adding a new one instead fixed the problem for now. But that's not a real fix. I am unsure what was the cause behind it.

**Comment by jachymb** [comment]
This seems relevant http://forge.prestashop.com/browse/BOOM-3310 there is a merged PR that should allegedly fix a very similar problem but as I said, I have the bug in  1.7.4.1 which is after the PR has been merged https://github.com/PrestaShop/PrestaShop/pull/8097

**Comment by khouloudbelguith** [comment]
Hi @jachymb, in this PR: #8097, it fixes the issue of a carrier with invalid ranges that you should not be able to save it.
But, in your case, you don't have any invalid ranges.
Thanks!

**Comment by jachymb** [comment]
The PR is appears to fix the issue, but it apparently does not so entirely, since it has already been included in 1.7.4.1, where I encounter this bug. Right?

**Comment by khouloudbelguith** [comment]
@jachymb,

This PR fixed a different issue ( about invalid ranges).
As I said before, I did not manage to reproduce the issue with ps1.7.4.1 / 1.7.4.2 / 1.7.4.3.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
