### ISSUE TITLE
The translation tool saving translations always into en.php

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#11253]
**Describe the bug**
The translation tool for installed modules saving translations into en.php no matter which language is editing.

**To Reproduce**
1. Add another language in PrestaShop, e.g. French
2. Back office - Go to module Modules > Module catalog.
3. Chose and install any module, e.g. ps_faviconnotificationbo
4. Go to International > Translations, select module translation for French language. Chose ps_faviconnotificationbo for translation.
5. Fill any field as translation and Save.
6. Go to FTP into /modules/ps_faviconnotificationbo/translations/
7. You will find, there fr.php no exist and saved translation for French language saved into en.php.

**Additionnal information**
PrestaShop version: PrestaShop 1.7.5.0 (nightly build 2018-10-30)
PHP version: 7.2.1

**Comment by khouloudbelguith** [comment]
Hi @Caleydon,

Thanks for your report.
I manage to reproduce the issue with the PS1.7.5.0build4.
PS1.7.4.3 => OK / PS 1.7.3 => OK.
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith @Caleydon 
I tried with prestashop 1.7.4.3 and 1.7.5.0 and I have the same behavior:
I add English language
I edit translations for main menu module
In /modules/ps_mainmenu/translations I just have index.php and no en.php or fr.php
Translations are well saved, so seems there is no issue here

**Comment by Caleydon** [comment]
Please try with the module ps_faviconnotificationbo
https://github.com/PrestaShop/ps_faviconnotificationbo/releases

**Comment by marionf** [comment]
I have the same behavior with this module
I edit translations
In /modules/ps_faviconnotificationbo/translations I just have index.php and no en.php or fr.php
But translations are well saved in database table translation

**Comment by khouloudbelguith** [comment]
Hi,

This only occurs when the template uses the smarty extends function from within the BO.
The Ips_faviconnotificationbo module has no template but uses HelperForm, no template, no extends.
I tried with another custom module
[translationbug (1).zip](https://github.com/PrestaShop/PrestaShop/files/2595826/translationbug.1.zip)
Thanks!
