### ISSUE TITLE
BO: Page header overlap modal windows

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#11254]
**Describe the bug**
BO: Page header overlap modal windows on some pages. Please see the video to reproduce the bug.

**Video**
https://vimeo.com/298824399/853e595698

**Additionnal information**
PrestaShop version: PrestaShop 1.7.5.0 (nightly build 2018-10-30)
PHP version: 7.2.1

**Comment by khouloudbelguith** [comment]
Hi @Caleydon,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11104 to fix the issue.
Your ticket is a duplicate of #11042
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11042
