### ISSUE TITLE
Multistore login and default scope

### ISSUE THREAD

**Issue by amtriorix** [PrestaShop/PrestaShop#11255]
Problem:
In a multistore, when You login to a substore, using their URL and backend, the scope is wrongly set to all shops. Which makes it difficult to admin if You do not take care to put the right scope in a substore,
managing a substore.

Proposed solution:
1) Login at the backend from a store
2) check ENV VAR of the URL for domainname
3) Lookup domainname in stores to find bound store
4) Set scope to found store of that (sub)store by default
5) If failure, impossible or mandatory (all stores scope settings), set scope 'all stores'
6) Admin can change if needed manualy to other scope.

**Comment by khouloudbelguith** [comment]
Hi @amtriorix,

Thanks for your report.
We have made some fixes in the next release 1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9450
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @amtriorix,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
