### ISSUE TITLE
Error on install dev-version

### ISSUE THREAD

**Issue by lupitaflowers3** [PrestaShop/PrestaShop#11250]
**Describe the bug**
Im installing version dev on windows with xampp but in the last step I see an error
Failed to unzip 'C:\xampp\htdocs\PrestaShop/translations/cldr\core.zip'. I try to unzip directly but I get an error El archivo tiene un formato desconocido o esta dañado

**To Reproduce**
1. Go to 'http://localhost:8080/prestashop/install-dev'
2. Configure all to the last option Instalación de la tienda
3. The process starts but stops in the step Creando tienda predeterminada e idiomas

**Screenshots**
![prestashopfailed](https://user-images.githubusercontent.com/3925259/47944823-d185dc80-dec3-11e8-99d3-e00f4121a76d.png)

**Additionnal information**
PrestaShop version: The last
PHP version: 7.2.11

**Comment by khouloudbelguith** [comment]
Hi @lupitaflowers3,

Did you clone the  PrestaShop project from [GitHub](https://github.com/PrestaShop/PrestaShop), then you installed it?
Did you use any branch? develop or 1.7.5.x?
Thanks!

**Comment by lupitaflowers3** [comment]
Hello I clone the project from GitHub and I'm using develop branch.

Thank you.

**Comment by khouloudbelguith** [comment]
Hi @lupitaflowers3,

I did not manage to reproduce the issue.
I installed the Prestashop project cloned from the GitHub develop branch.
What is the exact country/language did you used during the installation?
Thanks!

**Comment by lupitaflowers3** [comment]
I'm using UnitedStates/English (English).

Regards.

**Comment by khouloudbelguith** [comment]
@lupitaflowers3,  it is Okey for me with UnitedStates/English (English).
After the clone of the Prestashop project, what it the exact steps did you follow?
Did you installed composer?
Did you change the file permissions of all directories to 777?
Thanks!

**Comment by lupitaflowers3** [comment]
Yes I I installed all whit composer, I din't change the permissions because
I'm on windows working with xampp.

**Comment by khouloudbelguith** [comment]
From this [project](https://github.com/PrestaShop/PrestaShop), did you clone PrestaShop with this line command `git clone https://github.com/PrestaShop/PrestaShop.git`? or did Download it as a zip?
![image](https://user-images.githubusercontent.com/16067358/48055239-67b14f80-e1af-11e8-9b7f-73f37cc50db1.png)
Thanks!

**Comment by lupitaflowers3** [comment]
I clone whit this line  git clone
https://github.com/PrestaShop/PrestaShop.git.
I created a virtual machine with ubuntu and I installed Prestashop without
problem, I think the problem is with windows.

Regards.

**Comment by khouloudbelguith** [comment]
Hi @lupitaflowers3,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @lupitaflowers3,

I tried to install the develop branch on windows with xampp v3.2.2
It is ok, there is no problem in the installation.
```
Server information Windows NT build 9600 (Windows 8.1 Professional Edition) i586

Server software version: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.0.15

PHP version: 7.0.15

Memory limit: 128M

Max execution time: 9000

Upload Max File size: 6M

Xamp v3.2.2
```
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!

**Comment by lupitaflowers3** [comment]
Ok, thanks for all.
Regards.

**Comment by khouloudbelguith** [comment]
Hi @lupitaflowers3,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!
