### ISSUE TITLE
Reassurance module

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/PrestaShop#11263]
Reassurance module : Adds an information block aimed at offering helpful information to reassure customers that your store is trustworthy.

WORK IN PROGRESS 

- [x] [Issue #9748](https://github.com/PrestaShop/PrestaShop/issues/9748)
- [x] [Addons Block](https://github.com/PrestaShop/PrestaShop/issues/11402) 

- [x] Last improvements https://github.com/PrestaShop/PrestaShop/issues/14700

Here is the current[ ZIP](https://github.com/PrestaShop/blockreassurance/tree/a9aaa86d0ed984796f4afe42c1abae827d1e4189)
Here is the module repo : https://github.com/PrestaShop/blockreassurance/

**Comment by colinegin** [comment]
Follow those PRs : 

- [x] https://github.com/PrestaShop/blockreassurance/pull/20

- [x] https://github.com/PrestaShop/blockreassurance/pull/22

**Comment by colinegin** [comment]
The module has been released, I can close this issue !
