### ISSUE TITLE
The on-boarding welcome is displayed again after installing the "mbo" module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11265]
**Describe the bug**
After a fresh installation 1.7.5.0 build4, check that the mbo module is not installed.
The module welcome is enabled & all steps are done.
In the last step, after clicking "I'm ready", try to install the "mbo" module, after the installation, you need to go to the Module Catalog page, the on-boarding welcome is displayed again.
I attached a video record for more details.
https://drive.google.com/file/d/1v9cFdhH9nOOR29L1fbMO7v3QJV070u4c/view

**To Reproduce**
1. Fresh install 1.7.5.0build4 ( mbo is not installed)
2. Follow all steps of the welcome module
3. In the last step, click on "I'm ready"
4. Install the "mbo" module
5. Go to the Module Catalog page => the on-boarding welcome is displayed again

**Additionnal information**
PrestaShop version: 1.7.5.0build4
PHP version: 7.1

**Comment by marionf** [comment]
MBO is installed by default so it's unlikely to happen
