### ISSUE TITLE
Small error in czech localization

### ISSUE THREAD

**Issue by jachymb** [PrestaShop/PrestaShop#11262]
**Describe the bug**
There is a recurring annoying typo in Czech localization where it translates 'delete' as 'odstránit'. The correct spelling is 'odstranit' the one with 'á' is possibly a remnant of translating it from Slovakian. 

**To Reproduce**
All instances can be found by running: `grep  -ir 'odstránit' app`
Affected files are:

    app/Resources/translations/cs-CZ/ShopThemeActions.cs-CZ.xlf
    app/Resources/translations/cs-CZ/AdminCatalogNotification.cs-CZ.xlf
    app/Resources/translations/cs-CZ/messages.cs-CZ.xlf
    app/Resources/translations/cs-CZ/AdminActions.cs-CZ.xlf
    app/Resources/translations/cs-CZ/AdminInternationalNotification.cs-CZ.xlf
    app/Resources/translations/cs-CZ/ModulesLinklistAdmin.cs-CZ.xlf
    
**Additionnal information**
PrestaShop version: 1.7.4.1

**Comment by khouloudbelguith** [comment]
Hi @jachymb,

I tried to run your command but there are no files affected.
![image](https://user-images.githubusercontent.com/16067358/47994858-e0eb6c80-e0f3-11e8-92d4-1813849b1867.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @jachymb,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
