### ISSUE TITLE
graft the module - 504 error 

### ISSUE THREAD

**Issue by jcmy31** [PrestaShop/PrestaShop#11267]
Hi
When I want to add the module to prestashop 1.7.4.3, I have a 504 error ( Gateway Time-out
nginx). Do you have an idea?

PrestaShop version: 1.7.4.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @jcmy31,

What is the exact name of the module do you want to upload it.
Thanks!

**Comment by jcmy31** [comment]
Hi,
Any of them

**Comment by khouloudbelguith** [comment]
@jcmy31, 

Is it a custom module? or a module provided by PrestaShop?
If you enable the mode debug, is there any exception displayed?
Thanks!

**Comment by jcmy31** [comment]
It is a custom module, in debug mode, I have no notification.

**Comment by khouloudbelguith** [comment]
@jcmy31, have you tried to contact the module author about this issue?
Thanks!

**Comment by jcmy31** [comment]
The problem does not come from the module, I can go to the page positions, I can unregister a module, but when I click on the link to graft a new module, I can not access the same page if it is to graft a prestashop module.

**Comment by khouloudbelguith** [comment]
@jcmy31, could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

- Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
- Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
- Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by jcmy31** [comment]
Thank you very much, I'm going to watch all this.

**Comment by khouloudbelguith** [comment]
@jcmy31,

Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @jcmy31,

Any news?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jcmy31,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
