### ISSUE TITLE
Deleted custom text block module

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#11269]
**Describe the bug**
I've started a shop recently and my custom text block module wouldn't update because i don't had the permission, so i decided to uninstall it to reinstall it to check if it could fix it, but now i don't find the module anymore in the shop.

**Additionnal information**
PrestaShop version: 1.7.1.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Mandals44, 

After installing the module, you didn't find it in the installed module list?
Or, do you want to install it, but you don't in find it in Module Catalog page?
Thanks!

**Comment by ghost** [comment]
sorry i couldn't answer, i wasn't at home. So this is a native module of prestashop. It was broken, i deleted it of my shop and now i don't find it anywhere, on my backoffice or the catalog page

**Comment by khouloudbelguith** [comment]
Hi @Mandals44,

You need to navigate to your BO => Modules => Modules & Services=> Selection Tab, search for the ps_customtext, it should be displayed & try to install it.
![image](https://user-images.githubusercontent.com/16067358/48126763-5127f880-e282-11e8-831c-b60a2585f37b.png)

Thanks!

**Comment by ghost** [comment]
thanks, i finally found it, but when i try to install it, it said that the module isn't compatible with my prestashop's version.
![error](https://user-images.githubusercontent.com/44785290/48149242-edbabc80-e2bb-11e8-9fb3-8a4765d1a5ea.PNG)

**Comment by khouloudbelguith** [comment]
@Mandals44, what is the exact version of the ps_customtext module, did you tried to install?
Thanks!

**Comment by ghost** [comment]
I finaly found where the problem came from. So i installed prestashop from ovh and they don't give the most updated version of prestashop. So I installed the 1-click upgrade and updated my version and it worked. Thank you so much and good riddance.

**Comment by khouloudbelguith** [comment]
@Mandals44, thanks for your feedback.
Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!
