### ISSUE TITLE
Slow backoffice 1.7.2

### ISSUE THREAD

**Issue by fullhugo** [PrestaShop/PrestaShop#11268]
For some reason my backoffice are very slow.
The version of my prestashop is 1.7.2 (I can't upgrade)

When I check php logs, I see a timeout because of this
`lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopDemoCatalog.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=14203, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopDemoCatalog.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=14203, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCustomersigninAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1250, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCustomersigninAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1250, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesSharebuttonsShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1318, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesSharebuttonsShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1318, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/AdminGlobal.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=88834, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/AdminGlobal.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=88834, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesPagesnotfoundAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=7376, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesPagesnotfoundAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=7376, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCategoryproductsAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=2313, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCategoryproductsAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=2313, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesGAnalyticsAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=6378, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesGAnalyticsAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=6378, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopThemeGlobal.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=23634, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopThemeGlobal.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=23634, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopThemeCheckout.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=40399, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ShopThemeCheckout.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=40399, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCustomtextAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1454, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesCustomtextAdmin.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1454, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesLegalcomplianceShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=10792, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesLegalcomplianceShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=10792, ...}) = 0
lstat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesBrandlistShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1312, ...}) = 0
stat("/home/mywebsite/ww2/app/Resources/translations/pt-BR/ModulesBrandlistShop.pt-BR.xlf", {st_mode=S_IFREG|0666, st_size=1312, ...}) = 0`

Originally I had 2 different languages, add 3r and disable the other 2

Any Idea what is going on here?

**Comment by khouloudbelguith** [comment]
Hi @CrAzYk69,

Could you please try to disable the gamification module, it could be a reason for the slowness of your BO, in fact, the gamification module is updated to a new version 2.2.1.
Also, if your back office email is capitalized but your email on profile.prestashop.com is not, the back office takes a full minute to finish loading.
Thanks to check & feedback.

**Comment by fullhugo** [comment]
Tks for your answer,
Unfortunately that don't resolve the problem

**Comment by khouloudbelguith** [comment]
@CrAzYk69, the general speed of the Back Office has been greatly improved (up to 3x faster!) in this PR #8780
It is added to the 1.7.3.1.

**Comment by khouloudbelguith** [comment]
Hi @CrAzYk69,

Any news about your issue?
Thanks!

**Comment by turnoextra** [comment]
Hi @CrAzYk69,

I have a similar case... because the Gamification plugin i can't access to my backend of Prestashop. I tried with diferent versions, that's 1.6.13 (oldest) and 1.7.42 (newest) and I found the same trouble. 

In my case I disabled the Gamification plugin... only moving on the FTP directory **/modules/gamification** to **/modules/gamification_old**.
Fixed.

An example of another user... https://www.youtube.com/watch?v=zg_rRAZI0H4 

Thanks for all!!

**Comment by khouloudbelguith** [comment]
Hi @turnoextra,

What is the exact version Gamification did you use in your case?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @CrAzYk69,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by turnoextra** [comment]
The Gamification plugin was removed from my Prestas about 1 month, so don't have any news to bring you. I recovered the normal speed of backoffice.

Thanks!
