### ISSUE TITLE
Bug in module SEO performance URL cleaner by prestashop

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#11272]
**Describe the bug**
When have installed the Module with prestashop 1.7.4.3 and correct the bug of Information (bad parameters necesary after upgrade to 1.7.4.3). Have this error

2 errores 
The route is not valid
Ruta a los modulos: Valor incorrecto (Route to modules: Value incorrect) I uninstall the module with the backup of url, disable the friendly url and clean the cache, and work fine (Product with combinations display the combinations list in BO) if active the friendly URL Work fine, When install again the module SEO generate new .htaccess with friendly url, and clean the cache. Product with combination dont show combination list in BO, and cant save any change in the product, Disable Friendly URL, clean cache and work fine again. It's clear the bug is in the Prestashop SEO performance URL cleaner.
Solve the issue pls. I need the module for my seo and the module crash functions.

**To Reproduce**
* Install the module
* config
* Apply
* Open a product with combination in BO, try save the changes (Error), Open combinations (Dont listed the combinations)
* Apply backup of URL in the module
* Disable the module
* Uninstall it
* Clean caches
* Disable and enable again the Fryendly URL
* Open the product again, try save changes (Good work), Open combinations (Listed ok)
* Install again the module
* Apply the configuration to 3 types of URL
* active the module
* disable and enable again the friendly URL
* delete caches
* Try again save the changes in the same product (Error again), combination list don visible
With Friendly URL disable and module installed worked fine too.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

As it's not a native module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account https://addons.prestashop.com/en/contact-us?id_product=25758, they are the only ones to help you with it.
Thanks!
