### ISSUE TITLE
Loosing user's groups access when updating category by webservice

### ISSUE THREAD

**Issue by Nikito22** [PrestaShop/PrestaShop#11289]
**Describe the bug**
When updating by web service a category with several groups selected previously by the user, the category **reset to the configured** Visitor, Guest and Customer groups, losing user's ones. 

As the Web Service doesn't give access to the category's groups associations, it necessary not to override it in the update.

**To Reproduce**
1. In the back office create a new client group
2. In the back office update an existing category giving access to that group
3. Update the category using web service (Just GET  and POST the same data via PostMan, for example)
4. Go back to the back office and refresh the category. It has gone back to the standard groups of Visitor, Guest, and Customer.

**Additionnal information**
PrestaShop version: 1.7.4.1
PHP version: 5.6.38

The **desired behavior** in the category API would be **getting access to groups associations**. 

As it would take a lot of time to achieve that new feature, in the meanwhile would be necessary to avoid overriding with the standard groups.

**I opened a pull request** with a simple change in Category.php class avoiding to update the groups in the update function when it's called by the web service.

**Comment by khouloudbelguith** [comment]
Hi @Nikito22,

Thanks for your report.
I manage to reproduce the issue with 1.7.4.3 / 1.7.5.0.
I used this script

```
<html><head><title>CRUD Tutorial - update example</title></head><body>
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 29/09/17
 * Time: 10:58
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shopurl.coml/');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$category_id = 10;
#$timestamp_debut = microtime(true);
$xml = $webService->get(array('resource' => 'categories', 'id' => $category_id));
$category = $xml->category;

unset($category->level_depth);
unset($category->nb_products_recursive);

$category->active = 0;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['category_id'] = $category_id;
$opt['resource'] = 'categories';
$xml = $webService->edit($opt);
echo "DONE";
```
After update category via WS, the category has gone back to the standard groups of Visitor, Guest, and Customer.
We will see how to fix it.
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: #10069

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with 1.7.6.0 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, I manage to reproduce this issue with PS1.7.6.0beta1 using this script

```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 28/05/19
 * Time: 13:00
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop/1760beta1');
define('PS_WS_AUTH_KEY', 'key');
require_once('PSWebServiceLibrary.php');
$webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$id = 106;
$timestamp_debut = microtime(true);
$xml = $webService->get(array('resource' => 'categories', 'id' => $id));
$category = $xml->children()->children();

unset($category->level_depth);
unset($category->nb_products_recursive);

$category->active = 0;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'categories';
$xml = $webService->edit($opt);
echo "DONE";

```

THanks!

**Comment by jf-viguier** [comment]
I've made a PR that should fix this too https://github.com/PrestaShop/PrestaShop/pull/17450

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17450
