### ISSUE TITLE
Page isn't reloaded in FO when you change combination

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11281]
**Describe the bug**
Page isn't reloaded in FO when you change combination

**To Reproduce**
1. Go to a product with combination in FO
2. Change combination
3. The URL change but the page isn't reloaded
4. If you click on previous buttons, you are back to the previous page instead of previous combination

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by rdy4ever** [comment]
Wouldn't reloading the page defeat the purpose of using ajax to change combinations in the first place?

**Comment by colinegin** [comment]
What do you think @NeOMakinG ?

**Comment by NeOMakinG** [comment]
That's a choice because all the changes are happening using AJAX (no reload), and we've no history of ajax calls, same in the BO @marionf, reassign me this issue if you decide something here but I think it's not easily doable

**Comment by colinegin** [comment]
Do you think we should close it ?

**Comment by NeOMakinG** [comment]
To be honest we should keep the ajax refresh and so we can't do that easily, tell me if I'm wrong @PierreRambaud @eternoendless

**Comment by PierreRambaud** [comment]
We should play with the window.history object when we change the url. With this, we can keep the ajax behavior.

**Comment by NeOMakinG** [comment]
I'ts fixed on https://github.com/PrestaShop/PrestaShop/pull/17133, thanks @PierreRambaud for most of the job/help

**Comment by Progi1984** [comment]
Fixed by #17133
