### ISSUE TITLE
Italian Electronic Invoice from 1st January need 2 fields

### ISSUE THREAD

**Issue by disarci** [PrestaShop/PrestaShop#11299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by disarci** [comment]
Hi,
in Italy we will need to ask to customers two more fields in registration for B2B shops.
1) the new "official" email name as PEC (electronic certificate email)
2) the "official" code number for transmit the invoice to the finance services.

All the italian shops that will generate an invoice to someone with a vat_number need to ask this 2 new fields

France will arrive at this in 2020 (see: Facture électronique obligatoire).

I'd like to know if there will be some new fields on registration or if we need to develops many different modules and not have a standard in registration anymore.
We had the same problem on PS 1.1, 1.2 before adding dni and vat_number and had many problems with external modules and migration.

Best Regards
Christian

**Comment by khouloudbelguith** [comment]
Hi @disarci,

In our [addons.prestashop.com](https://addons.prestashop.com/en/) you can find a selection of the e-Invoice modules.
Thanks to check & feedback.

**Comment by disarci** [comment]
Hi, yes, and I sell one of this!

Just, I think, that will better to include the same fields in all the customer registration, if every module will insert his fields the future compatibility will be a problem.

**Comment by khouloudbelguith** [comment]
@marion what do you think?
Thanks!

**Comment by colinegin** [comment]
Hello @disarci,

Thanks for your feedback and sorry for the late reply.

There is one module already available for the Italian electronic invoice available on Addons : https://addons.prestashop.com/fr/comptabilite-facturation/42408-digital-invoice-xml.html.

About your idea, we will review it and see if we can add it to our roadmap.

About your comment "France will arrive at this in 2020 (see: Facture électronique obligatoire).", could you give us more details about it ?

Thank you very much !

**Comment by colinegin** [comment]
Hello @disarci,

Since we have had no news for a few months, I will close this issue.
Feel free to re-open it or write a new issue if needed !

Have a nice day,

Coline

**Comment by HartLarsson** [comment]
hi,
SDI and pec email aer needed to be collected like VAT code for italian shops that need to make Invoices.
There are some modules in addons like:
https://addons.prestashop.com/it/funzionalita-front-office-moduli-prestashop/42861-campi-fatturazione-elettronica-pec-e-sdi.html
that add SDI and Pec fields but need some modification to theme files.
Because as DNI and VAT code also SDI and pec email are needed why not embed these 2 fields inside the core?
