### ISSUE TITLE
Module ps_wirepayment more about no visible PrestaShop : 1.7.3.0

### ISSUE THREAD

**Issue by KHATERSAID** [PrestaShop/PrestaShop#11297]
Hello
I noticed that more about is the same color as the text
the customer does not know he can click on the link to find out more
how to fix this problem
thank you
![5](https://user-images.githubusercontent.com/39734318/48120862-a14b8e80-e273-11e8-8c53-ac00887ac65f.jpg)
![6](https://user-images.githubusercontent.com/39734318/48120863-a1e42500-e273-11e8-9924-b869b667aeda.jpg)

**Comment by khouloudbelguith** [comment]
Hi, @said4440,

In the file Project_Folder/themes/Your_Theme/assets/css/theme.css
You need to comment this line
   ` color: inherit;`
In fact, you can replace this
```
a:not([href]):not([tabindex]), a:not([href]):not([tabindex]):focus, a:not([href]):not([tabindex]):hover {
    color: inherit;
    text-decoration: none
}
```

by this 

```
a:not([href]):not([tabindex]), a:not([href]):not([tabindex]):focus, a:not([href]):not([tabindex]):hover {
    /*color: inherit;*/
    text-decoration: none
}
```

Thanks to check & feedback

**Comment by KHATERSAID** [comment]
hello thank you for your help but this method does not work
![herboriste en ligne - google chrome_4](https://user-images.githubusercontent.com/39734318/48144190-b98dce80-e2b0-11e8-9eaa-db5748eca95b.jpg)
![modules et services herboriste en ligne - google chrome_2](https://user-images.githubusercontent.com/39734318/48144192-ba266500-e2b0-11e8-9066-e6ef3addbb1b.jpg)
![performances herboriste en ligne - google chrome](https://user-images.githubusercontent.com/39734318/48144193-ba266500-e2b0-11e8-9307-f78f2c0699cd.jpg)

**Comment by khouloudbelguith** [comment]
@said4440, I've not commented it in the custom.css file but into the theme.css file.
![image](https://user-images.githubusercontent.com/16067358/48145193-9ebc5980-e2b2-11e8-9b92-2581b8953042.png)
![image](https://user-images.githubusercontent.com/16067358/48145256-bbf12800-e2b2-11e8-97d9-b791acc42e1c.png)
Thanks!

**Comment by KHATERSAID** [comment]
Thank you very much @khouloudbelguith  for the help you have given

**Comment by khouloudbelguith** [comment]
Hi @said4440,

You are welcome.
I close the issue, feel free to open a new one when needed.
Thanks!
