### ISSUE TITLE
Two Url catategory generation for the same category

### ISSUE THREAD

**Issue by hubyhuby** [PrestaShop/PrestaShop#11295]
**Describe the bug**
After a fresh install using "simplified url" I get inconsistent routes :
 
The product route works fine : WEBSITE /le-labo-experience/21-47-rhum.html#/26-degre_alcoolique-20/29-type_de_sucre-sucre_blanc
**but the category route: WEBSITE /le-labo-experience/ does not exist !**
The correct url for the category is **/11-le-labo-experience**

This is a majeor flow for SEO. Since there is no logical routing here...
Now I could n modify the rounting for the category since there doesn t seem to be a snippet {catergory-id}

**To Reproduce**
1. Install prestashop 1.7
2. Activate "simplified url"
3. create a category and a product
4. go to a product
5. remove the product name from the url to get only the category
6. Get "this page doesn t exist"

**Additionnal information**
Default routing: {category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html
SHOULD be : Default routing: {catergory-id}-{category}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html

**Comment by khouloudbelguith** [comment]
Hi @hubyhuby,

Thanks for your report.
We have just improved the SEO of the category page & the Product page in the PS1.7.5.0.
You can check these PRs: 
https://github.com/PrestaShop/PrestaShop/pull/9472
https://github.com/PrestaShop/PrestaShop/pull/9456
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @hubyhuby,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
