### ISSUE TITLE
WS: CDATA not encoded correctly in correctly

### ISSUE THREAD

**Issue by AJenbo** [PrestaShop/PrestaShop#11292]
**Describe the bug**
If a description contains a CDATA entry in the description, the produced WS XML is invalid.

**To Reproduce**
1. Create a product with the following description:
```
<script>// <![CDATA[
      // alert('hello'); 
// ]]></script>
```
2. View that product in WS `/api/products/ID`, giving you:
```
<description><![CDATA[<script>// <![CDATA[
      // alert('hello'); 
// ]]></script>]]></description>
```
This makes the description data end early at the </script> tag.

**Screenshots**
![billede](https://user-images.githubusercontent.com/204594/48091370-c7d4df80-e209-11e8-8ae0-296591d66d0e.png)

**Comment by khouloudbelguith** [comment]
Hi @AJenbo,

When I viewed that product in WS, I found this:
![image](https://user-images.githubusercontent.com/16067358/48127300-ac0e1f80-e283-11e8-99e3-64fcef9d09ee.png)
Thanks to check & feedback.

**Comment by AJenbo** [comment]
Looks like the offending shop is running 1.6.1.4 so probably this issue has been fixed in 1.7.4.3?

**Comment by khouloudbelguith** [comment]
Hi @AJenbo,

With PS1.6, when I go to that product in WS /api/products/ID, giving me:
![image](https://user-images.githubusercontent.com/16067358/48136251-76772f80-e29f-11e8-87ef-43db67fa82b0.png)
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @AJenbo,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
Thanks!
