### ISSUE TITLE
After updating 1.6.1.22 to 1.7.4.3 Front office / Modules back office Error 500

### ISSUE THREAD

**Issue by zaghouss** [PrestaShop/PrestaShop#11293]
Hello,
After updating Prestashop from 1.6.1.22 to 1.7.4.3, front office is not working anymore and some pages on back-end like Modules page.. Error 500

After activating debug mode here's what i have on front-office :  

Warning: Declaration of Tools::getPath($id_category, $path = '', $link_on_the_item = false, $category_type = 'products', Context $context = NULL) should be compatible with ToolsCore::getPath($url_base, $id_category, $path = '', $highlight = '', $category_type = 'catalog', $home = false) in /homepages/28/d755704286/htdocs/myedressit/override/classes/Tools.php on line 98

Notice: Use of undefined constant _PS_VENDOR_DIR_ - assumed '_PS_VENDOR_DIR_' in /homepages/28/d755704286/htdocs/myedressit/config/smarty.config.inc.php on line 26

Whoops, looks like something went wrong.

(1/1) ContextErrorExceptionWarning: Cannot modify header information - headers already sent by (output started at /homepages/28/d755704286/htdocs/myedressit/override/classes/Tools.php:98)
--
in FrontController.php line 934
at FrontControllerCore->initHeader()in Controller.php line 251
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

And here's what i have on modules back office page : 

(1/1) RuntimeExceptionFailed to start the session because headers have already been sent by "/homepages/28/d755704286/htdocs/myedressit/override/classes/Tools.php" at line 98.
--
in NativeSessionStorage.php line 141
at NativeSessionStorage->start()in NativeSessionStorage.php line 302
at NativeSessionStorage->getBag('attributes')in Session.php line 258
at Session->getBag('attributes')in Session.php line 280
at Session->getAttributeBag()in Session.php line 75
at Session->get('_security_main')in ContextListener.php line 89
at ContextListener->handle(object(GetResponseEvent))in WrappedListener.php line 46
at WrappedListener->handle(object(GetResponseEvent))in TraceableFirewallListener.php line 35
at TraceableFirewallListener->handleRequest(object(GetResponseEvent), object(RewindableGenerator))in Firewall.php line 61
at Firewall->onKernelRequest(object(GetResponseEvent))in FirewallListener.php line 48
at FirewallListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
at call_user_func(array(object(TraceableFirewallListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request',object(TraceableEventDispatcher))in WrappedListener.php line 104
at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in TraceableEventDispatcher.php line 139
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 88

After many research coudn't find any solution and my website is down now.

PrestaShop version: 1.6.1.22 to 1.7.4.3
PHP version: Used 7.2 on 1.6.1.22 Work fine ; Tested 1.7.4.3 with 5.6 , 7.0 , 7.2 nothing changes.

**Comment by khouloudbelguith** [comment]
Hi @zaghouss,

You have some overrides are not compatible with Ps1.7, you have error in the override tools.php, it could be due to a custom module.
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @zaghouss,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
