### ISSUE TITLE
No carriers available at the checkout just for desktop

### ISSUE THREAD

**Issue by lilianamc** [PrestaShop/PrestaShop#11307]
**Describe the bug**
My online store (PS 1.7.4.2) was working well for a month when a message suddenly started to appear at the checkout "No carriers available ..... " I did not move anything, I'm the only one who has access to my site, and I have 6 years of experience with Prestashop.

Few days ago, I noticed something very strange, a client told me that the website was charging her double for the shipment for an order that was free shipping, that seemed very strange. I did not know what the client did but she could place the order and receive free shipping.

**To Reproduce**
it's happening just for **desktop**. it's happening for old and new clients. 

**Screenshots**
https://imgur.com/a/7kKdhlE

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @lilianamc,

You need to check Zones if they are checked.
![image](https://user-images.githubusercontent.com/16067358/48142653-754cff00-e2ad-11e8-971b-b16f8ec87c3b.png)
Also, you can check the available carriers in the Product page.
![image](https://user-images.githubusercontent.com/16067358/48142698-8e55b000-e2ad-11e8-8a09-37d1674c23eb.png)
Thanks to check & feedback.

**Comment by lilianamc** [comment]
@khouloudbelguith I did check all the Zones. It worked :) 
Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank youuuuuuuuuuu. 

I made my day !!!!!

**Comment by khouloudbelguith** [comment]
Hi @lilianamc,

You are welcome.
I close the issue, feel free to open a new one when needed.
Thanks!
