### ISSUE TITLE
BO - Delete categories .... very very slow

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11303]
Hi,
I have about 1000 categories. For the moment 0 product.
I just tried to delete all the categories ... it takes about 3sec per category (possibly more) ...
I use PHP 7.1 and Mysql 5.7 ....
Prestashop 1.7.4.3 (latest stable)

Is it normal ? I would say no (because it it not possible to wait so long ... )

Thank you all

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by grabelle** [comment]
Hi, in fact there are no error message ... it ends with a 503 because sooo long.
I see many many sql query . For information I have 1230 categories.
With debug mode, where can I see the log ? (nothing is displayed on the screen)

thanks for your help

**Comment by khouloudbelguith** [comment]
@jocel1 what do you think?
Thanks!

**Comment by grabelle** [comment]
It takes ~10-15 seconds to delete 1 category ... :-(

**Comment by grabelle** [comment]
@jocel1 : for information it takes also hours to insert 1000 categories using the webservice (on the same serveur, with good hardware (ssd, 32Go ram, good proc)

Thx for your help.

**Comment by jocel1** [comment]
Hi @grabelle,

If you add a return at the beginning of Category::regenerateEntireNtree() do you still see this issue?

Thanks,

**Comment by grabelle** [comment]
Yes ! It is much much faster : 30s to delete all the category and about 2min30 to insert all (vs 1h40 before).

**Comment by jocel1** [comment]
Thanks for the feedback, so we need to optimize this function! (but I have perhaps a quick fix to speedup the WS)

**Comment by jocel1** [comment]
@grabelle: are you using the webservice in batch mode, with several ids / objects or one by one?

**Comment by jocel1** [comment]
@grabelle: could you try the fix I've just pushed to check if it improves things in your case?

**Comment by grabelle** [comment]
@jocel1 : unfortunately it is again terribly slow. (batchSize is 100) : more than 30min to insert 500 categories.

**Comment by jocel1** [comment]
@grabelle ah, with a batchSize of 100 I can understand it's still slow (but I assume it's a bit faster?)
Next step will be to optimize the function itself then

**Comment by grabelle** [comment]
For 1000 categories : 10 x 100 ... the function will be call 10 times. If I reduce the batchsize to 10 it will be worse I guess (function call 100 times) .... am I wrong ?

**Comment by grabelle** [comment]
You could try to remove all index (not the primary key) .... do the many updates... then rebuild the index ? (or use a function that avoid the index to be rebuild).
Or use the load data infile ?

**Comment by jocel1** [comment]
@grabelle yes, ideally it would be great to do it in one batch. It's not related to sql index, so removing them would not speedup things a lot @marionf the fix is still WIP, I'd like to optimize the regenerateEntireNtree function itself :)

**Comment by marionf** [comment]
@jocel1 PR #11313 is ready for QA or still WIP ?

**Comment by jocel1** [comment]
@marionf I'll do some extra optimizations in it, so still WIP (there's no WIP tag BTW?)

**Comment by marionf** [comment]
No, I removed the waiting for QA label of the PR and put the issue as in progress :)

**Comment by jocel1** [comment]
@grabelle I've just updated my patch to try to speed the regenerateEntireNtree function, could you give it a try?

**Comment by jocel1** [comment]
Blackfire profiling of the regenerateEntireNtree function call with 10000 categories in the DB:
https://blackfire.io/profiles/compare/17ff2742-04a6-4e1a-b923-93039daa61c4/graph

**Comment by grabelle** [comment]
@jocel1 : Hi, I'll try by tomorrow. Thanks a lot.

**Comment by jocel1** [comment]
@grabelle any news? :)

**Comment by grabelle** [comment]
Hi @jocel1 , still very long and ends with a 503. You can import a csv file with 1000 fake categories (with the root cat as parent). Sorry for the delay.

**Comment by jocel1** [comment]
@grabelle weird, do you know how many queries you have with the patch? it should be much lower

**Comment by p2rcoder** [comment]
is it possible to add this fix to 1.7.5?
