### ISSUE TITLE
The same cart for all registered customers

### ISSUE THREAD

**Issue by Benla79** [PrestaShop/PrestaShop#11308]
**Describe the bug**
I have a B2B website where people have to login to see the prices. But once they log in, they'll see the previous custmer's cart and if 2 customers are on the website at the same time, they share the same cart... (I tried)
I have installed the "Hide prices easily" module and created a new group category "professionnel" where all logged in customers will belong.

**To Reproduce**
1. Go to 'create an account'
2. Click on 'cart'
3. See error as it is not your cart

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
Hi @Benla79,

Did you use the MailChimp module?
If yes, thanks to disable it, check & feedback.
Thanks!

**Comment by Benla79** [comment]
Hi @khouloudbelguith,

Yes, I do have the mailchimp module. I disabled it. It still does it. When I add a product in one customer's cart, it appears also in the other cart...
Should I clear the cache?

**Comment by khouloudbelguith** [comment]
@Benla79, Yes, please.
Because this issue occurs due to the mail chimp module.
This is a previous ticket: http://forge.prestashop.com/browse/BOOM-5486 about this issue.
Thanks!

**Comment by Benla79** [comment]
@khouloudbelguith 
It works!!! Thank you very much.

**Comment by Benla79** [comment]
@khouloudbelguith 
Is there a solution to integrate Mailchimp?

**Comment by khouloudbelguith** [comment]
@Benla79, great!
I close the issue, feel free to open a new one when needed.
