### ISSUE TITLE
The admin payment preferences page is blank

### ISSUE THREAD

**Issue by Yoninov** [PrestaShop/PrestaShop#11319]
Hello,

i am trying to change payment preferences on the back office but the  page doesnt load. Its blank.

Prestashop is 1.7.4.4.
Server information 
Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Server software version: Apache
PHP version: 7.2.11
Memory limit: 512M
Max execution time: 300
Upload Max File size: 64M
Everything else works like charm

Any idea?

[debug info.txt](https://github.com/PrestaShop/PrestaShop/files/2562141/debug.info.txt)

**Comment by khouloudbelguith** [comment]
Hi @Yoninov,
.
could you please try to disable the welcome module, clear cache, check & feedback.
Thanks!

**Comment by Yoninov** [comment]
Hi @khouloudbelguith,
Thank you, but this is no solution.
See new file report
Regards,
[debug info2.txt](https://github.com/PrestaShop/PrestaShop/files/2562487/debug.info2.txt)

**Comment by khouloudbelguith** [comment]
@Yoninov, did you use any 3rd party module?
Thanks!

**Comment by Yoninov** [comment]
No this is new instalation and i have instaled only IQIT wharehouse theme, imported products and BG languages pack.
Thanks!

**Comment by khouloudbelguith** [comment]
@Yoninov, could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

- Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
- Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
- Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by Yoninov** [comment]
@khouloudbelguith, this is the report.
![2018-11-08](https://user-images.githubusercontent.com/24920574/48217927-5cb61500-e391-11e8-9de3-8de2ac4215c5.png)
Regards

**Comment by khouloudbelguith** [comment]
Hi @Yoninov,

Thanks for your feedback.
Your configuration is OK.
But, the PHP version in the screenshot is PHP7.1, in the information that you gave to me in the first comment is PHP7.2.
In my case, I did not manage to reproduce the issue with PS1.7.4.4, PHP7.1 / PHP7.2.
Thanks!

**Comment by Yoninov** [comment]
Hi @khouloudbelguith
Thank you for your responce, but see again please my php is 7.2.11

If you can give me some advice on this problem?
Thanks in advance!

**Comment by khouloudbelguith** [comment]
@Yoninov, yeah, sorry.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Yoninov** [comment]
@khouloudbelguith  see new debug file.
[debuginfo3.txt](https://github.com/PrestaShop/PrestaShop/files/2565648/debuginfo3.txt)

Thanks!

**Comment by khouloudbelguith** [comment]
@Yoninov, what are the payment modules that you installed?
Thanks!

**Comment by Yoninov** [comment]
@khouloudbelguith only two modules
1. Cash on delivery (COD) v1.0.6 - by PrestaShop
2. Bank transfer v2.0.4 - by PrestaShop
Thanks!

**Comment by khouloudbelguith** [comment]
@Yoninov, did you installed any custom module related to the carriers? any transport module?

**Comment by Yoninov** [comment]
@khouloudbelguith I just tested one carrier module /Ekont/ but is currently uninstalled.
Active is only pickup in store.

**Comment by khouloudbelguith** [comment]
@Yoninov, it could be an issue, could you please try to remove the folder of this module in Project_Folder/modules
Thanks to check & feedback.

**Comment by Yoninov** [comment]
@khouloudbelguith Great!!!

The problem is solved. :)

Thank you very much!

**Comment by khouloudbelguith** [comment]
@Yoninov, great.
I close the issue, feel free to open a new one when needed.
Thanks!
