### ISSUE TITLE
[SF Migration] Allow devs to choose SF services to be public instead of setting all services to public

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11316]
#### Is your feature request related to a problem?
Currently, all PrestaShop Symfony services are public (example: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/bundle/controller.yml#L3)

I think this is under-performing for Symfony container behavior. If I'm not wrong, and this needs to be benchmarked to be proved, marking a SF service as true changes the container behavior and increases loading SF loading time.

#### Describe the solution you'd like
I guess we put all services to `public: true` in order to allow module developers and shop developers to use any SF service for their needs. Maybe we can find a mechanism to allow these developers to "toggle" the `public` setting of these services, and control which ones are public, which ones are private ?

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for the suggestion. So, what's this issue status?
Ping @PrestaShop/prestashop-core-developers friendly reminder :wink: 

Thanks!
