### ISSUE TITLE
change the install options

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#11310]
Hi, in install process, when you select spanish language and Argentina country per example prestashop when finish the installation, adding automatic es-AR lang, this language is bad translated, The installer take the parameter of language (in install fase for display the process in spanish, but at the same time he take this option to add the language to the language list in BO), and Country for install the predefined langs when finish the install. This is bad the install process finally Charge in the database languages, i'll never use....
The installer only need take the Country for the installation of initial language of store....
And pls, es-Ar is the same of es-ES for default

For example in my case, I'm select spanish language  in installer process and Argentina Country
When processs successfully and I'm enter to BO -> languages
Display es-Ar and es-Es language....
es-Es no need.

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

Is that the same issue described in this previous ticket: http://forge.prestashop.com/browse/BOOM-5295?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @TecnoHands,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
