### ISSUE TITLE
Bug on orders created from the back office, with specific prices products

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#11317]
**Describe the bug**
The unit price change on an order made on the back office does not apply if a product has a specific price on the quantity.

To correct this problem, put the `score` before` from_quantity` in `ORDER BY` as follows:
[https://github.com/PrestaShop/PrestaShop/blob/475d65fbda93403cd1afde0db09764c5295e952c/classes/SpecificPrice.php#L360](url)
```
// In /classes/SpecificPrice.php, line 360 : 
$query .= ' ORDER BY `id_product_attribute` DESC, `score` DESC, `from_quantity` DESC, `id_specific_price_rule` ASC,  `to` DESC, `from` DESC';
```

This modification seems to me logical, I think it does not negatively impact the Specific rules. I even think that it can fix even bugs on Front Office

**To Reproduce**
Create a product with specific price from 10 units.
Create an order from the back office
Add this product with at least 10 quantity
Edit the unit price on the product line. The price will return automatically with the specific price defined on the product. It does not take into account the change.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.6.23
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @tups,
Thanks for your report.
I did not manage to reproduce the issue with 1.7.4.4.
https://drive.google.com/file/d/1CUun4Yu5ixTIcxz5ncfPn16BV4SDlqMY/view
In the PS 1.6, the problem exists but as you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
if your bug isn’t critical or a security issue, it can not be fixed.
Thanks for your understanding

**Comment by tups** [comment]
Thank you for your checking and your return.

I will override the client, until the 1.7 is stable enough.
