### ISSUE TITLE
Pixels between buttons in helper cards

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11315]
**Describe the bug**
We need to put 15 pixels between buttons in helper cards

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. We need to have 15px between "Learn more" & "Configure index page" buttons

**Screenshots**
![capture d ecran_591](https://user-images.githubusercontent.com/13449658/48191741-35862600-e346-11e8-8eb0-f21af8e44f4f.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by marionf** [comment]
Requested by @TristanLDD

**Comment by colinegin** [comment]
#12644
