### ISSUE TITLE
No carriers available at the checkout

### ISSUE THREAD

**Issue by lilianamc** [PrestaShop/PrestaShop#11320]
**Describe the bug**
My web site is saying "No carriers available ..... "at the checkout -  I did what @khouloudbelguith told me, please check ticket #11307  - the web site was OK for few hours and suddenly started to appear at the checkout "No carriers available ..... " again :( and now it is happening for mobile and desktop. My sales are stopped :(  

**To Reproduce**
please check ticket #11307

Screenshots
https://imgur.com/a/7kKdhlE

Additionnal information
PrestaShop version: 1.7.4.2
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @lilianamc,

Did you check if the Zones are selected or not again?
Thanks!

**Comment by lilianamc** [comment]
Hi @khouloudbelguith 
They are still selected - Please see image https://imgur.com/a/3S2EbUa

**Comment by khouloudbelguith** [comment]
@lilianamc, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
If you enable the debug mode, is there any exception displayed?
Thanks!

**Comment by lilianamc** [comment]
@khouloudbelguith 

Please see this images:
https://imgur.com/a/sxd7T9z

https://imgur.com/a/coCwTtz
https://imgur.com/a/009wVTs

**Comment by khouloudbelguith** [comment]
@lilianamc, It looks like a permission error or PHP misconfiguration on your server. From the stack trace you posted, I can tell that PHP is configured to store stores its sessions on /var/cpanel/php/sessions/ea-php56, but it's unable to read from there. It might be that the user on which your web server (or PHP, if you're using fastcgi) needs read/write rights on that directory.
Here's a link that might shed some more light on this issue: https://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder
Hope this helps solve your problem

**Comment by lilianamc** [comment]
Hi, @khouloudbelguith 

The debug mode is not showing any exception :) 

I have a question regarding to " _try to clear cache manually by deleting all the folder into var/cache (prod & dev)_." 
Do you want me to delete the folders (prod & dev) or just the information inside these 2 folders?  Please see image https://imgur.com/a/5Ek7nVR

**Comment by khouloudbelguith** [comment]
@lilianamc, you need to delete the folders (prod & dev).
Thanks!
Your problem is a server issue as I described above.
You need to contact your host.
Thanks to check & feedback.

**Comment by lilianamc** [comment]
Hi @khouloudbelguith ,
Thank you very much for your help. It's working ok now. 

Regards, Liliana from Colombia.

**Comment by khouloudbelguith** [comment]
Hi @lilianamc,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
