### ISSUE TITLE
Add reference parameter in the StockManager sendLowStockAlert method

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#11324]
Hello there, I need to add a custom parameter (the product reference) in the productoutof stock email body.
My problem is not related to the edit of the templates inside the email folder.
I have to edit the class handling the template parameters in order to get the data on the email's body.

My assumption is that I cannot override and customize it because the file `\src\Core\Stock\StockManager.php is in the src folder` (correct me if I'm wrong).

So, to achieve the ability to integrate the reference parameter inside the transactional email I have to edit the method `sendLowStockAlert`... but doing so as soon as PS gets an update my modification is deleted.

Any suggestion?
Thanks in advance.

**Comment by khouloudbelguith** [comment]
Hi @masiorama,

Thanks for your report.
This is an improvement request.
It should be specified by our developers.
Related to https://github.com/PrestaShop/PrestaShop/issues/9641
Thanks!

**Comment by masiorama** [comment]
So what can I do? Make an edit and do a pull request hoping for the best?
Thanks in advance!

**Comment by khouloudbelguith** [comment]
@masiorama, 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by masiorama** [comment]
Ok, I'll try to make a modification and a PR.

**Comment by matks** [comment]
Hi, I dont see why there is `waiting for dev` for this issue 😅 

I cant find any PR from @masiorama so I guess he could not find time for this topic. No worries 😄  it happens.

I close this issue as nothing else is needed.

**Comment by masiorama** [comment]
Wow, 2y ago! Sorry, never had the chance to contribute, and I totally forgot about it.

**Comment by matks** [comment]
@masiorama No worries, it happens all the time 😉
