### ISSUE TITLE
Is it safe to disable mod_security?

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#11327]
Is it safe to disable mod_security if using latest version of PrestaShop?

**Additionnal information**
PrestaShop version: latest
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment]
@MathiasReker, what do you want to disable the mod_security in the latest version Prestashop?
Thanks!

**Comment by MathiasReker** [comment]
A theme (warehouse theme) require mod_security disabled.

**Comment by khouloudbelguith** [comment]
@MathiasReker, what is the exact version PrestaShop did you use?

**Comment by MathiasReker** [comment]
I would like to use 1.7.5.0 (when stable) with warehouse theme. Warehouse theme writes in the docs, that mod_security should be disabled: https://iqitcommerce.ticksy.com/article/13083/

Is this safe?

**Comment by khouloudbelguith** [comment]
@eternoendless, @Quetzacoalt91, @PrestaShop/prestashop-core-developers, what do you think?
Thanks!

**Comment by eternoendless** [comment]
Hi @MathiasReker, it should be, since the Back Office provides an option to disable it (scroll down the Traffic & SEO page).

Here's a very old, [related commit](https://github.com/PrestaShop/PrestaShop/commit/f5cf54ef3b2147edde59ff1d3bf574d148e43095) for history's sake. It goes way back to 1.5.5...

**Comment by MathiasReker** [comment]
I am not unsure how to enable or disable it. I am just a little scared about disable it due to security reasons. Do you think it is a bad idea to disable it or is it safe?

**Comment by MathiasReker** [comment]
Thanks, it is solved :-)
