### ISSUE TITLE
Bad design on small screen for module action buttons in V1.7.5.0 beta 1

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11331]
**Module List buttons are looking bad**
See my screenshot

**To Reproduce**
1. Go to 'Modules -> Module Manager'
2. Click on 'Module Manager Tab'
3. See error

**Screenshots**
![ps-module manager beta test](https://user-images.githubusercontent.com/19220745/48247367-10161c80-e419-11e8-82ca-91633fdfcbee.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 beta 1
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
@PierreRambaud, @LouToma, what do you think about the responsive design?
About the position of the tab, in the second one, it's related to #10047.
Thanks!

**Comment by dheerajwebkul** [comment]
@PierreRambaud 

Sorry about my word responsive design, it's responsive. I mean to say bad design.
You should make a drop-down same as previous before V 1.7.5.0.
Just like admin product page design see screenshot:

![product ps175 beta](https://user-images.githubusercontent.com/19220745/48255991-42814300-e434-11e8-9311-bbf78f57791f.png)
![product ps175 beta-1](https://user-images.githubusercontent.com/19220745/48256001-4745f700-e434-11e8-9b7e-d0461961480f.png)

**Comment by LouToma** [comment]
I talked about this problem a few weeks ago to @TristanLDD who suggested to put the 2 buttons aside. is it possible to do it ?

**Comment by marionf** [comment]
@TristanLDD can you provide asap a mock-up or specify margin ?

**Comment by TristanLDD** [comment]
Hi, 

We should keep the 2 buttons on large screens and go back to the 1.7.4 display on small screens when the design breaks: 

![capture d ecran 2018-11-15 a 10 42 46](https://user-images.githubusercontent.com/27484094/48544558-22ce9c80-e8c4-11e8-9329-91ed8becdd85.png)

**Comment by dheerajwebkul** [comment]
@TristanLDD exactly, which I explained in my last reply in another way :)
https://github.com/PrestaShop/PrestaShop/issues/11331#issuecomment-437310156

Thanks

**Comment by dheerajwebkul** [comment]
@marionf and @TristanLDD 
I have also one doubt, What is the difference between these two design, why you changed the design in V1.7.5.0

You have split the button and add "Other" with the arrow, V1.7.4 just don't have "Other", I think V1.7.4 is the best design

See this screenshot,

![download 4](https://user-images.githubusercontent.com/19220745/48546216-cbddbd00-e8ed-11e8-9fa0-0ee73e0b468d.png)

**Comment by TristanLDD** [comment]
@dheerajwebkul 

The choice was made to split those buttons after taking note that several users were not familiar with that particular behavior, so we decided to highlight the main action and make secondary actions more affordable. 

But, considering the very bad rendering of these buttons on average screen size, I agree with you and I'll say let's go back to the previous design with dropdown buttons on all screen size. 

- One thing we can do to improve this page is to replace those checkboxes with material icons check box, the same that are used in the products list page.

**Comment by Quetzacoalt91** [comment]
Fixed by #11466
