### ISSUE TITLE
Disable Supplier in front office

### ISSUE THREAD

**Issue by dreammeup** [PrestaShop/PrestaShop#11332]
Hello,

I have the same request very regularly from E-merchants.

Most of them do not want suppliers with back office information to be visible in the front office.

Brands, of course, but not their suppliers.

Also, I think it should be disabled by default, and that an option could enable front-office visibility for those who want it.

**Comment by khouloudbelguith** [comment]
Hi @dreammeup,

You can navigate to the BO => Shop Parameters => General page, and disable the "Display brands and suppliers" option.
![image](https://user-images.githubusercontent.com/16067358/48253119-cde3df80-e406-11e8-9d97-f021e1c6db10.png)
Thanks to check & feedback.

**Comment by dreammeup** [comment]
Hello, Thanks for the quick answer,

And, yes that's what i am asking for a change :)

For what I know, nobody want to have the supplier in front-office but they do want to have the brands in front-office.

So it should be 2 separate options, and i think that suppliers should be disable by default.

I'm pretty sure if you make a survey, that will be the answer from the E-merchants.

**Comment by khouloudbelguith** [comment]
@dreammeup, thanks for your feedback.
@marionf, what do you think of his suggestion?
Is that possible to create two different options?
Thanks!

**Comment by marionf** [comment]
I have display brands and suppliers pages at Yes

![capture d ecran_578](https://user-images.githubusercontent.com/13449658/48258774-41411d80-e416-11e8-85cc-fb67a515464a.png)

I have added a supplier

![capture d ecran_580](https://user-images.githubusercontent.com/13449658/48258788-4e5e0c80-e416-11e8-9c38-de26fd95d440.png)

Supplier list module isn't installed

![capture d ecran_581](https://user-images.githubusercontent.com/13449658/48258809-5c139200-e416-11e8-8044-b6cecdc38a14.png)

And suppliers are not diplayed in FO

![capture d ecran_583](https://user-images.githubusercontent.com/13449658/48258851-72b9e900-e416-11e8-9de7-c8f3d9e25eda.png)

Suppliers list is displayed in FO only if the module supplier list is installed and hooked

In the footer I have also no links to supplier page

![capture d ecran_582](https://user-images.githubusercontent.com/13449658/48259069-27540a80-e417-11e8-923b-db9a2e1c17e5.png)

The only way to accees the supplier page when the module is uninstalled is to know the URL and direclty enter it when the option "display brands and suppliers pages" is at Yes
So, I think there is very little chance that your customers see this page

![capture d ecran_584](https://user-images.githubusercontent.com/13449658/48259579-b7df1a80-e418-11e8-8613-58e5dc2a7a36.png)

**Comment by dreammeup** [comment]
Hello,

I think you're wrong.

Because, the supplier pages are listed in the sitemap page, so Google can see them, and index them.

And we don't wan't Google to index them, because the customers (and competitors) will find the page.

So the only way is to disable completely the access to supplier pages.

**Comment by marionf** [comment]
@dreammeup 

In sitemap module, you should select the pages that you don't want to be include in your sitemap

![capture d ecran_585](https://user-images.githubusercontent.com/13449658/48265115-f29e7e00-e42b-11e8-80c2-721dfb3a80ea.png)

**Comment by dreammeup** [comment]
Yes, but i was talking about the sitemap page in front-office : /sitemap
And even if you disable the display everywhere on your website, if the page exist you have a risk that Google find it and index it. So it should be totally disabled, in the sitemap and we should have a 404 error.

**Comment by marionf** [comment]
Instead to have 1 option for brands & suppliers, solution will be to have 2 options:
- 1 for suppliers disabled by default, this way link isn't displayed in /sitemap page
- 1 for brands enabled by default

@colinegin wdyt ?

**Comment by BilalDr** [comment]
Hi everyone,

Currently, if we disable brands and suppliers in the page Shop parameter > General, we haven't access to those page in front office even with link of those page we end up with a 404. 
But we can't manage brands and suppliers separatly. 

So, as you said @marionf, 

- A merchants should be able to configure the display of suppliers and brands separatly with two enable/disable button in the page Shop parameter > General. 

- By default we can disable suppliers page and enable brands page.
 
@TristanLDD what do you think ? Should we add an element to redirect from brands/suppliers page to shop parameter > general page ?

**Comment by eternoendless** [comment]
We should keep in mind that modules may still use the old "composite" (brands+suppliers) setting even after we split it in two. I suggest that the previous option keeps being handled by the form so that:

- If brands AND suppliers are enabled, the composite setting is enabled.
- If either one is disabled, the composite setting is disabled.

Native modules and the core must be updated to stop using the old setting if the new ones are available.

**Comment by jolelievre** [comment]
Juste te be clear @eternoendless, do you suggest to leave the former "composite" setting available in the form?
Which can become confusing for the user.
Or juste keep it in the database so that it's still accessible for modules? And then the new controller should be able to update it based on the two separate settings?
`PS_DISPLAY_SUPPLIERS` being the actual configuration then we would have this kind of rules:

| CONFIGURATION | | | | |
| ------------- | -- | -- | -- | -- |
| PS_SHOW_BRANDS  | 1 | 0 | 1 | 0 |
| PS_SHOW_SUPPLIERS  | 1 | 1 | 0 | 0 |
| PS_DISPLAY_SUPPLIERS  | 1 | 0 | 0 | 0 |

**Comment by jolelievre** [comment]
@eternoendless if we agree on the previous comment, I can take care of it

**Comment by eternoendless** [comment]
I meant only in the database, for backwards compatibility. Ok for the suggested behavior.

This should be documented. A list of all the settings and what they mean would be nice 😄

**Comment by jolelievre** [comment]
What?! You mean there is nowhere a list of the settings?! :P

**Comment by colinegin** [comment]
Hello @jolelievre , shame on us we still need to work on the fonctional specifications :D 
I think we should postpone the fix of this issue if that's ok for you, so that we have a bit more time to work on it.

Thanks !

**Comment by jolelievre** [comment]
Alright, keep me posted when you decided everything ;)

**Comment by TristanLDD** [comment]
Hello ! 

I suggest that we add an information message on each brand and suppliers tabs to inform the user about the default display on his front office, and to redirect him on the page where he can now change his preferences for both: 

![brands_info](https://user-images.githubusercontent.com/27484094/50826000-d4290600-133a-11e9-9196-fb15f87b30b2.png)
![suppliers_info](https://user-images.githubusercontent.com/27484094/50826001-d4290600-133a-11e9-80f1-671150f5524f.png)

**Comment by jolelievre** [comment]
nice idea
But do we always show these messages? If the setting has already been modified it can be confusing
Let's imagine you enable display Supplier but the information card tells you it is hidden by default..

**Comment by TristanLDD** [comment]
@jolelievre Indeed, it can be confusing if the messages are still there after the merchant changed his preferences. 

The easy solution would be to redirect to the parameters page without specifying the default state, so the message is still helpful without being confusing 

The more complicated solution would be to link the wording of the message to the state of the setting so the merchant knows if it's enabled or not without leaving the page

**Comment by jolelievre** [comment]
Yes, both solutions work. And the second one is not really complicated, we just need to switch the message based on a boolean in the configuration.

**Comment by TristanLDD** [comment]
Having this dynamic behavior would be great ! Also there are many other pages where we could use this kind of "augmented" info messages. 

So if we can change the message depending on the state, we would have something like this: 

![artboard](https://user-images.githubusercontent.com/27484094/51106173-4db56e00-17eb-11e9-9c7e-cc7c9934a9ba.png)
![artboard 2](https://user-images.githubusercontent.com/27484094/51106176-5017c800-17eb-11e9-8eb0-235400308c66.png)

@LouiseBonnard Can you have a look at the wording ?

**Comment by jolelievre** [comment]
This would be nice! And I think the message should be split in two parts:
"Go to Shop ... preferences" (always present)

and two other messages for each use case:

"The display of ... **disabled**" and "The display of ... **enabled**"

**Comment by LouiseBonnard** [comment]
Hello there! It can be kept in one piece, in my opinion, but I would rather express it this way:

_By default, displaying brands on your store is **enabled**. Go to Shop Parameters > General to edit settings._ is to be localized in _Admin.Catalog.Notification_

_By default, displaying suppliers on your store is **disabled**. Go to Shop Parameters > General to edit settings._ is to be localized in _Admin.Catalog.Notification_

**Comment by jolelievre** [comment]
But with messages you suggest @LouiseBonnard we don't use "dynamic" display then? We simply inform about the default behavior, not the current one.
That's what we were talking about with @TristanLDD, I thought this message could be confusing if the user has already changed the setting and it does not match the default behavior.

But if I'm the only one troubled by this we can keep it simple.

**Comment by LouiseBonnard** [comment]
You're right, it's just that I'm not fond of the first wording but I can't find a better option.

**Comment by LouiseBonnard** [comment]
What if I drop "By default" and use "Currently" instead?

**Comment by jolelievre** [comment]
Yes, seems fine to me

**Comment by LouiseBonnard** [comment]
Well, it seems there is no best option to express it. So let's keep the following wording:

_The display of your brands/suppliers is enabled/disabled on your store. Go to Shop Parameters > General to edit settings_. in _Admin.Catalog.Notification_

**Comment by ghost** [comment]
That options should be separated as
Show manufacturers (enable/disable)
Show suppliers (enable/disable)

instead of

Show brands and suppliers (enable/disable)

To remove unwanted (in most cases) suppliers page we must delete whole page in SEO & URL panel.

**Comment by jolelievre** [comment]
Hi @PrestaShark 
that's the purpose of this issue, to allow to manage brands and suppliers independently So there will be two buttons available. What still needs to be defined is how do we present and explain this feature in helper blocks.

I think this new feature will be available in 177, @colinegin do you confirm?

**Comment by fabio-zetaweb** [comment]
Hello, 
@khouloudbelguith 
ok to manage manufacturers and suppliers independently, but what will happens to the indexation of those single (suppliers) pages on Google? 
Those pages shouldn't appear on google search.

**Comment by khouloudbelguith** [comment]
>but what will happens to the indexation of those single (suppliers) pages on Google?
Those pages shouldn't appear on google search.

Ping @matthieu-rolland what do you think?

Thanks!
