### ISSUE TITLE
Deprecated: The each() function is deprecated

### ISSUE THREAD

**Issue by parmindermca84** [PrestaShop/PrestaShop#11336]
**Describe the bug**
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in prestashop/smarty/sysplugins/smarty_internal_compilebase.php on line 75

**To Reproduce**
1. Login to prestashop admin
2. Click on Notification (bell) icon > click to messages and click to any message
3. Error will popup with this error.

**Additionnal information**
PrestaShop version: 1.7
PHP version: 7.2

**Comment by parmindermca84** [comment]
This error has been fixed after I replaced this updated file: https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_compilebase.php

So we can close this issue.

**Comment by khouloudbelguith** [comment]
Hi @parmindermca84,

Thanks for your report & your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
