### ISSUE TITLE
* mandatory fields (required fields) ... * Champs requis

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11334]
Hi,

Prestashop 1.7.4.4 in the import section, it says "* Champs requis" (in french) but no field has a "*" ...
I guess, It is a translation problem (* removed)
Could you please fix that ?

Thx

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Could you please provide me a screenshot of your issue.
Thanks!

**Comment by grabelle** [comment]
[FireShot Capture 012 - Importer • Velo Discount_ - http___www.velodiscount.ch_admin18.pdf](https://github.com/PrestaShop/PrestaShop/files/2565438/FireShot.Capture.012.-.Importer.Velo.Discount_.-.http___www.velodiscount.ch_admin18.pdf)

Here is the screencopy

**Comment by khouloudbelguith** [comment]
@grabelle, thanks for your feedback.
This behavior exists in the PS1.6 and PS1.7.
![image](https://user-images.githubusercontent.com/16067358/48257605-3d5fcc00-e413-11e8-95ba-adca24501f8f.png)

The expression `* Required field ` is displayed under the `Available fields`, but there is no field with the `*` symbol.
It could an improvement.
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment]
There are some required fields for Combinations, customers, address, alias and shops.
For products, categories, brands and suppliers only name is required
