### ISSUE TITLE
[Critical] CMS page save empty if words in content have russian (cyrillic) letter 'И' PS 1.7.4.4

### ISSUE THREAD

**Issue by p2rcoder** [PrestaShop/PrestaShop#11340]
**Describe the bug**
When edit or add cms page content I can't save text which contain russian letter 'И'

**To Reproduce**
try to save 'АБВГДЕЁЖЗКЛМНОПРСТУФХЦЧШЩЭЮЯ' - this work (without 'И')

'АБВГДЕЁЖЗКЛИМНОПРСТУФХЦЧШЩЭЮЯ' - this bug 

**Screenshots**
https://www.screencast.com/t/EWtPHpS4E58X - test
https://www.screencast.com/t/P4YU8fEPmn - result

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6

**Comment by p2rcoder** [comment]
this is very serious bug because I can't save any text without 'И'

**Comment by p2rcoder** [comment]
need workaround

**Comment by p2rcoder** [comment]
DB utf8_general_ci

**Comment by p2rcoder** [comment]
in demo 1.7.4.2 its work correct

**Comment by khouloudbelguith** [comment]
Hi @p2rcoder,

I did not manage to reproduce the issue with the last version 1.7.4.4.
https://drive.google.com/file/d/1JemCK5OMzEG6KYc7RW2gpmdomarE9cwv/view
Did installed fresh install 1.7.4.4 with Russia country? or did you import the pack localization Russia?
Thanks!

**Comment by p2rcoder** [comment]
I installed fresh PS and then template. Work correct after I change collation for this field https://www.screencast.com/t/iaAItwTPoBL to cp1251_general_ci but looks like that this problem at all places on the site... product title https://www.screencast.com/t/mqMcNZumeqV8 (also letter 'И')

**Comment by khouloudbelguith** [comment]
@p2rcoder, could you please try to navigate to your BO => International => Translations => Select the "Russian" language and click on "Add or update a language" button.
Thanks to check & feedback.

**Comment by p2rcoder** [comment]
I did this - nothing changed. https://www.screencast.com/t/C00gMKz3
I have several sites on this hosting and this DB - it is all OK

**Comment by khouloudbelguith** [comment]
@p2rcoder, did you check the encoding of your database?

**Comment by p2rcoder** [comment]
cp1251_general_ci
and all other sites with the same encoding but they work without such issue
https://www.screencast.com/t/ftMRGHlPN8Lc

**Comment by p2rcoder** [comment]
I changed DB encoding to utf8_general_ci - didn't help

**Comment by p2rcoder** [comment]
problem present on clean install without any modules and templates... 
db encoding: cp1251_general_ci
language during instalation: Russian
country: Belarus
all tables after instalation utf8_general_ci

in DB:
https://www.screencast.com/t/OUhplgZ0
https://www.screencast.com/t/fMmeWziEx7i

this is after clean install

**Comment by p2rcoder** [comment]
I have tried to change DB encoding  to utf8_general_ci before install PS - result the same

all charset variables:
https://www.screencast.com/t/6pqON0To

**Comment by p2rcoder** [comment]
1.7.3.4 - the same error
1.7.0.0 - all OK, installed without such problem https://www.screencast.com/t/gVYtfSO3u

please help to find workaround

**Comment by p2rcoder** [comment]
I moved site to new hosting with php 7.2 - PS installed without such problem

**Comment by khouloudbelguith** [comment]
Hi @p2rcoder, It seems that your issue is not a PrestaShop's core bug but most likely a server configuration.
I did not manage to reproduce the issue with Ps1.7.4.4 / language Russian / country: Belarus
Despite our several trials, we could not reproduce your issue with the provided information.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
