### ISSUE TITLE
Menu font size changed on 'Theme & Logo' page

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11346]
**Menu font size changed on 'Theme & Logo' page**
On "AdminThemes" Controller, 'Theme & Logo' page, Admin left menu font design changed, Even page font design also changed.

**To Reproduce**
1. Go to 'Design -> Theme & Logo'
2. Click on 'Theme & Logo' tab
4. See font size of the left menu, its smaller than the default

**Screenshots**
![stats ps175 beta](https://user-images.githubusercontent.com/19220745/48298674-2a1e3080-e4e7-11e8-8586-df150d486ebf.png)
![theme logo ps175 beta](https://user-images.githubusercontent.com/19220745/48298676-2ee2e480-e4e7-11e8-88ba-98c42d91717d.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 Beta 1
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
These changes are made in this https://github.com/PrestaShop/PrestaShop/pull/8637, so we are able to navigate in the unwrapped menu and we can access any section.
1. At click on a 1st level entry, entries drop down, the background of the global section (entries + subentries) is changed
1.1 Picto of the 1st level entry switch to another color
1.2 Text of the 1st level entry switch to bold 12 
1.3 A small rectangle, 4x30px, appears on the left of the picto
2. At 2nd click on the same 1st level entry
2.1 Closed with the reverse effect
2.2 Highlight remains the same
3. At click on a 2nd level entry
3.1 The same highlight for the 1st level entry
3.2 2nd level entry clicked switch to bold
3.3 All other previously opened 1st level entries closed

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
