### ISSUE TITLE
How can we deal with known vulnerabilities?

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#11356]
**Describe the bug**
How can we deal with known vulnerabilities?

How about add X-XXS header?

```
<IfModule mod_headers.c> 
  Header set X-XSS-Protection "1; mode=block" 
</IfModule>
```

And maybe patch the used version against:
https://github.com/twbs/bootstrap/pull/23679
https://github.com/jquery/jquery/pull/2588
https://github.com/jquery/jquery-ui/commit/f2854408cce7e4b7fc6bf8676761904af9c96bde
https://github.com/jquery/jquery-ui/commit/7e9060c109b928769a664dbcc2c17bd21231b6f3
https://github.com/jquery/jquery-ui/pull/1622

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: 7.2.x

**Comment by PierreRambaud** [comment]
It's an idea but you can't force everyone to block a page if the browser "think" it's a XSS.
We need to update dependencies but not now, we can't introduce B/C breaks before 1.8.

**Comment by MathiasReker** [comment]
Okay, I understand.

**Comment by matks** [comment]
> It's an idea but you can't force everyone to block a page if the browser "think" it's a XSS.
> We need to update dependencies but not now, we can't introduce B/C breaks before 1.8.

What about allowing people to enable this ? As an option ?

**Comment by MathiasReker** [comment]
@matks yes, that could be nice! There could be a section in BO to configure security headers.

Example of output in httacess file:

```
# Extra Security Headers
<IfModule mod_headers.c>
   Header set Content-Security-Policy "default-src 'unsafe-inline' 'unsafe-eval' 'self' *.googleapis.com *.gstatic.com;"
   Header set X-XSS-Protection "1; mode=block"
   Header always append X-Frame-Options SAMEORIGIN
   Header set X-Content-Type-Options nosniff
   Header set Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
</IfModule>
```

It should be possible to select values for each header. Is it overkill since it is easy to hardcode?

**Comment by MathiasReker** [comment]
doc: https://infosec.mozilla.org/guidelines/web_security

**Comment by PierreRambaud** [comment]
Watch out:
> New websites should use this header, but given the small risk of false positives, it is only recommended for existing sites. This header is unnecessary for APIs, which should instead simply return a restrictive Content Security Policy header.

The best way is to secure the core and its dependencies.

**Comment by MathiasReker** [comment]
I retract my suggestion before about being able to configure all security headers - it will be overkill.
