### ISSUE TITLE
Search bar incomplete in BO

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11350]
Hello,

The search bar in BO in different for:
- index.php/product/catalog
https://tof.cx/image/VaJs1
- other page (index.php?controller=AdminDashboard for example)
https://tof.cx/image/VaD8V

Only in product, we can select which kind of thing we want search.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2.11

**Comment by Rolige** [comment]
Hi @BenTen,

You just have to press the magnifying glass icon and the categories will appear.

![image](https://user-images.githubusercontent.com/2866694/48308528-d6363a80-e52c-11e8-8a0d-7c6217d73e30.png)


Regards!

**Comment by BenTen** [comment]
.... I didn't notice :/
But why it's not the same everywhere?

**Comment by Rolige** [comment]
Because one is with the new symfony templates and others are not.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

@Rolige said, the dashboard page is not migrated to Symfony, it will be migrated in the next versions.
![image](https://user-images.githubusercontent.com/16067358/48336635-1696d500-e661-11e8-9467-2614aa48e51e.png)
But, the product page is migrated to Symfony page, so they have not the same behavior.
![image](https://user-images.githubusercontent.com/16067358/48336888-b7859000-e661-11e8-8e3e-fed82cd792dd.png)
I close the issue, feel free to open a new one when needed.
Thanks!
