### ISSUE TITLE
1-click upgrade from 1.6 to 1.7 on Prestashop error

### ISSUE THREAD

**Issue by rafzkontorsmobler** [PrestaShop/PrestaShop#11361]
I use 1-click upgrade on Prestashop to upgrade from 1.6 verison to 1.7. But when I want to upgrade there comes an error saying; [Ajax / Server Error for action unzip] textStatus: "error " errorThrown:"temporarily overloaded " jqXHR: " 

PrestaShop version: 1.6.1.11
PHP version: 7.0

I have also bought the MigrationPro module.

How do I solve this problem so i can upgrade, or is there another solution to upgrade to 1.7?

**Comment by khouloudbelguith** [comment]
Hi @rafzkontorsmobler,

What is the exact of the 1-click upgrade did you use?
Thanks!

**Comment by rafzkontorsmobler** [comment]
> Hi @rafzkontorsmobler,
> 
> What is the exact of the 1-click upgrade did you use?
> Thanks!

![rrrr](https://user-images.githubusercontent.com/44974760/48355884-51b2fb80-e695-11e8-8644-13ce278a795d.png)

**Comment by khouloudbelguith** [comment]
@rafzkontorsmobler, so it is the latest downloaded from addons?
1-click upgrade v4.4.1?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt
you can find it in the Project_Folder/Admin_folder/autoupgrade/tmp path.
Thanks!

**Comment by Quetzacoalt91** [comment]
I guess you're using a shared environment to run your shop. `temporarily overloaded` is written in your error message, which means your hosting proving voluntarily prevent too many "greedy" PHP requests to run on your website.

**Comment by Quetzacoalt91** [comment]
Hi,

This issue is related to the environment, nothing can be done on the module to prevent this issue to occur. As said in my previous message, please contact your hosting provided to see how to prevent this error to occur.

Closing as "nothing to change".
