### ISSUE TITLE
Display error when client groups are Tax excluded

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#11360]
Hello the team !
I sell only to professionals and I come to bring you some errors of displays on 1.7!
In addition to display errors all along the order see [BOOM-2330], in the shopping cart and on the order confirmation, when customer groups are displayed in tax excl., there is also a display problem in the customer's history and in the detail of the order.
The total amount must always be the subtotal tax excl + tax, even when the taxes are equal to 0!
See attached photos.

customer history
![history](https://user-images.githubusercontent.com/44966543/48353632-31347280-e690-11e8-9405-fa0c1e105f9c.png)

Order details
![history-details](https://user-images.githubusercontent.com/44966543/48353626-2d085500-e690-11e8-888b-83ef56e2de75.png)

**To Reproduce**
---   groups are Tax excluded and place an order

**Additionnal information**
PrestaShop version: 1.7.2.x, 1.7.3.x, 1.7.4.x, 1.7.5.0b
PHP version: 7.1.20

Can you add to the [BOOM-2330] for problem solving in 1.7.6.0 please!
Cordially

**Comment by khouloudbelguith** [comment]
Hi @Peterits,

Thanks for your report.
I manage to reproduce the issue with the PS1.7.4.4.

- Display tax in the shopping cart in enable in the International /Taxes page
- Price groups display is Tax excluded

In the order history, the total is displayed only with tax excluded, it should be more clear.
![image](https://user-images.githubusercontent.com/16067358/48353702-5f19b700-e690-11e8-886c-ecd43d45fd02.png)
Related to: #10013; #9698

**Comment by Peterits** [comment]
Hello, That's exactly it, thanks, if it can be fixed on version 1.7.6.0 at the same time as the command display, it would be cool!
I was able to solve the problem of the orders and the basket by modifying the theme, but I am not on code in the time, but if it can help merchant, it works for the moment, I give you the code:

To add and display the price including tax on the orders and carts of the theme:

![panier-ttc](https://user-images.githubusercontent.com/44966543/48360801-474a2f00-e6a0-11e8-99d1-d1d4b434ce80.png)

![panier-details](https://user-images.githubusercontent.com/44966543/48360812-4ca77980-e6a0-11e8-8e59-101946795e88.png)


cart_detailed_totals.tpl

    <div class="cart-summary-line cart-total">
      <span class="label">{l s='Total' d='Shop.Forms.Labels'}</span>
	  <span class="value">{$cart.totals.total_including_tax.value}</span> 
    </div>


cart-summary-totals.tpl

    {block name='cart_summary_total'}
    <div class="cart-summary-line cart-total">
      <span class="label">{l s='TOTAL' d='Shop.Forms.Labels'}</span>
      <span class="value">{$cart.totals.total_including_tax.value}</span>
    </div>


Pour order-comfirmation and history.tpl, I do not know how to do!

**Comment by khouloudbelguith** [comment]
@Peterits, 
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Peterits** [comment]
> @Peterits,
> Would you be willing to make a pull request on GitHub with your code suggestion?
> https://github.com/PrestaShop/PrestaShop/tree/develop
> Thank you!

The code is not complete but if it helps!
