### ISSUE TITLE
PS 1.7, wrong shop URL in back-office on subdomain

### ISSUE THREAD

**Issue by Lndaw** [PrestaShop/PrestaShop#11364]
**Describe the bug**

One of our customers experience strange behaviour in the shop URL in the back-office, causing problems using the back-office.
The problem only occur on the admin pages that uses the new 1.7 link structure, e.g. the product admin page and the module admin page.
The URL to the product admin page should be 
https://boekwinkel.levendiguitgever.nl/admin574tzrnee/index.php/product/catalog?_token=<token>
But is actually:
https://boekwinkel.levendiguitgever.nl/boekwinkel.levendiguitgever.nl//admin574tzrnee/index.php/product/catalog?_token=<token>

The domain is showing twice on the URL.

**To Reproduce**

2. Click on 'product page'.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![capture](https://user-images.githubusercontent.com/3532079/48404730-3ac1e700-e731-11e8-89fc-98df5b9e94ce.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.23

**Comment by khouloudbelguith** [comment]
Hi @Lndaw,

With fresh install PS1.7.4.2, I did not manage to reproduce the issue.
Could you please navigate to your BO => Shop Parameters => Traffic & SEO, check the SHOP URL:
- Shop domain 
- SSL domain 
- Base URI

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@Lndaw,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by knekke** [comment]
Trying to setup a subdomain multistore I ran across the same error.
First of all what is the correct procedure for subdomains?
The help page says: 
> Do not create any subdomain or subfolder yourself, either on your server or your computer: PrestaShop takes care of creating the path for you on your server. When the customer requests this path, PrestaShop will recognize the shop and serve the files and data for the correct store automatically.
>
So if I try it like this and I enter a non-existing subdomain for the shop URLs:

- On hitting "save" I get a 'page not found' error because of the former mentioned double URL
- I go on by correcting the URL and get confirmation that it is set, but I can't access the shop on that subdomain

If I use an existing subdomain that redirects to the original shop:

- Backoffice works fine
- The subdomain only serves the main shop

any ideas?


btw: The double URL Error also occurs on setting a virtual URL.

**Comment by khouloudbelguith** [comment]
Hi @knekke,

About the multistore URL, in the 1.7.5.0, there are some fixes, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9450
But in the 1.7.5.0beta1, when I try to edit the URL, clicking on save, I'm redirected to the page not found with a double URL, this issue exists also in the PS1.7.4.4. Only when I try to edit the URL of the first shop.
1.7.5.0BETA1 => https://drive.google.com/file/d/1qhjgn5ZZPdavNL8GNXz31UczcsOiXY21/view
@jolelievre what do you think?
Thank!

**Comment by jolelievre** [comment]
Hey I will look into it
But first @knekke can you tell me which version you are using?
1.7.4.x or 1.7.5.0? some fixes have indeed been made for multi shop urls, but mainly focused on legacy urls
there might be some issues on symfony urls left, from what you said @khouloudbelguith it seems the bug also exists on 1.7.5, I'm gonna add it to our Kanban

**Comment by jolelievre** [comment]
hello @khouloudbelguith I was able to reproduce your bug
it seems to happen each time we update a store url informations, wether you update the main one or a subdomain, the modification is saved but the redirection is wrong, this should be fixable

On the other hand I'm not sure this is the exact same problem as @Lndaw I only reproduce the double url after saving a multistore settings, but you have this double url even on the product page
Could you please show the settings of your store? did you set any value in physical or virtual url?
or maybe you could show a copy of the rules set in your .htaccess file, especially the rewrite rules to see if they might have been incorrectly generated

**Comment by jolelievre** [comment]
@knekke about your questions, you need to set your domains to target your prestashop folder
all your domains must point to the same PrestaShop installation/folder
And then PrestaShop manages the different urls and is able to detect which store the user needs to see based on the url
