### ISSUE TITLE
Not possible use direct URL to product combination

### ISSUE THREAD

**Issue by martinznv** [PrestaShop/PrestaShop#11366]
**Describe the bug**
I found weird behavior in 1.7.4.4. with opening direct URL of product combination. It is necessary for Google shopping when sending them products with separate URL. It is necessary when you have URL of "black" combination, shop will display "Black" product choosen.  

**To Reproduce**
1. Find product with combination. Open it. It will open default combination (product/color-black). 
2. Choose other combination (product/color-white) 
3. Copy this URL and paste it in another window. It will open default combination (black), but the URL will say white. 

**Additionnal information**
PrestaShop version: 1.7.4.4.
PHP version: 7.1.

**Comment by khouloudbelguith** [comment]
Hi @martinznv,

Thanks for your report.
I did not manage to reproduce the issue with the last version stable 1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1nrWLpa0n4cKrDMe9thEaw38Vp0pQkJV7/view
Thanks to check & feedback.

**Comment by wzzly** [comment]
@martinznv I have the same problem. Did you find a solution?
