### ISSUE TITLE
Checkbox "show condition" always checked when editing product

### ISSUE THREAD

**Issue by IntoTheBlueAt** [PrestaShop/PrestaShop#11368]
**Describe the bug**
When editing an existing product, on the information tab, the checkbox for for "show condition" is always checked, even if it was unchecked before. When saving the product, the "show condition" flag in the database is set to 1 again.

**To Reproduce**
1. Go to "edit product"
2. Click on "information"
3. Scroll down to "show condition" checkbox
4. Find checkbox checked even if "show condition" flag in database ps_product is set to 0

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Barbwire,

I did not manage to reproduce the issue with the last version 1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1pb0QsQaUrTcmgvEGlJ-CjNFNaGbs-wxk/view
Thanks to check & feedback.

**Comment by Rolige** [comment]
@Barbwire Maybe your hosting have some kind of cache enabled in MySQL and/or php, if so, this behavior is completely normal and the changes have no immediate effect.

Try clearing the cache from the performance tab.

**Comment by IntoTheBlueAt** [comment]
Hello, thank you for your quick reply!
It seems to be caused by the fact that I imported all my products (directly to database) from an old store (PS1.6). If I manually uncheck and save or vice versa in BO it works as expected.

![grafik](https://user-images.githubusercontent.com/10073297/48422588-44fada00-e75f-11e8-8f63-66b31e9a0626.png)

Sorry for the german interface :-)

**Comment by khouloudbelguith** [comment]
Hi @Barbwire,

You can find the full schema for 1.7.4.4 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by IntoTheBlueAt** [comment]
Hello @khouloudbelguith 
Thank you for leading me into the right direction, it is definitely a problem caused from the data import.
I will close the issue as there is none :-)
Thank you and have a nice day!

**Comment by khouloudbelguith** [comment]
@Barbwire, you are welcome.
Feel free to open a new one when needed.
Thanks!
