### ISSUE TITLE
Multiple carriers with same name & delay key will not be display

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11379]
**Describe the bug**
If two carriers with the same name and transit time (delay) then only one carrier display when we edit product for assign carrier, This is because we are creating the key with name and delay which can be same for multiple carriers. See this code

Code: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L71

Some shipping providers will create the same name and delay time carrier like DHL and other. they maintain with the service code of carriers in the different zone.

**To Reproduce**
1. Go to 'Shipping -> Carriers'
2. Click on 'Add Carriers'
3. and add two carriers with the same name & delay (Transit time)
4. Edit any product and see only one carrier display

**Screenshots**
![download 2](https://user-images.githubusercontent.com/19220745/48478266-c7e86700-e829-11e8-9243-dcf0f5a66b1b.png)
![download 3](https://user-images.githubusercontent.com/19220745/48478269-cb7bee00-e829-11e8-8c72-b4361e6c5a33.png)

**Additionnal information**
PrestaShop version: 1.7.4.4 & 1.7.5.0 beta also
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4 / PS1.7.5.0beta1.
https://drive.google.com/file/d/17O9oZ72YwPubtC8B6a-yxrGNaCwL-Wnt/view
We will see how to fix it.
Thanks!

**Comment by dheerajwebkul** [comment]
Thanks @khouloudbelguith 

This is because it displays by Symfony ChoiceType
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L147

And ChoiceType will render key as a text.

So it looks like to change the way we display.

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, Would you be willing to make a pull request on GitHub with a code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by dheerajwebkul** [comment]
@khouloudbelguith Yes, I can,

I think we have to add one more unique key to display like because displaying the same name is not feasible, we can append any id with it.

PS1750 Beta (Pick-up in store) - 1
PS1750 Beta (Pick-up in store) - 2

But I don't think PrestaShop will accept it :(, May they can fix this is a more better way

**Comment by matks** [comment]
Implemented in https://github.com/PrestaShop/PrestaShop/pull/12379
