### ISSUE TITLE
Major forum issues missing form elements

### ISSUE THREAD

**Issue by naps1saps** [PrestaShop/PrestaShop#11374]
I can't find any way to report this other than here.

I am trying to update my question on the forum or post a new question and the message box is missing in every browser I try.  I cannot access the the site menu on my phone the button does nothing but I think I'm logged in.  There is something seriously wrong.  I click reply and it says required form missing.  I try to edit but there is no box to edit.  Start new topic page is blank.  My username is naps1saps.

**Comment by khouloudbelguith** [comment]
Hi @naps1saps,

We have made a major upgrade of the forum (+ default theme), you can follow this [link](https://www.prestashop.com/forums/topic/937296-maintenance-of-the-forums/) for more details.
About your issue, l will transfer it.
Thanks!

**Comment by naps1saps** [comment]
Appears it was resolved overnight.  I didn't see any notifications of maintenance so maybe pass on to include a banner during major maintenance tasks :)On Nov 14, 2018 12:04 AM, khouloudbelguith <notifications@github.com> wrote:Hi @naps1saps,
We have made a major upgrade of the forum (+ default theme), you can follow this link for more details.
About your issue, l will transfer it.
Thanks!
