### ISSUE TITLE
Add total_shipping_tax_excl and total_shipping_tax_incl in email data in /classes/PaymentModule.php

### ISSUE THREAD

**Issue by sitte** [PrestaShop/PrestaShop#11396]
**Is your feature request related to a problem? Please describe.**
No way to use total shipping tax excl in order_conf email. 

**Describe the solution you'd like**
In Shop where everything is tax excluded its inconsistency

**Describe alternatives you've considered**
overriding is not easy/imposible and total_shipping_tax_excl and total_shipping_tax_incl are right in class

**Additional context**
Just add:
'{total_shipping_tax_excl}' => Tools::displayPrice($order->total_shipping_tax_excl, $this->context->currency, false),
'{total_shipping_tax_incl}' => Tools::displayPrice($order->total_shipping_tax_incl, $this->context->currency, false),

in line 812 of /classes/PaymentModule.php

**Comment by khouloudbelguith** [comment]
Hi @sitte,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by sitte** [comment]
it's my first pull, I hope it's properly prepared: https://github.com/PrestaShop/PrestaShop/pull/11397
