### ISSUE TITLE
It is impossible to change the position of blocks in linklist module

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11404]
**Describe the bug**
It is impossible to change the position of blocks in linklist module by drag & drop. The new positions of blocks are not saved.

**To Reproduce**
1. Go to Link List Module > Configure
2. Drag & drop blocks
3. Shows successfully updated.
4. After refreshing page changes will reverted.

**Additionnal information**
PrestaShop version: 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Here's the PR: https://github.com/PrestaShop/ps_linklist/pull/48 to solve the issue.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9950
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9950
