### ISSUE TITLE
Can't update to 1.7.4.4

### ISSUE THREAD

**Issue by Alenici** [PrestaShop/PrestaShop#11409]
**Describe the bug**
When updating the version from 1.7.3 to 1.7.4.4 by 1Click update, the procedure fails with the follwing error:

Tools14.php line 1399 - Out of memory (allocated 75288576) (tried to allocate 66904096 bytes)
PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php line 57 - vsprintf(): Too few arguments

I already increased the allocated memory until 2048MB but the problem still going on.

Talked with the provider, ti said the limit is inside Prestashop and not on server side.

Tried also to change PHP version to 7.1 and 7.2 but no solution yet

**To Reproduce**
1. try updating by 1Click update module

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Alenici,

Thanks for your report.
What is the exact version of the 1-click upgrade did you use?
Thanks!

**Comment by Quetzacoalt91** [comment]
Also, what language have you selected?

**Comment by Alenici** [comment]
Hello,
the 1-click upgrade version is 4.4.1.
About the language, i'm using italian language only.
I tried also a manual backup and running 1-click upgrade without backup option but still getting the same error.

**Comment by khouloudbelguith** [comment]
Hi @Alenici,

Thanks for your feedback.
I did not manage to reproduce the issue after upgrade from 1.7.3.4 to 1.7.4.4, using Itlay country / Italian language & using the 1-click upgrade v4.4.1.
![image](https://user-images.githubusercontent.com/16067358/48609203-b3b87d00-e983-11e8-9518-2603db5f142f.png)
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by Alenici** [comment]
Hi @khouloudbelguith 
thanks for your kind reply.
The log file is here attached.
Thanks again
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2588717/log.txt)

**Comment by khouloudbelguith** [comment]
@Quetzacoalt91, what do you think?
In his log file, he has this error also : `[INTERNAL] /home/mhd-01/www.sitename.com/htdocs/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php line 57 - vsprintf(): Too few arguments`
Thanks!

**Comment by Quetzacoalt91** [comment]
The error is obviously this one:
`
[2018-11-06 11:46:07] [INTERNAL] /home/mhd-01/www.sitename.com/htdocs/modules/autoupgrade/classes/Tools14.php line 1400 - Out of memory (allocated 75288576) (tried to allocate 66904096 bytes)
`

You should update your PHP configuration to increase the `memory_limit` value.

**Comment by Alenici** [comment]
Hi @Quetzacoalt91 
thanks for your comment.
It was the first thing i did... I have increased the memory limit value until very high value but still have the same error and always at the same level (allocated 75288576 tried to allocate 66904096 bytes)

**Comment by Quetzacoalt91** [comment]
What value is currently set? You could probably set en unlimited value while you upgrade your shop. :)

**Comment by Alenici** [comment]
The default value is 256M and the last try was 2048M... seems it needs not over than 145M so it's already more over the necessary. I will try tonight setting a higher value and I will let you know if it worked or not. Thanks for now

**Comment by Alenici** [comment]
Hello @khouloudbelguith and @Quetzacoalt91,
happy monday for you all.
I increased the memory limit until 12800 and 25600 but still have exactly the same error.
Here attached the log file
i don't know what to think about  it...
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2594526/log.txt)

**Comment by khouloudbelguith** [comment]
@Alenici, it is the same error as before `Out of memory (allocated 75288576) (tried to allocate 66904096 bytes)`
Thanks!

**Comment by Alenici** [comment]
Yes @khouloudbelguith , i've got it also... seems it's not actually related to the memory_limit value.. so.. how to fix it? any suggestion or idea? have a nice day!

**Comment by khouloudbelguith** [comment]
@Alenici, in my case, I did not manage to reproduce the issue.
@Quetzacoalt91, what do you think?
Thanks!

**Comment by Quetzacoalt91** [comment]
This is clearly something related to the environment, not the upgrade process itself. I would have a look at the PHP config (http://php.net/manual/en/function.phpinfo.php) to make sure the values have been properly applied.

**Comment by Alenici** [comment]
@Quetzacoalt91 and @khouloudbelguith many thanks for your kind reply, much appreciated. I checked the  PHP config and it seems ok... do you wanna check it also? May i attach the file here? If i will not fix it, it means i will not update it anymore... not good

**Comment by Quetzacoalt91** [comment]
It would be great to show a screenshot of your PHP config page, just for confirmation. Also, you should ask your hosting provider is there is memory limitation of it side about memory consumption.

**Comment by Alenici** [comment]
Thanks @Quetzacoalt91 
here attached the php screenshot. Since it's longer more than 24 pages i hope the data i selected are enough.
![php01](https://user-images.githubusercontent.com/45073496/48851959-a3056e00-edac-11e8-847d-18a03da095ad.jpg)
![php02](https://user-images.githubusercontent.com/45073496/48851961-a3056e00-edac-11e8-9a1a-9188222885f9.jpg)
![php03](https://user-images.githubusercontent.com/45073496/48851963-a39e0480-edac-11e8-8d23-ee8fe2d9c6b8.jpg)

**Comment by Quetzacoalt91** [comment]
Well, the value is properly taken in account. Would you mind disable the memory limit for testing purpose, y setting the value as `-1`? http://www.php.net/manual/en/ini.core.php#ini.memory-limit

Once you're done with this issue, you should bring back the initial value. :)

**Comment by Alenici** [comment]
Hello @Quetzacoalt91 
i did it, value -1 and is properly taken in account but...
[INTERNAL] /home/mhd-01/www.sitename.com/htdocs/modules/autoupgrade/classes/Tools14.php line 1400 - Out of memory (allocated 75288576) (tried to allocate 66904096 bytes)...
no way... 
The provider said maybe something in prestashop decrease the available memory otherwise the allocated part would have been closed to the set value

**Comment by Quetzacoalt91** [comment]
Now I see a difference between the error I usually (`Allowed memory size of 262144 bytes exhausted`) see and yours (`Out of memory`)... Sorry I missed that during all this time.
https://stackoverflow.com/questions/8808125/random-php-fatal-error-out-of-memory-errors

You should retrieve the current available memory you have from your hosting provider and temporarily increase it if possible. On our side, having your current memory limit would be an objective to aim for improving the module.

**Comment by Quetzacoalt91** [comment]
To give more details on what could be the reason, the downloaded package of PrestaShop is stored in RAM before being copied in the file system. Depending on the package you try to use, you can easily reach the memory limit of your server.

I'll have a look to stream the file instead, but on your side, you can download the package you want to upgrade to, copy it in the folder `<admin>/autoupgrade/download/` and use the option "local archive" of the module.

**Comment by Alenici** [comment]
Hello @Quetzacoalt91 
thank you for your help, i think you are right.
Now I have the following error:
Impossibile aprire il zipFile /home/mhd-01/www.sitename.com/htdocs/admin/autoupgrade/download/prestashop_1.7.4.4
[ERROR] Error on extracting archive using PclZip: PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature.
Should i extract the archive before uploading it?

Ah, there is also this one
Unable to extract /home/mhd-01/www.sitename.com/htdocs/admin/autoupgrade/download/prestashop_1.7.4.4.zip file into /home/mhd-01/www.sitename.com/htdocs/admin/autoupgrade/latest folder...

**Comment by Quetzacoalt91** [comment]
You don't have to. However, the file you uploaded seems to be corrupted. Could you try again downloading / uploading it?

**Comment by Alenici** [comment]
Hello @Quetzacoalt91 
you were right, the file was corrupted. 
I was running the upgrading but sadly it didn't finish because of timeout of the server and i couldn't save the error message on time... anyhow, the backoffice and frontoffice seems working good, I will check it in all his functions to see if everything still working well.
Just one thing.. the folders <admin>/autoupgrade/download/ and <admin>/autoupgrade/latest/ are now containing the archive and lot of files but i think they should be empty... I guess it happened because the updating couldn't get completed (I also tried to check if it is possible running it once more but seems can't...  the tool says "55 file modifications have been detected, including 54 from core and native modules"
However, i upgraded it now, thank you so so so so so so much for your help and also thanks @khouloudbelguith for your assistance

**Comment by Quetzacoalt91** [comment]
I'm glad to see you could move forward in the process.

You can find the complete log at the same place as before, in `<admin>/autoupgrade/tmp/log.txt`. You will be able to know where the process could go before the timeout occurred (I hope the step UpgradeDatabase could ran completely).

In the last steps, the two folder you are mentioning are supposed to be emptied. You can safely delete their content. For the issue you initially reported, an improvement has just been opened on the module repository: https://github.com/PrestaShop/autoupgrade/pull/192

**Comment by Alenici** [comment]
Hello @Quetzacoalt91 
i checked the log file and i can't get if the database had been upgraded... i afraid it's not even if the site is working well... do you think it's possible to complete the update?
Here attached the log.txt
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2615533/log.txt)

**Comment by Quetzacoalt91** [comment]
It is, you can read in your log file:

```
[2018-11-22 16:14:19] Database upgrade OK
````

**Comment by Alenici** [comment]
Thank you so much for your help @Quetzacoalt91 
I proceed now deleting the two folders content as you told me.
Thanks again
