### ISSUE TITLE
Can't configure a linklist module

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11400]
**Describe the bug**
Can't configure a linklist module

**To Reproduce**
1. Go to  Module manager > Link List
2. Click on 'Configure'
3. Internal server 500 error

**Screenshots**

![screenshot-localhost-2018 11 15-15-44-28](https://user-images.githubusercontent.com/40850057/48546079-61c51800-e8ed-11e8-873e-8fba6f65c8b8.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 Beta 1

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

I did not manage to reproduce the issue with PS1.7.5.0beta1 & the Link Widget module v2.1.5 by PrestaShop.
I attached a video record.
https://drive.google.com/file/d/10HcodFkHvxRXmUrwcYJ8iFaswJHGPf8-/view
What is the exact version of the link widget module did you use?
Thanks!

**Comment by dineshbadrukhiya** [comment]
I'm using Link List  module v2.1.5.

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, could you please try to uninstall this module, delete the link widget module folder, clear cache, check & feedback.
Thanks!

**Comment by dineshbadrukhiya** [comment]
Okay. I will update you.

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, thanks!
Waiting for your feedback.

**Comment by dineshbadrukhiya** [comment]
After uninstalling not able to access module manager page.

![test](https://user-images.githubusercontent.com/40850057/48547856-933fe280-e8f1-11e8-962e-03dd92c45359.png)

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, it is ok in my case.
https://drive.google.com/file/d/1_BPh2wf4CnJGMmajP4FX8UXllWIglwe3/view
Could you please try to remove the ps_linklist module folder into your path Project_Folder/modules/
Thanks!

**Comment by dineshbadrukhiya** [comment]
Hello @khouloudbelguith 
I have uninstalled and cleared cache. After re-installing it facing error as in screenshot below.

![screenshot-localhost-2018 11 15-16-23-57](https://user-images.githubusercontent.com/40850057/48548495-16ae0380-e8f3-11e8-96a0-39b78c100e84.png)

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith I did it manually.

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, yes you are right.
I uninstalled the ps_linklist v 2.1.5 & I installed the new version ps_linklist v3.0.0, but I have an exception in the configuration page.
![image](https://user-images.githubusercontent.com/16067358/48549356-d9844a00-e8cf-11e8-8fab-3f803bdb011c.png)
@jolelievre @marionf what do you think?
Thanks!

**Comment by jolelievre** [comment]
this is strange indeed, I'm gonna look into it
which version of PrestaShop are you using? 1.7.5.0.beta1 ? and version 3.0.0 of the module?
also are in debug mode or prod mode?

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I checked the issue with PS1.7.5.0beta1 & the ps_linklist v3.0.0.
Thanks!

**Comment by dineshbadrukhiya** [comment]
Hi @jolelievre 
I had tried with PS 1.7.5.0 beta 1 and ps_linklist v3.0.0 & v2.1.5 in the debug mode.

**Comment by jolelievre** [comment]
Hi @khouloudbelguith @dineshbadrukhiya 
I was able to reproduce the two bugs, the route one is indeed linked to the Router cache, the class generated for the router is not aware of the module routing file so it does not update itself
It is linked to another issue as well on upgrade https://github.com/PrestaShop/ps_linklist/issues/52
I'm gonna try to fix this issue in the module

About the other bug you had with `record_route_params` actually some modifications have been made on the PositionColumn **after** the beta was built It works on the last version in **1.7.5.x** branch and will of course work in the final release
