### ISSUE TITLE
Admin - Product supplier 

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11401]
Hi,
I have created one supplier in the BO.
I can't see on the product sheet (any tabs) the field to specify the supplier ... where is it ?
Thanks for your help.

Prestashop 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

You can find it, in the BO => Catalog => Products => product page => Options Tab => scroll to the buttom of the page & you can find it.
I attached a video record.
https://drive.google.com/file/d/1TxboQCb_3-as47rEPzolOldQ6I-FwZNg/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
