### ISSUE TITLE
[EPIC] Create addons redirection block for specific modules 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/PrestaShop#11402]
In order to help merchants have access to premium modules, we need to add "addons redirection block" 
it looks like this : 
![image](https://user-images.githubusercontent.com/40759259/48549156-43502400-e8cf-11e8-9586-4724e91f7e3d.png)

it should appear at the bottom of the following modules :

- [x] #11277 - Wishlist module
- [x] #11210 - Watermark module
- [x] #11263 - Reassurance module
- [x] #11518 - Customer review module
(more modules are coming soon on the list..) 

Expected behaviour for all blocks :
Every block has 
- the same left icone 
- a category 
- a description 
- and button with a link to the addons category 
![image2](https://user-images.githubusercontent.com/40759259/48549662-af7f5780-e8d0-11e8-870a-337b902b801a.png)

document with categories, description and URLs per module is available here : https://docs.google.com/document/d/1pT6jXrx4g5fXCNN3RvsOH4toG7c4wCatprYVNqnyqic/edit

**Comment by colinegin** [comment]
To be discussed with the team

**Comment by colinegin** [comment]
This is the PR integrating the Addons block : https://github.com/PrestaShop/productcomments/pull/33

**Comment by colinegin** [comment]
ping @lolath-presta do you confirm it is expected to integrate this block in Wishlist ?
