### ISSUE TITLE
A wrong button is displayed in Payment methods - COD - 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11420]
**Describe the bug**
After installing the COD module provided by PrestaShop, in the BO => Payment => Payment Methods page, the COD is displayed with the button "Configure" which is wrong (The COD module doesn't have a configure page), when we click on this button, an exception displayed.

**To Reproduce**
1. Install the COD module provided by PrestaShop
2. Go to BO => Payment => Payment Methods 
3. The COD module is displayed with an incorrect button "Configure", it should be a "Disable" button
4. Click on the Configure button
5. See error

1.7.4.4 => OK

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/48626739-fa719b80-e9b2-11e8-82e6-c2c4c2dc0d90.png)

**Additionnal information**
PrestaShop version: 1.7.5.0beta1
PHP version: 7.2

**Comment by Quetzacoalt91** [comment]
Fixed by #11421
