### ISSUE TITLE
Discount Total doesn't work

### ISSUE THREAD

**Issue by johstrom** [PrestaShop/PrestaShop#11425]
**Describe the bug**
Though I set round up  total in settings, Prestashop doesn't round up the total in cart after applied discount. See screen captures below.

If I set zero decimals, it is shown correct, but only in "visible data" - when going to the checkout the total is still with decimals.  

**To Reproduce**
1. Store/Settings and choose to round total.
2. Set up a discount which result in a decimal.
3. Put a product in the cart and apply the discount.
4. See error in the total of the cart.

**Screenshots**
Setting: https://hstrom.mangoapps.com/sf/MTIzMTkyXzYwMjg2MzQ
Frontend: https://hstrom.mangoapps.com/sf/MTIzMTk0XzYwMjg2MzY

**Additionnal information**
PrestaShop version: 1.7.4.4.
PHP version: 7.1

**Comment by Rolige** [comment]
Hi @johstrom,

Before I had to make similar adjustments like the one you need, but I think that for some reason at the moment they are not possible from the configuration of the back office, bbut you can achieved by changing a language file, [here](https://stackoverflow.com/questions/52145202/prestashop-unit-price-decimal-configuration/52150781#52150781) I leave the solution we have done.

Don't forgot to clear cache after any change.

Regards!

**Comment by johstrom** [comment]
Hi @Rolige ,
Yeah, I have noticed this "fix" earlier - but it does only fix the visual appearance, not the underlying numbers itself, it seems. Though I in cart have zero decimals when altering the language file, the checkout still counts on the underlying numbers that ain't rounded. 

This seems to be a bug in Prestashop. I can alter the visual aspect, but I can't alter the real numbers... Then it is completely useless as a round function. 

The accurate process here is to be able to set a round up/down for the total, which is an actual round, which is transferred to the checkout.

**Comment by khouloudbelguith** [comment]
Hi @johstrom,

Thanks for your report.
 The removal of decimals from the currency doesn't work in the PS1.7.
We have an issue in our bug roadmap: https://github.com/PrestaShop/PrestaShop/issues/10017
Also, we have a different rounding problem, it is an issue should be specified & fixed by our developers, you can follow this issue: #9779
Thanks to check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @johstrom,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
