### ISSUE TITLE
Upload child theme failed 1.7.4.3

### ISSUE THREAD

**Issue by vlskrbek** [PrestaShop/PrestaShop#11428]
**Describe the bug**
In Prestashop 1.7.4.3 there is a function to download child theme, customize it and them upload it. But there as an failed upload even I try the theme without changes. See the pictures.

**To Reproduce**
Steps to reproduce the failed upload of child theme:
1. Go to Design -> Theme & Logo -> Advanced Customization
2. Click on Download Theme - there will be downloaded for example file "child_classic.zip"
3. Click on the same page Upload child theme
4. Click on "select file" and choose the "child_classic.zip" and click "Open"
5. Then there is an error "ChildThemeFailed4.png"
6. When I click on "What happened?" or "Try again" then there is nothing happen.

**Screenshots**
![childthemefailed1](https://user-images.githubusercontent.com/44057715/48675491-cd132200-eb59-11e8-892a-c787160fcf30.png)
![childthemefailed2](https://user-images.githubusercontent.com/44057715/48675492-cd132200-eb59-11e8-94e5-9d1c8667f385.png)
![childthemefailed3](https://user-images.githubusercontent.com/44057715/48675493-cd132200-eb59-11e8-9f00-73587335dd6c.png)
![childthemefailed4](https://user-images.githubusercontent.com/44057715/48675494-cd132200-eb59-11e8-8bbe-28e034b02d20.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.37

I have tried it also on version Prestashop 1.7.3.0  and also on two diffrent computers.
Is this happen also in your environment?
When I upload theme directly to folder and then choose in prestashop administrator then it works.

Thanks very much for help
Best Regards
Vladimír Skrbek

**Comment by khouloudbelguith** [comment]
Hi @vlskrbek,

Could you please follow these steps:
1. Go to Design -> Theme & Logo -> Advanced Customization
2. Click on Download Theme - there will be downloaded for example file "child_classic.zip"
3. Go to your Downloads folder
4. Unzip the file "child_classic.zip"
5. Rename the unzipped file to child_classic to child
6. Try to zip this folder child to child.zip
7. Go to Design -> Theme & Logo -> Advanced Customization again 
8. Click on "select file" and choose the "child.zip" and click "Open"

Thanks to check & feedback.

**Comment by vlskrbek** [comment]
Hi,

thank but unfortunately I have got the same result.

My question. If you try it it works or not on your environment?
Best Regards

**Comment by khouloudbelguith** [comment]
Hi @vlskrbek,

When I follow with the steps that I described in my last comment, it is OK.
I attached a video record.
https://drive.google.com/file/d/19zK2SOWaYq-rWueQNbUpEzaH2Slsco6L/view => OK
But, If I try to upload child theme without renaming it, I have issues.
https://drive.google.com/file/d/1Kc9n7tqz2ASrIXrNMxArj6Vgph6JoNMF/view => NOK
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment]
I can reproduce the issue on 1.7.4.3 without renaming
I can't reproduce the issue on 1.7.5.0, it works even without renaming

![capture d ecran_647](https://user-images.githubusercontent.com/13449658/48837709-5870fb00-ed86-11e8-9e8b-858ea50c33a5.png)

So, I guess it's fixed

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue on the last version with the provided information.

Best regards.

**Comment by johstrom** [comment]
Hi, I am having the exact same issue. I have tested to download the child theme, renamed it and uploaded it again - with the same error as shown above. I have Prestashop 1.7.5.1.

Can it be some kind of folder permission issue?

With kind regards,
 - Johan.

**Comment by khouloudbelguith** [comment]
Hi @johstrom,

This issue is currently closed, can you open a new one with more information about your problem.
Thanks!

**Comment by rmln** [comment]
I'd like to reopen this issue. Prestashop 1.7.6.0. The same steps as from the intro post.

**Comment by khouloudbelguith** [comment]
Hi @rmln,

In fact, this issue occurs because the theme folder is in the zip file as reported here: #15004
If you try to upload a zip file with the theme folder => OK
child_classic.zip
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15004
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15004
