### ISSUE TITLE
Apache mod_pagespeed has issues with webp image rewrite

### ISSUE THREAD

**Issue by mortenhartvig** [PrestaShop/PrestaShop#11423]
I have a recent apache webserver with mod_pagespeed enabled. 
When i have filters enabled, that rewrites images to the webp format, there are some places, where images breaks (403 - no access granted to the image file), among other weird behavior.

I have no idea if this is a general issue with mod_pagespeed, or maybe i am missing some important files (due to me having everything versioned by git, pushing up to production, and the auto upgrade module typically goes downstream the other way, as it does not seem to like merchants having staging/test sites........ - another great discussion, or maybe i just missed how to do database migrations manually.....). 

-----------
The pagespeed module holds the actual webp files (and other things) in a temp folder outside the document root. I think, that the .htaccess rules somehow gets poorly interpreted by mod_pagespeed, because the files doesn't live inside /img/, and therefore wont match the rules for that folder and subfolders? (not sure)

Even if i add "webp" to the list of filetypes that are allowed, it dosn't work.

------------

In my case, i solved it by whitelisting/granting everything (dangerous by itself), then blocking everything -that aren't in a specific whitelist (block all inside a "not theese" selector).

Example given/attached.

** Please note, that i am using "Require all granted/denied in my updated file, which may not be available for older Apache versions **

In that case, you have to stick with the old deny/allow directive. (Haven't tested that one)

**To Reproduce**
Try running a site with mod_pagespeed enabled.
The manufacturer images breaks in the the /img/m/*.webp path. (Please note the files doesn't exactly exist there. They live outside in a temp folder, handled by mod_pagespeed, which may cause the  
             interpretation error from the .htaccess file. 

-------------
In my case, i had apache (latest stable), mod_pagespeed (latest stable), nginx as reverse proxy and SSL termination (latest stable), all running on a single docker host machine (ubuntu latest stable).

I kept the mod_pagespeed enabled filters to a miminum (only rewrite_images to webp for testing/confirmation)

[htaccess-example.txt](https://github.com/PrestaShop/PrestaShop/files/2591270/htaccess-example.txt)

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

The mod_pagespeed is enabled, `X-Mod-Pagespeed: 1.13.35.2-0`.
![image](https://user-images.githubusercontent.com/16067358/48701157-26c52c00-ebee-11e8-9464-09e89716ee0d.png)
When I try to upload a webp image, I have a red alert
I attached a video record 
https://drive.google.com/file/d/1VEN9BGaroXe0cY0pKrIwejnltSPlNo7A/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

Any news about your issue?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
