### ISSUE TITLE
Add zip-backup of files.

### ISSUE THREAD

**Issue by EV-soft** [PrestaShop/PrestaShop#11434]
Enhancement: Add zip-backup of files, in release 1.7.x
There is a database backup function, but none for file backup.
It would be nice if there was an option to backup certain folder content,
eg. current theme, or the complete installation.
I have a php file (SnapFiles.php) that does this, which may be beneficial to others. 
Best if the feature could be built into PrestaShop.

[SnapFiles.zip](https://github.com/PrestaShop/PrestaShop/files/2595759/SnapFiles.zip)

**Comment by khouloudbelguith** [comment]
Hi @EV-soft,

Thanks for your suggestion.
About the theme, in your BO => Design => Theme & Logo, you can export your current theme.
![image](https://user-images.githubusercontent.com/16067358/48716351-779d4a80-ec17-11e8-8a90-fe0710b753bc.png)
Thanks to check & feedback.

**Comment by EV-soft** [comment]
Yes - Export works to create a zip file, but it can only be used with ftp connection, and it's hard to find!

**Comment by khouloudbelguith** [comment]
@EV-soft, ok thanks for this clarifications.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think about his suggestions.
Thanks!

**Comment by MatShir** [comment]
It’s a feature to consider but on the marketplace or at your host you can find really efficient backup modules which you can automate the task.
Also don’t hesitate to make a pull request (https://github.com/PrestaShop/PrestaShop/tree/develop) if you have a code suggestion.

**Comment by EV-soft** [comment]
My host only offers complete backup of the hotel, not just the online store, or subfolders below.
I can not find free backup modules in the marketplace.

I suggest that my script be placed in the folders:
prestashop/ - "File-BACKUP: the entire installation"
prestashop/content - "File-BACKUP: uploaded user files"
<other content folders?>/ - "File-BACKUP: other user files"
prestashop/themes/classic-xx/ - "File-BACKUP: current theme"

Additionally, link buttons, which start scripts, add on the relevant pages, or the same place as DB backup.

**Comment by MatShir** [comment]
Many solutions are available more efficient than the solution we could bring like backup files button as I said. Also, it's not our priority for now. I shared the idea at Prestashop Feedbacks (http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/36193876-enable-a-backup-button-files-images-themes) to let the community help us to prioritizes all ideas from the community.

But I really invite you to do a pull request with the button features and be part of the contributors' community.

**Comment by mickaelandrieu** [comment]
Hello,

this is indeed useful *but* I don't think we should do it but let the community provide a premium module for that.

> Why?

Because we don't have this need and so on we are not the best to create and maintain this feature when an agency could sell and maintain its module. We need to search a little bit but there is probably already a module for that: https://addons.prestashop.com/fr/recherche?search_query=export

Mickaël

**Comment by marionf** [comment]
Hello @EV-soft 

We will not integrate natively this feature as there are several modules on our Marketplace allowing to do that.
Furthermore, you can also ask to your hosting provider if you want to backup your files regularly.

Regards
