### ISSUE TITLE
By default, select the payment method if only one available

### ISSUE THREAD

**Issue by rbuelund** [PrestaShop/PrestaShop#11435]
**Note: improvement description edited by Louise B. on October 14th**

**Is your feature request related to a problem?**

As you see in the attached image, the payment method is not elected as default and the customer has to make two ticks to continue - annoying!

![image](https://user-images.githubusercontent.com/1399437/48719790-9521e280-ec1e-11e8-9966-7d480131e4b3.png)

**Describe the solution you'd like:**

It would be really nice if, when a shop has only one payment method activated, this payment method could be selected by default at checkout.

**Comment by khouloudbelguith** [comment]
Hi @rbuelund,

Thanks for your report.
@marionf, what do you think?
It could be an improvement just by adding a Default Payment method, so when there is one payment method, it will be always selected.
Like the carriers, what do you think?
Thanks!

**Comment by rbuelund** [comment]
Yes exactly - but would each payment method then have to be modified to achieve this ? Bambora is a  payment module I have installed.

**Comment by khouloudbelguith** [comment]
@rbuelund, no I don't think that each payment method has to be modified to achieve this, it is an improvement on the core of PrestaShop.
Thanks!

**Comment by rbuelund** [comment]
Is it in any way possible to do this as a hack, so that I can change it manually now ?

**Comment by khouloudbelguith** [comment]
@rbuelund, this improvement should be specified by our developers before.
Thanks!

**Comment by BilalDr** [comment]
Hi @rbuelund 
Thanks for this idea ! 
If we have one payment method it will be automatically selected. 
We will work on it.

**Comment by ghost** [comment]
This little piece of code works like a charm

`jQuery(window).load(function(){
	$('#payment-option-2').prop('checked', true);
});`

Set #payment-option-2 as checked by default even its not first in position.

![id](https://user-images.githubusercontent.com/8243273/48947614-fb19ad00-ef31-11e8-939d-a9a73a27fe4d.jpg)

In this example #payment-option-5 was checked by default (paysafecard)

![id3](https://user-images.githubusercontent.com/8243273/48947717-55b30900-ef32-11e8-82aa-0ff7bb621342.jpg)


So @rbuelund use this

`jQuery(window).load(function(){ $('#payment-option-1').prop('checked', true); });` in Your template assets/js/custom.js file :)

**Comment by rbuelund** [comment]
Perfect solution! Thanks :-)

**Comment by marionf** [comment]
@PrestaShark 

Thanks for diving into this!

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by rbuelund** [comment]
But this solution cannot be added to the code as it has to be set manual to the correct payment method ??

**Comment by TarifaFisch** [comment]
Hi,
I tried out this JS snippet in the document.ready function:
$('#payment-option-1').click();
This alwas shows the 1. payment method selected and the corresponding option box too.
Should be perfect to set the preselcted payment method in the core configs?
Best regards
Thomas - TarifaFisch

**Comment by IlPizza79** [comment]
+1, I think this "default method selection" should have been in PS core since long time ago :-)

**Comment by futurowebpl** [comment]
@PrestaShark but this walkthrough does not display an additional description of the payment method, it is exactly the same if you added {if $ option.id == 'payment-option-1'} checked {/ if} in payment.tpl - this is not the right solution.

this is a bug in Prestashop with $selected_payment_option - when will it finally be solved @khouloudbelguith?

**Comment by patrickmyh** [comment]
@futurowebpl if you fire a click event on the input field it'll work, that's what I ended up doing.

**Comment by kpodemski** [comment]
hey @LouiseBonnard are you planning  to work on this or I can do it?

**Comment by LouiseBonnard** [comment]
Hi @kpodemski! Please go ahead if you want to work on it. ;-)

Here is the related functional specification, feel free to review it: https://github.com/PrestaShop/prestashop-specs/pull/156

**Comment by PrestaShark** [comment]
It can be successfully tweaked by jquery
```
jQuery(window).load(function(){
	$('#payment-option-1').prop('checked', true);
});
```

**Comment by NeOMakinG** [comment]
@kpodemski I did it, feel free to review it, not sure counting the array is the best solution thought but it looks fine to me
