### ISSUE TITLE
png to jpg Module Block Reassurance 3.0.1

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11430]
Hello,

When I upload a custom icone (.png) with a transparent background in BO, the image is display as a .jpg in FO.

**To Reproduce**
1. Go to Setting of the module v3.0.1
2. Upload a .png
3. Go to the FO
4. see a .jpg without transparent bg

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by Rolige** [comment]
Hi @BenTen,

You can keep the transparency of a `.png` image by specifying such a configuration in:  
**BO > Design > Image Settings > Images Generation Options > Image format**

![image](https://user-images.githubusercontent.com/2866694/48684072-b2e73d00-eb75-11e8-8df3-4cea7b4c3b8d.png)


Regards!
