### ISSUE TITLE
Offer module dont work

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#11438]
The offer module dont work in my store, i upload the products whit the "in offer" in 1 and the special offert module and offer pague dont work, and i need for black friday D:

![image](https://user-images.githubusercontent.com/9163980/48727793-82fe6f00-ec33-11e8-832d-6acf13d1b4fc.png)
![oferta](https://user-images.githubusercontent.com/9163980/48727810-8abe1380-ec33-11e8-9feb-659169dbef74.PNG)

**Comment by khouloudbelguith** [comment]
HI @LinkOfLight,

Thanks for your report.
What is the exact name of the offer module? is it provided by PrestaShop?
Thanks!

**Comment by LinkOfLight** [comment]
yes, is name in spanish is Bloque de promociones especiales , sorry for the bad english

**Comment by khouloudbelguith** [comment]
HI @LinkOfLight,

The `Specials block`  Provides information on special offers in a specific block, but in your second image, I see you just enabled the "Display the "On sale!" flag on the product page, and on product listings." option in the product page, but there are no specific prices on this product.
https://drive.google.com/file/d/1oGukLi_fqXHDG_gIwhI9nZECF7y3Yuzr/view
I attached a video record.
Thanks to check & feedback.

**Comment by LinkOfLight** [comment]
yeah but, if my provider dont make my the csv whit the discount and make the prices directly we need mark the on sale! and we need the product see in the on sale module, i think is a basic feacture,

thanks

**Comment by khouloudbelguith** [comment]
@LinkOfLight, thanks for your feedback.
When we check the option `Display the "On sale!"`, a box shows that the product is on sale, both on the product page and in the text on the product listing. An "On sale" icon will appear under the product.
But this product is not displayed in the list of special offers in a specific block, because there are no discounts on this product.
@marionf, it could be an improvement for this module?
Thanks!

**Comment by marionf** [comment]
It's not legal to display a product as on sale without any discount 
It's an obligation to display the original price crossed and the new one.
So, a product can't be displayed in specific block if it's not on sale (have not a specific price or catalog price rule) 
For this reason, we can't add in special block products that are display "On sale" without discount
