### ISSUE TITLE
Discounts based on quantity show incorrect product price

### ISSUE THREAD

**Issue by tanzo** [PrestaShop/PrestaShop#11449]
**Describe the bug**
When we set one or more specific price with quantity major than 1 in front-office the product price goes to 0(zero)

**To Reproduce**
1. Install PrestaShop
2. Create a new product (without combination)
3. Set a price, save
4. Create new specific price with from quantity major than 1
5. Go in frontoffice and change the quantity wanted

**Screenshots**
![ps-discount-bug](https://user-images.githubusercontent.com/16319438/48782139-c9100d00-ecdd-11e8-8bd3-c45b50a99766.gif)

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 7.0.20

**Comment by khouloudbelguith** [comment]
Hi @tanzo,

Thanks for your report.
Here's the PR: #8099 to solve the issue.
As there are too many changes in the theme, we can't merge this to prevent breaking other themes.
Thanks!

**Comment by tanzo** [comment]
As you wish... But I think that is a serious and annoying bug, I found this pull request: https://github.com/PrestaShop/PrestaShop/pull/8538
That works on a fresh installation and on the default-bootstrap template (without changing nothing in the template), the fix works with and without taxes displaying. We have to improve this little fix, it works only with discount in percentage (or fixed) but with the same base price, when we change the base price it displays the price with taxes (no good). 
Here you can see the fix applied:
http://ps16123.tanzows.it/en/home/8-test-prodotto.html
