### ISSUE TITLE
New module not in backend list

### ISSUE THREAD

**Issue by titamrtn** [PrestaShop/PrestaShop#11445]
**Describe the bug**
I create a new module following the tutorial [here](https://devdocs.prestashop.com/1.7/modules/creation/) . 
I just change name. And when i go to backend i don't see module in list
this is : /modules/openflex/openflex.php
```php
<?php
if (!defined('_PS_VERSION_')) {
    exit;
}

class Openflex extends Module
{
    public function __construct()
    {
        $this->name = 'openflex';
        $this->tab = 'billing_invoicing';
        $this->version = '1.0';
        $this->author = 'Openflex SaRL';
        $this->need_instance = 1;
        $this->ps_versions_compliancy = [
            'min' => '1.6',
            'max' => _PS_VERSION_,
        ];
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Openflex Sync');
        $this->description = $this->l('Synchronisation openflex et prestashop');

        $this->confirmUninstall = $this->l('Are you sure you want to uninstall?');

        if (!Configuration::get('MYMODULE_NAME')) {
            $this->warning = $this->l('No name provided');
        }

    }

    public function install()
    {
        if (!parent::install() || !Configuration::updateValue('MYMODULE_NAME', 'openflex')
        ) {
            return false;
        }

        return true;
    }

    public function uninstall()
    {
        if (!parent::uninstall() ||
            !Configuration::deleteByName('MYMODULE_NAME')
        ) {
            return false;
        }

        return true;
    }
}

```

**To Reproduce**
Follow this [tutorial](https://devdocs.prestashop.com/1.7/modules/creation/)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by Quetzacoalt91** [comment]
Hi @titamrtn,

I just tested your code and the module appears properly on the module catalog.

![capture du 2018-11-20 16-36-51](https://user-images.githubusercontent.com/6768917/48788431-b9df8e00-ece2-11e8-92f5-463fead8d2c3.png)

Note the modules ready to be installed are visible on the module catalog, while the installed modules are on the module manager.

Regards

**Comment by titamrtn** [comment]
Hi @Quetzacoalt91 ,
I use PS 1.7.4.4

In modules catalog when i search it redirect me to [addons.prestashop.com](http://addons.prestashop.com)
![screenshot_2018-11-21 catalogue de modules bookdepo](https://user-images.githubusercontent.com/5078563/48820927-1c2ea200-ed68-11e8-9eec-220eb97da19f.png)

And my module isn't in modules and services
![screenshot_2018-11-21 gerer les modules installes bookdepo](https://user-images.githubusercontent.com/5078563/48820960-44b69c00-ed68-11e8-8c55-c78ae36fd820.png)

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

I tried also with your code & I manage to install the module successfully me too.
I attached a video record.
https://drive.google.com/file/d/10q7u53LSkxCcZfOWQ4PPhXrAgNVJfvnL/view
In BO => Modules => Modules & Services =>  Selection Tab, search for your module.
Thanks!

**Comment by Quetzacoalt91** [comment]
Yeah, sorry. The module pages have been updated on 1.7.5.0.

You will find your module in "Modules & Services > Selection"

**Comment by titamrtn** [comment]
Thanks!
