### ISSUE TITLE
product combination not created in shop B in multistore environment

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#11452]
**Describe the bug**
I have a multistore environment shop where shop A has different prices from shop B. Both share the same stock quantity and differ in customers.

When a product is created as "All shops" with combinations, combinations are seen as All Shops and as shop A but it is hidden nor seems to be created in the backoffice of shop B. However if a SQL is executed, it is registered in both shops.

**To Reproduce**
1. Go to product with combination within all shops environment
2. Click on 'Combinations' and create one combination with attribute "Coloración de tintes" and select 7.60 value and generate combination. Afterwards, change to "CentroBell Cosmética Profesional" and go again to combinations tab.
3. Scroll down to search the recently added combination.
4. See error where the combination is not there.

**Screenshots**

[ErrorCombinations720.zip](https://github.com/PrestaShop/PrestaShop/files/2601331/ErrorCombinations720.zip)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
Hi @demperador,

Thanks for your report.
Have you the same issue with this issue https://github.com/PrestaShop/PrestaShop/issues/9664
Thanks!

**Comment by demperador** [comment]
Hello. We are still dragging with this issue and for us is a vital feature. Is the fix for this issue in a nearby roadmap for prestashop?  Sorry for insisting so much but it is necessary for our shop that is in production.

Thanks.

**Comment by khouloudbelguith** [comment]
@demperador, in your configuration Multistore, did you enabled "share quantities" in a group?
Thanks!

**Comment by demperador** [comment]
Hello @khouloudbelguith, yes. It has been configured to share quantities and 
![captura de pantalla 2018-12-14 a las 11 02 56](https://user-images.githubusercontent.com/31283004/49999914-ed36d500-ff8f-11e8-9210-c3cf99323cde.png)

**Comment by khouloudbelguith** [comment]
@demperador, we have a lot of issues when multistore enabled, 
we are aware of your issue, here's a similar problem to yours: #9940
It is added to our bug roadmap, we have also this issue: #9664
We have another issue when share quantities is enabled, #10274
All these issues are not fixed yet.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @demperador,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by demperador** [comment]
Hi @khouloudbelguith I have not posted anything else because of the last reply in this thread. For our company is necessary to have this bug fixed. We have noticed though that if all combinations are deleted and generated again. Then there is no problem but it is a hassle to have to link pictures to every combination, even more when there are products that can have more than 100 combinations (just imagine trying to attach to each nail polish color)...
