### ISSUE TITLE
in the combination page only few attributes are shown

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11459]
Hi
in this case a site has 29 attributes but in the product page it is possible to manage only 7 of them and the others?

**Screenshots**
![2](https://user-images.githubusercontent.com/653230/48834492-3ecbb580-ed7e-11e8-9833-90b7be160a01.png)
![1](https://user-images.githubusercontent.com/653230/48834494-412e0f80-ed7e-11e8-990c-0dfb51a9fe0a.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

thanks
bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
Have you the same issue with this issue: https://github.com/PrestaShop/PrestaShop/issues/9627#issuecomment-415051695?
Did you delete any deleted language?
Thanks to check & feedback.

**Comment by Maofree** [comment]
there are 3 languages
italian, english and french
in the past none has been removed

**Comment by Maofree** [comment]
I can give you the access to this site if you need it

**Comment by khouloudbelguith** [comment]
@maofree, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
I think this issue is related to #11458
Thanks!

**Comment by Maofree** [comment]
debug mode no report
php log there are only few things about the front-office around images not found or some redirect

I pass you the access to the back-office

**Comment by Maofree** [comment]
did you get the email with the access to the site?

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Yes, I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @maofree,

It is the behavior that I expected.
![image](https://user-images.githubusercontent.com/16067358/48847229-52d4de80-eda1-11e8-84c1-b5078d398dec.png)
You have deleted the language of id_language = 1.
This is the whole issue.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10924 to solve the issue.
I close the issue, feel free topen a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9627

**Comment by Maofree** [comment]
hi
thanks
yes now it works with that solution

`        $doctrine = $this->getDoctrine()->getManager();
        $language = empty($languages[0]) ? ['id_lang' => 1, 'id_shop' => 1] : $languages[0];
        $attributeGroups = $doctrine->getRepository('PrestaShopBundle:Attribute')->findByLangAndShop((int) $language['id_lang'], (int) $language['id_shop']);`

is it possible to add it on the 1.7.5 instead to wait the 1.7.6 ?

**Comment by khouloudbelguith** [comment]
@maofree, sorry now we can't add to the milestone 1.7.5.0.

**Comment by Maofree** [comment]
but it can solve problems in many sites

**Comment by khouloudbelguith** [comment]
@maofree, your point makes sense, unfortunately, we only accept security fixes or regression from 1.7.5.0 on this branch to be focused on the 1.7.5.0 version, as described here: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#target-branch
The fix will be available in the next minor release, with a beta coming shortly. It will be in consequence available for everybody ready to upgrade.
Thanks!

**Comment by Maofree** [comment]
can you do an example of version when it can be fixed?
1.7.5.1 or 1.7.6.0 ?

**Comment by khouloudbelguith** [comment]
@maofree, 1.7.6.0.
Thanks!
