### ISSUE TITLE
Not sending e-mails. mail() function not working

### ISSUE THREAD

**Issue by pg4al** [PrestaShop/PrestaShop#11453]
PrestaShop: version 1.7.4.4
Actual theme: warehouse
Información del servidor Linux #1 SMP Thu Aug 23 19:33:51 MSK 2018 x86_64
Versión del software del servidor: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.6.37
Versión PHP: 5.6.37
Límite de memoria: 512M
Tiempo máx. de ejecución: 300
Tamaño máx. para la subida de archivos: 64M
Módulo PageSpeed para Apache instalado (mod_instaweb)
Método de correo electrónico: Estás utilizando la función PHP mail().
 
After upgrading to 1.7.4.4 users stopped getting messages from the website, test messages are not received either.

**Comment by khouloudbelguith** [comment]
Hi @pg4al,

After upgrade from 1.7.3.4 to 1.7.4.4 using the 1-click upgrade v4.4.1, I checked the "Send test Email", the new customer Email and all are working good.
To configure PrestaShop to send emails to your customers, we strongly advise you that you consult your web host to determine which settings to use for this feature. The options are:

- Never send e-mails. Keep this setting for testing purpose. Once your shop is public, you should never use this setting.
- Use PHP's mail() function. This option is recommended by default. In the event that this does not work, then use the SMPT option below.
- Set my own SMTP parameters. In this case, a new section appears, with more fields. The information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check with your host & feedback.

**Comment by khouloudbelguith** [comment]
Hi @pg4al,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
