### ISSUE TITLE
Unnecessary spaces on header of the checkout page

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11454]
**Describe the bug**
We need to improve design of checkout page header in classic theme by removing unnecessary spaces

**To Reproduce**
1. Go to 'Checkout page on FO'

**Screenshots**
![header-checkoutpage-prestashop](https://user-images.githubusercontent.com/40850057/48822727-0a5af800-ed84-11e8-961f-95b4f42cf171.png)

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Thanks for your report & for your PR.
Thanks!
