### ISSUE TITLE
Exception on theme & logo page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11461]
**Describe the bug**
Exception on theme & logo page

**To Reproduce**
1. Go to Design > Theme & logo
2. Scroll down
3. See error

**Screenshots**
![capture d ecran_648](https://user-images.githubusercontent.com/13449658/48844375-f8844f80-ed99-11e8-8e63-8adee4514a43.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by marionf** [comment]
Maybe to solve in MBO
@alexisvallee can you check that ?
If it's the case I will move the issue in MBO repository

**Comment by jolelievre** [comment]
I'm not sure it needs to be fixed in MBO, but it's probably linked.
I tried in an install from the branch, with no mbo, and there is no error when you scroll
Is this a feature from mbo? to add the theme catalog under the settings?

**Comment by marionf** [comment]
@jolelievre Yes, it's a feature of MBO
This is why you don't see the error if MBO isn't installed

**Comment by jolelievre** [comment]
Ok I'm gonna fix this bug, no need to move it to the other repo for now

**Comment by jolelievre** [comment]
hello,
this is fixed by https://github.com/PrestaShop/ps_mbo/pull/67 in ps_mbo
