### ISSUE TITLE
UndefinedMethodException when confirmation of order

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11468]
Hello,

When I try to confirm an order (this one by check), I have an Exception message error.
https://tof.cx/image/kDXUy

Even if there is the error, the order is create in BO.

But when I try to enter in the detail of the order in the BO, I have an other issue
https://tof.cx/image/kDqoC

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
Did you use any module something like CODwFreePlusValidation ?
Thanks to check & feedback.

**Comment by BenTen** [comment]
I use this one to be honest: https://www.prestashop.com/forums/topic/912961-free-module-cash-on-delivery-with-fee-plus-ps-16-17/

I try to uninstall it because I thought it was this plugin, but the problem is the same.

**Comment by khouloudbelguith** [comment]
@BenTen, this module is the whole problem, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need to check also if you have any overrides due to this module.
Thanks to check and feedback.

**Comment by BenTen** [comment]
I deleted all cache and check overrides but the issue is display again in BO and FO.

But I can see a message in log "Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart "

**Comment by khouloudbelguith** [comment]
@BenTen, this log is a different issue, you can follow this issue: #9866
The exception is displayed again, is there any errors?

**Comment by BenTen** [comment]
Thank you for the other issue.

About this one, after delete cache into var/cache (prod & dev), the exception is displayed again.
The same error than the first post (BO and FO).

**Comment by khouloudbelguith** [comment]
@BenTen, what is the exact transport & the exact payment method did you use?
Because in your exception, the [module](https://www.prestashop.com/forums/topic/912961-free-module-cash-on-delivery-with-fee-plus-ps-16-17/) is the problem again.
![image](https://user-images.githubusercontent.com/16067358/48932599-17e7bd80-eefd-11e8-95d2-e2cf79ca2cfa.png)

Thanks!

**Comment by BenTen** [comment]
Since I remove the plugin, I can't use this method.

When I use "payments by check" the problem is the same than the first post.
Here the screenshot of the error when I pay by check: https://tof.cx/image/koSfU

**Comment by khouloudbelguith** [comment]
@BenTen, what is the exact version of the ps_checkpayment module did you use?
Is it v2.0.4.
If yes, could you please try to uninstall it, remove the ps_checkpayment folder in the Project_Folder/modules/ & try to install it again.
Thanks!

**Comment by BenTen** [comment]
It's 2.0.4 so I uninstalled and removed the folder.
I installed an tried again but, same error happen https://tof.cx/image/kokFw

**Comment by khouloudbelguith** [comment]
@BenTen, what is the exact carrier did you use?
Did you use any other custom module for the transport for example or any other module to generate invoices?
Thanks!

**Comment by BenTen** [comment]
I created different carrier in the native part of Prestashop.
I don't use 3rd part module to generate invoices nor to set carriers.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

I did not manage to reproduce the issue in my case.
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
The issue seems comes from the module, I can't reproduce it on a fresh install of PrestaShop without added modules.

**Comment by BenTen** [comment]
There was an OrderInvoice.php in override. I didn't saw it before.
```
class OrderInvoiceCore extends ObjectModel{
	public static function getCurrentFormattedShopAddress($id_shop = null){
		$address = new Address();
		$address->company = Configuration::get('PS_SHOP_NAME', null, null, $id_shop);
		$address->address1 = Configuration::get('PS_SHOP_ADDR1', null, null, $id_shop);
		$address->address2 = Configuration::get('PS_SHOP_ADDR2', null, null, $id_shop);
		$address->postcode = Configuration::get('PS_SHOP_CODE', null, null, $id_shop);
		$address->city = Configuration::get('PS_SHOP_CITY', null, null, $id_shop);
		$address->phone = Configuration::get('PS_SHOP_PHONE', null, null, $id_shop);
		$address->id_country = Configuration::get('PS_SHOP_COUNTRY_ID', null, null, $id_shop);
		$address->id_state = Configuration::get('PS_SHOP_STATE_ID', null, null, $id_shop);

		return AddressFormat::generateAddress($address, array(), '<br />', ' ');
	}
}
```
I delete it and everything is fine now.

Sorry for this ticket.
