### ISSUE TITLE
Get product list with tax in webservice

### ISSUE THREAD

**Issue by troelsselch** [PrestaShop/PrestaShop#11460]
**Is your feature request related to a problem? Please describe.**
When retrieving products and combinations from the webservice it is possible to get a list (e.g. `/api/products`) or the individual item (e.g `/api/products/1`). However, those two endpoints work differently regarding taxes.

For the individual products you can specify e.g. `/api/products/1?price[price][use_tax]=1&price[price][country]=3` as [per the documentation](http://doc.prestashop.com/display/PS16/Chapter+10+-+Price+management), but this parameter does not work for the listing. This means that if we want to get all prices with taxes we have two options:

- Retrieve all products, combinations, taxes, tax_rules, tax_rule_groups, and countries and do the calculation ourselves.
- Retrieve all products and combinations and for each of product/combination call the specific endpoint.

*Corrected: The webservice is not throttled as previously stated.* With an average of 7069 products/combinations per site and 22 sites that mean a lot of calls, which will put a big load on our servers and on the shop servers. When we get more customers using our service we will have even more issues keeping up.

**Describe the solution you'd like**
When calling the webservice endpoint `/api/products` it should be possible to add the parameters `use_tax` and `country` (e.g. `price[price][use_tax]=1&price[price][country]=3`) in order to get the price including tax for all products without additional calls.

**Describe alternatives you've considered**
Maybe a solution already exists, but has not been documented?

**Additional context**
We are using the data to create product feeds for Google Ads, which require the prices to be with tax, and in special cases to be without tax.

**Calculations**
- 22 shops
- 155520 products in total, 7069 on average

**Comment by khouloudbelguith** [comment]
Hi @troelsselch,

Could you please try with this link: `http://xxxxxx/api/products/?display=full&price[price][use_tax]=1&price[price][country]=3` & feedback.
Thanks!

**Comment by troelsselch** [comment]
Hi @khouloudbelguith,

It does work. In order to make it work PrestaShop needs to be fully set up with currencies, exchange rates, taxes, and countries. And then you need to specify all of the following:

```
?display=full
&url=products
&price[price][use_tax]=1
&price[price][country]=3
&price[price][currency]=2
&price[price][decimals]=6
```

So we can remove this issue, since it was simply a lack of documentation.

Thank you for your help.
