### ISSUE TITLE
Problem with combination and mouse click on other product

### ISSUE THREAD

**Issue by sportelli94** [PrestaShop/PrestaShop#11476]
HELLO,
I HAVE A PROBLEM WITH PRESTASHOP WHEN A PRODUCT HAVE A COMBINATION AND CHANGE A PARAMETRS THEREFORE I DO NOT PROCEED ANY OTHER OPERATION (ES ADDED TO THE CART) AND I GO TO ANOTHER PRODUCT, IN THE BOARD SHOWING THE PRICE EQUAL TO 0.
THE SCREEN IS A EXAMPLE.

THE SITE IS WWW.TRACKDESIGN.NET PLEASE HAVE A TIP?

php version is a 5.6

**Comment by khouloudbelguith** [comment]
Hi @sportelli94,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sportelli94** [comment]
yes,

the version prestashop is 1.7.3.2 
server is a apache e mysql on debian
version php 5.6 
but in apache2 and in javascript 
it's not what mistakes to give you.
it shows me nothing when I go to their logs.
![immagine](https://user-images.githubusercontent.com/45287071/48940424-d1ec2300-ef17-11e8-8c1f-226de30865b2.png)

**Comment by sportelli94** [comment]
but with a reload on page the price reapparance

**Comment by PrestaShark** [comment]
1) Try to disable SEO Friendly URLS module
2) Try to update PS and Template

**Comment by khouloudbelguith** [comment]
Hi @sportelli94,

Could you please Navigate to the BO => Shop Parameters => Traffic & SEO and provide a screenshot of the SCHEMA OF URLS.
![image](https://user-images.githubusercontent.com/16067358/47072066-8c8c5580-d1f5-11e8-88ec-7a81af16c08e.png)
Thanks!

**Comment by sportelli94** [comment]
ok.
it is
![immagine](https://user-images.githubusercontent.com/45287071/48941173-c0584a80-ef1a-11e8-8830-4b29ed22031e.png)

**Comment by sportelli94** [comment]
because you asked me for these parameters. what should I do? I wait for you

**Comment by khouloudbelguith** [comment]
@sportelli94,

Thanks for your feedback.
Can you change the SCHEMA OF URLS to the default Shema provided by PrestaShop?
Like described in this screenshot:
![image](https://user-images.githubusercontent.com/16067358/47073013-9911ad80-d1f7-11e8-98ce-f1325816b16b.png)
Also, you need to check if you have some overrides added by a custom module could be a problem.
Thanks!

**Comment by sportelli94** [comment]
i have a modify but check ovveride how how can I control the override
![immagine](https://user-images.githubusercontent.com/45287071/48946506-40d47680-ef2e-11e8-99b9-ce8bc2867a23.png)

**Comment by sportelli94** [comment]
because it could be problems of url malfunction with the price variable that is not displayed. what does it has to do with it?

**Comment by sportelli94** [comment]
it's the only problem that
and it would be great to solve it in such a way that we can fix this problem

**Comment by khouloudbelguith** [comment]
@sportelli94, you can delete this override to check if it the issue happens again.

**Comment by sportelli94** [comment]
no. but if disable a ovveride not work the button add to product.
please do you know how to help me?
you can debug you by visiting the site and doing the operations: select a product with conbinations for example itria and make a change of selection of the combinations. successively changed product. poom find 0 euros

**Comment by khouloudbelguith** [comment]
@sportelli94, I attached a video record.
https://drive.google.com/file/d/1ar0sDU4ss9f9IbrZvKPB0a3VfBX5em1U/view
Thanks to check & feedback.

**Comment by sportelli94** [comment]
but after a select a combination change a product visual a bug.
please

**Comment by khouloudbelguith** [comment]
@sportelli94, yes, in your shop I have this issue, but in fresh installation PS 1.7.4.4 I did not manage to reproduce the issue.
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
If the performance page, if you enable the debug mode is there any exception displayed in Front office?
Thanks!

**Comment by sportelli94** [comment]
no exception, unfortunately, is displayed in front of the office. ALSO AS YOU SAID NOTHING TO DO DOES NOT ALLOW TO UNDERSTAND WHAT IS THE PROBLEM. SOME DISABLED VARIABLE? DO I HAVE TO FORCE UP THE PAGE UPDATE? ARE YOU CAN DO?

**Comment by khouloudbelguith** [comment]
@sportelli94, we just need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
About the override which you cannot delete it, from which module is added?
Have you tried to contact the theme author?

**Comment by sportelli94** [comment]
but is problem in this variables. the strange thing that concerns only and only
the viarbile of the price. that is all the variables of the price. why this?

where session variables or cookies are managed because it seems more like a problem.

**Comment by khouloudbelguith** [comment]
@sportelli94, it is the same problem reported [here](https://github.com/PrestaShop/PrestaShop/issues/11029#issuecomment-433204969) & he solved it by deleting some overrides which is not a PrestaShop problem core.
Thanks!

**Comment by sportelli94** [comment]
and how can I solve them? eliminating the overrides, however, almost nothing resolves me. on the contrary, the situation worsens. I tried it on a debug server and it gave me worse results.and how can I solve them? eliminating the overrides, however, almost nothing resolves me. on the contrary, the situation worsens. I tried it on a debug server and it gave me worse results.

I have to solve this problem. thank you.

**Comment by khouloudbelguith** [comment]
Hi @sportelli94,

How did you eliminate the overrides?
Did you disable the "Disable all overrides" option in the BO => Advanced Parameters => Performance page?
![image](https://user-images.githubusercontent.com/16067358/49008788-0b6a9b80-f16f-11e8-8171-20bed9256ed8.png)
Thanks!

**Comment by sportelli94** [comment]
yes, but not resolve this problem on the contrary, it made the situation worse as it blocked the addition of the products

**Comment by khouloudbelguith** [comment]
@sportelli94, to be sure, could you please try to remove all the overrides manually from your project folder.
You can find them in this [folder](https://github.com/PrestaShop/PrestaShop/tree/develop/override)
Thanks to check & feedback.

**Comment by sportelli94** [comment]
provid at delete a folder manually but not work. HAVE A SAME PROBLEM

**Comment by khouloudbelguith** [comment]
@sportelli94, thanks for your feedback.
@marionf, I did not manage to reproduce the issue with PS1.7.4.4 / PS1.7.5.0beta1, what do you think?
Thanks!

**Comment by sportelli94** [comment]
someone to let me know?

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.
