### ISSUE TITLE
Bug on combination

### ISSUE THREAD

**Issue by Lndaw** [PrestaShop/PrestaShop#11474]
BUG DESCRIPTION:
- On the product page(s) of products with different variants available, not all variants are displayed.
- The dropdown menus do not contain all possible items to select from.
- Example page: https://anson.ch/de/ventilatoren/638-13790-schallisolierte-luftungsbox-sbr-ibr-ec-erp-2018#/nenndurchmesser-100/
----------------------------------------
STEPS TO REPRODUCE THE BEHAVIOR:
1. Go to the following product page on the shop website (Frontend):
    https://anson.ch/de/ventilatoren/638-13790-schallisolierte-luftungsbox-sbr-ibr-ec-erp-2018#/nenndurchmesser-100/
2. Click on the dropdown menu "Ausführung".
3. There is only one entry called "IBR".
4. The variant "SBR" is not displayed and can not be selected.
5. Login to the backend of the shop.
6. Go to: Catalog => Article.
7. Search for the article ID 638.
8. Go to the product edit/configuration page.
9. Go to "Varianten".
10. You will see 8 different variants listed.
11. Two variants are with "Ausführung: IBR" and 6 with "Ausführung: SBR".
----------------------------------------
PROBLEM:
- The Variants with "Ausführung: SBR" can not be selected on the example page.
- The dropdown menu for "Nenndurchmesser" does contain all the possible measurements.
- The dropdown menu for "Ausführung" only contains the value "IBR" (and not "SBR").
- The visitor/client therefore can not select the "SBR" products.
----------------------------------------
SCREENSHOTS:
- Shop information: shop_info.jpg
- Dropdown menu with only the "IBR" item: dropdown.jpg
- Different variants in the backend: variants.jpg
----------------------------------------
ADDITIONAL INFORMATION:
- PrestaShop version: 1.7.4.3
- PHP version: 7.1.23
- Template: ps_furniture2_super_store_v2
- Template version: 1.0.1

**Comment by khouloudbelguith** [comment]
Hi @Lndaw,

I followed the link that you provided to me & it is OK in my side.
![image](https://user-images.githubusercontent.com/16067358/48913857-f72a5400-ee79-11e8-8e72-f1035d3617e9.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@Lndaw, I can select all the combinations also.
https://drive.google.com/file/d/156eA5yuAdrXn8crvKNASMoNgH7FqJKp6/view
Thanks!

**Comment by Lndaw** [comment]
Hello,

Ok i am going to close this ticket.

Kind regards,

**Comment by Lndaw** [comment]
Hello ,

Could you please close this ticket.

Kind regards,

**Comment by khouloudbelguith** [comment]
Hi @Lndaw,

I close the issue, feel free to open a new one when needed.
Thanks!
