### ISSUE TITLE
Show price with TAX on backend product list

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#11479]
Please restore to backend product list prices with TAX column....
This is very annoying complication in B2C businesses, and its cant be fixed by override of src/PrestaShopBundle/ folder

**Comment by PrestaShark** [comment]
![tax](https://user-images.githubusercontent.com/8243273/48941577-593b9580-ef1c-11e8-8090-beab8a9bbfb6.jpg)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

In back office > catalog > products list:

- Price without tax is interesting in B2B mode.
- Price with tax is interesting in B2C mode (default mode), therefore it should be the default behavior.

@marionf, what do you think, it could an improvement.
Thanks!

**Comment by marionf** [comment]
In 1.6 there was price without tax and price with tax

![capture d ecran_657](https://user-images.githubusercontent.com/13449658/48946300-89d7fb00-ef2d-11e8-8e91-f044910b55a4.png)


In 1.7 there is only price without tax

![capture d ecran_658](https://user-images.githubusercontent.com/13449658/48946317-94929000-ef2d-11e8-92be-d163a3d4c6f2.png)

**Comment by ghost** [comment]
![finalprice](https://user-images.githubusercontent.com/8243273/48947271-d113bb00-ef30-11e8-9341-49677f7781e1.jpg)

https://github.com/PrestaShop/PrestaShop/pull/11483 sorry. this is my first pull ;)

**Comment by khouloudbelguith** [comment]
@PrestaShark Thanks for the fix!
Also do not be afraid of "messing it up", we'll help you getting it right

**Comment by ghost** [comment]
Need to learn how to merge my file edits in one pull :/

**Comment by marionf** [comment]
@PrestaShark this is a guide to help you: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/
