### ISSUE TITLE
Catalog/Stocks Wrong sort by reference if product attributes

### ISSUE THREAD

**Issue by AyLia85** [PrestaShop/PrestaShop#11472]
If product reference is different by combinations, the sort by refernce in Stock pages is not order by reference. 

On clean install 
change reference for product demo_1 add _B1 for Black S, _B2 for Black M, _W1 for Whithe S ...

Go to Catalag/Stock 
filter on demo_1 
and change sort by reference 

Order is not correct 

![image](https://user-images.githubusercontent.com/45260295/48899482-ff6d9980-ee4f-11e8-9eee-7cdf54090963.png)

PrestaShop version: 1.7.4.4
PHP version: 7.1.16

**Comment by khouloudbelguith** [comment]
Hi @AyLia85,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4.
In the Stocks page, I searched products by reference "demo_1" => OK
When I try to reorder by reference => NOK.
![image](https://user-images.githubusercontent.com/16067358/48900322-5a07f500-ee52-11e8-8498-aee9c4d3ab68.png)
We will see how to fix it.

**Comment by arouiadib** [comment]
This is no longer an issue in 1.7.7.x

**Comment by marionf** [comment]
@khouloudbelguith Could you close the issue if fixed in 1.7.7 ?

**Comment by khouloudbelguith** [comment]
@marionf, it is fixed with 1.7.7.0.
![image](https://user-images.githubusercontent.com/16067358/75546482-e8d9c900-5a28-11ea-9fa6-f846816b2bad.png)

Thanks!
