### ISSUE TITLE
multisites issue cant save prices to product on all shop mode

### ISSUE THREAD

**Issue by hyperians1** [PrestaShop/PrestaShop#11489]
**Describe the bug**
when i try to save product price while setting on All shops mode , price is not saves, but when i save it on single shop its saved ok... but not in all shops..
its major because we cnt make global changes on product except from multishop

moreover , when save the product to another shop and try to change settings it affects all shops..

which means i have to upload same product everytime shop by shop

it happened suddenly , before it was okay..

i have prestashop multisite 1.6.20

**To Reproduce**
1. Go to 'Catalog , Products , Price  in ALL SHOPS mode '
2. Click on 'save in multishop mode'
3. Scroll down to 'top page'
4. See error zero price set

**Screenshots**
attached

**Additionnal information**
PrestaShop version: 1.6.20 multi shop , multi currencies , multi languages
PHP version: 7.2

**Comment by hyperians1** [comment]
#11488

**Comment by PierreRambaud** [comment]
Hi @hyperians1 and thanks for your issue but unfortunately we can't merge your pull request since you're only targeting the 1.6.1.x branch into develop and sadly we can't approve this merge request :)
Make sure your target your fork & branch.
Regards

**Comment by khouloudbelguith** [comment]
Hi @hyperians1,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-8834
It wasn't necessary to create a new one.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/8158 to solve the issue.
So, this one can be closed
Thanks!
