### ISSUE TITLE
Unexistent product added on orders. CRITICAL ISSUE

### ISSUE THREAD

**Issue by Bonobomagno** [PrestaShop/PrestaShop#11480]
**Describe the bug**

Some orders have product that dont exist on the prestashop.
There is no record on the db about this products, but still they appeir on the order list on the backend.
The domain is new, never used as a shop.
Order total is still only the sum of  the real products, but this products have a quantity and a price that probably the customer can see.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

**Comment by Bonobomagno** [comment]
little info, this happend only on some paypal order.
we are using official module

**Comment by khouloudbelguith** [comment]
Hi @Bonobomagno,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Did you use the MailChimp module?
What is the exact version Paypal did you use?
Thanks!

**Comment by Bonobomagno** [comment]
Other guystold me that the shop was not so "new". It was new, but some migration happened before coming to prestashop. So, i dunno how, some previous orders were still on the order table. Withouf fk its easy to have orphan records..
 Now i think that this will not happen again :/

**Comment by khouloudbelguith** [comment]
@Bonobomagno, thanks for your feedback.
