### ISSUE TITLE
The "Add a new" button has no effects in the Monitoring page, just refresh the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11482]
**Describe the bug**
In the BO => Catalog => Monitoring page, the icon Add a new is displayed, but it has no effect, it  just refreshes the page.

**To Reproduce**
1. Go to BO => Catalog => Monitoring page
2. Click on 'ADD NEW' button => the page will be refreshed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/48946649-afb1cf80-ef2e-11e8-9980-cbab9305e12d.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by marionf** [comment]
The add button should be removed

**Comment by matks** [comment]
Fixed in migrated page https://github.com/PrestaShop/PrestaShop/issues/10552
