### ISSUE TITLE
multishop list URL

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#11493]
**Describe the bug**
When configuring a multishop, on the BO store list (top right menu), when you click on the eye to see your shop, every line goes to the first main shop

**To Reproduce**
1-install a fresh 1.7.5 shop
2-enable multistore
3-create a second store
4-go to backoffice and clic on "all shops" menu, clic on any "eye" button : it's the same URL

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

I did not manage to reproduce the issue with PS1.7.5.0beta1.
I attached a video record
https://drive.google.com/file/d/1F7EOrNy9Z73O1_pF770yGeCAhHLgWODh/view
In the BO => Advanced Parameters => Multistore, select a shop & you can edit the Virtual URL for example.
![image](https://user-images.githubusercontent.com/16067358/49011994-5210c380-f178-11e8-8bcc-42789066fe6f.png)
Thanks to check & feedback.

**Comment by elmanu13** [comment]
Hi @khouloudbelguith,

You are correct, that works in your case and I forgot a small detail : my 2 shops have the same subdomain, but not the same URL.
Shop 1 : myshop.mydomain.com
shop 2 : myshop.shop2.mydomain.com

I tried with a 3rd one : shop3.myshop.mydomain.com
and a 4th on : shop4.mydomain.com

None of them work : the link goes to myshop.mydomain.com

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

Thanks for this clarifications.
I manage to reproduce the issue with the branch 1.7.5.x / PS1.7.4.4
https://drive.google.com/file/d/1wL_e6B5pInC-xN3-n3aup5rJmgORKPXv/view
We will see how to fix it.
ping @jolelievre what do you think?
Thanks!
