### ISSUE TITLE
My server ip online

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11499]
Prestashop 1.7.4.4
Linux #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
apache + nginx
php 7.2.12
cloudflare as cdn
My doubt is why my own server ip address is show every time about 100 times on visitor online stats.
Thank you

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Your issue is so difficult to reproduce it, in your case it random.
But, when the issue occurs, is there any error in your log file?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by centoasa** [comment]
It seems now disappear adding my server ip address and 127.0.0.1 into maintenance ip address.
It's not an error so if I enable debug mode I think I can't see nothing.

**Comment by khouloudbelguith** [comment]
@centoasa, so can I close this issue?

**Comment by centoasa** [comment]
@khouloudbelguith Yes, fo now yes.  If you will have updates about this issue, please let us know!

**Comment by khouloudbelguith** [comment]
@centoasa, thanks!
I close the issue, feel free to open a new one when needed.
