### ISSUE TITLE
BO Product tabs width problem in polish

### ISSUE THREAD

**Issue by mklimkiew** [PrestaShop/PrestaShop#11496]
In 'Product edit' section navigation tabs jump to the second line. UL section has fixed width value.
This may be issue in different languages. Tab titles can have diferent lenght in different languages.

Additionaly it causes a wrong display on small screens.

1. Go to 'Catalog / Products'
2. Click on any product
3. Product tab "OPTIONS" jump to the second line
4. See bug

![ps-1-7-5-0-bug](https://user-images.githubusercontent.com/45269666/48977053-06381e80-f093-11e8-9f17-dd5a0bd2a82e.jpg)

PrestaShop version: 1.7.5.0.beta.1
PHP version: 7.2.12
Lang version: PL

**Comment by khouloudbelguith** [comment]
Hi @mklimkiew,

I did not manage to reproduce the issue with PS1.7.5.0beta1.
I attached a video record.
https://drive.google.com/file/d/1BOZ2ozFty0tiKOYPRuzpxmk9ioFkmD-D/view
Thanks to check & feedback.

**Comment by mklimkiew** [comment]
Try this with different product. I notced this bug in some products, some others are OK. 
See attached photos.

If a product has combinations then tab "Quantities" is replaced by "Combinations"
This changes the tab width and makes the last tab to jump to second line.


![ps-1-7-5-0-bug2](https://user-images.githubusercontent.com/45269666/49012744-a3ba4d80-f17a-11e8-9ef9-b424e7bdcdef.jpg)
![ps-1-7-5-0-bug3](https://user-images.githubusercontent.com/45269666/49012746-a452e400-f17a-11e8-8927-8c09dd74fa8f.jpg)

**Comment by khouloudbelguith** [comment]
@mklimkiew, I tried with a product with combinations & it is NOK.
https://drive.google.com/file/d/1bVamAfjPbmWGdMo85HV6GiT5oQEFs6-7/view
@marionf what do you think, is it a normal behavior.
In English, it is ok, only with the Polish language.
Thanks!

**Comment by mklimkiew** [comment]
> In English, it is ok, only with the Polish language.

Other languages can be afected as well. 
@marionf Try to reduce size of the browser so that it displays like on the tablet/smartphone.
You'll see incorrect behavior - the second line with tabs disappears.
