### ISSUE TITLE
classic theme footer block design improvement

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11490]
**Describe the bug**
Contact block has extra spaces in the left side and border compare to other footer columns of classic theme footer. We should remove that extra space for better UX.

**Screenshots**

![footer](https://user-images.githubusercontent.com/40850057/48967722-12789900-f00b-11e8-9541-8bce9ad45199.png)

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Thanks for your report & your fix.
