### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by titamrtn** [PrestaShop/PrestaShop#11504]
**Describe the bug**
When i have long title, for category or page title, the search bar is going down

**To Reproduce**
Add long title to category or page title

**Screenshots**
![screenshot from 2018-11-26 11 01 45](https://user-images.githubusercontent.com/5078563/49000566-0b689c80-f16b-11e8-8ff3-2f88c7176147.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

It a normal behavior, when we can add categories, it will be displayed well.
Also, In the BO => Design => Positions page, in the display top hook, the Main menu has the first position but the search bar module is in the second position.
![image](https://user-images.githubusercontent.com/16067358/49001622-8d51c900-f15d-11e8-9375-890656605121.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
