### ISSUE TITLE
Cart product change

### ISSUE THREAD

**Issue by adipso-jerome** [PrestaShop/PrestaShop#11507]
Hello,

My problem is when I change price of my product while some customer are paying on bank. They pay the wrong price because Prestashop calculate the cart amount in PaymentModule when order is validate.

**To Reproduce**
1. Front : add some product to cart
2. Front : go to cart, follow step and when you should pay, use some bank module who make you leaving the website (like systempay, Monetico, etc)
3. Admin Back : change a product price while the user is taping his credit card
4. Front : the user finish order process
5. Admin Back : order appear as "Paiement error", because customer paid the old price but when order is validate, it take the new price of products.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1.24

**Comment by khouloudbelguith** [comment]
Hi @adipso-jerome,

Could you provide me a `systempay` module to test with it, I tried with Paypal but there are problems in the configuration of this module.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks

**Comment by khouloudbelguith** [comment]
Hi @adipso-jerome,

I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @adipso-jerome,

The installation of this module is very long, is not finished until now, more than 15 min.
I attached a video record
https://drive.google.com/file/d/1mc9J4bLo-co3-m-UkW_7NOlAVQXbvi5G/view
Thanks to check & feedback.

**Comment by adipso-jerome** [comment]
Hi @khouloudbelguith,
I don't know what you want to do with the module (without account you can't pay).
Here an exemple with video : https://drive.google.com/open?id=1pd9y_sZP9IGdsMlk2IZVHNVPNa33TsIl
I try with other paiement, it's the same problems. At the end, the customer don't pay the price he expect, but the price in database when he valid the order. Do you see the problem?

**Comment by khouloudbelguith** [comment]
@adipso-jerome, I tried to check the issue with a payment method that makes me leave the website.
But in your case, I did not manage to reproduce the issue with PS1.7.5.0
I attached a video record
[Nov 27 2018 2_53 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2620255/Nov.27.2018.2_53.PM.webm.zip)
Thanks to check & feedback

**Comment by adipso-jerome** [comment]
@khouloudbelguith , your video show exactly the problem : you was about to pay your order 36.00€, but when you clicked on "Order with an obligation to pay", you have only 12€ to pay. Its not possible, user should pay 36.00€, not the new price.
Do you see the problem?

**Comment by khouloudbelguith** [comment]
@adipso-jerome, no, I don't think so.
I edited the new price before I confirm the order so, in the order confirmation page, we should have a new price.
Thanks!

**Comment by adipso-jerome** [comment]
@khouloudbelguith here a proof with paypal : https://drive.google.com/file/d/1lhYV3bQK-q-e-aVTFBWwPtcxYCHZzJ2u/view?usp=sharing
I paid 34.80 but price of my order is 58.80 ... Prestashop should not take new product price but price when the user click "pay" on step 4
Do you see the problem?

**Comment by khouloudbelguith** [comment]
@adipso-jerome, I do not agree with you, the price is changed during the order checkout, in the last steps & it is not finished => so the price should be changed.
@marionf what do you think about this issue? it is a normal behavior or a bug?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith it's a normal behavior, the price change if you update it
