### ISSUE TITLE
Get the price in the hook 

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#11505]
**Describe the bug**
Get the price in the hook is not possible, an error appears
![image](https://user-images.githubusercontent.com/13940741/49001366-8af76b00-f16d-11e8-9cc0-360daee28fd4.png)

**To Reproduce**
1.    use - "hookactionCartSave"
2.    $context = Context::getContext();
       $cart = new Cart($context->cookie->id_cart);
       $total_prod = $cart->getProducts(true, false, null, true);
3.    
![-1](https://user-images.githubusercontent.com/13940741/49001879-fa218f00-f16e-11e8-8731-38742ad343f4.jpg)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0.30

**Comment by khouloudbelguith** [comment]
Hi @dmitrij1988,

I did not manage to reproduce the issue with PS1.7.4.4.
I used this module
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2614866/mymodule.zip)
Thanks to check & feedback.

**Comment by ewonta** [comment]
Thank you! I found a bug!

**Comment by khouloudbelguith** [comment]
@dmitrij1988, Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
