### ISSUE TITLE
Order message of order detail not showing in BO

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11503]
Hello,

**FO**
After made an order, a customer can add a message in the order detail (from his account).
https://tof.cx/image/kg0zA

**BO**
But If I go in Customer Service > Order Messages, there is not the message.
https://tof.cx/image/kgERz

**To Reproduce**
1. Make an order in FO
2. Go in the detail of your order in your account
3. Scroll down to "add a message" and send it
4. You can see him in the detail of your order
5. Go to BO > Customer Service > Order Messages
6. Don't see the message

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.4.4.
In FO, after adding a message, in the BO, I get a notification message
![image](https://user-images.githubusercontent.com/16067358/49000406-bff9c280-f159-11e8-82d2-9b16a399076e.png)
If I click on it, I will be redirected to the customer service page
![image](https://user-images.githubusercontent.com/16067358/49000422-d1db6580-f159-11e8-8912-909ff8cbedba.png)
Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
Thanks to check and feedback.

**Comment by BenTen** [comment]
There was a delay. I can see it now, sorry.
