### ISSUE TITLE
Customer review module

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/PrestaShop#11518]
Product comments module : Allows users to post reviews.

- [x] [All UX improvement](https://invis.io/KHP9OX9246Q#/333001938_Configure) 
- [x] [Addons block](https://github.com/PrestaShop/PrestaShop/issues/11402) 

Back office [behaviour ](https://invis.io/KHP9OX9246Q#/333001938_Configure): 

1) Merchants are able to configure 4 option in their back office. 
 - Choose if they want to add moderation of every comments 
 - Allow guest reviews
 -  Configure minimum time between 2 reviews from the same user
 - Enable/disable upvotes/downvotes on reviews (which not affect display of comments in FO) 

2) Merchants will have 3 sections with the listing of 
 - reviews waiting for approval
 - reported reviews 
 - approved reviews 

3) And merchants will be able to add/edit/delete criterions name, status and application scope of the criterion ( valid for the entire catalog, restricted to some categories, restricted to some products) 
![image](https://user-images.githubusercontent.com/40759259/49023738-26053a80-f198-11e8-8d93-7d5b78bc99ab.png)

Front office behaviour : 
1) Product page : 
- In product page, [if there is 0 reviews,](https://projects.invisionapp.com/d/main#/console/16057198/333001937/preview) at the bottom, two 
 buttons appear to invite people to add a 
 reviews. Else[ if there is reviews](https://projects.invisionapp.com/d/main#/console/16057198/333001936/preview), one button appear to write a review. 
- Rating based on rating on reviews appear on the product page 
- After 8 reviews, pagination appears 

2) Review card : 
Reviews appears at the bottom of the page with  : 
the date, the name of the owner of the review, rating, title of the review, the review, area where appear like/dislike button (if they are enabled in BO), report button. 

![image](https://user-images.githubusercontent.com/40759259/49023769-3a493780-f198-11e8-876a-5b9820320d22.png)

3) Writing a review : 
- If you are [connected](https://invis.io/KHP9OX9246Q#/333001934_Write_A_Review_-1-), there is title, review field and criterions to fill.
![image](https://user-images.githubusercontent.com/40759259/49023822-5a78f680-f198-11e8-9aed-8011284e67bd.png)

- If you are [disconnected](https://invis.io/KHP9OX9246Q#/333001935_Write_A_Review), you need to fill your name too.  
![image](https://user-images.githubusercontent.com/40759259/49023806-5220bb80-f198-11e8-9747-29d84a5191ca.png)

Additional specific behaviour : 
- If someone upgrade from a prestashop version < 1.7 then we should recover every comments. 
- If someone delete his account, all his reviews should be anonymize (for GDPR). 
- Reviews appear from the most recent to the oldest order. (like/dislike button doesn't affect the order of display.

Here is the current [ZIP](https://github.com/PrestaShop/productcomments)

**Comment by duGuillaume** [comment]
it will be great to add another option to allow comment only if you have purchased the product

**Comment by jolelievre** [comment]
Important Note: this module must respect RGPD laws, so be sure to respect this behavior:
http://build.prestashop.com/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/

**Comment by jolelievre** [comment]
Two PRs linked to this issue https://github.com/PrestaShop/PrestaShop/pull/12564 and https://github.com/PrestaShop/productcomments/pull/26
Waiting to be reviewed before QA

**Comment by colinegin** [comment]
Still waiting for this PR to be approved before publishing the module : https://github.com/PrestaShop/productcomments/pull/33
