### ISSUE TITLE
Manufacturer Part Number in product codes

### ISSUE THREAD

**Issue by mklimkiew** [PrestaShop/PrestaShop#11517]
Manufacturer Part Number is missing in the product codes section.
An additional field in which you can enter the manufacturer's number (digits or letters) will improve the indexing and searching. It will also have a positive effect on SEO.

The Reference (SKU) number is used rather to identify the product internally in the online and stationary store. Practically, it does not have to be visible to the customer.

The MPN number is used to identify a specific product of a given manufacturer. 
Here you can apply the "mpn" field according to Schema.org

This new feature can be very useful in stores offering automotive spare parts, but also in other industries that use numbers to identify products. 

You could add extra filed to enter MPN in the Product Options tab, just near EAN, UPC and ISBN codes.
![ps-1-7-5-0-mpn](https://user-images.githubusercontent.com/45269666/49024339-8b0d6000-f199-11e8-99fe-9520b7062129.jpg)

**Comment by khouloudbelguith** [comment]
Hi @mklimkiew,

Thanks for your report.
In the BO => Catalog => Products => Options Tab, in the bottom of the page, you can find a block to add the Supplier reference
![image](https://user-images.githubusercontent.com/16067358/49032937-2d374300-f1ae-11e8-927a-f72f888e90b5.png)
Thanks to check & feedback.

**Comment by mklimkiew** [comment]
This is only Supplier reference, not Manufacturer. I think supplier reference number is used more for stock monitoring, not as a part of product description. You can have the same product from different suppliers...

Moreover after adding supplier reference to the product you can not search this product under this entry in Front Office.

MPN should work more similar to EAN or UPC. Just MPN should be alphanumeric.
This new feature would be very useful.

**Comment by khouloudbelguith** [comment]
@mklimkiew, thanks for your feedback.
@marionf, @colinegin, what do you think?
Thanks!

**Comment by mklimkiew** [comment]
@khouloudbelguith Do you think this issue should be labeled as 1.7.4.4 ?
As an option for new feature I think it could be 1.7.5.0

**Comment by khouloudbelguith** [comment]
@mklimkiew, the `1.7.4.4` label is the Affects version & not the fix version.
Thanks!

**Comment by MatShir** [comment]
Hi @mklimkiew, 
Unfortunately, I won't be for 1.7.5. The release candidate is out and our backlog is quite full of new features for the next version. But I will share your idea on [feedback.prestashop.com ](http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/36520666-add-new-references-in-product-page-mpn-ean-14), the community helps us to prioritize. 
Don’t hesitate to make a pull request (https://github.com/PrestaShop/PrestaShop/tree/develop) if you have a developer background, we will be keen to guide in the process. And hopefully, someone will suggest a Pull Request before we do. 
Thanks

**Comment by mirali-se** [comment]
HI there,
I can not find Supplier reference In the BO => Catalog => Products => Options Tab in PS 1.7.6.0. any suggestion?

**Comment by khouloudbelguith** [comment]
Hi @mirali-se,

This issue is different, can you open a new one with more information about your configuration.

Thanks!

**Comment by pogo84** [comment]
Vote for it, its not only for automotive spare parts, now I have to change fields descriptions ;) vote yes

**Comment by matks** [comment]
🎉

**Comment by mklimkiew** [comment]
Many thanks to everyone engaged in this PR! Much needed improvement.
