### ISSUE TITLE
This value is not valid.

### ISSUE THREAD

**Issue by Lndaw** [PrestaShop/PrestaShop#11512]
**Describe the bug**
We have several bugs:
-I can`t update porducts or create it if the product has features. The backoffice shows an error message in each values' feature: "This value si not valid".

-We have installed a module called "Seur". Is a module about delivery products. This module has changed the the backoffice's main menu. Then, the link "transport>preference" has changed and it doesn`t work because try to access to de configuration's module installed.

**To Reproduce**
First bug:
1. Go to "Catálogo" -Catalogue-
2. Click on 'Productos' -Products-
3. Click on any Product.
4. If the product has "Características" -features- added, then click on "Guardar" -Save-.
5. Then, a message erros will be shown under each features' values.
Second bug:
1.Click on transport>preference

**Screenshots**
Scrrenshots about the first bug:
![mug4tho21o6r95zqdoqcnfyueiavd-7ugq](https://user-images.githubusercontent.com/3532079/49018762-8db58880-f18c-11e8-9526-b84e7ade922a.jpg)

This is the error message that appears when the product is saved

**Comment by khouloudbelguith** [comment]
Hi @Lndaw,

If you disable the `seur` module, all these issues disappear?
If you enable the debug mode, is there any exception displayed?
Thanks!

**Comment by LazaroMarin** [comment]
Hi @Lndaw and @khouloudbelguith 
I have disable the Seur module and it has fixed  the problem with the menu "transport->preference".
On the other hand, degub mode doesn't display any exception.

**Comment by khouloudbelguith** [comment]
@LazaroMarin, you should contact the module author about this issue https://addons.prestashop.com/en/contact-us?id_product=32140
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Lndaw,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by mauricecec** [comment]
I have the same exactly Issue , i upgraded Prestashop to 1.7.8.7 everything work fine , but i have features problem:
For example if i select Default Features no problem the product will be saved , but if i save 2 3 times different features Custom
i will get the following error This value is not valid.
I updated php to 7.4 but same issue , than i deactivate 90% Modules , and i continute to get this problem
Any suggetsion will be appreciated.

**Comment by mauricecec** [comment]
Kindly ask if anyone get same problem as described problem thanks

**Comment by dandumit** [comment]
I have same problem. I saw a similar issue raised.  IS there any workaround at least ?
Daniel
