### ISSUE TITLE
Bug found on invoice with discount voucher.

### ISSUE THREAD

**Issue by wouterb038** [PrestaShop/PrestaShop#11520]
Hello,

The discount codes in 1.7 do not work well. We have created a 10 euro product on a new installation (1.7.4.x or 1.7.5.x). Then we have created a discount code of 100 euros. The calculation does not go well on the invoice.

**To Reproduce**
1) Create product €10.00 excl. VAT (€12.10 incl. 21% dutch VAT).
2) Create a discount voucher of €100 (Action: Discount amout: €100 incl. VAT).
3) Create a test order with the test product en apply the test discount voucher. Now you get a "free" order and dont have to pay, next step.
4) Go to the admin -> Orders -> Test order -> Download PDF invoice.
5) Look at the Tax-detail and totals discount amout. The wrong calculations on the invoices are:
- Tax-detail base price: €72,64  (should be: €0)
- Tax-detail total price: €15,26   (should be: €0)
- Total discount: € 82,64   (should be: €10)

So something goes wrong with splitting the discount code. It is nice that the discount code is re-created with the remaining amount. But the invoice is not correct.

I tested on 1.7.4.x and 1.7.5.x

Screenshot:
![in000004](https://user-images.githubusercontent.com/1822139/49027652-f870bf00-f1a0-11e8-9225-d23c52e3a96a.jpg)

**Comment by khouloudbelguith** [comment]
Hi @wouterb038,

I manage to reproduce the issue with PS1.7.4.4/ PS1.7.5.0beta1.
The total Discount is correct, but it could be improved, 
`if Total discount > total => total discounts =0`.
The block tax is incorrect
![image](https://user-images.githubusercontent.com/16067358/49031549-8a30fa00-f1aa-11e8-8fcf-8c9316a63eba.png)
We will see how to fix it.
Thanks!

**Comment by wouterb038** [comment]
@khouloudbelguith @marionf 

Do you have any idea if this bug is solved in 1.7.5.0? or will this most likely be 1.7.6.0?

**Comment by khouloudbelguith** [comment]
@wouterb038, unfortunately, we only accept security fixes or regression from 1.7.5.0 on this branch to be focused on the 1.7.5.0 version, as described here: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#target-branch
Thanks!
