### ISSUE TITLE
1.6.1.23: After Upgrade from 1.6.1.19 > 1.6.1.23 Unable to Use Add Discount - > free Freight in submitted Order: Error "The discount value is invalid."

### ISSUE THREAD

**Issue by OhmegaStar** [PrestaShop/PrestaShop#11522]
After upgrading from 1.6.1.19 (where the feature was working) to 1.6.1.23 I'm unable to add the discount "Free Freight" to an existing order, the error from the system is "The discount value is invalid."

**To Reproduce**
Create an order whith Freight.

Go to backoffice, 
go to order details, 
choose to add discount
Name the Discount e.g "Free Freigth Missing"
Choose Type "Free Freight"

Add the Discount 
See the Error Message "The discount value is invalid."
See that the discount has not been added.

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @OhmegaStar,

Thanks for your report.
I manage to reproduce the issue with PS1.6.1.23, I cannot add a discount "Free shipping" in the BO => Orders => Order details.
In the PS1.6.1.19 =>OK; 1.7.5.0 => ok

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards

**Comment by OhmegaStar** [comment]
The Fix is here;

/controllers/admin/AdminOrdersController.php:

Line; 1337
                } elseif ((Tools::getValue('discount_type') == 2 || Tools::getValue('discount_type') == 1) && (float)Tools::getValue('discount_value') <= 0) {

check for a positive value non zero only for percent and amount discounts.

/OhmegaStar

**Comment by OhmegaStar** [comment]
Well that is only part of the fix it seems, there is some other place as the free freight is still not added when users approves order in front office flows..

**Comment by Casper-O** [comment]
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/controllers/admin/AdminOrdersController.php#L1337

This is the line that cause the issue, what solved it for me was that i changed to the code to the following
`} elseif ((float)Tools::getValue('discount_value') <= 0) {`

To this:

`} elseif ((float)Tools::getValue('discount_value') <= 0 && Tools::getValue('discount_type') != 3) {`

My guess is that if I or others spend the time looking through the code changes from 1.6.1.19 and to 1.6.1.23, the discount_value might have been set to 1 by default, when people selected "Free shipping" as discount type.
