### ISSUE TITLE
Improve the creation of Kpi

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#11524]
Looking at the way we create new Kpis views, we always do the same things with the same dependencies on when we implement the interface.

I think we have a good opportunity to introduce a new abstract class using "Template Method pattern" because we only have to create a new Kpi and then this object is rendered.

How about getHelperKpi() : HelperKpiInterface? It's rôle is to return an instance of Kpi with a method named generate.

See https://github.com/PrestaShop/PrestaShop/pull/11519/files#diff-bafc8da8a0ebe28c563926d99cd44b0aR67

**Comment by colinegin** [comment]
@mickaelandrieu is it a critical task for 1.7.6 ?
We need to prioritize this issue compared to all the other projects in progress.

**Comment by mickaelandrieu** [comment]
it's a nice improvement for developers and could be done by the community.

I think it's like 1 day of work, and a very low priority :+1:
