### ISSUE TITLE
Error occured during installation

### ISSUE THREAD

**Issue by chicochicaya** [PrestaShop/PrestaShop#11539]
![prestashop-error](https://user-images.githubusercontent.com/18226427/49157352-e36e6a00-f31f-11e8-84df-b9d067fef1dd.PNG)

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1, Wamp, Local

**Comment by khouloudbelguith** [comment]
Hi @chicochicaya,

Thanks to follow these steps during the installation

1. Set up your database
2. Download Prestashop and extract
3. Upload Prestashop to your server using FTP
4. Change file permissions of all directories to 777 using your FTP software. In Filezilla, this is done by:
5. File permissions >777>tick box to do it for all subdirectories> choose directories only
6. Go to the website in a browser and follow instructions as normal
7. Delete the install folder
8. Rename ‘admin’ folder and record the new name

You can follow this link: https://www.youtube.com/watch?v=IOM9AffOa3s, check, and feedback.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @chicochicaya,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
