### ISSUE TITLE
New created product (imported) not shown in category page, but accessible in search and catalogue PS 1.7.2

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#11530]
**Describe the bug**
Import some product using PS import function or 3rd part module.
Try to find in category page with no luck.
Product was right created and activated.
filter and search index was updated.
Product are visible trought search and direct url on catalogue, but still not shown in category page

**To Reproduce**
1) create new product or import, assing to a new or old category or to many one
2) save, update search and filter index
3) check in the category (both default or correlated), product are not shown
4) use catalog search will find the product
5) product is visible accessing the product url or by search

remove category and re-add does not solve problem

PRODUCT URL: https://store.sixrace.it/it/protezioni-leve/40962-ducati-panigale-v4-s-set-protezione-leva-freno-2018.html

CATEGORY URL:
https://store.sixrace.it/it/protezioni-leve

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/24798703/49098540-65eb2100-f26f-11e8-9934-ccc7b5e8e447.png)

![image](https://user-images.githubusercontent.com/24798703/49098560-6f748900-f26f-11e8-875e-7a4e980bfca5.png)

**Additionnal information**
Versione di PrestaShop: 1.7.2.4

URL negozio: http://store.sixrace.it/

Tema attualmente utilizzato: classic

Informazioni sul server: Linux #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64

Versione software del server: Apache/2.4.33 (Ubuntu)

Versione di PHP: 7.0.32-2+ubuntu16.04.1+deb.sury.org+1

Limite di memoria: 4G

Tempo di esecuzione massimo: 6000

Dimensione Max. dei file da caricare: 200M

Modulo PageSpeed per Apache installato (mod_instaweb)

 INFORMAZIONI DATATBASE
Versione MySQL: 5.7.21-20

Server MySQL: 127.0.0.1

Nome MySQL: Prestashop_1

Utente MySQL: prestashop

Prefisso delle tabelle: ps_

Motore MySQL: InnoDB

Driver MySQL: DbPDO

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Thanks for your report.
In the BO => Catalog => Products => Product page => Options Tab, could you please check the Visibility of this product is selected to "Everywhere", if not, thanks to select it, save, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/49099107-ebbb9c00-f270-11e8-9ed9-2ae06d205a1b.png)

**Comment by matteolavaggi** [comment]
Hi dear, naturally all the product has visibility set to anyware

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Thanks for your feedback.
In my case, I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record
[Nov 28 2018 10_13 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2623694/Nov.28.2018.10_13.AM.webm.zip)
To make sure, thanks to navigate to your BO => CONFIGURE => Shop Parameters => Search => INDEXING => Click on "Add missing products to the index" / "Re-build the entire index".
Thanks!

**Comment by matteolavaggi** [comment]
Hi dear, i've just done the reindex (product was searchable), my ps version is 1.7.2.4 (the buggy one i think), any idea on how to fix / diagnose? product was 100% visible but not shown in the category (also in backoffice).

Categoryes in BO result "empty"

**Comment by matteolavaggi** [comment]
![image](https://user-images.githubusercontent.com/24798703/49146644-ddb65b80-f302-11e8-8dc9-d0e41ad5bd4f.png)


![image](https://user-images.githubusercontent.com/24798703/49146663-e73fc380-f302-11e8-81a0-e4e344d6a1c2.png)

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS1.7.2.4 either.
I attached a video record.
[Nov 28 2018 11_57 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2624083/Nov.28.2018.11_57.AM.webm.zip)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matteolavaggi** [comment]
php log dont show usefull information. and on our prestashop store enabling debug mode in BO result in nothing ^^ very good :P , another way to get log?

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

I checked again your shop, but I did not manage to reproduce the issue.
https://drive.google.com/file/d/1N8zQSs8Ya2Iai51D51y7m6XY_ZITsWtC/view
Thanks to check & feedback.

**Comment by matteolavaggi** [comment]
Isse is still here, we need to re open each product (by using 3rd part module due to this ISSUE - [https://github.com/PrestaShop/PrestaShop/issues/11186](https://github.com/PrestaShop/PrestaShop/issues/11186) - affecting last 5 major release of PS and not yet fixed), and change category, next apply back the original one.

**Comment by khouloudbelguith** [comment]
@matteolavaggi, What is the exact 3rd part module did you use? it could be a problem?
Thanks!

**Comment by matteolavaggi** [comment]
I use it to update category so its used to "fix the problem", BTW
to import: Product Catalog (CSV, Excel) Import
to update: Mass edit product

**Comment by khouloudbelguith** [comment]
@matteolavaggi, thanks for your feedback.
@marionf, I did not manage to reproduce the issue with PS1.7.4.4 / PS1.7.5.0 / 1.7.4.3.
What do you think?
Thanks!

**Comment by marionf** [comment]
I can't reproduce it either, products are well displayed in the category after an import
