### ISSUE TITLE
Design => Pages - Filtering by position causes an exception

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11540]
**Describe the bug**
In the BO => Design => Pages page, when we try to filter "PAGES IN CATEGORY" by position an exception is displayed.

**To Reproduce**
1. Go to BO => Design => Pages page
2. By default, you have more than two pages in the Home category
3. Filter by position

**Screenshots**
https://drive.google.com/file/d/16jHobSq0d8i5rNTPezmcf_hOP-iYnwO1/view
![image](https://user-images.githubusercontent.com/16067358/49161742-b921aa00-f329-11e8-9af3-3c87edbfed7c.png)

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0
PHP version: 7.1

**Comment by matks** [comment]
This is fixed by the page migration. @marionf do you want to check ?

**Comment by marionf** [comment]
Yes, it's fixed
Thanks @matks
