### ISSUE TITLE
Module Template overrides not working in 1.7.4.4

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#11548]
Hi

In previous versions of prestashop 1.7.4 a module template could be overridden in the theme folder in the following fashion:

/theme/classic/modules/mymodule/views/templates/front/mytemplate.tpl

and Prestashop would automatically use the above overridden template when available.

However this does not work in PS 1.7.4.4.  But works fine in Prestashop 1.7.4.0

The only way I found to make it work was to rename / delete the original module template file which then forces Prestashop to use the override.  

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Could you please try to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office.
Thanks to check and feedback.

**Comment by SP86** [comment]
Hello. 
I have the same problem. Delete the file 'config/themes/themename/shop1.json' does not work.

My situation is following.
I installed the "supercheckout" module. The file I want to change is along the way.
"modules/supercheckout/views/templates/front/cart_summary.tpl"

I placed this file in such folder: "themes/classic/modules/supercheckout/views/templates/front/cart_summary.tpl". Then I made some changes in this file. But these changes were not applied. The code is output from the original module file

**Comment by khouloudbelguith** [comment]
Hi @SP86, could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
And, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by SP86** [comment]
In Admin Panel my "Debug mode".
![image](https://user-images.githubusercontent.com/12730330/49730899-624d9600-fc82-11e8-99ef-54916401709a.png)
Also I clear  "var\cache\dev" and "var\cache\prod"
![image](https://user-images.githubusercontent.com/12730330/49730939-7abdb080-fc82-11e8-9368-96cdace03db2.png)
I clear cache from Admin-Panel.
Also I delete the file 'config/themes/themename/shop1.json' 

My original module Tpl file 
![image](https://user-images.githubusercontent.com/12730330/49731132-059eab00-fc83-11e8-91ac-aec9e8e28052.png)

My override Tpl file
![image](https://user-images.githubusercontent.com/12730330/49731166-20711f80-fc83-11e8-86df-cbc43a9816b6.png)

But unfortunately аfter all the changes I still see original code from tpl module file.
![image](https://user-images.githubusercontent.com/12730330/49731586-83af8180-fc84-11e8-9371-c216471a704f.png)

**Comment by musaffar-patel** [comment]
Before posting the original bug report, I also tried all the suggested steps, deleting the json file, clearing caches + cache folder, disabling caching and enabling debug mode.  Unfortunately the only solution which worked was to delete the original module template file which then resulted in Prestashop using the override file instead.

**Comment by SP86** [comment]
When I leave the file "themes/classic/modules/supercheckout/views/templates/front/cart_summary.tpl , and delete it in the main module "themes/classic/modules/supercheckout/views/templates/front/cart_summary.tpl", I get an error in the work of the module
![image](https://user-images.githubusercontent.com/12730330/49732470-7fd12e80-fc87-11e8-9751-a0fdc7c70d38.png)

**Comment by khouloudbelguith** [comment]
Hi all,

With PrestaShop 1.7, all module overriding code goes to the modules directory (in your module’s own directory). Every PS 1.7 module developer should be aware of this change (introduced with PR: https://github.com/PrestaShop/PrestaShop/pull/5020).
For more details, you can follow our [documenation](https://devdocs.prestashop.com/1.7/themes/reference/overriding-modules/)
Thanks to check & feedback.

**Comment by musaffar-patel** [comment]
If the overrides go into the modules own directory, then are these overrides preserved after the module is updated?

**Comment by khouloudbelguith** [comment]
@musaffar-patel, so do you need to make changes in modules/demo_module/views/templates/front/demo_module.tp ?
Thanks!

**Comment by musaffar-patel** [comment]
Hi

I'm slightly confused:
modules/demo_module/views/templates/front/demo_module.tpl

this is simply the path to the normal module template

However, module templates can be overridden at the theme level to and upto Prestashop 1.7.4.3, I could do the following:

/themes/classic/modules/demo_modules/views/templates/front/demo_module.tpl 

to override module templates.  This was particularly useful because it meant we could customize assets such as templates, css and js which would not be overwritten when the module is upgraded.

However, I can't seem to be able to do this anymore in Prestashop 1.7.4.4.  My original post details the issue.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Could you please provide me the custom module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by evagofr** [comment]
Hi, 
I am also experiencing it since we updated to 1.7.5.0 last month (from 1.7.2.4).
Module : psgdpr (GDPR Official / RGPD Officiel (in french) v1.1.2 by Prestashop)
Did not see other modules impacted but this is possible. I tested a minor modification on contactform module overide and it works. So there is only this one module psgdpr for now.

**Comment by khouloudbelguith** [comment]
@Juke29,

What is the exact modification did you make with the module GDPR? could you please provide me the override?
Thanks!

**Comment by evagofr** [comment]
I simply added a `<p>some texte</p>` to the file: 
my_theme/modules/psgdpr/views/templates/front/customerPersonalData17.tpl

**Comment by evagofr** [comment]
I tried to update the file directly in /modules/psgdpr/ but now I see that it is not updating either!
I don't get it, any other module's files I see the update, but not this one, neither in /modules/ or in /my_theme/modules/.

**Comment by khouloudbelguith** [comment]
Hi @Juke29,

There is one very important issue that you should be aware of. When loading a template file (for instance ‘moduledemo.tpl’), PrestaShop will look for overriding first, in the following order:

```
/themes/THEME_NAME/modules/MODULE_NAME/views/templates/front/moduledemo.tpl
/modules/MODULE_NAME/views/templates/front/moduledemo.tpl
```
**But** if your moduledemo.tpl file **includes** the included-template.tpl file, you will have to override ‘included-template.tpl’ as well, even if you don’t want to modify it (nor to edit the path). This means that every file that an overridden file includes needs to be copy-pasted as-is in order for your override to work properly.

The issue goes both ways: if you want to modify the included-template.tpl file, you will have to override the moduledemo.tpl file that includes it.

`{include file='./included-template.tpl'} `

PrestaShop 1.7 introduces a new cool way to include files in module templates. By using this method, all the expected rules will be followed:

`{include file='module:MODULE_NAME/views/templates/front/included-template.tpl'}`

Thanks!

**Comment by evagofr** [comment]
Hi, thanks for the reply. I do know the concept of includes. This tpl file is not included anywhere I am aware of, as it is a direct template. It is extended from theme's customer/page.tpl however.

Before update, it was working fine. And I checked the file, it did not change a bit (compared my_theme/modules/psgdpr/ to local file from before update).
The most astonishing is that modifying the real tpl file in module's directory (/modules/) does not appear either. This is weird.

**Comment by khouloudbelguith** [comment]
@Juke29, before updating from which version?
Thanks!

**Comment by evagofr** [comment]
PS update from 1.7.2.4 to 1.7.5.0, I checked if psgdpr got an update but no, it was 1.1.2 before and today, sorry for the misunderstanding.

**Comment by khouloudbelguith** [comment]
@Juke29, thanks!
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@Juke29, thanks a lot for your feedback.
I created a file into my_theme/modules/psgdpr/views/templates/front/customerPersonalData.tpl
```
{include file='module:psgdpr/views/templates/front/customerPersonalData.tpl'}
{extends file='customer/page.tpl'}

{block name='page_title'}
		<h2>{l s='test' mod='psgdpr'}</h2>
{/block}
```

With PS1.7.2.4 & PS1.7.4.4 & PS1.7.5.0 => OK => when I navigate to the FO => GDPR - Personal data => the templete overrided is displayed
![image](https://user-images.githubusercontent.com/16067358/52429181-d205c300-2b03-11e9-8c8a-ba847b86b55e.png)
https://drive.google.com/file/d/1gKzti0n6EZ74Hb-CtF-k0IC3Ths921J0/view
You need to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by xiropot** [comment]
@khouloudbelguith ps 1.7.4.4 Ι try to fix greek encoding issue in customer message

/admin/themes/default/template/controllers/customer_threads/helpers/view

I add custom classes to check if something happens, the file is being saved as expected file permissions are ok but nothing changes :/

Moreover, on order confirmation, no email is being sent. Changed to SMTP (with wrong credentials on purpose) error (as expected), changed to the right ones (success message) but no email is being sent :/ Change back to PHP mail(), nothing as well.

**Comment by fubax** [comment]
Hello everybody
Excuse me for my English.
I have the same problem with PS 1.7.6 and really can't understand khouloudbelguith solution,but fortunately I solved this  with toggling "mod_security" option on Shop parameters>>traffic
Hope it can help others that may face similar problem

**Comment by Noido** [comment]
> When I leave the file "themes/classic/modules/supercheckout/views/templates/front/cart_summary.tpl , and delete it in the main module "themes/classic/modules/supercheckout/views/templates/front/cart_summary.tpl", I get an error in the work of the module
> ![image](https://user-images.githubusercontent.com/12730330/49732470-7fd12e80-fc87-11e8-9751-a0fdc7c70d38.png)

Hi @SP86, @khouloudbelguith  Do you have find solution for override supercheckout template ?

I try in theme/mytheme/modules/supercheckout/views/templates/front/cart_summary.tpl

{include file='module:supercheckout/views/templates/front/cart_summary.tpl'}

Test


But this not work

Thanks

**Comment by HartLarsson** [comment]
PS 1.7.6.5 i still experiencing the same problem too

**Comment by itis-mmi** [comment]
as said by @HartLarsson, still experiencing the same issue in Prestashop 1.7.6.5 

my module template is in **modules/storelocator/views/templates/front/store_infos.tpl** 
my override template is in **themes/THEME/modules/storelocator/views/templates/front/store_infos.tpl** 


EDIT : found the solution (SPECIFIC TO STORELOCATOR), the template file was called with an absolute path via `$this->context->smarty->fetch()` instead of a relative call via `$this->display()`.

**Comment by masiorama** [comment]
@itis-mmi I have the same issue with a different module. In my case the template is loaded like this:

`$tpl = '../../../modules/'.$this->module->name.'/views/templates/front/thankyou.tpl';`
                `$thankyou = Context::getContext()->smarty->fetch($tpl);`

How did you solve it? Thanks!

**Comment by aritz-veiss** [comment]
Thanks @itis-mmi ! I had the same problem with another module.

@masiorama it should be something like:
$thankyou = $this->display(__FILE__, '/views/templates/front/thankyou.tpl');
