### ISSUE TITLE
It is impossible to filter the list of categories by position in the Design => Pages page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11546]
**Describe the bug**
In the BO => Design => Pages page when we try to filter the list of categories by position, the result is incorrect.

**To Reproduce**
1. Go to BO => Design => Pages page
2. You have at least more than one page Category.
3. Filter by position
4. See the error, the result is incorrect

**Screenshots**
https://drive.google.com/file/u/1/d/1T0P_jqUTJpAn0k_l4BGwobCK8arD8ei3/view

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0beta1
PHP version: 7.1

**Comment by matks** [comment]
This is fixed by the page migration. @marionf do you want to check ?

**Comment by marionf** [comment]
Yes, it's fixed +1
