### ISSUE TITLE
It is impossible to filter by position in the Categories page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11545]
**Describe the bug**
In the BO => Catalog => Categories page, when we try to filter by position, the result is incorrect.

**To Reproduce**
1. Go to  BO => Catalog => Categories page
2. You have at least more than one category
3. Filter by position
4. See the error, the result is incorrect

**Screenshots**
https://drive.google.com/file/d/1FoarYYgPiGFkkm3u3NxkQGYqvvknhIn_/view

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0beta1
PHP version: 7.1

**Comment by matks** [comment]
This issue is still true and needs to be fixed for 1.7.6

**Comment by matks** [comment]
In order to fix it, we need to apply https://github.com/PrestaShop/PrestaShop/pull/13125 for the Categories page
