### ISSUE TITLE
Clearing symfony cache after installing or uninstalling a module

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/PrestaShop#11557]
After prestashop 1.7.5 , modules can use Symfony's futures,
but, after unsinstalling a module some cache may be cleared,

For example Symfony routes are note cleared.
to constat this beahavior ,
 try to test new ps_linklist 3.1 version, and them try to uninstall it and install the old version : 2.14
( new route for the bo controller of this module is not cleared after uninstalling)

**Comment by khouloudbelguith** [comment]
Hi @123monsite-regis,

Thanks for your report.
Steps to reproduce the issue with PS1.7.5.x

1. Install ps_linklist v3.0.1
2. Click on configure button => OK
3. Uninstall ps_linklist module
4. Install [ps_linklist v2.1.4](https://github.com/PrestaShop/ps_linklist/releases/tag/v2.1.4)
5. Click on configure button => NOK

I attached a video record
https://drive.google.com/file/d/1UgTs-4TRQ7dXBch4SitfUBN7EQ3ZvMbh/view

Thanks!

**Comment by 123monsite-regis** [comment]
thanks @khouloudbelguith for the screen capture

**Comment by jolelievre** [comment]
This should be tested, but there are high chances that there is the same issue for every actions performed by the `ModuleManager` such as `install|uninstall|enable|disable|enable_mobile|disable_mobile|reset|upgrade`

**Comment by jolelievre** [comment]
hello @123monsite-regis this PR should fix a lot of problems with new modules installation https://github.com/PrestaShop/PrestaShop/pull/11572

By the way I noticed the same issue you mentioned when you uninstall the v3 and then reinstall the v2 It happens when you uninstall the module without removing the folder because the config files are still present and so they override the v2 behavior

**Comment by 123monsite-regis** [comment]
thanks @jolelievre 

Your work is more general than my reports :) , sorry to have targeted the module you are currenlty improving , it was just a sample. ( and a way to test new  modules sf's features ).

**Comment by jolelievre** [comment]
don't worry it's the only module migrated for now so it's expectable ^^

**Comment by mbadrani** [comment]
Same problem if you upgrade your module and trying to configure it
v2.1.5 is installed by default

**Comment by 8ternity** [comment]
I also discover that when i change my language code "QC" to "FR"; when debug is "ON"; Symfony is holding in cache the URL rewrite to new language code and get an error; It seem that Symfony has bad cache and causing issue while debut is ON. Should have a Symfony Clear Cache option too.
