### ISSUE TITLE
Help in Back office always in english

### ISSUE THREAD

**Issue by fd87** [PrestaShop/PrestaShop#11556]
Help in back office is always displayed in englis even if the default language is french and language of employee is also French.

**To Reproduce**
1. Go to a prestashop Back office in french with an employee's language set to french 
2. "Aide" on top left of the page
![image](https://user-images.githubusercontent.com/41292066/49206900-f7bc7080-f3cc-11e8-819f-62b89182834b.png)

3. See that help is in English :
![image](https://user-images.githubusercontent.com/41292066/49206933-0b67d700-f3cd-11e8-927b-a2f3f1cedd33.png)

**Additionnal information**
PrestaShop version: 1.6.1.20

**Comment by khouloudbelguith** [comment]
Hi @fd87,

I did not manage to reproduce the issue with PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/49207455-4100c600-f3b5-11e8-83ff-b2cbf3971c5b.png)
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!
