### ISSUE TITLE
When changing stores it redirects back to admin login  PS 1.7.4

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11555]
In multistore, whenever I switch stores and try to edit/configure one of the controllers it redirects me back to the admin login page. The URL/admin is then switched to that store.

1. Activate Store 1
2. Do some stuff (configure, edit) and save (e.g. in modules, or carriers, or international)
3. Activate Store 2
4. Go to carriers and then click edit carrier (this is just an example but applies to many things)

**Additional information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1Kr47Rk4Mw4GYfsfKN1srArgSo9n_10-P/view
Also, in the next release, we have made some fixes, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9450
https://github.com/PrestaShop/PrestaShop/pull/11478
Thanks to check & feedback.

**Comment by nrcjea001** [comment]
Hi @khouloudbelguith 

Thanks for getting back to me. Yes, this may be the same issue.

Can you please try this:

1. Login BO in default shop (Shop1)
2. You should see "All shops" on the top left so change to Shop1.
3. Go to international --> localization
4. Activate Shop2
5. Go to Currencies
(redirects to admin login)

**Comment by khouloudbelguith** [comment]
@nrcjea001, Thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.0beta1.
https://drive.google.com/file/d/1fc0gz4w9Tahkbck13FfUBJJSAJX_lSXw/view
Either with PS1.7.4.4, https://drive.google.com/file/d/1ZksIlPlDCFh9UuD3WeiN2IIhPuc0IjTc/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
THanks!

**Comment by nrcjea001** [comment]
Please advise me on how to retrieve this for you. I have cpanel so I can search in file manager. But what name do you give the file? I also entered debug mode but I don't know where exactly to look

Can you please try this (1.7.4.4):

1. Login BO in default shop (Shop1)
2. Activate Shop2 and sign out.
3. In your browser, enter url for BO of shop1 (e.g. shop1.com/admin)
4. At this point it would like you are still signed in.
5. Refer to my previous comment and repeat steps 2 to 5.

It appears that I can login BO on different URLs for different sites.

Many thanks

**Comment by khouloudbelguith** [comment]
@nrcjea001, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
I attached a video record: https://drive.google.com/file/d/1UfgqE9O7kNoLbYgA72zUwRFsNT4YKeTI/view
Could you please provide me the exact configuration for each store did you make, you can find it the Advanced Parameters => Multistore page.
Thanks!

**Comment by nrcjea001** [comment]
Hi

I think I see the source of the problem: all my shops are the main url. I don't understand how this happened. Please see screenshot below

I'm trying to disable them but it wont allow me to change a main URL. Is there another way to change it?

![image](https://user-images.githubusercontent.com/26452178/49217123-34489600-f3e6-11e8-8832-81a45b527adb.png)

Thanks

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Yes, I manage to reproduce the issue with PS1.7.4.4
https://drive.google.com/file/d/1kCy1FpeVq6-FnxNlb6TsFb1reMwpBfPt/view
But, in The PS1.7.5.x is fixed as I said.
https://drive.google.com/file/d/1JXZmlGYFYLVzl0lJN7otvPx8PR8EpA12/view
So, I close the issue.
Thanks!
