### ISSUE TITLE
One Click upgrade path folder failed installation - Now needs removing

### ISSUE THREAD

**Issue by magnum93** [PrestaShop/PrestaShop#11567]
Hello I have a 1 click upgrade that failed. Can anyone tell me how to clean flush the folder where it is held as I am now running outta disk space thanks.
Notes version 1.7.2 Failed 1 click upgrade needs flushing via FTP or other

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @magnum93,

Thanks for your report.
In your Project_Folder/modules/ you can find the `autoupgrade` folder, thanks to remove it.
After That, in the BO=> Modules => Modules & Services, Selection Tab, Search for the autoupgrade module & install it.
Or you can download it from [here](https://addons.prestashop.com/en/data-migration-backup/5496-.html) and then use the 'upload a module' in the Modules & Services page to install it.
Thanks to check & feedback.

**Comment by Quetzacoalt91** [comment]
There are also data added by the module in `<admin_folder>/autoupgrade`

**Comment by khouloudbelguith** [comment]
Hi @magnum93,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
