### ISSUE TITLE
Random address into customer's order (not related address or customer)

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#11562]
**Describe the bug**
Hi,

I'm having this identical issue:
https://www.prestashop.com/forums/topic/473780-order-address-becomes-random-address-of-other-users/

And I don't really know how to reproduce it. I've updated the store from 1.7.2 to 1.7.4.4 and it was working fine until I had this issue.
A customer purchases an item and then the delivery address is set from another customer, I've checked the prestashop tables ps_address and ps_customer and I can't see any issue... the ID's assigned of each address is correct to the customer but in the back office-orders I face the same problem as described in the forum.

Also this came from an order splitted into two (with same ID), but we have no different carrier or anything for theese products/customer/address, and the customer in question doesn't even have the address randomly placed

**To Reproduce**
Can't really, since the erro occurs very often

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

Thanks for your report.
Did you use the MailChimp module?
Thanks to check & feedback.

**Comment by ChineseNorris** [comment]
Hello @khouloudbelguith , and yes, we are using MailChimp integration module, should it be a problem?

Thanks for your fast feedback.

**Comment by khouloudbelguith** [comment]
@ChineseNorris, with MailChimp module, we manage to reproduce an issue related to your problem: http://forge.prestashop.com/browse/BOOM-5486
So, it could be a problem.
Thanks to disable it, check & feedback.

**Comment by ChineseNorris** [comment]
@khouloudbelguith since it's a random thing and not something that occurs, we will try to disable the module and see if we have problems again.

Thanks

**Comment by khouloudbelguith** [comment]
@ChineseNorris,

Thanks!
Waiting for your feedback.

**Comment by ChineseNorris** [comment]
Hello @khouloudbelguith ,

We encountered the same issue, now the issue we had is that the customer with order ID 12794 with customer ID 16948, the addess of the order is set with customer ID 16945 address, even with the mailchimp module uninstalled.

Maybe is something about concurrency?

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

I created two orders at the same time with different customers but I did not manage to reproduce the issue with PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/49461316-aad50180-f7f3-11e8-9ed2-bff90d53dee2.png)
Are there any errors in your log file?
Thanks!

**Comment by ChineseNorris** [comment]
Hello @khouloudbelguith 
Thanks for your fast reply, I can't replicate too the issue by myself, I think it should be under specific server stress conditions and with multiple orders at the same time. Where should I start looking in error log files? In the server or the prestashop? If so, where are the prestashop error logs located?

Best regards

**Comment by khouloudbelguith** [comment]
@ChineseNorris, don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith sorry, I've checked the article.
Apache logs: None, just a few blocked images
Nginx: none
Php: none

Can't really help with logs :/

**Comment by khouloudbelguith** [comment]
@ChineseNorris, have you ever cleaned up your database or imported the data?
Did you delete a customer in the database?
If no, did you use any module Social Login Connect (Facebook or Google login)?
Thanks!

**Comment by caedp** [comment]
Hi, I am having the same issue.

**Comment by khouloudbelguith** [comment]
@caedp, as I said before, did you deleted any data from the database?
 did you use any module Social Login?
Thanks!

**Comment by caedp** [comment]
I didn't delete any data from ps_address table. I am not using Social Login. According to my customers, the bug occurs upon confirming their order.

**Comment by khouloudbelguith** [comment]
@caedp, this issue occurs only when you use a specific payment method?
Also, did you use any custom carrier module?
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith yes, I've cleaned up the database with the module "[Database Optimization](https://mypresta.eu/modules/administration-tools/database-optimization.html)"
And also had restored the entire database from a backup, but never imported data,deleted or altered tables. 
Yes, I'm using a [facebook login ](https://mypresta.eu/modules/social-networks/facebook-login-connect.html).

This bug happened at first in only one module but then after more bugs appeared it's happening on more payment methods. The carrier we are using is a custom made from our carrier TIPSA, but the module won't work until we say to do so.

Thanks

**Comment by khouloudbelguith** [comment]
@ChineseNorris, thanks to check if you can reproduce the issue using the Facebook login.
Also, the problem probably comes from one of the carrier modules in front-office, that is where you should start to look for.
Check your orders, is it always from the same carrier? Or from a set of a carrier that a module created and deals with? If yes, then there is a high chance you have found the problem.
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith , I've reproduced the error with Facebook login without success.
It is always from the same carrier, but the strange thing is that the carrier is created from the back office and the bug happens sometimes, not always, so it's hard to reproduce and know where the issue is.
Do you think that wiping out all the carriers and create them again would do the trick?

Regards

**Comment by khouloudbelguith** [comment]
@ChineseNorris, it could be a solution, thanks to check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

Any new about your issue?
Thanks!

**Comment by ChineseNorris** [comment]
Hi @khouloudbelguith ,

Resetting the carriers did work, but would be great to look why is this happening.

Thanks!

**Comment by khouloudbelguith** [comment]
@ChineseNorris, did you a custom module for carriers, what are those modules?
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith the modules are custom made by a third company (carrier company), the modules are carriers from Spain like: TIPSA, CORREOS EXPRESS, SEUR, but we had problems with TIPSA mostly.

Thanks

**Comment by khouloudbelguith** [comment]
@ChineseNorris, as those modules are not provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
