### ISSUE TITLE
Questions about Prestashop features

### ISSUE THREAD

**Issue by DamienFel** [PrestaShop/PrestaShop#11574]
Hi there,

I am starting a new e-commerce project, using dropshipping system. I had someone on the phone from Prestashop that advised me to put my issues and questions here.

I would like to use BIG BUY as my supplier. Obviously, I would like to avoid manual actions and make it automatic. That is why I am planing to use the multi channel integration in order to synchronise product catalog, stocks, prices, orders, shipping fees.
https://www.bigbuy.eu/fr/multi-channel-integration.html

Yet, I would like to bring some light on some points :)
The call center told me that : 
The product catalog keeps the priority upon what is inside Prestashop categories (categories and products), meaning that : 
- inside prestashop if we change product infos (pdp) or images the last update of catalog will erase everything.
- If I download a sub-category "decorations > lights" (50 products). All the 50 lights will be displayed on the front for the final user/customer. I cannot choose to display only 20 of them for example.

Could you please confirm these 2 points please ? Is that the way it is managed or is there another option please ?

Then, other point about prestashop it self this time. I am comparing the tools on the market to find what suit the best my needs. I am sorry for the comparison but here are my questions. I saw that shopify propose nice features like these ones and I would like to know if Prestashop can handle these needs : 

- Buy button https://fr.shopify.com/buy-button
For example being able to add a "buy button" on an blog post like wordpress and then, when clicking, landing on the checkout page of prestashop.

- Sell on facebook and messenger 
https://fr.shopify.com/facebook
https://fr.shopify.com/messenger

Thanks a lot,

Damien F.

**Comment by khouloudbelguith** [comment]
Hi @DamienFel,

Thanks for your report, it's great to hear that you will use PrestaShop.
About your first question, could you please specify the "update catalog" action? which catalog you will update it & how you will update it?
About your second question, in PrestaShop, we have a native module [ps_featuredproducts](https://github.com/PrestaShop/ps_featuredproducts
) allows you to display featured products in the central column of your homepage with a number of products, from which category,...
![image](https://user-images.githubusercontent.com/16067358/49287303-42a5b900-f49d-11e8-8c27-e91680fa2528.png)
About the buy button, we have another [module](https://github.com/PrestaShop/ps_buybuttonlite) that will allow you to create a product checkout redirect link to post on a blog or any social media.
Also, you can find in ou [Market place](https://addons.prestashop.com/en/) a lot of modules you can help you to improve your shop.
Thanks to check & feedback.

**Comment by DamienFel** [comment]
Hello khouloudbelguith,

First, thanks for your answer and your time :)

As a customer from big buy, it is possible to synchronise products, stocks, prices, orders etc with prestashop, thanks to the MCI (multi-channel integration). I am interested in that feature.
https://www.bigbuy.eu/fr/multi-channel-integration.html

- Meaning the product, price, stock, etc. flow comes from Bigbuy. If they change an image or a product name, I am impacted directly into prestashop. I can always change it on prestashop but if they update, that will erase my modifications.
- Other point, if I decide to download all their "light category" (let's say 50 products) then I have to display all of them on the frontoffice (the 50) > I cannot select some product to download and/or display on front.
==> This is what bigbuy told me but it is quite weird from my point of view

Is there a direct phone number to discuss about the link betwen Prestashop and the big buy MCI (multi-channel integration) please ?

regarding the buy button, indeed this https://addons.prestashop.com/en/blog-forum-new/41139-buy-button-premium-.html could fit my need Thanks :)

**Comment by khouloudbelguith** [comment]
ping @eternoendless

**Comment by DamienFel** [comment]
Bonjour :)
Je me permets de vous relancer sur ces questions svp :)
--------
Hi
Do you have any update for my questions please ?

Thanks in advance,

Damien F.

**Comment by khouloudbelguith** [comment]
Hi @DamienFel,

Sorry for the delay.
In fact, this bug tracker GitHub is used to report issues and request new features only.
If you need help and support your request, you can ask on our Forum (https://www.prestashop.com/forums/) 
Thanks for your understanding!
