### ISSUE TITLE
Url next register

### ISSUE THREAD

**Issue by nayithu** [PrestaShop/PrestaShop#11577]
Hello,
I want to direct users to a different url to start page, after they register.

**Comment by khouloudbelguith** [comment]
Hi @nayithu,

With the module ps_customersignin, you can modify the URL after registration.
You need to edit this line https://github.com/PrestaShop/ps_customersignin/blob/master/ps_customersignin.php#L75
Thanks to check & feedback.

**Comment by nayithu** [comment]
but this works for "logout".

I need to change the url after the user registers

**Comment by khouloudbelguith** [comment]
@nayithu, so you need to edit this line, https://github.com/PrestaShop/ps_customersignin/blob/master/ps_customersignin.php#L76 by replacing the old URL with the new URL that you want to edit it.
Thanks!

**Comment by nayithu** [comment]
thank you very much for your help.

1. But what I want is that when you register here (http://techfitds.com/iniciar-sesion?create_account=1)

2. at the end of your sample registration this page (http://techfitds.com/paciente)

**Comment by khouloudbelguith** [comment]
Hi @nayithu,

In the file /Project_Folder/controllers/front/AuthController.php, you need to replace this line 
[$should_redirect = true;](https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/controllers/front/AuthController.php#L63)
by this code line:

```
$this->redirect_after = ($this->authRedirection) ? urlencode($this->authRedirection) : 'index.php?controller=address';
$this->redirect();
```

Thanks to check & feedback.

**Comment by nayithu** [comment]
Wooooo, I am very happy with your help, I love you.
Thank you thank you thank you

**Comment by khouloudbelguith** [comment]
@nayithu, Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Comment by nayithu** [comment]
I need to work with people like you. Write me to tell you about projects: nayith@origenweb.co

**Comment by Timotcho** [comment]
Hi everyone,
I just see ur topic and i'm very interrested about it, i have the same issus, i want to redirect the user after his registration like Nayithu, http://mywebsite.com/connexion?create-account=1 and after he submit the register form i want to redirect him to http://mywebsite.com/my-account, how can i do that please ?? i just test the line Khouloudbelguith send on the the top but it don't work.
Thank for ur reply.
