### ISSUE TITLE
Need a hook for a file attachments

### ISSUE THREAD

**Issue by RomSunZ** [PrestaShop/PrestaShop#11570]
**Is your feature request related to a problem? Please describe.**
I did not find possibilities to add to e-mail custom file that will be send together with mail after order validation.

**Describe the solution you'd like**
Please add a hook after 'Join PDF invoice' block inside  PaymentModuleCore->validateOrder.

**Comment by khouloudbelguith** [comment]
Hi @RomSunZ,

Thanks to check the [official hook list ](http://doc.prestashop.com/display/PS17/Hooks+in+PrestaShop+1.7.x), you can find the hook `actionEmailAddAfterContent`, `actionEmailAddBeforeContent`, `actionEmailSendBefore`
Thanks to check & feedback.

**Comment by RomSunZ** [comment]
Mensioned by you hooks do not work because in this case mail is sending from PaymentModuleCore->validateOrder function.

**Comment by kpodemski** [comment]
You're not right, you still can use those hooks, mails are always send using Mail class

**Comment by khouloudbelguith** [comment]
@RomSunZ, you can follow our [documentation](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/)

**Comment by khouloudbelguith** [comment]
Hi @RomSunZ,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
