### ISSUE TITLE
DisplayAdminProductsExtra hook form not display in product edit module page for PS1.7.5.0 beta

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11582]
**Describe the bug**
DisplayAdminProductsExtra hook return form not display in catalog product edit module tag configure button click

**To Reproduce**
1. Create a module which use 'DisplayAdminProductsExtra' hook and return a form
2. Go to Catalog -> Products, and edit a product
3. Click on 'Modules' tab and then click on Module 'Configure' button
4. Form not display

**Screenshots**
![download 15](https://user-images.githubusercontent.com/19220745/49326872-bcfa3a00-f57e-11e8-8410-da8a17bd9151.png)

**Fixed**
Change this line:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Twig/HookExtension.php#L137

From: 
```
- 'content' => array_values($hookRender)[0],
+ 'content' => $hookRender,
```

**Testing**
This change works if multiple module use this hook.

**Additionnal information**
PrestaShop version: 1.7.5.0 beta
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report & your fix.
Could you please provide us with an example of a module to test with it.
Thanks!

Related to #9889

**Comment by dheerajwebkul** [comment]
Ok @khouloudbelguith 

I will provide you ASAP.

But I don't think so #9889 related to this that much, in this #9889 form display but only file upload not working, I also faced this issue, But in this my issue, in PS 1.7.5.0 beta, all form data not display.

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, Thanks for this clarifications.
Waiting for your feedback.

**Comment by dheerajwebkul** [comment]
Hello @khouloudbelguith 

I have added the test module, please check

https://github.com/dheerajwebkul/wktestadminproductextra

A form like in this screenshot added to this module, But you can not see this form until you fix this by this PR https://github.com/PrestaShop/PrestaShop/pull/11584

![download 17](https://user-images.githubusercontent.com/19220745/49429820-7f402000-f7cf-11e8-9737-417507bdf5ec.png)

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.x.
In the PS1.7.4.4 => OK.
I tried with the `wktestadminproductextra` module & the `Product Videos - YouTube` module.
PS1.7.5.0 => NOK
![image](https://user-images.githubusercontent.com/16067358/49432250-8c4d1700-f7af-11e8-90ab-36a46f671c3c.png)
![image](https://user-images.githubusercontent.com/16067358/49432275-996a0600-f7af-11e8-9482-5e7ace8916a5.png)
PS1.7.4.4 => OK
![image](https://user-images.githubusercontent.com/16067358/49432294-a4249b00-f7af-11e8-8892-13ceeb02467b.png)
![image](https://user-images.githubusercontent.com/16067358/49432303-a8e94f00-f7af-11e8-8b31-e57fbc566ddc.png)
Thanks!

**Comment by kapilsurya895** [comment]
but not showing content in product page
