### ISSUE TITLE
Spinning Save Button on 1.6.1.23 Upgrade

### ISSUE THREAD

**Issue by andrewupandabout** [PrestaShop/PrestaShop#11589]
Host: Godaddy
PrestaShop Version: 1.6.1.23
System: Linux
PHP Version: 7.0.3

After upgrading to 1.6.1.23 I have the "save buttons spinning" on the products pages. (Last year I solved the issue of the "prestashop save buttons spinning" however can not find my notes on it.)

I have tried the below:

Upgraded PHP Version from 5.6PHP to 7.0.3PHP.

Visited [http://prestamania.com/prestashop-back-office-bug-not-saving-everytime/] but no string of [submitHandler: function(form) { form.submit(); },] is found to edit in the [admin//themes/default/template/controllers/products/helpers/form/form.tpl] file.

Force Compiled in the BO - Performance Page

 

When using Chrome and the Inspect Setting I see 4 Errors:

 

﻿#1 -------------------------------------------------------------------------------------------------------------------------------------------------------
jquery.fileupload-process.js:32

Uncaught TypeError: Cannot read property 'fileupload' of undefined
    at jquery.fileupload-process.js:32
    at jquery.fileupload-process.js:25
    at jquery.fileupload-process.js:29
(anonymous) @ jquery.fileupload-process.js:32
(anonymous) @ jquery.fileupload-process.js:25
(anonymous) @ jquery.fileupload-process.js:29

#2 -------------------------------------------------------------------------------------------------------------------------------------------------------

jquery.fileupload-validate.js:33

Uncaught TypeError: Cannot read property 'fileupload' of undefined
    at jquery.fileupload-validate.js:33
    at jquery.fileupload-validate.js:25
    at jquery.fileupload-validate.js:29

 

#3 -------------------------------------------------------------------------------------------------------------------------------------------------------
[DOM] Found 4 elements with non-unique id #product_form_submit_btn: (More info: https://goo.gl/9p2vKq)

<button id="product_form_submit_btn" type="submit" name="submitAddproduct" class="btn btn-default pull-right" disabled="disabled"><i class="process-icon-loading"></i> Save</button>

<button id="product_form_submit_btn" type="submit" name="submitAddproductAndStay" class="btn btn-default pull-right" disabled="disabled"><i class="process-icon-loading"></i> Save and stay</button>

<button id="product_form_submit_btn" type="submit" name="submitAddproduct" class="btn btn-default pull-right" disabled="disabled"><i class="process-icon-loading"></i> Save</button>

<button id="product_form_submit_btn" type="submit" name="submitAddproductAndStay" class="btn btn-default pull-right" disabled="disabled"><i class="process-icon-loading"></i> Save and stay</button>
 
 #4 -------------------------------------------------------------------------------------------------------------------------------------------------------
Uncaught TypeError: $(...).fileupload is not a function
    at HTMLDocument.eval (eval at <anonymous> (jquery-1.11.0.min.js:2), <anonymous>:25:14)
    at j (jquery-1.11.0.min.js:2)
    at Object.add [as done] (jquery-1.11.0.min.js:2)
    at e.fn.init.n.fn.ready (jquery-1.11.0.min.js:2)
    at eval (eval at <anonymous> (jquery-1.11.0.min.js:2), <anonymous>:19:16)
    at eval (<anonymous>)
    at jquery-1.11.0.min.js:2
    at Function.globalEval (jquery-1.11.0.min.js:2)
    at e.fn.init.domManip (jquery-1.11.0.min.js:3)
    at e.fn.init.append (jquery-1.11.0.min.js:3)

 

Any ideas to try?

**Comment by khouloudbelguith** [comment]
Hi @andrewupandabout,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-9042
It wasn't necessary to create a new one.
So, this one can be closed
Thanks!

**Comment by andrewupandabout** [comment]
Hi @khouloudbelguith, that bug is for May 2017, that's over a year ago. No new bugs could have occurred by then? Thanks.

**Comment by andrewupandabout** [comment]
Ok, I solved my issue. I had a file with no data in it. Thus I took a backup file and copied the code into the server file. Below is the file I needed to populate to make the spinning save buttons work.

"admin_folder"/themes/default/js/jquery.fileupload-validate.js
