### ISSUE TITLE
Checkout: unchecking "Use this address for invoice too" when having more than one address

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#11595]
**Describe the bug**
At checkout, when you have more than one address and you edit the delivery address, if you uncheck "Use this address for invoice too" and click "Save", after the page refreshes you are in the delivery step, instead of being presented with a different invoicing address to choose from. 

**To Reproduce**
See attached screen recording

**Screenshots**
https://drive.google.com/open?id=1fZ71XYZMW21rcB0p-GyzjKD-fUMoDAoG

**Wanted behavior**
We should be redirected on address step with no address selected for invoice and continue button disabled

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Thanks for your report.
I manage to reproduce the issue with PS 1.7.4.4 / PS1.7.5.0.
In the checkout steps, when we have more than 1 address, we uncheck the "Use this address for invoice too" option and click "Save" => we are redirected to "Shipping method" step.
It is not the same behavior in the PS1.6,
https://drive.google.com/file/d/1wDlonFQKdKCt2-52jxjKQdFa1oBmIqGy/view
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
Yes, we should be redirected on address step with no address selected for invoice and continue button disabled

**Comment by NeOMakinG** [comment]
Backend issue, one address is selected even if every delivery address has 'Use this address for invoice too' unchecked

/themes/classic/templates/checkout/_partials/address-selector-block.tpl var $selected should be empty and the backend should not consider that one of the address is selected for invoice, it should redirect back to the invoice form instead

**Comment by uruk-hai-21** [comment]
@NeOMakinG 

Same problem in last version (1.7.6.7)
More details here:
https://github.com/PrestaShop/PrestaShop/issues/20209

https://www.youtube.com/watch?v=uiWekKdOn_w

there are plans to solve this problem?

**Comment by NeOMakinG** [comment]
@marionf should this be inside a specific kanban ? I think 1.7.8, otherwise I think this will sleep for a while as backend devs are focusing on release features :/

**Comment by NeOMakinG** [comment]
@ajejebrazorf01 your response is there, you'll get it inside the 1.7.8 release :)

**Comment by uruk-hai-21** [comment]
@NeOMakinG have you a suggest for a workaround?
 Please move to "To do" ;)

**Comment by NeOMakinG** [comment]
@ajejebrazorf01 It should stay on the backlog card for now, but don't worry anyway, releases can't be done until backlog is not empty, it will be picked up by someone working on the release !

I think as It's a backend issue, there are no workaround simple, and I won't suggest to modify core code to do this, but let's wait for a @PrestaShop/prestashop-core-developers response :)

By the way, if you wan't to work on this, don't hesitate to create the PR, that would make it faster to be done and maybe you'll be able to use it on your project !

**Comment by SD1982** [comment]
Hi @matthieu-rolland I still have the same wrong redirection than before when editing the invoice address ...
