### ISSUE TITLE
I have version 1.5.6.2 prestashop and I want version 1.6 please

### ISSUE THREAD

**Issue by glam-strass** [PrestaShop/PrestaShop#11597]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by glam-strass** [comment]
I can't download the version 1.6 in prestashop. Actually I have version 1.5.6.2

**Comment by khouloudbelguith** [comment]
Hi @glam-strass,

Do want to make an upgrade from PS1.5 to PS1.6?
Thanks!

**Comment by glam-strass** [comment]
hello yes

**Comment by glam-strass** [comment]
but 1 click upgrade in prestashop does not work

**Comment by khouloudbelguith** [comment]
@glam-strass,

New versions of PrestaShop come every few months, they all bring a slew of innovations, improvements and bug fixes. It is therefore highly advised to keep up with the latest version.
There are two ways to upgrade PrestaShop:

- Automatic
- Manual

For more information, you can follow this documentation: http://doc.prestashop.com/display/PS15/Updating+PrestaShop
Thanks to upgrade your shop to the last version and feedback.
Thanks!

**Comment by glam-strass** [comment]
do you speak French,?

**Comment by khouloudbelguith** [comment]
@glam-strass yes.

**Comment by glam-strass** [comment]
lorsque je fais la mise à jour j'ai un message java qui s'affiche

**Comment by khouloudbelguith** [comment]
@glam-strass, quelle est la version du module 1-click upgrade tu es entrain de l'utiliser?
Merci!

**Comment by glam-strass** [comment]
erreur javascript (parsejson) détectée

**Comment by glam-strass** [comment]
module 1.6.8

**Comment by khouloudbelguith** [comment]
@glam-strass, could please provide me the exact error that you have.
Thanks!

**Comment by glam-strass** [comment]
erreur javascript  (parseJSON) détectée pour l'action "backupDb". début de restauration...

**Comment by khouloudbelguith** [comment]
ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by khouloudbelguith** [comment]
@glam-strass, This error is a very generic error that simply means it fails. This could be due to many things and parameters.
As this is probably due to allow_url_fopen not activated on your host.
If the display of errors is enabled on your shop, this can cause a problem during the update.
Thanks to check & feedback.

**Comment by Quetzacoalt91** [comment]
Hi @glam-strass,

On this version of the module, you must dig by yourself in the server log to know what happened.
On modules below v3.0.0, the error cannot be displayed on the screen, except if the debug mode is enabled.

**Comment by khouloudbelguith** [comment]
Hi @glam-strass,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
