### ISSUE TITLE
No access to BO after regenerating .htaccess in Multistore

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11590]
**Describe the bug**
My FO and BO became inaccessible (site was down) by the following the below approach:

1. I created an alias (parked domain) in Cpanel and called it test.maindomain.com (as if it were a subdomain to the main domain but without creating the subdomain - not sure if that was the correct approach?). 
2. I enabled multistore and created new group and new shop with URL test.maindomain.com
3. Do some stuff in BO in the test shop (it was working fine at this point).
4. Once I finished testing everything, I went back to the multistore page and removed the test URL (I hadn't yet deleted the shop, I just removed the URL).
5. I then turned off friendly URL (which I presume has the effect of regenerating .htaccess file).

Everything crashed after that. I had to restore my shop using a backup because I couldn't fix the problem.

Note that I contacted my hosting provider and they confirmed it was not an issue on their side.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Thanks for your report.
How did you remove the test URL?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

I attached a video record, https://drive.google.com/file/d/190a9mHbuTIdiJEPN9M_Gw47NGx-3X4ba/view
Thanks to check & feedback.

**Comment by nrcjea001** [comment]
Hi

I will send you the error logs shortly. Please see other information below:

Per your video record, it should be a subdomain of the default shop. Though in cpanel I created an alias instead of a subdomain.

To remove the test URL, simply delete the URL from the shop. Once URL is deleted, the shop is still there but no URL assigned to it. I've attached a screenshot here. Then regenerate .htaccess
![image](https://user-images.githubusercontent.com/26452178/49372644-c4ebe280-f714-11e8-960b-9dc942a499a8.png)


a2hosting is the hosting provider. Please see screenshot below for configuration:

![image](https://user-images.githubusercontent.com/26452178/49372436-121b8480-f714-11e8-9b64-7197a4d7efb0.png)

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

As I can see in your first screenshot, the group of the new shop is the default one, not the second group created.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by nrcjea001** [comment]
Hi

Here is the Apache error log. This is all I have.

[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/2640302/error_log.txt)

Thanks

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

In your log file, you have this error `[ERROR] [HTAccess] Failed to open [/home/loopshop/public_html/.htaccess]: Permission denied`.
It is a permission issue on your server, thanks to check it with your host & feedback.
Thanks!

**Comment by nrcjea001** [comment]
Hi 

Please see below response from host:

> This error indicates a permissions issue on the file. If this error is happening again checking the permissions in the cPanel > Filemanager to ensure their valid will correct it.

> Based on the ticket notes it looks like the original file was having redirect loops due to invalid configuration in the .htaccess and this was the cause, but the logs already rotated for that date.

> The new error provided is for a different issue and would also cause the site to not load properly when this is happening as the rewrite rules would not work for the permalinks. This typically happens when a plugin or site updates the file and corrupts it or changes the permissions.

> Regards, Mike

**Comment by nrcjea001** [comment]
If this doesn't help, I will try reproduce the steps again to induce the crash. I just need to backup everything again first.

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001, It will help us if you can attach a screen record.
Your issue, is related to this ticket: #9846?
Thanks!

**Comment by nrcjea001** [comment]
I saw this before and I think it might be related. I removed the URL of test.loopshops.mu from multistore and the FO was still visible, but not the FO of my default domain loopshops.mu.

However, in my case, I couldn't access BO either. Also, I did not disable multistore, instead I removed the test URL and then regenerated htaccess.

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Finally, I manage to reproduce the issue with PS1.7.4.4.
To reproduce the issue, we need to create an order in the second shop. 
https://drive.google.com/file/d/1vjI06Ry63EQcvTEdXdG8bgpMOFXP57Lw/view
Steps to reproduce the issue
1. Enable multistore
2. create a second shop
3. Add an URL to the second shop
4. Create an order from the FO / BO for the second shop
5. Delete the URL / disable friendly URL (not necessary)
6. Go to the Dashboard => NOK

With PS1.7.5.0beta1, I did not manage to reproduce the issue.
https://drive.google.com/file/d/1pS-K17_UR05eClNF4dX4QizkdWGaVPSw/view
In the PS1.7.5, we have made some fixes
https://github.com/PrestaShop/PrestaShop/pull/9450
https://github.com/PrestaShop/PrestaShop/issues/11364

Thanks to check & feedback.

**Comment by nrcjea001** [comment]
Great that you were able to reproduce the issue.

Regarding step 5,  are you saying we do not need to disable friendly URL? Is deleting the URL necessary? or Both?

**Comment by khouloudbelguith** [comment]
@nrcjea001, not necessary for disabling the friendly URL.
After deleting the URL, if you navigate to the Dashboard => error.
Thanks!

**Comment by nrcjea001** [comment]
Ok yes, confirmed error for PS1.7.4.4. 

Many Thanks!

**Comment by khouloudbelguith** [comment]
@nrcjea001, but it is fixed on the PS1.7.5.0, so we can close this issue.
Thanks!

**Comment by nrcjea001** [comment]
It is fixed on PS1.7.5

You may close this issue

**Comment by khouloudbelguith** [comment]
@nrcjea001, Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
