### ISSUE TITLE
Faceted search filter by the attribute doesn't works

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#11609]
**Describe the bug**
Accidentally updated the module Faceted search to the latest version 2.2.1. Now the filter by the attribute Color doesn't works. Filter by prices and features works. See screenshots.

**To Reproduce**
See screenshots.

**Screenshots**
![attributes-color](https://user-images.githubusercontent.com/44600313/49442780-325e4880-f7d3-11e8-99a6-fbdb2422060d.jpg)
![features](https://user-images.githubusercontent.com/44600313/49442811-4ace6300-f7d3-11e8-9cac-aa809f2ebd27.jpg)
![nofilter](https://user-images.githubusercontent.com/44600313/49442813-4efa8080-f7d3-11e8-8f4c-d5b94961cd4b.jpg)
![filterbywhitecolor](https://user-images.githubusercontent.com/44600313/49442819-528e0780-f7d3-11e8-9a1a-96291060a959.jpg)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

Thanks for your report.
I did not manage to reproduce the issue with PS 1.7.4.4 & the ps_factedsearch module v2.2.1.
I attached a video record.
https://drive.google.com/file/d/1hpBQ2IbAO1Qro8WkeXLQfzoxasMPxmT_/view
Thanks to check & feedback.

**Comment by weddingtextile** [comment]
Hi,

There are several products in the database with one color combination (see screenshot). Perhaps in the new version of the module changed the filtering algorithm?
![00762](https://user-images.githubusercontent.com/44600313/49445484-afd98700-f7da-11e8-98c2-5da76d3ad0ff.jpg)

**Comment by khouloudbelguith** [comment]
@weddingtextile, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by weddingtextile** [comment]
1. Clear Cache
2. Debug Mode On
3. Faceted search - Configure - Build attribute index
4. Go To FO and filter by color -> No data
5. JS Console is empty
6. PHP Errors (today without errors)

**Comment by weddingtextile** [comment]
[PHP_errors.log](https://github.com/PrestaShop/PrestaShop/files/2644350/PHP_errors.log)

**Comment by weddingtextile** [comment]
Can you try add product with one color combination (see screenshot above) and test filter?

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

I attached a video record.
https://drive.google.com/file/d/1_dk4WL5Bh9n_d6oxCtRUgR557PFw4387/view
Thanks to check & feedback.

**Comment by weddingtextile** [comment]
Thank you very much for the answer!
But!
I am 99.9999% sure that you have a version of the filter module 2.2.0.
I compared versions 2.2.0 and 2.2.1.
The difference is only in one file ps_facetedsearch.php (query associated with attributes is changing).
I replaced this file from version 2.2.0 and now everything works !!!! Hooray!!!!!

**Comment by khouloudbelguith** [comment]
@weddingtextile,

I tried with PS1.7.5.x & the ps_fecetedsearch 2.2.1 & it is OK
https://drive.google.com/file/d/176ExkLLAYjxMnD4wXAv0PcnJYnlDp3wL/view
I tried with PS1.7.4.4 & it is ok
https://drive.google.com/file/d/1jHcEZ7cAcWJE_ypRqOip0f5megnYDb-Q/view
Thanks!

**Comment by weddingtextile** [comment]
khouloudbelguith,

I believe you!
But I think the query has an error that occurs on my data.
I can give access to my site, if necessary.
Thanks!

**Comment by khouloudbelguith** [comment]
@weddingtextile, it is not necessary to get your access, we must first try to reproduce your issue.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
