### ISSUE TITLE
Disparition de codes EAN

### ISSUE THREAD

**Issue by otg79** [PrestaShop/PrestaShop#11606]
Bonjour,

J'ai tous les jours des codes EAN de produits qui disparaissent de prestashop. J'ai un intégrateur de flux qui s'appelle channable, pour envoyer mes produits vers Amazon. Tous les jours, je dois remettre les codes EAN sur certains produits. Pouvez-vous m'aider pour que cela cesse ?

Merci par avance

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @otg79,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by otg79** [comment]
Bonjour,

l’hôte est 1and1: Serveur : home740573720.1and1-data.host  => Protocole sftp
Prestashop version 1.7.4.4

Hier j’ai réécrit les codes ean de certains produits :

      847  A. chicandstock 1 Product modification Product 156 0x 0 03/12/2018 08:57:41 
      848  A. chicandstock 1 Connexion au back-office depuis 217.128.217.74  0 0x 0 03/12/2018 13:31:24 
      849  A. chicandstock 1 Product modification Product 140 0x 0 03/12/2018 13:32:56 
      850  A. chicandstock 1 Product modification Product 143 0x 0 03/12/2018 13:38:41 
      851  A. chicandstock 1 Product modification Product 210 0x 0 03/12/2018 13:41:46 
      852  A. chicandstock 1 Product modification Product 210 0x 0 03/12/2018 13:44:16 
      853  A. chicandstock 1 Product modification Product 210 0x 0 03/12/2018 13:47:00 
      854  A. chicandstock 1 Product modification Product 211 0x 0 03/12/2018 13:48:25 
      855  A. chicandstock 1 Connexion au back-office depuis 217.128.217.74  0 0x 0 03/12/2018 14:02:33 
      856  A. chicandstock 1 Product modification Product 199 0x 0 03/12/2018 14:05:59 
      857  A. chicandstock 1 Product modification Product 215 0x 0 03/12/2018 14:09:27 
      858  A. chicandstock 1 Product modification Product 215 0x 0 03/12/2018 14:10:15 
      859  A. chicandstock 1 Product modification Product 215 0x 0 03/12/2018 14:10:56 
      860  A. chicandstock 1 Product modification Product 215 0x 0 03/12/2018 14:11:53 
      861  A. chicandstock 1 Product modification Product 214 0x 0 03/12/2018 14:14:07 
      862  A. chicandstock 1 Connexion au back-office depuis 217.128.217.74  0 0x 0 03/12/2018 14:33:01 
      863  A. chicandstock 1 Product modification Product 182 0x 0 03/12/2018 14:38:35 
      864  A. chicandstock 1 Product modification Product 199 0x 0 03/12/2018 14:45:19 

Sur le produit 210 par exemple, j’ai écrit le codes ean hier et ils ont à nouveau disparu. Le stock sort à 0 alors qu’il y a des déclinaisons remplies !








 Symfony Profiler
 Search
http://boutique.chicandstock.fr/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance?_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs
  Method  GET  HTTP Status  200  IP  217.128.217.74  Profiled on  Tue, 04 Dec 2018 10:14:42 +0000  Token  68525eLast 10 Latest  Search
  a.. Request / Response
   
  b.. Performance
   
  c.. Validator
   
  d.. Forms
   
  e.. Exception
   
  f.. Logs7 
  g.. Events
   
  h.. Routing
   
  i.. Cache
   
  j.. Translation7 
  k.. Security
   
  l.. Twig
   
  m.. Doctrine
   
  n.. E-Mails
   
  o.. Debug
   
  p.. Hooks
   
  q.. Guzzle 
  r.. Configuration
Translation Locales
fr-FR
Localedefault
Fallback localesTranslation Metrics
62
Defined messages0
Fallback messages7
Missing messagesTranslation Messages
  a.. Defined 62 a.. Fallback 0 a.. Missing 7These messages are correctly translated into the given locale.

      Locale Domain Times used Message ID Message Preview 
      fr-FR AdminAdvparametersFeature 2 Clear cache Vider le cache 
      fr-FR AdminAdvparametersFeature 4 Memcached via PHP::Memcache Memcached par PHP::Memcache 
      fr-FR AdminAdvparametersNotification 4 (you must install the [a]Memcache PECL extension[/a]) (vous devez installer [a]l'extension Memcache PECL[/a]) 
      fr-FR AdminAdvparametersFeature 4 Memcached via PHP::Memcached Memcached par PHP::Memcached 
      fr-FR AdminAdvparametersNotification 4 (you must install the [a]Memcached PECL extension[/a]) (vous devez installer [a]l'extension Memcached PECL[/a]) 
      fr-FR AdminAdvparametersFeature 4 APC APC 
      fr-FR AdminAdvparametersNotification 4 (you must install the [a]APC PECL extension[/a]) (vous devez installer [a]l'extension APC PECL[/a]) 
      fr-FR AdminAdvparametersFeature 4 Xcache Xcache 
      fr-FR AdminAdvparametersNotification 4 (you must install the [a]Xcache extension[/a]) (vous devez installer [a]l'extension Xcache[/a]) 
      fr-FR AdminNavigationMenu 1 Performance Performances 
      fr-FR AdminGlobal 1 Help Aide 
      fr-FR AdminAdvparametersFeature 1 Smarty Smarty 
      fr-FR AdminAdvparametersFeature 1 Template compilation Compilation des templates 
      fr-FR AdminAdvparametersFeature 1 Cache Cache 
      fr-FR AdminAdvparametersFeature 1 Should be enabled except for debugging. Devrait être activé sauf pour les tests et debug. 
      fr-FR AdminGlobal 12 No Non 
      fr-FR AdminGlobal 12 Yes Oui 
      fr-FR AdminAdvparametersFeature 1 Multi-front optimizations Synchronisation multi-serveurs 
      fr-FR AdminAdvparametersHelp 1 Should be enabled if you want to avoid to store the smarty cache on NFS. À activer si vous voulez éviter de stocker le cache smarty sur NFS. 
      fr-FR AdminAdvparametersFeature 1 Caching type Type de mise en cache 
      fr-FR AdminActions 6 Save Enregistrer 
      fr-FR AdminAdvparametersFeature 2 Debug mode Mode debug 
      fr-FR AdminAdvparametersFeature 1 Disable non PrestaShop modules Désactiver les modules non développés par PrestaShop 
      fr-FR AdminAdvparametersFeature 1 Enable or disable non PrestaShop Modules. Activer ou désactiver les modules non développés par PrestaShop. 
      fr-FR AdminAdvparametersFeature 1 Disable all overrides Désactiver toutes les surcharges 
      fr-FR AdminAdvparametersFeature 1 Enable or disable all classes and controllers overrides. Activer ou désactiver toutes les surcharges des classes et des contrôleurs. 
      fr-FR AdminAdvparametersHelp 1 Enable or disable debug mode. Activer ou désactiver le mode de débogage. 
      fr-FR AdminAdvparametersFeature 1 Optional features Fonctionnalités désactivables 
      fr-FR AdminAdvparametersHelp 1 Some features can be disabled in order to improve performance. Plusieurs fonctionnalités peuvent être désactivées afin d'optimiser les performances. 
      fr-FR AdminGlobal 1 Combinations Déclinaisons 
      fr-FR AdminAdvparametersHelp 1 Choose "No" to disable Product Combinations. Choisissez "Non" pour désactiver les déclinaisons de produits. 
      fr-FR AdminAdvparametersHelp 1 You cannot set this parameter to No when combinations are already used by some of your products Vous ne pouvez pas définir ce paramètre à "Non" si certains de vos produits utilisent déjà des déclinaisons. 
      fr-FR AdminGlobal 1 Features Caractéristiques 
      fr-FR AdminAdvparametersHelp 1 Choose "No" to disable Product Features. Choisissez "Non" pour désactiver les caractéristiques de produits. 
      fr-FR AdminAdvparametersFeature 1 Customer groups Groupes de clients 
      fr-FR AdminAdvparametersHelp 1 Choose "No" to disable Customer Groups. Choisissez "Non" pour désactiver les groupes de clients. 
      fr-FR AdminAdvparametersFeature 1 CCC (Combine, Compress and Cache) CCC (Concaténation, Compression et mise en Cache) 
      fr-FR AdminAdvparametersHelp 1 CCC allows you to reduce the loading time of your page. With these settings you will gain performance without even touching the code of your theme. Make sure, however, that your theme is compatible with PrestaShop 1.4+. Otherwise, CCC will cause problems. CCC vous permet de réduire le temps de chargement de vos pages en Front Office. Avec ces fonctionnalités, vous allez gagner en performances sans modifier le code source de votre Front Office. Soyez sûr que votre thème est compatible avec PrestaShop 1.4+. Dans le cas contraire, CCC peut causer des problèmes. 
      fr-FR AdminAdvparametersFeature 1 Smart cache for CSS "Smart cache" pour les feuilles de style 
      fr-FR AdminAdvparametersFeature 1 Smart cache for JavaScript "Smart cache" pour le code JavaScript 
      fr-FR AdminAdvparametersFeature 1 Apache optimization Optimisation Apache 
      fr-FR AdminAdvparametersHelp 1 This will add directives to your .htaccess file, which should improve caching and compression. En cochant cette case, votre fichier .htaccess sera complété automatiquement avec des directives améliorant le cache et la compression. 
      fr-FR AdminAdvparametersFeature 1 Media servers (use only with CCC) Serveurs de média (utilisé uniquement lorsque CCC est activé) 
      fr-FR AdminAdvparametersFeature 1 You must enter another domain, or subdomain, in order to use cookieless static content. Vous devez mettre un autre domaine ou sous-domaine, afin d'utiliser du contenu statique sans cookie. 
      fr-FR AdminAdvparametersFeature 1 Media server #1 Serveur de média n°1 
      fr-FR AdminAdvparametersHelp 1 Name of the second domain of your shop, (e.g. myshop-media-server-1.com). If you do not have another domain, leave this field blank. Nom du deuxième domaine de votre boutique, (par exemple, myshop-media-server-1.com). Si vous n'avez pas un autre domaine, laisser ce champ vide 
      fr-FR AdminAdvparametersFeature 1 Media server #2 Serveur de média n°2 
      fr-FR AdminAdvparametersHelp 1 Name of the third domain of your shop, (e.g. myshop-media-server-2.com). If you do not have another domain, leave this field blank. Nom du troisième domaine de votre boutique, (par exemple, myshop-media-server-1.com). Si vous n'avez pas un autre domaine, laisser ce champ vide 
      fr-FR AdminAdvparametersFeature 1 Media server #3 Serveur de média n°3 
      fr-FR AdminAdvparametersHelp 1 Name of the fourth domain of your shop, (e.g. myshop-media-server-3.com). If you do not have another domain, leave this field blank. Nom du quatrième domaine de votre boutique, (par exemple, myshop-media-server-1.com). Si vous n'avez pas un autre domaine, laissez ce champ vide 
      fr-FR AdminAdvparametersFeature 1 Caching Cache 
      fr-FR AdminAdvparametersFeature 1 Use cache Utiliser le cache 
      fr-FR AdminAdvparametersFeature 1 Caching system Système de cache 
      fr-FR AdminAdvparametersFeature 1 Add server Ajouter un serveur 
      fr-FR AdminAdvparametersFeature 1 IP Address Adresse IP 
      fr-FR AdminAdvparametersFeature 2 Port Port 
      fr-FR AdminAdvparametersFeature 2 Weight Poids 
      fr-FR AdminAdvparametersFeature 1 Add Server Ajouter un serveur 
      fr-FR AdminAdvparametersFeature 1 Test Server Tester le serveur 
      fr-FR AdminGlobal 1 ID ID 
      fr-FR messages 1 IP address Adresse IP 
      fr-FR AdminGlobal 1 Loading... 

Log Messages
  a.. Info. & Errors 8 a.. Deprecations 0 a.. Debug 181 a.. PHP Notices 0 a.. Container 765Informational and error log messages generated during the execution of the application.

      Level Channel Message 
      INFO
      10:14:36 request Matched route "admin_performance". 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 
      WARNING
      10:14:42 translation Translation not found. 
      Show context 


PerformanceController :: indexAction
  a.. Request a.. Response a.. Cookies a.. Session a.. FlashesGET Parameters
      Key Value 
      _token "7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 

POST Parameters
No POST parameters

Request Attributes
      Key Value 
      _controller "PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\PerformanceController::indexAction" 
      _firewall_context "security.firewall.map.context.main" 
      _legacy_controller "AdminPerformance" 
      _route "admin_performance" 
      _route_params [▶] 
      _security [▶] 
      _template Template {#2421 ▶} 
      controller_name "PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\PerformanceController" 
      controller_type 2 

Request Headers
      Header Value 
      accept "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" 
      accept-encoding "gzip, deflate" 
      accept-language "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7" 
      cache-control "max-age=0" 
      cookie "PrestaShop-acf879f8b8457357ff01233d8a6b7384=def50200ae11950416f23343bf1785c907ba329ab409c203dc15f1ec0f904e4c42a1392784a001396c938792320502a0ebb11488a61a7cf59de795f08b36d2a98ffb913b03d886fd00d74600325775ca06529066c7d0cc038d2aad9deae2008f8a5a45f073f556de902caaf281a1d828fa63c9aab830f8ab868e044cac7ff8c12020e46da7ffb7ca8e93f8a76afc4ed8f836030f0186e4e48a43f894f254b5a43c3d42945af04f6b385d6fd701472ad8fb72924fab8059a6d61d5429f50501; PrestaShop-6a2bf2d35bd668e7b7c63d107ac41f9d=def50200010948eb6458726986997d781ddbd383c21a9da7428ac32824be2f3e7034723f986d5c0c097b4e9dd72c32dbe8fda3815b6fc0ed161852b6c153bb5903779c164b97a98da5700b802b9028a3d16c570389d7109c9344f3450f72b0cbece875c847b8a143279bf5481ac31ce8dbdb3e6628538749ab65908bc5b0cc0a67403cb18d8565dd874e51658963303271adaef0fd4e3767d7095a9d81ece65ba9390f2ab4fcc506310f684151998531fa05faa64f4c9b00f8b3c93b66b7073f58f690398d8b529a63f74a6dccc6d9f9c25787c6be04b3b4b289577046dd1ecf08913585c1c50064d623089e953822156914444a1aba40a0b5b423ee0a7f1967e01f6343436bd654c5ee68965ecfb4a32233b34d5a5c4e456d0f7a943df30fb399b562b9a50560fd060b77a83f10e80a39dc7cc99e980ccf9ed900abd2c87acd335655ca280ca437ebedc4d0898408089fcac16ef8dbf18ad9df6d05fb5ea17853c849; PHPSESSID=f051f7dd5c5bc74281edaa6a8537cb83; PrestaShop-8df430953e93d77b0661b910ab7c8c54=def50200476ddf72b65e56b31b0d068f8d10a2789a54cbd188c2328bb841e251207518284adf826f9bb0c046d8691303838c94ac7f425dc7366df725527a945a3ae8cf937ab25852417286704b432d73d37ce286d86eaffb0fae09a44d77cfc6335ee453a5fe12215b266f04feeb634f2985ebd88859624c4d6ded4d0f2b13048a1e3acd24decee65bcc20f123849ae347355372e32c8eb8d9ac6dab651bb9c413e89e7a9a0f1900775f044fa90c25697b534ef2fe7a63a8eb88eb33473d2fac858048236eb8615941609d5d5162cdb053d615e7f9dd04bd1093750011a3e9652ab2640161f2bab06a5c791d13e8d38a1f538f55b58ac3b52a390411acd1d1016ea2f397c9eeda2d22dd2c28eb421db5a815c71345b2afb938d3fd50801807b87de72db021536f7b9f8e290773cea4a901b9e261eae18e0bb971087b4dfbefeb74845b752cf58070c5cfb256a6441bd7837a3e58a9e1160d1cb93ddddda4ffbdbbeafbec3fbbcb06dbb669f17228c2914680dd76e9ae0feca1bb56437f87b7dc8f81cfdb1390137244a83459dc652a99c01dcbcb5018b7d0859be2324113543d9e84239798abeb30" 
      host "boutique.chicandstock.fr" 
      referer "http://boutique.chicandstock.fr/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance?_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 
      upgrade-insecure-requests "1" 
      user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" 
      x-php-ob-level 0 

Request Content
Request content not available (it was retrieved as a resource).

Server Parameters
      Key Value 
      CONTEXT_DOCUMENT_ROOT "/kunden/usr/lib/cgi-bin/" 
      CONTEXT_PREFIX "/system-bin/" 
      DOCUMENT_ROOT "/kunden/homepages/31/d740573720/htdocs/clickandbuilds/PrestaShop/MyeCommerce" 
      GATEWAY_INTERFACE "CGI/1.1" 
      HTTP_ACCEPT "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" 
      HTTP_ACCEPT_ENCODING "gzip, deflate" 
      HTTP_ACCEPT_LANGUAGE "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7" 
      HTTP_CACHE_CONTROL "max-age=0" 
      HTTP_COOKIE "PrestaShop-acf879f8b8457357ff01233d8a6b7384=def50200ae11950416f23343bf1785c907ba329ab409c203dc15f1ec0f904e4c42a1392784a001396c938792320502a0ebb11488a61a7cf59de795f08b36d2a98ffb913b03d886fd00d74600325775ca06529066c7d0cc038d2aad9deae2008f8a5a45f073f556de902caaf281a1d828fa63c9aab830f8ab868e044cac7ff8c12020e46da7ffb7ca8e93f8a76afc4ed8f836030f0186e4e48a43f894f254b5a43c3d42945af04f6b385d6fd701472ad8fb72924fab8059a6d61d5429f50501; PrestaShop-6a2bf2d35bd668e7b7c63d107ac41f9d=def50200010948eb6458726986997d781ddbd383c21a9da7428ac32824be2f3e7034723f986d5c0c097b4e9dd72c32dbe8fda3815b6fc0ed161852b6c153bb5903779c164b97a98da5700b802b9028a3d16c570389d7109c9344f3450f72b0cbece875c847b8a143279bf5481ac31ce8dbdb3e6628538749ab65908bc5b0cc0a67403cb18d8565dd874e51658963303271adaef0fd4e3767d7095a9d81ece65ba9390f2ab4fcc506310f684151998531fa05faa64f4c9b00f8b3c93b66b7073f58f690398d8b529a63f74a6dccc6d9f9c25787c6be04b3b4b289577046dd1ecf08913585c1c50064d623089e953822156914444a1aba40a0b5b423ee0a7f1967e01f6343436bd654c5ee68965ecfb4a32233b34d5a5c4e456d0f7a943df30fb399b562b9a50560fd060b77a83f10e80a39dc7cc99e980ccf9ed900abd2c87acd335655ca280ca437ebedc4d0898408089fcac16ef8dbf18ad9df6d05fb5ea17853c849; PHPSESSID=f051f7dd5c5bc74281edaa6a8537cb83; PrestaShop-8df430953e93d77b0661b910ab7c8c54=def50200476ddf72b65e56b31b0d068f8d10a2789a54cbd188c2328bb841e251207518284adf826f9bb0c046d8691303838c94ac7f425dc7366df725527a945a3ae8cf937ab25852417286704b432d73d37ce286d86eaffb0fae09a44d77cfc6335ee453a5fe12215b266f04feeb634f2985ebd88859624c4d6ded4d0f2b13048a1e3acd24decee65bcc20f123849ae347355372e32c8eb8d9ac6dab651bb9c413e89e7a9a0f1900775f044fa90c25697b534ef2fe7a63a8eb88eb33473d2fac858048236eb8615941609d5d5162cdb053d615e7f9dd04bd1093750011a3e9652ab2640161f2bab06a5c791d13e8d38a1f538f55b58ac3b52a390411acd1d1016ea2f397c9eeda2d22dd2c28eb421db5a815c71345b2afb938d3fd50801807b87de72db021536f7b9f8e290773cea4a901b9e261eae18e0bb971087b4dfbefeb74845b752cf58070c5cfb256a6441bd7837a3e58a9e1160d1cb93ddddda4ffbdbbeafbec3fbbcb06dbb669f17228c2914680dd76e9ae0feca1bb56437f87b7dc8f81cfdb1390137244a83459dc652a99c01dcbcb5018b7d0859be2324113543d9e84239798abeb30" 
      HTTP_HOST "boutique.chicandstock.fr" 
      HTTP_REFERER "http://boutique.chicandstock.fr/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance?_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 
      HTTP_UPGRADE_INSECURE_REQUESTS "1" 
      HTTP_USER_AGENT "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" 
      ORIG_PATH_INFO "/configure/advanced/performance" 
      ORIG_PATH_TRANSLATED "/kunden/homepages/31/d740573720/htdocs/clickandbuilds/PrestaShop/MyeCommerce/xyu8ekcfwqh9soxi/index.php" 
      PATH "/bin:/usr/bin" 
      PHP_SELF "/xyu8ekcfwqh9soxi/index.php" 
      QUERY_STRING "_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 
      REDIRECT_BASE "/xyu8ekcfwqh9soxi" 
      REDIRECT_DOCUMENT_ROOT "/kunden/homepages/31/d740573720/htdocs/clickandbuilds/PrestaShop/MyeCommerce" 
      REDIRECT_HANDLER "x-mapp-php5.5" 
      REDIRECT_HTTP_MOD_REWRITE "On" 
      REDIRECT_QUERY_STRING "_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 
      REDIRECT_SCRIPT_URI "http://boutique.chicandstock.fr/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance" 
      REDIRECT_SCRIPT_URL "/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance" 
      REDIRECT_STATUS "200" 
      REDIRECT_UNIQUE_ID "XAZTetmgPhUAAJqwmMcAAAAZ" 
      REDIRECT_URL "/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance" 
      REMOTE_ADDR "217.128.217.74" 
      REMOTE_PORT "11556" 
      REQUEST_METHOD "GET" 
      REQUEST_SCHEME "http" 
      REQUEST_TIME 1543918458 
      REQUEST_TIME_FLOAT 1543918458.2367 
      REQUEST_URI "/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance?_token=7RDTjRajrH9yYNDfpNxGclNcHyiwFrPCClKSaAT6FSs" 
      SCRIPT_FILENAME "/kunden/homepages/31/d740573720/htdocs/clickandbuilds/PrestaShop/MyeCommerce/xyu8ekcfwqh9soxi/index.php" 
      SCRIPT_NAME "/xyu8ekcfwqh9soxi/index.php" 
      SCRIPT_URI "http://boutique.chicandstock.fr/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance" 
      SCRIPT_URL "/xyu8ekcfwqh9soxi/index.php/configure/advanced/performance" 
      SERVER_ADDR "217.160.62.21" 
      SERVER_ADMIN "webmaster@boutique.chicandstock.fr" 
      SERVER_NAME "boutique.chicandstock.fr" 
      SERVER_PORT "80" 
      SERVER_PROTOCOL "HTTP/1.1" 
      SERVER_SIGNATURE "" 
      SERVER_SOFTWARE "Apache" 
      STATUS "200" 
      UNIQUE_ID "XAZTetmgPhUAAJqwmMcAAAAZ" 
      argc 1 

debug_mode ("PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\DebugModeType")
Default DataProperty Value 
      Model Format same as normalized format 
      Normalized Format [▶] 
      View Format same as normalized format 

Submitted DataThis form was not submitted.

Passed OptionsNo options where passed when constructing this form.

Resolved OptionsView Variables

**Comment by otg79** [comment]
Translation Messages
  a.. Defined 62 a.. Fallback 0 a.. Missing 7These messages are not available for the given locale and cannot be found in the fallback locales. Add them to the translation catalogue to avoid Symfony outputting untranslated contents.

      Locale Domain Times used Message ID Message Preview 
      fr-FR AdminAdvparametersFeature 1 Never recompile template files Never recompile template files 
      fr-FR AdminAdvparametersFeature 1 Recompile templates if the files have been updated Recompile templates if the files have been updated 
      fr-FR AdminAdvparametersFeature 1 Force compilation Force compilation 
      fr-FR AdminAdvparametersFeature 1 File System File System 
      fr-FR AdminAdvparametersFeature 1 MySQL MySQL 
      fr-FR AdminAdvparametersFeature 1 Never clear cache files Never clear cache files 
      fr-FR AdminAdvparametersFeature 1 Clear cache everytime something has been modified Clear cache everytime something has been modified

**Comment by khouloudbelguith** [comment]
@otg79, thanks for your feedback.
We need the PHP error logs also. If you don't have it, you should ask your hosting provider.

**Comment by otg79** [comment]
Bonjour,

J’ai demandé à 1 and 1 et je n’ai pas de fichier qui correspond à cela selon eux.

Désolé

**Comment by otg79** [comment]
NIVEAU DE GRAVITÉSignification des niveaux de gravité :

  1.. À but informatif 
  2.. Attention 
  3.. Erreur 
  4.. Problème majeur (erreur critique)LOGS > FILTRER PAR GRAVITÉ (1-4) : 4 0
      ID   Employé   Gravité (1-4)   Message   Type de l'objet   ID de l'objet   Code d'erreur   Date    
             Rechercher  Réinitialiser 
      Aucun enregistrement trouvé

**Comment by otg79** [comment]
Je n’ai pas d’erreur niveau 4 ni niveau 3

Filtrer par Gravité (1-4) : 3a.. Modules recommandésa.. Aide
 NIVEAU DE GRAVITÉSignification des niveaux de gravité :

  1.. À but informatif 
  2.. Attention 
  3.. Erreur 
  4.. Problème majeur (erreur critique)LOGS > FILTRER PAR GRAVITÉ (1-4) : 3 0
      ID   Employé   Gravité (1-4)   Message   Type de l'objet   ID de l'objet   Code d'erreur   Date    
             Rechercher  Réinitialiser 
      Aucun enregistrement trouvé

**Comment by otg79** [comment]
pas de niveau 2 non plus


 NIVEAU DE GRAVITÉSignification des niveaux de gravité :

  1.. À but informatif 
  2.. Attention 
  3.. Erreur 
  4.. Problème majeur (erreur critique)LOGS > FILTRER PAR GRAVITÉ (1-4) : 2 0
      ID   Employé   Gravité (1-4)   Message   Type de l'objet   ID de l'objet   Code d'erreur   Date    
             Rechercher  Réinitialiser 
      Aucun enregistrement trouvé

**Comment by khouloudbelguith** [comment]
@otg79, how did you update all the EAN of your products, manually or by importing a file or a custom module?
What are the type of such products, Standard product, with combinations..?
Thanks!

**Comment by otg79** [comment]
J’ai créer les codes ean manuellement et les produits sont des chaussures avec déclinaisons.

Merci

**Comment by khouloudbelguith** [comment]
@otg79, after clicking "Save", a green alert is displayed?
If yes, if you reload the product page, the EAN exists or disappear?
Thanks!

**Comment by otg79** [comment]
Oui j’ai bien une alerte verte qui dit “enregistré”. Les codes EAN disparaissent la nuit à priori mais pas quand je rafraichi la page...

Merci

**Comment by khouloudbelguith** [comment]
@otg79, it could be due to a custom module?
Do you have any module related to the product/product EAN?
Thanks!

**Comment by otg79** [comment]
Bonjour,

Non aucun module personnalisé pour les codes EAN. Mais je fais des recherches par rapport à mon logiciel de stock aussi.

Merci

**Comment by khouloudbelguith** [comment]
Hi @otg79,

OK, Thanks to check & feedback.
Waiting for your feedback!

**Comment by otg79** [comment]
Thank you !

**Comment by luisjsolsona** [comment]
I have a similar issue...
the problem was solved checking all the EAN and UPC in combination products
PS1.7 check if EAN or UPC is correct (13 digits for ean)
check ps_product_attribute table 
If you need to use a private EAN with a personal configuration, add a column and use this in ps_product_attribute
Regards

**Comment by otg79** [comment]
Merci pour votre réponse, mais mes codes EAN font bien 13 chiffres et sont ceux du fabricant. Je n’en crée pas moi-même.

**Comment by khouloudbelguith** [comment]
Hi @otg79,

Any news about the search of your stock app?
Thanks!

**Comment by otg79** [comment]
Non, pas de certitudes...Le problème est en cours d‘étude chez mon logiciel de stock. Je pense que cela vient de lui.

Merci

**Comment by khouloudbelguith** [comment]
@otg79, ok, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @otg79,

Any news about your issue?
Thanks!

**Comment by otg79** [comment]
Bonjour,

A priori oui et cela semblait venir de mon logiciel de stocks.

Merci

Arnaud

**Comment by khouloudbelguith** [comment]
Hi @otg79,

Thanks for your feedback.
Since your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Comment by otg79** [comment]
thank you !
