### ISSUE TITLE
Unable to view payment module in FO multistore

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11602]
I installed the payment module BlueSnap and configured it as instructed. Its working fine on my default shop but not on my other shops in multistore. When I activate my other shop the module appears in BO but not in FO (see screenshots below). I configured it exactly as the default shop (as instructed). I've checked payment controller (payment method and preferences) and also international controller (localization, location) but no notable differences. I tried clearing cache, nothing.

I have contacted BlueSnap and they are looking into it. Please also confirm on your side if theres any issue with Prestashop.

Thanks

![image](https://user-images.githubusercontent.com/26452178/49418606-80a42500-f79c-11e8-8f9d-fb1c35b92ff5.png)
![unnamed](https://user-images.githubusercontent.com/26452178/49418618-9580b880-f79c-11e8-8f65-5ac3b7260e01.png)

**Additional information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

I did not manage to reproduce the issue with PS1.7.4.4 / PS1.7.5.0beta1.
I attached a video record.
https://drive.google.com/file/d/1rfnqihFU_8dip3ty9QtduNIT5qAK-ZXw/view
In the BO => Modules & Services, Installed Tab, when the second shop is selected, could you please try to reset your payment module.
![image](https://user-images.githubusercontent.com/16067358/49427441-9c5ef980-f7a3-11e8-8b04-845c621469d7.png)
Thanks to check & feedback.

**Comment by nrcjea001** [comment]
I reset the module as you suggested and it did help. However, now I only see one payment method available for the new store. For the default store, I have 2 payment methods from which to choose.

**Comment by khouloudbelguith** [comment]
@nrcjea001, for the second payment method, you need also to reset it also.
Thanks to check & feedback.

**Comment by nrcjea001** [comment]
Yes thanks. that worked

**Comment by nrcjea001** [comment]
you may close this issue now

**Comment by khouloudbelguith** [comment]
@nrcjea001, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
