### ISSUE TITLE
Use composer to install/upgrade/uninstall modules

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#11619]
As discussed in #11594:

We realized that requiring a module via composer merges said module's dependencies into the core's `vendor` folder, instead of placing them in the module's `vendor` directory. This raises several issues:

1. Modules using composer are currently distributed with their own dependencies in the zip package, so they expect to have their dependencies inside the module's directory and use their own autoloader. This was detected by Travis.
2. Upgrade. If the dependencies are included in the core, upgrading the module will make the module crash because of duplicate dependencies. Removing the module would potentially leave orphan dependencies behind, too.

We need to find a way to bring these two systems together. If we choose to distribute all modules using composer, we need to change the whole system. If not, we need to drop composer for native modules.

**Comment by eternoendless** [comment]
As discussed, we can't change the way we install community modules right now, it should be done in the next major version.

For 1.7, I suggest creating a composer extension so that dependencies of modules installed using composer are not merged with the core's.

**Comment by matks** [comment]
Here are questions about the work to be done for 1.7 :
- if we install modules A and B both using Composer, which both use the same library such as https://github.com/moneyphp/money : should the dependency be installed in both `vendor` folders for modules A and B (=> duplication)
 - if we install modules A and B both using Composer, which both use a library *used by PrestaShop core* such as Swiftmailer: I guess this one stays in root `vendor` folder

**Comment by PierreRambaud** [comment]
If dependencies are not merged, what behavior should have:
* Install module A with Guzzle 6.3
* Install module B with Guzzle 5.3
* Core use Guzzle 5.3

1) Install everything in vendor and say module A is not compatible
2) Install in module's vendor and everything should work
3) Install Guzzle 6.3 in module vendor, and module B use Core dependency? (reduce space usage)

**Comment by eternoendless** [comment]
Remember, in 1.7 we aren't doing anything fancy, just _keeping it working the way it has until now_.

Currently, when a module is installed via the Back Office, it includes its own `vendor` directory. We should simply try using a [Custom installer](https://getcomposer.org/doc/articles/custom-installers.md) to make it behave the same way when importing modules using composer.

It's not about how it _should_ behave (we'll see about that in v8), but in keeping it consistent. I did some tests to see how it behaves.

First, let's take @PierreRambaud's example:

> - Install module A with Guzzle 6.3
> - Install module B with Guzzle 5.3
> - Core use Guzzle 5.3

Now let's make it more interesting so that we have three versions of Guzzle:

- Module A with Guzzle 7.3
- Module B with Guzzle 6.3
- Core uses Guzzle 5.3

What happens depends on several factors, including:

- If the library is imported by the core or not
- If each module's autoloader has been built using `--prepend-autoloader=false` (the recommended way) or not
- Which pice of the code uses it first

In general, if the core imports the library and if all module autoloaders have been built properly, then the core wins because its autoloader will be used first. ➡️ v5.3

If any module autoloader (say, module B) is built with `--prepend-autoloader=true`, then it starts getting interesting:
- If the core uses Guzzle first
  ➡️ v5.3
- If Module A uses Guzzle first
  ➡️ v7.3
- If Module B uses it first, **or if it's loaded before any of the two others use it**
  ➡️ v6.3

In any case, keep in mind that autoloading is performed on a class-by-class basis, and at the time of first use. This may lead to classes from two different versions being loaded in some cases 😅 .

**Comment by matks** [comment]
@eternoendless I guess you expect Guzzle 5.3 to be installed in `vendor/guzzle`, Guzzle 7.3 to be installed in `modules/module_a/vendor/guzzle` and Guzzle 6.3 to be installed in `modules/module_b/vendor/guzzle` then ?

**Comment by eternoendless** [comment]
That's right

**Comment by PierreRambaud** [comment]
Not sure it's possible to do something like that with PHP :disappointed:

**Comment by eternoendless** [comment]
> Not sure it's possible to do something like that with PHP

What do you mean? I know we can't have the three libraries _available_ at the same time, but that's not what I expect; I only described how it behaves with zip-installed modules.

I just want the behavior of composer-installed modules to be consistent with zip-installed modules, that's all.

**Comment by PierreRambaud** [comment]
Thinking you expected this behavior :P

**Comment by mickaelandrieu** [comment]
Hi,

after discussions with @eternoendless, this is what we have decided.

We won't use anymore Composer to manage native modules _directly_, this means we will remove all ```prestashop/ps_whatever``` from the `require` section, **because** it's not possible to avoid installation of **modules requirements** into the ``vendor`` folder of PrestaShop.

But we still want to use Composer to manage all our dependencies and list the required native modules... so this is what we will do instead:

* Using `extra` section of Composer, we will list all our native modules;
* We will create a Composer extension able to loop into this list and install the modules at the right place (basically this will do something like `cd modules && composer create-project prestashop/ps_whatever`);
* This way, the ``vendor`` folder of PrestaShop will never be impacted by the native (or even community) modules => _this is the problem we want to solve_;
* We will celebrate and @eternoendless have promised to me alcohol and a lot of money 🤣;

Mickaël

**Comment by jolelievre** [comment]
nice priorities!

**Comment by mickaelandrieu** [comment]
I've updated/completed again my comment, if you have any questions: feel free to ask!

**Comment by jolelievre** [comment]
I know it's not definitive I think `composer install-module` would be more appropriate
And I was wondering what exactly will this command do?
- download the module from addons with vendors embedded? then weed ids for the platform?
- clone the project from github and perform `composer install` inside its folder?

**Comment by Quetzacoalt91** [comment]
They could be downloaded from `packagist`, as they already exist on this platform (https://packagist.org/?query=prestashop).

**Comment by mickaelandrieu** [comment]
> I know it's not definitive I think composer install-module would be more appropriate

What do you expect this script to do?

> And I was wondering what exactly will this command do?

:D you can't suggest to use a command and at the same time ask what should do this command ahahah!

> download the module from addons with vendors embedded? then weed ids for the platform?
clone the project from github and perform composer install inside its folder?

We will rely on packagist like before, the command "composer create-project" means ~= "git clone + composer install", there is no plan to rely on Addons API to retrieve the ZIP files.

**Comment by jolelievre** [comment]
Is there an easy way to target a package at a specific version?
And what kind of version matching should we manage? only strict version like `2.1.4`? or like in composer `~2.1`?
what about compatibility with prestashop version?

**Comment by jolelievre** [comment]
@mickaelandrieu my bad I didn't know this composer action (I should have searched for it)
should we integrate prestashop compatible versions in the modules' composer.json then? or is it our responsibility to assure we set the appropriate versions in the core composer.json (in the extra section)?

**Comment by mickaelandrieu** [comment]
> or is it our responsibility to assure we set the appropriate versions in the core composer.json (in the extra section)?

Yes, we don't change anything: we just move the information from `require` to `extra -> 'to-be-announced'` section.
