### ISSUE TITLE
PS 1.7.4.2 BO unable to delete customer

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#11617]
**Describe the bug**
Unable to delete customer, no wrning message

**To Reproduce**
1 go to customer
2 select one customer
3 hit "delete"
4 page refresh, no warning, customer still in the customer list.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
Informazioni sul server Linux #1 SMP PREEMPT Tue Aug 28 15:11:59 CEST 2018 x86_64

Versione software del server: Apache

Versione di PHP: 5.6.30

Limite di memoria: 128M

Tempo di esecuzione massimo: 180

Dimensione Max. dei file da caricare: 128M

Versione MySQL: 5.5.58-38.10-log

Server MySQL: localhost

Nome MySQL: 

Utente MySQL: 

Prefisso delle tabelle: ps_

Motore MySQL: InnoDB

Driver MySQL: DbPDO

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Did you use which option during the delete of the customer?
![image](https://user-images.githubusercontent.com/16067358/49508224-76f4ed00-f882-11e8-80af-fb59c7632b5a.png)
Thanks!

**Comment by matteolavaggi** [comment]
No, no message or aller was shown

**Comment by khouloudbelguith** [comment]
@matteolavaggi, I did not manage to reproduce the issue with PS1.7.4.4
I attached a video record.
https://drive.google.com/file/d/15ci5KGh8yPhJqsnikemo25SeWq60rzu8/view
Thanks to check & feedback.

**Comment by matteolavaggi** [comment]
Dear, i'm a bit confuse ^^ the new goal of PS issue solve is to have 1 single installation working and attacching video to every issue report of that single one installed? i also can attach a video of the issue ^^

**Comment by khouloudbelguith** [comment]
@matteolavaggi, in your last comment, you mentioned to me that you don't have any alerts during the deletion of customers.
In fresh installed 1.7.4, when we delete a customer, we have a pop up to validate this deletion and we have two choices to delete this customer, I make a video record to confirm with you the issue.
If you enable the debug mode, are there any exceptions displayed?
Thanks!

**Comment by matteolavaggi** [comment]
i'll delete it in DB

**Comment by khouloudbelguith** [comment]
@matteolavaggi, ok.
But, you need to make a backup to be safe.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
