### ISSUE TITLE
Prestashop 1.7.4.4, Putenv function one more time

### ISSUE THREAD

**Issue by matesbu** [PrestaShop/PrestaShop#11616]
here is my problem again, because it was closed without any solution:

Hi,
after upgrading to version 1.7.4.4 I can't get to back office login page because of error 500. I turned on debug mode and it says the problem is with disabled function putenv. I googled it and there is one same case on forge.prestashop.com: http://forge.prestashop.com/browse/BOOM-6194 , but it was solved with provider. My provider isn't able to solve it because of security reasons, but they told me I can figure it out by editing .htaccess file or stoping the putenv script.

Any ideas how?

contributor khouloudbelguith answerd me this and closed the ticket:

Some server disables putenv because of security reason.
Your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
We can't do anything with this.
You should contact your host provider, they are the only ones to help you with it.
Thanks!

But she totally ignored my question (no offence) - I know that there is problem with my provider and I wrote it at my first message, I am asking about solving my problem thru htaccess or some other way...  I don't unerstand, why new prestashop (1.7.4.4) needs this function while old version (1.7.2) didn't...

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Thanks for your report.
Could you please provide me the exact last version PrestaShop did you use before the upgrade? is it 1.7.2.4? or 1.7.2.5?
Also, could you please try to provide us with your php info.
http://kb.mediatemple.net/questions/764/How+can+I+create+a+phpinfo.php+page%3F#gs
Thanks!

**Comment by matesbu** [comment]
it was 1.7.2.4

here is phpinfo, hopfully it is enough

![php1](https://user-images.githubusercontent.com/45437757/49535117-a2e49280-f8c3-11e8-8b6c-e3bba9811410.jpg)
![php2](https://user-images.githubusercontent.com/45437757/49535118-a2e49280-f8c3-11e8-9e9b-7ddac645f09f.jpg)
![php3](https://user-images.githubusercontent.com/45437757/49535119-a37d2900-f8c3-11e8-950b-fa9e1ba88d22.jpg)
![php4](https://user-images.githubusercontent.com/45437757/49535120-a37d2900-f8c3-11e8-888e-257b00333c98.jpg)

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Thanks for your feedback.
We release the Prestashop 1.7.2.5 for security reasons, 
Security researchers recently reported the Core team of two vulnerabilities affecting the Back Office, one of them critical, for more details you can follow this [link](http://build.prestashop.com/news/prestashop-1-7-2-5-maintenance-release/)
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Thanks for your feedback.
We have updated the Symfony version, this new version used the Putenv function.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Thanks for your feedback.
We have updated the Symfony version, this new version use the Putenv function.
Thanks!

**Comment by mpetricek** [comment]
@matesbu since I have the exact same problem with the same hosting provider (WEDOS I guess). Can you tell me if it's solved with version 1.7.4.4? 

Thank you

**Comment by matesbu** [comment]
My provider is Forpsi, but it is probably same with every webhosting provider, cause this cheap webhostings are usually shared with other hosted sites. And because of security reasons, they can't turn on putenv function. So I probably gonna have to pay for some cloud VPS, where you can set your server settings as you want to.
As I understand it, it will not be solved in any new version, cause they are using new version of Symfony.

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Yes, PrestaShop 1.7 was moved To Symfony 3.4 And PHP 5.6.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matesbu 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
