### ISSUE TITLE
Eshop on the main menue

### ISSUE THREAD

**Issue by marionpelouzet** [PrestaShop/PrestaShop#11611]
Hi,

I bought a template on prestashop for my eshop http://them.fr
When you go on my website http://them.fr, you will see my main menu with
ESHOP -   SUR-MESURE   -     LE CONCEPT     -    CARNET DE VOYAGE ...

When you click on "sur-mesure" or "le concept" or "carnet de voyage", you are drive on their own pages.

But, the issue is with "eshop" : 
- When you pass the computer mousse on "eshop" you can see all the categories appearing. That's perfect.
- When you click on "eshop", you are not drive on an other page, you stay on the home page.

I would like that when you click on eshop, you be drive on my product category "all the products". 
Currently, when you click on eshop, you stay on the home page.

Does someone know how to do that ?

Thank you very much

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionpelouzet,

Thanks for your report.
The category E-shop in your case is the Home category that's why you are redirected to the Home page.
Thanks to check & feedback.

**Comment by marionpelouzet** [comment]
Hi,

Thank you for your reply.
Can I change it ?

Thanks



http://them.fr <http://them.fr/>
https://www.facebook.com/themofficiel/ <https://www.facebook.com/themofficiel/>
https://www.instagram.com/themofficiel/ <https://www.instagram.com/themofficiel/>

**Comment by khouloudbelguith** [comment]
Hi @marionpelouzet,

In the file Project_Folder/themes/your_current_theme/modules/ps_mainmenu/ps_mainmenu.tpl
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/modules/ps_mainmenu/ps_mainmenu.tpl#L8
Thanks to replace this code line:

`
<a
                class="{if $depth >= 0}dropdown-item{/if}{if $depth === 1} dropdown-submenu{/if}"
                href="{$node.url}" data-depth="{$depth}"
                {if $node.open_in_new_window} target="_blank" {/if}
              >
`
by this

`<a
                class="{if $depth >= 0}dropdown-item{/if}{if $depth === 1} dropdown-submenu{/if}"
                {if $node.page_identifier == "category-2"} href="https://them.fr/2-e-shop"{/if} href="{$node.url}" data-depth="{$depth}"
                {if $node.open_in_new_window} target="_blank" {/if}
              >`

But this fix is a temporory fix, because I just edit with your current URL `https://them.fr/2-e-shop`
In other case, it is the behavior by default in Prestashop
Thanks to check & feedback.

**Comment by marionpelouzet** [comment]
Hi,

Thank you very much for your reply !

Best



http://them.fr <http://them.fr/>
https://www.facebook.com/themofficiel/ <https://www.facebook.com/themofficiel/>
https://www.instagram.com/themofficiel/ <https://www.instagram.com/themofficiel/>

**Comment by khouloudbelguith** [comment]
@marionpelouzet, you are welcome!
so can I close the issue?
Thanks!

**Comment by marionpelouzet** [comment]
yes

thank you very much



http://them.fr <http://them.fr/>
https://www.facebook.com/themofficiel/ <https://www.facebook.com/themofficiel/>
https://www.instagram.com/themofficiel/ <https://www.instagram.com/themofficiel/>

**Comment by khouloudbelguith** [comment]
@marionpelouzet, you are welcome!
I close the issue, feel free to open a new one when needed.
Thanks!
