### ISSUE TITLE
[SOLVED] Nginx + php 7.2.12 + prestashop 1.7.4.3 + 2 languages + friendly URL --> Index Home Error 404 nginx

### ISSUE THREAD

**Issue by luisjsolsona** [PrestaShop/PrestaShop#11624]
Hello

**Describe the bug**
When you activate more than 2 languages and have URL friendly  activated, the main url in the domain runs ok with defaul language but not with another langauges.  Also i add a override in classes/ link.php and dispacher.php and tools.php to delete ISO default language and id product or id category

Example:
http://www.thesneakerone.com RUNS OK (default language. es --> remove /es)
**http://www.thesneakerone.com/en ERROR 404 Ngninx**
http://www.thesneakerone.com/nike RUNS OK  (default language. es --> remove /es and /category-id)
http://www.thesneakerone.com/en/nike RUNS OK

**To Reproduce**
1. Set more than 2 language active
2. Set URL Friendly
3. Remove iso code language 
4. Remove id-number in categories/products
4. See error in home with a no default language

**Screenshots and server configuration in plesk**
PHP configuration
https://prnt.sc/lr4ztk

NGINX configuration
https://prnt.sc/lr5091

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.12

File htaccess
```
`# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>


# Disable Multiviews
Options -Multiviews

RewriteEngine on


#Domain: www.thesneakerone.com
RewriteRule . - [E=REWRITEBASE:/]
RewriteRule ^api$ api/ [L]

RewriteRule ^api/(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^www.thesneakerone.com$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType font/woff2 .woff2
<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again

````

**Comment by khouloudbelguith** [comment]
HI @mistik777,

Thanks for your report.
@PierreRambaud what do you think?
Thanks!

**Comment by PierreRambaud** [comment]
Hi @mistik777 You can't use htaccess files in Nginx context, you need to write your own rules.

**Comment by luisjsolsona** [comment]
Hum.....  this htaccess is generated by prestashop ...

@PierreRambaud : Doy you mean that i should delete the htaccess content and write in nginx directives¿?

Anybody has the rules that prestashop write in htaccess when url friendly are activated as a Nginx rules??

Thanks in advanced

**Comment by PierreRambaud** [comment]
Yes, this file is generated by prestashop but it's because Apache allows to use it. Unlike Nginx.
You can find example here: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist

**Comment by luisjsolsona** [comment]
[SOLVED]

Change in server: execute mode PHP:   Nginx --> FastCGI served by Apache

FastCGI server by Apache OK

**Comment by khouloudbelguith** [comment]
Hi @mistik777,

Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Comment by asmagroupsa** [comment]
jai ce meme probleme

**Comment by PierreRambaud** [comment]
@asmagroupsa as I said few lines above you need to define all rules in your nginx configuration : https://github.com/PrestaShop/PrestaShop/issues/11624#issuecomment-444886802
