### ISSUE TITLE
Improve UI for Gamification module

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#11625]
See mock-ups here : https://projects.invisionapp.com/share/XMQQMBWFV79#/screens/349287917

**Comment by eternoendless** [comment]
@colinegin this needs to be specified

**Comment by colinegin** [comment]
See this PR on the gamification module : https://github.com/PrestaShop/gamification/pull/63

**Comment by PierreRambaud** [comment]
Is it still needed? I see the issue is in Done since June 2019 :thinking:
