### ISSUE TITLE
Bug Scroll Below AdminParentEmployees

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#11626]
1. Go to 'controller=AdminEmployees'
2. See error: No scroll below

**Screenshots**
![screenshot_2](https://user-images.githubusercontent.com/6318282/49535660-62f7cc80-f910-11e8-896a-b95f50c16045.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for your report.
The onboarding navbar is displayed, you need to stop the OnBording, to see all the main menu.
Thanks to check & feedback.

**Comment by TemKaSD** [comment]
@khouloudbelguith hey. pls confirm me, no email.
![screenshot_4](https://user-images.githubusercontent.com/6318282/49932536-fd5d9e80-ff14-11e8-8387-041b6812cb7c.png)

**Comment by khouloudbelguith** [comment]
@TemKaSD, this is a different issue? & you just closed?

**Comment by TemKaSD** [comment]
@khouloudbelguith sorry, small English.

**Comment by khouloudbelguith** [comment]
@TemKaSD, you resolved your issue?
Thanks!
