### ISSUE TITLE
Bug : Add to cart success without stock 

### ISSUE THREAD

**Issue by francoispeyret** [PrestaShop/PrestaShop#11631]
**Description**
1. Go to a page product with stock.
2. In BO go to this product and update the quantity to 0.
3. in the page page produit (without page refresh) add the product to cart.
4. Ouch...

The product was added but it's a success for shoppingcart but it'snot in real life.

![capture du 2018-12-06 10-37-27](https://user-images.githubusercontent.com/15829643/49575660-8851fe00-f943-11e8-8435-c6305eb3fe09.png)

**Comment by khouloudbelguith** [comment]
Hi @francoispeyret,

Thanks for your report.
If you click on "Proceed too checkout" button, you will be redirected to shopping cart page with a red alert "The item The best is yet to come' Framed poster in your cart is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted." & the "Proceed too checkout" is disabled so you cannot proceed your checkout.
![image](https://user-images.githubusercontent.com/16067358/49576964-b258ef80-f946-11e8-93d9-c60738965a72.png)
Recently, we have made some changes to fix those issues: 
https://github.com/PrestaShop/PrestaShop/pull/8752
https://github.com/PrestaShop/PrestaShop/pull/8774
https://github.com/PrestaShop/PrestaShop/pull/8607
Thanks to check & feedback.

**Comment by francoispeyret** [comment]
Right but the proceed was stop before that in 1.6..

![image](https://user-images.githubusercontent.com/15829643/49577784-7757bb80-f948-11e8-9956-fdfdab879d9f.png)

The modal-dialog hasn't got every information of current product in this case.

no bug :
![image](https://user-images.githubusercontent.com/15829643/49578035-15e41c80-f949-11e8-9c82-cb85267f121d.png)

buged : 
![image](https://user-images.githubusercontent.com/15829643/49575660-8851fe00-f943-11e8-8435-c6305eb3fe09.png)

**Comment by khouloudbelguith** [comment]
@francoispeyret, thanks for your feedback.
Yes, I tried with PS1.6 & we are stopped before the redirection to shopping cart
https://drive.google.com/file/d/1pHl6_aO4IbVLQsMdDfm3c57_8aHM3I5S/view
But with PS1.7.5.0, we are redirected to the shopping cart & the alert will be displayed.
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment]
We could add a check to verify the quantity when we click on the "add to cart" button on the product page or in the quickview
But if the product is no more available (qty <= 0 and order of out of stock products disabled) we need to specify which message we displaye and how

**Comment by francoispeyret** [comment]
A fix can do the job.
It is only to correct the display with empty data due to controller error.

https://github.com/PrestaShop/PrestaShop/compare/develop...francoispeyret:patch-3

**Comment by colinegin** [comment]
Hello,

We've checked with Nadia, our recommendation would be to have the same info and display as it is currently when the product is already out of stock. See the image
![capturenostock](https://user-images.githubusercontent.com/35263827/50145832-baa01b80-02b2-11e9-8e8e-d306b8d39c64.PNG)

The error message would be displayed when the client clicks on Add to cart (product page or quickview) instead of the current "broken" pop-up.

Of course, we still need to check with the dev team if it is possible to add a check to verify the quantity when we click on the "add to cart" button on the product page or in the quickview.

Have a nice day,

Coline

**Comment by francoispeyret** [comment]
thanks✌

**Comment by LouiseBonnard** [comment]
@colinegin, can you confirm that the action will be impossible to do? For the wording, I suggest `There are not enough products in stock`, to be localized in _Shop.Notifications.Error_. @TristanLDD, okay for you?

**Comment by colinegin** [comment]
We need the confirmation of the dev team on this issue. What do you think @PrestaShop/prestashop-core-developers ?

**Comment by marionf** [comment]
When the product is out of stock and order of out of stock products is disabled, the message displayed on the product page is the one defined in Shop parameters > Products

![capture d ecran_802](https://user-images.githubusercontent.com/13449658/50278133-82c9dd00-0446-11e9-8eb1-3a64f34c87d5.png)

![capture d ecran_801](https://user-images.githubusercontent.com/13449658/50278138-86f5fa80-0446-11e9-8688-c00375c0d20b.png)

**Comment by mickaelandrieu** [comment]
Hello,

> can you confirm that the action will be impossible to do?

the action won't be impossible but hard to be done: as it's a very minor issue I think the suggested workaround is ok.

Mickaël

**Comment by francoispeyret** [comment]
also affects 1.7.5.0

**Comment by jf-viguier** [comment]
The main issue is that the add to cart action errors returned by the CartController are not managed or displayed.
You're talking here of the out of stock error but there can be many more.

First step : I've made a PR to avoid display add to cart confirmation when an error occured :
https://github.com/PrestaShop/ps_shoppingcart/pull/41

Second step :
There is this PR that manage errors in a modal : https://github.com/PrestaShop/ps_shoppingcart/pull/24

**Comment by marionf** [comment]
I just tested: https://github.com/PrestaShop/ps_shoppingcart/pull/41

The modal isn't displayed anymore if the product is out of stock and the product page is not refreshed.
So, it's like add to cart button didn't do anything, but the product is anyway added to the cart

Video: https://drive.google.com/file/d/1HF5gts5RwANbmQ4zeTWCr38wao0lsSbg/view?usp=sharing

I just tested also: https://github.com/PrestaShop/ps_shoppingcart/pull/24

The modal isn't displayed anymore if the product is out of stock and the product page is not refreshed.
So, it's like add to cart button didn't do anything, but the product is anyway added to the cart and the product page is like blocked

Video: https://drive.google.com/file/d/1F67XapHrknmIH4oAqC1Vk1ljQsQEi5SJ/view?usp=sharing

**Comment by jf-viguier** [comment]
Tell we what's your prestashop version, I'll try to stick to it

**Comment by marionf** [comment]
I was on 1.7.6.x branch

**Comment by jf-viguier** [comment]
I've done it https://github.com/jf-viguier/ps_shoppingcart/tree/patch-1

**Comment by 4itsoft** [comment]
This patch cannot resolve my tichet #13946.

**Comment by marionf** [comment]
@4itsoft because your issue is for customizable product, please follow #9974

**Comment by francoispeyret** [comment]
thanks @marionf

**Comment by matks** [comment]
Issue not yet fixed, it requires https://github.com/PrestaShop/ps_shoppingcart/pull/41

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/ps_shoppingcart/pull/41 and Handle shoppingcart error returns properly - part 2 #14214

**Comment by matks** [comment]
Module ps_shoppingcart has been released on v2.0.3 which ship the related fix. So this bug is fully fixed when using PrestaShop 1.7.7.x and ps_shoppingcart 2.0.3
