### ISSUE TITLE
Product box

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11632]
I sell some products that can only be sold in packs (boxes) from some pieces (for example 12) and in no way can be separated, sold as singles.
If I set the box as a product (https://www.100asa.it/it/ribbon-cera/223-zebra-ribbon-cera-110x74-tipo-2300-box-12.html) on search engines I go out with the price per package, instead my other competitors come out with a single price (and they seem cheaper)
How do you think I can do with Prestashop in the standard version?
It may be a good idea to implement a function that sets the required qty / package (as was the old zencart)

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for your report.
So, you need search engines, the price displayed is only the price of one product, not all the pack?
Thanks!

**Comment by centoasa** [comment]
Hi @khouloudbelguith 
If I create a single product with single price ($1) search engine show "product X --> $1"
And into product I can set qty_box=15, so customers can buy 15pcs or multiple of 15
(this is the default behaviour of zencart)

**Comment by khouloudbelguith** [comment]
@marionf, @colinegin what do you think of his improvement?
Thanks!

**Comment by marionf** [comment]
@centoasa 

You can fill the unit price field for your product like this:

![capture d ecran_742](https://user-images.githubusercontent.com/13449658/49748158-3f80a900-fca5-11e8-84df-75b734be0af4.png)

![capture d ecran_741](https://user-images.githubusercontent.com/13449658/49748164-427b9980-fca5-11e8-893f-76b2c57d58f4.png)

**Comment by centoasa** [comment]
@marionf maybe a very good solution!
Still remain valid my suggestion!
Thank you so much.

**Comment by marionf** [comment]
The thing we can do is put the unit price more forward, what do you think ?

**Comment by centoasa** [comment]
that's OK @marionf

**Comment by marionf** [comment]
@TristanLDD Can you suggest something to put the unit price more forward ?

**Comment by TristanLDD** [comment]
@marionf  What we could do is use the same CSS class both for the price and the unit price, so the unit price will be more visible. We just need to check if that change has unexpected impacts or not.

**Comment by MatShir** [comment]
Hi @centoasa ,

We got your feedback and we seem to have a solution.
But with the load of work we have in our hands, we have shared your idea at Prestashop Feedbacks(http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/36889873-price-per-unit-for-product-pack-like-alibaba-marke) to let the community help us to prioritizes all ideas from the community.

Thank you

**Comment by NeOMakinG** [comment]
Fine on product with a promotion, wrong on normal product
