### ISSUE TITLE
Private functions in ps_facetedsearch module

### ISSUE THREAD

**Issue by netraagal** [PrestaShop/PrestaShop#11630]
Hi,

I'm working on the override of the ps_facetedsearch module, but am stuck due to the private functions in the module, as I cannot cal them in my override.

Is it possible to pass them to public or protected or there is a reason behind this choice ?

**Comment by matks** [comment]
Hi @netraagal, thanks for the input

Can you tell us which methods you are looking to override as the answer will depend ? Usually if we have used `private` methods it is because we consider this to be an internal behavior and that overriding this part alone is not recommended, but we can check.

Can you also tell us what you are trying to achieve ? Overrides might not be the good way to do it, especially because it makes your shop very specific and might create issues when upgrading the shop or adding new modules.

**Comment by khouloudbelguith** [comment]
Hi @matks,
There is an old [issue](http://forge.prestashop.com/browse/BOOM-2376) similar to this ticket.
Thanks!

**Comment by netraagal** [comment]
Hi @matks,

I have to add some filter types (supplier and tag) in the ``getFilterBlock`` function.

Then the horrible part comes:
To do that, I'm in the obligation to copy/paste the **whole** function to set my modifications.
And copy/paste all the little private functions ``get[name]FilterSubQuery`` as they are called in ``getFilterBlock``.

The overrides I'm coding are really big modifications. For the ``getFilterBlock`` function block, I don't really have another way to do it :/
But for the little private ones, it would be cool to have access to them from my override, or to have a generic static method like ``getFilterSubQuery`` which check if the ``get[name]FilterSubQuery`` exist and return its result.

As you say, it's better to set internal behavior functions to private, but can also be really difficult to develop on it when the website has really specific needs. :)

Hi @khouloudbelguith,

Didn't see that issue before :) Cannot say it's not related in a way.

**Comment by mickaelandrieu** [comment]
Hello,
I'm more in favor of adding new hooks than make function public, allowing you to alter the current behavior make the upgrade difficult for everyone.

In 1.7.x, more and more we are closing our API (making classes final, properties and methods private by default) and expanding the ways you can alter the common behavior (hooks, events, templating customization).

If you have the need for a new Hook and are willing to contribute, you are very welcome to make a pull request.

Anyway, thanks for your feedback :+1:

**Comment by marionf** [comment]
@mickaelandrieu Is there something to do here or it can be closed ?

**Comment by colinegin** [comment]
Hello,

we are currently refactoring the faceted search module, tell us if you have the need for new hooks !

Have a nice day,

Coline

**Comment by marionf** [comment]
@netraagal Could you please tell us if you have the need for new hooks ?

**Comment by netraagal** [comment]
@marionf nah I don't think, I will probably continue to override the module, even if it means copy/paste whole functions.
The modifications done are too much to simply code it with a hook.
Thank anyway :)
