### ISSUE TITLE
Order in the wrong customer account

### ISSUE THREAD

**Issue by Yquem1983** [PrestaShop/PrestaShop#11642]
**Describe the bug**
We migrated from PS 1.6 to 1.7 and since we sometimes have an order that is valid in another customer account. This bug occurred on new clients but also old clients (before the migration) and with different product or carriers. It seems that the bug occurs when both clients are connected at the same time so it is very hard to reproduce the bug...

Have you ever have this kind of bug ? 

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.3.4
PHP version: 7.0.31

**Comment by khouloudbelguith** [comment]
Hi @Yquem1983,

Thanks for your report.
Did you use any module Social Login Connect (Facebook or Google login)?
Thanks!

**Comment by Yquem1983** [comment]
Hi @khouloudbelguith ,
Thanks for your message.
I installed a social login module but I disabled it because it caused other bugs.
Thanks

**Comment by Yquem1983** [comment]
I uninstalled the social login module completely.
Hope this will solve the bug.

**Comment by khouloudbelguith** [comment]
Hi @Yquem1983,

To be sure, could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
If you have any ovveride created by this module, thanks to delete it.
Thanks!

**Comment by Yquem1983** [comment]
Hi @khouloudbelguith,
I clear cache manually. There is ni overide by this module.

Unfortunately, the bug has been repeated several times. 

I have a module for the header that allows customers to connect while overflying icon "account". Can this module be the cause of the problem?

Thanks!

**Comment by khouloudbelguith** [comment]
@Yquem1983, yes it could be.
We are really interested to find out what's wrong.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Yquem1983,

Any news about your issue?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Yquem1983,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
