### ISSUE TITLE
Advanced filters on stock movements page are not working

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11640]
**Describe the bug**
Advanced filters on stock movements page are not working

**To Reproduce**
1. Go to Catalog > Stock
2. Edit quantity of some products
3. Click on Movements tab
4. You see products
5. In the filter select an employee or type of movements or status or dates
6. No results

**Screenshots**
![capture d ecran_731](https://user-images.githubusercontent.com/13449658/49587408-06260180-f964-11e8-9ab2-43488f92f1f4.png)

![capture d ecran_732](https://user-images.githubusercontent.com/13449658/49587417-0a521f00-f964-11e8-91d4-a29a3127c013.png)

![capture d ecran_733](https://user-images.githubusercontent.com/13449658/49587421-0cb47900-f964-11e8-9922-a801f7cba8fa.png)

![capture d ecran_734](https://user-images.githubusercontent.com/13449658/49587425-0faf6980-f964-11e8-91a2-3e8c04f72589.png)

![capture d ecran_735](https://user-images.githubusercontent.com/13449658/49587427-1211c380-f964-11e8-8c8c-b7c8a17ec77d.png)

![capture d ecran_736](https://user-images.githubusercontent.com/13449658/49587438-16d67780-f964-11e8-8dbe-60c684f98a8a.png)

![capture d ecran_738](https://user-images.githubusercontent.com/13449658/49587746-1a1e3300-f965-11e8-93cf-5bcdcdc836f5.png)

![capture d ecran_737](https://user-images.githubusercontent.com/13449658/49587749-1d192380-f965-11e8-919b-dec0da96ae29.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by jolelievre** [comment]
hello, I cant reproduce the problem on branch 1.7.5.x
the filters seem to work correctly, although I was limited because I had few different Movements, yet the filters were consistent

**Comment by marionf** [comment]
I can't reproduce it either
