### ISSUE TITLE
hookDisplayAdminProductsExtra not showing its content in 1.7.5

### ISSUE THREAD

**Issue by elektryz** [PrestaShop/PrestaShop#11657]
**Describe the bug**
Can't see the content of hook hookDisplayAdminProductsExtra on PS 1.7.5 (fresh installed). From PS 1.7.0.0 to 1.7.4.4 it is visible. See the screenshot below

![image](https://user-images.githubusercontent.com/8435019/49650241-e0642f80-fa2b-11e8-8d3e-8d81e352dae5.png)

Why is that happening?

**Comment by khouloudbelguith** [comment]
Hi @elektryz,

Here's the Pr: https://github.com/PrestaShop/PrestaShop/pull/11584 to fix the issue.
Your ticket is a duplicate of #11582
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11582
