### ISSUE TITLE
Installatron fresh install 1.7.4.4 - cannot add product to cart

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11651]
To test errors we have on operational site, we created fresh dev site through Installatron.

On fresh site cannot add product to cart. 

SP 1.7.4.4
PHP 7.1.22

server error log.

[Thu Dec 06 20:59:19.553350 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Trying to get property of non-object in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/classes/Context.php on line 353\n
[Thu Dec 06 20:59:19.556775 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 20:59:19.580416 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 20:59:19.580497 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 20:59:19.580895 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 20:59:19.581463 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 20:59:19.758486 2018] [lsapi:notice] [pid 1508613:tid 140692135270144] [client 141.138.169.224:40647] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/src/PrestaShopBundle/Install/LanguageList.php on line 175\n
[Thu Dec 06 21:00:19.673127 2018] [lsapi:notice] [pid 1528711:tid 140692324087552] [client 217.62.77.185:64444] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined offset: 252 in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/modules/gamification/gamification.php on line 538\n, referer: http://www.mydomain.nl/xxxxxxxx/ldk1gzipxvetlvdw/index.php?controller=AdminDashboard&token=74c709257d2cd3ff40dacd8041117506
[Thu Dec 06 21:00:19.701378 2018] [lsapi:notice] [pid 1528711:tid 140692324087552] [client 217.62.77.185:64444] [host www.mydomain.nl] Backend log: PHP Notice:  Undefined offset: 252 in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/modules/gamification/gamification.php on line 538\n, referer: http://www.mydomain.nl/xxxxxxxx/ldk1gzipxvetlvdw/index.php?controller=AdminDashboard&token=74c709257d2cd3ff40dacd8041117506
[Thu Dec 06 21:02:16.888728 2018] [lsapi:error] [pid 1590342:tid 140692198209280] [client 217.62.77.185:64525] [host www.mydomain.nl] Backend fatal error: PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove directory "/home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/var/cache/dev/smarty/compile": rmdir(/home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/var/cache/dev/smarty/compile): Directory not empty. in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180\nStack trace:\n#0 /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/classes/Tools.php(3165): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#3 [internal function]:  in /home/deb115780/domains/mydomain.nl/public_html/xxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180\n, referer: http://www.mydomain.nl/xxxxxxxx/ldk1gzipxvetlvdw/index.php/configure/advanced/performance?_token=AfERazbvQyvg-vT1VVZu-aSvO0GWlVoOpaN3ZUXEwWYlVoOpaN3ZUXEwWY

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Thanks for your report.
With Fresh installation PS1.7.4.4 downloaded from this [link](https://www.prestashop.com/en/previous-versions), I did not manage to reproduce the issue.
If you enable the mode debug in the BO => Shop Parameters => Performance page, is there any exception displayed when you add the product to the cart?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
