### ISSUE TITLE
error in module Viewed products block v1.2.0

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11655]
Prestashop 1.7.4.4
with this module installed I've now this error:
(1/1) ClassNotFoundException
Attempted to load class "ProductListingPresenter" from namespace "PrestaShop\PrestaShop\Adapter\Presenter\Product".
Did you forget a "use" statement for "PrestaShop\PrestaShop\Core\Product\ProductListingPresenter"?

in ps_viewedproduct.php line 269
--
at Ps_Viewedproduct->getViewedProducts()in ps_viewedproduct.php line 219

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4 & ps_viewedproduct v1.2.0
![image](https://user-images.githubusercontent.com/16067358/49644543-07653600-fa19-11e8-9339-54d221102329.png)
We will see how to fix it.

I tried with ps_viewedproduct v1.2.0 & PS1.7.5.0rc1 and it is ok.
Thanks!

**Comment by khouloudbelguith** [comment]
To visualize the issue, we need to enable the debug mode.
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith last message was for me?
I'm sorry but my website is in production, so I can't enable module and show error in product page

**Comment by khouloudbelguith** [comment]
@centoasa, no.
Just to reproduce the issue, we need to enable the debug mode.
Thanks!

**Comment by MobileStarChart** [comment]
Me the same, I follow this topic and keep looking the way to fix it.

**Comment by shacker2** [comment]
to solve the issue, replace in the top of the file the line

//use PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductListingPresenter;
use PrestaShop\PrestaShop\Core\Product\ProductListingPresenter;

**Comment by wordliner** [comment]
Thx. Works for me. The same problem on 1.7.2

**Comment by phaan** [comment]
Thx. Works for us to. The same problem on 1.7.4.4,Multistore
It was a big issue for us, because the customers could not put anything or only 1 product in de the shopping cart. After a long search, found this solution, the first thought we had was a cookie or cache problem.

**Comment by khouloudbelguith** [comment]
Hi @shacker2,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/ps_viewedproduct/
Thank you!

**Comment by centoasa** [comment]
I don't understand why with the patch of @shacker2 I've an error500 when I see more than 1 product

**Comment by khouloudbelguith** [comment]
@centoasa, if you enable the debug mode, is there any exceptions displayed?
Thanks!

**Comment by shacker2** [comment]
done

**Comment by marionf** [comment]
PR: https://github.com/PrestaShop/ps_viewedproduct/pull/12

**Comment by khouloudbelguith** [comment]
Here's the fix https://github.com/PrestaShop/ps_viewedproduct/pull/13
Thanks!

**Comment by zubee** [comment]
> 
> 
> to solve the issue, replace in the top of the file the line
> 
> //use PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductListingPresenter;
> use PrestaShop\PrestaShop\Core\Product\ProductListingPresenter;

Thanks for the help. It solved my problem in 1.7.3.2

**Comment by centoasa** [comment]
with latest release 1.2.1 of this module I've still this error: https://1drv.ms/t/s!AnkbspQIR_C67GifIkwDNUAzglgz
Already patched with https://github.com/PrestaShop/PrestaShop/issues/11655#issuecomment-450387405

**Comment by Matt75** [comment]
@centoasa Hi, it seems you have an error in `themes/leo_emarket/templates/catalog/_partials/miniatures/product.tpl`
This file is provided by third party, contact the developper of your theme on Addons MarketPlace.
