### ISSUE TITLE
Allow Countries to have Multiple Zones

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#11662]
**Describe the bug**
Sometimes there is the need for one country to have multiple shipping zones (for example in my case, Portugal, we have mainland and we have 2 sets of islands. Carriers tend to charge different values depending on whether the shipment is to mainland Portugal or to the islands) 

In prestashop you can set zones to countries and zones to states but setting a state to zone X is useless as it will always be overwritten by whatever zone the state's country is set to

**To Reproduce**

I have 2 zones:
1 - Mainland
2 - Islands

I'm forced to select one single zone for the country so I select zone 1.

In the states tab I have multiple States all under Portugal. Some states are set to zone 1, others to zone 2. 

The states set to zone 1 are ok. 
The states set to zone 2 are K.O. - Everytime someone orders from one of those states they get the "No Carriers Available" message on checkout even if the carriers are set correctly.

I think that this is a big flaw in the shipping mechanism of prestashop. The simple solution would be to allow a country to be assigned to multiple zones and to always get the zone id from the states configs and not from the country's configs (only when states are disabled for some country should the zone id be fetched from the country's configs)
 

**Additionnal information**
PrestaShop version: 1.7.2.2 but I think it applies to all versions of 1.7 (maybe also 1.6)
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @psydomin,

Could you please try to create a custom zone Mainland-Islands.
![image](https://user-images.githubusercontent.com/16067358/49722673-8babf900-fc65-11e8-92aa-39ec94c346e1.png)
For this new zone, you can select it to your country.
![image](https://user-images.githubusercontent.com/16067358/49722775-c31aa580-fc65-11e8-8c91-114a523bf706.png)
Thanks to check & feedback.

**Comment by rdy4ever** [comment]
Hi @khouloudbelguith
I do think he wants to have multiple shipping zones (with different rates) inside the same country. As you suggested, he is still restricted to pick just one zone for one country.
And it does make a lot of sense: in my country, for example, the carriers charge different fees if you send locally or national. So it would be very handy to be able to set multiple shipping zones inside the same country.

**Comment by khouloudbelguith** [comment]
@rdy4ever, thanks for your feedback.
@marionf, @colinegin what do you think?
Is it possible to have a country in more than one zone, so we can give each carrier to their own zone numbers?
Thanks!

**Comment by psydomin** [comment]
Exactly as @rdy4ever said. The goal is to have multiple zones within one given country so that we can charge different shipping prices for different zones inside the same country.

**Comment by MatShir** [comment]
Hi @psydomin,
It's a specific case but with a bit of search, there is already a module for that: https://addons.prestashop.com/en/search?search_query=postal%20code. You could choose a specific carrier for a define postal code zone. Thank you for feedbacks but this kind of feature is well made and maintained by the contributors. 
In any case, if you really want it to be implemented in PrestaShop future version, I invite you to share your idea to the community at http://feedback.prestashop.com/forums/387864-prestashop-1-7-x

**Comment by thierryzoller** [comment]
It is unfortunate (and frankly mindblowing) that Prestashop requires paid plugins to allow to include a country in multiple zones. It is the easiest way to achieve a common problem, yet it appears Prestashop diverts to hacks instead of implementing what must be the most obvious solution possible.
