### ISSUE TITLE
BO : Impossible to save a product with a new attachment

### ISSUE THREAD

**Issue by mael-c** [PrestaShop/PrestaShop#11686]
**Describe the bug**
On the BO, I can't add or edit a product with a new attachment without an error. The attachment is added on the database. When the product is saved, Prestashop don't know the new attachment field and throw this error : "This value is not valid".

**To Reproduce**
1. Go to your BO and edit or add product.
2. Add your product information if needed.
3. Add Attachment in your product options
4. Click on product save button. 
5. See error

**Screenshots**
![selection_041](https://user-images.githubusercontent.com/25532080/49720652-aaf45780-fc60-11e8-9745-aee8e2672880.png)

**Additionnal information**
PrestaShop version: 1.7.3.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @mael-c,

Thanks for your report.
I did not manage to reproduce the issue.
What is the exact type of the attachment that you uploaded it?
Can you please provide us this attachment to test with it.
Thanks!

**Comment by mael-c** [comment]
Hi @khouloudbelguith 
I don't think that attachment type is my problem.
I tested with pdf, jpg, and png (30-40 different files) with no success.
If I just upload my attachment, there is no problem. My attachment is uploaded and correctly linked to my product. I have to refresh my page for update my other product fields.
Here is one of my test attachment : 
![board-361516_640](https://user-images.githubusercontent.com/25532080/49738556-ec502b80-fc8f-11e8-8bfb-5ab5488d70b5.jpg)

Thanks for your quick answer !

**Comment by khouloudbelguith** [comment]
@mael-c, could you please navigate to your BO => Advanced Parameters => Information => check the Upload Max File size valur.
Thanks!

**Comment by mael-c** [comment]
@khouloudbelguith My Upload File size value is 640Mo.

**Comment by khouloudbelguith** [comment]
@mael-c, We need to retrieve the PHP error log in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by mael-c** [comment]
Hi @khouloudbelguith I checked my php and apache logs.
They have no errors for my problem. I have an error only on my console browser.
![selection_046](https://user-images.githubusercontent.com/25532080/49810075-ad3ddb00-fd60-11e8-8dd6-5f43e8182990.png)

**Comment by khouloudbelguith** [comment]
Hi @mael-c,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
