### ISSUE TITLE
Introduce new labels

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#11683]
I need 2 more labels:

* `WIP` for `Work In Progress`: this means that we don't have to review the contribution right now, could be named `RFC` too;
* `Waiting for Review`: this means the pull request need a review from a specific developer (we can assign him) so the others don't need to review the contribution: we gain time.

**Comment by matks** [comment]
1) Currently, WIP PRs have `[WIP]` in their title. Is that not good enough ?
2) The label you are talking about is a good idea, but can we improve the naming to really underline the fact it expects a specific review, not anyone ? Like `Waiting for reviewer` ?

I also have a usecase where I would love to have a label, it is "discussion in progress": when the PR is ready, a 1st review has been done and now there are back-and-forths between the PR author and the reviewers. I am not sure whether this requires a new label or not (just sharing 😃 ).

**Comment by mickaelandrieu** [comment]
> Like Waiting for reviewer ?

I like it :)

> when the PR is ready, a 1st review has been done and now there are back-and-forths between the PR author and the reviewers.

Yup.

In fact, my needs is to not waste time on already reviewed pull requests (or on uncomplete ones).

I use a lot the available filters for that :)

**Comment by PierreRambaud** [comment]
FYI: There is already a section for Waiting for Review: https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+is%3Aopen+review%3Arequired
https://blog.github.com/2017-01-23-filter-pull-request-reviews-and-review-requests/

**Comment by marionf** [comment]
I can create new labels, so we need :
1. WIP
2. Waiting for review ? Or it's not necessary ?

**Comment by marionf** [comment]
@mickaelandrieu 

I just created WIP label: https://github.com/PrestaShop/PrestaShop/labels?utf8=%E2%9C%93&q=WIP
