### ISSUE TITLE
Generally, the "Module Manager" tab should be the first tab here in Modules Tab

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11692]
**PrestaShop Version**
V1.7.5.0 RC1

**Is your feature request related to a problem? Please describe.**
See my screenshot, All clear in the screenshot

**Describe the solution you'd like**
Just reverse the order
![download 21](https://user-images.githubusercontent.com/19220745/49781644-89b36a00-fd39-11e8-9c15-77609979b55c.png)

**Comment by dheerajwebkul** [comment]
This new module manager tab improvement is resolving one of my previous requests

http://forge.prestashop.com/browse/BOOM-5749
http://forge.prestashop.com/browse/BOOM-4033

Discusses with @vincentbz 

If you can see the forge.

Still, I think the problem is,
we need to search uninstalled module in "Module Catalog" Tab and installed modules in "Module Manager" tab. My concern was keeping "Module Catalog" is only for addons module feed, But when the user downloaded or installed the module, this will now place the "Module Manager" tab, no matter module is installed or uninstalled, the only if downloaded.

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
Your improvement issue is related to #10047, in fact, we are planning to make this changes.
Thanks to check & feedback.

**Comment by dheerajwebkul** [comment]
@khouloudbelguith Thanks

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, so can I close your issue?
Thanks!

**Comment by dheerajwebkul** [comment]
@khouloudbelguith You can close, I have nothing much to explain this here,
But just be sure there is a difference between #10047 (its closed also) and this, 

Important in this request is:
- Swap tab position
- Do not send uninstalled module in "Module Catalog" tab

If these features are raised anywhere exactly, Please link here and close this issue.

**Comment by khouloudbelguith** [comment]
@marionf, @colinegin, what do you think? is that possible to add these improvements suggested by @dheerajwebkul?

**Comment by colinegin** [comment]
Hi all,

We are currently discussing with the rest of the team about what page should be put first to provide the best possible user experience, we will come back to you as soon as possible with a decision.

Have a nice day,

Coline

**Comment by colinegin** [comment]
As discussed, this should be the new tab organization :
Modules
Module Manager
Module Catalog

Thanks
