### ISSUE TITLE
demande de configuration du menu Horizontal

### ISSUE THREAD

**Issue by TelInfo** [PrestaShop/PrestaShop#11717]
Bonjour,
Je voudrais savoir comment configurer mon menu en Horizontal en ayant
1 Catégorie
     5 Sous-Catégories 
          6 Sous-Familles

Comme sur le document joint le meme menu....
![p_20181211_121642](https://user-images.githubusercontent.com/45788818/49801364-444b6880-fd4a-11e8-8457-8bfcf29dbdcc.jpg)

**Comment by khouloudbelguith** [comment]
Hi @TelInfo,

You need to navigate to your BO => Modules => Modules & Services => Installed modules tab => search for the ps_mainmenu module & configure it.
![image](https://user-images.githubusercontent.com/16067358/49804501-fd15a580-fd52-11e8-9784-e6d964c9d38d.png)
Thanks to check & feedback.

**Comment by TelInfo** [comment]
Je l'ai déjà effectuer en revanche mon menu se déroule en vertical et je le voudrais en Horizontal.
Allez jeter un Oeil vous comprendrez...
https://www.boutiquetelinfo85.com

**Comment by khouloudbelguith** [comment]
@TelInfo, your vertical menu module is developed by your theme author, it is not provided by PrestaShop.
I should be called a vertical menu.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @TelInfo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
