### ISSUE TITLE
[1.7.3.3] CSV product import created new products instead overwriting existing ones

### ISSUE THREAD

**Issue by MarekKaliszuk** [PrestaShop/PrestaShop#11719]
Hello,
i have problem with import of CSV file with products - it is always creating new products instead existing ones.

Reproduce:
- export 5 products exisitng in database through catalog->products list -> export buttom. CSV file will be downloaded.
- open csv file in csv editor - i've used open office with utf8 support. 
- i used only  product id, name, and netto price columns - also tested on full  list of exported columns)
- go to catalog->products->import - load file, set lang to polish, separator ; -> next -> table is filled with data from csv -> i've set first table as ID, second Name, thrid - price netto
-> click import

PS 1.7.3.3
PHP 5.6

No errors in debug mode and in php error log.

Here are screenshots:
![screencapture-ps17-creas-pl-admin645sgpnnp-index-php-2018-12-11-13_49_15](https://user-images.githubusercontent.com/35937012/49802042-2252e580-fd4c-11e8-81cd-fd6a317f4380.png)
![screencapture-ps17-creas-pl-admin645sgpnnp-index-php-2018-12-11-13_49_51](https://user-images.githubusercontent.com/35937012/49802044-22eb7c00-fd4c-11e8-8f1c-4fe55a97a2bc.png)
![screencapture-ps17-creas-pl-admin645sgpnnp-index-php-2018-12-11-13_50_21](https://user-images.githubusercontent.com/35937012/49802046-22eb7c00-fd4c-11e8-8116-4dcad77bc124.png)
![screencapture-ps17-creas-pl-admin645sgpnnp-index-php-product-catalog-0-50-2018-12-11-13_51_41](https://user-images.githubusercontent.com/35937012/49802047-22eb7c00-fd4c-11e8-94dd-5ccdb493ff8f.png)
[product_2018-12-11_125151.pdf](https://github.com/PrestaShop/PrestaShop/files/2667601/product_2018-12-11_125151.pdf)

**Comment by khouloudbelguith** [comment]
Hi @MarekKaliszuk,

Thanks for your report.
To update products via The Import page, you need to enable the option "Use product reference as key" & the option "Force all ID numbers".
Thanks to check & feedback.

**Comment by MarekKaliszuk** [comment]
Thank You!!!
Sometimes is better to write here on github.
 i've spent like 1,5h on solving issue :X

Have a nice day @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@MarekKaliszuk, you are welcome.
Feel free to open a new one when needed.
Thanks!
