### ISSUE TITLE
Cart

### ISSUE THREAD

**Issue by pmono75** [PrestaShop/PrestaShop#11748]
Hello,

Prestashop 1.7.3.0
localisation>defaut country > Allemagne
Order can be proceed withou account

When a new customer want to pay his order, he entered name and email adresse (step 1), then he entered his address :
If the country is allemagne : >no problem
If the country is changed to : France > at the end of this step (step2)
The customer is directed to login to his account

How I can fix this issue?

Regards,
P

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @pmono75,

Thanks for your report.
I did not manage to reproduce the issue with PS 1.7.5.0rc1.
I attached a video record.
https://drive.google.com/file/d/172uzSCR4qsvLLFSKLlP6EAlXw2UuaGI0/view
Thanks to check & feedback

**Comment by pmono75** [comment]
Hi,

On your video, you have created an account (you have a password).
You change the country in a second time.
Could you please try it without password (no account) ?
You can also try it on our store : www.magasino.com
Best regards,
P

**Comment by khouloudbelguith** [comment]
@pmono75, in my case it is OK.
https://drive.google.com/file/d/1cPXAqiN9_GIv1Su276cPTHLNNhI92STB/view
Have you tried to contact the theme author about this issue?
Thanks!

**Comment by pmono75** [comment]
As i can see you are not using a 1.7.3.0 version of prestashop.
Why you can't change the country at first time (you entered your adress, then you go back to the adress) ?
Regards,
P

**Comment by khouloudbelguith** [comment]
@pmono75, yes, in my previous comment, I specified that I did not manage to reproduce the issue with PS1.7.5.0rc1.
Yes, I can change my country for the first time, but I just create an address with Germany country, then I edited my address.
Thanks!

**Comment by pmono75** [comment]
OK, I updated prestashop to 1.7.4.4 then the theme and now it seems to be working well.
Thanks for you help.

Best regards,
P.

**Comment by khouloudbelguith** [comment]
@pmono75, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
