### ISSUE TITLE
Wrong Recovery Password Error Messages

### ISSUE THREAD

**Issue by web-fu** [PrestaShop/PrestaShop#11743]
**The bug**
If the user enter a non valid password, the error messages displayed are not corrects

**To Reproduce**
1. Log out
2. Use 'Password Recovery' for your customer account
3. Go to password recovery link
4. Insert an INVALID password and an EQUAL confirmation (eg: pass: 1234 confirmation: 1234)
5. The error returned is : "The password and its confirmation do not match" instead of "The password is not in a valid format."

The error does not present itself in admin area.

**Additional information**
PrestaShop version: 1.7.4
PHP version: 7.2

**Comment by luisjsolsona** [comment]
Have you migrate from a Prestashop 1.6 ¿?

**Comment by web-fu** [comment]
New installation.
Just check /controllers/front/PasswordController.php, lines 123 - 140:
`  if (!(Tools::isSubmit('passwd'))
                || !(Tools::isSubmit('confirmation'))
                || ($passwd = Tools::getValue('passwd')) !== ($confirmation = Tools::getValue('confirmation'))
                || !Validate::isPasswd($passwd) || !Validate::isPasswd($confirmation)) {
                // Check if passwords are here anyway, BUT does not match the password validation format
                if (Tools::isSubmit('passwd') || Tools::isSubmit('confirmation')) {
                    $this->errors[] = $this->trans('The password and its confirmation do not match.', array(), 'Shop.Notifications.Error');
                }
                $this->context->smarty->assign([
                    'customer_email' => $customer->email,
                    'customer_token' => $token,
                    'id_customer' => $id_customer,
                    'reset_token' => Tools::getValue('reset_token'),
                ]);
                $this->setTemplate('customer/password-new');
            } `
I've fixed on my prestashop, how do I submit the code?

**Comment by khouloudbelguith** [comment]
Hi @web-fu,

I did not manage to reproduce the issue with PS1.7.5.0rc1.
![image](https://user-images.githubusercontent.com/16067358/49864511-eb8bd680-fe02-11e8-9b50-4f1099196da2.png)
Thanks to check & feedback.

**Comment by web-fu** [comment]
Not in admin panel.
It's a problem only for customer.
If you look at the file /controllers/front/PasswordController.php, there is not an error message for invalid password format

**Comment by khouloudbelguith** [comment]
@web-fu,

Yes you are right
![image](https://user-images.githubusercontent.com/16067358/49864941-ea0ede00-fe03-11e8-90a2-f91dd2aab0e1.png)
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by web-fu** [comment]
@khouloudbelguith just submitted the pull request, but is failed during pipeline check:

> The command "if [ $PRESTASHOP_TEST_TYPE = "lint" ]; then bash tests-legacy/check_file_syntax.sh; fi" exited with 255.

No more error is shown, what I have to debug?

**Comment by khouloudbelguith** [comment]
@web-fu, I restarted the build for you, Tanks for the fix.
Our dev should review your PR, to be tested.
THanks!
