### ISSUE TITLE
Switch for price display when the catalog mode is on 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#11742]
**User Story**
As a merchant,  I want to choose if the prices are hidden or not when I enable the catalog mode.

**Description**
When I enable the catalog mode, it will display a switch to choose to show prices or not. By default, the prices are hidden so when the catalog mod is on the switch should be on "NO".

**Additional context**
![mod catalogue](https://user-images.githubusercontent.com/43613217/50275920-e4874880-0440-11e9-96dc-acfb2f95206e.png)

You can find the same UI comportment on Page Advanced Preferences > Performance > Smarty block > Enable/Disenable Cache

**Wording** 
In English:

**- Catalog mode**
_text on the bottom of the "Catalog mode" switch_:
> Disable products checkout (prices, add to cart buttons, price filters etc.)

Catalog mode toolbox: "Catalog mode makes your store look like a retail website."

**- Show prices**
_text on the bottom of the "Show prices" switch_ : None

Show prices toolbox: None

**Reference PR/Issues**
#9937

**Comment by MatShir** [comment]
@LouiseBonnard  
Do you think we should find another name for Catalog Mode?

**Comment by LouiseBonnard** [comment]
Do you already have something else in mind? Do you think it is not clear enough?

**Comment by jolelievre** [comment]
@MatShir so this additional setting is only available when the Catalog mode is on?

**Comment by MatShir** [comment]
> @MatShir so this additional setting is only available when the Catalog mode is on?

@jolelievre Yes exactly

**Comment by jolelievre** [comment]
I worry about the complexity this is gonna bring in the code.. We will have to implement many test and `if`s, like "ok we're in the catalog mode, BUT we display prices, so actually ignore this case.."
This notion of "sub-setting" seems complicated for little gain. Maybe it would be simpler to separate the catalog mode into two settings:

CATALOG_MODE = DISPLAY_PRICES_MODE + DISPLAY_CHECKOUT_MODE

**Comment by MatShir** [comment]
> Do you already have something else in mind? Do you think it is not clear enough?

Nevermind, changing the name will confuse the current user. @LouiseBonnard I edit the new wording directly in the issue

**Comment by MatShir** [comment]
Hi @jolelievre, 
Check the new wording on the related section in the issue, the one from mock-up is not correct anymore :)

**Comment by jolelievre** [comment]
Okay, what is the correct wording then?

**Comment by MatShir** [comment]
> Okay, what is the correct wording then?

On the issue, you can find the wording paragraph. It contains all English wording required.

**Comment by MatShir** [comment]
New wording specification coming in the following issue #12539

**Comment by Shimazakid** [comment]
Where is the catalog mode option in prestashop 1.7.5.4? i cannot find it, i just find third party modules that cost 30 dollars or more.....is this the future of this mode function?, to put a paywall on it?

**Comment by eternoendless** [comment]
> is this the future of this mode function?, tu por a paywall on it?

@Shimazakid calm down, I don't know where you got that idea. This feature will be available in PrestaShop 1.7.6.0, as indicated in the Milestone here:

<img width="1012" alt="Screenshot 2019-04-26 at 17 30 49" src="https://user-images.githubusercontent.com/1009343/56819356-d495d000-6849-11e9-9480-7982a493dfe2.png">

BTW PrestaShop 1.7.5.4 doesn't exist, the latest released version to date is 1.7.5.1.

**Comment by Shimazakid** [comment]
Edited due to @eternoendless responding to my question in the most polite manner, this post was quite aggresive and has no point to be Here!

**Comment by eternoendless** [comment]
FYI the Catalog mode is still present in 1.7 versions. You can find it in Shop Parameters > Product Settings > Products (general).

This change in particular allows you to go in catalog mode while keeping prices shown.

**Comment by eternoendless** [comment]
This screencap was taken on a 1.7.4.2

<img width="824" alt="Screenshot 2019-04-26 at 17 55 46" src="https://user-images.githubusercontent.com/1009343/56820558-8df5a500-684c-11e9-8bbf-ef452e3c884b.png">

**Comment by Shimazakid** [comment]
Ok, now, i need to apology, and ask for forgiveness, @eternoendless, i was so frustated with not finding this answer in google that i went  berserk, my most deep and sincerelly apology for my angry rant, i have no words to express the valuable help you provided where google had no answer for this (it had the answer for 1.6).....thanks, many, many thanks! i´ll proceed to erase my last angry post.....(my instalation was 1.7.2.4, so, it was right there where you pointed me, i believed erroniouslly that i had the las version)

**Comment by eternoendless** [comment]
Don't worry about it 😉
