### ISSUE TITLE
In the installation page, the step3 is skiped, it is not verified

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11755]
**Describe the bug**

In the installation page, the step3 is skipped and not verified.
I attached a video record.

**To Reproduce**
1. Try to install the branch develop

**Screenshots**
https://drive.google.com/file/d/1q3G3mC3B_nDYZNbXSBarP7EpgorZFA4i/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by marionf** [comment]
I will try to reproduce when 1.7.5.x will be merged into develop

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is not about this PR https://github.com/PrestaShop/PrestaShop/pull/11689?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

it's related to https://github.com/PrestaShop/PrestaShop/pull/9366, we are planning to do that.
Thanks!
