### ISSUE TITLE
1.7.4.4 Can't be install 

### ISSUE THREAD

**Issue by Trylam** [PrestaShop/PrestaShop#11759]
**Describe the bug**
There is an error during the installation. It occur during the system configuration step. it says the accessory table already exists.

**To Reproduce**
1. download from the website https://www.prestashop.com/en/download
2. extract 
3. go to the install adress
4. create database and user 
 ```sql
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password'; 
create database mydatabase;
grant all privileges on mydatabase.* to user@localhost;
```
5. start and follow installation step 
6. At 12% it stop with error msg.
Une erreur est survenue durant l'installation...
Vous pouvez utiliser les liens à gauche pour revenir aux étapes précédentes, ou redémarrer l'installation en cliquant ici.
    1: Erreur SQL sur la requête Table 'accessory' already exists

note : i try with and without the default table prefix
  

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.3
Debian testing
Apache2 with mpm itk

**Comment by khouloudbelguith** [comment]
Hi @Trylam,

1. Before the installation, could you please enable the mode dev.
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:
`define('_PS_MODE_DEV_', false);`
… and change it to:
`define('_PS_MODE_DEV_', true);`
2. During the installation, thanks to untick the box "Drop existing tables (mode dev)".
![image](https://user-images.githubusercontent.com/16067358/45284906-fe300000-b4e1-11e8-8bc1-d4739926b747.png)

PS: You have to be completely sure, that the database is empty.
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
@Trylam, P restaShop is not compatible with PHP7.3.
We recomanded that you run your PrestaShop install on the version of PHP7.1 / PHP7.2.
PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 is compatible with PHP 7.2.
For more details you can follow this link http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

**Comment by Trylam** [comment]
@khouloudbelguith 

With the check box :

    Create file parameters
    Create database tables

An error occurred during installation...

edit :  i m sure for the database

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

    1: HTTP 0 - error - 


-----
php 7.3 is stable ...
I have a 1.7.4.0 version install (before 7.3 php version) on an other computer with same system configuration and i don't see trouble (quick check).
there is no ci test with beta version of php ? (i m pretty new with prestashop)

**Comment by Trylam** [comment]
I check database and the last one table order by name is  zone_shop .
I don't know if you create table and index at the same time so it may not help.

**Comment by khouloudbelguith** [comment]
@Trylam, could you please try with this link https://github.com/sstalle/php7cc to check php7 compatibility.
Thanks to follow this steps:

1. Login to your phpMyAdmin or wherever you can have a look at you database: delete all the tables, to make sure the database is empty.
2. Open the file prestashop > install > data > db_structure.sql in your editor (e.g. TextWrangler)
3. Replace all a.) with b.)
a. CREATE TABLE
b. CREATE TABLE IF NOT EXISTS
4. The error messages "table ps_[...] already exists" disappear. 

Thanks to check & feedback.

**Comment by Trylam** [comment]
Thanks for your answers. Finaly I install it in a VM (with php 7.0) and it's work.

**Comment by khouloudbelguith** [comment]
Hi @Trylam,

Thanks for your feedback.
Since it fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!
