### ISSUE TITLE
Weak Token Implementation

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#11751]
Thanks Jhon Ken.

1- Go to forgot-password in front office
2- Enter your email address and you will get one password reset token in your email. Call this token1.
3- No repeat step 1 and 2 and you will get another rest token. Call this token2
4- Now change password using token1 and you will be successfully log in from your new password.

All unused password reset token should be expired immediately with the issue of new token

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I manage to reproduce the issue with PS1.7.5.0rc1 also.
Thanks!
