### ISSUE TITLE
Fix ru lng СПСИОК

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#11760]
**Describe the bug**
СПСИОК replace Список

**To Reproduce**
1. Go to 'AdminTracking'
2. See error

**Screenshots**
![screenshot_3](https://user-images.githubusercontent.com/6318282/49932331-7a3c4880-ff14-11e8-8571-e7189a5ad98d.png)

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for your report.
What is the exact language/country did you use?
Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith 
![screenshot_1](https://user-images.githubusercontent.com/6318282/49935053-b32beb80-ff1b-11e8-9ee1-0b4e667c5696.png)

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0RC1 also.
![image](https://user-images.githubusercontent.com/16067358/49936196-9a97e300-fed3-11e8-87fa-3621ddb37499.png)
We will see how to fix it.

**Comment by PierreRambaud** [comment]
@LouiseBonnard Should it be on crowdin?

**Comment by LouiseBonnard** [comment]
Perhaps, but I need the English word first. @TemKaSD, what is it in English? Can you confirm you're on the Catalog > Monitoring part of the back office? You can also have a look at the Russian translation project [here](https://crowdin.com/project/prestashop-official/ru#). ;-)

**Comment by TemKaSD** [comment]
@LouiseBonnard 
![screenshot_7](https://user-images.githubusercontent.com/6318282/50038907-76bfd300-0074-11e9-8daa-2495e8234084.png)

English:
![screenshot_8](https://user-images.githubusercontent.com/6318282/50038957-7b38bb80-0075-11e9-8e0d-4e11ac5e50bb.png)

Fix:
СПСИОК (List)

Need to replace

Список (List)

**Comment by LouiseBonnard** [comment]
@TemKaSD, thanks a lot, I've spotted the mistake in the Crowdin catalog and brought the correction to the wrong wording, it should be effective in the software in the next few days. ;-)

**Comment by TemKaSD** [comment]
@LouiseBonnard thx
