### ISSUE TITLE
Enregistrement d'un produit en cours d'édition non exécuté à cause du champ "récapitulatif"

### ISSUE THREAD

**Issue by F-Zeayon** [PrestaShop/PrestaShop#11765]
Bonjour.

Par défaut, la limite du champ "récaputilatif" est de 800 caractères, je me baserai donc sur cette valeur pour la suite, bien que le problème soit sûrement le même quelque soit la limite.

Lorsque le texte saisi dans le champ "récapitulatif" d'un produit en cours d'édition est proche de la limite du nombre de caractères autorisés, l'appui sur le bouton "enregistrer" n'exécute pas l'enregistrement, même si le message apparaissant indique un enregistrement avec succès.

De plus, si on a dépassé une fois la limite du nombre de caractères, il n'est plus possible d'enregistrer sans quitter le produit en cours d'édition et d'y revenir pour terminer l'édition, malgré le message d'enregistrement avec succès.

Ceci génère également la perte de la saisie de tous les autres champs du produit.

En fait, cette limite inclut les caractères html (champ de la base de données certainement bridé à la même limite). De ce fait, dans l'exemple de l'image jointe, j'ai saisi 796 caractères mais le champ n'est pas enregistré car il y a plus de 800 caractères html (du fait des "< p >" et < /p >").

Une première solution peut être d'indiquer le nombre total de caractères saisis, caractères HTML compris, bien que cela ne corrige pas le problème d'enregistrement successifs inopérants malgré le retour à un nombre de caractères inférieur à la limite.
Note : le problème est peut-être le même pour tous les champs dont le nombre de caractères est limité 
et pour lesquels un formatage HTML est applicable.

![prestashop_bug_recap_produit_donnees_masquees](https://user-images.githubusercontent.com/45851101/49942843-b8bb0e80-fee6-11e8-9ea8-e3d910c738a9.jpg)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.24

**Comment by khouloudbelguith** [comment]
Hi @F-Zeayon,

Thanks for your report.
This issue is fixed in the PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1AeS39akGFIsAy40dMKLg9vo4nEZYlOBB/view
Thanks to check & feedback.

**Comment by F-Zeayon** [comment]
Hello.

The videos shows some kind of solution but not clear for non programmer users.
That said, the "save" command is no more silently inhibited wich was the major issue here.

We can probably state that it is a fix but it could be more elegant.

**Comment by khouloudbelguith** [comment]
Hi @F-Zeayon,

we have just published the Release Candidate of PrestaShop 1.7.5.0.
So, take a minute and read all about this release here: http://build.prestashop.com/news/prestashop-1.7.5-rc-release/
So the stable version will be released in a short time.
Thanks!
