### ISSUE TITLE
Brands yes, supplier NO

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11786]
I believe that for any merchant, showing their brands is excellent and producers; but showing own suppliers is not good, it can be the object of competition!
So I think it is better to separate in the backoffice (general setup) the enabling of brands different from the enabling / disabling of suppliers.

**Comment by BenTen** [comment]
Hello,
There is another ticket about this setting, you can read it #11332

**Comment by khouloudbelguith** [comment]
Duplicate of #11332

**Comment by centoasa** [comment]
it's possible disallow robot to add suppliers to search engine?
How to?
