### ISSUE TITLE
Warehouse

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11794]
Hi,
Do you plan (if yes ... when) to restore the warehouse stock management ?

Thx for your answer.
Guillaume

Version 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

We plan to release and sell an embedded ERP module that will do just what you need, ie routing warehouses with carriers and customer addresses.
You can follow our work on our dev blog :
http://build.prestashop.com/news/stock-management-in-prestashop-1-7/ http://build.prestashop.com/news/stock-management-in-prestashop-1-7-part-2/
http://build.prestashop.com/news/stock-management-in-prestashop-1-7-part-3/
Stay tuned for the next articles and the launch date of the ERP modules.
