### ISSUE TITLE
Number of color variants count shows wrong on category page

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#11797]
**Describe the bug**
There is wrong count shows (+92) and on product page there is only (49). There is also 49 combination saved on back-office also. When I check in inspect element there are +92 color variants links. Other products shows right count on category page. Is there any wrong configuration from my side? Can you help me to find the reason?

**Screenshots**
**On category page**
![1](https://user-images.githubusercontent.com/40850132/50134925-52543880-02b8-11e9-943b-acc64221c53e.png)
**On product page**

![2](https://user-images.githubusercontent.com/40850132/50134929-56805600-02b8-11e9-95d3-6ea8f877fea3.png)

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @Akashvastarpara,

I did not manage to reproduce the issue with the last version PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1Ykmf5scR0sJBWjh74Djx3Iq3eSv0rdw9/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith  Can I share you Back-office details?

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, 
This is a public space.
You can share me your Back-office details by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith Have you received mail with credential details?

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, I just received the email, I will check & feedback.
Thanks!

**Comment by Akashvastarpara** [comment]
Okay. Thanks in advance. @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, this issue occurs only with this product (10X20CM METRO "AMARANDA")?
Thanks!

**Comment by Akashvastarpara** [comment]
Not only one @khouloudbelguith , There is other products also. 
13x13cm "spaanse" witjes, glans
10x10cm liso, gladde glanzende finish
10x10cm getrommeld glans
10x10cm liso, gladde mat finish

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, I enabled debug mode in your shop but I don't get any information or any exception.
We need to retrieve the PHP error log in order to find out what's wrong.
Thanks!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith  I don't know how to send it. But I can share FTP details via mail.

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith I have shared error.log file via mail.

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, in your log file, I found some issue with your theme "bizkickpro".
Also, you have some issues with your module "ht_promotionbar".
Thanks to check the issue with your theme author & feedback.
In my case with default theme & PS1.7.5.0, I did not manage to reproduce the issue.
Thanks!

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith do you think theme and module promotion bar causing this combination issue?

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, in the error log file I found some issues with this theme & the module.
We need to check if they are really causing this issue.
Thanks!

**Comment by dineshbadrukhiya** [comment]
@Akashvastarpara try to disable that module and your installed theme.

**Comment by Akashvastarpara** [comment]
@khouloudbelguith I have disabled module and checked with classic theme but issue was still there.

![tc](https://user-images.githubusercontent.com/40850132/50199631-14b6e480-0378-11e9-9a9d-a9eea883bcfc.png)

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, to be sure of your issue if you create a new product with the same combinations or your duplicate this product.
The issue occurs again?
Thanks!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith Same issue again.

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, did you create a new product or just duplicate an old product?
Thanks!

**Comment by dineshbadrukhiya** [comment]
@Akashvastarpara Can you please share generated combination screenshot from back-office?

**Comment by Akashvastarpara** [comment]
@khouloudbelguith I have tried both the way. But still same for the products.

@dineshbadrukhiya 

![untitled](https://user-images.githubusercontent.com/40850132/50279277-41015c80-046f-11e9-8f4b-d5647ffe1034.png)

**Comment by dineshbadrukhiya** [comment]
@Akashvastarpara If I'm not wrong, you have 50 combination and in each combination it seems you have added two colors which looks same. So as +92 is count of variant links not a count of no of combination. As you have used two color for each combination, it means total count is 100 for variant links of your color attributes. I think that's why its showing +92 count.

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith wdyt?

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, no I don't think that it is the whole issue, I tried with PrestaShop 1.7.4.4 & I did not manage to reproduce the issue
https://drive.google.com/file/d/18pNiDkMejNmjD54JE2coUbEWbXh1g0rX/view
Thanks!

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith he used both the  comple and Omschrijving attribute for color. Just make two atrribute  of color and make combination as he made. and see the count.

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith I managed to reproduce the issue on 1.7.5.0
Make two attributes (For example: attribute1 & atrribute2) for color and then add the same value of color (Red and Black)for both the attribute. Now generate the combination, delete the combination which have different color of pair. So Remaining 2 combination have pair of same color.
For example:
Combination A: attribute-1: Red, attribute2:Red
Combination B: attribute-1: Black, attribute2:Black
Now see on front-office, there will be 4 color variants.

**Comment by khouloudbelguith** [comment]
Hi @Akashvastarpara

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/50292207-d05b3f80-0470-11e9-86ca-7cd46ebb3b03.png)
But, I think it is normal behavior because for this product we have 4 colors with two attributes.
That's why we have displayed the four colors.
@marionf what do you think? it is normal behavior or a bug.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith Yes, that's a normal behavior
