### ISSUE TITLE
probleme tracking temps réel google analytics

### ISSUE THREAD

**Issue by lily-anncurve** [PrestaShop/PrestaShop#11803]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by lily-anncurve** [comment]
Bonjour,

Nous travaillons avec la société Pumpup pour nos campagnes Google Ads et Google Shopping. Jusque-là, notre compte Ads était correctement relié à notre compte Google Analytics.

Depuis le 1er décembre environ, nous ne recevons plus de données sur notre compte Analytics et il est impossible de tracker les utilisateurs du site.

Voici le message que nous avons reçu de notre agence : Je reviens vers vous pour informer que nous avons des problèmes de remontées sur Analytics. 
- Depuis le 01 Décembre nous ne trackons plus l'ensemble des utilisateurs de votre site. Seule la source "Direct" semble être active. 
- En analysant l'onglet "Temps Réel", celui-ci m'indique 0 utilisateur actif sur le site, alors que je suis sur votre Home Page.

En pièce jointe, vous trouverez une capture d’écran du problème et de l’onglet « temps réel » sur Analytics.

Merci d’avance pour votre aide,

Cordialement,

**Comment by lily-anncurve** [comment]
![capture d ecran 2018-12-17 a 09 41 28](https://user-images.githubusercontent.com/45966481/50149537-c3491f80-02bb-11e9-9932-af7fa95dbf7b.png)

**Comment by khouloudbelguith** [comment]
Hi @lily-anncurve,

Thanks for your report.
What is the exact version of the ps_googleanalytics module did you use?
We need to provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by lily-anncurve** [comment]
Prestashop 1.7.3.2
Module Analytics 3.1.3
No access to the log files.

**Comment by khouloudbelguith** [comment]
@lily-anncurve,  We need PHP error logs in order to find out what's wrong. If you don't have it, you should ask your hosting provider.
Thanks!

**Comment by lily-anncurve** [comment]
sorry i don't know where to find it !!!!!!

**Comment by khouloudbelguith** [comment]
@lily-anncurve,

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by lily-anncurve** [comment]
https://we.tl/t-3Gjf3dOzTG

**Comment by khouloudbelguith** [comment]
@lily-anncurve, in my case, I did not manage to reproduce the issue with Google Analytics  v3.1.3 - by PrestaShop.
![image](https://user-images.githubusercontent.com/16067358/50282665-d42c9900-0453-11e9-9e4c-8ce4e64a1ecc.png)
Also, can you please provide a valid zipped file, I can not unzip your last file.
Thanks for your understanding!

**Comment by lily-anncurve** [comment]
[lily-ann.fr-19-12-2018.log](https://github.com/PrestaShop/PrestaShop/files/2698833/lily-ann.fr-19-12-2018.log)

**Comment by khouloudbelguith** [comment]
Hi @lily-anncurve,

In your file log, I find this error `H00687: Negotiation: discovered file(s) matching request`
Did you installed any module to edit the schema of URLs of your shop?
If no, did you enabled mod_negotiation and MultiViews on your server configuration?
Thanks!

**Comment by lily-anncurve** [comment]
merci beaucoup!!! pensez vous que ca a un rapport avec google site map?
je ne l'ai pas configurer

**Comment by lily-anncurve** [comment]
![image](https://user-images.githubusercontent.com/45966481/50336400-672a0980-050e-11e9-9b01-4b659214ec48.png)

**Comment by lily-anncurve** [comment]
![image](https://user-images.githubusercontent.com/45966481/50337302-f89a7b00-0510-11e9-8a2b-a43849fe0262.png)

**Comment by khouloudbelguith** [comment]
HI @lily-anncurve,

I don't think so, I tried to uninstall the gsitemap module => OK, no errors
![image](https://user-images.githubusercontent.com/16067358/50339130-e1f72280-0516-11e9-9d2f-f523e69fbb27.png)
I tried also to install the gsitemap module => OK also.
Could you please try to re-install the Google Analytics module.
You need to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by lily-anncurve** [comment]
encore merci mais finalement mon webmaster a régler le probléme en changeant la balise de place et manuellement.
merci a vous!!!!!

**Comment by khouloudbelguith** [comment]
Hi @lily-anncurve,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
