### ISSUE TITLE
Problem with ps email alerts

### ISSUE THREAD

**Issue by aurelcomypunto** [PrestaShop/PrestaShop#11805]
**Describe the bug**
Th ps email alerts modules doesn't works properly, 
PLease help us to confuigure it from scratch
Maybe it would help to configure smtp 

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @aurelcomypunto,

Thanks for your report.
Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
What is the exact version PrestaShop did you use & what the exact version of the mailalert did you installed?
Thanks to check and feedback.

**Comment by aurelcomypunto** [comment]
Hi there,We be already solved it. There was an error in SMTP parameters and we were fighting to discover where PrestaShop sotred ItMany thanks!Kind regards"Más vale una palabra potente que mil vacías de sentido." COMYPUNTO-------- Message original --------Objet : Re: [PrestaShop/PrestaShop] Problem with ps email alerts (#11805)De : khouloudbelguith À : PrestaShop/PrestaShop Cc : aurelcomypunto ,Mention Hi @aurelcomypunto,
Thanks for your report.
Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
What is the exact version PrestaShop did you use & what the exact version of the mailalert did you installed?
Thanks to check and feedback.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PrestaShop/PrestaShop","title":"PrestaShop/PrestaShop","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/PrestaShop/PrestaShop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@khouloudbelguith in #11805: Hi @aurelcomypunto,\r\n\r\nThanks for your report.\r\nCould you please try to navigate to your BO =\u003e CONFIGURE =\u003e Advanced Parameters =\u003e E-mail =\u003e TEST YOUR EMAIL CONFIGURATION by sending a test email.\r\nWhat is the exact version PrestaShop did you use \u0026 what the exact version of the mailalert did you installed?\r\nThanks to check and feedback."}],"action":{"name":"View Issue","url":"https://github.com/PrestaShop/PrestaShop/issues/11805#issuecomment-448213851"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PrestaShop/PrestaShop/issues/11805#issuecomment-448213851",
"url": "https://github.com/PrestaShop/PrestaShop/issues/11805#issuecomment-448213851",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khouloudbelguith** [comment]
@aurelcomypunto, since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!
