### ISSUE TITLE
BO - Catalog - Stock weird generated URL

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#11807]
**Describe the bug**
When I tried to open Catalog > Stock page, I see the dashboard page and the URL is quite weird :
http://myurlsite.com/adminfolder/index.php/stock/index.php?controller=AdminDashboard&token=...

**To Reproduce**
1. Go to Back-office
2. Click on Catalog > Stock 
4. Look at the URL

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1

**Comment by khouloudbelguith** [comment]
HI @tii-bruno,

Here's the URL for the product page: 
http://shop_URL/admin-dev/index.php/sell/catalog/products?_token=KC4OEbmsTRPOTFweofoG_T1lmigfgKTekoFPOKb0Wm0

Here's the URL for the stocks page: http://shop_URL/admin-dev/index.php/sell/stocks/?_token=KC4OEbmsTRPOTFweofoG_T1lmigfgKTekoFPOKb0Wm0

What is the exact weird think?
PS: they are migrated pages.
Thanks!

**Comment by thalassa-web** [comment]
When I click on SELL >Catalog > Stock, I'm not redirected to the stock page.
But I'm stuck in the dashboard.
And if I click again, the URL become greater and greater :
http://shop_URL/admin-dev/index.php/stock/index.php/stock/index.php/stock/index.php?controller=AdminDashboard&token=
It's maybe a server problem, I don't manage it …
![capture](https://user-images.githubusercontent.com/29065423/50159605-63607200-02d7-11e9-8de5-e714a4a2ca92.JPG)

**Comment by khouloudbelguith** [comment]
@tii-bruno, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by thalassa-web** [comment]
I have the same diagnostics of you … In my internal 1.7.4.4 test server, I have no particular problem with the stock.
I saw that my client installed PrestaShop on a NGINX server …
My local PrestaShop runs on Apache … 
Is it possible that the rewrite rules or something is broken ?

**Comment by khouloudbelguith** [comment]
@tii-bruno, with nginx you can't use htaccess files in Nginx context, you need to write your own rules. The htaccess file is generated by PrestaShop but it's because Apache allows to use it. Unlike Nginx.
You can find an example here: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist
Thanks!

**Comment by thalassa-web** [comment]
Thank you, I close the ticket because I don't use Nginx. I give the informations to the webmaster …

**Comment by khouloudbelguith** [comment]
@tii-bruno, thanks!
Feel free to open a new one when needed.
Thanks!
