### ISSUE TITLE
An error is displayed "getimagesize(): php_network_getaddresses" when we try to change the status of the order to payment accepted

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11801]
**Describe the bug**
This issue occurs only when we use a docker environment.
Here's some information about the configuration
![image](https://user-images.githubusercontent.com/16067358/50147611-e32a1480-02b6-11e9-9cbb-72d759f24d62.png)
After creating an order from the FO, when we try to change the status of this order to payment accepted an error is displayed

```
Warning on line 126 in file /var/www/html/dev/PrestaShop/classes/pdf/HTMLTemplate.php
[2] getimagesize(): php_network_getaddresses: getaddrinfo failed: Name or service not known


Warning on line 126 in file /var/www/html/dev/PrestaShop/classes/pdf/HTMLTemplate.php
[2] getimagesize(http://prestashop.local/dev/PrestaShop/img/logo.png): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**To Reproduce**
You need to use an environment docker to reproduce the issue, not on the local
1. Go to FO
2. Create an order
3. Go to BO => Orders
4. Change the status of this latest order to payment accepted
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/50147923-87ac5680-02b7-11e9-9c54-f94268976d5c.png)

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1 / 7.0

**Comment by khouloudbelguith** [comment]
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11802 to fix the issue.
Thanks!

**Comment by eternoendless** [comment]
Looks like there's something wrong with the logo path, since it's tying to retrieve it using HTTP instead of using the local path:

```
Warning on line 126 in file /var/www/html/dev/PrestaShop/classes/pdf/HTMLTemplate.php
[2] getimagesize(http://prestashop.local/dev/PrestaShop/img/logo.png): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by khouloudbelguith** [comment]
Related to #11791
