### ISSUE TITLE
1.7.4.4 to 1.7.5.0 with autoupgrade

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11811]
Hello,

I just try to update from 1.7.4.4 to 1.7.5.0 with autoupgrade 4.5.1
In the end of the upgrade, I got a message.
https://tof.cx/image/HyrR4

> Error during database upgrade.
You already have the 1.7.5.0 version.

Is there a tool to check if the db is really upgrade correctly?

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

it could be that something went wrong with your update and don't have some of the database columns that were added for 1.7.5.
You can find the full schema for 1.7.5.0rc1 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0-rc.1/install-dev/data/db_structure.sql
You can find the schema changes from 1.7.4.4/1.7.5 by looking at this file:
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.5.0.sql
Thanks!

**Comment by BenTen** [comment]
I'm updating manually.

One of the module of my project modified a table of PS. Maybe it's for that (think)

And I don't have the table _groupe_reduction_cache
Is this table is created when we active the cache?


Btw, I can see in the table **PREFIX_order_detail** of [1.7.4.x](https://github.com/PrestaShop/PrestaShop/blob/1.7.4.x/install-dev/data/db_structure.sql)
` `product_supplier_reference` varchar(32) DEFAULT NULL,`

In the [1.7.5.x](https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/install-dev/data/db_structure.sql) it's var(64)
` `product_supplier_reference` varchar(64) DEFAULT NULL,`

But in the upgrade script 1.7.5.0.sql, there is not this CHANGE in this table.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

I checked a new installation of version PS1.7.4.4, the table `PREFIX_product_group_reduction_cache` exists, you can follow this [link](https://github.com/PrestaShop/PrestaShop/blob/3b60885165ef9df00a7952339285ebf4a1217a81/install-dev/data/db_structure.sql#L873)
We manage to reproduce some during the upgrade from PS1.7.4.4 to 1.7.5.0
Here's a fix https://github.com/PrestaShop/PrestaShop/pull/11814
Your ticket is a duplicate of #11812
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11812

**Comment by BenTen** [comment]
duplicate? where?

1/For my part the table was not upgrade and the message was:
"Error during database upgrade.
You already have the 1.7.5.0 version."
#11812 is totally different.

2/ I talk about the table order_detail, #11814 is not about that.

3/ about PREFIX_product_group_reduction_cache, my bad I didn't see it on my db (I forgot to update my ticket after found it)

It's not a request support  ticket, I updated manually, it's just a report.

**Comment by khouloudbelguith** [comment]
@BenTen, 

In your ticket, you mentioned about PREFIX_order_detail, which is the duplicate of this ticket #11812.
Now, about your issue, it could a permission issue during the upgrade, thanks to check & feedback.
Thanks!

**Comment by BenTen** [comment]
@khouloudbelguith yes but I said, in this table, "product_supplier_reference" need to be change to varchar(64).
It was a missing change.

It's now reviewed.
