### ISSUE TITLE
1.7.4.4 to 1.7.5.0 with 1-click upgrade

### ISSUE THREAD

**Issue by EV-soft** [PrestaShop/PrestaShop#11812]
The upgrade to the new version, finished with 3 warnings:

[**WARNING**] SQL 1.7.5.0 1060 in ALTER TABLE `psw_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '', CHANGE `employee_lastname` `employee_firstname` VARCHAR(255) DEFAULT '': **_Duplicate column name 'employee_firstname'_**
[OK] SQL 1.7.5.0 ALTER TABLE `psw_supplier_lang`...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_order_detail` ...
[**WARNING**] SQL 1.7.5.0 1060 in ALTER TABLE `psw_product` CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL, CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL: **_Duplicate column name 'supplier_reference'_**
[OK] SQL 1.7.5.0 ALTER TABLE `psw_product_attribute` ...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_warehouse` ...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_stock` ...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_supply_order_detail`...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_product_supplier`...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_product_lang`...
[OK] SQL 1.7.5.0 ALTER TABLE `psw_customer_thread` ...
[**WARNING**] SQL 1.7.5.0 1060 in ALTER TABLE `psw_stock_available` ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: **_Duplicate column name 'location'_**
Database upgrade OK

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @EV-soft,

Thanks for your report.
I manage to reproduce the issue with the 1-click upgrade v4.5.1 from 1.7.4.4 to 1.7.5.0.
The upgrade is done succeessfully with 3 warnings as Described by @EV-soft.
ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by eternoendless** [comment]
The warnings are not a serious problem. A fix is available in #11814
