### ISSUE TITLE
Error style BO PS 1.7.5.0

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11837]
Hi,
In BO on "Shop Parameters", there is a problem of style 
https://tof.cx/image/HTQVa

Best Regards

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

This is not a bug, it is a cache issue.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks!
