### ISSUE TITLE
The Symfony debug bar hides the action buttons on the product page

### ISSUE THREAD

**Issue by rGaillard** [PrestaShop/PrestaShop#11846]
**Describe the bug**
The Symfony debug bar hides the action buttons on the product page.

**To Reproduce**
1.  Enable the debug mode
2. Edit or create a new product 
3. Scroll down and search the action buttons

**Screenshots**
https://www.awesomescreenshot.com/image/3793613/088c75445bbdffd4296e9c35381812c2

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: N/A

**Comment by matks** [comment]
Hi @rGaillard,

The result will depend on your screen size, however if the debug bar is annoying for you when you use the Product page, you can toggle it using the "close toolbar" cross on the far right of the bar

**Comment by khouloudbelguith** [comment]
Hi,

When the window is lower than 1428px * 977px,
The Symfony debug bar hides the action buttons on the product page, it will be displayed like that
![image](https://user-images.githubusercontent.com/16067358/50222399-6cfdde80-0398-11e9-93b8-97fce90fa2d7.png)
When the window is between 1428px * 977px & 1450px * 977px,
The Symfony debug bar hides only a part of the action buttons on the product page
![image](https://user-images.githubusercontent.com/16067358/50222467-9dde1380-0398-11e9-99fb-d6a860dfb392.png)
Else, it will be displayed like that
![image](https://user-images.githubusercontent.com/16067358/50222491-b2baa700-0398-11e9-8905-f3c01cf7fac5.png)
Thanks!

**Comment by marionf** [comment]
As explained by @matks you can close the symfony toolbar, so no issue here
