### ISSUE TITLE
Error editing products with a too long product summary for a disabled language.

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#11848]
If you limit the short description size and you have a disabled language with a short description that exceeds the specified size, products are not saved anymore and no message is shown.

**To Reproduce**
1. Go to "International > Localization > Languages tab" and create a new language to the shop
2. Save a long Summary description for any product for the new language you've created (e.g., a description with 200 characters)
3. Go to "Shop Paramaters > Product Settings" and set "Max size of short description" to a shorter value than the size of the description you've just saved (e.g. 160)
4. Go back to "International > Localization > Languages tab" and deactivate the new language.
5. Go back to the product you have added the long summary, change something and save it.
You will be able to save, no message will be shown, but if you preview the product, no changes will have been made.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment]
Hi @rblaurin,

Thanks for your report.
I manage to reproduce the issue withPS1.7.4.4 but with PS1.7.5.0, it is fixed
I attached a video record.
https://drive.google.com/file/d/1ZvVxrgV5i2Pk8X1VBrBt0572EZ0zxfxp/view
Thanks!

**Comment by rblaurin** [comment]
Great! Thanks for the quick feedback
