### ISSUE TITLE
API error with php 7.2 (1.7.5.0)

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11840]
Hi,
Using PHP7.2 and prestashop 1.7.5.0 : just call the API like "youwebsite/api" enter your key .... the response return a 500 code. Probably the case with prestashop 1.7.4.4 ...

Thanks
Sorry same as https://github.com/PrestaShop/PrestaShop/pull/11649

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0 & PHPv7.2.
I attached a video record.
https://drive.google.com/file/d/1Wviq_BBueRS6mtFqoIBU70nnVeo4yoZ8/view
In your BO => Shop Parameters => Traffic & SEO page, did you enabled the Friendly URL option?
Thanks!

**Comment by grabelle** [comment]
Sorry, I was not clear.
Please call {{your-url}}/api/?output_format=JSON

**Comment by khouloudbelguith** [comment]
@grabelle,

No, it is OK.
https://drive.google.com/file/d/1o0Fo3AOZAH0UjWv8BQdCuJ4B4wixuAuj/view
Thanks!

**Comment by grabelle** [comment]
Version de PHP : 7.2.13-1+ubuntu16.04.1+deb.sury.org+1

Strange ...

code | 3
message | "[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable (/home/.........../classes/webservice/WebserviceOutputJSON.php, line 155)"

So I guess you don't return the warning in your config ?

**Comment by khouloudbelguith** [comment]
@grabelle, yes there are no warnings in my case.
With PHP 7.1 it is ok in your side?
Thanks!

**Comment by grabelle** [comment]
Yes it is ok with 7.1

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by matks** [comment]
@grabelle Looks like in DEV mode you have warnings that are being returned, and because of that the response you get is not a proper JSON document

Can you check in PRODUCTION mode to validate this hypothesis 🙏 ?

**Comment by grabelle** [comment]
You mean DEV mode in the performance parameter of prestashop ? if so ... no it is not in dev mode.
To avoid the warning, I modifyed my php.ini (not sure it's a good idea but it on a local server)

```
**before**
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**now**
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING
```

**Comment by khouloudbelguith** [comment]
@grabelle,

To turn off the Debug mode on PrestaShop 1.7, follow these steps:
Got to Advanced Parameters > Performance
In the Debug Mode section, set “Debug Mode” to “No”.
Click the “Save” button.
You can still enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', true);`

… and change it to:

`define('_PS_MODE_DEV_', false);`

Thanks!

**Comment by DelecroixQuentin** [comment]
Hello @grabelle, 

This fix works fine:
In classes/webservice/WebserviceOutputJSON.php

Change line 41:
`protected $currentAssociatedEntity;`

To:
`protected $currentAssociatedEntity = array();`
Or
`protected $currentAssociatedEntity = [];`

**Comment by khouloudbelguith** [comment]
@DelecroixQuentin,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!
