### ISSUE TITLE
the installation does not end 

### ISSUE THREAD

**Issue by Trylam** [PrestaShop/PrestaShop#11842]
**Describe the bug**
Prestashop is install in linux vm. We start creating a theme on another computer from the startertheme(with prestashop 1.7.4.0)  and we imported it from the prestashop which is on the vm. I have a sshfs mount in folder in my computer on the theme. I try to realise npm installation from my folder computer. npm has been reinstalled and the path to bin has been added. And when I try to install npm, the installation does not end (with command : npm run watch). 

**To Reproduce**
1.move to the _dev file (from the computer)
2. npm install
3. npm audit fix
4. npm run watch

**Screenshots**
Version: webpack 1.15.0
Time: 4036ms
           Asset     Size  Chunks             Chunk Names
        theme.js  2.12 kB       0  [emitted]  main
../css/theme.css   5.7 kB       0  [emitted]  main
   [0] multi main 76 bytes {0} [built]
    + 11 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Additionnal information**
PrestaShop version:  1.7.4.4
PHP version: 7.0
npm version : 6.5.0

**Comment by khouloudbelguith** [comment]
Hi @Trylam,

Thanks for your report.
Could you please run this command `npm run --watch`, check & feedback.
Thanks!

**Comment by Trylam** [comment]
It return to me :
```bash
$npm run --watch
Scripts available in new-theme via `npm run-script`:
  build
    webpack --progress -p
  watch
    webpack --progress --colors --watch
  debug
    webpack --progress --colors --debug --devtool source-map --output-pathinfo --display-chunks --watch

```

**Comment by khouloudbelguith** [comment]
Hi @Trylam,

I manage to reproduce the issue follwing these steps:
1. cd themes
2. git clone https://github.com/PrestaShop/StarterTheme.git YOUR_THEME_NAME
3. create theme.yml into the config folder
4. cd _dev
5. npm install
6. npm run watch

the installation does not end 
![image](https://user-images.githubusercontent.com/16067358/50230035-0aaed900-03ac-11e9-8620-5a75c52295bb.png)
Thanks!

**Comment by Quetzacoalt91** [comment]
This is an expected behavior of the `--watch` parameters. It keeps "watching" the changes you make on the project, and compile every time you save one of the files.

If you want to webpack to stop after it compiled all your assets, remove the `--watch` parameter.
