### ISSUE TITLE
Column 'message' in field list is ambiguous

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#11849]
**Describe the bug**
Into Clients > SAV page, I have the following warning (without debug mode):

> Il y a 2 avertissements.
>    IMAP configuration is not correct
>    Mauvaise requête SQL
>    Column 'message' in field list is ambiguous

And any message is displayed.

With debug mode enabled I've the following exception:

> [PrestaShopDatabaseException]
> Column 'message' in field list is ambiguous

complete message on screenshot:

![exception](https://user-images.githubusercontent.com/7419525/50226147-b6ebc200-03a2-11e9-85dd-e8c7157c6e86.png)

**To Reproduce**
1. Go to Clients > SAV
2. See warning "Column 'message' in field list is ambiguous"
3. Enable debug mode
4. See a exception

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
HTTP Server : Apache
PrestaShop version: 1.6.1.23
PHP version: 5.6.30
MySQL version: 5.6.25

**Comment by Klemart3D** [comment]
I fixed this exception by replacing into `controllers/admin/AdminCustomerThreadsController.php` file, line 242: `group_concat(message)` by "group_concat(cm.`message`)"

**Comment by matks** [comment]
@Klemart3D Nice 😄 ! Would you make a PR to submit this change ? I can do it but you would not get the credit you deserve for finding the solution

**Comment by khouloudbelguith** [comment]
HI @Klemart3D,

With a fresh installation PS1.6.1.23, I did not manage to reproduce the issue.
In the SAV page, did make any filter with which exact field?
Thanks!
Also, you can make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!
