### ISSUE TITLE
Setting show_price to off doesn't hide price in schema.org tags

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#11844]
**Describe the bug**

If you don't want to show prices in products, for eg. by setting show_price to No or hide prices for Group, it does not hide prices in schema.org tags

**To Reproduce**
1. Go to whatever Product you want and edit it
2. Turn on catalog mode and turn off showing price
3. Now save changes, visit product page and check source code of the page, you'll see:

```
<meta property="product:pretax_price:amount" content="35.9">
<meta property="product:pretax_price:currency" content="PLN">
<meta property="product:price:amount" content="44.16">
<meta property="product:price:currency" content="PLN">
```

even tho price should be not visible

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
I manage to reproduce the issue with the last version PrestaShop v1.7.5.0
I disabled show price in the customer Group page for all group.
When I check the source code of the product page, the price is visible.
![image](https://user-images.githubusercontent.com/16067358/50218262-95cba700-038b-11e9-852d-93a42634f373.png)
We will see how to fix it.
Thanks!
