### ISSUE TITLE
DeliverySlipPDF and InvoicePDF on Order Settings page

### ISSUE THREAD

**Issue by D2Red** [PrestaShop/PrestaShop#11855]
**Describe the bug**
on the order settings page, in the column PDF the shop displays no Icon fpr Invoice and  DeliverySlip.
in the pic "orders.png" you can see that some orders have a invoice-icon
and some order have invoice-icon and deliveryslip-icon.
but the most have no icon.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1
![orders](https://user-images.githubusercontent.com/45538290/50239606-f4604780-03c2-11e9-9978-dbe0dae00a59.png)

**Comment by khouloudbelguith** [comment]
Hi @D2Red,

You can get many PDF documents out of the order page.

You can get an invoice for the order by clicking on the "Generate invoice" button from the "Documents" section. The invoice is also generated once you put the order in the "Payment accepted" status.
Once it is generated, the "View invoice" button below gets activated the top-bar. => so, the invoice-icon will be displayed.
![image](https://user-images.githubusercontent.com/16067358/50272449-219b0d00-0438-11e9-9a4f-bd142a91a811.png)

When you put the order in the "Processing in progress" state, a delivery slip PDF is generated, which you can then download from the "Documents" section => so, the deliveryslip-icon will be displayed.
![image](https://user-images.githubusercontent.com/16067358/50272551-6fb01080-0438-11e9-95e4-9c4b965f31e3.png)

In the other case, where you don't have any document generated for this order, it will not have any icon.
![image](https://user-images.githubusercontent.com/16067358/50272406-f4e6f580-0437-11e9-9784-ececee811ace.png)

In the BO => Shop Parameters => Order settings page => Statuses Tab, you can see all statuses, you can check for each status, you can find many options for each status.
Thanks!

**Comment by D2Red** [comment]
hello,

the problem is that an invoice an Delivery Slip is available.
![order](https://user-images.githubusercontent.com/45538290/50305528-6011e580-0493-11e9-9d6a-b73278310bc5.png)
as seen in this order.
But the "view Invoice" and "view DeliverySlip" Icons are not shown.

In this order both icon schown in the overview and in the order.
![order1](https://user-images.githubusercontent.com/45538290/50305668-d31b5c00-0493-11e9-9541-505a81e748db.png)

this is the Order settings page => Statuses Tab
![order2](https://user-images.githubusercontent.com/45538290/50305785-386f4d00-0494-11e9-990e-8617d236ae63.png)

When the Icons are not shown, in the Dashboard is not Sale registered.
![order3](https://user-images.githubusercontent.com/45538290/50305999-b29fd180-0494-11e9-8fb1-ecf8516dbd60.png)

best regards

**Comment by khouloudbelguith** [comment]
Hi @D2Red,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @D2Red,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
