### ISSUE TITLE
Create EmailTemplateGenerator with classic theme

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#11878]
**Is your feature request related to a problem? Please describe.**
PrestaShop Core needs to generate its email static templates independently. Today those templates are downloaded from i18n.prestashop.com

**Describe the solution you'd like**
Create new service `EmailTemplateGenerator`
- `generateTemplates($theme, $language, $type)` (returns the template as string)
- `generateTemplate($heme, $language, $type, $template)` (returns the template as string)

Create new service `EmailTemplateExporter`
- `exportTemplates($templateContent, $language, $type)` (writes the template in the appropriate files)
- `exportTemplate($templateContent, $language, $type, $template)` (writes the template in the appropriate file)

Classic theme (legacy mails)
- integrate template from `ps_emailgenerator` in twig format

The service is able to generate the same templates as the module `ps_emailgenerator` including those for native modules.

**Comment by jolelievre** [comment]
The scope of this issue got bigger because the Generator actually needs the `EmailTemplateCatalog` introduced in this issue https://github.com/PrestaShop/PrestaShop/issues/11880
Although the service won't be integrated in the controller in this issue, so they are linked but not merged

**Comment by jolelievre** [comment]
I just created a PR for this issue, it contains the basic implementation of this feature and only one template integrated for now. I have a few questions about this code and I'd like feedback from @PrestaShop/prestashop-core-developers or any contributor

Here are my questions:
- mail themes folder: {PS_ROOT_DIR}/mails/themes? {PS_ROOT_DIR}/mail-themes?
- theme info are from convention with folder structure or with config (json file):
    themes
        - classic
            - core
                - html
                    account.html.twig
                - txt
                    account.txt.twig
            - modules
                - followup
                    - html
                        followup1.html.twig
                        followup2.html.twig
                    - txt
                        followup1.txt.twig
                        followup2.txt.twig
                - ps_reminder
                    - txt
                        outofstock.txt.twig

- namespace architecture: for now everything is in PrestaShopBundle/Service/Mail, I'm thinking nearly everything could be in Core/MailTemplate
except the MailTemplateRenderer which uses twig (an additional interface would be need MailTemplateRendererInterface)
- Exceptions? for now I use the `PrestaShop\PrestaShop\Core\Exception\InvalidException` in all the components, should we have a more refined exception management? specific to this domain? or create more generic exceptions like `InvalidArgumentException`, `FileNotFoundException`, ...

- needed hooks?
    - MailTemplateCatalogInterface
        - listTemplates => actionListMailTemplatesTemplates (with a MailTemplateCollectionInterface as argument)
    - MailTemplateParametersBuilderInterface
        - buildParameters => actionMailTemplateBuildParameters (with the parameters array as reference to allow editing it)
    - (maybe) MailTemplateRendererInterface
        - render => actionMailTemplateRender (with the core rendered template, allow to modify it for wrapping or replacing text)

**Comment by Quetzacoalt91** [comment]
Could mails templates be provided by theme developers?

You could keep the current folder `/mails` as base, and allow each theme to bring its own template in `/themes/<theme_name>/mails`.

**Comment by jolelievre** [comment]
The thing is mail themes are not necessarily linked to a PrestaShop theme, I would prefer to keep them separated which is why they should not be stored as a theme subfolder

**Comment by PierreRambaud** [comment]
Mails themes are not necessarily linked to a FO theme, but it can. 
How to install mails themes otherwise?

**Comment by jolelievre** [comment]
Well there are actually two different "notions" here, the theme I'm talking about here are "templates themes" which are a collection of twig templates used to generate mail templates exported as html or txt files

It does not change the way mails are used, it simply changes the way they are generated for now
Instead of download the mail templates from an archive stored on our server they are generated base on these "mail templates theme"

I don't know if it's clear enough.. But anyway it means that the template generator will export the mail templates in default folders but you can still override them via a theme. It is not manage by the Mail class which is not supposed to change for now.

However in the future (probably not before a major version) the static files should disappear and the mail contents will be rendered on the fly.

Maybe the wording is ambiguous here and we should find better words to define "mail templates" (static html/txt files) from "mail templates basic layout twig files" (used in the new generation process)

**Comment by colinegin** [comment]
#12046
