### ISSUE TITLE
Override removes old override if not in class_index

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#11874]
**Describe the bug**

**To Reproduce**
1. Override class Product manually. Copy the following code at `/overrides/classes/Product.php`

> class Product extends ProductCore
> {
>     public function getFieldsShop()
>     {
>         return parent::getFieldsShop();
>     }
> }

2. Don't clear cache
3. Install attached module
4. Installation has removed getFieldsShop function from override

[dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2698649/dummymodule.zip)

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by idnovate** [comment]
If you clear caché after step 1 the problem is fixed. What I propose is to clear cache/regenerate class_index before module installation.

**Comment by khouloudbelguith** [comment]
HI @idnovate,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0/ 1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1Mpafp1UyvnpZUEXbGAhBoATCXJw_nW_f/view
Thanks to check & feedback.

**Comment by idnovate** [comment]
Here's my screencast :)

https://drive.google.com/file/d/1zL4HQGcESTmIsWJqTAJ1sFeZrPRF8OPV/view

I tried with a fresh PS 1.7.5.0, but I also reproduced in PS 1.7.4.

There's another difference, and it's that the module has not been enabled in your installation, while in mine it was enabled automatically.

This is my Performance config:
![image](https://user-images.githubusercontent.com/15104724/50288973-c8e36880-0467-11e9-8fa6-e5307e63268b.png)
As I told you I just installed the version and have not modified anything.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

ni, after the installation of the dummymodule, I checked it, it enabled.
Here's a video record with PS1.7.4.4
https://drive.google.com/file/d/1da24sVdAQ0BzoMcsV9S02t60XdqfHJRL/view
Thanks!

**Comment by idnovate** [comment]
Hi!

Something's wrong with your second test. You have installed the module, the module is enabled but the override has not changed.

**Comment by idnovate** [comment]
I tried again with PS 1.7.5.0 and I always reproduce it:

- Uninstall and remove module "dummymodule".
- Clear cache
- Create manually /override/classes/Product.php with a function overrided.
- Install module "dummymodule"

Module is installed and enabled by default, and Product.php function has been removed with the override from the module.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I tried again with a fresh installation PS1.7.5.0 & PS1.7.4.4, but I cannot manage to reproduce the issue.
@marionf, can you please try to reproduce the issue?
Thanks!

**Comment by idnovate** [comment]
Pleas note I installed Spanish localization although I think it should not affect.

I'm running PHP 7.1.16 with WAMP.

**Comment by khouloudbelguith** [comment]
@idnovate, thanks for this specification.
I fact, it had an effect.
With a fresh installation PS1.7.5.0  with Español (Spanish) language & Spain country, I manage to reproduce the issue.
But with fresh installation 1.7.4.4 with Español (Spanish) language & Spain country, the getFieldsShop function is not removed from the override.
Thanks!

**Comment by idnovate** [comment]
> I fact, it had an effect.

Interesting :open_mouth:

**Comment by khouloudbelguith** [comment]
Hi, @idnovate,

As discussed with @PierreRambaud, we have made some tests & we did not manage to reproduce the issue with PS1.7.5.0 ( Spain country also).
This code line 
```
<?php
class Product extends ProductCore { public function getFieldsShop() {
return parent::getFieldsShop();
}
}
?>
```
is not removed from the Product.php after installing the dummymodule.
https://drive.google.com/file/d/1ra0eLVNIteiUie0-UiKsaLWnJnnRBDRi/view
Thanks!
