### ISSUE TITLE
Undefined offset error, In Post method of Web-services of Prestashop

### ISSUE THREAD

**Issue by amansrivastava8355** [PrestaShop/PrestaShop#11871]
Undefined offset error, In Post method of Web-service of Prestashop, while using **output_format JSON**
[Error Screnshot](https://prnt.sc/lxc5nz)

**Comment by khouloudbelguith** [comment]
Hi @amansrivastava8355,

Thanks for your report.
Heres' a fix https://github.com/PrestaShop/PrestaShop/issues/11840#issuecomment-448635878 to solve your issue.
Your ticket is a duplicate of #11840
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11840
