### ISSUE TITLE
Hook reset during theme upgrade (1.7.5 from 1.7.4.4)

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11873]
Hi
upgrading from 1.7.4.4 the previous hook are reseted to default
I've reported it on another bug report but I don't find it again
it should be fixed on the 1.7.5 but it is not so

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Is it this issue reported before http://forge.prestashop.com/browse/BOOM-3195?
Thanks!

**Comment by Maofree** [comment]
can you import it on github?
when will be fixed it?
at this moment each time I upgrade prestashop 1.7 I need to backup all hook tables, then remove them and import the previous tables

**Comment by khouloudbelguith** [comment]
@maofree, I have the same issue with the 1-click upgrade v4.5.1.
Steps to reproduce the issue
1. Install PS1.7.4.4
2. Install the ps_bestsellers module & ps_newproducts module
3. check in the FO => They are well displayed
4. Upgrade to PS1.7.5.0 with the 1-click upgradev4.5.1 => OK
5. Enable shop
6. check FO => The two blocks are not displayed

@marionf, what do you think?
Thanks!

**Comment by Maofree** [comment]
hi
this error is present from many months
I understood that it was solved on 1.7.5, I don't know why, there is something in the upgrade module that reset all hooks except few modules

**Comment by khouloudbelguith** [comment]
@maofree, yes, I tried with some other modules but they are ok.
For example ps_checkpayment, ps_contactform, ps_banner,...

But with ps_bestsellers module & ps_newproducts module => NOK.
Thanks!

**Comment by Maofree** [comment]
it is due on the hooks, not from the modules
like diplayhome or displayleft and right

**Comment by Maofree** [comment]
it happens the same on my modules but not all, just for that modules that they use these hooks. I don't know the complete hook list with this problem.

**Comment by khouloudbelguith** [comment]
@maofree, thanks for your feedback.

**Comment by marionf** [comment]
It's also the case for ps_viewedproduct module

**Comment by Quetzacoalt91** [comment]
See https://github.com/PrestaShop/autoupgrade/pull/288
