### ISSUE TITLE
Wrong Product page title when multiple languages

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#11889]
**Describe the bug**
The product page title is not retrieved correctly when there is more than 1 language

**To Reproduce**
1. Fresh installation of **SPANISH** PS 1.7.5.0 (4 languages by default)
2. Open a product
3. Check title

**Screenshots**
![image](https://user-images.githubusercontent.com/15104724/50336405-6a24fa00-050e-11e9-9e71-f747ec84635c.png)

**Additionnal information**
PrestaShop version: PS 1.7.5.0 with Spanish localization

**Comment by idnovate** [comment]
Problem is that `id language` is not sent to all the functions:

Stacktrace:

1.  `ProductControllerCore` controller:
```
public function getTemplateVarPage()
{
    $page = parent::getTemplateVarPage();
    ...
}
```
2. `FrontControllerCore` class:
```
public function getTemplateVarPage()
 {
    $page_name = $this->getPageName();
    $meta_tags = Meta::getMetaTags($this->context->language->id, $page_name);
    ...
}
```
3. `Meta` class:
```
public static function getMetaTags($idLang, $pageName, $title = '')
{
    if (Configuration::get('PS_SHOP_ENABLE')
    || in_array(Tools::getRemoteAddr(), explode(',', Configuration::get('PS_MAINTENANCE_IP')))) {
    if ($pageName == 'product' && ($idProduct = Tools::getValue('id_product'))) {
        return Meta::getProductMetas($idProduct, $idLang, $pageName);
    ...
}
```
4. `Meta` class:
```
public static function getProductMetas($idProduct, $idLang, $pageName)
{
    $product = new Product($idProduct, false, $idLang);
    if (Validate::isLoadedObject($product) && $product->active) {
        $row = Meta::getPresentedObject($product);
        if (empty($row['meta_description'])) {
            $row['meta_description'] = strip_tags($row['description_short']);
        }

        return Meta::completeMetaTags($row, $row['name']); // Here's the problem, no $idLang!!
    }

    return Meta::getHomeMetas($idLang, $pageName);
}
```
5. `Meta` class:
```
public static function completeMetaTags($metaTags, $defaultValue, Context $context = null)
{
    if (!$context) {
        $context = Context::getContext();
    }

    if (empty($metaTags['meta_title'])) {
        $metaTags['meta_title'] = $defaultValue;
    }

    return $metaTags;
}
```

6. Value for `$page['meta']['title']` at line 1262 **after calling** `$page = parent::getTemplateVarPage();` at function `getTemplateVarPage` from controller `ProductController`:
```
array:4 [▼
  1 => ""
  2 => ""
  3 => ""
  4 => ""
]
```

7. Value for `$page['meta']['title']` **at the end** of function `getTemplateVarPage` from controller `ProductController`:

`"Array Dimension 40x60cm"`

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I tried a new fresh installation PS1.7.5.0 with `Español (Spanish)` language & Spain country, but I did not manage to reproduce the issue.
I attached a screenshot
![image](https://user-images.githubusercontent.com/16067358/50340827-cd1d8d80-051c-11e9-8f7a-a725f2100531.png)
Thanks to check & feedback.

**Comment by idnovate** [comment]
Another related error when DEBUG mode is enabled. Please note that it expects a string and an array is given.

![image](https://user-images.githubusercontent.com/15104724/50510829-7f100900-0a8b-11e9-80e3-1d117f104d25.png)

**Comment by idnovate** [comment]
Could you please edit file `/src/Adapter/Image/ImageRetriever.php` and print `$object->name`  in function `getImage()` around line `173`?

```
foreach ($image_types as $image_type) {
    $resizedImagePath = implode(DIRECTORY_SEPARATOR, [
        $imageFolderPath,
        $id_image . '-' . $image_type['name'] . '.' . $ext,
    ]);

    if (!file_exists($resizedImagePath)) {
        ImageManager::resize(
            $mainImagePath,
            $resizedImagePath,
            (int) $image_type['width'],
            (int) $image_type['height']
        );
    }

    dump($object->name); //Modification

    $url = $this->link->$getImageURL(
        isset($object->link_rewrite) ? $object->link_rewrite : $object->name,
        $id_image,
        $image_type['name']
    );

    $urls[$image_type['name']] = [
        'url' => $url,
        'width' => (int) $image_type['width'],
        'height' => (int) $image_type['height'],
    ];
}
```

My output:
```
array:5 [▼
  1 => "The adventure begins Framed poster"
  2 => "The adventure begins Framed poster"
  3 => "The adventure begins Framed poster"
  4 => "The adventure begins Framed poster"
  5 => "The adventure begins Framed poster"
]
```

**Comment by khouloudbelguith** [comment]
Hi, @idnovate,

I tried with another fresh installation PS1.7.5.0 & it is OK.
https://drive.google.com/file/d/1O2kzaOA-I6PIM4DbbhJdPfAMKvuE-XT6/view
![image](https://user-images.githubusercontent.com/16067358/50512852-9c95a080-0a94-11e9-825d-a9f5d0e4a479.png)
I tried with your modification & I have the same result as you
![image](https://user-images.githubusercontent.com/16067358/50512886-e1b9d280-0a94-11e9-88e5-77d95176f46b.png)
Thanks!

**Comment by idnovate** [comment]
I couldn't reproduce the issue again with a new PS 1.7.5.0 installation.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
