### ISSUE TITLE
Error 500 - Disable product with a too long short description

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#11887]
If you limit the short description size and you already have products that exceed the new limit, an Error 500 is thrown when trying to disable the product by clicking in the "tick" icon in product listing.

To Reproduce

1. Save a long Summary description for any product (e.g., a description with 200 characters)
2. Go to "Shop Paramaters > Product Settings" and set "Max size of short description" to a shorter value than the size of the description you've just saved (e.g. 160)
2. Go to "Catalog > Products" and try to disable it directly in the product listing by clicking on the tick icon of the "state" column.

An Error 500 will be thrown.

Additional information
PrestaShop version: 1.7.5.0
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment]
Hi @rblaurin,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 / PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/50331401-c7b14a80-04fe-11e9-8e55-e18759a4ffcd.png)
We will see how to fix it.
Thanks!

**Comment by rblaurin** [comment]
This error also occurs if you try to duplicate the product (3rd step) instead of disabling it. (Tested in 1.7.5.1)

**Comment by khouloudbelguith** [comment]
@rblaurin, the issue is not fixed yet, it is added tour bug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
