### ISSUE TITLE
Token error not managed in module page

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#11883]
**Describe the bug**
When token has expired and you do some action with modules, it doesn't appear any AJAX error.

**To Reproduce**
1. Go to Modules page
2. Open another tab
3. Logout employee session in the 2nd tab*
4. Try to disable a module
5. Check network. There's a 403 error. **Any error has been displayed in action 4**.

_* This is how I managed to reproduce the issue, but it also happens when token has expired (I don't know how to force token expiration):_ 

![image](https://user-images.githubusercontent.com/15104724/50289252-8f5f2d00-0468-11e9-933d-f8cf7b887e69.png)

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Did you used a fresh installation PS1.7.5.0?
In my case, I did not manage to reproduce the with fresh installation PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1vQb_KBfafnPPiTifa5WzdYnOpAofrUle/view
Thanks to check & feedback.

**Comment by idnovate** [comment]
Hi!

The test is not correct.

Please check:

1. Go to Modules page
2. Open another tab <-- **Caution with this step. You need 2 tabs with the backoffice.**
3. Logout employee session in the **2nd tab**
4. Try to disable a module **in the 1st tab**
5. Check network. There's a 403 error. Any error has been displayed in action 4.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0 / PS1.7.4.4.
https://drive.google.com/file/d/1cXpGzyKOE3Mtk-4qUbdLHPHxl6aciIpt/view
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
I can't reproduce the issue with 1.7.6.x, I well have an error message when I try to disable a module

https://drive.google.com/file/d/1OVfqqa9yZMzUPHx2J7J9L2qr326UKyKn/view?usp=sharing

![capture d'écran_1647](https://user-images.githubusercontent.com/13449658/59098666-335a6900-8921-11e9-823d-ed857d098b88.png)
