### ISSUE TITLE
Manufacturer page query take extreme long time compared to other places queries

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#11893]
Try to load the products list in FO accessing the manufacturer page take 5 times more time than access the same product using a category page .

Create a manufacturer. 
Add 3'000 product (or 30'000 or any considerable amount).
Assign these products to a new category.

Try load on FO the categories page result in a normal waith time for db and prestashop script to load product.

Try to open the manufacturer page take 5 times load time.

The query used by manufacturer page or the code has something that need improve

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
What is your exact PrestaShop version did you use?
Thanks!

**Comment by matteolavaggi** [comment]
PS 1.7.2

Maybe the problem is the LIMIT se tot 9999 for the query result? How we can change this on code to make some test? thanks

**Comment by khouloudbelguith** [comment]
ping @jocel1 what do you think?
Thanks!

**Comment by matteolavaggi** [comment]
There is a way to past SQL code in a good way on GitHub?!

```
# Query 2: 0.03 QPS, 0.05x concurrency, ID 0xE2E98FA24423D738837571249429F288 at byte 46642
# This item is included in the report because it matches --limit.
# Scores: V/M = 0.12
# Time range: 2018-12-21T12:49:38 to 2018-12-21T13:03:56
# Attribute    pct   total     min     max     avg     95%  stddev  median
# ============ === ======= ======= ======= ======= ======= ======= =======
# Count         27      24
# Exec time     25     40s      1s      3s      2s      2s   439ms      2s
# Lock time     22    10ms   315us   722us   425us   515us    84us   403us
# Rows sent     99 119.47k      12   9.76k   4.98k   9.33k   4.59k   9.33k
# Rows examine  22   6.60M  29.87k 297.15k 281.54k 283.86k  51.00k 283.86k
# Rows affecte   0       0       0       0       0       0       0       0
# Bytes sent    99 202.40M  21.15k  16.47M   8.43M  15.90M   7.81M  15.90M
# Query size    26  45.33k   1.89k   1.89k   1.89k   1.86k       0   1.86k
# String:
# Databases    Prestashop_1
# Hosts        localhost
# Last errno   0
# Users        prestashop
# Query_time distribution
#   1us
#  10us
# 100us
#   1ms
#  10ms
# 100ms
#    1s  ################################################################
#  10s+
# Tables
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_attribute_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_attribute_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_lang'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_lang`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_image_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_image_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_image_lang'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_image_lang`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_manufacturer'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_manufacturer`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_stock_available'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_stock_available`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_category_product'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_category_product`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_category'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_category`\G
# EXPLAIN /*!50100 PARTITIONS*/
```
```
SELECT p.*, product_shop.*, stock.out_of_stock, IFNULL(stock.quantity, 0) as quantity, product_attribute_shop.minimal_quantity AS product_attribute_minimal_quantity, IFNULL(product_attribute_shop.`id_product_attribute`,0) id_product_attribute
                        , pl.`description`, pl.`description_short`, pl.`link_rewrite`, pl.`meta_description`, pl.`meta_keywords`,
                        pl.`meta_title`, pl.`name`, pl.`available_now`, pl.`available_later`, image_shop.`id_image` id_image, il.`legend`, m.`name` AS manufacturer_name,
                                DATEDIFF(
                                        product_shop.`date_add`,
                                        DATE_SUB(
                                                "2018-12-21 00:00:00",
                                                INTERVAL 15 DAY
                                        )
                                ) > 0 AS new FROM `ps_product` p
                         INNER JOIN ps_product_shop product_shop
        ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1)LEFT JOIN `ps_product_attribute_shop` product_attribute_shop
                                                ON (p.`id_product` = product_attribute_shop.`id_product` AND product_attribute_shop.`default_on` = 1 AND product_attribute_shop.id_shop=1)
                        LEFT JOIN `ps_product_lang` pl
                                ON (p.`id_product` = pl.`id_product` AND pl.`id_lang` = 1 AND pl.id_shop = 1 )
                                LEFT JOIN `ps_image_shop` image_shop
                                        ON (image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop=1)
                        LEFT JOIN `ps_image_lang` il
                                ON (image_shop.`id_image` = il.`id_image` AND il.`id_lang` = 1)
                        LEFT JOIN `ps_manufacturer` m
                                ON (m.`id_manufacturer` = p.`id_manufacturer`)
                         LEFT JOIN ps_stock_available stock
                        ON (stock.id_product = `p`.id_product AND stock.id_product_attribute = 0 AND stock.id_shop = 1  AND stock.id_shop_group = 0  )JOIN `ps_category_product` cp ON (p.id_product = cp.id_product)JOIN `ps_category` ca ON cp.`id_category` = ca.`id_category` AND ca.`active` = 1
                                WHERE p.`id_manufacturer` = 29
                                 AND product_shop.`active` = 1
                                 AND product_shop.`visibility` IN ("both", "catalog")
                                GROUP BY p.id_product
                                ORDER BY pl.`name` ASC
                                LIMIT 0,9999\G

```

**Comment by matteolavaggi** [comment]
```
# Query 1: 0.05 QPS, 0.08x concurrency, ID 0x1B51C554754CD8AD4659D353656C44A5 at byte 5090
# This item is included in the report because it matches --limit.
# Scores: V/M = 1.01
# Time range: 2018-12-21T12:49:01 to 2018-12-21T13:08:29
# Attribute    pct   total     min     max     avg     95%  stddev  median
# ============ === ======= ======= ======= ======= ======= ======= =======
# Count         64      57
# Exec time     62     99s      1s     10s      2s      3s      1s      1s
# Lock time     51    23ms   317us   878us   409us   467us    71us   384us
# Rows sent      0     513       9       9       9       9       0       9
# Rows examine  48  14.43M  16.87k 271.94k 259.23k 270.35k  53.81k 270.35k
# Rows affecte   0       0       0       0       0       0       0       0
# Bytes sent     0   1.22M  18.79k  24.04k  21.99k  22.45k  860.24  21.38k
# Query size    68 115.29k   2.02k   2.03k   2.02k   1.96k       0   1.96k
# String:
# Databases    Prestashop_1
# Hosts        localhost
# Last errno   0
# Users        prestashop
# Query_time distribution
#   1us
#  10us
# 100us
#   1ms
#  10ms
# 100ms
#    1s  ################################################################
#  10s+  #
# Tables
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_category_product'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_category_product`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_attribute_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_attribute_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_stock_available'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_stock_available`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_category_lang'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_category_lang`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_product_lang'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_product_lang`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_image_shop'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_image_shop`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_image_lang'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_image_lang`\G
#    SHOW TABLE STATUS FROM `Prestashop_1` LIKE 'ps_manufacturer'\G
#    SHOW CREATE TABLE `Prestashop_1`.`ps_manufacturer`\G
# EXPLAIN /*!50100 PARTITIONS*/
SELECT p.*, product_shop.*, stock.out_of_stock, IFNULL(stock.quantity, 0) AS quantity, IFNULL(product_attribute_shop.id_product_attribute, 0) AS id_product_attribute,
                                        product_attribute_shop.minimal_quantity AS product_attribute_minimal_quantity, pl.`description`, pl.`description_short`, pl.`available_now`,
                                        pl.`available_later`, pl.`link_rewrite`, pl.`meta_description`, pl.`meta_keywords`, pl.`meta_title`, pl.`name`, image_shop.`id_image` id_image,
                                        il.`legend` as legend, m.`name` AS manufacturer_name, cl.`name` AS category_default,
                                        DATEDIFF(product_shop.`date_add`, DATE_SUB("2018-12-21 00:00:00",
                                        INTERVAL 15 DAY)) > 0 AS new, product_shop.price AS orderprice
                                FROM `ps_category_product` cp
                                LEFT JOIN `ps_product` p
                                        ON p.`id_product` = cp.`id_product`
                                 INNER JOIN ps_product_shop product_shop
        ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1) LEFT JOIN `ps_product_attribute_shop` product_attribute_shop
                                ON (p.`id_product` = product_attribute_shop.`id_product` AND product_attribute_shop.`default_on` = 1 AND product_attribute_shop.id_shop=1)
                                 LEFT JOIN ps_stock_available stock
                        ON (stock.id_product = `p`.id_product AND stock.id_product_attribute = 0 AND stock.id_shop = 1  AND stock.id_shop_group = 0  )
                                LEFT JOIN `ps_category_lang` cl
                                        ON (product_shop.`id_category_default` = cl.`id_category`
                                        AND cl.`id_lang` = 1 AND cl.id_shop = 1 )
                                LEFT JOIN `ps_product_lang` pl
                                        ON (p.`id_product` = pl.`id_product`
                                        AND pl.`id_lang` = 1 AND pl.id_shop = 1 )
                                LEFT JOIN `ps_image_shop` image_shop
                                        ON (image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop=1)
                                LEFT JOIN `ps_image_lang` il
                                        ON (image_shop.`id_image` = il.`id_image`
                                        AND il.`id_lang` = 1)
                                LEFT JOIN `ps_manufacturer` m
                                        ON m.`id_manufacturer` = p.`id_manufacturer`
                                WHERE product_shop.`id_shop` = 1
                                        AND cp.`id_category` = 143 AND product_shop.`active` = 1 AND product_shop.`visibility` IN ("both", "catalog") ORDER BY RAND() LIMIT 9\G

```

**Comment by matteolavaggi** [comment]
Query 1 # Exec time     25     40s      1s      3s 
Query 2 # Exec time     62     99s      1s     10s

**Comment by matteolavaggi** [comment]
No update after 3 month ... very good.

**Comment by matteolavaggi** [comment]
Any update dear? Waith 1 minutes for open a manufacturer page in a dedicated 12GB RAM SERVER a 8 CPU mean that coding is HORRIBLE!

**Comment by matteolavaggi** [comment]
....

**Comment by matteolavaggi** [comment]
@jocel1

**Comment by matteolavaggi** [comment]
What is this?
`    /**
     * Get Products by Manufacturer
     * (light edition)
     *
     * @param int $idLang
     *
     * @return array|false|mysqli_result|null|PDOStatement|resource
     */
    public function getProductsLite($idLang)
    {
        $context = Context::getContext();
        $front = true;
        if (!in_array($context->controller->controller_type, array('front', 'modulefront'))) {
            $front = false;
        }

        return Db::getInstance()->executeS('
		SELECT p.`id_product`,  pl.`name`
		FROM `'._DB_PREFIX_.'product` p
		'.Shop::addSqlAssociation('product', 'p').'
		LEFT JOIN `'._DB_PREFIX_.'product_lang` pl ON (
			p.`id_product` = pl.`id_product`
			AND pl.`id_lang` = '.(int) $idLang.$context->shop->addSqlRestrictionOnLang('pl').'
		)
		WHERE p.`id_manufacturer` = '.(int) $this->id.
        ($front ? ' AND product_shop.`visibility` IN ("both", "catalog")' : ''));
    }`

Instead this?
`    /**
     * Get Products by Manufacturer ID
     *
     * @param  int         $idManufacturer
     * @param  int         $idLang
     * @param  int         $p
     * @param   int        $n
     * @param null         $orderBy
     * @param null         $orderWay
     * @param bool         $getTotal
     * @param bool         $active
     * @param bool         $activeCategory
     * @param Context|null $context
     *
     * @return array|bool
     */
    public static function getProducts(
        $idManufacturer,
        $idLang,
        $p,
        $n,
        $orderBy = null,
        $orderWay = null,
        $getTotal = false,
        $active = true,
        $activeCategory = true,
        Context $context = null
    ) {
        if (!$context) {
            $context = Context::getContext();
        }

        $front = true;
        if (!in_array($context->controller->controller_type, array('front', 'modulefront'))) {
            $front = false;
        }

        if ($p < 1) {
            $p = 1;
        }

        if (empty($orderBy) || $orderBy == 'position') {
            $orderBy = 'name';
        }

        if (empty($orderWay)) {
            $orderWay = 'ASC';
        }

        if (!Validate::isOrderBy($orderBy) || !Validate::isOrderWay($orderWay)) {
            die(Tools::displayError());
        }

        $groups = FrontController::getCurrentCustomerGroups();
        $sqlGroups = count($groups) ? 'IN ('.implode(',', $groups).')' : '= 1';

        /* Return only the number of products */
        if ($getTotal) {
            $sql = '
				SELECT p.`id_product`
				FROM `'._DB_PREFIX_.'product` p
				'.Shop::addSqlAssociation('product', 'p').'
				WHERE p.id_manufacturer = '.(int) $idManufacturer
                .($active ? ' AND product_shop.`active` = 1' : '').'
				'.($front ? ' AND product_shop.`visibility` IN ("both", "catalog")' : '').'
				AND EXISTS (
					SELECT 1
					FROM `'._DB_PREFIX_.'category_group` cg
					LEFT JOIN `'._DB_PREFIX_.'category_product` cp ON (cp.`id_category` = cg.`id_category`)'.
                    ($activeCategory ? ' INNER JOIN `'._DB_PREFIX_.'category` ca ON cp.`id_category` = ca.`id_category` AND ca.`active` = 1' : '').'
					WHERE p.`id_product` = cp.`id_product` AND cg.`id_group` '.$sqlGroups.'
				)';

            $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($sql);
            return (int) count($result);
        }
        if (strpos($orderBy, '.') > 0) {
            $orderBy = explode('.', $orderBy);
            $orderBy = pSQL($orderBy[0]).'.`'.pSQL($orderBy[1]).'`';
        }

        if ($orderBy == 'price') {
            $alias = 'product_shop.';
        } elseif ($orderBy == 'name') {
            $alias = 'pl.';
        } elseif ($orderBy == 'manufacturer_name') {
            $orderBy = 'name';
            $alias = 'm.';
        } elseif ($orderBy == 'quantity') {
            $alias = 'stock.';
        } else {
            $alias = 'p.';
        }

        $sql = 'SELECT p.*, product_shop.*, stock.out_of_stock, IFNULL(stock.quantity, 0) as quantity'
            .(Combination::isFeatureActive() ? ', product_attribute_shop.minimal_quantity AS product_attribute_minimal_quantity, IFNULL(product_attribute_shop.`id_product_attribute`,0) id_product_attribute' : '').'
			, pl.`description`, pl.`description_short`, pl.`link_rewrite`, pl.`meta_description`, pl.`meta_keywords`,
			pl.`meta_title`, pl.`name`, pl.`available_now`, pl.`available_later`, image_shop.`id_image` id_image, il.`legend`, m.`name` AS manufacturer_name,
				DATEDIFF(
					product_shop.`date_add`,
					DATE_SUB(
						"'.date('Y-m-d').' 00:00:00",
						INTERVAL '.(Validate::isUnsignedInt(Configuration::get('PS_NB_DAYS_NEW_PRODUCT')) ? Configuration::get('PS_NB_DAYS_NEW_PRODUCT') : 20).' DAY
					)
				) > 0 AS new'
            .' FROM `'._DB_PREFIX_.'product` p
			'.Shop::addSqlAssociation('product', 'p').
            (Combination::isFeatureActive() ? 'LEFT JOIN `'._DB_PREFIX_.'product_attribute_shop` product_attribute_shop
						ON (p.`id_product` = product_attribute_shop.`id_product` AND product_attribute_shop.`default_on` = 1 AND product_attribute_shop.id_shop='.(int)$context->shop->id.')':'').'
			LEFT JOIN `'._DB_PREFIX_.'product_lang` pl
				ON (p.`id_product` = pl.`id_product` AND pl.`id_lang` = '.(int) $idLang.Shop::addSqlRestrictionOnLang('pl').')
				LEFT JOIN `'._DB_PREFIX_.'image_shop` image_shop
					ON (image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop='.(int)$context->shop->id.')
			LEFT JOIN `'._DB_PREFIX_.'image_lang` il
				ON (image_shop.`id_image` = il.`id_image` AND il.`id_lang` = '.(int) $idLang.')
			LEFT JOIN `'._DB_PREFIX_.'manufacturer` m
				ON (m.`id_manufacturer` = p.`id_manufacturer`)
			'.Product::sqlStock('p', 0);

        if (Group::isFeatureActive() || $activeCategory) {
            $sql .= 'JOIN `'._DB_PREFIX_.'category_product` cp ON (p.id_product = cp.id_product)';
            if (Group::isFeatureActive()) {
                $sql .= 'JOIN `'._DB_PREFIX_.'category_group` cg ON (cp.`id_category` = cg.`id_category` AND cg.`id_group` '.$sqlGroups.')';
            }
            if ($activeCategory) {
                $sql .= 'JOIN `'._DB_PREFIX_.'category` ca ON cp.`id_category` = ca.`id_category` AND ca.`active` = 1';
            }
        }

        $sql .= '
				WHERE p.`id_manufacturer` = '.(int) $idManufacturer.'
				'.($active ? ' AND product_shop.`active` = 1' : '').'
				'.($front ? ' AND product_shop.`visibility` IN ("both", "catalog")' : '').'
				GROUP BY p.id_product
				ORDER BY '.$alias.'`'.bqSQL($orderBy).'` '.pSQL($orderWay).'
				LIMIT '.(((int) $p - 1) * (int) $n).','.(int) $n;

        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($sql);

        if (!$result) {
            return false;
        }

        if ($orderBy == 'price') {
            Tools::orderbyPrice($result, $orderWay);
        }

        return Product::getProductsProperties($idLang, $result);
    }`

**Comment by colinegin** [comment]
@matks do you think this issue will be solved with manufacturer page migration ?

**Comment by matks** [comment]
@colinegin No, because the issue is on front-office, not back-office

**Comment by colinegin** [comment]
My bad @matks, i did not know it was on FO !

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay, we have a lot of things to do :sweat_smile: 

I think the 3000 products should not be displayed on the same page, or with a pagination / infinite load.
@PrestaShop/product-team wdyt?

**Comment by marionf** [comment]
@PierreRambaud it's already the case

On brands and categories pages in the front-office, the number of products displayed are already limited by a pagination system (on classic theme):

Category:

![capture d'écran_2863](https://user-images.githubusercontent.com/13449658/99784646-6811ae80-2b1c-11eb-8733-e3d57bf49111.png)

Brand:

![capture d'écran_2862](https://user-images.githubusercontent.com/13449658/99784675-752e9d80-2b1c-11eb-8c3a-24aef570421f.png)

By the way, the number of products per page can be configured in Shop parameters > Product settings

![capture d'écran_2864](https://user-images.githubusercontent.com/13449658/99784879-b6bf4880-2b1c-11eb-9dd2-3886c5738e3d.png)

**Comment by matteolavaggi** [comment]
On brands and categories pages in the front-office, the number of products displayed are already limited by a pagination system (on classic theme):

==> So why it take crazy amount of time to be executed ?

**Comment by PierreRambaud** [comment]
You should check with the modules you installed.
I tried with a thousand products and it takes 200ms to load the page.

**Comment by matteolavaggi** [comment]
TRy with one hundred thousand , 1k product is nothing !


Il giorno ven 20 nov 2020 alle ore 14:48 GoT <notifications@github.com> ha
scritto:

**Comment by PierreRambaud** [comment]
Not sure the PrestaShop Core is optimized for 100 000 products, if you have a lot of products in your shop, please contact a professional to help you to optimize your shop, and if problems come from the Core, feel free to reopen the issue or create a pull request :)
