### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #.total_paid

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#11906]
**Describe the bug**
This issue occurs when we update the product details in order. It is a syntax error on orders.js
File link - https://github.com/PrestaShop/PrestaShop/blob/develop/js/admin/orders.js#L292 

**To Reproduce**
1. Go to 'Order detail page on backend'
2. Click on 'Edit and then update button on the product list of that order'
3. inspect the window and click on console
4. check error here

**Screenshots**
![error](https://user-images.githubusercontent.com/39614089/50373886-206e0980-060b-11e9-9370-bd3514f36885.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/50395498-c719ed80-0764-11e9-962b-e857a3940b4d.png)
With PS1.7.4.4, there are different errors in the console
![image](https://user-images.githubusercontent.com/16067358/50395514-e87ad980-0764-11e9-87ae-8e4185a1eb29.png)

Thanks for the fix!
