### ISSUE TITLE
Allow dynamic lazy arrays properties

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11901]
@123monsite-regis has the following usecase: he receives a`ProductLazyArray` from hook hookFilterSupplierContent and wishes to add a property to it, **making it lazy as well**

So this does not work:
```
public function hookFilterSupplierContent($params) {
        $params['object']->appendArray(array('MymoduleVars' => array('MyVAriable' => 'MyVAriable'));
}
```
Added data is not lazy

A solution would be to create a LazyArray able to use closures.

```
$myLazyArray = new AdvancedClosureLazyArray();
$myLazyArray->appendArray(array(
    'get_my_url' => function () use ($link) {
        return getPageLink('foo', true, null);
    }
));
```
And when calling `$myLazyArray['get_my_url']` it would execute the closure then return the result

What do you think @jocel1 ? 😄

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17419

**Comment by matks** [comment]
@123monsite-regis this feature will be available in 1.7.8 😊and you can use it in your shop now by using the code I built in https://github.com/PrestaShop/PrestaShop/pull/17419

**Comment by 123monsite-regis** [comment]
thank you :)

**Comment by jf-viguier** [comment]
@matks is this feature documented in dev doc ?

**Comment by matks** [comment]
@jf-viguier No, I think LazyArray are absent from the devdoc
