### ISSUE TITLE
Error 500 in administrator modules

### ISSUE THREAD

**Issue by Tossko92** [PrestaShop/PrestaShop#11904]
**Describe the bug**
Good day,

The following error occurs when I try to enter the module manager, to the product administration or performance although I may have more sections of the administrator.

`Fatal error: Uncaught Twig_Error_Loader: The "/home/paiicom/public_html/final\app/../src/PrestaShopBundle/Resources/views/Admin/Product" directory does not exist ("/home/paiicom/public_html/final\app/../src/PrestaShopBundle/Resources/views/Admin/Product"). in /home/paiicom/public_html/final/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101 Stack trace: #0 /home/paiicom/public_html/final/var/cache/prod/ContainerZqwlxhs/appProdProjectContainer.php(2143): Twig_Loader_Filesystem->addPath('/home/paiicom/p...', 'Product') #1 /home/paiicom/public_html/final/var/cache/prod/ContainerZqwlxhs/appProdProjectContainer.php(1463): ContainerZqwlxhs\appProdProjectContainer->getTwig_LoaderService() #2 /home/paiicom/public_html/final/var/cache/prod/ContainerZqwlxhs/appProdProjectContainer.php(1989): ContainerZqwlxhs\appProdProjectContainer->getTwigService() #3 /home/paiicom/public_html/final/var/cache/prod/ContainerZqwlxhs/appProdProjectContainer.php(1108): ContainerZqwlxhs\appProdProjectContainer->getSensioFrameworkExtra_View_ListenerSer in /home/paiicom/public_html/final/vendor/twig/twig/lib/Twig/Loader/Chain.php on line 130`

It should be noted that when the debug is activated, the error does not appear and the information is displayed correctly, but only with the active debug

**To Reproduce**
1. Go to 'Modules or products or performance'
4. see error

**Screenshots**

![captura de pantalla 2018-12-21 a la s 7 11 40 p m](https://user-images.githubusercontent.com/46057255/50379311-fe798480-0614-11e9-8dc3-a5378ed8046f.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2.13

**Comment by khouloudbelguith** [comment]
Hi @Tossko92,

Did you installed any custom module before this issue occurs?
Could please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @Tossko92,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
