### ISSUE TITLE
Module tab name is still have 'Modules & Services' after upgrade to V1.7.5.0

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11905]
**Describe the bug**
After upgrade using the 1-click upgrade module, from V1.7.1.2 to V1.7.5.0 latest, Module tab name is still not updated see the screenshot.
I have cleared cache from the back-office, even deleted folder from the cache folder

**To Reproduce**
1. upgrade using the 1-click upgrade module, from V1.7.1.2 to V1.7.5.0 latest
2. Check module tab name
3. In latest V1.7.5.1 its 'Module Manager' But its still 'Modules & Services'

![download 34](https://user-images.githubusercontent.com/19220745/50371882-88135d00-05e9-11e9-8bf5-7b7f9f4c12b4.png)

**Additionnal information**
PrestaShop version: Upgraded V1.7.5.0
PHP version: PHP-7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
I manage to reproduce the issue after upgrade from PS1.7.4.4 to PS1.7.5.0 using the 1-click upgrade 4.5.1.
After upgrade from 1.6.1.23 to PS1.7.5.0, I did not manage to reproduce the issue.
Here's the log file.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2706911/log.txt)
ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by Quetzacoalt91** [comment]
Hi,

This change has been forgotten in the upgrade process in https://github.com/PrestaShop/PrestaShop/commit/6d87a6c5efbdf7d6898da10885d119483c51107b. This needs to be added for 1.7.5.1. :)

**Comment by Quetzacoalt91** [comment]
Fixed by #12016
