### ISSUE TITLE
Combinations are not loaded after upgrade to 1.7.5.0

### ISSUE THREAD

**Issue by popovoleksandr** [PrestaShop/PrestaShop#11918]
**Describe the bug**

**To Reproduce**
1. Open product with combinations
2. Open combinations tab and cannot see combinations
3. Have 500 error in console:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/admin*****/index.php/sell/catalog/products/combinations/form/:numbers?_token=k7TXu3hDNWId3y72Xr_L0nPyXJBKXfQ-gidTiCeoEBU:1 

On other pages combinations still working (can select and order).

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment]
Hi @anantaramdas,

Your ticket is a duplicate of #11825
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11825
