### ISSUE TITLE
French flag giving false positive to antivirus/malware

### ISSUE THREAD

**Issue by daniloarayaz** [PrestaShop/PrestaShop#11912]
**Describe the bug**
An antivirus/malware scan on my bluehost hosting account is giving positive because the french flag image.

**To Reproduce**

Hope the antivirus log can give you a clue on what tool are using on my hosting
but i saw an unsolved case here.
http://forge.prestashop.com/browse/PSCSX-8715

**Screenshots**
This is the standard outpot of the antivirus/malware scanner tool

/home3/faithcl/public_html/officesandwich.cl/estilo_old/installbak/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/estilo_old/psadmin/autoupgrade/latest/install/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/estilo_old2/installbak/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/estilo/installbak/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/estilo/psadmin/autoupgrade/latest/install/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/prod/installbak/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND
/home3/faithcl/public_html/officesandwich.cl/estilo.bak.201811291125/installbak/langs/fr/flag.jpg: HG.ELF.DDos.25969.UNOFFICIAL FOUND

----------- SCAN SUMMARY -----------
Known viruses: 2075176
Engine version: devel-clamav-0.99-beta1-632-g8a582c7
Scanned directories: 63669
Scanned files: 348469
Infected files: 7
Data scanned: 2354.56 MB
Data read: 14731.12 MB (ratio 0.16:1)
Time: 2919.628 sec (48 m 39 s)

----------- SCAN SUMMARY -----------
Known viruses: 2075176
Engine version: devel-clamav-0.99-beta1-632-g8a582c7
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 4.456 sec (0 m 4 s)

----------- SCAN SUMMARY -----------
Known viruses: 2075176
Engine version: devel-clamav-0.99-beta1-632-g8a582c7
Scanned directories: 0
Scanned files: 6
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 4.664 sec (0 m 4 s)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6.37

**Comment by khouloudbelguith** [comment]
Hi @daniloarayaz,

I tried to scan this [link](https://download.prestashop.com/download/releases/prestashop_1.7.5.0.zip?_ga=2.113304647.1327997385.1545639303-455038412.1544784014), but there are no virus detected.
I attached the Scan report file
[Scan report for at UTC - VirusTotal.pdf](https://github.com/PrestaShop/PrestaShop/files/2707433/Scan.report.for.at.UTC.-.VirusTotal.pdf)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @daniloarayaz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by joecoolio66** [comment]
Just an FYI that this is still a bluehost issue!  I had this file flagged for the same virus today
