### ISSUE TITLE
Can't open module configure: 500 error after ps_linklist update to 3.0.2

### ISSUE THREAD

**Issue by MSiliunas** [PrestaShop/PrestaShop#11914]
**Describe the bug**
After updating prestashop to 1.7.5 I also updated Link List module to 3.0.2. Now I'm getting 500 error when I try to configure it in back office.
I've tried:
- reinstalling the module
- clearing the cache manually (it is disabled atm)

**To Reproduce**
1. Update Link List from 2.*.* to 3.0.2
2. Go to Modules -> Configure "Link List"
3. See Error

**Screenshots**
![image](https://user-images.githubusercontent.com/6944305/50387421-9609d080-0704-11e9-88bb-f903603c213e.png)

**Additionnal information**
PrestaShop version: 1.7.5
Error stacktrace:
```
InvalidArgumentException:
Class "PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController" does not exist.

  at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:180
  at Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController::listAction')
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php:63)
  at Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->createController('PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController::listAction')
     (vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php:43)
  at Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->createController('PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController::listAction')
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:88)
  at Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php:41)
  at Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->getController(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php:49)
  at Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:134)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin772b6nbxw/index.php:88)
```

**Comment by khouloudbelguith** [comment]
Hi @MSiliunas,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
The upgrade of the ps_linklist from v2.1.5 to 3.0.2 is done successfully.
I attached a video record.
https://drive.google.com/file/d/1HLGbBuToAG4Qy1_ZbfGaTKgcK1Kn5cKq/view
Could you please try to uninstall this module, clear cache & install it again.
Thanks to check & feedback.

**Comment by pdsolutions** [comment]
I have the same issue on a fresh PS 1.7.5.0 Prestashop installation. 
![bugs](https://user-images.githubusercontent.com/46190904/50476643-27a96480-09c9-11e9-9fe2-967fdc498107.jpg)

**Comment by khouloudbelguith** [comment]
Hi @pdsolutions,

What the exact version of the ps_linklist module did you use before the upgrade?
Thanks!

**Comment by pdsolutions** [comment]
Hi khouloudbelguith,

Did you read my comment. I have the same issue on a fresh prestashop install v1. 7.5.0

So, this means that the version of @MSiliunas before update does not matter.

**Comment by khouloudbelguith** [comment]
Hi @pdsolutions,

Sorry, but I did not manage to reproduce the issue with a fresh installation PS1.7.5.0.
I attached a video record.
[Module manager • 1750.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2712252/Module.manager.1750.webm.zip)
@marionf, did you manage to reproduce the issue?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith I can't reproduce 

![capture d ecran_821](https://user-images.githubusercontent.com/13449658/50478214-4bbc7400-09d0-11e9-9c52-445aed8988e6.png)

**Comment by marionf** [comment]
@jolelievre any idea about this issue ?

**Comment by pdsolutions** [comment]
Hello,

I just tested it on another PS 1.7.5.0 installation and it works with the default template.
The problem of @MSiliunas and mine is that we don't use the default template. I think the problem is more related to the template than prestashop core.

Here i attach my video installing and testing the link widget on a brand new PS 1.7.5.0, then i install the template and it fails.

https://tienda.termprotect.es/linkwidget.mp4

Thanks

**Comment by khouloudbelguith** [comment]
Hi @pdsolutions,

I tried with other different themes but I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1fpTVdimchlQL_SMOPp8pHc_GlTVgXKkP/view
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com [account](https://addons.prestashop.com/fr/themes-maison-jardin/24311-interior-magasin-de-meubles.html), they are the only ones to help you with it.
Thanks!

**Comment by MSiliunas** [comment]
@khouloudbelguith Sorry for late response.
I'm using `Classic` theme by PrestaShop (v 1.0.0). So it's not a problem with the theme (I suppose).
What I didn't mention is that I use `1-Click Upgrade` for PS upgrade.

**Comment by khouloudbelguith** [comment]
Hi @MSiliunas,

Despite our several trials, we could not reproduce your issue with the provided information, so we closed the issue.
In your case, try to uninstall the ps_linklist module, remove the ps_linklist folder from your projectFolder/modules/, clear cache & try to install the new version of the ps_linklist.
Thanks!

**Comment by MSiliunas** [comment]
@khouloudbelguith I've tried uninstalling, clearing cache, manually deleting files and installing newest version downloaded directly from github. Didn't work. I've downloaded the `2.1.5` version and it works again.

**Comment by khouloudbelguith** [comment]
Hi @MSiliunas,

I cloned this module from Github
[ps_linklist.zip](https://github.com/PrestaShop/PrestaShop/files/2731877/ps_linklist.zip)
It is the latest version of ps_linklist module, thanks to check with it!

**Comment by jolelievre** [comment]
@MSiliunas maybe your problem is linked to the absence of vendor

If you go in modules/ps_linklist/vendor is the folder empty?
If it you need to run `composer install` because the module was probably installed manually from the sources and they don't include vendors
If you install from the `Module Manager` you don't have this problem

**Comment by MSiliunas** [comment]
Ive already checked and the vendors were installed. Ive tried installing
via manager and manually. It was the same. Currently ive installed the
older version.

**Comment by jolelievre** [comment]
Ok so it seems to be a different problem from https://github.com/PrestaShop/PrestaShop/issues/12085

**Comment by jolelievre** [comment]
Do you have access to command line? If so you can try these commands at the root of the project:

`php ./bin/console debug:router` and check if `admin_link_block_list, admin_link_block_create, ...` are present

`php ./bin/console debug:container | grep prestashop.module.link_block` to see if the module's services are present

**Comment by mrabsinthe** [comment]
Same issue as @MSiliunas , clean installation, no issues with older version 2.1.5. Installed via manager, modules/ps_linklist/vendor is not empty, composer folder is there as well as autoload.php
Uncaught Exception: Class "PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController" does not exist.
as well as:
Uncaught PHP Exception InvalidArgumentException: "Class "PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController" does not exist." at /home/xxx/public_html/store/var/cache/dev/classes.php line 4187
All screenshots below:

**Comment by mrabsinthe** [comment]
![linklist](https://user-images.githubusercontent.com/31688689/51316144-185f8900-1a54-11e9-816d-1aeb8189c8d6.png)
![module linklist controller](https://user-images.githubusercontent.com/31688689/51316312-9885ee80-1a54-11e9-80f6-7383cad201a7.png)

**Comment by mrabsinthe** [comment]
Perhaps PHP related...? I have managed to test two identical 1.7.5 clean installations on two different servers. Only one of them is working fine after ps_linklist update to v3.0.2., have a look:
This one has 500 error:
![error](https://user-images.githubusercontent.com/31688689/51382993-82416680-1b18-11e9-93a1-c609348098b5.png)

And this one is working just fine:
![ok](https://user-images.githubusercontent.com/31688689/51383029-99805400-1b18-11e9-9b11-0992adc3312b.png)

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe, Thanks for your feedback.

Could you please follow this link: https://github.com/PrestaShop/php-ps-info & check with your first server information.
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by mrabsinthe** [comment]
Sure, here it is for the server with 500 error:
![prestashop info](https://user-images.githubusercontent.com/31688689/51384829-d13dca80-1b1d-11e9-8ee3-3b1370e301c5.png)

**Comment by jolelievre** [comment]
I'm gonna try with PHP 5.6 to see if it's related

**Comment by jolelievre** [comment]
I tried a fresh install of PS 1744 on an environment with PHP 5.6
After upgrade I had a 500 on prod env when accessing `Link Widget` (on debug mode it works fine)
After removal of cache `rm -fR var/cache/*` and `cache:clear` commands it works fine:
```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
I'm sorry I'm still unable to reproduce your problem.

**Comment by khouloudbelguith** [comment]
Hi,

It is OK for me also.
PHP version: 5.6.32.
I tried a fresh installation 1.7.5.0, after upgrade of the module ps_linklist from 2.1.5 to 3.0.2, when accessing Link Widget => it is OK (debug mode in my case is disabled => working)
https://drive.google.com/file/d/1Cb25IlYYO6ol3R4fhIHUIp7KY0eCadQI/view
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @MSiliunas,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by leungda** [comment]
Me too. I got the same problem 

I understand that khouloudbelguith says they cannot reproduce the problem. The issue is it looks like it is not only a few people are having the same issue. If you google "prestashop link list module 3.0.2", there are more people are having this issue on this like https://github.com/PrestaShop/PrestaShop/issues/12085

**Comment by netdrag** [comment]
Got the same problem. 

php ./bin/console debug:container | grep prestashop.module.link_block is returning nothing.
reinstalling didn't help.

**Comment by jolelievre** [comment]
When you go in `modules/ps_linklist` does the vendor folder contain `autoload.php` and `composer` folder. If not you need to run `composer install`
Then manually remove the cache and retry `rm -fR var/cache/*`

**Comment by jolelievre** [comment]
When you go in `modules/ps_linklist` does the vendor folder contain `autoload.php` and `composer` folder. If not you need to run `composer install`
Then manually remove the cache and retry `rm -fR var/cache/*`

**Comment by netdrag** [comment]
Yes it contains the files. I installed the module through the module manager in prestashop. 
Server is nginx with php 7.0. I started with prestashop 1.7.1 and am now on prestashop 1.7.5.1 but have that problem only on one installation. all others work as expected.

**Comment by dtamajon** [comment]
I had the same problem and it was due to nginx configuration. Following directive solves the problems (the "modules" allowed path):

location ~ /(international|_profiler|module|modules|common|product|feature|attribute|improve|sell|supplier|combination|specific-price|configure|api|stock|security|translations|_wdt)/(.*)$ {
  try_files $uri $uri/ /index.php?q=$uri&$args /admin-ecofestes/index.php$is_args$args;
}
