### ISSUE TITLE
Sorting by Price (tax included) is based on the sort by price tax excluded

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11925]
**Describe the bug**
In the product listing page, when we try to sort by price tax included, this sort is not correct, it is based on the price tax excluded => so we will have an incorrect sorting.

**To Reproduce**
1. Go to BO => Catalog => Products
2. Sort by Price Tax included
3. See error => the sort is done by the price tax excluded

This PR: https://github.com/PrestaShop/PrestaShop/pull/11484 is related to this issue.
**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/50403374-5abbe000-079e-11e9-853b-f9139f08115f.png)

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by PierreRambaud** [comment]
As I said in the pull request, we need to define if we want to sort this column because it is calculated after the sort.
