### ISSUE TITLE
Warning displayed on customer searh page

### ISSUE THREAD

**Issue by popovoleksandr** [PrestaShop/PrestaShop#11931]
**Describe the bug**
Warning displayedon customer searh page

**To Reproduce**
1. Set `define('_PS_MODE_DEV_', true)` in `config/defines.inc.php`
2. Go to Orders
3. Click on Add new order
4. See warning:
```
Notice on line 1752 in file /var/home/*********/var/cache/dev/smarty/compile/49/47/b2/4947b262a2a90c442dbf49deae71c6337a6865c1_0.file.form.tpl.php
[8] Trying to get property 'name' of non-object

Notice on line 1753 in file /var/home/*********/var/cache/dev/smarty/compile/49/47/b2/4947b262a2a90c442dbf49deae71c6337a6865c1_0.file.form.tpl.php
[8] Trying to get property 'displayName' of non-object
```

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment]
Hi @anantaramdas,

Thanks for your report.
Could you please try to run this resquest SQL in your database

ALTER TABLE `ps_order_detail` CHANGE `product_supplier_reference` `product_supplier_reference` varchar(64) DEFAULT NULL;
![image](https://user-images.githubusercontent.com/16067358/50439077-e776b300-08f0-11e9-97ae-9526af064e31.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @anantaramdas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
