### ISSUE TITLE
After upgrade to PS1.7.5.0, The quick access new product and installed modules, they don't work

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11934]
**Describe the bug**
After upgrade from PS1.7.4.4 to PS1.7.5.0 & from PS1.6.1.23 to PS1.7.5.0 with the 1-click upgrade v4.5.1.
The quick access new product and installed modules, they don’t work. If you click on the quick access new product and installed modules, this access are redirect you to Dashboard. They should redirect to a new product page for the new product and module manager page for installed modules.

**To Reproduce**
1. Go to BO => Quick Access
2. Click on New product and installed modules
3. See error

With fresh installation PS1.7.5.0 => OK

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/50472595-b7471700-09b9-11e9-9813-3dbf4573a8b9.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by Quetzacoalt91** [comment]
Fixed by #12016
