### ISSUE TITLE
$pagination.should_be_displayed return NULL

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#11930]
Hey. Why does a variable return NULL?

Pagination not work.

![screenshot_1](https://user-images.githubusercontent.com/6318282/50431256-23237400-0915-11e9-9e47-0859d50528db.png)

![screenshot_2](https://user-images.githubusercontent.com/6318282/50431290-6e3d8700-0915-11e9-8daa-3b4275d1ebf4.png)

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for your report.
What is the exact version PrestaShop did you use?
Is it PS1.7.4.4?
In the BO => Shop Parameters => Traffic & SEO => Did you disable the friendly url?
Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith 

PS Version 1.7.5.0
URL rewriting is ON

**Comment by khouloudbelguith** [comment]
@TemKaSD, I did not manage to reproduce the issue with fresh installation PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1HikzrDrQ9MEHe1qry82xsiOQe-MSLzZq/view
Thanks to check & feedback.

**Comment by TemKaSD** [comment]
@khouloudbelguith I have a bad template. Thx.
