### ISSUE TITLE
Can't switch cache off 1.7.3

### ISSUE THREAD

**Issue by Werbike** [PrestaShop/PrestaShop#11944]
I cannot switch off cache in BO what's needed to make update via 1-Click from 1.7.3 to higher...
When i switch Cache to No and hit Save, the site reload and the green text "Setting are change!"(smthng like that) appears, but Cache are still on "Yes"...
![image](https://user-images.githubusercontent.com/40056329/50516534-9bbc3900-0aab-11e9-917e-7c9cfd082f34.png) 
![image](https://user-images.githubusercontent.com/40056329/50516545-ad9ddc00-0aab-11e9-8260-59023513082f.png) 
![image](https://user-images.githubusercontent.com/40056329/50516555-b7274400-0aab-11e9-9f4f-349e1e979591.png)
So 1-click upgrade module still inform me about "PrestaShop's caching features are disabled"
![image](https://user-images.githubusercontent.com/40056329/50516590-e473f200-0aab-11e9-888c-20d81a360fa3.png)

The same problem was with CCC, but i switched value to 0 in MyAdmin DB
![image](https://user-images.githubusercontent.com/40056329/50516599-f6ee2b80-0aab-11e9-984e-79db14932acd.png)

But still cannot find the value for main cache in database... 
Any solutions ?
Under are some screens from debug mode in symphony but idk it's related with this problem.
![image](https://user-images.githubusercontent.com/40056329/50516627-374da980-0aac-11e9-8904-1ea6772f5fe6.png)

**Additionnal information**
PrestaShop version: 1.7.3.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Werbike,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Werbike** [comment]
-VPS on Hekko.pl
![image](https://user-images.githubusercontent.com/40056329/50519570-d6c66880-0abb-11e9-8dd1-9e3f223d31d6.png)
![image](https://user-images.githubusercontent.com/40056329/50519675-4fc5c000-0abc-11e9-9717-d38c68827c59.png)
- Presta 1.7.3.3
- no logs in BO
- debug/Symphony logs above

> Matched route "admin_performance". Context: { "route_parameters": {"_controller": "PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\PerformanceController::indexAction", "_legacy_controller": "AdminPerformance", "_route": "admin_performance" },"request_uri": "https://werbike.pl/admin7878/index.php/configure/advanced/performance?_token=dfr5u_gL8Om0Kxtn3E-CA6Ut8hLUBoTIhUIL7zn2L7I" )

Last server logs:
![image](https://user-images.githubusercontent.com/40056329/50519484-6fa8b400-0abb-11e9-8141-6beed379394e.png)

**Comment by khouloudbelguith** [comment]
@Werbike, could you please try to disable the `pshowblog` module & the `gsitemap` module, clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by Werbike** [comment]
Didn't helped.. Caches are still on "Yes"
![image](https://user-images.githubusercontent.com/40056329/50522110-86ee9e00-0ac9-11e9-9da3-762410e5771e.png)

**Comment by khouloudbelguith** [comment]
Hi @Werbike,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by thbl** [comment]
+1 same problem here

**Comment by Solander** [comment]
+1 exactly the same problem..

**Comment by khouloudbelguith** [comment]
Hi @Solander,

This issue is currently closed, can you open a new one with more information about your configuration.
Thanks!

**Comment by milaonline** [comment]
Go to your hosting php section and enable memcache or memcached.
Your problem is that you've had enabled memcache or memcached and probably changed hosting where memcache is not enabled that is why you can't switch off cache - go to php configuration enable memcache or memcached (that what you have enabled before) and then you will be able to turn of cache in prestashop :)
Spent 3 hours to solve it on my own and there was a problem :)
