### ISSUE TITLE
When selecting attributes in quick view, URL switches to product URL

### ISSUE THREAD

**Issue by Dylan-Chapman** [PrestaShop/PrestaShop#11941]
**Describe the bug**
Changing a product's attributes in a quick view popup will change the URL to the product's URL upon change. So, if the page is then refreshed, you'll be on the product page instead of the page you were on (i.e. category page). As far as I can tell, this was caused by [https://github.com/PrestaShop/PrestaShop/pull/9335](https://github.com/PrestaShop/PrestaShop/pull/9335).

It looks like this could be fixed by wrapping the history logic in something like `if (prestashop.page.page_name === 'product') ...` so that the URL is only adjusted if you're already on a product page. I can foresee this still being a problem with something like cross-selling modules on product pages though, because your URL would still change to the wrong product in the URL. In my opinion, this logic shouldn't apply at all if you're in a quick view.

**To Reproduce**
1. Open a quick view from a category page for a product that has attributes
2. Change an attribute
3. Notice the URL changes
4. Refresh the page - you'll now be on the product page

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by Dylan-Chapman** [comment]
Quick thought: Perhaps this could be prevented by only running the history logic if there's not a visible modal present? i.e. `if (!$('.modal:visible').length || !$('body').hasClass('modal-open')) ...`

**Comment by khouloudbelguith** [comment]
Hi @Dylan-Chapman,

I manage to reproduce the issue with PS1.7.5.0 / PS1.7.4.4.
When we refresh the page => we are redirected to product page.
https://drive.google.com/file/d/1wRFaJv5Z20PnG0f6-967LLOfeKAMaZft/view
With PS 1.7.4.0 => it is not the same behavior => when we refresh the page => we are in the same page
https://drive.google.com/file/d/1Vz85pN8HhSnJaPEjiH3nFclQTym6beO-/view
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
I can't reproduce the issue with 1.7.6.x, we stay on the same page after refreshing
