### ISSUE TITLE
French translation of the RGPD module is no longer available with version 1.1.2

### ISSUE THREAD

**Issue by Stephane1874** [PrestaShop/PrestaShop#11940]
**Describe the bug**

Hello,

After the update of the RGPD module 1.1.2 on the french version of prestashop 1.7.5, the translation of the module no longer works.

![capture](https://user-images.githubusercontent.com/46202635/50494919-60c3f200-0a26-11e9-8ecf-f57abd60a7ba.PNG)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment]
Hi @Stephane1874,

Thanks for your report.
After the upgrade of the RGPD module from v1.1.0 to v1.1.2.
 the translation of the module works. 
With a fresh installation PS1.7.5.0 => OK. with PS1.7.5.0 after upgrade from PS1.7.4.4 => OK
https://drive.google.com/file/d/1yqxRzev9YdWXMQ__Vn9atCpJ_EiG4BoD/view
I tried with a new installation of the RGPD module (v1.1.2 => OK) => the translation of the module works. 
I tried with RGPD module v1.1.0 => OK. => the translation of the module works. 
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Also, after the upgrade of your module => try to navigate to your BO => International => Translation => Edit the translation of your module is successfully saved.
Thanks to check and feedback.

**Comment by Stephane1874** [comment]
Hi @khouloudbelguith ,

You're right just translate the module again, I was tired last night and I did not check this point :)

Sorry for the time lost with this.

![capture](https://user-images.githubusercontent.com/46202635/50512718-e0d47100-0a93-11e9-9724-8e0cd63f9f57.PNG)

**Comment by khouloudbelguith** [comment]
Hi @Stephane1874,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
