### ISSUE TITLE
bug Use of undefined constant when the website needs to send an email

### ISSUE THREAD

**Issue by Sxpink** [PrestaShop/PrestaShop#11949]
Hello everyone i have a really big bug that is been bothering me since days whell when a customer register and the website needs to send an email it shows me a bug also when a customer validate a command and the website needs to send an email it shows me the errors bellow

**Screenshots**

![capturar](https://user-images.githubusercontent.com/46243917/50538748-1056ac80-0b6c-11e9-9f22-b42315c1468c.JPG)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by rdy4ever** [comment]
Yeap, same for one of my fresh 1.7.5.0 installation. Could you check if you also experience this issue: #11933?

**Comment by Sxpink** [comment]
> Yeap, same for one of my fresh 1.7.5.0 installation. Could you check if you also experience this issue: #11933?

No didnt came across that problem but i think its related

**Comment by khouloudbelguith** [comment]
Hi @Sxpink,

Could you please try to install php-intl extension.
Thanks to check and feedback.

Thanks,
Khouloud

**Comment by rdy4ever** [comment]
Hi. Try this: https://github.com/PrestaShop/PrestaShop/issues/11933#issuecomment-450652659

**Comment by khouloudbelguith** [comment]
Hi @Sxpink,

I believe you may be running a server with a ICU<4.6, Try to know the version of ICU in your php info.
http://kb.mediatemple.net/questions/764/How+can+I+create+a+phpinfo.php+page%3F#gs
Thanks to check & feedback.

**Comment by bogdanmoisin** [comment]
> Yeap, same for one of my fresh 1.7.5.0 installation. Could you check if you also experience this issue: #11933?

I have also the same issue.

**Comment by khouloudbelguith** [comment]
Hi @bogdanmoisin,

Here's a PR: https://github.com/PrestaShop/PrestaShop/pull/11995 to fix the issue.
Thanks!

**Comment by bogdanmoisin** [comment]
Thank you very much.

 

Have a nice day!

 

 

 

 <http://www.mbtconcept.ro/>

**Comment by bogdanmoisin** [comment]
> Hi @bogdanmoisin,
> 
> Here's a PR: #11995 to fix the issue.
> Thanks!

Thank you very much!
