### ISSUE TITLE
prestashop stock bug when qty less than zero ( negative number)

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#11953]
Prestashop stock bug when qty less than zero ( negative number )

Using PS1.7.4.4

![prestashop stock bug1](https://user-images.githubusercontent.com/22105014/50551451-6c0e5c00-0c78-11e9-94a7-e6b1609155a9.jpg)

![prestashop stock bug2](https://user-images.githubusercontent.com/22105014/50551456-77618780-0c78-11e9-804a-668775179862.jpg)

The actual stock settings have been set to not accept orders when stock is zero. So it should not display -1. In manually changing the stock figure to zero or +1 the correct 'stock or 'no stock' images show correctly.

**Comment by khouloudbelguith** [comment]
Hi @gray-b 

Thanks for your report.
Here's the PR: #8478 to solve the issue.
Thanks to check and feedback.

Thanks,
Khouloud

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
