### ISSUE TITLE
PS 'private note' on admin/order page does not work

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#11954]
PS 'private note' on admin/order page does not work. 

Using PS 1.7.4.4

![prestashop private note](https://user-images.githubusercontent.com/22105014/50551499-52214900-0c79-11e9-9123-f76b0d5eed4d.jpg)

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

I manage to reproduce the issue with the last version : PS 1.7.5.0.
We will see how to fix it.

Thanks,
Khouloud

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

After some tests with other shops.
I did not manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.0.
It is OK.
I attached a video record.
https://drive.google.com/file/d/1Sk46PnL7zLebXS9WE9lFeqUM1te_fwKg/view
The customer private note will be, only be displayed (not send!) to the employees, not to the customer him/herself. It's a field where you can write about that customer, for example, communication with the customer ("customer contacted us about shipping on 7 June"), problems with the customer (late payer, frequently asking for refunds, etc). The employee dealing with this customer can read these notes and uses this info when dealing with the customer.
Thanks to check & feedback.

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
The private comment is well saved

Best regards.

**Comment by gray-b** [comment]
So this function of 'private note' is only a one off note. It does not retain all the previous notes entered. Previous notes are over written ?

**Comment by khouloudbelguith** [comment]
@gray-b, no, it is just a note will be displayed to the employees, does not retain all the previous notes.
Thanks!
