### ISSUE TITLE
no robots.txt after update to 1.7.5.0 with 1-click upgrade

### ISSUE THREAD

**Issue by novallis** [PrestaShop/PrestaShop#11952]
Robots.txt is gone after upgrade from 1.7.4.4 to 1.7.5.0 with 1-click upgrade (latest version)

**Comment by rdy4ever** [comment]
You can generate it from Traffic and SEO:
![image](https://user-images.githubusercontent.com/12268701/50546478-efa45a80-0c30-11e9-90c9-b52b070336de.png)

**Comment by khouloudbelguith** [comment]
Hi @novallis,

Could you please regenerate your robots.txt from Configure => Shop parameters => Traffic & SEO => Generate robots.txt file.
Thanks to check and feedback.

Thanks,
Khouloud

**Comment by novallis** [comment]
Regenerated and OK, but:
Maybe it is better do not delete or overwrite existing robots.txt and also htaccess in admin-folder because the may be customized. If this works for htacces in root why not for robots.txt and htaccess in admin?

Anyway, thanks for help and answer,
regards

**Comment by khouloudbelguith** [comment]
Hi @novallis,

After the generation of the htaccess files and robots.txt, they return to these intial ways.

Thanks,
Khouloud

**Comment by khouloudbelguith** [comment]
Hi @novallis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
