### ISSUE TITLE
Password with the character \ doesn't work in BO

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11959]
Hello,
I just notice than password with the character \ doesn't work to connect to the BO.

1. Go to 'Team'
2. Create an account
3. Write the password with \ , for example: 1234\56789
4. Save
5. Notice you can save it without issue.
6. Try to connect with this account and password.
7. See the message "The employee does not exist, or the password provided is incorrect."

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen 

I manage to reproduce the issue with the last version PS 1.7.5.0.
We will see how to fix it.

Thanks,
Khouloud
