### ISSUE TITLE
Currency decimal points do not show correctly, and summary figures are not correct.

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#11956]
Currency decimal points do not show correctly, and summary figures are not correct.

Using PS1.7.4.4

![prestashop-summary1](https://user-images.githubusercontent.com/22105014/50551560-5306aa80-0c7a-11e9-99b5-e8ab1a5229a6.jpg)

This has a knockon effect with invoices.

**Comment by khouloudbelguith** [comment]
Hi @gray-b 

Could you please add steps to reproduce your issue in a new comment.

Thanks,
Khouloud

**Comment by gray-b** [comment]
Sorry - I do not seem to be able to replicate problem.

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
