### ISSUE TITLE
Upgrading PS1.7.4.2 to PS1.7.5 does not complete using 1-click stops with 7000 files to go.

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#11958]
Upgrading PS1.7.4.2 to PS1.7.5 does not complete using 1-click

I have tried a number of times in upgrading to PS1.7.5 but the upgrade window stops with about 7000 files left to process. The number 7000 is not consistent every time I upgrade, but its an average.

No error message is thrown, it just stops. All the other buttons on the page works, so I can get out of it, and then try another upgrade. But still it fails.

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

What is the exact version of the module 1-click upgrade?

Thanks,
Khouloud

**Comment by gray-b** [comment]
module 1-click version 4.5.1

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
