### ISSUE TITLE
Google Sitemap - incorrect "Home"

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#11964]
Google Sitemap module v3.2.2 for PS 1.6.1.x is generating wrong URL link for root category = home.

**To Reproduce**
Visit the sitemap.xml and you will found a 404 error url like:

`<url>
<loc><![CDATA[https://www.angelovintage.com/en/2-home]]></loc>
<priority>0.8</priority>
<lastmod>2017-01-16T08:59:54+01:00</lastmod>
<changefreq>daily</changefreq>
</url>
`

**Screenshots**
I provide a sample sitemap URL affected by 2-home problem. It happens in every languages
https://www.angelovintage.com/1_en_0_sitemap.xml

**Additionnal information**
PrestaShop version: 1.6.1.18
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Thanks,
Khouloud

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Best regards,
Khouloud
