### ISSUE TITLE
Typos in Prestashop 1.7.5.0 DB upgrade

### ISSUE THREAD

**Issue by ndegory** [PrestaShop/PrestaShop#11994]
**Describe the bug**

Upgrading Prestashop to 1.7.5.0 generates error messages related to the DB upgrade, and doesn't leave the DB with the expected changes.

**To Reproduce**
1. Install Prestashop in a version lower than 1.7.5.0 (i.e. 1.6.1.23), with 1-click module up to date
2. Execute the 1-click upgrade procedure
3. Check the logs in the browser, or in admin/autoupgrade/tmp/log.txt

**Screenshots**

```
[2019-01-01 00:52:40]
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.5.0
            1060 in ALTER TABLE `ps_supply_order_receipt_history`
  CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '',
  CHANGE `employee_lastname` `employee_firstname` VARCHAR(255) DEFAULT '': Duplicate column name 'employee_firstname'</div>
  
  [2019-01-01 00:52:40]
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.5.0
            1060 in ALTER TABLE `ps_product`
  CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL,
  CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL: Duplicate column name 'supplier_reference'</div>
  
  [2019-01-01 00:52:40]
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.5.0
            1060 in ALTER TABLE `ps_stock_available`
  ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'</div>
```

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2 (fpm)

All issues are related to file _install-dev/upgrade/sql/1.7.5.0.sql_.

- ALTER TABLE `PREFIX_stock_available` is duplicated 
- ALTER TABLE `PREFIX_supply_order_receipt_history` tries to rename employee_lastname to employee_firstname
- ALTER TABLE `PREFIX_product` tries to rename reference to supplier_reference

**Comment by matks** [comment]
Hi and thanks for the report 😉 we already got the bug report in https://github.com/PrestaShop/PrestaShop/issues/11812 and it's fixed in https://github.com/PrestaShop/PrestaShop/pull/11814

**Comment by ndegory** [comment]
Thanks @matks, sorry for the duplicate.

**Comment by khouloudbelguith** [comment]
Duplicate of #11812
