### ISSUE TITLE
Cannot download language pack when using install with index_cli

### ISSUE THREAD

**Issue by pveron** [PrestaShop/PrestaShop#11998]
Obtain error when using index_cli to install fresh downloaded prestathop 1.7.5.0

php /****/install/index_cli.php --domain=www.****.fr --db_server=localhost --db_name=**** --db_user=**** --db_password=**** --language=fr --prefix=pscha63w_ --firstname="****" --lastname="****" --name="****" --password=**** --email=****
Errors :
Cannot download language pack "fr"

Same error when i remove --language parameter

php /****/install/index_cli.php --domain=www.****.fr --db_server=localhost --db_name=**** --db_user=**** --db_password=**** --prefix=pscha63w_ --firstname="****" --lastname="****" --name="****" --password=**** --email=****
Errors :
Cannot download language pack "en"

PrestaShop version: 1.7.5.0
PHP version: PHP 7.0.33-0+deb9u1 (cli)

NB : I found an issue in #10161. When changing the source code in src/PrestaShopBundle/Install/Install.php as explained in #10161#issuecomment-418660717 the install (at least in english) works.

**Comment by khouloudbelguith** [comment]
Hi @pveron,

Could you please try with this line command

`php ProjectFolder/install-dev/index_cli.php --language=en --country=fr --domain=xxx --db_server=xxx --db_user=root --db_name=developbranch --db_password=xxx --firstname=Demo --lastname=Prestashop --email=demo@prestashop.com --password=prestashop_demo --db_create=1`

thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @pveron,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by pveron** [comment]
Install works but only in english

I just test again with all theses

--language=en --country=fr
--language=fr --country=fr
--language=fr

and i only have english installed prestashop
