### ISSUE TITLE
Product stock not working PS 1.7.4

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#11999]
Product stock is not working on combinations.

When entering 5 voor comb A and 0 for comb B in BO, both shows "in stock" FO.
Also when allowing backorders, status is not being refreshed to actual status.

When entering 5 for comb A and 5 for comb B, and order 6, it still shows "in stock"'. while it should show "backorder" (since stock is 5 and not 6).
When adding to cart, it shows nothing, but when returning to product page , product page still shows same amount as before ordering and adding to cart (in stead of changing to default value again which is 1) and all combinations are showing "backorder" in stead of "in stock".
When editing the amount to 4 (which are in stock) it still does not change and still shows "backorder" (while it should show in stock until you order more then 5).

**Comment by khouloudbelguith** [comment]
Hi @loetje88,

I did not manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1A-F3qD8GXGTyOdSvi_iEET1whpRgcdyb/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by loetje88** [comment]
Hi Khouloud,

You have recorded without status on FO.

I have attached 2 videos from my ps 1.7.4.
There are no error reports available since it does not give an error.


https://www.dropbox.com/sh/h9c60fws1ctinjc/AAA1P_w5J5-o1g7pKV8Lwxsda?dl=0

thanks!

**Comment by khouloudbelguith** [comment]
@loetje88, could you please share me a video record.
I downloaded the file provided but I cannot open those records.
Thanks!

**Comment by loetje88** [comment]
Hi khouloud,

What do you mean y video record?
These were the video records from camtasia, is the problem in the file extension?

thanks!

**Comment by khouloudbelguith** [comment]
Hi @loetje88,

Yes, there is a problem with the `camrec` extension.
Thanks!

**Comment by loetje88** [comment]
Hi Khlouloud,

Sorry for that! Didnt thought of it.

I have uploaded them in AVI, will that work?
https://www.dropbox.com/sh/h9c60fws1ctinjc/AAA1P_w5J5-o1g7pKV8Lwxsda?dl=0

**Comment by khouloudbelguith** [comment]
@loetje88, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.4.4 & the default theme provided by PrestaShop.
I attached a video record
https://drive.google.com/file/d/1-RybGQ5dPQdMtJ3T8Pk6O7QOjAC6cnKN/view
Did you a custom theme? have you tried to contact the theme author about your issue?
Thanks!

**Comment by loetje88** [comment]
hi khouloud,

I noticed that indeed in the default theme it is working!
i have mailed the theme developer for this matter.

Sorry to take up your time, and thanks for the help!

**Comment by khouloudbelguith** [comment]
@loetje88, it's not the default theme, provided by Prestashop, we can't do anything with this, they are the only ones to help you with it.
I close the issue, feel free to open a new one when needed.
Thanks!
