### ISSUE TITLE
Search reindex not working 1.6.1.4 and also after upgrade to 1.6.1.23

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12002]
Any ideas why can't add more than 971 products?
![search](https://user-images.githubusercontent.com/8243273/50599817-69497c00-0eaf-11e9-93c0-7ff283797cad.png)

Also notticed that some of the products missing from the admin area but they are still in database... 

Thanks for hints

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment]
@PrestaShark, I tried with PS1.6.1.23 & it is ok.
![image](https://user-images.githubusercontent.com/16067358/50603297-57210b00-0eba-11e9-8ba0-f0f963e83eb9.png)
Thanks!

**Comment by ghost** [comment]
Something was mismatched with database. After clean and fresh product upload everything is fine now. Closed. Thanks for Your time @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@PrestaShark, thanks for your feedback.
Feel free to open a new when needed.
Thanks!
