### ISSUE TITLE
nginx url rewrite doens't work on some pages

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12018]
prestashop 1.7.5
Informazioni sul server Linux #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64
Versione software del server: nginx/1.14.1
Versione di PHP: 7.2.13
follow #11948 if I active nginx as engine, and active url rewrite, some of my page doesn't work with rewrite:
https://www.100asa.it/it/index.php?controller=pricesdrop
https://www.100asa.it/it/index.php?controller=newproducts
https://www.100asa.it/it/index.php?controller=bestsales

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

I did not manage to reproduce your issue with PS 1.7.5.0 & Server software version: nginx/1.14.0.
All the pages are well displayed.
I attached a video record.
https://drive.google.com/file/d/1LEgGbTEZdWOLEqsox_z1R-X9WlnYspeH/view
You need to check your server configuration as described in this file
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
Thanks to check & feedback.

**Comment by PierreRambaud** [comment]
Hi @centoasa 
I create a pull request to inject multilang & multishop configuration: https://github.com/PrestaShop/PrestaShop/pull/12082/files#diff-b115851dfa6156b9d45986fb7d75c601R103
Let's try and tell me if everything is ok for you
