### ISSUE TITLE
problem directory autoupgrade 1.6.8

### ISSUE THREAD

**Issue by arg73** [PrestaShop/PrestaShop#12020]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by arg73** [comment]
i have a problem with autoupgrade 1 click 1.6.8
after backup there is this message
[ERROR] /homepages/25/d497952429/htdocs/admin9776/autoupgrade/latest/prestashop does not exist or is not a directory.

**Comment by khouloudbelguith** [comment]
Hi @arg73,

Thanks for your report.
We need more details to understand your issue
 - Version you started from: [e.g. 1.7.1.0]
 - Version you upgrade to: [e.g. 1.7.4.0]
 - Way of upgrade: Web?
 - Step concerned: [e.g upgrade DB] 
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Thanks!

**Comment by arg73** [comment]
i think i have a problem of directory
started version 1.5.6.0
upgrage 1.7.5
 Notice: Undefined index: files in /homepages/25/d497952429/htdocs/cache/smarty/compile/6f/db/83/6fdb83b34086a56c79b9285abe15305f68d7355d.file.view.tpl.php on line 260
message error 

Version de PHP: 5.6.39 
my filezilla
![image](https://user-images.githubusercontent.com/46370249/50681111-83e43800-100a-11e9-96f2-52ad2d87b76f.png)

debut : 

[DEV] ajax request : upgradeNow
Downloaded archive will come from https://download.prestashop.com/download/releases/prestashop_1.7.5.0.zip
MD5 hash will be checked against ae5cf6b2798a2cb489fd6529c08ef127
[DEV] ajax request : download
Téléchargement de https://download.prestashop.com/download/releases/prestashop_1.7.5.0.zip
Sauvegarde du fichier dans /homepages/25/d497952429/htdocs/admin9776/autoupgrade/download/prestashop.zip
download directory has been emptied
Téléchargement terminé.
[DEV] ajax request : unzip
"/latest" directory has been emptied
Using class ZipArchive...
Archive extracted
[DEV] ajax request : removeSamples
[DEV] ajax request : backupFiles
1 fichiers à sauvegarder.
sauvegarde des fichiers initilialisée dans auto-backupfiles_V1.5.6.0_20190104-101821-11692080.zip
Using class ZipArchive...

end : 

85 tables have been saved.
[DEV] ajax request : upgradeFiles
[ERROR] /homepages/25/d497952429/htdocs/admin9776/autoupgrade/latest/prestashop does not exist or is not a directory.

**Comment by khouloudbelguith** [comment]
Hi @arg73,

The 1-click upgrade module cannot make an upgrade from PS1.5 to PS1.7.5.
Also, the  1-click upgrade module version +4.0.0 has been reworked internally for PrestaShop 1.6 & 1.7.
The objective of this latest version 1-click upgrade module is to have a single module version to handle these PrestaShop upgrades:
1.6 >> to >> 1.6 / 1.7
1.7 >> to >> 1.7.
About PS1.5, there are two ways to upgrade PrestaShop:

- Automatic
- Manual

For more information, you can follow this documentation: http://doc.prestashop.com/display/PS15/Updating+PrestaShop
Thanks!

**Comment by arg73** [comment]
thanks
please can you give me  the file zip of the old version of 1-click upgrade which propose de take this : vers 1.5 to vers 1.6
of prestashop

**Comment by khouloudbelguith** [comment]
Hi @arg73,

As described here https://addons.prestashop.com/en/data-migration-backup/5496-.html, you can use the 1-click upgrade v1.6.8 to make an upgrade PS1.5 to PS1.6.

-  install the autoupgrade module
-  Download the zip of PrestaShop 1.6.1.23
-  Put it in the folder admin / autoupgrade / download
-  in the configuration page of the module select "local archive" as a channel
-  Specify the version to which we are upgrading (example: 1.6.1.23)
-  Launch the upgrade

As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks!

**Comment by arg73** [comment]
thanks a lot for your help
all is good now

best regard
thierry

**Comment by khouloudbelguith** [comment]
Hi @arg73,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
