### ISSUE TITLE
Multiple free shipping vouchers give order total error - The discount is incorrect

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#12024]
**Describe the bug**
in cart class
public function getOrderTotal
when using the flag Cart::ONLY_DISCOUNTS
the returned value will sum up the free shipping vouchers two times.
So if a customer has two free shipping vouchers and use both at the same time, the value returned from this function will be the shipping cost x 2.

**To Reproduce**
Create two vouchers for free shipping.
Add both vouchers to the cart.
check the return value of the call to this function on the cart.

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

I manage to reproduce your issue with PS1.7.5.0, it is added to our debug roadmap.
Your ticket is a duplicate of #11722
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11722

**Comment by Robin-Fischer-PS** [comment]
Issue https://github.com/PrestaShop/PrestaShop/issues/11722 is now fixed, but the PR does not fix this issue, so I reopen it :)

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

I did not manage to reproduce the issue with 177x (1775) and 178x
https://drive.google.com/file/d/1fWMLe869WzzCOogFU0T_RAKAGbDDRCsV/view?usp=sharing
I will close the issue.

Thank you!
