### ISSUE TITLE
Can't delete product item or product image

### ISSUE THREAD

**Issue by rafaviana** [PrestaShop/PrestaShop#12029]
After the update to 1.7.5.0 it's not possible to do some tasks, for example: remove a product item or remove an image from a product. Check image attached to see the error I get 

Anyone can help with this?

<img width="545" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/5817213/50691732-85712880-1029-11e9-9e0c-868f07134133.png">

**Comment by khouloudbelguith** [comment]
Hi @rafaviana,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rafaviana** [comment]
@khouloudbelguith here are some more info, I hope it can help
<img width="1211" alt="screen shot 2019-01-04 at 2 35 09 pm" src="https://user-images.githubusercontent.com/5817213/50693170-1e09a780-102e-11e9-9a24-06e18e59761e.png">

I don't know which path I can find the PHP log related with this issue… I'm sending the one there is in the root folder
[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/2727394/error_log.txt)
[server log.txt](https://github.com/PrestaShop/PrestaShop/files/2727399/server.log.txt)

Debug from catalog page:
![notice undefined index manufacturer_rule 500 internal server error](https://user-images.githubusercontent.com/5817213/50694612-44314680-1032-11e9-93d1-6eb373c4ebaa.png)

Debug from product page:
![notice undefined index manufacturer_rule 500 internal server error 1](https://user-images.githubusercontent.com/5817213/50694655-64610580-1032-11e9-9a08-5a5c7fd92a36.png)


Prestashop version: 1.7.5.0

Thanks!

**Comment by khouloudbelguith** [comment]
@rafaviana, you have problems with the configurator module.
Thanks to disable it, try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback!

**Comment by rafaviana** [comment]
@khouloudbelguith configurator module is disabled and I clear the cache as you suggested but it's still not working. I forgot to mention this error in browser console:
```
Uncaught ReferenceError: $ is not defined
    at override-autocomplete.js:165
    at override-autocomplete.js:61
```

**Comment by khouloudbelguith** [comment]
@rafaviana, could you please check in your folder path if you have any overrides(controller/classes/modules..) which are not compatible with PS1.7.5.
You can find in the /ProjectFolder/overrides/
Thanks!

**Comment by rafaviana** [comment]
@khouloudbelguith that it very hard for me to know, I don't have enough knowledge of PHP to check that :/

**Comment by khouloudbelguith** [comment]
@rafaviana, in your ProjectFolder, you can check if you have any new overrides created.
https://github.com/PrestaShop/PrestaShop/tree/develop/override/classes ( => by default)
https://github.com/PrestaShop/PrestaShop/tree/develop/override/controllers ( => by default)
https://github.com/PrestaShop/PrestaShop/tree/develop/override/modules ( => by default)

Thanks!

**Comment by rafaviana** [comment]
So I asked the developer of configurator module and he fix something related with the module. There are no PHP errors right now.

But the fact that I can't delete an image is still there… I will share a video to help understand the issue
[AwesomeScreenshot-2019-01-04T17-18-47-063Z.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2727908/AwesomeScreenshot-2019-01-04T17-18-47-063Z.webm.zip)

In the video it's not possible to see but I was with the browser inspector opened and when I click "remove" a class "modal-open" is added to the body and the console is empty

**Comment by rafaviana** [comment]
Debug mode for product page:
![notice undefined index manufacturer_rule 500 internal server error 2](https://user-images.githubusercontent.com/5817213/50701469-d4c55200-1045-11e9-94c0-ca8438d58e04.png)

![notice undefined index manufacturer_rule 500 internal server error 3](https://user-images.githubusercontent.com/5817213/50701476-d727ac00-1045-11e9-9972-ad5dd0043c86.png)

**Comment by khouloudbelguith** [comment]
Hi @rafaviana,

For this product, have you any manufacture assigned for this product, you can find it in the Product details => Options Tab, on the bottom page?
you have this error "undefined index: manufacturer_rule", have you any module related to this error?
Thanks!

**Comment by rafaviana** [comment]
Hi @khouloudbelguith 
There's no manufacture on that page… I can't figure out what's wrong with this PS installation :/

**Comment by rafaviana** [comment]
So, let's keep things organized. I'm sorry for all the messages.

The problem is: I have some products to delete and I can't do it. When I click to delete the product prestashop freezes, I'm forced to refresh the page.
I have the following error in the browser console:
```
Uncaught Error: Syntax error, unrecognized expression: [here goes product descritption]
    at Function.t.error (main.bundle.js:formatted:40355)
    at t.tokenize (main.bundle.js:formatted:40679)
    at t.select (main.bundle.js:formatted:40696)
    at Function.t [as find] (main.bundle.js:formatted:39917)
    at De.fn.init.find (main.bundle.js:formatted:40793)
    at new De.fn.init (main.bundle.js:formatted:40814)
    at De (main.bundle.js:formatted:39733)
    at i (main.bundle.js:formatted:51902)
    at e.value (main.bundle.js:formatted:51914)
    at new e (main.bundle.js:formatted:51890)
```
This error is only visible in the pages I can't delete

**Comment by khouloudbelguith** [comment]
@rafaviana, those products which you can not delete them, are they created manually or imported by csv file?
Have you tried to do the same action when debug mode is enabled? is there any exception displayed?
Thanks!

**Comment by rafaviana** [comment]
@khouloudbelguith I created the products manually
When I tried to enable debug mode I can't open any page, I got this error:
![screen shot 2019-01-23 at 11 30 44 am](https://user-images.githubusercontent.com/5817213/51603671-5cde9f00-1f02-11e9-910b-665a8e844e47.png)

I need to solve that issue first, I think…

Thanks!

**Comment by rafaviana** [comment]
Error log from admin folder:
```
[23-Jan-2019 11:35:02 Europe/Lisbon] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of type Symfony\Component\HttpFoundation\ParameterBag as array in /home/temosonline/public_html/src/Adapter/Security/Admin.php:91
Stack trace:
#0 /home/temosonline/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(111): PrestaShop\PrestaShop\Adapter\Security\Admin->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#1 /home/temosonline/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /home/temosonline/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfon in /home/temosonline/public_html/src/Adapter/Security/Admin.php on line 91
[23-Jan-2019 11:38:03 Europe/Lisbon] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/temosonline/public_html/modules/jscomposer/include/classes/shortcodes/vc-row.php on line 61
```

**Comment by khouloudbelguith** [comment]
@rafaviana, as I expected before you have an override which not compatible, it is not a PrestaShop core.
You need to navigate to your Project_Folder/override/classes/ => you will find an override of the Dispatcher.php class.
![image](https://user-images.githubusercontent.com/16067358/51604537-5c97d100-1f0d-11e9-89fc-95438bd6ca90.png)

By default, doesn't exist https://github.com/PrestaShop/PrestaShop/tree/develop/override/classes, you should remove it.

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
Thanks!!

**Comment by RajatYadavIndia** [comment]
Disable Advanced Stock Managment for the Product or set the stock to zero.
