### ISSUE TITLE
robot module disallow

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12032]
Prestashop 1.7.5
Linux #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
Apache
Version PHP: 7.2.13
default prestashop robots file disallow /modules, so search engine look at module folder.
but my psfeeder works only on module folder--> https://www.100asa.it/it/module/ps_feeder/rss?id_category=0&orderby=date_upd&orderway=desc

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Could you please add steps to reproduce the issue in a new comment.
Thanks!

**Comment by centoasa** [comment]
As I said, google always watch /module
If you inspect the robots.txt disallow is on /modules folder. But, for example, this 
https://www.100asa.it/it/module/ps_feeder/rss?id_category=0&orderby=date_upd&orderway=desc
Is on /module folder. 
Please see this attached image get by mu cloudflare account: http://nimb.ws/2L5eBW
Is it right? I hope I’m clear

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for this clarifications.
I tried to install the ps_feeder module, we need to navigate to this link `http://xxxx/en/module/ps_feeder/rss` which is on the /modules folder.
![image](https://user-images.githubusercontent.com/16067358/50764801-2c490500-1274-11e9-8262-530d109bee71.png)
But when I generate the robots.txt file, => I found the `Disallow: /modules/`.
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith Do you have also this issue on 1.7.4.4 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

With PS1.7.5.0, there is `Disallow: /modules/`
![image](https://user-images.githubusercontent.com/16067358/50773231-953e7600-1290-11e9-87d8-2047b7084199.png)
But with PS1.7.4.4, I found `Disallow: */modules/`
![image](https://user-images.githubusercontent.com/16067358/50773250-a5eeec00-1290-11e9-8017-37068239f1b6.png)
Thanks!

**Comment by marionf** [comment]
So, it's a regression when you generate robots.txt file ?

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

to more understand the issue, can you please provide us your file robots.txt.
Also, we need to know your exact attending, http://xxxx/en/module/ps_feeder/rss which is on the /modules folder so it is not indexed when we have Disallow: /modules/?
Thanks!

**Comment by centoasa** [comment]
Also, we need to know your exact attending, http://xxxx/en/module/ps_feeder/rss which is on the /modules folder so it is not indexed when we have Disallow: /modules/?---> it's right!

**Comment by khouloudbelguith** [comment]
@centoasa, thanks for your feedback.
Can you please provide us your file robots.txt
Thanks!

**Comment by centoasa** [comment]
https://drive.google.com/file/d/1USMQMqw027LwsHlvBoHUoNSXn1Ej_3w-/view?usp=sharing

**Comment by khouloudbelguith** [comment]
ping @marionf what do you think?
Thanks!

**Comment by marionf** [comment]
It's the normal behavior if ps_feeder is not indexed because you have Disallow: /modules/ in your robotos.txt file
If you want it to be indexed you should edit your robots.txt file

**Comment by centoasa** [comment]
Sorry I was not clear. 
My question was: why robot file disallow modules folder, instead (for example) ps_feeder is in module folder? I don’t want search engine index my feed, so I think robot would have disallow module folder (it’s right?)

**Comment by marionf** [comment]
If I well understand, you want module folder to be indexed except ps_feeder module, right ?

**Comment by centoasa** [comment]
I think it would be better exclude full module folder

**Comment by marionf** [comment]
Your ps_feeder module isn't indexed by Google currently

![image](https://user-images.githubusercontent.com/13449658/50848340-4d911a80-1374-11e9-82aa-848417931539.png)

**Comment by centoasa** [comment]
the point is not ps_feeder, but the /module folder
as you can see here https://s.nimbusweb.me/share/2422954/f1dzqudxds8m4fnw76w2 google bot index the /module folder

**Comment by marionf** [comment]
I don't understand, you was talking about ps_feeder ?
What is this screenshot ?

**Comment by PierreRambaud** [comment]
As I understand, it is because your are running a multishop instance.
https://github.com/PrestaShop/PrestaShop/pull/9462/files break this.

**Comment by centoasa** [comment]
@marionf we’re talking about disallow module folder from searching engine. My screenshot to see how google index the module folder. 
@Pierre my Prestashop isn’t multi shop.

**Comment by marionf** [comment]
Thanks to @PierreRambaud for explanations
In fact, it happens because you have several languages installed
We will see how to fix it :)

**Comment by centoasa** [comment]
@marionf @PierreRambaud Yes, it's right: I've 2 languages, ITA+ENG
