### ISSUE TITLE
FrontController::addJqueryUI() is not working

### ISSUE THREAD

**Issue by rGaillard** [PrestaShop/PrestaShop#12035]
**Describe the bug**
FrontController:: addJqueryUI() is not working, indeed, the $component variable is not used in the method....

**To Reproduce**
Try to register any jqueryui plugin.

**Additionnal information**
PrestaShop version: 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @rGaillard,

Thanks for your report.
@eternoendless @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by PierreRambaud** [comment]
Not sure we can change the behavior of this method because of this pull request: https://github.com/PrestaShop/PrestaShop/pull/6785

**Comment by PierreRambaud** [comment]
Hi @rGaillard ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!
