### ISSUE TITLE
Used base price is wrong with specific price and combinations

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#12039]
**Describe the bug**
When you add a specific price, you can uncheck "base price" in order to define your own base price.
If you define a base price pour product and another base price for combinations, you'll be a bad calculated discount.

**To Reproduce**
1. Go to demo_1 product
2. Add a new specific price for all combination (only new base price). In screenshoot, 50 €.
3. Add a new specific price for a single combination (base price AND % discount). In screenshoot, 100 € + 70%
4. See error in front end, combination's price is 50 * 1.2 (VAT) * 0.7 instead of 100 * 1.2 (VAT) * 0.7 (see screenshot.

**Screenshots**
This is backoffice prices' configuration:
![image](https://user-images.githubusercontent.com/6622400/50756269-e41de880-125b-11e9-87d2-f3fb30daa9cf.png)

How we can see this bug in frontoffice:
![image](https://user-images.githubusercontent.com/6622400/50756328-1fb8b280-125c-11e9-8938-79a279a48d99.png)

**Additionnal information**
PrestaShop version: 1.6.23
I don't reproduce it onto 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @Max84,

Thanks for your report.
I manage to reproduce the issue with PS16.1.23, with PS1.7.5.0 =>OK.
![image](https://user-images.githubusercontent.com/16067358/50757661-5db7d580-1260-11e9-8dec-3278b2bec535.png)
For the PS1.6, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/8099 to solve the issue.
But, as there are too many changes in the theme, we can't merge this to prevent breaking other themes, but the fix remains valid if someone wants to apply it manually.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!
