### ISSUE TITLE
After submitting the Contact form, it is white screen when I set both settings to ON.

### ISSUE THREAD

**Issue by eumedia** [PrestaShop/PrestaShop#12036]
**Describe the bug**
After submitting the Contact form, it is white screen when I set both settings to ON.
Module Manager > Modules > Contact form > Configure > Parameters
![seting](https://user-images.githubusercontent.com/46417881/50735452-a3689580-11af-11e9-948b-d4ef5f17f9e9.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @eumedia,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - contactform version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by eumedia** [comment]
Fix undefined INTL_IDNA_VARIANT_UTS46 if intl ICU < 4.6
https://github.com/PrestaShop/PrestaShop/pull/11995

**Comment by khouloudbelguith** [comment]
Hi @eumedia,

So, your issue is fixed after applying this patch #11995?
Thanks!

**Comment by eumedia** [comment]
YES :-) OK thank you

**Comment by khouloudbelguith** [comment]
@eumedia, thanks for your feedback.
Since it is fixed, I will close the issue.
Feel free to open a new one when needed.
Thanks!

**Comment by eumedia** [comment]
Yes, after applying this patch email, it works correctly, thank you.
Will this update be in the new version of PS 1.7.5.1?
When will PS 1.7.5.1 be available?

**Comment by khouloudbelguith** [comment]
@eumedia, yes, it will be added in the next version PS1.7.5.1.
It is not planned yet the exact date of the release of PS1.7.5.1.
Thanks!
