### ISSUE TITLE
Use PrestaShop/decimal to perform price operations

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#12051]
PHP, alongside most programming languages, has [floating point precision issues](http://php.net/manual/en/language.types.float.php). PrestaShop has many float operations involving prices, which results in rounding errors.

To improve precision, all price calculations should be performed using arbitrary-length precision operations instead of floating point operations.

Since the [BC Math extension](http://php.net/manual/en/book.bc.php) is not available everywhere, we developed the [Decimal library](https://github.com/prestashop/decimal), which provides an object-oriented, strongly typed interface to basic arithmetic operations, using BC math if available, and a custom made implementation otherwise.

We should replace all floating point operations using this library.

**Comment by Progi1984** [comment]
After [discussion on a PR](https://github.com/PrestaShop/PrestaShop/pull/16150#discussion_r352083528) with @jolelievre, What is planned for Javascript ?

**Comment by eternoendless** [comment]
@Progi1984 we can use Big.js for that https://github.com/MikeMcl/big.js

**Comment by LouiseBonnard** [comment]
Since #21372 has been merged, I close this issue and add it to the _done_ work. :-)
