### ISSUE TITLE
Create an AbstractCollection class to manage all collections

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#12065]
### Description of the need

In various places of PrestaShopCode we use `Collections`, they are usually strongly typed
and we need to implement them each time, meaning losing time and duplicating code.

Collection Examples:
- PrestaShop\PrestaShop\Core\Backup\BackupCollection
- PrestaShop\PrestaShop\Core\Addon\Theme\ThemeCollection
- PrestaShop\PrestaShop\Core\Addon\AddonsCollection
- PrestaShop\PrestaShop\Core\Grid\Collection\AbstractCollection
- ...

### Possible solution
We need a generic `AbstractCollection` class that will serve as a base for all other collections.

**Interfaces**

Like the existing collections it should implements a few interfaces (for backward compatibility
AND for usability):
- Iterator
- ArrayAccess
- Countable
- Traversable
(some of these interfaces are probably duplicates)

**Associative or Not Associative**

Depending on the context the collection might be a simple integer indexed list or an associative list (each element is identified by a specific key).
The ideal would to manage both cases in the same class, but this requires to be really vigilant when removing keys:
- associative: removing an element simply "unset" it from the list and lets the container array as is
- non associative: removing a key "unsets" it but the array must remain consistent (no "holes" in the keys) so we need to splice the array instead of simply unset it

If we want to manage these two behaviors we need to check if the container array is associative or not, so that we know if we *unset* or *splice* it.

Potential issues:
If you store a collection of database objects using their id as a key, you might end up with an array considered "non associative" whereas the key hold a real meaning. Then if you remove an element and we automatically splice the array then all they index will be offset.

This raises questions:
- Should we really manage both behaviors?
- Should the behavior be a setting?
- Should we have a core abstract class and two abstract sub classes? (this would allow to separate the specific methods: `add($element)` != `set($key, $value)`

**Basic methods**
Here are the basic method expected from a collection
- `add($element)`
- `set($key, $value)`
- `remove($element)`
- `toArray()` equivalent `all()`
- `setElements(array $elements)`

Some nice to have ideas:
- `addBefore($position, $element)`
- `addAfter($position, $element)`
- `addAtBeginning($element)`
- `addAtEnd($element)`
- `first()`
- `end()`

**Type Checking**

Additionally it needs to allow (optional) type checking, so we can set the expected elements type and the class internally checks any push to the collection and throws an Exception is the expected type does not match. (if no type is set, then no checking is done)

**Strong Types and abstract Inheritance**

Of course the Abstract class can't have strongly typed prototype so it needs to offer generic methods, but it does not mean you don't want to implement a strongly typed

One solution is to implement basic method as protected in the abstract and let the child class implement the real typed public methods. We can also have a BasicCollection with weakly typed public methods.

Example:

```php
abstract class AbstractCollection()
{
    protected function doAdd($element)
    {
        ...
    }
}

class BasicCollection extends AbstractCollection
{
    public function add($theme)
    {
        $this->doAdd($theme);
    }
}


class ThemeCollection extends AbstractCollection
{
    public function add(Theme $theme)
    {
        $this->doAdd($theme);
    }
}
```

**Comment by eternoendless** [comment]
What about https://github.com/doctrine/collections/ ?

**Comment by jolelievre** [comment]
I looked into it, it covers our needs except for strong typing and type checking
So I think we still need our custom collection but it's a good place to start

About the associative issue I suggested they didn't manage it, they simply unset the removed element, I guess we can have the same approach

https://github.com/doctrine/collections/blob/73b0d9ac2fd3d5aecc94f1e217b408fe59e3d265/lib/Doctrine/Common/Collections/ArrayCollection.php#L127

**Comment by mickaelandrieu** [comment]
> I looked into it, it covers our needs except for strong typing and type checking

This is the main reason I haven't introduced an abstraction for our collections as one of the biggest advantages is to be able to validate what we manipulate (add, remove, get) on our collection and avoid the shameful `foreach($items as $item) { if ($item instanceof Foo) { doStuff() }}` in our code.

From this point of view, removing the strong typing make collections useless compared to a simple associative array.

Also, I'm not in favor of abstracting functions because - for a domain point of view - not all collections need the same functions.

Instead of having ``$products->filter(function () {});`` don't you think it's better to provide the right functions who do what we really need, like ``$products->getActiveProducts()`` ?

This is why some collections in the Grid component have some specific helpers (like addBefore/addAfter) because for columns in a grid it makes sense: but is it useful for all columns? I'm not sure.

Still... it's not a bad idea if we manage to control the typing, what do you think of something like that?

For instance:

```php
class AbstractCollection
{
    public abstract function getClass();

    public function add($item) {
        if (!$item instanceof $this->getClass()) {
            throw new InvalidArgumentException('Expected ... , get ...');
        }
    } 
}
```

I'm not that sure that all collections needs add, get, remove ... the same way as I'm not sure that all object needs getter and setters 👼 

> PS: for the Grid component, I'd like we don't use an abstract from the core as I still plan to extract it to its own package 👍

**Comment by jolelievre** [comment]
@mickaelandrieu yes that's exactly what I had in mind, except the type checking could be optional so it would be something like:

```php
public function add($item) {
        if ($this->getClass() && !$item instanceof $this->getClass()) {
            throw new InvalidArgumentException('Expected ... , get ...');
        }
    } 
```

But what bothers me with `public function add($item)` in the abstract is that you lose the strong typing in the prototype of the child class.

About what you said for addBefore/addAfter indeed it might not be needed for all collections, but we can implement these methods in another abstract class:

```php
abstract AbstractOrderableCollection extends AbstractCollection {
    public function addBefore($position, $item);
    public function addAfter($position, $item);
}
```

But anyway even though the abstract has lots of default methods, nothing forces you to use them all so it's not that much of a problem.

Finally I agree with about `$products->getActiveProducts()` but since you need to create a `ProductCollection` anyway you can add the methods depending on your needs:

```php
class ProductCollection extends AbstractCollection {
    public function getClass() {
        return Product::class;
    }

    public function getActiveProducts() {
        return $this->filter(function (Product $product) {
            return $product->isActive();
        });
    }
}
```
