### ISSUE TITLE
Product images in multishop

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#12061]
**Describe the bug**
If you run multishops, and have one product in both shops but different images in the two shops. There is no way in the BO to see what images are connected to what shop.

**To Reproduce**
1. Go to a product in BO
2. Select one of your two multishops in the context.
3. Upload a new image
4. In the front end, the images is only displayed in the correct shop, but in BO you will see all images no matter what shop context you select, there is also no way to tag the image to another shop.

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Thanks for your feedback
I manage to reproduce the issue
when a specific shop is selected in the BO => Product detail page => all the images are displayed for the different shops.
![image](https://user-images.githubusercontent.com/16067358/50826625-6f6eab00-133c-11e9-9047-f10030e5774f.png)
In FO => OK.
Thanks!

**Comment by 123monsite-regis** [comment]
hi @marionf ,

some improvments about this are propose by jocel1  on : https://github.com/PrestaShop/PrestaShop/pull/11028

regards

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15909
