### ISSUE TITLE
BO: Price was changed from 8,20 to 8,199999 when I save - Same for the unit price

### ISSUE THREAD

**Issue by polo195pl** [PrestaShop/PrestaShop#12078]
**Describe the bug**
Price change

**To Reproduce**
1. Install 1.7.4.x -> 1.7.7.0 
2. Go to add new product
3. Type price without tax: 8,20
4. Click textarea or anything but didnt get out
5. Look at price it is 8,1999999

**Screenshots**

https://drive.google.com/file/d/1_ErIqOLLnGueEiUnIGw3wRP8qElIVJA5/view

**Additionnal information**
PrestaShop version: from 1.7.4.0 to 1.7.7.0 (maybe in the all 1.7.x)
PHP version: 7.0.33 & 7.2

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 / PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1_ErIqOLLnGueEiUnIGw3wRP8qElIVJA5/view
We will see how to fix it.
Related to #9972
Thanks!

**Comment by polo195pl** [comment]
Well i have more similar prices that's one from price tax inc, price tax exclude. I send more after 6 PM UTC-2

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0beta1
https://drive.google.com/file/d/1UZ_muoI3L5Q051AjKY29HvAEZqYNhR1l/view

Thanks!

**Comment by khouloudbelguith** [comment]
In the FO, The price is well displayed
![image](https://user-images.githubusercontent.com/16067358/59772558-e7ee7600-92a3-11e9-92f8-2d357e0ab083.png)

![image](https://user-images.githubusercontent.com/16067358/59772566-eae96680-92a3-11e9-99f0-c2edf4000977.png)

In the BO => Order details page => OK
![image](https://user-images.githubusercontent.com/16067358/59772643-10767000-92a4-11e9-93d6-05ac1373abd0.png)
![image](https://user-images.githubusercontent.com/16067358/59772676-208e4f80-92a4-11e9-99a4-fe65ba53d945.png)

In the invoice & the delivery slip => price is OK.
![image](https://user-images.githubusercontent.com/16067358/59772760-4d426700-92a4-11e9-9fd9-244a35491e3a.png)
![image](https://user-images.githubusercontent.com/16067358/59772791-5a5f5600-92a4-11e9-92e7-9be0d05a7f43.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

Same issue for the unit price
https://drive.google.com/file/d/1rKCdRmuj6VTErZzYlpJZLc5SP6pabz-s/view?usp=sharing

Thanks!

**Comment by polo195pl** [comment]
@jolelievre @khouloudbelguith @kpodemski this issue still exists in PrestaShop 8.1.0 also 8.1.1
