### ISSUE TITLE
Wrong language link on mail when change order status on BO - only mass update

### ISSUE THREAD

**Issue by RomanXT** [PrestaShop/PrestaShop#12070]
There was a problem with links in emails when changing the status of the BO.
Part of the problem was removed by the amendment:
https://github.com/PrestaShop/PrestaShop/pull/4393/files

Now the problem of links has been with mass status changes
![2019-01-08_162812](https://user-images.githubusercontent.com/43031929/50840317-7d372700-1362-11e9-9bec-92440969ed3d.png)

**Comment by khouloudbelguith** [comment]
Hi @RomanXT,

Could you please add steps to reproduce the issue in a new comment.
What is the exact version PrestaShop did you use?
Thanks!

**Comment by RomanXT** [comment]
Prestashop 1.6.1.20
Email template default

1. I mark orders
2. mass actions
3. change the order status
4. I choose the status
5. status update
then in email there are links not in the language of the order / customer

Customer from DE gets:
https://shop.led-glass.eu/pl/moje-konto
This is correct:
https://shop.led-glass.eu/de/mein-konto

**Comment by khouloudbelguith** [comment]
@RomanXT, thanks for this clarifications.
I managed to reproduce the issue with PS1.6.1.23.
![image](https://user-images.githubusercontent.com/16067358/50843069-4fed7780-1368-11e9-8619-bb373087f99c.png)
![image](https://user-images.githubusercontent.com/16067358/50843356-d2763700-1368-11e9-9c2c-32ec63e3d2cb.png)
But, it is OK with PS1.7.5.0,
![image](https://user-images.githubusercontent.com/16067358/50843383-defa8f80-1368-11e9-9de5-e959bc534d69.png)
![image](https://user-images.githubusercontent.com/16067358/50843471-09e4e380-1369-11e9-9d33-612ca3fad666.png)

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!

**Comment by RomanXT** [comment]
Poor customer approach, we've spent just over 2,000 euros on the add-ons in your store.
We have a very improved shop and now I have to change to the shit version 1.7??, NO thanks.

**Comment by RomanXT** [comment]
I solved the problem myself, if someone has a problem with this, I invite you to contact me:  https://shop.led-glass.eu/en/contact-us (Webmaster)
