### ISSUE TITLE
Faceted search ->  RuntimeException

### ISSUE THREAD

**Issue by polo195pl** [PrestaShop/PrestaShop#12071]
**Describe the bug**
Faceted search not work

**To Reproduce**
I made update from 1.7.4.3 to 1.7.5.0 without error's
Go to category page
Select variables from filters
In console have 500 error -> 
Trying to unset the index id of the LazyArray PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductListingLazyArray already defined by a method is not allowed

**More info**
When i copy GET url from request and past directly in work, for a moment, when i try change filters i have 500 in browser console 

**Screenshots**
Any

**Additionnal information**
PrestaShop version: 1.7.5.0 upgraded from 1.7.4.3
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0 after upgrade from PS1.7.4.2.
What is the exact version of the ps_facetedsearch did you use?
THanks!

**Comment by polo195pl** [comment]
Hi @khouloudbelguith i have  2.2.1

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Also, thanks to uninstall the module ps_factedsearch, remove the ps_factedsearch folder from Project_PrestaShop/modules/ & try to install this module again.
Thanks to check & feedback.

**Comment by polo195pl** [comment]
@khouloudbelguith ok i check :) i write soon

**Comment by khouloudbelguith** [comment]
@polo195pl, thanks!
Waiting for your feedback.

**Comment by polo195pl** [comment]
@khouloudbelguith well i test it, and didnt help :(

**Comment by khouloudbelguith** [comment]
@polo195pl, could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by polo195pl** [comment]
http://hardleo.stronazen.pl/info.php

**Comment by khouloudbelguith** [comment]
@polo195pl, thanks for your feedback.
In my case, I did not manage to reproduce the issue, @marion what do you think?
Maybe related to this PR: https://github.com/PrestaShop/PrestaShop/pull/10230
Thanks!

**Comment by polo195pl** [comment]
Well my mistake ;) I have override in ProducListingFrontController :(
