### ISSUE TITLE
Il y a 1 erreur      Une erreur s'est produite pendant l'envoi du message

### ISSUE THREAD

**Issue by fouad1962** [PrestaShop/PrestaShop#12072]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @fouad1962,

We manage to reproduce the issue.
Your ticket is a duplicate of #9566
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9566
