### ISSUE TITLE
Problem recomputing order price

### ISSUE THREAD

**Issue by QuatorzeJr** [PrestaShop/PrestaShop#12081]
-----------------------------------------[EN]-----------------------------------------

Hello,
I set up the Colissimo module of Common Services with a dedicated Colissimo carrier created in Prestashop to offer delivery for a basket over 100 € for all orders placed in France.

That is to say that when a user buys a product at 140 euros with a coupon code of 30% (excluding delivery costs), the order goes to 98 €.

So the user has to pay the delivery.

Here is the problem :
The order is charged as a delivery charge, whereas it should charge additional delivery charges for that carrier. (because the order is less than 100 €).

I have the impression that Prestashop takes into account the basic price of the product, but does not recalculate after reduction.

Can you tell me how to fix this problem?

-----------------------------------------[FR]-----------------------------------------

Bonjour, 
J'ai paramétré le module Colissimo de Common Services avec un transporteur créé Colissimo dédié dans Prestashop afin d'offrir la livraison pour un panier supérieur à 100€ pour toutes commandes passées en France.

C'est à dire que lorsqu'un utilisateur achète un produit à 140 euros avec un code promo de 30% (hors frais de livraison), la commande passe à 98€. 

Donc l'utilisateur doit payer la livraison.

Le problème est le suivant : 
La commande passe en frais de livraison offert, alors qu'elle devrait demander les frais de livraison supplémentaires pour ce transporteur. (car la commande est inférieur à 100€).

J'ai l'impression que Prestashop prend en compte le prix de base du produit, mais ne recalcule pas après réduction.

Pouvez-vous me dire comment régler ce problème ?

Prestashop 1.7.4
<img width="627" alt="capture d ecran 2018-12-06 a 11 12 34" src="https://user-images.githubusercontent.com/45938192/50887898-a43e3900-13f4-11e9-9fc8-4f571de077ae.png">
<img width="1210" alt="capture d ecran 2018-12-06 a 11 11 59" src="https://user-images.githubusercontent.com/45938192/50887900-a43e3900-13f4-11e9-8678-c6359e86ce7e.png">

**Comment by khouloudbelguith** [comment]
Hi @QuatorzeJr,

This issue is added to our bug roadmap.
Your ticket is a duplicate of #9540
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #9540
