### ISSUE TITLE
Exception on link widget page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12093]
**Describe the bug**
Exception on link widget page on develop branch
Module version: 3.0.2

**To Reproduce**
1. Go to Design > Link widget
2. See error

**Screenshots**
![capture d ecran_887](https://user-images.githubusercontent.com/13449658/50912081-91962500-1431-11e9-9ac1-84bf3c0dd1e3.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Here's a PR: https://github.com/PrestaShop/ps_linklist/pull/60 to fix the issue.
Thanks!
