### ISSUE TITLE
Disable possibility of enabling "Send email to customer" from order statuses list if no template is selected

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#12105]
**Describe the bug**
If you enable option `Send email to customer` from the grid and there is not any template choosen, when you change an order to this status it returns error `Error: invalid e-mail template`

**To Reproduce**
1. Create a new order status
2. Go to order statuses list
3. Enable `Send email to customer` from the grid clicking on the cross icon
4. Change an order to this status

If you enable this option in the order status edit page it doesn't happen because template dropdown is required.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/15104724/50965830-6fed7a00-14d3-11e9-98b9-dca9404b103e.png)

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
We need to enable the mode debug to reproduce the issue.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1qLYvzA2UFtxb3qnExr3_Um4LGf1eihay/view
We will we see how to fix it.
Thanks!

**Comment by idnovate** [comment]
Sorry you are right, I didn't notice it. Error is displayed from this function:

```
public static function dieOrLog($msg, $die = true)
{
    if ($die || (defined('_PS_MODE_DEV_') && _PS_MODE_DEV_)) {
        die($msg);
    }
    return PrestaShopLogger::addLog($msg);
}
```

**Comment by marionf** [comment]
We could delete the column "send email to customer" from the list

**Comment by idnovate** [comment]
Or disable callback so this column is not clickable.

**Comment by matks** [comment]
Done in https://github.com/PrestaShop/PrestaShop/pull/17215
