### ISSUE TITLE
When adding product to cart, other product in cart disappears.

### ISSUE THREAD

**Issue by ThomasJKlip** [PrestaShop/PrestaShop#12102]
**Describe the bug**
Hi guys

Some customers complain about a problem what occurs when using our shop. When they are shopping for products, sometimes happends that when adding a product to the cart, another product in the cart disappears. It happends fully random and i cant reproduce the problem, but various customers contacted us for the problem.

The only problem i can reproduce what could be related to the problem is; 
Sometimes when adding a product to cart, it gives me the popup it added something to the cart but the cart stays empty. (see screenshot)
![schermafbeelding 2019-01-10 om 11 31 19](https://user-images.githubusercontent.com/46560180/50962796-50eaea00-14cb-11e9-860b-68070cb1e1e9.png)

Does anyone have i idea where i have to search for?

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @ThomasJKlip,

Thanks for your report.
Recently, we have made some changes to fix those issues:
#8752
#8774
#8607
Did you add the product to cart before the page is fully loaded?
Do you have a slow shop?
Thanks!

**Comment by ThomasJKlip** [comment]
Hi @khouloudbelguith 

Thanks for your reaction.

I cannot identify the problems with the issues you mention to be honest.

i did not add the products to the cart before the page is fully loaded. The webshop is not really fast but to call it slow is a bit to much. Caching is disabled because i thought that was the a possible problem.

Loading time homepage:
![schermafbeelding 2019-01-10 om 12 28 44](https://user-images.githubusercontent.com/46560180/50966051-1174cb80-14d4-11e9-8fee-804bb8e8eb9d.png)

Loading time category page:
![schermafbeelding 2019-01-10 om 12 31 30](https://user-images.githubusercontent.com/46560180/50966064-16d21600-14d4-11e9-9fce-42cfb74f94d6.png)

**Comment by khouloudbelguith** [comment]
@ThomasJKlip We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ThomasJKlip,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
