### ISSUE TITLE
Grant read access automatically when a user has create, update, delete rights ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12109]
Right now, for BO pages, you must set up for each existing profile whether it has read, create, update or delete rights.

However for some pages, having only the create or update rights means: you can modify the page's content but you cannot see it.

Idea: shall we implement a rule that says "whenever a page requests _read_ access to be read, if the logged in user has _create_, _update_ or _delete_ rights this grants him _read_ access too ? 

This can be implemented in 2 ways:
1) in the security process, by granting automatic _read_ rights when _create_, _update_ or _delete_ are granted
2) in the Permissions page, by automatically checking the checkbox "read" whenever one of the "create", "update" or "delete" checkboxes are checked

**However** I think this behavior should be only implement on BO pages. Webservice access rules should not be modified. If I'm not wrong, permissions both manage the BackOffice access and the Webservice access. So this means option 2) should not be done.

**Comment by matks** [comment]
ping @eternoendless @mickaelandrieu @Quetzacoalt91 @PierreRambaud @tomlev @jolelievre @jocel1 for dev team
ping @colinegin for product team

**Comment by Quetzacoalt91** [comment]
If we keep the current management of permission, with all the checkboxes, this makes sense to keep these permission independent. The webservices should not impacted by the decision taken here as they work with another access system.

Your idea could be nice if we rework all the system with a maximum access level per controller / module.

**Comment by matks** [comment]
What if we only enable this behavior for migrated pages ? Webservice behavior will be left untouched.

**Comment by marionf** [comment]
I will be more for solution 1)
Waiting for a decision before to validate #12077 & #12099

**Comment by colinegin** [comment]
I don't really like the idea of having 2 different behaviours for legacy and symfony pages...
This will be harder to explain to the user.

Option 1 seems interesting, but it means there could be a difference between what the permission page shows (ex : if a user has permission to create, update, delete on a specific page but not to read it) and the reality of the user's permissions ?

**Comment by PierreRambaud** [comment]
FYI, as I know this is the original behavior in many controllers: https://github.com/PrestaShop/PrestaShop/pull/12099/files#diff-5e786a90d0fd87f3057a4a9d7936a2d1L87

**Comment by matks** [comment]
Looks like we dont have an agreement so better not change the system.
