### ISSUE TITLE
Duplicate CLDR Repository Symfony service

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12118]
There is a duplicate definition of CLDR Repository Symfony service:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/localization/cldr.yml
and
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/cldr.yml

```
  prestashop.core.localization.cldr.repository:
    class: 'PrestaShop\PrestaShop\Core\Cldr\Repository'
```

TO DO:
- check these services have not been released with 1.7.5, else it's a BC to remove one of them (in this case, deprecate or use an alias)
- find all usages of both services
- remove the less relevant service and migrate usages of this one to the remaining one

**Comment by matks** [comment]
See
- https://github.com/PrestaShop/PrestaShop/commit/99aec1594844fc6c94f69756a6296d8f615f4a7d
- https://github.com/PrestaShop/PrestaShop/pull/11894#discussion_r246063536

**Comment by tomlev** [comment]
https://github.com/PrestaShop/PrestaShop/pull/10455 uses second one (core/cldr.yml)

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/10455 has been merged
So we can now tackle this issue 👍

**Comment by matks** [comment]
All right, no CLDR service in 1.7.5.x so we can merge the 2 services without creating a BC
