### ISSUE TITLE
During installation is not checked presence of php-mbstring

### ISSUE THREAD

**Issue by MalikKrak** [PrestaShop/PrestaShop#12121]
During installation (of 1.7.5.0) is not checked presence of php-mbstring, which will cause error 500 when opening orders in Backend and of course on other places.

**Comment by khouloudbelguith** [comment]
Hi @MalikKrak,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9583
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9583
