### ISSUE TITLE
Permissions Notice - Advanced Parameters > Team > Employees > Permissions

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#12126]
**Describe the bug**
Upgraded to 1.7.5 from 1.7.4.2
It is OK on vanilla installation of 1.7.5

See the prinscreen:
![permissions](https://user-images.githubusercontent.com/31688689/51046622-da331700-15c6-11e9-9147-f11f6d1a19e2.png)

**To Reproduce**
1. Go to Advanced Parameters > Team > Employees > Permissions
2. Click on Permissions

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.6.30

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by mrabsinthe** [comment]
It has been fixed. According to our host, they've removed the deny code which existed in .htaccess file and the issue has been resolved. I believe that the .htaccess file was at /home/user/public_html/cache location.

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
