### ISSUE TITLE
var_dump show to much data 1.7.5

### ISSUE THREAD

**Issue by polo195pl** [PrestaShop/PrestaShop#12131]
**Describe the bug**
When we make a vardamp or print_r some variable we have for examples output like: "array(6) { ["title"]=> string(0) "" ["canonical"]=> NULL ["meta"]=> array(4) { ["title"]=> string(47) (...)" but when i try made {$product|@var_dump} or {$product|@print_r} i have a lot's of data for examples: strings from admin dashobard, translations from diffrent parts of system and a lots of more (looks like a var_dump full shop) 

**To Reproduce**
1. Go to themes/your_theme/catalog/produc.tpl
2. type {$product|@var_dump} or {$product|@print_r}
3. See result

**Screenshots**
![image](https://user-images.githubusercontent.com/22961693/51074033-e0360000-1679-11e9-9c83-148d12e88275.png)

**Additionnal information**
PrestaShop version: 1.7.5 from 1.7.4.3 on fresh install i have that same problem
PHP version: 7.0.33

**Comment by rdy4ever** [comment]
How about ditching the `@` and just try `$product|var_dump`?

**Comment by polo195pl** [comment]
@rdy4ever that same

**Comment by kpodemski** [comment]
oh, look at this @jocel1 :D

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
When I add this line code `{$product|@var_dump}` in the `/Project_PrestaShop/themes/classic/templates/catalog/product.tpl`, I have a lot of data.
[1750.pdf](https://github.com/PrestaShop/PrestaShop/files/2758678/1750.pdf)
I tried with PS1.7.4.4, I have a lot of data, but there are no strings from the admin dashboard, translations.
[1744.pdf](https://github.com/PrestaShop/PrestaShop/files/2758692/1744.pdf)
Thanks!

**Comment by jolelievre** [comment]
Hello @polo195pl 

This behavior is because `$product` is not an array any more but a `ProductLazyArray`, it includes more data and logic than the former array
(see https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductLazyArray.php for more details)

If you need to display the initial product array (for debug) you can use the `jsonSerialize` method, here is how you can use it in your smarty template:

```
{$product->jsonSerialize()|@var_dump}
```

I hope this will help you.

**Comment by polo195pl** [comment]
Ok thx all :)

**Comment by polo195pl** [comment]
@jolelievre its ok BUT if PrestaShop want to use LazyArray maybe the good point is used it as default? If in the future other variables also use LazyArray, I think that would be a good solution. On the other way, using methods of some objects directly in tpls is a reversing of the development of the project, not its development.
