### ISSUE TITLE
Paypal split order information

### ISSUE THREAD

**Issue by Partenopeo83** [PrestaShop/PrestaShop#12137]
Hi, i use paypal module.
Sometimes the an order paid with paypal is split in two orders with same reference.
In the most of cases the first order contain the correct total of the entire order while in the second there is the partial total.

Apparently the items in order not have differences, the carrier is the same and quantities are ok.

I can't understand why prestashop/paypal split the order, the customer pay correct total but i have problem to manage the order.

The prestashop show message where inform me that the customer have paid more less about the total, where, for prestashop, the total is the sum of two orders.Oviusly not is so, the correct total is the total of the first order

What are the situations where prestashop/paypal split the order?
How can i disable this situation?

Thanks for help

**Additionnal information**
PrestaShop version:  1.7.4.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Partenopeo83,

I did not manage to reproduce the issue with PS1.7.5.0 & the PayPal module v4.4.2.
The split order is done if you have 2 different carriers for different products added to the cart.
I attached a video record
https://drive.google.com/file/d/11MiJ7TRW5xdmOwO-O3v7HIiQqAI9eguC/view
Thanks to check & feedback.

**Comment by Partenopeo83** [comment]
Ok, thanks for specification.
Unfortunately i have this problem with paypal and products with same carrier.
I'don't know why paypal/prestashop split order into two parts, apparently there aren't this settings.

I don't know if it is paypal problem. I can't contact them or there is a mail where i can contact the support?

Thanks

**Comment by khouloudbelguith** [comment]
@Partenopeo83, PayPal module is provided by our partners.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it: https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks!
