### ISSUE TITLE
iframe issues in PS 1.6, 1.7.4.4, and 1.7.5

### ISSUE THREAD

**Issue by RUMBuilder** [PrestaShop/PrestaShop#12135]
Hello all,

Have checked every setting i can find, enabled the setting in backoffice to allow iframes, and have even followed some of the "solved" posts out there related to this. I can not for the life of me, seem to figure out how to utilize ANYTHING related to iframes  - specifically youtube embed code, in PS 1.7.5. I had this issue also in 1.6(when i was just learning PS) and also in 1.7.4.4. 

I've tried using the built in controls to add video via embed code, manually adding the iframe code, etc. I've tried modifying and using the tinymce extended editor and related files etc, and nothing. Every time I add even just the freaking WORD "iframe" in PS, whether it's on the home page, product info, product description, cms pages etc, it just fails. I either get a product that say "cannot save changes", or a 403 error, etc. 

Certainly I'm not THAT unique? Any help would be appreciated. I've posted in the PS forums and have had ZERO help there. Also called PS and they never got back to me.

**Additional information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @RUMBuilder,

With PS1.7.5.0, in the BO => Shop Parameters => General page, I enabled the `Allow iframes on HTML fields` option.
In the Bo => Product page, in the description, I added a video.
![image](https://user-images.githubusercontent.com/16067358/51190700-1aeea100-18e3-11e9-9861-e93b7beba65d.png)
In the FO, this video is displayed.
![image](https://user-images.githubusercontent.com/16067358/51190732-2d68da80-18e3-11e9-9ce1-a34ee56efd96.png)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by RUMBuilder** [comment]
> Hi @RUMBuilder,
> 
> With PS1.7.5.0, in the BO => Shop Parameters => General page, I enabled the `Allow iframes on HTML fields` option.
> In the Bo => Product page, in the description, I added a video.
> ![image](https://user-images.githubusercontent.com/16067358/51190700-1aeea100-18e3-11e9-9861-e93b7beba65d.png)
> In the FO, this video is displayed.
> ![image](https://user-images.githubusercontent.com/16067358/51190732-2d68da80-18e3-11e9-9ce1-a34ee56efd96.png)
> We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!


Have tried that, still doesn't work. I've tried manually inserting the iframe code, i've tried using the method you suggest, etc... still nothing. as soon as i go to save, i either get the toast "red box" at the top right of PS saying "unable to update settings", or sometimes it throws a 403 error.

For the red warning box, I'm getting this in console if it helps:
---------------------------
Failed to load resource: the server responded with a status of 400 ()
object.gif:1 Failed to load resource: the server responded with a status of 404 ()
main.bundle.js:292 POST https:(url hidden) 403
send @ main.bundle.js:292
ajax @ main.bundle.js:292
send @ form.js?1.7.5.0:635
(anonymous) @ form.js?1.7.5.0:843
dispatch @ main.bundle.js:292
_.handle @ main.bundle.js:292
VM2661:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.5.0:687)
    at u (main.bundle.js:292)
    at Object.fireWith [as rejectWith] (main.bundle.js:292)
    at i (main.bundle.js:292)
    at XMLHttpRequest.<anonymous> (main.bundle.js:292)
------------------------------

**Comment by khouloudbelguith** [comment]
@RUMBuilder, if you enable the debug mode, is there any exception displayed?
It could be caused by a custom module or an override.
Thanks!

**Comment by RUMBuilder** [comment]
@khouloudbelguith 
I've enabled debug, and then attempted to insert a YT iframe to generate the same error... I'm not familiar with PS debug mode, can you direct me as to what I need to provide you for review? Thanks a ton for any help you've given/will give.

**Comment by khouloudbelguith** [comment]
@RUMBuilder, could you please check the permission of your Project, it could be a problem, also thanks to checking the exact value of memory_limit on your server, the minimum required value is **64MB**.
Thanks to check & feedback.

**Comment by RUMBuilder** [comment]
> @RUMBuilder, could you please check the permission of your Project, it could be a problem, also thanks to checking the exact value of memory_limit on your server, the required value is **64MB**.
> Thanks to check & feedback.

@khouloudbelguith thank you for the reply!

currently memory is set to 512M. does it need to set exactly to 64M? or is that minimums?
(UPDATE - tried it at 64M, still didn't work)

as for permissions, i've played with those, in some cases even trying 777 for root(temporarily), but other than possibly needing to set some specific file permission, i'm not sure. do you know of a specific file/permission? 

thanks again for the response. this has been a problem for months. now i have a live functioning business site that's driven a TON by YT, and i can't embed an iframe...lol

**Comment by khouloudbelguith** [comment]
Hi @RUMBuilder,

Usually, directories have: 755 files: 644
You can check this: http://doc.prestashop.com/display/PS17/Installing+PrestaShop
There is a part with information about recursive write permissions for directories.
About your issue,  despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by RUMBuilder** [comment]
> I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

$279, $399, $699..... i bet you do! 

I'm not claiming it's a PS core bug, but given that I've tried all the suggested settings from various resources, I still don't understand why it doesn't work. I've reviewed the installation guide for PS, and I did in fact USE the auto installer and it showed NO compatibility issues with my server settings. So is there some other more detailed "required server settings/PS settings/permissions/etc" that you can provide?

**Comment by khouloudbelguith** [comment]
@RUMBuilder, you can follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks!

**Comment by RUMBuilder** [comment]
> @RUMBuilder, you can follow this link: https://github.com/PrestaShop/php-ps-info
> phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
> 
> 1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
> 2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
> 3. Now you can view all of the information about PHP for your server for that particular directory.


Ok, done that... see below. Everything checks out it seems. Still have the same issue. Suggestion? Thanks!



![php prestashop info 1](https://user-images.githubusercontent.com/46640217/51791725-aa5e4480-216c-11e9-9c75-40a1bf95a7d8.png)

**Comment by khouloudbelguith** [comment]
Hi @RUMBuilder,

Yes, it seems to be OK.
But as I said before, we could not reproduce your issue with the provided information.
With fresh install 1.7.5.0 & PS1.7.4.4. => OK.
Thanks!

**Comment by RUMBuilder** [comment]
> Hi @RUMBuilder,
> 
> Yes, it seems to be OK.
> But as I said before, we could not reproduce your issue with the provided information.
> With fresh install 1.7.5.0 & PS1.7.4.4. => OK.
> Thanks!

Thanks for the input. I'd rather not take the chance of something being corrupted by doing a "fresh install", and risk having to rebuild/restore. I literally JUST did a brand new, fresh, clean folder install of 1.7.5.0, so I still don't understand the issue. Will continue to investigate. 

Thanks again, open to any other additional comments if anyone has ideas.

**Comment by RUMBuilder** [comment]
@khouloudbelguith 
How about another issue i hadn't notice until attempting to test again on a custom page/cms/etc. When I click Design>Pages, i get "Access Denied"... and i'm the admin. ???

**Comment by khouloudbelguith** [comment]
Hi @RUMBuilder,

This issue is different from this one, can you open a new one with more information about your configuration.
Thanks!

**Comment by RUMBuilder** [comment]
Why was this closed? I still don't have a solution, was hoping someone else might have better input?
