### ISSUE TITLE
Add to cart on Safari does not work

### ISSUE THREAD

**Issue by fadupla** [PrestaShop/PrestaShop#12145]
Tested on http://demo.prestashop.com/fr/?view=front and on multiple clean install (PS 1.7.4.0 and 1.7.5.0 with or without classic theme).
Add to cart does not work, see picture : 

![capture d ecran 2019-01-14 a 14 03 51](https://user-images.githubusercontent.com/897717/51114473-b3aeef00-1805-11e9-9369-58f499c428b2.png)

When "Add to cart" button is pressed, the success popin open but displays "There is 0 product in your cart" and a total of 0$.

_Edit : versions : 
Safari version 12.0.2
Mac OS version 10.12.6_

**Comment by khouloudbelguith** [comment]
Hi @fadupla,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0, with Mac OS version=Mojave & browser=Safari & browser_version=12.0.
I attached a video record.
https://drive.google.com/file/d/189AU75tpT-ZZKo4rD9Yy175-ubPcCfXd/view
Thanks to check & feedback.

**Comment by fadupla** [comment]
Hello @khouloudbelguith 

Thank you for your message.

Here is the video record : https://drive.google.com/open?id=1h9uJKZ8egAqoH41EDc1j4ckATIWsLQ90

And the screenshots of the versions : 

![capture d ecran 2019-01-15 a 11 29 00](https://user-images.githubusercontent.com/897717/51174803-fbdb1980-18b8-11e9-9dc1-0826e3d5f928.png)

![capture d ecran 2019-01-15 a 11 29 05](https://user-images.githubusercontent.com/897717/51174808-fda4dd00-18b8-11e9-86c8-5e8d4d0ec1eb.png)

**Comment by khouloudbelguith** [comment]
Hi @fadupla,

If you try with another version of your browser, did you manage to reproduce the issue?
I tried with Safari v11.1.2 & Mac OS Sierra 10.13.6, there no issue
https://drive.google.com/file/d/1g49qA9zYrwgRG3-svezTJ5b5hdmdQmoz/view
Also, about the demo, is not updated to the last version 1.7.5.
Thanks!

**Comment by fadupla** [comment]
Hello @khouloudbelguith 

Yes, we tried with other versions it works. Only this combo of versions doesn't work...

**Comment by khouloudbelguith** [comment]
@fadupla, thanks for your feedback.
We'll first try to reproduce it and we'll come back to you if we need more information.
Thanks!

**Comment by fadupla** [comment]
Thank you :)

**Comment by khouloudbelguith** [comment]
Hi @fadupla,

I did not manage to reproduce the issue with Mac OS High Sierra v10.13.5 & with the browser Safari v12.0.2, I attached a video record.
https://drive.google.com/file/d/1a1HKVE3s0Y2CafeoCbsLK0h5qlhj7dlm/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by fadupla** [comment]
```It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.```

http://demo.prestashop.com/fr/?view=front is hosted on your server ^^

**Comment by khouloudbelguith** [comment]
@fadupla, in my last video record, I tried also with http://demo.prestashop.com/fr/?view=front also, but I did not manage to reproduce the issue with Safari v12.0.2.
It could be a custom issue, you said also that you have the same issue with PS 1.7.4.0 and 1.7.5.0 with or without a classic theme). 
Thanks!

**Comment by amigainc** [comment]
Hi, I also meet the same problem on every latest Safari/iOS/MacOS version.
Website: https://letrocdeslutins.fr
Framework: PS 1.7.5.2
