### ISSUE TITLE
Maintenace Mode bug

### ISSUE THREAD

**Issue by jayp03** [PrestaShop/PrestaShop#12148]
Good day ! I have an issue with maintenance mode, I'm trying to activate my website but it is still in maintenance mode I don't know why.

**Screenshots**
https://snag.gy/iBwqQA.jpg
https://snag.gy/K2Pisj.jpg

**Comment by rdy4ever** [comment]
Run this SQL on your database via phpMyAdmin to take your shop out of maintenance mode manually:
`UPDATE ps_configuration SET value = "1" WHERE name = "PS_SHOP_ENABLE";`

**Comment by khouloudbelguith** [comment]
Hi @jayp03,

Thanks to run the SQL query suggested by @rdy4ever.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check & feedback.

**Comment by jayp03** [comment]
thank you guys for your help !it's working now 
the problem was because of mailchimp module 
when its activated the website doesn't work I don't know why

**Comment by khouloudbelguith** [comment]
@jayp03, thanks for your feedback.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
