### ISSUE TITLE
 Prestashop can not write to the TMP folder

### ISSUE THREAD

**Issue by AntonioManta** [PrestaShop/PrestaShop#12153]
![errore](https://user-images.githubusercontent.com/46569923/51126499-9a1ca000-1823-11e9-9f34-f493ee3de18c.jpg)

**Comment by AntonioManta** [comment]
![errore2](https://user-images.githubusercontent.com/46569923/51126654-faabdd00-1823-11e9-82cc-f6284bed6f04.jpg)

**Comment by marionf** [comment]
Duplicate of #11939
