### ISSUE TITLE
Timezone standard is ignored

### ISSUE THREAD

**Issue by michaesc** [PrestaShop/PrestaShop#12151]
### Description

World timezone standards exist, including zones UTC-12 to UTC+14, however PrestaShop chooses to ignore these standards and apply antiquated GMT identifiers and country codes instead. It's unclear when this works in practice, but at least according to **PHP Version 7.1.8** the behaviour is flawed. Trying to install PrestaShop fails with a error message:

> Your default timezone is not supported by PHP. Check for typos in your php.ini file and have a look at the list of deprecated timezones at http://php.net/manual/en/timezones.others.php.

### Reproducing

1. Install PrestaShop on a host with PHP 7.1.8
2. Begin configuration (by navigating to 'install-dev/index.php')
3. Click through 'Choose your language' and 'License agreements'
4. Observe the stated error in 'System compatibility'

### Screenshots

A screenshot exists, but it seems that this GitHub system fails to allow easy upload of images.

## Additional information

PrestaShop version: develop
PHP version: 7.1.8
Platform: Openshift Online

**Comment by khouloudbelguith** [comment]
Hi @michaesc,

I did not manage to reproduce the issue with develop branch.
I attached a video record.
https://drive.google.com/file/d/158vGHF6mgh0ozTQ-BsgoilCjk5-ciPri/view
I used PHP 7.1.20 / PHP 7.0.33
Thanks to check & feedback.

**Comment by michaesc** [comment]
> Hi @michaesc,
> 
> I did not manage to reproduce the issue with develop branch.
> I attached a video record.
> https://drive.google.com/file/d/158vGHF6mgh0ozTQ-BsgoilCjk5-ciPri/view
> I used PHP 7.1.20 / PHP 7.0.33
>
It is likely because the admin (you probably) has set a php.ini in the root or used a installation method that sets the timezone to a correct value. The bug only appears in PrestaShop (which fails to validate timezones) when a value such as 'GMT' is set before the PrestaShop installation procedure begins.

It's unclear to me if PrestaShop sets 'GMT' as a timezone, but when I build and run a container on Openshift, the installation does fail. You might try getting a Openshift Starter account if you really want to reproduce the error I have seen.

**Comment by khouloudbelguith** [comment]
@michaesc, thanks for your feedback.
Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @michaesc,

I tried to set `date.timezone = Nonsense` in my php.ini.
![image](https://user-images.githubusercontent.com/16067358/51310967-214a5d80-1a48-11e9-85e4-dbe5b583dca8.png)
When Trying to install, I have errors
![image](https://user-images.githubusercontent.com/16067358/51310905-f7913680-1a47-11e9-8836-a69f0dabadbc.png)
checked with 1.7.5.0 & develop branch.
When I apply these changes https://github.com/PrestaShop/PrestaShop/pull/12152, the error is not displayed.
In the same server, I tried to install 1744 => But the error is not displayed.
Thanks!

**Comment by eternoendless** [comment]
Hi @michaesc 

FYI, you can upload images by [dropping them in the text area](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).
