### ISSUE TITLE
Filter selector under Module Manager (responsive issue)

### ISSUE THREAD

**Issue by joelprestaworks** [PrestaShop/PrestaShop#12165]
**Describe the bug**
Module selector under module manager is not working when having too small height on view-port

**To Reproduce**
1. Go to tab Modules -> Module manager
2. Make sure to lower the height on your browser (specific devices uses different resolutions)
3. Try to sort on options through the selector to filter modules from specific categories
4. The selector will be hidden under the tab above.
5. This will result in that you can't filter on options higher up in the selector = Responsive bug.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @joelprestaworks,

I attached a video record.
https://drive.google.com/file/d/1QQ8EegHtOjF4_mpO4073l9ekqYKli4Gb/view
Thanks to check & feedback.

**Comment by joelprestaworks** [comment]
Hi,

I just watched your video and you did not do the information described under step 2. I have recorded a video for you to see what I mean:
https://www.useloom.com/share/d57472baa47e46ff84ff6cac5f77ecd3

It does not matter which browser you're using, in this test I was using Google Chrome. The issue is the view-port when having a smaller resolution on the **height** of the browser.

**Comment by khouloudbelguith** [comment]
HI @joelprestaworks,

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/51238616-9863f100-1977-11e9-877a-b8c7da47d5cb.png)
With PS1.7.4.4, the same issue.
![image](https://user-images.githubusercontent.com/16067358/51238957-67d08700-1978-11e9-9433-b0bbf51428c0.png)
We will see how to fix it.
Thanks!
