### ISSUE TITLE
Translation of Countries in PS1.7 - installation step

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12168]
**Describe the bug**
During the installation of PrestaShop, the `日本語` is selected; in Step 4: "Store information" => all Countries are displayed in English.
In fact, they are always displayed in English in any language selected.

**To Reproduce**
1. Install PrestaShop with any language different from English
2. In the in Step 4: "Store information" => all Countries are displayed in English

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/51237987-0d362b80-1976-11e9-83e7-c5ce7ae468f8.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 / 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
ping @ansar21mallouli

**Comment by Progi1984** [comment]
Found the solution : 
* Copy the file from `install-dev/langs/en/data/country.xml` to `install-dev/langs/<locale>/data/country.xml`
* Translate it.

Ping @LouiseBonnard : Is there any translations for country names ?

**Comment by LouiseBonnard** [comment]
@Progi1984, I confirm: country names are not translated.

**Comment by Progi1984** [comment]
@LouiseBonnard I have the solution. ;)

**Comment by Progi1984** [comment]
@LouiseBonnard CLDR has translations so I used it for extractions. A PR is available : #19818
