### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by Alex-2019** [PrestaShop/PrestaShop#12167]
**Describe the bug**
I dont receive mail about orders and other notifications.

**To Reproduce**
1. Go to 'Advanced Options' - 'Email'
2. Click on 'Send test email'
4. And there is no actions - I dont receive email

**Screenshots**
I added

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2.7
![2019-01-15 21_27_03-e-mail chip6 club](https://user-images.githubusercontent.com/46726370/51207897-66697500-190c-11e9-9ffc-06fe86dc7ee5.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Alex-2019,

About the technical configuration: to configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature.
Thanks to check with your host & feedback.
Thanks!

**Comment by Alex-2019** [comment]
What have they got to do with it? Mail works, I can receive and send. Only the site does not work sending. This is a prestashop problem.

**Comment by Alex-2019** [comment]
What should I set for mail to work on the site?

**Comment by khouloudbelguith** [comment]
Hi @Alex-2019,

You need to contact your host provider about this issue because it could be that sending emails is not allowed or something else.
In my case, I tried with PS1.7.5.0 & it is working, there is no problem.
I attached a video record.
https://drive.google.com/file/d/1yQF5BojMOznswyBb7JAeNEKeNv3UXCPB/view
Thanks!

**Comment by Alex-2019** [comment]
Ok. Thanks.
I think you are right. I wrote to my host.


*------------------------*
[image: motorstate] Aleksey Seminozhenko [image: YouTube]
<https://www.youtube.com/user/Motorstatecomua?sub_confirmation=1> [image:
https://t.me/MotorstateUA] <https://t.me/MotorstateUA>
<https://www.instagram.com/motorstate_com_ua/> [image: Facebook]
<https://www.facebook.com/Motorstate.cis> [image: Vk]
<https://vk.com/motorstate>
 CEO of motorstate
 mob:   +38050 931-6847
 skype: alexavias
 mail:    alex@motorstate.com.ua




чт, 17 янв. 2019 г. в 11:39, khouloudbelguith <notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@Alex-2019, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by Alex-2019** [comment]
Ok

*------------------------*
[image: motorstate] Aleksey Seminozhenko [image: YouTube]
<https://www.youtube.com/user/Motorstatecomua?sub_confirmation=1> [image:
https://t.me/MotorstateUA] <https://t.me/MotorstateUA>
<https://www.instagram.com/motorstate_com_ua/> [image: Facebook]
<https://www.facebook.com/Motorstate.cis> [image: Vk]
<https://vk.com/motorstate>
 CEO of motorstate
 mob:   +38050 931-6847
 skype: alexavias
 mail:    alex@motorstate.com.ua




чт, 17 янв. 2019 г. в 14:20, khouloudbelguith <notifications@github.com>:
