### ISSUE TITLE
Same ID (custom_fields) used in the Back Office product edition

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#12161]
**Describe the bug**
Inside the DOM, while editing a product and having a supplier inside our shop, we have two times the same ID: custom_fields

**To Reproduce**
1. Add a supplier
2. Go to the product edition
3. Check the tab "Options" source code

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @prestamodule,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.0.
![image](https://user-images.githubusercontent.com/16067358/51235224-3a331000-196f-11e9-961e-9b480fc8fe38.png)
![image](https://user-images.githubusercontent.com/16067358/51235250-4f0fa380-196f-11e9-9cea-e5bccac4ce60.png)
We will see how to fix it.
Thanks!
