### ISSUE TITLE
Prestashop Footer

### ISSUE THREAD

**Issue by jayp03** [PrestaShop/PrestaShop#12175]
Good Day ! I would like to know how to remove Prestashop footer 

https://snag.gy/td0MRI.jpg

**Comment by khouloudbelguith** [comment]
Hi @jayp03,

You can edit or remove the footer of your Prestashop by editing the file into the `themes > your_theme > templates > checkout >  _partials > footer.tpl` and the checkout file into the path `themes > your_theme > templates > checkout >  _partials > footer.tpl`
Thanks!
