### ISSUE TITLE
Wrong tax in order slip when product tax has changed

### ISSUE THREAD

**Issue by ckubitza** [PrestaShop/PrestaShop#12174]
**Describe the bug**
When an order slip is created, the current tax rule from the product is used instead of the saved one in the order detail. So when the tax rule has changed since the order was created, a wrong tax is applied to the order slip detail and this also leads to wrong totals in the order slip.

**To Reproduce**

1. Order a product so that you have a valid order with an invoice
1. Change the tax rule of this product in the product admin page so that it has a different tax percentage
1. Refund the product from the order and create an order slip
1. See that tax included values are wrong compared to those in the orginal invoice from this order

**Additionnal information**
PrestaShop version: checked in 1.7.2.1, should also be present in current version

**Fix**
see pull request

**Comment by khouloudbelguith** [comment]
Hi @ckubitza,

Before the step2, did you have a valid order (order paid)?
Step 2, did you change the tax rule of this product from the product page, or you just edited the price TTC of this product from the order page?
Thanks!

**Comment by ckubitza** [comment]
Hey @khouloudbelguith,
> Before the step2, did you have a valid order (order paid)?

I think so, the state of the order has the paid and invoice options checked.

> Step 2, did you change the tax rule of this product from the product page, or you just edited the price TTC of this product from the order page?

I changed the tax rule on the product page.

**Comment by khouloudbelguith** [comment]
Hi @ckubitza,

Thanks for your report.
I have the same issue with PS1.7.5.0
Before the changes, in the invoice pdf, I have 
![image](https://user-images.githubusercontent.com/16067358/51254677-da099180-19a1-11e9-93de-5309db051264.png)
After changing the tax rule from the product page, in the order slip, the tax is different from the invoice pdf
![image](https://user-images.githubusercontent.com/16067358/51254744-01605e80-19a2-11e9-927e-4ae0cd81fffb.png)
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 

This is the invoice

![capture d ecran_1016](https://user-images.githubusercontent.com/13449658/52847060-7f339900-310b-11e9-9514-36a63823d01d.png)

And this is the credit notes after editing the product VAT (from 20% to 10%) and refund the order.

![capture d ecran_1017](https://user-images.githubusercontent.com/13449658/52847145-b43feb80-310b-11e9-9b95-8e42fd81020e.png)

The total tax is wrong (should be 2€, as before the change), but the total tax incl (12€) is good

**Comment by jolelievre** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18023
