### ISSUE TITLE
Can't import tanzania pack

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12178]
**Describe the bug**
When you try to import Tanzania pack, you have an exception (develop branch) instead of an error message (1.7.5.1)

**To Reproduce**
1. Go to International > Localization
2. Select Tanzania
3. Click on Import

**Screenshots**

![capture d ecran_935](https://user-images.githubusercontent.com/13449658/51251796-687a1500-199a-11e9-945a-fe90a3cd8692.png)

It's working in 1.7.5.1
![capture d ecran_936](https://user-images.githubusercontent.com/13449658/51251811-76c83100-199a-11e9-8fca-76f00f84c252.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by PierreRambaud** [comment]
The PR doesn't fix the issue.
We still don't have `sw` language. Should we be able to download this language?

**Comment by PierreRambaud** [comment]
@colinegin @eternoendless @marionf Need your feedback here.

**Comment by marionf** [comment]
Maybe it's better to remove it from the list if not available, wdyt ?

**Comment by PierreRambaud** [comment]
I agree, but I'm not the one who chose :)

**Comment by colinegin** [comment]
@LouiseBonnard for you ! :)

**Comment by LouiseBonnard** [comment]
I also had difficulties when trying to import the Australian, Guiana, Kenya and Nigeria localization packs on Machine Shuffle version 1.7.5.1. Let's remove it from the list, it is useless from a language point of view as it only contains English (US) and Swahili (TZ) - whose translation does not exist in the software anymore...
🙄

**Comment by PierreRambaud** [comment]
Localization pack list came from: http://api.prestashop.com/rss/localization.xml
We don't have anything to do on the Core!

**Comment by colinegin** [comment]
Should i remove it from the kanban then ?

**Comment by PierreRambaud** [comment]
No, we still corrected the warning  and improve errors messages :)
