### ISSUE TITLE
How to translate "Tax excl." for the front-office?

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12186]
hi

where is it possible to translate "Tax excl." for the front-office? I cannot find it in the translation pages.
I've seen that these texts are from these variables like from product-prices.tpl and cart-summary-totals.tpl
{$cart.labels.tax_short}
{$product.labels.tax_long}
{$cart.subtotals.tax.label}

from the translation page it is not possible for both: theme and ps_legalcompliance module selections

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/51272374-3b455b00-19ca-11e9-9eb3-2d3281818a05.png)
![2](https://user-images.githubusercontent.com/653230/51272375-3b455b00-19ca-11e9-85bc-de5b801e213e.png)
![3](https://user-images.githubusercontent.com/653230/51272377-3bddf180-19ca-11e9-9dd8-d5f08c836d64.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

You need to navigate to your BO => IMPROVE => International => Translations page => Modify translations
1. Type of translation => Themes translations
2. Select your theme
3. Select your language
4. Click on Modify
5. Search Translations

 For example:
1. Shop > Theme > Global, you can find 
1.1 (tax incl.) => pop up add to cart / shopping cart block
![image](https://user-images.githubusercontent.com/16067358/51303334-55685300-1a35-11e9-8e43-cec0580ad304.png)
![image](https://user-images.githubusercontent.com/16067358/51303469-ba23ad80-1a35-11e9-8462-64dc056ed30f.png)
![image](https://user-images.githubusercontent.com/16067358/51303384-7af55c80-1a35-11e9-9bd2-a4ba2582d796.png)

1.2 Tax included => Product page 
![image](https://user-images.githubusercontent.com/16067358/51303404-8d6f9600-1a35-11e9-8408-18a513a983d6.png)
![image](https://user-images.githubusercontent.com/16067358/51303422-9a8c8500-1a35-11e9-9d49-65c52bcca0fc.png)

1.3 tax incl. => Checkout page
![image](https://user-images.githubusercontent.com/16067358/51303565-0c64ce80-1a36-11e9-98a0-ebe09c0f4b21.png)
![image](https://user-images.githubusercontent.com/16067358/51303579-1981bd80-1a36-11e9-82bb-9bb7bba376c1.png)
Thanks!

**Comment by Maofree** [comment]
Hi @khouloudbelguith 
with the classic theme it is ok, but for a theme of addons I cannot edit these phrases.
I tested 3 different themes and all give me no result to find (tax excl.)
you should increase the verification on the templates because they are full of bugs and are not updated by those who develop them, many companies make hundreds of templates but then have many problems

![1](https://user-images.githubusercontent.com/653230/51310672-7a65c180-1a47-11e9-8328-543f82e0548f.png)

thanks

**Comment by khouloudbelguith** [comment]
@maofree, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Maofree** [comment]
yes ok but 3 themes have the same problem
in the next months I'll develop a my own template :)

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I imported a new theme "minimal" version 3.0.4 Designed by PrestaShop & in the FO, the translations are displayed.
![image](https://user-images.githubusercontent.com/16067358/51314126-8190cd80-1a4f-11e9-817f-0d4b8318332e.png)
![image](https://user-images.githubusercontent.com/16067358/51314128-83f32780-1a4f-11e9-9279-13f2698ef28e.png)
![image](https://user-images.githubusercontent.com/16067358/51314135-86558180-1a4f-11e9-979d-38a742c61de7.png)
Thanks!

**Comment by zodit** [comment]
I have the same problem, all themes have problems with languages and i am wasting a lot of time for these issues. I think it is really wrong that you force us to use the Prestashop Back Office as the only solution possible, and "call the developer to fix it". It is a restriction unbearable, if the BO is not working as expected, and we can't have support from the developer, we are let down.

I have full access to the files and database of the website, in this situation I should be able to fix my localization problems modifying files in the filesystem and/or tables in database. 

Could you please give us clear and simple instructions on how to achieve the translation fixes MANUALLY, in fact AVOIDING the Prestashop Admin logic? This should be possible or Prestashop is really crap.
 
If modifying files and database is not enough, then tell me a PHP hack i need to run, with the required parameters, and in what file i need put that function. 

If the PHP hack is not enough, then give me clear instructions on why the themes are failing the translations, so i can check their PHP code and fix it accordingly.

Sorry if I am harsh, but this is a nightmare, i want stomp this problem once and for all.
Thank you.

**Comment by matks** [comment]
It seems there is a misunderstanding.

> I think it is really wrong that you force us to use the Prestashop Back Office as the only solution possible

In the PrestaShop Back Office, there is a tool that you can use to manage the translations. If theme uses translatable items, this tool will allow you to translate them. What is wrong about telling you "there is a tool which purpose is to solve your issue in your BO" ?

> "call the developer to fix it"

We only say this when there is an issue in the theme. If the theme uses translatable items, you can translate them. If the theme does not use translatable items, the theme developer should insert these translatable items for you to be able to translate them.

> I have full access to the files and database of the website, in this situation I should be able to fix my localization problems modifying files in the filesystem and/or tables in database.

> Could you please give us clear and simple instructions on how to achieve the translation fixes MANUALLY, in fact AVOIDING the Prestashop Admin logic?

You modify the theme files and insert translatable items. It's explained here https://devdocs.prestashop.com/1.7/themes/reference/theme-translation/ . Basically you do exactly what the developer should do. Make items translatable for them to be acknowledged by PrestaShop translation system. Then it works in BO 😄.
