### ISSUE TITLE
Disparition des Déclinaison

### ISSUE THREAD

**Issue by KevinSainclair** [PrestaShop/PrestaShop#12180]
Bonjour,

Ce matin 2 de nos articles ont perdu des déclinaisons. Apres un export, je me suis rendu compte que les déclinaisons perdues avaient toutes le même nom, à savoir le nom de l'article père.
J'arrive à retrouver les déclinaisons grâce au code unique de l'article mais impossible de rentrer dans la fiche ou la déclinaison pour remettre le nom initial.

Merci d'avance pour votre aide car si je ne retrouve pas ces déclinaisons, je ne vais plus pouvoir analyser les ventes 

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @KevinSainclair,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

PS: did you used a custom module to export products?

Thanks!

**Comment by KevinSainclair** [comment]
I'm sorry I'm not an informatics person and I won't be able to provide you those informations

What is the minimum information you need to begin to analyse the problem?

**Comment by khouloudbelguith** [comment]
@KevinSainclair, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Also, did you used a custom module to export products?
Thanks!

**Comment by KevinSainclair** [comment]
Yes We use a custom module to export products, I think that's how I was able to see the problem.
![image](https://user-images.githubusercontent.com/46752224/51260735-3aeb9680-19af-11e9-8cd9-65edb1fd1a23.png)
![image](https://user-images.githubusercontent.com/46752224/51260776-4b9c0c80-19af-11e9-9d42-41f7f2bd49a8.png)

**Comment by khouloudbelguith** [comment]
@KevinSainclair, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
