### ISSUE TITLE
Impossible to delete combinations of a product

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#12187]
**Describe the bug**
Try delete combination of a product.
There is an error in debug mode:
DELETE	xhr	403	/admin***/index.php/attribute/172?_token=tvcVWoU*****

Usually on a shared hosting server request DELETE denied (for security purposes).

This is the only one place in PrestaShop where the server request DELETE is used. In the remaining cases, the POST request was used. For example, when deleting a product, we see the following query in debug mode:
POST	xhr	200	/admin***/ajax.php?rand=15476***

This problem seriously limits using of the PrestaShop on a shared hosting.
Are there any plans to remedy this situation?

**Additionnal information**
PrestaShop version: 1.7.4.3
Server software version: Apache/2.2
PHP version: 5.6.38

**Comment by Tomskor** [comment]
Same here, this bug exist from start presta version 1.7

**Comment by khouloudbelguith** [comment]
HI @weddingtextile,

I did not manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.0.
403 error is meaning that the request was valid, but the server is refusing action. You might not have the necessary permissions for a resource.
So your issue is a server issue permission.
You need to check your host about this issue.
Thanks to check with them & feedback.

**Comment by weddingtextile** [comment]
Hi,

On my hosting it is forbidden to use the request DELETE to the server.
Usually on a shared hosting server request DELETE denied (for security purposes).
Ask the developers about this issue.
Perhaps this problem can be transferred to section "Feature request" (with high priority).

Thanks

**Comment by khouloudbelguith** [comment]
@weddingtextile, thanks for your feedback.
Could please describe with more information your feature request & describe a solution you'd like.
Thanks!

**Comment by weddingtextile** [comment]
Use POST request with function call on server.
For example, when deleting a product, we see the following query in debug mode:
POST	xhr	200	/admin***/ajax.php?rand=15476***

**Comment by khouloudbelguith** [comment]
ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by eternoendless** [comment]
Using DELETE doesn't pose a security risk whatsoever, at least not as far as I know. In any case, DELETE is part of the HTTP/1.1 standard and a fundamental feature of [RESTful web services](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URI_and_HTTP_methods). I don't see this changing in the foreseeable future.

I'd be interested to learn the reasoning behind this choice. Unless this limitation is properly justified, I'd be suspicious of your hoster's security policy, and consider moving elsewhere.

**Comment by weddingtextile** [comment]
Hello Pablo Borowicz,

Thanks for the answer.
The hosting has made the necessary settings, now it works.

Have a nice day!

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
