### ISSUE TITLE
Product Meta description gives javascript error with certain characters

### ISSUE THREAD

**Issue by Jabades** [PrestaShop/PrestaShop#12191]
In product editing formulary in backoffice, for Prestashop #1.7.5.0 when you edit the field "Meta description" and insert certain characters like <.,"'¡!¿?`´[]{}@=/%&#$| gives an javascript error. This occurs when you edit a product with these charactes saved previusly also first edition.

1. Go to "Catalog > Products"
2. Edit a product
3. Click on tab "SEO"
4. Open browser development javascript console.
5. Insert in field "Meta description" one of the following characters: <.,"'¡!¿?`´[]{}@=/%&#$|

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: Any

**Comment by khouloudbelguith** [comment]
Hi @Jabades,

In the PS1.7.4, there was a problem with a meta description which contains invalid characters => a green alert is displayed => which is wrong => any modification in this product will be not saved.
So, this issue is saved in the PS1.7.5.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/10946
with PS 1.7.5.0 when we insert in field "Meta description" one of the following characters: `<.,"'¡!¿?`´[]{}@=/%&#$|` => if you click save => a red alert is displayed
![image](https://user-images.githubusercontent.com/16067358/51315720-18ab5480-1a53-11e9-9002-5f6c1bdc2fd8.png)
Thanks!

**Comment by Jabades** [comment]
Hello,

In think is not the same issue. In my case in a clean 1.7.5.0 install (and some clients shops). I get a javascript error:
Syntax error, unrecognized expression: <.,"'¡!¿?`´[]{}@=/%&#$|

No alert alert box is displayed, only the javascript error in file "main.bundle.js"

![ps_capture](https://user-images.githubusercontent.com/35447309/51320456-27e4cf00-1a60-11e9-9f68-9faa593ee6d9.PNG)

Regards,

**Comment by khouloudbelguith** [comment]
@Jabades, yes I have the same issue in the console but after adding this expression: `<.,"'¡!¿?`´[]{}@=/%&#$|` & you try to click save => have you any a red alert?
Thanks!

**Comment by Jabades** [comment]
Hello,

No, i don't get a alert as your first capture, simply the javascript error.

But the main problem is that when edit a product with these characters in "Meta description" previusly stored, this error is triggered too. And other many javascript functions stop working for product edition. For example if you have any additional modules configuration in [Modules] tab, you can't configure it.

Regards,

**Comment by khouloudbelguith** [comment]
@Jabades, did you made an upgrade to PS1.7.5.0?
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11923 to fix the issue.
It is added to the PrestaShop 1.7.5.1.
Thanks to check & feedback.

**Comment by Jabades** [comment]
Hello,

No, i don't made an upgrade. Is a clean install.
I've try the fix and work ok.

Many thanks!!

**Comment by khouloudbelguith** [comment]
Hi @Jabades,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11911
