### ISSUE TITLE
REST API - Impossible to find right product when combination product is added in a pack

### ISSUE THREAD

**Issue by ajayak** [PrestaShop/PrestaShop#12193]
Steps to Reproduce:
1. Create a standard product with different combinations.
![image](https://user-images.githubusercontent.com/5102208/51317716-5671a280-1a7e-11e9-908f-4f39aad1a4e0.png)

2. Create a pack of products and include any 1 product from the combinations
![image](https://user-images.githubusercontent.com/5102208/51317812-92a50300-1a7e-11e9-9bbc-050b8e0c24b2.png)

3. Use PrestaShop REST API to get the (pack of product) product.

In the response, under `associations > product_bundle`, I get Id of the standard product. But it is impossible to know which one of the combination was added.

![image](https://user-images.githubusercontent.com/5102208/51317924-df88d980-1a7e-11e9-99cc-350b756dbfac.png)

**Comment by khouloudbelguith** [comment]
Hi @ajayak,

Thanks for your report.
I have the same issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/51322382-91b3a780-1a65-11e9-9d3c-78b3119e9522.png)
But it could be an improvement issue, to specify the exact combination for each product associated to the pack.
@colinegin, @marionf what do you think?
Thanks!

**Comment by MatShir** [comment]
hi @ajayak,

The information is indeed missing, is just a miss. The data is well stored on select * from ps_pack  ;
```
+-----------------+-----------------+---------------------------+----------+
| id_product_pack | id_product_item | id_product_attribute_item | quantity |
+-----------------+-----------------+---------------------------+----------+
|              15 |               5 |                        19 |        5 |
|              15 |               7 |                         0 |        5 |
|              18 |              19 |                        40 |        1 |
|              18 |              19 |                        41 |        1 |
|              18 |              19 |                        42 |        1 |
+-----------------+-----------------+---------------------------+----------+
```
Thank you for your feedback. Don't hesitate to contribute by making a Pull Request if you have the technical skills. Otherwise, it will be done by our team in the next versions.

**Comment by ajayak** [comment]
Hi @MatShir,

Is it possible to get this information from any other REST API?

**Comment by MatShir** [comment]
Hi @ajayak,

I am afraid not.
@PrestaShop/prestashop-core-developers Is that correct?

**Comment by Quetzacoalt91** [comment]
Unfortunately @ajayak, the core does not provide another API entrypoint for Pack details. If you absolutely need this information, you might need to implement your own entrypoint.

In the meanwhile, I created a PR for the next minor version which covers your needs: https://github.com/PrestaShop/PrestaShop/pull/12329
