### ISSUE TITLE
docker-compose up: No such file or directory

### ISSUE THREAD

**Issue by paparga** [PrestaShop/PrestaShop#12204]
**GUI error message**

![screenshot from 2019-01-17 20-39-50](https://user-images.githubusercontent.com/2799637/51356094-19b2a500-1a98-11e9-8feb-1bc9985381b3.png)

**Terminal error message**

prestashop-git | cp: cannot stat '/tmp/data-ps/prestashop/*': No such file or directory
prestashop-git | \n* Renaming install folder as install-dev ...
prestashop-git | mv: cannot stat '/var/www/html/install': No such file or directory
prestashop-git | \n* Renaming admin folder as admin-dev ...
prestashop-git | mv: cannot stat '/var/www/html/admin': No such file or directory

**To Reproduce**

1.  git clone https://github.com/PrestaShop/PrestaShop.git
2.  cd PrestaShop
3.  docker-compose up

docker -v
Docker version 18.06.1-ce, build e68fc7a

docker-compose -v
docker-compose version 1.23.2, build 1110ad01

**Comment by khouloudbelguith** [comment]
Hi @paparga,

Thanks for your report.
It is a permission issue.
Could you please try to change file permissions of all directories to 777, check & feedback.
Thanks!

**Comment by PierreRambaud** [comment]
The best way to have write and read access is to use the same user the container image.

```
$ chown -hR www-data:www-data ./PrestaShop
```
And everything will work fine.

**Comment by paparga** [comment]
Thank you @PierreRambaud, everything works fine

This should be documented in README.md

**Comment by PierreRambaud** [comment]
@paparga I do it in this PR (https://github.com/PrestaShop/PrestaShop/pull/12222) Thanks for the advice.

**Comment by smartsoftbox** [comment]
I still have same problem.

**Reproduce**
1. chown -hR www-data:www-data ./prestashop
2. git clone https://github.com/PrestaShop/PrestaShop.git
3. cd prestashop
4. docker-compose up

docker
Docker version 19.03.2, build 6a30dfc

docker-compose
docker-compose version 1.24.1, build 4667896b

**error message**

\n* Reapplying PrestaShop files for enabled volumes ...
cp: cannot stat '/tmp/data-ps/prestashop/*': No such file or directory

**Comment by davidglezz** [comment]
@smartsoftbox chown after clone

1. git clone https://github.com/PrestaShop/PrestaShop.git
2. cd prestashop
3. chown -hR www-data:www-data .
4. docker-compose up
