### ISSUE TITLE
Last login is not traced

### ISSUE THREAD

**Issue by coreykck** [PrestaShop/PrestaShop#12228]
**Describe the bug**
I've installed Prestashop 1.7.4.4 and ported old modules to the fresh new installation.
When customer login to the shop no login time is recorded into DB so, last visit is not shown in Admin Customer table.

**Screenshots**
![nolastvisit](https://user-images.githubusercontent.com/6223578/51438743-5822ac80-1cb0-11e9-886f-e71aed416629.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment]
Hi @coreykck,

I did not manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/51462690-8ca27100-1d61-11e9-96e6-920f08c21937.png)
Your issue could be related to a custom module or an override.
Thanks to check & feedback.

**Comment by coreykck** [comment]
Got it, my fault.
The hook displayBeforeBodyClosingTag was not enabled in Display Positions
Tnx a lot

**Comment by khouloudbelguith** [comment]
@coreykck, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
