### ISSUE TITLE
Multi Shop upgrade to 1.7.4.2 =>1.7.5.0 full of errors 

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#12229]
I have a multi store / multi domain shop

First I upgraded 1 click upgrade to 4.5.1 on both sides.

Then I did an upgrade on store 2 first (in production mode), went fine, no errors.
Then I tried to do an upgrade on store 1 (also in production mode), it went fine up to the database update, I got a response: database already up to date, do you want to downgrade to 1.7.4.2 (??? why would I want that). 
Then after clicking no I got a 500 error. Only by switching to development mode was I able to actually login to the back office. Investigation showed that the \var\cache\prod was not present giving a 500 error. 
Now the installation is corrupted. Both log files are littered with critical errors.
[prod_shop1.log](https://github.com/PrestaShop/PrestaShop/files/2776579/prod_shop1.log)
[prod_shop2.log](https://github.com/PrestaShop/PrestaShop/files/2776580/prod_shop2.log)
so I can basically only run the shops in development mode.
It is mostlikely to do with the var/cache folders not being created correctly (or at all) and not with the right permissions/ownership

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

The autoupgrade is done in all stores.
With this module, you can upgrade your shop to the latest version of PrestaShop but not your stores separately.
![image](https://user-images.githubusercontent.com/16067358/51466984-b82a5900-1d6b-11e9-82c2-921f785ebb5a.png)
You can run those command lines to remove the cache:
 `rm -fR /Projet_PrestaShop/var/cache/*`
```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Thanks to check & feedback.

**Comment by sickboards** [comment]
Even if the stores are in 2 separate folders/drives on the server?

**Comment by khouloudbelguith** [comment]
@sickboards, so you have a different `Physical URL` for each store?
![image](https://user-images.githubusercontent.com/16067358/51471764-e44bd700-1d77-11e9-81a9-8e5ab90a5172.png)
Thanks!

**Comment by sickboards** [comment]
Yes exactly
thanks

**Comment by khouloudbelguith** [comment]
@sickboards, these two stores, they have different databases? 
Thanks!

**Comment by sickboards** [comment]
no same database

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

Have you the same issue with this after upgrading the second store?
![image](https://user-images.githubusercontent.com/16067358/51482152-f50b4580-1d95-11e9-9366-bceb428384bf.png)
Thanks!

**Comment by sickboards** [comment]
yes that was what I had to and then I said no i don't want to restore and
then i got a 500 error because the /var/cache/prod folder did not exist.

**Comment by khouloudbelguith** [comment]
@sickboards, thanks for your feedback.
Yes, I manage to reproduce the issue with the 1-click upgrade v4.5.1.
Steps to reproduce the issue:
1- fresh install PS1.7.4.4 => Folder name **1744**
2- fresh install PS1.7.4.4 => folder name **ps1744**
3- replace the database of **ps1744** by the database **1744**, in the file **ps1744**/app/config/parameters.php
4- Clear cache manually from **ps1744**
5- Enable a multistore context for the shop **1744**
6- Create a new shop with the `URL physique` **ps1744** which is the second fresh install
7- Now, we have two shops with the same database but they have not the same folder
8- Do the upgrade for the first shop(**1744**) => OK
9- Do the upgrade for the first shop(**ps1744**) => during the upgrade we have 
```
Error during database upgrade. You may need to restore your database.
You already have version 1.7.5.0.
```
10- Then after switching to another page, I got a 500 error.
11- When I tried to clear cache manually by deleting all the folder into **ps1744**/var/cache (prod & dev)=> shop 2(**ps1744**)  is OK => the upgrade is done successfully.
Ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by Quetzacoalt91** [comment]
As far as I understand, both shops are running on the same database and in your example `ps1744` is not used anymore.
Database is already running the version you try to upgrade on, the script is supposed to return an error code as written [in the doc](https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#error-codes).

What do you expect from me here? This seems to be a expected consequence of the process done.

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

Could you please confirm us the steps to reproduce the issue?
Is it the [right way](https://github.com/PrestaShop/PrestaShop/issues/12229#issuecomment-456111377) to reproduce the issue?
If yes, as discussed with @Quetzacoalt91, it is normal behavior, because, in the second shop, the upgrade is stopped in the middle, so the cache is not cleared automatically because this action (clearing the cache) is done in the last step of the upgrade.
Thanks!

**Comment by sickboards** [comment]
Hi, yes that is correct, would it not be better if the cache was deleted automatically to avoid the 500 error?

On this topic is there a better way of running a multi-store environment with 2 distinct domain names?

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

Thanks for your feedback.
As I said before, it is normal behavior to have 500 error because the cache is not cleared so, in the second shop, the upgrade is stopped in the middle, that's why the cache is not cleared automatically because this action (clearing the cache) is done in the last step of the upgrade.
For more details about `Managing Multiple Shops`, you can follow this [link](http://doc.prestashop.com/display/PS17/Managing+Multiple+Shops).
Thanks!
