### ISSUE TITLE
In page Traffic & SEO

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#12239]
Hi the team,
Tests on version 1.7.5.1,
in page Traffic & SEO

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

![seo-error](https://user-images.githubusercontent.com/44966543/51473814-ace02900-1d7d-11e9-93bb-81e86329411c.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by tomas862** [comment]
On **1.7.5.1** it works , this happens only on develop branch

**Comment by khouloudbelguith** [comment]
Hi @Peterits,

I did not manage to reproduce the issue with the branch 1.7.5.x ( PS1.7.5.1).
But, I have the same issue with develop branch.
We will see how to fix it.
Thanks!

**Comment by Peterits** [comment]
Hi @ khouloudbelguith , 
The error is on 1.7.5.x too, I will check on another installation !! 
Thanks!

**Comment by Peterits** [comment]
Hi the team,
Tests on version 1.7.5.x,
Always the same error with updates for 1.7.5.1
The tomas862 corectif did not solve the problem.
The problem is in version 1.7.5.1
cordially

![page-traffic- -seo](https://user-images.githubusercontent.com/44966543/51741370-ff2f8b80-2096-11e9-9789-9f1f3824dac0.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Peterits,

Sorry, I just tried a fresh install from the branch 1.7.5.x (which is 1.7.5.1 version) & it is OK.
https://drive.google.com/file/d/1PXAb1tzH51ImeaQMiPBAqD5EmKD1zbhR/view
Thanks!

**Comment by Peterits** [comment]
Hi @ khouloudbelguith ,
There must be an error in my file, I'm sorry!
I will check or wait for the final version 1.7.5.1
I must be a donkey, lol! hi hi
cordially

**Comment by Peterits** [comment]
Hi,
I uninstalled the "Keep showcase cards closed # 12111" corectif and everything is back in order, now the 1.7.5.x SEO page is working again!
cordially
