### ISSUE TITLE
bug on SEO product, if the field meta description is empty

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#12233]
Hi the team,
I have done some tests on version 1.7.5.1, there is a small bug on SEO product, if the field meta description is empty, the preview SEO shows code!

**Screenshots**
![image-seo](https://user-images.githubusercontent.com/44966543/51459052-87d8bf80-1d57-11e9-9efe-d637385a0005.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Peterits,

Thanks for your report.
I manage to reproduce the issue with the branch 1.7.5.x ( PrestaShop v 1.7.5.1)
![image](https://user-images.githubusercontent.com/16067358/51461707-14d34700-1d5f-11e9-8788-ab7909f4026f.png)
In the last version 1.7.5.0, it is OK.
We will see how to fix it.
Thanks!

**Comment by Peterits** [comment]
Hi,
The modification seems to work properly !!
Thanks !
