### ISSUE TITLE
Product with combination

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#12241]
Let me explain the concern:
If I have One product A and Which I want to show with image 1.jpg (this one is set as cover image for refence of product)
Product A has 2 combination a and b with image 2.jpg and 3.jpg respectively.
Now when I see the product on the front-office. It should be shown with 1.jpg image (Cover Image) but in prestashop first combination (combination a with image 2.jpg) get selected automatically and shows in product list instead of cover image of product.

I think there should be display Product A with cover image which is only for reference image of product (This should not be allow for order) and once customer select any of attribute then related combination image should be shown and only combination can be allow for order.

## SPECS
Diplay the cover image in the product listing (category)
Display the images selected for the combination in the product page

**Comment by khouloudbelguith** [comment]
Hi @Akashvastarpara,

Thanks for your report.
@marionf, @colinegin what do you think of his suggestion?
Thanks!

**Comment by Akashvastarpara** [comment]
@khouloudbelguith  Any update?

**Comment by khouloudbelguith** [comment]
@Akashvastarpara, sorry not yet.
Thanks for your understanding & for your patience!

**Comment by MatShir** [comment]
Hi @Akashvastarpara, 

If I understand, you rather want to display a generic image of your product instead of the one selected by default in product combination. I would make sense to have as well a cover image, currently, the cover image is disabled in product combination.
Your feedback is taken into account with the team, a rework on the product page is planned in one of the next released.

Thank you

**Comment by dineshbadrukhiya** [comment]
@MatShir 
I think expected behavior should be like : If product have combination then there should be option to allow or set generic image or main image for that product on list page and product page as well and once customer click on shopping cart button then customer must have to select the attribute (there should not be default selection) and then after only call for add to cart button should be triggered.

Right now, Image of default combination is showing but the cover image is not showing even we have set, if we add generic image(main image) with thumbnail and customer clicks on add to cart then main image showing in the shopping cart modal and checkout page (while expected behavior should be: image should be of that combination not the (main image), to avoid it we need to remove default selection of attribute on product page so once customer selects any attribute then image with that combination shows on modal and checkout and next pages for order.)

**Comment by MatShir** [comment]
Thanks for your detail explanation @dineshbadrukhiya

**Comment by marionf** [comment]
@tlhuillier suggest also to add the possibility to reorder images

**Comment by Frankyet** [comment]
In Prestashop 1.6, this is working correct, when set cover-image in combinations it will shown on product list and not the image of the default combination.
hoop you can fix this soon in Prestashop 1.7.5.2
Thanks

**Comment by khouloudbelguith** [comment]
Hi @Frankyet,

This issue is added to our bug roadmap.
PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by txominvila** [comment]
I had the same problem and I "fixed" this way:

1 product | 2 combinations | 3 images (main image, combination 1 image, combination 2 image)

Set main image as cover image
For first combination, set main and combination 1 image
For second combination, set main and combination 2 image

Result:
Product list displays main image.
Product sheet displays slide with both main and combination image
Shopping cart displays main image. If this is not acceptable, it's not difficult overriding the theme to show combination image.

**Comment by dfliess** [comment]
+1

**Comment by ProBackup-nl** [comment]
Remove to default combination, let customers make an explicit choice which product combination they want. 

Without a default combination selected, then display the product cover image.
With a default combination selected, then display the cover image of the combination.

Not having a default combination selected has been requested before, even 8 years ago: <https://www.prestashop.com/forums/topic/145292-mandatory-to-select-a-combination-with-no-combination-as-default/>

**Comment by CaseOnline** [comment]
Any developer with skills to fix this?
Really important standard feature.

Why upload 20 pictures of a product when customers never can see anything else than attributes, really fucked up.

Another important features wich finally added in 1.7.5 is locations field. Unbelivable merchants can work smooth without it, should be standard for a long time ago. But why hide this important field? Should be visable on create product first page right under ref nr, also in product listing page should be super. Sure i know you can use advanced stock to show this field in recent versions, but much more complicated way to work.

**Comment by dfliess** [comment]
+1

**Comment by marionf** [comment]
Hello everyone, 

What do you think about restoring the behavior of PS 1.6 which is:
Diplay the cover image in the product listing (category)
Display the images selected for the combination in the product page

**Comment by CaseOnline** [comment]
Sounds like an excellent idea! Hope some developer with skills could fix this asap.
If anyone know how to do this properly please contact us we pay for this core fix.
Tony (info@caseonline.se). 

Also want some other fixes wich is worse thn ps 1.6.

**Comment by dineshbadrukhiya** [comment]
> Hello everyone,
> 
> What do you think about restoring the behavior of PS 1.6 which is:
> Diplay the cover image in the product listing (category)
> Display the images selected for the combination in the product page

Yes, that's the best solution for all merchants as per my opinion.

**Comment by CaseOnline** [comment]
YES and best to RESTORE complet 1.7.6 to I.6 behavior. This is the worst prestashop i ever seen.
As a merchant this BO i a joke. Many importand field is now hidden very well for example:

Attribute numbers > Need to click on each attribute to see this number (visable in 1.6) 
Location Filed > Need to goto stock to see and attributes then goto each attribute to see this. (should be placed in firstpage under refnr.
Delete Pictures > Need to open each picture (1.6 just click on x in corner of picture)
Short description > Well this field is open (wow)
Long discription > Need to click (ps 1.6 has it open under)

And whole interface is made for people with sight problem? Everything so big i guess thats why they need to hide all important fields and features in many diffrent windows.

This going to be expensive to get custom made so it possible to work in BO.

Lucky i got storemanager to rescue us...

**Comment by marionf** [comment]
Hello @CaseOnline 

> Attribute numbers > Need to click on each attribute to see this number (visable in 1.6)

What do you call "attribute numbers" ?

> Delete Pictures > Need to open each picture (1.6 just click on x in corner of picture)

Are you talking about images in basic settings or images for a combination ?
In 1.6 there was a delete button for each picture

![capture d'écran_1872](https://user-images.githubusercontent.com/13449658/62771394-647c2480-ba9d-11e9-90af-1302703242c0.png)

I don't see the x in corner of picture in 1.6 you are talking about, could you please provide a screenshot ? 

> Short description > Well this field is open (wow)
Long discription > Need to click (ps 1.6 has it open under)

About Short & Long description tabs, we plan to remove them as you can see here: https://github.com/PrestaShop/PrestaShop/issues/14985

**Comment by CaseOnline** [comment]
Hi @marionf,

About attribute nr
Ref nr 12345-1 (black) 12345-2 (blue) 12345-3 (red) etc... to see thoose attribute nr 1,2,3 in 1.7.6 they not listed in combination view. In 1.6 they are all listed perfect.

Delete pictures : If you duplicate a product and it has lets say 7 pictures. You need to remove 1 by 1 and confirm popup window. In ps 1.6 as you picture above you just press delete and press enter. Ps 1.7 don't like enter keyboard need to use mouse maybe a bug in my version i don't know.

Also an important field for merchants with many products use stock location field. This is finally added but should be easy accessed. Dreamwould be in BO product listing page also show in first page when you create a new product for example under refnumber field. And when go to combination listview add column "location" and column "Ref nr"

**Comment by marionf** [comment]
@CaseOnline 

Thank you for your feedbacks

About the duplication of a product & images there is already an issue here: https://github.com/PrestaShop/PrestaShop/issues/13397
We also plan to add the possibility to add many images in once and delete images in bulk, as you can see here: https://github.com/PrestaShop/PrestaShop/issues/12773

About adding the reference and the location in combinations listing table, we need to think about it as there is not too much space in width

**Comment by CaseOnline** [comment]
Ok sounds greate! @marionf and  @khouloudbelguith are you freelancers? Our company need a lot of prestashop work done often. So if you are interested please contact me at tony@caseonline.se we cant wait for prestashop updates need to get things working and also much custom work that is important for a merchant. Thanks Tony

**Comment by marionf** [comment]
@CaseOnline 

No, we are working for PrestaShop company ;)

**Comment by fredo85** [comment]
@CaseOnline, if it helps, this solution works for us (it would be better with a hook or with a widget)

you can do this in your template for listing

        {assign var='coverImage' value=Image::getCover($product.id_product)}
        {assign var='coverImageSrc' value=''}
        {if !empty($coverImage) && !empty($coverImage.id_image) &&  $coverImage.id_image > 0 }
            {assign var='coverImageSrc' value=$link->getImageLink($product.link_rewrite, $coverImage.id_image, 'large')}
        {/if} {if $coverImageSrc != ''}{$coverImageSrc}{else}{$product.cover.bySize.large.url}{/if}

**Comment by khouloudbelguith** [comment]
Hi @fredo85,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by fredo85** [comment]
sorry, no time for this, we works on https://github.com/PrestaShop/PrestaShop/issues/11059 ;-)

**Comment by CaseOnline** [comment]
Sorry thats not correct code to make ps 1.7.6 be like 1.6 and show all pictures.

**Comment by fredo85** [comment]
it works, you can copy code to template themes/classic/templates/catalog/_partials/miniatures/product.tpl and to {block name='product_thumbnail'}

**Comment by dineshbadrukhiya** [comment]
> it works, you can copy code to template themes/classic/templates/catalog/_partials/miniatures/product.tpl and to {block name='product_thumbnail'}

Are you sure your code suggestion can show all the product thumbnails on product page as well same as in PrestaShop 1.6?

![product-thumbnail](https://user-images.githubusercontent.com/40850057/64502772-9aebd000-d2e5-11e9-8ed0-0673d749d36a.png)

**Comment by CaseOnline** [comment]
Fredo85> Are you sure this code fix the issues? Will it show like picture above that dineshbadrukhiya posted??

**Comment by dineshbadrukhiya** [comment]
In order to get cover image of product on product listing we can modify code as below in file themes/classic/templates/catalog/_partials/miniatures/product.tpl

Current code:

```
        {if $product.cover}
          <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
            <img
              src="{$product.cover.bySize.home_default.url}"
              alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name|truncate:30:'...'}{/if}"
              data-full-size-image-url="{$product.cover.large.url}"
            />
          </a>
        {else}
          <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
            <img src="{$urls.no_picture_image.bySize.home_default.url}" />
          </a>
        {/if}
```

Modified code:
```
                {if $product.cover}
                    {assign var='coverImage' value=Product::getCover($product->id)}
                    {assign var='coverImageId' value="{$product->id}-{$coverImage.id_image}"}
                    <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
                        <img
                            src="{$link->getImageLink($product.link_rewrite, $coverImageId)}"
                            alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name|truncate:30:'...'}{/if}"
                            data-full-size-image-url="{$product.cover.large.url}"
                            />
                    </a>
                {else}
                    <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
                        <img src="{$urls.no_picture_image.bySize.home_default.url}" />
                    </a>
                {/if}
```

**Note:** This solution can not show all thumbnails image of product on product page like PrestaShop 1.6

**Comment by CaseOnline** [comment]
Hi Dinesh,

I think that what Piyush implemented?? He got cover picture to show on products in Front but when view product all tiny pictures not showing when have combinations.
Only show assigned color when click on diffrent combination colors.

You think your code will also show tumbnails (tiny pictures) under product picture? As in ps 1.6?

Thanks
Tony

 



Tony Hörnberg
CaseOnline Sweden AB


phone: + 46 (0) 920 47 79 90
mobile: + 46 (0) 790 77 57 67


 <https://www.facebook.com/caseonline.se>  <https://twitter.com/caseonline1>  <https://www.youtube.com/.../UCkVHvmW_2jIf7lPTM4SMOJQ>  <https://www.linkedin.com/company/www-caseonline-se>  <https://plus.google.com/113492579733881346995> 


 <https://www.caseonline.se/> 


Blomgatan 17 B
973 31 Luleå | Sweden


 <http://www.caseonline.se/> www.caseonline.se

 

 

Från: Dinesh Badrukhiya <notifications@github.com> 
Skickat: den 19 september 2019 14:42
Till: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Kopia: CaseOnline <info@caseonline.se>; Mention <mention@noreply.github.com>
Ämne: Re: [PrestaShop/PrestaShop] Product with combination (#12241)

 

In order to get cover image of product on product listing we can modify code as below in file themes/classic/templates/catalog/_partials/miniatures/product.tpl

Current code:

        {if $product.cover}
          <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
            <img
              src="{$product.cover.bySize.home_default.url}"
              alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name|truncate:30:'...'}{/if}"
              data-full-size-image-url="{$product.cover.large.url}"
            />
          </a>
        {else}
          <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
            <img src="{$urls.no_picture_image.bySize.home_default.url}" />
          </a>
        {/if}

Modified code:

                {if $product.cover}
                    {assign var='defaultImage' value=Product::getCover($product->id)}
                    {assign var='defaultImageId' value="{$product->id}-{$defaultImage.id_image}"}
                    <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
                        <img
                            src="{$link->getImageLink($product.link_rewrite, $defaultImageId)}"
                            alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name|truncate:30:'...'}{/if}"
                            data-full-size-image-url="{$product.cover.large.url}"
                            />
                    </a>
                {else}
                    <a href="{$product.canonical_url}" class="thumbnail product-thumbnail">
                        <img src="{$urls.no_picture_image.bySize.home_default.url}" />
                    </a>
                {/if}

**Comment by colinegin** [comment]
Congrats 👍

**Comment by dineshbadrukhiya** [comment]
As the demand is same feature like 1.6 version, Still we needs more improvement for product page.
