### ISSUE TITLE
Multistore mode issues

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#12255]
I have created 5 different shops . Now if i trying to disable all website by selecting the "All shops " the website still enable.

For disabling all shops i need to select each shops and disable the shop(put the website in maintance mode).

Please let me know what exactly issue is this

**Comment by khouloudbelguith** [comment]
Hi @pks891618,

We manage to reproduce the issue.
Your ticket is a duplicate of #9548
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9548

**Comment by pks891618** [comment]
Sorry but i cant the fixes for this issue on the url https://github.com/PrestaShop/PrestaShop/issues/9548

**Comment by khouloudbelguith** [comment]
@pks891618, sorry it is not fixed yet.
Thanks!

**Comment by pks891618** [comment]
@khouloudbelguith  so this issue is not fixed in 1.7.4.2 , we can use the latest version for prestashop 1.7.5

**Comment by khouloudbelguith** [comment]
@pks891618, sorry it is not fixed from 1.7.4.0 to PS1.7.5.0
