### ISSUE TITLE
Search for hook leads to invalid token warning

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#12259]
Search for hook leads to an invalid token warning:
Invalid token: direct access to this link may lead to a potential security breach.

how to reproduce:
- go to design -> positions
- type in 'home' in search for a hook field and press enter.

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
With PS1.7.5.0, In the Positions page, the "enter" action with the keyboard is **allowed**.
https://drive.google.com/file/d/14b6NE7BQHgyU0cEp3PknZMdCBLT2-uiA/view
In the PS1.7.4.4,  In the Positions page, the "enter" action with the keyboard is **not allowed**.
https://drive.google.com/file/d/11wKr2uhzBGcQEl0FiPt07JIMbEp8XlaN/view
We will see how to fix it.
Thanks!
