### ISSUE TITLE
Japan States in double with different iso

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#12252]
### Describe the bug

I just notice that the State of Japan are in double in the BO (Locations/States) but with a different iso code.

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/94ba8c88-9187-4fea-9aa3-db79d6d52c10)

### Expected behavior
....

### Steps to reproduce

1. BO>IMPROVE>International>Locations
2. Go to States
3. Filter by country "Japan"
4. See the error>there's some states are in double but with a different iso code.

### Addtional infos

- PS 1.7.5.0
- PHP: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/51520789-f0da3900-1e24-11e9-9d93-d0ff25178719.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @BenTen & @khouloudbelguith 

It seems the issue has been fixed with PS1.7.7.1 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/107707046-92a97880-6cc1-11eb-9faa-dddf575f7bb9.png)

Please check and feedback.
Thanks!

**Comment by BenTen** [comment]
> Hello @BenTen & @khouloudbelguith
> 
> It seems the issue has been fixed with PS1.7.7.1 and develop, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/107707046-92a97880-6cc1-11eb-9faa-dddf575f7bb9.png)
> 
> Please check and feedback. Thanks!

A bit late but, fresh install of 8.1 is clean.
If we update language by downloading from International > Localization, states with wrong ISO are installed.

**Comment by florine2623** [comment]
This is fixed on PS 8.0.x, 8.1.x, develop.

There are 47 states now, before there were 94.
<img width="1435" alt="Screenshot 2024-01-24 at 16 13 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ed11aab0-9ff8-4492-b823-4b3e506e072a">

I'm closing the issue as it is fixed.
