### ISSUE TITLE
Webservice Product Image Size Limit 

### ISSUE THREAD

**Issue by sanctusmob** [PrestaShop/PrestaShop#12254]
When i try to upload product over 3Mb i got this reply from webservice.

`<code><![CDATA[72]]></code>
<message><![CDATA[The image size is too large (maximum allowed is 3000 KB)]]></message>`

Php settings are 32Mb. Also in Image Settings --> Maximum file size of product customization pictures --> is 8Mb (8388608 bytes).

Where can i change this limit?

Prestashop 1.7.5
Php fpm 7.2

**Comment by khouloudbelguith** [comment]
Hi @sanctusmob,

Can you please edit the file `WebserviceSpecificManagementImages` into the path ProjectPrestaShop/classes/webservice/WebserviceSpecificManagementImages.php, replace this code line `protected $imgMaxUploadSize = 3000000;` 
by this 
`protected $imgMaxUploadSize = 10000000;`
Thanks to check & feedback.

**Comment by sanctusmob** [comment]
Issue solved. In the next update this value will be lost. 
This value must be read from the configuration in DB (or somewhere else)

Thank very much khouloudbelguith.

**Comment by NikosTsiligaridis** [comment]
It's been years since I first stumbled on this problem and it is still present in the latest version.

**Comment by rodriciru** [comment]
This should be fixed
