### ISSUE TITLE
Import che related products

### ISSUE THREAD

**Issue by diegomariani** [PrestaShop/PrestaShop#12278]
I can not import product related...

![prestashop import combination ask](https://user-images.githubusercontent.com/32632725/51627944-fbd7bb00-1f43-11e9-9799-1d128b50e87d.png)

**Comment by khouloudbelguith** [comment]
Hi @diegomariani,

You can import related product by filling the field `Accessories (x,y,z...)`
![image](https://user-images.githubusercontent.com/16067358/51663201-6a556100-1fb6-11e9-8656-4c920b836931.png)
I tried with this file, 
[product.csv.zip](https://github.com/PrestaShop/PrestaShop/files/2790684/product.csv.zip)
& it is OK.
![image](https://user-images.githubusercontent.com/16067358/51663296-9f61b380-1fb6-11e9-978d-8967cf4059ab.png)
Thanks to check & feedback.

**Comment by diegomariani** [comment]
woowww, tank's!!!

Il giorno gio 24 gen 2019 alle ore 09:01 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment]
@diegomariani, so can I close the issue?
Thanks!

**Comment by khouloudbelguith** [comment]
@diegomariani, feel free to open a new one when needed.
Thanks!
