### ISSUE TITLE
specific price reduction not display in BO

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#12275]
Hello,

When I add a specific price reduction, the value is display in FO but not in BO.

1. Create a product
2. Set price (5000)
3. Add specific price reduction (1000)
4. Click "Apply"

We can't see the specific price.
If we try to put an other reduction, an error is display on the tob right of the screen "A specific price already exists for these parameters."

Before apply: https://tof.cx/image/sOxHN
After apply: https://tof.cx/image/sO1uX

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

I did not manage to reproduce the issue with fresh install 1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1wo_noEWlzryUZDTO8NbLcprAZcpwOVBC/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by BenTen** [comment]
I fount the problem. It seems to be a bug with a [3rd part module](https://addons.prestashop.com/en/price-management/27821-change-or-remove-the-decimals-and-format-currency.html) on PS 1.7.5.0

I will contact the dev.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
