### ISSUE TITLE
 Uploaded images don't show if turn on friendly URL

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#12271]
Hello,

Original link at PrestaShop official forum, [https://www.prestashop.com/forums/topic/952933-uploaded-images-dont-show-if-turn-on-friendly-url/](url)

The images are well displayed without friendly URL enabled.

After I enabled friendly URL, they don't display at all.

Witho﻿ut friendly URL enabled, the URL to the uploaded images﻿ is:﻿
`https://x.x.x/x/x/img/p/4/5/45-large_default.jpg`

After I enabled the friendly URL. It turned to below, which is not accessible by web browser.
`https://x.x.x/x/x/45-large_default/pharmacotherapy-a-pathophysiologic-approach-tenth-edition.jpg﻿`

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

I did not manage to reproduce the issue with PS1.7.5.0 fresh install.
I attached a video record.
https://drive.google.com/file/d/18ySGXfl6I1vGhVwnwfshrJCVzBi2q-q1/view
Could you please follow these steps after enabling Friendly URL, check and feedback.

1. Go to BO => Design => Images Settings page
2. Scroll down to Regenerate thumbnails

Thanks!

**Comment by TomHsiung** [comment]
I had tried thumbnail regeneration for several time but no luck. I use https with a port of 50443.

You can browse my PrestaShop site at: https://www.toms-therapeutics.site:50443/prestashop/

Tom

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

I tried in my case with https:// but it is OK.
I attached a video record.
https://drive.google.com/file/d/128-GUr0vzUcxlJMeyEMORuUPJqvS-ZAH/view
Your shop is not accessible, 
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by TomHsiung** [comment]
Please accept the public key to access my site. I cannot access Google because of great firewall of China.

**Comment by TomHsiung** [comment]
I enabled debug mode just a moment ago and I checked my php error log. Here is a log record.

`[Wed Jan 23 13:02:02.569035 2019] [php7:warn] [pid 16602] [client x.x.x.x:62298] PHP Warning:  U$

[Wed Jan 23 13:02:02.569035 2019] [php7:warn] [pid 16602] [client 10.0.0.254:62298] PHP Warning:  Use of undefined constant ADMIN_LEGACY_CONTEXT - assumed 'ADMIN_LEGACY_CONTEXT' (this will throw an Error in a future version of PHP) in xxx/prestashop/modules/ps_mbo/ps_mbo.php on line 320, referer: https://www.toms-therapeutics.site:50443/prestashop/admin/index.php?controller=AdminImages&conf=x&token=xxxxxxxxxx`

**Comment by TomHsiung** [comment]
The database table of log did not record any related error information.

**Comment by khouloudbelguith** [comment]
@TomHsiung, to be sure that ps_mbo is not the problem, could you please try to disable the `PrestaShop Marketplace in your Back Office` module, clear cache & feedback.

**Comment by TomHsiung** [comment]
I found the issue:

- I use 50443 as my ssl web service port

- I keep the default 80 port as my http web service port.

This issue happened because of:

After fresh installation, the domain is xxx.xxx.xxx:50443/prestashop, and the domain_ssl is also xxx.xxx.xxx:50443/prestashop, right? Because by default Prestashop does not enable SSL, so after this fresh installation, I have trouble to access the webpage of PrestaShop.

The error is:
```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

Apache/2.4.29 (Ubuntu) Server at x.x.x Port 443
```
PS: the browser tried to access Prestashop pages with http protocol at port 50443, with resulted the bad requisition problem.

Although I enabled SSL for the apache2 service, the PrestaShop script after fresh installation forced to use http, which resulted above error with port 50443.

To access the admin panel of Prestashop, I had to modify the domain from xxx.xxx.xxx:50443 to xxx.xxx.xxx, so that I was able to access the admin panel by http (80 port). I made it by change the domain in the MySQL database.

And this is the reason for the image issue after enabling friendly URL - the domain was set to xxx.xxx.xxx before and was not changed back to its (after fresh installation) original value of xxx.xxx.xxx:50443.

So, 10 minutes ago, I changed the domain to xxx.xxx.xxx:50443, and the issue resolved.

Tom

**Comment by khouloudbelguith** [comment]
@TomHsiung, thanks for your feedback.
I'm glad that your issue is solved.
I will close the issue, feel free to open a new one when needed.

Just an issue related to PrestaShop installation with https:// https://github.com/PrestaShop/PrestaShop/issues/10482, it is added to our bug roadmap.
Thanks!

**Comment by TomHsiung** [comment]
The root reason for this issue is that your script does not support SSL by default.

Tom

**Comment by TomHsiung** [comment]
Also, there is a config file xxx/prestashop/config/config.inc.php, where a line:
`/* SSL configuration */
define('_PS_SSL_PORT_', 443);`
Should keep it as 443, or should I changed it to be consistent with my SSL port (50443)?

**Comment by khouloudbelguith** [comment]
@TomHsiung,  you should change it to be consistent with your SSL port.
Thanks!
