### ISSUE TITLE
Strange Payment (Paypal) behaviour on modified order

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#12282]
Hello there, I'm experiencing a bug with PS 1.7.4.2/1.7.5 (PHP 7.1) with Paypal Payment module.

Here the details: a client asked for a change in his order (in the image, 63,75), adding a couple other products. 
We modified manually the order (adding a payment for 19,22).
The total is correct, the client paid the total 82,97.

Here the strange thing: on its own, a day after (you can see it from the image) paypal added 15 euros without ID transaction.
Weeks later, once the problem was noticed (via the client, who had the wrong invoince), we tried to fix removing the 15 euros.
90 minutes later the 15 euro were restored by the module, again with no transaction id and no idea how to solve it.

![clipboard01](https://user-images.githubusercontent.com/731916/51670003-f91daa00-1fc5-11e9-898d-d1e54652e4f8.jpg)

Any idea, suggestion?

Thanks in advance for any help.

**Comment by khouloudbelguith** [comment]
Hi @masiorama,

PayPal module is provided by our partners.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it: https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks!
