### ISSUE TITLE
Remove timeout from product image upload

### ISSUE THREAD

**Issue by JohnMidity** [PrestaShop/PrestaShop#12285]
**Is your feature request related to a problem? Please describe.**
When uploading product images using the dropzone.js, the upload stops after 30 seconds

**Describe the solution you'd like**
The timeout of 30s was introduced by dropzone.js as a default and can be easily removed by adding a `timeout:0` in `\admin-dev\themes\default\js\bundle\product\form.js` . 

**Describe alternatives you've considered**
All php.ini and apache settings ;)

**Additional context**
patch:
```
diff --git a/admin-dev/themes/default/js/bundle/product/form.js b/admin-dev/themes/default/js/bundle/product/form.js
index b9e080d..53d489a 100644
--- a/admin-dev/themes/default/js/bundle/product/form.js
+++ b/admin-dev/themes/default/js/bundle/product/form.js
@@ -1300,6 +1300,7 @@
         thumbnailWidth: 250,
         thumbnailHeight: null,
         acceptedFiles: 'image/*',
+        timeout: 0,
         dictRemoveFile: translate_javascripts['Delete'],
         dictFileTooBig: translate_javascripts['ToLargeFile'],
         dictCancelUpload: translate_javascripts['Delete'],
```

**Comment by khouloudbelguith** [comment]
Hi @JohnMidity,

Thanks for your report.
ping @eternoendless @PrestaShop/prestashop-core-developers what do you think?
THanks!

**Comment by PierreRambaud** [comment]
Yes it is a good idea to let php define what is the best timeout to have :)

**Comment by BenTen** [comment]
@JohnMidity This timeout 0 is really useful, I can upload image in product page without trouble now, thank you.
