### ISSUE TITLE
Configuration module Live Chat Pro

### ISSUE THREAD

**Issue by Littlemonkey56** [PrestaShop/PrestaShop#12283]
Hello, 

We would like a proactive chat. 
For instance, we would like that a pop-up window opens after a certain period of time asking customers if they have any questions or offering a special offer. 
Can we do that using "Triggers" (in the module) and how do we proceed ? 

Thank you in advance for your help. 

Best regards,

**Comment by khouloudbelguith** [comment]
Hi @Littlemonkey56,

Have you tried to contact the module author about your issue?
You should contact them via your addons.prestashop.com account: https://addons.prestashop.com/en/contact-us?id_product=17437
Thanks to check with them & feedback.

**Comment by Littlemonkey56** [comment]
Hello, 

Thank you for the answer. 
Yes, I did it and I had a reply. 
There was a typing error in fact. 

Thank you for your help anyway. 

Best regard,

**Comment by khouloudbelguith** [comment]
@Littlemonkey56, so can I close the issue?
Thanks!

**Comment by Littlemonkey56** [comment]
Hello, 

Yes, you can do it. 

Thank you. 

Best regards,

**Comment by khouloudbelguith** [comment]
@Littlemonkey56, feel free to open a new one when needed.
Thanks!
