### ISSUE TITLE
CANCEL button doesn't work in Safari

### ISSUE THREAD

**Issue by git0matt** [PrestaShop/PrestaShop#12299]
Hi

In the past I remember pressing the CANCEL button and it returns to the previous screen - as expected.

However it is no longer working.  Other javascript actions are working, like the AJAX loading spinner in the top-left corner, AJAX form save, and others.

Perhaps it because I'm using Safari, since Chrome and Firefox perform as expected.  Here is the code Prestashop uses:

>` <a href="#" class="..." id="..." onclick="window.history.back();">...</a>`

I have another web-application but it's using:

> `<input class="..." type="button" value="←&nbsp;Back" onclick="history.back(-1)">`

This works fine in all browsers (the ones listed above).

**I suggest the input-button-code replace the anchor-code.**

**Comment by khouloudbelguith** [comment]
Hi @git0matt,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 and Safari browser v10.1 also Safari v12.0.2.
Steps to reproduce the behavior:

Design page
1. Go to BO => Design => Pages
2. Click on "Add new page"
3. Click on "Cancel" button, it is not working
![image](https://user-images.githubusercontent.com/16067358/51733184-d8665a80-2080-11e9-9287-35c7192bc393.png)

Category page
1. Go to BO => Catalog => Categories
2. Click on "Add new category"
3. Click on "Cancel" button, it is not working


I tried with Chrome browser, it is working!

With PS1.7.4.4 & the browser Safari v10.1 => OK.
https://drive.google.com/file/d/1lRqdgENqcRXyrAPIJW7a_Iqxq_JOGTlr/view
We will see how to fix it.
Thanks!
