### ISSUE TITLE
Web Service POST dont works.

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12294]
I have a lot of shops in multiple versions. But in one of them (v 1.6.1.23) when I send product POST request PRESTASHOP response me "ok" and didnt create new product. ( PUT,DELETE,GET works fine).

It only happens to me in this store, could it be a module? (comes from an update of version 1.6.1.7)

**Comment by ghost** [comment]
I solve it. the requests were forced by https. apologize

**Comment by khouloudbelguith** [comment]
Hi @OscarBanos,

Thanks!
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
