### ISSUE TITLE
HTTPS error

### ISSUE THREAD

**Issue by Bakker66** [PrestaShop/PrestaShop#12290]
Hi all,
In the chrome console I get next message.
Apperently the pictures are loaded in http instead of https

**was loaded over HTTPS, but requested an insecure image** 
Can anyone tell me what to do about it ?

Thanks,
René

**Comment by khouloudbelguith** [comment]
Hi @Bakker66,

We have similar issues reported in this ticket: #9807 & this #12253.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Bakker66,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
