### ISSUE TITLE
Undefined index: iso_code

### ISSUE THREAD

**Issue by feyll** [PrestaShop/PrestaShop#12303]
Hello everyone, I set up the multilingual site and currently I have only two languages. It seems that this has created conflicts or problems in my product pages. It seems it is a problem of missing ﻿code of ISO code for the countries.
From the debugging I get this result, please anyone have any suggestions on how to solve this?
I think there is also a problem with the smarty recompilation of template files.

> (1/1) ContextErrorExceptionNotice: Undefined index: iso_code
> --
> in 1c00f78dace25d509ec3a1f54176b7ae2000accf_2.module.pslanguageselectorpslangu.php line 32
> at content_5c4828d15dac45_55505364(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
> at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
> at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 41
> at SmartyDevTemplateCore->fetch()in Module.php line 2282
> at ModuleCore->fetch('module:ps_languageselector/ps_languageselector.tpl')in ps_languageselector.php line 61
> at Ps_Languageselector->renderWidget('displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 929
> at HookCore::coreRenderWidget(object(Ps_Languageselector), 'displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 881
> at HookCore::exec('displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)), null)in smarty.config.inc.php line 165
> at smartyHook(array('h' => 'displayNav2'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
> at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayNav2'), object(SmartyDevTemplate)))in cabe4f6fa9a3f328edda810b0448ca742141494a_2.file.header.tpl.php line 81
> at Block_20708550685c4828d15b7a14_04171567->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
> at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_20708550685c4828d15b7a14_04171567), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
> at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_20708550685c4828d15b7a14_04171567))in smarty_internal_runtime_inheritance.php line 157
> at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_20708550685c4828d15b7a14_04171567', 'header_nav')in cabe4f6fa9a3f328edda810b0448ca742141494a_2.file.header.tpl.php line 31
> at content_5c4828d15bf7e9_94044981(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
> at Smarty_Internal_Template->_subTemplateRender('file:_partials/header.tpl', null, 'layouts/layout-right-column.tpl', 0, 3600, array(), 0, false)in a585becf68d625336862b6ceda78a0f180ea1ba9_2.file.layout-both-columns.tpl.php line 188
> at Block_7253954555c4828d15668e5_93572198->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
> at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_7253954555c4828d15668e5_93572198), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
> at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_7253954555c4828d15668e5_93572198))in smarty_internal_runtime_inheritance.php line 157
> at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_7253954555c4828d15668e5_93572198', 'header')in a585becf68d625336862b6ceda78a0f180ea1ba9_2.file.layout-both-columns.tpl.php line 62
> at content_5c4828d157afc0_56589757(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
> at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-right-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
> at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in ef0919b744b1678166864f75b73faaef5066fcee_2.file.layout-right-column.tpl.php line 38
> at content_5c4828d155c540_97324174(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
> at Smarty_Internal_Template->_subTemplateRender('layouts/layout-right-column.tpl', null, 'layouts/layout-right-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
> at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-right-column.tpl')in ad5a1533ae3b6c81eab6a8f9ec955c7d416dc1cd_2.file.product.tpl.php line 54
> at content_5c4828d154db94_57529699(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
> at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-right-column.tpl', null, 0)in smarty_internal_templatebase.php line 116
> at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-right-column.tpl', null, false, true, false)in SmartyDev.php line 41
> at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-right-column.tpl')in FrontController.php line 679
> at FrontControllerCore->smartyOutputContent('catalog/product.tpl')in FrontController.php line 663
> at FrontControllerCore->display()in Controller.php line 275
> at ControllerCore->run()in Dispatcher.php line 428
> at DispatcherCore->dispatch()in index.php line 28

This is the file that asks me to check line 32, but I do not understand what the problem is on this line. Any suggestions will be appreciated.

line 32: ```
.jpg" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['current_language']->value['iso_code'], ENT_QUOTES, 'UTF-8');?>
" width="16" height="11" />
```

**full code of 1c00f78dace25d509ec3a1f54176b7ae2000accf_2.module.pslanguageselectorpslangu.php**
`<?php
/* Smarty version 3.1.32, created on 2019-01-24 13:35:44
  from 'module:pslanguageselectorpslangu' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.32',
  'unifunc' => 'content_5c49b120a40592_28713111',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '1c00f78dace25d509ec3a1f54176b7ae2000accf' => 
    array (
      0 => 'module:pslanguageselectorpslangu',
      1 => 1547477215,
      2 => 'module',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_5c49b120a40592_28713111 (Smarty_Internal_Template $_smarty_tpl) {
?><!-- begin /usr/www/users/canaph/ingrosso-canapa-light/themes/classic/modules/ps_languageselector/ps_languageselector.tpl --><div id="_desktop_language_selector">
  <div class="language-selector-wrapper">
    <span id="language-selector-label" class="hidden-md-up"><?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['l'][0], array( array('s'=>'Language:','d'=>'Shop.Theme.Global'),$_smarty_tpl ) );?>
</span>
    <div class="language-selector dropdown js-dropdown">
      <button data-toggle="dropdown" class="hidden-sm-down btn-unstyle" aria-haspopup="true" aria-expanded="false" aria-label="<?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['l'][0], array( array('s'=>'Language dropdown','d'=>'Shop.Theme.Global'),$_smarty_tpl ) );?>
">
        <span class="expand-more"><img src="/img/l/<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['current_language']->value['id_lang'], ENT_QUOTES, 'UTF-8');?>
.jpg" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['current_language']->value['iso_code'], ENT_QUOTES, 'UTF-8');?>
" width="16" height="11" />
		<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['current_language']->value['name_simple'], ENT_QUOTES, 'UTF-8');?>
</span>
        <i class="material-icons expand-more">&#xE5C5;</i>
      </button>
      <ul class="dropdown-menu hidden-sm-down" aria-labelledby="language-selector-label">
        <?php
$_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, $_smarty_tpl->tpl_vars['languages']->value, 'language');
if ($_from !== null) {
foreach ($_from as $_smarty_tpl->tpl_vars['language']->value) {
?>
          <li <?php if ($_smarty_tpl->tpl_vars['language']->value['id_lang'] == $_smarty_tpl->tpl_vars['current_language']->value['id_lang']) {?> class="current" <?php }?>>
            <a href="<?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['url'][0], array( array('entity'=>'language','id'=>$_smarty_tpl->tpl_vars['language']->value['id_lang']),$_smarty_tpl ) );?>
" class="dropdown-item"><img src="/img/l/<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['language']->value['id_lang'], ENT_QUOTES, 'UTF-8');?>
.jpg" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['language']->value['iso_code'], ENT_QUOTES, 'UTF-8');?>
" width="16" height="11" />
			<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['language']->value['name_simple'], ENT_QUOTES, 'UTF-8');?>
</a>
          </li>
        <?php
}
}
$_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);?>
      </ul>
      <select class="link hidden-md-up" aria-labelledby="language-selector-label">
        <?php
$_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, $_smarty_tpl->tpl_vars['languages']->value, 'language');
if ($_from !== null) {
foreach ($_from as $_smarty_tpl->tpl_vars['language']->value) {
?>
          <option value="<?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['url'][0], array( array('entity'=>'language','id'=>$_smarty_tpl->tpl_vars['language']->value['id_lang']),$_smarty_tpl ) );?>
"<?php if ($_smarty_tpl->tpl_vars['language']->value['id_lang'] == $_smarty_tpl->tpl_vars['current_language']->value['id_lang']) {?> selected="selected"<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['language']->value['name_simple'], ENT_QUOTES, 'UTF-8');?>
</option>
        <?php
}
}
$_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);?>
      </select>
    </div>
  </div>
</div>
<!-- end /usr/www/users/canaph/ingrosso-canapa-light/themes/classic/modules/ps_languageselector/ps_languageselector.tpl --><?php }
}
`



**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @feyll,

How did you create the language? did you created from BO => Localization => Languages Tab?
If yes, what is the exact language created?
Thanks!

**Comment by feyll** [comment]
Hi @khouloudbelguith yes i create the language from BO
The language is English (ENGLISH) iso code en-us

**Comment by khouloudbelguith** [comment]
@feyll, could you please navigate to your BO => International => Translations => "Add / Update a language" part, Select the "English" language and click on the button "Add or update a language" .
Thanks to check & feedback.

**Comment by feyll** [comment]
@khouloudbelguith , i had already done this step, in any case now I tried again to update the language and the problem continues to be present. Debug mode responds with the same error

**Comment by khouloudbelguith** [comment]
@feyll, about the iso code in your case, you have set it `en-us` but in our case, the maxlength is "2"
![image](https://user-images.githubusercontent.com/16067358/51742871-3a33be00-209b-11e9-835d-211b0222cadf.png)
Thanks to edit the iso code in your case & feedback.
(Sorry for the close, I just reopened it.)

**Comment by feyll** [comment]
it's already like that
![screenshot 15](https://user-images.githubusercontent.com/27018255/51743971-a82db480-209e-11e9-992b-a8100fd06557.png)

**Comment by khouloudbelguith** [comment]
@feyll, could you please try to delete this language created manually, then you need to navigate to your BO => International => Translations => "Add / Update a language" part, Select the "English" language and click on the button "Add or update a language"., if it is NOK, can you import the "United States", check & feedback.

**Comment by feyll** [comment]
@khouloudbelguith , i deleted the language from BO and I downloaded the English language (GB) iso code en-gb.
I confirm that the problem is identical, the debug responds with the same error

**Comment by khouloudbelguith** [comment]
@feyll, did you made any changes in ps_languageselector module?
if no, could you please try to disable it temporarily, check & feedback.
Thanks!

**Comment by feyll** [comment]
@khouloudbelguith Yes, now with the module deactivated and active debugging I no longer receive an error message.
I had made a change, I had added an English flag jpg image

**Comment by khouloudbelguith** [comment]
@feyll, those changes make errors, you need to remove those changes, so you can enable this module and you will not have errors.
Your issue is not a PrestaShop's core bug but a customization problem 
I close the issue, feel free to open a new one when needed. 
Thanks!
