### ISSUE TITLE
saving employee options Will cause add new employee Button to dissapear

### ISSUE THREAD

**Issue by marchspa** [PrestaShop/PrestaShop#12302]
Ps 1.7.5

**Comment by marchspa** [comment]
![download_20190124_193438](https://user-images.githubusercontent.com/33666598/51713188-f0ea5c80-200f-11e9-8813-9498c5200047.jpg)

**Comment by khouloudbelguith** [comment]
Hi @marchspa,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0
I attached a video record.
https://drive.google.com/file/d/1CrIqjIbcBDPErOHEPVeV_DbXS_-Ue3Cy/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by marchspa** [comment]
Hi @khouloudbelguith the video is not what i said, after **saving employee options**, not after adding a new employee. Maybe it's because the screenshot isn't clear, below the employee list there is a bunch of options and a save button. If you hit save you'll be able to reproduce it. 
thanks!

**Comment by khouloudbelguith** [comment]
Hi @marchspa, 

Thanks for this clarifications.
Yes, you are right.
I manage to reproduce the issue with PS1.7.4.4 & ps1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/51753917-492a6880-20bb-11e9-9327-a37670a0b799.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @marchspa,

I did not manage to reproduce the issue with the branch PS 1.7.6.x, it is fixed.
https://drive.google.com/file/d/1mXuREC9pkNxRl2RcjnhlAo40yvz2rVxt/view
I close the issue, feel free to open a new one when needed.
Thanks!
