### ISSUE TITLE
Legacy translator in modern module controllers

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#12310]
We were developing module in PrestaShop 1.7.5 using Symfony controllers, however, one issue we faced is that `$translator->trans()` does not work for modules (translations key's doesn't show up in Back Office Translations).

What we did is created `LegacyTranslator` service that has `l()` (for compatibility with legacy translation system) method:

```php
namespace MyModule;

class LegacyTranslator
{
    public function l($key, $file = false)
    {
        return Module::getInstanceByName('mymodule')->l($key, $file);
    }   
}
```
This is basically a wrapper around legacy translations, that allows module developers to make their modules translatable when using Symfony controllers.

I think that PrestaShop should provide this kind of service until new translation system can be used in modules.

@matks @eternoendless wdyt?

**Comment by matks** [comment]
I like it ❤️ however I'm waiting for @eternoendless and @mickaelandrieu feedback because maybe they have something else in mind

**Comment by 123monsite-regis** [comment]
I like it :heart_decoration: too, 

the best for us, well be whith a fallbak on "Admin domain" traduction for key,
( in order not to have to translate again and again, "Save, "add", etc),

but this is in fact the new translation system.

regards

**Comment by mickaelandrieu** [comment]
> I think that PrestaShop should provide this kind of service until new translation system can be used in modules.

I think we should finish the new translation system instead :angel: , we have no good reason to provide this support when almost everything now accepts Xliff files, or we need to assume that the translation system won't be finished in 1.7.x.

WDYT @eternoendless ? Fallback on legacy system until 1.8.x or finish the migration of the system?

**Comment by sarjon** [comment]
> we have no good reason to provide this support 

i think we do. regarding of whether new translation system will be finsihed or not, legacy system will stay in 1.7 for sure.

in addition, module developers can't use symfony controllers because their modules become untranslatable (of course you can do this workaround in every module, but it's a bad DX imo) which is really sad. :(

**Comment by mickaelandrieu** [comment]
> i think we do. regarding of whether new translation system will be finsihed or not, legacy system will stay in 1.7 for sure.

I disagree as it's not supported right now, so it's not used... if we provide a native feature for it, it's like saying "old translation system works on Symfony Controllers": this is not something we want to push as the only missing feature is the support of external modules for the new translation system.

> in addition, module developers can't use symfony controllers because their modules become untranslatable (of course you can do this workaround in every module, but it's a bad DX imo) which is really sad. :(

Totally agree on the issue and on the importance of the issue, but disagree on the gains of this workaround versus "real" support of translation system :+1: 

In all cases, this can't be merged in 1.7.5.x and if we plan to do it in 1.7.6.x, let's do it right isn't it?

**Comment by sarjon** [comment]
i'd also prefer to see new translation system working everywhere for 1.7.6. 

either way, we need one of these 2 in next minor. :pray:

**Comment by mickaelandrieu** [comment]
> either way, we one of these 2 in next minor.

Agree, we need this to be part of 1.7.6.x!

**Comment by sarjon** [comment]
Closing as this is being solved in https://github.com/PrestaShop/PrestaShop/pull/11321 by @mickaelandrieu :heart:
