### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by odan** [PrestaShop/PrestaShop#12319]
**Describe the bug**

Typo in german translation: "Aretikel"

https://github.com/PrestaShop/TranslationFiles/search?q=Aretikel&unscoped_q=Aretikel

Expected translation: "Artikel"

**To Reproduce**
Steps to reproduce the behavior: Select a category and then "Delete"

**Screenshots**

![image](https://user-images.githubusercontent.com/781074/51787442-5fdfc680-2172-11e9-94af-54f345022af8.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @odan,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/51822573-119b0680-22dd-11e9-9777-175a40beccd6.png)
@LouiseBonnard what do you think? it could be fixed in Crowdin
Thanks!

**Comment by LouiseBonnard** [comment]
@odan, @khouloudbelguith, hello! It must be a typo, then I guess you can correct it on Crowdin: just go in the right directory ([here](https://crowdin.com/project/prestashop-official/de#/1.7.5)) and search the wording to modify it. ;-)

**Comment by khouloudbelguith** [comment]
@LouiseBonnard Done!
Thanks!

**Comment by LouiseBonnard** [comment]
@khouloudbelguith, I've just approved the suggested changes, thank you very much!
