### ISSUE TITLE
Admin Invoices - Expected argument of type "object, array or empty", "string" given

### ISSUE THREAD

**Issue by fabienfaff** [PrestaShop/PrestaShop#12314]
Hello, 
After upgrading using OneClick module 1.6.20 -> 1.7.1 -> 1.7.5 I'm having trouble accessing the Invoices tab in admin.
I was having the same problem for other tabs, and replacing ps_access from clean install solved that, but not for the invoices tab.
The error is the same encountered on issue #11909 and despite doing as @rdy4ever mentioned, the problem is still not resolved.

Could you please provide any help?

Thank you.

**Screenshots**
![screenshot_2019-01-25 expected argument of type object array or empty string given 500 internal server error 2](https://user-images.githubusercontent.com/31473076/51749847-c69cab80-20b0-11e9-865c-1e6ec5497bdf.png)

![screenshot_2019-01-25 informations lebigdeal shop](https://user-images.githubusercontent.com/31473076/51749886-e0d68980-20b0-11e9-900b-c48669d75ed4.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0.33
max_execution_time: 340
memory_limit : 512M

**Comment by khouloudbelguith** [comment]
Hi @fabienfaff,

We did not manage to reproduce the issue with PS1.7.5.0 after upgrade from 1.6.1.23 with the 1-click upgrade v4.5.1.
But, have you tried to replace the ps_configuration_lang table in the Database with the one from clean PS1.7.5.0 installation?
Thanks!

**Comment by fabienfaff** [comment]
Hello, 
Thank you for your quick reply. Yes I have tried that as well. I should mention that this is a french shop with 3 languages.

SQL returned the following after dropping ps_configuration_lang and importing a clean one : 
![screenshot_2019-01-25 srv ffdigital fr 8443 localhost presta17_ syf973configuration_lang phpmyadmin 4 8 4](https://user-images.githubusercontent.com/31473076/51751066-28aae000-20b4-11e9-84a1-e591080d03a8.png)

Content of this table after import:
![screenshot_2019-01-25 srv ffdigital fr 8443 localhost presta17_ syf973configuration_lang phpmyadmin 4 8 4 1](https://user-images.githubusercontent.com/31473076/51751091-39f3ec80-20b4-11e9-88b9-58063a2a14eb.png)

Thanks again.

**Comment by khouloudbelguith** [comment]
@fabienfaff, if you try to replace also the table ps_configuration by a clean PS1.7.5.0 installation, have you the same issue also.
because you need to check in the ps_configuration table the id_configuration where name =  "PS_INVOICE_LEGAL_FREE_TEXT" and you should insert it in the table ps_configuration_lang as described here: https://github.com/PrestaShop/PrestaShop/issues/11909#issuecomment-450491851 
Thanks!

**Comment by fabienfaff** [comment]
Hello,
Problem solved by copying fresh ps_configuration in addition to  ps_configuration_lang.
Thank you for your help.

**Comment by khouloudbelguith** [comment]
Hi @fabienfaff,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11909

**Comment by Matt75** [comment]
@khouloudbelguith Here a tutorial to fix this issue

If you have an error 500 on `Orders > Invoices` with this error

```
Symfony\Component\Form\Exception\UnexpectedTypeException:
Expected argument of type "object, array or empty", "string" given
```

_Of course you have to check if you use `ps_` as table prefix before_

# First check `PS_INVOICE_LEGAL_FREE_TEXT`

Execute this query

```sql
SELECT * FROM `ps_configuration_lang` WHERE `id_configuration` = (SELECT `id_configuration` FROM `ps_configuration` WHERE `name` LIKE 'PS_INVOICE_LEGAL_FREE_TEXT')
```

If no result, here is the issue.

So you can execute this query to create the language entry in `ps_configuration_lang` to solve the issue.

```sql
INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`) VALUES
(
	(SELECT `id_configuration` FROM `ps_configuration` WHERE `name` = 'PS_INVOICE_LEGAL_FREE_TEXT'),
	(SELECT `value` FROM `ps_configuration` WHERE `name` = 'PS_LANG_DEFAULT'),
	(SELECT `value` FROM `ps_configuration` WHERE `name` = 'PS_INVOICE_LEGAL_FREE_TEXT')
)
```

# If you have still the issue, you have to check `PS_INVOICE_FREE_TEXT`

Execute this query

```sql
SELECT * FROM `ps_configuration_lang` WHERE `id_configuration` = (SELECT `id_configuration` FROM `ps_configuration` WHERE `name` LIKE 'PS_INVOICE_FREE_TEXT')
```

If no result, here is the issue.

So you can execute this query to create the language entry in `ps_configuration_lang` to solve the issue.

```sql
INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`) VALUES
(
	(SELECT `id_configuration` FROM `ps_configuration` WHERE `name` = 'PS_INVOICE_FREE_TEXT'),
	(SELECT `value` FROM `ps_configuration` WHERE `name` = 'PS_LANG_DEFAULT'),
	(SELECT `value` FROM `ps_configuration` WHERE `name` = 'PS_INVOICE_FREE_TEXT')
)
```

**Comment by khouloudbelguith** [comment]
@Matt75, thank you!

**Comment by Maofree** [comment]
Hi Matt75
I get this error with your code

![1](https://user-images.githubusercontent.com/653230/57520800-e33ab780-731e-11e9-9443-d5350ada8112.png)

# 1048 - The 'id_configuration' column cannot be null

**Comment by Matt75** [comment]
@maofree Try this : https://github.com/Matt75/fixconfigurationlang

**Comment by Maofree** [comment]
hi
yes it has fixed the problem but for a variable it cannot be done

PS_INVOICE_LEGAL_FREE_TEXT cannot be fixed

is it ok?

![1](https://user-images.githubusercontent.com/653230/57521462-a1ab0c00-7320-11e9-8f40-251e1569e221.png)

**Comment by Maofree** [comment]
with a site I get this result

![11](https://user-images.githubusercontent.com/653230/57522738-462e4d80-7323-11e9-9715-d6a1f11abcbb.png)

in other 2 sites was all ok
however in all cases the problem is solved

**Comment by Matt75** [comment]
Yes it's good, the value cannot be fixed if we can't find it in the database but Prestashop will create it if not found at next saving process of concerned settings page. So it's fixed

**Comment by Dihya1988** [comment]
> @maofree Try this : https://github.com/Matt75/fixconfigurationlang

Thank you so much. It has fixed my issue.
