### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by pnshurba** [PrestaShop/PrestaShop#12312]
When working in the backoffice sometimes an error occurs.
What could be the problem?

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2
Theme: Warehouse 4.2.1
![screen](https://user-images.githubusercontent.com/39360984/51749047-50537580-20bf-11e9-9a21-0b4f5a301205.png)

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to delete all cookies, it could be a cookie related problem. In Chrome, for example, to delete all cookies you right-click->Inspect element->Application->Cookies->Delete all cookies.
Also, check the developer console in your browser, see if you have some errors there.
Another approach, try to log in in the admin using the browser Incognito mode (Ctrl+Shift+P in Google Chrome). This way you will start without any cookies set. See if it works.

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
