### ISSUE TITLE
importing combinations with the same reference does not work

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#12321]
**Describe the bug**
Import combinations (attributes) does not work.

**To Reproduce**
1. Go to 'controller=AdminImport'
2. Upload attrachted csv file and click import.
3. No errors, everything went fine.
4. Now check product. Expected 40 combinations, find only 1. There should be 20 colors and a select box with 2 options.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 7.1
PHP version: 1.7.5.0

[combinations_import.zip](https://github.com/PrestaShop/PrestaShop/files/2799565/combinations_import.zip)

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

I did not manage to reproduce the issue with PS1.7.5.0.
I imported this file 
[combinations_import.csv.tar.gz](https://github.com/PrestaShop/PrestaShop/files/2802159/combinations_import.csv.tar.gz)
In the product page, I have this 
![image](https://user-images.githubusercontent.com/16067358/51825082-4eb6c700-22e4-11e9-92d3-e0141d089c39.png)
I also tried with your import file & it is OK
https://drive.google.com/file/d/1Z6QQRNStbrWSvdCyJvkgLiYBn093xDK1/view
Thanks to check & feedback.

**Comment by MathiasReker** [comment]
Thats weird. I have a fresh install and the product import works.

**Comment by khouloudbelguith** [comment]
@MathiasReker, if you enable the debug mode, is there any exception displayed?
Are there errors in your PHP log file?
Thanks!

**Comment by MathiasReker** [comment]
No errors in debug or in php error log

**Comment by khouloudbelguith** [comment]
@MathiasReker, I tried with a new installation 1.7.5.0 & it is OK.
![image](https://user-images.githubusercontent.com/16067358/51831535-9e03f400-22f2-11e9-8668-72187a994203.png)
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!

**Comment by MathiasReker** [comment]
Thanks, I will look further into this.

**Comment by MathiasReker** [comment]
@khouloudbelguith I found the bug, but I did not solve it. I have included CSV file and screenshot with settings, please check.

Set the combinations with SAME reference:

When import with CSV it only takes the last combination
When doing manual from BO it works.

[combination.zip](https://github.com/PrestaShop/PrestaShop/files/2807608/combination.zip)

**Comment by MathiasReker** [comment]
The reference MUST be unic otherwise the import does not work. This is a bug.

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

Thanks for your feedback.
Yes, now I manage to reproduce the issue with PS1.7.5.0& PS1.7.4.4.
If I import combinations with the same reference, it only takes the last combination
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by MathiasReker** [comment]
I tried to fix it, but I did not manage to do it.

Can you add it for 1.7.5.1? This minor issue blocks an easy migration to 1.7.

**Comment by khouloudbelguith** [comment]
@MathiasReker, why it blocks the migration for PS1.7.?
Thanks!

**Comment by MathiasReker** [comment]
I export all combinations on my PS 1.6 store. Then I import the combinations on a new 1.7 store.

With this bug, I can't have the same Reference.

**Comment by khouloudbelguith** [comment]
ping @eternoendless @colinegin what do you think, can we fix this issue in the PS1.7.5.1?
Thanks!

**Comment by MathiasReker** [comment]
Any news ? :)

**Comment by SharakPL** [comment]
@khouloudbelguith @eternoendless  @colinegin another thing about reference during import. It cuts off leading 0s. References like 0123456 are imported as 123456. It should import whole string exactly as it is.

**Comment by khouloudbelguith** [comment]
@SharakPL, this is a different issue, can you open a new one with more information about your configuration.
Thanks!

**Comment by MathiasReker** [comment]
> 
> 
> @khouloudbelguith @eternoendless @colinegin another thing about reference during import. It cuts off leading 0s. References like 0123456 are imported as 123456. It should import whole string exactly as it is.

+1

**Comment by SharakPL** [comment]
@khouloudbelguith @eternoendless @colinegin @MathiasReker nevermind reference. Made some testing and all imports with leading 0 are OK. Turned out leading 0s were removed by my spreadsheet editor that even when I explicitly set field types as plain text and save my .csv, reopening it loads all fields with digits only as numbers without leading 0. I just need to find something _useful_ to edit my data... or simply avoid csv format as xls xlsx and ods work better.
Sorry for the confusion.

**Comment by colinegin** [comment]
Hello @MathiasReker ,

Thanks for your feedback, unfortunately this is not a regression from 1.7.5.0, so we won't be able to fix it for 1.7.5.1.

We will review this issue when working on the import system, probably for 1.7.7.
If possible, do not hesitate to make a pull request to fix the bug.

Thank you for your understanding

**Comment by MathiasReker** [comment]
@colinegin I understand that this is not a regression from 1.7.4, but this is a major part to migrate manuelly from 1.6 to 1.7. Therefore I hope you can take a look at it for next patch release. I am stock on 1.6 until this issue is fixed. I was not able to fix it, but I think it will be quick for one of your developers :)

**Comment by colinegin** [comment]
Hello @MathiasReker,

I really understand your situation, and I'm sorry this is a blocking issue for you.
Unfortunately, we won't be able to fix it during a patch, as it requires indepth study and probably not just a small development.

We will work on the import system as soon as possible.
We will keep you updated !

Have a nice day,

Coline

**Comment by mrjcgoodwin** [comment]
@MathiasReker Did you ever find a work-around or create your own patch for this. Just ran into this issue for the first time today and it's a pain. I'm going to have to append an arbitrary number to the end of all my combos I think.
