### ISSUE TITLE
Very slow dev environment any suggestions?

### ISSUE THREAD

**Issue by juslintek** [PrestaShop/PrestaShop#12326]
Any Ideas why new install is so slow php 4G memory limit, apache, mysql, php 7.2 windows laragon AMP stack, fails to connect using memcache dll from pecl, but still pretty slow? http://prntscr.com/md0whc as well my mysql specs: https://paste.ofcode.org/34xSHUa9uq54363c49y6gFW and my php https://paste.ofcode.org/qzuksumxzUCFqx6zZWWiaE

I've cloned master of this repository, from load time stack I can see that, controller is loading very long, then twig is parsed very long and saved very long. Why? On symphony on laragon twig is crazy fast. And on here its very slow, got demo data installed.

**Comment by khouloudbelguith** [comment]
Hi @juslintek,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by juslintek** [comment]
![image](https://user-images.githubusercontent.com/5687423/51931531-badd1c00-2405-11e9-8e4b-255f4a7950d2.png)

**Comment by khouloudbelguith** [comment]
Hi @juslintek,

Thanks for your feedback.
To install PrestaShop, you have some [system requirements](https://www.prestashop.com/en/system-requirements), so in the PHP configuration (php.ini file) set memory_limit to "128M" and upload_max_filesize to "16M" (or more if available), in your screenshot, they are displayed on Red, thanks to change the settings, check & feedback.

**Comment by juslintek** [comment]
Okay seems that everything got faster, just needed less memory. But still in debug mode its quite slow. guess it has to be like that.

**Comment by khouloudbelguith** [comment]
@juslintek, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
