### ISSUE TITLE
Cannot set specific price when product module tab is present

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#12335]
**Description**
Having 1.7.5.0 installed, even (again) with a fresh install to avoid the possible other conflicts with many modules:

From the moment I install a module (in my case: Product Fields manager) that creates a Module product tab, I have issues with the specific price discount amount and dropdown menus ("% or €" and "incl/excl. tax" settings)... 

- I cannot fill in the specific price (the text field is not responding on click)
- the dropdown to choose percentage or amount is not reacting on click
- the dropdown to choose incl/excl tax is also not reacting on click

I hope to get the know the fix... Thank you!

Please see attachment.

**To Reproduce**
1. Install a module that created a Product Module Tab on Products
2. Go to 'Products'
3. Click on any product
4. Click on the Prices tab
5. Add/Configure specific price
6. Try to change the fields from the attachment
7. Inactivating (no need to uninstall) the module, makes it work again.

**Screenshots**
<img width="1552" alt="schermafbeelding 2019-01-28 om 13 45 26" src="https://user-images.githubusercontent.com/43880279/51848459-ebe22180-231d-11e9-8f32-1794f02d0b37.png">

**Additionnal information**
PrestaShop version: 1.7.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1JgEU-Jt9QdfU3fb3lIqlLGrwqI8VZK1H/view
I tried with the `blockyoutubevideos` module & also with this module https://github.com/dheerajwebkul/wktestadminproductextra and it is OK.
Thanks!

**Comment by Ybeske** [comment]
Hi khouloudbelguith, thanks to try it.
I discovered something: From the moment I activate the module, there is a "transparent" element covering most of the the spoken text and selection fields. It only works if you click on the top of the elements... see attachment. Who's responsible for this "bug"? What can I do to make the fields intuitive again? Please check if you also have such an element on top of the other fields.

![image_from_ios](https://user-images.githubusercontent.com/43880279/51939243-4909d000-240f-11e9-8a84-27e432221932.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

Thanks for your feedback.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@Ybeske, about your screenshot, I checked  PS1.7.5.0 where I have a module installed & not installed, in the two cases, I have this 
```
<div class="col-md-12 text-sm-right">
    <button type="button" id="form_step2_specific_price_cancel" name="form[step2][specific_price][cancel]" class="btn-outline-secondary js-cancel btn">Anuluj</button>
    <button type="button" id="form_step2_specific_price_save" name="form[step2][specific_price][save]" class="btn-outline-primary js-save btn">Zastosuj</button>
  </div>
```
displayed, it is the element for buttons "Cancel" & "Apply"
1. Module not installed
![image](https://user-images.githubusercontent.com/16067358/51967360-69697700-246f-11e9-878a-6eca7ebaddba.png)
2. Module installed
![image](https://user-images.githubusercontent.com/16067358/51967449-9cac0600-246f-11e9-923b-ec82eeb741fb.png)
Thanks!

**Comment by Ybeske** [comment]
Before I will put some pressure on Prestashop core developers, I contacted the developers of the module I'm having problems with.

Maybe this info is useful:
The inline style in the page source: I suspect this inline style is added because of the module.
The line ...  height:40px op .col-lg-3  is disturbing the BO interface.

<style>
        .col-lg-3{
                float: left;margin-bottom: 0px; height:40px;
        }
        .col-lg-9{
                float: right; height:40px;
        }
</style>

From the moment I have feedback, I will let you know.

**Comment by khouloudbelguith** [comment]
@Ybeske, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by Ybeske** [comment]
Hi there. The problem was caused and solved by the module developer.

They added 
            <style>
                div.text-sm-right{
                    margin-top: 28px;
                }
            </style>';

into their main .php file.

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

Thanks for your feedback.
I will close the issue, feel free to open a new one when needed.
Thanks!
