### ISSUE TITLE
Fix minor display issues introduced by webpack update

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12333]
https://github.com/PrestaShop/PrestaShop/pull/10911 has been merged but some issues were reported by QA team:
- https://github.com/PrestaShop/PrestaShop/pull/10911#issuecomment-458168741
- https://github.com/PrestaShop/PrestaShop/pull/10911#issuecomment-458169848
- https://github.com/PrestaShop/PrestaShop/pull/10911#issuecomment-458179568

It needs to be fixed and validated by QA again 😄

**Comment by khouloudbelguith** [comment]
I have the same issue with develop branch in the product page.
![image](https://user-images.githubusercontent.com/16067358/51853050-aa567400-2327-11e9-9b51-ada5f25d71d2.png)
![image](https://user-images.githubusercontent.com/16067358/51853055-ac203780-2327-11e9-99e9-20c388ce158c.png)
Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

In the product page, if we click on the help icon button, they are not well-displayed and they are superposed.
![image](https://user-images.githubusercontent.com/16067358/51966156-ff9b9e00-246b-11e9-9ac0-0db85313f113.png)
Thanks!

**Comment by marionf** [comment]
Another way to reproduce the issue:
https://drive.google.com/file/d/1e6pvuGuX4pEiCAkNYBRd9rSnhoL37JUk/view?usp=sharing

**Comment by colinegin** [comment]
@matks is it a critical task for 1.7.6 ?
We need to prioritize this issue compared to all the other projects in progress.

**Comment by matks** [comment]
@colinegin It looks really dirty in the BO now and popups are messed up. Looks critical to me and I think @marionf will agree ^^

**Comment by marionf** [comment]
Yes and furthermore it's a regression

**Comment by khouloudbelguith** [comment]
In the product page, we have other issues.
Before
![image](https://user-images.githubusercontent.com/16067358/52799468-2ec02b00-307a-11e9-8254-4c0e9bbdec40.png)
After
![image](https://user-images.githubusercontent.com/16067358/52799494-367fcf80-307a-11e9-909a-1aea8badef51.png)
![image](https://user-images.githubusercontent.com/16067358/52799500-397ac000-307a-11e9-9adf-7257bcba7ccb.png)

Thanks!

**Comment by marionf** [comment]
Fixed by #12739
