### ISSUE TITLE
Issue with editing a credit note

### ISSUE THREAD

**Issue by sabrinadis** [PrestaShop/PrestaShop#12347]
Hello,

I use Prestashop 1.6.1.20.

I am having a problem trying to edit a credit note.

it is an order for which an exchange request has been made. The exchange has been validated on Prestashop. However, the client finally wanted a refund.

When I am on my order page, I click on "return product". Normally, the next step is to select the returned product and then click on the "create a credit note" button. But in this case I can't select the product.

Please find attached 2 screen shots detailing my problem : 
- Screen shot 1 : a standard order 
- Screen shot 2 : the order concerned

Can someone here help me solve this issue ?

Thanks in advance
Sabrina
![screen shot 1](https://user-images.githubusercontent.com/47142470/51905726-4e8cf900-23c2-11e9-8377-3e369f11fb0f.png)
![screen shot 2](https://user-images.githubusercontent.com/47142470/51905727-4f258f80-23c2-11e9-8fed-6d964bc94f9c.png)

**Comment by khouloudbelguith** [comment]
Hi @sabrinadis,

I did not manage to reproduce the issue with PS1.6.1.23.
I attached a video record.
https://drive.google.com/file/d/1SE2Pu9cHmsM4WNx_r0PJzcPIzHkm61U0/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
Thanks!
