### ISSUE TITLE
Tax calculates wrong precentage

### ISSUE THREAD

**Issue by massehbg11** [PrestaShop/PrestaShop#12359]
**Describe the bug**
If i choose the 25% tax, 100 should be 75 (tax excluded)
![tax](https://user-images.githubusercontent.com/45628492/51971157-d0d7f480-2478-11e9-9df3-c8de95fe7489.png)

If i choose the 12% tax 100 should be 88(tax excluded)
![tax12](https://user-images.githubusercontent.com/45628492/51971382-4ba10f80-2479-11e9-8cbf-4b87f270a315.png)

This behavior is in the cart aswell, seems to be som kind of wrong calculation! Anyone has an idea how to solve this issue? Or have an idead how i can manually fill both tax incl and excl?

Also in the tax settings the rate is at 25.000 so nothing is wring there either!

**To Reproduce**
1. Go to 'products'
2. Click on 'product'
3. Scroll down to 'tax'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5 i hade the same issue in 1.7.4.4
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment]
Hi @massehbg11,

In your first screenshot, you have a
1. price tax excluded = 80
2. Tax rule = 25%
3. Price tax included = (80*25%) +80 = 20 + 80 = 100

In your second screenshot

1. price tax excluded = 89.285714
2. Tax rule = 12%
3. Price tax included = (89.285714 * 12%) +89.285714 = 100

So, it is correct.
Thanks!
