### ISSUE TITLE
Introduce new file type input on every page in back-office

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#12360]
As In https://github.com/PrestaShop/PrestaShop/pull/12331 I need to introduce new file type input which is used in PrestaShop UI kit.

![filetype](https://user-images.githubusercontent.com/17051250/51979420-c415c980-2495-11e9-9d87-e2bf438e01bb.png)

what I'm thinking now that I can introduce it to all pages which are currently using `FileType` input which currently looks like this:

![no_file_choosen](https://user-images.githubusercontent.com/17051250/51979547-13f49080-2496-11e9-9aa9-77010adce5d3.png)

The main issue is that despite the fact it looks really nice but it looses some default functionality which is:
**An uploaded file name is not visible to the user**

You can try to upload a file by finding the input here https://cdn.rawgit.com/PrestaShop/prestashop-ui-kit/master/index.html - the name of the uploaded file is not visible

**My solution**

1. Fix the problem in the PrestaShop UI kit (I think that's possible)
2. Introduce it on every page of PrestaShop when fixed

**Comment by matks** [comment]
Thanks @tomas862 you're right : the right solution is to improve the UI Kit. Do you feel like trying to do it ? Else I can take it.

**Comment by tomas862** [comment]
I have several solutions in mind and the fact that this is needed for my PR I can improve UI kit ;)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/prestashop-ui-kit/pull/59
