### ISSUE TITLE
Remove CategoryPositionColumn and Use PositionColumn instead

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#12368]
**Describe the bug**
This issue is caused by a parallel work on `1.7.5.x` & `develop` branches which has diverged.

It seems the class `CategoryPositionColumn`, going to be released with PrestaShop 1.7.6.0, is not really needed and could be removed in favor of `PositionColumn`.

It requires an update on the parameters which have changed since the release of PS 1.7.5.0, and must now rely on Symfony routes. We cannot do this task for now as the position update of a category is still handled by the legacy controller.

To avoid pushing a potential unnecessary class in a release, it would be great to considerate this task before PS 1.7.6.0.

**To Reproduce**
Nothing to test, this issue is a refacto request.

**Additionnal information**
PrestaShop version: `develop` branch, to be done before 1.7.6.0
PHP version: 7.2

**Comment by colinegin** [comment]
@Quetzacoalt91 is it a critical task for 1.7.6 ?
We need to prioritize this issue compared to all the other projects in progress.

**Comment by Quetzacoalt91** [comment]
It would be great, because the concerned classes are not released yet. As soon as they are released, we must take care of not breaking the compatibility with other versions.

**Comment by matks** [comment]
@colinegin I confirm this issue is less relevant now. If we had done it before 1.7.6 was out, we would have been able to delete an unnecessary piece of code because it was duplicated. However, 1.7.6 is now released and it is forbidden for us to delete pieces of code released as it might now be used by a module. We will only be able to remove this piece of code in next major.

The only thing we can do now is to deprecate class `CategoryPositionColumn` and use `PositionColumn` instead. But there is no need to be quick anymore.

**Comment by colinegin** [comment]
Thanks for the feedback ! I'm leaving this issue in the backlog then, just in case we have nothing left to do :) I'm unassigning you !

**Comment by LouiseBonnard** [comment]
Hi @Quetzacoalt91, @matks, what's the status of this issue? Should we move it to the 1.7.8 or next major kanban?

**Comment by PierreRambaud** [comment]
I don't think it's needed any more, Classes are really different :thinking:

**Comment by hibatallahAouadni** [comment]
Hello @Quetzacoalt91 

> I don't think it's needed any more, Classes are really different

Well @PierreRambaud said it's not needed any more and we had no news from you for more than 20 days. So, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create **reopen** the issue if further information pops up :wink: 

Thanks!
