### ISSUE TITLE
Create a simple module, install and uninstall => can't access anymore the module

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [PrestaShop/PrestaShop#12365]
1 Create the simplest module (for example use a module created with https://validator.prestashop.com/generator)
2 Install
3 Uninstall

==> In module manager you cannot  access anymore the module
You cannot reinstall the module

**Comment by khouloudbelguith** [comment]
Hi @nicoja,

After uninstalling the module, could you please navigate to the BO => Modules => Module Catalog, search for this module => you can find it?
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Hi @khouloudbelguith,
no I cannot find it

**Comment by khouloudbelguith** [comment]
@nicoja, when uninstalling the module, did you select the option " Optional: delete module folder after uninstalling.  "?
In my case no & I can find the module after uninstalling the module
https://drive.google.com/file/d/17khfNTHG50h50PlzQO067cWvY_5qQoLr/view
Thanks to check & feedback.

**Comment by Kixell-NicolasJardillier** [comment]
No I did not remove select the option to delete the module folder ;) And I can see it in my project folder.
I try another module and it is the same.

I use fresh install of Prestashop
Work locally with MAMP PRO
PHP 7.2.10
Nginx / Mysql

**Comment by khouloudbelguith** [comment]
@nicoja, what the exact version of PrestaShop?
Is it 1.7.5.0?
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
yes 1.7.5.0
I remove everything and try a new fresh install ..... Prestashop + Module

**Comment by khouloudbelguith** [comment]
@nicoja, could you please try with this demo module, in my case, it is OK with nginx/1.14.0 & PS1.7.5.0.
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2813164/mymodule.zip)
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
@khouloudbelguith I saw your message after
you ll find here my module and also the video : https://drive.google.com/file/d/1So6AhhHpxPYcptnX6eie9f5PjfKlq0h0/view
[k_test.zip](https://github.com/PrestaShop/PrestaShop/files/2813227/k_test.zip)

**Comment by Kixell-NicolasJardillier** [comment]
@khouloudbelguith Now I tried with your module and also have the problem
https://drive.google.com/open?id=1NAIbQi1uztsNkXoD0xE4MEmkDWORefrM

**Comment by khouloudbelguith** [comment]
@nicoja, no after uninstalling a module, you need to search it in the Module Catalog page & not in the Module Manager page
 https://drive.google.com/file/d/17K8k6MNOnCGGCRPTm9Viz9K6KKsT7gzE/view

**Comment by Kixell-NicolasJardillier** [comment]
@khouloudbelguith Okay, many thanks, so simple !
It could be close .... I am a 1.6 prestashop user, I think that this exchange is clearly a good user test case for you ;)
Again thanks for the time you spend

**Comment by khouloudbelguith** [comment]
@nicoja, you are welcome!
Feel free to open a new one when needed.
THanks!

**Comment by Kixell-NicolasJardillier** [comment]
How you delete an uninstall module ? .... another use case 
Thks again

**Comment by khouloudbelguith** [comment]
@nicoja, when you uninstall the module, click on the option: "Optional: delete module folder after uninstalling." => so it will be removed after the uninstall.
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
@khouloudbelguith I meant if you want to delete a module already uninstalled, not delete an installed module during uninstall process.
I think this cannot be possible with this use case

**Comment by khouloudbelguith** [comment]
@nicoja, do you need to remove the module folder from your Project_Folder/modules/ path?
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Yes
I think that we should be able to delete an uninstalled module from the "Catalogue de modules" interface in the backoffice, don't you ?
At the moment if you do not want to delete it manually (i.e., ssh, ftp, etc ...) and want to delete it from the backoffice interface, you have to reinstall the module then unsintall with the option delete checked.
Hope to be clear enough

**Comment by khouloudbelguith** [comment]
@nicoja, yes it is clear.
But in the Catalog page, we have only listed all modules not installed. 
In the Module manager page, we can uninstall a module & removed it completely when we click on this option "Optional: delete module folder after uninstalling" => it is the best behavior.
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Never mind, should be another discussion.
Best regards @khouloudbelguith and thanks again for all the time you took.

**Comment by khouloudbelguith** [comment]
@nicoja, you are welcome!
