### ISSUE TITLE
Better Support UTF8 charset in products with combinations page

### ISSUE THREAD

**Issue by ivysotskyi** [PrestaShop/PrestaShop#12371]
**Is your feature request related to a problem? Please describe.**
My hosting uses cp1251 default collate charset in MySQL database. That's why it is needed to set utf8 on every connection. With some hack in PDO constructor (#11648), I've launched my shop. But seems like only one thing is not working: combinations window in "new product" still has the wrong charset.

**Describe the solution you'd like**
I've investigated the issue and discovered that this piece of information is not going through PDO. Callstack:
Query->execute:917	
Query->getArrayResult:732	
AttributeRepository->findByLangAndShop:66	
ProductController->formAction:658	

**Describe alternatives you've considered**
I suggest to rewrite this code and maybe other code in PrestaShop to make it use only PDO or mysqli.

**Additional context**
I debugged it on version 1.7.4.3 but after update to 1.7.5.0 issue is still reproducible.
![2019-01-30_18-55-50](https://user-images.githubusercontent.com/37252364/51998111-b590d780-24c0-11e9-92ad-56cabcd68083.png)

**Comment by khouloudbelguith** [comment]
HI @ivysotskyi,

Thanks for your report.
ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by SharakPL** [comment]
@ivysotskyi the fix below might help a bit, but the main problem is with the mysql server configuration. Check its variables, specifically `init_connect`. It should be empty or `SET NAMES utf8`.
___
It seems only MySQLi has this value checked:
https://github.com/PrestaShop/PrestaShop/blob/aec97ddb1551fd7d6d56f75549a992d6937caf50/classes/db/DbMySQLi.php#L76-L79

Adding that condition to PDO connect function just after try/catch block seems to fix the problem:
https://github.com/PrestaShop/PrestaShop/blob/aec97ddb1551fd7d6d56f75549a992d6937caf50/classes/db/DbPDO.php#L122-L133

Clearing cache is required after that.

Related bug: #11155

**Comment by ivysotskyi** [comment]
Hi @SharakPL , thank you, I tried it. But it does not help in my case. It seems that it is not going through pdo at all.

See method findByLangAndShop of class AttributeRepository and set breakpoint there. If you already get into this function set breakpoint in PDO/MySQLi connect method and make sure that it doesn't go there.

**Comment by ivysotskyi** [comment]
this change fixed issue for me:
https://github.com/ivysotskyi/PrestaShop/commit/472bae61aef8accb28fcbb3249e648f8082edcb6

I tried to change configuration of sumfony database framework but not successfully. So I've made the workaround locally.

**Comment by khouloudbelguith** [comment]
Hi @ivysotskyi,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by ivysotskyi** [comment]
> Hi @ivysotskyi,
> 
> Would you be willing to make a pull request on GitHub with your code suggestion?
> https://github.com/PrestaShop/PrestaShop/tree/develop
> Thank you!

I am not sure that my change is OK from the code architecture point of view. I will create PR. But maybe fix somewhere deeper in the code should be done. My change looks like a local workaround.

An opinion of the Prestashop developers would be highly appreciated here.

**Comment by PierreRambaud** [comment]
The database will be settled to utf8mb4 in 1.7.7.0
