### ISSUE TITLE
Can't install any module on 1.7.5

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12374]
Can't install any module on 1.7.5 (both on fresh and upgraded store)
Ziped, or unziped, custom or this from https://validator.prestashop.com/generator
[topinfo.zip](https://github.com/PrestaShop/PrestaShop/files/2814530/topinfo.zip)

Error!
Cannot install module topinfo. The module is invalid and cannot be loaded.

It's look like PrestaShop block to install non Marketplace modules...

![zrzut 2019-01-30 22 36 20](https://user-images.githubusercontent.com/8243273/52014308-7f168500-24df-11e9-9795-f156c6bb3e74.png)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

I did not manage to reproduce the issue with PS1.7.5.0 fresh install or after an upgrade.
I attached a video record.
https://drive.google.com/file/d/1X-MJb4--bjiegPB_HqwnzJBuRvpjNUjR/view
Thanks to check & feedback.
Thanks!

**Comment by ghost** [comment]
Hi @khouloudbelguith  !
Wow... its means something is in hosting settings. I wil give more information. Because its very weird...

**Comment by khouloudbelguith** [comment]
@PrestaShark, that's ok.
Waiting for your feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
