### ISSUE TITLE
prestashop 1.7.3.3 webservice - get products - filter date_upd - product

### ISSUE THREAD

**Issue by Alexandre17220** [PrestaShop/PrestaShop#12385]
Hi,

I have find a bug , I think :
I do this request via WebService to get product list modified between two dates :

$xml = $webService->get(array('resource' => 'products&date=1', 'display'  => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
"filter[date_upd]" => "[2018-12-03 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));

And I got a list of products...but the first product have date_upd = 2018-09-04 14:35:17...

Why ????

If I try with anoter date like this :

$xml = $webService->get(array('resource' => 'products&date=1', 'display'  => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
"filter[date_upd]" => "[2019-01-29 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));    

the output is correct only product modified after 2019-01-29 ..

any idea?

Thanks,

ps: I have  4000 products in my table ps_product

**Comment by khouloudbelguith** [comment]
Hi @Alexandre17220,

I checked with this link

```http://Shop_Url/api/products?display=full&filter[date_upd]=[2019-01-29 16:16:39,2019-01-31 00:00:00]&date=1&sort=date_upd_ASC```

to filter products by `date_upd` & they are well displayed.
Thanks to check & feedback.

**Comment by Alexandre17220** [comment]
Yes, but for some date the result it's very strange cf : 

> $xml = $webService->get(array('resource' => 'products&date=1', 'display' => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
"filter[date_upd]" => "[2018-12-03 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));
And I got a list of products...but the first product have date_upd = **2018-09-04 14:35:17**...

**Comment by khouloudbelguith** [comment]
@Alexandre17220, I tried with your array, but something get wrong in the `HTTP REQUEST HEADER `
The Get URL is incorrect
![image](https://user-images.githubusercontent.com/16067358/52071052-7d51cd80-2582-11e9-8317-bc1659b1d70b.png)
You should have an URL like this `http://Shop_Url/api/products?display=full&filter[date_upd]=[2019-01-29 16:16:39,2019-01-31 `

Thanks!

**Comment by Alexandre17220** [comment]
maybe custom field code_zone... display=full -> no relation with the problem
there is not the problem because the second request give a correct result

**Comment by khouloudbelguith** [comment]
Hi @Alexandre17220,

Could you please provide me the exact script "GetProduct" that you use to test it.
I tried with this script
```

<html><head><title>test</title></head><body>
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 31/01/19
 * Time: 08:24
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://projet/1750');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');

try {

    $webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
    $filter= "filter[date_upd]";
    $range="[2018-12-03 16:40:48,9999-12-31 00:00:00]";
    print_r($filter);
    array($filter);

    $opt = array( 'resource' => 'products',
                        'filter[date_upd]' => "[2018-12-03 16:40:48,9999-12-31 00:00:00]",
                        'date' => 1,
                        'display'  => 'full'
                        );
//    $xml = $webService->get(array('resource' => 'products&date=1', 'display' => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
//        "filter[date_upd]" => "[2018-12-03 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));
    $xml = $webService->get($opt);
    $opt['resource'] = 'products';
    $xml = $webService->get($opt);

}
catch (PrestaShopWebserviceException $ex) {
    echo "Error:<br>";
    echo  $ex->getMessage();
    exit(1);
}

?>
</body></html>
```

I have a wrong Get URL
`GET /1750/api/products?filter%5Bdate_upd%5D=%5B2018-12-03+16%3A40%3A48%2C9999-12-31+00%3A00%3A00%5D&display=full HTTP/1.1`

Thanks!

**Comment by Alexandre17220** [comment]
ok the code : 

```
...
require_once('./PSWebServiceLibrary.php');
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG); 
$xml = $webService->get(array('resource' => 'products&date=1', 'display'  => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
"filter[date_upd]" => "[2018-12-03 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));
foreach ($xml->children()->children() as $obj_product) {
     $product_id = $obj_product->id;
     echo $product_id.'|'.$obj_product->date_upd.'<br>';
}

```

**Comment by khouloudbelguith** [comment]
@Alexandre17220,

Thanks for your feedback, after deleting the `code_zone` field, I tried with your script & it OK.
I attached a video record.
https://drive.google.com/file/d/16Q-4VS3ipuzbXmhuhBBBRU6BnCQINO5b/view
Thanks to check & feedback.

**Comment by Alexandre17220** [comment]
> maybe custom field code_zone... display=full -> no relation with the problem
there is not the problem because the second request give a correct result

Could you understand ?

**Comment by khouloudbelguith** [comment]
@Alexandre17220, I tried your script to check if your issue can be reproduced in my case 
> " I got a list of products...but the first product have date_upd = 2018-09-04 14:35:17"

But in my case, `"filter[date_upd]" => "[2019-01-30 16:40:48,9999-12-31 00:00:00]"`, I don't have any product with dat_upd < 2019-01-30 16:40

![image](https://user-images.githubusercontent.com/16067358/52128339-f90c5280-2634-11e9-8c90-8e2d98257e72.png)
thanks!

**Comment by Alexandre17220** [comment]
ok me too with this date but if I use 2018-12-03 16:40:48 the problem appear like I say in my first post.
So, it's very strange... problem and no body have the same ??

**Comment by khouloudbelguith** [comment]
@Alexandre17220, sorry I did not manage to reproduce the issue with this date `2018-12-03 16:40:48`, if you use another previously date, have you the same issue?
Thanks!

**Comment by Alexandre17220** [comment]
I don't know, I have find this date because this block my synchronization script between Prestashop and my CRM.. I cannot find other date.. I go to debug  myself prestashop's API. thanks

**Comment by khouloudbelguith** [comment]
@Alexandre17220, despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
