### ISSUE TITLE
Showcase cards are not definitely closed in multistore context

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12390]
**Describe the bug**
Showcase card reappear after closing it in multistore context

**To Reproduce**
1. Go to Shop parameters > General
2. Enable multistore
3. Go on Advanced parameters > Multistore > Create a new store
4. Define the URL for this new store
5. Click on Shop parameters > SEO & URLs
6. Close the card
7. Refresh the page, the card is still here

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by marionf** [comment]
This issue is for all configuration variables in multistore context

**Comment by colinegin** [comment]
@marionf is it a critical task for 1.7.6 ?
We need to prioritize this issue compared to all the other projects in progress.

**Comment by marionf** [comment]
It's major because it's not just about showcase cards but about all configuration variables
But it's an old issue, we can do it later when we will attack multistore
I move it in up next

**Comment by kpodemski** [comment]
hey @marionf 

could you test it using changes from my PR? #12544 

this PR aims to fix this issue but also it should help with other issues in back-office as we're now getting properly information about ShopGroup and Shop context

**Comment by marionf** [comment]
Thank you for your PR @kpodemski :+1: 
I will test it when the code review will be done

**Comment by florine2623** [comment]
On PS 8.1.x, the issue is fixed :

https://github.com/PrestaShop/PrestaShop/assets/16019289/6f2f346a-b2c3-40de-98ef-3cbbba79f744

I'm closing the issue.
