### ISSUE TITLE
Vertically align the pagination system components

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12392]
**Describe the bug**
Vertically align the pagination system components on **ALL** migrated pages

**To Reproduce**
1. Go to Advanced parameters > Logs
2. Add more than 10 logs
3. Pagination components are not aligned

**Screenshots**
![50214246-0ff62e80-0380-11e9-8d41-7af751038e15 1](https://user-images.githubusercontent.com/13449658/52072935-7b8a0900-2586-11e9-9dff-353f775da6ca.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
@matks FYI

**Comment by matks** [comment]
😭

**Comment by sarjon** [comment]
Hi @marionf, wasn't it fixed?

I cannot reproduce it, see https://prnt.sc/nnsiq9

**Comment by marionf** [comment]
Yes it's fixed :+1:
