### ISSUE TITLE
1.7.5.0 - lazyarray prevents from access content of $params in hookdisplayCartExtraProductActions

### ISSUE THREAD

**Issue by Ditwo** [PrestaShop/PrestaShop#12396]
**Describe the bug**
Get the id_product from **$params in hook** hookdisplayCartExtraProductActions is **impossible** because of **LazyArray** (protected variable)
id_product is an example of course. All the product variables are unvailaible.

**To Reproduce**
1. Create a module mymodule hooked to hookdisplayCartExtraProductActions
2. in mymodule.php, into function hookdisplayCartExtraProductActions($params) {...} :
**$params['product']->product is empty** and of course $params['product']->product['id_product'] is undefined.

**Access is not allowed because $product in \src\Adapter\Presenter\Product/ProductLazyArray.php is defined as 'protected'.** If status was set to 'public', issue would be solved. 
Previously (1.7.4.4 and <) it was easy to get $params['product']['id_product']. 

**Screenshots**

**Additionnal information**
PrestaShop version:  PS 1.7.5.0
PHP version: 5.6

Thanks in advance
Denis

**Comment by khouloudbelguith** [comment]
Hi @Ditwo,

Thanks for your report.
I tried PS1.7.5.0 with this demo module 
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2820884/mymodule.zip)
and it is OK
![image](https://user-images.githubusercontent.com/16067358/52113526-d284f200-2609-11e9-8720-d4dba0ad3e53.png)
Thanks to check & feedback.

**Comment by Ditwo** [comment]
Hi Khouloud,
Thank you so much for your time and your reply.
It's ok, Im confused, I found out the reason. It's because of the cast to an array I usually execute in this hook : 
```
            if (!is_array($params['product'])) {
                $params['product'] = (array)$params['product'];
            }
```
From PS 1.7.5 onwards, this cast is not relevant.
Have a nice day
Denis

**Comment by khouloudbelguith** [comment]
@Ditwo, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
