### ISSUE TITLE
Problem after update 1.7.5 prestashop

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12404]
Hi everyone,
I did the upgrade of my prestashop 1.7.2 to 1.7.5 but after downloaded that was ok 
I refresh the page tried to log in to my BO but got error 500. 
How can I fix it?

**Describe the bug** The server returned a "500 Internal Server Error".

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @morghy1992 

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by morghy1992** [comment]
Hi, thank you for the replay
could you explain me how to clear cache manually?

Il giorno ven 1 feb 2019 alle ore 15:26 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by morghy1992** [comment]
I tried again to log in but got this errore.
Did screenshot.
What should I do? 
<img width="1054" alt="schermata 2019-02-01 alle 15 36 31" src="https://user-images.githubusercontent.com/47249256/52129180-32de5880-2637-11e9-867b-872da6c657e3.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, during the upgrade, have you any errors displayed?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

**Comment by morghy1992** [comment]
I just installed the module and did the upgrade. I got only the Error Unable to check md5 files that I fixed chanting permission 755 and 644.
I can't find the tmp/log.txt into autoupgrade

**Comment by morghy1992** [comment]
<img width="884" alt="schermata 2019-02-01 alle 15 56 09" src="https://user-images.githubusercontent.com/47249256/52130238-eba59700-2639-11e9-966d-3c3ded5f0a89.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, could you please try to disable the welcome module.
If you cannot access to the BO => Module page, you can try to rename the welcome folder to welcome_old into the path Project_Folder/modules/
Thanks to check & feedback.

**Comment by morghy1992** [comment]
ok I changed it. I tried to log in but this is the result  :( Why? 
<img width="519" alt="schermata 2019-02-01 alle 16 06 02" src="https://user-images.githubusercontent.com/47249256/52130749-4db2cc00-263b-11e9-9a49-9760bc502ef7.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, could you please try to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

**Comment by morghy1992** [comment]
Did it, Still same situation. What can be? 
<img width="1245" alt="schermata 2019-02-01 alle 16 14 46" src="https://user-images.githubusercontent.com/47249256/52131287-afc00100-263c-11e9-86a6-aef04676bba1.png">
<img width="519" alt="schermata 2019-02-01 alle 16 06 02" src="https://user-images.githubusercontent.com/47249256/52131288-afc00100-263c-11e9-8106-12d9887c2aa3.png">

**Comment by khouloudbelguith** [comment]
@morghy1992,

Could you please try to regenerate the file .htaccess you need:

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by morghy1992** [comment]
ok I regenere the file .htaccess_old 
but I can't disable friendly url it gives me this error 
<img width="569" alt="schermata 2019-02-01 alle 16 30 05" src="https://user-images.githubusercontent.com/47249256/52132112-bfd8e000-263e-11e9-9eea-8c26ecba1217.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, thanks to follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/12026#issuecomment-452633575), it can help you to solve your last issue.
Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith thank you but is not working. 
I just want to solve the problem about the BO that is not working properly everything is moved.
<img width="1440" alt="schermata 2019-02-01 alle 16 57 05" src="https://user-images.githubusercontent.com/47249256/52133890-98841200-2642-11e9-9f50-863027bb5fb7.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, what is the exact version of the 1-click upgrade did you use to do the upgrade?
Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith yes I used 1-click upgrade versione : 4.5.1

**Comment by khouloudbelguith** [comment]
@morghy1992, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in Project_Folder/admin_folder/autoupgrade/tmp/log.txt

**Comment by morghy1992** [comment]
@khouloudbelguith into folder autoupgrade I do not have any tmp/log.txt
See photo
<img width="254" alt="schermata 2019-02-01 alle 17 42 13" src="https://user-images.githubusercontent.com/47249256/52136645-cec49000-2648-11e9-9be1-997cc1d137dc.png">

**Comment by khouloudbelguith** [comment]
@morghy1992, no it is not located into the autoupgarde module folder, but into the /admin_Folder/autoupgrade/tmp/
Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith where can I find admin_folder?Into the public_html?
Because I can't find it

**Comment by khouloudbelguith** [comment]
@morghy1992, no it is the folder admin, is should be displayed on the link when you navigate to your BO, it should be renamed with a custom name.
For example, in my case the link for the dashboard page is `http://prestashoptest.com/admin-dev/index.php?controller=AdminDashboard&token=434b3e2fe1fe439818bb36a411a4251a` => the name of the admin folder in my case is `admin-dev`

**Comment by morghy1992** [comment]
@khouloudbelguith ok I went into it but I do not have any autoupgrade folder I looked everywhere but I can't find it.

**Comment by morghy1992** [comment]
@khouloudbelguith finally I solved the problem of BO now is working fine but I enable my shop and here the error 404. Suggestion? 
<img width="780" alt="schermata 2019-02-01 alle 18 42 35" src="https://user-images.githubusercontent.com/47249256/52139701-2961ea00-2651-11e9-8881-5bbf02e326d9.png">

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Could you please try to regenerate again the file .htaccess you need:

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith thank you for your replay,
it was a problem of the theme. I contacted the developer who fixed for me.

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
