### ISSUE TITLE
Issue on error log vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php

### ISSUE THREAD

**Issue by Partenopeo83** [PrestaShop/PrestaShop#12408]
**Describe the bug**
Hi,
i don't know it's a bug or my module problem but from the upgrade the platform from 1.7.2 to 1.7.4.2 i find an error in my server php_log:

HP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- 
  thrown in /.........../vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 176

Apparently this not cause problems but after a day i have a php_log of 800MB (not good) it's a bug that you know or i have problems with some module?

If is the second option how i can find the module? In debug mode i can't see error apparently all work fine.

Thanks for help

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Partenopeo83,

Did you use the default theme provided by PrestaShop?
Thanks!

**Comment by Partenopeo83** [comment]
No, my theme is custom(very custom) but initially i haven't this error in log.
If i can ask.... when the function _execute in smarty_internal_templatebase.php is called? Maybe the problem start from a module but i can't know what is.

Apparently the log is write when in particular condition(i don't know exactly) the users navigate in listing product or product page but not always .

**Comment by khouloudbelguith** [comment]
@Partenopeo83, this PR: https://github.com/PrestaShop/statsdata/pull/7 could help you to solve the issue? it fixes a [similar issue reported previously](http://forge.prestashop.com/browse/BOOM-4826).
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Partenopeo83,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by telcotronics** [comment]
y cual fue la solucion xq tengo un lista de problemas y este esta primer fila

**Comment by thejoshualewis** [comment]
I'm getting this same issue, using the default theme
`$file_attachement = null;
                   Mail::Send(
                    (int)$email_order->id_lang,
                    'voucher',
                    Mail::l('Order confirmation', (int)$email_order->id_lang),
                    null,
                    $email_customer->email,
                    $email_customer->firstname.' '.$email_customer->lastname,
                    null,
                    null,
                    $file_attachement,
                    null, _PS_MAIL_DIR_, false, (int)$email_order->id_shop
                );`

The values are all valid, but my error logs give me the Missing $template - smarty_internal_templatebase.php on line 177

**Comment by khouloudbelguith** [comment]
@thejoshualewis, an issue created here: https://github.com/PrestaShop/PrestaShop/issues/17856
