### ISSUE TITLE
Search "within the word" is NOK when we search with expression within the word at the position 16

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12407]
**Describe the bug**

In the BO => Shop Parameters => Search page, enable the option "Search within word", With this option enabled, it gives the good result if you search for anything contained in the word.

Try to create a new product with this name "referenceupdatedtoday" > 16 characters.

In the FO, try to search with "today", the product will not be found, also, if you try to search with this "eferenceupdated", it will not be found.
If we try to search with "eferenceupdate" => ok
In fact, the Search within word action is NOK when we use an expression withen the word more than the positon 16.

**To Reproduce**
1. Go to BO => Shop Parameters => Search page
2. Enable the option "Search within word"
3. Create a new product with this name "referenceupdatedtoday"
4. Go to the FO => try to search with "today", the product will not be found, also, if you try to search with this "eferenceupdated", it will not be found.

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0
PHP version:7.1

**Comment by matthieu-rolland** [comment]
I fixed this issue by increasing the maximum search word's length in database and in the code.
This is not ideal, so I created a feature request suggesting a more complete solution:

https://github.com/PrestaShop/PrestaShop/issues/14588
