### ISSUE TITLE
Issue PHP Fatal error: Uncaught --> Smarty: Source: Missing name <--  thrown in /home/gelitaly/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_template_source.php on line 168

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12409]
**Describe the bug**
I upgrade my prestashop to 1.7.5 but I got this problem : PHP Fatal error: Uncaught --> Smarty: Source: Missing name <-- 
thrown in /home/gelitaly/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_template_source.php on line 168 

Now my website is not working the page is blank.
Someone can help me? 

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by cperez75** [comment]
HI! Same here!
Did you find any solutions??

Host: [https://juguetesdeplacer.com](https://juguetesdeplacer.com)
But I have make the rollback to continue working
Prestashop 1.7.5
PHP 7.0
Versión Apache | 2.4.37
Versión PHP | 5.6.30
Versión MySQL | 10.1.37-MariaDB-cll-lve
Arquitectura | x86_64
Sistema operativo | linux

![image](https://user-images.githubusercontent.com/22915403/52916920-83b3a980-32e5-11e9-87f7-b0507e5f5063.png)
![image](https://user-images.githubusercontent.com/22915403/52916937-b65da200-32e5-11e9-9bd9-a7b13ec633a0.png)

**Comment by khouloudbelguith** [comment]
Hi @cperez75,

Have you tried to contact your theme author?
The "appagebuilder" module is provided by your theme?
If yes, thanks to check the issue with the theme author & feedback.

**Comment by cperez75** [comment]
Hi @khouloudbelguith!

Thans for your answer, as you say it is a theme problem, there is not update yet for 1.7.5 so i must wait...

Thanks again!

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by partiid** [comment]
Do you know what exactly was the problem? I have the same problem after migration to the new server.
