### ISSUE TITLE
Prestashop 1.6.1.23 - smart cash javascript - Trojan.Coinminer 6840768

### ISSUE THREAD

**Issue by WS-NL** [PrestaShop/PrestaShop#12419]
Please advise, 

ClamAV from linux keeps detecting these cache js files which are from default bootstrap or any theme as an virus and delete theme. These wil come back everytime these get deleted

If smart java script cache is disabled then it is fine.

Is this a false positive detect?

Txt.Trojan.Coinminer-6840768-0 : /public_html/themes/transformer/cache/v_297_7b48be0abe22e5e449e44687266c76b5.js

**Comment by khouloudbelguith** [comment]
Hi @Def2019,

First of all, thank you for reporting on the PrestaShop project!

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed in the `1.6.1.x` branch.

Thanks for your understanding!

**Comment by PierreRambaud** [comment]
Hey @Def2019, 
Can you send us the link where you download this theme? It looks you download one which include a coin miner malware.
Regards

**Comment by WS-NL** [comment]
> Hey @Def2019,
> Can you send us the link where you download this theme? It looks you download one which include a coin miner malware.
> Regards

Thanks for your reply
We think this is a false positive detection. We dont have a reply from ClamAV yet.
We installed this morning a fresh and clean Prestashop 1.6.1.23 version on a clean fresh installed linux server as well.
Enabled Smart javascript cache in backoffice and as well the mallware get detected in the cache js files

**Comment by PierreRambaud** [comment]
@Def2019 The problem is we don't provide transformer theme with a fresh install. This is something you should have installed. Watch out with this kind of malware :/

**Comment by WS-NL** [comment]
You dont understand, 

This is without a installed theme. just with defualt bootstrap theme what we tested this morning.

**Comment by matks** [comment]
@Def2019 on the clean install, the issue is not detected in `/public_html/themes/` but in another folder / file, right ?

**Comment by PierreRambaud** [comment]
So I don't understand how `public_html/themes/transformer` this directory can be created :/

**Comment by WS-NL** [comment]
> So I don't understand how `public_html/themes/transformer` this directory can be created :/

First post of this topic is from a production server with running prestashop webshops

**Comment by WS-NL** [comment]
> So I don't understand how `public_html/themes/transformer` this directory can be created :/

Yes indeed in /public_html/themes/

/public_html/themes/default-bootstrap/cache/v_1_35425876793946483e9a4ac9f2362d81.js

But still we think these are false positives

**Comment by matks** [comment]
Either that or Bootstrap is really screwed 😄 

Better wait for ClamAV I guess.

**Comment by ron44124** [comment]
I tried to upgrade to 1.6.23 today from 1.6.20 and the ClamAV detected a virus.  Any updates? Thanks.

**Comment by PierreRambaud** [comment]
Can you send us the exact url to this file please?

**Comment by WS-NL** [comment]
It is due to jquery 1.11
it should be updated

http://www.webassist.com/forums/posts.php?id=41843

**Comment by PierreRambaud** [comment]
It a false positive, nothing need to be upgrade :) 
More, we use jquery 2+ on the latest release for the classic theme.

**Comment by ron44124** [comment]
Where would I add the  jquery 2+ to Prestashop 1.6? Thanks.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matks** [comment]
@ron44124 it's not simple. jQuery 1 is used in a lot of pages in PS 1.6. To be able to use jQuery 2 you need to check whether these scripts (the ones from prestashop and the external ones, for example if you use a custom theme it might have JS code too that relies en jQuery 1) are compatible with jQuery 2.
