### ISSUE TITLE
Should var prestashop show all product information?

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#12411]
**Describe the bug**
Looking at the page source I see there is a "var prestashop" that contains among other things the available quantity of a product. That would make it a bit too easy for a bot to scrape exact stock quantities of a store no? What is this var prestashop used for? I do not see it in the source of my 1.5 based shop.

**To Reproduce**
Right click -> View page source

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by matks** [comment]
@johanlantz I think (need to confirm though) this variable is here in order to allow themes and modules developer to access this data, which allows them to provide extended features to prestashop.

**Comment by khouloudbelguith** [comment]
Hi @johanlantz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
