### ISSUE TITLE
Attempted to call an undefined method named "getSimpleCategoriesWithParentInfos" of class "Category".

### ISSUE THREAD

**Issue by criacaosites** [PrestaShop/PrestaShop#12415]
**Describe the bug**

**To Reproduce**
1. Go to 'BACKOFFICE > CATALOG'
2. Click on 'PRODUCTS'
Attempted to call an undefined method named "getSimpleCategoriesWithParentInfos" of class "Category".

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @criacaosites,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1ichkJmSNfg87f-Nf5esUXbZ1I0IsO-b_/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matks** [comment]
Hi @criacaosites the function you talk is here in the code:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/classes/Category.php#L803

Maybe you have an override that removes this function ?

**Comment by criacaosites** [comment]
Tank you Guys, its a override.

**Comment by khouloudbelguith** [comment]
Hi @criacaosites,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
