### ISSUE TITLE
SQL manager order export problem

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#12416]
**Describe the bug**
When we export the orders (with or without filter), the SQL looks not correct for the SQL Manager and gives an error.

**To Reproduce**
-Go to order page and clic on "export to SQL manager"
-validate the SQL request : undefined error "checkedForm"

-if I take the SQL request of my 1.6 shop, I have the strange error "FROM doesn't exist"

A simple request (SELECT SQL_CALC_FOUND_ROWS `reference`FROM `ps_orders`) works perfectly.
<img width="1436" alt="capture d ecran 2019-02-03 a 19 08 12" src="https://user-images.githubusercontent.com/32092528/52180516-87283a80-27e7-11e9-9900-d4b8814634e0.png">
<img width="1444" alt="capture d ecran 2019-02-03 a 19 08 33" src="https://user-images.githubusercontent.com/32092528/52180517-87c0d100-27e7-11e9-9998-4e1fa7552e94.png">

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

This issue is fixed in the PS1.7.6 after the migration the SQL Manager page to Symfony with this PR: https://github.com/PrestaShop/PrestaShop/pull/9206
I attached a video record.
https://drive.google.com/file/d/160oJCB-NRrTzgO5ciXCqgtbC5JALO23q/view
Thanks
