### ISSUE TITLE
Affiliation

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12420]
Prestashop 1.7.5.0
What is the correct use of the affiliation program included in prestashop? That is: I tried to add a user pippo@pluto.com (uri included %pippo123) but although we tried to visit a page with www.test.com/prodottoprova.html?pippo123 the visits are not recorded. I have searched for a long time on the web, but there is very little documentation about it.
Thank you

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

In the Referrers page, there is a help section

> Definitions:

> The "http_referer" field is the website from which your customers arrive.
> For example, visitors coming from Google will have an "http_referer" value like this one: "http://www.google.com/search?q=prestashop".
> If the visitor arrives directly (by typing the URL of your shop, or by using their bookmarks, for example), the http_referer will be empty.
> If you'd like to view all the visitors coming from Google, you can type "%google%" in this field. > Alternatively, you can type "%google.fr%" if you want to view visitors coming from Google France, only.

> The "request_uri" field is the URL from which the customers come to your website.
> For example, if the visitor accesses a product page, the URL will be like this one: "http://prestashop.local/175/ps175/music-ipods/1-ipod-nano.html".
> This is helpful because you can add tags or tokens in the links pointing to your website. For example, you can post a link (such as "http://prestashop.local/175/ps175/index.php?myuniquekeyword" -- note that you added "?myuniquekeyword" at the end of the URL) in an online forum or as a blog comment, and get visitors statistics for that unique link by entering "%myuniquekeyword" in the "request_uri" field. This method is more reliable than the "http_referer" one, but there is one disadvantage: if a search engine references a page with your link, then it will be displayed in the search results and you will not only indicate visitors from the places where you posted the link, but also those from the search engines that picked up that link.

> The "Include" fields indicate what has to be included in the URL.

> The "Exclude" fields indicate what has to be excluded from the URL.

> When using simple mode, you can use a wide variety of generic characters to replace other characters:
"_" will replace one character. If you want to use the real "_", you should type this: "\\_".
"%" will replace any number of characters. If you want to use the real "%", you should type this: "\\%".

>The Simple mode uses the MySQL "LIKE" pattern matching, but for a higher potency you can use MySQL's regular expressions in the Expert mode.

Also, don't forget to install & configure the module 'Data mining for statistics', it must be activated and configurated in order to have all the statistics.
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith https://www.100asa.it/modules/trackingfront/stats.php ==>error 500 with

ContextErrorExceptionNotice: Undefined index: tpl_dir
--
in 9052520951d633beb0b8a51e78d045fca88ac0c9_2.file.login.tpl.php line 33
at content_5c586238f08012_90019627(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in Module.php line 2375
at ModuleCore->display('/var/www/vhosts/100asa.it/httpdocs/modules/trackingfront/trackingfront.php', 'login.tpl')in trackingfront.php line 169
at TrackingFront->displayLogin()in stats.php line 35

**Comment by khouloudbelguith** [comment]
@centoasa, we are of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9780
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/trackingfront/issues/13

**Comment by dialt0n3** [comment]
Is there any plans to actually fix this ? like common ? its been years

**Comment by matks** [comment]
Hi @dialt0n3 I see the repository https://github.com/PrestaShop/trackingfront/ has been archived since 2021 so there will never be a fix I think.

If you need a custom fix of the module, your can contact a professional and hire them to do it. See https://www.prestashop-project.org/support/
