### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when changing order status

### ISSUE THREAD

**Issue by Belyce32** [PrestaShop/PrestaShop#12421]
**Describe the bug**
I create an order in FO. I display it in BO, open it and close without changing anything : OK. But if I change the status, the server seems to have a time out, and few seconds after, I have a page that says CHROME
Cette page ne fonctionne pas
mywebsite.com vous a redirigé à de trop nombreuses reprises.
Essayez de supprimer les cookies..
ERR_TOO_MANY_REDIRECTS

FIREFOX
La page n’est pas redirigée correctement
Une erreur est survenue pendant une connexion à mywebsite.com.
La cause de ce problème peut être la désactivation ou le refus des cookies.

**To Reproduce**
1. create an order in FO, pay by check for example
2. go to BO and display it, change status to paiement accepted
3. Validation
4. error message, different with FF and Chrome.

**Additionnal information**
PrestaShop version: 1.7 or 1.75
certificat ssl
PHP version: 7.2
Hosting : ionos

**Comment by khouloudbelguith** [comment]
Hi @Belyce32,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1yBiYb-M63ydkv3Vpv5AxXnAoHyXLmBl1/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Belyce32,

No, I did not receive your previous comment.
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
@Belyce32, about this error: `Duplicate entry '4' for key 'PRIMARY'<br /><br /><pre>INSERT INTO `omf_packlink_wait_draft` (`id_order`, `date_add`) VALUES ('4', '2019-02-04 10:31:34')</pre>`

The table `omf_packlink_wait_draft` is created by a custom module, what is the exact name of this module?
THanks!

**Comment by Belyce32** [comment]
Module Packlink, use for shipping order

Le 06/02/2019 à 10:12, khouloudbelguith a écrit :

**Comment by Belyce32** [comment]
I placed phppsinfo.php at the root, but when I try to load my page 
https://www.mywebsite.com/phppsinfo.php 
<http://www.example.com/phppsinfo.php>, it asks me an identification. 
Which is it ? BO or FTP ?

Le 06/02/2019 à 10:10, khouloudbelguith a écrit :

**Comment by khouloudbelguith** [comment]
@Belyce32, if you try to enable the mode debug from the BO => Advanced Parameters => Performance page => then you try to change the order status to payment accepted, what is the exact error will be displayed?
It is similar to this error?
![image](https://user-images.githubusercontent.com/16067358/52332737-d941a980-29fb-11e9-895c-b3b714c5dbea.png)
Thanks!

**Comment by Belyce32** [comment]
Of course I tried to enable this mode, but I have absolutly no message 
displayed. It just go like 10 seconds like nothing happens, then firefox 
message about cookies or chrome message about too many redirects

I tried also everything about cookies but this is not the right track.

I isolated the following action : if I change the status to 
"preparation" or "bankwire waiting"; the status is validated, I can 
close and reopen the order. But the moment I chosse "paiement accepted" 
or "shipped", it goes time out with the error page.

Le 06/02/2019 à 10:42, khouloudbelguith a écrit :

**Comment by khouloudbelguith** [comment]
Hi @Belyce32,

Could you please try to disable the Packlink module temporarily, clear cache, check & feedback.
Thanks!

**Comment by Belyce32** [comment]
Wow, you are a star, it is working again !!! Does it mean that my 
packlink pro module is corrupted ?

Le 06/02/2019 à 11:53, khouloudbelguith a écrit :

**Comment by khouloudbelguith** [comment]
Hi @Belyce32,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Belyce32** [comment]
Thank you so much for your precious help !!!!

Le 06/02/2019 à 12:09, khouloudbelguith a écrit :

**Comment by Belyce32** [comment]
Hi khouloudbelguith,

This subject is closed but I need to delete  **my website name** in all posts where it appears. Because this post comes up on google page when searching my company. Or could you do it for me please if I can't do it ?
There is 9 occurrences to delete named om**fil***.com  (* have been replaced, I can't write it one more time.)
Thank you :)

**Comment by Belyce32** [comment]
Hi !!!
Anybody to help me to delete the name of my website in the previous posts ?????
Should I contact an administrator ? Please, can someone answer me ?
