### ISSUE TITLE
I cant enter in store settings, modules, seo etc

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#12434]
I get this on the last stable build

![image](https://user-images.githubusercontent.com/9163980/52273495-557bb480-294a-11e9-8204-4a1a0955c6cf.png)

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight ,

Your shop is disabled, could you please navigate to your BO => Shop Parameters => General page => Maintenace tab, & try to enable the shop.
![image](https://user-images.githubusercontent.com/16067358/52274972-85c55200-294e-11e9-9e3b-54bf8e27df83.png)
Thanks!

**Comment by LinkOfLight** [comment]
Cant it, get this 
![image](https://user-images.githubusercontent.com/9163980/52426246-e5159480-2afd-11e9-814f-10ad02295586.png)

**Comment by khouloudbelguith** [comment]
@LinkOfLight, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by LinkOfLight** [comment]
I Activate the debug mode but dont get the log

**Comment by khouloudbelguith** [comment]
@LinkOfLight, you cannot navigate to your General page?
Or your shop is always disabled?
Thanks!

**Comment by LinkOfLight** [comment]
i cant enter in config and parameters, get security compromised, and i dont know for what is this, i have all permisions en 644 y 755

**Comment by khouloudbelguith** [comment]
@LinkOfLight, could you please try to navigate to your BO => Advanced Parameters => Check your configuration if it is OK?
![image](https://user-images.githubusercontent.com/16067358/52428312-024c6200-2b02-11e9-9d99-426e0be1c1d3.png)

**Comment by LinkOfLight** [comment]
get compromised too

**Comment by khouloudbelguith** [comment]
@LinkOfLight, have you tried to contact your host?
thanks to check with them & feedback.
THanks!

**Comment by LinkOfLight** [comment]
what i need say to mi provider?

**Comment by khouloudbelguith** [comment]
@LinkOfLight, it could be a server issue or permission issue, or other problem on your server.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
