### ISSUE TITLE
[SF Migration] For grid pages, only enable search button when 1 input is not empty

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12439]
Issue to solve:
- https://github.com/PrestaShop/PrestaShop/pull/10839#issuecomment-438985992
- as stated in https://github.com/PrestaShop/PrestaShop/pull/10839#issuecomment-439344886

**Comment by sarjon** [comment]
Isn't it already done? ping @zuk3975

**Comment by zuk3975** [comment]
> Isn't it already done? ping @zuk3975

Yes, I did in #13241.
