### ISSUE TITLE
Upgrade to 1.7.5.0 from 1.6.1.23 SQL issue - max key length is 1000 bytes - encoding

### ISSUE THREAD

**Issue by DavidEschmeyer** [PrestaShop/PrestaShop#12435]
**Describe the bug**
During database upgrade part of 1 click upgrade...

SQL 1.7.5.0 1071 in ALTER TABLE `ps_customer` CHANGE `company` `company` VARCHAR(255), CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes

SQL 1.7.5.0 1071 in ALTER TABLE `ps_employee` CHANGE `firstname` `firstname` VARCHAR(255) NOT NULL, CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL, CHANGE `lastname` `lastname` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes

**To Reproduce**
1) simple way - database and sql command (see photo below).  
long way: i can provide files and database, then run upgrade if you wish to see entire thing. 

Problem is with the data
my environment is mysql 5.7.14
php - 7.0.10

Info on problem:
https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

**Screenshots**
![here2](https://user-images.githubusercontent.com/1899221/52283281-2e17ee00-2930-11e9-973b-7280e2045d55.png)

recreatable with just the sql command on the db... ^^

**Additional information**
PrestaShop version: 1.6.1.23 > 1.7.5.0
PHP version: 7.0.10
mysql 5.7.14

**Comment by khouloudbelguith** [comment]
Hi,

@dave-ps provide me his database & I tried to run this SQL query `ALTER TABLE `ps_customer` CHANGE `company` `company` VARCHAR(255), CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL` & I have the same issue.
ping @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
In the current structure.sql, we can find the following indexes for the table customer:

```
[...]
  PRIMARY KEY (`id_customer`), 
  KEY `customer_email` (`email`), 
  KEY `customer_login` (`email`, `passwd`), 
  KEY `id_customer_passwd` (`id_customer`, `passwd`), 
  KEY `id_gender` (`id_gender`), 
  KEY `id_shop_group` (`id_shop_group`), 
  KEY `id_shop` (`id_shop`, `date_add`)
```

I wonder if indexing the column `passwd` isn't too superfluous.

**Comment by Quetzacoalt91** [comment]
More insights:

* https://www.xaprb.com/blog/2006/04/17/max-key-length-in-mysql/
* https://bugs.mysql.com/bug.php?id=6604

As the column changes are brought on 1.7.5.0, we could handle this issue for 1.7.5.x

**Comment by Quetzacoalt91** [comment]
Even if we don't follow the best practice, it looks like the issue is caused by the database created in utf8mb4, and must be converted to utf8.

**Comment by SharmPRO** [comment]
I did experience the same problem ( max key length ) on database utf8.
Autoupdating PS 1.7.5.2 to 1.7.6.7 for table ps_admin_filter and new index creation including field 'filter_id' VARCHAR(255)
It would be solved with index creation with a length of 170 instead of 255

**Comment by jakub-trzebiatowski** [comment]
Could I ask what are the possible workarounds? I'm trying to upgrade from 1.6.1.24 to 1.7 (1.7.8.0, to be precise, as that's what 1-click upgrade picks) and I'm having the same issue. Would upgrading in multiple steps (for example 1.6.1.24 -> 1.7.4.x -> 1.7.5.x -> ...) help?

**Comment by Prestaworks** [comment]
I changed the tables from myIsam to InnoDB and that fixed the problem for me and those alter tables where executed properly.

**Comment by gericfo** [comment]
Hello,
Version 1.6 is no longer actively supported with the Autoupgrade module ([see this announcement](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)).
However, this behaviour has been clearly identified and will be taken into account in our future developments.
I therefore close this ticket.
Thanks!
