### ISSUE TITLE
Error 500 in production mode

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#12430]
Another issue related to 1.7.5,0 upgrade. Seems most troubled release ever.

PS 1.7.4.2 to 1.7.5.0 using Autoupgrade 4.5.1.
Server configuration set to recommended based on Pierre script.
Upgrade went fine including all modules.
However after the upgrade Performance and Catalog gives 500 error with the following in the log.
The ERROR is generated only if debug mode is off. When debug on everything works fine.

[2019-02-05 08:50:26] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShop\Prest
aShop\Core\Search\SearchParameters::__construct() must be an instance of PrestaShopBundle\Entity\Repository\AdminFilterRepository, instance of Doctrine\ORM\EntityReposi
tory given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/ContainerWtuifgk/getPrestashop_Core_Admin_SearchParametersService.php on line
 8" at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/SearchParameters.php line 50 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\
FatalThrowableError(code: 0): Type error: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Search\\SearchParameters::__construct() must be an instance of PrestaShopBu
ndle\\Entity\\Repository\\AdminFilterRepository, instance of Doctrine\\ORM\\EntityRepository given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/
cache/prod/ContainerWtuifgk/getPrestashop_Core_Admin_SearchParametersService.php on line 8 at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/Sear
chParameters.php:50)"} []

**Comment by joseprr87** [comment]
I have the same problem!

I just finish to upgrade ps 1.7.4 -> 1.7.5.0. How can I fix the problem?
