### ISSUE TITLE
override admin product template 1.7

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#12437]
Hello,

I tried to use this link https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/ to override @PrestaShop/Admin/Product/ProductPage/product.html.twig
I put the file in my (enabled) module in this path modules/mymodule/views/Prestashop/Admin/Product/ProductPage/product.html.twig

but even after deleting the cache, my template file is not used...

I am using prestashop 1.7.4.2, is it supposed to work?

Thank you

**Comment by khouloudbelguith** [comment]
Hi @agnesdennetiere,

I tried with a demo module & I have an exception when I try to edit a product, so the override is used.
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2833131/mymodule.zip)
Thanks to check & feedback.

**Comment by agnesdennetiere** [comment]
Hello,

ok my problem was that my folder was named "Prestashop" and not "PrestaShop" with a capital S

Thank you!

**Comment by khouloudbelguith** [comment]
@agnesdennetiere, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by wfpaisa** [comment]
sorry it doesn't work in 1.7.6.5.
