### ISSUE TITLE
"themes/core.js.map"

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#12452]
**Describe the bug**
After a clean Prestashop 1.7.5 install, I got this 404 error message in the front end (using the inspector).

When I install a theme I bought, I got more errors.

All errors refer to missing files (404) with the .map extension.

**To Reproduce**
1. install Prestashop
2. Go to any page in the font office
3. open webinfo (inspector)

**Screenshots**

<img width="1241" alt="schermafbeelding 2019-02-06 om 11 03 28" src="https://user-images.githubusercontent.com/43880279/52336142-6688fc00-2a04-11e9-83b9-d9e0e4dfb077.png">

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Ybeske** [comment]
> Hi @Ybeske,
> 
> Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * host
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> * screenshots
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

I accidentally already posted my message without describing the bug. I edited the original message.

**Comment by Ybeske** [comment]
The most important question I have right now: Is it a big problem and could it be the cause of some css failure (some elements are not hidden while they need to be... etc...) in the checkout page (in this example).

**Comment by khouloudbelguith** [comment]
@Ybeske, have you tried to contact the module author about this issue?
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by Ybeske** [comment]
After a clean PS install (without the extra theme installed) I got one error from a certain type.

**Comment by Ybeske** [comment]
This is the situation after a clean install:

<img width="1692" alt="schermafbeelding 2019-02-06 om 12 10 49" src="https://user-images.githubusercontent.com/43880279/52337583-507d3a80-2a08-11e9-8053-d89373719737.png">

**Comment by Ybeske** [comment]
To clarify my note -> This screenshot describes the situation after a clean PS1.7.0 install:

<img width="1692" alt="schermafbeelding 2019-02-06 om 12 10 49" src="https://user-images.githubusercontent.com/43880279/52337723-b2d63b00-2a08-11e9-8586-c33bcb81a47d.png">

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0  when friendly URL is disabled. (only reproduced with 2 shops)
![image](https://user-images.githubusercontent.com/16067358/52341864-10bc5000-2a14-11e9-9a2e-0969a7a67d07.png)
Tested with another PS1.7.5.0 => OK
Tested with machine-shuffle => OK
@marionf did you manage to reproduce the issue?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith I can't reproduce with a fresh 1.7.5.0

![capture d ecran_984](https://user-images.githubusercontent.com/13449658/52343332-13b93f80-2a18-11e9-9d5e-d12756e25fbf.png)

**Comment by Ybeske** [comment]
Strange: When I visit the website with Firefox (instead of Safari), I only got these 2 errors:
I suppose the other "less important" errors are not shown in Firefox and occurs based on the [root]/theme/core.js...

I don't understand the call of the .map extension. This file doesn't exist.
Where/by who is it called?

<img width="1093" alt="schermafbeelding 2019-02-06 om 15 08 06" src="https://user-images.githubusercontent.com/43880279/52347483-55e77e80-2a22-11e9-92b8-97df2e5de47f.png">

**Comment by khouloudbelguith** [comment]
@Ybeske, try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to regenerate the file .htaccess

* Rename the old file to .htaccess_old
* Disable friendly URL
* Enable friendly URL

Thanks to check and feedback.

**Comment by mateuszstompor** [comment]
I followed steps which @khouloudbelguith provided but it didn't help at all. Issue still exists. Prestashop 1.7.5.0, default theme.

Edit:
One important note, it only affects Safari browser

**Comment by khouloudbelguith** [comment]
@mateuszstompor, what is the exact version PHP did you use? could you please provide us your server setup and configuration
Thanks!

**Comment by mateuszstompor** [comment]
I am using php 5.6 with extensions. I attached a file containing list of all I use.
<img width="1346" alt="php-version extension" src="https://user-images.githubusercontent.com/24464340/53102811-bb606280-352c-11e9-93cc-495d5ad945dc.png">
Screenshot with error:
<img width="1680" alt="js-error" src="https://user-images.githubusercontent.com/24464340/53102985-0a0dfc80-352d-11e9-8955-f1287967d8d1.png">
host: https://oprawydladomu.pl
I have checked all log files which I have on the cms I use and it does not show any kind of errors for this domain

**Comment by khouloudbelguith** [comment]
Hi @mateuszstompor,

In my case, the issue doesn't exist anymore.
I tried with PS1.7.5.0
![image](https://user-images.githubusercontent.com/16067358/53109478-40ea0f80-3539-11e9-95c2-9af83eccf276.png)
![image](https://user-images.githubusercontent.com/16067358/53109500-4fd0c200-3539-11e9-88f9-a0b9b32ebb74.png)
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by mariusherea** [comment]
Same problem, in Safari only

**Comment by mateuszstompor** [comment]
@mariusherea in my case the problem disappeared when I upgraded php version to 7.1

**Comment by mariusherea** [comment]
> @mariusherea in my case the problem disappeared when I upgraded php version to 7.1

I am using php 7.3. To fix the problem, I created empty  .map files and now Safari stopped complaining about it.

**Comment by khouloudbelguith** [comment]
Hi @mariusherea,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks!

**Comment by mariusherea** [comment]
Hello @khouloudbelguith,
That's.... good to know :) Thank you.

**Comment by Macrisu** [comment]
Prestashop 1.7.6.4
PHP 7.2

I get the same error ONLY when I disable CCC and cache from Performance

`DevTools failed to load SourceMap: Could not parse content for http://www.xxxx.com/themes/core.js.map: Unexpected end of JSON input`

**Comment by przemko2000** [comment]
I have exactly the same error: DevTools failed to parse SourceMap: https://>>MY SITE<</themes/core.js.map
It is present on all pages.

Presta 1.7.6.3
PHP 7.2

What should I do?

**Comment by Macrisu** [comment]
Disable Debugging from Advanced Parameters - Performance

**Comment by przemko2000** [comment]
It is disabled

**Comment by Macrisu** [comment]
I use 17.6.5 (released today) and no problem.
Clear cache & update

**Comment by przemko2000** [comment]
OK. I upgraded to 1.7.6.5 and the error sounds a bit more detailed, but it is still there:
DevTools failed to load SourceMap: Could not load content for https://>>MY SITE<</themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by rodrideveloper** [comment]
@przemko2000 I have the same error :/

**Comment by giladze** [comment]
have the same error

**Comment by Alcpaone** [comment]
PS 1.7.6.5 / PHP 7.2 same error

**Comment by xmovu** [comment]
Same error here, PHP 7.2.30, Prestashop version 7.6.4

**Comment by xmovu** [comment]
Edit: upgeaded to 7.6.5, same issue.

**Comment by 01park** [comment]
Also, we have this 

Can this issue btw cause everything from loading slow?

**Comment by xmovu** [comment]
I had to recover a backup basically, it was the only way to get it sorted.

**Comment by 01park** [comment]
Can you describe your problem. In my case it's just become very slow and won't load. I wanted to back up, now my DB is corrupted also with JSON problem. 

Do you know what files need to be restored ( manually) for this?

**Comment by xmovu** [comment]
> Can you describe your problem. In my case it's just become very slow and won't load. I wanted to back up, now my DB is corrupted also with JSON problem.
> 
> Do you know what files need to be restored ( manually) for this?

I restored the whole thing.

core.js.map was missing.

**Comment by 01park** [comment]
Hi,

Sorry, but from where did you get the missing file and in what folder exactly to I need to place it.

**Comment by xmovu** [comment]
Hello,

The file still doesn't exist but it doesn't complain about it and works fine.

**Comment by eternoendless** [comment]
Source maps (`.map` files) are only useful for development/debugging. They help map compressed files to their original source code. They are only used by the development toolbar so their presence or not should have no impact on your shop's performance.

**Comment by eternoendless** [comment]
This issue has been closed because we haven't been able to reproduce it on a clean shop. If you find a way to reproduce it on a clean shop, please open a new issue.

**Comment by thbl** [comment]
i have the same issue

**Comment by thbl** [comment]
php 7.2 prestashop 1.7.6.5
@khouloudbelguith @eternoendless could you look more into this ?

**Comment by xmovu** [comment]
Damn, this just happened again, nothing was changed. Just stopped working.

**Comment by gpsaliola** [comment]
I've the same problem with Prestashop 1.7.6.5 and PHP 7.3.
I think this may be a penality for SEO.

**Comment by Bess112** [comment]
Did I found the solution?:

I did this and the fault is gone:
**PS-Background->advanced settings->Performance->Smart Cache for JavaScript->YES**

_It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

**Comment by matks** [comment]
> I've the same problem with Prestashop 1.7.6.5 and PHP 7.3.
> I think this may be a penality for SEO.

Note: PS 1.7.6.5 is not fully compliant with php7.3 you should use php7.2

> _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

All of us are noobs in one field or another 😄

**Comment by gpsaliola** [comment]
> Did I found the solution?:
> 
> I did this and the fault is gone:
> **PS-Background->advanced settings->Performance->Smart Cache for JavaScript->YES**
> 
> _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

Hello, thank you but this doesn't solve the problem (I've also tried to set Multi-front optimization to YES).

**Comment by gpsaliola** [comment]
> > I've the same problem with Prestashop 1.7.6.5 and PHP 7.3.
> > I think this may be a penality for SEO.
> 
> Note: PS 1.7.6.5 is not fully compliant with php7.3 you should use php7.2
> 
> > _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._
> 
> All of us are noobs in one field or another 😄

Hello thank you, I've set the right PHP version but this doesn't solve the problem.

**Comment by Bartozo** [comment]
> Did I found the solution?:
> 
> I did this and the fault is gone:
> **PS-Background->advanced settings->Performance->Smart Cache for JavaScript->YES**
> 
> _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

This fixed my problem. I tested it on safari and chrome.

**Comment by phausca** [comment]
In  my case I think it all started the day that I tried enabling the Smart Cache for CSS.
The CSS became terrible and I had to disable it again.
It looks like it created a css.map file per each css file in the theme and now it is still looking for these files....even they don't exist anymore..

DevTools failed to load SourceMap: Could not load content for. https://xxxxx/themes/leo_bread/modules/leobootstrapmenu/views/css/megamenu.css.map:

**Comment by TamasFelix** [comment]
Hello, i have the same issue
DevTools failed to load SourceMap: Could not load content for /modules/revws/views/js/front-1_1_0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for /themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[https://www.kiwigym.ro/sanatate-incheieturi/universal-nutrition-animal-flex-44plicuri](https://www.kiwigym.ro/sanatate-incheieturi/universal-nutrition-animal-flex-44plicuri)

![similar-kiwigym-min](https://user-images.githubusercontent.com/50567469/99867652-da899980-2bc3-11eb-83a3-880ac366c608.jpg)

Did I found the solution? Thanks

**Comment by theGera** [comment]
this is not an error, it is merely development and design ... with webpack we can disable it when compiled ...

> sourceMap: false,

actually it would be easier for us to delete it manually ...

-backupfile
open the themes/core.js file and delete the last line ...

![image](https://user-images.githubusercontent.com/47211666/105622757-9f7d2f80-5dd9-11eb-9189-8607623699d8.png)

There are also templates in the css and js that bring the map ...
It is only to erase the last line...

clear cache of yor computer
clear cache prestashop

and ok

**Comment by glowstore** [comment]
Hi, I have the same problem and I can't deal with it. 
My shop has stopped allowing "add to cart" on the product page. 
It works on the home page. 
After entering the product, the website does not work as a person.
The error that shows up on the debug is the same.

**Comment by aghaeian** [comment]
> Did I found the solution?:
> 
> I did this and the fault is gone: **PS-Background->advanced settings->Performance->Smart Cache for JavaScript->YES**
> 
> _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

you are a true hero

> Did I found the solution?:
> 
> I did this and the fault is gone: **PS-Background->advanced settings->Performance->Smart Cache for JavaScript->YES**
> 
> _It's funny nobody think about this in 1.5 years.. Just to be clear I am the biggest noob you will find within prestashop experience.._

you are a true hero @Bess112 . 

issue is fixed.
