### ISSUE TITLE
Errors after placing order in 1.6.1.23

### ISSUE THREAD

**Issue by paintspec** [PrestaShop/PrestaShop#12457]
After customers place an order on my webshop the order comes in, but doesnt give the right status. Customers doesnt become a confirmation(payment done by mollie). I have to mannual update the order.

In log i get the following error:

[Wed Feb 06 13:54:37.897850 2019] [proxy_fcgi:error] [pid 491791:tid 139869342516992] [client xxxxxxxxxx:55118] AH01071: Got error 'PHP message: PHP Warning:  Declaration of Tools::file_get_contents($url, $use_include_path = false, $stream_context = NULL, $curl_timeout = 5) should be compatible with ToolsCore::file_get_contents($url, $use_include_path = false, $stream_context = NULL, $curl_timeout = 5, $fallback = false) in /home/xxxxx/domains/xxxxxxxxxx/public_html/override/classes/Tools.php on line 0\n', referer: https://xxxxxx.nl/adminxxx/index.php?controller=AdminDashboard&token=xxxxxxxxxxxxxxx

I also became orders who didnt show the products in backoffice. To see what people had ordered i went to the cart section to see what was in cart. There it shows what they ordered. see images
![111](https://user-images.githubusercontent.com/30367310/52343324-0a2fd780-2a18-11e9-9c4d-af9d7cf27f3e.jpg)
![112](https://user-images.githubusercontent.com/30367310/52343325-0a2fd780-2a18-11e9-894c-de09b901fbc5.jpg)

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @paintspec,

You have an override of the class Tools.php, it is displayed in your error.
`/home/simon/domains/paintspectrum.nl/public_html/override/classes/Tools.php on line 0\n', referer: https://paintspectrum.nl/adminxxx/index.php?controller=AdminDashboard&token=ac447ca3e45fc1a11680bfab950787f9`
It could be a problem.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

**Comment by paintspec** [comment]
ahaa well i will not go over to 1.7 as that gives more and more issues. Maybe time to switch

**Comment by paintspec** [comment]
to another platform, so thumbs up is a bit weird

**Comment by khouloudbelguith** [comment]
@paintspec, as I described in my last comment, you have an override of the class Tools.php, it could be the problem.
Thanks!
