### ISSUE TITLE
Glitch: onboarding popup on safari browser

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#12454]
On safari
We have this kind of graphical glitch:
![image](https://user-images.githubusercontent.com/29543279/52064799-9d2ec480-2575-11e9-879e-653253c9692e.png)

_Originally posted by @mbadrani in https://github.com/PrestaShop/PrestaShop/pull/12354#issuecomment-459387200_

**Comment by marionf** [comment]
@mbadrani why waiting for PM ?
What is your Safari version ?
What is your screen size ?
Do you have the same issue on 1.7.5.0, 1.7.4.4 ?

**Comment by khouloudbelguith** [comment]
Hi,

I tried with fresh installation 1.7.5.x & Safari browser v11 & it is OK.
![image](https://user-images.githubusercontent.com/16067358/52343083-6fcf9400-2a17-11e9-8e07-172df5d2be19.png)
Thanks!

**Comment by marionf** [comment]
@mbadrani any news ?

**Comment by mbadrani** [comment]
yes reproducible on Safari Mavericks 7.1

**Comment by mbadrani** [comment]
Screen size: full screen
Version tested: only 1.7.5.x

**Comment by khouloudbelguith** [comment]
@marionf, I have the same issue with PS1.7.5.1 with:

- os_version=Mavericks
- browser=Safari
- browser_version=7.1

![image](https://user-images.githubusercontent.com/16067358/52800427-05080380-307c-11e9-8709-cd6861b7bef8.png)
Thanks!

**Comment by marionf** [comment]
Thank you @khouloudbelguith 
Could you try on 1.7.4.4 & 1.7.5.0 to know if it's a regression or not ?
7.1, is it the last version of Safari ?

**Comment by khouloudbelguith** [comment]
@marionf, yes with PS1.7.5.0, same issue.
![image](https://user-images.githubusercontent.com/16067358/52801309-e1de5380-307d-11e9-8752-4046b5580e71.png)

But with 1.7.4.4, click on the resume button doesn' work
![image](https://user-images.githubusercontent.com/16067358/52801253-c5421b80-307d-11e9-9809-a29b183342dd.png)
Thanks!

**Comment by mbadrani** [comment]
You rock @khouloudbelguith !

**Comment by marionf** [comment]
@khouloudbelguith buttons are centered with 1.7.4.4 ?

**Comment by khouloudbelguith** [comment]
@marionf,
About Safari, the last version is 12.0.2, but it is compatible only with the operating system Mac OS High Sierra.
with PS1.7.4.4 fresh install same issue.
![image](https://user-images.githubusercontent.com/16067358/52802665-aee98f00-3080-11e9-9570-b468827dafae.png)

Thanks!

**Comment by marionf** [comment]
Thank you very much @khouloudbelguith :+1:

**Comment by hibatallahAouadni** [comment]
Hi,

I managed to reproduce this issue with PS1.7.7.0_rc.1+build.3.
I used:
- os_version=Mavericks
- browser=Safari
- browser_version=7.1

![image](https://user-images.githubusercontent.com/23308427/97454258-d789e900-1936-11eb-80f4-f3921529a98e.png)

Thanks!

**Comment by NeOMakinG** [comment]
As we use bootstrap, we support last stable release of every browsers.

Safari 7.1 is used by 0.02% of the population, this is almost like wanting to support IE10...

Closing this

Thanks for the report anyway
