### ISSUE TITLE
/module/ps_wirepayment/validation

### ISSUE THREAD

**Issue by ClaudioSagaris** [PrestaShop/PrestaShop#12466]
Prestashop 1.7.5 Complet New
www.supreme-shop-schweiz.ch
Create a new Account
Create an new Order

[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] PHP Fatal error:  Uncaught Swift_RfcComplianceException: Address in mailbox given [info@] does not comply with RFC 2822, 3.6.2. in /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:345, referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] Stack trace:, referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] #0 /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(261): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('info@'), referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] #1 /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array), referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] #2 /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array), referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] #3 /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array), referer: http://supreme-shop-schweiz.ch/de/Bestellung
[Wed Feb 06 16:31:27 2019] [error] [client 46.140.9.106] #4 /home/www/web455/html/ne in /home/www/web455/html/new.supreme-shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 345, referer: http://supreme-shop-schweiz.ch/de/Bestellung

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ClaudioSagaris,

Did you use the ps_emailalerts module?
if no, the intl extension should be installed on your server, thanks to check& feedback.
Thanks!

**Comment by ClaudioSagaris** [comment]
Thank you... can you explain that to me exactly?
    	
    	

    	Mobile Mail Claudio Vagnoni Supreme Shop Schweiz 🇨🇭 
    
  




On Wed, Feb 6, 2019 at 5:11 PM +0100, "khouloudbelguith" <notifications@github.com> wrote:












Hi @ClaudioSagaris,


Did you use the ps_emailalerts module?

if no, the intl extension should be installed on your server, thanks to check& feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
@ClaudioSagaris, it could be a probelm fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/11995/files

Or, in your BO => Modules => Module Manager => you can search for the `Mail alerts ` module, if it is installed, your problem could be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/9638 => not fixed yet.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @ClaudioSagaris,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
