### ISSUE TITLE
Problem with the Product Attributes change it and revert to default variation P.S. 1.7.5

### ISSUE THREAD

**Issue by nziria** [PrestaShop/PrestaShop#12468]
when create a product with variations.
in FO i select a variation and the page semi-refresh and the variation revert back to default.
seems to be a know issue, and tried different method like modify seo and url etc...

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0 (also tried 7.2)

**Comment by khouloudbelguith** [comment]
Hi @nziria,

Have you the same issue with this ticket: #9667?
Thanks!

**Comment by nziria** [comment]
similar, but i have no stock, i disabled it in preference products.

**Comment by khouloudbelguith** [comment]
@nziria, the "Display unavailable product attributes on the product page" option is disabled in your case?
Thanks!

**Comment by nziria** [comment]
is enabled.
![enabled](https://user-images.githubusercontent.com/33318379/52406228-7f111900-2acd-11e9-814f-46e126250eb9.png)

**Comment by khouloudbelguith** [comment]
@nziria, I tried with PS1.7.5.0 (Friendly URL enabled & disabled) with your configuration
![image](https://user-images.githubusercontent.com/16067358/52409607-475a9f00-2ad6-11e9-9cb5-c4744f5661a0.png)
But, I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1zaJG9Gq3DSvDzZlE7pF_K6kuusq_QhCj/view
Thanks to check & feedback.

**Comment by nziria** [comment]
anyone have this problem? @khouloudbelguith what version of php you have?

**Comment by khouloudbelguith** [comment]
@nziria, tried with PHP7.0.33 & PHP 7.2.10.
Thanks!

**Comment by nziria** [comment]
anyway i can't resolve this problem. i'm so sad, after that i resolved the coupon code on virtual product i don't understand this type of problem, maybe it's a hosting problem.

**Comment by khouloudbelguith** [comment]
Hi @nziria,

The only issue which I can reproduce is reported in this ticket: #9667
But it is not your case.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by nziria** [comment]
@khouloudbelguith can you access to my site for verify?

**Comment by khouloudbelguith** [comment]
Hi @nziria,

This is a public space.
You can provide me your link by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by nziria** [comment]
Resolved,
my file: product.tpl was edited, replaced with default tpl and it simply work
