### ISSUE TITLE
Enter keypress disabled on admin product form

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#12463]
Hello,

I have added a textarea field on the product form in the backoffice, but I realised that the "enter" key was disabled in javascript, so it is not possible to insert a line break (other than with copy paste...).
I checked everywhere to override this but I cannot find where in the code it is done.
Could you please help me?

**Additionnal information**
PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @agnesdennetiere,

Could you please try with "Shift" + "Enter" & feedback.
Thanks!

**Comment by agnesdennetiere** [comment]
Shift+Enter is indeed working

**Comment by khouloudbelguith** [comment]
@agnesdennetiere, so could this help you to solve your issue?
Thanks!

**Comment by agnesdennetiere** [comment]
I will make it work with my customer
thank you !

**Comment by khouloudbelguith** [comment]
@agnesdennetiere, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
