### ISSUE TITLE
error in update product though webservice

### ISSUE THREAD

**Issue by fantonifra** [PrestaShop/PrestaShop#12464]
Hi,
using Prestashop after I upgrade MySql from 5.5 to 8.0.13 and Php from 5.6 to 7.0 (7.1 or 7.2) I got an error updating a product through webservice api.

I investigated deeply and I found this error in prestahop log:
_ERROR v1.7.2.4	2019/01/30 - 16:41:18: Link to database cannot be established:SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers at line 102 in file classes/db/DbPDO.php_

in DbPdo.php the exception is raised here:
`public function connect() { try { $this->link = $this->_getPDO($this->server, $this->user, $this->password, $this->database, 5); } catch (PDOException $e) { throw new PrestaShopException('Link to database cannot be established:'.$e->getMessage()); }`

It seems this issue is related to the utf8 support; we found several post in internet about this but no one help us to fix it. We tried also to use old versione of php but without result.
Do you have any suggestions?

PrestaShop version: 1.7.2
PHP version: 7.1.19
MySql version: 8.0.13

**Comment by khouloudbelguith** [comment]
Hi @fantonifra,

The problem comes from your web host. 
Your issue is not related to PrestaShop => it is an error on your server.

Try to connect to your MySQL server in command line if you can, `mysql -u MYSQL_USER -p DATABASE_NAME -h DATABASE_HOST` try to connect by replacing values.

Thanks to check & feedback.

**Comment by fantonifra** [comment]
Hi [@khouloudbelguith](/khouloudbelguith),
thanks for your reply. Prestashop is in a our virtual machine, so we have complete access to the host.
All worked fine until we migrated mysql to 8.0.13 version and php to 7.0. Now we cannot go back because we are in production.  All works fine except webservice update: we can read data from api but we cannot update any product due to the error above

**Comment by matks** [comment]
Hi @fantonifra, when using PS in our docker image, this is how we fix it: https://github.com/PrestaShop/docker#during-the-installation-prestashop-cannot-connect-to-mysql---bad-charset

Hope it helps

**Comment by fantonifra** [comment]
Thanks @matks , it works now!
but to force utf8 instead utf8mb4 could give me some trouble, in your opinion?

**Comment by matks** [comment]
@fantonifra Yes, this is something you probably want to monitor although I do not know exactly what can be the consequences (we could use a database expert help here). 

I know some special chars cannot be handled by mysql utf8 mode (and utf8mb4 solves it), like chinese characters for example. But there might be bigger issues.

**Comment by khouloudbelguith** [comment]
@fantonifra, can I close the issue?
Thanks!

**Comment by fantonifra** [comment]
Yes, thanks @matks and @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@fantonifra, you are welcome!
Feel free to open a new one when needed.
Thanks!
