### ISSUE TITLE
Insert tracking number in mail template

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#12472]
Would be nice to have {shipping_number} in email templates.
So customers can get a follow up email
 "your order is sent. Your tracking number is: XXXXXXXX"

**Comment by khouloudbelguith** [comment]
Hi @thbl,

In the order BO, when we try to edit the tracking number
![image](https://user-images.githubusercontent.com/16067358/52398766-7236fa00-2aba-11e9-977e-b7841958add2.png)
The customer will receive a mail "Package in transit" that contains the tracking number
![image](https://user-images.githubusercontent.com/16067358/52398811-9b578a80-2aba-11e9-9daf-6ddb683293a7.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @thbl,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by thbl** [comment]
This email wont be sent if you update the tracking no. over webservice ?

**Comment by khouloudbelguith** [comment]
@thbl, issue created here: #13912

**Comment by thbl** [comment]
@khouloudbelguith  Thanks
