### ISSUE TITLE
Unknown column 'location' in 'field list' 

### ISSUE THREAD

**Issue by elcolibri** [PrestaShop/PrestaShop#12474]
**Describe the bug**
Update my store from 1.7.4.2 to 1.7.5 and I have this problem with the Stock of the products in a new product I can not put the Quantity and when putting in Debug mode it does not let me create product and inside the store when wanting to see a product appears these.

SELECT location
FROM `pse0_stock_available`
WHERE (id_product = 218) AND (id_product_attribute = 0) AND (id_shop = 1) AND (id_shop_group = 0) LIMIT 1

at line 769 in file classes/db/Db.php
764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }

**To Reproduce**
1. Go to product
2. Unknown column 'location' in 'field list'
3. 3\. Enable debug mode

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![error](https://user-images.githubusercontent.com/10228695/52386049-d4a3e200-2a49-11e9-8772-c4869937a22f.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment]
Hi @elcolibri,

It could be like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.

Can you please check if you have missing columns on your database schema.
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/upgrade/sql/1.7.5.0.sql

You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql

Thanks!

**Comment by elcolibri** [comment]
hello thank you for your answer but I can not solve and I was reviewing all the tables and if they are all correct but the error follows and when I upload again the file 1.7.5.0.sql tells me this error at the end

Error
SQL query:


ALTER TABLE `PREFIX_cms_lang`
   ADD `head_seo_title` varchar (255) DEFAULT NULL AFTER` meta_title`,
   CHANGE `meta_title`` meta_title` VARCHAR (255) NOT NULL,
   CHANGE `meta_description`` meta_description` VARCHAR (512) DEFAULT NULL
MySQL said: Documentation

# 1146 - Table 'bettzvnd_pres991.PREFIX_cms_lang' does not exist

**is in Debug mode the site if you want to see as it says**
https://better-buy.store/en/home/71-gold-plated-bitcoin-coin-collectible-gift-btc-coin-art-collection-physical-en-32854531776.html

**I do not know if I finish all the products can be solved although I do not believe because when creating a new product it does not let me put the amount of the stock**

**Comment by khouloudbelguith** [comment]
@elcolibri, the table PREFIX_cms_lang doesn't exist in your database, you need to create it.

```
CREATE TABLE `PREFIX_cms_lang` (
  `id_cms` int(10) unsigned NOT NULL, 
  `id_lang` int(10) unsigned NOT NULL, 
  `id_shop` int(10) unsigned NOT NULL DEFAULT '1', 
  `meta_title` varchar(255) NOT NULL, 
  `head_seo_title` varchar(255) DEFAULT NULL, 
  `meta_description` varchar(512) DEFAULT NULL, 
  `meta_keywords` varchar(255) DEFAULT NULL, 
  `content` longtext, 
  `link_rewrite` varchar(128) NOT NULL, 
  PRIMARY KEY (`id_cms`, `id_shop`, `id_lang`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8 COLLATION;
```
You can follow this link: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql#L403

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @elcolibri,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Prem-lmx** [comment]
Hai the same issue ,
plesase help me,

**Comment by khouloudbelguith** [comment]
@elcolibri, It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.5.2 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

It could be that the field location is missing in the table "ps_stock_available"
![image](https://user-images.githubusercontent.com/16067358/63426260-4d78f300-c40a-11e9-9e26-677426cb39ea.png)

Thanks!

**Comment by Prem-lmx** [comment]
which column?

**Comment by Prem-lmx** [comment]
Thank you for your mail
im already add the location field..
[image: image.png]
Thanks
