### ISSUE TITLE
Problem with popups

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12476]
**Describe the bug**
Popups are not correctly displayed

**To Reproduce**
1. Go to a migrated page
2. Click on a tooltip
3. The tooltip popup isn't correctly placed

**Screenshots**
![capture d ecran_987](https://user-images.githubusercontent.com/13449658/52400790-69492700-2ac0-11e9-8618-06a894f84088.png)

Another way to reproduce the issue:
https://drive.google.com/file/d/1e6pvuGuX4pEiCAkNYBRd9rSnhoL37JUk/view?usp=sharing

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/12333?
Thanks!

**Comment by marionf** [comment]
Thank you @khouloudbelguith !

**Comment by khouloudbelguith** [comment]
Duplicate of #12333
