### ISSUE TITLE
Many erros when switch mode dev in the backoffice

### ISSUE THREAD

**Issue by lewis2413** [PrestaShop/PrestaShop#12470]
Hi,

I´m trying to access to backoffice in dev mode but it showing me this errors:

![image](https://user-images.githubusercontent.com/47395448/52360322-044bed80-2a3c-11e9-8745-3b1d9b118dc2.png)

and i don´t know how to solve it.

thanks advance.

**Comment by khouloudbelguith** [comment]
Hi @lewis2413,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by lewis2413** [comment]
Hi [khouloudbelguith],

I was checking some settings in **var/cache directory**, i was have 2 folders, one dev folder and other prod folder, that i did was to comment the dev folder and refresh the Back Office.

**Comment by khouloudbelguith** [comment]
Hi @lewis2413,

those folders are cache, you can clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by lewis2413** [comment]
Hi @khouloudbelguith 

thanks for your information,  now, I have another problem, can I use the same ticket?

**Comment by khouloudbelguith** [comment]
@lewis2413, if it is a different issue, yes, you need to open a new one with more information about your configuration.
About the issue, it is fixed? can I close the issue?
Thanks!

**Comment by lewis2413** [comment]
Yes close it....

**Comment by khouloudbelguith** [comment]
@lewis2413, feel free to open a new one when needed.
Thanks!
