### ISSUE TITLE
Duplicate content on ebay

### ISSUE THREAD

**Issue by bluebear13005** [PrestaShop/PrestaShop#12489]
**Describe the bug**
Some of my product are duplicate on my ebay account. I use the addons eBay v2.0.5 - by 202-ecommerce. When I call the addon support they say that it's a problem from ebay and when I contact ebay they say that it's a problem directly from prestashop. Anyone have an idear ?

Thanks for your help.

Clément

**To Reproduce**

**Screenshots**
https://snag.gy/ZYuO42.jpg 

**Additionnal information**
PrestaShop version: 1.6
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @bluebear13005,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks!

**Comment by bluebear13005** [comment]
I did contact the addon author and they say it's not their doing. Also the support from ebay say that it is a prestashop issue...
