### ISSUE TITLE
Tax included when customer has country with no tax

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#12508]
**Describe the bug**
When customer has group with tax = 0, Tax included in product after order.

**To Reproduce**
1. Go to Internationals > Vat
2. Create a VAT with rate = 0%; give name NOVAT
3. Create Tax Rule, give a name, add a country and in behaviour select "This vat only" and in Tax select NOVAT
4. Go to Shop Parameters > Customer Settings
5. Click on Groups
6 . Create a Group GROUP_NOIVA 
7 . Select in Price display method, VAT Excluded
8. Create a customer
9. in address select as country the country of point 3
10. select add group  GROUP_NOIVA
12. create a product with vat
13. create a order 
14. in checkout the customer doesn't see VAT --> correct
15. complete checkout and create the order
16. in backoffice the product has applied the VAT
**Screenshots**
![download 1](https://user-images.githubusercontent.com/186556/52473009-0c6b7080-2b95-11e9-92f1-70d3ab7c0eab.png)
![download](https://user-images.githubusercontent.com/186556/52473014-0ecdca80-2b95-11e9-9b75-1ac8d5c655f4.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @luigimassa,

With these steps (1, 2, 3) you just created a tax rule applied in one country, then you have created a product with vat => so you used a different tax rule than the `NOVAT` tax rule created previously.
So, it will not be applied.
As I understand your issue, you can use the European VAT number module, it enables you to enter the intra-community VAT number when creating the address, with this module prices should be displayed tax excluded on the product page, on the cart and paid without tax for the country selected.
This module is not released yet for the PS1.7
You can follow this link https://github.com/PrestaShop/vatnumber
Also, we have an issue with this module reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9928
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @luigimassa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by matteolavaggi** [comment]
You think is time for PS 1.7 to get a EU VAT module? Now we are on ps 1.7.6 and still nos upport for the module? Thanks

**Comment by khouloudbelguith** [comment]
@matteolavaggi, here's an issue about the European VAT number, it is added to our bug roadmap
https://github.com/PrestaShop/PrestaShop/issues/9884
Thanks!

**Comment by matteolavaggi** [comment]
Please can you point me in the right way to handle today different vat based on different country? 
A standard shop create all the products with a single vat rate (example IT 22%), now how we can do to right configure tax rates for different country, example for USA where we need to apply 0%? Add new rate 0% and create the aliquote under our "IT 22%" and manual do this step for every country in the world?

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Could you please navigate to your BO => International => Taxes => Tax Rules Tab, you can find the EU VAT For Virtual Products, Try t edit it, you will discover, that it has different taxes for different countries
![image](https://user-images.githubusercontent.com/16067358/57081409-e9b0aa00-6cf4-11e9-9125-220a0691b09c.png)
For each tax rule, you can edit the tax for each country.
Thanks!

**Comment by Maofree** [comment]
Hi @khouloudbelguith 
why is it not corrected? I see that the last change dates back to 10 months ago. I believe that selling to companies in the EU is now a standard thing, why is it not corrected and placed among the defaults like in version 1.6?
if some company buy from an EU country the order include the taxes so now with the electronic invoice is a big problem
can you give more priority to this request?
thanks

this is an example from italian shop to a france customer with vat number

![1](https://user-images.githubusercontent.com/653230/69383403-d3326600-0cb9-11ea-9b1a-e6510f98bf2a.png)
![2](https://user-images.githubusercontent.com/653230/69383404-d3326600-0cb9-11ea-955d-a8db4646f18d.png)

**Comment by Maofree** [comment]
I tested the module and it works well
I don't need the vat check
however it should be set in the default module like on the 1.6
bye
