### ISSUE TITLE
ContextErrorException Warning: session_start()

### ISSUE THREAD

**Issue by Styxm** [PrestaShop/PrestaShop#12513]
Hello, today I turned my on my debugging from prestashop to see why one of my module wasn't working(PayU Romania,Turkey, Russia, Hungary, Ukraine) 
Everytime when I wanted to checkout to pay with the gateway I had the error 500 so I turned on my debugging and I saw I have some errors. 

![gg](https://user-images.githubusercontent.com/17001721/52485585-e27c7300-2bc1-11e9-933c-f74ae16ebce1.png)

The problem is I have these errors everytime even when I activated classic theme with no module activated, I have the same errors. My guess, the problem is from Prestashop.

The prestashop is fresh installed directly to 1.7.5 with no updates from other version.

**To Reproduce**
1. Go to https://axafarm.ro/ (i may need to remove debugging and to give you access to your IP but maybe you can do it yourself if not I'll do it)
2. Click on any product and try to buy it 
3. See error
4. More errors on debugging mode with no modules activated and even classic theme.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1.5

**Comment by khouloudbelguith** [comment]
Hi @Styxm,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by Styxm** [comment]
https://axafarm.ro/phppsinfo.php no errors

**Comment by khouloudbelguith** [comment]
@Styxm, how did you disabled your modules? from this option "Disable non PrestaShop modules" in your BO => Advanced Parameters => Performance page?

**Comment by Styxm** [comment]
Yes and I activated clasic theme and double check in BO =>Module => Module Manager if all the modules are off

**Comment by khouloudbelguith** [comment]
@Styxm, in fact this option: "Disable non PrestaShop modules" does not work as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9965
Thanks!

**Comment by Styxm** [comment]
Ok I understand! to double check with you to be sure of what I'm doing, I will go and activate clasic theme and after that I should disable all modules from BO =>Module =>Module Manager right? Every single one from the pics and check again if there are any errors right?

![pb1](https://user-images.githubusercontent.com/17001721/52490420-6425ce00-2bcd-11e9-953d-0a6de80a5d92.png)
![pb2](https://user-images.githubusercontent.com/17001721/52490422-6425ce00-2bcd-11e9-9e2f-2537e8dd16e1.png)
![pb3](https://user-images.githubusercontent.com/17001721/52490423-6425ce00-2bcd-11e9-8fcd-2334aaeefdd9.png)

**Comment by khouloudbelguith** [comment]
@Styxm, in my case, with fresh install PS1.7.5.0, I did not manage to reproduce the issue.
Could you please try to clear cache, you can rum those commands
```
rm -fR /Project_Folder/var/cache/*
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Check & feedback.

**Comment by Styxm** [comment]
I did just now same errors

**Comment by khouloudbelguith** [comment]
Hi @Styxm,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
