### ISSUE TITLE
La propriété Customer->lastname est vide. 

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#12512]
Bonjour,

Lorsque je me connecte à un compte que j'ai créé sur mon site test (Prestashop 1.7.5), l'erreur suivante apparaît : 
La propriété Customer->lastname est vide.
at line 984 in file classes/ObjectModel.php

Pouvez-vous m'aider à corriger cette erreur ?

Merci d'avance !

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

did you create this customer from the BO or from the FO?
During the creation, did you st the last name?
Thanks!

**Comment by Amulliez** [comment]
Bonjour @khouloudbelguith,

Merci de répondre à mon problème. 
Ce compte a été créé directement via le FO. Tous les champs avaient été correctement renseignés.

Merci.

**Comment by khouloudbelguith** [comment]
@Amulliez, this issue occurs only with one customer or with all customers created?
Thanks!

**Comment by Amulliez** [comment]
@khouloudbelguith 
Avec plusieurs comptes mais pas l'intégralité.
Merci.

**Comment by khouloudbelguith** [comment]
@Amulliez, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Amulliez** [comment]
Bonjour @khouloudbelguith,

Voici les fichiers en question en pièce jointe.

Merci pour votre aide.

Bonne journée.
[20190208_exception.log](https://github.com/PrestaShop/PrestaShop/files/2850226/20190208_exception.log)
[dev.log](https://github.com/PrestaShop/PrestaShop/files/2850229/dev.log)

**Comment by khouloudbelguith** [comment]
@Amulliez, in a dev log file, you have some errors, with `sizeconversion` module, `lyoshowvatfree` module, have you tried to contact the module author about the errors?
Did you use a migration Pro module to make to an upgrade? Does this issue occur after the upgrade only?
Thanks!

**Comment by Amulliez** [comment]
@khouloudbelguith Excusez-moi pour le délai de réponse assez long. 
La version des deux modules que vous avez cité précédemment ne sont pas compatibles avec la version Prestashop 1.7. J'ai désinstallé ces modules mais l'erreur est toujours présente.
Oui un module de migration Pro a été utilisé pour effectuer le mise à niveau. Le problème n'est pas survenu juste après la migration mais quelques jours après.

Merci de votre réponse.

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

Could you please check if there is something went wrong with your update and don't have some of the database columns that were added for 1.7.5.
The solution is to check if there are missing columns in your database schema.

You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql

Also, try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
