### ISSUE TITLE
Customers from United Kingdom cannot see taxes in the site when logged

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12514]
Hi
a my customer get some orders from some countries of EU (the shop is in Italy) like from France or Spain and the orders have tax included in the prices, instead from UK no.
I've tested on a clean prestashop 1.7.5 and I can see the same problem
UK is in the EU zone like Spain, so it is very strange

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/52486068-87934d80-2bba-11e9-817f-f4e42b870183.png)
![2](https://user-images.githubusercontent.com/653230/52486069-87934d80-2bba-11e9-93ae-bef237686908.png)
![3](https://user-images.githubusercontent.com/653230/52486070-87934d80-2bba-11e9-93e6-c08e6397525c.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by PierreRambaud** [comment]
Wait for March 29 :trollface:

**Comment by Maofree** [comment]
if the shopkeepr wants to add the taxes also for that people how is it possible?
so at this moment is it normal that the taxes are not included?

**Comment by Maofree** [comment]
problem solved adding a new tax rule for the italian vat of UK

**Comment by jf-viguier** [comment]
Hi @PierreRambaud, UK is still in EU et VAT should be applied. Can you reopen this issue ?

**Comment by matks** [comment]
@PrestaShop/prestashop-product-team @jf-viguier has spotted a potential cause for this bug, could you please tell us whether this line is right:
https://github.com/PrestaShop/PrestaShop/blob/develop/localization/fr.xml#L77

In "localization/fr.xml" localization file, there is a VAT setting targeting country with ISO code "uk" although United Kingdom iso code is "gb"

**Comment by jf-viguier** [comment]
Line is wrong I guess. It should be "gb" in all EU countries in corresponding xml.
UK is not mentioned in "EU VAT For Virtual Products", is there any legal reason here ?
