### ISSUE TITLE
can not edit or create a new product prestashop 1.7.5.0

### ISSUE THREAD

**Issue by jhon111** [PrestaShop/PrestaShop#12517]
Hello;

I'm trying to start a store but i can't save or create produts because it is showing me an error.More exactly this error http://forge.prestashop.com/browse/BOOM-5229  http://forge.prestashop.com/browse/BOOM-5228

Please see this video in the site of test i have https://screencast-o-matic.com/watch/cqnirD3HTQ

so the error is this:

VM2537:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
at Function.parse [as parseJSON] (<anonymous>)
at Object.error (VM1795 form.js:907)
at u (VM1744 main.bundle.js:275)
at Object.fireWith [as rejectWith] (VM1744 main.bundle.js:275)
at i (VM1744 main.bundle.js:275)
at XMLHttpRequest.<anonymous> (VM1744 main.bundle.js:275)

Is strange because with your theme by default all work fine but if i activate the theme i purchased in addons the error appear.

I've contacted the developers of the theme but they answer me this,telling not is error of their theme

![image](https://user-images.githubusercontent.com/2414901/52495880-eac3b680-2b9f-11e9-8da2-87a0554445b1.png)

Let me know

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version:7.2

**Comment by MathiasReker** [comment]
I can't reproduce. Can you record a video to show how to reproduce and show all the values of your product?

**Comment by jhon111** [comment]
Please check it in computer friend not in mobile,the video is wrking fine

thanks
Kind Regards

**Comment by khouloudbelguith** [comment]
Hi @jhon111,

I did not manage to reproduce the issue with fresh install PS1.7.5.0.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source): fresh install or upgrade from a previous version
 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by jhon111** [comment]
Hello;
the errorr appear when i have this theme activated  http://morgans-pomade.ch/themes/v1.1.0-PRS187.zip ,please install it activate and test adding a new product,or if you have products you can try to change of category or add in another category a product. In this image you can see the error you go to get
![error theme](https://user-images.githubusercontent.com/2414901/52557674-1de39100-2dbe-11e9-8039-38d9839d077b.png)

I have this error in the prestashop versión you can see in the image but also in prestashop 1.7.5.0 fresh installation

thanks

**Comment by khouloudbelguith** [comment]
@jhon111,

You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by khouloudbelguith** [comment]
@jhon111, about your theme, I just uploaded it, when I try to use it, I have an error.
![image](https://user-images.githubusercontent.com/16067358/52559204-f9ef7200-2df4-11e9-82a4-99d29ccce21d.png)
Thanks!

**Comment by jhon111** [comment]
In network tab there is not error the error is in console tab
* enable debug mode  I HAVE IT ENABLED
* go to the product page YES
* open up developer tools  YES I MADE THAT
* go to Network tab  DONE
* save product  DONE
* wait for an error, you should see red request information in Network tab  IN NETWORK TAB THERE IS NOT ERROR
* click on it, you should see the error message in "Response" or "Preview" tab   IN CONSOLE TAB IS THE ERROR THE ERROR APPEAR WHEN I TRY TO ASING A PRODUCT TO A DIFERENT CATEGORY

**Comment by jhon111** [comment]
> @jhon111, about your theme, I just uploaded it, when I try to use it, I have an error.
> ![image](https://user-images.githubusercontent.com/16067358/52559204-f9ef7200-2df4-11e9-82a4-99d29ccce21d.png)
> Thanks!

Well i have the theme installed in two stores but i don't have problems with the logo or other things i only have the problem of the console i sent you when i try to add a product to a category
thanks

**Comment by khouloudbelguith** [comment]
Hi @jhon111,

I uploaded your theme, I have the same issue as you, in the Preview Tab, an exception is displayed,

```
Symfony\Component\Debug\Exception\
UndefinedMethodException
in modules/ttspecials/ttspecials.php (line 118)

```

![image](https://user-images.githubusercontent.com/16067358/52561361-7d13c680-2dfb-11e9-819d-c25c595aa0fb.png)
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by jhon111** [comment]
ok thanks now is solved

**Comment by papich06** [comment]
hello,
i have the same template and problem how do you resolve it please can you explain?

**Comment by khouloudbelguith** [comment]
@papich06, in the case of @jhon111, it is a custom module issue, have you the same module installed in your shop, if yes, you need to disable it.
Thanks!

**Comment by jhon111** [comment]
> hello,
> i have the same template and problem how do you resolve it please can you explain?

You need to contact the developer the problem is in the module ttspecials

**Comment by papich06** [comment]
@jhon111 you boought also theme for TemplateTrip Team ?

how can they fix it?

**Comment by jhon111** [comment]
Contact them and explain the problem  they go to help you.

i bought it on addons,they need fix the source code,there is an error in one of the files of the module
