### ISSUE TITLE
Order status images not appearing after upgrade

### ISSUE THREAD

**Issue by niccoX** [PrestaShop/PrestaShop#12527]
Upgraded PS _1.6.1.18_ to _1.6.1.23_

In backoffice> Orders> View: there are no images on the status, except the Canceled image.

_/img/os/6.gif_

I checked the _/img/os_ directory and no images where in the directory after the upgrade.

Not even _/img/os/6.gif_ which is the canceled status, but only that image from the statuses I have tested appear. Payment accepted for example is just an ? image: `<img src="../img/os/2.gif" width="16" height="16">`

**Screenshot**

http://i.prntscr.com/UayBtTe8Qoag2qq4kH91Fw.png

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 7.0

**Comment by MathiasReker** [comment]
Try to clear cache and delete images in tmp folder.

**Comment by khouloudbelguith** [comment]
Hi @niccoX,

I made an upgrade from PS1.6.1.4 to 1.6.1.23 with 1-click upgrade v4.5.1. & I did not manage to reproduce the issue.
![image](https://user-images.githubusercontent.com/16067358/52552294-f1d90780-2ddf-11e9-9c83-6a8419e1011d.png)
Could you please navigate to your BO => Preferences => Images page => in the bottom of the page, click on "Regenerate thumbnails".
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, that’s why I close it.
Thanks for your understanding!

**Comment by niccoX** [comment]
> Try to clear cache and delete images in tmp folder.

Ok, but how will this make the images appear in _/img/os_/ again. As said all images in the directory has gone missing.

**Comment by niccoX** [comment]
> Hi @niccoX,
> 
> I made an upgrade from PS1.6.1.4 to 1.6.1.23 with 1-click upgrade v4.5.1. & I did not manage to reproduce the issue.
> ![image](https://user-images.githubusercontent.com/16067358/52552294-f1d90780-2ddf-11e9-9c83-6a8419e1011d.png)
> Could you please navigate to your BO => Preferences => Images page => in the bottom of the page, click on "Regenerate thumbnails".
> As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
> Your bug isn’t critical or a security issue, that’s why I close it.
> Thanks for your understanding!

Thanks, I will try that. But should I copy the images to _/img/os/_ from another installation before regenerating?

Ok, but there are many bugs that have been fixed by the community and ready to be merged for future releases, why are not those bug fixes included when you release a security update, for example no ones where included in the 1.6.1.23 except one security fix.

**Comment by khouloudbelguith** [comment]
@niccoX, thanks for your feedback.
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be accepted in the `1.6.1.x` branch.
Thanks!
