### ISSUE TITLE
php 7.3 only -Product variants do not show up , product can´t be saved

### ISSUE THREAD

**Issue by yovo-cgn** [PrestaShop/PrestaShop#12522]
**Describe the bug**
Product variants do not show up
A product with variants can´t be edited or saved

**To Reproduce**
1. Go to 'product with variants '
2. Click on 'variations`
![no variants](https://user-images.githubusercontent.com/47471893/52518412-798d0d80-2c4a-11e9-8ca1-9a526d69d097.JPG)

Bug History:
I always had the error "can´t be saved" while creating a product with variants.
But they did show up.
After the change from a supdomain to the maindomain the variants do not show up at all.
Fron-end works fine,
But i can not change any product with variants .. it will not save the changes

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.3

**Comment by yovo-cgn** [comment]
Solved..
This problem only occures with php 7.3
7.2. and below works

**Comment by khouloudbelguith** [comment]
Hi @yovo-cgn,

PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Thanks!

**Comment by matks** [comment]
I think we can reopen this now as we have announced next version will support php7.3 👍 
http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

**Comment by khouloudbelguith** [comment]
Hi @matks,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PHP 7.3.5.
I attached a video record
https://drive.google.com/file/d/1S04U4v_9l2Mj0ZyKTECuD8qHElYfY8hu/view
Thanks!

**Comment by ogi99** [comment]
All I am using PS 1.7.5.2 with PHP 7.2 and I face exactly the problem as described.

**Comment by khouloudbelguith** [comment]
@ogi99, issue reported here: #14368
