### ISSUE TITLE
Where is the PS Cleaner Module

### ISSUE THREAD

**Issue by x29a** [PrestaShop/PrestaShop#12529]
**Describe the bug**
I want to follow https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/migration/ and it states a `pscleaner` module. I can not find it.

**To Reproduce**
1. Go to `Modules Catalog` in Shop
2. Search for `cleaner`
3. Be redirected to https://addons.prestashop.com/en/search?search_query=cleaner&utm_source=back-office&utm_medium=recherche&utm_campaign=back-office-EN
4. Dont find any free module named `cleaner`

**Additionnal information**
PrestaShop version: 1.7.4.4 from official docker image
PHP version: 5.6.40

**Comment by MathiasReker** [comment]
https://github.com/PrestaShop/pscleaner

**Comment by x29a** [comment]
Thanks, any reason its not distributed via the Marketplace?
