### ISSUE TITLE
Base de données qui explose sans raison apparente, jusqu'au dépassement de quota et au blocage

### ISSUE THREAD

**Issue by Neilerua75** [PrestaShop/PrestaShop#12526]
Bonjour,

Je suis sur Prestashop 16.1 (projet que je relance et donc site encore en construction / importation des produits dématérialisés en cours / peu de visiteurs / nombreuses catégories et sous-catégories créées mais nombre de produit inférieur à 50 pour l'heure) et je rencontre un problème avec la base de données de la boutique qui explose sans aucune raison et sans intervention de ma part, a priori depuis le passage en mode SSL.

Le problème est apparu plusieurs fois et est donc récurrent. 

Le bug est ennuyeux car ma base de données passe de 50 Mo environ en temps normal à plusieurs gigas (jusqu'à 16 Go) d'une journée à l'autre sans que j'utilise l'interface dans l'intervalle et mon hébergeur bloque la base de données une fois le quota atteint (mode lecture simple). Ce qui m'oblige à restaurer la dernière version de la base de données (= perte des modifs récentes et produits nouvellement créés), avant toute explosion de sa taille. 

Mes interrogations de débutant :
1 : le problème est-il fréquent ?
2 : est-il plutôt lié à Prestashop ou à mon hébergeur ?
3 : le mode SSL est-il en cause ?
4 : mon arborescence de produits dématérialisés avec de nombreuses catégories et sous-catégories pourrait-il être en cause ?
5 : que faire pour que le bug cesse et que la base de données n'explose plus ?

Je précise que le certificat SSL semble correctement installé au niveau de l'hébergeur et de Prestashop, et ma boutique a obtenu A à un test de sécurité sur le site Qualys SSL Lab. En revanche, je n'ai pas modifié le fichier htaccess pour forcer la redirection sur https: par peur de faire une bêtise (redirection forcéesur https: déjà activée sur Prestashop), ce qui a peut-être une incidence (script qui tourne en boucle ?). 

Avec tous mes remerciements par avance pour vos éclairages.

Neil

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Neilerua75,

Could you please provide us with more info? We need more details to understand your issue:

- debug mode report
- PHP error logs
- apache error log
- javascript console log

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Neilerua75,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
