### ISSUE TITLE
iFrame issue in 1.7.5 - 

### ISSUE THREAD

**Issue by RUMBuilder** [PrestaShop/PrestaShop#12525]
previous thread CLOSED for no reason with NO resolution by mods:
https://github.com/PrestaShop/PrestaShop/issues/12135

I have checked everything I can, server is compatible, settings are correct, etc. 
Finally bit the bullet and did they're last option - I did a COMPLETE wipe of the installation, and a BRAND NEW installation - TWICE. The first time I used the autoinstaller in the PS zip file(via index.php) 
I then attempted to modify an EXISTING demo product, and add my own iframe to the product description. (I enabled iframes in settings, and also disabled html cleaner). THIS WORKED FINE. My content displayed, no issues. 

I then created a NEW test product, cloning the information from the demo product EXACTLY. Then I added my iframe code, exactly the way i had before. GUESS WHAT!? I get the "Unable to update settings". Console throws: 
VM798:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.5.0:687)
    at u (main.bundle.js:275)
    at Object.fireWith [as rejectWith] (main.bundle.js:275)
    at i (main.bundle.js:275)
    at XMLHttpRequest.<anonymous> (main.bundle.js:275)

I then tried wiping everything AGAIN, and using the Softaculous Installer via cPanel, did the exact same tests, and got the exact same results. 

Anybody have ANY idea what the cause could be? I've checked everything I can think of, and I have not modified any core files, or heck... ANY files, and have tried this TWICE from a completely clean install, with ZERO resolution. 

I appreciate any help possible, I have a functioning store that I need to have up and running asap.

Thanks.

**Comment by kpodemski** [comment]
I don't think that it's a PrestaShop issue, i think that you should contact with some PrestaShop developer who will debug it for you.

You need to enable debug mode in your store and debug request which is send for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see error message in "Response" or "Preview" tab

**Comment by khouloudbelguith** [comment]
Hi @RUMBuilder,

As said in your previous issue.
I did not manage to reproduce the issue with PS1.7.5.0, after enabling the iframe in the General page, in the product the video inserted is well displayed in the FO - product page.
![image](https://user-images.githubusercontent.com/16067358/52553694-b7259e00-2de4-11e9-953c-72217cc642f6.png)
@marionf, can you try to reproduce the issue?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith I can't reproduce

![capture d ecran_996](https://user-images.githubusercontent.com/13449658/52554117-20f27780-2de6-11e9-90a0-9991b2e0a9aa.png)

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Comment by khouloudbelguith** [comment]
@marionf thank you!
