### ISSUE TITLE
Impossible d'envoyer des emails en utilisant mes paramètres SMTP

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#12534]
Je renseigne mes paramètres SMTP dans Paramètres avancés > Email, avec chiffrement SSL et port 465.

Lorsque je clique sur Envoyer un email d e test, ça fonctionne très bien, mais dans les cas suivant, je ne reçois pas d'email :
1. Lorsque j'envoie un email de test à partir de la page contact : aucune erreur et le message "Votre message a bien été envoyé à notre équipe." s'affiche, mais ni l'expéditeur ne le destinataire ne reçoivent d'email.
2. Lorsque je modifie le statut d'une commande, aucun email n'est envoyé, et j'ai une erreur 500 Swift_RfcComplianceException : Address in mailbox given [contact@] does not comply with RFC 2822, 3.6.2.

Sur Prestashop 1.6 cela fonctionne très bien en TLS 465.
Mais sur la 1.7, lorsque je mets TLS 465 j'ai le message d'erreur suivant : 
Erreur : veuillez vérifier votre configuration
Connection to tcp://in-v3.mailjet.com:465 Timed Out

J'ai également testé avec tous les paramètres possibles : Chiffrement TLS, SSL, Aucun, et Port 25, 465, 587, 588, ça ne fonctionne dans aucun cas.

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

If you use the PrestaShop 1.7.5.0, apply this PR to fix your issue: #11995
From 1.7.5.1 this fix will be included in core.
Thanks to check & feedback.

**Comment by guigplt** [comment]
Hi,
Thanks for your answer, I installed the fix and it works now when I change order state.
But it's still not working when I send message from contact page.

**Comment by khouloudbelguith** [comment]
@guigplt, you are not receiving any message, or you have an exception displayed?
Thanks!

**Comment by guigplt** [comment]
No exception displayed, but not receiving any message for sender and recipient.

**Comment by khouloudbelguith** [comment]
@guigplt, you need to check your host about this issue.
Thanks to check with them & feedback.

**Comment by guigplt** [comment]
The problem is not from the host, because it works on Prestashop 1.6 with same parameters (except TLS parameter), and same server.
As I said before when I use TLS on PS 1.7 I have this error message when I try send test message : 
Erreur : veuillez vérifier votre configuration
Connection to tcp://in-v3.mailjet.com:465 Timed Out

**Comment by khouloudbelguith** [comment]
@guigplt, could you please navigate to your BO => Modules => Module Manager => search for the "contactform" module, click on "Configure" button, enable all the options, save.
![image](https://user-images.githubusercontent.com/16067358/52582200-ebbd4800-2e2c-11e9-8029-79d258891200.png)
Thanks to check & feedback.

**Comment by guigplt** [comment]
These options are enabled, but it doesn't work.

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

I tried with SMTP in PS1.7.5.0 & it is working.
I attached a video record.
https://drive.google.com/file/d/1B7hTG21EuU7rBzHajkJJGrXMwlkRS2nS/view
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @guigplt, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
