### ISSUE TITLE
Address form in checkout: button "continue" change to "save" and customer redirected to customer account

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#12533]
Hello !

We noticed, in the checkout address form, when customer changes country, a JS script replaces the "continue" button with a "save" button and the customer is sent to his customer account instead of stay in the checkout. Why ?
Can we disable it without causing other problems ?

**To Reproduce**
1. Connect like a customer
2. Create an address in customer account
3. Add a product to cart
4. Go to checkout
5. Click on Add a new address
6. Enter an address : choose a country different of his selected

The button "continue" becomes "save" button.

Strangely, if the customer has no address, it's necessary to change the country twice for the bug occures.

**Additionnal information**
PrestaShop version: 1.7.3.3, 1.7.4.0, 1.7.5.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/10I5Rnk_daBmYqx2m5-q2nOJUtOOyDJSX/view
https://drive.google.com/file/d/1bNqRO75Wd5H8gfuEpp96fr3CCwTH3Efi/view
Just the "continue" button becomes "save" button, but we are not redirected to the customer account.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@bm-services, I tried with PS1.7.4.4 & it is OK.
https://drive.google.com/file/d/1BOtQS7dSM6FY8csKXCz0EwntlKCx6vaF/view
The "continue" button becomes "save" button, but we are not redirected to the customer account.
Thanks!

**Comment by bm-services** [comment]
Indeed, I relied only on the change of the button's title for my tests. So, in fact, we have this problem of redirection to the customer account only on one PrestaShop.
Sorry for the inconvenience.

**Comment by khouloudbelguith** [comment]
@bm-services, thanks for your feedback.
So, can I close the issue?
Thanks!

**Comment by bm-services** [comment]
Yes, thanks !

**Comment by khouloudbelguith** [comment]
@bm-services, you are welcome!
Feel free to open a new one when needed.
Thanks!
