### ISSUE TITLE
One Click upgrade 1.6.1.17 to 1.7.5.0 Theme error 

### ISSUE THREAD

**Issue by NLukasz24** [PrestaShop/PrestaShop#12530]
**Describe the bug**
I was upgrading from 1.6.1.17 to 1.7.5.0 Stable by one click upgrade feature.
What happened was that data has moved successfully, (that includes orders, clients, products etc.)
But problem is with the template. In a new, fresh and clean 1.7.5.0 install under Design/Theme&logo there are tabs "Homepage configuration" However, after migrating from 1.6 to 1.7 as described above, classic theme doesn't have those tabs under said path.
So the shops' main page comes out empty, because somehow homepage tab is missing, preventing it from being customized.

As seen on screenshots, both show the same menu on clean install and migrated one from 1.6
Migrated one doesn't have those tabs which are not missing on clean install.

**To Reproduce**
Well for me reproducing this bug was easy, just migrate from 1.6 to 1.7 with one-click upgrade module.

**Screenshots**
![przechwytywanie175](https://user-images.githubusercontent.com/47522100/52557073-b3971480-2dee-11e9-8528-373a918d4da9.JPG)
![przechwytywanie172](https://user-images.githubusercontent.com/47522100/52557080-b72a9b80-2dee-11e9-8e1f-93c2adcf8d5e.JPG)

**Additionnal information**
PrestaShop version: 1.6.1.17 to 1.7.5.0 Stable
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @NLukasz24,

You need to install the ps_themecusto module.
![image](https://user-images.githubusercontent.com/16067358/52558556-fbb83600-2df2-11e9-8b6d-51058147bc86.png)
Thanks!
