### ISSUE TITLE
Multi-store feature usage within the forms

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#12540]
### Description
On legacy pages we had feature which allowed us to restrict certain settings update to certain shops.

### Explanation of the functionality

In short, when a multistore feature is enabled and when you are in specific shop context you can see a form which looks like this:

![multi_store_all_disabled](https://user-images.githubusercontent.com/17051250/52632683-e31b4f00-2eca-11e9-93a3-4f91b2b317fe.png)

the disabled fields and checkboxes near the form elements means that **the form inherits all the settings which can only be changed in all shops context**

If I start ticking the checkboxes then I choose a **specific configuration only for the current shop context I am in**

#### Displaying checkboxes and switch

It seems like we need a way to modify each form type - to decorate it with extra checkboxes and the `YesNoSwtich` selector. Talking in very abstract way, I'm thinking of having a Decorator class which will append extra form types:

1. Use it in your form type like:
```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('theme_to_adapt', ChoiceType::class, [
                'choices' => $this->themeChoices,
            ])
            ->add('generate_rtl_css', SwitchType::class, [
                'required' => false,
                'data' => false,
            ])
        ;

        $this->multiStoreFormDecorator->decorate($builder);
    }
```

also , maybe we don't want that all fields would have multi-store checkbox relation:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('theme_to_adapt', ChoiceType::class, [
                'choices' => $this->themeChoices,
            ])
            ->add('generate_rtl_css', SwitchType::class, [
                'required' => false,
                'data' => false,
            ])
        ;

        $this->multiStoreFormDecorator->decorateFor($builder, ['theme_to_adapt']);
    }
```
2. Inside the decorator I'll iterate over available form types and add another type which will be a checkbox and it will be named like `theme_to_adapt_is_restricted_to_shop` or something :thinking: (Basic idea is to append some text to the original for type for easier usage withing javasscript etc..)
Also a new switch type will be appended as well  - **not sure if it should be optional or not**

With this usage we have full control ir our twig template to put these checkboxes in appropriate place. **Maybe in form_group_row macro we can attach it automatically ?**

#### Submitting the data

Well it would be very unconfortable to take all the checkboxes manually. However inside a decorator maybe a [data transformer](https://symfony.com/doc/3.4/form/data_transformers.html) might come in handy. With using this the data can be retrieved in a comfortable array or the collection which holds the mapping of the original field name and  a way to recognise that for specific field checkbox has been ticked. Usually all the settings forms share same logic so something reusable can be made as well when  having the data built in comfortable way.

Need opinions on this topic @matks , @eternoendless , @mickaelandrieu , @sarjon , @rokaszygmantas

**Comment by tomas862** [comment]
Got a real example of how this stuff might be implemented: although done it on purpose in not reusable way in order to just demonstrate the idea - after some discussions I will be able to refactor it and split the behaviors. Everything in Form type is done with private methods but the idea is to move that part to decorator services etc... 

1. First part - decorating the form type with extra shop restriction checkboxes and shop restriction swich. https://github.com/PrestaShop/PrestaShop/pull/12331/files#diff-c761f50618701a6d1ec1fea9dcd817ccR100

2. On form submit data transformer transforms shop restriction fields in object `ShopRestriction` https://github.com/PrestaShop/PrestaShop/pull/12331/files#diff-c761f50618701a6d1ec1fea9dcd817ccR183

3. When form is submitted I ensure that form fields which should be turned off due to the checkbox is not checked are not being submitted - I do that in https://github.com/PrestaShop/PrestaShop/pull/12331/files#diff-d2904cde011eb3f3bf62fee65b7f3953R77. But also I can do that by overriding form event directly in type so maybe its more appropriate do to that there?

4. The form must know whenever the checkbox were checked and submitted - I created another interface https://github.com/PrestaShop/PrestaShop/pull/12331/files#diff-c488c3ce3fc680313d3e43e98e71c4e8R32 but right now I have doubts about its purpose - maybe we should just use query bus for providing the **checkbox is on or off**   ?

5. The javascript must be called in order to checkboxes and switch functionality to work https://github.com/PrestaShop/PrestaShop/pull/12331/files#diff-fad5a4e4ee85e6ce6936f33bdc5f31cbR33


so my idea now is just to confirm if the workflow looks okey and in another PR I'll make all these parts reusable

**Comment by matks** [comment]
ping @eternoendless this is the discussion about multi-shop system

**Comment by marionf** [comment]
Ping @matthieu-rolland FYI, maybe this issue will be usefull to implement checkboxes, let me know otherwise I close it

**Comment by matthieu-rolland** [comment]
Yes, this issue and the related PR and also this PR: (https://github.com/PrestaShop/PrestaShop/pull/14802) are indeed useful 👍   (the last PR is the one that @matks tested recently)

**Comment by matks** [comment]
Topic now in the smart hands of @matthieu-rolland . No need to keep this issue, there are other issues open.
