### ISSUE TITLE
Product Module configuration page backoffice issue

### ISSUE THREAD

**Issue by kaydm** [PrestaShop/PrestaShop#12542]
If there's a "." (dot) in the SEO Meta Description fo the product you cannot access any product module configuration page.

**Comment by khouloudbelguith** [comment]
HI @kaydm,

Have you the same issue described in this ticket: #11911?
Thanks!

**Comment by kaydm** [comment]
Hi @khouloudbelguith, that is correct. Thanks.

**Comment by khouloudbelguith** [comment]
@kaydm, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11923 to fix the issue.
It is fixed in the next release PS1.7.5.1.
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11911

**Comment by kaydm** [comment]
> @kaydm, here's the PR: #11923 to fix the issue.
> It is fixed in the next release PS1.7.5.1.
> Your ticket is a duplicate of #11911
> So, I close it.
> Thanks!

Thanks, alredy fixed it in my 1.7.5 store.
