### ISSUE TITLE
Can't delete product images on multistore

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#12555]
I know here is no more maintenance on PS 1.6 but maybe you fixed it and I can find a patch. 

I found out that we can't delete picture of Products when multistore is enabled. When I click on the delete button, it says that it's OK but nothing when I refresh the page, images are still here. The problem is that the invoices uses the first loaded image, even if they are desactivated/disabled and that is a problem.

Any idea ? Thanks !

PrestaShop version: 1.6.1.6

**Comment by khouloudbelguith** [comment]
Hi @hellodracon,

I did not manage to reproduce the issue with PS1.6.1.23.
I attached a video record.
https://drive.google.com/file/d/12RRHgLgwaeHAhduiD_Hh_g7CLuYij5rQ/view
It could be this PR: https://github.com/PrestaShop/PrestaShop/pull/8612 help you to solve your issue.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs, that’s why I close it.

**Comment by hellodracon** [comment]
Sorry to re-open it @khouloudbelguith that's not really the same issue. Is there a way i can try on PS 1.6.1.6 without having to install it myself ? Like a demo version or something ?

I've read all the code that means to delete the image (in class/Image.php and class/ObjectModel.php), and nothing seems weird but I don't get how it can not be working. Maybe you have an idea on what I should look into ? I'm just looking for a small help if I can have it, not real maintenance. Let me know If I'm asking too much :) 
Thank you !

**Comment by khouloudbelguith** [comment]
@hellodracon, we have a [demo](http://demo.prestashop.com) version but it is with version PS1.7.4.2.
PrestaShop 1.6.1.6 is a very old version
Thanks!

**Comment by hellodracon** [comment]
@khouloudbelguith  alright, thank you ! I'll find my way

**Comment by hellodracon** [comment]
Found out what was wrong (a store from the multistores was broken).
