### ISSUE TITLE
ps_brandlist when installed is not a the side column

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12562]
Hi
try to install the ps_brandlist module, it will not visible in the front-office like under the ps_facetedsearch
normally it should be present in the left column

thanks
bye

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I did not manage to reproduce the issue with PS1.7.5.0 & the ps_brandlist module v1.0.2.
I attached a video record.
https://drive.google.com/file/d/1qM3mSy34WQQQFkLgUPZZd5fUEPCyDptA/view
Could you please navigate to your BO => Design => Positions page, search for the brand list module, it should be displayed in the displayLeftColumn hook under the ps_facetedsearch module.
![image](https://user-images.githubusercontent.com/16067358/52771524-65745200-3036-11e9-99a2-b3f4826dfc02.png)
Thanks to check & feedback.

**Comment by Maofree** [comment]
hi
today it works well in both sites where the other time did not work, strange, however, better this way

**Comment by khouloudbelguith** [comment]
@maofree, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
