### ISSUE TITLE
Wrong taxes and detail prices on invoice when product with special price 

### ISSUE THREAD

**Issue by tessa135** [PrestaShop/PrestaShop#12568]
In Prestashop 1.7.5.0 I have a product with 20% discount and 7% taxes. 
On invoice this product has 15% taxes and wrong prices. The invoice total is correct. 
Taxes of last item should be 7% and price without taxes 38,80€ instead of 34,89€.
To reproduce: 
(1) create product with 7% taxes (german MwSt.)
(2) add 20% discount via special price
(3) order product
(4) create invoice
![bildschirmfoto 2019-02-13 um 10 07 07](https://user-images.githubusercontent.com/14851954/52780949-ac207700-304b-11e9-814a-6e55a5beae42.png)
![bildschirmfoto 2019-02-13 um 10 06 24](https://user-images.githubusercontent.com/14851954/52780950-ac207700-304b-11e9-8e5f-0c3d997f402b.png)
![rinti](https://user-images.githubusercontent.com/14851954/52780962-b2aeee80-304b-11e9-8f10-7f26f92ae070.png)

**Comment by khouloudbelguith** [comment]
Hi @tessa135,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1lHojw0Dm9szUFmH22ctUBLjAxtAeu3Dt/view
Thanks to check & feedback.

**Comment by tessa135** [comment]
Today I couldn't reproduce the issue neither. Really awkward. Sorry for the inconvenience, I will Close the issue

**Comment by khouloudbelguith** [comment]
@tessa135, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
