### ISSUE TITLE
'AppKernel' not found when running `docker-compose up` with prestashop v1.7.5.0

### ISSUE THREAD

**Issue by diegocastrum** [PrestaShop/PrestaShop#12583]
**AppKernel not found in /var/www/html/config/autoload.php:28**
I just download the last release of Prestashop (v1.7.5.0), after that I run a `docker-compose up`, everything seems to be ok but when I try to access to the web interface using the ip of the container I got a 500e and the log says:

```
PHP Fatal error:  Uncaught Error: Class 'AppKernel' not found in 
/var/www/html/config/autoload.php:28\nStack trace:\n#0 /var/www/html/config/config.inc.php(36): require_once()\n#1 /var/www/html/index.php(27): require('/var/www/html/c...')\n#2 {main}\n  thrown in 
/var/www/html/config/autoload.php on line 28
```

**To Reproduce**
1. Download prestashop_1.7.5.0
2. Run `docker-compose up`
3. Use the browser to access to the web interface
4. See error log

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @diegocastrum,

Could you please confirm these steps to reproduce the issue:
1. Download the stable version PS1.7.5.0 from this link: https://www.prestashop.com/fr/versions-precedentes
2. Unzip the folder downloaded
3. Into the project folder, you just run `docker-compose up`
4. Then reach your shop on this URL: http://localhost:8001

Thanks!

**Comment by diegocastrum** [comment]
Hi @khouloudbelguith,

Sure, I'm having the same error.

**Comment by khouloudbelguith** [comment]
@diegocastrum, 

In my case here's what I followed & I installed the PS1.7.5.0 successfully.
1. Download the stable version PS1.7.5.0 from this link: https://www.prestashop.com/fr/versions-precedentes
2. Unzip the folder downloaded
3. Into the Project folder, I run `docker-compose up`

=> Two containers are successfully created
1. `foldername_mysql_1` container from the image `mysql:5`
2. `prestashop-git` container from the image `prestashop/prestashop-git:7`
3. Give the write and read access is to use the same user the container image.

```
$ chown -hR www-data:www-data ./Project_Folder_name
```
4. I tried to access to http://localhost:8001/install-dev
5. I am resigned to install composer 
6. I created a file composer.json into the Project folder similar to this https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/composer.json
7. I installed the composer from this link: https://getcomposer.org/download/
8. Then I run this command: `php composer.phar install` => OK
9. I tried to access to `http://localhost:8001/install-dev `=> OK ( MYSQL_ROOT_PASSWORD = password )
10. Installation complete => access to BO via this link: `http://localhost:8001/admin-dev`

Heres' my server information
![image](https://user-images.githubusercontent.com/16067358/52851499-91670480-3116-11e9-9ec6-3f8feb4cc52c.png)

Heres' my volume for the `prestashop-git` container
![image](https://user-images.githubusercontent.com/16067358/52852809-ee17ee80-3119-11e9-947d-0b4e1837cce3.png)

Thanks!

**Comment by diegocastrum** [comment]
Got it, it works now!

I think the problem was just missing of the `composer.json` file. The whole process around `composer` is a bit "dark" for me, I mean I couldn't find the right process to follow anywhere (maybe my bad).

Thank you very much for your time and help!!

**Comment by khouloudbelguith** [comment]
@diegocastrum, thanks for your feedback.
You are welcome!
Feel free to open a new one when needed.
Thanks!
