### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by web-centre** [PrestaShop/PrestaShop#12582]
by accessing the backoffice, I receive this error message

5 errors

Error found: CData section not finished 29.99 in the must_have_module_list.xml file.
Error Found: Premature end of data in EUR line tag 1 in the must_have_module_list.xml file.
Error found: Premature end of data in price tag line 1 in the must_have_module_list.xml file.
Error found: Premature end of data in module line tag 1 in the must_have_module_list.xml file.
Error found: Premature end of data in module line tag 1 in the must_have_module_list.xml file.

 

 

 

 

accedendo al backoffice mi appare questo messaggio di errore

5 errori 

Errore trovato: CData section not finished 29.99 nel file must_have_module_list.xml.
Errore trovato: Premature end of data in tag EUR line 1 nel file must_have_module_list.xml.
Errore trovato: Premature end of data in tag price line 1 nel file must_have_module_list.xml.
Errore trovato: Premature end of data in tag module line 1 nel file must_have_module_list.xml.
Errore trovato: Premature end of data in tag modules line 1 nel file must_have_module_list.xml.

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @web-centre,

Could you please try to navigate to your BO => Advanced Parameters => Performance page and click on the  clear cache button.
Thanks for check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @web-centre, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
