### ISSUE TITLE
OutOfMemory Error when opening add product page

### ISSUE THREAD

**Issue by titamrtn** [PrestaShop/PrestaShop#12589]
**Describe the bug**
After new install i can add product normally but after i upload category(over 7000) i got OutOfMemory exception when opening add product page in backend. 

I already tried to increase memory to 512M but still have the same error.
![screenshot from 2019-02-15 15 41 46](https://user-images.githubusercontent.com/5078563/52857441-39d99080-3138-11e9-9040-b010d619de3e.png)

this is my category import file 
[importation_csv.csv.zip](https://github.com/PrestaShop/PrestaShop/files/2869241/importation_csv.csv.zip)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

Thanks for your report.
I'm trying to import your file csv, but it took time because you have more 7000 categories, then I will come back to you if we need more information.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
[import.mp4.zip](https://github.com/PrestaShop/PrestaShop/files/2869809/import.mp4.zip)
I'm affraid that 512M will be not enough, especially when you have more than 7000 categories.
Thanks to check & feedback.

**Comment by titamrtn** [comment]
So to fix it i need to upgrade to 1.7.5.0?

**Comment by khouloudbelguith** [comment]
@titamrtn, the `outOfMemory` issue is a server issue.
In your php.ini file, Try to increase:
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit = 1000M

Thanks to Check & Feedback.

**Comment by titamrtn** [comment]
I can't go over 512M, is there no way to load all categories by ajax for e.g. Not load it one time.

**Comment by khouloudbelguith** [comment]
@titamrtn, in the PS1.7.4.0, with this PR: https://github.com/PrestaShop/PrestaShop/pull/8896, we have improved the time to show the product page when we have a large number of categories, reported in this [ticket](http://forge.prestashop.com/browse/BOOM-3666) previously.
Thanks to check & feedback.

**Comment by marionf** [comment]
@titamrtn As we have no news from you since more than 30 days, I close your issue.
Feel free to open a new one if it's necessary
Regards
