### ISSUE TITLE
Module manager: modules are not always in the right categories according to the language

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12591]
Just installed a fresh 1.7.5.0 in Spanish:

![image](https://user-images.githubusercontent.com/15104724/52856552-06413b00-3125-11e9-80b4-830ef10356e6.png)

_Originally posted by @idnovate in https://github.com/PrestaShop/PrestaShop/issues/11440#issuecomment-464030434_

**Comment by marionf** [comment]
Install in French:

![capture d ecran_1020](https://user-images.githubusercontent.com/13449658/52862618-f716b900-3135-11e9-845a-e96d26da54bf.png)
![capture d ecran_1021](https://user-images.githubusercontent.com/13449658/52862623-fa11a980-3135-11e9-8dd9-a4ffa006d4be.png)
![capture d ecran_1022](https://user-images.githubusercontent.com/13449658/52862632-fc740380-3135-11e9-90b0-a25b757b907e.png)
![capture d ecran_1023](https://user-images.githubusercontent.com/13449658/52862636-fed65d80-3135-11e9-87ef-b693e4f14660.png)

**Comment by marionf** [comment]
Install in English:

![capture d ecran_1024](https://user-images.githubusercontent.com/13449658/52862758-49f07080-3136-11e9-99db-0e6fa2cb5ec4.png)
![capture d ecran_1025](https://user-images.githubusercontent.com/13449658/52862762-4ceb6100-3136-11e9-8ecd-443eb1f954ec.png)
![capture d ecran_1026](https://user-images.githubusercontent.com/13449658/52862765-4fe65180-3136-11e9-8d9b-28b91bf2f8c0.png)
![capture d ecran_1027](https://user-images.githubusercontent.com/13449658/52862769-5248ab80-3136-11e9-99b6-99bb79c9a2a2.png)
![capture d ecran_1028](https://user-images.githubusercontent.com/13449658/52862772-55439c00-3136-11e9-89ec-54a0b877325f.png)

**Comment by colinegin** [comment]
As discussed, this should be the new tab organization : 
Modules 
        Module Manager
        Module Catalog

Thanks

**Comment by nikitamekh** [comment]
After this fix, all custom modules are displayed in "Other category" now. I do not know why, but they do not have '**categoryParentEnglishName**' attribute. Please check this forum thread https://www.prestashop.com/forums/topic/1022836-problem-with-module-categories/
