### ISSUE TITLE
Cannot delete cart rule with no code

### ISSUE THREAD

**Issue by tlhuillier** [PrestaShop/PrestaShop#12608]
**Describe the bug**
User cannot remove a cart rule with *no code* from his cart.

**To Reproduce**
1. Add a cart rule with no code
2. On the Front Office, visit the cart page and try to remove the cart rule from the cart.
3. Cart rules stays !

**Additionnal information**
Inside the templates, we can't see if a cart rule has a voucher code or not,
so we can't hide the delete button for this kind of cart rule.

**Comment by khouloudbelguith** [comment]
Hi @tlhuillier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.5.1 & PS1.7.4.4.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
