### ISSUE TITLE
Link format doubt

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#12604]
I noticed the links to products with combinations are still adding extra parameters:

http://localhost/ps/en/men/1-1-hummingbird-printed-t-shirt.html#/1-size-s/8-color-white

Previously the default product link was just a simple:
http://localhost/ps/en/men/1-1-hummingbird-printed-t-shirt.html

I know this has been debated in other tickets, is there an explanation somewhere about why the combination information such as #/1-size-s/8-color-white is now added when navigating? Can someone ensure this does not impact SEO etc. 

I am not saying its wrong I am just curious to why we can not use the plain url to get to the default product combination like it was before.

**Comment by kpodemski** [comment]
Canonical url has no additional attributes so it should be all good for SEO

**Comment by johanlantz** [comment]
ok, that is a very reasonable answer so I will close the ticket with that. Thanks
