### ISSUE TITLE
category and module issue

### ISSUE THREAD

**Issue by M-Grafix** [PrestaShop/PrestaShop#12607]
Hi,

Three days ago, I was creating new products in my catalog and Prestashop couldn't work anymore !
Now, I cannot access to my catalog and also the module, my page stays white. Other tabs works.

If someone can help me, I would be very happy ! :)
Thanks,
Marie

**Comment by khouloudbelguith** [comment]
Hi @M-Grafix,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by M-Grafix** [comment]
Hi,

 

Thansk for your reply !

I’m gonna try to give you the needed information ! Please find below and attached !

You have to know that sometimes the catalog page appears in the BO (I don’t know which reason for !) but if I try again, the page becomes white again !

 

• Host : OVH - ftp.cluster021.hosting.ovh.net

• Server setup and configuration : ?

• Version Prestashop 1.7.2.2

• debug mode report : unable to go to this page ( same problem as to go to my catalog and module, I cannot access, I’ve got a white page appearing !

• PHP error logs
• Apache error log

• Javascript console log

• Screenshots : attached

 

Regarding the tab “ Click Upgrade”, a page error appears : see attached

 

Don’t understand nothing ☹

Hope you can help me !

Regards,

 

Marie

Graphiste indépendante

+32472841189

www.m-grafix.be

 

 

De : khouloudbelguith <notifications@github.com>
Répondre à : PrestaShop/PrestaShop <reply@reply.github.com>
Date : lundi 18 février 2019 09:54
À : PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc : M-Grafix <info@m-grafix.be>, Mention <mention@noreply.github.com>
Objet : Re: [PrestaShop/PrestaShop] category and module issue (#12607)

 

Hi @M-Grafix,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
host
server setup and configuration
PrestaShop version (source)
debug mode report
PHP error logs
apache error log
javascript console log
screenshots
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@M-Grafix, there are attached files, you need to connect to Github & attache files in this ticket.
Thanks!

**Comment by M-Grafix** [comment]
![click upgrade](https://user-images.githubusercontent.com/47738000/52957589-4c4f0680-3392-11e9-93ab-c992c98e38e8.jpg)
![info prestashop](https://user-images.githubusercontent.com/47738000/52957590-4c4f0680-3392-11e9-85b2-862510fb49e3.jpg)

**Comment by khouloudbelguith** [comment]
@M-Grafix, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by M-Grafix** [comment]
How can I retrieve the PHP error log and the debug mode report ?

**Comment by khouloudbelguith** [comment]
@M-Grafix, if you don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by M-Grafix** [comment]
PHP error log : "L’encodage de caractères d’un document dans un cadre n’a pas été déclaré. Le document peut apparaître différent s’il est visionné sans le document qui l’encadre." It means in english : "The character encoding of a document in a frame has not been declared. Can be seen in the document is the frame. "

To have the debug mode report, I have to go to my Advanced Parameters > Performance but I cannot have the access anymore :s The page appears white !!

**Comment by khouloudbelguith** [comment]
@M-Grafix,
If you can’t access your dashboard, you can still enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

I cannot do anything without having a little more detail in addition to the 500 error
Thanks for your understanding!

**Comment by M-Grafix** [comment]
I've changed what you asked me in my FTP but I don't know what to do now !

Thank U to try to help me but it's quite complicated for me to understand everything !
Maybe I'm gonna asked to a technical support who could do it for me !
I'm quite sure it's a Prestashop issue because it became for no reason when I was creating product !

**Comment by khouloudbelguith** [comment]
@M-Grafix, after enabling the debug mode, when you navigate to your BO(create a new product,..), are there any exceptions displayed?
Thanks!

**Comment by M-Grafix** [comment]
Always white page and nothing in the console (see printsrceen)
![sans titre-1](https://user-images.githubusercontent.com/47738000/53004381-5aa02f80-3431-11e9-8a91-84bd0e043860.jpg)

**Comment by khouloudbelguith** [comment]
@M-Grafix, the blank page cannot help us to understand the issue.
We need php error logs. If you don't have it, you should ask your hosting provider.
Thanks!

**Comment by M-Grafix** [comment]
I succeeded to go to my catalog, I don't know why ! And I quickly made a print screen with the message :
![print screen](https://user-images.githubusercontent.com/47738000/53021445-82a38900-3459-11e9-9088-8bfa1db8116f.jpg)

**Comment by khouloudbelguith** [comment]
@M-Grafix, those are just warnings, not errors, some warnings about the maps, related to this: #10393.
What about the other pages => they are well opened?
THanks!

**Comment by M-Grafix** [comment]
I cannot access to other pages like Module, Click Upgrade, Theme, Advanced parameter, etc.

**Comment by M-Grafix** [comment]
And the catalog is not accessible again !

**Comment by khouloudbelguith** [comment]
@M-Grafix, could you please provide me your credentials to access to your BO to test it.
This is a public space.
You can provide me the link by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by M-Grafix** [comment]
Sent ;)

**Comment by khouloudbelguith** [comment]
@M-Grafix, I just received your email.
Could you please edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

I need debug mode enabled.
Thanks!

**Comment by M-Grafix** [comment]
Ok, done

**Comment by khouloudbelguith** [comment]
@M-Grafix, no, in the link that you provided it to me, it is still disabled.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @M-Grafix,

As described in your last email.
Your issue is solved ( not a PrestaShop issue).
I close the ticket, feel free to open a new one when needed.
Thanks!
