### ISSUE TITLE
Hook displayFooterAfter is missing in Design -> Positions (PS 1.7.5.1)

### ISSUE THREAD

**Issue by grigorevlad** [PrestaShop/PrestaShop#12619]
Hi, the new SP 1.7.5.1 has a hook missing in Design -> Positions. There is no displayFooterAfter. 
Any quick fix? 

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @grigorevlad,

After installing the ps_legalcompilance module which is displayed in the hook displayFooterAfter, When I try to navigate to the BO => Design => Positions page => Click on "Transplant a module", 
when I search for a hook, I found the displayFooterAfter hook.
![image](https://user-images.githubusercontent.com/16067358/53007505-ac4bb880-3437-11e9-8fd3-900251bcdab6.png)

I checked with PS1.7.5.1 & PS1.7.4.4 => same behavior.
Thanks to check & feedback.

**Comment by grigorevlad** [comment]
Ah, great. So it needs a module install in order to show in list as active hooks. 
Another thing, 1 Click Upgrade doesn't show new PS 1.7.5.1 in Minor Channel upgrade list. 
I'm doing it manually using autoupgrade/download folder.

**Comment by khouloudbelguith** [comment]
@grigorevlad, The version PS1.7.5.1 will be available for the upgrade today.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by grigorevlad** [comment]
> @grigorevlad, The version PS1.7.5.1 will be available for the upgrade today.
> I close the issue, feel free to open a new one when needed.
> Thanks!

Hi @khouloudbelguith , thanks for feedback. 1-Click Upgrade module was updated today to 4.6.0 , unfortunately it can't find 1.7.5.1 in minor channel upgrade. 
Maybe later, i'll check again.

**Comment by khouloudbelguith** [comment]
@grigorevlad, we just published the new release 1-click upgrade v4.6.0, so, the PS1.7.5.1 will be available to upgrade in few hours.
Thanks for your understanding!
