### ISSUE TITLE
The help message isn't correctly displayed

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#12613]
**Describe the bug**
In B.O, migrate "Catalog , brand & suppliers, "suppliers" page. the help message is displayed on  the whole page.

**To Reproduce**
1. Go to B.O, Catalog, Brands & Suppliers(suppliers page)
2. Click on help button
3. See error

**Screenshots**
![help message2](https://user-images.githubusercontent.com/36889855/52961696-d2bc1600-339b-11e9-9a71-da84a9442e0a.png)

Access: `/admin-dev/index.php/sell/catalog/suppliers/`

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by PierreRambaud** [comment]
Look like this one is outdated:
![image](https://user-images.githubusercontent.com/1462701/55610819-04d6db00-5784-11e9-86f2-ddc6a7b53607.png)

**Comment by PierreRambaud** [comment]
My bad, I tried the wrong url :trollface:
