### ISSUE TITLE
BO : Special chars in product name will stop saving the product

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#12614]
**Describe the bug**
If you use a special character in the name of a product name like ° or ® you can't change properties of the product anymore like the linked category.

**To Reproduce**
1. Create a product with ° or ® in the name
2. Save it
3. Try to change the category will.
4. Nothing happens. So the category will not change.

**Additionnal information**
PrestaShop version: 1.7.3.3
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @mark-app,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1hHsOzm2mhMx2qwmC4EJyJBzoWU3vF4ai/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @mark-appn,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
