### ISSUE TITLE
1.7.5 + autoupgrade 4.5.1 = Internal server error

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12620]
Clean Prestashop 1.7.5 + Autoupgrade 4.5.1 = Internal server error... when want to access module.

**Comment by kpodemski** [comment]
you will not find any updateDelay string because it's obscured by webpack into core.js

also, internal server error says nothing, you should provide log errors from your server

**Comment by ghost** [comment]
[Tue Feb 19 10:57:56.672810 2019] [proxy_fcgi:error] [pid 1187:tid 140337538352896] [client xxxxx] AH01071: Got error 'PHP message: PHP Warning:  Uncaught Symfony\\Component\\Debug\\Exception\\ContextErrorException: Warning: require_once(/home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/vendor/autoload.php): failed to open stream: No such file or directory in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php:38\nStack trace:\n#0 /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php(38): require_once()\n#1 /home/admin/domains/XXXXXX.pl/public_html/classes/Dispatcher.php(485): include_once('/home/admin/dom...')\n#2 /home/admin/domains/XXXXXX.pl/public_html/XXXXXXadmin/index.php(99): DispatcherCore->dispatch()\n#3 {main}\n  thrown in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php on line 38\nPHP message: PHP Fatal error:  DispatcherCore::main(): Failed opening required '/home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/vendor/autoload.php' (include_path='/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/pear_exception:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/console_getopt:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/pear-core-minimal/src:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/archive_tar:.:/usr/local/php71/lib/php') in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php on line 38\n', referer: https://XXXXXX.pl/XXXXXXadmin/index.php/configure/advanced/performance/?_token=jTrvH6dC2GqIiIQNu3RDs_Vm4RE9t91gcJH4TeG9FbY

**Comment by kpodemski** [comment]
your 1.7.5 installation was previously updated from 1.6 maybe?

**Comment by ghost** [comment]
Nope. Pure fresh.

**Comment by kpodemski** [comment]
cc @Quetzacoalt91

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

In my case, I did not manage to reproduce the issue with PS1.7.5.0.
The 1-click upgrade is successfully installed
https://drive.google.com/file/d/10css7c52gtcUQ7M8ScrOK__zAmWyiebL/view
The version PS1.7.5.1 will be available for the upgrade today.
Did you installed the upgrade module from the Catalog module page?
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by Quetzacoalt91** [comment]
> [Tue Feb 19 10:57:56.672810 2019] [proxy_fcgi:error] [pid 1187:tid 140337538352896] [client xxxxx] AH01071: Got error 'PHP message: PHP Warning: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require_once(/home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/vendor/autoload.php): failed to open stream: No such file or directory in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php:38\nStack trace:\n#0 /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php(38): require_once()\n#1 /home/admin/domains/XXXXXX.pl/public_html/classes/Dispatcher.php(485): include_once('/home/admin/dom...')\n#2 /home/admin/domains/XXXXXX.pl/public_html/XXXXXXadmin/index.php(99): DispatcherCore->dispatch()\n#3 {main}\n thrown in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php on line 38\nPHP message: PHP Fatal error: DispatcherCore::main(): Failed opening required '/home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/vendor/autoload.php' (include_path='/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/pear_exception:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/console_getopt:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/pear-core-minimal/src:/home/admin/domains/XXXXXX.pl/public_html/vendor/pear/archive_tar:.:/usr/local/php71/lib/php') in /home/admin/domains/XXXXXX.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php on line 38\n', referer: https://XXXXXX.pl/XXXXXXadmin/index.php/configure/advanced/performance/?_token=jTrvH6dC2GqIiIQNu3RDs_Vm4RE9t91gcJH4TeG9FbY

It seems you got the module from `git clone`. You need to run `composer install` to get the dependencies and the autoloader.

**Comment by khouloudbelguith** [comment]
@PrestaShark, the issue is fixed?
Can I close the ticket?
Thanks!
