### ISSUE TITLE
Adding a Cart Rule problem - Prestashop 1.7.4.2

### ISSUE THREAD

**Issue by unicomprocom** [PrestaShop/PrestaShop#12624]
We have a problem with the Cart Rule on Prestashop 1.7.4.2. when we add a cart rule.

Adding to cart does not work when you enable any cart rule and the cart page loads long then we have an "Internal Server Error" problem

We tried to do a debogging, we found that there is a blogging at the line 

`if ($ cart_rule-> checkValidity ($ context, false, false)) {`

at line 1554 of the file classes/CartRule.php

Do you know the origin of this problem ?

thank you

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

What is the exact configuration did you used for this cart rule( with/without code, free shipping/ percent discount,...)?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by unicomprocom** [comment]
Thank you, 

For Cart Rule, we have this problem with all config (with/without code, free shipping/ percent discount,...)

this is our config :

the website is hosted by ovh
Apache
PHP : 7.1.25
Memory limit: 512M
Maximum execution time: 300
Max size for sending files: 128M

the debug mode show this message after a a long loading

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request

OVH error log :

[Tue Feb 19 16:08:24 2019] [error] [client x.x.x.x] [host boutique.yyyyyy.com] (104)Connection reset by peer: AH10143: FastCGI: comm with server "/homez.437/yyyyyyclc/boutique/index.php" aborted: read failed, referer: http://boutique.yyyyyy.com/fr/panier?action=show
[Tue Feb 19 16:08:24 2019] [error] [client x.x.x.x] [host boutique.yyyyyy.com] AH10149: FastCGI: incomplete headers (0 bytes) received from server "/homez.437/yyyyyyclc/boutique/index.php", referer: http://boutique.yyyyyy.com/fr/panier?action=show
[Tue Feb 19 16:08:24 2019] [error] [client x.x.x.x] [host boutique.yyyyyy.com] AH10157: FastCGI: An error happend on Fastcgi processing, fallback to CGI, referer: http://boutique.yyyyyy.com/fr/panier?action=show
[Tue Feb 19 16:08:52 2019] [error] [client x.x.x.x] [host boutique.yyyyyy.com] End of script output before headers: index.php, referer: http://boutique.yyyyyy.com/fr/panier?action=show

* javascript console log : no error

ps: for information, this shop has been migrated from version 1.6 to version 1.7.4.2 through various stages a year ago and we did not test before this feature of cart rule. When activated this time, it generated this problem

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

About this error:

`Connection reset by peer: mod_fcgid: error reading data from FastCGI server`, it is a server issue, have you tried to contact your host about this?
Thanks to check with them & feedback.

**Comment by unicomprocom** [comment]
Hi,

There is no relationship between the 2 problems according to the supplier.

As I told you, the blogging is at the level of the function "if ($ cart_rule-> checkValidity ($ context, false, false)) {" which is not working. I put a log message in the checkValidity function, and the script does not run this function. I do not now why !

if i comment this code `if ($cart_rule->checkValidity($context, false, false)) {
                        $context->cart->addCartRule($cart_rule->id);
                    }`  there is no error

**Comment by khouloudbelguith** [comment]
Hi @wajingdev,

It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.4.2
Thanks to check if there are missing columns to your database schema.
You can find the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by unicomprocom** [comment]
I managed to fix the problem, I deactivated the different non-prestashop modules and some Prestashop modules and I reactivate them.

and as weird there is no problem !

Thank you Khouloud

**Comment by khouloudbelguith** [comment]
@wajingdev, I'm glad that your issue is solved.
Feel free to open a new one when needed.
Thanks!
