### ISSUE TITLE
1: Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Van-peterson** [PrestaShop/PrestaShop#12637]
I had the following error at step 6 while trying to install PrestaShop 1.7.6.* in localhost using Xampp

**Une erreur est survenue durant l'installation...**
Vous pouvez utiliser les liens à gauche pour revenir aux étapes précédentes, ou redémarrer l'installation en cliquant ici.

1: Warning: Invalid argument supplied for foreach()

**Steps to reproduce the behavior:**

1 - Choix de la langue
2 - Acceptation des licences
3 - Compatibilité système
4 - Informations
5 - Configuration du système
6 - Installation de la boutique (Showing error)

I had the error at step 6

**Additionnal information**
PrestaShop version: 1.7.6.*
PHP version: 7.2.12

**Comment by khouloudbelguith** [comment]
Hi @Van-peterson,

Did you clone the project from GitHub?
https://github.com/PrestaShop/PrestaShop
This is not a stable version.
I tried with develop Branch (1.7.6.0 => OK).
I attached a video record.
https://drive.google.com/file/d/1XJPa_LfJYTd373YD77yEpXcPsKG1PV8l/view
Thanks to check & feedback.

**Comment by Van-peterson** [comment]
Thank you a lot @khouloudbelguith 
Now I clone the project from GitHub
And I have the develop Branch (1.7.6.0).
It works great, Thank you.

**Comment by khouloudbelguith** [comment]
@Van-peterson, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
