### ISSUE TITLE
npm run dev isn't working

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#12639]
**Describe the bug**
npm run dev isn't working

**To Reproduce**
1. Go to admin-dev/themes/new-theme/
2. Launch npm run dev

**Comment by marionf** [comment]
@PierreRambaud

**Comment by PierreRambaud** [comment]
Waiting for feedback here: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/147

**Comment by PierreRambaud** [comment]
Close, we revert to an old webpack version.

**Comment by matks** [comment]
@PierreRambaud I think `npm run watch` neither 🤔

**Comment by PierreRambaud** [comment]
I also add a `npm run dev` alias when I revert. `dev` command was introduce with webpack 4
