### ISSUE TITLE
Cant var_dump in hookdisplayProductExtraContent

### ISSUE THREAD

**Issue by polo195pl** [PrestaShop/PrestaShop#12631]
**Describe the bug**
Cant var_dump or print_r in hook displayProductExtraContent. When i try all data didnt show. 

**To Reproduce**
1. Create basic module add set hookdisplayProductExtraContent($params)
2. in tpl try @var_dump or print_r
3. Dont see anything from this hook

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0/7.1/7.2/7.3

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

I tried with this module
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2883752/mymodule.zip)
and it is OK.
I tried with `print_r` & the `var_dump` in the php file 
![image](https://user-images.githubusercontent.com/16067358/53078738-2a21c980-34f5-11e9-90c5-d6c6e72bf67c.png)
Thanks to check & feedback.

**Comment by polo195pl** [comment]
Well read it my issue again. Add template to this hook and try in var_dump or print_r any variable in template assigned for this hook from module.

**Comment by khouloudbelguith** [comment]
@polo195pl, thanks for your feedback.
Could you please provide me a demo module to check the issue.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by polo195pl** [comment]
I will write today

**Comment by khouloudbelguith** [comment]
@polo195pl, Thanks!
Waiting for your feedback.

**Comment by Marcin-J-PL** [comment]
Template should be in Smarty or Twig. In Smarty you shoulde use {$var|@print_r} in Twing i'm not sure.  Also in smarty you can use {debug}

[`PrestaShop DevDocs`](https://devdocs.prestashop.com/1.7/modules/creation/displaying-content-in-front-office/)

**Comment by polo195pl** [comment]
@marcin-jaworski i know...

**Comment by khouloudbelguith** [comment]
@polo195pl, I just successfully tried to install your custom module without errors with PS1.7.4.4.
I just sent you an email to get more details.
Thanks!

**Comment by polo195pl** [comment]
@khouloudbelguith check mail ;)

**Comment by khouloudbelguith** [comment]
@polo195pl, thanks for your feedback.
In my case, with your custom module installed in the shop PrestaShop 1.7.4.4, I added the `@var_dump` and `print_r` => they are well displayed.
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
![image](https://user-images.githubusercontent.com/16067358/53155843-3a51ab80-35be-11e9-889b-e95d2e11203b.png)

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
