### ISSUE TITLE
1-Click Upgrade missing 1.7.5.1

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#12633]
In PS "1-Click Upgrade" module
Latest official version for minor channel.: 1.7.5 stable - (1.7.5.0)

So not possible to upgrade to the new 1.7.5.1 ?

**Comment by khouloudbelguith** [comment]
Hi @thbl,

We just released a new version for the module 1-click upgrade v4.6.0.
So the new version PrestaShop 1.7.5.1 will be available today for the upgrade.
Thanks!

**Comment by thbl** [comment]
I have v4.6.0, but it still says 
Latest official version for minor channel.: 1.7.5 stable - (1.7.5.0)

**Comment by khouloudbelguith** [comment]
@thbl, yes.
the PS1.7.5.1 is not published yet for the upgrade.
It will be available in a few hours.
Thanks for your understanding!

**Comment by Quetzacoalt91** [comment]
The version 1.7.5.1 is now available for upgrade.

**Comment by thbl** [comment]
Thanks
