### ISSUE TITLE
Bulk actions don't exist in the currencies page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12648]
**Describe the bug**
In the BO => International => Localization => currencies tab, the Bulk actions don't exist.
It could be an improvement issue to add to the currencies page like the languages page.
Currencies page
![image](https://user-images.githubusercontent.com/16067358/53107766-121e6a00-3536-11e9-8205-4bfeab05e13f.png)

Languages page
![image](https://user-images.githubusercontent.com/16067358/53107748-07fc6b80-3536-11e9-898b-4974c5d95606.png)

**Additionnal information**
PrestaShop version: develop / 1.7.5.0 / 1.7.4.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
ping @marionf @colinegin what do you think?
Thanks!

**Comment by matks** [comment]
This might be because removing a currency is a very impacting action. It has huge consequences.

**Comment by colinegin** [comment]
So what's your opinion @matks ?

**Comment by matks** [comment]
"With great power comes great responsibility" 😉 you need to decide if you want to allow users to perform a heavy process on bulk, or you would rather have the user click on each language and perform the action for each of them (so we're sure he did not select something by accident).

**Comment by MatShir** [comment]
> This might be because removing a currency is a very impacting action. It has huge consequences.

I quite agree with you, since a merchant doesn't add currencies every day. 
Thanks for your suggestion but I close the issue.
