### ISSUE TITLE
Quick view doesnt work after upgrade 1.7.5.0 to 1.7.5.1

### ISSUE THREAD

**Issue by jeeece** [PrestaShop/PrestaShop#12649]
Hi,

After upgrading my prestashop from 1.7.5.0 to 1.7.5.1, quick view does not work anymore.

Respose is 500.

![capture](https://user-images.githubusercontent.com/14275975/53126732-1a3fcf00-3561-11e9-9329-4a5533856cd4.JPG)

I dont have this problem on fresh installation 1.7.5.1

**Comment by Tomskor** [comment]
Turn on default theme, and turn off additional modules, may be caused this error.

**Comment by khouloudbelguith** [comment]
Hi @jeeece,

You need to enable debug mode in your store and debug request which is sent for "Quick view" in your browser, using DevTools, so:

1. enable debug mode
2. go to the Home page
3. open up developer tools
4. go to Network tab
5. Click on Quick view
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by jeeece** [comment]
Hi @khouloudbelguith 

Preview tab is blank and i have this on response tab :
//

**Comment by khouloudbelguith** [comment]
@jeeece, you should click the red request in the network, which is in your case "Post..... =Product 500"
Then you click on the preview tab.
Did you enable the debug mode? is there any exception displayed?
Thanks!

**Comment by jeeece** [comment]
@khouloudbelguith when I activate debug mode, on home page I don't have any debug line on bottom of my page like in back office is it normal ?

**Comment by jeeece** [comment]
Ok, i think problem don't provide from quick view but the product page! I have this with debug mode activate when i try to going on any product page :
///

**Comment by khouloudbelguith** [comment]
Hi @jeeece,

Did you the default theme provided by PrestaShop?
Thanks!

**Comment by jeeece** [comment]
Ok, i've fixed this error. It was a module "pshreflang" which was not compatible with 1.7.5.1. Just disabled it don't fix the issue, but when i uninstall it, that's ok !

**Comment by khouloudbelguith** [comment]
Hi @jeeece, 

Thanks for your feedback. 
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
