### ISSUE TITLE
ERROR 500 in many BO tabs after upgrade 1.7.5.1

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#12652]
**Describe the bug**
Can't go to cuz ERROR 500:
- invoices
- module catalog
- payment 
- payment preference
- translate
-

**To Reproduce**
1. Go to module catalog

**Screenshots**
![screencapture-tomskor-pl-admin850kwyszj-index-php-improve-modules-manage-2019-02-21-10_20_51](https://user-images.githubusercontent.com/42567245/53158084-1d6ba700-35c3-11e9-83b3-d9c1ac010e9f.jpg)
![screencapture-tomskor-pl-admin850kwyszj-index-php-improve-modules-manage-2019-02-21-10_20_43](https://user-images.githubusercontent.com/42567245/53158093-22305b00-35c3-11e9-8106-161163ef74db.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.13

Realy is so hard relase ONE usefull and working update?

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

You have an issue with the `inixframe` module.
Could you please try to disable it, clear cache, it could be not compatible with PS1.7.5.1.
Thanks to check & feedback.

**Comment by Tomskor** [comment]
@khouloudbelguith how I can disable it, cuz can't enter on modules so I can't manage them
I clear cache from BO thats enough? or I must on ftp delete cache?

**Comment by khouloudbelguith** [comment]
@Tomskor, ok.
So, you need to go to your Project_Folder/modules/, search for the `inixframe` folder & try to rename it.
You can clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by Tomskor** [comment]
Ok I almost work, propably lost "iniframe" what exactly is this module? becouse I can't find him now, what is does?

**Comment by khouloudbelguith** [comment]
@Tomskor,
As I can see in your exception, it is a module named "inixframe"
![image](https://user-images.githubusercontent.com/16067358/53159536-59ecd200-35c6-11e9-8815-54a4552ad9cb.png)

**Comment by wordliner** [comment]
You need to change displayInformation() function from private/protected tu public

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
