### ISSUE TITLE
1 Click Upgrade Fail 1.7.2 to 1.7.5

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#12650]
**Describe the bug**

After Upgrade get this error in console and in PHP Log:

[INTERNAL] /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php line 102 - Error: Call to undefined method Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass::setHotPathEvents() #0 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): Symfony\Bundle\FrameworkBundle\FrameworkBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(148): Symfony\Component\HttpKernel\Kernel->boot() #5 /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(135): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() #6 /src/PrestaShopBundle/Service/Database/Upgrade.php(40): Symfony\Bundle\FrameworkBundle\Console\Application->add(Object(PrestaShopBundle\Command\UpdateSchemaCommand)) #7 /modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): PrestaShopBundle\Service\Database\Upgrade->addDoctrineSchemaUpdate() #8 /modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(54): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #9 /modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.2.4') #10 /modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #11 /admin_17ledh/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #12 {main}

184081h55m59│000|Feb 21 08:23:56 vw04 ool www: PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass::setHotPathEvents() in /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:102#012Stack trace:#012#0 /vendor/symfony/symfony/src/Symfony/Component/HttpKer│

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Did you use the 1-click upgrade v4.6.0?
What is the exact version PrestaShop 1.7.2, did you installed before the upgrade?
Thanks!
