### ISSUE TITLE
fatal error in module file theme 

### ISSUE THREAD

**Issue by iramita** [PrestaShop/PrestaShop#12651]
Hello,
I want to change copyright year in footer, but i have problem error.

[PrestaShop] Fatal error in module file :/home/u392606586/domains/scallopmode.net/public_html/modules/ntthemeeditor/ntthemeeditor.php:
Uncaught Error: Access to undeclared static property: Validate::$field in /home/u392606586/domains/scallopmode.net/public_html/modules/ntthemeeditor/ntthemeeditor.php:807 Stack trace: #0 /home/u392606586/domains/scallopmode.net/public_html/controllers/admin/AdminModulesController.php(867): NtThemeeditor->getContent() #1 /home/u392606586/domains/scallopmode.net/public_html/controllers/admin/AdminModulesController.php(1116): AdminModulesControllerCore->postProcessCallback() #2 /home/u392606586/domains/scallopmode.net/public_html/classes/controller/Controller.php(178): AdminModulesControllerCore->postProcess() #3 /home/u392606586/domains/scallopmode.net/public_html/classes/Dispatcher.php(367): ControllerCore->run() #4 /home/u392606586/domains/scallopmode.net/public_html/yvkev7b0hxurgykr/index.php(58): DispatcherCore->dispatch() #5 {main} thrown

help me, please..
Thank's

Ira Mita
![error](https://user-images.githubusercontent.com/47849627/53157932-1e1d3100-35f5-11e9-9c46-f34a9475e579.JPG)

**Comment by khouloudbelguith** [comment]
Hi @iramita,

You have an issue with the `ntthemeeditorAs` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by iramita** [comment]
thank you @khouloudbelguith, I will contact them
