### ISSUE TITLE
Cannot Use Form Helper in hook DisplayAdminProductsExtra

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#12657]
Hi

Occurs in Prestashop 1.7.x

When attempting to use the Helper class form in the "DisplayAdminProductsExtra" hoook smarty returns the following error:

Unable to load template 'file:helpers/form/form.tpl

But the same code will work fine elsewhere *such as in the main getContent method of a module.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Could you please provide me a demo module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
