### ISSUE TITLE
Conflict in cart numbers

### ISSUE THREAD

**Issue by Nutripure** [PrestaShop/PrestaShop#12669]
Hello

we have updated to 1.7.5.0, we are facing problems with validated payment information returns, for paypal and credit cards paiements (systempay Caisse Epargne). Prestashop does not retrieve the validated payment information. This information is clearly visible in the server log. After several attempts, the information goes into fatal error and the order doesn't appear on the back office.

The problem occurs on approximately 15% of the order

Logs in BO are :

PaymentModule::validateOrder - Secure key does not match

PaymentModule.php -> ligne 253

if ($secure_key !== false && $secure_key !=
$this->context->cart->secure_key) {
PrestaShopLogger::addLog('PaymentModule::validateOrder -
Secure key does not match', 3, null, 'Cart', (int) $id_cart, true);
die(Tools::displayError());

This mistake is generated in this file (line 253)
- we set up an email to check the secure key. On validated orders, key are the same. On bugged orders, we will verify that keys are differents. this problem only occurs 10% of the orders.
-  we never deleted carts from the database
- Cache folder was removed manually.

This problem occurs for systempay and paypal. 
The problems occurs in prestashop file PaymentModule.

After investigating, I found that there is a conflict between the cart number and the order number sent to the paiement module with are not equal when it does bad.

Normally, cart number is set as the order number in the payment module. When the payment is ok, this number is checked in prestashop BO :

* if cart number and payement number are the same (the two secury keys are also the same), order is validated and payment number is transformed in BO order in prestashop BO
* if cart number and payment number are not the same (the two security keys are not the same), order is not validated.
  In this last case, when looking into the payment information, I found that payement is attributed to the owner of a wrong cart : it is attributed to the cart which number is corresponding with the payement number (an old abandonned cart).
  It make me think that neither two cart have the same number or there are two cart registers that are not matching.

I have to say that the problems occurs much more frequently since last thursday, when I upgraded from 17.2.4 to 1.7.5

thanks for your help
Florent

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment]
Hi @Nutripure,

As described in your last issue: #12618, 
Me & @marionf, we don't manage to reproduce the issue with PS1.7.5.0 & PayPal module.
So, could you please provide us the exact version PayPal did you & the exact version systempay did you use also?
Did you use some modules to sign in from the FO?
Thanks!

**Comment by Nutripure** [comment]
Hello
we use Paypal v4.4.2 and systempay v1.11.0. There are up to date.
No additional module is used to log in. 
Florent

**Comment by khouloudbelguith** [comment]
@Nutripure, thanks for your feedback.
To make sure, did you made an upgrade before from PS1.3 / PS1.4 to PS1.7, or did you installed a fresh install PS1.7.2.4?
To make an upgrade from PS1.7.2.4 to PS1.7.5.0, what the exact tools did you used to do the upgrade?
Thanks!

**Comment by Nutripure** [comment]
It was as fresh instal from 1.7.2.4.

We started with a fresch install of the version "PrestaShop v 1.7.2.4 Stable" and then we
updated directly to the version "PrestaShop v 1.7.5.0 Stable".

We use the official module "1 click Upgrade" which is up to date.

We detected that some carts were allocated to the wong customers, which generates when
the return of payment a difference between the 2 keys).

We have disabled OPcache in PHP which could be the source of problem.

**Comment by khouloudbelguith** [comment]
@Nutripure, did you use the MailChimp module?
Thanks!

**Comment by Nutripure** [comment]
Yes I do.
We use "Mailchimp Integration v1.1.4" and "Mailchimp Sync v3.2.4".
Thanks

**Comment by khouloudbelguith** [comment]
@Nutripure, the MailChimp Integration is causing this issue.
As described in the previous ticket: http://forge.prestashop.com/browse/BOOM-5486
I manage previously to reproduce the issue, the MailChimp Module added products to new customer's basket by default.
MailChimp isn't developed by PrestaShop.
You should contact the developer here:  https://addons.prestashop.com/en/contact-us?id_product=26957
Thanks!

**Comment by drc0** [comment]
@Nutripure we are facing asimilar issue, we are using braintree module https://addons.prestashop.com/it/pagamento-carta-credito-wallet/46833-ufficiale-di-braintree.html and mailchimp module, in the error logs I see an error " PaymentModule::validateOrder - Secure key does not match " but on braintree the transaction has been settlet, on prestashop the order was never market as completed, also I only see a pending cart and not an order for that customer.

have you been able to solve this issue?

**Comment by ballashop** [comment]
Hi @khouloudbelguith 
we have the same issue:
"PaymentModule::validateOrder - Secure key does not match"
I can't access the link to see it.
As described in the previous ticket: http://forge.prestashop.com/browse/BOOM-5486
Thanks

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

This issue is currently closed, can you open a new one with more information about your configuration.

Thank you!

**Comment by Betafer** [comment]
Same problem, but without mailchamp.
Prestashop 1.7.6.8

Maybe but i'm not sure the problem is correlated to minimum order amount 

Back office logs: 

Errore (3) | PaymentModule::validateOrder - Secure key does not match
-- | --

**Comment by powolnymarcel** [comment]
Hello,

Also having this issue also on Prestashop 1.7.6.8.
Can"t reproduce the end user scenario so far, but happened several times over last few month

**Comment by uruk-hai-21** [comment]
Nothing?

**Comment by leseeb22** [comment]
Bonjour, j'ai le même problème sans module mailchimp
Prestashop 1.8.8.2 payzen v1.15.3 
moi aussi c'est aléatoire 
Quelq'un à trouvé une solution ?
Merci
