### ISSUE TITLE
"Generate RTL stylesheet" cannot be enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12661]
**Describe the bug**
In the BO => Design => Theme & Logo page, in the "Adaptation to Right-to-Left languages" section, when we try to enable the "Generate RTL stylesheet" button & click same, a green alert is displayed but the button is always disabled.
In the FO, the theme is adapted to RTL.
The issue is only with button, it should be enabled but, it is disabled.

**To Reproduce**
1. Go to BO => International => Translations => Add a RTL language (Persian for example)
2. Go to BO => Design => Theme & Logo page, in the "Adaptation to Right-to-Left languages" section
3. Enable the "Generate RTL stylesheet" option
4. Click Save
5. Scroll down to the button again => it is disabled
**Screenshots**
https://drive.google.com/file/d/1uK-hmzv_PCyc2Jkg62Gq0oN0MrN1o7SR/view
![image](https://user-images.githubusercontent.com/16067358/53176186-d8109f00-35ed-11e9-866a-66b1fd260a3e.png)

**Additionnal information**
PrestaShop version: develop (1.7.6.0)
PHP version: 7.1

**Comment by marionf** [comment]
When the page is refreshed, the button comes back to No anyway because it's not a parameter saved, it's one time if you want to regenerate RTL stylesheet
