### ISSUE TITLE
[PS 1.7.3.3] duplicate invoice number

### ISSUE THREAD

**Issue by Alexandre17220** [PrestaShop/PrestaShop#12660]
Hi,

I am a developper and my customer have a problem with Prestashop.
In fact, my customer have a big shop and many invoice have same number...
So when I look here : 
classes/order/order.php
Function : 
setLastInvoiceNumber

I see "SELECT (MAX(`number`) + 1) AS new_number" ..very bad idea if you have many order at the same time..
This problem exists in all version of Prestashop and on all shop over Prestashop.

The big problem is that already an auto-incremented field in ps_order_invoice, so I cannot make my own field and use it like it:

`public static function setLastInvoiceNumber($order_invoice_id, $id_shop) {
        if (!$order_invoice_id) {
            return false;
        }

        $sql = 'UPDATE `'._DB_PREFIX_.'order_invoice` SET number =number_unique';
        $sql .= ' WHERE `id_order_invoice` = '.(int)$order_invoice_id;

        return Db::getInstance()->execute($sql);
}`
Any idea for that ?

Thanks,

PrestaShop version: 1.7.3.3
PHP version: 7.1.5
MariaDB : 5.5.52

**Comment by khouloudbelguith** [comment]
Hi @Alexandre17220,

Have you the same issue with this ticket: #11115?
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11115

**Comment by thantadis** [comment]
Its not the same issues. Because #11115 talk about duplicate order reference and this issue was open for duplicate invoice number

Do you have a fix ?

**Comment by Alexandre17220** [comment]
yes, override class Order, and function setLastInvoiceNumber...

**Comment by iamtend0** [comment]
@Alexandre17220 hello, could you please share your fix? I have the same problem for duplicate order invoice + order reference.

-- 

I found it here: https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-466388153 thank you

**Comment by steefv911** [comment]
Please re open this topic. In presta 1.7.8.5 this issue still exist.

**Comment by Alexandre17220** [comment]
> Please re open this topic. In presta 1.7.8.5 this issue still exist.

[matks](https://github.com/matks) commented [on May 11, 2021](https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-838056954):
> @Alexandre17220 😄 if the race condition issue is important for a PrestaShop user, he might be willing to pay you for this work.
> 
> if nobody's willing to pay for it... I guess it's not an issue so important 😄 ?

**Comment by steefv911** [comment]
Sorry I do not get the point. 
We have multiple order placed on the same date-time, a few seconds apart. There is unique order number and unique order reference but same order invoice number.
