### ISSUE TITLE
A problem with a new added language while he was chosen in FO

### ISSUE THREAD

**Issue by AdrianStolarski1988** [PrestaShop/PrestaShop#12673]
**Describe the bug**
After entered new language in BO, the user who chose this language displays an error (error 500 without disabled debug mode)

**To Reproduce**
1. Go to Localization > Language 
2. Click on add new language and fill required fields like:
 - Name : Spanish 
 - ISO code: es
 - Language code: es-ES
 - Date format: Y-m-d
 - Date format (full) : Y-m-d H:i:s
And I save form
3. I go to main site in FO
4. I change language to Spanish
5. After change language appears php stacktrace 

**Screenshots**
1. filled form
![zaznaczenie_514](https://user-images.githubusercontent.com/26248031/53246305-9eed3300-36b0-11e9-9b92-4bac7da2efe0.jpg)
2. Result of change language to Spanish
![zaznaczenie_515](https://user-images.githubusercontent.com/26248031/53246337-b2000300-36b0-11e9-9f7c-d2a5dd23d160.jpg)
3. Probable couse of bug - not filled locale column in table ps_lang: 
![zaznaczenie_516](https://user-images.githubusercontent.com/26248031/53246583-67cb5180-36b1-11e9-8947-651e950bfa46.jpg)

**Additionnal information**
PrestaShop version:1.7.6.0
PHP version: 7.1
branch: develop

**Comment by khouloudbelguith** [comment]
Hi @AdrianStolarski1988,

Thanks for your report.
I manage to reproduce the issue with the develop branch.
PS1.7.5.1 => OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
