### ISSUE TITLE
Product miniature - smarty variables stopped work

### ISSUE THREAD

**Issue by flexcodenet** [PrestaShop/PrestaShop#12670]
**Describe the bug**
I've updated prestashop from 1.7.4.3 or 1.7.4.4 to 1.7.5, and later 1.7.5.1.
Now smarty on product miniature don't show nothing. For example: 

{if $product.has_discount}{/if} - dont work
{$product.has_discount|@print_r} - display "1"
{$product.id_category_default} - display nothing
{$product.id_category_default|@print_r} - display "1"

File located in "\themes\templatename\templates\catalog\_partials\miniatures\product.tpl

But while we check this file "themes\templatename\templates\catalog\product.tpl" - all work correct, this bug i found only on listing.

**To Reproduce**
I don't how to reproduce it. Before update, all work correct. After update prestashop, smarty variables stopped work in product miniature.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![ps2](https://user-images.githubusercontent.com/47887928/53239816-4ceee200-369d-11e9-825a-b37456fef937.png)
![ps1](https://user-images.githubusercontent.com/47887928/53239817-4ceee200-369d-11e9-8d07-b9286aa0afc3.png)

**Additionnal information**
PrestaShop version:   @#1.7.5.1
PHP version: 7.2.11

**Comment by khouloudbelguith** [comment]
Hi @flexcodenet,

Have you tried to contact the theme author about this issue?
Thanks to check with hem & feedback.

**Comment by flexcodenet** [comment]
I use code from classic theme in miniature. I'm author. I only add new class & css. On 1.7.4.4 work all correct. Problem is smarty return "1" or nothing.

**Comment by flexcodenet** [comment]
Hello. I found the problem. Fixed. Please close issue.

I change:
if $product.id_customization =! NULL
to
if $product.id_customization != NULL

**Comment by khouloudbelguith** [comment]
@flexcodenet, thanks for your feedback.
I close the ticket, feel free to open a new one when needed.
Thanks!
