### ISSUE TITLE
combinations not shown in product sheet after upgrade from 1.7.4.4 to 1.7.5.1

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#12677]
Hi, 

after upgrade from 1.7.4.4 to 1.7.5.1 in product sheet the combinations ar not more shown:

![image](https://user-images.githubusercontent.com/44971218/53254362-820e2b00-36c3-11e9-9add-d290fdd4316c.png)

but they are available for order in FO:

![image](https://user-images.githubusercontent.com/44971218/53254447-ac5fe880-36c3-11e9-8f56-24e3cf3671df.png)

What can I do to fix this? 

Using php 7.2.1

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

What is the exact 1-click upgrade did you use?
Have you any errors during the upgrade?
Thanks!

**Comment by didi-2018** [comment]
version 4.6.0
only that cache folder could´nt be emptied

**Comment by khouloudbelguith** [comment]
@didi-2018, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by didi-2018** [comment]
this is what I have in log folder:
![image](https://user-images.githubusercontent.com/44971218/53255827-c3540a00-36c6-11e9-8581-5f5555e1c1b1.png)
which one do you need?

**Comment by khouloudbelguith** [comment]
@didi-2018, dev.log file & prod.log file, because they are generated today.
Thanks!

**Comment by didi-2018** [comment]
or do you need something from here:
![image](https://user-images.githubusercontent.com/44971218/53255959-15952b00-36c7-11e9-9f3c-cac2e30f0b95.png)

I am sorry but I don´t know what you need

**Comment by didi-2018** [comment]
how can I submit it as file?

**Comment by khouloudbelguith** [comment]
@didi-2018, you can follow this link: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
It will help you to get the right information.
You can attach a file by clicking on this 
![image](https://user-images.githubusercontent.com/16067358/53256165-83d9ed80-36c7-11e9-8e77-19b7d26ed27d.png)

Thanks!

**Comment by didi-2018** [comment]
file type is not supported

**Comment by didi-2018** [comment]
[dev.log](https://github.com/PrestaShop/PrestaShop/files/2894852/dev.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/2894853/prod.log)

**Comment by didi-2018** [comment]
And I have other problems too:
![image](https://user-images.githubusercontent.com/44971218/53257369-3743e180-36ca-11e9-84dc-e2b1ef760bd3.png)

![image](https://user-images.githubusercontent.com/44971218/53257436-6a867080-36ca-11e9-8bb9-693f8d95382a.png)

**Comment by khouloudbelguith** [comment]
@didi-2018, did you use a different theme?
In your log file, I found the "appagebuilder" module, in a similar [issue](https://github.com/PrestaShop/PrestaShop/issues/12409#issuecomment-465457611), I found that his theme is not yet compatible with PS1.7.5.
Thanks to check & feedback.
About your last screenshot, you need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks!

**Comment by didi-2018** [comment]
The curious thing is that there are no problems in my shop copy
![image](https://user-images.githubusercontent.com/44971218/53257909-92c29f00-36cb-11e9-843a-24bfd63e2278.png)
![image](https://user-images.githubusercontent.com/44971218/53257941-a1a95180-36cb-11e9-8bf9-e9af9e37e965.png)
![image](https://user-images.githubusercontent.com/44971218/53257982-c1407a00-36cb-11e9-8c92-8c67860e268a.png)

My Hosting provider can´t find differences between copy und live shop. 

we are at a loss

**Comment by khouloudbelguith** [comment]
@didi-2018, strange thing.

Try to remove cache

```
 rm -fR var/cache/*

php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by didi-2018** [comment]
I cleared cache a few times and nothing happens. I think I have to go back to 1.7.4.4

**Comment by didi-2018** [comment]
I could find out more details:
![image](https://user-images.githubusercontent.com/44971218/53264899-1df86080-36dd-11e9-8170-c99b12c1ac1b.png)

**Comment by didi-2018** [comment]
I could find out more details. This file makes trouble in line 166
admin/themes/new-theme/public/main.bundle.js
![image](https://user-images.githubusercontent.com/44971218/53265539-cce96c00-36de-11e9-8ec2-d82d129a86c5.png)
![image](https://user-images.githubusercontent.com/44971218/53266076-0b335b00-36e0-11e9-937a-ed397954752f.png)

![image](https://user-images.githubusercontent.com/44971218/53267140-eb516680-36e2-11e9-9848-c25ca7875ce2.png)

![image](https://user-images.githubusercontent.com/44971218/53267291-484d1c80-36e3-11e9-844c-3384d6c1f8fd.png)

![image](https://user-images.githubusercontent.com/44971218/53267368-7599ca80-36e3-11e9-9497-bacf65beffed.png)

**Comment by didi-2018** [comment]
@kouloudbelguith do you have any suggestions?

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.1
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by didi-2018** [comment]
Hi, 

this could not be. On weekend I copied shopcopy folder to liveshop domain folder with the same database connected from shopcopy and I get the same errors. I hope you understand my bad english ;-)

**Comment by khouloudbelguith** [comment]
@didi-2018, and this issue occurs only on your live shop, in your shop copy, it is OK?

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check the difference between your server & your local.

**Comment by didi-2018** [comment]
thank you for your reply. Test are exactly the same.

Shopcopy:
![image](https://user-images.githubusercontent.com/44971218/53340827-3c8f6f00-390a-11e9-8e62-178ee471cb1f.png)
![image](https://user-images.githubusercontent.com/44971218/53340863-529d2f80-390a-11e9-9d74-719e4f6e4db5.png)
![image](https://user-images.githubusercontent.com/44971218/53340883-62b50f00-390a-11e9-82bf-c1da8d537ad2.png)
![image](https://user-images.githubusercontent.com/44971218/53340913-79f3fc80-390a-11e9-9094-24c5aa5fbaee.png)


liveshop:
![image](https://user-images.githubusercontent.com/44971218/53340955-8b3d0900-390a-11e9-8475-c9c0b2c853ed.png)
![image](https://user-images.githubusercontent.com/44971218/53340986-9d1eac00-390a-11e9-9780-48e04da8dbd2.png)
![image](https://user-images.githubusercontent.com/44971218/53341011-af004f00-390a-11e9-8748-ee844ff1fc6f.png)
![image](https://user-images.githubusercontent.com/44971218/53341031-bd4e6b00-390a-11e9-890f-8cedeebc1ded.png)


If I enable Debug Mode in liveshop (1.7.5.1) I get the following error:
![image](https://user-images.githubusercontent.com/44971218/53341121-f8e93500-390a-11e9-9e20-88ff934763ff.png)

**Comment by didi-2018** [comment]
Hi, my hosting uses "Google PageSpeed Module" on server. After I activated it again everything works now! This is really embarrassing! But maybe it helps someone else.

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks for your feedback.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by didi-2018** [comment]
Hi, no it is not prestashop module. It is a nginx server module! ;-)
