### ISSUE TITLE
Can´t access some sections and can´t delete Cache after Upgrade from 1.7.4.4 to 1.7.5.1

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#12674]
Hi, 
I just upgraded from 1.7.4.4 to 1.7.5.1 and I can´t access some sections like Catalog -> Articles. I only can access these sections with enable Debug. But I can only enable Debug in file. 
If I want to access some sections I get 500 ERROR. With Debud mode I can access without any error shown. 
And I get the following error if I try to delete cache:
![image](https://user-images.githubusercontent.com/44971218/53247783-85e68100-36b4-11e9-9eaa-1031fdd75767.png)

I am using php 7.2.1

Please contact me if you need more informations.

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

Thanks for your report.
This is a permission issue.
Thanks to edit the permissions access to the folder /Projet_Folder/cache/
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by didi-2018** [comment]
I have done that and I get the same Error:
![image](https://user-images.githubusercontent.com/44971218/53248584-52a4f180-36b6-11e9-9768-ec67c28fa189.png)

**Comment by didi-2018** [comment]
I now can access all areas ! Thank you! You can close it please! Have a nice weekend ;-)

**Comment by khouloudbelguith** [comment]
@didi-2018, since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!
