### ISSUE TITLE
Installation process does not change to language SPANISH 1.7.5.1

### ISSUE THREAD

**Issue by jesusruiz** [PrestaShop/PrestaShop#12680]
**Describe the bug**
When starting the installation process, even if the Spanish language is selected, the English language is still used.

**To Reproduce**
Start the installation process and select the Spanish language.

**Screenshots**
https://i.imgur.com/sa4DFFm.png

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.3.1

**Comment by khouloudbelguith** [comment]
Hi @jesusruiz,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1s8y7SXDZQLFmnfXyOyBOXZbpm0Dtw2WF/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@jesusruiz, PrestaShop is not compatible with PHP7.3 yet.
PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4/ PS1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

**Comment by jesusruiz** [comment]
Hello, khouloudbelguith:

Thank you for your feedback and the tests you have done ;)

In the video that you have recorded, I understand that the language you have selected is **Spanish from Mexico** (not **Spanish from Spain**), but in any case, I see that the language change correctly in the Spanish (Mexico) language. So I'm going to do other tests of the installation process because maybe the problem is in the version of PHP that I selected or in another cause.

If you want we can close the issue, while I do other tests.

Thanks and a gretting ;)

**Comment by khouloudbelguith** [comment]
@jesusruiz, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
