### ISSUE TITLE
BO manual order shows wrong shipping price (one product without changes)

### ISSUE THREAD

**Issue by json81** [PrestaShop/PrestaShop#12682]
Bug in Back Office manual order. Shipping price will show the wrong amount and the summary will be wrong. When creating the order everything recalculates and shipping cost will be correct according to the chosen carrier.

Can be reproduced in version 1.6.1.23 and 1.7.4.2.

How to reproduce: 
1) Create two delivery options with different amounts, none with free shipping (use different amount to see the bug). Take notice of the Position ID (1 and 2 in my case).
2) Go to Shipping -> Preferences and set the default carrier to the the carrier with highest ID (4 in my case)
3) Create a new manual order in the back office (Orders -> Add new order)
4) Choose customer and add one product
5) Scroll down to "Shipping"-part. "Delivery option" has the carrier with the highest position but the "Shipping price" shows the price of the default carrier.
6) If you add one more product to the cart, shipping price will be corrected. If you create the order, shipping price will be recalculated to the price of the carrier in the "Delivery option" box.
![wrong shipping price](https://user-images.githubusercontent.com/8902665/53276184-5b211a80-36fe-11e9-9b3c-f2da0cd1ac3a.jpg)
![wrong shipping price2](https://user-images.githubusercontent.com/8902665/53276199-66744600-36fe-11e9-987f-ba4f91b6ffc7.jpg)

**Comment by khouloudbelguith** [comment]
Hi @json81,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/53327026-3cca4300-38e7-11e9-8320-a478b3d50ead.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by kijamve** [comment]
Maybe this PR https://github.com/PrestaShop/PrestaShop/pull/14117 fix this

**Comment by colinegin** [comment]
@MatShir has this issue been fixed with the migration of create order page ?

**Comment by bc-devle** [comment]
Hello, still have this issue on 1.7.8.8

**Comment by MatShir** [comment]
The bug is fixed for PS 8.1.

**Comment by bc-devle** [comment]
Hi Mateo, any chance to get this on 1.7.8 ?

**Comment by MatShir** [comment]
The only possible fix for 1.7.8 is a critical bug or a security issue :/
