### ISSUE TITLE
Mail domen not work in preference

### ISSUE THREAD

**Issue by Goretsv** [PrestaShop/PrestaShop#12684]
My email provider require other mail domen in HELO answer,
but Swiftmailer ignore mail domen in PrestaShop Email setting

PrestaShop version: 1.7.5.1
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

Could you please provide me more details to reproduce your issue.
In the BO => Advanced Parameters => E-mail => you selected the option "Set my own SMTP parameters (for advanced users ONLY)"
So, you set a mail domain & Swiftmailer ignore mail domain in PrestaShop Email setting.
How did you check that it is ignoring the mail domain?
Thanks!

**Comment by Goretsv** [comment]
in mail server log.
To get work mail i must edit host in file AbstractSMTPTransport.php
(my email provider need specific host)

**Comment by Goretsv** [comment]
(i have this problem after upgrade from 1.6 to 1.7, in 1.6 work normal)

**Comment by khouloudbelguith** [comment]
@Goretsv, could you please provide us the exact error in your mail server log?
Did you make some fixes in the AbstractSMTPTransport.php, what is the exact changes?
Thanks!

**Comment by Goretsv** [comment]
Log: Expected response code 250 but got code "550", with message "550 Bad HELO - Host impersonating domain name [print-service.ua] "

(i fix for my SMTP setting)
 private function _lookupHostname()
    {
        if (!empty($_SERVER['SERVER_NAME']) && $this->_isFqdn($_SERVER['SERVER_NAME'])) {
            $this->_domain = [savo.in.ua];

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

In the BO => Advanced Parameters => Email, I set the `mail domain name`.
I check this value in the Database table ps_configuration & this value is well saved.
I attached a video record.
https://drive.google.com/file/d/1VOsCY3wRrCHTAbfzlXFfKt-f02Wyl4Jd/view
Thanks to check & feedback.

**Comment by Goretsv** [comment]
In database all correct.
mail domen must be id 422??
i have 

1197 | NULL | NULL | PS_MAIL_DOMAIN | mail.print-service.ua | 2016-08-18 09:45:01 | 2019-01-14 09:15:39
-- | -- | -- | -- | -- | -- | --

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

No, I tried with another shop & I have different id
![image](https://user-images.githubusercontent.com/16067358/53411528-006e1400-39c7-11e9-943b-96fc0296c3c1.png)
In your case, the value of "PS_MAIL_DOMAIN" is different from `[savo.in.ua]`
Thanks!

**Comment by Goretsv** [comment]
I tried many options, this is the last saved option.

**Comment by khouloudbelguith** [comment]
@Goretsv, in your case, the PS_MAIL_DOMAIN value is "mail.print-service.ua" or "savo.in.ua"?
What is the difference between those values in your case?
Thanks!

**Comment by Goretsv** [comment]
Because Prestashop always puts domain print-service.ua (root site domen) and ignores any settings, including domain "mail.print-service.ua"
And I cannot use domain print-service.ua, since it is configured on a CloudFlare proxy, and not on my server, and I need to put any domain in which the server IP is specified, since the mail server detects an attempt to spoof the IP and does not accept mail

**Comment by khouloudbelguith** [comment]
@Goretsv,

> print-service.ua (root site domen) and ignores any settings, including domain "mail.print-service.ua"

What are those exact settings?
Thanks!

**Comment by Goretsv** [comment]
With any settings in the database, Prestashop takes as a mail domain, the carne domain of the store

**Comment by khouloudbelguith** [comment]
@Goretsv, thanks for your feedback.
But I need to know the exact steps to reproduce the issue in my local.
Thanks!

**Comment by Goretsv** [comment]
1) Set any mail domain.
2)Send test email
3)Look log mail server (host parameter)

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/15CYSPCed9p4TlA4x3h04solmdWRd5bjP/view
And here's my log file
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2909999/log.txt)
Thanks to check & feedback.

**Comment by Goretsv** [comment]
I do not agree with your conclusions,
from=<**@prestashop.com> to=<**@prestashop.com> proto=ESMTP helo=<[127.0.1.1]>
Why you have HELO 127.0.1.1?

**Comment by khouloudbelguith** [comment]
@Goretsv, I use PrestaShop in my local.
Thanks!

**Comment by Goretsv** [comment]
Yes .. right .. you are right
relay=127.0.0.1[127.0.0.1]
But why HELO 127.0.1.1, prestashop mail domen is used to configure the mail domain, SMTP servers with the correct security settings will not accept the name 127.0.1.1

**Comment by khouloudbelguith** [comment]
@Goretsv, the 127.0.1.1 is the address of my vhost created in my local.
In the PrestaShop, Email page, I defined an SMTP server 192.x.x.x & a mail domain name webmail.xxx.tn
Thanks!

**Comment by Goretsv** [comment]
You are right, in log HELO must be webmail.xxx.tn, in this problem, this i write as problem

**Comment by khouloudbelguith** [comment]
@Goretsv, but in my case, I don't have error 550, in my log, it is OK.

```
webmail postfix/smtp[706]: 54FB721E18D: to=<khouloud.belguith@prestashop.com>, relay=127.0.0.1[127.0.0.1]:10025, delay=0.42, delays=0.18/0/0.01/0.23, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 7825021E002)
Feb 27 00:00:19 webmail postfix/lmtp[618]: 7825021E002: to=<khouloud.belguith@prestashop.com>, relay=webmail.xxx.tn[192.168.1.16]:7025, delay=1.6, delays=0.26/0/0.12/1.2, dsn=2.1.5, status=sent (250 2.1.5 Delivery OK)
```

**Comment by Goretsv** [comment]
You have not security postfix setting , if use email provider, HOST 127.0.1.1 was blocked as spam

**Comment by khouloudbelguith** [comment]
@Goretsv, and in my case, I receive all the emails in my inbox & not in the spam.
Thanks!

**Comment by Goretsv** [comment]
I have nore arguments.... HELO must be = mail domen

**Comment by khouloudbelguith** [comment]
@Goretsv, the parameter after HELO should identify the system sending the email.
Go back to your original issue, in my case, there are no errors in my log when I sent a test mail while mail domain is not empty.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by ghost** [comment]
Thank you @Goretsv for providing the solution. 
I had the same issue. I'm new to Presta and I was close to ditch it. 
After some research I know that this problem is known since Prestashop 1.6.1.5.

If you have SMTP server or another machine and your provider implemented some anti-spam policies, you might end up with connection being rejected by SMTP server with error:
"Expected response code 250 but got code "550", with message BAD HELO - Host impersonating domain name [_domain.name_]

In my provider log it was:
rejected EHLO or HELO _domain.name_: Bad HELO - Host impersonating domain name [_domain.name_]

The same will occur when your have your DNS record proxied in on Cloudflare, and your provider cannot verify the host.

The bug is: the mail domain name in Advanced Parameters > Email is not used.

Solution provided by @Goretsv works perfectly. 
If you have the same problem:
modify the file: vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php

private function _lookupHostname()
    {
        if (!empty($_SERVER['SERVER_NAME']) && $this->_isFqdn($_SERVER['SERVER_NAME'])) {
            //$this->_domain = $_SERVER['SERVER_NAME']; 
            **$this->_domain = "your.domain.name";**


I hope this will help someone.

**Comment by jakub-trzebiatowski** [comment]
I'm having the same problem as the OP. My VPS server hosting a Prestashop shop under domain `karbonowy.pl` tries to connect to an external shared mail server for domain `karbonowy.pl` via SMTP, which results in the `550 Bad HELO - Host impersonating domain name [karbonowy.pl]` error.

@khouloudbelguith 
Could you please comment on the @xpectopatronus post aboce? I know that such "let's just hack around in PHP files" solutions might sometimes suggest that something is done wrong, but I really can't see what's wrong with the provided reasoning.

What's the _intended_ use of the "Advanced Parameters > Email > Mail domain name" property if it's not used for SMTP requests?

**Comment by misieq12** [comment]
Hello, 

I have same problem on ps 1.7.8.7. I get this error:

Error: please check configuration

Expected response code 250 but got code "550", with message "550 Bad HELO - Host impersonating domain name [DOMAIN.COM]".

However, when I switch the settings to / usr / sbin I get an error:

Error: please check configuration

Expected response code 220 but got an empty response

Solution:

> private function _lookupHostname()
> {
> if (!empty($_SERVER['SERVER_NAME']) && $this->_isFqdn($_SERVER['SERVER_NAME'])) {
> //$this->_domain = $_SERVER['SERVER_NAME'];
> **$this->_domain = "your.domain.name";

Unfortunately doesn't work for me. I tested my SMTP configuration on other ps shop, and it work, but on my basic shop not. 

What may be the problem?

Regards.
