### ISSUE TITLE
[PrestaShop] Fatal error in module CP_PrestaCraftFormCore Prestashop1.6

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#12697]
Hi, 
I have a client that he has that mistake in prestashop 1.6, when he was installing a some modules, the clients when they prefer make a order and after sing in, they se the error 
[**PrestaShop] Fatal error in module CP_PrestaCraftFormCore:
Can't inherit abstract function CP_PrestaCraftFormInterface::render() (previously declared abstract in CP_PrestaCraftFormCore)** i supose that the error is by a module but i do not know what is the correct module, i cant upgrade to the last version i supose is by this error, if you know what is the cause and have a solution i need it.

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, that’s why I close it.
Thanks for your understanding!

**Comment by matks** [comment]
Also @juank2808 the error is very likely to come from the module as class `CP_PrestaCraftFormCore` is not from the Core project. You probably need to uninstall the module with this class.

To find it, you can try looking for a file `CP_PrestaCraftFormInterface.php` or something similar, and see where it is. It is probably - but I say probably as we cant be 100% sure as it is a module on your client's server - the module that creates the issue.

**Comment by juank2808** [comment]
Oh thanks, problem solved! now i need upgrade from 1.6 to 1.7 but prstashop only gives me the version 1.6.1.23 y need upgrade to the last version :(

**Comment by khouloudbelguith** [comment]
@juank2808, 

In the autoupgrade configuration page, you need to follow these steps:
![image](https://user-images.githubusercontent.com/16067358/53333197-7efa8100-38f5-11e9-85d3-4410b7718831.png)

Thanks!

**Comment by juank2808** [comment]
no i can't, this is ins spanish but is the same 
![imagen](https://user-images.githubusercontent.com/14195668/53333390-0516c780-38f6-11e9-94c6-e3dfc8c17600.png)

**Comment by khouloudbelguith** [comment]
@juank2808, you need to click on the button "More options" first, then select the "Major release, the save.
Thanks!

**Comment by juank2808** [comment]
No, i cant again i supose that is by PHP version but if i upgrade to 7.1 for example i cant see nothing
![imagen](https://user-images.githubusercontent.com/14195668/53334302-a99a0900-38f8-11e9-8cd6-696ceae980f0.png)

**Comment by khouloudbelguith** [comment]
@juank2808, when you select "Major release" & you save, the version PS1.7.5.1 is not displayed?
Thanks!

**Comment by juank2808** [comment]
No, only i can see that the "last" version is the 1.6.1.23 i have tried all things, install a test version in local, and upload the database backup..., and installl 1.6.1.23 in local and i can't cause the PHP version isn't compatible

**Comment by khouloudbelguith** [comment]
@juank2808, what is the exact version PHP did you use?
Thanks!

**Comment by juank2808** [comment]
i have the 5.6

**Comment by juank2808** [comment]
i have other question, Does the prestashop update affect the database? now i cant update prestashop but i'm really insecure cause i have make it in a real web

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

Yes, PrestaShop update the Database during the upgrade.
You can find the schema changes from 1.7.5.0 to 1.7.5.1 by looking at this file: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.5.1.sql

You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql

As always, you can use the 1-click update to upgrade without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production & try to make a backup before the upgrade.

Thanks!

**Comment by juank2808** [comment]
thanks! now i have the other problem, when i decide update the pestashop version, prestashop gives me a error  
![imagen](https://user-images.githubusercontent.com/14195668/53398471-f5f15180-39a9-11e9-88d8-377684fef1f2.png)

have you some idea baout this?

**Comment by khouloudbelguith** [comment]
@juank2808, you need to increase the `max_execution_time` in your php.ini file
Thanks!

**Comment by juank2808** [comment]
Done! now y havce one more problem sorry 
![imagen](https://user-images.githubusercontent.com/14195668/53407174-d19e7080-39bb-11e9-9ab6-37437e68c574.png)

**Comment by khouloudbelguith** [comment]
@juank2808, this error cannot help us to find what's wrong.
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by juank2808** [comment]
good news! i ave updated the prestashop version haha i'm happy now thaks for your help :)

**Comment by khouloudbelguith** [comment]
@juank2808, great!

**Comment by juank2808** [comment]
hi again, i have a proble with the spanish translations, first a message comes out that said, that the folder didn't exist now, in mas test version i have the folder and I have copied and pasted the folder in the same site now i have this error; do you know the solution? @khouloudbelguith 
**An exception occurred while executing 'SELECT p0_.id_translation AS id_translation_0, p0_.`key` AS key_1, p0_.translation AS translation_2, p0_.domain AS domain_3, p0_.theme AS theme_4, p0_.id_lang AS id_lang_5 FROM ps_translation p0_ WHERE p0_.id_lang = ? AND p0_.theme IS NULL AND (p0_.domain REGEXP ?) = 1' with params [1, "^Admin*"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist**

**Comment by khouloudbelguith** [comment]
This issue is currently closed, can you open a new one with more information about your configuration.
Thanks!
