### ISSUE TITLE
microdata errors in many pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12694]
hi
from this tool you can see that there are many errors around microdata of products
https://search.google.com/structured-data/testing-tool#

it is present in the homepage, category pages and product pages but you should check also other pages
the microdata is very important for google

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/53325144-dcd19d80-38e2-11e9-9f23-4a93531c9384.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0

bye

**Comment by eternoendless** [comment]
For future reference: https://schema.org/price

The schema for the product page looks OK in 1.7.5.1, according to spec:

<img width="895" alt="screenshot 2019-02-25 at 10 28 16" src="https://user-images.githubusercontent.com/1009343/53327502-36889680-38e8-11e9-8f0c-8a9a0e8e37ba.png">

**Comment by Maofree** [comment]
the price attributes are good only in the product pages and only for the main products, but not in the modules like ps_categoryproducts or ps_viewedproduct
not in the product blocks of the homepage and category pages
however should be present some other values, I think now google requests more data for product microdata
it is necessary to fix the miniature tpl

![1](https://user-images.githubusercontent.com/653230/53327809-db0ad880-38e8-11e9-976e-c025143ba557.png)

**Comment by khouloudbelguith** [comment]
Hi @maofree, @eternoendless,

I checked the home page 2, I have the same issue with PS1.7.5.1 & PS1.7.4.4
![image](https://user-images.githubusercontent.com/16067358/53331137-7784a900-38f0-11e9-99e9-660cec40f2a8.png)
With PS1.7.5.1 & PS1.7.4.4 in the ps_categoryproducts section
![image](https://user-images.githubusercontent.com/16067358/53331392-11e4ec80-38f1-11e9-8987-b7caf4433980.png)
With PS1.7.5.1 & ps1.7.4.4 in the ps_viewedproduct section
![image](https://user-images.githubusercontent.com/16067358/53331808-15c53e80-38f2-11e9-9ad8-d67c45ee707c.png)

@eternoendless what do you think?
Thanks!

**Comment by Tomskor** [comment]
We have with this same problem, find some solution but on my theme this not working:

https://www.prestashop.com/forums/topic/956810-google-analytics-error-either-offers-review-or-aggregaterating-should-be-specified/

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with 1.7.6.x ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, I have the same issue with PS1.7.6.0beta1
1. ps_categoryproducts section
![image](https://user-images.githubusercontent.com/16067358/59192157-79aa0500-8b79-11e9-8673-a97dd8dfde5e.png)
2. the ps_viewedproduct section
![image](https://user-images.githubusercontent.com/16067358/59192173-86c6f400-8b79-11e9-8931-bd3586a0bf95.png)
3. In the home page 2
![image](https://user-images.githubusercontent.com/16067358/59192280-d2799d80-8b79-11e9-842e-4071ea7b01a7.png)

Thanks!
