### ISSUE TITLE
"Delete combinations" button not working anymore in 1.7.5.1

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#12703]
After  upgrade to 1.7.5.1, when I edit a product with many combinations and click the "Delete combinations" button, in Combinations Tab, I get a green message of "Undefined", and the combinations are not deleted.

To reproduce:
1. Go to Catalog > Products
2. Edit a product with many combinations
3. Go to Combinations Tab
4. Click the "Delete combinations" button.

Prestashop Version: 1.7.5.1
PHP Version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @rblaurin,

I did not manage to reproduce the issue with PS1.7.5.1 after upgrade from 1.7.5.0 with the 1-click upgrade v4.6.0.
I attached a video record.
https://drive.google.com/file/d/1xpAUNoGP6CyRpMkDuWF7-TVBvwlDg7QX/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rblaurin** [comment]
Hi, sorry. I mean the "Delete combinations" button in bulk actions.

**Comment by khouloudbelguith** [comment]
@rblaurin, seems ok to me also https://drive.google.com/file/d/1PqJyFF_zE-h5x2NGn0WJWhLW890BfnYs/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment]
@rblaurin, the issue is solved?
Thanks!

**Comment by rblaurin** [comment]
It is solved, thanks. My mistake.

**Comment by khouloudbelguith** [comment]
@rblaurin, thanks!
Feel free to open a new ticker when needed.
Thanks!
