### ISSUE TITLE
$layout should be considered a 'general purpose variables' and always assigned.

### ISSUE THREAD

**Issue by tlhuillier** [PrestaShop/PrestaShop#12702]
**Is your feature request related to a problem? Please describe.**
When prestashop core is updating product lists, for example when sorting or filtering,
templates such as `templates/catalog/_partials/products.tpl` are rendered individually during Ajax calls.
See `getAjaxProductSearchVariables()` in `ProductListingFrontController.php`.

Lets say the number of items per row is dependent from your layout : 
- pages with full width layout have 4 items/row
- pages with left column layout have 3 items/row
- ...

Variables that you could assign in your layouts templates would do the job,
but since templates mentioned above are rendered individually, you can't opt for this solution.

Another solution could be to assign such variables directly inside `templates/catalog/_partials/products.tpl` depending on the `$layout` variable.
Unfortunately, this variable is not exposed, but only variables declared in `assignGeneralPurposeVariables()` from `frontController.php` are.

**Describe the solution you'd like**
I think `$layout` should be moved in `assignGeneralPurposeVariables()` from `frontController.php`.

**Comment by khouloudbelguith** [comment]
Hi @tlhuillier,

Thanks for your report.
ping @eternoendless @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay.

I'm not sure assigning the `$layout` to `assignGeneralPurposeVariables` is the right solution, it will generate and consume resources for something that will no be used.

If I understand what you need, it's only because you want to know which layout name you load?
Otherwise, you can use hooks, retrieve the smarty instance, and put the needed variable inside :thinking:

**Comment by hibatallahAouadni** [comment]
Hello @tlhuillier ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
