### ISSUE TITLE
Superposition de fenêtre 1.7.5.0

### ISSUE THREAD

**Issue by christiandouchamps** [PrestaShop/PrestaShop#12712]
1° Bonjour, nativement quand ont se rend dans 'commande' et en cliquant sur la cliente en descendant ont trouve l'onglet 'paiement' et a droite 'message' or c'est deux fenêtre se superpose à partir du moment ou il y a des informations de paiement et donc je je sais pas y accéder photo ci dessous

2° Comme vous le voyer sur la photo un message en rouge apparait 'Attention 50,88 € payé au lieu de 25,44 €' or j'ai bien reçus 25,44 et non 50,88 comment puis-je faire pour régler cette affichage erroné
 
**Describe the bug**

**To Reproduce**
1. Go to '.commande..'
2. Click on '.customer...'
3. Scroll down to '.paiement...'
4. See error en creen shot bellow

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![capture d ecran 2019-02-26 a 10 54 35](https://user-images.githubusercontent.com/47417328/53404060-28547c00-39b5-11e9-8b2a-a3ccc12bbfae.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @christiandouchamps,

About the first issue, we are aware of this issue, you can follow this ticket: #9863.
About the second issue, you just received a double payment => could you please provide the exact status created for this order, then navigate to your BO => Shop Parameters => Order Settings => Status Tab => Search for the status of your order => Click edit => and provide me the exact configuration of this status.
Thanks!

**Comment by christiandouchamps** [comment]
Couleur
X .....Considérer la commande associée comme validée.
Autoriser les clients à télécharger et lire la version PDF de la facture.
Cacher cet état dans la commande pour les clients.
X.....Envoyer un e-mail au client lorsque la commande change d'état.
Joindre la facture PDF à l'e-mail.
Joindre le bon de livraison PDF à l'e-mail.
Marquer la commande associée comme expédiée.
X.....Marquer la commande associée comme payée.
Afficher le PDF de bon de livraison.
Modèle
 
Seules les lettres, les nombres et le caractère souligné ("_") sont autorisés.
Modèle d'e-mail pour HTML et texte brut.

**Comment by khouloudbelguith** [comment]
@christiandouchamps, this issue occurs only with PayPal module?
Have you tried to contact the module author about this issue?
Thanks!

**Comment by christiandouchamps** [comment]
no I do not contact the author it's just a problem of posting because I receive correctly the right amount

**Comment by christiandouchamps** [comment]
i need help for my * 1° problem

**Comment by khouloudbelguith** [comment]
@christiandouchamps, about your first issue, it is added to our bug roadmap, it is not fixed yet.
Your ticket is a duplicate of #9863
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9863

**Comment by christiandouchamps** [comment]
thank s for all
best regard
