### ISSUE TITLE
Impossible to edit product 

### ISSUE THREAD

**Issue by nathino10** [PrestaShop/PrestaShop#12719]
Hello everybody, 

I try here, because i haven't found in others topics. Sorry I'm new here so maybe i will do something in the wrong way.

I'm on PS 1.7.4.4 , and it is impossible to edit products. Categories are ok , but products not. I check with the console, i have these errors (files attached), i don't know how to deal with it to solve.

Thanks for your help

![capture d ecran 2019-02-26 a 14 58 49](https://user-images.githubusercontent.com/39501256/53418042-33200880-39d7-11e9-836a-4fc4b5e1e1b8.png)

**Comment by khouloudbelguith** [comment]
Hi @nathino10,

You need to enable debug mode in your store and debug request which is sent for product edition in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. Edit a product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Preview" tab

Thanks!

**Comment by nathino10** [comment]
Hello, 

Thansk for your help, i have some things

The first is : 
![capture d ecran 2019-02-26 a 15 09 57](https://user-images.githubusercontent.com/39501256/53418768-d58cbb80-39d8-11e9-89a3-90bff87fbfa6.png)
![capture d ecran 2019-02-26 a 15 10 08](https://user-images.githubusercontent.com/39501256/53418782-dd4c6000-39d8-11e9-9c3f-5992e4610583.png)

The second and the third are concerning these files, but i have nothing in the preview tab ..
![capture d ecran 2019-02-26 a 15 10 45](https://user-images.githubusercontent.com/39501256/53418841-f5bc7a80-39d8-11e9-97c6-c7e2d1326bd6.png)

**Comment by khouloudbelguith** [comment]
@nathino10, if you click on this error:
![image](https://user-images.githubusercontent.com/16067358/53418998-43d17e00-39d9-11e9-98b7-2fc270c7c177.png)
There is nothing in the "Preview" Tab.
When you enabled the debug mode, there are no exceptions displayed when you edit a product?
Thanks!

**Comment by nathino10** [comment]
No, normally i must see something but in this case, i don't have window of debug with databas exception or something like this ..

**Comment by khouloudbelguith** [comment]
@nathino10, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nathino10** [comment]
I add some informations
----------Server setup and configuration---------------------
Informations sur votre serveur Linux #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64
Version du logiciel serveur : Apache
Version de PHP : 5.6.40-1+0~20190111135457.9+jessie~1.gbp5f42c9
Limite de mémoire : 256M
Temps maximal d'exécution : 120
Taille max. pour envoi de fichiers : 100M

------------------APACHE ERROR LOG------------------
[Tue Feb 26 16:20:18.307181 2019] [proxy_fcgi:error] [pid 15566] [client 185.62.189.177:59648] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 26 16:24:36.475956 2019] [proxy_fcgi:error] [pid 15594] [client 185.62.189.177:60928] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 26 16:28:54.545479 2019] [proxy_fcgi:error] [pid 15736] [client 185.62.189.177:33302] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 26 16:33:12.238709 2019] [proxy_fcgi:error] [pid 15870] [client 185.62.189.177:33756] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 26 16:37:30.197981 2019] [proxy_fcgi:error] [pid 15790] [client 185.62.189.177:34952] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 26 16:41:48.227471 2019] [proxy_fcgi:error] [pid 16306] [client 185.62.189.177:35156] AH01071: Got error 'Primary script unknown\n'

For the debug mode, i don't have informations on chrome, but i tried with Mozilla, it shows me that things

![capture](https://user-images.githubusercontent.com/39501256/53426728-d547ec80-39e7-11e9-917c-4563e6a5ac1d.PNG)

**Comment by khouloudbelguith** [comment]
@nathino10, the AdminProductsController.php is overrated, which causing the problem.
You need to edit this override if you have added it manually or find which module that overrode this class.
Your issue is not a PrestaShop's core bug but most likely a customization problem.

I will close the issue, feel free to open a new one when needed.
Thanks!
