### ISSUE TITLE
CMS Layout not showing at theme options

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#12729]
With my version 1.7.5.1 I can't change CMS pages layout because the option CMS doesn't show up at theme options.

**To Reproduce**
Go to Design
Go to Theme & Logo
Click Choose Layouts
CMS Is missing

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: PHP 7.0.33-0ubuntu0.16.04.1
![cms missing](https://user-images.githubusercontent.com/3126847/53445782-48ae2600-3a09-11e9-8aa6-96cefeb5cdcb.png)

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1vj8wkzcLSpXfyS7H-SbDsn7APaNGb7DV/view
Did you use the theme by default provided by PrestaShop?
Thanks!

**Comment by seederp2p** [comment]
Hi!
I use a different theme but with the default theme I have the same behaviour.

My store was fresh installed with 1.7.5.0 and after that I updated with 1.7.5.1...

**Comment by khouloudbelguith** [comment]
@seederp2p, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.1 after upgrade from PS1.7.5.0 with the 1-click upgrade v4.6.0.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by seederp2p** [comment]
Hi!

Ubuntu Server  16.04.6 LTS
PHP 7.0.33
mysql  Ver 14.14 Distrib 5.7.25
Cache emptied

No PHP Errors when I click "Layouts"
No Apache Erros when I click "Layouts"

jquery-1.11.0.min.js:3 Mixed Content: The page at 'https://MYURL/BACKOFFICE/index.php?controller=AdminThemes&display=configureLayouts&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' was loaded over HTTPS, but requested an insecure resource 'http://addons.prestashop.com/iframe/analytics-themes-1.6.html?parentUrl=https://MYURL/BACKOFFICE/'. This request has been blocked; the content must be served over HTTPS.

I don't know if it helps but recently I renamed my prestashop directory. Everything else is working

**Comment by khouloudbelguith** [comment]
@seederp2p, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by seederp2p** [comment]
Hi!

In fact I already did that because when I renamed the directory I had a problem with my modules. In any case I did that again and it did no solve the issue.

I also had some paypal module "pages" missing from "layouts". After I reinstalled the paypal module it appeared again... but CMS is still missing...

**Comment by khouloudbelguith** [comment]
@seederp2p, it could be caused by a module also?

**Comment by seederp2p** [comment]
Is there any way to debug it in a more convenient way?

**Comment by khouloudbelguith** [comment]
@seederp2p, if you click on the button "Reset to defaults", the CMS will appear?
![image](https://user-images.githubusercontent.com/16067358/53571931-5f1fc300-3b6a-11e9-9e85-f132f9358ee4.png)
Could you please try to check & feedback.

**Comment by seederp2p** [comment]
I have no such option.

Please check attached file.
![no reset option](https://user-images.githubusercontent.com/3126847/53573469-71e3c900-3b65-11e9-8fbb-a7fd73147ce9.jpg)

**Comment by khouloudbelguith** [comment]
@seederp2p, could you please try to navigate to your BO => Module Manager => search for the "Theme Customization" module & reset it.
Thanks!

**Comment by seederp2p** [comment]
Hi!
No changes.

**Comment by khouloudbelguith** [comment]
@seederp2p, you need to enable the debug mode.
Thanks to navigate to your BO => Advanced Parameters => Performance => Enable debug mode & the try to click on the button "Reset to defaults"
Thanks!

**Comment by seederp2p** [comment]
Reset button is present now.
Did a reset but CMS is still missing.

**Comment by khouloudbelguith** [comment]
@seederp2p, We need to retrieve the PHP error log in order to find out what's wrong.
If you don't have it try to rest all module, check & feedback.
Thanks!

**Comment by seederp2p** [comment]
Hi!

I've PHP error enabled. But I don't have any error messages.

If I reset all modules I'm going to lose all the configs from it, right?

**Comment by khouloudbelguith** [comment]
@seederp2p, yes!

**Comment by seederp2p** [comment]
Ok!

So I reseted in my dev environment and CMS is still missing. :(

Is there any other way to debug this?

**Comment by khouloudbelguith** [comment]
@seederp2p, because the upgrade, it was ok?
if yes, can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

**Comment by seederp2p** [comment]
hi!
The upgrade was ok.
I don't have that directory / file

**Comment by khouloudbelguith** [comment]
@seederp2p, you can find it in the /Project_folder/admin_folder/autoupgrade/tmp/log.txt
Thanks!

**Comment by seederp2p** [comment]
There you go.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2919340/log.txt)

**Comment by khouloudbelguith** [comment]
@seederp2p, there are no errors in your log.
Could you please try to replace the folder `classic` of your theme with another folder from a fresh install 1.7.5.1.
Thanks to check & feedback.

**Comment by seederp2p** [comment]
Hi!
Same thing.

By the way I tried with a different theme and same result.

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

Despite our several trials, we could not reproduce your issue with the provided information with fresh install PS1.7.5.1 & after upgrade from PS1.7.5.0.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by seederp2p** [comment]
Hi!
I did some research and changed my shop1.json manually to have:

"cms":"layout-full-width"

But i got this:

[PrestaShopException]
No template found for cms/page
at line 68 in file classes/Smarty/TemplateFinder.php

63.                     return $tpl;
64.                 }
65.             }
66.         }
67. 
68.         throw new PrestaShopException('No template found for ' . $template);
69.     }
70. 
71.     private function getTemplateHierarchy($template, $entity, $id)
72.     {
73.         $entity = basename($entity);

**Comment by seederp2p** [comment]
FYI If I manually add "cms":"layout-left-column" to shop1.json, it changes the layout BUT it is not present at layouts.
