### ISSUE TITLE
Provide access to pages Module Updates and Module Alerts pages when upgrading to 1.7.6

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12722]
In https://github.com/PrestaShop/PrestaShop/pull/12713 I introduced 2 new roles needed to access pages Module Updates and Module Alerts.

This means that, for a shop that migrates to 1.7.6, since the superadmin rights are granted to him at install process, and this process will not be performed, then *no BO user* will be granted the required rights to access these 2 pages.

The access rights will need to be given through the Permissions page.

I guess that the expected behavior would rather be "any user who could previously access the Module Manager page should be able to access Module Updates and Module Alerts" ?

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/12713#issuecomment-467394955

**Comment by matks** [comment]
ping @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
In my opinion, we should duplicate the parent access configuration to each tabs.

**Comment by jolelievre** [comment]
Yes actually we have a function `add_new_tab_17` which does it. I integrated this bug fix in another PR along with other upgrade scripts https://github.com/PrestaShop/PrestaShop/pull/13048
