### ISSUE TITLE
Position Updater component should not be on the Grid namespace

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#12738]
As stated in the documentation, the [Position Updater](https://devdocs.prestashop.com/1.7/development/components/position-updater/) is a standalone component.

Then, why all its classes are located into ``Grid`` namespace?

This make the extraction of the Grid Component more difficult and create risks to couple the two components for no gain.

What I suggest:

* move the component into its own namespace (``PrestaShop\Component\PositionUpdater``) and add it as a standalone library

This could be done in 2 steps:
* move the component from current namespace ``PrestaShop\PrestaShop\Core\Grid\Position`` to ``PrestaShop\PrestaShop\Core\PositionUpdater`` and later consider a complete extraction from the Core.

WDYT?

**Comment by sarjon** [comment]
I agree, I've already tried to push this idea some time ago, but without luck. :cry:
