### ISSUE TITLE
[PRICE & TAXES] As a merchant I need to correctly display all the details of the order price in the purchase funnel

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#12743]
**WHY**
We have identified different issues related to price display in the front and back-office. Here are some of these issues :
#10013
#9698
#11360
#9999
#11492
#12969
 
The calculation is correct but the wording and/or the display order often introduce confusion for both merchants and final customers.

**WHAT**
Thus, this project aims at redesigning and reworking the display of the price detail during the purchase process. This should address the following issues :
unclear tax display
unclear total to pay
Unclear difference between Subtotal (tax excluded) and Total (tax included)
incorrect display vs configuration options
This first step aims at displaying a clearer detail of the price by improving most important front office pages (customer view) :
Cart summary
Order block (purchase funnel)
“Add to Cart” confirmation pop-up
Order confirmation
In the second step, the following pages will be addressed with the same improvements :
on the Back-office, in the order page 
on the confirmation email
on the Front-office, on the customer account (order history)
 
**USER SCENARIOS**

We have identified 7 generic user cases which will have an impact on the price details display :

Standard BtoC user scenarios :
with tax details displayed
with tax details hidden
In a multi-tax country (ex: Canada)

Scenarios for a customer group with price display method option set to “Tax excluded”
with tax details displayed
with tax details hidden
In a multi-tax country (ex: Canada)

Scenario for All tax disabled on the store
Specific to BtoB or “autoentrepreneur” user scenarios

According to the scenarios, prices can include :
Total price of the product(s)
Discount 1, discount X
Shipping price
Gift wrapping (if option enabled and selected)
Taxes (if option enabled)
 
The sum of all elements result in the total price to be paid by the user.
 

CART SUMMARY

Scenario 1 : Standard BtoC user scenario with tax details displayed

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Total (tax included)    XXX €
Including taxes   XXX €

Scenario 2 : Standard BtoC user scenario with tax details not displayed

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Total (tax included)    XXX €

Scenario 3 : Standard BtoC user scenario in a multi-tax country (ex: Canada)

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Total (tax included)    XXX €
Including taxes :
XX € (- - -)
XX € (- - -)

Scenario 4 : Scenario for a customer group with price display method option set to “Tax excluded” with tax details displayed

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Subtotal (tax excl.) XXX €
Total (tax incl.)    XXX €
Including taxes : XX € (- - -)

Scenario 5 : Scenario for a customer group with price display method option set to “Tax excluded” with tax details not displayed

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Subtotal (tax excl.) XXX €
Total (tax incl.)    XXX €

Scenario 6 : Scenario for a customer group with price display method option set to “Tax excluded” in a multi-tax country (ex: Canada)

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Subtotal (tax excl.) XXX €
Total (tax incl.)    XXX €
Including taxes :
XX € (- - -)
XX € (- - -)

Scenario 7 : Scenario for All tax disabled on the store

Y items            XXX €
Discount 1       XXX €
Discount 2       XXX €
Gift wrapping       XXX €
Shipping     XXX €
Total   XXX €

ORDER BLOCK (PURCHASE FUNNEL)
Same as detailed in the cart summary scenarios but :
There is no price shown next to “X items” (same as current)
There is a dropdown to show the detail of the products (same as current)
Subtotal wording is replaced with Total items (tax included / excluded)
See an example here :

“ADD TO CART” CONFIRMATION POP UP
Same as detailed in the cart summary scenarios but :
There is no discount line
There is no gift wrapping line
See an example here :

ORDER CONFIRMATION

Same as detailed in the cart summary scenarios but :
There should be a title for the 1st column : “Unit price” with tax included / tax excluded or nothing according to the configuration 
There should be a a title for the 2nd column : “Total products” with tax included / tax excluded or nothing according to the configuration 
See an example here :

**DESIGN**

Mockups available on Invision : 
https://invis.io/38QZ6JOE7GP#/351470285_Confirmation_Ex_2

**Comment by Peterits** [comment]
Hello, I made some modifications for the display of groups with the excluded tax, also works with tax groups included
Modification to solve the display of the detail to pay and the customer history with HT groups in 1.7.5.x, if it can be useful for 1.7.6.x

Display error when client groups are Tax excluded in history

![History-customer](https://user-images.githubusercontent.com/44966543/54349247-23e1c180-464b-11e9-8693-3b6c8fefb735.jpg)

![Details-clients-HT](https://user-images.githubusercontent.com/44966543/54349274-30feb080-464b-11e9-8e49-df9ab99186fa.jpg)

****** Display the correct total price to be paid in the order history & order detail in 1.7.5.x ******

-->  src/Adapter/Presenter/Order/OrderLazyArray.php
-->  Line: 233

remove:       
$amount = $this->includeTaxes() ? $order->total_paid : $order->total_paid_tax_excl;

Add:            
$amount = $this->includeTaxes() ? $order->total_paid : $order->total_paid;

------------------------------------------------------------------------------------------------------

***** Display the correct price of the HT or TTC port in detail history in 1.7.5.x  ******

-->  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
-->  Line: 216 - 217

Remove:                   
(!$order->getTaxCalculationMethod()) ? $shipping['shipping_cost_tax_excl']
                        : $shipping['shipping_cost_tax_incl'];   

Add:                 
(!$order->getTaxCalculationMethod()) ? $shipping['shipping_cost_tax_incl']
                        : $shipping['shipping_cost_tax_excl'];

**Comment by khouloudbelguith** [comment]
@Peterits, thanks for your code suggestion.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Peterits** [comment]
Yes, I want but I do not know how to do it !!

**Comment by khouloudbelguith** [comment]
@Peterits, Thanks to follow this documentation: https://github.com/PrestaShop/PrestaShop/tree/develop#contributing to make your pull request.
Thanks!

**Comment by Peterits** [comment]
I'm going to try

**Comment by matks** [comment]
@Peterits I also like https://github.com/firstcontributions/first-contributions it's a very good tutorial from lot of opensource people themselves on how to make pull requests 😉

**Comment by colinegin** [comment]
#13047

**Comment by CatchMeZZo** [comment]
I have massive problems with vouchers in the shopping cart when buying and redeeming.

(buying)
[https://imgur.com/G7w3uPr](url)

(redeeming)
I try to explain it point for point:
-> If I sell a premium gift voucher in germany. I sell it to 0% VAT.-> Why? Easy!
-> Because this time it is not clear at which products the customer will be bought with the premium gift voucher. So far so clear!
-> Now the customer buys products at 7% and 19% VAT and want to redeems his premium gift voucher. Problem? Paying attention now!
-> Let's say the customer have 50 Euro in the shopping cart and he want to redeem it with his 50 Euro premium gift card. After purchasing, prestashop will generate an invoice with a total of 0 euros. That's right... BUT!!!!! the VATs of the total must be calculated in the invoice and should not be set to 0 euros! That would be tax evasion and illegal!!!
-> It must not be treated like a simple coupon (price reduction)! The total amount must be taxed with a premium gift voucher.

**Comment by khouloudbelguith** [comment]
Hi @CatchMeZZo,

Issue created here: https://github.com/PrestaShop/PrestaShop/issues/17378

Thanks!

**Comment by netzgestaltung** [comment]
Hi there,

is there a specific reason why not both values are available as variables for subtotals? including and excluding taxes?

would be a two-liner at https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderSubtotalLazyArray.php#L140

to add these values
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // is missing
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
            ];
```

Then it would be possible to write in [order-confirmation-table.tpl](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/checkout/_partials/order-confirmation-table.tpl#L110):
```
{assign var='subtotal_value_exc_format' value=Context::getContext()->currentLocale->formatPrice($subtotal.amount_excl_tax, Context::getContext()->currency->iso_code) }
{$subtotal_value_exc_format}
```
This also applies to products!

But it looks like impossible to get that variable out of the system. How can i override that file? is that possible for "/scr/Adapter" paths?

Also i could imagine to get the variables like so:
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // handy variables for theme developers:
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
                'value_excl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_excl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
                'value_incl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_incl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
            ];
```

PS: if you see me rant today: im hunting after tax/wt variables since 6 days and these are the last ones missing.

you also can comment my latest workaround:
```
            {if $subtotal.type === 'shipping'}
              {assign var='shipping_data' value=$order.details->getShipping() }
              {assign var='subtotal_value_exc' value=$shipping_data[0].shipping_cost_tax_excl }
            {/if}
```
now only the products subtotals are missing...
