### ISSUE TITLE
Add a E2E test to check each BO pages access rules

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12741]
PRs such as https://github.com/PrestaShop/PrestaShop/pull/12709 secure a BO page but in order to make sure this keeps over time, we need a end-to-end test that would attempt to access *all* BO pages with a user that does *not* has the required access ... and check that indeed this user is denied access to the page.

**Comment by matks** [comment]
@mbadrani that would be a nice topic for puppeeter 😉

**Comment by mbadrani** [comment]
@matks challenge accepted!!!
