### ISSUE TITLE
PS 1.7.5.1 OnBoarding configuration banner not work and hide configuration section

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#12750]
**Describe the bug**
Install a new fresh super ultra 1.7.5.1 installation, when login we get a banner in the top left corner with the "onboarding" store launcher helper. Unable to close, unable to stop. Unable to access the under section "configuration" because this wonderfoul banner still here ...

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1yWXc6wVOF495MemgFv49cNSMHyj0dV8Q/view
You need to enable debug mode in your store and debug request which is sent for closing the pop up on your browser, using DevTools, so:

1. enable debug mode 
2. open up developer tools
3. go to Network tab
4. close the popup
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by matteolavaggi** [comment]
i've uninstalled ps 1.7.5.1.
