### ISSUE TITLE
Missing new-products page

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#12759]
In previous versions there was a new-products page provided by default but it seems its no longer there in 1.7.I was trying to get feedback in the forum as well without luck:
https://www.prestashop.com/forums/topic/957362-is-there-a-new-products-page-in-17/

 Is this intentional or should there be something like:
{$urls.pages.new_products}

**Comment by khouloudbelguith** [comment]
Hi @johanlantz,

Yes, it still exists.
I attached a video record.
https://drive.google.com/file/d/1tuj9g1sV8ssoQBIuIAo0TcmZti6cLn-X/view
Thanks to check & feedback.

**Comment by johanlantz** [comment]
Thanks for being so reactive and answer quickly, it is super helpful

I explained myself poorly. I was just wondering if there was a premade option such as: {$urls.pages.prices_drop} 
for the new product but I saw that it could be accomplished with the {url entity='new-products'} instead so closing this.

**Comment by khouloudbelguith** [comment]
@johanlantz, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
