### ISSUE TITLE
Can't connect to backoffice using CDN (not only static files)

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#12752]
Does Prestashop would allow this kind of setup ? the site is pointed toward CDN (stackpath) and then reaching to my origin ? I mean some in-between service while the authentication takes place.

I'm using a CDN (with the URL of media server recorded and working great). 
But I want to use all their service, especially the Web Application Firewall service. To do so, they told me to change my host files with the defined IP (that will become the A zone of my DNS afterwards) to verify the site before making any change on the DNS. I did all of this, with them verifying and everything is working great **except** I can't connect to the backoffice.

The form appears. If I'm using a bad email or bad password, I receive the error. But if they are both good, nothing happens. Like really nothing, the form submits, it reloads the page and, but it's still the form without anything. They didn't get anything while monitoring - the requests are just passing through them on the authenticate page. But everything works fine if I don't change my hosts file.

I know there are still some maintenance on PS 1.6 about security issues. And this is quite one since I can't use the WAF service that would be able to prevent SQL injection on my website. I really hope someone have the solution. Thank you !

PrestaShop version: 1.6.1.6

**Comment by khouloudbelguith** [comment]
Hi @hellodracon,

Could you please try with this solution

```
Access the SQL database via phpmyadmin
Go to the table ps_configuration
Search for the PS_COOKIE_CHECKIP option
Set the value to 0 
```
I hope this helps you, the solution is proposed in this [forum](https://www.prestashop.com/forums/topic/342334-acc%C3%A8s-backoffice-impossible-avec-ovh-cdn/)

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
I will close the issue.
Thanks!

**Comment by hellodracon** [comment]
@khouloudbelguith  My god thanks a lot, it's working great ! Can you explain what it is by any chance ?

**Comment by khouloudbelguith** [comment]
@hellodracon, Great!
I found this solution in the forum: https://www.prestashop.com/forums/topic/342334-acc%C3%A8s-backoffice-impossible-avec-ovh-cdn/?do=findComment&comment=2469299
Thanks!

**Comment by hellodracon** [comment]
Yes, but no one explains why it's working. I was just curious. Thanks anyway ! You made my day
