### ISSUE TITLE
Hardcoded image URLs should be using `Link::getImageLink`

### ISSUE THREAD

**Issue by jacket** [PrestaShop/PrestaShop#12763]
**Describe the bug**

On the product page of PrestaShop admin, images are displayed via hardcoded image URLs, instead of the correct method of `Link::getImageLink`. This is inconsistent because throughout all other PrestaShop admin and live web pages, product images are embedded with the special `Link::getImageLink` method.

This causes missing images if the product thumbnails are deleted, in preference to the [Sirv image optimisation/CDN addon](https://addons.prestashop.com/en/website-performance/26622-sirv-image-cdn-optimization-and-responsive-images.html) or another such addon. Deleting product thumbnails is desirable because they can use up a lot of disk space on stores with many products.

The solution is simply to replace the hardcoded image URLs with `Link::getImageLink`.

**To Reproduce**

1. Install the [Sirv addon](https://www.prestashop.com/forums/topic/957014-image-urls-hardcoded-in-admin/) and set 'Delete images created by PrestaShop' to 'Delete'.
2. Click the blue button 'Sync Images'.
3. Go to any product in 'Catalogue > Products > Images' to see the missing images.

**Screenshots**
![Screenshot of Sirv addon settings](https://demo.sirv.com/demo/prestashop/sirv-admin-delete-thumbnails.png)
![Screenshot of PrestaShop product image management page](https://demo.sirv.com/demo/prestashop/admin-images-missing.png)

**Additional information**

Also reported here: https://www.prestashop.com/forums/topic/957014-image-urls-hardcoded-in-admin/

**Comment by khouloudbelguith** [comment]
Hi @jacket,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by jacket** [comment]
I think you misunderstood. The problem is not with the addon. The problem is with core PrestaShop code. PrestaShop is not referencing images in the standard way. They're hard coded. Hopefully it's just an oversight, which can be resolved by referencing images like PrestaShop normally does in its code.

I work for the company that provides the Sirv addon.

**Comment by khouloudbelguith** [comment]
@jacket, thanks for these clarifications.
This issue is reproduced with PS1.7?
If yes, could you please provide me the module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
Hi @jacket,

I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
@jacket, this module is only compatible with PS1.6.
Is not compatible with PS1.7?
Thanks!

**Comment by jacket** [comment]
It is compatible with PS1.7 (v1.5.0.0 - v1.7.5.1).

**Comment by khouloudbelguith** [comment]
@jacket, thanks, it is installed in PS1.7.5.1.
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@jacket, I tried with PS1.7.5.1, but it takes a lot of time.
In the meantime, I tried with PS1.6.1.23, but it is OK
I attached a video record
https://drive.google.com/file/d/1vr4M5jWbJznvkn9qVW3kvCHtTO_nI-3j/view
Thanks to check & feedback.

**Comment by jacket** [comment]
Thanks for testing. Please enable the Sirv addon with the option attached,
then click Save settings.

**Comment by khouloudbelguith** [comment]
@jacket, I enabled the "Active" option => but it is OK.
I attached a video record.
https://drive.google.com/file/d/1ePEKSlq5bx-omazLGgf_YaKAkJG9X8Wv/view
Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
@jacket, I tested the module with PS1.7.5.1, the synchronise does not complete.
![image](https://user-images.githubusercontent.com/16067358/53653080-b2694280-3c4a-11e9-9425-a7d1f2d688de.png)
That's why I couldn't complete the test of your module with PS1.7.5.1.
Thanks

**Comment by jacket** [comment]
Thanks for sharing your investigation @khouloudbelguith. 

We found that the issue affects PS1.6.x only. The code in PS 1.7 has been rewritten to image URLs are retrieved using one of the methods of the Image core class. 

Do you think a fix might be released for PS1.6? If not, we'll try and can create a workaround to override the Image class method.

**Comment by khouloudbelguith** [comment]
@jacket, sorry.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be accepted in the `1.6.1.x` branch.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by jacket** [comment]
OK, thanks for your help @khouloudbelguith!
