### ISSUE TITLE
jquery vulnerability in 2.2.4

### ISSUE THREAD

**Issue by juchems** [PrestaShop/PrestaShop#12768]
Bug Description:
A known, moderate severity jquery vulnerability exists in the bundled jquery library.

https://snyk.io/vuln/npm:jquery:20150627

This results in being flagged by Google for using technology with known vulnerabilities.

Earlier comments on #10463 indicated that this could be mitigated by using a different theme, but even when using a suggested theme like Classic-Rocket, we continue to be flagged by scans from tools like Google Lighthouse for using a vulnerable version of jquery.  The bulk of the comments there addressed Bootstrap and it's updates, but left open question of how to address jquery.

Currently, there is no way to mitigate this issue, even when used just targeting the Front Office.

To reproduce:

Scan a Prestashop Storefront (known to effect versions greater than 1.7.4.2) with Google Lighthouse and view the Best Practices section.

**Screenshots**
![image](https://user-images.githubusercontent.com/2808488/53652941-b461e000-3c0f-11e9-8ef1-f1e8e39f37e0.png)

**Additionnal information**
PrestaShop version: 1.7 and greater
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @juchems,

I have the same issue with PS1.7.5.1 & the default theme Classic
![image](https://user-images.githubusercontent.com/16067358/53654082-20af0480-3c4d-11e9-88f1-9eab2aec2bf8.png)
But, as @eternoendless said in this comment: https://github.com/PrestaShop/PrestaShop/issues/10463#issuecomment-425008014
Unfortunately, we cannot upgrade Bootstrap and jQuery on the classic theme until the next major version.
Thanks for your understanding!

**Comment by khouloudbelguith** [comment]
Duplicate of #10463
