### ISSUE TITLE
Installing Prestashop 1.7.5.x with PHP 5.6 fails

### ISSUE THREAD

**Issue by L3o-pold** [PrestaShop/PrestaShop#12779]
Install fails with PHP 5.6.40 and Prestashop 1.7.5.x during the Creat table in the database operation.

The url `http://example.com/e-commerce/install/index.php?installDatabase=true&_=1551683304694` returns the following error:
`web/e-commerce/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\\Common\\Annotations\\DocParser->Annotation(), referer: http://leopez.ch/e-commerce/install/index.php?restart=true`

**To Reproduce**
1. Go to `http://example.com/e-commerce/install` page with a web hosting in PHP 5.6 and Prestashop 1.7.5.0 or 1.7.5.1
2. Follow the install steps until the installation start

**Screenshots**
![capture d ecran 2019-03-04 a 08 12 21](https://user-images.githubusercontent.com/4710495/53716484-6ccc9580-3e55-11e9-9414-67e67bc01d21.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 and 1.7.5.1 not tested other versions
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @L3o-pold,

I did not manage to reproduce the issue with PrestaShop 1.7.5.1 & PHP5.6.32.
I attached a video record.
https://drive.google.com/file/d/1IebpyUfPEYssPBFqJoWCNuf3iLWp-yc2/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by L3o-pold** [comment]
It's a shared hosting...
Error logs: https://pastebin.com/qdezsisH
Javascript console log is empty.
Debug mode is on with the following screenshot

![capture d ecran 2019-03-04 a 11 30 38](https://user-images.githubusercontent.com/4710495/53727675-11100580-3e71-11e9-896e-28be0fefd0eb.png)
![capture d ecran 2019-03-04 a 11 30 23](https://user-images.githubusercontent.com/4710495/53727676-11100580-3e71-11e9-8ba7-5d3af01f5271.png)

**Comment by matks** [comment]
@L3o-pold Hi, it seems related to caching, from Google I can find people having the same issue:
- https://stackoverflow.com/questions/47443381/symfony-3-3-cant-find-doctrine-annotations
- (French) https://openclassrooms.com/forum/sujet/symfony-3-3-probleme-avec-les-annotations-doctrine
- (French) https://openclassrooms.com/forum/sujet/symfony-probleme-annotations-en-prod

**Comment by L3o-pold** [comment]
@matks There is no opcache on this hosting

See https://presta.leopez.ch/phpinfo.php

PS: Openclassrooms seems down ;)

**Comment by khouloudbelguith** [comment]
Hi @L3o-pold,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) & try those commands to clear cache:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks to check & feedback.

**Comment by L3o-pold** [comment]
@khouloudbelguith 

```
php-5.6 -d memory_limit=-1 ./bin/console cache:clear

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        


In AnnotationRegistry.php line 145:
                                                                               
  Warning: class_exists() expects parameter 1 to be a valid callback, functio  
  n 'author' not found or invalid function name                                
 ```

```
php-5.6 -d memory_limit=-1 ./bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false                                                 

PHP Warning:  class_exists() expects parameter 1 to be a valid callback, function 'ORM\Table' not found or invalid function name in /home/clients/6d914a7d2c241e9b168e3c144fec82a0/presta/e-commerce/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 145
PHP Warning:  class_exists() expects parameter 1 to be a valid callback, function 'ORM\Entity' not found or invalid function name in /home/clients/6d914a7d2c241e9b168e3c144fec82a0/presta/e-commerce/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 145
PHP Warning:  class_exists() expects parameter 1 to be a valid callback, function 'PassVsprintf' not found or invalid function name in /home/clients/6d914a7d2c241e9b168e3c144fec82a0/presta/e-commerce/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 145
PHP Warning:  class_exists() expects parameter 1 to be a valid callback, function 'Doctrine\ORM\Mapping\Table' not found or invalid function name in /home/clients/6d914a7d2c241e9b168e3c144fec82a0/presta/e-commerce/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 145

In AnnotationException.php line 54:
                                                                                                                
  [Semantical Error] The annotation "@Doctrine\ORM\Mapping\Table" in class PrestaShopBundle\Entity\Translation  
   does not exist, or could not be auto-loaded.  
```

**Comment by khouloudbelguith** [comment]
@L3o-pold, could you please try to go to your Projet_Folder/src/PrestaShopBundle\Entity\Translation.php

Search for this expression `Table` and check it is displayed like that
 `* @ORM\Table(` 
not like this
 `* @ORM/Table(`
Thanks to check & feedback.

**Comment by L3o-pold** [comment]
```
/**
 * Translation.
 *
 * @ORM\Table(
 *     indexes={@ORM\Index(name="key", columns={"domain"})},
 * )
 * @ORM\Entity(repositoryClass="PrestaShopBundle\Entity\Repository\TranslationRepository")
 * @PassVsprintf
 */
```
I installed Prestashop 1.7.5.1 zip from the official website

**Comment by khouloudbelguith** [comment]
@L3o-pold, thanks for your feedback.
Yes, but I said before, in my case, PS1.7.5.1 is well installed with PHP5.6.32.
I will try to install it again with PHP5.6.40 & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
@L3o-pold, I tried also with PHP 5.6.40 & ps1.7.5.1 is successfully installed, here's my PHP info file
[phpinfo().pdf](https://github.com/PrestaShop/PrestaShop/files/2927218/phpinfo.pdf)
![image](https://user-images.githubusercontent.com/16067358/53746548-b347e180-3ea1-11e9-8589-f1829ff4a8f9.png)

Thanks!

**Comment by L3o-pold** [comment]
@khouloudbelguith I'll try to find the time to debug this myself.
If not we'll disable Prestashop 1.7.5.x for our client on their shared web hosting.

**Comment by khouloudbelguith** [comment]
@L3o-pold, thanks!
Waiting for your feedback.

**Comment by L3o-pold** [comment]
@khouloudbelguith Sorry I don't know where can be the issue. I'm not a Symfony or Annotation expert. 
We'll disable Prestashop 1.7.5.x for ou clients, maybe someone will be able to catch the thing.

Feel free to close the issue

**Comment by khouloudbelguith** [comment]
Hi @L3o-pold,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by L3o-pold** [comment]
@khouloudbelguith FYI we are one of the most important web hosting of Switzerland. Feels bad to disable Prestashop 1.7.5.x with PHP 5.6 on our side but we have to...
Thanks for your time.

**Comment by khouloudbelguith** [comment]
@L3o-pold, I tried to install PS1.7.5.1 with PHP 5.6.40 & PHP5.6.32 & it is OK.
In fact, all contributions are tested automatically with PHP 5.6, 7.0 and 7.1 and for PrestaShop 1.7.4/ PS1.7.5 are also tested with PHP 7.2.
Thanks!

**Comment by L3o-pold** [comment]
@khouloudbelguith I understand that, BUT it's still an issue. Maybe on our server side configuration but we can't investigate further without more idea from your side. You know better your product than ourself (even if I'm a Prestashop 1.6 expert). If you could not ask us more details to investigate, we'll not go further. We are a hosting not some developer trying to debug their website.

BTW it works like a charm with PHP7.0 and greater.

**Comment by khouloudbelguith** [comment]
@L3o-pold, Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by L3o-pold** [comment]
@khouloudbelguith 

![capture d ecran 2019-03-05 a 16 08 01](https://user-images.githubusercontent.com/4710495/53814927-ea30fc80-3f60-11e9-83d3-98c56b25ec2c.png)

**Comment by khouloudbelguith** [comment]
@L3o-pold, thanks for your feedback.
@marionf, can you try to reproduce the issue, in my case, it is OK.
Thanks!

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Comment by L3o-pold** [comment]
@marionf OK we disabled Prestashop 1.7.5.x this morning anyway ;)
