### ISSUE TITLE
Improve product images management in basic settings tab

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#12773]
**Is your feature request related to a problem? Please describe.**
When adding or editing a product in back office, users can add multiple images at a time, but it is not possible to delete or update multiple images at a time. You cannot select more than one.
Delete images in bulk would be very useful, specially now that we are not able to duplicate products ignoring its images anymore (it was an option in PS 1.6).

**Describe the solution you'd like**
I am not sure this is a possibility with dropzone, but it would be nice if you could select multiple images by pressing ctrl key while clicking the preview images.
When two or more images were selected, the "Image cover" check box, of course, should be disabled, and "Zoom" link too. But you could be able to write a caption and save, or delete in bulk.

## MOCKUPS
https://invis.io/FNUG4HDJRVH

## SPECS

1) If one image is selected, the frame on the right is opened with:
- The number of images selected _(NEW)_
- A "Select all" link allowing to select all images _(NEW)_
- The "zoom" button opens the selected image of the list zoomed
- A “delete” button to delete the selected image. When you click on it, you have a modal for cancel or confirm the action.
- The cross to close the frame and unselect the selected image
- caption field: You can enter a caption which will be applied to all images. If some selected images already had captions, they are replaced when clicking on Save. 
- "Use as cover image" checkbox

2) _(NEW)_ You can select many images with the checkboxes. After selecting more than one image, the frame on the right is opened with:
- The number of images selected
- An "Unselect all" link to unselect images and close the frame
- The "zoom" button to open the first image of the list zoomed
- A “delete all” button to delete all the product images. When you click on “delete all”, you have a modal for cancel or confirm the action.
- The cross to close the frame and unselect images
- caption field: You can enter a caption which will be applied to all images. If some selected images already had captions, they are replaced when clicking on Save. 

If more than one image is selected the checkbox "cover" disappears
**The drag icon isn't displayed when many images are selected and you can't move many images**

3) _(NEW)_  Add the possibility to navigate between multiple images in zoom view   
Merchants should be able to navigate between several pictures to have an easy last check before saving the page.

![Design specs product images bloc](https://user-images.githubusercontent.com/27484094/67104037-86dd9d00-f1c6-11e9-92ab-032c8a3485bc.jpg)

**Comment by khouloudbelguith** [comment]
Hi @rblaurin,

Thanks for your suggestion.
@marionf, @colinegin, what do you think?
I think it could be a good improvement.

Related previous ticket: http://forge.prestashop.com/browse/FF-74
Thanks!

**Comment by ghost** [comment]
Hi @rblaurin,

Thanks for your feedback 👍 !
I'll look into it.

In order to define the best solution, can you tell me a bit more about how you want to use it, is it when you duplicate products only or you have other use cases in mind?

Also, do you use the "import" feature to manage your catalog?

Thanks

**Comment by rblaurin** [comment]
Hi, @samuel-pires,
Not only when I duplicate products. It would be useful when I add wrong images, or when the product images are outdated, or when you don't sell a product color anymore, for instance.
Personally, I don't use the import feature.

**Comment by ghost** [comment]
@PrestaShop/prestashop-core-developers Would it be quick/easy to implement the ctrl+select option and allow bulk actions on the product page?

**Comment by eternoendless** [comment]
An attempt was made but it was [left unfinished](https://github.com/PrestaShop/PrestaShop/pull/7890). It could be picked up and finished -- but don't think its "quick/easy".

**Comment by ghost** [comment]
Thanks @eternoendless,
Do you think it is better to work on it before or after we migrate the product page?

**Comment by ghost** [comment]
Hi @MatShir,
Do you think we could add this improvement to the product page rework?

It has been mentioned in #13397 as well

**Comment by marionf** [comment]
We have a duplicate for combinations here: https://github.com/PrestaShop/PrestaShop/issues/14034

**Comment by marionf** [comment]
Specs for this improvement:

1) If one image is selected, the frame on the right is opened with:
- The number of images selected _(NEW)_
- A "Select all" link allowing to select all images _(NEW)_
- The "zoom" button opens the selected image of the list zoomed
- A “delete” button to delete the selected image. When you click on it, you have a modal for cancel or confirm the action.
- The cross to close the frame and unselect the selected image
- caption field: You can enter a caption which will be applied to all images. If some selected images already had captions, they are replaced when clicking on Save. 
- "Use as cover image" checkbox

2) _(NEW)_ You can select many images with the checkboxes. After selecting more than one image, the frame on the right is opened with:
- The number of images selected
- An "Unselect all" link to unselect images and close the frame
- The "zoom" button to open the first image of the list zoomed
- A “delete all” button to delete all the product images. When you click on “delete all”, you have a modal for cancel or confirm the action.
- The cross to close the frame and unselect images
- caption field: You can enter a caption which will be applied to all images. If some selected images already had captions, they are replaced when clicking on Save. 

If more than one image is selected the checkbox "cover" disappears

3) _(NEW)_  Add the possibility to navigate between multiple images in zoom view   
Merchants should be able to navigate between several pictures to have an easy last check before saving the page.

**Comment by kandiaga** [comment]
Hi,
We   have   developed   a module  that   allows   to  delete multiple  images  at  a  time  for a  given  product.
You can   now   bulk   delete  product   images  with  no issue.
Please   find   the  module from  the  forum :  https://www.prestashop.com/forums/topic/1015827-module-bulk-delete-product-images-for-17-and-16/

**Comment by ttoine** [comment]
Hello, advertisement is not welcome here: this is a platform to contribute to the PrestaShop open source project, not a place to promote your modules and services.
Your post has been reported to GitHub.
Please follow the code of conduct and do not try again.

**Comment by NoZTurn** [comment]
I add a new suggestion.

Now, if you want to do replace an image, you have to delete an image and then upload a new one, then accociate the new uploaded image to the its related combinations.

So I suggest if we can add an option in a proper process, that upload and replace a specific image with a new one, this is better than delete an image and upload a new one, espcially in the case that one image is accociated with many combinations.

With the new feature added, it's much more simple, you just need upload and replace a new one, and all its accociated combinations relationships remain the same.

About where to place the option, I give 2 suggestions:
1)when click on one image there pops an upload image window, after we select a image, the new image will replace the clicked one while the image_id and its accociated combinations relationships remain the same.
2)considering now when we click one image, the option result is select one image, so to avoid the conflict, we can add the upload and replace option on the frame on the right when one image is selected.

**Comment by MatShir** [comment]
Checkout the product V2 in the experimental feature, the feature has been implemented :) 🚀
