### ISSUE TITLE
Cannot login into the back office

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#12770]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

Several days after auto-upgrading from 1.7.5.0 to 1.7.5.1, I encounter this issue now. It worked well couple of days after the upgrading till today.

![screen shot 2019-03-02 at 1 23 57 pm](https://user-images.githubusercontent.com/6930263/53677673-e007c780-3cee-11e9-816f-d3dc52909a74.png)

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by TomHsiung** [comment]
I fixed this issue by deleting:

`rm .../config/xml/default_country_modules_list.xml`

- Tom

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

This is a cache issue.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by TomHsiung** [comment]
It happened again.

**Comment by khouloudbelguith** [comment]
@TomHsiung, as I said before, this is a cache issue.
Try to delete the file `default_country_modules_list.xml`, it will be generated automatically again.
THanks!
