### ISSUE TITLE
Problème bloc information client

### ISSUE THREAD

**Issue by andreepi** [PrestaShop/PrestaShop#12778]
Bonjour,

Mon bloc information clients s'est décalé vers le bas. Je n'arrive pas à le remonter.
[Ecran boutique.pdf](https://github.com/PrestaShop/PrestaShop/files/2922977/Ecran.boutique.pdf)

https://se-soigner-nature.com/

Merci

**Comment by andreepi** [comment]
Bonjour,

Je n'ai plus accès à l'expertise prestashop : "Contrôleur introuvable"
Je ne comprends pas pourquoi.
Merci de m'aider.

**Comment by khouloudbelguith** [comment]
Hi @andreepi,

About your block, could you please navigate to your BO => Design => Positions => search for your "user information" module & try to reorder the position of this module.
About your second problem, have you a problem in the BO => Shop Parameters => Merchant Expertise page? if yes, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)

Thanks!

**Comment by andreepi** [comment]
Hello,

Thank you, I managed to put my blocks back correctly.
Yesterday, impossible and today is ok.

In "Administration - expertise prestashop", there is "Controller not found".

And I would like to set up shipping costs for France at 2 euros. Despite
the introduction of the carrier with elements, it does not take me into
account.
I do not understand why.

Thanks a lot for your help


*Se Soigner NatureA. Pierdon*



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 4 mars 2019 à 09:05, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by andreepi** [comment]
Hello,

I have another question. On mobile, I would like to put a drop-down menu
instead of its full display. Could you tell me how?

thank you so much

*Se Soigner NatureA. Pierdon*



Le lun. 4 mars 2019 à 09:05, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by andreepi** [comment]
Hello,

I also have a "bug" in the footer: customer information.
promotion, new products and best sellers are not checked in the block yet
they appear.
I tried everything to rectify without success.
Would you know what's going on?


thank you so much

*Se Soigner NatureA. Pierdon*



Le lun. 4 mars 2019 à 09:05, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
Hi @andreepi,

About the

> Administration - expertise prestashop

Try to re-install the gamification module & clear cache.

>And I would like to set up shipping costs for France at 2 euros

You would like to edit this only for france or the all the Europe zone?
If for the europe zone, you can edit your carrier, in the second Tab, select Europe for the ranges
![image](https://user-images.githubusercontent.com/16067358/53729192-d7d99480-3e74-11e9-82c0-fe65f4c8b4fd.png)
If, you want only for france, you can manually create a zone that contains only "France" & in the carriers page, select this zone.
Thanks!

About the other issues, could you please provide me your exact version PrestaShop, some screeshots,.. to understand how to reproduce the issue.
Thanks!

**Comment by andreepi** [comment]
Hello,

Thank you. It's OK for "prestashop expertise"

For shipping costs, that's what I did. But he does not take it into account.

Informations :
[image: image.png]

Version Prestashop : 1.6.1.18
<https://se-soigner-nature.com/vgfueoguy6hmplmt/index.php?controller=AdminDashboard&token=588c86221d22539c8a4e993122c0d57a>

thank you so much

*Se Soigner NatureA. Pierdon*



Le lun. 4 mars 2019 à 12:01, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@andreepi, I did not manage to reproduce the issue with PS1.6.1.23.
I attached a video record.
https://drive.google.com/file/d/1-YLZVBUN08k1PYUkjR_HltDH-Cif0Poc/view
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.
Thanks for your understanding!
