### ISSUE TITLE
BackOffice Cookie does not have the secure flag set when SSL is enforced

### ISSUE THREAD

**Issue by molearnik** [PrestaShop/PrestaShop#12783]
**Description**
PROD PrestaShop instances are usually configured to enable SSL on all pages. In that case all Cookie objects should be constructed with "secure" flag in order browsers never send such a cookie over HTTP. Hereby the overall security would be further augmented (regardless of other security controls like the actual Cookie encryption) with very little DEV effort. In addition, security web app scanners will stop reporting "Cookie Vulnerability" and scare some merchants. So, the fix is worth of some small effort.

In https://github.com/PrestaShop/PrestaShop/blob/develop/config/config.inc.php it seems that BackOffice cookie (unlike Front Office one) is constructed always without the secure flag.

//  $force_ssl should be initialized a little bit earlier and applied in the 1st (Admin) Cookie constructor below (the code snippet is taken from mentioned Config.inc.php).
```
if (defined('_PS_ADMIN_DIR_')) {
    $cookie = new Cookie('psAdmin', '', $cookie_lifetime); // BUG
} else {
    $force_ssl = Configuration::get('PS_SSL_ENABLED') && Configuration::get('PS_SSL_ENABLED_EVERYWHERE');
    if ($context->shop->getGroup()->share_order) {
        $cookie = new Cookie('ps-sg'.$context->shop->getGroup()->id, '', $cookie_lifetime, $context->shop->getUrlsSharedCart(), false, $force_ssl);
    } else {
        $domains = null;
        if ($context->shop->domain != $context->shop->domain_ssl) {
            $domains = array($context->shop->domain_ssl, $context->shop->domain);
        }
        $cookie = new Cookie('ps-s'.$context->shop->id, '', $cookie_lifetime, $domains, false, $force_ssl);
    }
}
```
**To Reproduce**
Pre-conditions:
Have a PrestaShop instance that has "Enable SSL" and "Enable SSL on all pages" set to TRUE in the "Shop Parameters -> General" configuration screen

Steps to reproduce:
1. Go to any Admin page / Back Office.
2. Check the PrestaShop-* cookie attributes e.g. in Chrome: Open Dev Tools & Go to Application Tab & Click Storage / Cookies in the left men

Results: PrestaShop-* cookie does not have Secure flag set => Browser would send the Cookie over HTTP too

Expected Behavior: All PrestaShop-* cookies will have Secure flag set

**Additionnal information**
PrestaShop version: Any
PHP version: Any

**Comment by khouloudbelguith** [comment]
Hi  @molearnik,

Thanks for your report.
Could you please confirm these steps:
1. SSL enabled / SSL enabled on all page
2. When I navigate to the BO
In the Dev Tools => Application Tab => Click Storage / Cookies
I have 
![image](https://user-images.githubusercontent.com/16067358/53739065-2563fa80-3e91-11e9-8e68-ef7f1ff95042.png)

Thanks!

**Comment by molearnik** [comment]
I can confirm these steps - although I was referring only to PrestaShop-* cookie ("Admin-context") that may hold various states of business process flows. 
I guess PrestaShop code cannot "secure" PHPSESSID cookie programmatically. That can be "secured" in php.ini (http://php.net/manual/en/session.configuration.php#ini.session.cookie-secure).
I didn't see PSDOTCOM42 cookie on a test environment.

Remark: 
I know my issue does not report real Cookie vulnerability because there is rather strong encryption of cookie content employed (I guess this encryption uses unique key generated for each prestashop instance programmatically) and I don't know how some attacker would be able to read the Cookie content relatively easily even if the attacker managed to force user's browser to send the cookie over HTTP. 
So, the fix would be more about compliance with good security practices. That means you would "only" get nicer results from vulnerability scanners and the nicer results should please more merchants. That's a reason to invest very little DEV effort required while no side-effects are expected.

**Comment by khouloudbelguith** [comment]
@molearnik, thanks for your feedback.
So, the issue occurs only with `PrestaShop-e05fde` which does not have Secure flag set? is it?
Thanks!

**Comment by molearnik** [comment]
You are right.

**Comment by khouloudbelguith** [comment]
@molearnik, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
When SSL enabled / SSL enabled on all page, When I navigate to the BO, In the Dev Tools => Application Tab => Click Storage / Cookies
`PrestaShop-*` cookie does not have Secure flag set and the browser send the Cookie over HTTP as described in the screenshot
![image](https://user-images.githubusercontent.com/16067358/53796297-21d57f80-3f34-11e9-8f48-61fcaa4a33f8.png)
Similar issue reported on forge: http://forge.prestashop.com/browse/BOOM-2911
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by meomay** [comment]
@khouloudbelguith I saw this issue also appear on PS1.7.3.1
