### ISSUE TITLE
CMS pages in prestashop 1.7 load in white

### ISSUE THREAD

**Issue by infopavon** [PrestaShop/PrestaShop#12790]
Good afternoon,

We are using Prestashop 1.7.5 and the CMS pages do not load the content. Why? Is it a bug?

Web: https://lasmarcasdemoda.com

CMS page: https://lasmarcasdemoda.com/content/7-entrega-y-envio

Thank you.

I wait for news.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
Hi @infopavon,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1lGnDAcfKkPS2TnHdUuP0nOlbsU8WXg2p/view
Did you use a multilanguage?
Thanks!

**Comment by infopavon** [comment]
Hi @khouloudbelguith,

We are using Prestashop 1.7.5.0. Is it advisable to update?

We have entered in localization => Languages ​​and we only have active the Spanish language. You mean that, right?

Thank you.

I wait for news.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
@infopavon, I tried with PS1.7.5.0 & it is OK also.

>You mean that, right?

Yes, I mean that.
Have you tried to contact the theme author about this issue?
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

Who is the author of the topic?

Thank you.

I wait for news.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, did you contact them?
You are waiting for their feedback?
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

No, who do I have to contact?

Can you contact them?

Thank you.

I need to solve the problem as soon as possible.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, could you please navigate to your BO => Design => Theme & Logo page & provide me the theme & theme author in use.
Thanks!

**Comment by infopavon** [comment]
Good Morning

The theme is Warehouse.

Is the issue that is causing problems?

If so, can not a .tpl file be renamed so that it loads the file from the prestashop pages instead of the theme file?

Thank you.

I wait for news.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, thanks!
Could you please confirm these steps:
1. In the BO => Design => Pages => you created a page in the Spain language.
2. If you click on the " Save and preview" button, you are not redirected to the FO & page is well displayed?
![image](https://user-images.githubusercontent.com/16067358/53798841-57c93280-3f39-11e9-8556-3f00cd5899b3.png)
Thanks!

**Comment by infopavon** [comment]
Good Morning,

First, I tried to create a page only in the English language and then I have given the button to save and preview but it has returned this error:

![image](https://user-images.githubusercontent.com/37174407/53803108-fd819f00-3f43-11e9-9ab4-436f6bce714c.png)

The system tells me that I must also fill out the page in the Spanish language, once I have filled in the Spanish language, I have returned to select the English language and I have given it to save and show, but the content will also appear empty.

![image](https://user-images.githubusercontent.com/37174407/53803174-3588e200-3f44-11e9-9e45-a374a72d05d8.png)

![image](https://user-images.githubusercontent.com/37174407/53803286-87ca0300-3f44-11e9-8ce4-aca8550b5a72.png)

![image](https://user-images.githubusercontent.com/37174407/53803298-931d2e80-3f44-11e9-85b9-66eb26c17692.png)

I also attach a list of activated / deactivated languages.

![image](https://user-images.githubusercontent.com/37174407/53803361-cb247180-3f44-11e9-8a95-d933f3ea7dba.png)


Thank you.

I await your news.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
Hi @infopavon,

You are creating your page when English is selected, you need to select Spanish language & set the description of your page
![image](https://user-images.githubusercontent.com/16067358/53811116-e7caa480-3f58-11e9-960a-7e836fd2d080.png)
I attached a video record.
https://drive.google.com/file/d/1d7oPWmYMVjnfqTyUM2bFiqKorJNDXQWt/view
About the red alert, you cannot create a page with empty friendly URL.
Thanks to check & feedback.

**Comment by infopavon** [comment]
Good Afernoon,

Thanks for your fast answer.

So I created it but it did not work. I created it in English because I thought you were telling me to do it in the English language.

Now I believe it in Spanish like this:

![image](https://user-images.githubusercontent.com/37174407/53812001-d08cb680-3f5a-11e9-98c5-f1a7a6645e1c.png)

but it still does not work.

![image](https://user-images.githubusercontent.com/37174407/53812113-15b0e880-3f5b-11e9-94d0-5db79c6c84a7.png)

Why?

We can not rename the .tpl that loads and that and put another one?

Thanks for your reply.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, Could you please provide me your credentials to check your shop.
This is a public space.
You can provide me the link by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
@infopavon, I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
@infopavon, I found another issue in your shop
![image](https://user-images.githubusercontent.com/16067358/53816052-29f8e380-3f63-11e9-892f-a292a994ea7e.png)
it is not related to this issue, you should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

About your issue reported on this ticket, I did not manage to reproduce the issue 
1. 
![image](https://user-images.githubusercontent.com/16067358/53816203-77755080-3f63-11e9-8181-bad49be8992b.png)
2.
 ![image](https://user-images.githubusercontent.com/16067358/53816244-8956f380-3f63-11e9-8f89-77dbc4c81584.png)
3. A custom theme
![image](https://user-images.githubusercontent.com/16067358/53816284-983da600-3f63-11e9-8bd4-c1ea5751317b.png)
4. Classic theme
![image](https://user-images.githubusercontent.com/16067358/53816351-b4414780-3f63-11e9-96bb-fc04baea13f5.png)

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by infopavon** [comment]
Good afternoon,

I have uninstalled and removed this module from our system.

We have activated the classic theme of Prestashop 1.7.5 but the pages still look the same, blank.

Can you take a look, please?

Thank you.

I appreciate your help.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, your link is not accessible for now.
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

If it is. Try the Mozilla Firefox browser.

Thanks for your help.

Greetings,

**Comment by khouloudbelguith** [comment]
Hi @infopavon,

I tried with Firefox => Same issue.
![image](https://user-images.githubusercontent.com/16067358/53865675-08920900-3ff0-11e9-9561-aaf11550bdfe.png)

Thanks!

**Comment by infopavon** [comment]
Good Morning,

The page works correctly. Can you clear the cache, please?

Since which IP address is the connection made?

Thank you.

I wait for news.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
@infopavon, Thanks!
Waiting for your feedback.

**Comment by infopavon** [comment]
Good Morning,

The page works correctly. Can you clear the cache, please?

Since which IP address is the connection made?

Thank you.

I wait for news.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
@infopavon, I need to clear cache from your shop?
What is the exact cache I need to clear?
My last Login IP Address 197.14.53.186
Thanks!

**Comment by infopavon** [comment]
Good Morning,

You must delete the browser history of your browser.

Your IP is not blocked.

Tell me if he let you see the store after performing these steps.

If not, can you connect to my team through Teamviwer or Anydesk?

Thanks for your help.

Best Regards, Rafael M.

**Comment by khouloudbelguith** [comment]
Hi @infopavon,

I cleared the cache from my browser => still same error.
Please be aware that the GitHub should be used to report PrestaShop issues only. 
We don't need to connect your team.
The cms page is working correctly now?
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

We have enabled your IP in the Geolocation section of Prestashop.

Can you try now?

No, the pages do not work yet.

Thank you.

Greetings, Rafael M.

**Comment by khouloudbelguith** [comment]
@infopavon, sorry, I tried again.
But always the same issue, I cannot access to your BO / FO.
I have this error `ERR_CONNECTION_TIMED_OUT`
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

I'll check with the webmaster if it's something from the server.

You are connecting from Austria, right?

Although I think it's a browser problem. Look at this link:

https://www.softzone.es/2018/09/22/como-solucionar-el-error-err_connection-timed-out-en-chrome/

Thanks.

**Comment by khouloudbelguith** [comment]
@infopavon, no I'm not from Austria.
This issue occurs only with your shop.
Thanks!

**Comment by infopavon** [comment]
Good afternoon,

Can you indicate from which country you connect, please?

Thank you.

Greetings,

**Comment by khouloudbelguith** [comment]
@infopavon, thanks!
the link is accessible now.
I tried with your shop with the classic theme & it is OK.
![image](https://user-images.githubusercontent.com/16067358/53899759-36e90600-403b-11e9-858c-40a67af8b791.png)
I sent you a screen-record by email.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
