### ISSUE TITLE
Problem PS 1.7.5 Search Console

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12806]
**Describe the bug**
Hello everyone, I have a problem with Google Search Console because it asks me to insert offers", "review" o "aggregateRating" on my products. Do you know how to insert it?
Should I need a module?

Hope you can help me

Thanks

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Your ticket is a duplicate of #12687
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #12687
