### ISSUE TITLE
[1.7.5.1]Cache issue with translations

### ISSUE THREAD

**Issue by pedluis** [PrestaShop/PrestaShop#12819]
**Describe the bug**
Hello, we are developing our new website with prestashop 1.7.5.1, unfortunately we have found an issue with translations. If you switch from the English version to Italian for example, many string remains in English, if you refresh again the page the content is correctly in Italian.
**To Reproduce**
1. Go to 'https://prova.ferrarisboutique.com/it/sneakers-donna/sneaker-olympia-trainer-rosa-michael-kors.html'
2. Switch to English for example, and you can see that some strings remains in Italian, the same bug if you switch into other languages

**Screenshots**
https://snag.gy/C9o1TQ.jpg

In the screenshot as you can see the url is set to the spanish version but there are many strings in German. 
**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @pedluis,

Have you the same issue reported in this ticket: #9652?
Do you have the issue with each module? ps_categoryproducts module?
Thanks!

**Comment by pedluis** [comment]
Hi @khouloudbelguith ,
I've already found that thread, but in my case the issue cover the theme and not only a module.

Any suggestion?
Thanks!

**Comment by khouloudbelguith** [comment]
@pedluis, did you use the default theme Classic provided by PrestaShop?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @pedluis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
