### ISSUE TITLE
Product Combinations not loading for some products in Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by hacchus** [PrestaShop/PrestaShop#12815]
Combinations for most products are not loading in back-office. The drop-down "Bulk actions (0/3 combination(s) selected)" remains grayed out and if I place the mouse over it, it keeps spinning forever.

If I turn on debug then in the place of combinations I get the message:

**[Debug] This page has moved
Please use the following URL instead: https://www.mysitename.com/en/root**

No other errors in Web Console or PHP error logs.

1. This was a clean 1.7.5.0 installation that I upgraded to 1.7.5.1.
2. The products were all entered through importing using the native Prestashop Import page
3. In the front all products with combinations work as expected without problems.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment]
Hi @hacchus,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version: did you used the 1-click upgrade?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hacchus** [comment]
I'm on a Litespeed server on A2Hosting.
I used 1 click to update from 1.7.5.0 to 1.7.5.1.


This is the screenshot when I have debug on:

![debug](https://user-images.githubusercontent.com/5149317/53944850-e1f3d100-40c8-11e9-80c3-5f71ecd6c09d.png)

**Comment by khouloudbelguith** [comment]
@hacchus, did you enabled debug mode from the BO => Advanced Parameters => Performance page?
Thanks!

**Comment by hacchus** [comment]
Yes

**Comment by hacchus** [comment]
Something that I just noticed and might be important, is that all my products with 2 combinations are showing correctly, but everything with 3 or more combinations is not.

**Comment by hacchus** [comment]
@khouloudbelguith OK I think I found the issue. If I disable the "URL Cleaner- SEO Performance Module" from Prestashop then all of my combinations work. But I don't know why this is happening.

**Comment by khouloudbelguith** [comment]
@hacchus, this is a module bought from our market place PrestaShop?
Thanks!

**Comment by hacchus** [comment]
Yes this one: https://addons.prestashop.com/en/seo-natural-search-engine-optimization/25758-url-cleaner-seo-performance.html

**Comment by khouloudbelguith** [comment]
@hacchus, as it's not a native module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
