### ISSUE TITLE
Circuit Breaker - Page Dashboard - Asynchronous Calls for Gamification JSON files  

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12828]
**Context**
The API call is used for the generation of 
- partner module advices in the dasboard : 
![image](https://user-images.githubusercontent.com/35263827/84800988-e498e200-affe-11ea-8e62-ad677ce96e25.png)

- badges in the gamification module :
![image](https://user-images.githubusercontent.com/35263827/84800932-cd59f480-affe-11ea-9513-c333d6d0f9ac.png)

## Call info

**When is the call made?**
After the Login Page - Asynchro

**At which frequency is it made?**
Every 24h or when not in the cache

**Cache expiration frequency**
24h

## Expected Behavior

**What to do if the service is unreachable and never was**
- display no partner module blocks on the dashboard
- display "No badge available" in the gamification block and page

**What to do if the service is unreachable but old data is stored in cache**
Display old data stored for partner modules in cache IF valid.
Display nothing for partner modules if data in cache is invalid.

Display old data stored for badges in cache IF valid.
Display "No bagde available" if data in cache is invalid.

**What to do if the service responds with invalid data**
Display the latest partner modules and badges available

**What to do if the service responds with an error**
Same behaviour as when unreachable + log the error

## Request parameters
**Call frequency**
Every 24h or when not in the cache

**Timeout**
0.3s

**Max Failures**
3

**Threshold**
12h

**Comment by colinegin** [comment]
@MatShir @samuel-pires can you tell us what's the status of this issue ?

**Comment by ghost** [comment]
It has to be specified but it is not in top priority because this call is already asynchronous, so it doesn't block the Dashboard page loading if the API is down. 
It's more about what to display if the API is down than Circuit Breaker parameters, I believe.

**Comment by colinegin** [comment]
ping @atomiix can you confirm these calls are made in the Gamification module ?

**Comment by atomiix** [comment]
@colinegin yes!

**Comment by colinegin** [comment]
Alright then, I remove the issue from the 177 kanban ;)

**Comment by Progi1984** [comment]
@MatShir  Sorry the module `gamification` is now managed by the `PrestaShopCorp` organization. Could you create a new issue on their issues board : https://github.com/PrestaShopCorp/gamification/issues/new ? Thank you for your help.
