### ISSUE TITLE
[PrestaShopException]

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#12820]
Hi Again!
I have a problem with a client, He deleted a Root category, and after he wanted see the products and prestashop show this error.
![imagen](https://user-images.githubusercontent.com/14195668/53955490-70704e80-40d9-11e9-852e-7fa06ae9aad1.png)

I need to fix this error for after updating the version.

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

How did you delete the root category? from the Database?
Thanks!

**Comment by juank2808** [comment]
the root category is in the database but is deleted in the backoffice, i dont know, this is very confusing, cause i have restored the root category but still showing the same error.

**Comment by khouloudbelguith** [comment]
@juank2808, in your database, the table `ps_category`, you need to check that the column `is_root_category` set to 1.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
