### ISSUE TITLE
We can make Logs page fail with a bad URL

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12835]
**Describe the bug**
Logs BO page can be broken if we toy with the GET filter parameters.

**To Reproduce**
1. Go to BO Logs page, URL should be something like `http://localhost/admin-dev/index.php/configure/advanced/logs/`
2. Perform a filter search, for example filter logs on the word "Back", the URL should be something like
`http://localhost/admin-dev/index.php/configure/advanced/logs/?filters%5Bmessage%5D=Back&_token=[your token]` 
3. Modify this URL :trollface: replace "message" by "mossage"
4. Refresh with the modified URL, you get a HTTP 500 error

PrestaShop version: `develop`

**Comment by khouloudbelguith** [comment]
Hi @matks,

Same issue with PS1.7.5.1 & PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/54015596-710ff000-4180-11e9-87bd-b4f763d20f87.png)
In the PS1.7.4.4, we don't have the same behavior.
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14450
