### ISSUE TITLE
CB - Page Login/Dashboard -  call for Tips & Updates section

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12830]
**Context**
Every time the Dashboard page is loaded, a call to the Addons API is made to get the "weekly advice" plus a link to the Addons website. (The link sends to a list of modules related to the advice)

The Weekly advice is displayed on the Dashboard, in the "Tips & Updates" section once the user is connected to Addons.

Tips can be changed every week or not (few weeks without new advice)

The "practical links" part is always the same and does not rely on the call.

![Capture d’écran 2019-04-30 à 09 13 55](https://user-images.githubusercontent.com/47456895/56946688-1d3fd880-6b2b-11e9-92ac-8d73f9c2d052.png)

![Capture d’écran 2019-04-30 à 09 14 19](https://user-images.githubusercontent.com/47456895/56946691-1f099c00-6b2b-11e9-8e08-78ed2b7ec37a.png)

## Call info

**When is the call made?**
After Login form is submitted or when the dashboard is loaded.

**At which frequency is it made?**
Every time the Dashboard is loaded.

**Cache expiration frequency**
Currently no cache

**What URL or API endpoint does it call?**
https://api-addons.prestashop.com/request/?method=week_advice&iso_lang=en

## Behavior

**What to do if the service is unreachable and never was**
Display the latest tips or hide "Tip of the moment" section
![image](https://user-images.githubusercontent.com/43613217/58094326-b3b66580-7bd0-11e9-8364-37e182811ea8.png)

**What to do if the service is unreachable but old data is stored in cache**
Display old data stored in cache.

**What to do if the service responds with invalid data**
Display the latest tips or hide "Tip of the moment" section
![image](https://user-images.githubusercontent.com/43613217/58094326-b3b66580-7bd0-11e9-8364-37e182811ea8.png)

**What to do if the service responds with an error**
Log the error and display placeholder data

## Request parameters

**Call frequency**
Every 24h or when not in the cache

**Timeout**
0.3s

**Max Failures**
3

**Threshold**
12h

**Comment by MatShir** [comment]
**Issues to be fixed with the Circuit Breaker implementation:**
- [x] #10934 
- [x] #13438

**Comment by MatShir** [comment]
@Shiryu75 let's do this !

**Comment by Quetzacoalt91** [comment]
V2.0.0 of the module psaddonsconnect, released yesterday, now includes the circuit breaker. This task can be closed.
