### ISSUE TITLE
Product image position not updatable in multishop [1.6.1.23]

### ISSUE THREAD

**Issue by glictevo** [PrestaShop/PrestaShop#12832]
Description : On a multistore PrestaShop, when you manage the images of a product in the BO, you can't change the images positions if one of them is not in the default shop

1. Install PrestaShop 1.6.23
2. Go to Preferences > General > enable multistore
3. Go to Advances parameters > Multistore
4. Create a new store group with all the basic settings
5. Create a new store with all the basic settings and attach it to the newly created store group
6. Go the a product with images, in the Images tab
7. Deselect the default shop for one of the images, wait for the green update confirmation popup in the top right corner
8. Try to change the position of one image, observe the loading image in the PrestaShop logo in the top left  corner (next to PrestaShop 1.6.1.23)

The problem cause this error in the console : 
![prestashop 1 6 1 23 console error](https://user-images.githubusercontent.com/14160631/53963977-aa981b00-40ee-11e9-8190-8e66f5a5a5f8.jpg)

When looking into the request generated by the drag and drop, we can see the response :
![prestashop 1 6 1 23 request response](https://user-images.githubusercontent.com/14160631/53964073-e206c780-40ee-11e9-843b-777b673b193e.jpg)

So, what happens ? Well, here is everything that happens from the moment you change a position : 
1. The function ajaxProcessUpdateImagePosition() is called in controllers/admin/AdminProductsController.php
2. This function then calls the Image class as seen in the screenshot below
![prestashop 1 6 1 23 adminproductscontroller](https://user-images.githubusercontent.com/14160631/53964454-afa99a00-40ef-11e9-969b-495abc5e919d.jpg)
3. The __construct() function in classes/Image.php then calls the __construct() function from classes/ObjectModel.php
![prestashop 1 6 1 23 image class construct function](https://user-images.githubusercontent.com/14160631/53964643-057e4200-40f0-11e9-93d9-f1b026be3b5e.jpg)
4. This function then select the id_shop from the current Context as seen in the screenshot below
![prestashop 1 6 1 23 class objectmodel construct function](https://user-images.githubusercontent.com/14160631/53964934-93f2c380-40f0-11e9-84f3-c21588aa25dc.jpg)
5. Then it calls the load function from Adapter/Adapter_EntityMapper.php from where it does the sql request to get the image which looks like this : 
SELECT *
FROM `ps_image` a
LEFT JOIN `ps_image_shop` `c` ON a.`id_image` = c.`id_image` AND c.`id_shop` = 1
WHERE (a.`id_image` = 1)

The problem is that the id_shop is the one from the current context, and if we deselect an image from the shop with the id 1 (for this exemple), it deletes in the database in the table ps_image_shop the corresponding line which this request is trying to get.

The issue comes from the fact that the Image class construct method does not take into account the id_shop of the image.

EDIT (in case someone might want to fix this issue on their shop) :

Simple Solution : Replace the inside of the foreach loop in the ajaxProcessUpdateImagePosition() in AdminProductsController with this code
                $res &= Db::getInstance()->execute('UPDATE ' . _DB_PREFIX_ . 'image SET position = ' . $position . ' WHERE id_image = ' . $id);

**Comment by khouloudbelguith** [comment]
Hi @glictevo,

Thanks for your report.
I manage to reproduce this issue with PS1.6.1.23.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and and security fixes will be accepted in the `1.6.1.x` branch.
In the PS1.7, this behavior doesn't exist.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 

Could you try to reproduce this issue with 1.7.6.1 ?

**Comment by khouloudbelguith** [comment]
Hi @glictevo,

With PS1.6, we have a different behavior
When multistore is enabled, we can select a shop for images
![image](https://user-images.githubusercontent.com/16067358/63954001-4f7e2a00-ca7a-11e9-8c34-78c08a43fb13.png)
With PS1.7 => this feature doesn't exist
![image](https://user-images.githubusercontent.com/16067358/63954069-69b80800-ca7a-11e9-8d16-8e317467869b.png)
But we can reproduce the issue following these steps:
1. Install PrestaShop 1.7.6.1
2. Go to Preferences > General > enable multistore
3. Go to Advances parameters > Multistore
4. Create a new store group with all the basic settings
5. Create a new store with all the basic settings and attach it to the newly created store group
6. Go the product with images, in the Images tab (shop 2 is selected)
7. Add new image
8. Try to change the position of an image
9. Save => a red alert => an exception on the console
![image](https://user-images.githubusercontent.com/16067358/63954494-17c3b200-ca7b-11e9-9915-26888c16b76c.png)

I’ll add this to the debug roadmap.
Thanks!

**Comment by PierreRambaud** [comment]
Is this problem still present in the latest release?

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I did not manage to reproduce the issue with PS1772
It is ok :heavy_check_mark: 
I attached a screen record
https://drive.google.com/file/d/1ctkaTenZuonN3qiAyxiS9uhbG6tadeqr/view?usp=sharing

Since it is not reproduced, I will close the issue.

Thanks!

**Comment by julgarut** [comment]
Hi, i change the code for this:
![image](https://user-images.githubusercontent.com/80578144/111027995-f8d60800-83f3-11eb-8cfa-a8fca3ed9988.png)

But it gives me the following error "An error occurred while attempting to move this picture."

 Do you know why?
