### ISSUE TITLE
CB - Page Login - List modules call API for Recommended Modules

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12833]
## Context
The API calls the Recommended Modules at the Login Page from Prestashop API

## Call info

**When is the call made?**
After the Login Page

**At which frequency is it made?**
Every 24h or when not in the cache

**Cache expiration frequency**
24h

**What URL or API endpoint does it call?**
http://api.prestashop.com/xml/tab_modules_list_17.xml

## Behavior
The API calls must be handled by PrestaShop Marketplace in your Back Office module

## TODO
- [x] add circuit breaker for the call on MBO #14715
- [x] remove the call from the core

**Comment by MatShir** [comment]
It should be fixed by #14715. To be followed

**Comment by eternoendless** [comment]
@MatShir Keep in mind that the core will have to be updated to remove these calls after MBO is updated.
