### ISSUE TITLE
Prestashop Category order problems

### ISSUE THREAD

**Issue by MaduPRS** [PrestaShop/PrestaShop#12840]
Hi,

I would like to move the position of my main categories but when I am using the arrows of position in the right, it saves it but it doesn't appear in my site so i would like to know if you have a solution for this issue pls.

Thank You

**Comment by khouloudbelguith** [comment]
Hi, @MaduPRS,

I did not manage to reproduce the issue with PS1.7.5.1 & the ps_mainmenu module v2.1.1.
I attached a video record.
https://drive.google.com/file/d/1G4RvVZJ1p5RugPEAU636S98oI3nf8auL/view
Thanks to check & feedback.

**Comment by MaduPRS** [comment]
> Hi, @MaduPRS,
> 
> I did not manage to reproduce the issue with PS1.7.5.1 & the ps_mainmenu module v2.1.1.
> I attached a video record.
> https://drive.google.com/file/d/1G4RvVZJ1p5RugPEAU636S98oI3nf8auL/view
> Thanks to check & feedback.

Hi 

I tried but in my site nothing changed, do we have a limit of category numbers ?
Thank you for the reply

**Comment by khouloudbelguith** [comment]
@MaduPRS, How many categories in the menu you have?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by MaduPRS** [comment]
> @MaduPRS, How many categories in the menu you have?
> We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

8 
I am going to read the link

**Comment by khouloudbelguith** [comment]
@MaduPRS, thanks!
Waiting for your feedback.

**Comment by MaduPRS** [comment]
What do you need exactly ?

**Comment by khouloudbelguith** [comment]
@MaduPRS, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Having 8 categories is not a problem.
Thanks!

**Comment by MaduPRS** [comment]
https://pastebin.com/Aaid0602

**Comment by khouloudbelguith** [comment]
@MaduPRS, you have an error with the `an_brandslider` module.
Have you tried to contact the module author?
Thanks!

**Comment by MaduPRS** [comment]
https://drive.google.com/file/d/1aNeSex4ZtNVU6RVa95UYB0-jlfHR9NNQ/view?usp=sharing

**Comment by khouloudbelguith** [comment]
@MaduPRS, you need to change the position of these categories from the ps_maimenu module not from the categories page.
You need to navigate to your BO => Modules => Module Manager page => search for the ps_maimenu & click on configure, then try to change the position of the categories.
Thanks!

**Comment by MaduPRS** [comment]
I tried but it doesnt change anything
Thanks, Do you want a video ?

**Comment by khouloudbelguith** [comment]
@MaduPRS, have you a module named `amegamenu`?
Thanks!

**Comment by MaduPRS** [comment]
<img width="440" alt="capture d ecran 2019-03-08 a 16 09 30" src="https://user-images.githubusercontent.com/48350712/54036696-915da000-41bc-11e9-9a2f-0522cc61a3db.png">

I only have this one

**Comment by MaduPRS** [comment]
When i change tabs in this one it changes categories too

**Comment by khouloudbelguith** [comment]
@MaduPRS, the ps_maimenu is replaced in your case by this module which is developed by your theme.
Son, you can change the position of categories throw this module.
Thanks!

**Comment by MaduPRS** [comment]
> @MaduPRS, the ps_maimenu is replaced in your case by this module which is developed by your theme.
> Son, you can change the position of categories throw this module.
> Thanks!

Thank you very much for your help, i will be recontacting you this Monday because i have another problem

**Comment by khouloudbelguith** [comment]
@MaduPRS, thanks!
I close this issue, feel free to open a new one when needed.
Thank you!
