### ISSUE TITLE
Hide Recommended Modules on Edit/Add Pages after migration

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12846]
**Is your feature request related to a problem? Please describe.**
On edit and add pages, the button Recommended Module redirects to the Catalog Module even when the marchert has full fill some informations. It is prefereable to hide the button for the user experience and since the presence of the button on the edit and add pages is not really revelant. 

**Describe the solution you'd like**
To hide in it on all Add/Edit pages after the migration is done

**Pages concerned**
[International > Localisation > Devises > Add new / edit
](https://github.com/PrestaShop/PrestaShop/issues/10190)[Paramètres >Traffic & SEO > SEO & URL > Add new / edit
](https://github.com/PrestaShop/PrestaShop/issues/10192)[Catalogue > Catégories > Add new / edit
](https://github.com/PrestaShop/PrestaShop/issues/10194)[Clients > Clients > Add new / edit
](https://github.com/PrestaShop/PrestaShop/issues/10560)

**Comment by eternoendless** [comment]
Done for MBO in https://github.com/PrestaShop/ps_mbo/pull/87

Needs to be done in the core as well.

**Comment by matks** [comment]
@MatShir Looks like "on which page do we display 'recommanded modules' button" is controlled by configuration file `config/xml/tab_modules_list.xml` . This is where it is put for caching, but the source is probably somewhere else.

**Comment by matks** [comment]
@eternoendless I guess `tab_modules_list.xml` comes from the API, right ?

**Comment by Matt75** [comment]
@matks Yes but not from AddonsApi : https://api.prestashop.com/xml/tab_modules_list.xml (Only static files here)

**Comment by marionf** [comment]
I close this issue following the differentiation between the OS project and the company
