### ISSUE TITLE
Wrong Address Layout when Printing Order

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#12842]
With my version 1.7.5.1, when I print an order I get the address with a wrong layout like:

Name of the Person Address Zip Code etc etc etc

Instead of 

Name
Address
etc.

On the backoffice the address appears correctly. Only when I print it is wrong.

Additionnal information
PrestaShop version: 1.7.5.1
PHP version: PHP 7.0.33-0ubuntu0.16.04.1

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

In the BO => Orders => Order details => I click on "Print" order
I have this file
[Orders _ Order LBCTGKRZT from John DOE • 1751ttt.pdf](https://github.com/PrestaShop/PrestaShop/files/2945579/Orders._.Order.LBCTGKRZT.from.John.DOE.1751ttt.pdf)
Have you a wrong layout with this?
![image](https://user-images.githubusercontent.com/16067358/54026143-2a7cbe80-419d-11e9-9804-cc297b8884f1.png)

Thanks!

**Comment by seederp2p** [comment]
No!

But I found the problem. Somehow on my database, ps_address_format, there was no breaks between address elements.

**Comment by khouloudbelguith** [comment]
@seederp2p, so your issue is fixed?
Thanks!

**Comment by seederp2p** [comment]
Yes.

TY

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
