### ISSUE TITLE
To optimize Prestashop plugin 

### ISSUE THREAD

**Issue by Baptoun** [PrestaShop/PrestaShop#12849]
Hi there,

**Issue**
Our Carts Guru plugin need to be optimized. No big deal, the code just has to be simpler and clearer.

**Solution**
We are looking for a PHP developer & Prestashop expert to assist us on this. Of course, we can speak together about the benefits. 

Best,

**Comment by khouloudbelguith** [comment]
Hi @Baptoun,

Please be aware that this bug tracker GitHub should be used to report issues only.
Thanks for your understanding!
