### ISSUE TITLE
Webservice is letting create customers with same email

### ISSUE THREAD

**Issue by mowcixo** [PrestaShop/PrestaShop#12844]
**Describe the bug**

When you create two customers with same email from webservice, it doesn't throw any error. Then when you try to login with one of two customers, the login form fails.

**To Reproduce**
1. Create a customer with foo@bar.com email using webservice endpoint.
2. Create another customer with foo@bar.com email using webservice endpoint.
3. Go to login form and try to login with one of them.
4. You will receive an error.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

I would be glad to fix it if some of mantainers give me some clue about what files should be involved.

**Comment by khouloudbelguith** [comment]
Hi @mowcixo,

Yes I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
I used this script

```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 08/13/19
 * Time: 14:44
 */

ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
//                      !! BACHA, nezapomenout přenastavit i DTB u obrázků dole !!!
define('PS_SHOP_PATH', 'http://shop/'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$psXML = <<<XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
 <customer>
   <email>test@test.com</email>
   <firstname>khouloud</firstname>
   <lastname>belguith</lastname>
   <passwd>abc123</passwd>
 </customer>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'customers' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
for ($i = 1; $i <= 2; $i++) {
    $xml = $webService->add( $opt );
}
```
Which I can create two customers with same informations successfully.
But, in Fo, I have an error in FO.
![image](https://user-images.githubusercontent.com/16067358/54032823-fb714780-41b2-11e9-9bef-36bbe14216cb.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with 1.7.6.x ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, I manage to reproduce the issue with PS1.7.6.0beta1
https://drive.google.com/file/d/1XrZwxiXf4Fh1DHSwJPizbw4TPU_ukVCr/view
Thanks!

**Comment by Mch0** [comment]
Can i submit a merge request to fix that?

**Comment by marionf** [comment]
Hello @Mch0 

Yes, sure, you can make a pull request on GitHub with your code suggestion:
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16553
