### ISSUE TITLE
CR - Page Dashboard - Asynchronous Calls for Gamification CSS files

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12848]
## Current behavior

The gamification JSON file (see [#12828](https://github.com/PrestaShop/PrestaShop/issues/12828)) is called and stored in cache every 24 hours, or when not in the cache.
The JSON file refers to several CSS files that are called to adapt dynamically the style of the gamification. 
Currently, 49 calls are made to get these CSS files. All of these 49 CSS files are empty

**When is the call made?**
Asynchro.

**At which frequency is it made?**
Called and stored in cache every 24 hours, or when not in cache. Right after the gamification call to get the JSON file is made (see [#12828](https://github.com/PrestaShop/PrestaShop/issues/12828)).

**What API does it call?**
gamification.prestashop (???).

**Why is it used for?**
The CSS files are used to adapt dynamically the style of the gamification.

**impact on loading time**
Difficult to evaluate.

## Expected behavior

Because the CSS files have been empty for a while now and there are no plans to use them, we want to delete these 49 calls.

**Comment by eternoendless** [comment]
Done in https://github.com/PrestaShop/gamification/pull/64
