### ISSUE TITLE
Gift wrapping wrongly displayed in cart

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#12857]
**Describe the bug**
I believe that this is a bug simply because I believe that the Gift wrapping should NOT be displayed in cart if GiftWrappingPrice = 0. In some countries it is not possible to display product or service with 0 price (or free).
I think that logic tells to display price only if GiftWrappingPrice != 0

**To Reproduce**
1. Go to BO / Order setting
2. Enable Gift Wrapping
3. Set price to 0.00
4. Go to FO
5. Place product to cart, go to checkout
6. Under shipping select: I would like my order to be gift wrapped 
7. Gift wrapping "Free" is diplayed in cart summary

**Screenshots**
![wrapping](https://user-images.githubusercontent.com/31688689/54085261-76199e80-433c-11e9-8624-c501d1a8fac2.png)
![wrapping1](https://user-images.githubusercontent.com/31688689/54085265-86ca1480-433c-11e9-9bc4-8f00ce033c27.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.26

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
In your BO => Shop Parameters => Order Settings => YOu have enabled the action "Suggest gift-wrapping to customers" with a free price.
![image](https://user-images.githubusercontent.com/16067358/54111217-a700de80-43e3-11e9-88bb-92d1cd9b9310.png)

If this information is not displayed in the FO, it will be confusing for the customers and for them there is an information is missing, in fact they don't know the price if the gift-wrapping because it is not displayed => which is incorrect.
Thanks to check & feedback.

**Comment by mrabsinthe** [comment]
What I'm trying to say is that we can certainly enable it in BO and display in FO with the following for eaxple: "I would like to have my order gift wrapped for free." It is than not necessary (and in some countries not possible) to list in in a/cart summary, b/ order confirmation c/ invoice as FREE item. I think that easy ON/OFF switch in BO "Display in cart summary/invoice" would do the job.

**Comment by khouloudbelguith** [comment]
@mrabsinthe, so you need only to change the label "Free" to "I would like to have my order gift wrapped for free."?
![image](https://user-images.githubusercontent.com/16067358/54113617-fb5a8d00-43e8-11e9-91ab-91aadbee6ae5.png)
Thanks!

**Comment by mrabsinthe** [comment]
No, I need the option to hide the line completely but keep the gift wrapping selection box available.
![wrapping_hide](https://user-images.githubusercontent.com/31688689/54114467-cbac8480-43ea-11e9-9df7-9d15c15f99d1.png)

**Comment by khouloudbelguith** [comment]
@mrabsinthe, as I said in my last comment.
If we hide completely this option, it will be confusing for the customer => it is not a good improvement to add.
This is a custom need, so you can hide it by editing the your theme. 
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by cariena1** [comment]
Hi all.  I am trying to edit the TEXT for my Gift Wrapping, but have looked everywhere in the back office, and cannot find it.  please assist?  I have Prestashop 1.7.7.2. THank you so much

![image](https://user-images.githubusercontent.com/73464144/143674931-7d4f1cfc-93de-48a1-85b1-ad33eb490654.png)
