### ISSUE TITLE
can't modify the product and I get error can't saving Prestashop 1.7.5.1 and 1.7.6.2

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#12858]
Hi @khouloudbelguith
for followup my second problem from my last issues, I create these issues.
https://github.com/PrestaShop/PrestaShop/issues/12777

PrestaShop 1.7.5.1 rtl (Persian language panel )

Friendly URL and Accented URL both of them are enabled, and there isn't any difference between both product.

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

With PS1.7.5.1, when Persian language panel is selected:
1. Friendly URL is enabled
1.1 if Accented URL is disabled => in the product page detail => SEO tab => Friendly URL will be empty => 
![image](https://user-images.githubusercontent.com/16067358/54115479-ccdeb100-43ec-11e9-9dda-daa13ac1ae26.png) => `http://0.0.0.0:8001/en/27-.html`

1.2 if Accented URL is enabled => in the product page detail => SEO tab => Friendly URL will be not empty => for example "نسخه-ی-نمایشی" => 
![image](https://user-images.githubusercontent.com/16067358/54113958-a66b4680-43e9-11e9-9f3c-1d8f27e680c6.png) =>  http://shop/en/home/26-نسخه-ی-نمایشی.html

2. Friendly URL is disabled & Accented URL is enabled => http://shop/index.php?id_product=27&id_product_attribute=0&rewrite=ترکیب&controller=product&id_lang=1

Thanks to check & feedback.

**Comment by IranDec** [comment]
Hi, @khouloudbelguith 
thanks for followup my problem
friendly URL is enabled  & Accented URL is enabled. 
but in some of my product page, I can't edit them and get an error.
this problem just accurate in Persian panel, when I use the English panel everything works fine.
for example, I have an error in this product :
https://irandec.com/لوستر-کریستالی/-670لوستر-مهتاب-تنه-استیل.html

**Comment by khouloudbelguith** [comment]
@IranDec, You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by IranDec** [comment]
Hi @khouloudbelguith 
today, I upgrade my PrestaShop to 1.7.6.2 after the upgrade finished, I couldn't modify any product and I cant see none of my entire combination of product
Id like to solve this problem but when I turn on debug mode I got this error:

ContextErrorException
Warning: putenv() has been disabled for security reasons

I will download a fullback of my website and try to restore in offline mode and send it feed back of that.
pls open this ticket again

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

We have updated the Symfony version, this new version use the Putenv function.
Some server disables `putenv` because of security reasons.
Your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
We can't do anything with this. 
You should contact your host provider, they are the only ones to help you with it.
Thanks!

**Comment by IranDec** [comment]
Hi @khouloudbelguith 
I restored my website in localhost and i enable-debug mode 
but in product page, I get this error

An error occurred while loading the web debug toolbar. Open the web profiler.

what i must to do now?

**Comment by IranDec** [comment]
I solved this error
An error occurred while loading the web debug toolbar. Open the web profiler.

it's related to PHP ver and ioncube ver

but I couldn't find your way; is it possible to send a guide for me? 

enable debug mode
go to the product page
open up developer tools
go to Network tab
save product
wait for an error, you should see red request information in Network tab
click on it, you should see the error message in "Response" or "Preview" tab

i got this error is  AJAX requests:
Method	Type	Status	URL	Time	Profile
POST	xhr	          400              http://localhost:8080/...../index.php/sell/catalog/products/278?_token=cfchqAbQc84decoaNKR92xxXtk7nfqWlTjOx07HuLE8#tab-step3	4667ms	33471d

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

Here's a screen record:
https://drive.google.com/file/d/1U_yAShWC0R2LsnEYqay5vbhUolGvZ9M2/view

Thanks!

**Comment by IranDec** [comment]
Hi @khouloudbelguith 
pls check this item
https://drive.google.com/file/d/1Vn5BDhfUYEMkpZKxiqaK5cfNmQk95VWv/view

Thanks
