### ISSUE TITLE
Price Problem with combination 1.7.5

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12856]
Hello everyone, 

I use PS 1.7.5 and everything was working fine until yesterday. 
I have products with combinations but after I changed some prices to all my products now is showing the price: Impact on price (tax excl.) and not the Impact on price (tax incl.)

For example I have this product that you can choose your size to get different price. If I put the price with tax included it showing the price tax excluded then on my website is written : tax included. 

What happen? 

Please help me :(

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Thanks for your report.
In the BO => Products details page => Combination Tab => You have "impact on price" tax excluded
![image](https://user-images.githubusercontent.com/16067358/54110042-9c911580-43e0-11e9-8542-8b6f5978a1b7.png)
I you click to edit on combination => You have two options 
1. Impact on price (tax excl.) 
2. Impact on price (tax incl.)

![image](https://user-images.githubusercontent.com/16067358/54110109-cf3b0e00-43e0-11e9-87b6-96f61364e12d.png)

So, you are editing which field? could you please provide me more information to reproduce your issue.
Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith thank you for your replay.
I fixed it was only a problem linked to countries.

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
