### ISSUE TITLE
Cart rules issue with taxes

### ISSUE THREAD

**Issue by Pliciweb** [PrestaShop/PrestaShop#12863]
**Describe the bug**
Apply cart rules generate a tax include price lower than tax exclude price in back office if customer is supposed to be tax exempt.

**To Reproduce**
1. Install fresh lasted 1.6 version of Prestasop : 1.6.1.23 
2. Go to Price Rules -> Cart rules -> Add new cart rule
![bug_1_informations](https://user-images.githubusercontent.com/1949479/54118751-141c7000-43f4-11e9-8c56-14ff9dc8d8db.png)
![bug_2_conditions](https://user-images.githubusercontent.com/1949479/54118776-21d1f580-43f4-11e9-8fa2-2f41bbb7cdfa.png)
![bug_3_actions](https://user-images.githubusercontent.com/1949479/54118786-25fe1300-43f4-11e9-9c06-bb44254236fd.png)
4. Go to Orders -> Orders -> Add new order 
5. Select Customer:  john doe, Product : Blouse, Select voucher : test
6. Update Delivery address by select country Afghanistan with a postal code 1234
7. See Summary, the Total (Tax incl.) [17.28] is lower Total (Tax excl.) [18.90]
![bug_result](https://user-images.githubusercontent.com/1949479/54119120-e7b52380-43f4-11e9-9f0d-4cd00c715f22.png)

**Additionnal information**
PrestaShop version: 1.6.1.23 
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Pliciweb,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1fA24gLx-cBS7rsOkKKviIskHm1QUguTo/view
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, that’s why I close it.
Thanks!
