### ISSUE TITLE
Uncheck the sub-category in the back office, but always check the sub-category in the front-end category

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12860]
Hello i'm facing a little bug with prestashop 1.7.5.1 version. When you unchecked the sub-category in main category in the Back office. The sub-category still display in front end. 

**Describe the bug**

**To Reproduce**
1. Go to 'Catalog'
2. Click on 'products'
3. Select a product 
4- Unchecked main category in exemple for the sampel theme(Vêtements) and Keep femmes
3. Save and go to the front end, click the main category you always show the sub-category in main category.

5. The goal is to not display this sub-category in main category.

**Screenshots**
![Capture d’écran 2019-03-11 à 10 26 34](https://user-images.githubusercontent.com/15048897/54113567-dcf49180-43e8-11e9-8b09-1a07472b920c.png)
![Capture d’écran 2019-03-11 à 10 26 43](https://user-images.githubusercontent.com/15048897/54113577-e0881880-43e8-11e9-8cb5-fa4f3596de6b.png)
![Capture d’écran 2019-03-11 à 10 27 18](https://user-images.githubusercontent.com/15048897/54113578-e2ea7280-43e8-11e9-8743-e3e1664240af.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
Hi @manouxep,

You need to navigate to your BO => Modules => Module Manager => search for the ps_facetedsearch module => click on configure button => Disable the "Show products from subcategories" option & save.
![image](https://user-images.githubusercontent.com/16067358/54126075-fc9ab280-4406-11e9-9258-b4d0ef4ecc2e.png)
Thanks, I close the issue, feel free to open a new one when needed.
Thank you!
