### ISSUE TITLE
index button on search module

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12869]
Prestashop 1.7.5.1 on debian
This button https://s.nimbusweb.me/share/2647953/rf1t1ibql6xhza6y0m1k doesn't works.
I'm explain better: with this button flagged or unflagged, after edit or add product, the index doesn'r change until click on link "add product to idnex" or "rebuild index"

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

No, it is working well.
If you enable this feature, the products will be indexed in the search automatically when they are saved. If the feature is disabled, you will have to index products manually.
I attached a video record.
https://drive.google.com/file/d/1pq3_Qn4_Agt1fSooc0NKlo0B0EfUxykr/view
Thanks to check & feedback.

**Comment by centoasa** [comment]
thank you so much @khouloudbelguith I'm testing again and let you know if updates happens

**Comment by khouloudbelguith** [comment]
@centoasa, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
