### ISSUE TITLE
Technical debt of the Translations in PrestaShop

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#12873]
> This issue follows the bugs and improvements spotted in https://github.com/PrestaShop/PrestaShop/pull/11321.

# Translations system

We need to support the management of the translations of the external modules in the Back Office.
For the native modules, translations come from the core Xliff files and domains so we have introduced the support of legacy translation files from PrestaShop 1.6-.

Doing that, we have identified a lot of mistakes or code smell in the current implemntation of the translation system.

## TranslationService class

This class have multiple scope and is error prone. We have identified multiple tasks to be done in further refactorings:

`TranslationService:listDomainTranslation($locale, $domain, $theme  =  null, $search  =  null, $module  =  null)`

This function have multiple scope and so on must be splitted in multiple functions:
`TranslationService:listDomainTranslation:listTranslations($locale, $domain, $theme)` and
`TranslationModuleService:listDomainTranslation:listTranslations($locale, $domain, $theme, $module)`. Names are not perfect, but you get the idea.

Looking at these 2 functions, we see that $locale, $domain and $theme are common and required (we always need a theme, the nullable value is a hack).

How about a specific object instead of three parameters? 

```php
<?php
class TranslationContext implements TranslationContextInterface
{
    public function __construct($locale, $domain, $theme)
    {
        // ...
   }
}
```

The function also calls a specific Translation Provider according to the function arguments: this is also a code smell and could be refactored using the [Factory Method Pattern](https://en.wikipedia.org/wiki/Factory_method_pattern).

Doing that will allow us to design a specific custom logic for each provider, and so on remove the check on the existence of a specific function like `get{Xliff|Legacy}Catalogue`.

So, to fix this technical debt: this business logic must be extracted from TranslationService class to some AbstractMethodFactory class, with 2 strategies: for legacy files and for xliff files.

Working on that make us think about the "sources" of data.

### Sources of data

As we have Providers able to collect translations into multiple sources:
* legacy translation files, 
* php code,
* smarty files,
* twig files,
* xliff files,
We also have 2 system of translations:
* the Legacy one (think about `l()` function;
* the New one (think about `trans()` function;

I think a provider class should be able to define Sources. Doing that will clarify the scopes and intents and remove a lot of hardcoded code (See **TreeBuilder**).

How about this:

```php
<?php
interface TranslationProviderInterface
{
    public function getDomains() : string[];
    public function getSources() : SourceInterface[];
    public function getCatalogue($locale) : CatalogueInterface;
}
```

If we need to filter data, we could address the subject in another implementation:

```php

interface TranslationFilterable
{
    public function getFilters();
}
```

Doing that, we will be able to remove any hardcoded code on the application, that rely on "database" and "xliff" as sources of truth and not applicable when we have introduced the "legacy files" source.

This is why we have some minor issues with the number of missing keys on the current feature, because the 2 catalogs don't have at all the same behavior (so I'm not quite sure we should rely on the CatalogueInterface from Symfony but on something from PrestaShop to ensure we compare the same things when computing the misses in translations).

### TreeBuilder

This [class](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Translation/View/TreeBuilder.php) is very badly designed, error-prone and really hard to test and debug.

The code is not documented, not types are now defined but most of the defined default values with hacky behaviors are implemented. More this class have multiple scopes:
* makeTranslationArray(AbstractProvider  $provider, $search  =  null)
* makeTranslationsTree($catalogue)
* cleanTreeToApi($tree, Router  $router, $theme  =  null, $search  =  null, $module  =  null)

As sources of truth are hardcoded into the application, we retrieve "xlf" and "database" keys hardcoded everywhere, with the objective of generating some JSON output consumed by the Vuejs application...

What I suggest here:
#### Fix the TreeBuilder responsibilities
Split the class into multiples classes: `ThemeTreeBuilder`, `ModuleTreeBuilder`, ...TreeBuilder with only one responsibility.

```php
interface TreeBuilderInterface
{
    public function build(array $buildParameters) : TreeViewInterface; // can be difficult to do
    public function getProviders() : ProviderInterface[];
    
}
```

Implement a TreeView with a function `toArray()`.

```php
interface TreeViewInterface
{
     public function getMessages();
     public function getDomain();
     public function getTotalTranslations();
     public function getTotalMissingTranslations();
     public function getChildren() : TreeViewInterface[];
     ... // looks like many more information here
     public function toArray() : array;
}
```

All with unit tests to ensure it just works as expected without having to reload again and again the Back Office with die()/ xdebugs stops everywhere!

**Comment by sarahdib** [comment]
@eternoendless can we close this issue ?

**Comment by eternoendless** [comment]
No, this issue lists problems in the translation services.
