### ISSUE TITLE
#BO - Translations search : menu items active or not

### ISSUE THREAD

**Issue by francoispeyret** [PrestaShop/PrestaShop#12888]
**Navigation items disabled in translation controller**
When you do a search in translations (BO). Items of navigation aren't allways enabled and don't affect interface..
![Capture d’écran de 2019-03-12 14-43-32](https://user-images.githubusercontent.com/15829643/54204868-74cfa980-44d5-11e9-9ceb-87b0e9347cd4.png)

**My solution**
When item is not enabled hide it a little with opacity
![Capture d’écran de 2019-03-12 14-43-44](https://user-images.githubusercontent.com/15829643/54204935-9597ff00-44d5-11e9-9dc7-9f7218d8235b.png)

Class in Dom Element are already here so i find a quick solution is to add this line in BO's Theme.
`.d-flex.tree-name.disable{opacity: 0.3;}`

**Comment by khouloudbelguith** [comment]
Hi @francoispeyret,

Thanks for your suggestion.
Yes, I think, it is a good idea.
@marionf, @colinegin what do you think?

@francoispeyret, would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by francoispeyret** [comment]
@khouloudbelguith yes. Soon, i guess

**Comment by francoispeyret** [comment]
Hi @khouloudbelguith,

Yes. Soon, i guess.

**Comment by francoispeyret** [comment]
@khouloudbelguith #12997

**Comment by khouloudbelguith** [comment]
Hi @francoispeyret,

Thanks a lot for your fix.

**Comment by ghost** [comment]
Hello @francoispeyret,

We discussed it with @TristanLDD, do you think you could hide empty navigation items instead of modifying opacity?
It would make the interface clearer :) 

Thanks

**Comment by francoispeyret** [comment]
Helllo @samuel-pires,

Personally, I think it's not nescessary. Less is not always better.

The user will have as always the same structure with each search, it is surely simpler?


Thanks a lot !

**Comment by ghost** [comment]
@TristanLDD what do you think ?

**Comment by ghost** [comment]
Hi @francoispeyret,

We agreed with @TristanLDD to go with your version!
You are right, the user will have the same structure with each search, and the opacity difference will make it way easier to use the search, it is simple and works well 👍 

Your PR needs a review and some modification on your side, can you check it?
I pinged you on it.


Thanks a lot!

**Comment by khouloudbelguith** [comment]
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12997 to add this feature.
