### ISSUE TITLE
cURL error: Resolving timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by Marwazeinoo88** [PrestaShop/PrestaShop#12885]
**Describe the bug**
Hi, this morning i'm getting 500 (Internal Server Error) on front office! On debeug mode i find the forward error 👍 

> Exception in instagram.php line 289: Error: makeCall() - cURL error: Resolving timed out after 5000 milliseconds

**To Reproduce**
1. Go to 'my website front page'
2. See error

**Screenshots**
I’ve attached a screenshot of it as well.
![Capture](https://user-images.githubusercontent.com/43037924/54191665-ad13bf80-44b6-11e9-95c1-2d7068384673.PNG)

**Additionnal information**
PrestaShop version: 1.7.3.0
host: phpnet
Version de PHP : 7.1.25
Limite de mémoire : 256M
Temps maximal d'exécution : 80
Taille max. pour envoi de fichiers : 200M
Thème actif : classic
serveur : Apache

**Comment by khouloudbelguith** [comment]
Hi @Marwazeinoo88,

Your issue is related to the `hicarouselspack` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Marwazeinoo88** [comment]
@khouloudbelguith But the module was working just fine for more than 6 months...I only got this error this morning! the 3 months of support are over long ago..

**Comment by khouloudbelguith** [comment]
@Marwazeinoo88, you have some issues with file instagaram.php file & hicarouselspack.php file.
I'm sorry, but as I said before, As it's not a module provided by Prestashop, we can't do anything with this.
Thanks for your understanding!

**Comment by Marwazeinoo88** [comment]
Thank you anyway! the error has disappeared suddenly as it came suddenly...Never know if it is presta bug or a hosting server issue!
