### ISSUE TITLE
PRESTA 1.6.17 Controller not found 

### ISSUE THREAD

**Issue by tlukowskia** [PrestaShop/PrestaShop#12886]
**Describe the bug**
Several days ago everythink works well but when i wanted to change cms sites i have a problem. Changed debug mode to true but i don't have more errors. Caan u help me?

**To Reproduce**
1. Go to 'admin'
2. Click on 'preferences -> cms'
3. And i have problem like this http://prntscr.com/mwrh2n

**Screenshots**
http://prntscr.com/mwrh2n

**Additionnal information**
PrestaShop version: 1.6.17
PHP version: 7.1.12

**Comment by khouloudbelguith** [comment]
Hi @tlukowski,

I did not manage to reproduce the issue with PS1.6.1.23.
![image](https://user-images.githubusercontent.com/16067358/54196734-6b891180-44c2-11e9-96cf-093333d07111.png)
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
I close the issue, feel free to open a new one when needed.
Thanks!
