### ISSUE TITLE
Stats does not show the real numbers 

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#12896]
Hello, I have problems with Stats since the day 1 (I installed PS somewhere around 1.7.2 version). Both Stats section and the stats widgets on Dashboard are showing various numbers not related to the real life.

Stats section shows "no module installed" on the left side. I do not know how to solve it. Also take a look at the period selected and the number of orders. These numbers are different. I believe they should be the same or at least matching to the real life.

![1](https://user-images.githubusercontent.com/48493952/54230467-c2183f00-4506-11e9-8cf9-bd81d8519a56.JPG)

Now we are going to the Back Office - Dashboard section. The first widget is dashbord that shows 6 orders since the start of 2019 until today. The number is incorrect.

![2](https://user-images.githubusercontent.com/48493952/54230469-c2183f00-4506-11e9-95f5-4b281dbbf849.jpg)

Scroll down below I have Recent orders widget and you can see there are more orders then the widget above shows and what Stats section is showing me.

![3](https://user-images.githubusercontent.com/48493952/54230468-c2183f00-4506-11e9-894f-74e1a5313e21.jpg)

I think these orders that are not counted are paid by PayPal. I do not know why I have "No module installed" info in Stats section. Can anyone know how to solve these issues? Currently I have Prestastop 1.7.5.1. All updates were performed with 1-click update module.

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Thanks for your report.
In your Dashboard page, could you please check if the "Demo mode" option is disabled.

"Demo mode" => This mode displays sample data so you can try your dashboard without real numbers.
![image](https://user-images.githubusercontent.com/16067358/54262108-b2801100-456d-11e9-8471-4a573aa3cdc4.png)
Thanks to check & feedback.

**Comment by banan44** [comment]
Thank you for your reply. Yes, the Demo mode is disabled. The orders that are showed in the graph widget were paid by other payment module I am using. Orders paid by PayPal are not showed on graph.

**Comment by khouloudbelguith** [comment]
@banan44, thanks for your feedback.

> Orders paid by PayPal are not shown on the graph.

During this period, did you generate any new invoices?
for this module `dashtrends`, it is necessary to regenerate invoices so the statistics will be displayed.
Thanks!

**Comment by banan44** [comment]
I do not generate invoices on Prestashop. I have a separate invoicing system provided by a accountant company that do my taxes. So the problem is still not fixed because orders paid by other Payment modules are shown correctly. I only do not see orders paid by PayPal module.

**Comment by banan44** [comment]
To be honest, besides stats section and the graph, all dashboard widgets are not working properly. Traffic widget always shows the same numbers. When I click on 'Link to your Google Analytics account' od redirects me to Module manager. Google Analytics module is already configured. 

![traffic](https://user-images.githubusercontent.com/48493952/54393378-4d7e0580-46aa-11e9-9cb9-8f38a9cb9dbd.JPG)

I also have problems with Forecast widget. It shows nothing in all tabs. I believe the widget should show something.

![forecast](https://user-images.githubusercontent.com/48493952/54393542-b6657d80-46aa-11e9-96a2-562ec88901b8.JPG)

I have these problems since the start. I was hoping the updates will solve these problems but it over 9 months of store running and updateing and the dashboard section is still useless.

**Comment by khouloudbelguith** [comment]
Hi @banan44,

About the `dashgoals` module (Forcast widget) doesn't work, we are aware of this issue, reported in this ticket: #9662.
About the `dashtrends` module (Dashboard widget), as I said before, it is necessary to regenerate invoices so the statistics will be displayed, if you don't regenerate an invoice for an order, it will not be taken in consideration for the statistics.
Thanks!

**Comment by banan44** [comment]
But how can I do that? I do not used Prestashop invoice. Orders paid by other payment modules do not require to regenerate invoices. These orders are present on the graph. I do not see just PayPal orders. There seems to be a problem with PayPal module. Or prestashop do not consider PayPal as a payment module or something.

**Comment by khouloudbelguith** [comment]
Hi @banan44,

I did not manage to reproduce the issue with PS1.7.5.1 & the PayPal module v4.4.2
I attached a video record
https://drive.google.com/file/d/1zbD0Vx3iQngZgFzM2GuxTox0k0VJ9EmB/view
Thanks to check & feedback.

**Comment by banan44** [comment]
Ok, I have watched your video and I noticed some things. First, I have checked the order statuses. I have notice that the order payment modules that counts orders correctly have theit own 'Payment accepted' status with marked option 'Allow a customer to download and view PDF versions of his/her invoices.' My original 'payment accepted' status that PayPal uses did not have this option marked. So I have marked it. 'Deivered' status also have this option marked.

Then I began testing. And here's what is strange. When I manually set one of these statuses, the order is counted in the graph. And there is an employee name next to the status. When I set different status, for example 'not paid' which do not have this invoice option marked, then the graph recounts the number of orders. This works great.

![stat](https://user-images.githubusercontent.com/48493952/54708192-26f51a00-4b43-11e9-80e5-e170fce2681f.png)

But in my case 'Payment accepted' and ' Delivered' statuses are set automatically. When the payment is accepted or when the tracking number of the order has delivered status. In my case when the order is automatically set there is no employee name in the status (like on the screenshot above) and the order is not counted on the graph.

To be more clear about the statuses. I use external service that is connected to prestashop, 6 eBay services, facebook market and some other selling services in different countries. This service gathers all my orders in one place so I use only one service to manage all orders in all markets. This service synchronizes tracking numbers and the statuses of all orders in my prestashop (statuses are directly linked between PS and this service). When this services sets the status delivered, my prestashop also have the same status. But for reason unknown the invoice is not created. 

I also did another thing. I have set the 'delivered' status manually to one order and the invoice has been generated and the graph counted the order. Then I opened the service and re-set the status 'Delivered' there. It synchronized the status on PS but the order has not been counted and the graph recalculated itself. There were 2 'Delivered' statuses next to each other but one with employee name and the next one blank. I only have one 'Delivered' status on my Prestashop so it was the same status.

Do you know what might be wrong?

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Thanks for these clarifications.
But it is Ok in my case.
When we created order with PayPal module => an invoice is generated => OK => there is no employee selected because the status is generated via the module.
And this command is considered in all statistics.
I attached a video record.
https://drive.google.com/file/d/1Ighojnp2O4SOa2v8QzXO3do6ddL-wJJ8/view
Thanks to check & feedback.

**Comment by banan44** [comment]
Ok, the issue seems to be resolved. I have updated some option, reseted the modules and deactivated and activated again inoices and from that point it started to count PayPal transactions. Thanks for the help.

**Comment by fabio-zetaweb** [comment]
Hello,

I've a similar problem. But in my case Invoice are regularly generated, nevertheless there is an error on the statistics, infact they reveal 12 orders instead of 11 (real order numbers).

I'm using v1.7.6.3 (no order managment modules active).

![orders](https://user-images.githubusercontent.com/56585945/81917592-af4f3d80-95d5-11ea-8489-e5bec8bd8f8b.jpg)

![dashtrends](https://user-images.githubusercontent.com/56585945/81917601-b2e2c480-95d5-11ea-8b9d-3c62c8faa2f2.jpg)

![difference](https://user-images.githubusercontent.com/56585945/81917618-b70ee200-95d5-11ea-9813-6ca8208c41fa.jpg)

I need an help to solve this issue, please. Thanks.
