### ISSUE TITLE
Charset database not specified for table ps_layered_category ?

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#12898]
Hello. Maybe need charset database?
![Screenshot_1](https://user-images.githubusercontent.com/6318282/54237014-bd807480-4560-11e9-864d-1e14f297866e.jpg)

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for your report.
I have the same issue with PS1.7.5.1.
The collocation of the table ps_layered_category.
The most "standard" table is that defaulted by phpMyAdmin, is "latin1_swedish_ci".
It corresponds perfectly to ISO-8859-1.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
