### ISSUE TITLE
Server overload on image generation after update

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#12894]
**Describe the bug**
After upgrade a PrestaShop 1.7.4.2 to 1.7.5.1 the serveur is overload when i tried to go on a product page or a category page, it seems to generate all the images (on front office). 
If a rename the img root folder by img- the category / product page is displayed.

It's the second time i've seen it, and in the same case upgrade 1.7.4.X to 1.7.5.X
at first i thought it was a hack, but it's not and i'm sure of it. 

If re-generate images with image generator module (in AJAX) after that, it works again. 
This bug appareas when whe add images to products too. 

Thanks !

**To Reproduce**
Upgrade a prestashop
1. Go to to a category page or product page
You need to have a big catalogue (more then 500 products)

**Screenshots**
<img width="726" alt="Capture d’écran 2019-03-12 à 17 44 52" src="https://user-images.githubusercontent.com/4788787/54218838-9a1ce180-44ee-11e9-8fb7-097a541e1c37.png">

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.24
Serveur VPS A Alwaysdata

**Comment by khouloudbelguith** [comment]
HI @PrestaSafe,

I tried with PS1.7.5.1, I have more than 500 products, the query time is 0.31 ms.
I attached a video record.
https://drive.google.com/file/d/1p3gjKuDFstp9VlUfiSsyNBXtE1s9TelY/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by PrestaSafe** [comment]
Thanks, but my probleme is when i'm on the front office. 
Did you tried to regnerate all of images ?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

Thanks for updating the issue.
@jolelievre created a PR: https://github.com/PrestaShop/PrestaShop/pull/12337 to fix this issue: https://github.com/PrestaShop/PrestaShop/issues/12207
It is fixed in the PS1.7.5.1.
Is it similar to your issue?
Thanks!

**Comment by PrestaSafe** [comment]
@khouloudbelguith yes it seems to be the same things, but not in the same place. 
I've not this probleme when i change combination, it makes 500ms to change it on a good server (is it long ?)
In my customer template, the combinations are loaded on category page so it make sense. 

I think the problem is linked to the upgrade process. i haven't this probleme on the previous version (1.7.4.3) and it was the same theme. 

it cool if we have a trace, i hope it will be fixed soon. Thanks ;)

**Comment by khouloudbelguith** [comment]
@PrestaSafe, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
