### ISSUE TITLE
Static function called as self

### ISSUE THREAD

**Issue by bertoferrero** [PrestaShop/PrestaShop#12908]
**Describe the bug**
If you call cleanPositions as self::cleanPositions PHP will not call the overrided version of cleanPositions.

**Additionnal information**
PrestaShop version: 1.71x
PHP version: N/A

**Comment by matks** [comment]
Hi @prestaquality, can you explain a bit more your usecase ? What class are you overriding ?

**Comment by bertoferrero** [comment]
Sorry :)
It is inside of Product class, all calls to product::cleanPositions are made with self:: instead of static::. Because of this php will never call the override version of cleanPositions

**Comment by khouloudbelguith** [comment]
Hi @prestaquality,

Thanks for your report.
I created the file Product.php into the path /Projetc_Folder/override/classes/Product.php

```
?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 14/03/19
 * Time: 11:26
 */

class Product extends ProductCore
{
public static function cleanPositions($id_category, $position = 0)
    {
        print_r('test 4');
        exit();
    }
}
?>
```
This function is call after deleting a product from a category.
I tried to delete a product, but no effect.
I manage to reproduce this issue with PS1.7.5.1 & PS1.7.4.4.
Ping @eternoendless @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by bertoferrero** [comment]
It is simple, you have to modify deleteCategory and deleteCategories. Just replace self::cleanPositions by static::cleanPositions

**Comment by khouloudbelguith** [comment]
@prestaquality, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by jtraulle** [comment]
@khouloudbelguith Without reply from @prestaquality, I took the liberty to make the PR against develop branch.

I have the exact same issue and this "fix" works perfectly :slightly_smiling_face:

**Comment by bertoferrero** [comment]
@jtraulle Thanks a lot and sorry, I forgot to reply here.
Thanks again!
