### ISSUE TITLE
Free Shipping anyway 1.7.5.1

### ISSUE THREAD

**Issue by JulienBerlinger** [PrestaShop/PrestaShop#12919]
**Describe the bug**
Trying to resolve the shipping registration process. I added / deleted carriers, means of payment. price brackets, weight slices. Transform "France" into "FRANCE" or "EUROPE". But still the same problems, "Free shipping" (under conditions)

**To Reproduce**
1. Go to 'fleurdeparfum.fr'
2. Click on 'try to buy something'
3. Scroll down to 'Select shipping option'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: PHP 7.3

**Comment by khouloudbelguith** [comment]
Hi @JulienBerlinger,

I have this issue when I try to navigate to your shop.
![image](https://user-images.githubusercontent.com/16067358/54346501-74eeb700-4645-11e9-86d1-ce2cf8f6e4c1.png)
Thanks to provide the access.

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP

**Comment by JulienBerlinger** [comment]
Ho ok sorry,
But where are you ?
Regards
Julien

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, now it is OK.
![image](https://user-images.githubusercontent.com/16067358/54354646-7c1ec080-4657-11e9-8f15-e94aa5056ece.png)
I will check & feedback.
Did you downgrade your PHP version?
Thanks!

**Comment by JulienBerlinger** [comment]
Please to check everything you need from BO.

I am right now in a train and my wifi is really bad I can't do anything for
now.
[Edited by Khouloud]
Best regards
Julien

**Comment by JulienBerlinger** [comment]
No the PHP is that I said in the ticket... I don't remember exactly.

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, I edited your comment.
This is a public space.
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, yes your PHP version is PHP 7.3.0.
![image](https://user-images.githubusercontent.com/16067358/54355283-f8fe6a00-4658-11e9-826f-8a1ecd98a566.png)
You need to downgrade your PHP version
Thanks!

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, there is something strange, When I'm logged to your shop, the shop is replaced to just a catalog, so I cannot add any product to cart, because it is not displayed.
![image](https://user-images.githubusercontent.com/16067358/54355455-7033fe00-4659-11e9-86ad-edf4a9693c0b.png)
Thanks!

**Comment by JulienBerlinger** [comment]
B to B is activated and connected are disable to order. You can change it
if you need.
Best regards
Julien

Le jeu. 14 mars 2019 1:02 PM, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, No, I disabled B2B, but always the same issue on FO.
![image](https://user-images.githubusercontent.com/16067358/54360774-e3dc0800-4665-11e9-9700-94a5c67738ce.png)

Thanks!

**Comment by JulienBerlinger** [comment]
I'm sorry my client is searching and trying to change every since two weeks.
I have contacted him to tell to stop it.
You can now activate it and change groups as you want.
Thanks a lot.
Julien

Le jeu. 14 mars 2019 2:32 PM, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, have you tried to contact the theme author about this issue?
Thanks!

**Comment by JulienBerlinger** [comment]
The theme author is me, and it's just a copy of classic theme... I have
tried to change it for restart with the classic theme... but same issue. I
have read a lot of ticket on forums about this problem.
I have called Prestashop this morning and they tell to contact you.
You are my last chance.

When you tell me to undergrade PHP, you means from hosting plateforme right
? Could you tell what php version should be right ?

Best Regards
Julien

Le jeu. 14 mars 2019 3:12 PM, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@JulienBerlinger, yes, on your server, you need to change the version PHP.
Thanks to downgrade your PHP version, check & feedback.

**Comment by JulienBerlinger** [comment]
Hello,
I would like to thanks you.
Everythings seems to works perfectly from now !
So enormus Thanks for all

Do we need  to stay in debug mode ?

Thanks a lot for all you've done !
Best Regards
Julien

**Comment by khouloudbelguith** [comment]
Hi @JulienBerlinger,

Thanks for your feedback.
When in debug mode, you can choose to lessen the impact of certain features on PrestaShop, in order to best pinpoint where an error comes from.
So, if you don't have issues, you can disable it.
I close the issue, feel free to open a new one when needed.
Thanks!
