### ISSUE TITLE
[CLASSIC THEME] New design for 'Add to cart' confirmation popup

### ISSUE THREAD

**Issue by TristanLDD** [PrestaShop/PrestaShop#12913]
UI modifications on the 'Add to cart' confirmation popup

Mockups: https://invis.io/7BQZL32SCRY#/352006191_Modale

Preview: 
![Capture d’écran 2019-03-13 à 17 48 33](https://user-images.githubusercontent.com/27484094/54298078-63130280-45b8-11e9-919f-aaee011278c6.png)

**Comment by colinegin** [comment]
#13047
