### ISSUE TITLE
Price and product (attributes) loading performance issue - pls help

### ISSUE THREAD

**Issue by MSG47** [PrestaShop/PrestaShop#12915]
Hi Guys,
So the situation is the following I have products with multiple combinations:
Four Attributes with the following number of values:
1)	- 19 values
2)	- 8 values
3)	- 8 values
4)	- 3 values

So ~3600 combination per product, with 30 products now that gives me >100000 rows. each with different price. I do load them from CVS file (take ages, but works😉), however - when going to the Product on front office:

1) the product page loads slow once selected / clicked
2) when changing the attribute – the price updates very slow giving the impression nothing happens and provoking the user to keeps clicking around, selecting other values etc.  

Ad.2 is very similar to what the user joaoafpedro pasted some time back on the forum (his screen):

![52003345-28e41a80-24bc-11e9-9537-6826b90fe72e](https://user-images.githubusercontent.com/48532848/54312760-00c9fa00-45d8-11e9-922b-53694c65620a.gif)

(that was to be fixed in 1.7.5.1 that I am currently using) – my is currently on localhost but have more attributes / values – 4 as mentioned at the beginning (the more i am afraid of performance once on web server...)

As a workaround I thought to make a loading animation when that happens so the customer would wait (not ideal one, but no better ideas) – any thoughts what would be the best address it? 

Also, if there is any solution for my primal problem regarding slow updates and multiple combinations (but take care – each needs to have customized price so taking the values form the CVS and not setting any price impact rules etc. [anyway, I am not able to access such Products from back office keeps getting only empty white page])

Thank you kindly and looking forward to your feedback.

Regards,
Marcin

**Comment by khouloudbelguith** [comment]
Hi @MSG47,

Thanks for your report.
About the blank page in the BO when editing a product, We are aware of this issue and we are working on it.
No, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your issue is a duplicate of #9809
About the slow performance, in the FO, have you the same issue reported in this ticket: #12894?
Thanks!

**Comment by MSG47** [comment]
Hi @khouloudbelguith 

Thanks for your prompt answer!

So - I do consider two issue (perhaps related, however) 
1.	Performance:

a.	Slow performance when selecting (clicking on) the product from the category / product list on the front office
b.	Very slow price updates when changing the values of attributes (very similar as on the image I shared and that was previously reported by the other user)

Ad. b) I am not very sure if it is same as #12894, the behavior I am facing seems to be very similar to the one reported in this thread - https://github.com/PrestaShop/PrestaShop/issues/12207 (from where the image comes), but I am not convinced whether the root cause is the same (coded waiting time in ms) as that stars happen only when I have a significant number of combinations. Same with the one from point a) 

2.	Blank page when accessing product from BO

a.	And again – only for products that have multiple combination, if I erased them or reduce significantly – all starts to work fine (but with around ~350 combinations I am also not able to use GENERATE on BO as it simply crashes). And if that is similar to #9809 – would you be so kind and advise what is the ETA for its resolution? (it seems to be reported from some time, a year+ at least, perhaps not a top priority for Jocelyn?)

Following the above, I would greatly appreciate the confirmation whether these are already captured and resolution is pending, and if so – when (more/less) we can expect them to be fixed?

All my be linked to how PRESTA handles multiple combinations?

Thank you kindly!

**Comment by khouloudbelguith** [comment]
Hi @MSG47,

Thanks for your feedback.

About the issue 2.a) => it is in progress, this is not something we can easily fix.
@jocel1, may help you to get more details about the ETA for its resolution
Thanks for your understanding!

About 1.a) In the BO => Shop Parameters => Product Settings page => Pagination section, how many "Products per page" you have?

About 2.b) the issue #12207 is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/12337 in the PS1.7.5.1 by @jolelievre which "reverts" a modification in the js that was introduced in 1750. 

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@MSG47, I created more than 4500 products & for almost product, I have more than 14 combinations.
In the FO, when I try to change the combination, the price is not displayed slowly.
I attached a video record.
https://drive.google.com/file/d/1w2LY0z9dz0qZR4DieDuKrefxzXSjYA-1/view
Thanks!

**Comment by MSG47** [comment]
Hi @khouloudbelguith,

Thanks a lot and appreicate the test you have made!

Regarding 1b (the slow update of price when changing) - I believe it is because apart from the significant number of combinations in total you in your example have relatively not much per product - and I have ~350 (see attached)

![przyklad](https://user-images.githubusercontent.com/48532848/54449570-b74feb00-474e-11e9-8e41-d6027786797d.gif)

1a - only 9 per page and around 40 products in total. 

Your thoughts? Thanks!

**Comment by khouloudbelguith** [comment]
@MSG47, thanks for your feedback.
For the 1.a, I tried with 9 products per page & I have more than 500 pages.
For the 1.b, I have more than 260 combinations with different prices & it is OK.
I attached a video record.
https://drive.google.com/file/d/161HXhZ2JTW1IVTHl7AQDuZaL7xzaiz5d/view
Thanks to check & feedback.

**Comment by MSG47** [comment]
Hi @khouloudbelguith

Thank you kindly and apology for my late response.

I have tested my shop on another PC to recheck and validate – but situation / lags are the same. 

Having said that (considering also the tests you have made) it drives me the assumption the problem is related to the number of combinations per product: ~3500 combinations per product (4 attributes and multiple options) vs 260 in your example (2 attributes).

Following, I would greatly appreciate your thoughts regarding this and any help to address accordingly.
Regards,

MSG

**Comment by khouloudbelguith** [comment]
Hi @MSG47,

Sorry for the late response.
We'll first try to reproduce it and we'll come back to you if we need more information.

**Comment by khouloudbelguith** [comment]
Hi @MSG47,

I manage to reproduce the issue with PS1.7.6.0beta1
I have more than 2000 combination for a product,
[request_sql_1.txt](https://github.com/PrestaShop/PrestaShop/files/3231834/request_sql_1.txt)

When changing the attribute – the updates are very slow
I attached a video record
https://drive.google.com/file/d/1EZfpTxCoBPffU916IODwCjplo-ThoqTx/view

ping @PrestaShop/prestashop-core-developers

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: I added this large number of combinations via webservice

Thanks!

**Comment by Dirdmaster** [comment]
I'm facing the same issue on 1.7.5.2 every time I'm switching colors it takes up to 3713ms to make the switch... 
Any updates on this issue or any solution to fix it? 

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Dirdmaster,

Sorry not yet.
PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by Bujj** [comment]
Hello,
Was this solved? i am facing the same issue with version 1.7.6.5
Kindly Assist

**Comment by matks** [comment]
As discussed together with Product Team, this is not a bug, this is an improvement.

**Comment by robertosanval** [comment]
Any news about this issue? Is it the fix in the roadmap?

**Comment by hostisoft** [comment]
Where did this end up, I have the latest version 1.7.8.6 and the same problem still exists, as soon as a product has many attributes, the choice of the product in the public part by the client causes a lot of slowness, any solution ??

**Comment by kpodemski** [comment]
Product combinations mechanism on the product page has been drastically improved on the new product page introduced in PrestaShop 8.1. I'm closing this ticket, but if you want to discuss the performance of it more, I suggest [creating a new Discussion.](https://github.com/PrestaShop/PrestaShop/discussions/new?category=ideas)
