### ISSUE TITLE
Please add link for breadcrumb ADMIN CP

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#12917]
Hello. Need add link.

![Screenshot_1](https://user-images.githubusercontent.com/6318282/54323233-09581a00-4644-11e9-993b-491f7dddf686.jpg)

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Can you explain a bit more your usecase?
Do you need to add a link to which page?
Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith breadcrumb should have links rather than text, I can't go back to the module settings.

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks for these clarifications.
I have the same issue with PS1.7.5.1 & PS1.7.4.4.
For example, in the module's configuration page, we have a text for the breadcrumb
![image](https://user-images.githubusercontent.com/16067358/54424571-7b4b6480-4713-11e9-9c16-76cbe6dbbde0.png)
It could be an improvement to issue to replace this text by a link like the stocks page
![image](https://user-images.githubusercontent.com/16067358/54424552-6f5fa280-4713-11e9-8155-39f0d4e0d618.png)
@colinegin, @marionf what do you think?
Thanks!

**Comment by TemKaSD** [comment]
Yes, all levels except the current one.

**Comment by colinegin** [comment]
Are you talking specifically about the module's page or in all BO pages ?
Regarding the module configuration page, I agree, there should be a link in the breadcrumb to go back to Module Manager.

**Comment by TemKaSD** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/6318282/54968453-7d8ca900-4fc6-11e9-91df-c26e2a498ef8.jpg)

modules and stmegamenu

**Comment by colinegin** [comment]
Thanks for your feedback ! 
We will discuss it with the dev team to see if we can add this improvement.
