### ISSUE TITLE
PrestaShopException Invalid address #72

### ISSUE THREAD

**Issue by Integraelec** [PrestaShop/PrestaShop#12924]
PrestaShopException is created when going to Orders / shopping carts in BO. Invalid address #72
at line 439 in file classes/Address.php

![Capture](https://user-images.githubusercontent.com/48558437/54362765-c76cab00-4626-11e9-9f52-c1cad2b6b105.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Integraelec,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11416 to fox the issue.
It is fixed in the PS1.7.5.0.
Your ticket is a duplicate of #9782
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9782
