### ISSUE TITLE
product-availability-date is always US format in Spanish language

### ISSUE THREAD

**Issue by cesarfierro** [PrestaShop/PrestaShop#12947]
Hello

Prestashop 1.7.5.1

At the front office, product page always shows the product-availability-date in US format (yyyy-mm-dd) instead of dd-mm-yyyy.

Regards
Cesar

**Comment by khouloudbelguith** [comment]
Hi @cesarfierro,

We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9591
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9591
