### ISSUE TITLE
Can't delete product image in BackOffice

### ISSUE THREAD

**Issue by tone87** [PrestaShop/PrestaShop#12949]
**Describe the bug**
When i try do delete a product image the browser "lock" the page  and the image not delete.
in console of browser not show any message .
in debug mode not show any message.
i tried different browser but the problem it's the same

i updated version with 1-Click Upgrate module from version 1.7.4.2 to 1.7.5.1

**To Reproduce**
1. Go to any product in backoffice
2. Click on any image
3. Click on a Delete button
4. the page lock and not delete the image

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.3.3

**Comment by khouloudbelguith** [comment]
Hi @tone87,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP, check & feedback.

**Comment by tone87** [comment]
i tried to downgrate php version to 7.2.16 now , but problem it's the same . i cleared cache from backoffice and browser too.
[ice_video_20190318-105525.zip](https://github.com/PrestaShop/PrestaShop/files/2977416/ice_video_20190318-105525.zip)

**Comment by khouloudbelguith** [comment]
@tone87, your screen record cannot be opened.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by tone87** [comment]
the bug it's maded by external module "jscomposer" when it's disabled works again.. i close the bug report.

**Comment by khouloudbelguith** [comment]
@tone87, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by TeapotJames** [comment]
Also have had the same issue and can confirm that disabling the Visual Composer module sorts the issue.

Am speaking to the VC module developers about this now.

**Comment by tone87** [comment]
the files comprimised in jscomposer module are :

/modules/jscomposer/assets/lib/vc_carousel/js/transition.js

/modules/jscomposer/assets/lib/bootstrap_modals/css/bootstrap.modals.css

/modules/jscomposer/assets/css/select2.css

remove or leave blank it. the module work correctly with or without this files ;-)

**Comment by tone87** [comment]
the assistance gave me the new version, but anyway it has the same problems both in the modal and in the css of the backoffice in general.
I solved by removing those files I listed you before.

**Comment by kandiaga** [comment]
Hi,
If  you  wish   to   delete multiple  images  at  a time  you can use  this  module:
https://www.prestashop.com/forums/topic/1015827-module-bulk-delete-product-images-for-17-and-16/

**Comment by shikotakcom** [comment]
I have the same problem. this bug has not been solved yet.

**Comment by matks** [comment]
> I have the same problem. this bug has not been solved yet.

If you read the above comments, you'll see there was no bug (and consequently there was no needed solution). The weird behavior came from 3rd party module jscomposer which is outside of this repository scope.
