### ISSUE TITLE
bug change state shipped back-office prestashop 1.7.3.0

### ISSUE THREAD

**Issue by KHATERSAID** [PrestaShop/PrestaShop#12951]
Hello
in the back office when I change the status of the order to shipped status when I click to display the Template does not display completely
can you help me

merci 
![2](https://user-images.githubusercontent.com/39734318/54525437-86e99600-4974-11e9-96c7-786695843af5.png)
![1](https://user-images.githubusercontent.com/39734318/54525438-86e99600-4974-11e9-990f-f332979dfe36.png)

**Comment by khouloudbelguith** [comment]
Hi @said4440,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1EZclmbuxmQH96Vl1n3_l2HYn2-tcozNN/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by said4440** [comment]
host = lws www.lws.fr
server setup and configuration = see picture
PrestaShop version (source) 1.7.3.0
debug mode report =see picture
PHP error logs =see picture
apache error log=see picture
javascript console log=see picture
[debug mode report.txt](https://github.com/PrestaShop/PrestaShop/files/2978467/debug.mode.report.txt)
[PHP error logs.txt](https://github.com/PrestaShop/PrestaShop/files/2978468/PHP.error.logs.txt)
![3](https://user-images.githubusercontent.com/39734318/54535277-7b0acd80-498e-11e9-8037-2b6fb6c6e09e.png)
![4](https://user-images.githubusercontent.com/39734318/54535278-7b0acd80-498e-11e9-8ecb-2b97a41a98b6.png)

**Comment by KHATERSAID** [comment]
I solved the problem
I cleaned PHP sessions in the php configuration of my host
thank you

**Comment by khouloudbelguith** [comment]
@said4440, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by KHATERSAID** [comment]
hello @khouloudbelguith
the problem is back
can you help me I'm going crazy with this problem
I checked everything without success
