### ISSUE TITLE
Undefined index: title_global 

### ISSUE THREAD

**Issue by servidiomarco** [PrestaShop/PrestaShop#12955]
**Describe the bug**
Undefined index: title_global when clicking on any product. 

**To Reproduce**

**Screenshots**
<img width="848" alt="Screen Shot 2019-03-18 at 19 25 19" src="https://user-images.githubusercontent.com/21959141/54553947-9dfba880-49b3-11e9-9489-1bd1ca2931f0.png">
**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 5.6.37

**Comment by khouloudbelguith** [comment]
Hi @servidiomarco,

This issue occurs due to the `nrtcustomtab` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
