### ISSUE TITLE
Fatal error for Chcek update

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#12957]
Hello,
after upgrade to the release 1.7.5.1 the system generates fatal error after pressing the button "Check update":

**To Reproduce**
1. Go to Module Manager
2. Click on Configure for any module, e.g. Bank transfer
3. Click on Check update 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
[PrestaShop] Fatal error in module file: /home/html/abc.sk/public_html/_sub/abc17/modules/inixframe/InixModule.php:4331
Access level to Inix2Module::displayInformation() must be public (as in class ModuleCore)

**Additionnal information**
PrestaShop version:  1.7.5.1 
PHP version: 5.6.36 

Best Regards
Juraj

**Comment by khouloudbelguith** [comment]
Hi @juraj1000,

This issue occurs due to the `inixframe` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
