### ISSUE TITLE
New Token Handling to prevent CSRF

### ISSUE THREAD

**Issue by molearnik** [PrestaShop/PrestaShop#12961]
**This feature request is related to current CSRF tokens implementation**
PrestaShop tokens are supposed to help to prevent CSRF.
However, there are some deviations from good practices in PrestaShop implementation of CSRF tokens.

- The tokens are reusable and they last practically "forever". Tokens are derived from customer id, password and page (PHP script name). Good practices say the tokens should be ideally destroyed and regenerated after being consumed. The same request with the same token should not work more than once, as this can be taken advantage of by Man-in-the-Middle attacks.
- PrestaShop tokens are just weak MD5 hashes of user id, password and page.
- Guests do not have user id, password and therefore PrestaShop tokens generated for Guests can hardly work
- Invalid Tokens on admin page are always handled by simple page providing "Take me out / Continue" links. This itself is vulnerable to “click-happy” users. Some merchants might prefer activation of stricter behavior.

 **Proposal**

- Could you consider implementing CSRF tokens using respected [OWAPS Cross Site Request Forgery Prevention Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md)? Main techniques to consider: 
  - [Synchronizer Token Pattern](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#synchronizer-token-pattern) 
Cannot you maintain tokens in some server side Token Repository? Sessions would be the first choice. Inspiration: Esapi [HTTPUtilities.php](https://github.com/OWASP/PHP-ESAPI/blob/master/src/reference/DefaultHTTPUtilities.php)
  - [Encryption based Token Pattern](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#encryption-based-token-pattern) - suitable for applications that do not want to maintain any state at server side
  - [HMAC Based Token Pattern](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#hmac-based-token-pattern)
- Could you consider providing Merchants with new Admin configuration options for "Invalid CSRF Token" handling? 
Proposed options (expected behavior should be clear):
  - Show PrestaShop Error Page with Take Me Out or Continue Links (Default)
  - Return "HTTP 403 Access Denied" error (more secure)
  - Logout (even more secure but may decrease usability)

**Comment by khouloudbelguith** [comment]
Hi @molearnik,

Thanks for your report.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by molearnik** [comment]
Seems to be related to [pull 5862](https://github.com/PrestaShop/PrestaShop/pull/5862)

**Comment by PierreRambaud** [comment]
Not talking for all core developers, but agreed :+1:

**Comment by nvhaver** [comment]
This still seems to be an issue in the latest version of PrestaShop (1.7.6.1). CSRF can be performed on the shopping cart (e.g. adding items to the cart). Possibly there are other instances of CSRF present in the CMS. Please take this into consideration for the upcoming release...

**Comment by PierreRambaud** [comment]
FYI the token is the URL is not here to prevent CSRF, there is already a token in new Symfony forms that is doing the job.

**Comment by PierreRambaud** [comment]
Closed in favor of #19348
