### ISSUE TITLE
Navbar-toggler faceted navigation

### ISSUE THREAD

**Issue by lukaszwojcik1990** [PrestaShop/PrestaShop#12973]
Hello,
In the module facet navigation, prestashop 1.7, how do you change the lists with attributes closed by default ? And you have to press a button to expand?

an example category where I would like the navigation list to be closed (works on a computer) - https://daars.pl/kolumny-107

greetings

**Comment by khouloudbelguith** [comment]
Hi @lukaszwojcik1990,

Thanks for your report.
Sorry, what do you mean by `attributes closed by default`? 
About the expand action, this feature added in your custom theme
In the Classic theme, this feature doesn't exist.
![image](https://user-images.githubusercontent.com/16067358/54749584-4a68a500-4bd5-11e9-99d2-29b7bfb448da.png)
Thanks!

**Comment by lukaszwojcik1990** [comment]
I am using the Alysum template.
My point is that the list of attributes, like here S, M, XL ... would not be visible, when you click the arrow that will expand it

**Comment by lukaszwojcik1990** [comment]
![1](https://user-images.githubusercontent.com/48737281/54810020-3bd9c680-4c85-11e9-9b48-5e9dc21c2c37.jpg)

**Comment by khouloudbelguith** [comment]
Hi @lukaszwojcik1990,

With the classic theme of PrestaShop it's normal behavior (the navigation list is not closed).
You should contact the theme author, they are the only ones to help you on it.
Thanks!
I close the ticket, feel free to open a new one when needed.
