### ISSUE TITLE
Bloc paiement

### ISSUE THREAD

**Issue by andreepi** [PrestaShop/PrestaShop#12979]
**Describe the bug**

Bloc complètement inactif.
Réinitialisation faite sans succès

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![image](https://user-images.githubusercontent.com/48160466/54686410-82aaad80-4b19-11e9-891a-483b4c2ba9dc.png)

**Additionnal information**
PrestaShop version: 1.6.1.18
PHP version: N/A

**Comment by marionf** [comment]
Hello @andreepi 

Your issue is a duplicate of #12978 so I close it.

Regards
