### ISSUE TITLE
Centralized users data 

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#12984]
We want to provide a scallable application.
And because we're able to add images, files, store translations, mails, etc. We must centralized these data into one directory.

Example:
If you want to use Amazon S3 / Google FileStore / GlusterFs or anything else to store your data
You need to define many `exports` in your nfs configuration. Sometimes mixin php files and images because sometimes developers don't care about where they'll add their files.
And if you're not lucky you'll forget to define one directory. 

The reason is, there are too many directories where to store data.

**Describe the solution you'd like**
Adding something clear and logic:

```
data
├── images
|   ├── welcome.jpg
|   └── logo.jpg
├── translations
|   ├── en-US
|   |   ├── language.zxml
├── download
|   ├── legals.pdf
├── mails
|   ├── en-US
|   |   ├── html
|   |   |  └── welcome.html
|   |   ├── txt
|   |   |   └── welcome.txt

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

Thanks for the suggestion!
Ping @PrestaShop/prestashop-core-developers  , what do you think of Pierre's sugguestion? shall we label it **`To Do`**?

**Comment by matks** [comment]
Hi @PierreRambaud I think it's a very good idea :) maybe something we can start for PrestaShop 8 when its development begins?

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud I think it's a very good idea :) maybe something we can start for PrestaShop 8 when its development begins?

Yes this is what I thought when we will use the standard Symfony structure, it will be easier :)

**Comment by matks** [comment]
Marked as `To Do`

**Comment by jean-io** [comment]
Hello there. Why is this issue closed? and why it as been categorized as "developer issue"?

To my knowledge, this feature request is still relevant and has not been implemented.

**Comment by PierreRambaud** [comment]
> 

I don't plan to work on it, the solution is not the right one. Everything will be handled when the project will follow the Symfony architecture.
