### ISSUE TITLE
Create new Hook Display on Checkout Process

### ISSUE THREAD

**Issue by Darmona** [PrestaShop/PrestaShop#12986]
A lot of module and custom developments want to customize the checkout process to boost the conversion rate or add some marketing best practices, but some more Hooks are needed in the checkout process.

It would be great to add 5 new display hooks in PrestaShop 1.7, to add some good features as : 
- On **the product page**, a display hook just below Add to Cart button
- On **the Checkout Cart Summary**, a display hook just below the Checkout button
- On the 1 step of Checkout, a display hook just above authentication block but below Personal Information text could be a good idea for fast login (social network login for instance)
- For the same reason, same kind of hook on 1-page checkout, a display hook just above authentication block but below Personal Information text. Maybe it is the same hook than the classic checkout hook just above. 
- On the Checkout page, a display hook in the header on the right could be a good idea for reassurance elements.

**Comment by Quetzacoalt91** [comment]
> - On **the Checkout Cart Summary**, a display hook just below the Checkout button

You can already use the hook `displayExpressCheckout` for this case.

**Comment by Quetzacoalt91** [comment]
> On the Checkout page, a display hook in the header on the right could be a good idea for reassurance elements.

You can use the `displayNav1`, after making sure you display your reassurance  elements on the checkout page. :)

**Comment by Quetzacoalt91** [comment]
Done with https://github.com/PrestaShop/PrestaShop/pull/13103

**Comment by Quetzacoalt91** [comment]
By the way @Darmona, about:

> For the same reason, same kind of hook on 1-page checkout, a display hook just above authentication block but below Personal Information text. Maybe it is the same hook than the classic checkout hook just above.

Do we agree there is no specific 1 page checkout on PrestaShop 1.7?

**Comment by Darmona** [comment]
Yes totally, my bad.
