### ISSUE TITLE
ERROR 500 in BO in one tab 1.7.5.1

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#12983]
Have problem with one tab in BO, when I trying to open this tab, get error 500. Have screen with debug mode.

This is tab from courier integration module with list of shipment.

![screencapture-tomskor-pl-admin850kwyszj-index-php-2019-03-20-15_11_10](https://user-images.githubusercontent.com/42567245/54691006-dd94d280-4b22-11e9-9e8a-906a8749c76f.jpg)
![screencapture-tomskor-pl-admin850kwyszj-index-php-2019-03-20-15_11_22](https://user-images.githubusercontent.com/42567245/54691007-dd94d280-4b22-11e9-853e-93f830dfedc2.jpg)

Additionnal information
PrestaShop version: 1.7.5.1
PHP version: 7.2.13

**Comment by matks** [comment]
Hi, I had a similar issue `Call to a member function trans() on null` when I could not download some translation data. I did https://github.com/PrestaShop/PrestaShop/pull/12959 in order to have a better error message. Would this help you ?

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

Did you check your issue after applying the patch created by @matks?
Thanks!

**Comment by Tomskor** [comment]
Yes but look exactly this same. Have same issue with invoices.

![screencapture-tomskor-pl-admin850kwyszj-index-php-sell-orders-invoices-2019-03-21-08_32_40](https://user-images.githubusercontent.com/42567245/54739722-6b230180-4bb9-11e9-9f4c-694f2b0c17c2.jpg)
![screencapture-tomskor-pl-admin850kwyszj-index-php-sell-orders-invoices-2019-03-21-08_32_46](https://user-images.githubusercontent.com/42567245/54739724-6b230180-4bb9-11e9-8d1c-34f939d21282.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

No, this is a different issue.
Thanks to follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12314#issuecomment-462410864 to fix your issue.
We are aware of this issue, it occurs following the upgrade of the shop in some cases.
About your first issue, it is fixed?
Thanks!

**Comment by Tomskor** [comment]
Ok, I fix that bug with invoices.

But saddly my issue with courier list its still there, debug message look this same with code changes. So propably its not it.

**Comment by khouloudbelguith** [comment]
@Tomskor, have you tried to contact the module author about this issue?
Did you buy this module from our addons Market place?
Thanks!

**Comment by Tomskor** [comment]
@khouloudbelguith I contacted them, and waiting for response.

This is official integration module from this courier but it isn't from marketplace.

**Comment by khouloudbelguith** [comment]
@Tomskor, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
