### ISSUE TITLE
Can't debug with XDebug because of Integrity Check Exception

### ISSUE THREAD

**Issue by francisa2d** [PrestaShop/PrestaShop#12992]
We try to do some debugging on a fresh installation of Prestashop 1.7.5.1 (developper mode)  but when we launch XDebug Listening, if we load almost any page, we get an Exception from Defuse : "Integrity Check Failed". Stack trace is too complexe for figure out what's going on... 

**Steps to reproduce the behavior:**

We use VScode, 

1. Configure XDebug for VScode 
2. Launch XDebug Listening
3. Load any page of Prestashop

![image](https://user-images.githubusercontent.com/48791347/54747002-f1494300-4bcd-11e9-9a3d-147e1a3f00cd.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.10
XDebug v2.6.0

**Comment by francisa2d** [comment]
Ok, fixed. Chrome cache was disabled.

**Comment by khouloudbelguith** [comment]
Hi @francisa2d, 

Thanks for your report.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
