### ISSUE TITLE
GDPR isn't working anymore with 1.7.6.0

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13005]
**Describe the bug**
GDPR isn't working anymore with 1.7.6.0

**To Reproduce**
1. Go to Module catalog and install GDPR module
2. Click on configure
3. Click on a link

**Screenshots**
![capture d'écran_1204](https://user-images.githubusercontent.com/13449658/54810031-45fbc500-4c85-11e9-90c5-2a39f5d6904e.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
ping @Joukz & @colinegin

**Comment by matks** [comment]
🔥 👀

**Comment by slupostrupek** [comment]
it already stopped working on 1.7.5 and propably on 1.7.4
![psgdpr](https://user-images.githubusercontent.com/9866119/55479613-c4118180-561e-11e9-9775-feeff0aab30b.jpg)

**Comment by marionf** [comment]
@slupostrupek 

It's ok for me on 1.7.5.1

![capture d'écran_1286](https://user-images.githubusercontent.com/13449658/55480559-e1dfe600-5620-11e9-989c-0bb7549d1af7.png)

I see you have psgdpr version 1.1.2, the last one is 1.1.3

**Comment by marionf** [comment]
Edit: V1.1.2 is available in BO when you install the module and no upgrade available, while the last version available on github is v1.1.3

**Comment by jolelievre** [comment]
And I confirm that the v1.1.3 (available here https://github.com/PrestaShop/psgdpr/releases/tag/v1.1.3) works on 1.7.6, we just need to update addons platform.

**Comment by marionf** [comment]
V1.1.3 of the module is now available in BO and working with PrestaShop 1.7.6.x
So, I close this issue
