### ISSUE TITLE
Function setFieldsToUpdate() does not work for single database table

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#13007]
**Describe the bug**
While you want to simply one field while update an ObjectModel, you could use the setFieldsToUpdate() method. But this one need to have a _shop table associated, to work.

Instead, the ObjectModel is whole saved.

**To Reproduce**
1. Instanciate an ObjectModel (which have no _shop table associated !)
2. Change somes properties
3. Apply the setFieldsToUpdate() method for one of theses modified changes
4. Update the ObjectModel
5. See that the ObjectModel is whole saved, instead of the only field to update.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit,

Could you please send me your script to test it.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @khouloudbelguith ,

No  ; the script was done inside a bigger module and I have remote it since it's not working.

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by matks** [comment]
Hi @PrestaEdit, I guess it happens there: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ObjectModel.php#L746

Indeed `update_fields` seems only used in multishop usecase. I've been able to track this change back to https://github.com/PrestaShop/PrestaShop/commit/84d1e57ad968bb6fd81ba22ac6e4ef40d5efbeee#diff-3a9696437ae9aa19d7b202bbefbe87daR519 and the commit message clearly states that this is built to work only for multishop.

It looks like it was always the intended behavior 🤔

**Comment by PrestaEdit** [comment]
Hi @matks ;

Surely. But it could be usefull to get it work on single shop too, if you want to update only a field for example :)

**Comment by matks** [comment]
OK, I see the idea now.

Actually ... shouldn't it be a default behavior 😄? Like "if I update only field foo of my product, then `update()` only updates SQL field foo, and nothing else" ? Being able to force which fields to update can be useful, but an extended feature (outside of this issue's scope i'd say) would be "ObjectModel must be able to track which fields have been updated, and only perform the required SQL queries to update them".

[Doctrine](https://github.com/doctrine/orm) does that I think

**Comment by matks** [comment]
Nice work @jolelievre !

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25913

Bug might have been there since 2012
