### ISSUE TITLE
In customer's service module a customer's reply is linked to a new thread instead of the correct one

### ISSUE THREAD

**Issue by fededim** [PrestaShop/PrestaShop#13000]
**Describe the bug**
As stated in title

**To Reproduce**
1. Customer selects an order and sends a message about it
![image](https://user-images.githubusercontent.com/8364158/54786858-42872000-4c2a-11e9-8209-ea7002248be8.png)

2. An answer is sent back through the customer service module
![image](https://user-images.githubusercontent.com/8364158/54786923-75c9af00-4c2a-11e9-9084-9132d69f0a45.png)

3. The customer receives an email containing the answer; the mail also prompts not to reply, but to use the provided link for follow up. The link contains a querystring parameter pointing to the right thread id (number 3). The email subject contains strange characters, can anybody tell me why ?
![image](https://user-images.githubusercontent.com/8364158/54787053-e40e7180-4c2a-11e9-8ffe-43ba2f3b7141.png)

4. The customers clicks the link, fills in the form and sends another question.
![image](https://user-images.githubusercontent.com/8364158/54787123-1ae48780-4c2b-11e9-9ba3-606c208c9786.png)

5. In the customer service module the new question is linked to another thread id (number 4).
![image](https://user-images.githubusercontent.com/8364158/54787174-35b6fc00-4c2b-11e9-89bc-0f3c33d2bf41.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.16
MySQL version: 5.7.25-log

**Comment by khouloudbelguith** [comment]
Hi @fededim,

Thanks for your report.
- #ct3 is " #ct%thread_id% ".
- #tcB683GIMPRdkA is " #tc%thread_token% ".
- For id_customer_thread increases with sending a new message.

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @fededim, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by fededim** [comment]
Well what kind of input do you need from me ? I explained all the steps with screenshots in order to reproduce the bug.

> Hi @fededim,
> 
> Thanks for your report.
> 
> * #ct3 is " #ct%thread_id% ".
> * #tcB683GIMPRdkA is " #tc%thread_token% ".
> * For id_customer_thread increases with sending a new message.
> 
> Thanks to check and feedback.

**Comment by Ruman-Git** [comment]
@fededim , Could you fix that problem? I am with the same situation!
