### ISSUE TITLE
DATABASE additional shipping cost reading

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#13019]
This is (another) one crazy situation with prestashop 1.7.2.

Create a product. assign a 10€ value for extra shipping cost.

Open in database that product, 
Set shipping cost to 0€ extra.

Reload cart > still get the extra 10€.

Open product in backoffice, still 10€ in extra shipping cost.

Reload product in DB, the shipping cost save in the ps_products tab is 0.

So WHERE prestashop get this data?!

Mysql query is cleared .. and this is crazy.
![HOW THIS IS POSSIBLE WHERE PS READ THE DATA](https://user-images.githubusercontent.com/24798703/54837675-4ae16880-4cc7-11e9-9a57-b9c7a8bea549.png)

**Comment by Matt75** [comment]
Check into ps_product_shop

**Comment by matteolavaggi** [comment]
Why?
There is no index for products in category but there is 2 table for the same setting , i would cry.
