### ISSUE TITLE
Error 500 during 1.7.5.1 install

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#13011]
**Describe the bug**
During 1.7.5.1 install, at the beginning, I have an error 500 without messages but with success = true.

**To Reproduce**
1. Download 1.7.5.1 zip here : https://www.prestashop.com/fr/telecharger
2. Unzip files
3. Configure install
4. Launch install

**Screenshots**
![chrome_2019-03-22_14-51-54](https://user-images.githubusercontent.com/4289331/54827375-19aa6d80-4cb2-11e9-9d66-20baa7b04ca7.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @bm-services,
Could you please follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by bm-services** [comment]
Thanks for this link !

I have only these 4 problems:

memory_limit | 64M | 256M | 128M
post_max_size | 16M | 128M | 16M
upload_max_filesize | 4M | 128M | 12M
Memcached | No | Yes | No

However, they are not blocking

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

What is the exact Language/Country did you used during the installation?

Thanks!

**Comment by bm-services** [comment]
My language / country:
French/France

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

I tried the installation with the file that is in " https://www.prestashop.com/fr/telecharger " with French language and France country =>OK.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Any news about your issues?
Thanks!

**Comment by bm-services** [comment]
No, I have no more information and the mistake is still relevant.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Thanks for your feedback.
In fact, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong. 
Could you please provide us with more info?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Sorry but since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
