### ISSUE TITLE
Function create_function() is deprecated in php7.2

### ISSUE THREAD

**Issue by tczaude** [PrestaShop/PrestaShop#13015]
PHP message: PHP Deprecated:  Function create_function() is deprecated in ..../modules/gamification/classes/GamificationTools.php on line 42" while reading response header from upstream, client: xx. xx xx xx, server: ....., request: "POST

**Comment by scorpio-angel** [comment]
Hello,

in file classes/module/module.php is create_function too, with deprecated state.
Use this change 
_FROM
usort($module_list, create_function('$a,$b', 'return strnatcasecmp($a->displayName, $b->displayName);'));
_TO:
usort($module_list, function($a, $b) (return strnatcasecmp($a->displayName, $b->displayName);));

**Comment by scorp1czech** [comment]
Hello,

in file classes/module/module.php is create_function too, with deprecated state.
Use this change
_FROM
usort($module_list, create_function('$a,$b', 'return strnatcasecmp($a->displayName, $b->displayName);'));
_TO:
usort($module_list, function($a, $b) {return strnatcasecmp($a->displayName, $b->displayName);});
Good instances can found [here](https://stackoverflow.com/questions/48161526/php-7-2-function-create-function-is-deprecated)

**Comment by khouloudbelguith** [comment]
Hi,

Here's the PR: https://github.com/PrestaShop/gamification/pull/61 to fix the issue.

Thanks!
