### ISSUE TITLE
Gamification optimisation

### ISSUE THREAD

**Issue by amarock** [PrestaShop/PrestaShop#13017]
**Is your feature request related to a problem? Please describe.**
Le module gamification fait de nombreuses requêtes externes pour télécharger des CSS selon le conseil affiché.

Actuellement cette opération ne semble plus utile, les feuilles de style étant intégrée dans le fichier de configuration JSON.

**Describe the solution you'd like**
Supprier les lignes suivantes dans le module gamification, fichier gamification.php

```
$advice_css_path = __DIR__.'/views/css/advice-'._PS_VERSION_.'_'.(int)$advice['id_ps_advice'].'.css';
               // 24h cache
               if (!$this->isFresh($advice_css_path, 86400)) {
                   $advice_css_content = Tools::file_get_contents(Tools::getShopProtocol().'gamification.prestashop.com/css/advices/advice-'._PS_VERSION_.'_'.(int)$advice['id_ps_advice'].'.css');
                   file_put_contents($advice_css_path, $advice_css_content);
               }
               if (filesize($advice_css_path) > 0) {
                   $this->context->controller->addCss($this->_path.'views/css/advice-'._PS_VERSION_.'_'.(int)$advice['id_ps_advice'].'.css');
               }
```

**Describe alternatives you've considered**
-

**Additional context**
Les fichiers CSS retournés sont tous vide de toutes façon.

**Comment by eternoendless** [comment]
Fixed here: https://github.com/PrestaShop/gamification/pull/64
