### ISSUE TITLE
`Translate::getModuleTranslation()` with locale returns string in wrong language if there is none in provided locale

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#13024]
In a cron task, we need to generate a french and an english version. As we can't rely on context language, we use `Translate::getModuleTranslation()` and pass the `Locale` as a parameter.

We found that in `getModuleTranslation` it will populate `$_MODULES` array with the translation. Problem is that it doesn't care of the locale and the context and so it will mix french and english in `$_MODULES`. As we don't have english translation in our translation file, we end up with french text even if we specify english in our locale if the current context in french and if `$_MODULES` is already used,

---

#### Describe the bug

Using $this->l() with locale provided uses last language instead of falling back to english/base string/empty string/throwing exception/whatever.
I added pl, de, fr to default english, and for example, when I have translation in polish, but doesn't have german and french, instead of english/whatever I get polish.

#### Expected behavior

I would like to get english/base string/empty string/exception thrown/something that would indicate that there is no such string in given language.

#### Steps to Reproduce

My module is working on certain products, so I thought I'll add them in code and wrote function that uses translations to insert needed products and categories to database. I run this function is run inside modules getContent() and dump its return for testing purposes. If some string doesn't have translation in given locale I get one from previous language.

```
    public function generateLanguageArrayForString($string, $module) : array
    {
        $langarr = [];
        $activeLangs = Language::getLanguages();
        foreach ($activeLangs as $lang) {
            $langarr[(int)$lang['id_lang']] = $this->l($string, $module, $lang['locale']);
        }
        return $langarr;
    }
```
For example, when ran on "Category name" which has only polish and english translations, I get this:
```
array(4) {
  [1]=>
  string(13) "Category name"
  [6]=>
  string(15) "Nazwa kategorii"
  [7]=>
  string(15) "Nazwa kategorii"
  [8]=>
  string(15) "Nazwa kategorii"
}
```

#### Additional information
When `global $_MODULES, $_MODULE, $_LANGADM;` inside _Translate.php_'s _getModuleTranslation()_
 is changed into `$_MODULES = array(); $_MODULE = array(); $_LANGADM = array();` I get translations only for languages that have them, otherwise I get base string (but when I add english translation that is different from base string, I don't get this one, which is pretty weird). But apart from weird issue with english, the _global_ must be there for a reason, and I don't want to change things outside of module's code for this to work.

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

Thanks for your report.
ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi!

As reported by @marekjedrzejewski, you can use his custom module to test this issue.

[langtest.zip](https://github.com/PrestaShop/PrestaShop/files/5057501/langtest.zip)


Could be fixed by https://github.com/PrestaShop/PrestaShop/pull/20537

Thanks @marekjedrzejewski

**Comment by marekjedrzejewski** [comment]
> Hi!
> 
> As reported by @marekjedrzejewski, you can use his custom module to test this issue.
> 
> [langtest.zip](https://github.com/PrestaShop/PrestaShop/files/5057501/langtest.zip)
> 
> Could be fixed by #20537
> 
> Thanks @marekjedrzejewski

Fix in #20537 was very naive and breaks if there is more than one string. To test this it's best to add some more strings, to have more robust solution.

**Comment by marekjedrzejewski** [comment]
Due to no movement in PR I ended up copying getModuleTranslation() inside the module I'm using it in and removing file caching so I always get either original string, or translation in language I want, no caching leftovers. Here's code, if anyone stumbled upon this, and there's still no official fix (changed arguments order):

```
    private function getTranslation(
        $originalString,
        $source,
        $locale = null,
        $escape = true,
        $sprintf = null,
        $js = false,
        $fallback = true
    ) {
        $translations = [];
        global $_MODULE;

        $name = $this->name;

        if (null !== $locale) {
            $iso = Language::getIsoByLocale($locale);
        }

        if (empty($iso)) {
            $iso = Context::getContext()->language->iso_code;
        }

        $filesByPriority = [
            // PrestaShop 1.5 translations
            _PS_MODULE_DIR_ . $name . '/translations/' . $iso . '.php',
            // PrestaShop 1.4 translations
            _PS_MODULE_DIR_ . $name . '/' . $iso . '.php',
            // Translations in theme
            _PS_THEME_DIR_ . 'modules/' . $name . '/translations/' . $iso . '.php',
            _PS_THEME_DIR_ . 'modules/' . $name . '/' . $iso . '.php',
        ];
        foreach ($filesByPriority as $file) {
            if (file_exists($file)) {
                include $file;
                $translations = !empty($translations) ? array_merge($translations, $_MODULE) : $_MODULE;
            }
        }

        $string = preg_replace("/\\\*'/", "\'", $originalString);
        $key = md5($string);

        $cacheKey = $name . '|' . $string . '|' . $source . '|' . (int) $js . '|' . $iso;
        if (isset($langCache[$cacheKey])) {
            $ret = $langCache[$cacheKey];
        } else {
            $currentKey = strtolower('<{' . $name . '}' . _THEME_NAME_ . '>' . $source) . '_' . $key;
            $defaultKey = strtolower('<{' . $name . '}prestashop>' . $source) . '_' . $key;

            if ('controller' == substr($source, -10, 10)) {
                $file = substr($source, 0, -10);
                $currentKeyFile = strtolower('<{' . $name . '}' . _THEME_NAME_ . '>' . $file) . '_' . $key;
                $defaultKeyFile = strtolower('<{' . $name . '}prestashop>' . $file) . '_' . $key;
            }

            if (isset($currentKeyFile) && !empty($translations[$currentKeyFile])) {
                $ret = stripslashes($translations[$currentKeyFile]);
            } elseif (isset($defaultKeyFile) && !empty($translations[$defaultKeyFile])) {
                $ret = stripslashes($translations[$defaultKeyFile]);
            } elseif (!empty($translations[$currentKey])) {
                $ret = stripslashes($translations[$currentKey]);
            } elseif (!empty($translations[$defaultKey])) {
                $ret = stripslashes($translations[$defaultKey]);
            } elseif (!empty($_LANGADM)) {
                // if translation was not found in module, look for it in AdminController or Helpers
                $ret = stripslashes(Translate::getGenericAdminTranslation($string, $key, $_LANGADM));
            } else {
                $ret = stripslashes($string);
            }

            if (
                $sprintf !== null &&
                (!is_array($sprintf) || !empty($sprintf)) &&
                !(count($sprintf) === 1 && isset($sprintf['legacy']))
            ) {
                $ret = Translate::checkAndReplaceArgs($ret, $sprintf);
            }

            if ($js) {
                $ret = addslashes($ret);
            } elseif ($escape) {
                $ret = htmlspecialchars($ret, ENT_COMPAT, 'UTF-8');
            }

            if ($sprintf === null) {
                $langCache[$cacheKey] = $ret;
            }
        }

        if (!is_array($sprintf) && null !== $sprintf) {
            $sprintf_for_trans = [$sprintf];
        } elseif (null === $sprintf) {
            $sprintf_for_trans = [];
        } else {
            $sprintf_for_trans = $sprintf;
        }

        /*
         * Native modules working on both 1.6 & 1.7 are translated in messages.xlf
         * So we need to check in the Symfony catalog for translations
         */
        if ($ret === $originalString && $fallback) {
            $ret = Context::getContext()->getTranslator()->trans($originalString, $sprintf_for_trans, null, $locale);
        }

        return $ret;
    }
```

**Comment by matks** [comment]
> ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?

Sorry for late answer, I confirm this is a bug.

**Comment by eternoendless** [comment]
I found this bug a couple months ago while working on #24401. I can't find if I documented what I found but to me this looks like an unfixable bug: module translations are stored in a global variable `$_MODULES` and indexed by a key that is not locale sensitive (key is [documented here](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/classic-system/#editing-a-dictionary-file-manually)). Fixing this would involve a breaking change (changing the way `$_MODULES` is indexed), meaning that it wouldn't work in previous PrestaShop versions, and in that case, you could as well just switch to the new translation system, that doesn't have this problem.

**Comment by eternoendless** [comment]
I'm going to go ahead and just close it as won't fix. Feel free to contribute to the discussion if you think this can be fixed in a backward compatible way.
