### ISSUE TITLE
Multistore, URL subdirectory, cart problem, 404 

### ISSUE THREAD

**Issue by falanga1** [PrestaShop/PrestaShop#13029]
**Describe the bug**
Can't add product to cart (or access cart) because of 404 error in Multistore with virtual URLs set

**To Reproduce**

1. Fresh Install Prestashop (install language English and shop location Poland, so that after install shop has two languages: Polish and English)
2. Shop Parameters -> General -> Enable Multistore -> Yes
3. Advanced Parameters -> Multistore -> Add new shop "Shop2"
4. Now setting virtual URLs for both shops: Shop 1: "en" Shop 2: "pl"
5. International -> Localization  -> Languages -> English language set only for shop1 , Polish language set only for shop2

Go to sample product page and try to add product to cart. Console log:

Failed to load resource: the server responded with a status of 404 (Not Found)
core.js:39 
POST http://website.com/pl/koszyk 404 (Not Found)
send @ core.js:39ajax

**Additional Information**
PrestaShop 1.7.5.1
PHP Version testet with both 5.6.40 / 7.2.16

**Comment by falanga1** [comment]
closing the issue - I narrowed it down to simpler symptoms
https://github.com/PrestaShop/PrestaShop/issues/13032

**Comment by zinebnouari** [comment]
Hey can you please tell me what was your solution?
