### ISSUE TITLE
Migrate "Advanced Parameters > Team > Employees > Profiles > Add new profile" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13038]
Type: page
Available by `/admin-dev/index.php/configure/advanced/profiles/1/edit`

Todo:
-  [x] Migrate CRUD form https://github.com/PrestaShop/PrestaShop/pull/13076

**Comment by matks** [comment]
We forgot to create the github issue for this page.

**Comment by jolelievre** [comment]
Thank you @sarjon
