### ISSUE TITLE
Fresh Prestashop 1.7.5.1 instance - Friendly URL not working when shop virtual URL set

### ISSUE THREAD

**Issue by falanga1** [PrestaShop/PrestaShop#13032]
**Describe the bug**
When Friendly URL ON and Shop virtual URL set (for example to "/en") there are 404 errors 
(this is fresh PrestaShop Instance) 

**To Reproduce**
1. Go to http://pandeczusia.ga
2. Click on "Contact" in the footer, or try to add anything to cart
3. See error 
4. Problems occurs only when Friendly URL on 

**Additionnal information**
This is fresh prestashop instance with multistore enabled and virtual url set to "en" 

I already tried regenerating htaccess by turning on and off Friendly URL, I also tried combination of "Disable Apache's MultiViews option" on/off and "Disable Apache's mod_security module" on/off

I also tried to disable all modules. 

Server has mod_rewrite turned on http://pandeczusia.ga/phpinfo.php

PrestaShop version: 1.7.5.1
PHP version: tested with both 5.6 and 7.2

**Comment by falanga1** [comment]
It was problem with hosting all along - closing

**Comment by ilmtech** [comment]
Hi,
I'm also facing this issue. Can you tell me what kind of error to notify the hosting people about?
