### ISSUE TITLE
Calls to `trans` in Module context should fall back to the legacy translation system

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#13039]
**Is your feature request related to a problem? Please describe.**
There are currently two problems:
1. As a module developer, I need to be aware that if my module is not native, I have to use the legacy translation system (`l()`) instead of the Symfony one (`trans()`).
2. As a module developer, if my module is symfony-based, I cannot use translation in twig, because `trans()` will use the new translation system, and `l()` is not available.

**Describe the solution you'd like**
All module developers should be able to use `trans()` regardless of the underlying translation system.
`trans()` should fall back to the legacy translation system if:
- The translation domain belongs to a module (ie. it starts with `Modules.`)
- The domain doesn't exist in the translation catalogue, or the wording is untranslated.

This can be easily done in `PrestaShopTranslatorTrait`, which powers the `trans()` method in `ModuleCore` or in `ModuleCore` itself.

Regarding Twig, the native `trans()` will have to be overridden (I'm not sure how).

In a future version, modules should expose xliff or yaml files with their translations, which will allow us to fully phase out the legacy system.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mickaelandrieu** [comment]
Locked by https://github.com/PrestaShop/PrestaShop/pull/11321 for now.

Thanks for the issue, once https://github.com/PrestaShop/PrestaShop/pull/11321 merged I'll work on a first contribution with the tests.

**Comment by mickaelandrieu** [comment]
> As a module developer, I need to be aware that if my module is not native, I have to use the legacy translation system (l()) instead of the Symfony one (trans()).

warning on that: there is no way to figure out if a module is native or not because we don't tag native modules with a specific tag or parameter. This can't be addressed at the translation level, but maybe at "module" level?

What do you suggest to inform the developer? I guess documentation is the solution :/

Workaround suggested when we want to use the new translation system in the modules => https://github.com/friends-of-prestashop/masterclass/blob/master/masterclass.php#L127

**Comment by eternoendless** [comment]
> there is no way to figure out if a module is native or not

I think you misunderstood what I meant:

> As a module developer, I need to be aware that if my module is not native, I have to use the legacy translation system (l()) instead of the Symfony one (trans()).

This **actually is a problem that needs to be solved**. As a module developer, I shouldn't _need_ to be aware if my module is native or not, I should just be able to use `trans()` and live happily ever after.
