### ISSUE TITLE
bug change state back-office commands prestashop 1.7.3

### ISSUE THREAD

**Issue by KHATERSAID** [PrestaShop/PrestaShop#13030]
hello
the problem is back
when I change the state of the command, the display becomes crazy
this problem is on the back office
I really try to solve the problem for weeks without success
in debug mode no error message
help to save me

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 7.1

![httpsherboristeenligne comadminlwsindex phpcontroller=AdminOrders id_order=10 vieworder token=09ea5642bc3995bdb592087fcaf69867 - G](https://user-images.githubusercontent.com/39734318/54881820-629a2780-4e54-11e9-86b6-ad7bde1fa21f.jpg)
![Commandes  Commande 583378836 de gzqsg egeg • Herboriste en ligne - Google Chrome_2](https://user-images.githubusercontent.com/39734318/54881821-629a2780-4e54-11e9-95be-684e7ccdeab4.jpg)
![Commandes  Commande 583378836 de gzqsg egeg • Herboriste en ligne - Google Chrome](https://user-images.githubusercontent.com/39734318/54881822-629a2780-4e54-11e9-986a-fd08a068b6d9.jpg)
![Commandes • Herboriste en ligne - Google Chrome](https://user-images.githubusercontent.com/39734318/54881823-629a2780-4e54-11e9-8468-4a96af182d10.jpg)

**Comment by khouloudbelguith** [comment]
Hi @said4440,

Thanks for your report.
In your last issue created https://github.com/PrestaShop/PrestaShop/issues/12951#issuecomment-473928146, you solved your problem by cleaning the PHP sessions in the php configuration of your host.
So, it could be the problem related to the cache.
Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by KHATERSAID** [comment]
Hello@khouloudbelguith,
I manually delete the cache of my prestashop I clear the cache of my browser I try several browser unsuccessful

**Comment by khouloudbelguith** [comment]
@said4440, this issue occurs only with this status?
When you change the status of your order to another one except "shipped" => it is OK?
Thanks!

**Comment by KHATERSAID** [comment]
last week just shipped status
now all the statues
this problem drives me crazy
![222](https://user-images.githubusercontent.com/39734318/54912449-f3bedc00-4ef0-11e9-9533-9098f8447dc8.png)

**Comment by khouloudbelguith** [comment]
@said4440, We need to retrieve the PHP error logs in order to find out what's wrong. If you don't have it, you should ask to your hosting provider.

Thanks!

**Comment by said4440** [comment]
hello I empty the cache of several folder to see if the problem comes from the
now I am no longer in the back office and at my site
I put all the files as before but it always gives me error
![444](https://user-images.githubusercontent.com/39734318/54916437-d0e4f580-4ef9-11e9-99c4-dd7461a4ef82.png)

**Comment by KHATERSAID** [comment]
here is the file thank you
![1111111](https://user-images.githubusercontent.com/39734318/54917355-f246e100-4efb-11e9-8746-75ea9a047b9d.png)

[error php.txt](https://github.com/PrestaShop/PrestaShop/files/3003058/error.php.txt)
![88](https://user-images.githubusercontent.com/39734318/54917215-9a0fdf00-4efb-11e9-97f1-24f7154ca6f5.png)
![99](https://user-images.githubusercontent.com/39734318/54917262-b9a70780-4efb-11e9-98ac-2da905693bea.png)

**Comment by khouloudbelguith** [comment]
@said4440, the method name "getDeliveryNumberFormatted" doesn't exist in the OrderInvoice Class: https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/classes/order/OrderInvoice.php
I think you have an override of the `OrderInvoice` class, it is located into the path /Project_Folder/override/classes/order
Thanks to check & feedback.

**Comment by KHATERSAID** [comment]
I replace the two files orderinvoice
I empty all caches / cache (prod & dev).
I also empty the browser cache and the cache via the backoffice
it does'nt work
![0000](https://user-images.githubusercontent.com/39734318/54924183-1c080400-4f0c-11e9-9b42-c7bdb1cf9c08.png)
![00](https://user-images.githubusercontent.com/39734318/54924184-1c080400-4f0c-11e9-8f7d-f7a3f8ca0b28.png)

**Comment by khouloudbelguith** [comment]
@said4440, did you replace those files with what files exactly?
Those overrides are created by a custom module? or your custom development?
Thanks!

**Comment by KHATERSAID** [comment]
I replace with your link

https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/classes/order/OrderInvoice.php

**Comment by Matt75** [comment]
You have a module named `ba_prestashop_invoice`, try to disable it
Contact this module developer to have assistance

**Comment by khouloudbelguith** [comment]
@said4440, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by KHATERSAID** [comment]
thanks for your help last question
the module I deleted for weeks
but I see he's still in phpmyadmin in my database
if I delete, will there be consequences?
![66666](https://user-images.githubusercontent.com/39734318/54926661-12cd6600-4f11-11e9-9a68-12a4b8ddff33.png)

**Comment by khouloudbelguith** [comment]
@said4440, you should make a backup of your database before deleting these columns.
Thanks!

**Comment by KHATERSAID** [comment]
Hello
I delete the module everywhere
I empty cache dev / prod + smarty + cache
recompile by force
I replace the file ordervoice php and tpl
I also delete everything that is in reference with this module in overide
I still have this error message
I saw on google many people we have the same problem as me but never a solution
I'm lost
![lost](https://user-images.githubusercontent.com/39734318/55000574-15908f80-4fd3-11e9-8fe7-6f138a922931.png)

**Comment by khouloudbelguith** [comment]
@said4440, always the same issue, it is related to the method name "getDeliveryNumberFormatted" which is provided by your custom module.
You need to contact the module author about this issue.
Thanks!
