### ISSUE TITLE
Force country price display not working

### ISSUE THREAD

**Issue by pperezclavei** [PrestaShop/PrestaShop#13042]
I have a product with two specific prices:

The first for "All countries" (20€)
The second for "Germany" (40€)

If I activate the geolocation by IP, everything works correctly. If I access from Germany, it shows me € 40 and if we access from another place, it shows € 20. All right.

And now my question comes, if I deactivate the geolocation by IP, how can I force PHP to simulate being in Germany, for example in Spain? We have been struggling with "$ this-> context-> country" but without success.

We need this because regardless of where we are, we give the option to change the country in the FrontOffice.

**TO REPRODUCE**
1. Within the hook "hookDisplayHeader" and "hookHeader" I have added the country Germany in a fixed way. 
![1](https://user-images.githubusercontent.com/48911274/54920570-d6473d80-4f03-11e9-829b-edb739ecf4e9.JPG)

2. The product "Today is a good day Framed poster" I have assigned two specific prices, one for all countries and one for Germany.
![2](https://user-images.githubusercontent.com/48911274/54920573-d6473d80-4f03-11e9-9f2b-3cae5016c3bc.JPG)

3. When I access, on the CATEGORY page it is displayed correctly, however, when I access the product form or add it to the shopping cart, it does not give me the price for Germany. 
Attached capture named 3.jpg
![3](https://user-images.githubusercontent.com/48911274/54920574-d6dfd400-4f03-11e9-89c1-416d776cc5a7.JPG)
![4](https://user-images.githubusercontent.com/48911274/54920576-d7786a80-4f03-11e9-8301-48350945ecb6.JPG)
![5](https://user-images.githubusercontent.com/48911274/54920577-d7786a80-4f03-11e9-931c-299d3f758f69.JPG)

**Additionnal information**
PrestaShop version: Tested in version 1.7.3.4 and 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @pperezclavei,

Thanks for your report.
In the FO, when I change the country of the customer, the specific price is well displayed.
I attached a video record.
https://drive.google.com/file/d/1DWvFpAqHF6pXGN0j8fkVdzLG9q8KmEha/view
Thanks to check & feedback.

**Comment by pperezclavei** [comment]
> Hi @pperezclavei,
> 
> Thanks for your report.
> In the FO, when I change the country of the customer, the specific price is well displayed.
> I attached a video record.
> https://drive.google.com/file/d/1DWvFpAqHF6pXGN0j8fkVdzLG9q8KmEha/view
> Thanks to check & feedback.

Hi @khouloudbelguith !

Thank you very much for the reply.

Effectively, it works correctly when you login and create a shipping address to the country.

But my problem is that they access anonymous people and they can not create shipping addresses. I thought that the correct solution is to change the country in the context of Prestashop (capture of point 1), but it is not the correct result.

Thank you

**Comment by khouloudbelguith** [comment]
@pperezclavei, Thanks for your feedback.
There is no screenshot attached
You need to login to GitHub & upload the picture here.
Thanks!

**Comment by pperezclavei** [comment]
> @pperezclavei, Thanks for your feedback.
> There is no screenshot attached
> You need to login to GitHub & upload the picture here.
> Thanks!

I was referring to point 1 of the main comment:
![Captura](https://user-images.githubusercontent.com/48911274/54989354-9beba800-4fb8-11e9-9eff-7d0bea0a0df4.JPG)

**Comment by khouloudbelguith** [comment]
@pperezclavei,
>But my problem is that they access anonymous people and they can not create shipping addresses. 

What is the exact problem do you have?

Thanks!

**Comment by pperezclavei** [comment]
> @pperezclavei,
> 
> > But my problem is that they access anonymous people and they can not create shipping addresses.
> 
> What is the exact problem do you have?
> 
> Thanks!

The problem is that a product has been assigned to it.
When I access, on the CATEGORY page it is displayed correctly, however, you will not have to put the price of Germany. This is reproducible for example with a guest user.

**Comment by khouloudbelguith** [comment]
@pperezclavei, 

>The problem is that a product has been assigned to it.

What do you mean exactly? => You created a specific price for such country (Germany)?

>When I access, on the CATEGORY page it is displayed correctly, however, you will not have to put the price of Germany. This is reproducible for example with a guest user.

This issue occurs after your update? "Within the hook "hookDisplayHeader" and "hookHeader" I have added the country Germany in a fixed way, if yes, this is not the correct solution.
Thanks to check & feedback.

**Comment by pperezclavei** [comment]
> @pperezclavei,
> 
> > The problem is that a product has been assigned to it.
> 
> What do you mean exactly? => You created a specific price for such country (Germany)?
> 
> > When I access, on the CATEGORY page it is displayed correctly, however, you will not have to put the price of Germany. This is reproducible for example with a guest user.
> 
> This issue occurs after your update? "Within the hook "hookDisplayHeader" and "hookHeader" I have added the country Germany in a fixed way, if yes, this is not the correct solution.
> Thanks to check & feedback.

I added Germany in a fixed way to do the test.

The objective is to change the country from a popup and show its prices, regardless of the country where you are or have defined in the shipping address (in the case of registered customers).

What should I change so that the prices are from the selected country? Seeing that changing the "$this->context->country" does not work for me.

Thank you

**Comment by khouloudbelguith** [comment]
Hi @pperezclavei,

This is not the correct solution.
There are 2 solutions: enable the geolocation to know which country is the customer or with the address step.

Thanks!
                                    -

**Comment by khouloudbelguith** [comment]
Hi @pperezclavei,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
