### ISSUE TITLE
New links and texts on the "useful links" block on Dashboard 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13044]
Some links in the "useful links" block on the dashboard are not correct anymore. 
We decided to modify them and to give this block a refresh.

## Current

![Capture d’écran 2019-03-25 à 15 50 35](https://user-images.githubusercontent.com/47456895/54931583-8f644280-4f19-11e9-9964-88b2f92093bc.png)

___

## New

![Capture d’écran 2019-03-25 à 17 49 27](https://user-images.githubusercontent.com/47456895/54938312-66967a00-4f26-11e9-8f4c-fe95d111c0c4.png)

**Block Title:** 
* h3 text "Useful links" must be replaced by "We stay by your side!"
* To guarantee same display as today, there should be a space at the beginning of the string or some space between icon and text
* Title should still be translated according to the shop's language, as it is currently

**Links with descriptions:**
* Instead of the 4 links with descriptions we now have 2 links with descriptions, as follows: 

>Help Center 
>Documentation, support, experts, training... PrestaShop and all of its community are here to guide you

>PrestaShop Marketplace
>Traffic, conversion rate, customer loyalty... Increase your sales with all of the PrestaShop modules and themes

* These texts should still be translated according to the shop's language, as it is currently
* Links available [here](https://docs.google.com/spreadsheets/d/11n2ichTRER1Ya_p2assqv2RNc48R4atIRXF9UP1uFlI/view?ts=5c86913b#gid=6), line 391 for "Help Center" link and line 401 for "PrestaShop Marketplace" link
* links' URLs exist in 8 languages: FR, EN, ES, DE, IT, NL, PT, PL, according to the shop's language, as it is today
* If there is no URL corresponding to the shop's language, URL for EN language should be used, as it is today

**Contact us! link:**
* We do not have this link anymore

**Comment by eternoendless** [comment]
Fixed by #13095
