### ISSUE TITLE
Doctrine Migration mechanism to use for updates

### ISSUE THREAD

**Issue by ronskyi** [PrestaShop/PrestaShop#13046]
I want to use GIT for the whole project, as we're going to use dev\staging\prod envs. So when I need to update PrestaShop core I need to update files and DB separately. Right now I can update one instance with 1-Click Upgrade module. It will upgrade both files and DB. Other instances will need DB only upgrade after git pull. I think the migration mechanism will work for this, as you're already migrating to Symfony.

So It would be nice upgrade flow look likes:

- update dev instance with any module (files only or files + DB)
- git push

Other instances:

- git pull
- composer install
- php bin/console cache:clear
- php bin/console migrate

**Comment by khouloudbelguith** [comment]
Hi @ronskyi,

Thanks for your report.
ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by matks** [comment]
Maybe a solution would be to extract the code dedicated to database migration from https://github.com/PrestaShop/autoupgrade into a stand-alone library and provides a CLI command to use this stand-alone library to run them onto the project.

But there's the issue of the install folder being deleted on PROD instance.

@Quetzacoalt91 The idea is to be able to either upgrade the database or the files, not both. Wdyt ?

**Comment by Quetzacoalt91** [comment]
There is an entrypoint available in the core if you want to upgrade the database schema, as mentionned in the documentation: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#database-upgrade

When the file copy is completed, you should call the following script
`php install/upgrade/upgrade.php`. Do not forget to remove the installation folder once you're done, which should not be present on production environment.

**Comment by ronskyi** [comment]
@Quetzacoalt91, thnx, missed this, and not got an answer in the gitter channel, this can work in my case
Install folder is still a question, I should leave it in git, but delete in prod, but not so important as DB.

**Comment by PierreRambaud** [comment]
I'm closing this issue since @Quetzacoalt91 answer you with a link to the documentation :)
