### ISSUE TITLE
Prestashop issue after upgrade 1.7.5.0 -> 1.7.5.1

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#13045]
I have upgraded Prestashop with 1-Click Upgrade module from 1.7.5.0 to 1.7.5.1 it seems it failed during database upgrade.

The Back office seems to work and 1-Click Upgrade module shows these messages : 
Congratulations, you are already using the latest version available!
 6 file modifications have been detected, including 6 from core and native modules:
config/defines.inc.php
img/favicon.ico
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MediaWikiInstaller.php
Differences between versions:
 0 files will be modified, 0 files will be deleted (if they are found).

But on Front office I have this error : 
UndefinedMethodExceptionAttempted to call an undefined method named "initLogoAndFavicon" of class "IndexController".
--
in FrontController.php line 32

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

Did you use the 1-click upgrade v4.6.0.?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by guigplt** [comment]
Yes I used 1-click upgrade v4.6.0.

[log.txt](https://github.com/PrestaShop/PrestaShop/files/3004444/log.txt)

**Comment by khouloudbelguith** [comment]
@guigplt, in your log file, you don't have errors or warnings during the upgrade from PS1.7.5.0 to PS1.7.5.1.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by guigplt** [comment]
I have deleted all folders in /var/cache and it works now, thanks !
Is it possible some parts have not been upgraded ?
And how can I see it ?

**Comment by guigplt** [comment]
The error is here again.

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

After removing the cache `rm -fR var/cache/*` 
could you please try to run these commands:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks to check & feedback.

**Comment by guigplt** [comment]
I removed the cache.
Here are the results of the commands :

**php -d memory_limit=-1 ./bin/console cache:clear**
PHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /var/www/vhosts/.../vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 524

Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /var/www/vhosts/.../vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 524

**php -d memory_limit=-1 ./bin/console cache:clear --env=prod**
PHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /var/www/vhosts/.../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 201

Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /var/www/vhosts/.../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 201

**Comment by khouloudbelguith** [comment]
@guigplt, what is the exact PHP version that you use?

**Comment by guigplt** [comment]
PHP 7.0.21

**Comment by khouloudbelguith** [comment]
@guigplt, thanks to navigating to you BO => Advanced Parameters => information page => provide me the exact php version displayed.
Also, thanks to check with `php info` file, the exact version php displayed. Is there any difference?
Thanks!

**Comment by guigplt** [comment]
I confirm :
In BO information page : 7.0.21
In PHP info : 7.0.21

**Comment by khouloudbelguith** [comment]
@guigplt, thanks for your feedback.
On your side, thanks to remove the folder modules/autoupgrade, clear cache, check & feedback.

**Comment by guigplt** [comment]
I removed the folder and clear cache, but still not working...

**Comment by guigplt** [comment]
Do you know why it worked when I removed /var/cache the first time, and then it doesn't work anymore ?
As I asked you before, is it possible some parts have not been upgraded ?
And is it possible to reinstall last version of Prestashop ?

**Comment by khouloudbelguith** [comment]
@guigplt, 
1. the first issue it could be related to the cache files permissions, to don't have write/read permission to the cache folder.
2. It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.1
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql
3. if you re-install the prestashop, you should make a backup of your database, of your folder before, to avoid problems.

Thanks!

**Comment by guigplt** [comment]
1. The permissions on /var/cache are 755 and subfolder 775.
2. Difficult to see if there are missing columns in database. Can I import this structure in my database to update it ?
3. Can I re-install last prestashop without starting from scratch (or downgrade to 1.7.5.0 with 1-click upgrade, and then upgrade again to 1.7.5.1) ?

**Comment by khouloudbelguith** [comment]
@guigplt, yes, you can make a downgrade to PS1.7.5.0 then upgrade to 1.7.5.1.
But make sure to have always backup to avoid problems.
Before that, did you use a custom theme? if no, thanks to check if you have overrides, because the method "initLogoAndFavicon" doesn't exist in the FrontController.php class
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/classes/controller/FrontController.php
Thanks!

**Comment by guigplt** [comment]
Ok so I think the upgrade did not work correctly because I have this line on function displayMaintenancePage() in FrontController.php class : 
$this->context->smarty->assign($this->initLogoAndFavicon());

I reinstalled 1-Click Upgrade module but I don't see how to downgrade.

**Comment by khouloudbelguith** [comment]
@guigplt, in the upgrade configuration page, scroll down to the bottom of the page, you can find the ROLLBACK section, select your backup & Click on the "ROLLBACK" button.
Thanks!

**Comment by guigplt** [comment]
I did not make backup because last time I did it, it was too long and it failed.
Isn't it possible to simply reinstall the upgrade ?

**Comment by khouloudbelguith** [comment]
@guigplt, no, your database is just upgraded to the last version PS1.7.5.1, so can not re-install the upgrade.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
