### ISSUE TITLE
appParameters.php are always generated with chmod xxx permissions

### ISSUE THREAD

**Issue by seedsgallery** [PrestaShop/PrestaShop#13050]
**Describe the bug**
var/cache/prod/appParameters.php or var/cache/dev/appParameters.php are always generated with chmod xxx permissions (instead of 644 or 666). Even if i change to 644 or 755 it generate again to xxx.

**To Reproduce**
Advanced Parameters>Performance press "clear cache"
Also this happening if I go to Modules and install or try to configure any of them...

**Screenshots**
I made video from

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0 OPcache
https://prnt.sc/n2ucwy

**Comment by seedsgallery** [comment]
Here is same problem but without exactly manual how to fix ti
https://github.com/PrestaShop/PrestaShop/issues/10998

**Comment by seedsgallery** [comment]
Same problem comes by translation

**Comment by khouloudbelguith** [comment]
Hi @seedsgallery,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/149dNhrvUdtyX50ZXEL8qbPydFbd_2MvR/view
after clearing the cache, the file var/cache/dev/appParameters.php is generated with 644 permissions.
In your case, did you use opcache?
Thanks!

**Comment by seedsgallery** [comment]
Please see also this error message

Warning: require_once(/var/www/web27852346/html/var/cache/dev/appParameters.php): failed to open stream: Permission denied in /var/www/web27852346/html/config/bootstrap.php on line 86

Fatal error: require_once(): Failed opening required '/var/www/web27852346/html/var/cache/dev/appParameters.php' (include_path='/var/www/web27852346/html/vendor/pear/pear_exception:/var/www/web27852346/html/vendor/pear/console_getopt:/var/www/web27852346/html/vendor/pear/pear-core-minimal/src:/var/www/web27852346/html/vendor/pear/archive_tar:.:/opt/php/7.1.26/share/pear') in /var/www/web27852346/html/config/bootstrap.php on line 86

**Comment by khouloudbelguith** [comment]
@seedsgallery,

>Warning: require_once(/var/www/web27852346/html/var/cache/dev/appParameters.php): failed to open >stream: Permission denied in /var/www/web27852346/html/config/bootstrap.php on line 86

This is a permission issue, you need to change the permission of your files.
Also, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by seedsgallery** [comment]
Hello, i know that this is a permission issue. Problem is that prestashop changes this permission all the time to xxx even if I change to 644, 666, 755 prestashop changes again to xxx, after i usem modules settings or clear cache. With 1.6.22 or 1.6.18 i do not have this problems. Can I provide you BO data so you can see allone what i am talking about?

**Comment by seedsgallery** [comment]
Sorry, and FTP data...

**Comment by khouloudbelguith** [comment]
@seedsgallery, to be sure, in my case it is OK, I checked with PS1.7.5.1.
The var/cache/dev/appParameters.php file is generated with 644 permissions.
In your case you use the opcache, did you use this solution ?https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-431596422
Have you tried to edit the opcache config?
Thanks!

**Comment by seedsgallery** [comment]
Hello @khouloudbelguith i did not try https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-431596422 since i do not have manual and do not know where to edit opcache config file. 
Regards

**Comment by khouloudbelguith** [comment]
Hi @seedsgallery,

You should check with your host.

Thanks!

**Comment by seedsgallery** [comment]
Hello @khouloudbelguith switching opcache to of, solved problem.

**Comment by khouloudbelguith** [comment]
Hi @seedsgallery 

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by vencedor** [comment]
maybe opcache config issue mentioned here
[https://github.com/PrestaShop/PrestaShop/issues/10998](url)
