### ISSUE TITLE
Features page - search button id is changed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13055]
**Describe the bug**
In the BO => Attributes & Features Page => Features tab, after editing any values, the id of the search button is changed from `submitFilterButtonfeature` to `id="submitFilterButtonfeature_value"`

**To Reproduce**
1. Go to  BO => Attributes & Features Page => Features tab
2. the id of the search button is  `submitFilterButtonfeature`
3. Click on view button for the Compositions feature 
4. Edit any value
5. Click save => you are redirected to the features page
6.  the id of the search button is changed from `submitFilterButtonfeature` to `id="submitFilterButtonfeature_value"`

With PS1.7.5.1 => OK
**Screenshots**
https://drive.google.com/file/d/1VPENtC40EAhCVPBunYvuocgI7YZVNhxH/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by marionf** [comment]
Could please close it when it will be fixed in E2E test ?

**Comment by marionf** [comment]
Fixed in E2E tests
