### ISSUE TITLE
Migrated page: ids are changed without justifications

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13056]
**Describe the bug**
After the migration of some pages to symfony, some ids are changed without justifications which broken the automatic test.

**Languages page**
1. The search button changed from `id="submitFilterButtonlang"` to **No id**
2. The table language changed from `id="table-lang"` to `id="language_grid_table"`
3. The add new language button changed from `id="page-header-desc-lang-new_language"` to `id="page-header-desc-configuration-add"`

**Add new language page**
1. The input name changed from `id="name"` to `id="language_name"`
2. The iso code input changed from `id="iso_code"` to `id="language_iso_code"`
3. The language code input changed from `id="language_code"` to `id="language_tag_ietf"`
4. The Date format input changed from `id="date_format_lite"` to `id="language_short_date_format"`
5. The Date format (full) input changed from `id="date_format_full"` to `id="language_full_date_format"`
6. The flag input changed from `id="flag-name"` to `id="language_flag_image"`
7. The "No-picture" image input changed from `id="no_picture-name"` to `id="language_no_picture_image"`
8. The Is RTL language option when disbaled changed from `id="is_rtl_off"` to `id="language_is_rtl_0"`
9. The Is RTL language option when enabled changed from `id="is_rtl_on"` to `id="language_is_rtl_1"`
10. The status option when disabled changed from `id="active_off"` to `id="language_is_active_0"`
11. The status option when enabled changed from `id="active_on"` to `id="language_is_active_1"`
12. The save button changed from `id="lang_form_submit_btn"` to **No id**
13. The cancel button changed from `id="lang_form_cancel_btn"` to **No id**

**Theme & Logo page**
1. The div section Generate RTL stylesheet changed from `id="conf_id_PS_GENERATE_RTL"` to **No id**
2. The div section for `ADAPTATION TO RIGHT-TO-LEFT LANGUAGES` changed from `id="configuration_fieldset_RTL"` to **No id**

**Currencies Page**
1. The Search button changed from `id="submitFilterButtoncurrency"` to **No id**
2. The add new currency button changed from `id="page-header-desc-currency-new_currency"` to `id="page-header-desc-configuration-add"`
3. The table currencies changed from `id="table-currency"` to `id="currency_grid_table"`
4. The div section for the Live exchange rates changed from `id="currencyCronjobLiveExchangeRate"` to **No id**

**Add new currency Page**
1. The select currency is changed from `id="iso_code"` to `id="currency_iso_code"`
2. The exchange rate input changed from `id="conversion_rate"` to `id="currency_exchange_rate"`
3. The save button changed from `id="currency_form_submit_btn"` to **No id**
4. The status option changed from `id="currencyStatus"` to tow ids `id="currency_active_1"` and `id="currency_active_0"`
5. The select button changed from `id="currency_form_cancel_btn"` to **No id**

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matks, we should have justifications for these ids.
ping @mbadrani 
Thanks!

**Comment by marionf** [comment]
Could please close it when it will be fixed in E2E test ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I think that there are some ids will be fixed in the E2E test but some other ids should be fixed in the core, for example 
`Add new currency Page => The save button changed from id="currency_form_submit_btn" to No id`.
Thanks!

**Comment by marionf** [comment]
Fixed in E2E tests
