### ISSUE TITLE
The lines inside table > tbody payments in orders tab go out of their coantiner

### ISSUE THREAD

**Issue by cr998** [PrestaShop/PrestaShop#13061]
**Describe the bug**
The lines inside table > tbody payments in orders tab go out of their coantiner

**To Reproduce**
1-Create one order
2-Go to this order
3-Adjust resolution to 1423px of width

**Screenshots**
![bug prestashop](https://user-images.githubusercontent.com/6900835/55032123-7a1e0f80-5010-11e9-880d-fc1161d19d96.PNG)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.15-0ubuntu0.18.04.1

**Comment by khouloudbelguith** [comment]
Hi @cr998,

I did not manage to reproduce the issue with PS:1.7.5.1 and with a resolution to 1423px of width.
I attached a screenshot.
![Capture du 2019-03-27 09-17-06](https://user-images.githubusercontent.com/16067358/55060312-7bcbef80-5071-11e9-8af6-0e74c7bfcf4b.png)
Thanks to chech and feedback.

**Comment by cr998** [comment]
Tryit again whit 900px x 500px

![fix css prestashop](https://user-images.githubusercontent.com/6900835/55083976-b733e180-50a4-11e9-8869-6a850a717c2c.PNG)

**Comment by khouloudbelguith** [comment]
@cr998, I manage to reproduce the issue with PS:1.7.5.1.
This issue is added to our bug roadmap.

Thanks!

**Comment by cr998** [comment]
It looks like the same
https://drive.google.com/file/d/1Te95n-2COLCJmIS4dWXyLeZ11rRnoI8-/view

**Comment by eternoendless** [comment]
This may be fixed through the new design introduced in 1.7.7

Wdyt @matks ?

**Comment by marionf** [comment]
It's fixed on develop branch and will be ok for 1.7.7:

![capture d'écran_2169](https://user-images.githubusercontent.com/13449658/69876015-cd8ede80-12be-11ea-9a7b-bbdf92c10494.png)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

This issue is not fixed in the 1770stablebuild1
![image](https://user-images.githubusercontent.com/16067358/100206716-ff08ad00-2f06-11eb-990c-9ec5cd2bec8f.png)

We should re-open the issue.

Thanks!
