### ISSUE TITLE
Invalid mysql syntax during upgrade to 1.7.6

### ISSUE THREAD

**Issue by rokaszygmantas** [PrestaShop/PrestaShop#13068]
**Describe the bug**
Database upgrade file contains invalid sql syntax, which will cause an error during prestashop upgrade to 1.7.6

**To Reproduce**
It would occur during prestashop upgrade from 1.7.5 to 1.7.6, but we cannot test that easily while 1.7.6 is not released.

**Screenshots**
Problematic code: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.6.0.sql#L21
`IF EXISTS` cannot be used with `DROP INDEX` in mysql.
Error screenshot with mysql 5.7: 
![Screenshot from 2019-03-27 12-31-05](https://user-images.githubusercontent.com/6286794/55069240-3e289000-508c-11e9-91e9-99bc85b4ad19.png)

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed by #13223
