### ISSUE TITLE
Translation of the new form address field

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#13065]
It's not possible to translate a new address form field because the CustomerAddressFormatterCore::getFieldLabel() method is private and therefore cannot be used by overriding the class.
Also in this method (CustomerAddressFormatterCore::getFieldLabel()) there are no hooks to use.
I added the new field updating the 'format' field of the AddressFormat class.
Thanks.

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

Do you mean the "Other" field?

Thanks!

**Comment by Codencode** [comment]
> Do you mean the "Other" field?

Hi @khouloudbelguith, 
No, I'm referring to new fields added to the form.

Thanks.

**Comment by khouloudbelguith** [comment]
@Codencode, you have to create a new class "CustomerAddressFormatter"  who inherits from "CustomerAddressFormatterCore",  then you can add the function "getFormat()" to create the wish field.
For the private method, you can redefine it again.

Thanks to check and feedback.

**Comment by Codencode** [comment]
I created the CustomerAddressFormatter class in "override/classes/form/" with the getFieldLabel() public method but it doesn't work.
If I change the scope of the "getFieldLabel" method of the "CustomerAddressFormatterCore" class from "private" to "protected" it works.
Thanks.

**Comment by khouloudbelguith** [comment]
@Codencode, your problem is solved?

**Comment by Codencode** [comment]
No, because the "getFieldLabel" method of the CustomerAddressFormatterCore class is private and is called by the "getFormat" method of the same class and therefore the "getFieldLabel" method of the CustomerAddressFormatter class is not called.

class "CustomerAddressFormatter" (file override/classes/form/CustomerAddressFormatter.php):

`class CustomerAddressFormatter extends CustomerAddressFormatterCore
{
    public function getFieldLabel($field)
    {
        // Country:name => Country, Country:iso_code => Country,
        // same label regardless of which field is used for mapping.
        $field = explode(':', $field)[0];

        switch ($field) {
            case 'alias':
                return $this->translator->trans('Alias', [], 'Shop.Forms.Labels');
            case 'firstname':
                return $this->translator->trans('First name', [], 'Shop.Forms.Labels');
            case 'lastname':
                return $this->translator->trans('Last name', [], 'Shop.Forms.Labels');
            case 'address1':
                return $this->translator->trans('Address', [], 'Shop.Forms.Labels');
            case 'address2':
                return $this->translator->trans('Address Complement', [], 'Shop.Forms.Labels');
            case 'postcode':
                return $this->translator->trans('Zip/Postal Code', [], 'Shop.Forms.Labels');
            case 'city':
                return $this->translator->trans('City', [], 'Shop.Forms.Labels');
            case 'Country':
                return $this->translator->trans('Country', [], 'Shop.Forms.Labels');
            case 'State':
                return $this->translator->trans('State', [], 'Shop.Forms.Labels');
            case 'phone':
                return $this->translator->trans('Phone', [], 'Shop.Forms.Labels');
            case 'phone_mobile':
                return $this->translator->trans('Mobile phone', [], 'Shop.Forms.Labels');
            case 'company':
                return $this->translator->trans('Company', [], 'Shop.Forms.Labels');
            case 'vat_number':
                return $this->translator->trans('VAT number', [], 'Shop.Forms.Labels');
            case 'dni':
                return $this->translator->trans('Identification number', [], 'Shop.Forms.Labels');
            case 'other':
                return $this->translator->trans('Other', [], 'Shop.Forms.Labels');
            //***** my code
            case 'myField':
                return $this->translator->trans('My field', [], 'Shop.Forms.Labels'); 
            //***************
            default:
                return $field;
        }
    }    
}`

**Comment by khouloudbelguith** [comment]
@Codencode,

Did you add the function "getFormat()" in the class "CustomerAddressFormatter"?

Thanks!

**Comment by Codencode** [comment]
@khouloudbelguith 

If I add the "getFormat" function in the "CustomerAddressFormatter" class I get other errors related to the "country" property because its scope is private.

Thanks.

**Comment by khouloudbelguith** [comment]
@Codencode, all that you use is the private type you have to redeclare it in your new class.

Thanks!

**Comment by Codencode** [comment]
@khouloudbelguith

If I do this, I have other problems.

Thanks!

**Comment by khouloudbelguith** [comment]
@Codencode, send us your created class.

Thanks!

**Comment by Codencode** [comment]
@khouloudbelguith

I attached 4 examples
example 1: no errors but it don't work
example 2: an error occurs concerning country property
example 3: an error occurs (Trying to get property of non-object)
example 4: an error occurs (Catchable Fatal Error: Argument 2 passed to CustomerAddressFormatter::__construct() must be an instance of TranslatorInterface, instance of ...)

Thanks.

[classes.zip](https://github.com/PrestaShop/PrestaShop/files/3019083/classes.zip)

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

In example 4 please add the script "use Symfony\Component\Translation\TranslatorInterface;" before the declaration of "class CustomerAddressFormatter extends CustomerAddressFormatterCore".

Thanks!

**Comment by Codencode** [comment]
@khouloudbelguith, 

It works, but we have to redefine all the methods of the class "CustomerAddressFormatterCore" in the new class "CustomerAddressFormatter"

Thanks!

**Comment by khouloudbelguith** [comment]
@Codencode, I close the ticket, feel free to open a new one when needed.

**Comment by ShaimyWinda** [comment]
Hello, 

I have this problem.
I cant to translate in BO

I changed 
          ```case 'phone_mobile':
                return $this->translator->trans('Mobile Phone (for the carrier)', [], 'Shop.Forms.Labels');```

Can you help me ?


[CustomerAddressFormatter.zip](https://github.com/PrestaShop/PrestaShop/files/3677003/CustomerAddressFormatter.zip)
