### ISSUE TITLE
Unable to access back office Prestashopexception

### ISSUE THREAD

**Issue by Integraelec** [PrestaShop/PrestaShop#13075]
I get a presatashop exception when trying to access the back office, (Error 500) appears when access web-site from the front. Here is the back office exception : 

102.             throw new PrestaShopException('Link to database cannot be established:'.$e->getMessage()); 

What does this mean and how can it be fixed?

**Comment by khouloudbelguith** [comment]
Hi @Integraelec,

When this message appears, it means your database is down. Please contact your hosting provider, which is the only one that can do anything.
Thanks!
I close the ticket, feel free to open a new one when needed.

**Comment by Integraelec** [comment]
OK Thank You
