### ISSUE TITLE
Webservices : how to set the Availability preferences of a product

### ISSUE THREAD

**Issue by jcvoyeux** [PrestaShop/PrestaShop#13071]
I connect my ERP to Prestashop (by using CURL in command line).
My users are not friendly "webuser" so I try to make everything in the ERP.
I didn't see in product's API how to set the availability preference of a product.

Can you add it in PRODUCT webservices ?

**Comment by khouloudbelguith** [comment]
Hi @jcvoyeux,

I used this script.

```
<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php

define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop/');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');

try {

    $webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
    $xml = $webService->get(array('url' => PS_SHOP_PATH.'/api/products?schema=blank'));

    $product = $xml->children()->children();
    $product->price = 99;
    $product->wholesale_price = 89;
    $product->active = '1';
    $product->advanced_stock_management = '1';
    $product->on_sale = 0;
    $product->show_price = 1;
   $product->available_for_order = 1;

    $product->name->language[0][0] = "Produit webservice test test 1751";
    $product->name->language[0][0]['id'] = 1;
    $product->name->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;

    $product->description->language[0][0] = "Description produit webservice";
    $product->description->language[0][0]['id'] = 1;
    $product->description->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;

    $product->description_short->language[0][0] = "Descr. courte";
    $product->description_short->language[0][0]['id'] = 1;
    $product->description_short->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;
    $product->reference = "ref_product_webservice";
    $product->unit_price_ratio = 10.000000;
    $product->depends_on_stock = 0;

    $category_id = 2;
    $product->associations->categories->addChild('category')->addChild('id', $category_id);
    $product->id_category_default = $category_id;

    //
    $opt = array('resource' => 'products');
    $opt['postXml'] = $xml->asXML();
    $xml = $webService->add($opt);
}
catch (PrestaShopWebserviceException $ex) {
    echo "Error:<br>";
    echo  $ex->getMessage();
    exit(1);
}

?>
</body></html>
```

Thanks to check & feedback.

**Comment by jcvoyeux** [comment]
Hello,

Thank you for your answer.
Witch value set the Availability preferences ?

available_for_order set if it can be bought
active set the visibility
on_sale display "Promo"

**Comment by khouloudbelguith** [comment]
@jcvoyeux, the available_for_order.

**Comment by jcvoyeux** [comment]
@khouloudbelguith I think we don't speak about the same information.
available_for_order modify "Available for order" in the "options" of products.
Me I want to change "Availability preferences" in the "Quantities" of products.
Behavior when out of stock
( ) Deny orders
( ) Allow orders
( ) Use default behavior (Allow orders)

**Comment by jcvoyeux** [comment]
I need this option because some products stay available even if they are out of stock but other not and could not be bought any more. I must set this field in each item.

**Comment by khouloudbelguith** [comment]
@jcvoyeux, these options do not exist.
@PrestaShop/prestashop-core-developers , what do you think?

**Comment by PierreRambaud** [comment]
The field used for this is `out_of_stock` as you can see here:https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L272 
So you need to use this endpoint: https://devdocs.prestashop.com/1.7/webservice/resources/stock_availables/

**Comment by hibatallahAouadni** [comment]
Hello @jcvoyeux ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
