### ISSUE TITLE
Webservices : modify categories

### ISSUE THREAD

**Issue by jcvoyeux** [PrestaShop/PrestaShop#13070]
When we modify categories by webservice. The displayed order is lost.

To solve the problem, the order should be given when we call the categories, (we should not modified it) then applyed.

**Comment by khouloudbelguith** [comment]
@PrestaShop/prestashop-core-developers, what do you think?

**Comment by jcvoyeux** [comment]
Here what I did : 
I sent 10 categories with my ERP (and webservices). My customer asked me to change the order. I did it directly in prestashop. he changed the name of a category in the ERP. The change has been sent to prestashop. The order has been lost.
JC

**Comment by PierreRambaud** [comment]
As you can see in this documentation, the position is a field in the API: https://github.com/PrestaShop/docs/tree/master/src/content/1.7/webservice/resources
So if you update it via API you must provide the position value, otherwise, it's lost.

**Comment by hibatallahAouadni** [comment]
Hello @jcvoyeux ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
