### ISSUE TITLE
FIx lang

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#13082]
Hello. page: /index.php?controller=order-confirmation
Lang: RU

Fix:
> Ваш заказ **оплачен**

Replace:
> Ваш заказ **оформлен**

![Screenshot_1](https://user-images.githubusercontent.com/6318282/55123150-35e45980-514d-11e9-87ae-9f63f67d48f9.jpg)

**Comment by TemKaSD** [comment]
**order confirmation** in breadcrumb translate: Подтверждение заказа

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Thanks to adding a short description of your issue and add steps to reproduce it in a new comment.

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
