### ISSUE TITLE
Error 500 suite cache vidé

### ISSUE THREAD

**Issue by JessicaCr** [PrestaShop/PrestaShop#13086]
**Describe the bug**
Bonjour,
après avoir vidé le cache de prestashop, la page error 500 est apparue. Et impossible d'acceder au back office, toujours cette page affiché
Après avoir discuté sur le forum de prestashop, apparemment c'est une "fausse" erreur d'après les fichiers ftp.log et error.log

**To Reproduce**
1. Go to https://latelierteinture.fr/admin7066

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @JessicaCr,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Eolia** [comment]
More info here: https://www.prestashop.com/forums/topic/960396-impossible-de-se-connecter-au-backoffice-suite-cache-vidé

**Comment by JessicaCr** [comment]
host : OVH
server setup and configuration : Prestashop 1.7.5.1 ?
Informations sur votre serveur Linux #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.14
debug mode report : 
PHP error logs
apache error log
javascript console log
screenshots

**Comment by JessicaCr** [comment]
![image](https://user-images.githubusercontent.com/49023767/55154350-df7b1900-5154-11e9-9f4a-f1aef44a3414.png)

**Comment by JessicaCr** [comment]
![image](https://user-images.githubusercontent.com/49023767/55154394-033e5f00-5155-11e9-93fc-37cac498ec7a.png)

**Comment by JessicaCr** [comment]
![image](https://user-images.githubusercontent.com/49023767/55154496-44cf0a00-5155-11e9-906d-54be2ab4103a.png)

**Comment by JessicaCr** [comment]
Quand je vide le cache en mode debug
![image](https://user-images.githubusercontent.com/49023767/55154603-81026a80-5155-11e9-98f4-daf6ddf710c2.png)

**Comment by khouloudbelguith** [comment]
@JessicaCr, is your problem solved? because when I go to your BackOffice I do not know 500 error.
![13086](https://user-images.githubusercontent.com/16067358/55163793-b9607380-516a-11e9-9e67-c5802b894a82.png)

Thanks!

**Comment by JessicaCr** [comment]
Bonjour

> @JessicaCr, is your problem solved? because when I go to your BackOffice I do not know 500 error.
> ![13086](https://user-images.githubusercontent.com/16067358/55163793-b9607380-516a-11e9-9e67-c5802b894a82.png)
> 
> Thanks!

J'étais en mode debug, c'est pour ça

**Comment by Cr2Agency** [comment]
Bonjour, avez vous trouvé une solution ? 
J'ai exactement le même problème suite à une migration (de local vers OVH)

**Comment by JessicaCr** [comment]
Non...

**Comment by Cr2Agency** [comment]
C'est bon, j'ai trouvé pour ma part, j'ai supprimer tous les fichiers qui se trouve dans le dossier /var/cache.
J'avais 2 dossiers : dev et prod
J'ai supprimer les 2 dossiers (en faisant quand même 1 sauvegarde avant) vider le cache de mon navigateur et ça fonctionne.

**Comment by khouloudbelguith** [comment]
Hi @JessicaCr,

Could you please try to clear cache from your project and your navigator and feedback.

Thanks!

**Comment by JessicaCr** [comment]
> C'est bon, j'ai trouvé pour ma part, j'ai supprimer tous les fichiers qui se trouve dans le dossier /var/cache.
> J'avais 2 dossiers : dev et prod
> J'ai supprimer les 2 dossiers (en faisant quand même 1 sauvegarde avant) vider le cache de mon navigateur et ça fonctionne.

ça a marché ! Merci beaucoup!

**Comment by khouloudbelguith** [comment]
@JessicaCr, I close the ticket, feel free to open a new one when needed.
