### ISSUE TITLE
PrestaShop inception in new order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13085]
If I create a new order, click on add a new customer and click on Cancel, I still have the PrestaShop's inception

![capture d'écran_1232](https://user-images.githubusercontent.com/13449658/55016422-00c1f500-4fef-11e9-88cd-9a84e334099e.png)

_Originally posted by @marionf in https://github.com/PrestaShop/PrestaShop/pull/13043#issuecomment-476742903_

**Comment by matks** [comment]
@marionf I added a commit in order to fix this in https://github.com/PrestaShop/PrestaShop/pull/13043 🤔strange the PR should have fixed that

**Comment by marionf** [comment]
Oh yes, my bad
