### ISSUE TITLE
Remove the link in the last item in breadcrumb for SEO

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#13083]
Hello. For SEO, it is useful when the page does not link to itself.

![Screenshot_1](https://user-images.githubusercontent.com/6318282/55142120-98f2e200-5187-11e9-8c8f-8e96cad9433d.jpg)

Need remove link from last item

**Comment by khouloudbelguith** [comment]
@colinegin, @marionf, what do you think?

**Comment by colinegin** [comment]
Thanks for your feedback and sorry for the delay.
We have reviewed your idea with our SEO expert, he confirmed your idea is a good practice for SEO.
I add it in our roadmap for 1.7.7 !

Thanks again and have a nice day,

Coline
