### ISSUE TITLE
Beloved "An error occurred while processing your request"

### ISSUE THREAD

**Issue by imartin1983** [PrestaShop/PrestaShop#13089]
**Describe the bug**
Hi,
I have this error message "An error occurred while processing your request" below the add to cart button, when trying to increase quantity on the product page, or when I add to cart and click "continue shopping" button. It's a simple product, no parameters.

PS 1.7.5.1, PHP 7.2.16, MySQL 5.6.39, Apache, PHP limit 90 Mb.

It's a fresh install with a template and URL rewrite module (works OK). I have a test site installed on a subdomain and that works with no issues. So I don't know if it's a server, template, module or PS 1.7.5 issue.

Btw, I don't know what nginxy is. I know that Ginxy is the cat of Roberto De Niro in that movie, where he plays a CIA agent...but beyond that. No. I also don't host my site on a private server or on servers in my bedroom. 

Appreciate any ideas.
Cheers,
Martin

**Comment by khouloudbelguith** [comment]
Hi @imartin1983,

Is it the same issue reported here: #10178?

Thanks!

**Comment by imartin1983** [comment]
Sorry but there is no clear explanation of the solution. Apart from guys posting ideas and some test configurations and code. It seems like a common issue. It happens on products without variation. Looks like some tables are missing or something...

**Comment by khouloudbelguith** [comment]
Hi @imartin1983,

Have you tried to check this fix: #9390?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @imartin1983,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
