### ISSUE TITLE
Customer page migration : ids are changed without justifications

### ISSUE THREAD

**Issue by YosraAk** [PrestaShop/PrestaShop#13091]
**Describe the bug**
Some ids are changed after the migration of "Customers" pages to Symfony. These changements broke some automatic tests.

**customers page**

- Add new customer button: changed from id="page-header-desc-customer-new_customer" to id="page-header-desc-configuration-add"
- Customer form: changed from id="form-customer" to id="customer_filter_form"

**Add new customer page**

-  Social title "Mr." radio button: changed from id="gender_1" to id="customer_gender_id_0"

- "First name" input:  changed from id="firstname" to id="customer_firstname"

- "Last name" input: changed from id="lastname" to id="customer_lastname"

- "Email" input: changed from id="email" to id="customer_email"

- "Password" input: changed from id="passwd" to id="customer_passwd"

- "Save" button: changed from id="customer_form_submit_btn" to **no id**

Thanks.

**Comment by YosraAk** [comment]
ping @mbadrani.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matks, we should have justifications for these ids.

**Comment by marionf** [comment]
Could please close it when it will be fixed in E2E test ?

**Comment by marionf** [comment]
Fixed in E2E tests
