### ISSUE TITLE
No formatted Invoice number before check or wire payment

### ISSUE THREAD

**Issue by matlopes** [PrestaShop/PrestaShop#13099]
When an order is placed, no formatted invoice number appear on the invoice pdf sent by mail to customer.
Correct formatted number appears only once payment is validated (in the pdf sent by mail), or, after a while, through the order listing pages (both public and backend), with the "generate" or "download invoice pdf" link.
NB: the shop i'm talking about only has check or wire transfer payment.

Steps to reproduce (for example, with the order number 45 and with prefix set as PREFIX):

As a customer on public page
- Place order and choose check or wire transfer as payment.
- You get an email with a PREFIX-000045.pdf file without any invoice number on it.

As admin:
- create new order, set awaiting check or wire transfer as state.
- customer get an email with a PREFIX-000045.pdf file without any invoice number on it.
- **erratically** : on the order listing page of the backoffice, if you click the PDF icon of the order, you get the same PREFIX-000045.pdf file without invoice number **OR** you get the proper PREFIX-2019000045.pdf (with the year) and the correctly formatted invoice number appearing on it : PREIX-2019/000045

The issue wouldn't appear that much of a problem if it weren't that some customers (rightfully) demand that the initial invoice they get has a proper invoice number to send payment...

Prestashop version : 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @matlopes,

Could you please add screenshots or a video record to reproduce the issue.

Thanks!

**Comment by matlopes** [comment]
I found the culprit : the editorder addon (https://addons.prestashop.com/fr/gestion-commandes/23760-management-des-commandes-edition-des-commandes.html).

When deactivated, trouble disappears...

I move the issue to the addon developper.

**Comment by matlopes** [comment]
Bug was solved by the module developper. He should issue a module update soon.
