### ISSUE TITLE
How to insert flag SOLD OUT on products

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#13096]
Hello, 
hope you can help me. 
I would like to insert the flag "sold out" when is out of stock. 

Do you know how to do it?

Kind regards

**Comment by kpodemski** [comment]
Hey,

from 1.7.6 you would be able to use custom hook for this:
https://github.com/PrestaShop/PrestaShop/pull/11614

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

If your PrestaShop version is less than 1.7.6,  you have to add this script
" Hook :: exec ('actionProductFlagsModifier', array (
            'flags' => & $ flags,
            'product' => $ this-> product,
        )); " in the file "src / Adapter / Presenter / Product / ProductLazyArray.php" as stated in this commit " https://github.com/PrestaShop/PrestaShop/pull/11614/commits/0575283e48ca76a2a4f40a3fb9d85be6a9eaf6fc " before installing the module.

**Comment by morghy1992** [comment]
@khouloudbelguith thank you for the reply.

I added the script into the file but I got errors. here the images 

<img width="1115" alt="Schermata 2019-03-29 alle 23 46 37" src="https://user-images.githubusercontent.com/47249256/55266382-eef58180-527c-11e9-95cc-70b7e8d18f42.png">
<img width="1420" alt="Schermata 2019-03-29 alle 23 46 58" src="https://user-images.githubusercontent.com/47249256/55266390-f7e65300-527c-11e9-87c6-dfb8705f9a52.png">

**Comment by kpodemski** [comment]
@morghy1992 you need to contact some PrestaShop developer to help you out, ask on the forum or something, it's not a good place for this, sorry

**Comment by morghy1992** [comment]
I added this code into product.tpl 

{block name='product_flags'}
                <ul class="product-flags">
                  {foreach from=$product.flags item=flag}
                    <li class="product-flag {$flag.type}">{$flag.label}</li>
                  {/foreach}
                </ul>
                {if $product.show_quantities <= "0"}
                     <li class="product-flag {$flag.type}">
                 {l s='Sold Out' d='Shop.Theme.Catalog'}</li>
                   {/if}
              {/block}

But it works only with one product. The others is not working :(

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by jouino16** [comment]
Pardon me if I'm posting on a closed issue, my question is related to the title of this issue which is: what is the effective way/check to determine a sold out item? I tired the check: product equals to zero, but it does not work effectively: actually when a first user adds an item in his cart, the second user in another session sees the item as sold out.

Could you please advise me with the effective condition? Thank you in advance.

And sorry for posting my question here, please point me to a related issue if any. Thank you.

**Comment by warezmail1981** [comment]
im using  prestashop 1.7.6
go to **ProductLazyArray.php**  on function **getFlags** and append this 

 if ($this->product['quantity'] == 0) {
            $flags['quantities'] = array(
                'type' => 'unavailable',//
                'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
            );
        }

this is effect.
![immagine](https://user-images.githubusercontent.com/62803203/100659825-739d7a80-3351-11eb-8851-114c647e78ce.png)

**Comment by yiohan** [comment]
Hello everyone i input this code on ProductLazyArray.php on function getFlags
 if ($this->product['quantity'] == 0) {
$flags['quantities'] = array(
'type' => 'unavailable',//
'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
);
}
but i have a problem with product with compination because some product has different quantities anyone solved this?

**Comment by vhrist** [comment]
> 
> 
> im using prestashop 1.7.6
> go to **ProductLazyArray.php** on function **getFlags** and append this
> 
> if ($this->product['quantity'] == 0) {
> $flags['quantities'] = array(
> 'type' => 'unavailable',//
> 'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
> );
> }
> 
> this is effect.
> ![immagine](https://user-images.githubusercontent.com/62803203/100659825-739d7a80-3351-11eb-8851-114c647e78ce.png)

Hi, thanks for solution
It's worked on 1.7.6.5, but I didn't see expresion "Sold Out" in translations.

Please for advice how to translate it?

Regards

**Comment by ilisiaraul** [comment]
Works like a charm in PS 1.7.7.8 


> > im using prestashop 1.7.6
> > go to **ProductLazyArray.php** on function **getFlags** and append this
> > if ($this->product['quantity'] == 0) {
> > $flags['quantities'] = array(
> > 'type' => 'unavailable',//
> > 'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
> > );
> > }
> > this is effect.
> > ![immagine](https://user-images.githubusercontent.com/62803203/100659825-739d7a80-3351-11eb-8851-114c647e78ce.png)
> 
> Hi, thanks for solution
> It's worked on 1.7.6.5, but I didn't see expresion "Sold Out" in translations.
> 
> Please for advice how to translate it?
> 
> Regards

You just need to change Sold Out to whatever you want 
EX: 

if ($this->product['quantity'] == 0) {
$flags['quantities'] = array(
'type' => 'unavailable',//
'label' => $this->translator->trans('Sold Epuizat', array(), 'Shop.Theme.Catalog'),
);
}

**Comment by vhrist** [comment]
> 
> 
> Works like a charm in PS 1.7.7.8
> 
> > > im using prestashop 1.7.6
> > > go to **ProductLazyArray.php** on function **getFlags** and append this
> > > if ($this->product['quantity'] == 0) {
> > > $flags['quantities'] = array(
> > > 'type' => 'unavailable',//
> > > 'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
> > > );
> > > }
> > > this is effect.
> > > ![immagine](https://user-images.githubusercontent.com/62803203/100659825-739d7a80-3351-11eb-8851-114c647e78ce.png)
> > 
> > 
> > Hi, thanks for solution
> > It's worked on 1.7.6.5, but I didn't see expresion "Sold Out" in translations.
> > Please for advice how to translate it?
> > Regards
> 
> You just need to change Sold Out to whatever you want
> EX:
> 
> if ($this->product['quantity'] == 0) {
> $flags['quantities'] = array(
> 'type' => 'unavailable',//
> 'label' => $this->translator->trans('Sold Epuizat', array(), 'Shop.Theme.Catalog'),
> );
> }

The problem is that i don't see this expression in backoffice and I can't translated in my local language

Regards

**Comment by Mauro207** [comment]
> im using prestashop 1.7.6 go to **ProductLazyArray.php** on function **getFlags** and append this
> 
> if ($this->product['quantity'] == 0) { $flags['quantities'] = array( 'type' => 'unavailable',// 'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'), ); }
> 
> this is effect. ![immagine](https://user-images.githubusercontent.com/62803203/100659825-739d7a80-3351-11eb-8851-114c647e78ce.png)

Hi, sorry, what would be the path to get to ProductLazyArray.php? src /adatper /presenter /product?

**Comment by EricioMuray** [comment]
> Hello everyone i input this code on ProductLazyArray.php on function getFlags if ($this->product['quantity'] == 0) { $flags['quantities'] = array( 'type' => 'unavailable',// 'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'), ); } but i have a problem with product with compination because some product has different quantities anyone solved this?

Hi @yiohan,
To make it work on products with combinations, just replace **'quantity'** by **'quantity_all_versions'**.

if ($this->product['quantity_all_versions'] == 0) {
$flags['quantities'] = array(
'type' => 'unavailable',//
'label' => $this->translator->trans('Sold out', array(), 'Shop.Theme.Catalog'),
);
}
