### ISSUE TITLE
 Prestashop Category Tree Block not showing all categories

### ISSUE THREAD

**Issue by skipy** [PrestaShop/PrestaShop#13098]
Hi there!

So I run a prestahop 1.7 website and I have the category tree block in the left part of the website. I've set up to show the Home category with 0 maximum depth so all my categories will be shown.

But it displays only 7 categories even if in the Home category there are 18 all of them being activated. Also, only 4 subcategories are shown for each main category.

Does anyone encountered this problem? Or is it just me doing something wrong?﻿

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @skipy,

I did not manage to reproduce the issue with the PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1BO1c5HI1p-8qxfoBFVWENxlrZcKxS0dI/view
Are you using the template by default of Prestashop?

Thanks!

**Comment by skipy** [comment]
Hi there!

[https://drive.google.com/open?id=18eUu9qyXOABEBhP7stvYGsMs9joCak4k](https://drive.google.com/open?id=18eUu9qyXOABEBhP7stvYGsMs9joCak4k)

I am using a different theme than default, but it doesn't matter, the behaviour still persists. I made this recording with the default theme.
My version is 1.7.0.

**Comment by khouloudbelguith** [comment]
@skipy, what is the exact version of the module ps_categorytree?

**Comment by skipy** [comment]
@khouloudbelguith v2.0.0
Thanks!

**Comment by khouloudbelguith** [comment]
@skipy, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by skipy** [comment]
Hey again, @khouloudbelguith! And thank you for your time and patience.
First of all I've been wrong with the PS version. It is 1.7.3.0 and I've saw that after I've enabled debug mode.
So, I have a VPS with Centos 7, Apache Webserver with PHP 7.0.10
Console: [http://i64.tinypic.com/27zxb8l.jpg](http://i64.tinypic.com/27zxb8l.jpg)
Error_log: empty. The site runs smoothly except this part with the category tree. And I've broken a php file to see if the error_log works and it did.

PS Debug
[http://txt.do/15wdw ](http://txt.do/15wdw ) Info&Errors
[https://textuploader.com/15wdy](https://textuploader.com/15wdy) - Deprecations
[https://textuploader.com/15wd3](https://textuploader.com/15wd3) - Debug
[https://textuploader.com/15wde](https://textuploader.com/15wde) - Debug part  2.

**Comment by skipy** [comment]
Found out that another module that I use, a vertical menu module, displays in the backend the same categories that the category tree module displays on the frontend.

**Comment by khouloudbelguith** [comment]
Hi @skipy,

Could you please try to deactivate the smart cache and check.

Thanks!

**Comment by skipy** [comment]
Hi @khouloudbelguith !
In the backoffice all cache is deactivated.

Thank you and have a wonderful week!

**Comment by skipy** [comment]
Strange thing though. I was searching in the forums for cache updating and searched with phpmyadmin for the term "cache" in the database and the only results were:

PS_SMARTY_CACHE (with value 0)
PS_SMARTY_CACHE
SC_SETTINGS

and all of these in the configuration table.

**Comment by khouloudbelguith** [comment]
@skipy, thanks to disable the following modules:novblocktags, novnivoslide, novmegamenu, novverticalmenu, smartblog and check with the default theme.

**Comment by skipy** [comment]
@khouloudbelguith I've already did that last week and did it again and nothing changed.

**Comment by khouloudbelguith** [comment]
@skipy,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

**Comment by oscarcuenca** [comment]
HI @skipy.
Did you solve this issue? I have exactlly same problem. Only showing 7 subcategories. But i can not find any information about how to solve it,
Thanks in advance.
