### ISSUE TITLE
Problem with Automatic Emails

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#13102]
Hi,

I deactivated all submissions in the settings as you can see in the attachment. However, when I change the status of the orders, it sends the same e-mail to the customers to tell me how to change the order. I do not want this to send out automatic emails.

![enc](https://user-images.githubusercontent.com/49063138/55226674-75727a80-520d-11e9-9bdf-b23a6d325ef6.PNG)

Someone can help me?

**Comment by khouloudbelguith** [comment]
Hi @JorgeNogueiraLFMPro,

I did not manage to reproduce the issue with PS:1.7.5.1.
What is the exact version of PS did you used?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
My version is 1.7.5.0

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, with PS1.7.4.4 and PS:1.7.50 => it's OK.
@marionf, could you please try to reproduce it.

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I need the store to stop sending automatic emails to my customers. Just this, nothing more.

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information, emails are well not send when they are disabled in Shop parameters > Orders > orders statuses

Best regards.
