### ISSUE TITLE
Le prix de la déclinaison par défaut s’affiche pour toutes les déclinaisons 

### ISSUE THREAD

**Issue by HECOSFAIR** [PrestaShop/PrestaShop#13100]
Bonjour,

Je fais suite à mon cas précédent et merci pour votre réponse rapide.
J’ai bien recréé les déclinaisons comme vous me l’avez indiqué. Dorénavant, les clients peuvent sélectionner les déclinaisons (qui s’affichent sur le site) et les ajouter à leur panier.
Cependant, c’est uniquement le prix de la déclinaison par défaut qui s’affiche pour toutes les déclinaisons. Mais quand on les ajoute au panier, c’est bien le prix qui correspond à la déclinaison qui est pris en compte.
Je vous joins un lien et des captures d’écran : 
https://hecosfair.com/accueil/136-234-pignon-de-cedre-bio-de-siberie-3770010599241.html#/509-poids-70g

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 1.7

Bien cordialement 
![1BB0CC00-40D2-43FD-B5F0-FFF711B02569](https://user-images.githubusercontent.com/48907418/55221511-ed3ea600-5209-11e9-8777-7ad150bbad54.png)
![D2B281EF-6D5A-4090-BD59-19BD26BBC917](https://user-images.githubusercontent.com/48907418/55221512-ed3ea600-5209-11e9-846e-2ad0b7a4e03b.png)
![2D06EB62-BFF6-4CC8-9D3F-ACAEE7E961A5](https://user-images.githubusercontent.com/48907418/55221513-ed3ea600-5209-11e9-8224-d0362439ce3d.jpeg)
![EDD251BB-F87C-4DB5-9B46-C31B38E26F9E](https://user-images.githubusercontent.com/48907418/55221514-ed3ea600-5209-11e9-91fa-01a932fdca81.png)

**Comment by khouloudbelguith** [comment]
Hi @HECOSFAIR,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1cjys9BJjUAbJcqi1liMkqrfwqaQMJqHQ/view

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @HECOSFAIR,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
