### ISSUE TITLE
Simplify TranslatableType when constrains are used on parent and options level

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#13107]
**Is your feature request related to a problem? Please describe.**
This issue comes from this discussion
https://github.com/PrestaShop/PrestaShop/pull/12995#discussion_r270376371

When we use a `TranslatableType` with multiple constraints (from parent level and in options) we need to set `error_bubbling` to false for the errors to be displayed correctly.

**Describe the solution you'd like**
This is not something you can guess so we should find a way to ease the use of this form type.
Maybe it could set this option itself:

```php
if (!isset($options['error_bubbling']) && !empty($options['constraints']) && !empty($options['options']['constraints'])) {
    $options['error_bubbling'] = false;
}
```

**Describe alternatives you've considered**
Think about alternatives that could make it easier, or try to make it work whether `error_bubbling` is set to false or not.

**Comment by eternoendless** [comment]
Closed via #13158
