### ISSUE TITLE
Is there a version of PSWebServiceLibrary.php that works with PHP v 7.0?

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#13109]
Hello everybody,
(_I hope I'm at the right place to report my issue. In contrary case, please excuse me._)
I have site A that runs on Prestashop 1.6.1.5 and to retrieve data on another site (site B) which also runs under Prestashop 1.6.1.5, I use a module "homemade" (by my predecessor) which uses, among other things, PSWebServiceLibrary.php.
When I change version of PHP (from version 5.6 to version 7.0) on site B and I want to use the module on site A, I have a number of errors including PSWebServiceLibrary.php
I thus have the following error message:

> Fatal error: Uncaught exception 'PrestaShopWebserviceException' with message
> 'This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error.' in www.wikao.fr/PSWebServiceLibrary.php:95
> Stack trace:
> 
> 1. www.wikao.fr/PSWebServiceLibrary.php(297): PrestaShopWebservice->checkStatusCode(500)
> 2. www.wikao.fr/modules/orderlist/classes/orderArrayCreator.class.php(145): PrestaShopWebservice->get(Array)
> 3. www.wikao.fr/modules/orderlist/controllers/admin/AdminOrderList.php(125): orderArrayCreator->createDistantOrderArray()
> 4. www.wikao.fr/classes/controller/Controller.php(178): AdminOrderListController->postProcess()
> 5. www.wikao.fr/override/classes/Dispatcher.php(335): ControllerCore->run()
> 6. www.wikao.fr/override/classes/Dispatcher.php(107): Dispatcher->dispatch_16()
> 7. www.wikao.fr/admin_wikao/index.php(58): Dispatcher->dispatch()
> 8. {main} thrown in www.wikao.fr/PSWebServiceLibrary.php on line 95

If I come back to version 5.6, I have no problem, the module works normally.
So this is a problem related to version 7 of PHP.
Is there a version of PSWebServiceLibrary.php that works with PHP v 7.0?
In advance thank you for your help because I am a beginner in PHP

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Thanks for your report.
As you can see here: the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, that’s why I close it.

Thanks!
