### ISSUE TITLE
Recommended modules button isn't working when MBO is uninstalled

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13110]
**Describe the bug**
Recommanded modules button isn't working when MBO is uninstalled

**To Reproduce**
1. Uninstall MBO module
2. Click on Orders > orders > recommanded modules
3. See error

**Screenshots**
![capture d'écran_1264](https://user-images.githubusercontent.com/13449658/55241632-c13c1880-523b-11e9-9413-6199ab56a991.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by Matt75** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/18554

**Comment by florine2623** [comment]
Does not exist anymore on 9.0.x
