### ISSUE TITLE
PrestaShop AddOn Store could issue some signed "AddOn download/purchase receipt"

### ISSUE THREAD

**Issue by molearnik** [PrestaShop/PrestaShop#13112]
**Problem**
AddOns publishers might need a mechanism that could prove that installed AddOn was really purchased/downloaded from the official PrestaShop AddOn Store AND for the particular webstore or merchant.
The similar need was discussed in [PrestaShop forum](https://www.prestashop.com/forums/topic/447662-prestashop-addons-api):
_Is there a feature (or API) from Prestashop Addons where publisher can check if one is valid purchase/buyer ?_

**Why would this be useful?**
It would be useful for hassle-free and rather secure AddOn registration with external AddOn APIs.
You know that some AddOns might depend on API that AddOn publisher's created to support AddOn functionality. 
If installed AddOn could show an official and trusted PrestaShop purchase/download"receipt" to the PrestaShop specific API "handshake" end-point (AddOns publisher could create it easily) then this handshake end-point could generate unique API secrets for the installed PrestaShop AddOn easier. API handshake end-point would just validate the receipt and decide to trust the caller as real WebStore / AddOn as no one else should have that receipt.

Google Play provides some [Developer API](https://developers.google.com/android-publisher/api-ref/purchases/products/get) for similar purpose but in PrestaShop case I think the problem might have simpler solution that would not require PrestaShop to implement and host GooglePlay-like API for publishers. The simpler solution could be inspired by "OpenId" protocol and JWT tokens.

**Describe the solution you'd like**
User story:
As AddOn Publisher, I'd want to use signed "AddOn download/purchase receipts" that "PrestaShop AddOn Store" will provide to Merchants who purchased/downladed my AddOns.

In more detail:
1. PrestaShop AddOn Store needs to be able to issue properly signed "AddOn purchase / download" receipts.  
2. Merchant (AddOn Store user) need to be able to get the mentioned receipt into her/his WebStore configuration (or new receipts table). This should be automatic with "One-Click" installations from the WebStore Back Office in future (and one time action upon PrestaShop webstore upgrade).
3. Installed AddOns could then retrieve the corresponding receipt from local WebStore (configuration) and use the receipt for a handshake with external APIs authentication end-points.
4. External API handshake end-point could validate the receipt issuer, receipt signature and the other claims in the receipt; and finally generate new AddOns API secrets for the AddOn.

Note, the AddOn would not need to use any new API provided by PrestaShop AddOns Store.

The download/purchase receipts could leverage JSON Web Tokens (an open, industry standard RFC 7519) that are used in e.g. OpenID protocol. That means the receipt could carry some useful claims in the payload of the JWT token and "PrestaShop AddOn Store" would append proper signature into the token (JWT header+payload hash encrypted with private key of PrestaShop AddOn store). So, the mentioned external API handshake end-point could validate signature and issuer (by comparing descrypted and calculated hashes) i.e. by resolving receipt issuer e.g. "https://addons.prestashop.com" on a public key e.g. https://addons.prestashop.com/${keyid}.cer, decrypting receipt signature i.e. getting hash as it was calculated by the issuer, calculating new payload hash using the specified hash algorithm, and finally by comparing these two hashes.

JWT Token could look like:
header:
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "N-lC0n-9DALqwhuHYnHQ63GeCXc" // key id
}
payload (Claims in the JWT token / receipt):
{
  iss: "https://addons.prestashop.com", //issuer
  sub: "webstore url", // subject that downloaded addon
  aud: "addon publisher", // audience
  exp: '', // no expiration would do the job.
  iat: 'download/purchase date/time', 
  addon: 'some addon name' // non standard claim reports the plugin that this receipt was generated for
}
signature:
RSASHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/prestashop-core-developers, what do you think?

**Comment by PierreRambaud** [comment]
It seems this issue is related to addons.prestashop.com, we don't manage this.
Sorry I'm closing this issue. Feel free to reopen if you think it's still relevant.
