### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#13114]
Hello
I can't get the product in search bar
CPU | Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (8 core(s))
-- | --
Version | Plesk Onyx v17.8.11_build1708180301.19 os_CentOS 7
OS | CentOS Linux 7.6.1810 (Core)

https://drive.google.com/file/d/1tW-bUunBs5vEq0VzZajVxVwXL_2IT0v3/view

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

You can try to re-build the entire index. Go to Back-office => Configure => Shop Parameters => Search and click on "Re-build the entire index".

Thanks to check and feedback.
