### ISSUE TITLE
Cannot add products to cart

### ISSUE THREAD

**Issue by MarcHe124** [PrestaShop/PrestaShop#13121]
**Describe the bug**
Cannot add products to cart, will get fetal error.

**To Reproduce**
1. Go to Homepage http://longboxiang.ca/supermarket
2. Click on some product
3. Open dev tool, click add to cart
4. See the errror in network for cart request

**Screenshots**
```
[PrestaShopException]
Fatal Error
at line 1109 in file classes/Tools.php

1104.                 ->getTranslator()
1105.                 ->trans('Fatal error', [], 'Admin.Notifications.Error');
1106.         }
1107. 
1108.         if (_PS_MODE_DEV_) {
1109.             throw new PrestaShopException($errorMessage);
1110.         }
1111. 
1112.         return $errorMessage;
1113.     }
1114. 
ToolsCore::displayError - [line 394 - classes/Cart.php]
CartCore::getTaxesAverageUsed - [line 481 - src/Adapter/Presenter/Cart/CartPresenter.php] - [1 Arguments]
PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter->getTemplateVarVouchers - [line 437 - src/Adapter/Presenter/Cart/CartPresenter.php] - [1 Arguments]
PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter->present - [line 102 - controllers/front/CartController.php] - [2 Arguments]
CartControllerCore->initContent - [line 281 - classes/controller/Controller.php]
ControllerCore->run - [line 511 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]
```
![2019-03-29_194150](https://user-images.githubusercontent.com/12852794/55284434-6d106180-532b-11e9-8ef9-6c9bca9a7bc6.jpg)

**Additionnal information**
Website Url: http://longboxiang.ca/supermarket
PrestaShop version: 1.7.5
PHP version: 5.6 
My email: arthurma124@gmail.com if you need ftp account.

**Comment by MarcHe124** [comment]
Resolved, it is a database issue

**Comment by bikefactorycl** [comment]
> Resolved, it is a database issue

Hello,

I have the same problem with exactly the same template Zone Supermarket, use PS 1.7.4.2, how did you solve the problem? Thank you very much.

**Comment by masztal18** [comment]
Hello,

I have the same problem, how did you solve the problem? Thank you very much.

**Comment by coolternet** [comment]
i need tips..
