### ISSUE TITLE
Change checkout behavior

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13126]
**Describe the bug**
#12456 was not done completely
Here is what remains to be done:

The main difference vs current behaviour is that the user will always have to click on "Continue" to go from Step X to Step X+1, no matter if :

- he/she goes in the different steps for the first time
- he/she went to the step X and decided to go back to X-1 or X-2 to check or modify the information stored.

This means that :

- The next steps after the current step are no longer clickable (only Continue button allows to go to the next step)
- There should be a "Continue" button in the Personal information step (in case the logged in user goes back to the 1st step)
- Green checks and "Modify" CTAs should be removed in the steps following the user current one.

**Comment by marionf** [comment]
The main issue is if you try to change your address without clicking on Continue button, it's not saved and y
and you're not delivered where you wanted

**Comment by marionf** [comment]
@colinegin FYI

**Comment by kpodemski** [comment]
@marionf 

> The main issue is if you try to change your address without clicking on Continue button, it's not saved and y and you're not delivered where you wanted

this is so true, we have this feedback a lot of times with a new checkout page
