### ISSUE TITLE
Leo panel tool

### ISSUE THREAD

**Issue by Domnina** [PrestaShop/PrestaShop#13129]
Hi, 
I wish to delete the **leo panel tool** from my website and reallly i can't found where can I desactive this.

**Comment by khouloudbelguith** [comment]
Hi @Domnina,

As it's not the default theme, provided by Prestashop, we can't do anything with this.
You should contact the theme author, they are the only ones to help you with it.
Thanks!
I close the ticket, feel free to open a new one when needed.
