### ISSUE TITLE
Prestashop 1.7.5 - Module error with namespace

### ISSUE THREAD

**Issue by hottern** [PrestaShop/PrestaShop#13133]
Hello, I use this article https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/  to create controller in my module. I create composer.json file in my module folder but I can't access to my route.  As I understand I need to use this command in terminal `php composer.phar update ` but I've got error `Could not open input file: composer.phar
`

**Comment by Matt75** [comment]
You can find example here : https://github.com/friends-of-prestashop/masterclass

Try `composer -v` to check if composer is available in your terminal
If you have composer installed you can use `php composer update` directly

**Comment by hottern** [comment]
> You can find example here : https://github.com/friends-of-prestashop/masterclass
> 
> Try `composer -v` to check if composer is available in your terminal
> If you have composer installed you can use `php composer update` directly

thanks. And when I install composer it's work. but now I can't add my controller to tab in admin panel. My route is `modules/product_manuf/index`. How can I add this to tab? I use
           `$tab = new Tab();
            $tab->class_name = $controller;`

**Comment by khouloudbelguith** [comment]
@Matt75, what do you think?

**Comment by Matt75** [comment]
Everything is in the example : https://github.com/friends-of-prestashop/masterclass

https://github.com/friends-of-prestashop/masterclass/blob/4100a2c251b597a682895fa75723163f577792f3/masterclass.php#L60

https://github.com/friends-of-prestashop/masterclass/blob/master/config/routes.yml
