### ISSUE TITLE
Asunto Correo ps_reminder ¿donde se modifica?

### ISSUE THREAD

**Issue by javierVP** [PrestaShop/PrestaShop#13136]
Hola,
Necesito saber donde se puede modificar el asunto del mail del módulo ps_reminder follow_1 no lo encuentro en las traducciones, solo en el archivo php del módulo.

**Comment by khouloudbelguith** [comment]
@javierVP,

Thank you for giving your problem with the English language.

**Comment by javierVP** [comment]
ok.
Hello,
I need to know where you can modify the mail subject of the module ps_reminder follow_1 I can not find it in the translations, only in the php file of the module.

**Comment by khouloudbelguith** [comment]
Hi @javierVP,

You can add the desired language in your project folder => modules => ps_reminder => translations.

Thanks to check and feedback.

**Comment by javierVP** [comment]
Can you tell me how to add the translation for the mail subject

**Comment by khouloudbelguith** [comment]
Hi @javierVP,

In your project folder => modules => ps_reminder => mails, you have to create a folder with the name "name of the desired language" (for example fr if the language is French),  then under this folder create a file "lang .php"  with the following content 
```
<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['old text'] = 'nouveau texte (French language)';

return $_LANGMAIL;
```

Thanks to check and feedback.

**Comment by javierVP** [comment]
thanks

**Comment by khouloudbelguith** [comment]
@javierVP, you are welcome.

**Comment by khouloudbelguith** [comment]
Hi @javierVP,

Does your problem is solved?

**Comment by khouloudbelguith** [comment]
Hi @javierVP, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
