### ISSUE TITLE
Dropzone already attached in modules.

### ISSUE THREAD

**Issue by wordliner** [PrestaShop/PrestaShop#13134]
My client installed module in his Prestashop 1.7.5 on PHP 7.1, and something went wrong. Now we cant add any new module because dropzone is allredy attached. If it really has infinite timeout it didn't close first time we try to install module.

Here is consol log. Debug shows no error. 
`Uncaught Error: Dropzone already attached.
    at new Dropzone (main.bundle.js:24413)
    at Function.Dropzone.discover (main.bundle.js:25465)
    at Dropzone._autoDiscoverFunction (main.bundle.js:25747)
    at HTMLDocument.init (main.bundle.js:25716)
main.bundle.js:64176 
manage?_token=kOZkyDmYk_7A-nJJI4OacZ4cncpWLQ_jrJIQ2YStrsE:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (main.bundle.js:64178)
    at fire (main.bundle.js:51635)
    at Object.fireWith [as resolveWith] (main.bundle.js:51765)
    at done (main.bundle.js:57205)
    at XMLHttpRequest.<anonymous> (main.bundle.js:57571)`

**Comment by khouloudbelguith** [comment]
Hi @wordliner,

What is the module he has installed?

Thanks!

**Comment by wordliner** [comment]
Etykiety produktów (Product Stickers. )
v1.5.0 - z SeoSA

**Comment by wordliner** [comment]
I renamed all the modules in shop and the problem persists.

**Comment by khouloudbelguith** [comment]
@wordliner, the Etykiety produktów module is provided by Prestashop?

**Comment by wordliner** [comment]
https://addons.prestashop.com/pl/odznaki-logo/17830-stickers-and-labels-on-products.html

**Comment by khouloudbelguith** [comment]
@wordliner, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
I close the ticket, feel free to open a new one when needed.
