### ISSUE TITLE
Problem sending email from module

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#13148]
If you install Prestashop in a subfolder and try to send an email from a module (eg ps_emailsubscription), the system shows the error: "Error - The following e-mail template is missing: ...".
Ex:
If you subscribe to the newsletter the system tries to send the confirmation email (newsletter_verif) and shows the error.
I suppose the problem is in the function Mail::Send()
`            // get templatePath`
`            if (preg_match('#' . $shop->physical_uri . 'modules/#', str_replace(DIRECTORY_SEPARATOR, '/', $templatePath)) &&
                preg_match('#modules/([a-z0-9_-]+)/#ui', str_replace(DIRECTORY_SEPARATOR, '/', $templatePath), $res)
            ) {`
`                $moduleName = $res[1]`;
`            }`

when Prestashop is installed in a subfolder eg www.site.it/shop/, $shop->physical_uri takes the value "shop", and $templatePath takes the value "/home/xxxx/domains/site.it/public_html/shop/modules/ps_emailsubscription/mails/, with these values
`preg_match ('#'. $ shop-> physical_uri. 'modules / #', str_replace (DIRECTORY_SEPARATOR, '/', $ templatePath))`
returns 0 and therefore the variable $moduleName is not set and this generates the problem.

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

Could you please add steps screenshots or video record to reproduce the issue in a new comment because the email hasn't  been sent
 
Thanks!

**Comment by Codencode** [comment]
Hi @khouloudbelguith ,

I attached 2 screenshots

![Screenshot_1](https://user-images.githubusercontent.com/2463965/55474682-113b2680-5612-11e9-9d90-bad3ea3110dc.png)
![Screenshot_2](https://user-images.githubusercontent.com/2463965/55474684-113b2680-5612-11e9-9b2b-bdd9481f8ea9.png)

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1s4kBGnuD93SeqZfjIeZZsHcZiQUxqj3Q/view
What is the exact version of PS did you used?

Thanks!

**Comment by Codencode** [comment]
Hi @khouloudbelguith 

You have to set the "Would you like to send a verification email after subscription?" (Configuration NW_VERIFICATION_EMAIL)  field on "Yes" for the "ps_emailsubscription" module.

Thanks!

**Comment by khouloudbelguith** [comment]
@Codencode, yes, I attached a video record.
https://drive.google.com/file/d/1dnr5jzH28fZHLt31A38r-zrdVLSLR_c_/view

**Comment by Codencode** [comment]
Hi @khouloudbelguith,

the problem also occurs when you create a new order and the system sends the notification to the merchant

I attached the error video.

Thanks!

[Video.zip](https://github.com/PrestaShop/PrestaShop/files/3039314/Video.zip)

**Comment by Codencode** [comment]
I attached the debugging video (after send newsletter form).

[Debugging.zip](https://github.com/PrestaShop/PrestaShop/files/3039394/Debugging.zip)

**Comment by Codencode** [comment]
I think I understood the cause of the problem.
My problem is caused by using an alias to define the root of the project
eg:
Alias "/prestashop" "D:/cms/Prestashop/Site/"
<Location / prestashop>
Options All
Require all granted
</ Location>

where D:/cms/Prestashop/Site/ is the path to the root and "prestashop" is the alias

If I try the site on a server in production the problem doesn't occur.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

I close the ticket, feel free to open a new one when needed.
