### ISSUE TITLE
Payment filter by carrier

### ISSUE THREAD

**Issue by raharima** [PrestaShop/PrestaShop#13142]
Hello,

I have configure payment restriction by carrier but in front, the restriction is not good.

On the Hook classe, the method `getHookModuleExecList` from _**Hook**_ classe use `$context->cart->id_carrier`.
But on the front `$context->cart->id_carrier` is not set.
And the **_CheckoutPaymentStepCore_** use `$this->getCheckoutSession()->getSelectedDeliveryOption()` and not `$context->cart->id_carrier`. 

So, the carriers restrictions for payment never work for me.

I use Prestashop 1.7.5

**Comment by khouloudbelguith** [comment]
Hi @humansix,

Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @humansix,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
