### ISSUE TITLE
problem refreshing the reference

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#13143]
Hi,

I am working on a Prestashop version 1.7.5.0. In a product sheet, I have several variations with several references.
In front office, the reference doesn't update when I choose another declination. For it to update, I have to reload the page.
I also checked the basket and the order validation, the reference doesn't update so it creates internal errors.

My old shop was on Prestashop 1.6.1.3 and the change of reference worked perfectly.

Can you help me ?

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1nuhlvY-TjF9U1R39miDq_Y7d-cUTPirE/view
Are you using the template by default of Prestashop?

Thanks!

**Comment by Amulliez** [comment]
Hi @khouloudbelguith 

I don't see your video.

Yes, I use the template by default of Prestashop.

Thanks.

**Comment by khouloudbelguith** [comment]
@Amulliez, sorry you can see it now.

**Comment by Amulliez** [comment]
Hi @khouloudbelguith 

I modified the product.tpl file to add the following part of the product-details.tpl file:
{if isset ($ product.reference_to_display) && $ product.reference_to_display neq ''}
       <div class = "product-reference">
         <label class = "label"> {l s = 'Reference' from 'Shop.Theme.Catalog'} </ label>
         <span itemprop = "sku"> {$ product.reference_to_display} </ span>
       </ Div>
     {/ If}

It does not work because I should miss this part that updates the reference:
<div class = "tab-pane fade {if! $ product.description} in active {/ if}"
      id = "product-details"
      data-product = "{$ product.embedded_attributes | json_encode}"
      role = "tabpanel"
   >

Can you help me without changing this development?

Thank you.

**Comment by Amulliez** [comment]
I modified the product.tpl file to add the following part of the product-details.tpl file:
{if isset ($ product.reference_to_display) && $ product.reference_to_display neq ''}
       <div class = "product-reference">
         <label class = "label"> {l s = 'Reference' from 'Shop.Theme.Catalog'} </ label>
         <span itemprop = "sku"> {$ product.reference_to_display} </ span>
       </ Div>
     {/ If}

It does not work because I should miss this part that updates the reference:
<div class = "tab-pane fade {if! $ product.description} in active {/ if}"
      id = "product-details"
      data-product = "{$ product.embedded_attributes | json_encode}"
      role = "tabpanel"
   >

Can you help me without changing this development?

Thank you.

**Comment by khouloudbelguith** [comment]
@Amulliez, try to change your file by [product.tpl.zip](https://github.com/PrestaShop/PrestaShop/files/3034844/product.tpl.zip) and check.

**Comment by Amulliez** [comment]
Hi @khouloudbelguith ,

I have already modified this file and the product-details.tpl file and the problem update reference is resolved. I hope to keep changing my theme.

Javascript doesn't work properly. Can you help me?

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

No, sorry.
I close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by 0dp** [comment]
@khouloudbelguith 
> @Amulliez, try to change your file by product.tpl.zip and check.

What changes are you implying will fix the issue?

@Amulliez 
> I have already modified this file and the product-details.tpl file and the problem update reference is resolved. I hope to keep changing my theme.

How did you resolve the issue?
