### ISSUE TITLE
The Max size of short description field is invalid.

### ISSUE THREAD

**Issue by ninefingersodnd** [PrestaShop/PrestaShop#13140]
**Describe the bug**
Spontanious i get a fault in the Max size of short description.
I cant change it to anything and it stated Array. Products cannot be saved.

**To Reproduce**
1. Go to 'Shop parameters-product settings'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![array](https://user-images.githubusercontent.com/23555131/55388703-09a55000-5534-11e9-8cd8-063be96b335c.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: php 7.33

**Comment by khouloudbelguith** [comment]
Hi @ninefingersodnd,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1ti07obNrpnvs417DDPJhQrc6Hw1EWSxa/view

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ninefingersodnd** [comment]
This has to do with an extra id in the configuration_lang table in DB. When removed it works again!

**Comment by khouloudbelguith** [comment]
Hi @ninefingersodnd,

Thanks for your feedback.
I close the ticket, feel free to open a new one when needed.
