### ISSUE TITLE
brand assign instead of supplier on SupplierController

### ISSUE THREAD

**Issue by chrisvanberg** [PrestaShop/PrestaShop#13149]
Hello,
**Describe the bug**
While I was looking at the core, I saw that in `PrestaShop/controllers/front/listing/SupplierController.php`  
near the line 175 there is a reference about brands.

```php
  $this->context->smarty->assign(array(
            'brands' => $suppliersVar,
        ));
```

Isn't supposed to be suppliers instead ?

I would love to make a PR if it is a bug

**To Reproduce**
N/A

**Screenshots**
N/A

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @chrisvanberg,

It's not a BUG because of the basic model of suppliers.tpl is brands.tpl.
In .../themes/classic/templates/catalog/suppliers.tpl we find "extends file='catalog/brands.tpl'".

Thanks to check and feedback.

**Comment by chrisvanberg** [comment]
Ohh I see, thanks for the info !

Have a nice day
