### ISSUE TITLE
Material icon on add brand page should be a star

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13155]
**Describe the bug**
Material icon on add brand page should be a star
https://github.com/PrestaShop/PrestaShop/pull/12735#issuecomment-475590654

**Screenshots**
![capture d'écran_1281](https://user-images.githubusercontent.com/13449658/55464217-e2fe1c80-55fa-11e9-81c3-1cc9241a4f60.png)

It should be like below instead

<img width="217" alt="54820768-8ae12500-4ca0-11e9-94d0-e1ac6ac9b203" src="https://user-images.githubusercontent.com/13449658/55464247-f6a98300-55fa-11e9-8058-9523209b2baf.png">

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13157
