### ISSUE TITLE
Duplicate "Multistore" page in Employee dropdown

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13166]
**Describe the bug**
In the Employee form, you can choose the "default page" for an Employee and 2 of the options are displayed identical.

In fact it is 2 different pages:

- one allows to control Shop Groups for multistore management
- one allows to control Shop URLs for multistore management
We need to choose 2 different wordings to relate to them. I suggest "Multistore Groups" and "Multistore URLs", what do you think ?

This is extracted from https://github.com/PrestaShop/PrestaShop/issues/10503#issuecomment-458961056

**To Reproduce**
Go to Add/Edit an employee page, see "default page" drop-down, open it and see the duplicate options.

**Screenshots**
https://prnt.sc/me9rq5

**Comment by marionf** [comment]
@matks 

It seems there is only one "multistore" in the migrated page

![capture d'écran_1657](https://user-images.githubusercontent.com/13449658/59195899-7b7dc380-8b8d-11e9-89a3-ad9a25230701.png)

**Comment by matks** [comment]
> @matks
> 
> It seems there is only one "multistore" in the migrated page
> 
> ![capture d'écran_1657](https://user-images.githubusercontent.com/13449658/59195899-7b7dc380-8b8d-11e9-89a3-ad9a25230701.png)

Check in English ;) maybe the 2 tabs have been translated with 2 different names for French.

**Comment by marionf** [comment]
Humm, same thing

![capture d'écran_1663](https://user-images.githubusercontent.com/13449658/59278111-b3563b00-8c61-11e9-8af6-97d03bc519f5.png)

**Comment by marionf** [comment]
I can't reproduce, I have only one "multistore" option in the dropdown
