### ISSUE TITLE
Information about split orders

### ISSUE THREAD

**Issue by Partenopeo83** [PrestaShop/PrestaShop#13179]
Hi,
i don't think it's an issue. I would to know what are the occasions where PS split orders into parts with same reference and if it's possible to disable this feature because in my systems create many problems.

Thanks for help

PrestaShop version: 1.7.4.2
PHP version:7.1

**Comment by khouloudbelguith** [comment]
Hi @Partenopeo83,

The split order is done if you have 2 different carriers for different products added to the cart.
I attached a video record
https://drive.google.com/file/d/1hX6jeyZmD8VyYVVezIJJvUIzMGloLghR/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Partenopeo83,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
