### ISSUE TITLE
shortening the description of the category in prestashop 1.7

### ISSUE THREAD

**Issue by Ksawery88** [PrestaShop/PrestaShop#13205]
hey, he wants to shorten the description of the category to 500 characters I want the read more button to appear

in the file /themes/classic/templates/catalog/listing/category.tpl is:
    
```
<h1 class="h1">{$category.name}</h1>
      {if $category.description}
        <div id="category-description" class="text-muted">{$category.description nofilter}</div>
      {/if}
```

In prestashop 1.6, read more is standard when the description is too large. How should I do this on prestashop 1.7?

**Comment by khouloudbelguith** [comment]
Hi @Ksawery88,

Could you please provide us some screenshots about your issue.

Thanks!

**Comment by Ksawery88** [comment]
I mean, I have a long text and I want to shorten it. To make the read more button appear.

![text](https://user-images.githubusercontent.com/49279333/55610295-ea503200-5782-11e9-980a-54ae79d0129c.jpg)
Prestashop 1.6 is standard. How should I do this on prestashop 1.7?

**Comment by khouloudbelguith** [comment]
Hi @Ksawery88,

I will consider this as a suggestion.
@colinegin, @marionf, what do you think?

**Comment by Ksawery88** [comment]
@khouloudbelguith 
 are you able to help me with this problem?

**Comment by khouloudbelguith** [comment]
Hi @Ksawery88,

It's normal behavior in PrestaShop 1.7, it's not a problem.

Thanks!

**Comment by Ksawery88** [comment]
but will it be solved? There will be a button to read more, how the content is too big.

**Comment by colinegin** [comment]
Hello @Ksawery88 ,

Thanks for your feedback and sorry for the late reply.

This feature has been removed in 1.7.6 as it is not a good practice to write a long description in this page. The goal of the category page is to showcase products and make it easy for the user to easily find the products he is looking for. The category banner is here to remind the category and its value proposition not to give a detailed explanation of what it is, how it works, etc. If this type of content is needed for your activity, I would rather recommend to created a dedicated content page.

What do you think ?

**Comment by khouloudbelguith** [comment]
Hi @Ksawery88,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
