### ISSUE TITLE
Apply free shipping voucher crashing the entire website

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#13207]
PS version: 1.7.4.2
PHP 7.1

Create a voucher from AdminCartRules
Set minimum amount to 45€ (tax included) (shipping excluded)
From the Action tab flag to yes FREE SHIPPING and nothing else (no amount or percentage discount).
Then go on front office, add a product to the cart, and add the voucher code to the cart.
At this point you shouldn't see any confirmation or error message about the added voucher code, but the entire website will crash because PS it's using 100% of CPU.
I have a server with 8 CPU and the website stopped working, including all the other website I have under the same domain.

My hosting said that from the log they saw a problem with classes/Group.php.
Multiple error like this one:
WARNING: [pool mydomain.com] child 13925 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 240 seconds exceeded

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1swr85XkuqzL0LtKT-arktXQ0vUHKA-s0/view

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by darkf3d3** [comment]
Debug mode doesn't show any error, and also chrome console. After clicking on the button to add the voucher, timeout error it's showed.
This is what I have into server error log:
![errorlog](https://user-images.githubusercontent.com/42684711/55569143-52f6ca80-5701-11e9-8813-7c379457524f.png)
There's a public prestashop demo where i can test this? I lookead at the Prestashop demo linked on PS website but I'm not sure it allow to do this, because also if i create vouchers, I cant see voucher field on front office.
One thing I noticed from your video it's that you already have free shipping before adding the voucher, while on my test the shipping it wasn't free. Maybe it could be because of this that you were not able to reproduce the bug?

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

With carrier not free, I did not manage to reproduce your issue.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

**Comment by abondares** [comment]
I have the same exact problem. Is the problem fixed? I have Prestashop 1.7.5.2. Nothing in debug logs. 
There must be some recursion.

**Comment by khouloudbelguith** [comment]
Hi @abondares,

We just manage to reproduce a similar issue in those tickets:
https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882
https://github.com/PrestaShop/PrestaShop/issues/11172#issuecomment-502165356

Thanks!
