### ISSUE TITLE
The product doesn't get add to cart after deleting product customisation

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#13211]
**Describe the bug**
The product doesn't get added to cart in the below situation.
Suppose a product is created with customization(with at least one required field) without any combinations. Now from the front end, we have added the customization and add the product to cart. In this case, the product will get added to cart. Now delete the customization fields from the back office and save the product, Now if you will try to add the product in the cart the product will not be added to cart. 

And now if you will try to duplicate this product from back office then the copy product will create with that product customization fields.  

**To Reproduce**
1. Go to catalog and click on New Product
2. Now add the product with customisation field in which there must be at least one required field
3. Set the basic configuration of the product as normal. No need to add combinations.
4. Now from front end save the custiomisation data and add the product to a cart.(The product will be added)
5. Now from back office delete the customisation from the product.
6. Now again try to add product in to cart (the Product will not added to cart)
7. Even if will try with other customer then also the product will not add to cart.

**Screenshots**
![addtocart](https://user-images.githubusercontent.com/39614089/55610270-3493dc00-57a0-11e9-83c9-3c9d41ce35f1.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

I manage to reproduce the issue with PS:1.7.5.1
This issue is added to our bug roadmap.

Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 

Thanks,

I have a solution for this bug and will raise PR soon.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, about your code suggestion, would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith 

Yes, I'll make a pull request on GitHub but can't be raised with branch develop.
Actually, I have already raised a pull request on this branch which is pending #12033 and also has raised one more pull request on branch 1.7.5.x which is also pending #12683 

Please review these and get approve this so that I can raise a new pull request on develop branch  (https://github.com/PrestaShop/PrestaShop/tree/develop)

Could you please suggest me any other branch on which I can make a pull request for this issue.

Thanks.

**Comment by dazhbog** [comment]
I think I am having the same issue. 

Firstly, the cart is not working as @PeeyushAgrawalWebkul mentioned. I deleted the required customization field and I can't add the product as expected. However, if I duplicate the buggy product, the customization becomes enabled for the duplicated product. That means that something is not getting cleared correctly in the original listing?

However, the duplicated product does work (after clearing its customization) though which is weird.

**Comment by khouloudbelguith** [comment]
Hi @dazhbog,

This issue is added to our bug roadmap 

Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 

Thanks,

I have a solution regarding this issue but I can't raise pull request with branch develop.
Actually, I have already raised a pull request on this branch which is pending #12033 and also has raised one more pull request on branch 1.7.5.x which is also pending #12683

Please review these and get approve this so that I can raise a new pull request on develop branch (https://github.com/PrestaShop/PrestaShop/tree/develop)
OR
Could you please suggest me any other way or branch on which I can make a pull request for this issue.

Thanks.

**Comment by dazhbog** [comment]
Hi @khouloudbelguith,

Thank you for your message.

I just noticed that even though the duplicated product I made (that had the customization bug) was working on my same machine that I created it (cookie issue?) It could not be added to cart on a fresh session with no cookies.

Do you think this is the same issue? Why would cookies in some sessions allow a product to be added and in some not?

Do you have any recommendations on how to monitor this? What error logs shall I be looking for? Front-end doesnt really throw any warnings.

Thanks

**Comment by khouloudbelguith** [comment]
@dazhbog, so did you create from the BO a duplicate for this product, the issue is not reproduced with it in the FO?
Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 

The PR https://github.com/PrestaShop/PrestaShop/pull/15739 has been rasied please check.

Thanks.
