### ISSUE TITLE
CartPresenter computes tax information only if PS_TAX_DISPLAY is enabled and tax amount is badly computed

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13228]
## Strange condition to compute cart tax data

In `PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter::present($cart, $shouldSeparateGifts = false)`, we compute an array `$subtotals` with one key `tax` ONLY if configuration PS_TAX_DISPLAY is enabled.
`if (Configuration::get('PS_TAX_DISPLAY')) {`

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Cart/CartPresenter.php#L380

## Bad tax amount computation

In this array, we compute the amount of the taxes in order to display to the customer how much he is paying for taxes. But this amount is a basic soustraction:
`$taxAmount = $total_including_tax - $total_excluding_tax;`

This is prone to rounding issues.

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Cart/CartPresenter.php#L381

**Comment by khouloudbelguith** [comment]
@colinegin, what do you think?

**Comment by colinegin** [comment]
@matks is there anything I should specify here ? Should it be done in 1.7.6 ?
Is this a bug or an improvement ?

**Comment by matks** [comment]
No, the question is rather whether this is for 1.7.6 or does it go into the backlog

**Comment by colinegin** [comment]
Well i think this should be solved within the project Price & taxes (2nd round), with other rounding issues. What do you think ?

**Comment by matks** [comment]
Good idea 😄

**Comment by colinegin** [comment]
Alright then, I put it into 1.7.7 backlog !

**Comment by colinegin** [comment]
@eternoendless @matks as we have to make a full refacto of the price calculation system, does this mean this issue no longer makes sense for 1.7.7 ?

**Comment by matks** [comment]
@colinegin No, luckily this issue is related to the Cart Presenter (how data from cart are being computed to be used in the front office) which is a lot easier to deal with. It's outside of the big rework of price calculation and can be quickly.

**Comment by atomiix** [comment]
After looking to this issue, it seems that it's okay for me.

The key `tax` is being computed only when `PS_TAX_DISPLAY ` is true and that makes sense to me as every `$subtotals` keys will be displayed on the cart summary and if `PS_TAX_DISPLAY` is false we don't want it to be displayed.

`$taxAmount ` is calculated from the 2 variables `$total_including_tax` and `$total_excluding_tax` that are already rounded so it cannot add any rounding issue

I think we can close this issue, what do you think @colinegin, @matks ?

**Comment by colinegin** [comment]
To be honest i'm not sure of this issue, @matks will better know what we are supposed to do with this issue and if this is still needed.

**Comment by matks** [comment]
@atomiix analysis is good 👍 my worries were not met by reality so we can close this issue safely 😊
