### ISSUE TITLE
Display "tax included" or "tax excluded" if cart contains no taxeable items ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13227]
In https://github.com/PrestaShop/PrestaShop/pull/13047/commits/381b85c33cd93114c10b7bea453d4412f46f17cd we hide the "tax included" or "tax excluded" part from the cart summary if taxes have been disabled in the backoffice.

Question is: what if taxes are enabled *but* customer has put in his carts products that have no tax configured, and are being shipped with a shipping method which has no tax too ? Should we hide the "tax included" or "tax excluded" part as well ?

**Comment by khouloudbelguith** [comment]
@colinegin, what do you think?

**Comment by colinegin** [comment]
In my opinion, we should leave it the way it is now, meaning that if the product has no tax, but the store uses taxes, then the price should be tax included, in this case taxes = 0.

Do you agree @matks ?

**Comment by colinegin** [comment]
What do you think about this @matks ?

**Comment by matks** [comment]
Sorry for the late response, indeed it makes sense 👍 

So to sum it up:
- if the shop has been configured with taxes ON
- if product X has no tax configured
- customer add product X to cart
- customer chooses a shipping method that has no tax configured
THEN
we display the "tax included" label although the tax amount is zero

**Comment by colinegin** [comment]
Yes exactly. I close this issue then, i will add this behaviour in the PrestaShop specs.
