### ISSUE TITLE
Problem with Prestashop for save and stay

### ISSUE THREAD

**Issue by NewNelson** [PrestaShop/PrestaShop#13224]
Hello,
I have a problem on Prestashop when I want to "save and stay" a product on Firefox since yesterday but also on Chrome for 2 years.

Someone can help me.

Damien

**Comment by khouloudbelguith** [comment]
Hi @NewNelson,

What is the exact version of PS did you used?

Thanks

**Comment by NewNelson** [comment]
Hi khouloudbelguith,

![image](https://user-images.githubusercontent.com/49316747/55640827-b3067300-57cc-11e9-8e95-2ac7f8af1343.png)

Thanks

**Comment by khouloudbelguith** [comment]
@NewNelson, consult this link: http://forge.prestashop.com/browse/PSCSX-9042
As you can see here: the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Your bug isn’t critical or a security issue, that’s why I close it.

Thanks!
