### ISSUE TITLE
Promo code during checkout and order button

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13229]
**Describe the bug**
1) Try to add a promo code during checkout, try to open and close it
The effect is jerky

2) The "order" button is stuck to the frame

![capture d'écran_1323](https://user-images.githubusercontent.com/13449658/55716239-c5fc8b80-59f6-11e9-9e16-cd92edcec689.png)

3) When you have promo code highlighted and you arrive on the checkout you have 2 links: "Have a promo code ?" and "Close" to do the same thing
"Have a promo code?" shouldn't be displayed in this case

![capture d'écran_1331](https://user-images.githubusercontent.com/13449658/55784715-6a430880-5ab1-11e9-927c-9a721493d3e9.png)

4) When you click on close the promo code higlighted is closed, it should be only the promo field

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by TristanLDD** [comment]
I've seen with @YeLnatSs for the expected behavior : 
![Capture d’écran 2019-04-17 à 15 08 16](https://user-images.githubusercontent.com/27484094/56290257-0e1c5c00-6123-11e9-9eb6-2bd81e21227a.png)

**Comment by marionf** [comment]
@TristanLDD 

Do you have recommendations about the order button that is stuck to the frame ?

**Comment by TristanLDD** [comment]
I checked with @YeLnatSs for the button, it's fixed ;)

**Comment by PierreRambaud** [comment]
@marionf @TristanLDD Can you have a check on https://github.com/PrestaShop/PrestaShop/pull/14180 and tell me if everything is ok. Didn't have the time to checked it together today :disappointed:
