### ISSUE TITLE
Create currency has no names nor symbols

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#13249]
**Describe the bug**
I go to "International > Localization > Currencies" page in the Back office.
I try to create a new currency, select it and set a rate, then click save
The currency is added I can see it in the back office and in the database
However is localized info (in `currency_lang`) are empty (name and symbol)
The numeric_iso_code is also missing (and I'm not sure about the precision but 0 seems suspect)

**Screenshots**
![Capture d’écran 2019-04-09 à 10 25 16](https://user-images.githubusercontent.com/13801017/55785007-f9e8b700-5ab1-11e9-837c-2a817677de27.png)

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by jolelievre** [comment]
Hi @tomlev can you check that this fixes another issue in the Product price
When you wan to add a specific price, you have a select box which can contain either percentage or price type
Currently the price type is empty because it uses `currency->getSymbol()`, can you please check that your fix also fixes this issue?

**Comment by tomlev** [comment]
do you have issue number please ?
Maybe it could be checked in QA phase ?

**Comment by jolelievre** [comment]
I didn't want to create an extra issue (since it's the same origin as this one) but Marvine saw it while fixing another issue on this page
Validate it in QA seems appropriate

**Comment by Quetzacoalt91** [comment]
May I close this issue @marionf?

**Comment by marionf** [comment]
Yes :)
