### ISSUE TITLE
Currency missing language infos after fresh installation

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#13247]
**Describe the bug**
After a fresh install from `1.7.6.x` branch when I try to access the front I get an exception:

![Capture d’écran 2019-04-08 à 18 41 14](https://user-images.githubusercontent.com/13801017/55742829-fa8d3900-5a30-11e9-86c0-dc738d7ae908.png)

**To Reproduce**
I clone the project and switched to the `1.7.6.x` branch then I performed a CLI installation with these parameters:

```
php install-dev/index_cli.php \
        --language=en \
        --country=fr \
```

**Symptoms**
Both languages have been installed (I can see them in the database and in the back office), however when I look a `currency_lang` table I only see one language for the only present currency Euro.

**Solution**
We need to fix two problems:

- [ ] when the user's language is not available in the Currency it must fallback on the default one
- [ ] find out why only one language was installed for the currency

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by marionf** [comment]
I can't reproduce with a "normal" install, it's jsut in CLI mode ?

**Comment by marionf** [comment]
Edit: I well have the issue when I install in English and France country
