### ISSUE TITLE
 prestige_fashion version 1.1.2

### ISSUE THREAD

**Issue by sklepgdansk** [PrestaShop/PrestaShop#13248]
Hello, I have a problem with the motive
prestige_fashion version 1.1.2 did not load the upper image instead, I read in a photo from the previous classic template, there is an error at the entrance to each page

ERROR THROWN OBJECT TEXT STATUS PARSERERROR. 

I am asking for help from my side, I installed everything in turn, I uploaded themes on other pages and there were no mistakes Tomasz Osinski

mail: kontakt@stronadebno.pl

**Comment by kpodemski** [comment]
This is not a place to report issues with custom themes, you should contact theme author.

**Comment by khouloudbelguith** [comment]
Hi @sklepgdansk,

As it's not the default theme, provided by Prestashop, we can't do anything with this.
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you on it.
Thanks!
I close the ticket, feel free to open a new one when needed.
