### ISSUE TITLE
Left and Top Shop-Menu is shown twice if access "Menu" -> "Payment" PS 1.7.5.1

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#13255]
If I access the payment settings in left menu the left menu and the top menu is shown twice in payment window:

![image](https://user-images.githubusercontent.com/44971218/55840252-1e34aa00-5b2b-11e9-88b6-02599ab6a52b.png)

It seams like prestashop wants to open the "Modules" -> "Modules Catalogue" too

![image](https://user-images.githubusercontent.com/44971218/55840389-88e5e580-5b2b-11e9-96ef-fe42339201ad.png)

Prestashop 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1QrAS1AnzYQI6vLdcHK0eX1enxNqQNTN1/view
Can you tell me the language and the country selected at the installation of your shop?

Thanks!

**Comment by didi-2018** [comment]
Hi @khouloudbelguith  my installation is in german and I am in germany

**Comment by khouloudbelguith** [comment]
@didi-2018, I checked with a fresh installation PS:1.7.5.1, Germany country, German language, and everything is OK.
I attached a video record.
https://drive.google.com/file/d/1aBcpLQNVPdfUskJyvWMrUcf_J279SNz-/view
Could you please clear cache, check your shop with another browser and feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith In your videos you always go first to modules but I do not. I only go to payments -> payment settings but NOT to modules. In that second menu prestashop wants to open the modules themselves. Cache is always clear and disabled at the moment. I have the same behavior with other browsers. Can you explain me how to make a video like yours? I like to show you in a video too. Thanks a lot!

**Comment by khouloudbelguith** [comment]
@didi-2018, just add the extension "Screencastify - Screen Video Recorder" to your browser to record videos.

**Comment by didi-2018** [comment]
@khouloudbelguith, thanks! I maked a video:
https://drive.google.com/file/d/12KxMiP3pCA51S2BhXiz_R1L2q4YWdG_j/view

**Comment by khouloudbelguith** [comment]
@didi-2018, it worked well for me.
I attached a video record.
https://drive.google.com/file/d/1qZe3PCP_dvqUgQp2wCqCBqtgAJLeSll6/view

**Comment by khouloudbelguith** [comment]
@didi-2018, despite our several trials, we could not reproduce your issue with the provided information.
I close the ticket, feel free to open a new one when needed.
 Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith , okay it is not such a big problem for me cause I can access all payment modules from Modules Section ;-)

**Comment by Matt75** [comment]
Can you try to disable module ps_mbo ?
I looks like the ajax request performed in hook displayAdminEndContent on this page inject bad content in the page.

**Comment by didi-2018** [comment]
@Matt75 , Thanks that was it! I disabled ps_mbo and the issue is gone! :-D GREAT! 

@khouloudbelguith , please open it again and notice that bug with module ps_mbo. Thanks!

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & the ps_mbo module v1.1.1.
I attached a video record.
https://drive.google.com/file/d/1k8dqPjOyM84dy8L-ItECh6UWhMXFN9lX/view
Thanks!

**Comment by didi-2018** [comment]
@Matt75 @khouloudbelguith  I have exactly the same problem with PS 1.7.6.3
![image](https://user-images.githubusercontent.com/44971218/74109757-7478dc00-4b86-11ea-9c86-76beafe0549f.png)

and module **ps_mbo** is again the trouble maker :-( 
by disabling this module the issue is gone

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

In my case, it is ok with the PS1.7.6.3  & ps_mbo module.
https://drive.google.com/file/d/15Tf5JGXJVryteZZY0hMqw28I3D9fNh7o/view

Thanks!
