### ISSUE TITLE
Test E2E to test the migration of permission page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13254]
**Describe the bug**
We need E2E tests to test this PR: https://github.com/PrestaShop/PrestaShop/pull/12428

**Comment by PierreRambaud** [comment]
@mbadrani Any reason to close this issue? Can you add explanation please? :smile_cat:

**Comment by marionf** [comment]
It's done but I don't see any comments or QA approved on the PR
So, what are tests results ? This PR is ok or not ?

**Comment by mbadrani** [comment]
@PierreRambaud my bad just a mistake when I've closed the list of Issues included in Automation Kanban

**Comment by marionf** [comment]
Arfff, I thought it was done 
Can you tell us when is it planned to start on your schedule ?

**Comment by mbadrani** [comment]
Not this sprint for sure, but next iterations we need estimating it

**Comment by mbadrani** [comment]
I will keep you informed as well

**Comment by marionf** [comment]
@mbadrani any news ?

**Comment by mbadrani** [comment]
Mentioned for the next roadmap, will be planned on it

**Comment by marionf** [comment]
Currently, no feasible test (manual or auto)
We must first decide which behavior should be kept to be consistent between all the pages
