### ISSUE TITLE
Khmer Language not appearing in delivery Slip, instead shows [][][][][][] bracket

### ISSUE THREAD

**Issue by pawan120391** [PrestaShop/PrestaShop#13258]
Hi,

Khmer language is not appearing in Delivery Slip PDF, instead it shows [][][][][] brackets, which is unreadable, please suggest the suitable font or how can I fix this to be able to generate PDF in Khmer(Cambodian) language

**Comment by khouloudbelguith** [comment]
Hi @pawan120391,

What is the exact version did you used?
Could you please add a screenshot.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @pawan120391, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by rupalidu** [comment]
i am also facing the same issue Prestashop version is 1.7.4.2
