### ISSUE TITLE
Traffic stats should ignore search engine crawlers

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#13252]
**Describe the bug**
Search engine crawlers like googlebot generate a lots of traffic that is recorded as visits and page visits. This increase the traffic PKI artificially.
Search engine bots should be ignore or recorded separatly than real visitors.
**To Reproduce**
1. Go to a real backoffice shop in production.
2. Compage Google Analytics and Prestashop visits metrics.

Source code that track crawlers is here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Connection.php#L142

**Additionnal information**
PrestaShop version: all
PHP version: all

**Comment by jf-viguier** [comment]
Some bots or scrapers can use regular user agent (chrome ou firefox) and should be excluded from the traffic.

**Comment by matks** [comment]
Idea: the system we'll use to handle this should be configurable, so that people can expand the regular "blacklist" we're going to sketch. We will provide a standard blacklist of known user-agents and IPs to exclude, and people can then look in their server logs and expand it when they recognize another bot pattern.

**Comment by jf-viguier** [comment]
Everything in Prestashop should be customisable to fit specific country/context/marchant needs.

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I can not reproduce the problem with my site locally.
Could you please try to reproduce it from your side.
Thanks!

**Comment by jf-viguier** [comment]
Hi @khouloudbelguith,
Try to browse the site with a bot : the visit will appears. You can use "User-Agent Switcher for Chrome"

**Comment by khouloudbelguith** [comment]
@jf-viguier, thanks for your feedback.
The issue is added to our bug roadmap.

Thanks!

**Comment by jf-viguier** [comment]
Any news here ? I don't see this issue in any roadmap @khouloudbelguith ?

**Comment by khouloudbelguith** [comment]
@jf-viguier, the Label Todo is added to this issue
So, it is in the Todo list.

Thanks!

**Comment by jf-viguier** [comment]
Yes but no milestone assigned, I know what it means in Prestashop language : Saint Glin Glin

**Comment by khouloudbelguith** [comment]
@jf-viguier, Our product Team is responsible about the milestone.
Thanks!

**Comment by jf-viguier** [comment]
I've suggested a pr, discussion here https://github.com/PrestaShop/PrestaShop/pull/17322

**Comment by matks** [comment]
> Yes but no milestone assigned, I know what it means in Prestashop language : Saint Glin Glin

🤣

**Comment by HartLarsson** [comment]
Any implementation to avoid GoogleBot and other searching index bots at least?

Thanks
