### ISSUE TITLE
Generate button on add webservice isn't here anymore

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13263]
**Describe the bug**
Generate button on add webservice isn't here anymore

**To Reproduce**
1. Go to Advanced parameters > Webservice
2. Click on Add a webservice key
3. The generate button isn't here anymore 

**Screenshots**

![capture d'écran_1335](https://user-images.githubusercontent.com/13449658/55864593-17cf1e00-5b7d-11e9-9bfe-b8a92b30313b.png)

![capture d'écran_1334](https://user-images.githubusercontent.com/13449658/55864603-1a317800-5b7d-11e9-9d01-77f098702711.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13264
