### ISSUE TITLE
After Installation warning message "memcache:connect() error"

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#13265]
**Describe the bug**
After a successfull installation when you try to access to the front office page you can see this kind of error (capture attached)

**To Reproduce**
1. Install a Prestashop on 1.7.6.x branch
2. After successfull installation go to Front Office
3. An error message is diplayed (capture below)

**Screenshots**
![image](https://user-images.githubusercontent.com/29543279/55866547-dc365300-5b80-11e9-8b18-462a5756f28b.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7

**Comment by marionf** [comment]
Can't reproduce on 1.7.6.x branch
Do you have it also on 1.7.5.1 version ?

**Comment by mickaelandrieu** [comment]
Problem solved, this bug happens only if you have the memcached PHP extension enabled but not the memcached software.

This is not something we will try to fix, as it's really really really really uncommon!
