### ISSUE TITLE
Can't import united states localization pack

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13271]
**Describe the bug**
Can't import united states localization pack

**To Reproduce**
1. Go to International > Localization
2. Select united states and click on import
3. See error

**Screenshots**
![capture d'écran_1348](https://user-images.githubusercontent.com/13449658/55884378-43b3c900-5ba8-11e9-8f15-3ab1cf7a7c52.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Could be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13247
