### ISSUE TITLE
Overlap between From and To with the Help part of the orders page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13275]
**Describe the bug**

**To Reproduce**
1. Go to ''Orders" page.
2. Click on "Help"
3. Adjust resolution to 1455px of width

**Screenshots**
![Capture du 2019 04 10 15 54 14](https://user-images.githubusercontent.com/16067358/55889972-d1dc7f00-5ba9-11e9-97e3-128bb4e526e4.png)

**Additionnal information**
PrestaShop version: 1.7.5.1

**Comment by marionf** [comment]
Fixed on develop branch for 1.7.7:

![capture d'écran_2166](https://user-images.githubusercontent.com/13449658/69875292-15ad0180-12bd-11ea-84dc-2e05280e086d.png)
