### ISSUE TITLE
Currency list isn't the same as in 1.7.5.1

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13270]
**Describe the bug**
Currency list on 1.7.6.x isn't the same as 1.7.5.1

**To Reproduce**
1. Go to International > Localization > Currencies
2. Click on Add new currency
3. Look the list

For example, in 1.7.5.1 I had ZMW
In 1.7.6.0, I don't have it anymore but I have ZWD, ZWL, ZWR

![capture d'écran_1345](https://user-images.githubusercontent.com/13449658/55883620-f3883700-5ba6-11e9-9a27-4fd7c5531987.png)

![capture d'écran_1344](https://user-images.githubusercontent.com/13449658/55883631-f71bbe00-5ba6-11e9-8016-99d13edf1621.png)

**Additionnal information**
PrestaShop version: 1.7.6.X
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Please check again @marionf, I found it on my shop:

![Capture d’écran du 2019-04-10 15-32-16](https://user-images.githubusercontent.com/6768917/55887940-6349f200-5ba6-11e9-89fc-dc68d7d2c2b5.png)

Note the list may be not ordered properly.

**Comment by marionf** [comment]
Yes, you are right, I well have ZMW :)

We need to decide if we want to keep old currencies that were not there before and maybe reorder the list
