### ISSUE TITLE
Theme Customization module

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#13283]
A few issues need to be fixed (for 1.7.6 mostly) : 

- [x] https://github.com/PrestaShop/ps_themecusto/issues/9
- [x] https://github.com/PrestaShop/ps_themecusto/issues/10
- [x] https://github.com/PrestaShop/ps_themecusto/issues/7

Find the module repo here : https://github.com/PrestaShop/ps_themecusto

**Comment by jolelievre** [comment]
Seems like the first two issues are ok (no need to fix anything)
The last one already has a linked PR, should we do a QA for this one and merge it?

**Comment by marionf** [comment]
Pr is ok for me :)
