### ISSUE TITLE
Module dev: Override Class definition - bug when uninstall

### ISSUE THREAD

**Issue by IvoRabush** [PrestaShop/PrestaShop#13352]
**Describe the bug**
Incorrect uninstall of a module when overriding Class definition array. The whole definition array is not deleted, only the first line of the definition declaration is deleted.

**To Reproduce**
1. Crete a module
2. Create an override of any Prestashop Core Class
3. Override the **$definition array** by adding a new property. See the print screen below where I added "description_mobile"
**Screenshot**
![image](https://user-images.githubusercontent.com/32366618/55936356-b96a7400-5c3e-11e9-813d-8535b8507600.png)

4. When uninstalling the module, Prestashop deletes the **first line which is the declaration**: "public static $definition = array(" but **doesn't delete the content of the definition array**. See the print screen below
**Screenshot**
![image](https://user-images.githubusercontent.com/32366618/55936457-10704900-5c3f-11e9-8598-ac3ade38ea32.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @IvoRabush, 

Could you please try with these steps:
1. Delete the category class that is created under the override folder.
2. Give the right 755 to the category class created in the module.
3. Install uninstall your module.

Thanks for check and feedback.

**Comment by kpodemski** [comment]
This will not help, it's an issue with override mechanism not permissions

**Comment by khouloudbelguith** [comment]
Hi @IvoRabush,

I manage to reproduce the issue with PS:1.7.5.1.
I attached a screenshot.
![removeoverride](https://user-images.githubusercontent.com/16067358/55952366-5930fd80-5c51-11e9-959b-1fab180d4d6f.png)
This issue is added to our bug roadmap.

Thanks!

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers wdyt ?

**Comment by PierreRambaud** [comment]
I don't think we will do something about this problem since the override system is deprecated.
