### ISSUE TITLE
import 5 products per time

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13355]
prestashop 1.7.5.1 on ubuntu 18.4 (php 7.2.17)
I just can't understand why until a few weeks ago (I don't remember exactly) I imported the same csv / xlsx file more quickly, without these skips every 5 products. Now it imports 5 products at a time, as you can see in the video. Surely it's not a bug, but mine is just curiosity. Perhaps there is something to change in prestashop or in the configuration of my server?
https://nimb.ws/wUrcZe

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Could you please send me your file CSV to test it.

Thanks!

**Comment by centoasa** [comment]
attached
[grandstream1104.xlsx](https://github.com/PrestaShop/PrestaShop/files/3067653/grandstream1104.xlsx)

**Comment by khouloudbelguith** [comment]
@centoasa, could you please specify the names of the columns.

**Comment by centoasa** [comment]
attached
[test1104.xlsx](https://github.com/PrestaShop/PrestaShop/files/3068207/test1104.xlsx)

**Comment by khouloudbelguith** [comment]
@centoasa, did you use a specific module or activate an option (which is in red rectangle)?

![test](https://user-images.githubusercontent.com/16067358/55962696-517d5300-5c69-11e9-88f3-ee77b993bcaa.png)

**Comment by centoasa** [comment]
previously I saved the columns of my interest that I saved in the scheme that I named grandstream (red box)

**Comment by khouloudbelguith** [comment]
@centoasa, I did not manage to reproduce the issue with PS:1.7.5.1.
I used another file because yours is in the Italian language (we do not have the same names of categories ...)
I attached the CSV file and a video record.
https://drive.google.com/file/d/17mwWXEeEns4jAeX6A48KqKnA_uoLrxQw/view
[test_file.xlsx](https://github.com/PrestaShop/PrestaShop/files/3069180/test_file.xlsx)

Thanks to check and feedback.

**Comment by centoasa** [comment]
the result is almost identical to mine, even for you the import goes to step of 5/7 products; in addition I use the "Use the product reference as a keyword" flag
https://nimb.ws/6BnwxY
oh well, maybe I remember correctly, but before I import/updated many more products in one step

**Comment by khouloudbelguith** [comment]
@centoasa, with option "Use product reference as key" enabled.
I attached a video record.
https://drive.google.com/file/d/15-csWN7XfYUaAlGqX6HC0e_nuw7u2MiH/view

**Comment by centoasa** [comment]
I do other import tests and check. @khouloudbelguith  you can close this ticket, in case I write again. Thank you very much.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for your feedback.
I close the ticket, feel free to open a new one when needed.

**Comment by centoasa** [comment]
With smarty cache enabled (and template recompile if updated) my import stuck at 99%, server goes down and in the error_log I'll:
`[Sat Apr 13 11:08:42.580903 2019] [proxy_fcgi:error] [pid 13187:tid 140340237416192] [client 79.7.101.116:54040] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /var/www/vhosts/100asa.it/httpdocs/classes/db/Db.php:794\nStack trace:\n#0 /var/www/vhosts/100asa.it/httpdocs/config/alias.php(48): DbCore->escape('configuration', false)\n#1 /var/www/vhosts/100asa.it/httpdocs/config/alias.php(53): pSQL('configuration')\n#2 /var/www/vhosts/100asa.it/httpdocs/classes/Configuration.php(155): bqSQL('configuration')\n#3 /var/www/vhosts/100asa.it/httpdocs/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()\n#4 /var/www/vhosts/100asa.it/httpdocs/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')\n#5 /var/www/vhosts/100asa.it/httpdocs/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()\n#6 [internal function]: PrestaShopAutoload->load('Tools')\n#7 /var/www/vhosts/100asa.it/httpdocs/config/config.inc.php(85): spl_autoload_call('Tools')\n#8 /var/www/vhosts/100asa.it/httpdocs/Back100asa/index.php(42): require('/var/www/vhosts...')\n#9 {main}\n  thrown...\n', referer: https://www.100asa.it/Back100asa/index.php/configure/advanced/performance/?_token=PSsEj4dXrSg5e94cEUWlQxsKvVIpnakuWoniYaxa1hs
`
note happens with never compile template.

**Comment by khouloudbelguith** [comment]
@PrestaShop/prestashop-core-developers, what do you think?

**Comment by khouloudbelguith** [comment]
related to #12667

**Comment by centoasa** [comment]
sorry little question: what exact mean with "Skip preview regeneration" in import session?

**Comment by khouloudbelguith** [comment]
@centoasa, in which page, this expression is displayed?
Could you please provide a screenshot.
Thanks!

**Comment by centoasa** [comment]
https://nimb.ws/KXhnxp
and also: Delete all products before import--> delete all products in catalogue, or only products first of import process (so the product with the same reference that I'll import?)

**Comment by khouloudbelguith** [comment]
@centoasa, Skip thumbnails regeneration: Category and product import only. You can choose to have PrestaShop regenerate the thumbnails that are linked from your CSV file (in the "Image URL" or "Image URLs" fields).
Delete all ___ before import: This option will erase all previously existing entries of the type of data you are importing. Thus you will start with a clean slate.
Thanks!

**Comment by centoasa** [comment]
sorry me, but for sure: "Delete all ___ before import" feature will only delete the products that are included in my import file?
so: if I am importing 5 t-shirts A-B-C-D-E, this option will completely delete the sheet product only of these 5 t-shirts, or it will only delete the column data that I have selected from these 5 t-shirts of my prestashop, and not of my entire product catalog ? (you know, I wouldn't want to lose all my catalog of about 15k products with relative sheets)

**Comment by khouloudbelguith** [comment]
@centoasa, no, it will delete all your Products.
Thanks!

**Comment by centoasa** [comment]
while clear cache, on backoffice via performance-->clear cache, same error here (debian 9+php7.2.19+mod_pagespeed):
`AH01071: Got error 'PHP message: PHP Warning: require(/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_Core_Admin_PagePreferenceInterfaceService.php): failed to open stream: No such file or directory in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\nPHP message: PHP Warning: require(/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_Core_Admin_PagePreferenceInterfaceService.php): failed to open stream: No such file or directory in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\nPHP message: PHP Fatal error: require(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_Core_Admin_PagePreferenceInterfaceService.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\nPHP message: PHP Warning: require(/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\nPHP message: PHP Warning: require(/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\nPHP message: PHP Fatal error: require(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/ContainerDdg54gr/appProdProjectContainer.php on line 1151\n', referer: https://www.100asa.it/Back100asa/index.php/configure/advanced/performance/?_token=wLZe27XoUcZKqQcWrtcQll4ROqwivQ0vvJlFoLaqG6k`
crash and stuck my vps server

**Comment by PierreRambaud** [comment]
Look like you have issues with Symfony generated cache.
Try to remove manually.
`/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/` and reload the front and admin pages.

**Comment by centoasa** [comment]
whenever prestashop crashes, I'm forced to delete this folder to be able to reuse my store. But this problem often reappears.

**Comment by PierreRambaud** [comment]
We will investigate on it.
Ping @PrestaShop/prestashop-core-developers anyone already had this issue?

**Comment by centoasa** [comment]
With Prestashop 1.7.6, clean installation of Ubuntu 18.04, and only mod_pagespeed this issue doesn't happens anymore!

**Comment by khouloudbelguith** [comment]
@centoasa, thanks!
Feel free to open a new one when needed.

Thanks!
