### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#13360]
**Is your feature request related to a problem? Please describe.**
Prestashop will not get high scores on Google Pagespeed due to the html not being minified. Every whitespace/linebreak counts as an node in the DOM and this makes the count go up in the thousands and that gives a bad score on Pagespeed tests. This will have an effect on the ranking on Google and need to be addressed.

**Describe the solution you'd like**
A setting in performance like in 1.6 to enable minify of html.

**Comment by khouloudbelguith** [comment]
@PrestaShop/prestashop-core-developers, what do you think?

**Comment by matks** [comment]
> **Describe the solution you'd like**
> A setting in performance like in 1.6 to enable minify of html.

It make sense 👍 although it would ignore modules and hooks blocks as they would be out-of-scope.
If possible, let's use something that plugs on Smarty rather than a JS tool. This will make it easier to use for themes developer. 🤔 

@Prestaworks do you feel like trying to do a PR for it ? 😄

**Comment by eternoendless** [comment]
I think HTML minification is pretty much useless if your web server has compression enabled. Furthermore, a server module will be much more efficient at compressing than a PHP script.

See https://httpd.apache.org/docs/2.4/mod/mod_deflate.html

To me this is a no go.

**Comment by Prestaworks** [comment]
@eternoendless What do mod_deflate have to do with minification and removal of line breaks? Did you not read the initial message before closing the request?

**Comment by eternoendless** [comment]
I read too fast, my mistake. But even then, I can't see any HTML minification tests anywhere: https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=http%3A%2F%2Ffo.demo.prestashop.com%2Fen%2F

**Comment by Prestaworks** [comment]
@eternoendless it shows up when the amount of html elements grov, the default template do not suffer from this but if you would add a lot of modules and plugins the amount of elements will ofcourse grow, and when a linebreak is counted it will stack up quickly. 

It was a nice feature in 1.6, did it really cause issues for anyone?

**Comment by eternoendless** [comment]
Maybe [this](https://www.modpagespeed.com/doc/filter-whitespace-collapse) would help?

**Comment by Prestaworks** [comment]
Yes probobly, but that is not available on all hosts and it do from time to time cause other issues also.

**Comment by eternoendless** [comment]
IMO doing it on the PHP side would degrade performance, not improve it, because it would involve post-processing every request.

**Comment by Prestaworks** [comment]
Yes performance is important, I do believe the old code was built around running minify on the output from smarty? so the cached (compiled) templates where minified and that was not so heavy on the performance?

**Comment by eternoendless** [comment]
The compiled templates _could_ be minified but the inserted content won't, unless it's post-processed and stored in cache as well. 

Again, a quick google search didn't show any results advocating for removing whitespace for performance, which leads me to think it's a non-issue. If PageSpeed is complaining about  too big a number of nodes, I think the problem is probably related to your theme being too node-heavy as it is. For the record, I just had a peek at Amazon's markup and it's not minified.

As an additional argument **against** minifying HTML, be aware that doing so may have unintended side effects as the presence of whitespace nodes (regardless of their size) can be significant regarding the page rendering. [Check out this article for more details](https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33).

**Comment by Prestaworks** [comment]
A argument for this tech is that there are currently two modules on addons that do this, and it is better to have this feature in the core I think.
Also, the tech was available in 1.6 and was working really well? why did you guys remove it?

Amazon may sell alot, but their UX is really bad :)

**Comment by eternoendless** [comment]
> the tech was available in 1.6 and was working really well? why did you guys remove it?

I don't have a definite answer about this as this was done before me, but my guess is that it probably wasn't working well (probably for the reasons I stated above).

> Amazon may sell alot, but their UX is really bad 

This is about performance, not UX :wink:

**Comment by FeyaParis** [comment]
For info huge company like Google and Cdiscount use html minification for performance and it was a nice feature of ps 1.6.
Anyway to integrate it on 1.7 without a module ?

**Comment by matks** [comment]
> For info huge company like Google and Cdiscount use html minification for performance and it was a nice feature of ps 1.6.
> Anyway to integrate it on 1.7 without a module ?

I recently researched this recently, if you are looking for performance boost the true game changer is gzip compression for web server output. From multiple sources, HTML minification benefit is very minor compared to gzip compression.
One of the source I read was saying "If you are using gzip compression, then your benchmark will see no difference between raw HTML and HTML minified"

**Comment by Prestaworks** [comment]
I think google removed / deprecated the requirement to have minified html in the pagespeed test on their last update. They still seem to prefer that css and js is minified.

old info
https://developers.google.com/speed/docs/insights/MinifyResources

new info
https://web.dev/unminified-javascript/?utm_source=lighthouse&utm_medium=unknown
https://web.dev/reduce-network-payloads-using-text-compression/

**Comment by FeyaParis** [comment]
Ok thanks
