### ISSUE TITLE
Multishop - wrong Logo in other shop

### ISSUE THREAD

**Issue by MiiiMaaa** [PrestaShop/PrestaShop#13364]
**Describe the bug**
When I create a new multistore in Prestashop 1.6 and upload the logos, in other shops are wrong logos.
See on this site: http://forge.prestashop.com/browse/PSCSX-9243

**To Reproduce**
1. Go to 'Preferences' > 'Themes'
2. Add Logo file for 'Logo', 'Invoice', ...

**Screenshots**
http://fs5.directupload.net/images/171114/9e8jrcdi.jpg

**Additionnal information**
PrestaShop version: 1.6.1.17
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @MiiiMaaa,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.
Thanks for your understanding!

**Comment by MiiiMaaa** [comment]
This is very annoying, because already since 2017 there is this problem in Prestashop. We have built a multishop system, which we can not easily update to 1.7.
We'll probably have to look for a completely new system.

 

Von: khouloudbelguith [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. April 2019 15:12
An: PrestaShop/PrestaShop
Cc: MiiiMaaa; Mention
Betreff: Re: [PrestaShop/PrestaShop] Multishop - wrong Logo in other shop (#13364)

 

Hi @MiiiMaaa <https://github.com/MiiiMaaa> ,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.
Thanks for your understanding!

**Comment by matks** [comment]
@MiiiMaaa in incoming release 1.7.6 we have migrated "Theme&Logo" page to Symfony and reworked the code in that page, including how Multishop is handled. We restarted it from scratch and gave it a new implementation.

This might have solved your issue, would you check it ?
