### ISSUE TITLE
Export is not working in Brands and Brands addresses lists

### ISSUE THREAD

**Issue by rokaszygmantas** [PrestaShop/PrestaShop#13365]
**Describe the bug**
List export action for Brands and Brands addresses does nothing.

**To Reproduce**
1. Go to Catalog > Brands & Suppliers
2. Click on grid actions (wrench icon), then on "Export" https://prnt.sc/naj1qf
3. It reloads the page and does nothing. Same for addresses grid, which is below in the same page.

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13466
