### ISSUE TITLE
[1.6.1.23] Property "unit_price_ratio" does not set itself via webservice

### ISSUE THREAD

**Issue by Pipeze** [PrestaShop/PrestaShop#13369]
All is in the title, I can set any product property via the webservice except "unit_price_ratio" which is set to 0.000000 in any case.
I can only affect this via the backoffice but I need to use the webservice...

Possible duplicate of #9922 but not on the same version. Any fix ?

Library: PSWebServiceLibrary.php
PrestaShop version: 1.6.1.23
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Pipeze,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.
Thanks for your understanding!

**Comment by Pipeze** [comment]
Hi @khouloudbelguith,

Thank you for the answer, is there any way to get some support ?

**Comment by khouloudbelguith** [comment]
Hi @Pipeze,

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
