### ISSUE TITLE
Id changed in Team page

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#13373]
Describe the bug
In B.O > Advanced Parameters> Team page, id  "employee info icon"  changed.  This change broken the automatic test.

Team Page
The employee info icon changed from id = " #employee_info" to id = " #header-employee-container ". 

Thanks!

**Comment by marionf** [comment]
@ntiepresta Could please close it when it will be fixed in E2E test ?

**Comment by ntiepresta** [comment]
Ok, no problem @marionf

**Comment by marionf** [comment]
Fixed in E2E tests
