### ISSUE TITLE
Typo in German translation

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13388]
**Describe the bug**
Typo in German translation: "Aretikel"

**To Reproduce**

Install the shop with the German language then select a category and delete it

**Screenshots**
![branch1 76 0](https://user-images.githubusercontent.com/16067358/56044655-966fbb00-5d37-11e9-94a3-b3fa1fde3d43.png)

**Additionnal information**
PrestaShop version: 1.7.6.x

**Comment by matks** [comment]
@LouiseBonnard looks like a translation issue, can you confirm ?

**Comment by LouiseBonnard** [comment]
Indeed, I've had a look at the German translation project on Crowdin and fixed it. It should be solved in a couple of days. ;-)

**Comment by marionf** [comment]
@LouiseBonnard seems not fixed

**Comment by LouiseBonnard** [comment]
Hey Marion! From my side, it is corrected... have you updated the German language?

**Comment by marionf** [comment]
Yes, fresh install of German language

**Comment by LouiseBonnard** [comment]
Alright, I think I got it. I guess that it is because the shop is 1.7.6.x, the translation catalog has not been pushed on Crowdin yet and therefore has not retrieved the correction.

**Comment by marionf** [comment]
Fixed in Crowdin
