### ISSUE TITLE
Adding to cart very slow

### ISSUE THREAD

**Issue by scolink** [PrestaShop/PrestaShop#13380]
Hello,

I have a store, where i have 67 products, but i have around 500.000 cart rules, i know its alot of cart rules, but i really need them.

Im facing a problem when customer try to add products to the cart is very slow, probably some tests i made takes 40 a 60 seconds to add product to the cart, and when customer have for example 400 products in the cart, to add more products is more slower adding products, sometimes could take 1 minute to add every products, because is use a module of attribute grid by presta chageo where customers, can add all products and sizes/colors at same time an that is very slow ?

Someone could help me to try to fix this please, its very important to me ?

**Comment by khouloudbelguith** [comment]
Hi @scolink,

What is the exact version of PS did you used?

Thanks!

**Comment by scolink** [comment]
Hello @khouloudbelguith  sorry i forget to say the ps version 1.6.0.14

**Comment by khouloudbelguith** [comment]
Hi @scolink,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
That’s why I close it.
Thanks!
