### ISSUE TITLE
Positions - Internal Server Error

### ISSUE THREAD

**Issue by stoltzsp** [PrestaShop/PrestaShop#13399]
Following a Fresh install of v1.7.5.1, "Designs/Positions" results in 500 Internal Server Error.

Server information Linux #1 SMP Wed Mar 20 07:36:02 EDT 2019 x86_64 
Server software version: Apache 
PHP version: 7.1.28 
Memory limit: 256M 
Max execution time: 300 
Upload Max File size: 128M 
info_outline Database information 
MySQL version: 10.2.22-MariaDB-cll-lve 
MySQL engine: InnoDB

**Comment by khouloudbelguith** [comment]
Hi @stoltzsp,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by stoltzsp** [comment]
Server setup/Config:
Linux/Apache hosted server (hostking)
Prestashop:   1.7.5.1

[Edited by Khouloud]
note this is a clean prestashop install - for purposes of testing 1.7.5.1 (not a production server).

The problem can be recreated by accessing:  Design/Positions

**Comment by khouloudbelguith** [comment]
Hi @stoltzsp,

This is a public space.
You can provide me the credentials of your shop by email.
My address mail: khouloud-belguith.ext@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
@stoltzsp, you have to make sure that the line "define('_PS_JQUERY_VERSION_', '1.11.0');" is defined in "defines.inc.php"

Thanks to check and feedback.

**Comment by rdy4ever** [comment]
> Server setup/Config:
> Linux/Apache hosted server (hostking)
> Prestashop: 1.7.5.1
> 
> Server can be accessed:
> Edited by Khouloud
> 
> note this is a clean prestashop install - for purposes of testing 1.7.5.1 (not a production server).
> 
> The problem can be recreated by accessing: Design/Positions

You should delete this comment ASAP. **Never give up admin login on public pages.** 
@khouloudbelguith I think you should edit/delete the comment. It's been public for 2 days now.

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever, thanks a lot for your feedback.
@stoltzsp, I deleted the access note.
Let's be safe!
Thanks!

**Comment by stoltzsp** [comment]
When trying to access "Design/Positions" The following is shown in /var/logs/dev.logs:

[2019-04-21 16:30:36] request.INFO: Matched route "admin_modules_positions". {"route":"admin_modules_positions","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Improve\\Design\\PositionsController::indexAction","_legacy_controller":"AdminModulesPositions","_legacy_link":"AdminModulesPositions","_route":"admin_modules_positions"},"request_uri":"https://mydomain.co.za/index.php/improve/design/modules/positions/?_token=f-zzzzEr0p8Ds_hoEMUl1TPzt2C-s2bXEY310lkW3nk","method":"GET"} []

and under php error log:-

require(../public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory in ../public_html/vendor/composer/autoload_real.php on line 61

Any ideas..?

**Comment by khouloudbelguith** [comment]
@stoltzsp, did delete any folders before this bug occurred?
did you recreate the vendor folder?
Thanks!

**Comment by stoltzsp** [comment]
Sadly I am giving up on this. I suspect it has something to do with the particular webhost, as I have done a clean install on another domain/server and its working.  It is "impossible" or at least frustrating to try and troubleshoot if the webhost cant give access to the error and log files.  thanks khouloudbelguith for trying to assist.

**Comment by khouloudbelguith** [comment]
@stoltzsp, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
