### ISSUE TITLE
ps_orders colum curent_state not updated after ps_orders_history modification

### ISSUE THREAD

**Issue by mygitaccount2** [PrestaShop/PrestaShop#13390]
Hi Dear comunity,

i have to put my hand in ps_orders_history and remove manually all wrongfully posted order status,  that a very bad module did.

but now, my order list statuses are not updated they still have the old status while the order page itself is 100% accurate.

i pin point the issue where the "current_state" status is not update in ps_orders.
i dont think it is a bug as i updated the table order_history, but i like id someone can help me out to make thing right again , i guess it is just a  sql to run

thank you so much in advance.

**Comment by mygitaccount2** [comment]
anyone please .?

**Comment by mygitaccount2** [comment]
here is a screenshot that will help a bit 

https://www.screencast.com/t/VepHk0xxJ

thx

**Comment by khouloudbelguith** [comment]
Hi @mygitaccount2,

What is the exact version of PS did you used?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mygitaccount2,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
