### ISSUE TITLE
Exception on catalog prices rules page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13406]
**Describe the bug**
Exception on catalog prices rules page

**To Reproduce**
1. Go to Catalog > Discounts > Catalog prices rules
2. See error

**Screenshots**
![capture d'écran_1387](https://user-images.githubusercontent.com/13449658/56134386-c664cb80-5f8e-11e9-8212-fc2fa8137380.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed by #13409
