### ISSUE TITLE
Error when selecting some languages at first step of the installer

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13401]
**Describe the bug**
Try to select for example Italy, Espagnol or Deutsh at the first step of the installer
You will see the error below, but if you refresh the page it disappear and the installation is completed with success

![capture d'écran_1383](https://user-images.githubusercontent.com/13449658/56115151-0a41db80-5f63-11e9-9f08-5ba6f791217b.png)

I don't have it in French or English

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/13471
