### ISSUE TITLE
BO / Minor : Number of modules to update in notification icon is different from the actual modules detected

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#13416]
**Describe the bug**

Number of modules to update in notification icon
is different from the actual modules detected

**To Reproduce**
Problem appeared after upgrading a website from 1.7.4.3 to 1.7.5.1 with oneclick upgrade.
Clearing cache / cookie / config/XML files did not helped.

**Screenshots**
https://www.screencast.com/t/1YQ7WGtCZF

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @gennaris,

I did not manage to reproduce the issue when upgrading from PS: 1.7.4.3 to PS: 1.7.5.1 via the 1-Click Upgrade v4.7.0 - by PrestaShop.
I attached a screenshot.
![1751](https://user-images.githubusercontent.com/16067358/56202428-e9e55000-603a-11e9-9098-f2c6adca9839.png)

Thanks for check and feedback.

**Comment by gennaris** [comment]
Hi @khouloudbelguith ,
yes I also upgraded some other sites with no issues,
this is only happening on this particular website.
Let me know if I can provide some additional details to troubleshoot the problem.

**Comment by khouloudbelguith** [comment]
Hi @shakaran,

It seems that your issue is not a PrestaShop's core bug. 
I close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by gennaris** [comment]
After upgrading some more websites I discovered that this behaviour is always happening.

Simply if there are more than 6 modules to update, only the first 6 are shown in the upgrade list with no pagination , not very clear from the UX perspective.
