### ISSUE TITLE
Customized feature are not saved

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13419]
**Describe the bug**
Customized feature are not saved

**To Reproduce**
1. Go to Catalog > Products
2. Edit a product
3. Click on Add a feature, select a feature and fill the "customized value" field
4. Click on Save & refresh the page, it's not saved

**Screenshots**
![capture d'écran_1396](https://user-images.githubusercontent.com/13449658/56190734-290ba500-602b-11e9-845b-df2afe922a27.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by fezzit** [comment]
Same issue here, can't save custom features.
After saving everything seems OK, but the new feature is not stored in DB and doesn't show both in FE or BE.
This happens while editing an existing product. First insert of product was made with previous versions of PS and I had no problem in adding custom features.
Now im in 1.7.5.1 multistore

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I did not manage to reproduce the issue with the branch 1.7.6.x.
I attached a video record
https://drive.google.com/file/d/116e5eyczSxFR1Eqr13UW-pj0pa0aOttH/view
Could you please check if the issue happens again?
@fezzit, I checked in the PS1.7.5.1, it is Ok also.
Thanks!

**Comment by fezzit** [comment]
Thank you. Solved, but an issue remains IMHO.
You should fill the field for any installed language. If one language is left empty, it doesn't save the customer feature for all langiages.
I suggest to fix this, anyway, because it's common to insert content one language at a time.

**Comment by khouloudbelguith** [comment]
@fezzit, is it the same issue reported here: #9625?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith , Thank you I can't reproduce also on 1.7.6.x

**Comment by reanim8ed** [comment]
It is showed in the backoffice product edit page, yes, but the value isnt saved in the database.
I have described how to reproduce it here: https://github.com/PrestaShop/PrestaShop/issues/15018
