### ISSUE TITLE
Border of notification counter appears in tabs even when empty

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13422]
**Describe the bug**
On the pages using a tab system with notifications on it, we can see a small white line in the tab when the notification-counter is empty. It is the notification-counter border.

It should not appear if the counter is empty.

**To Reproduce**
1. Go to Modules > Module Manager
2. See the white line on the first tab

**Screenshots**
![Capture d’écran 2019-04-16 à 10 57 21](https://user-images.githubusercontent.com/47456895/56196142-907b2200-6036-11e9-83b5-9812d9e65821.png)

**Additional information**
List of pages having the issue:
* Shop parameters > General
* Shop parameters > Order settings
* Shop parameters > Customers
* Shop parameters > Traffic & SEO
* International > Localization
* Module > Module Manager
  
List of pages using the tab system but not having notifications (FYI):
* Shop parameters > Contacts
* Advanced parameters > Team
* Advanced parameters > Database
* International > Zones
* International > Taxes
* Design > Themes & Logos
* Module > Module catalog
* Catalog > Stock

PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by ghost** [comment]
**[REOPENED 07/17/2019]**

Despite the fix in the following PR : [#13425](https://github.com/PrestaShop/PrestaShop/pull/13425), the problem still happens in some pages.

At the moment it has been seen in the following pages:
- Advanced parameters > Database, on both the _SQL Manager_ and the _DB Backup_ tabs.
![Capture d’écran 2019-07-17 à 17 06 56](https://user-images.githubusercontent.com/47456895/61387055-a7d7de80-a8b5-11e9-8c1e-9c62942e2abd.png)

- TBC

**Comment by marionf** [comment]
@samuel-pires 

Your screenshot is on 1.7.6
The PR has been merged in develop, it will be fixed in 1.7.7

![capture d'écran_1867](https://user-images.githubusercontent.com/13449658/62362288-ed82e100-b51c-11e9-85ab-cd20ae98d114.png)

I think we can close it as it's fixed on develop

**Comment by ghost** [comment]
Thanks @marionf!
