### ISSUE TITLE
Can't drag & drop and disable categories

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13426]
**Describe the bug**
Can't drag & drop and enable/disable categories

**To Reproduce**
1. Go to Catalog > Categories
2. Try to drag and drop or disable a category
3. It doesn't work
4. It works if you rebuild assets

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
@marionf Should be fixed on 1.7.6.x now

**Comment by marionf** [comment]
Yes, thank you :)
