### ISSUE TITLE
Can't create a pack

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13421]
**Describe the bug**
Can't create a pack

**To Reproduce**
1. Go to Catalog > Products > New product
2. Select pack of product
3. Search an existing product
4. Nothing is found

**Screenshots**
![capture d'écran_1399](https://user-images.githubusercontent.com/13449658/56195972-4134f180-6036-11e9-937b-0fdf7425494a.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13431
