### ISSUE TITLE
productoutofstock email firstname and lastname var not displayed

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13424]
**Describe the bug**
productoutofstock email firstname and lastname var not displayed 

**To Reproduce**
Make sure modern email templates are configured
1. Go to Catalog > Products > edit a product
2. Click on the second tab and define a "low stock level"
3. Order this product in FO to have a stock < low stock level
4. See productoutofstock email received

**Screenshots**
![capture d'écran_1400](https://user-images.githubusercontent.com/13449658/56200678-827dcf00-603f-11e9-9171-2a45470b535b.png)

![capture d'écran_1401](https://user-images.githubusercontent.com/13449658/56200682-84479280-603f-11e9-85b3-3e8d358e383e.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by marionf** [comment]
@LouiseBonnard Do you think we should remove lastname and firstname as this email is sent to the merchant ?
Or should we keep theme ?

**Comment by LouiseBonnard** [comment]
Hi @marionf, let's keep the formula _Hi {firstname} {lastname},_ so that all of the PrestaShop core emails can start the same, even if sent to the merchant. :-)
