### ISSUE TITLE
Private comment in Order

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13428]
**Describe the bug**
when we add a private note on the order the message is not saved (only on order page. The private note is save when we add it on the customer informations page). 

**To Reproduce**
1. Go to order and display an order 
2. Add a private comment il the customer section of the order
3. Refresh the page or click on the name of the customer to see the customer informations page
4. See that there is no private note in the section.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by colinegin** [comment]
We need to check if this issue is related to the Customer page migration. Wdyt @matks ?

**Comment by marionf** [comment]
When you click on save, you have the error below in the console:

![capture d'écran_1577](https://user-images.githubusercontent.com/13449658/58163046-92628180-7c83-11e9-8fee-0108b7354e75.png)

![capture d'écran_1576](https://user-images.githubusercontent.com/13449658/58163059-97273580-7c83-11e9-9ee7-62de57705745.png)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13916

**Comment by 01park** [comment]
I just upgrade to the 1.7.6 version and now when I write a private note; for example before saving. After saving it adds strange characters to the text

![Screenshot 2019-07-11 at 19 13 16](https://user-images.githubusercontent.com/46492443/61074629-0b728f80-a410-11e9-8074-820151496806.png)


![Screenshot 2019-07-11 at 19 13 34](https://user-images.githubusercontent.com/46492443/61074638-10cfda00-a410-11e9-9a3c-e12fd51c9b39.png)

**Comment by marionf** [comment]
Hello @01park I created a new issue with your comment as this one is closed
