### ISSUE TITLE
allow ordering out-of-stock

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13447]
Prestashop 1.7.5.1 on debian php 7.2.17
Please see here https://nimb.ws/nSykKN
Only with "allow ordering our-of-stock" YES (arrow 1) on product there are labels (arrows 2-3)
Instead, whe allow ordering is NO, there are no labels (arrows 2-3)
Thank you

**Comment by khouloudbelguith** [comment]
@marionf, @colinegin, what do you think?

**Comment by marionf** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/12630

**Comment by marionf** [comment]
Hello @centoasa 

Your issue is a duplicate, please follow the issue referenced.
This has been fixed for 1.7.6.0

**Comment by centoasa** [comment]
Apply the fix, now works fine!
