### ISSUE TITLE
[SF Migration] Harmonize controller grid search action

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13448]
We have a generic and reusable [searchGridAction](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/CommonController.php#L335) in CommonController but some Controllers use their own `searchAction` rather than the reusable one.

For each Controller which has a custom searchAction, check if there is a valid need/reason for it, else make it use the generic `searchGridAction`.

**Comment by jolelievre** [comment]
In some cases it is justified by the presence of two grids in the same page I believe

**Comment by zuk3975** [comment]
Done in #18123 :heavy_check_mark: 

Some notes: 
- Multi-grid pages are the only ones left with custom search actions.
- Pages containing **grid** and **options form** with **constraints** should use `FilterFormFactoryFormActionDecorator` which fixes path by decorating it in case of form error and allows grid filters to work correctly (examples in `src/PrestaShopBundle/Resources/config/services/core/grid/grid_filter_form_factory.yml`)
- Common grid search action only posts to index route, so if custom action path is needed, then custom search method should be implemented.

**Comment by matks** [comment]
@zuk3975 Thanks for the hard work !

I'm sorry I think you went further than I thought, a bit too far 😓 
- the PR must aim for `develop` I think, it will be refused for `1.7.7.x`
- modifying the routing is 👍but removing the controller actions 🤔I dont know, is it against SemVer ? we might need to keep them (but deprecate them)

**Comment by zuk3975** [comment]
> @zuk3975 Thanks for the hard work !
> 
> I'm sorry I think you went further than I thought, a bit too far 
> 
> * the PR must aim for `develop` I think, it will be refused for `1.7.7.x`
> * modifying the routing is +1but removing the controller actions thinkingI dont know, is it against SemVer ? we might need to keep them (but deprecate them)

Separated prs.
* #18130 - targets 1.7.7.x. Changes for upcoming version only(1.7.7). Unusable actions are deleted.
* #18136- targets develop. Changes for older controllers. Unusable actions are deprecated instead of deleting.

**Comment by Progi1984** [comment]
#18130 is merged. Remain #18136
