### ISSUE TITLE
Module same category  duplicate the current product

### ISSUE THREAD

**Issue by smag-dev** [PrestaShop/PrestaShop#13441]
In the product single, module same category duplicate the current product!

In my debugs the problem is the comparation type:
$idProduct is integer;
$rawProduct['id_product'] is string;

![Screenshot from 2019-04-16 18-41-05](https://user-images.githubusercontent.com/14795225/56232281-4f0b6680-6078-11e9-92fd-9fa324f838d6.png)
![Screenshot from 2019-04-16 18-41-49](https://user-images.githubusercontent.com/14795225/56232322-621e3680-6078-11e9-9c4b-2657900460b5.png)

PrestaShop version: 1.7.4.4
PHP version: 5.6
Products in the same category version: 1.0.4

Best regards

**Comment by khouloudbelguith** [comment]
Hi @aguia10,

Could you please add steps to reproduce your issue in a new comment.

Thanks!

**Comment by smag-dev** [comment]
Hi @khouloudbelguith ,

Sorry but there is no mistake

Thanks!

**Comment by khouloudbelguith** [comment]
@aguia10, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
