### ISSUE TITLE
Help isn't displayed on add customer page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13449]
**Describe the bug**
Help isn't displayed on add customer page

**To Reproduce**
1. Go to Customers > Add a new customer
2. Click on Help
3. It's loading ....

**Screenshots**
![capture d'écran_1414](https://user-images.githubusercontent.com/13449658/56278584-ca1b5e00-6106-11e9-8dfb-49c266775b83.png)

![capture d'écran_1415](https://user-images.githubusercontent.com/13449658/56278663-eddea400-6106-11e9-9697-b3d211ec6707.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13763
