### ISSUE TITLE
BO: Tiny MCE editor do not work for all resolutions on manufacturers

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#13445]
**Describe the bug**
When resolution on the device is low, the tinyMCE editor will not work well, the icons will not scale down with the box and on some resolutions the language selector will place itself above the icons making it impossible to upload or edit images.

**To Reproduce**
1. Click edit on a manufacturer in BO
2. Scale down the browserwindow.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

I manage to reproduce the issue with PS:1.7.5.1 with a resolution 590px  x 981px.
I attached a screenshot.
![13445](https://user-images.githubusercontent.com/16067358/56279851-cf75aa00-6100-11e9-9832-93c3e1c56ddd.png)

This issue is added to our bug roadmap.

Thanks!

**Comment by NeOMakinG** [comment]
We've TinyMCE responsive theme now, it's simplified and working on mobile, we can close this issue :)
