### ISSUE TITLE
PS 1.7.6.x - Add header to the core contact.html email

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#13459]
**Describe the bug**
Core contact.html email needs to get the same header phrase than all of the other core emails, that is to say _Hi {firstname} {lastname},_ - right before writing _Message from a PrestaShop customer_.

**To Reproduce**
1. Go to Design > Email Theme
2. In the last frame (Email themes), click on the search icon to display all modern themes
3. Select the contact email, click on the html to see it

**Screenshots**
<img width="621" alt="Capture d’écran 2019-04-17 à 14 42 37" src="https://user-images.githubusercontent.com/32565890/56289855-39527b80-6122-11e9-94e8-362ec75e1de2.png">

<img width="611" alt="Capture d’écran 2019-04-17 à 15 06 01" src="https://user-images.githubusercontent.com/32565890/56289913-5a1ad100-6122-11e9-9bab-3e7b6c34c999.png">

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by jolelievre** [comment]
Hi @LouiseBonnard actually I think it's normal for this message. Unlike most other emails this one is sent to the shop administrator, not to the customer. So it is not supposed to be personalized (and the `{firstname}` and `{lastname}` variables are not available in this case).
In `classic` emails we already had this behavior.

**Comment by LouiseBonnard** [comment]
Indeed! But the point was to get all emails with the same header, notably because we were not fully sure of the destination (merchants or clients) for some of the emails.

**Comment by jolelievre** [comment]
Yes, except this template is different from the others because `{firstname}` and `{lastname}` are not injected in the template so we can't display them. This would require to update the controller code to change this behavior but it's not the purpose of the new email theme feature.

So I will close this issue ;)
