### ISSUE TITLE
Old admincustomer URL in notifications

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13450]
**Describe the bug**
Old admincustomer URL in notifications

**To Reproduce**
FYI you can enable/disable notifications in Advanced parameters > Administration
1. Create a new customer in FO
2. Click on the bell > Customers

**Please note this should be fixed on legacy AND on symfony pages**

**Screenshots**
![capture d'écran_1416](https://user-images.githubusercontent.com/13449658/56280798-44e67800-610b-11e9-9a22-52d874534c31.png)

![capture d'écran_1417](https://user-images.githubusercontent.com/13449658/56280971-b58d9480-610b-11e9-9a95-439714661a03.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13764
