### ISSUE TITLE
Field "id_lang" in emailsubscription table

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#13453]
In the e-mail database table the id_lang field must be entered to store the language of the user (guest) who registers to the newsletter.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Codencode,

What is the exact version of PS did you used?

Thanks!

**Comment by Codencode** [comment]
Hi @khouloudbelguith,
sorry, I rephrase the request:

In the table of the emailsubscription database the id_lang field should be inserted in order to register the language of the user (guest) who registers for the newsletter. This does not depend on the version of prestashop, but depends on the ps_emailsubscription module.

Thanks!

**Comment by Codencode** [comment]
My solution
https://github.com/PrestaShop/ps_emailsubscription/compare/master...Codencode:patch-1

**Comment by marionf** [comment]
Hello @Codencode 

I just tried and the 3 emails (newsletter_conf, newsletter_verif & newsletter_voucher) sent by emailsubscription module are well sent in the language selected in FO by the customer

![capture d'écran_1492](https://user-images.githubusercontent.com/13449658/57076269-89683b00-6ce9-11e9-82f2-abcf13d75cd8.png)

For some languages, emails are not completely translated, that's why you can have some content in English

**Comment by Codencode** [comment]
Hi @marionf,

the problem does not refer to the sending of the email, but it concerns the lack of the "id_lang" field in the "emailsubscription" table in the database.
This field is useful for knowing the language used by the user when registering for the newsletter.

Thanks!

**Comment by marionf** [comment]
Is there something that you would like to do with this information ?

**Comment by Codencode** [comment]
It is useful to send the newsletter in the user's language.
Thanks!

**Comment by marionf** [comment]
Thank you for your answer @Codencode !

I submited your idea [here](http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/37531810-save-the-language-of-the-subscribers-to-the-newsle) don't hesitate to vote for it. It will help us to prioritize all improvements ideas

**Comment by Codencode** [comment]
Thank you @marionf.

My solution is at the following link: https://github.com/PrestaShop/ps_emailsubscription/compare/master...Codencode:patch-1

**Comment by marionf** [comment]
Thanks for diving into this @Codencode 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by Codencode** [comment]
In https://github.com/PrestaShop/PrestaShop/tree/develop the modules folder is empty. However I have already made a pull request at the following link: https://github.com/PrestaShop/ps_emailsubscription/compare/master...Codencode:patch-1

**Comment by marionf** [comment]
Thank you @Codencode 

Seems the PR isn't yet created. 

![capture d'écran_1493](https://user-images.githubusercontent.com/13449658/57147843-bdfef400-6dc8-11e9-9152-e0363795b8c7.png)

Could you create it ? It will allow us to review and test it :)

**Comment by Codencode** [comment]
Ok.
https://github.com/PrestaShop/ps_emailsubscription/pull/34

Thanks!
