### ISSUE TITLE
Calendar not displayed correctly on customers page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13469]
**Describe the bug**
Calendar not displayed correctly on customers page

**To Reproduce**
1. Go to Customers > Customers
2. Click on date filter
3. See error

**Screenshots**
![capture d'écran_1431](https://user-images.githubusercontent.com/13449658/56353495-caccf680-61d1-11e9-92d7-6e30514da7f6.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13528
