### ISSUE TITLE
Some native modules wordings do not have domain

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#13476]
**Describe the bug**
When I grep usage of `$this->l(` in the `modules` directory, I see that many native modules are missing the use of domain.

In those cases, either:

- The translation is not working
- The translation is handled by the legacy translation system (if there are translations in the module's `translations` directory)
- The translations have been extracted into the `messages` domain

In any case, **all native modules** should be translated using the new system, that is, using `trans()` and translation domains.

Failure to do so will produce unexpected behavior when extracting the translation catalog and when using the Translations BO page, **specially** once the new implementation of legacy translations will be merged.

In the new implementation, all calls to `$this->l()` without domain will be interpreted by the extractor as a "legacy module call", and therefore the domain will be inferred as `Modules.Themodulename.Themodulename` instead of `messages`.

**To Reproduce**

1. Search for `$this->l(` on the `modules` directory
2. Identify the uses where the method call does not specify a second parameter
3. Look up the module name in `composer.json`
4. If the module is found there (it's native), then [it should be using a translation domain](https://devdocs.prestashop.com/1.7/development/internationalization/translation/translation-domains/#modules)

**Screenshots**

![Screenshot 2019-04-18 at 14 35 59](https://user-images.githubusercontent.com/1009343/56361449-a845d800-61e7-11e9-9fe3-8665c656d5b2.png)

![Screenshot 2019-04-18 at 14 36 13](https://user-images.githubusercontent.com/1009343/56361454-aaa83200-61e7-11e9-88be-e8dff0147dd4.png)

**Comment by colinegin** [comment]
@LouiseBonnard what do you think ? Is it critical ?

**Comment by LouiseBonnard** [comment]
It would be great! Each wording needs to be localized. But shouldn't it fall into the `Modules.Themodulename.Admin`domain instead?

**Comment by eternoendless** [comment]
@LouiseBonnard it would depend on whether the wording already exists in the core translations or not, wouldn't it? Also the domain would change according to whether it's meant for the front office or the back office.

**Comment by LouiseBonnard** [comment]
Of course! How can I help?

**Comment by LouiseBonnard** [comment]
Hello @eternoendless, I've reproduced the process described in this issue and found where wordings were missing localization (in native, API-pushed and preinstalled modules). I've counted about two hundred strings to localize. It is not that much. In this case, I'd prefer to add the right localization myself since there can be duplicates or even more relevant localizations.

I only talk about adding domains here, but this could be part of a bit bigger project regarding native modules: it could be the occasion to add the new icons @TristanLDD designed last year, and to update their description as reworked slightly last year as well - with the purpose to add a better description of the native modules on Addons. We will probably need the help of one developer at first, to show us how to do, but then we will be able to 'chain-update' all these small elements. What do you think?

**Comment by ghost** [comment]
@LouiseBonnard You will be able to do the work? Or you need help from a developer?

**Comment by LouiseBonnard** [comment]
I'm currently doing it. Half of the work has been done so far, pull requested and reviewed for some parts. ;-)

**Comment by LouiseBonnard** [comment]
Okay, one last thing is: should I do the same for both GDPR and Theme Custo modules? I know that they are working differently since they come with their own translations... it is only ten strings to localize so I can handle it quickly but I just wanted to know before. ;-)

**Comment by LouiseBonnard** [comment]
Work has been done, please find below the list of the pull requests to review:

- [x] [Cron Tasks Manager](https://github.com/PrestaShop/cronjobs/pull/49)
- [x] [Date Of Delivery](https://github.com/PrestaShop/dateofdelivery/pull/18)
- [x] [Merchant Expertise](https://github.com/PrestaShop/gamification/pull/70)
- [x] [PrestaShop Security](https://github.com/PrestaShop/prestafraud/pull/12)
- [x] [Email Alerts](https://github.com/PrestaShop/ps_emailalerts/pull/25)
- [x] [Emails Manager](https://github.com/PrestaShop/ps_emailsmanager/pull/10)
- [x] [MBO, part 1](https://github.com/PrestaShop/ps_mbo/pull/93)
- [x] [MBO, part 2](https://github.com/PrestaShop/ps_mbo/pull/94)
