### ISSUE TITLE
Part of the BO is in English, the other in French

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#13475]
**Describe the bug**
I just installed Prestashop 1.7.5.1 locally and when I go in the B.O, I have a part in English (as the left side menu). The rest, the content, the central part, is in French.

I went to Advanced Settings> Team, on my account, it's in French

After searching the forum Prestashop, I found similar topics where it was answered to go in International> Localization and import the French localization pack.

I did it several times, but it did not help.

Do you have an idea?

**To Reproduce**
I don't know how reproduce it; I just installed Prestashop 1.7.5.1 locally

**Screenshots**
![bo_presta_1751_in_english](https://user-images.githubusercontent.com/48359467/56360927-5badcd00-61e6-11e9-8f65-c5f50aaadd84.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 5.6.40 (via Xampp on Mac OS X Mojave)

**Comment by khouloudbelguith** [comment]
Hi @shakaran,

what is the exact language/country did you installed this shop?
In the BO, what is the exact language used by your employee?
Thanks!

**Comment by wikao2** [comment]
I just found the solution for those who have the same problem as me.

You have to go to International> Translations and in the section "Add / Update a language" click on the "Add or Update language" button

It grinds a moment then the page is recharged with everywhere in French.

I hope it would help.

Have a nice day ;)

**Comment by khouloudbelguith** [comment]
@wikao2, thanks for your feedback.
Feel free to open a new when needed.
Thanks!

**Comment by wikao2** [comment]
In fact, I realized that it always does when I activate the debug mode BEFORE installing Prestashop (to have the option Do not create the products demo).
Moreover, there is no other way to do (to have the option Do not create the products demo Prestashop installation)?

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Yes, when debug mode enabled, you can disable the installation of the demo products.
After the installation, you can also, install the `pscleaner` module, this provides options to delete everything from the catalog, orders, and customers and also options to check and fix the database integrity and to clean and optimize the physical storage of data
Thanks!
