### ISSUE TITLE
Can't close helper card on CMS page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13474]
**Describe the bug**
Can't close helper card on CMS page

**To Reproduce**
1. Go to Design > Pages
2. Click on Close
3. It's not closed

**Screenshots**
![capture d'écran_1432](https://user-images.githubusercontent.com/13449658/56358813-15556f80-61e0-11e9-9bfa-d9c5b9c3f0fb.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by zuk3975** [comment]
I have checked this issue, and it seems it only requires to rebuild assets to work.
@matks, I guess it's not worth separate PR as it should be fixed automatically later once rebuilding assets in another PR's?

**Comment by matks** [comment]
@marionf Should be fixed on `1.7.6.x` now 😉

**Comment by marionf** [comment]
Yes, it's all good :+1:
