### ISSUE TITLE
Automatically assign a "default" image to a product combination

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13479]
### Is your feature request related to a problem? Please describe.
Currently, when creating combinations for a product, no images are assigned to the combinations.
You have to manually select which image to assign to each combination.
And the combinations don't have a "default" image.

Why is it a problem?
* If you don't assign an image to a combination, its thumbnail is broken anywhere it should appear in the Backoffice (dropdown when creating a pack for instance).
* When creating combinations which don't need a particular image, sizes (S, M, L, ..) for instance, you still have to manually assign an image = bad UX.
* We need to have a "default" image per combinations for facetedsaerch
Like this, we will be able to display the good product image corresponding to the filter made in front-office

[See video for the thumbnail issue](https://drive.google.com/file/d/1dJOK4BN707GuMS_jQkOK34xufjRPXz2q/view?usp=sharing)

### Describe the solution you'd like

[US] As a user, when creating product combinations, I want my combinations to be automatically assigned to the product cover image as "default" so that I don't have to assign it manually to every combination.

When creating new combinations
For each combination
If at least one image has been uploaded to the product page assign the cover image to the combination and make it the default one.
Else don't assign an image to the combination (same as current behavior)

Thern the merchant should be able to change later the "default" image of each combination.
You can have only one "default" image per combination

**Attention**
These behaviors only apply to combination creation done in the BO.
If combinations are imported (creation or modification), these behaviors should not apply, in this case, the default behavior should be the same as today, no image assigned unless it is assigned in the import file.

Thanks,
Ping me if you have any question

**Comment by ghost** [comment]
[EDIT 11 sept 2019] I Removed the solution 2

---
@PrestaShop/prestashop-core-developers 
Feedback wanted

Hi guys, can someone have a look at the 2 solutions and tell me if number 2 seems feasible?

**Comment by MatShir** [comment]
Done on the new product page
