### ISSUE TITLE
Undefined offset in front office when we add a language 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13483]
**Describe the bug**
When I try to use a language that I add in the back office there is an error in the front office Undefined offset

**To Reproduce**
1. Go to 'back office-> International-> Languages
2. Add a language 
3. Go to the front office and select the language you just add

**Screenshots**
![Capture d’écran 2019-04-19 à 09 12 39](https://user-images.githubusercontent.com/3034677/56412231-c06b3500-6283-11e9-98fd-91439828e6f0.png)

![Capture d’écran 2019-04-19 à 09 19 13](https://user-images.githubusercontent.com/3034677/56412388-38395f80-6284-11e9-86a5-a905e69a1d9c.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by tomlev** [comment]
hi @sarahdib 
could you please retry with latest 1.7.6.x version ?
This bug should have been fixed recently
On my local env I didn't manage to reproduce the issue.

**Comment by tomlev** [comment]
probably fixed by https://github.com/PrestaShop/PrestaShop/pull/13261

**Comment by marionf** [comment]
@tomlev 

I still have it on 1.7.6.x branch

![capture d'écran_1443](https://user-images.githubusercontent.com/13449658/56565287-510d8200-65b0-11e9-8879-21ba7323e439.png)
