### ISSUE TITLE
1-click upgrade 1.7.5.1 - blank screen after update from 1.7.4.2 to 1.7.5.1

### ISSUE THREAD

**Issue by Prestashopnewbie** [PrestaShop/PrestaShop#13491]
Just started to upgrade our prestashop from 1.7.4.2 to 1.7.5.1, using 1-click upgrade module. 

The upgrade seems to work fine (just 3 warnings about the d-base). 

Unfortionally the upgrade didn`t preform well, the shop and backoffice are returning a blank http 500 error screen. 

 

When I try to enable debug modus I get the following message:

(1/1) FatalThrowableErrorCall to a member function getRequestUri() on null
--
in Dispatcher.php line 533
at DispatcherCore->setRequestUri()in Dispatcher.php line 60
at Dispatcher->__construct(object(Request))in Dispatcher.php line 207
at DispatcherCore::getInstance()in index.php line 99

In the logs I did found an exeption: 

*ERROR*     v1.7.5.1    2019/04/19 - 12:30:02: Cannot select any valid SQL engine. at line 302 in file classes/db/Db.php

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Thanks for your report.
I did not manage to reproduce the issue after upgrade from PS1.7.4.4 to PS1.7.5.1 using the 1-click upgrade v4.6.0.
I attached a video record.
https://drive.google.com/file/d/1Z0nLQ9ED8v6utyYGIpWYjh5o2oG1JifR/view
do you have any override file which is not compatible?
Thanks to check & feedback.

**Comment by Prestashopnewbie** [comment]
Yes u are right, I've a dispachter override wich is not compatible, related to the module clean url - from vekia.

**Comment by khouloudbelguith** [comment]
@Prestashopnewbie, Thanks for your feedback.
As it's not the module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
