### ISSUE TITLE
Prestashop 1.7.X actionCustomerAccountAdd not firing when user making register

### ISSUE THREAD

**Issue by kshirodpatel** [PrestaShop/PrestaShop#13507]
**Describe the bug**
I am using the hook actionCustomerAccountAdd in one of my custom module. When user makes register I want to get the details of the user. Thats why I have used the hook actionCustomerAccountAdd. But its not firing at all. But the same code works in Prestashop 1.6.X. 

**To Reproduce**
Use actionCustomerAccountAdd in any module and try to make register. You will not get any data in that hook.

**Comment by khouloudbelguith** [comment]
Hi @kshirodpatel,

Could you please provide me a demo module to check with it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by kshirodpatel** [comment]
Hello @khouloudbelguith ,

I have sent you the module. Please check it. Its just a basic module.

**Comment by khouloudbelguith** [comment]
Hi @kshirodpatel,

I just received the email.
I will check & feedback.
Thanks a lot!

**Comment by khouloudbelguith** [comment]
@kshirodpatel, it is OK.
I tried with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1niJmAAWgTjOlPQgEGxdKdzraledUFV4u/view
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @kshirodpatel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
