### ISSUE TITLE
Possibility to negate checkbox filter

### ISSUE THREAD

**Issue by christian-predebon** [PrestaShop/PrestaShop#13500]
Hello,
in order to use a different type of filter in the catalog page, it would be interesting to add the possibility to negate a specific filter among those available with checkbox.
Let me explain with an example.

In my shop I need to filter a catalog for the absence of an allergenic ingredient, created using features.
It would be interesting to negate this condition and return the list of the product that not contain a specific feature.

Thank you

**Comment by khouloudbelguith** [comment]
Hi @ChristianPredebon,

Thanks for your report.
To better understand your issue, in the FO => Catalog page, with the faceted search block, you need to filter all products which they do not have the specific feature?
Thanks!

**Comment by christian-predebon** [comment]
Hi @khouloudbelguith,
That's exactly what I want to achieve.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @ChristianPredebon,

Thanks for your feedback.
For your information, we are currently reworking this module.
@marionf, @colinegin what do you think of his suggestion?
THanks!

**Comment by marionf** [comment]
@ChristianPredebon 

> In my shop I need to filter a catalog for the absence of an allergenic ingredient

You can create a feature without this ingredient

**Comment by christian-predebon** [comment]
@marionf 
Of course, I can create a feature named for instance "w/o eggs, w/o soy" and then add this feature to an article that not contains this ingredient. It would work as well but I think it's a workaround.
It would be better to have a solution more straight, in this case I could name the feature "Not contains" and then flag a single ingredient to keep out it from the selection.

Thanks!

**Comment by marionf** [comment]
@ChristianPredebon I added your suggestion [here](http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/37878268-possibility-to-negate-checkbox-filter) to see if other people are interested by this feature

**Comment by marionf** [comment]
Hello @ChristianPredebon 

As a workanround is available and there were only one vote for this, we don't plan to integrate this improvement for now
