### ISSUE TITLE
errors/maintenance.tpl does not include custom.css in head

### ISSUE THREAD

**Issue by Jeff-A-Again** [PrestaShop/PrestaShop#13505]
**Describe the bug**
The errors/maintenance.tpl does not include  themes/child_classic/assets/css/custom.css when it is present on the file system, making it impossible to easily use custom CSS on the maintenance page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin -> Configure -> Shop Parameters -> Maintenance
2. Enable Maintenence Mode
3. Check the HEAD content that is rendered.
4. It does not include custom.css

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

I'm a newbie to PrestaShop - I checked maintenance.tpl - that uses _partials/stylesheets.tlp - and a PHP $stylesheets variable that is passed in. I'm not sure that I want to dicker with the stylesheet logic in the PHP application.

Please fix so that custom.css is included when present on the file system.
Thank you

**Comment by rdy4ever** [comment]
maintenence.tpl uses assets/css/error.css stylesheet, so that’s the one you’d want to edit to customize the page.

**Comment by Jeff-A-Again** [comment]
No - modifying the upstream is an anti-pattern - it's a bug that child theme css is not already included - esp. when it is included elsewhere.

**Comment by Jeff-A-Again** [comment]
Until the bug is fixed, the best work-around I've found is:

```
cd themes/
mkdir -p child_classic/templates/_partials/
cp classic/templates/_partials/stylesheets.tpl child_classic/templates/_partials/
vi child_classic/templates/_partials/stylesheets.tpl
  added this line after the first {foreach} loop
  <link rel="stylesheet" href="/themes/child_classic/assets/css/my.css" type="text/css" media="all">
vi child_classic/assets/css/my.css
  create my custom css 
```
This is a better solution because I get to keep all my CSS tweaks in one place, without touching the contents of the classic theme.

This is the first time I've looked at PrestaShop code - it has lots of obvious issues, looks like no-one is doing code reviews? An example - I had to reimplement stylesheets.tpl instead of just using inheritance because the block-name for stylesheets is in the layout template - now there's a clear anti-pattern!

**Comment by khouloudbelguith** [comment]
Hi @Jeff-A-Again,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.1.
I tried with this child theme 
[child.zip](https://github.com/PrestaShop/PrestaShop/files/3103509/child.zip)
In the `custom.css` file, I added these lines

```
#layout-error h1 {
    font: 24px sans-serif;
    color: #b333ca;
    padding: 0 0 14px 0;
    margin: 0 0 19px 0;
}
```

But in FO => when maintenance enabled => those changes are not considered
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by henri9813** [comment]
Hello,

Do you have news about this ?

Best regards

**Comment by juliendombret** [comment]
I have the same probleme in multishop.
the patch is : 

in frontController -> displayMaintenancePage -> 

**$styles = $this->getStylesheets();**
                $this->context->smarty->assign([
                    'urls' => $this->getTemplateVarUrls(),
                    'shop' => $this->getTemplateVarShop(),
                    'HOOK_MAINTENANCE' => Hook::exec('displayMaintenance', []),
                    'maintenance_text' => Configuration::get('PS_MAINTENANCE_TEXT', (int) $this->context->language->id),
                    'stylesheets' => **$styles**,
                ]);
