### ISSUE TITLE
Pagination system is broken on Grid pages

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#13511]
**Describe the bug**
Go the the logs page in 1.7.5.1, create enough log entries to get a second page available.
Click on "2" and you will get this exception page (in dev mode).

![exeption](https://user-images.githubusercontent.com/1247388/56471628-00354680-6455-11e9-8a56-d3a1f7cc7772.png)

**To Reproduce**
See the previous section.

**Additionnal information**
PrestaShop version: 1.7.5.1+ (also broken in develop branch)
PHP version: 7.2 (but unrelated afaik)

But after installing again the shop, the error disappear

**Comment by khouloudbelguith** [comment]
Hi @mickaelandrieu,

I did not manage to reproduce the issue with PS1.7.5.1. / 1.7.6.x branch
Debug mode is enabled, I tried with PHP 5.6.40 & PHP 7.2.14.
I attached a video record.
https://drive.google.com/file/d/14-AmVkSv8tSl8i1mhHc9_u-e8zuPBTEu/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @mickaelandrieu,

I did not manage to reproduce the issue with PS1.7.6.0beta1
https://drive.google.com/file/d/121Y20pk0pmRMkayFHJt3L4le1q6cSvIV/view
I close the issue.

Thanks!
