### ISSUE TITLE
Hook actionCartUpdateQuantityBefore replaced by obsolete hook actionBeforeCartUpdateQty

### ISSUE THREAD

**Issue by psyray** [PrestaShop/PrestaShop#13518]
**Describe the bug**

During module installation with the new **actionCartUpdateQuantityBefore** hook, this one is replaced by the obsolete **actionBeforeCartUpdateQty** which [was commented](https://github.com/PrestaShop/PrestaShop/blob/199d56fdd616b52a9801e7f37750179b94952331/classes/Cart.php#L1351) in the cart class.
So the new hook **actionCartUpdateQuantityBefore** is never called.

This is caused by 2 bad behaviours during the hook registering of the module install :

-  the alias contained in the [hook_alias](https://github.com/PrestaShop/PrestaShop/blob/2460b01ad3dcc7af10349a6f60ea242b8bb767de/install-dev/data/xml/hook_alias.xml#L320) table
- the call to the deprecated [getRetroHookName](https://github.com/PrestaShop/PrestaShop/blob/f2a7da28d55f884f5f9758dd56a9ca632b96f41e/classes/Hook.php#L496) method during hook register

**To Reproduce**

1. Install a module with the **actionCartUpdateQuantityBefore** hook position
2. Hook position is replaced by **actionBeforeCartUpdateQty** during module installation

**Fix**

- Delete the alias record  in the **hook_alias** table
![image](https://user-images.githubusercontent.com/1230954/56518041-b32d9f00-653e-11e9-8ff3-3f6f1aad4456.png)

OR

- Uncomment [this line](https://github.com/PrestaShop/PrestaShop/blob/199d56fdd616b52a9801e7f37750179b94952331/classes/Cart.php#L1351)

OR

- Stop using the [getRetroHookName](https://github.com/PrestaShop/PrestaShop/blob/f2a7da28d55f884f5f9758dd56a9ca632b96f41e/classes/Hook.php#L496) method

Don't know what's the correct fix to use to provide a PR

**Additionnal information**
PrestaShop version: 1.7.5.0 **fresh installed, not upgraded**
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @psyray,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
In my module, I used the `actionCartUpdateQuantityBefore` hook.
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/3106491/mymodule.zip)
In the BO => Design => Positions => the `actionbeforecartupdateqty` is used.
![image](https://user-images.githubusercontent.com/16067358/56564900-fae81100-65a6-11e9-85c0-5389ec254626.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by psyray** [comment]
I can't decide what's the good fix because I don't know your strategy about removing deprecated function.

For me the best fix is to remove the call to the [getRetroHookName](https://github.com/PrestaShop/PrestaShop/blob/f2a7da28d55f884f5f9758dd56a9ca632b96f41e/classes/Hook.php#L377) function at [this line](https://github.com/PrestaShop/PrestaShop/blob/f2a7da28d55f884f5f9758dd56a9ca632b96f41e/classes/Hook.php#L496).
This could prevent another bug.

The more quickly is to uncomment [this line](https://github.com/PrestaShop/PrestaShop/blob/199d56fdd616b52a9801e7f37750179b94952331/classes/Cart.php#L1351).

You need to decide.

**Comment by eternoendless** [comment]
I believe this one is fixed by this PR: #12578

**Comment by psyray** [comment]
@eternoendless 
Yes it fixes the issue. Well done !
Thanks
