### ISSUE TITLE
Please add support for PostgreSQL

### ISSUE THREAD

**Issue by renkam** [PrestaShop/PrestaShop#13512]
I would like to use PostgreSQL instead of MySQL
PostgreSQL seems to behave better on heavy load.

**Comment by khouloudbelguith** [comment]
Hi @renkam,

This link could be helpful
https://stackoverflow.com/questions/23691112/prestashop-and-postgresql
About the PostgreSQL support @eternoendless, @PrestaShop/prestashop-core-developers what do you think?

**Comment by matks** [comment]
Hi @renkam indeed PostgreSQL is known for having better results for heavy workload in comparison to MySQL.

It would be great to have prestashop supporting both MySQL and PostgreSQL however we have already a lot of major projects in progress, and the work needed to make this happen is huge.

I am sorry but although this is a relevant feature and, as a developer, I consider this an interesting challenge, I dont think we can do it, at least now. Maybe in 1 or 2 years when our major projects are done.

However as this is an opensource project, there might be external contributions to make it happen 😉 but the Core team cannot tackle this topic.

**Comment by renkam** [comment]
Hi @khouloudbelguith, I saw that one before writing this issue. I thought it is not relevant as it mentions version 1.6 and from what I know it is very different from current 1.7
@matks Thanks for explanation. I understand. Unfortunately I am not a PHP fan. I was hoping that it might be possible to make some db framework switch that support both PostgreSQL and MySQL interchangeably.

**Comment by eternoendless** [comment]
Hi @renkam 

It's currently possible to switch the database adapter from MySQL to PostgreSQL, but most SQL queries in PrestaShop have been written with MySQL in mind and are not portable. Furthermore, it's very difficult to optimize queries for more than one engine, so unfortunately I don't see this happening in the future.

**Comment by matmicro** [comment]
Added support for PostgreSQL #32937 

Does this PR means Prestashop will be fully compatible with postgresql ?

**Comment by sikl0** [comment]
I'm very disappointed with the fact that the core team didn't think about making pgsql the main db driver for prestashop. I experienced a huge slowdown in medium and small shops when mysql was filled with thousands of orders. I bet that pg would handle this a lot easier.

**Comment by Progi1984** [comment]
@matmicro Sorry. I didn't see your sentence about my PR. It was a mission from one of my clients (and not in m'y job for PrestaShop). But when I announced the price to my client he refused. May be many clients for the same mission Could be possible.
