### ISSUE TITLE
Final retail price is not displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13516]
**Describe the bug**
IN the BO => Product page => Pricing Tab, the Final retail price is not displayed

**To Reproduce**
Steps to reproduce the behavior: New clone from GitHub 1.7.6.x branch
1. Go to BO => Product Page
2. Edit a product
3. Go to the Pricing Tab
4. See error => The final retail price is not displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/56513171-7e631d00-6529-11e9-9670-1fb17df6f33a.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
ping @nesrineabdmouleh

**Comment by mbadrani** [comment]
Detected by Test Automation Suit Full/02_product thanks @nesrineabdmouleh & @khouloudbelguith

**Comment by colinegin** [comment]
Is it really critical ? It does not display the final price, but is this price still taken into account ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

In our documentation http://doc.prestashop.com/pages/viewpage.action?title=Severity+Criteria&spaceKey=QA, if an issue breaks the Auto Tests so it is critical.
Thanks!

**Comment by colinegin** [comment]
As seen with Mehdi, as those auto tests are going to be changed, this is not a critical but major issue. I've changed the label :) Thanks !

**Comment by PierreRambaud** [comment]
FYI: javascript functions `formatNumber`, `formatNumberCldr` and `formatCurrency` were not longer working. The following pull request must fixed it: #13665
