### ISSUE TITLE
Product settings hints misbehave when loading tabs with ajax

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#13513]
**Describe the bug**
In product edit form `Basic settings` tab the hints stays opened when going to another tab through references in `Quantity` or `Price` sections.

**To Reproduce**
1. Go to Catalog > Products > edit 
2. Click on any hint ( marked as `?`) in `Basic settings` tab.
3. Click on `Quantities` or `Pricing` reference in in corresponding sections( `Quantity` or `Price`) on right side of the screen. (screenshot 1)
4. You will be moved to another tab, but the hints stays opened. (screenshot 2)

**Screenshots**
1.
 ![Screenshot from 2019-04-22 15-43-08](https://user-images.githubusercontent.com/31609858/56500946-844f0300-6515-11e9-963c-b3c952f4c565.png)
2.
 ![Screenshot from 2019-04-22 15-44-29](https://user-images.githubusercontent.com/31609858/56500983-af395700-6515-11e9-95f4-c6fb7fc4b492.png)
**Additionnal information**
PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I did not manage to reproduce the issue with the branch 1.7.6.x & the PS version 1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/174JT8Z-nW2fK6WGwsjY4e1HzfTi8zs8o/view
What is the exact version PrestaShop did you use?
Thanks!

**Comment by zuk3975** [comment]
> Hi @zuk3975,
> 
> I did not manage to reproduce the issue with the branch 1.7.6.x & the PS version 1.7.5.1.
> I attached a video record.
> https://drive.google.com/file/d/174JT8Z-nW2fK6WGwsjY4e1HzfTi8zs8o/view
> What is the exact version PrestaShop did you use?
> Thanks!

Hi, im using 1.7.6.x and actually was on develop branch, but to reproduce the bug you have to press the references in the right (not the tabs in top. I added screenshot bellow).
![Screenshot from 2019-04-22 18-50-10](https://user-images.githubusercontent.com/31609858/56509491-cedd7900-652f-11e9-8536-1cf893ddee8c.png)

**Comment by khouloudbelguith** [comment]
@zuk3975, thanks for these clarifications.
Yes, now I manage to reproduce the issue with PS1.7.4.4, PS1.7.5.1 & The 1.7.6.x branch.
I’ll add this to the debug roadmap.
Thanks!
