### ISSUE TITLE
 Downloadable product email: Not sent

### ISSUE THREAD

**Issue by lilianamc** [PrestaShop/PrestaShop#13514]
**Describe the bug**
The email for a  downloadable product is not sent

**To Reproduce**
1. Create a downloadable product
2. Do the checkout process 
3. You don't get the email to download the virtual product :( 

**Screenshots**
As you can see the configuration of the virtual product is ok . Please see image https://imgur.com/a/G6YhMJu 

**Additional information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @lilianamc,

For this order, it should be valid (the status of the order id payment accepted for example), so you have the email to download the virtual product 
Mail page
![image](https://user-images.githubusercontent.com/16067358/56508899-743b2180-651d-11e9-8870-56050495241a.png)
Order History page
![image](https://user-images.githubusercontent.com/16067358/56508904-77cea880-651d-11e9-8c3d-be7a6387b98f.png)

Thanks to check & feedback

**Comment by lilianamc** [comment]
Hi @khouloudbelguith 

I did all that. 

It is a pack product. 

Please see the images. 

https://imgur.com/a/yd0VC1H
https://imgur.com/a/mDfs969
https://imgur.com/a/AfN0ji4

**Comment by khouloudbelguith** [comment]
@lilianamc, the type of product is a pack or virtual product?
The first screenshot from your product page 
![image](https://user-images.githubusercontent.com/16067358/56509560-3e973800-651f-11e9-9e7c-068fd11258af.png) => it is from a virtual product
Thanks!

**Comment by lilianamc** [comment]
Hi @khouloudbelguith 

It is combination. 

In order to sell more I'm given away 2 virtual products for the purchase of a bracelet. So I created a pack products. 
1 standard product
2 virtual products

As you can see here 
Image 1 : https://imgur.com/a/Yw170mD
Image 2 : https://imgur.com/a/YVARTSm

**Comment by khouloudbelguith** [comment]
@lilianamc, it is impossible to add virtual products to a pack.
For more information, you can follow our official documentation: http://doc.prestashop.com/display/PS17/Managing+Products#ManagingProducts-Creatingapackofproducts
![image](https://user-images.githubusercontent.com/16067358/56512500-76a27900-6527-11e9-8de8-898ad78ce98a.png)
Thanks to check & feedback.

**Comment by lilianamc** [comment]
Ok :( 

Thank you very much @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@lilianamc, I close the issue.
Feel free to open a new one when needed.
Thanks!
