### ISSUE TITLE
filter panel based for brand specific page.

### ISSUE THREAD

**Issue by nirav-nanda** [PrestaShop/PrestaShop#13521]
hello developers,

some days ago i have raised  a issue regarding faceted search in brand specific page #9684, but lately i got to know that faceted search serves  to the category specific filters, if we want filters from  any particular brands , like one brand have more than one categories and if user wanted to know how many categorized product have under the same brand , we can't show it. this feature is missing. 

ex. check this page. https://shreemahavir.in/brands
( site using ps ver. 1.7.5 )

@khouloudbelguith ma'am have suggested me to open a new "Feature request" for this.

hence if this functionality is added in newer version, it would be very user friendly for visitors to know about brands having all different categories under a single page.

regards
nirav nanda

**Comment by khouloudbelguith** [comment]
Hi @nirav-nanda,

Thanks for your report.
In the FO => home page => you can filter by brand
![image](https://user-images.githubusercontent.com/16067358/56580240-0698ff00-65ca-11e9-82a2-7a87f85fb429.png)
=> OK => then you have the number of products displayed in each category
![image](https://user-images.githubusercontent.com/16067358/56580286-25979100-65ca-11e9-9da7-6da85c8e6f4e.png)
In this screenshot => you have for the filter with "Brand: Graphic Corner" we have 3 products in the Accessories category 
![image](https://user-images.githubusercontent.com/16067358/56580380-58418980-65ca-11e9-888a-f1763ceae018.png)
And 6 products in the Art category
![image](https://user-images.githubusercontent.com/16067358/56580449-7909df00-65ca-11e9-9485-3255fe32ff19.png)
Thanks to check & feedback.

**Comment by nirav-nanda** [comment]
yes , this is what i am looking for. Thank you,

need one more help, how can i add this filters to brand page if possible.. i can't find any option for that.

thank you ma'am for quick response, and solving our issue.

**Comment by khouloudbelguith** [comment]
Hi @nirav-nanda,

You need to create a custom hook for the manufacturer page & transplant the ps_factedsearch module to this hook.
Thanks!

**Comment by kpodemski** [comment]
@khouloudbelguith @nirav-nanda 

unfortunately ps_facetedsearch module is working **only** on category pages

**Comment by khouloudbelguith** [comment]
@kpodemski, thanks for your feedback.
@nirav-nanda, can I close the issue?
Thanks!

**Comment by nirav-nanda** [comment]
@khouloudbelguith , thank you for support.
you can close this issue.

**Comment by khouloudbelguith** [comment]
Hi @nirav-nanda,

You are welcome.
Feel free to open a new on when needed.
Thanks!
