### ISSUE TITLE
Problem with customer account creation

### ISSUE THREAD

**Issue by arg73** [PrestaShop/PrestaShop#13524]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @arg73,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by arg73** [comment]
hello
i have an e-boutic of engraving on glasses ''www.gravure-sur-verres.fr'' with prestashop version 1.6.1.22
since 1 month, eatch day in my back office i have about 20 new creations of customer's accounts 
(see the attached picture) which provide from spam, virus or other ...

![argprobleme](https://user-images.githubusercontent.com/46370249/56580188-4c59c580-65d2-11e9-9985-be028ab3fe8f.JPG)
![argproblemebis](https://user-images.githubusercontent.com/46370249/56580192-4fed4c80-65d2-11e9-819b-989374a02770.JPG)

thanks a lot
thierry

**Comment by khouloudbelguith** [comment]
@arg73, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 

Log and debug are not needed : 

https://www.prestashop.com/forums/topic/981159-securite-spam-customer-account-solution-13-17/

https://www.prestashop.com/forums/topic/981158-securite-spam-compte-client-solution-13-17/

The form allows url in fisrtname and lastname.

**Comment by ghost** [comment]
You can also add 1.7 label

**Comment by matks** [comment]
> The form allows url in fisrtname and lastname.

Thank you ! Our understanding of the issue is that the goal of the spam attack is to make the shop send a registration email to a real user, and put there links using firstname or lastname URL. Then the user clicks on the link, be it a spam link or a phishing link.

Did you observe another behavior behind this spam attack ?

**Comment by matks** [comment]
An additional impact of this behavior: if injected mail addresses are bad and the shop sends registration mail to these addresses, this can damage the mailing reputation of the shop and make it look like a spammer.

This is probably a side-effect of this attack but still annoying

**Comment by arg73** [comment]
i don't observe another behaviour behind this spam attack
i going to install your solution 

thanks for your advices
thierry

**Comment by Eolia** [comment]
You can also add all versions, since 0.97 ;)

**Comment by matks** [comment]
PrestaShop versions prior to 1.5 are not maintained anymore, so only 1.6 and 1.7 versions are needed

**Comment by arg73** [comment]
i have make modification
there is a probleme now
invalid name when i create an account
[Customer.txt](https://github.com/PrestaShop/PrestaShop/files/3111547/Customer.txt)
[Validate.txt](https://github.com/PrestaShop/PrestaShop/files/3111548/Validate.txt)
see the 2 files

**Comment by eternoendless** [comment]
Hi there, we are going to release a patch for 1.7.5.x and 1.6.1.x in order to mitigate the attack vector.
