### ISSUE TITLE
Prestashop breadcrumb google issue 

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#13520]
Google is generating the position error for the breadcrumb on prestashop
![2019-04-11_14-25-25](https://user-images.githubusercontent.com/46920172/56550158-7b584300-65a2-11e9-991e-741bb1a9ee5b.jpg)

**Comment by khouloudbelguith** [comment]
Hi @pks891618,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1z0vKhSnLLUKUhruFu2D3KnOgBwReKOJD/view
Thanks to check & feedback

**Comment by pks891618** [comment]
Hi @khouloudbelguith 
Please test the url here on the google

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdev.legastronomesexy.com%2Ftenga-eggs-oeuf-masturbateurs%2F30-tenga-egg-masturbateur-homme.html

You need to pass the page like category or products page where breadcrumb are commings

this url testing the schema of the prestashop breadcrumb

**Comment by khouloudbelguith** [comment]
@pks891618, with your URL, I have a problem
![image](https://user-images.githubusercontent.com/16067358/56584217-3d274780-65d3-11e9-9875-6638e1a80926.png)
But if check with my shop, it is OK
![image](https://user-images.githubusercontent.com/16067358/56584264-58925280-65d3-11e9-87b2-2ec13942b2f0.png)
Thanks!

**Comment by pks891618** [comment]
Are you using prestashop. 1.6

**Comment by khouloudbelguith** [comment]
@pks891618, no.
I'm using the latest PrestaShop version PS1.7.5.1.
![image](https://user-images.githubusercontent.com/16067358/56591186-2d623000-65e0-11e9-9a69-6bb6b89bdd33.png)
Thanks!

**Comment by pks891618** [comment]
Please test this for 1.6.1

**Comment by khouloudbelguith** [comment]
@pks891618,
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
Thanks!

**Comment by pks891618** [comment]
Is this means there is no solutions for this ?? I need to manually code it ?

**Comment by khouloudbelguith** [comment]
@pks891618, I tried with PS1.7.5.1 but we cannot reproduce the issue with PS1.7.5.1
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security issue will be fixed.
Thanks!
