### ISSUE TITLE
Invoices can be changed/modified 

### ISSUE THREAD

**Issue by hiousi** [PrestaShop/PrestaShop#13539]
**Describe the bug**
When changing an address for a customer, if that address is used in some invoices, the invoice is modified. This can be a problem because some regulation laws does not allow an invoice to be modified.

**To Reproduce**
1. Go to 'customer/address
2. Click on 'edit an address
3. save the address and check an invoice using this address
4. See that the invoice is changed

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: all
PHP version: all

**Comment by khouloudbelguith** [comment]
Hi @hiousi,

Thanks for your report.
Yes, I manage to reproduce the issue with PS1.7.5.1
![image](https://user-images.githubusercontent.com/16067358/56597839-386e8d80-65eb-11e9-9d2d-cd85f1058868.png)
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
@hiousi 

Your issue is related to #12394 
I added a comment on it and I close this issue as it's a duplicate

**Comment by khouloudbelguith** [comment]
Duplicate of #12394
