### ISSUE TITLE
Simplify Commerce Module has been deactivated

### ISSUE THREAD

**Issue by JohnbConneely** [PrestaShop/PrestaShop#13546]
**Describe the bug**
A plugin we have on your marketplace has been deactivated for some reason.
The link used to be http://addons.prestashop.com/en/17104-simplifycommerce.html

That link no longer works.

I have since logged into my developer account and can see that the plugin has been deactivated. When I try to save the product sheet, it tells me "One of your documentation is unavailable, try to reupload them."

I then try to re-upload my readme file (with and without deleting the old one) and I get a random popup box error saying "Addons.prestashop.com says An error occured"

I need to get this plugin reactivated ASAP - can someone point me in the correct direction as to how I do this?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
Screenshot addition not working.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Johnnerz,

Please be aware that this bug tracker should be used to report issues of the PrestaShop core only. If you need help, you can ask on this link https://addons.prestashop.com/en/contact-us
Thanks for your understanding!
