### ISSUE TITLE
Catalog > Monitoring > Empty categories list status toggling action not working

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#13541]
**Describe the bug**
In Sell > Catalog > Monitoring > `list of empty categories` status toggling button not working.
This is due to already migrated Categories page to which toggling action is referred with `GET` method ( legacy behavior ), while in migrated page the accepted method is only `POST`. Removing _legacy_link from route provokes just another error, because it can't find legacy `AdminCategoriesController` (which is already deleted, after categories page migration).
Same behavior is reproducible with delete action.

**To Reproduce**
1. Go to Sell > Catalog > Monitoring > 'List of empty categories'
2. Click on toggle category status action (marked as green check or red X icon. Screenshot 1)
3. You can see the error. (screenshot 2)

**Screenshots**
1.
![Screenshot from 2019-04-23 19-22-13](https://user-images.githubusercontent.com/31609858/56598568-652ba080-65fd-11e9-887c-7217728b45de.png)
2.
![Screenshot from 2019-04-23 19-23-47](https://user-images.githubusercontent.com/31609858/56598619-82f90580-65fd-11e9-950f-347b027eaef8.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I have the same issue with branch 1.7.6.x.
It is a regression.
In the PS1.7.5.1 => OK.
Thanks!

**Comment by marionf** [comment]
There is also an issue if you try to delete a category from Monitoring page:

![capture d'écran_1457](https://user-images.githubusercontent.com/13449658/56658950-39132c80-669c-11e9-93e7-da16dc4a4a5e.png)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13813
