### ISSUE TITLE
Cart rule with free shipping AND % or amount reduction not applied in FO

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#13543]
**Describe the bug**
For my case, when I add a new promo code on cart rule (individual or to everyone), in Front-Office adding a correct promo code not working.
Detected by the E2E automation tests.

**To Reproduce**
1. Add a new promo code
2. Don’t forget to activate free shipping (toggle button) before saving it
3. Go to Front-Office and add the promo code
4. Nothing happen, if you reload the page you have an error page (500) 

**Screenshots**
Please refer to the video attached https://drive.google.com/file/d/16dyBqxzC5SDAwNAVa6DAKyK0svf6Rt7j/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @mbadrani,

I have the same issue with PS1.7.6.x
After clicking "Add button" => I reload the page => an exception displayed
![image](https://user-images.githubusercontent.com/16067358/56599971-9d2be700-65ef-11e9-9707-d00c038c85b2.png)
Thanks!

**Comment by matks** [comment]
Nice catch !

**Comment by mbadrani** [comment]
@matks & @khouloudbelguith I have another bug when I try to access to "orders/shopping carts" in the backoffice, it seems to be related bug wdyt?
![image](https://user-images.githubusercontent.com/29543279/56647691-2986ea00-6682-11e9-816a-3ca99964af92.png)

**Comment by mbadrani** [comment]
both are calling CartRuleCalculator.php

**Comment by khouloudbelguith** [comment]
@mbadrani, I think they are related.
In my case all the shop FO is blocked with this exception, I don't have access to FO any more.
![image](https://user-images.githubusercontent.com/16067358/56648785-d27e1680-667b-11e9-9fe9-a7aee6edbe0e.png)

Thanks!

**Comment by mbadrani** [comment]
so If FO is not accessible anymore it's critical

**Comment by tomlev** [comment]
@mbadrani please give more details:
With a fresh-installed shop, when I add a cart rule I can go through the checkout steps without interruption.
which sort of cart rule did you use ? Is it on a fresh install (which parameters) or after some changes (carrier, products...) ?
Your description is far too vague to reproduce easily.

**Comment by mbadrani** [comment]
@tomlev a complete description here on how to reproduce it:
https://docs.google.com/document/d/1pUVx5060vM2hgNIlaVS4KfI9BbWWmV7wTUos1OHYnHg/edit?usp=sharing

**Comment by tomlev** [comment]
`Don’t forget to activate free shipping`
I think it was the missing part, please share these details next time ^^

**Comment by tomlev** [comment]
it was. I can reproduce now

**Comment by marionf** [comment]
Furthermore, the problem is if you create a cart rule with free shipping **AND** a promo in % or amount.
A cart rule with only free shipping is working correctly
