### ISSUE TITLE
na abre para verificar os pedidos na administração

### ISSUE THREAD

**Issue by hipercenterbo** [PrestaShop/PrestaShop#13551]
**Describe the bug**
quando entro em minha adim e clico nos pedidod realizados na loja para ver os produtos não abre o pedido
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @hipercenterbo,

Please, send your request in English.
English is the norm on GitHub.
Thanks to add a clear description of your issue
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @hipercenterbo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
