### ISSUE TITLE
BO - We can create a new customer successfully without setting required field "Partner offers"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13556]
**Describe the bug**
We can create from the BO a new customer successfully without setting required field "Partner offers"
![image](https://user-images.githubusercontent.com/16067358/56678473-b2ba1300-66ba-11e9-9a30-6b337e45d1b7.png)

**To Reproduce**
1. Go to BO => Customers => Click on  Set required fields for this section
2. Check the "Partner offers" option
3. Save
4. Create a new customer from BO without enabling Partner offers => the customer is successfully saved => NOK
We should have a red alert like in the last previous version PrestaShop
 

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/56678327-522ad600-66ba-11e9-98a2-354169515078.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.0

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13887
