### ISSUE TITLE
Bosnian language doen't apper in backoffice

### ISSUE THREAD

**Issue by bubo1991** [PrestaShop/PrestaShop#13555]
![123](https://user-images.githubusercontent.com/6005499/56665991-63b8b180-66ab-11e9-93de-e9105b821542.png)

**Describe the bug**
I can't find bosnian and herzegovina on my back office. I tired 3 older version and i have same problem. When i look on official demo there is bosnan language. Currency (BAM) alo doesn't apper. Sorry for bad English

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @bubo1991,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
In the BO => International => Localization => the pack Bosnia and Herzegovina, doesn't exist
But in the countries page, this country is displayed
Also, during the install, the Bosnia and Herzegovina country exists.
I tried to install PS1.7.5.1 with Bosnian language /  Bosnia and Herzegovina country => In BO, the currencies displayed Euro & Dollar
![image](https://user-images.githubusercontent.com/16067358/56669573-4682e380-66a9-11e9-8385-2cc4f432841e.png)
The currency (BAM) doesn't exist.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @bubo1991,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
In the BO => International => Localization => the pack Bosnia and Herzegovina, doesn't exist
But in the countries page, this country is displayed
Also, during the install, the Bosnia and Herzegovina country exists.
I tried to install PS1.7.5.1 with Bosnian language /  Bosnia and Herzegovina country => In BO, the currencies displayed Euro & Dollar
![image](https://user-images.githubusercontent.com/16067358/56669573-4682e380-66a9-11e9-8385-2cc4f432841e.png)
The currency (BAM) doesn't exist.
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
I don't know how localization packs are working
We have well Bosnian language and BAM currency, so why we don't have a Bosnian pack ?
@PrestaShop/prestashop-core-developers any idea ?

**Comment by tomlev** [comment]
@marionf please give the bosnian language iso-code, I dont know all of them ^^

**Comment by marionf** [comment]
BS

**Comment by tomlev** [comment]
indeed, there is no file named `bs.xml` in `/localization` directory
adding such a file requires defining all data like taxrule groups, units...
have a look on the neighbour files to get examples

**Comment by bubo1991** [comment]
any solution ? i didn't understand nothing. Can i import my currenncy and language or not and how to do that ? I need currrenny (BAM or KM )

**Comment by marionf** [comment]
@bubo1991 

You can import Bosnian language from International > Translations menu
You can add BAM currency from International > Localization > Currencies menu

**Comment by colinegin** [comment]
Hello @LouiseBonnard , what do you think of this issue ?

**Comment by LouiseBonnard** [comment]
As said @marionf, you can add Bosnian in the International > Translations page of the back office, this language is available. As for the currency, you won't be able to find it natively since Bosnian is available in the back office only as a language and not as part of a localization pack. It means that there is no localization content (currencies, taxes, units, etc.) to download with it. But if you want to add a Bosnia-Herzegovina pack with this information, feel free to do so. ;-)

**Comment by LouiseBonnard** [comment]
FYI: #16435

**Comment by khouloudbelguith** [comment]
Duplicate of #16435
