### ISSUE TITLE
The Welcome module isn't displayed if you use a language different than the one selected during installation

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13569]
#### Describe the bug

The Welcome module isn't displayed if you use a language different than the one selected during installation

#### Steps To Reproduce

1. Install Prestashop in English language and France country
2. Go to the BO
3. Select a language other than French or English (Arabic or Polish or Sounth Korea (hangul)) in your employee account
4. Click on the resume button => Click on Start
5. You will be redirected to the product page
6. See error: the onboarding is not displayed on this page

**PS:**
- with Arabic language, sometimes the onboarding modal partially hidden (badly placed) 
- with korean language (hangul), the all characters are displayed as small squares (I don't know if this bug is from PrestaShop or from my browser), see the attached screen record below:

![image](https://user-images.githubusercontent.com/23308427/101016372-fcdaca00-3568-11eb-938b-f740800079f6.png)

#### Screenshots

- Arabic
https://drive.google.com/file/d/1YQauPikeQ5ttVL0ig2BdpfJQZN1VPFgZ/view
- Polish
https://drive.google.com/file/d/1zF9KUfSZa8L77kFzkjCA_RSeTxWnq0K5/view
- Korean
https://drive.google.com/file/d/1SapVgqPrOPMraqonnvHDa9X3lnTn5qG1/view

#### Additionnal information
PrestaShop version: 1.7.6.9
PHP version: 7.2
Welcome Module: v6.0.3

**Comment by mbadrani** [comment]
nice catch Nesrine & Khouloud! Thanks

**Comment by khouloudbelguith** [comment]
ping @nesrineabdmouleh

**Comment by eternoendless** [comment]
I'm unable to reproduce this issue using the github repository on 1.7.5.1 and 1.7.5.x, nor with the pre release 1.7.5.2 zip. Would you care to see if you can reproduce AND see if there are any error messages in the JS console?

**Comment by eternoendless** [comment]
BTW I installed in French. Not sure if related.

**Comment by SimonGrn** [comment]
We have a kinda related issue: #12560 in 1.7.6.x. Maybe it's the same problem ? To summarize, the onboarding module only works in the original language selected during installation and not in another one.

**Comment by mbadrani** [comment]
I've updated the issue, we can reproduce this behaviour after installing in english

**Comment by marionf** [comment]
I just tried with 1.7.5.2-**build2**:
- install in English and country United States: can't reproduce
- install in English and country France (default language English): can't reproduce
If I switch my employee language to French, I can reproduce
So, it seems related to #12560 as @SimonGrn said

**Comment by eternoendless** [comment]
I'm only able to reproduce using the zip release. If I refresh the page the onboarding appears correctly. If I stop it, reset the module using Module Manager and then start over, It works as expected. It's weird.

**Comment by khouloudbelguith** [comment]
I tried with 1.7.5.2build2 French language / France country => can't reproduce
I tried with 1.7.5.2build2 English language / France country => issue reproduced

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 
I can reproduce it with 1.7.5.1, so it's not a regression of 1.7.5.2

**Comment by hibatallahAouadni** [comment]
Hello @khouloudbelguith 

I didn't manage to reproduce your issue with PS1.7.6.9 and module Welcome v6.0.3, see the attached screen record below:

https://drive.google.com/file/d/1NTK1qPRM3aEpEFomPn_fxZDkdUFifmiz/view

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello,

I just modify the issue content, cause this bug is fixed with french languge but not fixed yet with these languages (Arabic, Polish, Korean, ...).

Thanks!

**Comment by marionf** [comment]
Hello, 

The welcome module will be archived with the V8.0.0, so I close this issue.
