### ISSUE TITLE
core.js obfuscated

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#13562]
Hello,

Why is the core.js file is obfuscated? Is it not supposed to be the developer version here? If so, where can I find an unobfuscated version of this file?

**Comment by matks** [comment]
Hi, I guess you are referring to https://github.com/PrestaShop/PrestaShop/blob/develop/themes/core.js ?

This is a bundled JS file, created by webpack. The developer version is splitted into several files, each relevant to one topic. You can find them in https://github.com/PrestaShop/PrestaShop/tree/develop/themes/_core/js

**Comment by vincent-dp** [comment]
Oh ok! thank you very much, I was not aware of that

**Comment by khouloudbelguith** [comment]
Hi @vincent-dp,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
