### ISSUE TITLE
Wrong shipping cost on order page

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#13575]
Hello, i have a problem with shipping cost on order page. In admin price is set to **12.11** and pl standard rate **23%**, the price should be calculated: 12.11 + 23% = **14.90**, but it is **12.30** 
Similar problem in all carrier

in admin:
![obraz](https://user-images.githubusercontent.com/11571787/56758705-97710580-6797-11e9-83a3-97e2a2edbf1e.png)
![obraz](https://user-images.githubusercontent.com/11571787/56758743-a8217b80-6797-11e9-8db7-da95272f282c.png)

on front:
![obraz](https://user-images.githubusercontent.com/11571787/56758784-bf606900-6797-11e9-87a5-f59498b71fb0.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0

Anybody have an idea what happen wrong?

**Comment by khouloudbelguith** [comment]
Hi @madkot,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1jCqya1FS7zPIPOSB1lA5baJ3ue7AuS1q/view
did you use the default theme provided by PrestaShop?
Thanks!

**Comment by madkot** [comment]
Hi @khouloudbelguith 
I'm have default theme but little modified by me. presta files are default, no changes, no overrides.

Only for one carrier i have a good price, i dont have any idea to resolve it

**Comment by khouloudbelguith** [comment]
@madkot, do you make a modification to the PrestaShop core?

**Comment by madkot** [comment]
May i found problem in my case.. column 'shipping_external' in table 'carrier' is set to 1. I change it to 0 and the price is correct now.

I have some migrated data from ps1.6, may it is the problem source.

**Comment by khouloudbelguith** [comment]
@madkot, is your problem solved?

**Comment by madkot** [comment]
Yes, but i must know, what 'shipping external' rly mean, and why prestashop calculating bad price when it is set to 1?

**Comment by khouloudbelguith** [comment]
@madkot, the "shipping external"  attribute defaults to 0.
I attached a screenshot.
![carrier](https://user-images.githubusercontent.com/16067358/56820346-84b40a80-6843-11e9-9995-0f91f75aaad0.png)
I close the ticket, feel free to open a new one when needed.

**Comment by ReGi00** [comment]
I confirm this resolution.
The shipping cost was shown incorrectly and after changing the field shipping external in the database to 0 for carier everything works correctly
Thanks
