### ISSUE TITLE
[Optimization] Autoloaders proper order

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13573]
## Issue description

There is multiple autoloaders involved in rendering the BO pages. Composer autoloader, PrestaShop legacy autoloader, Smarty autoloader*.

It seems that whenever php attempts to autoload a class, Smarty is the 1st autoloader being called. In the case of a Symfony class such as `Symfony\Component\Config\ConfigCache`, Smarty will detect this is a not-Smarty class and [return early](https://github.com/smarty-php/smarty/blob/master/libs/Autoloader.php#L94). Then Composer autoload is called and autoloads the class. 

*Because the BO layout is still being rendered by Smarty on migrated pages

The consequence is that we call Smarty autoload 1st although most classes will be Composer-autoloaded classes. This is a performance loss.

## Solution

Find where are these Composer registered by tracking `spl_autoload_register()` calls and ensure that Composer autoload is the 1st autoload being called, rather than Smarty.

## Beyond

There might be more than 3 autoloaders being in use for PrestaShop. For example HTMLToPDF has one too although I cant tell (it needs to be checked) whether it is being used or the code is not applicable to our usecase. The same optimization strategy (call the relevant autoload first) should be used when possible.

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?

**Comment by Quetzacoalt91** [comment]
@matks you should know that modules can also bring their own autoloader too.

**Comment by PierreRambaud** [comment]
I see only one file where the Smarty_Autoloader is registered :thinking: 
![image](https://user-images.githubusercontent.com/1462701/100249860-54f84780-2f3d-11eb-97e8-db314558d0f0.png)
I try to sniff what happened in the bootstrap.php, but it's never loaded :thinking:

**Comment by matks** [comment]
I close this issue as no progress has been done for 2 years. I dont think I can work on it soon.
