### ISSUE TITLE
Failed to start the session: already started by PHP.

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#13577]
When I am in my back office and I try to use the searchbar, I got this

(1/1) RuntimeExceptionFailed to start the session: already started by PHP.
--
in classes.php line 136
at NativeSessionStorage->start()in classes.php line 515
at Session->start()in SessionTokenStorage.php line 78
at SessionTokenStorage->hasToken('https-ANONYMOUS_USER')in CsrfTokenManager.php line 72
at CsrfTokenManager->getToken('ANONYMOUS_USER')in Router.php line 50
at Router->generate('admin_order_invoices', array(), 0)in LegacyUrlConverter.php line 82
at LegacyUrlConverter->convertByParameters(array('controller' => 'AdminInvoices'))in Link.php line 799
at LinkCore->getAdminLink('AdminInvoices')in AdminController.php line 2018
at AdminControllerCore->getTabs('3', 2)in AdminController.php line 2019
at AdminControllerCore->getTabs('2', 1)in AdminController.php line 2019
at AdminControllerCore->getTabs()in AdminController.php line 1887
at AdminControllerCore->initHeader()in Controller.php line 277
at ControllerCore->run()in Dispatcher.php line 509
at DispatcherCore->dispatch()in index.php line 99

Any idea?

**Comment by khouloudbelguith** [comment]
Hi @vincent-dp,

Thanks for your report.
What is the exact version PrestaShop did you use?
Did you make the search from a migrated page (Symfony page or not?)
Thanks!

**Comment by vincent-dp** [comment]
1.7.5.0

Admin back office page of prestashop, any of them

**Comment by khouloudbelguith** [comment]
@vincent-dp, thanks for your feedback.
Did you use a custom module to generate invoices?
Thanks!

**Comment by vincent-dp** [comment]
yes
Team Ever PS Quotation

**Comment by khouloudbelguith** [comment]
@vincent-dp, have you tried to contact the module author about this issue?
because you have some errors related to invoices

```
at Router->generate('admin_order_invoices', array(), 0)in LegacyUrlConverter.php line 82
at LegacyUrlConverter->convertByParameters(array('controller' => 'AdminInvoices'))in Link.php line 799
at LinkCore->getAdminLink('AdminInvoices')in AdminController.php line 2018
```

Thanks to check with them & feedback

**Comment by vincent-dp** [comment]
But, this is a file of yours

**Comment by khouloudbelguith** [comment]
@vincent-dp, In my case, I did not manage to reproduce the issue with PS1.7.5.1.
could you please check if you have override file in your ProjetFolder/override/
Thanks!

**Comment by vincent-dp** [comment]
neither in my %root%override nor my template override folders

I find references of `AdminInvoices` in var/cache/dev, should I empty var/cache/dev?

**Comment by khouloudbelguith** [comment]
@vincent-dp, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by vincent-dp** [comment]
Nope :'( didn't worked

**Comment by khouloudbelguith** [comment]
@vincent-dp, to be sure it is not a module issue.
Could you please contact the module author & feedback.
In my case, it is OK.
Thanks!

**Comment by vincent-dp** [comment]
I deactivated this module and it still doesn't work

**Comment by khouloudbelguith** [comment]
@vincent-dp, thanks for your check!
Do you have the same error as before?
Thanks!

**Comment by vincent-dp** [comment]
Yes, same message as before deactivation. I tried to deactivate other modules, same problem :(

**Comment by khouloudbelguith** [comment]
@marionf, could you please try to reproduce this issue.

**Comment by vincent-dp** [comment]
I cloned my prestashop from another server, and on this (old) server, it works. What could have change?

**Comment by khouloudbelguith** [comment]
@vincent-dp, it seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
You should check your host.
I close the ticket, feel free to open a new one when needed.

**Comment by mwkaicz** [comment]
Seems that this bug is related with moving shop from one location to another. I got in same problems after moving the shop from one server to another.  
- domain and also path to the main folder has changed from "/shop/" to "/" ( I changed it everywhere I found it in .htaccess and in DB tables)
 - problem occures in admin section after login.
 - v1.7.4.2
- PHP src server 7.3, target server 7.4.9 

Is there some description how to migrate shop properly?

**Comment by matks** [comment]
Warning: I think v1.7.4 is not fully compatible php7.3 compliant and I'm sure it's not php7.4 compliant. This could create issues. See PHP compatibility per version https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by mwkaicz** [comment]
Ouch, thx for warning, that page is kind of confusing, not everyone scrolls to the bottom of the page and at the top is written "We recommend PHP 7.1 or later. See the compatibility chart below for more details." :)

Solved 👍

**Comment by ayushshrestha** [comment]
@vincent-dp 
Go to Host Panel and find
MultiPHP INI Editor
and set to 

or you can add this to .htaccess

max_execution_time 6000
max_input_time 6000
session.save_path /tmp

and go to your root and create tmp folder

and refresh your prestashop

**Comment by shakingwerito** [comment]
> @vincent-dp Go to Host Panel and find MultiPHP INI Editor and set to
> 
> or you can add this to .htaccess
> 
> max_execution_time 6000 max_input_time 6000 session.save_path /tmp
> 
> and go to your root and create tmp folder
> 
> and refresh your prestashop

I have a new server with php 8.2, and fresh install prestashop 8.1.3 and has the same issue.
To fix it I use the session.save_path = /tmp , thanks ayushshrestha :D
