### ISSUE TITLE
Grid presenter hook doesn't respects the documentation

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#13579]
**Describe the bug**
While defining a hook to customize the Grid presentation, the dispatched hook is wrong.

It's not formatted like the other ones, making the use of this hook impossible while using lowercased grid identifiers.

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Presenter/GridPresenter.php#L96 while for others one the Grid identifier is formatted https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/GridFactory.php#L92.

Can we fix this for 1.7.6?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by mickaelandrieu** [comment]
Hi @khouloudbelguith, I just fixed the issue :+1:

**Comment by khouloudbelguith** [comment]
Hi @mickaelandrieu,

Great!
Good work :smile:
