### ISSUE TITLE
Email Theme: Disable theme selector when no the theme contains no mail overrides

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#13586]
**Describe the bug**
In email theme when you try to generate mail templates for a specific theme, if this theme doesn't contain any mail overrides you get an error because the output folder does not exist.

**Screenshots**
![capture d'écran_1466](https://user-images.githubusercontent.com/13801017/56815604-13c02300-6842-11e9-8805-9cdac507738b.png)

**Recommended solution**
Even though the error is legitimate (it makes no sens to override non existing files). The error message is not really understandable by the user. And he should be able to perform this action in the first place.

1- The form builder needs to check for each themes if it contains mail files to override, and filter those that don't contain any.
2- If no themes contain mail templates in the form page the selector must be disabled (grey) with an explanation legend.

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13722

**Comment by jolelievre** [comment]
Here is a missing change https://github.com/PrestaShop/PrestaShop/pull/13779
Allows to overwrite modules emails even if core emails were not overriden by the theme

**Comment by kpodemski** [comment]
Hey @jolelievre 

lets assume that we have a module `examplemodule`

this module has its own mails in:

`modules/examplemodule/mails/ISO/`

how can we create a new modern template for a module, but only for 1.7.6 version? is there any way to do that? (i didn't have time to dig into codebase just yet)

do we need to generate those e-mails first and put conditional `if` while sending it? or core will find out proper template for us?

**Comment by jolelievre** [comment]
Hi @kpodemski 

> how can we create a new modern template for a module, but only for 1.7.6 version? is there any way to do that? (i didn't have time to dig into codebase just yet)

If you want to use the email theme feature for a module you have two ways of doing it:

- you can add your layouts in the appropriate email theme. For example if your module template is `modules/examplemodule/mails/en/my_email.html` then you need to add a layout `mails/themes/modern/modules/examplemodule/my_email.html.twig` in your theme, then it will be exported in the module mails folder on generation (this is the quick and dirty way ^^)
- or you can use the hooks available during the generation process, and in this case the `actionListMailThemes` which dispatch a collection of `MailTheme` in which you can **add** your own `LayoutInterface` which indicate the paths to your modules layout (and the module they are associated to)

From there as long as the `MailGenerator` is aware of your layouts (wether you add them in the email theme folder or via a hook), they will be generated just like the core ones into the appropriate folder (in this case in `modules/examplemodule/mails/en/my_email.html`, `modules/examplemodule/mails/fr/my_email.html`, ...
So they will be used later by the `Mail::send` just like they used to be

> do we need to generate those e-mails first and put conditional `if` while sending it? or core will find out proper template for us?

I'm not sure I understand what you mean with the conditional `if`?

That said your question is really interesting because it makes me think about potential improvements:
- add the possibility to add a folder to scan by the `FolderThemeCatalog` via a hook
- automatically scan the `modules/*/mails/themes/*` folders

I am currently writing the documentation for this feature, and improving the tool to help build modern theme with MJML. Your feedback about this doc will be more than welcome

Don't hesitate to ask other questions, this will help me write a better documentation

**Comment by kpodemski** [comment]
@jolelievre 

> I'm not sure I understand what you mean with the conditional if?

sorry, what i meant was scenario, when we have two mail templates, one for 1.7.5 and below, one for 1.7.6, just to make sure that we can provide package with generated e-mail, for all PrestaShop versions with modules, but:

> you can add your layouts in the appropriate email theme. For example if your module template is modules/examplemodule/mails/en/my_email.html then you need to add a layout mails/themes/modern/modules/examplemodule/my_email.html.twig

looking for an e-mail template in `modules/examplemodule/mails/en/my_email.html` with a `modern` theme enabled seems to be a bad idea and non retrocompatbile one :) i think, that if we want to keep both layouts in module folder Mail.php should look for template files in proper subdirectory, so, if we have a code like this:

```
Mail::Send(
                            $this->context->language->id,
                            'new_comment',
                            sprintf(Mail::l('New comment on %1$s blog for article: %2$s', $this->context->language->id), $toName, $this->SimpleBlogPost->title),
                            array(
                                '{lastname}' => $customer->lastname,
                                '{firstname}' => $customer->firstname,
                                '{post_title}' => $this->SimpleBlogPost->title,
                                '{post_link}' => $this->SimpleBlogPost->url,
                                '{comment_content}' => $comment_content,
                            ),
                            $to,
                            $toName,
                            $from,
                            $fromName,
                            null,
                            null,
                            _PS_MODULE_DIR_.'ph_simpleblog/mails/'
                        );
```

with a `modern` theme enabled Mailer should look for files in `_PS_MODULE_DIR_.'ph_simpleblog/mails/themes/modern/`

what do you think?

**Comment by jolelievre** [comment]
Well I see your point but we didn't change the Mailer component, so wether you integrate your mails or you use layout to generate them dynamically they will always be fetched from the same folder: `_PS_MODULE_DIR_.'ph_simpleblog/mails/en'`

This was made to avoid changing the Mail behavior or structure, the only change is that now not all languages have to be included only layout with translatable keys.

So in your module you can integrate mails like you did in 175 (one folder per language `_PS_MODULE_DIR_.'ph_simpleblog/mails/en'`, `_PS_MODULE_DIR_.'ph_simpleblog/mails/fr'`, ...

And you can include you own layouts, for example in ``_PS_MODULE_DIR_.'ph_simpleblog/mails/themes/modern'`` and then add them to the `Theme` via the hook. What will happen in 176 is that generated emails will overwrite the existing static templates that were embedded inside the module.

**Comment by kpodemski** [comment]
@jolelievre 

ok, is this hook is triggered once the module is installed? or do i need to trigger it manually?

**Comment by jolelievre** [comment]
The hook is triggered on templates generation which can happen:
- on a language installation
- manually via the BackOffice "Design > Email Theme"

So if you install a new module you will have to regenerate the email templates for the languages you already installed.

Besides by default the generation process doesn't overwrite existing templates (to avoid erasing manual modification) during a language installation. So if you integrate static templates like in 175 as you suggested, you will have to use the "Force overwrite" option in the back office to erase the existing ones.

Note: I didn't think about it before, but you might launch the generation process on module installation. This would require to have access to the Symfony container as the services managing this feature are only available in Symfony context.
I will attach to the doc a module describing how to use the hooks for this feature, I will try if this is possible and integrate it inside the demo module.

**Comment by kpodemski** [comment]
> you will have to use the "Force overwrite" option in the back office to erase the existing ones.

this is not a good option because i presume that it will override not only my template, but also other modules templates

> Note: I didn't think about it before, but you might launch the generation process on module installation. 

this would be best option :)

**Comment by jolelievre** [comment]
> > Note: I didn't think about it before, but you might launch the generation process on module installation.
> 
> this would be best option :)

Even though you can launch the generation process from the module installation, the overwrite option is common to the whole process , it is not a module by module option so yours and others modules will be overwritten

But of course it will only overwrite templates included in an email theme, so if other modules include their own templates they won't be touched since they have no layouts to be generated As for those which manage the new email theme, it seems logical that they are overwritten as well in this case

**Comment by jolelievre** [comment]
Hi @kpodemski 

just in cas here is the PR of the coming doc for Email Theme, feel free to have a look (I advise you to launch hugo server to read it more easily).
Or if you prefer for it to be published, I will post the link here later anyway.

**Comment by jolelievre** [comment]
I didn't pay attention, with link to the PR it should be better ^^
https://github.com/PrestaShop/docs/pull/269
