### ISSUE TITLE
newsletter_verif and newsletter_voucher email firstname and lastname var empty

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13582]
**Describe the bug**
For newsletter_verif and newsletter_voucher emails, firstname and lastname var are empty for modern emails templates

**To Reproduce**
1. Install ps_emailsubscription module
2. Configure the module and enable Email verification after subscription and fill promo code field.
3. Subscribe to the newsletter in FO
4. See received emails

When the customer have already an account, we can have firstname and lastname
When the customer don't have an account these values should be removed

**Screenshots**

![capture d'écran_1464](https://user-images.githubusercontent.com/13449658/56808017-c12a3b00-6830-11e9-90ef-729e833929c0.png)

![capture d'écran_1465](https://user-images.githubusercontent.com/13449658/56808024-c38c9500-6830-11e9-8afc-dd8e20ebd825.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by marionf** [comment]
@LouiseBonnard FYI

**Comment by LouiseBonnard** [comment]
@marionf, thank you.
:-)
