### ISSUE TITLE
Cannot Add Files - Version 1.7.5.1

### ISSUE THREAD

**Issue by bestbuybargains** [PrestaShop/PrestaShop#13590]
Hello,

When you try to add a theme or file like a logo, the explorer window is not opening.  Tried Chrome and Edge. 

PrestaShop version: 1.7.5.1
PHP version: 7.0

![image](https://user-images.githubusercontent.com/50038176/56844320-2d7a5e00-6874-11e9-9536-aaf581901218.png)

**Comment by khouloudbelguith** [comment]
Hi @bestbuybargains,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record
https://drive.google.com/file/d/13fLeuVZ6i8c-pJJjwxLB4lrH8APaFzp2/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@bestbuybargains, you just closed the issue, it is fixed?
Thanks!
