### ISSUE TITLE
Add some targetable markup to the total amount of a customer

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#13598]
**Is your feature request related to a problem? Please describe.**
For automated testing : we need to be able to target efficiently the total amount a customer generated through valid orders.

**Describe the solution you'd like**
I would like to have some targetable markup around the total amount.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/49909275/56894430-2165ea80-6a86-11e9-821c-c510a54d7b46.png)

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by matks** [comment]
Make sense 👍 we'll do it

**Comment by khouloudbelguith** [comment]
Hi @matks,

So we can add this improvement to our bug roadmap?
@marionf, @colinegin what do you think?
Thanks!

**Comment by jolelievre** [comment]
Not sure w should get rid of the currency however, as it should be tested as well.

**Comment by SimonGrn** [comment]
> Not sure w should get rid of the currency however, as it should be tested as well.

Currency should be kept, you're totally right. I'll edit my FR.
