### ISSUE TITLE
Inapropriate hook names formatted for identifiable object forms.

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#13594]
Some hooks are being called like **actionAfterUpdateroot_categoryFormHandler**, **actionAfterUpdatecms_page_categoryFormHandler** or **actionAfterCreatemanufacturer_addressFormHandler**. It is due to the form types which are constructed from one then more word are being separated by snake cases automatically. 

**Suggestion**

We can use **Container::camelize()** when rendering hook name for identifiable object forms.

**What to do for existing hooks that were introduced in 1.7.5**

I can't recall correctly but I think theres only one hook or not at all - but we can check that to make sure. If such exists either we can call both or just ignore it. @matks what do you think we should do in such case?

**Additionnal information**
PrestaShop version: 1.7.6.x

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by jolelievre** [comment]
@mickaelandrieu seems like this one was not the only one https://github.com/PrestaShop/PrestaShop/pull/13580/files

**Comment by jolelievre** [comment]
Good news is https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/src/Core/Form/IdentifiableObject/Handler/FormHandler.php was only introduced in 176
We probably should check other hooks on grid and form

**Comment by matks** [comment]
@tomas862 Nice catch !

We can create a PR for 1.7.5.x just like https://github.com/PrestaShop/PrestaShop/pull/13580 to fix bad hook names using `Container::camelize()`

At least the patch will be there, available. And it might get shipped with either 1.7.5.2 or 1.7.5.3 is there is one

**Comment by jolelievre** [comment]
This is not needed for 175 because the FormHandler didn't exist (at least in `IdentifiableObject`)
But we should check it there are other ones that need to be fixed.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13643#pullrequestreview-234349491
