### ISSUE TITLE
Pricing / Tax / Different Countries

### ISSUE THREAD

**Issue by cry-ahmet** [PrestaShop/PrestaShop#13601]
hallo,

I am configuring a shop on which we want to sell digital products (Software, gamge code etc)
For every EU-country the endprice has to be the same and only the included TAX has to be change but it is not.
At the moment for greece:
25,20€ without TAX, 31€ included TAX and 5,80€ TAX

How it has to be for example:
for germany it is and it has to be: 29,99€ with TAX, 25,20€ without TAX, 4,79€ TAX
for greece it has to be 29,99€ with TAX, 24,38€ without TAX, 5,61€ TAX

thanks for your help

**Comment by khouloudbelguith** [comment]
Hi @cry-ahmet,

Could you please navigate to your BO => International => Taxes => Tax Rules Tab, you can find the EU VAT For Virtual Products, Try t edit it, you will discover, that it have different taxes for different countries
![image](https://user-images.githubusercontent.com/16067358/57081409-e9b0aa00-6cf4-11e9-9125-220a0691b09c.png)
Thanks to check & feedback.

**Comment by cry-ahmet** [comment]
Hi @khouloudbelguith ,

thanks for your answer.
Yes, I found the rule already and assigned it to the product in product edit page in price tab. But the endprice changes always. I want to keep the endprice for every country. Only included TAX amount should be changed.

cheers

**Comment by khouloudbelguith** [comment]
@cry-ahmet, in fact this behavior is not possible.
The price TTC is calculated just after changing the taxes.
So, the price HT is the same, but if we change the country => the taxes will be changed so the price TTC is changed also=> which is a normal behavior
>I want to keep the end-price for every country

 => it is not possible.
Thanks!
I close the issue, feel free to open a new one when needed
