### ISSUE TITLE
Unable to open customer service module  PrestaShop version: 1.7.2.0

### ISSUE THREAD

**Issue by magnum93** [PrestaShop/PrestaShop#13608]
Hi, I am currently using Prestashop version: 1.7.2.0
and a Database MySQL version: 10.0.30-MariaDB-0+deb8u1

I was configuring my mail mail settings in the customer serice options and in error put in the wrong information in the imap settings.

Now because I entered the wrong settings in the fields, I am no longer able to access the Customer service module.

Is their a way please I can remove these values in order to get my CMS to work again please?
I did find this thread https://www.prestashop.com/forums/topic/623123-impossible-to-access-customer-service-after-setting-up-imap-v171/

I am unable to find these in the database.

Would anybody be able to tell me an easy way to fix my shop please
heres a screenshot of the settings I put the wrong values in https://imgur.com/a/9txnI0Y

**Comment by magnum93** [comment]
Hi, I am currently using Prestashop version: 1.7.2.0
and a Database MySQL version: 10.0.30-MariaDB-0+deb8u1

I was configuring my mail mail settings in the customer serice options and in error put in the wrong information in the imap settings.

Now because I entered the wrong settings in the fields, I am no longer able to access the Customer service module.

Is their a way please I can remove these values in order to get my CMS to work again please?
I did find this thread https://www.prestashop.com/forums/topic/623123-impossible-to-access-customer-service-after-setting-up-imap-v171/

I am unable to find these in the database.

Would anybod be able to tell me an easy way to fix my shop please

**Comment by khouloudbelguith** [comment]
Hi @magnum93,

Could you please try to delete the data related to IMAP config in the table ps_configuration : PS_SAV_IMAP_URL, PS_SAV_IMAP_PORT, PS_SAV_IMAP_USER and PS_SAV_IMAP_PWD, clear cache and feedback.

**Comment by khouloudbelguith** [comment]
Hi @magnum93,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
