### ISSUE TITLE
seo canonical url should be accessible

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#13613]
"Rollback the product canonical url #11150" changed the canonical url to be no longer accessible, but, in terms of SEO this seems to be a bad idea. The canonical url needs to be accessible.

Prestashop Version: 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @tom75,

Thanks for your report.
As @jolelievre said that the canonical header keeps the no-attribute URL which is not accessible.
ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by decom-media** [comment]
Just have a check on products with options, you will see that basically there is no url available for indexing, as there is always a 301 going on  (attached a screaming frog screenshot) 
![prestashop-canonical-301](https://user-images.githubusercontent.com/31710761/56963879-46c42880-6b5a-11e9-8e3d-e8752ea9072a.PNG)

**Comment by jolelievre** [comment]
Hello @tom75 
As explained in another comment https://github.com/PrestaShop/PrestaShop/issues/11150#issuecomment-488015961 (sorry I didn't see this issue yet) this will change in `176` version, these addresses will now be accessible.
If you want more details this was done with this PR https://github.com/PrestaShop/PrestaShop/pull/13009

This modification will be available in the coming 1.7.6 version, so I think we can close this issue if it's ok for you?

**Comment by decom-media** [comment]
Well, that sounds already like a solution for that problem - looking forward then to update to 1.7.6. - is there any release date available? (as, after researching quite a lot, this seems to be - at least one of - the reasons on my drop in SER)

thanks for your quick response!

**Comment by jolelievre** [comment]
You can download our nightly builds here https://nightly.prestashop.com/ if you want to test the next version in advance.

There is no official release date yet but we are aiming at a stable release in june

**Comment by decom-media** [comment]
the nightly build is no option for my productive page, therefore i have to wait then for the release of 1.7.6. - thanks anyway!
