### ISSUE TITLE
Delete categories selected with bulk action will remove all the categories

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13618]
**Describe the bug**
In the BO => Categories page, when we try to delete categories with bulk action will remove all categories

**To Reproduce**
Steps to reproduce the behavior: fresh install 1.7.6.x with English language / France country
1. Go to BO => Categories page
2. Select a category for example Clothes 
3. Delete with bulk action
4. All categories will be removed

**Screenshots**
https://drive.google.com/file/d/1X1nVUnx3gGW_JYZxzu9Ur7C0zpGB6i6L/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.1

**Comment by marionf** [comment]
@matks FYI
