### ISSUE TITLE
When I upgrade modules - Exception thrown by module autoupgrade on upgrade

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#13611]
Error! Exception thrown by module autoupgrade on upgrade. Error sent by Addons. You may need to be logged.

![Screen Shot 2019-04-30 at 1 44 28 PM](https://user-images.githubusercontent.com/6930263/56942623-4887ef00-6b4e-11e9-93e1-eb74907c2af2.png)

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

I did not manage to reproduce the issue with PS1751 during the upgrade of the 1-click upgrade module from 4.6.0 to 4.7.0
I attached a screen record
https://drive.google.com/file/d/1cZJcGP1f8rlNEUUXxPWn2GjZKkQeZgdM/view
Could you please try to clear cache, sign in to your account addons & try to upgrade the module again.
Thanks to check & feedback.

**Comment by TomHsiung** [comment]
I cleaned my Safari bower's cache. Then I cleaned the Prestashop's cache in the advanced parameters/performance page. After this operation, the back office reported xml file errors (country_modules_list.xml, and must_have_modules_list.xml). So I deleted these two files. Then I cleaned the Safari brewer cache again.

OK. I logged in back the back office, and the update icon for modules disappeared. The two modules remain their old version numbers.

![Screen Shot 2019-04-30 at 5 35 04 PM](https://user-images.githubusercontent.com/6930263/56953085-62392e80-6b6e-11e9-8d84-0e0dffcff939.png)

**Comment by khouloudbelguith** [comment]
@TomHsiung, in your Project_Folder/module/autoupgrade/config.xml, could you please check your current version
Thanks!

**Comment by TomHsiung** [comment]
I think it is 4.6.0

![Screen Shot 2019-04-30 at 5 46 11 PM](https://user-images.githubusercontent.com/6930263/56953775-df18d800-6b6f-11e9-84ed-2852f4143c9e.png)

**Comment by khouloudbelguith** [comment]
@TomHsiung yes, it is 4.6.0 & it is not the last one.
In the module manager page => Module Tab => search for the 1-click upgrade module & check if the button upgrade is displayed.
Thanks!

**Comment by TomHsiung** [comment]
There is no upgrade button.

![Screen Shot 2019-04-30 at 6 14 46 PM](https://user-images.githubusercontent.com/6930263/56955408-e17d3100-6b73-11e9-8f1d-70152e1b0c11.png)

**Comment by khouloudbelguith** [comment]
@TomHsiung, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TomHsiung** [comment]
It a Ubuntu 18.04 host machine.

Apache 2.4.29-1ubuntu4.6
PHP 7.2.17-0ubuntu0.18.04.1
Prestashop 1.7.5.1

**Comment by TomHsiung** [comment]
Now the upgrade icon turns up back, but still the original issue remains.

"Exception thrown by module autoupgrade on upgrade"

**Comment by khouloudbelguith** [comment]
@TomHsiung, did you tried to singing in before the upgrade of this module?
Thanks!

**Comment by TomHsiung** [comment]
Of course I have signed in the addons market with my account.

**Comment by khouloudbelguith** [comment]
@TomHsiung, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by TomHsiung** [comment]
Debug logs:

Data from PrestaShop Addons is invalid, and cannot fallback on cache.
Hide context
[▼
  "exception" => "cURL error 28: Operation timed out after 5000 milliseconds with 8316 bytes received"
]

**Comment by khouloudbelguith** [comment]
@TomHsiung, could you please check if the `allow_url_fopen ` is enabled on your server?
Thanks!

**Comment by TomHsiung** [comment]
Directive | Local Value | Master Value
-- | -- | --
allow_url_fopen | On | On

**Comment by khouloudbelguith** [comment]
@TomHsiung, thanks a lot for your feedback.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by TomHsiung** [comment]
Finally, I downloaded the autoupgrade module from the official addons market and uploaded and installed it via the BO module manager. And it was successful.

However, I didn't find the Theme Customization v1.0.10 on the addons market.

Tom

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

Thanks for your feedback.
You can find the last version of the Theme customization module on our official repository Github https://github.com/PrestaShop/ps_themecusto/releases/tag/v1.0.10
You need to clone it from GitHub.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by TomHsiung** [comment]
This issue happens again now.

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

>Error sent by Addons. You may need to be logged.

This issue happens again in your case?

Thanks!

**Comment by IranDec** [comment]
Hi
I have the same issue I can't download and update mail alert module even autoupgrade module too I will get the same 
Best Regards

also after i deleted var/cache (prod & dev).
I could install autoupgrade but not the second one.

and additionally, after I deleted cache when I check var/cache folder again I just had prod file, I cant see dev folder furthermore
Best Regards

**Comment by MattiaMarchiorato** [comment]
This software is full of bugs! 🐛
