### ISSUE TITLE
Bulk action & the Select all doesn't work in the SQL manager page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13620]
**Describe the bug**
In the SQL manager page, the bulk action doesn't work, if we select any option, the bulk action button is always disabled
Also, Select all doesn't work.

**To Reproduce**
Steps to reproduce the behavior: Fresh install 1.7.6.x with English language & France country
1. Go to BO => Advanced Parameters => Database
2. Create at least two SQL requests
3. Select any SQL request => the bulk action is disabled => Error
4. Click on Select all => doesn't work

**Screenshots**
https://drive.google.com/file/d/1dsjKkPtuGyWp4niaK3YMRDRuqMmr3e2w/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13765
