### ISSUE TITLE
Add to cart disabled

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#13625]
**Describe the bug**
Without touching anything, I began to receive reports from customers regarding shopping cart, the problem is that they can't add products to their cart even if product is in stock. Can't even update or delete from cart without refreshing website (AJAX disabled)
I have tried to disable AJAX but here are a few issues:
1. If AJAX is enabled, nothing works.
2. If AJAX is disabled, cart can update and remove products from the cart but nothing happens unless you refresh the cart page (in the console I get Empty string passed to getElementById() )

**To Reproduce**
1. product page
2. try to click on add to cart but the label in stock is visible but add to cart button is not clickable

**Screenshots**
This screenshot is from the cart page when I try to update or delete from the cart
![Captura](https://user-images.githubusercontent.com/7015860/57026950-4f406000-6c3b-11e9-9e1c-d3e358cf3a3c.PNG)

This screenshot is when the combinations and stock are OK but you can't add to the cart, the warning comes when you click in the quantity box or try to change the quantity
![Snap4](https://user-images.githubusercontent.com/7015860/57027577-0e494b00-6c3d-11e9-9dab-ba466b693a90.png)

**Additionnal information**
PrestaShop version: 1.7.0.x and 1.7.5.1
PHP version: 7.0 and 7.2

The behaviour began to reproduce in 1.7.0 and after upgrading to 1.7.5.1 the problem persists. I've tried to disable all overrides and modules but with no luck.

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

I did not manage to reproduce the issue with PS1.7.5.1 & the ps_shoppingcart module version 2.0.2.
I attached a vdeo record
https://drive.google.com/file/d/1CVeLbBFz9su3ocMq2BA5K8Re-WcBXhSx/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - ps_shoppingcart version
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ChineseNorris** [comment]
Here are my specs:

-Host : dedicated hosting
- Server setup with apache + engintron
![Captura](https://user-images.githubusercontent.com/7015860/57070941-3c7c6880-6cd9-11e9-805e-de21763f057a.PNG)
-ps_shoppingcart version : 2.0.2
- debug mode is enabled but no errors appears?
- PHP error logs attatched
[error.log](https://github.com/PrestaShop/PrestaShop/files/3137735/error.log)

-Apache error log.
[apache_error.log](https://github.com/PrestaShop/PrestaShop/files/3137832/apache_error.log)


-JS console log
[console.log](https://github.com/PrestaShop/PrestaShop/files/3137811/console.log)

Let me know if you need more info or something is missing! I'm really having troubles to debug this bug? Searching on internet I found people from forums with my similar issue, let's see if is a BUG.

Alex

**Comment by khouloudbelguith** [comment]
@ChineseNorris, in your error log file, you have a fatal error with the pagecache module.

```
[01-May-2019 10:05:19 Country] PHP Fatal error:  Uncaught Error: Call to undefined method IndexController::isRestrictedCountry() in /prestashop_url/modules/pagecache/pagecache.php:1311
Stack trace:
#0 /prestashop_url/modules/pagecache/pagecache.php(1281): PageCache::isRestrictedCountry()
```
You need to contact the module author about this issue.

Also, you have some warnings in the override AdminStatsController.php, you should to edit this override.

`[01-May-2019 10:05:18 Country] PHP Warning:  Invalid argument supplied for foreach() in /prestashop_url/override/controllers/admin/AdminStatsController.php on line 138`

Thanks to check & feedback

**Comment by ChineseNorris** [comment]
@jherry can you help us out about the error?

@khouloudbelguith  I've disabled the module but the error persists, the override is for retrieving stats in dashboard without creating invoices, so it shouldn't interfere with the cart, but I've deleted the override and tested again with same results in the firebug console.
I've tried almost everything but I'm out of ideas and don't know where to start debugging more since there is no critical error and all the errors redirects to /themes/core.js

**Comment by khouloudbelguith** [comment]
@ChineseNorris, could you please try to uninstall the ps_shoppingcart module, remove the ps_shoppingcart  folder from /Projet_Folder/modules/, clear cache & try to install it again.
Thanks to check if the issue persists or not?

**Comment by ChineseNorris** [comment]
@khouloudbelguith , I've checked and clear all cache without success, the problem in product page persists ( add to cart is non clickable) even when the ps_shoppingcart module is uninstalled. Tried reinstalling from fresh 1.7.5.1 and tried from prestashop addons.

**Comment by khouloudbelguith** [comment]
@ChineseNorris, so the issue occurs not only when Ajax is enabled?
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith , the cart don't work either with Ajax enabled or disabled, but I managed to "make it work"with a module called Attributegrid(https://www.presto-changeo.com/prestashop-17-modules/122-prestashop-attribute-grid-module.html)
But it only works when ajax is disabled, I can add products to the cart and my shop is still working, if I disable this module my customers can't even add products to the cart.
Thank you for you help!

**Comment by khouloudbelguith** [comment]
@ChineseNorris, thanks a lot for these clarifications.
Did you use the default theme provided by PrestaShop?
This issue occurs with all products or only with product which have combinations?
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith, yes, I've made a few modifications but they are design modifications only and a few functionalities that doesn't touch the cart or combinations, since all of that kind of modifications are made with modules. The issue is ocurring with products with and without combinations.

Thanks!

**Comment by khouloudbelguith** [comment]
@ChineseNorris,the issue occurs after these modifications?
In my case, with the default installation, no odifications, I did not manage to reproduce the issue.
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith , the issues occurs from one day to another without me doing modifications to the code or php versions or server at all, the cart was working properly with the modifications.

I know this won't occur in a fresh installation, but can occur after using the fresh install.
To reproduce this problem is really hard, instead of trying to reproduce it I think we should focus in debugging and try to get that bug, and then try to reproduce it and fix the problem.

Thanks!

**Comment by khouloudbelguith** [comment]
@ChineseNorris, thanks for your feedback.
When debug mode is enabled, is there any exception displayed in your FO?
Thanks!

**Comment by ChineseNorris** [comment]
@khouloudbelguith , no, I can't see any exception displayed in FO nor error at the javascript console, just the warning you can see in the first comment. Is there any other way to trace the bug?

Thanks!

**Comment by khouloudbelguith** [comment]
@ChineseNorris, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) and try to provide me again the php error file log.
Thanks!

**Comment by jherry** [comment]
Sorry for late reply I was on vacation.
@ChineseNorris Disable Page Cache module and test again. If you don't reproduce the issue without Page Cache then contact me here: https://jpresta.com/en/contact-us

**Comment by ChineseNorris** [comment]
@khouloudbelguith , I've cleared the cache without results and empty my error logs to see if I can get the error. I did not managed to get any error from the logs and the cart is still greyed out.
However I managed to make the cart work if the stock management is disabled ( I can add products to the basket if I allow selling products that have no stock) but the ajax cart is still bugged (when you try to update the cart in cart-page you still have to refresh the page)
@jherry I've done it and at the moment I can't get any error in the logs, I'll update you when I notice more pagecache errors and glad you had vacations, you are lucky to have them =D

**Comment by ChineseNorris** [comment]
Hello,

Doing more tests disabling and enabling the stock management the add to cart button is now working again with AJAX, however in cart section the AJAX function to update and delete products from the cart is still bugged (you click or enter another quantity or delete it from the cart and you have to refresh the page in order to update the cart)

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

Despite our several trials, we could not reproduce your issue with the provided information.
I tried with PS1.7.5.1 & PS1.7.5.2 => OK.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
