### ISSUE TITLE
Canonical missing on 1st page and rel="prev" missing on 2nd page

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#13629]
Pagination and canonical problems - in prestashop 1.7.5.1:

category pages are having a problem with missing prev tag and canonical tag missing and also wrong:

- the first page is ok, but, there is no canonical tag included
![canonicalwrong_page1_](https://user-images.githubusercontent.com/31710761/57069168-1b654900-6cd4-11e9-9656-48a4bc1f3d84.png)

- the second page is missing the rel="prev"
![canonicalwrong_page2_](https://user-images.githubusercontent.com/31710761/57069169-1b654900-6cd4-11e9-9a8c-93ef2c360d4a.png)

please check the attached images, i do not know if this is maybe also already fixed in the issue #13613, but, i dont think so

**Comment by khouloudbelguith** [comment]
Hi @tom75,

Thanks for your report.
Is it the same issue reported here: #9503?
Thanks to check & feedback.

**Comment by decom-media** [comment]
Hello @khouloudbelguith, 

i did edit now my post, to make it more clear and yes, the canonical part seems to be the same like the #9503 issue, as the canonical tag is missing on page 1, but, the second part of my issue is still not covered by this issue (maybe i should seperate it and open another issue) 

-> on the second page (?page=2) the rel="prev" tag is missing (but, on the rest of the pages it is included (?page=3, ?page=4 ,...)

**Comment by khouloudbelguith** [comment]
@tom75, thanks for these clarifications.
I did not manage to reproduce the issue with the PS1.7.5.1.
https://drive.google.com/file/d/1-_9OM_eiRsmFDVkjUq_ZYARVQXa4U2Fv/view
I tried with the Accessories category.
Thanks to check my screen record & feedback.
Thanks!

**Comment by decom-media** [comment]
@khouloudbelguith, well, it seems that there are different pages having different problems with canonical and prev tags

basically, the rel="prev" you are referring to, seems not to be in the head - cannot see it well, but, it does not look like you are showing the one which should be in the header.
i did find out, after checking a few other pages, that even the rel="next" is having wrong information in it, please check the pic - this IS page 2 and "next" is referring to page 2 (instead of 3) and no prev tag available and the canonical is referring to the 1st page instead of the 2nd page itself (which is different on another category page like "new items" - there is the canonical tag ok (at least starting from 2nd page)

![2canonicalwrong_page2_](https://user-images.githubusercontent.com/31710761/57077966-9f77fa80-6ced-11e9-9b0c-4aea46c277b2.png)
the screenshot was taken from a "normal" category page like "women"

there is something mixed up with "next", "prev" and canonical tags - different behaviour on different pages as well

**Comment by khouloudbelguith** [comment]
@tom75, I checked with another PS1.7.5.1 => OK, in the first & second page (Accessories category page)
Here's the link of the shop http://presta1and1.com/prestashop_1.7.5.1/index.php?id_category=6&controller=category&id_lang=1
Thanks to check & feedback.

**Comment by decom-media** [comment]
@khouloudbelguith, well, that installation is showing also the same problem:

url: http://presta1and1.com/prestashop_1.7.5.1/index.php?id_category=6&controller=category&id_lang=2&page=2 is showing the canonical tag: `<link rel="canonical" href="http://presta1and1.com/prestashop_1.7.5.1/index.php?id_category=6&amp;controller=category&amp;id_lang=2">` ... there is `&page=2` missing

also the `prev `tag is missing there (i cannot check `next`, as there are just 2 pages)

**Comment by khouloudbelguith** [comment]
@tom75, I checked the same link & &page=2 is displayed
![Capture](https://user-images.githubusercontent.com/16067358/57083478-e4edf500-6cf8-11e9-8856-5c65ea0773b4.PNG)
Also, the prev is displayed, if you search with this expression, you will find it
![Capture2](https://user-images.githubusercontent.com/16067358/57083535-fe8f3c80-6cf8-11e9-849f-87db7d99f8c8.PNG)

Thanks!

**Comment by decom-media** [comment]
@khouloudbelguith, the prev is not the one i am talking about - you are showing me always the one in the body - i am talking about the one which needs to be in the header as meta information - the next is already there, but, prev is just in pages starting from the 3rd page, in the second one it is missing.

the canonical i will check with more pages and let you know

**Comment by khouloudbelguith** [comment]
@tom75, in the second page, the `next` is also displayed in the body, in the third page also, the `previous` is displayed in the body also.
You can check this view-source:http://presta1and1.com/prestashop_1.7.5.1/index.php?id_category=6&controller=category&id_lang=2&page=2
In the third page also, `previous` is displayed in the body
http://presta1and1.com/prestashop_1.7.5.1/index.php?id_category=6&controller=category&id_lang=2&page=3
Thanks!

**Comment by decom-media** [comment]
@khouloudbelguith, well, after checking again everything, it seems that this problem is depending on the theme, which i did buy - the prev and next need to be in the header for seo reasons, i will check now with the developer of the theme if this is maybe related with his modifications.

**Comment by khouloudbelguith** [comment]
@tom75, thanks for your feedback.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
