### ISSUE TITLE
Access to BO is slow even from the same local network

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#13622]
Hello,

Access to BO is very slow even from I am from a same local network.

Tom

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

Tanks for your report.
We need more details to understand how we can reproduce your issue:
 - PrestaShop version, fresh install 1.7.5.1 or an upgrade from a previous version?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - Have you a lot of data?

Thanks!

**Comment by danirios93** [comment]
Disable gamification module and you will be set :P At least it worked for me, seems it uses lots of resources of the BO

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

What is the exact version of the module `gamification `did you use?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
