### ISSUE TITLE
Admin credentials after installation via docker

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#13624]
**Describe the bug**
I've followed [this guide](https://devdocs.prestashop.com/1.7/contribute/contribute_using_docker/) to install Prestashop via docker. Everything went well, however: I don't have any credentials to log in into the BO. Where do I find these credentials?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
Hi @rdy4ever,

As you started the docker-compose on the root folder of PrestaShop, you used the image `prestashop/prestashop-git` available on [Docker Hub](https://hub.docker.com/r/prestashop/prestashop-git/).

As notified in its readme, the default credentials are `demo@prestashop.com` / `prestashop_demo`.

Regards
