### ISSUE TITLE
HTML code appear when I try to add a picture too big in short description

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13639]
**Describe the bug**
HTML code appear when I try to add a picture too big in short description

**To Reproduce**
1. Edit a product in the tab catalog
2. Add a picture in the short description using the file manager (the size of the picture is 14mo)
3. See error

**Screenshots**
![Capture d’écran 2019-05-02 à 16 52 16](https://user-images.githubusercontent.com/3034677/57084492-aeb17500-6cfa-11e9-82d2-2df3c4d53a16.png)

**Additionnal information**
PrestaShop version: 1.7.5 / 1.7.6
PHP version: 7.1

**Comment by arouiadib** [comment]
When I test with PS 1.7.5.2 under debug mode and with an image file of 15mb, it returns an error message inside HTML markup as you said, but outside debug mode it only shows "SERVER ERROR" in the red popup (with 'close' button).



If you inspect elements under (Chrome dev tools example), under the 'Network' tab, you will see an HTTP response with 405 status code.  And I don't see any size comparison in the correspending php file : `admin-dev/file-manager/upload.php` ( BTW, this is the only place in source code where the 405 header is returned ).

Did you checked your php.ini file? En principe, it is located in /etc/php/7.1/apache2/php.ini.  There are two parameters there that you might tweak to resolve the issue:  `upload_max_filesize` and `post_max_size`. When I decrease them below 15mb, I get the error.

**Comment by hibatallahAouadni** [comment]
Hello @sarahdib 

I didn't manage to reproduce the issue with PS1778, it seems be fixed, see the attached screen record below:

https://watch.screencastify.com/v/KXQzGzGl3PGLFcLufS1p

![image](https://user-images.githubusercontent.com/23308427/134772723-4b4cf8d2-5c50-4f3f-9876-79d3055bab87.png)

Closing this issue as has been fixed :tada: 
PS: I attached below an image with size more than 14Mo, if you want to check the issue has been fixed or not :wink: 
https://drive.google.com/file/d/1xgoL56MPR-0-bO-YaRIS_v8jrUbtP9MS/view?usp=sharing

Thanks!
