### ISSUE TITLE
Invalid canonical URL created on checkout for products without attributes

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#13634]
**Describe the bug**
The product URL generated by PrestaShop on the checkout page is invalid for some products: the URL is generated with "id_product_attribute=0" which is not valid for a product without atttributes.

**To Reproduce**
1. In the BO, create a product without attributes and activate it
2. In the FO, add this product in your cart and click on "Checkout"
3. Click on the product link in the cart

**Screenshots**
![defect](https://user-images.githubusercontent.com/49909275/57077669-e9141580-6cec-11e9-90be-3dd9467c265a.png)
![defect_url](https://user-images.githubusercontent.com/49909275/57077808-3b553680-6ced-11e9-9a11-f3107d9bc851.png)

**Additional information**
PrestaShop version: 1.7.6.x just installed, default configuration
PHP version: 7.2.17

**Comment by jolelievre** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13635
@SimonGrn your test should run properly now
