### ISSUE TITLE
Sort by products in categories White Screen result on load

### ISSUE THREAD

**Issue by manu20gm** [PrestaShop/PrestaShop#13631]
**Describe the bug**
When I go to any Category in the shop and try to sort by any method (price, name, reference...) no result are showed, only the header and body of the categories but without products listed. There are only white div.

**To Reproduce**
1. Go to Any Category
2. Click on Sort By: "something"
3. The url are updated but no result is loaded
3. See no result loaded. But if you manually update the page it shows

**Screenshots**
![git1](https://user-images.githubusercontent.com/50202891/57074360-e5c85c00-6ce3-11e9-9d93-3753ff17001f.PNG)
![git2](https://user-images.githubusercontent.com/50202891/57074362-e5c85c00-6ce3-11e9-872f-f788039591e4.PNG)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @manu20gm,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record
https://drive.google.com/file/d/1uWVxqsRv-rcMU0_0Rb5HSM-eCR1muRUE/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by manu20gm** [comment]
Hope it helps
- Host: regalosgourmetonline.com Linux sd5158.lineagrafica.es 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- server setup and configuration: 

- 1. Server software version: Apache
- 2. PHP version: 5.6.40
- 3. Memory limit: 1024M
- 4. Max time of execution: 3600
- 5. Max size for uploading files: 24M

- PrestaShop version (source): 1.7.5.0
- debug mode report: none result
- PHP error logs: none result
- apache error log: none result:
- javascript console log: 
![git3](https://user-images.githubusercontent.com/50202891/57075427-178ef200-6ce7-11e9-968e-776cf1420363.PNG)

**Comment by khouloudbelguith** [comment]
@manu20gm, you don't use the default theme Classic provided by PrestaShop? is it?
Thanks!

**Comment by manu20gm** [comment]
@khouloudbelguith it's the default theme classic only with design modifications

Thanks!

**Comment by manu20gm** [comment]
The problem was resolved, this bug was caused by a third-party module incompatibility

**Comment by khouloudbelguith** [comment]
@manu20gm, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
