### ISSUE TITLE
Better alert for customer creation and customer info edit forms

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13640]
**Is your feature request related to a problem? Please describe.**
Following 1.7.5.2 patch, when an existing customer having a first name such as "John R.Hamond" wants to modify its account info an alert is raised when saving saying "Incorrect name".
This is because his/her name doesn't match the new forms' conditions.
Problem is that this name used to be good and is not anymore, we need to explain it.

![Capture d’écran 2019-05-07 à 09 39 17](https://user-images.githubusercontent.com/47456895/57281825-06116580-70ac-11e9-841d-acd7482c85fc.png)

This alert is not explicit enough as the name was previously good and not anymore. We need to inform the customer about new conditions introduced in 1.7.5.2 .

**Todo:**
- [X] Study feasibilty
- [ ] Add new error message 

**Describe the solution you'd like**

It is first necessary to study the complexity to modify this text. The message might come from the database content validation and not from the form itself. In the first case, it would require to create a specific event.

**If the message is generated at the form level:**
An alert with more context/information about fields conditions for the "First name" and "Last name" fields:
"
Invalid name.
The following characters are not accepted: / \ ` ^ *
The characters . and 。 are allowed only if they are directly followed by a space or the end of the string.
"

**If the message is generated at the db level:**
Add a message below the fisrtname and lastname field. The message should always be displayed, like in this example: 
![57281825-06116580-70ac-11e9-841d-acd7482c85fc](https://user-images.githubusercontent.com/47456895/58025641-337efa00-7b15-11e9-9c88-827f00c5d44f.png)

Text: 
"
not accepted: / \ ` ^ *
A space is necessary after a "."
"

---
Should be added to the account creation form, the edit account and the form in the checkout.

Thanks,

**Comment by ghost** [comment]
@MatShir What do you think of the solution ?

**Comment by matks** [comment]
We also forbid the use of / character, which prevents people of using a last name such as "Morin / Dubois".

**Comment by ghost** [comment]
@TristanLDD Do you have a "best practice" for this kind of alert/message?

**Comment by colinegin** [comment]
As discussed with the team, if we cannot control the error message, we should add a generic message under the names field. 

@LouiseBonnard and @TristanLDD what text should we put and where ? Under both fields ?

**Comment by TristanLDD** [comment]
Best practice for this kind of message would be to display it as a contextual error message when the entry isn't correct, as it concerns just a few cases. 

I'm not a fan of writing the whole input characters rules under the field as it sounds very complicated for a simple name field, we don't usually see messages like that on any other name fields.

Is changing the error message really no option?

**Comment by ghost** [comment]
Feasibility will be studied first to see what's possible.

I agree, ideally, the best would be to display the message only when the name is not correct.

**Comment by LouiseBonnard** [comment]
One first thing is to check whether we can improve the translation key with clearer wording, and for that I need all forbidden characters. If it is good, the next step should not be too complicated since we just need to keep the existing string and add a little help.

**Comment by colinegin** [comment]
@eternoendless @PrestaShop/prestashop-core-developers can you study the feasibility so that we can take a quick decision on what should be done ?

To be noted : the issue is the same on the checkout form.

**Comment by jolelievre** [comment]
@samuel-pires @colinegin so it is feasable ^^ feel free to test the PR to see if it matches what you expected
