### ISSUE TITLE
Installer: suggest localhost as alternative default value for host

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13646]
Today I installed a PrestaShop 1.7.5.2 on a Simple Hosting instance from gandi.net .
In the installation process, at the step for configuring the database, I could not connect to my database. I had to change "127.0.0.1" to "localhost" to successfully connect. Dont know why 😐.

**Describe the solution you'd like**
Either update the default value `127.0.0.1` to `127.0.0.1 / localhost`
or add a helper message below "If 127.0.0.1 does not work, try localhost". Maybe display the helper message only after a 1st failed attempt to connect.

**Describe alternatives you've considered**

**Additional context**
mysql 5.7, hosted on gandi.net, php7.1

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment]
This came from your server configuration.
You can tell to your users to accept only localhost and not 127.0.0.1.
For example:
```
MariaDB [mysql]> select Host, User from user\G;
*************************** 1. row ***************************
Host: %
User: dba
*************************** 2. row ***************************
Host: localhost
User: modok
*************************** 3. row ***************************
Host: localhost
User: phpmyadmin
*************************** 4. row ***************************
Host: localhost
User: prestashop
*************************** 5. row ***************************
Host: localhost
User: root
5 rows in set (0.000 sec)

ERROR: No query specified
```

**Comment by matks** [comment]
@PierreRambaud Thanks for the info 😉

What about the help message for the users ? The content can change indeed 😃for example "Having trouble to setup your database connection, see our FAQ" and in the FAQ we add your statement about mysql host and user settings.

If people use root superadmin database user it works 🤣but I think we should encourage proper secure behavior.

**Comment by PierreRambaud** [comment]
The return code from MySQL will be the same as if you provide a wrong password / user.
It's a kinda useless :/

**Comment by Progi1984** [comment]
@matks @PierreRambaud So no correct solution ?

**Comment by PierreRambaud** [comment]
@PierreRambaud afaik, there is no correct solution, the server needs to be properly configured. 
This isn't something PrestaShop should manage.

**Comment by khouloudbelguith** [comment]
Hi @matks!

So, can we close this issue?

Thanks!

**Comment by PierreRambaud** [comment]
I close the issue. Feel free to reopen it if you think it's still relevant and not overkill.
