### ISSUE TITLE
Add a new step in checkout process - new Hook and Classes

### ISSUE THREAD

**Issue by tonyinuma** [PrestaShop/PrestaShop#13642]
There are different steps to make the purchase of a product, before they have 5 in prestashop, now they are 4. It can vary according to the store.

To add a new step to the purchase process, as in my case, I would like to add the step where it helps the customer to choose between the ticket or the invoice, which is before the payment process and after the delivery. It would be great if there was a hook for the new payment processes, according to what the store needs to implement.

1. What hook to use add for the new purchase process.
2. What classes should be created for a new purchase process. What is the way to create a new step.urchase process. What is the way to create a new step.

**Comment by khouloudbelguith** [comment]
Hi @tonyinuma,

You can use the `displayAfterCarrier` hook. This hook is displayed after the carrier list in Front Office Located in: /classes/checkout/CheckoutDeliveryStep.php
For more details, you can follow our dev documentation: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/
I close the issue, feel free to open a new one when needed.
Thanks!
