### ISSUE TITLE
Prestashop 1.7 : Site only accessible in debug mode

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#13649]
I have an issue with a test version of our site under Prestashop 1.7
http://vps680775.ovh.net/
Login : user
Password : wikao
(I've set a password so that Googlebot does not crawl the site and sees the content as duplicate content)
It only works in debug mode. As soon as I disable the debug mode => blank page (both on the back and on the front office)

Do you know why ?

Thanks in advance for your help
Have a nice day ;-)

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Thanks!

**Comment by rdy4ever** [comment]
> (I've set a password so that Googlebot does not crawl the site and sees the content as duplicate content)

You don't need to do that. Just replace the content of robots.txt with:
```
User-agent: *
Disallow: /
```
That's all you need to do in order to prevent the site from being indexed

**Comment by wikao2** [comment]
Let it down. I reinstall Prestashop and now it works.
Thank you for your tip @rdy4ever
