### ISSUE TITLE
Help Side Bar on Catalog > Products isn't very helpful

### ISSUE THREAD

**Issue by TeapotCallum** [PrestaShop/PrestaShop#13647]
**Describe the bug**
Help Side Bar on Sell > Catalog > Products isn't very helpful.
None of the things it says it covers in the list is actually covered on the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sell > Catalogue > Products.
2. Click on Help.

Having a look at the iframe URL and compared it to the 1.6 version it seems like a lot of information has just been removed!
Obviously, we cannot just use the 1.6 one as everything has changed for products.

1.7 - https://help.prestashop.com/en/doc/AdminProducts?version=1.7
1.6 - https://help.prestashop.com/en/doc/AdminProducts?version=1.6

**Screenshots**
![Screen Shot 2019-05-03 at 09 33 33](https://user-images.githubusercontent.com/15929456/57126907-97b86480-6d86-11e9-8be6-9953a3c3b80a.png)

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: Not relevant

**Comment by khouloudbelguith** [comment]
Hi @TeapotCallum,

Thanks for your report.
This is a desired behavior, because the documentation of the PS1.6 is so heavy.
You can follow our documentation in details in this link: http://doc.prestashop.com/display/PS17/User+Guide
Thanks for your understanding!
