### ISSUE TITLE
Creating useless comments when using ajax to refresh the address form in checkout

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13652]
**Describe the bug**
On checkout page, for a shop with multiple countries available, you can use the country dropdown to select your country. When you do so, an ajax request is performed to `/order?ajax=1&action=addressForm`. This returns the updated HTML form which is then inserted into the checkout page.

But when it does so, it does replace everything. So if you perform this dropdown multiple times you see the template grow bigger and bigger 😄.

**To Reproduce**
1. Setup a shop using `develop` branch, enable at least 2 countries from BO. You need to be able to choose a country in the checkout page.
2. Go to checkout page, so for a French shop it is `/commande`
3. Have a look at HTML section `checkout-addresses-step` it looks like this

<img width="475" alt="Capture d’écran 2019-05-03 à 12 14 57" src="https://user-images.githubusercontent.com/3830050/57131748-b1b17180-6d9d-11e9-9ece-cbfc957c2c51.png">

4. Choose another country. It refreshes the form. Do this multiple time. Look again at HTML section `checkout-addresses-step`. Now it looks like this 😄 

<img width="555" alt="Capture d’écran 2019-05-03 à 12 15 25" src="https://user-images.githubusercontent.com/3830050/57131790-cd1c7c80-6d9d-11e9-8061-ae11eaf47e3e.png">

**Additional information**
PrestaShop version: develop
PHP version: php7.2

**Comment by matks** [comment]
It's harmless because it's only html comments. But it's not very clean either.

**Comment by PierreRambaud** [comment]
These comments came from the debug mode to help developers to create themes and are not displayed in production. Because a comment could not be selected with `selectors` I'm not sure we're able to do something :/

**Comment by matks** [comment]
> These comments came from the debug mode to help developers to create themes and are not displayed in production.

Considering this, then this is 100% harmless

**Comment by khouloudbelguith** [comment]
Hi @matks,

I have the same issue with `develop` branch.
With PS1752, it is OK.
Thanks!

**Comment by marionf** [comment]
@matks Is it a regression of 1.7.6.0 ?
If yes, we should add it to the 1.7.6 backlog

**Comment by matks** [comment]
> @matks Is it a regression of 1.7.6.0 ?
> If yes, we should add it to the 1.7.6 backlog

I dont know, but anyway this is really harmless. Nothing bad can come of it, it's just a "clean code" issue.

**Comment by PierreRambaud** [comment]
Yes, this is really harmless. In fact, as I understand, we use the `replaceWith` jquery function (https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/listing.js#L153) with the new content:
```html
<!-- begin my-template.tpl -->
<div id="content">blabla</div>
<!-- end my-template.tpl -->
```

because comments are not selected, it's added again, and again, each time we use this kind of replacement.

**Comment by PierreRambaud** [comment]
@marionf @khouloudbelguith I'm able to reproduce the bug in 1.7.5.2, so this is not a regression and I think can be remove from 1.7.6 backlog
![image](https://user-images.githubusercontent.com/1462701/59258279-f7344a80-8c37-11e9-9e4f-e2c6abad9802.png)

**Comment by matks** [comment]
I close as I think it's insignificant
