### ISSUE TITLE
price doesn't show when stored in a variable

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#13653]
If I do 

`{$priceht = $product.price_tax_exc}{$priceht}`

That returns me the price

but if I do

`{$pricettc = $product.price}{$pricettc}`

That returns me nothing at all, still $product.price alone shows me the price taxe included.

:(

**Comment by khouloudbelguith** [comment]
Hi @vincent-dp,

In your product page, you can display the prices with taxes by editing the /Project_Folder/themes/classic/templates/catalog/_partials/product-prices.tpl
Replace this 

```
{if $priceDisplay == 2}
        <p class="product-without-taxes">{l s='%price% tax excl.' d='Shop.Theme.Catalog' sprintf=['%price%' => $product.price_tax_exc]}</p>
      {/if}
```

by this 

```
{*{if $priceDisplay == 2}*}
        <p class="product-without-taxes">{l s='%price% tax excl.' d='Shop.Theme.Catalog' sprintf=['%price%' => $product.price_tax_exc]}</p>
      {*{/if}*}
```

Thanks to check & feedback.

**Comment by vincent-dp** [comment]
I don't need, as I told you {$product.price} already shows it

**Comment by khouloudbelguith** [comment]
@vincent-dp, what is the exact edited file which you added this line `{$pricettc = $product.price}{$pricettc}`?
Thanks!

**Comment by vincent-dp** [comment]
templates/catalog/_partials/product-prices.tpl

**Comment by khouloudbelguith** [comment]
@vincent-dp, you just closed the issue? it is fixed?
Thanks!

**Comment by vincent-dp** [comment]
Yes, it was just a typo
