### ISSUE TITLE
Lets automatically generate hook titles and descriptions

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#13655]
**Problem**

I got the task where I need to update hooks information in three different places - more info here: https://github.com/PrestaShop/PrestaShop/issues/13408
In hook.xml and sql I expected this to be too much of writing and very error prone if you type them all by hand.

by creating hook names collector scripts https://github.com/PrestaShop/PrestaShop/pull/13593 I found that in a short period we introduced **219** new hooks - that's a lot to write by hand!

Unfortunately the script right now collects only the hook names from options form, identifiable object form, and from grids but it would be great to have some generated titles and descriptions.

There will be way more hooks in the future so this make sense to have such thing.

**Solution**

I think for grid hooks, option form hooks and identifiable object hooks the titles and descriptions can be generated automatically due to the titles and descriptions are very similar:

```xml
<hook id="actionWebserviceKeyGridQueryBuilderModifier">
      <name>actionWebserviceKeyGridQueryBuilderModifier</name>
      <title>Modify Webservice grid query builder</title>
      <description>This hook allows to alter Doctrine query builder for Webservice grid</description>
    </hook>
    <hook id="actionWebserviceKeyGridFilterFormModifier">
      <name>actionWebserviceKeyGridFilterFormModifier</name>
      <title>Modify filters form for Webservice grid</title>
      <description>This hook allows to alter filters form used in Webservice</description>
    </hook>
```

```xml
    <hook id="actionSqlRequestGridQueryBuilderModifier">
      <name>actionSqlRequestGridQueryBuilderModifier</name>
      <title>Modify SQL Manager grid query builder</title>
      <description>This hook allows to alter Doctrine query builder for SQL Manager grid</description>
    </hook>
    <hook id="actionSqlRequestGridFilterFormModifier">
      <name>actionSqlRequestGridFilterFormModifier</name>
      <title>Modify filters form for SQL Manager grid</title>
      <description>This hook allows to alter filters form used in SQL Manager</description>
    </hook>
```

in this sample the titles and descriptions are very similar - the only part that is being different is the dynamic hook name id.

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13593
We agreed to go with Tomas suggestion:

> I think for grid hooks, option form hooks and identifiable object hooks the titles and descriptions can be generated automatically due to the titles and descriptions are very similar

**Comment by jolelievre** [comment]
Thanks @tomas862
