### ISSUE TITLE
Regression on price calculation in FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13658]
**Describe the bug**
Regression on price calculation in FO when you have cart rules and specific display price in customer group

**To Reproduce**
Scénario 1:
1. Set your customer group to display price tax excl
2. Create a cart rule of 10%
3. Create a product of 10€ tax excl, 20% TVA
4. Total tax excl is 8.80 instead of 9
5. Amount of tax incl is 2 instead of 1.80€

Scénario 2:
1. Set your customer group to display price tax incl (by default)
2. Create a cart rule of 1€ tax incl
3. Create a product of 10€ tax excl, 20% TVA
4. Total tax incl is 12 instead of 11
5. Amount of tax incl is 2 instead of 1.83€

Scénario 3:
1. Set your customer group to display price tax incl (by default)
2. Create a cart rule of 10%
3. Create a product of 10€ tax excl, 20% TVA
4. Amount of tax incl is 2 instead of 1.80€

**Screenshots**
https://docs.google.com/spreadsheets/d/1y-4p2cIDeIF9SIxVPUtZ604OJutLDHVu9uPpoE1QirE/edit#gid=0

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
@tomlev Behat tests incoming \o/

**Comment by tomlev** [comment]
unfortunately behat will no help with this issue because it's more related to display than calculation...
E2E tests will.
