### ISSUE TITLE
Cannot see carrier buttons

### ISSUE THREAD

**Issue by jotakar** [PrestaShop/PrestaShop#13654]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by jotakar** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Screenshots**
> If applicable, add screenshots or screenrecords to help explain your problem.
> 
> **Additionnal information**
> PrestaShop version: N/A
> PHP version: N/A

Prestashop 1.6
Theme: Panda
When I arrive to the step when you have to select carrier I see the list of carriers, but the radio buttoans appears and, inmediately, dissapears. 
It's posible select any carrier clickin in their names, but radio buttons and check buton (for accpet conditions) dissapears...
Any idea?

**Comment by khouloudbelguith** [comment]
Hi @jotakar,

I did not manage to reproduce the issue with the last version PrestaShop 16124 & PS1752.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
Thanks for understanding!
I close the issue, feel free to open a new one when needed.
Thanks!
