### ISSUE TITLE
Products import doesn't import at all without errors in PS 1.7.5.2

### ISSUE THREAD

**Issue by Fixmetal** [PrestaShop/PrestaShop#13673]
Hello everybody,
I'm trying to import stuff to migrate from another E-Commerce platform.
I've successfully imported every object since version 1.7.4.x (can't recall). By now I need to complete importing stuff and start using PS as main site.
I've updated from 1.7.5.0 to 1.7.5.2 with not an error.
After the update I've imported customers + addresses flawlessly.
Now I've started importing products but it just doesn't work. Import procedure works fine but products are not actually imported, they are not even present in ps_product nor in the ps_stock_available tables (IDs/rows not present).
Categories for products being imported are present and correctly chained.
Debug mode on does not shows up any entries to sort this out. Not even logs track any errors.

Server side PHP 7.2
PS version 1.7.5.2

Thanks in advance for anybody willing to help.

**Comment by khouloudbelguith** [comment]
Hi @Fixmetal,

I made an upgrade from PS1.7.4.4 to PS1.7.5.2 with the 1-click upgrade v4.7.0 successfully.
https://drive.google.com/file/d/18t1bzUls03Eo--XpVLPTNHKvyOdhnC5e/view
In the import page, when I import products, it is OK
I attached a video record.
https://drive.google.com/file/d/1oyHx1MbEtGpWc54T5v4xp4z2IQCHfnIU/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Fixmetal** [comment]
I found out that the problem was due to "Use product reference as key" option being enabled so this is no bug.
Thanks for your concern.

**Comment by khouloudbelguith** [comment]
@Fixmetal, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
