### ISSUE TITLE
Prestashop 1.7.2 search from app BAD result

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#13672]
**Describe the bug**
Prestashop 1.7.2 has a bug function on search classes that return full of non pertinent result. I've ever seen a fix from official bug trace, but there is a fix available in many forum that consist in replace the classes with the 1.7.3 one. 

There is a fix for the 1.7.2 search that allow to use internal and mobile app search in a usable way? Its incredible that we cant use the search function of an ecommerce ^^!

Thanks

**To Reproduce**
Make a web service search request, you'll get a lot of poor result (incredible but true ...)

This is a normal search result provided by doofinder:
https://store.sixrace.it/it/#/dfclassic/query=carene%20panigale%20final%20edition&query_name=match_and

This is the doofinder module override the internal search:
https://store.sixrace.it/it/ricerca?controller=search&s=carene+panigale+final+edition

Our elastichsearch result (not visible now due to doofinder override work similar).

Default prestashop integrated search work in a "usable" way after the fix from 1.7.3 (usable mean about 30% of the usability of a decent search engine .. ).

This is the screenshot of the search made by knowband app (that use internal ps search)... 100% of not pertinet result. Upper there is every object that has at least one word in one field  O_O !

![image](https://user-images.githubusercontent.com/24798703/57190827-27911680-6f1f-11e9-9bc5-d0b2032090f4.png)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2
PHP version: 7 fpm

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Thanks for your report.
ping @eternoendless @matks @PrestaShop/prestashop-core-developers what do you think about the  web service search request?
Thanks!

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay.

This is something related to the doofinder module, you should see with them for more information.
If you think the problem also exist with a fresh install, feel free to reopen the issue.

Kind regards
