### ISSUE TITLE
Composer update lead to ClassNotFoundException for ICanBoogie\CLDR\RunTimeProvider

### ISSUE THREAD

**Issue by cereal-s** [PrestaShop/PrestaShop#13688]
Hello,

after performing `composer update` I got this error (in all pages, FO and BO):

```
(1/1) ClassNotFoundExceptionAttempted to load class "RunTimeProvider" from namespace "ICanBoogie\CLDR".Did you forget a "use" statement for another namespace?
--
in Repository.php line 84
at Repository->__construct('en-us')in Tools.php line 724
at ToolsCore::getCldr(object(Context))in Currency.php line 101
at CurrencyCore->__construct(1)in Currency.php line 614
at CurrencyCore::getCurrencyInstance(1)in Tools.php line 682
at ToolsCore::setCurrency(object(Cookie))in FrontController.php line 350
at FrontControllerCore->init()in Controller.php line 262
at ControllerCore->run()in Dispatcher.php line 511
at DispatcherCore->dispatch()in index.php line 28
```

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.17
Linux: Ubuntu 18.04
Web Server: NGINX

I have also installed a brand new copy of PS, a new database and all, and after the update, I get the same issue. Is it not possible to perform a composer update? And, can I add packages through composer? Thank you.

**Comment by khouloudbelguith** [comment]
Hi @cereal-s,

Did you installed the stable version PS1.7.5.1 from our official website?
The stable version doesn't have the composer.json file, how you could run `composer update`?
Thanks!

**Comment by cereal-s** [comment]
Hi,

Thank you for your reply!

Yes, the PS is the 1.7.5.1 stable version downloaded from your website, while I got the composer.json file from https://raw.githubusercontent.com/PrestaShop/PrestaShop/develop/composer.json

My original goal was to include jcupitt/php-vips[0] through composer, which I have done by running the command in my box, then I just uploaded the vendor/jcupitt folder and the composer.json file to the server and executed a composer dump-autoload. I got everything to work for two weeks. Yesterday, after running the 1-click upgrade module I upgraded PS to 1.7.5.2 and everything worked fine except for php-vips (I'm using it to override the ImageManager.php class and add support for TIFF files), the server started returning the same exception of above ClassNotFoundExceptionAttempted but for php-vips and only when the ImageManager.php was executed, so I ran the composer update command and got the reported error. At that point, I reinstalled everything by uploading a clean archive, included the composer.json file and run an update without including php-vips and got the same error.

To be honest, when I ran the first update I didn't recall the file was added by me ^^'

Should I switch to another version? Or is it possible to get the composer.json for the stable version? 

[0] https://github.com/libvips/php-vips

**Comment by khouloudbelguith** [comment]
@cereal-s, you just added the composer file from the develop branch, but you are using the PS1.7.5.1 version.
You can find here the composer.json file for the PS1.7.5.1 https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/composer.json
Thanks to check & feedback.

**Comment by cereal-s** [comment]
@khouloudbelguith I knew I was doing something wrong. Thank you very much, this solved the issue.

**Comment by khouloudbelguith** [comment]
@cereal-s, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
