### ISSUE TITLE
Customer can only ask for a return out of customer account if status "order delivered" reached

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#13697]
Hi, 

customers can only ask for a return out of costumer account if status "order delivered" (ID 5) is set manually in orders. 

How to reproduce:
1.) have an order from customer which has created a costumer account
2.) set order status as "shipped" or any other status
3.) log into customer account
4.) go to "orders" 
5.) select an placed order
6.) try to mark items which you want to return and you will see that the function is not available. 
7.) go to backoffice orders and set status "order delivered" (ID 5) 
8.) make steps 1.) to 6.) again and function to mark items for return is working

Due to this behavior of Prestashop, I have to monitor each order and constantly check when the order has been delivered to the customer and then manually set the status "order delivered" (ID 5). That means a lot of work that the shop owner does not have. But without the manual set of this status, the customer can not request a return via his customer account.

Prestashop 1.7.5.1 and older versions

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I tried with PS1.7.5.2, when the status of the order is set to `Delivered` or `Shipped`, we can return a product from the FO
![image](https://user-images.githubusercontent.com/16067358/57307343-4a1c5e80-70dc-11e9-9ac2-b7e06918a8b1.png)
For those statuses, we have the "Set the order as shipped." option is checked => so we can return products
![image](https://user-images.githubusercontent.com/16067358/57307547-abdcc880-70dc-11e9-85ad-3803df14de97.png)
Thanks to check & feedback

**Comment by didi-2018** [comment]
Hi @khouloudbelguith maybe it is working with 1.7.5.2 but I have the problem with 1.7.5.1

and my status "shipped" has the option "set order as shipped" too

![image](https://user-images.githubusercontent.com/44971218/57310015-58bd4280-70e9-11e9-9dd7-b2eecd8ac45a.png)

**Comment by khouloudbelguith** [comment]
@didi-2018, could you please try to select the option `Set the order as paid.` & the option `Show delivery PDF.` & save.
Thanks to check & feedback

**Comment by chendayin** [comment]
111

**Comment by khouloudbelguith** [comment]
@chendayin, could you please add some information about your last comment?

**Comment by didi-2018** [comment]
@khouloudbelguith I selected "set order as paid" and now it is working with status "shipped". Thank you sooooo much ♥ ♥ ♥

**Comment by khouloudbelguith** [comment]
@didi-2018, you are welcome, I close the issue.
Feel free to open a new one when needed.
Thanks!
