### ISSUE TITLE
Incorrect value after udating product quantity in cart

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#13708]
**Describe the bug**
Changing product quantity in cart works like random.

**To Reproduce**
1. Add any product to cart and go to cart.
2. Click UP arrow to change product quantity or type quantity manually.
3. Repeat step 2 few times.
4. Result product quantity is random.

**Screenshots**
https://sendvid.com/jgk6d5jj
In my example when I type 10, it sends quantity 6 in debugger. Then when I click down arrow to 9, it changes to 15 with quantity 5 in debugger. And there is no price update. Next when I click down arrow it works. But when I type value 1 there is no price update again. It works totally random.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Flower7C3,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1G_JPdct19KscD6Kf6MQe7073XR9XAbSC/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Flower7C3** [comment]
Hi.
I find out, that JS event `updateCart` has no value in `reason` when cart value was changed with input value. So action cart refresh was not send.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/3767861/58837477-00cc1a00-865c-11e9-96aa-73b000c0520b.png">

In addition there is no JS event like `beforeUpdateCart` which will show spinner and/or disable change buttons and input during quantity change. Here is my code:
```
_prestashop2['default'].on('beforeUpdateCart', function (data) {
	if (data.$target) {
		var $parent = data.$target.closest('.bootstrap-touchspin');
		$parent.find('.fa-spinner').removeClass('hidden');
		$parent.find('input').attr('disabled', true);
	}
});
```

Bug only exists in my clients shop theme. It seems to be not related with PS core.

**Comment by khouloudbelguith** [comment]
@Flower7C3, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
