### ISSUE TITLE
Critical error on PHP 7.1 due to deprecated function usage.

### ISSUE THREAD

**Issue by Shakarhaba** [PrestaShop/PrestaShop#13719]
#### Describe the bug
mcrypt_get_iv_size function has been deprecated since PHP 7.1.
It causes a critical error when accessing for example the modules page or the translations.

If the module does not use the legacy encryption functions no critical error, but the file causing an error is in the source of prestashop, not the module, so in Prestashop there should be a test before executing that function to see if it's PHP 7.2 or lower and use an appropiate encrytion.

#### Expected behavior
mcrypt should be removed and used something like bcrypt or openssl_encrypt instead or not call this legacy encrypt method at all if it's running v7.1 or newer or openssl_encrypt is available.

#### Steps to Reproduce
1. Have PHP 7.2.4 running
2. Have a module that uses this legacy encryption. In my case it's psmegamenu from http://www.prestabrain.com
3. Navigate to Modules > Modules & Services
4. Get the exception

**Screenshots**
```
classes/PhpEncryptionLegacyEngine.php @ line 53:
$this->ivSize = mcrypt_get_iv_size($this->cipher, $this->mode);
```
![image](https://user-images.githubusercontent.com/23308427/134773289-60d10782-3daa-4b49-9332-0ddb38c95d67.png)

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Shakarhaba,

Thanks for your report.
What is the exact version PrestaShop did you use?
These errors are displayed in your var/logs/dev.log file?
Thanks!

**Comment by Shakarhaba** [comment]
Hello @khouloudbelguith 

The version of Prestashop is 1.7.5.2.
Yes the error make it to the logs.

**Comment by khouloudbelguith** [comment]
@Shakarhaba, I did not manage to reproduce the issue with PS1.7.6.0beta1 & PHP7.1.
Here's my dev.log
[dev.log.zip](https://github.com/PrestaShop/PrestaShop/files/3198580/dev.log.zip)
Thanks to check & feedback

**Comment by Shakarhaba** [comment]
@khouloudbelguith mcrypt_get_iv_size was alerting a deprecation in 7.1 but still functioning
In 7.2 it's totally removed, you should get a deprecation notice with 7.1 and the critical error with 7.2

![image](https://user-images.githubusercontent.com/1680143/58244285-97423680-7d52-11e9-8ab4-5693964b23b1.png)

```
UndefinedFunctionException
--
Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "mcrypt_get_iv_size" from the global namespace.    at classes\PhpEncryptionLegacyEngine.php:53   at PhpEncryptionLegacyEngineCore->__construct('9b92830da4e70f5a8badd764a9e11e2c')      (modules\psmegamenu\psmegamenu.php:46)   at PsMegaMenu->__construct()   at ReflectionClass->newInstance()      (src\Core\Foundation\IoC\Container.php:130)   at PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClassName('psmegamenu', array('psmegamenu' => true))      (src\Core\Foundation\IoC\Container.php:163)   at PrestaShop\PrestaShop\Core\Foundation\IoC\Container->doMake('psmegamenu', array('psmegamenu' => true))      (src\Core\Foundation\IoC\Container.php:176)   at PrestaShop\PrestaShop\Core\Foundation\IoC\Container->make('psmegamenu')      (src\Adapter\ServiceLocator.php:65)   at PrestaShop\PrestaShop\Adapter\ServiceLocator::get('psmegamenu')      (classes\module\Module.php:1137)   at ModuleCore::coreLoadModule('psmegamenu')      (classes\module\Module.php:1116)   at ModuleCore::getInstanceByName('psmegamenu')      (src\Core\Addon\Module\ModuleRepository.php:473)   at PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepository->getModule('psmegamenu', false)      (src\Core\Addon\Module\ModuleRepository.php:562)   at PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepository->getModulesOnDisk(false)      (src\Core\Addon\Module\ModuleRepository.php:213)   at PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepository->getFilteredList(object(AddonListFilter))      (src\PrestaShopBundle\Controller\Admin\Improve\ModuleController.php:116)   at PrestaShopBundle\Controller\Admin\Improve\ModuleController->manageAction()      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:151)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:200)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)      (admin6500wrics\index.php:88)
```

**Comment by khouloudbelguith** [comment]
@Shakarhaba, what are the exact steps that you followed to get this exception?
Thanks!

**Comment by Shakarhaba** [comment]
@khouloudbelguith 

1) Have PHP 7.2.4 running
2) Have a module that uses this legacy encryption. In my case it's psmegamenu from http://www.prestabrain.com
2) Navigate to Modules > Modules & Services
3) Get the exception

If the module does not use the legacy encryption functions no critical error, but the file causing an error is  in the source of prestashop, not the module, so in Prestashop there should be a test before executing that function to see if it's PHP 7.2 or lower and use an appropiate encrytion.

**Comment by khouloudbelguith** [comment]
@Shakarhaba,

Could you please provide me the `psmegamenu` module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
@Shakarhaba, thanks for the module.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1 & PHP 7.1
![image](https://user-images.githubusercontent.com/16067358/58326183-fcb22800-7e23-11e9-9c7d-2fdf8810583e.png)
![image](https://user-images.githubusercontent.com/16067358/58326212-0b98da80-7e24-11e9-89a7-055b902327ac.png)
Those methods are used in the https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0-beta.1/classes/PhpEncryptionLegacyEngine.php class
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by florine2623** [comment]
I'm closing the issue. I can't retest it as the website you mentioned is not working anymore :

<img width="974" alt="Screenshot 2023-12-27 at 11 05 13" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a233e2b4-d413-4143-8579-6db0b94577e6">
