### ISSUE TITLE
Travis builds regurlarly fail because of timeout on a specific endpoint

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#13723]
**Describe the bug**
Travis often fails when we try to run tests, especially during the installation of PrestaShop.

```
file_get_contents_curl failed to download http://www.prestashop.com/ajax/controller.php?email=demo%40prestashop.com&method=addMemberToNewsletter&language=0&visitorType=1&source=installer : (error code 28) Operation timed out after 5766 milliseconds with 0 bytes received

Installed failed, displaying errors from logs: [...]
```

Example of failure: https://travis-ci.org/PrestaShop/PrestaShop/jobs/530152208#L632

**Additionnal information**
PrestaShop version: N/A, any branch on GitHub may be concerned
PHP version: N/A, any PHP version may be concerned

**Comment by matks** [comment]
I close as this issue has not been observed for a long time and Travis is not used anymore since 1.7.8.x
