### ISSUE TITLE
All native module are displayed in the "Other" category - Module Manager

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#13725]
Using the 1-click module, I am unable to complete installation of upgrade from 1.7.5.1 to 1.7.5.2. Files are copied and databases upgrade correctly. However, the upgrade stops when upgrading the addons modules. All non-native modules were previously disabled. 

The last line on the log states: "FrontController.php line 352 - Trying to get property of non-object".

Please see attached log file.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3161712/log.txt)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Thanks for your report.
>All non-native modules were previously disabled

Did you disabled those modules from the BO => Performance page 
![image](https://user-images.githubusercontent.com/16067358/57448844-4d395b00-7252-11e9-8540-45c85b383047.png)
If yes, this option doesn't work, here's a ticket: https://github.com/PrestaShop/PrestaShop/issues/9965
The upgrade of your files & the database => OK.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Quetzacoalt91** [comment]
Hi there,

That's weird to see a FrontController to be called here. Anyway, note your shop has been updated and module upgrades can anyway been done in a second time via the Module Manager.

**Comment by nrcjea001** [comment]
@khouloudbelguith non-native modules were disabled in the 1-click upgrade as shown in image below:
![Untitled](https://user-images.githubusercontent.com/26452178/57449702-b24e7a00-726d-11e9-91c9-8bd67c280274.png)

@Quetzacoalt91 ok glad to know upgrade is ok

**Comment by khouloudbelguith** [comment]
@nrcjea001, your shop is OK after the upgrade?
Thanks!

**Comment by nrcjea001** [comment]
@khouloudbelguith, it appears so

**Comment by khouloudbelguith** [comment]
@nrcjea001, good!
Can I close the issue?
Thanks!

**Comment by nrcjea001** [comment]
@khouloudbelguith sure

**Comment by khouloudbelguith** [comment]
@nrcjea001, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by nrcjea001** [comment]
I've discovered that the website is not working as per normal after upgrade. Do I open a new issue can we reopen this one?

**Comment by nrcjea001** [comment]
After upgrade, I went to module manager and discovered all native modules were put in "Other" category. Also, as a test, I went to bank transfer module and clicked "check for updates" and BO has crashed

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

I just reopened the issue.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nrcjea001** [comment]
Hi @khouloudbelguith 

No issue in PHP error log. BO did not crash as I thought, "check updates" load was just hanging for a long time. "Check updates" button redirects me to module manage page

--> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
This page explains how to enable debug mode, but not how to produce a report. How to send this to you?

To summarize steps, 
1. Upgrade 1.7.5.1 to 1.7.5.2, 
2. Go to module manager and discover all native modules are in "Other" category. 

All permissions are 755 for directories and 644 for files
Upgraded PHP to 7.2 and no change

**Comment by khouloudbelguith** [comment]
@nrcjea001, thanks a lot for these clarifications.
I manage to reproduce the issue with PS1.7.5.2 (fresh installation & after upgrade from PS1.7.5.1)
All native modules are displayed in the "Other" category.
PS1.7.5.1 => OK
https://drive.google.com/file/d/1EBufi6je1APUeXJJldM9WMiSqHwjgkrf/view
PS1.7.5.2 => NOK / PS1.7.6.beta1
https://drive.google.com/file/d/11B7WD_-3p8SrDjQxD7ewib35sgDGiufG/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by colinegin** [comment]
@PierreRambaud what do you think of this issue ? I thought it had been solved ?

**Comment by marionf** [comment]
Addons API push has been updated, it's now fixed for 1.7.5.2
And it's too early to update it for 1.7.6.0, it will be done for the final release
