### ISSUE TITLE
An exception is displayed when we try to upload in the logo section with an image which has a not recognized format

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13729]
**Describe the bug**
An exception is displayed when we try to upload in the logo section with an image which has a not recognized format

**To Reproduce**
1. Go to BO => Design => Theme & Logo
2. Upload in the logo section with a not recognized format ( for example a zip file)
3. Click save

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/57453878-6a285b00-725f-11e9-87ee-b8e724d5dcb3.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13774
