### ISSUE TITLE
Solved - big problem about the canonical url in the category pages when there is pagination and multi languages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#13737]
### Describe the bug
It is strange that on 1.7.5.2 there are bugs like this:

1. try to use a shop with multi languages and go to the category pages with paginations, so you can see that the second page has a different canonical url of the first page because there is `?page=2`
2. another problem is that you use the `context->language->id` and not the default language, so the italian pages have a different canonical url of english pages, and it is wrong

### Expected behavior
This code will solve this bug: 
in FrontController.php, function `getTemplateVarPage`
```
$id_category = (int) Tools::getValue('id_category');

        $page = array(
            'title' => '',
            'canonical' => isset($id_category) && $id_category ? $this->context->link->getCategoryLink($id_category, null, (int) Configuration::get('PS_LANG_DEFAULT')) : $this->getCanonicalURL(),
            'meta' => array(
                'title' => $meta_tags['meta_title'],
                'description' => $meta_tags['meta_description'],
                'keywords' => $meta_tags['meta_keywords'],
                'robots' => 'index',
            ),
            'page_name' => $page_name,
            'body_classes' => $body_classes,
            'admin_notifications' => array(),
        );
```
### Steps to reproduce

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/57467595-1891c780-7283-11e9-9926-69b110b947e3.png)
![2](https://user-images.githubusercontent.com/653230/57467597-192a5e00-7283-11e9-8800-6b469a7a4ea5.png)
![3](https://user-images.githubusercontent.com/653230/57467598-192a5e00-7283-11e9-91a0-685b1d944673.png)

**Additionnal information**
PrestaShop version: 1.7.7.4
PHP version: 7.2

**Comment by matks** [comment]
@maofree Wouldn't this code be better put in CategoryController::getCanonicalURL() ?
https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/listing/CategoryController.php#L53

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
About the first issue: 
>the second page has a different canonical

It the same behavior with PS1.7.5.1 & PS1.7.5.2.
I think different page => different content
About the second issue, as you can see in this comment https://github.com/PrestaShop/PrestaShop/issues/9500#issuecomment-415453287
It is logical to have different canonical when the language is changed
Different language = different content
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
About the first issue: 
>the second page has a different canonical

It the same behavior with PS1.7.5.1 & PS1.7.5.2.
I think different page => different content => so we don't have duplicated content
ping @matks @jolelievre what do you think?
About the second issue, as you can see in this comment https://github.com/PrestaShop/PrestaShop/issues/9500#issuecomment-415453287
It is logical to have different canonical when the language is changed
Different language = different content
Thanks to check & feedback.

**Comment by Maofree** [comment]
Hi
the problem is that google signals these paginations as errors because it sees the same texts for all paginations.
so probably it is true that for different languages there are different canonical url because the content is different

for getCanonicalURL yes you can fix the problem here removing all code except
$canonicalUrl = $this->context->link->getCategoryLink($this->category);

the problem is that all these pages have the same meta title and meta description

**Comment by Maofree** [comment]
another problem is that the canonical url is missing in many pages like for manufacturers, index, contact, discount page ....

**Comment by khouloudbelguith** [comment]
@maofree,

>another problem is that the canonical URL is missing in many pages like for manufacturers, index, contact, discount page

here is an issue previously reported #9503

**Comment by khouloudbelguith** [comment]
@maofree, 

>the problem is that all these pages have the same meta title and meta description

for example, you can add different `Meta title`, `Meta description` for different languages
I attached a video record
https://drive.google.com/file/d/1fIEMIuDC86t1Ei5QIKVl3OKvJ42FZoaa/view
Thanks to check & feedback.

**Comment by Maofree** [comment]
it was created in 22 august
I think these types of issues should have a higher priority

**Comment by khouloudbelguith** [comment]
@maofree, 

>the problem is that all these pages have the same meta title and meta description

for example, you can add different `Meta title`, `Meta description` for different languages
I attached a video record
https://drive.google.com/file/d/1fIEMIuDC86t1Ei5QIKVl3OKvJ42FZoaa/view
For the page n°2, the title of the page is changed also
https://drive.google.com/file/d/17cP3B7VMPI0cf6vpsJ2suKwO5EVLS7rk/view
Thanks to check & feedback.

**Comment by Maofree** [comment]
yes I know this so I think it is right to use different canonical url on each language
for example, you can add different Meta title, Meta description for different languages

**Comment by khouloudbelguith** [comment]
@maofree, thanks for your feedback.
About the pagination, 
>the second page has a different canonical

the second page has a different meta title than the first page & different content => so we have different canonical, is it right?
Thanks!

**Comment by Maofree** [comment]
no
the second page has the same meta title and meta description of the first page and the third page ...

the problem is present for all page with paginations

the multi language is another thing

**Comment by khouloudbelguith** [comment]
@maofree, 
Yes, the meta description is the same for different page.
But the title is different, as you can see in my screen-record
https://drive.google.com/file/d/17cP3B7VMPI0cf6vpsJ2suKwO5EVLS7rk/view
PS: For each paginated page, we have the rel next/prev.
Thanks!

**Comment by jolelievre** [comment]
Hello @maofree 

I know it is complicated to have a unique/general point of view about SEO, so I'm aware what I'm saying may not be correct for every use cases. But in several best practices about managing pagination for SEO you can find that each page needs to be self canonical, which makes sense because the content is different (not the same products).

You can also have the same title and meta it will not be considered as duplicate content, however it is recommended to have more content in the first page in order to "highlight" it, that's why from 175 the category description is only displayed in the first page.

About language it is also advised to use the `alternate` rel link, each page can have its own canonical (different language => different content => different page), but the alternate link (with `hreflang` attribute) helps SEO engine to relate pages between each other.

However one thing we are indeed missing is the rel next/prev between each pages.. or at least in the header ^^ The rel links are indeed present in the pagination block, but we probably should emphasize this by adding them in the header as well.

This could be added in the 177 version, @colinegin wdyt?

**Comment by Maofree** [comment]
hi @jolelievre 
the problem is that Google alert everyone with its notifications that there are duplications on meta titles and meta descriptions.
for the description only in the first page I think it not solve the problem, normally it is enought the first page because it has all content to index on some keywords, the rest of paginations are necessary?

another problem that Google alert everyone is the missing tag for the microdata of the blocks present in the category pages, now request more data to be set

I think if these alert will be removed everybody will be happy, and it should be a plus point for Prestashop.

bye

**Comment by jolelievre** [comment]
Hi @maofree 
we plan to discuss this topic to think about how it could be improved in 177 version
Do you have any suggestion on how/what we could do by any chance?

**Comment by Maofree** [comment]
hi
I summarize the 4 points that I believe are a problem. At this moment Google reports errors with the current solutions used in prestashop 1.7.5.x

1)
Google alerts shopkeepers, because some microdata are missing in the product pages and in the pages with products lists like category pages, try to have a look with the google's tool
https://search.google.com/structured-data/testing-tool

2)
the pages with paginations give problems because Google alerts shopkeepers that there are duplications on meta title and meta descriptions. I think it is enought to use the first page to index the category page and use the url canonical to avoid duplications on meta data. Normally it is the first page that index those pages.

3)
only the category pages have url canonical the other paginations are without it, like for manufacturer page.
the url canonical can be useful also for the homepage or contact pages to protect them

4)
the other problem is that now each combination has own page, so if the site use comparators like google shopping visitors come on product page and it is necessary to give to them all informations without move it on many pages, all data should be present in the product pages to reduce the bounce frequency

bye

**Comment by colinegin** [comment]
Hello @maofree ,

sorry for only writing back now and thanks for all your feedbacks. About your comment :
- 1st issue is fixed in 1.7.7 see PR https://github.com/PrestaShop/PrestaShop/pull/14558
- 2nd issue : there's a few issues listed here https://github.com/PrestaShop/PrestaShop/issues/18402 about pagination, is it one of them ? 
- 3rd issue is listed here : #9503
- 4th issue : i'm not sure I understand it clearly, what kind of informations are you talking about ?

**Comment by Maofree** [comment]
hi
1st issue  #14558 uses the ItemList but it is a wrong solution, because it is not possible to have more than one ItemList in a page

4th issue in the 1.7 a product with combinations has a number of urls how many are its combinations. Normally each url show the images of the current combination, so if I'm a visitor I need to scroll each combination to see its images, I think it is better to can see all infos, data, images at the start

**Comment by hibatallahAouadni** [comment]
Ping @marionf any news about this issue :pray:

**Comment by Hlavtox** [comment]
Each category page should have it's own canoncial. No problem in that.

Canoncial being in wrong language is a huge bug of course.

**Comment by Prestafan1234** [comment]
@hibatallahAouadni I cannot see that the pagination problem is solved in any threads where they are marked as duplicate or in this one. The problem persists in PrestaShop 1.7.8.3

**Comment by HanaRebaiQA** [comment]
Hello, 

Any news about this issue?

Thanks!

**Comment by Hlavtox** [comment]
@HanaRebaiQA I will check the current behaviour tommorow.

**Comment by Hlavtox** [comment]
Just checked it and it works correctly.
✅ All pages have correct canoncial for each page.
✅ All languages have correct canoncial for each language.

![3](https://user-images.githubusercontent.com/6097524/208979713-d6a4cc0c-b4a8-4884-91fa-561dd8e76854.jpg)
![4](https://user-images.githubusercontent.com/6097524/208979715-3d875351-911c-4aa1-9d88-3658e88bc0ea.jpg)
![1](https://user-images.githubusercontent.com/6097524/208979717-e37fdfc0-0944-4ade-bf43-75361684fff7.jpg)
![2](https://user-images.githubusercontent.com/6097524/208979718-3051d727-f4b2-443b-9946-13b6535871da.jpg)

**Comment by HanaRebaiQA** [comment]
Thanks @Hlavtox !

**Comment by web-burn** [comment]
@Hlavtox, hello
In the PrestaShop 8.2 on Classic theme i see wrong urls in hreflang in category pagination: doesn't appear parametr ?page=2 like on your screenshots:

![Image](https://github.com/user-attachments/assets/b1d4578b-7c0f-4f28-b73e-7926d8c76d85) 

I can get the same result like on your screenshot if i changed in the code <link rel="alternate" href="{$pageUrl}" hreflang="{$code}> in the file "themes/classic/templates/_partials/head.tpl" to 

![Image](https://github.com/user-attachments/assets/3f6ce862-be39-4365-977e-8efd3f4df7df)
