### ISSUE TITLE
New tax incl column shouldn't take into account specific price

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13731]
**Describe the bug**
Tax excl column in catalog page doesn't take into account specific prices while new tax incl column take it

**To Reproduce**
1. Go to Catalog > products and create a product with a specific price
2. Go back to the product list
3. Price tax incl column take into account the specific price but tax excl column doesn't

In 1.7.5.0 there wasn't tax incl column so it wasn't a problem.
We should remove specific price to tax incl column

**Screenshots**
![capture d'écran_1507](https://user-images.githubusercontent.com/13449658/57460278-17599e00-7275-11e9-8ab1-92cb1be9ffe5.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment]
See #14091

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14091
