### ISSUE TITLE
errors in invoices page of admin side

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#13740]
Hi
I've upgrade many site to 1.7.5.2 and some of them have the same error on the invoices page of admin side

Expected argument of type "object, array or empty", "string" given

I pass you the access to one of them

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/57519295-3579d980-731b-11e9-93cf-620046218183.png)
![2](https://user-images.githubusercontent.com/653230/57519296-36127000-731b-11e9-85b2-23b58a2dd2cb.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

bye

**Comment by Maofree** [comment]
![1](https://user-images.githubusercontent.com/653230/57519644-1465b880-731c-11e9-87d4-bb9e026b5bb1.png)

**Comment by khouloudbelguith** [comment]
Hi @maofree,

This issue is fixed in the PS1.7.6.0.
Your ticket is a duplicate of #12962
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #12962

**Comment by Maofree** [comment]
is it possible to fix it on the 1.7.5.2 ?
in that page I cannot see the pages to edit to fix it

**Comment by khouloudbelguith** [comment]
@maofree, you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12314#issuecomment-462410864 to fix your issue.
Thanks!
