### ISSUE TITLE
Amount of promotion is wrong while discount line is ok

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13748]
![image](https://user-images.githubusercontent.com/15104724/57457606-212cd280-7270-11e9-82e2-51723a0dede5.png)

![image](https://user-images.githubusercontent.com/15104724/57457627-2c7ffe00-7270-11e9-9aea-eb62b933d0b7.png)

![image](https://user-images.githubusercontent.com/15104724/57457655-373a9300-7270-11e9-8de9-171f540c0723.png)

The problem is in function `getTemplateVarVouchers` from `CartPresenter`:

```
// Voucher reduction depending of the cart tax rule
// if $cartHasTax & voucher is tax excluded, set amount voucher to tax included
if ($cartHasTax && $cartVoucher['reduction_tax'] == '0') {
    $cartVoucher['reduction_amount'] = $cartVoucher['reduction_amount'] * (1 + $cartHasTax / 100);
}
```
This `if` is evaluated as false, but `$cartVoucher['reduction_amount']` is 1€ (in my example). Taxes should be removed.

_Originally posted by @idnovate in https://github.com/PrestaShop/PrestaShop/pull/13684#issuecomment-490908622_

**Comment by marionf** [comment]
And also this one:

![image](https://user-images.githubusercontent.com/15104724/57519309-3ca0e780-731b-11e9-888a-393f58d431e0.png)

![image](https://user-images.githubusercontent.com/15104724/57519329-46c2e600-731b-11e9-9f85-179a92ecb32e.png)

![image](https://user-images.githubusercontent.com/15104724/57519342-50e4e480-731b-11e9-93b5-7d9c6c90daee.png)

_Originally posted by @idnovate in https://github.com/PrestaShop/PrestaShop/pull/13684#issuecomment-491234173_

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13780
