### ISSUE TITLE
Product with combinations page Ajax refresh when multi languages and url rewriting are enabled

### ISSUE THREAD

**Issue by webperfect-lhd** [PrestaShop/PrestaShop#13750]
**Describe the bug**
When two or more languages are enabled, combined with URL rewriting enabled, the product page ajax refresh process doesn't work when you change an attribute. The url of the Ajax become /{iso_code}/index.php instead of /index.php.

**To Reproduce**
1. Enable two languages in International / Localization / Languages
2. Enable URL rewriting in Shop Parameters / Traffic & SEO
3. Go to a product with combinations page (frontend)
4. Click on a color or change an attribute
5. An error is showing up
6. In Chrome Console, you could see a 404 error.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/39125207/57530397-6c5de880-7337-11e9-897f-7972229c222a.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @webperfect-lhd,

Did you use an `nginx` configuration?
Thanks!

**Comment by webperfect-lhd** [comment]
> Hi @webperfect-lhd,
> 
> Did you use an `nginx` configuration?
> Thanks!

Hi @khouloudbelguith,
No, I use Apache 2.4.
Thank's

**Comment by khouloudbelguith** [comment]
@webperfect-lhd, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1vUcrLmtAyr_GIfknpgLN5Vf5x_3MlHOB/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source), fresh installation or an upgrade from an old version?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by webperfect-lhd** [comment]
@khouloudbelguith,
Thank you for your help !

It's on my desktop, an iMac with Mac OS X High Sierra 10.13.6.

Ok ! After seeing your video, I understood that I certainly have a misconfiguration problem if you did not reproduce the problem. I noticed on your video you don't have the specific phrase I had in URL rewriting admin part.
![image](https://user-images.githubusercontent.com/39125207/57536477-8c47d900-7344-11e9-9c2f-be1194a655d1.png)
So, I tried to modify my Apache virtual host configuration to see if something goes wrong. I am using PHP-FPM with different PHP versions since a few days. And when I change my vhost configuration without using PHP-FPM, the problem disappear !

Here is my vhost configuration which let me have the problem
```
<VirtualHost *:80>
	ServerName prestashop.1.7.5.2.local
    ServerAdmin xxx@xxx.fr
    DocumentRoot "/Users/xxx/Documents/Sites/prestashop_1.7.5.2"
	ProxyPassMatch "^/(.*\.php(/.*)?)$" "fcgi://127.0.0.1:9070/Users/xxx/Documents/Sites/prestashop_1.7.5.2/$1"
	<Directory "/Users/xxx/Documents/Sites/prestashop_1.7.5.2">
		<FilesMatch \.php$>
			SetHandler "proxy:fcgi://127.0.0.1:9070"
		</FilesMatch>
	    Options Indexes FollowSymLinks
	    AllowOverride All
	    Require all granted
	</Directory>
    ErrorLog "/Users/xxx/Documents/Sites/prestashop_1.7.5.2/apache.error.log"
    CustomLog "/Users/xxx/Documents/Sites/prestashop_1.7.5.2/apache.access.log" common
	RewriteEngine On
</VirtualHost>
```

And here a vhost configuration without php-fpm which fix the problem !

```
<VirtualHost *:80>
	ServerName prestashop.1.7.5.2.local
    ServerAdmin xxx@xxx.fr
    DocumentRoot "/Users/xxx/Documents/Sites/prestashop_1.7.5.2"
	<Directory "/Users/xxx/Documents/Sites/prestashop_1.7.5.2">
	    Options Indexes FollowSymLinks
	    AllowOverride All
	    Require all granted
	</Directory>
    ErrorLog "/Users/xxx/Documents/Sites/prestashop_1.7.5.2/apache.error.log"
    CustomLog "/Users/xxx/Documents/Sites/prestashop_1.7.5.2/apache.access.log" common
	RewriteEngine On
</VirtualHost>
```

So, I certainly have an Apache / Php-fpm misconfiguration issue, I will look for a better solution, which let me continue to use php-fpm. If I found something about that, I will post it here, perhap's it could help someone ;-)

Thanks !

**Comment by webperfect-lhd** [comment]
@khouloudbelguith,

OK, I found the problem.
It seems I don't need to use the config line ProxyPassMatch "^/(.*\.php(/.*)?)$" "fcgi://127.0.0.1:9070/Users/xxx/Documents/Sites/prestashop_1.7.5.2/$1"
If I remove it, all is ok and I could continue to use php-fpm for my vhost.

Sorry for the time spent on a problem that wasn’t there. Thank's for your quick help !
Best regards.

**Comment by khouloudbelguith** [comment]
Hi @webperfect-lhd,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
