### ISSUE TITLE
Search cron not working with multistore.

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#13759]
I tried to setup a cron task to rebuild the search index in back office. 
Cron task is excecute on the server, but the rebuild does not start

When I click on the link in backoffice, the search index does start

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1
Multistore activate

Solved:

Issue had nothing to do with prestashop, but the cron task I set up

**Comment by khouloudbelguith** [comment]
Hi @01park,

Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!
