### ISSUE TITLE
Nom de domaine prestashop

### ISSUE THREAD

**Issue by union-des-vignerons** [PrestaShop/PrestaShop#13753]
Je n'arrive pas à inscrire mon nom de domaine dans Prestashop.
Nous avons acheté un nom de domaine sur OVH et nous souhaitons l'implémenter sur notre site.
Après avoir taper notre nom de domaine et cliquer sur ajouter, nous recevons ces deux messages d'erreur :
- L'entrée "A" ne contient pas la bonne adresse IP. Veuillez le changer ou ajouter un enregistrement "A".
- L'entrée "A" du sous-domaine "www" ne contient pas la bonne IP. Veuillez la modifier ou ajouter l'entrée "A" pour ce sous-domaine. Si vous ne souhaitez pas ajouter automatiquement le sous-domaine "www", vous pouvez modifier ce paramètre dans les "Paramètres avancés".

**Comment by khouloudbelguith** [comment]
Hi @union-des-vignerons,

Have you tried to contact your host about this issue?
Thanks to check with him & feedback.

**Comment by khouloudbelguith** [comment]
Hi @union-des-vignerons,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
