### ISSUE TITLE
After the upgrade from 1.6.x to 1.7.x some parts of the back-office have texts in english

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#13781]
hi
I've upgraded some sites to 1.7.5.x and many of them had the same problem after the upgrading, the vertical menu and the title of the pages became in english.
in parameters.php I saw that there was
'locale' => 'en-US',
instead the default language was the italian.
even changing to it-IT and clearing the cache the texts remain in English. I have talked to others and several have had the same problem

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/57690482-05e00f80-7642-11e9-9841-3fec159798eb.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

What is the exact version you started from?
What is the exact version of the 1-click upgrade did you use?
Could you please, navigate to your BO => International => Translations => " Add / Update a language" section, choose the Italian language & click on the "Add or update a language" button.
Thanks to check & feedback

**Comment by Maofree** [comment]
hi
1-click upgrade version was 4.6.0 or 4.7.0
the start version was 1.6.1.21 or 1.6.1.23

yes updating the Italian language the problem is solved

**Comment by khouloudbelguith** [comment]
@maofree, thanks!
Since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!
