### ISSUE TITLE
New customer profile field: This user has suspicious activities

### ISSUE THREAD

**Issue by miha1** [PrestaShop/PrestaShop#13786]
As part of the new [3-D Secure](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) standard that is coming into force in Europe, there are a number of new parameters that must be sent to credit card acquirers.

One of these parameters is a new field for tracking suspicious activity with users. To ensure full compliance this field should be added to the customer profile fields in Prestashop

**Describe the solution you'd like**

On the admin customer page (in AdminCustomers controler) there should be a new field (perhaps a checkbox?) stating "This user has suspicious activities" that can be set manually by the merchant as they see fit.

**Comment by khouloudbelguith** [comment]
Hi @miha1,

You can use the additionalCustomerFormFields hook, you can add a new field to customer registration form from the Front office.
For the BO, you can use displayAdminCustomers, it display new elements in the Back Office, tab AdminCustomer
Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
@miha1, can I close the issue?
Thanks!

**Comment by miha1** [comment]
Yes, tnx for support

**Comment by khouloudbelguith** [comment]
@miha1, thanks!
Feel free to open a new one when needed.
