### ISSUE TITLE
Split prestashop into components and distributions

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13785]
Following Symfony example, I think it would be nice for next major version of PrestaShop to be available through Composer package manager as a set of components or a distribution.

## Ideal usecase

Create components:
- `prestashop/prestashop-core` that contains all the Core classes
- `prestashop/prestashop-frontoffice` that contains the FO classes
- `prestashop/prestashop-backoffice` that contains the BO classes and theme
- `prestashop/classic-theme` that contains the Classic Theme for FO
- `prestashop/prestashop-api` that contains the API classes

And provide also the following packages:
- `prestashop/prestashop-app-light` that contains a light prestashop distribution, ready to use
- `prestashop/prestashop-app-full` that contains a full prestashop distribution, ready to use

## Easier usecase

As the split might be very heavy to do, maybe we can first start by providing `prestashop/prestashop-core` and `prestashop/prestashop-app-full`.

`prestashop/prestashop-core` would be useful for modules that would require it. This would allow for example full test integration possible with CI

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment]
Could be cool to remove the unneeded prefix `prestashop-` which is already in `prestashop/` :)

**Comment by matks** [comment]
Additionnal usage: being able to use [composer create-project](https://getcomposer.org/doc/03-cli.md#create-project) command to create a new PS project:
```
php composer.phar create-project prestashop/prestashop 8.0.*
```
or even provide a PrestaShop installer CLI (like Symfony does) to be able to do
```
prestashop-cli new my_project_name
```

ping @MDWeb-Lille this one we discussed it yesterday 😉

**Comment by matks** [comment]
Well I close this issue because I think we will not be able to do it soon
