### ISSUE TITLE
The number of items per page will be reset when clicking on the "Reset" button

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13799]
**Describe the bug**
In the BO => International => Taxes page, the number of items per page will be reset when clicking on the "Reset" button to reset a filter

**To Reproduce**
1. Go to BO => International => Taxes page
2. Modify to number of items per page (for example 20 ) => OK
3. Filter by any field ( for example by Id)
4. Click on the "Reset" button
5. The number of items per page is returned to the default one => it shouldn't (PS1.7.5.2 => OK)

**Screenshots**
https://drive.google.com/file/d/1xBhEm1lwcFK-wMxG-1KFOQPZdjyISglV/view

**Additionnal information**
PrestaShop version: 1.7.6.0beta1
PHP version: 7.1

**Comment by zuk3975** [comment]
@khouloudbelguith it might be the pagination/filtering behavior, not the tax list itself. I have checked currency list for example, and it behaves the same way.

**Comment by khouloudbelguith** [comment]
@zuk3975, thanks for your feedback.
In the product page, it is not the same behavior.

**Comment by zuk3975** [comment]
> @zuk3975, thanks for your feedback.
> In the product page, it is not the same behavior.

It should all be the same in new migrated pages. (Product page is kinda exception, because its not using the same grid system)

**Comment by PierreRambaud** [comment]
In not in favor to make this change.
If you're on a grid page, want to find an element with filters and navigate to the wanted result. For example going to page 3. 
If the reset button is clicked, you want to reset each action on this grid, pagination included, not staying on the same page :thinking:

**Comment by zuk3975** [comment]
> In not in favor to make this change.
> If you're on a grid page, want to find an element with filters and navigate to the wanted result. For example going to page 3.
> If the reset button is clicked, you want to reset each action on this grid, pagination included, not staying on the same page

@PierreRambaud https://github.com/PrestaShop/PrestaShop/pull/13840/files#diff-8b03d6d67a334ff0b304181a10b14e5aR110 it resets the offset, so the pagination is resetted.

**Comment by PierreRambaud** [comment]
@zuk3975 Thanks :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13840
