### ISSUE TITLE
New theme & logo page - Design fixes part 2

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13793]
When uploading a PrestaShop theme that contains the theme configurator module, the bloc that links to the module doesn't display correctly :
![56347641-031a0800-61c5-11e9-92f3-28eb7fd53f98](https://user-images.githubusercontent.com/3034677/57764484-dbef2180-7703-11e9-947a-9a2731dfc772.png)

It looked like this in legacy :
![56348350-8720bf80-61c6-11e9-816d-ebd5f4646dac](https://user-images.githubusercontent.com/3034677/57764496-e01b3f00-7703-11e9-8061-00f253c2a9eb.png)

related to the issue : #13690

**Comment by matks** [comment]
Can you tell us where is hosted the Theme Configurator, as the bug seems to require a fix in the module ?

**Comment by eternoendless** [comment]
@matks https://github.com/PrestaShop/themeconfigurator ?

**Comment by eternoendless** [comment]
Disregard my last comment, that module is not on GitHub.

**Comment by colinegin** [comment]
@sarahdib @marionf you can test it with the 2.0.2 version of the module ! (see with Alexandre or Adrien)

**Comment by marionf** [comment]
@YeLnatSs 

I tested with themeconfigurator v2.0.2 and display is not ok

![capture d'écran_1611](https://user-images.githubusercontent.com/13449658/58480462-b0842200-815a-11e9-92de-9f96804f2b59.png)

**Comment by YeLnatSs** [comment]
@marionf 
Module CSS ('back.css') is not call yet in Html page. I already saw that point with @matks, he'll do it

**Comment by marionf** [comment]
It's all good with themeconfigurator version 2.0.3 in 1.7.6 and 1.7.5

![capture d'écran_1688](https://user-images.githubusercontent.com/13449658/59590661-dd3db080-90ec-11e9-9432-cf7cd0b20e75.png)

![capture d'écran_1687](https://user-images.githubusercontent.com/13449658/59590669-e038a100-90ec-11e9-9fd4-2aa4944d7eb4.png)
