### ISSUE TITLE
Small issues during the checkout process

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#13796]
There is minor issue left after development on the checkout steps : when I start the purchase process, it is not possible to click on step 2 / 3 / 4 but the mouse changes into a pointer which can create confusion.

**Comment by colinegin** [comment]
Be careful with retrocompatibility, the fix must work both in 1.7.6 and 1.7.5

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13905
