### ISSUE TITLE
Percentage discounts ignores tax

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#13791]
**Describe the bug**
When reduction type of 'percentage' is selected while creating discount, product price calculation ignores taxes.

**To Reproduce**
1. Go to Sell > Catalog > Catalog Price Rule > Add new Catalog Price Rule
2. When creating price rule fill any data (:warning:  important to select `Reduction type - Percentage`). And Save.
3. Go to Front Office, see the discounts.
4. Go back to Catalog Price Rule > Edit previously created rule - change `Reduction with or without taxes` option.
5. Go to Front Office again - there is no difference, the tax was not considered when calculating product price.
(:warning: make sure to select same shop and currency in form as you check in Front Office)

**Screenshots**
classes/Product.php
![Screenshot from 2019-05-15 10-02-25](https://user-images.githubusercontent.com/31609858/57757089-59fbfa00-76fd-11e9-86bb-853e91382fc3.png)

**Additionnal information**
PrestaShop version: 1.7.6.x (and possibly all previous versions)
PHP version: N/A
In classes/Product.php code line 3459  `if` statement checks for `reduction_type 'amount'` and handles taxes only inside it.

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1
In the FO, the discount is always applied to the price tax included.
The field "Reduction with or without taxes" has no effects.
I’ll add this to the debug roadmap so that it’s fixed.

Thanks!

**Comment by colinegin** [comment]
@sarahdib i don't reproduce this issue with the migrated page, can you confirm ?

**Comment by sarahdib** [comment]
@colinegin In the migrated page the field HT / TTC is not displayed for percentage discount.

**Comment by colinegin** [comment]
Ok sorry I misunderstood the issue. Now I remember : we decided to remove it just like on Cart rules, as this does not make any sense. You do not decide to do 20% reduction with taxes included, you just do 20% reduction on the product price (which is available in ht or ttc according to the store configuration).

**Comment by colinegin** [comment]
ping @SD1982, do you confirm it is removed like on cart rule page ?

**Comment by SD1982** [comment]
Hi @colinegin Yes I confirm that it's removed on the migrated page ( tested on 1.7.7.x & develop branch )
https://drive.google.com/file/d/1HPOqt8NBYFP8pssJLE31O8UjXWGVKvzd/view?usp=sharing

**Comment by colinegin** [comment]
Alright then, we can close this issue ! :)

Thanks
