### ISSUE TITLE
Translations are not working anymore, max execution time set 60 sec

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13801]
**Describe the bug**
Translations are not working anymore

**To Reproduce**
1. Go to International > Translations
2. Select BO translations or any other choice
3. Click on the left to select something in the menu
4. See error in the console, max execution time of 60 sec exceeded
5. You can't translate anything

**Screenshots**
![capture d'écran_1542](https://user-images.githubusercontent.com/13449658/57782730-1e792400-772d-11e9-98d0-b21bb0650397.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by marionf** [comment]
![capture d'écran_1544](https://user-images.githubusercontent.com/13449658/57784106-a2341000-772f-11e9-9204-430ee192f055.png)

![capture d'écran_1543](https://user-images.githubusercontent.com/13449658/57784113-a5c79700-772f-11e9-8ff5-84c38247d8f9.png)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

In my case, it is OK with PS1.7.6.0beta1
https://drive.google.com/file/d/1M8vWFOcrYpaFK2WBDo9_TlE2vk9yZ3Br/view
In my php info file 
`max_execution_time = 30`
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith @marionf 

It doesn't work. It loads for a minute, then it shows the domains on the left, but you cannot click on anything. Right side is empty - no translations.

You can't translate anything.
