### ISSUE TITLE
Can't add a promo in order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13809]
_Originally posted by @Hlavtox in https://github.com/PrestaShop/PrestaShop/issues/11059#issuecomment-492771674_

I don't know if somebody is trying to make jokes of people or WTF is happening here. I am opening this issue for second time and always somebody quiets it down or says it's fixed when it's not. 

Now there is another issue and it throws 500 even when creating the voucher.
https://youtu.be/MHbHYnx5UAo

**Comment by marionf** [comment]
Hi @Hlavtox

I tried to reproduce your issue with PrestaShop 1.7.6.0 beta 1 but without success as you can see in the screenrecord below:
https://drive.google.com/file/d/18ULX7quWqYTdCgwRNUSn-oUaQ99E4axy/view?usp=sharing

You will need more infos about your issue:
- What is the status of your order ?
- What is your currency ?
- What is your language ?

Could you try to enable debug mode in Advanced parameters > Performance, maybe it could allow to have more details than 500 error :)

Thank you

**Comment by khouloudbelguith** [comment]
Hi @marionf, @Hlavtox,

I manage to reproduce the issue with PS1.7.6.0beta1.
But this error is different from this ticket: #11059
I attached a video record
https://drive.google.com/file/d/1wTi2LmBmB6eOWcwzCi1txM1GnoxZxCJo/view
![image](https://user-images.githubusercontent.com/16067358/57836894-955bfe80-77b9-11e9-9ae5-46d57c828fa7.png)
Steps to reproduce the issue:

1- Create a product
1.1 Price (tax incl.) = 435.95 €
1.2 Tax rule = 50% => Price (tax excl.) = 290.633333 €
2. Create a cart rule 5%
3. Add the last product to the cart => process checkout
4. Edit the order created
5. Delete the discount => OK
6. Add a new discount "Amount" = 435
7. See error

Thanks!

**Comment by marionf** [comment]
I can reproduce it also with 1.7.5.1

**Comment by marionf** [comment]
I can repoduce it more simply: 

1- Create a product
1. Price (tax incl.) = 435.95 €
2. Tax rule = 20% 
3. Add the last prduct to the cart => process checkout
4. Edit the order created
5. Add a new discount "Amount" = 435
6. See error

![capture d'écran_1546](https://user-images.githubusercontent.com/13449658/57838533-2be1ed00-77c5-11e9-9de8-058d11cf756d.png)

**Comment by colinegin** [comment]
Hello @khouloudbelguith (sorry for the intense spamming ;) ), do you reproduce this issue on 177x branch ? Thanks !

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Not fixed.
Same issue with 177x branch
![image](https://user-images.githubusercontent.com/16067358/74856422-670be080-5342-11ea-8748-f646b5a64d42.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #17877
