### ISSUE TITLE
Improve UX on SEO card in Categories

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#13806]
In product page, there is an explanation of what SEO card is, see:

![prod_seo](https://user-images.githubusercontent.com/15143151/57831278-6182d800-77bd-11e9-919d-e088c61d59f9.png)

However, in Categories page SEO card is placed in the middle of form without any explanation of what it is, see:

![cat_seo](https://user-images.githubusercontent.com/15143151/57831329-7f503d00-77bd-11e9-8c7d-3c78a813be6f.png)

I think that Categories SEO preview should have similar explanation to improve UX. It could be something like this:

![cat_seo_card](https://user-images.githubusercontent.com/15143151/57831459-dbb35c80-77bd-11e9-80aa-c8308d716979.png)

**Comment by khouloudbelguith** [comment]
Ping @colinegin @marionf what do you think?
Thanks!

**Comment by colinegin** [comment]
Thanks @sarjon , I completely agree !
I'll check with the rest of the team if we can fix it in 1.7.6.
What do you think @marionf ?

**Comment by marionf** [comment]
I agree and it's also the same on CMS page

![capture d'écran_1550](https://user-images.githubusercontent.com/13449658/57840972-f4297400-77c9-11e9-9ffc-3f928ede71a2.png)

**Comment by colinegin** [comment]
Related to #13848
