### ISSUE TITLE
Is there a version of PSWebServiceLibrary.php compatible with Prestashop 1.7.5.1?

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#13817]
Hello everybody,

I have an issue with a module that uses PSWebserviceLibrary.php

The previous Webmaster developed under Prestashop 1.6.1.5, various home-made modules including 2 that use PSWebServiceLibrary.php.
One of its modules queries, via the webservice, a remote site in order to retrieve the list of the commands passed on the 2 sites (those of the current site where one executes the module + those of the distant site) and to generate a file csv.
As we want to migrate our sites in Prestashop 1.7.5.1, I installed the 2 sites on a VPS server.
Then I installed the Orderlist module on both sites. I activated the webservice on site B. I also generated a key for the Webservice of this site.
I postponed this key + the URL of site B, in the config of the module, on the site A. Like that, the site A knows what is the URL of the remote site B and which key webservice the site B uses .
Then, on the site A, I wanted to export / generate the list of the orders to have the list of the orders passed on the 2 sites.
First problem: error 500
Seeing no Apache error, I enabled the debug mode to display errors => "This library is not compatible with this version of PrestaShop." Please upgrade / downgrade this library "about PSWebServiceLibrary.php
So I modified the file PSWebServiceLibrary.php and replaced:
const psCompatibleVersionsMax = '1.6.99.99';
by
const psCompatibleVersionsMax = '1.7.99.99';
at line 49
(Always on site A) I redo an export to generate the list of orders placed on the 2 sites.
And here I have, the following error message:
Uncaught PHP Exception PrestaShopWebserviceException: "This call to PrestaShop Web Services failed and returned an HTTP status of 401. That means: Unauthorized." at PSWebServiceLibrary.php line 93

So, I wanted to know: is there a version of PSWebServiceLibrary.php compatible with Prestashop 1.7.5.1? If no, is there an alternative (to PSWebServiceLibrary.php)?

In advance thank you for your answers, even negative.
**Screenshots**
![erreur_401_orderlist_module](https://user-images.githubusercontent.com/48359467/57854608-ef27ed00-77e8-11e9-8131-598b662a4cef.png)
_No need to consider the first Info; it is a minor bug for the moment_

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.18-1

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Yes, the file PSWebServiceLibrary.php is compatible with the version PS1.7.5.2.

```
	const psCompatibleVersionsMin = '1.4.0.0';
	const psCompatibleVersionsMax = '1.7.99.99';
```

[PSWebServiceLibrary.php.zip](https://github.com/PrestaShop/PrestaShop/files/3187108/PSWebServiceLibrary.php.zip)
The error 401, it is a problem of authorization, you should check the Auth key (Get it in your Back Office)
Thanks!

**Comment by wikao2** [comment]
I found a solution. Indeed, I forgot to allow the GET function on Customers where the error.
Thank you for your reply.
Have a nice day ;)

**Comment by khouloudbelguith** [comment]
@wikao2, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
