### ISSUE TITLE
The Russian Ruble has an invalid symbol after importing Russia pack

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13814]
**Describe the bug**
The Russian Ruble has an invalid symbol after importing Russia pack

**To Reproduce**
Steps to reproduce the behavior: install shop with English language / France country
1. Go to BO => International => Localization 
2. Import the Russian pack => OK
3. Go to the Currencies page from the BO => The Russian Ruble has an invalid symbol
4. Go to the FO => change the currency to RUB => same issue

**Screenshots**
BO
![image](https://user-images.githubusercontent.com/16067358/57848728-7ec1a180-77d1-11e9-8bd8-3d94670ed95e.png)
FO

![image](https://user-images.githubusercontent.com/16067358/57848777-97ca5280-77d1-11e9-94e4-c23afe062970.png)

**Additionnal information**
PrestaShop version: 1.7.6.0beta1
PHP version: 7.0

**Comment by marionf** [comment]
@khouloudbelguith 

I can't reproduce on 1.7.6.x branch with English language

![capture d'écran_1553](https://user-images.githubusercontent.com/13449658/57850807-2a252300-77df-11e9-9134-ac1fee288245.png)

![capture d'écran_1552](https://user-images.githubusercontent.com/13449658/57850808-2abdb980-77df-11e9-98ed-b593902703bf.png)

**Comment by marionf** [comment]
@tomlev or @Quetzacoalt91 Could you try to reproduce it ?
I can't reproduce it but I was asking if it's not related to CLDR ?

**Comment by tomlev** [comment]
Hi @khouloudbelguith @marionf 
this issue is related to the system. @marionf we did need to update your OS to fix it.
it is NOT related to prestashop

@PierreRambaud could you please provide more precision, I can't remember what you updated on @marionf OS

**Comment by PierreRambaud** [comment]
@tomlev Few months ago, but was maybe a intl update :thinking:
