### ISSUE TITLE
id_guest , id_customer & id_connections null on visitor

### ISSUE THREAD

**Issue by cr998** [PrestaShop/PrestaShop#13810]
**Describe the bug**
I can not differentiate the visiting sessions

**To Reproduce**
var_dump the $this->context->cookie->id_guest

**Screenshots**

**Additionnal information**
PrestaShop version: 1.6.1.18
PHP version: 5.6

**Comment by cr998** [comment]
id_guest is false allways

**Comment by khouloudbelguith** [comment]
Hi @cr998,

What is the exact file where did you added this line `var_dump the $this->context->cookie->id_guest`?
Thanks!

**Comment by cr998** [comment]
in the product page

**Comment by khouloudbelguith** [comment]
@cr998, I tried var_dump with this line https://github.com/PrestaShop/PrestaShop/blob/c44c307f1923ddf941247c8d0fe60089dc460234/classes/controller/FrontController.php#L413
and I have `/projet/prestashop/classes/controller/FrontController.php:414:string '1' (length=1)`
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @cr998,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
