### ISSUE TITLE
Taxes detail missing in order confirmation page

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#13819]
When the option "display taxes" is enabled, the taxes detail is available in every step of the checkout but not in the order confirmation. It should be available below Total (tax incl.)

**Comment by marionf** [comment]
Edit: It happens only if your cart contains products without tax (no tax selected in product page)

![capture d'écran_1560](https://user-images.githubusercontent.com/13449658/57930813-2f55a100-78b7-11e9-8fc1-8cd957971e51.png)

![capture d'écran_1561](https://user-images.githubusercontent.com/13449658/57930817-32e92800-78b7-11e9-9284-a340ff2ae4de.png)

**Comment by colinegin** [comment]
@marionf if I understand well, this happens in 2 different scenarios :
- product with taxes
- product with no taxes

Am I correct ?

**Comment by marionf** [comment]
It's ok with a product with taxes

![capture d'écran_1570](https://user-images.githubusercontent.com/13449658/58094265-88cc1180-7bd0-11e9-8732-21b15c33f5d0.png)
