### ISSUE TITLE
"The ISO Code field is not valid"

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#13837]
**Describe the bug**
Hi, I try to move Province (State) in a new Zone, but Prestashop does not allow moving and allert to me "The ISO Code field is not valid"

**To Reproduce**
1. Go to 'Location => Zone => create new one called "Italia island"'
2. Click on 'Province (Ex State) '
3. Scroll down to 'the name of the provincia, and try to modification => move to the new zone I create before'
4. Try to save but => "The ISO Code field is not valid"

HOW TO FIX IT
Delete the "**ISO code**" field and write it again, in this way the system accepts the change
Thanks a lot.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.6.1.23
![palermo1](https://user-images.githubusercontent.com/28685316/57927453-5d82b300-78ae-11e9-89e7-75dcf7a0bf41.png)
![palermo2](https://user-images.githubusercontent.com/28685316/57927454-5e1b4980-78ae-11e9-943b-7856617623ab.png)
![palermo3](https://user-images.githubusercontent.com/28685316/57927456-5e1b4980-78ae-11e9-8cda-1ba73cdc65ae.png)

PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

I did not manage to reproduce the issue with PS1.7.6.0beta1.
I attached a video record
https://drive.google.com/file/d/1c8uK20lnmeObrNEY2eaQ4XrxzEBhlPHA/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by ballashop** [comment]
Hi, thanks a lot, with PS1.7.6.0beta1 works but not really with 1.6.1.23,
I know of the suspension of support for the 1.6 :(, 
Unfortunately we cannot upgrade to 1.7 at the moment because the graphic theme does not support this version. 
But can we still use 1.6? Or not?
Thanks a lot for your support.

**Comment by khouloudbelguith** [comment]
@ballashop, yes you can still use PS1.6.
Thanks!

**Comment by ballashop** [comment]
I discovered why it generates error:
See the image.
![iso-problem](https://user-images.githubusercontent.com/28685316/57930360-0c76bd00-78b6-11e9-8d4d-67b4bd9a6caf.gif)

When accessing the province (ex state) change, the ISO code field generates a space before the text!
Thanks a lot.

**Comment by khouloudbelguith** [comment]
@ballashop, thanks for your feedback.
