### ISSUE TITLE
Wrong quantities for products' attributes/combinations

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#13833]
Hello !

That concerns Prestashop 1.6.1.6 but maybe you should try it on 1.7 (because the function is the same). I figured a bug but I'm not sure how I can make it again. Probably by adding an attribute and then delete it and then add it again. I've soon some quite similar issues here but not exactly the same.

**Here is the problem (and the solution at the bottom) :**
after doing the previously mentioned action (not sure, but seems to be it), the tab with the combinations' tab lists your attributes (for example A, B, C) with ordered IDs (ex: 30,31,32) BUT the quantities' tab lists them in a odd way. IDs are not ordered but Names are, which make them wrong. Example A=31, B=32, C=30. Meaning they are also wrong in the Front office but in a weird way : If you select for exemple attribute A, that is 0 in the backoffice, it appears good in the front office because IDs are not the same. Meaning you can order a product that **should** have no stock.

**The solution**
After a quick search, I found out that the file classes/Product.php has the function getAttributesResume() which give attribute's information. Everything looks good except this : 
```
 $combinations = Db::getInstance()->executeS('SELECT pa.*, product_attribute_shop.*
				FROM `'._DB_PREFIX_.'product_attribute` pa
				'.Shop::addSqlAssociation('product_attribute', 'pa').'
				WHERE pa.`id_product` = '.(int)$this->id.'
				GROUP BY pa.`id_product_attribute`');
```

Because it doesn't order anything. Which means, if an id_product_id is after a lower one in the database, the array badly increments. Then I've added the last line, which change it to : 

```
 $combinations = Db::getInstance()->executeS('SELECT pa.*, product_attribute_shop.*
				FROM `'._DB_PREFIX_.'product_attribute` pa
				'.Shop::addSqlAssociation('product_attribute', 'pa').'
				WHERE pa.`id_product` = '.(int)$this->id.'
				GROUP BY pa.`id_product_attribute`
				ORDER BY pa.`id_product_attribute` ASC');
```

After that, I checked everything, and everything looks good in every pages in the backoffice and in the front office. 

Even if there are no bugs in PS 1.7, I think it's important to order this query since things can move. And I've seen that this query is still without the ordering in PS 1.7.

Hop that helps

**Comment by khouloudbelguith** [comment]
Hi @hellodracon,

Thanks for your report.
Isn't the same issue with this ticket: #12814?
Thanks!

**Comment by hellodracon** [comment]
Hi @khouloudbelguith  I though at first but #12814 is more about the total of the product quantities when mine is more about each attributes' quantities that are note linked to the good attribute's name. I don't think that's the same issue. Maybe related but not the same exactly.

**Comment by khouloudbelguith** [comment]
@hellodracon, could you please confirm these steps:
1. create a product which has 3 combinations A, B & C
2. A, B & C have the same quantity = 5
3. order the combination C
4. delete this combination C
5. Re-create the combination C 
6. There is something wrong with the Quantity of the combination C => Which is?

In my case, it is OK, just this issue #12814 => NOK
Thanks!

**Comment by hellodracon** [comment]
@khouloudbelguith 

No sorry if I don't succeed to explain it clearly.

1. create a product which has 3 combinations A, B & C
2. A, B & C have different quantities (5,10,15)
3. _something happened, I don't know what exactly but quantities in the ps_product_attribute are not ordered by ID. Maybe I've deleted a combination and recreated it or it has been ordered differently by an action from PS._
4. I go back to the quantities tabs and now A has the B's quantity, B has the C's quantity and C has the A's quantity.

The 3/ is the problem since I don't know how it happened but that made me discover that the query in classes/Product.php is not good since it fills the $combinations array without sorting the results. Which means IF the id of a combination has another sibling with a lower ID after in the database, the array will be wrong.

I understand that it doesn't seem like a problem for you since I don't know how to reproduce the problem but my guess is at at some point, Prestashop edit ps_product_attribute table maybe by deleting/adding a line instead of editing it which brings it to have non-ordered id_product_attribute rows.

I guess it's more like a protection

**Comment by khouloudbelguith** [comment]
@hellodracon, sorry, I made some tests, but I did not manage to reproduce the issue with PS1.7.6.0beta1.
Did you manage to reproduce with PS1.7?
Thanks!

**Comment by hellodracon** [comment]
@khouloudbelguith :

unfortunately no as I don't know where exactly Prestashop changes the order of the records in ps_product_attribute without changing their IDs.

I'll try to find out (could be anything, maybe deleting an attribute that is used in a product without deleting if from the product before and recreate and re-use it afterwards since it's not "deleting an attribute in a product and then re-use it"), but don't have much time to do so. But the issue to find is this one : a change in the table _ps_product_attribute_ that let an attribute keeps its ID but changes its place in the table to appear **after** siblings with higher IDs

Nevertheless, I think my update is quite good just to make sure, if that happens, that the $combinations array is well filled. It's not a good idea to not order this query in my opinion.

**Comment by khouloudbelguith** [comment]
@hellodracon, I tried to delete an attribute, then re-create it, order it => no problem reproduced in the quantity
Thanks to check & provide me the exact steps to reproduce the issue.
Thanks!

**Comment by hellodracon** [comment]
@khouloudbelguith will do and let you know

**Comment by khouloudbelguith** [comment]
@hellodracon, thanks!

Waiting for your feedback.

**Comment by hellodracon** [comment]
@khouloudbelguith I tried a lot of things, nothing is happening. I really don't know how we managed to change the order of the rows in ps_product_attribute the first place (maybe a problem in the database itself). 

Maybe someone else will have this issue and find this thread one day :) If yes, the solution I give in my first message works well. Maybe that's something to do with multistore and copying products and I don't have the motivation to do all the tests. Don't bother yourself as I really don't know how that happened.

**Comment by khouloudbelguith** [comment]
@hellodracon, Thanks for your feedback.
Since I cannot reproduce the issue, I will close it.
Feel free to open a new one when needed.
Thanks!

**Comment by giles247** [comment]
@hellodracon Thank you so much for your efforts on this! this has resolved an issue our client had recently.

The issue was that in the admin area under product > prices for combinations, the attributes listed and their quantities were not synced with what was being displayed on front end for customer. We took a copy of the site and installed locally, yet it worked. Exactly the same PS version, PHP version, database version etc... Was very strange. On investigation it seemed that the attributes being fetched by getAttributesResume() were not in the correct order on the client's site. Even stranger was this had not been an issue a week ago or for many years before. The only event that had happened in the last week was the data center had migrated the client to a new server. So what I believe might have happened is the database transfer somehow disrupted the default sort order of items in one of the attribute related tables, yet this sort order was corrected when we ran a MySQL import of the client's data locally - hence why we were not able to reproduct locally.

So of course PS team unable to replicate as they have test data as inserted into tables and in correct order. It's only when some event such as a database migrations occurs that could disrupt ordering that this bug occurs. So what I need to do now is investigate whether the additional sort you added should really exist in all future PS versions.

Thanks again for your fix and documenting it - 3 years later someone did find it

**Comment by hellodracon** [comment]
Glad I could help @redactuk

**Comment by CyberCr33p** [comment]
Had the same issue after upgrading MySQL from 5.7 to 8.0. Changing the query in classes/Product.php solved the issue. Thank you.

**Comment by LFCDK** [comment]
PrestaShop 1.6.1.24 
Perfect!
Thank you
