### ISSUE TITLE
How to change menu text on admin panel: State --> Province

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#13834]
**Describe the bug**
We need to change "State" text into "province" because State text it is not clear in Italiano.
Thanks a lot
**To Reproduce**
1. Go to 'Location'
2. Click on 'Translation'
3. Scroll down to '?'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![stati-to-province](https://user-images.githubusercontent.com/28685316/57924356-2b208800-78a5-11e9-982e-8250407817ae.png)

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

You need to navigate to your BO => Localization => Translation 
1. Type of translation: Back office
2. Select you language
3. Click Modify
4. Expand all fieldsets
5. translate the menu name from the ADMINLOCALIZATION

Also, you can edit it manually from the database => table ps_tab_lang
![image](https://user-images.githubusercontent.com/16067358/57925656-e0047600-78a0-11e9-9130-98281bc8f1c5.png)

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by ballashop** [comment]
thanks a lot, I did by db.
