### ISSUE TITLE
Regression faceted search

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13839]
**Describe the bug**
Regression on faceted search version 3.0.0

**To Reproduce**
1. Install faceted version 3.0.0 (currently dev branch of the module)
2. Click on Shop parameters > Product settings
3. For "default order by" in pagination part, select product reference, brand, product modified date or product add date, product price, product inside category
4. See errors in FO

**Screenshots**
![capture d'écran_1556 product ref](https://user-images.githubusercontent.com/13449658/57927985-da625c80-78af-11e9-90c9-1679f651f087.png)

![capture d'écran_1556 brand](https://user-images.githubusercontent.com/13449658/57927991-dcc4b680-78af-11e9-8c6c-06e08db0cfbb.png)

![capture d'écran_1556 prod modified date](https://user-images.githubusercontent.com/13449658/57927996-df271080-78af-11e9-9e08-142c4009e386.png)

![capture d'écran_1556 prod add date](https://user-images.githubusercontent.com/13449658/57928005-e2220100-78af-11e9-92c1-dc2887ac238d.png)

Filter by product price is NOK if you have a product with specific price

![capture d'écran_1556](https://user-images.githubusercontent.com/13449658/57929071-a3da1100-78b2-11e9-94f2-aecb9812a2fb.png)

Filter by product inside category is NOK

![capture d'écran_1559](https://user-images.githubusercontent.com/13449658/57929210-f61b3200-78b2-11e9-947a-5d56eabf53fa.png)

![capture d'écran_1558](https://user-images.githubusercontent.com/13449658/57929214-f87d8c00-78b2-11e9-9860-cfecf063c407.png)

![capture d'écran_1557](https://user-images.githubusercontent.com/13449658/57929216-fa474f80-78b2-11e9-943f-4899cd575a95.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by PierreRambaud** [comment]
Fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/59

**Comment by marionf** [comment]
Fixed also by https://github.com/PrestaShop/ps_facetedsearch/pull/60
