### ISSUE TITLE
Improve tooltip wording of the Products settings' "Default activation status" option

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13841]
The **"Default activation status"** setting in the Product settings allows to automatically activate/disable products when they are created.

![Capture d’écran 2019-05-17 à 16 10 04](https://user-images.githubusercontent.com/47456895/57934364-ddfddf80-78bf-11e9-8243-f38ebd3a25ef.png)

But this setting only applies to manual product creation and does not apply to creation through import.

It is not clearly indicated and can lead to confusion for the user.

![Capture d’écran 2019-05-17 à 16 10 53](https://user-images.githubusercontent.com/47456895/57934384-e6eeb100-78bf-11e9-8384-3451de0aa9e1.png)

## Specs

**Page:** Shop parameters > Product Settings

**Describe the solution you'd like:**
Modify the tooltip wording of the "Default activation status" setting 

**Current tooltip wording:** "When active, new products will be activated by default during creation."

**New tooltip wording:** "Enable this option if you want to activate by default all your manually created new products."

**Comment by LouiseBonnard** [comment]
I would even write _Enable this option if you want to activate by default all your created manually new products._, what do you think?

**Comment by ghost** [comment]
Sounds good, easier to read.
You are the content master, I let you have the final decision :)

Though I'm not sure about "manually" being put after "created", I would rather say "manually created products", wdyt?

**Comment by LouiseBonnard** [comment]
I was wondering about that as well... I've just asked Damian, it's _Enable this option if you want to activate by default all your manually created new products._, perfect then! And the localization remains in the same domain. ;-)

**Comment by ghost** [comment]
Updated the specs
