### ISSUE TITLE
Error 500 - Module Manager

### ISSUE THREAD

**Issue by bestbuybargains** [PrestaShop/PrestaShop#13846]
**Describe the bug**
I am getting an Error 500 when I click on Module > Module Manager

**To Reproduce**
1. Go to Back Office
2. Click on Module > Module Manager
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/50038176/57943378-80569c80-7899-11e9-8b57-9775427d3a33.png)

![image](https://user-images.githubusercontent.com/50038176/57943407-95cbc680-7899-11e9-890d-77499a0173a1.png)

![image](https://user-images.githubusercontent.com/50038176/57943423-a3814c00-7899-11e9-829e-8ade2e9919f1.png)

![image](https://user-images.githubusercontent.com/50038176/57943519-d9263500-7899-11e9-9615-4582d27e9cc9.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33
![image](https://user-images.githubusercontent.com/50038176/57944266-14c1fe80-789c-11e9-8ae9-f9d81774af5e.png)

**Comment by PierreRambaud** [comment]
Look like you're trying to install prestasho-integration which is a Wordpress plugin 🤔 
https://wordpress.org/plugins/prestashop-integration/

**Comment by bestbuybargains** [comment]
Awesome catch!  You are so amazing :-)  I went into the server and deleted the folder Prestashop Integration and resolved the issue. Thank you!

**Comment by PierreRambaud** [comment]
You're welcome 😉
