### ISSUE TITLE
Missing label for Seo preview in cms form 

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#13848]
**Is your feature request related to a problem? Please describe.**
PS 1.7.6.x In Improve > Design > pages > Add new/ Edit Cms form seems to miss a label/explanation of SEO preview field.

**Describe the solution you'd like**
Add label and/or hint for SEO preview field, so user would be able understand what is it about.

**Additional context**
![Screenshot from 2019-05-18 14-13-40](https://user-images.githubusercontent.com/31609858/57968789-ad797c80-7977-11e9-9abe-3ed2372f6d22.png)

**Comment by sarjon** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/13806

**Comment by khouloudbelguith** [comment]
Ping @colinegin @marionf what do you think?
Thanks!

**Comment by colinegin** [comment]
@TristanLDD would you recommend to put both label and title + description ?

**Comment by TristanLDD** [comment]
I think the best solution to adapt this component to any form is to harmonise it with the display of other inputs: 

![Capture d’écran 2019-05-21 à 18 45 24](https://user-images.githubusercontent.com/27484094/58114715-a44b1280-7bf8-11e9-92b3-db0ee3641cb3.png)

The title + description was basically designed for the product page, but I didn't knew we would use the SEO preview on other forms. 
Also, it is important that the description below the preview doesn't mention a specific page, as it is the case in product page preview description.
