### ISSUE TITLE
How do you sent the page layout for a controller when installing a module

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#13844]
**Describe the bug**
When installing a controller as part of a custom module in 1.6, you could define it as using the left/right column, stored in the theme table in the database.
With 1.7 this has been removed, and in the layout options you can manually choose which layout the controller page should have.
The question here is, how do you set this automatically when installing the module?

**To Reproduce**
You would need to create a custom module, with a custom front controller.

**Screenshots**
How to set this value during module installation
![image](https://user-images.githubusercontent.com/19314911/57940206-94969b80-7891-11e9-9fd5-cbd13c91d852.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @roja45,

Could you please provide your custom module to check it.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @roja45,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by roja45** [comment]
oh, sorry, I didn't realise you were waiting on me.  I'll create a test module, and open another.

Thanks

**Comment by khouloudbelguith** [comment]
@roja45, I just re-opened the issue.
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @roja45,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by alisamie97** [comment]
i installed a custom module with a front controller using hook moduleRoutes, but its not appearing in the layouts list,
