### ISSUE TITLE
The steps missing in welcome module

### ISSUE THREAD

**Issue by ntiepresta** [PrestaShop/PrestaShop#13845]
**Describe the bug**
The welcome module isn't complete in the BO => Payments =>Payment Methods, , the step  4/6( Get your shop ready for payments) the steps 1/2 and 2/2 missing 

**To Reproduce**

1. BO => International => Locations => Countries Tab => Edit an enabled country (France)
2. Add the Customer fields in the Address format 
1. Go to  BO => Modules => Module Manager ( Reset welcome module)
2. Click on yes, reset it
3. refresh your shop and click on resume in configure tab
4. click on start and start the steps.

**Screenshots**
Before 
![avant1](https://user-images.githubusercontent.com/36889855/57942166-122dcc00-78d1-11e9-9333-8f85375c357d.png)

![avant2](https://user-images.githubusercontent.com/36889855/57942196-25d93280-78d1-11e9-8f60-88fc967f8407.png)

After
![now1](https://user-images.githubusercontent.com/36889855/57942174-178b1680-78d1-11e9-9c51-353c270bc87f.png)

![now2](https://user-images.githubusercontent.com/36889855/57942206-2bcf1380-78d1-11e9-9c5a-b1e92f373966.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by marionf** [comment]
The issue is the following:
At the first step of the welcome module you are at 2/6 instead of 1/6

![capture d'écran_1568](https://user-images.githubusercontent.com/13449658/58036730-1d306880-7b2c-11e9-9e71-d365f9bd2087.png)

But this issue is also on 1.7.5.2 so it's not a regression

**Comment by marionf** [comment]
@ntiepresta 

I correctly have steps 2 on payment method and carrier pages.

![capture d'écran_1569](https://user-images.githubusercontent.com/13449658/58037242-443b6a00-7b2d-11e9-8e2d-40aa61ae19ba.png)

These parts are managed by MBO, so please verify you have MBO module installed
Furthermore, you need to wait a few seconds before to see them displayed

If MBO isn't installed, it's normal if you don't see them

**Comment by ntiepresta** [comment]
Thank your @marionf 

You are right for this issue, if the ps_MBO is installed we don't have this issue. In addition, the ps_mbo is not installed by default on  fresh install, and ps_bestsellers for example. The ps_mbo should installed by default.
Thanks,

**Comment by marionf** [comment]
Because modules have not been updated yet for 1.7.6
