### ISSUE TITLE
How should I test my payment method

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#13843]
Hello, I want to test if my payment method is ready to go. Please tell me how to. Thank you.

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

You need to do simple tests to make sure that the module does not break the BO or FO?

-Installing the module / uninstalling it 
-Check that the module does not break the BO module manager page
-Verification of some actions in FO: display a category, the product page and place an order

Also, we have the validator PrestaShop: https://validator.prestashop.com
Thanks!
