### ISSUE TITLE
New field address3

### ISSUE THREAD

**Issue by miha1** [PrestaShop/PrestaShop#13858]
As part of the new [3-D Secure](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) standard that is coming into force in Europe, there are a number of new parameters that must be sent to credit card acquirers.

One of these is a third street field for the customer's address (billing and shipping). To ensure full compliance of Prestashop with the new standard I request that this field be added.

Solution would be to have a new, third street field (address3) added to it by default .

**Comment by khouloudbelguith** [comment]
Hi @miha1,

In the new release PS1.7.6., we have added a new hook named additionalCustomerAddressFields, this hook add fields to the Customer address form, it returns an array of FormFields to add them to the customer address registration form.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9132 

Thanks!
