### ISSUE TITLE
Anchor ads code

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#13854]
Hello
I'm on PS 1.7 and when I add    overlays: {bottom: true} to this code the site stop 

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-xxxx",
    enable_page_level_ads: true,
    overlays: {bottom: true}
  });
</script>
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

What is the exact file did you edit?
Is this a module installed in PrestaShop?
What is the exact version Prestashop did you use?
Thanks!

**Comment by go-sudo** [comment]
Additionnal information
PrestaShop version: 1.7.5.1
PHP version: Plesk php 7.2.15
Informations sur votre serveur Linux #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.15

Limite de mémoire : 6056M

Temps maximal d'exécution : 3000

Taille max. pour envoi de fichiers : 70M

Code added to file footer.tpl

```
  {if Context::getContext()->isMobile()}
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-2843469830642836",
     enable_page_level_ads: true,
     });
</script>{else}{/if}
```

Google said that to move ads to bottom we should add 	 overlays: {bottom: true}
as it described on the link below
https://support.google.com/adsense/answer/7478225?hl=en

and wen i do it the website go offline and i get this error

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/var/www//templates/_partials/footer.tpl" on line 42 "overlays: {bottom: true}" - Unexpected ": ", expected one of: "}" <-- \n thrown in /var/www/vhosts//smarty_internal_templatecompilerbase.php on line 42\n', referer: https://www.google.com/`
Regards
--

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your feedback.
You need to use `{literal}` option as described here https://www.smarty.net/docsv2/fr/language.function.literal.tpl
I replaced this 

```
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1234567891234567",
    enable_page_level_ads: true,
    overlays: {bottom: true}
  });
</script>
</head>
```

by this

```
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
{literal}
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1234567891234567",
    enable_page_level_ads: true,
    overlays: {bottom: true}
  });
</script>
{/literal}
</head>
```

and it works!
![image](https://user-images.githubusercontent.com/16067358/59342100-ff0bf180-8d00-11e9-934e-c349174428b5.png)

I close the issue.
Feel free to open a new one when needed.

Thanks!
