### ISSUE TITLE
Add a new product type: Gift cards

### ISSUE THREAD

**Issue by miha1** [PrestaShop/PrestaShop#13859]
As part of the new [3-D Secure ](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) standard that is coming into force in Europe, there are a number of new parameters that should be sent to credit card acquirers.

There are a few parameters related to tracking gift card purchases, but as Prestashop currently does not support gift cards by default so I am unable to track these.

This is different from discount codes in that users would be able to purchase a kind of credit in advance from the shop.

I'd love to have a new product type "Gift Card" that could be selected when creating a product. It could be a subset of virtual product or phyiscal product that generates a discount code on purchase.

**Comment by khouloudbelguith** [comment]
Hi @miha1,

Thanks for your report.
This is something that can be improved with a module
https://addons.prestashop.com/en/wishlist-gift-card/16680-gift-card-advanced-solution.html
Also, you can search some other modules in our [addons Market place](https://addons.prestashop.com/en/search?search_query=gift%20card)

Thanks to check & feedback

**Comment by espacious** [comment]
> As part of the new [3-D Secure ](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) standard that is coming into force in Europe, there are a number of new parameters that should be sent to credit card acquirers.
> 
> There are a few parameters related to tracking gift card purchases, but as Prestashop currently does not support gift cards by default so I am unable to track these.
> 
> This is different from discount codes in that users would be able to purchase a kind of credit in advance from the shop.
> 
> I'd love to have a new product type "Gift Card" that could be selected when creating a product. It could be a subset of virtual product or phyiscal product that generates a discount code on purchase.

Hi, Miha1
i found those two for free:
https://www.prestashop.com/forums/topic/355886-giftcard-3/ (i used this one a little pain translating it but all working)
https://www.knowband.com/prestashop-free-gift-card-manager (this seems better)

one from Vekia:
https://mypresta.eu/modules/advertising-and-marketing/gift-cards-sell-voucher-codes.html

**Comment by khouloudbelguith** [comment]
@miha1, great!
Thanks a lot for your feedback.
Since this improvement could be done by a custom module, I will close the issue, feel free to open a new one when needed.

Thanks!
