### ISSUE TITLE
Cannot disable Debug Mode

### ISSUE THREAD

**Issue by M4tho** [PrestaShop/PrestaShop#13855]
After enabling the "debug mode" with the profiling tools for fixing a bug, it cant be disabled any more.
In the settings and the config file the debug mode is disabled.
But on any site (Back- and FrontEnd) i see the profiling inforamtions.

I don't really know how to reproduce this bug, just enable the Debug Mode and thats it.

**Screenshots**

![image](https://user-images.githubusercontent.com/11182709/57980308-30f3a600-7a2a-11e9-8699-0f2850abf669.png)
This is what my backend looks like....

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.29

**Comment by khouloudbelguith** [comment]
Hi @M4tho,

You need to disable the debug profiling.
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', false);
}
```

Thanks to check & feedback

**Comment by M4tho** [comment]
Hey @khouloudbelguith 
Thanks for your tipp, but as far as i can see, it is already disabled:

    define('_PS_DEBUG_PROFILING_', false);

In my version of the defines-file there is no if(!defined.... 
but i've never changed this particular file

**Comment by khouloudbelguith** [comment]
@M4tho,

>After enabling the "debug mode" with the profiling tools for fixing a bug

What are the exact steps did you follow to disable the debug mode? from the BO => Advanced Parameters => Performance page? or by editing file Projetc_Folder/config/defines.inc.php?
Thanks!

**Comment by M4tho** [comment]
Yes I've disabled it via the BO

**Comment by khouloudbelguith** [comment]
@M4tho, could you please try to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @M4tho,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
