### ISSUE TITLE
New field phone_work

### ISSUE THREAD

**Issue by miha1** [PrestaShop/PrestaShop#13860]
As part of the new [3-D Secure](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) standard that is coming into force in Europe, there are a number of new parameters that should be sent to credit card acquirers.

Some of these parameters relate to the tracking of a user's phone number. Currently there is only two fields (**phone and phone_mobile**), whereas the standard proposes three separate ones (**mobile_phone, work_phone, home_phone**).

It would be great to have a new field **phone_work** to track the three different types of phone numbers within the default checkout workflow of Prestashop so that full compliance with 3DS 2.0 can be ensured.

**Comment by khouloudbelguith** [comment]
Hi @miha1,

As described in this issue: #13858, you can add some fiedls to the customer address form using the additionalCustomerAddressFields hook.
You can use this hook to add a new field work_phone in the address form.
This hook is added in the PS1.7.6.0.
Here's a test module link for this hook.
https://github.com/PeeyushAgrawalWebkul/Testing-module-PR-9132/tree/master
Thanks!

**Comment by khouloudbelguith** [comment]
Related to  #13858

**Comment by miha1** [comment]
Thanks 👍
