### ISSUE TITLE
Difference of empty categories in categories kpi and monitoring

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#13873]
**Describe the bug**
I've generated some categories (10 000 (using https://github.com/PrestaShop/prestashop-shop-creator)) and encountered some bugs in categories page. The thing is that the generator might be associated with these bugs, so it need to be tested by hand. So these are the bugs:
1. The missmatch of empty category number in categories KPI and monitoring page. (screenshot 1)
2. When being in a list of any child categories and changing items per page value - the root categories page is loaded instead of current page reload. For example being in Home > HomeChild category, when i change items per page, i get redirected to Home.

**Screenshots**
![Screenshot from 2019-05-20 13-57-50](https://user-images.githubusercontent.com/31609858/58017019-dd578a00-7b07-11e9-8cec-74e49c09a570.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I tried to add a large number of categories via API using this script

```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 20/05/19
 * Time: 14:44
 */

ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
//                      !! BACHA, nezapomenout přenastavit i DTB u obrázků dole !!!
define('PS_SHOP_PATH', 'http://0.0.0.0:8008/1760'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'I3PHFEFTU5L3EJADCXWPLI1UBR4LCXEY'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = $webService -> get(array('url' => PS_SHOP_PATH . '/api/categories?schema=synopsis'));

//$j=515;
for ($i = 1; $i <= 10510; $i++) {
$resources = $xml -> children() -> children();
unset($resources ->id);
unset($resources ->position);
unset($resources ->date_add);
unset($resources ->date_upd);
//unset($resources ->id_parent); //if unset category will be root. If set it must have id existing parent category!
unset($resources ->level_depth);
unset($resources ->nb_products_recursive);
$resources ->id_parent = 8;
//$j=$j+1;
$resources ->name ->language[0][0] = 'cat_kh';
$resources ->link_rewrite->language[0][0] = 'cat';
$resources ->active = 1;
$resources ->id_shop_default = 1;
$resources ->is_root_category = 0;

$opt = array('resource' => 'categories');

$opt['postXml'] = $xml -> asXML();

    $xml = $webService->add( $opt );
}
```

The first issue, I did not manage to reproduce it with more than 11000 categories
![image](https://user-images.githubusercontent.com/16067358/58075990-f4968600-7ba0-11e9-9e2d-fa70d5ea77fa.png)
![image](https://user-images.githubusercontent.com/16067358/58076007-feb88480-7ba0-11e9-9efa-0da065dae8e4.png)

The second issue, Yes, I manage to reproduce the issue with PS1.7.6.0beta1
In the PS1.7.5.2 => OK

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13984
