### ISSUE TITLE
Able to set the quantity more than available for existing order in BO

### ISSUE THREAD

**Issue by hanicab** [PrestaShop/PrestaShop#13871]
**Describe the bug**
Admin is able to set the quantity more than available when editing existing order in BO

**To Reproduce**
1. Set a product quantité to 1 pc , and set 'disallow orders when product is out of stock'
2. Create an order from FO with this product
3. Go to BO and Try to edit the quantity of this product in this existing order
4. You will be able to set any quantity for this product ( you should not because product is out of stock)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @hanicab,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1, PS1.7.5.2 & PS1.7.4.2.
In the BO => Shop Parameters => Product Settings `Allow ordering of out-of-stock products` is disabled => this option disables the Add to Cart button when a product is unavailable. 
But it has no effect in the BO when updating an order => update the product quantity => NOK
![image](https://user-images.githubusercontent.com/16067358/58016279-205c3200-7af5-11e9-9735-fc684ac66f8b.png)

If we try to make an order from the BO, with a product out of stock, an alert is displayed => OK
![image](https://user-images.githubusercontent.com/16067358/58016086-b774ba00-7af4-11e9-814c-3e46e9d6bbbf.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by blks** [comment]
Well we have the same problem and we managed to find a quick solution for it, this is the code that you can use until it will be fixed in next builds:

We need to change the methode **ajaxProcessEditProductOnOrder**  in the **AdminOrderController.php** controller.

PS: use it as an override 
>
      public function ajaxProcessEditProductOnOrder()
    { ...
       // Check fields validity
        $this->doEditProductValidation($order_detail, $order, isset($order_invoice) ? $order_invoice : null);
           
            // Check if Qty is submited
              if ( Tools::getValue ( 'product_quantity' ) ) {   
                   
                // check in stock Qty
                $StockAvailable = StockAvailable::getQuantityAvailableByProduct($order_detail->product_id, $order_detail->id_product_attribute , $order_detail->id_shop);
                
                // get the key that make us decide if this product is orderable when out of Qty or not
                $sql = 'SELECT out_of_stock FROM ps_stock_available WHERE id_product = '.$order_detail->product_id.'';
                if ($results = Db::getInstance()->ExecuteS($sql))
                    foreach ($results as $row)
                        $canOrder = $row['out_of_stock'];

                // Check if submited qty is superior to orignal qty
                if( Tools::getValue('product_quantity') - $order_detail->product_quantity > 0 ){                
                    
                    if($StockAvailable > 0 ){
                       $addedQty = Tools::getValue('product_quantity') - $order_detail->product_quantity ;
                        if(  $addedQty > $StockAvailable ){
                            if ( (int)$canOrder != 1  ) {
                             die(json_encode(array('error' => $this->trans('You already have the maximum quantity available for this product.', array(), 'Admin.Orderscustomers.Notification'))));
                             return false;
                            }
                        }
                          
                     }else{
                        if ( (int)$canOrder != 1 ) {
                             die(json_encode(array('error' => $this->trans('You already have the maximum quantity available for this product.', array(), 'Admin.Orderscustomers.Notification'))));
                             return false;
                        }
                     }
                }   
                
            }

**Comment by khouloudbelguith** [comment]
Hi @blks,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by blks** [comment]
> Hi @blks,
> 
> Would you be willing to make a pull request on GitHub with your code suggestion?
> https://github.com/PrestaShop/PrestaShop/tree/develop
> Thank you!

Fine @khouloudbelguith  , I'll do it .

**Comment by colinegin** [comment]
ping @MatShir I do not reproduce this issue, can you confirm ? 
But I noticed another issue, it seems that you can not add to the maximum quantity available.
Let me give you an example : If I have 2 quantities left and I buy one product, if in BO I try to edit to add the 2nd item I get an error. 
![image](https://user-images.githubusercontent.com/35263827/85023414-fc927200-b174-11ea-8385-381249326a90.png)

Can you confirm ?

**Comment by colinegin** [comment]
As discussed with @jolelievre we no longer reproduce this issue, so we can close it. 
Unfortunately we have discovered a new issue (regression), I'll add it here.

**Comment by jolelievre** [comment]
New issue https://github.com/PrestaShop/PrestaShop/issues/19855
