### ISSUE TITLE
500 Server Error at log out at order page in Prestashop 1.7.3.0

### ISSUE THREAD

**Issue by davidcmx** [PrestaShop/PrestaShop#13881]
**Describe the bug**
I have an e-commerce with Prestashop 1.7.3.0, and I have a problem with the log out in the front-end, in any part of the site it works correctly, but in the order page (when you proceed to make the order after the cart page), when I need to log out there, the site throw a 500 Server Error. I have activated the debug option, and this is the error that shows me.

**To Reproduce**
1. Sign in.
2. Go to 'checkout page'.
3. Click on 'Sign Out'.
4. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/50840082/58037251-9dd27300-7af2-11e9-8759-611449db17dc.png)

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @IngDavidCm,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2
It seems that you have an override of the class DeliveryOptionsFinder.php
![image](https://user-images.githubusercontent.com/16067358/58076702-cade5e80-7ba2-11e9-847e-681f0db66cb2.png)
This override is not compatible with your version.
You should contact the module author if it is created by a custom module.
Thanks to check & feedback.

**Comment by davidcmx** [comment]
Hi @khouloudbelguith 

Thanks for your help.
With the information we found the problem, and yes, was a module, we uninstall the module since it was not necessary.

Thanks for your time.

**Comment by khouloudbelguith** [comment]
@IngDavidCm,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
