### ISSUE TITLE
displayBackOfficeTop hook should be in nav container

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#13893]
In the new backoffice theme, the hook displayBackOfficeTop has been moved outside the nav container. We can't add buton in fixed navigation bar : It's a regression.

Here is the old hook position
https://github.com/PrestaShop/PrestaShop/blob/fbd75202b69460805724201068f162e4e371a997/admin-dev/themes/default/template/header.tpl#L385

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by PierreRambaud** [comment]
Seems legit! :+1:
