### ISSUE TITLE
Unable to load template file:layout-ajax.tpl

### ISSUE THREAD

**Issue by paolo75015** [PrestaShop/PrestaShop#13892]
I am not able to import products via CSV into my Prestashop database. I select my file, set the parameters I need, set the mapping with columns in my file and then I get this error message in my browser console :

> An exception has been thrown during the rendering of a template ("Unable to load template 'file:layout-ajax.tpl'").

I already:

- test another CSV. Same error.
- delete manually /var/cache/dev/ and /var/cache/prod/ folders
- check CHMOD of my /admin/ and /src/ folders and subfolders (755 for directories, 644 for files)

The layout-ajax.tpl exists, I don't understand why Prestashop can't use it. By the way, my website front-end and back-end work perfect ! But I recently upgrade my Prestashop from 1.7.5.1 to 1.7.4 to 1.7.5, maybe a CHMOD is not correct somewhere ?

![error png 50a55e6c5faaf4b814a61ff168a977ce](https://user-images.githubusercontent.com/30658093/58085555-3df4ce80-7bbd-11e9-95bd-68a657514ce0.png)

PrestaShop version: 1.7.5.1
PHP version: 5

**Comment by khouloudbelguith** [comment]
Hi @paolo75015,

Could you please provide me the exact file csv, you tried to import it, to test it.
Thanks!

**Comment by paolo75015** [comment]
@khouloudbelguith unfortunately I can't because our products are confidential, but I created a sample file (same columns), please fint "test.csv" attached. Same error. I believe it will work on your side, the issue could be related to a CHMOD or a missing file in my FTP ?

[test.zip](https://github.com/PrestaShop/PrestaShop/files/3201934/test.zip)

**Comment by khouloudbelguith** [comment]
@paolo75015, no I have this error
![image](https://user-images.githubusercontent.com/16067358/58095159-41428700-7bca-11e9-8af9-8e3bae3b62bd.png)
I tried with the default CSV file & it is OK
Thanks!

**Comment by paolo75015** [comment]
This is the result I got on my Prestashop with the test.csv.

![Sans titre](https://user-images.githubusercontent.com/30658093/58131461-074fa000-7c1f-11e9-8787-157433d6e9d0.png)

**Comment by paolo75015** [comment]
I found a solution... by unchecking the parameter "Use product reference as key".

**Comment by khouloudbelguith** [comment]
@paolo75015, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Comment by Jacky75** [comment]
Hi,
what can I do if I need to keep  "Use product reference as key"? I have thousands of products to update by reference...

**Comment by khouloudbelguith** [comment]
Hi @Jacky75,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by jonasburneika** [comment]
@khouloudbelguith I had the same issue with Features import and problem are with Feature name or value containing special characters like Ø, °C, and Feature and Feature Class name has validation isGenericName. After removing validation rule I could import values. 
`  'name' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isGenericName', 'required' => true, 'size' => 128),`

You need to return some error message here. If validation failed as in Product Name.

I have attached my features import file. feel free to test with it.
[2020-05-15_prodcut_import_irankiai_specifikacijia.xlsx](https://github.com/PrestaShop/PrestaShop/files/4633248/2020-05-15_prodcut_import_irankiai_specifikacijia.xlsx)

**Comment by mreduar** [comment]
I recently upgraded to the latest version of prestashop 1.7.7.8. And when I try to change the customer from one order to another customer, I get this same error. Is there any solution for this problem? I have been trying to figure out what the problem is myself, but I could not solve anything.
