### ISSUE TITLE
Error Stock in New Products

### ISSUE THREAD

**Issue by sebaborda04** [PrestaShop/PrestaShop#13901]
I am loading the stock as the images show.
I attach the images step by step.
1-update stock in 4 new products
2-click on the "Apply new Quantity" button
3-The stock was updated
4-Re-enter Stock Management
5-There is only one product with stock!

![stock](https://user-images.githubusercontent.com/50870195/58094229-8d7bd000-7ba6-11e9-987c-d77c33542d28.png)
![sotck3](https://user-images.githubusercontent.com/50870195/58094230-8d7bd000-7ba6-11e9-9f3f-be6e638bac25.png)
![stock2](https://user-images.githubusercontent.com/50870195/58094231-8d7bd000-7ba6-11e9-97f5-49e733172369.png)
![stock1](https://user-images.githubusercontent.com/50870195/58094232-8e146680-7ba6-11e9-8345-0e94f43cb2e7.png)

![Deshabilitado](https://user-images.githubusercontent.com/50870195/58094356-e186b480-7ba6-11e9-8b37-b0345d0373ef.png)
![Stock](https://user-images.githubusercontent.com/50870195/58094368-e51a3b80-7ba6-11e9-88d0-da6a6567441b.png)

Thanks, and help me, please.

**Additionnal information**
PrestaShop version: 1.7.2.4
PHP version:  Versión del software del servidor: Apache
Versión PHP: 7.1.22
Límite de memoria: 512M
Tiempo máx. de ejecución: 30
Tamaño máx. para la subida de archivos: 128M

**Comment by khouloudbelguith** [comment]
Hi @sebaborda04,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7..6.0beta1.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sebaborda04** [comment]
Do you mean this data?
![log](https://user-images.githubusercontent.com/50870195/58097252-52c96600-7bad-11e9-8cba-fd562bb734de.png)
![log1](https://user-images.githubusercontent.com/50870195/58097263-56f58380-7bad-11e9-8841-70cbca90ca48.png)
![log3](https://user-images.githubusercontent.com/50870195/58097264-58bf4700-7bad-11e9-9635-307fa92f8472.png)
![Sin título](https://user-images.githubusercontent.com/50870195/58097265-5a890a80-7bad-11e9-86a6-d22dac566ec2.png)

**Comment by khouloudbelguith** [comment]
@sebaborda04, when debugging mode enabled in your case => there is no exception.
You can use DevTools, so:

1. enable debug mode
2. go to the stocks page
3. open up developer tools
4. go to Network tab
5. Click on the "Apply new Quantity" button
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks to check & feedback.

**Comment by sebaborda04** [comment]
Error.
![error](https://user-images.githubusercontent.com/50870195/58098303-a341c300-7baf-11e9-8323-f8509d060b28.png)
![Error1](https://user-images.githubusercontent.com/50870195/58098307-a6d54a00-7baf-11e9-85ae-8c48a1e49675.png)

**Comment by khouloudbelguith** [comment]
@sebaborda04, you have some duplicated entry in the table ps_stock_avalible for the product which has id_product = 34.
Did you edit your database manually?
Thanks!

**Comment by sebaborda04** [comment]
I'm going to check it and I'll tell you ...
Thanks

**Comment by khouloudbelguith** [comment]
@sebaborda04, thanks!
Waiting for your feedback

**Comment by sebaborda04** [comment]
I do not have any product_id = 34 in the table ps_stock_avalible. The last number is the product_id = 31 and has id_stock_available = 0

**Comment by khouloudbelguith** [comment]
@sebaborda04, this error is displayed in your case
![image](https://user-images.githubusercontent.com/16067358/58107385-9f2e9900-7be1-11e9-9f25-fef1dd3f6719.png)
Thanks!

**Comment by sebaborda04** [comment]
![IMG-1579](https://user-images.githubusercontent.com/50870195/58108187-c07f8d00-7bc1-11e9-8a01-07c8945660d8.JPG)

**Comment by sebaborda04** [comment]
![Product_ID34](https://user-images.githubusercontent.com/50870195/58116451-aef2b100-7bd2-11e9-993a-48eb45952e88.png)
when I want to modify the product_id 34, it shows this error.

**Comment by khouloudbelguith** [comment]
@sebaborda04, could you please run the command SQL in your Database & feedback.

`Select * from ps_stock_available where id_product = 34;`

Thanks!

**Comment by sebaborda04** [comment]
now I see it
![IMG-1580](https://user-images.githubusercontent.com/50870195/58170293-60dcbc80-7c69-11e9-98a4-77beec6e85ca.JPG)

**Comment by khouloudbelguith** [comment]
@sebaborda04, the id_stock_available for this product which has id_product = 34 is incorrect.
id_stock_available = 0 where id_product = 34 => incorrect => you need to edit it.
Thanks!

**Comment by sebaborda04** [comment]
Thank you very much for the help.
What happens if that table is empty? I do not know why he kept that field at 0.

**Comment by khouloudbelguith** [comment]
@sebaborda04, in my case, it is OK.
I tried with steps that you provided but I did not manage to reproduce the issue.
Thanks!

**Comment by sebaborda04** [comment]
**If I empty that table, I only lose the stock or can I lose something else?**

**Comment by khouloudbelguith** [comment]
@sebaborda04, if you empty this table, you will lose the quantity of your products.
Make sure to have a backup of your database before deleting anything from the database.
Thanks!

**Comment by sebaborda04** [comment]
Thank you, you are very kind.

**Comment by khouloudbelguith** [comment]
@sebaborda04, you are welcome!
Can I close the issue?
Thanks!

**Comment by sebaborda04** [comment]
yes, Thanks

**Comment by khouloudbelguith** [comment]
@sebaborda04, Thanks!

Feel free to open a new one when needed.
THanks!
