### ISSUE TITLE
ps_facetedsearch : hidden product visible in filtering

### ISSUE THREAD

**Issue by ndkdesign** [PrestaShop/PrestaShop#13902]
suite à mise à jour du module en version 3.0.0 les produits en visibilité "nulle part" sont tout de même affichés lors d'une recherche par filtre

![capture d'écran_1571](https://user-images.githubusercontent.com/13449658/58098862-b322cc80-7bda-11e9-9dc1-2de56e92feef.png)

**Comment by khouloudbelguith** [comment]
Hi @ndkdesign,

Did you clone the last version ps_factedsearch from GitHub?
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.0.0
Thanks!

**Comment by ndkdesign** [comment]
Hi thanks for reply.
yes , a small precision : hidden products appears when you d'ont select filters, so on category page load, and disappear when you select filters.

Disabling module works and hidden products don't appear

**Comment by PierreRambaud** [comment]
Thanks for your feedback @ndkdesign 
Fixed in https://github.com/PrestaShop/ps_facetedsearch/pull/63 :)

**Comment by khouloudbelguith** [comment]
@ndkdesign, yes I manage to reproduce the issue with ps_facetedsearch  v3.0.0

**Comment by ndkdesign** [comment]
@PierreRambaud Merci!

**Comment by PierreRambaud** [comment]
@ndkdesign Thank to you for helping us making PrestaShop better :wink:
