### ISSUE TITLE
Exception appear when I upload a template too large

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13914]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: with debug mode active only
1. Go to Design -> theme & logo
2. Click on add a theme
3. Add a zip theme too large 
4. See the exception

**Screenshots**
<img width="1276" alt="Capture d’écran 2019-05-22 à 11 32 53" src="https://user-images.githubusercontent.com/3034677/58165729-a8bf0c00-7c88-11e9-9262-abb7a8749026.png">

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by matks** [comment]
The error message is not an issue, isn't it ? If file is too large to be handled by prestashop, it tells it to the BO user.

The exception should be hidden however IMO.

**Comment by sarahdib** [comment]
@matks the exception is the issue :)

**Comment by tomas862** [comment]
@matks @sarahdib  when using  "Import from your computer" functionality it handles max file upload size restrictions. In exception provided here I see that  when uploading a theme it reached out of memory which is different thing. It consumed around 500mb but 134mb are allocated only. For such opeartion 500mb is huge number although :thinking:

**Comment by matks** [comment]
> @matks @sarahdib when using "Import from your computer" functionality it handles max file upload size restrictions. In exception provided here I see that when uploading a theme it reached out of memory which is different thing. It consumed around 500mb but 134mb are allocated only. For such opeartion 500mb is huge number although 🤔

Got the answer: we have to consider some servers have a max_file_upload very low (like 10mb). Indeed that is a server config mistake but they must be displayed a nice error message in order to understand what is the issue rather than a scary exception message.

**Comment by tomas862** [comment]
> > @matks @sarahdib when using "Import from your computer" functionality it handles max file upload size restrictions. In exception provided here I see that when uploading a theme it reached out of memory which is different thing. It consumed around 500mb but 134mb are allocated only. For such opeartion 500mb is huge number although thinking
> 
> Got the answer: we have to consider some servers have a max_file_upload very low (like 10mb). Indeed that is a server config mistake but they must be displayed a nice error message in order to understand what is the issue rather than a scary exception message.

Test result one:
`post_max_size = 2M` and `upload_max_filesize = 2M` when I tried to upload theme which is `10mb`

![file_upload_err_1](https://user-images.githubusercontent.com/17051250/58545646-5b084d80-820c-11e9-9732-90f538febd6c.png)

test result two:

`post_max_size = 20M` and `upload_max_filesize = 2M`

![second_error_native](https://user-images.githubusercontent.com/17051250/58545760-9b67cb80-820c-11e9-8ff3-75f77c7d95f7.png)

this error is native symfony. I think its not translatable in our end but thats the only problem I saw regarding the testing.

something else happened and I think its quite specific use case for the theme :thinking: 

ofcourse I can try catch whole block with `OutOfMemoryException` and display translatable message instead - wdyt?

**Comment by matks** [comment]
> ofcourse I can try catch whole block with `OutOfMemoryException` and display translatable message instead - wdyt?

This is good 👍

**Comment by PierreRambaud** [comment]
I'm able to reproduce the memory allocation problem.
This is related to Symfony, which in debug mode try to add everything in a `ProfilerStorage` context.
You can turn it off in the symfony configuration:
```
framework:
    profiler:
        collect: false
```
Or increase your `memory_limit` in debug mode 
Or turn off debug mode.

The best way still increasing your `memory_limit` while running in debug mode.

**Comment by tomas862** [comment]
@PierreRambaud nice!
