### ISSUE TITLE
PRESTASHOP 1.7.5.2 COMBINATIONS IMAGES GENERATION BUG

### ISSUE THREAD

**Issue by MEGA911** [PrestaShop/PrestaShop#13918]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @MEGA911,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by MEGA911** [comment]
Describe the bug
In the Back-Office => In a product => In combination product => when i want to assign an other image for a combination => It's impossible => The miniature of the image product does not appear => I go to the console and i see ERROR 404 => I go to my FTP and i look for the first error "XXX-small_default.jpg" => This generation of this image does not appear

To Reproduce
Steps to reproduce the behavior:

In the Back-Office
    Go to 'PRODUCT ID40 LABEL TEST'
    Click on 'COMBINATIONS / DECLINAISONS'
    Scroll down to '.COMBINATIONS / DECLINAISONS and click on the pen to modify'
    See error at the end of the page we have some verticals lines whithout images to create the variation of the product

Screenshots
<img width="1920" alt="Capture d’écran 2019-05-22 à 14 30 28" src="https://user-images.githubusercontent.com/15946111/58174526-6c96a600-7c9e-11e9-88bb-7f1b6f5c45d8.png">

<img width="1920" alt="Capture d’écran 2019-05-22 à 14 30 42" src="https://user-images.githubusercontent.com/15946111/58174581-833cfd00-7c9e-11e9-889b-1cae8f5b0ce6.png">

<img width="1920" alt="Capture d’écran 2019-05-22 à 14 31 02" src="https://user-images.githubusercontent.com/15946111/58174595-89cb7480-7c9e-11e9-9e2f-3d4d8c037fcb.png">

<img width="1918" alt="Capture d’écran 2019-05-22 à 14 31 45" src="https://user-images.githubusercontent.com/15946111/58174622-98b22700-7c9e-11e9-9ee8-18eaea8b2959.png">
<img width="1920" alt="Capture d’écran 2019-05-22 à 14 31 52" src="https://user-images.githubusercontent.com/15946111/58174644-a5367f80-7c9e-11e9-961b-4746109ee4ff.png">

FTP SCREENSHOT
<img width="764" alt="Capture d’écran 2019-05-22 à 14 34 32" src="https://user-images.githubusercontent.com/15946111/58174715-d1520080-7c9e-11e9-9f82-d4e5e7c0fbfd.png">


Additionnal information
I have the same bug with Prestashop 1.7.5.1
PrestaShop version: 1.7.5.2 fresh install with theme VENTE + Data sample
https://www.templatemonster.com/prestashop-themes/vente-apparel-store-prestashop-theme-73782.html
PHP version: 7.1 ( I test 7.2 & 7.3 with the same bug)

**Comment by MEGA911** [comment]
Do you want an accès to the Back-Office ?

**Comment by khouloudbelguith** [comment]
@MEGA911, thanks to navigate to your BO => Design => Images Settings => Click on the `Regenerate thumbnails` button.
Thanks to check & feedback

**Comment by MEGA911** [comment]
Hello => I do that yesterday with no succes => But i try it now to retest

**Comment by khouloudbelguith** [comment]
@MEGA911, thanks!
waiting for your feedback.

**Comment by MEGA911** [comment]
I test it =>i clear the cache but => Doesn't work => The same bug
<img width="1704" alt="Capture d’écran 2019-05-22 à 14 44 36" src="https://user-images.githubusercontent.com/15946111/58175597-c6986b00-7ca0-11e9-8743-5b1f0f664919.png">
<img width="1703" alt="Capture d’écran 2019-05-22 à 14 47 48" src="https://user-images.githubusercontent.com/15946111/58175611-cd26e280-7ca0-11e9-9d61-2013b399e12c.png">
<img width="1911" alt="Capture d’écran 2019-05-22 à 14 48 10" src="https://user-images.githubusercontent.com/15946111/58175624-d3b55a00-7ca0-11e9-9311-ec9deb2144f1.png">

**Comment by khouloudbelguith** [comment]
@MEGA911, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by MEGA911** [comment]
Ok i active the debug mode

**Comment by MEGA911** [comment]
do you want an access to the Back-Office ?

**Comment by MEGA911** [comment]
How i give you the PHP error log ?

**Comment by khouloudbelguith** [comment]
@MEGA911, you can provide your credentials to access your shop by email.
This is a public space.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by MEGA911** [comment]
It s ok for you to connect ?

**Comment by MEGA911** [comment]
I send you the email to connect at the BO

**Comment by MEGA911** [comment]
For information I test an other install (the same configuration + Presta 1.7.5.2 + Theme) on an other server and domaine => I have the same bugs for combinations

**Comment by khouloudbelguith** [comment]
@MEGA911, Yes!

I will check & feedback.

**Comment by MEGA911** [comment]
perfect :)

**Comment by khouloudbelguith** [comment]
@MEGA911, it is OK now.
![image](https://user-images.githubusercontent.com/16067358/58179183-98665b80-7c9f-11e9-9a23-904166a79f19.png)

I enabled small_default for products, it shouldn't disabled
![image](https://user-images.githubusercontent.com/16067358/58179241-b207a300-7c9f-11e9-8cf2-895e63e4307b.png)

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by MEGA911** [comment]
Perfect !! You are the BEST !! I try to my other website and its works ! Thanks for all !! Have a nice day

**Comment by khouloudbelguith** [comment]
@MEGA911, thanks!

You are welcome!
