### ISSUE TITLE
Multistore Shop - Context Language

### ISSUE THREAD

**Issue by IvoRabush** [PrestaShop/PrestaShop#13928]
**Describe the bug**
**Context::getContext()->language** return always the language object from the settings of the **logged in employee** in the admin panel instead of the selected Shop Context

**To Reproduce**
1. Set up a multistore Shop
2. Configure exactly 1 language for each store
3. Doesn't matter on which Context is the user (shop context, context group or context all) The object **Context::getContext()->language** return always the language object from the settings of the **logged in employee** in the admin panel. 
Means if the user language setting is EN but he is on the context Shop FR, the **Context::getContext()->language** will always return EN

**Additionnal information**
PrestaShop version: 1.7.5.0 and higher
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @IvoRabush,

Thanks for your report.
Have you the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9682#issuecomment-415073999?

Thanks to check & feedback

**Comment by IvoRabush** [comment]
Hello @khouloudbelguith 

NO, It's not the same issue. in ticket #13928 it's about the FrontOffice and there the language is changing.

My problem is in the BackOffice (Admin Panel) and there the language NEVER changes, it's always the language in the user settings doesn't matter the Shop Context

**Comment by khouloudbelguith** [comment]
@IvoRabush, thanks for your feedback

could you please confirm these steps:
- Enable multistore context
- Create a new shop 
- Select French language to the first shop
- Select English language to the second shop
- The language of the employee is English
- The language by default of the first shop is English
- The language by default of the first shop is French
- the result of `Context::getContext()->language` => 
`Language Object ( [id] => 1 [name] => English (English) [iso_code] => en [locale] => en-US [language_code] => en-us `

If I change the default language of the first shop => the result of `Context::getContext()->language` will be changed.

Thanks!

**Comment by PierreRambaud** [comment]
I manage to reproduce, I'm on it!

**Comment by PierreRambaud** [comment]
Fixed in https://github.com/PrestaShop/ps_facetedsearch/pull/70
