### ISSUE TITLE
Multistore Shop - Context Errors

### ISSUE THREAD

**Issue by IvoRabush** [PrestaShop/PrestaShop#13927]
**Describe the bug**
When Multistore feature is active, Prestashop is loosing the Context when passing from custom PHP scripts / files in the modules.

**To Reproduce**
One of the many examples is the ps_facetedsearch core module
1. Go to Modules / Module Manager / ps_facetedsearch
2. Click on 'Build Attribute Index'
3. This button is calling the php file **ps_facetedsearch-attribute-indexer.php** which calls the method **indexAttribute** => here Prestashop looses the Context
4. Inside the mthod **indexAttribute** is called **Shop::addSqlAssociation('product_attribute', 'pa')** which ALWAYS return the association by Shop ID. It return **always and exactly the first active Shop ID doesn't matter the context (shop, shop group or all shops)**

**What happens**
In the example above, the following happens when trying to rebuild the attribute index:
1. Method **indexAttribute** is called without $id_product parameter
2. It goes into "if (is_null($id_product))" and **truncates** the DB table layered_product_attribute
3. The insert query calls the method **Shop::addSqlAssociation('product_attribute', 'pa')** which returns the association by **id_shop = 1** (in my case the first active shop is id_shop = 1)
4. rebuilds the attribute index for **Shop ID 1 ONLY** after **truncate**

This is the same for every other php file that is not extending a Prestashop Core class like **Module**. Which means that ajax requests, cron jobs and etc are not working properly.
This gives a lot of errors when getting Context::getContext(), Shop::getContext() :
* Object shop return always the first active shop
* Object employee returns a php fatal error.

P.S I didn't test it on none multistore setup, but I'm sure it's the same problem

**Additionnal information**
PrestaShop version: 1.7.5.0 and higher
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay,
I think it's fixed here: https://github.com/PrestaShop/ps_facetedsearch/pull/70

**Comment by PierreRambaud** [comment]
@IvoRabush FYI, we will release a new version next week!
