### ISSUE TITLE
WidgetInterface removed from ps_facatedsearch 3.0

### ISSUE THREAD

**Issue by iqit-commerce** [PrestaShop/PrestaShop#13920]
**Describe the bug**
In latest version there is widgeting option removed from facatedsearch which is quiet big issue for theme developers and people who want to customize display of this module

**To Reproduce**
Try to call ps_facatedsearch using widget
https://devdocs.prestashop.com/1.7/modules/concepts/widgets/
{widget name='<module_name>'}

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
ps_facatedsearch: 3.0/3.1
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @iqit-commerce,

I tried to add {widget name="ps_facetedsearch"} in a template
But in the FO, I have this exception
![image](https://user-images.githubusercontent.com/16067358/58180383-e67c5e80-7ca1-11e9-9fda-6d246b0b66bc.png)
Same issue with ps_facetedsearch v3.0.0 & v2.2.0

Thanks to check & feedback

**Comment by mrabsinthe** [comment]
@khouloudbelguith are you able to "Rebuild entire price index"? Because I get "Price indexing failed". Using ps_facetedsearch v3.0.0 and PS 1.7.5.1. Same with ps_facetedsearch v3.0.1 and v2.2.1

**Comment by khouloudbelguith** [comment]
@iqit-commerce, with PS1.7.6.0beta1, it is OK
https://drive.google.com/file/d/1dA4oKnxLKBYx2Sd6WXZoJwqZHZH9i2Zp/view
with PS1.7.5.2 & ps_facetedsearchv3.0.1 => OK
https://drive.google.com/file/d/1QZys24VI9dZNbNtbfkvmfQy4OBciScHe/view
Thanks!

**Comment by iqit-commerce** [comment]
@khouloudbelguith 
"I tried to add {widget name="ps_facetedsearch"} in a template
But in the FO, I have this exception" 

Exatly, I'm talking about this exception, ps facatedsearch doease not include WidgedInterface anymore and it is not possible to use it as widget


Rebuild price is not related to the issue I report

**Comment by ZeroLe** [comment]
Hi,

I have an error when I install the "ps_facetedsearch" module version 3.0.1.
<img width="535" alt="ps_facetedsearch_error" src="https://user-images.githubusercontent.com/18438590/58232459-bac1ad00-7d63-11e9-9664-801aa2bab1f9.png">

Pleae help me. Thanks!

**Comment by grabelle** [comment]
Hi all,
For information with v 3.0.1 if you don't check "Afficher les produits des sous catégories" (display sub categories products) ... the faceted search left block is not visible

**Comment by khouloudbelguith** [comment]
Hi @iqit-commerce,

I have this exception when I used ps_facetedsearch v3.0.0 & v2.2.0 =>so it is not a regression for the latest version of the module.
ping @PierreRambaud what do you think? the ps_factedsearch doesn't include WidgetInterface?

@ZeroLe, if you cloned the module from GitHub, you need to run `composer install`
I installed this module & it is OK.
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3211023/ps_facetedsearch.zip)

@grabelle, I did not manage to reproduce your issue with PS1.7.6.0beta1 & ps_factedsearch v3.0.1.
https://drive.google.com/file/d/1ppnt2P75DWP-apjViK79_dbEd-aPFDzV/view

Thanks!

**Comment by ZeroLe** [comment]
@khouloudbelguith 
I can not run "composer install"
Where can I download module package?
Thanks!

**Comment by khouloudbelguith** [comment]
@ZeroLe, thanks to check with this module
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3211125/ps_facetedsearch.zip)
Thanks!

**Comment by ZeroLe** [comment]
@khouloudbelguith 
It works.
Thank you very much!

**Comment by khouloudbelguith** [comment]
@ZeroLe, thanks!
You are welcome!

**Comment by PierreRambaud** [comment]
@khouloudbelguith yes this module doesn't include the `WidgetInterface` anymore, it has many limitations and issues and wasn't used in the module (always depending on hooks)

**Comment by khouloudbelguith** [comment]
@PierreRambaud, thanks for your feedback.
I’ll add this issue to the debug roadmap.
Thanks!

**Comment by marcoaguglia** [comment]
I encountered this bug. I tried to install version 2.1.1 for the moment but I also have problems with "composer install". Can anyone provide me the zip?

**Comment by iqit-commerce** [comment]
@PierreRambaud Earlier version of facated search had included WidgetInterface, and widgeting system was used for this module by theme developers without any problems. It should be bring back, I have plenty customers who now have this error becouse of that and i belive other theme developers also used wdiget system with this module. IT was also very usefull in custom layouts

**Comment by PierreRambaud** [comment]
@iqit-commerce are you able to test this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/66 and tell me if everything's ok?

**Comment by AdriCruz** [comment]
I get an error when installing it, I have to delete the previous version, is there any way to not delete the templates already made? do you know where the file is stored and then incorporate it? I would not like to start again ...

**Comment by iqit-commerce** [comment]
@PierreRambaud Yes it works great! Well done!

**Comment by PierreRambaud** [comment]
@iqit-commerce Thank again for your feedback, a new version is coming!

**Comment by AdriCruz** [comment]
It takes a long time to install and alfinal gives error, does it happen to someone else?

**Comment by khouloudbelguith** [comment]
@AdriCruz, I tried to make an upgrade of the ps_factedsearch & it is OK.
I attached a video record
https://drive.google.com/file/d/1v7izIrh4ZPrpqvoBuxp8Y20E5LAWvASL/view
Thanks!

**Comment by PierreRambaud** [comment]
I've an idea about what's happening. This is due to the huge amount of products or something similar.
i'm on a fix :)

**Comment by khouloudbelguith** [comment]
@PierreRambaud, it could be a huge amount of categories?
THanks!

**Comment by AdriCruz** [comment]
Yes, I've tried it that way but it's still failing, I think it's because of the large number of products ...

**Comment by grabelle** [comment]
One installed, you also have a lot of notice generated 
PHP Notice:  Undefined offset: 1 in 
/modules/ps_facetedsearch/src/Filters/Block.php on line 744,

**Comment by PierreRambaud** [comment]
@grabelle Let me now if this fix is working for you https://github.com/PrestaShop/ps_facetedsearch/pull/69/commits/0593b8013fbfd2ce8644552a45bbca1181eb7d40 ?

**Comment by ZeroLe** [comment]
Hi module developers,

In new version (3.0.x), we don't have the "product_attribute_minimal_quantity" parameter in the product result. We have this parameter in PrestaShop 1.7.5.x version.
I think this is a important parameter, so please add it to the product result.
Thanks!

Regards,

P/S: I see new version has many errors, I think we should stop informing customers of the new version update until it's stable

**Comment by PierreRambaud** [comment]
@ZeroLe FYI, the new version still has errors, but really less than the previous version 😉 
We are working on it to improve this module :)

**Comment by ZeroLe** [comment]
@PierreRambaud 
Thank you for your reply!

I'm a template developer on Addons Marketplace.
A lot of my customers have updated this module, and they see the error, and they think this is my theme's error, they are complaining. What should I do?

Please do not allow customers to continue to update the module version 3.0.x
Thank you very much.

**Comment by PierreRambaud** [comment]
The latest 3.0.2 already fixed this issue.

**Comment by grabelle** [comment]
Hi All, 
Any chance to have a module using elasticsearch in the near futur ? It would be much faster, probably easier to manage ... what do you think ?

Anyway thanks for you work !

**Comment by grabelle** [comment]
Sorry to disturb, but how to override the file template modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl

where shoud I put the facets.tpl in my theme files ?

**Comment by PierreRambaud** [comment]
@grabelle We create interfaces to do it (for elastic), but not planned for the moment.
For override module: https://devdocs.prestashop.com/1.7/themes/reference/overriding-modules/

**Comment by Matt75** [comment]
@ZeroLe WidgetInterface is really important for theme developers. Lot a complaining from agencies about this BC too. New version restore it, so new module update should not be a problem anymore 👍

Thanks of @PierreRambaud for this huge refactoring work 🎉

**Comment by PierreRambaud** [comment]
Done and release
