### ISSUE TITLE
Some attribute values are not visible in product edit page

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#13924]
This active attribute:
https://www.dropbox.com/s/0trbvs40veag4er/1.png?dl=0
is not visible while editing the product:
https://www.dropbox.com/s/6hdk70a239ya2b5/Screenshot%202019-05-22%2018.15.14.png?dl=0
The reason is, that the shop has deleted lang ID1 since 1.6 version (and ID2 is now default language) and this part is hardcoded to 1:
https://www.dropbox.com/s/yr94vqp3xfv952c/2.png?dl=0

The issue and temporary fix are also described here:
https://www.prestashop.com/forums/topic/600370-ps-1706-product-attributes-not-showing-in-admin-product-page/?tab=comments#comment-2532104

**Comment by web-plus** [comment]
... I see it's modified to dynamic values in dev version so you can probably close this :-)

**Comment by khouloudbelguith** [comment]
Hi @web-plus,

Thanks for your report.
I close the issue, feel free to open a new one when needed.
Thanks!
