### ISSUE TITLE
No documentation for php unrelated api

### ISSUE THREAD

**Issue by nhh** [PrestaShop/PrestaShop#13922]
Hi prestashop team,

i am currently creating products via the prestashop webservice.

Can someone describe how i cant assign a quantity to a fresh created product?

Or even better, how can i create a product with a predefined amount of stock quantity?

Please do not provide php code. I need a proper REST/HTTP Documentation.

This is the xml i am sending to prestashop atm:

```xml
<prestashop>
    <product>
        <id/>
        <id_supplier/>
        <type/>
        <id_manufacturer/>
        <advanced_stock_management>1</advanced_stock_management>
        <low_stock_alert>0</low_stock_alert>
        <id_category_default/>
        <id_shop_default/>
        <id_tax_rules_group/>
        <on_sale/>
        <online_only/>
        <ean13/>
        <upc/>
        <type>1</type>
        <ecotax/>
        <minimal_quantity>1</minimal_quantity>
        <available_for_order>1</available_for_order>
        <price>1999</price>
        <wholesale_price>1999</wholesale_price>
        <reference/>
        <active>1</active>
        <redirect_type/>
        <condition/>
        <show_price/>
        <name>
            <language id=\"1\">AHT Wandkühlregal Medium RDM 10-125</language>
        </name>
        <description>
            <language id=\"1\">name</language>
        </description>
        <link_rewrite>aht-wandkhlregal-medium-rdm-10-125</link_rewrite>
        <associations>
            <categories>
                <category>
                    <id>10</id>
                </category>
            </categories>
            <stock_availables/>
        </associations>
    </product>
</prestashop>
```

Thanks in advance!

**Comment by khouloudbelguith** [comment]
Hi @nhh,

We are unfortunately aware of that, however, we have a huge pile of tasks to do to improve the project and make it evolve in the right way (as I'm writing now, there is 999 issues, so as you can see we are quite busy ).

However, this is an opensource project so please consider contributing to the project wink you have a good knowledge of what this documentation should contain and look like. Would you write down your suggestions?

Now that I'm thinking of this, probably https://github.com/PrestaShop/docs is better suited for this.


>Can someone describe how i cant assign a quantity to a fresh created product

You need to add the quantity in your xml sent
![image](https://user-images.githubusercontent.com/16067358/58182002-bb473e80-7ca4-11e9-8ff9-97b58b75f2ec.png)

Thanks!

**Comment by nhh** [comment]
Hi @khouloudbelguith,

unfortunately your tip did not help :(

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n
<prestashop
    xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n
    <errors>\n
        <error>\n
            <code>
                <![CDATA[93]]>
            </code>\n
            <message>
                <![CDATA[parameter \"quantity\" not writable. Please remove this attribute of this XML]]>
            </message>\n
        </error>\n
    </errors>\n
</prestashop>
```

Thank you for your fast response!

Greetings
Niklas

**Comment by khouloudbelguith** [comment]
@nhh, thanks for your feedback.
In fact, to set the amount of the product must be done separately

Thanks to check this function to edit stock via WS

```
function set_product_quantity( $product, $quantity ){

  try{

    $webservice_client = new PrestaShopWebservice('http://localhost/ps', 'Key', true);

    foreach( $product->product->associations->stock_availables->stock_available as $item ){

      $xml = $webservice_client->get( array('url' => 'http://localhost/ps/api/stock_availables?schema=blank') );
      $resources = $xml->children()->children();
      $resources->id = $item->id;
      $resources->id_product  = $product->product->id;
      $resources->quantity = $quantity;
      $resources->id_shop = 1;
      $resources->out_of_stock = 1;
      $resources->depends_on_stock = 0;
      $resources->id_product_attribute = $item->id_product_attribute;

      $xml = $webservice_client->edit(array(
        'resource'  =>  'stock_availables',
        'putXml'    =>  $xml->asXML(),
        'id'        =>  $item->id
      ));

    }

  }catch( PrestaShopWebserviceException $e ){
    die($e);
  }

}
```
Thanks to check & feedback

**Comment by crishnakh** [comment]
Hi @nhh maybe you should work with the **stock_availables** node

- **First:** Insert the new product without stock and get the **ID** generated
- **Second:** Get the **id_stock_available** associated to the product ID
- **Third:** Update the **quantity** value of this node with the id_stock_available.

**Comment by nhh** [comment]
Hi @crishnakh, hi @khouloudbelguith 

thank you you can close this issue.

**Comment by khouloudbelguith** [comment]
@nhh, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by AyoubAchour** [comment]
when i call the function i get this error : 
  "Trying to get property 'product' of non-object"
any suggestions ?
