### ISSUE TITLE
Corrupted utf8 characters in mails

### ISSUE THREAD

**Issue by jankratochvil** [PrestaShop/PrestaShop#13937]
I got a mail from https://e-filson.cz which is a Czech website and in Czech we use diacritic characters outside of 7bit us-ascii.
And these diacritic characters are corrupted.
received: `VaE!e objednC!vka byla odeslC!na`
expected: `Vaše objednávka byla odeslána`

I ordered a product and I got such mail.
The mail is assembled incorrectly:

```
Content-Type: multipart/related;
 boundary="_=_swift-15330876875ce668a5d892b4.47383362_=_"
Content-Transfer-Encoding: 7bit
...
--_=_swift-15330876875ce668a5d892b4.47383362_=_
Content-Type: multipart/alternative;
 boundary="_=_swift-14778117705ce668a5d895e8.01908557_=_"
Content-Transfer-Encoding: 7bit
--_=_swift-14778117705ce668a5d895e8.01908557_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
...
VaE!e objednC!vka byla odeslC!na 
```

In MIME you cannot use 8bit content without a header:
```
Content-Transfer-Encoding: quoted-printable
```

PrestaShop version: dunno, check https://e-filson.cz
PHP version: dunno, check https://e-filson.cz

**Comment by khouloudbelguith** [comment]
Hi @jankratochvil,

I did not manage to reproduce the issue with PS1.7.6.0beta1.
I attached a video record
https://drive.google.com/file/d/13IsbEUXOw7npPTuKy7kEUQkfjqU-Ybg9/view
Thanks to check & feedback

**Comment by jankratochvil** [comment]
This is the mail I received after making an order:
[mail.zip](https://github.com/PrestaShop/PrestaShop/files/3211724/mail.zip)

**Comment by jankratochvil** [comment]
That it works with some mail servers and mail clients (and other parts of mail infrastructure) does not mean it is correctly sent by PrestaShop. What matters is if the PrestaShop mails are compliant with RFCs (internet standards). And they are not. And it is incompatible with some of software on my side (Postfix, Sendmail, fetchmail, procmail and some others) and the software is correct as if the mail was standards compliant it would be processed correctly.
One cannot use 8-bit characters inside: `Content-Transfer-Encoding: 7bit`

**Comment by khouloudbelguith** [comment]
@jankratochvil, thanks for your feedback.
I tried with Gmail & Zimbra => OK.
We'll first try to reproduce it with Sendmail and we'll come back to you if we need more information.

Thanks!

**Comment by jankratochvil** [comment]
Reproducibility really does not matter.
[RFC 2045](https://www.rfc-editor.org/rfc/rfc2045.txt) section 6.1:
```
An encoding type of 7BIT requires that the body
is already in a 7bit mail-ready representation.
```
And section 6.2
```
Labelling unencoded data containing 8bit characters as "7bit" is not
allowed
```
which is obviously violated by PrestaShop, dot.

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi @jankratochvil ,

We update our dependencies, could you tell us if with the latest version everything is ok?

Kind regards

**Comment by jankratochvil** [comment]
I do not know which version https://www.e-filson.cz is running and some detection tools I found could not find it out. If you are not going to investigate/fix it yourself and you are just waiting until it gets fixed on its own then this bugreport is pointless.

**Comment by PierreRambaud** [comment]
> I do not know which version https://www.e-filson.cz is running and some detection tools I found could not find it out. If you are not going to investigate/fix it yourself and you are just waiting until it gets fixed on its own then this bugreport is pointless.

We will not be able to investigate on the website we don't own.
If you're not the owner of this website and can't provide us more information to be able to reproduce, we will close this issue.
Feel free to reopen if you can provide us more information :)
