### ISSUE TITLE
Controller AdminModulesPositions not found

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13935]
**Describe the bug**
Controller AdminModulesPositions not found

**To Reproduce**
1. Go to Design > Positions
2. Click on Transplant a module
3. See error

**It was working on the 1.7.6.0 beta**

**Screenshots**
![capture d'écran_1592](https://user-images.githubusercontent.com/13449658/58240875-2861df00-7d4c-11e9-9c6f-31631857b686.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
We did a mistake in https://github.com/PrestaShop/PrestaShop/pull/13850 which caused this. PR to fix it will come soon
