### ISSUE TITLE
Acces denied when i'm in my admin panel

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#13936]
**Is your feature request related to a problem? Please describe.**
Hi, I have actualized to the last version, and all is OK  but when i  access to my admin panel, i can't see my dashboard and more elements as products, categories, modules...
because the access is denied, i dont understand why. i add the picture 
![imagen](https://user-images.githubusercontent.com/14195668/58241646-ad99c380-7d4d-11e9-9163-2b613ee3b29e.png)
the texts are in spanish, the texts are: **You do not have permission to configure this module.** and **access denied**
please i need your help!

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

To fix this issue you need to replace 'ps_access' table in DB with the one from clean PS1.7 installation.

Thanks to check & feedback.

**Comment by juank2808** [comment]
i don't undestand you, do i have to delete table 'ps_access?, or do i have to make clean installation?

**Comment by khouloudbelguith** [comment]
@juank2808, 

You can, for example, install PrestaShop separately, copy & paste the table ps_access to your shop.
Or you can follow this solution in this comment to solve your issue https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961
Before any modification, you can make a backup of your old database.
Thanks to check & feedback

**Comment by juank2808** [comment]
ok I will try, but i wont close the issue until I solve this

**Comment by khouloudbelguith** [comment]
@juank2808, thanks!

Waiting for your feedback.

**Comment by juank2808** [comment]
SOLVED! i hace copy al data from 'ps_acces' and is OK thanks now i close the issue

**Comment by khouloudbelguith** [comment]
@juank2808, thanks for your feedback.
Feel free to open a new one when needed.

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/autoupgrade/issues/100
