### ISSUE TITLE
Currency not display properly with language whos are using RTL

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13934]
**Describe the bug**
Currency are not displayed properly with languages who are using RTL

**To Reproduce**
1. Go to Localisation and add arabic language
2. Add a currency with at least two characters (like USD) 
3. Go to front and see the error

**Screenshots**
![Capture d’écran 2019-05-23 à 10 50 41](https://user-images.githubusercontent.com/3034677/58241405-36fcc600-7d4d-11e9-843f-dcc4d4332729.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by colinegin** [comment]
@MatShir wdyt of this issue ?

**Comment by colinegin** [comment]
@jolelievre do you know if there is anything that should be done on our side or the CLDR should handle it ?

**Comment by jolelievre** [comment]
Mmm, it seems it's only for discounted prices that there is an error Probably a problem on the front, I'm not sure it's directly related to CLDR it needs more checking I'd say something is messed up with the special RTL character This will have to be checked with customization as well

**Comment by jolelievre** [comment]
@colinegin Is it in 177 scope?

**Comment by colinegin** [comment]
no, there's no emergency :)
