### ISSUE TITLE
the upgrade to ps_facetedsearch 3.0.1 from 2.2.1 doesn't work

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#13938]
Hi
I've tried to upgrade the ps_facetedsearch module from the version 2.2.1 to 3.0.1 but in all cases on some sites I get errors, after many tests in some case I've solved it but in others no
in all cases there are errors in the installation phase that make errors in the db
can you fix it please?

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/58244969-fe141f80-7d53-11e9-9784-da354a4ecd6f.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

This exception is displayed when installing the ps_facetedsearch module v3.0.1?
If yes, after cloning this module from GitHub, you need to run  `composer install` before installing it.
Thanks to check & feedback

**Comment by Maofree** [comment]
ok

**Comment by Maofree** [comment]
however from the backoffice I get many errors
on a site I try to reinstall the 2.2.1
the other is not possible

**Comment by khouloudbelguith** [comment]
@maofree, thanks!
Waiting for your feedback.

**Comment by Maofree** [comment]
can I send you the access to the back-office?

**Comment by khouloudbelguith** [comment]
@maofree, yes!

**Comment by khouloudbelguith** [comment]
@maofree, ps_factedsearch is installed in your shop
![image](https://user-images.githubusercontent.com/16067358/58247798-66620180-7d52-11e9-90ef-c9f07a3ce244.png)

Thanks to check & feedback

**Comment by Maofree** [comment]
look at the error in the category page

**Comment by Maofree** [comment]
![1](https://user-images.githubusercontent.com/653230/58248073-73cfb980-7d5b-11e9-89dc-f43d87f6ae31.png)
![2](https://user-images.githubusercontent.com/653230/58248075-73cfb980-7d5b-11e9-8541-e920a499185b.png)

some tables are missing in the db

I try to add them in the db

![3](https://user-images.githubusercontent.com/653230/58248248-f0629800-7d5b-11e9-9eb2-5704e9faad52.png)

these are missing, probably there is an error in the installation phase

**Comment by khouloudbelguith** [comment]
@maofree, I will check & feedback.
Thanks!

**Comment by Maofree** [comment]
the site is in production so leaving it with this error is a problem, however I let you try

**Comment by khouloudbelguith** [comment]
@maofree, I just uninstalled the module in your shop.
The issue disappears.
But, only in your shop, that I have an error during the install of the module.
In my case, with PS1.7.5.2 & the same zip file => module installed successfully

Thanks!

**Comment by Maofree** [comment]
the problem is present in other shop, at this moment I don't upgrade their module to avoid this type of error

**Comment by Maofree** [comment]
I get this error when I try to install it from the back-office

Eccezione lanciata dal modulo ps_facetedsearch su install. Notice: Undefined offset: 0

**Comment by Maofree** [comment]
problem fixed
before I install the module with that error, then I upload the missing table on db got from another db
then updated its data in the donfiguration page
however there is some errors in the installation phase

**Comment by khouloudbelguith** [comment]
@maofree, you have another problem during the installation different from this

`Notice: Undefined offset: 0`

Thanks!

**Comment by Maofree** [comment]
hi
yes the first error was due from the missing composer install

**Comment by khouloudbelguith** [comment]
@maofree, so, can I close the issue?
Thanks!

**Comment by Maofree** [comment]
some errors are present to upgrade from 2.2.1 to 3.0.1
all sites has  problems to upgrade, in some modes I can fix it like before
I need to upgrade other 4 sites so I can test it again and I'll check the code that gives errors
at this moment wait

can you test it on a big site from 2.2.1? default prestashop demo site is too little

**Comment by khouloudbelguith** [comment]
@maofree, it is OK in my case.
I attached a video record
https://drive.google.com/file/d/1v7izIrh4ZPrpqvoBuxp8Y20E5LAWvASL/view
Thanks!

**Comment by grabelle** [comment]
In fact it is very very slow ... I also got the error (error 500 ... need more memory)
With a limit to 1024Mb it is OK

**Comment by khouloudbelguith** [comment]
@grabelle, error 500? in the configure page of the ps_facetedsearch module? or a different issue?
Thanks!

**Comment by grabelle** [comment]
to upgrade from v2 to v3 of the module

**Comment by khouloudbelguith** [comment]
@grabelle, could you please provide me the exception displayed in your case?
Thanks!

**Comment by grabelle** [comment]
Sorry I don't have the log anymore ... but like "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted" ... 
On the frontend it just tell that an undefined error occured

**Comment by khouloudbelguith** [comment]
@grabelle, do you have a large number of products or categories?
Thanks!

**Comment by grabelle** [comment]
A

> @grabelle, do you have a large number of products or categories?
> Thanks!

About 1100 categories and 3500 prod

**Comment by khouloudbelguith** [comment]
@grabelle, our developer is working on it to fix it
https://github.com/PrestaShop/PrestaShop/issues/13920#issuecomment-495242382
Thanks!

**Comment by Luxurdk** [comment]
Can somebody help me with this issue, all my category pages are white.

**Comment by Maofree** [comment]
Hi @Luxurdk 
you have white pages because there is an error, to see it go in
advanced parameters - performance
and active the debug mode
probably you will get this db error

![11](https://user-images.githubusercontent.com/653230/58310590-404a6900-7e07-11e9-8aa7-1133710bd8f6.png)

the module has problems, but it does not behave in the same way
to solve this problem I unistall the module and remove its folder from the site, then install it again, configure it and push on the rebuild buttons

bye

**Comment by Luxurdk** [comment]
> 
> 
> Hi @Luxurdk
> you have white pages because there is an error, to see it go in
> advanced parameters - performance
> and active the debug mode
> probably you will get this db error
> 
> ![11](https://user-images.githubusercontent.com/653230/58310590-404a6900-7e07-11e9-8aa7-1133710bd8f6.png)
> 
> the module has problems, but it does not behave in the same way
> to solve this problem I unistall the module and remove its folder from the site, then install it again, configure it and push on the rebuild buttons
> 
> bye

Okay thanks. But where can I download the module V2.2 because thats the one that works.

**Comment by Maofree** [comment]
I installed the 3.0.1 version
at 90% it should work

**Comment by PierreRambaud** [comment]
We released a 3.0.2 which this the upgrade problem is there is many products / categories.

**Comment by Luxurdk** [comment]
So if I press update now it will update to 3.0.2 i my backend, or should I do something els.?
I took a backup and went back to V2.2

**Comment by PierreRambaud** [comment]
Nothing more, after an upgrade you must reindex all products / attributes.

**Comment by Luxurdk** [comment]
It dosen't say update i backend.
Please help how to update it.
![2019-05-24 10_44_01-Moduler • Luxur](https://user-images.githubusercontent.com/50981231/58314991-f0709f80-7e10-11e9-8966-a397f030fbb7.png)

**Comment by PierreRambaud** [comment]
Weird :thinking: you can download a zip here: https://github.com/PrestaShop/ps_facetedsearch/releases

**Comment by khouloudbelguith** [comment]
@PierreRambaud, in my case also.
With PS1.7.6.0beta1 => when ps_factedseachv = 3.0.1 => I don't have upgrade button 
when ps_factedsearch = 2.2.0 => upgrade button, is well displayed

Thanks!

**Comment by PrestaUser** [comment]
After the update to v3.0.2, I still have the same problem. What to do?

**Comment by PierreRambaud** [comment]
@PrestaEdit What's the problem exactly? The HookDispatcher issue? Database issue?

**Comment by PrestaUser** [comment]
Don't know. Doesnt show products and filters. Same problem as v3.0.1

**Comment by Maofree** [comment]
@PrestaUser 
pass to them the access of your site, it would be easier for them to check the problems and the configuration

**Comment by BobvanderValk** [comment]
I ran into problems yesterday during update to 3.0.1.  The update didn't want to work.  My web site responded very very slow till it didn't work anymore.  One.com checked the problem and warned me that ps_facetedsearch.php was sending a lot of php requests.  It took many minutes for the server to handle them all and that caused the site to block.  Today I tried the upgrade to 3.0.1 again and even I got a message that it didn't work, I checked with ftp and 3.0.1 replaced the old one.  Slow site again instantly and when I wanted to rename ps_facetedsearch.php I got the HTTP 500 error.  I hope this info helps.  It is PS 1.7.5.1 with 3500 products and 250 categories.  I will do a fresh install of 1.7.5.2 now to see if that works.

**Comment by PrestaUser** [comment]
@BobvanderValk I also run on 1.7.5.1. What is your site url? I think we have the same problem here.

**Comment by BobvanderValk** [comment]
> @BobvanderValk I also run on 1.7.5.1. What is your site url? I think we have the same problem here.

Please follow instructions of khouloudbelguith in #13913 .  This was the solution for me too!
It meanse deleting the cache as described (it was giga huge in my case) and download and replace the ps_facetedsearch folder under modules.  This folder was also mega big in my case because of the upgrade.  After these steps my (test) site works again.

**Comment by Klemart3D** [comment]
Hi,

The module [ps_facetedsearch v3.0.0](https://github.com/PrestaShop/ps_facetedsearch/tree/v3.0.0) officially released 14 days ago (21/04/19). So, I upgraded module from admin.

But in PrestShop [composer.json file](https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json#L60), it still remain on v2.x.x. So when I'm doing a `composer update`, module is downgraded to v2.2.1:

![v2.2.1 after composer update](https://user-images.githubusercontent.com/7419525/58940968-197f2180-877b-11e9-8def-96de1c9b9cf4.png)


Now I have errors mentioned above (or some admin pages likes _modules_ or _products_ are not loaded) and when I'm checking admin module version it remains "v3.0.2" and when I'm checking in database "v.3.02" still associated to this module:

![Still v3.0.2 on BO](https://user-images.githubusercontent.com/7419525/58941173-85fa2080-877b-11e9-8e44-0d51ef035c60.png)
![Still v3.0.2 on DB](https://user-images.githubusercontent.com/7419525/58941215-97432d00-877b-11e9-8747-d9d781293e83.png)

So, what is the right way to update a module? Do have we to change the `composer.json` with last module version or have we to wait?

EDIT 05/06: I tried to replace `"prestashop/ps_facetedsearch": "^2"` by `"prestashop/ps_facetedsearch": "^3"` and do a `composer update` but this is adding some wrong permissions to files, by sample:

> ➜  httpdocs git:(develop) ✗ git diff modules/ps_facetedsearch/ps_facetedsearch.php
> diff --git i/modules/ps_facetedsearch/ps_facetedsearch.php w/modules/ps_facetedsearch/ps_facetedsearch.php
> old mode 100644
> new mode 100755

**Comment by PierreRambaud** [comment]
We will update the composer file in few days

**Comment by khouloudbelguith** [comment]
HI @Klemart3D,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14197 about updating the composer file.
@maofree, we released in few days a new version ps_facetedsearch v3.0.4
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.0.4

I close this issue, feel free to open a new one when needed.

Thanks!

**Comment by ibrahimfsasmaz** [comment]
I have the same problem with exact same errors

I upgraded prestashop 1.7.5.1 to 1.7.6.2 and has several broken links...
faceted search does not upgrade with our without clean cache even manual installation does not work..

I do not know how to fix the table and fields missing DB after 1-click upgrade...

Need help pls

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/16795

Thanks!
