### ISSUE TITLE
i can't open my shop!

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#13940]
**Is your feature request related to a problem? Please describe.**
Hi again i have updated to the last version, and i had a little problem with  a Database in the table 'ps_access', now, when  i wanna open the shop i can't, error 500, ok ,I enter into mode debug and 
i try  again to open the shop and this appears:
![imagen](https://user-images.githubusercontent.com/14195668/58248563-b940b680-7d5c-11e9-8fd4-8ca0ceff8321.png)
What can  I do?

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

Thanks to try with this module https://github.com/Matt75/fixconfigurationlang and feedback.

Thanks!

**Comment by juank2808** [comment]
Ok this SOLVED! thanks

**Comment by khouloudbelguith** [comment]
@juank2808, Thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
