### ISSUE TITLE
Upgrade from 1.6.1.24 to 1.7.5.2 500 Internal Server Error

### ISSUE THREAD

**Issue by GrossOutD** [PrestaShop/PrestaShop#13958]
**Describe the bug**
After upgrading 1.6 to 1.7 i got the following error in autoupgrade

[INTERNAL] /****/src/PrestaShopBundle/Install/LanguageList.php line 100 - Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load 

class "PrestashopInstallerException" from the global namespace. Did you forget a "use" statement? #0 

/****/*****/autoupgrade/latest/install/upgrade/php/migrate_tabs_17.php(57): PrestaShopBundle\Install\LanguageList->setLanguage('gb') #1 [internal 

function]: migrate_tabs_17() #2 /****/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(392): call_user_func_array('migrate_tabs_17', 

Array) #3 /****/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(360): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader

\CoreUpgrader->runPhpQuery('1.7.0.0', '/* PHP:migrate_...') #4 /****/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(284): PrestaShop

\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.0.0', '/* PHP:migrate_...') #5 

/****/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader

\CoreUpgrader->upgradeDb('1.6.1.24') #6 /****/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(101): PrestaShop\Module

\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.6.1.24') #7 /****/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php

(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /****/autoupgrade/ajax-upgradetab.php(53): 

PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

Every time i now visit the site i get the following error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Not sure how to fix

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @HAF1ZUR,

What is the exact version of the module 1-click upgrade did you used?
Because this issue seems to be fixed in the V4.2.0 with this PR: https://github.com/PrestaShop/autoupgrade/pull/163, it fixes this issue: https://github.com/PrestaShop/autoupgrade/issues/158 which is similar to yours.
THanks!

**Comment by GrossOutD** [comment]
Hi

I updated autoupgrade to 4.8 before doing the update

**Comment by GrossOutD** [comment]
I enabled debug mode manually and the following is now shown

![prestashop error](https://user-images.githubusercontent.com/46545164/58322655-201fa780-7e11-11e9-95c1-8a30a4829d55.png)

**Comment by GrossOutD** [comment]
I have switched back to php 7.2 after experimenting and see the following:

![1](https://user-images.githubusercontent.com/46545164/58322908-eac78980-7e11-11e9-8d73-a9bb6ee3ac29.png)
![2](https://user-images.githubusercontent.com/46545164/58322916-edc27a00-7e11-11e9-8cef-e476ddaaf7e0.png)
![3](https://user-images.githubusercontent.com/46545164/58322919-f024d400-7e11-11e9-8ea2-583d730ee628.png)

I have also noticed the PS_ACCESS is blank with nothing in the database

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, could you please try to replace 'ps_access' table in DB with the one from clean PS1.7 installation

Thanks!

**Comment by GrossOutD** [comment]
Added PS_ACCESS from a clean install and i get slightly different results

![2](https://user-images.githubusercontent.com/46545164/58324968-f3bb5980-7e17-11e9-8d84-1058d2dfc805.png)
![3](https://user-images.githubusercontent.com/46545164/58324970-f5851d00-7e17-11e9-8e6f-4348aeeec878.png)

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

**Comment by GrossOutD** [comment]
I imported clean version of PS_TABS and PS_MODULES this gave me access to the back office but with a bunch of errors

Currently rolling back to working 1.6.1.24, will try again tomorrow

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, Thanks!

Waiting for your feedback.

**Comment by rsysadmin-com** [comment]
Hi all! any updates on this? I was about to use the 1-click-upgrade, version 4.8.0, to bump one PS site of a customer from 1.6.1.20 to 1.7.5.2. Currently running on PHP 5.6 but I can change the version up to 7.3 if recommended,

Thanks in advance!

**Comment by khouloudbelguith** [comment]
Hi @rsysadmin-com,

I'm waiting for the author on this issue.
No, you don't need to upgrade to PHP7.3, PrestaShop 1.7.5 is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Thanks!

**Comment by GrossOutD** [comment]
I have not had the chance to go through with this yet, will have an update later this week

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, thanks!
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

**Comment by GrossOutD** [comment]
Now have access to modules and other pages, but not complete

Had to import a clean version of ps_authorization_role table, as this had no data in it, this caused access denied on all pages

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, thanks for your feedback.
We are aware of this issue (denied access), here's an issue similar to this: https://github.com/PrestaShop/autoupgrade/issues/100

Since the pages are ok, can I close the issue?

Thanks!

**Comment by GrossOutD** [comment]
Hi, yes as no more internal server error

Thanks

**Comment by khouloudbelguith** [comment]
@HAF1ZUR, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by giles247** [comment]
I'm getting same error as this, Can't really see resolution in this thread.
Can someone tell me what else gets done after database upgrade?
