### ISSUE TITLE
Weird Currency management behavior

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#13952]
So, I have USD currency in shop, see:
![2](https://user-images.githubusercontent.com/15143151/58309082-e13b2300-7e0b-11e9-97de-be16a9c24dbc.png)

Once I click edit I change "Currency" value to `EUR` in form and save it. After saving, I can see "ISO code" has changed, but "Currency" is still `USD`. See:
![3](https://user-images.githubusercontent.com/15143151/58309148-0d56a400-7e0c-11e9-8b42-004c441a079a.png)

In Currency form (Add/Edit) there is no way to change currency name, is this behavior expected?

It's on 1.7.6.x branch.

**Comment by khouloudbelguith** [comment]
Hi @sarjon,

I have the same issue with PS1.7.6.0beta1.
![image](https://user-images.githubusercontent.com/16067358/58311723-86043300-7e01-11e9-938b-bb028848211b.png)
In FO => NOK
![image](https://user-images.githubusercontent.com/16067358/58311982-383bfa80-7e02-11e9-9daa-44dcfa511f84.png)

With PS1.7.5.1 =>OK
![image](https://user-images.githubusercontent.com/16067358/58311747-9d432080-7e01-11e9-98ca-38e015b44d8e.png)

Thanks!

**Comment by sarjon** [comment]
So, this issue should be solved by adding new "Name" field to currency form? Currently, there isn't one:  

![download (2)](https://user-images.githubusercontent.com/15143151/58567314-d3860300-823a-11e9-9b26-7ddb0aa205e1.png)

**Comment by matks** [comment]
@colinegin @marionf We need feedback here

Nice catch from Sarunas: BO user cannot change a currency name. Is it expected ? For custom created currencies it would make sense, isn't it ?

**Comment by marionf** [comment]
@matks Yes, it's part 2 of CLDR: https://github.com/PrestaShop/PrestaShop/issues/11660

For 1.7.6 we can keep the same behavior as 1.7.5: update the currency name if the iso code is changed

**Comment by colinegin** [comment]
I agree with @marionf. Is there anything left to do here then ?

**Comment by matks** [comment]
@sarjon so behavior to be implemented is "when changing currency from USD to EUR, this should modify both ISO code and Currency name" (1 field controls 2 data fields)
