### ISSUE TITLE
Quite a lot of mistakes when I update to the latest version

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#13955]
**Is your feature request related to a problem? Please describe.**

Hi Again, i have updated to the last version, my first problem was wtih the permissions, was solved, now, i have a problem again i show this capture, because i don't undestand, Why is this happening?,
![imagen](https://user-images.githubusercontent.com/14195668/58315598-1cd8eb80-7e12-11e9-9aea-b654966ec99d.png)
I compare with the database of a clean installation, and some records are missing

i need help

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

In your project_folder/modules/contactform/ did you add the file `recaptcha.php` ?
![image](https://user-images.githubusercontent.com/16067358/58316931-a2599d00-7e0c-11e9-8e3b-9910a1ebb915.png)
By default, this file doesn't exist
https://github.com/PrestaShop/contactform

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by juank2808** [comment]
Ok, all the files that are inside the var / cache folder?

**Comment by khouloudbelguith** [comment]
@juank2808, yes, they are cache files!
Thanks!

**Comment by juank2808** [comment]
Ok it's done but now i have the same error, when I try to get updates on the modules, 
![imagen](https://user-images.githubusercontent.com/14195668/58318728-adb2c580-7e18-11e9-9185-e361dac70e11.png) do i try with the link that you sent me?

**Comment by khouloudbelguith** [comment]
@juank2808, in your project_folder/modules/contactform/ did you add the file recaptcha.php?
THanks!

**Comment by juank2808** [comment]
No, I haven't, the link you sent me is not there.

**Comment by khouloudbelguith** [comment]
@juank2808, so the file recaptcha.php is not located into /your_projet_folder/modules/contacform?

THanks!

**Comment by juank2808** [comment]
@khouloudbelguith No, the file isn't

**Comment by khouloudbelguith** [comment]
@juank2808, did you use the module recaptcha in your shop?

Thanks!

**Comment by juank2808** [comment]
has been installed, but now it isn't in use

**Comment by khouloudbelguith** [comment]
@juank2808, did you disable it?

Thanks!

**Comment by juank2808** [comment]
now isn't installed, i have other problem, the clientes cant see the products an more 
![imagen](https://user-images.githubusercontent.com/14195668/58321556-bf976700-7e1e-11e9-8359-b66564d0cf41.png)

**Comment by khouloudbelguith** [comment]
@juank2808, After uninstalling the recaptcha module, you have some issue related to this
You should contact the module author about this issue.
when debug mode is enabled, there are no exceptions displayed?

Thanks!

**Comment by juank2808** [comment]
No i cant se the exception, now i try close the shop and I do not have permissions, this is very confused

**Comment by khouloudbelguith** [comment]
@juank2808, how do you want to close the shop? by enabling the maintenance mode?
Thanks!

**Comment by juank2808** [comment]
Yes maintenance  monde sorry, this is very serious! now i'm debug mode and  show this error
![imagen](https://user-images.githubusercontent.com/14195668/58322529-78f73c00-7e21-11e9-982a-afdb39065321.png)
prestashop gives me errors on all sides and i cant make a clean installacion, 
![imagen](https://user-images.githubusercontent.com/14195668/58322706-0b97db00-7e22-11e9-99b9-778d58292ad7.png)

**Comment by khouloudbelguith** [comment]
@juank2808, It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

Thanks!

**Comment by juank2808** [comment]
i told you before, in the table ps_module, don't has some registers, example   
![imagen](https://user-images.githubusercontent.com/14195668/58323648-e22c7e80-7e24-11e9-81b4-81a8a1fd63ab.png) where is the id_module= 1?

**Comment by khouloudbelguith** [comment]
@juank2808, did you uninstalled the module contactform?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @juank2808,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
