### ISSUE TITLE
Error 500 - Back Office Login

### ISSUE THREAD

**Issue by bestbuybargains** [PrestaShop/PrestaShop#13951]
**Describe the bug**
Noticed that Import option was not working properly, turned on debugger and now BO is showing Error 500

**To Reproduce**
1. Go to BO
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/50038176/58276932-3e789b00-7d5e-11e9-910b-b5855575316a.png)

![image](https://user-images.githubusercontent.com/50038176/58276958-4d5f4d80-7d5e-11e9-851b-50dcb48c3442.png)

![image](https://user-images.githubusercontent.com/50038176/58276985-5b14d300-7d5e-11e9-963a-89ab209c4ad3.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by bestbuybargains** [comment]
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3213696/dev.log)
[20190521_exception.log](https://github.com/PrestaShop/PrestaShop/files/3213698/20190521_exception.log)

**Comment by bestbuybargains** [comment]
I have manually turned off the debugger in my server however Import option is throwing error 500

**Comment by khouloudbelguith** [comment]
Hi @bestbuybargains,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
After removal of cache try with those commands:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Thanks to check and feedback.

**Comment by bestbuybargains** [comment]
Thank you. After manually deleting the folders, I can now access the import section, however, after validation, i receive this error.

![Screenshot_20190524-074103_Chrome](https://user-images.githubusercontent.com/50038176/58328387-94e5e800-7df7-11e9-9751-091fb9aa0288.jpg)

**Comment by khouloudbelguith** [comment]
@bestbuybargains, could you please provide me the first product in your file csv that you need to import.
Thanks!

**Comment by bestbuybargains** [comment]
Hi! I sent the csv file to your email just in case you need it as i am importing a bunch of iphones

**Comment by khouloudbelguith** [comment]
@bestbuybargains, thanks!
I just received the email.
I will check & feedback

**Comment by khouloudbelguith** [comment]
@bestbuybargains, I imported the 3 first product & it is OK.
https://drive.google.com/file/d/1gARv9tI8vmsQapCYCD7gpvV1uj3ScQ95/view
I have a question about 
- what is the difference between Main_Product_Picture & image?
- you have column Height_mm/Width_mm/.. Height_cm, we only have one column height, width & depth

Thanks!

**Comment by bestbuybargains** [comment]
Great question! I actually ignore image as its extra sizes of photos and i also ignore the mm sizes as it is better to use cm.

**Comment by khouloudbelguith** [comment]
@bestbuybargains, same!

I ignored those columns & it is OK as described in my screen record
Thanks!

**Comment by bestbuybargains** [comment]
Understanding that the csv document is acceptable, what else may i try to get the file to import?  The same file has imported successfully on my other sites.

**Comment by khouloudbelguith** [comment]
@bestbuybargains, what is the exact configuration used in your case?
![image](https://user-images.githubusercontent.com/16067358/58338402-b1a60e00-7e3f-11e9-8214-ca95e9c4334f.png)

Thanks!

**Comment by bestbuybargains** [comment]
Another great question!  I always enable Force all ID numbers and disable the rest.

**Comment by bestbuybargains** [comment]
Okay, i have an update. So, I've tried all possible combinations with the importing options with no success, however, when i look at my products, i see that up to 5 will import (amount is always random) and the pictures are doubled, tripped, etc.  Do you want a screenshot or access to the BO?

**Comment by khouloudbelguith** [comment]
Hi @bestbuybargains,

Could you please provide me the credentials of your shop to check it.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by bestbuybargains** [comment]
All set my friend. Let me know if you have any questions!

**Comment by khouloudbelguith** [comment]
@bestbuybargains, thanks!
I just received the email.
I will check & feedback

**Comment by khouloudbelguith** [comment]
@bestbuybargains, in your file csv, you have a lot of products.
I will try to import them
Can you please confirm this action?

Thanks!

**Comment by bestbuybargains** [comment]
Yes, you can import all. Let me know if you have any questions!

**Comment by khouloudbelguith** [comment]
Hi @bestbuybargains, 

After importing the file csv, I have this error: `Attempted to call function "idn_to_ascii" from the global namespace.`
![image](https://user-images.githubusercontent.com/16067358/58464674-0d1d1800-812e-11e9-8507-5d7e0f7fdab9.png)

You need to enable & install php-intl extension on your server.

Thanks to check & feedback.

**Comment by bestbuybargains** [comment]
Alright. Intl is installed and functioning. Let me know if you see anything else

**Comment by khouloudbelguith** [comment]
@bestbuybargains, can I try to re-import products again?
Thanks!

**Comment by bestbuybargains** [comment]
Absolutely! Thanks for your help 😄

**Comment by khouloudbelguith** [comment]
@bestbuybargains, Now the import is OK
I sent you via email a video record
Thanks to check & feedback.

**Comment by bestbuybargains** [comment]
Thank you so much!!!

**Comment by khouloudbelguith** [comment]
@bestbuybargains, you are welcome!
Feel free to open a new one when needed.

Thanks!
