### ISSUE TITLE
Error in saving changes to products, after upgrade to 1.7.5

### ISSUE THREAD

**Issue by Madalina-nadari** [PrestaShop/PrestaShop#13960]
Hi, 
I've just made an upgrade to my store from 1.7.2.3 to 1.7.5.2 and i have some issues with the products.
First of all, i was missing the "location" column in ps_stock_available, and i put it, since i knew about this issue.
Now, i can update my stock, from products catalog - products, but if I try to make any other changes, or even going back to the catalog, i get an error message that the changes are not saved, and i have to back from the browser.
In debug mode i have this error: 
Unknown column 'cf.is_deleted' in 'where clause'<br /><br /><pre>
SELECT cf.`id_customization_field`, cf.`type`, cf.`required`, cfl.`name`, cfl.`id_lang`
FROM `psnad_customization_field` cf
NATURAL JOIN `psnad_customization_field_lang` cfl
WHERE cf.`id_product` = 555
AND cf.`is_deleted` = 0
ORDER BY cf.`id_customization_field`</pre>
I've looked it up, and i am missing the "is_deleted" column from customization_field, but I don't know the settings for this column. I've put it on the table anyway, and after saving it, the products changes are saved, but my products are missing their features (they exist before adding this column), and I have a lot of combinations for each product.

Another issues is that in product catalog - stocks, the list for the products is not generated, and even if I search for a product, i don't get any response ....it shows that is permanently charging the list..(no messages, no error when debug mode is on).

So, could you please help me sort this issue?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Madalina-nadari,

Thanks for your report.
What is the exact version 1-click upgrade did you use?

Thanks!

**Comment by Madalina-nadari** [comment]
Hi!
I have the version 4.7.0.
Thanks!

**Comment by khouloudbelguith** [comment]
@Madalina-nadari, we released a new version 1-click upgrade https://github.com/PrestaShop/autoupgrade/releases/tag/v4.8.0

It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

Thanks!

**Comment by Madalina-nadari** [comment]
> @Madalina-nadari, we released a new version 1-click upgrade https://github.com/PrestaShop/autoupgrade/releases/tag/v4.8.0
> 
> It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
> Thanks to check if there are missing columns in your database schema.
> You can find the full schema for 1.7.5.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql
> 
> Thanks!

Thank you for the quick response!
I'll check that out and come back with news!

**Comment by khouloudbelguith** [comment]
@Madalina-nadari, thanks!
Waiting for your feedback.

**Comment by Madalina-nadari** [comment]
Hi, 
I found that i was missing a lot o f the tables from the 1.7.5 version, because I have imported a database created in 1.7.2.3, and not because of the 1-click upgrade module.
Since I don't have a database created in 1.7.5, I am going back to 1.7.2.3 version.
Thanks for your help!

**Comment by khouloudbelguith** [comment]
@Madalina-nadari, thanks for your feedback.

I close the issue, feel free to open a new one when needed.

Thanks!
