### ISSUE TITLE
{id_order} not available in order_conf

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#13964]
Only {order_name} is available as a variable to use in the template, but {id_order} is available in all other templates.
Could you please make this variable available also out-of-the-box ?

**Comment by khouloudbelguith** [comment]
ping @jolelievre what do you think?
Thanks!

**Comment by jolelievre** [comment]
Hello @cedricfontaine,

I'm sorry but I don't see any `{id_order}` in the templates, they all use the same variable `{order_name}`

**Comment by cedricfontaine** [comment]
Hello,

They all use {order_name} but {id_order} is an available variable in every step, except for order_conf.
It could be cool to be consistent.

**Comment by jolelievre** [comment]
Hi,

ok I get it now I was looking at the templates but couldn't find this variable anywhere (only `{order_name}` is used in the classic templates. But i see it in the PHP calls, so indeed we could add this variable in order_conf, thanks for pointing it out.

As 176 is already frozen this update will be integrated in 177 now.

**Comment by ghost** [comment]
@jolelievre, Is it still on waiting for dev?

**Comment by jolelievre** [comment]
@samuel-pires Nothin has been made so far It should be prioritized (I think it's an `S` complexity)
