### ISSUE TITLE
BO filemanager filter not working

### ISSUE THREAD

**Issue by ComonSoft** [PrestaShop/PrestaShop#13968]
Using filemanager in backoffice other https, the filter doesn't work. Due to mixed content a js include file is blocking.

1. Go to any rich text editor (page, product description...)
2. Click on insert picture Icon
3. Click on browse Icon
4. Enter text in filter box
5. Click on filter button, filter not working

If you go to browser inspector, you will see in console an error for a js request :
Mixed content error ... http://prestashop.domain.ext/adminXXXX/filemanager/dialog.php?type=1&descending=false&sort_by=&lang=fr&filter=keyword ... include.min.js

​PrestaShop version: 1.7.4.2 to 1.7.5.2
PHP version: 7.0 to 7.1

**Comment by khouloudbelguith** [comment]
Hi @ComonSoft,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1
I attached a video record
https://drive.google.com/file/d/1-eiq8H_32axD6PTPlZNy8B4mF8J5RDoI/view
Thanks to check & feedback

**Comment by ComonSoft** [comment]
Are you in HTTPS ? Because in my local test I'm in 1.7.5.2 and it's not working. And if you look at the [source code 1.7.5.x you'll see hard coded http line 350](https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/admin-dev/filemanager/dialog.php)
It has been fixed in 1.7.6.x

**Comment by khouloudbelguith** [comment]
@ComonSoft, no, I'm not using https, did you use https in your case?

Thanks!

**Comment by ComonSoft** [comment]
Yes this is the issue, mixed content blocked when you are in https as explained in ticket ;-)
But you can close it, it solved in next release.

**Comment by khouloudbelguith** [comment]
@ComonSoft, thanks for your feedback.
Fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/11526
Feel free to open a new one when needed.

Thanks!
