### ISSUE TITLE
Age validation 

### ISSUE THREAD

**Issue by cr998** [PrestaShop/PrestaShop#13974]
**Describe the bug**
it looks like the age validation doesn`t works porperly

**Reproduce**
Can be read in the [https://www.prestashop.com/forums/topic/987326-po-validacji-i-blad-formatu-daty-w-rejestracji/](https://www.prestashop.com/forums/topic/987326-po-validacji-i-blad-formatu-daty-w-rejestracji/)

**Additionnal information**
PrestaShop version: I think 1.7.5.1
PHP version: Anything about this.

**Comment by khouloudbelguith** [comment]
Hi @cr998,

I tried with PS1.7.6.0beta1 & PS1.7.5.2.
The 18 validation doesn't exist in my case, 
In the first time, I enter a wrong format => ok => an alert is displayed
In the second time => I enter the good format => it is OK => le format is not transformed

I attached a video record
https://drive.google.com/file/d/1Yq00rdi_6MChIizEaGDkeV6eHnrIcrLv/view

Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @cr998,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
