### ISSUE TITLE
PS1.7.6 beta - If Ask for birth date option is disabled, an exception is displayed in the FO

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13976]
PS 1.7.6.0 clean install after 1.7.5
```
(1/1) FatalThrowableError
Call to a member function getValue() on null
in CustomerForm.php line 120
at CustomerFormCore->validate()
in CustomerForm.php line 188
at CustomerFormCore->submit()
in CheckoutPersonalInformationStep.php line 62
at CheckoutPersonalInformationStepCore->handleRequest(array('id_customer' => '', 'id_gender' => '1', 'firstname' => 'MyName', 'lastname' => 'MyName', 'email' => 'email', 'password' => '', 'submitCreate' => '1', 'continue' => '1', 'isolang' => 'en', 'id_lang' => 1, 'controller' => 'order'))
in CheckoutProcess.php line 59
at CheckoutProcessCore->handleRequest(array('id_customer' => '', 'id_gender' => '1', 'firstname' => 'MyName', 'lastname' => 'MyName', 'email' => 'email', 'password' => '', 'submitCreate' => '1', 'continue' => '1', 'isolang' => 'en', 'id_lang' => 1, 'controller' => 'order'))
in OrderController.php line 264
at OrderControllerCore->initContent()
in Controller.php line 291
at ControllerCore->run()
in Dispatcher.php line 515
at DispatcherCore->dispatch()
in index.php line 28
```

Order as a guest -> click Continue
**Steps to reproduce the issue:**
1. In the BO => Shop Parameters => Customer settings => Disable `Ask for birth` date option

2. In the FO, when you try to create a new account from the new account page, or the checkout page(a guest or a customer) => an exception is displayed

Reported by user @PeterStudioWeb

**Comment by khouloudbelguith** [comment]
Hi @PeterStudioWeb, @matks, 

I did not manage to reproduce the issue with PS1.7.6.0beta1 and PS1.7.5.2
I attached a video record
https://drive.google.com/file/d/17BViOZ7YccCznGqsFuQrnfPDvkEax2Pg/view?usp=sharing

Thanks to check & feedback

**Comment by PeterStudioWeb** [comment]
A bit later I will record video with this mistake

**Comment by khouloudbelguith** [comment]
Hi @PeterStudioWeb,

Thanks!
Waiting for your feedback

**Comment by ghost** [comment]
Same issue here.
When I try to continue from Guest Name and e-mail input, error 500 is returned.

Enabling Debug Mode swaps er 500 with this:
![image](https://user-images.githubusercontent.com/22904165/58579807-13a1b180-824c-11e9-8140-954cdf53f0ce.png)

**Comment by matks** [comment]
> Same issue here.
> When I try to continue from Guest Name and e-mail input, error 500 is returned.
> 
> Enabling Debug Mode swaps er 500 with this:
> ![image](https://user-images.githubusercontent.com/22904165/58579807-13a1b180-824c-11e9-8140-954cdf53f0ce.png)

Can you tell us about the shop config : multiple currencies activated ? multiple countries enabled ? multiple languages enabled ?

**Comment by ghost** [comment]
Currencies - 1 (PLN)
Countries - All (None removed from default)
Languages - PL (default), EN

**Comment by PeterStudioWeb** [comment]
> Can you tell us about the shop config : multiple currencies activated ? multiple countries enabled ? multiple languages enabled ?
Yes,
1. Currencies - 11
2. Countries - All (244)
3. Languages - default (en, de)

**Comment by OneDotIT** [comment]
Hello,
This issue is represented when the option 'Ask for birth date' is disabled.
> Shop Parameters -> Customer Settings, Ask for birth date: NO

Also, you will not be able to register a new account, change the option 'Ask for birth date' to YES as a current workaround.

**Comment by khouloudbelguith** [comment]
Hi all,

Thanks for the clarifications.
I manage to reproduce the issue with PS1.7.6.0beta1 
In the BO => Shop Parameters => Customer settings => Disable `Ask for birth` date option

In the FO, when you try to create a new account from the new account page, or the checkout page(a guest or a customer) => an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/58621730-f3143e80-82c1-11e9-9ef9-1f6900ec6167.png)

In the PS1.7.5.2 => OK
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by OneDotIT** [comment]
أهلاً أ.خلود,
I proposed the fix: https://github.com/PrestaShop/PrestaShop/pull/14035

**Comment by OneDotIT** [comment]
I proposed the fix: #14035

**Comment by khouloudbelguith** [comment]
@OneDotIT, thanks for your fix!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14075
