### ISSUE TITLE
Whoops, looks like something went wrong after "upgrade" to 17.5.2 500 Server Error

### ISSUE THREAD

**Issue by jointsystems** [PrestaShop/PrestaShop#13970]
We attempted to upgrade a 1.6.2.3. to 1.6.2.4. using 1-Click upgrade version 4.7  as we did 18 other stores without incident.  Due to the failure to be observant we ended up "upgrading" to 1.7.5.2 instead and the process ended up at the Dashboard with all items in a permanent time out mode.  Attempting to go to manage modules we instead got a 500 Server error.  Click on My Shop takes us to the front end which is now default woman's clothes plus Latin and the search  results in a 500 server error.  We can find no tab for 1-click update and as a result no roll back.

**To Reproduce**
1. Go to '1-click  update'
2. Click on 'put shop in maintenance mode.'
3. Scroll down to 'Update PrestaShop'
4. See unusable store 

**Screenshots**

(1/1) ContextErrorExceptionNotice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php56) failed: Permission denied (13)
--
in StrictSessionHandler.php line 101
at StrictSessionHandler->gc(1440)in SessionHandlerProxy.php line 83
at SessionHandlerProxy->gc(1440)
at session_start()in NativeSessionStorage.php line 145
at NativeSessionStorage->start()in NativeSessionStorage.php line 295
at NativeSessionStorage->getBag('attributes')in Session.php line 256
at Session->getBag('attributes')in Session.php line 278
at Session->getAttributeBag()in Session.php line 73
at Session->get('_security_main')in ContextListener.php line 89
at ContextListener->handle(object(GetResponseEvent))in WrappedListener.php line 46
at WrappedListener->handle(object(GetResponseEvent))in TraceableFirewallListener.php line 35
at TraceableFirewallListener->handleRequest(object(GetResponseEvent), object(Generator))in Firewall.php line 84
at Firewall->onKernelRequest(object(GetResponseEvent))in FirewallListener.php line 48
at FirewallListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))in WrappedListener.php line 111
at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in TraceableEventDispatcher.php line 143
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 88

![1752 Front end](https://user-images.githubusercontent.com/41153050/58343885-2f5b2100-7e22-11e9-8412-5f3bb0b12c92.PNG)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jointsystems,

It looks like a permission error or PHP misconfiguration on your server. From the stack trace you posted, I can tell that PHP is configured to store stores its sessions on /var/cpanel/php/sessions/ea-php56, but it's unable to read from there. It might be that the user on which your web server (or PHP, if you're using fastcgi) needs read/write rights on that directory.

Here's a link that might shed some more light on this issue: https://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder

Hope this helps solve your problem.
Thanks to check & feedback

**Comment by jointsystems** [comment]
See below warning of non-compatibility.  This is why we did not want to use 1.7 versions as their is no AuthorizeAim compatibility which is used for payment.  How do we roll this back, cannot get into modules and no link for 1-Click upgrade?  
![warning line 30 in file](https://user-images.githubusercontent.com/41153050/58591542-89018800-8234-11e9-9c87-5c2cc9c16d79.PNG)

**Comment by khouloudbelguith** [comment]
@jointsystems, about the first warning, yes as you said, you have an AuthorizeAim compatibility issue.
You need to contact the module author about this issue.
About the second alert, as I said in my previous comment, it looks like a permission error or PHP misconfiguration on your server.

To rollback, in the 1-click upgrade configuration page, you have a section Rollback, you need to choose your backup & click on Rollback.

![image](https://user-images.githubusercontent.com/16067358/58623223-69ff0680-82c5-11e9-9646-34b03823cb21.png)

Thanks!

**Comment by jointsystems** [comment]
As stated in the initial post "We can find no tab for 1-click update and as a result no roll back."  Where is the 1-click  upgrade it is not a tab in Advanced Parameters and we can't get into database as it just produces a page full of errors?  I changed the permissions to 755 from 644 for strict session handler php but it has not corrected any of the errors?

**Comment by khouloudbelguith** [comment]
@jointsystems,

>"We can find no tab for 1-click update and as a result no roll back.

In the PS1.7, the 1-click upgrade should be displayed in the menu Tab.
You can navigate to your BO => Modules => Module Manager => seach for the 1-click upgrade module.
About the strict session handler PHP, you need to check with your host about this issue, it is a server issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jointsystems,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by jointsystems** [comment]
Lost the link to the case.    Though there are payment modules at addons.prestshop.com that support authorize.net none popup in the modules market place in the admin of the actual 1.7.2.5 shop.  Trying to determine which would be best.  The popup chat help was absolutely worthless and none of the developers responded to inquires?  Trying to find out if we have to purchase the module once or for each ot the 24 shops?

**Comment by jointsystems** [comment]
These are the modules for which we received no response from the developers:
