### ISSUE TITLE
facetedsearch - filtering doesn't filter between product attributes

### ISSUE THREAD

**Issue by Varindien** [PrestaShop/PrestaShop#13985]
Hello,

Filtering between 2  product attributes, do not filter, it seems to doing a "OR" filtering, instead of a "AND".

to reproduce : 

- Create  products with 2 attributes, eg : color and size.
- Add attribute to filter in module configuration
- Go to category listing page and apply filter on a color and size.

eg: if a color is available for one product, and a size for several products. It will display all size available, not only the product with color "AND" size available :  instead of  we got a "OR" listing.

Module version ps_facetedsearch : 3.0.2
PrestaShop version:  1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Varindien,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & ps_factedseach v3.0.2
Same with PS1.7.5.2 & ps_facetedsearch v3.0.2

Fresh installation 1.7.6.0 => in the Home category page => I have Active filter color: Black & Size:S
In the Result, I have 5 products, from this filter, I have a product which has the only color black & doesn't have the size: S

https://drive.google.com/file/d/1RyxF2w9nrl0UCMfEL4DwPeGjL0oNFZ87/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/58425919-0a211980-8093-11e9-80bd-49df4b797bdf.png)

But with ps_factedsearch v2.2.0, I have Active filter color: Black & Size:S
In the Result, I have only one product

https://drive.google.com/file/d/1BwVWc8f5VkZD0YyyYkaP1JNS69ojSk3r/view
![image](https://user-images.githubusercontent.com/16067358/58425901-ff668480-8092-11e9-9467-e479b3232af1.png)

ping @PierreRambaud 

Thanks!

**Comment by PierreRambaud** [comment]
Will be fix as soon as possible :+1: 
I'm on it!

**Comment by HeineFr** [comment]
I've got the same problem, i have checkbox faceted filters in this order configuration :
-Brand filter
-1 couple of Attributes (exemple size)
-1 couple of caracteristics (exemple season wear)
-A second couple of caracteristics (exemple material)

If you select cumulative faceted filter **from the bottom to the top** :
Material + size -> Works
Material + size + Brand -> Works
Material + season wear -> Bug ; show all season wear & ignore material

If you select **from the top to the bottom** :
Brand + anything -> Bug ; show anything & ignore brand
Size + material ->  Bug ; show material & ignore brand

ps 1.7.5 & ps faceted 3.0.1

**Comment by PierreRambaud** [comment]
Should be ok here: https://github.com/PrestaShop/ps_facetedsearch/pull/72 Thanks for feedbacks and help guys!
