### ISSUE TITLE
BO AdminCarrierWizard add FormModifier

### ISSUE THREAD

**Issue by RomsC** [PrestaShop/PrestaShop#13986]
**Is your feature request related to a problem? Please describe.**
For a project I need to add custom fields to the AdminCarrierWizard.
I know that a FormModifier action hook exist but it doesn't be call.

**Describe the solution you'd like**
AdminCarrierWizard doen't use mehod renderForm so the FormModifer action hook doesn't call.
I have add the hook in the renderGenericForm method of AdminWizardCarrier.

```
public function renderGenericForm($fields_form, $fields_value, $tpl_vars = array())
    {
        Hook::exec('action' . $this->controller_name . 'FormModifier', array(
            'object' => &$this->object,
            'fields' => &$fields_form,
            'fields_value' => &$fields_value,
            'form_vars' => &$tpl_vars,
        ));

        $helper = new HelperForm();
        $helper->show_toolbar = false;
        $helper->table = $this->table;
        $lang = new Language((int) Configuration::get('PS_LANG_DEFAULT'));
        $helper->default_form_language = $lang->id;
        $helper->allow_employee_form_lang = Configuration::get('PS_BO_ALLOW_EMPLOYEE_FORM_LANG') ? Configuration::get('PS_BO_ALLOW_EMPLOYEE_FORM_LANG') : 0;
        $this->fields_form = array();
        $helper->id = (int) Tools::getValue('id_carrier');
        $helper->identifier = $this->identifier;
        $helper->tpl_vars = array_merge(array(
                'fields_value' => $fields_value,
                'languages' => $this->getLanguages(),
                'id_language' => $this->context->language->id,
            ), $tpl_vars);
        $helper->override_folder = 'carrier_wizard/';

        return $helper->generateForm($fields_form);
    }
```

**Comment by Matt75** [comment]
This controller will be rework entirely when migrate on Symfony stuffs.

I need that too but for the moment I use an override of this legacy controller to add what I need.

It's for your own Prestashop or a module you want to distribute ?

Because we just have to wait few months to use more powerful tools :D

**Comment by RomsC** [comment]
It's for my own Prestashop so I can wait the migration.
Thanks for your reply.

**Comment by khouloudbelguith** [comment]
Hi @RomsC,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!
