### ISSUE TITLE
WebService Update return empty tag for numeric field if value is 0

### ISSUE THREAD

**Issue by pumamood** [PrestaShop/PrestaShop#13981]
**Describe the bug**
For some entities when you update numeric field with value 0, XML response returned from PUT request has an empty tag without the value inside

**To Reproduce**
1. Request
PUT /api/product_options?ws_key=xxx 
content:
 ```<prestashop>
<product_option>
  <id>2</id>
  <is_color_group>0</is_color_group>
  <group_type>select</group_type>
  <position>0</position>
  <name>
    <language id="1">color_188</language>
    <language id="2">colore_188</language>
  </name>
  <public_name>
    <language id="1">Color</language>
    <language id="2">Colore</language>
  </public_name>
  <associations>
    <product_option_values />
  </associations>
</product_option>
</prestashop>
```
2. Response
```<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product_option>
	<id><![CDATA[2]]></id>
	<is_color_group></is_color_group>
	<group_type><![CDATA[select]]></group_type>
	<position><![CDATA[0]]></position>
	<name><language id="1" xlink:href="https://shop.xxx/api/languages/1"><![CDATA[color_188]]></language><language id="2" xlink:href="https://shop.xxx/api/languages/2"><![CDATA[colore_188]]></language></name>
	<public_name><language id="1" xlink:href="https://shop.xxx/api/languages/1"><![CDATA[Color]]></language><language id="2" xlink:href="https://shop.xxx/api/languages/2"><![CDATA[Colore]]></language></public_name>
<associations>
```
….

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @pumamood,

Thanks for your report.

If you try to update the same product option with the same XML, just replace this

`<group_type>select</group_type>`

by this

`<group_type>color</group_type>`

In the return response, you will find that `is_color_group` is not empty

Thanks to check & feedback

**Comment by pumamood** [comment]
i know but it is not what i want. it works because  is_color_group value is automatically set to 1. it happens only with value 0. It doesn't happen in GET requests

**Comment by khouloudbelguith** [comment]
@pumamood, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1

XML sent
![image](https://user-images.githubusercontent.com/16067358/58419541-cfaf8080-8082-11e9-996f-70cb386c2d1b.png)

Http response
![image](https://user-images.githubusercontent.com/16067358/58419551-d76f2500-8082-11e9-8621-a8aff058fa4d.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by pumamood** [comment]
yes i think i found the issue
https://github.com/PrestaShop/PrestaShop/blob/913c4c84893373c9ef97da09b6c7ea93b10831e3/classes/webservice/WebserviceOutputXML.php#L138
change into
`            if ($field['value'] !== '') {`

**Comment by khouloudbelguith** [comment]
@pumamood, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13983
