### ISSUE TITLE
Hi There, in the module Relance Panier, it's not clear if conditions are "OR" or "AND". You really shoud add explanations during the conditions process

### ISSUE THREAD

**Issue by JoSchmutz** [PrestaShop/PrestaShop#13998]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JoSchmutz** [comment]
For each rule you can add conditions, in the french version, it is not mentioned if conditions are OR or AND.

**Comment by khouloudbelguith** [comment]
Hi @JoSchmutz,

What is the exact module did you use?
This module https://addons.prestashop.com/fr/remarketing-paniers-abandonnes/16535-relance-de-paniers-abandonnes-pro.html ?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @JoSchmutz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
