### ISSUE TITLE
 ContextErrorException

### ISSUE THREAD

**Issue by amine96nas** [PrestaShop/PrestaShop#13991]
**Describe the bug**
Hi guys, 
I bought lately a theme for my prestashop store.
After the theme support installed it, I had this problem

(1/1) ContextErrorExceptionWarning: Invalid argument supplied for foreach()
--
in tm_categoryslider.php line 483
at Tm_Categoryslider->getWidgetVariables('displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in tm_categoryslider.php line 445
at Tm_Categoryslider->renderWidget('displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 971
at HookCore::coreRenderWidget(object(Tm_Categoryslider), 'displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 923
at HookCore::exec('displayHome')in IndexController.php line 39
at IndexControllerCore->initContent()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 511
at DispatcherCore->dispatch()in index.php line 28

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @amine96nas,

This issue occurs due to the tm_categoryslider modules.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
