### ISSUE TITLE
Hi please help i need it badly Payment Preference is Blank Prestashop 1.7

### ISSUE THREAD

**Issue by zer0below** [PrestaShop/PrestaShop#13997]
Please help Payment Preference is Blank Prestashop 1.7, I need to check the cash on delivery on my country. is it possible to force it on database?

![image](https://user-images.githubusercontent.com/38272278/58469894-12e91c80-8173-11e9-97f2-5c409162581d.png)

**Comment by khouloudbelguith** [comment]
Hi @zer0below,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by zer0below** [comment]
Hi thank you so much for your quick response
here's the error in the debug mode
please see screenshot below
![image](https://user-images.githubusercontent.com/38272278/58471002-7aa06700-8175-11e9-8446-2fe5aa1910c7.png)

**Comment by khouloudbelguith** [comment]
@zer0below, this exception is displayed due to the `Posmegamenu` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by zer0below** [comment]
Question all i want for the meantime is to tick the cash on delivery enable. is it possible to do it in database? what table?

**Comment by khouloudbelguith** [comment]
@zer0below, to avoid this exception, you can disable the `Posmegamenu` module temporary.

Thanks!
