### ISSUE TITLE
Manually created currencies don't have decimals

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13990]
**Describe the bug**
Manually created currencies don't have decimals

**To Reproduce**
1. Go to BO > International > Localization > Currencies
2. Click on Add a new currency (ex: GBP, USD ...)
3. Enable it
4. Go to FO/BO and see prices

**If I import a localization pack, I don't have this issue**

**Screenshots**
![capture d'écran_1604](https://user-images.githubusercontent.com/13449658/58429728-144d1300-80a7-11e9-9a23-f045fcfa5780.png)

![capture d'écran_1605](https://user-images.githubusercontent.com/13449658/58429947-cb498e80-80a7-11e9-8040-5b93d212e291.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by colinegin** [comment]
It works again when the newly created currencies are removed from the BO.
