### ISSUE TITLE
Blurry effect on edit and delete submenu icons on migrated pages

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14001]
In newly migrated pages, there is a "blurry" effect on submenu icons for edit and remove options. This might be related to a change in their size, which should not happen.
Ex : 
![image](https://user-images.githubusercontent.com/35263827/58484777-0b217c00-8163-11e9-891e-3ef72fe6e021.png)

**Comment by sarjon** [comment]
This happened to me before as well, make sure your browser zoom is at 100%, but I guess it should be fixed anyway.

**Comment by zuk3975** [comment]
I found out that this behavior is associated with bootstrap dropdown, so i doubt we can do anything.
The thing is that on toggle it puts style with transform:translate3d('x', 'y', 0) and this causes the blur. There are workarounds for this particular css attribute (for example putting transform:translateX('x') translateY('y')), but we cannot change the behavior of bootstrap anyway.

**Comment by colinegin** [comment]
Alright thanks for your feedback @zuk3975 , since there's nothing we can do yet, I remove it from the 1.7.6 kanban. 
@matks , for a future version we'll see if there's something we can do to improve it.

**Comment by davidglezz** [comment]
It is easy to fix adding single line of code.

> You can just turn off the transform placement on Popper to make it only use top/left for positioning instead. Then you can use transform for any animations/transitions as you wish.
> 
> `Popper.Defaults.modifiers.computeStyle.gpuAcceleration = false;`

https://github.com/twbs/bootstrap/issues/23378#issuecomment-324750360

**Comment by NeOMakinG** [comment]
Still unfixable without a bootstrap update of UIKit and BO Themes

**Comment by colinegin** [comment]
Alright so I guess this will be fixed with 178 once the UI kit has been updated ?

**Comment by NeOMakinG** [comment]
Well it seems like I can yes, gonna work on this

**Comment by LouiseBonnard** [comment]
On hold, waiting for the merge of the UI kit.

**Comment by davidglezz** [comment]
https://github.com/twbs/bootstrap/pull/30811#issuecomment-661795646

**Comment by NeOMakinG** [comment]
@davidglezz It will probably fixed on next uikit release, or on new major version :/

I say that because we noticed that it wasn't here with uikit on the develop branch, but overwhise it will probably be fixed later with the PR you linked, thanks :)

**Comment by NeOMakinG** [comment]
Looks fine now on develop, should be fixed :)
