### ISSUE TITLE
ps_facetedsearch 3.0.2 hides products when it is active

### ISSUE THREAD

**Issue by gescocis** [PrestaShop/PrestaShop#14014]
**Describe the bug**
Although I have reconstructed the entire index of prices and product attributes, if active it hides all the products from me.
I have tried all the possible configurations, with customer groups, discounts, products etc ... but every time I activate it it hides my products when I browse the product categories.
As soon as I deactivate it, products by category work.

There are the filters but nothing products >>>> http://prntscr.com/nuv2vi

**To Reproduce**
1. Go to category page of gescotradingsrl.com
2. The error as per screenshots are hide product. if i deactivate the module i can show the product in category (the module is now deactivated)

**Screenshots**
>>> http://prntscr.com/nuv0ac
>>> http://prntscr.com/nuv2vi﻿

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.3.5
Versione MySQL: 5.7.23
Motore MySQL: InnoDB
Driver MySQL: DbPDO

Thanks very much.

**Comment by khouloudbelguith** [comment]
Hi @gescocis,

PrestaShop 1.7.5 is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

In my case, it is OK.
Thanks to downgrade your version PHP, check & feedback.

**Comment by gescocis** [comment]
Hi,
thanks for quick reply.

I downgrade with this data: 
Versione di PHP: 7.2.18
Limite di memoria: 256M
Tempo di esecuzione massimo: 300
Dimensione Max. dei file da caricare: 50M

>>> Opzion Activated >>> http://prntscr.com/nuvlkg

I re activated the module, i clear the cache and i refresh the site.

the products are not yet displayed on the category pages

**Comment by khouloudbelguith** [comment]
@gescocis, in the configuration page of the ps_facetedseach module, `Show products from subcategories` option is enabled or disabled?

![image](https://user-images.githubusercontent.com/16067358/58555002-55ad0200-8210-11e9-9b12-524abc28b2a6.png)

THanks!

**Comment by gescocis** [comment]
hi,
sorry for the delay in the response. Everything is activated as shown in the screenshots:
1) Template of filters >>>> http://prntscr.com/nuzjst
2) Options of Module >>> http://prntscr.com/nuzkaf

How can fix the error?

Thanks

**Comment by gescocis** [comment]
now the site is online accessible to customers and I have to deactivate the form.
I look forward to suggestions and if needed I can also give FTP login credentials to check the form.

Thank you

**Comment by gescocis** [comment]
Hi,
I believe I have identified the problem that did not make me view the products with facetedsearch activated.

There were 2 products in the DB with assigned category 0 root which probably created conglitto with the module.

I deleted them, then followed your instructions and now everything works fine.

Thank you so much for the help

Amedeo di Gesco

**Comment by khouloudbelguith** [comment]
@gescocis, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by gescocis** [comment]
Thank you very much for your time.
Amedeo
