### ISSUE TITLE
getUriFromPath strips slashes when PS is in servers root (chrooted to document root)

### ISSUE THREAD

**Issue by edspiner** [PrestaShop/PrestaShop#14025]
**Describe the bug**
When the web server is chrooted to DOCUMENT ROOT of the web application the getUriFromPath function will strip all slashes from the path, so they look like:
`http://someshop.examplethemeassetsstyle.css`
The issue happens in https://github.com/PrestaShop/PrestaShop/blob/aec97ddb1551fd7d6d56f75549a992d6937caf50/src/Adapter/Assets/AssetUrlGeneratorTrait.php#L46 because of:
```php
str_replace('/', rtrim('/', '/'), '/theme/path/to/asset.css')
```

**To Reproduce**
1. Chroot the server to web servers DOCUMENT_ROOT
2. Install PS
3. Visit frontend
4. Path to JS and CSS are stripped from slashes 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @edspiner,

Thanks for your report.
I used this [link](https://www.howtoforge.com/tutorial/chrooting-apache-2.4-with-mod_unixd-on-debian-8-jessie/) to chroot apache.
When I tried to install Prestashop 1.7.6.0beta1 / 1.7.5.2, in the second steps: License agreements
I have error 500
https://drive.google.com/file/d/1dN0UUj_9GQ1kbLGtLefxjSPH9bYJZNG6/view
I enabled debug mode, I have this exception
![image](https://user-images.githubusercontent.com/16067358/58629019-26ab9480-82d3-11e9-8ca9-09ac757bb546.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @edspiner,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by jakub-swierk** [comment]
Some hosting providers define root directory same as page directory.

In this situation:

In `defines.inc.php`
```php
$currentDir = dirname(__FILE__);
```
So `$currentDir` is equal to `/config`.

```php
/* Directories */
if (!defined('_PS_ROOT_DIR_')) {
    define('_PS_ROOT_DIR_', realpath($currentDir.'/..'));
}

if (!defined('_PS_CORE_DIR_')) {
    define('_PS_CORE_DIR_', realpath($currentDir.'/..'));
}
```

After that, the `_PS_ROOT_DIR` and `_PS_CORE_DIR_` is equal to `/`.
Because of that we have situation where `getUriFromPath` is removing slashes from url:

```php
str_replace($this->configuration->get('_PS_ROOT_DIR_'), rtrim($this->configuration->get('__PS_BASE_URI__'), '/'), $fullPath);
str_replace('/', rtrim('/', '/'), '/theme/path/to/asset.css');
str_replace('/', '', '/theme/path/to/asset.css');
'themepathtoasset.css';
```
