### ISSUE TITLE
Multistre does not set the same quantities

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#14032]
Hello. I have a multistore and I add and update products in All shops mode, like on the screen below:

![obraz](https://user-images.githubusercontent.com/48493952/58659405-276c1700-8323-11e9-817d-2889f8b6ab4f.png)

When I update description, title or price it updates in both shops with no problem. But when I change available quantities it updates only product in main shop. When I add new product and set quantit to 5, the main shop has 5, but the second shop has 0. I have select the second shop in All shops mode and change it manually.

This is the setting for the main shop (I called this group Global):

![obraz](https://user-images.githubusercontent.com/48493952/58659826-3b644880-8324-11e9-89bf-4a838432dced.png)

And this is a setting for the second shop (I called it IT)

![obraz](https://user-images.githubusercontent.com/48493952/58659869-5636bd00-8324-11e9-9560-ff04787228eb.png)

I do not know how to fixed this. Any advice?

**Comment by khouloudbelguith** [comment]
Hi @banan44,

This is normal behavior.
In fact, in the Product page
Available quantity for sale provided that:

- The "Share quantity available for sale" option is checked for the group
- The group does not share its quantity available for sale outside of the group.

The Available quantity for sale can be customized for a single shop, for a group of shops but **not** for all shops at once

![image](https://user-images.githubusercontent.com/16067358/58694508-0ccd8880-838b-11e9-8a86-ceddd0dd21b0.png)

For more details, you can follow our documentation: http://doc.prestashop.com/display/PS17/The+multistore+interface

Thanks!
