### ISSUE TITLE
Ask confirmation before upgrade module

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#14039]
**Is your feature request related to a problem? Please describe.**
Many thread on PrestaShop Forums about FacetedSearch upgrade troubleshooting.
Merchants do module upgrade on production without testing it on a test instance.

**Describe the solution you'd like:**
I would like to show a warning popup to inform merchant about potential risk of doing an upgrade on production without test.

One click upgrade is not safe, merchants who has custom theme or other customization can be not compliant with a module upgrade without test on their side.

_Bonus : be able to check PHP version compliancy_

**Specifications:**
https://github.com/PrestaShop/prestashop-specs/pull/163/files

**Design:**
https://invis.io/RDZ7QTTK8NY

**Additional context**
https://www.prestashop.com/forums/tags/facetedsearch/

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by Matt75** [comment]
I think this is not related on FacetedSearch, this concern all modules upgrade.

**Comment by Quetzacoalt91** [comment]
> One click upgrade is not safe, merchants who has custom theme or other customization can be not compliant with a module upgrade without test on their side.

As a sidenote, we're NOT talking about the autoupgrade module here.

**Comment by PierreRambaud** [comment]
Agreed with this feature. Adding the capability to add a confirm box, with the changelog or something similare is a great idea :)

**Comment by TristanLDD** [comment]
Similar modals already exist for PrestaTrust : 

![Capture d’écran 2019-07-26 à 11 56 30](https://user-images.githubusercontent.com/27484094/61943763-72f61680-af9c-11e9-90b8-d2b4b5f61888.png)

I just need the wording for this new modal, then i can give you the design.

**Comment by Matt75** [comment]
@PrestaShop/prestashop-core-developers I thinks this feature should be in 1.7.7 because we have many issue with people updating modules in production environment.

It cause many issues related to PrestaShop cache cleaning and server cache invalidation.
I thinks it need a new EPIC about cache management because we need to provide in documentation guidelines to manage cache in production.
Some hosting provider use a bad configuration like OVH cause issues or 1&1 with a IO limitation...

Moreover I thinks we should add a new empty state on Modules > Modules Manager > Updates
To inform merchant about best practice to do a module update like put the shop in maintenance, disable cache etc...

Related issues : 
- https://github.com/PrestaShopCorp/ps_mbo/pull/96
- https://github.com/PrestaShop/PrestaShop/issues/17137
- https://github.com/PrestaShop/PrestaShop/issues/15436 
- https://github.com/PrestaShop/PrestaShop/issues/19465
- https://github.com/PrestaShop/PrestaShop/issues/16214
- https://github.com/PrestaShop/PrestaShop/issues/18664 
- https://github.com/PrestaShop/PrestaShop/issues/11557
- https://github.com/PrestaShop/PrestaShop/issues/11914
- https://github.com/PrestaShop/PrestaShop/issues/12085
- https://github.com/PrestaShop/PrestaShop/issues/15744
- https://github.com/PrestaShop/PrestaShop/issues/19741
- https://www.prestashop.com/forums/topic/1025654-you-have-requested-a-non-existent-service-mbotabcollectionprovider/
- https://www.prestashop.com/forums/topic/1026050-11-servicenotfoundexception/

A lot of report on PrestaShop Forums too

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by matks** [comment]
I 🆙 this request and this need ; makes a lot of sense 👍

**Comment by eternoendless** [comment]
I'm sorry to be the one saying no, but we can't add this in 1.7.7 because it's too late  in the release cycle. However I think this would be a nice addition to 1.7.8

**Comment by Matt75** [comment]
Well, we should investigate on Cache issues, reports are growing since ps_mbo first release on shared hosting. (ps_linklist is concerned too since v3.0.0 🥴 )

Note : this feature request has been made last year... 👎

**Comment by Matt75** [comment]
Bump, we still receive issues about cache issue due to merchant not aware about doing module upgrade in production should be done in maintenance mode to avoid concomitant cache access...

@PrestaShop/prestashop-product-team Please ensure this will be handled in 1.7.8
This cause issue with many modules ! Not only ps_mbo but modules from Addons too.

**Comment by LouiseBonnard** [comment]
100% okay for the 1.7.8! @TristanLDD, is it only the wording you need to design those warning modals? If yes, I let you add the right labels and coordinate with @Julievrz, thanks!

**Comment by Julievrz** [comment]
"Are you sure you want to upgrade this module? We advise you not to upgrade a module without first testing it on maintenance mode to avoid any cache issues." in _Admin.Modules.Notifications_

What do you think @LouiseBonnard, @Matt75 ?

**Comment by Julievrz** [comment]
@TristanLDD @Matt75 Following our meeting, here is the updated wording for each situation:

1. The user is NOT on maintenance mode : 

"Are you sure you want to upgrade this module? We strongly advise you to upgrade the module on maintenance mode to avoid any cache issues." in Admin.Modules.Notifications

With 3 exit buttons : 

"Upgrade anyway"  in _Admin.Actions_
"Go to maintenance page" in _Admin.Actions_
"Cancel"  in _Admin.Actions_

2. The user is already on maintenance mode:

"Are you sure you want to upgrade this module?" in Admin.Modules.Notification

With 2 exit buttons:

"Upgrade" in _Admin.Actions_
"Cancel" in _Admin.Actions_

**For bulk action:** 

The user is NOT on maintenance mode :

"Are you sure you want to upgrade these modules? We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues." in Admin.Modules.Notifications

With 3 exit buttons :

"Upgrade anyway" in Admin.Actions
"Go to maintenance page" in Admin.Actions
"Cancel" in Admin.Actions

The user is already on maintenance mode:
"Are you sure you want to upgrade these modules?" in Admin.Modules.Notification

With 2 exit buttons:

"Upgrade" in Admin.Actions
"Cancel" in Admin.Actions


@LouiseBonnard fyi

**Comment by TristanLDD** [comment]
Hello ! 

Design is available here: https://invis.io/RDZ7QTTK8NY
