### ISSUE TITLE
Transplant module error

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#14037]
**Describe the bug**
Transplanting modules produces weird results.  Thanks to @zuk3975 for finding this issue. 

**To Reproduce**

1. Go to 'IMPROVE > Design > Positions'
1. Click on 'Transplant' at the top right corner
1. In Modules input select `Banner` and save.
1. See fun stuff

![Screenshot from 2019-05-31 14-19-22](https://user-images.githubusercontent.com/15143151/58702772-63e55480-83af-11e9-94db-47b322810d6e.png)
![Screenshot from 2019-05-31 14-20-17](https://user-images.githubusercontent.com/15143151/58702776-66e04500-83af-11e9-927e-4aefb183db3b.png)

Depending on the module, you can get different results. If you were to choose `Customer "Sign in" link` when transplanting module, you would get fatal error in every BO page:

![Screenshot (2)](https://user-images.githubusercontent.com/15143151/58702916-c8081880-83af-11e9-8316-cf69c77e4ba2.png)

**Additionnal information**
PrestaShop version: develop (maybe 1.7.6.x)
PHP version: n/a

**Comment by khouloudbelguith** [comment]
Hi @sarjon,

I have the same issue with PS1.7.6.0beta1, 1.7.6.x branch & PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/58703478-be2ae900-83a0-11e9-963e-c5f1b7834d2d.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by zuk3975** [comment]
With the banner module maybe it is behaving as expected? because you can select a hook on which you want to show the banner and it shows it, but for sure there is something wrong with that :smile: ,  especially when :warning:  **I can't see any possibility to revert those module-hook changes using user interface** (except resetting the module)...
![Screenshot from 2019-05-31 15-24-21](https://user-images.githubusercontent.com/31609858/58707114-a6615e00-83bc-11e9-9f82-53e00d46c790.png)

**Comment by matks** [comment]
@marionf @colinegin we have discovered that although Module page has been migrated, the "Transplant a module" button is not migrated

So we're going to migrate it. Maybe we can use this opportunity to improve this button behavior with some restrictions to avoid the crazy stuff demonstrated by @zuk3975 up there ?

**Comment by colinegin** [comment]
@MatShir wdyt ?
If i'm correct, this page had not been anticipated (another one...), so you should add it to our document and change the roadmap according to it.

**Comment by matks** [comment]
@MatShir 🆙

**Comment by MatShir** [comment]
>**I can't see any possibility to revert those module-hook changes using user interface** (except resetting the module)...
> ![Screenshot from 2019-05-31 15-24-21](https://user-images.githubusercontent.com/31609858/58707114-a6615e00-83bc-11e9-9f82-53e00d46c790.png)

@zuk3975 It should be displayed on the position page list and then you can unhook it if am i right. But you need to know the module name or the hook name to find it.

@matks Can we differentiate Front office modules and Back Office modules?

**Comment by marionf** [comment]
@hibatallahAouadni This issue may be fixed, could you re-test it ?

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

Following these steps:

1. Go to 'IMPROVE > Design > Positions'
2. Click on 'Transplant' at the top right corner
3. In Modules input select Banner and choose **`displayAdminAfterHeader`** as **Transplant to**
4. You will get these results and that's normal:

![image](https://user-images.githubusercontent.com/23308427/147949308-f3f1aff8-a628-4bb6-ad8c-5b9c20df0feb.png)

![image](https://user-images.githubusercontent.com/23308427/147949300-c1f613a8-a3ee-46c9-9300-7eb5f8087f59.png)

5. If you choose **`displayCustomerLoginFormAfter`** as **Transplant to**:

![image](https://user-images.githubusercontent.com/23308427/147949330-bb488333-facd-4b06-8a59-b0a6dfc47f40.png)

6. Every BO page is ok and in FO, you get this result and that's normal:

![image](https://user-images.githubusercontent.com/23308427/147949383-1ba505d6-10a6-4110-bc51-5be22015ec96.png)

Could you please check my steps if I miss something and feedback.

Thanks!

**Comment by MatShir** [comment]
LTGM ! thanks @hibatallahAouadni
