### ISSUE TITLE
Redirect to Default Category when disabling product not working

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#14036]
the newly added feature of prestashop 1.7.5.0 is not working in my installation

http://build.prestashop.com/news/prestashop-1-7-5-0-available/

"When a product is taken offline, by default visitors will be redirected to the product’s main category, instead of a “Not found” page."

I assume this should happen, just with disabling the product!?

PrestaShop version: 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @tom75,

It is OK in my side, I checked it with PS1.7.5.2 & PS1.7.6.0beta1
>When a product is taken offline, by default visitors will be redirected to the product’s main category, instead of a “Not found” page.

In the BO => product page => SEO table, by default: Redirection when offline => Permanent redirection to a category (301)

![image](https://user-images.githubusercontent.com/16067358/58695270-e0b30700-838c-11e9-8b00-d059d7d83dff.png)

Thanks to check this option in your side & feedback..

**Comment by decom-media** [comment]
Well, yes, I was happy about this feature already since I did read the first time that it will be included in 1.7.5 – but, since I did update to that version and now already 1.7.5.1 it never happened to include that default redirect.

Manual redirections are working fine, I did use that already many times, but, the default redirect is not working

I am using a multishop, maybe this is the reason? I did not update to 1.7.5.2 till now, just want to wait for the 1.7.6.0 update, but, that should not change anything I think.

**Comment by khouloudbelguith** [comment]
@tom75, so when you create a new product => enable it => preview this product => disable it => in the FO, there no redirection to the main category?
Did you make an upgrade from PS1.7.4 to 1.7.5?
Thanks!

**Comment by decom-media** [comment]
Not exactly, product disabling without adding manual redirect in the seo tab is just causing a “not found” instead of the proper redirect – BUT, it seems there is a difference for products which were created already before that update and newly created products (I was just disabling old sold out products till now, of course):

I did create now a new test product and it seems that there is the default permanent 301 already the default setting and the behavior is like it should be, but, for products which were created before the default setting is “no redirect” and therefore it is not working (was thinking that this is the default behavior now with all products) – however, I can accept to handle all the old products manually if there is no global setting for this to change all products.

BUT – in my testing I realized now, that there is another problem with the disabling of products --> test with newly created product and also “old” product is the same behavior: new product created, enabled, then product disabled and it is being redirected to the main category – everything fine – BUT, when I enable the product again, the redirect is still in place and the product is no longer available to be opened as of the redirect which is still in place. Same behavior with “old” products when I change the seo settings manually to redirect and disable the product – all fine, but, not possible to open the product after enabling, as the redirect is still in place and not removed.

I did make an upgrade from 1.7.4 to 1.7.5, but cannot tell you which minor version of 1.7.4 was the last one I did have installed (pretty sure it was the last available one, as I normally update all versions)

**Comment by khouloudbelguith** [comment]
Hi @tom75,

About old products, Redirection page is not set to permanent redirection to a category, this is normal behavior.
Because old products are just saved with the 404 "Not Found" page, so you need to change it manually.

About the second issue, it is a cache issue, it is, in fact, a cache navigator.
After enabling the product, try to open this product in a new incognito tab, there is no redirection.

Thanks!

**Comment by decom-media** [comment]
Hello,

Ok, understand the behavior now – could not find any information about it before anywhere about the exact behavior.

Also, the second topic, you are right, in another incognito tab it seems ok.

Thanks for the quick response.

Thomas

**Comment by khouloudbelguith** [comment]
@tom75, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
