### ISSUE TITLE
Impossible add custom form field

### ISSUE THREAD

**Issue by ElderTugBoat786** [PrestaShop/PrestaShop#14042]
**Describe the bug**
I have attemp to add a custom field in PS sign-up form but when i submit form i get this error:

(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "isCustomerName" of class "Validate".
--
in AbstractForm.php line 142

**To Reproduce**

1. Add to ps_customer this field:
```sql
     ALTER TABLE ps_customer ADD COLUMN pec VARCHAR(250);
     ALTER TABLE ps_customer ADD COLUMN spid VARCHAR(250);
``` 

2. Add field in CustomerFormatter.php file 
```php
        $format['pec'] = (new FormField)
            ->setName('pec')
            ->setLabel(
                $this->translator->trans(
                    'Pec', [], 'Shop.Forms.Labels'
                )
            )
        ;

        $format['spid'] = (new FormField)
            ->setName('spid')
            ->setLabel(
                $this->translator->trans(
                    'Spid', [], 'Shop.Forms.Labels'
                )
            )
        ;
``` 
3. add two variable at file Customer.php
```php
    public $pec;
    public $spid;
``` 
    and add this two field at $definition array
```php
   'pec' => array('type' => self::TYPE_STRING,  'validate' => 'isEmail', 'size' => 255),
   'spid' => array('type' => self::TYPE_STRING,  'validate' => 'isCustomerName', 'size' => 255
``` 

4. If i attemp to submit new form I get the error

**Pastebin File link**
[CustomerFormatter.php](https://pastebin.com/adRfK9g0)
[Customer.php](https://pastebin.com/3msEfe0i)

**Screenshots**

![form_custom_field](https://user-images.githubusercontent.com/38555796/58708867-2ab1e200-83b9-11e9-9f44-6a776481a78f.PNG)
![form_custom_field_error](https://user-images.githubusercontent.com/38555796/58708868-2ab1e200-83b9-11e9-9f76-198ef252ea2c.PNG)

**Additionnal information**
*I used a docker prestashop version
PrestaShop version: 1.7.5.1
PHP version:  PHP 5.6.40 (cli) (built: Jan 23 2019 00:10:05)
Container uname -a command: Linux d357a0592bfd 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux

**Comment by matks** [comment]
Hi, the function `Validate::isCustomeName()` has been introduced in PS 1.7.5.2 in order to mitigate spam attacks. You can see it here : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L166

So if you use PS 1.7.5.1 this error is logical. You must update to 1.7.5.2 to be able to use it

**Comment by khouloudbelguith** [comment]
Hi @ElderTugBoat786,

You can use the `additionalCustomerFormFields` hook, you can add a new field to customer registration form from the Front office.
Here's a demo module
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/3241446/mymodule.zip)
You can use Overriding to “override” class files and controller files. PrestaShop’s ingenious class auto-loading function makes the “switch” to other files fairly simple. Thanks to PrestaShop’s fully object-oriented code, you can rely on object inheritance to modify and add new behaviors, using the properties and methods of the various existing classes.

Thanks for your understanding!

**Comment by ElderTugBoat786** [comment]
> Hi, the function `Validate::isCustomeName()` has been introduced in PS 1.7.5.2 in order to mitigate spam attacks. You can see it here : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L166
> 
> So if you use PS 1.7.5.1 this error is logical. You must update to 1.7.5.2 to be able to use it

**Comment by ElderTugBoat786** [comment]
> Hi @ElderTugBoat786,
> 
> You can use the `additionalCustomerFormFields` hook, you can add a new field to customer registration form from the Front office.
> Here's a demo module
> [mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/3241446/mymodule.zip)
> You can use Overriding to “override” class files and controller files. PrestaShop’s ingenious class auto-loading function makes the “switch” to other files fairly simple. Thanks to PrestaShop’s fully object-oriented code, you can rely on object inheritance to modify and add new behaviors, using the properties and methods of the various existing classes.
> 
> Thanks for your understanding!

Thanks for the module, It's possible set up the field position in the form?

**Comment by ElderTugBoat786** [comment]
> Hi, the function `Validate::isCustomeName()` has been introduced in PS 1.7.5.2 in order to mitigate spam attacks. You can see it here : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L166
> 
> So if you use PS 1.7.5.1 this error is logical. You must update to 1.7.5.2 to be able to use it

Thanks for the explanation!

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13119 to allow hookAdditionalCustomerFormFields and AddressFormFields to modify fields positions.
It is added in the next major release PS1.7.7.

Thanks!

**Comment by reanim8ed** [comment]
There is similar hookActionAdminCustomersFormModifier hook which enables to add fields to the customer form in the backoffice. But to save this value, the Customer class needs to be overriten. Is there a way to add new fields to the field definitions on that class from the module?

**Comment by matks** [comment]
> But to save this value, the Customer class needs to be overriten. Is there a way to add new fields to the field definitions on that class from the module?

No, you can save this value anywhere you want. It could be in another SQL table (example: `ps_customers_extra`), it could be in a file, you are free to store it wherever you want 😉 . Usually we consider a new SQL table to be a good solution as you are sure another module will not mess with your data.

However if you want to store the data from the extra fields in the customer database, then indeed you have to override the Customer class.
