### ISSUE TITLE
Preference products

### ISSUE THREAD

**Issue by Evgaid** [PrestaShop/PrestaShop#14047]
Multistore issue, Any change of preference products in shop, change advanced_stock_management and depends_on_stock to 0

Prestashop 1.6.1.23
Php 5.6

**Comment by khouloudbelguith** [comment]
Hi @Evgaid,

Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by Evgaid** [comment]
Hello,
Any changes in Preferences-Products, for examples number of products  in particular shop change change advanced_stock_management and depends_on_stock to 0 if I change preference of products in All shop it is work normally.

**Comment by khouloudbelguith** [comment]
@Evgaid, I did not manage to reproduce the issue with PS1.7.6.0beta1.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!

**Comment by Evgaid** [comment]
It is critical bug for Multistore.  I have 5000 products in 5 store, after change number of products or Cataloge Mode all of them 0 in particular shop.
I need to make program to change advanced_stock_management and depends_on_stock to 1.
Thank you for understanding and patience

**Comment by khouloudbelguith** [comment]
@Evgaid, in my case it is OK with PS1.6.1.24.
I attached a video record
https://drive.google.com/file/d/1gKnRk8w0TSOnaCGdN73In7_-uRMRSjy3/view
Thanks!

**Comment by Evgaid** [comment]
I will make video about 14-30 European time, i need to go to my localhost, I do not want to repeat on active shop one more time. It killed a lot of my time previous time.

**Comment by khouloudbelguith** [comment]
@Evgaid, Thanks!

Waiting for your video record.

**Comment by Evgaid** [comment]
Sorry, it takes a bit time. Never did video before. https://drive.google.com/open?id=1_ONphbzRwGjPQ-bxsbVLxAM5zra7Yn81

**Comment by khouloudbelguith** [comment]
@Evgaid, thanks for your feedback.
Sorry, but I did not manage to reproduce the issue with PS1.6.1.24.
https://drive.google.com/file/d/1ZnjcPYciHALwqrQpRhj2cjntqWxhVR5S/view
It is OK.
Thanks!

**Comment by Evgaid** [comment]
Share available quantities to sell  - Yes or No in your Multistore settings?

**Comment by Evgaid** [comment]
Shop group settings

**Comment by khouloudbelguith** [comment]
@Evgaid, it is NO.
Thanks!

**Comment by Evgaid** [comment]
Thank you. I will compare clean installation of Prestashop 1.6.1.24 with my Db. Something wrong.

**Comment by khouloudbelguith** [comment]
@Evgaid, thanks!

**Comment by Evgaid** [comment]
Hello,

I checked it in Completely clear new installation, only enable Multistore
mode and add 1 shop. I checked your previous video carefully and found
problem. First of all, you need to change product to advanced stock
management (in product menu of each product), add quantity of product in
stock menu,and you  will get the same mistake in preference product like me.

https://drive.google.com/open?id=1_ONphbzRwGjPQ-bxsbVLxAM5zra7Yn81

Best Regards,

Evgeny



пн, 3 июн. 2019 г. в 16:17, khouloudbelguith <notifications@github.com>:
