### ISSUE TITLE
Error 404 account page

### ISSUE THREAD

**Issue by frenchqwerty** [PrestaShop/PrestaShop#14046]
Hi,

I have an issue with account page. When I'm trying to access to the page, I'm getting an error 404...

URL Friendly is enable, debug mode too. I have this log : `Notice: Undefined index: controller in Dispatcher.php on line 1049`

How can I fix it ?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @frenchqwerty,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by frenchqwerty** [comment]
Hi,
This issue is solved. The URL Rewrite was broken.
I've remove the rewrite and it's work.

**Comment by khouloudbelguith** [comment]
@frenchqwerty, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
