### ISSUE TITLE
Solved - Wrong H1 tag in active-filters.tpl of the ps_facetedsearch module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14044]
Hi
it is necessary to replace the the H1 in active-filters.tpl of the ps_facetedsearch module
with a "div" or "p" tag to obtain

`<div class="h6 {if $activeFilters|count}active-filter-title{else}hidden-xs-up{/if}">{l s='Active filters' d='Shop.Theme.Global'}</div>`

it is wrong to use a H1 tag for "Active filters"

can you fix this bug with the next 3.0.3 version ?

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/58724349-9d808480-83dc-11e9-9cf9-a4b17bb1db34.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0
module version: 3.0.2

**Comment by PierreRambaud** [comment]
Since it's in a section, we can have multiple h1.
And for your information, this came from a very very old PR: https://github.com/PrestaShop/PrestaShop/pull/4895

**Comment by Maofree** [comment]
hi
yes you said me the same thing in the past for another thing
but tell me which kind of important information is "Active filters" ?
what is the sense to use a H1 for this type of information?
the title tags should be used for important informations like product name or about product featurs or manufacturers ... but not for "new product" or "special prices" or texts like this
What is the point in telling search engines that these phrases are important to consider?

**Comment by Tomskor** [comment]
@maofree exactly, we change that manually, this should be h4 or h5, h6

**Comment by Maofree** [comment]
hi
why should it be a title? it is not a title, so it is possible to use "p", "div" or a "span" tag
for me it should give less importance to this type of sentences, they have no content or even keywords, so it is not necessary for search engines to consider them important

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
I have no idea, it's here since a very long time.
And with a good properties names, actives filters is important for its own section. 
But I'm not an seo export and I think instead of Google, no one know what's really good for seo ^^. 

Let's check with @colinegin, @marionf and others people from Product team to define what needs to be done. 
And we'll be able to change it for the Core and the module :)

**Comment by colinegin** [comment]
We have discussed about it with a SEO agency which agrees with your recommendations.
I let @marionf decide how to prioritize this issue with others in the backlog for faceted search.

Thanks !
