### ISSUE TITLE
Combination::deleteAssociations deletes all cart products without attributes if id not set

### ISSUE THREAD

**Issue by kazeno** [PrestaShop/PrestaShop#14041]
From time to time the contents of most of the shopping carts in our store would be cleared without any apparent reason, affecting sales for a few days everytime it happened (probably from disgruntled customers abandoning the site), and breaking the functionality of some modules that didn't expect an order's cart to be empty.

After putting loggers around any function that might edit a cart's contents, it turned out that the Combination::deleteAssociations function doesn't check if the id is set before removing all cart products with the id_product_attribute corresponding to that id, which means that it will remove all products without combinations if called incorrectly, like this:

    $combination = new Combination();
    $combination->deleteAssociations();

In our case it turned out that the AdvancedPack5 module was the one incorrectly calling this function. However, the interface should not allow this incorrect usage as the effect is completely unintended and hard to debug. Instead a check needs to be made inside Combination::deleteAssociations and the queries that remove data should only be called if the id is set (i.e. does not evaluate to 0).

PrestaShop version: 1.5 (all), 1.6 (all), 1.7 (all) 
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kazeno,

Thanks for your report.
Have you tried to contact the module author about this issue?

Thanks!

**Comment by kazeno** [comment]
I haven't contacted them because it's a very difficult issue to debug, we have about 700000 visits per month and it only happens once every 2 or 3 months, and from our logs I can see that the module creates and deletes a lot of combinations all the time, so there must be a condition somewhere that occasionally will instantiate a Combination without id.

Besides, it's a very easy mistake to make by any module developer, and a completely unintended consequence of the Prestashop API. The solution is simple enough so I'll try to make a pull request, it shouldn't even break any tests.

**Comment by khouloudbelguith** [comment]
@kazeno, thanks for these clarifications.
Could you please provide me the AdvancedPack5 module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by kazeno** [comment]
> @kazeno, thanks for these clarifications.
> Could you please provide me the AdvancedPack5 module to test it.
> This is a public space.
> You can provide me the module by email.
> My address mail: [khouloud.belguith@prestashop.com](mailto:khouloud.belguith@prestashop.com)
> Let's be safe!
> 
> Thanks!

I tried sending it to you but gmail blocked it as it contains "evil javascript". Then again it would be really difficult to replicate with that module anyway for the reasons I've outlined above. I've made a pull request with the Prestashop Core fix so the dev team can evaluate it, should be easy enough to merge.

**Comment by khouloudbelguith** [comment]
@kazeno, thanks for these clarifications & for the fix.
