### ISSUE TITLE
paypal bug 

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#14048]
hello,

i belive there is a bug in latest paypal addon, it has an empty cart when used on product pages... and reports empty cart... tested on prestashop 1.6

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
