### ISSUE TITLE
Bug with PrestaShop/blockspecials

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#14045]
**Describe the bug**
Hi, on PS 7.5.1 when you have the special promotion module activated, this one is showing item's promotions that ar past of date (disabled) on the frontend.

To avoid been shown, we had to erase the discount on the catalog -> discount -> catalog price rules tab.

**Comment by khouloudbelguith** [comment]
Hi @msautral,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 & the ps_specials module v1.0.1.
I attached a video record
https://drive.google.com/file/d/1fJSP5WOcMgcywoKPz46Uy1QKqV8VCfFP/view
Thanks to check & feedback.

**Comment by msaustral** [comment]
Hi @khouloudbelguith, nice to meet you.
We made a discount by making a price rule by catalog with a filter by category and brand, with a starting and end date.

the module show the special offer but when the end date comes the module still show the products as in offer. thank you

**Comment by khouloudbelguith** [comment]
@msautral, I created a catalog price rule from `2019-05-02 00:00:00` to `2019-06-04 12:06:00`

From 2019-06-04 12:05:00, I tried to reload the prices drop page, if the end date comes, those products are not displayed anymore
![image](https://user-images.githubusercontent.com/16067358/58871328-b24d6880-86b9-11e9-9651-05c8508e8b7a.png)
https://drive.google.com/file/d/1ndZUCUMSqubRAhWlb8HORKLWkUPZV4z5/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @msautral,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by msaustral** [comment]
hi i had again the same issue, but if you can not reproduce it, there is no way to fix it

**Comment by msaustral** [comment]
Hi last week we erase a product that has a discount and mark as an offer and it was still showing on the front end on the special offer until we clean the cache.
