### ISSUE TITLE
URL in SEO preview is not correct when the product is not active

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14054]
Hello,

We have discovered that the URL is not exact in the SEO preview when the product is not active (newly created or disabled product).
The URL in FO is : 
![image](https://user-images.githubusercontent.com/35263827/60812031-e1f80080-a190-11e9-8c6c-1ecf725b2760.png)

But in the SEO preview, it is different, see below for more details :

![image](https://user-images.githubusercontent.com/35263827/58803091-f46da000-860e-11e9-87ca-6d292a958dc7.png)

**Comment by matks** [comment]
Can you tell us what is wrong with this URL, what it should be instead ?

**Comment by PierreRambaud** [comment]
@matks She's talking about the query params `adtoken=...`  which not not appear in the preview

**Comment by colinegin** [comment]
Exactly, thanks for replying @PierreRambaud. 
This is the URL I have on FO : 
![image](https://user-images.githubusercontent.com/35263827/60811933-9e04fb80-a190-11e9-819a-82576e9f0936.png)
But the SEO preview also displays query params adtoken=....

**Comment by PierreRambaud** [comment]
Should be fixed with #14530
