### ISSUE TITLE
Highlight element in dropdown menus of the product page when using keyboard

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14052]
**Is your feature request related to a problem? Please describe.**
Several menus in the product page have dropdown items or autosuggestions - when selecting items with a mouse, the items are highlighted on hover. But when using the keyboard to select items, there are no highlights.

**Example**
When creating a combination in product page > Combination tab,
In the attributes field, as you type autosuggestions appear
When navigating through these suggestions with your mouse cursor, the suggestions are highlighted, but not when navigating with your keyboard arrows.

**When using the mouse:**
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/47456895/58794388-57a00800-85f8-11e9-8638-6baa4d16e10d.gif)

**When using the keyboard:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47456895/58794222-faa45200-85f7-11e9-9fe7-cb7f34096499.gif)

**Describe the solution you'd like**
Having blue highlit on menu items when navigating through them with the keyboard

List of impacted menus:

- [x]  Attributes menu in the combination tab (example above)

- [ ]  Categories menu in the Basic Settings tab

![capture d'écran_1921](https://user-images.githubusercontent.com/13449658/63594357-8950bb80-c5b6-11e9-95fd-1b3cbf1d11e6.png)

- [x]  Search customers when adding a specific price in the pricing tab

![capture d'écran_1920](https://user-images.githubusercontent.com/13449658/63594330-73db9180-c5b6-11e9-962d-d4b4b8c3168f.png)

- [x] Search a product to add to the pack in the basic settings tab

![capture d'écran_1922](https://user-images.githubusercontent.com/13449658/63594460-c61cb280-c5b6-11e9-8f68-5ed200327eaf.png)

- [x] Search a related product in the basic settings tab

![capture d'écran_1923](https://user-images.githubusercontent.com/13449658/63594540-f82e1480-c5b6-11e9-8db7-6c6b610f9c5d.png)

**Additional context**
Prestashop 1.7.5.2

**Comment by NeOMakinG** [comment]
Not fixed for every inputs, not closable yet

**Comment by NeOMakinG** [comment]
The category autocomplete doesn't use the same component as the whole page, I think it should be refacto for the next version @matks and use the same everywhere

**Comment by marionf** [comment]
@NeOMakinG I created a new issue for the categories drop-down: https://github.com/PrestaShop/PrestaShop/issues/20331
