### ISSUE TITLE
SEO information metatags title no updated in multistore for ALL shops

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#14056]
I have multishop activated and recently noticed that when I do an update on a product from my mainstore ( ALL SHOPS ). The meta title and meta description of the mainstore is updated, but not for SHOP 2, 3 etc

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1Ih1LbFOIAgFde9dRHutXIItVZosswqor/view
Thanks to check & feedback

**Comment by 01park** [comment]
Hi,

I have been doing some testing and the problem is probably because I'm using the module SEO PRO. In prestashop 1.6 this was working different than in 1.7.

**Comment by khouloudbelguith** [comment]
Hi @01park,

As it's not the default module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
