### ISSUE TITLE
Products not displayed in "All shops" context

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#14059]
**Describe the bug**
All products created are not displayed when "All shops" context is selected

**To Reproduce**
1. Create a multistore
2. Select a store **other** than store with ID 1
3. Create a product
4. Return to product page
5. Select "All shops" context
6. Previous product is not displayed

**Additionnal information**
PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9613
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9613
