### ISSUE TITLE
Undefined index: dsn_config

### ISSUE THREAD

**Issue by elviraprint** [PrestaShop/PrestaShop#14057]
**Describe the bug**
i m on my home page so everything looks fine i can open pages, but as soon as i want to go on a product page to make an order or one page of the menu, i got this message from the mode debug. i didnt touch anything so i dont understand where the error come from.

**To Reproduce**
1. Go to '.the home page..'
2. Click on '.a product...'
3. Scroll down to '
...'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
<img width="1407" alt="Capture d’écran 2019-06-03 à 16 00 30" src="https://user-images.githubusercontent.com/51324358/58807773-03f1e680-8619-11e9-9c29-f83447ebd69c.png">

**Additionnal information**
PrestaShop version: N/A 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @elviraprint,

You have an issue with your module `productdesigner`
![image](https://user-images.githubusercontent.com/16067358/58808671-61366980-8612-11e9-9d22-e7505cbe6d88.png)
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by elviraprint** [comment]
ok i just sent a mail to prestashop addons thank you,

can you have a look on this issue ? 

is that the same issue ? this one come when i click on the menu

<img width="1258" alt="Capture d’écran 2019-06-03 à 16 59 59" src="https://user-images.githubusercontent.com/51324358/58811949-14a65a80-8621-11e9-87a0-46a45bca835c.png">

**Comment by khouloudbelguith** [comment]
@elviraprint, this issue also, is not a PrestaShop core bug.
You have an error in the class `Block.php`, you need to find this class is added by which module.

Thanks!

**Comment by PierreRambaud** [comment]
@elviraprint This issue will be fixed this week, it came from the facetedsearch module.

**Comment by elviraprint** [comment]
Ok will you send me a message as soon as it is fixed ?
Thats really make me in trouble my all website is compromised
