### ISSUE TITLE
1-Click Upgrade Error when upgrading database (1.7.3.0 -> 1.7.5.2)

### ISSUE THREAD

**Issue by AminPersis** [PrestaShop/PrestaShop#14068]
1-Click Upgrade Error when upgrading database (1.7.3.0 -> 1.7.5.2)
--------------------------------------------------------

I tried several times, but every time I have the same issue. Everything seems to go well until it reaches the upgrading database, then it fails.

Here's the Error log:
---------------------------------------------------------------------------------------
[INTERNAL] /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php line 102 - Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "mailer_user". #0 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('mailer_user') #1 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('mailer_user') #2 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%mailer_user%', Array) #3 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%mailer_user%', Array) #4 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue(Array, Array) #5 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue(Array) #6 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #7 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(141): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #8 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(788): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #9 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(637): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #10 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #11 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #12 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #13 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #14 /home/karizmat/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #15 /home/karizmat/public_html/admin5785gnc99/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #16 {main}
---------------------------------------------------------------------------------------
PrestaShop version: 1.7.3.0
---------------------------------------------------------------------------------------
Database information:

MySQL version: 10.1.38-MariaDB-cll-lve
MySQL engine: InnoDB
MySQL driver: DbPDO
---------------------------------------------------------------------------------------
Server information:

Server information Linux #1 SMP Thu Dec 6 05:11:00 EST 2018 x86_64
Server software version: LiteSpeed
PHP version: 7.0.33
Memory limit: 1G
Max execution time: 6000
---------------------------------------------------------------------------------------
Sorry, I don't have a "php error log" and despite reading some articles, still not able to create it.
And I read similar issues some people had but didn't solve my problem, so I had to submit a bug report.

I'm a beginner and I don't understand what this log is saying.
I would appreciate any help and tips to solve this issue.
I've been trying to upgrade for a long time since 1.7.3.0 and every time a new version comes out, I fail to upgrade my website.

Regrads
Amin
---------------------------------------------------------------------------------------

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A
![1-Click Upgrade Error](https://user-images.githubusercontent.com/51361765/58868958-01999600-86c6-11e9-9cd2-7b7dbdc447c4.jpg)
![php extensions](https://user-images.githubusercontent.com/51361765/58868972-065e4a00-86c6-11e9-9edd-b761e029a957.jpg)

**Comment by khouloudbelguith** [comment]
Hi @AminPersis,

In your file /Project_Folder/app/config/parameters.php, did you defined the `mail_user`?
For example `mailer_user' => NULL,`
Thanks to check & feedback.

**Comment by AminPersis** [comment]
Hello khouloudbelguith,

Thanks for your quick reply.

No, I didn't edit any files directly, I just configured everything from backoffice, and I'm using PHP's mail() function, because I had an issue with SMTP.

I checked the file and realized I don't even have a "mail_user" there.

This is my parameters.php:


<?php return array (
  'parameters' => 
  array (
    'database_host' => 'localhost',
    'database_port' => '',
    'database_name' => '*******',
    'database_user' => '*******',
    'database_password' => '*******',
    'database_prefix' => 'ps_',
    'database_engine' => 'InnoDB',
    'mailer_transport' => 'smtp',
    'mailer_host' => '127.0.0.1',
    'secret' => '5YAWupBqwwLLrPffsdvyniXJszVkIqHIkgPLH4rf6KnozqT78iSkMtMf',
    'ps_caching' => 'CacheMemcached',
    'ps_creation_date' => '2017-11-23',
    'locale' => 'fa-IR',
    'cookie_key' => '0AAmTOwxRJ0L0z8LRdSKDsQo8LWIDxd2b7HwwzPyuOzu2XTXXfbIMVWU',
    'cookie_iv' => 'jaRzxO3h',
    'new_cookie_key' => 'def00000c4dd0932d156c011ecb2c11a8e5ee3bae675ce4f1eadb9a59f22ad0c43192cc6a17f3b53618b6edb9735d19990f5df0908ea9ea1f0ab2ca0a6cd0dbf8e1ee8c3',
    'ps_caching_system' => 'CacheMemcached',
    'ps_cache_enable' => 'true',
  ),
);



It says 'mailer_transport' => 'smtp', but I'm using php mail and it's working properly. Please look at attachement.

What should I do? Should I change it? and How?

Regards
Amin
![E-mail](https://user-images.githubusercontent.com/51361765/58873119-3f022180-86ce-11e9-994d-1e0e6396c84b.jpg)

**Comment by AminPersis** [comment]
![parameters](https://user-images.githubusercontent.com/51361765/58873271-a7e99980-86ce-11e9-9432-a12bf4955c8d.jpg)

**Comment by khouloudbelguith** [comment]
@AminPersis, thanks to add this line `'mailer_user' => NULL,`in your file app/config/parameters.php.
uou need to replace this 

`array ( 'database_host' => 'localhost', 'database_port' => '', 'database_name' => '*******', 'database_user' => '*******', 'database_password' => '*******', 'database_prefix' => 'ps_', 'database_engine' => 'InnoDB', 'mailer_transport' => 'smtp', 'mailer_host' => '127.0.0.1', 'secret' => '5YAWupBqwwLLrPffsdvyniXJszVkIqHIkgPLH4rf6KnozqT78iSkMtMf', 'ps_caching' => 'CacheMemcached', 'ps_creation_date' => '2017-11-23', 'locale' => 'fa-IR', 'cookie_key' => '0AAmTOwxRJ0L0z8LRdSKDsQo8LWIDxd2b7HwwzPyuOzu2XTXXfbIMVWU', 'cookie_iv' => 'jaRzxO3h', 'new_cookie_key' => 'def00000c4dd0932d156c011ecb2c11a8e5ee3bae675ce4f1eadb9a59f22ad0c43192cc6a17f3b53618b6edb9735d19990f5df0908ea9ea1f0ab2ca0a6cd0dbf8e1ee8c3', 'ps_caching_system' => 'CacheMemcached', 'ps_cache_enable' => 'true', ), ); `

by this

`array ( 'database_host' => 'localhost', 'database_port' => '', 'database_name' => '*******', 'database_user' => '*******', 'database_password' => '*******', 'database_prefix' => 'ps_', 'database_engine' => 'InnoDB', 'mailer_transport' => 'smtp', 'mailer_host' => '127.0.0.1','mailer_user' => NULL, 'secret' => '5YAWupBqwwLLrPffsdvyniXJszVkIqHIkgPLH4rf6KnozqT78iSkMtMf', 'ps_caching' => 'CacheMemcached', 'ps_creation_date' => '2017-11-23', 'locale' => 'fa-IR', 'cookie_key' => '0AAmTOwxRJ0L0z8LRdSKDsQo8LWIDxd2b7HwwzPyuOzu2XTXXfbIMVWU', 'cookie_iv' => 'jaRzxO3h', 'new_cookie_key' => 'def00000c4dd0932d156c011ecb2c11a8e5ee3bae675ce4f1eadb9a59f22ad0c43192cc6a17f3b53618b6edb9735d19990f5df0908ea9ea1f0ab2ca0a6cd0dbf8e1ee8c3', 'ps_caching_system' => 'CacheMemcached', 'ps_cache_enable' => 'true', ), ); `

Thanks to check & feedback

**Comment by AminPersis** [comment]
@khouloudbelguith

Thanks for your help.
I did what you said and added 'mailer_user' => NULL, and then I used 1-Click upgrade. But again I have this error:

[INTERNAL] /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php line 102 - Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "mailer_user". #0 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('mailer_user') #1 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('mailer_user') #2 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%mailer_user%', Array) #3 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%mailer_user%', Array) #4 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue(Array, Array) #5 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue(Array) #6 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #7 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(141): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #8 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(788): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #9 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(637): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #10 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #11 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #12 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #13 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #14 /home/karizmat/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #15 /home/karizmat/public_html/admin5785gnc99/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #16 {main}

What should I do next?

Regards
Amin

**Comment by khouloudbelguith** [comment]
@AminPersis, what is the exact version `autoupgrade` did you use?
Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by AminPersis** [comment]
@khouloudbelguith

My 1-click upgrade module is up-to-date (v4.8.0)
Sure, I will clear the Cache now, and repeat the upgrade again.

Regards
Amin

**Comment by khouloudbelguith** [comment]
@AminPersis, thanks!
Waiting for your feedback!

**Comment by AminPersis** [comment]
@khouloudbelguith

Sorry for asking, but should I write 'NULL' instead of NULL. Isn't using ' sign important?

**Comment by khouloudbelguith** [comment]
@AminPersis, here's my file parameters.php
[parameters.php.txt](https://github.com/PrestaShop/PrestaShop/files/3252235/parameters.php.txt)
Thanks to check & feedback

**Comment by AminPersis** [comment]
Thank you so much, I'm going to try again

**Comment by khouloudbelguith** [comment]
@AminPersis, thanks!
Waiting for your feedback

**Comment by AminPersis** [comment]
@khouloudbelguith

Hello again, and sorry it took so long. My server was too slow and I couldn't do anything.

Now, I changed parameters.php as you said and the database was upgraded successfully. 
But I had another error at the final stage when just 1 module left to upgrade. 

Please see the error below and the attachment:

----------------------------------------------------------
[INTERNAL] /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 141 - RuntimeException: Failed to start the session because headers have already been sent by "/home/karizmat/public_html/modules/webmastersiteverification/webmastersiteverification.php" at line 456. #0 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(57): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #1 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenStorage/SessionTokenStorage.php(78): Symfony\Component\HttpFoundation\Session\Session->start() #2 /home/karizmat/public_html/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php(72): Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage->hasToken('https-ANONYMOUS...') #3 /home/karizmat/public_html/src/PrestaShopBundle/Service/Routing/Router.php(50): Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('ANONYMOUS_USER') #4 /home/karizmat/public_html/modules/welcome/OnBoarding/Configuration.php(97): PrestaShopBundle\Service\Routing\Router->generate('admin_product_n...') #5 /home/karizmat/public_html/modules/welcome/OnBoarding/OnBoarding.php(141): OnBoarding\Configuration->getConfiguration(Object(PrestaShopBundle\Service\Routing\Router)) #6 /home/karizmat/public_html/modules/welcome/OnBoarding/OnBoarding.php(57): OnBoarding\OnBoarding->loadConfiguration(Object(PrestaShopBundle\Service\Routing\Router)) #7 /home/karizmat/public_html/modules/welcome/welcome.php(75): OnBoarding\OnBoarding->__construct(Object(PrestaShopBundle\Translation\TranslatorComponent), Object(Smarty_Data), Object(Welcome), Object(PrestaShopBundle\Service\Routing\Router)) #8 [internal function]: Welcome->__construct() #9 /home/karizmat/public_html/src/Core/Foundation/IoC/Container.php(130): ReflectionClass->newInstance() #10 /home/karizmat/public_html/src/Core/Foundation/IoC/Container.php(163): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClassName('welcome', Array) #11 /home/karizmat/public_html/src/Core/Foundation/IoC/Container.php(176): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->doMake('welcome', Array) #12 /home/karizmat/public_html/src/Adapter/ServiceLocator.php(65): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->make('welcome') #13 /home/karizmat/public_html/classes/module/Module.php(1137): PrestaShop\PrestaShop\Adapter\ServiceLocator::get('welcome') #14 /home/karizmat/public_html/classes/module/Module.php(1116): ModuleCore::coreLoadModule('welcome') #15 /home/karizmat/public_html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(196): ModuleCore::getInstanceByName('welcome') #16 /home/karizmat/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(22385, 'welcome') #17 /home/karizmat/public_html/admin5785gnc99/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #18 {main}
--------------------------------------------------

I'm really thankful for your help and effort to solve my issue. It means a lot to me.

Regards
Amin

![1-Click Upgrade Error - 03](https://user-images.githubusercontent.com/51361765/58898458-4db6fb80-8703-11e9-8e3d-a0a885614080.jpg)

**Comment by AminPersis** [comment]
@khouloudbelguith

I managed to upgrade successfully to 1.7.5.2 today, by removing 2 modules (webmastersiteverification & Welcome) and the upgrade process completed without any errors, thanks to you.
![1-Click Upgrade successful](https://user-images.githubusercontent.com/51361765/58941388-57cd0e80-8784-11e9-89e5-9423936c45aa.jpg)

I just now have this issue of not showing my backoffice properly. I hear that it is a cache related issue, but I cleared the browser cache and it did not work.
Any suggestions? 

![Back Office](https://user-images.githubusercontent.com/51361765/58941554-b85c4b80-8784-11e9-8948-98bb24c157c4.jpg)

Best Regards
Amin

**Comment by AminPersis** [comment]
One more thing, my contact-us form does not show up.

**Comment by AminPersis** [comment]
> One more thing, my contact-us form does not show up.

I have re-installed the contact us module and it works fine again. 👍

**Comment by AminPersis** [comment]
@khouloudbelguith 
Hello,

I still have this issue in the backoffice and can't fix it. 
Any help is appreciated

![Back Office](https://user-images.githubusercontent.com/51361765/58981228-a3120c00-87da-11e9-8528-89416fa76577.jpg)

Best Regards
Amin

**Comment by khouloudbelguith** [comment]
@AminPersis, you just created a new issue.
Duplicate of #14095

**Comment by khouloudbelguith** [comment]
Duplicate of #14095
