### ISSUE TITLE
My products don't show in subcategory.

### ISSUE THREAD

**Issue by YourStylesas** [PrestaShop/PrestaShop#14062]
On my website www.shopyourstyle.it the products show only in the main category, and the subcategories seem empty but they aren't' in the backend. Can someone help me?

**Comment by khouloudbelguith** [comment]
Hi @YourStylesas,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - did you the module ps_facetedsearch? what is the exact version?

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by YourStylesas** [comment]
www.shopyourstyle.it

- Presta Shop 1.7.5.2 
- Linux #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64  - Apache
- PHP: 7.2.19
- MySQL: 5.5.60-MariaDB 

https://www.shopyourstyle.it/adminki/var/log/apache/index.php?controller=AdminDashboard&token=0273365682e44d4b5da33334d1cca3ae

**Comment by YourStylesas** [comment]
It was the ps_facetedsearch module. Thank you very much.

**Comment by khouloudbelguith** [comment]
@YourStylesas, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
