### ISSUE TITLE
Go back from 1.6.1.24 to 1.6.1.23

### ISSUE THREAD

**Issue by paintspec** [PrestaShop/PrestaShop#14073]
As we have multiple clients who cant register or complete their registration while ordering because of the restrictions made in 1.6.1.24 i want to get back to 1.6.1.23

How can i make the changes undone in 1.6.1.24

As the spam has stopped i want to get this function get undone. Multiple customers who want to order have 2 or more initials so someone who wants to register as h.w. noname gets a 500 error.

Anyone who can help me with this?

**Comment by khouloudbelguith** [comment]
Hi @paintspec,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
Thanks for your understanding!

**Comment by matks** [comment]
> As we have multiple clients who cant register or complete their registration while ordering because of the restrictions made in 1.6.1.24 i want to get back to 1.6.1.23
> 
> How can i make the changes undone in 1.6.1.24
> 
> As the spam has stopped i want to get this function get undone. Multiple customers who want to order have 2 or more initials so someone who wants to register as h.w. noname gets a 500 error.
> 
> Anyone who can help me with this?

Hi,

I dont think downgrading PS is possible 🤔however it should be as simple as undoing https://github.com/PrestaShop/PrestaShop/pull/13607/files#diff-83536235df8e0d38c1fdcfd4b2613a0c
Basically we use new Validation method `isCustomerName` for customer fields `firstname` and `lastname` so if you use again Validation method `isName` instead you should be fine

Also your customers should be able to register as "H. W. noname" : if you put 1 space after the "." it works
