### ISSUE TITLE
Cannot translate texts after creating a new language

### ISSUE THREAD

**Issue by rabtaray** [PrestaShop/PrestaShop#14074]
**Describe the bug**
After creating a new language Malagasy (iso code mg-mg), I cannot translate any texts, nothing happens.

**To Reproduce**
1. Go to 'International' / ''Translates
2. Click on 'Backoffice' for example to try to translate in Malagasy and choose the language 'Malagasy'
3. Scroll down to '....' : Select an item to translate and click on 
4. See error :: there's no error but nothing happens then I cannot continue.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: PHP 5.6.33-0+deb8u1

**Comment by OneDotIT** [comment]
Yes, you can add the Malagasy language in the BO through the localization option and then add it as a new language, afterwards you will start translating strings through the 'Modify translations' section.

My personal suggestion you join the Official translation project at https://crowdin.com/project/prestashop-official for the Malagasy language, and if it is not there, ask for the add up.

As for your case, I suspect that you are missing some required PHP drivers, have you checked the system requirements http://doc.prestashop.com/display/PS17/What+you+need+to+get+started ?

**Comment by mariem-abid** [comment]
Hi @rabtaray,

I manage to reproduce the issue with PS:1.7.5.2 and PS:1.7.6.0beta1
After creating the Malagasy language and go to  International => Translations => Modify translations=> select the Malagasy language => Modify
=> I get this error (See screenshot)
![Capture du 2019-06-07 15-49-14](https://user-images.githubusercontent.com/36841537/59112875-d61fe100-893b-11e9-8015-12471ec99004.png)

I’ll add this to the debug roadmap so that it’s fixed. 
Thanks!

**Comment by rabtaray** [comment]
> Hi @rabtaray,
> 
> I manage to reproduce the issue with PS:1.7.5.2 and PS:1.7.6.0beta1
> After creating the Malagasy language and go to International => Translations => Modify translations=> select the Malagasy language => Modify
> => I get this error (See screenshot)
> ![Capture du 2019-06-07 15-49-14](https://user-images.githubusercontent.com/36841537/59112875-d61fe100-893b-11e9-8015-12471ec99004.png)
> 
> I’ll add this to the debug roadmap so that it’s fixed.
> Thanks!

Hi Mariem, 
I met this error message before. Try to use iso code 'mg-mg' in lowercase. I got the message because I wrote mg-MG instead of.

**Comment by rabtaray** [comment]
> Yes, you can add the Malagasy language in the BO through the localization option and then add it as a new language, afterwards you will start translating strings through the 'Modify translations' section.
> 
> My personal suggestion you join the Official translation project at https://crowdin.com/project/prestashop-official for the Malagasy language, and if it is not there, ask for the add up.
> 
> As for your case, I suspect that you are missing some required PHP drivers, have you checked the system requirements http://doc.prestashop.com/display/PS17/What+you+need+to+get+started ?

Hi @OneDotIT ,
thank you for your response. I'll check all my configurations first.
I met the crowdin team a few days ago and they created the project at the following link [https://crowdin.com/project/prestashop-official/mg#](https://crowdin.com/project/prestashop-official/mg#) so I can start transllating PS.

**Comment by khouloudbelguith** [comment]
Hi,

I have the same issue with PS1.7.6.0beta1 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/59204639-f8626a80-8b98-11e9-81f0-d9a99b22bd04.png)
When I try to translate the BO with the language created, I have the same exception
![image](https://user-images.githubusercontent.com/16067358/59204707-192ac000-8b99-11e9-9e5e-c54f01ed9703.png)

Thanks!

**Comment by OneDotIT** [comment]
Hello again,
I have debugged the issue.

It seems PrestaShop pre-identifies the 2-characters ISO code's, and using that to identify the language tag, which is a component of the language name and region, i.e 'fr->fr-FR', and to note, the language tag represent the translation folder and where the localization strings are located.

the supported ISO code's location:
`/app/Resources/legacy-to-standard-locales.json`


Appending the _mg_ language and region _MG_ as like have solved the initial case:
```
.....
"zh": "zh-CN",
"mg": "mg-MG"
}

```
But still, per version 1.7.6.0-beta1, the folder mg-MG has to be created (a nice error pop-up would appear on the top right).

**Comment by khouloudbelguith** [comment]
@OneDotIT, thanks for your feedback.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment]
@OneDotIT, thanks for your PR.
You need to add your language in this file also: https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json

Thanks!

**Comment by OneDotIT** [comment]
@khouloudbelguith 
Thank you for the mention.
@rabtaray, would you confirm the localization ? This is an example:
```
    "name": "اللغة العربية (Arabic)",
    "iso_code": "ar",
    "date_format_lite": "Y-m-d",
    "date_format_full": "Y-m-d H:i:s",
    "is_rtl": "1",
    "language_code": "ar-sa",
    "locale": "ar-SA"
```

**Comment by rabtaray** [comment]
Hi @OneDotIT 

 "name": "Malagasy",
    "iso_code": "mg",
    "date_format_lite": "d-m-Y",
    "date_format_full": "d-m-Y H:i:s",
    "is_rtl": "0",
    "language_code": "mg-mg",
    "locale": "mg-MG"

Thank you.

**Comment by OneDotIT** [comment]
Thank you khouloud.

I suspect the file _all_languages.json_ is what build the drop menu while selecting a language in BO.
