### ISSUE TITLE
Place the reference on the product

### ISSUE THREAD

**Issue by josejecas** [PrestaShop/PrestaShop#14072]
How can I place the reference on the product below the product photo?

http://prntscr.com/nxl3vu

**Comment by mariem-abid** [comment]
Hi @josejecas,

You have to put the desired change in the product.tpl file of your template.

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @josejecas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
