### ISSUE TITLE
bill date and logo issue

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#14076]
**Describe the bug**
in a client web, when a client of my client make a buy, the date and logo of the bill get bad 

**To Reproduce**
1. Go to 'a order'
2. Click on 'the bil of the order.'
3. See error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/9163980/58920068-c3858c00-8730-11e9-88d4-3577497c1265.png)

![image](https://user-images.githubusercontent.com/9163980/58920086-e31cb480-8730-11e9-8c2c-38ae85698df4.png)

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

I manage to reproduce the issue with the PS:1.7.6.0beta1 (the bill is missing the logo)
With PS 1.7.5.2 and PS 1.6.1.24, the logo and the date are OK.
I attached a screenshot.
![Capture du 2019 06 07 09 54 00](https://user-images.githubusercontent.com/16067358/59093127-12871900-890b-11e9-91d2-9a90191aecaf.png)
I’ll add this to the debug roadmap so that it’s fixed.

Thanks!

**Comment by marionf** [comment]
@mariem-abid I can't reproduce the issue with 1.7.6.x, the logo is correctly displayed

![capture d'écran_1648](https://user-images.githubusercontent.com/13449658/59102390-33ac3180-892c-11e9-9498-b8c897c321d3.png)

**Comment by mariem-abid** [comment]
@marionf, I manage to reproduce the issue with PS:1.7.6.0beta1
I attached a video record.
https://drive.google.com/file/d/1cnyjLHsqpX1QxMx6nqY8FlGj0fJ4SCWv/view
Thanks!

**Comment by marionf** [comment]
@mariem-abid 
Did you change the logo in Design > Theme & logo > Invoice logo ?
Can you try on 1.7.6.x ?

**Comment by Quetzacoalt91** [comment]
This issue has already been fixed on 1.7.6.0 via https://github.com/PrestaShop/PrestaShop/pull/11691

**Comment by LinkOfLight** [comment]
Logo fixed, but the date no D:

**Comment by mariem-abid** [comment]
@marionf, I did not make a change.
I will try to reproduce with 1.7.6.x and come back

**Comment by marionf** [comment]
@LinkOfLight 

You said
>  the date and logo of the bill get bad

I don't see what is wrong on your invoice ?

**Comment by LinkOfLight** [comment]
I fixed the logo, but the dais is wrong
[Imagen]




Obtener Outlook para Android<https://aka.ms/ghei36> desde mi Galaxy S10+

Angel Moreno Cubero - Administrador de Tech4Life - www.tech4life.es<http://www.tech4life.es>

Advertencia Legal: La información que contiene este correo electrónico y, en su caso, los ficheros adjuntos, está dirigida a la persona cuya dirección electrónica figura en la cabecera. Si usted recibe este correo electrónico y no es el destinatario, ruegolo borre de inmediato y comunique dicha circunstancia. Cualquier uso fraudulento realizado con el contenido del correo electrónico recibido queda sometido a las acciones previstas por la legislación vigente. Queda expresamente prohibida la divulgación, copia o distribución a terceros sin la previa autorización.
Política de Protección de Datos de Carácter Personal:En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), y el propio Reglamento General de Protección de Datos, ANGEL MORENO CUBERO,Responsable del Fichero, informa a los usuarios que los Datos de Carácter Personal que recoge son objeto de tratamiento mixto, y se incorporan en los ficheros correspondientes debidamente registrados en la Agencia Española de Protección de Datos. En nombre de la empresatratamos la información que nos facilita con el fin de prestarles el servicio solicitado y realizar la facturación del mismo. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal. En virtud de lo establecido en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), ANGEL MORENO CUBERO, Responsable del Fichero, le informa que podrá utilizar las direcciones de correo electrónico facilitadas por los usuarios, para mantenerles informado acerca de lo concerniente a la relación comercial establecida. Usted da su consentimientoexpreso para que el Responsable del Fichero, ANGEL MORENO CUBERO, pueda utilizar su dirección de correo electrónico con este fin concreto Usted tiene derecho a obtener confirmación sobre si ANGEL MORENO CUBERO está tratando sus datos personales, por tanto tiene derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios. En ningún caso le será enviada publicidad de ningún tipo. El usuario podrá en todo momento ejercitar los referidos derechos reconocidos en la LOPD, de Acceso, Rectificación, Cancelación y Oposición (ARCO). El ejercicio de estos derechos puede realizarlo el propio usuario acompañando copia del DNI de manera presencial en las oficinas de ANGEL MORENO CUBERO, titular del DNI 26820694A, como Responsable del Fichero, bien mediante correo electrónico admin@tech4life.es, o bien mediante comunicación escrita a la siguiente dirección postal Ángel Moreno Cubero. C/ Juan Ramón Jiménez 1 Local- Doña Mencía (Córdoba). C.P. 14860 – España.

________________________________

**Comment by marionf** [comment]
@LinkOfLight 

Sorry but I don't see what is wrong with the date
It's the same in your BO and in the invoice

![capture d'écran_1649](https://user-images.githubusercontent.com/13449658/59111921-4df10a00-8942-11e9-9e47-5dac7733f97f.png)

![capture d'écran_1650](https://user-images.githubusercontent.com/13449658/59111927-521d2780-8942-11e9-8472-cd15bcb8abb4.png)

**Comment by LinkOfLight** [comment]
Tech, this is the problem, why un bd is 2012, not 2019

Obtener Outlook para Android<https://aka.ms/ghei36> desde mi Galaxy S10+

Angel Moreno Cubero - Administrador de Tech4Life - www.tech4life.es<http://www.tech4life.es>

Advertencia Legal: La información que contiene este correo electrónico y, en su caso, los ficheros adjuntos, está dirigida a la persona cuya dirección electrónica figura en la cabecera. Si usted recibe este correo electrónico y no es el destinatario, ruegolo borre de inmediato y comunique dicha circunstancia. Cualquier uso fraudulento realizado con el contenido del correo electrónico recibido queda sometido a las acciones previstas por la legislación vigente. Queda expresamente prohibida la divulgación, copia o distribución a terceros sin la previa autorización.
Política de Protección de Datos de Carácter Personal:En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), y el propio Reglamento General de Protección de Datos, ANGEL MORENO CUBERO,Responsable del Fichero, informa a los usuarios que los Datos de Carácter Personal que recoge son objeto de tratamiento mixto, y se incorporan en los ficheros correspondientes debidamente registrados en la Agencia Española de Protección de Datos. En nombre de la empresatratamos la información que nos facilita con el fin de prestarles el servicio solicitado y realizar la facturación del mismo. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal. En virtud de lo establecido en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), ANGEL MORENO CUBERO, Responsable del Fichero, le informa que podrá utilizar las direcciones de correo electrónico facilitadas por los usuarios, para mantenerles informado acerca de lo concerniente a la relación comercial establecida. Usted da su consentimientoexpreso para que el Responsable del Fichero, ANGEL MORENO CUBERO, pueda utilizar su dirección de correo electrónico con este fin concreto Usted tiene derecho a obtener confirmación sobre si ANGEL MORENO CUBERO está tratando sus datos personales, por tanto tiene derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios. En ningún caso le será enviada publicidad de ningún tipo. El usuario podrá en todo momento ejercitar los referidos derechos reconocidos en la LOPD, de Acceso, Rectificación, Cancelación y Oposición (ARCO). El ejercicio de estos derechos puede realizarlo el propio usuario acompañando copia del DNI de manera presencial en las oficinas de ANGEL MORENO CUBERO, titular del DNI 26820694A, como Responsable del Fichero, bien mediante correo electrónico admin@tech4life.es, o bien mediante comunicación escrita a la siguiente dirección postal Ángel Moreno Cubero. C/ Juan Ramón Jiménez 1 Local- Doña Mencía (Córdoba). C.P. 14860 – España.

________________________________

**Comment by LinkOfLight** [comment]
This invoice is one of the last Sell of this web
________________________________

**Comment by marionf** [comment]
@LinkOfLight I can't reproduce your issue, please check your server datetime is well configured

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration
I invite you to contact you hosting provider.

Best regards.

**Comment by LinkOfLight** [comment]
Yes, is ok, in other webs in the dame server this go ok

Obtener Outlook para Android<https://aka.ms/ghei36> desde mi Galaxy S10+

Angel Moreno Cubero - Administrador de Tech4Life - www.tech4life.es<http://www.tech4life.es>

Advertencia Legal: La información que contiene este correo electrónico y, en su caso, los ficheros adjuntos, está dirigida a la persona cuya dirección electrónica figura en la cabecera. Si usted recibe este correo electrónico y no es el destinatario, ruegolo borre de inmediato y comunique dicha circunstancia. Cualquier uso fraudulento realizado con el contenido del correo electrónico recibido queda sometido a las acciones previstas por la legislación vigente. Queda expresamente prohibida la divulgación, copia o distribución a terceros sin la previa autorización.
Política de Protección de Datos de Carácter Personal:En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), y el propio Reglamento General de Protección de Datos, ANGEL MORENO CUBERO,Responsable del Fichero, informa a los usuarios que los Datos de Carácter Personal que recoge son objeto de tratamiento mixto, y se incorporan en los ficheros correspondientes debidamente registrados en la Agencia Española de Protección de Datos. En nombre de la empresatratamos la información que nos facilita con el fin de prestarles el servicio solicitado y realizar la facturación del mismo. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal. En virtud de lo establecido en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), ANGEL MORENO CUBERO, Responsable del Fichero, le informa que podrá utilizar las direcciones de correo electrónico facilitadas por los usuarios, para mantenerles informado acerca de lo concerniente a la relación comercial establecida. Usted da su consentimientoexpreso para que el Responsable del Fichero, ANGEL MORENO CUBERO, pueda utilizar su dirección de correo electrónico con este fin concreto Usted tiene derecho a obtener confirmación sobre si ANGEL MORENO CUBERO está tratando sus datos personales, por tanto tiene derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios. En ningún caso le será enviada publicidad de ningún tipo. El usuario podrá en todo momento ejercitar los referidos derechos reconocidos en la LOPD, de Acceso, Rectificación, Cancelación y Oposición (ARCO). El ejercicio de estos derechos puede realizarlo el propio usuario acompañando copia del DNI de manera presencial en las oficinas de ANGEL MORENO CUBERO, titular del DNI 26820694A, como Responsable del Fichero, bien mediante correo electrónico admin@tech4life.es, o bien mediante comunicación escrita a la siguiente dirección postal Ángel Moreno Cubero. C/ Juan Ramón Jiménez 1 Local- Doña Mencía (Córdoba). C.P. 14860 – España.

________________________________
