### ISSUE TITLE
Hook actionAdminProductsListingFieldsModifier is duplicated

### ISSUE THREAD

**Issue by Jacky75** [PrestaShop/PrestaShop#14083]
**Describe the bug**
The Hook "actionAdminProductsListingFieldsModifier " is invoked twice in /src/Adapter/Product/AdminProductDataProvider.php. Since the parameters are passed by reference and this hook is invoked twice, the changes applied by a hooked module are applied twice.
Is it possible the hook should be present only once in actionAdminProductsListingFieldsModifier?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by mariem-abid** [comment]
Hi @Jacky75,

Thanks to adding a short description of your issue and add steps to reproduce it in a new comment.

**Comment by Jacky75** [comment]
Hi,
sorry.
The Hook "actionAdminProductsListingFieldsModifier " is invoked twice in /src/Adapter/Product/AdminProductDataProvider.php. Since the parameters are passed by reference and this hook is invoked twice, the changes applied by a hooked module are applied twice.
Is it possible the hook should be present only once in actionAdminProductsListingFieldsModifier?

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by sowbiba** [comment]
I think the 2nd hook only should be trigger : after the 1st one, $sqlWhere is modified

**Comment by PierreRambaud** [comment]
> I think the 2nd hook only should be trigger : after the 1st one, $sqlWhere is modified

I disagree, `$sqlSelect` is used in the foreach statement, it can be used with custom params :thinking: 
The second one can also be used in order to play with what has been created before :sweat_smile: 
In fact, we have simple choices here:
- Change hooks name with `After` and `Before`, but it's a BC
- Add a params to define which hook is called (it's ugly)
- Add a property on your class to define if the hook has already been called.

wdyt?

**Comment by hibatallahAouadni** [comment]
Thanks @sowbiba & @PierreRambaud for your detailed answer.
So, what the status of this issue?

**Comment by matks** [comment]
As no consensus was reached, I guess we can close the issue.
