### ISSUE TITLE
Updating a third-party module overwrites any custom translations made.

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#14088]
**Describe the bug**
Install a third-party module (that uses the legacy translations)
Update a translatable field.
Install the module again to simulate an update.
The translation is lost.

Previously the updated translation would be saved in the theme directory.  Unless I'm missing something you are now saving it in the module directory, which means if you have made any translation changes, you can't update your module.

**To Reproduce**
Install a third-party module (that uses the legacy translations)
Update a translatable field.
Install the module again to simulate an update.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by mariem-abid** [comment]
Hi @roja45,

Thank you for giving us the module to test it.

**Comment by roja45** [comment]
[testtranslation-master-1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/3269612/testtranslation-master-1.0.0.zip)

**Comment by roja45** [comment]
Here you go.

Install the module, open a product page, the default provided translation file is used. 

Update the module translation from the back office, product page shows the updated translation.

Install the module file again to simulate installing a module update, and the translation you made before is overwritten by the translation file in the module archive, so you lose your translation changes.

**Comment by roja45** [comment]
Issue is present in 1.7.6.0 beta 1 as well.

**Comment by roja45** [comment]
A bit more info.
If you manually add the translation file for the module in the theme directory, then the front end picks up the theme translation, so that still works, and it seems the theme selection UI options in the back office are there as well, it's just not hooked up.

![image](https://user-images.githubusercontent.com/19314911/59160161-d255a100-8a98-11e9-9b0f-cb96f6e5d16a.png)

**Comment by khouloudbelguith** [comment]
Hi @roja45,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
After re-installing the module, the new translation is not lost.
I attached a video record
https://drive.google.com/file/d/1JLQwYLNYR59MG6LflehnWIjPKEvUFeAG/view
Thanks to check & feedback

**Comment by roja45** [comment]
Hi @khouloudbelguith,

Couple of things to confirm with your test;

1) Don't uninstall the module, customers wouldn't do this if upgrading their module when an update is available.  You have to add the module again to correctly simulate a customer downloading a module update, and uploading it to their server (I think it's this step that overwrites the files, as it is uploading the archive again).  Just re-installing will re-install the files already on the server, which will still have you translation.
2) Just to also check that it is not configured to cache the template.

Thanks

**Comment by khouloudbelguith** [comment]
@roja45, I attached a video record
https://drive.google.com/file/d/1UhEhrhgXs98BRuPcX3TUpSO2Y1c8v2Qq/view
Thanks to check & feedback.

**Comment by roja45** [comment]
Prestashop cache should be disabled, or clear it after uploading the module again.

In you test installation then, is the updated translation saved in the theme structure?

**Comment by khouloudbelguith** [comment]
@roja45,

>In you test installation then, is the updated translation saved in the theme structure

No, I selected the translation of the module.
https://drive.google.com/file/d/1wQfuCDpUSGoHtvivi0PasmRPVheg0vKD/view

Thanks!

**Comment by roja45** [comment]
Yes, I understand that, it's the only way to translate legacy modules at the moment, the question was more about where the translation file has been saved in the file system, did it save it in the module directory, or in the theme module directory.

The more important is to disable the prestashop cache and clear it when running your test.

**Comment by khouloudbelguith** [comment]
@roja45,

> the question was more about where the translation file has been saved in the file system, did it save it in the module directory, or in the theme module directory.

It is saved in the module directory.
In your projet_Folder/modules/testtranslation/translations folder you can find the files of translations.

Thanks!

**Comment by roja45** [comment]
yes, that's what I see, but that must cause an issue.  

If you make a change to the translation, as in your video, and this has been saved back to the module directory, then there are two things that can happen.

1) The file will be overwritten if the module has an updated translation file, and you will lose your change.  - This is what I see when I test.

or

2) if the module translation file is ignored, to keep the modified one, then the module cannot provide an updated translation file.  - This seems to be what you are seeing, but I think your template has been cached.

So either way, I think this process has a problem.

Cheers

Nigel

**Comment by khouloudbelguith** [comment]
@roja45, 

>The file will be overwritten if the module has an updated translation file, and you will lose your change. - This is what I see when I test.

But in my case, it is ok.
I cleared cache from Prestashop & from the navigator & it is always ok.

Thanks!

**Comment by roja45** [comment]
I will record a video, I'm testing in a fresh install and it's the same module so not sure why you would see a different result.

**Comment by khouloudbelguith** [comment]
@roja45, ok thanks!
Waiting for your feedback.

**Comment by roja45** [comment]
Here you go:
https://drive.google.com/file/d/1mz4y2FMto6ItBneGMFPEbtGg-rtIkz1x/view

Not sure what I am doing differently

**Comment by khouloudbelguith** [comment]
@roja45, in my case it is Ok.
I cleared cache manually by deleting folder into /var/cache,
I deleted the file shop.json into the path /config/theme/classic/,
I used the incognito tab, I refreshed the window with Ctrl +Shift + R
=> I have always the same translated expression, it is not lost.
@sarahdib could you please try to reproduce it?

Thanks!

**Comment by sarahdib** [comment]
Hello @roja45 

Like @khouloudbelguith I didn't reproduce the bug

You can see the video here : https://drive.google.com/file/d/1hrEP2uKkltaULyUcFJV8n9DyxrCnn8bA/view

Thank you

**Comment by khouloudbelguith** [comment]
Hi @roja45,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
