### ISSUE TITLE
Backoffice display issue

### ISSUE THREAD

**Issue by AminPersis** [PrestaShop/PrestaShop#14095]
Hi,

I've upgraded to 1.7.5.2 yesterday and ever since I have a problem in the back office.
I've cleared the browser cache, cleared and disabled Prestashop caching features and deleted public_html/var/cache/ a hundred times, but nothing seems to solve my issue.

after a few hours, it suddenly started to display properly in the English language, but when I switch to Persian, I have the same issue, and despite everything I do, the issue persists.

I would appreciate if someone can help me with this issue.

Please, see the screenshot for reference:

![Back Office](https://user-images.githubusercontent.com/51361765/59017239-bb6e3f00-884b-11e9-8750-b35ec19c8048.jpg)

PrestaShop version: 1.7.5.2
PHP version: 7.0.33

Regards
Amin

**Comment by khouloudbelguith** [comment]
Hi @AminPersis,

What is the exact version PS did you installed before the upgrade ?

Thanks!

**Comment by AminPersis** [comment]
Hello @khouloudbelguith 

Prestashop 1.7.3.0

Regards

**Comment by AminPersis** [comment]
@khouloudbelguith 

Hi,
I couldn't fix this issue, yet. Do you know how should I fix it?

Regards
Amin

**Comment by khouloudbelguith** [comment]
Hi @AminPersis,

Sorry for the late answer.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @AminPersis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
