### ISSUE TITLE
multistore is not working properly || directory problem 

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14108]
i have a created multistore, shop name is shopA and copy from primary  folder/code/project &&  paste in  subfolder/newShop then i was changed themes logo for shopA.
But logo not showing.
i was checked problem is that added new logo image storing in primary project,i don't know why not store in subfolder/newShop   
 plz comment

Thanks

**Comment by mariem-abid** [comment]
Hi @dharmendravirasat,

What is the exact version of PrestaShop did you use?

Thanks!

**Comment by dharmendravirasat** [comment]
I am using  Prestashop version 1.7.5.1   @mariem-abid 
plz reply

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, you just created a new issue about this problem.
Duplicate of #14139

**Comment by khouloudbelguith** [comment]
Duplicate of #14139
