### ISSUE TITLE
missing form_error element in some forms

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#14103]
**Bug description**
In some migrated pages (e.g currency page form) form_error is missing - I believe it should be located above.

The error dispatched here https://github.com/PrestaShop/PrestaShop/blob/95683248751795b1e927445d57abaf45708fea09/src/Core/Form/IdentifiableObject/Handler/FormHandler.php#L109 will never be visible in some pages

**Additionnal information**
PrestaShop version: 1.7.6 and develop

when adding form_error please dont forget to check other errors which belong to the form field - are they not being popped up in form_error field rather then being displayed near the input.

Try to check multilanguage input field - it has error_bubbling option enabled. It might be the case that the error which should appear below input actually can appear in form_error place

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14172
