### ISSUE TITLE
You shouldn't be able to move a parent category in a sub category

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14100]
**Describe the bug**
You shouldn't be able to move a parent category in a sub category

**To Reproduce**
1. Go to Catalog > Categories
2. Click on edit for Clothes
3. Select Women as parent category
4. See error with max execution time
5. Return to the category list, the category edited disappeared

**Screenshots**
![capture d'écran_1642](https://user-images.githubusercontent.com/13449658/59037728-23378080-8872-11e9-926e-91ff4f9f2c61.png)

On 1.7.5.2 it was not possible to move a parent category in the sub category, they was disabled

![capture d'écran_1643](https://user-images.githubusercontent.com/13449658/59037773-3ba79b00-8872-11e9-820d-978f67d87b87.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14107
