### ISSUE TITLE
problem changing company information 

### ISSUE THREAD

**Issue by lothianwraps** [PrestaShop/PrestaShop#14104]
**Describe the bug**

**To Reproduce**
1. Go to 'Homepage Configuration'
2. Click on 'footer'
2. Click on 'link list'
2. Click on 'configure'
2. Click on 'edit our company'
2. Click on 'save'
The server returned a "500 Internal Server Error"

PrestaShop version: 1.7.5.2

**Comment by mariem-abid** [comment]
Hi @lothianwraps,

Could you please add a video record to reproduce the issue.

**Comment by lothianwraps** [comment]
hi what format do i need to save the file as you dont support mp4

**Comment by khouloudbelguith** [comment]
Hi @lothianwraps,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & the ps_linklist module v3.0.3.
https://drive.google.com/file/d/1hyaDPcWkRxbU_5olebkF1Var2hoKoxHt/view
It is OK also with PS1.7.5.2 & the ps_linklist v2.1.6.
https://drive.google.com/file/d/1HpF8bNhlCttCB3JYb3_C-__IZAVR-JQn/view

What is the exact version of the module ps_linklist did you use?

Thank you!

**Comment by lothianwraps** [comment]
Hi 
I reinstalled the module and it seems to have fixed the problem 

Thanks you for trying to help 
Scott

**Comment by khouloudbelguith** [comment]
@lothianwraps, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
