### ISSUE TITLE
Add support for product price exempt from VAT (next to including or excluding VAT)

### ISSUE THREAD

**Issue by ProBackup-nl** [PrestaShop/PrestaShop#14102]
Current product pricing is either including VAT or excluding VAT. But there is a third state, some products or services are exempted from VAT taxation by law.

I would like to see a third choice "VAT exempted" beside "VAT included" or "VAT excluded".

For example Dutch coop's that produce sustainable energy and only supply tax reduction to their members do sell membership certificates that are exempted from VAT collection.

**Comment by mariem-abid** [comment]
@colinegin , @marionf , what do you think?

**Comment by Hlavtox** [comment]
Maybe you guys can use the tax rule's description field - which is to my knowledge not used?

By default, it could show Without tax/With tax, but if a user defines a custom note/description in Tax rule set > Tax rule, it would show this message instead.

**Comment by Hlavtox** [comment]
1. User will create tax rule set "Tax for certificates".
2. For every country, he will make a Tax rule with "No Tax" option selected and he will fill the Description field with "exempted from VAT".
3. Just show the description in FO.

**Comment by marionf** [comment]
@ProBackup-nl 
Yes, you can create a tax rule as suggested by @Hlavtox and also create a customer group with "price display method" set to "tax excluded"

**Comment by ProBackup-nl** [comment]
@marionf @Hlavtox 
Yes, I can create a tax rule set and customer groups. However the product is still listed as "excluding tax" (or whatever value I set in "customer group > price display method"). The price is still not displayed as "exempted from VAT".

The workaround doesn't show the "Tax rules > single rule enabled = Country=nl > Description".

**Comment by marionf** [comment]
@ProBackup-nl you can change the translation for "tax excluded" in International > Translations
Select Theme translations, your theme and your language
Click on Theme > Global and search "tax excluded"

**Comment by ProBackup-nl** [comment]
@marionf Translating the label is a clumsy workaround. It works only as long as all product in the store are tax exempt.

Products need a third state:

1. including VAT
2. excluding VAT
3. VAT/tax exempt

**Comment by Hlavtox** [comment]
@ProBackup-nl Excluding VAT = VAT exempt. Just add your message to it and done.

**Comment by marionf** [comment]
Hello @ProBackup-nl 

I posted your idea here: http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/38279389-add-a-third-state-for-vat-including-vat-excluding

This way we will be able to see if this feature interests other people

**Comment by marionf** [comment]
@ProBackup-nl 

There was no vote for this suggestion, so I do not think we're going to implement it
