### ISSUE TITLE
Main menu || Image slider not showing in prestashop version 1.7.5.1

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14118]
I am using multistore in my prestashop project, i installed Prestashop default **main menu** module. In  module added categories menu but menu not showing in all themes 
and 
**Image slider** module is not working 
I don't know why not showing menu && image slider
plz comment
thanks.

**Comment by khouloudbelguith** [comment]
Hi @dharmendravirasat,

I did not manage to reproduce the issue with PS1.7.5.2 / PS1.7.6.0beta1, ps_mainmenu v2.1.1 & the ps_imageslider v3.0.0.
I attached a video record.
https://drive.google.com/file/d/1Hm2Ul2MiCCCJIFB6rHdsDHOz80jMPG0q/view
thanks to check & feedback

**Comment by dharmendravirasat** [comment]
I was cleared cache then now working fine main menu && image slider.

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
