### ISSUE TITLE
Impossible to see my cart 

### ISSUE THREAD

**Issue by elviraprint** [PrestaShop/PrestaShop#14111]
**Describe the bug**
Hi, when i add a product to the cart i got an error on page, why ??

**To Reproduce**
1. Go to '.the product page..'
2. Click on 'the cart....'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
<img width="1261" alt="Capture d’écran 2019-06-07 à 14 35 15" src="https://user-images.githubusercontent.com/51324358/59104466-f480df00-8931-11e9-9d0a-2850b5708197.png">

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by mariem-abid** [comment]
Hi @elviraprint,

What is the exact version PHP do you use?

Thanks!

**Comment by elviraprint** [comment]
i 'm on the prestashop version 1.7.5.0, how could i know the php i use ?

**Comment by elviraprint** [comment]
i use the version php 7.2

**Comment by elviraprint** [comment]
i apparently solved the problem tahks

**Comment by khouloudbelguith** [comment]
@elviraprint, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
