### ISSUE TITLE
Modify Copyright Prestashop 

### ISSUE THREAD

**Issue by sebaborda04** [PrestaShop/PrestaShop#14115]
Hi, I want to modify the copyright of the footer of my Prestashop website and I can not do it.
I no longer have files to modify and I still do not see the change.
Can you tell me where I have to do it?
Prestashop version 1.7.2.4
Thank you

**Comment by matks** [comment]
The file is footer.tpl for your theme
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/_partials/footer.tpl#L49

**Comment by khouloudbelguith** [comment]
Hi @sebaborda04,

Thanks for your report.
@matks, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
