### ISSUE TITLE
Faceted seach: multiple filters works like "OR" function

### ISSUE THREAD

**Issue by cesarfierro** [PrestaShop/PrestaShop#14120]
PS 1.7.5.2
PS_FacetedSearch 3.0.3

Hello,
When I config a search template with two or more features for a single category, I have observed that the selection works like an logical OR function instead AND function.
If I check "Feature 1 - Value A" and also check "Feature 2 - Value X" I get all products with "Feature 1 - Value A" plus "Feature 2 - Value X" increasing the view list.
It works like logical operation (Filter-1 OR Filter-2) instead of (Filter-1 AND Filter-2).

With PS 1.7.5.0 it worked fine.

Regards
César

![Step 1](https://user-images.githubusercontent.com/47951167/59144762-56455580-89d3-11e9-8e2f-ab6aeb00127c.PNG)
![Step 2](https://user-images.githubusercontent.com/47951167/59144760-55acbf00-89d3-11e9-9119-e958ac6366dc.PNG)
![Step 3](https://user-images.githubusercontent.com/47951167/59144761-55acbf00-89d3-11e9-8121-8bd0dccc2a59.PNG)

**Comment by rdy4ever** [comment]
+1 Just tried the new module on my test shop, the logic is wrong. You should try to downgrade the module to version [2.2.1](https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.2.1). If it doesn't work, you may have to reset the module.

**Comment by PierreRambaud** [comment]
Thanks for your feedbacks guys: We create a fix here: https://github.com/PrestaShop/ps_facetedsearch/pull/87

**Comment by frankymartinES** [comment]
Hi, I got another error after update PS_FacetedSearch to 3.0.3, it is not working properly in my multistore 1.7.4.4. After update the module every shop show the same products, if I active a product in one shop, the other shops show also the product.

**Comment by PierreRambaud** [comment]
@frankymartinES Don't forget to rebuild indexes

**Comment by frankymartinES** [comment]
@PierreRambaud I did it in every shop (not in All Shops Backoffice) but the problem is still here.

**Comment by PierreRambaud** [comment]
ping @khouloudbelguith Are you able to reproduce the multistore issue?

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

issue reproduced with PS1.7.6.0beta1 / 1.7.5.2 & ps_factedsearch v3.0.3 but in inother case

Product A with:
1. Brand: Graphic Corner
2. Category: Home
3. Created in all shops
4. Enabled in the shop 1
5. Disabled in the shop 2

In the FO => Shop 1 selected, home page 2, filter with the brand Graphic Corner

1. Before disabling the product in the shop 2 
![image](https://user-images.githubusercontent.com/16067358/59261373-3d3bdf00-8c35-11e9-9d0a-824ee0e9907c.png)

OK => the product is displayed in the first shop 

2. After disabling the product in the shop 2 

![image](https://user-images.githubusercontent.com/16067358/59261434-5f356180-8c35-11e9-80bd-51809a91d7c3.png)

NOK => the product is not displayed in the first shop

When I checked with a product selected to another category, it is OK.

With v2.2.0 => I did not manage to reproduce the issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

The issue of multistore is fixed with this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/88

Thanks!

**Comment by frankymartinES** [comment]
Hi, thanks for fixing the issue. Now I have found other issue, when I active the faceted module the default combnation of products is not showed in product list. I am working in a multistore PS 1.7.4.4

**Comment by khouloudbelguith** [comment]
Hi @frankymartinES,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
