### ISSUE TITLE
Display warning before creating refund and changing order status

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#14123]
Using PS 1.7.5.2.

I noticed that when I do a refund for an order that was paid with Paypal it automatically creates the refund in Paypal. This is great, but it would be nice if an extra pop-up could be created, a warning, to inform you that you are booking the money also from the Paypal account. 

What if by accident you are doing a bulk order update and press refund as a mistake. That would be an expensive mistake.

**Comment by marionf** [comment]
Hello @01park 

Where do you make the refund, in your back-office ?
Could you please send a screenshot of the page and the button ?
From what I know, it's not possible to make refunds in bulk in the back-office

Thank you

**Comment by 01park** [comment]
Hi,

I made the refund in back office. It's the basic change status field in the order status.  What I'm suggesting is to build in a double check, like a " ARE YOU SURE YOU WANT TO REFUND", because once you execute, the Paypal transaction gets automatic refunded. I never tried a bulk refund, but if that doesnt work. Good!

**Comment by marionf** [comment]
@01park 

I just tried to make an order and a refund with Paypal 

![capture d'écran_1659](https://user-images.githubusercontent.com/13449658/59256276-eaadf300-8c33-11e9-8206-24658999a4df.png)

![capture d'écran_1660](https://user-images.githubusercontent.com/13449658/59256293-f00b3d80-8c33-11e9-8a20-0ddb164e8df8.png)

![capture d'écran_1661](https://user-images.githubusercontent.com/13449658/59256300-f4cff180-8c33-11e9-90d9-8e123babfe82.png)

The "Refund PayPal" checkbox is added by Paypal module
We can't add an alert if this box is checked when clicking on "Partial Refund", this should be done in the Paypal module and it's not developed by PrestaShop
You can contact [the developer](https://www.202-ecommerce.com/en/contact-us/) of the module to suggest them this improvement

**Comment by 01park** [comment]
I share screen shots. After I select refund in the status menu, i receive a customer service message. Saying that the refund is done
<img width="1205" alt="Screenshot 2019-06-11 at 09 35 14" src="https://user-images.githubusercontent.com/46492443/59256890-cac70100-8c2c-11e9-9ea4-c92d455e232b.png">
<img width="852" alt="Screenshot 2019-06-11 at 09 36 44" src="https://user-images.githubusercontent.com/46492443/59256898-cef31e80-8c2c-11e9-8a38-03b8682a42a0.png">
<img width="525" alt="Screenshot 2019-06-11 at 09 41 49" src="https://user-images.githubusercontent.com/46492443/59257115-37420000-8c2d-11e9-994e-652e4b8539ac.png">


i see your running on 1.7.6, im using 1.7.5.2 could this be the difference?

**Comment by marionf** [comment]
No, it's the same on 1.7.5.2
The "refund Paypal" checkbox is displayed after clicking on "Partial Refund"
Anyway, the refund is also done when you select the "refunded" order status and this is also managed by Paypal module, so the alert should be implemented by Paypal module
And you are right, order status can be changed in bulk directly in order listing

**Comment by 01park** [comment]
Hi,

 Like I said, this is not an issue, its a concern. Will someone from Prestashop reach out to Paypal?

**Comment by marionf** [comment]
Yes, it's an improvement request. You should contact [PayPal](https://www.202-ecommerce.com/en/contact-us/) directly
