### ISSUE TITLE
[SKIP] the directory &quot;/app/cache/&quot; does not exist and cannot be emptied

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#14122]
**Describe the bug**
Hi, after the update from 1.6.1.23 to 1.6.1.24, I found this line in the log file and another error:
[SKIP] the directory "&quot;/app/cache/&quot;" does not exist and cannot be emptied
and this error:
...server path.../autoupgrade/tmp/gsitemap.zip is not a file
Thanks for any reply.

**To Reproduce**
1. Go to => modules => module 1 click upgrade
2. Check that all recommendation are ok (green icon)
3. Select minor release (1.6.1.24) and click
4. Wait patiently...

**Screenshots**
SKIP
![skip-log](https://user-images.githubusercontent.com/28685316/59148871-6e869600-8a0e-11e9-86af-3da391620a10.gif)

ERROR
![errore](https://user-images.githubusercontent.com/28685316/59148790-65e19000-8a0d-11e9-9fa5-b84389bd63d2.gif)

**Additionnal information**
PrestaShop version: 1.6.1.24 (now)
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

I did not manage to reproduce the issue, the upgrade is done successfully from PS1.6.1.23 to PS1.6.1.24 with the 1-click upgrade 4.8.0.
https://drive.google.com/file/d/1KhAqpGLSbI8FNbDB7SX7LsfchnEdYJ52/view
Thanks to delete the cache files? you can remove them by using FTP or your hosting file manager, browse the folder on your server where you have installed Prestashop:
\cache\smarty\cache\
You can see many files with long names in this folder. The file names include the module name, so you can delete any of them. Just leave the index.php file alone!

Thanks to check & feedback.

**Comment by ballashop** [comment]
Hi @khouloudbelguith 
and thank for your reply, I'm going to cancel as you wrote me, after update i discovered another problem from login and logout web page, the redirect doesn't work as expected. Is it better if I open another issue, or can I write it here?
Thanks

**Comment by khouloudbelguith** [comment]
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
And your issue, I cannot reproduce it with PS1.6.1.24.
Thanks for your understanding!

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by ballashop** [comment]
Ok, unfortunately I haven't solved yet, but I'll try again soon, waiting for 1.7.6.
Thanks a lot.
