### ISSUE TITLE
useless ELSE IF in AdminProductsController

### ISSUE THREAD

**Issue by finlanderid** [PrestaShop/PrestaShop#14126]
The "else if" in this code is useless and will never fire, because it duplicates half of the OR condition from the IF that it is attached to.

```
// Manage references and prices
foreach ($attributes as $attribute) {
	foreach ($associated_suppliers as $supplier) {
		/** @var ProductSupplier $supplier */
		IF (Tools::isSubmit('supplier_reference_' . $product->id . '_' . $attribute['id_product_attribute'] . '_' . $supplier->id_supplier) ||
			(Tools::isSubmit('product_price_' . $product->id . '_' . $attribute['id_product_attribute'] . '_' . $supplier->id_supplier) &&
			 Tools::isSubmit('product_price_currency_' . $product->id . '_' . $attribute['id_product_attribute'] . '_' . $supplier->id_supplier))) {
			
. . . [code removed here to shorten code example] . . . 
			
		} ELSEIF (Tools::isSubmit('supplier_reference_' . $product->id . '_' . $attribute['id_product_attribute'] . '_' . $supplier->id_supplier)) {
			//int attribute with default values if possible
			if ((int) $attribute['id_product_attribute'] > 0) {
				$product_supplier = new ProductSupplier();
				$product_supplier->id_product = $product->id;
				$product_supplier->id_product_attribute = (int) $attribute['id_product_attribute'];
				$product_supplier->id_supplier = $supplier->id_supplier;
				$product_supplier->save();
			}
		}
	}
}
```

**Comment by khouloudbelguith** [comment]
Hi @finlanderid,

Thanks for your report.
ping @PrestaShop/prestashop-core-developers what do you think about the `elseif` from this line
https://github.com/PrestaShop/PrestaShop/blob/786f04823b96f41b7bd5485df30dddf3de509322/controllers/admin/AdminProductsController.php#L2550  ?

Thanks!

**Comment by PierreRambaud** [comment]
yes, the condition seems useless, but don't really know what was the wanted behavior here :/

**Comment by finlanderid** [comment]
Yes, it would have to be studied to figure out why they wanted it.  It seems to be about setting a few variables in the database (when product attributes exist) in the new product_supplier table that was implemented when multi-shop was implemented a few years ago.  Another clue might be the use of save() rather than update().

Another clue: the block in the elseif is identical to the block of code directly above the [// Manage references and prices] comment.

Possibility: its purpose was intended to **update** those variables -- not save them since they had been saved above -- when (at least) supplier_reference is being input and submitted.

If so, the logic in its current form won't accomplish that, since the ELSEIF will never be entered.  A correct place for it might be **inside** the IF (as an IF), at the bottom.

Totally speculating here, so take this suggestion with a grain of salt.  I could be completely wrong regarding the intention.

Can you contact the previous developer?  This has been in the code since at least as far back as 2015.

**Comment by sowbiba** [comment]
Agree: the code in the elseif will never be executed

**Comment by Hlavtox** [comment]
This code was already removed from AdminProductsController. So fixed. :-)
