### ISSUE TITLE
Error send email

### ISSUE THREAD

**Issue by josejecas** [PrestaShop/PrestaShop#14121]
I do not know if this is a bug, but if you can help me.

Watch the video.

Two prestashop installations in which one works the email and another not, and I can not find the problem.

I already changed the password, the email and it does not work

https://drive.google.com/file/d/1bbeRINcsa2FuI8F88y15cEABONQFvkKC/view

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @josejecas,

Thanks for your report.
It looks like the SMTP was blocked for hosting free users.
you need to check the issue with your host provider.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
Hi @josejecas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
