### ISSUE TITLE
multistore is not working properly || directory problem

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14139]
i have a created multistore, shop name is shopA and copy from primary folder/code/project && paste in subfolder/newShop then i was changed themes logo for shopA.
But logo not showing.
i was checked problem is that added new logo image storing in primary project,i don't know why not store in subfolder/newShop
prestashop version 1.7.5.1
plz comment

Thanks

**Comment by khouloudbelguith** [comment]
Hi @dharmendravirasat,

Could you please add steps t reproduce the issue in a new comment.

Thanks!

**Comment by dharmendravirasat** [comment]
I have  two store,store name is shop and shopA. shop is primary project and shopA  saved in subfolder.
problem is that i am changed logo for shopA/subfolder but front end showing image undefine path.
Image could't storing in subfolder/img/cms and i am checked image stored in primary/project/shop directory
Note: I don't know why store in primary project directory.
I should save in subfolder directory   

plz reply  @khouloudbelguith
thanks

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, what is the exact `Physical URL` & `Virtual URL` for both `shop` & `shopA`?
![image](https://user-images.githubusercontent.com/16067358/59270448-64041080-8c49-11e9-919f-b6c9802946d0.png)

Thanks!

**Comment by dharmendravirasat** [comment]
thanks your feedback

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, feel free to open a new one when needed.

Thanks!
