### ISSUE TITLE
Round the  $this->total_paid_real  in addOrderPayment method

### ISSUE THREAD

**Issue by sunnyvsrainy** [PrestaShop/PrestaShop#14149]
Hi team,

in PrestaShop/classes/order/Order.php,  the method public 
function addOrderPayment(**$amount_paid**, $payment_method = null,...

.....
        // Update total_paid_real value for backward compatibility reasons
        if ($order_payment->id_currency == $this->id_currency) {
             **$this->total_paid_real += $order_payment->amount;**
        } else {
            $this->total_paid_real += Tools::ps_round(Tools::convertPrice($order_payment->amount, $order_payment->id_currency, false), 2);
        }

Could the team round the result after the if/else block,  such as :
` $this->total_paid_real = Tools::ps_round($this->total_paid_real, 2);`
  ?

Current behaviors:
If the argument $amount_paid is less than 0,  there can result in many decimals. 
E.g:
  $this->total_paid_real = 114.76 , 
  $order_payment->amount = -114, 
then 
   the $this->total_paid_real  will be: **0.76000000000001**
This will cause Invalid price exception.

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @sunnyvsrainy,

I created a product with a price = 114.76, then I created order with this product => change the status of this order to "payment accepted", in my database I have `total_paid_real` = 114.760000

![image](https://user-images.githubusercontent.com/16067358/59256597-2fce2700-8c2c-11e9-916b-df0ef63a5cd7.png)


During those steps, I don't have any invalid price exceptions.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @sunnyvsrainy,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
