### ISSUE TITLE
Faceted search: price indexing stopped working

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#14140]
**Describe the bug**
On PS 1.7.5.0, after upgrading ps_fatetedsearch from version 2.2.1 to version 3.0.3, price reindexing (_index all missing prices_ button) stopped working on the module configuration page: the ajax call loops forever, but no error is returned in the console. In the FO, if you go to a category and click 'Sort by price...' no products are returned. I have tried deleting the templates, uninstalling and reinstalling the module.
On 1.7.6.0 beta, price reindexing works, so it could be just a 1.7.5.0 error, or an error caused by the upgrade of the module from 2.2.1 to 3.0.3. I've reproduced this error on two test shops, both running PS 1.7.5.0. Before module upgrade, reindexing worked fine, after - kaput.
On my test 1.7.6.0 beta, price reindexing works fine.

**To Reproduce**
Steps to reproduce the behavior FO:
1. Go to any category page
2. Click on 'sort by price, low to high'
3. See error

Steps to reproduce the behavior BO:
1. Go to module config page
2. Click on 'index all missing prices'
3. Wait
4. Nothing happens (the spinner just keeps on spinning)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.16

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Thanks for your report.
Yes, I manage to reproduce the issue with PS1.7.5.2 & the ps_factedsearch v3.0.3 after upgrade from v2.2.1.
https://drive.google.com/file/d/1IN7IOtFxPnZugUUiQnolYQEmfbqly0uG/view
If I made the upgrade from v3.0.2 to 3.0.3 => it is OK
https://drive.google.com/file/d/19DOyoZwIilRaY5yJonBwkw4IbvmIzeJj/view
with PS1.7.6.0beta1 => OK
https://drive.google.com/file/d/1EnlI4PV4iftrSof7bJSKnZtq6EnPjMD9/view
ping @PierreRambaud 

Thanks!

**Comment by PierreRambaud** [comment]
I'm not able to reproduce after a fresh 1.7.5.2 install and upgrade to the latest facetedsearch version :/

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever, yes @PierreRambaud is right, In my last case, I have a large number of products, I have more than 8000 products, "Rebuilt entire price index" takes a lot of time.

@rdy4ever, do you have a large number of products?

Thanks!

**Comment by rdy4ever** [comment]
@PierreRambaud @khouloudbelguith 
No. I have only 65 products. Please note that #14144 is the same issue, so I am not the only one affected by this. So it must be something related to having the old versions of the module installed and configured first. I have tried every each way to make it work, I have also uninstalled the module completely, deleted all its tables and reinstalled it. The problem remains. I have also tested it on both local machine and production server with the same result on my test shop (that is a clone of my production shop). Indeed, on a clean install the problem may not occur, but most people don't have clean installs, don't they? It could be something related to [this PR](https://github.com/PrestaShop/ps_facetedsearch/pull/69), that change the way the price indexer works. 
Also, please note that I am on 1.7.5.0, not 1.7.5.2 (if that matters).
The only way I could make the price indexing work again is uninstalling and installing the old v. 2.2.1.

**Comment by rdy4ever** [comment]
@PierreRambaud @khouloudbelguith 
Also, please note that in my case "Rebuild entire price index" works, but in FO I still have the error. So, then I try "Index all missing prices" and that doesn't work, the spinner just spins forever.

**Comment by khouloudbelguith** [comment]
@rdy4ever, no, it is OK in my case, after upgrade from v2.2.0 to 3.0.3
https://drive.google.com/file/d/1008_nYbM2sS_hGlR9tM1O66uboYWcWdQ/view
Thanks!

**Comment by rdy4ever** [comment]
@khouloudbelguith please also try "index all missing prices" button

**Comment by sandra2n** [comment]
Hello,
similar issue for me. In the front the filter by product only work if in the module parameter I choose to apply the filter to price with tax incl. It seems that when the index is build without this option the id_country in the base "layered_price_index" is put to "0", while the current id_country is used in the sql request when products are filtered by price "
'price_min' => [
                'tableName' => 'layered_price_index',
                'tableAlias' => 'psi',
                'joinCondition' => '(psi.id_product = p.id_product AND psi.id_currency = ' .
                $this->getContext()->currency->id . ' AND psi.id_country = ' . $this->getContext()->country->id . ')',
                'joinType' => self::INNER_JOIN,
            ],
            'price_max' => [
                'tableName' => 'layered_price_index',
                'tableAlias' => 'psi',
                'joinCondition' => '(psi.id_product = p.id_product AND psi.id_currency = ' .
                $this->getContext()->currency->id . ' AND psi.id_country = ' . $this->getContext()->country->id . ')',
                'joinType' => self::INNER_JOIN,
            ],
            'range_start' => [
                'tableName' => 'layered_price_index',
                'tableAlias' => 'psi',
                'joinCondition' => '(psi.id_product = p.id_product AND psi.id_currency = ' .
                $this->getContext()->currency->id . ' AND psi.id_country = ' . $this->getContext()->country->id . ')',
                'joinType' => self::INNER_JOIN,
            ],
            'range_end' => [
                'tableName' => 'layered_price_index',
                'tableAlias' => 'psi',
                'joinCondition' => '(psi.id_product = p.id_product AND psi.id_currency = ' .
                $this->getContext()->currency->id . ' AND psi.id_country = ' . $this->getContext()->country->id . ')',
                'joinType' => self::INNER_JOIN,
            ],
"

**Comment by sandra2n** [comment]
and "
if (!Configuration::get('PS_LAYERED_FILTER_PRICE_USETAX')) {
                $taxRatesByCountry = [['rate' => 0, 'id_country' => 0, 'iso_code' => '']];
            }
"

**Comment by rdy4ever** [comment]
In my case, all my prices are tax-free. 

With version 2.2.1 installed, everything works and `ps_layered_price_index` table is populated correctly. See screen recording: https://drive.google.com/open?id=1kax81xOSDGqMCpL_vo_cgTTShkgQJW7n

With version 3.0.3 updated from 2.2.1 (but I also tried installing it directly), if I click on "rebuild entire price index", the ajax call seems to work, but the table `ps_layered_price_index` remains empty. If I click "Index all missing prices", then the ajax call loops and never finishes. See recording:
https://drive.google.com/open?id=1dFDVwobrTtaCYYu2i6HnCty0DbJSyQmy

**Comment by rdy4ever** [comment]
OK. I can confirm that @sandra2n is right. 
In version 3.0.3, in the module configuration, if I set "**Use tax to filter price**" to **NO**, then the price indexing works just in the BO, while in the FO still doesn't work. Also, in the database, price_min, price_max and id_country are all set to 0:
![image](https://user-images.githubusercontent.com/12268701/59265526-2eadf180-8c4e-11e9-836d-5f58cba5005c.png)
 
Note that all my products have "Tax rule: No tax"

**Comment by rdy4ever** [comment]
@khouloudbelguith @PierreRambaud 

**Please reproduce the issue as follows:**
1. Set all the active products in the shop to **Tax rule: No tax**. You can leave just a few activated products, I tried it with just 5 active products. You need to set it te every active product, it doesn't work if you just disable all tax rules.
2. Go to module config, click "rebuild entire price index". It will work, however:
3. Go to the database, table `ps_layered_price_index`. `price_min`, `price_max` and `id_country` should all be 0. This is not good.
4. Back in the module config, click on "Index all missing prices". If, in module config "Use tax to filter price" is set to YES - it will remain stuck at the number of active products. If set to "NO", then it doesn't get stuck, however the table is still populated with 0's.
5. In the FO, category page, sort by price will no longer work,

**Comment by khouloudbelguith** [comment]
@rdy4ever, thanks a lot for your feedback.
Now, I manage to reproduce the issue with PS1.7.5.2 & the ps_factedsearch v3.0.3
to reproduce the issue, we need all the active products in the shop to **Tax rule: No tax**.
ping @PierreRambaud 
With PS1.7.6.0beta1 & ps_factedsearch v3.0.3 => it is OK
https://drive.google.com/file/d/1-QU0_yKd_pT3iIHp7ngk87jg-aJhe7IZ/view

Thanks!

**Comment by rdy4ever** [comment]
Hi @khouloudbelguith 
I also managed to reproduce with PS1.7.6.0 and v3.0.3

**Comment by khouloudbelguith** [comment]
@rdy4ever, with PS1.7.6.0 => in the FO ok
as described in this video record
https://drive.google.com/file/d/1-QU0_yKd_pT3iIHp7ngk87jg-aJhe7IZ/view
But, in the table ps_layered_price_index, not all the prices price_min, price_max, and id_country are not all 0.
![image](https://user-images.githubusercontent.com/16067358/59269285-9c561f80-8c46-11e9-83e0-12bbb706380e.png)

Thanks!

**Comment by rdy4ever** [comment]
@khouloudbelguith 
In my case it doesn't work: https://drive.google.com/open?id=1ZLOAbN9-dUnvQdZYEw9XyAHqotzPRdnn. 
Could you try to truncate `ps_layered_price_index` table first, so you'' have just the active products inside?

**Comment by shnslmz** [comment]
> Now, I manage to reproduce the issue with PS1.7.5.2 & the ps_factedsearch v3.0.3
> to reproduce the issue, we need all the active products in the shop to **Tax rule: No tax**.
> ping @PierreRambaud
> With PS1.7.6.0beta1 & ps_factedsearch v3.0.3 => it is OK

It's so interesting: "we need all the active products in the shop to Tax rule: No tax.".

> 
> 
> Hi @khouloudbelguith
> I also managed to reproduce with PS1.7.6.0 and v3.0.3

Anyway,  I will try to upgrade for 17.6.0.
There is no any other solutions for now, right?

**Comment by rdy4ever** [comment]
> It's so interesting: "we need all the active products in the shop to Tax rule: No tax.".

Actually, it's not necessary for **_all_** the products to be set to Tax rule: No tax. If you have mixed products, some with tax and some without, only the ones with tax will be indexed and shown in the FO when sorting by price. If all products are set to No tax, then no product will be shown.

**Comment by shnslmz** [comment]
> 
> 
> > It's so interesting: "we need all the active products in the shop to Tax rule: No tax.".
> 
> Actually, it's not necessary for **_all_** the products to be set to Tax rule: No tax. If you have mixed products, some with tax and some without, only the ones with tax will be indexed and shown in the FO when sorting by price. If all products are set to No tax, then no product will be shown.

Thanks but I don't think that's good. According to your above report, I will try to upgrade.

**Comment by khouloudbelguith** [comment]
@rdy4ever,
>Could you try to truncate ps_layered_price_index table first, so you'' have just the active products inside?

Yes, I did that & it is the same result.
I attached a video record
https://drive.google.com/file/d/16G6VLZpepCav88ZzBCH2znSs9HQ0F9N1/view
Thanks!

**Comment by ptvsat** [comment]
BIG issue ps1.7.5.1 >> upgread 3.0.2 to 3.0.3
500 server error

log:

213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:10 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 408 221 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:21:56:59 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 408 221 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:21:57:11 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 408 221 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:07 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 302 3 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:12 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:16 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:21:57:00 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 408 221 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:03:43 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:15 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:05:07 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:21:57:04 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 408 221 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:00:10 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 302 3 "-" "-"
213.251.182.106 www.planet-tvsat.com - [11/Jun/2019:22:05:04 +0200] "GET /boutique/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=1bf50fe948&cursor=355&full=0 HTTP/1.1" 500 2454 "-" "-"

**Comment by khouloudbelguith** [comment]
Hi @ptvsat,

Your issue is different from this issue, can you open a new one with more information about your configuration.

Thanks!

**Comment by PierreRambaud** [comment]
@rdy4ever Should be ok with this PR :) https://github.com/PrestaShop/ps_facetedsearch/pull/90

**Comment by rdy4ever** [comment]
Hi @PierreRambaud 
Yes. I can confirm this PR fixes the problem with price indexation for products with no tax applied.
Thanks!

**Comment by khouloudbelguith** [comment]
@PierreRambaud, it is OK for me also with PS1.7.5.2.

Thanks!

**Comment by PierreRambaud** [comment]
@rdy4ever Thanks to you for your help :+1: 
We'll release a new version tomorrow :)
