### ISSUE TITLE
No country code

### ISSUE THREAD

**Issue by billaronson** [PrestaShop/PrestaShop#14153]
**Describe the bug**

**To Reproduce**
1. Go to Checkout
2. Click on Country
3. No list of country codes

Unable to complete order

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![image](https://user-images.githubusercontent.com/51707566/59273997-49359a00-8c51-11e9-8bb1-6b42e6470dfb.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @billaronson,
Thanks for your report.
Could you please navigate to your BO => International => Locations => Countries Tab => check if you have any country enabled?

Thanks to check & feedback.

**Comment by billaronson** [comment]
that works thank you

**Comment by khouloudbelguith** [comment]
@billaronson, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
