### ISSUE TITLE
I have problems with updating a Product (custom fields) in Prestashop.

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14150]
I followed the tutorial: http://blog.belvg.com/how-to-create-a-custom-product-tab-in-prestashop.html

It works quite fine, when I save a product the normal way. But Prestashop 17.5.2 has an autosave function, when changing stock or prices. This makes my custom fields empty. By trial & error I found out, that my hookActionProductUpdate function causes the problem, but I dont know why not get custom field value :

public function hookActionProductUpdate($params) {
$url =Tools::getValue('custom_field'); // Tools::getValue not working i don't why 
return Db::getInstance()->execute(
                'UPDATE `'._DB_PREFIX_.'amazon_url` SET `amazon_url` ='.$url.' WHERE `id_product` ='.$params['id_product'].'');

}

What is wrong with it?

 

Thanks in advance!

**Comment by khouloudbelguith** [comment]
Hi @dharmendravirasat,

In your function `hookActionProductUpdate` could you please try to add this line

`$id_product = Tools::getValue('id_product'); `

THanks to check & feedback.

**Comment by dharmendravirasat** [comment]
But i am get Tools::getValue('custom_field');
and product id  already able to access 
Note:- This text type custom_field already added in  product update;
overall working fine but i am not getting custom_field value

Note:- public function hookActionProductUpdate($params){
$id_product = Tools::getValue('id_product');
if(!Tools::getValue('custom_field'))return;

	$url=(string)Tools::getValue('custom_field');
return Db::getInstance()->execute('UPDATE `'._DB_PREFIX_.'amazon_url` SET `amazon_url` ='.$url.' WHERE `id_product` ='.$id_product.'');
/* return Db::getInstance()->execute('UPDATE `'._DB_PREFIX_.'amazon_url` SET `amazon_url` ="testng" WHERE `id_product` ='.$id_product.''); */ //this query working when  set default value but dynamic value not getting
} 

 plz reply  @khouloudbelguith 
Thanks

**Comment by dharmendravirasat** [comment]
But i am get Tools::getValue('custom_field');
and product id already able to access
Note:- This text type custom_field already added in product update;
overall working fine but i am not getting custom_field value

Note:-```
 public function hookActionProductUpdate($params){
$id_product = Tools::getValue('id_product');
if(!Tools::getValue('custom_field'))return;

$url=(string)Tools::getValue('custom_field');
return Db::getInstance()->execute('UPDATE '._DB_PREFIX_.'amazon_url SET amazon_url ='.$url.' WHERE id_product ='.$id_product.'');
/* return Db::getInstance()->execute('UPDATE '._DB_PREFIX_.'amazon_url SET amazon_url ="testng" WHERE id_product ='.$id_product.''); */ //this query working when set default value but dynamic value not getting
}
```


and tpl file 
`<input class="form-control" id="custom_field" name="custom_field" type="text" value="{$custom_field}">
`

plz reply @khouloudbelguith
Thanks

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, first, you need to check if in your module the `hookActionProductUpdate` is working or not.
You can try with `die();`

```
public function hookActionProductUpdate($params) {
     die();
    }
```
When you update a product => Settings updated is always displayed?

Thanks!

**Comment by dharmendravirasat** [comment]
Hi 
I am checked my code problem is that i am not using quotes for string

`return Db::getInstance()->execute('UPDATE '.DB_PREFIX.'amazon_url SET amazon_url ='.$url.' WHERE id_product ='.$id_product.'');`
replace code and apply new code 
`return Db::getInstance()->execute('UPDATE '.DB_PREFIX.'amazon_url SET amazon_url ="'.$url.'" WHERE id_product ='.$id_product.'');`

Thank for your feedback 
I have one  issue for multiple store related please check this url
https://github.com/PrestaShop/PrestaShop/issues/14139

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
