### ISSUE TITLE
Can't create formtypes with TranslatableAwareType dependency

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#14160]
**Describe the bug**

```php
class ExempleForm extends CommonAbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('test', TranslatableAwareType::class, []);
    }
}
```

```php
public function indexAction()
    {
        $form = $this->createForm(ExempleForm::class, []);

        return $this->render('@Modules/training/views/Admin/Training/exemple.html.twig', [
            'layoutTitle' => 'Controller using the modern architecture',
            'help_link' => false,
            'form' => $form->createView(),
        ]);
    }
```

I got an error: Symfony is unable to retrieve translator and locales needed in TranslatableAwareType type, even when I declare it as a service.

**To Reproduce**
See explanation.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think? what is the severity of this issue?

Thanks!

**Comment by matks** [comment]
@mickaelandrieu Do you mean `TranslatableType` ?

**Comment by mickaelandrieu** [comment]
@matks, it's an instance of PrestaShopBundle\Form\Admin\Type\TranslatorAwareType
