### ISSUE TITLE
Submitting URL change after upgrading/changing domain name [Presthop Addons]

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14176]
Scenario i have is i have upgraded my domain i.e. from Fastcars.co.uk to cars.uk 

I can no longer download/auto-update anything from the addon store as it has my old domain attached. 

Everything under your Addon username/password won't work. Maybe easier if it's change to work with the solo account holder like on envato the license should be registered to the person instead of a particular domain or should be able to update your URL in the addon store. I.e. the same way Revo slider works revoke license then assign to new domain. multiple ways of achieving the same outcome.  

![update domain name](https://user-images.githubusercontent.com/43471871/59366168-c5071380-8d31-11e9-8f35-16d01566d1c8.png)

**Comment by khouloudbelguith** [comment]
Hi @Hintergedanke,

Does this issue occur in our Market place add-ons PrestaShop?

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith Yes.

**Comment by ghost** [comment]
i.e. you purchase a Module you keep same email, name etc etc

You change your site from belguith.fr to belguith.com you can no longer automatically update your addon or submit your new url via the Prestashop Addon store

**Comment by khouloudbelguith** [comment]
@Hintergedanke, Please be aware that this bug tracker should be used to report issues only.
You need to contact us via this link https://addons.prestashop.com/en/contact-us

Thanks!
