### ISSUE TITLE
Wrong shipping cost by deleting some articles from an order

### ISSUE THREAD

**Issue by benlecoqartisans** [PrestaShop/PrestaShop#14174]
My shipping costs are setting like this :
![image](https://user-images.githubusercontent.com/48204607/59360143-e5ce6980-8d2f-11e9-83b0-b2cf9b12d53c.png)

For an order, when I delete some articles that I can't provide, shipping cost are wrong. I reproduce 2 cases illustrating by these examples :
1- After having deleted one or some articles, but still with a total product cost over 100€, I have shipping cost of the previous interval that are attributed
2 - After having deleted one or some articles and having a total product cost under 100€, I still have free shipping.

**Comment by khouloudbelguith** [comment]
Hi @benlecoqartisans,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
I attached a video record
https://drive.google.com/file/d/1nJSPRloPuzMmPCMP7EP4BcmGPifsa00F/view
Thanks to check & feedback.

**Comment by benlecoqartisans** [comment]
Hi @khouloudbelguith 
I attached a video record which shows the bug

https://drive.google.com/open?id=16UHRiWbWHEzMs69SS9FSF1kl8ZMdDnoT

**Comment by benlecoqartisans** [comment]
I don't know what other element I can give to you, tell me if you think to anything else

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, in your last screen record, you have this
![image](https://user-images.githubusercontent.com/16067358/59368095-6479d580-8d35-11e9-90ab-784f86a08e49.png)

You have total TTC > 100 & shipping <> 0.
Could you please try to display the price with tax excluded, check & feedback.

Thanks!

**Comment by benlecoqartisans** [comment]
I've ever checked this point
![image](https://user-images.githubusercontent.com/48204607/59368596-e7ebf480-8d3e-11e9-9c88-694c8604ef1e.png)

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, did you use a specific tax for your carrier?
![image](https://user-images.githubusercontent.com/16067358/59425755-765b8700-8dce-11e9-9abb-1b7d628c38d3.png)

Thanks!

**Comment by benlecoqartisans** [comment]
Yes
![image](https://user-images.githubusercontent.com/48204607/59428810-9f841380-8dde-11e9-8a55-a9dc9e2d06ae.png)

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, sorry, but I did not manage to reproduce the issue.
https://drive.google.com/file/d/1iGrdJERcW1e7JjdyH5_iyFmbMsHU4wIb/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by benlecoqartisans** [comment]
Ok I check this with my developer and then give it to you.

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, thanks!
Waiting for your feedback.

**Comment by benlecoqartisans** [comment]
@khouloudbelguith 
You will find our logs but I don't think there is a relevant information in them.  It seems to be a fonctional bug, I mean in algorithm.
[php.log](https://github.com/PrestaShop/PrestaShop/files/3286732/php.log)

[dev.log](https://github.com/PrestaShop/PrestaShop/files/3286731/dev.log)
 find

Did you try to reproduce in 1.7.5.1 ? 
And did you try with 3 intervals of shipping cost like me ? 
Another tip : Sometime, I have to delete many products to see the bug, and sometime just one. Try by deleting products with little amount one after the other...

**Comment by benlecoqartisans** [comment]
Another tip : I desactivate all external modules and still reproduce the problem

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, yes, I created a case similar to yours.
https://drive.google.com/file/d/1Omz9ZBbJFXVWpmi_lJ32K4PERiurYlXQ/view
Thanks!

**Comment by benlecoqartisans** [comment]
last element, I work with a multishop Prestashop

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, could you please provide us the exact configuration of your shop Group?
![image](https://user-images.githubusercontent.com/16067358/59445264-3f4d9b80-8df7-11e9-8ae7-8ae5e84cfe30.png)

Thanks!

**Comment by benlecoqartisans** [comment]
![image](https://user-images.githubusercontent.com/48204607/59445491-0fef5c80-8e00-11e9-81e9-634ebf6c7202.png)

Did you check logs ?

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, yes, there are no errors in your files.
When I try to delete a product from an order when all shops is selected, I have an error
![image](https://user-images.githubusercontent.com/16067358/59448533-4a0b2f00-8dfd-11e9-9ef8-dd61c6a211da.png)

Thanks to check & feedback.

**Comment by benlecoqartisans** [comment]
Yes I agree, I've ever seen that. 
But in ma case, I was with the good shop for deleting an article from the order.

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, when the shop1 is selected, I manage to reproduce the issue with PS1.7.5.2
https://drive.google.com/file/d/1QjOkpW8_Y4_pFbIhBTMW3vp60gBMRmoX/view
But with PS1.7.6.0beta1 => it is OK
https://drive.google.com/file/d/1KmHRbyfsEVvka5K2848RU_XMXRSxIpI7/view
Thanks to check & feedback

**Comment by benlecoqartisans** [comment]
Just to be sure, could you play the same scenario with PS1.7.6.0beta1 ? I mean, could you have the same order as in 1.7.5.2 (same product and same quantity) and delete the same product (n°7). 
This bug seems to be so hazardous that I will be more confident with the exactly same test in 1.7.6.0beta1
Thanks.

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, I rechecked with PS1.7.5.2 & PS1.7.6.0beta1.
The error doesn't exist.
PS1.7.6.0beta1 https://drive.google.com/file/d/1aHoGixJvE69pAJ_02wcgIrtgjmSG039y/view
PS1.7.5.2 https://drive.google.com/file/d/10epE-fb_4Uekn6WeWoC3B4i-sr5LV9h8/view

After checking my previous screen record https://drive.google.com/file/d/1QjOkpW8_Y4_pFbIhBTMW3vp60gBMRmoX/view

I found that the problem is not related to the shipping cost, but the total product was incorrect
![image](https://user-images.githubusercontent.com/16067358/59502497-d0734f80-8e95-11e9-9b28-cc82f3182a0f.png)

Thanks to check & feedback.

**Comment by benlecoqartisans** [comment]
Hi @khouloudbelguith 
I don't reproduce your problem of wrong total products. Sorry.
https://drive.google.com/open?id=1dI4Dy-cSIj7MzSmhIFvDVrVsz6wrdMA7
Any other idea of something to check ?

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, could you please try to import those products
[product_2019-06-14_113713.txt](https://github.com/PrestaShop/PrestaShop/files/3290942/product_2019-06-14_113713.txt)
& check if you can reproduce your issue after ordering those products.

Thanks!

**Comment by benlecoqartisans** [comment]
@khouloudbelguith 
https://drive.google.com/open?id=1bir0gx__ZnzE8dtvEhgb7OOlVFXmn9Wv
I don't reproduce my issue with your products but I had to change it (I don't know if it was good, but, for instance, we don't have the same total).
Here is my file
[product_2019-06-14_113713.txt](https://github.com/PrestaShop/PrestaShop/files/3291115/product_2019-06-14_113713.txt)

Would you suggest that the bug could come from my products ? If yes, do you have any more precise idea about what is wrong ?

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, I used your products & it is OK.
No issue reproduced
https://drive.google.com/file/d/1W_kHxgbo7jfVYL5q0SeVro8IWDKdiRnp/view
Thanks!

**Comment by benlecoqartisans** [comment]
Do you have any idea about what could be wrong ?

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, I don't think.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by benlecoqartisans** [comment]
Do you know if it is possible to export products with their combinations, because perhaps there is something like that ?
 It is the main difference that I can see between your products and mine (the real ones)

**Comment by benlecoqartisans** [comment]
Hi @khouloudbelguith 
I have made another tests and realized that (I have a multistore Prestashop) when I was deleting an article when I was on 'All stores', the issue wasn't there, but when I was on a store I reproduced the matter. I precise it's the same order with the same articles.
https://drive.google.com/open?id=1ioQjTI1IsowlCvOVqtcXNFbba2ZIAEwB

Could you make another test in that way please ?
Thanks

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, when all shop selected, we have an error after deleting a product from the order as described in this issue
https://github.com/PrestaShop/PrestaShop/issues/9609

Thanks!
