### ISSUE TITLE
Deletion of Product confirmation needed. 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14177]
Hi Team,

To me this is the wrong way around. Deletion of a combination prompts for "Are you sure to delete this?" When it should be the product as you can replace the combination with little to few inputs vs the product which has feature's categories etc etc. 

You can see from the view how easy it is to make the mistake thinking your using another combination delete icon. Text box maybe with confirmation Delete Product instead? as it looks exactly the same with no layer of protection - it is a very costly mistake you will not see unless you look through the logs. 

![Painful](https://user-images.githubusercontent.com/43471871/59367261-a144cd00-8d33-11e9-8483-be4ee7acd870.png)

**Comment by khouloudbelguith** [comment]
Hi @Hintergedanke,

Thanks for your report.
So, when you try to delete a combination, you need to have the exact name of the combination you want to delete it in the confirmation pop-up?
![image](https://user-images.githubusercontent.com/16067358/59367665-760ead80-8d34-11e9-855d-819fa3b0d2be.png)

THanks!

**Comment by ghost** [comment]
@khouloudbelguith 

Visually the **combination** selection column aligns almost with the **Product Delete** icon. 

Because of the sticky footer it should be a Text box that says "Delete Product" because it's far to easy to assume you're deleting the combination

**Comment by khouloudbelguith** [comment]
@Hintergedanke, but if you move the mouse under this icon, you have some information about the delete completely of this product.
![image](https://user-images.githubusercontent.com/16067358/59424436-e6b4d900-8dcb-11e9-970a-20aa0d0b25c6.png)

Thanks!

**Comment by mariem-abid** [comment]
Hi @Hintergedanke,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
