### ISSUE TITLE
Div not aligned on some migrated pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14186]
**Describe the bug**
The last div is not aligned with the others on add new theme page and localization page

**To Reproduce**
1. Go to Design > Theme & logo / International > Localization
2. Click on Add a theme
3. The last div is not aligned

**Screenshots**

1.7.6.0

![capture d'écran_1671](https://user-images.githubusercontent.com/13449658/59420211-c5a0b800-8dcc-11e9-9c95-5169e52f0261.png)

![capture d'écran_1685](https://user-images.githubusercontent.com/13449658/59521413-85c0fa00-8ecc-11e9-8c15-a9022020d2d3.png)

1.7.5.2

![capture d'écran_1686](https://user-images.githubusercontent.com/13449658/59521594-f23bf900-8ecc-11e9-8d47-c7f46f9328ba.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by jolelievre** [comment]
Fixed by #14242
