### ISSUE TITLE
Not receiving email notifications of customer message on contact page

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#14188]
**Describe the bug**
Whenever a customer sends a message via the contact page, notification is received in the BO but there is no email notification.

I went to advanced parameters -> test email and it works fine. I went to Contact -> Customer Service and the email is the same as the email I tested. Order messages are received successfully via mail alerts module. 

Customer messages are not working - neither I nor the customer receives any notification. However, when I respond to a message in the BO, the customer receives a notification.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Could you please navigate to your BO => Modules => Module Manager page => search for the `Contact form` module => configure it.
You need to enable `Send confirmation email to your customers` & `Receive customers' messages by email` options.
![image](https://user-images.githubusercontent.com/16067358/59426339-dbfc4300-8dcf-11e9-97ba-a3342cbe239b.png)

Thanks to check & feedback.

**Comment by nrcjea001** [comment]
Thank you. This worked. You may close the issue

**Comment by khouloudbelguith** [comment]
@nrcjea001, great!
I close the issue, feel free to open a new one when needed.

Thanks!
