### ISSUE TITLE
Ask visitors feedback for basket cancelled

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#14203]
**Is your feature request related to a problem? Please describe.**
I can't increase my selles.

**Describe the solution you'd like**
When a visitor cancel his shooping basket, I have no details to contact this person so I need to know if there is an option to make visitors give us the reason why they cancelled and the answer will be stored in back office 
The will have a choices to select or required text field to fill.

**Describe alternatives you've considered**
Regards
**Additional context**

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your report.
In our Market place Add-ons, you can find such modules about abandoned cart reminder
https://addons.prestashop.com/en/search?id_category=0&search_query=abandoned%20cart%20reminder
So, you can 
- Remind abandoned cart through a Facebook Messenger chatbot
- Get higher open and click conversion rates than email

Thanks to check & feedback.

**Comment by mariem-abid** [comment]
Hi @go-sudo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
