### ISSUE TITLE
Bad display in Traffic & SEO page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14205]
**Describe the bug**
Schema of URLs part missing in Traffic & SEO page

**To Reproduce**
1. Go to Shop parameters > Traffic & SEO
2. Disable friendly URL
3. You will see two "*" under "SEO options" part
4. Enable friendly URL
5. You will see one "*" under "SEO options" part

**Screenshots**
![capture d'écran_1679](https://user-images.githubusercontent.com/13449658/59496433-b5064580-8e91-11e9-9384-deb08ca3ebfb.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by sarjon** [comment]
Hi @marionf, are you sure it's a bug?

I get same behavior on 1.7.5.2. If you disable friendly URL, this section is gone as it is related to friendly url configuration.

The only issue I can see is * being rendered in weird place.

**Comment by marionf** [comment]
@sarjon yes you are right, I updated the issue :)

**Comment by jolelievre** [comment]
Fixed by #14220
