### ISSUE TITLE
An empty box for the sort options when selected not default one

### ISSUE THREAD

**Issue by iqit-commerce** [PrestaShop/PrestaShop#14210]
**Describe the bug**
Sort options from preferences > products do not match sort options on frontoffice. 
Selecting sort option in backoffice which is not avaiable in frontoffice result error in debug mode

**Screenshot**
https://pasteboard.co/IjmArG3.png

**To Reproduce**
1. Go to category pages on frontoffice and check avaiable sort options
2. Go to backoffice> preferences > products, select sort order which is not avaiable on frontoffice
3. Go back to category page on fronfoffice

**Additionnal information**
PrestaShop version: Tested on 1.7.6, but it happen on all of 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @iqit-commerce,

I did not manage to reproduce the issue with Ps1.7.6.0beta1 & the ps_facetedsearch v4.0.4.
I attached a screen record
https://drive.google.com/file/d/1jjBBv-1a_QEChea59FAhyUvjKs0TvrSV/view
thanks to check & feedback

**Comment by iqit-commerce** [comment]
@khouloudbelguith I confimg that with 3.0.4 it is ok, however sort order box is empty which not looks good

**Comment by khouloudbelguith** [comment]
@iqit-commerce, thanks for your feedback.
I have the same issue with ps_facetedsearch v2.2.0 & v3.0.4.
In the BO => Shop Parameters => Product Settings => if we select sort order which is not available on the front office for example "Product modified date", in the FO, we will have an empty box
![image](https://user-images.githubusercontent.com/16067358/59590926-f8a4bd80-90e4-11e9-9b2b-d09328657827.png)

@marionf, @colinegin, @PierreRambaud what do you think?
It could be a good improvement to not displaying an empty box?

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith The same issue happens without facetedsearch and also if you select "date add", "date update", "brand", "product quantity" or "product reference" in BO.

If you select "Position in the category" in BO, "Relevance" is displayed in FO.
I think it's useless to display "date add", "date update", "brand", "product quantity" or "product reference" for customers in FO, so "Relevance" could also be selected for these options

wdyt of this solution @iqit-commerce ?
