### ISSUE TITLE
Modules are not installing

### ISSUE THREAD

**Issue by renochost** [PrestaShop/PrestaShop#14213]
I was trying to install 1-click update module but its not installing and showing me 500 error.

![Opera Snapshot_2019-06-14_172306_www renoc in](https://user-images.githubusercontent.com/51604042/59507737-902dc480-8ec9-11e9-898b-402612a588d1.png)
![Opera Snapshot_2019-06-14_172454_www renoc in](https://user-images.githubusercontent.com/51604042/59507739-902dc480-8ec9-11e9-9f32-cff9315c08c4.png)
![Opera Snapshot_2019-06-14_172507_www renoc in](https://user-images.githubusercontent.com/51604042/59507741-90c65b00-8ec9-11e9-9cfe-5eb5a1a2342b.png)
![Opera Snapshot_2019-06-14_172526_www renoc in](https://user-images.githubusercontent.com/51604042/59507743-90c65b00-8ec9-11e9-8da1-9c54e9c653d5.png)
![Opera Snapshot_2019-06-14_172551_www renoc in](https://user-images.githubusercontent.com/51604042/59507745-915ef180-8ec9-11e9-8eb1-c6d5fbe07f7d.png)
 

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.28
MySQL server: localhost

**Comment by khouloudbelguith** [comment]
Hi @renochost,

you must install PHP `zip` extension on your server.

Thanks to check & feedback.

**Comment by renochost** [comment]
Thanks its done
