### ISSUE TITLE
Importing .csv category list error. v1.7.5.2

### ISSUE THREAD

**Issue by rateforx** [PrestaShop/PrestaShop#14218]
When I try importing categories from a .csv file I get an error.

1. Advanced Parameteres -> Import
2. Choose "category".
3. Upload .csv file. I've tried using the sample one and one of my own.
4. The error occurs regardless of the import settings ("Delete all categories before import", "Skip thumbnails regeneration", "Force all ID numbers", "Send notification email").

![2019-06-14 15_55_41-Import • EroLovers - Firefox Developer Edition](https://user-images.githubusercontent.com/24194569/59514980-61f6b780-8ebe-11e9-88db-57c480e32740.png)

Verification returns:
`{"isFinished":true,"doneCount":3,"totalCount":3}`

The next request returns code 302.

And then the last one is code 500 and throws an exception: "An exception has been thrown during the rendering of a template ("Unable to load template 'file:layout-ajax.tpl'")."

![2019-06-14 16_18_16-Narzędzia dla programistów — Import • EroLovers — https___erolovers com_adminpin](https://user-images.githubusercontent.com/24194569/59515719-0d543c00-8ec0-11e9-8c66-713683c669d6.png)

I've tried clearing caches prior to importing and it didn't change anything.

PrestaShop version: 1.7.5.2
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment]
Hi @rateforx,

I did not manage to reproduce the issue with PS1.7.5.2 & the sample csv.
I attached a video record
https://drive.google.com/file/d/1ruB00FRIJ5VMOJmPEVC3X7JG05u5my8Y/view
Could you please provide your exact file csv to check it.

Thanks!

**Comment by rateforx** [comment]
Here:
[categories_import(1).csv.txt](https://github.com/PrestaShop/PrestaShop/files/3291148/categories_import.1.csv.txt)

I've run out of ideas on how to troubleshoot this...

**Comment by khouloudbelguith** [comment]
@rateforx, I used also your file csv, it is OK
https://drive.google.com/file/d/1fbMp13SXNk8gtEQqtYfJmzBEpZ3cDUdJ/view
If you try to disable some options before the import

- Delete all categories before import
- Skip thumbnails regeneration
- Force all ID numbers 

Does the same issue occur?

Thanks!

**Comment by rateforx** [comment]
As I've said, the error occurs regardless of the settings.

**Comment by rateforx** [comment]
I've reinstalled the shop and got rid of the issue that way. I guess we'll never know what was the problem. Thanks for the help. Over and out.

**Comment by rateforx** [comment]
After installing the shop the issue came back after applying a theme I've bought on the prestashop addons. I've reopened the issue and contacted the theme creator, maybe he'll want to contribute here.

**Comment by khouloudbelguith** [comment]
Hi @rateforx,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
