### ISSUE TITLE
Shop logo has problem if enabled the pagespeed apache module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14229]
Hi
if you add this code in the .htaccess

`<IfModule pagespeed_module>
ModPagespeed On
</IfModule>`

and if the apache module is enabled in the server, it is possible to compress all the images from jpg to webp format

all is ok except for the logo images present in the page

I try to change

`<img class="logo img-responsive" src="{$shop.logo}" alt="{$shop.name}">`
to
`<img class="logo img-responsive" src="{$urls.shop_domain_url}{$shop.logo}" alt="{$shop.name}">`

but I get the same problem, these images are missing from the page

if I set the logo url
https://allarmiwireless.net/shop/img/allarmiwirelessnet-logo-1560628089.jpg
I get the same problem

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/59556844-71632700-8fca-11e9-8de3-a52295ce0eae.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

**Comment by Maofree** [comment]
the issue is done from the .htaccess file present in the img folder
removing it I can see the logo in webp format changed from the pagespeed module of apache

**Comment by Maofree** [comment]
it is necessary to edit this .htaccess to be compatible with pagespeed

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I installed `mod_pagespeed` for apache
![image](https://user-images.githubusercontent.com/16067358/59597115-ffd1c880-90f0-11e9-998a-dfb5ed7c84b2.png)
I added those lines to the .htaccess file
```
<IfModule pagespeed_module>
  ModPagespeed on
  ModPagespeedEnableFilters rewrite_css,combine_css
  ModPagespeedEnableFilters recompress_images
  ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
  ModPagespeedEnableFilters collapse_whitespace,remove_comments
</IfModule>
```
In the BO => Design => Theme & Logo, when we try to add a logo with this type `.webp`
I have an exception
![image](https://user-images.githubusercontent.com/16067358/59597254-47f0eb00-90f1-11e9-9bc2-befd5dd2a516.png)

It is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10356

Is it?

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Maofree** [comment]
hi
in this case it is missing only the image without errors
