### ISSUE TITLE
themes  static custom content convert in selected translation language without module

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14238]
I want to themes custom static content convert in selected translation language without any module used.
-> my prestashop version 1.7.5.1
->I am already tried
`    <h2>{l s='Amazon Product Url Fields' }  </h2> `
plz comment

**Comment by khouloudbelguith** [comment]
Hi @dharmendravirasat,

You can use a custom domain for the new strings.
Something like “Shop.Mytheme”.

It must:

- Start by “Shop”.
- Have 2 levels only. For example “Shop.Mytheme.Checkout” won’t work.
- Not be in CamelCase. For example “Shop.MyTheme” won’t work.

![image](https://user-images.githubusercontent.com/16067358/59589122-28ea5d00-90e1-11e9-8bab-cc788bc5b837.png)

You can try with this  `{l s='Amazon Product Url Fields' d='Shop.Mytheme'}`

Thanks to check & feedback.

**Comment by dharmendravirasat** [comment]
it's working 
Thanks for your  feedback

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
