### ISSUE TITLE
Error when upgrading a added language 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#14247]
**Describe the bug**
Error when upgrading a added language 

**To Reproduce**
1. Go to International -> localization -> language
2. Click on add a language
3. Create a language (English, en, us)
4. Go to international -> traduction 
5. Click on add/upgrade language and choose the language you just add
5. See error

**Screenshots**
https://drive.google.com/file/d/1FE_2kQA5_K_L0-kH8um8rfH5vD-0Q8q7/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14259
