### ISSUE TITLE
The image of the category is not placed correctly in FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14241]
**Describe the bug**

The image of the category is not placed correctly

**To Reproduce**
1. Go to Catalog > Categories
2. Create a category and add description and category cover image
3. See the category in FO
4. The image is placed according to the size of the description

In 1.7.5.2 the image was always at the same place, no matter the description size, but the text could go under the image

**Screenshots**

1.7.6.0
![capture d'écran_1692](https://user-images.githubusercontent.com/13449658/59594999-3c9fbe80-90f5-11e9-9e10-a520d313261f.png)

1.7.5.2
![capture d'écran_1691](https://user-images.githubusercontent.com/13449658/59595033-49241700-90f5-11e9-9ca4-c2134fec31ac.png)

1.7.6.0
![capture d'écran_1689](https://user-images.githubusercontent.com/13449658/59595049-5214e880-90f5-11e9-8aa9-15540023c805.png)

1.7.5.2
![capture d'écran_1690](https://user-images.githubusercontent.com/13449658/59595073-5a6d2380-90f5-11e9-91ec-4145b3c22c00.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14251
