### ISSUE TITLE
Bug in cart - qty spin

### ISSUE THREAD

**Issue by eBug** [PrestaShop/PrestaShop#14257]
**Describe the bug**
When trying to modify quantities in the shopping cart, using the quantity spinner, the arrows disappear and I can't modify quantity anymore

**To Reproduce**
1. Go to http://superorganic.es
2. Add an item to your cart
3. Go to the shopping cart
4. Increase quantity using spinner arrow.
5. spinner vanishes.

**Screenshots**
![image](https://user-images.githubusercontent.com/2424036/59621882-835eda00-9130-11e9-923b-24bf19c0dea4.png)
![image](https://user-images.githubusercontent.com/2424036/59621933-9a053100-9130-11e9-93ab-b019cea7f406.png)

**Additionnal information**
PrestaShop version:  1.7.5.2
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @eBug,

This is a theme issue.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.

I close the issue, feel free to open a new one needed.
Thanks!
