### ISSUE TITLE
Not correct stock quantity in front

### ISSUE THREAD

**Issue by Andrew-LT** [PrestaShop/PrestaShop#14260]
Hi,
I faced some strange situation.
One of the products has quantity left 1. But when I open this product in front it shows 0. However if I add any other product in a cart on the same browsing session and later came back to the previous product, then it already shows correct quantity.
In any other new browsing session the quantity is already ok, but if I clear browsing data (cookies and etc.) then again I see quantity 0.
This issue is with several products.
Some time ago these product were added to carts by customers but didn’t bought. However I cleared these abandoned carts.
I tried to clear cache in back office, but not helped.

Previously I had an issue when I add product to cart but in cart I saw nothing, however in stocks the amount was locked. But this issue seems was related with local carrier module and after disabling it the issue has gone. Maybe it’s still a cause of my current issue…

Pleas help me to find the cause.

PrestaShop version: 1.7.5.1
PHP version: 7.3.4

**Comment by ghost** [comment]
Hi. 
Does Your store was upgraded from previous versions to 1.7.5.1?
Also PrestaShop is not compatbile with PHP 7.3 yet. Please downgrade to stable 7.2 enviroment.
Check this for reference: https://github.com/PrestaShop/PrestaShop/issues/12461

**Comment by khouloudbelguith** [comment]
Hi @Andrew-LT,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by Andrew-LT** [comment]
Hi @PrestaShark and @khouloudbelguith
Thanks for your relpy.
I have downgraded PHP to 7.2.17, ufortunately it didn’t help. I still face the issue.
In response to @PrestaShark question does store was upgraded from previous versions to 1.7.5.1, answer is no, 1.7.5.1 is the initial version I’m using.

How do you think, can it be related with some module I used before?
Or maybe you have any other ideas what I should check?

**Comment by khouloudbelguith** [comment]
@Andrew-LT, thanks for your feedback.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Andrew-LT** [comment]
Hi @khouloudbelguith,
sorry, but I'm totally newbie and not very sure if I'm sending exactly what you were expecting. 
I didn't find PHP error log. I was looking for it in folder /var/log/ via FTP, but found debug mode log in the same folder and also adding some PrtScr from debug mode.

Please let me know if this info is enough for the moment or you need somethig more.

Thanks!

[dev.log](https://github.com/PrestaShop/PrestaShop/files/3312028/dev.log)
![001](https://user-images.githubusercontent.com/51888197/59879887-718d6900-93b4-11e9-911d-5993037291fa.jpg)
![002](https://user-images.githubusercontent.com/51888197/59879900-7520f000-93b4-11e9-860b-5791ed8728f0.jpg)
![003](https://user-images.githubusercontent.com/51888197/59879906-78b47700-93b4-11e9-8762-4b81dbb6de7f.jpg)
![004](https://user-images.githubusercontent.com/51888197/59879924-7ce09480-93b4-11e9-8503-e2137e80ef28.jpg)
![005](https://user-images.githubusercontent.com/51888197/59879930-80741b80-93b4-11e9-8ab0-dc25d7b5e139.jpg)

**Comment by Andrew-LT** [comment]
forgot to mention product id's with whom I have issues and which can be found in log:
"106"
"11"

**Comment by khouloudbelguith** [comment]
@Andrew-LT, thanks for your feedback.
Does this issue occur only with those two products?
When debug mode enabled, no exception is displayed in the FO?
Thanks!

**Comment by Andrew-LT** [comment]
Hi @khouloudbelguith,
no, the issue occur with more products then those two.

I checked FO few times in debug mode and noticed these things:
- when I open shop with Chrome browser I don't get any error messages but I can't add any product to cart. The button "Add to cart" looks active, but when clicking nothing happens;
- when I try to open a shop with Safari I get this screen:
<img width="1280" alt="Screenshot 2019-06-24 at 00 07 01" src="https://user-images.githubusercontent.com/51888197/59982200-350d7780-9617-11e9-9403-555679d48d3f.png">

"omnivalt" is a local carrier module which is disabled at the moment. I disabled it because I suspected that it could cause me some other issue - i.e. I had an issue that if I add a product to a cart, the cart which is displayed on the spot is empty, however the stocks of the product was reserved in BO. After disabling this module the issue has gone.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Andrew-LT,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
I close the issue, feel free to open a new one when needed.

Thanks!
