### ISSUE TITLE
Add recommended length counters to SEO fields in CMS Pages Add/Edit and SEO Add/Edit URLs

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14266]
Suggestion from @CreaNico
We have added a character length counter to SEO fields for Categories:
<img width="905" alt="Capture d’écran 2019-06-17 à 11 56 29" src="https://user-images.githubusercontent.com/3830050/59682024-9aa3d300-91d5-11e9-8dbe-204806e4393d.png">

We should do the same for other SEO fields:
- [x] meta title and meta description for CMS Pages
- [x] title and meta description for URLs (in trafic & SEO page)

Recommended lengths for SEO: 70 for titles, 160 for descriptions (edited)

**Comment by creanico** [comment]
"Recommended lengths for SEO: 70 for titles, 180 for pages"
It's 160 for metadescriptions

**Comment by matks** [comment]
> "Recommended lengths for SEO: 70 for titles, 180 for pages"
> It's 160 for metadescriptions

Bad copy-paste 😅 thanks for pointing it, I fixed it

**Comment by LouiseBonnard** [comment]
Of course, that would be nice!

**Comment by matks** [comment]
Started a PR to fix this https://github.com/PrestaShop/PrestaShop/pull/14469
But I am blocked by a strange behavior from TranslatableType

**Comment by matks** [comment]
3 years later the suggestion from @creanico was finally implemented in https://github.com/PrestaShop/PrestaShop/pull/28668 thanks to @Progi1984
