### ISSUE TITLE
Special character in link widget

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#14272]
**Describe the bug**
a "*" appear in link widget new bloc

**To Reproduce**
1. Go to link widget
2. Click on new bloc
3. Scroll down 

**Screenshots**
<img width="1268" alt="Capture d’écran 2019-06-18 à 16 09 57" src="https://user-images.githubusercontent.com/3034677/59691751-d0e84f00-91e3-11e9-9005-80f067dc9856.png">

**Additionnal information**
PrestaShop version: 1.7.6.X
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Relate to: #14205

**Comment by jolelievre** [comment]
Fixed by https://github.com/PrestaShop/ps_linklist/pull/67
