### ISSUE TITLE
i cant add new product

### ISSUE THREAD

**Issue by elviraprint** [PrestaShop/PrestaShop#14276]
**Describe the bug**
when i'm on my back office and i want to create a new product i got an error messahe from debug mode

**To Reproduce**
1. Go to '.catalog..'
2. Click on 'add a new product....'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
<img width="1233" alt="Capture d’écran 2019-06-18 à 18 12 02" src="https://user-images.githubusercontent.com/51324358/59701065-06e1ff00-91f5-11e9-86c1-ed2e0e065945.png">
<img width="1141" alt="Capture d’écran 2019-06-18 à 18 11 55" src="https://user-images.githubusercontent.com/51324358/59701078-0cd7e000-91f5-11e9-9067-16c5455feaf8.png">
<img width="1128" alt="Capture d’écran 2019-06-18 à 18 11 48" src="https://user-images.githubusercontent.com/51324358/59701083-106b6700-91f5-11e9-908c-1d90d0212ae6.png">
<img width="1290" alt="Capture d’écran 2019-06-18 à 18 11 30" src="https://user-images.githubusercontent.com/51324358/59701091-13feee00-91f5-11e9-97be-33156bf977ae.png">

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @elviraprint,

You have an issue with the module `productdesigner`.
![image](https://user-images.githubusercontent.com/16067358/59747794-975e2500-9271-11e9-90c0-cd55b1f9c985.png)
As it's not the module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
