### ISSUE TITLE
Client tab is not display properly in laptop

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#14275]
**Describe the bug**
Client tab is not display properly in laptop

Appear only with little screen.

**To Reproduce**
1. Go to customer page in BO
2. See the customer tab

**Screenshots**
<img width="1272" alt="Capture d’écran 2019-06-18 à 16 52 53" src="https://user-images.githubusercontent.com/3034677/59695113-f9734780-91e9-11e9-85b1-1355fab9274c.png">

**Additionnal information**
PrestaShop version: 1.7.6.X
PHP version: N/A

**Comment by jolelievre** [comment]
Fiexed by #14290

**Comment by matks** [comment]
And https://github.com/PrestaShop/PrestaShop/pull/14401
