### ISSUE TITLE
[BO IMPROVEMENT] Product specific prices UI/UX wording

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14274]
Hi.
When user change type of discount to percentage "input-group-append" are still showing zł (currency) instead of %.
![wording2](https://user-images.githubusercontent.com/8243273/59694681-54586f00-91e9-11e9-8a8f-92b551b8acf9.jpg)

Removing class "input-group-append" will be just fine!

Trivial but...
Also Euro sign is weird in that place. Missing labels not helping also.
![wording](https://user-images.githubusercontent.com/8243273/59694670-502c5180-91e9-11e9-9527-2c9a2c79a702.jpg)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13382 to fix the issue.
It is added in the next major release PS1.7.7.
Thanks to check & feedback

**Comment by ghost** [comment]
Hello @khouloudbelguith 
This is it. Thanks!

**Comment by khouloudbelguith** [comment]
@PrestaShark, you are welcome!
Feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #12800
