### ISSUE TITLE
hookdisplayBackOfficeCategory is not in prestashop1.7.6.0 beta

### ISSUE THREAD

**Issue by Webpog** [PrestaShop/PrestaShop#14279]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Webpro2019,

I did not manage to reproduce the issue with PS1.7.6.0beta1.
![image](https://user-images.githubusercontent.com/16067358/59753331-ced1cf00-927b-11e9-93c5-2ed034382c6a.png)

I attached a screen record
https://drive.google.com/file/d/1ORXow7eJFTQyd5iOPD2Ne4F8owEcHni0/view
Thanks to check & feedback.

**Comment by Webpog** [comment]
ok, thank you, the problem in my side then

**Comment by khouloudbelguith** [comment]
@Webpro2019, thanks for your feedback.
Feel free to open another one when needed. 

Thanks!
