### ISSUE TITLE
Revision History and Deleted Items Folder (Recycle Bin) on Blog Posts

### ISSUE THREAD

**Issue by ToyPerson** [PrestaShop/PrestaShop#14278]
Can we have the following features on PrestaBlog?

1. Revision history on posts and ability to restore to previous saved format.

2. Deleted items folder and the ability to recover deleted posts,

**Comment by khouloudbelguith** [comment]
Hi @ToyPerson,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
