### ISSUE TITLE
Autoupgrade module cant find 1.7.6.0 beta 1 in beta channel?

### ISSUE THREAD

**Issue by psppro26** [PrestaShop/PrestaShop#14285]
Beta is released but the Autoupgrade module cant find 1.7.6.0 beta 1 in beta channel?

**Comment by khouloudbelguith** [comment]
Hi @psppro26,
You can use the channel "Local archive".

- install the autoupgrade module
- Download the zip of PrestaShop 1.7.6.0beta1
- Put it in the folder admin / autoupgrade / download
- in the configuration page of the module select "local archive" as a channel
- Specify the version to which we are upgrading (example: 1.7.6.0)
- Launch the upgrade

PS: it is not currently possible to perform an automatic upgrade from the Beta to the stable version
Remember, this beta version is beta release software.
Do not use it on your production shop!

I close the issue, feel free to open a new one when needed.

Thanks!
