### ISSUE TITLE
Produit en rupture de stock

### ISSUE THREAD

**Issue by MaisonMONTEL** [PrestaShop/PrestaShop#14280]
Bonjour,

Nous rencontrons un problème lors de la modification du statut d'un produit.

Nous voulons refuser les commandes et mettre le produit en rupture de stock et le produit reste en rupture de stock pendant quelques minutes avant de se remettre automatiquement en stock.

Merci de nous aider pour ce problème.

Bien à vous.

**Comment by khouloudbelguith** [comment]
Hi @MaisonMONTEL,

English is the norm on this bug tracker.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @MaisonMONTEL,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
