### ISSUE TITLE
Module ps_feeder not work fine

### ISSUE THREAD

**Issue by gescocis** [PrestaShop/PrestaShop#14295]
Hello,
I recently installed the ps_feeder module in my store, but I think there is some bug as I can't get a link for valid RSS feeds.

From various guides on the forums I realized that to have a link to my RSS feeds based on the category it is sufficient to use this link >>>> https://gescotradingsrl.com/module/ps_feeder/rss?id_category=3&orderby=price&orderway=asc
where id_category = 3 is the identifier of my category.

When I try to view the feed in the browser it gives me the error as shown in the screenshot >>> http://prntscr.com/o4aenp

While if I try to pass the link to feedburner to spread on social media or social media managers, the system returns the following errors: It does not seem to be a valid XML feed, or Timeout while fetching the feed.

Where is the mistake?

Some System Information:
- Linux server information # 4 SMP Wed Jun 19 20:26:04 UTC 2019 x86_64
- Server software version: Apache
- PHP version: 7.2.19
- Memory limit: 512M
- Maximum execution time: 300
- Max. Size of files to upload: 20M
- MySQL engine: InnoDB
- MySQL driver: DbPDO
- Required parameters: OK
- Optional parameters: OK
- PrestaShop version: 1.7.5.0
- Store URL: http://gescotradingsrl.com/
- Theme currently used: leo_bicmart

Thank you so much for the help

**Comment by khouloudbelguith** [comment]
Hi @gescocis,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 & the ps_feeder v1.0.1.
When I try to access to this link http://shop/fr/module/ps_feeder/rss?id_category=0&amp;orderby=date_upd&amp;orderway=desc
=> it is well displayed
![image](https://user-images.githubusercontent.com/16067358/59840756-e6c45400-934a-11e9-85f1-28aa7cd0d78a.png)

```
<!--
 begin module:ps_feeder/views/template/front/rss.tpl 
-->
<!--
 begin /projet/beta176/modules/ps_feeder/views/template/front/rss.tpl 
-->
<rss version="2.0">
<channel>
<title>
<![CDATA[ 1760tu ]]>
</title>
<description>
<![CDATA[ Boutique propulsée par PrestaShop ]]>
</description>
<link>http://projet/beta176/</link>
<generator>PrestaShop</generator>
<webMaster>khouloud.belguith@prestashop.com</webMaster>
<language>fr</language>
<image>
<title>
<![CDATA[ 1760tu ]]>
</title>
<url>http://projet/beta176/img/logo.png</url>
<link>http://projet/beta176/</link>
</image>
<item>
<title>
<![CDATA[ T-shirt imprimé colibri - 23,90 € ]]>
</title>
<description>
<![CDATA[
<img src="http://projet/beta176/2-small_default/hummingbird-printed-t-shirt.jpg" title="T-shirt imprimé colibri" alt="thumb" /><p><span style="font-size:10pt;font-style:normal;">Coupe classique, col rond, manches courtes. T-shirt en coton pima extra-fin à fibres longues. </span></p>
]]>
</description>
<link>
<![CDATA[
http://projet/beta176/fr/hommes/1-hummingbird-printed-t-shirt.html
]]>
</link>
</item>
</channel>
</rss>
<!--
 end /projet/beta176/modules/ps_feeder/views/template/front/rss.tpl 
-->
<!--  end module:ps_feeder/views/template/front/rss.tpl  -->
```
Thanks to check & feedback

**Comment by gescocis** [comment]
Can you give me the link for correct module? I try to reinstall
Thanks

**Comment by khouloudbelguith** [comment]
@gescocis, try to navigate to your BO => Module Catalog page => search for the ps_feeder module & install it.
![image](https://user-images.githubusercontent.com/16067358/59841690-c0071d00-934c-11e9-88ee-34688992ed72.png)

Thanks!

**Comment by gescocis** [comment]
Ok, it same work fine when oi try to viewing on the browser, but i f i pass the link in feedburner the system give me the error: NON VALID XML FILE

Thank you for your help

**Comment by khouloudbelguith** [comment]
@gescocis, maybe you need for example to use this `SimpleXMLElement::asXML` after getting the XML file.
It return a well-formed XML string based on SimpleXML element
https://www.php.net/manual/en/simplexmlelement.asxml.php
Since it is not a PrestaShop core issue, I close the ticket, feel free to open a new one when needed.

Thanks!
