### ISSUE TITLE
customer payment

### ISSUE THREAD

**Issue by elviraprint** [PrestaShop/PrestaShop#14297]
**Describe the bug**
when the customer wants to pay with strip i receive the money but there is an error message show on the customer page. but i receive the money well on my stripe account i dont know how to coorect that where does it come from ?

**To Reproduce**
1. Go to '.buy a product..'
2. Click on '..buy..'

**Screenshots**

If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @elviraprint,

Thanks for your report.
Have you tried to contact the module author about your issue?
https://addons.prestashop.com/fr/contactez-nous?id_product=24922
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @elviraprint,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
