### ISSUE TITLE
Duplicate Product in BO with several taxes (multishop)

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#14302]
**To Reproduce**

1. Set a multishop with 2 shops (or more) and several taxe rule. For instance:
- shop FR with Tax rate FR 20%
- shop CH with Tax rate CH 10%
2. Create a product in context all shop
3. On each shop set a specific tax rate
4. Finally on products board, select the previous product and click on duplicate product on all shop context.

**Describe the bug**

A product duplicated from all shop context set the default shop's tax for all shops. It should set the same tax than the original product (the tax corresponding to the shop).

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: all

**Comment by khouloudbelguith** [comment]
Hi @202-ecommerce,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
Thanks for the fix!
