### ISSUE TITLE
Customer details page is not well displayed - BO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#14301]
**Describe the bug**
In the BO => customers page, when you try to add or edit a customer, the customer details page is not well displayed.
![image](https://user-images.githubusercontent.com/16067358/59851496-aeca0a80-9364-11e9-979b-4bd93eb0ccf1.png)

With PS1.7.6.0beta1 => OK

**To Reproduce**
1. Go to BO => Customers page
2. Add/Edit a customer
3. See error

**Additionnal information**
PrestaShop version: branch 1.7.6.x
PHP version: 7.0

**Comment by matks** [comment]
Issue introduced by PR https://github.com/PrestaShop/PrestaShop/pull/14290 so now we need to find a way to fix it without removing the bugfix https://github.com/PrestaShop/PrestaShop/pull/14290

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14401
