### ISSUE TITLE
An incorrect flag discount is displayed in the FO => Product page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#14321]
**Describe the bug**
An incorrect flag discount is displayed in the FO => Product page => it shouldn't.
![image](https://user-images.githubusercontent.com/16067358/59918512-d7add680-941c-11e9-8197-addc9a4892d0.png)

**To Reproduce**
1. Go to BO => Shop Parameters => Product Settings
2. Set `Quantity discounts based on ` to Combinations
![image](https://user-images.githubusercontent.com/16067358/59918583-062bb180-941d-11e9-9376-01bd0ed20665.png)

3. Create a product with combinations
4. Set a combination c1 of a product with a discount price.
5. Set that combination as default
6. Go to FO => product page
7. Change the combination => see error => A flag discount is displayed in the FO => Product page => it shouldn't.

PS: if we set another combination as default which doesn't have any discount, the flag is not displayed anymore on the product page.
![image](https://user-images.githubusercontent.com/16067358/59919195-b5b55380-941e-11e9-9875-d251dc946982.png)

In the PS1.7.5.2, in all combinations, the flag is not displayed.
**Screenshots**
https://drive.google.com/file/d/1kxlO26U68JWx84mptOaAbw_JWDvyaSuQ/view

**Additionnal information**
PrestaShop version: 1.7.6.x / 1.7.6.0beta1
PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14325

**Comment by Mreco83** [comment]
Hello. How do I fix an error in prestashop 1.7.5.2? In prestashop 1.7.5.2 I don't see a file like themes / _core / js / product.js
