### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by xtoffx** [PrestaShop/PrestaShop#14333]
**Describe the bug**
suddenly my shop does not work anymore. it is a version 1752 that I use to start an activity. I had not finished filling it. see here the error message :class Order extends OrderCore { /** * Return a unique reference like : GWJTHMZUN#2 * * With multishipping, order reference are the same for all orders made with the same cart * in this case this method suffix the order reference by a # and the order number * * @since 1.5.0.14 */ public static function generateReference() { $Context = Context::getContext(); $id_order_max = Db::getInstance()->getValue('SELECT max(`id_order`) FROM `'._DB_PREFIX_.'orders` WHERE `id_shop`="'.pSQL($Context->shop->id).'"'); return $id_order_max+1; } }
BO is ok but I cannot use ORDERS I obtain same error
**To Reproduce**

I dont know, it appears on start

**Screenshots**
![chrome_2019-06-22_01-56-25](https://user-images.githubusercontent.com/31537371/59960655-b0faa900-94cb-11e9-8d72-88b225297b6e.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @xtoffx,

Could you please navigate to your BO => Advanced Parameters => Performance => Enable the option "Disable all overrides", clear cache from your shop & your browser & feedback.
![image](https://user-images.githubusercontent.com/16067358/60000887-0adea880-965d-11e9-8c70-cc96fdb7f283.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @xtoffx,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
