### ISSUE TITLE
Improve "welcome" email wording

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14337]
**Is your feature request related to a problem? Please describe.**

The "welcome" email sent to new registered customers has a section "login details" that says "Here are your login details". However only the email is provided in this section.

I guess a long time ago this section contained the email and the password, and the password was removed because it is a bad security practice. But now the section name is not accurate with the section content.

**Describe the solution you'd like**
Rename "Here are your login details" to something more accurate. Or just say "Reminder: you registered with email X".

Mail template in French:
![Capture d’écran 2019-06-21 à 10 43 54](https://user-images.githubusercontent.com/3830050/59978835-0ecce500-95e1-11e9-9d8d-1b0da2cf029f.png)

**Comment by LouiseBonnard** [comment]
Hi @matks, thanks for reporting it. It has been changed recently but we can think about a more accurate wording for the next version. Actually, _login details_ has been kept since it was generic enough and also used in two other email templates, password and password query. But it could make sense to turn it into _login email_ when the password is not mentioned anymore.

**Comment by LouiseBonnard** [comment]
@jolelievre, do you think it will be possible for us to modify the title of some emails in the next version?

**Comment by jolelievre** [comment]
@LouiseBonnard sure it can be done, too bad I didn't see this issue last week we could have integrated it in the 176

**Comment by LouiseBonnard** [comment]
Both the wording and the design of the PrestaShop emails have been improved in 1.7.6, it is the modern theme template but I can see improvements that could still be made:

- replace _login details_ with _login email address_ inside the **account** email
- replace the _Go to your customer account to learn more about it._ wording inside the frame to keep consistency between both **order_canceled** and **order_changed** emails
- fix the variables typo in the **order_customer_comment** email, it should be _Customer: {firstname} {lastname} ({email})_
- delete quotation marks in both **productoutofstock** and **log_alert** emails when mentioning the section of the back office - it should be _You can check for it in the Advanced Parameters > Logs section of your back office._, not _You can check for it in the "Advanced Parameters" > "Logs" section of your back office._.

**Comment by LouiseBonnard** [comment]
Oh and, @colinegin, you did have a remark about the wording in the footer (when it is said _powered by PrestaShop_), right?

UPDATE: as seen with @colinegin today, it needs to be removed
