### ISSUE TITLE
Cart blocked on personal information page could not proceed to step 3: delivery.

### ISSUE THREAD

**Issue by gaecde** [PrestaShop/PrestaShop#14335]
Hello,
I simulated an order, after having filled the address, the page remains blocked. Can not finalize the order.
I write you all the steps:

1. On the product page, I select the number example:4, it does not set on 4, it comes back on 1.
2. Click on 'add to cart'
3. On the basket page, everything is ok the number of products selected (4) is taken into account.
4.  Click on 'place an order'
5. page: 1.personal information, I filled.
6. Click on 'next'
7. page: 2.adress,  I filled.
8.  Click on 'next' : The page remains blocked

I disabled modules not developed by PrestaShop
I emptied the browser cache.
When I empty the prestashop cache: 500 Server Error. Refresh: all caches have been successfully erased.
But it does not change anything.

PrestaShop version: 1.7.5.1
PHP version: 7.2.19
server: 1&1 Inios
site: https://gaec-de-fugieres.fr/

Thank you in advance for your help.

**Comment by khouloudbelguith** [comment]
Hi @gaecde,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by gaecde** [comment]
Hello,
thank for your help.
this is console javascript
![console](https://user-images.githubusercontent.com/51715158/60002914-ea691b00-9669-11e9-84ad-fcd7c533cc0a.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, thanks for your feedback.
We need also to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by gaecde** [comment]
I have a message error, clic on 'performance'
![acces performance](https://user-images.githubusercontent.com/51715158/60006033-f7890880-966f-11e9-9efa-3ab74ecf9fa2.JPG)
![message logs](https://user-images.githubusercontent.com/51715158/60006045-feb01680-966f-11e9-908f-0d0083e0cdb8.JPG)
![deprecations](https://user-images.githubusercontent.com/51715158/60006061-05d72480-9670-11e9-8797-4d2eaf0ce94f.JPG)

**Comment by gaecde** [comment]
![debug](https://user-images.githubusercontent.com/51715158/60006248-55b5eb80-9670-11e9-985a-7e256a6d8021.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, this is normal behavior, just click on 'I understand the risk', it is a token regeneration.

Thanks!

**Comment by gaecde** [comment]
Which folder to choose for the php report? please.
![dossier](https://user-images.githubusercontent.com/51715158/60007179-15f00380-9672-11e9-9afb-ea66d6199921.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, Php stores error logs in `/var/log/apache2` if PHP is an apache2 module. Shared hosts are often storing log files in your root directory `/log` subfolder.
If you don't have it, you should ask your hosting provider.

Thanks!

**Comment by gaecde** [comment]
Error reports are not enabled by default on the host.

**Comment by khouloudbelguith** [comment]
@gaecde, exceptions from debug mode & PHP error log will help us to understand what's wrong.
Thanks for your understanding!

**Comment by gaecde** [comment]
yes I understand, I try to set up the error reports.

**Comment by khouloudbelguith** [comment]
@gaecde, thanks!
Waiting for your feedback.

**Comment by gaecde** [comment]
Do you want the php report for the whole site or one folder?

**Comment by khouloudbelguith** [comment]
@gaecde, no, just the debug mode report & PHP error log.

Thanks!

**Comment by gaecde** [comment]
Hello,
Sorry, I still can not find what to do.
Can you help me ?

Thank you again for your help

**Comment by khouloudbelguith** [comment]
@gaecde, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by gaecde** [comment]
Maybe that's it?

*ERROR* 	v1.7.5.1	2019/06/25 - 00:19:01: Table 'db7000011.m16b_layered_filter_block' doesn't exist<br /><br /><pre>SELECT data FROM m16b_layered_filter_block WHERE hash="d8a7a0bd0dd26c25e7a3cca55b3f207d" LIMIT 1</pre> at line 769 in file classes/db/Db.php
*ERROR* 	v1.7.5.1	2019/06/25 - 12:40:26: Table 'db7000011.m16b_layered_filter_block' doesn't exist<br /><br /><pre>SELECT data FROM m16b_layered_filter_block WHERE hash="4ce48d3950215b0bdd589337b192e00f" LIMIT 1</pre> at line 769 in file classes/db/Db.php

**Comment by gaecde** [comment]
That's it ?


[2019-06-25 12:49:20] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_controller":"web_profiler.controller.profiler:panelAction","token":"2325ef","_route":"_profiler"},"request_uri":"https://gaec-de-fugieres.fr/tzqdo2nyibxqof3l/index.php/_profiler/2325ef?_token=nda8h9IXqGUj2Xov-s2DbBQWhtF9Y7TOBhGtaG-KL6g&panel=cache","method":"GET"} []
[2019-06-25 12:49:20] doctrine.DEBUG: SELECT name FROM m16b_module WHERE active = 1 [] []
[2019-06-25 12:49:20] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /homepages/13/d773662125/htdocs/clickandbuilds/PrestaShop/gaec_de_fugieres/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-06-25 12:49:20] request.INFO: Matched route "_profiler_search_bar". {"route":"_profiler_search_bar","route_parameters":{"_controller":"web_profiler.controller.profiler:searchBarAction","_route":"_profiler_search_bar"},"request_uri":"https://gaec-de-fugieres.fr/tzqdo2nyibxqof3l/index.php/_profiler/search_bar?_token=nda8h9IXqGUj2Xov-s2DbBQWhtF9Y7TOBhGtaG-KL6g&panel=cache","method":"GET"} []

**Comment by khouloudbelguith** [comment]
@gaecde, have you some issues with the ps_facetedsearch module?
Could you please try to re-install it, clear cache, check & feedback.

Thanks!

**Comment by gaecde** [comment]
It's done the problem is still there.

 This report was displayed instead of my homepage in debug mode.

(1/1) ContextErrorException
Notice: Undefined index: slider

in c8a1147e449eb47424a25b568c3463e8f1780f0d_2.module.epnewproductsviewstemplat.cache.php line 42
at content_5d13d5d48f8f80_31174518(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_runtime_updatecache.php line 38
at Smarty_Internal_Runtime_UpdateCache->updateCache(object(Smarty_Template_Cached), object(SmartyDevTemplate), false)
in smarty_template_cached.php line 143
at Smarty_Template_Cached->render(object(SmartyDevTemplate), false)
in smarty_internal_template.php line 211
at Smarty_Internal_Template->render(false, 0)
in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)
in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)
in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()
in Module.php line 2413
at ModuleCore->fetch('module:ep_newproducts/views/templates/hook/ep_newproducts.tpl', 'ep_newproducts|1|3|3|8')
in ep_newproducts.php line 206
at Ep_NewProducts->renderWidget('displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))
in Hook.php line 971
at HookCore::coreRenderWidget(object(Ep_NewProducts), 'displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))
in Hook.php line 923
at HookCore::exec('displayHome')
in IndexController.php line 39
at IndexControllerCore->initContent()
in Controller.php line 281
at ControllerCore->run()
in Dispatcher.php line 511
at DispatcherCore->dispatch()
in index.php line 28

**Comment by khouloudbelguith** [comment]
@gaecde, thanks for your feedback.
You have an issue with the "New products block" module, could you please try to re-install it agian.

Thanks!

**Comment by gaecde** [comment]
Hello,
it is done ! but the problem is still there.

**Comment by khouloudbelguith** [comment]
@gaecde, could you please try to rename the `ep_newproducts` folder to `ep_newproducts_old` into the `Project_Folder/modules/` folder
Thanks to check & feedback.

**Comment by gaecde** [comment]
it is done ! Nochange.
I erased the browser cache.
try again to make an order and this report appeared:

(1/1) ContextErrorExceptionNotice: session_start(): ps_files_cleanup_dir: opendir(/tmp/.priv) failed: Permission denied (13)
--
in FrontController.php line 699
at FrontControllerCore->prepareNotifications()in FrontController.php line 663
at FrontControllerCore->display()in Controller.php line 301
at ControllerCore->run()in Dispatcher.php line 511
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment]
@gaecde, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by gaecde** [comment]
I must delete: prod & dev?

**Comment by gaecde** [comment]
or the files at the back of prod and dev?

**Comment by khouloudbelguith** [comment]
@gaecde, yes prod & dev folders.
Thanks!

**Comment by gaecde** [comment]
it is done ! No change.

**Comment by khouloudbelguith** [comment]
@gaecde, We need to retrieve the debug mode report in order to find out what's wrong.

Thanks!

**Comment by gaecde** [comment]
![RAPPORT](https://user-images.githubusercontent.com/51715158/60335872-2cae9700-999f-11e9-8842-4a5b28f009eb.JPG)

**Comment by gaecde** [comment]
![RAPPORT2](https://user-images.githubusercontent.com/51715158/60335997-77301380-999f-11e9-9d8a-94c7964b5321.JPG)

**Comment by gaecde** [comment]
![RAPPORT3](https://user-images.githubusercontent.com/51715158/60336013-82833f00-999f-11e9-98f8-d6c056720108.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, You need to enable debug mode in your store and debug request which is sent for the  "Continue" second step in your browser, using DevTools, so:

1. enable debug mode
2. go to the checkout page
3. open up developer tools
4. go to Network tab
5. Click on "continue" the second step
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by gaecde** [comment]
that's it ?
![RAPPORT4](https://user-images.githubusercontent.com/51715158/60340199-38a05600-99ab-11e9-9773-4bedc18b3db2.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, no.
debug mode enabled? there is no exception on the checkout page?

Thanks!

**Comment by gaecde** [comment]
the debug mode is activated but nothing is displayed

**Comment by khouloudbelguith** [comment]
@gaecde, in the BO => Advanced Parameters =>  Performance, could you please try to enable the "Disable all overrides" option, clear cache, check & feedback.

Thanks!

**Comment by gaecde** [comment]
its good.
I erased the chrome navigation data.
I reennished and the message appeared.
![RAPPORT5](https://user-images.githubusercontent.com/51715158/60341106-b82f2480-99ad-11e9-8cd0-8f5d99239af0.JPG)

**Comment by khouloudbelguith** [comment]
@gaecde, this is a permission issue on your server, you need to check your host about this issue.
Thanks to check with your host & feedback.

**Comment by gaecde** [comment]
ok i'll see with them and you'll know.
Thanks for your help.

**Comment by khouloudbelguith** [comment]
@gaecde, thanks!
Waiting for your feedback.

**Comment by gaecde** [comment]
Hello,
Here are the returns of my host, he tells me that there is a problem of way.
Because I am trying to open a folder (/tmp/.priv) on shared server directly.
What is not possible at the level of your right of access.
The problem would come from the fact that I install the module MTARGET, module that sends sms on the mobile phone. It will change the access path.
I have uninstalled the module, cleared the cache. But that does not correct the problem.
How to change the access path?

**Comment by khouloudbelguith** [comment]
@gaecde, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the theme module via your addons.prestashop.com account, they are the only ones to help you with it.
I close the issue, feel free to open a new one when needed.
Thanks!
