### ISSUE TITLE
your address is incomplete

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#14332]
Prestashop 1.7.5.2 on php 7.2.19 on debian
Why this error? https://nimb.ws/oWcC1g

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

In your BO => Customers => Addresses page, you have some fields required.
But those fields required are not added tour address format from your country.
You need to navigate to your BO => Internation => Locations => Countries => Edit your country => Add the missing field to your address format & Save.

Thanks to check & feedback.

**Comment by centoasa** [comment]
You're perfectly right! Thanks so much @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@centoasa, you are welcome, feel free to open a new one when needed.

Thanks!
