### ISSUE TITLE
Saving Friendly URL: Error 500 (identical error in clearing the cache)

### ISSUE THREAD

**Issue by ArteInfoRM** [PrestaShop/PrestaShop#14343]
Shop Parameters -> Traffic & SEO -> Set up URLs -> Save
Blank Page Error 500 

Active Debug Mode - No Error
Log Server (Error Save URLs no Debug Mode): 
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Tools' not found in 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/db/Db.php:794\nStack trace:\n#0 
/var/www/vhosts/soundtaste.shop/httpdocs/config/alias.php(48): DbCore->escape('configuration', false)\n#1 
/var/www/vhosts/soundtaste.shop/httpdocs/config/alias.php(53): pSQL('configuration')\n#2 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/Configuration.php(155): bqSQL('configuration')\n#3 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()\n#4 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')\n#5 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()\n#6 [internal function]: 
PrestaShopAutoload->load('Tools')\n#7 /var/www/vhosts/soundtaste.shop/httpdocs/config/config.inc.php(85): spl_autoload_call('Tools')\n#8 
/var/www/vhosts/soundtaste.shop/httpdocs/admWine17/index.php(...\n', 
referer: https://www.soundtaste.shop/admWine17/index.php/configure/shop/seo-urls/?_token=

Advanced Parameters -> Performance -> Clear Cache 
Blank Page Error 500 
With active debug mode:
Fatal error: Uncaught Error: Class 'Tools' not found in /var/www/vhosts/soundtaste.shop/httpdocs/classes/db/Db.php:794 
Stack trace: #0 /var/www/vhosts/soundtaste.shop/httpdocs/config/alias.php(48): DbCore->escape('configuration', false) #1 
/var/www/vhosts/soundtaste.shop/httpdocs/config/alias.php(53): pSQL('configuration') #2 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/Configuration.php(155): bqSQL('configuration') #3 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/Configuration.php(209): ConfigurationCore::loadConfiguration() #4 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...') #5 
/var/www/vhosts/soundtaste.shop/httpdocs/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex() #6 
[internal function]: PrestaShopAutoload->load('Tools') #7 /var/www/vhosts/soundtaste.shop/httpdocs/config/config.inc.php(85): 
spl_autoload_call('Tools') #8 /var/www/vhosts/soundtaste.shop/httpdocs/admWine17/index.php(42): require('/var/www/vhosts...') 
in /var/www/vhosts/soundtaste.shop/httpdocs/classes/db/Db.php on line 794

**Additionnal information**
PrestaShop 1.7.5.2
CentOS Linux 7.6.1810
Plesk Onyx 17.5.3
PHP 7.1.30 or 7.2.19
Check your configuration
Required parameters: OK
Optional parameters: OK

**Comment by khouloudbelguith** [comment]
Hi @ArteInfoRM,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by ArteInfoRM** [comment]
Already done the manual deletion, but the problem with Set up URLs remains, for now I only know this in 1.7.5.2.

**Comment by khouloudbelguith** [comment]
@ArteInfoRM, when debug mode is enabled => there is no exception & the page is well displayed?

Thanks!

**Comment by ArteInfoRM** [comment]
When I try again now, I get this error:
http://prntscr.com/o5z2fw
http://prntscr.com/o5z2y5

Before manually deleting, no message appeared with debug active.

**Comment by ArteInfoRM** [comment]
To re-enter the BO, I had to delete dev and prod again.

**Comment by ArteInfoRM** [comment]
I don't know if it is connected, but in version 1.7.5.2 there are no links to Price Drop and Best Sales in the sitemap (front-end). Their url's are not friendly url, but index.php?controller=prices-drop and index.php?controller=best-sales

**Comment by ArteInfoRM** [comment]
the only solution found for now is to modify in classes/db/Db.php on line 794:

```
if (!$html_ok) {
   $string = strip_tags(Tools::nl2br($string));
}
```
in
```
if (!$html_ok) {
   $string = strip_tags(nl2br($string));
}
```

it's not a clean thing ...

**Comment by khouloudbelguith** [comment]
@ArteInfoRM, Could you please try to run this SQL query 

`select * from  ps_configuration where name LIKE 'PS_ROUTE%'` & provide me the result.
In my case, 
![image](https://user-images.githubusercontent.com/16067358/60026851-4a74b700-9694-11e9-9594-04f3ea108006.png)

Thanks!

**Comment by ArteInfoRM** [comment]
![image](https://user-images.githubusercontent.com/41371761/61201440-ce92eb00-a6e4-11e9-80ec-4fa570656a89.png)

**Comment by khouloudbelguith** [comment]
Hi @ArteInfoRM,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!

**Comment by ArteInfoRM** [comment]
The problem is the same as this issue
https://github.com/PrestaShop/PrestaShop/issues/12667

PrestaShop 1.7.6.0 has the problem with Server Plesk Onyx ver 17.8.11

**Comment by ArteInfoRM** [comment]
The error with Plesk 17.5.3 and 17.8.11 occurs with FPM served by Apache, using FastCGI, prestashop does not generate the error. 

![image](https://user-images.githubusercontent.com/41371761/62620667-37ebcf80-b91a-11e9-8d0a-404794e17cc4.png)
