### ISSUE TITLE
Fistname required

### ISSUE THREAD

**Issue by josejecas** [PrestaShop/PrestaShop#14345]
I have a problem when the customer tries to place an order, as you can see in the video.

https://drive.google.com/file/d/1NKa1YDoNiF6ny2rmmqGvrtm2kxPV9UBn/view

**Comment by khouloudbelguith** [comment]
Hi @josejecas,

Thanks for your report.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
Hi @josejecas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
