### ISSUE TITLE
Cannot get into customer service module

### ISSUE THREAD

**Issue by OriginalMillhouse** [PrestaShop/PrestaShop#14347]
Using Prestashop 1.7.5.2 changed my imap settings and now I cannot get into the customer service module!   When I try to go to Sell > Customer Service > Customer Service I get a Gateway timeout 504 error. Then I cannot open my admin page at all for a few minutes.

There are some other threads about this issue, but they reference database tables that I do not have.  I do have database table psir_customer_message_sync_imap 

I am pretty new to Prestashop and really appreciate any solutions! 

Thank you for your help!

**Comment by khouloudbelguith** [comment]
Hi @OriginalMillhouse,

Could you please try to delete the data related to IMAP config in the table ps_configuration: PS_SAV_IMAP_URL, PS_SAV_IMAP_PORT, PS_SAV_IMAP_USER and PS_SAV_IMAP_PWD, clear cache and feedback.

**Comment by OriginalMillhouse** [comment]
Ok I feel stupid. I found PS_SAV_IMAP_URL, PS_SAV_IMAP_PORT, PS_SAV_IMAP_USER and PS_SAV_IMAP_PWD, they are in the psir_configuration table. Will clear and write back.

**Comment by khouloudbelguith** [comment]
@OriginalMillhouse, thanks for your feedback.
Since it fixed, I close the issue, feel free to open a new one when needed.

Thanks!
