### ISSUE TITLE
CSS classes / element attributes called by core.js have to be marked 

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#14346]
It would be very, very helpful for anyone designing / updating a theme if all classes, ids, data-attributes or anything else required by the core could be prefixed in the starter & classic theme as such.

Ideally it would be something like class="js-core-xyz"

I remember reading this was an aim on the developer.prestashop.com docs before they got migrated to devdocs.prestashop.com but I can't find anything on it now.

I just spent a good part of day debugging why the product page theme wasn't working after updating to the newest version of PS. I had to debug the core itself line by line only to find it was because I didn't have a div class="product-actions" in my theme, which the core requires to update thumbnails. If mandatory element attributes were easily signposted in the classic theme I could just compare my template file like for like and spot any missed element attributes.

I am aware this might break a lot of themes in the short run but it seems good coding practice for the long run.  You could either check for both attributes for backward comparability while you deprecate.

I know not a big one but would make things feel more dev friendly and probably save a bunch of hidden wasted hours in the long run.

**Comment by khouloudbelguith** [comment]
Hi @haveyougotanypets,

Thanks for your report.
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by tlhuillier** [comment]
I think this would be very useful.
I find myself often writing comments like the following in the templates I write :
```
{* @info `.delivery-option` class is used by `core.js` *}
{*  @info `.add` class is used by `core.js` in updateProduct *}
{* @info `.continue` class is used by `core.js` *}
```

I think like doing this by Prestashop itself would force some consistency:
- like always using `.js-` prefix on classes used by javascript (and stop writing CSS styles on such classes)
- or maybe always using `data-stuff` to attach JS code on HTML elements.

**Comment by PierreRambaud** [comment]
I don't know if it's a good idea. In fact, it's up to people who create modules to add `my-module-class`, and if they remove content, it's also up to them to be sure nothing is broken :thinking: 
Wdyt @NeOMakinG ?

**Comment by NeOMakinG** [comment]
Since 2 months, every selectors used in core js and theme js are listed inside these two files, I think this is already enough in order to know the class you deleted is used by the core, by the way having every classes used by the js prefixed by a `js-` is a good practice that we already follow a lot inside the BO and we should do the same on the classic theme !

The question is, should we do it inside a minor version using multiple selectors (with old ones and new ones) ?

It would be safer to wait a major version, and I think it's enough to have these new 2 files, but it's doable and I'll think about it !

https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/selectors.js
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/selectors.js

**Comment by haveyougotanypets** [comment]
Hi 

@NeOMakinG thanks for those two links, did not know about them and they will be a very useful reference for some theme upgrades I am about to make.

@PierreRambaud I agree that it is up to devs to test to make sure nothing is broken but I still think the idea of adding warning signs to potential hazards is a good idea, just like we do in RL. Ideally everyone tests everything thoroughly but in reality we all know that doesn't always happen. Also if you are expecting people creating modules to add `my-module-class` then the core should lead by example and labels it's own selectors.

In regards to when and how to do it. I think it would be best if you could keep the old ones and use new ones if that is possible (although this might be a bit messy). If you are going to make a hard switch please don't do it until a major version change as it will surely break peoples themes.

Also one last thing (sorry a little bit off topic) @NeOMakinG Do you advise people to amend the classic theme when developing a new theme or the starter theme. The documentation seems to advise the starter but it isn't under maintenance any more and no edits have been made to it in some time.

**Comment by NeOMakinG** [comment]
The starter theme is no longer maintained, this means that the only one which got updates is the classic theme inside this repository.

Just got to the doc and I think you're right, we should modify this part in order to redirect to the classic theme
