### ISSUE TITLE
Can not get url (for edit) of the category in backoffice in prestashop 1.7.6.0

### ISSUE THREAD

**Issue by Webpog** [PrestaShop/PrestaShop#14348]
**Describe the bug**
Can not get url (for edit) of the category in backoffice in prestashop 1.7.6.0

I am trying to get url for editing of the category in backoffice in prestashop 1.7.6.0. And I can not find function for that.

In previous versions < 1.7.6.0 (before twig template) it was easy to get like:

`{$link->getAdminLink('AdminCategories')|escape:'htmlall':'UTF-8'}&id_category={$category['id_category']|intval}&updatecategory`

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Webpro2019,

The URL of updating a category is changed from 
`index.php?controller=AdminCategories&id_category=id_category&updatecategory`
to 
`index.php/sell/catalog/categories/id_category/edit`

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10408 to migrate Categories Add/Edit actions.
ping @sarjon, what do you think? after the migration, how we can link to update a Category?

Thanks!

**Comment by sarjon** [comment]
Hey @Webpro2019 , since Categories page where migrated the URL has changed.

You can generate new URL using legacy `$link` (for backwards compatibility), like so:

```php
$context->link->getAdminLink('AdminCategories', true, [
    'id_category' => 2,
    'updatecategory' => 1,
])
```

Or using Symfony router (recommended)

```php
$this->get('router')->generate('admin_categories_edit', ['categoryId' => 2])
```

**Comment by Webpog** [comment]
thank you, this method is working:
`$context->link->getAdminLink('AdminCategories', true, [
    'id_category' => 2,
    'updatecategory' => 1,
])`

About Symfony router (recommended) - I did not find the way how to call it from module class

**Comment by khouloudbelguith** [comment]
@Webpro2019, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
