### ISSUE TITLE
Is equal to symbol = can't be used in product title

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#14365]
Like title said, symbol 'is equal to' (=) can't be used in product titles

1. Add new product or edit present
2. Click on title
3. add symbol ' = ' to title and try to save

PrestaShop version: 1.7.5-1.7.6
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @slupostrupek,

This is normal behavior.
We have an Expected value, in regexp form `/^[^0-9!<>,;?=+()@#"°{}_$%:]*$/u`
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L182
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @slupostrupek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thank
