### ISSUE TITLE
[Classic theme] Faceted search module design issue on mobile device

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14376]
**Describe the bug**
Design improvement required on mobile device for category page filter options. 

**Screenshots**
![IMG_0158](https://user-images.githubusercontent.com/40850057/60173083-a02f9780-982b-11e9-9e4c-b710a4e02bfe.PNG)

 To fix:
Go to: `/var/www/html/practice/testshop1/modules/ps_facetedsearch/views/dist/font.css`
Remove below style at line 124:
`width: calc(100% - 30px);`

**Additionnal information**
PrestaShop version: 1.7.6 RC1

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Thanks for your report.
Ping @PierreRambaud what do you think of his suggestion?

Thanks!

**Comment by ghost** [comment]
https://github.com/PrestaShop/classic-rocket/issues/55

**Comment by PierreRambaud** [comment]
@khouloudbelguith I'm not the one who chose what should be done with design :smile_cat: 
PIng @TristanLDD @colinegin

**Comment by colinegin** [comment]
Hello @dineshbadrukhiya , can you tell us what is the difference with this issue : https://github.com/PrestaShop/PrestaShop/issues/14377 ?

**Comment by dineshbadrukhiya** [comment]
@colinegin collapse icon and facet title are not aligned.

**Comment by Hlavtox** [comment]
Happens to me also. iOS 12.3.1 Safari.

- Price slider is initially displayed, when it should be hidden.
- Arrows are badly displayed
- Labels next to checkboxes are off after expanding.

#14377 is also connected to this.

![IMG_5150](https://user-images.githubusercontent.com/6097524/61186862-88994100-a66a-11e9-8d3d-d68117884e98.PNG)
![IMG_5151](https://user-images.githubusercontent.com/6097524/61186863-8931d780-a66a-11e9-9d43-b0397668c78c.PNG)

**Comment by TristanLDD** [comment]
Hi! Here are the design specs to fix the display on mobile: 

![Capture d’écran 2019-07-26 à 10 56 26](https://user-images.githubusercontent.com/27484094/61939667-0ecf5480-af94-11e9-854e-86d50d02f922.png)

**Comment by PierreRambaud** [comment]
I create https://github.com/PrestaShop/ps_facetedsearch/pull/118 for collapse and buttons' alignements. But I think therest need to be done in the classic theme. 
Wdyt @PrestaShop/prestashop-core-developers?

**Comment by PierreRambaud** [comment]
@marionf More things need to be done in the classic theme now :/

**Comment by colinegin** [comment]
@PierreRambaud is there an issue stating what's left to be done in the classic theme to close this issue ? Maybe @NeOMakinG could work on it :)

**Comment by PierreRambaud** [comment]
@colinegin there is only this issue. Only the collapse  and buttons alignments have been done.
