### ISSUE TITLE
Wrong payment costs after deleting a product

### ISSUE THREAD

**Issue by benlecoqartisans** [PrestaShop/PrestaShop#14379]
I think this bug is related to #14174 even if I don't know for the moment how to exactly reproduce

When I delete an article from my order (without invoice), I have a negative payment generated (normal) directly followed by another one which is the sum of article's amount and shipping costs (which are wrongly cancelled)

With the same cart, the same customer, I don't reproduce the bug when my supplier has free shipping

Wrong payment
https://drive.google.com/open?id=1XuJXX18rbu8ne-SNpygKiD7eSzy0g1Eu

Good payment
https://drive.google.com/open?id=1fW9RMHETH-IiO-c9ma6MJq9Fo60b_iaE

Prestashop 1.7.5.1

Thanks

**Comment by khouloudbelguith** [comment]
Hi @benlecoqartisans,

I did not manage to reproduce the issue with PS1.7.5.2.
https://drive.google.com/file/d/1PAG6C7u6_91zQiLCrTC8d3OMK2IKmVHR/view
Did you use a custom payment method? have you tried to check if you have the same issue using another payment method like payment by check? thanks to check & feedback.

Thanks!

**Comment by benlecoqartisans** [comment]
hi @khouloudbelguith 
I reproduced with another payment method.
But it's quite weird, I found 2 solutions to this problem (unfortunately it doesn't solve issue #14174 that I still reproduce). 
First one, I create another carrier, but the same in viewpoint of datas except one : its id_reference refers to itself and it wasn't that before.
Second one, I "modified" products (just by changing buy_price) and saved them.

In the two cases, the bug has disapeared...
So you can close this issue, even if I still don't know what is wrong...

**Comment by khouloudbelguith** [comment]
@benlecoqartisans, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
