### ISSUE TITLE
Price slider shouldn't be collapsed when page loads on mobile device in filter options.

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14377]
**Describe the bug**
Price slider shouldn't be collapsed when page loads on mobile device in filter options.

**Screenshots**
![IMG_0158](https://user-images.githubusercontent.com/40850057/60173083-a02f9780-982b-11e9-9e4c-b710a4e02bfe.PNG)
 To fix:
Go to: `/var/www/html/practice/testshop1/modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl`
Replace the code as below at line 164:
`class="faceted-slider"`
As below:
`class="faceted-slider collapse"`

**Additionnal information**
PrestaShop version: 1.7.6 RC1

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

It is well working with PS1.7.6.0rc1 & the ps_fecetedsearch v3.0.5.
I attached a video record
https://drive.google.com/file/d/1nZxcvW4F4GRKkweMWxk0jV7bIpaT8RTE/view
Thanks to check & feedback.

**Comment by dineshbadrukhiya** [comment]
Yes but you can see that price slider is opened and all others are closed on page load

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, it is the same behavior with Price & the weight
![image](https://user-images.githubusercontent.com/16067358/60188832-d703ae80-9827-11e9-86bd-50c04cd3dab1.png)

ping @PierreRambaud, @colinegin what do you think of this improvement.
Those filters should be collapsed?

Thanks!

**Comment by TristanLDD** [comment]
All filters should have the same behavior indeed, price and weight should be closed just like the other filters. 

Example on Asos: 
![Capture d’écran 2019-07-25 à 16 41 59](https://user-images.githubusercontent.com/27484094/61883845-6e2d5600-aefb-11e9-852c-d37c5cbd0193.png)

**Comment by PierreRambaud** [comment]
Closed by https://github.com/PrestaShop/ps_facetedsearch/pull/118
Release in 3.2.0
