### ISSUE TITLE
Can not change visibility of a product

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#14386]
**Describe the bug**
i can not change the visibility value for any product

**To Reproduce**
i open a product
i modified the value visibilty to "nowhere"
i save
when i come back on my product, it is back to "everywhere"

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Jerome08,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I attached a video record
https://drive.google.com/file/d/1Pax40rflAoTnybU28-oUFvqHzQkWa4FQ/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Jerome08** [comment]
Hello
i confirm i can not change this value:
u can see here
https://drive.google.com/open?id=1NYtW1sSnBwRFDkvZ_xVWakO46FpMx9Ms
one information usefull, i can change this value with a module of importing products
i use this one : https://addons.prestashop.com/fr/import-export-de-donnees/19091-catalogue-de-produits-csv-excel-dimportation.html

but directly in prestashop, i can no modify, even if i create a new product without using any module

best regards
jerome

**Comment by khouloudbelguith** [comment]
@Jerome08, I tried with PS1.7.5.1 & it is OK
https://drive.google.com/file/d/1LcFr2nUD64gFb_R9H4dXIliXENjQPN6g/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Jerome08** [comment]
ok i have a log in /var/logs
can i send it here? or does it contain some private information?

for debug mode report, i kwow thow to activate debug mode but i don't see how to export it
can i save the page to a pdf file?

Thanks
jerome

**Comment by khouloudbelguith** [comment]
@Jerome08, 
>can i send it here? or does it contain some private information?

yes you can send here, it is an error log file.

>for debug mode report, i kwow thow to activate debug mode but i don't see how to export it
can i save the page to a pdf file?

You can print the page or make a screenshot.

Thanks!

**Comment by Jerome08** [comment]
Hello

Here are the files

thank you !
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3402026/dev.log)
[debug mode.zip](https://github.com/PrestaShop/PrestaShop/files/3402035/debug.mode.zip)

**Comment by khouloudbelguith** [comment]
@Jerome08, in your log file, you have only some warnings, some Infos & there are no errors.
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. change the visibility of the product & save.
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Jerome08** [comment]
mmmm i activad bug mode
on the bottom of my prestashop i have a toolbar with many information but i don't see what u say (don't see network tab, or response, preview...)
can u check picture in attachment
and i confirm u i edited the product when i was in debug mode; i did it again
![ScreenShot015](https://user-images.githubusercontent.com/50581985/61385504-ce484a80-a8b2-11e9-9e69-a498f467d2a4.jpg)
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3402423/dev.log)

**Comment by khouloudbelguith** [comment]
@Jerome08, Open DevTools by pressing Control+Shift+J or Command+Option+J (Mac). The Console panel opens.
You can follow this link for more details: https://developers.google.com/web/tools/chrome-devtools/network/

Thanks!

**Comment by Jerome08** [comment]
in response and preview there are:
![ScreenShot001](https://user-images.githubusercontent.com/50581985/61399505-9d760e80-a8ce-11e9-9831-2094a03599cc.jpg)
![ScreenShot002](https://user-images.githubusercontent.com/50581985/61399506-9d760e80-a8ce-11e9-90ec-51c27d2f4f8b.jpg)
![ScreenShot003](https://user-images.githubusercontent.com/50581985/61399508-9e0ea500-a8ce-11e9-9e6a-a1d1a62043cb.jpg)

if u want full error from "response" tab it's in the text file
[error.txt](https://github.com/PrestaShop/PrestaShop/files/3403230/error.txt)

**Comment by khouloudbelguith** [comment]
@Jerome08, thanks for your feedback, but there is no error displayed in the response Tab.
When debug mode is enabled, there is no exception displayed after editing the visibility of your product?

Thanks!

**Comment by Jerome08** [comment]
mmmm i don't think so, i only find this:
![ScreenShot004](https://user-images.githubusercontent.com/50581985/61530565-b0025c00-aa24-11e9-9169-99054bd709e4.jpg)
i tried to record it :
https://drive.google.com/file/d/1TmoTPaY8VCdz8r8y7VL0G3aCkpSbrIKW/view

**Comment by khouloudbelguith** [comment]
@Jerome08, could you please provide me the link to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Jerome08,

This issue occurs due to the "Update Elements" module.
https://drive.google.com/file/d/1dOk1higYn299uFZpey1LFCcWQJxP0RFZ/view
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
