### ISSUE TITLE
Order details only 2 customer messages appear

### ISSUE THREAD

**Issue by siomosp** [PrestaShop/PrestaShop#14388]
**Describe the bug**

**To Reproduce**
1. Place an order
2. Add 3 or more  messages to order
3. Only the first two messages appear at order details page

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.x
![PS1752_Order_details_messages](https://user-images.githubusercontent.com/4071032/60254139-0a9d1200-98d6-11e9-8ad2-d01145a425d5.jpg)

**Comment by khouloudbelguith** [comment]
Hi @siomosp,

No, It is not the first & second message.
They are the last two messages, it is normal behavior, you can click on "Show all message" to show them all.
I attached a screen record
https://drive.google.com/file/d/1_NdOLd9mHfmMBLWJzG5oDh0crEGjEXJT/view
Thanks to check & feedback.

**Comment by siomosp** [comment]
Hi,
thanks for the reply!
There is an option to display more than last 2 meesages?
For example last 4 messages?
Thank you

**Comment by khouloudbelguith** [comment]
@siomosp, sorry no.
But this is could be an improvement added to the order page after the migration to Symfony: #13878.
ping @matks, @colinegin what do you think?
Can we have an option to display the number of the latest message?

Thanks!

**Comment by TristanLDD** [comment]
Hi @siomosp, thank you for your feedback, we are currently working on the order page and this problem has been signaled by several merchants. We will do our best to address it as soon as possible.

**Comment by colinegin** [comment]
@MatShir could you give us an update on the status of this issue ?

**Comment by MatShir** [comment]
@colinegin We consider adding the feature in the order page redesign. To check the status of the issue and the design results follow the issues #14745, it's currently in work in progress in @TristanLDD hand's.

**Comment by MatShir** [comment]
Fixed by #17801
