### ISSUE TITLE
FO - Shopping cart page - Incorrect display with FireFox

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#14389]
**Describe the bug**
Using the browser FireFox, The shopping cart is not well displayed.

**To Reproduce**
1. Go to FO
2. Add a product to the cart 
3. Go to the Shopping cart Page

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/60256008-a889e000-98c8-11e9-80df-561ee1bec1da.png)

With PS1.7.5.2 => iT is OK.
I used machine shuffle 1.7.5.2 => OK
**Additionnal information**
PrestaShop version: 1.7.6.0rc1
PHP version: 7.1

**Comment by dineshbadrukhiya** [comment]
We can remove the qty arrow with below style:

`input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    margin: 0; 
}`

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by dineshbadrukhiya** [comment]
Okay, I will once I get the time.

**Comment by matks** [comment]
> Okay, I will once I get the time.

Dont bother, we already did it 😉 https://github.com/PrestaShop/PrestaShop/pull/14395 as this is a blocking item to release PS 1.7.6.0
But thanks for volunteering ❤️

**Comment by dineshbadrukhiya** [comment]
> > Okay, I will once I get the time.
> 
> Dont bother, we already did it 😉 #14395 as this is a blocking item to release PS 1.7.6.0
> But thanks for volunteering ❤️

Welcome ❤️

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14395
