### ISSUE TITLE
SalesPerson can't quickview Product

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#14399]
Why someone with SalesPerson permission can't use the button "quickview" of products in BO? please need a fix ASAP
Thanks

**Comment by khouloudbelguith** [comment]
Hi @omar2886,

You are logged with SalesPerson permission? from the BO => Product page => you cannot click on the "Preview" button?
![image](https://user-images.githubusercontent.com/16067358/60279378-d4bd5500-98f8-11e9-9d60-0d6dc8d9ece2.png)

Thanks!

**Comment by omar2886** [comment]
> Hi @omar2886,
> 
> You are logged with SalesPerson permission? from the BO => Product page => you cannot click on the "Preview" button?
> ![image](https://user-images.githubusercontent.com/16067358/60279378-d4bd5500-98f8-11e9-9d60-0d6dc8d9ece2.png)
> 
> Thanks!

That's it!
![screenshot](https://user-images.githubusercontent.com/12675798/60280322-a0e32f00-98fa-11e9-9515-a07363bc9b01.jpg)

**Comment by khouloudbelguith** [comment]
@omar2886, I did not manage to reproduce the issue with PS1.7.6.0rc1.
In the BO => Advanced Parameters => Team => Permissions Tab, Salseman, all the action for the Product are selected?
![image](https://user-images.githubusercontent.com/16067358/60281919-bad24100-98fd-11e9-9138-5860c175c2a7.png)

Thanks!

**Comment by omar2886** [comment]
I only have "View", as I don't want any employee to be able to modify or create new products, it's out of their competences. But they should be able to click the quickview button to easily share the link with customers, one thing doesn't have to be related to the other, isn't it?

**Comment by khouloudbelguith** [comment]
@omar2886, when you click on the "Preview" button, you are saving the "Product".
But, this action is not allowed, you need to select the "Edit" action for this permission to be able to click on the "Preview" button.
Thanks!

**Comment by omar2886** [comment]
ooh I see! that's bad, how to fix this? or to add just a simple preview button with no saving function so my sales team can use it without "edit" permissions? 
Thanks for the help, really appreciate

**Comment by khouloudbelguith** [comment]
@omar2886, In the BO => Product page => SEO tab, you can preview the link of your product.
![image](https://user-images.githubusercontent.com/16067358/60341428-5dde9580-99a6-11e9-95fb-0480024caf0c.png)

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by omar2886** [comment]
Thanks! shame on me... I'm new on PS 1.7
