### ISSUE TITLE
Error 500 after update 1.7.6.0 - problem with module

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#14390]
After update to 1.7.6.0 have many error 500 with some random places for example when we try enter in BO: Positions/Premissions 

Module what is couse of this issues is ManufacturerSlider but I can't localize this in BO in modules, in FTP there is folder "manufacturesrlider" but I can't uinstal this. 

**Screenshots**
![screencapture-test-tomskor-pl-admin850kwyszj-index-php-improve-design-modules-positions-2019-06-27-12_26_46](https://user-images.githubusercontent.com/42567245/60259370-64eaa280-98d7-11e9-808e-f46d9512d1ca.jpg)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.27

**Comment by khouloudbelguith** [comment]
Hi @Tomskor,

Your module "manufacturesrlider" have some issues with PS1.7.6.0.
You can rename the folder "manufacturesrlider" to "manufacturesrlider_old" into the path `/Projet_Folder/modules/` to disable it temporarily.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.

I close the issue, feel free to open a new one when needed.
Thanks!
