### ISSUE TITLE
[BO/FO IMPROVEMENT] VAT number format as country setting

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14391]
Hi,
Regarding https://github.com/PrestaShop/PrestaShop/issues/14382 issue there will be very nice to validate VAT number in the same way as Postal code is validated. 

There are many VAT number formats across the world https://www.avalara.com/vatlive/en/eu-vat-rules/eu-vat-number-registration/eu-vat-number-formats.html 

That little option will help a lot

![vat](https://user-images.githubusercontent.com/8243273/60262978-cdd61880-98df-11e9-8bad-309ffdc13404.jpg)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Thanks for your report.
PING @marionf, @colinegin what do you think?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Thanks for your report.
The check of the VAT number could be done by the `vatnumber` module, here's the issue: https://github.com/PrestaShop/PrestaShop/issues/9884
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
