### ISSUE TITLE
Cart rule bug: Exclude discounted products issue with categor

### ISSUE THREAD

**Issue by MatthiasD0** [PrestaShop/PrestaShop#14407]
**Describe the bug**
Cart rule discounts are not properly added when the cart rule applies for one category and excludes already discounted products

**Fix**
Change following line https://github.com/PrestaShop/PrestaShop/blob/4846d0e196b91fa0e89bc9079f90c7ee4998522e/classes/CartRule.php#L1209
From:
`                        if (in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                            || in_array($product['id_product'] . '-0', $selected_products)
                            && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {`

To:
`                        if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                            || in_array($product['id_product'] . '-0', $selected_products))
                            && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {`

The OR statement needs to be inside () in order for 'reduction_exclude_special' to work!

**Comment by khouloudbelguith** [comment]
Hi @MatthiasD0,

Here's a PR: https://github.com/PrestaShop/PrestaShop/pull/13704 to fix the issue.
It is added to the 1.7.7 milestone.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @MatthiasD0,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
