### ISSUE TITLE
Product catalog / back office

### ISSUE THREAD

**Issue by marionpelouzet** [PrestaShop/PrestaShop#14408]
Bonjour,

Good morning,

In the product catalog from my back office there are 2 pages of 300 products (the maximum).
I can't pass products from page 1 to page 2 and from page 2 to page 1.
Do you know how to do ?

Thank you very much.

**Comment by khouloudbelguith** [comment]
Hi @marionpelouzet,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @marionpelouzet,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
