### ISSUE TITLE
Two timezones pacific in installer

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14411]
**Describe the bug**
2 timezones pacific in installer

**To Reproduce**
1. Install PS in English + United States

This is the norme for US:

![install 3](https://user-images.githubusercontent.com/13449658/60339914-6933c000-99aa-11e9-8b8a-ed784c0977f2.png)

**Screenshots**
![install 2](https://user-images.githubusercontent.com/13449658/60339884-54572c80-99aa-11e9-8c70-1773d0772124.png)

**Specifications**
_US/Pacific New_ is an obsolete timezone that should not be displayed nor selected by users in the PrestaShop installer, therefore it should be removed. Currently, it appears in the following files:

- install-dev/data/xml/timezone.xml
- install-dev/upgrade/sql/1.2.0.2.sql
- install-dev/upgrade/sql/1.2.0.1.sql

**Additionnal information**
PrestaShop version: 1.7.5, 1.7.6
PHP version: N/A

**Comment by colinegin** [comment]
What do you think of this issue @LouiseBonnard ?

**Comment by LouiseBonnard** [comment]
**US/Pacific-New** is an obsolete timezone, therefore it should not be available in this drop-down list. More info [here](https://mm.icann.org/pipermail/tz/2009-February/015448.html). I suppose that timezones in PrestaShop are introduced by a protocol - IANA, perhaps. 

@PrestaShop/prestashop-core-developers, would it be safe to remove the mention of this obsolete timezone in _install-dev/data/xml/timezone.xml_?

Also, I can see that it is also mentioned in the following files (related to databases if I'm right):

_install-dev/upgrade/sql/1.2.0.2.sql_
_install-dev/upgrade/sql/1.2.0.1.sql_

**Comment by PierreRambaud** [comment]
Yes it is safe, we can remove whatever we want for timezone :)

**Comment by LouiseBonnard** [comment]
It's great news, thanks @PierreRambaud, let's remove the obsolete timezone _US/Pacific-New_ then!

**Comment by HanaRebaiQA** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/507 & https://github.com/PrestaShop/PrestaShop/pull/29664
