### ISSUE TITLE
readme_override.txt is not up to date

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14415]
**Describe the bug**
readme_override.txt is not up to date

**To Reproduce**
1. Open the file readme_override.txt 

**Screenshots**
![readme_override](https://user-images.githubusercontent.com/13449658/60342124-e6623380-99b0-11e9-923d-733f341d1e13.png)

**Additionnal information**
PrestaShop version: All 1.7

**Comment by ghost** [comment]
LOL ;)

**Comment by matks** [comment]
@marionf I think we can remove this document. Wdyt ?

**Comment by marionf** [comment]
Yes we can :)

**Comment by PierreRambaud** [comment]
We've also many link with PS16 in the README file:
https://raw.githubusercontent.com/PrestaShop/PrestaShop/develop/README.md
In WebserviceRequest:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php#L66
In controllerHttp.php:
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/classes/controllerHttp.php#L436
Install database.php:
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/theme/views/database.php#L32
