### ISSUE TITLE
Issue with linkedin button after the install

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14412]
**Describe the bug**
Issue with linkedin button after the install

**To Reproduce**
1. Complete installation
2. Click on Linkedin

**Theses buttons are not used (6 tweets), maybe we can delete them ?**

**Screenshots**
![install 4](https://user-images.githubusercontent.com/13449658/60340093-f6771480-99aa-11e9-8f20-eaffb50b23f3.png)

**Additionnal information**
PrestaShop version: All 1.7
PHP version: N/A

**Comment by Progi1984** [comment]
@marionf I close this issue. @eternoendless has removed share buttons in #17340 (1.7.8).
