### ISSUE TITLE
Bad number of merchants in the installer

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14410]
**Describe the bug**
Bad number of merchants in the installer

**To Reproduce**
Install PS

**Screenshots**
![install1](https://user-images.githubusercontent.com/13449658/60339727-da26a800-99a9-11e9-842d-a99f77b59dd0.png)

**Additionnal information**
PrestaShop version: 1.7.5, 1.7.6
PHP version: N/A

**Comment by Progi1984** [comment]
@LouiseBonnard @Junebyun  Do you think in domain `Install` the string 
`'Installing PrestaShop is quick and easy. In just a few moments, you will become part of a community consisting of more than %numMerchants% merchants. You are on the way to creating your own unique online store that you can manage easily every day.'` would be better than 
`'Installing PrestaShop is quick and easy. In just a few moments, you will become part of a community consisting of more than 300,000 merchants. You are on the way to creating your own unique online store that you can manage easily every day.'` for customizing the number ?

**Comment by matks** [comment]
I think the string is better but the issue that it will not translated immediately 🤔 so in every installer in a foreign language, it will appear English until it has been translated

It's the same for every new string, however in the installer it's even more important

**Comment by Progi1984** [comment]
@matks As each string

@LouiseBonnard I let you decide if I change this string.

**Comment by LouiseBonnard** [comment]
@Progi1984, I think it'll better indeed! Where would you retrieve this number of active stores?

**Comment by Progi1984** [comment]
@LouiseBonnard I put in variable. It is more easier to change the variable in code without changing the string in Crowdin.

**Comment by LouiseBonnard** [comment]
Okay so the number is coded, there is no possibility to retrieve it dynamically?

**Comment by Progi1984** [comment]
@LouiseBonnard Is there any API or data anywhere ?

**Comment by LouiseBonnard** [comment]
Well, the only one I know is Sandrine. 😁
