### ISSUE TITLE
Guest account are not converted to a customer account through the FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14414]
**Describe the bug**
Guest account are not converted to a customer account through the FO

**To Reproduce**
1. Complete an order as guest (do not fill password field during checkout)
2. Go to BO and see the customer account is guest
3. After the order, scroll down and fill the fields (firstname, lastname, email & password)
3. Go to BO and see the customer account is still guest instead of customer

**Screenshots**
https://drive.google.com/file/d/1mM1olLM1ygwI1-MnZTAwvUUFxLFxg6Iw/view?usp=sharing

**Additionnal information**
PrestaShop version: All 1.7
PHP version: N/A

**Comment by matks** [comment]
I checked #8721 it was fixing another bug, similar but not this one.

Strange thing about this usecase: same function `transformToCustomer()` is called from both the BO and FO, but on BO it works while on FO it fails 🤔

**Comment by dangelion** [comment]
Any news on this? It's like an year this is opened and it's a serious issue. Rather it is better to remove it from upcoming releases since it doesn't work.

**Comment by damianobertuna** [comment]
I follow this topic. I found the problem in PrestaShop 1.7.6.7.

**Comment by damianobertuna** [comment]
I've just noticed that maybe the problem is the action of the form.

I've recorded this video to be more clear:
https://youtu.be/YocCXGUq7C8

Best regards.

**Comment by damianobertuna** [comment]
This module solves the problem:
https://addons.prestashop.com/en/customer-administration/49706-transform-guest-account-to-customer-account.html

You can suggest to your guest buyers to turn their account into a customer account when they arrive to the order confirmation page. They will find a button by clicking on which they can turn their account into a customer one.

**Comment by Slews** [comment]
Is there any plan to fix this issue soon ?
It makes no sense to keep this form if it does not work at all. At least, it should be removed.

**Comment by marionf** [comment]
Hello,

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). 

Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@marionf @matks @hibatallahAouadni I did a little digging about this issue. :-)

### To begin
- ✔️ Converting to customer through BO works perfectly fine.
- ✔️ Converting to customer from guest tracking screen works perfectly fine. You enter password, click convert and done.
- ❗  Our issue - **Converting to customer through form on order confirmation page can never work.** There is just no code in OrderConfirmationController.php that would do anything with it. :-) Also, why there are fields to enter name and email, when we already know it?

### How to fix it
- Change the form on order confirmation to the same form as on guest tracking page. - easy ✔️ 
![Výstřižek](https://user-images.githubusercontent.com/6097524/125926516-6f7e47c7-6348-4ba9-bda3-66935381596a.JPG)

- Use the same code as in GuestTrackingController and redirect him to login screen afterwards. - easy ✔️ 
![code](https://user-images.githubusercontent.com/6097524/125926690-92ed6e5d-ecf9-4cf0-aafa-e8591d11a1fa.JPG)
________________

Notes:
- Revisiting of this page must be fixed at once to show errors - https://github.com/PrestaShop/PrestaShop/issues/20388.
- $order->id_customer != $this->context->customer->id in controller must be disabled
- customer.is_guest, customer.email in order-confrmation.tpl must come from the controller directly, not from the context.

**Comment by hibatallahAouadni** [comment]
@Hlavtox Waiting for your PR :pray:

**Comment by Hlavtox** [comment]
@hibatallahAouadni @marionf @dangelion @Slews Will be fixed in https://github.com/PrestaShop/PrestaShop/pull/25395

**Comment by hibatallahAouadni** [comment]
@Hlavtox Thanks for your PR 🚀

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/25395 was merged fixing this issue for PrestaShop 8.0.0
