### ISSUE TITLE
Do not display the e-mail address in clear on the contact page and in the footer

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14416]
**Describe the bug**
Do not display the e-mail address in clear on the contact page and in the footer

**To Reproduce**
1. See the contact page and the footer

**Screenshots**
![contact1](https://user-images.githubusercontent.com/13449658/60342294-625c7b80-99b1-11e9-8288-e903b577789f.png)

![contact2](https://user-images.githubusercontent.com/13449658/60342298-64bed580-99b1-11e9-97f8-e8fba2ff4f38.png)

**Additionnal information**
PrestaShop version: All 1.7
PHP version: N/A

**Comment by matthieu-rolland** [comment]
This improvement requires modifications in two different repositories

PR for the contact info module:
https://github.com/PrestaShop/ps_contactinfo/pull/13

Pr for prestashop's theme:
https://github.com/PrestaShop/PrestaShop/pull/14539

Note that it could be possible to make this optional, making it configurable in the back office module administration page.

**Comment by matks** [comment]
> Note that it could be possible to make this optional, making it configurable in the back office module administration page.

I like that. @marionf wdyt ? We can create a "todo" issue in ps_contactinfo module to add this option

**Comment by marionf** [comment]
@matks @breizoreol 
We are waiting for more informations from Bruno (as this issue was brought up by him) before the validation of the two PRs

**Comment by marionf** [comment]
It would be better to leave the choice to the merchant to display or not the email address in the footer and in the contact page.

Problem: Currently the ps_contactinfo module isn't configurable and retrieves the information filled in Shop parameters > Contact > Stores > Contact details.
If you don't want to display the address for example, you can remove it. But the email address is a mandatory field, so if you don't want to display it the only way is to disable the ps_contactinfo module and all info will not appear anymore in the footer.

We have 2 options here:
1) Make the ps_contactinfo module configurable and let the merchant choose if he/she wants to display the email
2) Make the email address field not mandatory (I'm afraid this has edge effects ?)

About the email address displayed in the contact page, I guess it's also the address filled in Shop parameters > Contact > Stores > Contact details ?
So, if we choose to make the email address field not mandatory, it will works also for the contact page. Otherwise, we need to add an option also in the contactform module to let the merchant choose.

WDYT @matthieu-rolland ?

**Comment by matthieu-rolland** [comment]
I think the most sensical approach would be to let the user choose to display or not the email address. So that would be **option 1**.

Is it ok for you?

**Comment by marionf** [comment]
Yes it's ok, so let's add the following option in the ps_contactinfo & contactform module:
"Display email address": Yes / No
By default the option should be set on Yes in both modules

**Comment by matthieu-rolland** [comment]
Alright !

**Comment by matthieu-rolland** [comment]
So I made the display of email configurable, that required two pr:

The ps_contactinfo module: PrestaShop/ps_contactinfo#13

Prestashop's classic theme:

https://github.com/PrestaShop/PrestaShop/pull/14539

**Comment by matthieu-rolland** [comment]
@marionf there was actually no need to modify the contactform module, the email address in its left column is managed by the ps_contactinfo module as well. 

The two PRs are open for review. I noticed there is no label for wording in modules repositories, I will ping @LouiseBonnard here and in the module's pr.
