### ISSUE TITLE
GDPR isn't working if the module have multiple form on same page.

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#14429]
**Describe the bug**
If the module which has multiple forms on the same page at the same time on DOM then the GDPR module consent box doesn't work. The submit button of the forms doesn't get disable except the first form on page load.

**To Reproduce**
To reproduce the issue, need to create a tpl file with multiple forms in a single module and add the "displayGDPRConsent" hook to add consent box.
1. On Prestashop install GDPR module
2. Now in any module add a tpl file which has multiple forms on a single page (like using this hook displayFooterProduct)
3. And also add the "displayGDPRConsent" hook to display the consent box on each form.
4. Now check the front end, it will disable only first form submit button instead of all forms submit button. 

**Screenshots**
![grpr-consent](https://user-images.githubusercontent.com/39614089/60381811-27714b00-9a78-11e9-8eb5-5c0a75989240.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

Thanks for your report.
Could you please provide me your demo module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
In my case, I tried with "ps_emailsubscription" module, but only one form is always displayed.

Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith ,

Yes, I'll provide a test module soon.

Thanks!

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, thanks!

Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, any news?

Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 

I have emailed a test module on your email id. Please check and let me know I'll create the PR for this issue solution.

Thanks.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, sorry for the late answer.
But, I did not receive any mail yet.
Thanks to re-send me again the module.

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith 
Please check the attachment (Test module) to check this issue.
[Uploading testgdpr.zip…]()


Thanks.

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith 
Please check the attachment (Test module) to check this issue.
[testgdpr.zip](https://github.com/PrestaShop/PrestaShop/files/3520505/testgdpr.zip)

Thanks.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, thanks for your feedback.
I tried with your module with PS1.7.6.0 & PS1.7.5.2
1. No checkbox is checked => All "Submit" buttons are disabled => OK
![image](https://user-images.githubusercontent.com/16067358/63349024-7342c100-c352-11e9-822a-e1b9318e19d4.png)

Thanks to check & feedback

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 
Now please try to check the third or second checkbox, it will not enable the corresponding submit button , it will enable the first form button.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, if I check the second & the third checkbox => no "Submit" button is enabled.
If I check the first one => all the other "Submit" buttons are enabled.
https://drive.google.com/file/d/1K4M4pS0KikmcjW0Nx7Ss6I8wvtVV4jh8/view

Thanks!

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith 
Yes, that's the issue. I have a solution for this issue.
Please once confirm that the issue is clear so that I can create the PR for the solution of this issue.

Thanks

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, thanks for your feedback.
I have the same issue with PS1.7.5.2 & PS1.7.6.0.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith @Darmona 

As the issue is related to the GDPR module that's why I have raised a pull request on GDPR repository.
Please check - https://github.com/PrestaShop/psgdpr/pull/64

If any changes need to done then please let me know.
Thanks.

**Comment by Progi1984** [comment]
Fixed by PrestaShop/psgdpr#64
