### ISSUE TITLE
Can't add new carrier or edit existing one in PS 1.7.5.2

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#14421]
When I try to add a new carrier, the field Transit Time is missing.

in code, it seems to be set to display: none. Changing that, doesn't help, because I get an error at that moment. 

My shop has been upgraded from 1.6 (latest version) to 1.7.5.2

It is a multistore set up.

**To Reproduce**
1. Go to 'Admin > Shipping > Carriers'
2. Click on Add or Edit
3. Textfield of Transit time has css display: none, removing this allows to fill in the value, but result remains the same.

**Screenshots**
![1155751936_Schermafbeelding2019-06-19om09_13_58 thumb png 31009917af8838cca854f03958ebc2cf](https://user-images.githubusercontent.com/52320806/60341915-5a500c00-99b0-11e9-810c-e028e00b1b40.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nielsverhoeven84,

Thanks for your report.
You have some code lines missing in your Project.
Thanks to check the file `/Projetc_Folder/admin-dev/themes/default/template/helpers/form/form.tpl`
From this line: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/admin-dev/themes/default/template/helpers/form/form.tpl#L138
to this line: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/admin-dev/themes/default/template/helpers/form/form.tpl#L151

You need to add those lines.
Thanks to check & feedback.

**Comment by nielsverhoeven84** [comment]
I've modified the lines, but the result remains the same.
No input field is displayed (display: none in html source of the page)
Changing it still gives the same error

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) & clear cache from your browser.
Thanks to check and feedback.

**Comment by nielsverhoeven84** [comment]
I've cleared the cache on server and locally of browser and even tried incognito mode, but still no difference.

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, 
In my case, I did not manage to reproduce the issue after upgrade from ps1.6.1.23 to 1.7.5.2 using the 1-click upgrade v4.8.0.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nielsverhoeven84** [comment]
Dear @khouloudbelguith 

the error log shows

```
 Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 459 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Undefined index: language

Notice op lijn 462 in bestand /data/sites/web/shop-huysmans-boonenbe/www/var/cache/dev/smarty/compile/80/ce/24/80ce24b58c712aea8bedd7a2cba8ea5ff5d9049d_0.file.form.tpl.php
[8] Trying to get property 'value' of non-object

```

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, Thanks for your feedback.
Your error log shows only notices in the cache files.
Try to clear cache manually & provide me again the log file.

Thanks!

**Comment by nielsverhoeven84** [comment]
hello @khouloudbelguith, is there a way to increase the log level? even after clearing the cache folders I only see notices.

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84,  you can check the PHP error logs. If you don't have it, you should ask your hosting provider.

Thanks!

**Comment by nielsverhoeven84** [comment]
@khouloudbelguith nothing shows up in the error logs concerning the admin pages

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, could you please navigate to your BO => Advanced Parameters => Performance, Enable the "Disable all overrides" option, clear cache, check & feedback.

Thanks!

**Comment by nielsverhoeven84** [comment]
@khouloudbelguith that is already enabled

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, It could be an issue related to your database like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
The solution is to check & add the missing columns to your database schema.
You can find the full schema for 1.7.5.2 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

Thanks!

**Comment by nielsverhoeven84** [comment]
I can't find major differences, I've attached the structure of my db
[db_dump.sql.zip](https://github.com/PrestaShop/PrestaShop/files/3359123/db_dump.sql.zip)

**Comment by khouloudbelguith** [comment]
Hi @nielsverhoeven84,

Yes, it seems that there is no difference.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by nielsverhoeven84** [comment]
@khouloudbelguith Is there a dev team for the all in 1 upgrade module that can look into the issue?

**Comment by khouloudbelguith** [comment]
ping @Quetzacoalt91 what do you think?

Thanks!

**Comment by Quetzacoalt91** [comment]
Looks fine on my upgraded shop 1.6.1.24 -> 1.7.6.0

![image](https://user-images.githubusercontent.com/6768917/60678804-93d7ba00-9e7d-11e9-8d0e-d220bc846921.png)

Ther's probably a module adding css rules on this field.

**Comment by nielsverhoeven84** [comment]
@Quetzacoalt91 I didn't upgrade to 1.7.6.0 but 1.7.5.2. There is an style attribute on the text field of the transit time which sets to display: none, but removing that style doesn't fix the problem it only makes the field visible.

**Comment by nielsverhoeven84** [comment]
@Quetzacoalt91 On a fresh install, the text field is displayed properly, what tables/fields in db should I check to correct this? The files of the fresh install are the same as the one of the upgraded shop.

**Comment by nielsverhoeven84** [comment]
@Quetzacoalt91 The fields were set to `display: none` because the default language wasn't set.
