### ISSUE TITLE
Problem with CLDR format

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#14424]
**Describe the bug**
For some country and currency there is a problem with the currency format
- Portuguese 
 Wanted format : 12,345.67 € 
 Result : 12345,67 €
 
- Romania
 Wanted format : 12,345.67 lei 
 Result : 12345,67 lei 

- Czech
 Wanted format : 12,345.67 Kč  
 Result : 12345,67 Kč 

**Additionnal information**
PrestaShop version: 1.7.6-RC
PHP version: N/A

**Comment by Hlavtox** [comment]
In the first place, wanted format for Czech currency is 12 345 Kč, but that's something current sh**ty CLDR implementation can't do. :-)

**Comment by colinegin** [comment]
@sarahdib can we close this issue as we finally don't have issues with these languages ?

**Comment by sarahdib** [comment]
@colinegin yes we can close it :)
