### ISSUE TITLE
post-comment-modal issue on mobile device

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14427]
**Describe the bug**
Refer the screenshot below

**To Reproduce**
1. Go to 'product page'
2. Click on 'Write your review '
3. Check the "Title" and "Your name" field on mobile devices

**Screenshots**
![IMG_0166](https://user-images.githubusercontent.com/40850057/60379697-01867f00-9a55-11e9-929d-158e54241a4b.PNG)

**Additionnal information**
PrestaShop version: 1.7.6 RC

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

I did not manage to reproduce the issue with PS1.7.6.0rc1 & the `productcomments` module v4.0.0.
![image](https://user-images.githubusercontent.com/16067358/60427063-d71bf980-9bed-11e9-9276-19631b85aa52.png)
I used Iphone7 as a device.
Thanks to check & feedback.

**Comment by dineshbadrukhiya** [comment]
You need to allow guest review and need to check as a guest.

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, thanks for these clarifications.
Now, I manage to reproduce the issue with PS1.7.6.0rc1 & productcomments module v4.0.0.
![image](https://user-images.githubusercontent.com/16067358/60435601-e9a02e00-9c01-11e9-8353-c1aa9a4c46f9.png)

ping @jolelievre what do you think, PR https://github.com/PrestaShop/productcomments/pull/35 created by @dineshbadrukhiya.

Thanks!

**Comment by jolelievre** [comment]
Nice catch @dineshbadrukhiya 
I'll look into your PR

**Comment by Progi1984** [comment]
Fixed in PrestaShop/productcomments#47
