### ISSUE TITLE
BO bug in HTML - wrong display of help-box

### ISSUE THREAD

**Issue by mklimkiew** [PrestaShop/PrestaShop#14431]
**Describe the bug**
BO > Product section > Simple product > Quantities menu
Bug in HTML - wrong display of help-box

**To Reproduce**
Language PL
BO > Product section > Simple product > Quantities menu

**Screenshots**
![a](https://user-images.githubusercontent.com/45269666/60386211-88a61800-9a92-11e9-9577-d073df1bfef8.jpg)

**Additionnal information**
PrestaShop version: 1.7 - - 1.7.6 RC
PHP version: N/A

**Comment by zalexki** [comment]
Hey @mkdgs,  can you make sure that it does not come from your browser cache (i had similar issues before testing in private mode).

If you still can reproduce can you please add your browser and OS informations as front end issues can be very specific to the user environment.

**Comment by mklimkiew** [comment]
It is not related to the browser cache.

Chrome 75.0, same issue on Edge
PHP 7.2.19

**Comment by matks** [comment]
Like @zalexki I dont reproduce on chrome 75.0.3770.100 for MacOS X 10.13.6

<img width="404" alt="Capture d’écran 2019-06-30 à 17 30 39" src="https://user-images.githubusercontent.com/3830050/60398843-3120ae80-9b5d-11e9-9b56-340968aead3b.png">


@mklimkiew can you tell us wjhat is your OS ? A linux distro ? Windows ?
Can you also tell us what language your use in the BO ?

**Comment by mklimkiew** [comment]
Windows 10
BO language PL (polish)

**Comment by zalexki** [comment]
thx @mklimkiew bug is reproduced with BO language Polish on mac, seems like Polish version add some text for some reason

**Comment by khouloudbelguith** [comment]
Hi @mklimkiew, @zalexki,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I used Debian "Linux #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64".
![image](https://user-images.githubusercontent.com/16067358/60430708-dbe4ab80-9bf5-11e9-8021-b0048ea2dbd4.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by NeOMakinG** [comment]
This is a translation mistake in Admin.Catalog.Help file, I think there are too much quotes, these quotes should be html encoded like this : &quot; , I asked to join the translation team in order to fix this, waiting !

**Comment by NeOMakinG** [comment]
Removed extra double quotes in translation, should be fixed when translations will be update

**Comment by colinegin** [comment]
Thanks @NeOMakinG ! What do you think @LouiseBonnard ? Is there anything to do on your side ?

**Comment by LouiseBonnard** [comment]
Already done, just wait a couple of days and check if the help box is back to normal. :-)

**Comment by colinegin** [comment]
Greaaaat !

**Comment by NeOMakinG** [comment]
Some new ? I did download the Poland package and the bug is there, is the translation up?

**Comment by LouiseBonnard** [comment]
Yep, everything is fine on the translation side. If you've updated the Polish translation and noticed the typo is not here anymore but the display bug is, then it is not a translation issue. :-(

**Comment by NeOMakinG** [comment]
Will be fine when lang packs will be updated @eternoendless could you notify us the next languages update?

**Comment by colinegin** [comment]
Should be ok now, can you test it @Robin-Fischer-PS @sarahdib @SD1982 ?

**Comment by Robin-Fischer-PS** [comment]
Hi there !

On branch 1.7.7.x, this bug is now fixed : 
![polish display OK](https://user-images.githubusercontent.com/55688534/76453628-7cb97680-63d3-11ea-9833-1576c15fb2eb.png)

**Comment by colinegin** [comment]
Great ! I close this issue then ;)
