### ISSUE TITLE
Where is the Warehouse tab on the product page on the Prestashop 1.7 BO?

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#14436]
Hello,

On Prestashop 1.6, on the product page on the BO, I had a tab Warehouse. In this tab, I indicated, where (in which warehouse) was this or that combination when there was one.

Under Prestashop 1.7, you can not find this tab (or an equivalent). When I search "warehouse Prestashop 1.7" on Google, I am constantly referred to the Advanced Stock/Inventory Management, but when I go in Catalog> Stock, I can not find where to indicate in which warehouse is stored such and such a combination. Finally, when I type Warehouse Module Manager, I find nothing about it either.

Where, on Prestashop 1.7, I can indicate that this or that combination is in such warehouse?

Thank you in advance for your answer.

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Thanks for your report.
It was not available at first in 1.7.
We plan to release and sell an embedded ERP module that will do just what you need, ie routing warehouses with carriers and customer addresses.
You can follow our work on our dev blog :
http://build.prestashop.com/news/stock-management-in-prestashop-1-7/ http://build.prestashop.com/news/stock-management-in-prestashop-1-7-part-2/
http://build.prestashop.com/news/stock-management-in-prestashop-1-7-part-3/
http://build.prestashop.com/news/stock-management-in-prestashop-1-7-part-4-prestashop-erp/
Stay tuned for the next articles and the launch date of the ERP modules.
Also, Item location is available in 1.7.5.0. => added with this PR: https://github.com/PrestaShop/PrestaShop/pull/10422
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by wikao2** [comment]
Or "how to transform a simple, free, basic functionality into a gas plant and especially a paying one?" ... Thank you Prestashop Developers
We are (like many of your users) a small company. We do not need a paid on-board ERP module, even if it does what we need.
What we need is something simple and free.
Why not put back the Warehouse feature of version 1.6 of Prestashop and if, it is not enough for us, we offer your ERP module embedded?
I understand that it is more profitable for you to do that, but to complicate and especially pay for the slightest functionality, you will lose market share and users will turn to other solutions like WooCommerce that does much the same thing than Prestashop with many more free modules.

**Comment by khouloudbelguith** [comment]
@wikao2, the warehouse functionality was not available at first in 1.7.
You can find this module in our market place addons
https://addons.prestashop.com/en/modules-prestashop/39407-prestashop-erp-suite.html?ab=1

Thanks!

**Comment by papich06** [comment]
@khouloudbelguith 
Warehouse will return in prestashop 8 ?e
https://devdocs.prestashop-project.org/8/webservice/resources/warehouses/
