### ISSUE TITLE
Translation not saving

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#14432]
Prestashop 1.7.5.2 on php 7.2.19
as also discussed on this thread https://www.prestashop.com/forums/topic/958547-prestashop-1751-translations-not-saving-updating/
even saving translation on bo-->translation, it doesn't show on f.o.
attached image example (new transation present on b.o. "IVA inclusa"but on f.o. still "Tasse incluse")
![Opera Snapshot_2019-06-29_175843_www 100asa it](https://user-images.githubusercontent.com/5500935/60386713-184ec500-9a99-11e9-995b-154e403711d2.png)

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I attached a screen record
https://drive.google.com/file/d/1UJkdSMRCgZoxEP7XmdMXyiG5wybPmrCi/view
Thanks to check & feedback.

**Comment by centoasa** [comment]
@khouloudbelguith for me this settings are in "other translations"
![Opera Snapshot_2019-07-01_154224_www 100asa it](https://user-images.githubusercontent.com/5500935/60441302-0135e180-9c17-11e9-8ee1-08f7d40c1cbe.png)
and translation are done, but now show on f.o.
![Opera Snapshot_2019-07-01_154302_www 100asa it](https://user-images.githubusercontent.com/5500935/60441339-13178480-9c17-11e9-83e9-eb4b4c963c50.png)
where can I find the translation files, to be able to apply by hand?

**Comment by khouloudbelguith** [comment]
@centoasa, you need to check your expression in `Shop > Theme > Global`.

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith much, much strange! PLease see my video and let me know what about it:
https://nimb.ws/8lidTw

**Comment by khouloudbelguith** [comment]
@centoasa, In my case, I tried with "Other translations" => in the FO => It is the same, the translation of this expression is changed only after setting it in the theme translations not other translations.
You need to check the theme author about this issue.
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith sorry, I'm very sorry: the translations was in "classic" default theme
Translate it, now all is OK
Many thanks!

**Comment by khouloudbelguith** [comment]
@centoasa, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
