### ISSUE TITLE
Cannot download language pack "es"  PrestaShop v 1.7.6.0 RC 1

### ISSUE THREAD

**Issue by fred1code** [PrestaShop/PrestaShop#14447]
**Describe the bug**
esto ocurre cuando estoy instalado prestashop. se descomprime crea la base de datos, pero  casi al final me manda este error 

**To Reproduce**
1. this happens when installing prestashop with either the graphic web installer or using index_clie.php   with a script  bash  
2. when doing a very common installation this happens

**Screenshots**
![Captura de pantalla de 2019-06-28 11-05-47](https://user-images.githubusercontent.com/36098355/60450250-0da64400-9bef-11e9-927c-dcf467bb71bd.png)
![Captura de pantalla de 2019-06-28 11-08-00](https://user-images.githubusercontent.com/36098355/60450252-0da64400-9bef-11e9-85d6-02450d34fb26.png)
![Captura de pantalla de 2019-07-01 10-46-54](https://user-images.githubusercontent.com/36098355/60450253-0da64400-9bef-11e9-95a4-9ac9b1f74795.png)

**Additionnal information**
Prestashop 1.7.6.0 RC 1
PHP 7.2.15

**Comment by khouloudbelguith** [comment]
Hi @fred1code,

Hello, the error indicates an issue when downloading the "es" language pack, this is probably a temporary network issue, and if you restart the install it should be fine now.

Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @fred1code,

Any news about your issues?

Thanks!

**Comment by jabarrioss** [comment]
> Hi @fred1code,
> 
> Any news about your issues?
> 
> Thanks!

I'm having the same issue right now there's anyway I can download the **es** package manually and put it within the installation zip?

PD the installation crash even if I choose english as the default language

**Comment by khouloudbelguith** [comment]
Hi @fred1code, @jabarrioss,

I did not manage to reproduce the issue with PS1.7.6.0.rc2.
https://drive.google.com/file/d/18Rae4ImHm3ybar_gt8alool8ay8984n1/view
As I said before, this is probably a temporary network issue, and if you restart the install it should be fine now.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by xzessmedia** [comment]
same problem here using the docker image in a kubernetes environment, starting the container, then installing it, always stuck at 23 %

**Comment by cyrrelsneer** [comment]
same here, trying via Docker. I suspect an internal proxy though. 
Or was there another solition for that problem yet?
