### ISSUE TITLE
missing top-border in text editor on category and brand page

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14448]
There is missing top-border in text editor on category and brand page 

1. Go to 'BO > Category page > Add category'

See the error as in below screenshot:

**Screenshots**
![3](https://user-images.githubusercontent.com/40850057/60483272-64c11d00-9cb2-11e9-9a20-0058aefb89fd.png)

**Additionnal information**
PrestaShop version: 1.7.6 RC

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Thanks for your report.
ping @matks, @colinegin what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
ping @TristanLDD It's design specific

**Comment by TristanLDD** [comment]
@Pierre  I can't see any text editor when I go to the category page on 1.7.6 (it's a simple text field) is there something I'm missing here ? 
![Capture d’écran 2019-07-12 à 15 49 43](https://user-images.githubusercontent.com/27484094/61140024-ee4ec700-a4ca-11e9-9f7f-d686b0415bd6.png)

**Comment by TristanLDD** [comment]
The design is now displaying well in 1.7.6. Must have been related to the RC. 
I close the issue.
