### ISSUE TITLE
Improving the Developer eXperience while declaring new Controllers

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#14441]
We could listen to the yaml files of every module, when one file change we could dispatch a clear of the cache so developers wont need to care about it anymore.

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by jolelievre** [comment]
@mickaelandrieu which yaml files are you refering to?

For routing files it is partially managed by the legacy route manager (not sure it is available for the Symfony router, but maybe it's just adding a Resource to check)
For services I believe it is managed by the ContainerBuilder, via the `LoadServicesFromModulesPass` but we can also check it it automatically updates once the file is modified
