### ISSUE TITLE
Summary not refreshed in checkout

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#14464]
**Describe the bug**

**To Reproduce**
1. Create 2 cart rules with **COUPON CODE**, for example TEST 1 and TEST2
2. Add a product to the cart and go to the cart.
3. Add **TEST1** coupon.
4. Go to **checkout** page.
5. Add **TEST2**. New detail line is added but **discount amount is not refreshed**:
![image](https://user-images.githubusercontent.com/15104724/60587446-be9a1380-9d94-11e9-913d-3dc1f64f6d7d.png)
6. Remove both discounts. **Discount amount is not refreshed**:
![image](https://user-images.githubusercontent.com/15104724/60587486-d83b5b00-9d94-11e9-997c-79d3349ac570.png)

If a module overrides shipping cost, it's not refreshed neither. As in checkout page it's not possible to edit products in the cart, subtotal never change, but it would not be refreshed neither.

This works perfectly in "cart" page.

**Additionnal information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I did not manage to reproduce the issue with ps1.7.6.0RC1.
I attached a video record.
https://drive.google.com/file/d/1DvmAdMJCH4MqV61MRX4AxxylVMINt7Tv/view
Thanks to check & feedback.

**Comment by idnovate** [comment]
Hi @khouloudbelguith!

I thought I was running PS 1.7.6.0RC1 but it was Beta 1, and here is the bug fixed: https://github.com/PrestaShop/PrestaShop/commit/0f566a4ca699e4457ce9ed105bf9d2fd9517749b

**Comment by khouloudbelguith** [comment]
@idnovate, thanks!
Feel free to open a new one when needed.
