### ISSUE TITLE
PageSpeed make backoffice slow

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#14485]
**Describe the bug**
I'm using Google PageSpeed on Plesk to make my website faster but I'm facing a lot of issue with PrestaShop 
As it described on this video backoffice is becoming slow and take more time to navigate between menus
so I decedied to disabled PageSpeed
I need yuour help so the module will not work on backoffice 

https://youtu.be/ilmTzf05_9Q 
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version:Informations sur votre serveur Linux #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.1.30

Limite de mémoire : 4096M

Temps maximal d'exécution : 7000

Taille max. pour envoi de fichiers : 200M

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your report.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
