### ISSUE TITLE
Multi Shop categories

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#14498]
**Describe the bug**
Unable to set category on multi shop edit page.

**To Reproduce**
1. Go to 'Admin / MultiShop'
2. Click on 'Edit'
3. Only one category exists
4. And when click to Expand/Collapse fatal error occured

**Screenshots**

View with JS:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/3767861/60706365-954ec400-9f09-11e9-87da-c33dc216724f.png">

```Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/clients/client249/web407/web/modules/wkassignfeatures/wkassignfeatures.php:584 Stack trace: #0 /var/www/clients/client249/web407/web/modules/wkassignfeatures/wkassignfeatures.php(553): WkassignFeatures->getBackofficeProductIdFromRequest() #1 /var/www/clients/client249/web407/web/classes/Hook.php(966): WkassignFeatures->hookBackOfficeHeader(Array) #2 /var/www/clients/client249/web407/web/classes/Hook.php(355): HookCore::coreCallHook(Object(WkassignFeatures), 'hookbackOfficeH...', Array) #3 /var/www/clients/client249/web407/web/classes/Hook.php(903): HookCore::callHookOn(Object(WkassignFeatures), 'displayBackOffi...', Array) #4 /var/www/clients/client249/web407/web/classes/controller/AdminController.php(2804): HookCore::exec('displayBackOffi...', Array) #5 /var/www/clients/client249/web407/web/controllers/admin/AdminProductsController.php(87): AdminControllerCore->init() #6 /var/www/clients/client in /var/www/clients/client249/web407/web/modules/wkassignfeatures/wkassignfeatures.php on line 584```

View without JS:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/3767861/60706492-e19a0400-9f09-11e9-90ab-bc7926eed93b.png">

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Flower7C3,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
https://drive.google.com/file/d/16HsQbhhPfkTMLbekiNbhNa0SmoKpTQ4s/view
It is an issue due to the `wkassignfeatures` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
