### ISSUE TITLE
PS 1.7 FO product-list can't organize by price

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#14494]
Hi,
When I try to organize the product list by product price (asc or desc) all products disappear. It still shows a text saying how much products are on the list but shows nothing.
If I change in the drop menu any other criteria rather than quantity, works fine.
Does it have anything to do with the ps_facetedsearch module? always has problems. I just updated it to 3.0.6 and nothing happens.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @omar2886,

I did not manage to reproduce the issue with PS1.7.6.0rc1 & PS1.7.5.2 & the ps_facetedsearch v3.0.6 after an upgrade from a previous version.
https://drive.google.com/file/d/117L77WUcWIY8T7UMF-KdeTLbbF_Aekbz/view
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
You need also to Click on "Rebuild entire price index", "Build attributes and features indexes" & "Clear cache" button in the ps_facetedsearch configuration module.
Thanks to check and feedback.

**Comment by omar2886** [comment]
Great! thank you! I've tried to use the rebuild functions on the last 3 versions of ps_facetedsearch and never worked, always error, now it did! I think there was something corrupted in the cache folder, so after deleting folder inside I could clear cache and rebuild price and features index so now all filters work.
thank you very much!

**Comment by omar2886** [comment]
needed to manually delete folders within cache directory

**Comment by khouloudbelguith** [comment]
@omar2886, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
