### ISSUE TITLE
javascript not loaded

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#14499]
**Describe the bug**
My customer have one shop group with 5 shops. When I work on main shop everything is ok. But when I change context to any other shop some features does not work. Eg. I am unable to filter installed modules.
In inspector I can see that not all JavaScript files are loaded in other shops.

**Screenshots**
Main shop - 19 JS requests:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/3767861/60706893-c54a9700-9f0a-11e9-9809-a22c202fd456.png">

Other shop - only 15 JS resuests:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3767861/60706867-b663e480-9f0a-11e9-8e3c-dd44574eee77.png">

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Flower7C3,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by PierreRambaud** [comment]
I can see a broken lock on these images. What happened if you open the link? Is there an https issue?

**Comment by Flower7C3** [comment]
The problem was, that one context has more JS files loaded than other. I have just updated to PS 1.7.6.0 and the problem has disappeared.

**Comment by khouloudbelguith** [comment]
@Flower7C3, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
