### ISSUE TITLE
Qty Input field UX improvement

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#14496]
Actually it could not be considered as a bug, it is rather UX improvement.

When you select an quantity input field, no matter it is in the product page or in the cart, it does bring the normal keypad on mobile phones.
It would be much better to bring up the large numeric keypad, because I doubt someone needs to type something else there than number.

1. Just select quantity field on mobile phone.

**Screenshots**
I couldn't find I way to attach a screenshot, but I don't think you need one.

**Additionnal information**
Tested on the PS demo site and on local 1.7.5.1 installation.

**Comment by khouloudbelguith** [comment]
Hi @MockoB,

Thanks for your report.
Using a mobile or not, we have the same behavior when setting the quantity with something else than a number, when we click outside the quantity will be automatically changed to the minimal quantity.
As you can see in this screen record
https://photos.app.goo.gl/bqGCkVnJEn5Gs6Tq5
Thanks to check & feedback.

**Comment by MockoB** [comment]
Thanks for your reply, but that's not the point.

It would be much better when you select the QTY field, willing to enter a number, to bring up the large **numeric** keyboard on mobile devices. Currently it brings the normal (letter) keyboard, which forces users to switch between keyboards. Even switching, the user is forced to enter the quantity with the small number buttons, which may be the cause for errors in desired quantities.

Look how it is at the moment: https://imgur.com/lcGyQSy

Look what selecting quantity field brings on this site: https://imgur.com/UMr9J6C

I believe the best option is this one, which brings the large numeric keypad and allows you easily to enter the desired quantity: https://imgur.com/k7uwtxb

I hope it is more clear now. 

Edit: I'm stripping the link tag because the images don't open correctly, please copy and paste the addresses in your browser to see the images.

**Comment by khouloudbelguith** [comment]
@MockoB, thanks for these clarificationa.
@colinegin, @marionf, @TristanLDD what do you think?

Thanks

**Comment by TristanLDD** [comment]
Hi @MockoB , thank you for your suggestion which I totally agree with. Every numeric input field should open the numeric keyboard on mobile. 
@PrestaShop/prestashop-core-developers I think this is pretty easy to implement right?

**Comment by oliverhudson** [comment]
Is there any update to this query?

**Comment by NeOMakinG** [comment]
Working on this right now @oliverhudson

**Comment by oliverhudson** [comment]
@NeOMakinG  How long will this take and will it be released in new version?

**Comment by NeOMakinG** [comment]
I think this will be finished today, but on develop, this means that it will be released in 1.7.8
