### ISSUE TITLE
Rework of the E2E test suite run by Travis

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14497]
Travis runs some E2E tests using Selenium. We've had multiple issues over time with this test suite: false positives, random failures, bad test settings.

Recently we had to disable one scenario because it was failing randomly: see issue #14384
and the related PR https://github.com/PrestaShop/PrestaShop/pull/14491

We need to rebuild this E2E test suite to make it more reliable.

**Comment by matks** [comment]
ping @SimonGrn 

Here's the issue to be done for 1.7.7 about Travis web acceptance tests

**Comment by SimonGrn** [comment]
We will only have smoke and sanity tests before the 1.7.7 is shipped, no E2E tests and I don't think we'll ever have since we want to have functional/E2E tests only for the nightly. Is that a problem ?

**Comment by matks** [comment]
> We will only have smoke and sanity tests before the 1.7.7 is shipped, no E2E tests and I don't think we'll ever have since we want to have functional/E2E tests only for the nightly. Is that a problem ?

Smoke & sanity will do 👍 we talk about E2E tests here but we mean "web acceptance tests, powered by either Selenium or Puppeeter". Remember that so far, only you has a different meaning for E2E 😉 most of us think that E2E tests = "tests that start a browser and interact with the HTML and JS interface".

For example, if you pick https://engineering.wingify.com/posts/e2e-testing-with-webdriverjs-jasmine/ as an example:
"e2e or end-to-end or UI testing is a methodology used to test whether the flow of an application is performing as designed from start to finish."
=> so far so good 😄 
"In simple words, it is testing of your application from the user endpoint where the whole system is a blackbox with only the UI exposed to the user."
=> :trollface:

**Comment by SimonGrn** [comment]
"From start to finish" is the only relevant piece of info here. Smoke and sanity don't test from start to finish, neither unit tests. I don't really understand why they put UI testing and E2E testing together as it was never mixed up when it was introduced to me.
Anyway, we got the spirit and that's the most important !

**Comment by matks** [comment]
> I don't really understand why they put UI testing and E2E testing together as it was never mixed up when it was introduced to me.

Because most developers are introduced to web acceptance testing (meaning: using a browser to interact with the app) by tutorials and conference talks, not professionals. So we mix things up.

**Comment by matks** [comment]
Fixed by the wonderful QA team in 1.7.7

Congratulations @boubkerbribri @nesrineabdmouleh @SimonGrn
