### ISSUE TITLE
Many PHP Notices

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#14495]
In apache error log i see many of "**PHP Notice:  Undefined index**" contain (i think that) admin module access rights, because the indexes: view, configure, uninstall and name, id_module. I write it just for information, may in my case its generated after migration from ps1.6 to 1.7. So what you think about it?
```
/Smarty version 3.1.33, 
  from '/admin/themes/default/template/controllers/access/helpers/form/form.tpl' 
```
and example of index (near line 711 of smarty cached file)

 `<?php if ($_smarty_tpl->tpl_vars['module']->value['uninstall'] == true) {?>`

**Comment by khouloudbelguith** [comment]
Hi @madkot,

About the issue after upgrade from PS1.7 to PS1.7, we have a lo of PRs which are in progress:

- PrestaShop/PrestaShop#14481
- PrestaShop/PrestaShop#14404
- PrestaShop/PrestaShop#14031
- PrestaShop/PrestaShop#14022
- PrestaShop/PrestaShop#13376
- PrestaShop/PrestaShop#13350

For more details, you can follow this link: https://github.com/PrestaShop/autoupgrade/issues/100#issuecomment-508160384

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @madkot,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
