### ISSUE TITLE
Browser console suggestion for the password form

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14506]
**Describe the bug**
What do you think about this suggestion in console? Should we need to implement it in the code?

**To Reproduce**
1. Go to 'Sign in/Sign Up' page
2. Open browser consolve
3. See suggestion

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/40850057/60728138-3b77e980-9f5d-11e9-815f-3bd3051e820f.png)

**Additionnal information**
PrestaShop version: PrestaShop 1.7.6 RC

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

I tried with PS1.7.5.2 & PS1.7.6.0rc2, I have this warning:

`This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.`
I don't think it is the same warning?

Thanks!

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith Have you tried with Google Crome browser?

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, yes, I'm using Google Chrome browser Version 71.0.3578.98 (Build officiel) (64 bits).

Thanks!

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith  I have tried with Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, it is OK with Google Chrome v75
I attached a screen record
https://drive.google.com/file/d/1vPQa3hJV5Dr2RcpyvxneQLhKl2K2K8o4/view

Thanks!

**Comment by dineshbadrukhiya** [comment]
@matks wdyt?

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith Enable Verbose in Default levels (Next to the Filter in browser console) and check.
@matks wdyt?

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Thanks for these clarifications.
Yes, when I enable Verbose in Default levels.
I have the same console suggestion with PS1.7.5.2 & PS1.7.6.0rc2.
![image](https://user-images.githubusercontent.com/16067358/60805755-f7f9c700-a178-11e9-8e8e-c89f1c6416e3.png)

```
[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) 
<input class="form-control js-child-focus js-visible-password" name="password" title="Au moins 5 caractères" type="password" value="" pattern=".{5,}" required="">
```

Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
@NeOMakinG What do you think about this one?

**Comment by NeOMakinG** [comment]
That would be really cool to be honest, gonna do it
