### ISSUE TITLE
Add payment options useful for East Africa

### ISSUE THREAD

**Issue by bkmgit** [PrestaShop/PrestaShop#14519]
**Is your feature request related to a problem? Please describe.**
Prestashop is nice software, but it does not have options for payment that are most used in East Africa directly integrated

**Describe the solution you'd like**
Direct integration with  Pesapal (http://developer.pesapal.com/official-extensions) or similar would be great.

**Comment by ghost** [comment]
Hi @bkmgit,

Thanks for your feedback!
From what I see on the link you just shared some modules already exist to connect Pesapal to PrestaShop.
It doesn't work?

Do you have other payment companies in mind so we can contact them?

Thanks,

**Comment by khouloudbelguith** [comment]
Hi @bkmgit,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
