### ISSUE TITLE
blank invoice in front office user account

### ISSUE THREAD

**Issue by LSClaire** [PrestaShop/PrestaShop#14512]
**Describe the bug**
Everything seems normal in BO. In FO, when a user logs into his account to fetch his invoice, it comes out empty.

**To Reproduce**
1. Place an order
2. Once payment in validated, go to your account
3. download your invoice
4. empty.

**Screenshots**
[FA003143 (2).pdf](https://github.com/PrestaShop/PrestaShop/files/3364331/FA003143.2.pdf)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @LSClaire,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @LSClaire,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
