### ISSUE TITLE
Multilanguage site, error 404 at combination selection , English language only

### ISSUE THREAD

**Issue by siomosp** [PrestaShop/PrestaShop#14513]
**Describe the bug**
At a multilanguage site Greek , English , only at English language 
at product combination selection there is  404 error when clicking a combination
**To Reproduce**

Product Greek laguage working

https://www.stickit.gr/el/pinakes-se-kamva/themata/topia/red-leafs-pinakas-se-kamva

The same product Elnglish Language not working
https://www.stickit.gr/en/canvas-prints/themes/nature/canvas-print-red-leafs-en-16918

*Sample Post when selecting combination*
Product Greek laguage working

https://www.stickit.gr/el/index.php?controller=product&token=0687827d206069ce6434a4facc2e24f3&id_product=16918&id_customization=0&group%5B24%5D=1519&group%5B23%5D=2643&qty=1

The same product English Language not working
https://www.stickit.gr/en/product?token=0687827d206069ce6434a4facc2e24f3&id_product=16918&id_customization=0&group%5B24%5D=1519&group%5B23%5D=1518&qty=1

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33
Nginx 1.10.3
Friendy URL module ( remove ids from products enabled)

**Comment by khouloudbelguith** [comment]
Hi @siomosp,

I did not manage to reproduce the issue with PS1.7.5.2 with the fresh installation using the multilanguage Greek & English.
https://drive.google.com/file/d/1mgJteCLc_56m-a7XsZ_ZD_4doO3CCfzC/view
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by siomosp** [comment]
Hi,
thank you for your reply
I will try to contact module developers,
best regards
Panagiotis
