### ISSUE TITLE
Birthday format when error in authentication form

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#14524]
Hello,

When a user submits the authentication form with a birthday with a french date format (example: 15/08/1985) but has an error in the form (exemple: email already in database), the form is reloaded with user values, but birthday is displayed this way: "1985-08-15", because of the validator in CustomerForm.php: 

```
// birthday is from input type text..., so we need to convert to a valid date
$birthdayField = $this->getField('birthday');
if (!empty($birthdayField)) {
    $birthdayValue = $birthdayField->getValue();
    if (!empty($birthdayValue)) {
        $dateBuilt = DateTime::createFromFormat(Context::getContext()->language->date_format_lite, $birthdayValue);
        if (!empty($dateBuilt)) {
            $birthdayField->setValue($dateBuilt->format('Y-m-d')); //<------ this line
        }
    }
}
```

So when the user corrects the error in the form and then submits it, he has a new error: the format of the birthday.

How could we avoid this?

Thank you

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @agnesdennetiere,

When the English language is selected in the FO:
I have two errors are well displayed as described in this screen record
https://drive.google.com/file/d/1oNiM-EkoyerrzxCJkGHQG_dHKtg4M9eM/view
But when French is selected in the FO:
I have the first error "email already in database" => the form is reloaded with user values =>  but the birthday is displayed this way: "1985-08-15" 
When I change the mail, there is no error displayed about the birthday
https://drive.google.com/file/d/1Nhew0bpXTLnpq-cYIFTWGFIHzdgOC5iW/view

Thanks to check & feedback.

**Comment by agnesdennetiere** [comment]
Hello,

yes because when you had an error, you changed the value of the birthdat field (second video, 00:04) you but if the user does not do it, it is sent with this format: 1985-08-15 so he gets an error...

**Comment by khouloudbelguith** [comment]
@agnesdennetiere, thanks for your feedback.
I tried to not change the birthdate after having the email error & it is OK.
I attached a screen record.
https://drive.google.com/file/d/1jfqUytAArFwIZF2fEircDmALRVNPUHvU/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @agnesdennetiere,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by jf-viguier** [comment]
The bug is still there in Prestashop 1.7.6.1, can you reopen it ?

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Could you please confirm these steps:
1. Français is selected
2. Create a new customer with a previous email & with birthday date like 15/08/1985
3. click submit
4. An error "L'adresse email est déjà utilisée, veuillez en choisir une autre ou vous connecter" is displayed
5. change the address email & submit again => there is no error
In my case, in the step5, The user is well registered, but in the @agnesdennetiere issue, there is an error.
https://drive.google.com/file/d/1ycbutoESPG68KfCMZROvzzKFg0QN05sl/view
Thanks to check & feedback.

**Comment by jf-viguier** [comment]
There is clearly a display issue : when submitting to server with en error, the birthday is displayed in yyyy-mm-dd instead of french format dd/mm/yyyy
![bugdate](https://user-images.githubusercontent.com/16720275/68137487-5a948100-ff27-11e9-98ab-2e412a842a29.png)
In my screenshot, I used a wrong password.

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I updated an old issue.
it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9591
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9591

**Comment by jf-viguier** [comment]
It's not a duplicate of #9591 because the birthday is not managed by the same code of the product availability date.

**Comment by khouloudbelguith** [comment]
Hi @agnesdennetiere,

But the issue is the same "Date format always in US format in the French language".
In the BO => International => Loaclization => Languages Tab => The Date format is specified & we can edit it => but in the FO is not applied.
![image](https://user-images.githubusercontent.com/16067358/68190855-873fab80-ffae-11e9-88aa-20c0d48518af.png)

Thanks!
