### ISSUE TITLE
ProductId throw an OrderException instead of ProductException

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#14520]
**Describe the bug**
I need to use a [ProductId](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Product/ValueObject/ProductId.php) for a module (1.7.6.+) but it throw an OrderException instead of ProductException

**To Reproduce**
1. Go to https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Product/ValueObject/ProductId.php
2. Look on assertIntegerIsGreaterThanZero function
3. See Exception thrown is not a ProductException

**Additionnal information**
PrestaShop version: develop
PHP version: PHP 7.2

**Comment by matks** [comment]
Nice catch !

**Comment by Matt75** [comment]
Already fixed 🥳
