### ISSUE TITLE
Sort by price not correct from one page to another based on discounted price

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#14521]
**Describe the bug**
On the category page, if filter 'Sort By: Price, low to high' then if compare by discounted product, from one page to next page sorting is wrong but on the same page, the comparison is ok.

**To Reproduce**
1. Go to 'Category Page'
2. Click on 'Sort By: Price, low to high'
3. Scroll down and change the page.
4. Compare discounted price from one page to the next page.

**Screenshots**
![download (2)](https://user-images.githubusercontent.com/19220745/60782683-4dc47400-a165-11e9-80e5-911c51966293.png)
![download (3)](https://user-images.githubusercontent.com/19220745/60782690-56b54580-a165-11e9-911e-c5d5f8f4d2d2.png)

**Additionnal information**
PrestaShop version: v1.7.5.2 and in latest v1.7.6.0 rc1 also
PHP version: PHP-7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

This issue is fixed with PS1.7.6.0 & the new version of the ps_facetedesrach v3.
Your ticket is a duplicate of #10010
What is the exact version of the ps_facetedsearch module did you use?

Thanks!

**Comment by dheerajwebkul** [comment]
Hello @khouloudbelguith 

I am using ps_facetedsearch v3.0.5
But not able to upgrade, 
![download (4)](https://user-images.githubusercontent.com/19220745/60805410-9dbf2d00-a19d-11e9-9b84-61bb3a6df896.png)
Even I am not able to login by the correct credentials.

**Comment by dheerajwebkul** [comment]
I just download ps_facetedsearch from git and updated, and it's fixed.

Thanks.

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, thanks!

Feel free to open a new one when needed.

THanks!
