### ISSUE TITLE
label "sale" is not appear on discount product 1.7.5.2

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14534]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by photinia73** [comment]
Close this issue pls.

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by photinia73** [comment]
Hello!

I can`t find anywhere the module or page with drop-prices. It placed in the bottom of page in the block Product.
After clicking on it the page drop-prices is opened with all products which have discount price. 
But the left menu contain only one item and every time different.

Where I can adjust this page?
Or to obtain more options I have to install one other module?

Thank you.


З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: вторник, 9 июля 2019 г. в 11:26
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] label "sale" is not appear on discountproduct 1.7.5.2 (#14534)

Closed #14534.

**Comment by khouloudbelguith** [comment]
@photinia73, about the left menu, in fact, The Category Tree module always displays the latest visited category with default settings.
We are aware of this issue, you can follow this issue: https://github.com/PrestaShop/PrestaShop/issues/10763
Thanks!
