### ISSUE TITLE
feature empty duplicate issue  

### ISSUE THREAD

**Issue by thibaudimd** [PrestaShop/PrestaShop#14535]
If someone forgets to choose a feature from the list but enters a name in the "customized value"  and saves the feature is no longer removable without deleting the entire product 
and each time we save the product the feature is duplicated in a loop  

![image](https://user-images.githubusercontent.com/52695980/60871723-95193600-a233-11e9-9358-844d64ec0701.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
I have this issue in prestashop 1.7.5.x
I tested on an old version 1.7.2.2 and the issue was not present

**Comment by khouloudbelguith** [comment]
Hi @thibaudimd,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9680
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9680
