### ISSUE TITLE
Discount table display incorrect prices based on quantity and country

### ISSUE THREAD

**Issue by cboillat** [PrestaShop/PrestaShop#14537]
**Describe the bug**
I have a product with specific prices based on quantity and quantity + country :
![image](https://user-images.githubusercontent.com/1654758/60871805-ca258880-a233-11e9-96e0-6111a3c90360.png)

IP Geolocalisation is enabled on the shop.

When I check the product on the FO with no user connected, the base product price displayed is the "Swiss" price (I'm visiting the website from Switzerland). But the discount table show the other prices :
![image](https://user-images.githubusercontent.com/1654758/60872038-428c4980-a234-11e9-9d17-35e0662e9cbf.png)

If I log in with a user that has a Swiss address, the discount table updates and show the correct price list :
![image](https://user-images.githubusercontent.com/1654758/60872323-c6decc80-a234-11e9-97ad-f778e0880e7d.png)

If I change my address to "France" the base price + discount table update correctly :
![image](https://user-images.githubusercontent.com/1654758/60872471-fe4d7900-a234-11e9-84ef-5a1be81ec0bf.png)

As soon as I log out, the base price remains the "Swiss" price, but the discount table shows the wrong prices.

**To Reproduce**
1. Enable IP Geolocalisation
2. Setup a product with specific prices based on quantity and quantity + country
3. Go to FO and check the product price and discount table. Try to login and logout with a user and change it's address

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @cboillat,

I did not manage to reproduce the issue with PS1.7.6.0rc2 & PS1.7.5.1.
IP Geolocalisation is enabled in the shop.
I'm visiting the website from "France" & The default country is France.
I have a specific price on the France country
![image](https://user-images.githubusercontent.com/16067358/60883453-27283b00-a242-11e9-9c5e-ef2141645a4e.png)
On the FO, when I m not logged, the price is well displayed & the specific prices are well displayed

![image](https://user-images.githubusercontent.com/16067358/60883535-5a6aca00-a242-11e9-915d-08ee2459b636.png)

I attached a screen record.
https://drive.google.com/file/d/1TxG_vQu5ax4SO0-mqyJUexx0TsghLcUs/view
Thanks to check & feedback.

**Comment by cboillat** [comment]
Hi @khouloudbelguith,

Thanks for your answer and the time you've taken to test.

I think I found a small part of my problem. To make things better, I changed the value "Set the country according to the browser language" to "No" under "Localisation".

But there's still a problem that you should be able to reproduce too. Try to access your shop from a VPN as if you were in Switerland and you'll see that the main price will change and display the "Swiss" price but the discount table will still display your "French" prices.

Any idea why ?

**Comment by khouloudbelguith** [comment]
@cboillat, I tried with another country & it is OK.
https://drive.google.com/file/d/1L15JeLwqqu9Yyy5yMV55UoHsKld_0z1p/view
Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith I did exactly the same as you and it worked like in your video.

But as soon as I enabled the Geolocalisation by IP (and accessing the website from Switzerland), the product main price became 120 euro (which is correct) and the discount table remains with the "italy" prices (not correct).

[https://drive.google.com/file/d/1nuXnLYeHArGfQ2mcldWekh0PLNzkj4Fz/view?usp=sharing](https://drive.google.com/file/d/1nuXnLYeHArGfQ2mcldWekh0PLNzkj4Fz/view?usp=sharing)

**Comment by khouloudbelguith** [comment]
@cboillat, when you access the website from Switzerland.
In the FO => Your account  => Addresses, when you try to add an address, what is the exact country displayed by default when Geolocalisation by IP is enabled & disbled?
![image](https://user-images.githubusercontent.com/16067358/60959306-e2fb7000-a2ff-11e9-87ff-3cca089da6eb.png)

Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith 
when Geolocalisation by IP is enabled -> France
when Geolocalisation by IP is disabled -> Italie

**Comment by khouloudbelguith** [comment]
@cboillat, thanks for your feedback.
So, when the Geolocalisation by IP is enabled => error (incorrect specific price).
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith Yes indeed. But why the main price change correctly and not the discount table price ? Because if I enable Geolocalisation by IP, the main price is 120 (which is correct) and the discount table price for 50 pieces is 20 (which is wrong, that's the italy price).

**Comment by khouloudbelguith** [comment]
@cboillat, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith 
I checked the console in Chrome on the product page -> no error
I enabled debug mode -> nothing special

**Comment by khouloudbelguith** [comment]
@cboillat, in your log file, you have some warnings about the `jxproductsslider` module & some error in the cache.
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by cboillat** [comment]
@khouloudbelguith, I disabled the jxproductsslider and deleted the cache under var/cache (prod+dev). Style the same problem. Main price is correct but table discount is wrong.

**Comment by khouloudbelguith** [comment]
@cboillat, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith access sent ;-)

**Comment by khouloudbelguith** [comment]
@cboillat, thanks for your feedback.
I just received your email.
I will check & feedback.

Thanks!

**Comment by cboillat** [comment]
Hi @khouloudbelguith any news following your tests ?

**Comment by khouloudbelguith** [comment]
@cboillat, 

Thank you for your feedback.
I'm trying to reproduce it and we'll come back to you if we need more information.

Thanks:

**Comment by khouloudbelguith** [comment]
@cboillat, I tried again with PS1.7.6.0 but I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1cA4mxX-14INdJTs5hoVT0YLMwA4dqlBV/view

Thanks to check & feedback.

**Comment by cboillat** [comment]
@khouloudbelguith 
is the Geolocalisation by IP enabled during your test ?

**Comment by khouloudbelguith** [comment]
@cboillat, yes!
https://drive.google.com/file/d/1egtmpX71sSxLlqf8NLd3IguI69EWflAl/view
Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith 
So if I want to have the right price and table prices even if not logged I must use a plugin like [this one](https://addons.prestashop.com/fr/international-localisation/27368-geo-targeting-pro-by-country-prices-taxes-currency-.html) ?

**Comment by khouloudbelguith** [comment]
@cboillat, yes it could be a solution to your problem.
Since in my case, I did not manage to reproduce the issue.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!

**Comment by cboillat** [comment]
@khouloudbelguith 
Alright thank you for all the tests, video and for your help. Maybe an update to 1.7.6.0 will correct my bug.
