### ISSUE TITLE
The customized payment module always appears in Other category section in Module manager page

### ISSUE THREAD

**Issue by sunnyvsrainy** [PrestaShop/PrestaShop#14538]
**Describe the bug**
The customized payment module always appears in Other category section in Module Module manager page, although I already specified  
`<tab><![CDATA[payments_gateways]]></tab>`
 in config.xml 
and          
`$this->tab = 'payments_gateways';`
in the constructor method.

**To Reproduce**
1. Go to 'Module->Module Manager'
2. Click on 'Upload a module' button on top right
3. Select the attached file zip and upload
4. Refresh the Module Manager page
5. Then you will see the module appears in Other  category section . My understanding is: it should appear in Payment category. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9953993/60873365-d8da6280-a268-11e9-89f4-794b28415756.png)

config.xml
![image](https://user-images.githubusercontent.com/9953993/60873720-64ec8a00-a269-11e9-871f-569a38071ca3.png)

constructor:
![image](https://user-images.githubusercontent.com/9953993/60873798-85b4df80-a269-11e9-9c25-864624dbf659.png)

**Additionnal information**
PrestaShop version: 7.5.1
PHP version: 7.2

[universalpay.zip](https://github.com/PrestaShop/PrestaShop/files/3372052/universalpay.zip)

**Comment by khouloudbelguith** [comment]
Hi @sunnyvsrainy,

Thanks for your report.
Yes, I tried with your module with PS1.7.5.2 & PS1.7.6.0rc2.
It is displayed in the Other category.
But, when I tried to install other modules Like Paypal & COD, they are well displayed in the Payment category
![image](https://user-images.githubusercontent.com/16067358/60876287-80d53900-a233-11e9-9c10-c6dccd2fb39d.png)
In fact, the modules are retrieved via the API push.
So if the module is not in addons, the category is not recovered

So it's "normal" behavior.

I close the issue, feel free to open a new one when needed.

Thanks!
