### ISSUE TITLE
Product customization field fixed price

### ISSUE THREAD

**Issue by siomosp** [PrestaShop/PrestaShop#14548]
Hi,
please add at Product customization field,  option to add a fixed price, and or weight
Now it can be done only by a module
Thanks
Panagiotis

**Comment by khouloudbelguith** [comment]
Hi @siomosp,

What is the exact module did you use to add this feature?
Can you please provide us a screenshot about this field fixed price from the Back office?

Thanks!

**Comment by siomosp** [comment]
Hi @khouloudbelguith ,
it is a feature request for the next releases of Prestahop.
I am asking to add this feature at Prestahop core.
( I use this module https://addons.prestashop.com/en/sizes-units/19389-dynamic-product-price.html 
but i think at most products there is no need for a module, if at PS core was the option to add static price and weight to customization fields)
Thanks!

**Comment by khouloudbelguith** [comment]
@siomosp, thanks for your feedback.
ping @marionf, @colinegin what do you think?

Thanks!

**Comment by marionf** [comment]
Hello @siomosp 

You can already do this through a product with combinations. 
For a customized product it's really a specific need and a module already exists, so we don't plan to add this feature natively
