### ISSUE TITLE
Add employee info on the PaymentPanel when payment is registered 

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#14547]
Hi,
How can we do in BO order page to include the name of the employee who adds manually a payment in formAddPaymentPanel? just the same way in "table history-status" registers for each status change who changed it.
I think it's an interesting option to better control who adds payments when you have many authorized employees that can do so.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @omar2886,

Thanks for your report.
This is could be an improvement added to the order page after the migration to Symfony: #13878.
Ping @colinegin @marionf what do you think can we add the employee name in the Payment section?
![image](https://user-images.githubusercontent.com/16067358/60883994-a9fdc580-a243-11e9-835d-2406d09aa7e8.png)

Thanks!

**Comment by seifygsm** [comment]
Employee who adds manually a payment is very important. please add this.

**Comment by MatShir** [comment]
@seifygsm The feature seems relevant. I will join it to the epic #17598 which regroups ideas and bugs around the same problematics.

Also, we would like to have more information about your feature request even if it seems obvious just to be sure we have all the insight to make a decision. 
Why is it important to have the name of the employee? 
How does it influence your order management?
How are you going to use this data afterward?

It will help us to add more context around your feature request.
Thank you :)

**Comment by omar2886** [comment]
> @seifygsm The feature seems relevant. I will join it to the epic #17598 which regroups ideas and bugs around the same problematics.
> 
> Also, we would like to have more information about your feature request even if it seems obvious just to be sure we have all the insight to make a decision.

> Why is it important to have the name of the employee?

**_It's important to well control who added which payment as any employé can do it by mistake or not. If the wrong amount or a non existing payment is added, the employé must be accountable for it, otherwise the company has absolutely no control on the real incomes._**

> How does it influence your order management?

**On e-commerce and any kind of company, the most basic thing is to have control of the income and expenses, so you need to know who, when and how registered a payment for an order.**

> How are you going to use this data afterward?

**Employees must be accountable of how they use the system**
> 
> It will help us to add more context around your feature request.
> Thank you :)

**Comment by MatShir** [comment]
@omar2886 It seems, your suggestion was not published correctly on Github.

**Comment by omar2886** [comment]
answered between lines, I made it more clear.

**Comment by MatShir** [comment]
Thank you @omar2886 for your feedack. It shared to the product team.

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/9676

**Comment by Matt75** [comment]
@MatShir PrestaShop Checkout module received feedbacks from Support Team about merchants want to log actions of employee about payments

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team What is the status of this issue?

**Comment by omar2886** [comment]
> Ping @PrestaShop/product-team What is the status of this issue?

yes please! this is critical, and I'd like if there was a way to implement it manually on previous versions, because it took me 2 years to upgrade 1.6 to 1.7 and I'm no planning to do another major upgrade just to have a couple new features.
Thanks!

**Comment by MatShir** [comment]
Sorry to tell you @omar2886, for now, your issue wasn't yet implemented by the PrestaShop team. PrestaShop is open-source software so if another contributor finds your feature relevant, they might implement it. Keep in mind that all implementation will be for the latest PrestaShop version.

But if it is major feature for your business, you could hire a developer to implement it for you and share your feature in Github so that all merchants can benefit from it. The feature doesn't look complex to develop.
