### ISSUE TITLE
Image not displayed in example data in "About" CMS page

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#14559]
**Describe the bug**
An image in the "About" CMS page is not displayed. The "src" attribute is not correct if we install Prestashop in a folder without URL rewriting (it seems to be written as `../img/cms/cms-img.jpg` and thus breaks when in a subfolder).

**To Reproduce**
1. Install Prestashop 1.7.6 in a subfolder (country FR, language EN)
2. Go to the "About" page (link in footer)
3. Check the middle column

**Screenshots**
![image](https://user-images.githubusercontent.com/49909275/60902933-bd735580-a270-11e9-83cd-741e5846ca73.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SimonGrn,

I have the same issue with PS1.7.5.2 & PS1.7.6.0rc2.
I’ll add this to the debug roadmap so that it’s fixed.
Thanks!
