### ISSUE TITLE
The alert "Unfortunately, there is no payment method available." is not displayed in the checkout page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#14554]
**Describe the bug**
After disabling all the Payment modules, the alert "Unfortunately, there is no payment method available." is not displayed on the checkout page.
![image](https://user-images.githubusercontent.com/16067358/60894454-9a3dab80-a25a-11e9-8ad5-23dbbf155d62.png)

![image](https://user-images.githubusercontent.com/16067358/60894494-b2152f80-a25a-11e9-85f6-6bd6c0bc0a71.png)

**To Reproduce**
1. Go to BO => Module manager page
2. Disable all the Payment modules
3. Go to the FO => Add some product to the cart => complete the order
4. In the Payment method, the alert "Unfortunately, there is no payment method available." is not displayed on the checkout page.

PS1.7.5.1 => OK
PS1.7.5.2 / PS1.7.6.0rc2 => NOK

**Additionnal information**
PrestaShop version: 1.7.5.2 / 1.7.6.0rc2
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith 

I well have it both on 1.7.5.2 and 1.7.6.0 RC2

![capture d'écran_1744](https://user-images.githubusercontent.com/13449658/60895525-1e952c00-a265-11e9-8fd7-8ee768f15986.png)

**Comment by marionf** [comment]
@sarahdib Can you try to reproduce it ?

**Comment by khouloudbelguith** [comment]
@marionf, I have the same issue on the machine shuffle (Ps1.7.5.2)
Could you please check with this link: http://talented-connection.machine-shuffle.prestashop.net/en/
Thanks!

**Comment by marionf** [comment]
On machine shuffle yes, but I can't reproduce on localhost 1.7.5.2 & 1.7.6.0RC2

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Re-installing the shop 1.7.6.0rc2 & clear cache from the shop in Machine shuffle => the issue doesn't exist anymore.
I close the issue.

Thanks!

**Comment by hdkcreative** [comment]
reset the module !

**Comment by msaustral** [comment]
Hi Everyone here is a workaround
1.- Find the table prefix_carrier -> take note of the field id_reference of all your active carriers
2.- Find the tables prefix_module -> take note of the field id_module of all your active payment module
3.- Find the table prefix_module_carrier -> you will see that there are missing entries for your carrier id_reference with the payment id_module associated, create the missing one
the row id_module is the id of the payment module that you have active
the row id_reference is the id of the carrier that you want thar payment to be available.
Still do not know what is causing these records to disappear but this solves the issue, have a good day :)

**Comment by mmystery** [comment]
@msaustral workaround fixed the problem, thank you!

I confirm the same problem. I'm on PS 1.7..6.8.

No alert "Unfortunately, there is no payment method available." was shown to the user. 

I have tried to save again the settings in the Payment -> Preferences, both Payment Restrictions and Carrier Restrictions, but nothing happened. I had to add the missing lines in the DB as per msaustral's instructions.

This problem happened without changing anything, the payments worked normally up to some days ago. Nothing logged, and no errors.

@khouloudbelguith if you could please reopen the issue, as it still stands...

**Comment by msaustral** [comment]
Hi @mmystery nice to help

**Comment by mmystery** [comment]
Update,

this error also happens even if the tables records are populated correctly. 

This morning I got a recording from a user which tried to checkout but without any payment options and without any error. 

@marionf If you could please reopen the issue, as it still stands, or you prefer me to open a new issue?

Thanks

**Comment by marionf** [comment]
Hello @mmystery 

Please create a new issue :)

Thank you
