### ISSUE TITLE
Better default Contact Form anti spam design

### ISSUE THREAD

**Issue by ProBackup-nl** [PrestaShop/PrestaShop#14553]
**Is your feature request related to a problem? Please describe.**
Within 2 days after lifting the geolocation country block, the first [FO] contact form spam message arrived from talkwithcustomer.com aka liveserveronline.com.

**Describe the solution you'd like**
I do want better form spam handling: for example css hidden form fields that required specific values.

1. duplicate attack detection
One annoying attack on HTML forms scripts is to submit an email address in every field, with the aim of getting the script to send email to someone via your server. Check input fields that are not checkbox, radio button, or select fields for duplicates.

2. check fields for presence of e-mail address
This attack detection logic checks certain special fields for the presence of an email address. The special fields that are checked would never have an email address in them, so the presence of an email address indicates an attack on the form.

3. fields to check for containing only an email address
This means the whole field must comprise just an email address in order to be detected as an attack. 

4. block textarea submissions with many urls
Allow a configurable amount of urls. 1, 2 or 3 seem reasonable.

5. insert a css hidden field that should remain empty
When the field is submitted with a value, it is most likely a spamming bot.

6. insert a css hidden field with a known value
In case the value is changed, it is most likely a spamming bot.

**Describe alternatives you've considered**
I don't want any modules for this: **Form spam protection** should be the **default**.
I don't want any (re)captchas, what a waste of user time.

**Comment by khouloudbelguith** [comment]
Hi @ProBackup-nl,

Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
There are already a lot of anti-spam protections modules: https://addons.prestashop.com/en/429-website-security-access

Having it inside the Core could be a problem because of maintainability and updates. The release process of a module is always faster, easier and can be available in a lot of PrestaShop versions :)
