### ISSUE TITLE
The auto emails dont work properly

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#14566]
The system isn't sending emails to clients I get the email telling me they have made a purchase but they are not getting any email with a receipt or instructions on how to pay, if they select to pay by Bitcoin or bank transfer they should get the email with the banking instructions, but they get nothing so I can not trade right now.

I run 3 sites and 1 is working perfectly and the other 2 don't, they are both suffering the same problems, even in the order management page where I would normally update the record to say payment complete I just get error messages and no emails are being sent.

Whats going on, what can I do to fix this error?

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

Thanks for your report.
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email.
Thanks to check & feedback.

**Comment by Allthejam** [comment]
Hi, and yes I have done that many time now and every time I get the email, it's not the problem, the problem is that the clients do not get an email.
For example,
A client makes a purchase and chooses to pay by either Bank Transfer or Bitcoin, this is great they make the purchase I get an email telling me that they have made the purchase but they receive NO email with instructions on how to pay, and even when I update their status to canceled, paid or anything the system has an error and can't send them the email confirming the new status.

![2019-07-10_152631](https://user-images.githubusercontent.com/52738920/60972801-42b94180-a327-11e9-875b-0f4f78b2eadf.jpg)

The problem is not me getting any emails I get them all just fine, it's the clients that are not getting any emails, 

Can you help?

**Comment by khouloudbelguith** [comment]
@Allthejam, could you please navigate to the BO => Shop Parameters => Order Settings => Statuses Tab & check for each status if "Send email to customer" is enabled.
![image](https://user-images.githubusercontent.com/16067358/60974352-de47b380-a321-11e9-8683-b3b631c82a27.png)

Thanks!

**Comment by Allthejam** [comment]
Yes I have everything on, 
![2019-07-10_160401](https://user-images.githubusercontent.com/52738920/60975537-7054b980-a32c-11e9-86b1-e8ca9ba77b85.jpg)

I have created a new account to test for myself again and its all still the same
![2019-07-10_160319](https://user-images.githubusercontent.com/52738920/60975614-89f60100-a32c-11e9-9431-680be629019b.jpg)

**Comment by khouloudbelguith** [comment]
@Allthejam, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Allthejam** [comment]
Hey, 

1. Hosted - on One.com
2. Server setup - PHP version 7.3
Web server
nginx/1.14.0
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.17-0ubuntu0.18.04.1

Database server
Server: blu-pharma.com.mysql (blu-pharma.com.mysql.service.one.com via TCP/IP)
Server type: MariaDB
Server version: 10.3.12-MariaDB-1:10.3.12+maria~bionic - mariadb.org binary distribution
Protocol version: 10
User: blu_pharma_com_db1@10.27.22.48
Server charset: UTF-8 Unicode (utf8)
                           
3. Prestashop version - 1.7.5.2
4. debug mode report - 
5. PHP error log - 
6. apache error log - 
7. javascript console log - 

As for 4, 5, 6, & 7. I have no error logs not that I can find as for the debug I have no idea what I'm looking at.

Thank you

**Comment by khouloudbelguith** [comment]
@Allthejam, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by Allthejam** [comment]
Not good news, but changing it has not solved the problem in fact 1 of the sites I have is running PHP 7.1 and always has been so now I'm really stuck because the site I have that's all working correctly has been running on PHP 7.3, 

The site that I was testing with you, I have modified it through 7.1, 7.2, 7.3 and a beta 7.4 and nothing there made a difference so I ruled out the PHP as an issue.

Any other ideas because Im totally lost.

Thank you.

**Comment by khouloudbelguith** [comment]
@Allthejam, did you use the PHP's mail() function or SMTP parameters?

Thanks!

**Comment by Allthejam** [comment]
PHP's mail() function

Wasn't sure about the settings for SMTP

**Comment by khouloudbelguith** [comment]
@Allthejam, did you checked your spam, it could be received in the spam.
Thanks!

**Comment by Allthejam** [comment]
That was the 1st this we checked, its an error in PS remember the image I sent showing the error message, it's just not sending any messages to clients or today it's not even sending me the test email anymore 
![2019-07-12_171022](https://user-images.githubusercontent.com/52738920/61138527-f9542800-a4c7-11e9-892e-1b095816dc67.jpg)

**Comment by khouloudbelguith** [comment]
@Allthejam, this is a server configuration server, you need to check with your host.
This option is recommended by default. In the event that this does not work, then use the SMPT option.

Thanks!

**Comment by Allthejam** [comment]
Can I only use the email account setting for outgoing mail that I used to create the account? 
Because 
Error: Please check your configuration

Expected response code 250 but got code "550", with message "550 5.7.1 Username info@xxxxxxx-xxxxxx.com and sender blxxxxx2xx8@gmail.com doesn't match "

I think you'll get it.

**Comment by khouloudbelguith** [comment]
@Allthejam, could you please try to change it, check & feedback.

**Comment by Allthejam** [comment]
Where do I find and change the sender address?

**Comment by Allthejam** [comment]
Solved the problem for now anyway I think.

The email address on the CMS/Stores page has to be the same as the sender's address in the advanced parameters/email page, and once you get the correct SMTP info from the host it works, now it's just a case of settings on the individual payment gateway installed.

Thank you for all your assistance.

**Comment by khouloudbelguith** [comment]
@Allthejam, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
