### ISSUE TITLE
prestashop 1.7.6 payment accepted status error

### ISSUE THREAD

**Issue by razvypp** [PrestaShop/PrestaShop#14561]
Bad encoding when changing status to Payment Accepted, instead of redirect i get: GIF89a�����,D;

https://snag.gy/eH4Jmp.jpg

**Comment by khouloudbelguith** [comment]
Hi @razvypp,

What is the exact payment module did you use?
In my case, I did not manage to reproduce the issue with Fresh installation PS1.7.6.0rc2
https://drive.google.com/file/d/1PEG_U_8oTjXnvN9ePmvbL5LqmI5MQO5J/view
Thanks!

**Comment by razvypp** [comment]
It is the same when I change to Canceled order.
I am using cash on delivery module (codwfeeplus) here is the exact link: https://filebin.net/xj0h9s2oekl8jen0

**Comment by SimonGrn** [comment]
Are you sure this is not related to this module you're using ? The module has been updated for PS 1.7.6.0 24 days ago, are you using the latest version ?

(Also please think about following the issue template, it's made this way to help us help you ;-) )

**Comment by khouloudbelguith** [comment]
@razvypp, I tried to use your module with PS1.7.6.0RC2 & I don't have any issue after changing the order's status to payment accepted.
I attached a screen record
https://drive.google.com/file/d/1NFm5WjzWE62gLeoQ5WbnuQcTR5pAMcCJ/view
Thanks to check & feedback.

**Comment by decom-media** [comment]
@razvypp - why you are using this module, is there any advantage to the prestashop cash on delivery module which is already included?

**Comment by razvypp** [comment]
> @razvypp - why you are using this module, is there any advantage to the prestashop cash on delivery module which is already included?

I cannot find the prestashop cash on delivery module for prestashop 1.7.6

**Comment by khouloudbelguith** [comment]
@razvypp, you need to navigate to your BO => Modules => Module Catalog => search for "COD" & install it.
https://drive.google.com/file/d/1TEhkw7XfVREqVTwOiGdCUt74o2TZxWyG/view

Thanks!

**Comment by mariem-abid** [comment]
Hi @razvypp,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
