### ISSUE TITLE
Can't upload module via backend

### ISSUE THREAD

**Issue by kernig** [PrestaShop/PrestaShop#14568]
**Describe the bug**
When you try to install a module it shows an error: "1G" is not a valid maximum size.

**To Reproduce**
1. Go to 'Module Manager'
2. Click on 'Upload Module'
3. Select your module to start upload

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

This is caused by the PHP setting upload_max_filesize, which is set to 1G

I found a fix on this website:
https://kijam.com/tienda/reparar-error-1g-is-not-a-valid-maximun-size-en-prestashop-1-7/

Quote:
You need to  edit this file "/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/File.php"

Replace this part:
        $factors = array(
            'k' => 1000,
            'ki' => 1 << 10,
            'm' => 1000000,
            'mi' => 1 << 20,
        );

with this
        $factors = array(
            'k' => 1000,
            'ki' => 1 << 10,
            'm' => 1000000,
            'mi' => 1 << 20,
            'g' => 1000000000,
            'gi' => 1 << 30,
        );

**Comment by khouloudbelguith** [comment]
Hi @kernig,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by kernig** [comment]
Hi @khouloudbelguith,

thank you for your quick response.
You are right, the script marks the G values red. 
In the PHP documentation it says "PHP allows shortcuts for byte values, including K (kilo), M (mega) and G (giga)." so in my opinion presta should be able to handle that :-)

**Comment by khouloudbelguith** [comment]
@kernig, could you please provide me a screenshot about your PHP's information for your server that you have just uploaded.

Thanks!

**Comment by kernig** [comment]
![prestaresult](https://user-images.githubusercontent.com/17124093/60963807-1d6e0880-a312-11e9-9013-4ec22b0294d8.png)
@khouloudbelguith 
if you need more details, just let me know.

**Comment by khouloudbelguith** [comment]
@kernig, Thanks for your feedback.
Ye, I tried with 1G with my server & it not accepted.
![image](https://user-images.githubusercontent.com/16067358/60965114-efd29080-a30c-11e9-879e-b05920db7c3a.png)
Ping @PrestaShop/prestashop-core-developers what do you think about his suggestion?
>In the PHP documentation it says "PHP allows shortcuts for byte values, including K (kilo), M (mega) and G (Giga)." so in my opinion presta should be able to handle that

Thanks!

**Comment by PierreRambaud** [comment]
It's normal because 1G is not a supported value by Symfony.
An issue has already been created https://github.com/PrestaShop/PrestaShop/pull/10892

**Comment by khouloudbelguith** [comment]
@PierreRambaud, thanks for your feedback.
@kernig, you should not use G with upload_max_filesize.
I close the issue, Feel free to open a new one when needed.

Thanks!

**Comment by kernig** [comment]
@khouloudbelguith, thanks for verifying it.
@PierreRambaud, thank you. Didn't see it, when opening this issue.
I already posted it in the symfony repository and they asked me to send a pull request.
I'm not sure if it would be better to wait for the next symfony update in prestashop or if there should be a seperate fix for the meantime. If they implement it in 3.4 does presta get it with the next update automatically?

**Comment by kernig** [comment]
Hey @khouloudbelguith, @PierreRambaud,  
symfony team accepted the pull request. When does the symfony 3.4 update find it's way to the presta core?

**Comment by Progi1984** [comment]
@kernig Hi, have you got the link to the PR ? Thanks :)

**Comment by kernig** [comment]
Hi @Progi1984, sure, it's https://github.com/symfony/symfony/pull/32485
