### ISSUE TITLE
Contácte a un técnico de hosting detectó este error Uncaught Error: Class 'SmartBlogLink' 

### ISSUE THREAD

**Issue by luisagreda10** [PrestaShop/PrestaShop#14565]
We were trying to upload a template several times and I throw that limiting size did not allow upload, it was modified and added the subject, but when you add the subordinate website fell. I need support for the same please.

The technician answered this and told us to contact you:

thrown in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php on line 134
[09-Jul-2019 17:57:29 America/Santiago] PHP Fatal error:  Uncaught Error: Class 'SmartBlogLink' not found in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php:134
Stack trace:
#0 /home/zhiyunte/public_html/classes/Hook.php(895): SmartBlogAddThisButton->hookDisplayHeader(Array)
#1 /home/zhiyunte/public_html/classes/Hook.php(327): HookCore::coreCallHook(Object(SmartBlogAddThisButton), 'hookdisplayHead...', Array)
#2 /home/zhiyunte/public_html/classes/Hook.php(843): HookCore::callHookOn(Object(SmartBlogAddThisButton), 'displayHeader', Array)
#3 /home/zhiyunte/public_html/classes/controller/FrontController.php(533): HookCore::exec('displayHeader')
#4 /home/zhiyunte/public_html/controllers/front/IndexController.php(37): FrontControllerCore->initContent()
#5 /home/zhiyunte/public_html/classes/controller/Controller.php(205): IndexControllerCore->initContent()
#6 /home/zhiyunte/public_html/classes/Dispatcher.php(379): ControllerCore->run()
#7 /home/zhiyunte/public_html/index.php(28): DispatcherCore->dispatch()
#8 {main}
  thrown in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php on line 134
[09-Jul-2019 17:57:29 America/Santiago] PHP Fatal error:  Uncaught Error: Class 'SmartBlogLink' not found in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php:134
Stack trace:
#0 /home/zhiyunte/public_html/classes/Hook.php(895): SmartBlogAddThisButton->hookDisplayHeader(Array)
#1 /home/zhiyunte/public_html/classes/Hook.php(327): HookCore::coreCallHook(Object(SmartBlogAddThisButton), 'hookdisplayHead...', Array)
#2 /home/zhiyunte/public_html/classes/Hook.php(843): HookCore::callHookOn(Object(SmartBlogAddThisButton), 'displayHeader', Array)
#3 /home/zhiyunte/public_html/classes/controller/FrontController.php(533): HookCore::exec('displayHeader')
#4 /home/zhiyunte/public_html/controllers/front/PageNotFoundController.php(42): FrontControllerCore->initContent()
#5 /home/zhiyunte/public_html/classes/controller/Controller.php(205): PageNotFoundControllerCore->initContent()
#6 /home/zhiyunte/public_html/classes/Dispatcher.php(379): ControllerCore->run()
#7 /home/zhiyunte/public_html/index.php(28): DispatcherCore->dispatch()
#8 {main}
  thr in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php on line 134
[09-Jul-2019 17:57:31 America/Santiago] PHP Fatal error:  Uncaught Error: Class 'SmartBlogLink' not found in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php:134
Stack trace:
#0 /home/zhiyunte/public_html/classes/Hook.php(895): SmartBlogAddThisButton->hookDisplayHeader(Array)
#1 /home/zhiyunte/public_html/classes/Hook.php(327): HookCore::coreCallHook(Object(SmartBlogAddThisButton), 'hookdisplayHead...', Array)
#2 /home/zhiyunte/public_html/classes/Hook.php(843): HookCore::callHookOn(Object(SmartBlogAddThisButton), 'displayHeader', Array)
#3 /home/zhiyunte/public_html/classes/controller/FrontController.php(533): HookCore::exec('displayHeader')
#4 /home/zhiyunte/public_html/controllers/front/IndexController.php(37): FrontControllerCore->initContent()
#5 /home/zhiyunte/public_html/classes/controller/Controller.php(205): IndexControllerCore->initContent()
#6 /home/zhiyunte/public_html/classes/Dispatcher.php(379): ControllerCore->run()
#7 /home/zhiyunte/public_html/index.php(28): DispatcherCore->dispatch()
#8 {main}
  thrown in /home/zhiyunte/public_html/modules/smartblogaddthisbutton/smartblogaddthisbutton.php on line 134

**Comment by khouloudbelguith** [comment]
Hi @luisagreda10,

The `smartblogaddthisbutton` module is perhaps incompatible with your PrestaShop version.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
