### ISSUE TITLE
error after upgrade to 1.7.6.0

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#14580]
ubuntu 18.4
upload zip into admin/autoupgrade, after all upgrade I've this error
https://nimb.ws/SdoxMU
attached the admin/autoupgrade/tmp
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3379254/log.txt)
Now accessing on admin, always...
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Did you make an upgrade to PS1.7.6.0 using the 1-click upgrade v4.9.0? using the `Local archive` mode?
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by centoasa** [comment]
I had to use the local archive because, even now, PS tells me that my version 1.7.5.2 is still the most up to date.
First of update I've manually delete var/cache/prod folder.
Now I'm working on my PS webshop, because tonight I've restored my whole website backup.

**Comment by khouloudbelguith** [comment]
@centoasa, there's a small delay between the 1.7.6.0 release and its availability in the autoupgrade.
The delay is usually 24 hours.

So, you just make a back up to the last version PS1.7.5.2?
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith I'm using 1.7.5.2 restored from a previous backup.
have you seen the log? why the last error
`[2019-07-10 19:48:09] [INTERNAL] /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php line 87 - require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear')` caused me the error 500 on backoffice, and not being able to use it anymore?

**Comment by khouloudbelguith** [comment]
@centoasa, you just have those errors previously: https://github.com/PrestaShop/PrestaShop/issues/13355#issuecomment-498961164
It is a Symfony cache.
You need to remove the cache manually & refresh the Back office page & the FO.

Thanks!

**Comment by jolelievre** [comment]
Hi @centoasa 
Maybe you can try running this command `rm -fR ./var/cache/* && ./bin/console cache:clear --env=prod && ./bin/console cache:clear`
This will remove your cache and perform a warmup of the Symfony cach (including the appParameters.php file), if it doesn't work it might be because of a permission problem preventing you from writing (be careful your user and the server user have compatible rights)

**Comment by Quetzacoalt91** [comment]
Also check the permission on the folder are correct. By calling some commande from a terminal, you may get the wrong user and PHP won't be able to read / modify on the cache.

**Comment by centoasa** [comment]
@jolelievre my /var/cache/ directory have 777 and remigio/psacln
appparameters.php have 644
@khouloudbelguith those settings are right?

**Comment by jolelievre** [comment]
Using 777 rights is not a good practice, because it lets anyone read/write/access your folder
That said it should work now if you ran the command, do you still have the issue?

**Comment by centoasa** [comment]
@jolelievre run command, with -bash: ./bin/console: Permission denied
/bin/console have 644 (as default) so I've to first change it to higher permission and after run command?

**Comment by jolelievre** [comment]
No need to change the permission if it is 644 you can call it with php instead: `php ./bin/console cache:clear`
It's actually safer to do it this as it should work on most environments (I'm just just to execute this script directly)

**Comment by centoasa** [comment]
@khouloudbelguith do you suggest upgrade to 1.7.6.0 via oneclick 4.9 or local archive? what's the better for ensure better results?

**Comment by khouloudbelguith** [comment]
@centoasa, in my case, I tried to upgrade to PS1.7.6.0 using the local archive & the 1-click upgrade v4.9.0.
In the two cases, the upgrade is well done.
In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith  @jolelievre 
:-(
step to reproduce my issue-->debian 9.9 with php 7.2.20-->
login into colsole as root; 
run via console rm -fR ./var/cache/*
php ./bin/console cache:clear --env=prod 
php ./bin/console cache:clear
cache cleared OK
upgrade via oneclick 4.9, at the end of upgrade, when was to upgrade database.....
[INTERNAL] /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php line 87 - require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear')
and my prestashop stuck and my admin show always the message:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment]
@centoasa, after having this error, did you tried to clear cache manually?

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith yes, sure, many times, but nothing. Issue remain.
I think the very issue is on database, because the server stuck just while on ....database upgrade

**Comment by khouloudbelguith** [comment]
Ping @Quetzacoalt91, @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by Quetzacoalt91** [comment]
That's weird because when we check the concerned "bootstrap.php", we see:

```php
[...]

if ($lastParametersModificationTime) {
    $cachedParameters = _PS_CACHE_DIR_. 'appParameters.php';

    $lastParametersCacheModificationTime = (int)@filemtime($cachedParameters);
    if (!$lastParametersCacheModificationTime || $lastParametersCacheModificationTime < $lastParametersModificationTime) {
        // When parameters file is available, update its cache if it is stale.
        if (file_exists($phpParametersFilepath)) {
            $config = require $phpParametersFilepath;
            $exportPhpConfigFile($config, $cachedParameters);
        } elseif (file_exists($yamlParametersFilepath)) {
            $config = Yaml::parse($yamlParametersFilepath);
            $exportPhpConfigFile($config, $cachedParameters);
        }
    }

    $config = require_once _PS_CACHE_DIR_ . 'appParameters.php'; # <- ERROR THROWN HERE
    array_walk($config['parameters'], function (&$param) {
        $param = str_replace('%%', '%', $param);
    });
[...]
```

The file is supposed to be generated if it does not exist or if it is older than the parameters.php. This means the PHP cannot access the file, although it exists.

**Comment by ihrewebagentur** [comment]
I had the same error in the logs after new installation of 1.7.6.
I could solve the problem with the following steps:
- delete symfony cache in console
- set rights 777 to var/cache

Then Backoffice and Frontend worked immediately.

**Comment by centoasa** [comment]
My Prestashop 1.7.5.2 say still my version is update!
https://nimb.ws/EpoQZt

**Comment by centoasa** [comment]
> No need to change the permission if it is 644 you can call it with php instead: `php ./bin/console cache:clear`
> It's actually safer to do it this as it should work on most environments (I'm just just to execute this script directly)

@jolelievre login into console as root, after your suggested commands, folder prod have root/root user/group permission
Is this right or wrong?

**Comment by jolelievre** [comment]
You shouldn't use this command as root (actually you should **never** login as root unless you need to install things on your server and know exactly what you're doing) Because it will generate your cache files with root ownership and then your server is unable to access or modify them

I don't know about your server settings so I can't be sure but you should use either a user which has the same group as your server user (www, apache, ...) Or you can try login as the same user as your server Lastly you can try running the script with your user and then perform a `chown` on your cache files

But honestly it appears you are not very familiar with these kind of manipulations, so I wouldn't advise you trying something you don't really understand I hope you are not doing all these manipulations on a production website?

**Comment by centoasa** [comment]
When delete /var/cache/prod folder manually, it recreate with user/group of the server (not root).
So I've do it. 
Thanks @jolelievre

**Comment by centoasa** [comment]
why still today my prestashop 1.7.5.2 is show aas "product update"?
https://nimb.ws/Aq9Qr5

**Comment by khouloudbelguith** [comment]
@centoasa, issue created: https://github.com/PrestaShop/PrestaShop/issues/14688

**Comment by centoasa** [comment]
I tried once again to upgrade to 1.7.6 but I still have the same problem: `[INTERNAL] /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php line 87 - require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear')`
after I clear manually /var/cache/* login screen appear well,  but after login I'ìve always: Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment]
@centoasa, did you tried to clear cache manually as before or not?

Thanks!

**Comment by centoasa** [comment]
as I wrote, I've deleted cache manually first of update, and after too

**Comment by centoasa** [comment]
I'm sorry, I forgot: this time I upgraded directly from 1click v4.9.0

**Comment by centoasa** [comment]
Tryed again, after all, I've enabled debug and found:

(1/1) PrestaShopDatabaseExceptionTable 'prestashop_5.ps_currency_lang' doesn't exist<br /><br /><pre>SELECT *FROM `ps_currency_lang`WHERE `id_currency` = 1</pre>
--
in Db.php line 769
at DbCore->displayError('SELECT *	FROM `ps_currency_lang`	WHERE `id_currency` = 1')in Db.php line 385
at DbCore->query('SELECT *	FROM `ps_currency_lang`	WHERE `id_currency` = 1')in Db.php line 613
at DbCore->executeS('SELECT *	FROM `ps_currency_lang`	WHERE `id_currency` = 1')in EntityMapper.php line 82
at EntityMapper->load('1', null, object(Currency), array('table' => 'currency', 'primary' => 'id_currency', 'multilang' => true, 'fields' => array('iso_code' =>array('type' => 3, 'validate' => 'isLanguageIsoCode', 'required' => true, 'size' => 3), 'numeric_iso_code' => array('type' => 3, 'validate' => 'isNumericIsoCode', 'size' => 3), 'precision' => array('type' => 1, 'validate' => 'isInt'), 'conversion_rate' => array('type' => 4, 'validate' => 'isUnsignedFloat', 'required' => true, 'shop' => true), 'deleted' => array('type' => 2, 'validate' => 'isBool'), 'active' => array('type' => 2, 'validate' => 'isBool'), 'name' => array('type' => 3, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255), 'symbol' => array('type' => 3, 'lang' => true, 'size' => 255)), 'classname' => 'Currency', 'associations' => array('l' => array('type' => 2, 'field' => 'id_currency', 'foreign_field' => 'id_currency'))), 1, true)in ObjectModel.php line 264
at ObjectModelCore->__construct('1', null, null)in Currency.php line 177
at CurrencyCore->__construct('1')in AdminController.php line 2950
at AdminControllerCore->initShopContext()in AdminController.php line 535
at AdminControllerCore->__construct()in LegacyContext.php line 85
at LegacyContext->getContext()in UserLocaleListener.php line 39
at UserLocaleListener->__construct(object(LegacyContext))in appDevDebugProjectContainer.php line 2381
at appDevDebugProjectContainer->getPrestashop_UserLocale_ListenerService()in appDevDebugProjectContainer.php line 2868
at appDevDebugProjectContainer->ContainerJjgaxyi\{closure}()in EventDispatcher.php line 229
at EventDispatcher->sortListeners('kernel.request')in EventDispatcher.php line 61
at EventDispatcher->getListeners('kernel.request')in ContainerAwareEventDispatcher.php line 128
at ContainerAwareEventDispatcher->getListeners('kernel.request')in TraceableEventDispatcher.php line 262
at TraceableEventDispatcher->preProcess('kernel.request')in TraceableEventDispatcher.php line 137
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 86

**Comment by khouloudbelguith** [comment]
@centoasa, this issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620
Your issue is duplicate of https://github.com/PrestaShop/PrestaShop/issues/14617

Thanks!

**Comment by centoasa** [comment]
Sorry, I'm confused! but debug say into my db is missing the table ps_currency_lang (I've cecked and it's missing). The #14620 talk about other files. I'm wrong?
where I can found the list of all table of db for 1.7.6, to compare mine?

**Comment by khouloudbelguith** [comment]
@centoasa, it is the same error log reported here: https://github.com/PrestaShop/PrestaShop/issues/14617#issuecomment-510884731
And this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 fixes this issue.
Thanks!

**Comment by centoasa** [comment]
:-) @khouloudbelguith I'm very sorry. The #14620 talk about changes into install/upgrade/upgrade.php (it's right?). But now with my 1.7.5.2 ver. I've no install directory? So?

**Comment by khouloudbelguith** [comment]
@centoasa, those fixes are added in the next release 1.7.6.1: the Major version & not the previous version.

Thanks!

**Comment by centoasa** [comment]
but first you tell me that # 14620 fixes my problem, then you tell me that these solutions will be included in the next release. So how can I upgrade to 1.7.6 now?

**Comment by centoasa** [comment]
download original release of 1.7.6.0, update upgrade.php file as described in #14620, zip again all the prestashop folder, put it into admin/autoupgrade/download
Tried also with unzipped folder into /latest, same error:
Analyzing the situation...Shop deactivated. Extracting files...
File extraction complete. Removing sample files...

Downloading step has been skipped, upgrade process will now unzip the local archive.
Starting upgrade...
"/latest" directory has been emptied
Content of archive /var/www/vhosts/100asa.it/httpdocs/Back100asa/autoupgrade/download/presta176.zip is extracted
errori
Could not assert the folder /var/www/vhosts/100asa.it/httpdocs/Back100asa/autoupgrade/latest contains a valid PrestaShop release, exiting.
A file may be missing, or the release is stored in a subfolder by mistake.

**Comment by khouloudbelguith** [comment]
@centoasa, in my case, I tested this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 & it is OK.
The shop well upgraded from PS1.7.5.2 to the new version PS1.7.6.1 following these steps:

- PS1.7.5.2 installed
- Install the autoupgrade module
- Create a release from the PR
- Put it in the folder admin / autoupgrade / download
- in the configuration page of the module select "local archive" as a channel
- Specify the version to which we are upgrading (example: 1.7.6.1)

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith 
maybe my error was because I've specified the version to which I'm upgrading to 1.7.6.0?
p.s.: the autoupgrade module you mean the 1click module?

**Comment by khouloudbelguith** [comment]
@centoasa, it could be or a problem in the zip file.
Yes, it is the 1-click upgrade module.

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith can you send me your zip release?

**Comment by centoasa** [comment]
tried again and again and gain, with the same error. when 1click being update database same error appear and stuck the sever: 

> @centoasa, in my case, I tested this PR: #14620 & it is OK.
> The shop well upgraded from PS1.7.5.2 to the new version PS1.7.6.1 following these steps:
> 
> * PS1.7.5.2 installed
> * Install the autoupgrade module
> * Create a release from the PR
> * Put it in the folder admin / autoupgrade / download
> * in the configuration page of the module select "local archive" as a channel
> * Specify the version to which we are upgrading (example: 1.7.6.1)
> 
> Thanks!

follow as you, tried again and again and gain, with the same error. when 1click being update database same error appear and stuck the sever:  [INTERNAL] /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php line 87 - require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/prod/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear')
@khouloudbelguith have you used php 7.2.20?

**Comment by khouloudbelguith** [comment]
@centoasa, no, I used PHP7.0.33

**Comment by centoasa** [comment]
@khouloudbelguith Finally, the light!
Solution was the php 7.1.30 (my debian installation 9.9 has deprecated the 7.0.33)
So, Prestashop 1.7.6 and php 7.2.20 they don't get along very well :-)

**Comment by khouloudbelguith** [comment]
@centoasa, I tried with PHP version: 7.2.13 & it is OK.
I attached a screen record
https://drive.google.com/file/d/1cjlUJv51arw5-raMmmCo8ZPBltBHa_eo/view
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by centoasa** [comment]
Now I've changed php to 7.2.20 (the last my plesk vps have onboard) and seems alla works well. We need to find out why the auto upgrade did not work with 7.2.20.

**Comment by ghost** [comment]
This issue is still happening.
