### ISSUE TITLE
 1-Click Upgrade v4.9.0

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#14583]
**Describe the bug**
1-Click Upgrade v4.9.0 doen't showing latest release PrestaShop 1.7.6 stable to upgrade 

**Screenshots**
![1](https://user-images.githubusercontent.com/40850057/61022721-bcebd380-a3c4-11e9-82dc-ada8fe125f2b.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by matks** [comment]
Hi @dineshbadrukhiya there's a small delay between the 1.7.6.0 release and its availability in the autoupgrade 😉

The delay is usually of 24 hours

**Comment by dineshbadrukhiya** [comment]
> Hi @dineshbadrukhiya there's a small delay between the 1.7.6.0 release and its availability in the autoupgrade 😉
> 
> The delay is usually of 24 hours

Okay.  @matks 
"PrestaShop 1.7.6 is also available through the 1-Click Upgrade module." This is mentioned in the [http://build.prestashop.com/news/prestashop-1-7-6-0-available/](url) blog, that's why I have just checked it.

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

You can now upgrade to 1.7.6 with the module.
![image](https://user-images.githubusercontent.com/16067358/61044362-65ebfb80-a3d0-11e9-9217-73578be7422b.png)

Thanks!
