### ISSUE TITLE
Email Notifications not working for customers and orders in Prestashop 1.7.5.2

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14582]
hi khouloudbelguith
I am going through an issue and tried too many solutions available over the internet and the forums but nothing is working. When ever order is created, email alters to customer and admin do not works. rather its gives 500 internal error. (http://banobazaar.com/en/module/ps_cashondelivery/validation) when I disable the email option, order works fine but email notification don't.  Test email works fine on the settings applied in Advanced parameters/Email and received as well. The same issues comes while creating customer or updated an order status.

I am hosting @Go Daddy 
domain name: banobazaar.com 
email: order@banobazaar.com
PS Version : 1.7.5.2
I am only using cash on delivery 

Need urgent support please. 

thanks
Naeem

**Comment by khouloudbelguith** [comment]
Hi @banobazaar,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@banobazaar, as reported here: https://github.com/PrestaShop/PrestaShop/issues/13001#issuecomment-510252412
This issue is occurred due to php-intl extension.
Could you please try to install it, it is required.
Thanks to check and feedback.

**Comment by banobazaar** [comment]
thank you khouloudbelguith for your details response.

I have re0installed PS from scratches and started debugging every step ...here debug means which  configuration settings is effecting the process). I think its cash on delivery module which is not settled properly …. give me some time. I will let you know about same soon.

**Comment by khouloudbelguith** [comment]
@banobazaar, thanks!

Waiting for your feedback.

**Comment by banobazaar** [comment]
khouloudbelguith my name is Naeem :)

Can  you share step by step guideline (if available) for cash on delivery setup.  I dont want risk all thechanges i have made from last three hours.

**Comment by khouloudbelguith** [comment]
@banobazaar, This module?
![image](https://user-images.githubusercontent.com/16067358/61065388-6e0d6080-a3fb-11e9-874a-cee61c5e0b4a.png)
Thanks!

**Comment by banobazaar** [comment]
yes this one …. do we have step by step guide lines available

**Comment by khouloudbelguith** [comment]
@banobazaar, you just need to click on the "install" button & it will be installed on your shop.
Thanks!

**Comment by banobazaar** [comment]
ok let me chk.
is there any shipment/carrier/else settings associated with COD?

**Comment by banobazaar** [comment]
wow its worked...………
I think your its was some installation issue previously....
new installations worked fine...………..

one is for sure.... khouloudbelguith you are pure genius ….
thank you so much

**Comment by khouloudbelguith** [comment]
@banobazaar, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
