### ISSUE TITLE
Wording seems to be off translation

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#14589]
**Describe the bug**
Currently, there are a few wordings in the back office that are not available in the Crowdin translation files. It means that translations are missing in some parts. It seems that the "Browse" button is related to the Symfony migration. See screenshots.

**To Reproduce**
1. Go to the Categories, Import, Modules and Theme pages
2. Change the back office language for a non-English
3. See missing translations

**Screenshots**
![Capture d’écran 2019-07-11 à 11 27 58](https://user-images.githubusercontent.com/32565890/61042351-58d10b80-a3d4-11e9-9e52-69b06183773b.jpg)
![Capture d’écran 2019-07-10 à 16 17 06](https://user-images.githubusercontent.com/32565890/61042356-5a9acf00-a3d4-11e9-9ece-a17f0fb9a2b0.jpg)
<img width="792" alt="Capture d’écran 2019-07-10 à 16 16 35" src="https://user-images.githubusercontent.com/32565890/61042373-69818180-a3d4-11e9-8d05-3a3a4fa117cd.png">

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

I have the same issue with PS1.7.6.0.
In the PS1.7.5.2
1. The category page is OK => it is not migrated to Symfony.
2. The Module Manager page => same issue with PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/61043444-320fd680-a3ce-11e9-94f3-f8302443fe74.png)
3. The import page => NOKwith PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/61043521-5e2b5780-a3ce-11e9-92c2-0d50956b9874.png)

4. The Theme & Logo page => With PS1.7.5.2 => OK => the page is not migrated to Symfony.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14613
