### ISSUE TITLE
Error upgrading to 1.7.6 with php 5.6

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#14591]
Upgrading from 1.6.0 to 1.7.6 (php 5.6):
**PHP Fatal error: Call to a member function get() on null in /var/www/html/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php on line 55**

Sorry, I did not have time to try it in a fresh prestashop.
I was able to update up to 1.7.5.2, but not up to 1.7.6.

1. From old PrestaShop version (1.6.0.x by example), with php 5.6
2. Do manual upgrade https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#manual-upgrade-process-details
4. See error above

**Additional information**
PrestaShop version: 1.7.6
PHP version: 5.6
MySQL : 5.5

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by khouloudbelguith** [comment]
@davidglezz, could you please provide me the exact steps (step by step) that you followed to make the manual upgrade to PS1.7.6.0.

Thanks!

**Comment by davidglezz** [comment]
Steps to reproduce
```
docker network create prestashop-test-net
docker run -ti --name prestashop-test-mysql --network prestashop-test-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
#docker run -ti --name prestashop-test --network prestashop-test-net -e DB_SERVER=prestashop-test-mysql -p 8888:80 -d prestashop/prestashop:1.6-5.6-apache
docker run -ti --name prestashop-test --network prestashop-test-net -e DB_SERVER=prestashop-test-mysql -p 8888:80 -d prestashop/prestashop:1.5-5.6-apache

# Install http://localhost:8888/install/index.php

docker exec -it prestashop-test bash

# Update prestashop : script https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

mkdir /prestashop-upgrade
wget -q -O /prestashop-upgrade/prestashop-upgrade.zip https://github.com/PrestaShop/PrestaShop/releases/download/1.7.6.0/prestashop_1.7.6.0.zip
unzip -qo /prestashop-upgrade/prestashop-upgrade.zip -d /prestashop-upgrade && unzip -qo /prestashop-upgrade/prestashop.zip -d /prestashop-upgrade
rm /prestashop-upgrade/prestashop*.zip /prestashop-upgrade/Install_PrestaShop.html
cp -npr /prestashop-upgrade/img/* /var/www/html/img
cp -npr /prestashop-upgrade/override/* /var/www/html/override
rm -rf /prestashop-upgrade/img /prestashop-upgrade/override
rm -rf /var/www/html/vendor /var/www/html/var/cache/*
cp -Rf /prestashop-upgrade/* /var/www/html
chown -R www-data:www-data /var/www/html
chmod -R 777 /var/www/html/var
chmod -R 777 /var/www/html/img
chmod -R 777 /var/www/html/modules

php -d memory_limit=2048M /var/www/html/install/upgrade/upgrade.php

```

PHP Fatal error:  Call to a member function get() on null in /var/www/html/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php on line 55

**Comment by Quetzacoalt91** [comment]
I removed the Autoupgrade label as the module is not concerned by this issue. We talk about a manual upgrade.

**Comment by Quetzacoalt91** [comment]
As we reproduce the issue, we could find easily find the root cause. Here is a fix for that: https://github.com/PrestaShop/PrestaShop/pull/14620

**Comment by jgradeckimaryville** [comment]
I've tested this fix trying to update 1.7.2.4 to 1.7.6

Downloaded the latest ZIP
updated the upgrade.php according to 14620
ran the 1-step upgrade using local directory as source option

same exact error.

I'm using PHP 5.6

**Comment by xsbr** [comment]
I'm using PHP 7.1.27 and did upgrade using 1-Click Upgrade module from 1.7.5.1 -> 1.7.6.0 - same error on line 55

**Comment by khouloudbelguith** [comment]
Hi @jgradeckimaryville,

The issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620
It is added to PS1.7.6.1 milestone.
Thanks!
