### ISSUE TITLE
Invoice number doesn't roll back when an order is cancelled

### ISSUE THREAD

**Issue by Archikawa** [PrestaShop/PrestaShop#14598]
**Describe the bug**
When a sopping cart is cancelled the invoice numer doesn't roll back. This causes legal issues and invoices must be created manually to bypass it

**To Reproduce**
Create an order -> Invoice Nr. 0001
Create a shopping cart. Go checkout. Do all stuff and before payment abort process. Empty cart. leave.
Create an order -> Invoice Nr 0003

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2
Theme: Z.One 2.4.2
Payment: RedSys: v3.0.4
Transportation: Packlink v2.0.0
Overrides attached (folder classes\order)
[Order.php.txt](https://github.com/PrestaShop/PrestaShop/files/3384052/Order.php.txt)
)

**Comment by Archikawa** [comment]
Seen related issues to this topic, when an order is cancelled. I close the issue here and monitor other issues in this area

**Comment by rdy4ever** [comment]
Hi @Archikawa 
I think this is intended behaviour. Once an invoice number is issued, it should not get reused, even if you cancel the order. Legally, you just need to write "CANCELLED" over it (it would've been nice if Prestashop added this kind of watermark automatically for cancelled invoices) and submit both invoices (for ex. INV-0001 and INV-0001 canceled) to your accountant for processing. If Prestashop would've just cancelled the invoice and issued the same number to the next invoice, then you could actually get in some legal trouble, as the customer might've already downloaded the invoice before you cancelled it and in this case there would exist two different invoices (for different orders) with the same number.
What you can do, is configure Prestashop to only issue the invoice in the latest status (like Shipped or Delivered ). This way you could limit the number of times when you actually need to cancel the invoice along with the order.

**Comment by Archikawa** [comment]
Yes @rdy4ever ! I spent some time last night reading and comparing the issues and I totally agree with you. That's why I closed the issue :)
I will try to configure as you say to issue the invoice at a certain status that reflects better the situation and doesn't interere with tests.
Thank you very much!
