### ISSUE TITLE
Notice Brands listing page

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#14594]
Hi,

I just installed à fresh prestashop 1.7.6, add à manufacturer and when i go on brands listing page (aka manufacturer) i have this notice
![manufacturer](https://user-images.githubusercontent.com/552339/61059901-17ebed80-a3fa-11e9-9fb9-50472818c8fe.png)

Thanks for your help

**Comment by khouloudbelguith** [comment]
Hi @azralth,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0 fresh install
I attached a screen record
https://drive.google.com/file/d/1w_740vu-Auzjsy8PMsmAo7v9rq81RZPl/view
Thanks to check & feedback.

**Comment by azralth** [comment]
Hi,

Thanks for your report.

I just found that the jscomposer (Visual composer) module was the problem. In fact, this module make an override from ManufacturerController : 
![jscomposer](https://user-images.githubusercontent.com/552339/61109494-4ebb1580-a485-11e9-9d2c-aeb80f430b78.png)

Just add a test to check if $this-manufacturer was an object and all clear.

Thanks for your help.

**Comment by khouloudbelguith** [comment]
@azralth, thanks for your feedback.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
