### ISSUE TITLE
Button spin up in product page not work

### ISSUE THREAD

**Issue by ldarake** [PrestaShop/PrestaShop#14597]
**Describe the bug**
This bug make when I click the button spin up in product page, if product have a minimum quantity configured.

**To Reproduce**
1. Go to next link 'https://ginetom.es/es/sillas-de-plastico/255-86731-silla-hosteleria-paris.html#/84-color_plastico-burdeos'
2. Click on quantity button spin up

**Screenshots**
![image](https://user-images.githubusercontent.com/41681733/61070485-21cc1b80-a40f-11e9-873c-6532e2dcdb45.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.29

**Comment by khouloudbelguith** [comment]
Hi @ldarake,

I did not manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2 & the default classic theme.
https://drive.google.com/file/d/1ZpmYZE646_ItPgtUOioZWIVGk5Y1tmOG/view
Did you use a custom theme?
Have you tried to contact the theme author about this issue?

Thanks!

**Comment by ldarake** [comment]
Thanks @khouloudbelguith, 

I use default theme with a child to make the eshop.

You can reproduce the issue in this link 'https://ginetom.es/es/sillas-de-plastico/255-86731-silla-hosteleria-paris.html#/84-color_plastico-burdeos'

Best regards

**Comment by khouloudbelguith** [comment]
@ldarake, have you the same issue with the Classic theme?

Thanks!

**Comment by ldarake** [comment]
Hi @khouloudbelguith,

I have trying it a few minutes ago and now work right. The problem is fixed.

Thank you for you support

**Comment by khouloudbelguith** [comment]
@ldarake, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
