### ISSUE TITLE
Disappear fileds

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14600]
How can I reduce optional fields from customer and addresses forms.

**Comment by khouloudbelguith** [comment]
Hi @banobazaar,

About the Options of the customer, you can disable "Ask for birth date" & "Enable partner offers" fields, by navigating to the BO => Shop Parameters => Customer Settings Page.
![image](https://user-images.githubusercontent.com/16067358/61112649-3eef0180-a484-11e9-83ea-aeb359f69e82.png)

About the Options of the Address, you need to navigate to your BO => International => Locations => Tab Countries, edit your country & edit your Address format by removing some fields.
![image](https://user-images.githubusercontent.com/16067358/61112633-35659980-a484-11e9-8be8-3bc63060fc3d.png)

I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by banobazaar** [comment]
great thanks @khouloudbelguith
