### ISSUE TITLE
Different data in 'ps_currency' table when upgrading to PS 1.7.6

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#14608]
**Describe the bug**
Different data in 'ps_currency' table when upgrading to PS 1.7.6.
- different `precision`
- `name` is not set
- `numeric_iso_code` is not set

**To Reproduce**
Scenary 1
1. Install PS 1.7.6
2. Check table `ps_currency`

![image](https://user-images.githubusercontent.com/15104724/61116470-ccd2e880-a494-11e9-9eb9-f0fa3621f2a6.png)

Scenary 2
1. Install PS 1.7.5.2
2. Upgrade to PS 1.7.6
3. Check table `ps_currency`

![image](https://user-images.githubusercontent.com/15104724/61116447-c04e9000-a494-11e9-88da-143f241a82f0.png)

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
I have the same issue with the `ps_currency` table.
Fresh installation PS1.7.6.0
1. The name is empty
![image](https://user-images.githubusercontent.com/16067358/61118032-c726d400-a48f-11e9-8c60-02afb76114a6.png)

2. After upgrade from PS1.7.5.2 to PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/61118110-f5a4af00-a48f-11e9-922e-998324a71a1e.png)

We have different `numeric_iso_code`, `precision`.

In the PS1.7.5.2, table ps_currency is different
![image](https://user-images.githubusercontent.com/16067358/61118535-d65a5180-a490-11e9-9d7f-5a059c4a18ef.png)

Ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by jcpaybox** [comment]
Hi, reproduced the bug when passing from 1.7.5.1 to 1.7.6.0.
This is breaking the Paybox/e-transactions payment module which uses the numeric iso code.

**Comment by idnovate** [comment]
> Hi, reproduced the bug when passing from 1.7.5.1 to 1.7.6.0.
> This is breaking the Paybox/e-transactions payment module which uses the numeric iso code.

And many others payment modules :worried:

**Comment by demperador** [comment]
Hello! I have had the exact same issue after upgrading from 1.7.5.2 to 1.7.6.0. In fact, we use a module developed by @idnovate and now orders do not update their status. Is there any solution at least by updating the field values numeric_iso_code to 978 and precision to 2 instead of 0 and 6 respectively? Thanks

**Comment by idnovate** [comment]
@demperador Which module?

**Comment by demperador** [comment]
@idnovate 
> @demperador Which module?

Pago con tarjeta Redsys 
v3.6.8 - de idnovate
When a payment is made, Redsys accepts the payment but I receive the following error: Error (-1 Server returned HTTP response code: 500 for URL: http://centrobell.com/index.php?fc=module&module=redsys&controller=ipn).

**Comment by idnovate** [comment]
@demperador Please contact us at https://addons.prestashop.com/es/contacte-con-nosotros?id_product=6492 to fix the problem meanwhile

**Comment by flyman30** [comment]
> > Hi, reproduced the bug when passing from 1.7.5.1 to 1.7.6.0.
> > This is breaking the Paybox/e-transactions payment module which uses the numeric iso code.
> 
> And many others payment modules 😟

After correction of the table ps_currency the data is well transmitted to the bank (module E-transaction) but the return of the bank accepted or not is not taken into account by PrestaShop after the update of 1.7.5.2 -> 1.7 .6.0
LOG :
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/vhosts/****/httpdocs/classes/Tools.php:801\nStack trace:\n#0 /var/www/vhosts/pierre-sempe.com/httpdocs/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 /var/www/vhosts/*****/httpdocs/classes/PaymentModule.php(421): ToolsCore::displayPrice(9.6, Object(Currency), false)\n#2 /var/www/vhosts/****/httpdocs/modules/etransactions/etransactions.php(925): PaymentModuleCore->validateOrder(1190, '2', 17.1, 'E-Transactions', 'Le paiement a \\xC3...', Array, NULL, false, '01e083d45ca21d3...')\n#3 /var/www/vhosts/****/httpdocs/modules/etransactions/classes/ETransactionsController.php(241): ETransactions->onMixedIPNSuccess(Object(Cart), Array)\n#4 /var/www/vhosts/****/httpdocs/modules/etransactions/index.php(69): ETransactionsController->ipnAction()\n#5 {main}\n thrown in /var/www/vhosts/****/httpdocs/classes/Tools.php on line 801\n'
--

**Comment by ArteInfoRM** [comment]
I had the same problem with two migrations from 1.7.5.2 to 1.7.6.0.
![Screenshot_9](https://user-images.githubusercontent.com/41371761/61646080-95401980-aca8-11e9-9e9c-96fc3b2dbd6f.jpg)

**Comment by flyman30** [comment]
https://www.prestashop.com/forums/topic/997100-validation-commande-impossible-avec-e-transaction-paybox/

**Comment by idnovate** [comment]
> I had the same problem with two migrations from 1.7.5.2 to 1.7.6.0.
> ![Screenshot_9](https://user-images.githubusercontent.com/41371761/61646080-95401980-aca8-11e9-9e9c-96fc3b2dbd6f.jpg)

I think this is not related. Have you tried in a fresh PS 1.7.6.0 without the currency problem? Probably it will happen the same ;)

**Comment by idnovate** [comment]
> https://www.prestashop.com/forums/topic/997100-validation-commande-impossible-avec-e-transaction-paybox/

I think this is not related. Have you tried in a fresh PS 1.7.6.0 without the currency problem? Probably it will happen the same ;)

**Comment by flyman30** [comment]
No I did not, my current concern is that our customers can order and pay for their purchases on the shop of prod ..

**Comment by jcpaybox** [comment]
Hi,

We are currently investigating  an issue during order validation, which seems to be your problem (Prestashop's order validation is triggered by our plugins when Instant Payment Notification is received).

somehow i believe it is related to the currency issue, probably a bug in prestashop. for information, reverting to 1.7.5 seems to correct the problem.

regards,

Paybox by Verifone

**Comment by idnovate** [comment]
**Test it in a fresh PS 1.7.6.0 where the current currency bug is not present**. It should appear the same error.

**Comment by flyman30** [comment]
374/5000
So as you ask I made a new installation of Prestashop 1.7.6.0 download to do this and we have exactly the same problem validation by the bank is OK but the Prestashop page displays "waiting for validation" it turns about 10 loops and there is no payment validation in Prestashop 1.7.6.0 administration orders

**Comment by khouloudbelguith** [comment]
@flyman30, so after fresh installation PS.1.7.6.0, you create a new order => proceeded to checkout with the bank payment => in the BO => Order details page => there is no status displayed for these order?

Thanks!

**Comment by idnovate** [comment]
> 374/5000
> So as you ask I made a new installation of Prestashop 1.7.6.0 download to do this and we have exactly the same problem validation by the bank is OK but the Prestashop page displays "waiting for validation" it turns about 10 loops and there is no payment validation in Prestashop 1.7.6.0 administration orders

So as I said ;) **This is a module bug not related with current currency issue**

**Comment by flyman30** [comment]
> @flyman30, so after fresh installation PS.1.7.6.0, you create a new order => proceeded to checkout with the bank payment => in the BO => Order details page => there is no status displayed for these order?
> 
> Thanks!

Yes your right

**Comment by khouloudbelguith** [comment]
@flyman30, what is the exact payment module did you use?

Thanks!

**Comment by flyman30** [comment]
E-transaction V3.0.12
but
cmcicpaiement
Sogenactif 2.0
clicandpay
Are impacted too

**Comment by khouloudbelguith** [comment]
@flyman30, did you tried to contact the module's authors about that issue?

Thanks!

**Comment by flyman30** [comment]
Yes of course !
That's their answer:
We have just received the PHP logs from a client who is having the same problem.
There are actually loops at the time of validation of the payment.
One of the new parameters of Prestashop must act on the **validateorder**.

We invite you to get closer to Prestashop support.
We lack elements at our level to be able to bring you a solution.

Regards,

**Comment by idnovate** [comment]
@flyman30 are you using `E-transaction` module developed by PrestaShop?

**Comment by marionf** [comment]
I close this issue as the original subject "Different data in 'ps_currency' table when upgrading to PS 1.7.6" has been fixed by #14664 
It seems there is an issue about payments modules here: #14648 Please follow & commment on this issue

**Comment by flyman30** [comment]
J'utilise le module E-transaction 3.0.12 fournit par ma banque depuis que j'ai une boutique Prestashop (1.7.0.1) sans aucun soucis.
Ce n'est pas le module qui est en cause puisque TOUS les modules de paiement bancaire semble impactés !

- E-Transaction
- cmcicpaiement
- Sogenactif 2.0
- clicandpay
etc...


Il faut comprendre pourquoi cette version PrestaShop présente un bug majeur dans la réception des validations bancaire

exemple : 
https://www.prestashop.com/forums/topic/997100-validation-commande-impossible-avec-e-transaction-paybox/
https://www.prestashop.com/forums/topic/997001-suite-mise-%C3%A0-jour-1752-1760-les-retours-bancaire-ne-se-font-pas/?tab=comments#comment-3138391

**Comment by debuss** [comment]
> > > Hi, reproduced the bug when passing from 1.7.5.1 to 1.7.6.0.
> > > This is breaking the Paybox/e-transactions payment module which uses the numeric iso code.
> > 
> > 
> > And many others payment modules worried
> 
> ## After correction of the table ps_currency the data is well transmitted to the bank (module E-transaction) but the return of the bank accepted or not is not taken into account by PrestaShop after the update of 1.7.5.2 -> 1.7 .6.0
> LOG :
> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/vhosts/****/httpdocs/classes/Tools.php:801\nStack trace:\n#0 /var/www/vhosts/pierre-sempe.com/httpdocs/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 /var/www/vhosts/*****/httpdocs/classes/PaymentModule.php(421): ToolsCore::displayPrice(9.6, Object(Currency), false)\n#2 /var/www/vhosts/****/httpdocs/modules/etransactions/etransactions.php(925): PaymentModuleCore->validateOrder(1190, '2', 17.1, 'E-Transactions', 'Le paiement a \xC3...', Array, NULL, false, '01e083d45ca21d3...')\n#3 /var/www/vhosts/****/httpdocs/modules/etransactions/classes/ETransactionsController.php(241): ETransactions->onMixedIPNSuccess(Object(Cart), Array)\n#4 /var/www/vhosts/****/httpdocs/modules/etransactions/index.php(69): ETransactionsController->ipnAction()\n#5 {main}\n thrown in /var/www/vhosts/****/httpdocs/classes/Tools.php on line 801\n'

Banque return is made through Ajax, therefore the Context class is not instantiated correctly.

To avoid the error **PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null **, your bank module needs to instantiate the controller and language in Context.
Example :
```php
Context::getContext()->language = new Language(Configuration::get('PS_LANG_DEFAULT'));
Context::getContext()->controller = new FrontController();
Context::getContext()->controller->init()
```
With that, it should be okay and ToolsCore::displayPrice() method should be not throw exception.

**Comment by Fernandama96** [comment]
> Hi @idnovate,
> 
> Thanks for your report.
> I have the same issue with the `ps_currency` table.
> Fresh installation PS1.7.6.0
> 
> 1. The name is empty
>    ![image](https://user-images.githubusercontent.com/16067358/61118032-c726d400-a48f-11e9-8c60-02afb76114a6.png)
> 2. After upgrade from PS1.7.5.2 to PS1.7.6.0
>    ![image](https://user-images.githubusercontent.com/16067358/61118110-f5a4af00-a48f-11e9-922e-998324a71a1e.png)
> 
> We have different `numeric_iso_code`, `precision`.
> 
> In the PS1.7.5.2, table ps_currency is different
> ![image](https://user-images.githubusercontent.com/16067358/61118535-d65a5180-a490-11e9-9d7f-5a059c4a18ef.png)
> 
> Ping @PrestaShop/prestashop-core-developers what do you think?
> Thanks!

Hi! i have the same problem, but i use USD, the iso code will be 978 too?

**Comment by Fernandama96** [comment]
Hi! i changed the precision, and now works perfectly! Thank you very much!

**Comment by idnovate** [comment]
> > Hi @idnovate,
> > Thanks for your report.
> > I have the same issue with the `ps_currency` table.
> > Fresh installation PS1.7.6.0
> > 
> > 1. The name is empty
> >    ![image](https://user-images.githubusercontent.com/16067358/61118032-c726d400-a48f-11e9-8c60-02afb76114a6.png)
> > 2. After upgrade from PS1.7.5.2 to PS1.7.6.0
> >    ![image](https://user-images.githubusercontent.com/16067358/61118110-f5a4af00-a48f-11e9-922e-998324a71a1e.png)
> > 
> > We have different `numeric_iso_code`, `precision`.
> > In the PS1.7.5.2, table ps_currency is different
> > ![image](https://user-images.githubusercontent.com/16067358/61118535-d65a5180-a490-11e9-9d7f-5a059c4a18ef.png)
> > Ping @PrestaShop/prestashop-core-developers what do you think?
> > Thanks!
> 
> Hi! i have the same problem, but i use USD, the iso code will be 978 too?

Iso code for USD is 840

**Comment by HartLarsson** [comment]
even with all things Ok in the table:
![image](https://user-images.githubusercontent.com/16102074/92723634-a2670e80-f369-11ea-9a70-8b25213b2f15.png)

we continue to have round problems when there are discounts:

![image](https://user-images.githubusercontent.com/16102074/92723724-c88cae80-f369-11ea-80c7-35df4ac99b58.png)

a difference not on decimals but consistent like in this case.
