### ISSUE TITLE
mailalerts 3.7.0 module doesn't send order notification for ver. PrestaShop 1.7.4.4

### ISSUE THREAD

**Issue by kibiribi** [PrestaShop/PrestaShop#14623]
**Describe the bug**
MailAlerts v3.7.0 installed on PrestaShop ver. 1.7.4.4
All notifications are enabled - screen - https://www.screencast.com/t/P2s8KvjH
There are no errors, warning, 500 erros. Site works without problem. 
When order was completed:
- Customer gets PrestaShop notifications 
- 3 Backend admins (admin email = store domain)  didn't get any order confirmation message
SMTP, PHP works well - all tests were done in Presta backend. 
Test email from site - done - all ok. 
More info on the PrestaForum  - https://www.prestashop.com/forums/topic/996101-mail-allerts-installed-but-order-confirm-didnt-send/

**To Reproduce**
1. Download module - https://github.com/PrestaShop/mailalerts/archive/v3.7.0.zip 
2. Unzip and rename folder from mailalerts-3.7.0.zip to mailalerts.zip
3. Go to Module installation and select ZIP
4. Goto Module settings after installation.  To add 3 emails from this store. Doman of store = domain of email. 
5. To add product to Cart and start checkout. 
6. Registered user got a PrestaShop email with order notifications. Backend Admins didn't any email confirm.
7. As a result - there are no error messages, warnings, Mail queue is empty. 

**Screenshots**
All screenshots are attached in the PrestaShop forum post https://www.prestashop.com/forums/topic/996101-mail-allerts-installed-but-order-confirm-didnt-send/
screen1 - https://www.screencast.com/t/pNSJmKR6ut
screen2 - https://www.screencast.com/t/gBAvgZhD
screen3 - https://www.screencast.com/t/xg1m13qWoB9
screen4 - https://www.screencast.com/t/yXXHOpNl

**Additional information**
PrestaShop version: 1.7.4.4
PHP version:  7.2.20
MailAlerts: 3.70
Dedicated server:  CentOS 6.10 (Final)
MySQL:  5.1.73-8.el6_8

I'm ready to show you issue via remote connection (TeamViewer or VNC)

**Comment by kibiribi** [comment]
The problem was that I have RU-lang PrestaShop but MailAlerts module was in English. 

So all settings (backend and server was ok) but this module couldn't find Prestashop backend default language (in my case it was Russian). I've created folder ru, and copied English files to this folder and translated to Russian. Order notifications were run without problem 

**### This is real BUG from the side of PrestaShop Module.** 

Module didn't give me warning, messages about  "No current language was found" or warning on Module page settings about missing language. 
![image](https://user-images.githubusercontent.com/15987425/61173660-f8da9080-a59e-11e9-90d5-7e2160d9a15e.png)

**Comment by khouloudbelguith** [comment]
Hi @kibiribi,

I followed these steps
1. install PS1.7.6.0
2. Import the package Russian
3. Install the module mailalert v3.7.0
4. Go to the FO => Select the Русский language
5. Add some product to the cart => complete order

=> I have a New order mail
![image](https://user-images.githubusercontent.com/16067358/61275407-cea6ef80-a7a5-11e9-848a-df6563b7753d.png)

It is just received in the English language.

Thanks to check & feedback.

**Comment by mariem-abid** [comment]
Hi @kibiribi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
