### ISSUE TITLE
Prestashop update error 1.7.5.2 to 1.7.6

### ISSUE THREAD

**Issue by Attiro76** [PrestaShop/PrestaShop#14625]
Hello everyone, I got an error while trying to 1-Click update my prestashop:

07:41:26 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "prestashop:schema:update-without-foreign","message" => "Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it."]In AbstractPlatform.php line 423: Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--][DEV] ajax request : rollback

 
I am writing here with the hope that someone can help me with this issue :)

Best regards,

Attila

**Comment by mariem-abid** [comment]
Hi @Attiro76,

What is the exact version of the 1-click upgrade module that used?

Thanks!

**Comment by mariem-abid** [comment]
Hi @Attiro76,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
