### ISSUE TITLE
Feature request: addWebP image format 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#14628]
WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.

WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

https://developers.google.com/speed/webp/

**Comment by mariem-abid** [comment]
Hi,
@Peter4661, Thank you for your report.
@colinegin , @sarahdib , what do you think?

**Comment by ghost** [comment]
Thanks for the feedback @Peter4661!

@PrestaShop/prestashop-core-developers, what do you think about it? Is it something you have already discussed/considered in the team?

**Comment by PierreRambaud** [comment]
Duplicate of #10356

We all agreed webp must be supported. Maybe for 1.7.7, or if you're able to help us and create a pull request :)
