### ISSUE TITLE
Spam registrations continue on Prestashop 1.7.6

### ISSUE THREAD

**Issue by indusone** [PrestaShop/PrestaShop#14627]
Hi,,
There was a patch before which had slowed down the spam, though it wasnt 100% gone. Now it seems to have discovered new vulnerabilities and spam is happening in a big way.

**Comment by matks** [comment]
Hi @indusone thanks for the feedback. Can you tell us more about it ? Is that the same spam strategy like before: it creates a lot of fake customer accounts, with firstnames and/ore lastnames are URLs ?

**Comment by indusone** [comment]
Not sure about the URL's , but for me its the same as before, with a lot of junk customer first names and last names like these 

![image](https://user-images.githubusercontent.com/3143014/61170563-8d85c400-a588-11e9-8e90-ad5e69c26edf.png)

**Comment by Matt75** [comment]
It’s not the same behavior, they use allowed pattern so we can’t block them with standard validation.
You should install a captcha :
- http://build.prestashop.com/news/fighting-against-spamming-again/
- http://build.prestashop.com/news/fighting-against-spamming/

**Comment by indusone** [comment]
Why not add presta;s own captcha for this? Its a simple solution isnt it?

**Comment by Matt75** [comment]
Because it’s an external service, you have to choose your service provider.

For example Recaptcha : you have to create an account, create an API key and make a configuration to use them with your domain etc...

That’s why it’s optional and provided as PrestaShop Module.

**Comment by indusone** [comment]
ok thanks for quick replies.

**Comment by marksull** [comment]
> Why not add presta;s own captcha for this? Its a simple solution isnt it?

They should have a free module that provides captcha capability because it's an essential requirement these days for Prestashop to be functional. But, it's not in their vested interest to do so because so many captcha modules are sold through addons...

**Comment by indusone** [comment]
I installed eicaptcha solution, and it works good. Thanks.

**Comment by Matt75** [comment]
@marksull there are free community modules and paid modules.

No need to provide a native module as you have already a lot of choice available for this.

Core team have to save time to focus on PrestaShop migration and bug fixes.
PrestaShop backlog is already big ;)

Thanks for understanding ;)

**Comment by indusone** [comment]
I hope the spammers also order a thing or 2 from the store, then i wont mind them too much :)

**Comment by mariem-abid** [comment]
Hi @indusone,

Thanks for your feedback.
I close the ticket, feel free to open a new one when needed.

**Comment by simulbeni** [comment]
Hi

I can still see the issue remains there and fake customers are being created. 1.7.6.1 and .1.7.6.2.

Please give some permanent solution for this.

Thanks

**Comment by marksull** [comment]
@beniwal you have to by a module with captcha

**Comment by matks** [comment]
> Hi
> 
> I can still see the issue remains there and fake customers are being created. 1.7.6.1 and .1.7.6.2.
> 
> Please give some permanent solution for this.
> 
> Thanks

As @marksull said 😄 the permanent solution is to use a captcha module. You'll find more informations [here](https://build.prestashop.com/news/fighting-against-spamming-again/).
