### ISSUE TITLE
URL rewrite rules invalid after install in Czech language

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14629]
**Whats wrong**
Authentication and sitemap rewrite rules are invalid in Czech language.
They contain spaces and special characters. Cannot be saved when opened.

**Solution**
Change "authentication " to "prihlaseni".
Change "sitemap" to "mapa-stranek".

**Additional information**
PrestaShop version: 1.7.6 final

**Comment by mariem-abid** [comment]
Hi @Hlavtox,
I manage to reproduce the issue with PS:1.7.6.0
I attached a video record
https://drive.google.com/file/d/1yg60GNIpxy1yyLBu3-aQ2iUyXQ5hjMmB/view
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by sarahdib** [comment]
Hello,

This problem is related to the data in Czech language for sitemap and authentication. In Traffic & SEO some friendly url in Czech have accent and space.

**Comment by Hlavtox** [comment]
@sarahdib Just change the install values to what I proposed in the first message and fixed ;-)

**Comment by Hlavtox** [comment]
Fixed in crowdin
