### ISSUE TITLE
Emails files are not completely translated on prestashop 1.7.6

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14633]
Hi
I've upgraded from 1.7.5.2, all is ok except the email files
I've seen that the emails files are not completely translated
I've already updated the translations from back-office
it happens for many translations like italian, spanish ...

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/61175341-e156d400-a5ad-11e9-8a80-d298ad303f33.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by mariem-abid** [comment]
Hi @maofree,

Do you have made the update translations before or after the upgrade?

**Comment by Maofree** [comment]
After

**Comment by khouloudbelguith** [comment]
@maofree, thanks for your feedback.
I have the same issue after upgrade from PS1.7.5 to PS1.7.6.0 using the 1-click upgrade v4.9.0.

In fact, in the BO => International => translation => 
- Type of translation => Email translations
- Select the type of email content => Body
- Select your theme => Core
- Select your language => Italian

When we click for example on "Core emails" link => order_conf => some strings are not translated

I attached a screen record
https://drive.google.com/file/d/1MTDc5LURUxc1Z7axVKdlahjfPSioRJ3Z/view

PS: I tried to edit the "Edit HTML" version => ok 
ping @jolelievre what do you think?

Thanks!

**Comment by jameshellfire** [comment]
A temporary baypass is: change e-mail templates to classic.
In new added menu.:
![image](https://user-images.githubusercontent.com/16944636/61294127-6a9c1f80-a7d5-11e9-949e-c7f1fb909ca4.png)

**Comment by khouloudbelguith** [comment]
Hi,

As discussed with @jolelievre, this is a bug & it is a regression.
In fact, In the PS1.7.5.2 is different from PS1.7.6 but emails are well translated.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by jolelievre** [comment]
Indeed some translation keys were missing in the catalog, so they couldn't be translated in crowdin. We fixed this issue so the missing keys will be published in crowdin as soon as this PR will be merged.

**Comment by md-brnursery** [comment]
Any update on this, when I have installed the update 1.7.6, the shop name has been replaced with "My Shop"?

**Comment by liviu-v** [comment]
No fix for this issue yet?!?

**Comment by khouloudbelguith** [comment]
Hi @liviu-v,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14719 to fix the issue & it should be reviewed by our developers.

Thanks!

**Comment by liviu-v** [comment]
@khouloudbelguith Thank You very much for your fast reply! Pardon me but I am new in here, what exactlly does it mean, like aproximativlly when this error will be resolve by your delevopers? and I will find the fix for this issue in the PR #14719 or here in this issue: #14633, now is in progress correct?

**Comment by khouloudbelguith** [comment]
@liviu-v, it should be fixed in a few days.
Yes, this is the fix https://github.com/PrestaShop/PrestaShop/pull/14719/files, it will be added in the next version PS1.7.6.1.
Thanks!
