### ISSUE TITLE
Wrong tax exclusive prices update 1.7.5.2 to 1.7.6.0

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14630]
Price ex vat column in admin, dutch language with € wrong display.  From 1.7.5.1 to 1.7.6.0.
issue invoice product prices excl. vat / tax

![image](https://user-images.githubusercontent.com/2944981/61172291-82c83080-a582-11e9-9fa2-abd59acec683.png)

![Schermafbeelding 2019-07-13 om 15 26 44](https://user-images.githubusercontent.com/2944981/61172300-a4291c80-a582-11e9-9c30-85a14ea1d1d9.png)

For example 950,413223 instead of 950,41
Where? Back-end Product Catalog and on the Invoice PDF

**Comment by ghost** [comment]
Also in front-end wrong tax excl. display.
![Schermafbeelding 2019-07-15 om 09 14 05](https://user-images.githubusercontent.com/2944981/61200187-e9636080-a6e0-11e9-8d4c-4297916daaa8.png)

**Comment by Maofree** [comment]
hi
also in tax incl.
look at my post

bye

**Comment by marionf** [comment]
Hello @sdwebdesign 
Thanks for reporting this issue. It is a duplicate of #14640, please follow this issue.
