### ISSUE TITLE
missing Email Theme tab after update 1.7.5.1 to 1.7.6. 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14631]
No new tab in admin after update 1.7.5.1 to 1.7.6.
 Clean install works fine!

**Comment by mariem-abid** [comment]
Hi @sdwebdesign,

I did not manage to reproduce the issue after the upgrade from PS:1.7.5.1 to PS:1.7.6.0 using the module 1-click upgrade V4.9.0
I attached a screenshot
![AwesomeScreenshot-email-2019-07-15-13-07-19](https://user-images.githubusercontent.com/36841537/61215057-9bab2000-a701-11e9-8453-fa7371be284e.png)

Thanks for check and feedback.

**Comment by mariem-abid** [comment]
Hi @sdwebdesign,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
