### ISSUE TITLE
how can I change color product border

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14635]
please guide me a way so I can change color product border as explain in picture.

in picture there are two products tagged with 1 and 2 (edited in paint brush)
![abc](https://user-images.githubusercontent.com/52763446/61177458-38c96400-a5ef-11e9-8ad4-1298648ab697.png)

i want my product to be displayed with yellow back ground as tagged 2.

**Comment by mariem-abid** [comment]
Hi @banobazaar,

In the theme.css file which is under your project folder/ themes / classic / assets / css / theme.css add  the background-color style.

Thanks for check and feedback.

**Comment by mariem-abid** [comment]
Hi @banobazaar,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
