### ISSUE TITLE
FO>Customer>Personal info requires current password, why?

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14641]
**Describe the bug**
1. Login in FO.
2. Go to your account, personal info.
3. Now, to save the form, even when not chaging the password, it wants the current password.

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with PS:1.7.5.2. and PS:1.7.6.0
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by colinegin** [comment]
I've listed your issue as an improvement and not a bug. In my opinion, this is a good and secure practice to prevent people from changing critical information such as the email address. What do you think @marionf and @Hlavtox ?

**Comment by Hlavtox** [comment]
@colinegin You are right, closing
