### ISSUE TITLE
Broke sending/preview e-mail template  from admin panel

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#14643]
**Describe the bug**
I have some errors in fresh install on updated 1.7.6.x , when I try to send or view email template from admin panel.

**To Reproduce**
1. Go to : admin panel > design > email theme
2. on Email Themes tab click preview icon (on classic or modern version) > click on HTTP or try to send test message.

**Screenshots**
![image](https://user-images.githubusercontent.com/42643563/61188957-e3d92c80-a686-11e9-90d0-fbc4bdf00983.png)

**Additional information**
PrestaShop version: 1.7.6.x - newest
PHP version: 7.3

**Comment by mariem-abid** [comment]
Hi @LocalHeroPro,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by LocalHeroPro** [comment]
PHP7.2 and PHP7.1 the same.

**Comment by khouloudbelguith** [comment]
Hi @LocalHeroPro,


Thanks for your feedback & your report.
I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1_cuzUYMzyh2WByAjRgAKKixaPpyi2OAz/view
Could you please navigate to your BO => International => Translations => "Add / Update a language" => Select the Polish language and click on "Add or update a language button" button.

Thanks to check & feedback.

**Comment by LocalHeroPro** [comment]
Yes, I make that step in first row after installed PS and issue still occur.

**Comment by khouloudbelguith** [comment]
@LocalHeroPro, what is the exact Language/Country did you used during the install of PrestaShop1.7.6?

Thanks!

**Comment by LocalHeroPro** [comment]
PL

**Comment by khouloudbelguith** [comment]
@LocalHeroPro, I tried again but it is OK.
https://drive.google.com/file/d/19dUK22uT-9TliI6RAv581z0Csb3Z28Ow/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!

**Comment by DonGyno** [comment]
Hi,
I had the same problem but I found the cause simply. The problem appears when there are no commands in the database (deletion of test data). When adding an order, the problem does not appear.

Prestashop developers, it would be good to check if the variable is well initialized and it is not null before generating a template!

Thanks

**Comment by khouloudbelguith** [comment]
Hi @DonGyno,

It is Ok after deleting all orders with the module psclean.
https://drive.google.com/file/d/1CvZ1AicPruGiJJa_QS-UCcbwsNN-n3PQ/view

Thanks!
