### ISSUE TITLE
on 1.7.6 rounds errors in the FO and BO for some products

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14640]
Hi
look in the product list from the back-end, you can see many decimals
the same problem happen in the from office when some product are added to the cart
I show you this problem on 3 sites, one is on the clean site with classic theme

I think the problem is not in the theme but in the php files,
{$product.price} gives in some cases too much decimals

in the backoffice I cannot set 279€ (with 22% of tax) I get always 279.000001 after saved

setting 2 like Number of decimals this problem should not be present in the front-office, instead in some php file this number is not taken into account and shows all the decimal numbers

from the module ps_shoppingcart it is possible to know something about this problem

`    public function renderModal(Cart $cart, $id_product, $id_product_attribute)
    {
        $data = (new CartPresenter)->present($cart);
        $product = null;
        foreach ($data['products'] as $p) {
            if ($p['id_product'] == $id_product && $p['id_product_attribute'] == $id_product_attribute) {
                $product = $p;
                break;
            }
        }

        $this->smarty->assign(array(
            'product' => $product,
            'cart' => $data,
            'cart_url' => $this->getCartSummaryURL(),
        ));

        return $this->fetch('module:ps_shoppingcart/modal.tpl');
    }`

I think the problem come from this like
$data = (new CartPresenter)->present($cart);

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/61185982-fee47600-a65f-11e9-8e3d-4932a500ef66.png)
![2](https://user-images.githubusercontent.com/653230/61185983-fee47600-a65f-11e9-8f50-2e155a791f77.png)
![3](https://user-images.githubusercontent.com/653230/61185984-ff7d0c80-a65f-11e9-943e-93bacbae8e77.png)
![4](https://user-images.githubusercontent.com/653230/61185987-00ae3980-a660-11e9-8027-d25e72448441.png)
![5](https://user-images.githubusercontent.com/653230/61185988-00ae3980-a660-11e9-89fa-d4d8fa382572.png)
![6](https://user-images.githubusercontent.com/653230/61185989-0146d000-a660-11e9-98e8-a0de7af2cd38.png)
![7](https://user-images.githubusercontent.com/653230/61186014-6995b180-a660-11e9-89d0-a54cd1fce703.png)
![8](https://user-images.githubusercontent.com/653230/61186015-6a2e4800-a660-11e9-816b-cbf202abcae1.png)
![9](https://user-images.githubusercontent.com/653230/61186016-6ac6de80-a660-11e9-9104-52157435ec7e.png)
![1](https://user-images.githubusercontent.com/653230/61186112-d2315e00-a661-11e9-9146-1163ba72e179.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by Maofree** [comment]
the problem come out from this function that you have changed

Tools::displayPrice()

the problem is from this
return $locale->formatPrice($price, $currencyCode);

I think the problem come from here
Number/Formatter.php

![1](https://user-images.githubusercontent.com/653230/61186327-32290400-a664-11e9-942f-a43813d18449.png)
![2](https://user-images.githubusercontent.com/653230/61186328-32290400-a664-11e9-86d9-d1c1731106d6.png)
![3](https://user-images.githubusercontent.com/653230/61186329-32c19a80-a664-11e9-9ef6-9c91520ba90c.png)

**Comment by matks** [comment]
Thank you for the very accurate report @maofree ! 👍 We're going to investigate this issue.

Can you tell us which countries, currencies and languages you use for these sites ? It would be a great help

**Comment by Maofree** [comment]
Hi
it is not important those selections, it happens for all currencies, languages ..
look at this image (with english and dollar)

![1](https://user-images.githubusercontent.com/653230/61189642-8cd85500-a690-11e9-95d7-8619da45a4a4.png)

the number of decimals should follow the value of price_display_precision

bye

**Comment by ghost** [comment]
Related to #14630

**Comment by Shad-Shinoda** [comment]
I have the same issue with german language and euro currency.
For me, it appears in the cart and product discount table. Didn´t checked the mails yet.
![cart](https://user-images.githubusercontent.com/52961221/61291265-586ab300-a7ce-11e9-80b9-334cbb83a18f.png)

**Comment by Slews** [comment]
The issue occures because the data used to set the maxFractionDigits of the priceSpecification is the precision field of the currency from the database.

**Comment by simplix-fr** [comment]
UPDATE `ps_currency` SET `numeric_iso_code` = '978', `precision` = '2' WHERE `ps_currency`.`id_currency` = 2;

**Comment by ghost** [comment]
GREAT WORK! Works for me changed in ps_currency  (EURO) the column numeric_iso_code (was empty) to 978 and precision to 2. now the prices are fine in front and back. But done this by hand in database table. Adding new currency has the same issue.

**Comment by HartLarsson** [comment]
Italian Store with Euro only 
![image](https://user-images.githubusercontent.com/16102074/92460755-9f80e800-f1c8-11ea-8fe4-3fc8bd3ae085.png)

But when i write the Tax included field with 19,00 euro and save the product when i edit back i see this:

![image](https://user-images.githubusercontent.com/16102074/92460821-b6273f00-f1c8-11ea-8287-758e596da71f.png)


PS 1.7.6.7

**Comment by stephR** [comment]
@HartLarsson same for me with 1.7.6.5 
my data in ps_currency table is like yours but on front-end price_tax_exc shows more than 2 decimals (6 in back-end) and currency is not displayed like with regular price...
