### ISSUE TITLE
back office is too slow to load in PS 1.7X

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14642]
currently back office too slow to load in PS 1.7.5.2.

I am trying since morning but unable to get through.

how can I resolve this issue.

**Comment by mariem-abid** [comment]
Hi @banobazaar,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by banobazaar** [comment]
thanks working now

**Comment by khouloudbelguith** [comment]
@banobazaar, thanks for your feedback.

Feel free to open a new one when needed.

Thanks!
