### ISSUE TITLE
1.7.6 & 1-click upgrade 4.9.0 - FO Error 500 

### ISSUE THREAD

**Issue by mariusherea** [PrestaShop/PrestaShop#14644]
I had PS 1.75.2. I installed the 1-click upgrade 4.9.0 and ran the upgrade to 1.7.6. 
After upgrade, the BO seemed fine but the FO is not working anymore. Error 500. 

 AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: "1.0E+15" cannot be interpreted as a number in /vendor/prestashop/decimal/src/Number.php:466\nStack trace:\n#0  /vendor/prestashop/decimal/src/Number.php(72): PrestaShop\\Decimal\\Number->initFromString('1.0E+15')\n#1 /src/Core/Localization/Number/Formatter.php(149): PrestaShop\\Decimal\\Number->__construct('1.0E+15')\n#2 /src/Core/Localization/Number/Formatter.php(106): PrestaShop\\PrestaShop\\Core\\Localization\\Number\\Formatter->prepareNumber(1.0E+15)\n#3/src/Core/Localization/Locale.php(155): PrestaShop\\PrestaShop\\Core\\Localization\\Number\\Formatter->format(1.0E+15, Object(PrestaShop\\PrestaShop\\Core\\Localization\\Specification\\Price))\n#4/classes/Tools.php(776): PrestaShop\\PrestaShop\\Core\\Localization\\Lo...\n'

At the same time, on another website, I did a clean install of PS 1.7.6 and everything works fine. So... is it a problem with the 1-click upgrade module or with the files it downloads before the upgrade?

**Comment by mariem-abid** [comment]
Hi @mariusherea,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks for check and feedback.

**Comment by mariusherea** [comment]
I have deleted both prod and dev folders in /var/cache.
I did again the upgrade with 1-click upgrade 4.9.0.
Result....

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: "1.0E+15" cannot be interpreted as a number in /home/public/vendor/prestashop/decimal/src/Number.php:466\nStack trace:\n#0 /home/public/vendor/prestashop/decimal/src/Number.php(72): PrestaShop\\Decimal\\Number->initFromString('1.0E+15')\n#1 /home/public/src/Core/Localization/Number/Formatter.php(149): PrestaShop\\Decimal\\Number->__construct('1.0E+15')\n#2 /home/public/src/Core/Localization/Number/Formatter.php(106): PrestaShop\\PrestaShop\\Core\\Localization\\Number\\Formatter->prepareNumber(1.0E+15)\n#3 /home/public/src/Core/Localization/Locale.php(155): PrestaShop\\PrestaShop\\Core\\Localization\\Number\\Formatter->format(1.0E+15, Object(PrestaShop\\PrestaShop\\Core\\Localization\\Specification\\Price))\n#4 /home/public/classes/Tools.php(776): PrestaShop\\PrestaShop\\Core\\Localization\\Lo...\n'

**Comment by mariusherea** [comment]
Btw, all non-prestashop modules and overrides  are disabled

**Comment by mariusherea** [comment]
`

(2/2) LocalizationExceptionInvalid $number parameter: "1.0E+15" cannot be interpreted as a number
--
in Formatter.php line 108
at Formatter->format(1000000000000000.0, object(Price))in Locale.php line 155
at Locale->formatPrice(1000000000000000.0, 'RON')in Tools.php line 776
at ToolsCore::displayPrice(1000000000000000.0, object(Currency))in PriceFormatter.php line 55
at PriceFormatter->format(1000000000000000.0)in CartPresenter.php line 470
at CartPresenter->present(object(Cart))in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 548
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 291
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

`

**Comment by mariusherea** [comment]
(2/2) LocalizationExceptionInvalid $number parameter: "1.0E+15" cannot be interpreted as a number
--
in Formatter.php line 108
at Formatter->format(1000000000000000.0, object(Price))in Locale.php line 155
at Locale->formatPrice(1000000000000000.0, 'RON')in Tools.php line 776
at ToolsCore::displayPrice(1000000000000000.0, object(Currency))in PriceFormatter.php line 55
at PriceFormatter->format(1000000000000000.0)in CartPresenter.php line 470
at CartPresenter->present(object(Cart))in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 548
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 291
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28


(1/2) InvalidArgumentException"1.0E+15" cannot be interpreted as a number
--
in Number.php line 466
at Number->initFromString('1.0E+15')in Number.php line 72
at Number->__construct('1.0E+15')in Formatter.php line 149
at Formatter->prepareNumber(1000000000000000.0)in Formatter.php line 106
at Formatter->format(1000000000000000.0, object(Price))in Locale.php line 155
at Locale->formatPrice(1000000000000000.0, 'RON')in Tools.php line 776
at ToolsCore::displayPrice(1000000000000000.0, object(Currency))in PriceFormatter.php line 55
at PriceFormatter->format(1000000000000000.0)in CartPresenter.php line 470
at CartPresenter->present(object(Cart))in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 548
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 291
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment]
@mariusherea, your issue seems to be related to this https://github.com/PrestaShop/PrestaShop/issues/14608
Could you please check the table `ps_currency` => `precision` column & feedback.

Thanks!

**Comment by mariusherea** [comment]
I found the problem with the help of nice guy on PS forums. In Preferences > Orders, there was a min. amount set to accept an order, 1000000000000000. Once that modified, the error went away.

**Comment by khouloudbelguith** [comment]
@mariusherea, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!
