### ISSUE TITLE
Faceted search bad currency format - thousands separator

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14657]
**Describe the bug**
Price amount in faceted price filter has a different format then the store. It contains comma instead of space as a **THOUSAND SEPARATOR**.

Language: Czech
Currency: Kč (CZK)

Store: 1 000 Kč
Filter: 1,000 Kč

**Screenshots**
![currency](https://user-images.githubusercontent.com/6097524/61214301-e039ba00-a707-11e9-850f-e7f437bffe7d.PNG)

**Note**
Achieved zero decimals by changing precision from 2 to 0 in ps_currency. No files related to this are modified.

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment]
Hi @Hlavtox,

Which country is selected for the installation of your shop?

**Comment by Hlavtox** [comment]
@mariem-abid Czech Republic

**Comment by mariem-abid** [comment]
@Hlavtox, I did not manage to reproduce the issue with PS:1.7.6.0
I attached a video record
https://drive.google.com/file/d/1p8p4etxnYsx6RN9N3MAn8WQPpgc9nYRg/view

Thanks for check and feedback.

**Comment by Hlavtox** [comment]
@mariem-abid I am talking about the thousands separator. Make a product with a price over 1000,00 and you will see the error

**Comment by ghost** [comment]
Hello,
I have a pretty similar issue, I am getting 6 decimals, instead of just 2.

**Comment by ACO-space** [comment]
Hi,
same issue here: 6 decimals instead of 2. I've been digging for hours in the php and js files without finding a way to fix the issue.

**Comment by khouloudbelguith** [comment]
Hi @Adyku, @m3ss3ng3rAC,

This issue occurs after an upgrade from PS1.7.6.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14664 to fix the issue.
Your issue is a duplicate of #14608
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14608

**Comment by Hlavtox** [comment]
@khouloudbelguith This is a different issue, isn't it? I have a fresh install of 1.7.6 final.

**Comment by khouloudbelguith** [comment]
@Hlavtox, could you please check your database => table `ps_currency` & check the precision.

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith It was 0, I set it back to 2 and still the same issue.

This is not about the decimal points. Do you see the thousands separator? I added it to the text description and issue title.

![teka](https://user-images.githubusercontent.com/6097524/61290485-4556e380-a7cc-11e9-961d-5c85c3ad1201.PNG)

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks for your feedback.
Yes, I have the same issue with PS1.7.6.0 & PS1.7.5.2 and the ps_facetedsearch v3.1.0.
![image](https://user-images.githubusercontent.com/16067358/61291734-43d6ec80-a7c7-11e9-85f0-a930c70a5883.png)

It should be like this format
`12 345,67 Kč`

With PS1.7.6.0 & ps_facetedsearch v2.2.1 => OK

![image](https://user-images.githubusercontent.com/16067358/61291892-b051eb80-a7c7-11e9-956e-f8b73b3844e1.png)


I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Fixed for 1.7.6 here: https://github.com/PrestaShop/ps_facetedsearch/pull/115
