### ISSUE TITLE
Faceted search bad product count/message when no products are found

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14658]
**Describe the bug**
Bad product count is shown when no products are found in faceted search.

**Current behavior**
![product count](https://user-images.githubusercontent.com/6097524/61214661-c77dd400-a708-11e9-8b37-d5151e45743b.PNG)

**Desired behavior**
![desired](https://user-images.githubusercontent.com/6097524/61214790-280d1100-a709-11e9-9ab4-20c7e3b71f68.PNG)

**Additional information**
PrestaShop version: 1.7.6
Faceted search version: 3.1.0

**Comment by mariem-abid** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with PS:1.7.6.0
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by marionf** [comment]
@Hlavtox 
Version 3.1.0 doesn't exists, the last one is 3.0.7, can you please tell us what is your version ?
Thank you

**Comment by marionf** [comment]
In 3.0.7 version, if you have 0 products for a feature value, this feature value isn't displayed as a filter in front-office

**Comment by Hlavtox** [comment]
I guess it does? :-) 

![faceted](https://user-images.githubusercontent.com/6097524/61226444-b8a41b00-a722-11e9-830c-12fca7bf0607.PNG)

**Comment by mariem-abid** [comment]
@marionf, also I tested with the version 3.1.0

**Comment by marionf** [comment]
> I guess it does? :-)

You're right, my bad I didn't see it

**Comment by marionf** [comment]
I can reproduce it with version 3.1.0

**Comment by Hlavtox** [comment]
@marionf You can close this issue. Fixed.

After 3.2.1, there is no posibility to reach this state I think, as it hides all "unsuable" values. :-)
