### ISSUE TITLE
Faceted search filter visibility when no products appliable

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14655]
Faceted search should hide or grey out the options in filters, which are not appliable to any product. Or there should be an option like in 1.6. There is no point of having million of choices. It should bring the user to tight selection of products, with less and less options.

**Example**
You have following filters
_Material_
`Steel`
`Glass`

_Steel look_
`Polished`
`Brushed`

_Glass look_
`Nice`
`Ugly`

**Current behavior**
You select _Material_: `Glass` and filter _Steel Look_ is still visible with product count in brackets. So user clicks on _Steel look_: `Polished` and sees 0 products found. Isn't it confusing?

**Desired behavior**
You select `Steel` - Filter _Glass look_ should get hidden.
You select `Glass` - Filter _Steel look_ should get hidden.
You select `Nice` or  `Ugly` - `Steel` option should get hidden.
You select `Polished` or  `Brushed` - `Glass` option should get hidden.

When there is only one remaining option in the Filter, the filter should get hidden.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 3.1.0

**Comment by mariem-abid** [comment]
@colinegin, @sarahdib, what do you think?

**Comment by marionf** [comment]
We can add an option "Hide filter values when no product is matching" like in blocklayered in 1.6 version

![capture d'écran_1769](https://user-images.githubusercontent.com/13449658/61456582-c0540180-a966-11e9-920d-615bcfe23f6a.png)

**Comment by Hlavtox** [comment]
@marionf @colinegin @sarahdib 

Have a look my comparsion and you will see my point.
https://drive.google.com/file/d/1TMZfDF3sMTMcpeD5_8lE0IeF5XSmo38r/view?usp=sharing

The refresh of the module was good but it has some new quirks and missing stuff I already mentioned in other issues/feature requests.

**Comment by Hlavtox** [comment]
@marionf Fixed on 3.2.1. It hides all values, which do not match any product. You can close it.

@PierreRambaud Faceted search is great again!!! 🚀

PS: Add stock filtering by quantity and it will be even greater 💣;-)

**Comment by marionf** [comment]
Thank you for your feedback @Hlavtox it's nice to hear :)
