### ISSUE TITLE
Vouchers with carrier restrictions don't apply on time

### ISSUE THREAD

**Issue by hacchus** [PrestaShop/PrestaShop#14652]
If you create a voucher that has carrier restrictions, it won't be applied unless you proceed to the payment step during checkout or manually change carrier selection during the "Shipping Method" step.

**To Reproduce**

1. Have two carriers setup with different costs and none of them free
2. In carrier preferences select "Default Carrier" as "Best Price"
3. Create a voucher for free shipping, without code and allow it only for the cheapest of your two carriers
4. Put some products to your cart and go to checkout
5. Select an address (valid for both carriers) and continue to "Shipping Method" step.
6. The best price carrier (for which the voucher is applicable) is selected by default, but the coupon is not applied.
7. If you select the other carrier and then select the first carrier again the coupon is correctly applied. Alternatively, if you proceed to payment you will again see that the voucher is applied.
8. The problem is that if the customers don't see the discount voucher immediately at the "Shipping Method" step, they might abandon their order.

**Screenshots**

![1](https://user-images.githubusercontent.com/5149317/61210886-94d2dc00-a706-11e9-8488-90ac6567144c.png)

![2](https://user-images.githubusercontent.com/5149317/61210900-a0be9e00-a706-11e9-895a-189753709665.png)

![3](https://user-images.githubusercontent.com/5149317/61210907-a2886180-a706-11e9-9e55-cd1bbc084431.png)

**Additional information**
PrestaShop version: 1.7.6.0, 1.7.5.2, 1.7.4.4
PHP version: 7.2

**Comment by mariem-abid** [comment]
Hi @hacchus,

A cart rule without "code", the free shipping is not be applied.
Thanks for check and feedback.

**Comment by mariem-abid** [comment]
Hi @hacchus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
