### ISSUE TITLE
appParameters.php not found on new server 

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#14653]
Hello,

I am trying to transfer my Prestashop 1.7.5 website on my new server and I got this issue bellow 

**Fatal error: require_once(): Failed opening required '/var/www/clients/client0/web1/web/var/cache/dev/appParameters.php' (include_path='/var/www/clients/client0/web1/web/vendor/pear/pear_exception:/var/www/clients/client0/web1/web/vendor/pear/console_getopt:/var/www/clients/client0/web1/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client0/web1/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client0/web1/web/config/bootstrap.php on line 86**

![erreurpresta](https://user-images.githubusercontent.com/39828779/61213116-6522d480-a704-11e9-853d-30079e9e4d4d.png)

I don't know how to fix it.. I tried to change PHP version 7.0, 7.1 and 7.2, no success. 

I use a dedicated OVH server and I am using ISPconfig 3.0.5.4 (Debian 9)

Thanks by advance for your help

**Comment by mariem-abid** [comment]
Hi @Dupflo,

Could you please try to clear cache manually: go to your Prestashop installation directory and delete the content of the following folders: cache/smarty/compile, cache/smarty/cache.

**Comment by mariem-abid** [comment]
Hi @Dupflo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by danishlaeeq** [comment]
Hello Mariem-abid

i also have the same issue and removing cache manually is not working

**Comment by danishlaeeq** [comment]
i have created folder "dev" inside var/cache/ and put appParameters.php

and now it's giving this error

Fatal error: Uncaught Error: Class 'Db' not found in /var/www/html2/config/alias.php:48 Stack trace: #0 /var/www/html2/config/alias.php(53): pSQL('configuration') #1 /var/www/html2/classes/Configuration.php(155): bqSQL('configuration') #2 /var/www/html2/classes/Configuration.php(209): ConfigurationCore::loadConfiguration() #3 /var/www/html2/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...') #4 /var/www/html2/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex() #5 [internal function]: PrestaShopAutoload->load('Db') #6 /var/www/html2/config/alias.php(48): spl_autoload_call('Db') #7 /var/www/html2/config/alias.php(53): pSQL('configuration') #8 /var/www/html2/classes/Configuration.php(155): bqSQL('configuration') #9 /var/www/html2/classes/Configuration.php(209): ConfigurationCore::loadConfiguration() #10 /var/www/html2/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...') #11 /var/www/html2/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->g in /var/www/html2/config/alias.php on line 48

**Comment by khouloudbelguith** [comment]
Hi @danish234,

If you use `opcache`, I think you have an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10998
you need to follow these steps: https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-476361695
```
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.fast_shutdown = 0
```
Fixed with this PR: https://github.com/PrestaShop/docker/pull/193

Thanks!

**Comment by fabiodc95** [comment]
> advance

@Dupflo 
Hello, I have the same exact issue, how did you solve it?

**Comment by Dupflo** [comment]
Sorry mate I remember I just reinstall a copy of the website ...

**Comment by sneko** [comment]
A possible solution is to regenerate cache files: `php -d memory_limit=-1 ./bin/console cache:clear --env=dev`.
