### ISSUE TITLE
Facebook pixel - prestashop

### ISSUE THREAD

**Issue by xxrestlessx** [PrestaShop/PrestaShop#14669]
Hi! 

We have an issue with Facebook Ads and Prestashop. We reinstalled Facebook pixel and it's not working correctly. We can't retarget 100% of views, purchases and add to cart. The error is shown in catalogs. Anyone know what is going on? Is this fault of prestashop?

**Comment by khouloudbelguith** [comment]
Hi @xxrestlessx,

As it's not a module provided by the Prestashop core, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=27646
Thanks!
