### ISSUE TITLE
Cannot install product comments module

### ISSUE THREAD

**Issue by blahapeta** [PrestaShop/PrestaShop#14662]
Cannot install Product Comments module

**To Reproduce**
1. Go to modules->module catalog->Product Comments
2. Click on Install

DEBUG:
Exception thrown by module productcomments on install. Column count doesn\'t match value count at row 1INSERT IGNORE INTO `ps_product_comment_criterion` VALUES (\'1\', \'1\', \'1\') 

Firefox developer console:
{"productcomments":{"status":false,"msg":"Cannot install module productcomments. Unfortunately, the module did not return additional details."}}

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/1114515/61221930-e6d12d00-a719-11e9-9c13-a27caf04d43d.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by mariem-abid** [comment]
Hi @blahapeta,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by blahapeta** [comment]
Hi @mariem-abid ,
i have solved it.

Problem was in my database. There was one extra row in my table. After removing it i was able to install module.

ALTER TABLE ps_product_comment_criterion DROP COLUMN id_shop;

I had Mypresta product comment module i installed previously. It probably altered this db table.
https://mypresta.eu/modules/advertising-and-marketing/free-product-reviews-comments.html

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @blahapeta,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by DPStudioGR** [comment]
> ALTER TABLE ps_product_comment

I also have the same problem and had previously installed the same module from mypresta...
Can you be more specific as to how to resolve this\?

**Comment by blahapeta** [comment]
My Prestashop is totally broken now, have to reinstall. Not sure why. Only thing i can recommend it to do **not do changes by hand** like me. Hope Mypresta and official Prestashop will communicate about this matter and resolve it

**Comment by shnslmz** [comment]
@Stampa-Stampa and @blahapeta 
You can remove vikea's module tables on phpMyadmin manually.

--
@khouloudbelguith 

Why this module can be just/min. usable for +1.7.6.0?

//$this->ps_versions_compliancy = array('min' => '1.7.6', 'max' => _PS_VERSION_);

It needs which changes to be avaible for 1.7.4.4?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @shnslmz,

It is compatible with PrestaShop from PS1.7.6.0.
You can change this line
`$this->ps_versions_compliancy = array('min' => '1.7.6', 'max' => PS_VERSION);`
by this
`$this->ps_versions_compliancy = array('min' => '1.7.4', 'max' => PS_VERSION);`
But, it is not official this change, it can provide you issues because it is not compatible.

Thanks!

**Comment by shnslmz** [comment]
> 
> 
> Hi @shnslmz,
> 
> It is compatible with PrestaShop from PS1.7.6.0.
> You can change this line
> `$this->ps_versions_compliancy = array('min' => '1.7.6', 'max' => PS_VERSION);`
> by this
> `$this->ps_versions_compliancy = array('min' => '1.7.4', 'max' => PS_VERSION);`
> But, it is not official this change, it can provide you issues because it is not compatible.
> 
> Thanks!

Hi @khouloudbelguith ,

Yes. 
This is exactly what I want to ask:
"But, it is not official this change, it can provide you issues because it is not compatible."

Is there any big changes between this two versions, at this point, do you have any info?

Thanks!

**Comment by khouloudbelguith** [comment]
@shnslmz, you can follow this [link](https://www.prestashop.com/en/previous-versions) & check the changelog between each version.

Thanks!

**Comment by photinia73** [comment]
> Hi @mariem-abid ,
> i have solved it.
> 
> Problem was in my database. There was one extra row in my table. After removing it i was able to install module.
> 
> ALTER TABLE ps_product_comment_criterion DROP COLUMN id_shop;
> 
> I had Mypresta product comment module i installed previously. It probably altered this db table.
> https://mypresta.eu/modules/advertising-and-marketing/free-product-reviews-comments.html
> 
> Thanks!

The same situation )) Thanks for SQL query )
