### ISSUE TITLE
How to add several attributes to the same product feature?

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#14675]
On Prestashop 1.6.x.x, we could add several attributes to the same feature (for example: For the characteristic Size, we could put S, L, XL or XXL).
On Prestashop 1.7.5.1, I do not find how to do it. The only alternative I have found is to create the same feature as many times as I have attributes.
In my example, I end up with 4 features Size with 4 different attributes :
Size : S
Size : L
Size : XL
Size : XXL

Therefore, I have a table of product features that is very long and (very) unclear to the customer / user.

Hence my question: How to add several attributes to the same product feature?

It may be stupid, but I have not (yet) found how to do it.

Thank you in advance for your help
Have a nice day ;)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @wikao2,

Thanks for your report.

Could you please provide me a screenshot about the exact difference between PS1.7 & PS1.6.

Thanks!

**Comment by wikao2** [comment]
Hi @khouloudbelguith

Please find attached screenshots.
![features-on-presta-1 6](https://user-images.githubusercontent.com/48359467/61296956-7854a380-a7db-11e9-9333-3f309cab89e4.jpg)
![features-on-presta-1 7](https://user-images.githubusercontent.com/48359467/61296957-7854a380-a7db-11e9-9d51-570dbb0f5857.jpg)
Is it what you want ?

**Comment by khouloudbelguith** [comment]
@wikao2, thanks for these clarifications.
I checked with PS1.7.5.1 & PS1.7.6.0.
In the FO => Product page, the features are well displayed 
![image](https://user-images.githubusercontent.com/16067358/61303506-86a4be80-a7df-11e9-8957-137f88b51202.png)
It is not similar to yours.

In the BO, after reloading the product page => the features are displayed in order.
![image](https://user-images.githubusercontent.com/16067358/61303594-b2c03f80-a7df-11e9-9141-a48572db524c.png)

I attached a screen record
https://drive.google.com/file/d/1CIMK-2V4Q1tuFE6t0xnbEbOVWI9Z6GzL/view
Thanks to check & feedback.

**Comment by wikao2** [comment]
I think it's a problem related to the theme, because actually, when I reload the page (on the BO or on the FO) the features appear in order. However, even if on the FO it appears in order, I always have:
Feature 1 Value 1
Feature 1 Value 2
Feature 2 Value 1
Feature 2 Value 2
If I have multiple values for the same feature, I still have as many rows as values.
I'll ask that with the developer of the theme.
Thank you for your reply.

**Comment by khouloudbelguith** [comment]
@wikao2,
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
