### ISSUE TITLE
Add another scenario for disabled products

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14676]
I want to give you an idea what to do with disabled products. I made the modification manually, but it would be nice to have in default PS.

**Current options of what to do with disabled products**
- 404
- 301 product redirect
- 302 product redirect
- 301 category redirect
- 302 category redirect

**My idea**
Add a 6th option - **Show a replacement product**
1. If this option was enabled and id_product_redirected was set up.
2. User would come from some old link.
3. We would show him the product, but with a text **No longer in sale** and show him a box: This product was replaced with a newer model, with image, price and link to the new product.

**My custom solution in PS 1.6.1.23**
![replacement](https://user-images.githubusercontent.com/6097524/61288770-1e96ae00-a7c8-11e9-88a8-779761b3a51a.PNG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
ping @colinegin, @marionf what do you think of his improvement?
It could be added to the new Product page feature?

Thanks!

**Comment by marionf** [comment]
Hello @Hlavtox 

Why displayed the disabled product ? 
The final result is the same as a permanent or temporary redirection to a product, customers are invited to click on the replacement product. But you can lose them if they don't click on it. This doesn't happen with the 301 or 302 redirection.

**Comment by Hlavtox** [comment]
Hi @marionf,

redirect is way better uproach than 404, but the thing is, it can be confusing for the customer, and it really is.

Imagine you search for something on google, you click on a link and get redirected to a product with different name, look, parameters. You say: “where am I?” and possibly leave because it's not what you wanted.

When you display the product first, he will know what he is on. Do you get me?

**Comment by marionf** [comment]
All right, I understand, thanks for your reply !

I added your suggestion on here: http://feedback.prestashop.com/forums/387864-prestashop-1-7-x/suggestions/38173840-add-another-scenario-for-disabled-products so people can vote for it, and we will see if it's someting that interests other people
