### ISSUE TITLE
ContextErrorException  jxsecuritypanel.php

### ISSUE THREAD

**Issue by MEGA911** [PrestaShop/PrestaShop#14674]
**Describe the bug**
We don't have access to the Back-Office : ERREUR 500 => Only on mode debug and when i stay on regular mode I have a big bug on the front and vice versa

**To Reproduce** Active the debug mode via FTP : defines.inc.php
1. Go to 'https://www.march-lab.com'
2. Click on 'women or men'

**Screenshots**

(1/1) ContextErrorExceptionWarning: Cannot assign an empty string to a string offset
--
in jxsecuritypanel.php line 131
at Jxsecuritypanel->getSettings(array('JXSECURITY_CONTENT_COPY' => '0', 'JXSECURITY_CONTENT_PASTE' => '0', 'JXSECURITY_CONTENT_CUT' => '0', 'JXSECURITY_CONTENT_SELECT' => '0', 'JXSECURITY_CONTENT_SEARCH' => '0', 'JXSECURITY_CONTENT_SAVE' => '0', 'JXSECURITY_CONTENT_PRINT' => '0', 'JXSECURITY_CONTENT_HELP' => '0', 'JXSECURITY_CONTENT_DEV' => '0', 'JXSECURITY_CONTENT_SOURCE' => '0', 'JXSECURITY_CONTENT_RELOAD' => '0', 'JXSECURITY_CONTENT_RELOAD_CACHE' => '0', 'JXSECURITY_CONTENT_SCREEN' => false, 'JXSECURITY_CONTENT_CONTEXTMENU' => '0', 'JXSECURITY_CONTENT_HOTLINKING' => '0', 'JXSECURITY_CONTENT_TEXTSELECTION' => '0', 'JXSECURITY_CONTENT_DRAGNDROP' => '0', 'JXSECURITY_CONTENT_COPY_TEXT' => ''))in jxsecuritypanel.php line 161
at Jxsecuritypanel->setMedia()in jxsecuritypanel.php line 245
at Jxsecuritypanel->hookHeader(array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 34))in Hook.php line 966
at HookCore::coreCallHook(object(Jxsecuritypanel), 'hookHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 34))in Hook.php line 355
at HookCore::callHookOn(object(Jxsecuritypanel), 'displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 34))in Hook.php line 903
at HookCore::exec('displayHeader')in FrontController.php line 555
at FrontControllerCore->initContent()in CategoryController.php line 130
at CategoryControllerCore->initContent()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 511
at DispatcherCore->dispatch()in index.php line 28

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @MEGA911,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by MEGA911** [comment]
You need some info to connect at the BO and the FTP ? maybe database
(For information I try to restaure a databse backup but I have the same problem)

**Comment by khouloudbelguith** [comment]
@MEGA911, Thanks to downgrade your version PHP, check & feedback.

**Comment by MEGA911** [comment]
ok i test

**Comment by khouloudbelguith** [comment]
@MEGA911, thanks!
Waiting for your feedback.

**Comment by MEGA911** [comment]
PHP 7.2
But i can't access to the BO

**Comment by MEGA911** [comment]
ERREUR 500 => I access to the BO only with debug mode

**Comment by khouloudbelguith** [comment]
@MEGA911,
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by MEGA911** [comment]
Cool  I access to my BO

**Comment by khouloudbelguith** [comment]
@MEGA911, great!

So the issue is fixed?

Thanks!

**Comment by MEGA911** [comment]
Perfect !!
YOU ARE THE BOSS

IT WORKS => BUT know is strangly in the front on retailers we don't have now the google map for the Geolocalisation => Very strange

https://www.march-lab.com/fr/boutiques

**Comment by MEGA911** [comment]
The issue was good but i don't understand why the module store don't display the map
How i can fix this bug ?

**Comment by khouloudbelguith** [comment]
@MEGA911, did you use a custom module to display the map on the "stores" page?


Thanks!

**Comment by MEGA911** [comment]
yes => 
Store Locator
v1.6.5 - par BelVG

**Comment by MEGA911** [comment]
https://addons.prestashop.com/fr/international-localisation/6650-localisateur-de-magasin.html

**Comment by MEGA911** [comment]
can i desactive and reactive the module ?

**Comment by khouloudbelguith** [comment]
@MEGA911, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by MEGA911** [comment]
Ok THANKS FOR ALL 
IT WORKS I DESACTIVE ET REACTIVE THE MODULE

YOU ARE THE BOSS
