### ISSUE TITLE
Admin logouts when any option is selected like order/invoice/modules/settings etc.

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14678]
I am facing issue for prestashop 1.7X admin login

it logouts when any option is selected like order/invoice/modules/settings etc.

I have to re-login and select menu option again but its logout again.

please help

**Comment by khouloudbelguith** [comment]
Hi @banobazaar,

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
if ($this->context->cookie->last_activity + 900 < time()) {

By this:

if ($this->context->cookie->last_activity + 3600 < time()) {

Thanks to check & feedback.

**Comment by banobazaar** [comment]
thank you @khouloudbelguith

**Comment by didi-2018** [comment]
@khouloudbelguith  how can I disable IP Check in classes/Cookie.php? I am facing the same problem. But do not know where to disable?

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

You can comment this condition: `&& (!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP'))`
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cookie.php#L240

Thanks!
