### ISSUE TITLE
In the Dashboard page Previous version Prestashop, Newest version is not updated

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#14688]
**Describe the bug**
In the Dashboard page Previous version Prestashop, Newest version is not updated
**To Reproduce**

1. Prestashop old version < 1.7.6.
1. Go to the BO => Dashboard

=> Newest version is not updated

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/61306261-2fedb380-a7e4-11e9-8fcd-1d33026fb53f.png)
![image](https://user-images.githubusercontent.com/16067358/61306376-69beba00-a7e4-11e9-8c0b-bdb62abc4e86.png)

**Additional information**
PrestaShop version: old version < PS1.7.6
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/64123913-88314280-cd9d-11e9-8ae1-9ead3b652d43.png)
The latest version is PS1.7.6.1

**Comment by atomiix** [comment]
@marionf, It seems to be related to the Prestashop api (api.prestashop.com).

You can check [this url](http://api.prestashop.com/version/check_version.php?v=1.7.5.2&lang=fr&autoupgrade=0&hosted_mode=0) to see that what is displayed is wrong

**Comment by matks** [comment]
@marionf This URL returns what is displayed in the Back-Office. So if the content is false, it must fixed in the source of the content, on api.prestashop.com

**Comment by marionf** [comment]
I close the issue as it can't be solved in PS core
You can follow the issue here: http://forge.prestashop.com/browse/PLFS-1346
