### ISSUE TITLE
Stuck in Maintenance Mode After Update

### ISSUE THREAD

**Issue by SSHawke** [PrestaShop/PrestaShop#14696]
**Describe the bug**
After I updated from version 1.7.4.3 to 1.7.6.0 I cannot get the shop out of maintenance mode. The settings show the shop as active, however it is still displaying my maintenance message. I have a multishop. All shops are showing maintenance message. I have emptied cache and I am able to get to the admin panel without issue.

**Comment by khouloudbelguith** [comment]
Hi @SSHawke,

Thanks for your report.
Did you try to disable the maintenance mode shop by shop?
You need to select your shop in the BO => Disable the maintenance mode & save.
Thanks to check & feedback.

**Comment by mariem-abid** [comment]
Hi @SSHawke,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
