### ISSUE TITLE
Unable to upload png files into Product categories pages

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#14693]
**Describe the bug**
I wanted to use a png file as product category image but I can't, the file is always converted to jpg file at best.

**To Reproduce**
1. Go to the Back Office, in Sell > Categories
2. Edit a category, upload a png file
3. Save and the message of success
4. Then check the file: well, it's a jpg and the transparency is lost.

![oupsy](https://user-images.githubusercontent.com/1247388/61325045-22502200-a814-11e9-8d24-362d4d927189.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @mickaelandrieu,

I have the same issue with PS1.7.5.1 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/61358680-c7014c80-a872-11e9-9309-2ef6132c44a8.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by mickaelandrieu** [comment]
Fair enough !

Thanks @khouloudbelguith :)

**Comment by marionf** [comment]
@mickaelandrieu 

Can you tell us what is selected in your BO > Design > Image > Image format ?

**Comment by mickaelandrieu** [comment]
Sorry for your time @marionf
