### ISSUE TITLE
Polish blockreassurance module

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14700]
Before releasing blockreassurance v4, we can give it a few more polishing 😄 

Todo list
- [x] Merge css files in 2 files only: for front, one for back (=> can be done using webpack if you want to, in order to keep split files for dev but bundle them for prod)
- [x] Refactor the svg management (https://github.com/PrestaShop/blockreassurance/blob/dev/views/js/front.js#L34)
- [x] The module uses `$this->ajaxDie(json_encode('error'));` everywhere (the issue is that it returns HTTP 200 instead of HTTP 400) 🤔 
- [x] Have a round of QA validation
- [x] Add Travis (recherche à facettes)

**Comment by Progi1984** [comment]
PR PrestaShop/blockreassurance#22
