### ISSUE TITLE
[CLDR] Manage save and interpretation of currency customization (3/3)

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14709]
After saving the currency new display, the saved information will override information from the CLDR files and create a new CLDR format to be interpreted. 

Blocked by 1.7.6.2 and 1/3 & 2/3

**Comment by colinegin** [comment]
Hello @jolelievre , is this issue fixed by #14972 ?

**Comment by jolelievre** [comment]
As explained in this other comment https://github.com/PrestaShop/PrestaShop/issues/14750#issuecomment-549368083
No the PR  #14972 is only the first one, two other PRs will be coming once it is merged.
