### ISSUE TITLE
how can i get the why slow

### ISSUE THREAD

**Issue by langziyang** [PrestaShop/PrestaShop#14724]
PrestaShop version: PrestaShop version: 1.7.5.1 
PHP version: 7.2.19 

index.php/configure/advanced/system-information/

![1](https://user-images.githubusercontent.com/2345387/61426486-2469cc00-a94d-11e9-8e76-63821df8b703.png)

**Comment by khouloudbelguith** [comment]
Hi @langziyang,

Could you please try to enable profiling mode
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```
by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks to check & feedback.

**Comment by langziyang** [comment]
> Hi @langziyang,
> 
> Could you please try to enable profiling mode
> In your Projetc_Folder/config/defines.inc.php, you need to replace this
> 
> ```
> if (!defined('_PS_DEBUG_PROFILING_')) {
>     define('_PS_DEBUG_PROFILING_', flase);
> }
> ```
> 
> by this
> 
> ```
> if (!defined('_PS_DEBUG_PROFILING_')) {
>     define('_PS_DEBUG_PROFILING_', true);
> }
> ```
> 
> When profiling mode is enabled, you should have information about the time needed to run queries.
> 
> Thanks to check & feedback.

you can see on https://demo.518global.com/zh/ i upgrade to 1.7.5.2

**Comment by langziyang** [comment]
> Hi @langziyang,
> 
> Could you please try to enable profiling mode
> In your Projetc_Folder/config/defines.inc.php, you need to replace this
> 
> ```
> if (!defined('_PS_DEBUG_PROFILING_')) {
>     define('_PS_DEBUG_PROFILING_', flase);
> }
> ```
> 
> by this
> 
> ```
> if (!defined('_PS_DEBUG_PROFILING_')) {
>     define('_PS_DEBUG_PROFILING_', true);
> }
> ```
> 
> When profiling mode is enabled, you should have information about the time needed to run queries.
> 
> Thanks to check & feedback.

and the backoffice is
![1](https://user-images.githubusercontent.com/2345387/61440314-cd2c2180-a975-11e9-81bb-78de54c483ca.png)

**Comment by khouloudbelguith** [comment]
@langziyang, 
- Do you have any additional cache? for example opcache?
- Try to implement this fix: https://github.com/PrestaShop/PrestaShop/pull/12940/files
- Some performance issues have been detected on our side and have been solved with #11559.
It is added in the PS1.7.6.0, try to implement this fix also.

Thanks to check & feedback.

**Comment by langziyang** [comment]
> @langziyang,
> 
> * Do you have any additional cache? for example opcache?
> * Try to implement this fix: https://github.com/PrestaShop/PrestaShop/pull/12940/files
> * Some performance issues have been detected on our side and have been solved with #11559.
>   It is added in the PS1.7.6.0, try to implement this fix also.
> 
> Thanks to check & feedback.

1、yes,i use opcache
ok,i will try other thing,thanks

**Comment by khouloudbelguith** [comment]
@langziyang, Could you please try to disable any type of caching extensions, check & feedback.
PS: you can follow our documentation to optimize your shop: https://devdocs.prestashop.com/1.7/scale/optimizations/
Thanks!

**Comment by langziyang** [comment]
> @langziyang, Could you please try to disable any type of caching extensions, check & feedback.
> PS: you can follow our documentation to optimize your shop: https://devdocs.prestashop.com/1.7/scale/optimizations/
> Thanks!

i already do this documentation

**Comment by khouloudbelguith** [comment]
@langziyang, any news?
Did you try to implement fixes?

Thanks!

**Comment by langziyang** [comment]
> @langziyang, any news?
> Did you try to implement fixes?
> 
> Thanks!

yes,i did

**Comment by khouloudbelguith** [comment]
@langziyang, your shop is still slow?

Thanks!

**Comment by langziyang** [comment]
> @langziyang, your shop is still slow?
> 
> Thanks!

i am try up gto 1.7.6.0

**Comment by khouloudbelguith** [comment]
@langziyang, thanks!

Waiting for your feedback.

**Comment by langziyang** [comment]
> @langziyang, thanks!
> 
> Waiting for your feedback.

i upgrade, look like better,  https://demo.518global.com/zh/
thank you

**Comment by khouloudbelguith** [comment]
@langziyang, great!
I close the issue, feel free to open a new one when needed.

Thanks!
