### ISSUE TITLE
Color combination issue in backoffice after update to 1.7.6.0

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#14720]
Hi there....
i have an eshop  (stampa-stampa.com) and today i decided to upgrade to 1.7.6.0..
what i noticed right away is that when i edit a product and try to choose different pictures per combination nothing happens. Pictures although are uploading correctly and showing with no errors are not clickable or can be selected.

**Comment by khouloudbelguith** [comment]
Hi @Stampa-Stampa,

Your ticket is a duplicate of #14708
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14708

**Comment by DPStudioGR** [comment]
This is not a simple issue ......
i also tried to rollback to 1.7.5.2 and i get the following error..

[INTERNAL] /home/stampast/public_html/stampa-stampa.com/config/config.inc.php line 123 - Error: Call to a member function getName() on null #0 /home/stampast/public_html/stampa-stampa.com/modules/autoupgrade/classes/UpgradeContainer.php(550): require_once() #1 /home/stampast/public_html/stampa-stampa.com/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /home/stampast/public_html/stampa-stampa.com/Iriathen/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}
