### ISSUE TITLE
Tools::getDateFormat function return DD in format forcely

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#14729]
**Describe the bug**
small dd should be here for date format according to this rule

![image](https://user-images.githubusercontent.com/1533248/88403054-49004b80-cdcc-11ea-833b-b39ab2a3680c.png)

here in function getDateFormat,
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/Tools.php#L1013

I can create a PR if this should not have any issue.

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by davidglezz** [comment]
It seems that it is only used for the placeholder of birthdate input.

So it is a human understandable format and not an date format rule.

https://github.com/PrestaShop/PrestaShop/blob/6c0372118c9f377310045401ca0ae80a75e30570/classes/form/CustomerFormatter.php#L208

**Comment by PierreRambaud** [comment]
Yes, also you're refering to another language. We are using PHP: https://www.php.net/manual/en/datetime.format.php
I'm closing this issue. Thanks
