### ISSUE TITLE
Bug upgrading modules 

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#14722]
**Describe the bug**
when there are modules to upgrade, we clic upgrade all and after the process is successful and press F5 to reload, appear the modules again as it was not upgrading. 

**Additional information**
PrestaShop version: 1.7.5.1 and 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @msautral,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1V-Xqg2QvkTfuj3rkmMM7gTBPMf9kfM7p/view
Thanks to check & feedback.

**Comment by JavierEB** [comment]
> 
> 
> Hi @msautral,
> 
> I did not manage to reproduce the issue with PS1.7.6.0.
> I attached a screen record
> https://drive.google.com/file/d/1V-Xqg2QvkTfuj3rkmMM7gTBPMf9kfM7p/view
> Thanks to check & feedback.

![error addons](https://user-images.githubusercontent.com/5004396/61452888-1fad1400-a95d-11e9-8139-00e5bd1d4bf9.jpg)
the partner is right I can also have those update errors of "Addons Prestashop" and tested in version 1.7.5.2 and then updated to version 1.7.6 and still jumping the same errors ... In fact I'm trying to install a new template for my store and I miss 500 error due also to the failure of communication with Addons

**Comment by khouloudbelguith** [comment]
@msautral, @JavierEB, isn't the same issue reported here: #11450?

Thanks!

**Comment by JavierEB** [comment]
> 
> 
> @msautral, @JavierEB, isn't the same issue reported here: #11450?
> 
> Thanks!

It is the same problem I think, but in my case it does not update any module. It is with all the prestashop modules. However, last night I updated them all perfectly, so, I think it is due to a problem of punctual generalized "Addons Prestashop"

**Comment by msaustral** [comment]
Hi everyone, it is not the same issue, the back office say that the module have been successfully updated but when you reload the page the same module say upgrade on the bottom again, but mysteriously today did upgrade all modules without any problem. :(

**Comment by khouloudbelguith** [comment]
@msautral, so this issue is fixed in your shop?

Thanks!

**Comment by msaustral** [comment]
I do not think it's fixed because things do not fix themselves, I would try to reproduce it next time I have modules to upgrade, it is not the first time that this happen to me.

**Comment by khouloudbelguith** [comment]
@msautral, we have a similar issue about upgrade module issue: #11450 added to our bug roadmap.

Thanks!

**Comment by JavierEB** [comment]
> 
> 
> Hi everyone, it is not the same issue, the back office say that the module have been successfully updated but when you reload the page the same module say upgrade on the bottom again, but mysteriously today did upgrade all modules without any problem. :(

But in the end I think that if the problem is that the communication with "Addons Prestashop" fails, the problems, even if they are not the same, are related, since in the end it does not update correctly when the connection fails ... with the prestahop market ... I do not tell you from my humble thoughts :)

**Comment by msaustral** [comment]
Hi the important thing is to solve the bug, no matter where :)

**Comment by khouloudbelguith** [comment]
@msautral, @JavierEB, we are working on this problem.
I will get you updated if it is fixed.

Thanks for your understanding!

**Comment by JavierEB** [comment]
thanks to you always for your support :+1:

**Comment by JavierEB** [comment]
> 
> 
> @msautral, @JavierEB, we are working on this problem.
> I will get you updated if it is fixed.
> 
> Thanks for your understanding!

thanks to you always for your support +1

**Comment by khouloudbelguith** [comment]
Hi @msautral, @JavierEB,

There was an issue with some of our modules, we fixed it. Do you still have issues on your side?

Thanks!

**Comment by JavierEB** [comment]
> 
> 
> Hi @msautral, @JavierEB,
> 
> There was an issue with some of our modules, we fixed it. Do you still have issues on your side?
> 
> Thanks!

yes everything solved. It works perfectly Thank you

**Comment by khouloudbelguith** [comment]
@msautral, any news?

Thanks!

**Comment by msaustral** [comment]
Hi, I had to click 2 times on upgrade all to get the modules upgrade:
1- upgrade all
2- reload the page
3- again 3 modules tu upgrade
4- again upgrade all
5- reload
6- nothing to upgrade

![module2](https://user-images.githubusercontent.com/46203943/61637632-eb3f9d80-ac65-11e9-82b2-0e4c49d2743e.png)
![mudule1](https://user-images.githubusercontent.com/46203943/61637634-eb3f9d80-ac65-11e9-94c3-a69b8633a0e9.png)

**Comment by khouloudbelguith** [comment]
@msautral, so your issue is different.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by msaustral** [comment]
HI here is a video to explain what is happening, there are no error.

[module.zip](https://github.com/PrestaShop/PrestaShop/files/3417805/module.zip)

**Comment by JavierEB** [comment]
> 
> 
> HI here is a video to explain what is happening, there are no error.
> 
> [module.zip](https://github.com/PrestaShop/PrestaShop/files/3417805/module.zip)

I suppose you have also tried another browser? Chrome or Firefox seems silly but it can be ...

**Comment by msaustral** [comment]
Hi I not really try it, but I use Chrome, sometimes works and some time don't, the day I started to write on this post it was no way to upgrade the modules, at the next day, just one time everything upgraded.

It happen on differents pages with different PS versions.

**Comment by khouloudbelguith** [comment]
@msautral, if you try to upgrade the module from the "Modules" tab page? this issue occurs also?
Thanks!

**Comment by msaustral** [comment]
Hi, yes it does :(

**Comment by khouloudbelguith** [comment]
@msautral, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by msaustral** [comment]
Hi, I got the issue in action on a new video, also I add Apache regular log, I do not have any apache error log, PHP logs or Chrome console log.

I miss the debug mode report, sorry.
[Module2.zip](https://github.com/PrestaShop/PrestaShop/files/3418415/Module2.zip)

**Comment by khouloudbelguith** [comment]
@msautral, could you please try to follow these steps:
- Go to this link: http://shop.com/modules/ps_linklist/config.xml
- Check the exact version displayed in your module 
```
<version>
<![CDATA[ 3.0.3 ]]>
</version>
```
![image](https://user-images.githubusercontent.com/16067358/61702218-560cd980-ad37-11e9-8532-05d1255d689e.png)
- Try to upgrade your module
- Go to this link: http://shop.com/modules/ps_linklist/config.xml again & check the new version

https://drive.google.com/file/d/1G20sOt5AotJ3GgO6SRDZUhoN6b5i5F6d/view
Thanks to check & feedback.

**Comment by msaustral** [comment]
HI there are no modules to upgrade, lets wait

**Comment by khouloudbelguith** [comment]
@msautral, thanks!
Waiting for your feedback.

**Comment by msaustral** [comment]
HI still no modules to update, sorry

**Comment by khouloudbelguith** [comment]
@msautral, I will close the issue.
Feel free to open a new one if this issue occurs again.

Thanks!

**Comment by msaustral** [comment]
Hi this is the second case that you close without a solution!!! Don't worry let's keep the issue on the platform!

**Comment by khouloudbelguith** [comment]
@msautral, There was an issue with some of our modules, we fixed it. 
Thanks for your understanding!

**Comment by msaustral** [comment]
I do not see that on the conversation! you were waiting 10 min ago to send you more information with a procedure that you ask me to do!, 

really this way does not make any sense to report something. have a good day.
