### ISSUE TITLE
1.7.6 productscomments  not available

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#14737]
After upgrading PS from 1.7.5.2 to 1.7.6  productcomments not available. Module productcomments not found 

Servergegevens Linux #1 SMP Wed May 15 10:57:13 EDT 2019 x86_64
Server softwareversie: Apache
PHP-versie: 7.2.20
Geheugenlimiet: 1024M
Maximale uitvoeringstijd: 300
Maximale bestandsgrootte voor uploads: 128M
PrestaShop-versie: 1.7.6.0
Winkel-URL: http://www.derks-wielersport.nl/
Shop path: /home/xxxxxxx/domains/derks-wielersport.nl/public_html
Huidig gebruikte thema: classic
Verplichte parameters: Oké
Optionele parameters: Oké

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Did you installed it before the upgrade?

Thanks!

**Comment by Peter4661** [comment]
Hi  khouloudbelguith,

I did not install it before the update. I assumed (correct or wrong 🤔) it
would come with the upgrade to 1.7.6


Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op do 18 jul. 2019 om 14:40 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@Peter4661, yes, the minor compliance version is PS1.7.6.0.
https://github.com/PrestaShop/productcomments

Thanks!

**Comment by Peter4661** [comment]
Thank you . Downloaded the zip file from github.

With attempt to install it, failed to install. System reports: 'this file
seems not a zip file for a module' 😨

Best regards,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op do 18 jul. 2019 om 15:29 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@Peter4661, you need to run this command `composer install` into this folder after cloning the module from GitHub.
Here's a zip file
[productcomments.zip](https://github.com/PrestaShop/PrestaShop/files/3406921/productcomments.zip)

Thanks to check & feedback.

**Comment by Peter4661** [comment]
Thank you for your help. Installed and working.

Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op do 18 jul. 2019 om 16:19 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@Peter4661, you are welcome!
I close the issue, feel free to open a new one when needed.

THanks!
