### ISSUE TITLE
[ORDER LIST] Order preview in Order page list

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#14732]
**USER STORY**

As a merchant, I want to quickly check the details of order without opening it in the order list.

**WHY**

Many merchants only open the order page to know and just to read the essential information from the order as the products, the amount, stock location or customer details. The preview order will prevent the merchant from opening all concerned orders and thus gain in productivity.

**SPECIFICATION**

When the mouse hovers over command, the symbol of the drop-down list is displayed on the left of the reference. 

![image](https://user-images.githubusercontent.com/43613217/63580582-6feb4780-c595-11e9-92c1-50c534e91103.png)

 
When the user clicks only the down arrow, it will display the order preview. The order preview is composed of the invoice details information, shipping details, information, Carrier details information (Carrier name + Tracking ID when available) and the product list. 
The opened order line becomes blueish.

![Capture d’écran 2019-10-16 à 10 35 46](https://user-images.githubusercontent.com/27484094/66902352-d1152180-f000-11e9-8214-5a24c7cc8653.png)

The product list displays on each line the product name, reference, stock location, quantity, taxes price and total price for the product (including taxes, the quantity factor).

The list can display only for a maximum of 10 products.
If the order as more than 10 product the button “Open Order” on the bottom right of the preview becomes “View the other X products”

Clicking on another preview list will close the previous one to open the one selected.

The preview has to be easily customizable for modules and specifics development

**DESIGN**

https://invis.io/YKTGGFZAMCB#/376656277_Order_List_-_Quick_View

**Comment by sarjon** [comment]
> The product list displays on each line the product name, reference, stock location, quantity, taxes price and total price for the product (including taxes, the quantity factor).

Currently it replicates products list that is displayed in Order view page, does it make sense to display different data in preview list?

> The list can display only for a maximum of 10 products.
If the order as more than 10 product the button “Open Order” on the bottom right of the preview becomes “View the other X products”

Isn't it confusing a little? Why do we have to replace “Open Order" button for some orders?

> Clicking on another preview list will close the previous one to open the one selected.

Does it make sense to allow having only on preview opened?

> The preview has to be easily customizable for modules and specifics development

@matks do you think we should add some hook in order preview template?

**Comment by matks** [comment]
> Isn't it confusing a little? Why do we have to replace “Open Order" button for some orders?

The idea is that
- orders with less than 10 items will be displayed as a whole, and the "Open Order" button will be available
- for orders with more than 10 items, we display only the 1st ten, and to highlight the fact there is more, we modify the naming of the button so the merchant understands there is more products
 
> @matks do you think we should add some hook in order preview template?

Yes 😄 we can add hooks if needed

For this last item: we must think about the usecases where modules want to customize some part of the preview.
Here are the usecases I can think of:
- customize the content
Easy feature: allow modules to modify the content of the modal
Complex feature: allow modules to modify either the whole content or only of the 3 blocks
- customize the button
- add some JS behavior on open or close
For this one I guess we can fire some JS event, and let modules to listen on them ?

**Comment by sarjon** [comment]
Is this how you image this to work? https://prnt.sc/pjib7x I have 12 products, 10 of them are displayed and 2 more can be viewed in order page.

**Comment by MatShir** [comment]
> > The product list displays on each line the product name, reference, stock location, quantity, taxes price and total price for the product (including taxes, the quantity factor).
>>Currently it replicates products list from Order view page, does it make sense to display different >>data in preview list?

The product name, reference, quantity, stock location and the total price are mandatory for the merchant to have all the must information on the preview.
From our user tests, it seems were pleased with the information displayed. We can't really quantify for whom it will be useless or priceless to have all the information.
I prefer to have all the columns and narrows some after proper use by merchants after the release to adjust for the best behaviours. The space between the address detail and the product lists should help for the responsive.

> > The list can display only for a maximum of 10 products.
> > If the order as more than 10 product the button “Open Order” on the bottom right of the preview becomes “View the other X products”

Well said by @matks, we don't want the merchant to think that all his orders are displayed and miss information. Do you think we should increase the threshold? @sarjon 

> > Clicking on another preview list will close the previous one to open the one selected.

It was a design decision. The idea to have only one opened is to have a clean working list. 
If the user really wants to compare order, he could open them with the right-click and if he needs the lists all the product of the day, the merchants shall pass to another tool.
I see as much as poor and cons for this, for me, we should see how people react to the feature.
Maybe, we could test the behaviours if the PR testable? To have a final shot on the decision.
 
Also, @sarjon. It was specified on the issue but not designed, but here how to display the carrier information in this new design.
![preview list + carrier](https://user-images.githubusercontent.com/43613217/66837013-9c528d00-ef62-11e9-97d6-f8f9e14681d4.png)

the link to invision: [preview list design](https://invis.io/YKTGGFZAMCB#/376656277_Order_List_-_Quick_View)

**Comment by sarjon** [comment]
@TristanLDD one more question, in case order/cart is virtual (contains only virtual products), do we need to show shipping details? Virtual order does not have carrier at all.

**Comment by TristanLDD** [comment]
@sarjon In case of virtual product we don't display any information in the Shipping column (let's use "-" in case): 
 
![Capture d’écran 2019-10-15 à 17 26 05](https://user-images.githubusercontent.com/27484094/66845797-ff4b2080-ef70-11e9-8630-6121785f49b5.png)

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/14682 has been merged in order to avoid git conflicts and endless rebases however I'll be waiting for validation before closing this issue 😉

**Comment by marionf** [comment]
Stock location is empty when product has combinations

![capture d'écran_2093](https://user-images.githubusercontent.com/13449658/67304012-86f5d980-f4f3-11e9-9522-e777e783735b.png)

![capture d'écran_2094](https://user-images.githubusercontent.com/13449658/67304036-8e1ce780-f4f3-11e9-90e9-bd6563abbd01.png)

And I have the errors below when I click on "Open details"

Order with a product without image:

![capture d'écran_2095](https://user-images.githubusercontent.com/13449658/67304091-9d039a00-f4f3-11e9-955c-b1a089d00822.png)

Demo orders:

![capture d'écran_2097](https://user-images.githubusercontent.com/13449658/67304960-e99ba500-f4f4-11e9-881e-c3ef080c40a4.png)

I defined a shipping address different of the delivery address
The shipping address firstname and lastname are not good
(Same thing if I change the firstname and lastname for invoice address)
I think it takes the firstname and lastname of the customer instead of the address

![capture d'écran_2101](https://user-images.githubusercontent.com/13449658/67306558-78a9bc80-f4f7-11e9-9877-f71e73146e68.png)

![capture d'écran_2099](https://user-images.githubusercontent.com/13449658/67306573-7f383400-f4f7-11e9-8271-cde2f6368933.png)

If I make an order tax excluded (tax disabled in International > Taxes), the total is displayed tax included instead of tax excluded

![capture d'écran_2102](https://user-images.githubusercontent.com/13449658/67307385-b9ee9c00-f4f8-11e9-8726-845ea4cbbe0f.png)

The customer mail address goes on the line

![capture d'écran_2096](https://user-images.githubusercontent.com/13449658/67304223-cde3cf00-f4f3-11e9-85b7-ded176b5ce84.png)

**Comment by sarjon** [comment]
> If I make an order tax excluded (tax disabled in International > Taxes), the total is displayed tax included instead of tax excluded

If you open order view (legacy), does it show "Tax included" or "Tax excluded"?

**Comment by marionf** [comment]
@sarjon 

> If you open order view (legacy), does it show "Tax included" or "Tax excluded"?

It shows also tax included instead of tax excluded

**Comment by sarjon** [comment]
@marionf I think it's not related to the setting you have changed.

**Comment by marionf** [comment]
Yes, but maybe it should @MatShir wdyt ?

**Comment by matks** [comment]
@marionf I'm a bit confused here, can we write down what needs to be done ?

**Comment by MatShir** [comment]
> @marionf I'm a bit confused here, can we write down what needs to be done ?

I'm on it ;)

**Comment by MatShir** [comment]
> Stock location is empty when product has combinations with stock location
> 
> ![capture d'écran_2093](https://user-images.githubusercontent.com/13449658/67304012-86f5d980-f4f3-11e9-9522-e777e783735b.png)
> 
> ![capture d'écran_2094](https://user-images.githubusercontent.com/13449658/67304036-8e1ce780-f4f3-11e9-90e9-bd6563abbd01.png)
> 
> And I have the errors below when I click on "Open details"
> 
> Order with a product without image:
> 
> ![capture d'écran_2095](https://user-images.githubusercontent.com/13449658/67304091-9d039a00-f4f3-11e9-955c-b1a089d00822.png)
> 
> Demo orders:
> 
> ![capture d'écran_2097](https://user-images.githubusercontent.com/13449658/67304960-e99ba500-f4f4-11e9-881e-c3ef080c40a4.png)
> 
> I defined a shipping address different of the delivery address
> The shipping address firstname and lastname are not good
> (Same thing if I change the firstname and lastname for invoice address)
> I think it takes the firstname and lastname of the customer instead of the address
> 
> ![capture d'écran_2101](https://user-images.githubusercontent.com/13449658/67306558-78a9bc80-f4f7-11e9-9877-f71e73146e68.png)
> 
> ![capture d'écran_2099](https://user-images.githubusercontent.com/13449658/67306573-7f383400-f4f7-11e9-8271-cde2f6368933.png)

This must be fixed, it hasn't be done yet. 

For the tax included/excluded issue, it depends also on how the issue going to be fixed: [comment PR product list](https://github.com/PrestaShop/PrestaShop/pull/16150#issuecomment-550345968
)
- If you can't fix the client group display management in the order, we should all display on the product list with no tax column on the total price with tax label. So the total price by-product should be the same as in the order product list (whenever the taxes are included or not). 
![image](https://user-images.githubusercontent.com/43613217/68309468-c3f2cc00-00ae-11ea-8df6-36d110320434.png)

- If you can handle the display per client group, we still won't have the tax column but the total price with the right label. So label "tax included" if the client group is flagged as tax excluded and "tax excluded" in the order case.
![image](https://user-images.githubusercontent.com/43613217/68309746-28159000-00af-11ea-9f61-23ce24d4c401.png)

@matks

**Comment by matks** [comment]
For the record: every feedback from Marion was fixed by Sarunas in Some fixes to Orders page #16075
Only remaining issue: the price, whether it should be displayed with or without taxes

**Comment by matks** [comment]
Last issue is to be fixed in https://github.com/PrestaShop/PrestaShop/pull/16319. Please see "how to test" description for an accurate description of the expected scenario.
