### ISSUE TITLE
Right click "open in new tab" over the full width table line

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#14736]
**USER STORY**
As a merchant, I want to able to open in a new tab my the orders from the order list.

**WHY**
Merchants cannot open their orders in another tab even if the action is possible through the order view button. Making the entire line clickable would provide a better user experience and increase merchant productivity.

**SPECIFICATION:**
A right-click on any order then "open in a new tab"

**Comment by MatShir** [comment]
Hello @TristanLDD,
Through the user experience perspective, what do you think to put the right-click "open new tab" the default action in a left click?

**Comment by matks** [comment]
Looks like it's not as easy as "make it a big link" 🤔 according to https://html.spec.whatwg.org/multipage/tables.html#the-tr-element

We cant put a link on a `<tr>`, but we can put it in a `<td>`

**Comment by matks** [comment]
According to @eternoendless we might track the following trick: put a large `<td>` which would contain the whole row and inside it, put one `<td>` for each column

So, before:
```
<tr>
  <td></td> <td></td> <td></td>
</tr>
```
After:
```
<tr>
   <td>
     <td></td> <td></td> <td></td>
  </td>
</tr>
```

this would allow us to make the row clickable without javascript

**Comment by MatShir** [comment]
As discussed with @jolelievre @matks To compleat the feature, we dig out this one #16455 from another bigger issue. It is a "nice to have", so to be done after all the "must" feature (High) are been reviewed & merged before the feature freeze.

**Comment by jolelievre** [comment]
I'm not sure we can close this one, it was replaced by "Left click" + "Bulk open in tab" in this version

But the initial "Right click" feature hasn't been postponed, it is planned to add it in the next version

**Comment by colinegin** [comment]
Hello @MatShir what should we do with this issue ?

**Comment by colinegin** [comment]
ping @MatShir

**Comment by MatShir** [comment]
This is a general problem on all our listing pages. The problem has therefore been removed from the order page project to be addressed in a more global project.
One of the possible solutions is to redesign the right-click interface has on Gmail for example.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team friendly reminder :sweat_smile: what is the status of this issue?

**Comment by MatShir** [comment]
I close this issue. I create a new ticket #22800. This improvement is a big improvement that won't be planned for now will stay  TBS until it is prioritize
