### ISSUE TITLE
Number of product not ok after selecting filters

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14734]
**Describe the bug**
Number of product not ok after selecting filters

**To Reproduce**
Fresh install, install faceted search module
Go to home category in FO
Select the filter composition: coton (2)
You have 2 results as indicated, it's ok 
Select the filter property: 120 pages (3)
You have 0 results, it's not ok it should be indicated 0 in parentheses for 120 pages after selecting the first filter, or better do not show this filter.

**Screenshots**
![capture d'écran_1768](https://user-images.githubusercontent.com/13449658/61456439-50de1200-a966-11e9-9e0e-086aa79ea2f5.png)

**Additional information**
PrestaShop version: 1.7.6.0
Faceted search version: 3.1.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Is it the issue reported here: https://github.com/PrestaShop/PrestaShop/issues/14658

Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/14658

**Comment by PierreRambaud** [comment]
Release in 3.2.0
