### ISSUE TITLE
Date picker calendar is shown in wrong place when rendered downwards in grid

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#14748]
**Describe the bug**
When page has enough content to scroll down and make the picker render downwards, a gap appears between input and the calendar. This could be associated with #14401.
**To Reproduce**
1. Go to Sell > Catalog > customers
2. Click on 'set required fields for this section' to expand the content
3. Scroll down so that your page top would be touching with list filters row (screenshot 1).
4. Click on date filter
5. See the gap between calendar and input (screenshot 2)

**Screenshots**
1. ![Screenshot from 2019-07-18 16-42-47](https://user-images.githubusercontent.com/31609858/61462352-26e31a80-a97b-11e9-815a-0c2cc2d217bf.png)
2. ![Screenshot from 2019-07-18 16-45-21](https://user-images.githubusercontent.com/31609858/61462551-788ba500-a97b-11e9-847b-364893696e79.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I have the same issue with PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/61464000-6e62aa00-a96d-11e9-9142-48ee0244b74d.png)

It is Ok before the migration
![image](https://user-images.githubusercontent.com/16067358/61464064-8a664b80-a96d-11e9-9f84-1bb54ec467d9.png)

So, it is a regression.
I’ll add this to the debug roadmap.
Thanks!

**Comment by kpodemski** [comment]
@khouloudbelguith could you please add to this bug one more little thing? these date fields should not have autocomplete enabled, it's annoying when autocomplete overlay is on the top of date picker :)

**Comment by khouloudbelguith** [comment]
@marionf, @colinegin what do you think of @kpodemski's request?

Thanks!

**Comment by colinegin** [comment]
@matks what do you think ?

**Comment by matks** [comment]
@kpodemski you mean "when I open the datepicker, the default value should be today" ?

**Comment by matks** [comment]
@kpodemski 🆙 😄 
If we wait too long, 1.7.6.1 will be shipped before we fix this bug 😅

**Comment by eternoendless** [comment]
I think he means to disable the autocomplete feature on that field via the `autocomplete="off"` HTML attribute
