### ISSUE TITLE
[ORDER LIST] - A dropdown button for the order's status to modify it

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#14741]
**USER STORY**

As a merchant, I want to change the status of the command quickly for a single order in the order list.

**WHY**

Some merchants do not change the status of orders already processed due to time constraints that cause frustration to their customers. 
Facilitating the status change quickly from the list will allow the merchant to change the status of their order without leaving orders untreated and to handle all their orders more easily.

**SPECIFICATION**

When the mouse hovers over command, the symbol of the drop-down list is displayed in the label of the status of the command next to the status name. 
When the user clicks anywhere on the label the drop-down list with all statues is displayed.
Selecting one of the order statuses updates the order status with the one selected.

**DESIGN**
https://invis.io/YKTGGFZAMCB#/376713836_Order_List_-_Status_Hover_Dropdown
![change order status in order list](https://user-images.githubusercontent.com/43613217/63529139-7ed5e980-c504-11e9-9553-72c64fa92163.png)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15908
