### ISSUE TITLE
Export (from France) - Amount VAT 

### ISSUE THREAD

**Issue by CarPrc** [PrestaShop/PrestaShop#14746]
**Describe the bug**
For DOM-TOM and Switzerland, we do not have to charge VAT. Prestashop handles it well.
But if a person (DOM-TOM or Switzerland) choose a promo product, the total amount is not calculated well. Indeed, Prestashop subtracts a discount TTC of the product HT. Which is not acceptable.

Example:
- product of 50 € HT / 60 € TTC
- with a discount of 10 € HT / a discount of 12 € TTC

The customer (DOM-TOM or Switzerland) should pay 50 - 10 = 40 € HT
But Prestashop invoice 50 HT € - 12 € TTC = 38 €

Which is a mistake.

**To Reproduce**

**Screenshots**

**Additional information**
PrestaShop version: 1.7.5.2
PHP version:

**Comment by khouloudbelguith** [comment]
Hi @CarolinePrc,

Thanks for your report.
Your issue is similar to this ticket: #14537?

Thanks!

**Comment by CarPrc** [comment]
Hi @khouloudbelguith , no it's not similar.
Thanks !

**Comment by khouloudbelguith** [comment]
Hi @CarPrc,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1y31TEokZO2q2EIC8ZlIpz0YXBZ7WoK-g/view
Thanks to check & feedback.

**Comment by CarPrc** [comment]
Thanks @khouloudbelguith 
The issue is when the discount is in the product sheep, not in "cart rules"
:)

**Comment by khouloudbelguith** [comment]
@CarPrc, thanks for these clarifications.
In my case, I did not manage to reproduce the issue also with PS1.7.6.0 & PS1.7.5.2.
It is OK in the invoice.
I attached a screen record
https://drive.google.com/file/d/1S3xmUrkGW1qTkhJ4SDVMUaWAHG1KMs9Q/view

Thanks!

**Comment by CarPrc** [comment]
Thanks @khouloudbelguith but the issue is when a customer buy a product from Szwizerland or from the dom-tom ;)

**Comment by khouloudbelguith** [comment]
@CarPrc, the "Geolocation by IP address" option is enabled in your case?
Did you create a specific price "Country"?

Thanks!

**Comment by CarPrc** [comment]
@khouloudbelguith Yes and yes. The issue is the amount of the invoice.

**Comment by khouloudbelguith** [comment]
@CarPrc, it is OK also in my case.
I tried to buy a product from Switzerland & it is OK.
I attached a screen record
https://drive.google.com/file/d/1KcNnGrgRQYf4mFymPbSvo4DUGl89YZBZ/view

Thanks!

**Comment by CarPrc** [comment]
@khouloudbelguith , we don't have ton charge VAT to Swizerland and dom tom, it's illegal 

thanks a lot

**Comment by khouloudbelguith** [comment]
@CarPrc, In my screen record, I didn't change my TVA.

Thanks!

**Comment by CarPrc** [comment]
@khouloudbelguith yes but we don't have to charge VAT.
VAT must not appear on the invoice

Thanks a lot for your help

**Comment by khouloudbelguith** [comment]
@CarPrc, so you need to disable the display of the tax block in the invoice?
![image](https://user-images.githubusercontent.com/16067358/61544021-76d5e600-aa3c-11e9-93d0-06da989dea70.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @CarPrc,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
