### ISSUE TITLE
Some images are being loaded from the SCSS directory

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#14757]
When we tried removing the SCSS directory from the BO new theme in the production zip release, we realized that some images were being loaded from there, and therefore weren't available anymore.

This means that either the image extraction webpack plugin is not working properly for some image, or that some of them are being referenced directly in the code.

See [this comment](https://github.com/PrestaShop/PrestaShop/pull/14579#issuecomment-510134341) for more information.

**Comment by Progi1984** [comment]
I confirm that the plugin doesn't work for images referenced directly in code (img tag). 

[EDIT 17:53] That seems normal because webpack just analyzed js or vue files.
