### ISSUE TITLE
Allow Doctrine Query Builder to set a native SQL query

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#14755]
**Is your feature request related to a problem? Please describe.**
Currently, in Grids you can't set your own raw sql query, you have to manage sql parts one by one, making the process of migration of old grids to new ones painful.

Also, optimizing the query is difficult

**Describe the solution you'd like**

Add a new state to the query builder named "RAW" and add a setSQL() function.

**Describe alternatives you've considered**

None, I'm the best alternative you got :p

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!
