### ISSUE TITLE
Translation search feature seems a bit broken

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#14756]
Using clean 1.7.6 installation.

Go to Translations and search for instance for:
"Order with"

This gives 4 results (all of them for the string "Order with an obligation to pay".

The problem is that only the result that is visible is for the LegalCompliance module. The other 3, I have no way of navigating to. I would like to translate the one in Shop/Theme/Checkout but there is no quick way to find it.

**Comment by khouloudbelguith** [comment]
Hi @johanlantz,

In the newt version PS1.7.7, we added a new improvement to add a disable visual effect on translations.
Heres' the PR: https://github.com/PrestaShop/PrestaShop/pull/12997 to add this feature.

Thanks to check & feedback.

**Comment by johanlantz** [comment]
I think it is a bit worse than I initially thought. I filed another PR with the latest issue that is that only some of the translatable strings are shown.

As a follow up to this issue, I can just see that even the string that I initially found by navigating the translation tree is no longer showing up either. I could find translation files in the var/cache folder where this previously translated string was visible but it does not show up in the backoffice anymore.

Also I see that in my theme folder, empty cataloges have been created but there are no translation files there. Should they be?

**Comment by johanlantz** [comment]
As indicated in another thread, lets close this one for now pending more investigation. The theme translation started to work for some magical reason.

**Comment by khouloudbelguith** [comment]
@johanlantz, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
