### ISSUE TITLE
Add internal order note

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14753]
**Is your feature request related to a problem? Please describe.**
Employees often need to write down some information to a single order, for them and other employees to know, what's the status of the order, because order status is not explanatory enough. 

Customer note is not very useful for this. When customer orders something for a second time, you see the previous note and could confuse you a lot. Customer note is only good for entering "good customer"/"asshole customer".

**Describe the solution you'd like**
Add a field with internal note on the order page.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @colinegin, @marionf what do you think?

Thanks!

**Comment by MatShir** [comment]
@Hlavtox,
This is something to be done! but for now, we will just put a clearer wording for the private message to be used as an internal order note. It will integrate into a 2nd part of the order project after the 177.

**Comment by kmorgen** [comment]
Noticed the new order note field available in PS 1.7.8 which is fine. 
However it is filling up and getting a bit confusing with now 3 internal notes fields?!

If one is for general customer notes (being visible on all orders from this customer), and the new one is a order note (only visible for the current order), then what is the purpose of having a check box in the customer message field too?

Maybe better to remove this check box option, as the purpose of this section is for communicating with the customer. I guess in many cases one might forget to check this box, which mean the customer will never get the message.

![Screenshot](https://user-images.githubusercontent.com/4300688/141971993-ecef06d2-9f6e-4f71-85b2-aa1098b8ecb0.jpg)

**Comment by MatShir** [comment]
It makes sense @kmorgen, if you have the technical knowledge or find someone that could don't hesitate to propose a pull request ([find more information here](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/)). We will be happy to review your contribution to the PrestaShop core.
