### ISSUE TITLE
What nginx, mysql and php settings does the site use demo?

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#14758]
![Screenshot_1](https://user-images.githubusercontent.com/6318282/61498806-293f8600-aa08-11e9-8f7e-f2406524fd5a.jpg)

Nice connect and TTFB. Please share a secret.

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Sorry, but you want to know the exact information about the configuration for the demo shop?

Thanks!

**Comment by TemKaSD** [comment]
Yes. nginx and mysql.

**Comment by khouloudbelguith** [comment]
@TemKaSD, this shop: http://demo.prestashop.com/#/en/back?
![image](https://user-images.githubusercontent.com/16067358/61528799-9c042d80-aa17-11e9-95fd-675b1968b739.png)

Thanks!

**Comment by Quetzacoalt91** [comment]
Hi there,

Each shop is running in its own container, from the Docker image [prestashop/docker-internal-images](https://hub.docker.com/r/prestashop/docker-internal-images/).
There's a apache with mod-php enabled in it, and a mysql server running in background.

We reduced the memory consumption with a light [MySQL configuration](https://github.com/PrestaShop/docker-internal-images/blob/master/1.7/config_files/build/my-minimal.cnf).

About the Nginx you saw, that's a simple proxy redirecting the request to the container specified by the subdomain. :)
