### ISSUE TITLE
In faceted search, Manufacturers are displayed using ordering by id, instead of name

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#14769]
For other filters in the faceted search, items can be sorted via BO, for the manufacturers this is not available.

PS 1.7.2.4

**Comment by khouloudbelguith** [comment]
Hi @nielsverhoeven84,

Could you please provide me the exact steps to reproduce the issue.
Did you the latest version ps_facetedsearch v3.1.0.?
Thanks!

**Comment by nielsverhoeven84** [comment]
Hello @khouloudbelguith 
I'm using the latest version (3.1.0)

On https://www.newvanherck.be/ you can see the filter

The manufacturers are in the section of `Merk`
Currently it is not possible to sort those items

**Comment by khouloudbelguith** [comment]
@nielsverhoeven84, yes you are right.
I have the same behavior as you, we can not change the position of the brands.
They are sorted by id in the ps_facetedsearch module.
In the Brands Page => they are sorted by name.
Ping @colinegin, @marionf what do you think?

Thanks!

**Comment by nielsverhoeven84** [comment]
That's why I added it as a feature . Is it possible via a simple modification?

**Comment by marionf** [comment]
Hello @nielsverhoeven84 

To be sure to well understand, you want brands to be displayed in front-office in faceted search (image below) by ascending name ?

![capture d'écran_1832](https://user-images.githubusercontent.com/13449658/61729311-35fd0a80-ad77-11e9-93e7-9d3ccf753a39.png)

**Comment by nielsverhoeven84** [comment]
@marionf 

Yes indeed, in your example AAA should be above BBB instead of below it.
