### ISSUE TITLE
[EPIC] Issue Product page - Basic settings tab 2/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14763]
## Issues in **basic settings tab** sorted by priority high to low :

**Must-Have**
- [x] #9945
- [x] #12773 (#9631)
- [x] #30219

**Should-Have**
- [x] #9752
- [x] #9625
- [x] #9626
- [x] #11587
- [x] #9617

**Improvement**
- [x] #20331
- [x] #16306

**Nice to Have**
- [x] #15383
- [x] #9631
- [x] #10459
- [x] #16004 
- [x] #9960
- [x] #13751
- [x] #17822 

**New feature**
- [x] #18823 

**New issues to prioritize** 
- [x] #18636
- [x] #19022
- [x] #25582
- [ ] #26566

## Fixed
- [x] #26519
- [x] #23255
- [x] #9678
- [x] #16308
- [x] #13513
- [x] #17957
- [x] #9668
- [x] #14955
- [x] #16415
- [x] #20035
- [x] #14052
- [x] #15018 (PR: #15035)
- [x] #12061
- [x] #12832
- [x] #14985 (#9668)
- [x] #13698 - #19281
- [x] #22144
- [x] #19524

**Comment by marionf** [comment]
### - Issues in **basic settings tab** sorted by priority high to low :

**Must-Have**
- [ ] #9945
- [x] #12773 - #9631
- [x] #14985  - #9668
- [ ] #16306
- [ ] #13698

**Should-Have**
- [ ] #9752
- [ ] #9625
- [x] #12832 - Multistore
- [ ] #9626
- [ ] #11587
- [ ] #9617
- [x] #15018 PR: https://github.com/PrestaShop/PrestaShop/pull/15035
- [x] #12061

**Improvement**
- [x] #14052
- [ ] #20331
- [x] #14955
- [x] #16415

**Nice to Have**
- [x] #9668
- [ ] #15383 - Multistore
- [x] #17957
- [x] #9631
- [x] #13513
- [x] #10459
- [x] #16004
- [ ] #9960
- [x] #20027
- [x] #9678
- [x] #16308

**New feature**
- [x] #12773
- [x] https://github.com/PrestaShop/PrestaShop/issues/18823

**Comment by sarjon** [comment]
Question https://github.com/PrestaShop/PrestaShop/issues/10632#issuecomment-515981529

**Comment by MatShir** [comment]
new issue to prioritize: https://github.com/PrestaShop/PrestaShop/issues/18636
