### ISSUE TITLE
Issue when we delete a supplier in multistore

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#14762]
**Describe the bug**
If a supplier is available for all shops and I delete the supplier for Shop A when I try to edit in Shop B an error page appear

**To Reproduce**
1. Create two shops 
2. Go to Brands & Supplier
3. Create a supplier for all shops
4. Then delete this supplier for shop A
5. Edit the supplier in shop B 
6. See the error 

**Screenshots**
https://drive.google.com/file/d/1lsyNnpeGF0adJeC2liNBtSLZBUTnI0pX/view

**Additional information**
PrestaShop version: 1.7.7
PHP version: 7.1

**Comment by marionf** [comment]
If you create a supplier for all shops, then select only one shop in the context and delete the supplier it should be deleted only for the selected shop in the context.
If you select "all shops" in the context and delete the brand, it should be deleted for all shops.

It's working like this for brands.

**Comment by atomiix** [comment]
I think this issue has been fixed because I can't reproduce it but now, following the exact same steps I got
> The address for this supplier have been deleted

when trying to edit a supplier.

@sarahdib, do you confirm?

**Comment by sarahdib** [comment]
@atomiix I got the same error message : The address for this supplier have been deleted.

@colinegin  What is the wanted behavior : 
1. Create two shops 
2. Go to Brands & Supplier
3. Create a supplier for all shops
4. Then delete this supplier for shop A
5. Edit the supplier in shop B 
6. Error message who indicated that the supplier is deleted 

![Capture d’écran 2019-10-25 à 10 37 45](https://user-images.githubusercontent.com/3034677/67556448-80de4380-f713-11e9-9f53-2c3b84899ab2.png)

The supplier is still there but we can't edit just delete.

**Comment by marionf** [comment]
If you create a supplier for all shops, then select only one shop in the context and delete the supplier it should be deleted only for the selected shop in the context.
If you select "all shops" in the context and delete the brand, it should be deleted for all shops.

> Create two shops
Go to Brands & Supplier
Create a supplier for all shops
Then delete this supplier for shop A
Edit the supplier in shop B
Error message who indicated that the supplier is deleted

There shouldn't be an error message which indicate that the supplier is deleted as it has been deleted for the shop A and not for the shop B, you should be able to edit it in shop B

**Comment by atomiix** [comment]
Actually, the error message is not that the supplier has been deleted but that the **address** of the supplier we are trying to edit has been deleted.

But I guess this should not happen either.

**Comment by marionf** [comment]
> But I guess this should not happen either.

Yes :+1:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16123

**Comment by darkf3d3** [comment]
I just discovered that into my shop there's some "broken" supplier because of the missing address.
There's a way to fix them? PS doesn't allow me to open these suppliers, so there's no way to add the address again.
