### ISSUE TITLE
Making the search tolerance for mistakes configurable 

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#14766]
### Problem:
This feature request follows this pull request:
https://github.com/PrestaShop/PrestaShop/pull/14428

This PR allows to get search results even if we mistyped the keyword.
This is a very nice improvement, but it could be costly performance wise, the new mysql query makes a costly "group by", and then php's levenhstein function is used up to twice per query result... and this whole process is to be multiplicated by the number of words the user typed in the search field. 

### Solution:
It would be nice to make this configurable in the back office, at least a on/off mechanism, while stating in the option's description that this feature could be costly on large databases, and even more if there are many products with similar names.

### Alternative:
An alternative to the on/off option, would be to choose the level of tolerance:
**intolerant** => off
**tolerant** => costly 
**more tolerant** => costlier
(because the more tolerant it is, the more results could have to be treated by php's levenhstein function)

**Comment by khouloudbelguith** [comment]
Ping @marionf, @colinegin what do you think?

Thanks!

**Comment by colinegin** [comment]
Hello @matthieu-rolland, thanks for your warning !
Is there any other technical alternative with less impact in terms of performance ?

**Comment by colinegin** [comment]
Hello @matthieu-rolland ,

coud you check @Lathanao's new commits to see if his PR is less impacting in terms of performance ?

Have a nice day,

Coline

**Comment by matthieu-rolland** [comment]
Hey @colinegin 

Yes, @Lathanao did some very valuable improvements to his PR, especially the part taking into account the size of ps_search_word.

I think it is still important to make that configurable, just in case some end user has a very slow DB and would prefer not to have this feature.

It could be something like that (just an idea, it has be reworded), what do you think ?

Search tolerance:

**intolerant** => off
**tolerant** => costly
**more tolerant** => costlier

**Comment by matthieu-rolland** [comment]
another way would be to have a simple  on / off.

**Comment by colinegin** [comment]
This is great news ! 
I would rather go for the on / off option, to keep it simple.
My recommendation would be to have the feature on ON by default, but I would like to be sure this won't cause performance issues on most stores.
@sarahdib when you will test this PR, could you try to test it with different scenarios to see if there are any differences in terms of perf ?

**Comment by matks** [comment]
Hi @matthieu-rolland what's the status of this issue? We did not make any progress?

**Comment by matthieu-rolland** [comment]
This issue can be closed, we were still discussing how the feature would be implemented, since then the PR was merged in the end of 2019.
