### ISSUE TITLE
As a user making an upgrade, I want to be able to disable my overrides before the upgrade to ensure its success.

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14781]
**As a user making an upgrade, I want to be able to disable my overrides before the upgrade to ensure its success.**

1. We should add a toggle "Disable all overrides" in Advanced Parameters > Performance" in the "upgrade options" block.
2. When this option is enabled or disabled from the module, the same option in "Advanced Parameters > Performance" is changed accordingly.
3. By default, the toggle should be on the same state at the same toggle in "Advanced Parameters > Performance"

⚠️ Please note that the feature to [disable overrides in Advanced Parameters > Performance](https://github.com/PrestaShop/PrestaShop/issues/14596) is not working. We should fix this issue first

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

**Comment by ghost** [comment]
Ping @marionf i work on this one

**Comment by ghost** [comment]
Hello @marionf 

How about adding a link / button to disable the override directly from the module?

Here a merchant looks at the check list, he will once activate maintenance, then go to performance to deactivate overrides, then he will go back to perfomance to deactivate modules...

Currently there are buttons to deactivate or disable the module directly.

For the moment my PR respect the mockups but i think it's a good idea

**Comment by marionf** [comment]
Hello @okom3pom 

Yes, the idea is to add a toggle in the "upgrade options" block allowing to enable/disabled overrides
The mockups are now up to date:

<img width="889" alt="Capture d’écran 2021-10-08 à 14 34 03" src="https://user-images.githubusercontent.com/13449658/136557566-59375ec6-e784-46f2-96cd-7fc52bbafdc8.png">
