### ISSUE TITLE
Manage installation & upgrade of natives modules

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14784]
**As a user, I want to be able to benefit from the latest version of the natives modules I use** (upgrade)
- If the native module version included with the core is HIGHER than the one installed before the upgrade, then the module upgrade process should be triggered in order to ensure that the module is properly upgraded (this might already be the case). For upgraded modules, **the configuration should be kept**.
- If the native module version included with the core is LOWER than the one installed before the upgrade, then the module should be left untouched (and certainly not downgraded!)

**As a user, I want to be able to benefit from the new natives modules** (installation)
- The new natives modules (which did not exist before and that are available from the version to which the user upgrades his store) should be installed. 

**As a user, I do not want after the upgrade of my store to have natives modules that I had uninstalled**
- The natives modules that have been uninstalled should not be reinstalled during the upgrade of the store. This would require storing which modules have been uninstalled to not reinstalled them.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team , what is the status of this feature? is it **`To Do`**?
