### ISSUE TITLE
[AUTOUPGRADE] Add upgrade history in the 1st step of the upgrade process

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14783]
In the 1st screen of the module configuration, we need to add a listing of all upgrades that were processed before. It is possible to click on a specific upgrade to have access to the back up which was done during this upgrade and see the list of modules which were disabled.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team , what is the status of this feature? is it **`To Do`**?

**Comment by LouiseBonnard** [comment]
Hi @hibatallahAouadni, it is part of the old project to rework the auto-upgrade module. I'll add the _PM approved_ label but leave them as TBS so that it can be (re)challenged and specified [here](https://github.com/PrestaShop/prestashop-specs/tree/master/modules) once the topic back on track.
