### ISSUE TITLE
Errors on Front Office after upgrade

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#14789]
Hello, I have just upgraded Prestashop to the letest version. I have noticed that when I select Debug mode, I have an error in my Front Office. When the debug mode is turned off there is no problem and shop is working with no problem. I have multishop with 2 different theme. This error appears only in one shop. The FO in the second shop works with no problem.

Here's the errors I have: https://drive.google.com/file/d/1jp9LOBxw_k8JiSAy-3N_L-XBCrpENL5A/view

Here are some details about the shop with the issue:
Prestashop 1.7.6.0
PHP version: 7.2.19
Theme: bentriz (free theme downloaded from here: https://www.hiddentechies.com/bentriz-responsive-theme-prestashop.html). I have the latest version. I use a child theme with minor changes.

I have tested this theme on a fresh Prestashop and I did not have any issues so I am clueless what might cause these errors. I would like to avoid configuring the shop's theme again. Can you help me?

**Comment by Matt75** [comment]
Problem come from your module tawkto, you should contact the author to retrieve latest version of this module.

**Comment by banan44** [comment]
Hey Matt75. Thnks for your answer. You are right. Once I deactivated tawk.to module the errors are not present in debug mode anymore. That's weird that I have these errors only in one site and the second one with different theme works without any error while in debug mode.

**Comment by Matt75** [comment]
This module is probably not activated on same hooks.
You can compare that in Appearance > Positions, use filter to display only registered hooks for this module.
PHP version can also be different or PrestaShop version too.
But the main problem is this module contain errors.

**Comment by khouloudbelguith** [comment]
Hi @banan44,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
