### ISSUE TITLE
Can't use the back-office, redirect to login page, session token

### ISSUE THREAD

**Issue by ValerioFoddai** [PrestaShop/PrestaShop#14796]
**Describe the bug**
After the login, I'm trying to use the back-office, but if I select some option on the menu, the system redirects me to the login page.

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version:  7.1.30

**Comment by khouloudbelguith** [comment]
Hi @ValerioFoddai,

Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
if ($this->context->cookie->last_activity + 900 < time()) {

By this:

if ($this->context->cookie->last_activity + 3600 < time()) {

Thanks to check & feedback.

**Comment by brk34** [comment]
Hi @ValerioFoddai, @khouloudbelguith 
Go phpmyadmin
Find your Prestashop's database
find pr_configuration table 
Choose "500" in number of rows 
CTRL+F and copy paste there "PS_COOKIE_CHECKIP" 
There will write "NULL" / "1" in column of value
double click there and write "0" and click to enter key

Your problem fixed

**Comment by khouloudbelguith** [comment]
Hi @ValerioFoddai,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
