### ISSUE TITLE
When Generating Product Combination Reference Field is not Created

### ISSUE THREAD

**Issue by Digitalfastmind** [PrestaShop/PrestaShop#14791]
**Bug Description**
When creating product combinations in the past the product Reference was copied across all the combinations, now it's not....i don't know if it may be considered a bug as in theory sometimes different combinations should have different references, but sometimes they don't.

**To Reproduce**
1. Create a new product with combinations
2. Generate a product combination Ex. size S-M-L
3. Check the Product reference for the created Combinations, it's empty

**Comment by khouloudbelguith** [comment]
Hi @freeman78ita,

I tried with PS1.7.4.4, PS1.7.5.2 & PS1.7.6.0.
All these versions, have the same behavior, the reference is not copied after regeneration of the combinations.
https://drive.google.com/file/d/1FDB8YJP1o6HBCsgUmM-EgynUMcr6BnFU/view
What is the exact version PrestaShop did you use before?

Thanks!

**Comment by Digitalfastmind** [comment]
Hi,Last 1.6! 
>Il 22 lug 2019 11:00, khouloudbelguith <notifications@github.com> ha scritto:Hi @freeman78ita,
I tried with PS1.7.4.4, PS1.7.5.2 & PS1.7.6.0.
All these versions, have the same behavior, the reference is not copied after regeneration of the combinations.
https://drive.google.com/file/d/1FDB8YJP1o6HBCsgUmM-EgynUMcr6BnFU/view
What is the exact version PrestaShop did you use before?
Thanks!

**Comment by khouloudbelguith** [comment]
@freeman78ita, thanks for your feedback.
Yes, I tried with PS1.6.1.2.4, when I click on the "Generate these combinations" => the reference is copied to all the combinations created.
@marionf, @colinegin what do you think? can we add this feature to PS1.7?

Thanks!

**Comment by marionf** [comment]
Hello @freeman78ita 

As you said, you can have a global reference for the product and a different reference for each combinations, so I am not sure it's a good idea to do that.
Furthermore, if you have the same reference as the product for all combinations, you can select all combinations and assign them the same reference thanks to the bulk action

![capture d'écran_1839](https://user-images.githubusercontent.com/13449658/61795023-c80e1d00-ae22-11e9-9e3f-8d985aa317ea.png)

**Comment by Digitalfastmind** [comment]
Hi @marionf , good point but this is a "next" step when creating the combinations.
-Step1 - Create combination
-Step2 - Bulk assign
The "risk" is to create empty reference for combinations, so maybe it would be best to keep at least it filled with the same instead of having the field empty.

**Comment by marionf** [comment]
It's a problem if you don't want the same reference for your combinations because until changing them you have a bad reference. I think having nothing is better than having a wrong reference

**Comment by Digitalfastmind** [comment]
yes it can be, but usually a combination is part of a product itself, usually the reference is the same (al least in my experience) but BARCODES changes. So you have like :
Gren cup ref. 12345
Green Cup size LARGE - same ref - barcode 34234234234L
Green Cup size MEDIUM - same ref - barcode 34234234234M
But having no Reference is worst in my eye :)

**Comment by marionf** [comment]
Yes, I understand but like explained some merchants have a different reference for each combination
So, we can't do that
