### ISSUE TITLE
RouteNotFoundException

### ISSUE THREAD

**Issue by lukaszlan** [PrestaShop/PrestaShop#14799]
Can't login to Admin panel.

PrestaShop 1.7.5.2
PHP 7.1

Unable to generate a URL for the named route "admin_common_notifications_ack" as such route does not exist.

Router->generate('admin_common_notifications_ack', array(), 0)
in src/PrestaShopBundle/Service/Routing/Router.php (line 49)
    /**     * {@inheritdoc}     */    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)    {        $url = parent::generate($name, $parameters, $referenceType);        $token = $this->tokenManager->getToken($this->userProvider->getUsername())->getValue();        return self::generateTokenizedUrl($url, $token);    }

Level	Channel	Message
DEBUG
08:55:20
doctrine	SELECT name FROM pre4478_module WHERE active = 1
INFO
08:55:21
php	User Deprecated: The "sensio_framework_extra.routing.loader.annot_class" service is deprecated since version 5.2
INFO
08:55:21
php	User Deprecated: The "Sensio\Bundle\FrameworkExtraBundle\Routing\AnnotatedRouteControllerLoader" class is deprecated since version 5.2. Use "Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader" instead.
INFO
08:55:21
php	User Deprecated: The "sensio_framework_extra.routing.loader.annot_dir" service is deprecated since version 5.2
INFO
08:55:21
php	User Deprecated: The "sensio_framework_extra.routing.loader.annot_file" service is deprecated since version 5.2
DEBUG
08:55:21
doctrine	SELECT name FROM pre4478_module WHERE active = 1
CRITICAL
08:55:21
php	Uncaught Exception: Unable to generate a URL for the named route "admin_common_notifications_ack" as such route does not exist.
DEBUG
08:55:21
doctrine	SELECT name FROM pre4478_module WHERE active = 1
CRITICAL
08:55:21
request	Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "admin_common_notifications_ack" as such route does not exist." at /home/rafawojt/domains/sklep.datacomp.com.pl/public_html/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 227

**Comment by khouloudbelguith** [comment]
Hi @lukaszlan,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to run this SQL query 

`select * from  ps_configuration where name LIKE 'PS_ROUTE%'` & provide me the result.
In my case, 
![image](https://user-images.githubusercontent.com/16067358/60026851-4a74b700-9694-11e9-9594-04f3ea108006.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @lukaszlan,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
