### ISSUE TITLE
Wrong category position returned by web service

### ISSUE THREAD

**Issue by johndoe1395** [PrestaShop/PrestaShop#14795]
When requesting a category from Web service, the "position" field is returned with a wrong value, so if you use this returned category and change eg. its name and post it back to the web service, the category's position changes.

Steps to reproduce:
1. Do a GET curl request to eg. (will return category "clothes" from demo presta store data)
   prestapi/api/categories/3
2. Check database ps_category for id 3 the position is 0.
2. Position returned in response is 5 instead of 0:

```xml
<position>
   <![CDATA[5]]>
</position>
```

Optionally you can also try to update:
1. Update category with:

```php

<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php
require_once("vendor/autoload.php");

define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://localhost/presta176');
define('PS_WS_AUTH_KEY', 'the key goes here');
require_once('PSWebServiceLibrary.php');
$webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);

$category_id = 3;

//
// Get existing categpry
//
$xml = $webService->get(array('resource' => 'categories', 'id' => $category_id));

//
// Get blank schema
//
$category = $xml->children()->children();

$category->name->language[0][0] = "New name";
unset($category->level_depth);
unset($category->nb_products_recursive);
unset($category->associations);

$opt['putXml'] = $xml->asXML();                  
$opt['id'] = $category_id;
$opt['resource'] = 'categories';
$xml = $webService->edit($opt);
echo "DONE";
```
2. Check category and it is now gone to the bottom because getting the existing category returned wrong position 5 instead of 0.

Now the position is 5, and if you try getting it again it will return again, wrong number, 6.

**Comment by khouloudbelguith** [comment]
Hi @johndoe1395,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
After updating the category via web service, the position of the category is changed to the bottom.
https://drive.google.com/file/d/1P2r2G4Wa7oHQIs1-eRD5tZBSuuMzWop1/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16431
