### ISSUE TITLE
Problems with saving (product changes, order items)

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#14793]
For a while now I cannot amend products changes like text or price and when I press save it says it was saved (green return meesage) but it was not saved. Front office still unchanged, relead product page shows all as per before the change. I experimented with clearing cache and sometimes helps but often not.  Now I have which looks like random problems with orders placed. The order is shown in back office but no products are show on the order, total price and carriage is shown. Payment is processed correctly and on the email from the payment provider I can see the products or have to look in the cart in the back office where products are shown before order was placed.

On an off I have been trying to find out what causes this but no luck. The webshop workes fine for visitors as we still receive orders. However incidentally without product details (happened 2-3 times now). However I cannut update the products which is becoming a pain. Can only change minor thing directly in the database but takes a lot of time to find the right item and field.
What can cause this?  Is this a php problem?

I don't use many third party modules. Only Redis Cache v1.0.13 (by Vopster), 301, 302, 303 URL Redirects - SEO v1.2.8 (by Linea Grafica) and Product Video Youtube  v1.0.1 (by Bonpresta) and a API modules that obtains order info for shipping.
PSP modules for our local payment system but we have used these for many years now without any problems.

I started my PS webshop in 2012 with PS v.1.4.9.0 and updated it in december 2017 to v.1.7.2.4 (using MigrationPro to do the update)  From the start only a minor problem that I could not changes the shipping charges weight/price tables but could do that directly in the database.
Untill the present problems I was quite happy with v.1.7.2.4

![afbeelding](https://user-images.githubusercontent.com/53129699/61585455-cbbc4e00-ab5b-11e9-9b0f-80b93a7c230d.png)

**Comment by khouloudbelguith** [comment]
Hi @frevab,

Thanks for your report.
Previously, we manage to reproduce a similar issue, if we have a reference field with a length greater than 32 chars, this issue is fixed in the PS1.7.6.0.
Here's the exact issue: https://github.com/PrestaShop/PrestaShop/issues/9955
Also, it could be similar to the problem of the meta description if it is more than 255 characters in the product then the changes are not saved reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9717 and fixed in the PS1.7.5 with this PR: https://github.com/PrestaShop/PrestaShop/pull/10446

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @frevab,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by frevab** [comment]
Since my original post I discovered that it was the Redis module that caused problems with saving any changes made in a product. I also discovered that the PHP version was end-of-life and also the SQL version needed updating. Perhaps the combination Redis-module, PHP version and MySQL version was causing the problem. 
My shop is on PS 1.7.2.4 , I have updated MySQL to 5.7.27 and available PHP versions are 5.4, 5.5, 5.6, 7.0, 7.1, 7.2 and 7.3
The PHP compatibility chart shows that the recommended PHP version for PS 1.7.4 is  7.1 however I get problems in back office when I want to open products or order details:
_Notice on line 4603 in file /home/....../public_html/....../app/cache/dev/classes.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php71) failed: Permission denied (13)__
When I scale back to PHP 5.6 this problem is gone. Then I only get error:
_Notice: Memcache::get(): Server 127.0.0.1 (tcp 11211) failed with: Connection refused (111) in /home/...../public_html/......./classes/cache/CacheMemcache.php on line 94__
but webshop works fine except for the Memcaching.
One thing I noticed is in Advanced Parameters > Information > Changed/missing files have been detected: Missing is ".eslintrc.json".

Why does it not work with PHP 7.1 ?


![AdvancedParameters-Information](https://user-images.githubusercontent.com/53129699/66785534-d463bc80-eedd-11e9-96b1-aab865e63307.png)
![error-products](https://user-images.githubusercontent.com/53129699/66785747-71bef080-eede-11e9-8116-21fb89f87b6a.PNG)

**Comment by roncarino** [comment]
> Since my original post I discovered that it was the Redis module that caused problems with saving any changes made in a product. I also discovered that the PHP version was end-of-life and also the SQL version needed updating. Perhaps the combination Redis-module, PHP version and MySQL version was causing the problem. My shop is on PS 1.7.2.4 , I have updated MySQL to 5.7.27 and available PHP versions are 5.4, 5.5, 5.6, 7.0, 7.1, 7.2 and 7.3 The PHP compatibility chart shows that the recommended PHP version for PS 1.7.4 is 7.1 however I get problems in back office when I want to open products or order details: _Notice on line 4603 in file /home/....../public_html/....../app/cache/dev/classes.php [8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php71) failed: Permission denied (13)__ When I scale back to PHP 5.6 this problem is gone. Then I only get error: _Notice: Memcache::get(): Server 127.0.0.1 (tcp 11211) failed with: Connection refused (111) in /home/...../public_html/......./classes/cache/CacheMemcache.php on line 94__ but webshop works fine except for the Memcaching. One thing I noticed is in Advanced Parameters > Information > Changed/missing files have been detected: Missing is ".eslintrc.json".
> 
> Why does it not work with PHP 7.1 ?
> 
> ![AdvancedParameters-Information](https://user-images.githubusercontent.com/53129699/66785534-d463bc80-eedd-11e9-96b1-aab865e63307.png) ![error-products](https://user-images.githubusercontent.com/53129699/66785747-71bef080-eede-11e9-8116-21fb89f87b6a.PNG)

Hi @frevab, how did you overcome your Redis problem about saving a product? Cheers

**Comment by frevab** [comment]
Hi Loris

 

Simple. I just stopped using Redis. J

 

Best regards

Freek
