### ISSUE TITLE
Configuration forms with missing multistore checkboxes

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#14804]
Type: tech-issue

List of pages that contains configuration forms with multistore checkboxes:

- [ ] Advanced Parameters > Administration
- [ ] Advanced Parameters > Email
- [ ] Advanced Parameters > Team > Employees
- [ ] Advanced Parameters > Database > SQL Manager
- [ ] Advanced Parameters > Database > Backup
- [ ] Advanced Parameters > Logs
- [ ] Advanced Parameters > Webservice
- [ ] Shop Parameters > General > Preferences
- [ ] Shop Parameters > General > Maintenance
- [ ] Shop Parameters > Order Setting
- [ ] Shop Parameters > Product Settings
- [ ] Shop Parameters > Customer Settings > Customers
- [ ] Shop Parameters > Customer Settings > Groups
- [ ] Shop Parameters > Contact > Stores
- [ ] Shop Parameters > Traffic & SEO > SEO & URLs
- [ ] Shop Parameters > Search
- [ ] International > Localization > Localization
- [ ] International > Localization > Geolocation
- [ ] International > Location > Countries
- [ ] International > Taxes > Taxes
- [ ] Shipping > Preferences
- [ ] Design > Theme & Logo > Theme & Logo
- [ ] Design > Email Theme (new in 1.7, multistore behavior might be needed)
- [ ] Design > Image Settings
- [ ] Customer Service > Customer Service
- [ ] Customer Service > Merchandise Returns
- [ ] Catalog > Products > Add / edit product
- [ ] Orders > Invoices
- [ ] Orders > Credit Slips
- [ ] Orders > Delivery Slips

When adding multistore behavior to forms, you check legacy first to figure out how it should behave.

**Comment by khouloudbelguith** [comment]
Related to: #9548.

**Comment by colinegin** [comment]
ping @marionf

**Comment by marionf** [comment]
Duplicate of #19304
