### ISSUE TITLE
Main menu module keeps deactivating itself

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#14816]
From some time I am experiencing problems with modules Main Menu v 2.1.1. It keeps deactivating itself on random occasions. I cannot find the exact situation that causes deactivating. Sometimes it happens after a few hours, sometimes right after activating and refreshing FO twice. I do not know what to do to reproduce this issue. Is there a log of activating/deactivating module to check what happened? I have multishop with 2 different themes. I use this module on both shops. 

Prestashop 1.7.6.0
PHP version: 7.2.19
Main shop uses following theme: bentriz (free theme downloaded from here: https://www.hiddentechies.com/bentriz-responsive-theme-prestashop.html). I have the latest version. I use a child theme with minor changes.

The second shop uses this theme: https://www.prestashop.com/forums/topic/984837-free-themes-watch-fashion-prestashop-17-theme/

**Comment by khouloudbelguith** [comment]
Hi @banan44,

I did not manage to reproduce your issue with PS1.7.6.0. & the ps_mainmenu module v2.1.1.
Multishop is enabled & I used your themes for the first shop & the second shop.
I attached a screen record
https://drive.google.com/file/d/1K_ChPvA0QJKfFzsGxpatQg9L-AyB4YoH/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by banan44** [comment]
Hi @khouloudbelguith 
I am sorry it took me so long to reply. I the link below you will find all information I could gather. I have checked the logs and I noticed one thing. When Main Menu module deactivated itself last time I was doing price indexing in Faceted Search. I got a PHP error - you will find it in error.log1 with date Sat Jul 27 00:00:52.970292 2019. 

I forgot to activated it again after that. I did that this morning and I had error while aticating twice. Please check the - it was Sat Jul 27 09:47:36.687304 2019 and Sat Jul 27 09:50:29.644518 2019

Debug mode on FO shows no errors. I took screenshots from SYmfony Profiler.

Link to all information: https://drive.google.com/open?id=1RUgx9ALskqPlWeVnS4dC0LbtTY_5b-D4

**Comment by khouloudbelguith** [comment]
In your error logs, you have this:

>edited

What is the exact version ps_facetedsearch module did you use?

>edited

In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```

>edited

You need to check this error with your host => you have some permissions issue.

Thanks to check & feedback.

**Comment by banan44** [comment]
> What is the exact version ps_facetedsearch module did you use?
> 
> >

The latest one. All my modules are up to date. 

I will discuss the isseas and php.ini with my host and let you know. In the meantime, can you edit your message and remove logs for security reasons?

**Comment by khouloudbelguith** [comment]
@banan44, Done.
Thanks!
Waiting for your feedback.

**Comment by banan44** [comment]
@khouloudbelguith my php.ini values has been increased to following numbers today:

php_value max_execution_time 300
php_value max_input_time 300
php_value memory_limit 800M

I will keep checking if the main manu deactivates today or not. I have spoken with the host admin about "AH01630: client denied by server configuration" orror that appeared for /vendor/phpunit. The said such file/folder like phpunit does not exist in that location. I have downloaded a fresh Prestashop and there is no such folder/file as well. Should I create it myself?

I am sending you yesterday's logs - main menu dissappeared yesterday a couple of times but I did not noticed when exactly. Can you check them? Link: https://drive.google.com/open?id=1kQE0CCn_ocGKn6pyubldNWEuuuG8QUsJ

Today I have no errors so far.

**Comment by khouloudbelguith** [comment]
@banan44, in your new log file, you have fatal errors in the cache files.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to run those command lines also to remove the cache:
```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Thanks to check and feedback.

**Comment by banan44** [comment]
@khouloudbelguith I did what you asked. For a few days the problem was not present anymore until yesterday. Main menu dissapeared twice between 22:00 and 23:00. I have attached new logs: https://drive.google.com/open?id=19n0hmkuv2QCZ_0RhYgAGfcgxXdRs6fmT

error.log - is for today
error.log.1 - is for yesterday (when the main menu dissappeared).

I have noticed that it dissapeared when I tried to updated Faceted Search to a new version. It updated after the third attempt. First time the update failed for no reason and I have not noticed that. I kept working with the offers and noticed the main menu is gone. I activated the main menu, then I noticed the updated failed. I updated the module for the second time but after a while the error occured. I checked FO and noticed the main menu dissappeared again. I tried to update the module for the third time. This time it was succesful and then I activated Main Menu and it is working until now. 

I am noticing that every time the Main Menu deactivates itself it connects with Faceted Search. I also have logs of 'Error on sending request' but I do not know how to solve them. I have these errors everyday.

**Comment by khouloudbelguith** [comment]
In the second file `lbshop.eu.error.log.1`, you have a PHP fatal error in the var/cache directory.
This is a cache issue, you need to clear cache from your shop.
In the other file, you have this error
>ReceiveAckHdr: backend reset connection: errno 104

I think it is related to your server, you need to check it with your host.

PS: in the two files, there is no error related to the ps_facetedsearch & main menu module.

Thanks!

**Comment by banan44** [comment]
These errors in var/cache directory happends very often. What might be the cause of that? I cleared cache like you asked me a couple of days ago. The var/cache directory was empty and fatal errors keeps happening.

I will ask host about ReceiveAckHdr: backend reset connection. I will let you know what they tell me. I realize there are no errors related to faceted search and main menu. I am just telling you what I noticed.

**Comment by khouloudbelguith** [comment]
@banan44, thanks!
Waiting for your feedback.

**Comment by banan44** [comment]
Hi @khouloudbelguith. Sorry it took me so long to reply. I have discussed the PHP error with my host. They said this is not correct behavior of the page. The reason may be, for example, that some process on the site that is taking a long time blocks the entire database, which means that other processes that are in queue can not be executed at that time. The number of available connections to the database are exceeded. They said I should analyze the processes on the site to find the root cause but I do not know how to analyze what causes this problems. 

BTW. Main Menu stopped deactivating. The only problem left is ReceiveAckHdr: backend reset connection: errno 104

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by banan44** [comment]
@khouloudbelguith Main Menu deactivated today again when I updated Revws module (free module from PS forum) to the lastest version. Here's the log with the error that occured. Can you check?

Link: https://drive.google.com/open?id=1i9w_cL8Q2fz-sm9nyqRQaREEkfdniRJL

**Comment by khouloudbelguith** [comment]
@banan44, Product Comments module?

Thanks!

**Comment by banan44** [comment]
@khouloudbelguith I have wacthed the behaviour of the Main Menu module for a few days. I noticed it deactivates everytime I update any module I have installed in my PS. It does not matter if this is an original PS module or third-party. Update means deactivation of Main Menu. When I clear cache on any shop, the Main Menu deactivates in all shops (currently I have 7 shops in Multistore option). All these problems started when I activated Multistore option. To be honest I am tired of activating Main Menu every few hours so I decided to deactivated it for good. For now I have installed Extra Content menu and created my own menu using html and css and selected to display it in navigation area. I am clueless what to do.

**Comment by khouloudbelguith** [comment]
@banan44, I tried to upgrade some modules when multistore context enabled & it is OK.
https://drive.google.com/file/d/14YI0o-Mqu6qKhqf3aHIi6UQjLnxcSuKA/view

Thanks!

**Comment by banan44** [comment]
@khouloudbelguith I do not know what else to say. Please, take a look at the logs from today and yesterday. There are a lot of errors that I have see every time a post a log here. Plus I can see new problems. Today I wanted to show you the problem. All logs between 21:37:22 and 21:56:13 - I have enabled Main Menu, then I upgraded a module that needed to be upgraded. During upgrade red pop up window showed that there was an error during upgrade. It took over 3 minutes until this message poped out. Then I tried to clear cache. It took another 3-4 minutes before it showed me Error 500 in Back Office. After CTRL +F5 still showed me Error 500. After to refresh attempts my BO appeared again with 4 green bars saying that cache has been cleared succesfully. The upgrading and deleting cache always takes a few minutes. I think this should work faster. Lots of errors are related to cache and smarty (both options are enambled in all of my shops). 

Logs: https://drive.google.com/open?id=1bhQgCsgclVrsfBtj6uxaULEjBLcnYJOJ

**Comment by banan44** [comment]
Hi @khouloudbelguith 
Can you check the logs I have sent?

**Comment by khouloudbelguith** [comment]
@banan44, yes!

You have those errors:
>Backend fatal error: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /home/xxx/websites/lbshop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n

You are not using a the default theme, it is a theme issue, you should check your theme author => similar ticket: https://github.com/PrestaShop/PrestaShop/issues/12409

I found other errors
>fatal error: PHP Fatal error:  require(): Failed opening required '/home/xxx/websites/lbshop/var/cache/prod/ContainerLamoffe/getCacheWarmerService.php' (include_path='/home/xxxx/websites/lbshop/vendor/pear/pear_exception:/home/bowshrine/websites/lbshop/vendor/pear/console_getopt:/home/bowshrine/websites/lbshop/vendor/pear/pear-core-minimal/src:/home/xxx/websites/lbshop/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/bowshrine/websites/lbshop/var/cache/prod/ContainerLamoffe/appProdProjectContainer.php on line 1632\n, referer: https://xxxxxx/xxxxx/index.php/configure/advanced/performance/

>Backend fatal error: PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove directory "/home/xxxxx/websites/lbshop/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl": rmdir(/home/bowshrine/websites/lbshop/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl): Directory not empty. in /home/bowshrine/websites/lbshop/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180\nStack trace:\n#0 /home/bowshrine/websites/xxxx/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /home/bowshrine/websites/lbshop/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 /home/bowshrine/websites/lbshop/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#3 /home/bowshrine/websites/lbshop/classes/Tools.php(3430): Symfony\\Component\\Filesystem\\Filesys in /home/bowshrine/websites/lbshop/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180\n, referer: https://xxxx/xxxxx/index.php/configure/advanced/performance/

Those errors are cache errors.

Thanks!

**Comment by banan44** [comment]
Hi @khouloudbelguith this is just an information post. I have disabled Smarty cache after you sent me the last message and since then I do not have any problems with Main Menu module.

**Comment by tklems** [comment]
@khouloudbelguith Please see https://www.prestashop.com/forums/topic/1000221-ps_mainmenu-deactivates-itself/
This a terrible bug. How could you close it as "Can't Reproduce"?
It makes whole Prestashop useless.
So typical and so frustrating for PrestaShop. I regret so much choosing PrestaShop...

**Comment by kpodemski** [comment]
@tklems it's hard to help if there's no way for QA member to reproduce issue, if you have instructions of how to reproduce it let us know :)

**Comment by tklems** [comment]
Thank you, @kpodemski, well that is a problem... See above. It is random! @banan44 tried really hard and nothing.
But we know it is there. For several users, different versions, different themes. 
Multi store does not matter.
It happens after saving a product, a category or changing a module. Sometimes.
It also happens without BO action at all. So it might be scheduled tsk like reindexing or some shop user triggered event, like searching FT or faceted search.
It cannot be reproduced on fresh install. So it must be some combination of modules or content or both.

There is something which is disabling ps_mainmenu modul. We have to trace it, what is the root cause, what is setting the module to "disabled".

**Could provide us with the instructions, how to trace it?** 

I expect that the module status is saved in the database. Can we trace what is changing the status of the module in the database? Some SQL trace at DB level should work IMHO.

Note that Faceted search is a suspect here...

Thank you.

**Comment by khouloudbelguith** [comment]
Hi @tklems,

This issue is currently closed, can you open a new one with more information about your configuration.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!

**Comment by afterglow93** [comment]
Hi, 

I didn't managed to reproduce issue on PS 1.7.6.8 but i still have this issue also.
It seems to be related to theme (unexpected error on variable).

Something pretty strange also, when cacheApc is enabled, ps_mainmenu keep enabled, but the menu completely disappear ?
When disabled, menu come back, but disable itself randomly.

How can we change this ? Something turn it to disabled in core or controller.
Why smarty errors cause a such thing ? 
That's the only module acting like this, disabling itself when some warnings or errors exists
