### ISSUE TITLE
Wrong 'create an account' link on sitemap page

### ISSUE THREAD

**Issue by Thomas-lhuillier** [PrestaShop/PrestaShop#14818]
**Describe the bug**
When going on the sitemap, then clicking on "create new account" link, it's taking me to the authentication form instead of the registration form.

**To Reproduce**
1. Go to the sitemap page
2. Click on 'create new account'

**Additional information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @Thomas-lhuillier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.6.0.
https://drive.google.com/file/d/1BmpsatpNTcH5hhIv-ASAC1MK3glgl0Bl/view
Great for the PR.

Thanks!
