### ISSUE TITLE
Cannot even make a fresh install of 1.7.6.0

### ISSUE THREAD

**Issue by vallka** [PrestaShop/PrestaShop#14812]
After failing to update with 1-Click update tried manual update. Failed as well
Tried a fresh install and failed too!!!!!

An error occurred during installation...

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

    1: Unable to write into "en-US"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer")

![presta-error](https://user-images.githubusercontent.com/12764829/61640358-15f51a80-ac95-11e9-8b2b-e910a6baaac7.JPG)

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

Guys, are you serious?? I really annoyed with all this.... Are you going to make a _working_ version finally??

**Comment by khouloudbelguith** [comment]
Hi @vallka,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @vallka,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by buby84** [comment]
in real i have the same error, installing in wsl .. i check with  phppsinfo.php,  but is all green except imagick and memcached
php 7.3.8.1

**Comment by khouloudbelguith** [comment]
Hi @EvoSw,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Comment by buby84** [comment]
not even with version:
7.2.22-1+ubuntu18.04.1+deb.sury.org+1

**Comment by khouloudbelguith** [comment]
@EvoSw, This issue is currently closed, can you open a new one with more information about your configuration

Thanks!

**Comment by augustu5** [comment]
@vallka try https://github.com/PrestaShop/PrestaShop/issues/16529#issuecomment-575635077

**Comment by alouimohamedhabib** [comment]
I did create a video on this topic
https://www.youtube.com/watch?v=gOIOw76cCQ0

**Comment by matks** [comment]
> I did create a video on this topic
> https://www.youtube.com/watch?v=gOIOw76cCQ0

Woha 😮
