### ISSUE TITLE
Contact form "send" button not working

### ISSUE THREAD

**Issue by ldarake** [PrestaShop/PrestaShop#14817]
**Describe the bug**
In the contact form the "Send" button do not make any action

**To Reproduce**
1. Go to page https://ginetom.es/es/contactenos
2. Filling mandatory fields.
3. Click on 'Enviar' button.

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.29
Theme: classic_child

Page to register new customer has the same issue.
See in this link https://ginetom.es/es/autenticacion?create_account=1

Thank you for you help.

Best regards

**Comment by khouloudbelguith** [comment]
Hi @ldarake,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ldarake** [comment]
Hi, @khouloudbelguith ,

Thank you for yor quickly response.

I have enabled debug mode, but don't show any errors.

I don't find log files:
      -/var/log/apache/apache_error.log
      -/var/log/apache/php_error.log

In Console log don't show any message.

Yoy can try reproduce following steps I wrote above

In my opinion is how if button event click not triggering.


Thank you for your support

Best regards

**Comment by khouloudbelguith** [comment]
@ldarake, in my case, I did not manage to reproduce the issue with PS1.7.6.0 & using this child theme.
[mythem.zip](https://github.com/PrestaShop/PrestaShop/files/3426269/mythem.zip)
We need PHP error logs. If you don't have it, you should ask your hosting provider.

Thanks!

**Comment by ldarake** [comment]
Hi @khouloudbelguith,

I attach a image of register of my hosting provider. You can see a error 408.

I hope will be useful to you

Thanks

![image](https://user-images.githubusercontent.com/41681733/61896239-d50b3900-af14-11e9-805c-606763f70a19.png)

**Comment by khouloudbelguith** [comment]
@ldarake, could you please try to reset the contactform module or try to re-installing it.
Check and feedback.

Thanks

**Comment by ldarake** [comment]
Hi,
I have reinstallig the contactform module before to send issue,  but don´t fix the problem.

Version installed is 4.1.1.


Thanks  for all.

**Comment by khouloudbelguith** [comment]
@ldarake, did you tried to check the issue with the classic theme & not the child theme?

Thanks!

**Comment by ldarake** [comment]
Hi @khouloudbelguith,

I fixed the bug, the problem was a module of data protection lay installed.

I uninstalled this module and now working right.


Thanks for your help

Best regards.

**Comment by khouloudbelguith** [comment]
@ldarak, thanks for your feedback.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
