### ISSUE TITLE
Error 500 when activating child theme

### ISSUE THREAD

**Issue by jlorquin** [PrestaShop/PrestaShop#14814]
Did a clean installation of PS 1.7.6.0. Installed theme, all ok. Then activated child theme and started getting error 500 when entering back office (front office: ok).

Set define('_PS_MODE_DEV_', true);

Now I can access the back office. Error displays: 

![Capture](https://user-images.githubusercontent.com/27868281/61647676-2a91dc80-acae-11e9-8e02-ab48c45c987d.PNG)

So I notice a repeated slash there in the file path. Went to /src/core/addon/theme/theme.php and commented the string concatenation:

![capture2](https://user-images.githubusercontent.com/27868281/61647657-1ea61a80-acae-11e9-9b43-c4c4e140b20b.jpeg)

Error 500 was still present. Had to remove all /var/cache contents.

I'm not sure if this is really a bug or not but it may be worth investigating. I activated the ps classic theme, then the parent theme and finally the child theme again, and now it works I think. The /src/core/addon/theme/theme.php looks like this:

![Capture3](https://user-images.githubusercontent.com/27868281/61648452-bf490a00-acaf-11e9-8e26-a853437a372b.PNG)

PHP version: 5.6

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @jlorquin,

The child theme used from the classic theme as a parent or the Warehouse theme?

Thanks!

**Comment by khouloudbelguith** [comment]
@jlorquin, in my case, I use this child theme with PS1.7.6.0 & it is OK.
[mythem.zip](https://github.com/PrestaShop/PrestaShop/files/3421203/mythem.zip)
Thanks!

**Comment by jlorquin** [comment]
@khouloudbelguith 

It was the warehouse child theme. I guess the problem comes from the developer's side! Thanks for checking.

**Comment by khouloudbelguith** [comment]
@jlorquin, thanks!
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
