### ISSUE TITLE
no_picture_image overwrite flag_image

### ISSUE THREAD

**Issue by zulus** [PrestaShop/PrestaShop#14826]
**Describe the bug**
It's not possible to upload no_picture_image

**To Reproduce**
1. Go to Internation / Localization / Languages
2. Click on Edit Language
3. Select "No-picture" image
4. Save
5. Flag image will be overwriten

**Additional information**
PrestaShop version: 1.7.6
PHP version: Doesn't matter

**Solution** Edit PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\LanguageFormDataHandler
line 104. Change from `setFlagImagePath()` to `setNoPictureImagePath()`

**Comment by khouloudbelguith** [comment]
Hi @zulus,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0.
It is Ok with PS1.7.5.1.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Addendum for people like me that dont understand what "no picture image" is 😅 : it's the picture displayed when no other picture is available

**Comment by PierreRambaud** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/14828
