### ISSUE TITLE
PLOrder->id_order est vide. at line 984 in file classes/ObjectModel.php

### ISSUE THREAD

**Issue by bigbizyou** [PrestaShop/PrestaShop#14820]
**Describe the bug**
I have the next message when i try to consult or edit commands from back-office :

[PrestaShopException]
La propriété PLOrder->id_order est vide.
at line 984 in file classes/ObjectModel.php

979.             }
980. 
981.             $message = $this->validateField($field, $this->$field);
982.             if ($message !== true) {
983.                 if ($die) {
984.                     throw new PrestaShopException($message);
985.                 }
986. 
987.                 return $error_return ? $message : false;
988.             }
989.         }
ObjectModelCore->validateFields - [line 284 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 551 - classes/ObjectModel.php]
ObjectModelCore->add - [line 508 - classes/ObjectModel.php] - [2 Arguments]
ObjectModelCore->save - [line 1333 - modules/packlink/packlink.php]
Packlink->createPlShippement - [line 1104 - modules/packlink/packlink.php] - [1 Arguments]
Packlink->execCreatePlShipment - [line 742 - modules/packlink/packlink.php] - [1 Arguments]
Packlink->hookdisplayBackOfficeHeader - [line 966 - classes/Hook.php] - [1 Arguments]
HookCore::coreCallHook - [line 351 - classes/Hook.php] - [3 Arguments]
HookCore::callHookOn - [line 903 - classes/Hook.php] - [3 Arguments]
HookCore::exec - [line 2804 - classes/controller/AdminController.php] - [2 Arguments]
AdminControllerCore->init - [line 262 - classes/controller/Controller.php]
ControllerCore->run - [line 511 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 99 - admin/index.php]

**To Reproduce**
1. Go to backoffice
2. Click on 'orders/orders'
3. Click on an Order

**Screenshots**
If applicable, add screenshots or screenrecords to h
<img width="792" alt="Capture d’écran 2019-07-23 à 11 36 59" src="https://user-images.githubusercontent.com/48217163/61701678-d8e56280-ad3e-11e9-8cac-885d2cc7bcc2.png">
elp explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @bigbizyou,

You have an issue with the `packlink` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
