### ISSUE TITLE
payment modules are in error with version 1.7.6.0

### ISSUE THREAD

**Issue by yoss55** [PrestaShop/PrestaShop#14823]
Hi , 
i have an error when a customer pays a command, instead of having a state "accepted payement, i have two dashes. 
and i also have this error in the file 'log' : [Tue Jul 23 11:29:15.790635 2019] [php7:error] [pid 11988] [client 160.92.133.135:36616] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /www/classes/Tools.php:801\nStack trace:\n#0 /www/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 /www/classes/PaymentModule.php(421): ToolsCore::displayPrice(119, Object(Currency), false)\n#2 /www/modules/atos/validation.php(137): PaymentModuleCore->validateOrder(508, '8', 119, 'Atos', 'Transaction ID:...', Array, NULL, false, '3e40c674e2f2254...')\n#3 {main}\n  thrown in www/classes/Tools.php on line 801
Informations sur votre serveur Linux #799710 SMP Wed Jul 10 08:31:28 UTC 2019 x86_64

<img width="2196" alt="Capture d’écran 2019-07-23 à 13 29 31" src="https://user-images.githubusercontent.com/52825657/61709005-7a27e500-ad4e-11e9-8ed2-ffe7ee04fc3a.png">
Version du logiciel serveur : Apache/2.4.25 (Debian)
Version de PHP : 7.2.20-1+0~20190710.23+debian9~1.gbp2428c5
Version de PrestaShop : 1.7.6.0

**Comment by khouloudbelguith** [comment]
Hi @yoss55,

You have an issue with your module `atos`.
Have you tried to contact the module author?

Thanks to check with them & feedback.

**Comment by yoss55** [comment]
i contacted ATOS and they told me that everything is okay in their sides
they told me to contact prestashop but there's no way to be helped by them

**Comment by khouloudbelguith** [comment]
@yoss55, did you make an upgrade from a previous version PrestaShop?

Thanks!

**Comment by yoss55** [comment]
no , it's new prestashop , and i tested it with 3 anothers prestashop 1,7,6 (UPGRATED) and i have the same problem

**Comment by khouloudbelguith** [comment]
@yoss55, did you tried to check another payment method?

Thanks!

**Comment by sebdgk** [comment]
same errors with another payment plugin (Worldline Sogenactif 2.0)

[Tue Jul 23 12:46:46.407490 2019] [:error] [pid 163123:tid 140027266819840] [client 160.92.133.135:19330] FastCGI: server "/home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/.config/apache/www.domain.tld/.fpm/php5.external" stderr: PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null in /home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/www.domain.tld/www/classes/Tools.php:801

other logs entries can be usefull

[Tue Jul 23 12:46:46.407519 2019] [:error] [pid 163123:tid 140027266819840] [client 160.92.133.135:19330] FastCGI: server "/home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/.config/apache/www.domain.tld/.fpm/php5.external" stderr: #3 /home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/www.domain.tld/www/modules/worldline/validation.php(179): Worldline->validate('465', '2', 37.95)
[Tue Jul 23 12:46:46.407517 2019] [:error] [pid 163123:tid 140027266819840] [client 160.92.133.135:19330] FastCGI: server "/home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/.config/apache/www.domain.tld/.fpm/php5.external" stderr: #2 /home/clients/e4cb1ca1a4bb2cef9b6243f15067ebaeaz/www.domain.tld/www/modules/worldline/worldline.php(762): PaymentModuleCore->validateOrder('465', '2', 37.95, 'Worldline', NULL, Array, NULL, false, '6c6619596a6b4e1...')


It s a Prestashop migration from 1.7.2.4

**Comment by yoss55** [comment]
yes i don't have problem with another payment method

**Comment by khouloudbelguith** [comment]
@yoss55, Could you please provide me the exact module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by yoss55** [comment]
did you receive my mail ?

**Comment by khouloudbelguith** [comment]
@yoss55, I just installed the `atos` module.
We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by yoss55** [comment]
ok

**Comment by jimmybsilva** [comment]
I am using NMI Payment Gateway I can't process cards

Module developer said is something to do with ajax changes 

https://mydomain.com/module/nmipaymentgateway/index.php?r=0.31478002121557647&ajax=true

it was able to connect once updated to 1.7.60

https://whitecbd.com/module/nmipaymentgateway/index.php?r=0.31478002121557647&ajax=true ajax return 404 error

In prestashop did something change how it handles ajax request?

**Comment by jimmybsilva** [comment]
I am using NMI Payment Gateway I can't process cards

Module developer said is something to do with ajax changes

https://mydomain.com/module/nmipaymentgateway/index.php?r=0.31478002121557647&ajax=true

it was able to connect once updated to 1.7.60

https://mydomain.com/module/nmipaymentgateway/index.php?r=0.31478002121557647&ajax=true ajax return 404 error

In prestashop did something change how it handles ajax request?

**Comment by jimmybsilva** [comment]
I am using NMI Payment Gateway I can't process cards

Module developer said is something to do with ajax changes

https://mydomain.com/module/nmipaymentgateway/index.php?r=0.31478332121557647&ajax=true

it was able to connect once updated to 1.7.60

https://mydomain.com/module/nmipaymentgateway/index.php?r=0.31478332121557647&ajax=true ajax return 404 error

In prestashop did something change how it handles ajax request?

**Comment by khouloudbelguith** [comment]
@jimmybsilva; Please follow this issue: #14648, it is similar to your problem.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14648
