### ISSUE TITLE
Decimales en el carriro

### ISSUE THREAD

**Issue by customvalencia** [PrestaShop/PrestaShop#14832]
Tengo configurado mostrar dos decimales y en el carrito muestra 6 decimales 

PrestaShop version: 1.7.6
PHP version: N/
Web: www.regaloslovel.es

**Comment by khouloudbelguith** [comment]
Hi @customvalencia,

English is the norm on this bug tracker.
This issue related to this problem: #14608. 
This issue should be fixed in the next release 1.7.6.1.
To solve your issue, you need to update your database => table `ps_currency` precision from `6` to `2`.

Thanks to check & feedback.

**Comment by GiorgioCarttoni** [comment]
Si, ya se está tratando en la incidencia que indican. Vaya pedazo de chapuza de actualización.

Yo he modificado en la tabla ps_currency la columna precision de 6 cambiado a 2(son los decimales) y el ISO de la moneda. Me funciono en un par de pedidos, pero ahora de nuevo nada. Error por todos lados, si puedes vuelve a la versión anterior.

**Comment by customvalencia** [comment]
Gracias por la ayuda, la verdad es que esta dando muchos problemas, volveré a la versión anterior.

**Comment by barbosatrix** [comment]
Estoy en la version 1.7.6.5 saben si aun presenta problemas, di vueltas y la unica opcion que encontre fue la de cambiar la columna precision como comenta Giorgo
