### ISSUE TITLE
#13440 creates a small BC break

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#14846]
**Describe the bug**
One little BC problem introduced in #13440 : when using a theme that doesn't include the button added in [personal-information.tpl](https://github.com/PrestaShop/PrestaShop/pull/13440/files#diff-936ab2713e0bb9cd8ac42716e0d33a37)  (from add-ons or other custom theme, or even Classic whithout the 1.7.6 update), if the user clicks on step one from another step (after step 1 is completed), then there's no way for him to go back (or forward, te be exact) to the next step, as this button is missing and he cannot click on the other steps. So he gets stuck and needs to refresh the page.

**To Reproduce**
Remove the button code from `themes/classic/templates/checkout/_partials/steps/personal-information.tpl`, so the file is as before #13440 and use the check-out. After completing step 1 as a logged-in user (create account, don't use the guest check-out), click on it to go back (as if you'd like to change personal info), but without the new `Continue` button you'll get stuck, no longer being able to continue to the next steps.

**Note:** Use the check-out as logged-in user, not as guest.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by rdy4ever** [comment]
Ping @jolelievre

**Comment by matks** [comment]
Hi @rdy4ever, thanks for the feedback ! @jolelievre is on vacations but we'll review this as BC breaks in the FO theme are a very important issue

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers should we fix it in 1.7.6.1 ?

**Comment by jolelievre** [comment]
Hi @marionf yes I guess we should look for a way to avoid this BC break.
