### ISSUE TITLE
SDK Facebook not update

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#14849]
Hello
I'm trying to add chatbot to my website and I get this error message 
```
sdk.js?hash=44d9c59c8ad485ab151d9e97a8bd1807&ua=modern_es6:52 ##########################
#  The CustomerChat plugin is no longer part of the main Facebook SDK.
#  To continue using it please use the correct SDK URL,
#  meaning replace sdk.js with sdk/xfbml.customerchat.js.
#  For more details see https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk
##########################
```
So I check and I found that a lot of module still use the old SD link and facebook require the new one 

Could you please take note this issue for a future update

I replaced the link and it works 

regards
![sss](https://user-images.githubusercontent.com/11594433/61839762-1bb65000-ae8f-11e9-89af-00dd174d7fae.png)

**Comment by rdy4ever** [comment]
Hi @go-sudo 
You're using a non-native module that's not developed by Prestashop. You need to contact the module's developer in order to fix this issue. This bug tracker is reserverd for core or native modules issues.

**Comment by go-sudo** [comment]
hi @rdy4ever 

Thank  very much, I will do that

Regards

**Comment by PierreRambaud** [comment]
Thanks @rdy4ever 😉 
I'm closing it!
