### ISSUE TITLE
Use command line to generate module files

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#14855]
I everyone. 

Since 2011 i create module for PrestaShop. 

I've discovered Laravel, and artisan is very inspiring for PrestaShop. 

I've imagined a lot of command who can help developpers to make module easier and faster 
like
```php psbuilder module:enable myModule```
For enable one module

```php psbuilder module:install myModule```
For install one module if it's exist on addons and it's a free plugin download it

```php psbuilder module:disable myModule```
For disable one module

```php psbuilder module:uninstall myModule```
for uninstall one module

```php psbuilder module:refresh myModule```
for autodetect new backendcontroller without reset database tables of one module. 

```php psbuilder module:delete myModule```
For uninstall and deleting one module folder

```php psbuilder module:make myModule```

for generated a module
there is what i'm imagine: 

`psbuilder module:create:admincontroller modulename ControllerName`

this command will create and backend  controller with the great name and 'refresh' the module for being autodetect. 

`psbuilder module:create:frontcontroller modulename ControllerName`
the same with front controller

`psbuilder module:validate modulename`
check if the module is ready for addons, create index.php in empty folders and clean code (php-cs-fix) 

`psbuilder module:create:views modulename viewsname`

create a smarty views in the good folder

`psbuilder module:create:model modulename modelName`

for create a model in the good directory. 

`psbuilder module:migrate modulename`

This is a big feature, this command will generated the database from the models, it could read the models attributes and generate a sql request for creating the database tables. 

`psbuilder module:migrate:rollback modulename`

Empty tables and make migrations again

`psbuilder module:export modulename`
generated and archive without hidden folders like .git .vscode 

Each module should be able to register one or many commands with a simple method in their modules files: 

`public function registerCli(){ 
 return ['mycommand' => \name\space\command::class]; 
}`

So, i hope to see a great tool like that in the futur of PrestaShop, it could be really awesome !

**Comment by mickaelandrieu** [comment]
Hi! for modules and themes management, it's already possible using the PrestaShop console.

For code generation, I'm not aware of any work in progress but eh! I can be wrong 🙂

ping @matks for additionnal comments

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

Thanks for your report.
Also, we have this PR: https://github.com/PrestaShop/PrestaShop/pull/14578 to improve Theme command as reported in this issue: https://github.com/PrestaShop/PrestaShop/issues/14577

Thanks

**Comment by PrestaSafe** [comment]
Thanks for your answer but this is absolutely not the same request, i'm talking to generate file for modules and autodetect admincontrollers, this features are not in PR #14578 and not in issue #14577 too.

**Comment by nenes25** [comment]
Hi,
I've faced the same problem so i decide to write my own classes in order to create module files through console.
( As i wanted to do the same on ps 1.6.x version, it uses my own implentation of symfony console rather than prestashop one )
You can see more information about here ( in french )
https://www.h-hennes.fr/blog/2019/04/16/prestashop-generer-des-modules-via-la-console/
https://www.h-hennes.fr/blog/2019/06/18/prestashop-generer-des-modeles-via-la-console/

**Comment by jf-viguier** [comment]
Its really a good idea @PrestaSafe 
@mickaelandrieu ready to give us a help to start something like that ?

**Comment by PierreRambaud** [comment]
Hi, you're already able to generate a module based on https://validator.prestashop.com/generator
Seems the community has already tools to do the job :)

**Comment by jf-viguier** [comment]
We have started something here https://github.com/friends-of-presta/fop_console/pull/13
WIP, any help apreciated.
