### ISSUE TITLE
Product price is zero 0 in listings when no default combination is set

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14851]
**Describe the bug**
Product price is zero 0 in listings (home, categories, search) when no default combination is set.
Price is available in product page.

**To Reproduce**
Imported product without default combination set happend - no radio button (also a separate bug?).
No matter how its it imported - default combination should be set.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by Hlavtox** [comment]
Happens also in 1.6.1.23.

If a fallback mechanism is implemented for a product page, it should be like that also in the product list...

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,
I did not manage to reproduce the issue with PS 1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1sZtNYEsx7VxEqtv3nStx6Erg-UFyF1W_/view
Thanks to check and feedback.

**Comment by ghost** [comment]
Hi and thanks for Your time! 
Unfortunately i have notticed that sometimes default combination is not set and then 0 price in listings may occour... (its not related with native csv import feature).

**Comment by khouloudbelguith** [comment]
@PrestaShark, could you please provide the file CSV file that you used to import combinations?

Thanks

**Comment by ghost** [comment]
Its not related with csv file

![Bez-nazwy-1](https://user-images.githubusercontent.com/8243273/61953910-de011680-afb7-11e9-9f8f-86a3b2d96cd7.png)

Missing default combination check causing "zero" price in all product listings

**Comment by khouloudbelguith** [comment]
@PrestaShark, I tried to create a similar co,bination with webservice, I used this script
```
<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php


/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 26/07/19
 * Time: 14:04
 */
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop.com/');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = $ws->get(array('url' => PS_SHOP_PATH.'/api/combinations?schema=blank'));

//On modifie les 
$xml->children()->children()->id_product = 21;
$xml->children()->children()->quantity = 40;
$xml->children()->children()->reference = 123;
$xml->children()->children()->price = 100;
$xml->children()->children()->minimal_quantity = 1;
/*
$xml->children()->children()->reduction = 0;
$xml->children()->children()->reduction_tax = 1;
$xml->children()->children()->reduction_type = 'amount';
$xml->children()->children()->from = '2017-06-02';
$xml->children()->children()->to = '2017-07-02';

$xml->children()->children()->id_shop = 0;
$xml->children()->children()->id_cart = 0;
$xml->children()->children()->id_currency = 0;
$xml->children()->children()->id_country = 0;
$xml->children()->children()->id_group = 0;*/


//On renvoi les donnÃ©es
$opt['postXml'] = $xml->asXML();
$opt['resource'] = 'combinations';
$xml = $ws->add($opt);

?>
</body></html>
```
& it is OK

I attached a screen record
https://drive.google.com/file/d/1Q4TaOPcGIHrmI9h6tnUcAfNoHpvCPZ-6/view

Thanks!

**Comment by ghost** [comment]
Ok. I will investigate it and let You know! Thanks for Your time! :)

**Comment by khouloudbelguith** [comment]
@PrestaShark, thanks!
Waiting for your feedback

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
