### ISSUE TITLE
products with declensions

### ISSUE THREAD

**Issue by jasonchemama** [PrestaShop/PrestaShop#14856]
Hello, Since a few days my products with declensions in size in price does not work anymore. I tried everything but I do not understand.  It worked properly before.  Even calling on other people to help me.  You would be very helpful if you could find the problem.

 Thank you in advance.
 Cordially.

**Comment by khouloudbelguith** [comment]
Hi @jasonchemama,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by jasonchemama** [comment]
> Hi @jasonchemama,
> 
> Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> * screenshots
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

hello, every month, I have this problem in my site 1.7.5 and 1.7.6.  here are the infos
![CA767C6A-E023-4771-8F22-50187A3AED0B](https://user-images.githubusercontent.com/43283123/61950956-7cbc5180-af7d-11e9-8a77-ee9e239bc91d.png)
[Safari - 26 juil. 2019 à 08:02.pdf](https://github.com/PrestaShop/PrestaShop/files/3435676/Safari.-.26.juil.2019.a.08.02.pdf)
![1397EA6D-B016-4191-B2E1-E8E1254A5C67](https://user-images.githubusercontent.com/43283123/61950984-9362a880-af7d-11e9-983c-14a1dab908c7.jpeg)
![E8594AFB-5199-41C9-8A17-5CEE4A9C0EB8](https://user-images.githubusercontent.com/43283123/61950985-9362a880-af7d-11e9-8391-738a925e61a2.jpeg)

**Comment by khouloudbelguith** [comment]
@jasonchemama, you have an issue with the ps_categoryproducts module.
Could you please try to re-install it, clear cache, check & feedback.

**Comment by jasonchemama** [comment]
> @jasonchemama, you have an issue with the ps_categoryproducts module.
> Could you please try to re-install it, clear cache, check & feedback.

how to do that?

**Comment by khouloudbelguith** [comment]
@jasonchemama; you need to navigate to your BO > Module Manager page > search for the ps_categoryproducts module, uninstall it with removing the folder, then navigate to the Module Catalog page > search for the module & install it.

Thanks!

**Comment by jasonchemama** [comment]
> @jasonchemama; you need to navigate to your BO > Module Manager page > search for the ps_categoryproducts module, uninstall it with removing the folder, then navigate to the Module Catalog page > search for the module & install it.
> 
> Thanks!

I can not access the Module Catalog page
![6CB470C5-1191-4A11-998E-4FB32224CB01](https://user-images.githubusercontent.com/43283123/61954655-4d124700-af87-11e9-870c-b214fda34109.png)

**Comment by khouloudbelguith** [comment]
@jasonchemama, when debug mode is enabled; is there any exception displayed?

Thanks!

**Comment by jasonchemama** [comment]
> @jasonchemama, when debug mode is enabled; is there any exception displayed?
> 
> Thanks!

yes here are the errors
[Safari - 26 juil. 2019 à 09:33.pdf](https://github.com/PrestaShop/PrestaShop/files/3435954/Safari.-.26.juil.2019.a.09.33.pdf)

**Comment by khouloudbelguith** [comment]
@jasonchemama,
>An exception occured in driver: SQLSTATE[HY000] [1226] User 'handi902361_4bsvsv' has exceeded the 'max_user_connections' resource (current
value: 14)

That means that the specific database user has already used up all the concurrent connections at that moment and more cannot be processed.
The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration

**Comment by jasonchemama** [comment]
> @jasonchemama,
> 
> > An exception occured in driver: SQLSTATE[HY000] [1226] User 'handi902361_4bsvsv' has exceeded the 'max_user_connections' resource (current
> > value: 14)
> 
> That means that the specific database user has already used up all the concurrent connections at that moment and more cannot be processed.
> The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration

how to do that?

**Comment by khouloudbelguith** [comment]
@jasonchemama, The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration

You need to check the issue with your host.

Thanks!

**Comment by jasonchemama** [comment]
> @jasonchemama, The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration
> 
> You need to check the issue with your host.
> 
> Thanks!

I come to contact my host;

**Comment by khouloudbelguith** [comment]
@jasonchemama, thanks!

Waiting for your feedback.

**Comment by jasonchemama** [comment]
> @jasonchemama, thanks!
> 
> Waiting for your feedback.

Here is my host's response: Hello,

 I'm sorry, but on a pooled formula, it will not be possible to change the value of max_user_connections.

**Comment by khouloudbelguith** [comment]
@jasonchemama, but you have an exception because of this
![exception](https://user-images.githubusercontent.com/16067358/61961072-b6617c80-afbe-11e9-93ab-df6e52c037cc.png)
It is a server issue.

Thanks!

**Comment by jasonchemama** [comment]
Here is my host's response
Hello,

 Indeed, the fact that this variable is blocked at 14 causes exceptions.  But it is not normal that you need more than 14 simultaneous connections for your shop.  We must work on the cause and not on the consequences.

 If you have a seal that collects water from a leak and that seal overflows.  Is it better to replace it with a bigger seal or repair the leak?

 In your case, it's the same thing, you have to find the cause of this excessive use of simultaneous connection rather than wanting to increase the quota.  Thousands of prestashop shops run smoothly on our servers with the same or even less quota.

 Regards,

 The technical team.

 ------

**Comment by khouloudbelguith** [comment]
@jasonchemama, thanks for your feedback.
But, in my case, I did not manage to reproduce the issue.
> Since a few days my products with declensions in size in price does not work anymore

Before this issue occurs, did you make any changes in your project, did you installed any custom module?

To solve this issue, you need to increase your max_user_connections (https://dev.mysql.com/doc/refman/8.0/en/user-resources.html)

Thanks!

**Comment by jasonchemama** [comment]
> @jasonchemama, thanks for your feedback.
> But, in my case, I did not manage to reproduce the issue.
> 
> > Since a few days my products with declensions in size in price does not work anymore
> 
> Before this issue occurs, did you make any changes in your project, did you installed any custom module?
> 
> To solve this issue, you need to increase your max_user_connections (https://dev.mysql.com/doc/refman/8.0/en/user-resources.html)
> 
> Thanks!

here is a new debug mode
[Safari - 29 juil. 2019 à 08:03.pdf](https://github.com/PrestaShop/PrestaShop/files/3442111/Safari.-.29.juil.2019.a.08.03.pdf)

**Comment by khouloudbelguith** [comment]
@jasonchemama, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by jasonchemama** [comment]
> @jasonchemama, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
> Thanks to check and feedback.

how to do that?

**Comment by khouloudbelguith** [comment]
@jasonchemama, in your `Project_Folder/var/cache` folder, you have some cache folder like `prod` & `dev`, you need to delete those folders manually.

Thanks!

**Comment by jasonchemama** [comment]
> @jasonchemama, in your `Project_Folder/var/cache` folder, you have some cache folder like `prod` & `dev`, you need to delete those folders manually.
> 
> Thanks!

I did, I still have the same problem

**Comment by khouloudbelguith** [comment]
Hi @jasonchemama,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
