### ISSUE TITLE
Upgraded to 1.7.5.2 Cannot amend any product Quantities

### ISSUE THREAD

**Issue by leecharles25** [PrestaShop/PrestaShop#14861]
Hi have recently upgraded to 1.7.5.2 and now i cannot amend any product quantities in Back Office.
So edit product quantity from 1 to 10....says changes have been saved but then will still only say 1 item in stock.
In de-bug mode when i open a product this comes up;

![image](https://user-images.githubusercontent.com/53303590/61891690-22ca7600-af02-11e9-82e9-02f798578787.png)

**Comment by leecharles25** [comment]
Forgot to say please help.
Lee

**Comment by khouloudbelguith** [comment]
Hi @leecharles25,
 It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.5.2 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

Thanks to check & feedback

**Comment by MathiasReker** [comment]
@khouloudbelguith It is really weird. I have the exactly the same problem on PrestaShop 1.6. I did not change or update anything in years. The issue started yesterday.

**Comment by khouloudbelguith** [comment]
@MathiasReker, I did not manage to reproduce the issue with PS1.6.1.24.
I attached a screen record
https://drive.google.com/file/d/1m2eFp93c-V72B3E9pD3OTM2jsi7w2zOh/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

Thanks

**Comment by MathiasReker** [comment]
@khouloudbelguith I know. But what is weird is that I had the exactly the same issue as @leecharles25 yesterday on an other version and I did not upgrade. Today I can not reproduce the issue. I have never had that issue before.

**Comment by MathiasReker** [comment]
I don't need help on that, it was just FYI :-)

**Comment by khouloudbelguith** [comment]
@MathiasReker, it could be a cache issue.

**Comment by MathiasReker** [comment]
I did not clear cache for a year and suddenly I had the issue.

I repaired and cleared db and cleared cache. I don't face the issue anymore, but I am not sure it was related to the cache.

**Comment by leecharles25** [comment]
Hi Khouloudbelguith, looks like you know the answer, i have looked at the schema you have sent....excuse my ignorance but what do i do with it?
Can you talk me through how i add the missing collumn(s).
I am very grateful for the help.

Lee

**Comment by ghost** [comment]
@leecharles25 its missing location column in ps_stock_available table... Check email from me. Send You yesterday.

**Comment by khouloudbelguith** [comment]
@leecharles25, here's the exact structure of the ps_stockavailable table.
![ps_stockavailable](https://user-images.githubusercontent.com/16067358/61954584-0a656480-afb1-11e9-8290-45f600db4fdc.png)

Thanks!

**Comment by leecharles25** [comment]
Hi @khouloudbelguith, thanks for your reply, I don’t know how to put it right?

Do I upload something this is why I needed you to talk me through what it is I need to do step by step.

Sorry I don’t really know what you are showing me.

Kind Regards

Lee

**Comment by leecharles25** [comment]
Hi Prestashark, sorry I have no email yesterday.

 

Thanks for telling me a bout the missing location column, what I need is to be told step by step how to fix this.

 

Are you in Poland?

 

My wife is Polish…

 

Lee

**Comment by ghost** [comment]
Yes im from Poland. Please check email twice i will help with this issue.

**Comment by khouloudbelguith** [comment]
@leecharles25, first, could you please navigate to the BO =>Advanced Parameters => Database => Create this SQL `Select * from ps_stockavailable` & Save.
Try to view the result & provide me a screenshot.

Thanks!

**Comment by leecharles25** [comment]
Hi, is this what you need?

**Comment by khouloudbelguith** [comment]
@leecharles25, there is no screenshot attached here.
You need to login into GitHub & upload your picture.

Thanks!

**Comment by leecharles25** [comment]
Ok try this....
![image](https://user-images.githubusercontent.com/53303590/61962082-ad71aa80-afc0-11e9-85a5-77b6fcdac696.png)

**Comment by leecharles25** [comment]
I am missing collumn "location"

**Comment by khouloudbelguith** [comment]
@leecharles25, yes, this is the exact issue.
So you need to add this column in your table.
Try to connect to your PhpMyadmin, for example, => find your database & your table and try to add this missing column.

Thanks!

**Comment by leecharles25** [comment]
Ok im in and ready to add collumn.

What do i put in Length/Value and varchar is available but not varchar(255)???

Please advise

**Comment by khouloudbelguith** [comment]
@leecharles25, you can follow my screenshot
![image](https://user-images.githubusercontent.com/16067358/61963955-b49ab780-afc4-11e9-9a5c-837363f32284.png)

Thanks!

**Comment by leecharles25** [comment]
Ok so i press save and it says i have to enter a length/value
![image](https://user-images.githubusercontent.com/53303590/61964693-64bcf000-afc6-11e9-8fcb-8c926f38b22e.png)

**Comment by khouloudbelguith** [comment]
@leecharles25, try to use `0`.

Thanks!

**Comment by khouloudbelguith** [comment]
@leecharles25; here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10422 to add stock location.

Thanks!

**Comment by leecharles25** [comment]
Hooray its worked xxxxxx

However now in BO products it no longer shows quantity in stock collumn...this has disapeared.

Any advise ???

We are making progress...

**Comment by khouloudbelguith** [comment]
@leecharles25, could you please follow this PR's files: https://github.com/PrestaShop/PrestaShop/pull/10422/files & compare them to your files.

Thanks!

**Comment by leecharles25** [comment]
Hi the missing quatity column in Bo was due to stock management....all is working well many thanks for all help.
This can be closed now.

**Comment by khouloudbelguith** [comment]
@leecharles25, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
