### ISSUE TITLE
Check and fix categories count for CMS Pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14865]
@jolelievre has fixed a bug on Product categories in PR https://github.com/PrestaShop/PrestaShop/pull/13984

Considering the root cause of the bug, I think the same issue applies to CMS Page categories. We need to
- check whether the bug exists for CMS Page categories
- fix it if if exist

## To Do

Read PR https://github.com/PrestaShop/PrestaShop/pull/13984, read the related issue, check whether the same faulty behavior applies to BO page "Improve > Design > Pages" and if it does (we think so), then apply the same kind of fix

**Comment by Hlavtox** [comment]
@matks There is no KPI on the CMS or CMS category pages, so nothing to fix here. :-)
