### ISSUE TITLE
voucher_new nos used in Prestashop ?

### ISSUE THREAD

**Issue by alex4102** [PrestaShop/PrestaShop#14867]
**Describe the bug**

**To Reproduce**
1. Go to Cart Rules
2. Create a new cart rule for specific user
3. Not receive the email template voucher_new

**Additional information**
PrestaShop version: 1.7.6.0 and previous

Do you know why the template voucher_new is not used when we create a cart rule for specific user ?

**Comment by khouloudbelguith** [comment]
Hi @alex4102,

No, there is no email sent.
As you can see in our documentation, this function doesn't exist.
http://doc.prestashop.com/display/PS17/Cart+Rules
You can see the voucher in the account of the user.
https://drive.google.com/file/d/1C5Tcs575fltOOFq0fM6kLRyYejFVShZu/view
But, if you use the ps_emailsubscription module, you can receive the email for the Welcome voucher code.
About the voucher_new  template, it is sent when a person receives a refund in the form of a voucher.

Thanks for your understanding
