### ISSUE TITLE
Add to cart button stuck on loading

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#14874]
**Describe the bug**
Add to cart button is stuck on loading on site https://madein.mu/

Please see attached image of console (chrome).
![untitled](https://user-images.githubusercontent.com/26452178/61957462-5ecc0c80-afd0-11e9-8099-8c187ca821dc.png)

Not sure how to interpret error. Is this an issue with theme?

**Additional information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

You have an error 500, could you please try to enable debug mode & check if there is an exception when you click "add to cart".

Thanks!

**Comment by nrcjea001** [comment]
Sorry. I am new to this. I go to debug mode and this what I see. Please advise where to look

![untitled](https://user-images.githubusercontent.com/26452178/61958667-ce42fb80-afd2-11e9-90fb-e3808fa66275.png)

**Comment by nrcjea001** [comment]
I may be wrong but it doesn't look like an exception is being thrown

![untitled](https://user-images.githubusercontent.com/26452178/61959481-88873280-afd4-11e9-87f5-3ce62e142810.png)

**Comment by khouloudbelguith** [comment]
@nrcjea001, thanks!
I found the exception in your shop
![cart](https://user-images.githubusercontent.com/16067358/61959740-f7a45d00-afbb-11e9-9ac4-076aa2d6c8b5.png)
It is related to the mailchimp module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by nrcjea001** [comment]
thank you very much for the help :)
