### ISSUE TITLE
Missing Controllers 1.7.6

### ISSUE THREAD

**Issue by donadiov** [PrestaShop/PrestaShop#14882]
My issue is a little bit related to this one:
https://github.com/PrestaShop/PrestaShop/issues/13681

I understand that Prestashop is looking foward to deprecate overrides, which I think it could solve some issues, like two or more modules overriding same class; method or controllers' function.

Today I find myself working to upgrade my Store, first from 1.6 to 1.7.5.2 - Which wasn't so hard, and now from 1.7.5.2 to 1.7.6 - My Store is a Marketplace, and for some security issues I had worked on modifications on Profiles, Employees, etc.

Since my first version of this modifications, I used overrides for Profile and Employee, the most important entities when talking about security issues, access, permission, etc.

Now with 1.7.6 I found a surprise, AdminProfileController DOES NOT exists, so I can't make an override for this file. Checking other controllers, I found there are around 11 Controllers that no longer exists from 1.7.5.2 to 1.7.6.

I understand the possible reasons, but what is our workaround to this problem? I'm sure other developpers had overrides on this files too, what is the best aproach or solution yo can give us?

Just for the record, here is the list of the 11 missing contorllers:
AdminCategoriesController
AdminContactsController
AdminCurrenciesController
AdminCustomersController
AdminEmployeesController
AdminLanguagesController
AdminMetaController
AdminProfilesController
AdminTaxesController
AdminThemesController
AdminWebserviceController

**Comment by khouloudbelguith** [comment]
Hi @donadiov,

Those pages are migrated to symfony as described here: http://build.prestashop.com/news/prestashop-1-7-6-0-beta-release/
You can find the controller in this path: `Prestahop_Project/src/PrestaShopBundle/Controller/<path>/<Your>Controller`
- For example `AdminCategoriesController` exist here: `Prestahop_Project\src\PrestaShopBundle\Controller\Admin\Sell\Catalog`
- `AdminContactsController` exits here: C:\xampp\htdocs\QA\prestashop\prestashop_1.7.6.0\src\PrestaShopBundle\Controller\Admin\Configure\ShopParameters

Ping @matks what do you think?

Thanks!

**Comment by donadiov** [comment]
@khouloudbelguith

Thanks for your wuick answer - I get the point, now how can I overrides or modify this controllers' behavoir as I would do with overrides?  My intention of course si not to modify Prestashop Core

**Comment by khouloudbelguith** [comment]
@donadiov, thanks to follow our documentation: https://devdocs.prestashop.com/1.7/modules/concepts/overrides/#overriding-a-controller

Thanks!

**Comment by donadiov** [comment]
@khouloudbelguith I have read that link, and I know how to override standar controllers or clases.

Now my question is HOW to override this controllers located in the folder you mentioned in your first comment:
Prestahop_Project/src/PrestaShopBundle/Controller/<path>/<Your>Controller

Should I just replicate that folder structure inside override folder?

**Comment by khouloudbelguith** [comment]
Ping @matks

**Comment by sarjon** [comment]
Hi @donadiov,

if you are looking for how to extend new controller **using module**, you can check template overrides [here](https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/), Grid hooks  [here](https://devdocs.prestashop.com/1.7/development/components/grid/#hooks). You can check [here](https://github.com/friends-of-presta) for more examples of how to extend new controllers.

If you want to customize controller for your own shop **without using modules** and you have some knowledge in Symfony, then you could try creating new Symfony bundle and override specific controllers.

**Comment by khouloudbelguith** [comment]
Hi @donadiov,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
