### ISSUE TITLE
Mobile Template

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#14886]
any mobile template available for PS 1.7.6.0?

**Comment by khouloudbelguith** [comment]
Hi @banobazaar, 

You can find in this link: https://addons.prestashop.com/en/3-templates-prestashop?compatibility[]=1.7.6&functionality[]=92& the list of templates which are compatibles with PS1.7.6.0 & responsives.
So, in our addons market place, you can find the mobile-optimized PrestaShop themes.

Thanks!

I close the issue, feel free to open a new one when needed.
