### ISSUE TITLE
An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Theme\Exception\ThemeConstraintException code 2]

### ISSUE THREAD

**Issue by BIGREECE** [PrestaShop/PrestaShop#14887]
I keep receiving this error everytime I try to upload my prestashop template. it is in a zip file and I have tried multiple templates, by link and zip upload. I also found that the free prestashop templates that are available online are not available in the catalog. how can I fix this error?

again its:
 An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Theme\Exception\ThemeConstraintException code 2]

**Comment by khouloudbelguith** [comment]
Hi @BIGREECE,

I tried with two different themes & they are well uploaded.
I attached a screen record
https://drive.google.com/file/d/1933fl4VzoCezrP8XRUxXGsjHFx2blps_/view

Thanks to check & feedback.

**Comment by PoggoAgency** [comment]
Hi there,

I have same problem as @BIGREECE : how did you fix it? 

Thanks

**Comment by mbintanveer** [comment]
Facing same problem too.

**Comment by BIGREECE** [comment]
I believe it’s because they are a different version of prestashop  and simply not compatible. My only work around was finding a free template that works. Prestashop’s customer support won’t help unless you have a purchase order number, purposely weeding out the people who use the free templates that they have available.

**Comment by khouloudbelguith** [comment]
Hi @all,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by vilzuh** [comment]
Having the same problem. I can work around it by movin the .zip file to prestashop's theme folder via ftp and extracting it there manually. That way I can see the theme on back office and activate it there too. This also happens if I download Classic theme to modify and upload back.

**Comment by khouloudbelguith** [comment]
Hi all,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15004
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15004

**Comment by valkor** [comment]
This is nice way to handle an issue, just move move ticket to duplicate!

**Comment by cabinatele** [comment]
Ya tengo la solución, Cada archivo Free esta comprimido sobre otro comprimido zip, debe descomprimir el theme y luego ver el zip que queda de la primera descompresión y luego ver que dentro de este no este comprimido nuevamente. Luego si ir al Back Office y subir el Theme zip. Ya no saldrá el error.

**Comment by iliankirov** [comment]
Hello! And I meet this problem a lot of times, trying to install my theme. It caused, that the steps I do was wrong. I installed the theme without problems, following the steps from this video: 

https://www.youtube.com/watch?v=LuI-ynLYlGY

**Comment by dainora** [comment]
if you see this message and if you have config/theme.yml file you might do something wrong when ziping file.
My issue was that I zipped folder instead folders inside theme, Example Test folder, but instead you should go inside that folder, **select all files and zip to some name, then it works**.
Example select assets, config, modules....etc folders and zip to name "Test"
It means it shouldn't be extra step go to you created theme :) 
Hope this helps for everyone who has this issue.

**Comment by crishnakh** [comment]
Hi, my problem was related to the config folder of the theme. And the theme.yml file inside.
I created a really basic file for my theme and now I can see it. I think it's a problem of the theme... it's not ready to the last version of prestashop.

My PST version was 1.7.7.2 .
