### ISSUE TITLE
Admin Cart gives error 500 when trying to use it

### ISSUE THREAD

**Issue by Kilipukki** [PrestaShop/PrestaShop#14884]
Hello folks. 

im bit new to this Prestashop and i have a problem that i cant solve.

in admin panel side, when i try to access Cart (orders-cart) it gives me this error:

Exeption tab:

PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException

in src/Core/Localization/Locale.php (line 171)

    public function getPriceSpecification($currencyCode)

    {

        $currencyCode = (string) $currencyCode;

        $priceSpec = $this->priceSpecifications->get($currencyCode);

        if (null === $priceSpec) {

            throw new LocalizationException(

                'Price specification not found for currency: "' . $currencyCode . '"'

            );

        }

        return $priceSpec;

LOGS tab:

 

DEBUG13:57:49 doctrine SELECT name FROM psrf_module WHERE active = 1

CRITICAL13:57:49 php Uncaught Exception: Price specification not found for currency: ""

CRITICAL13:57:49requestUncaught PHP Exception PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException: "Price specification not found for currency: """ at /home/santaspb/public_html/src/Core/Localization/Locale.php line 171

 

Any idea what is wrong with it? using PS 1.7.6.0 version (updating did not solve it so rolled back to previous) PHP version is 7.1.30  - language is finnish and currencies Euro

**Comment by khouloudbelguith** [comment]
Hi @Kilipukki,

The issue is related to #14608. 
Could you please try to change the precision to `2` in your table `ps_currency` from your database.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Kilipukki,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
