### ISSUE TITLE
Drag & Drop to change position in grid with HelperList

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [PrestaShop/PrestaShop#14885]
PrestaShop version: 1.7.6
PHP version: 7.2.14

HelperList : still a bug on drag and drop to change position of items in grid.

We have to specify manually the currentIndex:
Media::addJsDef(array(
            'currentIndex' => AdminController::$currentIndex.'&configure='.$this->name/*and whatever*/,
));

Best

**Comment by khouloudbelguith** [comment]
Hi @nicoja,

Thanks for your report.
In which pages this issue occurs, in pages migrated to Symfony?
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Hello, no.
simply create an helperlist in module to display a grid and implement a drag and drop of items to update their positions, that's it
Best,
Nicolas

**Comment by khouloudbelguith** [comment]
@nicoja, in fact, HelperList is indeed not used anymore in pages migrated to Symfony however other mechanisms are available (the Grid) as well as new hooks.
Could you please check & feedback.

**Comment by Kixell-NicolasJardillier** [comment]
ok, but how you make your module compatible with older Prestashop versions ?
It is a little bit confusing.
HelperList is still used in many Prestashop controllers : AdminPatterns, AdminSearch, AdminCarts, AdminTracking
So why I should migrate as Symfony (3) is still not fully implemented, as well as more than 95% of modules still used old system.
I really wonder how compatibility could be managed and also how to do proper work in Prestashop now.

I ll try if I have any time to implement "other mechanisms"

**Comment by khouloudbelguith** [comment]
@nicoja, could you please provide me a demo module to test it.

Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Sorry, but It is complicate for me to take this time. You have the information if you want to debug it.
Best regards

**Comment by khouloudbelguith** [comment]
@nicoja, thanks!
We'll try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @nicoja,

I checked the module Blog Pro & PS1.7.6.1 & it is OK.
I attached a screen record
https://drive.google.com/file/d/1wGURNWJBUmxrRoT6LWXodMhG6bxnEJQT/view
Thanks to check & feedback.

**Comment by Kixell-NicolasJardillier** [comment]
Hi, you did it on a module that probably manage this error, cf. my first post : 
Media::addJsDef(array(
'currentIndex' => AdminController::$currentIndex.'&configure='.$this->name/and whatever/,
));

Several modules manage this errors as I mentioned (do not ask which one).
My problem is not with the module but the Prestashop core.
Thus, please check the code of the module you used, I am sure that the error is handle.
This is a bug in the core.

I ll checked several times.

Maybe, you would like to suggest that the problem was corrected in version 1.7.6.1 of prestashop you used ?

**Comment by khouloudbelguith** [comment]
@nicoja, I tried with the same module with PS1.7.5.2 => OK.
Drag & drop is well working!
But I tried with PS1.7.6.1 & PS1.7.5.2 & the `ps_linklist` module v2.1.6(old version)
As reported here https://github.com/PrestaShop/PrestaShop/issues/9950, but it is fixed after refactoring the module.
=> I have the same issue
https://drive.google.com/file/d/16cJ4DevKrSD8fzmebhrIiFGIutXMDL0W/view
Ping @PrestaShop/prestashop-core-developers what do you think?
Is it a core issue or a module bug?

Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
Hi,

as I said this is a core issue.
From my side I know how to manage it, but I think that it should be send to core team as you mentioned.
Link to core team you provided is in 404.

Isn't the right place to report issue ?

**Comment by khouloudbelguith** [comment]
@nicoja, yes, it is the right place.
In your case, you have 404 not found => because you don't have the right access.
It is OK with the core team member.
f you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
I never change the core, but manage it in the module (sorry, but again, as mentioned in initial post)

**Comment by PierreRambaud** [comment]
> @nicoja, I tried with the same module with PS1.7.5.2 => OK.
> Drag & drop is well working!
> But I tried with PS1.7.6.1 & PS1.7.5.2 & the `ps_linklist` module v2.1.6(old version)
> As reported here #9950, but it is fixed after refactoring the module.
> => I have the same issue
> https://drive.google.com/file/d/16cJ4DevKrSD8fzmebhrIiFGIutXMDL0W/view
> Ping @PrestaShop/prestashop-core-developers what do you think?
> Is it a core issue or a module bug?
> 
> Thanks!

If the bug is fixed with the new version, we can close this issue. :)

**Comment by hibatallahAouadni** [comment]
Hello,

I didn't reproduce it with PS1.7.6.9 and ps_linklist 3.2.0 as you can see in the attached screen record below:

https://drive.google.com/file/d/1EflzaMoaSHGqzHRccTT8oHxZlRRWZXPU/view

I close this issue.

Thanks!
