### ISSUE TITLE
Can not choose from more than 40 product features in controller=AdminFeatures&addfeature_value

### ISSUE THREAD

**Issue by harm-smits** [PrestaShop/PrestaShop#14888]
**Describe the bug**
I have 60 product features, but can only select form the first 40 in the backend when adding a new feature value

**To Reproduce**
1. Create a number of product features
2. You can no longer add values to a features after a certain number using the add feature values option in the backend

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by harm-smits** [comment]
It seems to be solve-able by reloading php-fpm, however, that seems to be a pretty weird fix...

**Comment by khouloudbelguith** [comment]
Hi @harm-smits,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1FWZwpAlg9i_Ef_y_EKifCPBuuMdMvUlK/view
Thanks to check & feedback.

**Comment by harm-smits** [comment]
We use APC for caching along with opcache re-validation set to false. 

I managed to reproduce it by doing the following:
1. Load the feature variants page.
2. Create a new feature.
3. Now we can not see the feature when we want to add it using the feature variants.

It seems that the filecache / apcu cache is not invalidated accordingly in some cases. It would be worth to look into this: https://www.php.net/manual/en/function.opcache-invalidate.php

**Comment by khouloudbelguith** [comment]
@harm-smits, so the issue is not a PrestaShop core issue? is it?

Thanks!

**Comment by harm-smits** [comment]
Well, seems like it is. Incorrect invalidation of caches seems to be a pretty big concern if you ask me... Will see if I can find a solution to this.

**Comment by khouloudbelguith** [comment]
@harm-smits, 
Your issue is not a PrestaShop's core bug but most likely a server configuration.

Thanks!
