### ISSUE TITLE
Add FosUser API

### ISSUE THREAD

**Issue by alouimohamedhabib** [PrestaShop/PrestaShop#14897]
Include FosRest instead of the classic WS system that is not flexible.

**Comment by khouloudbelguith** [comment]
Hi @alouimohamedhabib,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
It would be nice but that's a very big piece of work that cannot be started right now as we have major areas of the software already being reworked

A big rework of the WS is in the roadmap: https://github.com/PrestaShop/PrestaShop/projects/1#card-13082456

Although nothing is decided, it is likely that when we start this big project, we'll build a V2 REST API (current webservice will remain available but deprecated) using a popular API PHP engine: FosRest could be a nice one, ApiPlatform is another great candidate too

And of course it will be documented using one modern API specification schema (OpenApi or RAML), which will provide a nice out-of-the-box doc, and fully tested with dedicated tests

**Comment by PierreRambaud** [comment]
As @matks a huge work is planned for the API. I'm closing this issue :)
