### ISSUE TITLE
php 7.3 ORM

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#14893]
> Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Hello. Pls update ORM version. https://github.com/doctrine/orm/releases

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3, you can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/12461

Thanks to check & feedback.

**Comment by matks** [comment]
@TemKaSD It will be done in PS 1.7.7 😉having Doctrine support for php7.3 is one of the main reasons we have dropped php5.6 compatibility for next 1.7.7 version (see details on http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/)

The PR that will update Doctrine versions is in Work In Progress here: https://github.com/PrestaShop/PrestaShop/pull/13761
