### ISSUE TITLE
Price Specification not found for currency: "" (Viewing suppliers)

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#14908]
**To Reproduce**
>[Edit by Khouloud]
1. Go to the BO => => Advanced Parameters => Import page => Import products using the csv file by default
1. Go to Catalog -> Brands & Suppliers
2. Click Suppliers -> click view supplier

**Screenshots**
![untitled](https://user-images.githubusercontent.com/26452178/62104475-c58f4580-b2b0-11e9-85d8-e04e243c297b.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

The issue seems to be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/14608
Could you please try to change the `precision` from `6` to `2` in your table `ps_currency` in your database, check & feedback.

**Comment by nrcjea001** [comment]
![untitled](https://user-images.githubusercontent.com/26452178/62127940-60edde00-b2e4-11e9-9a31-965f878e5cd3.png)

This did not work for me

**Comment by khouloudbelguith** [comment]
@nrcjea001,
Thanks for your feedback. 
Could you please follow this comment https://github.com/PrestaShop/PrestaShop/issues/14595#issuecomment-510884182, try with this solution and feedback.

**Comment by nrcjea001** [comment]
Tried this solution but no change unfortunately

**Comment by khouloudbelguith** [comment]
@nrcjea001, could you please try with this solution, be sure that you have a back up of your database.
Try to delete all rows with `id_currency == 1` from `ps_product_supplier`.
Thanks to check & feedback.

**Comment by nrcjea001** [comment]
I've tried this as well and it doesn't work. I tried removing all suppliers associated to product and reimporting everything, but still nothing.

 All id_currency == 0 now. But why 0? if my default currency ID = 1, how can it be 0 in ps_product_supplier?

**Comment by khouloudbelguith** [comment]
@nrcjea001, could you please try to `Truncate` the `ps_product_supplier`, check it this issue occurs again.

PS: you should make a backup of your database.

Thanks!

**Comment by nrcjea001** [comment]
@khouloudbelguith , I deleted all records using the delete option provided by phpmyadmin. Is this different from "truncate" command?

**Comment by khouloudbelguith** [comment]
@nrcjea001, 'truncate' command is to empty all the table.

Thanks!

**Comment by nrcjea001** [comment]
@khouloudbelguith , I truncated table and issue went away. However, when I imported suppliers again, issue came back.

I am using an import module from another vendor. I will get in touch with them first to see if its not an issue on their side.

**Comment by khouloudbelguith** [comment]
@nrcjea001, yes, you should contact them.
In my case, I tried to empty the table & select suppliers to products => it is OK.
Thanks!
Waiting for your feedback.

**Comment by nrcjea001** [comment]
Hello

Vendor confirmed it is not a bug in the module. I truncated table and it is OK. But then I reimported suppliers and the issue comes back.

Please see attached ps_product_supplier table for reference

![untitled](https://user-images.githubusercontent.com/26452178/62290433-6aa54c00-b472-11e9-9832-a00d89f51bb1.png)

**Comment by nrcjea001** [comment]
![untitled](https://user-images.githubusercontent.com/26452178/62290578-b0faab00-b472-11e9-88e2-7e6b5da8bc46.png)

**Comment by khouloudbelguith** [comment]
@nrcjea001,

> But then I reimported suppliers and the issue comes back.

Could you please try to edit the suppliers for your some products manually, from the BO => Products details page => Options Tab
![image](https://user-images.githubusercontent.com/16067358/62290698-dc24d080-b459-11e9-8bc4-bc6b1941d254.png)

Thanks!

**Comment by nrcjea001** [comment]
@khouloudbelguith , I've edited suppliers without error. All seems ok there. But issue above remains

**Comment by khouloudbelguith** [comment]
@nrcjea001, in the BO => the exception is always displayed?

Thanks!

**Comment by nrcjea001** [comment]
No Exception when editing suppliers in Options Tab. Exception is always thrown when viewing suppliers

**Comment by khouloudbelguith** [comment]
@nrcjea001, did you use the multistore context?

Thanks!

**Comment by nrcjea001** [comment]
no

**Comment by khouloudbelguith** [comment]
@nrcjea001, I manage to reproduce the issue with PS1.7.6.0.
In fact, I tried to import new products from the BO => Advanced Parameters => Import page using the CSV file by default.
In the BO => Catalog => Brands & Suppliers page => Supplier Tab => Click on "View" => see error
![image](https://user-images.githubusercontent.com/16067358/62297337-ee5a3b00-b468-11e9-8067-1453010bc25d.png)
With PS1.7.5.2 => OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
Thanks!

**Comment by eternoendless** [comment]
The offending line, AdminSuppliersController.php:403

```php
$products[$i]->product_supplier_price_te = Tools::displayPrice($product_infos['product_supplier_price_te'], new Currency($product_infos['id_currency']));
```

line 397:
```php
$product_infos = Supplier::getProductInformationsBySupplier(
   $this->object->id,
   $products[$i]->id,
   0
);
```

I'm betting `$product_infos['id_currency']` is 0 or `null`...

**Comment by nrcjea001** [comment]
Hello

Although 1.7.6.1 cleared up this issue with my other shops, my shop morganic.mu remains unresolved when attempting to access suppliers.

![Untitled](https://user-images.githubusercontent.com/26452178/64470979-9d6eee00-d15c-11e9-8bb0-23b225d096d2.png)

I also found an exception while trying to add a new currency. Please see pdf attached.

[exception.pdf](https://github.com/PrestaShop/PrestaShop/files/3586330/exception.pdf)

After exception was thrown, 2 new faulty currencies were added at random

![Untitled2](https://user-images.githubusercontent.com/26452178/64470999-d9a24e80-d15c-11e9-963c-14d67529b1bd.png)

As mentioned, all is working fine with my other shops. Perhaps its not working with morganic.mu because we tried to fix this issue previously by truncating the ps_product_supplier table a few weeks ago. 

It may be that my database needs to a fresh install. But I'm not sure how to approach this without having to start from scratch.

Thanks

**Comment by nrcjea001** [comment]
![Untitled](https://user-images.githubusercontent.com/26452178/64471155-72859980-d15e-11e9-9373-78599caa2b39.png)

![Untitled2](https://user-images.githubusercontent.com/26452178/64471156-787b7a80-d15e-11e9-8958-4f14a481ca48.png)

**Comment by khouloudbelguith** [comment]
@nrcjea001, This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
