### ISSUE TITLE
Customer order message display wrong variable {firstrname} in mail

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#14906]
**Describe the bug**
Typo in {firstname} variable when customer send order message

**To Reproduce**
1. Go to 'FO: order history page -> open any order details page'
2. Click on 'Add a message and send'
3. See {firstrname} variable in mail goes to admin

**Screenshots**
![fdfasdfasdfasdfasd](https://user-images.githubusercontent.com/19220745/62182921-f38a8d80-b375-11e9-8114-841086403174.png)

**Additional information**
PrestaShop version: 7
PHP version: 1.7.6.0

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your report.
I tried with PS1.7.6.0 to send a message but there is no email sent.
Other mails are well displayed.
What do you think?

Thanks!

**Comment by dheerajwebkul** [comment]
Hello @khouloudbelguith 

Mail is going, please make sure your mail is configured.

The issue is only in in mail when customer send message from order details page.
Check this screenshot:

![testeetwsetsetett](https://user-images.githubusercontent.com/19220745/62182828-af978880-b375-11e9-863d-67b4390bcb26.png)


This PR has fixed this issue I have tested well.
https://github.com/PrestaShop/PrestaShop/pull/14907

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, I manage to reproduce the issue with PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/62228922-82b79580-b3b6-11e9-8cf5-578d29c1882f.png)
With PS1.7.5.1 => It is OK
![image](https://user-images.githubusercontent.com/16067358/62228994-ab3f8f80-b3b6-11e9-8aba-8b13124c0ecb.png)
It is a regression, you should add your PR in the branch 1.7.6.x & not develop.
Thanks!
