### ISSUE TITLE
Problems changing the store name (my Shop) prestashop 1.7.6

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#14917]
Hello, after updating prestashop 1.7.5 to 1.7.6, the name of the store was changed to "My Shop"
I tried to change the name in the back office and it didn't change, I went to the database (pr_configuration - PS_SHOP_NAME) to change it from there and it didn't work. I have prestashop 1.7.6 (before with 1.7.5 and if it worked) The name "My Shop" is in the mail and in other sections.
I use the warehouse template

**Additional Information**
PrestaShop version: 1.7.6
PHP Version: 7.3
MariaDB 10.1

Thank
![2019-07-30 (2)](https://user-images.githubusercontent.com/53478767/62134229-806e1200-b2b6-11e9-8bf3-a19fe022a069.png)
![2019-07-30 (3)](https://user-images.githubusercontent.com/53478767/62134230-806e1200-b2b6-11e9-9868-0c110acd409e.png)

**Comment by khouloudbelguith** [comment]
Hi @Marcelozippo,

Could you please try to navigate to the BO => Shop Parameters => General => Enable "Multistore".
Then go to the BO => Advanced Parameters => Multistore => Edit your shop => & edit the shop name & save => after that try to disable multistore.
![image](https://user-images.githubusercontent.com/16067358/62037610-02453900-b1ec-11e9-96a7-1764ab2dabcb.png)
You need to check that all categories & subcategories are checked before saving (click on Expand all & check all multiple times)
Thanks to check & feedback

**Comment by Marcelozippo** [comment]
Hello, it worked, I did the steps as you told me and it worked very well. Thank you so much
It is the first time I publish here, what do I have to do? must be solved?

Thank you

**Comment by khouloudbelguith** [comment]
@Marcelozippo, since it is fixed.
I close the issue.
Feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14891

**Comment by ranno525** [comment]
Thnx you so much , it workt for me :-)

**Comment by zelduxs** [comment]
Thanks!🥇

**Comment by MatjeGit** [comment]
Thanks!!  worked for us.

**Comment by akshuvo** [comment]
Thanks @khouloudbelguith

**Comment by FaustoBoscaro** [comment]
This is NOT SOLVED, all my subcategories are desappered and there's no way to show them back!!!!

**Comment by Marcelozippo** [comment]
Hello, thanks for the comment, I solve it, I followed all the steps, but before I made a backup in case it did not work. But it worked for me. Do you have a backup to return everything as it was before? What version of prestashop do you have? PHP? MySQL or Maria? I used in this moment Maria but I don't remember the version and PHP 7.2 in cpanel with apache and nginx. The first thing I would recommend is that you return the backup to have everything as it was, then duplicate the store and experiment on that copy. This is how I always do.

regards
Marcelo

**Comment by FaustoBoscaro** [comment]
I solved from database with this:

INSERT INTO `ps_category_shop` ( `id_category` , `id_shop` , `position` )
SELECT id_category, 1, 0
FROM `ps_category`
WHERE id_category NOT
IN (
SELECT id_category
FROM `ps_category_shop`
)

BUT i think that the bug should not be solved with Multistore!!
The big problem with Multistore is that if you have a lot of subcategories (500 in my store) you can't flag them.

**Comment by jamiloo** [comment]
Hi, is there any progress in problem with dissapered categories during multistore's shop rename? Is there any information which part of Prestashop does delete of catefgories after shop rename? It is nice to revert from backup or rebuild categories with SQL placed above. But I would like to make some safet fix at our Prestashops. Thank wery mucho to all for all advices.

**Comment by tswfi** [comment]
Issue for the category assignment https://github.com/PrestaShop/PrestaShop/issues/22402

**Comment by sitareci** [comment]
Hi FaustoBoscaro, would you please tell me what where and how to change those lines? I'm not entirely sure how apply your solution. Can you pleas further clarify what's need to be done in order to bring back the missing sub categories? Your reply would be greatly appreciated. Many thanks

**Comment by CharlieHarpers** [comment]
The 

> Hi @Marcelozippo,
> 
> Could you please try to navigate to the BO => Shop Parameters => General => Enable "Multistore". Then go to the BO => Advanced Parameters => Multistore => Edit your shop => & edit the shop name & save => after that try to disable multistore. ![image](https://user-images.githubusercontent.com/16067358/62037610-02453900-b1ec-11e9-96a7-1764ab2dabcb.png) You need to check that all categories & subcategories are checked before saving (click on Expand all & check all multiple times) Thanks to check & feedback

Thank you! Best way to change it! And to [FaustoBoscaro]´, after adjustment you have to switch off the MultiStore feature. It is only a workaround, a nice and easy one! Cu Karl
