### ISSUE TITLE
Error when save an existing product before it is fully loaded

### ISSUE THREAD

**Issue by R-Larsson** [PrestaShop/PrestaShop#14910]
**Describe the bug**
I get an error message 'Unable to update settings' if i try to save an existing product before the product has been fully loaded. I would expect the 'Save' button to be disabled before the product is fully loaded.

**To Reproduce**
1. Go to 'Catalog / Products'
2. Click on an existing product with combinations
3. Click on 'Save' before the combinations is loaded
4. See error 'Unable to update settings'

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @R-Larsson,

Thanks for your report.
I have the same behavior as PS1.7.6.0 & PS1.7.5.2.
https://drive.google.com/file/d/1PnKJ-Ckabg-uRCm0Kb4b7RdTI0Iew7S1/view
Ping @marionf, @colinegin, it could be a could improvement to disable the button until the combinations are fully loaded, what do you think?

Thanks!

**Comment by nazimgel** [comment]
I have the same issue but i think it is not about combinations. Because also i can't create product.
PrestaShop version: 1.7.6.0
PHP version: 7.1.30

https://drive.google.com/file/d/1pjAG93ybYhiQoFYJpNqdYPgXF0DVkdrL/view

**Comment by khouloudbelguith** [comment]
Hi @nazimgel,

Your issue is different.
In my case it is OK
https://drive.google.com/file/d/1-gEvLQCNYSKczA60vmC8FIyUD5eYzP94/view
Can you open a new one with more information about your configuration?

Thanks

**Comment by marionf** [comment]
Yes, if you connection is bad (try to select 3G connection on Chrome debug toolbar) when you access the product page, you should see that the save/generate actions are disabled
Work was started but PR has been closed: https://github.com/PrestaShop/PrestaShop/pull/8439

**Comment by MatShir** [comment]
It should be fixed with the new product page on 8.1 :)
