### ISSUE TITLE
Error msg when saving customer in PS 1.7.6

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#14915]
When saving / updateing a customer in BO, this strange error comes.
(if there is an invalid symbol in name etc. "/")
Shouldn't there be an error saying invalid symbol ? 
Also why is "/" not possible in name ?
![save-name](https://user-images.githubusercontent.com/19774996/62122446-fa59c780-b2c5-11e9-88b1-e97a25578a9d.PNG)

**Comment by khouloudbelguith** [comment]
Hi @thbl,

We are aware of this issue.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14838 to fix the issue.
Your ticket is a duplicate of #14157
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14157
