### ISSUE TITLE
Can't udpate combinations in product

### ISSUE THREAD

**Issue by biaggio12** [PrestaShop/PrestaShop#14919]
**Describe the bug**
You can only create combinations for product once. When you try to generate more combinations after the attributes are not applied for product

**To Reproduce**
[https://youtu.be/J9lCDCNL-SY](url)
1. Add combinations
2. Save product
3. Check for product combinations in FRONT view
4. Add another combinations to same product
5. New combinations are not available

**Screenshots**
Here's video how to reproduce bug.
https://youtu.be/J9lCDCNL-SY
**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment]
Hi @biaggio12,

Your combinations are not correctly generated in the second time.
Then, in the right column, you should select all your combinations (from your 1 group and click on "Generate" => like the first time
In the combination list, every combination needs to have the same attributes as the others. I mean you can't have, in the same product, combinations with colors & size and some others with dimensions.
All of them need to have color + size + dimension or color or size or dimension.

First, you should delete all your combinations & re-cretae them.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @biaggio12,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
