### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column - Database ps_admin_filter error

### ISSUE THREAD

**Issue by coffeebean19** [PrestaShop/PrestaShop#14911]
**Describe the bug**
Error when try to open Catalog->Brands in the Back Office.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_lang' in 'order clause'
For some reason it cleans database all the time - screenshoots. Used the solution from #14617 but not helped.

**To Reproduce**
1. Go to BO->Catalog->Brands
2. Error 500

**Screenshots**
<img width="1091" alt="Zrzut ekranu 2019-07-29 o 16 48 20" src="https://user-images.githubusercontent.com/53439246/62111099-1fdbd680-b2b0-11e9-8ee7-0a7c5e624f1b.png">
<img width="1267" alt="Zrzut ekranu 2019-07-29 o 21 11 38" src="https://user-images.githubusercontent.com/53439246/62111107-2407f400-b2b0-11e9-9abd-d8ba727693b2.png">
<img width="1252" alt="Zrzut ekranu 2019-07-29 o 21 13 15" src="https://user-images.githubusercontent.com/53439246/62111117-2d915c00-b2b0-11e9-93c5-d68425967c84.png">
<img width="1056" alt="Zrzut ekranu 2019-07-29 o 21 12 56" src="https://user-images.githubusercontent.com/53439246/62111128-34b86a00-b2b0-11e9-9325-ccc7a3c7b262.png">

**Comment by khouloudbelguith** [comment]
Hi @coffeebean19,

Did you make an upgrade from a previous version PrestaShop? or it is a fresh installation?

Thanks!

**Comment by coffeebean19** [comment]
> Hi @coffeebean19,
> 
> Did you make an upgrade from a previous version PrestaShop? or it is a fresh installation?
> 
> Thanks!

**Comment by coffeebean19** [comment]
It was upgrade from 1.7.4.2

**Comment by khouloudbelguith** [comment]
@coffeebean19, what is the exact version of the module 1-click upgrade did you used?
Are there any errors displayed during the upgrade?
Thanks!

**Comment by coffeebean19** [comment]
Yes 1-click upgrade. I had also errors from #14617

**Comment by khouloudbelguith** [comment]
@coffeebean19, have tried with this solution?
https://github.com/PrestaShop/PrestaShop/issues/14617#issuecomment-511737940
>Provisional solution:
ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;

Thanks!

**Comment by coffeebean19** [comment]
Yes it helped, but not for brands page.

**Comment by khouloudbelguith** [comment]
@coffeebean19, could you please provide me the structure of your table `ps_manufacturer_shop`.
![image](https://user-images.githubusercontent.com/16067358/62147113-c0e98200-b2ee-11e9-99fa-36881b753443.png)

Thanks!

**Comment by coffeebean19** [comment]
Take a look. 
<img width="967" alt="Zrzut ekranu 2019-07-30 o 18 52 02" src="https://user-images.githubusercontent.com/53439246/62149106-4a06b600-b2fb-11e9-88a8-87cf70fffb00.png">

**Comment by khouloudbelguith** [comment]
@coffeebean19, sorry, I mean the `ps_manufacturer_lang` table.
Thanks!

**Comment by coffeebean19** [comment]
Looks the same:
<img width="913" alt="Zrzut ekranu 2019-07-31 o 15 07 41" src="https://user-images.githubusercontent.com/53439246/62214307-14b6a280-b3a5-11e9-89ad-3620df851e0b.png">

**Comment by khouloudbelguith** [comment]
@coffeebean19, thanks!
In my case, I did not manage to reproduce the issue with PS1.7.6.0 after upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0.
It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.6.0
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.6.0 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/install-dev/data/db_structure.sql

Thanks to check & feedback

**Comment by coffeebean19** [comment]
@khouloudbelguith please take a look again a the logs. I'm really not able to resolve the issue. Every time I fill empty column at database it cleans another.

<img width="1086" alt="Zrzut ekranu 2019-08-3 o 14 13 47" src="https://user-images.githubusercontent.com/53439246/62411825-6bb4b580-b5f9-11e9-8b9e-a1c9725a31e9.png">

<img width="1086" alt="Zrzut ekranu 2019-08-3 o 14 14 05 kopia" src="https://user-images.githubusercontent.com/53439246/62411858-03b29f00-b5fa-11e9-8618-dc20a9a9497f.png">

**Comment by coffeebean19** [comment]
I have downgraded to lower version. Next time please test the relased version twice. 1.7.6.0 is called as a stable version, but it is not. You can't even manage your brands and products via admin. So it's just a waste of time for using the version filled with bugs.

**Comment by khouloudbelguith** [comment]
Hi @coffeebean19,

Sorry for this bug.
But in our case, we did not manage to reproduce the issue with PS1.7.6.0 fresh install & after an upgrade from a Previous Version.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!

**Comment by ibrahimfsasmaz** [comment]
Hello,

I have the same problem I upgraded with 1 click upgrade from prestashop 1.7.5.1 to 1.7.6.2 stable.
"catalog>categories" , "catalog>discount>create new cart rule" and some other links are not working..
Is there any fix pls ?

**Comment by ibrahimfsasmaz** [comment]
Is there a way to return 1.7.5.1 without loosing the new order coming at the moment to the 1.7.6.2 version pls ? 
Or is there a way to make a fresh installation and add all existing orders, themes and settings on the new fresh installation pls ?

**Comment by ibrahimfsasmaz** [comment]
> Hi @coffeebean19,
> 
> Sorry for this bug.
> But in our case, we did not manage to reproduce the issue with PS1.7.6.0 fresh install & after an upgrade from a Previous Version.
> As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
> 
> Thanks!

Could you pls help me 
every time that I upgrade I am in trouble

**Comment by ibrahimfsasmaz** [comment]
> @coffeebean19, thanks!
> In my case, I did not manage to reproduce the issue with PS1.7.6.0 after upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0.
> It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.6.0
> The solution is to add the missing columns to your database schema.
> You can find the full schema for 1.7.6.0 here:
> https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/install-dev/data/db_structure.sql
> 
> Thanks to check & feedback

I guess I have exact same problem, how can I find the missing tables or columns pls ? is there a quick way

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/16795
