### ISSUE TITLE
Error in basic product settings

### ISSUE THREAD

**Issue by samcristoper** [PrestaShop/PrestaShop#14924]
I have an error in the basic settings of the products
I have the same modules installed on LocalHost and on my server the same modules, the same template all ran well perfectly, since yesterday trying to change delete the images in the Module of basic product settings does not load the window that allows to put an image As product cover or delete, when I do the same in my localhost this is done without any problem.
 
Then I leave the code that appears in both cases

1 Hosted on the web

`<div id="product-images-form-container" class="col-md-4">
                <div id="product-images-form"></div>
              </div>﻿`

2 Hosted in local area

`<div id="product-images-form"><button type="button" class="float-right close" onclick="formImagesProduct.close()"><i class="material-icons">close</i></button>

<div class="row">
    <div class="﻿col-lg-12 col-xl-7">
      <div class="checkbox">                          
            <label><input type="checkbox" id="form_image_cover" name="form_image[cover]" value="1">
Imagen de portada</label>
          </div>
    </div>
    <div class="col-lg-12 ﻿col-xl-4">
        <a href="/1760mimallweb/img/p/2/5/25.jpg" class="btn btn-link btn-sm open-image" target="_blank">
          <i class="material-icons">zoom_in</i> Zoom
        </a>
    </div>﻿
</div>

<label class="control-label">Leyenda</label>
    
    <div class="translatio﻿ns tabbable" id="form_image_legend">
        
        <div class="translationsFields tab-content">
                            <div da﻿ta-locale="pe" class="translationsFields-form_image_legend_2 tab-pane translation-field show active translation-label-pe">
                    
                    <textarea id="form_image_legend_2" name="form_image[legend][2]" class="form-control"></textarea>
  
                </div>
                    </div>﻿
    </div>﻿

<div class="actions">
    <button type="button" class="btn btn-sm btn-primary pull-sm-right" onclick="formImagesProduct.send(25)">Guardar los ajustes de imágenes</button>
    <button type="button" class="btn btn-sm btn-link" onclick="formImagesProduct.delete(25)"><i class="material-icons">delete</i> Eliminar</button>
</div>
</div>﻿﻿﻿﻿﻿`
I leave the images below to have a clearer idea of ​​what my words say, the order in which I present the coding

 I hope someone can help me solve this problem, which is perhaps that of many of us who use prestashop

I will leave some other information that may be necessary

Server software version: Apache

PHP version: 7.2.19

Store URL: http://www.mimallweb.com/

Prestashop 1.7.6.0
 

I hope your kind and kind help
THANK YOU

![image](https://user-images.githubusercontent.com/44956272/62179493-6cf09480-b312-11e9-9ef7-ce50b7762329.png)
![image](https://user-images.githubusercontent.com/44956272/62179501-7679fc80-b312-11e9-9f5f-c74dfef962a3.png)

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @samcristoper, 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by samcristoper** [comment]
I put prestashop in debug mode and this is what appears on my website


(1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in posstaticblocks.php line 125
at posstaticblocks->hookDisplayNav(array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 970
at HookCore::coreCallHook(object(posstaticblocks), 'hookdisplayNav', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' =>object(Cart), 'altern' => 1))in Hook.php line 355
at HookCore::callHookOn(object(posstaticblocks), 'displayNav', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' =>object(Cart), 'altern' => 1))in Hook.php line 907
at HookCore::exec('displayNav', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayNav'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayNav'), object(SmartyDevTemplate)))in d2f52286fcf736fb584c5491492dec88e4c53cd6_2.file.header.tpl.php line 73
at Block_19783442475d4866ecf27e80_84990741->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_19783442475d4866ecf27e80_84990741), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_19783442475d4866ecf27e80_84990741))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_19783442475d4866ecf27e80_84990741', 'header_nav')in d2f52286fcf736fb584c5491492dec88e4c53cd6_2.file.header.tpl.php line 31
at content_5d4866ecf2f543_67621737(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('file:_partials/header.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 0, false)in f7618bf4cb83fcd00be3dfd4fa712e240a59c387_2.file.layout-both-columns.tpl.php line 224
at Block_16391542995d4866ece94f31_56602309->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_16391542995d4866ece94f31_56602309), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_16391542995d4866ece94f31_56602309))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_16391542995d4866ece94f31_56602309', 'header')in f7618bf4cb83fcd00be3dfd4fa712e240a59c387_2.file.layout-both-columns.tpl.php line 63
at content_5d4866ecec2f48_04676115(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in 232d14e01d1afa163ed6b34970fe530ca0a1b24f_2.file.layout-full-width.tpl.php line 42
at content_5d4866ece7e676_81094593(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 1b54af26a5736e32cd0f3899ba032abb93d87818_2.file.page.tpl.php line 33
at content_5d4866ece693e5_94390435(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in ee7c0abb07f36a0e7a4d1473b92eef0fa4367ede_2.file.index.tpl.php line 33
at content_5d4866ece53dd5_96337691(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('index.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('index.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('index.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 311
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

![1](https://user-images.githubusercontent.com/44956272/62483839-4c936080-b77e-11e9-875a-a00c85a7a455.PNG)

**Comment by samcristoper** [comment]
[www.mimallweb.com.pdf](https://github.com/PrestaShop/PrestaShop/files/3468735/www.mimallweb.com.pdf)

**Comment by khouloudbelguith** [comment]
@samcristoper, this issue occurs due to the `posstaticblocks` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
