### ISSUE TITLE
404 error on quick view and adding multiple products to cart

### ISSUE THREAD

**Issue by sunnmagic** [PrestaShop/PrestaShop#14921]
Hello,

It is about this website under 1.7.5.2: https://www.lightpainting-shop.com/

. If you try to use the quick view button on a product, nothing happens and you got a 404 error in the console log
. On a product page, if you change quantities then add to cart, you got the message "An error occurred while processing your request", with a 404 in the console log too

Same problem with the dev website under 1.7.6 and the classic theme: https://www.lightpainting-shop.co.uk/

Does anyone has a solution?

**Additional information**
PrestaShop version: 1.7.5.2 AND 1.7.6
PHP version: 7.0.27

**Comment by khouloudbelguith** [comment]
Hi @sunnmagic,

I did not manage to reproduce the issue with PS1.7.6.0.
https://drive.google.com/file/d/1ydXVeDw9V8kCJRydRShbcinBtyHxhW6p/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sunnmagic** [comment]
Hi! 

Thanks for your answer. What is the "debug mode report", where can I find a report?

**Comment by khouloudbelguith** [comment]
@sunnmagic, when debug mode is enabled, in the FO, when you click on the "Quick view" there is no exception displayed?

Thanks!

**Comment by sunnmagic** [comment]
Nothing at all... actually https://www.lightpainting-shop.co.uk/fr/ is in debug mode.

So, I've collected all the necessary informations:

- host : syntis.net
- server setup and configuration : Linux CentOS 6.10 x64 / Apache 2.2 / PHP : 7.0.27 / MySQL/MariaDB : 5.5.55
- PrestaShop version : 1.7.6
- debug mode report : none
- PHP error logs : none
- apache error log : [apache.txt](https://github.com/PrestaShop/PrestaShop/files/3450967/apache.txt)


- javascript console log:
[addtocart.log](https://github.com/PrestaShop/PrestaShop/files/3450884/addtocart.log)
[quickview.log](https://github.com/PrestaShop/PrestaShop/files/3450885/quickview.log)


Thanks :)

**Comment by khouloudbelguith** [comment]
@sunnmagic, Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by sunnmagic** [comment]
Done, but same problem :(

**Comment by khouloudbelguith** [comment]
@sunnmagic, could you please try to restart your server & clear cache.

Thanks!

**Comment by sunnmagic** [comment]
Server rebooted and Prestashop cache cleared, but same problem :(

**Comment by khouloudbelguith** [comment]
@sunnmagic, did make any changes in your project or did you installed any custom module before this issue occurs?

Thanks!

**Comment by sunnmagic** [comment]
Some modules are installed, but all came from Addons.

**Comment by khouloudbelguith** [comment]
@sunnmagic, did you installed them before having this issue?

Thanks!

**Comment by sunnmagic** [comment]
Impossible to remember...

**Comment by khouloudbelguith** [comment]
@sunnmagic,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by sunnmagic** [comment]
FYI I've tried with "Disable non PrestaShop modules" and "Disable all overrides" to "YES", then cache cleared, but nothing changed.

Here are the results of this file:

![config](https://user-images.githubusercontent.com/50998197/62224042-484df880-b3b6-11e9-802e-f85f9fdf86f6.JPG)

**Comment by khouloudbelguith** [comment]
@sunnmagic, those options don't work as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9965 and here: https://github.com/PrestaShop/PrestaShop/issues/14596

In the BO => Shop Parameters => Traffic & SEO => you don't have any alerts about friendly URL?
Thanks!

**Comment by sunnmagic** [comment]
I got "URL rewriting (mod_rewrite) is not active on your server, or it is not possible to check your server configuration. If you want to use Friendly URLs, you must activate this mod."

But URL rewriting is working, so the mod seems fine.

**Comment by khouloudbelguith** [comment]
@sunnmagic, yes, this is the exact issue.
You have an issue on your server with mod rewrite, you need to check with your host about this issue.

PS: if you disable the option friendly URL => No error.
Thanks!

**Comment by sunnmagic** [comment]
Weird... but thanks, I will talk with my host!

Thank you very much for your help :)

**Comment by khouloudbelguith** [comment]
@sunnmagic, thanks!
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks!

**Comment by sunnmagic** [comment]
Good to know, I will let you know what the solution is, we never know, if someone has the same problem!

**Comment by Flying--Dutchman** [comment]
For anyone still getting this issue;

The reason for this issue is probably beacause you are running your PrestaShop with NGINX (either as a **server** or **reverse proxy**) and did not setup NGINX correctly: https://devdocs.prestashop.com/8/basics/installation/nginx/.

Check the line with:
```
rewrite ^/fr$ /fr/ redirect;
rewrite ^/fr/(.*) /$1;
```

And change `fr` to your language you are using. Add the same block for all your languages.

If your site does not work after that, you are probably running NGINX as a reverse proxy with Apache as server (e.g. standard Plesk setup). In that case, the easiest fix would be to simply pick one. Otherwise you can check out [this post](https://www.prestashop.com/forums/topic/638424-prestashop-configuration-with-apache-and-nginx/?tab=comments#comment-2648015) and create a correct rewrite.

----------------------------------------------
EDIT:
Currently removed the official multi-language solution:
```
rewrite ^/fr$ /fr/ redirect;
rewrite ^/fr/(.*) /$1;
```

and replaced it with the one from the link above:
`rewrite '^/((?!js|qq)[a-z]{2})/(.*)' /index.php?isolang=$1&$args last;`

`(?!js|qq)` This part makes sure that the folder /js/ does not get blocked, which is needed for the backend. I added `qq` to show how to add multiple exclusions.


Everything seems to be working fine :+1:
