### ISSUE TITLE
Database translations not taken into account by modules

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#14932]
**Description**
Modules translations stored in database are not taken into account. So users can't modify their module's translations.

**To Reproduce**
1. Go to international > translations > installed modules translations
2. choose a module, change its translations
3. go to the modified module's configuration and check that wording has changed

**Additional information**
PrestaShop version: 1.7.6.x

**Comment by studio1one** [comment]
I have almost the same issue in 1.7.6 new fresh installation: I go to translation>installed modules but get an red error flag (There is no translation file available ) And I have installed the Swedish language pack twice and nothing change.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14966
