### ISSUE TITLE
Upgrade to jQuery latest, use jQuery migrate for retro compatibility 2/4 - DEFAULT THEME BO

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14930]
EPIC : #13829

**Please update the EPIC after completion**

We are currently using old or very old versions of jQuery. These versions have never been upgraded because of breaking changes introduced in later versions. Using jQuery Migrate we could upgrade them to the latest version without breaking backward compatibility.

**Comment by matthieu-rolland** [comment]
Here is the official migration guide:

https://jquery.com/upgrade-guide/3.0/#overview

We already use a jquery-migrate (version 1.2.1) in the back office, it can't be used simultaneously with jquery-migrate 3.x, so we have to update our jquery first.

**Comment by matthieu-rolland** [comment]
I had to do a modification in the dashactivity module because otherwise it would bring it's own jquery (yolo).

https://github.com/PrestaShop/dashactivity/pull/16

**Comment by jolelievre** [comment]
> I had to do a modification in the dashactivity module because otherwise it would bring it's own jquery (yolo).
> 
> [PrestaShop/dashactivity#16](https://github.com/PrestaShop/dashactivity/pull/16)

Yep just like many other modules I guess :P
Maybe we should add some filters in the `addJs` method to prevent the modules from adding a useless jquery version? (if it's an older version than 3.4.1)
