### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#14942]
I can not find a way to insert any HTML code into the product descriptions, In the setting on the left Shop Peramiters / General / Allow iframes on HTML fields select to YES but I can still not enter anything is it possible I'm using the latest version 1.7

Any Ideas?

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

For example in the BO => Catalog => Products => Summary & description section, you can click on the icon code o insert any HTML code
I attached a screen record for more details
https://drive.google.com/file/d/1PPTr6ko2NgUkiAkH1cRgQMrds5_U4wsB/view
I close the issue, feel free to open a new one when needed.

Thanks!
