### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_customer' in 'order clause'

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#14944]
**Describe the bug**
I get a 500 error qhen trying to access the Brands Page on the Backoffice:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_customer' in 'order clause'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/12779551/62257381-1449f600-b3fd-11e9-9241-2c72a06283c3.png)
![image](https://user-images.githubusercontent.com/12779551/62257406-2deb3d80-b3fd-11e9-90aa-1a6daad8a199.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @psydomin,

It is a fresh install PS1.7.6.0 or an upgrade from a previous version?
It seems to be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/14911

Thanks!

**Comment by psydomin** [comment]
> Hi @psydomin,
> 
> It is a fresh install PS1.7.6.0 or an upgrade from a previous version?
> It seems to be related to this issue: #14911
> 
> Thanks!

Hey @khouloudbelguith 
It is an update from 1.7.4.0.
It is possible that it is related. I didnt notice if there was any error while updating but I did have to manually fix the same problem as #14617 as I was getting some 500 errors in some pages in the back office. After fixing that only the brands page continues to give 500 error.
Any idea of which table's structure should I compare to the schema?

**Comment by khouloudbelguith** [comment]
@psydomin, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
In my case, it is Ok after upgrade from PS1.7.5.2 to PS1.7.6.0 using the 1-click upgrade v4.9.0.
Thanks!

**Comment by psydomin** [comment]
Here it is. I can see that there were some errors. 
Any idea how I can manually fix them? I cant just rollback and upload the db backup because it is a working website and there has already been loads of orders/ new messages and clients since the upgrade. Everything seems to be working except that
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3458223/log.txt)

**Comment by khouloudbelguith** [comment]
@psydomin, in your log file, you have two errors
>[2018-07-14 04:09:14] 04:09:14 ERROR     [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "The table with name 'vivumcom_prestashop.psbl_prestools_diskspace' already exists." ["exception" => Doctrine\DBAL\Schema\SchemaException { …},"command" => "prestashop:schema:update-without-foreign","message" => "The table with name 'vivumcom_prestashop.psbl_prestools_diskspace' already exists."] []

This table is added with a custom module?

>[2019-07-30 02:23:56] Error during database upgrade. You may need to restore your database.

You have some errors during the upgrade of your database

There is something went wrong with your update and don't have some of the database columns that were added for 1.7.6.0
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @psydomin, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
