### ISSUE TITLE
Missing app_icon.png on BO - Firefox browser

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#14954]
**Describe the bug**
On fresh install of PS 1.7.6.0 is missing `app_icon.png` image on back-office:

![app_icon](https://user-images.githubusercontent.com/7419525/62300532-47c96680-b477-11e9-9f93-919a5b1efff1.png)

File is called on default admin theme:
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/template/header.tpl#L31

But no file exists in `img/` folder:
https://github.com/PrestaShop/PrestaShop/tree/develop/img

Does this file is really necessary? If yes, why it doesn't exists and why it can't be uploaded from BO?

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

In which page from the BO, the error in the console is displayed?
In my case, there is no 404 error in the Network tab.

Thanks!

**Comment by Klemart3D** [comment]
Every page of BO, included dashboard (I tried on another instance of PS and I get the same):

![404](https://user-images.githubusercontent.com/7419525/62310749-7d2b7f80-b48a-11e9-9d03-af64bc52dc71.png)

Do you have no request to `app_icon.png` or your request is successful (200 code)?

**Comment by khouloudbelguith** [comment]
@Klemart3D,

No, I don't have any requests for the `app_icon.png`.
I attached a screen record
https://drive.google.com/file/d/1fELVQ8YhjtzIVIr3j5BWUjO37D4aa5_d/view
Thanks to check & feedback

**Comment by Klemart3D** [comment]
You're on Chrome? I tried with Chrome v.75 on Linux and you're right: no request to app_icon.png found.
Error seems only appears on Firefox (I'm on v.68)

**Comment by khouloudbelguith** [comment]
@Klemart3D, yes, you are right.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2 using the browser Firefox v64.0.2.
![image](https://user-images.githubusercontent.com/16067358/62365466-1191f280-b51c-11e9-913d-f8c0377d6e9b.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by evgenij-sobolev** [comment]
The same problem on Presatshop 1.7.6.4  and  Firefox 74
