### ISSUE TITLE
Get full info about product incl. all prices, discount, VAT

### ISSUE THREAD

**Issue by georgikolev7** [PrestaShop/PrestaShop#14969]
I'm opening a new issue, because the previous one #14961  was closed by @khouloudbelguith 

Based on the explanation in the previous issue I open, here is the result. (I'm using demo product)

VAT is 22%.
We have a product with price 23.90 EUR excl. VAT, which become 29.15 EUR incl. VAT.

![1234134](https://user-images.githubusercontent.com/3003037/62367563-5a50a800-b52a-11e9-8023-866e0889da6c.png)

Based on @khouloudbelguith tips, I can send a web service request

`api/products/1?price[price][use_tax]=1&price[price]`

And here is the response (unnecessary data is cutted)

```
{
    "product": {
        "id": 1,
        "id_tax_rules_group": "53",
        "price": "23.330000",
        "wholesale_price": "0.000000",
        "available_now": "",
        "available_later": ""
    }
}
```
With the 2nd call suggestion
`api/products/?display=full&price[price][use_tax]=1&price[price][country]=193`

the response is the same.

So as you can see, with this calls I cannot understand what is the regular price for this product, is this product have VAT (how much it is), is there a discount price, 

It will be good if there is a more information about the product like

```
{
    "product": {
        "id": 1,
        "id_tax_rules_group": "53",
        "tax_rate": "22.000",
        "regular_price_excl_tax": "100.00",
        "regular_price_incl_tax": "122.00",
        "wholesale_price": "0.000000",
        "available_now": "",
        "available_later": ""
    }
}
```
And please don't close the issue, maybe other programmers also need such improvements.

**Comment by khouloudbelguith** [comment]
Hi @suncho26,

I attached a video record
http://projet/QA/1760fr/api/products/43?price[price][use_tax]=1&price[price][country]=3
Thanks to check & feedback.

**Comment by georgikolev7** [comment]
Hi @khouloudbelguith, can you check the link please.

**Comment by khouloudbelguith** [comment]
@suncho26, sorry, but what is the exact link?
Thanks!

**Comment by georgikolev7** [comment]
I'm closing the issue, since I think there is no adequate answer on the subject by the developers of PrestaShop.

**Comment by mariem-abid** [comment]
Hi @suncho26,

Feel free to open a new one when needed.

**Comment by teloconf** [comment]
Hello, I have seen that this thread is open. I have come to the solution from another site but I write it here in case someone is interested.
http(s)://TOKEN@SITE/api/products/ID_PRODUCT?price[my_price][use_reduction]=1
With this call we have a new field called "my_price" which is the price with taxes and discount applied
