### ISSUE TITLE
Importing a theme that has a translations folder but no files in it will throw an exception

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#14960]
**Describe the bug**
When loading a theme, ThemeManager will try to load its translations if the translations directory is present. But if it's present AND empty it would throw an exception.

**To Reproduce**
1. Create a theme that is not named classic, make sure there's a translations directory in it with nothing inside.
2. Zip it
3. Try to import it into PS.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

I tried to import a theme with nothing inside the translations directory.
I have this error
![image](https://user-images.githubusercontent.com/16067358/62536699-829c1780-b846-11e9-8670-e0a24fba4fe8.png)
I tried also with a child theme => Same behavior
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/3471937/childtheme-example.zip)

Only this error, without exception.
=> issue created https://github.com/PrestaShop/PrestaShop/issues/15004
Thanks!
