### ISSUE TITLE
Get full info about product, including all prices + VAT throught WebService

### ISSUE THREAD

**Issue by georgikolev7** [PrestaShop/PrestaShop#14961]
Hey everyone,

I'm integrating other system with PrestaShop WebService and I'm searching for the right call to can get all the info for product with one call.

**What I mean**

Product XXX have a price 100 EUR excl. VAT.
VAT is 20%, so the price become 120 EUR incl. VAT.
The product have 10% discount of the price, so final price will be 108 EUR incl. VAT. or 90 EUR excl. VAT.

When I make a web service call I just see "Price is 100 EUR".

To understand everything writen above - is this product have a VAT, how much is it, is there a discount of this price etc. I should create multiple requests for taxes, tax_rules, tax_rule_groups and more.

Is there a more simple way/call for all this?

**Comment by khouloudbelguith** [comment]
Hi @suncho26,

You can follow our documentation http://doc.prestashop.com/display/PS16/Chapter+10+-+Price+management
For the individual products you can specify e.g. /api/products/1?price[price][use_tax]=1&price[price][country]=3
Also, you can use this link: api/products/?display=full&price[price][use_tax]=1&price[price][country]=3 to get product list with tax in webservice.

Thanks!

I close the issue, feel free to open a new one when needed.

Thanks!
