### ISSUE TITLE
I want to import product in prestashop || So need product sample csv file,Why so difficult to import products?  

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14965]
**
I'm getting this  
Errors occurred:
The category ID must be unique. It can't be the same as the one for Root or Home category.
i already tried this link
https://github.com/PrestaShop/PrestaShop/issues/9764

plz share product import csv file format 
**

**Comment by khouloudbelguith** [comment]
Hi @dharmendravirasat,

In your BO => Advanced Parameters => Import Page => you have a simple Products file.
Also, if you want to import products, you need to the "What do you want to import?" option to Products.
![image](https://user-images.githubusercontent.com/16067358/62356597-5e200280-b509-11e9-8dbf-4efb437936a8.png)

Thanks to check & feedback.

**Comment by dharmendravirasat** [comment]
I'm already tried this
Errors occurred:
The category ID must be unique. It can't be the same as the one for Root or Home category.
![image](https://user-images.githubusercontent.com/44469219/62357589-009fac00-b531-11e9-871f-9261099ee397.png)
![image](https://user-images.githubusercontent.com/44469219/62357600-08f7e700-b531-11e9-8942-d2adf3663fa2.png)
![image](https://user-images.githubusercontent.com/44469219/62357659-275de280-b531-11e9-8b9d-35f892368093.png)
and category also there 
![image](https://user-images.githubusercontent.com/44469219/62357687-38a6ef00-b531-11e9-9dfd-213855b98258.png)

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, the select option in your case is incorrect.
You want to import products, you need to the "What do you want to import?" option to Products.
https://drive.google.com/file/d/1ohpLDDEmXkItVEb3rFtTtdX7ubaGD4id/view
Thanks!

**Comment by dharmendravirasat** [comment]
Its working fine 
thanks for reply

**Comment by khouloudbelguith** [comment]
@dharmendravirasat, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
