### ISSUE TITLE
Paypal doesnt appear in shoppign cart

### ISSUE THREAD

**Issue by vagaluz** [PrestaShop/PrestaShop#14975]
Hello, Paypal doesnt appear in shopping cart.

1. Go to some product add to cart process payment fill the formularies and in payment method paypal doesnt appear.

![Sin-título-1](https://user-images.githubusercontent.com/52562703/62382927-ebd21100-b54e-11e9-9c66-0426b7c7e2c2.png)

But in paypal module says 

**You are trying to switch to a production account. You must use your production credentials. Access the Products tab and click Modify to activate the production version of the selected product.**

but i dont find that product credentials.. can someon explaine me how to do this?

THANKS

PrestaShop version: 1.7.5.1
PHP version: 7.1.17

**Comment by khouloudbelguith** [comment]
Hi @vagaluz,

I did not manage to reproduce the issue with PS1.7.6.0 & the Paypal module v4.5.0.
I attached a screen record
https://drive.google.com/file/d/1m3gbESiRqsvcmfVrFGRMbHRA7CTDbUNA/view
Your module is well configured?
In your BO => Payment => Preferences => did you check the restrictions?

Thanks!

**Comment by vagaluz** [comment]
I think i dont have the same paypal you have. the only one that appear to me as free is paypal & braintree

**Comment by vagaluz** [comment]
The restrictions are ok

**Comment by vagaluz** [comment]
Also this appear in red but i dont know how to do it.

You are trying to switch to a production account. You must use your production credentials. Access the Products tab and click Modify to activate the production version of the selected product.


![1](https://user-images.githubusercontent.com/52562703/62388533-d31d2780-b55d-11e9-8a38-2c8b1965f0da.PNG)

**Comment by khouloudbelguith** [comment]
@vagaluz, Thank you for your message.
Could you please contact our support team via [module page on PrestaShop Addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748)?
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
