### ISSUE TITLE
problem with the classes / language.php file (line 809) 

### ISSUE THREAD

**Issue by jhuanmy** [PrestaShop/PrestaShop#14978]
**Describe the bug**
I was reviewing version 1.7.6.0 and found that when I try to enter the configurations of a module this problem appears to me.
with smarty
"The locale 1 is invalid"
in the next function
of the archive
classes / Language.php (line 809)

public static function getIsoByLocale ($ locale) {if (! Validate :: isLanguageCode ($ locale)) {throw new Exception ('The locale'. $ locale. 'is invalid'); } if ($ details = self :: getJsonLanguageDetails ($ locale)) {return $ details ['iso_code']; }

it is a module that is being developed .. and in prestashop 1.7.5.2 if it works and I can't find what the change is

**To Reproduce**
1. Go to 'module manager'
2. select module
3.  Click on configuration

**Screenshots**
![Captura de pantalla (53)](https://user-images.githubusercontent.com/41839809/62394583-40679300-b533-11e9-9459-d75d1234ca16.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.2.24

**Comment by khouloudbelguith** [comment]
Hi @jhuanmy,

Thanks for your report.
You have a bug with the `spfooterlinks` module.
Have you tried to contact the module author about this issue?
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
Hi @jhuanmy,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by yahyaefendy** [comment]
Hi I have the same error with jhuanmy. how to solve this error?

**Comment by rutuke121** [comment]
I have the same error with psblog 🙄

**Comment by khouloudbelguith** [comment]
Hi,

The `spfooterlinks` and the `psblog` modules are not developed by PrestaShop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by SergiuszZ** [comment]
Hi, 
my proposition ;-)
exchange
        if (!Validate::isLanguageCode($locale)) {
            throw new Exception('The locale ' . $locale . ' is invalid');
on 
        if ($details = self::getJsonLanguageDetails($locale)) {
            return $details['iso_code'];

**Comment by rederijker** [comment]
> Hi,
> my proposition ;-)
> exchange
> if (!Validate::isLanguageCode($locale)) {
> throw new Exception('The locale ' . $locale . ' is invalid');
> on
> if ($details = self::getJsonLanguageDetails($locale)) {
> return $details['iso_code'];

Great!

**Comment by guille889** [comment]
Somebody have the solution? Ty!!!

**Comment by tajriba** [comment]
@SergiuszZ thanks, can you explain what your code changes?

**Comment by SergiuszZ** [comment]
this code
-------------------
    public static function getIsoByLocale($locale)
    {
        if (!Validate::isLanguageCode($locale)) {
            throw new Exception('The locale ' . $locale . ' is invalid');
        }

        if ($details = self::getJsonLanguageDetails($locale)) {
            return $details['iso_code'];
        }

        return false;
    }
-----------------
==== replaced by ====
---------------
    public static function getIsoByLocale($locale)
    {
        if ($details = self::getJsonLanguageDetails($locale)) {
            return $details['iso_code'];
        }

        return false;
    }

**Comment by tajriba** [comment]
Merci. My questions was more like: any idea what things occurs this error? So I need to change this code, for what reason?
