### ISSUE TITLE
In Prestashop 1.7.6 is disappear colum quantity

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#14987]
After I updated Prestashop from 1.7.5 to 1.7.6 version, I see that on catalogue page is disappeared the column "Quantity". The same problem is on combination section of each product, where is disappear the column "Quantity".
So, now we cannot have idea of quantity remain of single product.

Please solve this issue as soon as possible an let me know.

**Comment by khouloudbelguith** [comment]
Hi @pollat,

I did not manage to reproduce the issue with PS1.7.6.0 after upgrade from PS1.7.5.2. using the 1-click upgrade v4.9.0.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by pollat** [comment]
Attached ther'is the screenshot
![problema-quantita](https://user-images.githubusercontent.com/9538665/62558705-d2480680-b879-11e9-96a8-dfc7b26db3d4.jpg)

**Comment by khouloudbelguith** [comment]
@pollat, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by pollat** [comment]
I doesn't have any particular php error (see image attache):
![ERROR-LOG](https://user-images.githubusercontent.com/9538665/62700996-7ef1c780-b9e3-11e9-813a-ac78d6af4b3b.jpg)

On Prestashop 1.7.6, on the catalogue page is happer a new column "Price (tax include)" and is disappear the column "Qy" (Quantity) I think is a bug or bad choice for this version.

**Comment by pollat** [comment]
...maybe I have only this advise (see image attached):
![error-2](https://user-images.githubusercontent.com/9538665/62701295-34bd1600-b9e4-11e9-8c28-44d004b1813d.jpg)

**Comment by khouloudbelguith** [comment]
@pollat, in my case it is Ok after upgrade from PS1.7.5.2.
You need to enable debug mode in your store and debug request which is sent for product Page in your browser, using DevTools, so:

1. enable debug mode
2. go to the product list page 
3. open up developer tools
4. go to Network tab
5. Reload the page
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by pollat** [comment]
@khouloudbelguith thanks for your help:
I follow your instructions, but I doesn't see any red error reported on "Network tab". 
The only 2 errors I see on "developer console" are these (see image attached):

![error-01](https://user-images.githubusercontent.com/9538665/62716653-c8054400-ba02-11e9-9036-462f4dc18064.jpg)

**Comment by pollat** [comment]
@khouloudbelguith thanks for your help, I solve my problem: 
the problem was not the update version, but that "stock manage" was disable, so quantity was not showed.

**Comment by khouloudbelguith** [comment]
@pollat, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
