### ISSUE TITLE
Duplicated Customer Accounts 1.7.x.x

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#14980]
I realized that since I moved to 1.7 version from times to times prestashop creates duplicated customer accounts, I mean the exact same account (name, surname, email etc) only differs the id.

I'm on 1.7.6.0 and this still happens.
I'm not able to reproduce it as it won't happen all the times.
I talked with the developers of the modules I use and this is not originated from any module.

I also found other reports on the comunity:

https://www.prestashop.com/forums/topic/689513-usuarios-duplicados/

I don't have guest checkout enabled.

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

The problem is that the guest account is not transformed into a customer account, it creates a second account.
###
_So, The problem is that the guest account is not transformed into a customer account, it creates a second account => there is no alert => visitors can do multiple orders with the same mail address => this is the whole issue => it needs to be specified by our developers._

We are aware of this issue.
Your ticket is a duplicate of #10122
Please follow #10122. 
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10122

**Comment by seederp2p** [comment]
I have not guest accounts. It's disabled

Please re-open.

**Comment by khouloudbelguith** [comment]
@seederp2p, so did you any custom module to sign in or registration?

Thanks!

**Comment by seederp2p** [comment]
I did use a GDPR module bought on prestashop official store.

**Comment by khouloudbelguith** [comment]
@seederp2p, this module?
![image](https://user-images.githubusercontent.com/16067358/62466427-2de69700-b789-11e9-8023-7e4254717c8c.png)

Thanks!

**Comment by seederp2p** [comment]
No.

This: https://addons.prestashop.com/en/legal/8123-data-privacy-extended-data-protection-law-gdpr.html

**Comment by khouloudbelguith** [comment]
@seederp2p, Have you tried to contact the module author about this issue?, in my case, I did not manage to reproduce the issue with PS1.7.6.0, after registration, only one customer is created.

Thanks!

**Comment by seederp2p** [comment]
They said that It is not their module.

If you check here there's more people with the same problem:

https://www.prestashop.com/forums/topic/689513-usuarios-duplicados/

**Comment by khouloudbelguith** [comment]
@seederp2p, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Betafer** [comment]
Any news about this problem ?
