### ISSUE TITLE
SEO preview on product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14984]
**Describe the bug**
1) The friendly URL in the SEO preview on product page doesn't update in live. 
If I change the friendly URL I need to save and refresh the page to see it in the preview.
It should be displayed directly like when I edit meta title & meta desc.

2) The SEO preview on product page isn't displayed in the selected language

**To Reproduce**
Steps to reproduce the behavior 1) :
1. Go to Catalog > Products > Edit a product
2. Change the friendly URL field
3. See it's not updates in the SEO preview

Steps to reproduce the behavior 2):
1. Make sure you have many languages installed
2. Go to Catalog > Products > Edit a product
3. Fill the meta title, meta desc & friendly URL fields in both language
4. See the SEO preview isn't displayed in the selected language

https://drive.google.com/file/d/1QMamx6OlAep6Tgsl6OIgwoal2hYSDvfF/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by MatShir** [comment]
It seems to be fixed 8.1 :)
