### ISSUE TITLE
403 Forbidden pop-up when selecting combination

### ISSUE THREAD

**Issue by fruitfreak** [PrestaShop/PrestaShop#14981]
1. Go to https://plante-protein.dk/protein-pulver/39-258-pulsin-supershake-vegansk-proteinpulver.html
2. Select between flavors - last one ('Immunity') has different sizes and instead of the sizes simply changing to the relevant ones, when selected - it triggers a pop-up error 403.
3. When you change back to to one of the other two variations - the pop-up triggers again.

http://prntscr.com/oo69jv

PS 1.7.6.0
PHP 7.2.20

Thanks guys :-)
Kind regards
Ivan

**Comment by khouloudbelguith** [comment]
Hi @fruitfreak,

This issue occurs with the `productextratabs` module.
![image](https://user-images.githubusercontent.com/16067358/62451672-9a9c6a00-b766-11e9-8dc7-40c55dd07821.png)

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
