### ISSUE TITLE
ps_featuredproducts Warning

### ISSUE THREAD

**Issue by thomas-coichot** [PrestaShop/PrestaShop#14990]
**Describe the bug**

ContextErrorException
Warning: A non-numeric value encountered in the ps_featuredproducts module in debug mode

**Screenshots**
![Capture d’écran 2019-08-05 à 14 33 28](https://user-images.githubusercontent.com/35110724/62465701-d26bd780-b78f-11e9-9994-bd2bdc4bd25c.png)
![Capture d’écran 2019-08-05 à 14 33 45](https://user-images.githubusercontent.com/35110724/62465705-d5ff5e80-b78f-11e9-923a-f37e0beb0adc.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2.16

**Comment by khouloudbelguith** [comment]
Hi @TwiX95,

I did not manage to reproduce the issue with PS1.7.6.0 & the ps_featuredproducts module.
I attached a screen record
https://drive.google.com/file/d/1kACwsz04OwFcNp6BhT16QDGyYIUNACqN/view
Thanks to check & feedback.

**Comment by thomas-coichot** [comment]
The bug initially comes from a module present in a purchased theme. The module in question is a duplicate of the ps_featuredproducts module. I can't find which variable is not numeric.

**Comment by khouloudbelguith** [comment]
@TwiX95, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
