### ISSUE TITLE
Uninstall A Theme 

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#15009]
How do I get rid of a bad theme, I need to uninstall a theme that I purchased as it's far to slow and full of bugs, I was much better with the free version provided by Prestashop

I can mess with the directory files but not the database but don't really want to if I can get away with it, there must be a way of uninstalling the theme, I can't even switch back to the old one as it's now no longer giving me the option to, Any Ideas?

![2019-08-06_202621](https://user-images.githubusercontent.com/52738920/62566171-a4b68980-b888-11e9-8313-670c838d845c.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

I did not manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.1.
![image](https://user-images.githubusercontent.com/16067358/62608422-b84d0900-b8f7-11e9-9827-fa4fc91a2607.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Allthejam** [comment]
I'm sorry, all I can suggest is that you log this template as not a good one to purchase. there have been so many issues after I installed it, it caused more problems than I can even list and I decided, in the end, to simply delete the database and remove all the files and simply start again here the theme in question - v1.0.1-ps_lingerie_307

Thank you and sorry if I wasted your time. and I really think there should be a simple uninstall tap for themes as well as modules.

**Comment by khouloudbelguith** [comment]
@Allthejam, thanks for your feedback.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
