### ISSUE TITLE
Key is not recognized as translatable in faceted search

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15007]
**Describe the bug**
Impossible to translate "Build attributes and features indexes".

**To Reproduce**
1. Go in the configuration panel of the Faceted Search module
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/32565890/62558852-1509de80-b87a-11e9-9341-17f32e39fe79.jpg)

**Additional information**
PrestaShop version: 1.7.5 + 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

Same issue with PS1.7.6.0 & PS1.7.5.2 & the ps_facetedsearch v3.2.0.
![image](https://user-images.githubusercontent.com/16067358/62608103-22b17980-b8f7-11e9-9051-3f3152aa3543.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by marionf** [comment]
This issue should be fixed in the core and not in the module

**Comment by PierreRambaud** [comment]
With the latest for https://github.com/PrestaShop/PrestaShop/issues/14932

I'm able to edit translations: 
![image](https://user-images.githubusercontent.com/1462701/63339997-5e603080-c346-11e9-9cee-8145b9016139.png)
![image](https://user-images.githubusercontent.com/1462701/63340003-63bd7b00-c346-11e9-9219-5205bcbf73f7.png)
