### ISSUE TITLE
Upload Quota Configuration bug

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#15006]
Hello

file - src\Adapter\Upload\UploadQuotaConfiguration.php
line - 81
function - updateFileUploadConfiguration

bug: `$uploadMaxSize = (int) str_replace('M', '', ini_get('upload_max_filesize'));`

in some cases upload_max_filesize setting in php.ini file has value not 2048M but 2G.
if value is 2G variable $uploadMaxSize is set to 2 (megabytes).

solution:
$php_upload_max_filesize = ini_get('upload_max_filesize');
$php_post_max_size = ini_get('post_max_size');
        if (strpos($php_upload_max_filesize, 'G') !== false) {
            $uploadMaxSize =  (int)str_replace('G', '', $php_upload_max_filesize) * 1024;
        }
        else {
            $uploadMaxSize = (int) str_replace('M', '', $php_upload_max_filesize);
        }
if (strpos($php_post_max_size, 'G') !== false) {
            $postMaxSize =  (int)str_replace('G', '', $php_post_max_size) * 1024;
        }
        else {
            $postMaxSize = (int) str_replace('M', '', $php_post_max_size);
        }
        $sizes = [
            'max_size_attached_files' => $uploadMaxSize,
            'max_size_downloadable_product' => $postMaxSize,
            'max_size_product_image' => $uploadMaxSize,
        ];

**Comment by khouloudbelguith** [comment]
Hi @zapper,
The 1G is not a supported value by Symfony.
An issue has already been created #10892

Thanks!

**Comment by khouloudbelguith** [comment]
Related to #14568.
