### ISSUE TITLE
Email Notifications - new_order

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#15001]
Hi,

We are not receiving email notifications of new orders. Just yesterday we received, but today several orders have dropped and we have not received email's.

I never changed the module configuration. and now even the site crashes when I have the active module

![image](https://user-images.githubusercontent.com/49063138/62535169-ad846c80-b842-11e9-8e5e-0d9bbb14d1e7.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.22

**Comment by khouloudbelguith** [comment]
Hi @JorgeNogueiraLFMPro,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
PHP error log:
Apache: /var/log/apache/php_error.log
Nginx: /var/log/php-fpm/default/error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
Server setup:
Operating system.
Type and version of webserver (Apache, Nginx, IIS, other).
Version of PHP.
Version of MySQL/MariaDB.
Make sure you have emptied PrestaShop’s cache!

[bGZtcHJvLmNvbS5lcnJvci5sb2c= (1).zip](https://github.com/PrestaShop/PrestaShop/files/3471916/bGZtcHJvLmNvbS5lcnJvci5sb2c.1.zip)

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, thanks for your feedback.

I found this error in your log file
>[Tue Aug 06 11:57:18.364551 2019] [php7:error] [pid 17155] [client 37.189.146.145:51135] PHP Fatal error:  Cannot declare class MailAlert, because the name is already in use in /home/lab/domains/lfmpro.com/public_html/modules/mailalerts/MailAlert.php on line 290, referer: https://www.lfmpro.com/pt/mirrorless

What is the exact version of the `mailalerts` module did you use?
Could you please try to reset it, clear cache, check & feedback.

**Comment by JorgeNogueiraLFMPro** [comment]
Hi,
I tried to do what you told me but still don't send new_order email. 
The error on the page has disappeared. 

Alertas por e-mail 
v2.1.1

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, in the BO => Advanced Parameters => Administration page, check if the option "Show notifications for new orders" is enabled.
![image](https://user-images.githubusercontent.com/16067358/62541416-a57ff900-b851-11e9-9283-b05915b6ec62.png)

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith yes as you can see it is active

![image](https://user-images.githubusercontent.com/49063138/62542256-59ce4f00-b853-11e9-9f08-11620626a81d.png)

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
![image](https://user-images.githubusercontent.com/49063138/62549263-17f7d580-b860-11e9-82dd-0ce0c1189110.png)

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, this exception is displayed in the Product page Front office?
This link: https://www.lfmpro.com/pt/profoto-connect#/251-compatibilidade-canon?
Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
This appear on category page.
This Link: https://www.lfmpro.com/pt/dslr

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, it is OK in my side
![image](https://user-images.githubusercontent.com/16067358/62551462-f7317f00-b863-11e9-89af-703d8c6758c9.png)

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
Yes I know it is working. What I sent you was when I turned on debug mode in BO. The only problem I have in the store is not receiving new_orders emails. Isn't it better to go to the site BO to test?

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Hlavtox** [comment]
@JorgeNogueiraLFMPro It could not be related to the module at all.

In my case, when I enable developer mode, Prestashop is unable to send any email.

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, from your BO => Advanced Parameters => Emails => Test Email is well sent?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith Yes I am receiving thank you

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, thanks!
Feel free to open a new one when needed.

**Comment by JorgeNogueiraLFMPro** [comment]
Hi,


After clearing the cache manually, we came across this situation that was not happening in my Pack's module. For the information I pointed out did not appear.

![image](https://user-images.githubusercontent.com/49063138/62618165-76c65900-b90b-11e9-9e69-7d0e63815fd4.png)

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, what is the exact issue on your screenshot?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
These values, stock and reference that appear below the product image did not appear before. And after we cleared the cache began to appear

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, about the stock, in your BO => Shop Parameters => Product Settings Page => "Display available quantities on the product page" option is enabled?

Thanks

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 

You can see what happens when I update the page, prices do not appear but when you finish updating the page they appear and should not appear.

[Mala Rígida DNP DS620.zip](https://github.com/PrestaShop/PrestaShop/files/3477015/Mala.Rigida.DNP.DS620.zip)

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, `show prices` option in your case is disabled?
Also, the `Display discounted price` option is disabled?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith This is active as this is within a module of making product packs. And no one changed the settings. They appeared because of clearing the cache manually.

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, 

>They appeared because of clearing the cache manually.

So, before clearing the cache => they are not displayed => error => they should be displayed because the option is enabled
After clearing the cache, they are displayed again.

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I was seeing but the settings are the same as before clearing the cache.

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, try to disable the "show price" option & the "display the quantity available" & check if they are still displayed?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I created some rules in css inside the module, it worked correctly. Thanks

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
