### ISSUE TITLE
Prestashop requests auto_increment_increment and auto_increment_offset to be set to 1

### ISSUE THREAD

**Issue by SniperCZE** [PrestaShop/PrestaShop#15019]
**Describe the bug**
Installation of prestashop fails when installed on mysql in master-master or multimaster galera setup. Instalator checks for auto_increment options are set to 1, which is incompatible with galera or M-M setup.

**To Reproduce**
1. Setup mysql cluster Master-Master or Galera
2. Start instalation process of prestashop
3. Point configuration to M-M or Galera cluster

**Expected**
Galera or M-M cluster setup is quite common to achieve HA for database, prestashop should not check auto_increment options and should be installable on M-M or Galera cluster.

**Comment by khouloudbelguith** [comment]
Hi @SniperCZE,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by matks** [comment]
Hi @SniperCZE I'm afraid current prestashop implementation relies very heavily on auto_increment strategy so it would need a very huge quantity of work to be able to stop using it, although it would be for the best (using UUID would solve multiple design issues in prestashop).

Your issue and request are relevant but honestly I dont think we will be able to address it before some months/years 😞 .

If your company requires this feature a lot, we would be happy to welcome your contribution on the topic but I think this is a work that could busy a developer for weeks, even for months

**Comment by matks** [comment]
And also this would be a breaking change so since we follow SemVer this could be done only in next 8.0 version 🤔

**Comment by SniperCZE** [comment]
Maybe I'm missing some point but you can rely on auto_increment event when not set to 1, ID is just generated by database engine itself. Or does prestashop generates ID for rows in app and just insert it? Something like "select id of last row, add 1, insert new row."?

**Comment by matks** [comment]
> auto_increment

I'm sorry I read your comment too fast 😥 indeed my answer was irrelevant

So what does M-M Setup requires `auto_increment` to be ? I'm sorry I have no knowledge of M-M requirements for mysql. Depending on the requirement, we can see whether disable the check, make it optional, or something else.

This check is useful but we could transform it into a warning if eligible.

**Comment by SniperCZE** [comment]
It depends. When you have classic master - master setup, you have to set auto_increment_increment to 2 and auto_increment_offset to 2 on one server (another one stays with auto_increment_offset 1). When you're using multi master setup with galera, you need to setup auto_increment_increment to number of nodes in cluster (usually 3) and auto_increment_offset set to 1 - n (first node gets 1, second node gets 2, nth node gets n).

**Comment by matks** [comment]
> It depends. When you have classic master - master setup, you have to set auto_increment_increment to 2 and auto_increment_offset to 2 on one server (another one stays with auto_increment_offset 1). When you're using multi master setup with galera, you need to setup auto_increment_increment to number of nodes in cluster (usually 3) and auto_increment_offset set to 1 - n (first node gets 1, second node gets 2, nth node gets n).

OK, so we cannot adapt the warning to something relevant, but we can allow people to disable it *providing they know what they are doing*, right ?

**Comment by SniperCZE** [comment]
I think you can. There will be auto_increment set to 1 in most cases and people knows when using some bigger M-M/galera cluster (because they setup it so).

**Comment by iw0der** [comment]
Hi,
to understand: can we skip the check made during installation? What happens, for example, if the index increase with 1, 3, 5, 7, 9 and later with 10,12,14,16? In short, if they are always "increased" sometimes even and sometimes odd: does the software survive? 

73s,
Arturo.

**Comment by iw0der** [comment]
> In short, if they are always "increased" sometimes even and sometimes odd: does the software survive?
> 
for the benefit of someone who is reading here, I answer to my own question... 

**NO**

...bypassing the autoincrement check, it does not even complete the installation ... goes wrong during the installation of the modules :-( and actually looking through the various forums, I found the following written:

> So you will get an error during install that you are not allowed to install modules. That's correct because the employee id_profile is "1", but the id_profile within ps_profile is "2" for the master. Same behavior within the shops, languages, categories and so on.

so it seems to me there are not many alternatives at present, a little too complex to modify the code to avoid being influenced by the progression of ids! :-(

DB cluster & Prestashop don't get along, at least for now!

73s,
Arturo.

**Comment by matks** [comment]
> for the benefit of someone who is reading here, I answer to my own question...

Sorry I did not see the question 😢and thank you for providing the answer
