### ISSUE TITLE
Wrong decimal places after upgrading to PrestaShop 1.7.6.0

### ISSUE THREAD

**Issue by mowcixo** [PrestaShop/PrestaShop#15015]
**Describe the bug**
After upgrading to PrestaShop 1.7.6.0 the decimals shown in some places are wrong, even in the configuration are settled to 2 decimals.

**Screenshots**

Configuration: 
![2019-08-07_11-08](https://user-images.githubusercontent.com/47653/62610473-0ec04480-b904-11e9-8df2-24d0b28f99d8.png)

Cart preview: 
![image](https://user-images.githubusercontent.com/47653/62610584-3f07e300-b904-11e9-8033-7d4d01d1d982.png)

Cart:
![image](https://user-images.githubusercontent.com/47653/62610416-f94b1a80-b903-11e9-81f0-3ce4bf165ddf.png)

Add to cart modal:
![image](https://user-images.githubusercontent.com/47653/62610649-6363bf80-b904-11e9-9d71-605dad8bcfa5.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @mowcixo,

This issue is related to this problem: https://github.com/PrestaShop/PrestaShop/issues/14608
Could you please try to replace precision to `2` in the table ps_currency, clear cache, check & feedback.

Thanks!

**Comment by mowcixo** [comment]
Hello @khouloudbelguith, that's right, following that steps the problem is solved.
Thanks!

**Comment by khouloudbelguith** [comment]
@mowcixo, thanks!
Feel free to open a new one needed.
