### ISSUE TITLE
Advanced Parameters> Logs 

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#15012]
Hi,
I can't access Advanced Parameters> Logs in the back office. 

See the attachment.

![image](https://user-images.githubusercontent.com/49063138/62606115-67d3ac80-b8f3-11e9-9b6b-daec6aaee234.png)

**Comment by khouloudbelguith** [comment]
Hi @JorgeNogueiraLFMPro,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14926 to fix the issue.
It is added to ps1.7.6.1.
Thanks to check & feedback.

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I made the changes but the error remains

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)

 Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
Host: lfmpro.com
Operating System: CentOS release 6.6 (Final)
Type and version of webserver: Apache/2.4.25 (Unix)
Version of PHP: PHP 7.1.22
Version of MySQL/MariaDB: mysql  Ver 14.14 Distrib 5.5.31

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, thanks!
What the exact PrestaShop Version?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith Prestashop Version 1.7.5.2

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, before this issue occurs, did you make a filter with `ID Object`?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith We have not made any changes to any filter in id ocject

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, in the Logs page, did you make a search with the Object ID?
https://drive.google.com/file/d/1EMTo6sqQLvAdb_ZErNV4D1sflutd0Nyw/view

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I can't open the video

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, 
[Logs • 1751.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3476483/Logs.1751.webm.zip)

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I may have probably done searches for filters. But I don't really know which filters I used

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, did you make a filter with the Date?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith I think so. But as I told you earlier I'm not sure

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, I tried to reproduce the same error as yours.
![image](https://user-images.githubusercontent.com/16067358/62627124-acc20800-b920-11e9-92fa-96ec71778f96.png)
But, after editing my file with this fix https://github.com/PrestaShop/PrestaShop/pull/14926/files
It is OK
https://drive.google.com/file/d/1A32FpieINXPWz4VRxgLEeN2y61txDj5A/view
Here's my new file:
[LogRepository.txt](https://github.com/PrestaShop/PrestaShop/files/3477259/LogRepository.txt)
Thanks!

**Comment by JorgeNogueiraLFMPro** [comment]
@khouloudbelguith 
I copied your file and it worked correctly. Thank you.

**Comment by khouloudbelguith** [comment]
@JorgeNogueiraLFMPro, you are welcome!
Feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14785
