### ISSUE TITLE
I want to use carries in both option billing ,price and weight 

### ISSUE THREAD

**Issue by amir201808** [PrestaShop/PrestaShop#15039]
i have two country for example
india and china 
india in use weight wise shipping option 
 && 
china in use price wise shipping option 
but now looked that i choose only one option 

i don't have idea how to both option use 
plz suggest
@khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi @amir201808,

Fist, you need to create different carriers.
Please follow these steps:
1. Create a zone1: China
2. Create a zone2: India
3. Edit the zone for the India country & the China country
![image](https://user-images.githubusercontent.com/16067358/62710730-ba928e80-b9ef-11e9-84ac-72737c370bdb.png)
![image](https://user-images.githubusercontent.com/16067358/62710768-c9794100-b9ef-11e9-819d-e082d6f1244c.png)
4. Create the first carrier with price-wise & select China zone
![image](https://user-images.githubusercontent.com/16067358/62710861-f9284900-b9ef-11e9-9656-0c7e1168cf15.png)

5. Create a second carrier with weight wise & Select India zone
![image](https://user-images.githubusercontent.com/16067358/62710957-25dc6080-b9f0-11e9-9f35-3f6abb42612e.png)


Thanks to check & feedback.

**Comment by dharmendravirasat** [comment]
How to show country wise carriers
if user indian then user order in show only indian carriers
else china

how to possible ?
i will try with ip address 
if user  indian ip then show indian carriers option 
else china 
plz suggest how can do which option is best, hard code ya prestashop backend in  provide 
these funcationlites 

@khouloudbelguith
