### ISSUE TITLE
SELECT SQL_NO_CACHE `id_guest`

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#15037]
Hello,
I worked on my BO and i have this error:

PS 1.7.6

`Table 'dbs80428.klprl_connections' doesn't exist

SELECT SQL_NO_CACHE `id_guest`
				FROM `klprl_connections`
				WHERE `id_guest` = 0
					AND `date_add` > '2019-08-08 10:45:00'
					 AND id_shop IN (1) 
				ORDER BY `date_add` DESC LIMIT 1

at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }

    DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
    DbCore->query - [line 663 - classes/db/Db.php] - [1 Arguments]
    DbCore->getRow - [line 163 - classes/Connection.php] - [2 Arguments]
    ConnectionCore::setNewConnection - [line 97 - classes/Connection.php] - [1 Arguments]
    ConnectionCore::setPageConnection - [line 117 - modules/statsdata/statsdata.php] - [1 Arguments]
    statsdata->getScriptCustomerPagesViews - [line 75 - modules/statsdata/statsdata.php] - [1 Arguments]`

I checked my database and i don't have  table klprl_connections

How can i restore it ?
How was it hapen ?

best regards
[nocache.pdf](https://github.com/PrestaShop/PrestaShop/files/3481491/nocache.pdf)

**Comment by khouloudbelguith** [comment]
Hi @papich06,

Yes, in your case, the klprl_connections tab doesn't exist.
You need to create a table in your database.
Here's an example
[ps_connections.sql.txt](https://github.com/PrestaShop/PrestaShop/files/3481645/ps_connections.sql.txt)
Just you need to replace the PREFIX `ps` to `klprl`
Thanks to check & feedback.

**Comment by papich06** [comment]
[whoops.pdf](https://github.com/PrestaShop/PrestaShop/files/3482893/whoops.pdf)
[guest.pdf](https://github.com/PrestaShop/PrestaShop/files/3482898/guest.pdf)

Hi @khouloudbelguith ,

Thanks for your help it's great

I checked but I also miss in additional to ps_connections: ps_connections_page and ps_connections_source can you send me a table? Where do you find them?

Before, there was a Prestashop module called "prestashop cleaning" to analyze and repair the databases, is there already for PS 1.7.6?

When I go into the BO customers -> customers to set hide price I have these errors

how to fix ?

**Comment by khouloudbelguith** [comment]
@papich06, the table ps_guest is not found in your case.
I attached the three tables
[ps_guest.sql.txt](https://github.com/PrestaShop/PrestaShop/files/3486919/ps_guest.sql.txt)
[ps_connections_source.sql.txt](https://github.com/PrestaShop/PrestaShop/files/3486920/ps_connections_source.sql.txt)
[ps_connections_page.sql.txt](https://github.com/PrestaShop/PrestaShop/files/3486921/ps_connections_page.sql.txt)

>Before, there was a Prestashop module called "prestashop cleaning" to analyze and repair the databases, is there already for PS 1.7.6?

Yes, it is PrestaShop Cleaner
![image](https://user-images.githubusercontent.com/16067358/62789389-b97d6200-bac0-11e9-93cd-6a404ed3acc1.png)

Thanks to check & feedback.

**Comment by papich06** [comment]
@khouloudbelguith 
In fact, i have a blank page on my BO i can work only when i activate PS_mode_dev

I think i have problem with Cache how to fix it ? (view attach file)
[cache.pdf](https://github.com/PrestaShop/PrestaShop/files/3487295/cache.pdf)

I update database thanks but i can't find module Prestashop Cleaner for 1.7.6 where you get it ?

thanks

**Comment by khouloudbelguith** [comment]
@papich06, 

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
I search it in the BO => Modules => Module Catalog Page
Thanks to check and feedback.

**Comment by papich06** [comment]
@khouloudbelguith thanks it's work

**Comment by khouloudbelguith** [comment]
@papich06, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by bernardochitas** [comment]
Thank you for the insert ps_connections query.

Now when I try to check open carts menu there's this crash:

[PrestaShopException]
Invalid address #16
at line 472 in file classes/Address.php

467.             // if an id_address has been specified retrieve the address
468.             if ($id_address) {
469.                 $address = new Address((int) $id_address);
470. 
471.                 if (!Validate::isLoadedObject($address)) {
472.                     throw new PrestaShopException('Invalid address #' . (int) $id_address);
473.                 }
474.             } elseif ($with_geoloc && isset($context->customer->geoloc_id_country)) {
475.                 $address = new Address();
476.                 $address->id_country = (int) $context->customer->geoloc_id_country;
477.                 $address->id_state = (int) $context->customer->id_state;
AddressCore::initialize - [line 197 - classes/tax/Tax.php] - [1 Arguments]
TaxCore::getProductEcotaxRate - [line 774 - classes/Cart.php] - [1 Arguments]
CartCore->getProducts - [line 1916 - classes/Cart.php]
CartCore->getOrderTotal - [line 1831 - classes/Cart.php] - [2 Arguments]
CartCore::getTotalCart - [line 872 - controllers/admin/AdminCartsController.php] - [3 Arguments]
AdminCartsControllerCore->getOrderTotalUsingTaxCalculationMethod - [line 339 - classes/helper/HelperList.php] - [2 Arguments]
HelperListCore->displayListContent - [line 165 - classes/helper/HelperList.php]
HelperListCore->generateList - [line 933 - controllers/admin/AdminCartsController.php] - [2 Arguments]
AdminCartsControllerCore->renderList - [line 2103 - classes/controller/AdminController.php]
AdminControllerCore->initContent - [line 281 - classes/controller/Controller.php]
ControllerCore->run - [line 511 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 99 - admin/index.php]



How can I solve this?

**Comment by khouloudbelguith** [comment]
Hi @bernardochitas,

This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/11416 as reported here: https://github.com/PrestaShop/PrestaShop/issues/9782

Thanks!

**Comment by CreatePublicidad** [comment]
Hello I have the same problem with my store in Prestashop, I don't know how I can solve it
