### ISSUE TITLE
1.7.6 invoice generating by date 

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15046]
BO> invoices

When selecting a date and generating invoices. A bundle is generated with all invoices, so not the selected date range. I have tried this in two stores. Both have the same issue. 
One store even crashes, probably because of the amount of invoices that is being created. 

Prestashop: 1.7.6
PHPl=: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/14vBZtQbV3d9TZ6cQaS1uphZ85aih_Ohr/view
Thanks to check & feedback.

**Comment by 01park** [comment]
Hi @khouloudbelguith ,

I have discovered the problem. I migrated my stores from PS 1.6 to 1.7 and used the migration module for this. The module imported all the the invoices and used the import date as the date the order was created. This is a mistake from the module. 

After changing the dates manual in the database I managed to fix the issue.

**Comment by khouloudbelguith** [comment]
@01park, did you used the 1-click upgrade module?

Thanks!

**Comment by 01park** [comment]
@khouloudbelguith 

No, at that time the 1-Click upgrade did not upgrade from 1.6 to 1.7, so I bought the promoted version on Prestashop.com

**Comment by khouloudbelguith** [comment]
@01park, thanks!
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
