### ISSUE TITLE
Exception error when multiple cart rules added

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#15041]
**Describe the bug**
`Warning: Division by zero in CartRuleCalculator.php line 240` exception when multiple cart rules added.

**To Reproduce**

1. Create 3 cart rules, each one with a different gift product
![image](https://user-images.githubusercontent.com/15104724/62712102-7fe22380-b9fa-11e9-86dc-bb0981a78373.png)
1. Create a 4th cart rule, 1€ amount discount, **`tax included`** (with `tax excluded` the error doesn't appear).
![image](https://user-images.githubusercontent.com/15104724/62712145-938d8a00-b9fa-11e9-99cf-4f693e4ca2bc.png)
1. Configure the price of the 3 products gifts configured in the previous cart rules to 1€
![image](https://user-images.githubusercontent.com/15104724/62712200-a99b4a80-b9fa-11e9-8fb8-cec0a785f6d1.png)
>[edited by Khouloud]

Products created must be with combinations & Tax =21% => Tax # 21% => OK

1. Add a product to the cart
![image](https://user-images.githubusercontent.com/15104724/62712235-b6b83980-b9fa-11e9-8376-36d8cd8aaf22.png)

> Edited by Khouloud

**Other steps to reproduce the issue**
1. Create a product with price tax included = 14.76 & specific price = 0.76 tax included
![image](https://user-images.githubusercontent.com/16067358/168029279-3087ffc8-8e21-45bf-bcbc-e774549383d9.png)
2. Create a cart rule 1 euro tax **included**  without code 
![image](https://user-images.githubusercontent.com/16067358/168029390-26d8c18b-75ca-46f0-a787-89cc82c71d7d.png)
3. Create a cart rule gift (the last product added) without code 
![image](https://user-images.githubusercontent.com/16067358/168029466-a2be52a2-2cf3-4a88-9f9d-c4cedcdd320b.png)
4. Go to FO > Add any product to the cart & refresh the page
5. See error 
![image](https://user-images.githubusercontent.com/16067358/168029544-672f9574-129a-441f-a713-59646670644d.png)

**Additional information**
PrestaShop version: 1.7.6.0, 1.78.0, 1.7.8.5, 1.7.8.6build1

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1r8TOURpzqDCykUoydmQo8xpSxTakVT1g/view
Thanks to check & feedback.

**Comment by idnovate** [comment]
You skipped step 3 :)

**Comment by khouloudbelguith** [comment]
@idnovate, thanks for these clarifications.
Following your steps => OK > There is no exception
I attached a screen record
https://drive.google.com/file/d/1OTQyesAdmmrhNh1QFjcWvIh5igCRywZ3/view
Thanks to check & feedback.

**Comment by idnovate** [comment]
Hi!

I managed to reproduce the issue with a fresh PS 1.7.6.1.

Please retry and choose "SPAIN" as store country, maybe it's applying different taxes than in FR.

**Comment by khouloudbelguith** [comment]
@idnovate, I tried also with PS1.7.6.1 & it is Ok
I attached a screen record
https://drive.google.com/file/d/10bmI_wmqTle6JssPpdWX-6b6fbSB6Pt7/view

Thanks!

**Comment by idnovate** [comment]
Please test it with a Spanish installation.

Look how my products prices look like:

![image](https://user-images.githubusercontent.com/15104724/64621361-d53c9680-d3e5-11e9-966c-ed8e6a618195.png)

**Comment by khouloudbelguith** [comment]
@idnovate, no, I just added those products with no tax => same issue with Tax =20%
https://drive.google.com/file/d/1mg887RbRgvxbG9UPl1RD5d6KNFqhMrnO/view

Thanks!

**Comment by idnovate** [comment]
Hi!

I attach you a video. It's quite long as I have recorded also installation.
https://drive.google.com/file/d/1q21un3FE_wh8NkUut4GFuMzlCZ6LoKk6/view

Developer console is not recorded (:disappointed_relieved:), but this is what appears after the product is added to the cart:
![image](https://user-images.githubusercontent.com/15104724/64628220-49c90280-d3f1-11e9-89cb-bec3abbc7bbe.png)

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I manage to reproduce the issue with PS1.7.6.1. & PS1.7.6.0 & PS1.7.5.2 / Spain because in fact => we must have Tax = 21%

We need to have gifts with combinations (not standard products) 
to reproduce the issue:

1. Create 3 product with combinations => Configure the price of the 3 products to 1€ TTC
2. Create 3 cart rules, each one with a different gift product (3 Products created previously)
3. Create a 4th cart rule, 1€ amount discount, **`tax included`**
4. Add a product to the cart

An error 500 is displayed in the FO
![image](https://user-images.githubusercontent.com/16067358/64687297-20a48280-d482-11e9-9def-60d927c335f0.png)

The FO doesn't work anymore.
PS: when we have products without combinations => OK & when Tax <> 21% => OK


I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Hydrog3n** [comment]
Hello ! This bug is fix on 1.7.6 ?

**Comment by khouloudbelguith** [comment]
Hi @Hydrog3n,

Sorry, it is not fixed yet.

Thanks!

**Comment by Hydrog3n** [comment]
> Hi @Hydrog3n,
> 
> Sorry, it is not fixed yet.
> 
> Thanks!

Ok thank for the info. Do you have a PR or a fix to fix this until you fix ?

**Comment by khouloudbelguith** [comment]
@Hydrog3n,

Sorry no.
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by Hydrog3n** [comment]
> @Hydrog3n,
> 
> Sorry no.
> But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.
> 
> Thanks!

Ok :) I know just if someone already do this I doesn't want to recode again. If I find I will PR ;)

**Comment by carlosul** [comment]
Hi! @Hydrog3n 

I have the same problem with Prestashop 1.7.6.4
The same error appears when:
1. A gift product is added to cart
2. Another voucher in discount price is added to cart

What I've checked is that this happens when:
1. The gift product has a Tax
2. The total price of the gift product (tax inc) is a integer

So for example it triggers with a gift that costs 3.0 but it doesn't trigger with a gift that costs 3.5

Then I tried to debug the problem (I'm not an expert programmer) and saw that when this case happened the variable $taxRate was equal to -1
Because of that the division /1-$taxRate gives an error in line 240.

I've parched adding
`                    if($taxRate==-1){$taxRate = 0;}` 
before line 240

This should be solved properly however.

**Comment by Hydrog3n** [comment]
Hi @carlosul !

We are under 1.7.6.0 and I fix like this. 
in the CartRuleCalculator.php Line 234 

it's this block in master : https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Cart/CartRuleCalculator.php#L243-L249

I don't remember why we don't PR this fix, but it's maybe it's not perfect for all cases.  

```php
                   // if cart rule amount is set tax included : calculate weight tax included
                    if ($totalTaxIncl != 0) {
                        $weightFactor = $concernedRow->getFinalTotalPrice()->getTaxIncluded() / $totalTaxIncl;
                    }
                    $discountAmountTaxIncl = $discountConverted * $weightFactor;

                    // Protect unkwown issue when $taxRate = -1
                    // https://github.com/PrestaShop/PrestaShop/issues/15041
                    if ($taxRate != -1) {
                        // recalculate tax included
                        $discountAmountTaxExcl = $discountAmountTaxIncl / (1 + $taxRate);
                    } else {
                        $discountAmountTaxExcl = $discountAmountTaxIncl;
                    }
```

**Comment by Nukium** [comment]
Hello, thank you @Hydrog3n this work for us.

We're able to reproduce the issue on PrestaShop 1.7.6.x fresh install like this : 

1. Create a product with an integer price and with tax like this :
![2021-11-23_15h06_36](https://user-images.githubusercontent.com/35034/143038847-400716da-2af7-48a5-8d98-24aaea9be0a0.png)

2. Create 2 cart rules, one with a discount amount (tax included) and another with the product created previously as a gift

3. Create a customer group with global reduction (50%) and price display without tax

4. Login with an account on this group (default group), add some products to the cart and then apply the 2 cart rules.

5. You can see a white screen or a warning if you have enabled the debug mode
![2021-11-23_15h12_01](https://user-images.githubusercontent.com/35034/143039759-343fc789-d44b-43e4-b9b8-24fafca91ac0.png)

 good luck !

**Comment by Ditwo** [comment]
Hello,
Same issue on PS 1.7.6.5. 
After some investigation, it appears when $concernedRow->getFinalTotalPrice()->getTaxExcluded() is almost zero, but not zero. And at the same time $concernedRow->getFinalTotalPrice()->getTaxIncluded() = zero.
Example in my case
$concernedRow->getFinalTotalPrice()->getTaxIncluded() = float(0)
$concernedRow->getFinalTotalPrice()->getTaxExcluded() = float(0.00066100000000002)
(which in the end it isn't logical)
As a result the condition if ($concernedRow->getFinalTotalPrice()->getTaxExcluded() != 0) is successful, and then $taxeRate = -1 > division by zero!

Rather than recalculate $taxRate as in the previous patches, I prefer to strenghten the condition : 
                if ($concernedRow->getFinalTotalPrice()->getTaxExcluded() != 0 **&& $concernedRow->getFinalTotalPrice()->getTaxIncluded() != 0**) {

Because if getTaxExcluded is != 0, also getTaxIncluded should !=0. This is logical. And it applies to all cases ;)

Hope it helps,
Denis

Fix
            foreach ($concernedRows as $concernedRow) {
                // get current line tax rate
                $taxRate = 0;
                /*protect division by zero*/
                if ($concernedRow->getFinalTotalPrice()->getTaxExcluded() != 0 **&& $concernedRow->getFinalTotalPrice()->getTaxIncluded() != 0**) {
                // if ($concernedRow->getFinalTotalPrice()->getTaxExcluded() != 0) {
                    $taxRate = ($concernedRow->getFinalTotalPrice()->getTaxIncluded()
                                - $concernedRow->getFinalTotalPrice()->getTaxExcluded())
                               / $concernedRow->getFinalTotalPrice()->getTaxExcluded();
                }

**Comment by shawe** [comment]
@Ditwo Where exactly did you try the changes you are sharing? I can test it on a customer installation that is blocking it's customer to buy for this bug.

Are you noticed any unexpected behavior after apply this fix?

**Comment by khouloudbelguith** [comment]
Hi :) I found other steps to reproduce the issue

**First case**
1. Create a product with price tax included = 14.76 & specific price = 0.76 tax included
![image](https://user-images.githubusercontent.com/16067358/168029279-3087ffc8-8e21-45bf-bcbc-e774549383d9.png)
2. Create a cart rule 1 euro tax **included**  without code 
![image](https://user-images.githubusercontent.com/16067358/168029390-26d8c18b-75ca-46f0-a787-89cc82c71d7d.png)
3. Create a cart rule gift (the last product added) without code 
![image](https://user-images.githubusercontent.com/16067358/168029466-a2be52a2-2cf3-4a88-9f9d-c4cedcdd320b.png)
4. Go to FO > Add any product to the cart & refresh the page
5. See error 
![image](https://user-images.githubusercontent.com/16067358/168029544-672f9574-129a-441f-a713-59646670644d.png)

**Second case**
1. Install PS16124
1. Create a product with price tax included = 14.76 & specific price = 0.76 tax included
2. Create a cart rule 1 euro tax **included**  without code 
3. Create a cart rule gift (the last product added) without code 
4. Go to FO > create some orders & cart rules
5. Upgrade to PS178
6. Go to BO > Orders > Shopping carts > View last carts => see an error, the shopping cart cannot be opened, the page is refreshed
7. View the first order created by john Doe > See exceptions
https://user-images.githubusercontent.com/16067358/168256076-00ef2cd1-758f-4331-91b0-e0c5871c4cce.mp4
8. Go to FO > Your account > Re-order any order created before the upgrade
9. See exception 

https://user-images.githubusercontent.com/16067358/168256949-fa33b0f8-88eb-4b32-8aa6-4844f611e3c5.mp4

I changed the severity from Minor to Major

**Comment by Ditwo** [comment]
> @Ditwo Where exactly did you try the changes you are sharing? I can test it on a customer installation that is blocking it's customer to buy for this bug.
> 
> Are you noticed any unexpected behavior after apply this fix?

Hello shawe,
The file is src\Core\Cart\CartRuleCalculator.php.
Everything works fine  ;)
Best regards,
Denis

**Comment by shawe** [comment]
> > @Ditwo Where exactly did you try the changes you are sharing? I can test it on a customer installation that is blocking it's customer to buy for this bug.
> > Are you noticed any unexpected behavior after apply this fix?
> 
> Hello shawe, The file is src\Core\Cart\CartRuleCalculator.php. Everything works fine ;) Best regards, Denis

Thanks, then maybe ower customer will try your solution.

**Comment by carcam** [comment]
This change is not in PrestaShop 1.7.8.8. Will it be added in next 1.7 release or is it in PrestaShop 8?

**Comment by idnovate** [comment]
The `1.7.8.x` branch is in the security-only maintenance phase. This means that patch releases of PrestaShop 1.7.8 will only be published if critical bugs are reported or if security fixes are needed.

**Comment by carcam** [comment]
Well this issue was closed on May 2022 and I think PrestaShop 1.7 was not in security-only maintenance...

In any case it makes sense. Do you know if it has been ported to PrestaShop 8 ?

Thanks!!

**Comment by idnovate** [comment]
This issue is still opened :)

And I don't know if this bug still happens in PS 8 and has to be fixed.

**Comment by carcam** [comment]
oohh!! I read "closed" in the history and didn't noticed the big "Open" on top of the page!!

Thanks!!

**Comment by web-cooking-factory** [comment]
Hi everyone !
I've got the bug. In my case it came from a difference of rounding in a gift product cart rule.
The amount passed to applyFlatDiscount is not rounded but the price of the product is. It results in a $taxIncluded < $taxExcluded.

**Comment by alisamie97** [comment]
Hello everyone, we are also facing this issue at 2023 and still not fixed! I know that this is going to be fixed in ps 8 but not sure when exactly, I tried some patches before and they did not accept them, I don't know if I make another patch for this they will accept or not
it seems like it is still now fixed in ps 8
https://github.com/PrestaShop/PrestaShop/blob/9f71ee38fec557d465b92233d25f96ee92bac9df/src/Core/Cart/CartRuleCalculator.php#L239-L268

**Comment by alisamie97** [comment]
I am not sure what is happening exactly, but I think that `$taxRate` must be `0` or grater than `0` always. Am I right?

**Comment by alisamie97** [comment]
I tried adding this line and it seems good to me.
```
if ($taxRate < 0) {
    $taxRate = 0;
}
```

**Comment by OrionCodeDev** [comment]
Hello @Hlavtox and @matks,

I wanted to ask if it would be possible to resolve this ticket by implementing the merge request with ID #35953 . I’ve tested it, and this fix from the PR does address the issue described here. Although it requires specific conditions to trigger, it can still cause a critical error that blocks the store. Given the seriousness of this issue, it might be worth considering.

**Comment by Hlavtox** [comment]
@ChronoBrake Hi, if it fixes the issue, we can close this issue. :-)
