### ISSUE TITLE
Improve ecotax management in BO product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15044]
As the merchant enter the product price with the ecotax, the ecotax must be deducted from the selling price to let the merchant know what he/she will really earn.
We will also need this amount later if there is some discounts as they are applied on the prixe without ecotax (see https://github.com/PrestaShop/PrestaShop/issues/9600) 
Today the ecotax is deducted from the price tax excl field of the product in BO as soon as the ecotax is filled.

**The problem is the following**: 
By removing the ecotax amount from the field price tax excl of the product in BO, if we want to change again the price of the product after entering the ecotax, the calculations are not correctly redone and the price tax incl is incorrect.

As a merchant, I entered my price excl. ecotax included in BO: 10€
Let's say that I don't have VAT on my product or my eco-participation.
My price incl VAT = 10€
Then I enter the amount of eco-participation included: 2€
The recalculation is done at this moment: the price tax excl of my product in BO goes to 8€ (in front it remains well 10€)

The problem is that if I decide to rechange my price tax excl for example for 12€ (including ecotax normally), the field price tax incl is 14€ and also 14€ in front (instead of 12€).
So, as a merchant I must empty the ecotax field, and re-enter my price tax excl ecotax included: 12€, then re-enter my ecotax: 2€ so that the price tax excl is again recalculated correctly: 10€ (ecotax withdrawn) in BO and 12€ in front.

Please see: https://drive.google.com/file/d/1w07b7Dch5BBV8pxnl-iFcnSKNxjuxSYd/view?usp=sharing

**Solution**
- Don't remove the ecotax from the field Price (tax excl.) in BO

When ecotax is enabled and if it is not a virtual product:

- Rename the field "Price (tax excl.)" to "Price (tax excl.) ecotax included" only if the “ecotax” option is enabled in International > Taxes.
- Rename the field "Price (tax incl.)" to "Price (tax incl.) ecotax included" only if the “ecotax” option is enabled in International > Taxes.
So that the merchant understands that he must enter his price ecotax included.
- Add an information part **Net turnover excluding tax**:
Price (tax excl.) - ecotax (tax incl.)
This amount will have to be taken into account for the calculations of the margin instead of the field "Price (tax excl.)" when it is different from 0
The value of this information part will be recalculated when the merchant will change one of the following fields: Price (tax excl.) ecotax included, Price (tax incl.) ecotax included & Ecotax (tax incl.)

**Comment by marionf** [comment]
@matks Does it seem feasible to do this during the migration of the product page (pricing tab) ?

**Comment by matks** [comment]
@marionf This is an ambiguous behavior and *yes* I think we should fix it during the migration.

But, more than fixing it, we must *make sure people understand what is being computed between the different fields*. So I think somewhere in the page we must show to the merchand *what is being added or removed* so he does not wonder "why do I get price X ? what tax is being or not being applied" ?

**Comment by ElodieOS** [comment]
Hello @MatShir @TristanLDD, 

The UX part of the problem has been solved, no?
 
![Capture d’écran 2023-10-02 à 15 52 05](https://github.com/PrestaShop/PrestaShop/assets/113457393/75c07852-d5b1-45e1-856a-88e179201f84)
