### ISSUE TITLE
too many trailing zeroes on the price slider

### ISSUE THREAD

**Issue by karopka** [PrestaShop/PrestaShop#15047]
too many trailing zeroes on the price slider
![price_slider](https://user-images.githubusercontent.com/18676256/62759608-e286fe00-ba92-11e9-99ba-00cb28efa2d5.JPG)

PrestaShop version: 1.7.6.0
ps_facetedsearch version:  3.2.0
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment]
Hi @karopka,

This issue occurs after an upgrade to PS1.7.6.0.
Here's the PR: #14664 to fix the issue.
To solve your issue thanks to change the `precision` in the Database => `ps_currency` Table from `6` to `2`.
Thanks to check & feedback

**Comment by karopka** [comment]
Yes, it solves the issue

**Comment by mariem-abid** [comment]
Hi @karopka,

Thanks for your feedback.
Feel free to open a new one when needed.
