### ISSUE TITLE
Translation is not updated in the Symfony page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15052]
**Describe the bug**
Seems that the translation from the BO is not updated in the Symfony page

**To Reproduce**
1. Go to BO => International => Translations => Select 
1.1. Type of translation => Back office
1.2  Select your language => English
1.3 Click on Modify 
2. Search for the expression "View my shop"
3. Try to translate it
4. click Save => OK
5. Go to the Dashboard page => the new expression well displayed
6. Go to any page migrated to Symfony => old expression is displayed

**Screenshots**
https://drive.google.com/file/d/1n50LmEhI01xRq55Y1X16WVFR6znmet_O/view

**Additional information**
PrestaShop version: 1.7.6.x/1.7.6.0/1.7.5.1
PHP version: 7.0

**Comment by eternoendless** [comment]
I think this is probably related to #14932

**Comment by marionf** [comment]
I change the translation for "Set required fields for this section", it's well applied on Customer page (symfony page)

![capture d'écran_1884](https://user-images.githubusercontent.com/13449658/62933334-4296e080-bdc2-11e9-8eb9-eef8ff2aab85.png)

However, the translation of "View my shop" is ok on legacy page but not in symfony pages

![capture d'écran_1885](https://user-images.githubusercontent.com/13449658/62933463-84278b80-bdc2-11e9-9a86-a9a6ed538f8d.png)

**Comment by eternoendless** [comment]
I believe this is fixed by https://github.com/PrestaShop/PrestaShop/pull/15111
