### ISSUE TITLE
Webservice Customer - Updating forces password reset

### ISSUE THREAD

**Issue by dnatabar** [PrestaShop/PrestaShop#15069]
Updating any field on a customer through the webservice fails if there are no password element as well.
But when you supply a password element, the customers password is obviously changed.
Since it requires an unhashed password ( as it automatically hashes the recieved password ), it will effectively block a customer who have been udpated through the webservice, from logging in without resetting their password as well.

**To Reproduce**
1. Update a customers first name through the webservice.
2. If no password element is supplied, exception is thrown and nothing updates.
3. If password is supplied, customers password is updated.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.3.6

Edit:
Also asked about it on PrestaForums, no response.
https://www.prestashop.com/forums/topic/996144-ps-17-webservice-updating-customers-causes-password-problems/

**Comment by mariem-abid** [comment]
Hi @dnatabar,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by dnatabar** [comment]
I highly doubt it is a compatibility issue, as the shop itself works fine and the webservice works fine as well.
I will however give it a try ofcourse, better rule something out than make assumptions :)

**Comment by mariem-abid** [comment]
@dnatabar, waiting for your feedback!

**Comment by dnatabar** [comment]
@mariem-abid Sorry for the delay, had some other work pop up.

Can confirm that with 7.1 it works when i send the hashed version of the current password.
Now i am curious as to if i made a mistake when i tested it with 7.3...

Edit:

Yes can confirm it works fine with 7.3 as well, i must have done it wrong when i tried it initially.
As long as i send the current hash with the PUT request, it won't change the password of the customer.

Thanks for the help!

**Comment by mariem-abid** [comment]
Hi @dnatabar,

Thanks for your feedback 
Feel free to open a new one when needed.
