### ISSUE TITLE
Faceted Search - products are displayed in wrong order when sorted by "position" and "Show products from subcategories" is disabled

### ISSUE THREAD

**Issue by gbr161** [PrestaShop/PrestaShop#15062]
**Describe the bug**
As title says. When products are sorted by position they are not in the order ive set in admin panel. If I change order from ascending to descending, products are changing order, but still this is not the order that is set in admin panel.

**To Reproduce**
1. Go to admin panel -> add some products and sort them the way you wish
2. Save it
3. Go to your shop and category you put products in.

**Additional information**
PrestaShop version: 1.7.5.2 
PHP version: 7.0.27
MYSQL version: 10.0.38-MariaDB

Ive spent some time and it boiled down to this query:
`SELECT p.id_product FROM (SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position FROM ps_product p LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND 0 = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 ) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) WHERE p.id_category_default='37' AND p.visibility IN ('both', 'catalog') AND ps.id_shop='1' GROUP BY p.id_product) p INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) GROUP BY p.id_product ORDER BY p.position ASC LIMIT 0, 12`

Its from 
`    /**
     * Construct the final sql query
     *
     * @return string
     */
    public function getQuery()
`

This one returns p.id_product list in wrong order.

**Comment by marionf** [comment]
Hello @gbr161 

I tried to reproduce the issue with PS 1.7.6.0 & faceted search v 3.2.0 but without success as you can see in the screenrecord below:
https://drive.google.com/file/d/1rgX4dcHdTGAHL6GU6_41LkRUMRkWqMAH/view?usp=sharing

**Comment by Mindfield-Studio** [comment]
Hi,

I think I found something (thanks @gbr161, you get me on the right way).

-> "src/Adapter/MySQL.php" in "getFieldMapping" method:

```
...
'position' => [
                'tableName' => 'category_product',
                'tableAlias' => 'cp',
                'fieldName' => 'position',  // <- ADD THIS
                'joinCondition' => '(p.id_product = cp.id_product)',
                'joinType' => self::INNER_JOIN,
            ],
...
```

Hope that helps ;)

**Comment by Mindfield-Studio** [comment]
@marionf : it seems you have to have at least one filter on the category to reproduce this issue

**Comment by marionf** [comment]
@Mindfield-Studio 

I tried to reproduct but even with 1 filter it's correclty sorted by position ascending

![capture d'écran_1878](https://user-images.githubusercontent.com/13449658/62867284-3e5fba00-bd13-11e9-9e8f-b89c137c6a02.png)

![capture d'écran_1879](https://user-images.githubusercontent.com/13449658/62867286-415aaa80-bd13-11e9-8cb1-71d8f82525bc.png)

**Comment by gbr161** [comment]
@Mindfield-Studio thanks for the reply but this doesnt fix the problem.
Here are the screenshots:
![front](https://user-images.githubusercontent.com/3307202/62875787-e8dfd900-bd23-11e9-8030-fc13f5592806.png)
![back](https://user-images.githubusercontent.com/3307202/62875793-ebdac980-bd23-11e9-86a8-7bac2e7e0d8c.png)

**Comment by gbr161** [comment]
@marionf @Mindfield-Studio 
After hours of looking whats wrong, changing servers and database version i ended with setting up clean install of prestashop and it worked. Looking further and extracting the sql query on both setups i found that query is different:

"Bugged" query:
`
SELECT p.id_product FROM (SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position FROM ps_product p LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND 0 = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 ) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) WHERE p.id_category_default='37' AND p.visibility IN ('both', 'catalog') AND ps.id_shop='1' GROUP BY p.id_product) p INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) GROUP BY p.id_product ORDER BY cp.position ASC LIMIT 0, 12`

Working query:
`SELECT * FROM (SELECT p.id_product, cp.id_category, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position FROM ps_product p LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND 0 = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 ) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) WHERE p.visibility IN ('both', 'catalog') AND c.nleft>=4 AND c.nright<=5 AND ps.id_shop='1' GROUP BY p.id_product) p INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) GROUP BY p.id_product ORDER BY p.position ASC LIMIT 0, 12 `

"Bugged" uses 'id_category_default' to get products from category we are in and working one uses tree structure marks from category table to get category id.

The 'id_category_default' appears in:
`    /**
     * @param array $selectedFilters
     * @param Category $parent
     * @param int $idShop
     */
    private function addSearchFilters($selectedFilters, $parent, $idShop)`
and
`    /**
     * Init the initial population of the search filter
     *
     * @param array $selectedFilters
     */
    public function initSearch($selectedFilters)
{
<cut>
        $psLayeredFullTree = Configuration::get('PS_LAYERED_FULL_TREE');
        if (!$psLayeredFullTree) {
            $this->addFilter('id_category_default', [$parent->id]);
        }
</cut>
}
`
So if I want to display products only from the last child category it will use the 'id_category_default' and sorting by position will not work.

It seems problem was there before latest version because on 3.0.6 it acts the same.

Thats all ive found for now. If im wrong, please correct me.

**Comment by Mindfield-Studio** [comment]
Maybe it's different depending on prestashop version (i'm on a "fixed" version of 1.7.4).
The "**p**.position" ordering does not make sense, I don't even think this field exists in "product" table. 

The position field is in "category_product", so the ordering need to be on "**ps**.position". Everything is in the "src/Adapter/MySQL" class. My previous post fixed the issue for me (by adding "'fieldName' => 'position'").

**Comment by gbr161** [comment]
@Mindfield-Studio 
I don't know how it is on 1.7.4 but since it all happens in module it shouldn't be the difference. Have you tried switching "Show products from subcategories" to "No"? This what makes the problem visible.
I know that there is no "p.position" and it should use "cp.position" but there is no difference in result i have got after changing it on two hosts where i have tested it running clean install and even running the extracted query - the order is wrong when "Show products from subcategories" is set to "No" in module config page.

**Comment by marionf** [comment]
Thank you for these details @gbr161 
I can reproduce the issue when "Show products from subcategories" is disabled

**Comment by Mindfield-Studio** [comment]
@gbr161 
I did not see the "Show products from subcategories" options ^^
All I can see is, on 1.7.4, when this option is enabled, position is also in wrong order. It seems it's not exactly the same issue then :D

**Comment by agalussio** [comment]
I have the same problem and with the latest version of facet search 3.5.0 it doesn't work either.

**Comment by agalussio** [comment]
@gbr161  Have you been able to work it out? I'm the same way.

**Comment by agalussio** [comment]
It shows me by root category. It doesn't have the category parameter.
As I see in

"/modules/ps_facetedsearch/src/Adapter/MySQL.php"

in "getFieldMapping" method:
...
'position' => [
'tableName' => 'category_product',
'tableAlias' => 'cp',
'fieldName' => 'position', // <- ADD THIS
'joinCondition' => '(p.id_product = cp.id_product)',
'joinType' => self::INNER_JOIN,
],


It does not happen in the condition that the id_category = id_category

Whenever I make this select it shows the first position
SELECT * from ps_category_product where id_product = (x)

**Comment by marionf** [comment]
Hello @agalussio 

I tried to reproduce the issue with ps_facetedsearch 3.5.0 but without success
Below is my configuration:

![capture d'écran_2482](https://user-images.githubusercontent.com/13449658/77760649-fd64ad80-7036-11ea-9893-e9c383934082.png)

![capture d'écran_2481](https://user-images.githubusercontent.com/13449658/77760668-05bce880-7037-11ea-9ced-04b8f1318afd.png)

![capture d'écran_2480](https://user-images.githubusercontent.com/13449658/77760679-09e90600-7037-11ea-8feb-163fa2388215.png)

![capture d'écran_2479](https://user-images.githubusercontent.com/13449658/77760699-11a8aa80-7037-11ea-9a9f-cb234ead893d.png)

Could you give me more details about your configuration ?

**Comment by agalussio** [comment]
@marionf 

Yeah, right. Attached are captures.

Prestashop 1.7.6.3
ps_facetedsearch 3.5.0

![image](https://user-images.githubusercontent.com/32964322/77765920-3acd3900-703f-11ea-8313-b3edd307e014.png)

![image](https://user-images.githubusercontent.com/32964322/77765962-491b5500-703f-11ea-85b9-6f9fd30dbdde.png)

![image](https://user-images.githubusercontent.com/32964322/77765987-57697100-703f-11ea-8b0e-63a2d5b9de81.png)

As you will see the order within the category with the facet search module is not correct.
But I see that the order it puts is the one with the root folder (id=2)

Attached 

![image](https://user-images.githubusercontent.com/32964322/77766233-a7483800-703f-11ea-9e4d-47bac8801ced.png)

**Comment by marionf** [comment]
@agalussio 

I applied the same configuration as you:

![capture d'écran_2485](https://user-images.githubusercontent.com/13449658/78005356-bc70df80-733b-11ea-9645-f7aeff88bef6.png)

![capture d'écran_2488](https://user-images.githubusercontent.com/13449658/78005383-c85ca180-733b-11ea-8049-a8425ed31fc7.png)

![capture d'écran_2486](https://user-images.githubusercontent.com/13449658/78005424-d4e0fa00-733b-11ea-9dd6-5e9e7f2eb76d.png)

![capture d'écran_2487](https://user-images.githubusercontent.com/13449658/78005431-d8748100-733b-11ea-8793-de17a5218201.png)

![capture d'écran_2489](https://user-images.githubusercontent.com/13449658/78005551-035ed500-733c-11ea-918f-46216688cb7c.png)

But I can't reproduce the issue

**Comment by epertinez** [comment]
Here you have my solution.
At least the solution to my problem (that I feel is a common one)
The problem is that the filter engine returns positions without taking into consideration that a product can be in more than one categories at the same time.
So the INNER_JOIN of a product that has more than one categories returns more than one results with more than one positions. 
Now, category can be product->id_category_default, but it also can be any other category that is saved as not default categories. Don't know if those have their own table or are somehow encoded as a list in the product register but anyway, I wouldn't know how to get the actual category so I made a hack that somehow works (yet be careful because I am not sure it works in all situations).

First of all you must let MySQL.php access to Tools library
Add this at the list of use libraries at the begining or the file (after StockAvailable?)

// 202111 Bredax afegitó per accedir a la categoria en la que estem
use Tools;

Then, substitute the position in filterToTableMapping with


            'position' => [
                'tableName' => 'category_product',
                'tableAlias' => 'cp',
                'fieldName' => 'position', // <- 202109 Bredax ADD THIS (not sure it is needed)
                'joinCondition' => '((p.id_product = cp.id_product) AND (cp.id_category='.Tools::getValue('id_category').'))',// <- 202110 Bredax Modified
                'joinType' => self::INNER_JOIN,
            ],

That is all. It works for me, hope it works for anybody.

**Comment by epertinez** [comment]
Hi there, I am back.
My solution did work for ending categories but not for categories up in the tree.

Here you have a solution that works booth for final leaves of the tree and middle nodes.
All changes made in modules/ps_facetedsearch/src/Adapter/MySQL.php
Add
use Tools; // 202110 Added by Bredax
after use StockAvailable;

Modify 'position' with
                'aggregateFunction' => 'MIN(IF(cp.id_category = '.Tools::getValue('id_category').',',// <- 202110 Bredax ADD THIS*/
                'aggregateFunctionParams' => '), 9999+1+cp.position)',// <- 202110 Bredax ADD THIS*/
                'aggregateFieldName' => 'position',// <- 202110 Bredax ADD THIS*/
 
In cpmputeFieldName look for if (isset($joinMapping['aggregateFunction'], $joinMapping['aggregateFieldName'])) and add aggregateFunctionParams so we can put a line AFTER the aggregation we need it for MIN(IF(condition,,)) .

            if (isset($joinMapping['aggregateFunction'], $joinMapping['aggregateFieldName'])) {
                $aggregateFunctionParams=isset($joinMapping['aggregateFunctionParams'])?$joinMapping['aggregateFunctionParams']:''; // Added by Bredax
                $fieldName = $joinMapping['aggregateFunction'] . '(' . $fieldName. $aggregateFunctionParams. ') as ' . $joinMapping['aggregateFieldName']; // Modified by Bredax
            }



That's it. It should work now.


ONE LAST THING: In my case out of stock products were shown before the others in not final nodes (surely because I dont use stock and there are plenty of negative numbers there?) Anyway for my hack to work I set Show unavailable, out of stock last to NO.
