### ISSUE TITLE
ps_facetedsearch 3.2.0 : the order of the attributes doesn't correspond to the back office PS 1.7.6

### ISSUE THREAD

**Issue by Mamar25** [PrestaShop/PrestaShop#15065]
Hi,

On Prestashop 1.7.6, I have problems with the facetedsearch 3.2.0 module.
The product variations, which appear in the front office do not correspond to the order set in the back office (catalog / attributes).

For example, I have different sizes of clothes that I want to display in this order: S / M / L / XL but it is displayed in alphabetical order: L / M / S / XL.

I configured the back office, I emptied all the caches, reindexed products and attributes. I have uninstalled and reinstalled the module several times, but nothing works.

I also have a problem with off-stock versions but I think the subject is already open. For example, a product of different size S / M / L where only L is left in stock; in the filter, the customer can choose sizes S and M while stocks are at 0.

**Comment by marionf** [comment]
Hello @Mamar25 

Thank you for opening an issue.
I reproduce the problem, the order of the attributes is not as defined in the back-office.

> I also have a problem with off-stock versions but I think the subject is already open. For example, a product of different size S / M / L where only L is left in stock; in the filter, the customer can choose sizes S and M while stocks are at 0.

This issue was supposed to be fixed: https://github.com/PrestaShop/PrestaShop/issues/10018
But it seems to be not

**Comment by Mamar25** [comment]
Hi, 
Thank you for your return - I will wait for your solution.
