### ISSUE TITLE
Product prize digits

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#15070]
**Describe the bug**
Back office price is calculated with to many decimal points

**To Reproduce**
1. In back office go to 'Catalog / Products'
2. Edit product
3. Change tax excluded price to one with 2 decimal point values, eg. **13.87**
4. Change field, then tax excluded changed to **13.869999**, and tax included changed to **16.643999** - first error

If that value will be saved it makes problem in front office when price will be formatted with 2 decimal points. One product will have rounded price, but multiple same instances of product will not have valid total price.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/3767861/62850557-823acb00-bce3-11e9-9710-639f38c55377.png">

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.20
Tested on demo.prestashop.com

**Comment by marionf** [comment]
Hello @Flower7C3 

Thank you for reporting this issue, however it has already been reported here: https://github.com/PrestaShop/PrestaShop/issues/12078
You should follow this issue

Regards

**Comment by khouloudbelguith** [comment]
Duplicate of #12078
