### ISSUE TITLE
Positions doesn't work.  Gives me error 404.

### ISSUE THREAD

**Issue by pedroideavity** [PrestaShop/PrestaShop#15085]
**Describe the bug**

**To Reproduce**
1. Go to 'Design'
2. Click on 'Positions'
3.. See error

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2
Memory Limit: 512M
Max execution time: 300

**Comment by mariem-abid** [comment]
Hi @pedroideavity,

Thanks to adding a short description of your issue and add steps to reproduce it in a new comment.

**Comment by khouloudbelguith** [comment]
Hi @pedroideavity,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
