### ISSUE TITLE
Oneclick upgrade from 1.7.5.2 to 1.7.60 (database_prefix)

### ISSUE THREAD

**Issue by fdonnet** [PrestaShop/PrestaShop#15080]
Exactly the same bug as this forum post:
https://www.prestashop.com/forums/topic/998058-after-upgrade-1740-to-1760-site-reach-500-internal-server-error/

but from 1.7.5.2 to 1.7.6.0

Oneclick updater version up to date.

The procedure worked fine for another shop => no issue, but for my principal it raised this error and I don't know why at all

"Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "prestashop.database.naming_strategy" has a dependency on a non-existent parameter "database_prefix". in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:102 Stack trace: #0 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('database_prefix') #1 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('database_prefix') #2 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->re in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 102"

Very strange.

**Comment by mariem-abid** [comment]
Hi @fdonnet,

Do you use the prefix "ps" by default of PrestaShop or did you change it during installation?

**Comment by fdonnet** [comment]
Hi @mariem-abid ,
Default "ps" prefix. And it's a very simple shop (with a classic child theme). My other shop upgrade (more complex site) passed 1.7.6 without any issue... it seems strange, and I cannot identify where to look at, but apparently some other guys have the same issue (forum link, in the issue).

**Comment by mariem-abid** [comment]
Hi @fdonnet,

What is the exact version of the module 1-click upgrade?

**Comment by fdonnet** [comment]
Hi @mariem-abid 
4.9.0

**Comment by khouloudbelguith** [comment]
Hi @fdonnet,

Thanks for your feedback.
In your file /Project_Folder/app/config/parameters.php, did you defined the `database_prefix`?
For example 'database_prefix' => 'ps_',
here's my file parameters.php
[parameters.php.txt](https://github.com/PrestaShop/PrestaShop/files/3515490/parameters.php.txt)

Thanks to check & feedback.

**Comment by fdonnet** [comment]
Yes, it's defined like this :
 'database_prefix' => 'ps_',

**Comment by khouloudbelguith** [comment]
@fdonnet, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by fdonnet** [comment]
@khouloudbelguith 
1) var/cache (prod & dev) content removed
2) run oneclick upgrade from 1.7.5.2 to 1.7.6.0
3) same issue (same error)
4) clean var/cache (prod & dev) content again
5) same issue (error 500) database prefix
6) rollback to my db dump and manual backup (1.7.5.2)

Not linked to the app cache apparently

**Comment by fdonnet** [comment]
@khouloudbelguith 
For info, this shop has been upgraded with "one click upgrade module" for 2 or 3 versions already... that's the first time I have an issue like this...

**Comment by khouloudbelguith** [comment]
@fdonnet, It seems this parameter does not exist on a default PrestaShop configuration. As far as I know, the config files (except parameters.yml & parameters.php) are being overwritten when the PrestaShop files are upgraded.

I guess you modified one of them and added some additional libraries to your shop? This could explain these errors we cannot reproduce on our side.

**Comment by fdonnet** [comment]
@khouloudbelguith  Ok, it's seems very strange because it's a very minimalist implementation. My parameters.php file look like the one you put in attachment.. Do you have any advice ? Because it seems that I m not the only one who had this issue : 
https://www.prestashop.com/forums/topic/998058-after-upgrade-1740-to-1760-site-reach-500-internal-server-error/....

The only thing I modified is the creation of a classic child theme... maybe I need to search here ?

**Comment by khouloudbelguith** [comment]
@fdonnet, do you have the ViaBill module installed?

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith no, no weird module installed ;)

**Comment by khouloudbelguith** [comment]
@fdonnet, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith 
I cannot really put the site in maintenance now. (2 maintenances and rollbacks already during the last days).

But I can confirm, that I didn't have any error in the log window after the 2 tentatives I made... that's why it's very strange. (database OK etc)

**Comment by khouloudbelguith** [comment]
@fdonnet, did you tried to make an upgrade again & there is no error displayed?

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith 
Yes yesterday I made a new upgrade with your advice (remove cache content folder - prod and dev), no error is displayed (upgrade success etc, database success) but the same issue as before with database_prefix on the front-end. The backend/admin  works good.

Very strange...

For info, the custom thing I made on the frontend of this shop is a redirect to simulate a B2B shop.

I modified the init() function in a override of the FrontController 
(file: override/classes/controller/FronController.php) 

if (!$this->context->customer->isLogged() && $this->php_self != 'authentication' && $this->php_self != 'password' && $this->php_self != 'cms')
        Tools::redirect('index.php?controller=authentication?back=index');

This line allows me to redirect to the login page if the user is not logged in.
Maybe it is the problem ? But for me it's seems correct... Or I lost the context (database_prefix) with this redirect (last upgrade to 1.7.5.2 it worked fine) ?

Hope you can help.
Thx a lot for your support.
Fabien

**Comment by khouloudbelguith** [comment]
@fdonnet, could you please try to remove this override & check if the issue occurs again (try to clear cache after removing this override)
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check & feedback.

**Comment by fdonnet** [comment]
@khouloudbelguith 
Ok, I will try that, when 1.7.6.1 will be available. For now, I will stay on 1.7.5.2. 
In the meantime, I will follow the Github, if someone will raise the same issue.

It seems, for the moment, that the problem is on my side.

Thx for your help.
You can close the issue.
Regards,

**Comment by khouloudbelguith** [comment]
@fdonnet, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith could you pls reopen this issue. Even with the new version 1.7.6.1 the problem persists and I was forced to roll back to 1.7.5.2. 

I can send you the update log if needed.
Regards,
Fabien

**Comment by fabiorme** [comment]
Hello to all,
I updated prestashop from version 1.7.3.2 to version 1.7.6.1
with the one click upgrade 4.9.0 plugin, once the update was finished I had the following error:

`[INTERNAL] F:\argentissimo_v2\src\Adapter\Configuration.php line 48 - TypeError: Argument 1 passed to PrestaShop\PrestaShop\Adapter\Configuration::__construct() must be of the type array, object given, called in F:\argentissimo_v2\src\Core\Addon\Theme\ThemeManagerBuilder.php on line 84 
#0 F:\argentissimo_v2\src\Core\Addon\Theme\ThemeManagerBuilder.php(84): PrestaShop\PrestaShop\Adapter\Configuration->__construct(Object(Shop)) 
#1 F:\argentissimo_v2\classes\shop\Shop.php(489): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManagerBuilder->buildRepository(Object(Shop)) 
#2 F:\argentissimo_v2\classes\shop\Shop.php(133): ShopCore->setTheme() 
#3 F:\argentissimo_v2\classes\shop\Shop.php(413): ShopCore->__construct('1') 
#4 F:\argentissimo_v2\config\config.inc.php(119): ShopCore::initialize() 
#5 F:\argentissimo_v2\modules\autoupgrade\classes\UpgradeContainer.php(550): require_once('F:\\argentissimo...') 
#6 F:\argentissimo_v2\modules\autoupgrade\classes\TaskRunner\AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() 
#7 F:\argentissimo_v2\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeDb.php(75): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() 
#8 F:\argentissimo_v2\admin2017\autoupgrade\ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() 
#9 {main}`

and now the site gives me error 500 and the following error in the php log:

`PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "prestashop.database.naming_strategy" has a dependency on a non-existent parameter "database_prefix". in F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php:102
Stack trace:
#0 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('database_prefix')
#1 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('database_prefix')
#2 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%database_prefi...', Array)
#3 F:\argen in F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php on line 102`

have you found a solution to solve the problem?

**Comment by fdonnet** [comment]
@fabiorme a #15877 issue has been open again because on my side the problem persists even with the 1.7.6.1 upgrade.

For info, I don't have any error in the upgrade process but at the end, when the upgrade is finished without any error, I have the same database_prefix issue you described above (for the frontend part of the shop)

**Comment by fabiorme** [comment]
I activated the debug mode, and when I try to access the administrator panel the following message appears

"----------
Table 'argentissimo1761.ps_currency_lang' doesn't exist<br /><br /><pre>SELECT *
FROM `ps_currency_lang`
WHERE `id_currency` = 2</pre>
"---------

now I will try to create the table manually and see what happens ....

"-------------
CREATE` TABLE `ps_currency_lang` (

    `id_currency` int(10) unsigned NOT NULL,
    `id_lang` int(10) unsigned NOT NULL,
    `name` varchar(255) NOT NULL,
    `symbol` varchar(255) NOT NULL,
    PRIMARY KEY (`id_currency`,`id_lang`)
  ) 
"----------

once the table is created I enter the backend but in the frontend the following error appears:

"-------------
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "prestashop.database.naming_strategy" has a dependency on a non-existent parameter "database_prefix". in F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php:102 Stack trace: #0 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('database_prefix') #1 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('database_prefix') #2 F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%database_prefi...', Array) #3 F:\argen in F:\argentissimo_v2\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php on line 102
"-------------

**Comment by amigainc** [comment]
I also have the same message:

> The service "prestashop.database.naming_strategy" has a dependency on a non-existent parameter "database_prefix".

**Comment by khouloudbelguith** [comment]
Hi @amigainc,

Maybe you have an override which is incompatible with your PrestaShop version as described here: https://github.com/PrestaShop/PrestaShop/issues/15877#issuecomment-541568906

Thanks!

**Comment by n3b0r** [comment]
Hi, I was stuck in this issue too after update from 1.7.3.2 to 1.7.6.1. The problem it's caused by the PayPal module update. 

This module creates an AdminController.php class overrides in override/classes/controller. If you delete this override, you will be able to access again. 

The PayPal module it's always painful.

**Comment by khouloudbelguith** [comment]
Hi @vgsystems,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by n3b0r** [comment]
@khouloudbelguith My comment only was a hint for other people with the same problem. I was able to solve it on my own ;)

**Comment by francisco-velazquez** [comment]
I had the same problem when I was update to 1.7.3.~ to 1.7.8.~. I was solve removing the overrides (first I made my backup), there was the problem.

If somebody have problem like this, send me message for help you
