### ISSUE TITLE
Logo is missing on invoice

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#15088]
**Describe the bug**
Logo is missing on invoice if SSL is enabled.

**To Reproduce**
See this screenrecord: http://reker.dk/ssl.webm
Tested with 100% clean install of 1.7.6.0 on Windows with open SSL.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/26626066/62892105-b8aa3180-bd47-11e9-9662-7783c50bdabc.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/PrestaShop/pull/15089

**Comment by mariem-abid** [comment]
Hi @MathiasReker,

Thanks for your fix.
I manage to reproduce the issue with the last version PS 1.7.6.0
I’ll add this to the debug roadmap

**Comment by MathiasReker** [comment]
New PR: https://github.com/PrestaShop/PrestaShop/pull/15109
