### ISSUE TITLE
Product category empty in results ps_facetedsearch

### ISSUE THREAD

**Issue by ddv1976** [PrestaShop/PrestaShop#15086]
My version prestashop is 1.7.5.2

No results in category page

Screen:
https://gyazo.com/9b0f31e35038595dc15fade0c81d44ee

There are no products on any categories page!!!

Please, I need help with this.

**Comment by mariem-abid** [comment]
Hi @ddv1976,

I did not manage to reproduce the issue with the last version PS 1.7.6.0 and the module  ps_facetedsearch v3.2.0.
I attached a video record
https://drive.google.com/file/d/1ZUdUqLgp1FAoBKdqbRrKwDQ5WuVL8z6h/view
What is the exact version of PS and the module ps_facetedsearch did you installed?

**Comment by ddv1976** [comment]
> 
> 
> Hi @ddv1976,
> 
> I did not manage to reproduce the issue with the last version PS 1.7.6.0 and the module ps_facetedsearch v3.2.0.
> I attached a video record
> https://drive.google.com/file/d/1ZUdUqLgp1FAoBKdqbRrKwDQ5WuVL8z6h/view
> What is the exact version of PS and the module ps_facetedsearch did you installed?

Hello!

My version of prestashop is 1.7.5.2
https://gyazo.com/5c980db9156e3cb79ae6c7e64e501b70

The ps_facetedsearch module is 3.1.0
https://gyazo.com/a4c5140d6245ed9310dd49f0930b615e
https://gyazo.com/210ae9f1be5b4883fdc84692802380dc

No results are shown in any category, there are more than 700 products in the store:
https://gyazo.com/de119f229072d5be8a28c85c15d07c7f
https://gyazo.com/74d4f1982a4bde42f7d24a1c1876f181

It's strange, the products are shown by brand but not in categories, without the filter:
https://gyazo.com/f8c6af09b40673905367d4e02d08a220

**Comment by marionf** [comment]
@ddv1976 

I am not sure your issue is related to faceted search, as the category is empty when you click on it before making a filter through faceted search.
Furthermore, I don't see facetedsearch here for example: https://www.calzadosclubverde.es/18_48-hours

![capture d'écran_1888](https://user-images.githubusercontent.com/13449658/63012178-15ae0080-be8a-11e9-8364-dccbd14e30f9.png)

Could you try to disable facetedsearch module and tell us if your category is still empty ?

**Comment by ddv1976** [comment]
Hi, thanks for your attention!

Try this:

I deactivated the ps_facetedsearch module and the categories and subcategories again showed products! The module is still disabled so you can see:
https://gyazo.com/0d7a35f8e7c00a9aea6cc7ca8f9a4dbb

Capture of the parent category and subcategories and brands:
https://gyazo.com/9e59553a5a818c2d1d72161966db483d

The problem now is the products of the subcategories, they are not shown in the parent category. For example, the Caballero category only shows 2 products ???
https://gyazo.com/3501cce3ff9d20a02546d3de679af691

When I reactivate the module facetedsearch again the products disappear from the categories and subcategories! But not of the brands.

So, the facetedsearch module is not working?

**Comment by marionf** [comment]
@ddv1976 
I think the option "Show products from subcategories" in your factedsearch module is disabled ?
Could you try to enable it and reactivate facetedsearch module ?

**Comment by ddv1976** [comment]
Hi
![Screenshot_2019-08-14 Gyazo(1)](https://user-images.githubusercontent.com/34251232/63037666-2445e900-be85-11e9-8498-ef218f189022.png)
Show products from subcategories is actived

**Comment by ddv1976** [comment]
Hello
I activate visualize the facetedsearch, the filters and quantity of products appear in the filters, but none are displayed! What will be the problem?
I do not understand!
![Screenshot_2019-08-15 Comprar Online mejor Calzado de calidad para Caballeros](https://user-images.githubusercontent.com/34251232/63093253-14ccab80-bf2a-11e9-8ef6-62b05c87df00.png)

**Comment by mariem-abid** [comment]
Hi @ddv1976,

Did you use the default template by Prestashop?

**Comment by ddv1976** [comment]
Hi
No, I use the theme:
warehouse version 4.2.1
![Screenshot_2019-08-15 Tema y logotipo • CalzadosClubVerde](https://user-images.githubusercontent.com/34251232/63104145-07241f80-bf44-11e9-8996-6f8a3b0f35a7.png)

**Comment by mariem-abid** [comment]
@ddv1976, Could you please check with the default theme and feedback.

**Comment by ddv1976** [comment]
Hi

I solved the problem, install the module that comes with the installation of prestashop 1.7.5.2, the version of the facetedsearch module v2.2.0, now the products are displayed without problems.
![Screenshot_2019-08-16 Comprar Online mejor Calzado de calidad para Caballeros](https://user-images.githubusercontent.com/34251232/63176641-ed4e0f80-c00b-11e9-9b75-9d111d885b28.png)

Thank you for your attention, help and patience.
Greetings.

**Comment by mariem-abid** [comment]
@ddv1976, thanks for your feedback.
I close the ticket, feel free to open a new one when needed.
