### ISSUE TITLE
Fix support of Twig 2 in the optional build

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#15087]
**Describe the bug**
No matter the contribution, the optional build is broken with explicit error messages:

* "admin_themes_index" ('Theme & logo', 'admin_themes_index') Twig\Error\RuntimeError: Variable "ps" does not exist.
* "admin_mail_theme_index" ('Email Theme', 'admin_mail_theme_index') Twig\Error\RuntimeError: Variable "ps" does not exist.
* "admin_emails_index" ('Advanced parameters E-mail', 'admin_emails_index') Twig\Error\RuntimeError: Variable "ps" does not exist.

You need to import the macro "ps" inside the templates that require its functions.

**To Reproduce**
Trigger a Travis build _or_ do a composer update and then try to access the related pages.

**Additional information**
PrestaShop version: 1.7.6.x+
PHP version: 7.1.3+ (Twig 2 is not available in PHP 5)

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/13761

**Comment by mariem-abid** [comment]
Hi @mickaelandrieu,

Hi @8ternity,

Here's the PR: #13761 to fix the issue.
Your ticket is a duplicate of #12461
So, I close it.
Thanks!

**Comment by mariem-abid** [comment]
Duplicate of #12461
