### ISSUE TITLE
Prestashop 1.7.6.0 Private note not saved

### ISSUE THREAD

**Issue by ConvarDeutschland** [PrestaShop/PrestaShop#15091]
Hello,

In Prestashop 1.7.6.0 the private notes are not saved

Goto Orders, click on view, enter a text in private note, click on save
The note is not saved and a green notification withrhe text undefined is dsplayed.

If you select "vie full details..." and save the private note there it works
![Comment_not_saving](https://user-images.githubusercontent.com/14978257/62924704-f3947f80-bdb0-11e9-99d7-b1c1fadc3f9f.jpg)

**Comment by mariem-abid** [comment]
Hi @ConvarDeutschland,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record
https://drive.google.com/file/d/1liIIyHxmxnDZeNDeFU_Mq5qyijaCF0zg/view

Thanks for check and feedback.

**Comment by ConvarDeutschland** [comment]
Hello I did supect the google map script to made some problem but after removing it the symptom is still the same. Maybe our version of 1.7.6.0 is not the same as yours. Waht I want to do is to download the latest version of 1.7.6.0 and try to replace our files with the downloaded one. can you tell me exactly witch file I need to swap. Thanks

**Comment by ConvarDeutschland** [comment]
Hi @mariem-abid,

I did made some more research about this error and found the solution here.

https://github.com/PrestaShop/PrestaShop/pull/13916

after updating the view.tpl file it work sagain

Thanks for your help

**Comment by mariem-abid** [comment]
Hi @ConvarDeutschland,

Thanks for your feedback
Feel free to open a new one when needed.
