### ISSUE TITLE
Product not showing up when listed in multiple categories

### ISSUE THREAD

**Issue by s-mancia** [PrestaShop/PrestaShop#15094]
**Describe the bug**
When a product is listed in multiple categories the product is only listed in the "Main category".

Meaning if I list a product in Category 1 and Category 2 and put Category 1 as "Main category" it only shows up in Category 1 in the frontend.

Please confirm this issue, last version this was working fine.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.3.8
Theme: classic Version 1.0.0

**Comment by mariem-abid** [comment]
Hi @Swerone,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by s-mancia** [comment]
Thanks for the response @mariem-abid.

Just downgrades to PHP 7.2.21, cleared cache both in PS and the browser, readded a new product in two different categories and still, it only shows the product in the main category.

Where you able to reproduce the issue?
Kind regards

**Comment by taniacr** [comment]
I have the exact same issue in 2 stores. Here are both configurations:

Live store:
PHP Version: 7.1.31 
PrestaShop: 1.7.6.0 

Local:
PHP Version: 7.2.16 
PrestaShop: 1.7.6.0

**Comment by mariem-abid** [comment]
Hi @Swerone, @taniacr,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1n87oKwH2xxsgGLuPB932oMX7ZWUr0IGD/view

Thanks for check and feedback.

**Comment by s-mancia** [comment]
Hi @mariem-abid 
I just found the cause to the issue I think.
I configured the ps_facetedsearch module to not show products from the subcategory in the parent category and when I re-enable "Show products from subcategories" the product shows up correctly.

Please try this "Modules -> ps_facetedsearch"

And disable "Show products from subcategories"

Now I don't actually know if this was the right way to stop Prestashop from showing products in the parent category when the product hasn't been marked to be shown in that category.

**Comment by mariem-abid** [comment]
@Swerone, this is the normal behavior of the module.
I close the ticket, feel free to open a new one when needed.
