### ISSUE TITLE
Problems with my email

### ISSUE THREAD

**Issue by efren1975** [PrestaShop/PrestaShop#15090]
I ask to refresh my ´password to log in in my session in prestashop
because  i forgo it .
But I did not receive noting in mi email

![Bug](https://user-images.githubusercontent.com/54050460/62912187-ac74a300-bd4c-11e9-86ba-1cfd053f2ef3.jpg)

**Comment by GTAR777** [comment]
I never made an account

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GTAR777** [comment]
But i will because im working for the ecommerce development.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mariem-abid** [comment]
Hi @efren1975,

I did not manage to reproduce the issue with PS 1.7.6.0.
What is the exact version of PS did you installed?

**Comment by efren1975** [comment]
it is the most recent version

**Comment by efren1975** [comment]
I changed the password in the database but still not working. I do not know what can i do more.

**Comment by mariem-abid** [comment]
@efren1975, could you please try to change the password from the Back Office.
Thanks for check and feedback.

**Comment by efren1975** [comment]
From the Back office? I do not how to do that.

**Comment by mariem-abid** [comment]
@efren1975, try to navigate to BO=> Customers => Customers=> Click on the edit button for the client you wish to change the password.

Thanks for check and feedback.

**Comment by efren1975** [comment]
mariem-abid thanks so much for your answers, But that is the problem i have. I can not acces to the back office because i can´t remenber my password. :-)

**Comment by mariem-abid** [comment]
Hi @efren1975,

Could you please try to reproduce these steps:
1-You need to find out your COOKIE KEY: navigate to the app/config folder. Open the file parameters.php and find the "cookie_key".
2- Go to the phpMyAdmin and navigate to your PrestaShop database. Find the table ps_employee and click on the edit button for your account.
3-Scroll down to the field labeled "passwd" and clear the field from your old encrypted password.
4-Paste the COOKIE KEY followed by your new password.
5-Select MD5 as our function
6-Click on the Go button.

Thanks for check and feedback.

**Comment by efren1975** [comment]
Mariwm abid thanks so much for your support. You are a nice person.
I reproduce the steps.
I found the COOKIE Key in the parameters folders
2.- I went to phpMyAdmin and i navigated to Prestashop database. I found the table ps_employee and i did click on the edit button.
3 Scrolled down to field labeled "passwd"
I did the stpes 4, 5 and 6 and still not working. I do not Know what happened

**Comment by mariem-abid** [comment]
@efren1975, You are sure of the email address is correct?

**Comment by efren1975** [comment]
I will send you a image

**Comment by mariem-abid** [comment]
@efren1975, could you please record a video for all the steps already mentioned.

**Comment by efren1975** [comment]
I do not have a software to record it.

**Comment by efren1975** [comment]
![cookie](https://user-images.githubusercontent.com/54050460/63034125-599b0880-be7e-11e9-8dd7-239cba5fa4b7.jpg)

**Comment by efren1975** [comment]
![employee](https://user-images.githubusercontent.com/54050460/63034164-67508e00-be7e-11e9-84a5-17ac765723e3.jpg)

**Comment by efren1975** [comment]
![new password](https://user-images.githubusercontent.com/54050460/63034205-7a635e00-be7e-11e9-83f5-2f92c30a857e.jpg)

**Comment by efren1975** [comment]
![new password 2](https://user-images.githubusercontent.com/54050460/63034253-91a24b80-be7e-11e9-9612-1e905f506c84.jpg)

**Comment by mariem-abid** [comment]
@efren1975, exactly, and the problem still again?

**Comment by efren1975** [comment]
Yes, take a look
![error](https://user-images.githubusercontent.com/54050460/63035120-307b7780-be80-11e9-88cc-40ad8a288cf8.jpg)

**Comment by mariem-abid** [comment]
@efren1975, the changed password it's for the Back Office not for the Front Office, and with the Back Office, you can change the passwords of the customers.

Thanks for check and feedback.

**Comment by efren1975** [comment]
So...I will have to reinstall the pre4stashop again.

**Comment by mariem-abid** [comment]
@efren1975, try to connect to the Back Office with the new password.

**Comment by efren1975** [comment]
i can not access to Back office

**Comment by efren1975** [comment]
To acces to Back office i need a login

**Comment by mariem-abid** [comment]
Hi @efren1975, 

Your login is "efrenlazde@hotmail.com".

**Comment by efren1975** [comment]
Hi mariem-abid
 Yes that is my login. I could access to my Back office. Right now I´m looking to change the login in my front office

**Comment by mariem-abid** [comment]
@efren1975, does your problem is solved?

**Comment by efren1975** [comment]
Yes. But I am looking to change the login in the front office

**Comment by efren1975** [comment]
I want to create a online-shop and i though prestashop was easy but not much.

**Comment by mariem-abid** [comment]
@efren1975, Prestashop is easy.
For logins and passwords of customers, you find it in the Back Office: navigate to Back Office=>  Customers => Customers.
I close the ticket, feel free to open a new one when needed.
