### ISSUE TITLE
Save button not showing on carriers edit after upgrade from 1.7.5.2 to 1.7.6.0

### ISSUE THREAD

**Issue by boomdrak** [PrestaShop/PrestaShop#15101]
After upgrading til 1.7.6.0 -> BO -> Carriers and Edit on a specific.
The "Save" button is not there any more.

https://shop.xx.no/xxxxx/index.php?controller=AdminCarrierWizard

console says :

notifications.js:77 Uncaught ReferenceError: admin_notification_get_link is not defined
    at getPush (notifications.js:77)
    at HTMLDocument.<anonymous> (notifications.js:58)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)

Screenshot: ![carrier edit no save button](https://user-images.githubusercontent.com/4997449/62968178-cc6a9c00-be0a-11e9-8955-aafd708e245f.png)

**Additional information**
PrestaShop version: 1.7.6.0 - upgrade from 1.7.5.2
PHP version: 5.6.40

**Comment by mariem-abid** [comment]
Hi @boomdrak,

Could you please clear cache, check your shop with another browser and feedback.

**Comment by boomdrak** [comment]
Hey @mariem-abid 

That was the first ting i tryd before creating an issue.
Cleared cache, disabled cache, disabled all non-prestashop modules, tryd debug-mode and disabled css caching.

Same result i newest version of Chrome and Firefox.

Also cleared client cache in browser..

**Comment by mariem-abid** [comment]
Hi @boomdrak,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by boomdrak** [comment]
cPanel v82.0.8
Linux web.cc.no 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Server version: Apache/2.4.39 (cPanel)
Server built:   Jul  1 2019 21:24:05
Compiled in modules:
  core.c
  mod_so.c
  http_core.c

mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

PHP 5.6.40 (cli) (built: Aug  6 2019 03:54:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

I get alot of errors from https://shop.xxx.no/js/admin/notifications.js
notifications.js:77 Uncaught ReferenceError: admin_notification_get_link is not defined
    at getPush (notifications.js:77)
    at HTMLDocument.<anonymous> (notifications.js:58)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)

Also i cannot disable any modules anymore, see video for more details on all issues:

**I can se that BO is trying to access url https://shop.cc.no/cc/themes/new-theme/public/index.php?controller=AdminDashboard&token=xx)**

Latest http_error_log
[](
[Sun Aug 18 11:04:51.451976 2019] [cgi:error] [pid 29084] [client 1.1.1.1.1:64216] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://shop.cc.no/admin818nx3gxz/index.php/improve/modules/manage?_token=emxidAlz5sQVqxT2TSwilT-jsvvzGTvQZ0QB3pU-ngk

[Sun Aug 18 11:06:55.171157 2019] [cgi:error] [pid 15225] [client 1.1.1.1.1:64757] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://shop.cc.no/admin818nx3gxz/index.php/improve/modules/manage?_token=emxidAlz5sQVqxT2TSwilT-jsvvzGTvQZ0QB3pU-ngk

[Sun Aug 18 11:08:30.267333 2019] [cgi:error] [pid 29064] [client 1.1.1.1.1:65169] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://shop.cc.no/admin818nx3gxz/index.php/improve/modules/manage?_token=emxidAlz5sQVqxT2TSwilT-jsvvzGTvQZ0QB3pU-ngk

[Sun Aug 18 11:09:00.109932 2019] [cgi:error] [pid 29084] [client 1.1.1.1.1:65367] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://shop.cc.no/admin818nx3gxz/index.php/improve/modules/manage?_token=emxidAlz5sQVqxT2TSwilT-jsvvzGTvQZ0QB3pU-ngk

[Sun Aug 18 11:09:23.422441 2019] [cgi:error] [pid 28897] [client 11.11.11.11:65443] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://shop.cc.no/admin818nx3gxz/index.php/configure/advanced/system-information/?_token=emxidAlz5sQVqxT2TSwilT-jsvvzGTvQZ0QB3pU-ngk)

**Comment by boomdrak** [comment]
All my own stupid fault!
Im so sorry for taking up your time :)

Forgot to rename old new /admin folder til /adminXXXXX
