### ISSUE TITLE
Stats not working part II

### ISSUE THREAD

**Issue by silviu25** [PrestaShop/PrestaShop#15106]
For part I please read here: https://github.com/PrestaShop/PrestaShop/issues/14164

I'm coming with news
I installed a fresh new PS 1.7.6.0 on a subfolder (ex: www.mysite.com/2 )
I installed and configured a new theme, then I checked and everything was fine, including stats.
I moved entire PS 1.7.6.0 from subfolder to root (ex: www.mysite.com) and everything is fine except stats. They show 0 for all including online visitors and etc.

**Comment by mariem-abid** [comment]
Hi @silviu25,

Could you please try to clear cache and feedback.

**Comment by silviu25** [comment]
I cleaned the cache, I did a reset on statsforecast module, I deleted ./var/cache/dev and prod

**Comment by mariem-abid** [comment]
@silviu25, the problem still again?

**Comment by silviu25** [comment]
yes

**Comment by mariem-abid** [comment]
Hi @silviu25,

Could you please check with your host and feedback.

**Comment by silviu25** [comment]
since it was working on "www.domain.com/2" I think there are no problems with the host

**Comment by khouloudbelguith** [comment]
Hi @silviu25,

Thanks for your report.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by silviu25** [comment]
I activated debug mode and deactivated cache but is not generating any PHP error log

**Comment by khouloudbelguith** [comment]
@silviu25, in my case, I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1rVoBM1lNg3XATIlnDD6mIIvd_JxCDvoQ/view
Thanks to check & feedback.

**Comment by silviu25** [comment]
I know it's annoying since it worked in the subfolder and now it has stopped.
I tried everything but I don't know what else to do

**Comment by khouloudbelguith** [comment]
@silviu25, you can install the Google Analytics module, it is very simple for the statics.
![ga](https://user-images.githubusercontent.com/16067358/63511294-b75fce00-c4d8-11e9-89c5-24105a806425.png)
Thanks to check & feedback

**Comment by silviu25** [comment]
I;m already using Google Analytics module but it is just annoying to know there is a function which is not working
Thanks

**Comment by khouloudbelguith** [comment]
@silviu25, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.


Thanks!

**Comment by ghost** [comment]
I can't believe that nobody help with that trivial bacic and setup! Statisctics works only when correct status was set - and Invoice mark is set...

![mark](https://user-images.githubusercontent.com/8243273/71082484-78ddd580-2191-11ea-8bd7-9d8480e05580.png)

**Comment by neich78** [comment]
I have same issue in PS 1.7.6.4. Many of the statistics appear to 0. The most important info is "best customers" that does not show any data. 
I have reseted all stats modules, change php version (now have PHP 7.3.17), etc, with no result. 
![Captura de pantalla 2020-05-28 a las 23 30 20](https://user-images.githubusercontent.com/11721870/83195977-63ef7000-a13b-11ea-9f80-2fce7ecd7943.png)
Thanks
