### ISSUE TITLE
Prestashop 1.7.6 product page - module tab - not working

### ISSUE THREAD

**Issue by maposka** [PrestaShop/PrestaShop#15104]
**Describe the bug**
Can't configure modules on product page tab, when I click configure nothing happens.

**To Reproduce**
1. Go to 'Products Catalog'
2. Click on 'Product then on Module '
3. If you have a product on this hook click configure
4. Nothing happens.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**

PrestaShop version: 1.7.6.0
PHP version: 7.2

![image](https://user-images.githubusercontent.com/44245055/62983625-59741c00-be30-11e9-8436-ed6ae4063f9f.png)

**Comment by mariem-abid** [comment]
Hi @maposka,

I manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1URJMkXTpN0QrJknvGRT6m8nkH--pqXIo/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@mariem-abid 
Can you try to reproduce it with 1.7.5.2 and tell us if it's a regression or not ?
Do you have any errors in the console ?

**Comment by mariem-abid** [comment]
@marionf, I manage to reproduce the issue with PS  1.7.5.2
I attached a video record.
https://drive.google.com/file/d/1c-Y41brSI9emlqtb0QRDuszdKs0JPe-X/view

**Comment by mariem-abid** [comment]
@maposka, @marionf , I did not manage to reproduce the issue with the last version 1.7.6.0.
The used Hook is displayAdminProductExtra.
I attached a screenshot and a video record.
![test](https://user-images.githubusercontent.com/36841537/63016291-3034a980-be8b-11e9-8f9a-53a5a51d0ed6.png)
https://drive.google.com/file/d/138RXIX--eZpaeS2HLxgg1m0rDVAkw8JC/view

Thanks for check and feedback.

**Comment by maposka** [comment]
Hi, sorry but I am laik - what can I must do? What and where I must repair?????
Thank you very much

**Comment by mariem-abid** [comment]
@maposka, thank you for sending us the module to test it.

**Comment by maposka** [comment]
[v1.7.6-bestkit_preorder.zip](https://github.com/PrestaShop/PrestaShop/files/3501429/v1.7.6-bestkit_preorder.zip)
[v2.1.1-advanceseo.zip](https://github.com/PrestaShop/PrestaShop/files/3501430/v2.1.1-advanceseo.zip)
[v2.7.13-productvideo.zip](https://github.com/PrestaShop/PrestaShop/files/3501440/v2.7.13-productvideo.zip)

**Comment by mariem-abid** [comment]
@maposka, I tested with the module bestkit_preoder => it's OK (See screenshot)
![AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-14_2_49](https://user-images.githubusercontent.com/36841537/63026298-d7710b00-bea2-11e9-9fad-baa06bae8a61.png)
The Modules page of the Products page is specified for the functions of a given product.
To have the same configuration on the Module Manager page, you have to add the same code.

Thanks to check and feedback

**Comment by maposka** [comment]
sorry I do not know which code and when I make it.... :-((

**Comment by mariem-abid** [comment]
Hi @maposka,

In the "productAdminTab.tpl" file: project folder / modules / bestkit_preorder / views / templates / hook/  you can do the desired modification.

**Comment by maposka** [comment]
O.K.
Thank you very much :-)

**Comment by mariem-abid** [comment]
@maposka, You are welcome.
Feel free to open a new one when needed.
