### ISSUE TITLE
Faceted search | Unusable - OR behavior between filters

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15103]
After upgrade to 3.2.0, faceted search returns all product that match filter A OR that match filter B. See the video. Explains it all.

I want a Red BMW in diesel.
I select Brand BMW, Fuel diesel, Color Red.
Why I get shown all BMWs, all diesel cars and all red cars?

This is not even funny.

**Video**
https://drive.google.com/file/d/1lkDe0eFc0UUXhWVAudnB-iPyNIkOO-zo/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6
PHP version: 3.2.0

**Comment by ghost** [comment]
> This is not even funny.

Yes. Not funny :(

**Comment by marionf** [comment]
Hello @Hlavtox 

I manage to reproduce the issue with facetedsearch v3.2.0
It was working with facetedsearch v3.1.0

**Comment by Seeebastian** [comment]
+1 I also have this problem in my shop. I think it's a huge regression.

**Comment by PierreRambaud** [comment]
My bad... Should be fixed with https://github.com/PrestaShop/ps_facetedsearch/pull/123

**Comment by maarlok** [comment]
I have the same problem on v3.2. It does not work well
