### ISSUE TITLE
Doesn´t work on 1.7.6

### ISSUE THREAD

**Issue by isaiasreyez** [PrestaShop/PrestaShop#15119]
**Describe the bug**
The Module doesn´t work on prestashop 1.7.6

When I install the module directly from prestashop install module option, I recieve an error of installation

**To Reproduce**
1. Go to 'Modules'
2. Click on 'Module manager.'
3. Then¨Install a module¨
4. Choose from downloads folder ¨productcomments-master.zip´
5.Error

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.21

**Comment by mariem-abid** [comment]
Hi @isaiasreyez,

I manage to reproduce the issue with the last version PS  1.7.6.0
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
Hello @isaiasreyez 

You cannot upload the zip directly downloaded from github.
You can find the module in Module catalog in your back-office

![capture d'écran_1890](https://user-images.githubusercontent.com/13449658/63151021-b7f3f280-c008-11e9-86ee-8f6b2d7d3a44.png)

**Comment by isaiasreyez** [comment]
I Can't install directly from front office, Prestashop show me an installation error.

**Comment by khouloudbelguith** [comment]
@isaiasreyez, this zip folder is invalid.
You need to rename it to productcomments, unzip it & install the composer then compress it again.
You can try with this zip file.
[productcomments.zip](https://github.com/PrestaShop/PrestaShop/files/3520146/productcomments.zip)

Thanks!
