### ISSUE TITLE
Back office is very slow at first loggin

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#15115]
**Describe the bug**
Hello
When I acces each time to my backoffice it takes a while to load data and let me move to an other menu as commande or SAV

Here is a video shows you that issue 
and my errors log 
https://youtu.be/e8ojDP4zhM8 
https://youtu.be/IEYwv5-2s50

https://pastebin.com/embed_js/8r36UZqW

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
Version de PrestaShop : 1.7.6.0
Version de PHP : 7.2.21

**Comment by mariem-abid** [comment]
Hi @go-sudo,

Could you please try to clear cache from your project and your navigator and feedback.

**Comment by go-sudo** [comment]
Hello

I was able to reproduce the issue. Page Catalogue > Produits required about 1.4 minutes to be opened after logging in. Please find the screenshots attached.

This delay of TTFB (Time to first byte) the most probably caused by the PHP script which processes the request:
https://gggg.com/hdfghdfdfgj/index.php/sell/catalog/products?_token=Hi25rIPupWNEdQMVTiQfyeVRgKTxshF9IDqlvwPzulc 

At the same time, the site itself loads quickly: https://playstore.ma/ 

I have reviewed all the available log files but didn't find any issues from the server side.

![Screenshot1](https://user-images.githubusercontent.com/11594433/63518032-74115980-c4f0-11e9-887f-03767f08a445.png)
![Screenshot2](https://user-images.githubusercontent.com/11594433/63518034-74a9f000-c4f0-11e9-847b-94557ec32ea7.png)

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Could you please try to enable profiling mode
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks!

**Comment by go-sudo** [comment]
Hello 

I made this changes and now the back office is down 

Regards,
![back](https://user-images.githubusercontent.com/11594433/63651562-e6cb4080-c74d-11e9-8a22-e876adc0b5c3.png)
![2019-08-25_15-35-12](https://user-images.githubusercontent.com/11594433/63651578-18dca280-c74e-11e9-9345-3a71b7cae012.png)

**Comment by khouloudbelguith** [comment]
@go-sudo, could you please try to enable the debug mode & try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by go-sudo** [comment]
Hello

https://youtu.be/egrU8JEk2Gw

**Comment by khouloudbelguith** [comment]
@go-sudo, I checked your screen record.
The load time is the BO => Order page is very slow comparing the Products Page.
The time for the Order page is 1.5 min but in the product page is 2.11s
In your screen record, you displayed the profiling in the product page which is ok, but you need to trace all SQL queries in the order page to find what is slow for you on the order page.

Thanks!

**Comment by go-sudo** [comment]
Hello

I appreciate your help, any help for recommendations please to trace the 
sql queries

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, The profiling mode is enabled in your case.
You need to navigate to your BO => Orders page => scroll down to the buttom of the page to check what is slow for you on the order page.

**Comment by go-sudo** [comment]
![image](https://user-images.githubusercontent.com/11594433/64084255-609c9480-cd21-11e9-9ecd-dd189ce2cd43.png)

**Comment by khouloudbelguith** [comment]
@go-sudo, thanks for your feedback.
You have some modules installed, they could be causing this issue.
![image](https://user-images.githubusercontent.com/16067358/64112270-dc78fa00-cd7e-11e9-9cd5-a7116987067b.png)
As they are not provided by Prestashop, we can't do anything with this. 
You should contact the module's authors via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by go-sudo** [comment]
Hello

I appreciate your help and i will contact theme soon 

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, thanks!
Waiting for your feedback.

**Comment by go-sudo** [comment]
Hello @khouloudbelguith 
since the modules dev doesnt reply I decided to uninstall all them but the issue is always here

https://www.youtube.com/watch?v=XgQGWsT7TZ0
https://ibb.co/fYFTWPY

**Comment by khouloudbelguith** [comment]
@go-sudo, what is the exact version of the module gamification did you use?
If you try to disable it temporarily => the issue occurs again?

Thanks!

**Comment by go-sudo** [comment]
Hello @khouloudbelguith 

I disabled and I removed the prod folder it but the issue occurs 

https://www.youtube.com/watch?v=vJNpWLkrV_o
Regards

**Comment by khouloudbelguith** [comment]
@go-sudo,  Try to enable the profiling mode again.
Try to navigate to your BO => Dashboard page => scroll down to the bottom of the page to check what is slowing this page.

Thanks!

**Comment by go-sudo** [comment]
Hello

https://drive.google.com/file/d/1mdGiicQcWYxdgmozHuWP8_YllP9bMeji/view

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, thanks!
As you can in the profiling mode => the execution time is ok
![image](https://user-images.githubusercontent.com/16067358/64682446-601aa100-d479-11e9-95cc-0e1093d2392d.png)
![image](https://user-images.githubusercontent.com/16067358/64682486-732d7100-d479-11e9-9eea-afa7b9ed6fb8.png)


Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

When i disable the profiling mode and now i get 1.4 min before the before the  BO is fully loaded
![image](https://user-images.githubusercontent.com/11594433/64783648-3f794680-d560-11e9-86e0-b9df9c050e05.png)

Regards,

**Comment by khouloudbelguith** [comment]
@go-sudo, did you disable only the profiling mode? 

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (TES)`: brings together in a single file, compresses and caches JS files.
- `Minify HTML (YES)`: removes all the white space from the HTML code.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

Thank you very much I disabled the statsdata and cleared the tables and the BO is loaded faster event when i enabled gain the module is still faster so i think that the data stored in the tables which causes that 
any idea how to make a cron to clear this data for ex every 15 days

I'am enabling now the others modules which i disabled before.

for the settings there are already all activated and I'm using MEMCACHED too 

Regards


![image](https://user-images.githubusercontent.com/11594433/64787084-dac1ea00-d567-11e9-8bda-f73c259697ce.png)

**Comment by khouloudbelguith** [comment]
@go-sudo, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
We have a cron module but it is NOK as reported here: https://github.com/PrestaShop/PrestaShop/issues/13825

Thanks!
