### ISSUE TITLE
[IMPROVEMENT] Make separate error templates for empty product lists and search

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15118]
**Current situation**
Currently, `errors/not-found.tpl` is used for 404s, empty categories, empty product listings (new products etc.) and for empty search queries.

"Sorry for inconvinience, find what you are looking for." is eeeeew wording for these situations. At first, upon 1.7 install I was wondering if my rewrites are working, I thought these are 404s.

**Proposed solution**
Make templates with different wordings like "There are no products in this category." and use it in `catalog/listing/product-list.tpl`.

- Search: "There are no products that match your criteria. Try to search something else."
- New products: "There are no new products this time."
- Empty category: "There no products in this category."
etc.

**Specifications**
https://github.com/PrestaShop/prestashop-specs/pull/200/files

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment]
@Hlavtox, thanks for your report.
@marionf, @colinegin, what do you think?

**Comment by hibatallahAouadni** [comment]
Firendly reminder :slightly_smiling_face: 

Ping @PrestaShop/product-team I think @Hlavtox idea about chaging the wording 
**`Sorry for inconvinience, can not find what you are looking for.`** => **`There are no products in this category.`**
 is a good idea, do you agree with me?

**Comment by Julievrz** [comment]
I think it is always a good idea to specify error messages, by explaining to the user what the error is and more importantly, how to solve it. We should wait for the PM's validation though. (@LouiseBonnard maybe? ☺️) 
However, I was not able to find the exact string you are talking about... 🤔 Would be great if you could specify the exact string and its domain. Thanks!

**Comment by Hlavtox** [comment]
@Julievrz These are the strings: https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/errors/not-found.tpl It's universal error message, when the product list is empty.

**Comment by LouiseBonnard** [comment]
Hi @Hlavtox, thanks for the improvement idea!

<img width="1127" alt="Capture d’écran 2021-01-06 à 13 45 17" src="https://user-images.githubusercontent.com/32565890/103770201-ea4f2700-5025-11eb-8730-c2cad1b66d39.png">

Indeed, this content looks quite old... I agree with rewording it: either we keep a generic message that would suit every customer situation, either we create a customized message for each situation. I'm fine with both as long as it helps users navigate the store. @Julievrz, your choice! ;-)

**Comment by Julievrz** [comment]
Here is my suggestion:

Search: "No matches were found for your search" in Shop.Theme.Global
"Check for misspellings or use other keywords to describe what you are searching for." Shop.Theme.Global
![image](https://user-images.githubusercontent.com/70583503/103784373-27251900-503a-11eb-897c-4286a468892d.png)

Empty categories: “There are no products in this category” in Shop.Theme.Global
“Check back later or try another search.” 
![image](https://user-images.githubusercontent.com/70583503/103785603-b0891b00-503b-11eb-991f-66b37368e521.png)

I think the empty category wording could also be used for the "New products" category. 

what do you think? 

I could not reproduce the "Error 404", it would be nice if you could give me the steps to reproduce :)

**Comment by Hlavtox** [comment]
https://test177.trendo.cz/gb/hdhshaha

@Julievrz Put any nonsense to the url. 😄

What about something like: “Unfortunately, there are no products here at this time.”? If you eliminate the word “category”, it could be used on new products page and others.

**Comment by Julievrz** [comment]
I understand what you mean. For empty categories, no new products, etc... We could use a more generic message that could apply to many situations. Let me know what you think. 

"No products available yet" 
"Stay tuned! More products will be shown here as they are added."
"Try another search" 

![image](https://user-images.githubusercontent.com/70583503/104297215-e2c6cc80-54c2-11eb-81f4-7790c960c453.png)

All of the strings would be located in Shop.Theme.Global

@LouiseBonnard @Hlavtox Wdyt? ☺️

**Comment by Hlavtox** [comment]
@Julievrz Yesssss!

Last suggestion - I would remove “Try another search”, because 99% of cases, the person who sees this did not come from a search. (Search page will have it's own error.)

I would change it to this:
"No products available yet"
"Stay tuned! More products will be shown here as they are added. Also, try to use the search to find what you are looking for."
"Search..."

**Comment by Julievrz** [comment]
Hi @Hlavtox, Thanks for your suggestion! I feel like your second sentence is quite long but we could definitely remove the "Try another search" and replace it with "Search our catalog" like in the previous template.

So to summarize: 

Search: 
"No matches were found for your search" in Shop.Theme.Global
"Please try other keywords to describe what you are searching for." Shop.Theme.Global
"Search our catalog" in Shop.Theme.Global 

More generic message for other situations (e.g. no new products, empty categories, ...) 

"No products available yet" Shop.Theme.Catalog
"Stay tuned! More products will be shown here as they are added." Shop.Theme.Catalog
"Search our catalog" Shop.Theme.Catalog

@LouiseBonnard What do you think of this suggestion?

**Comment by LouiseBonnard** [comment]
Hi @Julievrz, sounds great, thanks! Misspellings might be taken into account depending on the search parameters set by the user so I'll just shorten the wording into _Please try other keywords to describe what you are searching for._ in _Shop.Theme.Global_. :-)

**Comment by Julievrz** [comment]
Great, thanks, I will modify my comment!

**Comment by hibatallahAouadni** [comment]
@Julievrz @LouiseBonnard Great work girls :muscle: 
@Hlavtox you too :rocket: :superhero: 
Well I think it's time to change the lable to **`To Do`** :wink:

**Comment by Julievrz** [comment]
> @Julievrz @LouiseBonnard Great work girls 💪
> @Hlavtox you too 🚀 🦸
> Well I think it's time to change the lable to **`To Do`** 😉

I agree, great teamwork on this one. 😊 Thanks @Hlavtox

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/PrestaShop/pull/22908

I opened this, so you can set different string inside the 404 template directly from where your using this file using variable inside `include` tag or even smarty blocks

Btw, I can't manage to change the input placeholder as it comes from the backend, which probably never know the context he's in, maybe you can help for this @Hlavtox ? Otherwise I'll need to ask for a backend dev to help me :/

**Comment by Hlavtox** [comment]
@NeOMakinG @Julievrz @LouiseBonnard What if we ditch the idea of changing the search input placeholder? It's included from another file and it would make things more difficult...

![Výstřižek](https://user-images.githubusercontent.com/6097524/105161004-2d72c500-5b11-11eb-954e-2f722fb68a90.JPG)

**Comment by Hlavtox** [comment]
@NeOMakinG See my PR, I think it will be enough like this, and we don't need to modify the core https://github.com/PrestaShop/PrestaShop/pull/22913

**Comment by NeOMakinG** [comment]
@Julievrz can we forget the input placeholder ? We can't modify it without some maybe big reworks

**Comment by Julievrz** [comment]
"Search our catalog" is the input placeholder?

**Comment by NeOMakinG** [comment]
> "Search our catalog" is the input placeholder?

Yes

**Comment by Julievrz** [comment]
Ok thanks, I was not sure. As soon as the search bar stays, I don't think it is a big deal if we remove the input placeholder... However, I don't understand why we need the placeholder input to "know the context he's in" as it is always the same wording, in all cases (whether it is an empty category, or if there are no matching products). But it is probably more complicated than that.

**Comment by Julievrz** [comment]
However I'm not sure I'm the one who should approve this, so I'll let @LouiseBonnard have the final word. :)

**Comment by NeOMakinG** [comment]
Mmmh, you got a point, as the wording doesn't change, maybe we can do it, I need to find where the search bar input is, do you've an idea @Hlavtox ?

**Comment by Hlavtox** [comment]
@NeOMakinG It's generated by ps_searchbar module. If I was the boss, I would do it like this. 🚀

**Search - nothing found**
{l s='No matches were found for your search' d='Shop.Theme.Global'}
{l s='Please try other keywords to describe what you are searching for.' d='Shop.Theme.Global'}
and Search bar


**Empty product list**
{l s='No products available yet' d='Shop.Theme.Global'}
{l s='Stay tuned! More products will be shown here as they are added. Try to search our catalog.' d='Shop.Theme.Global'}
and Search bar


**default 404 page**
{l s='Nothing was found here' d='Shop.Theme.Global'}
{l s='Try to use the search to find what you need.' d='Shop.Theme.Global'}
and Search bar


I would leave it alone and just change the two texts, easiest solution. _Search our catalog_ is perfectly fine wording for all cases.

**Comment by NeOMakinG** [comment]
I agree with @Hlavtox on this, the last wording you told me to change is the 404 page, and the generic wording looks not appropriate, wdyt @Julievrz

**Comment by Julievrz** [comment]
What I don't understand is that when we have 404 pages, this wording does not appear. At least when I tried to reproduce it, by modifying the URL it didn't redirect me to a 404 page with this wording. If nothing was found, isn't it because the page is empty? Why does the generic wording does not apply in your opinion?

I agree with adding another wording, I just want to understand. 😄

**Comment by Hlavtox** [comment]
@Julievrz I changed the wording in my post, maybe we can include it in @NeOMakinG 's PR if you approve 😄

**Comment by Julievrz** [comment]
Hi, I have summarized here the wording I have in mind so that it is clearer. I have taken into account your suggestion concerning the 404 pages @Hlavtox.  I don't think we should get rid of the placeholder input as it is the only wording that does not change. 

![image](https://user-images.githubusercontent.com/70583503/105336624-c40ab900-5bd9-11eb-9dfa-ed9e39c6783d.png)

**Comment by Hlavtox** [comment]
@Julievrz This is perfection! 🚀

**Comment by Julievrz** [comment]
I'm glad that you like it! 😃
