### ISSUE TITLE
dashactivity slow and config value not used

### ISSUE THREAD

**Issue by ckubitza** [PrestaShop/PrestaShop#15128]
**Describe the bug**
Module "dashactivity" is very slow with lots of old connection data and is also not correctly using a config value.

**To Reproduce**
Have a shop with e.g. 500k entries in ps_connections and 65k entries in ps_guest. Open admin dashboard in browser, the dashboard panels take long time to show its contents (here it takes more than 30 seconds).
Also, when setting a different config value for visitors-online, the result is always the same.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in PrestaShop/dashactivity#15
