### ISSUE TITLE
unable to reset modules in module manager

### ISSUE THREAD

**Issue by LINUX3932** [PrestaShop/PrestaShop#15122]
Resetting any module using the **module manager** gives an error:

> Error! Could not perform action reset for module undefined

Disable/enable module works. RESET fails.

**Debug mode info**
AJAX **RESET module** request results in 404 error. url: `/index.php/improve/modules/manage/action/reset/welcome?`
AJAX **DISABLE module** results in 200 success. url: `/index.php/improve/modules/manage/action/disable/welcome?`

**Additional infomation**
PrestaShop version: 1.7.6.0 
Server information Linux #46-Ubuntu SMP  x86_64
Server software version: nginx/1.14.0
PHP version: 7.1.30-1+ubuntu18.04.1+deb.sury.org+1
Memory limit: 256M
Max execution time: 360
Upload Max File size: 100M
MySQL version: 10.1.41-MariaDB-0ubuntu0.18.04.1
MySQL server: 127.0.0.1
MySQL engine: InnoDB
MySQL driver: DbPDO

**Comment by mariem-abid** [comment]
Hi @LisaB123,

Could you please try to disable the Welcome module and check.

**Comment by LINUX3932** [comment]
Disable module and attempt reset - fail.
Uninstall module, reinstall module and attempt reset - fail

Issue applies to all modules.

**Comment by mariem-abid** [comment]
@LisaB123, Could you please rename the folder modules/welcome to modules/welcomeOLD and feedback?

**Comment by LINUX3932** [comment]
renamed welcome to welcomeOLD = module is no longer visible in BO>Module Manager, AND not searchable in BO>Module Catalogue.

Test same as above with **paypal** module.

I assume a module with a renamed directory is not available for installation from catalogue because the uninstall script was not executed.

**Comment by mariem-abid** [comment]
@LisaB123, Have you made an upgrade?

**Comment by LINUX3932** [comment]
@mariem-abid  No, it is a fresh install.

Is anyone else having this problem?

If not I will look into any variables unique to the installation such as the nginx config, cloudflare settings.

**Comment by LINUX3932** [comment]
Rewrote the nginx config using:
https://github.com/MattLoyeD/Prestashop-Nginx/blob/master/prestashop-nginx.conf as a basis. 

It was an nginx config issue after all. Now working - thanks for your help.

**Comment by khouloudbelguith** [comment]
@LisaB123, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
