### ISSUE TITLE
VAT not being added to EU customers/private persons

### ISSUE THREAD

**Issue by gorkij77** [PrestaShop/PrestaShop#15129]
**Describe the bug**
Customer from the UK purchases item from my store in Sweden. No VAT-number, since I only sell to individuals, not companies. Item is set to 25% VAT, standard swedish VAT per the pricing tab. VAT is not applied as it should be on EU customers.

**To Reproduce**
1. Create new account
2. Select product, add to basket. Shown with Swedish tax.
3. Go to checkout, fill in adress, here to United Kingdom
4. Go to payment, tax is gone?
5. Check any products in listing, all are now listed without tax for this customer.

Now, this is pretty bad. Mind pointing to whatever I might have missed? Because losing tax means losing income.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.9

**Comment by mariem-abid** [comment]
Hi @gorkij77,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1TtGp5IGW3ZitAPDOHuF_VA3MEURSYEiO/view

Thanks for check and feedback.

**Comment by gorkij77** [comment]
Hi @mariem-abid,

Interesting. You created a new rule specifically for the UK, and set that to a specific ware. 

I already have wares set with the basic 25% Swedish VAT that should be paid as per international EU customers - what am I missing and where should I start searching then?

What can I supply you with to backtrack this issue?

**Comment by gorkij77** [comment]
Just as a curiosity - am I to understand that if I want this to work proper and as legally intended, I'll have to add EVERY EU country under the normal swedish tax rule?

As per the below image?

![taxrules-se25and-uk](https://user-images.githubusercontent.com/42741897/63182171-332dc680-c052-11e9-8d8d-2851acad2220.JPG)

**Comment by gorkij77** [comment]
Well, I hacked this by adding every country in the EU with a swedish tax set, then changed 4000 wares to use the new tax groups for 6% and 25%. Consider it closed, I guess this is one of these "intuitive" thingies users are supposed to know.
