### ISSUE TITLE
White page after close import pop-up

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#15120]
**Describe the bug**
After import run, and click close import pop-up process, the page doesn´t return to import page, instead shows a clean page

**To Reproduce**
1. Go to Advance parms ->import -> 
2. Click on import anything you want (products, categories, etc)
3. Do the import

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6 (after 1-click upgrade from 1.7.5)
PHP version: 7

**Comment by Borgas** [comment]
I delete manully the folder at cpanel of var/cache/prod

Seems to be ok

**Comment by mariem-abid** [comment]
Hi @Borgas,

I close the ticket, feel free to open a new one when needed.
