### ISSUE TITLE
Filters should work on specific brand/manufacturer pages

### ISSUE THREAD

**Issue by Seeebastian** [PrestaShop/PrestaShop#15137]
#### Is your feature request related to a problem?

Now, in the Prestashop you can filter by brand but when you want to use filter on specific brand or manufacturer page there is no such possibility. I think it's a basic case to have faceted navigation working on the every important page of the shop. 

The same goes for other pages:
`best-sales`, `manufacturer`, `new-products`, `prices-drop`, `search`, `supplier`

For years, product subpages displaying new products, with discounts, bestsellers only have the option of sorting (which also does not work well, bugs have been reported, such as this one https://github.com/PrestaShop/PrestaShop/issues/25309). 

#### Describe the solution you'd like

It would be great if Faceted Search also worked on these product subpages.

`some-domain.com/new-products`
`some-domain.com/prices-drop`
`some-domain.com/best-sales`

**Comment by Hlavtox** [comment]
@Seeebastian Would be a nice improvement. The same goes for other pages:
`best-sales, manufacturer, new-products, prices-drop, search, supplier`

But at first, let them fix it in the category. :-)

**Comment by Matt75** [comment]
Facetedsearch is only designed for category page initially and you could find advanced modules on marketplace to add support for others pages.
Initial goal was to demonstrate how to do with categories and let community to enhance it for others pages.

**Comment by Seeebastian** [comment]
I think that it's the basic functionality of the shop to have uniform filters on every page. Mixing other modules in this area is not a good idea (functionality, performance and seo cases). Moreover, I've never seen the module on the marketplace that extends the original faceted search module. If there is such a module (that only extends the original module) I will be interested in the purchase. 

We are in 2019, so easy and uniform (technically the same for each section/page) filtering should be ensured in a standard. Especially that, as we can see, faceted navigation is a little problematic module. Paid modules may be useful when you want to filter in a less standard way, for instance when you want to build a configurator or something similar. But in my opinion, the standard should be adapted to 2019. Finally, filtering is the core functionality and community modules are not always updated on time. For this reason, it would be very problematic to be up to date with ps version.

**Comment by Matt75** [comment]
You can find modules on marketplace to replace and enhance facetedsearch.
This native module is a first implementation to demonstrate how to use the system on category pages.
For others pages, community developers can do their own implementation to manage more listing pages.
So you can find paid community module who replace native facetedsearch by a more advanced.
Community can contribute to improve this native module on Github for others pages.

By the way, you can have best experience with ElasticSearch or external tools like Algolia and similars.
Rely on MySQL for search is not an efficient way.
This module work on shared hosting with minimal configuration but if it’s not your case, maybe you have to think about use a better search engine.

**Comment by Hlavtox** [comment]
@Matt75

No need for a separate search module. We have 15000 products in our store and layered search and faceted search are super fast and reliable. It's more integrated than any 3rd party module will ever be and  loads fast.

In 1.6, I was experimenting with Advanced Search 4. Most selling module on PS Addons, never seen a bigger shit. Went back to Layered navigation and was happy. :)

Guys, just make the faceted search as great as it was on 1.6, please!

**Comment by Seeebastian** [comment]
@Matt75 
I understand the reasons of your approach but I agree with Hlavtox that standard is good enough, more integrated than 3rd party modules and should be ensured for all pages. Of course, Algolia or Elastic Search are additional interesting extensions. It is good for Prestashop ecosystem, but there should be a standard that is supported and easily maintained.

> Community can contribute to improve this native module on Github for others pages.

Hence, there is a feature request directed to core developers and generally, to community contributors. I do not know the exact process of making decisions about feature requests future. Is this an arbitrary decision of one person? Or of a core team? How does it work?

**Comment by Matt75** [comment]
You really need to test others alternative, there are so much faster et reliable than a module based on MySQL for this needs. You can try a demonstration for free for somes, can be interessting for test and compare.

I think this will not being implemented in facetedsearch native module because this as to be documented, specified, implemented, tested... and there are so many more critical work to do.

So I think you can wait it for months or years for the native module. Priority is to make it great again for category pages.

Some search engine are not available on PrestaShop Marketplace, but a module is sometime delivered by external services. Advanced Search 4 is based on MySQL so not a good alternative I think.

**Comment by Seeebastian** [comment]
@Matt75 
We know that alternatives exist, but I just mentioned that the standard should be adapted to 2019. The faceted search has some advantages. But if there is a problem to make filters great again, I understand that there is no hope to extend it in such a way. Especially, in the closest future.

**Comment by matks** [comment]
I do not know the exact process of making decisions about feature requests future. Is this an arbitrary decision of one person? Or of a core team? How does it work?

This is the responsibility of the Product Team whose members are @marionf, @colinegin, @samuel-pires and @MatShir 😉they listen to all our channels for user feedback (github, gitter, the forum, feedback.prestashop.com and all the conversations they have with merchants/developers/agencies/partners) and try to aggregate it all into the roadmap

EDIT: I put the `waiting for PM` label on this ticket so that they see the issue in their queue

**Comment by Seeebastian** [comment]
@matks 
Thanks for detailed information ;)

**Comment by ghost** [comment]
My customer (non-tech) was supprised and confused at the same time w.t.h. he can't use search by size when he is in Manufacturer/Best sellers/New products/Search pages... Its non-uniform approach and yes - that feature should be implemented in faceted search.

Faceted search module expectation are high as same as our customers from us...

Im still about make a fund for that project...
https://community.joomla.org/sponsorship-campaigns.html

**Comment by ttoine** [comment]
well, maybe your customer could provide money for this feature, instead of thinking that other will do it for them? feel me to DM me on Twitter (ttoine), I would enjoy to discuss opportunities with you and your customer in a video chat.

**Comment by ghost** [comment]
Make a crowdfund like https://www.indiegogo.com/projects/elasticsearch-module-for-thirty-bees and then we will talk about "providing money" and module goals & roadmap. Im waiting for that! Just "shut up and take my money!"

Let's say Prestashop is World of Tanks. Both are Free for Play. In WoT there was many plugins (mods). The better ones in next patches were incorporated into WoT core features providing uniform UI/UX for software users. Core features are also more stable and reliable than third-party plugins provided by the community. 

Let's be clear. You are doing a lot of good work but expectations from the customers are higher than even before...

**Comment by ttoine** [comment]
Of course, the more is done well, the more people will expect. This is challenging.

Unfortunately this is not only a problem of money (that will of course help). This is also about finding people with skills and time for code review.

Please, keep in mind that PrestaShop is a very big open source project, with big challenges and priorities in mind. It's not just about keeping some legacy code up to date or merging pull request without review and QA check.

**Comment by roscopecoltran** [comment]
https://github.com/appbaseio/reactivesearch

Could help a lot if elasticsearch is connected to Prestashop AP...

**Comment by matks** [comment]
> https://github.com/appbaseio/reactivesearch
> 
> Could help a lot if elasticsearch is connected to Prestashop AP...

👍 

Sad thought: we will never be able to do this in the core 😢because we want the software to remain an easy setup: PHP + web server + mysql.

However this could become a nice module 😉if you feel like giving it a try. There are already a few modules on Addons marketplace (https://addons.prestashop.com/fr/recherche?search_query=elasticsearch) leveraging the capabilities of elasticsearch

**Comment by ghost** [comment]
@PierreRambaud did a impresive work with Faceted Search module in last months and few last weeks. Im very thankful about it! I repeat my request timidly to include functional pages such as search results, specials, new produts to module :)

**Comment by marionf** [comment]
Hello guys,

Yes, a lot of work has been done to improve faceted search these last months.
We are currently focused on the 1.7.7
So this improvement will not be integrated right now, I hope we could rework on facetedsearch after the 1.7.7

**Comment by ghost** [comment]
Yes @marionf - 🔥🔥🔥 in module was extinguished for a while ;) Thanks! Let's focus on other improvements! 💪

**Comment by PierreRambaud** [comment]
It could be awesome if we plan to integrate Elastic in the faceted search module :roll_eyes: (Interface are ready for it at least :sweat_smile:)

**Comment by ghost** [comment]
> It could be awesome if we plan to integrate Elastic in the faceted search module 🙄 (Interface are ready for it at least 😅)

I've heard PrestaRocket built a faceted search module integrating Algolia, works pretty well and I believe they are thinking about making it Open Source.

Would that be interesting or it's really different with Elastic?

**Comment by ttoine** [comment]
With Elastic it would be possible to stay 100% open source and to manage the data without a third party service. (well, of course, one would need the knowledge to run and maintain an Elastic instance on their infra)

**Comment by matks** [comment]
> > It could be awesome if we plan to integrate Elastic in the faceted search module 🙄 (Interface are ready for it at least 😅)
> 
> I've heard PrestaRocket built a faceted search module integrating Algolia, works pretty well and I believe they are thinking about making it Open Source.
> 
> Would that be interesting or it's really different with Elastic?

Same issue: it means to use it you need to subscribe to Algolia, and not everybody can do that. So this would be an option, enabled only for the people willing to use it. I dont think we should spend time working on a topic that has such strict requirements 😐as it means focusing on only a fraction of users.

**Comment by PierreRambaud** [comment]
:+1: @ttoine  And you can do a lot of things with Elastic.
And as @matks it must depends on how many people need this feature. (Even if it's cool to implement this kind of feature :D)

**Comment by ttoine** [comment]
That would make a very attractive module, and it would make PrestaShop to compete with the Magento 2 requirement of Elastic.

BTW, to take another example, it's like using Google Analytics (a third party service) or run a Matomo instance (open source, you own the data). This way, no need of a third party cookie banner, this has actually a lot of value.

**Comment by ghost** [comment]
Bump. Allow use faceted search module in Manufacturer, Supplier, Search results pages would be very nice addition to every store features. Consider that. Thanks! :)

**Comment by ajmnz** [comment]
Hey, any news on this?

**Comment by Renrhaf** [comment]
👍  for such a feature 
Do you have any module you can recommend that may fill this need in the meantime ?

**Comment by Hlavtox** [comment]
## My notes on this:
- We want faceted search to work on other controllers than only category - manufacturer, supplier, new-products, best-ales, prices-drop and search
- I removed a simple condition and that made faceted search popup and work on other pages. It pops up with a filter set to PS_HOME_CATEGORY as default. This needs to be changed, everything other works!!!

![works](https://user-images.githubusercontent.com/6097524/127167833-ae115d1b-41f2-405c-84eb-297763b7f5c5.JPG)
  


## Places to implement
- We need to configure which filters appear on these new pages. We will configure it the same way as now, but user would be able to check which pages this filter should be used on. We can maybe even enable him to enter a custom listing controller. Controller column will be added to this database and 'category' will be used for current filters.
- src/Hook/ProductSearch.php - Removing of the condition on id category. Instead, we will check if the query comes from a controller for which we have a template prepared, or category. Or just enable it for all controllers.
- Modify src/Filters/Converter.php to load a proper filters for current detected controller. Only a slight modification in a query is needed.
- Modify category filter block to show right categories always.
- Hardcode some settings in case of these other pages.

## There must hardcoded settings for these pages.
- Category depth - 1
- Root category - PS_HOME_CATEGORY
- Show products from subcategories - YES
- Show products only from default category - NO

**Comment by Hlavtox** [comment]
I did it, can you test guys? @Renrhaf @PrestaShark @Seeebastian 🚀

**Comment by ftardio** [comment]
> I did it, can you test guys? @Renrhaf @PrestaShark @Seeebastian 🚀

I tried it. Unfortunately , it's not working properly. For example, if you go to "prices-drop" page, you get products without discount, even if you are not assigning any rule to this page. If you deactivate module, it shows only products with discounts, but if you activate it, you get wrong products filtering.

**Comment by Hlavtox** [comment]
@ftardio Yes, I didn't realize it will take some more work, we need to build proper SQL queries for it to work. :(

**Comment by ftardio** [comment]
It can be very hard work. For example, at "prices-drop" page, if you filter by categories or attributes, keep in mind you have to filter products having the selected category or attribute value, but also having discounts. And in every single page is different (for example, in "new-products" page you have to keep in mind creation dates, and so...

**Comment by Hlavtox** [comment]
@ftardio Yeah, we would need to replicate Product::getPricesDrop, Product::getNewProducts, ProductSale::getBestSales and search somehow. Will need some help from @PierreRambaud :D 🥺

**Comment by Dan-Orchard** [comment]
Still nothing?

You must note that there are no modules on addons for this functionality

`Facetedsearch is only designed for category page initially and you could find advanced modules on marketplace to add support for others pages.`

I still cannot believe this isn't sorted in core yet.

**Comment by Fourmarketing360** [comment]
Still not sorted in PS 8

**Comment by Hlavtox** [comment]
@Fourmarketing360 Already done a long time ago, update your faceted search module.

**Comment by michalidesko** [comment]
I am currently working with the experimental faceted search feature on search results. While the filtering works correctly and products are displayed, I’ve noticed that when this feature is enabled, the faceted search module takes over product sorting based on relevance. However, the relevance of faceted search is not as accurate as PrestaShop’s native search.

Is there a way to combine PrestaShop’s better search relevance with the faceted search filters? Or is this the intended behavior, and I might have something misconfigured that causes the sorting to behave this way?

For reference, I am using PrestaShop 8.1.7 and Faceted Search v3.16.1.

Any suggestions would be appreciated. Thank you!

**Comment by Hlavtox** [comment]
@michalidesko Upgrade to https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v4.0.0 and use this modified version of src/Adapter/MySQL.php file.

[MySQL.zip](https://github.com/user-attachments/files/18915171/MySQL.zip) (can't upload a PHP directly)

Then the order should work.
I did not commit this yet, because it was a quick hacky solution, but works.

**Comment by michalidesko** [comment]
Thanks for the quick response.

I tried both the module and uploaded the modified MySQL.php file, but without success. The only difference I noticed is in this part:


```
if ($orderField) {
    // Do not modify new order field in some cases at all
    if (strpos($orderField, 'FIELD(p.id_product') !== false) {
        $query .= ' ORDER BY ' . $orderField . ' ';
    } else {
        $query .= ' ORDER BY ' . $orderField . ' ' . strtoupper($this->getOrderDirection());
        if ($orderField !== 'p.id_product') {
            $query .= ', p.id_product DESC';
        }
    }
}
```

And this addition:
```
// Custom sort by IDs on search page
if ($orderField == 'p.position' && !empty($this->getInitialPopulation()->getFilters()['id_product']['='][0])) {
    $orderField = "FIELD(p.id_product," . implode(',', $this->getInitialPopulation()->getFilters()['id_product']['='][0]) . ")";
}
```
However, the products are still not sorted as accurately as in PrestaShop’s native search. Just in case, I also ran PrestaShop cron jobs and cleared the cache, but it didn’t help.

Any other ideas?

**Comment by Hlavtox** [comment]
@michalidesko That's weird, they should be. If you are using the latest version AND my modification, it should work. :(

**Comment by michalidesko** [comment]
Sorry! It was my mistake – after uninstalling and reinstalling the module, it works as expected. Thanks again for your help! 
EDIT: NO. Not my mystake :D It seems the issue occurs when the option "Display unavailable, out-of-stock items last" is enabled in the Faceted Search settings. When this option is activated, the hack doesn’t work as expected.

**Comment by Hlavtox** [comment]
Ha 😄😄, yes, I don't use this option. It would be good to finish it, but I don't have the best feeling of just passing a huge number of IDs there. It doesn't slow it down, but who knows what it would do if it found 10000 products.
