### ISSUE TITLE
Cannot translate modules when using a theme other than classic

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#15133]
**Describe the bug**
When using a theme other than classic, you cannot translate modules

**To Reproduce**
1. Activate a theme other than classic
2. Try to translate some installed module (a native one for example)
3. You get a domain tree, then the error message "Could not crawl for translation files: The "/path/to/prestashop/var/cache/prod/themes/TEMPLATE/translations" directory does not exist."
4. Translations don't appear afterwards

**Screenshots**
https://drive.google.com/file/d/1OvlF41Oo-6BhzIx6e9ULAKIk2CI7VTSE/view
<img width="1120" alt="Screenshot 2019-08-16 at 16 27 10" src="https://user-images.githubusercontent.com/1009343/63174666-bcd59800-c042-11e9-8d0a-c54219d3d639.png">

**Additional information**
PrestaShop version: 1.7.6.x
PHP version: 7.1

**Comment by eternoendless** [comment]
Workaround (not verified, but I think it may work): go to the theme translations before translating the module.

**Comment by Hlavtox** [comment]
@eternoendless The same in my case. Can't translate any module.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15139

**Comment by pierreloicq** [comment]
Here is the topic of interest : 
https://github.com/PrestaShop/PrestaShop/issues/15268
