### ISSUE TITLE
back office goes blank after disabling debug mode

### ISSUE THREAD

**Issue by LordMarZ** [PrestaShop/PrestaShop#15146]
hello guys, i work with a 1.7.4.2 version of Prestashop, and it is happening to me that everytime i disable the Debug Mode, the back office goes blank and cant enter.

the server report is this:

---
[17-Aug-2019 17:02:27 America/Montevideo] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AdminController" from the global namespace.
Did you forget a "use" statement? in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php:65

Stack trace:
#0 /home/darksidebroscom/public_html/src/PrestaShopBundle/EventListener/UserLocaleListener.php(39): PrestaShop\PrestaShop\Adapter\LegacyContext-&gt;getContext()
#1 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1403): PrestaShopBundle\EventListener\UserLocaleListener-&gt;__construct(Object(PrestaShop\PrestaShop\Adapter\LegacyContext))
#2 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1003): ContainerX5me8mb\appProdProjectContainer-&gt;getPrestashop_UserLocale_ListenerService()
#3 /home/darksidebroscom/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerX5me8mb\appProdProjectContainer-&gt;ContainerX5me8mb\{closure}()
#4 /home/ in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php on line 65
[17-Aug-2019 23:33:25 America/Montevideo] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AdminController" from the global namespace.
Did you forget a "use" statement? in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php:65

Stack trace:
#0 /home/darksidebroscom/public_html/src/PrestaShopBundle/EventListener/UserLocaleListener.php(39): PrestaShop\PrestaShop\Adapter\LegacyContext-&gt;getContext()
#1 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1403): PrestaShopBundle\EventListener\UserLocaleListener-&gt;__construct(Object(PrestaShop\PrestaShop\Adapter\LegacyContext))
#2 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1003): ContainerX5me8mb\appProdProjectContainer-&gt;getPrestashop_UserLocale_ListenerService()
#3 /home/darksidebroscom/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerX5me8mb\appProdProjectContainer-&gt;ContainerX5me8mb\{closure}()
#4 /home/ in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php on line 65
[17-Aug-2019 23:34:31 America/Montevideo] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AdminController" from the global namespace.
Did you forget a "use" statement? in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php:65

Stack trace:
#0 /home/darksidebroscom/public_html/src/PrestaShopBundle/EventListener/UserLocaleListener.php(39): PrestaShop\PrestaShop\Adapter\LegacyContext-&gt;getContext()
#1 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1403): PrestaShopBundle\EventListener\UserLocaleListener-&gt;__construct(Object(PrestaShop\PrestaShop\Adapter\LegacyContext))
#2 /home/darksidebroscom/public_html/var/cache/prod/ContainerX5me8mb/appProdProjectContainer.php(1003): ContainerX5me8mb\appProdProjectContainer-&gt;getPrestashop_UserLocale_ListenerService()
#3 /home/darksidebroscom/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerX5me8mb\appProdProjectContainer-&gt;ContainerX5me8mb\{closure}()
#4 /home/ in /home/darksidebroscom/public_html/src/Adapter/LegacyContext.php on line 65
---

what can i do to fix this?
i want to migrate to 1.7.6 but the migrator module need to disable the debug mode... and i cant

thanks!

**Comment by khouloudbelguith** [comment]
Hi @LordMarZ,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by LordMarZ** [comment]
omfg! you solved it!

i cant believe now is working!
thanks a lot @khouloudbelguith you are the man of the hour!

cheers

**Comment by khouloudbelguith** [comment]
@LordMarZ, thanks for your feedback.
You are welcome.
Feel free to open a new one when needed.

Thanks!
