### ISSUE TITLE
Unable to edit category

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#15140]
**Describe the bug**
I am unable to edit some categories in my multistore shop.
There are no PHP error logs. Also Symfony debugger does not display any message.

**Screenshots**
When I click save an unexpected error occurs:
![image](https://user-images.githubusercontent.com/3767861/63197997-b0b8fd00-c079-11e9-9ba8-8104e9c6dfe3.png)

Problem might be in parent category field:
- root category radio is disabled
- no parent category is checked
- some categories are not displayed in this tree
![image](https://user-images.githubusercontent.com/3767861/63198091-eb229a00-c079-11e9-9680-5a0d9131417e.png)

**Additional information**
PrestaShop version: .7.6.0
PHP version: 7.2

**Comment by nulledcc** [comment]
I have same Issue but I am selecting root Caegory

**Comment by nulledcc** [comment]
![image](https://user-images.githubusercontent.com/9316816/63223771-a27af600-c1cb-11e9-97c6-b71e1863f61e.png)
This was my issue friendly URL does not save when its is not english letters

**Comment by khouloudbelguith** [comment]
Hi @Flower7C3,

What s the exact language did you use in your BO?

Thanks!

**Comment by Flower7C3** [comment]
Hi @khouloudbelguith,
I use Polish version. The message _Nieoczekiwany błąd_ on my screenshot means _Unexpected error_.

I was looking for this in source code and I find out, that any CategoryConstraintException does not show user friendly message.

**Comment by khouloudbelguith** [comment]
@Flower7C3, in the BO => Shop Parameters => Traffic & SEO page => Accented URL is enabled?
 
![image](https://user-images.githubusercontent.com/16067358/63427884-1c022680-c40e-11e9-81b0-54d77b8f0b55.png)
If not, thanks to enable it, check & feedback.

**Comment by Flower7C3** [comment]
@khouloudbelguith I have enabled this option, but it does not make any change. Now when I edit category it gives me error code 6.

**Comment by khouloudbelguith** [comment]
@Flower7C3, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Flower7C3,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
