### ISSUE TITLE
Reorder products dont work properly

### ISSUE THREAD

**Issue by fernandoherlo** [PrestaShop/PrestaShop#15143]
**Describe the bug**
Sometimes when reorder the products, the order no save correctly

**To Reproduce**
1. Go to http://demo.prestashop.com/#/en/back -> Catalog -> Products
2. Click on Filter by category -> Accesories
3. Click Reorder -> drag and drop products

**Additional information**
PrestaShop version: 1.7.6

**Comment by fernandoherlo** [comment]
I have tested it more, the error occurs only with Chrome, not in Firefox, Safari.

**Comment by matks** [comment]
> I have tested it more, the error occurs only with Chrome, not in Firefox, Safari.

🤔 interesting, thanks for the extensive feedback

Chrome, why are you doing again ? 😄

**Comment by khouloudbelguith** [comment]
Hi @fernandoherlo,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14616

**Comment by fernandoherlo** [comment]
Thanks
