### ISSUE TITLE
Import csv - URL re-written by import (not csv file)

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#15141]
Import records, without re-write in csv file
The value re-write from prestashop is the not re-written in second import, it assumes old text for the ID

**To Reproduce**
Import file csv without values for re-written
Prestashop will generate automatic
Import another file but with different records ex: product name, prices etc (but with same id from last import)
It will not re-write the new text, it keeps the old

You need to click reiniciate url to take effect, product by product (one by one)

![a](https://user-images.githubusercontent.com/54105234/63202677-d1398500-c082-11e9-8cb9-498bab0748fb.JPG)

Prestashop 1.7.6
Php 7.0
Multi-language pt en es activated
Currency - EUR only

![Capturar](https://user-images.githubusercontent.com/54105234/63202692-db5b8380-c082-11e9-8a01-298a0c90dc8a.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Borgas,

It is the same behavior when we try to edit a product manually.
We should to res the Friendly URL manually.
I attached a screen record
https://drive.google.com/file/d/1nzutCWk_YS6u_gY66CZG2ICkthoL0duf/view
Thanks to check & feedback

**Comment by Borgas** [comment]
Hi @khouloudbelguith 
Yes thank you, i know we can solve restarting.
But doing in 1 product, will do in all products?

**Comment by khouloudbelguith** [comment]
@Borgas, thanks to enable the "Force update of friendly URL" option in the BO => Shop Parameters => Product Settings, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/63260044-dd3a6800-c277-11e9-9132-62f1ac683106.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Borgas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
