### ISSUE TITLE
Bulk invoice generating -  Price specification not found for currency - fatal error -  1.7.6

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15144]
When generating invoices in bulk. I get a fatal error when the currency is different than EUR.

![Screenshot 2019-08-17 at 20 23 49](https://user-images.githubusercontent.com/46492443/63216438-14503280-c12d-11e9-9024-e3cc58bc606b.png)

I tried turning on-off currency. Checked the ps_products_supplier in DB ( read about this in a different post, but this is empty ) I also already changed the number of decimals to 2.

Not sure if this has anything do with the currency problems but I noticed a difference in format when checking the log in debug mode "PLN" and "PLN"" : see image

![Screenshot 2019-08-17 at 20 44 49](https://user-images.githubusercontent.com/46492443/63216645-3d25f700-c130-11e9-96a3-75c87da3a22c.png)

**Comment by khouloudbelguith** [comment]
Hi @01park,

>I tried turning on-off currency. Checked the ps_products_supplier in DB

This issue occurs only when we import products.
>Not sure if this has anything do with the currency problems but I noticed a difference in format when checking the log in debug mode "PLN" and "PLN"" : see image

You have a double quote in the same sentence 
![image](https://user-images.githubusercontent.com/16067358/63259131-7d42c200-c275-11e9-8b83-556325815ca4.png)

>When generating invoices in bulk. I get a fatal error when the currency is different than EUR.

How did you generate the invoices? from the invoices page? By order status?

Thanks!

**Comment by 01park** [comment]
Hi @khouloudbelguith 

When I generate an invoice from the order page, it works fine ( 1 by 1)

But when I do BULK, I do it on this page.
<img width="1702" alt="Screenshot 2019-08-19 at 12 16 04" src="https://user-images.githubusercontent.com/46492443/63261337-2809af00-c27b-11e9-8be5-032c991b0971.png">

Does this double quote need to be removed?

**Comment by khouloudbelguith** [comment]
@01park,

>Does this double quote need to be removed?

No, it is a debug message.

This is a fresh installation PS1.7.6.0 or after an upgrade from a previous version?

Thanks!

**Comment by 01park** [comment]
@khouloudbelguith 

Its an update from 1.7.5.2 ( multistore ). 

Not sure if it makes a difference, but I did not upgrade the classic theme files. This option was disabled.

**Comment by khouloudbelguith** [comment]
@01park, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.0.
Steps to reproduce the issue:
1. PS1.7.6.0 with multi-currencies for example EUR & GBP
![image](https://user-images.githubusercontent.com/16067358/63264072-18419900-c282-11e9-9e2d-8d9ef64f620d.png)
2. Enable Multistore
3. Create a second shop
4. Set the "Default currency" for the first shop `EUR`
5. Set the "Default currency" for the second shop `GBP`
6. `EUR` is associated with the first shop only
![image](https://user-images.githubusercontent.com/16067358/63264305-a0c03980-c282-11e9-99f2-ed62cb495fbf.png)
7. `GBP` is associated with the second shop only
![image](https://user-images.githubusercontent.com/16067358/63264322-ac136500-c282-11e9-949d-1035acbad3da.png)
8. Create some orders in the first & second shop
9. Try to generate invoices from the BO => Orders page for those orders in the different shops.
10. Navigate to the BO => Orders => Invoices page => All shops is selected
11. Error:
11.1. Click on "Generate PDF file by date" => see error
11.2. Select a status "Payment accepted" & click on "Generate PDF file by status" => see error
![image](https://user-images.githubusercontent.com/16067358/63264614-6dca7580-c283-11e9-856f-9da6babbe3e2.png)

https://drive.google.com/file/d/1EPF-5Kds5wHFiWDGfIFFCRr1nNrbAoAv/view

With PS1.7.5.2 => OK

**Comment by 01park** [comment]
@khouloudbelguith 

Good work!
