### ISSUE TITLE
Edit window for product images in BO does not appear.

### ISSUE THREAD

**Issue by kkasztann** [PrestaShop/PrestaShop#15153]
**Describe the bug**
I can't edit products images, because, edit window for products images in BO does not appear after click on image.

**To Reproduce**
1. Go to BO ->Product ->
2. Click on Product image

**Screenshots**
![ss1](https://user-images.githubusercontent.com/33009149/63262110-6a37ee00-c285-11e9-94b7-3e5dcfcbc7c4.png)
![ss2](https://user-images.githubusercontent.com/33009149/63262113-6a37ee00-c285-11e9-9c37-3255c291e8f5.png)
![ss4](https://user-images.githubusercontent.com/33009149/63262115-6ad08480-c285-11e9-853f-d4c2f3bb8084.png)

Console:

![ss3](https://user-images.githubusercontent.com/33009149/63262112-6a37ee00-c285-11e9-9dfe-065c4c645109.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.31

**Comment by khouloudbelguith** [comment]
Hi @kkasztann,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/11IgssWaKHxZqY872AJf4Txq_r86zsI50/view
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. Click on the product's image
6. wait for an error, you should see red request information in Network tab (error 500 in your case)
7. click on it, you should see the error message in "Response" or "Preview" tab 

Thanks!

**Comment by kkasztann** [comment]
Hi @khouloudbelguith 

**Headers:** 
![ss1](https://user-images.githubusercontent.com/33009149/63267609-bdfd0400-c292-11e9-9004-dfd38f2fdc45.png)
![ss2](https://user-images.githubusercontent.com/33009149/63267611-bdfd0400-c292-11e9-88ca-ab98dcc3f65f.png)

**Preview:** 
![ss3](https://user-images.githubusercontent.com/33009149/63269013-ba1eb100-c295-11e9-997f-9120ef98dc3f.png)
![ss4](https://user-images.githubusercontent.com/33009149/63269019-bd19a180-c295-11e9-97ea-ad779a8ab9bf.png)
![ss5](https://user-images.githubusercontent.com/33009149/63269025-bf7bfb80-c295-11e9-9aec-1979029f8e02.png)
![ss6](https://user-images.githubusercontent.com/33009149/63269029-c0ad2880-c295-11e9-8b9c-06e54bc358cc.png)
![ss7](https://user-images.githubusercontent.com/33009149/63269031-c30f8280-c295-11e9-86db-9675281a3ab8.png)
![ss8](https://user-images.githubusercontent.com/33009149/63269036-c4d94600-c295-11e9-94e2-0acdf0f359f9.png)
![ss9](https://user-images.githubusercontent.com/33009149/63269042-c7d43680-c295-11e9-83ae-a87dcc438f71.png)
![ss10](https://user-images.githubusercontent.com/33009149/63269045-c99dfa00-c295-11e9-960b-9d87fca90d84.png)
![ss11](https://user-images.githubusercontent.com/33009149/63269054-ce62ae00-c295-11e9-9ff0-80e3c84fce50.png)

**Comment by pitangaweb** [comment]
Same issue here.

- PS 1.7.6.0
- PHP 7.2.20


"Failed to load resource: the server responded with a status of 500 (Internal Server Error):
http://www.site.com/admin241hymz2r/index.php/sell/catalog/products/image/form/16?_token=43QZDjyHlokdypAaaJsIDiy4FoporGEP02ikUyHZy_o"



Symfony\Component\Form\Exception\InvalidArgumentException:
Could not load type "form": class does not exist.

  at vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php:86
  at Symfony\Component\Form\FormRegistry->getType('form')
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:74)
  at Symfony\Component\Form\FormFactory->createNamedBuilder('form_image', 'form', array('id' => 16, 'id_product' => '9', 'position' => '2', 'cover' => false, 'legend' => array('', ''), 'format' => 'jpg', 'base_image_url' => '/img/p/1/6/16'), array('csrf_protection' => false, 'data' => array('id' => 16, 'id_product' => '9', 'position' => '2', 'cover' => false, 'legend' => array('', ''), 'format' => 'jpg', 'base_image_url' => '/img/p/1/6/16')))
     (src/PrestaShopBundle/Controller/Admin/ProductImageController.php:133)
  at PrestaShopBundle\Controller\Admin\ProductImageController->formAction('16', object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin241hymz2r/index.php:88)

**Comment by khouloudbelguith** [comment]
@kkasztann, what is the exact type for those images?

Thanks!

**Comment by kkasztann** [comment]
@khouloudbelguith 

*.jpg

**Comment by khouloudbelguith** [comment]
@kkasztann, @pitangaweb this issue occurs with a Fresh install PS1.7.6.0 or after an upgrade from previous version PrestaShop?

Thanks!

**Comment by kkasztann** [comment]
@khouloudbelguith this issue occured to me with a fresh install PS 1.7.6.0

**Comment by pitangaweb** [comment]
Fresh install as well !

**Comment by khouloudbelguith** [comment]
@kkasztann, @pitangaweb did you installed any custom module before this issue occurs?

Thanks!

**Comment by kkasztann** [comment]
@khouloudbelguith to be honest I don't know when this issue appeared. But I installed just few modules related to delivery and payments.

**Comment by khouloudbelguith** [comment]
@kkasztann, could you please try to disable one by one & check if the issue occurs again.

Thanks!

**Comment by kkasztann** [comment]
@khouloudbelguith issue still occurs.

**Comment by khouloudbelguith** [comment]
@kkasztann, could you please navigate to the BO => Design => Image Settings page => click on the "Regenerate thumbnails" button, check & feedback.

**Comment by kkasztann** [comment]
@khouloudbelguith It was my first step before I open this issue. I regenerated thumbnails at this moment and as before it finish successful, but issue still occurs.

**Comment by khouloudbelguith** [comment]
@kkasztann, this product is created manually for the BO => Products page & uploaded from the import page?

Thanks!

**Comment by kkasztann** [comment]
@khouloudbelguith 

Yes, product was created manually.

**Comment by khouloudbelguith** [comment]
@kkasztann, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by kkasztann** [comment]
Hi @khouloudbelguith 
I sent access data to Your email.

**Comment by khouloudbelguith** [comment]
@kkasztann, I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@kkasztann, doing some tests.
I find this error
![image](https://user-images.githubusercontent.com/16067358/63705294-b99d9180-c824-11e9-8c80-dd5561dd8ac1.png)

It is related to your module provided by a theme.
Could you please try to use the classic theme, clear cache, check & feedback.

**Comment by kkasztann** [comment]
@khouloudbelguith thank you for your time :) 
The problem was something else, but after the upgrade from 1.7.6.0 to 1.7.6.1 the issue disappeared.

**Comment by khouloudbelguith** [comment]
@kkasztann, thanks for your feedback.
Feel free to open a new one when needed.

**Comment by Stolaweb** [comment]
The same problem

Can anyone solve this for me? I have the same problem. Pictures in product settings cannot be deleted and img options are not displayed. How to fix it? I have Prestashop 1.7.6.1. I can't make changes to product images. All I can do is remove the product and add it again.

screen product https://prnt.sc/ppnrk3

debug token: https://www.butiktest.hekko24.pl//fyxmmlllslsjlkivm/index.php/_profiler/31ea40?_token=ShlxDvDumvhPzaDY6qFN_kqY1ah2X2twskK_ePJfFTE

please help what to do

**Comment by khouloudbelguith** [comment]
@Stolaweb, it is a module issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Stolaweb** [comment]
Thank You but, how to check which module cause the problem? It could be the module delivered with the theme?

**Comment by khouloudbelguith** [comment]
@Stolaweb, you can follow these steps:

You need to enable debug mode in your store and debug request which is sent for product edition in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. edit product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Stolaweb** [comment]
I have theese: Is this a problem with theme module or prestashop module? I turned off all modules and change for classic theme and the problem still exist:

Symfony\Component\Form\Exception\
InvalidArgumentException
in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php (line 86)
            }            if (!$type) {                // Support fully-qualified class names                if (!class_exists($name)) {                    throw new InvalidArgumentException(sprintf('Could not load type "%s": class does not exist.', $name));                }                if (!is_subclass_of($name, 'Symfony\Component\Form\FormTypeInterface')) {                    throw new InvalidArgumentException(sprintf('Could not load type "%s": class does not implement "Symfony\Component\Form\FormTypeInterface".', $name));                }
FormRegistry->getType('form')
in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php (line 74)
        if (!\is_string($type)) {            throw new UnexpectedTypeException($type, 'string');        }        $type = $this->registry->getType($type);        $builder = $type->createBuilder($this, $name, $options);        // Explicitly call buildForm() in order to be able to override either        // createBuilder() or buildForm() in the resolved form type
FormFactory->createNamedBuilder('form_image', 'form', array('id' => 31, 'id_product' => '27', 'position' => '1', 'cover' => true, 'legend' => array(''), 'format' => 'jpg', 'base_image_url' => '/img/p/3/1/31'), array('csrf_protection' => false, 'data' => array('id' => 31, 'id_product' => '27', 'position' => '1', 'cover' => true, 'legend' => array(''), 'format' => 'jpg', 'base_image_url' => '/img/p/3/1/31')))
in src/PrestaShopBundle/Controller/Admin/ProductImageController.php (line 133)
            return new Response();        }        $image = $productAdapter->getImage((int)$idImage);        $form = $this->container->get('form.factory')->createNamedBuilder('form_image', 'form', $image, array('csrf_protection' => false))            ->add('legend', 'PrestaShopBundle\Form\Admin\Type\TranslateType', array(                'type' => 'Symfony\Component\Form\Extension\Core\Type\TextareaType',                'options' => array(),                'locales' => $locales,                'hideTabs' => true,
ProductImageController->formAction('31', object(Request))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
        $this->dispatcher->dispatch(KernelEvents::CONTROLLER_ARGUMENTS, $event);        $controller = $event->getController();        $arguments = $event->getArguments();        // call controller        $response = \call_user_func_array($controller, $arguments);        // view        if (!$response instanceof Response) {            $event = new GetResponseForControllerResultEvent($this, $request, $type, $response);            $this->dispatcher->dispatch(KernelEvents::VIEW, $event);
HttpKernel->handleRaw(object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
    public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)    {        $request->headers->set('X-Php-Ob-Level', ob_get_level());        try {            return $this->handleRaw($request, $type);        } catch (\Exception $e) {            if ($e instanceof RequestExceptionInterface) {                $e = new BadRequestHttpException($e->getMessage(), $e);            }            if (false === $catch) {
HttpKernel->handle(object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
        $this->boot();        ++$this->requestStackSize;        $this->resetServices = true;        try {            return $this->getHttpKernel()->handle($request, $type, $catch);        } finally {            --$this->requestStackSize;        }    }
Kernel->handle(object(Request), 1, false)
in fyxmrlznlsjlkivm/index.php (line 86)
$request = Request::createFromGlobals();Request::setTrustedProxies([], Request::HEADER_X_FORWARDED_ALL);try {    require_once __DIR__.'/../autoload.php';    $response = $kernel->handle($request, HttpKernelInterface::MASTER_REQUEST, false);    $response->send();    $kernel->terminate($request, $response);} catch (NotFoundHttpException $exception) {    define('ADMIN_LEGACY_CONTEXT', true);    // correct Apache charset (except if it's too late)

**Comment by Stolaweb** [comment]
I have correct working Presta instalaltion, Can I rename some catalogues between installations?

**Comment by Stolaweb** [comment]
sorry *replace some directories or files?

**Comment by khouloudbelguith** [comment]
@Stolaweb, your issue is different.
This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
