### ISSUE TITLE
default price value show 0.00

### ISSUE THREAD

**Issue by Prem-lmx** [PrestaShop/PrestaShop#15168]
Hai ,
i have use the prestashop 1.7..
change the product price save the backend file in db..
but show the incorrect price in display,
please support him..

![image](https://user-images.githubusercontent.com/52959027/63342051-3255a700-c368-11e9-9bfe-7845b8a9711e.png)
![image](https://user-images.githubusercontent.com/52959027/63342201-86608b80-c368-11e9-886e-ccd0307e8b96.png)

**Additional information**
PrestaShop version: 1.7
PHP version: 5.6.25

Thanks,
Prem

**Comment by khouloudbelguith** [comment]
Hi @Prem-lmx,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by khouloudbelguith** [comment]
@Prem-lmx, there is no image attached, you need to connect to GitHub & upload your files.

Thanks!

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by khouloudbelguith** [comment]
@Prem-lmx, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

In your last comment => there is no image attached.
Thanks!

**Comment by Prem-lmx** [comment]
Edited because of sensitive data.

**Comment by PierreRambaud** [comment]
Please @Prem-lmx never send sensitive data. And change your password right now! :scream:

**Comment by khouloudbelguith** [comment]
@Prem-lmx, sorry we need more details to unstrand how to reproduce the issue(debug mode/PHP error log).

Thanks!

**Comment by PierreRambaud** [comment]
Please @Prem-lmx Do not respond anymore by email or be sure you remove your history. 
If you continue, we will be force to close this issue for you :/

**Comment by ghost** [comment]
This kind of issue happen when no default combination is selected (also have the same problem - https://github.com/PrestaShop/PrestaShop/issues/14851 )

**Comment by Prem-lmx** [comment]
Hai,
[image: image.png]

[image: image.png]
This issue not clear..

Thanks,

**Comment by khouloudbelguith** [comment]
@Prem-lmx, have you the same issue as @PrestaShark ?

The default combination is not set in the Back office?

Thanks!

**Comment by Prem-lmx** [comment]
That issue solve or non?
plese reply
Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, the issue reported by @PrestaShark, is not reproduced, we are waiting for his feedback, for more details you can follow this issue: #14851 
About your issue, The default combination is not set in the Back office => product details page => Combination Tab?
![image](https://user-images.githubusercontent.com/16067358/63427684-9e3e1b00-c40d-11e9-9454-94658edb83bb.png)

Thanks!

**Comment by Prem-lmx** [comment]
[image: image.png]
Thanks

**Comment by ghost** [comment]
Come on man stop using Github like that!
Click here https://github.com/PrestaShop/PrestaShop/issues/15168 and respond correctly!

**Comment by Prem-lmx** [comment]
But iisue not clear

thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, did you check this in your case?
>About your issue, The default combination is not set in the Back office => product details page => Combination Tab?

**Comment by ghost** [comment]
@Prem-lmx is Your products have combinations like Size? Color?

**Comment by Prem-lmx** [comment]
No only display the price..
Thanks

**Comment by Prem-lmx** [comment]
debug mode..
[image: image.png]

Thanks

**Comment by ghost** [comment]
xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Prem-lmx** [comment]
What?

**Comment by khouloudbelguith** [comment]
@Prem-lmx, sorry, but there is no image attached here.
You need to sign in on Github & upload this image on this ticket.
https://github.com/PrestaShop/PrestaShop/issues/15168
![image](https://user-images.githubusercontent.com/16067358/63429561-4d7cf100-c412-11e9-8a0f-3cf1b0597256.png)

Thanks!

**Comment by Prem-lmx** [comment]
![image](https://user-images.githubusercontent.com/52959027/63429768-9a73be00-c438-11e9-952f-3b2d290886d9.png)
![unnamed](https://user-images.githubusercontent.com/52959027/63429793-b11a1500-c438-11e9-8895-1c43e94c96b7.png)

**Comment by khouloudbelguith** [comment]
@Prem-lmx, Could you please navigate to your BO => Advanced Parameters => Information page & provide me a screenshot about your server configuration & the  MySQL version.

Thanks!

**Comment by Prem-lmx** [comment]
[image: image.png]

Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, there is no image attached here.
You need to sign in on Github & upload this image on this ticket.
Thanks!

**Comment by Prem-lmx** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/52959027/63433939-b596fb80-c441-11e9-8036-501b2ac6ff1b.png)
Thanks
![unnamed (1)](https://user-images.githubusercontent.com/52959027/63433952-bcbe0980-c441-11e9-9202-54ed716d34b3.png)

**Comment by khouloudbelguith** [comment]
@Prem-lmx,

You have memory limit =1G incorrect.
Thanks to change it to `1000M` for example.
unfortunately, we are aware of this issue and it does not come from Prestashop, see https://github.com/PrestaShop/PrestaShop/pull/10892#issuecomment-439097520

Thanks!

**Comment by Prem-lmx** [comment]
[image: image.png]
NO issue solve..
Thanks

**Comment by Prem-lmx** [comment]
![2a4adc36-05e6-4510-84ba-81c899fc9e1e](https://user-images.githubusercontent.com/52959027/63434884-884b4d00-c443-11e9-8425-9f61a9cb8f6b.png)
No issue solve..
Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, in your BO => Product details page => Price Tab
You have a lot of fields
![image](https://user-images.githubusercontent.com/16067358/63436339-6c827f80-c420-11e9-81f4-be08cdf67872.png)
@Prem-lmx, those fields are added from a custom module?

Thanks!

**Comment by Prem-lmx** [comment]
Yes custom module,
Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, Have you tried to contact the module author?
Thanks to check with them the issue & feedback.

**Comment by Prem-lmx** [comment]
sry ...not cusom module add,
Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, so those fields how they are added, did you edit the core PrestaShop & do you have any overrides?

Thanks!

**Comment by Prem-lmx** [comment]
Thanks for your Kind responce,,
i have solve the problem,
Thanks
khouloudbelguith

**Comment by khouloudbelguith** [comment]
@Prem-lmx, thanks!
Since it is fixed, I close the issue.

Feel free to open a new one when needed.

**Comment by ghost** [comment]
@Prem-lmx You should help community and tell how did You manage your issue... Maybe someone else will have similar problem?

**Comment by kossrlive** [comment]
joining the conversation,  (Prestashop 1.7.6.4)
I have same problem as i understood right current thread. 

I think, that issue often starts when we using  product imports. 

I have products with combinations too.

For example:  Adidas Sneakers with basic(Retail) price 100$
And its combinations(Sizes) available:       Size - 10, Size - 11, Size - 12 .
The price is the same as Retail (Basic) so here no combination impact.

The default combination for example Size - 7

Full combinations table looks like 
CombName   PriceImpact     EndPrice     StockCount
Size - 7                0                      0                      0                **Default**
Size - 8                 0                      0                      0               
Size - 9                 0                      0                      0               
Size - 10             100                  100                     5               
Size - 11              100                  100                      2               
Size - 12              100                  100                      4               

Here we can see that we have **DEFAULT** combination set by import to product that has no stock and no price. (Combinations may be filled with pattern from external source ERP, Accounting software etc) 

And we now see that price $0.00 at FrontOffice(HomePage e.g.) on product. 

Managing that products with hand is not an option b/c importing catalogs may be very large. 

I think here need to be some cron-task to scan all products
check Default combination on each iteration and if it has no stock or no price then change it to nearest combination with price and stock count. 

if product on current iteration has not more combination left with price and stock then do another stuff which can be set in setting tab for example. 

Turn product off, write to another table () show alert etc., 


For today i dont solved that problem yet. 
I have zero price in FO, and when i click that product -  than on product page i see price and combinations that available. So my conclusion that "Single Product Page" can determine which combinations available for order. And FO product tabs (thumbnails) - can`t.
