### ISSUE TITLE
"1G" is not a valid maximum size

### ISSUE THREAD

**Issue by silviu25** [PrestaShop/PrestaShop#15162]
**Describe the bug** **To Reproduce**
If  "upload_max_filesize"  is configured to 1G in PHP configuration, then I can not upload/ install new modules. I get the following error:  "1G" is not a valid maximum size.

**Screenshots**
https://ibb.co/HCkf9ZK

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.21

Linux Server Information # 1 SMP Fri Jun 28 06:30:57 EDT 2019 x86_64
Server software version: LiteSpeed
PHP Version: 7.2.21
Memory limit: 1G
Maximum execution time: 240
Maximum file upload limit: 1G

**Comment by matks** [comment]
Hi, unfortunately we are aware of this issue and it does not come from prestashop, see https://github.com/PrestaShop/PrestaShop/pull/10892#issuecomment-439097520
