### ISSUE TITLE
Product indexation on bulk/unit active/deactive operation from admin product list.

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#15165]
**Describe the bug**
Once the products are created in the offline stage and then its get active from the product list, the indexation for this product will not be true. Because of on product active/deactivate from the product list, the product indexation is not working and also on bulk action the indexation option is not getting updated.

**To Reproduce**
1. Create/save a new product in the offline stage from back-office catalog.
2. Now activate this product from the catalog product list.
3. Now the product will activate but still, it will not able to search the same product on the front office through search bar module.

If the product gets created in the online stage then it will get search on the front office search bar module.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9663
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9663

**Comment by PeeyushAgrawal** [comment]
Hello @khouloudbelguith 
thanks.

Can I create the PR for this issue solution?

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, yes!
You can make a pull request on GitHub with your code suggestion: 
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith 

The PR has been created https://github.com/PrestaShop/PrestaShop/pull/15167

Please check. 
Thanks.

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, thanks a lot!
