### ISSUE TITLE
An answer to your message no. ct%thread_id is available (thread ID tcVZCv6tKE7zVG)

### ISSUE THREAD

**Issue by ArtiomkaPL** [PrestaShop/PrestaShop#15172]
**Describe the bug**
Weird email reply subejct

**To Reproduce**
1. use contact form on shop
2. reply to it via prestashop  "Customer Service" 
3. receive weird email subject

I dont know if this is a bug or my error as first timer on prestashop.
So if i use contact form and send message to site and i reply to it via "Customer Service" from presta shop interface i get this error (?). email subject looks like this: "An answer to your message no. ct%thread_id is available (thread ID tcVZCv6tKE7zVG)"

**Comment by khouloudbelguith** [comment]
Hi @ArtiomkaPL,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/63361404-f6badd00-c367-11e9-8bde-7b893c32ccbc.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by LouiseBonnard** [comment]
On Crowdin, I have this string, available for all catalogs (from 1.7.2 to 1.7.6):

<img width="600" alt="Capture d’écran 2019-08-21 à 14 15 18" src="https://user-images.githubusercontent.com/32565890/63431017-35ab6a00-c41e-11e9-8900-776d63fdfdcb.png">

Here, it seems that the variables are not properly displayed... @jolelievre, any idea? If it is a bug, let's add it to the debug roadmap, thanks @khouloudbelguith. :-)

**Comment by arouiadib** [comment]
The default translation string is missing a `%` at the end of the variable. I can see it from `International / Translation / Emails translations/ Subject` in 1.7.5.0

It is (probably) coming from the translation file `app/Resources/translations/en-US/EmailsSubject.en-US.xlf`. But how can I edit this file?  I don't find it in the repository.

**Edit:**
Both `en-Us` and `en-GB` xlf files have this mistake. But where are they in Github? I just find the 'default' in `app/Resources/translations`. Any help?

**Comment by LouiseBonnard** [comment]
Dear @arouiadib, I've looked a bit into en-US files and the mistake is on the translation part, not the source string. I've just corrected it on the Crowdin translation project [here](https://crowdin.com/project/prestashop-official/en#), it should be effective in a couple of days. ;-)
