### ISSUE TITLE
Faceted Search - By default put "indexable" option to No in add/edit attributes & features pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15170]
When faceted search is installed it add an "Indexable" option in add/edit attributes and features pages.
By default this option is set to Yes but should be on No.

![capture d'écran_1910](https://user-images.githubusercontent.com/13449658/63350159-2ca69400-c35d-11e9-85c1-83ec44697065.png)

![capture d'écran_1911](https://user-images.githubusercontent.com/13449658/63350167-303a1b00-c35d-11e9-93ab-a0187889e47b.png)

**Comment by Progi1984** [comment]
Thanks @Kaudaj
