### ISSUE TITLE
Multiple feature values for a single feature

### ISSUE THREAD

**Issue by harm-smits** [PrestaShop/PrestaShop#15177]
**Is your feature request related to a problem? Please describe.**
It is very weird that you can not assign multiple feature values to a single product feature. Think about when you are selling e.g. intel processors. A processor normally has a socket, which is a single value per product. However, if you start selling processor coolers as well, then you have a problem as you can not assign multiple sockets to a cooler.

Another analogy: Lets imagine you are selling teddybears in different sizes. You also put accessories for the teddybears in that category, however, there are some shoes that fit on mulitple sizes of teddybears. E.g. for XL, L and M. There is no way to define this at all.

**Describe the solution you'd like**
Multiple product feature values can be assigned to a single feature.

**Describe alternatives you've considered**
There are literally no alternatives.

**Additional context**

**Comment by ghost** [comment]
In 1.7 You can do it ;)
![zrzut 2019-08-20 22 55 04](https://user-images.githubusercontent.com/8243273/63383746-acece980-c39d-11e9-8263-829d19b09865.png)

Feature "Skład" have three values "Bawełna, Elastan, Poliester"
So feature "Supported processors" will have "775, 1150, 1151, 2011" etc

**Comment by Hlavtox** [comment]
Yes, you can do it in 1.7. 

Nice advancement from 1.6. No need for multiple features module. :-)

**Comment by khouloudbelguith** [comment]
Hi @harm-smits,

Thanks for your report.
Yes, as said before, this improvement is well implemented with PS1.7.
BO:
![image](https://user-images.githubusercontent.com/16067358/63414688-447d2700-c3f4-11e9-9860-dc2128c3d965.png)
FO:
![image](https://user-images.githubusercontent.com/16067358/63414714-4e9f2580-c3f4-11e9-916a-c90c3492b72d.png)
I close the issue, feel free to open a new one when needed.

Thanks!
