### ISSUE TITLE
Missing "markbaker/matrix/classes/src/functions/adjoint.php"

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#15187]
**Describe the bug**
During autoupgrade from PS 1.7.5.1 to 1.7.6.0 an error 500 appears.

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.7.5.1
 - Version you upgrade to: 1.7.6.0
 - Way of upgrade: Web
 - Step concerned: upgrade code

**Displayed log**
```
2019/07/16 11:43:33 [error] 15645#15645: *2520 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/prestashop/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php): failed to open stream: No such file or directory in /var/www/prestashop/html/vendor/composer/autoload_real.php on line 61

PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/prestashop/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php' (include_path='/var/www/prestashop/html/vendor/pear/pear_exception:/var/www/prestashop/html/vendor/pear/console_getopt:/var/www/prestashop/html/vendor/pear/pear-core-minimal/src:/var/www/prestashop/html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/prestashop/html/vendor/composer/autoload_real.php on line 61"
```

**Expected behavior**
A clean install without error 500.

**Server (please complete the following information):**
 - Web Server: Nginx 
 - PHP Version: 7.1
 - Module Version 4.9.0

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks to check & feedback.

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith ,
I didn't changed core files. If I remember right, it was an issue with Composer. Certainly specific to my dev environment. Now it solved.
Thanks.

**Comment by khouloudbelguith** [comment]
@Klemart3D, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by giogutierrez** [comment]
friends help please I get the same error when updating from 1.7.5.1 to 1.7.6.0

you already delete the / var folders but follow the same problem and I don't identify a possible solution


Warning: require(/var/www/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 61

Fatal error: require(): Failed opening required '/var/www/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 61

**Comment by Klemart3D** [comment]
@t1desarrollo : can you give more information about your environment to see if we have some similar configuration ? Are you using dev mode ?

**Comment by khouloudbelguith** [comment]
@t1desarrollo, an issue created here: https://github.com/PrestaShop/PrestaShop/issues/15294

**Comment by joffd** [comment]
Hi, I am facing the same error. 
Debian 9 (scretch)
PHP 7.0
Apache 2.4.25
on a VPS.

It was when I updated from 1.7.5 to 1.7.6.5 using 1-click. No error message during the update
var/cache as been cleaned


Warning: require(/var/www/prestashop/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php): failed to open stream: No such file or directory in /var/www/prestashop/vendor/composer/autoload_real.php on line 61

Fatal error: require(): Failed opening required '/var/www/prestashop/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php' (include_path='/var/www/prestashop/vendor/pear/pear_exception:/var/www/prestashop/vendor/pear/console_getopt:/var/www/prestashop/vendor/pear/pear-core-minimal/src:/var/www/prestashop/vendor/pear/archive_tar:.:/usr/share/php:/usr/share/pear') in /var/www/prestashop/vendor/composer/autoload_real.php on line 61

**Comment by aayush-webkul** [comment]
I'm facing this exact same issue 
Laravel 7.x
Ecosystem Bagisto 1.2.0
PHP 7.2

I cleared all the folders in var/cache. It didn't help.

**Comment by Web2FixOy** [comment]
Notice the capitalized names are important in Linux based systems while in windows development environments the error may not occur!   
Temporary solution:
A temporary fix is to rename folders "functions" to "Functions" as well as "operations" to "Operations" .
Path to those folders: markbaker > complex > matric > classes > src > operations OR functions

Hope this helps!

**Comment by Kallou0** [comment]
This one worked for me. Thanks @Web2FixOy
