### ISSUE TITLE
How about Add products for XXX $ to get free shipping?

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15182]
How about Add products for XXX $ to get free shipping?

_Originally posted by @PrestaShark in https://github.com/PrestaShop/PrestaShop/issues/15152#issuecomment-523381283_

**Comment by marionf** [comment]
@PrestaShark 

You can already use a reassurance module to display this kind of information: "Free shipping from 50€"

**Comment by ghost** [comment]
Thanks @marionf . For clarification.

When free shipping is set to 100$ and products value in Your cart is 80$ then store tell customer something like "Add products for another 20$ and get free shipping" :)

**Comment by marionf** [comment]
@PrestaShark 

I see, however we already have several addons modules to do that:

https://addons.prestashop.com/fr/frais-de-port/21627-free-shipping-info.html
https://addons.prestashop.com/fr/frais-de-port/8895-gestion-avancee-frais-de-port-offerts.html
https://addons.prestashop.com/fr/frais-de-port/7490-freelivery-frais-de-port-gratuits.html
https://addons.prestashop.com/fr/frais-de-port/20769-amount-left-for-free-delivery-free-shipping-count.html
https://addons.prestashop.com/fr/frais-de-port/28187-free-shipping-amount-display.html

So, I don't think we will integrate this natively

**Comment by ghost** [comment]
As World of Tanks player i have notticed that many of unofficial mods was incorporated into game core features - just for mention ;)
