### ISSUE TITLE
Error: Class 'Core_Business_ContainerBuilder' not found (PS: 1.6.24 to 1.7.2)

### ISSUE THREAD

**Issue by carras** [PrestaShop/PrestaShop#15188]
Hello there:

After try many times to use the autougrade module (v4.8) to upgrade PS 1.6.24 to 1.7.2; I always get the following errors:

Does anybody know what's wrong? Thanks.

[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - scandir(/home//public_html/Adapter/): failed to open dir: No such file or directory
[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - scandir(): (errno 2): No such file or directory
[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - Invalid argument supplied for foreach()
[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - scandir(/home//public_html/Core/): failed to open dir: No such file or directory
[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - scandir(): (errno 2): No such file or directory
[INTERNAL] /home//public_html/classes/PrestaShopAutoload.php line 184 - Invalid argument supplied for foreach()

[INTERNAL] 
/home//public_html/config/bootstrap.php line 27 - Error: Class 'Core_Business_ContainerBuilder' not found 

#0 /home//public_html/config/config.inc.php(66): require_once() 
PrestaShop/autoupgrade#1 /home//public_html/modules/autoupgrade/classes/UpgradeContainer.php(499): require_once('/home//p...') 
PrestaShop/autoupgrade#2 /home//public_html/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() 
PrestaShop/autoupgrade#3 /home//public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(75): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() 
PrestaShop/autoupgrade#4 /home//public_html/controlador/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() 
PrestaShop/autoupgrade#5 {main}

**Comment by khouloudbelguith** [comment]
Hi @carras,

Do you need to make an upgrade from PS1.6 to PS1.7.2?
The last version PrestaShop released is PS1.7.6.0.
Did you use the local Archive?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @carras,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
