### ISSUE TITLE
Reviews are not displayed after changing the quantity

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15184]
**Describe the bug**
If we change the quantity on the product page, the reviews are not displayed any more.

**To Reproduce**
1. Go to a product with some reviews approved
![image](https://user-images.githubusercontent.com/16067358/63425451-77311a80-c408-11e9-9d2e-2e2992567464.png)

2. Change the quantity
3. See error

![image](https://user-images.githubusercontent.com/16067358/63425489-929c2580-c408-11e9-9c70-ea27ac14fe82.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2
productcomments v4.0.0

**Comment by khouloudbelguith** [comment]
Ping @jolelievre

**Comment by jolelievre** [comment]
Oh interesting bug ^^ this needs to be fixed in the module

**Comment by matks** [comment]
Will be fixed by the release of productcomments module
