### ISSUE TITLE
évolution d'un site prestashop 1.5.4.1 à 1.7

### ISSUE THREAD

**Issue by rachpat** [PrestaShop/PrestaShop#15189]
J'aimerais faire évoluer mon site créé avec prestashop 1.5.4.1, j'aimerais le passer en 1.7. J'ai pour cela activé le module v1.6.8-autoupgrade, mais lorsque je fais "upgrade prestashop now", rien ne se passe, j'ai le message : Analyzing the situation...Shop deactivated. Now downloading... (this can take a while)
[Ajax / Server Error for action download] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: " "
Pouvez-vous m'indiquer la marche à suivre ?
Merci beaucoup d'avance,
Rachel

**Comment by khouloudbelguith** [comment]
Hi @rachpat,

Sorry for the late answer.
Do you still have the same issue?

We release a new version of the 1-click upgrade v4.9.0 to make an upgrade from PS1.6 => PS1.7

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @rachpat,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
