### ISSUE TITLE
Error in upgrade to prestashop 1.7.5.2 to 1.7.6.0

### ISSUE THREAD

**Issue by toyser** [PrestaShop/PrestaShop#15185]
**Describe the bug**
the update of prestashop is impossible.
I tried the update with the module "1-click upgrade", I installed it and when I launched it, it failed after a moment.

**Upgrade environment (please complete the following information):**
 - Version you started from: [e.g. 1.7.5.2]
 - Version you upgrade to: [e.g. 1.7.6.0]
 - Way of upgrade: Web 

**Displayed log**
```
Unable to open archive
[INTERNAL] /homepages/39/d787428639/htdocs/modules/autoupgrade/classes/ZipAction.php line 111 - ZipArchive::close(): Can't open file: Permission denied
Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.
```

**Expected behavior**
I expect a solution to my issue so that I can update it. 

**Screenshots**
![error_module_1-click-upgrade](https://user-images.githubusercontent.com/53787145/62477030-6c3f7e80-b7a8-11e9-85f4-fccefacc1d67.png)

**Server (please complete the following information):**
 - Web Server: [e.g. Apache]
 - PHP Version: [e.g. 7.2]
 - Module Version [e.g. 4.9]

Thank's for your help

**Comment by khouloudbelguith** [comment]
Hi @toyser,

This is a permission issue.
Thanks to edit the permission's file & feedback.

**Comment by toyser** [comment]
Hi @khouloudbelguith,

Thanks for your reply.
I understand that, but what is the permission's file ? I searched for but i didn't find it... 
Can you help me (more) ?

**Comment by khouloudbelguith** [comment]
Hi @toyser,

Your exact issue is 
```
Can't open file: Permission denied
Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.
```

You have a permission denied on your server.
It is not allowed to write on your disk & there is no space available on it.
If you don't have access, you can check with your host to give the right permission. 
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @toyser,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
