### ISSUE TITLE
Add a percentage of progress during upgrade

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#15190]
**Describe the feature**
In order to improve the UX of the odule, we want to display a progress bar during the upgrade process.
This requires the back end to return a % of progress done.

**Comment by khouloudbelguith** [comment]
Ping @colinegin, @marionf

**Comment by gericfo** [comment]
Hello @Quetzacoalt91 
Great idea! 
We're keeping this in mind as we work to improve autoupgrade. I'm closing this ticket, and we'll be making a new one very soon.
Thanks!
