### ISSUE TITLE
Different store version in the DB and files

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#15198]
Store 1.7.3.4 to 1.7.4.2
autoupgrade 4.0.0

When the module starts to work it shows the current version of the store. In my case it was 1.7.3.4, but when it updates the data base structure it takes the version of the store from the db
```
mysql> SELECT * FROM `ps_configuration` WHERE name='PS_VERSION_DB';
+------------------+---------------+---------+---------------+----------+---------------------+---------------------+
| id_configuration | id_shop_group | id_shop | name          | value    | date_add            | date_upd            |
+------------------+---------------+---------+---------------+----------+---------------------+---------------------+
|              229 |          NULL |    NULL | PS_VERSION_DB | 1.6.1.16 | 0000-00-00 00:00:00 | 2015-03-04 10:48:37 |
+------------------+---------------+---------+---------------+----------+---------------------+---------------------+
1 row in set (0,00 sec)
```
I upgraded my store from 1.6.1.16 to 1.7.3.4 with diff and patch tools. So the store version was in the files 1.7.3.4 but in the DB the version was 1.6.1.16.

I upgraded my data base accordingly to the files in install/upgrade/sql/ with .sql extention, so my store works fine.

When I tried to use autoupgrade module (v.4.0.0) it upgraded files fine but the data base were corrupted because the module applied the changes from 1.6.1.19.

I think there should be warning if the versions in the DB and in the files are different.
![presta_upgrade](https://user-images.githubusercontent.com/37952504/44720806-06973c80-aad9-11e8-8723-ee1c89ce20cb.png)

**Comment by khouloudbelguith** [comment]
Ping @colinegin, @marionf
