### ISSUE TITLE
The auto-upgrade module is indicated as being up to date when it is not

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15194]
### Describe the bug
In the configuration page of the `autoupgrade` module, we have a checklist.
When we have an old module, the first checklist is wrong.
We have "The 1-click upgrade module is `up-to-date` (your current version is v4.5.1)" with a right icon, which is wrong, the latest version is 4.6.0, so the module is not up-to-date.
Thanks!

### Screenshots 
![image](https://user-images.githubusercontent.com/16067358/53249816-58e89d00-36b9-11e9-97cc-297273c287f1.png)

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 7.1
 - Module Version 4.5.1

### Wanted behavior

**As a user, I want to know if my module is up to date to be able to start the upgrade and ensure its success.**

1. Remove the line "The 1-click upgrade module is up-to-date (your current version is vX.X.X)" in the pre-upgrade checklist.
2. We should check that the module is well up to date, if it's not the case display the following warning in the "welcome" block: "Your current version of the module is out of date. Update now in Modules > Module Manager > Updates" with a link redirecting to the "updates" tab of the module manager page on "Modules > Module Manager > Updates" for 1.7 versions and a link to "Modules & services" tab for 1.6 versions

**Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710**

![Capture d’écran 2021-09-15 à 16 22 42](https://user-images.githubusercontent.com/13449658/133451590-6ec61f80-7c10-47e8-929f-f528ef194ef6.png)

**Comment by khouloudbelguith** [comment]
Hi,

This issue still occurs
![image](https://user-images.githubusercontent.com/16067358/63445639-a6f41880-c430-11e9-9247-f6398f12aa17.png)

I’ll add this to the debug roadmap.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello,

This issue is still persist, the newest version is 4.11.0:

![image](https://user-images.githubusercontent.com/23308427/105031498-ab719600-5a55-11eb-9717-9d71bb788504.png)

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @khouloudbelguith 

I didn't manage to reproduce this issue with **1-Click upgrade** v4.12.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/112504793-6c7cfb00-8d8c-11eb-9493-e5ab166b2554.png)

Please check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @hibatallahAouadni,

I manage to reproduce the issue with PS1772 and the 1-click upgrade v4.11.0.
![image](https://user-images.githubusercontent.com/16067358/112828525-16f86500-9090-11eb-9e41-5df443b1fbb7.png)

Thank you!

**Comment by marionf** [comment]
Duplicate of #25641

**Comment by Hlavtox** [comment]
@marionf My autoupgrade is even weirder. It says the module is not up to date and current version is v4.12.0.

But my module version is v4.12.0, freshly installed :D

**Comment by ghost** [comment]
Hello, @marionf && @khouloudbelguith 

I work actualy on this issue itss not say if the upgrade need to be blocked if it's not the last version ?

**Comment by marionf** [comment]
Hello @okom3pom 

No, the upgrade shouldn't be blocked if the module isn't up-to-date because it could be a problem if for example there was a critical bug on the last version of the module.
