### ISSUE TITLE
Consistent Error While upgrading database: Prestashop 1.6.1.23 -> 1.7.1.0

### ISSUE THREAD

**Issue by drchad2008** [PrestaShop/PrestaShop#15196]
**Describe the bug**
I've been able to successfully upgrade from Prestashop 1.5.6.0 to 1.6.1.23 using the 1-Click Upgrade Module (a few issues along the way but I worked them out). However I'm stuck trying to upgrade 1.6.1.23 to any version of 1.7 (I've mostly been trying 1.7.1.0). The upgrade always makes it through the files with no problems but then produces the same errors each time when trying to upgrade the database. 

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.1.23
 - Version you upgrade to: 1.7.1.0
 - Way of upgrade: Web
 - Step concerned: upgrade DB 

**Displayed log**
```

[INTERNAL] /home/drchad1983/public_html/classes/shop/Shop.php line 347 - Invalid argument supplied for foreach()


[INTERNAL] /home/drchad1983/public_html/config/config.inc.php line 121 - Error: Call to a member function getName() on null #0 /home/drchad1983/public_html/modules/autoupgrade/classes/UpgradeContainer.php(475): require_once() PrestaShop/autoupgrade#1 /home/drchad1983/public_html/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() PrestaShop/autoupgrade#2 /home/drchad1983/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(74): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() PrestaShop/autoupgrade#3 /home/drchad1983/public_html/admin0300/autoupgrade/ajax-upgradetab.php(51): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() PrestaShop/autoupgrade#4 {main}
```

**Expected behavior**
I expected the database to be upgraded 

**Screenshots**
I don't have screenshots, but the error above is exactly what I see on the module when it stalls. Then if I try to load the back end it's a blank white screen and the front end shows a 500 error.

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 7.0
 - Module Version 4.5.1

**Additional context**
Any help is appreciated. I'm not a developer but have troubleshooting skills and can usually solve these types of issues with some guidance.

**Comment by khouloudbelguith** [comment]
Hi @drchad2008,

Sorry for the late answer.
Do you still have the same issue?
We release a new version of the 1-click upgrade module v4.9.0.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @drchad2008,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
