### ISSUE TITLE
1-click upgrade prestashop v1.7

### ISSUE THREAD

**Issue by powergraf06** [PrestaShop/PrestaShop#15191]
Subject: Problem with 1-Click Update - fatal error admin

http://<URLremoved>/index.php?tab=AdminSelfUpgrade&token=

Fatal error: Call to undefined method AdminSelfUpgrade::displayErrors() in /home/comptoirr/www/admin7416/functions.php on line 278

Hello, After installing the module "1-Click Upgrade", as soon as I click on the button "Configure", the page in link is in failure (see above). For information, the PHP version was in 5.4, it was changed in 5.6, I do not know if that's what made the bug? Thank you for giving me the procedure to follow in order to finish the update of the admin prestashop in V 1.7.

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @powergraf06,

Do you still have the same issue?
We released a new version of the 1-click upgrade v4.9.0.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @powergraf06,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
