### ISSUE TITLE
Error upgrade prestashop db 1.6.1.20 to 1.7.4.2

### ISSUE THREAD

**Issue by JavierEB** [PrestaShop/PrestaShop#15199]
**Describe the bug**

**Upgrade environment (please complete the following information):**
 - Version you started from: [1.6.1.20]
 - Version you upgrade to: [1.7.4.2]
 - Way of upgrade: Web
 - Step concerned: [upgrade DB] 

**Displayed log**
```
Updating database schema...
13:18:02 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "prestashop:schema:update-without-foreign","message" => "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it."] []
In AbstractPlatform.php line 423:
Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] 
![error]
```

**Expected behavior**

**Screenshots**
(https://user-images.githubusercontent.com/5004396/44582709-c6674f80-a7a2-11e8-9b5f-83d6d62ebbb7.jpg)

**Server (please complete the following information):**
 - Web Server: [Apache 2.4.3 ]
 - PHP Version: [7.1.16]
 - Module Version [4.1]

**Additional context**
[log.txt](https://github.com/PrestaShop/autoupgrade/files/2318171/log.txt)

**Comment by Quetzacoalt91** [comment]
Thanks  for the update @JavierEB. By any chance, do you have the name of the module? It would be interesting for us to reproduce the issue. If it's sold on the marketplace, we should be able to contact the module developper to bring a fix.

Regards

**Comment by JavierEB** [comment]
> 
> 
> Thanks for the update @JavierEB. By any chance, do you have the name of the module? It would be interesting for us to reproduce the issue. If it's sold on the marketplace, we should be able to contact the module developper to bring a fix.
> 
> Regards

hello again, I think that this table is not specifically from a module, it is the table ps_specific_price as you can see in the picture that I attached, and I looked at several different prestashop facilities that I have and in all of them it looks the same, type BIT.
![tabla specific price](https://user-images.githubusercontent.com/5004396/45694167-f6fe9700-bb5e-11e8-9101-f8df0b6b1113.jpg)
I wait your answer thank you

**Comment by khouloudbelguith** [comment]
Hi @JavierEB,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Sasni** [comment]
expressmailing

```
--
-- Table structure for table `tr4Svg_expressmailing_email_recipients`
--

DROP TABLE IF EXISTS `tr4Svg_expressmailing_email_recipients`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tr4Svg_expressmailing_email_recipients` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_id` int(10) unsigned NOT NULL,
  `target` text,
  **`uploaded` bit(1) NOT NULL DEFAULT b'0',**
  `lang_iso` varchar(3) DEFAULT NULL,
  `last_name` text,
  `first_name` text,
  `ip_address` text,
  `last_connexion_date` int(10) unsigned DEFAULT NULL,
  `source` varchar(10) DEFAULT NULL,
  `group_name` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by khouloudbelguith** [comment]
Hi @Sasni,

This module is not provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
