### ISSUE TITLE
Mysql error in upgrading PS1.7.4.4 to PS1.7.5 using 1-click, and cannot display admin/module page.

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#15195]
The following 3 mysql errors displayed in window, when upgrading PS1.7.4.4 to PS1.7.5 using 1-click, and cannot display admin/module page.

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE ps_supply_order_receipt_history CHANGE employee_firstname employee_firstname VARCHAR(255) DEFAULT ”, CHANGE employee_lastname employee_firstname VARCHAR(255) DEFAULT ”: Duplicate column name ’employee_firstname’

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE ps_product CHANGE reference supplier_reference varchar(64) DEFAULT NULL, CHANGE supplier_reference supplier_reference varchar(64) DEFAULT NULL: Duplicate column name ‘supplier_reference’

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE ps_stock_available ADD location VARCHAR(255) NOT NULL DEFAULT ” AFTER out_of_stock: Duplicate column name ‘location’ 

It says Upgrade has been successful.

But I cannot display admin/module page (debug 'off') only an error is displayed.

When I set debug 'on', the actual listing of the admin/module shows up, perfectly OK. But again in setting dubug to 'off' the admin/module list does not show up, only error below shows up.

_Oops! An Error Occurred
The server returned a “500 Internal Server Error”.
Something is broken. Please let us know what.._

**Comment by khouloudbelguith** [comment]
Hi @gray-b,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
