### ISSUE TITLE
Javascript error (parseJSON) detected for action "upgradeNow".

### ISSUE THREAD

**Issue by bellamolipaolo** [PrestaShop/PrestaShop#15200]
Hi, i have try to upgrade from 1.7.3.3 to 1.7.4.2 but no way to complete the job with the 1-click upgrade module.
now I have this error_
Javascript error (parseJSON) detected for action "upgradeNow".

 - Version you started from: [e.g. 1.7.3.3]
 - Version you upgrade to: [e.g. 1.7.4.2]
 - Way of upgrade: Web

an anyone help me ?

**Comment by bellamolipaolo** [comment]
Thank you for your help  
@Quetzacoalt91

**Comment by khouloudbelguith** [comment]
Hi @bellamolipaolo,

Do you still have the same issue?
We released a new version Autoupgrade v4.9.0.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @bellamolipaolo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
