### ISSUE TITLE
Old module use ImportModule

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15204]
**Describe the bug**
Old module try to access to ImportModule classe

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.1.10
 - Version you upgrade to: 1.7.3.3
 - Way of upgrade: Web
 - Step concerned: module

**Displayed log**
```
AH01071: Got error 'PHP message: PHP Fatal error: Class 'ImportModule' not found in /var/www/vhosts/chafoins.com/httpdocs/presta2/modules/importerosc/importerosc.php on line 30\n', referer: https://www.chafoins.com/presta2/adminxxxx/index.php?controller=AdminSelfUpgrade&conf=6&token=7a843423af6472810924dfaf3bba77fe
```

**Expected behavior**
I have an old module in my folder not installed

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 7.0.30
 - Module Version 4.0.0 beta

**Additional context**

Informations sur votre serveur Linux PrestaShop/autoupgrade#1 SMP Tue Jun 30 19:37:11 CEST 2015 x86_64
Version du logiciel serveur Apache
Version de PHP 7.0.30
Limite de mémoire 1024M
Temps d'exécution maximal (max_execution_time) 0
Version de PrestaShop 1.6.1.10
URL de votre boutique http://www.chafoins.com/presta2/
Nom du thème utilisé esprit

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
