### ISSUE TITLE
update from 1.6.1.20 to 1.7.4.2 failed

### ISSUE THREAD

**Issue by tjengbudi** [PrestaShop/PrestaShop#15202]
hello,
is there any walk through that must be consider to make this running well?
i update autoupgrade 4.0 beta 5. the upgrade working succesfull. all non native is disabled. and use native module only. but native module looks like never upgrade. 
or new native module in 1.7 never installed. (please revised if i am wrong)

and the front page failure event used default theme by presta.

looks like i do not know how to used this module to upgrade the prestashop

any guide ?

**Comment by khouloudbelguith** [comment]
Hi @tjengbudi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
