### ISSUE TITLE
upgrade from 1.7.3.0 to 1.7.4.1

### ISSUE THREAD

**Issue by V41F** [PrestaShop/PrestaShop#15203]
Hi, I am trying to update from 1.7.3.0 to 1.7.4.1 with your module but it is not working. Version comparison is still loading. I also tried manual upgrade and the result is not working. After click on save button nothing happend. 
![image](https://user-images.githubusercontent.com/41673053/43199971-10e7dc42-9014-11e8-9f0a-acfe9d689c69.png)

could you pls help me. thx

**Comment by Quetzacoalt91** [comment]
> I don't know if it's good idea because then it's public and everyone can see the name of admin folder...

You can search/replace the admin folder by another name. :)

> OK, sorry but where I can find this values?

You can find these details in your back office, in "Advanced parameters > Information".
For instance:
![capture du 2018-08-10 11-18-54](https://user-images.githubusercontent.com/6768917/43949942-4a5ec1a2-9c8f-11e8-9915-c654e2335a68.png)

**Comment by V41F** [comment]
![image](https://user-images.githubusercontent.com/41673053/43950172-e3fd79c0-9c8f-11e8-8d5b-958540616660.png)

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
bad news. After this change you can see the result below. I'm sorry but I'm really exhausting. It is no possible to upgrade prestashop? I tried to do it from 25 jul without any possitive result.....
![untitled](https://user-images.githubusercontent.com/41673053/47656147-d0d10b80-db8e-11e8-809e-213a5134e78b.png)

**Comment by khouloudbelguith** [comment]
@wewew85, any news about your issue?

Thanks!

**Comment by V41F** [comment]
Hi @khouloudbelguith
I did it but with the same result:( same error

**Comment by khouloudbelguith** [comment]
@wewew85; we released a new version of the 1-click upgrade v4.9.0.
Did you check your issue with this version?

Thanks!

**Comment by V41F** [comment]
Hi @khouloudbelguith,
No I didn’t. You know it is always 2 hours of work because of error. I have to copy all files via FTP because prestashop is not working. Rollback in presta is not working...

**Comment by khouloudbelguith** [comment]
@wewew85, what is the exact version of the 1-click did you use?

Thanks!

**Comment by V41F** [comment]
@khouloudbelguith
My version of 1-click is 4.5.1.

**Comment by khouloudbelguith** [comment]
@wewew85, in my case, I dd not manage to reproduce the issue with PS1.7.4.1 after upgrade from PS1.7.3.0 using the 1-click upgrade v4.5.1.
https://drive.google.com/file/d/10zWPfsbBAtEaujo1ytIE1UHjJ-_D_jZW/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!
