### ISSUE TITLE
The service "installer" has a dependency on a non-existent parameter "module_settings" - Autoupgrade 4.5.1 Presta 1.7.4.2 > 1.7.5 fails

### ISSUE THREAD

**Issue by claustrier** [PrestaShop/PrestaShop#15205]
When using autoupgrade 4.5.1 to upgrade Presta 1.7.4.2 to 1.7.5, i get an error "The service "installer" has a dependency on a non-existent parameter "module_settings"."

Log:
[2019-01-03 23:05:55] [INTERNAL] /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php line 102 - Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "installer" has a dependency on a non-existent parameter "module_settings".
#0 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('module_settings')
PrestaShop/autoupgrade#1 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('module_settings')
PrestaShop/autoupgrade#2 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%module_setting...', Array)
PrestaShop/autoupgrade#3 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php(64): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%module_setting...')
PrestaShop/autoupgrade#4 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\ResolveParameterPlaceHoldersPass->processValue('%module_setting...', false)
PrestaShop/autoupgrade#5 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php(79): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
PrestaShop/autoupgrade#6 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(67): Symfony\Component\DependencyInjection\Compiler\ResolveParameterPlaceHoldersPass->processValue(Array)
PrestaShop/autoupgrade#7 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php(79): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
PrestaShop/autoupgrade#8 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\ResolveParameterPlaceHoldersPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
PrestaShop/autoupgrade#9 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php(79): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
PrestaShop/autoupgrade#10 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(39): Symfony\Component\DependencyInjection\Compiler\ResolveParameterPlaceHoldersPass->processValue(Array, true)
PrestaShop/autoupgrade#11 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php(43): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
PrestaShop/autoupgrade#12 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(141): Symfony\Component\DependencyInjection\Compiler\ResolveParameterPlaceHoldersPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
PrestaShop/autoupgrade#13 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(788): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
PrestaShop/autoupgrade#14 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(637): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
PrestaShop/autoupgrade#15 /home/vildmedg/staging/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
PrestaShop/autoupgrade#16 /home/vildmedg/staging/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot()
PrestaShop/autoupgrade#17 /home/vildmedg/staging/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(190): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->getModuleDataUpdater()
PrestaShop/autoupgrade#18 /home/vildmedg/staging/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(22312, 'blockreassuranc...')
PrestaShop/autoupgrade#19 /home/vildmedg/staging/admin341govc0d/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run()
PrestaShop/autoupgrade#20 {main}

Rollback is unsuccessful even though autoupgrade claims all files and db are restored. Manual restore of the database brings the site online again as 1.7.4.2.

Tried on 2 different servers, where the new server meets all requirements for Presta. (all green in php check file).  PhP 7.1, MariaDB.

No warnings in shop prior to running autoupgrade. 

[log.txt](https://github.com/PrestaShop/autoupgrade/files/2726328/log.txt)

**Comment by khouloudbelguith** [comment]
Hi @claustrier, @dennis-nielsen 

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
