### ISSUE TITLE
Added images to product do not appear on page

### ISSUE THREAD

**Issue by ArtiomkaPL** [PrestaShop/PrestaShop#15207]
**Describe the bug**
Added images to product do not appear on page

**To Reproduce**
1. Go to Catalog-Products
2. Click on Edit product - Basic settings
3. Add more images

**Additional information**
If it matters, auto added from prinftul
![notappearing](https://user-images.githubusercontent.com/40856128/63451205-57234a80-c44c-11e9-9487-76cc8d02a88e.PNG)
![notappearing2](https://user-images.githubusercontent.com/40856128/63451218-5be7fe80-c44c-11e9-9e4b-10067bfcdcef.PNG)

Found this but it was not helpful for me https://www.prestashop.com/forums/topic/628921-product-images-not-showing/
Also this
https://www.prestashop.com/forums/topic/946122-resolved-product-images-not-showing-on-website/
Deleting .htaccess did not help

Maybe it is just my error as first timer
This is a combination product.

**Comment by khouloudbelguith** [comment]
Hi @ArtiomkaPL, 

Could you please navigate to the BO => Product details page => Combinations Tab
Edit any combination and check if those images are selected in the buttom of the page. 

Thanks!

**Comment by ArtiomkaPL** [comment]
Yeah, turns out it has to be turned on in each combination. Thank You!

**Comment by khouloudbelguith** [comment]
@ArtiomkaPL, you are welcome.
I close the issue, feel free to open a new one when needed.

Thanks!
