### ISSUE TITLE
Create new order but the button of "Create the order" is grey 

### ISSUE THREAD

**Issue by AntiGravitySports** [PrestaShop/PrestaShop#15213]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @AntiGravitySports,

Do you have an issue with this button?
![image](https://user-images.githubusercontent.com/16067358/63500157-4103a180-c4c1-11e9-82d5-bc7a472f3b51.png)

Thanks!

**Comment by AntiGravitySports** [comment]
Hi Prestashop team,

Clicking these two bottons, it will show the page of creating new order, but the buttons of "Create the order" are still disable.







tina@eyezone.cn
 
From: khouloudbelguith
Date: 2019-08-22 16:43
To: PrestaShop/PrestaShop
CC: AntiGravitySports; Mention
Subject: Re: [PrestaShop/PrestaShop] Create new order but the button of "Create the order" is grey (#15213)
Hi @AntiGravitySports,
Do you have an issue with this button?
Thanks!

**Comment by khouloudbelguith** [comment]
@AntiGravitySports, thanks for these clarifications.
The order page will be migrated to Symfony so this button will be changed.https://github.com/PrestaShop/PrestaShop/issues/13878
As an example
The customer page
Before migration
![image](https://user-images.githubusercontent.com/16067358/63505201-043ca800-c4cb-11e9-9cb9-ce3fc60fa3d5.png)
After migration
![image](https://user-images.githubusercontent.com/16067358/63505223-1585b480-c4cb-11e9-9730-a82d5d004b64.png)

Thanks to check & feedback

**Comment by AntiGravitySports** [comment]
Currently our customer page show as following, how could we solve the problem of "Create the order"
![image](https://user-images.githubusercontent.com/54383614/63659775-dbc3ef00-c7e5-11e9-9607-225f9d4358bb.png)

**Comment by AntiGravitySports** [comment]
Hi Prestashop team,

 

Our customer page shows as following and I don’t know where is the problem, could you help me how to solve the problem of “Create the order”.

Thanks very much.

 



Best  Regards

Tina 

AntiGravitySports

http://www.antigravitysports.com/store/

Skype : tina.fu520

Phone: 0755-28435505-845

Address: 1108A Office, Block A ,Galaxy World, 1 Yabao Road, Longgang District, ShenZhen 

 

 

发件人: khouloudbelguith [mailto:notifications@github.com] 
发送时间: 2019年8月22日 17:54
收件人: PrestaShop/PrestaShop
抄送: AntiGravitySports; Mention
主题: Re: [PrestaShop/PrestaShop] Create new order but the button of "Create the order" is grey (#15213)

 

@AntiGravitySports <https://github.com/AntiGravitySports> , thanks for these clarifications.
The order page will be migrated to Symfony so this button will be changed.#13878 <https://github.com/PrestaShop/PrestaShop/issues/13878> 
As an example
The customer page
Before migration
 <https://user-images.githubusercontent.com/16067358/63505201-043ca800-c4cb-11e9-9cb9-ce3fc60fa3d5.png> image
After migration
 <https://user-images.githubusercontent.com/16067358/63505223-1585b480-c4cb-11e9-9730-a82d5d004b64.png> image

Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @AntiGravitySports,

You need to upgrade to the PrestaShop v1.7.6.0.
Your current version is PS1.6.1.23.
But, our Devs are improving the PS1.7.
The Customer Page is improved follwing those tickets:
https://github.com/PrestaShop/PrestaShop/issues/11010
https://github.com/PrestaShop/PrestaShop/issues/10560
For 1.6 project, 
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!
