### ISSUE TITLE
Unknown column 'a0.id_order' in ps_paypal_processlogger table

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#15217]
**Describe the bug**

Unable to open order datails payed by paypal.

`[PrestaShopDatabaseException]
Unknown column 'a0.id_order' in 'where clause'

SELECT *
FROM `ps_paypal_processlogger` a0
WHERE (a0.`id_order` = 1064)

at line 769 in file classes/db/Db.php
764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 613 - classes/db/Db.php] - [1 Arguments]
DbCore->executeS - [line 381 - classes/PrestaShopCollection.php] - [1 Arguments]
PrestaShopCollectionCore->getAll - [line 411 - classes/PrestaShopCollection.php]
PrestaShopCollectionCore->getResults - [line 68 - modules/paypal/vendor/ppbtlib/src/Extensions/ProcessLogger/ProcessLoggerExtension.php]
PaypalPPBTlib\Extensions\ProcessLogger\ProcessLoggerExtension->hookDisplayAdminOrderContentOrder - [line 96 - modules/paypal/vendor/ppbtlib/src/Module/PaymentModule.php] - [1 Arguments]
PaypalPPBTlib\Module\PaymentModule->handleExtensionsHook - [line 1921 - modules/paypal/paypal.php] - [2 Arguments]
PayPal->hookDisplayAdminOrderContentOrder - [line 1720 - modules/pagecache/pagecache.php] - [1 Arguments]
PageCache::execHook - [line 24 - override/classes/Hook.php] - [4 Arguments]
Hook::coreCallHook - [line 355 - classes/Hook.php] - [3 Arguments]
HookCore::callHookOn - [line 907 - classes/Hook.php] - [3 Arguments]
HookCore::exec - [line 1930 - controllers/admin/AdminOrdersController.php] - [2 Arguments]
AdminOrdersControllerCore->renderView - [line 2128 - classes/controller/AdminController.php]
AdminControllerCore->initContent - [line 291 - classes/controller/Controller.php]
ControllerCore->run - [line 387 - override/classes/Dispatcher.php]
Dispatcher->dispatch - [line 97 - admin/index.php]
[required] => 1 ) [recyclable] => Array ( [type] => 2 [validate] => isBool ) [gift] => Array ( [type] => 2 [validate] => isBool ) [gift_message] => Array ( [type] => 3 [validate] => isMessage ) [mobile_theme] => Array ( [type] => 2 [validate] => isBool ) [delivery_option] => Array ( [type] => 3 ) [secure_key] => Array ( [type] => 3 [size] => 32 ) [allow_seperated_package] => Array ( [type] => 2 [validate] => isBool ) [date_add] => Array ( [type] => 5 [validate] => isDate ) [date_upd] => Array ( [type] => 5 [validate] => isDate ) ) [classname] => Cart ) [update_fields:protected] => [force_id] => ) [altern] => 2 )
AdminOrdersControllerCore->renderView - [line 2128 - classes/controller/AdminController.php]
2123.         } elseif ($this->display == 'view') {
2124.             // Some controllers use the view action without an object
2125.             if ($this->className) {
2126.                 $this->loadObject(true);
2127.             }
2128.             $this->content .= $this->renderView();
2129.         } elseif ($this->display == 'details') {
2130.             $this->content .= $this->renderDetails();
2131.         } elseif (!$this->ajax) {
2132.             // FIXME: Sorry. I'm not very proud of this, but no choice... Please wait sf refactoring to solve this.
2133.             if (get_class($this) != 'AdminCarriersController') {
AdminControllerCore->initContent - [line 291 - classes/controller/Controller.php]
286.             if (!$this->content_only && ($this->display_header || (isset($this->className) && $this->className))) {
287.                 $this->initHeader();
288.             }
289. 
290.             if ($this->viewAccess()) {
291.                 $this->initContent();
292.             } else {
293.                 $this->errors[] = $this->trans('Access denied.', array(), 'Admin.Notifications.Error');
294.             }
295. 
296.             if (!$this->content_only && ($this->display_footer || (isset($this->className) && $this->className))) {
ControllerCore->run - [line 387 - override/classes/Dispatcher.php]
382.         try {
383.             $controller = Controller::getController($controller_class);
384.             if (isset($params_hook_action_dispatcher)) {
385.                 Hook::exec('actionDispatcher', $params_hook_action_dispatcher);
386.             }
387.             $controller->run();
388.             if (Module::isEnabled('pagecache') && $pagecacheInstance) {
389.                 $pagecacheInstance->displayStats(false, $pre_display_html);
390.             }
391.         } catch (PrestaShopException $e) {
392.             $e->displayMessage();
Dispatcher->dispatch - [line 97 - admin/index.php]
92.     if (!headers_sent()) {
93.         header('Content-Type: text/html; charset=utf-8');
94.     }
95. 
96.     // Prepare and trigger LEGACY admin dispatcher
97.     Dispatcher::getInstance()->dispatch();
98. }
`
**To Reproduce**
Install PS 1.7.6 , import order from old store, install paypal module official. 

Open an order with paypal payment result in this error.

But in old store there is no ps_paypal_processlogger table. In the new created database there is no ps_paypal_processlogger, installing again the paypal module does not create ps_paypal_processlogger table.

Need to manual createa the table and the 2 column a0 and id_order

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks to check with them & feedback

Best regards, Khouloud

**Comment by matteolavaggi** [comment]
Hi, myabe you or other dev team has better contact with paypal dev team than me. 

Its a module used by 100% of prestashop store, so i think is in your interest to contact paypal dev team and ask for a fix.

Feeel free to close this issue thanks.

For anyone found this issue, a workaround fix is simple create the table with no data, this result in no error:

![image](https://user-images.githubusercontent.com/24798703/63514875-e9c5f700-c4e9-11e9-8fb0-6cf4cc8e3d6d.png)

**Comment by khouloudbelguith** [comment]
@matteolavaggi, sorry but as I said before, it is not provided by PrestaShop Core, you need to contact them by your specific account on our MarketPlace Addons.

Thanks for your understanding!

**Comment by JulianC2** [comment]
@matteolavaggi  - Did you get any response from the developer - I am seeing the same issue while trying to get my prestashop up to date.
