### ISSUE TITLE
After Enabling "Free shipping" in the carriers page => the ranges shouldn't be emptied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15214]
**Is your feature request related to a problem? Please describe.**
In the BO => Shipping => Carriers page => after adding some Ranges to a specific carrier => when we enable the Free Shipping option, Ranges shouldn't be emptied
1. 
![carrier1](https://user-images.githubusercontent.com/16067358/63503014-97bfaa00-c4c6-11e9-8753-7cf1d53d72e6.jpg)
2. Enable Free shipping
![image021](https://user-images.githubusercontent.com/16067358/63503056-ac9c3d80-c4c6-11e9-86de-c55698c0fbc6.jpg)

It could be fixed with this
https://github.com/PrestaShop/PrestaShop/issues/10586

**Comment by khouloudbelguith** [comment]
Ping @colinegin, @marionf what do you think?

**Comment by ghost** [comment]
Hello @khouloudbelguith,
Is this the issue that Aurélien shared in an email he received from a merchant? (https://www.moonlight-boards.com)

**Comment by khouloudbelguith** [comment]
Hi @samuel-pires,

Yes!

**Comment by ghost** [comment]
Great! 
Thank you

**Comment by ghost** [comment]
## Specs

When enabling "Free Shipping", the content of the table should not be visible or editable, but it should be kept, so that if you disable "Free Shipping", the content is visible again in the table.

It avoids erasing all the content of the table if a user do a mistake by enabling Free Shipping.

**Comment by matks** [comment]
Please notice last infos on https://github.com/PrestaShop/PrestaShop/pull/28720#issuecomment-1312836059
