### ISSUE TITLE
Flags translation (New, Online only, On sale!) can't be translated

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15219]
In PS 1.7.5.2 and below to translate flags names (New, Online only, On sale!) we need to select Classic theme to translate them. Even if we use our own theme system can't find New, Online only, On sale! phrases.

In PS 1.7.6 even in above weird way we can't find and translate them.

![trans](https://user-images.githubusercontent.com/8243273/63518629-bdae7400-c4f1-11e9-9311-d2c3a62c5d69.jpg)

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

I did not mange to reproduce the issue with PS1.7.6.0 & the branch 1.7.6.x
I attached a screen record
https://drive.google.com/file/d/1Ie64NtUmljek3UY-CBWfVvK2oboDbkOl/view
Thanks to check & feedback

**Comment by ghost** [comment]
Thanks. I will check it!

**Comment by khouloudbelguith** [comment]
@PrestaShark, waiti,g for your feedback.

**Comment by Hlavtox** [comment]
The same issue as in my case #15075

@khouloudbelguith You did reproduce it on my ticket.

@eternoendless See? Product flags are another thing that is passed as a variable and cannot be translated.

**Comment by khouloudbelguith** [comment]
@Hlavtox, in your case, I could find some expression using the Classic Rocket theme & not the Classic theme.

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith But you did not find the expressions I told you about. You still don't understand.

- You cant translate breadcrumbs
- You can't translate product list headers.
- You can't translate many of strings in cart page
- You can't translate product list sort options
And many more

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks for your feedback.
@PrestaShark  Your ticket is a duplicate of #15075
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #15075
