### ISSUE TITLE
Prestashop 1.7.6.0 translation MX description disabled

### ISSUE THREAD

**Issue by alshira** [PrestaShop/PrestaShop#15218]
Version: Prestashop 1.7.6.0
Translation: MX
Module: Products
How reproduce the issue:
1) create a new product
2) try to add short description or long description, both fields disabled by css
3) atteched screenshot with evidence (css applied wrongly)
![Captura de pantalla de 2019-08-22 08-14-50](https://user-images.githubusercontent.com/21247436/63517883-7609f700-c4b5-11e9-99c8-24e495e51f4f.png)

**Comment by khouloudbelguith** [comment]
Hi @alshira,

I did not manage to reprouce the issue with PS1.7.6.0.
What is the exact language did you use during the install?
Is it a fresh install or an upgrade frol version?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @alshira,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
