### ISSUE TITLE
Add/Edit category problem

### ISSUE THREAD

**Issue by johanmeer** [PrestaShop/PrestaShop#15233]
Hi, after upgrade from 1.7.5 to 1.7.6 i'm not able to add/edit category's. Page is not as it should be and i'm getting an error in the log file: 

` Fri Aug 23 11:53:08.853733 2019] [proxy_fcgi:error] [pid 31792:tid 139849445115648] [client 62.194.59.29:58838] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php:801\nStack trace:\n#0 /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 /var/www/vhosts/***.nl/httpsdocs/classes/Notification.php(133): ToolsCore::displayPrice(26.88, Object(Currency), false)\n#2 /var/www/vhosts/***.nl/httpsdocs/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '14288')\n#3 /var/www/vhosts/***.nl/httpsdocs/admin152dmwx1f/ajax.php(125): NotificationCore->getLastElements()\n#4 {main}\n thrown in /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php on line 801\n', referer: https://www.***.nl/admin152dmwx1f/index.php/sell/catalog/categories/new?id_parent=2&_token=4-N6QgdPDyXiPEEOHV8V2cxSr10iImvXENTf9uY-NG0`

![Schermafbeelding 2019-08-23 om 12 17 23](https://user-images.githubusercontent.com/47300140/63585719-0d4b7900-c5a0-11e9-9670-2fd558561086.png)

Is there anybody that is familier with this problem?

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Thanks for your report.
The category page is migrated to Symfony.
Have you any disabled category which is not displayed in the "Parent category" section?

Thanks!

**Comment by johanmeer** [comment]
Hi @khouloudbelguith, i'm not sure what you meaning, how can i see that?

**Comment by khouloudbelguith** [comment]
@johanmeer, do you have any category disabled in your case?
When you try to add a new category under the Category Home => OK or not?

Thanks!

**Comment by johanmeer** [comment]
hi @khouloudbelguith that is working, editor is not working yet on categorie page. It seems that this error is appearing on multiple occasions, is there a way to solve and do you think that this has a relation to the editor?

`Fri Aug 23 11:53:08.853733 2019] [proxy_fcgi:error] [pid 31792:tid 139849445115648] [client 62.194.59.29:58838] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php:801\nStack trace:\n#0 /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 /var/www/vhosts/***.nl/httpsdocs/classes/Notification.php(133): ToolsCore::displayPrice(26.88, Object(Currency), false)\n#2 /var/www/vhosts/***.nl/httpsdocs/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '14288')\n#3 /var/www/vhosts/***.nl/httpsdocs/admin152dmwx1f/ajax.php(125): NotificationCore->getLastElements()\n#4 {main}\n thrown in /var/www/vhosts/***.nl/httpsdocs/classes/Tools.php on line 801\n', referer: https://www.***.nl/admin152dmwx1f/index.php/sell/catalog/categories/new?id_parent=2&_token=4-N6QgdPDyXiPEEOHV8V2cxSr10iImvXENTf9uY-NG0`

**Comment by khouloudbelguith** [comment]
@johanmeer, if you add in a new category under the Home category & you try to edit it?
Is it working in this case?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
