### ISSUE TITLE
Add states to India

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15234]
**Is your feature request related to a problem? Please describe.**
It is not a bug, but a default parameter to update.

**Describe the solution you'd like**
In International > Locations > States, there must be all Indian states by default since it is one of the countries whose address format requires states for deliveries. Yet there are not mentioned. So here are the states and ISO codes needed to correct this situation, let me know if it lacks information.

Andhra Pradesh (IN-AP)
Arunachal Pradesh (IN-AR)
Assam (IN-AS)
Bihar (IN-BR)
Chhattisgarh (IN-CT)
Goa (IN-GA)
Gujarat (IN-GJ)
Haryana (IN-HR)
Himachal Pradesh (IN-HP)
~~Jammu and Kashmir (IN-JK) - we must be careful with this state, right now its situation is pretty complicated since the territory is disputed between India and Pakistan~~
Jharkhand (IN-JH)
Karnataka (IN-KA)
Kerala (IN-KL)
Madhya Pradesh (IN-MP)
Maharashtra (IN-MH)
Manipur (IN-MN)
Meghalaya (IN-ML)
Mizoram (IN-MZ)
Nagaland (IN-NL)
Odisha (IN-OR)
Punjab (IN-PB)
Rajasthan (IN-RJ)
Sikkim (IN-SK)
Tamil Nadu (IN-TN)
Telangana (IN-TG)
Tripura (IN-TR)
Uttar Pradesh (IN-UP)
Uttarakhand (IN-UT)
West Bengal (IN-WB)

**Where?**

https://github.com/PrestaShop/PrestaShop/tree/develop/localization
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/state.xml

**Comment by Progi1984** [comment]
@LouiseBonnard For the "Jammu and Kashmir", do i add it or not ? Thanks for your answer.

**Comment by LouiseBonnard** [comment]
Hi @Progi1984, this region is currently under an Indian reorganization act that will come into effect on Octobre 31st. And the effect is its division into two parts: Jammu and Kashmir on the one hand, and Ladakh on the other hand. Perhaps we should wait until this date to be sure?

**Comment by Progi1984** [comment]
Hi @LouiseBonnard, No problem for this date (I was afraid by the feature freeze). Could you give me new names & ISO codes for these new territories ?

**Old :** Jammu and Kashmir (IN-JK)

**Comment by LouiseBonnard** [comment]
I will as soon as it is enacted, it is not available for now. :-)

**Comment by LouiseBonnard** [comment]
Hi @Progi1984, the formerly one state **Jammu and Kashmir** has been divided into two union territories (**Jammu and Kashmir** and **Ladakh**) and union territories are not referred to as states in PrestaShop, so you can forget about those two. :-)
