### ISSUE TITLE
Rename ecotax everywhere in PS

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15246]
"Ecotax" wording isn't clear because it's not really a tax but a participation
Maybe we can rename it "eco-participation" in English ?

**Comment by LouiseBonnard** [comment]
It is a bit touchy, it looks like the right word for all the green taxes established around the world is 'Ecotax'. Does this wording only concerns the French éco-participation or is it supposed to apply to other kinds of (foreign) environmental taxes?

**Comment by marionf** [comment]
Yes, it's supposed to apply to other kinds of environmental taxes
