### ISSUE TITLE
'PS_layered_filter_block' doesn't exist

### ISSUE THREAD

**Issue by johnndunbar** [PrestaShop/PrestaShop#15247]
Hi,

Since I updated from 1.6 to 1.7 its a nightmare.
I don't have a lof of module (only paiement and transport), and no design.
And I keep having bugs !
The last one :
Table '***.ps_layered_filter_block' doesn't exist<br /><br /><pre>TRUNCATE TABLE ps_layered_filter_block

It happened when I try to click on the category of the product. 
Nothing can be load and I have got this error.

I can't find any other similar exemple on forum. If any one can help me it will be great.
Also should I re-install the update ?
On the update panel, prestahsop tell me my PHP version is obsolete  ?

Thanks

**Comment by gotthardsen** [comment]
What was your solution? I got the same problem updating from 1.7.5 to 1.7.6 but can't find any docs for that table

**Comment by gabriele-carbonai** [comment]
Hello @gotthardsen 
Upgrade the module Faceted search, it will be install layered_* tables.

**Comment by ibrahimfsasmaz** [comment]
hello,
I have the same error but the Faceted search does not upgrade, I am having the error message below


×
Error!
Cannot upgrade module ps_facetedsearch. Unfortunately, the module did not return additional details.


How can I fix it pls ?

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/16795

**Comment by shnslmz** [comment]
BTW,
You can solve this issue, by doing "reset this module" basically.
