### ISSUE TITLE
modern email theme cannot be activated within 1.7.6

### ISSUE THREAD

**Issue by yuxiayuzhou** [PrestaShop/PrestaShop#15251]
**Describe the bug**
Updated from 1.7.5.1 to 1.7.6 about 1 month ago. But I realised im still using the classic email template not the latest modern ones. Im using classic theme should has both modern and classic email templates. I have conducted following steps to acheive this, but seems not working.
**To Reproduce**

1. Go to 'Design'
2. Click on 'Email Themes'
3. Select "Select your default email theme" as "modern"
4. Select "Select your email theme" as "modern"
5. Select your language "English"
6. Select the theme you want to overwrite "classic"
7. Overright templates "Yes"
8. "Successfully overwrote email templates for theme modern with locale en" pops out
9. Click ‘improve" then "modules" then ’module manager" then "Emails Templates Manager".
10. Click "Configure" which shows the current template is still "Classic"

 

**Screenshots**
screenshots provided for reference. If any further info required, please dot hesitate to let me know. Thanks for your generous works. 

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A
![screenshot reference](https://user-images.githubusercontent.com/53670538/63632394-30058c80-c689-11e9-9f80-ce5b2756c8d2.jpg)

**Comment by yuxiayuzhou** [comment]
one more image provided for reference. In this screenshot, it shows the current template is still classic one but not the modern one. Thank you.

![email templates manager](https://user-images.githubusercontent.com/53670538/63643538-aad0b500-c726-11e9-8dcd-1579df9e8517.jpg)

**Comment by MathiasReker** [comment]
@yuxiayuzhou you are overriding email templates with a module. Try to uninstall email template manager, that should fix your issue.

**Comment by khouloudbelguith** [comment]
Hi @yuxiayuzhou,

Here's a demo module https://github.com/jolelievre/tuto_mailtemplate, you can check it.
It is a Tutorial for Mail Template in PrestaShop
Thanks to check & feedback.

**Comment by yuxiayuzhou** [comment]
> @yuxiayuzhou you are overriding email templates with a module. Try to uninstall email template manager, that should fix your issue.

Thanks, Mathias. I would have interests to give it a try. Last night i just manually removed the "powered by Prestashop" footer MANUALLY. Do you think if i uninstall the email template manager and reinstall, would it bring the footer back? Thank you.

**Comment by yuxiayuzhou** [comment]
> Hi @yuxiayuzhou,
> 
> Here's a demo module https://github.com/jolelievre/tuto_mailtemplate, you can check it.
> It is a Tutorial for Mail Template in PrestaShop
> Thanks to check & feedback.

Thanks for the recommentation. I tried to install the module. Unfortunately it came with an error. The screenshot can be seen in attachement. thanks again for your generous work.
![error](https://user-images.githubusercontent.com/53670538/63680950-d21fa300-c848-11e9-97f1-b42295506919.jpg)

**Comment by khouloudbelguith** [comment]
@yuxiayuzhou, your memory limit is 1G => Invalid value.
unfortunately, we are aware of this issue and it does not come from Prestashop, see https://github.com/PrestaShop/PrestaShop/pull/10892#issuecomment-439097520

**Comment by yuxiayuzhou** [comment]
> @yuxiayuzhou, your memory limit is 1G => Invalid value.
> unfortunately, we are aware of this issue and it does not come from Prestashop, see [#10892 (comment)](https://github.com/PrestaShop/PrestaShop/pull/10892#issuecomment-439097520)

Thanks for pointing me to the solution. The issue now has been solved together with the server support. It has been set to 128MB instead of 1G before. so It is all right to upload file/module now. 
I downloaded the Tutorial for Mail Template as a zip file. May i know how to install this properly? I have access to FTP folder as well. Just dot know how to operate further. Thank you.

**Comment by khouloudbelguith** [comment]
@yuxiayuzhou, you are welcome!
You can follow this Readme file
https://github.com/jolelievre/tuto_mailtemplate#install
You can download this zip file also
[tuto_mailtemplate.zip](https://github.com/PrestaShop/PrestaShop/files/3541093/tuto_mailtemplate.zip)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @yuxiayuzhou,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by superskyman100** [comment]
Hello,

I have the same issue.

The tuto_mailtemplate.zip leads nowhere, i've installed on my prestashop, just an empty screen...

![image](https://user-images.githubusercontent.com/60083930/73136408-4379b100-4088-11ea-89a5-1f02cc00b0a9.png)

...

**Comment by khouloudbelguith** [comment]
Hi @superskyman100, This issue is currently closed, can you open a new one with more information about your configuration

Thanks!

**Comment by Webteyazilim** [comment]
Why not templates appear in warning emails?
