### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#15258]
Hello!
I am trying to migrate my Prestashop 1.7.6.0 shop to a new server and I have followed the following steps:
1. Compress files to .tgz from source server
2. Database dump from source server (mariadb)
3. Copied tgz file to destiny server
4. Created new database (mariadb) in destiny server with same credentials as source server
5. Extracted files from tgz file in destiny server
6. Checked & modified in file /app/config/parameters.php

As soon as I try to access Backoffice I get the following error:

InvalidArgumentException - Cache key must be string, "NULL" given

I have tried so many times and checked various internet sources but I cannot still find solution. It is my first time migrating and I do not know what is happening. Any help please?
[error.pdf](https://github.com/PrestaShop/PrestaShop/files/3540555/error.pdf)

**Comment by khouloudbelguith** [comment]
Hi @demperador,

Thanks to follow these steps to move your shop to a new server without errors.
1. I made a backup for my files & my database
2. I uploaded my store's files to your new server
3. I imported the old store's database to the new server
4. In file /app/config/parameters.php, I configured my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in the Table ps_shop_url, I changed with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. I cleared cache manually by deleting all the folder into var/cache (prod & dev).

Thanks to check & feedback.

**Comment by demperador** [comment]
Hello @khouloudbelguith I have done all those steps and still the same error. On step 5, I do have a multistore site but shops' URL are the same. Domain centrobell.com DNS A value is already directing to the right IP address. Meanwhile, if I try to access frontoffice, the error is: ContextErrorException - Notice: Undefined index: pl_grid_ld. But I cannot access Backoffice because of the error in the issue's main topic.

**Comment by khouloudbelguith** [comment]
@demperador, did you tried to clear the cache?

Thanks!

**Comment by demperador** [comment]
Yes I did, several times.

**Comment by demperador** [comment]
If I made a fresh install of prestashop as a test it seems to function correctly but as soon as I tweak the parameters.php, clear cache and upload my database, error happens

**Comment by khouloudbelguith** [comment]
@demperador, did you use a custom module or custom theme?
Could you please try to delete the file into `/Project_Folder/config/thmes/yourtheme/shop.json`, check & feedback.
Thanks!

**Comment by demperador** [comment]
Hello @khouloudbelguith I have managed to fix the problem. I think the problem is because of an incompatibility issue of MariaDB 10.3+ under Plesk Onyx 17.8.11 Update #65. However, now another issue I have is that Prestashop states that I must activate mod_auth_basic for webservices. Under my Apache server general settings it seems that the module is already installed.

**Comment by khouloudbelguith** [comment]
@demperador, you have an alert about the `mod_auth_basic` in the BO => Advanced Parameters => webservice page ?

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith exactly. I do not know why and I have been looking for this for 2 days straight 😅

**Comment by khouloudbelguith** [comment]
@demperador, In my case, I don't have this alert with PS1.7.6.0 after upgrade from PS1.7.5.2.
>Please activate the 'mod_auth_basic' Apache module to allow authentication of PrestaShop's webservice.
![image](https://user-images.githubusercontent.com/16067358/63774232-b8c43880-c8d4-11e9-909c-733b4c6210f9.png)

Could you please try to create this test.php script on your server to check if the `mod_auth_basic` is enabled

```
<?php
print_r(apache_get_modules());
?>
```

In my case, => OK

`Array ( [0] => core [1] => mod_so [2] => mod_watchdog [3] => http_core [4] => mod_log_config [5] => mod_logio [6] => mod_version [7] => mod_unixd [8] => mod_access_compat [9] => mod_alias [10] => mod_auth_basic [11] => mod_authn_core [12] => mod_authn_file [13] => mod_authz_core [14] => mod_authz_host [15] => mod_authz_user [16] => mod_autoindex [17] => mod_deflate [18] => mod_dir [19] => mod_env [20] => mod_filter [21] => mod_mime [22] => prefork [23] => mod_negotiation [24] => mod_instaweb [25] => mod_php7 [26] => mod_reqtimeout [27] => mod_rewrite [28] => mod_setenvif [29] => mod_status )`

**Comment by demperador** [comment]
@khouloudbelguith I created a file name test.php with the code in it and I get a 500 error.
![Captura de pantalla 2019-08-27 a las 14 18 47](https://user-images.githubusercontent.com/31283004/63774649-9f6fbc00-c8d5-11e9-84fc-aff84e9c3d0b.png)

**Comment by khouloudbelguith** [comment]
@demperador, thanks to check with this script.
[aut.php.txt](https://github.com/PrestaShop/PrestaShop/files/3546288/aut.php.txt)

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith just checked at (centrobell.com/aut.php.txt) and it only displays the php code.

**Comment by khouloudbelguith** [comment]
@demperador, you need to rename `aut.php.txt` to `aut.php` & check.
With GitHub, we cannot attach a PHP file.

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith same result, error 500

**Comment by khouloudbelguith** [comment]
@demperador, could you please check the issue with your host.
With this script, we are just checking the list of apache modules that are enabled on the server.

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith I am starting to think that the problem might be a php setting not properly defined. Is there any guide on which are the exact settings for php 7.2 and apache 2.4 that are recommended for prestashop 1.7.6.1? Thanks.

**Comment by khouloudbelguith** [comment]
@demperador,

You can follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith yes, I have uploaded that file phppsinfo but I cannot load neither because it asks for user/pass which I set as prestashop/prestashop but it will not accept the authorization. Perhaps it is related with the issue of the mod_auth_basic

**Comment by khouloudbelguith** [comment]
@demperador, following this file:
try to delete those lines 
```
if (!empty($_SERVER['PS_INFO_LOGIN'])) {
            $this->login = $_SERVER['PS_INFO_LOGIN'];
        }
        if (!empty($_SERVER['PS_INFO_PASSWORD'])) {
            $this->password = $_SERVER['PS_INFO_PASSWORD'];
        }
```


Thanks!

**Comment by demperador** [comment]
@khouloudbelguith it will not load. It keeps asking for user/pass. I also tried setting public function __construct($login = self::prestashop, $password = self::prestashop) and afterwards the page receives a 500 error…

**Comment by khouloudbelguith** [comment]
@demperador, could you please try with this file
[aindex.php.zip](https://github.com/PrestaShop/PrestaShop/files/3546889/aindex.php.zip)
Thanks!

**Comment by demperador** [comment]
@khouloudbelguith it does load! https://centrobell.com/aindex.php

**Comment by khouloudbelguith** [comment]
@demperador, 
>Is there any guide on which are the exact settings for php 7.2 and apache 2.4 that are recommended for prestashop 1.7.6.1

=> It is OK => Done.

But about the main issue "check if mod_auth_basic is enabled".
You need to check with this 
```
<?php
print_r(apache_get_modules());
?>
```

**Comment by demperador** [comment]
@khouloudbelguith I have change the PHP setting to display error and this is the result for the previous code: Fatal error: Uncaught Error: Call to undefined function apache_get_modules() in /var/www/vhosts/centrobell.com/httpdocs/aut.php:2 Stack trace: #0 {main} thrown in /var/www/vhosts/centrobell.com/httpdocs/aut.php on line 2

**Comment by khouloudbelguith** [comment]
@demperador, Could you please try to create a check_phpinfo.php file and Write this PHP Code:

```
<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>
```
Then Navigate to Url like `www.example.com/check_phpinfo.php` and It will show you PHP file in the server

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith I did already have a phpinfo.php uploaded. It has always been visible at centrobell.com/phpinfo.php. I do not understand why all other files has been difficult to load…

**Comment by khouloudbelguith** [comment]
@demperador, in the phpinfo file, you can check that the mod_auth_basic is not displayed.
In my case
![image](https://user-images.githubusercontent.com/16067358/63786721-7d346900-c8ea-11e9-84dc-3ca27478e00e.png)
It is not displayed in your case
![image](https://user-images.githubusercontent.com/16067358/63786777-9b01ce00-c8ea-11e9-8538-45c1fde79d25.png)

Thanks!

**Comment by demperador** [comment]
@khouloudbelguith I see the difference but I do not know how to solve the issue. It also seems that my server is running as FPM/FastCGI as server API and not as Apache 2 Handler. I do not know how to load the modules…

**Comment by khouloudbelguith** [comment]
@demperador, 
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I close the issue, feel free to open a new one when needed.
Thanks!
