### ISSUE TITLE
Orders Shopping > Carts > Online (Yes / No) Bug

### ISSUE THREAD

**Issue by lowfear** [PrestaShop/PrestaShop#15267]
Not correct show "Online" column. 

Bug are in SQL query
/PrestaShop/controllers/admin/AdminCartsController.php 58 Line
need remove "LIMIT 1"

**Screenshots**
![download](https://user-images.githubusercontent.com/1003459/63719042-b7532b80-c854-11e9-8ad1-d9b12fbc9801.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @lowfear,

Thanks for your report.
Ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think?
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9076 about this SQL query.

Thanks!

**Comment by PierreRambaud** [comment]
Oh my bad, really sorry for the delay and sorry for introduced this bug :sweat: 
I create a pull request to fix it.
