### ISSUE TITLE
Fixed a little css bug around .product-flags

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15260]
Hi
if you pass the mouse over a product block when there are some flags on the image, it is not possible to click over the image.
It is due from this code in theme.css

`.product-flags {
    width: 100%;
}`

to fix it it is necessary to use this code

`.product-flags {
    width: auto;
}`

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/63685531-e25f6000-c7ff-11e9-94d4-c4a2ff929d4b.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,
Yes, I manage to reproduce the issue with PS1.7.6.0 & PS1.7.6.1build1.
>if we pass the mouse over a product block when there are some flags on the image, it is not possible to click over the image.

https://drive.google.com/file/d/14Hg_LZpw3IkrGyP7u8QLb_0KbPnxqp9h/view
With PS1.7.5.2 => OK

>if we pass the mouse over a product block when there are some flags on the image, it is possible to click over the image.

https://drive.google.com/file/d/1uR4mnX2d-rXb5aWkK_O_4VnCHGWYg1BB/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by ghost** [comment]
Thanks @maofree !

**Comment by ghost** [comment]
Be careful, this solution has an impact on "Web only" labels.


![Capture d’écran 2019-08-30 à 11 11 27](https://user-images.githubusercontent.com/47456895/64009522-4d6aa880-cb18-11e9-8274-2da27a9026f6.png)
![Capture d’écran 2019-08-30 à 11 11 46](https://user-images.githubusercontent.com/47456895/64009529-4e9bd580-cb18-11e9-86c7-bb8503ad4678.png)

**Comment by colinegin** [comment]
Hello,

will this issue be fixed for 1.7.6.2 ?

Thanks !

**Comment by matks** [comment]
> Hello,
> 
> will this issue be fixed for 1.7.6.2 ?
> 
> Thanks !

Work is ongoing on PR https://github.com/PrestaShop/PrestaShop/pull/15265 but if you wish to ship this in 1.7.6.2, I guess we can give a hand to @samuel-pires 😉

**Comment by ghost** [comment]
@matks yep please 🙏 

We talked about it with @Progi1984 2 weeks ago. But not anymore since then.

**Comment by ghost** [comment]
I guess the best is to create a new PR and close mine

**Comment by Progi1984** [comment]
Sorry, I completly forgot. @matks As you want ;) I have some time for fixing this bug, if you want.

**Comment by matks** [comment]
> Sorry, I completly forgot. @matks As you want ;) I have some time for fixing this bug, if you want.

As I am a very weak front developer, I will not be able to solve this bug 😅 so yes, if you can help, please do @Progi1984

**Comment by micka-fdz** [comment]
Hello, to properly fix this bug, you can add `pointer-events: none;` to `.product-flags`.
I did that on all my projects :)

**Comment by Progi1984** [comment]
Fixed by #15930
