### ISSUE TITLE
[ps_facetedsearch] Bug in order by 'position' in category

### ISSUE THREAD

**Issue by lowfear** [PrestaShop/PrestaShop#15278]
**Describe the bug**
If are enabled "Show products from subcategories" sort don't work correctly, because sort by position in all categories nleft and nright. But need sort just by current category.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

** SQL Example **

*If id_category = 7*

Current SQL are:

`SELECT p.id_product FROM (
	SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position 
	FROM ps_product p 
	LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND 0 = sa.id_product_attribute  AND sa.id_shop_group = 1  AND sa.id_shop = 0 ) 
	INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) 
	INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) 
	INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) 
	WHERE p.visibility IN ('both', 'catalog') AND c.nleft>=3 AND c.nright<=224 AND ps.id_shop='1' GROUP BY p.id_product
) p 
INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) 
GROUP BY p.id_product 
ORDER BY p.position ASC LIMIT 0, 12`

Posible Fix:

`SELECT p.id_product FROM (
	SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position 
	FROM ps_product p 
	LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND 0 = sa.id_product_attribute  AND sa.id_shop_group = 1  AND sa.id_shop = 0 ) 
	INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product AND cp.id_category = 7) 
	INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) 
	INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) 
	WHERE p.visibility IN ('both', 'catalog') AND c.nleft>=3 AND c.nright<=224 AND ps.id_shop='1' GROUP BY p.id_product
) p 
INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) 
GROUP BY p.id_product 
ORDER BY p.position ASC LIMIT 0, 12`

**Comment by khouloudbelguith** [comment]
Hi @lowfear,

Isn't the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/15062
Here's the PR: https://github.com/PrestaShop/ps_facetedsearch/pull/125 to fix the issue.
Thanks to check & feedback.

**Comment by PierreRambaud** [comment]
Should have been fix with the latest release.

**Comment by khouloudbelguith** [comment]
@lowfear, did you tried with ps_facetedsearch v3.2.1?
Thanks to check & feedback.

**Comment by lowfear** [comment]
> @lowfear, did you tried with ps_facetedsearch v3.2.1?
> Thanks to check & feedback.

Yes, fixed in 3.2.1

**Comment by khouloudbelguith** [comment]
@lowfear, great!
I close the issue, feel free to open a new one when needed.

**Comment by kreare** [comment]
In 4.0.1 the bug is still (or again) present.
