### ISSUE TITLE
Translate mail templates fail

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#15275]
**Describe the bug**
I'm trying to translate mail templates and after I change something in html text I get 403 Forbidden access.

**To Reproduce**
1. Go to International->Translations
2. Select Email translations->Body->Core->language (Greek in my view)
3. Select an email template change something 
4. Hit save

**Additional information**
PrestaShop version: 1.7.61
PHP version: 7.1.31

**Comment by khouloudbelguith** [comment]
Hi @sotirisa,

I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1VM-_j7aYIRVAuFRpotpANiApoZWQEV5u/view
The user might not have the necessary permissions for a resource.
Thanks to check the permissions with your host & feedback.

thanks!

**Comment by sotirisa** [comment]
Yes it was host problem I solve it.
Thank you!

**Comment by khouloudbelguith** [comment]
@sotirisa, thanks for your feedback.
Feel free to open a new one when needed.

**Comment by moi12fre** [comment]
Hi! What do you mean with i was a host problem? @sotirisa I'm having the same issue
