### ISSUE TITLE
Activate the Apache module 'mod_auth_basic' to allow authentication of the PrestaShop webservice.

### ISSUE THREAD

**Issue by lordchukz** [PrestaShop/PrestaShop#15283]
Can somebody please help with this?

Error: Activate the Apache module 'mod_auth_basic' to allow authentication of the PrestaShop webservice.

I also checked the database sql for Apache error I was getting, ’mod_auth_basic’.

And got this result, can you detect something from this?

“SELECT wa.`id_webservice_account`, wa.`key`, wa.`description`, wa.`active` FROM ps9m_webservice_account wa INNER JOIN ps9m_webservice_account_shop was ON was.`id_webservice_account` = wa.`id_webservice_account` WHERE was.`id_shop` IN (‘1') GROUP BY wa.`id_webservice_account` ORDER BY wa.`id_webservice_account` asc LIMIT 50 OFFSET 0"

Contacted host and the confirmed it was installed with the following:

Upon investigation, we are seeing it is installed as evidenced below. We have not changed that in any way and it still shows as loaded.

It is possible the restoration of the site might be using invalid httpd 2.2 vs httpd 2.4 versions of the directive in the .htaccess.

https://www.prestashop.com/forums/topic/871412-ps-1741-apache-22-wrong-htaccess-mod_auth-is-white-spacecase-sensitive/
/home/lords/public_html/.htaccess
# WebPGenerator Module - Do not edit
# Apache 2.2

Allow from all

# Apache 2.4

Require all granted
allow from all

See the below references as well.
https://www.nmsu.edu/manual/mod/mod_auth_basic.html
https://httpd.apache.org/docs/2.4/mod/mod_auth_basic.html

[root@server:/root]$ httpd -v
Server version: Apache/2.4.41 (cPanel)
Server built: Aug 20 2019 17:10:23
[root@server:/root]$

[root@server:/etc/apache2]$ grep -Er 'mod_auth_basic|auth_basic_module' /etc/apache2
/etc/apache2/conf.modules.d/035_mod_auth_basic.conf:# Enable mod_auth_basic
/etc/apache2/conf.modules.d/035_mod_auth_basic.conf:LoadModule auth_basic_module modules/mod_auth_basic.so
[root@server:/etc/apache2]$

[root@server:/root]$ httpd -M |grep auth
auth_basic_module (shared) <<< is the same as mod_auth_basic
authn_core_module (shared)
authn_file_module (shared)
authz_core_module (shared)
authz_dbd_module (shared)
authz_dbm_module (shared)
authz_groupfile_module (shared)
authz_host_module (shared)
authz_owner_module (shared)
authz_user_module (shared)
[root@server:/root]$

1. Go to Webservice and the error appears on top. see attached image.

**Screenshots**
![Screen Shot 2019-08-28 at 09 38 50](https://user-images.githubusercontent.com/36967295/63835438-b830ae00-c977-11e9-9b3c-bafb46e1c77c.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: php 7.2

**Comment by khouloudbelguith** [comment]
Hi @lordchukz,

Could you please try to create a check_phpinfo.php file and Write this PHP Code:

```
<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>
```
Then Navigate to Url like `www.example.com/check_phpinfo.php` and It will show you PHP file in the server

Thanks!

**Comment by khouloudbelguith** [comment]
@lordchukz, according to this comment: https://github.com/PrestaShop/PrestaShop/issues/15270#issuecomment-527176800
Your issue is solved?

Thanks!

**Comment by lordchukz** [comment]
Exactly, 

Thanks.

**Comment by khouloudbelguith** [comment]
@lordchukz, it is OK?
Thanks!

**Comment by lordchukz** [comment]
@khouloudbelguith yes site is working perfectly fine now. Thanks.

**Comment by khouloudbelguith** [comment]
@lordchukz, Great!
I close the issue, feel free to open a new one when needed.

**Comment by cins06** [comment]
Hello, I have the same problem ! i have a question where i create this file to try :  check_phpinfo.php file and Write this PHP Code:

<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>
Then Navigate to Url like www.example.com/check_phpinfo.php and It will show you PHP file in the server


Thank you soo much

**Comment by khouloudbelguith** [comment]
Hi @cins06,

Thanks to follow this link: https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page

Thanks!

**Comment by cins06** [comment]
Hello,
i have a problem i don't find this (/var/www/vhosts/example.com/httpdocs/)
...My problem is already Vous devez activer le module Apache
'mod_auth_basic' afin de permettre l'authentification au service web.

can you help me ?
Thank
Cindy

Le mar. 24 déc. 2019 à 16:02, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
Hi @cins06,

Issue fixed in the PS1.7.6.2 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15731

Thanks!

**Comment by cins06** [comment]
Bonjour,

J'ai essayé de réaliser la mise à jour mais j'ai un soucis :
J'ai créé mon dossier old j'ai mis tout dedans sauf
c:\wamp64\www\prestashop qui ne veut pas se mettre dedans ...
Comment cela se fait il ?

 Merci de votre aide

Le lun. 30 déc. 2019 à 14:43, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
Hi @cins06,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
