### ISSUE TITLE
Compile Error: Cannot declare class MailAlert, because the name is already in use

### ISSUE THREAD

**Issue by taniacr** [PrestaShop/PrestaShop#15282]
After updating to 1.7.6.1 can't access Module Manager and Translations, in Backoffice.
Gives Error:
Compile Error: Cannot declare class MailAlert, because the name is already in use

Also the Module Catalog page doesn't load any modules.
![imagem](https://user-images.githubusercontent.com/5993331/63814370-89d7b200-c928-11e9-8254-82fcf5d9ec3e.png)

PHP 7.1.31

**Comment by Nor01** [comment]
How do you fixed this issue?

**Comment by matks** [comment]
My guess is that there was twice the module MailAlert in the shop (and it fails when it finds twice the same class) probably a new one and an old one. Removing the old solves the problem.

**Comment by jmirasolswg** [comment]
I agree with @matks. It is possible that the old modules/mailalerts still remained (or was accidentally copied back for some reason) in the modules folder after the upgrade. For 1.7, the email module should be modules/ps_emailalerts. When you activate either one while the two modules exist inside the modules/ folder, the issue will occur when you access the Module Manager and/or Translations in the Back Office.
