### ISSUE TITLE
page validation not working

### ISSUE THREAD

**Issue by Nisarg22** [PrestaShop/PrestaShop#15281]
when trying to buy a product through cod method it show this problem 
whats the solution
![Screenshot (6)](https://user-images.githubusercontent.com/39002772/63804036-db396e80-c933-11e9-852e-14b4a5dd3952.png)

**Comment by khouloudbelguith** [comment]
Hi @Nisarg22,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Nisarg22,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
