### ISSUE TITLE
1-Click Upgrade configuration ends up with Error 500

### ISSUE THREAD

**Issue by Tom1884it** [PrestaShop/PrestaShop#15292]
**Describe the bug**
Trying to upgrade to latest PS version, I correctly installed 1-Click Upgrade module.
When I click "Configure", to configure the module, after a long wait, browser ends up with this error:
"500 Internal Server error
Request Timeout
This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'."

Support tells me to hint this to you: "I checked your shop, and it could be related to the write permission check of your shop. You may forward this information to help the core team to fix this issue on environments with low IOPS."

**Additional information**
PrestaShop version: 1.6.1.13
1-Click Upgrade module versione: 4.9.0
PHP version: 7.0

Thx you

**Comment by khouloudbelguith** [comment]
Hi @Tom1884it,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in adminfolder/autoupgrade/tmp/log.txt

Thanks!

**Comment by Tom1884it** [comment]
@khouloudbelguith thanks you for quick feedback.

That log.txt exists but it's empty.

Edit - 
PS.: I notice now that "Advanced Parameters > Configuration information" menu link have the same 500 error.

**Comment by khouloudbelguith** [comment]
@Tom1884it, this issue occurs before or after the upgrade?
Your PrestaShop version is still 1.6.1.13.
Thanks!

**Comment by Tom1884it** [comment]
@khouloudbelguith before. 
I'm still on 1.6.1.13: I installed Autoupdate module (4.9.0) to upgrade to PS 1.7.x, but can't configure it, like said before.

**Comment by khouloudbelguith** [comment]
@Tom1884it, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Tom1884it** [comment]
@khouloudbelguith 

> * server setup and configuration
Apache | 2.4.41
PHP | 5.6.40 or 7.0 (checking...)
MySQL | 10.3.17-MariaDB-cll-lve
Architettura | x86_64
Sistema operativo | linux

> * debug mode report
Any report, it timeouts.

> * PHP error logs
Can't find /var dir.
> * apache error log
Can't find /var dir.
> * javascript console log
Empty.

Anything by "define('_PS_MODE_DEV_', true)", too.

I just click on configuration of module and, after many seconds, it ends up with 500 error.
[Same behavior for "Advanced Parameters > Configuration information"]

**Comment by khouloudbelguith** [comment]
@Tom1884it, could you please try to increase the `max_execution_time` & the `memory_limit` on your server.
I hope this helps you to solve your issue.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
