### ISSUE TITLE
Faceted Search by N cateogry levels

### ISSUE THREAD

**Issue by karilobre** [PrestaShop/PrestaShop#15295]
**Describe the bug**
Hi, I’ve installed Prestashop 1.7.5.2. I’ve configurated the faceted search by Categories, the store has 3 category levels. 
When I choose to see the products of the level 1 category the filter shows all subcategories of level 2 and 3 that belong to the selected Category level 1. 
So, if I filter by level 2 category the filter works fine but the problem is that if I filter by level 3 category the filter doesn’t work. Then if I choose to see products of one level 2 category the filter shows all level 3 subcategories that belong to the selected category and if I filter by one level 3 category the filter works fine.
I’ve researched how works the Faceted search and it only filter by the immediate next category level, that is why in level 1 the filter doesn’t work for level 3 categories. 
What I need is to know how I can modify the query that shows the categories. The filter only must show the   immediate next category level

The faceted search doesn’t work for 3 or more Category levels. In the level one the filter shows all subcategories of level 2 and 3 and …. N that belong to the selected Category level 1 but only filter by the immediate next category level so it seems like the filters doesn’t work.

**To Reproduce**
1. Go to Vertical Menu
2. Click on any Category
3. Scroll down to filter by Categories
4. Choose one category to filter
5. See the error, nothing happens

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @karilobre,

>Hi, I’ve installed Prestashop 1.7.5.2. I’ve configurated the faceted search by Categories

What is the exact version of the module ps_facetedsearch did you use?

>When I choose to see the products of the level 1 category the filter shows all subcategories of level 2 and 3 that belong to the selected Category level 1.

In the ps_facetedsearch configuration, we have an option "Show products from subcategories" => you can disable it.

![image](https://user-images.githubusercontent.com/16067358/63923477-8afb0300-ca3e-11e9-952c-347b04ab1772.png)

I attached a screen record
https://drive.google.com/file/d/1yUiERuVaQS27ERkiifKWUr-_1BKjnTs1/view

Thanks to check & feedback.

**Comment by karilobre** [comment]
Hi @khouloudbelguith, thank you for your help. 

If I disable that option and select one level 1or 2 category the search doesnt show products, only show if I select level 3 categories, it happens maybe because the products are associated to the level 3 category, and that is not what I need. I just need to show in the filters the immediate next categories level, so I can search level 1 and filter by only level 2, and I can search level 2 and filter level 3.
![Captura](https://user-images.githubusercontent.com/22664584/63948396-c513d700-ca35-11e9-844a-b2193ecf44bd.PNG)

**Comment by khouloudbelguith** [comment]
@karilobre, you need as described in this screenshot?
Subcategories should be displayed also in the filter?
![image](https://user-images.githubusercontent.com/16067358/63949164-dd094c00-ca71-11e9-9b4f-45dee67f1be4.png)

Thanks!

**Comment by karilobre** [comment]
![Captura2](https://user-images.githubusercontent.com/22664584/63949478-b4fcf700-ca37-11e9-8691-00bf0615a4b8.PNG)

Look at this screenshot, I am in the category level 1 named "Articulos para Higiene y Limpieza", look that in the filters there are categories level 2 like "Articulos Limpieza" and 3 like "Basureros", in this screen if I choose filter by  "Articulos Limpieza" the filter works fine, but in the same screen if I choose to filter by "Basureros" the filter doesnt work, nothing happens.  

That is why I need to show in the filter of the level 1 only level 2 categories because the other doesnt work

**Comment by khouloudbelguith** [comment]
@karilobre, so in your case
The parent category of "Basureros"(level3) is "Articulos Limpieza"(level2) which have a parent category "Articulos para Higiene y Limpieza"(level1)?
![image](https://user-images.githubusercontent.com/16067358/63950467-f0b5b200-ca73-11e9-982e-848570155904.png)

Thanks!

**Comment by karilobre** [comment]
Yes, exactly like that

**Comment by khouloudbelguith** [comment]
@karilobre, in your case, the faceted search module is overridden by the theme?
Because with native module subcategories are not displayed on the filter.
![image](https://user-images.githubusercontent.com/16067358/63951237-4c346f80-ca75-11e9-90cf-c86727e3d342.png)

Thanks!

**Comment by karilobre** [comment]
The theme has a module named ps_facetedsearch but only has one .tpl file, how do I check if the theme override the module ??

**Comment by khouloudbelguith** [comment]
@karilobre, you need to check the theme author.
Thanks to check with them & feedback.

**Comment by karilobre** [comment]
Hi, the author told me that I can delete the ps_facetedsearch folder from the theme folder to make sure our theme doesn't override the module, so I did that but the filter still show all categories.

**Comment by khouloudbelguith** [comment]
@karilobre, could you please try switch to the classic theme & check if all categories from all levels are displayed?

Thanks!

**Comment by karilobre** [comment]
Hi,I couldn't switch the classic theme but I think I know what is wrong. All the products in my store are associated to the 3 category levels, for example, following this structure 
"The parent category of "Basureros"(level3) is "Articulos Limpieza"(level2) which have a parent category"
I have 
"Articulos para Higiene y Limpieza" 
              "Articulos Limpieza"
                                 "Basureros"   
and the product named "Basurero 1" has the 3 category levels in the ps_product_category. 

I suppose the best I can do is associate the producto with the last category level only. Right?

**Comment by khouloudbelguith** [comment]
@karilobre, and for the product, what is the exact default category is selected? is it "Articulos para Higiene y Limpieza" or "Articulos Limpieza" or "Basureros"?
![image](https://user-images.githubusercontent.com/16067358/64332550-ae88f500-cfcc-11e9-86d0-8d82b1141f8a.png)
Thanks!

**Comment by karilobre** [comment]
The default category is Basureros, the 3rd level

**Comment by khouloudbelguith** [comment]
@karilobre, with the default theme & the default module ps_facetedesarch => subcategories are not displayed.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
