### ISSUE TITLE
Critical Bug with Payment by Credit Card 

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#15296]
Hello,

I’ve discovered a critical bug that causes a fraud and I wrote it to security@prestashop.com two days ago, but no one returned. 

I want to be sure if someone got my email and is working on it. Can you please check and get back to me?

cccarik@gmail.com

Thanks

**Comment by khouloudbelguith** [comment]
Hi @cemalarik,

I just forwarded your issue to the team core.
The issue will be treated.
Stay tuned!
I close this ticket, feel free to open a new one when needed.

Thanks!
