### ISSUE TITLE
error 1-Click Upgrade Warning: require(/var/www/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php)

### ISSUE THREAD

**Issue by giogutierrez** [PrestaShop/PrestaShop#15294]
**Describe the bug**
By updating prestashop 1.7.5 to 1.7.6 Failure and after this the web was left with errors.

**Screenshots**
Warning: require(/var/www/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 61

Fatal error: require(): Failed opening required '/var/www/html/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 61

**Additional information**
PrestaShop version: 1.7.5.1 to 1.7.6.0
PHP version: 7.2.17

**Comment by khouloudbelguith** [comment]
Hi @t1desarrollo,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @t1desarrollo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
