### ISSUE TITLE
Impossible add related products

### ISSUE THREAD

**Issue by ElderTugBoat786** [PrestaShop/PrestaShop#15299]
**Describe the bug**
After upgrade Prestashop from 1.6 to 1.7.6 when I attempt to add a new related product in the product details tab nothing appear

**To Reproduce**
1. Go to Product Details
2. Click on related Products
3. Type something in the related product input
4. Nothing appears

I have also enabled the debug mode and I see that the request is sent correctly but the response is empty ( i suppose that in the request there is an empty JSON ) 

**Screenshots**

![related products](https://user-images.githubusercontent.com/38555796/63922078-44a8a280-ca44-11e9-83c6-72d00533c559.PNG)
![request](https://user-images.githubusercontent.com/38555796/63922079-44a8a280-ca44-11e9-8cca-e26e58e5dba7.PNG)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @ElderTugBoat786,

With Fresh install PS1.7.6.1 => OK.
What is the exact previous version PS1.6 did you use before the upgrade?
Do you have any errors during the upgrade?
What is the exact version of the 1-click upgrade did you use?
You need to enable debug mode in your store and debug request which is sent for adding a related product in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. Add a related product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by ElderTugBoat786** [comment]
HI @khouloudbelguith 

I have used the last version of 1-click-upgrade
When I attempt to add new related products ( so when I press enter after inserting a text in the field ) nothing appear

This is the request in developer tool

![header request](https://user-images.githubusercontent.com/38555796/63923505-f6e16980-ca46-11e9-9328-c2737bb34b75.PNG)

![response](https://user-images.githubusercontent.com/38555796/63923469-e9c47a80-ca46-11e9-9ac8-3c1cea81da4a.PNG)

Thanks!

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, yes, there is no error 500 displayed.
- What is the exact previous version PS1.6 did you use before the upgrade?
- Do you have any errors during the upgrade?

**Comment by ElderTugBoat786** [comment]
@khouloudbelguith I don't get any error during the upgrade the Prestashop version before the upgrade was the 1.6.1.4

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, In my case, I tried to make an upgrade from PS1.6.1.24 to PS1.7.6.1 using the 1-click upgrade v4.9.0.
I tried to add some related products & it is OK
https://drive.google.com/file/d/1JSoPaNwrtGvIo2d3EWDHCuJRNXT18XBi/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ElderTugBoat786** [comment]
Hi @khouloudbelguith,

checking the apache log file I saw that it marks me this error

```
[cgi:error] [pid 4226] [client 62.101.114.38:23662] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://domainname.com/gestione/index.php/configure/advanced/performance/?_token=qvIjg40fuverRxH6RQdDjSFrLjwVSTv5b0uWR07y5mA

```
And if I check ( with the debug active ) the related product request there isn't a debug profile

![ns debug prestashop](https://user-images.githubusercontent.com/38555796/64187825-95b7fc80-ce71-11e9-861f-022ad71016ca.PNG)

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, 
>[cgi:error] [pid 4226] [client 62.101.114.38:23662] AH01215: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0: /usr/local/cpanel/cgi-sys/ea-php56, referer: https://domainname.com/gestione/index.php/configure/advanced/performance/?_token=qvIjg40fuverRxH6RQdDjSFrLjwVSTv5b0uWR07y5mA

This is just a warning, it is not an error.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ElderTugBoat786,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
