### ISSUE TITLE
Left navbar is empty in develop

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#15309]
After latest merges, the navbar is shown empty.

**Screenshots**
![Screenshot from 2019-08-29 13-37-12](https://user-images.githubusercontent.com/31609858/63933558-2782cc80-ca62-11e9-8fc1-bc76832e2f21.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

After running `composer install` & re-installing the shop => the issue doesn't exist anymore.

![image](https://user-images.githubusercontent.com/16067358/63934503-707f5480-ca53-11e9-8c9f-3b3939af32c4.png)

Thanks!

**Comment by zuk3975** [comment]
> Hi @zuk3975,
> 
> After running `composer install` & re-installing the shop => the issue doesn't exist anymore.
> 
> ![image](https://user-images.githubusercontent.com/16067358/63934503-707f5480-ca53-11e9-8c9f-3b3939af32c4.png)
> 
> Thanks!

Okay, cool, thanks :)

**Comment by zuk3975** [comment]
Ok, cool, thank you :)

**Comment by khouloudbelguith** [comment]
@zuk3975, so, can we close the issue?

Thanks!

**Comment by zuk3975** [comment]
Yes, indeed :smile:
