### ISSUE TITLE
Unneccessary / on Home category breadcrumb

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#15302]
In the breadcrumb of the Home category there is a slash at the end, this is not the case in any other category/product view.

![grafik](https://user-images.githubusercontent.com/47666330/63924671-f649d280-ca48-11e9-8e7f-9a7a178a2f48.png)

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

Thanks for your report.
I have the same behavior with PS1.7.5.2/PS1.7.6.1/develop branch.
When the Home category is selected
![image](https://user-images.githubusercontent.com/16067358/63926402-b16f6d00-ca43-11e9-87a5-31e6e733796b.png)
When another Category is selected
![image](https://user-images.githubusercontent.com/16067358/63926351-9f8dca00-ca43-11e9-9e34-82ddb79dfbc3.png)
Ping @marionf, @colinegin, what do you think?
It could be a good improvement?

Thanks!

**Comment by JBWModules** [comment]
Now this is even reported as an error in Google Search Console as there are even empty meta tags added.
![grafik](https://user-images.githubusercontent.com/47666330/65325914-7084f700-dbb0-11e9-99ad-446357cbd53d.png)

**Comment by marionf** [comment]
Hello @JBWModules 

Could you make your pull request on PrestaShop repository ?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by JBWModules** [comment]
I tried. It's my first pull request so I hope this will be fine.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15632

**Comment by matks** [comment]
> I tried. It's my first pull request so I hope this will be fine.

Looks like it was fine indeed 😉 thank you for your contribution !
