### ISSUE TITLE
Color name doesn't appear over the color block in the product pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15308]
Hi
in the product block the color name appear when the mouse pass over the color block, instead in the product page the color names will not show

the problem is due from the html code
in variant-links.tpl it is present a link tag, instead in the product-variants.tpl it is present a span tag

bye

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/63932400-66f7eb80-ca57-11e9-85f0-5f5c32f98cfe.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by Maofree** [comment]
to solve this problem you can add the attribute "title" to the input tag
`<input title="{$group_attribute.name}"`

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
