### ISSUE TITLE
Harmonize the currency creation/update

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#15303]
**Is your feature request related to a problem? Please describe.**
Currencies are created in different ways in different places in the codebase (ex: LocalizationPack) which uses legacy code and not command/handlers. All these modifications should be harmonized by removing the use of legacy classes.

**Describe the solution you'd like**
Once the the PR https://github.com/PrestaShop/PrestaShop/pull/14972 is validated and merged, the command/handler should manage most scenarii, including partial updates, and automatic filling of missing data. There might be a few missing scenarii to implement, but we should be able to use commands everywhere in the codebase.

**Describe alternatives you've considered**
You can check the behat scenarii to be sure everything is already managed, and any new scenario should be added if needed.

**Additional context**
Keep in mind that install/upgrade should be able to create/update Currency with minimum data (maybe ISO code only) and the missing data should be automatically filled if absent, or ignored if they are already in database.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers
