### ISSUE TITLE
Notice when configure some modules

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#15318]
**Describe the bug**

**To Reproduce**
1. Go to module
2. Click on configure ps_emailsubscription
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/3034677/63951747-979f4b80-ca7e-11e9-956b-05dbc77126d1.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Same issue with Product comments module v4.0.0.
![image](https://user-images.githubusercontent.com/16067358/64116817-41d2e800-cd8b-11e9-9135-ad83391df0ac.png)

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15382
