### ISSUE TITLE
Invisible Product in front added with WebService

### ISSUE THREAD

**Issue by jeffPro97** [PrestaShop/PrestaShop#15317]
**Describe the bug**
When i adding product with WebService, they are visible in my category in backoffice, but invisible in front office when i go to this category.

When i go to the page of one product the footer can tell me that all other product are present in it. (in front)

when i see the /api/products/idmyproduct, all information are present.
My code to add product :
            $webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, false);
            $xml = $webService->get(array('url' => PS_SHOP_PATH . '/api/products?schema=blank'));
            $product = $xml->children()->children();
            

            $product->reference = $p[0];
            //$product->id = $p[0];
            $product->price = 0; //Prix TTC
            $product->name->language[0][0] = $p[0];
            $product->name->language[0][0]['id'] = 1;
            $product->name->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;
            $product->active = 1;
            $product->state = 1;
            $product->show_price = 1;
            $product->low_stock_alert =0;

            //Association avec notre catégorie créée auparavant
            $product->associations->categories->addChild('category')->addChild('id', 17);
            $product->id_category_default = 17;
            $opt = array('resource' => 'products');
            $opt['postXml'] = $xml->asXML();
            $xml = $webService->add($opt);

**Additional information**
PrestaShop version: 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @jeffPro97,

For those products created with web service, could you please try to edit it => Tab Options => check the availability of this product if it is "Nowhere".
![image](https://user-images.githubusercontent.com/16067358/63950837-a254e300-ca74-11e9-83b2-9145e742cbee.png)
If yes, need to add the balise visibility to your script.


Thanks!

**Comment by jeffPro97** [comment]
i checked this and it's not nowhere. it's "partout in french".
i forget when i add product i set already the visibility with:
$product->visibility ='both';

**Comment by jeffPro97** [comment]
My products appear when i click on save product in back office but i want it without this action

**Comment by khouloudbelguith** [comment]
@jeffPro97, you need to go to the BO => Shop Parameters => Search page => Click on the "Add missing products to the index ".
![image](https://user-images.githubusercontent.com/16067358/63952299-39bb3580-ca77-11e9-9512-7092b617f6c0.png)

Thanks!

**Comment by jeffPro97** [comment]
Nothing append :(

![image](https://user-images.githubusercontent.com/54676075/63952659-41330c80-ca80-11e9-9793-ef885ce416f9.png)

**Comment by khouloudbelguith** [comment]
@jeffPro97, product are not displayed on the FO?
Thanks!

**Comment by jeffPro97** [comment]
no as i said they are not display when i go to my category in front office, but i can prove that they are in my database because when i go on one product they are all here in a footer module.

![image](https://user-images.githubusercontent.com/54676075/63953507-bc48f280-ca81-11e9-8a2e-05ceabb4fcf9.png)


![image](https://user-images.githubusercontent.com/54676075/63953551-d5ea3a00-ca81-11e9-810b-ad190deecf23.png)

**Comment by jeffPro97** [comment]
this screen to show no product in my catégory but one in new product : 

![image](https://user-images.githubusercontent.com/54676075/63954627-adfbd600-ca83-11e9-93b7-5d4a2bd028eb.png)

and this screen to show you that this new product is in my category :

![image](https://user-images.githubusercontent.com/54676075/63954761-eac7cd00-ca83-11e9-9eb9-b6966666bb1f.png)

**Comment by khouloudbelguith** [comment]
Hi @jeffPro97,

I did not manage to reproduce the issue with PS1.7.6.1 using this script
https://drive.google.com/file/d/12FCoE3-Q55ZVFeinAfs0KfNxbRLxrLOx/view
```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 29/09/19
 * Time: 16:44
 */
ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
define('PS_SHOP_PATH', 'http://shop.com/'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$psXML = <<<XML
<prestashop>
<product>
  <id/>
  <name>
  <language id="1">testingproduct</language></name>
  <price>120</price>
  <link_rewrite>aaaa</link_rewrite>
  <advanced_stock_management>1</advanced_stock_management>
  <active>1</active>
  <id_category_default>2</id_category_default>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <low_stock_alert>0</low_stock_alert>
  <id_shop_default>1</id_shop_default>
 <available_for_order>1</available_for_order>
  <minimal_quantity>1</minimal_quantity>
</product>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'products' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
/*for ($i = 1; $i <= 10000; $i++) {
    $xml = $webService->add( $opt );
}*/

$xml = $webService->add( $opt );
```

Thanks to check & feedback.

**Comment by jeffPro97** [comment]
ini_set('display_errors','on');

$psXML = <<<XML
<prestashop>
<product>
  <id/>
  <name>
  <language id="1">testingproduct</language></name>
  <price>120</price>
  <link_rewrite>aaaa</link_rewrite>
  <advanced_stock_management>1</advanced_stock_management>
  <active>1</active>
  <id_category_default>17</id_category_default>
  <associations>
    <categories>
      <category><id>17</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <low_stock_alert>0</low_stock_alert>
  <id_shop_default>1</id_shop_default>
 <available_for_order>1</available_for_order>
  <minimal_quantity>1</minimal_quantity>
</product>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, true);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'products' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
/*for ($i = 1; $i <= 10000; $i++) {
    $xml = $webService->add( $opt );
}*/

$xml = $webService->add( $opt );


same thing but like u don't have 'state' value it is not visible in back office too

![image](https://user-images.githubusercontent.com/54676075/64006411-90298200-cb12-11e9-82db-f07275d5b09a.png)

**Comment by jeffPro97** [comment]
well when i tried to copy the code it bug so i have done exactly ur code

**Comment by khouloudbelguith** [comment]
@jeffPro97, yes, I just checked on the FO, it is well displayed.
For the BO, you need to add the `state` balise & it is OK.

Using this script
```
<prestashop>
<product>
  <id/>
  <name>
  <language id="1">issuews</language></name>
  <price>120</price>
  <link_rewrite>aaaa</link_rewrite>
  <advanced_stock_management>1</advanced_stock_management>
  <active>1</active>
  <id_category_default>2</id_category_default>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <low_stock_alert>0</low_stock_alert>
  <id_shop_default>1</id_shop_default>
 <available_for_order>1</available_for_order>
  <minimal_quantity>1</minimal_quantity>
  <state>1</state>
</product>
</prestashop>
```
https://drive.google.com/file/d/1cVrxdlqR_0uRYulZ5SVT4qmNQgpyHCB7/view

Thanks!

**Comment by jeffPro97** [comment]
same thing it's not visible in my front office

![image](https://user-images.githubusercontent.com/54676075/64009758-ba7e3e00-cb18-11e9-89ee-e55f86569432.png)

![image](https://user-images.githubusercontent.com/54676075/64009780-c79b2d00-cb18-11e9-832a-4a737e7fd9f5.png)

**Comment by khouloudbelguith** [comment]
@jeffPro97, have you any module installed in your shop to edit the visibility of products?

Thanks!

**Comment by jeffPro97** [comment]
thx i've found the problem it was amazing filter.

thank you so much

**Comment by khouloudbelguith** [comment]
@jeffPro97, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #28586
