### ISSUE TITLE
Not show the image captcha contact page in prestashop1.7

### ISSUE THREAD

**Issue by Prem-lmx** [PrestaShop/PrestaShop#15321]
Hi guys,
im useed on prestashop1.7 version
i have install the module captacha in security purpose..
but not display show in capcha..
plesase support ...

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
captcha module is:
![image](https://user-images.githubusercontent.com/52959027/63996781-404eb900-cb1a-11e9-8b57-fe9b8cdd396f.png)

but issue of captcha:
![image](https://user-images.githubusercontent.com/52959027/63996683-f6fe6980-cb19-11e9-80e9-45b245c06890.png)

**Additional information**
PrestaShop version: 1.7
PHP version: 5.6.25

**Comment by khouloudbelguith** [comment]
Hi @Prem-lmx,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by Prem-lmx** [comment]
[advancedcaptcha.zip](https://github.com/PrestaShop/PrestaShop/files/3558887/advancedcaptcha.zip)
Hai khouloudbelguith i have sent module
plese support..
Thanks

**Comment by khouloudbelguith** [comment]
@Prem-lmx, I did not manage to reproduce the issue with PS1.7.6.0 & your module.
![image](https://user-images.githubusercontent.com/16067358/64003887-29519c00-cb05-11e9-8eed-87a3f5bba243.png)
As I said before, As it's not a module provided by Prestashop, we can't do anything with this.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
I close the issue, feel free to open a new one when needed.

Thanks!
