### ISSUE TITLE
Show Subtotal without Taxes

### ISSUE THREAD

**Issue by karilobre** [PrestaShop/PrestaShop#15320]
**Describe the bug**
I've installed Prestashop 1.7.5.2, the checkout summary shows Total of productos with taxes but I need to show without taxes in this line. 
![Captura2](https://user-images.githubusercontent.com/22664584/63977326-c7dfed80-ca70-11e9-94d7-065f185c3cc5.PNG)

**To Reproduce**
1. Go to store
2. Click on some product to add cart
3. Go to Checkout

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @karilobre,

You need to navigate to your BO => ShopParameters => Customer Settings => Groups Tab => Edit you Group & edit the "Price display method" to Tax excluded.
![image](https://user-images.githubusercontent.com/16067358/64002464-05d92200-cb02-11e9-9171-67d86cf66787.png)

Thanks to check & feedback.

**Comment by karilobre** [comment]
Hi, thank you I did that but the result is that the product price shows without taxes but when I go to checkout the item Product Totals shows with taxes and this is what I need to change.

**Comment by khouloudbelguith** [comment]
@karilobre, you have a lot of issues related to the taxes & prices are fixed in the PS1.7.6.
You can check those tickets:
- https://github.com/PrestaShop/PrestaShop/issues/11360
- https://github.com/PrestaShop/PrestaShop/issues/10013
- https://github.com/PrestaShop/PrestaShop/issues/9698

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @karilobre,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
