### ISSUE TITLE
Confusing display of VAT in product BO, when VAT disabled

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15330]
**Scenario**
Merchant is not a VAT payer, so disable VAT in International > VAT.

**What's wrong - product admin**
- It shows inputs for price without tax and with tax.
- It shows a tax selection dropdown.
- It allows you to select VAT, even if it's not applied to the price in the end.

**Solution**
A) Hide the fields that are not required and display only "Price"
B) Keep it, but add a message - VAT disabled, VAT will not take effect.

PS version: 1.7.6.1

______

+ Thumbs up to the dev team for improving the display on FO when VAT is disabled. In first versions of PS 1.7, it was still showing “Total (tax incl.)” and stuff like that. This seems to be fixed now. 👍

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @marionf, @colinegin what do you think?
If we disable taxes in the BO => International => Taxes page
![image](https://user-images.githubusercontent.com/16067358/64018995-e18f3c80-cb25-11e9-8b66-4a53a434fe0c.png)
In the BO => Product details page => can we hide all fileds related to taxes
![image](https://user-images.githubusercontent.com/16067358/64019138-3763e480-cb26-11e9-9fbf-cbaa4e2a5947.png)
![image](https://user-images.githubusercontent.com/16067358/64019146-3b900200-cb26-11e9-9919-59592007553b.png)

Thanks!

**Comment by marionf** [comment]
Thank you for your suggestion @Hlavtox 

It seems a good idea to not display the following info when taxes are disabled in International > Taxes:

- Price tax included & Tax rules fields in basic settings tab

![capture d'écran_1932](https://user-images.githubusercontent.com/13449658/64020341-a561d900-cb31-11e9-9328-5df26f21d4f5.png)

- Price (tax incl.), Tax rule fields in pricing tab & Final retail price tax incl.

![capture d'écran_1933](https://user-images.githubusercontent.com/13449658/64020415-de01b280-cb31-11e9-827f-69fe6681fde9.png)

- Impact on price (tax incl.) when editing a combination

![capture d'écran_1934](https://user-images.githubusercontent.com/13449658/64020478-fa055400-cb31-11e9-8d9e-737524fc7c98.png)

**Comment by FtigerARG** [comment]
In this scenario, the product page on FO shows "Tax excluded" below the price... It would be nice to have an option to hide that

**Comment by Hlavtox** [comment]
@MatShir @LouiseBonnard @marionf As I am thinking about it now for a second time, there could be a scenario, when the user will switch to VAT payer and wants to prepare his prices and tax rules in before. If we hide the fields, he can't.

I would keep these fields available, but display a hint next to prices, that tax is disabled.

**Comment by juraj1000** [comment]
I think it would better to have a new configuration parameter, e.g. "Display fields for VAT prices", in Tax options. When the option "Enable tax" was No and this new parameter was Yes then a merchant could prepare the new prices before changing of his status to VAT payer.  If the new parameter was No then all VAT fields would be hidden. By this way the both scenarios for VAT fields would be possible. Keep in mind that scenario for changing the prices with VAT is important but it is not daily business task, so it will not confuse the merchants who are not VAT payers.
