### ISSUE TITLE
Translation manager searches return only first result

### ISSUE THREAD

**Issue by FtigerARG** [PrestaShop/PrestaShop#15338]
![Screenshot_1](https://user-images.githubusercontent.com/54717602/64034142-6a0cdd80-cb24-11e9-9bb0-6e663f96ae99.png)

Even though the search returns 156 expressions, only the first one is listed.

Go to  International on left menu -> Translations -> click Modify button -> search for anything general to ensure many results are found

PrestaShop version: 1.7.6.0
PHP version: 7.3.4

**Comment by khouloudbelguith** [comment]
Hi @FtigerARG,

You need to click on the other links to display other expressions.
https://drive.google.com/file/d/1M8ppOfP0cUR9tHTulH_1ucXpaGTKlvJN/view
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP.

**Comment by FtigerARG** [comment]
Wow thanks for that instant response. PHP version downgraded, thank you for the advice (hadn't noticed problems with v7.3 though).
Didn't realize the search worked that way, sorry for posting it as a bug... let's make this a suggestion instead of an issue then:
It would be nice if the links on the left would get filtered after a search, to avoid the need to click one by one to find out whether a result is hiding inside or not.
Or maybe list all the results on the right, independently of to which category they belong (more intuitive imho)

**Comment by khouloudbelguith** [comment]
@FtigerARG, we have a new feature added to PS1.7.7.0.
Translations search : menu items active or not.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12997 to add this feature.
Thanks!
Feel free to open a new one when needed.
