### ISSUE TITLE
Introduce foreign keys in database schema

### ISSUE THREAD

**Issue by flavius** [PrestaShop/PrestaShop#15332]
Dear PrestaTeam

Are there any plans or thoughts on referential integrity, at least for new installations?

> Reasons to use Foreign Keys:
> 
> you won't get Orphaned Rows (real benefit for PS!)
> you can get nice "on delete cascade" behavior, automatically cleaning up tables (real benefit for PS!)
> knowing about the relationships between tables in the database helps the Optimizer plan your queries for most efficient execution, since it is able to get better estimates on join cardinality. (real benefit for PS!!)
> FKs give a pretty big hint on what statistics are most important to collect on the database, which in turn leads to better performance (real benefit for PS!!)
> they enable all kinds of auto-generated support -- ORMs can generate themselves, visualization tools will be able to create nice schema layouts for you, etc (will help PS developers)
> someone new to the project will get into the flow of things faster since otherwise implicit relationships are explicitly documented (will help PS developers)

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by flavius** [comment]
Ping @PrestaShop/prestashop-core-developers ?

Ping @khouloudbelguith ?

**Comment by khouloudbelguith** [comment]
@PrestaShop/prestashop-core-developers friendly reminder :)

**Comment by PierreRambaud** [comment]
Hi and thanks for your suggestion.
We currently plan nothing about adding it. But I'm in favor of adding referential integrity with this kind of database (mysql, pgsql, etc).
ping @eternoendless @matks @jolelievre

**Comment by jolelievre** [comment]
I think it could be great as well, although I don't know why we have no foreign keys for now
Maybe is it because of the modules that can change the database and would me more difficult to deal with with foreign keys? 🤔
Anyway if in some next major version we decide to use Doctrine for all our objects and get rid of the legacy ObjectModel maybe we could introduce FK at this moment, with some nice cascade behaviour

**Comment by Progi1984** [comment]
> Maybe is it because of the modules that can change the database and would me more difficult to deal with with foreign keys? thinking

But it's not a good practice to alter a table for a module. The good practice should be to create new tables with foreign keys.

> Anyway if in some next major version we decide to use Doctrine for all our objects and get rid of the legacy ObjectModel maybe we could introduce FK at this moment, with some nice cascade behaviour

:+1:

**Comment by PierreRambaud** [comment]
@jolelievre It was because of MyISAM which do not support relation keys.

**Comment by flavius** [comment]
@PrestaShop/prestashop-core-developers Thanks for the nice history recap. So how would you like to move forward?

ping @khouloudbelguith

**Comment by eternoendless** [comment]
This is definitely something we should try.

Some history here: https://github.com/PrestaShop/docs/issues/639#issuecomment-661782014

**Comment by nelero** [comment]
Hi, it would be a great improvement for the sanity of the database and particular behaviour with modules or even programmers databases removes which lets orphans in some tables and then create problems.
