### ISSUE TITLE
Getting issue on module admin controller's render list in Prestashop V1.7.6.1 with existing data

### ISSUE THREAD

**Issue by neerajwebkul** [PrestaShop/PrestaShop#15333]
Hello,

Currently I am getting issue on my module's admin controller render list page in Prestashop V1.7.6.1 while my controller's render list has some data.
After research, I found that I am getting this issue because I am not using $this->identifier name similar to $this->table name on module's admin controller page.
For example, my table name is 'product_review' and here I am using primary key as 'id_review' So in this case, I will define $this->identifier = 'id_review' on module admin controller.

In previous prestashop version (below V1.7.6.1), I don't have any issue like this but on current prestashop V1.7.6.1, I am getting a error -
"Notice: Undefined index: id_product_review"

Check this screenshot -  https://prnt.sc/ozmiwc

In Prestashop V1.7.6.1, you are always getting entity like -   'id_' . $table_name
So have you restrict it in current version 1.7.6.1 because you didn't mention anything like this before.

1. Create a table in module i.e. table name 'product_review' and set primary key in this table as 'id_review'
2. Create a module's admin controller and set 
   $this->identifier = 'id_review'
   $this->table = 'product_review'

Now while you will add any data in your table and when you see render list of your admin controller then you will get issue like "Notice: Undefined index: id_product_review"
https://prnt.sc/ozmiwc

Here if I used my primary key as 'id_product_review' then I will get no error. So It looks like It is mandatory to set table primary key same table name.

Screenshots -

![error](https://user-images.githubusercontent.com/43534930/64022949-e4edec80-cb54-11e9-9f59-7938d96b0db3.png)

PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @neeraj751,

Thanks for your report.
Yes, I manage to reproduce the issue with PS1.7.6.1 & the `blockblog` module which is a module admin controller's render list.
https://drive.google.com/file/d/13jpnwlaVXBEyDYdYfSSbmbhbtLz2HMNQ/view
![image](https://user-images.githubusercontent.com/16067358/64027656-11940b00-cb39-11e9-802e-5710c6a916be.png)
This exception is displayed when debug mode is enabled.
With PS1.7.5.2 => ok / 1.7.6.0 => OK

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by neerajwebkul** [comment]
Hello @khouloudbelguith ,

I have sent a pull request - #15341 
Please check.

Thanks

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15382

**Comment by wojoni** [comment]
Hi, when this bug when will it be solved ?

**Comment by khouloudbelguith** [comment]
Hi @wojoni,

It is fixed & it will be available in the next patch PS1.7.6.2.

Thanks!

**Comment by wojoni** [comment]
Hi @khouloudbelguith
can I have some instructions on how to fix it before upgrading to 1.7.6.2?

**Comment by khouloudbelguith** [comment]
@wojoni, you can follow this link: https://github.com/PrestaShop/PrestaShop/pull/15382/files & apply the fixes.

Thanks!
