### ISSUE TITLE
Disabled languages are not displayed in import page

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#15334]
**Describe the bug**
When going to Advanced Parameters -> Import the language selection form shows only active languages. I think it should show all installed languages, cause one may need to prepare the offer before turning on the language.

**To Reproduce**
1. Turn off some of the languages installed on the shop
2. Go to Advanced Parameters -> Import
3. See error - only active languages are available to select

**Additional information**
PrestaShop version: 1.7.5, 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @daresh,

Your Language is disabled, so it is normal behavior that cannot be displayed.
In fact, when you disable this language => when we try to add a product for example manually => this language is not displayed also.

 https://drive.google.com/file/d/1mrldHOj4-U84aLi8RurYuGmbzfEOiJ0O/view

Thanks!

**Comment by daresh** [comment]
Hi @khouloudbelguith,

but you still can edit features, attributes etc. in all the languages.

This language hiding seems to be a new concept of prestashop 1.7, it was not in 1.6 and I encourage you to reconsider it.

If someone wants to prepare his offer in some language he wants to introduce, he may not want to turn it on from the start, but after some time when all the descriptions etc. are ready and translated.

Another case - often people have data from wholesales in english, they want to import products on the shop, then translate and turn on when ready. They may even not want to use that language at all on the front.

Having too many languages to choose won't hurt anybody, but too few can be a problem.

So I consider it a bug, someone made a bad decision there.

**Comment by khouloudbelguith** [comment]
@daresh, thanks for these clarifications.
Yes, in the Attributes page, the disabled language is displayed.
![image](https://user-images.githubusercontent.com/16067358/64035001-9d149880-cb47-11e9-923a-28f991e0af2a.png)
Ping @matks is this a desired behavior during the migration, the disabled language will not be displayed?
![image](https://user-images.githubusercontent.com/16067358/64035121-e6fd7e80-cb47-11e9-8a20-15f3478e7afd.png)

Thanks!

**Comment by matks** [comment]
@khouloudbelguith this is rather a question for Product 😉

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team friendly reminder :wink: 

> is this a desired behavior during the migration, the disabled language will not be displayed?

Could someone please answer @khouloudbelguith question, thanks in advance.

**Comment by marionf** [comment]
That's a regression of the migrated page
On legacy page, disabled languages were displayed as you can see below

![capture d'écran_2928](https://user-images.githubusercontent.com/13449658/105200501-3038de80-5b40-11eb-8988-b0bfb0262e9f.png)

![capture d'écran_2929](https://user-images.githubusercontent.com/13449658/105200514-3333cf00-5b40-11eb-8dfc-37ebff34104b.png)
