### ISSUE TITLE
How do I disable vouchers?

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#15345]
Hello. How do I disable vouchers in admin cp?

**Comment by kpodemski** [comment]
Catalog -> Discounts, disable all discounts from the list

**Comment by TemKaSD** [comment]
@kpodemski 
![Screenshot_3](https://user-images.githubusercontent.com/6318282/64066037-b0fbef80-cc58-11e9-9f9a-8749dd7250f9.png)

**Comment by kpodemski** [comment]
Ok so... what exactly you want to disable? :D you don't have any vouchers

**Comment by TemKaSD** [comment]
Me need set PS_CART_RULE_FEATURE_ACTIVE 0 from admin cp.

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

When all cart rules are disabled or deleted => the `PS_CART_RULE_FEATURE_ACTIVE` is null.
I attached a screen record
https://drive.google.com/file/d/1IgZa6zedM7BXFmhYnfDwJg7kv0_DxtZB/view
Thanks to check & feedback

**Comment by TemKaSD** [comment]
@khouloudbelguith thx. I had no rules, it is standardly included without rules, I consider it a mistake.

**Comment by khouloudbelguith** [comment]
@TemKaSD, in your case, what is the exact value of `PS_CART_RULE_FEATURE_ACTIVE`?

Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith I install PrestaShop, PS_CART_RULE_FEATURE_ACTIVE = 1. Is that right?

**Comment by khouloudbelguith** [comment]
@TemKaSD, fresh install PrestaShop is 0 https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/install-dev/data/xml/configuration.xml#L422
Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith Really. Sorry.

**Comment by khouloudbelguith** [comment]
@TemKaSD, feel free to open a new one when needed.

Thanks!
