### ISSUE TITLE
ps_facetedsearch selections and paginations doesn't scroll to the top

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15342]
Hi
in some cases I've seen that after a selection or after push on the pagination the customer is move to the top of page, and it is right. but in some cases this is not happen like in this site
https://www.samitech.it/3-elettrodomestici
instead in this site all is ok
https://www.lampadaribartalini.it/luce-illuminazione-vendita-online/6-lampadari-sospensione

this behavior is managed from the module ps_facetedsearch not from the theme

what do you think?

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/64061200-7dc54c00-cbd7-11e9-96f6-0d8063c3ff8d.png)
![22](https://user-images.githubusercontent.com/653230/64061201-7dc54c00-cbd7-11e9-89af-676f3501944c.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0
Module version: 3.2.1

bye

**Comment by PierreRambaud** [comment]
Hi,

As far as I know, the scroll behavior is managed by the theme, not facetedsearch. 🤔

**Comment by Maofree** [comment]
Hi Pierre
I thought it was managed by the module, because with the last version of the module after a selection the preload logo is the same on all themes, are you sure that it ia managed by the theme?

![11](https://user-images.githubusercontent.com/653230/64075118-6dcf6a00-ccb4-11e9-9a21-39b4e422d68b.png)

**Comment by PierreRambaud** [comment]
yes we add the loader, but the scroll was already on the classic theme:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/listing.js#L146

**Comment by Maofree** [comment]
ok thanks for the info
bye

**Comment by PierreRambaud** [comment]
No problem, you're welcome!
