### ISSUE TITLE
On checkout getting error: Your address is incomplete, please update it.

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#15347]
Here is  how we can generate this error

Please place order on the site  https://www.gsmstyle.fr/  on the checkout page after you successfuly add the address and try to do the checkout you see the error.

Here is error screenshot

http://i.imgur.com/VJwpqQF.png

**Comment by khouloudbelguith** [comment]
Hi @pks891618,

Could you please navigate to your BO => Customers => Addresses => Check if you have any field set as required.
If yes, you need to navigate to BO => International => Locations => Countries Tab => Edit your country =>  check your Adrees format is complete (the required fiels is added to this format).
Thanks to check & feedback.

**Comment by pks891618** [comment]
http://i.imgur.com/tcx2ReV.png
http://i.imgur.com/iFqQYi1.png

still not working

**Comment by khouloudbelguith** [comment]
@pks891618, in your BO => Customers => Addresses => you need to Check if you have any field set as required.
See Screenshot
![image](https://user-images.githubusercontent.com/16067358/64103001-058e9000-cd69-11e9-9e55-e9451cb7aa6a.png)

Thanks!

**Comment by pks891618** [comment]
thanks its worked

**Comment by khouloudbelguith** [comment]
@pks891618, great!
Feel free to open a new one when needed.

**Comment by ersanjay5991** [comment]
> @pks891618, in your BO => Customers => Addresses => you need to Check if you have any field set as required. See Screenshot ![image](https://user-images.githubusercontent.com/16067358/64103001-058e9000-cd69-11e9-9e55-e9451cb7aa6a.png)
> 
> Thanks!

@khouloudbelguith
