### ISSUE TITLE
Picture Address Display 404

### ISSUE THREAD

**Issue by slomoo** [PrestaShop/PrestaShop#15353]
![image](https://user-images.githubusercontent.com/49021553/64101285-1f979500-cda0-11e9-8c86-78e6b10068be.png)

![image](https://user-images.githubusercontent.com/49021553/64101320-30480b00-cda0-11e9-92f3-9ae7ae1d2ca7.png)

![image](https://user-images.githubusercontent.com/49021553/64101704-00e5ce00-cda1-11e9-81a1-d9770b94dade.png)

PrestaShop Version : 1.7.6.0

What is this situation?

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

Could you please try to regenerate thumbnails.
You need to navigate to your BO => Design => Image Settings => On the bottom of the page => Click on Regenerate thumbnails button.
![image](https://user-images.githubusercontent.com/16067358/64102247-7765da00-cd67-11e9-9640-7a3a403f8c19.png)

Also, you need to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check & feedback.

**Comment by slomoo** [comment]
hi，I followed the steps you said and the results remained the same.


| |
slomoo
|
|
slomoo@126.com
|
签名由网易邮箱大师定制
On 9/2/2019 16:53，khouloudbelguith<notifications@github.com> wrote：

Hi @slomoo,

Could you please try to regenerate thumbnails.
You need to navigate to your BO => Design => Image Settings => On the bottom of the page => Click on Regenerate thumbnails button.


Also, you need to regenerate the file .htaccess

Rename the old file to .htaccess_old
Disable friendly URL
Enable friendly URL

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@slomoo, this issue occurs when the friendly URL is enabled or disabled?

Thanks!

**Comment by slomoo** [comment]
@khouloudbelguith  
![image](https://user-images.githubusercontent.com/49021553/64103463-eb72a300-cda4-11e9-8f27-ab3accc39271.png)
How do I operate this?

**Comment by khouloudbelguith** [comment]
@slomoo, you need to navigate to your BO => Shop Parameters => Traffic & SEO => SEO & URLs page => Set up URLs section => you can enable & disable Friendly URL
![image](https://user-images.githubusercontent.com/16067358/64103842-f6104680-cd6a-11e9-91f3-d1dd09f10ec3.png)

Thanks!

**Comment by slomoo** [comment]
It's still what it used to be.

My address ： shop.slomoo.cn

**Comment by khouloudbelguith** [comment]
@slomoo, are you using Nginx? 
Thanks!

**Comment by slomoo** [comment]
@khouloudbelguith  yes.

**Comment by khouloudbelguith** [comment]
@slomoo, it could be an issue related to the configuration of your server.
Thanks to follow this link
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
here's the the exact configuration for the images
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L83
Also, we have this PR: https://github.com/PrestaShop/PrestaShop/pull/10338 it could help you to solve your issue
This PR is not merged yet.

Thanks!

**Comment by slomoo** [comment]
@khouloudbelguith 
Hello, my problem hasn't been solved yet. My configuration files have been configured according to the above connection.

**Comment by khouloudbelguith** [comment]
@slomoo, could you please try to disable the Friendly URL & check if those images are well displayed?

Thanks!

**Comment by slomoo** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/49021553/64221800-9e0b4880-cf00-11e9-9615-b9b05ce21b71.png)
I turn them off and the page will be displayed properly.

But don't know how these configurations are applied?

**Comment by khouloudbelguith** [comment]
@slomoo, As I see in your picture, you have a message "`URL rewriting (mod_rewrite) is not active on your server, or it is not possible to check your server configuration. 
The `mod_rewrite` exists only for the apache environment.
So you need to make sure that you enable the mod_rewrite on your server.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
