### ISSUE TITLE
Undefined index:name after fresh install 1.7.6.1 for Jamarketplace module

### ISSUE THREAD

**Issue by ninefingersodnd** [PrestaShop/PrestaShop#15363]
**Describe the bug**
After installation of the new prestashop 1.7.6.1 i get a error when using the widget links of Jamarketplace on the left side in the menu. in 1.7.6.0 it isworking fine, but i can't see a major change in the 2 versions of prestashop.

Symfony\Component\Debug\Exception\ContextErrorException:
Notice: Undefined index: name

  at var/cache/dev/smarty/compile/f0/91/fa/f091fac4f79c95f8d96d458489e9513c54abde5b_0.file.content.tpl.php:25

**To Reproduce**
1. Install Prestashop 1.7.6.1 and set debug to on.
2. Download Jamarketplace (addon store)
3. click on a link from the module in the prestashop menu on the left.
4. See error undefined index:name as described above.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.21

**Comment by khouloudbelguith** [comment]
Hi @ninefingersodnd,

Did you tried to install this module: https://addons.prestashop.com/en/marketplace-creation/18656-ja-marketplace.html?

Thanks!

**Comment by ninefingersodnd** [comment]
> Hi @ninefingersodnd,
> 
> Did you tried to install this module: https://addons.prestashop.com/en/marketplace-creation/18656-ja-marketplace.html?
> 
> Thanks!

Yes i dit, the 1.7.6.1 version

**Comment by khouloudbelguith** [comment]
@ninefingersodnd, have you tried to contact the module author?
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback

**Comment by ninefingersodnd** [comment]
I have ask the question this morning. And knowing he is gonna solve it. The question for me is... I can't see mayor changes in the prestashop core that cause this problem. There is no change in handlers etc.

Thanks for your quick responses khouloudbelguith

**Comment by khouloudbelguith** [comment]
@ninefingersodnd, have you an error something like this?
![image](https://user-images.githubusercontent.com/16067358/64124466-fe827480-cd9e-11e9-8d7c-65bdfa857325.png)
As described in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15318

Thanks!

**Comment by Cofur64** [comment]
Hello, I have exactly the same problem and I am waiting for a response from the developer! I enclose the link of the page.
 ninefingersodnd do you have the same problem as me (file attached)
![5d6cd17def0e3](https://user-images.githubusercontent.com/54817051/64130313-dfe1a500-cdc1-11e9-9e83-ca5c2c5d61b6.png)

**Comment by ninefingersodnd** [comment]
> @ninefingersodnd, have you an error something like this?
> ![image](https://user-images.githubusercontent.com/16067358/64124466-fe827480-cd9e-11e9-8d7c-65bdfa857325.png)
> As described in this ticket: #15318
> 
> Thanks!

No this is not the error, it is exactly what Cofur64 has!
With debug on it gives, the stacktrace and the undifined index:name

**Comment by khouloudbelguith** [comment]
Hi @ninefingersodnd, @Cofur64,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
PS: here's the changelog for PS1.7.6.1: https://assets.prestashop2.com/en/system/files/ps_releases/changelog_1.7.6.1.txt
I close the issue, feel free to open a new one when needed.

Thanks!
