### ISSUE TITLE
FO not working due to error in module

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#15362]
**Describe the bug**
in develop branch Front Office is not working due to error coming from ps module. See screenshot below. Reinstalling the shop/composer/clearing cache doesn't seem to help.

**To Reproduce**
1. Go to front office
2. See error

**Screenshots**
![Screenshot from 2019-09-02 16-20-35](https://user-images.githubusercontent.com/31609858/64117359-a7c86b00-cd9d-11e9-8572-5434e56d78bf.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

What is the exact version of the ps_emailsubscription module did you use?
In my case ps_emailsubscription v2.5.0 => OK

Thanks!

**Comment by zuk3975** [comment]
v2.3 it was. 
After updating ps_emailsubscription to 2.5 and ps_contactinfo to 3.2 it works. I suppose those modules should be updated in composer.json, to be working from clean ps install.

**Comment by khouloudbelguith** [comment]
@zuk3975, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15354 to update composer.

Thanks!
