### ISSUE TITLE
Supplier logo doesn't change in grid between multiple shops

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#15367]
**Describe the bug**
When sharing supplier in couple shops, changing the supplier logo in one shop, does not change the logo in another shop (grid only). In form, the logo is changed.

**To Reproduce**
1. Have at least 2 shops with same supplier
2. Change supplier logo in shop 1
3. Go to shop 2 suppliers list -> supplier logo not changed.
4. Press Edit supplier -> see the logo is actually changed here.

**Screenshots**

**Additional information**
PrestaShop version: <= 1.7.6
PHP version: N/A

**Comment by zuk3975** [comment]
Is being solved within Suppliers migration in #13485

**Comment by khouloudbelguith** [comment]
Reproduced with PS1.7.6.1.

**Comment by marionf** [comment]
It seems to be fixed in 1.7.7.x
