### ISSUE TITLE
webservice API fatal error The service doctrine.orm.default_entity_manager has a dependency on a non-existent service prestashop.database.naming_strategy

### ISSUE THREAD

**Issue by MonkeyTime** [PrestaShop/PrestaShop#15365]
**Describe the bug**

I try to access via Postman to my webservice (under development). The adress is https://K6B8Y3Q4DIEUYHC6G6NBE3ZQ1SF8DCCI@mydomain.localhost/shop/api/?output_format=JSON

**To Reproduce**
1. Activate Api
2. generate a key
3. Try in debug mode
4. Try in production mode
5. Nothing work (**services_dev.yml not generated**)
6. Try https://K6B8Y3Q4DIEUYHC6G6NBE3ZQ1SF8DCCI@mydomain.localhost/shop/api/?output_format=JSON via Postman with the Prestashop DEBUG mode
6. Show error

<br />
<b>Fatal error</b>: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service
&quot;doctrine.orm.default_entity_manager&quot; has a dependency on a non-existent service
&quot;prestashop.database.naming_strategy&quot;. in
C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php:31
Stack trace:
#0
C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass.php(60):
Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass-&gt;processValue(Object(Symfony\Component\DependencyInjection\Reference),
false)
#1
C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php(28):
Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass-&gt;processValue(Array, false)
#2 C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony in
<b>C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php</b>
on line <b>31</b><br />

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.31

**Comment by khouloudbelguith** [comment]
Hi @MonkeyTime,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1w9Giiu32E3rT2NYHgJNb80msKBmSvrUG/view
Thanks to check & feedback.

**Comment by MonkeyTime** [comment]
Can you try via Postman to check if your API work ?

In debug mode under Prestashop when I try via Postman to check the api with this kind of link https://K6B8Y3Q4DIEUYHC6G6NBE3ZQ1SF8DCCI@mydomain.localhost/shop/api/?output_format=JSON

The error is produced (under postman).

If its working for you can you add a download link to your \config\services\webservice\services_dev.yml ?

I think maybe the problem comes from the file services_dev.yml. For me this file is not generated.

**Comment by khouloudbelguith** [comment]
@MonkeyTime, I tried also with Postman & it is OK
I tried with this link: `shop.com/api?output_format=JSON` & `shop.com/api/products?output_format=JSON`
![image](https://user-images.githubusercontent.com/16067358/64158384-43a2b700-ce30-11e9-831b-a7abd3c15fc3.png)
![image](https://user-images.githubusercontent.com/16067358/64158419-56b58700-ce30-11e9-9ce7-26b5ae137d35.png)
Thanks!

**Comment by MonkeyTime** [comment]
Thanks,

Weird I continue to have the problem and no **services_dev.yml** generated...

![Sans titre-1](https://user-images.githubusercontent.com/7724650/64167424-9472d980-ce49-11e9-8b72-15ae72fafeea.png)

**Comment by khouloudbelguith** [comment]
@MonkeyTime, when you try to access to this link with your browser => is it ok? or only with Postman, this issue occurs?

Thanks!

**Comment by MonkeyTime** [comment]
Next error when I try to access directly to https://GJSDWMCFSHLSJUYI2L85MYAATF9W6QFL@newvajra.localhost/shop/api

Fatal error: Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "C:\Apache24\htdocs\vajra-new\shop/config/services/webservice/services_dev.yml" does not exist. in C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\Config\FileLocator.php:44 Stack trace: #0 C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Loader\YamlFileLoader.php(115): Symfony\Component\Config\FileLocator->locate('C:\\Apache24\\htd...') #1 C:\Apache24\htdocs\vajra-new\shop\src\Adapter\ContainerBuilder.php(211): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('C:\\Apache24\\htd...') #2 C:\Apache24\htdocs\vajra-new\shop\src\Adapter\ContainerBuilder.php(172): PrestaShop\PrestaShop\Adapter\ContainerBuilder->loadServicesFromConfig(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #3 C:\Apache24\htdocs\vajra-new\shop\src\Adapter\ContainerBuilder.php(127): PrestaShop\PrestaShop\Adapter\ContainerBuilder->compileContainer in C:\Apache24\htdocs\vajra-new\shop\vendor\symfony\symfony\src\Symfony\Component\Config\FileLocator.php on line 44

I try a fresh install of prestashop 1.7.6.1 to retrieve this file

**Comment by khouloudbelguith** [comment]
@MonkeyTime, in your case, this is not fresh install PS1.7.6.1?

Thanks!

**Comment by MonkeyTime** [comment]
This is an update with module "1 click-upgrade" from 1.7.6.0 to 1.7.6.1.v I 'dont say why but the files

services_dev
services_prod
services_test
*.yml

does not exist in my folder \config\services\webservice

Now the problem is solved I copied these files from the fresh install to my old folder and now all work great.

Thanks for your help

**Comment by khouloudbelguith** [comment]
@MonkeyTime, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
