### ISSUE TITLE
After new installation, Frontend access gives Page Not Redirecting error

### ISSUE THREAD

**Issue by jshrek** [PrestaShop/PrestaShop#15373]
**Describe the bug**
The installation went well as far as unpacking and creating database and connecting to the database (pretty standard for any php installation), and was able to login to the admin backend. However when I tried to access the frontend store, I got a PAGE NOT REDIRECTING error. This took some googling and I figured out that it was because I was trying to access the frontend with HTTPS instead of HTTP. 

**SUGGESTIONS**
This would seem to me to be a bug as you should either be able to access http or https without any errors/issues and/or https should at least rediect to http (or at a minimum show a page that says "please use http and not https to access front end"). 

**To Reproduce**
1. Setup a new prestashop installtion.
2. Attempt to access frontend from non-ssl http.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @jshrek,

Did you try to install Prestashop directly through https?
As I said before: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks!

**Comment by jshrek** [comment]
Okay thanks for advising me about PHP version...

I am using PHP v7.3.8 and during the System Compatibility of the install, it says **PrestaShop compatibility with your system environment has been verified!**

So maybe the System Compatibility check should produce an error/warning if the PHP version is too high?

![system](https://user-images.githubusercontent.com/19673842/64190351-07208c80-ce2b-11e9-9518-7f049aefa02f.png)

**Comment by khouloudbelguith** [comment]
@jshrek, yes, it could be a great improvement.
Ping @PrestaShop/prestashop-product-team what do you think?

THanks!

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-product-team Must we check the maximal PHP version ?
Actually we check the minimal version (7.1.3 at this day), but not the maximal version.
But we are not compatible (7.4).

I vote for a YES.

**Comment by colinegin** [comment]
Yes I agree, it is a good way to prevent problems.

**Comment by Progi1984** [comment]
@colinegin Ok. I take it ;)

**Comment by Progi1984** [comment]
@colinegin Merged ;)
