### ISSUE TITLE
Available carriers for a product

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15377]
It doesn't make sense that all carriers are available if they are not selected.

![capture d'écran_1939](https://user-images.githubusercontent.com/13449658/64156615-6daaa800-ce35-11e9-9644-cae0b6101b0a.png)

By default all available carriers should be checked and displayed in Frontoffice.
If a carrier isn't checked, it's not displayed in front-office.

This way, we can remove the information message "If no carrier is selected then all the carriers will be available for customers orders."

We should also add a bulk action to select/unselect all carriers

**Comment by arouiadib** [comment]
Hi guys, 
It would be good if we only fix the issue on product v2. 
am I right?

The issue exists in v1 but still not implemented in v2.

**Comment by matks** [comment]
> Hi guys,
> It would be good if we only fix the issue on product v2.
> am I right?
> 
> The issue exists in v1 but still not implemented in v2.



We will be happy to welcome a Pull Request that solves the issue either on v1 page or v2 page 😉 

The v1 page had multiple structure issues that could only be solved by a rebuild, and that is the scope of the v2 page project. But we can some extra value 🎉
