### ISSUE TITLE
[IMPROVEMENT] New carrier features

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15379]
These are some mods I made to our store, I think it could be useful to other merchants. If you find interesting, maybe it could be implemented when migrating carriers wizard.

**Carrier message**
I added a new HTML field to a carrier definition for displaying a special message, for example in in_transit emails.

Sometimes, you need to tell people something before the package arrives, for example - "IMPORTANT - Check the package through carefully before taking and signing the delivery slip from the driver. There is no posibility to exchange it if you find damage after X days."

**Support of customized products**
I added a on-off switch, which controls if the carrier will be able to handle customized products.

Why? We offer an option of picking up the products at our manufacturer warehouse. We also offer some product customizations, but they can be only done at our warehouse. So, this prevents customer to choose it, if they customized the product. (It's an easy mod and one check when looping through products in cart.)

**Minimum weight (and maybe minimum sizes also)**
I added a minimum weight field.

Why?
- We have 10k products in our store, imagine sorting them to Group A (small stuff) and Group B (big stuff).
- We have several "normal", post-like carriers, which are used to transport the small stuff. Then we have a heavy-duty carrier, which we use for the heavy stuff.
- We want the heavy-duty carrier to show up only, when he adds some heavy product to the cart. 
- But we also want to hide the normal carriers, because it's impossible to send the heavy item with them. Impossible to do with standard PS.
- After adding minimum height, you just add 15 kg to the heavy stuff and set the heavy carrier min-weight to 10 and normal carrier max-weight to 9. Done. As soon as he adds a heavy thing to the cart, it swaps the carriers.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
PIng @colinegin, @marionf what do you think?
The Carrier page will be migrated to Symfony in the PS1.7.7.
https://github.com/PrestaShop/PrestaShop/issues/10586

Thanks!
