### ISSUE TITLE
Launch Your Shop Welcome module gets in the way of accessing options

### ISSUE THREAD

**Issue by jshrek** [PrestaShop/PrestaShop#15374]
**Describe the bug**
PROBLEM 1: The issue is the "Launch your shop" helper thing that popped up. I clicked on LATER, but the problem with this is that it puts a block down in the bottom left corner (with the percent you are at and a RESUME button) and this block covers the Shop Parameters and Advanced Parameters so you can can not access those settings while it is there. 
PROBLEM 2: I then clicked on RESUME and it asks me to add a product (which I did) and I saved the product, but it just keeps coming back to the ADD A PRODUCT screen and I can not seem to figure out what it wants me to do, so you are forever stuck on the ADD A PRODUCT screen. 

**To Reproduce**
Install new prestashop installation.
Go to Admin area and choose LATER for Launch helper.

**Screenshots**
![block](https://user-images.githubusercontent.com/19673842/64143926-1a9a0c00-cdc7-11e9-9371-9eb18e7e61ee.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @jshrek,

Thanks for your report.
First, PrestaShop is not compatible with PHP7.3, you need to downgrade your PHP version.
Second, `PROBLEM 1` => You need to click on the "Stop OnBoarding" button to close this popup & your menu is flexible.
`PROBLEM 2` => It could be the PHP version (in my case, it is OK)
Thanks!

**Comment by jshrek** [comment]
Per my other reports... I am using PHP v7.3.8 and during the System Compatibility of the install, it says PrestaShop compatibility with your system environment has been verified! So maybe the System Compatibility check should produce an error/warning if the PHP version is too high?
Thanks

**Comment by khouloudbelguith** [comment]
@jshrek, thanks!
Done: https://github.com/PrestaShop/PrestaShop/issues/15373#issuecomment-527531017
Waiting for the PM team feedback.

**Comment by khouloudbelguith** [comment]
Hi @jshrek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
