### ISSUE TITLE
Enable SSL on All Pages does not work on backend admin

### ISSUE THREAD

**Issue by jshrek** [PrestaShop/PrestaShop#15372]
**Describe the bug**
When you set CONFIGURE > SHOP PARAMETER > GENERAL > ENABLE SSL ON ALL PAGES = YES it only works on Frontend pages but no on Backend Admin pages.

**To Reproduce**
1. Set CONFIGURE > SHOP PARAMETER > GENERAL > ENABLE SSL ON ALL PAGES = YES
2. Go to Frontend page using non-ssl HTTP and it will automatically redirect to HTTPS (this works fine).
3. Go to Backend Admin login page using non-ssl HTTP and it will give you a warning but will not redirect you to HTTPS. 
4. Then go to any other back admin page using non-ssl HTTP and it will allow you view that page unsecurely and will not redirect you to HTTPS.

**Suggestion**
(1) If this is intended behavior, then the the ENABLE SSL ON ALL PAGES setting should be renamed to ENABLE SSL ON ALL FRONTED PAGES.
(2) There should be an option to FORCE SSL on admin backend pages. A warning on login screen is insufficient as I could accidentally end up on http somehow, when I want to actually always be in https.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by dineshbadrukhiya** [comment]
> Go to Backend Admin login page using non-ssl HTTP and it will give you a warning but will not redirect you to HTTPS. 

For me, it's redirecting me to https so there is no issue I think

> PHP version: 7.3

If I'm not wrong, PrestaShop 1.7.6.1 is compatible up to php 7.2

**Comment by khouloudbelguith** [comment]
Hi @jshrek,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by jshrek** [comment]
Per my other reports... I am using PHP v7.3.8 and during the System Compatibility of the install, it says PrestaShop compatibility with your system environment has been verified! So maybe the System Compatibility check should produce an error/warning if the PHP version is too high?
Thanks

**Comment by khouloudbelguith** [comment]
@jshrek,
Thanks!
Done: https://github.com/PrestaShop/PrestaShop/issues/15373#issuecomment-527531017

**Comment by khouloudbelguith** [comment]
Hi @jshrek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
