### ISSUE TITLE
Display of translated email subject

### ISSUE THREAD

**Issue by BrunoJunior** [PrestaShop/PrestaShop#15381]
**Describe the bug**
When I save the translation of an email subject (modules section). The translation is not dispayed ...

**To Reproduce**
1. Install (or make) a little module with email template. And call the Mail::Send method (by the way, a method should not be capitalized ...) like this : Mail::Send('my_template', Mail::l('My subject')...).
2. Go to International > Translations > Email translations;Body;Core or a theme;Any language > Modify
3. Go to Module Emails section > {your module} > {your template}
4. Specify Email subject
5. Save and stay
6. The modified subject does not appear

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BrunoJunior,

When I try to edit the templete email of a module, I have this error: `No Subject was found for new_order in the database.` as reported in this ticket:

https://github.com/PrestaShop/PrestaShop/issues/9599

![image](https://user-images.githubusercontent.com/16067358/64166438-0560c400-ce3f-11e9-85b3-b78a6aaf6d76.png)

Thanks to check & feedback.

**Comment by BrunoJunior** [comment]
Hi @khouloudbelguith,
It's because this module does not use the Mail::l method.
Do you want a minimal module to reproduce the bug ?

**Comment by khouloudbelguith** [comment]
@BrunoJunior, thanks to provide me a demo module to reproduce the issue.
Thanks!

**Comment by BrunoJunior** [comment]
The demo module (It does not do anything …) : 
[bjmailsubject.zip](https://github.com/PrestaShop/PrestaShop/files/3569150/bjmailsubject.zip)
The translation page : 
![Capture](https://user-images.githubusercontent.com/4368255/64168516-02200500-ce4c-11e9-9ffe-183d507e2813.JPG)

**Comment by khouloudbelguith** [comment]
@BrunoJunior, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.6.1.
I’ll add this to the debug roadmap.
Thanks for the PR.
Thanks!

**Comment by BrunoJunior** [comment]
For information, 
I proposed a bugfix with the PR #15337

**Comment by BrunoJunior** [comment]
Fixed with #19288

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19289
