### ISSUE TITLE
1-click upgrade after error please help

### ISSUE THREAD

**Issue by sszr22** [PrestaShop/PrestaShop#15387]
hi guys I'm try to upgrade my prestashop 1.7.x.x to 1.7.5.1 but when upgrade complate after I took
Fatal error: Class 'Smarty_Internal_Undefined' not found in /var/www/vhosts/***/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168
please help me to fix it, thanks

**Comment by khouloudbelguith** [comment]
Hi @sszr22,
In your `Project_Folder/config/config.inc.php` file, could you please comment this line `setlocale﻿(LC_TYPE)`.
Thanks to check & feedback.

**Comment by sszr22** [comment]
this line
`setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
`
I'm using to website normally only 'Turkish'

**Comment by khouloudbelguith** [comment]
@sszr22, did you tried to comment it?
Did you use the 1-click upgrade v4.9.0.?
Did you use the local archive option to make the upgrade?

Thanks!

**Comment by sszr22** [comment]
actually, I dont know but I remember upgrade to last version 1-click upgrade I think v4.9.0 and 
i don't know what i did for the archive :/ please help for fix

**Comment by khouloudbelguith** [comment]
@sszr22, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in admin_folder/autoupgrade/tmp/log.txt

Thanks!

**Comment by sszr22** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3570009/log.txt)

I hope its true folder, thanks

**Comment by khouloudbelguith** [comment]
@sszr22, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by sszr22** [comment]
deleted into var/cache (prod&dev) but same error again
Fatal error: Class 'Smarty_Internal_Undefined' not found in /var/www/vhosts/bakliyatdiyari.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168

**Comment by khouloudbelguith** [comment]
@sszr22, could you please try to comment this line //`setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');` check & feedback.

**Comment by sszr22** [comment]
now all is change like this,


[PrestaShopDatabaseException]
Table 'bakliyat_data.ps_currency_lang' doesn't exist


SELECT *
FROM `ps_currency` a
LEFT JOIN `ps_currency_lang` `b` ON a.`id_currency` = b.`id_currency` AND b.`id_lang` = 1
LEFT JOIN `ps_currency_shop` `c` ON a.`id_currency` = c.`id_currency` AND c.`id_shop` = 1
WHERE (a.`id_currency` = 1) LIMIT 1

at line 769 in file classes/db/Db.php
764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 663 - classes/db/Db.php] - [1 Arguments]
DbCore->getRow - [line 75 - src/Adapter/EntityMapper.php] - [1 Arguments]
PrestaShop\PrestaShop\Adapter\EntityMapper->load - [line 264 - classes/ObjectModel.php] - [6 Arguments]
ObjectModelCore->__construct - [line 177 - classes/Currency.php] - [3 Arguments]
CurrencyCore->__construct - [line 101 - src/Adapter/Currency/CurrencyDataProvider.php] - [2 Arguments]
PrestaShop\PrestaShop\Adapter\Currency\CurrencyDataProvider->getCurrencyByIsoCode - [line 119 - src/Adapter/Currency/CurrencyDataProvider.php] - [2 Arguments]
PrestaShop\PrestaShop\Adapter\Currency\CurrencyDataProvider->getCurrencyByIsoCodeAndLocale - [line 92 - src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php] - [2 Arguments]
PrestaShop\PrestaShop\Core\Localization\Currency\DataLayer\CurrencyDatabase->doRead - [line 90 - src/Core/Data/Layer/AbstractDataLayer.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->read - [line 150 - src/Core/Data/Layer/AbstractDataLayer.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->propagateRead - [line 94 - src/Core/Data/Layer/AbstractDataLayer.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->read - [line 73 - src/Core/Localization/Currency/CurrencyDataSource.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Localization\Currency\CurrencyDataSource->getLocalizedCurrencyData - [line 104 - src/Core/Localization/Currency/CurrencyDataSource.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Localization\Currency\CurrencyDataSource->getAvailableCurrenciesData - [line 94 - src/Core/Localization/Currency/Repository.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Localization\Currency\Repository->getAvailableCurrencies - [line 207 - src/Core/Localization/Locale/Repository.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getPriceSpecifications - [line 150 - src/Core/Localization/Locale/Repository.php] - [1 Arguments]
PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getLocale - [line 190 - classes/controller/Controller.php] - [1 Arguments]
ControllerCore->init - [line 2775 - classes/controller/AdminController.php]
AdminControllerCore->init - [line 273 - classes/controller/Controller.php]
ControllerCore->run - [line 515 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 97 - admin/index.php]

**Comment by khouloudbelguith** [comment]
@sszr22, the table `ps_currency_lang` in your case is missing.
Did you make a backup of your database, you need to import this table.

Thanks!

**Comment by sszr22** [comment]
how exactly can i do it, please help me thanks

**Comment by khouloudbelguith** [comment]
@sszr22, did you make a back up of your database?
Thanks!

**Comment by sszr22** [comment]
I think its make automatically backup, I have one zip file name auto-backupfiles_V1.7.2.4_20190903-134242-4794c12c

**Comment by sszr22** [comment]
please check www.bakliyatdiyari.com whats the error?

**Comment by khouloudbelguith** [comment]
@sszr22, as I said, the table `ps_currency_lang` is missing in your case.
You need to import this table to your Database.
Or, you can Install Fresh install PrestaShop 1.7.5.1 with your same configuration ( same language, same country)=> then copy the table ps_currency_lang from the new database to your old database.
An example of this table
[ps_currency_lang.sql.txt](https://github.com/PrestaShop/PrestaShop/files/3570393/ps_currency_lang.sql.txt)

Thanks!

**Comment by sszr22** [comment]
now main page are open but when I open pruduct and take new error for date https://www.bakliyatdiyari.com/pilavlik-pirinc/20-1-kg-pilavlik-luna-pirinc.html like this

**Comment by khouloudbelguith** [comment]
@sszr22, what is the exact error?
![image](https://user-images.githubusercontent.com/16067358/64242444-6f3fa300-cefd-11e9-8feb-de99c8161e46.png)

Thanks!

**Comment by sszr22** [comment]
now is all fix but admin panel doenst work I'm deleted all folder and upload again in ftp, I hope its fix

**Comment by khouloudbelguith** [comment]
@sszr22, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @sszr22,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
