### ISSUE TITLE
Notice: Undefined index: pages_array (error 500) when come back with browser from a proeduct, previously filtered with module advancedsearch4

### ISSUE THREAD

**Issue by racquetmarket** [PrestaShop/PrestaShop#15390]
**Describe the bug**

When come back with browser from a product page, (previously filtered with module advancedsearch4)
 I get error: Notice: Undefined index: pages_array (error 500) 

**To Reproduce**
www.ecoritas.com
1-Go to any category
2-filter and get some products
3- Go to product page
4-Come back with the browser (error 500)

**Screenshots**
(error page) 

(1/1) ContextErrorException    Notice: Undefined    index: pages_array
--
in add1b26fc2a68ab97a95785d1b58f6f56d554c06_2.file.header.tpl.php line   226
at Block_7326905705d6d6504d39366_34538251->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line   248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_7326905705d6d6504d39366_34538251), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line   184

**Additional information**
PrestaShop version: 7.5.1
PHP version: 7.2.21

**Comment by khouloudbelguith** [comment]
Hi @racquetmarket,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by racquetmarket** [comment]
Sorry, this error comes from a core variable. I have already contact the developer and he told mee to contact you (both the theme developer and the moduel developer)

**Comment by khouloudbelguith** [comment]
@racquetmarket, thanks for your feedback.
Could you please provide me your module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by racquetmarket** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@racquetmarket, I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
@racquetmarket, I tried to install those modules but it is OK in my side with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1nO1oh4u5644T2F_eR8ca-59BU54_zIHH/view
Thanks to check & feedback.

**Comment by racquetmarket** [comment]
Thank you. I will try to copy my site in a  test environment and do different test.

**Comment by PrestaEdit** [comment]
$pages_array is not a core var ; it's surely due to an override and/or a third party module.

**Comment by khouloudbelguith** [comment]
@PrestaEdit, thanks for your feedback.
@racquetmarket, thanks to check & feedback.

Thanks!

**Comment by racquetmarket** [comment]
The error is an a piece of code, for seo pruposes, and for the canical links. I have commented the code right now, I think is a code for PS 1.6:
{*
 
{if $page.page_name == 'product' }

<link rel="canonical" href="{$link->getProductLink($product->id)}" />
{elseif $page.page_name == 'manufacturer' }
<link rel="canonical" href="{$link->getManufacturerLink($manufacturer->id)}{$pagination}" />
{elseif $page.page_name == 'supplier' }
<link rel="canonical" href="{$link->getSupplierLink($supplier->id)}{$pagination}" />
{elseif $page.page_name == 'category' }


<link rel="canonical" href="{$link->getCategoryLink($category->id)}{$pagination}" />

{elseif $page.page_name == 'cms' }
<link rel="canonical" href="{$link->getCmsLink($cms->id)}" />
{else}
 
{assign var=amn value=explode("-",$page.page_name)}
{if strpos($page.page_name,"module-") !== false && count($amn) == 3}
<link rel="canonical" href="{$link->getModuleLink($amn.1,$amn.2)}{$pagination}" />
{else}
<link rel="canonical" href="{$base_dir|replace:'.fr/':'.fr'|replace:'http':'https'}{$request_uri|regex_replace:'/\?(.*)/':''|replace:'index.php':''}{$pagination}" />
  {assign var=nobots value=true}
{/if}
{/if}
 *}
Thanks !

**Comment by khouloudbelguith** [comment]
@racquetmarket, but your are using PS1.7.5? is it?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @racquetmarket,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
