### ISSUE TITLE
How to validate customer state (zone) before add to cart

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#15391]
Hi we have a new project and we need to validate where the customer is as depending on de state there is a different inventory.

Example: `https://merqueo.com/v2/bogota?migrate=true`

Once we validate the state, we have to redirect the customer to the store (differents inventory by state) that can have service to his zone.

We have been looking for any way to do this without any luck, thank you for all your help

**Comment by khouloudbelguith** [comment]
Hi @msaustral,

Could you please provide more information about your issue.
Do you need to add a function to validate the state of your customer?
An example: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L326
Thanks!

**Comment by msaustral** [comment]
Hi sorry, the project is an online supermarket, they only have service on one state of the country, let say Miami and soon the client will have service on another state let say Tampa, so we need to validate where the customer is before add any item to the cart and depending on where he is we need to redirect him to the specific state´s store Miami or Tampa.

**Comment by khouloudbelguith** [comment]
@msaustral, in your BO => International => Localization => Geolocation Tab => You can enable the Geolocation by IP address.
![image](https://user-images.githubusercontent.com/16067358/64242641-cfcee000-cefd-11e9-9874-83226097ec54.png)
Geolocation is "the identification of the real-world geographic location of an object, such as a radar, a mobile phone or an Internet-connected computer. In our case, geolocation is used to discover the location of a visitor, using his or her computer's IP and other tools. 
I hope this option helps you.
Thanks to check & feedback.

**Comment by msaustral** [comment]
Hi ok this is part of the issue, once I have the location, Prestashop redirects automatically the client to the store serving that location if I enable multistore?

**Comment by khouloudbelguith** [comment]
@msaustral, 
>Prestashop redirects automatically the client to the store serving that location

This is the behavior that you need to add it to your shop? is it?

Thanks!

**Comment by msaustral** [comment]
Hi yes, detect the visitor location -> send the visitor to store A or B depending on his location

**Comment by khouloudbelguith** [comment]
@msaustral, and the "Enable Geolocalisation" option doesn't solve your issue?
Thanks!

**Comment by msaustral** [comment]
Hi testing it, I realize that it does not solve the problem, because it filter by country not by state

**Comment by khouloudbelguith** [comment]
@msaustral, Yes, you are right.
This option allows you, among other things, to restrict access to your shop for certain countries & not states.

Thanks!

**Comment by msaustral** [comment]
Hi ok is there a module do redirects the user to a store depending on his city?

**Comment by khouloudbelguith** [comment]
Hi @msaustral,

You need to follow this link: https://addons.prestashop.com/en => It is our Marketplace where you can find a lot of modules.

I close the issue, feel free to open a new one when needed.
Thanks!
