### ISSUE TITLE
adding translations to childTheme

### ISSUE THREAD

**Issue by stamatisbreezer** [PrestaShop/PrestaShop#15395]
**Describe the bug**
There was some words that wasn't translated, so I try to add the translation to the childtheme so I can keep them, after a future update of the master-theme. Same problem when I try to translate the master-theme.

**To Reproduce**
Modify translations  >Themes Translations > Selecting transformerchild > Language Greek >
I get the fast showing-dissapearing error: 
var/cache/prod/themes/transformerchild/translations/el-GR directory does not exist. 
even if I create the directory, it deletes.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![εικόνα](https://user-images.githubusercontent.com/5318989/64235788-c3e51d00-cf01-11e9-973e-babd1beba568.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by HartLarsson** [comment]
same problem on 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,

Issue reported here: #15268. 

Thanks!
