### ISSUE TITLE
Search attributes by Name, not Public Name

### ISSUE THREAD

**Issue by LW-Frost** [PrestaShop/PrestaShop#15403]
My company website has a variety of products with almost each having different variations of attributes. We dont want to put them all under one category like "Size" becouse that would make a very long list with vague information about to which product its used in.

Instead of searching by public name, search by Name. It already shows its name when you add attribute from checkbox panel.

Alternatively, it would be nice to have "Add all" in checkbox.

Attribute public name is "Wymiary" (eng. dimension)  but i have different for different products. If i could search for attributes like in the picture example, it would be really convenient.

![obraz](https://user-images.githubusercontent.com/37908055/64260777-cc524d80-cf2b-11e9-94df-4e110ab77215.png)

**Comment by khouloudbelguith** [comment]
Hi @Fr0stwalker,

Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/12440?

Thanks!

**Comment by LW-Frost** [comment]
Yes, sorry for duplicating.

**Comment by khouloudbelguith** [comment]
Duplicate of #12440
