### ISSUE TITLE
New module errors with 1.7.6.1 with LegacyHelperLinkBuilder.php

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15407]
Hi
now with 1.7.6.1 there are some errors like this one, if the configuration page of a module has some tables like for the productcomments module
the same happens on other my modules

/src/Adapter/Routing/LegacyHelperLinkBuilder.php
[8] Undefined index: id_productcommentscriterion

bye

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/64275269-7be7e980-cf45-11e9-8799-d70cd4b9b0ae.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by Maofree** [comment]
the same problem with ps_emailsubscription module
on the 1.7.6.0 this type of error was not present

![11](https://user-images.githubusercontent.com/653230/64276145-80ad9d00-cf47-11e9-9ba3-59558f77c0e1.png)

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15382 to fix the issue.
Your ticket is a duplicate of #15318
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15318
