### ISSUE TITLE
New version of ps_themecusto module compatible for product page and category page

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15400]
## The ps_themecusto module allows users to configure the modules on the Homepage 

![Capture d’écran 2019-09-04 à 11 05 52](https://user-images.githubusercontent.com/47456895/64241413-00197d00-cf04-11e9-81e1-5b4e9a8a5aa4.png)

## The goal of this improvement is to make it possible for the Product page and the Category page as well.
![themecusto_after](https://user-images.githubusercontent.com/47456895/64241477-1f180f00-cf04-11e9-8ce9-3615481c136b.png)

**Comment by colinegin** [comment]
@Darmona could you share with us the specs of this new version ?

**Comment by Darmona** [comment]
Does a google doc + Invision mockups are enough for you ?

**Comment by colinegin** [comment]
Version 1.1.0 available ! Thanks everyone !

**Comment by Darmona** [comment]
YOUHOUUUUUU !
[image:
https://docs.google.com/uc?export=download&id=1SDWdzk43EBlEVbSwVoAWdbeN8GdcMHjN&revid=0B-u6WWK29W9ZZWlyaTAwMG1FZWRBNXhFdGNZUERMRmxaZlBjPQ]

Alexandre Darmon

Product Manager Modules @ PrestaShop

t: +33 (0)1 40 18 30 04

alexandre.darmon@prestashop.com

<https://addons.prestashop.com/en/payment-card-wallet/46347-prestashop-checkout-built-with-paypal.html?utm_source=signature&utm_medium=referral&utm_campaign=PrestaShopCheckOut&utm_content=AlexDarmon>


PrestaShop Online:
[image: Facebook] <https://www.facebook.com/prestashop> [image: Twitter]
<https://twitter.com/prestashop> [image: LinkedIn]
<http://www.linkedin.com/company/prestashop> [image: Github]
<https://github.com/PrestaShop/PrestaShop> [image: YouTube]
<https://www.youtube.com/user/prestashop?utm_source=signature&utm_medium=e-mail&utm_campaign=emails-signatures>

Subscribe
<https://www.prestashop.com/en/newsletter?utm_source=signature&utm_medium=e-mail&utm_campaign=emails-signatures>
to
our newsletter!
