### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by slomoo** [PrestaShop/PrestaShop#15409]
![image](https://user-images.githubusercontent.com/49021553/64310014-1b05f300-cfd1-11e9-9224-e56dbe0efdd4.png)

![image](https://user-images.githubusercontent.com/49021553/64310082-51dc0900-cfd1-11e9-9a39-067e8a133789.png)

**Comment by slomoo** [comment]
![image](https://user-images.githubusercontent.com/49021553/64310490-d3806680-cfd2-11e9-89a9-b0142d9c656a.png)

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

To configure PrestaShop to send emails to your customers, we strongly advise you that you consult your web host to determine which settings to use for this feature.
To set your own SMTP parameters => The information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.
Thanks to check with your host & feedback.

**Comment by slomoo** [comment]
@khouloudbelguith  I'm sure my have no problem with the mail server.

I tested e-mail push directly on the mail server and used the mail server in my blog, so I'm sure the mail service is normal.

Thanks！

**Comment by khouloudbelguith** [comment]
@slomoo, in my case with the right access => it is OK.
https://drive.google.com/file/d/1Aa5AsdO39Uv9tPQBp98UUALzUCxj0O7_/view
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
