### ISSUE TITLE
Quantity Discount Table --> More Readable

### ISSUE THREAD

**Issue by Digitalfastmind** [PrestaShop/PrestaShop#15410]
**Is your feature request related to a problem? Please describe.**
No, it's a feature to request a more Clear display of the Multiple quantity discount table

**Describe the solution you'd like**
Customer need to know the single Discouted item cost and the total made of single product discounted x quantity - The actual way display instead the discount value and the total discount value, but it's not very clear. Based on our customers feedbacks the perception is that the "total discount" is the total price..

**Describe alternatives you've considered**
Display quantity -> item discounted price ->total price for quantity 

**Additional context**
Added, note that the "values" are not real, i just 
![Untitled-1](https://user-images.githubusercontent.com/13288891/64319318-55b16080-cfbc-11e9-95b4-579a06004e30.jpg)

**Comment by khouloudbelguith** [comment]
Hi @freeman78ita,

In your BO => Shop Parameters => Product Settings => you can enable the option "Display discounted price"
![image](https://user-images.githubusercontent.com/16067358/64321298-34e70c00-cfb8-11e9-9682-1ced27499eef.png)

Thanks to check & feedback.

**Comment by Digitalfastmind** [comment]
Thanks, in my language it was not translated quite correctly tho :P All good :)

**Comment by khouloudbelguith** [comment]
@freeman78ita, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
