### ISSUE TITLE
500 error after 1-Click Upgrade to 1.7.6.1

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#15418]
**Describe the bug**
1.7.5.1 performed upgrade to 1.7.6.1 using 1-Click upgrade. The whole process completed within few minutes with no errors or warnings. See image:
![completed](https://user-images.githubusercontent.com/31688689/64336834-3dead400-cfde-11e9-9de0-f16352e20e3f.png)

However the FO - 500 error, with debug enabled, the following is displayed:
![PrestaShopException](https://user-images.githubusercontent.com/31688689/64336732-f8c6a200-cfdd-11e9-9cde-3059152d8f8d.png)

In BO, you can go to Customers, but section Orders shows errors:
![BO-orders](https://user-images.githubusercontent.com/31688689/64337010-a934a600-cfde-11e9-893a-8798b3866e27.png)

I do have a backup and it is not live server, but any ideas how to fix it? I have deleted var/cache but id didn't help. I have also disabled all overrides, no result.

**Additional information**
PHP version: 7.2.22
Memory limit: 1024M
Max execution time: 600
Upload Max File size: 64M

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

You have an override of the class Tools.php
![image](https://user-images.githubusercontent.com/16067358/64337231-d9784680-cfd6-11e9-95e1-ed9dae042758.png)
It is not compatible with PS1.7.6.1, you should removed it & check with the module author about this if it is added by a custom module.

Thanks to check & feedback.

**Comment by mrabsinthe** [comment]
All overrides disabled as well as all non PrestaShop modules, cache cleared, same result.
![disabled](https://user-images.githubusercontent.com/31688689/64337480-c3bb4f00-cfdf-11e9-96dd-2f009462b87a.png)

**Comment by khouloudbelguith** [comment]
@mrabsinthe, this option is not working as reported in this ticket
https://github.com/PrestaShop/PrestaShop/issues/14596
Thanks!

**Comment by mrabsinthe** [comment]
1. it should have been fixed in 1.7.6.1
2. #14596 should have label 1.7.6.1
3. the error was caused indeed by Tools.php file

Thank you for your help.

**Comment by khouloudbelguith** [comment]
@mrabsinthe, thanks!
Feel free to open a new one when needed.

Thanks!
