### ISSUE TITLE
Unit prices wrong (Again)

### ISSUE THREAD

**Issue by jansass** [PrestaShop/PrestaShop#15423]
Take any variable product, add 0.001 as unit price (to make it work, else unit prices wont be calculated at all... well)

Base Price: 1,00 Euro, weight 0,5 kg
Unit Price: 2,00 Euro 

Works on product pages: Price 1 Euro, 2 Euro/kg
But when adding the same product to cart > open cart (cart-detailed-product-line.tpl) the price in {$product.unit_price_full} is wrong: 1,00 Euro / kg.

Default install 1.7.6.1, default theme, nothing changed. See Screenshots.

<img width="784" alt="Bildschirmfoto 2019-09-05 um 15 07 03" src="https://user-images.githubusercontent.com/4060287/64346599-b0fe4580-cff2-11e9-8831-c636ee71dfee.png">
<img width="728" alt="Bildschirmfoto 2019-09-05 um 15 07 19" src="https://user-images.githubusercontent.com/4060287/64346600-b0fe4580-cff2-11e9-8943-eee73f03f399.png">

**Comment by khouloudbelguith** [comment]
Hi @jansass,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1bZasGj5uIBL8_sJb_kFrEcmyO_1Zf1_R/view
Thanks to check & feedback

**Comment by jansass** [comment]
@khouloudbelguith 

As i said, as screenshot shows: VARIABLE product.

**Comment by khouloudbelguith** [comment]
@jansass, sorry do you mean a customized product?

Thanks!

**Comment by jansass** [comment]
@khouloudbelguith 

I mean a product with eg two sizes: L and XL, and two prices, and two unit prices (=variable product).
If its additionally customizable the bug still persists, so i thing its related to variable products..

**Comment by khouloudbelguith** [comment]
@jansass, thanks it is a product with combinations.
I checked it again & it is ok
https://drive.google.com/file/d/1nz_JvyH9mOOtziT7RbsTMcBlENMj5wfW/view
Thanks!

**Comment by jansass** [comment]
Can you please send me screenshots of product > prices, variants > prices and frontend on product page and cart ?

**Comment by jansass** [comment]
@khouloudbelguith Im sorry, its a video you sent. I need the screenshot for variants only, like attached
<img width="1009" alt="Bildschirmfoto 2019-09-05 um 16 14 46" src="https://user-images.githubusercontent.com/4060287/64350044-494af900-cff8-11e9-9078-7d7039ba5290.png">

**Comment by khouloudbelguith** [comment]
@jansass,
![image](https://user-images.githubusercontent.com/16067358/64350442-932fe100-cff0-11e9-8a73-9d61b672f360.png)

Thanks!

**Comment by jansass** [comment]
@khouloudbelguith 

Your impact on unit price is empty; thus it works. But that does not work in real life:

One product: two sizes, two prices, two weights:
A, Size L, 2 €, Weight: 0,5 kg == Unit Price: 4€/kg
B, Size XL, 3 €, Weight: 1 kg == Unit Price: 3€/kg

..so you NEED TO adjust "impact on price per unit" and then it fails..

**Comment by jansass** [comment]
fails in terms: works in product page, but not in cart; in cart base unit price is taken, not impacted price per variant)

**Comment by khouloudbelguith** [comment]
@jansass, thanks for these clarifications
It is ok in the shopping cart but it is wrong calculated on the product page as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9901
https://drive.google.com/file/d/1PU-veva690YQ-176R9Q9WV3Vzgr18zgN/view
Thanks to check & feedback

**Comment by jansass** [comment]
@khouloudbelguith 

So its a bug and will be fixed.. ? And "no", its correct on the product page, and wrong in the cart; i can reproduce every time, in any installation, when using superlow base unit price (0.001) and do it all in variant > impact on unit price..

BTW: this 0.001 feels like a bug also: IF there are unit prices, please use them. 0.001 is mathematically wrong, but if base product is at 0.00, unit prices are not calculated AT ALL..

**Comment by jansass** [comment]
I've delegated this to one of our teams, that BUG is SEVERE, and its in all versions (here and there) since 1.4. What is the problem with unit prices and Prestashop .. They are buggy all the time ??

**Comment by khouloudbelguith** [comment]
@jansass, yes it is a bug & it is added to our bug roadmap.
So your issue is similar to this ticket?
Thanks!

**Comment by jansass** [comment]
@khouloudbelguith 

No, its not about wrong math in fractions of numbers. {$product.unit_price_full} in cart-detailed-product-line.tpl is the complete wrong numbers (i guess its base product unit price; not variants' ) - making it ILLEGAL to use it with EU

**Comment by khouloudbelguith** [comment]
@jansass, in your case, in the shopping cart the unit_price is 0.
But in my case, it is OK as desqcribed in this screenrecord
https://drive.google.com/file/d/1PU-veva690YQ-176R9Q9WV3Vzgr18zgN/view
Combi1
![image](https://user-images.githubusercontent.com/16067358/64356354-a47deb00-cffa-11e9-9b4c-44a46a9f31f4.png)
Combi2
![image](https://user-images.githubusercontent.com/16067358/64356382-b19ada00-cffa-11e9-8003-aa7c59e817a2.png)

In the shopping cart
![image](https://user-images.githubusercontent.com/16067358/64356451-cf683f00-cffa-11e9-9604-e31be267640b.png)

Thanks!

**Comment by jansass** [comment]
@khouloudbelguith 

I dont know the base prices, i cant see them in your video. Anyhow:

https://drive.google.com/file/d/1PU-veva690YQ-176R9Q9WV3Vzgr18zgN/view
sec 0:42, you add ProductA, Size M, 4€ at **11€/kg**
sec 0:48, in Cart ProductA, Size M, 4€ at **8€/kg**

This is why unit prices are messed up - you are not checking the results properly. Im sorry to be that harsh, but im fed up with doing your work. Presta already feels like OXID: Bugs, Bugs, Bugs
<img width="478" alt="Bildschirmfoto 2019-09-05 um 17 42 45" src="https://user-images.githubusercontent.com/4060287/64357433-eca20b00-d004-11e9-81b4-fc03a7677549.png">
<img width="291" alt="Bildschirmfoto 2019-09-05 um 17 42 35" src="https://user-images.githubusercontent.com/4060287/64357436-ed3aa180-d004-11e9-90b7-c021edc4c575.png">

**Comment by khouloudbelguith** [comment]
@jansass, I'm trying to reproduce your exact issue with all information.
>sec 0:42, you add ProductA, Size M, 4€ at 11€/kg
sec 0:48, in Cart ProductA, Size M, 4€ at 8€/kg
This is why unit prices are messed up - you are not checking the results properly.

As I said before it is wrong calculated on the product page as reported in this ticket: #9901, it is reported & added to our bug roadmap, that's why I have differnt prices.
Your issue about unit price = 0 in the shopping cart => it is OK in my case.
Thanks!

**Comment by jansass** [comment]
@khouloudbelguith 

khouloudbelguith, its not: You are adding a product aat 11€/kg then go to cart where is shows 8€/kg. Were are the missing 3€/kg? Its you own video!

And its wrong in eighter places: on product page you add base price, on checkout you dont. Since we are working with 0.001 base prices (to make adding it easier), our fault shows on cart; yours show on product page.

It still the same error: unit price is wrong. Still wrong. Or again wrong. I dont care, its a massive bug which disable the use of prestashop in the european union.

Ands its an old bug, it existed in 1.4 already..

**Comment by jansass** [comment]
Im closing this issue since talking to you does not lead anywhere. 

_Moderated by @matks : I have removed the aggressive statement below as I think it is not helping either the project and this bug_

**Comment by khouloudbelguith** [comment]
@jansass, your issue is duplicate of https://github.com/PrestaShop/PrestaShop/issues/9603
It is added to our bug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9603
