### ISSUE TITLE
Stop using Tools::displayPrice as it is deprecated

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15427]
`Tools::displayPrice()` is deprecated from 1.7.6.0

We need to update all usages of this function in the project and use `Locale::formatPrice()` instead

**Comment by Progi1984** [comment]
I replaced all matches in Core, else in PriceFormatter because PriceFormatter is bad used (instance of class instead of DependencyInjection) which needs a special PR for this.

**Comment by loetje88** [comment]
Same problem well over 6 months later.

What was the fix that was applied? Unfortunately it seems like that did not work.

User Deprecated: Tools::displayPrice() is deprecated since version 1.7.6.0. Use PrestaShop\PrestaShop\Core\Localization\Locale::formatPrice() instead.

**Comment by matks** [comment]
> Same problem well over 6 months later.
> 
> What was the fix that was applied? Unfortunately it seems like that did not work.
> 
> User Deprecated: Tools::displayPrice() is deprecated since version 1.7.6.0. Use PrestaShop\PrestaShop\Core\Localization\Locale::formatPrice() instead.

PR which supposedly fixed this issue is https://github.com/PrestaShop/PrestaShop/pull/15448

However why do you say this is a problem ? Using a deprecated function is not a bad thing, it's only an issue because you know that, in the future at upgrade time, you will need to stop using it.

**Comment by Gipielle** [comment]
I got this error with prestashop 1.7.6.5:

[2020-05-27 16:46:53] php.INFO: User Deprecated: Tools::displayPrice() is deprecated since version 1.7.6.0. Use PrestaShop\PrestaShop\Core\Localization\Locale::formatPrice() instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Tools::displayPrice() is deprecated since version 1.7.6.0. Use PrestaShop\\PrestaShop\\Core\\Localization\\Locale::formatPrice() instead. at /xx/classes/Tools.php:759)"} []

**Comment by matks** [comment]
This message tells you that you are using a function that is [deprecated](https://en.wikipedia.org/wiki/Deprecation#Software_deprecation) and you should use something else: `PrestaShop\PrestaShop\Core\Localization\Locale::formatPrice()`

**Comment by Gipielle** [comment]
Hello, but the classes/Tools.php is prestashop 1.7.6.5 standard file

**Comment by matks** [comment]
> Hello, but the classes/Tools.php is prestashop 1.7.6.5 standard file

Yes, it stays there in order to help you migrate 😉 

The idea is the following:
1) People use Tools
2) We need to modify Tools behavior, so we create a new class that works better: Locale
3) We add this deprecation message to tell people "Stop using tools, use Locale !"
4) People who use Tools see the message and modify their code to use Locale
5) When every people using Tools have stopped using it, we remove it

So we keep Tools inside the code to allow it to warn people. If we removed it directly, you would have a "Class not found" error instead of the deprecation message 😉 . We keep the old class to use it to forward our message 😄 but in next major version of PrestaShop, the old code will be gone.

**Comment by Ploppy3** [comment]
But `Locale::formatPrice()` is not accessible from smarty template, which does not make a it a good alternative. What can I do to display prices?

**Comment by kpodemski** [comment]
@Ploppy3 normally, your prices should be formatted at the controller level, not at the view level :)

**Comment by Ploppy3** [comment]
@kpodemski but that's not always the case, example: credit slips, and there is no way to format this price other than using tools.

**Comment by kpodemski** [comment]
@Ploppy3 you mean directly in .pdf files?

**Comment by Ploppy3** [comment]
@kpodemski no, in usual smarty template files.

**Comment by kpodemski** [comment]
@Ploppy3 yes, sorry, I meant .tpl files 😅

Well, they could be improved to move the proper logic outside of the view. That will probably be part of the task of removing Tools::displayPrice from the core.

**Comment by Ploppy3** [comment]
@kpodemski So i'll use Tools for now as it seems to be impossible otherwise.

**Comment by kpodemski** [comment]
@Ploppy3 without modifying the back-end part behind the credit slips, yes

Don't worry, we'll provide proper information on how to handle such issues in the future after the removal of `Tools::displayPrice`
