### ISSUE TITLE
Add Albanian and Korean to the installer

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15438]
**Is your feature request related to a problem?**
It is not a bug, but a default parameter to update.

**Describe the solution you'd like**
For the 1.7.7 version, following recent activity on Crowdin, it would be nice to add Albanian and Korean to the PrestaShop installer.

**Why?**
Since the installer helps you installing PrestaShop, it must be accessible to as many people as possible. And this is why it is available in many languages. If a language has a high level of translation on Crowdin, which is the case for both Albanian and Korean projects, without being available in the installer, we should consider adding it.

**How?**
Here, a pull request must be created to add a new folder in _install-dev/langs_, named with the code of the language we want to add.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team
