### ISSUE TITLE
Products are not displayed when deselect "show products from subcategory".

### ISSUE THREAD

**Issue by Ortezjan** [PrestaShop/PrestaShop#15430]
**Describe the bug**

Faceted search products are not displayed when I deselect "show products from subcategory".

**To Reproduce**
1. Go to 'faceted search module'
2. Click on 'deselect "show products from subcategory".'
3. Products are not displayed.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Ortezjan,

This a normal behavior.
Disabling this option => Products from in subcategories will not be displayed.
For example, we have categories:
1. Clothes (level1)
2. Men (level2)

In the Clothes category => there is no products displayed
In the Men category => products are displayed.
I attached a screen record
https://drive.google.com/file/d/1J_hzT99dL8PghXVVn7olasR3-NdNrFjX/view
Thanks to check & feedback.

**Comment by Ortezjan** [comment]
But in my case in both category is no products displayed.

**Comment by khouloudbelguith** [comment]
@Ortezjan, and have you products associated to those categories?
Thanks!

**Comment by Ortezjan** [comment]
Yes correct.

**Comment by khouloudbelguith** [comment]
Hi @Ortezjan,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Ortezjan** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/49912771/64359053-dea1b980-d007-11e9-8924-02d3e34e80f1.png)
![Screenshot_3](https://user-images.githubusercontent.com/49912771/64359054-dea1b980-d007-11e9-8065-b7f109fb249d.png)
![Screenshot_4](https://user-images.githubusercontent.com/49912771/64359055-dea1b980-d007-11e9-8f62-9487f2a40d1d.png)
![Screenshot_5](https://user-images.githubusercontent.com/49912771/64359057-dea1b980-d007-11e9-9c21-86e46abaa1ef.png)

**Comment by Ortezjan** [comment]
Hosting company OVH. Shared hosting, PHP version 1.7.6.1. Rest information I don't have an idea of how I can find.

**Comment by khouloudbelguith** [comment]
@Ortezjan, in your screenshot
![image](https://user-images.githubusercontent.com/16067358/64359387-1dcc0c80-d000-11e9-8134-bd6bbe06954d.png)
The main category of those products is not "Baby Cotton".
In my case
![image](https://user-images.githubusercontent.com/16067358/64359466-48b66080-d000-11e9-8380-818a49b3b152.png)

Thanks!

**Comment by Ortezjan** [comment]
So when I
![Screenshot_7](https://user-images.githubusercontent.com/49912771/64359920-a7340c80-d009-11e9-9ffa-64141d5762fa.png)
![Screenshot_8](https://user-images.githubusercontent.com/49912771/64359922-a7340c80-d009-11e9-9608-9cc063eadf4e.png)

 go to this category then those categories are empty. Or show only 1 or 2 product. 
![Screenshot_6](https://user-images.githubusercontent.com/49912771/64359807-620fda80-d009-11e9-904b-0f0b7dcee419.png)

**Comment by khouloudbelguith** [comment]
@Ortezjan, so they are displayed when selecting the main category.
Thanks!

**Comment by Ortezjan** [comment]
But i have selected in the default category a lot of products but showing only 1?

![Screenshot_9](https://user-images.githubusercontent.com/49912771/64360355-9932bb80-d00a-11e9-874a-e81e0a372c51.png)

**Comment by khouloudbelguith** [comment]
@Ortezjan, in our case, using the default theme Classic & the ps_facetedsearch v3.2.1. when "show products from subcategory" is disabled => the category filter is not displayed as a filter in the FO.
https://drive.google.com/file/d/1d1ulMbUu2YVmIC-NY2VBW6VtRDEjuL4F/view
Could you please check the issue with the theme author & feedback.
Thanks!

**Comment by PierreRambaud** [comment]
@Ortezjan Hi, any news? :sweat_smile:

**Comment by simulbeni** [comment]
Hi,

I have same issue. We have same products in two different categories. first one is main category and second one is sub category of that main category.

when we select main category as default category than subcategory always empty. When we select subcategory as main category than those products are not appearing in main category. 

I did reaserch on this issue. reason is that in where condition WHERE p.id_category_default='35' AND cp.id_category='35'.

This means faceted search work with default category only. There is no meaning of adding products in subcategory.

This is happening when we disable "display product from subcategory". We have to disable this option otherwise its not following sorting options.

This module two option is contradicting each other. Either use sorting option or use "Show products from subcategories"

We are stucked and our sales are effected by this issue. 

Please advice me as soon as possible.

Thanks

**Comment by khouloudbelguith** [comment]
@beniwal, when the option "Show products from subcategories" is disabled
![image](https://user-images.githubusercontent.com/16067358/65975999-647a1e80-e467-11e9-86ae-f1f0679b019b.png)
Products will be displayed only in the main category
![image](https://user-images.githubusercontent.com/16067358/65976081-8673a100-e467-11e9-8675-26e79ccd16dd.png)
>We have to disable this option otherwise its not following sorting options.

Why it is not following sorting options? what is the exact contradiction? can you explain to us?

Thanks!

**Comment by simulbeni** [comment]
Hi @khouloudbelguith 

Issue is in front end.

To reproduce issue, disable "display product from subcategory". Add product A and B both in category "first one" as default category.

Than assign both products or one product to category "second one".

Now in front end you will see category "second one" empty.

If you select product B with default category "second one" than product B will disapear from category "first one".

I do consider that category "second one" is a subcategory of category "first one".

Thanks

**Comment by khouloudbelguith** [comment]
@beniwal, yes, I have the same behavior described by you.
This normal behavior.
First: you just disabled the option:
![image](https://user-images.githubusercontent.com/16067358/67198301-fe960c80-f3fe-11e9-9779-348b13a5fb9d.png)
That's why, the products, in the FO, will be displayed only in the main category.
Ping @marionf @PrestaShop/prestashop-product-team what do you think if we change this expression `Show products from subcategories` to `Products will be displayed only from the default category`? to be more clear.

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 

> Ping @marionf @PrestaShop/prestashop-product-team what do you think if we change this expression Show products from subcategories to Products will be displayed only from the default category? to be more clear.

I think wording is pretty clear here
If the option is set to no, products that belongs to a subcategory (as **main** one) are not displayed in the parent category.
Furthermore, "default" isn't suitable as we use it nowhere, we talk about **main category**

**Comment by simulbeni** [comment]
Its not clear. You not understanding my point. Please check attached screenshot.

Product is in category clothes, you can see in screenshot. But in front end its not showing. It display only when we enable "Show products from subcategories".

This issue specially comes when faceted search module enabled. 

![cat2](https://user-images.githubusercontent.com/437314/67406918-5f2a7280-f5d4-11e9-9090-ea2e3c5d1538.JPG)
![cat1](https://user-images.githubusercontent.com/437314/67406920-5f2a7280-f5d4-11e9-8c38-859c29c355ca.PNG)

After disabling faceted search it works fine and i can see products in category clothes.

![cat3](https://user-images.githubusercontent.com/437314/67407224-d52ed980-f5d4-11e9-9e9a-8ee092a1f5a2.JPG)

I have this demo online. If you want to look at it i can give you login.

Thanks

**Comment by Ortezjan** [comment]
Faceted search is broken now. They mean in this main category. I have the same problem as You Beniwal.
![Screenshot_3](https://user-images.githubusercontent.com/49912771/67407768-4dd36d00-f5b8-11e9-99ec-10c35ad4269c.png)

**Comment by simulbeni** [comment]
Why it works differently in faceted search and without faceted search. I added the reason behind it also but nobody is looking at it.

Here is the reason, ps_facetedsearch\src\Adapter\MySQL.php line number 139 its comparing all with AND condition. 

FACETED SEARCH MODULE IS LOOKING FOR id_category_default ONLY not other categories.

I replaced this code 

if (!empty($whereConditions)) {
                $query .= ' WHERE ' . implode(' AND ', $whereConditions);
            }

With 

if (!empty($whereConditions)) {

            $defaultcategoryindex = '';
            $categoryindex = '';
            foreach($whereConditions as $row => $value)
            {
                if(strstr($value,'p.id_category_default'))
                {
                    $defaultcategoryindex = $row;
                }
                else if(strstr($value,'cp.id_category'))
                {
                    $categoryindex = $row;
                }
            }
            if($defaultcategoryindex || $categoryindex ) {
                $query .= ' WHERE  (' . $whereConditions[$categoryindex] . ') AND ';
                unset($whereConditions[$defaultcategoryindex]);
                unset($whereConditions[$categoryindex]);
                $query .= '' . implode(' AND ', $whereConditions);
            }
            else
            {
                $query .= ' WHERE ' . implode(' AND ', $whereConditions);
            }

        }

This will start displaying products in category but faceted search will not work on that specific category.


Executed Query while fetching products from database (default)

SELECT COUNT(DISTINCT p.id_product) c FROM (SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position FROM pr_product p LEFT JOIN pr_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN pr_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN pr_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 ) INNER JOIN pr_category_product cp ON (p.id_product = cp.id_product) INNER JOIN pr_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) WHERE **_p.id_category_default='3' AND cp.id_category='3'_** AND p.visibility IN ('both', 'catalog') AND ps.id_shop='1' GROUP BY p.id_product) p

![cat4](https://user-images.githubusercontent.com/437314/67410846-53da4580-f5da-11e9-806b-47057ab8841e.JPG)

After Update in MySQL.php in faceted search

SELECT COUNT(DISTINCT p.id_product) c FROM (SELECT p.id_product, p.id_manufacturer, sa.quantity, p.condition, p.weight, p.price, cp.position FROM pr_product p LEFT JOIN pr_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN pr_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN pr_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 ) INNER JOIN pr_category_product cp ON (p.id_product = cp.id_product) INNER JOIN pr_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) WHERE **_(cp.id_category='3')_** AND p.visibility IN ('both', 'catalog') AND ps.id_shop='1' GROUP BY p.id_product) p

![cat5](https://user-images.githubusercontent.com/437314/67411058-a9165700-f5da-11e9-9c4a-283a7ec4fa54.JPG)

**Comment by marionf** [comment]
@beniwal 

> Product is in category clothes, you can see in screenshot. But in front end its not showing. It display only when we enable "Show products from subcategories".

Yes, this is exactly the wanted behavior if "Show products from subcategories" is disabled. 
You just have to enable it if you want to display the products in clothes category

**Comment by simulbeni** [comment]
Why shoudl i use that. Product is in category clothes but its not set as default category.

I explained it in detail but you guys just sticked to what you have. If a product is assigned to a category it must be displayed into that category whatever position is there , set as main/default category or not. faceted search is enabled or not.

I understand really well when "Show products from subcategories" is enabled than its not possible to sort by position.

**Comment by simulbeni** [comment]
> @beniwal
> 
> > Product is in category clothes, you can see in screenshot. But in front end its not showing. It display only when we enable "Show products from subcategories".
> 
> Yes, this is exactly the wanted behavior if "Show products from subcategories" is disabled.
> You just have to enable it if you want to display the products in clothes category

I know filter module from last 10 years. We were thinking that prestashop will improve it to some better solution like add it to all product listing pages eg, search, manufacturer, price drops etc.

But what i can see is that its just reducing functions on the name of improvements. I see why people getting fadeup day by day from prestashop. 

Please keep in mind that what happened to OSCOMMERCE.

**Comment by marionf** [comment]
> If a product is assigned to a category it must be displayed into that category

Not everyone want this behavior, that's why there is the option Show products from subcategories
If you enable it, the product will be displayed like you want

> I understand really well when "Show products from subcategories" is enabled than its not possible to sort by position.

I don't understand what you mean here, could you explain how to reproduce the problem ?

**Comment by simulbeni** [comment]
I have complaint that relation between products and category is working different with and without module ps_faceted_search.

After enabling module faceted search there is no product in this category but when i disable it there is two products.

http://techarise.co.in/prestashop1761/3-clothes

I can give you access to this admin also on your email. Lot of information already added in previous comments. If a developer looks at it this issue can be replicated in 30 secs.

Please check this comment properly.
https://github.com/PrestaShop/PrestaShop/issues/15430#issuecomment-545490091

**Comment by marionf** [comment]
> I have complaint that relation between products and category is working different with and without module ps_faceted_search.

Yes, it's working different if Show products from subcategory is disabled. But it's the same if Show products from subcategory is enabled.

> After enabling module faceted search there is no product in this category but when i disable it there is two products.

Yes, there is no product because Show products from subcategory is disabled. If you enable it you will see your products.

> Please check this comment properly.

I already see it, and you tell it yourself: "It display only when we enable "Show products from subcategories"."

Why you don't enable this option if it solves your issue ?

**Comment by PierreRambaud** [comment]
@beniwal This is just because without faceted search, you have no filters, and the behaviour is => `Show products from subcategories`

**Comment by simulbeni** [comment]
> I already see it, and you tell it yourself: "It display only when we enable "Show products from subcategories"."
> 
> Why you don't enable this option if it solves your issue ?

With enabling this "Show products from subcategories" i cannot do product position inside category.

**Comment by marionf** [comment]
> With enabling this "Show products from subcategories" i cannot do product position inside category.

Could you explain how to reproduce the problem ?

**Comment by davideapvd** [comment]
Same here,
when selecting show product from subcategories we cannot order products that are in the subcategory because in the admin page when filtering by categories no products in the subcategories are shown so we cannot tweak their position ordering.
so for example if I have
```

  Cat1
    Cat2
```

and 
```

   Prod1 -> Cat1
   Prod2 -> Cat2 (BUT NO CAT1)

```
if faceted search is enabled and "show products in subcategories" is selected,  when navigating in the frontend for Cat1 I can see both products but I cannot tweak the order position for Prod2, this is probably the bug. But if I uncheck that option, no product is shown in Cat1 or Cat2 unless the product are in those category as "Default category". What we want is disabling "show products in subcategories" and show in the frontend products not only based in the default category (this should only control breadcrumbs for example), but pick categories association as is.

**Comment by davideapvd** [comment]
> I replaced this code
> With
> [...] 
> if (!empty($whereConditions)) {
> [...]

@beniwal this proposal somewhat works, but breaks the faceted navigation filters

**Comment by colinegin** [comment]
@marionf do you think we should reopen this issue ?

**Comment by marionf** [comment]
Duplicate of #14003
