### ISSUE TITLE
Add Malagasy, Uzbek, and Tagalog as new supported languages 

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15435]
**Is your feature request related to a problem?**
It is not a bug, but a default parameter to update.

**Describe the solution you'd like**
For the 1.7.7 version, following recent activity on Crowdin, it would be nice to add Malagasy, Uzbek, and Tagalog as supported languages in PrestaShop.

**Why?**
Some languages are available in Crowdin for translation but not available in PrestaShop because of a low completion level on Crowdin. But when translators are very active and/or showed interest in an unavailable language, it could be nice to add it to the software so that they can see the results of their Crowdin translations quickly in their own shop, and therefore continue translation work.

**How?**
Here is the process I know: to activate a language and have it available in the language drop-down, you need to add it to files _[all_languages.json](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json)_ and _[app/Resources/legacy-to-standard-locales.json](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/legacy-to-standard-locales.json)_.

UPDATE: the [TranslationFiles repository](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/available_languages.json) must be updated!

Once the language is officially available (after the release of the version adding it), I will have to update the Locale table in [Sandrine](https://sandrine.prestashop.com/admin/product/locale/dashboard).

- [x] Malagasy
- [x] Uzbek
- [x] Tagalog

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by LouiseBonnard** [comment]
Is there something I've missed in the process to activate a language in PrestaShop? I can see that Tagalog and Uzbek are listed in the two files, yet they are not available in the software (neither through the localization pack nor the International > Translations).
🤔

**Comment by LouiseBonnard** [comment]
UPDATE: the [TranslationFiles repository](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/available_languages.json) must be updated!

**Comment by Robin-Fischer-PS** [comment]
OK for Malagasy.

**Comment by LouiseBonnard** [comment]
MUCHAS GRACIAS, @Progi1984 !

**Comment by matks** [comment]
@Progi1984 Could you help us on the [Developer Documentation](https://github.com/PrestaShop/docs) by writing a "How to add new supported languages" how-to ? I dont know how to do it, so I'd be happy to learn and our contributors too I think 😄

**Comment by Progi1984** [comment]
@matks Good idea ;)
