### ISSUE TITLE
Carrier not updating after zone change - VAT related

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#15434]
If you set in BO->International->VAT-> Based on “Invoice address” (which is correct setting in some cases), the list of carriers will not update if you change the country under “Shipping Address”.
If it is set to delivery address, it works fine:
![](https://user-images.githubusercontent.com/31688689/64414873-74832600-d094-11e9-970a-9c7c8a4c1861.png)

**To Reproduce**

1. You need to set up a carrier with at least two zones and different delivery prices for each zone
1. You can even try and have two different carriers, one for each zone
1. Go to checkout, do not register, just change the delivery country
1. Observe if the shipping price and carrier will change

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

THanks for your report.
I checked with PS1.7.6.1.
The shipping price and the carrier will change
I attached a screen record
https://drive.google.com/file/d/1gODyg7b8hOY5cKEkP6Jl8z81v6Wv0O-8/view
Thanks to check & feedback.

**Comment by mrabsinthe** [comment]
Hi @khouloudbelguith ,
can you please try the same with VAT based on Invoice address?

**Comment by khouloudbelguith** [comment]
@mrabsinthe, it is OK also
https://drive.google.com/file/d/1ckn_isRBYi6lKI4y7QB5cWyL9zy_PxL_/view
Thanks!

**Comment by mrabsinthe** [comment]
OK, thank you, I need to dig deeper.

**Comment by khouloudbelguith** [comment]
@mrabsinthe, thanks!

Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
