### ISSUE TITLE
Wrong sql query in gamification module

### ISSUE THREAD

**Issue by R0bb12** [PrestaShop/PrestaShop#15441]
**Describe the bug**
In Gamification module, no order badge are on. The SQL statement for these badges are different from others, PREFIX string is not in the statement.

Using gamification file:
https://gamification.prestashop.com/json/data_EN_IDR_ID.json

At condition id 53, 54, 55 and 56 (table ps_orders not exists):
`SELECT COUNT(*) FROM ps_orders`

Example with condition 52: (PREFIX is used, which is good)
`SELECT COUNT(*) FROM PREFIX_cart`

**To Reproduce**
1. Go to Gamification module
2. Have some orders in database
3. Scroll down to the order badge
4. See order badge not on 

**Additional information**
PrestaShop version: 1.7.5.2
Gamification version: 2.3.1
PHP 7

**Comment by khouloudbelguith** [comment]
Hi @R0bb12,

So, in your case; in the Merchant Expertise configuration page, ACHIEVEMENTS section, when you select "Type" Orders => order badge not on?

![image](https://user-images.githubusercontent.com/16067358/64420828-06d8f900-d098-11e9-8335-52fd68c2fbb9.png)

Thanks!

**Comment by R0bb12** [comment]
Yes, all others are good but not Orders
![image](https://user-images.githubusercontent.com/5173984/64426026-c1272b00-d0ad-11e9-8695-be0bdb53854f.png)

**Comment by khouloudbelguith** [comment]
@R0bb12, in my case, I did not manage to reproduce the issue with PS1.7.6.1 & gamification module version 2.3.1.
https://drive.google.com/file/d/19AvrgjVry40gbqRzNL99idmAxv8UwwHy/view
In your case, the PREFIX your database is not `ps`?

**Comment by R0bb12** [comment]
On my database, table condition:
`SELECT COUNT(*)   FROM ps_orders WHERE reference NOT IN (XKBKNABJK",   "OHSATSERP", "FFATNOMMJ", "UOYEVOLI",   "KHWLILZLL")"`
All other queries use PREFIX before the table name, so it should be `PREFIX_orders`

My prefix is a random value like abc123 ->abc123_orders

**Comment by khouloudbelguith** [comment]
@R0bb12, thanks!
I manage to reproduce the issue with PS1.7.6.1 when installing a shop with PREFIX not `ps_`.
![image](https://user-images.githubusercontent.com/16067358/64432445-6d6c1000-d0b4-11e9-9d53-a1bbf9898dda.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by R0bb12** [comment]
Thanks, I didn't find the source code of sql queries for gamification so I can't send a pull request.

**Comment by Progi1984** [comment]
@R0bb12 Hello have you got always the problem ?

**Comment by hibatallahAouadni** [comment]
still reproduce with PS1782

**Comment by Progi1984** [comment]
@eternoendless or @PierreRambaud Could you move this issue to the gamification repository in PrestaShopCorp organisation ?

**Comment by eternoendless** [comment]
@Progi1984 AFAIK we can't move issues across organizations, so the issue must be reopened here: https://github.com/PrestaShopCorp/gamification/issues

**Comment by Progi1984** [comment]
@R0bb12 Could you please reopen your issue there : https://github.com/PrestaShopCorp/gamification/issues/new ?
