### ISSUE TITLE
Warning when I use cache clear command

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15445]
**Describe the bug**
I get a warning when I use cache clear command

**To Reproduce**
Run `php ./bin/console cache:clear`
Get warning `Warning: Use of undefined constant _DB_SERVER_ - assumed '_DB_SERVER_' (this will throw an Error in a future version of PHP)`
alias ps_install='/Applications/MAMP/bin/php/php7.2.10/bin/php composer.phar install'

**Additional information**
PrestaShop version: develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @matks,

Is it the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15324?

Thanks!

**Comment by matks** [comment]
Yes, this is a duplicate 👍

**Comment by khouloudbelguith** [comment]
Duplicate of #15324
