### ISSUE TITLE
Reduce client view in Customer Page 1/2 

### ISSUE THREAD

**Issue by guirou62** [PrestaShop/PrestaShop#15444]
**Is your feature request related to a problem? Please describe.**
Yes, it is. When I look a customer profile, which is a very old and very good customer, my page is really high !!
If we have this important list + some modules, this page become very very slow.
=> I have many customers in this case

**Describe the solution you'd like**
If it's possible to reduce all these informations such as see only 20 last carts, 20 last orders. Same for Products bought by the customer : Top 20 products more bought by the customer.
Every time we want to have more than 20, you have "See more" to display 20 others carts, orders or products.

**Describe alternatives you've considered**
None actually

**Additional context**
Screenshots about only one page/customer : [https://drive.google.com/drive/folders/13TPktWYVdz1Va985wvQH0g0qBHJngt_Z?usp=sharing](https://drive.google.com/drive/folders/13TPktWYVdz1Va985wvQH0g0qBHJngt_Z?usp=sharing)

**Comment by khouloudbelguith** [comment]
Hi @guirou62,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by guirou62** [comment]
I found the same way on the page to add an order from the BO.

I have same informations (carts and orders) from 2016. Actually, we don't have same products as now, many things/products have changed.

Maybe it will be easier to print the 10/20 last orders/carts and add 10 by 10 with Ajax or something like that.

**Comment by marionf** [comment]
@TristanLDD 

This improvement is about customer view page & order add page, wdyt about adding a "number of items" with a dropdown and/or a pagination system

![capture d'écran_1997](https://user-images.githubusercontent.com/13449658/65126654-3fad9200-d9f7-11e9-9ee3-4d620d5354a3.png)

![capture d'écran_1999](https://user-images.githubusercontent.com/13449658/65127451-ba76ad00-d9f7-11e9-8353-b5c852002d64.png)

I ping also @MatShir as it's concern order page

**Comment by TristanLDD** [comment]
Let's add a simple pagination system from the UI Kit on both pages and limit the number of items to 20:
![Capture d’écran 2019-10-24 à 18 12 41](https://user-images.githubusercontent.com/27484094/67504589-f3a2dc80-f689-11e9-8d3d-0f7435106162.png)

**Comment by MatShir** [comment]
#16129 issue for the case in the order creation. 
Thanks @guirou62 for your feedbacks

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/31442. :-)
