### ISSUE TITLE
Blanck page BO after migration PS 1.7.6

### ISSUE THREAD

**Issue by Mamar25** [PrestaShop/PrestaShop#15455]
Hello,

I can not access the BO after the migration of my site (I am under PS 1.7.6), a blank page is displayed. However, the front office is normally displayed.

I can not solve the problem. I emptied the caches in dev and prod in var / cache and on the browser.

I passed define ('_PS_MODE_DEV_', false); from /config/defines.inc.php to true:

The following messages are displayed:

RuntimeException

The expected class of the "Symfony \ Bundle \ SwiftmailerBundle \ DependencyInjection \ Compiler \ RegisterPluginsPass" autoloader to set in the "/home/www/vendor/composer/../symfony/swiftmailer-bundle/DependencyInjection/Compiler/RegisterPluger" file . The file was found, but the class was not there, the name of the class or namespace probably has a typo.

in line 213 of DebugClassLoader.php

ClassNotFoundException

You attempted to load the "RegisterPluginsPass" class from the "Symfony \ Bundle \ SwiftmailerBundle \ DependencyInjection \ Compiler" namespace.
Did you forget a "use" statement for another namespace?

in line 28 of SwiftmailerBundle.php

I tried to modify the files concerned, but I can not solve the problem.

**Comment by khouloudbelguith** [comment]
Hi @Mamar25,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - Intl is installed & enabled on your server
 - Could you please try to rename the `autoupgrade` folder to `autoupgrade_old` into the path `/Project_Folder/modules/`
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Mamar25** [comment]
Hello,

In fact my problem is solved, but I do not know where it came from or how I managed to solve it. I thank you in any case for your message.

Thank you very much !

**Comment by mariem-abid** [comment]
Hi @Mamar25,

Thanks for your feedback.
Feel free to open a new one when needed.

**Comment by LilNick971** [comment]
Salut @Mamar25 

Je rencontre le même problème actuellement, est ce que tu te souviens comment tu la réglé ?
