### ISSUE TITLE
Uncaught Exception: Unable to load template 'file:catalog/_partials/miniatures/product.tpl'

### ISSUE THREAD

**Issue by sireris** [PrestaShop/PrestaShop#15450]
**Describe the bug**
Hi, i get this error tha i cant resolve someone can help me?
Uncaught Exception: Unable to load template 'file:catalog/_partials/miniatures/product.tpl'
Uncaught PHP Exception SmartyException: "Unable to load template 'file:catalog/_partials/miniatures/product.tpl'" at /web/htdocs/www.dottsalute.it/home/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php line 96
 product.tpl exist and it is in the right place, the permission are 755
the website works regural but only the backoffice doesn't work.
i have a child theme but i have only 2 modification. 

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

![1617424157_Screenshot_2019-09-05Unabletoloadtemplatefilecatalog_partialsminiaturesproducttpl(500InternalServerError)(1) thumb png fecc2ad445ab181480c95f9224a00e67](https://user-images.githubusercontent.com/41742637/64437042-cd1ee700-d0c5-11e9-8df7-582db062eb7c.png)
![430488869_Screenshot_2019-09-06AnErrorOccurredInternalServerError thumb png 617ab7fc95734daece6e1d6f68d6f1d4](https://user-images.githubusercontent.com/41742637/64437043-cd1ee700-d0c5-11e9-8287-ab3bca957c8c.png)
![203454925_Screenshot_2019-09-05Unabletoloadtemplatefilecatalog_partialsminiaturesproducttpl(500InternalServerError) thumb png d334423417b52b27587865bdb8d7a661](https://user-images.githubusercontent.com/41742637/64437044-cdb77d80-d0c5-11e9-80f3-ecc4e45db369.png)
![ScreenShoot](https://user-images.githubusercontent.com/41742637/64437045-cdb77d80-d0c5-11e9-82b6-a404760bf132.png)
i have the host on aruba linux hosting.

**Comment by khouloudbelguith** [comment]
Hi @sireris,

Does this issue occur after the custom modifications that you made?

Thanks!

**Comment by sireris** [comment]
No. The modification that i made was when i install prestashop and from the it works fine. i install some new template but i didnt use them. and now i deleted from ftp.

**Comment by khouloudbelguith** [comment]
@sireris, what is the exact page from the BO, this exception is displayed?

Thanks!

**Comment by sireris** [comment]
on login page
https://www.dottsalute.it/admin01/index.php?controller=AdminDashboard&token=fa6d4a148dd701c8e71149e92dbb0f06
when i put the credentials i receive the errro 500

**Comment by sireris** [comment]
I put on the debug mode now

**Comment by khouloudbelguith** [comment]
@sireris, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by sireris** [comment]
do i have to cancel almost the folders dev & prod? or only whats inside

**Comment by khouloudbelguith** [comment]
@sireris, dev & prod files.
Thanks!

**Comment by sireris** [comment]
i delete everythin inside the folders but no change.

**Comment by khouloudbelguith** [comment]
@sireris, you are using your child theme or your theme by default Classic?
Thanks!

**Comment by sireris** [comment]
i'm using child_classic. these are the changes thai did with child theme
![child-classic](https://user-images.githubusercontent.com/41742637/64440998-4cfc7f80-d0cd-11e9-928d-5dd56fbf9cdd.png)

**Comment by khouloudbelguith** [comment]
@sireris, could you please try to switch to the classic theme & check the issue if it occurs again?
Thanks!

**Comment by sireris** [comment]
but i cannot enter to backoffice. can i do on ftp?

**Comment by khouloudbelguith** [comment]
@sireris, in your Database, table ps_shop
![image](https://user-images.githubusercontent.com/16067358/64441673-37378c00-d0c6-11e9-8fa0-63c9eaac41be.png)

Thanks!

**Comment by sireris** [comment]
Done but nothing changes. You're so nice that you are helping me 
![classic-theme](https://user-images.githubusercontent.com/41742637/64442370-f2185780-d0cf-11e9-9f14-c63ee5ed19b9.png)
thanks

**Comment by khouloudbelguith** [comment]
@sireris, Could you please try to clear cache manually & Clear cache from your browser.

Thanks!

**Comment by khouloudbelguith** [comment]
@sireris, It could also be a server permission issue.

﻿Try 777 on your files to test if this is the case then revert to safer permissions.

Thanks!

**Comment by sireris** [comment]
Ok. The permissions do I have do change all files in the server? Or only the folder of themes?

**Comment by khouloudbelguith** [comment]
@sireris, all files on your server.
Thanks!

**Comment by sireris** [comment]
Hi changing permission dosen't work. i change fro 755 to 777 and nothing. i'm changing in 755 and see but i'm affraid it will not work. I can do a zero installation but the problem are all the products.

**Comment by sireris** [comment]
Hi i found the problem i think but i didn't resolve it. I delete in modules ps_specials and backoffice turn on but when i go to themes and click "homepage configuration" it givrs me the same problem and create the folder "ps_specials" again. Can someone have the same problem.
![Screenshot_2019-09-09 Tema Logo Tema • DottSalute it](https://user-images.githubusercontent.com/41742637/64513867-c1ac0580-d2e9-11e9-9741-2f4c2f2a75ac.png)

**Comment by khouloudbelguith** [comment]
@sireris, the ps_specials module is added as a dependency in your child theme?
Did you use the ps_specials module in your child_theme/config/theme.yml?
Thanks!

**Comment by sireris** [comment]
no in my child theme there is no dependency. I create child theme from prestashop and use it but i diddn't add nothing.

**Comment by khouloudbelguith** [comment]
@sireris, by default, ps_specials is not installed in PrestaShop, you need to install it manually.
Could you please try with this child theme
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/3595200/childtheme-example.zip)
Cloned from this [link](https://github.com/PrestaShop/childtheme-example).
In my case, with PS1.7.6.1, I'm using the child theme & I installed the ps_specials module manually & it is OK.
https://drive.google.com/file/d/1K8tLJU9iAXNMCz7gH1eoINUCEXpOQmyv/view
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @sireris,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by bcsirt** [comment]
Hi khouloudbelguith ! 
I don't understand why you feel compelled to answer when you don't have the right answer ?
