### ISSUE TITLE
PS 1.7.6.1 product redirect error

### ISSUE THREAD

**Issue by dreamtheme** [PrestaShop/PrestaShop#15462]
**Describe the bug**
After upgrade from 1.7.5.2 to 1.7.6.1 when entering an product URL without language prefix in the URL like /en/ or /fr/ for example - https:/mydomain.com/ps17/3-clothes should redirect to https:/mydomain.com/ps17/en/3-clothes but it does not. It works before the installation is upgraded.

**To Reproduce**
1. Install PS 1.7.5.2 and install additional language (localization pack)
2. upgrade from 1.7.5.2 to 1.7.6.1
3. try to directly open url like https:/mydomain.com/ps17/3-clothes and see if redirects to the appropriate language set.
4. Additionally it seems that the upgraded 1.7.6.1 re-generate different .htaccess than clean installed 1.7.6.1

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2
Server: Litespeed.

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

I did not manage to reproduce the issue with PS1.7.6.1 fresh install & with PS1.7.6.1 after an upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0.
I attached a screen record
[redirection URL.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3589974/redirection.URL.webm.zip)
Thanks to check & feedback

**Comment by dreamtheme** [comment]
@khouloudbelguith Seems the issue is that product SEO URLs are changed from 1.7.5.2 to 1.7.6.0 so static links from old product urls produce this. 
For example, if you have 1.7.5.2 generated product URL that's looks like http://mydomain.com/ps17/20-96-example-product.html in 1.7.6.0 its changed to http://mydomain.com/ps17/20-example-product.html, so if you have old link in text editor for example, this is where the problem occur. 
I guess its fine. you can close that.

**Comment by khouloudbelguith** [comment]
@dreamtheme, Thanks for your feedback.
Yes, this behavior is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/13009
I close the issue, feel free to open a new one when needed.

Thanks!
