### ISSUE TITLE
url parameters no longer accessible in backOfficeHeader hook

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#15466]
Hi

Seems to be quite a serious issue which has appeared in Prestashop 1.7.6.0, the url parameters are no longer available in the hook backOfficeHeader.  These were available prior to 1.7.6.0 (using $_GET or Tools::getValue())

Example code:

public function hookBackOfficeHeader($params)
{
    var_dump($_GET)
}

The above returns an empty array

public function hookBackOfficeHeader($params)
{
    var_dump($params)
}

The above produces a $params array devoid of any url parameters or the Symphony request object.

Please advise as this is quite a serious issue which affects all of my modules.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

I did not manage to reproduce the issue with PS1.7.6.1 & the ps_faviconnotificationbo module which is using the hook BackOfficeHeader.
![image](https://user-images.githubusercontent.com/16067358/64522690-78ac7f00-d2f2-11e9-8aee-b4d1827f7225.png)

I have this response after adding `var_dump($params)`

```
/projet/QA/1761new/modules/ps_faviconnotificationbo/ps_faviconnotificationbo.php:260:
array (size=3)
  'cookie' => 
    object(Cookie)[12]
      protected '_content' => 
        array (size=12)
          'date_add' => string '2019-09-06 15:10:08' (length=19)
          'id_lang' => int 1
          'detect_language' => string '1' (length=1)
          'id_employee' => string '1' (length=1)
          'email' => string 'demo@prestashop.com' (length=19)
          'profile' => string '1' (length=1)
          'passwd' => string '$2y$10$W/7lA/FsKZPEbbAjWN5HJ.C1StcRe4EV4Yarksuwd6fPHDbG7WlAG' (length=60)
          'remote_addr' => string '2130706433' (length=10)
          'shopContext' => string 's-1' (length=3)
          'submitFilterorder' => string '0' (length=1)
          'ordersorderFilter_a!date_add' => string '["",""]' (length=7)
          'checksum' => string '955306578' (length=9)
      protected '_name' => string 'PrestaShop-6e12069c9677d278a43b43a555348f4a' (length=43)
      protected '_expire' => int 1569751741
      protected '_domain' => boolean false
      protected '_path' => string '/QA/1761new/' (length=12)
      protected 'cipherTool' => 
        object(PhpEncryption)[15]
      protected '_modified' => boolean false
      protected '_allow_writing' => boolean true
      protected '_salt' => string 'UH8GAOgn' (length=8)
      protected '_standalone' => boolean false
      protected '_secure' => boolean false
  'cart' => null
  'altern' => int 1
```
Thanks to check & feedback.

**Comment by musaffar-patel** [comment]
Hi

Your test is correct.  As described in the original message, there is no longer anyway to access the $_GET (url parameters) in the backOfficeHeader hook.

Prior to Prestashop 1.7.6 (in Prestashop 1.7.5 for example) in the hook backOfficeHeader you couild access the $_GET variables.  Eg:

public function hookBackOfficeHeader($params)
{
var_dump($_GET)
}

But in Prestashop 1.7.6 url parameters are no longer present, and they also do not exists in the $params array.

Hope this clarifies the issue.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
@musaffar-patel, I tried with `var_dump($_GET);` adding the `;` => it is well displayed
![image](https://user-images.githubusercontent.com/16067358/64531789-2bd3a300-d308-11e9-8298-9ece1bf26de6.png)

Thanks!

**Comment by musaffar-patel** [comment]
Hi

Does it work in AdminCustomers and Edit Product pages?  This is where I tried and the $_GET array did not contain url params such as product and customer ID.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
@musaffar-patel,

When editing a customer =>
```
/projet/QA/1761new/modules/ps_faviconnotificationbo/ps_faviconnotificationbo.php:259:
array (size=2)
  '_token' => string 'cKZ_r_Up6Ah8GGSnC5f0MuayRR6YCbN8_E_cppg1aQU' (length=43)
  'controller' => string 'AdminCustomers' (length=14)
```

When editing a product =>

```
/projet/QA/1761new/modules/ps_faviconnotificationbo/ps_faviconnotificationbo.php:259:
array (size=2)
  '_token' => string 'cKZ_r_Up6Ah8GGSnC5f0MuayRR6YCbN8_E_cppg1aQU' (length=43)
  'controller' => string 'AdminProducts' (length=13)
```

Thanks!

**Comment by musaffar-patel** [comment]
Hi

As you can see the $_GET array in your dump is missing the id_customer and id_product.  If you perform the same test in Prestashop 1.7.5.x they are present.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
@musaffar-patel, when trying to edit a product => it is similar to PS1.7.6.1
```
/projet/QA/1752/modules/ps_faviconnotificationbo/ps_faviconnotificationbo.php:259:
array (size=2)
  '_token' => string 'cKZ_r_Up6Ah8GGSnC5f0MuayRR6YCbN8_E_cppg1aQU' (length=43)
  'controller' => string 'AdminProducts' (length=13)
```

But editing a customer with PS1.7.5.2, we have a different response
```
/projet/QA/1752/modules/ps_faviconnotificationbo/ps_faviconnotificationbo.php:259:
array (size=5)
  'controller' => string 'AdminCustomers' (length=14)
  'id_customer' => string '1' (length=1)
  'updatecustomer' => string '' (length=0)
  'token' => string '2e1452ec5be6c397b49e054680211fea' (length=32)
  'controllerUri' => string 'AdminCustomers' (length=14)
```
So, with PS1.7.6, in the category page, some parameters are missing in the backofficeHeader hook.
With PS1.7.6, the Category page is migrated to Symfony.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Hi @musaffar-patel indeed on a migrated page, the `$params` does not contain the `$_GET` as it should not get this kind of data from here.

If you need to access these request data, I suggest using the `request_stack` service provided by Symfony.

To do this:
- build your module as a modern Symfony module (example https://github.com/friends-of-prestashop/demo-cqrs-hooks-usage-module and related doc on http://devdocs.prestashop.com)
- then you can hook your module on `displayBackOfficeHeader` and in the `hookBackOfficeHeader` action, request the service using `$this->get('request_stack');`

Complete example:
```

use Symfony\Component\VarDumper\VarDumper;

class MyModule extends Module
{

    public function hookBackOfficeHeader($params)
    {
        $requestStack = $this->get('request_stack');

        // use Symfony VarDumper instead of var_dump() , it provides a great display for variable dumps ;)
        VarDumper::dump($requestStack);
        die();
    }
    

    public function install()
    {
        return parent::install() &&
            $this->registerHook('displayBackOfficeHeader')
        ;
    }
}
```

You can get all the data you need using the right services provided by Symfony 😉give it a look, you'll see you'll have plenty of wonderful information now available !

I think this should answer your question 😉then I close this ticket
