### ISSUE TITLE
Remove fields from the registration form

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#15467]
Hello, how to remove some fields from the registration form?

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

In your BO => Shop Parameters => Customer Settings => Customers Tab
You can disable the `Ask for birth date` & the `Enable partner offers` options.
![image](https://user-images.githubusercontent.com/16067358/64518597-5ca4df80-d2ea-11e9-9023-823487a21647.png)

Thanks to check & feedback

**Comment by TemKaSD** [comment]
Me need gender

**Comment by khouloudbelguith** [comment]
@TemKaSD, id you delete all Titles in the BO => Shop Parameters => Customer Settings => Titles Tab => this option will not displayed in the FO.
![image](https://user-images.githubusercontent.com/16067358/64535950-1e221b80-d310-11e9-9af6-6554461841d3.png)

Thanks to check & feedback.

**Comment by TemKaSD** [comment]
@khouloudbelguith Thanks

**Comment by khouloudbelguith** [comment]
@TemKaSD, You are welcome!
Feel free to open a new one when needed.

Thanks!
