### ISSUE TITLE
The email is already used, please choose another one or sign in 

### ISSUE THREAD

**Issue by johanmeer** [PrestaShop/PrestaShop#15468]
Hi, in previous versions i had a override for this, since 1.7.6 i receive this error when i checkout as guest and there is already an account for this e-mail adress:

The email is already used, please choose another one or sign in 

Customers will go away if they won't do a password reset.

Site is running on 1.7.6 with Php 7.2.22

I saw some other reporting about this problem but no sollutions.

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Could you please confirm these steps to reproduce your issue:
1. You have an old customer registered with an email demo@prestashop.com (for example)
2. This customer try to sign in as a guest with the same email demo@prestashop.com
3. You have an error "The email is already used"?

Thanks!

**Comment by johanmeer** [comment]
Hi, i can confirm the 3 steps, that is right.

**Comment by khouloudbelguith** [comment]
@johanmeer, but this is normal behavior.
How can we have different customers with the same address email => this is incorrect.
In fact, we have another issue related to this, it will be fixed.
"Guest account is not transformed into a customer account, it creates a second account"=> incorrect => it is added to our bug roadmap => issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10122

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
