### ISSUE TITLE
Customer search - admin new order not work

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#15471]
**Describe the bug**
In admin > orders > new order > when search customer, presta gives error 500: 
/index.php/sell/customers/search?_token=4cdWeG5A_3UgEEu0b5mT8vjQgIe4CWt8Lc9r-4DyXhE&ajax=1&customer_search=xxxx

**To Reproduce**
1. Go to 'Admin > Orders'
2. Click on 'New order'
3. See error

**Screenshots**
![customer-search-01](https://user-images.githubusercontent.com/37780517/64523876-90d5cb80-d2fd-11e9-9dae-90821b4ef664.jpg)![customer-search-02](https://user-images.githubusercontent.com/37780517/64523875-90d5cb80-d2fd-11e9-86d8-47ff8fcf44f1.jpg)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @TaccCZ,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1FRObfSUdUzlqQtOowVg_E65JAKr9igeZ/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TaccCZ** [comment]
Hi @khouloudbelguith ,

- server setup and configuration
[customer-search-server-apache.txt](https://github.com/PrestaShop/PrestaShop/files/3590445/customer-search-server-apache.txt)
[customer-search-server-php.txt](https://github.com/PrestaShop/PrestaShop/files/3590446/customer-search-server-php.txt)
I have older prestashop (version 1.7.5.2) on same server and customer search works good.

- PrestaShop version (source)
![customer-search-version-presta](https://user-images.githubusercontent.com/37780517/64530891-7821e180-d30e-11e9-95f5-16e2c1110175.jpg)

- debug mode report + PHP error logs
https://www.loom.com/share/9f8aeb8a1e5b4c97b1a500a36bf7a59e

- apache error log
no errors

**Comment by khouloudbelguith** [comment]
@TaccCZ, what is the exact language of your employee did you use?
Intl is installed & enabled on your server?
Is the collation of the database utf8_general_ci?
Thanks!

**Comment by TaccCZ** [comment]
@khouloudbelguith 
- Language of employee is Czech (CZ)
- Intl is installed
![customer-search-intl](https://user-images.githubusercontent.com/37780517/64533531-f92fa780-d313-11e9-8a50-5b181297a8cb.jpg)

- Database is utf8_general_ci but some tables are utf8_unicode_ci as:
-- ps_admin_filter, ps_attribute, ps_attribute_group, ps_attribute_group_lang, ps_attribute_group_shop, ps_attribute_lang, ps_attribute_shop, ps_lang, ps_lang_shop, ps_module_history


EDIT: as I wrote before, search works correct on the same server with the same configuration and the same type of database. On a prestashop 1.7.5.2

Thanks

**Comment by khouloudbelguith** [comment]
@TaccCZ, thanks for your feedback.
In my case, I tried with Czech & it is Ok.
https://drive.google.com/file/d/13t7xfxUOKso8DqNlCy4mP3MAOHGnCLAy/view
Could you please navigate to your BO => International => Translations page => Update your language
![image](https://user-images.githubusercontent.com/16067358/64537034-051a6a00-d312-11e9-9fc7-861ff25fb408.png)


Thanks!

**Comment by TaccCZ** [comment]
@khouloudbelguith 
Hi, i Updated language, but no change :( Still does not work.

**Comment by khouloudbelguith** [comment]
@TaccCZ, if you try with another language =>  the issue occurs again?

Thanks!

**Comment by TaccCZ** [comment]
@khouloudbelguith , Yes. If i change to default english, issue is the same.

**Comment by khouloudbelguith** [comment]
@TaccCZ, Open the Project_Folder/config/config.inc.php file, and search this code:
`setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');` & try to comment it.
 (`//setlocale(LC_CTYPE, $locale.’.UTF-8′, $locale.’.utf8′);`) 

Clear cache from your shop & your browser & check & feedback.

**Comment by TaccCZ** [comment]
@khouloudbelguith > no change,
**Now give me error log:**
3. [Tue Sep 10 10:42:56.138593 2019] [proxy_fcgi:error] [pid 31321:tid 140164595287808] [client 90.180.236.159:53811] AH01071: Got error 'Primary script unknown\n', referer: xxxxx/admin/index.php/sell/catalog/products/347?_token=_eFuZoGcxA_2CaGh_dXPSebbpU-t8pJbZ8FuU-_Oe9c
4. [Tue Sep 10 10:43:08.425706 2019] [proxy_fcgi:error] [pid 31321:tid 140164670822144] [client 90.180.236.159:53819] AH01071: Got error 'Primary script unknown\n', referer: xxxxx/admin/index.php/sell/catalog/products/347?_token=_eFuZoGcxA_2CaGh_dXPSebbpU-t8pJbZ8FuU-_Oe9c
5. [Tue Sep 10 10:43:09.139678 2019] [proxy_fcgi:error] [pid 31321:tid 140164670822144] [client 90.180.236.159:53819] AH01071: Got error 'Primary script unknown\n', referer: xxxxx/admin/index.php/sell/catalog/products/347?_token=_eFuZoGcxA_2CaGh_dXPSebbpU-t8pJbZ8FuU-_Oe9c

**In DevTools:**
Returned 500, when I try to search customer (when i write some text to field)
Request URL: xxxxx/admin/index.php/sell/customers/search?_token=_eFuZoGcxA_2CaGh_dXPSebbpU-t8pJbZ8FuU-_Oe9c&ajax=1&customer_search=Test
Request Method: GET
Status Code: 500 
![customer-search-03](https://user-images.githubusercontent.com/37780517/64604191-04d9a780-d3c2-11e9-85a6-d9fabe280667.jpg)

**Comment by khouloudbelguith** [comment]
@TaccCZ, could you please try to enable debug mode & check if there is any exception displayed instead of error 500?

Thanks!

**Comment by TaccCZ** [comment]
@khouloudbelguith 
**1.7.6.1 debug mode:**
https://www.loom.com/share/e417559a270e4d17882dbcde56e87ffc

**1.7.5.2 debug mode, same server (everything is ok):**
https://www.loom.com/share/48a5443558904eb6ac87aa53600389c7

**Comment by TaccCZ** [comment]
@khouloudbelguith > Hi, we fixed it. 

The problem we found was in the module that adjusted the GDPR functions of the prestashop. The module supplier has modified its functions and everything is working as it should.

**Comment by khouloudbelguith** [comment]
@TaccCZ, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
