### ISSUE TITLE
Exception is displayed when the URL is invalid - ps_facetedesarch

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15475]
**Describe the bug**
To reproduce the issue, we should have the debug mode enabled
In the BO => Catalog => Features page, when we created a new feature with invalid URL => An exception is displayed

**To Reproduce**
1. Go to BO => Catalog => Features page
2. Add a new feature with Invalid URL (Test 1) with space
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/64539141-d4d4ca80-d315-11e9-852c-945428dff9bc.png)
https://drive.google.com/file/d/1TLqCn8SyxTOEYS2UP9RwPkzESMQN5xvO/view

**Additional information**
PrestaShop version: 1.7.5.2 / 1.7.6.1
PHP version: 7.0
ps_facetedesrach v3.06 / v3.2.1.

**Wanted behavior**
Display an error message "Invalid URL" located in _Admin.Notifications.Error_

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Yes, it's because of DEV mode and because the current behaviour is weird.
This part will be refactored later.

**Comment by PierreRambaud** [comment]
We need information about what the backend needs to do :)

**Comment by marionf** [comment]
We should display an error message like "invalid URL", to be confirmed by @Julievrz

**Comment by Julievrz** [comment]
Yes, we could use the existing string "Invalid URL" located in Admin.Notifications.Error
