### ISSUE TITLE
Admin panel and homepage won't open

### ISSUE THREAD

**Issue by BeReal86** [PrestaShop/PrestaShop#15480]
home and admin panel input does not open after the installation process is completed.  a white page appears and I found the following error in the error log file.
no errors occurred during installation.
turkey language option was selected during setup

[09-Sep-2019 23:16:50 Europe/Istanbul] PHP Fatal error: Uncaught Error: Class 'Smarty_Internal_Undefined' not found in /home/pitalfdg/public_html/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php:168

As for the solution in the forums are the following.

Open the config.inc.php file, and search this code:
setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');

 (//setlocale(LC_CTYPE, $locale.’.UTF-8′, $locale.’.utf8′);) 
You can delete this code or you can do comment line

I think it's not a definite solution.

PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BeReal86,

I did not manage to reproduce the issue after a new installation PS1.7.6.1 using the English language & France country.
What is the exact Language/country did you use during the install?
Did you download the zip file from our official site?

Thanks!

**Comment by BeReal86** [comment]
Hi @khouloudbelguith 

I download the zip file from official site.
Country Turkey
Language Turkish

**Comment by khouloudbelguith** [comment]
@BeReal86, thanks for these clarifications.
I did not manage to reproduce the issue with PS1.7.6.1 downloaded from this [link](https://www.prestashop.com/en/previous-versions).
https://drive.google.com/file/d/1aSIsAG1NcEGO8-FRVCRaOhm7cv6-Iv3z/view

Thanks!

**Comment by BeReal86** [comment]
@khouloudbelguith,I will try the discount again as soon as possible.  maybe there is a problem with the hosting company.

Thanks

**Comment by khouloudbelguith** [comment]
@BeReal86, Thanks!
Waiting for your feedback.

**Comment by BeReal86** [comment]
@khouloudbelguith  Hi,
I did some trials on the server. I've done a few install.

sample; Language Turkish
Countries Turkey. is a problem when I choose
But;
sample; Language Turkish
Countries France. no problem when I choose
The only problem in choosing a country.

alerts in the picture always appear
<img width="701" alt="ggg" src="https://user-images.githubusercontent.com/16218107/64654742-df38b680-d432-11e9-908d-933c4f628999.png">
<img width="947" alt="php" src="https://user-images.githubusercontent.com/16218107/64654958-6f76fb80-d433-11e9-80db-0e22787d6eb2.png">
<img width="1016" alt="php1" src="https://user-images.githubusercontent.com/16218107/64654963-769e0980-d433-11e9-8cc8-b259948f7346.png">

`[09-Sep-2019 23:16:50 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_Undefined' not found in /home/pitalfdg/public_html/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php:168
Stack trace:
#0 /home/pitalfdg/public_html/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php(130): Smarty_Internal_Extension_Handler->__get('registerResourc...')
#1 /home/pitalfdg/public_html/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_data.php(290): Smarty_Internal_Extension_Handler->_callExternalMethod(Object(Smarty), 'registerResourc...', Array)
#2 /home/pitalfdg/public_html/prestashop/config/smartyfront.config.inc.php(43): Smarty_Internal_Data->__call('registerResourc...', Array)
#3 /home/pitalfdg/public_html/prestashop/config/smarty.config.inc.php(59): require_once('/home/pitalfdg/...')
#4 /home/pitalfdg/public_html/prestashop/config/config.inc.php(202): require_once('/home/pitalfdg/...')
#5 /home/pitalfdg/public_html/prestashop/index.php(27): require('/home/pitalfdg/...') in /home/pitalfdg/public_html/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168
`

and I have experimented with xampp 7.2. no problem.  I think the problem is in the settings of the hosting company's server Or a different problem.

**Comment by khouloudbelguith** [comment]
@BeReal86, thanks for your feedback.
Yes, you have a warning to install & enable the php_posix extension => so, it is not enabled & not installed.
![image](https://user-images.githubusercontent.com/16067358/64677625-d4e8dd80-d46f-11e9-8dc7-a6c40ed42432.png)
I think it is a server issue => thanks to check the problem with your host & feedback.

**Comment by BeReal86** [comment]
@khouloudbelguith 
I checked posix via php extension but it was not installed. I thank you for your help.  Would the problem be solved when php_posix was installed?

**Comment by khouloudbelguith** [comment]
@BeReal86, could you please try to create a PHP info file on your server & check if `posix` exists
![image](https://user-images.githubusercontent.com/16067358/64678901-707b4d80-d472-11e9-8e5e-f578bb51e62d.png)

Thanks!

**Comment by BeReal86** [comment]
@khouloudbelguith 
 
sorry for the delay

https://pitaleathershop.com/phpinfo.php

**Comment by khouloudbelguith** [comment]
@BeReal86, as you can see in your PHP info file, you have a lot of functions related to `posix` are disabled
![image](https://user-images.githubusercontent.com/16067358/64682041-ab807f80-d478-11e9-91b2-69a0d9feb0dd.png)

In fact, as you can see in this section: `disable_functions` => This directive allows you to disable certain functions

Thanks!

**Comment by BeReal86** [comment]
@khouloudbelguith  as you said yes many functions are disabled.

Thanks for all

**Comment by khouloudbelguith** [comment]
@BeReal86, Try to check the issue with your host & feedback.
Thanks!

**Comment by BeReal86** [comment]
@khouloudbelguith, I’ve talked with hosting and tried to  tell problems. But They’ve made 5.6 native php setting, but ıt seemed 7.2 on php info. They suggest it as a solution. 

/config/config.inc.php

setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
to
//setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');

Unfortunately, hosting compony has neither knowledge nor experience. It has been experience for me. I will not do long term work. When the site is ready, I will find different place. Thank you for everything.

**Comment by khouloudbelguith** [comment]
@BeReal86, It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

I close the issue, feel free to open a new one when needed.

Thanks!
