### ISSUE TITLE
GZIP dont work without htaccess mod

### ISSUE THREAD

**Issue by kimo1960** [PrestaShop/PrestaShop#15487]
we use on waffen.shopping the z.one shop template. but we cant use gzip without a mod of the htaccess for mod_deflate.

our provider says we have to write it in the htaccess - the dev from the z.one says dont mod the htaccess...

so, what should / can we do.... and no - we are not pros on thsi  ;-)
![Screenshot 2019-09-10 at 09 45 56](https://user-images.githubusercontent.com/55141112/64612664-9d792300-d3d4-11e9-9aef-e55d32a10591.jpg)

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

see attached 

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: PHP 7.3

**Comment by khouloudbelguith** [comment]
Hi @kimo1960,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @kimo1960,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
