### ISSUE TITLE
Wrong text formatting <li>

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#15498]
Hello!
When I format text in the BO like List it looks like Ok
![image](https://user-images.githubusercontent.com/50954519/64690973-60776400-d49a-11e9-9af5-04376c6c1268.png)
 But in the FO the indent is lost

![image](https://user-images.githubusercontent.com/50954519/64691125-a2080f00-d49a-11e9-8072-2ea98497049c.png)

PS 1.7.5.2

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & the default theme Classic.
BO => ok
![image](https://user-images.githubusercontent.com/16067358/64700848-90753600-d49f-11e9-8538-911080119bdd.png)
FO => NOK
![image](https://user-images.githubusercontent.com/16067358/64700872-a08d1580-d49f-11e9-8e42-28be17cf6eaa.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by photinia73** [comment]
I wrote to the Theme support, may be they will resolve before PS 1.7.6.1 update will come…. If it will happen I`ll let you know
Thank you

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: среда, 11 сентября 2019 г. в 16:24
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] Wrong text formatting <li> (#15498)

Hi @photinia73,
Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
BO => ok

FO => NOK

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
@photinia73, Thanks!

**Comment by photinia73** [comment]
Hello!
The Theme team reply is below:

“Sorry for inconvenience caused to you.

As we have checked from our end, there is no issue with the theme. We have also checked with classic theme but the issue is still there. So there is possibility of bug from PretsaShop.”

Unfortunately they didn`t propose the decision (( So waiting for 1.7.6.1 as I understand…



З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: четверг, 12 сентября 2019 г. в 10:52
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] Wrong text formatting <li> (#15498)

@photinia73, Thanks!

**Comment by marionf** [comment]
Hello @photinia73 

We can provide a pull request to make the bullets appears on Classic theme but it will not fix your issue because you use another theme than Classic
You should make the fix on your own theme

Regards

**Comment by NeOMakinG** [comment]
Hello @photinia73,

Juste verified, Classic theme doesn't show the bullets on every ul, I activated it on the product's description, but if your theme is not based on this one or totally changed the markup of product page, then it won't take the update, your theme developper should do it.

Regards

**Comment by photinia73** [comment]
Hello!
Where I can see the changes in the code, to make the same for my Theme?

ср, 18 груд. 2019, 19:07 користувач SZCZUPAK Valentin <
notifications@github.com> пише:

**Comment by NeOMakinG** [comment]
Hey,

there : https://github.com/PrestaShop/PrestaShop/pull/16856/files
