### ISSUE TITLE
ps_socialfollow - icons not clickable

### ISSUE THREAD

**Issue by LaureMatou** [PrestaShop/PrestaShop#15502]
On various of our Ready themes, we have a problem with links to social networks that do not work: the icons are not clickable.

In fact if we pass the link in Display Block we see that the icon is not part of the link. The link is below, so that a click on the icon can't redirect anywhere. 

The css comes from the theme but the bug can be fixed at the module level, which would solve the problem on all themes.

**Describe the bug**

**To Reproduce**
1. Install Elegant, Gourmet or Design theme
2. Configure ps_socialfollow : add links
3. In FO, try to click on social icons to access the social pages of the store

**Screenshots**
![image](https://user-images.githubusercontent.com/33054143/64712340-51ed7480-d4bb-11e9-88d3-b499d8019e30.png)
![image](https://user-images.githubusercontent.com/33054143/64712351-59ad1900-d4bb-11e9-9ed7-42eb35423088.png)

**Additional information**
PrestaShop version: Ready 1.7.5.2

More info here : 
http://forge.prestashop.com/browse/PSREADY-1571
http://forge.prestashop.com/browse/PSREADY-977
http://forge.prestashop.com/browse/PSREADY-1640

**Comment by khouloudbelguith** [comment]
Hi,
In my case with ps_socialfollow v2.0.0 & PS1.7.6.1 & the default Theme Classic => OK
Also, I checked with minimal theme => OK
https://drive.google.com/file/d/1AXi_92mAJ1MyJDGAdWA6logvRCMCJbcC/view

Thanks!

**Comment by LaureMatou** [comment]
Hi @khouloudbelguith,

Indeed the bug is not happening with default Classic theme but with Elegant, Gourmet or Design themes for example, which are themes included in PrestaShop Ready.

To have the issue solved in a durable way, we need to correct it at module level instead of theme level.

Thanks :)

**Comment by khouloudbelguith** [comment]
@LaureMatou, Thanks!
I manage to reproduce the issue with PS1.7.6.1 & the `Elegant` theme v1.2.0. & the `design` theme Version 1.2.0 & `gourmet` theme Version 1.2.0.
I’ll add this to the debug roadmap.
The module is ps_socialfollow v2.0.0
Thanks!

**Comment by NeOMakinG** [comment]
I agree that thing is not well made at first, but if we change the markup disposition it's a breaking change for most of themes, you should adapt the CSS of your themes as classic theme is, kick out the `dislay: none;` of the link. Make the `<a></a>` tag `font-size: 0; height: 100; width: 100; display: block;` and the `<li></li>` having a width and height as the classic theme does

**Comment by colinegin** [comment]
So you recommend not to do it @NeOMakinG ?

**Comment by NeOMakinG** [comment]
It's related to ready themes, if they change what I said previously it should work

**Comment by colinegin** [comment]
Alright, thanks for the explanation. I've warned the PrestaShop theme team. 
As it is not to be fixed in the module, I close the issue. 

Thanks !
