### ISSUE TITLE
Class 'LegacyLayout' not found

### ISSUE THREAD

**Issue by leatonvof** [PrestaShop/PrestaShop#15500]
I get errors in BO when trying to do pretty much anything, I think this started by installing a module. But I have put backups back on and still produce the same errors..

I tried resetting cache but this didn't help.

![Screenshot_2019-09-11 Symfony Profiler](https://user-images.githubusercontent.com/55189982/64693076-c4982900-d496-11e9-9436-93224c03a006.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @leatonvof,

Could you please check if you have some overrides not removed after uninstalling the module?
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by leatonvof** [comment]
> 
> 
> Hi @leatonvof,
> 
> Could you please check if you have some overrides not removed after uninstalling the module?
> Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
> Thanks to check and feedback.

I checked, no overrides connected to the module. I deleted the var/cache but still receive the same error.

**Comment by khouloudbelguith** [comment]
@leatonvof, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source: fresh install or upgrade from a previous version)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - in which from the BO => this exception is displayed?

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by leatonvof** [comment]
It seems I had not succesfully deleted my browser's cache completely.. Doing this sorted the errors. Thanks

**Comment by khouloudbelguith** [comment]
@leatonvof, thanks!
Feel free to open a new one when needed.
