### ISSUE TITLE
Wrong language displaying for Slovenian.

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#15506]
Again I would like to get feedback how so find solution for Slovenian and Sri lanka language. Because after every upgrade of core files for PrestaShop you have to manually delete file in JS/tiny_mce/lang/si.js and rename sl.si file to si.js to get Slovenian language in BO on editing product. Marked with red. I'm advanced user and I know how to solve, but many users don't and than they struggle with this or use English BO. This way it's pointless to translating BO, since you cannot understand what is written on menus.
directory of file: /js/tiny_mce/langs/

solution right now is deleting sl.js file and rename sl.je => si.js

![image](https://user-images.githubusercontent.com/54998637/64770110-d5a37180-d54c-11e9-8583-2cef529e0d69.png)
![image](https://user-images.githubusercontent.com/54998637/64770338-48145180-d54d-11e9-81cc-2e29d1813ee5.png)

**Comment by matks** [comment]
@malcek thanks for reaching out !

We have explored this issue and the root cause is likely that Slovenian language, in BO, has ISO code "SI" instead of "SL". However it seems hard to make sure it's a mistake 🤔 for example https://en.wikipedia.org/wiki/Slovenia states ISO code should be SI while https://www.iso.org/obp/ui#iso:code:3166:SI states ISO code should be SL

**Comment by malcek** [comment]
yes, this is problem on many systems since our independence back in 1991 as many organisations dedicated different code to our country. Ok, maybe it isn't mistake, but sure it is problem, because on each upgrade you have to change this manually

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
I'm not sure we can do this fix right now. We don't have the capability to determine if we are in `sl` or `si` 
![image](https://user-images.githubusercontent.com/1462701/68869436-70f5c600-06f9-11ea-9e99-048c4faba71f.png)
I think it will automatically fixed with: #16070
