### ISSUE TITLE
Update jquery to latest version in Installation process 4/4

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#15508]
EPIC: #13829

Update installation process's jquery version so that the old jquery (1.11) can be safely removed.

**Comment by ghost** [comment]
Hi @matthieu-rolland 
Should we add it to the 1.7.7 backlog?

**Comment by matthieu-rolland** [comment]
hi @samuel-pires , 

We realised that there is a 4th place where the old jquery is still used (installation process). 

So if the other jquery migrate issues are part of the 1.7.7 kanban then this one should too I guess ?
