### ISSUE TITLE
Translation BO doesn't handle properly same translation with different cases

### ISSUE THREAD

**Issue by jocel1** [PrestaShop/PrestaShop#15510]
**Describe the bug**

If you have in your translation two same strings but with a different case ("Order" and "order" for example), the BO / International / Translation will not be able to update the right string (it will pick up one of the key randomly).
It's because the key field stored in the database is not case sensitive (text instead of binary)

**To Reproduce**
1. Go to BO / International / Translation
2. Choose a theme with several same strings, but with different cases (flowerio for example)
3. Try to translate it, usually you'll not see the modification because it will be applied to the wrong key

**Additional information**
PrestaShop version: 1.7.*
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jocel1,

Your ticket is a duplicate of #10701
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #10701
