### ISSUE TITLE
The total of price is displayed with Tax included after editing the quantity of the products in the order

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15528]
**Describe the bug**
The Price display method of  the customer group is set to tax excluded.
In the BO > Order details page => when we edit the product Quatity => the total in the payment section is not correct => it is displayed with tax included => NOK

**To Reproduce**
1. Go to BO > Customers > Groups > set the customer group Price display method to Tax excluded
1. Go to BO > Orders > edit order > edit product quantity and save, check that the total prices section is displayed with tax included => NOK.

**Screenshots**
https://drive.google.com/file/d/1otxDNQnbv04QUmtBjE2YIAAJVl-g8SRw/view

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by marionf** [comment]
@khouloudbelguith 

This is the wanted behavior. You just display the price tax excluded for a customer group only (not for the merchant) but the customer pay the price tax included if taxes are enabled.

![capture d'écran_1992](https://user-images.githubusercontent.com/13449658/64959452-71a4e400-d891-11e9-843f-e03843931e35.png)

So, the merchant should see the real price paid by the customer (tax included if taxes are enabled)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

No, this is a different issue.
In the BO => Orders => Order details page
1. Before updating the quantity
![image](https://user-images.githubusercontent.com/16067358/65027154-be3ffc00-d931-11e9-8754-0670fbb5c64f.png)

2. After updating the quantity
![image](https://user-images.githubusercontent.com/16067358/65024971-b8481c00-d92d-11e9-894d-611791260854.png)
3. After reloading the page
![image](https://user-images.githubusercontent.com/16067358/65025049-e0d01600-d92d-11e9-8c6c-a7f249b37f2e.png)

I attached a video record
https://drive.google.com/file/d/1V660MUc8tWsFNrHAc4kRTndIaKHAOHcX/view

Thanks!

**Comment by marionf** [comment]
Sorry @khouloudbelguith 

I didn't understand well the issue

**Comment by marionf** [comment]
@MatShir Maybe this one can be solved during the migration of order page ?

**Comment by matks** [comment]
@marionf Yes, PR https://github.com/PrestaShop/PrestaShop/pull/8493 provides a solution for legacy page, so it will be easy for us to re-apply the fix to the migrated page

**Comment by matks** [comment]
@PrestaShop/prestashop-qa I have checked this issue and it seems fixed with the migration of Edit an Order page. Could you confirm ?

**Comment by SD1982** [comment]
Hi @matks I have tested to reproduce on the 1.7.7.x branch and yes the issue seems to have been fixed
