### ISSUE TITLE
Problem when extending from ModuleAdminControllerCore to do a list of orders with some fields

### ISSUE THREAD

**Issue by shawe** [PrestaShop/PrestaShop#15535]
**Describe the bug**
I'm not competely sure that if this is really a bug or I'm missing something, but for me seems a bug because this only happens in certains specific classes conditions.

**To Reproduce**
When we create a back-office controller extending from ModuleAdminControllerCore, and try to list something from a custom query, in the code that we are extending is assuming that the table name is the same name than in entity. This is completely false in case of for example "Order" class and "orders" tablename.

Opening the class "classes/helper/HelperList.php" and going to line 843 on getViewLink method definition, we can see that first param on getViewLink called on return, is receiving the property table, but this method is expecting to receive and entity name.
How I say before, in this case 'order' != 'orders', and id auto-generated inside getViewLink is generated as 'id_orders'.
Assuming that id is always 'id_' + tablename how I found when it's auto-filling it, why not use "str_replace('id_','', $this->identifier)" instead of "$this->table" when identifier is not empty?

I replace on HelperList class the return code part on method defined on 843 line, with this:

        if(!empty($this->identifier)) {
            return $linkBuilder->getViewLink(str_replace('id_','', $this->identifier), $parameters);
        } else {
            return $linkBuilder->getViewLink($this->table, $parameters);
        }

and seems to work correctly as expected at least for me.

Maybe I'm loosing something and this change breaks in other combinations, but no other property is used here to do this and not seems to be able to do it in other way.

If needed, I can share the little class that I prepare for generate this list when I found this problem to make it easy to reproduce the issue.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.32-1+ubuntu19.04.1+deb.sury.org+1

**Comment by mariem-abid** [comment]
Hi @shawe,

The identifier of an object in Prestashop must be in the form "id_tableName" to facilitate the generation of lists in the admin part.

**Comment by shawe** [comment]
@mariem-abid Then, is really an internal mistake with the tablename?

**Comment by mariem-abid** [comment]
@shawe, do you want to add a new table or use the existing table?

**Comment by shawe** [comment]
@mariem-abid I'm trying to list the original table orders with a left join to get additional details, but the problem is that "Order" object in core is not working accordingly the directives you confirm that I found.

> The identifier of an object in Prestashop must be in the form "id_tableName" to facilitate the generation of lists in the admin part.

When this is trying to be generated in admin part, the id is generated as "id_orders", but the correct one for this table is "id_order".

The method that cause this to fail, is expecting one parameter type (entity), but in some cases like this, is receiving another one (tablename), because is assuming that you say me, but this is not always true.

**Comment by mariem-abid** [comment]
@shawe, try to create a new table with the desired attributes and join it with the "order" table.

**Comment by shawe** [comment]
All data I need is yet inside Order, Customer or Employee tables, I don't really need to create an extra table to do that, because this implies to generates duplicate data that tecnically is not needed.

For me it's a bug, the unique problem is that the "must be" condition, seems to not be aplicable on some core parts, or simply is not a requirement and this causes inconsistencies like this because some method are incorrectly called assuming things that are knowed from start that can be false.

Is there any other way to generate a list without this problems? Maybe is more easly to all people who detects this problem not extends from ModuleAdminController and extends from some other controllers that allows easely bypass this feature and get a similar result.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
HI and sorry for the delay.

Could you provide us an example? (Something like a module we can easily install and test)

**Comment by hibatallahAouadni** [comment]
Hello @shawe ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
