### ISSUE TITLE
Guest tracking page is not working

### ISSUE THREAD

**Issue by carlosrsabreu** [PrestaShop/PrestaShop#15536]
When I try to put the order reference and the e-mail and click "Send", what happens is that the page redirects to the homepage and doesn't return anything.

**Comment by mariem-abid** [comment]
Hi @kidlivin,

I did not manage to reproduce the issue with the last version PS:1.7.6.1.
I attached a video record.
https://drive.google.com/file/d/10JiI8xUXY771ty6l4yQizHo4NBExaD7W/view

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @kidlivin,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by 900i** [comment]
Hi,
I have the same problem with the guest tracking page. After I insert the order number and the email address and I press send, it goes to the home page. Even if I don’t fill out the email and the address and I press send it has the same behavior. 

Does anyone knows which is the problem?

Thanks!

**Comment by khouloudbelguith** [comment]
@900i, Duplicate of #9650
