### ISSUE TITLE
The price is displayed with tax included when the customer group is configured with tax excluded

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15532]
**Describe the bug**
The custom group by default has method to display price is "Tax Included"
When we create another group with method to display price is "Tax excluded"
In the BO > Order details page => The price is displayed with tax included when the customer group is configured with tax excluded
**To Reproduce**
1. Go to BO > create new customer group (G1) with Price display method = Tax excluded
2. Go to the FO > create a new customer with his group and default group are G1
3. Create a new order
4. Go to the BO > the order details and check that prices is displayed with tax included.

**Screenshots**
https://drive.google.com/file/d/1QuCNCllvSBNklSvzHFwH3dXtLQEytIKI/view

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by marionf** [comment]
@khouloudbelguith 

This is the wanted behavior. You just display the price tax excluded for a customer group (only not for the merchant) but the customer pay the price tax included if taxes are enabled.

![capture d'écran_1992](https://user-images.githubusercontent.com/13449658/64959452-71a4e400-d891-11e9-843f-e03843931e35.png)

So, the merchant should the real price paid by the customer (tax included)
