### ISSUE TITLE
Paypal Error code: 10413 Ps 1.7.5

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#15541]
Hello, 

i am using prestashop 1.7.5 and I have PayPal module V.5 but I have I customer that could't pay because when try to pay with PayPal it gives this error: Error code: 10413.Short message: Transaction refused because of an invalid argument. See additional error messages for details..Long message: The totals of the cart item amounts do not match order amounts..

On my shop for every products there is a discount based on quantities. So for example if you buy 6 products you get 15% off. Could be this the problem? But at the checkout the discount is fine. 

Could you please help me to understand ?

Thank you
Kind regards

**Comment by mariem-abid** [comment]
Hi @morghy1992,

Have you tried to contact the agency who develops the Paypal module? As it comes from a module update, I don't think we can do something before their feedback.

**Comment by ghost** [comment]
Hello @morghy1992 I am using P.S 1.7.6 and I also started having the same problem when PayPal updated to V5.0 How do we reach the module developers because it's affecting my sales since PayPal was my only Payment gateway.

**Comment by ghost** [comment]
https://www.prestashop.com/forums/topic/162185-solved-paypal-error-code-10413-totals-of-cart-items-dont-match-total/

Check out this link. It says the error is because of using PayPal Pro. I'll try it out and tell you if it works

**Comment by morghy1992** [comment]
@storepaperoomates thank you very much for sharing the link. I have PayPal v5.0.0 What version do you have? How can I know if my PayPal is Pro? Where did you download it? 

Thank you :)

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
