### ISSUE TITLE
ChoiceType checkbox

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#15548]
I try to add custom checkbox field in admin customer form.
I add this field like this : 

`			->add(
				'customer_type',
				ChoiceType::class,
				[
					'label' => $this->l('Customer type'),
					'choices' => $this->type_customer,
					'expanded' => true,
					'multiple' => true,
				]
			) `
But i'm getting an error (see attachment)
![error](https://user-images.githubusercontent.com/552339/64943443-07c61380-d86c-11e9-97cd-463245446f10.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by matks** [comment]
Hi @azralth it's because your `$customerForm` could not be created, and the exception was hidden by the try/catch in the controller. You can debug this by adding a `throw $e` in the catch 😉 (we know this is not practical, this will be improved in the future)

```
        try {
            /** @var ViewableCustomer $customerInformation */
            $customerInformation = $this->getQueryBus()->handle(new GetCustomerForViewing((int) $customerId));
            $customerFormOptions = [
                'is_password_required' => false,
            ];
            $customerForm = $this->get('prestashop.core.form.identifiable_object.builder.customer_form_builder')
                ->getFormFor((int) $customerId, [], $customerFormOptions);
           ......
        } catch (Exception $e) {
            $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
            if ($e instanceof CustomerNotFoundException) {
                return $this->redirectToRoute('admin_customers_index');
            }
        }
```
becomes
```
        try {
            /** @var ViewableCustomer $customerInformation */
            $customerInformation = $this->getQueryBus()->handle(new GetCustomerForViewing((int) $customerId));
            $customerFormOptions = [
                'is_password_required' => false,
            ];
            $customerForm = $this->get('prestashop.core.form.identifiable_object.builder.customer_form_builder')
                ->getFormFor((int) $customerId, [], $customerFormOptions);
            $customerForm->handleRequest($request);
            ..........
        } catch (Exception $e) {
            throw $e; // add this to see the error
            $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
            if ($e instanceof CustomerNotFoundException) {
                return $this->redirectToRoute('admin_customers_index');
            }
        }
```

**Comment by matks** [comment]
So you did something wrong when you added the field. Have you imported the `ChoiceType` class using a `use` ? else you need the full class name: `\Symfony\Component\Form\Extension\Core\Type\ChoiceType`

**Comment by azralth** [comment]
Thanks for your help ! 

Yep, i add the ChoiceType. This field Type work only if i had "multiple => false". But then i have a radio input.
Here the new error in attachment
![erreor](https://user-images.githubusercontent.com/552339/64944562-ea467900-d86e-11e9-8c2c-b142b06ec5b8.png)

**Comment by matks** [comment]
According to the error message, your prestashop is configured to store session files into  `/var/lib/php/sessions` which is a folder it has no access to. You need to either fix the directory access settings or modify where your prestashop store session files

**Comment by azralth** [comment]
Yep, i had" session.gc_probability = 0" in php.ini. That fix the bug.

Thanks for your support !
