### ISSUE TITLE
Mail translation - when you press the save button returns 404

### ISSUE THREAD

**Issue by namkynam** [PrestaShop/PrestaShop#15547]
**Describe the bug**
When you go to the email translations page and make any edits and press save BO will go to 404

**To Reproduce**
1. Go to 'BO > International > Translations'
2. Click on 'Email translations > body > Classic > English'
3. Scroll down to 'Save or Save and stay'

**Screenshots**
BO will return to 404 page - GG driver record
https://drive.google.com/open?id=1i4nT5gMk32g1OEmpCHUpZyrJ6sQuyBnn

**Additional information**
PrestaShop version: 1761
PHP version: 7.2

**Comment by sotirisa** [comment]
Hi, this solved from me with settings from the server. Do you have plesk?

**Comment by mariem-abid** [comment]
Hi @namkynam,

I did not manage to reproduce the issue with the version PS: 1.7.6.1.
I attached a video record.
https://drive.google.com/file/d/1zVD3hMD9VN7jLDJ8iAyjp5dir74OqJcw/view

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by namkynam** [comment]
> 
> 
> Hi, this solved from me with settings from the server. Do you have plesk?

Can you send me a screenshot of the server configuration that helped you fix the problem?

**Comment by namkynam** [comment]
@mariem-abid Hi,
Thank you for quick reply!
I'm ussing Cloud VPS and can not access to the root. I only get one file log for all.
Please help!
[logs.gz](https://github.com/PrestaShop/PrestaShop/files/3615735/logs.gz)
[console-export-2019-9-16_17-7-49.txt](https://github.com/PrestaShop/PrestaShop/files/3615737/console-export-2019-9-16_17-7-49.txt)

**Comment by mariem-abid** [comment]
@namkynam, are you using the template by default of Prestashop?

**Comment by namkynam** [comment]
@mariem-abid Hi,
I'm using default Prestashop download from prestashop.com.
I can send you BO, Cpanel information directly via email if you need it.
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @namkynam,

Thanks for your feedback.
When debug mode is enabled => there is no exception displayed?

Thanks!

**Comment by namkynam** [comment]
Hi @khouloudbelguith,
I have attached console with Firefox.
Please check. Debug mode enabled and no errors are displayed.

**Comment by khouloudbelguith** [comment]
@namkynam, in the files attached, I couldn't find errors.
You need to enable debug mode in your store and debug request which is sent for translation save in your browser, using DevTools, so:

1. enable debug mode
2. go to the translation page
3. open up developer tools
4. go to Network tab
5. save the translation
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by namkynam** [comment]
Hi @khouloudbelguith 
debug mode is enabled
Network tab is return the same 404(attached image) 

![network-console-tab](https://user-images.githubusercontent.com/19523750/65104237-024b0380-d9fb-11e9-9bff-a05bbc7db40f.png)

**Comment by khouloudbelguith** [comment]
@namkynam,

Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by namkynam** [comment]
Thank you for help! @khouloudbelguith 
I have just sent you Cpanel + BO access information via your mail.

**Comment by khouloudbelguith** [comment]
@namkynam, Thanks!
I just received the email, I will check & feedback.

**Comment by khouloudbelguith** [comment]
@namkynam, did make any changes in the core PrestaShop?
Did you changed your `Shop domain` or `SSL domain`?
Because you are redirected to another shop
`https://xxx.com.vn/`
Your current shop is `http://xxxx.com.vn/checkfl/`
Did you enabled Multistore before & disable it?

Thanks!

**Comment by namkynam** [comment]
Hi @khouloudbelguith,
The Prestashop site you consider to be the default version 1.7.6.1 does not have any code changes or configuration changes.
All BO settings are the default. I just installed Prestashop 1761 and translated the email. I have this problem on the main site. I installed the Test site with default version to check and it also suffers.

Please help!

**Comment by khouloudbelguith** [comment]
@namkynam, did you installed PrestaShop from our official web Site: https://www.prestashop.com/en/previous-versions?
What is the exact language/country did you use during the install?

Thanks!

**Comment by namkynam** [comment]
Hi, i installed with the language option in step one of Vietnamese. But the Firefox browser I am using has the default language of English.

Once installed, Prestashop is available in both languages.

I can provide a new database for you to install a completely new version of Prestashop on the cpanel I provided if you feel it is necessary.

Thank you for help!

**Comment by khouloudbelguith** [comment]
@namkynam, I tried with PS1.7.6.1 (Vietnamese language & United states country).
I changed the employee's language to English.
I tried with Firefox to translate email => OK
https://drive.google.com/file/d/1gigfgzEeRCMHFuxk_F1eAwIRb9s30_ib/view

Thanks!

**Comment by namkynam** [comment]
Yes, I have used many websites with Prestashop 1.7.6.x but I have never encountered this error.
This error is unique to the site I sent you.
PHP logs, Apache logs, debug mode, javascript console log are empty.
Could you please check directly on the site I sent you? Or you can use cpanel to install a completely new default version of PS and check.
Please help!

**Comment by khouloudbelguith** [comment]
Hi @namkynam,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by namkynam** [comment]
Hi,
I have attached phpinfo() image
![phpinfo()](https://user-images.githubusercontent.com/19523750/65474382-cb1a9d80-dea5-11e9-8254-34e1e146f99c.png)

**Comment by khouloudbelguith** [comment]
@namkynam, can you please provide a PDF file of your phpinfo file & also the equivalent to the phpinfo that reports PrestaShop Requirements.

Thanks!

**Comment by namkynam** [comment]
Hi, can you please get all of phpinfo here: http://hht-group.com.vn/checkfl/PHP-setting.php ?

I dont know how to export it to pdf file.

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @namkynam,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
