### ISSUE TITLE
Missing tables in mysql after update

### ISSUE THREAD

**Issue by vortexfoto** [PrestaShop/PrestaShop#15569]
Hello
I have discovered strange error. First dashboard went to 0. When i investigated i foun that i cannot access in admin area localization currencies it gave me error 500
i enabled debug mode and found out that some tables are missing

report:
An exception occurred while executing 'SELECT c.`id_currency`, c.`iso_code`, cs.`conversion_rate`, c.`active`, cl.`name`, cl.`symbol` FROM prsta342_currency c INNER JOIN prsta342_currency_shop cs ON c.`id_currency` = cs.`id_currency` INNER JOIN prsta342_currency_lang cl ON c.`id_currency` = cl.`id_currency` WHERE (cs.`id_shop` IN (?)) AND (cl.`id_lang` = ?) AND (c.`deleted` = 0) GROUP BY c.`id_currency` ORDER BY id_meta asc LIMIT 50 OFFSET 0' with params [1, 1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_meta' in 'order clause'

how can i fix this?
Presta version is latest 1.7.6.1 upgraded from latest 1.7.5

**Comment by khouloudbelguith** [comment]
Hi @vortexfoto,

Have you some errors during the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by vortexfoto** [comment]
huh strange log is empty
there was no errors everything completed ok

**Comment by khouloudbelguith** [comment]
@vortexfoto, what is the exact version of the module 1-click upgrade did you use?

Thanks!

**Comment by vortexfoto** [comment]
it was removed and installed new version from prestashop i think 4.9 butnot sure, but 100% it was the latest

problem is that i cannot do rolback - 2 weeks of shop data
i need to manually fix database
tnx

**Comment by khouloudbelguith** [comment]
@vortexfoto, you can check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/install-dev/data/db_structure.sql

Thanks!

**Comment by vortexfoto** [comment]
any idea how to speed it up? maybe import database with skipping existing entries?

**Comment by vortexfoto** [comment]
i have checked table ps_meta it has id_meta defined
maybe you can help me locate the real problem....

**Comment by vortexfoto** [comment]
ah just fixed it
i found out that some function uses column id_meta instead of id_currency so i just added column id_meta to table ps_currency and everything appeared ok

**Comment by khouloudbelguith** [comment]
@vortexfoto, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
