### ISSUE TITLE
Module main menu

### ISSUE THREAD

**Issue by mariem-abid** [PrestaShop/PrestaShop#15564]
**Describe the bug**
After creating and modifying a new link, the modification is not done, a new link will be added

**To Reproduce**
1. Add a new link.
2. Click on Edit button.
3. Edit the label.
=> The update button is not existing in the PS version 1.7.6.1 (PS:1.7.6.0 is OK)
I attached a video record.
https://drive.google.com/file/d/10RGsHOtebxjVkICoY2vCs2BLOe2seNp4/view

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by marionf** [comment]
Duplicate of #15559
