### ISSUE TITLE
GLEN BROWN 

### ISSUE THREAD

**Issue by mistabrown** [PrestaShop/PrestaShop#15561]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by mariem-abid** [comment]
Hi @mistabrown,

Thanks to adding a short description of your issue and add steps to reproduce it in a new comment.

**Comment by khouloudbelguith** [comment]
Hi @mistabrown,

Your issue is incomplete, I will close the issue. Feel free to open another one if you can give specific details.

Thanks!
