### ISSUE TITLE
APCu

### ISSUE THREAD

**Issue by itroom-agence** [PrestaShop/PrestaShop#15573]
Hy,

we have some issues with APCu

**Describe the bug**
When APCu is enabled, Prestashop seems to allways feed the cache. Even with 8Go allowed for the cache, it end with a crash because of 100% fragmentation.
According to our web host, the allowed cache space does'nt need to be so huge. The user cache entries has too many entries (currently more than 60000 for 13000 pages).

When the site is down because of this, mySql requests fail and the overrides crash.

Is there a specific Prestashop configuration to apply ? There's nothing to do with APCu configuration.

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Thanks for your report.
Here is a [link](https://devdocs.prestashop.com/1.7/scale/optimizations/) to Optimize your PrestaShop performance.
There is a Prestashop module that is promising for APCu.
https://dh42.com/free-prestashop-modules/apcu-manager/

Thanks to check & feedback.

**Comment by itroom-agence** [comment]
Thanks for your reply.
We allready checked the optimisation page and everything seems ok.
The module just display the APCu dashboard and does'nt have any impact on the configuration or performances.

**Comment by khouloudbelguith** [comment]
@itroom-agence, 
When APC is installed on your server, no additional configuration is required on your part. APC works at the webserver level, so PrestaShop itself does not require any special configuration to take advantage of the performance benefits.


Thanks!

**Comment by khouloudbelguith** [comment]
Hi @itroom-agence,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
