### ISSUE TITLE
Infinite loop and order blocked with two specific cart rules

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#15574]
**Describe the bug**
Infinite loop and order blocked with two specific cart rules.

**To Reproduce**
With a fresh Prestashop 1.7.6.1 installation in debug mode. Follow this exactly in this order :
1. Go to BO/cart rules
2. Add a first cart rule without voucher code with 10€ HT gift
3. Add a product condition on "Home" Category and save
4. Add another cart rule without voucher code with free delivery
5. Go to front and add a product to the cart : You'll have 500 error on the ajax call
6. Reload page : you'll get the infinite loop with this error "Maximum function nesting level of '256' reached, aborting!"
7. Go to BO / Carts : I'll get the infinite loop too

If xdebug is enabled, You'll get the error "Maximum function nesting level of '256' reached, aborting!" If not, php will crash and you'll only have a 500 error.

This bug is not present in 1.6, It's a regression.

It seems that cart rules are recursively evaluated and product list is reconstructed each call of cart computation.

As already disscussed with @matks, this PR should fix the bug https://github.com/PrestaShop/PrestaShop/pull/12878

**Screenshots**
![cartrule1](https://user-images.githubusercontent.com/16720275/65040726-54d1e480-d955-11e9-9169-0659476a0e3c.png)
![cartrule2](https://user-images.githubusercontent.com/16720275/65040732-58fe0200-d955-11e9-95d3-a0e57ddfc190.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I manage to reproduce the issue with PS1.7.6.1 & develop branch & PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/65047228-feb37000-d959-11e9-80f0-000757a4c34a.png)
In the BO => Orders => Shopping cart page => Error 500
https://drive.google.com/file/d/1NF_01f5wjBDMQ4ko4XHn1VWuETOHuovH/view

With PS1.7.5.2 => OK

![image](https://user-images.githubusercontent.com/16067358/65047692-ca8c7f00-d95a-11e9-814e-454fa6ac522c.png)
https://drive.google.com/file/d/1UsFAYsqj_KjZz-TFA7z6_5xCaTy-jkRw/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by jf-viguier** [comment]
Thanks @khouloudbelguith 
I can provide by email a real world dump with 300 cart rules for your future tests.

**Comment by ttoine** [comment]
you are speaking about PR #12878, is this issue related to #11172

**Comment by colinegin** [comment]
Unfortunately, after reviewing the PR, we have considered it does not fix the issue, so we put it back on the To do column and are going to work on it asap.

**Comment by jf-viguier** [comment]
> Unfortunately, after reviewing the PR, we have considered it does not fix the issue, so we put it back on the To do column and are going to work on it asap.

ok @colinegin and what's the plan to fix it ?

**Comment by matks** [comment]
> > Unfortunately, after reviewing the PR, we have considered it does not fix the issue, so we put it back on the To do column and are going to work on it asap.
> 
> ok @colinegin and what's the plan to fix it ?

We go deeper in the code 😉 
@PierreRambaud just assigned himself

**Comment by jf-viguier** [comment]
Thanks @PierreRambaud : you've got all my support.

**Comment by matks** [comment]
<img src="https://centralbay.michiganumc.org/wp-content/uploads/sites/5/2019/06/Brace-Yourselves-X-is-Coming.jpg">

**Comment by PierreRambaud** [comment]
Hum, I tried many times with 1.7.5 and still have the problem. Seems not to be a regression.
![image](https://user-images.githubusercontent.com/1462701/65677979-d65efc00-e052-11e9-8ff1-3fb040fbd39a.png)

**Comment by PierreRambaud** [comment]
We maybe found a fix with #15691 :crossed_fingers:

**Comment by jf-viguier** [comment]
Hi all, have you validated the fix #15691 for this bug ?

**Comment by PierreRambaud** [comment]
@jf-viguier Still waiting for review and QA :/

**Comment by jf-viguier** [comment]
ok thanks

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15691
