### ISSUE TITLE
Intl extension is not loaded

### ISSUE THREAD

**Issue by napsterrahul1** [PrestaShop/PrestaShop#15572]
in mac intl error is big issue not working with any xampp 7.3,7.2.7 or 5.6 as well tried all solutions but not working at all

**Comment by khouloudbelguith** [comment]
Hi @cakeph,

During the installation of your PrestaShop version, you have warning that the intl should be installed & enabled?
PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks!

**Comment by napsterrahul1** [comment]
hi currently i am working with php 7.2.7 but its shows error intl is not loaded i uncomment the int_php.dll but the error still exist in mac

**Comment by khouloudbelguith** [comment]
@cakeph, it is a server issue.

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/65027616-943b0980-d932-11e9-8a29-f10e46a426c1.png)


Thanks

**Comment by napsterrahul1** [comment]
it shows intl NO i am working on local mac environment

![Screenshot 2019-09-17 at 2 43 08 PM](https://user-images.githubusercontent.com/15106179/65028333-89479f80-d959-11e9-8771-f1eb6190fb14.png)

**Comment by khouloudbelguith** [comment]
@cakeph, so in your server, intl is not installed or enabled.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration.
I find this [link](http://budiirawan.com/install-php-intl-extension-os-x/)
I hope this helps you to solve the issue.
I close this ticket, feel free to open a new one when needed
Thanks!
