### ISSUE TITLE
Product Comments Admin Page - Too Many Reviews in a Single Page

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#15597]
Hello I am using Prestashop version 1.7.6.1 and I have around 1200 product reviews at the moment. 
If I want to check reviews for approval etc, this page takes huge time to load, because all review are listed in a single page.

Regarding the performance issues, this page must use pagination.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @cemalarik,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by TristanLDD** [comment]
Hi @cemalarik, thanks for your report

We took note of this problem and it will be fixed in the next version of the module along with other corrections. Unfortunately it's hard to give you a precise estimate of time as it still needs to be prioritized.
