### ISSUE TITLE
Removing an Attribute from a Product - Inactive Attributes are Listed in Monitoring Page

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#15596]
Hi,

When I remove a product attribute, it is OK. 
But when I check page:
Catalog -> Monitoring -> "LIST OF PRODUCTS WITH COMBINATIONS BUT WITHOUT AVAILABLE QUANTITIES FOR SALE: ", this attribute is still listed (stok is not available).

Thanks

**Comment by khouloudbelguith** [comment]
Hi @cemalarik,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1wLw-DmRlzmIlYHja_yQ6bvLAmcgOm-6w/view
What is the exact version PrestaShop Did you use?

Thanks!

**Comment by cemalarik** [comment]
Hello,

I am using 1.7.6.1

In order to reproduce;

1. Add an attribute to a product.
2. Update that attribute's stock to zero and save.
3. Remove the attribute from product.
4. Check the result on Catalog -> Monitoring -> "LIST OF PRODUCTS WITH COMBINATIONS BUT WITHOUT AVAILABLE QUANTITIES FOR SALE: "

If the stock available is greater than zero for this attribute, it is not listed as expected. 

In my case, I had to manually update that attribute's stock in database (someting >0 ), even if it is not visible on product page. 

Thanks

**Comment by khouloudbelguith** [comment]
@cemalarik, I tried to follow all these steps, but it is OK
https://drive.google.com/file/d/1EkI7DzOeucsxzj0xzvhhC21g8SL07QJ0/view

Thanks!

**Comment by cemalarik** [comment]
It is strange. The only difference is that, I migrated my shop from 1.6.1.24 to 1.7.6.1.
I guess that causes the problem. So I close the issue for now. 

Thanks

**Comment by khouloudbelguith** [comment]
@cemalarik, feel free to open a new one needed.

Thanks!
