### ISSUE TITLE
Rewrite Github action in yaml

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#15593]
According to Github: 

> On September 30, 2019, GitHub Actions will stop running workflows written in HCL. You’ll need to migrate your HCL workflows to the new YAML syntax using the migration script.

Source: https://github.blog/changelog/2019-09-17-github-actions-will-stop-running-workflows-written-in-hcl/

This means either rewriting or removing this file: https://github.com/PrestaShop/PrestaShop/blob/develop/.github/main.workflow

**Comment by mickaelandrieu** [comment]
Hi @eternoendless,

Github provides a script to convert the HCL file to Yaml => https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax#about-the-new-yaml-syntax-for-github-actions

Regards,

**Comment by Progi1984** [comment]
@eternoendless I think we can close this issue. Isn't it ?
