### ISSUE TITLE
Faceted search build is missing

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#15591]
For faceted search, v. 3.3.0: Build for production is missing: https://github.com/PrestaShop/ps_facetedsearch/releases

Ping  @PierreRambaud

**Comment by PierreRambaud** [comment]
It will be adding during the day :wink:

**Comment by PierreRambaud** [comment]
Done!

**Comment by MathiasReker** [comment]
Thanks :)
