### ISSUE TITLE
JS Sourcemap warning in FireFox

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#15607]
Presta 1.7.6.1

There is a warning that sourcemap file core.js.map is missing in FireFox - this only occures if JS Smart Cache is turned off

![grafik](https://user-images.githubusercontent.com/47666330/65218315-82826f00-dab6-11e9-82ec-1ec085b59b6d.png)

If I remove the source map link in core.js line 234 the warning is gone.

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

I did not manage to reproduce the issue with PS1.7.6.1 & Firefox browser v64.0.2 & chrome browser v69.0.3497.81.
I attached a screen record
https://drive.google.com/file/d/1fass7Vj3xieuanDQRd-wcHk-qQTkQFUY/view
Thanks to check & feedback.

**Comment by JBWModules** [comment]
Did you switch off JS smart cache before as mentioned?

**Comment by khouloudbelguith** [comment]
@JBWModules, yes!
https://drive.google.com/file/d/1CtmojZdYXQmupnzGAbxn6BUviYNNpVGm/view
Thanks!

**Comment by JBWModules** [comment]
I'm using firefox 69.0.1 and can reproduce the behaviour on 1.7.6.1 installation on other server (localhost). No warning/error in chrome

**Comment by khouloudbelguith** [comment]
@JBWModules, Friendly URL is enabled or disabled in your case?

Thanks!

**Comment by JBWModules** [comment]
It's enabled

**Comment by khouloudbelguith** [comment]
@JBWModules, I tried with FireFox v69 & it is OK
https://drive.google.com/file/d/10Q44xkgMZjKe9h1hpsBk1-A4Xj8UNnRK/view

Thanks!

**Comment by JBWModules** [comment]
Ok, I figured it out. It's not a issue: The message occurs only if you once active the "debug" tab in Firefox. Guess it tries to find and load the map then in preparation of debugging activities but can't find it on the server (what is ok). 
Please close this issue and thanks for your efforts.

**Comment by khouloudbelguith** [comment]
@JBWModules, thanks for your feedback.
I close the issue, feel free to open a new one needed.

Thanks!
