### ISSUE TITLE
Quick Access page is not available in the menu

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#15600]
**Describe the bug**
We want to edit Quick Access section, but there's no link to this page in back-office, therefore this page is available when visiting below link directly.

link: http://yourdomain.com/admin-folder/index.php?controller=AdminQuickAccesses

**Additional information**
PrestaShop version: 1.7
PHP version: n/a

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

In your BO => Quick access => Manage quick accesses
![image](https://user-images.githubusercontent.com/16067358/65152728-6af8a700-da20-11e9-88e4-6442d4751726.png)

Thanks to check & feedback.

**Comment by kpodemski** [comment]
Aaaa, you're right, we have so many links there that I didn't notice this URL... ¯\_(ツ)_/¯

**Comment by khouloudbelguith** [comment]
@kpodemski, Thanks!
Feel free to open a new one when needed.
