### ISSUE TITLE
hreflang missing return link

### ISSUE THREAD

**Issue by mreco** [PrestaShop/PrestaShop#15613]
Hello. In version 1.7.5.2, all products that have attributes in the hreflang test report the error "hreflang missing return link". Example on this page https://yourobsession.pl/rajstopy-i-ponczochy/12096-5665-subirata-15-den-mocca-livco-corsetti-fashion.html#/91-rozmiar-2.
The hreflang links do not have the second number which I marked in red on the screen in the attachment. This is probably the id of the product combination, which causes errors in the hreflang test.

Prestashop 1.7.5.2
PHP 7.2
![Clipboard01](https://user-images.githubusercontent.com/5249883/65241006-d5721b80-dae2-11e9-87b3-15d9e22813bb.jpg)

**Comment by khouloudbelguith** [comment]
Hi @mreco,

I have the same behavior as PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/65245175-0010a400-dae4-11e9-9875-85edd7972fa1.png)
>in the hreflang test report the error "hreflang missing return link".

What is the exact tool did you sed to test this?

Thanks!

**Comment by mreco** [comment]
https://technicalseo.com/tools/hreflang/
or
https://flang.dejanseo.com.au

**Comment by khouloudbelguith** [comment]
@mreco, I tried with this link, but it is OK
http://unsuitable-afternoon.machine-shuffle.prestashop.net/en/men/1-hummingbird-printed-t-shirt.html
There's no warning: "hreflang missing return link".
![image](https://user-images.githubusercontent.com/16067358/65246545-b83f4c00-dae6-11e9-9baa-d6f8f1753517.png)
![image](https://user-images.githubusercontent.com/16067358/65246635-e4f36380-dae6-11e9-9cf6-5ba8bdbac7b2.png)

Thanks to check & feedback.

**Comment by mreco** [comment]
Yes the link you provided is ok. There are no errors. However, I am using an earlier version of prestashop 1.7.5.2. Can you tell me what was changed in version 1.7.6.1 and what has to do with the hreflang attribute? Can an error cause a template? How to solve my problem?

**Comment by khouloudbelguith** [comment]
@mreco, this shop version is PS1.7.6.0.
Here's the changelog of PS1.7.6.0 & PS1.7.6.1.
https://assets.prestashop2.com/en/system/files/ps_releases/changelog_1.7.6.0.txt
https://assets.prestashop2.com/en/system/files/ps_releases/changelog_1.7.6.1.txt

Thanks!

**Comment by mreco** [comment]
Unfortunately I didn't find anything. Can anyone help me. Unfortunately, I'm not an IT specialist.

**Comment by khouloudbelguith** [comment]
@mreco, could you please check those PRs: https://github.com/PrestaShop/PrestaShop/pull/12597
https://github.com/PrestaShop/PrestaShop/pull/13009

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mreco,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
