### ISSUE TITLE
Prestashop 1.7.5.2 Translations not working

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#15612]
I have a smartblog module, and the text translations do not work at all in it. In PHP scripts, neither of these codes works:

class smartblog extends Module {

public $nrl;

public function __construct() {

        $this->nrl = $this->trans('Name is required.', array(), 'Modules.Smartblog.Shop');
        $this->nrl = $this->trans('Name is required.', array(), 'Modules.Smartblog');
        $this->nrl = Context::getContext()->getTranslator()->trans('Name is required.', array(), 'Modules.Smartblog.Shop');
        $this->nrl = Context::getContext()->getTranslator()->trans('Name is required.', array(), 'Modules.Smartblog');

}

}

In tpl. it is not such an issue, as the translations can be exported to an .xlf file.
It is insane to see such number of problems with the Prestashop translation system, it is a complete disaster.

**Comment by khouloudbelguith** [comment]
Hi @elrosi,

Thanks for your report.
I tried with PS1.7.5.2 & this demo module & translations => OK
[translationbug.zip](https://github.com/PrestaShop/PrestaShop/files/3630987/translationbug.zip)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @elrosi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by elrosi** [comment]
The update to Prestashop  1.7.6 helped. In the version PS1.7.5.2 in .tpl files the translations work correctly, in PHP files not.
Thank you for your help and response.
