### ISSUE TITLE
Removal of a customization makes impossible to remove a product from the cart

### ISSUE THREAD

**Issue by jocel1** [PrestaShop/PrestaShop#15624]
**Describe the bug**
Add a customization to a product, remove the customization, put the product into your cart. You'll not be able to remove the product from the cart because will still have an id_customization associated, but no more customized_data

**To Reproduce**
1. Create a product with a customized field
2. In the product page, add a customization, click save.
3. Click once again on save without any customization text, this will delete the customization
4. Add the product into your cart
5. You will not be able anymore to remove the product from your cart

Tested on 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @jocel1,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & PS1.7.6.0.
The Customization should not be required.
https://drive.google.com/file/d/1FL1lEjSAhlPImIUr8PPWof_uQa9MoRGb/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15625
