### ISSUE TITLE
Update order status to shipped also updates order as paid with cash on delivery 

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#15620]
While customer order any item with cash on delivery option and once we update order as shipped. I have seen that status of order changes as paid even it’s not confirmed that order is not delivered or paid.

**Additional information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

In your BO => Shop Parameters => Order Settings => Statuses Tab => Edit the Shipped status & you can check that the "Set the order as paid." option is selected.
![image](https://user-images.githubusercontent.com/16067358/65259867-4c1c1280-dafd-11e9-98fc-587490164ffb.png)

Thanks!

**Comment by dineshbadrukhiya** [comment]
Sorry I haven't checked that.
It's selected. You are right :) @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@dineshbadrukhiya, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
