### ISSUE TITLE
Search indexing buggy

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15626]
PrestaShop 1.7.5.2

Our customers has 1280 products.
All products are indexed when you looking at Settings > Search in the back-end.
When you search in front you see on keyword "keys" 8 results. But there are 70 results.
So the indexing is wrong. We need to push on Reindex everything to let it work again.

This happens once a month. Any idea?

**Comment by khouloudbelguith** [comment]
Hi @sdwebdesign,

Did you update those products, for example, disable them or updating from import page?

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith Nope. Just add new products.

**Comment by khouloudbelguith** [comment]
@sdwebdesign, in your BO => Shop Parameters => Search page, Indexing is enabled or not?
![image](https://user-images.githubusercontent.com/16067358/65314625-97cacc80-db8e-11e9-8dc7-435ffb7b3971.png)
In the BO => Shop Parameters => Product Settings page, "Default activation status" option is enabled or disabled?
![image](https://user-images.githubusercontent.com/16067358/65314716-c3e64d80-db8e-11e9-9cc6-d418734a87ac.png)


Thanks!

**Comment by ghost** [comment]
@khouloudbelguith thank you! 

Indexing = enabled (yes)
Default action status = No

**Comment by khouloudbelguith** [comment]
@sdwebdesign, so after creating new products => they are disabled => did you enable them from the product list page?
![image](https://user-images.githubusercontent.com/16067358/65318139-06128d80-db95-11e9-8470-dd17fb7284d4.png)

Thanks!

**Comment by ghost** [comment]
Creating products, the online offline switch in the product edit screen itself. So not change status in that list view.

**Comment by khouloudbelguith** [comment]
@sdwebdesign, thanks for your feedback.
>When you search in front

Are you searching with the product's name?

Thanks!

**Comment by ghost** [comment]
Thanks! Yes.

**Comment by khouloudbelguith** [comment]
@sdwebdesign, I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1IuYdU2VaPCiwU0FD2RQUzbc5Xz-DRbGm/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @sdwebdesign,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
