### ISSUE TITLE
PS 1.7.6.1 Two states when creating orders with payment by transfer

### ISSUE THREAD

**Issue by ganiveteria** [PrestaShop/PrestaShop#15639]
We have an issue with the transfer payment in version 1.7.6.1, which we cannot resolve:

When a customer accepts an order with payment by transfer, Prestashop creates a "Waiting for payment by bank transfer" order and then creates another "Payment remotely accepted" situation, leaving it there.

I guess it must be an error of the latest version 1.7.6.1, because in versions before 1.7.6 it did not happen.

With other forms of payment, it does not happen.

If someone has a solution or suggestion to indicate it, please.

Manuel

![Captura de pantalla 2019-09-22 01 33 19](https://user-images.githubusercontent.com/55640010/65380335-a5409d80-dcd9-11e9-88a4-e17f7863f737.png)

![Captura de pantalla 2019-09-22 01 30 45](https://user-images.githubusercontent.com/55640010/65380348-11bb9c80-dcda-11e9-9489-961a20b69c89.png)

**Comment by khouloudbelguith** [comment]
Hi @ganiveteria,

I did not manage to reproduce the issue with PS1.7.6.1 & the Bank transfer module v2.0.4.
https://drive.google.com/file/d/1gPJCn-89IUd6xTU8j-E8pK7y5mZ3XL2E/view
What is the exact version of Bank transfer module did you use?

Thanks!

**Comment by ganiveteria** [comment]
In our case, we have discovered that it only happens in those orders that there is no stock available but it can be purchased.

In orders with products in stock, it works well, does not generate the incidence.

While the problem is resolved, we have activated "Hide this status in all customer orders" and deactivated the rest of the options in the "Payment remotely accepted" state, so that the incident is not shown in the customer order tracking, but still showing up in the Backoffice.

https://drive.google.com/open?id=1SwCMCObc5qpYIlrSQ1ggvPxgr_tvYSKr

Regards,

**Comment by khouloudbelguith** [comment]
@ganiveteria, the status is wrong, it should be "On backorder (not paid)".
![image](https://user-images.githubusercontent.com/16067358/65420720-c8fb0500-ddf9-11e9-96ca-488700d89d97.png)
Thanks to navigate to the BO => Shop Parameters => Order Settings page => Statuses Tab & provide me a screenshot.

**Comment by ganiveteria** [comment]
we use the same version

Attached video of when there is stock of the product, then it works well.

https://drive.google.com/open?id=12S9zXai0pY6JA6hfNxm5YG43jjlOX5xM

Attached screen printing requested

![estados](https://user-images.githubusercontent.com/55640010/65421925-51cb6e00-de05-11e9-9f4c-48e776bd5c76.png)

Regards,

**Comment by khouloudbelguith** [comment]
@ganiveteria, as I expected.
By default, the id of the status On backorder is 12 ( in your case "Payment remotely accepted")
Which is wrong.
Did you edit status from the database manually?
Those statuses cannot be deleted from the BO.
![image](https://user-images.githubusercontent.com/16067358/65422461-76701780-ddfe-11e9-8c41-cfa71049b96a.png)

Thanks!

**Comment by ganiveteria** [comment]
We have changed the title in the Backoffice and the link to the out-of-stock template.

Thank you very much for the technical support.

Best regards

**Comment by khouloudbelguith** [comment]
@ganiveteria, you are welcome!
Feel free to open a new one when needed.

Thanks!
