### ISSUE TITLE
ps_facetedsearch module. Products not showed if are not in default categories

### ISSUE THREAD

**Issue by AndreaC71** [PrestaShop/PrestaShop#15636]
In ps_factedsearch module using last version 3.0.0 there is a bug on products showed.

Configuration example: https://prnt.sc/p9190i

If I set NO in "Include products from Subcategories" in the module configuration, the product is not showed in "Partecipazioni Matrimonio" category page even if the product is configured in the product. The reason is that "Partecipazioni Matrimonio" is not default category.

The expectation should be that the product is showed in both configured categories.

**Comment by PierreRambaud** [comment]
Duplicate of #14003
