### ISSUE TITLE
How to remove vatnumber field address page in prestashop1.7

### ISSUE THREAD

**Issue by Prem-lmx** [PrestaShop/PrestaShop#15644]
Hi i'm work the prestashop1.7.5
How to remove vatnumber field address page in prestashop1.7

**Comment by khouloudbelguith** [comment]
Hi @Prem-lmx,

You need to navigate to your BO => International => Locations => Countries => edit your country => remove the `vat_number` from the Address format.
![image](https://user-images.githubusercontent.com/16067358/65412956-3aca5300-dde8-11e9-9dc4-a11c235d08b4.png)
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by Prem-lmx** [comment]
Thank you for your response..
