### ISSUE TITLE
My prestashop don't use method getLayout() in FrontController

### ISSUE THREAD

**Issue by kubiak85** [PrestaShop/PrestaShop#15648]
Hi I have Prestashop 1.7.5.2. My  prestashop don't using getLayout(). I woulde like to change layount in this function. This method  is not called ?

**Comment by khouloudbelguith** [comment]
Hi @kubiak85,

No, it is called.
If you create an override /override/controllers/front/listing/CategoryController.php with incorrect code, clear cache & in the FO => Go to any category => an exception is displayed.

```
<?php
class CategoryController extends CategoryControllerCore
{
    public function initContent()
    {
        parent::initContent();
        if ($this->category->checkAccess($this->context->customer->id))
            $this->doProductSearch('catalog/listing/category', array('entity' => 'category', 'id' => $this->category->id));
        else
        {
            header('HTTP/1.1 403 Forbidden');
            header('Status: 403 Forbidden');
        }
    }
    public function getLayout()
    {

        if (!($this->category->checkAccess($this->customer->id)))

            return 'layouts/layout-full-width.tpl';
}
}
```
![image](https://user-images.githubusercontent.com/16067358/65415328-71ef3300-dded-11e9-8b2b-e9c572e068e3.png)

Thanks to check & feedback.

**Comment by kubiak85** [comment]
@khouloudbelguith thank's

**Comment by khouloudbelguith** [comment]
@kubiak85, you are welcome!
Feel free to open a new one when needed.

Thanks!
