### ISSUE TITLE
Can't add to cart from list/category pages

### ISSUE THREAD

**Issue by ccoltman** [PrestaShop/PrestaShop#15647]
**Describe the bug**
Items are added to the cart with 0 quantity if they require customization field.

**To Reproduce**
1. Add product to cart which requires customization field.
2. View cart contents.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1

I would like a notification/alert if a product requires customization before adding. Customers think the store is broken, though the store works for products that do not have the customization field.

**Comment by khouloudbelguith** [comment]
Hi @ccoltman,

The `Customization` is required or not?
In my case, with PS1.7.6.1 => OK
I attached a screen record
https://drive.google.com/file/d/1kjjHl5QRtl04_S9rLuWM7acmZTnYVNdQ/view
Thanks to check & feedback.

**Comment by ccoltman** [comment]
Yes I have them required, but from a category / list page it is added with 0 quantity. The products detail page is the **only** place you can add the customization field, but in areas like New Products, or Featured Products, the Add to Cart button exists and malfunctions.

**Comment by khouloudbelguith** [comment]
@ccoltman,
>category / list page it is added with 0 quantity.

Are you using the click view action?
![image](https://user-images.githubusercontent.com/16067358/65443234-9961f200-de25-11e9-9f7c-e9de69a56764.png)

Thanks!

**Comment by ccoltman** [comment]
Ahh I see, it's possible that the theme I'm using adds its own Add to Cart for the category and list pages. Thanks for clarifying this.

**Comment by khouloudbelguith** [comment]
@ccoltman,
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
