### ISSUE TITLE
Searching for a module in Quicksearch BO links to module catalog 

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15653]
When searching for a module in BO - Quicksearch the module is found.

When clicking on the module, the module is not opened. Instead redirected to the module catalog.

Prestashop 1.7.6.1

<img width="964" alt="Screenshot 2019-09-23 at 12 14 18" src="https://user-images.githubusercontent.com/46492443/65421698-46c01000-ddfc-11e9-8fe1-8ddaf1b5054f.png">
<img width="1101" alt="Screenshot 2019-09-23 at 12 14 38" src="https://user-images.githubusercontent.com/46492443/65421701-4889d380-ddfc-11e9-892f-223a37504a2f.png">

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by aniszr** [comment]
Hello,

I couldn't reproduce this issue in my PS 8.0.4.
See attached screenshots.

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/0a15683b-db96-4a56-82c7-ee208b0dc30e)

--->On click,redirected to the module manager page.
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/4ba5f23e-49d3-4d4d-ba06-fe5dfce7fe26)

Thanks!
