### ISSUE TITLE
error during upgrade from 1.7.5.2 to 1.7.6.1 | ALTER TABLE ps_tab | Integrity constraint violation

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15654]
Executing: ALTER TABLE ps_tab CHANGE id_tab id_tab INT AUTO_INCREMENT NOT NULL
12:29:32 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "An exception occurred while executing 'ALTER TABLE ps_tab CHANGE id_tab id_tab INT AUTO_INCREMENT NOT NULL':
SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '1' for key 'PRIMARY'" ["exception" => Doctrine\DBAL\Exception\UniqueConstraintViolationException { …},"command" => "prestashop:schema:update-without-foreign","message" => """ An exception occurred while executing 'ALTER TABLE ps_tab CHANGE id_tab id_tab INT AUTO_INCREMENT NOT NULL':\n \n SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '1' for key 'PRIMARY' """]
In AbstractMySQLDriver.php line 66:
An exception occurred while executing 'ALTER TABLE ps_tab CHANGE id_tab id_
tab INT AUTO_INCREMENT NOT NULL':
SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes au
to_increment resequencing, resulting in duplicate entry '1' for key 'PRIMAR
Y'
In PDOConnection.php line 106:
SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes au
to_increment resequencing, resulting in duplicate entry '1' for key 'PRIMAR
Y'
In PDOConnection.php line 104:
SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes au
to_increment resequencing, resulting in duplicate entry '1' for key 'PRIMAR
Y'
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]
Błędy
Error during database upgrade. You may need to restore your database.
Error upgrading Doctrine schema

**Comment by khouloudbelguith** [comment]
Hi @pl2019,

What is the exact version of the 1-click upgrade did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by pl2019** [comment]
Hi,

1-Click Upgrade
v4.9.0 - z PrestaShop

log.txt is empty

**Comment by ghost** [comment]
1-click-upgrade
4.9.0

**Comment by ghost** [comment]
[upgrade-log.txt](https://github.com/PrestaShop/PrestaShop/files/3641947/upgrade-log.txt)

**Comment by khouloudbelguith** [comment]
@pl2019, I did not manage to reproduce the issue after upgrade from PS1.7.5.2 to PS1.7.6.1 using the 1-click upgrade v4.9.0.
You have an issue with table Prefix_tab
Thanks to check the structure of this Table
![image](https://user-images.githubusercontent.com/16067358/65432388-fef8b300-de12-11e9-8e60-3a7617504853.png)

Thanks!

**Comment by ghost** [comment]
Works perfect! Thank you for your help 
Database upgrade OK
Let's close this ticket

**Comment by ghost** [comment]
CLOSED

**Comment by khouloudbelguith** [comment]
@pl2019, Great!
Feel free to open a new one when needed.

Thanks!
