### ISSUE TITLE
Validate.php & customer.php

### ISSUE THREAD

**Issue by Nykolium** [PrestaShop/PrestaShop#15663]
**Describe the bug**
in **

> validate.php

** after change line
 ` public static function isCustomerName($name)
    {
        $validityPattern = Tools::cleanNonUnicodeSupport(
            '/^(?:[^!<>,;?=+()\/\\@#"°*`{}_^$%:¤\[\]|\.。]|[\.。](?:\s|$))*$/u'
        );`
Nothing append 

Same problem if i would change **custumer.php**
if i change by a other "validity" nothing append .

This change work well on 1.7.4 I don't understand why
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @Nykolium,

It is OK for me with PS1.7.6.1.
I replaced this 
```
    public static function isCustomerName($name)
    {
        $validityPattern = Tools::cleanNonUnicodeSupport(
            '/^(?:[^0-9!<>,;?=+()\/\\@#"°*`{}_^$%:¤\[\]|\.。]|[\.。](?:\s|$))*$/u'
        );

        return preg_match($validityPattern, $name);
    }
```
![image](https://user-images.githubusercontent.com/16067358/65591682-d0024e80-df84-11e9-81a8-6878578a19bc.png)


By this
```
public static function isCustomerName($name)
    {
        $validityPattern = Tools::cleanNonUnicodeSupport(
            '/^(?:[^!<>,;?=+()\/\\@#"°*{}_^$%:¤[]|.。]|.。)*$/u'
        );

        return preg_match($validityPattern, $name);
    }
```
In the FO, when I try to create a new custom with Firstname & Lastname test123 => It is OK
https://drive.google.com/file/d/1jDVpGrvhVLBzEA4As0kawJEgfzCxDxHT/view

In your BO => Advanced Parameters => Performance => disblae the cache & clear it.

Thanks!

**Comment by Nykolium** [comment]
Hi , 
thx for reply , 
But it doesn't work if only modify **validate.php.**
Have to modify firstname.php (and for me, lastname.php) in
**Core/Domain/Customer/ValueObject**
Thx for reply.

**Comment by khouloudbelguith** [comment]
@Nykolium, no, in my case, I changed only the class validate.php & it is OK.
Thanks!

**Comment by Nykolium** [comment]
@khouloudbelguith 
sur you are in 1.7.6.1 ?
very strange , because I loose 1 day to search th problem , lol.
I try with safari or chrome cache clear, try to always recompile smarty... idem

And after made a other only for test, new prestashop on NAS,
try change valide no way, finaly seach the character from Dreamwaver an find Firstname.php.
What is the difference ?  I'm curius, i'm sur for you it work, but i'm  realy sur for me it doesn't work :-)

**Comment by Nykolium** [comment]
Hum, maybe I use only number no ,alpha character.
And it's not for auto register user, it's back-office

**Comment by khouloudbelguith** [comment]
@Nykolium, the function `Validate::isCustomeName()` has been introduced in PS 1.7.5.2 in order to mitigate spam attacks. You can see it here: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L166

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Nykolium,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
