### ISSUE TITLE
PS 1.7.6 Virtual Product not work JS button and add to cart no submit product

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#15669]
**Describe the bug**
Create a new virtual product, assign a file.
Open the product on FO.
Try to play with all the javascript driven button (language, currency) not work. 
Try to add to cart, cart are loaded and shown empty.

**To Reproduce**
https://www.sixrace.it/it/manuali/81806-manuale-officina-2015-ktm-450-sx-f-factory-edition.html

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

I tried with your shop & it is OK
https://drive.google.com/file/d/1lPl89N5B3WNcBwxnWgcyqE9b4AM3rqHz/view

Thanks!

**Comment by matteolavaggi** [comment]
i'm not able to have it work on chrome:
![image](https://user-images.githubusercontent.com/24798703/65507832-12695400-decf-11e9-8423-dade05b35e0c.png)

**Comment by matteolavaggi** [comment]
Also with firefox
![image](https://user-images.githubusercontent.com/24798703/65507900-3fb60200-decf-11e9-9040-76633eb3c89e.png)

**Comment by matteolavaggi** [comment]
And also with IE 
![image](https://user-images.githubusercontent.com/24798703/65508026-8a377e80-decf-11e9-8036-aa2916d84e7c.png)

**Comment by matteolavaggi** [comment]
i'm not able to open language and currency selector and to add product in cart O_O

**Comment by matteolavaggi** [comment]
And also in different server on remote desktop in different country and language (france)
![image](https://user-images.githubusercontent.com/24798703/65508193-fb773180-decf-11e9-859f-3d7450e8c434.png)

**Comment by khouloudbelguith** [comment]
@matteolavaggi, it is well working on me.
I tried with FireFox v64.0.2.
https://drive.google.com/file/d/1KPy7d_orZnl20j1WePRekSWlW3FLEZEU/view
Thanks!

**Comment by matteolavaggi** [comment]
I've try on 3 different computer, also now on a mac, with same result. Have you reloaded the page 1 time and try again?

I've try to reset the cache related to that page with no change.

Browser cache is cleared , computer changed, operating system changed, browser changed, there is no way to have it working starting from the italian version or france version.

**Comment by matteolavaggi** [comment]
https://drive.google.com/file/d/1yYqzDKLytKKq1MKU-eu18fDJ836GAA3n/view

**Comment by khouloudbelguith** [comment]
@matteolavaggi, so strange!
Your shop is well working.
I tried with a Mac also => Ok
https://drive.google.com/file/d/1o0o0V7wSOq7pNCd7nUKDyq5OxIa6zexO/view
Thanks!

**Comment by matteolavaggi** [comment]
Ok, but its not possible that on your test is ok and on mine not work at all, i'm still testing over smartphone, other computer is our office, tablet, ecc, i'venot yet seen 1 time it work, so strange, there is something that does not work, how to debug? we cant use any virtual products

**Comment by khouloudbelguith** [comment]
@matteolavaggi, I tried with mobile phone & it is well working
[videoplayback.mp4.zip](https://github.com/PrestaShop/PrestaShop/files/3647573/videoplayback.mp4.zip)
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) and try to run those command lines to remove the cache:
```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Thanks to check and feedback.

**Comment by matteolavaggi** [comment]
i've a script that delete the var/cache folder, nginx and apache and mod page speed cache and restart nginx and apache. i've run it with no difference.
Also i've run the command using the console bin and the command you provide to me, with no luck.

I dont use in production the smarty cache NOR the CCC NOR the cache of prestashop due to poor performance so all is disable.

![image](https://user-images.githubusercontent.com/24798703/65522194-b0b6e300-deea-11e9-8656-429ce2c91a2a.png)
This is the result, error 500 and web site down ... O_O

![image](https://user-images.githubusercontent.com/24798703/65522225-bdd3d200-deea-11e9-9a2c-08f4a203ba77.png)

**Comment by matteolavaggi** [comment]
FRONT OFFICE AND BACK OFFICE DOWN . on a production website is awesome....

**Comment by khouloudbelguith** [comment]
@matteolavaggi, it could be a permission issue.
You need to give the right permissions to your PrestaShop folder.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matteolavaggi** [comment]
How i can enable debug mode on a 500 server error ?! its possible that using a prestashop command to clear cache brake down a website .. this is f*** crazy.

**Comment by matteolavaggi** [comment]
I'm shocked. The console script you send to me complete delete all the root HTDOCS FOLDER of my web site. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by khouloudbelguith** [comment]
@matteolavaggi, you can edit the file config/defines.inc.php & replace 
https://github.com/PrestaShop/PrestaShop/blob/develop/config/defines.inc.php#L29
```
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', false);
}
```
By

```
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', true);
}
```

Those commands are used to clear the cache.

Thanks!

**Comment by matteolavaggi** [comment]
@khouloudbelguith maybe you have not read my answer, the script console file you ask me to run COMPLETE delete the htdocs folder. Remove the prestashop folder and all other folder of other website

**Comment by khouloudbelguith** [comment]
@matteolavaggi, those commands are used to clear the cache only.
For more details, you can follow this link: https://symfony.com/doc/3.3/console/usage.html

Thanks!

**Comment by matteolavaggi** [comment]
Dear, 1 second before all ok. Launch the command you can see above and the directory root of web server was deleted. Its related, now i need to fix 300GB of data. damn prestashop

**Comment by khouloudbelguith** [comment]
@matteolavaggi, all developers use this command, but this is a first time that clearing the cache can delete all folders.
You need to check again what is the exact issue of deleting all these folders.
Or you can check your host about this issue.

Thanks!

**Comment by matteolavaggi** [comment]
i will ask my host "hi, maybe you delete the root folder of my server the exact second i run a command on bin console prestashop" ... ok. Thanks a lot. now i need to fix more problem than this virtual product that not work.. hope to get back asap. will never use any other time a prestashop buggy console script in my life.

**Comment by khouloudbelguith** [comment]
@matteolavaggi, thanks!
Waiting for your feedback.

**Comment by matteolavaggi** [comment]
Maybe you think that you are in right but i will suggest to deeep inspect the 1.7.6.1 console, this is not a fun if there is only 1% of possibility that this script delete the root folder from wich is launched i thinik you need to check 30 times. i've launch the shell script you send to me and after the 2 green confirmation i've open the web page and found the 500 error, and the root folder DELETED.

**Comment by matteolavaggi** [comment]
[proxy_fcgi:error] [client 127.0.0.1:35564] www.sixrace.it AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/htdocs/www.sixrace.it/config/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/htdocs/www.sixrace.it/config/autoload.php on line 26\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /var/www/htdocs/www.sixrace.it/index.php:0\nPHP message: PHP   2. require() /var/www/htdocs/www.sixrace.it/index.php:27\nPHP message: PHP   3. require_once() /var/www/htdocs/www.sixrace.it/config/config.inc.php:36\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/htdocs/www.sixrace.it/config/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/htdocs/www.sixrace.it/config/autoload.php on line 26\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /var/www/htdocs/www.sixrace.it/index.php:0\nPHP message: PHP   2. require() /var/www/htdocs/www.sixrace.it/index.php:27\nPHP

**Comment by matteolavaggi** [comment]
I've restored all the backup, late this morning i will launch again the command on a test machine to diagnose the root cause of the delete problem.

Now still with the same virtual product issue not yet solved.

I've cleared the post for bettere reading of other people.

**Comment by khouloudbelguith** [comment]
@matteolavaggi, Great!
Your issue is strange!
I tried with the same link provided, but it is OK.
same link provided, but it is OK.
https://drive.google.com/file/d/1n8lZGcaPgT8mROc-fVs32VzJ8AVqKtFl/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Also, try to use a Private Browser or Navigation incognito.

Thanks!

**Comment by matteolavaggi** [comment]
`

(1/1) ContextErrorExceptionNotice: Undefined variable: release_date
--
in estimateddelivery.php line 1807
at Estimateddelivery->printProductSpecialDate(object(DeliveryProduct), 'tpl')in estimateddelivery.php line 1677
at Estimateddelivery->showEstimatedDelivery(array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))in estimateddelivery.php line 3070
at Estimateddelivery->hookDisplayProductAdditionalInfo(array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))in pagecache.php line 1720
at PageCache::execHook('m', object(Estimateddelivery), 'hookdisplayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))in Hook.php line 24
at Hook::coreCallHook(object(Estimateddelivery), 'hookdisplayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))in Hook.php line 355
at HookCore::callHookOn(object(Estimateddelivery), 'displayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))in Hook.php line 907
at HookCore::exec('displayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayProductAdditionalInfo', 'product' => object(ProductLazyArray)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayProductAdditionalInfo', 'product' => object(ProductLazyArray)), object(SmartyDevTemplate)))in 6c25ecf88e5754470dff37f872a25a832ccb018f_2.file.product-additional-info.tpl.php line 25
at content_5d8b306f145043_84642835(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('file:catalog/_partials/product-additional-info.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 0, false)in 64d02c4e9b140a45b3fad71ec7a0cd0b0f840e68_2.file.product.tpl.php line 350
at Block_16128353495d8b306d46caf2_80754974->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_16128353495d8b306d46caf2_80754974), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_16128353495d8b306d46caf2_80754974))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_16128353495d8b306d46caf2_80754974', 'product_additional_info', 0)in 64d02c4e9b140a45b3fad71ec7a0cd0b0f840e68_2.file.product.tpl.php line 400
at Block_3587368005d8b306d4416f7_40216279->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_3587368005d8b306d4416f7_40216279), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_3587368005d8b306d4416f7_40216279))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_3587368005d8b306d4416f7_40216279', 'product_buy', 0)in 64d02c4e9b140a45b3fad71ec7a0cd0b0f840e68_2.file.product.tpl.php line 877
at Block_14992273375d8b306d3d22a2_51653639->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_14992273375d8b306d3d22a2_51653639), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_14992273375d8b306d3d22a2_51653639), object(Block_3037592105d8b306d462452_54393587))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_3037592105d8b306d462452_54393587))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_3037592105d8b306d462452_54393587', 'content', 1)in d6f49b47d0e8c0be4c4a627222a4a4b664b372fd_2.file.layout-full-width.tpl.php line 101
at Block_20874361675d8b306d45ff89_80915106->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_20874361675d8b306d45ff89_80915106), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_20874361675d8b306d45ff89_80915106), object(Block_1599118145d8b306d4aa056_15603812))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_1599118145d8b306d4aa056_15603812))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_1599118145d8b306d4aa056_15603812', 'content_wrapper')in 2d21265fb669d6a6417690eae2d8ab1329e64fbd_2.file.layout-both-columns.tpl.php line 87
at content_5d8b306d4d91a1_45643071(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in d6f49b47d0e8c0be4c4a627222a4a4b664b372fd_2.file.layout-full-width.tpl.php line 42
at content_5d8b306d465214_85648499(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 64d02c4e9b140a45b3fad71ec7a0cd0b0f840e68_2.file.product.tpl.php line 54
at content_5d8b306d4f8825_93304838(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('catalog/product.tpl')in FrontController.php line 90
at FrontController->smartyOutputContent('catalog/product.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 311
at ControllerCore->run()in Dispatcher.php line 387
at Dispatcher->dispatch()in index.php line 28

`

**Comment by matteolavaggi** [comment]
`[proxy_fcgi:error] [client 127.0.0.1:42170] www.sixrace.it AH01071: Got error 'PHP message: PHP Notice:  Undefined offset: 4 in /var/www/htdocs/www.sixrace.it/classes/tax/TaxCalculator.php on line 124\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /var/www/htdocs/www.sixrace.it/index.php:0\nPHP message: PHP   2. Dispatcher->dispatch() /var/www/htdocs/www.sixrace.it/index.php:28\nPHP message: PHP   3. ProductController->run() /var/www/htdocs/www.sixrace.it/override/classes/Dispatcher.php:387\nPHP message: PHP   4. ProductController->initContent() /var/www/htdocs/www.sixrace.it/classes/controller/Controller.php:291\nPHP message: PHP   5. ProductController->getTemplateVarProduct() /var/www/htdocs/www.sixrace.it/controllers/front/ProductController.php:347\nPHP message: PHP   6. ProductCore::getProductProperties() /var/www/htdocs/www.sixrace.it/controllers/front/ProductController.php:1069\nPHP message: PHP   7. ProductCore::getTaxesInformations() /var/www/htdocs/www.six`

`ook.php:359\nPHP message: PHP  45. PageCache::execHook() /var/www/htdocs/www.sixrace.it/override/classes/Hook.php:24\nPHP message: PHP  46. Ganalytics->hookProductFooter() /var/www/htdocs/www.sixrace.it/modules/pagecache/pagecache.php:1720\nPHP message: PHP  47. Ganalytics->wrapProduct() /var/www/htdocs/www.sixrace.it/modules/ganalytics/ganalytics.php:630\n'`


Do you like to see php error in real time? We can setup a live access on web syslog server for you.

**Comment by khouloudbelguith** [comment]
@matteolavaggi, you have some errors with the `pagecache` & `estimateddelivery` modules.
As they are not provided by Prestashop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by matteolavaggi** [comment]
Only virtual product does not work, same error are shown also on other product page but with no bug on button or add to cart.

I've try to disable both modules with no change on bug. Still impossible to use top menù
 and add to cart button with

page cache disabled
estimated delivery disabled
analytics disabled

Issue is related to prestashop js i think

**Comment by khouloudbelguith** [comment]
@matteolavaggi, I tried with another pc & it is Ok on your shop.
It is well working!
The product is well added to the shopping cart & I can switch languages & currencies.
How it could be a prestashop js & it is ok for me?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by ShaimyWinda** [comment]
@matteolavaggi Hello, i have the same problem. I wanted to know how you solved the problem. Thanks
