### ISSUE TITLE
Incorrect amount of ecotax when tax excluded

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#15666]
**Describe the bug**

The final product price is incorrect when ecotax is enabled and the prices are tax excluded. It's not just a display problem. On the cart, the price is the same as displayed.

Maybe the price is incorrect with other configurations, I haven't tested it.

**To Reproduce**

1. Enable ecotax

2. Show prices tax excluded

3. Create a product with:

  - Price (tax excl): 50€
  - Ecotax (tax incl): 1.2€

4. On the front-office, the price (tax excluded) displayed is 51.20€ instead of 51€

It seems that the price displayed on the product page add the ecotax tax included to the price tax exluded.

I changed the amounts so that the final price (tax excluded) is correct, but it is the price tax included that becomes incorrect.

**Screenshots**

The product:
![image](https://user-images.githubusercontent.com/22885898/65496417-b3004980-deb8-11e9-971a-6551978f720a.png)

The front office:
![image](https://user-images.githubusercontent.com/22885898/65496436-bbf11b00-deb8-11e9-8592-a2860f65cdcb.png)

**Additional information**

PrestaShop version: 1.7.6.0
PHP version: 7.2.20

**Comment by khouloudbelguith** [comment]
Hi @yannicka,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9855
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #9855
