### ISSUE TITLE
reactivesearch / facteted search

### ISSUE THREAD

**Issue by lucmski** [PrestaShop/PrestaShop#15661]
Hi Guys,

Hope you are all well !

Do you have some professional faceted search like example above ?

### Screenshots
![alt text](https://github.com/lucmski/twint-search/raw/master/docs/screenshot1.png "Screenshot #1")

![alt text](https://github.com/lucmski/twint-search/raw/master/docs/screenshot2.png "Screenshot #2")

It is based on https://github.com/appbaseio/reactivesearch and elasticsearch

Cheers,
Luc Michalski

**Comment by khouloudbelguith** [comment]
Hi @lucmski,

We have a native module provided by PrestaShop: https://github.com/PrestaShop/ps_facetedsearch.
But also you can also find a lot of modules on our MarketPlace: https://addons.prestashop.com/en/search?id_category=510

Thanks!
