### ISSUE TITLE
Category Page : Canonical URL of the product wrong (!= canonical url on the product page)

### ISSUE THREAD

**Issue by DoIB** [PrestaShop/PrestaShop#15667]
The variable Canonical URL of a product on the category page is different of the one on the product page.

Prestashop v 1.7.5.1

**Comment by khouloudbelguith** [comment]
Hi @DoIB,

We have made some fixes in the next versions PrestaShop.
https://github.com/PrestaShop/PrestaShop/pull/15013
https://github.com/PrestaShop/PrestaShop/pull/13664
https://github.com/PrestaShop/PrestaShop/pull/13009
Thanks to check & feedback.

**Comment by DoIB** [comment]
Look like the default category of the product is not part on the canonical url variable on the product listing.

**Comment by khouloudbelguith** [comment]
@DoIB,

> on the product listing.

So, you are in the Category page, for example, the default category of the product is not part of the canonical URL variable?
![image](https://user-images.githubusercontent.com/16067358/65503829-a3373400-debd-11e9-89b4-b81c32c16a0f.png)

Thanks!

**Comment by DoIB** [comment]
No. The url of the product on the listing is different of the url of the product page targeted by the category listing (redirection of the url product).

When i try to change it with the canonical url in the theme, the url is still wrong.
So when i click on the product, i have a redirect (hurtful for SEO).

The url of the product seems to be always align with the current category.
When we try to change with the canonical url of the product, the variable canonical url
of the product (on the listing of the current category) is wrong.

**Comment by khouloudbelguith** [comment]
@DoIB, I did not manage to reproduce the issue with PS1.7.6.1.
It is the same Product URL
https://drive.google.com/file/d/1-gYMM7Ex2ZSsSuOGMwbVaQSXFS_rvcq6/view
Can you please navigate to the BO => Shop Parameters => Traffic & SEO => check the Schema of URLs
![image](https://user-images.githubusercontent.com/16067358/65507992-11ccbf80-dec7-11e9-9e34-f8f82aa351e0.png)

Thanks!

**Comment by DoIB** [comment]
Yeah, it's the same schema

**Comment by DoIB** [comment]
In some case, you have a product with multiple category but one default category.

The shop seems to display an product url with the current category (in it) on the product listing of the associated category (instead of one an only one url for all the shop). The url need the default category on it (instead of the current category)

**Comment by DoIB** [comment]
Otherwise, it's hurtfull for SEO :)

**Comment by khouloudbelguith** [comment]
@DoIB, I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
With PS1.7.5.2
The URL of the product in the category page (the default or no) is the same
![image](https://user-images.githubusercontent.com/16067358/65512523-49d90000-ded1-11e9-9415-1903774327d4.png)
![image](https://user-images.githubusercontent.com/16067358/65512584-6d03af80-ded1-11e9-9fd3-ecab5e690a8e.png)

PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/65512678-945a7c80-ded1-11e9-80a1-53275f573344.png)

![image](https://user-images.githubusercontent.com/16067358/65512703-a5a38900-ded1-11e9-8333-d8b7cb781d2c.png)

Thanks!

**Comment by DoIB** [comment]
Weird. Could i have something in database scrambling the redirection ? 
I will try with the default theme then with the current theme.

If, with the default theme, i have still have the issue, do i have something to inspect or check ? :)

**Comment by khouloudbelguith** [comment]
@DoIB, did you use any custom module related to the SEO or URLs?

Thanks!

**Comment by DoIB** [comment]
No SEO module or module associated to category or products.
With the default theme, i have the issue.

The products and category come from an import (migrating Magento to Prestashop).

Could i have something in database scrambling the redirection ?

The issue seems to come from the default category. How to check and correct it ? :)

**Comment by khouloudbelguith** [comment]
@DoIB, Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by DoIB** [comment]
I checked. It's unchanged.

**Comment by khouloudbelguith** [comment]
Hi @DoIB,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
