### ISSUE TITLE
Products Combinations defect 

### ISSUE THREAD

**Issue by Refe313** [PrestaShop/PrestaShop#15662]
Hi,

**Describe the bug**

On a fresh new install,

In back-office, product list/product details, the products combination panel (overview and details) show a defect
The "Quantity" field of the 2nd combination row is missing when consulting the product (but creation is ok)
The defect only occurs on the 2nd row, and only on the quantity field, suggesting a broken db2 order when selecting combination for display.

**To Reproduce**

1. Go to Back-office
2. click on product
3. create a product with combinations
4. go back to product list
5. go back to product detail
6. access product combinations
7. quantity fiels on 2nd row missing

**Screenshots**

![image](https://user-images.githubusercontent.com/55719892/65468535-a4884280-de64-11e9-938d-7528848844ca.png)

![image](https://user-images.githubusercontent.com/55719892/65468579-d39eb400-de64-11e9-8da7-b9e2c4840685.png)

**Additional information**

I'm running Debian 9, PHP 7.0, Mysql 5.6, Prestashop 1.7.5.2

Thanks in advance for your help and ideas,

Bests regards,

**Comment by Refe313** [comment]
I must precise that i use a theme.

The bug does not occurs when using standard one.

Thanks again to all,

Bests regards

**Comment by khouloudbelguith** [comment]
Hi @Refe313,

Yes, in my case, I tried with PS1.7.6.1 => OK
Have you tried to contact the theme author about this issue?
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by Refe313** [comment]
Hi,

Thanks for your answer,

I'm currently in discussion with the theme creator,

Seems to be a CSS problem 

I may link here a description of the resolved issue if i get enough info to be revelant.

Thanks again, 

Bests regards,

**Comment by khouloudbelguith** [comment]
@Refe313, so it is a theme issue?

Thanks!

**Comment by Refe313** [comment]
Hi,

so it was indeed theme related.

Unfortunatly, I do not have the final techinal description of the problem or resolving so i'll just close this topic.

Thanks all,

Best regards

**Comment by khouloudbelguith** [comment]
@Refe313, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
