### ISSUE TITLE
Total percentage reduction incorrect on cart

### ISSUE THREAD

**Issue by juliendombret** [PrestaShop/PrestaShop#15670]
I have an article with a price including VAT
I apply a promotion of 5%
Total tax is not good

1. Create product with  59.9€ tax incl. (5.5% tax)
2. Create a 5% basket rule for this product
3. Add product to cart
4. See error : 1product : 59.9€ - Reduction : 3€ - Total : 56.91€ (59.9-3=56.91)?

**Screenshots**
![2019-09-24_14h13_29](https://user-images.githubusercontent.com/6337822/65511661-f8803f00-ded7-11e9-8925-d14beeed2cf1.png)

If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 1.7.2.22

**Comment by khouloudbelguith** [comment]
Hi @juliendombret,

The method of calcul is not correct in your case.
Total products - discount = 59.9 - 5% = 56.905 => rounded => 56.91
Total od discount = 59.9 - (59.9 -5%) = 2.99 => rounded => 3

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @juliendombret,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
