### ISSUE TITLE
Free shipping for domestic customer

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15674]
Hi,
Please consider to allow Free shipping only for domestic customers.
So if store country is set to ex. Poland then additional option in Carrier settings will allow (or not) free shipping only for domestic customers.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Can you please provide us a description of your issue?
- You need to create a cart rule with free shipping only for a group of customer or you need to add a new option in the BO => Carriers page?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
