### ISSUE TITLE
Losing cart after submitting to PayPal

### ISSUE THREAD

**Issue by lgfocus** [PrestaShop/PrestaShop#15677]
I have a customer that made an order and has paid thru PayPal.  The store did not receive a receipt from PayPal that the order has been paid for.  Not only do I not have a copy of this in the store, but I have no records of the customer being at the store on that day, no orders and no abandoned cart.  This is the second time this has happened with this customer.

Has this happened to anyone else?  Is there something more I can check?

**Comment by khouloudbelguith** [comment]
Hi @lgfocus,

I did not manage to reproduce the issue with PS1.7.6.1 & PayPal v4.5.0.
![image](https://user-images.githubusercontent.com/16067358/65583837-d3430d80-df77-11e9-8b7d-f642a0c8751c.png)
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks!
