### ISSUE TITLE
Improve webservice with batch processing

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#15672]
**Is your feature request related to a problem? Please describe.**
Webservice is granular, so, if you want to add or update a lot of data, you've to do an HTTP request for each elements. It can be very very time consuming with large amount of data.

**Describe the solution you'd like**
Webservice XML data are like this:
`<prestashop>
<product></product>
</prestashop>`

So you can send throw one http request only one object. I suggest to add batch processing like this:

`<prestashop>
**<products>**
<product></product>
<product></product>
<product></product>
**</products>**
</prestashop>`

Of course, it should be the same for all methods, not only product.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by khouloudbelguith** [comment]
Hi @Max84,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Weird to see that it's not implemented yet.
I'm not an expert in PrestaShop webservices, maybe some people could give us their point.

**Comment by eternoendless** [comment]
I having tried this myself but [looking at WebserviceRequest](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php#L1535) it looks like this is already possible. You'd have to format your xml like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
	<product>...</product>
	<product>...</product>
</prestashop>

**Comment by hibatallahAouadni** [comment]
Ping @eternoendless so what's the status of this issue? is it **`TBS`** or **`To Do`**?
PS: I will add **`TBS`** label for now :wink: feel free to change it.

**Comment by PierreRambaud** [comment]
He said that it's already possible to do it :) 

I'm closing it

**Comment by sneko** [comment]
Long time since then but I'm wondering if someone has an example of a bulk delete?

Thank you,
