### ISSUE TITLE
Price slider not working [ps_facetedsearch v. 3.3.0]

### ISSUE THREAD

**Issue by DevAmine** [PrestaShop/PrestaShop#15676]
**Describe the bug**
The price slider filter is not working, when I try to filter a specific category using the price slider 
It does not refresh the results, the URL gets updated. 
When I refresh the page the results shows correctly.

**Additional information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.33
ps_facetedsearch v. 3.3.0

**Comment by khouloudbelguith** [comment]
Hi @DevAmine,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & ps_facetedsearch v3.3.0.
What is the exact language & currency did you use in the FO?
Could you please click on the button "Index all missing prices" & "Rebuild entire price index", clear cache, check & feedback.

**Comment by DevAmine** [comment]
Hello @khouloudbelguith 
The language I am using is French and the currency is MAD (Moroccan dirham)
After selecting a price range the URL gets updated to **?q=Prix-MAD-7915-16905** , When I refresh the page after applying a price filter the results showing correctly. 
I have tried to index the price & rebuild the index, clear the cache. It does not solve the problem
Thank you!

**Comment by khouloudbelguith** [comment]
@DevAmine, It is ok for me
https://drive.google.com/file/d/1FjQBSpkO15hgCYU05m9zcrMJFV1OJtkw/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @DevAmine,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
