### ISSUE TITLE
Allow employee to choose their own avatar

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#15671]
**Is your feature request related to a problem? Please describe.**
Since employee cannot choose a theme variation, it becomes hard to know which employee is logged. The only one distinctive element is employee avatar.
![employee-top](https://user-images.githubusercontent.com/5262628/65513261-3e8ad200-dedb-11e9-8984-0fef8c5c4cb1.png)

Currently employee avatar still rely on third party service linked to PrestaShop Forum account. It's not possible to choose an avatar until create an account with same email on PrestaShop Forum.
So it's harder to quickly know who is currently logged as nobody goes to PrestaShop.com to create an account for upload their own avatar.

![employee-avatar](https://user-images.githubusercontent.com/5262628/65512252-24e88b00-ded9-11e9-8653-7f6654ddc64b.png)

**Describe the solution you'd like**
Remove usage of profile.prestashop.com and add an upload field to send a custom image and add a way for module developers to replace the way to retrieve employee avatar by their own implementation.

**Describe alternatives you've considered**
Keep usage of profile.prestashop.com as default implementation but allow module developers to replace it by their own implementation easier.
Currently it require some override to Employee ObjectModel to change behavior of function getImage()
https://github.com/PrestaShop/PrestaShop/blob/10825700128e838a87d91f524d6c529c56a816a4/classes/Employee.php#L609

**Additional context**
On a PrestaShop instance with multiple employee who share same computer, they must open dropdown of employee avatar to see who is currently logged. (Or use different browser...)
By default there are no way to difference who is logged as there are anymore theme variation by employee and process to use a custom avatar is weird.
![employee-dropdown](https://user-images.githubusercontent.com/5262628/65514958-a7277e00-dede-11e9-9409-f1c0399e7d8b.png)

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by ghost** [comment]
Wow @Matt75, that's the kind of feature request I like, clean, complete, lots of context, and some alternatives 👍 

We talked about it yesterday within the team, this avatar is also the only way to identify who answered to a customer in the customer service block in the new Orders page.

I totally agree with you, this is a great idea!


Thanks!

**Comment by ttoine** [comment]
could be interesting to support gravatar, too, like many other cms and web applications.
Thanks @Matt75, +1

**Comment by toutantic** [comment]
PrestaShop the open source project should reduce the number of dependencies on prestashop.com (managed by PrestaShop the company).
I recommend, by default, to remove the call to profile.prestashop.com.
But make sure there is a hook if anyone wants to add a custom profile management module.

**Comment by Progi1984** [comment]
Fixed by #20207
