### ISSUE TITLE
Problems with ps_categoryproducts v.1.0.4 ps_viewedproduct v1.2.1

### ISSUE THREAD

**Issue by DRFrank89** [PrestaShop/PrestaShop#15684]
Hi,
I state that I read **all the proposed solutions** with those who in the past had the same problem as me.

I have two official prestashop modules installed: Products in the same category (**ps_categoryproducts v.1.0.4**) and Block products seen (**ps_viewedproduct v1.2.1**).

Both modules show me the name and price of the **first product only**, the subsequent products have only the image.

Apparently they have fixed the bug with the latest versions I installed, although when I have the Prestashop cache active, the problem recurs.

I have a Prestashop store in **Italian**.

I hope someone can help me, thanks.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22
MySQL version: 5.6.45-log

**Comment by khouloudbelguith** [comment]
Hi @DRFrank89,

I tried with PS1.7.6.1 fresh install & it is OK.
I attached a screen record
https://drive.google.com/file/d/1XFkwj5GC4lhe-GkbDiil_pwp65esCdym/view

Thanks!

**Comment by DRFrank89** [comment]
First of all, thanks for the quick reply @khouloudbelguith khouloudbelguith

So we learned that the modules are not bugged, but it is a problem related to my prestashop.
Activating the debug mode and clicking on any product (having both modules mentioned above), I see several lines of errors (I have attached the screens to the message).

If I uninstall the modules and click on a product (always in debug mode), no error appears.

If it can be useful, as a team I have installed
"warehouse" Version 4.2.2
Designed by IQIT COMMERCE



![error ps_categoryproducts](https://user-images.githubusercontent.com/55789019/65693648-eee00e00-e074-11e9-9cb7-4298bf134dbe.jpg)
![error ps_categoryproducts-2](https://user-images.githubusercontent.com/55789019/65693674-f7384900-e074-11e9-84f9-d31c8e9a9f29.jpg)
![error ps_categoryproducts-3](https://user-images.githubusercontent.com/55789019/65693679-fa333980-e074-11e9-9654-933e59b1b44b.jpg)

**Comment by khouloudbelguith** [comment]
@DRFrank89, when using the default theme => it is OK in my case.
Have you tried to switch to the theme by default & check if the issue occurs?

Thanks!

**Comment by DRFrank89** [comment]
Testing with the default theme, the two modules work.

By activating debug mode, however, it always finds an error relating to the modules (at least as regards the beginning of the error string).
![error ps_categoryproducts-theme-default](https://user-images.githubusercontent.com/55789019/65700611-3b7d1680-e080-11e9-9f68-b71ca7e2474a.jpg)

**Comment by khouloudbelguith** [comment]
@DRFrank89, this exception is provided by your theme
>Undefined index: iqitTheme

Thanks to Check the issue with your theme author and feedback.

**Comment by khouloudbelguith** [comment]
Hi @DRFrank89,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Bonobomagno** [comment]
> Testing with the default theme, the two modules work.
> 
> By activating debug mode, however, it always finds an error relating to the modules (at least as regards the beginning of the error string).
> ![error ps_categoryproducts-theme-default](https://user-images.githubusercontent.com/55789019/65700611-3b7d1680-e080-11e9-9f68-b71ca7e2474a.jpg)

Actually the only working solution is to change the miniature /product.tpl template, to include(yep, copy past) the product-miniatures.tpl part

**Comment by HartLarsson** [comment]
for me no debug errors, with PS 1.7.6.7 php 7.2 and latest modules.
But With Warehouse theme, only the first product have the description and the price while the others are blank:

![image](https://user-images.githubusercontent.com/16102074/91662716-87cca400-eae4-11ea-8eda-32e11bc656be.png)

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,


As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by HartLarsson** [comment]
> Hi @HartLarsson,
> 
> As it's not the default theme, provided by Prestashop, we can't do anything with this.
> You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
> Thanks!

I did and this is the answer

![image](https://user-images.githubusercontent.com/16102074/91729820-654e8f80-eba5-11ea-8b47-5e8b75ac2075.png)

There is probably a bad cache management but i dont' know if is in the modules or how the theme use them

**Comment by matks** [comment]
@HartLarsson Unfortunately "modules dont use cache properly" is way too vague to allow any bugfixing to happen

I dont think it's your job to report this issue. PrestaShop is an open source project. If there is an issue for some themes, it must be reported by ... theme developers 😄  we cant find it all. Everybody must put some energy into the project to push it forward. We will be happy to help if provided, by the theme developer, by something we can work on. "Module does not use cache properly" is not helpful.

**Comment by HartLarsson** [comment]
> @HartLarsson Unfortunately "modules dont use cache properly" is way too vague to allow any bugfixing to happen
> 
> I dont think it's your job to report this issue. PrestaShop is an open source project. If there is an issue for some themes, it must be reported by ... theme developers 😄 we cant find it all. Everybody must put some energy into the project to push it forward. We will be happy to help if provided, by the theme developer, by something we can work on. "Module does not use cache properly" is not helpful.

i agree with you, and i don't really know how to solve the problem except make both modules not use cache system at all.

**Comment by 01Kuzma** [comment]
@HartLarsson have you found a workaround for this?

**Comment by SharmPRO** [comment]
@HartLarsson any news?

I find same problem PS 1.7.8.3 PHP 7.4 ...
