### ISSUE TITLE
Missing vendor/ folder in .gitignore for native modules

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15687]
**Describe the bug**
A lot of native modules such as https://github.com/PrestaShop/ps_wirepayment or https://github.com/PrestaShop/welcome/blob/master/.gitignore do not gitignore the vendor folder. Consequently after a `composer install` the git status of the repo shows unstaged composer files.

**To Reproduce**
1. Git clone https://github.com/PrestaShop/welcome
2. Run `composer install`
3. Run `git status`, you see unstaged files that should not be displayed

**Solution**
Update all the .gitignore files

**Comment by matks** [comment]
Found by @marionf

**Comment by khouloudbelguith** [comment]
Same issue
![image](https://user-images.githubusercontent.com/16067358/65608559-57ac8500-dfa6-11e9-898e-9928ba868b59.png)

Thanks!

**Comment by PierreRambaud** [comment]
I'm not qualifying this in Bug, since it doesn't break anything. Updating the .gitignore should be an improvement.

**Comment by Progi1984** [comment]
@matks  I think we can close this issue as I add .gitignore all modules for the support of PHP 8.0/8.1.

**Comment by matks** [comment]
@Progi1984 thank you for the nice work
