### ISSUE TITLE
MemCache - Can't select Caching System (All are disabled)

### ISSUE THREAD

**Issue by levothanhhong** [PrestaShop/PrestaShop#15681]
**Describe the bug**
VPS Server detail:
OS: Centos 7 64bit
PS version: 1.7.6.1
Xampp fo Linux version: 7.2.22 / PHP 7.2.22
Cache System: i'm used command 'yum install memcached' to install cache system
when i check with command 'service memcached status' -> running (-l 127.0.0.1 U 0)/port: 11211

**To Reproduce**
1. Go to ' Performances'
2. Scroll down to 'Caching'
2. Use Cache 'Yes'
4. See issue

**Screenshots**
![52323723-6118bb00-29de-11e9-90f0-e3e61afe538e](https://user-images.githubusercontent.com/32972703/65569127-a21e0980-df86-11e9-8e7a-be656c2bddff.png)
i'm tried add server with default select (IP: 127.0.0.1 port: 11211 weght: 1) and received failed result
![image](https://user-images.githubusercontent.com/32972703/65569363-8bc47d80-df87-11e9-94a9-3b094f83abfa.png)
**Additional information**
PrestaShop version: 1.7.6.1
PHP version:  7.2.22

**Comment by khouloudbelguith** [comment]
Hi @levothanhhong,

I did not manage to reproduce the issue with PrestaShop v1.7.6.1.
I followed those links to install Memcached
https://www.itzgeek.com/how-tos/linux/debian/how-to-install-memcached-on-debian-9.html
https://serversforhackers.com/c/installing-php-7-with-memcached
![image](https://user-images.githubusercontent.com/16067358/65582978-48adde80-df76-11e9-9a67-8de829787979.png)

And it is well working
I attached a screen record
https://drive.google.com/file/d/1tpE77I-6zw1JlIRZUwm7niyvK3llXwr_/view
Thanks to check & feedback.

**Comment by levothanhhong** [comment]
Hi @khouloudbelguith 
Thanks for responding, it seems that this is not a issue of Prestashop
I don't install memcache**d** extension for lampp on CentOS
Thanks & best regards.

**Comment by khouloudbelguith** [comment]
@levothanhhong, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
