### ISSUE TITLE
Apache module detection in latest version (1.7.6.1) 1x7

### ISSUE THREAD

**Issue by AxxusWhoami** [PrestaShop/PrestaShop#15680]
**Describe the bug**

**To Reproduce**
1. Go to 'Advance configuration > Webservices'
4. Do not detect Apache module mod_auth_basic and doesnt work authentication. I try with another version on the same server with same configurations and its works.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @AxxusWhoami,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15385
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15385
