### ISSUE TITLE
tag cellspacing don't work

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#15699]

**Comment by photinia73** [comment]
I formated table with tag cellspacing. In the BO is OK, but in the FO any effect ((
![image](https://user-images.githubusercontent.com/50954519/65637248-8a796c00-dfec-11e9-93cd-76464c30f398.png)
and FO
![image](https://user-images.githubusercontent.com/50954519/65637284-9b29e200-dfec-11e9-972b-4366c7f5d157.png)
no any space between rows

**Comment by photinia73** [comment]
Find. Work with border-collapse: collapse | separate | inherit
Please close

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
