### ISSUE TITLE
Change link for all images

### ISSUE THREAD

**Issue by Miestre** [PrestaShop/PrestaShop#15696]
Hello
i used a theme for a new site, but the product images do not load.
where i can change the link for all product images?

![image](https://user-images.githubusercontent.com/55487556/65612365-0bfcda00-dfac-11e9-9989-79074f9a52df.png)

**Additional information**
PrestaShop version: 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Miestre,

Can you please try to navigate to the BO => Design => Images Settings => Click on the "Regenerate thumbnails" button, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/65612729-af4def00-dfac-11e9-843d-b5aa065095ca.png)

**Comment by Miestre** [comment]
after some time gives me gateway time out, i have 5000 products:

![image](https://user-images.githubusercontent.com/55487556/65613858-86c6f480-dfae-11e9-8a6f-5c32953859f0.png)

**Comment by Miestre** [comment]
now the site don´t load

**Comment by khouloudbelguith** [comment]
@Miestre, it is a Gateway timeout.
Try to select a type of images & & regenerate this type.
Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by Miestre** [comment]
i can´t acess the BO and i cant see the .htacess file

**Comment by khouloudbelguith** [comment]
@Miestre,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Miestre,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
