### ISSUE TITLE
Error 500 in guest checkout

### ISSUE THREAD

**Issue by andreareyoga** [PrestaShop/PrestaShop#15709]
Hello,
I've found an annoying problem in my prestashop website, and I can't find anything in the web that brings me close to a solution...

In my website ( www.reyoga.it/shop/ ), When a user wants to use the "Guest checkout", I have an error 500 that blocks me to to everything.
The funny thing is that, if I enable debug mode to see what's wrong... everything works fine!

It's literally driving me crazy, and I'm losing some customer for this... did anyone experienced the same bug and know how to solve this?

**To Reproduce**
1. Go to www.reyoga.it/shop
2. Add a product to the cart
3. go to checkout
4. in checkout, insert name and email, without insert any passowrd (guest checkout)
5. click continue and... there you go!

PrestaShop version: 1.7.5.1

Thanks to anyone who will help me!

**Comment by khouloudbelguith** [comment]
Hi @andreareyoga,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by andreareyoga** [comment]
Hello, It seems that it was a server error that was fixed by my hosting, now it does not happen anymore.
I'll close the topic for now.

**Comment by khouloudbelguith** [comment]
@andreareyoga, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
