### ISSUE TITLE
psaddonsconnect Module Upgrade action fails

### ISSUE THREAD

**Issue by metineren** [PrestaShop/PrestaShop#15700]
**Describe the bug**
psaddonsconnect Module Upgrade action fails

**To Reproduce**
1. Go to 'Module Manager > Updates'
2. Click on 'Upgrade psaddonsconnect (Tips and Updates module) Module '
3. See error

**Screenshots**
<img src="https://i.imgur.com/KKnkzQQ.png">

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @metineren,

Could you please try to connect to the Addons Market place, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/65674835-1dde8b80-e045-11e9-90c3-64db6bc36501.png)

Thanks!

**Comment by metineren** [comment]
Hi again @khouloudbelguith 
I connected Addons marketplace, the problem continues.
Module response is "Error sent by Addons. You may be not allowed to download this module."

**Comment by khouloudbelguith** [comment]
@metineren, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & `psaddonsconnect` v2.0.0.
https://drive.google.com/file/d/1erF3jvjt36JEZsEzbcqXMGV9mJXVUhYn/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Quetzacoalt91** [comment]
Hi there,

Does the issue still occurs today? We can get this error when the API is down or its calls have been disabled in the core.

On my side, the module on a shop running PS 1.7.6.0 was successfully upgraded:

![image](https://user-images.githubusercontent.com/6768917/66562776-3f1a9e00-eb54-11e9-9bdb-3953f0cedc2e.png)

**Comment by khouloudbelguith** [comment]
@Quetzacoalt91, thanks, but same issue here with PS1.7.6.1.
https://drive.google.com/file/d/1Kjs5WW9FEVa1rYxdFH2eyh6Nwu5OG962/view
I tried with this module
[psaddonsconnect.zip](https://github.com/PrestaShop/PrestaShop/files/3712134/psaddonsconnect.zip)

Thanks!

**Comment by DanDBX** [comment]
Any updates?

**Comment by marionf** [comment]
This module is not part of the open source project, so I close the issue
