### ISSUE TITLE
Improvement: each column template of grid should wrapped in a Twig block

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#15704]
**Is your feature request related to a problem? Please describe.**
Twig inheritance system works by overriding the defined `block`(s) of templates we extend.
We can already override the rendering of a Column at Shop, Grid or even Column level, but what if we want to re-use and complete the content of the original Column template ?

We can't because - sadly - we have forgotten to wrap template of each column type template in a Twig block.

**Describe the solution you'd like**

Wrap each template of `src/PrestaShopBundle/Resources/views/Common/Grid` folder with meaningful block.

Ex:

### before

```twig
{# data.html.twig #}
{{ record[column.options.field] }}
```

### after

```twig
{# data.html.twig #}
{% block column_type_content %}
{{ record[column.options.field] }}
{% endblock %}
```

> This is a Backward Compatible proposal.

**Comment by mickaelandrieu** [comment]
I will complete the issue later, thanks for your understanding !

**Comment by matks** [comment]
👀

**Comment by mickaelandrieu** [comment]
Issue completed !

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team
