### ISSUE TITLE
Shop alway redirect to old domain - how to change domain of shop

### ISSUE THREAD

**Issue by levothanhhong** [PrestaShop/PrestaShop#15705]
_**Describe the bug**_
Currently my old domain is disabled,
I have reconfigured a new domain for shop
**And when access to shop by new domain (both Back Office and Front Office), shop alway redirect to old domain and ... opps!!**

_**Additional information**_
PrestaShop version: 1.7.6.1
PHP version: 7.2.22
VPS server: CentOS 7

**Comment by khouloudbelguith** [comment]
Hi @levothanhhong,

Could you please navigate to the BO => Shop Parameters => Traffic & SEO page => Set shop URL section & try to change the Shop domain
![image](https://user-images.githubusercontent.com/16067358/65677635-e0c8c800-e049-11e9-896e-d14de6c00c65.png)

Thanks!

**Comment by levothanhhong** [comment]
Hi @khouloudbelguith 
Currently my old domain is disabled,
So, i can't access to shop (both Back Office and Front Office), because it alway redirect to old domain.

Thanks & best regards.

**Comment by khouloudbelguith** [comment]
@levothanhhong, you need to navigate to your Database, search for the table Prefix_shop_url & change all your settings
![image](https://user-images.githubusercontent.com/16067358/65678580-79137c80-e04b-11e9-83cd-3575689295f4.png)

Thanks!

**Comment by levothanhhong** [comment]
Yeah!! thanks @khouloudbelguith 
The issue has been resolved,
Best regards.

**Comment by khouloudbelguith** [comment]
@levothanhhong, Great!
Feel free to open a new one when needed.

Thanks!
