### ISSUE TITLE
"Add a product" and "Add a new discount" buttons disappear after editing a product in view order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15716]
**Describe the bug**

**To Reproduce**
1. Go to Order > View an order with "awaiting bankwire payment" status
2. Click on Edit a product and change the quantity
3. Note that there are 2 buttons: Add a product" and "Add a new discount"
4. Click on Update
5. See "Add a product" and "Add a new discount" buttons disappeared
6. Refresh the page and you will see these buttons again

**Screenshots**
![Captura1](https://user-images.githubusercontent.com/13449658/65700503-1ab4c100-e080-11e9-9b9f-852f1ec8061b.JPG)
![Captura2](https://user-images.githubusercontent.com/13449658/65700502-1a1c2a80-e080-11e9-9063-354de4139bec.JPG)
![Captura3](https://user-images.githubusercontent.com/13449658/65700501-1a1c2a80-e080-11e9-8942-e06eab2f8c6b.JPG)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by marionf** [comment]
@MatShir Maybe this can be fixed during the migration of view order page

**Comment by colinegin** [comment]
@TristanLDD @MatShir @marionf can you confirm this issue is fixed with the new order page design ?

**Comment by marionf** [comment]
Yes, it's fixed :+1:

**Comment by colinegin** [comment]
Great !!
