### ISSUE TITLE
Missing fields in migrated add/edit customer page when B2B mode is enabled

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15726]
**Describe the bug**
When B2B mode is enabled, fields should be added in add/edit customer page:

* Company
* Siret
* APE
* Website
* Outstanding amount
* Maximum payment delay (in days)
* Risk level

Also in customer lisiting, company should be displayed.

**To Reproduce**

1. Go to Shop parameters > Customer settings & enable B2B
1. Go to Customers > Customers and add/edit a customer

**Screenshots**
Legacy pages version 1.7.5.2

![capture d'écran!UNITO-UNDERSCORE!2022](https://user-images.githubusercontent.com/13449658/65756705-e68bdf80-e115-11e9-98ba-5d1298b778e1.png)

![capture d'écran!UNITO-UNDERSCORE!2021](https://user-images.githubusercontent.com/13449658/65756714-ea1f6680-e115-11e9-8807-7fedaacf02bf.png)

Migrated pages version 1.7.6.1

![capture d'écran!UNITO-UNDERSCORE!2024](https://user-images.githubusercontent.com/13449658/65756673-d2e07900-e115-11e9-9f59-8e9caa0f1422.png)

![capture d'écran!UNITO-UNDERSCORE!2023](https://user-images.githubusercontent.com/13449658/65756693-dffd6800-e115-11e9-865f-ff7dfccca937.png)

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by marionf** [comment]
@matks FYI

**Comment by matks** [comment]
@marionf I cant reproduce. I'm on 1.7.6.x branch, I enable B2B mode from Configure > Adv Parameters > Customers page, and I see the fields for B2B customers, and listing has the company column:
<img width="1116" alt="Capture d’écran 2019-10-07 à 17 42 50" src="https://user-images.githubusercontent.com/3830050/66326803-ee276180-e929-11e9-93de-04518ef1e530.png">
<img width="922" alt="Capture d’écran 2019-10-07 à 17 43 00" src="https://user-images.githubusercontent.com/3830050/66326817-f384ac00-e929-11e9-8bae-c22bbbf6cf83.png">

**Comment by marionf** [comment]
Me neither, looking at the screenshots that I posted, I activated the multi-store.
I guess I had to activate B2B for a store and display the customer page with another store selected :sweat:
