### ISSUE TITLE
Rebuild search index URL and cron

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#15725]
**Describe the bug**
Rebuild search index URL can not be called from a cron, as it requires a login

**To Reproduce**
1. Open rebuild search index URL that appears at `Shop parameters - Search` in a private tab (without login) or in a cron
2. Error. It requires BO login. Index is not rebuilt.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0.
With PS1.7.5.2 => It is OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15855
