### ISSUE TITLE
BO - Border "Your profile" too small in some languages

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#15734]
**Describe the bug**
In some languages (Russian, Arabic...), in BO User Menu, the border of the "Your Profile" label is too small fort the text (or the text is too long for the border ?).

The border length should be based on the length of the text, and not fixed.

**To Reproduce**
Choose Arabic or Russian Language
Open the User Menu
"Your profile" is over the border

**Screenshots**
![Capture d’écran de 2019-09-27 14-02-14](https://user-images.githubusercontent.com/55688534/65771574-cd485a80-e138-11e9-9a43-705211d65a4c.png)

**Additional information**
PrestaShop version: 1.7.7.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I have the same issue with PS1.7.6.1 & the develop branch.
![image](https://user-images.githubusercontent.com/16067358/65895983-397ac680-e3a4-11e9-9b2b-a34556b090d3.png)
With PS1.7.5.2, it is OK
![image](https://user-images.githubusercontent.com/16067358/65896006-4ac3d300-e3a4-11e9-9271-09b945637e77.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by ghost** [comment]
Does it only happen with RTL?

**Comment by Robin-Fischer-PS** [comment]
Not only, it also appears with Russian (and probably some other languages too).

**Comment by Robin-Fischer-PS** [comment]
I re-open this PR since this behavioiur appears again on 1.7.7.x branch (see example in Russian and Arabic) : 
![profile too large arabic](https://user-images.githubusercontent.com/55688534/76454231-927b6b80-63d4-11ea-9486-bd7fe9c661f7.png)
![profile too large russian](https://user-images.githubusercontent.com/55688534/76454233-93ac9880-63d4-11ea-872b-5aa343f220a8.png)

**Comment by Progi1984** [comment]
Fixed by #18515
