### ISSUE TITLE
On Backorder (paid) Status when stock is >0

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#15746]
After a customer did place an order, the status of the order is changing a few hours later to "On Backorder (paid)" - even if there are still more items available in stock.

I am getting this error after upgrading to 1.7.6 and still with 1.7.6.1 is the same error, it is not happening on all products. And it did not happen before that upgrade to 1.7.6

After checking to find a pattern, i did realise that it seems to be connected maybe with the paypal module, i am using also braintree from that module and when the order is having status (Awaiting for Braintree Validation) - it seems that, as soon as the validation has been confirmed it is being changed then to the wrong status.

I did not make any changes to the status.

But, since long time i can read that there should be a new paypal and also seperate braintree module in the prestashop marketplace which should have been installed already, but, i cannot find that modules. Paypal Support told me that these modules are not developed by them, just by prestashop developers. So, maybe this problem is connected to the missing update of the module(s)?

Here is the message:

_> 
![screenshot-error-onbackorder](https://user-images.githubusercontent.com/31710761/65861587-d588db80-e36c-11e9-8a13-ac5867da88d7.JPG)
Starting July 1st, 2019, Braintree payment solution will be separated from PayPal module. There will be 2 different modules: PayPal official (v5.x) and Braintree official (v1.x). Both modules will be available for free on Prestashop Addons.
> Braintree users: you’ll be required to install the new module (Braintree official (v1.x). It will be possible to transfer quickly your current module configurations from the current version of the PayPal module to the new Braintree module without any impact to your business. New exciting features will come soon!.
> PayPal payment solution: No changes & no impacts on your business. You can simply update the module to latest version (PayPal official (v5.x)) for getting new features & bug fixes._

**Comment by khouloudbelguith** [comment]
Hi @tom75,

In your screenshot provided, the available quantity = 0
![image](https://user-images.githubusercontent.com/16067358/65873408-edfff280-e37a-11e9-88f8-5d652fdbe59e.png)

Thanks to check the quantity of your product again.

**Comment by decom-media** [comment]
Yes, but, this is after the purchase – this is the current stock, which is NOW 0, as it was the last item, but, as you can see it has been purchased one time and after that the stock is 0 (otherwise it would be then -1)

**Comment by khouloudbelguith** [comment]
@tom75, but your main issue is:
>After a customer did place an order, the status of the order is changing a few hours later to "On Backorder (paid)" - even if there are still more items available in stock.

The On Backorder status will be displayed if the stock available of your product is  < = 0 which is your case.

Thanks!

**Comment by decom-media** [comment]
I think we are not talking about the same, as there is no need to have something on backorder when it is already paid by the customer.

Again:


·         Product A is having 1 item on stock.

·         Customer C is buying and paying for that item

·         Customer C gets the order confirmation and is happy

·         Customer C is getting then a few hours later an email which is telling him/her that the product is not in stock and has to be reordered --> customer is no longer happy and calling me why he can order and pay something and it is showing “on stock” and then he is getting the message that it is out of stock.

·         I have to change then the status manually back to another status


è Why does the customer need to get the information that the product is out of stock AFTER he purchased one which was on stock and just AFTER he did make the purchase there is no longer any item on stock – also, this information is showing in the customers order status, but, the order of this customer is not having any problem, as there is one item – the one which has been bought by the customer – and just AFTER this customer there is no other one able to buy it again, as it is out of stock then

Hope it is now clear?

**Comment by khouloudbelguith** [comment]
@tom75, THanks for these clarifications.
This issue occurs only when using this module https://addons.prestashop.com/fr/paiement-carte-wallet/1748-paypal-officiel.html?

Thanks!

**Comment by decom-media** [comment]
It looks like there is maybe the connection, as this module is including also “Braintree” which is the creditcard payment option of paypal – and they are doing a payment with additional verification, which is happening after the payment, but, in different time frames later on. And as it was working fine before the upgrade of prestashop 1.7.6 I can tell that normally the second status on a purchase when someone was using this module for payment was then the confirmation of the payment (Braintree) and everything was fine, but, since that update it seems to address the wrong status information when updating.

Also, I realized that finally today there is an update available from that paypal module – should I update the module now – but, I would need to wait then until someone is using that module again to see if it was working?!

**Comment by khouloudbelguith** [comment]
@tom75, this module is not provided by the PrestaShop team core.
So, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/fr/contactez-nous?id_product=1748
Thanks!
