### ISSUE TITLE
Wrong taxes for customers from other countries

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#15740]
I installed clean fresh PrestaShop 1.7.6.1. I set Germany as default country of the store.
No additional setting was made expect carriers. The prices were tax included in the PrestaShop settings. No "European VAT number" module were installed (Note: the module takes no effect after installing).

Then I created regular customer account with a few addresses: German, UK, Mexican and Russian.

I added any product into the cart and just starting things going wrong. 
1. When I select German address, the prices were tax included - that's correct. 
2. When I select UK, Mexican or Russian address, the all prices (products and shipping) were tax excluded - it's no correct. Additionally, these prices were marked with "Tax included" label which is completely wrong.

I double checked all PrestaShop settings, taxes, countries, customers groups etc. Everything is correct.

I also tested on PS 1.7.5.2 with the same result. Did anyone noticed this issue and report as bug?

**Additional information**
PrestaShop version:  1.7.6.1
PHP version: 7.2.2

**Comment by khouloudbelguith** [comment]
Hi @Caleydon,

In the Address created for the UK, for example, the VAT number is empty or not?
![image](https://user-images.githubusercontent.com/16067358/65971850-c6835580-e460-11e9-940c-0e855f0d81d6.png)
In fact, if it is empty => Taxes are not applied
If it is not empty => the prices will be displayed with Tax excluded & the Label is correct.
I attached a screen record
https://drive.google.com/file/d/13LFrN7k1rHex9-Un_kI-yW0Cz4Q3uVML/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Caleydon,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
