### ISSUE TITLE
Problem with module ps_newproducts Prestashop 1.7.1.6

### ISSUE THREAD

**Issue by Vitron1778** [PrestaShop/PrestaShop#15749]
**Describe the bug**
After creating new products they're showing only before updateing page (press F5), after that new products dont show.

**To Reproduce**
1. Go to 'Create new product'
2. Click on 'Save'
3. Check on the main page 'It works'
4. Press F5
5. New products become unvisible.

**Screenshots**
1. With Proucts - ![image](https://user-images.githubusercontent.com/55977913/65865324-e9880980-e37b-11e9-980c-28b1aa8da053.png)
2. Without Products - 
![image](https://user-images.githubusercontent.com/55977913/65865371-f9075280-e37b-11e9-8b1c-1c8e8f765088.png)
3. With Debug Mode - 
![image](https://user-images.githubusercontent.com/55977913/65866755-0cb3b880-e37e-11e9-8e2a-7bc86c748043.png)

**Additional information**
PrestaShop version: 1.7.1.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Vitron1778,

You have an issue with the ps_featuredproducts module.
What is the exact version of the module ps_featuredproducts did you use?
This module is overridden by your theme?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Vitron1778,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
