### ISSUE TITLE
Incorrect final price for a specific price on a combination

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#15767]
**Describe the bug**
For a simple product, with a price of 100 € and a specific price of 80 € for quantity 3, the final price on the cart for a quantity 3 is 3 * 80 = 240 €. This is what expected.

But, for a product with combinations, with a price of 0 €, combinations with a price of 100 € and a specific price of 80 € for quantity 3 (apply to all comabinations), the final price on the cart is not 3 * 80 = 240 € but (100 + 80) * 3 = 540 €.

I've follow the instructions of #12363 "In the BO =>Shop Parameters => Product Settings Page, in the Products (general) section, Select "Combinations" for the "Quantity discounts based on" option, save, check & feedback."" but that didn't solve the problem.

**To Reproduce**
1. Create a product with a price of 0 €
2. Enable "Product with combinations"
3. Click on the "Combinations" tab
4. Create few combinations, with a price of 100 €
5. Click on the "Prices" tab
6. Click on the "Add a specific price" button: quantity: 3 ; product price: 80
7. Open the product on the front office. Set quantity 3. Add the product on the cart. The final price is 540 € instead of 240 €.

**Screenshots**
Product price:
![image](https://user-images.githubusercontent.com/22885898/65943569-10a01300-e430-11e9-8e57-63465f842cf1.png)

Combinations:
![image](https://user-images.githubusercontent.com/22885898/65943592-1c8bd500-e430-11e9-8682-2755a81957b6.png)

Specific price:
![image](https://user-images.githubusercontent.com/22885898/65943618-29a8c400-e430-11e9-9424-38efda5ddab1.png)

Front-office product:
![image](https://user-images.githubusercontent.com/22885898/65943635-34fbef80-e430-11e9-85f0-2da6043259de.png)

Quantity 1 on the cart:
![image](https://user-images.githubusercontent.com/22885898/65943650-434a0b80-e430-11e9-9776-badbb9c0c34d.png)

Quantity 3 on the cart:
![image](https://user-images.githubusercontent.com/22885898/65943665-4cd37380-e430-11e9-86ca-cdd31e7b7c41.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @yannicka,

The Product price (tax excl.): This is where you can set an arbitrary price, independent of calculations and regular prices. This will override the retail price.
So, you have retrail price =0 if the quantity < 3 but if the quantity > = 3 the Retail price will be = 80
![image](https://user-images.githubusercontent.com/16067358/65947810-e7cc4d80-e430-11e9-9fce-5d19ee24c23c.png)
In your case, you have an impact on price = 100 for the combinations
If the combination is supposed to have an impact on the product's original price(retrail price), fill the field that appears with the value of that impact (e.g. "-2" if the price should be decreased by 2).
In your case impact =100 => so the price will be increased by 100.
![image](https://user-images.githubusercontent.com/16067358/65948021-55787980-e431-11e9-986e-84dbf7bb74d3.png)

For more details you can follow our documentation: http://doc.prestashop.com/display/PS17/Managing+Products
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by yannicka** [comment]
Thanks, but I don't understand what I can do to solve my problem.

How can I get a price of 240 € for a quantity 3+ of my combinations? I need to have a product price of 0 € and a combination price of "+100 €".

**Comment by khouloudbelguith** [comment]
@yannicka, you can make a discount amount = 20 Tax excluded.
![image](https://user-images.githubusercontent.com/16067358/65950770-a2ab1a00-e436-11e9-936f-444061a62729.png)
![image](https://user-images.githubusercontent.com/16067358/65950788-ae96dc00-e436-11e9-8a7b-e428654b83dc.png)

Thanks!

**Comment by yannicka** [comment]
Thank you, it works.

However, this means that I cannot have three "fixed" values (product price 0€, combination price +100€ and specific price 80€), I must necessarily have a "relative" value for the specific price (-20€)?

**Comment by khouloudbelguith** [comment]
@yannicka, you can make discounts on each combination.

Thanks!
