### ISSUE TITLE
[1.7.6.1] Failed to authenticate on SMTP server with username using 2 possible authenticators

### ISSUE THREAD

**Issue by arafatx** [PrestaShop/PrestaShop#15763]
Configure SMTP mail always failed both sending message and testing.

When we send test email. The following message appear:

[screenshot]
![image](https://user-images.githubusercontent.com/4420157/65905922-1aa42080-e3f4-11e9-9c94-76bf02a972d5.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.23

The mail SMTP configuration for the hosting has been tested and works with many mail applications such as Gmail app for iOS, android and Microsoft Outlook.  I can provide various info as the mail server is owned by myself.

**Comment by khouloudbelguith** [comment]
Hi @arafatx,

I did not manage to reproduce the issue with PS1.7.6.1.
It is well working.
https://drive.google.com/file/d/1s2Oo1ifa4TtnN8IifSCInJkjB6CK-pp1/view
The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check again & feedback.

**Comment by arafatx** [comment]
Is there a log that I can view generated from prestashop about this error?

I got this in the server mail log:

login authenticator failed for 535 Incorrect authentication data (set_id=)

Using telnet, the server responded and echoed the mail banner without any problem. Username and password definitely has no problem. my server accept both ssl and tls. 465 and 587. Firewall were disabled to test the mail response.

I'm not sure what else I can make the server compatible with prestashop SMTP. I  can put the SMTP configuration at the other client software with no error (receive and sending mail has no problem. the mail log doesn't generate any error).  By the way, it's true that, the gmail less secure can be used with no problem. and I think there's something or some rules that prestashop doesn't like about my server and i'm looking to find out what is that..

**Comment by arafatx** [comment]
Oh no. it was problem with Google Chrome. Using another browser works (tested with opera). Maybe the autofill function in google chrome prevented the correct data to be saved.

**Comment by khouloudbelguith** [comment]
@arafatx, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by go-sudo** [comment]
Hi 
Same thing for me, works with Firefox and not chrome 
Regards

**Comment by elmanu13** [comment]
Problem for me on firefox and chrome....impossible to understand !

**Comment by pavankumarat** [comment]
So, if you are using microsoft exchange

Azure active directory admin center -> Properties -> Manage security defaults -> Disable should solve

**Comment by PacificiShop** [comment]
Hi, this happens to me:
with chrome in anonymous browsing
the password field does not show the encrypted password (the field is empty )

<img width="1218" alt="Schermata 2022-01-25 alle 12 50 57" src="https://user-images.githubusercontent.com/98394445/150972092-ddb79839-2064-4665-828d-86121135cad6.png">

It works properly
Idem with Firefox
<img width="1218" alt="Schermata 2022-01-25 alle 12 48 06" src="https://user-images.githubusercontent.com/98394445/150971649-4ea12258-6cfc-426c-abba-4242654902a7.png">

With Chrome in normal browsing mode, the password field shows black dots

<img width="1207" alt="Schermata 2022-01-25 alle 12 53 25" src="https://user-images.githubusercontent.com/98394445/150972489-e28d11b5-d9e8-4741-98d3-dccaf4c1b8ee.png">

In this case if I enter the password of the email account and then I save, the system shows this error

<img width="1209" alt="Schermata 2022-01-25 alle 13 17 56" src="https://user-images.githubusercontent.com/98394445/150975614-b2b0d368-8f82-4f6e-93cb-0fc68f4edce9.png">

"Failed to authenticate on SMTP server with username" customers@pacificicorrado.it "using 2 possible authenticators"

if i enter the password without saving the mail is sent correctly

<img width="1037" alt="Schermata 2022-01-25 alle 13 17 06" src="https://user-images.githubusercontent.com/98394445/150975790-32b4e63c-6713-4740-b4ba-d35387cd1790.png">

Thanks for any reply.
PC

**Comment by Ronald72a** [comment]
Hello,
The problem is that the module "email" use the password that Chrome indicate (saved password), not the one who is "saved in module email", so when the password who is saved in chrome is different then the one your want to use you got an error, that's why when you got to Firefox (or another browser then your usual) who don't indicate the password you don't have this trouble !

to work around the problem, use another browser than the usual one to validate the email configuration, then stop testing in your usual browser

Have a nice day
Ronald

**Comment by go-sudo** [comment]
I would like to add, one information, the problem recurs for some webhost provider 
I don't know if it's because of the SSD or something else.
