### ISSUE TITLE
total_paid_real wrong value (doubled)

### ISSUE THREAD

**Issue by espacious** [PrestaShop/PrestaShop#15769]
**Describe the bug**

Prestashop 1.7.5.1

A customer places an order of 1.000,00 RON, on orders page total is ok.
Under customers the field Sales (total sales of that customer) is 2.000,00
So it's doubled.

The only thing i found is this paypal warning in order details:

Product pricing has been modified as your rounding settings aren't compliant with PayPal. To avoid automatic rounding to customers for PayPal payments, please update your rounding settings. Read more.

I dont know if it's related.

**To Reproduce**
1. Place an order of eg. 1.000,00 RON
2. See Sales field in Customers (will be doubled eg. 2.000,00)

**Screenshots**
https://imgur.com/a/T0FgqAT

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment]
Hi @espacious,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & Paypal v5.0.0.
https://drive.google.com/file/d/1IybZJivrEM2RetQG_g0_MTosDrJHZpvD/view
Paypal is not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by espacious** [comment]
Im on version 1.7.5.1 i know it's not the latest but i cant upgrade right now.
This has nothing to do with paypal i think. I also found other posts that mention total_price_paid_real has wrong value in database, but no solution. And also in my database there are values that are 2x too high.
It happenes no mather which payment method is selected.

**Comment by khouloudbelguith** [comment]
@espacious, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by espacious** [comment]
- Server setup and config:

It's an Plesk Onyx v17.8.11_build1708180301.19 os_CentOS 7
with Apache and PHP Version 7.1.32

- debug mode report show no errors
- PHP error log snow no errors
- apache log no errors
- javascript console log no errors

Infact the values in DB table "total_paid_real" are wrong so i think is's normal to have nothing in error logs.

May be the currency? We use RON (eg. 1.987,00 - see the dot and the comma)

**Comment by khouloudbelguith** [comment]
@espacious, thanks!
Waiting for your feedback.

**Comment by espacious** [comment]
Any new info on this? I edited my post, please take a look.

**Comment by khouloudbelguith** [comment]
@espacious, what the currency by default in your shop?

Thanks!

**Comment by espacious** [comment]
Default currency is RON.
But we have also EUR enabled because paypal does not support EUR. But i think it does not matter.

<a href="http://shrani.si/?g/4c/1XEKKTM5/991a5ac3-759e-46ec-89e3-.png"><img src="http://shrani.si/t/g/4c/1XEKKTM5/991a5ac3-759e-46ec-89e3-.jpg" style="border: 0px;" alt="Shrani.si"/></a>

I saw you can't recproduce the error but you tested on 1.7.6.1 im on 1.7.5.1 ...

Thanks to you khouloudbelguith

**Comment by khouloudbelguith** [comment]
@espacious, in my case, when RON is the currency by default, the Paypal doesn't support this currency.
But, if the EUR, is the currency by default, it is OK PayPal.
![image](https://user-images.githubusercontent.com/16067358/66393336-8b3dd500-e9d2-11e9-88c0-8914a8842a8d.png)

Thanks!

**Comment by espacious** [comment]
Yes this is right. Paypal does not support RON so i edited paypal module to convert before sending the total amount. Do you think this is the problem? I doubt becouse we have another site, almost exact copy which does not use paypal and the Customer totals are still wrong. I can provide paypal code modification. It happens also with COD.

**Comment by khouloudbelguith** [comment]
@espacious, using the COD module.
I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.1.
PS1.7.5.1: https://drive.google.com/file/d/1YcsAwFQPDK-kIsQXr1kdbN5zCMaC48F3/view
PS1.7.6.1: https://drive.google.com/file/d/12Lecmkpa5oDbXloj0E1tu9czJ3U_yABA/view

Thanks!

**Comment by espacious** [comment]
Ok i see. will try to investigate further what is the cause.

**Comment by khouloudbelguith** [comment]
@espacious, thanks!
Waiting for your feedback.

**Comment by espacious** [comment]
Hi khouloudbelguith, finaly i found the problem. Seems the module Custom order reference (v1.2.0 - by PrestaCraft) wa causing the problem. After disabling it everything is ok. So i removed this module from all sites and i implemented this override instead of the module:
https://www.prestashop.com/forums/topic/518497-change-the-order-reference-to-number-reference/?tab=comments#comment-3020921

Thanks to all.

**Comment by khouloudbelguith** [comment]
@espacious, Great!
Feel free to open a new one when needed.

Thanks!
