### ISSUE TITLE
Can't access back office

### ISSUE THREAD

**Issue by xandenet** [PrestaShop/PrestaShop#15775]
**Describe the bug**
I have Prestashop 1.7.6 installed and it worked but suddenly I can't access my back office. There is a blank page if I try it. I can only access the back office if debug mode is turned on.
Already disabled all non-native modules, and continues the error, until ontme worked fine did nothing different for this to happen, already deleted the cms cache, and nothing appears in the error log ...

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @xandenet, 

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP, check and feedback.

**Comment by xandenet** [comment]
Thanks @khouloudbelguith , it worked downgrading PHP to 7.2 and deleting the cache as per your suggestion

**Comment by khouloudbelguith** [comment]
@xandenet, thanks for your feedback.
Fell free to open a new one when needed.

Thanks!
