### ISSUE TITLE
Report request

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15786]
**Is your feature request related to a problem? Please describe.**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Would like a one time report built that looks at all accounts that have had 2  or more opportunities lost against it in the last 2 years.  

**Describe the solution you'd like**
>A clear and concise description of what you want to happen.

Just a spreadsheet or report outlining which accounts have had 2 lost opportunities against it in last 2 years.

**Describe alternatives you've considered**
>A clear and concise description of any alternative solutions or features you've considered.

I was thinking of building a custom query in sf.com but not sure i could build it (due to the complexity).

**Additional context**
>Add any other context or screenshots about the feature request here.

Please contact me with any questions.

thanks

Mike Denomme

**Comment by khouloudbelguith** [comment]
Hi @mdenomme,

Thanks for your report.
So, you need to create a report to get all accounts that they lost 2 or more opportunities.
What is this exact opportunity?

Thanks!

**Comment by ghost** [comment]
All opportunities last 2 years

**Comment by khouloudbelguith** [comment]
@mdenomme, opportunity to make an order?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mdenomme,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
