### ISSUE TITLE
BO: Price per unit set to 0 after saving product

### ISSUE THREAD

**Issue by ruinobreferreira** [PrestaShop/PrestaShop#15784]
Whenever you edit a product "Price per unit (tax excl.)" is set to 0.

**To Reproduce**

1. Go to Catalog > Products.

2. Click on the "Pricing" tab
   1. Make sure you have "Price per unit (tax excl.)" set and different from 0.

3. Click on "Save"

4. Refresh the page and the field "Price per unit (tax excl.)" is now 0.000000

**Additional information**

PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment]
Duplicate of #15785
