### ISSUE TITLE
Guest user name product comment module issue

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15797]
Hi,
Latest productcomments module show "By **Deleted account**" instead of provided guest name in FO. In BO guest user name is OK.

![Bez-nazwy-3](https://user-images.githubusercontent.com/8243273/66053487-b5a31480-e532-11e9-95a2-88cdf3868795.png)

Sorry if duplicated.

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Thanks for your report.
I have the same behavior with PS1.7.6.1 & The product comment module v4.0.0.
![image](https://user-images.githubusercontent.com/16067358/66057929-6a3c3680-e531-11e9-8923-cb01db550feb.png)
Ping @PrestaShop/prestashop-product-team what do you think? can we improve this?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @PrestaShark, do you mean that it appears when a customer account is not deleted? Or is the account deleted but the customer name is still available for the merchant in his/her back office?

**Comment by ghost** [comment]
Comment from guest user (no customer, no logged in)
His name from the modal input fielsd is in database. Its only FO module bug

**Comment by LouiseBonnard** [comment]
Alright, thanks @PrestaShark. @jolelievre, can it be fixed easily?

**Comment by jolelievre** [comment]
I guess it's fixable This text is only supposed to appear when a user/guest is removed from database We will need to search for the reason and fix this in the next version

@PrestaShark the guest is still in database, but does the id still matches with `product_comment.id_guest`? And does this bug occur on every guests or just a few ones?

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

We are waiting for your feedback.
Any news?

Thanks!

**Comment by colinegin** [comment]
ping @PrestaShark, did you see @jolelievre's comment ? We need your input to be sure how to fix it !

**Comment by SimonGrn** [comment]
@colinegin @marionf this isse has not been properly qualified, and we never got back from the OP. This issue should be closed ?
(only asking you because it's in an EPIC)

**Comment by sarahdib** [comment]
@PrestaShark 
I didn't reproduce : https://drive.google.com/file/d/14lHabjgcz_fjUu_ulgL0sDERbOqF0lfP/view

There is a new version of the module, could you try with this new version ?

I close this issue feel free to open a new one if you still have this issue with the new version.

Thank you
