### ISSUE TITLE
Remove a field from the employee creation form

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#15792]
**Describe the bug**
A little bit of cleanup in the fields of the employee creation form. Please note that if the field must disappear, the associated behavior must be removed too.

**Additional information**
PrestaShop version: 1.7.x

**Comment by khouloudbelguith** [comment]
Hi @ttoine,

What the exact field that should be removed?
![image](https://user-images.githubusercontent.com/16067358/66032790-f0d72080-e4fd-11e9-9dde-63652f267c58.png)

Thanks!

**Comment by matthieu-rolland** [comment]
So what field should be removed? I'm not sure I understand this issue 🤔

**Comment by matthieu-rolland** [comment]
1/ The newsletter field must be deleted
2/ All features linked to this field should be disabled and properly removed.
