### ISSUE TITLE
Prestashop Checkuot module

### ISSUE THREAD

**Issue by Diraco** [PrestaShop/PrestaShop#15802]
![checkout](https://user-images.githubusercontent.com/56108464/66106929-56d7ac80-e5bf-11e9-8751-9f469437989d.png)
<!--

the pay-in log-in button does not appear in the form

**Comment by khouloudbelguith** [comment]
Hi @Diraco,

Could you please provide us a clear description of your exact issue & steps to reproduce it in a new comment?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Diraco,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
