### ISSUE TITLE
Abandoned cart even after checkout

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#15806]
Hello the Prestashop community,

I have a question. I am setting up a cart recovery tool for a client but she has noticed me several times that abandoned cart of the same amount as orders made resurfaced ... it could be disturbing if customers receive a mail from raise when we ordered two days before ... Do you know where this problem can come from? You can check the screen to see what is happening. 

It looks like when a customer is login to check order status, the cart comes back?

Is there a way to fixed it ?

![image](https://user-images.githubusercontent.com/39828779/66108657-5b05c900-e5c3-11e9-9491-72b96bd95cde.png)

PrestaShop version: 1.7.61
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Dupflo,

Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9589?
In fact, Shopping cart is created automatically after login.
Thanks to check & feedback.

**Comment by Dupflo** [comment]
Yes I have this issue also but I have another issue that an abandoned cart of the same amount of the order passed previously (186,50€) is reproduced. Like if the ordered cart is recreated after the customer is coming back

**Comment by khouloudbelguith** [comment]
@Dupflo, I did not manage to reproduce the issue with PS1.7.6.1.
In your BO => Shop Parameters => Customer Settings page => Re-display cart at login is enabled?
![image](https://user-images.githubusercontent.com/16067358/66126271-653abe00-e5e9-11e9-83e1-5871ab803bc1.png)

Thanks!

**Comment by Dupflo** [comment]
This is not enable this is why I don't understand

**Comment by khouloudbelguith** [comment]
@Dupflo, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Dupflo** [comment]
![image](https://user-images.githubusercontent.com/39828779/66128607-76d29480-e5ee-11e9-889e-80ebeed2c420.png)

**Comment by Dupflo** [comment]
![image](https://user-images.githubusercontent.com/39828779/66128690-ac777d80-e5ee-11e9-92a9-6080ea1acb7f.png)

**Comment by Dupflo** [comment]
What you can do is 
-Create an order
-Disconnect and go back to your login (it should create a 0€ cart)
-Go like if you would like to check your order status as a customer
-Look if your last order cart comes back in the BO

**Comment by khouloudbelguith** [comment]
@Dupflo, di you use the module MailChimp for example?

Thanks!

**Comment by Dupflo** [comment]
Mailjet !
And for my abandonned cart I will use this https://addons.prestashop.com/fr/remarketing-paniers-abandonnes/19584-smart-cart-reminder-relance-panier-intelligent.html

**Comment by khouloudbelguith** [comment]
@Dupflo, what is the exact name of this module?

Thanks!

**Comment by Dupflo** [comment]
Module Smart Cart Reminder / Relance Panier Intelligent and Mail Jet Email Newsletter but I do not believe it came from a module

**Comment by khouloudbelguith** [comment]
@Dupflo, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Dupflo** [comment]
I just figure out what happen.. I try to reproduce and what happen is that the button "reorder" is placed on a zone to facilitate the "click" and the same cart came from it 

So I will closed the issue that is not really an issue

**Comment by khouloudbelguith** [comment]
@Dupflo, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
