### ISSUE TITLE
New products not visible in catalog mode

### ISSUE THREAD

**Issue by Ferry74** [PrestaShop/PrestaShop#15803]
The new products block is not visible on the frontpage when shop is in catalog mode.
Changing to maintenance mode with maintenance IP and catalog disabled will show the new products block. I think maintenance mode is independent of catalog mode, but I didn't test that.

**To Reproduce**
1. Go to 'Shop Parameters -> General -> Maintenance'
2. Click on 'Enable shop : YES' -> Save
3. Go to 'Shop Parameters -> Products -> Products (general)'
4. Click on 'Catalog mode : YES' -> Save
5. Go to 'View my shop'
6. See error: No 'New products' (nieuwe producten) block is visible
       See screenshot: Without NewProducts.png

7. Go to 'Shop Parameters -> General -> Maintenance'
8. Click on 'Enable shop : NO' -> Save
9. Go to 'Shop Parameters -> Products -> Products (general)'
10. Click on 'Catalog mode : NO' -> Save
3. Go to 'View my shop'
4. See error: 'New products' (nieuwe producten) block is visible
       See screenshot: With NewProducts.png

**Screenshots**
Without NewProducts.png and With NewProducts.png

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.23
Current theme in use: classic 

![With NewProducts](https://user-images.githubusercontent.com/56106951/66107130-c77ec900-e5bf-11e9-8484-57b299951292.png)
![Without NewProducts](https://user-images.githubusercontent.com/56106951/66107132-c77ec900-e5bf-11e9-9126-f1a04ace5f7d.png)

**Comment by khouloudbelguith** [comment]
Hi @alowncat,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & the `newproducts` module v1.0.1.
If I enable the Catalog mode, this block is not displayed in the FO.
The module is well installed & enabled.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by NeOMakinG** [comment]
@matks that looks mergeable

**Comment by Progi1984** [comment]
Fixed in PrestaShop/ps_newproducts#2
