### ISSUE TITLE
hookDisplayAdminProductsExtra($params) doesn't pass $params

### ISSUE THREAD

**Issue by jonasburneika** [PrestaShop/PrestaShop#15800]
**Describe the bug**
In this hook I can't get any $params data. And if we try to use the variable it crashes with error code 500. I tried to get an error log on dev mode, but it doesn't show any. Also tried to get `$id_product` by `Tools::getValue('id_product')` but this returns `null`

**Steps to reproduce the behavior:**
1. Create a module with hookDisplayAdminProductsExtra($params)
2. Try to var_dump($params)
3. $id_product = Tools::getValue('id_product');

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.22

Tried with custom module and belvg_samplemodule

**Comment by khouloudbelguith** [comment]
Hi @jonasburneika,

I tried with PS1.7.5.2 & PS1.7.6.1 & the BlockYoutubeVideos module.
I tried with `var_dump($id_product);` & it is well displayed
![image](https://user-images.githubusercontent.com/16067358/66118563-fce2e100-e5d6-11e9-9bf5-67e0e974ddaa.png)
Could you please enable debug mode when error 500 s displayed? is there any exception displayed?

Thanks!

**Comment by jonasburneika** [comment]
Hi, @khouloudbelguith 
I have enabled debug mode, but it doesn't show anything, just blank white page. Can you try to var_dump $params variable? Because today I found out that, `var_dump($params['id_product'])` works fine, but `var_dump($params)` crashes.

my method:
`public function hookDisplayAdminProductsExtra($params) {

        echo __FILE__.':'. __LINE__.'<br/ >';echo "<pre>";var_dump($params);echo"</pre>";

        $id_product = Tools::getValue('id_product');

        Context::getContext()->smarty->assign(array(

            'productID' => $id_product

        ));

        return $this->display(__FILE__, '/views/templates/admin/hook/displayadminproductsextra.tpl');
    }`

**Comment by khouloudbelguith** [comment]
@jonasburneika, with PS1.7.6.1, I tried with `var_dump` & it is OK
![image](https://user-images.githubusercontent.com/16067358/66122768-d2962100-e5e0-11e9-92f8-ff227ac0d377.png)
Thanks!

**Comment by jonasburneika** [comment]
@khouloudbelguith can you try with PS1.7.5.2? Maybe it's just in the PS1.7.5.2 version.

**Comment by khouloudbelguith** [comment]
@jonasburneika, it is Ok with PS1.7.5.2 also
![image](https://user-images.githubusercontent.com/16067358/66129842-f19caf00-e5f0-11e9-81f5-7efb76917443.png)

Thanks!

**Comment by jonasburneika** [comment]
Hi, @khouloudbelguith thanks for your time.

**Comment by khouloudbelguith** [comment]
@jonasburneika, you are welcome!
Feel free to open a new one when needed.

Thanks!
