### ISSUE TITLE
Change wording in FO when there is specific price by quantity

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15817]
To create discount by quantity:
1. Edit a product (Catalog > Products)
2. Click on price tab
3. Click on add a specific price
4.  Fill "Starting at" and "Apply a discount of" fields
5. See the product in FO

- [x] Replace "Discount" by "Unit discount"
=> Displayed when _Display discounted price_ is set to _No_ in Shop parameters > Products
- [x] Replace "Price" by "Unit price"
=> Displayed when _Display discounted price_ is set to _Yes_ in Shop parameters > Products
- [x] Remove "Up to" 

![capture d'écran_2053](https://user-images.githubusercontent.com/13449658/66192015-dcc32880-e68f-11e9-9b28-da4209a199e0.png)

![capture d'écran_2052](https://user-images.githubusercontent.com/13449658/66192016-dcc32880-e68f-11e9-8ec4-30abd91c3ca7.png)

**Comment by LouiseBonnard** [comment]
Hi @marionf, it suits me fine except for the third option. I would leave the amount without the wording before, so no 'at least' nor 'up to' but only '€3.00'.
