### ISSUE TITLE
[ORDER PAGE] Order Actions (update status, view invoice, delivery slip) - 1/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15818]
Part of the order page migration and redesign project.

**User Storie**

As a merchant, when I check an order, I need to be able to change the order status and to view the invoice & the delivery slip

**Detailed specification**
Specs on the repo prestashop-specs
[Order Action Specs](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#i-action-panel
)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16022
