### ISSUE TITLE
Backoffice header template differ from one page to another

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#15813]
1. Go to main backoffice page
2. Check the html template of the header menu : list items UL/LI
3. Go to catalog-->stock page
4. Check the html template of the header menu : div items

It's a problem for some modules that add an access on the header, using DIV (for example, "easy login as customer" module).
The display will be different on the pages and can even cause functionnal problems.

Why the header bloc receive a different template ? It should be the same in all pages.

PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

are you comparing the Dashboard page & the Stocks page?
The Dashboard page is not migrated to Symfony but the Stocks page is migrated to Symfony.

Thanks!

**Comment by elmanu13** [comment]
Dashboard page was an example, the problem is on many other pages.
Can I have the list of the symfony migrated pages somewhere ?

**Comment by khouloudbelguith** [comment]
@elmanu13, We are working hard to migrate all pages to Symfony.
You can follow our Project "Symfony migration"
https://github.com/PrestaShop/PrestaShop/projects/3
In the PS1.7.6.0, we made this:
Symfony Migration - new pages

- Catalog > Categories
- Catalog > Categories > Add new / edit category
- Catalog > Brand & Suppliers > Brands > Add new brand
- Catalog > Brand & Suppliers > Suppliers (will be hidden)
- Catalog > Brand & Suppliers > Brands
- Catalog > Brand & Suppliers > Brands > Add new brand address
- Catalog > Brand & Suppliers > Brands > View brand
- International > Localization > Currencies
- International > Localization > Currencies > Add new / edit currency
- International > Localization > Languages
- International > Localization > Languages > Add new / edit language
- International > Taxes > Taxes
- International > Taxes > Taxes > Add new / edit tax
- Design > Theme & Logo
- Design > Theme & Logo > Add new theme
- Design > Theme & Logo > Choose layouts
- Design > Pages
- Design > Pages > Add new / edit page
- Design > Pages > Add new / edit page category
- Advanced Parameters > Team > Employees
- Advanced Parameters > Team > Employees > Profiles
- Advanced Parameters > Team > Employees > Profiles > Add new profile
- Advanced Parameters > Team > Employees > Add new employee
- Advanced Parameters > Webservice > Add new webservice key
- Shop parameters >Traffic & SEO > SEO & URL > Add new / edit page
- Shop parameters > Contact > Contacts
- Shop parameters > Contact > Contacts > Add new / edit contact
- Customers > Customers
- Customers > Customers > Add new / edit customer
- Customers > Customers > View customer

Thanks!

**Comment by elmanu13** [comment]
Perfect answer, thanks !
So I guess you can close it as it's not really an issue ;-)

Good work !

**Comment by khouloudbelguith** [comment]
@elmanu13, Yes!
Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
