### ISSUE TITLE
virus on chrome

### ISSUE THREAD

**Issue by w2019fgatfield** [PrestaShop/PrestaShop#15812]
**Describe the bug**
this bug is when you have used google chrome for a long time and lots of weird adds start popping up.
**To Reproduce**
1. Go to "https://www.opera.com/download"
2. Click on 'Download Opera'
4.Go to settings and uninstall google chrome
**Screenshots**

![Capture](https://user-images.githubusercontent.com/56039030/66140541-36791380-e5fa-11e9-9a90-6f99736b7a55.PNG)

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @w2019fgatfield,

Please be aware that this bug tracker should be used to report issues only related to PrestaShop.

Thanks for your understanding!

**Comment by w2019fgatfield** [comment]
would you be able to help me start of on coding.
thanks
w2019fgatfield@
