### ISSUE TITLE
[ORDER PAGE] Customer block - 4/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15821]
Part of the order page migration and redesign project.

**User Story**

As a merchant, when I check an order, I need to be able to know who made the order.

**Detailed specification**
Specs on the repo prestashop-specs
[Customer Panel Specs](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#ii-customer-panel)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15955
