### ISSUE TITLE
[ORDER PAGE] Payments Tab - 10/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15827]
Part of the order page migration and redesign project.

**User Story**

As a merchant, when I check an order, I need to be able to see all the payment interaction.

**Detailed specification**
Specs on the repo prestashop-specs
[Payment Tab specs
](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#v-tabs-panel)

**Comment by sarjon** [comment]
Part of this issue, we should remove details from Payment block (marked as red https://prnt.sc/phbcbb), is that correct @LouiseBonnard ? :)

**Comment by LouiseBonnard** [comment]
It's correct, @sarjon, thank you. @colinegin said that it might be relevant to add a hook instead, for modules to be able to push some information.
