### ISSUE TITLE
[ORDER PAGE] Status Tab Order - 5/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15822]
Part of the order page migration and redesign project.

**User Story**

As a merchant, when I check an order, I need to be able to see the status history with the editor of the status changes.

**Detailed specification**
Specs on the repo prestashop-specs
[Status tab](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#v-tabs-panel)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16022
