### ISSUE TITLE
[ORDER PAGE] Documents Tab Order - 6/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15823]
Part of the order page migration and redesign project.

**User Story**

As a merchant, when I check an order, I need to be able to see all the documents generated by the order.

**Detailed specification**
Specs on the repo prestashop-specs
[Documents tab
](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#v-tabs-panel)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16046
