### ISSUE TITLE
Bad discount amount when specific price by quantity is configured tax excl and prices are displayed tax incl in FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15835]
- [ ] **Case 1**

Taxes are enabled in International > Taxes
_Display discounted price_ is set to _No_ in Shop parameters > Products
Product price tax excl: 10€
VAT: 23%
Product price tax incl: 12,30€
Now, I add a specific price for which **I change the initial price tax excl for 8€ from 10 units**.
I change _Apply a discount of_ for 0€ **tax excl**

<p><span class="image-wrap" style=""><a id="65126_thumb" href="http://forge.prestashop.com/secure/attachment/65126/65126_3.png" title="3.png" file-preview-type="image" file-preview-id="65126" file-preview-title="3.png"><img src="http://forge.prestashop.com/secure/thumbnail/65126/_thumb_65126.png" style="border: 0px solid black" /></a></span></p>

The amount of the discount and the "you save" are not good

![capture d'écran_2057](https://user-images.githubusercontent.com/13449658/66213572-55da7400-e6c0-11e9-8ab9-00737e831046.png)

_Unit discount_ should be 2,46€ instead of 4,30€
_You save_ should be 24,60€ instead of 43€

Set _Display discounted price_ is set to _Yes_ in Shop parameters > Products

![capture d'écran_2056](https://user-images.githubusercontent.com/13449658/66213306-c0d77b00-e6bf-11e9-8b65-7b42bcabb729.png)

_Unit price_ should be 9,84€ instead of 8,00€
_You save_ should be 24,60€ instead of 43€

- [ ] **Case 2**

Product price tax excl: 12.90€
VAT: 20%
Product price tax incl: 15,48€

Create a specific price with:
Initial price: 11,35€ tax excl
Discount: 2€ tax excl

_Display discounted price_ is set to _No_ in Shop parameters > Products

The amount of the discount and the "you save" are not good

![capture d'écran_2060](https://user-images.githubusercontent.com/13449658/66220387-34cc5000-e6cd-11e9-9757-239f55acf85c.png)

_Unit discount_ should be 4,26€ (1,86+2,40) instead of 5,80€
_You save_ should be 12,78€ instead of 17,39€

_Display discounted price_ is set to _Yes_ in Shop parameters > Products

![capture d'écran_2061](https://user-images.githubusercontent.com/13449658/66220467-5b8a8680-e6cd-11e9-867c-9a743c06ba26.png)

_Unit price_ should be 11,22€ (15,48-4,26) instead of 9,68€
_You save_ should be 12,78€ instead of 17,39€

**Comment by marionf** [comment]
Fixed by #15549

**Comment by levyn** [comment]
The current problem has been solved here - #16138
