### ISSUE TITLE
Create a repository to stock localization files

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15838]
**Is your feature request related to a problem?**
As it works now, the files related to the localization packs are stocked in the core and it is not ideal.

**How it works currently?**
Currently, they are .xml files on a server and they have not been updated since their creation for the 1.7.0 version. After that, it is the back office that reads a file in the server to retrieve the list of all available localization packs.

**Describe the solution you'd like:**
Extract them from the core et put them in a dedicated repository will make more sense. It would allow localization data to be much more editable (and they need to be updated often) since they will be separated from releases.

**Comment by eternoendless** [comment]
Done! https://github.com/PrestaShop/LocalizationFiles

New changes should be done there, then pulled on the API server, then updated in PrestaShop.

Note: updated packages are only available for 1.7+
