### ISSUE TITLE
Installation asks for inexistent file anything.html

### ISSUE THREAD

**Issue by lpvm** [PrestaShop/PrestaShop#15836]
When installing Prestashop, after the creation of the tables, there's an error

```
Unable to open primary script: 
public/install/sandbox/anything.php (No such file or directory)

```
**To Reproduce**
1. When installing via web access, `Create file parameters` is stricken through, and green
2. `Create database tables` is in red, installation progress at 12%
3. An error occurred during installation...
4. ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "prestashop:schema:update-without-foreign","message" => "An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known"]

![20191004_prestashop_error](https://user-images.githubusercontent.com/7320067/66214262-486dbb80-e6b9-11e9-928d-776e1d22b52d.png)
.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22
Connectio to MariaDB 10.4.6 via unix socket at /var/run/mysql/mysql.sock

**Comment by khouloudbelguith** [comment]
Hi @lpvm,

This failure comes from an IntlException which is an exception thrown when dealing with Intl issues. Meaning: internationalization. So here are 2 things you can check:

- does your failing server has the right intl extension enabled for Prestashop?
- what languages and currencies are enabled on your failing server? maybe there's one not enabled on your stage server, and that would explain the difference

Thanks!

**Comment by lpvm** [comment]
Hi @khouloudbelguith,

Regarding the first question, the package `php72-intl-7.2.22` is installed.
The locale was `C`.  I've installed an `UTF-8` locale and the error is gone.
Thank you.

**Comment by khouloudbelguith** [comment]
Hi @lpvm,

Thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
