### ISSUE TITLE
Direct access to customer's view missing from Customers list row

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15831]
**Describe the bug**
In Customers > Customers

Missing behavior following the "Customers" page migration.
In 1.7.5.2. when clicking on a row, it opens the customer's view page.
In 17.6.1 it doesn't work anymore.

Workaround:
It is still possible to access the customer's view via the actions dropdown on the right side of the rows. But it takes 2 clicks instead of one #productivity. 

**To Reproduce**
1. Go to Customers > Customers
2. Click on a customer row 
4. See error -> Nothing happens

**Screenshots**
https://drive.google.com/file/d/1CTavM3hvYwZCDtWWHiWqamU14kvJVkUL/view?usp=sharing

[UPDATED OCT 8 19]
**Specs for all grids**
https://github.com/PrestaShop/prestashop-specs/pull/71/files

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @samuel-pires,

Same issue with PS1.7.6.1.
I think it is a regression, we should add the regression label, what do you think?

Thanks!

**Comment by ghost** [comment]
Apparently this behavior is missing from many tables in migrated pages (not enough detailed specs).

@matks do you want us to regroup all the impacted tables and create an EPIC?

@PrestaShop/prestashop-core-developers do we consider this issue as a regression? To me it is., and it should be fixed before releasing a new version.

**Comment by PierreRambaud** [comment]
@samuel-pires at least for me, it's regression and must be fixed!

**Comment by ghost** [comment]
> @samuel-pires at least for me, it's regression and must be fixed!

Alright, I'll identify all impacted tables and define the missing behavior in the specs. So we can fix it.
Will add the issues in the 1.7.6 project.

**Comment by ghost** [comment]
Hi @TristanLDD & @jolelievre, 
I checked the pre-migration behaviors on the grids identified by Jo.
Here are the details. 

How to read:
Defaut button -> the action displayed in the button on the right side of the row.
Options -> actions available in the dropdown (or the 3 dots) in the right side of the row.
Row -> action available by clicking on the row, as it was before migration.

Here are the specs : https://github.com/PrestaShop/prestashop-specs/pull/71/files

cheers

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15859
