### ISSUE TITLE
Mail Templates generation not using twig files from custom email theme (Modern theme is always used instead)

### ISSUE THREAD

**Issue by jaxtheking** [PrestaShop/PrestaShop#15843]
**Describe the bug**
When re-generating mail templates using a custom email theme, the generated emails do not contain the modifications implemented in the custom theme.

**To Reproduce**
1. Create a custom theme by duplicating /mails/themes/modern/ and calling it (say) /mails/themes/mytheme/
2. Edit /mails/themes/modern/components/footer.html.twig and add the word 'MODERN' anywhere
3. Edit /mails/themes/mytheme/components/footer.html.twig and add the word 'MYTHEME' anywhere
4. Go to Improve > Design > Email Theme in the BO and set mytheme as the default theme
5. Regenerate emails either in the BO or by command: 
` php bin/console prestashop:mail:generate mytheme en-GB -o`
6. In either case, any generated email (mine are in /mails/gb/) will contain the word 'MODERN' and not 'MYTHEME' as expected
7. Bonus: if you rename the modern theme's folder to (say) '_modern', the generator will error out complaining the Modern theme was not found.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jaxtheking,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0 following your steps.
But there is something missing in your case, you just duplicated the modern folder & you didn't make necessary changes.
In fact, if you check all files, for example, mytheme/components/layout.html.twig
you can find
`{% include '@MailThemes/modern/components/header.html.twig' %}`
This is incorrect, you are including all templates of the modern theme.
All files are incorrect.
So, if you change, all these files, any generated email will contain the word 'MYTHEME'.
Also, if you try to regenerate emails after renaming the modern folder => it will be OK.
I tried with this & it is OK
[mytheme.zip](https://github.com/PrestaShop/PrestaShop/files/3696427/mytheme.zip)

Thanks to check & feedback.

**Comment by jaxtheking** [comment]
I can't believe I was such a rookie - however I was not expecting internal references to the theme's name.
Thank you so much for your help; it finally works!

**Comment by khouloudbelguith** [comment]
@jaxtheking, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
