### ISSUE TITLE
Order reference should be generated by hashids lib (or similar)

### ISSUE THREAD

**Issue by ip413** [PrestaShop/PrestaShop#15842]
**Problem**
When shop is using short order reference, example: `Tools::passwdGen(4, 'NUMERIC');` (3456, 6534, 2236) there is possibility of generating previously used numbers in a row. 
This is uneffective, and dangerous when most random order references are taken, because loop from PaymentModule.php could run many times
`do {
$reference = Order::generateReference();
} while (Order::getByReference($reference)->count());` or even **infinitely** when all random possibilities were taken. This problem is not handled in the code at the moment, so client won't be able to place an order.

Long order reference is not useful for many clients, when they call the shop and trying to identify the order which they are talking about. 

**Solution**
To generate order reference [hashids for php](https://hashids.org/php/) library (or similar) should be used.

Such solution is much safer, generates unique id, and could as short as possible and as safe as possible, without revealing real order id.

So for the orders with id's: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10... etc. we could generate references like:
3, 7, 5, 1, 3, 7, 8, 4, 7, 24, 76, 78, 23, 67, or, 453, 4563, 7342, 7455, 4656, 65456... such references are much easier to use for clients and shop staff.

**Proof**
I'm talking about numbers (reference) from second column, on image
![image](https://user-images.githubusercontent.com/6553887/66223764-8d531b80-e6d4-11e9-8b54-927300ad3354.png)

**Comment by khouloudbelguith** [comment]
Hi @ip413,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by Hlavtox** [comment]
How does this fix the possibility of the order reference being already used?

The references are almost always a short lettered/numeric string, does it matter how we generate it?

Ping @kpodemski

**Comment by kpodemski** [comment]
@Hlavtox I would close this one :)

**Comment by Hlavtox** [comment]
@kpodemski Closed, however, we should tackle the possibility of generating a duplicate reference. I have a loop on my stores that re-runs it when that happens.
