### ISSUE TITLE
Can't access to Module Manager and Homepage settings, error with Argument 3 passed to LinkBlockRepository::__construct() must be an instance of PrestaShopBundle\Translation\TranslatorComponent

### ISSUE THREAD

**Issue by dawidurus** [PrestaShop/PrestaShop#15846]
Hi!

I installed Prestashop and when I want go to homepage settings or in Module Manager i'm gettings this error:

`Type error: Argument 3 passed to LinkBlockRepository::__construct() must be an instance of PrestaShopBundle\Translation\TranslatorComponent, instance of PrestaShopBundle\Translation\DataCollectorTranslator given, called in /home/telefono/domains/socks-yeah.com/public_html/modules/ps_linklist/ps_linklist.php on line 65`

Anyone can help me?

**Comment by khouloudbelguith** [comment]
Hi @dawidurus,

Could you please try to re-install the `ps_linklist` by removing the folder during the uninstall.
If you can't access to your BO => Module Manager Page, you can rename the folder `ps_linklist` to `ps_linklist_old` in your `Project_Folder/modules/` path then try to install it again.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @dawidurus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by xcephpdev** [comment]
Hi,

I am facing the same issue on the PS 1.7. When remove the directory from the module then backend was start working. But when I try to install that then module showing the same error during installation time. 
How I install that module again.

Regards:
XCE Developer
