### ISSUE TITLE
Wrong subtotal in order confirmation when product is customised

### ISSUE THREAD

**Issue by miographix** [PrestaShop/PrestaShop#15844]
I encountered a problem or bug in the order confirmation shown to the customer after buying a customized product. The subtotal in the first row of a listed product shows "0". Same thing in the order overview in the customer account. Plaese see yellow markers at the screenshots. I use a special module for product customisation but this also happens when the module is deactivated and the customization option is provided over the standard settings of a product. Same thing with classic theme and also in Prestashop 1.7.6.1.

Looks like value $product.total is set wrong in oder-confirmation.tpl if product is customised with product options.

PrestaShop version: 1.7.5.2
PHP version: 7.2
Theme is warehouse 4.2.1. 

![Screenshots_2019-08-28](https://user-images.githubusercontent.com/56174949/66238390-d5376a00-e6f7-11e9-8505-a8e4f038e680.jpg)

**Comment by khouloudbelguith** [comment]
Hi @miographix,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15171 to fix the issue.
Your ticket is a duplicate of #10912
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10912
