### ISSUE TITLE
Update all native modules icons and short descriptions

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15858]
**Is your feature request related to a problem? Please describe.**
Native modules need to be updated with new content and icons - for version 1.7.7!

**Describe the solution you'd like:**
With @colinegin and @PierreRambaud, we agreed on automatizing this update with a script or a cron job. For that, we must have a [Drive](https://drive.google.com/drive/folders/1yzbplZvb0x4rRpa7OZXmXcWhK7OqPpbo?usp=sharing) with a folder for each module containing the updated logo .png - and the updated short description as well?

**Related documentation:**
Refer to this [mapping](https://docs.google.com/spreadsheets/d/1GtbFwElz5N_yvAcGuxvXyjNZv-OOx4tlBHyTI0ACD3Y/edit?usp=sharing) to get the modules' IDs and short descriptions.

**Comment by LouiseBonnard** [comment]
📢 **UPDATE:**

Here is the shared [Drive](https://drive.google.com/drive/folders/1yzbplZvb0x4rRpa7OZXmXcWhK7OqPpbo?usp=sharing) repertory as requested. All modules are there, with the updated icon called _logo.png_. ;-)

**Comment by Julievrz** [comment]
https://github.com/PrestaShop/ps_advertising/pull/15 (Update of Advertising block)

**Comment by Julievrz** [comment]
https://github.com/PrestaShop/statsbestproducts/pull/9 (Update Best Products)

**Comment by Julievrz** [comment]
https://github.com/PrestaShop/ps_brandlist/pull/9 (Update brand list)

**Comment by Julievrz** [comment]
https://github.com/PrestaShop/statsequipment/pull/13 (update browsers and operating system)

**Comment by Julievrz** [comment]
- [x] 1-Click Upgrade 
- [x] Advertising block
- [x] Available quantities
- [x] Banner
- [x] Best brands
- [x] Best categories
- [x] Best customers
- [x] Best suppliers
- [x] Best vouchers
- [x] Best-selling products
- [x] Brand list
- [x] Browsers and operating systems
- [x] Buy Button Lite
- [x] Carrier distribution
- [x] Cash on delivery (COD)
- [x] Catalog evaluation
- [x] Catalog statistics
- [x] Category tree links
- [x] Contact Form
- [x] Contact information
- [x] Cron tasks manager
- [x] Cross-selling
- [x] Currency block
- [x] Custom text blocks
- [x] Customer "Sign in" link
- [x] Customer accounts
- [x] Customer data privacy block
- [x] Customer follow-up
- [x] Customer reassurance
- [x] Dashboard Activity
- [x] Dashboard Goals
- [x] Dashboard Products
- [x] Dashboard Trends
- [x] Data mining for statistics
- [x] Email Templates Manager
- [x] Faceted search
- [x] Favicon Notifications in the Back-office
- [x] Featured products
- [x] Google Analytics
- [x] Google Sitemap
- [x] Image slider
- [x] Language selector block
- [x] Legal Compliance
- [x] Link List
- [x] Mail alerts
- [x] Main menu
- [x] Merchant Expertise
- [x] My Account block
- [x] New products block
- [x] Newsletter
- [x] Newsletter subscription
- [x] NVD3 Charts
- [x] Official GDPR Compliance by PrestaShop (1.7)
- [x] Pages not found
- [x] Payments by check
- [x] PrestaShop Cleaner
- [x] PrestaShop marketplace in your Back office (MBO)
- [x] PrestaShop Security
- [x] Product comments
- [x] Product details
- [x] Product Notification
- [x] Products in the same category
- [x] Registered customer information
- [x] RSS feed block
- [x] RSS products feed
- [x] Sales and orders
- [x] Search bar
- [x] Search engine keywords
- [x] Shop search
- [x] Shopping cart
- [x] Simple HTML table display
- [x] Social media follow links
- [x] Social media share buttons
- [x] Specials block
- [x] Stats Dashboard
- [x] Supplier list
- [x] Theme Customization
- [x] Tips & Updates
- [x] Top-sellers block
- [x] Tracking - Front office
- [x] Viewed products block
- [x] Visitors online
- [x] Visitors origin
- [x] Visits and Visitors
- [x] Watermark
- [x] Welcome
- [x] Wire payment
