### ISSUE TITLE
Carts created in few seconds away and a strange error

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15853]
Hi
from these 2 sites (probably I can see the same from others) I can see that prestashop create for the same customer some carts in few seconds away.
Can you explain me te motive? is it normal or can be fixed to avoid many carts from the same customers?

I report here another problem happens today from 2 sites at the distance of 1 hour:
today they had old customer who placed an order, in both cases in the checkout they complained that they did not have a courier, told him that a courier was not present based on the selections made. The strange thing is that the same error was present in the manual order creation phase of the control panel. At first I thought it was a problem with the addresses but then I realized that they both had in memory a cart with products, created today, so I removed the products from the carts and then readjusted. In this way the couriers are available again.
Given that the tests were made on various computers and that the problem also occurred in the control panel, I believe there is something wrong with storing data in the cart tables, perhaps for past customers who used prestashop 1.6, because these sites have been updated months ago to 1.7.
These two sites had this error one at the 11:00 and the other at 12:00 but it is the first time that they get this type of error, it is very strange

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/66310525-b1993d00-e90c-11e9-9eae-b26c7def4909.png)
![3](https://user-images.githubusercontent.com/653230/66310526-b1993d00-e90c-11e9-858b-f93e8d7899b0.png)

**Additional information**
PrestaShop version: 1.7.5.2 and 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @maofree,

In your BO => Shop Parameters => Order Settings => Disable Reordering option is enabled or disabled?

It could be related to the action Re-order.

Thanks to check & feedback.

**Comment by Maofree** [comment]
Hi
Is it necessary to set on "true" for "Disable Reordering" option ?

![1](https://user-images.githubusercontent.com/653230/66551700-45a31880-eb48-11e9-9b09-55062974ef3b.png)

bye

**Comment by khouloudbelguith** [comment]
@maofree, no it is not necessary, it is just an option.
But, I need some extra details to reproduce the issue, because it is OK in my case.

Thanks!

**Comment by Maofree** [comment]
I can pass to you the access of this site, I haven't extra details

**Comment by khouloudbelguith** [comment]
@maofree, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Maofree** [comment]
in this topic I report 2 errors
for the first one you can see by yourself why the a cart is replicated more than one time
for the second error is an error about cart data

in both cases the server is not a problem and the javascript is not the problem, from those logs you cannot see these type of errors they are in the php files

I passed you the access of the site, if you can and want to give a look

**Comment by khouloudbelguith** [comment]
@maofree, about the first error,
I checked the last 1000 carts, I have only one customer that has this problem of multiplication of carts, is it?

About the second issue, we have similar issues
https://github.com/PrestaShop/PrestaShop/issues/9932
https://github.com/PrestaShop/PrestaShop/issues/9672
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
