### ISSUE TITLE
Translation in English is not possible

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#15850]
Hello,
I have a multi-shop site and I can translate into all languages except English.

1. Go to Translation
2. And choose your theme and English language

After you have the bug :
`error: Catchable Fatal Error: Argument 2 passed to PrestaShopBundle\Translation\Loader\DatabaseTranslationLoader::addLangConstraint() must be an instance of PrestaShopBundle\Entity\Lang, null given, called in /data/www/gti/gti-moondream/ps17/src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php on line 75 and defined`

**Screenshots**
https://zupimages.net/up/19/41/5bk1.jpg
https://zupimages.net/up/19/41/rtiq.jpg

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6

Thank you very much for your help

**Comment by khouloudbelguith** [comment]
Hi @ShaimyWinda,

Could you please navigate to your BO => International => Translations => Add / Update a language section => Update your English language.
![image](https://user-images.githubusercontent.com/16067358/66307014-82320280-e903-11e9-8a46-c87203f703c5.png)

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment]
Hi @khouloudbelguith 

I have a error 500

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith , I managed to add but not to update because they don't offer us
Despite everything, I still have the red error
Error 500 was just a problem on our server

https://zupimages.net/up/19/41/he45.jpg

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, after the release of PS1.7.6.0, we reproduced some regressions related to the translation.
They are fixed in the PS1.7.6.1.
You can follow this [link](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3A1.7.6.0+label%3ARegression+label%3ATranslations+is%3Aclosed+project%3APrestaShop%2FPrestaShop%2F4) for more details.

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment]
Thansk for your answer @khouloudbelguith!
In the link you sent me, I can't find the error I have among the publications. So if I change the version of my Prestashop, the problem will be solved?

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, If you upgrade your version, some regressions will be fixed.
In my case, I did not manage to reproduce the issue with PS1.7.6.0.
https://drive.google.com/file/d/1IxZGESUXdwnC4GojmWrXeYrHzh4LNA8k/view
How did you import the English GB language? from the BO or from the install?

Thanks!

**Comment by ShaimyWinda** [comment]
I don't know exactly.
Let me explain. For a very long time, we were on version 1.5. Last year, an agency put our entire site in version 1.7.4. However, even then, we could not translate into English. 
Then they made a small migration to 1.6.7.0

Thanks @khouloudbelguith !

**Comment by ShaimyWinda** [comment]
Maybe this is the php version? I'm in PHP 5.6
https://github.com/PrestaShop/PrestaShop/issues/15324#issuecomment-527157190
You have the same error

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, no, It is OK with PHP5.6
https://drive.google.com/file/d/1UXJPN_zwjPiUf81EAoxX3FBomOKIg99y/view
Thanks!

**Comment by ShaimyWinda** [comment]
On the video, you are in 1.7.6.1 and not 1.7.6.0

**Comment by ShaimyWinda** [comment]
@khouloudbelguith  On the video, you are in 1.7.6.1 and not 1.7.6.0
https://reccloud.com/fr/u/safkdyb

I dont know why i have this problem

And this comment : #15324 (comment) ? It's the same error 

Thanks so much for your help!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, those errors are reproduced after testing a PR: https://github.com/PrestaShop/PrestaShop/pull/15081 which is still open & not merged yet, so, it doesn't exist in your case.
It is OK with PS1.7.6.0 https://drive.google.com/file/d/15JEX80hegqUf8XwAGrG5Vqo9RKMvelWH/view
What is the exact theme used in your case? it is classic? or moondream?

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith, Both. 
Even if I want to translate the back office it doesn't work.
I also show you that in the other languages, everything works well
https://reccloud.com/fr/u/iy2j9lr

**Comment by ShaimyWinda** [comment]
Hi @khouloudbelguith!
Did you get a look at the video?

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, in your case the `Multistore` context is enabled.
Could you please check if the language GB is enabled in all stores?
If yes, could you please try to select only one shop & try to translate with this language, check & feedback.

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith i tried but nothing ..
https://reccloud.com/fr/u/i7v6bsk

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, thanks for your feedback.
I tried with All shop selected, but it is OK with PS1.7.6.0 & PS1.7.6.1.
https://drive.google.com/file/d/1gvfqe3crbskJJW3pQCOBN2IzNdyrREDz/view
Could you please provide me the credentials of your shop to test it.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ShaimyWinda** [comment]
Thanks!
I just sent you an email @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, I just received the email.
I will check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, can I change the theme used in your case to the Classic theme?

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith Sorry, that's not possible. We are in e-commerce and the site must be up and running 24/7   :/

**Comment by ShaimyWinda** [comment]
But you can see that even if we want to translate the Moondream theme into English, it doesn't work

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, with PS1.7.6.0, we cannot translate a Back office or modules when using a theme other than classic
https://github.com/PrestaShop/PrestaShop/issues/15133 fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/15139
https://github.com/PrestaShop/PrestaShop/issues/14733 fixed with PR: https://github.com/PrestaShop/PrestaShop/pull/14962

They are fixed in the PrestaShop v1.7.6.1.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ShaimyWinda,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
