### ISSUE TITLE
Add missing languages in the right localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15857]
**Is your feature request related to a problem? Please describe.**

As PrestaShop evolved since version 1.7.0, languages have been added but last additions have not been redistributed in the concerned localization packs. Indeed, some languages are available in the International > Translations > Add / Update a language section of the back office (such as Hindi, Malayalam or Bengali) but when you import the Indian localization pack (International > Localization), you can only get Tamil. It does not make sense to search for all the Indian languages available in two different places.

**Describe the solution you'd like:**

While waiting for more flexible handling of the data localization packs contain, let's rearrange what already exists in PrestaShop and put it back at the right place. Regarding the languages, it means several tasks. 

- [x] **China** pack: add Uyghur
- [x] **France** pack: add Breton
- [x] **India** pack: add Hindi, Malayalam, and Bengali
- [x] **Norway** pack: add Nynorsk
- [x] **Philippines** pack: add Tagalog
- [x] **Serbia** pack: add Bosnian, Hungarian, Albanian, Croatian, Slovak, Romanian, and Bulgarian
- [x] **Singapour** pack: add Tamil

**Comment by colinegin** [comment]
@LouiseBonnard are you sure this is a good idea to add breton to the french pack as it is very specific ?

**Comment by LouiseBonnard** [comment]
Breton is already available in the Translations > Add / Update a language section of the back office and since it is somehow part of the French pack, I thought it could be nice to add it as well.

**Comment by colinegin** [comment]
I guess it means that if you install french localization pack, you will have french and breton languages by default available ?

**Comment by eternoendless** [comment]
Yes that's right

**Comment by colinegin** [comment]
To be honest i find it a bit weird, breton is a very very specific & local language. I feel like in 99% of the time you only need french as language, so it will require that people remove the breton language. What do you think @LouiseBonnard ?

**Comment by matks** [comment]
> breton is a very very specific & local language. I feel like in 99% of the time you only need french as language, so it will require that people remove the breton language.
⚠️ 
<img src="https://i.skyrock.net/5767/41125767/pics/3314351488_1_5_EkEyA7id.jpg">

**Comment by matks** [comment]
PR has been approved https://github.com/PrestaShop/PrestaShop/pull/16292 but we can make following your decision 😊
