### ISSUE TITLE
Payment not associated with delivery if delivery is a module 

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#15852]
During installation, payment module are associate with delivery. (table module_carrier)Currently, payment module are not associate with delivery if delivery is a module. If you select this delivery on order page, the payment will not appear.

_Originally posted by @Seleda in https://github.com/PrestaShop/PrestaShop/pull/15799#issuecomment-537946847_

Steps to reproduce the issue:
If you install a delivery module and then install a payment module, the new payment method will not contact that delivery module.

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/66317438-cb8d4c80-e919-11e9-9d1c-eb8237dd87d3.png)
I’ll add this to the debug roadmap.
Thanks!
