### ISSUE TITLE
I try to change the price of a product and I get a red card that says it can't be saved.

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#15862]
Problem after moving my store, from Cloudways to cpanel. In cloudways I didn't have that problem
- * - * -
I try to change the price of a product and I get a red card that says it can't be saved.
Unable to update settings.

Video
https://drive.google.com/file/d/1_yHwcL-8i600A87LStfT_SYj6LS1EaNb/view

- * - * -
Cpanel 82.0.16
Centos 7
Apache
Ngnix (Engintron-Nginx-on-cPanel)
PHP Version: 7.3.10
MySQL Version: 10.3.18-MariaDB
PrestaShop version: 1.7.6.1
Current topic in use: warehouse

**Comment by khouloudbelguith** [comment]
Hi @Marcelozippo,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
Next version PrestaShop 1.7.7. will be compatible with PHP7.3.

For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP, check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Marcelozippo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
