### ISSUE TITLE
PS 1.7.6.1 + Nginx half of the backoffice pages doesn't work

### ISSUE THREAD

**Issue by gbartosz83** [PrestaShop/PrestaShop#15864]
**Describe the bug**
prestashop 1.7.6.1 installed corectly on nginx but then, when I've logged in half of tabs from backoffice can't be loaded, in the browser there is an address of given backoffice page (links contains index.php/sell/ or index.php/improve/ or index.php/configure or index.php/configure or index.php/modules) but server displays main page of the website

the shop is not the main page, it's one of pages something like this: domain.com/shop
I have the ssl enabled but chrome displays warning that it didn't load some scripts from unsecure sources

also I've noticed that those working links have 'token' variable in the link, and those that didn't work contains '_token' variable

maybe it's htaccess or something - how to repair it?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @gbartosz83,

In my case, I did not manage to reproduce the issue with PS1.7.6.1 & Nginx server.
https://drive.google.com/file/d/1fnCZ8zJnUS6eyvWhvnPWlDDKJwzW2MsA/view
It is a server configuration issue.
here's my nginx configuration
```
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	# Add stdout logging
        error_log /var/log/nginx/error.log info;
        access_log /var/log/nginx/access.log;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files $uri $uri/ /1750/index.php?$args;
		# Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
		# AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
	}
	# Gzip Settings, convert all types.
        gzip on;
        gzip_vary on;
        gzip_proxied any;

        # Can be enhance to 5, but it can slow you server
        # gzip_comp_level    5;
        # gzip_min_length    256;

        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;

        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
	# Symfony controllers
        location /1750/admin-dev/ {                                  # [REQUIRED EDIT] the name of your admin directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /1750/admin-dev/index.php last;   # [REQUIRED EDIT] the name of your admin directory
            }
        }

        # Cloudflare / Max CDN fix
        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        # Do not save logs for these
        location = /1750/favicon.ico {
            log_not_found off;
            access_log off;
        }
        location = /1750/robots.txt {
            auth_basic off;
            allow all;
            log_not_found off;
            access_log off;
        }


	error_page 404 /1750/index.php?controller=404;

        location ^~ /sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }
        location ^~ /twitter.svg {
            alias /var/www/errors/twitter.svg;
            access_log off;
        }
        location ^~ /gitlab.svg {
            alias /var/www/errors/gitlab.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off; 
    		deny all;
	}
        
	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}

```
I created from this file https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
About the invalid token, thanks to follow this comment: https://github.com/PrestaShop/PrestaShop/issues/15592#issuecomment-534950199, it solves your issue.
Thanks to check & feedback.

**Comment by gbartosz83** [comment]
Sorry but I'm a prestashop newbie, where should I put this file: in the website root or shop root?
or maybe there? docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf (I can't change permissions for this directory to put this file there)
I have a website and shop, the shop is one of the tab - like this domain.com/shop
thank you for quick reply

**Comment by khouloudbelguith** [comment]
@gbartosz83, no, this is a file of the configuration on your server, you should put it on your server.
It should be available on `/etc/nginx/sites-available/default.conf`
For more details, you can ask your host.

Thanks!

**Comment by gbartosz83** [comment]
> @gbartosz83, no, this is a file of the configuration on your server, you should put it on your server.
> It should be available on `/etc/nginx/sites-available/default.conf`
> For more details, you can ask your host.
> 
> Thanks!

thank you I will do that

**Comment by khouloudbelguith** [comment]
@gbartosz83, thanks!

Waiting for your feedback.

**Comment by gbartosz83** [comment]
my web admin changed this config file but now I have 404 error instead
index.php/sell/orders/invoices/?token=
index.php/sell/catalog/products?_token=
and so on

**Comment by khouloudbelguith** [comment]
@gbartosz83, it is an issue about your configuration.
There is an incorrect redirection.
Please follow this line: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L55

Thanks!

**Comment by gbartosz83** [comment]
there is only admin and my admin folder has an extra letters afer admin word
can I change the folder name to admin in the FTP directory or should I change again the config file? 

also my front page still doesn't work I have too many redirection error

**Comment by khouloudbelguith** [comment]
@gbartosz83, the link that I provided to you, it is just an example & you need to edit your config file according to your configuration.
For example, you need to replace `admin` to `admin_folder`.

Thanks!

**Comment by gbartosz83** [comment]
> @gbartosz83, the link that I provided to you, it is just an example & you need to edit your config file according to your configuration.
> For example, you need to replace `admin` to `admin_folder`.
> 
> Thanks!

I have another question: if my shop is in such a directory: mysite.pl/shop
the admin directory should be location /1750/adminajhgajha/ or location /1750/shop/adminajhgajha/


why my main page of the shop doesn't work?

**Comment by khouloudbelguith** [comment]
@gbartosz83, it depends on your root
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L5

Thanks!

**Comment by gbartosz83** [comment]
My Admin doesn't know prestashop can you help me edit the config file?
I don't have access to the server configuration, I can only sent it to my admin.
Which lines should I check, I have some redirects rules for my website (non-shop part)

**Comment by khouloudbelguith** [comment]
@gbartosz83, you need to check this line
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L5
And this line
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L55
In my first comment, I provided you my Nginx configuration (in my case, the path of my project is `/var/www/html/1750/ `& the admin folder is `admin-dev`)
I hope this helps you.

Thanks!

**Comment by gbartosz83** [comment]
my shop domain is domain.com/shop

if my nginx root path is:
root	/srv/www/domain.com;

so admin should be like this? 
location /admin-myname/ {  
directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /admin-myname/index.php last;   
            }
        }
or rather like this? 
location /shop/admin-myname/ {  
directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /shop/admin-myname/index.php last;   
            }
        }

**Comment by khouloudbelguith** [comment]
@gbartosz83, did you tried with this configuration?

```
location /admin-myname/ {
directory
if (!-e $request_filename) {
rewrite ^/.$ /admin-myname/index.php last;
}
```

Thanks!

**Comment by gbartosz83** [comment]
> @gbartosz83, did you tried with this configuration?
> 
> ```
> location /admin-myname/ {
> directory
> if (!-e $request_filename) {
> rewrite ^/.$ /admin-myname/index.php last;
> }
> ```
> 
> Thanks!

I don't have direct access to the server configuration, I have to send this file to my admin, that's why I'm asking which folder path will work, I have access via ftp account

**Comment by khouloudbelguith** [comment]
@gbartosz83, thanks to send it, check & feedback.

**Comment by gbartosz83** [comment]
heh

**Comment by khouloudbelguith** [comment]
@gbartosz83, waiting for your feedback.
Thanks!

**Comment by gbartosz83** [comment]
my Admin changed the nginx config file but it doesn't helped 
what should be here?
try_files $uri $uri/ /shop/index.php?$args;
or 
try_files $uri $uri/ /index.php?$args;

**Comment by khouloudbelguith** [comment]
@gbartosz83, You must write your own rules, as we do for Apache.
More because it's an [example]( https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) and you can customize this part by everything you want.
If you do not know how Nginx works, you need to call a professional.
Also, for a second configuration, you can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/10156#issuecomment-416482457), it is provided by our developer & it is well working, and as I said, you need to define all rules in your Nginx configuration.

Thanks to check & feedback.

**Comment by gbartosz83** [comment]
Prestashop installation script should display errors during installation, or some configuration warnings, there wasn't any information about all of this...
if you're providing installation script then make it properly

**Comment by khouloudbelguith** [comment]
@gbartosz83, yes, during the install, we check the system compatibility 
![image](https://user-images.githubusercontent.com/16067358/66821772-48847b80-ef43-11e9-8c3a-b2e642b78eee.png)
But, in your case, with Nginx, You can't use htaccess files in Nginx context, you need to write your own rules.
The .htaccess file is generated by PrestaShop but it's because Apache allows to use it. Unlike Nginx.
You can find example here: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist

Thanks!

**Comment by gbartosz83** [comment]
I know that I have to rewrite rules. I manage to did it for my website (which have nothing to do with prestashop), but when it comes to prestahop my ideas ends.

**Comment by khouloudbelguith** [comment]
@gbartosz83, in my case, it is OK with PS1.7.6.1 & nginx/1.14.0
https://drive.google.com/file/d/19ZIdf_v8k9Y51hG_vHv1dig45CJgwLLI/view
I used this file of configuration
[default.conf.zip](https://github.com/PrestaShop/PrestaShop/files/3730287/default.conf.zip)

Thanks!

**Comment by gbartosz83** [comment]
> @gbartosz83, in my case, it is OK with PS1.7.6.1 & nginx/1.14.0
> https://drive.google.com/file/d/19ZIdf_v8k9Y51hG_vHv1dig45CJgwLLI/view
> I used this file of configuration
> [default.conf.zip](https://github.com/PrestaShop/PrestaShop/files/3730287/default.conf.zip)
> 
> Thanks!

thank you

**Comment by khouloudbelguith** [comment]
Hi @gbartosz83,

Despite our several trials, we could not reproduce your issue.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by gbartosz83** [comment]
great! why did you do that ? 
maybe someone else could help?

**Comment by khouloudbelguith** [comment]
@gbartosz83, since we cannot reproduce the issue, we need to close it.
But still, other users can comment.

Thanks!
