### ISSUE TITLE
Double bug

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#15863]
**Describe the bug**
Much products dont show the image in home but they are good placed in backoffice and in product page.

![Screenshot_20191008-085530_Opera](https://user-images.githubusercontent.com/9163980/66373681-7dc02500-e9a9-11e9-83c9-5fdc355915d6.jpg)

Cant make profiles whit all the privileges i like it in back office
![Screenshot_20191008-085139_Opera](https://user-images.githubusercontent.com/9163980/66373666-7731ad80-e9a9-11e9-9327-bdfb12be94a9.jpg)

**To Reproduce**
1. Go to 'www.nerai.es'
2. See error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2-FPM

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Could you please navigate to your BO => Design  => Image Settings Page=>  Click on the "Regenerate thumbnails" button
![image](https://user-images.githubusercontent.com/16067358/66379414-a9490c80-e9b5-11e9-8cc3-5acbb0e185c4.png)

Thanks to check & feedback.

**Comment by LinkOfLight** [comment]
I make it, but Sony generate

Obtener Outlook para Android<https://aka.ms/ghei36> desde mi Galaxy S10+

Angel Moreno Cubero - CEO de WolfWare - www.wolfware.pro<http://www.wolfware.pro>

Advertencia Legal: La información que contiene este correo electrónico y, en su caso, los ficheros adjuntos, está dirigida a la persona cuya dirección electrónica figura en la cabecera. Si usted recibe este correo electrónico y no es el destinatario, ruegolo borre de inmediato y comunique dicha circunstancia. Cualquier uso fraudulento realizado con el contenido del correo electrónico recibido queda sometido a las acciones previstas por la legislación vigente. Queda expresamente prohibida la divulgación, copia o distribución a terceros sin la previa autorización.

Política de Protección de Datos de Carácter Personal:En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), y el propio Reglamento General de Protección de Datos, ANGEL MORENO CUBERO,Responsable del Fichero, informa a los usuarios que los Datos de Carácter Personal que recoge son objeto de tratamiento mixto, y se incorporan en los ficheros correspondientes debidamente registrados en la Agencia Española de Protección de Datos. En nombre de la empresatratamos la información que nos facilita con el fin de prestarles el servicio solicitado y realizar la facturación del mismo. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal. En virtud de lo establecido en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), ANGEL MORENOCUBERO, Responsable del Fichero, le informa que podrá utilizar las direcciones de correo electrónico facilitadas por los usuarios, para mantenerles informado acerca de lo concerniente a la relación comercial establecida. Usted da su consentimientoexpreso para que el Responsable del Fichero, ANGEL MORENO CUBERO, pueda utilizar su dirección de correo electrónico con este fin concreto Usted tiene derecho a obtener confirmación sobre si ANGEL MORENO CUBERO está tratando sus datos personales, por tanto tiene derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios. En ningún caso le será enviada publicidad de ningún tipo. El usuario podrá en todo momento ejercitar los referidos derechos reconocidos en la LOPD, de Acceso, Rectificación, Cancelación y Oposición (ARCO). El ejercicio de estos derechos puede realizarlo el propio usuario acompañando copia del DNI de manera presencial en las oficinas de ANGEL MORENO CUBERO, titular del DNI 26820694A, como Responsable del Fichero, bien mediante correo electrónico admin@wolfware.pro, o bien mediante comunicación escrita a la siguiente dirección postal Ángel Moreno Cubero. C/ Juan Ramón Jiménez 1 Local- Doña Mencía (Córdoba). C.P. 14860 – España.


________________________________

**Comment by khouloudbelguith** [comment]
@LinkOfLight,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by LinkOfLight** [comment]
Shame situation

Obtener Outlook para Android<https://aka.ms/ghei36> desde mi Galaxy S10+

Angel Moreno Cubero - CEO de WolfWare - www.wolfware.pro<http://www.wolfware.pro>

Advertencia Legal: La información que contiene este correo electrónico y, en su caso, los ficheros adjuntos, está dirigida a la persona cuya dirección electrónica figura en la cabecera. Si usted recibe este correo electrónico y no es el destinatario, ruegolo borre de inmediato y comunique dicha circunstancia. Cualquier uso fraudulento realizado con el contenido del correo electrónico recibido queda sometido a las acciones previstas por la legislación vigente. Queda expresamente prohibida la divulgación, copia o distribución a terceros sin la previa autorización.

Política de Protección de Datos de Carácter Personal:En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, sobre Protección de Datos de Carácter Personal (LOPD), y el propio Reglamento General de Protección de Datos, ANGEL MORENO CUBERO,Responsable del Fichero, informa a los usuarios que los Datos de Carácter Personal que recoge son objeto de tratamiento mixto, y se incorporan en los ficheros correspondientes debidamente registrados en la Agencia Española de Protección de Datos. En nombre de la empresatratamos la información que nos facilita con el fin de prestarles el servicio solicitado y realizar la facturación del mismo. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal. En virtud de lo establecido en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), ANGEL MORENOCUBERO, Responsable del Fichero, le informa que podrá utilizar las direcciones de correo electrónico facilitadas por los usuarios, para mantenerles informado acerca de lo concerniente a la relación comercial establecida. Usted da su consentimientoexpreso para que el Responsable del Fichero, ANGEL MORENO CUBERO, pueda utilizar su dirección de correo electrónico con este fin concreto Usted tiene derecho a obtener confirmación sobre si ANGEL MORENO CUBERO está tratando sus datos personales, por tanto tiene derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios. En ningún caso le será enviada publicidad de ningún tipo. El usuario podrá en todo momento ejercitar los referidos derechos reconocidos en la LOPD, de Acceso, Rectificación, Cancelación y Oposición (ARCO). El ejercicio de estos derechos puede realizarlo el propio usuario acompañando copia del DNI de manera presencial en las oficinas de ANGEL MORENO CUBERO, titular del DNI 26820694A, como Responsable del Fichero, bien mediante correo electrónico admin@wolfware.pro, o bien mediante comunicación escrita a la siguiente dirección postal Ángel Moreno Cubero. C/ Juan Ramón Jiménez 1 Local- Doña Mencía (Córdoba). C.P. 14860 – España.


________________________________

**Comment by khouloudbelguith** [comment]
@LinkOfLight, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

PS: To attach files, you need to Sign in to GitHub & attach files here.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @LinkOfLight,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
