### ISSUE TITLE
1.7.6.1 valuta eur problem server 500 error

### ISSUE THREAD

**Issue by nesoor** [PrestaShop/PrestaShop#15867]
Hello Github Members,
I upgraded from from 1.7.4.2 to 1.7.6.1 and got this problem.
Does anybody has a fix for it?

The valuta has been removed when I installed 1.7.6.1 and when I add one I get a server error 500 at the frontend.

**Error log:**
`[Tue Oct 08 12:30:08.490355 2019] [php7:error] [pid 14716] [client 2001:1c01:46c7:8400:70e6:4884:c2fa:566d:0] PHP Fatal error:  Uncaught PrestaShop\\PrestaShop\\Core\\Localization\\Exception\\LocalizationException: Price specification not found for currency: "EUR" in /home/username/domains/domain.nl/public_html/src/Core/Localization/Locale.php:171\nStack trace:\n#0 /home/username/domains/domain.nl/public_html/src/Core/Localization/Locale.php(155): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->getPriceSpecification('EUR')\n#1 /home/username/domains/domain.nl/public_html/classes/Tools.php(776): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->formatPrice(0, 'EUR')\n#2 /home/username/domains/domain.nl/public_html/src/Adapter/Product/PriceFormatter.php(55): ToolsCore::displayPrice(0, Object(Currency))\n#3 /home/username/domains/domain.nl/public_html/src/Adapter/Presenter/Cart/CartPresenter.php(336): PrestaShop\\PrestaShop\\Adapter\\Product\\PriceFormatter->format(0)\n#4 /home/username/domains/domain.nl/public_html/classes/controller/FrontController.php(490): PrestaShop\\PrestaShop\\Adapter\\Presenter\\C in /home/username/domains/domain.nl/public_html/src/Core/Localization/Locale.php on line 171`

**Comment by khouloudbelguith** [comment]
Hi @nesoor, 

Does this issue occur in the BO => Orders Page?

Thanks!

**Comment by nesoor** [comment]
@khouloudbelguith 
No so far as I know everything is fine in the orders.
However I can't access the following page in the backend: International > Localization > Currency (error 500)

**Comment by khouloudbelguith** [comment]
@nesoor, did you delete the EUR currency before? or did you use the multistore context?
Because we manage to reproduce the similar bug but in different pages
https://github.com/PrestaShop/PrestaShop/issues/15486
https://github.com/PrestaShop/PrestaShop/issues/15376
Thanks to check & feedback.

**Comment by nesoor** [comment]
@khouloudbelguith 
We did used the Multi store but we have disabled it long time ago.
We didn't deleted the EUR currency before updating. I just deleted the Euro a currency a few seconds ago but now also the backend and frontend shows an error 500

**Comment by nesoor** [comment]
![Annotation 2019-10-08 130403](https://user-images.githubusercontent.com/19656499/66391164-b8878480-e9cc-11e9-8f4c-8f57ec2c169b.jpg)

**Comment by nesoor** [comment]
The shop also doesn't show any valuta and all prices are rounded for an example from: 19,95€ to 20 without a currency sign.

**Comment by khouloudbelguith** [comment]
@nesoor, so after deleting the currency Euro, this issue occurs, before that, it is OK?

Thanks!

**Comment by nesoor** [comment]
@khouloudbelguith Before deleting the EUR currency all product prices were rounded and didn't have any currency sign. After deleting EUR currency the back and frontend got internal server error 500.

**Comment by khouloudbelguith** [comment]
@nesoor, as I see in your screenshot, the table of the currencies is missing some columns(numeric_iso_code, precision)
![image](https://user-images.githubusercontent.com/16067358/66393536-1919c000-e9d3-11e9-9b18-86f9b375542f.png)
So, I think, that there is something wrong during the upgrade.
Thanks to adding those missing columns, check & feedback.

**Comment by nesoor** [comment]
@khouloudbelguith After the screenshot I tried importing US currency which didn't work so I created the missing fields and importing started working. However this didn't solve my issue.

**Comment by nesoor** [comment]
I clicked on closed by accident.

**Comment by khouloudbelguith** [comment]
@nesoor, 

>After deleting EUR currency the back and frontend got internal server error 500.

Did you delete this currency from the BO?
What is the exact currency by default in your shop?
In my case, it is OK after deleting a currency, the currency Page is well displayed.

Thanks!

**Comment by nesoor** [comment]
I deleted the currency in the database because there is no currency available even though it is shown in the database. The default and only currency is EUR.

**Comment by khouloudbelguith** [comment]
@nesoor, you make it in a dangerous way, because, from the BO, we cannot delete a currency by default of the shop & the currency used by your employee.
![image](https://user-images.githubusercontent.com/16067358/66401054-cfd16c80-e9e2-11e9-98fe-e2c591325a20.png)
Have you a backup of your database before deleting this currency?
Thanks!

**Comment by nesoor** [comment]
Yes I just restored it :)

**Comment by khouloudbelguith** [comment]
@nesoor, thanks to add the missing columns now to the table ps_currency.

**Comment by nesoor** [comment]
@khouloudbelguith I already restored the database and added the columns to ps_currency after adding the columns I created a new backup of the database.

**Comment by khouloudbelguith** [comment]
@nesoor, the issue still occurs?

Thanks!

**Comment by nesoor** [comment]
Yes still the same problem.

**Comment by khouloudbelguith** [comment]
@nesoor, still the exception ? or currency all product prices were rounded and didn't have any currency sign?

>Before deleting the EUR currency all product prices were rounded and didn't have any currency sign. After deleting EUR currency the back and frontend got internal server error 500.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @nesoor,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
