### ISSUE TITLE
Extract variable generation to another method on PaymentModule

### ISSUE THREAD

**Issue by mowcixo** [PrestaShop/PrestaShop#15873]
**Is your feature request related to a problem? Please describe.**
Based on solid principles, email variable generation should be extracted to another method.

**Describe the solution you'd like**
It has no sense to extend PaymentModule.php class and its giant validateOrder function, just for modifying email template variables, so it would be nice to have another function for this purpose: https://github.com/PrestaShop/PrestaShop/blob/85e403b811d0b4464bfca29cbe34e726f5ac1a73/classes/PaymentModule.php#L578-L631

Probably related to https://github.com/PrestaShop/PrestaShop/issues/10066

I would be glad to write a PR if the proposal is accepted.

**Comment by khouloudbelguith** [comment]
Hi @mowcixo,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
> **Describe the solution you'd like**
> It has no sense to extend PaymentModule.php class and its giant validateOrder function, just for modifying email template variables, so it would be nice to have another function for this purpose

This makes sense, absolutely 👍

There is one thing I'm afraid though 🤔: would this considered a backward compatibility break ? I dont think so but I dont want to break some modules / custom code behavior

**Comment by matks** [comment]
@mowcixo However if your need is to modify the mail variables, you can do this using hook `actionEmailSendBefore` called in `Mail::send()` ?

**Comment by mowcixo** [comment]
@matks I'm not writing the issue because a particular problem, is just an improvement suggestion.

The case is that if in the hook you need something outside the hook params to modify the variables, you will need to reload certain entities, making database queries etc... and probably all of it entities were already filled in the PaymentModule class.

If you have the possibility to override PaymentModule class, having another function just for email variables that had the access to all those entities ($delivery, $invoice....) it would be more performance optimized than the hook.

**Comment by PierreRambaud** [comment]
These variables are only used for email, the `$data` is not used elsewhere :thinking: 
I don't even know why we have to build this array if we don't pass this condition: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L671

**Comment by mowcixo** [comment]
That's right @PierreRambaud it makes no sense. I don't have the time right now to make a PR to aproach this, so maybe it shouldn't be marked as "waiting for author" as the improvement has been confirmed.

**Comment by PierreRambaud** [comment]
I create pull request #22087 to improve performance, but I don't see any reason to add a custom hook when you can use `actionEmailSendBefore`.
If you agree, you can close this issue :)
