### ISSUE TITLE
Oneclick upgrade from 1.7.5.2 to 1.7.6.1 (database_prefix)

### ISSUE THREAD

**Issue by fdonnet** [PrestaShop/PrestaShop#15877]
Linked #15080 to Oneclick upgrade from 1.7.5.2 to 1.7.60 (database_prefix) need to be reopen.

@khouloudbelguith
Even with the new version 1.7.6.1 the problem persists and I was forced to roll back to 1.7.5.2.

I can send you the update log if needed. 
Never had this kind of issue in the past with other auto-upgrade on this shop.

**Comment by khouloudbelguith** [comment]
Hi @fdonnet,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by fdonnet** [comment]
Could you pls give me your email @khouloudbelguith. Thx

**Comment by khouloudbelguith** [comment]
@fdonnet, This is a public space.
You can provide me the files by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by fdonnet** [comment]
Log.txt provided by email @khouloudbelguith 

Additional info:
ubuntu
php 7.2.19
mysql 5.7.27
child_classic theme (upgrade made with classic theme update and without => same issue)

error details in #15080

**Comment by khouloudbelguith** [comment]
@fdonnet, according to your log file
The files are well upgraded
>[2019-10-09 13:41:06] All files upgraded

The database is well upgraded
>[2019-10-09 13:41:11] Database upgrade OK

The upgrade of your modules are well done
>[2019-10-09 13:41:50] Upgrade process done, but some warnings have been found.

There is no `database_prefix` error in your file.

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith 
So why I have an error 500 on the front store, I cannot accesss any pages on the store after the upgrade the error message is 
"Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "prestashop.database.naming_strategy" has a dependency on a non-existent parameter "database_prefix". in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:102 Stack trace: #0 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('database_prefix') #1 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('database_prefix') #2 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->re in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 102"

(in debug)

The admin backend works...

on 1.7.5.2 it works perfectly fine but when i upgrade to 1.7.6.0 or 1.7.6.1 I have this database prefix problem.

Thx a lot for your help.

**Comment by khouloudbelguith** [comment]
@fdonnet, the password of your database contains a % symbol?

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith  No, no "%" char in the db password.

**Comment by khouloudbelguith** [comment]
@fdonnet, could you please provide us your files `app/config/parameters.php` &  `app/config/parameters.yml.dist`

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith 
Files sent by email.

the yml.dist seems a bit strange because it only contains default values ?
Thx for the support.
Regards,

**Comment by khouloudbelguith** [comment]
@fdonnet, yes I just received your email.
Those files are ok.
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1.Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2.Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3.Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by fdonnet** [comment]
hello, @khouloudbelguith 
For info, I have other shops on this server with this exact PHP config and it's working fine. 
Here are the results :
![image](https://user-images.githubusercontent.com/45830712/66562904-e8fe2880-eb5c-11e9-8752-fadfaf3d6b75.png)

**Comment by khouloudbelguith** [comment]
@fdonnet, did you use any custom them? or any custom module used in the FO?

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith I use a child theme based on the standard classic theme (no modification made in the original parent classic theme). 
I tried to upgrade with the "upgrade the classic theme" (true/false) options without success.
No custom module => very simple shop configuration, that's why it very strange and difficult to identify the problem.

**Comment by khouloudbelguith** [comment]
@fdonnet, to make sure because the upgrade is well done in your case.
Have you tried to install a fresh PrestaShop PS1.7.6.1, it is well working in your case?

Thanks!

**Comment by fdonnet** [comment]
Not for this shop.
But i have 2 other shops on this servers and it s working perfectly fine. 
AutoUpgrade from 1.7.5.2 to 1.7.6.0 = no problem,
AutoUpgrade from 1.7.6.0 to 1.7.6.1 = no problem

For this particular shop, all the other previous upgrades worked very well too. So I don't understand why I cannot push through 1.7.6 ;)

**Comment by khouloudbelguith** [comment]
@fdonnet, thanks!
Could you please try to remove the 1-click upgrade module from your shop, clear cache, check & feedback.

Thanks!

**Comment by fdonnet** [comment]
hello @khouloudbelguith,

Before or after the the upgrade ? Because I already tried to uninstall and reinstall it before i made an upgrade ?
Regards,
Fabien

**Comment by khouloudbelguith** [comment]
@fdonnet, no after the upgrade, just temporarily.
Or you can rename the `autoupgrade` folder to `autoupgrade_old`

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith exactly the same issue... need to roll back again ;)

**Comment by khouloudbelguith** [comment]
@fdonnet, could you please check the file `config.xml` in your module the 1-click upgrade & check the version
`<version><![CDATA[4.9.0]]></version>`

Thanks!

**Comment by fdonnet** [comment]
yes @khouloudbelguith in config.xml
` <version><![CDATA[4.9.0]]></version>`

**Comment by fdonnet** [comment]
@khouloudbelguith 

I just think about that : in the log.txt I sent to you I have this line :
[2019-10-09 13:41:11] Database upgrade OK
**[2019-10-09 13:41:14] Erreur(s) détectée(s) pendant la mise à jour.**
[2019-10-09 13:41:14] Database upgraded. Now upgrading your Addons modules...

Without any 0 or any information if I really had errors, and where ?
But maybe it's perfectly fine. Don't know.

**Comment by khouloudbelguith** [comment]
@fdonnet, could you please check that your files are similar to those files
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/config/services/common.yml#L13
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/src/PrestaShopBundle/Resources/config/services/bundle/services.yml#L41

Thanks!

**Comment by fdonnet** [comment]
@khouloudbelguith in the second one(services.yml) it seems that this line is missing on my side
modules_dir:              "%kernel.root_dir%/../modules"

line 6

But other than that the files are the same...

**Comment by fdonnet** [comment]
@khouloudbelguith (sry my mistake) I removed the post.
I confirm the files are exactly the same. (my shop after the update is aligned with the original github files you put above)

**Comment by khouloudbelguith** [comment]
@fdonnet, I just sent your error to our developer to check it.
Thanks for your understanding!

**Comment by fdonnet** [comment]
@khouloudbelguith 
Mega big sorry on my side. I finally found my problem. 
I had a override of the FrontController.php that I forgot about. (even when override are disabled in the shop the problem persists, I think because it was in the init func)

I just copied the good FrontController.php from the 1.7.6.1 and add the line related to my B2B redirection and now the site is working perfectly fine.

The changes made in the FrontController.php for version 1.7.6.x are some kind of big and my old override 1.7.5 file is no more compatible.

Again thx a lot for your support and sorry for the time I stole from you for my own sh... issue  ;)
Regards,

**Comment by khouloudbelguith** [comment]
@fdonnet, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Disable override button not working with PS1.7.6.1 reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14596
Thanks!

**Comment by deliciousvinos** [comment]
Hello. I've the same problem. 
I have followed all the steps and nothing, it still happens to me the same. I just need to look at the FrontController.php, but I don't know what to do with this.
I need help, I'm desperate ...
![1](https://user-images.githubusercontent.com/73553826/97346224-778a3880-188b-11eb-9193-16d5df57151c.jpg)

**Comment by PensionLab** [comment]
@deliciousvinos 
you need to compare your FrontController file, if you have one, in your override folder with the base FrontController, locate the differences in it if you want to reapply the specific behavior (text compare tool). 

Maybe it is not the same issue as mine... but the "disable override" checkbox function in the shop configuration doesn't seem to always work. (the difference is maybe located in another file in your case but the 1.7.6 version have a lot of core updates that can cause issue if you made override on our prestashop 1.7.5 vs).

Hope it helps a little....

**Comment by deliciousvinos** [comment]
Thanks. Tomorrow test it.
More information and posibles solutions about my problem?

**Comment by deliciousvinos** [comment]
I have doing some changes and currently I can run website in maintenance mode and enter in the backend whitout problems, but if I turn off maintenance mode, then I can´t enter in the website and I've this new error:

mod_fcgid: stderr: PHP Notice:  Undefined index: database_prefix in /home/deliciou/domains/deliciousesmas.es/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 104

mod_fcgid: stderr: PHP Notice:  Undefined index: database_prefix in /home/deliciou/domains/deliciousesmas.es/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 104, referer: https://www.deliciousesmas.es/

Can you help me, please?
