### ISSUE TITLE
[My Store] Appears in emails after upgrading to version 1.7.6.1 

### ISSUE THREAD

**Issue by Allbutfancy** [PrestaShop/PrestaShop#15885]
The issue
Whenever you receive information, messages or news from our site. We as the sender will appear as [My Store] in the mail.
We have added the stores name in Contact -> Stores.

It was working in 1.7.5.1 but after updating to 1.7.6.1 this bug appeared.

1. Go to www.dreamdirty.dk
2. Scroll down to the footer
3. Click "kontakt os" or "contact us"
4. Enter your email
5. Then you will receive mail with [My Store] as name of sender

- Additional information
PrestaShop version: 1.7.6.1
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @Allbutfancy,

Could you please try to navigate to the BO => Shop Parameters => General => Enable "Multistore".
Then go to the BO => Advanced Parameters => Multistore => Edit your shop => & edit the shop name & save => after that try to disable multistore.
![image](https://user-images.githubusercontent.com/16067358/62037610-02453900-b1ec-11e9-96a7-1764ab2dabcb.png)
You need to check that all categories & subcategories are checked before saving (click on Expand all & check all multiple times)
Thanks to check & feedback

**Comment by Allbutfancy** [comment]
Hey @khouloudbelguith,

Would enabling MultiStore not change anything to our shops database? We were informed that enabling MultiStore would change the core mechanic of the store, and disabling the multistore function afterwards could cause big database problems. 

Best wishes

**Comment by khouloudbelguith** [comment]
@Allbutfancy, you will not change anything, you not create a new shop & you will disable it after changing the name shop.
A second way, you can change the shop name manually from the database, table `ps_shop`
![image](https://user-images.githubusercontent.com/16067358/66488541-6028b380-eaae-11e9-94f2-fc81acb98423.png)

Thanks!

**Comment by ArielBaravalle** [comment]
Hello,  i have the same problem in a new clean installation of PS 1.7.6 
in the email received the shop name is "My shop"

![image](https://user-images.githubusercontent.com/9282436/66760860-33f0a680-eea3-11e9-8df3-ac120a77b12c.png)


in this version i can find the option tu enable or disable the multistore.  I try create two store more ,  and delete this , and can resolve this.

**Comment by khouloudbelguith** [comment]
Hi @ArielBaravalle,

Have you tried to follow this comment: https://github.com/PrestaShop/PrestaShop/issues/15885#issuecomment-540015919
Update the shop name manually from the database.

PS: thanks to make a back up of your shop & database before editing the database.
Let's be safe.

Thanks!

**Comment by ArielBaravalle** [comment]
Hi @khouloudbelguith  
thanks for you help.
i change  the name of shop in the admin web ,  and the name change en the database :
 
![image](https://user-images.githubusercontent.com/9282436/66807121-136b2f80-ef29-11e9-9a79-2719d1be151c.png)


in the email receibed  when register a new user,  the emial name show the correct name "tiendita"   but in the text of email show "my shop"
![image](https://user-images.githubusercontent.com/9282436/66806551-1fa2bd00-ef28-11e9-9a47-f641c3a7a4c6.png)

i try create two new shops:
![image](https://user-images.githubusercontent.com/9282436/66806778-ae173e80-ef28-11e9-8bcf-bf2e395cd32b.png)

how continue to resolve? i need delete the two shops ?

regards

**Comment by ArielBaravalle** [comment]
Solved.
change the database after delete the stores.
UPDATE `ps_shop` SET `name` = 'newname' WHERE `ps_shop`.`id_shop` = 1;

thanks!

**Comment by khouloudbelguith** [comment]
@ArielBaravalle, Great!
@Allbutfancy, any news?

Thanks!

**Comment by Allbutfancy** [comment]
@khouloudbelguith, Sorry for being inactive. We are currently waiting for our developer to try out the posted solutions. We will update you as soon as possible!

Thank you!

**Comment by khouloudbelguith** [comment]
@Allbutfancy, thanks!
Waiting for your feedback.

**Comment by Allbutfancy** [comment]
@khouloudbelguith, Finally we had time to try out the multistore solution. It worked without any issues! Thanks for the quick and effective answers!

Best regards

**Comment by khouloudbelguith** [comment]
Hi @Allbutfancy,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14891
