### ISSUE TITLE
Tax does not work

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#15884]
I already selected the tax rule, but the price with and without tax is the same.

<img width="1436" alt="Screen Shot 2019-10-09 at 9 02 23 PM" src="https://user-images.githubusercontent.com/6930263/66483720-397f7280-ead8-11e9-9b41-3724338dd90f.png">

**Comment by TomHsiung** [comment]
Your product setting is strange for a general customer. Why I have set it to tax but the price stays the same!

**Comment by khouloudbelguith** [comment]
Hi @TomHsiung,

Thanks to navigate to BO => International => Taxes => Taxes Rules => edit your Tax rule & check the Tax
![image](https://user-images.githubusercontent.com/16067358/66484359-1dafa880-eaa7-11e9-9dd7-82442abc8560.png)

Thanks to check & feedback.

**Comment by TomHsiung** [comment]
OK. Yes, I tried and it worked. Thank you.

**Comment by khouloudbelguith** [comment]
@TomHsiung, thanks for your feedback.
I close the issue, Feel free to open a new one needed.

Thanks!
