### ISSUE TITLE
Cannot change the email of a customer from a minor case letter to uppercase - Back office

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15889]
**Describe the bug**
It is not possible to change the email of a customer from a minor case letter in uppercase from the Back office
In the FO, it is OK.

**To Reproduce**
1. Go to the BO => Customers Page
2. Edit a customer (Jhon Doe)
3. Change the email for example from pub@prestashop.com to Pub@prestashop.com or PUB@prestashop.com
4. Click on save
![image](https://user-images.githubusercontent.com/16067358/66498515-7dfe1480-eabe-11e9-9c7e-697cdf6b1740.png)

With PS1.7.5.2 => OK
https://drive.google.com/file/d/1eZGay5m_f2bUFXfb_49KsQBV0f40wGrB/view

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by sbaraka** [comment]
hey can I pick this up?

**Comment by khouloudbelguith** [comment]
Hi @sbaraka,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by matks** [comment]
> hey can I pick this up?

Be our guest 😄
