### ISSUE TITLE
legacy order create page not working well after jquery migration

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#15882]
@matthieu-rolland, @matks  - after this pr legacy order create page is not working well.

- Cannot choose customer;
- Carts/orders are shown before even choosing customer. 

![Screenshot from 2019-10-09 14-18-47](https://user-images.githubusercontent.com/31609858/66477208-3072af00-eaa0-11e9-9b95-c41a68a92d2f.png)
Checked locally, that undoing this pr changes brings back the expected behavior.

_Originally posted by @zuk3975 in https://github.com/PrestaShop/PrestaShop/pull/15245#issuecomment-539958808_

**Comment by matthieu-rolland** [comment]
The **live** method doesn't exist anymore, one should use the **on** method instead.

Here is the **on** method:
https://api.jquery.com/on/

Here is how to use the **on** method to achieve the same thing as with the **live** method:
`$( document ).on( events, selector, data, handler );` 

The equivalent with the **live** method would be:
`$( selector ).live( events, data, handler );`

I'll do it.

**Comment by khouloudbelguith** [comment]
Hi,

Same issue with develop branch
![image](https://user-images.githubusercontent.com/16067358/66481848-0621f100-eaa2-11e9-9071-60d614905b90.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Also, the choose button doesn't work
![image](https://user-images.githubusercontent.com/16067358/66482249-d6bfb400-eaa2-11e9-94c7-137e4bfd1943.png)

Thanks!

**Comment by matthieu-rolland** [comment]
thank you for you feedback @khouloudbelguith 👍
