### ISSUE TITLE
Presta Shop Version 1.6.x Stock.

### ISSUE THREAD

**Issue by ySSistemas** [PrestaShop/PrestaShop#15883]
Hello.

While I order from the store, the quantity is deducted from the actual value of the stock receipt.

When I cancel this order, the quantity is not increased in stock.

I want to automatically increase the stock quantity when canceling the order.

Help me solve this problem.

Thanks in advance.

**Comment by khouloudbelguith** [comment]
Hi @ySSistemas,

I did not manage to reproduce the issue with PS1.7.6.1
https://drive.google.com/file/d/1HWjwr5wyvjgIxdreul8aLeG0N-_PADWC/view
[The maintenance of PrestaShop 1.6.1.x is now being performed exclusively by volunteers to fix critical issues only](http://build.prestashop.com/news/1.6.1.x-what-s-next/)
The normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
I close the issue.

Thanks for your understanding!
