### ISSUE TITLE
How to handle search in reduction column for "Catalog > Discounts > Catalog price rules > Add new / edit catalog price rule" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15890]
We have migrated page "Catalog > Discounts > Catalog price rules > Add new / edit catalog price rule" in PR https://github.com/PrestaShop/PrestaShop/pull/13584

However we have found one issue: https://github.com/PrestaShop/PrestaShop/pull/13584#discussion_r284236594

Basically, what happens is:
1) I create a catalog price rule with a reduction of 10.00005
2) I go to listing: well, on the listing the reduction is displayed but *rounded* so I see it was 10.00

![Capture d’écran 2019-10-09 à 18 27 36](https://user-images.githubusercontent.com/3830050/66500822-7f314080-eac2-11e9-8df2-b2076d2c0ca8.png)

3) However ... the "reduction" input I can use to "search for catalog price rules" is looking for an exact match.
=> So if I search all catalog rules whose reduction is 10.00005, I find my catalog price rule
=> So if I search all catalog rules whose reduction is 10.0, I **cannot find** my catalog price rule

There's a weird behavior here, which is that:
- the "search" input looks for exact matches
- but the data is being displayed after a rounding, so the customer cannot see the exact match 😄 

@MatShir @marionf

**Comment by marionf** [comment]
As the listing displays the amount rounded, If I search 10 or 10.00 it should find the result
Is it possible to do that ?

**Comment by MatShir** [comment]
I get the impression that this is a problem on the whole list for searches for numbers on Legacy. On the order page, if I type 20 to search for an order with a value of 20.84, I would not find it.

But it seems after a migrated page such as Product Page works fine. The problem might be fixed after migration? Wdyt @matks @PrestaShop/Prestashop-core-developers

**Comment by matks** [comment]
> I get the impression that this is a problem on the whole list for searches for numbers on Legacy. On the order page, if I type 20 to search for an order with a value of 20.84, I would not find it.
> 
> But it seems after a migrated page such as Product Page works fine. The problem might be fixed after migration? Wdyt @matks @PrestaShop/prestashop-core-developers

Product Listing page has been migrated differently than other listing pages (and will need re-migration to be harmonized)

I think what @marionf said must be tried.
"As the listing displays the amount rounded, If I search 10 or 10.00 it should find the result"
