### ISSUE TITLE
AdminCustomerController not found 

### ISSUE THREAD

**Issue by r4dhwene** [PrestaShop/PrestaShop#15894]
Hello
i can't find the file AdminCustomerController to edit customer form 
Can you help me?

**Comment by matks** [comment]
@r4dhwene This controller has been migrated to Symfony in latest release PS 1.7.6
The new controller is `PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController`

You might also be interested in
- a tutorial we have written to explain how to edit the form https://devdocs.prestashop.com/1.7/modules/sample_modules/grid-and-identifiable-object-form-hooks-usage/
- an exemple module to edit the form https://github.com/friends-of-prestashop/demo-cqrs-hooks-usage-module

**Comment by khouloudbelguith** [comment]
@r4dhwene, Those pages are migrated to symfony as described here: http://build.prestashop.com/news/prestashop-1-7-6-0-beta-release/
You can find the controller in this path: `Prestahop_Project/src/PrestaShopBundle/Controller/<path>/<Your>Controller`
- For example `AdminCategoriesController` exist here: `Prestahop_Project\src\PrestaShopBundle\Controller\Admin\Sell\Catalog`
- `AdminCustomerController` exits here: `PrstaShop_Folder\src\PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController`

Thanks!

**Comment by r4dhwene** [comment]
thanks for responding ! but how can i remove a field from Customer form [BACK-END] ? 
i can't find the function renderForm

**Comment by r4dhwene** [comment]
thanks for responding ! but how can i remove a field from Customer form [BACK-END] ?
i can't find the function renderForm

**Comment by mostofa62** [comment]
How to override this according to this tutorial concept
http://prestacraft.com/adding-new-fields-to-the-registration-form-in-prestashop-1-7/
