### ISSUE TITLE
Can't disable Terms and Condition check box on checkout

### ISSUE THREAD

**Issue by PrestaNewbie** [PrestaShop/PrestaShop#15897]
In order settings I disabled terms and condiotions check box, but it appears anyway in checkout.

PrestaShop version: 1.7.6.1
PHP version: 7.2
![how to disable](https://user-images.githubusercontent.com/56392393/66595437-a1e75600-eba3-11e9-9cda-b6eccc1f946e.PNG)

**Comment by khouloudbelguith** [comment]
Hi @PrestaNewbie,

This option is to Require customers to accept or decline terms of service before processing an order.
In fact, it is at the checkout page & not the "Create an account" page.
![image](https://user-images.githubusercontent.com/16067358/66565380-9a538d00-eb62-11e9-91bc-e7ff94790b0f.png)

Thanks to check & feedback.

**Comment by PrestaNewbie** [comment]
> Hi @PrestaNewbie,
> 
> This option is to Require customers to accept or decline terms of service before processing an order.
> In fact, it is at the checkout page & not the "Create an account" page.
> ![image](https://user-images.githubusercontent.com/16067358/66565380-9a538d00-eb62-11e9-91bc-e7ff94790b0f.png)
> 
> Thanks to check & feedback.

I already turned off Terms of service, but its still there, and yes its not Creat an account page its "checkout" page

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, in the last step of the payment.
If the option disabled
![image](https://user-images.githubusercontent.com/16067358/66574115-fd99eb00-eb73-11e9-849c-996f3a849167.png)
If it is enabled
![image](https://user-images.githubusercontent.com/16067358/66574151-0985ad00-eb74-11e9-8bd3-1103530e1a18.png)

Thanks!

**Comment by PrestaNewbie** [comment]
How should I disable these (partners offers disabled)--->
![how to disable](https://user-images.githubusercontent.com/56392393/66595504-c17e7e80-eba3-11e9-9b24-30d2b266e565.PNG)

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, To disable "partner offers", go to the BO => Shop Parameters => Customer Settings => Disable the option "partner offers"
![image](https://user-images.githubusercontent.com/16067358/66636314-405dd080-ec11-11e9-9a8c-e25d9a155342.png)
To disable the "Terms of service", go to the BO => Modules => Module Manager => Search for the module "psgdpr" => Click on Configure => Disable the "Account creation form"
![image](https://user-images.githubusercontent.com/16067358/66636460-874bc600-ec11-11e9-9f6a-8faa608c2042.png)

In the FO, it will be OK
![image](https://user-images.githubusercontent.com/16067358/66636485-99c5ff80-ec11-11e9-8ea6-25f4b05be3d7.png)
I close the issue, feel free to open a new one when needed.

Thanks!
