### ISSUE TITLE
Hide payment details in Order page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15893]
Following
- https://github.com/PrestaShop/PrestaShop/pull/15778#issuecomment-537911939
- https://github.com/PrestaShop/PrestaShop/pull/15778#issuecomment-538331114
- https://github.com/PrestaShop/PrestaShop/pull/15778#discussion_r332605043

It seems we want to remove any payment infos from the order page.

@colinegin @MatShir you confirm ?

I just want to state that I'm against it. PS shows what the payment modules provides. If the module is built correctly, it will provide hidden infos like "XXXX XXXX XXXX XX92" that can be useful for merchants (like customer service requests).

If the module is built in a bad way it might indeed show the full card number which is both insecure and incorrect. But I dont think we should modify PrestaShop behavior because some modules are badly written 😐

**Comment by colinegin** [comment]
@LouiseBonnard wdyt ?

**Comment by LouiseBonnard** [comment]
It's under discussion with the legal team, I keep you guys posted about it.

**Comment by LouiseBonnard** [comment]
📢 **UPDATE:**

We keep this details block but we hide it when there is no card transaction involved. Is everyone okay with this solution? @MatShir?

**Comment by matks** [comment]
> 📢 **UPDATE:**
> 
> We keep this details block but we hide it when there is no card transaction involved

Can you define "involved" ? Does it mean "if payment method is something else than an online payment using a credit card" ?

**Comment by LouiseBonnard** [comment]
Yep, currently this block is available for all types of payment but it is irrelevant when the order is paid by bank wire, cheque, cash-on-delivery or any other method unrelated to this information.

**Comment by colinegin** [comment]
We can close this issue as the fix has been done. See this issue for more info : https://github.com/PrestaShop/PrestaShop/issues/15827
