### ISSUE TITLE
SSL or cert config on PS upgrade servers, used by 1-click update module, is no longer supported by default on recent Linux distros

### ISSUE THREAD

**Issue by eriknuds** [PrestaShop/PrestaShop#15891]
SSL/TLS or certificate on upgrade servers seem to be incompatible with recent linux distros (Debian 10 Buster). This is used by 1-click update module, and updated secure systems can't download new PS versions and the upgrade module won't even be able to query about recent releases unless you figure out what's wrong and you are manually editing the SECLEVEL from 2 to 1 in /usr/llib/ssl/openssl.cnf on debian.

https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1

**Comment by eriknuds** [comment]
...instead of a most recent version, you will get the "You come from the future!" message.

**Comment by khouloudbelguith** [comment]
Hi @eriknuds,

Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by eriknuds** [comment]
Sure, here are the steps to reproduce:

Install or upgrade to Debian 10 (Buster)
Try PS 1-click upgrade.
Observe - it can't find version info or do an upgrade.
Change SECLEVEL from 2 to 1 in /usr/llib/ssl/openssl.cnf
Observe - 1-click upgrade works.

**Comment by khouloudbelguith** [comment]
@eriknuds, thanks for your feedback.
Could you please provide a screenshot about your server configuration.
You can find it in the BO => Advanced Parameters => Information.

Thanks!

**Comment by eriknuds** [comment]
I can't get to it right now, may be able to later, but as this issue is with the system wide openssl settings on the server it doesn't depend much on the PS config I would think. It seemed to be a problem with/without curl/url_fopen, given no site local overrides (if at all possible). Just try a Debian 10 (Buster) on LInode or Azure or a free virtual machine download with vmware or virtualbox, see if you can reproduce it out of the box.

**Comment by khouloudbelguith** [comment]
@eriknuds, I need to know what is the exact version PHP, did you use?

Thanks!

**Comment by eriknuds** [comment]
Hi,
this was latest 1.6 version - but as the problem is with the SSL system and the PrestaShop download servers or CDN network - and not the PS application - the PS version shouldn't matter.

**Comment by eriknuds** [comment]
Ah, version of PHP...both 7.0 and 7.3 had the same behavior. I know PS doesn't work perfectly with 7.3, but I tested and the behavior was the same.

**Comment by eriknuds** [comment]
BTW, a new Debian 10 install has PHP 7.3 by default, and it's a real problem that PS don't work perfectly with it. You can use PHP 7.0 quite easily on Debian 10, as it's in the default repository, but the PHP-mysql package is not I believe...so you have to add oldstable security update in sources.list to get it...so if you get into this situation it's a bit of a hassle. But in practive PS runs ok on 7.3 and you can reproduce the probem so you don't really have to mess with 7.0. Or you could try PS 1.7 as it will have the same problem using the systems openssl when accessing the PS download servers. As PHP 7.3 is default PHP on new Debian systems PS 1.7 must be able to run on that PHP version.

**Comment by khouloudbelguith** [comment]
@eriknuds, Next Major release PS1.7.7 will be compatible with PHP7.3, you can follow this ticket: #12461 (see details on http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/)

>but as the problem is with the SSL system and the PrestaShop download servers or CDN network - and not the PS application - the PS version shouldn't matter

So, it is not a PrestaShop core issue?
Thanks!

**Comment by eriknuds** [comment]
I believe it's a problem with the SSL or certificate setup on prestashops CDN or download servers, as explained in the first sentence of the bug report. IMHO the bug is an infrastructure bug (infrastructure which the 1-click update module depends on, and thus kind of a bug with the module).

**Comment by eriknuds** [comment]
This PS infrastructure issue effectively disables the 1-click update module on the most recent Debian stable version, and other Linux distros are likely to follow the same secure approach so the problem will spread if not fixed by fixing the PS download server infrastructure - I would think.

**Comment by eriknuds** [comment]
You don't even get an error about what is wrong even with debug settings on. The 1-click module just displays a blank version and can't upgrade.

**Comment by khouloudbelguith** [comment]
Ping @Quetzacoalt91 @PierreRambaud what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
I agree, there are problems with recent version. I'm also on Debian Buster and I'm unable to run the upgrade process.

**Comment by khouloudbelguith** [comment]
@PierreRambaud, thanks!
so, we need to add this bug to our bug roadmap? is it?

Thanks!

**Comment by eriknuds** [comment]
IMHO you need to escalate it to your infrastructure/operations team as no application change is required - but an infrastructure ssl and/or certificate issue requires fixing ASAP.

**Comment by eriknuds** [comment]
An application change is suggested - add check to see if the connection with download servers can be established in the 1-click module and/or fall back to no ssl, regular http download, preferably with a warning.

**Comment by djodjo3** [comment]
Hello @eriknuds, we've just performed some updates on our side that resolved the key exchange issue. Could you let us know if it's also resolved on your end? 
Thanks in advance!

**Comment by eriknuds** [comment]
I can't expirement on that server at the moment, maybe @PierreRambaud can verify?

**Comment by PierreRambaud** [comment]
@eriknuds We checked together with @djodjo3 and everything was ok on my machine. But we must be sure it's ok for you :)

**Comment by eriknuds** [comment]
Hi,
I won't be able to test this for a while so lets assume it's ok as it works for @PierreRambaud and we had the same system and symptoms. I have resolved the issue locally by setting the SECLEVEL from 2 to 1 and won't be able to mess with that for a while.

When I get a chance to test I'll reopen the issue if it still doesn't work for me, but don't wait for it;-)

**Comment by PierreRambaud** [comment]
Thanks @eriknuds for your feedback.
So feel free to reopen if something's falling again :)
