### ISSUE TITLE
Tax for shipping are duplicated when delivery slip is generated before invoice

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#15892]
Hello,

When the invoice is configured to be generated after the delivery slip, taxes for shipping will be duplicated in the invoice.

I found that Order::setDeliverySlip will call OrderInvoice::setInvoiceDetails and populate the order_invoice_tax table, even if it does not create any invoice.

Later when generating the order, Order::setInvoice will call once again OrderInvoice::setInvoiceDetails and adds the same data to order_invoice_tax. Et voilà !
**Steps to reproduce the issue:**
1. Install the COD module for example
2. Edit the status "Processing in progress"
![image](https://user-images.githubusercontent.com/16067358/66635549-c24cfa00-ec0f-11e9-941e-51fe365ddb91.png)
=> the invoice is configured to be generated after the delivery slip
3. Create Tax1 & Tax2 
4. Create a tax rule one after another with Tax1 & Tax2
5. Create a Carrier with this Tax rule created
5. Go to to the the BO => Orders => Invoices => Enable "tax breakdown"
6. Go to the FO => Create an order with a product & select the last carrier created & COD
7. Go to the BO => Order => Edit the status of the last order to payment accepted to generate the invoice
8. View Invoice 
9. See error
10. The total tax is incorrect also

**Additional information**
PrestaShop version: 1.7.4.0

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/16PcwejeH30dZ_bklQFkOqZGbJgbpEHlU/view
Thanks to check & feedback.

**Comment by cedricfontaine** [comment]
Maybe there is a difference in our configuration. In Quebec, price are not included taxes and we have 2 levels of taxes and we display the tax breakdown on the invoice.

**Comment by khouloudbelguith** [comment]
@cedricfontaine, your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/14646?

Thanks!

**Comment by cedricfontaine** [comment]
No it's not the same problem.

See duplicate in the shipping section. 
![Capture d’écran, le 2019-10-10 à 09 24 08](https://user-images.githubusercontent.com/3180112/66572935-db867580-eb3f-11e9-9f17-49a78a838ab9.png)

**Comment by khouloudbelguith** [comment]
@cedricfontaine, I created this cart rule
![image](https://user-images.githubusercontent.com/16067358/66575213-d7754a80-eb75-11e9-8b06-83739e87eb6b.png)
I used shipping & a product using the same tax rule.
![image](https://user-images.githubusercontent.com/16067358/66575327-068bbc00-eb76-11e9-81e6-a438708b6390.png)

In the invoice, it is OK
![image](https://user-images.githubusercontent.com/16067358/66575376-1acfb900-eb76-11e9-8f5d-42303dac1125.png)

Thanks!

**Comment by cedricfontaine** [comment]
Did you activate tax breakdown in the invoice setting ?

**Comment by khouloudbelguith** [comment]
@cedricfontaine, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/66635453-90d42e80-ec0f-11e9-94c6-5ac17b9401d8.png)
Steps to reproduce the issue:
1. Install the COD module for example
2. Edit the status "Processing in progress"
![image](https://user-images.githubusercontent.com/16067358/66635549-c24cfa00-ec0f-11e9-941e-51fe365ddb91.png)
=> the invoice is configured to be generated after the delivery slip
3. Create Tax1 & Tax2 
4. Create a tax rule one after another with Tax1 & Tax2
5. Create a Carrier with this Tax rule created
5. Go to to the the BO => Orders => Invoices => Enable "tax breakdown"
6. Go to the FO => Create an order with a product & select the last carrier created & COD
7. Go to the BO => Order => Edit the status of the last order to payment accepted to generate the invoice
8. View Invoice 
9. See error
10. The Tax total also is incorrect
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by cedricfontaine** [comment]
Thanks for the info.

**Comment by Eusebio100** [comment]
The solution may be easy if you don't need itemized taxes on shipping in delivery slip, this working on ps 1.6.
In override/classes/order/Orde.php:
` /**
     * This method allows to fulfill the object delivery slip with sales figures
     */
    protected function setDeliverySlipDetails($order_invoice)
    {
        if (!$order_invoice || !is_object($order_invoice)) {
            return;
        }

        $address = new Address((int)$this->{Configuration::get('PS_TAX_ADDRESS_TYPE')});
        $carrier = new Carrier((int)$this->id_carrier);
		
		if (Configuration::get('PS_ATCP_SHIPWRAP')) {
			$wrapping_tax_calculator = Adapter_ServiceLocator::get('AverageTaxOfProductsTaxCalculator')->setIdOrder($this->id);
            $tax_calculator = Adapter_ServiceLocator::get('AverageTaxOfProductsTaxCalculator')->setIdOrder($this->id);			
        } else {
			$wrapping_tax_manager = TaxManagerFactory::getManager($address, (int)Configuration::get('PS_GIFT_WRAPPING_TAX_RULES_GROUP'));
			$wrapping_tax_calculator = $wrapping_tax_manager->getTaxCalculator();
			$tax_calculator = $carrier->getTaxCalculator($address);
        }
		       
        $order_invoice->total_discount_tax_excl = $this->total_discounts_tax_excl;
        $order_invoice->total_discount_tax_incl = $this->total_discounts_tax_incl;
        $order_invoice->total_paid_tax_excl = $this->total_paid_tax_excl;
        $order_invoice->total_paid_tax_incl = $this->total_paid_tax_incl;
        $order_invoice->total_products = $this->total_products;
        $order_invoice->total_products_wt = $this->total_products_wt;
        $order_invoice->total_shipping_tax_excl = $this->total_shipping_tax_excl;
        $order_invoice->total_shipping_tax_incl = $this->total_shipping_tax_incl;
        $order_invoice->shipping_tax_computation_method = $tax_calculator->computation_method;
        $order_invoice->total_wrapping_tax_excl = $this->total_wrapping_tax_excl;
        $order_invoice->total_wrapping_tax_incl = $this->total_wrapping_tax_incl;
        $order_invoice->save();

       /* $order_invoice->saveCarrierTaxCalculator(
            $tax_calculator->getTaxesAmount(
                $order_invoice->total_shipping_tax_excl,
                $order_invoice->total_shipping_tax_incl,
                _PS_PRICE_COMPUTE_PRECISION_,
                $this->round_mode
            )
        ); */
        $order_invoice->saveWrappingTaxCalculator(
            $wrapping_tax_calculator->getTaxesAmount(
                $order_invoice->total_wrapping_tax_excl,
                $order_invoice->total_wrapping_tax_incl,
                _PS_PRICE_COMPUTE_PRECISION_,
                $this->round_mode
            )
        );
    }	
	
    /**
     * This method allows to generate first delivery slip of the current order 
     */
    public function setDeliverySlip()
    {
        if (!$this->hasInvoice()) {
            $order_invoice = new OrderInvoice();
            $order_invoice->id_order = $this->id;
            $order_invoice->number = 0;
            $this->setDeliverySlipDetails($order_invoice);
            $this->delivery_date = $order_invoice->date_add;
            $this->delivery_number = $this->getDeliveryNumber($order_invoice->id);
            $this->update();
        }
    }`

**Comment by florine2623** [comment]
This issue is fixed in PS 8.1.x. The tax break down is OK and not duplicated :

<img width="1014" alt="Screenshot 2023-10-25 at 17 06 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e8efc94a-6864-4457-b90b-90f42e7c2a5d">

I'm closing this issue.
