### ISSUE TITLE
Catalog product page gives error 500 after upgrade from 1.7.3 to 1.7.6

### ISSUE THREAD

**Issue by Modii** [PrestaShop/PrestaShop#15896]
Hello,

I can't access the product catalog page or edit any products after upgrading from 1.7.3.1 to 1.7.6.1

It gives me two fatal php errors.

The first exception: Twig\Error\RuntimeError

in src/PrestaShopBundle/Resources/views/Admin/layout.html.twig (line 34)
```

    layoutHeaderToolbarBtn is defined ? layoutHeaderToolbarBtn : [],

    layoutDisplayType is defined ? layoutDisplayType : '',

    showContentHeader is defined ? showContentHeader : true,

    headerTabContent is defined ? headerTabContent : '',

    enableSidebar is defined ? enableSidebar : false,

    help_link is defined ? help_link : ''

  )

  )) %}

{% import '@PrestaShop/Admin/macros.html.twig' as ps %}
![540031680_Skrmbillede2019-10-09kl_10_11_37 thumb png 2874b444df89df91cd24fbe6110088b7](https://user-images.githubusercontent.com/3637428/66559344-85bcc800-eb55-11e9-9aec-c1b930b42346.png)
![329378461_Skrmbillede2019-10-09kl_10_11_55 thumb png 79a22a63aa664f72380f8db9f579cacb](https://user-images.githubusercontent.com/3637428/66559345-86555e80-eb55-11e9-9a76-55be935b2247.png)


```
The second exception: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException

```
in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php (line 348)

                if ($lev <= \strlen($id) / 3 || false !== strpos($knownId, $id)) {

                    $alternatives[] = $knownId;

                }

            }

            throw new ServiceNotFoundException($id, null, null, $alternatives);

        }

    }

    /**

     * Returns true if the given service has actually been initialized.
 
```

I've tried disabling all modules one at a time and that did not help.

My php version is 7.1 and i've tried running 7.0 and 7.2 and it gives the same error.

I used the 1 click upgrade module to upgrade, it was upgraded to the latest version before i used it.

I have also updated the prestashop warehouse theme to the latest version according to the documentation, no issue with theme modules or the theme itself it seems.

I've gone through file permissions and made sure every folder in /modules and /themes has at least 755. 

I could do a full restore through cpanel, but i would like to try to avoid this, as i have had a few orders since the issue began 2 days ago.

I have used phppsinfo.php to check all php and mysql info and it all looks good as seen in my screenshots. 
![Skærmbillede 2019-10-10 kl  12 01 47](https://user-images.githubusercontent.com/3637428/66559499-c3b9ec00-eb55-11e9-91e7-a97a72930b82.png)
![Skærmbillede 2019-10-10 kl  12 01 37](https://user-images.githubusercontent.com/3637428/66559500-c3b9ec00-eb55-11e9-81d3-61925a934517.png)
![540031680_Skrmbillede2019-10-09kl_10_11_37 thumb png 2874b444df89df91cd24fbe6110088b7](https://user-images.githubusercontent.com/3637428/66559535-d2a09e80-eb55-11e9-9a05-d41396c634bc.png)
![329378461_Skrmbillede2019-10-09kl_10_11_55 thumb png 79a22a63aa664f72380f8db9f579cacb](https://user-images.githubusercontent.com/3637428/66559536-d2a09e80-eb55-11e9-8b9b-fd776d0fbb7e.png)

**Comment by rdy4ever** [comment]
I think you should download the latest version available for [relatedproducts](https://addons.prestashop.com/en/cross-selling-product-bundles/7942-related-products.html).
You should find it in your account, [here](https://addons.prestashop.com/en/customer-products.php).

**Comment by khouloudbelguith** [comment]
HI @Modii,

This issue occurs due to the `relatedproducts` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Modii** [comment]
Thank you, i checked compatibility and noticed it was compatible with 1.7.6.1 and that there was no available update in the prestashop BO for it.

It would be more intuitive if there was an indicator in the BO, even for paid module, that the module was out of date.

**Comment by khouloudbelguith** [comment]
@Modii, as you can see in your screenshot
![image](https://user-images.githubusercontent.com/16067358/66562100-29f53d80-eb5b-11e9-908f-0018c3907d2e.png)
it is related to your module.

Thanks!
