### ISSUE TITLE
Change "status" for some PrestaShop modules

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#15919]
For PrestaShop 1.7.7, some modules need to change the "status" they currently have according to their reviewed level of importance.

There are 2 different statuses: _native_ or _pushed by API_. 

For new native modules, some actions are needed: 
- publish the module on packagist 
- update the core (composer.json and composer.lock) with the module
- update the list of installed modules in the installer

And below are listed all modules which need a change of status or recently got a major upgrade:
 
- [x] **ps_crossselling** --> needs to become native (currently pushed by API)
- [x] **productcomments** --> needs to become native (currently pushed by API)
- [x] **blockreassurance** --> needs to be updated (major upgrade)
- [x] **ps_dataprivacy** --> needs to become native (currently pushed by API)

/ ! \ We must be careful and add a notification in the RGPD module to state that it duplicates with the Data Privacy module when installed. Here is the [issue](https://github.com/PrestaShop/psgdpr/issues/68).

**Comment by PierreRambaud** [comment]
We must update productcomments or blockreassurance.
Both are not compatible together :)
https://github.com/PrestaShop/productcomments/blob/master/composer.json#L17 https://github.com/PrestaShop/blockreassurance/blob/master/composer.json#L17

PIng @jolelievre @Progi1984

**Comment by Progi1984** [comment]
@jolelievre productcimments must be updated to 0.2.0. It's the release that I asked to Guzzle's team.

**Comment by PierreRambaud** [comment]
Thanks to @jolelievre for updating productcomments module.
we are waiting for a new version on packagist before updating #16310
