### ISSUE TITLE
New product page in blank in prestashop1.7.6

### ISSUE THREAD

**Issue by Prem-lmx** [PrestaShop/PrestaShop#15911]
Hai,
i'm use the prestashop version1.7.6..
click the new product page but still blank page..only,
please support ....
url :sumangalijewellers.in
![image](https://user-images.githubusercontent.com/52959027/66626981-d4cb3180-ec17-11e9-8e08-280dc6414e8c.png)
![image](https://user-images.githubusercontent.com/52959027/66633651-f08b0380-ec28-11e9-83e4-6f456598986a.png)

Thanks

**Comment by khouloudbelguith** [comment]
Hi @Prem-lmx,

Thanks for your report.
Have you an override of the class `SearchControllerCore.php`?

Thanks!

**Comment by Prem-lmx** [comment]
Hi @khouloudbelguith ,
Thanks for your report.
what write in over of the class SearchControllerCore.php?

Thanks!

**Comment by khouloudbelguith** [comment]
@Prem-lmx, no, 
Overriding is a way to “override” class files and controller files
An override can be introduced by a custom module
In this path for example  https://github.com/PrestaShop/PrestaShop/tree/develop/override/controllers/front

Thanks!
