### ISSUE TITLE
Impossible to disable Debug mode

### ISSUE THREAD

**Issue by SignalBip** [PrestaShop/PrestaShop#15914]
Hello,

Our store is on  1.7.6.0. Since activation of the Debug mode, we can disable it anymore.
It causes some Back-office menus to display ERROR 500.

We have tried two possible solutions without any success: 
1. delete Prestashop cache manually by deleting the "dev" and "prod" files in the "app" folder.
2. replace the "defines.inc.php" file.

Thank you for your help.

**Comment by khouloudbelguith** [comment]
Hi @SignalBip,

Have you the right permissions for your files.
They are writable?

Thanks!

**Comment by SignalBip** [comment]
Hello,

Thank you for your reply, yes they are writable.

**Comment by khouloudbelguith** [comment]
@SignalBip,

>replace the "defines.inc.php" file.

Did you replaced this 

```
if (!defined('_PS_MODE_DEV_')) {
    define('_PS_MODE_DEV_', false);
}
```
by this?
```
if (!defined('_PS_MODE_DEV_')) {
    define('_PS_MODE_DEV_', true);
}
```

Thanks!

**Comment by SignalBip** [comment]
It is on "false", we changed it on "true" and nothing changes.

**Comment by khouloudbelguith** [comment]
@SignalBip, could you please provide us the log file into the path `Project_Folder/var/logs`.

Thanks!

**Comment by SignalBip** [comment]
[logs.zip](https://github.com/PrestaShop/PrestaShop/files/3716978/logs.zip)

**Comment by khouloudbelguith** [comment]
@SignalBip, you have errors relted to the cache
>[2019-10-11 11:54:48] php.CRITICAL: Fatal Compile Error: ContainerVhrmeiq\appDevDebugProjectContainer::load(): Failed opening required '/home/signalbiyc/signalbipv2/var/cache/dev/ContainerVhrmeiq/getPrestashop_Core_Localization_Locale_RepositoryService.php' (include_path='/home/signalbiyc/signalbipv2/vendor/pear/pear_exception:/home/signalbiyc/signalbipv2/vendor/pear/console_getopt:/home/signalbiyc/signalbipv2/vendor/pear/pear-core-minimal/src:/home/signalbiyc/signalbipv2/vendor/pear/archive_tar:.:/usr/local/php7.2/lib/php') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: ContainerVhrmeiq\\appDevDebugProjectContainer::load(): Failed opening required '/home/signalbiyc/signalbipv2/var/cache/dev/ContainerVhrmeiq/getPrestashop_Core_Localization_Locale_RepositoryService.php' (include_path='/home/signalbiyc/signalbipv2/vendor/pear/pear_exception:/home/signalbiyc/signalbipv2/vendor/pear/console_getopt:/home/signalbiyc/signalbipv2/vendor/pear/pear-core-minimal/src:/home/signalbiyc/signalbipv2/vendor/pear/archive_tar:.:/usr/local/php7.2/lib/php') at /home/signalbiyc/signalbipv2/var/cache/dev/ContainerVhrmeiq/appDevDebugProjectContainer.php:1709)"} []

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) and try to run those command lines to remove the cache:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by SignalBip** [comment]
Thank you for your reply.
Our developer tries to run the command line concerning /bin/console but it is not recognized. She's on Mac.

**Comment by khouloudbelguith** [comment]
@SignalBip, All cache files are stored in a single cache/ directory located in the var/cache/ directory.
So, to clear the cache, you can just remove all the files and directories under cache/. And Symfony is smart enough to re-create the directory structure it needs if it does not exist.

Thanks!

**Comment by SignalBip** [comment]
The folders in var/cache have been successfully deleted, the thing we cannot do is to run the "commande lines":
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod

The error is /bin/console does not exist.

Even after cache deletion, disabling debug mode cannot be done.

Thansk again.

**Comment by khouloudbelguith** [comment]
@SignalBip, you need to run those commands under your `Project_Folder` path.

Thanks!

**Comment by SignalBip** [comment]
Hello @khouloudbelguith 
I have run the commands in the Project_folder path and deleted the folders dev nd prod in var/cache, then I had tried to disable debug mode from the backoffice, and it still isn't working

Can you please help
Thank you for your support

**Comment by khouloudbelguith** [comment]
@SignalBip,
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by SignalBip** [comment]
Hello, thanks again for your help.
Here it is: http://signalbip.com/phppsinfo.php

**Comment by khouloudbelguith** [comment]
@SignalBip, I am redirected to an incorrect page.
you need to upload this file: https://github.com/PrestaShop/php-ps-info/blob/master/phppsinfo.php on your server.
For example, download this file & unzip it on your server.
[test.php.zip](https://github.com/PrestaShop/PrestaShop/files/3869983/test.php.zip)
You should upload your file to the exact directory you want to test.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/test.php, replacing example.com with your own domain name.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @SignalBip,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
