### ISSUE TITLE
Module.php calls undefined function uninstallTabs()

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15927]
**Describe the bug**
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/Module.php#L397

At line 394 of the file Module.php, Module.php calls undefined function uninstallTabs(). This is triggered when .PrestaShop fails to install a module.

We need to understand why is it (I guess it's a bad deletion) and see what must be done: re-create the function or remove its call.

PrestaShop version: develop

**Comment by khouloudbelguith** [comment]
Related to this: https://github.com/PrestaShop/PrestaShop/issues/15002

Thanks!

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/25533
