### ISSUE TITLE
Passwords in Welcome emails

### ISSUE THREAD

**Issue by Talw3g** [PrestaShop/PrestaShop#15922]
**Description**
The welcoming email sent when a user creates an account contains the username AND password in clear text. This means passwords are stored as clear text in the db, which is a serious security risk !

**To Reproduce**
Simply create an account

**Comment by kpodemski** [comment]
What? :D Password are not stored in plain text... you can check it in database, table PREFIX_customer,

about an e-mail with registration confirmation... what version of PrestaShop you use?

**Comment by Talw3g** [comment]
I don't personally use PrestaShop, but I created an account on 2 websites that use it... and both sent me the same welcome email with my credentials in plain text !
I assumed it came from PrestaShop, but I don't know which version.

**Comment by kpodemski** [comment]
Ok, don't worry, passwords are not stored in plain text, also in newest versions of PrestaShop password is no longer sent after creating an account

**Comment by PierreRambaud** [comment]
By newer versions, he said, every versions that are over two or three years old 😅 
 https://github.com/PrestaShop/PrestaShop/pull/5889

**Comment by khouloudbelguith** [comment]
Hi @Talw3g,

There is no password displayed in the PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/66737614-bc078980-ee6c-11e9-8660-274b5abb6bd2.png)
It is fixed with PS1.7 fixed with this PR: #5889
If you are using the PS1.6, it is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/8564
Thanks to check & feedback.

**Comment by PierreRambaud** [comment]
Since it's related to an old PrestaShop version, and the reporter is not the owner of the websites, I close this issue.
