### ISSUE TITLE
Translate any module - 500 Internal Server Error

### ISSUE THREAD

**Issue by levothanhhong** [PrestaShop/PrestaShop#15924]
**Describe the bug**
When I access to translate for any module, I received an error message:

> Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Log error: 
> [2019-10-14 11:02:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require_once(): Failed opening required '.../sources/modules/fieldtestimonials/fieldtestimonials.php' (include_path='.../vendor/pear/pear_exception:.../vendor/pear/console_getopt:.../vendor/pear/pear-core-minimal/src:.../vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear')" at .../src/Adapter/Module/Module.php line 360 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require_once(): Failed opening required '.../sources/modules/fieldtestimonials/fieldtestimonials.php' (include_path='.../vendor/pear/pear_exception:.../vendor/pear/console_getopt:.../vendor/pear/pear-core-minimal/src:.../vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') at .../src/Adapter/Module/Module.php:360)"} []

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.20
Server: Hostinger

**Comment by khouloudbelguith** [comment]
HI @levothanhhong,

This issue occurs due to the `fieldtestimonials` module.
Have you tried to contact the module author about this issue, thanks to check with them & feedback?

**Comment by levothanhhong** [comment]
Hello @khouloudbelguith 
This issue occurs on the all module. (100% module, eg: Banner, Merchant Expertise,...)

**Comment by khouloudbelguith** [comment]
@levothanhhong, when you try to translate any other module, what is the exact exception displayed?
Can you provide me a screenshot.

Thanks!

**Comment by levothanhhong** [comment]
Hello @khouloudbelguith 
It's hard to understand, right now, it all works normally
Earlier, it occurs on all modules

Thanks for your support,
Best regards.

**Comment by khouloudbelguith** [comment]
@levothanhhong, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
