### ISSUE TITLE
Additional shipping not adding in cart

### ISSUE THREAD

**Issue by nateBitworks** [PrestaShop/PrestaShop#15920]
Since upgrading to version 1.7.5.2 products that contain "additional shipping" are not adding the additional shipping within the cart, nor charging the customer for it.

The only shipping that is charged is the carriers shipping charge.

**Comment by khouloudbelguith** [comment]
Hi @nateBitworks,

Thanks for your report.
Is it about the shipping fees?
![image](https://user-images.githubusercontent.com/16067358/66664447-d4995900-ec4c-11e9-9d93-9eaf83a234d7.png)

Thanks!

**Comment by nateBitworks** [comment]
Yes. It is not adding those fees

**Comment by khouloudbelguith** [comment]
@nateBitworks, I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
Your carrier is not free & it is using a tax? is it?
https://drive.google.com/file/d/1IAxdvfH9ix7_ORmDyE66fhSGXpu9inhx/view

Thanks!

**Comment by nateBitworks** [comment]
I have tried in both versions. My live site is using 1.7.5.2 and my dev site is 1.7.6.1. I have tried with including tax and excluding tax. And the carrier does not use tax.

**Comment by khouloudbelguith** [comment]
@nateBitworks, 
> And the carrier does not use tax.

The shipping fees is applied If a carrier has a tax, it will be added to the shipping fees. It does not apply to free shipping.

Thanks!

**Comment by nateBitworks** [comment]
![image](https://user-images.githubusercontent.com/56446569/66673777-ef58d700-ec26-11e9-9eb6-07481124e20f.png)

Still no taxes added after I added the tax rate to the carrier.

**Comment by nateBitworks** [comment]
That is the shipping cost without the $15 additional shipping not adding.

**Comment by khouloudbelguith** [comment]
@nateBitworks, could you please confirm these steps:
1. The shipping fees is well updated in the Product Page => Shipping Tab
![image](https://user-images.githubusercontent.com/16067358/66747297-7a82d880-ee84-11e9-9f3b-fd86a947012f.png)
2. The carrier used is not free
![image](https://user-images.githubusercontent.com/16067358/66747478-efeea900-ee84-11e9-8fd3-245e40c489c0.png)
3. the Tax for the shipping is not null
![image](https://user-images.githubusercontent.com/16067358/66747721-7acfa380-ee85-11e9-985e-0482b922ea41.png)

Thanks!

**Comment by nateBitworks** [comment]
Hello, thanks for reply. I have all those things set:
![additional_ship](https://user-images.githubusercontent.com/56446569/66765303-3d611b00-ee71-11e9-893c-b28e8da36654.PNG)
![additional_ship2](https://user-images.githubusercontent.com/56446569/66765304-3df9b180-ee71-11e9-9433-ae1da8269a72.PNG)

**Comment by khouloudbelguith** [comment]
@nateBitworks,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nateBitworks** [comment]
Thank you, I will put it together today or tomorrow AM.

**Comment by khouloudbelguith** [comment]
@nateBitworks, thanks!
Waiting for your feedback.

**Comment by nateBitworks** [comment]
Live version:
![image](https://user-images.githubusercontent.com/56446569/66851865-533e1100-ef41-11e9-92ce-f66e100fb609.png)


steps to reproduce:
Add this product to your cart:
https://www.trailerpartssupplies.com/trailer-fenders/2542-tie-down-engineering-black-plastic-fender-8-to-12-wheels.html
When pop up comes up click "Proceed to checkout" 
Click "proceed to checkout"
Create a test name/address
Select ups ground
The shipping cost SHOULD be more than 15 dollars because this item has additional shipping of 15 dollars
[trailer_log.txt](https://github.com/PrestaShop/PrestaShop/files/3730517/trailer_log.txt)

Let me know if anything else is need.

**Comment by khouloudbelguith** [comment]
@nateBitworks, in your log file, you have some warnings related to your modules `hitfedex` &  `authorizepaymentgateway`.

If you try to use a carrier created manually from the Back office, the shipping price, it is ok?

Thanks!

**Comment by nateBitworks** [comment]
I will try to create a carrier manually. Authorize is payment.

**Comment by khouloudbelguith** [comment]
@nateBitworks, thanks!
Waiting for your feedback.

**Comment by nateBitworks** [comment]
I'm sorry for the delay. I created a manual carrier and it adds the additional shipping. Is there a way to add to 3rd party shipping modules?

**Comment by khouloudbelguith** [comment]
@nateBitworks, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
@nateBitworks, feel free to open a new one when needed.

Thanks!
