### ISSUE TITLE
Add to cart Modal - Impossible to change text from tpl

### ISSUE THREAD

**Issue by ElderTugBoat786** [PrestaShop/PrestaShop#15925]
**Describe the bug**
I attempt to remove the word "gratis" on add to cart modal but though I have attemp to modify the ps_shopingcart.tpl nothing appears.

**To Reproduce**
1. Go to products'
2. Click on add to cart

**Screenshots**
![image](https://user-images.githubusercontent.com/38555796/66742210-756b5c80-ee77-11e9-9fdb-dff76119bba9.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.1

**Comment by khouloudbelguith** [comment]
Hi @ElderTugBoat786,

You need to navigate to your BO => International => Translations => 
Type of translation => Themes translations
Select your theme => your current theme
Select your language, search for "Free" expression (Gratis in your case)
You need to edit the expression into Shop > Theme > Checkout 
![image](https://user-images.githubusercontent.com/16067358/66743423-24109c80-ee7a-11e9-9108-9c39c7e610a8.png)
Fo
![image](https://user-images.githubusercontent.com/16067358/66743446-38ed3000-ee7a-11e9-9002-ca888553d87e.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, PrestaShop is not compatible with PHP 5.1
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Thanks!

**Comment by ElderTugBoat786** [comment]
Hi @khouloudbelguith 
The correct version of PHP is 5,6.
I would remove the word "gratis" and not change the translation. Is't possible?

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, something like this?
![image](https://user-images.githubusercontent.com/16067358/66744492-db0e1780-ee7c-11e9-87b5-6dfc84c808f0.png)

Thanks!

**Comment by ElderTugBoat786** [comment]
@khouloudbelguith  yup, but only if not are any shipping cost

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, yes only when you have free shipping? is it?

Thanks!

**Comment by ElderTugBoat786** [comment]
@khouloudbelguith Yup!

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, you need just to follow this comment & replace the expression of the "Free" with only space & save.
![image](https://user-images.githubusercontent.com/16067358/66745915-a00de300-ee80-11e9-90d9-28bd7c47d559.png)

Thanks to check & feedback.

**Comment by ElderTugBoat786** [comment]
Thanks, 
I changed what I needed!

**Comment by khouloudbelguith** [comment]
@ElderTugBoat786, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
