### ISSUE TITLE
ps_facetedsearch filtering by color doesn't show any result

### ISSUE THREAD

**Issue by LucaMozzo** [PrestaShop/PrestaShop#15928]
**Describe the bug**
I have a category in which I show filters for features, among which the color.
The filter looks like this:
![image](https://user-images.githubusercontent.com/8259971/66750126-87eb9300-ee83-11e9-81c6-872c071f763b.png)
However, when I press on, say, *gold*, I get no results (even though there are some, if I manually traverse the entire list).

Additionally, filters on custom attributes (so all of them except filtering by categories and brands, which are fine), show the number of pages instead of the number of products.
For instance
![image](https://user-images.githubusercontent.com/8259971/66750335-1b24c880-ee84-11e9-8ba9-917be2ff64e5.png)
shows 3 per type, but if I click the checkbox, I see "1-12 out of 33 products shown" and a list of 33 products.

I am using a custom theme, but the developers told me to escalate the request as the problem seems to happen on the classic theme too.

**To Reproduce**
I have a top level category with some subcategories in it, and all these products share some of these attributes. I opened the page of the top level category (`/index.php?id_category=4&controller=category`).

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @LucaMozzo,

What is the exact version of the module ps_facetedseach did you use?

Thanks!

**Comment by LucaMozzo** [comment]
@khouloudbelguith It's 3.1.0 thanks

**Comment by khouloudbelguith** [comment]
@LucaMozzo, The last release is V3.3.0.
![image](https://user-images.githubusercontent.com/16067358/66762310-06592c80-eea6-11e9-97d6-5e2c248a374c.png)
Thanks to upgrade your module & configure it by editing the template & rebuilding the entire price index & building attributes & features indexes & clearing the cache.
![image](https://user-images.githubusercontent.com/16067358/66762400-37396180-eea6-11e9-8826-5948e5e78713.png)
Thanks!

**Comment by LucaMozzo** [comment]
Thanks, that will solve!

**Comment by khouloudbelguith** [comment]
@LucaMozzo, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
