### ISSUE TITLE
Can't translate or disable [I agree to the terms and conditions] on guest checkout 

### ISSUE THREAD

**Issue by PrestaNewbie** [PrestaShop/PrestaShop#15923]
Hello,
i can't translate or find where to translate (I agree to the terms and conditions and the privacy policy) on first checkout page (guest-login.tpl i think). Any ideas?
![how to disable](https://user-images.githubusercontent.com/56392393/66707683-0db8f280-ed4d-11e9-93a9-fdcbd4decb42.PNG)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @PrestaNewbie,

You need to navigate to your BO => Modules => Module Manager => search for the `psgdpr` module => configure it => Click on the third Tab" Consent checkbox customization" & edit the "Consent request message" for the "Account creation form".

![image](https://user-images.githubusercontent.com/16067358/66738881-c2e3cb80-ee6f-11e9-8415-5dd55e815472.png)

Thanks to check & feedback.

**Comment by PrestaNewbie** [comment]
Thank You, very much!

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, you are welcome!
Feel free to open a new one needed.

Thanks!
