### ISSUE TITLE
Creating a once deleted currency causes duplicate rows in database

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#15934]
**Describe the bug**
When a currency is added in PrestaShop it is impossible to add it a second time,  thus it prevent having duplicate
However if you delete a currency and then add it again a new row is inserted and the former one is still present with its deleted column set to 1 (soft delete)
This means the database has duplicated rows, and that different orders with the same currency do not use the same one in database

**To Reproduce**
1. Go to Internationalisation > Localization > Currencies
2. Add a new currency (for example AUD)
3. Go back to the currencies list and delete the newly created currency
4. In your database you will see that the row is still present but the deleted column is now equal to `1`
5. Recreate this same currency (AUD)
6. Now if you check you database will see two rows for the same AUD currency (one is deleted, not the other)

**Expected behaviour**
Rather than adding a new row in database, the previously deleted one should be updated (use the data from the creation form to update its content) AND most importantly its deleted value should be revert back to 0 thus avoiding creating duplicate rows

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

Same issue with PS1.7.5.2 & PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/66757864-5b447500-ee9d-11e9-8b52-c0b589d9a612.png)

Thanks!

**Comment by colinegin** [comment]
@matthieu-rolland @jolelievre what's the status of this issue ?

**Comment by jolelievre** [comment]
It's done, but it needs to be rebased I'm on it

**Comment by Progi1984** [comment]
Fixed by #16287

**Comment by SD1982** [comment]
ping @matthieu-rolland 
This PR : [#16287 ](https://github.com/PrestaShop/PrestaShop/pull/16287) seems to have corrected the described bug in this issue but another scenario reproduces the error.

Step to reproduce : 

- Go to Internationalisation > Localization > Currencies
- Add a new currency (for example USD)
- Go back to the currencies list and delete the newly created currency
- Download the "added and deleted" curreny localisation pack
- A second row in database is created 

![#ISSUE #15934 Creating a once deleted currency causes duplicate rows in database](https://user-images.githubusercontent.com/40635814/74450145-ed757d80-4e7d-11ea-8f33-9db6d64cd57d.png)

**Comment by jolelievre** [comment]
Nice catch @SD1982 !!
But since it's another scenario I suggest creating a new issue, something like "Importing a currency from a localization pack duplicates a currency in database when previously deleted"

Indeed this is another feature related to localisation pack so it doesn't use the new handlers used in the dedicated form

**Comment by SD1982** [comment]
ping @khouloudbelguith

**Comment by khouloudbelguith** [comment]
Issue created here: https://github.com/PrestaShop/PrestaShop/issues/17661
