### ISSUE TITLE
Badly configured vouchers can result in them being displayed by customer although they should not

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15938]
**Describe the bug**
In the Back-Office, when a cart rule is created, and has **both** a customer condition (= should be available only for customer A) AND a customer group condition (= shoulb be available only for customer group B) then this voucher visibility will be wrongly computed and will be displayed to customer.

**To Reproduce**
1. Create a new customer group GA
2. Create a new customer C1 with Group access only GA
3. Create a new customer C2 with Group access only Customer & visitor & Guest
4. Create a cart rule CR1
4.1 this cart rule is only limited to a single customer ( pub@prestashop.com)
4.2 this cart rule have a restriction: customer group selection
4.3 unselected groups: GA
4.4 selected groups : Customer / visitor / Guest
5. Create another cart rule CR2 a restriction: customer group selection (selected groups : Customer / visitor / Guest)

In FO if we are signed with the customer C2 the cart rule CR1 is displayed but not applied ( In fact it should not be displayed because it is just limited to pub@prestashop.com)

PS: In the list voucher in FO, if we are signed with the customer C2 the cart rule is displayed =>, In fact, it should not be displayed because it is just limited to pub@prestashop.com)

**Screenshots**
Video record
https://drive.google.com/file/d/1lUySJIMwDVZJ_UxFsL548g8ZHP-cw8gL/view

**Additional information**
PrestaShop version: develop

**Comment by matks** [comment]
**Solution to implement**
In the Back-Office,
If I select a specific customer, then **I cannot** add a restriction on customer group (the checkbox is disabled).
If I select customer group restriction, **I cannot** add a specific customer (the field is disabled)

Because having both conditions does not make sense

**Comment by matks** [comment]
Please note that the steps above might not work anymore since the merge of https://github.com/PrestaShop/PrestaShop/pull/15903 as it hides (as a workaround) the bad vouchers. This was done to ensure that, even after the BO behavior has been fixed, the vouchers already saved in database are not displayed.

**Comment by matks** [comment]
This issue is the next step to solve https://github.com/PrestaShop/PrestaShop/issues/13002

**Comment by Hlavtox** [comment]
@matks Try my fix from this comment, will work. https://github.com/PrestaShop/PrestaShop/issues/13002#issuecomment-532876260

**Comment by matks** [comment]
> @matks Try my fix from this comment, will work. [#13002 (comment)](https://github.com/PrestaShop/PrestaShop/issues/13002#issuecomment-532876260)

Thanks !

However I have the same opinion as you:

> Commenting out $sql .= ' UNION (SELECT '.$sql_part1.' WHERE cr.group_restriction = 1 '.$sql_part2.')'; from CartRule.php seems to fix it, but I don't know what else it could break. Customer can then see only his vouchers, the group restrictions work as they should.

I don't know either what else could break, and currently we have no reliable way to make sure that we break nothing.
The automated testing coverage of Cart Rules is not wide and deep enough to ensure that a modification of a critical function such as `CartRule::getCustomerCartRules()` has no side-effects. That is why we cannot use this mean to solve this issue 😢 .

This is another symptom of one of the [pain points](http://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points/#global-state) of the code.

We have a long-term plan to fix this global issue and its symptoms but this will take longer.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16088
