### ISSUE TITLE
Friendly url not create in some case.

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#15936]
Hello,

I create a new product with two languages (EN and FR for example)
I write the title in EN but not in FR
When I save the product page, the EN title is copy in FR title

But the Friendly-url (in SEO tab) is only create for EN, not for FR even if the title is copy from EN.

PHP 7.2
PS 7.5.0

## SPECS

When many languages are installed, if I fill the product name only for the default language, I want the friendly-url field to be automatically filled in other languages with the same content as in default language (like that works for the product name)

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
I have the same behavior as PS1.7.5.2 & PS1.7.6.1.
In fact, when we create a product & save it => in the FO when the second language is selected => the URL of the product has an empty friendly URL: http://shop.com/1761/fr/accueil/30-.html
If we click on the Preview button after creating a new product, the friendly URL in the second language will be automatically generated.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement, the friendly URL will be automatically generated in all languages.

Related to: https://github.com/PrestaShop/PrestaShop/issues/14984

**Comment by MatShir** [comment]
It seems to be fixed on 8.1 new product page :)
