### ISSUE TITLE
Shipping cost calculation difference based on a way of defining free shipping

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15945]
**Describe the bug**
If you want to set free shipping on orders above x amount, you have two options. Setting it via Shipping > Configuration or via carrier ranges.
HOWEVER, there is a difference in a way Prestashop calculates the eligibility for free shipping.

Also, it creates confusions in some COD modules, which apply some kind of fee depending of order amount.

**Setting free shipping globally**
If you set free shipping in Shipping > Configuration, Prestashop calculates shipping costs/free shipping by counting total products BEFORE applying discounts.

**Setting free shipping**
If you set free shipping by defining 0 cost above some amount, Prestashop calculates shipping costs/free shipping by counting total products AFTER applying discounts.

Which way is correct? This should be unified or selectable in Prestashop configuration.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

>If you want to set free shipping on orders above x amount, you have two options. Setting it via Shipping > Configuration or via carrier ranges.

In fact, there are three options.
1. Shipping > Configuration
![image](https://user-images.githubusercontent.com/16067358/66816821-022b1e80-ef3b-11e9-94b0-671ea0a172a3.png)
There is alert info, that "Coupons are not taken into account when calculating free shipping."
2. Carrier ranges
![image](https://user-images.githubusercontent.com/16067358/66816914-30106300-ef3b-11e9-9f17-0de35880018e.png)
3. A voucher free shipping
3.1 ![image](https://user-images.githubusercontent.com/16067358/66817091-74036800-ef3b-11e9-8e1a-59afa85ec532.png)
3.2 ![image](https://user-images.githubusercontent.com/16067358/66817107-7b2a7600-ef3b-11e9-8eb0-008b5ca39e1d.png)
In this case, free shipping above x amount will be applied when a discount is applied

There are different settings.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
