### ISSUE TITLE
Jquery-migrate generates many messages in the console

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#15943]
Since upgrading jquery and adding jquery-migrate, we have many warning logs in the console:

**Screenshots**
![Capture d’écran 2019-10-14 à 15 15 24](https://user-images.githubusercontent.com/1784781/66766727-19bcc580-eeaf-11e9-94cd-d3151c5f7cfc.png)

**Questions needing answers**

Should we remove them? Should it be kept here? Should we display it but only in dev environment ? If so, how is this done following best practices ?

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by Progi1984** [comment]
@matthieu-rolland It seems that it's the normal behavior with the use of a development version : https://github.com/jquery/jquery-migrate#debugging. Else you can use `jQuery.migrateMute`.

**Comment by PierreRambaud** [comment]
We mustn't use `jQuery.migrateMute`. Like every deprecated messages we must do our best to update our code and always use latest functions. 
This only mean we have some js codes that need to be updated :sweat_smile:

**Comment by matthieu-rolland** [comment]
@PierreRambaud that's the question, do we consider that those messages should be displayed even in production ?

**Comment by PierreRambaud** [comment]
I think yes, it's related to the front and only available in console, which means you're watching "js logs".
It will force everyone to update dependencies and fix it, instead of hiding them.
But maybe we need to have @eternoendless' feedbacks

**Comment by eternoendless** [comment]
Can this be enabled in dev mode and disabled in prod mode?
Do the deprecation messages only appear if the deprecated functions are used? In that case, we must update our usage of deprecated functions.

**Comment by PierreRambaud** [comment]
We should be able to use: https://github.com/jquery/jquery-migrate/blob/master/src/migratemute.js

**Comment by NeOMakinG** [comment]
> Can this be enabled in dev mode and disabled in prod mode?
> Do the deprecation messages only appear if the deprecated functions are used? In that case, we must update our usage of deprecated functions.

it looks like deprecated messages appears even if we don't use these functions, tried to find a "delegate" function use on FO core and classic files, couldn't find anything

BTW, we should maybe check every deprecated messages, in order to be sure we don't use any function that is deprecated!

**Comment by matthieu-rolland** [comment]
> > Can this be enabled in dev mode and disabled in prod mode?
> > Do the deprecation messages only appear if the deprecated functions are used? In that case, we must update our usage of deprecated functions.
> 
> it looks like deprecated messages appears even if we don't use these functions, tried to find a "delegate" function use on FO core and classic files, couldn't find anything
> 
> BTW, we should maybe check every deprecated messages, in order to be sure we don't use any function that is deprecated!

Definitely, maybe we can plan this for 1.7.8 ? 

Because we will upgrade jquery to the next minor version. Dealing with these deprecations is probably not urgent for 1.7.7, and we're short on time for the 1.7.7 release...

**Comment by Progi1984** [comment]
Fixed by #20738
