### ISSUE TITLE
Error with PS 1.7.4 with PHP 7.1

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#15947]
Since my original post (https://github.com/PrestaShop/PrestaShop/issues/14793) I discovered that it was the Redis module that caused problems with saving any changes made in a product. I also discovered that the PHP version was end-of-life and also the SQL version needed updating. Perhaps the combination Redis-module, PHP version and MySQL version was causing the problem.
My shop is on PS 1.7.2.4 , I have updated MySQL to 5.7.27 and available PHP versions are 5.4, 5.5, 5.6, 7.0, 7.1, 7.2 and 7.3
The PHP compatibility chart shows that the recommended PHP version for PS 1.7.4 is 7.1 however I get problems in back office when I want to open products or order details:
Notice on line 4603 in file /home/....../public_html/....../app/cache/dev/classes.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php71) failed: Permission denied (13)_
When I scale back to PHP 5.6 this problem is gone. Then I only get error:
Notice: Memcache::get(): Server 127.0.0.1 (tcp 11211) failed with: Connection refused (111) in /home/...../public_html/......./classes/cache/CacheMemcache.php on line 94_
but webshop works fine except for the Memcaching.
One thing I noticed is in Advanced Parameters > Information > Changed/missing files have been detected: Missing is ".eslintrc.json".

Why does it not work with PHP 7.1 ?

![error-products](https://user-images.githubusercontent.com/53129699/66785965-1a6d5000-eedf-11e9-80e6-5b35afb59dc4.PNG)
![AdvancedParameters-Information](https://user-images.githubusercontent.com/53129699/66785985-2822d580-eedf-11e9-86d3-560425520e26.png)

**Comment by khouloudbelguith** [comment]
Hi @frevab,

Thanks for your report.
>I discovered that it was the Redis module that caused problems with saving any changes made in a product

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.

>The PHP compatibility chart shows that the recommended PHP version for PS 1.7.4 is 7.1

PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
PrestaShop 1.7 works perfectly with PHP 7.1.
In fact, all contributions are tested automatically with PHP 5.6, 7.0 and 7.1. and PrestaShop 1.7.4 is also tested with PHP 7.2.

About your exception, it is a permission issue, thanks to give the right access to your files & try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by matks** [comment]
> Why does it not work with PHP 7.1 ?

From the error message you get, it does not seem to be a php 5.6 VS php 7.1 issue. It looks like your php 5.6 is not configured the same way than your php 7.1 and this is why you have permission issues.

I suggest you check with your host provider and ask him to have identical configuration for php 5.6 and php 7.1 😉

**Comment by khouloudbelguith** [comment]
Hi @frevab,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
