### ISSUE TITLE
Docker compose cp: cannot stat '/tmp/data-ps/prestashop/*'

### ISSUE THREAD

**Issue by smartsoftbox** [PrestaShop/PrestaShop#15941]
docker-compose up 

**error message**
Reapplying PrestaShop files for enabled volumes ...
cp: cannot stat '/tmp/data-ps/prestashop/*': No such file or directory

**To Reproduce**
1. chown -hR www-data:www-data ./prestashop
2. git clone https://github.com/PrestaShop/PrestaShop.git
3. cd prestashop
4. docker-compose up

**Additional information**
docker
Docker version 19.03.2, build 6a30dfc
docker-compose
docker-compose version 1.24.1, build 4667896b

**Comment by PierreRambaud** [comment]
Should be ok if you use your primary Linux user, if you configuration is different, you must create your own docker-compose.yml file with your configuration.
https://github.com/PrestaShop/PrestaShop/pull/15942
