### ISSUE TITLE
Impossible to delete categories in BO - No errors, simply nothing happens

### ISSUE THREAD

**Issue by Jackpera** [PrestaShop/PrestaShop#15949]
**Describe the bug**
Once I create a category in the backoffice, if I click on the three dots next to it at the end, nothing happens. Debug mode enabled, but any message reported. Checked console and logs, but nothing. Any idea

**To Reproduce**
1. Go to Catalog > Categories
2. Click on the three dots at the bottom of the category
3. Nothing happens

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Jackpera,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1m0i-wTIRXu-SGJIZlg5tq_EyJGrJ0oPt/view
Is this a fresh install or upgrade from a previous PrestaShop version?
What is the exact language/country did you used during the install?

Thanks!

**Comment by Jackpera** [comment]
It's a fresh install from the hosting provider (Ionos). 

We installed it in Italian.

I can provide you login details if you want to reproduce. 

The worst thing is that I cannot see any error, nothing.

Here it is my screencast:
https://drive.google.com/file/d/1fbkKOtT96i4u0IfnMUTbtbhhrlxkGZ0a/view

**Comment by khouloudbelguith** [comment]
@Jackpera, thanks for your feedback.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PHP error logs, you can find logs into the path `Project_Folder/var/logs/`
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Jackpera** [comment]
Ok, here you go with the details required:


    **server setup and configuration** --> Linux #1 SMP Debian 4.4.190-1~ui80+1 (2019-08-26) x86_64
 
    **PHP error logs, you can find logs into the path Project_Folder/var/logs/** --> Attached
[error_logs.zip](https://github.com/PrestaShop/PrestaShop/files/3729194/error_logs.zip)

    **apache error log --> In attachment
[apache_logs.zip](https://github.com/PrestaShop/PrestaShop/files/3729254/apache_logs.zip)


Let me know if there's something missing.

Thanks a lot

J

**Comment by khouloudbelguith** [comment]
@Jackpera, thanks for your feedback.
I found this exception
>[2019-10-14 15:17:15] php.CRITICAL: Uncaught Exception: No route found for "GET /sell/catalog/categories/delete": Method Not Allowed (Allow: POST) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /sell/catalog/categories/delete\": Method Not Allowed (Allow: POST) at /homepages/40/d797573214/htdocs/PrestaShop/bbshop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:143, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /homepages/40/d797573214/htdocs/PrestaShop/bbshop/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:4857)"} []

>[2019-10-14 14:52:53] php.CRITICAL: Uncaught Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/tmp/.priv) failed: Permission denied (13) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/tmp/.priv) failed: Permission denied (13) at /homepages/40/d797573214/htdocs/PrestaShop/bbshop/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php:101)"} []

Could you please check this issue with your host, there is permission denied on your server.

Thanks!

**Comment by Jackpera** [comment]
Ok, we enabled all permissions in this folder, but nothing changed.

We had a demo by the customer, giving them a limited administration account, with modules and parts of the backoffice disabled.

Surprisingly, for them it works. I tried to reproduce on my machine, logging in with their credentials, just to be sure there was no caching in local, and it works on my machine too.

So the problem seems to be related to PS BO permissions, but I'm not able to check and edit the SuperAdmin ones.

I also tried to create a new super-profile with all permissions enabled and, again, Categories cannot be erased.

Any idea on this behaviour?

**Comment by khouloudbelguith** [comment]
@Jackpera, no it is not a PrestaShop BO permission, because, if you are not allowed to delete a category => a red alert will be displayed.
https://drive.google.com/file/d/1qLCAeWg3gBJRmg7KLCXfgfZNcVCLFeIw/view

Thanks!

**Comment by Jackpera** [comment]
@khouloudbelguith just updating you for the love of the game, look here:

https://drive.google.com/file/d/1Rt5nUnNXBEtLUNYWNOfOCpZFBuXP7ul0/view

As you can see, here are the steps to reproduce in my system:

1. Create a profile with all permissions granted, assign a user and enter the BO with that user (in the video Super-Amministratore profile).
2. Try to delete a category --> Does not work
3. Remove permissions just on modules, Category deletion works perfectly

So the problem is probably a module.

Now we'll try to disable them one by one and find the culprit  🐙

**Comment by khouloudbelguith** [comment]
@Jackpera, in my case, it is OK.
So, I think, it is a custom module.
Waiting for your feedback.

**Comment by Jackpera** [comment]
I didn't find the module causing this yet, but this is not definitely a Prestashop error.
Thanks for the support

Jacopo

**Comment by khouloudbelguith** [comment]
@Jackpera, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
