### ISSUE TITLE
Improve body text for order confirmation email

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#15940]
**Is your feature request related to a problem? Please describe:**
As soon as an order is placed, the client automatically receives a confirmation email but the payment is not always automatically accepted. It can take a couple of days.

**Describe the solution you'd like:**
We must modify the wording of this confirmation email to make the client understand the order is not validated yet - but still waiting for the payment to be validated.

For the modern template only:

- [x] replace _Thank you for shopping on [name of the store]!_ with _Thank you for your order on [name of the store]!_

- [x] add _(waiting for validation)_ next to the payment method in the first frame of the Order Details section - when the payment method used needs to be validated before

- [x] replace _Total paid_ with _Total_

**Additional context:**
<img width="601" alt="Capture d’écran 2019-10-14 à 17 22 38" src="https://user-images.githubusercontent.com/32565890/66762968-45d44880-eea7-11e9-9102-d6bbe9ed8722.png">

<img width="499" alt="Capture d’écran 2019-10-14 à 17 28 20" src="https://user-images.githubusercontent.com/32565890/66763398-0e19d080-eea8-11e9-804d-dc9b2b060f11.png">

**Comment by Hlavtox** [comment]
> add (waiting for validation) next to the payment method in the first frame of the Order Details section

@LouiseBonnard Be careful, not all payment methods require any validation. Think of cash on delivery, personal pickup in store and many other ways.

**Comment by LouiseBonnard** [comment]
@Hlavtox, you're right, I should have specified it. It applies to payment methods that require a validation delay: bank wire, some card payments, cheque payment, etc.

**Comment by ghost** [comment]
@LouiseBonnard Still waiting for wording?
