### ISSUE TITLE
Add attribute rel="nofollow" on prestashop.com link in PS stores

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#15953]
Hello,

To prevent Google from considering traffic to prestashop.com coming from "2019 - ecommerce software by PrestaShop" as fake, we need to add the attribute rel="nofollow". 
This mention is available by default in all footers from 1.7 stores.

**Comment by jf-viguier** [comment]
And change the url to https://www.prestashop.com ?

**Comment by jf-viguier** [comment]
@colinegin I've fix it. I'm waiting for 1.7.6.2 release soon !

**Comment by colinegin** [comment]
yes you're right @jf-viguier !
Thank you for your help, we will review this asap.
