### ISSUE TITLE
Registration of fake costumers 

### ISSUE THREAD

**Issue by clbrandt** [PrestaShop/PrestaShop#15952]
I am responsible for a webshop run by prestashop and there seems to be a problem on the site. Fake costumers keep registrating to the site, all the time. How can i stop this from happening all the time?

**Comment by matks** [comment]
@clbrandt You are probably being spammed.
See :
- http://build.prestashop.com/news/fighting-against-spamming-again/
- http://build.prestashop.com/news/fighting-against-spamming/

Short answer: install a CAPTCHA module 😉
