### ISSUE TITLE
contact module send email anyhow

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#15961]
Prestashop 1.7.6.1 with ubuntu 18.04 and mod_pagespeed
I don't understand why for some time the messages from the contact form have been sent with or without a privacy flag.
I also tried several captcha modules (https://github.com/nenes25/eicaptcha/releases/tag/2.0.3) but nothing works, the recaptcha box is not displayed

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Have you tried to contact the module author: https://github.com/nenes25/eicaptcha/blob/master/eicaptcha.php#L37 about this issue.
It is not provided by PrestaShop.
Thanks to check with them & feedback.

**Comment by centoasa** [comment]
As I said, the issue is not related only with this captcha module, but to contact module sent anyway email with or without privacy flag

**Comment by khouloudbelguith** [comment]
@centoasa, could you please provide me a screenshot about emails with a privacy flag?
Did you use the gdpr module?
Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith  here screenshot: https://nimb.ws/E4PsWc
Yes, I use gdpr module (already reset)

**Comment by khouloudbelguith** [comment]
@centoasa, I did not manage to reproduce the issue with PS1.7.6.1.
The contact form module is well hooked to the `registerGDPRConsent` hook.
 
![image](https://user-images.githubusercontent.com/16067358/66901943-08cf9980-f000-11e9-9fa1-6bb0d7f8af93.png)
And the contact form is well enabled in the `psgdpr` module
![image](https://user-images.githubusercontent.com/16067358/66901997-27ce2b80-f000-11e9-98b2-41d22fc6ab7e.png)

Thanks to check & feedback.

**Comment by centoasa** [comment]
@khouloudbelguith have you tried if you can send contact by contact module with or without gdpr flag?

**Comment by khouloudbelguith** [comment]
@centoasa, yes!
https://drive.google.com/file/d/1vrkbgPIOu2pGm6LgdcfXAid-5ZnCdPJ2/view

Thanks to check & feedback.

**Comment by centoasa** [comment]
@khouloudbelguith sorry, very sorry: I was add this `<script async type="text/javascript" src="{$js.uri}" {$js.attribute}></script>` into /themes/leo_emarket/templates/_partials/javascript.tpl
Deleted it, now all works well and fine!

**Comment by khouloudbelguith** [comment]
@centoasa, Great!
Thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
