### ISSUE TITLE
[ORDER LIST] Improvements for Orders list

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#15971]
![Group 4bis](https://user-images.githubusercontent.com/15143151/66895045-8d1f1e00-effa-11e9-8c3d-f8485e82c400.png)

1. ~~Prices should be aligned on the left of the column~~ 

2. ~~The icons for invoice and delivery slips should be moved in the column « Actions », in the same color as the view icon. The icon used for invoice is google material icon « Receipt »~~  

3.  ~~Customer name should be a link to the customer’s profile page~~

4. In order to make the order list appear higher on the page, could you move the « select all » checkbox into the table’s header, next to the ID field ? #17456 

-> With the statistic block, bulk action button and select all checkbox, the first order appears a little bit too low on the page. 

![Capture d’écran 2019-10-11 à 11 44 05](https://user-images.githubusercontent.com/15143151/66895086-a2944800-effa-11e9-8ff6-76e3fa14863b.png)

5. Is the style of the green price related to the coming changes of order status labels? The typo is very small as it is, but I guess it’s going to change with status update.  

@TristanLDD I've added your change requests here, so i won't get lost and forgotten. :)

**Comment by matks** [comment]
Fixed partially by #16060

**Comment by colinegin** [comment]
Is there anything left to do here ?

**Comment by matks** [comment]
Yes, it's not finished but will be finished in feature freeze (bug fixes + adjustments)

**Comment by tomas862** [comment]
@matks , @colinegin  regarind point 4 shall we do this for all lists or only in the orders list?

**Comment by TristanLDD** [comment]
@tomas862 This behavior will benefit all lists so it's preferable to change it everywhere

**Comment by colinegin** [comment]
@tomas862 could you give us some details about the status of this issue ? 
Are there other PRs coming ?

**Comment by tomas862** [comment]
Seems like only this https://github.com/PrestaShop/PrestaShop/pull/17456 needs to be merged. Although not sure about point 5 if its done since I cant recall which color it was before.

**Comment by colinegin** [comment]
@MatShir @TristanLDD can you tell us if point 5 needs to be addressed ? 

> Is the style of the green price related to the coming changes of order status labels? The typo is very small as it is, but I guess it’s going to change with status update.

**Comment by MatShir** [comment]
The lastest remaining point is 5. The typo of the value of an order considered as paid is still small.
See in the screenshot below.
> 5. Is the style of the green price related to the coming changes of order status labels? The typo is very small as it is, but I guess it’s going to change with status update.


![download (3)](https://user-images.githubusercontent.com/43613217/73864198-859db200-4841-11ea-8e44-317a1e17d7ab.png)

**Comment by colinegin** [comment]
@tomas862 do you prefer that we create another issue with price display issue so that we can close this one ?

**Comment by matks** [comment]
> @tomas862 do you prefer that we create another issue with price display issue so that we can close this one ?

We would like to create another issue indeed. As we just fixed item 4, we would be very happy to close this one to ackowledge the work 😄
