### ISSUE TITLE
Image of Categories Bug

### ISSUE THREAD

**Issue by mandres2** [PrestaShop/PrestaShop#15970]
**Describe the bug**
The ApImageCategory does not line up in a row but instead goes down like a line of stairs.

**To Reproduce**
1. Go to 'Ap PageBuilder'
2. Click on 'Ap Profiles Manage -> Edit Design Layout'
3. Scroll down to 'Home' layout. Add a Group and then a column and add widget:  Image of Categories
4. Select up to 5 premade categories and include images
5. Save and Preview.

**Screenshots**
![ps_productcategoryimage](https://user-images.githubusercontent.com/50851214/66875155-29e1ad00-ef62-11e9-8351-20d29f009adb.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment]
Hi @mandres2,

Thanks for your report.
Did you use this module: https://addons.prestashop.com/en/page-customization/20111-ap-page-builder.html?

Thanks!

**Comment by mandres2** [comment]
Yes. The current & updated version of the (Apollo) Ap Page Builder Module is installed in my domain.

**Comment by khouloudbelguith** [comment]
Hi @mandres2,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=20111
Thanks!
