### ISSUE TITLE
Cannot save product with combinations

### ISSUE THREAD

**Issue by labibyanes92** [PrestaShop/PrestaShop#15975]
Hi everyone,
I have an issue on Prestashop saving or modifying products with combinations.
this issue appeared  after upgrading prestashop from 1.7.4.2 to 1.7.5.1 despite in the previous version (1.7.4.2) it was working 
if I want to modify a price of a product I am obliged to activate the debug mode to save modifications, if not an error message appeared is not possible to update the parameters
so I tried regularly to increase the limit memory value also the max_input_vars but the problem is still not solved
____________________________
ps:
 *the activation of the debug mode does not display any error on the contrary it solves the problem
*the issue is only with product with combinations , simple product works normly 
____________________________
prestashop : 1.7.5.1
 php: 7.2
server ovh
 php.ini:
max_execution_time = 30
max_input_time = 60
max_input_vars = 10000
memory_limit = 3072M

**Comment by khouloudbelguith** [comment]
Hi @labibyanes92,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by labibyanes92** [comment]
thank you @khouloudbelguith  
i cleared cache from this folder var/cache/dev&prod 
the problem still not solved

**Comment by khouloudbelguith** [comment]
@labibyanes92,

You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by labibyanes92** [comment]
i enable debug mode , open developer tools after saving product 
product is saved 
but in the normal mode product not saving , the message is err_empty-response
![debug mod activ](https://user-images.githubusercontent.com/56633569/66914768-cfa32380-f017-11e9-81f5-0f74e8b07f64.png)
![without debug](https://user-images.githubusercontent.com/56633569/66914769-cfa32380-f017-11e9-8ae2-24967be415e1.PNG)

**Comment by khouloudbelguith** [comment]
@labibyanes92, we need to retrieve the PHP error log to understand what's wrong.
You can find the error log file into your `Project_folder/var/logs/` path.
Thanks!

**Comment by labibyanes92** [comment]
[prod.log](https://github.com/PrestaShop/PrestaShop/files/3734095/prod.log)

[dev.zip](https://github.com/PrestaShop/PrestaShop/files/3734096/dev.zip)

**Comment by khouloudbelguith** [comment]
@labibyanes92, 
>2019-10-16 13:10:58] doctrine.DEBUG: SELECT * FROM cles_memcached_servers [] []

Did you use any server for caching?

>[2019-10-16 10:38:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/var/www/prestashop/var/cache/prod/ContainerOg4hhy3/getCache_AnnotationsService.php' (include_path='/var/www/prestashop/vendor/pear/pear_exception:/var/www/prestashop/vendor/pear/console_getopt:/var/www/prestashop/vendor/pear/pear-core-minimal/src:/var/www/prestashop/vendor/pear/archive_tar:.:/usr/share/php:/usr/share/pear')" at /var/www/prestashop/var/cache/prod/ContainerOg4hhy3/appProdProjectContainer.php line 1151 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/var/www/prestashop/var/cache/prod/ContainerOg4hhy3/getCache_AnnotationsService.php' (include_path='/var/www/prestashop/vendor/pear/pear_exception:/var/www/prestashop/vendor/pear/console_getopt:/var/www/prestashop/vendor/pear/pear-core-minimal/src:/var/www/prestashop/vendor/pear/archive_tar:.:/usr/share/php:/usr/share/pear') at /var/www/prestashop/var/cache/prod/ContainerOg4hhy3/appProdProjectContainer.php:1151)"} []

You have a lot of errors due to the cache.

Thanks!

**Comment by labibyanes92** [comment]
i don't think so
![per1](https://user-images.githubusercontent.com/56633569/66923832-d470d300-f029-11e9-94d9-241611a9e00e.PNG)
![per2](https://user-images.githubusercontent.com/56633569/66923834-d5096980-f029-11e9-9f32-9183c99d13ff.PNG)
![per3](https://user-images.githubusercontent.com/56633569/66923835-d5a20000-f029-11e9-9217-6bb45f7f1179.PNG)

**Comment by khouloudbelguith** [comment]
@labibyanes92, when mode debug is disabled & you try to save this product, is there any red alert displayed?

Thanks!

**Comment by labibyanes92** [comment]
@khouloudbelguith, yes the alert is " impossible de mettre a jour les parametres "

**Comment by khouloudbelguith** [comment]
@labibyanes92,

Could you please provide me the access to your shop.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by labibyanes92** [comment]
done

**Comment by khouloudbelguith** [comment]
@labibyanes92, thanks!
I will check & feedback.

**Comment by labibyanes92** [comment]
thank you

**Comment by khouloudbelguith** [comment]
@labibyanes92, I found a lot of issues:
1. The pack bloc is displayed but it is a standard product.
2. Can't add an image
3. Can't select combinations

https://drive.google.com/file/d/11nG7i2yuWQmylfG1sDeTyePz0Frkxmy4/view

Thanks to check & feedback.

**Comment by labibyanes92** [comment]
it work for me !
![test1](https://user-images.githubusercontent.com/56633569/66927347-ebb2bf00-f02f-11e9-908a-f2f47869eeb8.PNG)
![test2](https://user-images.githubusercontent.com/56633569/66927348-ec4b5580-f02f-11e9-95e9-dcfe9f69e4d9.PNG)

**Comment by labibyanes92** [comment]
combinations not displayed
![test3](https://user-images.githubusercontent.com/56633569/66927612-5fed6280-f030-11e9-9062-27b775c2408b.PNG)

**Comment by khouloudbelguith** [comment]
@labibyanes92, yes, it is working now!
& I can save a product without issues
https://drive.google.com/file/d/1dPuRqW1YAQkmV6xWYuaRYLVK0-BPx5AS/view
Thanks!

**Comment by labibyanes92** [comment]
sorry @khouloudbelguith but still not working 
check the prodcut with this id 14435 please

**Comment by labibyanes92** [comment]
i think it was a problem  number of combinations

**Comment by khouloudbelguith** [comment]
@labibyanes92, did you use a lot of combinations?

Thanks!

**Comment by labibyanes92** [comment]
@khouloudbelguith  
yes there are product with many combinations
but if i cleared cache i can save product but sometimes i can't

**Comment by khouloudbelguith** [comment]
@labibyanes92, so it could be similar to this issue:
https://github.com/PrestaShop/PrestaShop/issues/9809

Thanks to check & feedback.

**Comment by labibyanes92** [comment]
@khouloudbelguith  This issue is not fixed yet.

**Comment by khouloudbelguith** [comment]
@labibyanes92, yes, it is added to our bug roadmap.
So, can I close the issue as a duplicate?

Thanks!

**Comment by labibyanes92** [comment]
thakns @khouloudbelguith 
i'm so confused i enable the debug mode , the problem is disapeared ,no error
it seems cache problem also 
ERR_EMPTY_RESPONSE

**Comment by khouloudbelguith** [comment]
@labibyanes92, You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @labibyanes92,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
