### ISSUE TITLE
Translating modules in English from BO

### ISSUE THREAD

**Issue by N-Wouda** [PrestaShop/PrestaShop#15985]
**Describe the bug**
Translating modules in English (_en-gb_) in the backoffice throws this error message (see screenshots). I've also had a look at #15850, but since we're already on 1.7.6.1, I do not think this applies. Do you have any idea?

This is the full stacktrace:
```
Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Argument 2 passed to PrestaShopBundle\Translation\Loader\DatabaseTranslationLoader::addLangConstraint() must be an instance of PrestaShopBundle\Entity\Lang, null given, called in <snip>/src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php on line 76

  at src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php:98
  at PrestaShopBundle\Translation\Loader\DatabaseTranslationLoader->addLangConstraint(object(QueryBuilder), null)
     (src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php:76)
  at PrestaShopBundle\Translation\Loader\DatabaseTranslationLoader->load(null, 'en-US', '^ModulesContactinfo([A-Z]|$)', null)
     (src/PrestaShopBundle/Translation/Provider/AbstractProvider.php:211)
  at PrestaShopBundle\Translation\Provider\AbstractProvider->getDatabaseCatalogue(null)
     (src/PrestaShopBundle/Translation/View/TreeBuilder.php:61)
  at PrestaShopBundle\Translation\View\TreeBuilder->makeTranslationArray(object(ExternalModuleLegacySystemProvider), null)
     (src/PrestaShopBundle/Controller/Api/TranslationController.php:353)
  at PrestaShopBundle\Controller\Api\TranslationController->getModulesTree('en', 'ps_contactinfo', null)
     (src/PrestaShopBundle/Controller/Api/TranslationController.php:149)
  at PrestaShopBundle\Controller\Api\TranslationController->listTreeAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin272eoiju3/index.php:86)
```

**To Reproduce**
1. Go to `International` -> `Translations` in the BO
2. Click on Module translations, for e.g. `ps_contactinfo` and select English.
3. Go into the translation screen, and you should be greeted with the same error.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![blank_screen](https://user-images.githubusercontent.com/16272507/66929294-105c6600-f033-11e9-993a-4da4215c4e99.png)
![error](https://user-images.githubusercontent.com/16272507/66929293-105c6600-f033-11e9-9ecd-6bae15c03768.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1

**Comment by N-Wouda** [comment]
I also tried switching themes prior to this, as I read in another issue this might be the cause of it, but that did not do much for me.

**Comment by khouloudbelguith** [comment]
Hi @N-Wouda,

Does this issue occur only with this module?
In my case, it is OK with PS1.7.6.1 & the ps_contactinfo
https://drive.google.com/file/d/1h6dL6BHqwlj5qptvBHhrDOhfVPFF2M-S/view

Thanks to check & feedback.

**Comment by N-Wouda** [comment]
Hi @khouloudbelguith,

I did some searching. Our English locale is `en-gb`, but for some reason, the locale turns to `en-US` at some point in the code (see also stack trace above, the call to `DatabaseTranslationLoader->load()`). This English locale does not exist in our shop (AFAIK), so `$langs[$locale]` as an argument to `$this->addLangConstraint()` is set to `null`.

I've updated our locale to `en-GB`, and that appears to fix it - where the whole `en-US` comes from, however, I have no clue!

**Comment by khouloudbelguith** [comment]
@N-Wouda, so the issue is fixed after updating the language?

Thanks!

**Comment by N-Wouda** [comment]
@khouloudbelguith yes, after updating the locale from `en-gb` to `en-GB`!

**Comment by khouloudbelguith** [comment]
@N-Wouda, I added the English GB from the translations Page & it is OK with `en-gb`
https://drive.google.com/file/d/1-bj4vFM0MfQdUYtcG3VQ7erUE-V7yQrs/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @N-Wouda,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
