### ISSUE TITLE
Customized product can't be deleted from the cart

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#15986]
**Describe the bug**
It's impossible to delete a customized product from the cart if attached image doesn't exists.

1. Create a customizable product with an image field 
2. Add this customized product to the cart with an image
3. Delete the image in the upload folder
4. Try to delete the product in the cart : the first time, the customization is deleted. Second time : nothing appends

It's a complicated issue, I've simplified the test case because my concern is in a more complicated setup with my module changing customization behaviour. 

PrestaShop version: develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
I will add the issue to the bug roadmap.
Thanks for the fix.
