### ISSUE TITLE
Can't checkout when logged in, but checkout works if buying as a guest

### ISSUE THREAD

**Issue by PrestaNewbie** [PrestaShop/PrestaShop#16003]
Hello,

when I create new account and I try to checkout on second step(see picture), when i press Continue, site just reloads and nothing happens. What can be wrong?

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2
![checkouterror](https://user-images.githubusercontent.com/56392393/67014447-8c22e500-f0fd-11e9-8aa3-f19eb6a4738c.PNG)

**Comment by khouloudbelguith** [comment]
Hi @PrestaNewbie,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by PrestaNewbie** [comment]
![console log](https://user-images.githubusercontent.com/56392393/67017202-110ffd80-f102-11e9-88fe-224113d9610b.PNG)
![debug logs](https://user-images.githubusercontent.com/56392393/67017203-110ffd80-f102-11e9-9b36-a1ef0ab78cf6.PNG)
![Information](https://user-images.githubusercontent.com/56392393/67017205-110ffd80-f102-11e9-8fd4-431a664988d4.PNG)

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, on the FO, when you click on continue button, there is no exception displayed when debug mode is enabled?

Thanks!

**Comment by PrestaNewbie** [comment]
@khouloudbelguith 
No, there is no exception displayed

**Comment by PrestaNewbie** [comment]
@khouloudbelguith 
i don't understand this, but maybe this is the problem?
![logs](https://user-images.githubusercontent.com/56392393/67019109-d0fe4a00-f104-11e9-9d30-061c096526a6.PNG)

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, they are just deprecations, click on the "Bebug" Tab to see is there are exceptions?

Thanks!

**Comment by PrestaNewbie** [comment]
@khouloudbelguith 
Debug tab
![debug tab](https://user-images.githubusercontent.com/56392393/67020096-546c6b00-f106-11e9-9cf0-a23f82837fcd.PNG)
![PHP notices](https://user-images.githubusercontent.com/56392393/67020214-82ea4600-f106-11e9-80cb-50b57ed6ee95.PNG)

**Comment by khouloudbelguith** [comment]
@PrestaNewbie,

You need to enable debug mode in your store and debug request which is sent for continue action in your browser, using DevTools, so:

1. enable debug mode
2. go to the checkout page
3. open up developer tools
4. go to Network tab
5. Click on Continue
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by PrestaNewbie** [comment]
@khouloudbelguith 
When i click Continue, that happens
![network](https://user-images.githubusercontent.com/56392393/67022054-453aec80-f109-11e9-8b8b-8394e5dd556e.PNG)

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, could please provide me a screenshot from your BO => Customers => Addresses => " Set required fields for this section"
 
![image](https://user-images.githubusercontent.com/16067358/67022584-bc6c8280-f101-11e9-85a0-7bdc36514964.png)

And a screenshot form your BO => International => Locations => Countries => Edit your country => The Address format
![image](https://user-images.githubusercontent.com/16067358/67022734-f9387980-f101-11e9-9c97-6a86f46bbcf4.png)

Thanks!

**Comment by PrestaNewbie** [comment]
@khouloudbelguith 
![address format](https://user-images.githubusercontent.com/56392393/67023152-fee68d00-f10a-11e9-86ad-a903c7460232.PNG)
![required fields](https://user-images.githubusercontent.com/56392393/67023155-fee68d00-f10a-11e9-89fa-e75a64a830e8.PNG)

THANKS!!!

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, thanks to add in your address format the field home phone & Save.
![image](https://user-images.githubusercontent.com/16067358/67023475-246f9880-f103-11e9-9561-3a61ac602e44.png)

Thanks!

**Comment by PrestaNewbie** [comment]
@khouloudbelguith , THANK YOU VERY MUCH!
It fixed checkout! I left only phone to be required. BIG THanks again!

**Comment by khouloudbelguith** [comment]
@PrestaNewbie, you are welcome!
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!
