### ISSUE TITLE
Hook Request (back office new order creation)

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#16007]
Hi,

Would be very useful to have a hook which allows modules to display content in the new order creation form in the back office.

At the moment, I have to modify the file
adminps/themes/default/template/controllers/orders/form.tpl

and add the following code where I wish to display the module content:

			<div class="form-group">
				<div class="checkbox col-lg-9 col-offset-3">
					**{hook h='AdminOrder'}**
				</div>
			</div>

Or I have to ask the customer to make this modification and I desperately try to avoid making changes to core files.

Unless a hook is already available and I am missing it?

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

The hook `displayAdminOrder` displays new elements in the Back Office, tab AdminOrder This hook launches modules when the AdminOrder tab is displayed in the Back Office.
The hook `displayAdminOrderContentOrder` displays new elements in Back Office, AdminOrder, panel Order This hook launches modules when the AdminOrder tab is displayed in the Back Office and extends/override Order panel content.

For more details, you can follow this comment: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/
Thanks to check & feedback.

**Comment by musaffar-patel** [comment]
Hi

Do these hooks actually display content during the creation of a new order in the back office?  As i tried them and it seems they instead display content when viewing existing orders (not a new order)

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment]
@musaffar-patel, and what if you use the hook displayAdminOrder instead of those hooks, 
It displays new elements in the Back Office, tab AdminOrder This hook launches modules when the AdminOrder tab is displayed in the Back Office
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
