### ISSUE TITLE
Some libraries should be in package.json in blockreassurance

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#16010]
**Describe the bug**
Currently, the pickr and vue libraries are straight into the code of the blockreassurance module, without information about version, licence, etc.
@Progi1984 asked me to open an issue in order to manage it with the package.json.

**To Reproduce**
https://github.com/PrestaShop/blockreassurance/blob/master/views/lib/pickr/js/pickr.js*
https://github.com/PrestaShop/blockreassurance/blob/master/views/js/vue.min.js

FYI: https://github.com/Simonwep/pickr

**Comment by khouloudbelguith** [comment]
@ttoine, @Progi1984, this issue is with Minor severity? is it?

Thanks!

**Comment by Progi1984** [comment]
Fixed in PrestaShop/blockreassurance#34
