### ISSUE TITLE
Maintenance ip filtering should support ipv6 client addresses

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#16032]
**Is your feature request related to a problem? Please describe.**
 ip v6 address filtering is not supported because  ip v6 address has an every day changing end.

**Describe the solution you'd like**
Ip prefix should be supported like xxx* : everything starting with xxx is ok.

Htaccess filtering can be done with this syntax : 2a11:e0d:237:eec0:0000:0000:0000:0000/64
Maybe we could support this syntax or something like this : 2a01:e0a:257:eec0:* or just compare the begining with 2a01:e0a:257:eec0

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I have the same behavior as PS1.7.5.2 & PS1.7.6.1.
https://drive.google.com/file/d/17p_Qs5ErY3ZNJ3GZvmO6CJtcxRpJN_nS/view
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by micka-fdz** [comment]
As a front-end developer, it's very annoying to add a new IPv6 address every day when the site is in maintenance mode. I think it's a good idea to add this improvement.
