### ISSUE TITLE
Cannot configure modules with CLI and PHP 7.3

### ISSUE THREAD

**Issue by antho-girard** [PrestaShop/PrestaShop#16037]
**Describe the bug**
The command `php bin/console prestashop:module configure testmod` fails with PHP 7.3
With PHP 7.2, the same command works fine.
<br>
Here is the error with PHP 7.3 : 

```
10:54:39 ERROR     [console] Error thrown while running command "prestashop:module configure testmod". Message: "Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?" ["exception" => Symfony\Component\Debug\Exception\ContextErrorException { …},"command" => "prestashop:module configure testmod","message" => "Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?"]

In UnitOfWork.php line 2636:

  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```

**To Reproduce**
Run the command above with PHP 7.3

**Screenshots**
N/A

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by matks** [comment]
@antho-girard PS 1.7.6.1 is not compatible with php7.3 . Next minor version PS 1.7.7 will be compatible (thanks to a Doctrine update).

**Comment by khouloudbelguith** [comment]
Hi @antho-girard,

As @matks said, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP.

I close the issue, feel free to open a new one when needed.

Thanks!
