### ISSUE TITLE
Improvements for Order view

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#16039]
Improvements needed for Order view page:

1. Material icon ‘account_box’ is missing
2. Edit should be done through material icon ‘more_vert ‘ —>  Edit  
3. Price background is missing
4. Add icons in tabs
5. Increase spacing between buttons to 15px 
6. Text color in buttons should be #576C72

![order_feedback](https://user-images.githubusercontent.com/15143151/67195671-07d4a880-f402-11e9-898b-80b28b7f02c3.jpg)

Regarding order preivew : 

- The 'open order' button is a little bit too close to the line below, which can lead to misclick.

![order_preview_feedback](https://user-images.githubusercontent.com/15143151/67195805-4ff3cb00-f402-11e9-9e78-e98127079cdc.png)

- The order line in order list should be clickable as it was in legacy page. 
- The status hover in order list should have the following behavior: 

![Capture d’écran 2019-10-21 à 14 10 53](https://user-images.githubusercontent.com/27484094/67203966-c4336c00-f40c-11e9-896b-cd580ad5ce86.png)

![Edit Adress](https://user-images.githubusercontent.com/27484094/69325443-777cc400-0c4a-11ea-8c71-f13f3fb64e8b.jpg)

Mockups for the poppin: https://invis.io/YKTGGFZAMCB#/382686482__Order_Details_-_Change_Adress

@TristanLDD I'm opening issue with your requests, so it won't get lost. :wink:

**Comment by MatShir** [comment]
@Robin-Fischer-PS 
FYI: All the improvements are going to be tagged on this issues to fix them after all the order page component is done :)

**Comment by colinegin** [comment]
@MatShir and @TristanLDD should this be fixed before or after the freeze ?

**Comment by TristanLDD** [comment]
@colinegin With Sarunas' departure we may want to keep it for after the freeze

**Comment by prestascott** [comment]
@sarjon For the improvement #2, we should keep the "edit" material icon rather than replacing it by "more_vert" because we might expect a button group after clicking on it so it can be confusing.
