### ISSUE TITLE
Shipping price changing to 0 auto

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#16042]
I am getting a very strange issue that shipping price setting to 0 after placing order. Its so random that i am not able to replicate it. 

If somebody has info about this please let me know.

PrestaShop version: 1.7.5.1
PHP version: 7.2

Thanks

**Comment by khouloudbelguith** [comment]
Hi @beniwal,

In fact, there are three options to have a free shipping
1. Shipping > Configuration
![image](https://user-images.githubusercontent.com/16067358/66816821-022b1e80-ef3b-11e9-94b0-671ea0a172a3.png)

2. Carrier ranges
![image](https://user-images.githubusercontent.com/16067358/66816914-30106300-ef3b-11e9-9f17-0de35880018e.png)
3. A voucher free shipping
3.1 ![image](https://user-images.githubusercontent.com/16067358/66817091-74036800-ef3b-11e9-8e1a-59afa85ec532.png)
3.2 ![image](https://user-images.githubusercontent.com/16067358/66817107-7b2a7600-ef3b-11e9-8eb0-008b5ca39e1d.png)
In this case, free shipping above x amount will be applied when a discount is applied

Thanks to check if you have the same behavior.

Thanks!

**Comment by simulbeni** [comment]
I am Working with prestashop from years.

Worked on websites more than 200.

Issue coming to me when order finished.

Its ok in first time but after sometime it change to shipping price to 0.

**Comment by khouloudbelguith** [comment]
@beniwal, have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/15411?
Did you use any custom payment module?

Thanks!

**Comment by simulbeni** [comment]
@khouloudbelguith yes i am using paynl as payment service. Earlier it was Ingenico.

But issue is same in both payment system.

More or less issue is same as #15411 but in my case its not coming always. Its so random that i cannot even get any root cause of issue.

Thanks

**Comment by khouloudbelguith** [comment]
@beniwal, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by simulbeni** [comment]
I will create a complete report for this. I am looking for some solution if exists.

Please look at the screenshot attached.
![shipping](https://user-images.githubusercontent.com/437314/67210346-8fd4a580-f436-11e9-87d6-4a372b8705ac.PNG)

**Comment by khouloudbelguith** [comment]
@beniwal, in my case, I did not manage to reproduce the issue with the Native payment module.
Waiting for your feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @beniwal,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
