### ISSUE TITLE
login template google plus (is dead ) but link is steel in login page

### ISSUE THREAD

**Issue by mohamedaitbella** [PrestaShop/PrestaShop#16040]
**Describe the bug**

**To Reproduce**
1. Go to 'login template you gonna see google plus link (google plus is dead)'

**Additional information**
PrestaShop version: 1.7.6.x

**Comment by khouloudbelguith** [comment]
Hi @mohamedaitbella,

Thanks for your report.
![image](https://user-images.githubusercontent.com/16067358/67197463-21bfbc80-f3fd-11e9-940b-4eb5f505e37d.png)

As written by the support team, `Google+ is only available for G Suite accounts through work or school. Consumer accounts (typically ending in @gmail.com) were shut down on April 2nd, 2019.`
https://support.google.com/plus/announcements/9195238
I’ll add this to the debug roadmap
Thanks!

**Comment by mohamedaitbella** [comment]
this is the My PR
https://github.com/PrestaShop/PrestaShop/pull/16041#issuecomment-544447029
