### ISSUE TITLE
Enabling Debug Mode gives 404 Error on every page in front office 

### ISSUE THREAD

**Issue by Allbutfancy** [PrestaShop/PrestaShop#16044]
Whenever we try to activate debug mode in backoffice, our whole site response with a 404 error.
What should we take a look into?

Best regards,
Allbutfancy

PrestaShop version: 1.7.6.1
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @Allbutfancy,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rdy4ever** [comment]
Hi @Allbutfancy 
I'd recommend to try these two things:

1. Manually delete the contents of `var/cache/` folder (dev and prod folders)
2. If this doesn't help, try to regenerate .htaccess, by disabling and enabling pretty urls in Configuration->Traffic and SEO.

**Comment by Allbutfancy** [comment]
Hey @khouloudbelguith 

I will create the bug report and reach back with the information.

Hi @rdy4ever 
Thanks for the response, will try it and let you know how it went.

Cheers!

**Comment by khouloudbelguith** [comment]
Hi @Allbutfancy,

Thanks!

Waiting for your feedback.

**Comment by Allbutfancy** [comment]
Hey @khouloudbelguith @rdy4ever 

Sorry for the late response, we tried to remove the cache manually but nothing happened.
Afterwards we tried to update from PHP 7.1.4 to 7.3.9 and this resolved the 404 error.

Thanks for the suggestions and fast response!
Best regards,
Allbutfancy

**Comment by khouloudbelguith** [comment]
@Allbutfancy, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version to PHP7.2, check and feedback

**Comment by Allbutfancy** [comment]
@khouloudbelguith we have downgraded our PHP version to PHP 7.2 and experience no errors! Works wonderfully.

Thanks!

**Comment by khouloudbelguith** [comment]
@Allbutfancy, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
