### ISSUE TITLE
Customers created in another shop are not displayed in the list if the shop group share customers

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16043]
**Describe the bug**
Customers created in another shop are not displayed in the list if the shop group share customers

**To Reproduce**
1. Enable multistore in Shop parameters > General
2. Go in advanced parameters > Multistore 
3. Add a new shop group "group2" and share customers, share available quantity to sell and share orders
4. Add a new shop "shop1" in "group2"
5. Define an URL for "shop1"
6. Add a new shop "shop2" in group2"
7. Define an URL for "shop2"
8. Open "shop1" FO and create a customer account
9. Go in BO > Customers > Customers and select "Shop1": You see the customer created OK
10. Click on view the customer in "shop1": OK
11. Select "shop2", you still view the customer details: OK
12. Go in BO > Customers > Customers and select "Shop2": You don't see the customer created NOK
13. Open "shop2" FO and try to login with the customer created in "shop1": OK 

If the shop group share customers, I should see in the list customers created in another shop
It was working in 1.7.5.2

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by marionf** [comment]
@Robin-Fischer-PS & @sarahdib 
You can take note of this scenario for the migration of order list & order view pages
As we also have the option to "share orders"
Which means if it's enabled for the shop group, I should be able to see in shop2 an order created in shop1 and vice versa

**Comment by jolelievre** [comment]
Closed by #16047
