### ISSUE TITLE
Prestashop DEMO (https://demo.prestashop.com) isn't working on https

### ISSUE THREAD

**Issue by romainguillo** [PrestaShop/PrestaShop#16048]
When searching "prestashop demo" on Google, the result is with https : 
https://demo.prestashop.com

But the DEMO isn't working on this URL because of "https" : 
_(Blocked mixed active content) « http://vast-collar.demo-ms.production.prestashop.com/error500.html_

**Comment by khouloudbelguith** [comment]
Hi @romainguillo,

Thanks for your report.
I just forwarded your issue to our Team.

Thanks!

**Comment by matks** [comment]
I confirm that Google is forcing https in results, so people coming from google arrive on the https and see a scary screen 😱 
![Capture d’écran 2019-10-22 à 17 47 59](https://user-images.githubusercontent.com/3830050/67304711-89a4fe80-f4f4-11e9-9d23-6e119f925a98.png)
![Capture d’écran 2019-10-22 à 17 51 47](https://user-images.githubusercontent.com/3830050/67304770-a4777300-f4f4-11e9-8a06-fa29285d01fc.png)

**Comment by Kixell-NicolasJardillier** [comment]
ok I complete @matks now https is ok on main domain but load http url, thus it stil do not work
![image](https://user-images.githubusercontent.com/4049969/67485225-e7a72280-f669-11e9-98bc-3ad2201a25da.png)

**Comment by ghost** [comment]
Hi @matks, should we put this one in "In Progress" ?

**Comment by Quetzacoalt91** [comment]
Yes that's a work in progress:

* https://github.com/PrestaShop/docker-internal-images/pull/30
* https://github.com/PrestaShop/live-demo-devices/pull/10

Plus one private repository impacted, and the certificates being managed by the devops team.

**Comment by matks** [comment]
🆙 
Is there something I can do to make this issue go forward ?

**Comment by matks** [comment]
Thanks to PrestaShop IT team, https://demo.prestashop.com/ is now ✅ 😄

**Comment by matks** [comment]
And thank you @Quetzacoalt91 of course
