### ISSUE TITLE
When proceeding to checkout, no shipping method appears, no purchase can be made for customers, but for visitors, yes.

### ISSUE THREAD

**Issue by Upartech** [PrestaShop/PrestaShop#16058]
Hi. I'm new here. I want to report a failure. I appreciate helping me to solve it.

System Specifications:
PrestaShop version: 1.7.6.0
PHP version: 7.2.22
MySQL Version: 10.2.27-MariaDB
MySQL Engine: InnoDB

Steps to reproduce the error:
1) Go to "Transportation"
2) to "Conveyors"
3) To the first transport operator that appears in the list go to "Edit"
4) Add an "@" in the URL link
5) In "Locations and shipping costs" change each price in each condition
6) Then "Finish"
7) Repeat each action from step 3.

The error:
Shipping methods do not appear for users who are customers and the purchase process cannot continue. but shipping methods do appear to visitors
(They do not have previous registration in the database, even when all the conveyors are available and there is no restriction on any product).

**Comment by khouloudbelguith** [comment]
Hi @ovallepa,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screenrecord
https://drive.google.com/file/d/1sN_eDgTegzmWeTsM-G2G8RM2o5_BWvVq/view
The carrier is available to all the groups?
![image](https://user-images.githubusercontent.com/16067358/67270708-7cb6e980-f4b9-11e9-9d9e-99783761f45d.png)

Thanks!

**Comment by Upartech** [comment]
If all groups are enabled and I have verified it in the database.  I really don't know what happens.  I have verified each condition for carriers to appear but they still do not appear.  The information that I have taken from reference has been:

https://www.prestashopmanager.com/useful-articles/tips-tricks/what-to-check-if-prestashop-carriers-are-not-available-at-checkout/

**Comment by Upartech** [comment]
If you like, I can provide you with the credentials to verify the fault.

**Comment by khouloudbelguith** [comment]
@ovallepa, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ovallepa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Upartech** [comment]
Okay.  It's okay.  The solution to the problem I had was time.  For some
reason the changes made did not take effect immediately but after 2 days.
It was strange but it was fixed.  Thank you very much for your help
