### ISSUE TITLE
Very strict selector div.delivery-option

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#16050]
The selector ["div.delivery-option"](https://github.com/PrestaShop/PrestaShop/blob/33684a3828f66e3a0e91ed53a8239813dcef41dd/themes/_core/js/checkout-delivery.js#L40) has 2 deficiencies:
1. Limit only div elements
2. The selector should start with "js-" to differentiate it from the style.

Point 1 is easy, change `div.delivery-option` to `.delivery-option`.
Point 2 is backwards incompatible. I think we can leave this for another issue. 

**Describe the bug**
I want to allow in my theme that `.delivery-option` is not `div`.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?
It is introduced with this PR: https://github.com/PrestaShop/PrestaShop/pull/6261

Thanks!
