### ISSUE TITLE
Notifications - "Kernel Container is not available"

### ISSUE THREAD

**Issue by devonto** [PrestaShop/PrestaShop#16061]
**Describe the bug**
Loading any page in the back office produces a PHP error

**Error**
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /home/vhosts/[...].com/httpdocs/src/Adapter/ContainerFinder.php:77
Stack trace:
#0 /home/vhosts/[...].com/httpdocs/classes/Tools.php(796): PrestaShop\\PrestaShop\\Adapter\\ContainerFinder->getContainer()
#1 /home/vhosts/[...].com/httpdocs/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))
#2 /home/vhosts/[...].com/httpdocs/classes/Notification.php(133): ToolsCore::displayPrice(12.35, Object(Currency), false)
#3 /home/vhosts/[...].com/httpdocs/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '23363')
#4 /home/vhosts/[...].com/httpdocs/admin944m5qvqa/ajax.php(125): NotificationCore->getLastElements()
#5 {main}\n  thrown in /home/vhosts/[...].com/httpdocs/src/Adapter/ContainerFinder.php on line 77
', referer: [...].com/admin/index.php?controller=AdminOrders&token=XXX
```

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.23

This is different from #15503, but is mentioned within it as a comment by @madcorp206

**Comment by khouloudbelguith** [comment]
Hi @devonto,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by devonto** [comment]
Sure, here you go:

**- host**
Private server
**- server setup and configuration**
Server information Linux #1 SMP Wed Feb 13 16:19:36 EST 2019 x86_64
Server software version: Apache
PHP version: 7.2.23
Memory limit: 256M
Max execution time: 1200
Upload Max File size: 16M
**- PrestaShop version (source)**
As above - 1.7.6.1
**- debug mode report**
Debugger does not appear when exception is thrown
**- PHP error logs**
As above
**- apache error log**
N/A
**- javascript console log**
N/A
**- screenshots**
N/A

Also, this issue went away earlier, but has reappeared with a new order - which would make sense, since it is a "notification" that is failing

**Comment by khouloudbelguith** [comment]
@devonto, did you use a custom payment module?

Thanks!

**Comment by devonto** [comment]
On this transaction, it was the Prestashop "Payments by check" module

**Comment by khouloudbelguith** [comment]
@devonto, this is a fresh install PS1.7.6.1 or an upgrade from an old version?

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith An upgrade from 1.7.5.2

**Comment by khouloudbelguith** [comment]
@devonto, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith Sure - anonymized and attached
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3757062/log.txt)

**Comment by khouloudbelguith** [comment]
@devonto, thanks for your feedback.

>[2019-10-21 10:31:53] All files upgraded.
>[2019-10-21 12:32:02] Database upgrade OK
>[2019-10-21 12:32:10] Database upgraded. 
>[2019-10-21 11:32:21] Addons modules files have been upgraded.

@devonto, could you please check that your `composer.lock` file is similar to this https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/composer.lock

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith I have ran the master through a diff checker with the one locally and they are identical

**Comment by khouloudbelguith** [comment]
@devonto, what are the exact steps that you did previously before this issue occurs?

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith Nothing specific... just browse the back office.

As mentioned above, it went away for a while, but then when a new order came in, it reappeared.

**Comment by khouloudbelguith** [comment]
@devonto, what are the exact Active payment in your shop?
![image](https://user-images.githubusercontent.com/16067358/67309372-0c7d8780-f4fc-11e9-8eb6-1851f4defaf8.png)

Thanks!

**Comment by devonto** [comment]
PayPal v5.0.2
Bank transfer v2.0.4
Payments by check v2.0.4

I do also have "Stripe Payment Pro" v 3.9.3 installed, but it does not appear in that list.

**Comment by khouloudbelguith** [comment]
@devonto, could you please try to disable each module one by one, check if the issue occurs again & feedback.
Thanks!

**Comment by devonto** [comment]
@khouloudbelguith Sorry - disabling all payment modules (And other third party modules) had no effect.

If it helps, the error is being produced on an AJAX call to `/admin/ajax.php` with the form data of `getNoficiations=1`

It does not fail on page load and curiously, it only appears to fail on the following BO pages.
It's easy to spot the failure in the BO when there is no notification count next to the bell icon at the top right.

- Main dashboard
- Orders -> Orders
- Orders -> Credit Notes
- Orders -> Shopping Carts
- Customers -> Addresses
- Customer Service - > [all]
- Stats

**Comment by khouloudbelguith** [comment]
@devonto, how did you disable the modules?
>disabling all payment modules (And other third-party modules)

From the BO => Advanced Parameters => Performance Page or manually?
![image](https://user-images.githubusercontent.com/16067358/67557698-d582be00-f715-11e9-8381-cd8d245ec72b.png)

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith, manually - one by one; however I have also just tried your method and the same issue persists with all "Non Prestashop modules" disabled.

**Comment by khouloudbelguith** [comment]
@devonto, no, this option is not working as reported here: https://github.com/PrestaShop/PrestaShop/issues/9965
Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith Thanks - email sent

**Comment by khouloudbelguith** [comment]
@devonto, thanks!
I just received the email, I will check & feedback.

**Comment by khouloudbelguith** [comment]
@devonto, I just sent an email, can you check it & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @devonto,

As discussed in the email.
It is a module issue.
I will close the ticket, feel free to open a new one when needed.
Thanks!

**Comment by devonto** [comment]
Just for the benefit of others, the specific module in question is "`[Stripe Payment Pro (SCA-ready)](https://addons.prestashop.com/en/payment-card-wallet/17856-stripe-payment-pro-sca-ready.html?ab=1)`".

A request has been sent to the developer to resolve it.
