### ISSUE TITLE
Data in All shops can't be saved 

### ISSUE THREAD

**Issue by Navus1** [PrestaShop/PrestaShop#16062]
Hi,

we have a store with 3 different shops. We want to create one product at All Shops, and then to make changes and customization to other shops.

But when we create product on All shops, part of the data is not saved. We have custom fealds in product describtion.

What might be the problem?

Screens:

![image](https://user-images.githubusercontent.com/56867869/67271306-eedffc00-f4c2-11e9-973a-c6ddcf37ab31.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment]
Hi @Navus1,

Thanks for your report.
>But when we create product on All shops, part of the data is not saved

What is the exact data? is it a price or description?

You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Navus1** [comment]
It is custom describtion fealds.

**Comment by khouloudbelguith** [comment]
@Navus1, this `custom description fields` is introduced by a custom module?

Thanks!

**Comment by Navus1** [comment]
Unfortunately we do not get any error.

**Comment by Navus1** [comment]
Yes, it is custom module

**Comment by khouloudbelguith** [comment]
@Navus1, you need to handle the Multistore feature https://devdocs.prestashop.com/1.7/modules/creation/#handling-the-multistore-feature
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
