### ISSUE TITLE
Price formatting error in order history

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#16080]
**Describe the bug**

**To Reproduce**
1. Go to FO and login
2. Make sure you have at least one order placed
3. Go to your account and open "Order history"
4. Click "Details" on any order and see error at the bottom of the page.

**Screenshots**
https://prnt.sc/pmztbx

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by matks** [comment]
Probably because of https://github.com/PrestaShop/PrestaShop/pull/15448

**Comment by khouloudbelguith** [comment]
Hi @sarjon, @matks,

I have the same issue with develop branch
![image](https://user-images.githubusercontent.com/16067358/67383612-c40fa980-f58f-11e9-8dd4-9f6c2075906f.png)

I’ll add this to the debug roadmap.

Thanks!
