### ISSUE TITLE
Prestashop 1.7.6.1 - [PrestaShopDatabaseException code 0] in Admin > Categories

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#16082]
If the debug mode is activated and I edit a category in the admin, I get this error upon saving:

Une erreur inattendue s'est produite. [PrestaShopDatabaseException code 0]
in English: An error has happened. [PrestaShopDatabaseException code 0]

There's no other indication than this.

![Screen Shot 2019-10-23 at 11 16 10 (2)](https://user-images.githubusercontent.com/71735/67383272-d1746600-f586-11e9-9f5a-91421c30fa13.png)

**Comment by khouloudbelguith** [comment]
Hi @ced--ced,

Thanks for your report.
You are using multilanguage, what is the exact other language are you using?
The friendly URL is set in all languages?

Thanks!

**Comment by ced--ced** [comment]
Hi @khouloudbelguith,

I'm using English (English) - en-us.

The friendly url is set but I don't what you mean by "in all languages", since the option is only on or off globally.

Thanks

![Screen Shot 2019-10-23 at 12 25 26 (2)](https://user-images.githubusercontent.com/71735/67388595-dd652580-f590-11e9-92e2-40dc581f0359.png)
![Screen Shot 2019-10-23 at 12 25 10 (2)](https://user-images.githubusercontent.com/71735/67388596-dd652580-f590-11e9-8435-2144fd97f1ea.png)

**Comment by khouloudbelguith** [comment]
@ced--ced, 
>The friendly url is set but I don't what you mean by "in all languages", since the option is only on or off globally.

I attached a screen record
https://drive.google.com/file/d/1_aZ4-GRBWCdWbHW4_YntAGj5q5Ga1wlT/view

Thanks to check & feedback.

**Comment by ced--ced** [comment]
Thanks for the screencast. Yes I can confirm the friendly url is set for all the languages.

**Comment by khouloudbelguith** [comment]
@ced--ced, if you enable the `Accented URL` on your shop, this issue occurs again?
![image](https://user-images.githubusercontent.com/16067358/67394237-21adf100-f5a4-11e9-987d-0c2f6248ae99.png)

Thanks!

**Comment by ced--ced** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@ced--ced,

You need to enable debug mode in your store and debug request which is sent for category save in your browser, using DevTools, so:

1. enable debug mode
2. go to the category page
3. open up developer tools
4. go to Network tab
5. save the category
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by ced--ced** [comment]
There is no error in Network.

**Comment by khouloudbelguith** [comment]
@ced--ced, could you please provide me the error log file, you can find it in the path `Projet_folder/var/logs`.
Thanks!

**Comment by ced--ced** [comment]
@khouloudbelguith, there you go
[20191008_exception.log](https://github.com/PrestaShop/PrestaShop/files/3763062/20191008_exception.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/3763063/prod.log)

**Comment by ced--ced** [comment]
Do you need the dev.log as well? The file is too big

**Comment by ced--ced** [comment]
@khouloudbelguith, I have reloaded the dev.log file
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3763110/dev.log)

**Comment by khouloudbelguith** [comment]
@ced--ced, did you use the `megamenu` module?
I found this exception

```
*ERROR* 	v1.7.6.1	2019/10/08 - 12:27:41: Table 'uftuzncu_energiefruit20190926hZNb7WVet.kptl_btmegamenu_group' doesn't exist<br /><br /><pre>SELECT *
                FROM `kptl_btmegamenu_group` gr
                LEFT JOIN kptl_btmegamenu_group_lang grl ON gr.id_btmegamenu_group = grl.id_btmegamenu_group AND grl.id_lang = 1
                WHERE (`id_shop` = 1)  ORDER BY gr.position</pre> at line 769 in file classes/db/Db.php
```

Thanks to check & feedback.

**Comment by ced--ced** [comment]
This is an error that has been corrected already.

**Comment by khouloudbelguith** [comment]
@ced--ced,

Could you please provide me the access link to your shop.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ced--ced** [comment]
Ok thanks

**Comment by khouloudbelguith** [comment]
@ced--ced, in your BO => Categories page => you have an extra field
![image](https://user-images.githubusercontent.com/16067358/67478766-0226cf00-f65d-11e9-886c-daddb5be69bf.png)
Is it introduced by a custom module?

Thanks!

**Comment by ced--ced** [comment]
Hi,

Yes it is but that’s not the problem. I have tried by deactivating it and the problem remains.

Thanks,

Cedric

**Comment by khouloudbelguith** [comment]
@ced--ced, what is the exact name of this module?

Thanks!

**Comment by ced--ced** [comment]
@khouloudbelguith, it's "Advanced Custom Fields".

**Comment by khouloudbelguith** [comment]
@ced--ced, I found the problem
https://drive.google.com/file/d/1Gfy9i2siBCrWy8O8FaZCxOZBOKeInCmu/view
It is the Apollo page Builder issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
