### ISSUE TITLE
Payment preferences (Back Office): lost carrier restriction data

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#16094]
**Describe the bug**
Lost carrier restriction data when having 2 carriers withe the same name.

**To Reproduce**
Let's say we ship for both France and Europe with 2 different carriers due to the delivery time difference:

1. for France we use "UPS Express Saver" (the name of the carrier) with a description: Home delivery within 24h.
2. for Europe we use "UPS Express Saver" (the name of the carrier) with a description: Home delivery within 1 to 3 days.

As you notice here, we have 2 carriers with the same name but with different descriptions. At this moment the table "XXX_module_carrier" has entry for each combination matching a carrier with payment method.

But when we open the "Payment preferences" - section "Carrier restrictions", we notice that there is only one line "UPS Express Saver" instead of 2 (for France and Europe). What happened, is that the query has really returned 2 carriers, but the display shows only one. Thus when we save, one carrier entry in "XXX_module_carrier" will be deleted. And this results in an error message when choosing this latter carrier (the one which has lost its entry in the "XXX_module_carrier" table) during checkout: "Unfortunately, there are no payment method available.".

The workaround is to ensure having carriers with different names: this way it worked. But the "Payment preferences" - section "Carrier restrictions" shows unique names only. And this causes data loss. Is it normal behavior or a bug?

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment]
Hi @jouino16,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
In the carriers Page, I have two carriers 
![image](https://user-images.githubusercontent.com/16067358/67464917-7d2fbb80-f644-11e9-9947-4270546cbbbb.png)
In the Payment preferences, I have only one carrier displayed
![image](https://user-images.githubusercontent.com/16067358/67464960-8f115e80-f644-11e9-9acd-dadad95f3f6a.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/11379

**Comment by jouino16** [comment]
@khouloudbelguith 
No, I  only did a workaround and named the carriers differently as follows:

- UPS Express Saver
- UPS Express Saver Europe

I searched a bit and I noticed that the data is retrieved correctly from the DB (2 carriers returned), but it looks like the form renderer checks whether it has already rendered a carrier with a specific name to avoid duplicates. 

Thank you and have a nice day!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/12379
