### ISSUE TITLE
Cannot create a page after deleting categories page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16098]
**Describe the bug**
After deleting the categories page, we cannot create a page associated with a subcategory of Home anymore
We have an error: The object cannot be loaded (or found)

**To Reproduce**
1. Go to BO => Design => Page
2. Create three categories page with the same name "cat1"
3. Delete all these categories with the bulk actions
4. Create a new category page with the same name
5. Create a page associated with this previous category
6. see the error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/67468789-68a2f180-f64b-11e9-972d-a8911431b64e.png)

https://drive.google.com/file/d/1W3zqVPzg8v7CFUoXWrSIT1huNXRUrrtM/view

**Additional information**
PrestaShop version: develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by PierreRambaud** [comment]
@khouloudbelguith Can you try again, I don't manage to reproduce it :(

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I still manage to reproduce the issue with the develop branch.
I followed these steps twice
>1.Go to BO => Design => Page
2.Create three categories page with the same name "cat1"
3.Delete all these categories with the bulk actions
4.Create a new category page with the same name
5.Create a page associated with this previous category

at the first time ok, but on the second time NOK.
https://drive.google.com/file/d/1xviOjNCoMPGAEY7YhxK2wdSYfKxaf63L/view

Thanks!
