### ISSUE TITLE
Minor issue: duplicate icon in the predefined selection

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16091]
**Describe the bug**
In the `blockreassurance`'s configuration page, we have a duplicate icon in the predefined selection, so we have a missing carrier icon.
As reported in this ticket: #16081 by @jouino16
**To Reproduce**
1. Go to BO => Module Manger page
2. Search for the blockreassurance module v4.1.1
3. Click on Configure button
4. Add a new block
5. Click on Modify icon 
6. See duplicated icons

![image](https://user-images.githubusercontent.com/16067358/67408091-c803f180-f5b8-11e9-859d-74a6791c31a7.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @Progi1984

**Comment by Progi1984** [comment]
Fixed in PrestaShop/blockreassurance#33
