### ISSUE TITLE
Add pagination for combinations listing

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16103]
Add pagination for combinations listing to avoid performances issues
By default display 10 combinations and a pagination system if there is more than 10 combinations

![capture d'écran_2110](https://user-images.githubusercontent.com/13449658/67483181-88471380-f665-11e9-98b3-5e44f0cedd55.png)

Don't allow to choose the number of elements by page to avoid performances issues if the user choose to much elements

**Comment by matks** [comment]
@marionf Having pagination is going to modify slightly multiple behaviors of current combinations list.

For example, the "search a combination by attribute" will only display the X first results. We must also adapt number of "pages" by search. We must think about how user goes back from "search results" state to "normal state". Like any listing.

**Comment by marionf** [comment]
Ping @MatShir

**Comment by marionf** [comment]
Issue related: https://github.com/PrestaShop/PrestaShop/issues/16108

**Comment by 5koder** [comment]
@marionf When is this going to be added? I cannot edit my products with a lot of combinations.

**Comment by MatShir** [comment]
Hi @5koder, 
This feature is planned for version 1.7.8 so for the end of the year. How many attributes do you have by product?

**Comment by 5koder** [comment]
@MatShir I have about 100 attributes (~700 combinations) all with their own images. It's a 'build a bag' sort product. Is there way I can get around the problem for now? Other than using software like Store Manager for Prestashop?

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/issues/16103

**Comment by pradeepKsrvastva** [comment]
@MatShir  @marionf Guys 1.7.8 is launched but still no pagination for combinations its very very essentials for stores selling highly customized products

**Comment by MatShir** [comment]
@pradeepKsrvastva I understand your frustration, we have reworked the page while remigrating the page in Symfony in the 8.1 such change could not fit in the 1.7.8.8 :/
