### ISSUE TITLE
As a merchant when I change a value for a combination, I want it to be automatically saved without clicking on Save

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16102]
As a merchant when I change a value for a combination in the list, I want it to be automatically saved without clicking on Save to save time and avoid performances issues

If I change the impact on price, reference, quantity or default combination it should be saved automatically
If the save is done successfully, display a success message: "**Settings successfully saved**" in _Admin.Notifications.Success_

If the save isn't done successfully, display an error message: "**Settings cannot be saved**" in _Admin.Notifications.Error_

**Please, use this type of notifications:**

![capture d'écran_2106](https://user-images.githubusercontent.com/13449658/67474896-7eb5af80-f655-11e9-9df5-8e15bdcf73d0.png)

![capture d'écran_2107](https://user-images.githubusercontent.com/13449658/67475395-66926000-f656-11e9-8f55-d59e7a63b9a6.png)

**Comment by marionf** [comment]
ping @LouiseBonnard for the wording

**Comment by elboletaire** [comment]
How is this the most priority must-have issue in front of actual bugs which are there since years ago?  Edit: ok now I'm wondering that, maybe, that list order is not important. But is still shocking to see this feature the very first one in that list (btw I'm talking about this list: #14773)

**Comment by MatShir** [comment]
Hi @elboletaire,
I can understand your frustration but the product page is currently been migrated to the framework Symfony. So there is a long list of major issues and more important than this one but we are going to rewrite this behavior anyway so let's do it right. The priority settled by the team does not depend only on the severity of the issues but also on the product roadmap, on pending project, and the community influence. If you want to alert us on specific issues don't hesitate to chat with us on the slack.
