### ISSUE TITLE
Display regression on BO product page with the filter by categories

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16106]
Display regression (develop) on BO product page with the filter by categories

Develop:

![capture d'écran_2108](https://user-images.githubusercontent.com/13449658/67482156-91cf7c00-f663-11e9-83a6-192e518f7cf4.png)

1.7.6.1:

![capture d'écran_2109](https://user-images.githubusercontent.com/13449658/67482105-84b28d00-f663-11e9-9672-d1d83ea8bb4f.png)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

The same issue with the develop branch.
![image](https://user-images.githubusercontent.com/16067358/67484690-e9241b00-f668-11e9-9c5f-b7a25abe2d3d.png)
I’ll add this to the debug roadmap.
Thanks!
