### ISSUE TITLE
As a merchant I want to edit my combination reference without editing it

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16101]
As a merchant I want to edit my combination reference without editing it to save time

Add a "Reference" column before "Impact on price" with inputs for each combination to be able to change it quickly 
This column should be displayed only with large screens

![capture d'écran_2105](https://user-images.githubusercontent.com/13449658/67473763-9429da00-f653-11e9-9edf-9c14619789e8.png)

**Comment by prestascott** [comment]
Thank you @marionf !
I think inputs in "Impact on price" and "Quantity" columns are way too large for its content and can be shrinked a little bit to make more space for the new "Reference" column. There is no need to show more than 2 numbers after the dot on the price. 

**Here is my prototype:**
![Issue 16101](https://user-images.githubusercontent.com/54888056/70042904-f9aca700-15bf-11ea-9af7-8977df90070c.png)


What do you think? @marionf @TristanLDD

**Comment by marionf** [comment]
All good, thank you @prestascott !

**Comment by MatShir** [comment]
Fixed by #23581
