### ISSUE TITLE
Statistics of doesn't work from 1 oct 2019

### ISSUE THREAD

**Issue by m4dh** [PrestaShop/PrestaShop#16118]
Sales statistics have stopped working since October 1 this year, it did not coincide with any update.
I see visits but, sale amount and orders doesn't work

<img width="674" alt="Zrzut ekranu 2019-10-25 o 11 10 43" src="https://user-images.githubusercontent.com/7033391/67558880-21366700-f718-11e9-9722-d24f0d05051c.png">
<img width="1147" alt="Zrzut ekranu 2019-10-25 o 11 10 28" src="https://user-images.githubusercontent.com/7033391/67558893-285d7500-f718-11e9-94fd-63526289bfda.png">
<img width="1159" alt="Zrzut ekranu 2019-10-25 o 11 10 12" src="https://user-images.githubusercontent.com/7033391/67558900-2bf0fc00-f718-11e9-8fad-90cc4efe8609.png">

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by sarahdib** [comment]
Hello @m4dh 

Thank you for your bug report.

Did you disable the option Enable invoices  in BO => Orders => Invoices ?

![Capture d’écran 2019-10-25 à 11 24 25](https://user-images.githubusercontent.com/3034677/67559898-1aa8ef00-f71a-11e9-9285-9956c200b184.png)

**Comment by m4dh** [comment]
Yes, Invoices are enabled.

**Comment by sarahdib** [comment]
@m4dh 
Could you try to generate invoices  in BO => Orders => Invoices by date 
![Capture d’écran 2019-10-25 à 11 43 31](https://user-images.githubusercontent.com/3034677/67561229-b9cee600-f71c-11e9-96a1-2c276024d60a.png)
And see if there is invoices.

**Comment by m4dh** [comment]
No pro forma invoices found for this period

<img width="1175" alt="Zrzut ekranu 2019-10-25 o 11 51 15" src="https://user-images.githubusercontent.com/7033391/67561813-cbfd5400-f71d-11e9-9c6c-913247d12a65.png">


i set generation of invoices from 01.10.2019 to 25.10.2019

**Comment by m4dh** [comment]
i can generate invoices in period before 01.10.2019

**Comment by sarahdib** [comment]
Can you try to generate invoices from 1-10-2019 to 25-10-2019 ?

**Comment by m4dh** [comment]
yes, system after generation change the dates

**Comment by sarahdib** [comment]
Do you have invoices generated or the alert ?

**Comment by m4dh** [comment]
in a mont before i have generated invoices

**Comment by sarahdib** [comment]
Could you try to make a screen record when you try to generate invoices from 1-10-2019 to 25-10-2019 ?

**Comment by m4dh** [comment]
this screen was sent before
<img width="1175" alt="Zrzut ekranu 2019-10-25 o 11 51 15" src="https://user-images.githubusercontent.com/7033391/67563626-5b583680-f721-11e9-8d28-a33fd8bab19f.png">

**Comment by sarahdib** [comment]
in the screenshot you generated invoices only for today. I need a screen record from 1-10-2019 to 25-10-2019

**Comment by m4dh** [comment]
i generate invoices from 01-10-2019 i 25-10-2019
after clicking button <generate> system change dates ... i write this 23 minutes ago  :-)

**Comment by m4dh** [comment]
> Do you have invoices generated or the alert ?

only alert

**Comment by sarahdib** [comment]
@m4dh The data is based on invoice if there is no invoice there is no stats. 

There is an issue already created for this bug #15319

**Comment by khouloudbelguith** [comment]
Duplicate of #15319
