### ISSUE TITLE
customer password reset link error

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#16112]
Prestashop 1.7.6.1 with debian 9 php 7.2.23
When customer try to reset own password, email sent well with link, but this link jump to same request reset page, and not on the page where customer can change own password.
As with friendly url as not.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/15JnkSiTojEwkNH4mc-fIi8bgLdLjpfPe/view
Here's my server configuration
![image](https://user-images.githubusercontent.com/16067358/67498671-221bba00-f680-11e9-9f3a-8426526108f9.png)
Thanks to check & feedback.

**Comment by centoasa** [comment]
@khouloudbelguith what do you think about this my issue?
The landing page is without box for new password
![Schermata del 2019-10-24 17-15-55](https://user-images.githubusercontent.com/5500935/67499925-221cb980-f682-11e9-8994-32cace25b6ee.png)

**Comment by centoasa** [comment]
@khouloudbelguith  just tried to reset password on backoffice, all works well!

**Comment by khouloudbelguith** [comment]
@centoasa, have you tried to contact your theme about this issue?
Thanks to check with them & feedback.

**Comment by centoasa** [comment]
was this module https://www.leotheme.com/module/prestashop-modules/828-boom-captcha-google-recaptcha.html create me issue! Deleted it, now all works well!

**Comment by khouloudbelguith** [comment]
@centoasa, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
