### ISSUE TITLE
When I want to check a category, it's like I clicked on it instead of just select it

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16119]
**Describe the bug**
When I want to check a category, it's like I clicked on it instead of just select it

**To Reproduce**
1. Go to Catalog > Categories
2. Try to check a checkbox
3. You are redirected like you have clicked on it

**Screenshots**
https://drive.google.com/open?id=1p89GeJ8XKjNZPewkjeUhZ_YLW_rOEJqK

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by PierreRambaud** [comment]
Should it be in the 1.7.6 backlog instead?

**Comment by matks** [comment]
I added it to both, as it was solved in both backlogs 😄
