### ISSUE TITLE
Non cumulative rebate codes problem

### ISSUE THREAD

**Issue by m4dh** [PrestaShop/PrestaShop#16117]
I have a rebate code that should not accumulate with other discounts
when I put in one item that already has a discount and use the code - the system blocks it
when I put in 2 items that have no discount - the system also grants me a discount for discounted items ...
<img width="1127" alt="Zrzut ekranu 2019-10-25 o 11 02 13" src="https://user-images.githubusercontent.com/7033391/67558262-f13a9400-f716-11e9-9f38-27b5d0abedad.png">
<img width="1136" alt="Zrzut ekranu 2019-10-25 o 11 01 05" src="https://user-images.githubusercontent.com/7033391/67558275-f992cf00-f716-11e9-949b-478396ea39a5.png">
<img width="1141" alt="Zrzut ekranu 2019-10-25 o 11 01 43" src="https://user-images.githubusercontent.com/7033391/67558288-fd265600-f716-11e9-8741-54664c9987f1.png">

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22-1+0~20190902.26+debian9~1.gbpd64eb7

**Comment by khouloudbelguith** [comment]
Hi @m4dh,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13704 to fix the issue.
It is fixed in the next version PS1.7.7.
Your ticket is a duplicate of #10300
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10300
