### ISSUE TITLE
Newly created addresses are saved with the wrong `id_customer`

### ISSUE THREAD

**Issue by levyn** [PrestaShop/PrestaShop#16116]
**Describe the bug**
Newly created addresses are saved with the wrong `id_customer`

**To Reproduce**
1. The system must have at least one guest account and one non-guest account (the guest account must be created earlier)
2. Go to BackOffice -> Orders -> Add new order
3. Type the customer name or email we created earlyer (two accounts with the same email)
4. Select the latest account (with the highest id)
5. Create a new address for this customer -> "Add a new address"
6. After we save the address, we will not see it in the list and cannot use it. Since it is not there. 
After the research I found out that the address was assigned to a user with the same email but with a guest account. 
There are two inaccuracies here: 
 - the user's search is done first by his email and not by the id, and therefore. This is not true, that is why the address was assigned to the wrong user. 
 - I don't think there should be any guest accounts on this list at all. You can't create a guest order from BackOffice.

The easiest solution is to swap conditions if we can get an id_customer, then we don't need to search for a user by email (see at the screenshot)
![579b04c740](https://user-images.githubusercontent.com/1076017/67504135-88f59f00-f691-11e9-8faf-bdeb7440f7ca.jpg)

**Additional information**
PrestaShop version: 1.6.* - 1.7.*
PHP version: 5.6, 7.0, 7.1

The PR [https://github.com/PrestaShop/PrestaShop/pull/16074](https://github.com/PrestaShop/PrestaShop/pull/16074)

**Comment by sarahdib** [comment]
Hello @levyn 

Thank you for your bug report. I reproduce the problem In 1.7.5 and 1.7.6
1.7.5.2 : https://drive.google.com/file/d/1xhJiqKG0RYMRxgRhqZN9BW_eJ0TeG2GI/view
1.7.6.1: https://drive.google.com/file/d/1TodEQm3g46VVxeZknEHg1em3YKxvVKnG/view

Step to reproduce : 
1. Create two orders with the same address mail guest 
2. Go to back office
3. Create an order using the guest account with the higher ID
4. Add an address in the create order process 
5. See that the address is not available for the order
6. Go to customer and check the customer 
7. See that the address is not add to the customer with the higher ID but the first one

@marionf & @colinegin wdyt ?

**Comment by marionf** [comment]
It's a bug, so I guess it should be fixed and the address associated to the good customer
