### ISSUE TITLE
can't load image for module

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#16135]
HEllo

we can't upload image and when we click on upload button there is an erreur on the f12 dev mode of chrome

also when i select a category when i want to manage my vertical menu so i refresh the page the category is not any more selected and i should do it again

issue with vertical menu
https://drive.google.com/file/d/1skDhps9IcV1ttNL3wfR_HBrdWAPwqCSN/view

https://drive.google.com/file/d/1vtCxiaWN5S_mc1js8WRREFgcF0k2KFsm/view

issue with banner

https://drive.google.com/file/d/1-xL5_gM89rooTfUFF5moDIjQ6eELvqbC/view

Regards

![mag](https://user-images.githubusercontent.com/11594433/67609521-22ea4400-f785-11e9-8533-a8e20162313e.png)

Version de PrestaShop : 1.7.5.2
nformations sur votre serveur Linux #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.3.10

Limite de mémoire : 128M

Temps maximal d'exécution : 30

Taille max. pour envoi de fichiers : 2M

**Comment by go-sudo** [comment]
Hi @khouloudbelguith any help please

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version, check and feedback.

**Comment by go-sudo** [comment]
HI @khouloudbelguith 

I did downgrade the pho to 7.2 and 7.1 but the issue persist 

```
Uncaught ReferenceError: OnBoarding is not defined
    at HTMLDocument.<anonymous> (index.php?controller=AdminModules&configure=splistingtabs&token=56d873f6e2a30e1eefa50c997787108a&editItem&id_splistingtabs=2&updateItemConfirmation:1126)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)
```

https://drive.google.com/file/d/11j6j2bPRiv_MdB28hhKsHbQMgeab-1Pl/view

**Comment by khouloudbelguith** [comment]
@go-sudo, thanks for your feedback.
The modules `vertical menu` & `banner` are not provided by PrestaShop.
As they are not provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

Trust me it's not the theme and the issue is elsewhere now i switched to the default theme and i tried the banner module by prestashop and I'm facing the same issue , when I click on browse button there's nothing happened and I can't even upgrade the prestashop as you see on the video 

https://drive.google.com/file/d/13gXxZwjV-EWaOH_oIPxG_n9lp96VQUNF/view

Uncaught ReferenceError: OnBoarding is not defined
    at HTMLDocument.<anonymous> (index.php?controller=AdminModules&configure=splistingtabs&token=56d873f6e2a30e1eefa50c997787108a&editItem&id_splistingtabs=2&updateItemConfirmation:1126)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, did you use the `SP Listing Tabs` module?
The error is related to this module:
```
 Uncaught ReferenceError: OnBoarding is not defined
at HTMLDocument. (index.php?controller=AdminModules&configure=splistingtabs&token=56d873f6e2a30e1eefa50c997787108a&editItem&id_splistingtabs=2&updateItemConfirmation:1126)
```
Thanks!

**Comment by go-sudo** [comment]
Hello
It's not recommended to install Prestashop from Plesk  or upload ZIP from file manager, I uploded the files with FTP and everything works correctly
Regards
