### ISSUE TITLE
No set Stores should hide "Our stores" from sitemap -> pages list.

### ISSUE THREAD

**Issue by Peterr-K** [PrestaShop/PrestaShop#16133]
No set stores in Backend - preferences - contact - stores, should hide "Our stores" from sitemap - pages list.

The "index.php?controller=stores" should also not work then.

**Comment by khouloudbelguith** [comment]
Hi @jannyba,

Thanks for your report.
I have the same behavior as PS1.7.6.1.
In fact, in the BO => ShopParameters => Contact => Stores Tab => The Parameters section doesn't exit.
It was available in PS1.6
![image](https://user-images.githubusercontent.com/16067358/67663600-31438600-f966-11e9-8847-3258fee63e9e.png)
So, Previously, we can Enable the "Display in the footer" option & "Display in the sitemap page" option for the Stores Page.
It is not the same case with PS1.7.
We should add this option.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @jannyba and @khouloudbelguith, this can be handled in the Design > Link Widget section of your back office. Edit the concerned block to select what links you want to display. ;-)

**Comment by LouiseBonnard** [comment]
But the sitemap part is weird, I'll look into it and keep you posted!

**Comment by LouiseBonnard** [comment]
Hey @jannyba, I've referenced this issue so that it can be studied when the Contact > Stores page will be migrated - at best for version 1.7.8.

**Comment by Hlavtox** [comment]
Hi @Peterr-K, I have made a PR that 404s the store page and hides it from the frontend sitemap, if no stores are configured.

Ping @kpodemski and @MatShir for confirmation
