### ISSUE TITLE
Error in classes/ProductAssembler.php

### ISSUE THREAD

**Issue by mmarquez** [PrestaShop/PrestaShop#16136]
PrestaShop version: 1.7.5.1
PHP version: 7.3

I've get this error:

PHP message: PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /**/classes/ProductAssembler.php on line 95

I've changed this line:

`if ($rows === false) {`

for this one:

`if (($rows === false) || (count($rows) === 0) || $rows[0] === null) {`

**Comment by khouloudbelguith** [comment]
Hi @mmarquez,
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version, check and feedback

**Comment by khouloudbelguith** [comment]
Hi @mmarquez,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
