### ISSUE TITLE
Combination

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16151]
Hi,
I can't manage 6000 combinations for a single product, what are the parameters I should increase?
Best regards

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

In the BO => Catalog => Products page => when you try to edit a product with 6000 combinations => blank page is displayed?

THanks!

**Comment by Webgaict** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@Webgaict,

We are working on the product page to fix all issues.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9809
