### ISSUE TITLE
ps_legalcompliance 1.7.6

### ISSUE THREAD

**Issue by cryptolikely** [PrestaShop/PrestaShop#16157]
I need one way to make Shipping costs + Taxes on the product page... 
At the moment we have only the product price without taxes. and taxes are added after the customer is clicking add to cart.

We want to have product price, taxes and shipping price on same page (product page).
Someone suggested to me to use ps_legalcompliance  but without any success. I'm not able neither to install it.
Looking for one instalation file, readme.. I don't see any instructions.
any advices? thanks

**Comment by khouloudbelguith** [comment]
Hi @zsocialmedia,

You can use this module to show shipping cost in the Product Page
https://addons.prestashop.com/fr/frais-de-port/20628-shipping-cost-on-product-s-page.html
In your product page, you can display the prices with taxes by editing the /Project_Folder/themes/classic/templates/catalog/_partials/product-prices.tpl
Replace this 

```
{if $priceDisplay == 2}
        <p class="product-without-taxes">{l s='%price% tax excl.' d='Shop.Theme.Catalog' sprintf=['%price%' => $product.price_tax_exc]}</p>
      {/if}
```

by this 

```
{*{if $priceDisplay == 2}*}
        <p class="product-without-taxes">{l s='%price% tax excl.' d='Shop.Theme.Catalog' sprintf=['%price%' => $product.price_tax_exc]}</p>
      {*{/if}*}
```

So, in your Products pages, you have two prices displayed, with/with no Tax.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @zsocialmedia,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
