### ISSUE TITLE
Cannot save field title when editing a block in blockreassurance with Safari

### ISSUE THREAD

**Issue by eCommerceWhiteKnight** [PrestaShop/PrestaShop#16152]
**Describe the bug**
You are unable to change or add a title since the module update. Will not save when new block is created. 

**To Reproduce**
1. Go to Modules  blockreassurance   Configure
2. Click on Edit or (+ new)
3. (new reassurance block) add image, save - 
or (default blocks) unable to change title - no text field  
4. (new reassurance block) See error - Cannot save, field title is a required field. (editing default blocks) 

*addendum 
Just tried with Firefox and Works ok, Safari is the issue.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @eCommerceWhiteKnight,

The title field in your case is empty, which is required.
You should set the title
![image](https://user-images.githubusercontent.com/16067358/67682233-2cdf9300-f98f-11e9-9083-b4b2be83f7a9.png)
Thanks to check & feedback.
PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

**Comment by eCommerceWhiteKnight** [comment]
Thanks for the Update. As far as i can tell so far there are no issues with running PHP7.3 with my current version of Prestashop. If any issues occur I will reduce the PHP version to 7.2 but so far all seems good. 

I have attached two screen shots, one from the latest Version of Firefox, and one from the latest version of Safari which was upgraded during the installation of Catalina (OSx 10.15) 74b.png is from Firefox and f44.png is from safari. I have tried dropping the version of PHP to 7.2 and there is no change in the issue :( 

![Screenshot_2019-10-28 Module Manager • Eutopia Components](https://user-images.githubusercontent.com/57034183/67698133-aaac9a00-f9a1-11e9-9e38-c7750336c74b.png)
![Screenshot 2019-10-28 at 16 35 11](https://user-images.githubusercontent.com/57034183/67698166-b6985c00-f9a1-11e9-8f3f-3644c64c8f44.png)

Thanks
Mat

**Comment by khouloudbelguith** [comment]
@eCommerceWhiteKnight, in your case, the title is missing.
I did not manage to reproduce the issue with PS1.7.6.1 using Safari browser v12.1.1
![image](https://user-images.githubusercontent.com/16067358/67699113-e0ef1700-f9ab-11e9-8c65-a52dc1487e66.png)
What is the exact version of your browser did you use?

Thanks!

**Comment by eCommerceWhiteKnight** [comment]
Version 13.0.2 (15608.2.30.1.1) It is with the Catalina update (10.15) and there has also been a security update since the osX version update. 

Mat

**Comment by khouloudbelguith** [comment]
@eCommerceWhiteKnight, with Safari v12 => it is OK.
I will try to check with v13 & feedback.

**Comment by khouloudbelguith** [comment]
@eCommerceWhiteKnight, I tried with Safari v13.0.3 & the `blockreassurance` v4.1.1 & it is well working
![image](https://user-images.githubusercontent.com/16067358/67943730-0150e880-fbdb-11e9-809d-cea0af74e9b5.png)

Thanks to check & feedback.

**Comment by piotro9x** [comment]
> **Describe the bug**
> You are unable to change or add a title since the module update. Will not save when new block is created.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Modules  blockreassurance   Configure
> 2. Click on Edit or (+ new)
> 3. (new reassurance block) add image, save -
>    or (default blocks) unable to change title - no text field
> 4. (new reassurance block) See error - Cannot save, field title is a required field. (editing default blocks)
> 
> *addendum
> Just tried with Firefox and Works ok, Safari is the issue.
> 
> **Screenshots**
> If applicable, add screenshots or screenrecords to help explain your problem.
> 
> **Additional information**
> PrestaShop version: 1.7.6.1
> PHP version: 7.3

I have the same problem, php 7.2 browser google chrome.
Have you found a solution to this problem?

**Comment by khouloudbelguith** [comment]
Hi @piotro9x,

What is the exact version PrestaShop did you use?
What is the exact browser version did you use?

Thanks!

**Comment by piotro9x** [comment]
Presta: 1.7.6.1
Chrome: 78.0.3904.97

**Comment by khouloudbelguith** [comment]
@piotro9x, I did not manage to reproduce the issue with PS1.7.6.1 & `blockreassurance` v4.1.1.
I attached a screen record
https://drive.google.com/file/d/1rPvLvcR1IAsEbXdIM3_76DZqy7yjfyF8/view

Thanks!

**Comment by piotro9x** [comment]
To the moment that is on the video, my module is OK, too. But the problem occurs after saving the text and re-editing it. 
When you enter the edit of a block of text, the edit field is missing text. But on the shop page teskt is visible.
Another thing I noticed that might be related to this problem is that I didn't have any default blocks in the module. 
At the beginning of my experience with prestashop I did something with this module but I don't remember. Maybe I accidentally modified something in files.

**Comment by khouloudbelguith** [comment]
@eCommerceWhiteKnight, it is ok with editing the blocks also.
https://drive.google.com/file/d/1d3_kTAZOJ9utQKcxDaAbrWT8zZWmCRRo/view
Can you try to re-install the module, clear cache, check & feedback?

Thanks!

**Comment by piotro9x** [comment]
Please see the video.
After entering the block edit icon, there is no text in the text field.
https://drive.google.com/file/d/1ko4-cUAckvDcXOzF221Vls1dOr9rTyLK/view
I did reinstallations. Unfortunately it doesn't help

**Comment by khouloudbelguith** [comment]
@eCommerceWhiteKnight, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by piotro9x** [comment]
I analyzed all report files.
When I try to run the module, debugging mode indicates the following errors:




> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4
> 
> Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
> [8] Undefined offset: 4










Notice w linii 47 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/c6/00/e8/c600e8bb5934f55896b68fa82df1e2725bad1b3f_0.file.title.tpl.php
[8] Undefined offset: 4

> echo call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'escape' ][ 0 ], array( $_smarty_tpl->tpl_vars['allblockByShop']->value[$_prefixVariable1][$_smarty_tpl->tpl_vars['block']->value['id_psreassurance']]['title'],'htmlall','UTF-8' ));

> 

Notice w linii 49 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
[8] Undefined offset: 4

> echo $_smarty_tpl->tpl_vars['allblockByShop']->value[$_prefixVariable2][$_smarty_tpl->tpl_vars['block']->value['id_psreassurance']]['description'];

> 

Notice w linii 55 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/92/05/81/920581808bb42e659d34d4f14f0c3a98e9fc3c9e_0.file.description.tpl.php
[8] Undefined offset: 4

> echo $_smarty_tpl->tpl_vars['allblockByShop']->value[$_prefixVariable3][$_smarty_tpl->tpl_vars['block']->value['id_psreassurance']]['description'];

> 

Notice w linii 53 w pliku /home/contactmkubo/websites/presta/var/cache/dev/smarty/compile/b7/73/bb/b773bb849d885f69902dcf541b4dd9e43b72ad75_0.file.url.tpl.php
[8] Undefined offset: 4

> echo $_smarty_tpl->tpl_vars['allblockByShop']->value[$_prefixVariable4][$_smarty_tpl->tpl_vars['block']->value['id_psreassurance']]['url'];

>

**Comment by khouloudbelguith** [comment]
Hi @piotro9x,

There is a lot of cache errors.
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by piotro9x** [comment]
Hello.
I deleted the contents of the folders. The 'prod' folder remains empty but in the 'dev' folder the files overwrite and errors still appear.

**Comment by khouloudbelguith** [comment]
@piotro9x, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @piotro9x,

I just received the email.
I will check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
@piotro9x, the Title field is well displayed when editing the block
https://drive.google.com/file/d/1-C8Eem4TAk1OE_UvBZQrS3nnN2lQsLRA/view
But, only I have warnings, related to your cache.
Thanks to check & feedback.

**Comment by piotro9x** [comment]
Yes, but each time you enter block editing, the titles in the editing window disappear and you must re-enter the title for each language. For example, if I had titles in all languages and enter the block edition, then to save all the titles I have to enter them all again. Is this the standard work of this module?
And one more question about the module. Should I have default blocks after reinstallation?
In my case, the blocks are empty. After adding blocks, I don't have bullets or lines separating blocks on the front of the store.
Thanks

**Comment by khouloudbelguith** [comment]
@piotro9x, I don't have access to your shop yet.
Thanks!

**Comment by piotro9x** [comment]
Please check now

**Comment by khouloudbelguith** [comment]
@piotro9x, yes!
Ok

**Comment by khouloudbelguith** [comment]
@piotro9x, I tried with a new install & an upgrade of the module.
The blocks by default are not created.
In my case, I did not manage to reproduce the issue.

Thanks!

**Comment by piotro9x** [comment]
OK. What about the first part of the question?
> Yes, but each time you enter block editing, the titles in the editing window disappear and you must re-enter the title for each language. For example, if I had titles in all languages and enter the block edition, then to save all the titles I have to enter them all again. Is this the standard work of this module?

**Comment by khouloudbelguith** [comment]
@piotro9x, it is only in your case also.
I tried with `blockressurance` & PS1.7.6.1 => OK.
But, in your case, there is no exception displayed can help us to understand what's wrong.

Thanks!

**Comment by piotro9x** [comment]
OK, thanks

**Comment by khouloudbelguith** [comment]
Hi @piotro9x, @eCommerceWhiteKnight,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
