### ISSUE TITLE
An error occurs when trying to register a hook whose name is longer than 64 characters

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#16169]
**Describe the bug**
Error!
Exception thrown by module on reset. Error when resetting module. The length of property Hook->name is currently 65 chars. It must be between 0 and 64 chars.

**To Reproduce**
Hook registration in the module.
$this->registerHook('actionBeforeAjaxDieOrderControllerdisplayAjaxselectDeliveryOption')

**Screenshots**
![image](https://user-images.githubusercontent.com/13940741/67746851-6b7d5800-fa38-11e9-99ac-2a06730676de.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @dmitrij1988,

Thanks for your report.
What is the exact name of the module do you need to reset it? it is provided by PrestaShop?

Thanks!

**Comment by ewonta** [comment]
This is in the documentation.
https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/

![image](https://user-images.githubusercontent.com/13940741/67747797-94065180-fa3a-11e9-9c8a-d5ab09efcbed.png)

**Comment by khouloudbelguith** [comment]
@dmitrij1988, as you can see in this documentation, it is deprecated since 1.6.1.1.
So, it is not used yet & you are using PS1.7.6.0, is it?

Thanks!

**Comment by ewonta** [comment]
I need to register a hook in the delivery module, no matter what old or new, they all register with an error!

**Comment by khouloudbelguith** [comment]
@dmitrij1988, I tried with this module https://addons.prestashop.com/en/collection-points-in-store-pick-up/1752-mondial-relay-official.html
It registers this hooks
```
      'actionAdminCarriersControllerDeleteAfter',
        'actionCarrierUpdate',
        'actionFrontControllerSetMedia',
        'displayBeforeCarrier',
        'displayCarrierList',
        'displayAfterCarrier',
        'actionCarrierProcess',
        'actionValidateStepComplete',
        'actionValidateOrder',
        'actionBeforeAjaxDieOrderOpcControllerinit',
        'actionAdminControllerSetMedia',
        'actionObjectAddressUpdateBefore',
        'actionObjectAddressDeleteBefore',
```
And it i well installed.
Thanks to check & feedback.

**Comment by ewonta** [comment]
Try this one
'actionBeforeAjaxDieOrderControllerdisplayAjaxselectDeliveryOption'

This hook works when you change the carrier

**Comment by khouloudbelguith** [comment]
@dmitrij1988, thanks for these clarifications.
 have the same issue with PS1.7.5.2 & the develop branch.
The problem must happen on the register, we should probably increase this limit.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
