### ISSUE TITLE
Images options in the product edit not appeared Prestashop 1.7.6.1

### ISSUE THREAD

**Issue by Stolaweb** [PrestaShop/PrestaShop#16177]
Can anyone solve this for me? I have the same problem. Pictures in product settings cannot be deleted and img options are not displayed. How to fix it? I have Prestashop 1.7.6.1. I can't make changes to product images. All I can do is remove the product and add it again.

screen product https://prnt.sc/ppnrk3

debug token: https://www.butiktest.hekko24.pl//fyxmmlllslsjlkivm/index.php/_profiler/31ea40?_token=ShlxDvDumvhPzaDY6qFN_kqY1ah2X2twskK_ePJfFTE

please help what to do

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3
Angara Theme

The error in the console Network Tab is:
Could not load type "form": class does not exist.
Exception
Symfony\Component\Form\Exception\
InvalidArgumentException
in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php (line 86)
            }            if (!$type) {                // Support fully-qualified class names                if (!class_exists($name)) {                    throw new InvalidArgumentException(sprintf('Could not load type "%s": class does not exist.', $name));                }                if (!is_subclass_of($name, 'Symfony\Component\Form\FormTypeInterface')) {                    throw new InvalidArgumentException(sprintf('Could not load type "%s": class does not implement "Symfony\Component\Form\FormTypeInterface".', $name));                }
FormRegistry->getType('form')
in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php (line 74)
        if (!\is_string($type)) {            throw new UnexpectedTypeException($type, 'string');        }        $type = $this->registry->getType($type);        $builder = $type->createBuilder($this, $name, $options);        // Explicitly call buildForm() in order to be able to override either        // createBuilder() or buildForm() in the resolved form type
FormFactory->createNamedBuilder('form_image', 'form', array('id' => 31, 'id_product' => '27', 'position' => '1', 'cover' => true, 'legend' => array(''), 'format' => 'jpg', 'base_image_url' => '/img/p/3/1/31'), array('csrf_protection' => false, 'data' => array('id' => 31, 'id_product' => '27', 'position' => '1', 'cover' => true, 'legend' => array(''), 'format' => 'jpg', 'base_image_url' => '/img/p/3/1/31')))
in src/PrestaShopBundle/Controller/Admin/ProductImageController.php (line 133)
            return new Response();        }        $image = $productAdapter->getImage((int)$idImage);        $form = $this->container->get('form.factory')->createNamedBuilder('form_image', 'form', $image, array('csrf_protection' => false))            ->add('legend', 'PrestaShopBundle\Form\Admin\Type\TranslateType', array(                'type' => 'Symfony\Component\Form\Extension\Core\Type\TextareaType',                'options' => array(),                'locales' => $locales,                'hideTabs' => true,
ProductImageController->formAction('31', object(Request))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
        $this->dispatcher->dispatch(KernelEvents::CONTROLLER_ARGUMENTS, $event);        $controller = $event->getController();        $arguments = $event->getArguments();        // call controller        $response = \call_user_func_array($controller, $arguments);        // view        if (!$response instanceof Response) {            $event = new GetResponseForControllerResultEvent($this, $request, $type, $response);            $this->dispatcher->dispatch(KernelEvents::VIEW, $event);
HttpKernel->handleRaw(object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
    public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)    {        $request->headers->set('X-Php-Ob-Level', ob_get_level());        try {            return $this->handleRaw($request, $type);        } catch (\Exception $e) {            if ($e instanceof RequestExceptionInterface) {                $e = new BadRequestHttpException($e->getMessage(), $e);            }            if (false === $catch) {
HttpKernel->handle(object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
        $this->boot();        ++$this->requestStackSize;        $this->resetServices = true;        try {            return $this->getHttpKernel()->handle($request, $type, $catch);        } finally {            --$this->requestStackSize;        }    }
Kernel->handle(object(Request), 1, false)
in fyxmrlznlsjlkivm/index.php (line 86)
$request = Request::createFromGlobals();Request::setTrustedProxies([], Request::HEADER_X_FORWARDED_ALL);try {    require_once __DIR__.'/../autoload.php';    $response = $kernel->handle($request, HttpKernelInterface::MASTER_REQUEST, false);    $response->send();    $kernel->terminate($request, $response);} catch (NotFoundHttpException $exception) {    define('ADMIN_LEGACY_CONTEXT', true);    // correct Apache charset (except if it's too late)

**Comment by khouloudbelguith** [comment]
Hi @Stolaweb,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by Stolaweb** [comment]
I am sorry, I have PHP 7.2

**Comment by Stolaweb** [comment]
I replace /src/PrestaShopBundle folder and it works.

I wil test and make a response

I hope that other things will also work without errors

**Comment by khouloudbelguith** [comment]
@Stolaweb, did you replace it by the original one? 

Thanks!

**Comment by Stolaweb** [comment]
Yes , from working another installation. But I have to test it if all things work good.

**Comment by khouloudbelguith** [comment]
@Stolaweb, thanks!
Since it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks!
