### ISSUE TITLE
Fallback to curl if allow_url_fopen is not present

### ISSUE THREAD

**Issue by bet0x** [PrestaShop/PrestaShop#16184]
**Is your feature request related to a problem?**

Fallback to curl if allow_url_fopen is not present.

**Describe the solution you'd like**
Well, yall moving to latest versions of Symfony so this is quite a good solution:
```php
use Symfony\Component\HttpClient\CurlHttpClient;
use Symfony\Component\HttpClient\NativeHttpClient;

// uses native PHP streams
$client = new NativeHttpClient();

// uses the cURL PHP extension
$client = new CurlHttpClient();
```
If Native HTTP is not present, you get the content with Curl. Will solve a lot of issues for web hostings without allow_url_fopen enabled.

**Comment by khouloudbelguith** [comment]
Hi @bet0x,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi @bet0x 
Could you tell us more about what you want exactly? In which context?

**Comment by bet0x** [comment]
@PierreRambaud You use file_get_contents, even for Prestashop core stuff. Using Symfony native method with fallback will prevent errors (in my case where i host i have no file_get_contents). Only curl extensions, so if you check for one or the other you will have always connection to the source.

**Comment by PierreRambaud** [comment]
Ohh, yes, this is something we will do later. Step by step, migrating our legacy to symfony is a really long task :/

**Comment by bet0x** [comment]
If you just grep the project and look for file_get_contents, then replace it for a middleware function to check if allow_url_fopen is enabled if not then you do 

```
$client = new CurlHttpClient();
$response = $client->request('GET', 'https://www.google.com/');
$responses = $response->getContent();
```

grep is your friend!

**Comment by PierreRambaud** [comment]
@matks @eternoendless I think it's a good idea to use newer component for file_get_contents (Replacing Tools::file_get_contents also)

**Comment by matks** [comment]
Doesn't it move the problem elsewhere ? Replacing file_get_contents by curl calls is going to move "I need allow_url_fopen" to "I need curl extension"

**Comment by bet0x** [comment]
> Doesn't it move the problem elsewhere ? Replacing file_get_contents by curl calls is going to move "I need allow_url_fopen" to "I need curl extension"

You are missing the whole point. If there is NativeHttpClient then you use it, if there is no NativeHttpClient you test for CurlHttpClient. It's a good practice to have at least 2 options, this is a critical component.

This has to be the most decent way to get it working for everyone.

```
<?php
include 'vendor/autoload.php';

use Symfony\Component\HttpClient\CurlHttpClient;
use Symfony\Component\HttpClient\NativeHttpClient;

if( ini_get('allow_url_fopen') ) {
  $client = new NativeHttpClient();
  $response = $client->request('GET', 'http://www..............');
  $headers = $response->getHeaders();
  echo "allow_url_fopen is enable"."\n";
  echo $headers['date'][0]."\n";

} elseif(in_array('curl', get_loaded_extensions())) {
  $client = new CurlHttpClient();
  $response = $client->request('GET', 'http://www..............');
  $headers = $response->getHeaders();
  echo "Curl is enable"."\n";
  echo $headers['date'][0]."\n";

} else {
  echo "CURL is not available on your web server and allow_url_fopen is disabled, install CURL or enable allow_url_fopen to proceed.";
}
```

You will save a lot of code and is more easy to implement. Far as i see you are doing it twice or more only in your ToolsCore.php file.

**Comment by PierreRambaud** [comment]
Just notice something but the cUrl extension is mandatory :thinking: 
Is it really needed to use the NativeHttpClient whereas curl is available?
