### ISSUE TITLE
Price formatter is not based on precision

### ISSUE THREAD

**Issue by pand-app** [PrestaShop/PrestaShop#16199]
Hello,

If I've KWD as a primary currency, prices will use currencyFormat which can be found in localization/CLDR/core/common/main/<lang>.xml

But, currency format != format number, and it's clearly not functional with KWD.

| price in BO | expected | what I get |
|------------|-----------|-----------|
| KWD 1.234 | KWD 1.234 | KWD 1.234 |
| KWD 1.23 | KWD 1.230 | KWD 1.23 |

When I have a product with the price 1.234 KWD
I think, this should rely on precision data available when I debug the app ?

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @Nainterceptor,

First of all, thanks for your report.
Second, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Finally, The first part of feature #[10052](https://github.com/PrestaShop/PrestaShop/issues/10052) is almost done which the implementation of the CLDR (the data needed to manage a maximum of currencies), Check the PR #10455

 It's planned to remove the number of the decimal parameter in Shop parameters > General, as you can see here: #12223
And it's also planned to add this feature in CLDR part 2: #11660

Thanks to check & feedback.

**Comment by pand-app** [comment]
Hello @khouloudbelguith, 
I know about PHP version, I've 7.2 in production, but 7.3 locally in dev environment.
I've few errors but it's working ;)

Any workaround for the current version ? I've dirty one (change format according to iso currency) but in src directory, so not overridable.

Thanks

**Comment by khouloudbelguith** [comment]
@Nainterceptor, I'm happy to hear that there is no issue with php7.3 on your staging server but as I said, currently PrestaShop is not compatible with php7.3. So some parts of the application might work, but there is no guarantee it works globally. Explications about why can be read here: http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

Sorry as I said before, It's planned to remove the number of the decimal parameter in Shop parameters > General, as you can see here: #12223
And it's also planned to add this feature in CLDR part 2: #11660

I close the issue, feel free to open a new one when needed.

Thanks:

**Comment by khouloudbelguith** [comment]
Duplicate of #12223
