### ISSUE TITLE
1 Clic upgrade bug

### ISSUE THREAD

**Issue by sextoysunivers** [PrestaShop/PrestaShop#16191]
**Describe the bug**
Hi,

After trying to upgrade with the 1 clic upgade module from 1.6.1.24  to 1.7.1.6 I get the follwong error :

Fatal error: Uncaught Symfony\Component\Config\Exception\FileLoaderLoadException: Cannot load resource "/var/www/src/PrestaShopBundle/Resources/config/services/bundle/form/form_type/desktop.ini". in /var/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/Loader.php:73 Stack trace: #0 /var/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(133): Symfony\Component\Config\Loader\Loader->resolve('/var/www/src/Pr...', NULL) #1 /var/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(79): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/src/Pr...', NULL, false, '/var/www/src/Pr...') #2 /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(196): Symfony\Component\Config\Loader\FileLoader->import('form_type/*', NULL, false, '/var/www/src/Pr...') #3 /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLo in /var/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/Loader.php on line 73

Thank you in advance for you help

Best regards,

JC

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.6.1.24
PHP version: 7.3

**Comment by matks** [comment]
Hi @sextoysunivers the file /var/www/src/PrestaShopBundle/Resources/config/services/bundle/form/form_type/desktop.ini should not exist, I think it was created by Windows when you opened the project files.

This is a windows-oriented file and is the reason why it crashes 😢

**Comment by sextoysunivers** [comment]
Hi Matks,
Thank you very much indeed. I'm going to try again this friday. After have seen that I went back to my previews version.

Fantastic thank you very much again.  I'm going to close this and reopen if need it
All the best
