### ISSUE TITLE
Proper way to detect incompatible modules and themes

### ISSUE THREAD

**Issue by bet0x** [PrestaShop/PrestaShop#16208]
**Is your feature request related to a problem?**
When browsing for modules and themes i encounter several problems as a new Prestashop user:

* Themes can be for old or new versions of PS.
* Modules can be for old or new versions of PS.

**Describe the solution you'd like**
Add a file (like composer.json) with a tested version on it (branch), example:
```
{
    "name": "mytheme",
    "ps_min_version": "1.7.7.0",
    "description": "My theme description here",
    "license": "OSL-3.0",
    "author": "bet0x"
    "author_url": "http://author.url",
    "author_support": "http://author.url/support"
}
```

This idea can be also applied to modules as you can see. I encounter several issues with the current development on almost all versions, including the devel one on GIT.

**Comment by khouloudbelguith** [comment]
Hi @bet0x,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment]
@PrestaShop/prestashop-contributors what do you guys think ?

**Comment by Progi1984** [comment]
The concept of a metadata file for each module/theme exists in anothers CMS :
* [blueprints.yaml for Grav](https://learn.getgrav.org/16/forms/blueprints#themes-and-plugins) 
* [composer.json for CraftCMS](https://docs.craftcms.com/v3/extend/plugin-guide.html#composer-json)
* [module.xml for Magento](https://devdocs.magento.com/videos/fundamentals/create-a-new-module/#make-sure-you-have-permission-to-create-files-and-folders-in-your-installation)
* [.info.yaml for Drupal](https://www.drupal.org/docs/8/creating-custom-modules/let-drupal-8-know-about-your-module-with-an-infoyml-file)
* [paquet.xml/plugin.xml for Spip](https://programmer.spip.net/paquet-xml)
* [XML file for Joomla](https://docs.joomla.org/J3.x:Creating_a_Plugin_for_Joomla)
* [desc.xml for Dotclear](https://fr.dotclear.org/documentation/1.2/contribute/plugin-creation#le-fichier-descxml)
* ...

**Comment by jolelievre** [comment]
We already use `composer.json` for native modules, and composer manages a special dependency type `"type": "prestashop-module"` to automatically install them in the modules directory
However I don't think it's possible to manage the required PrestaShop version in the module's composer.json file It is managed in the module class

**Comment by bet0x** [comment]
@jolelievre That's why i made a special example.

**Comment by jolelievre** [comment]
So this would be the composer.json of your module? So we would need to add a feature to composer so that it can interpret this field. I wonder if it's possible..

It would be cleaner to use a dependency in the module, like any other dependency But the thing is PrestaShop can't really be counted as a dependency I guess, to do that properly we would need to extract the core methods into a dedicated repo, although it would be nice to separate PrestaShop into several independent dependencies I don't think it's in the roadmap for now

So do you have an idea about how we could deal with this new field?

**Comment by bet0x** [comment]
> So do you have an idea about how we could deal with this new field?

Add an extra required file, like a theme.yml or module.yml and store those variables there, if the module requires develop branch or X version. 

I think when i mentioned composer i got you confused. Doesn't need to be composer or composer has something like this.

**Comment by PierreRambaud** [comment]
I think it's a good idea. 
Today we are based on values stored in `mymodule.php` which mean, if this file is not properly loaded, we can have a 500 errors.
Composer is not used by everyone but why not adding a Composer plugin to check these new information and make it mandatory in the future :thinking:

**Comment by bet0x** [comment]
> I think it's a good idea.
> Today we are based on values stored in `mymodule.php` which mean, if this file is not properly loaded, we can have a 500 errors.
> Composer is not used by everyone but why not adding a Composer plugin to check these new information and make it mandatory in the future 🤔

It happened to me.
I downloaded a theme after git cloning the dev branch, i just uploaded it into the theme folder and i got an error 500.

So this is a real need, a check to see if something is compatible or not. Modules and Themes alike.

**Comment by PierreRambaud** [comment]
@PrestaShop/prestashop-maintainers What do you think about adding metadata in modules, and if present (will be mandatory in the next major) check it before loading the moduleµ?

**Comment by Progi1984** [comment]
Which metadata do you think ?
