### ISSUE TITLE
No way to use other category thumbnail image than small_default

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [PrestaShop/PrestaShop#16206]
Hi,

Prestashop Version : All, included github.

Code illustrated in the image attached illustrate that it is impossible to use other image format for categories thumbnail than small_default.

::getFormattedName start to implement the use of format like small_<theme_name> but the method ::getByNameNType return always false because type and order are not provided.

It is an old problem that clearly need to pay attention.
It should be allowed to use categories thumbnail format other that small_default.
One example of use is : I want thumbnails of categories with sizes different from those of the products

![image](https://user-images.githubusercontent.com/4049969/67859030-e6b73a80-fb1a-11e9-8df8-ebb6df366e31.png)

Best regards

**Comment by jf-viguier** [comment]
Should be a good improvement.

**Comment by khouloudbelguith** [comment]
Hi @nicoja,

Thanks for your report.
Just for information, the thumbnail is not used in the classic template.
The small_default is used for categories also
![image](https://user-images.githubusercontent.com/16067358/67861446-888d5600-fb20-11e9-89f2-301219c02eaa.png)
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by Kixell-NicolasJardillier** [comment]
I know @khouloudbelguith

**Comment by MatShir** [comment]
Closing this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/30520
Don't hesitate to comment if I missed something :)
Duplicate of #30520
