### ISSUE TITLE
Modules Tab  500 Internal Server Error - FatalErrorException 

### ISSUE THREAD

**Issue by Mosquito65** [PrestaShop/PrestaShop#16205]
Ificlic on Modules tab appear  500 Internal Server Error - FatalErrorException 
![Screenshot_2019-10-30 Compile Error Arrays are not allowed in class constants (500 Internal Server Error)](https://user-images.githubusercontent.com/57178906/67855595-021e4780-fb13-11e9-9540-a26af3db7aff.png)

**Comment by khouloudbelguith** [comment]
Hi @Mosquito65,

What is the exact version PrestaShop did you use? & what is the exact version of the module `blockreassurance` you are using?

Thanks!

**Comment by Mosquito65** [comment]
The version of Prestashop is 1.7.2.4
I don't know the version of the module blockreassurance 
How can I verify?

**Comment by khouloudbelguith** [comment]
@Mosquito65, you can check it in the `Project_Folder/modules/blockreassurance/config.xml` file
https://github.com/PrestaShop/blockreassurance/blob/master/config.xml#L5

Thanks!

**Comment by Mosquito65** [comment]
I've updated this module yesterday
version 4.1.1

**Comment by khouloudbelguith** [comment]
@Mosquito65, in my case, I did not manage to reproduce the issue with PS1.7.2.4 & the blockreassurance v4.1.1.
I attached a screen record
https://drive.google.com/file/d/18E_mTzWDB3USyRVRGpOR2dQL7Qxc9Iek/view
Could you please try to re-install the blockreassurance module, check & feedback.

**Comment by Mosquito65** [comment]
Hi
how can I re-install the blockreassurance module?
If I Click on the Modules Tab appear 500 Internal Server Error - FatalErrorException

**Comment by khouloudbelguith** [comment]
@Mosquito65, you can follow these steps:
1. Remove or rename the `blockreassurance` folder in this path `Project_Folder/modules/`
2. Try to clear cache manually by deleting all the folder into app/cache (prod & dev)
3. Go to the BO => Module Catalog => search the module & install it again.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Mosquito65,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by MouRadB8** [comment]
i have the same problem
