### ISSUE TITLE
Webservice 500 Internal Server Error on update order

### ISSUE THREAD

**Issue by aavinseth** [PrestaShop/PrestaShop#16201]
**Describe the bug**

**To Reproduce**
1. In Webservice hit orders/ORDER_ID API
2. Copy XML response and change **current_state** parameter and submit as a put request
3. Response: 500 Internal Server Error
4. See error: PHP Fatal error:  Uncaught PrestaShopException: Property Order->id_address_delivery is not valid in D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php:1004\nStack trace:\n#0 D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php(292): ObjectModelCore->validateFields()\n#1 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(307): ObjectModelCore->getFields()\n#2 D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php(738): OrderCore->getFields()\n#3 D:\\xampp\\htdocs\\prestashop\\classes\\order\\OrderHistory.php(358): ObjectModelCore->update()\n#4 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(1670): OrderHistoryCore->changeIdOrderState(5, Object(Order))\n#5 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(2407): OrderCore->setCurrentState('\\n            5\\n...')\n#6 D:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1574): OrderCore->setWsCurrentState('\\n            5\\n...')\n#7 D:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1419): WebserviceRequestCore->saveEntityFromXml(200)\n#8 D:\\xampp\\htdocs\\prestashop\\c in D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php on line 1004

**Screenshots**
Requested XML data using Webservice Order API
![image](https://user-images.githubusercontent.com/5337520/67832417-98e50700-fb07-11e9-929c-a45973234d3e.png)

On update order using PUT method, response is **500 Internal Server Error**
PHP Fatal error:  Uncaught PrestaShopException: Property Order->id_address_delivery is not valid in D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php:1004\nStack trace:\n#0 D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php(292): ObjectModelCore->validateFields()\n#1 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(307): ObjectModelCore->getFields()\n#2 D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php(738): OrderCore->getFields()\n#3 D:\\xampp\\htdocs\\prestashop\\classes\\order\\OrderHistory.php(358): ObjectModelCore->update()\n#4 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(1670): OrderHistoryCore->changeIdOrderState(5, Object(Order))\n#5 D:\\xampp\\htdocs\\prestashop\\classes\\order\\Order.php(2407): OrderCore->setCurrentState('\\n            5\\n...')\n#6 D:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1574): OrderCore->setWsCurrentState('\\n            5\\n...')\n#7 D:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1419): WebserviceRequestCore->saveEntityFromXml(200)\n#8 D:\\xampp\\htdocs\\prestashop\\c in D:\\xampp\\htdocs\\prestashop\\classes\\ObjectModel.php on line 1004
![image](https://user-images.githubusercontent.com/5337520/67832475-c92ca580-fb07-11e9-9a89-613deebaf73a.png)

Current State list in prestashop database ps_order_state_lang table
![image](https://user-images.githubusercontent.com/5337520/67832593-27598880-fb08-11e9-83a2-282629973c77.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3.6

**Comment by khouloudbelguith** [comment]
Hi @aavinseth,

First of all, thanks for your report.
Second, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Finally, in your case, the `id_address_delivery` is not correct in your case.
I used this script:

```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 30/10/19
 * Time: 08:01
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop.com');
define('PS_WS_AUTH_KEY', 'key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'http://shop.com',
    'Key',
    false);
$id = 11; //ID order Here
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
unset($xml->order->current_state);
$xml->order->shipping_number = 10;
$xml->order->current_state = 4;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'orders';
$xml = $ws->edit($opt);
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo $xml->asXML();
```

Thanks to check & feedback.

**Comment by aavinseth** [comment]
Hey @khouloudbelguith 

I have tried it on PHP 7.2, but still getting the same error.

Uncaught PrestaShopException: Property Order->id_address_delivery is not valid in E:\\xampp1\\htdocs\\prestashop\\classes\\ObjectModel.php:1004\nStack trace:\n#0 E:\\xampp1\\htdocs\\prestashop\\classes\\ObjectModel.php(292): ObjectModelCore->validateFields()\n#1 E:\\xampp1\\htdocs\\prestashop\\classes\\order\\Order.php(307): ObjectModelCore->getFields()\n#2 E:\\xampp1\\htdocs\\prestashop\\classes\\ObjectModel.php(738): OrderCore->getFields()\n#3 E:\\xampp1\\htdocs\\prestashop\\classes\\order\\OrderHistory.php(358): ObjectModelCore->update()\n#4 E:\\xampp1\\htdocs\\prestashop\\classes\\order\\Order.php(1670): OrderHistoryCore->changeIdOrderState(5, Object(Order))\n#5 E:\\xampp1\\htdocs\\prestashop\\classes\\order\\Order.php(2407): OrderCore->setCurrentState('\\n           5\\n ...')\n#6 E:\\xampp1\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1574): OrderCore->setWsCurrentState('\\n           5\\n ...')\n#7 E:\\xampp1\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1419): WebserviceRequestCore->saveEntityFromXml(200)\n#8 E:\\xampp1\\htdocs\\pr in E:\\xampp1\\htdocs\\prestashop\\classes\\ObjectModel.php on line 1004

and in code which you have send, i want to pass a Auth key as
http://J8PHWJUPVDV55DS5EBMMX6SA6RNYQQNY@localhost/prestashop/ format. So, is there any way in PSWebServiceLibrary file?

**Comment by khouloudbelguith** [comment]
@aavinseth, in your script, you have invalid Property `id_address_delivery`.
`Property Order->id_address_delivery is not valid in`
So please check the `id_address_delivery` in your script.
It is causing this issue.

Thanks!

**Comment by aavinseth** [comment]
@khouloudbelguith if i does't pass `id_address_delivery`, then it give error **400 Bad Request id_address_delivery is required**. See below screenshot for the same. Even i am passing the same id which i am getting in get method response for parameter `id_address_delivery`.

![image](https://user-images.githubusercontent.com/5337520/67920613-dc547980-fbca-11e9-8cc0-c8ea306bb028.png)

**Comment by khouloudbelguith** [comment]
@aavinseth, thanks to add the "id_address_delivery" to your XML sent since it is required, it is similar to `id_address_invoice`.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @aavinseth,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
