### ISSUE TITLE
Possible regression causes invalid complaint on add to cart regarding customization fields

### ISSUE THREAD

**Issue by watou** [PrestaShop/PrestaShop#16200]
The code change here: https://github.com/PrestaShop/PrestaShop/commit/b552eaa904d631f7e069660658fffe2414262eba#diff-0dac05a6abe4d202319dd093b8ab2b37L352 changed the condition tested to learn if the product had uncompleted customization fields and shows a popup with the warning 

> Please fill in all of the required fields, and then save your customizations.

However the product has no customizations, and so the `if` condition is incorrect.  

```diff
-  if (!$product->hasAllRequiredCustomizableFields() && !$this->customization_id) {
+  if ($product->hasActivatedRequiredCustomizableFields() && !$this->customization_id) {

```

When I reverted the `if` condition as shown above, my shop started to handle the situation better.

Please see if this is a regression that can be fixed.

**Comment by khouloudbelguith** [comment]
Hi @watou,

Thanks for your bug report.
Could you please provide me the exact steps to reproduce the issue?

Thanks!

**Comment by watou** [comment]
Hi @khouloudbelguith,

The exact steps were to run a production multisite shop under 1.7.5.0 on Ubuntu 14.04 and PHP 7.0 for several months, move it to Ubuntu 18.04 and PHP 7.2, and when attempting to add certain products to the cart, receive instead a popup reporting:

> Please fill in all of the required fields, and then save your customizations.

However, that product, and no other products in the shop have customisations defined.

When reverting the `if` condition in PR #8478 as described, this popup no longer appears, and no other problems have yet been seen.

It might make sense for those who reviewed that PR to consider this change again.  Thank you.

Below is the information for the old vs. new server configurations:

## OLD SERVER

### Server information

- Server information Linux #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64
- Server software version: Apache/2.4.7 (Ubuntu)
- PHP version: 7.0.33-6+ubuntu14.04.1+deb.sury.org+3
- Memory limit: 128M
- Max execution time: 30
- Upload Max File size: 2M
- PageSpeed module for Apache installed (mod_instaweb)

### Database information

- MySQL version: 5.5.62-0ubuntu0.14.04.1
- MySQL server: 127.0.0.1
- MySQL name: xxxxx
- MySQL user: xxxxx
- Tables prefix: ps_
- MySQL engine: InnoDB
- MySQL driver: DbPDO

### Store information

- PrestaShop version: 1.7.5.0
- Shop URL: http://xxxxx/
- Current theme in use: PRS01

### Mail configuration

- Mail method: You are using your own SMTP parameters.
- SMTP server: mail.xxxxx.net
- SMTP username: Defined
- SMTP password: Defined
- Encryption: ssl
- SMTP port: 465

### Your information

- Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

### Check your configuration

- Required parameters: OK
- Optional parameters: OK

### List of changed files

- No change has been detected in your files.


## NEW SERVER

### Server information

- Server information Linux #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
- Server software version: Apache/2.4.29 (Ubuntu)
- PHP version: 7.2.19-0ubuntu0.18.04.2
- Memory limit: 128M
- Max execution time: 30
- Upload Max File size: 2M

### Database information

- MySQL version: 5.7.27-0ubuntu0.18.04.1
- MySQL server: 127.0.0.1
- MySQL name: xxxxx
- MySQL user: xxxxx
- Tables prefix: ps_
- MySQL engine: InnoDB
- MySQL driver: DbPDO

### Store information

- PrestaShop version: 1.7.5.0
- Shop URL: http://xxxxx/
- Current theme in use: PRS01

### Mail configuration

- Mail method: You are using your own SMTP parameters.
- SMTP server: mail.xxxxx.net
- SMTP username: Defined
- SMTP password: Defined
- Encryption: ssl
- SMTP port: 465

### Your information

- Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

### Check your configuration

- Required parameters: OK
- Optional parameters: OK

### List of changed files

- No change has been detected in your files.

**Comment by khouloudbelguith** [comment]
>However, that product, and no other products in the shop have customizations defined.

So, when you add a product, which doesn't have customization, to the cart => the pop up is not displayed?

![image](https://user-images.githubusercontent.com/16067358/67866084-ae1e5d80-fb28-11e9-9959-fc38b99201fb.png)

Thanks!

**Comment by watou** [comment]
> So, when you add a product, which doesn't have customization, to the cart => the pop up is not displayed?

In fact a very similar popup *is* displayed, but the left side of the popup only has the word "Quantity:" and no other information on the left, the total count of items in the cart shown on the right is unchanged by adding the product to the cart (that is, it was not added), and overlaying all of that is the reddish popup complaining "Please fill in all of the required fields, and then save your customizations."

The analysis could focus on the one difference: Is the conditional expression

```php
$product->hasActivatedRequiredCustomizableFields()
```
more or less appropriate than

```php
!$product->hasAllRequiredCustomizableFields()
```
which was used before the PR, and what testing was performed before merge to verify that?  My empirical experience, after moving servers and from PHP 7.0 to 7.2, was that `$product->hasActivatedRequiredCustomizableFields()` caused a problem that is resolved by using the previous `!$product->hasAllRequiredCustomizableFields()` instead.

**Comment by khouloudbelguith** [comment]
@watou, so in your case, you have a product without customization but, when you try to add this product to the cart => "Please fill in all of the required fields, and then save your customizations." => this is incorrect.
In my case, I tried with PS1.7.5.1 & PHP7.2.
If a product has a required customization
"Add to cart is disabled => Until I add customization"
If not => the product is well added to the cart.
https://drive.google.com/file/d/1qdzJzocZqOvA8rArGxef8dJARXJEoEIV/view
Thanks to check & feedback.

**Comment by watou** [comment]
@khouloudbelguith Yes, your description of my experience is accurate.  Further, when I revert the change to the `if` condition described above, the problem no longer appears.

In your case, you are not able to replicate my situation which is quite understandable.  Hopefully a developer can assess what the correct test is so that products without customisations never see this error popup, and it is only presented when it is indeed accurate.  Also, the PR review process and test coverage should examine this particular code change.  Thank you.

**Comment by khouloudbelguith** [comment]
@watou, I tried with another case, customization which is not required but I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1H-uzf69UlOvMN93kugyYaJ0RwLdIBGh6/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!!

**Comment by watou** [comment]
I believe it is overall harmful to the product to close issues simply because they cannot be reproduced in contrived lab environments.  When others find this odd behaviour in their own configurations, the presence of this prematurely closed issue will hopefully be found in their search so they will know at least that they are not alone, but they will sadly conclude that the development process will have failed to properly investigate this obviously critical flaw and thus they will doubt the overall product.

**Comment by matks** [comment]
@watou There are over 1300 open issues on PrestaShop, that is why we close the issues on which we cannot act. Issues are not a registry of possible bugs, it's rather items that need an action.

When someone, be it a prestashop developer or a contributor, can provide accurate steps and environment to reproduce this bug we'll be happy to put it in the roadmap. Until then we must focus on what we can act.

**Comment by watou** [comment]
@matks Thank you for writing.  I gave many bits of information and suggestions regarding steps to take to evaluate the process whereby this specific code change was made and to evaluate the code change by analysis.  The issue was instead only treated as something to consider if it could be reproduced in a lab environment, and all of that input seems to have been ignored.  If your development resources are only allowed to be tasked under that constraint, the rate at which the product is improved seems regrettably rigid and slow.  Ultimately this is viewed poorly by users, regardless of justifications.  Kind regards, John Cocula

**Comment by khouloudbelguith** [comment]
Hi @watou,

I tried with different versions to reproduce the issue => but it is Ok in my side.
In your case, you are using a different theme not the default one provided by PrestaShop =>PRS01.

Could you please try to change your theme, clear cache & check the issue again.
I will re-open until your feedback.

**Comment by watou** [comment]
The method `Product::hasAllRequiredCustomizableFields` calls the method `Product::getRequiredCustomizableFields`, which calls the method `Product::getRequiredCustomizableFieldsStatic`.  This last method performs the following query:

```sql
           SELECT `id_customization_field`, `type`
            FROM `' . _DB_PREFIX_ . 'customization_field`
            WHERE `id_product` = ' . (int) $id . '
            AND `required` = 1'
```

However my database has a row in this table for product 22 (one of the products that present the incorrect popup `Please fill in all of the required fields, and then save your customizations.`  This row has these data:

```sql
INSERT INTO `ps_customization_field` (`id_customization_field`, `id_product`, `type`, `required`, `is_module`, `is_deleted`) VALUES
(1, 22, 1, 1, 0, 1);
```

The BO does not show this customization field, probably due to the `is_deleted` being `1`.  However, you can see the above `SELECT` query does not account for the `is_deleted` value.

This leaves the user in an impossible situation where there is no customization data for the product as far as they can see because it's been deleted and not visible in the BO but a row still exists in the database.  The new code path introduced in the PR referenced above does not consider the `is_deleted` value in its `SELECT` query.

Separately, I believe my point still stands that developers ought to be doing this analysis even in absence of the ability to reproduce reported bugs in house.  Regards, John

**Comment by khouloudbelguith** [comment]
@watou,
Could you please confirm these steps:
1. you are creating a new product 
2. In the BO => Product => Product details page => Options Tab => you have a Customization?
Is it one customization or more?
Is it a Text or a file?
Is it required or not
![image](https://user-images.githubusercontent.com/16067358/67941775-b0d78c00-fbd6-11e9-9a27-d410f00d548b.png)
3. Does your product have a quantity or out of stock?
4. What is the exact behavior when out of stock? Deny orders or Allow orders?
![image](https://user-images.githubusercontent.com/16067358/67941905-e4b2b180-fbd6-11e9-9b9c-5f2d5fe32e7d.png)


Thanks!

**Comment by watou** [comment]
Hi @khouloudbelguith,

The steps were that at some point in the past, a BO user had created a customization for a product, by some means it gained the value `is_deleted` set to `1`, it no longer appears in the BO under that product, and yet, with PS 1.7.5.0 and the code change in PR #8478, this product incorrectly complains when trying to add to the cart.

I recommend that you focus on how rows are created or modified in the `customization_field` table with `is_deleted` set to `1`, and then try to test against the related product.

[Surely this issue can certainly stay open and be acted on by a developer now?  If you have some hard-and-fast rule that you have to recreate the problem in the lab before a developer can spend any time on it, then let me gently suggest that that is a disastrous rule for the product's future prospects.]

Thank you.

**Comment by khouloudbelguith** [comment]
@watou, did you make an upgrade from a previous version PrestaShop (less than 1.7.3.0) to PS1.7.5.0?
So, for example, => you deleted a customization => after the upgrade the issue occurs?

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Than or developers can review your code & our QA team can test the PR.
Thank you!

**Comment by watou** [comment]
This PS site was first set up in or around March/April 2018, so whatever the latest version was at the time was used, and then later upgraded to 1.7.5.0.

I can make a pull request, but I cannot rigorously test it with to stand behind the assertion that it does not have other unwanted side effects.  Only seeing internal uses of the method `getRequiredCustomizableFields` suggests that adding `AND is_deleted = 0` won't hurt, but was the `is_deleted` column removed in subsequent releases?  If so, my PR will definitely break things. I just hope those who review PRs are sufficiently sceptical, because one point of this issue is as regards insufficient review/testing of PR #8478 (with no ill meant towards whomever made that great contribution).  With that caveat, please expect a PR soon.

**Comment by watou** [comment]
Problem was already fixed in PR #15739.

**Comment by watou** [comment]
Duplicate of #13211.

**Comment by khouloudbelguith** [comment]
@watou, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #13211

**Comment by matks** [comment]
> [Surely this issue can certainly stay open and be acted on by a developer now? If you have some hard-and-fast rule that you have to recreate the problem in the lab before a developer can spend any time on it, then let me gently suggest that that is a disastrous rule for the product's future prospects.]

I think you are confusing project and product and this is why you have expectations that we do not meet. Please read https://opensource.com/business/15/8/open-source-products-four-rules that might help you understand why we have and apply this "disastrous rule" 😉

**Comment by watou** [comment]
@matks Ultimately time will tell if your "not my problem, I'm working on a project not a product" attitude will help or hurt the adoption and retention of this product.  To tell an outsider that he is confused and using the wrong concepts is really a bad sign in my opinion.  I really don't wish to risk repeating the points I've made in this issue, so please have a great day and all the best to you.

**Comment by matks** [comment]
> so please have a great day and all the best to you.

Sorry we could not understand each other. Wishing you a great day too
