### ISSUE TITLE
Product photos do not show 1.7.6.1

### ISSUE THREAD

**Issue by cosmoscrystals** [PrestaShop/PrestaShop#16215]
This is a new fresh install of 1.7.6.1
Php 7.2
I'm trying to put my first product and the product pics do not show.  I've tried everything that I've found on the net and here to fix it but nothing fixed the issue.  I saw a post where someone replaced a directory to fix the issue.  I do not have an old directory so I can't do that.

If I click the zoom link the images show in a popup.

Any suggestions?

**Comment by khouloudbelguith** [comment]
Hi @cosmoscrystals,

Could you please navigate to the BO => Design => Images Settings page => Click on the "Regenerate thumbnails" button, thanks to check & feedback.

**Comment by cosmoscrystals** [comment]
I regenerated.  The images still do not show.

**Comment by khouloudbelguith** [comment]
@cosmoscrystals,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by cosmoscrystals** [comment]
I tried that a few times and it didn't work.  I just tried it again and it didn't fix the issue.

**Comment by khouloudbelguith** [comment]
@cosmoscrystals, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by cosmoscrystals** [comment]
I don't have time to find and copy all of that info.  I've been trying to fix this for hours and hours.  I was up until 3am last night trying to make it work.  
I have two other prestashop installs that work fine. No problems at all. 

I can't find the post where someone else copied an older directory to fix the problem. Do you think if I do the same that it might fix it?  You were helping him. Do you remember the directory that he copied?

**Comment by khouloudbelguith** [comment]
@cosmoscrystals,
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by cosmoscrystals** [comment]
I put it in debug mode and got this error message when I tried to view the item page.
![Screenshot_20191030-125818](https://user-images.githubusercontent.com/57187709/67880552-38f55d00-fb15-11e9-805c-259e020cce0f.jpg)

**Comment by cosmoscrystals** [comment]
I uninstalled 1.7.6.1 and installed 1.7.6.0 and it's working fine so far.

**Comment by khouloudbelguith** [comment]
@cosmoscrystals, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
