### ISSUE TITLE
Admin -> Order Update -> Carrier Fee Miscalculation

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#16211]
Hello,

I am using Prestashop 1.7.6.1 

I found an issue related with order update process on Admin page.

On my shop, all orders over 149TL (Turkish Liras) shipment is set free.

If I want to update a current order with adding new products, new price is calculated, but this time shipment fee is added to the order, but it should not be.  

Here is a video record I got:

https://drive.google.com/open?id=1HccDaa5-eT9JQ9P8MgHeK8TBKvFLznF3

Thanks

**Comment by khouloudbelguith** [comment]
Hi @cemalarik,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1wroMb4vtgvPKnMdBF2XWCw8NCb4wlfy1/view
Thanks to check & feedback.

PS: shipping for the products is not null.

THanks!

**Comment by khouloudbelguith** [comment]
Hi @cemalarik,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
