### ISSUE TITLE
Issue in Image Settings in Product

### ISSUE THREAD

**Issue by creartlab** [PrestaShop/PrestaShop#16217]
I have an issue with product image settings in the BO. After uploaded it I can't manage it anymore, deleting or other. I have the window all blank. 

Screenshot: https://prnt.sc/pq8zpe

I enabled debug mode, gone to the product page, opened up developer tools
and in Network tab I read the followed error:

Request URL: https://missq.it/amministrazione/index.php/sell/catalog/products/image/form/40?_token=5pqV0rx2y0IvjNXUXLxxO9QCCrHfkulo7GTsSO30ODo
Request Method: GET
Status Code: 500 

In Symphony I have the Exception:
Could not load type "form": class does not exist.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

I tried to set classic theme and to disable all modules not in basic Prestashop. Nothing.
Anyone knows about it already?
thanks

**Comment by khouloudbelguith** [comment]
Hi @creartlab,

You need to enable debug mode in your store and debug request which is sent for product edition in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. edit product
6. wait for an error, you should see red request information in Network tab (error 500 in your case)
7. click on it, you should see the error message in "Response" or "Preview" tab

We need to show the exception in the "Response" or "Preview" tab.

Thanks!

**Comment by creartlab** [comment]
Hello, thanks for the replay. I done some screenshot of the visualization of error in Preview tab, thanks


![image](https://user-images.githubusercontent.com/57190143/67957100-6580a600-fbf5-11e9-8fa2-696a91c0dfb3.png)

![image](https://user-images.githubusercontent.com/57190143/67957149-78937600-fbf5-11e9-853c-f17cd92e0a06.png)

![image](https://user-images.githubusercontent.com/57190143/67957181-821cde00-fbf5-11e9-911b-bfc19c61cd4e.png)

![image](https://user-images.githubusercontent.com/57190143/67957203-89dc8280-fbf5-11e9-8379-58e86e547d5b.png)

![image](https://user-images.githubusercontent.com/57190143/67957220-9365ea80-fbf5-11e9-8e59-3fc8a481e44a.png)

![image](https://user-images.githubusercontent.com/57190143/67957247-9bbe2580-fbf5-11e9-8734-9191751cc4ef.png)

![image](https://user-images.githubusercontent.com/57190143/67957277-a5e02400-fbf5-11e9-890a-dae644c4ff51.png)

**Comment by khouloudbelguith** [comment]
@creartlab, did you use the `litespeedcache` module?

Thanks!

**Comment by creartlab** [comment]
No, i don't.

**Comment by khouloudbelguith** [comment]
@creartlab, did you run `composer install`?

Thanks!

**Comment by creartlab** [comment]
No, I installed the PS manually some years ago and this month I updated from 1.6 to 1.7.6.1. then I installed a new theme.

**Comment by khouloudbelguith** [comment]
@creartlab, could you please follow these steps:
1. make a backup of your shop & your database first => let's be safe
2. rename the vendor folder to vendor_old
3. download this file into your project_folder
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/composer.lock
4. Run `composer install`
 
Thanks to check & feedback.

**Comment by creartlab** [comment]
Hello, thanks.
what exactly composer install will do?

**Comment by khouloudbelguith** [comment]
@creartlab,`composer install ` just install all the dependencies as specified in the composer.lock file.

Thanks!

**Comment by creartlab** [comment]
I'm on the page. When i can download it and where I have to install?

**Comment by khouloudbelguith** [comment]
@creartlab,

You need just to unzip it & copy it into your Project_Folder
[composer.lock.zip](https://github.com/PrestaShop/PrestaShop/files/3794618/composer.lock.zip)
Thanks!

**Comment by creartlab** [comment]
Ok pls give all steps to do.
I downloaded it and uploaded it then in the main folder of the website.
then?
thanks

**Comment by khouloudbelguith** [comment]
@creartlab,
You just downloaded the composer.lock file & here's the composer.json file
[composer.json.zip](https://github.com/PrestaShop/PrestaShop/files/3794675/composer.json.zip)
=> download it, unzip it & copy it to your Project_Folder
Now, you need to run `composer install`
PS:
Please make a backup of your shop & your database first => let's be safe
Thanks!

**Comment by creartlab** [comment]
I unzipped composer.lock file and I putted in the main folder.
To run, just I have to call the complete url?

P.S. I done a complete backup from Softaculous in the cPanel.
thaks

**Comment by khouloudbelguith** [comment]
@creartlab, you need to use a terminal to run the `composer install` command.
![image](https://user-images.githubusercontent.com/16067358/67964167-1ab85b80-fc00-11e9-8288-2240d4b337e4.png)

Thanks!

**Comment by creartlab** [comment]
I dont have terminal tool in my cPanel, I dont know how to do it.

**Comment by khouloudbelguith** [comment]
@creartlab, could you please check with your host if it is possible to run `composer install`.

Thanks!

**Comment by creartlab** [comment]
yes, I will contact them now.
thanks

**Comment by khouloudbelguith** [comment]
@creartlab, thanks!
Waiting for your feedback.

**Comment by creartlab** [comment]
I can run it with SSH Access in cPanel.
But I dont know how to use it.

**Comment by creartlab** [comment]
sorry me I found Terminal in cPanel, I enabled shell.
But what I will write in it?

**Comment by khouloudbelguith** [comment]
@creartlab, first you need to open the terminal on your `Project_Folder` path

1. `cd /path_to_your_project_folder/`
2. `composer install`

Thanks!

**Comment by creartlab** [comment]
Hello,
I wanted to say that composer and to regenerate all classes didn't help and I have stille the problem.

**Comment by khouloudbelguith** [comment]
@creartlab, the command `composer install` is used to install all dependencies specified in the composer.lock file.

Thanks!

**Comment by creartlab** [comment]
yes it was installed already. We did to re install all dependencies. But it don't find "form" class.

**Comment by khouloudbelguith** [comment]
@creartlab, this issue is reproduced in which step? on running the composer install command?

Thanks!

**Comment by creartlab** [comment]
the issue is always in the product image window. it shows all blank without commando to delete.

**Comment by khouloudbelguith** [comment]
@creartlab, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by creartlab** [comment]
Ok! thanks
I will write a message here when I sent.

**Comment by khouloudbelguith** [comment]
@creartlab, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @creartlab,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
