### ISSUE TITLE
ps_facetedsearch display issue

### ISSUE THREAD

**Issue by LOUTAG** [PrestaShop/PrestaShop#16210]
### **Description of my issue:**
I bought a template which should display the color filter (ps_facetedsearch) like the picture just below:
![color](https://user-images.githubusercontent.com/57157316/67861507-a3f86100-fb20-11e9-99be-9538a9414579.png)

However in my case it was displayed like that (just below) with ps_facetedsearch version 3.4.0 :
![colo_bug_display](https://user-images.githubusercontent.com/57157316/67862941-4a456600-fb23-11e9-822b-0c0b75715cd1.png)

I've changed the ps_facetedsearch version to 2.1.2. Now, it's displayed better, but still an issue like you can see just below:
![color_bug](https://user-images.githubusercontent.com/57157316/67861655-ecb01a00-fb20-11e9-8a9d-d30ee36ee5d3.png)

I think the problem is due to the ps_facetedsearch module version which isn't compatible with my template, it's why I'm looking for the ps_facetedsearch v.2.1.2

On the forum another guy had this issue, which seems to work with the ps_facetedsearch v.2.1.2  link: https://github.com/PrestaShop/PrestaShop/issues/10869 

### **To reproduce my issue**
- I use prestashop 1.7.6.0
- my current ps_facetedsearch version is 2.2.1
- my php version is 7.1
- my template is from templatemonster : https://www.templatemonster.com/prestashop-themes/eveprest-fashion-1-7-fashion-store-prestashop-theme-69941.html)
- a link of my website : http://www.passagedelamode-shop.com/index.php?id_category=20&controller=category&id_lang=5

Thank you for your help !!

**Comment by khouloudbelguith** [comment]
Hi @LOUTAG,

Sorry, but in this case, 
>`ps_facetedsearch` module version which isn't compatible with my template, 

ps_facetedsearch is overridden by your theme.

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by LOUTAG** [comment]
Thank you for your answer!
I've done a mistake, I'm currently using the ps_facetedsearch version 2.2.1(image on the third screenshot, not 2.1.2) I've never had the version 2.1.2 !
Due to your answer on the topic that I've quoted I'm looking for the version 2.1.2.
I've already sent a message to the theme author, and I will share you the answer.
Could you share me the ps_facetedsearch version 2.1.2 ? Thanks

**Comment by khouloudbelguith** [comment]
@LOUTAG, this is an old version: https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.1.2

Thanks!

**Comment by LOUTAG** [comment]
> @LOUTAG, this is an old version: https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.1.2
> 
> Thanks!

I cannot upload the .zip... have I something specific to do?

**Comment by khouloudbelguith** [comment]
@LOUTAG, thanks to follow these steps:

1. Go to https://github.com/PrestaShop/ps_facetedsearch
2. Run `git clone https://github.com/PrestaShop/ps_facetedsearch.git`
3. Run `cd ps_facetedsearch`
4. Run `git checkout v2.1.2`
5. Run `composer install`
6. zip this folder & upload it.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @LOUTAG,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
