### ISSUE TITLE
Bug in module Ps_linklist after upgrade v.1.7.1.2 to 1.7.6.1

### ISSUE THREAD

**Issue by idrisselbasri** [PrestaShop/PrestaShop#16214]
You have requested a non-existent service "prestashop.module.link_block.repository". Did you mean one of these: "prestashop.core.admin.lang.repository", "prestashop.core.admin.log.repository", "prestashop.core.admin.shop.repository", "prestashop.core.api.stock.repository", "prestashop.module_kernel.repository"?

![image](https://user-images.githubusercontent.com/43181798/67872067-b29b4400-fb31-11e9-895d-94a3548f6b32.png)

**Comment by khouloudbelguith** [comment]
Hi @idrisselbasri,

Could you please try to re-install the ps_linklist module, clear cache, check & feedback.

Thanks!

**Comment by idrisselbasri** [comment]
Hi @khouloudbelguith 

I reset the module and clear the cache but I found the same bug

Thanks!

**Comment by khouloudbelguith** [comment]
@idrisselbasri, try to uninstall it with removing the folder, clear cache, then try to install it again.

Thanks!

**Comment by idrisselbasri** [comment]
@khouloudbelguith 

I try all this operation
i uninstall and chose Optional delete module folder after uninstall and clear the cache but I found the same bug

Thanks!

**Comment by khouloudbelguith** [comment]
@idrisselbasri, what is the exact version of the module ps_linklist did you try to install it?
Did you install it from the Module Catalog page?
Thanks!

**Comment by idrisselbasri** [comment]
@khouloudbelguith 

Yes,  I install it from the Module Catalog page
The version Exact of the module v3.0.4

Thanks!

**Comment by idrisselbasri** [comment]
@khouloudbelguith 

I found the problem on the vendor file
I deleted the src and vendor folder & download the two folders vendor & src of latest version prestashop
that works
Thanks Khouloud

**Comment by khouloudbelguith** [comment]
@idrisselbasri, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!
