### ISSUE TITLE
Infinite loop in CartRule class if free shipping is given

### ISSUE THREAD

**Issue by matrixino** [PrestaShop/PrestaShop#16212]
**Describe the bug**
If you have a rule which gives free shipping and this rules is used, trying to open the order/cart results in loop till memory exaust error.
I have identified the problem in this part (around line 1105 of CartRule.php):
`        if ($this->free_shipping && in_array($filter, array(CartRule::FILTER_ACTION_ALL, CartRule::FILTER_ACTION_ALL_NOCAP, CartRule::FILTER_ACTION_SHIPPING))) {
            if (!$this->carrier_restriction) {
                $reduction_value += $context->cart->getOrderTotal($use_tax, Cart::ONLY_SHIPPING, is_null($package) ? null : $package['products'], is_null($package) ? null : $package['id_carrier']);
            } else {
                $data = Db::getInstance()->executeS('
                SELECT crc.id_cart_rule, c.id_carrier
                FROM ' . _DB_PREFIX_ . 'cart_rule_carrier crc
                INNER JOIN ' . _DB_PREFIX_ . 'carrier c ON (c.id_reference = crc.id_carrier AND c.deleted = 0)
                WHERE crc.id_cart_rule = ' . (int) $this->id . '
                AND c.id_carrier = ' . (int) $context->cart->id_carrier);
                if ($data) {
                    foreach ($data as $cart_rule) {
                        $reduction_value += $context->cart->getCarrierCost((int) $cart_rule['id_carrier'], $use_tax, $context->country);
                    }
                }
            }
        }`
The problem appears when `if (!$this->carrier_restriction)` is true and `$reduction_value += $context->cart->getOrderTotal($use_tax, Cart::ONLY_SHIPPING, is_null($package) ? null : $package['products'], is_null($package) ? null : $package['id_carrier']);` gets triggered.

PS: Not verified, but I happen to have a free shipping carrier among others. Not sure if this only happens when a free carrier and a free shipping cart rule are both present in the shop.

**To Reproduce**
Create a free shipping cart rule
Make an order
Navigate to the cart/order in the BO

**To Reproduce**
Temporary fix: apply carrier restriction to the cart rule including all the carrier.
PS: by default PS doesn't allow that, unchecking the carrier selection rule if all are added. I had to select al except one (in my case was the free one).

**Additional information**
PrestaShop version: For sure up to 1.7.5.x, probably 1.7.6 too
PHP version: 7.2

**Comment by matrixino** [comment]
Not sure why the code format is messed up.

**Comment by khouloudbelguith** [comment]
Hi @matrixino,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15691 to fix the issue.
Fixed in the next patch 1.7.6.2.
Your ticket is a duplicate of #15574
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15574

**Comment by matrixino** [comment]
> Hi @matrixino,
> 
> Here's the PR: #15691 to fix the issue.
> Fixed in the next patch 1.7.6.2.
> Your ticket is a duplicate of #15574
> So, I close it.
> Thanks!

Woops. I only searched for open issues, my bad.
