### ISSUE TITLE
Password came to my email in plaintext

### ISSUE THREAD

**Issue by ChristopherThorpe** [PrestaShop/PrestaShop#16220]
I received an email from PastryChefsBoutique as a new subscriber and the email included my password in plain text. In 2019 this is unacceptable and I hope it doesn't affect all of your customers.
![Password in Plain Text](https://user-images.githubusercontent.com/78364/67901837-00f61600-fb25-11e9-8db6-fc554d45bd7a.png)

**Comment by ChristopherThorpe** [comment]
Suggestion:
1) IMMEDIATELY change your code to stop sending passwords in email.
2) Update your password storage so you don't store them in plaintext. Best practice is to encrypt passwords in your database using a hashing scheme resistant to brute force attacks. 

Some resources:
https://crackstation.net/hashing-security.htm
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

**Comment by khouloudbelguith** [comment]
Hi @ChristopherThorpe,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/67928703-f9358080-fbbb-11e9-92ca-42018767bca0.png)
It is fixed with PS1.7 fixed with this PR: #5889
If you are using the PS1.6, it is fixed with this PR: #8564
Thanks to check & feedback.

**Comment by matks** [comment]
@ChristopherThorpe as khouloudbelguith stated it, this behavior has been changed a long time ago in PrestaShop codebase. It is likely that PastryChefsBoutique is powered by a very old version of PrestaShop 😉 .

**Comment by matks** [comment]
And also passwords were never stored in plaintext. When the "send password in clear" behavior was enabled, the password would be sent just after being registered (so php has access to it as it was given to it as an input), but it would be encrypted in database.

**Comment by khouloudbelguith** [comment]
Hi @ChristopherThorpe,

Since it's related to an old PrestaShop version.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ChristopherThorpe** [comment]
Thank you. I had searched the GitHub issues for this before posting and did not find any mention of the problem. I think it would be helpful to leave something people like me could find so they don’t waste their time reporting this again and again. I got the following from legal. 

Dear Sir, 

I acknowledge receipt of your email and your complaint. 

Indeed, the recommendations of the CNIL provide that the passwords must not be disclosed by email. 

This recommendation was implemented by PrestaShop as soon as it was published. Therefore, PrestaShop does not send identifiers in clear since version 1.6.1. and complies with the GDPR. Passwords are not sent and their storage in our databases is encrypted in accordance with the personal data regulation. 

Only the older downloaded versions that are not updated by users still send these messages. As a result, PrestaShop does not have the possibility to modify this practice if users do not update the software. 

Several answers have also been published on Github on the same subject, I invite you to consult them for more information.

I remain at your disposal for any further information.

Marina Hauvieux
Legal intern
t: +33 (0)1 76 23 25 06

**Comment by matks** [comment]
It's strange you could not find it 🤔 https://github.com/PrestaShop/PrestaShop/issues/15922 was reported only 17 days ago, it was same topic. Hopefully this issue will be better found 😉

**Comment by ChristopherThorpe** [comment]
Thanks Mathieu, I was able to find it, eventually.
May I suggest you use GitHub's new Security Advisory feature
https://github.com/PrestaShop/PrestaShop/security/advisories and publish an
advisory that customers need to update their code because of this bug? I
think it's a big GDPR problem in Europe and a big PCI-DSS problem in the US.
