### ISSUE TITLE
Fix dates format in new Order page

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#16226]
All dates should be formatted according to logged in employee's language, currently format is hardcoded.

For this, `PrestaShopBundle\Twig\Extension\LocalizationExtension` extension was introduced which adds Twig filter `date_format_full` to ease the work. 

So, instead of this:
`{{ some_object.createdAt|date('Y-m-d H:i:s') }}`
it should become like this:
`{{ some_object.createdAt|date_format_full }}`

**Comment by khouloudbelguith** [comment]
Ping @matks

**Comment by matks** [comment]
Thanks @sarjon

**Comment by MatShir** [comment]
@matks I just find out this issue. 
It is fixed or going to be fixed during the migration?

**Comment by matks** [comment]
@MatShir once Order page is finished, it should be quite easy to apply the fix as it's a small change. We just need to locate all date display fields.

**Comment by colinegin** [comment]
Should be ok now that everything from the order page has been merged

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/18063

**Comment by Progi1984** [comment]
Fixed by #18063
