### ISSUE TITLE
No display of specific price on BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16228]
**Describe the bug**
When I add a new specific price, it's not displayed on the product page on BO (but still works in FO).

**To Reproduce**
1. Go to BO > Product > Pricing
2. Add a specific price : It does not appear after being added.
If you add same specific price : An error message stating that a similar rule exist appears.
The rule works fine in FO.

**Screenshots**
Screen record :
https://drive.google.com/file/d/1GxeK4_GbRgmvtHVao37wiKZiKhVopQDc/view?usp=sharing

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Same issue with the develop branch
