### ISSUE TITLE
Prestashop 1.7.5.2 $page['canonical'] is empty for manufacturer

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [PrestaShop/PrestaShop#16234]
Hi,

Prestashop 1.7.5.2
$page['canonical'] is empty for manufacturer

**Comment by khouloudbelguith** [comment]
Hi @nicoja,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9503
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9503

**Comment by Kixell-NicolasJardillier** [comment]
ok, I did not checked before. I ll do it next time. Sorry
