### ISSUE TITLE
Bug cart rule and specific price

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#16232]
Hi,
I'm on 1.7.4
I have a product with specific price -> 25% reduction

I have cart rule with 25% reduction for all catalog, applied on cart with with "not include product with discount".

If i add product with discount in my cart, the cart rule is not applied -> Great, this is what i want.
If i add another product in my cart with no discount, cart rule is applied but with the total cart including discount of first product. This is wrong. Cart rule need to apply only on product with no discount ...
Is this normal ?

**Comment by khouloudbelguith** [comment]
Hi @azralth,

Here's the PR: #13704 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #10300
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10300
