### ISSUE TITLE
When GDPR module is uninstalled, "accept terms" checkbox is not displayed

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16238]
**Describe the bug**
When GDPR module is uninstalled, "accept terms" checkbox is not displayed. I think this is a legal issue 🤔 this check is mandatory, GDPR or not.

**To Reproduce**
1. Install a shop
2. Uninstall GDPR module
3. Add a product to cart, go to checkout
4. See that checkbox "accept our terms" is not displayed

**Screenshots**
![Capture d’écran 2019-10-31 à 17 00 12](https://user-images.githubusercontent.com/3830050/67964085-f492bb80-fbff-11e9-906a-38fee3c440b9.png)

**Additional information**
PrestaShop version: develop

**Comment by khouloudbelguith** [comment]
Hi @matks,

It is the same behavior as PS1.7.5.2 & PS1.7.6.1.
We just need to disable the GDPR module to reproduce this issue.
Ping @colinegin @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by matks** [comment]
Spotted by @sarahdib by the way, cheers go to her

**Comment by marionf** [comment]
If you want to have this checkbox you can install data privacy module (it will be native and pre-installed soon, so no problem is API is down)
