### ISSUE TITLE
Design Fix: Shipping Method Display on Classic Theme's Checkout

### ISSUE THREAD

**Issue by TristanLDD** [PrestaShop/PrestaShop#16233]
Display of shipping method block in Classic theme looks broken and can be easily fixed :

![Capture d’écran 2019-10-31 à 15 35 12](https://user-images.githubusercontent.com/27484094/67956514-84cb0380-fbf4-11e9-87ef-111077c3a565.png)

**Comment by khouloudbelguith** [comment]
Hi @TristanLDD,

Same issue with PS1.7.6.1 & PS1.7.6.0 & PS1.7.5.2.
I’ll add this to the debug roadmap.
Thanks!
