### ISSUE TITLE
Product alignment is wrong in product lists for smaller devices

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#16249]
**Describe the bug**
In product lists and featured products on homepage, products look broken on smaller screens due to` justify-content: flex-start;`. We need to fix this as it looks terrible on mobile devices (see screen).
**To Reproduce**
Try if on mobile or via developer tools

**Screenshots**
![before](https://user-images.githubusercontent.com/12268701/68069827-5113e900-fd6e-11e9-8760-c901c350800d.png)

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Thanks for your report.
I manage to reproduce the issue with develop branch.
![image](https://user-images.githubusercontent.com/16067358/68107953-ad9a1400-fee6-11e9-8bb0-592c01f25ba4.png)
![image](https://user-images.githubusercontent.com/16067358/68107961-b985d600-fee6-11e9-85d2-22c68d95ba53.png)

In the PS1.7.6.1, it is OK.
![image](https://user-images.githubusercontent.com/16067358/68107992-cd313c80-fee6-11e9-92d5-b328b2015262.png)

It is a regression.
Thanks for the fix.
