### ISSUE TITLE
Folder vendor/prestashop/smarty is used for cache

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16243]
**Describe the bug**
It seems folder vendor/prestashop/smarty is used for cache

See https://github.com/PrestaShop/PrestaShop/blob/develop/config/smarty.config.inc.php#L26

This prevents us from using our Smarty fork http://github.com/PrestaShop/smarty  as composer attempts to install the fork in this folder.

Thus we cannot merge https://github.com/matks/PrestaShop/commit/52f6a9f0e831dfe5928bcf66e6a739fe4b53aa26

**Comment by bet0x** [comment]
@matks On the dev branch you are moving into Twig right?

**Comment by matks** [comment]
@bet0x We're moving into Twig only in the back-office, on the `develop` branch indeed. Front-office benefits from a higher level of backwards compatibility which prevents us from modifying the templating engine as we follow SemVer. Only when we release a new major version will we be able to introduce the necessary breaking changes to remove completely Smarty from PrestaShop.

**Comment by eternoendless** [comment]
> It seems folder vendor/prestashop/smarty is used for cache

![image](https://user-images.githubusercontent.com/1009343/91284618-70ac5000-e78c-11ea-9ea2-d192376d8e2a.png)

Sounds like this should be changed ASAP

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24634
