### ISSUE TITLE
Admin panel is not displayed. (70007)The timeout specified has expired

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#16254]
**Describe the bug**
I can't start the admin panel. I enter the login and password, but the admin panel is not displayed. Front office is working.

Аn error is displayed in the browser after a few minutes:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /admin***/index.php.

Reason: Error reading from remote server

On the web server in the logs:
[Sun Nov 03 19:26:32 2019] [error] [client *] (70007)The timeout specified has expired: proxy: error reading status line from remote server *, referer: https://weddingtextile.com/admin***/index.php?controller=AdminDashboard&token=68089897ddb384480c9ed83e1225e212
[Sun Nov 03 19:26:32 2019] [error] [client *] proxy: Error reading from remote server returned by /admin***/index.php, referer: https://weddingtextile.com/admin***/index.php?controller=AdminDashboard&token=68089897ddb384480c9ed83e1225e212

**Additional information**
PrestaShop version: 1.7.4.3
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

Thanks for your bug report.
Are you connected over Proxy with authentication?

Thanks!

**Comment by weddingtextile** [comment]
No Proxy

**Comment by khouloudbelguith** [comment]
@weddingtextile, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by weddingtextile** [comment]
On a hosting found cyclic requests to 216.58.215.115, then an error on a timeout.
Perhaps not exactly, it is somehow related to gamification.prestashop.com

How can I manually disable modules in the database?

**Comment by weddingtextile** [comment]
The assumption was confirmed. Renamed the gamification directory to gamification_ and the admin panel worked.

**Comment by khouloudbelguith** [comment]
@weddingtextile, what is the exact version of the gamification module did you use?

Thanks!

**Comment by weddingtextile** [comment]
<module>
	<name>gamification</name>
	<displayName><![CDATA[Merchant Expertise]]></displayName>
	<version><![CDATA[2.0.1]]></version>

**Comment by weddingtextile** [comment]
<module>
	<name>gamification</name>
	<displayName><![CDATA[Merchant Expertise]]></displayName>
	<version><![CDATA[2.0.1]]></version>

**Comment by weddingtextile** [comment]
2.0.1

**Comment by weddingtextile** [comment]
https://www.web-hints.com/tools/disable-prestashop-api-calls-in-backoffice/

That helped

**Comment by khouloudbelguith** [comment]
@weddingtextile, this version is very old.
We re-worked in this module & fixed issues.
Please upgrade your module to the latest one v2.3.1.
https://github.com/PrestaShop/gamification/releases

Thanks!
