### ISSUE TITLE
Minor display regression on Contact Us Page (FO)

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16257]
**Describe the bug**
On the "Contact us" page, the contact mail is not displayed correctly.

**To Reproduce**
1. Go to "Contact Us" on FO, see the display of the email adress.

**Screenshots**
On 1762 : 
![release 1762 custo contact mail 1 - now](https://user-images.githubusercontent.com/55688534/68116315-c7455680-fefa-11e9-97b8-2ed875884dd0.png)

On 1752 : 
![release 1762 custo contact mail 1 - 175](https://user-images.githubusercontent.com/55688534/68116363-efcd5080-fefa-11e9-86f4-a92a8eb616f0.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I have the same behavior as PS1.7.6.1 & PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/68117220-01aff300-fefd-11e9-80fb-f16495728e1f.png)
Thanks!
