### ISSUE TITLE
Attach invoice PDF to email toggle not working

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#16253]
**Describe the bug**
In Order Setting, you can set whether the invoice is added to the email or not, but it does not seem to matter if the box is ticked or not, the invoice is always attached.

**To Reproduce**
1. Go to order settings, select awaiting bank wire payment status
2. Unselect the box 'Attach invoice PDF to email' and save
3. Make an order using bank wire payment
4. Check the sent email to see there still is an invoice attached.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33-12+0~20191026.23+debian9~1.gbp940de0

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

You need to unselect the option "Allow a customer to download and view PDF versions of his/her invoices".
![image](https://user-images.githubusercontent.com/16067358/68110941-41231300-feee-11e9-8105-cec53706203c.png)

Thanks to check & feedback.

**Comment by sickboards** [comment]
Thanks that did the trick

**Comment by khouloudbelguith** [comment]
@sickboards, Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
