### ISSUE TITLE
The problem is related to the shopping cart.

### ISSUE THREAD

**Issue by fyndpriser** [PrestaShop/PrestaShop#16263]
Hi,
I have a problem after re-upload some files and replace them with the old.
The problem is related to the shopping cart.

When I click Add item to cart nothing happens but after refreshing the page the item appears already added.
The second thing when I try it on another browser that I have not used before shows the same product that I added earlier.
I think it's related to cookies.
Are there any tips on solving this problem?

Store link
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @fyndpriser,

Did you use the MailChimp module?

Thanks!

**Comment by fyndpriser** [comment]
Hi @khouloudbelguith 
No, I don't use the MailChimp module

Thanks..

**Comment by fyndpriser** [comment]
I've disable non PrestaShop modules and disable all overrides without result.

**Comment by khouloudbelguith** [comment]
@fyndpriser, did you use those options?
![image](https://user-images.githubusercontent.com/16067358/68132542-30d75c00-ff1f-11e9-9424-d0baa23af3db.png)

Thanks!

**Comment by fyndpriser** [comment]
yes, I've disable non PrestaShop modules and disable all overrides without result.

**Comment by fyndpriser** [comment]
@khouloudbelguith 
I have multiple stores and the problem is also with other stores/ . Thanks..

**Comment by khouloudbelguith** [comment]
@fyndpriser, no those options do not work as reported here:
https://github.com/PrestaShop/PrestaShop/issues/9965 & https://github.com/PrestaShop/PrestaShop/issues/14596

Thanks!

**Comment by fyndpriser** [comment]
@khouloudbelguith 
I've manually disabled all non-PrestaShop modules. And reset all PrestaShop modules.
But the same problem!

**Comment by fyndpriser** [comment]
I don't know if the problem is related to the database or something else?

**Comment by khouloudbelguith** [comment]
@fyndpriser, did you make any changes in the theme?

Thanks!

**Comment by fyndpriser** [comment]
@khouloudbelguith 
I installed the warehouse template and then after that removed it and tried to install the transformer2 template. Then the problem appeared and then removed all templates and keep the default template.
I have restored a backup of all files and folders before modifying without the database.

Sorry for my English
Thanks..

**Comment by khouloudbelguith** [comment]
@fyndpriser, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by fyndpriser** [comment]
@khouloudbelguith 
The problem has been resolved by disabling the Seo Meta Tags Manager module .

Seo Meta Tags Manager
v1.1.0 - by FMM Modules 

Thanks.....

**Comment by khouloudbelguith** [comment]
Hi @fyndpriser,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
