### ISSUE TITLE
Bug nombre de visiteurs en ligne

### ISSUE THREAD

**Issue by Alexsmart78** [PrestaShop/PrestaShop#16270]
Bonjour,

Je suis sous prestashop 1.7.4.3 et depuis quelques temps j'ai un bug concernant le nombre de visiteurs en ligne.
Il y a des explosions du nombre des visiteurs plusieurs fois par jour alors qu'il s'agit toujours de la même adresse IP qui se connecte toutes les 3 secondes.
Du coup mes stats : nombre de visites et taux de transfo sont complètement faussés.
Suis-je la seule dans ce cas ?
Peut on régler ce problème ?
Merci pour votre aide.
Alexandra

**Comment by khouloudbelguith** [comment]
Hi @Alexsmart78,

I think you have an attack.
Did you have some Amazon, ebay, etc. module to synchronize your shop with the market?
It could be due to a proxy server also.
You can use PrestaShop Geo Location Feature. It is really very good to block the IP.
Thanks!

**Comment by Alexsmart78** [comment]
No je n'ai pas de module Amazon, ebay...
Le problème c'est que l'IP change tous les jours voir plusieurs fois par jours :(

**Comment by khouloudbelguith** [comment]
@Alexsmart78, could you please provide me a screenshot.
As I said before, you can use PrestaShop Geo Location Feature. It is really very good to block the IP.
You can navigate to your BO => International => Localization => Geolocation Tab, in this page, you can enable the Geolocation by IP address, you can add IP addresses that will always be allowed to access your shop.
Thanks!

**Comment by Alexsmart78** [comment]
encore obligé d'acheter un module :( N'y a t'il pas de solution gratuite ?

**Comment by khouloudbelguith** [comment]
@Alexsmart78, the PrestaShop Geo Location Feature is not a module, it is a PrestaShop option.

Thanks!

**Comment by Alexsmart78** [comment]
c'est une option payante ?

**Comment by khouloudbelguith** [comment]
@Alexsmart78, No.
You can navigate to your BO => International => Localization => Geolocation Tab, in this page, you can enable the Geolocation by IP address, you can add IP addresses that will always be allowed to access your shop.
![image](https://user-images.githubusercontent.com/16067358/68193947-65e1be00-ffb4-11e9-88a5-ada75a684350.png)

Thanks!

**Comment by Alexsmart78** [comment]
ah ok. Super !
Merci beaucoup

**Comment by khouloudbelguith** [comment]
@Alexsmart78, thanks to check it & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Alexsmart78,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
