### ISSUE TITLE
Add information message for attached files in product options tab 

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16272]
Under the message "Add files that customers can download directly on the product page (instructions, manual, recipe, etc.)."
Add an information message: "To manage your files, go to Catalog > Files" with a link to the page

![capture d'écran_2125](https://user-images.githubusercontent.com/13449658/68198086-aa248c80-ffbb-11e9-90fa-4d9fc743b546.png)

**Comment by LouiseBonnard** [comment]
Here is my recommendation, feel free to challenge it:

_Select the files (instructions, documentation, recipes, etc.) your customers can directly download on this product page._
_Need to browse all files? Go to the [1]Catalog > Files[/1] section of your back office._
