### ISSUE TITLE
Prevent customers from returning a full virtual order

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16275]
**Is your feature request related to a problem? Please describe:**

When an order contains only virtual products, the Merchandise Returns tab displays the following message: Merchandise returns are not applicable for virtual orders. So we let the merchant know virtual products (and by extension, fully virtual orders) cannot be returned.

But once a virtual order is noted as delivered, the customer can connect to his/her account, go in the details of his/her virtual order, select all virtual products and decide to return them.

Back from a merchant's side, the Merchandise Returns tab remains the same, with the message displayed and the customer return not listed.

**Describe the solution you'd like:**

It would make sense to prevent the customer from returning his/her virtual order. Perhaps by displaying the same message?

cf. https://github.com/PrestaShop/PrestaShop/pull/16084#discussion_r338060225

**Comment by hibatallahAouadni** [comment]
Hello @LouiseBonnard 

Should I add this improvement to this [[EPIC] Order Pages, a new start](https://github.com/PrestaShop/PrestaShop/issues/17598) ?

**Comment by ghost** [comment]
Hello @LouiseBonnard 

It's ok for you or you need also a message ? 

Screenshot on the PR : https://github.com/PrestaShop/PrestaShop/pull/25165

**Comment by matks** [comment]
@LouiseBonnard has given its beacon to @Julievrz 😊

**Comment by ghost** [comment]
Thank for the good ping @matks

**Comment by Julievrz** [comment]
> Hello @LouiseBonnard
> 
> It's ok for you or you need also a message ?
> 
> Screenshot on the PR : #25165

Hi! I think it would be nice to add a message: 'Virtual products can't be returned.' in Shop.Theme.Customeraccount

**Comment by ghost** [comment]
@Julievrz new screenshot here https://github.com/PrestaShop/PrestaShop/pull/25204 i hope is good regards

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

Before testing #25204 PR, I want to make sure the issue is PM approved, could you put label "PM ✔️" and remove "TBS" ?

Thanks!

**Comment by marionf** [comment]
@florine2623 Done ;)
