### ISSUE TITLE
When I install a new language, the generated emails are not translated on first generation

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#16273]
**Describe the bug**
When I install a new language, the generated emails are not translated on first generation

**To Reproduce**
1. Go to International > Translations
2. Install new language "Polish"
3. The mails are generated in `mails/pl` but they are in englisg
4. If you regenerate them manually after it works fine

**Solution**
Check the update package part of the code, seems like the translations are not available
Maybe the translations are cached on the start of the request, so when mails are generated the new one is not available, maybe we should clean the cache right after the new language is installed

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I have the same issue with PS1.7.6.1 & PS1.7.6.2build1.
[pl.zip](https://github.com/PrestaShop/PrestaShop/files/3808419/pl.zip)

It is OK with PS1.7.5.2.
[pl.zip](https://github.com/PrestaShop/PrestaShop/files/3808413/pl.zip)

I’ll add this to the debug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think?
It should be fixed in the PS1.7.6.2 patch?

Thanks!

**Comment by johnchatel** [comment]
>     4\. If you regenerate them manually after it works fine

Hello,

I have the same problem, how do you regenarate the emails manually please?
Thank you for help!

**Comment by matks** [comment]
Might be fixed by https://github.com/PrestaShop/PrestaShop/pull/16294

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0
