### ISSUE TITLE
Text WYSIWYG Editor is not working correct

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#16276]
Hi, 

Back office editor not working correct. In PrestaShop versions 1.7.2 to 1.7.6.1 the editor for my product description doesn't work, it just appear html code as the attached picture. 
There is also a problem with resizing the table.

Browser: Google Chrome, version 78.0.3904.87 (Official Build) (64-bit)

![2019-11-05_11-15-20](https://user-images.githubusercontent.com/1309982/68199122-aeea4000-ffbd-11e9-979d-ce796c905d35.jpg)
![2019-11-05_11-15-54](https://user-images.githubusercontent.com/1309982/68199123-aeea4000-ffbd-11e9-8499-3d9ca662fc8f.jpg)

**Comment by khouloudbelguith** [comment]
Hi @elrosi,

Thanks for your bug report.
Have you the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9651?
I tried with PS1.7.6.1 & PS1.7.6.2build1 & it is OK
https://drive.google.com/file/d/1fBQlhqKd56iVONUCqnqEvq7b-btSB7Ac/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @elrosi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
