### ISSUE TITLE
Order creation page in BO: adding a product creates a new cart

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#16288]
**Describe the bug**

Here's the bug that was found by @Robin-Fischer-PS from QA when testing PR #16266 :

> When I add a product, it's OK, but if I add a second product immediately after on the same order, it creates a new cart (with only the last product added) instead of adding the product to current cart.

**To Reproduce**
1. Go to Orders > Orders > Create new order

When adding a product, it creates a new cart (with only the last product added) instead of adding the product to current cart. 

**Bug demonstration**
https://drive.google.com/file/d/191hrSUes1-eW16bpVYjwkBze1U2TbtTW/view

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

The first issue is not fixed also.
I have the same exception as reported here: https://github.com/PrestaShop/PrestaShop/issues/16259
when we choose a customer after deleting all shopping carts not ordered yet.
Steps to reproduce the issue:
1. fresh install to develop or delete all shopping carts not ordered yet.
2. Try to add a new order from the BO
3. Choose a customer
4. see the error in the console
![image](https://user-images.githubusercontent.com/16067358/68291740-c9d6b600-008a-11ea-9694-80a91be53036.png)

Also, same issue with develop branch "adding a product creates a new cart".

Thanks!

**Comment by matthieu-rolland** [comment]
@khouloudbelguith Damn, ok, issue #16259 mentioned the exception when searching for a product, I didn't not realize we had the same issue when choosing a customer. 😓 

So to sum up things that we still have to fix on this page:

- Exception when looking for a customer
- Products being added create a new cart

Am I right?

**Comment by khouloudbelguith** [comment]
@matthieu-rolland, yes exactly!

1. Exception when choosing a customer just searched, when all shopping carts not ordered yet are deleted
2. Products being added create a new cart

Thanks!

**Comment by matthieu-rolland** [comment]
So I found a way to fix the first point,  but I just learned that the order creation page's migration will be released in 1.7.7....  so I guess there's really no point in fixing this?  (or maybe for 1.7.6 ?).

Also the second point doesn't exist in the migrated page. 

ping @colinegin @khouloudbelguith

**Comment by colinegin** [comment]
If i'm correct, this is a regression found on the develop branch after order creation page's migration. If so, why would it be useless to fix it then ? 
Maybe @MatShir has more information about it ?

**Comment by Robin-Fischer-PS** [comment]
Hi @colinegin ,

The regression was found during the development of the Symfony create order page, but it does not appears on the migrated page (I did not manage to reproduce this bug I had in Legacy).

**Comment by colinegin** [comment]
Well, this is great news :)
Then if none of the two issues can be reproduced, i guess we can close this issue !

**Comment by matthieu-rolland** [comment]
@colinegin I moved it in the 1.7.6 kanban, since it's a major regression that still exists in 1.7.6, I'll fix the first point fast since I know what has to be done, about the second point, a bit more exploration is needed.
