### ISSUE TITLE
Migration from earlier version (ps earlier than 1.6.0.11), zero before product EAN13 where deleted

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/PrestaShop#16284]
**Describe the bug**
During Migration from earlier version than 1.6.0.9
When apply, autoupgrade, zeros before Ean13 disappear.
note that official ean13 from Usa seems to begin from 000 to 060 ( for instance : 018200110306 )

**To Reproduce**
1. Install a old prestashop (1.6.0.9 is used on the screens bellow the reproduce steps )
2. Fill EAN13 for a product and for a product Attribute starting with a 0 (018200110306)
3. Install autoupgrade module
4. lauch it and upgrade to latest prestashop version
5. Go agin to see the product admin page after the migration , the 0 has disapper and the field is incorrect.

**Screenshots**
Before update : 
![before_update](https://user-images.githubusercontent.com/3170104/68227574-45d1ef00-fff4-11e9-8724-6987d65e192f.png)

Autoupgrade module :  Update parameters
![update_to](https://user-images.githubusercontent.com/3170104/68227590-49fe0c80-fff4-11e9-9a38-3901386584fa.png)

After update :
![after_update](https://user-images.githubusercontent.com/3170104/68227599-4ec2c080-fff4-11e9-9afb-38b91addfada.png)

**Additional information**
PHP version: Migration from earlier version than 1.6.0.11

**Comment by khouloudbelguith** [comment]
Hi @123monsite-regis,

I did not manage to reproduce the issue.
I tried with the 1-click upgrade v4.9.0.
I tried an upgrade from PS1.6.0.11 to PS1.7.6.1 & from PS1.6.1.24 to PS1.7.6.1 & they are ok.
I attached a screen record
https://drive.google.com/file/d/12dZsBwgXkzJB5TTsShyXemNYb3XdVIet/view
Thanks to check & feedback.

**Comment by 123monsite-regis** [comment]
sorry @khouloudbelguith my description was not really clear,

you need to upgrade from a version stricly inferior as PS1.6.0.11  (PS1.6.0.9 for instance )

**Comment by khouloudbelguith** [comment]
@123monsite-regis, sorry.
I tried again with PS1.6.0.9 & it seems ok.
I attached a screen record
https://drive.google.com/file/d/1z8JDORe5XRWqM-ftkIwyVmR-Axt0tg6x/view
Thanks to check & feedback.

**Comment by 123monsite-regis** [comment]
@khouloudbelguith 

on your record, we can see that the ean13 has been changed from `018200110306` to `18200110306` (only 12 digits) .
this is the issue reported.

regards

**Comment by khouloudbelguith** [comment]
@123monsite-regis, yes you are right.
The 0 is missing.
I will add the issue to the debug roadmap.

Thanks!

**Comment by gericfo** [comment]
Hello,
Version 1.6 is no longer actively supported with the **1-click upgrade module** ([see this announcement](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)). I therefore close this ticket.
Thanks!
