### ISSUE TITLE
Cannot create or update a supplier with a country which contains states by default

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16293]
**Describe the bug**
It is impossible to create or update a supplier with a country which contains states by default, for example, the United States, Mexico,

**To Reproduce**
1. Go to BO => Catalog => Suppliers page
2. Create a new supplier with the country United States
3. Select a state for this country
4. Save
5. See error (The State field is empty)
![image](https://user-images.githubusercontent.com/16067358/68300456-1a0b4380-009e-11ea-97a5-2309d4586447.png)
6. Try to select again the state => no states displayed
![image](https://user-images.githubusercontent.com/16067358/68300501-33ac8b00-009e-11ea-9406-3f3e4b8df943.png)

PS: if you try to Enable the option `Contains states` for the France country & we create states manually for the France => we can create a new supplier with France & a state.

Now after creating new states, try to repeat all previous steps, in the last step, step 6, you will see the list of states of France(incorrect because the united states is selected as a country).

**Screenshots**
https://drive.google.com/file/d/1NiXc0dK6KH99jJWCM1XGclwNhaZKcYDy/view

**Additional information**
PrestaShop version: develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by PierreRambaud** [comment]
@matks The reason: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php#L134 you build the form without considering you already set a `country_id` will running the request, so it still use the language of the connected user here: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php#L102 and never refresh https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php#L219
I don't know what's the best way to change it or if you already did something similar in a migrated page.

**Comment by matks** [comment]
It's strange because we attempted to handle this usecase 🤔see the code below (https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php#L99):

```
        // By default the country id for states choices is taken from context country id
        $countryIdForStateChoices = $this->contextCountryId;

        // In case custom states country id is provided it is used instead (for example if it's edit action).
        if (null !== $options['country_id']) {
            $countryIdForStateChoices = $options['country_id'];
        }
```

If `$options['country_id']` is provided we use it instead. This is how we are supposed to handle dynamic country ID 🤔. Obviously we failed 😅as there's a bug but the solution then looks like we need to see what's wrong with this behavior.

**Comment by PierreRambaud** [comment]
You prepare the `SupplierType` for it, but nothing is set in the Controller compared to the edit action https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php#L323

A solution could be something similar than:
```php
        $supplierData = $request->request->get('supplier');
        $supplierForm = $this->getFormBuilder()->getForm(
            [],
            isset($supplierData['country_id']) ? ['country_id' => $supplierData['country_id']] : []
        );
```
