### ISSUE TITLE
URGENT! SpecificPriceRule (Catalog price rules) should work OVER product Specific Prices

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16295]
Hi guys.
We have now an very hot months in e-commerce world. Black Friday, Cyber Monday and Christmas...

Prestashop from the begining don;t have efficient way to set massive discount for all catalog.

**Example**
I have 500 products in catalog, 2/3 of them have set specific prices from 15 to 40% discounts.
I want to set catalog rule to cover whole site with 50% discount
Catalog rule will work only with 1/3 of non discounted products because

CATALOG RULES doesn't work OVER product SPECIFIC PRICE! ;(

Because without this the Catalog Rules don't make any sense...

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Isn't the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/14516?

Thanks!

**Comment by ghost** [comment]
Yes. It's becoming urgent... as many of customers want to set massive discounts on their stores...

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

It is added to our debug roadmap.
Your ticket is a duplicate of #14516
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14516
