### ISSUE TITLE
Javascript definitions loaded only after scripts

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#16302]
**Describe the bug**
In current classic theme the javascript variable defintions that can be set e.g. in a module by Media::addJsDef() are added only after the internal and external javascript code and are therefore not available when executing JS code that use this variables.

**To Reproduce**
1. Add some JS variable by using Media::addJsDef() (e.g. in a module hookHeader)
2. Add a JS script (into head) that is using the JS variable (e.g. in a module  by using $this->context->controller->registerJavascript('id','script.js', arr**ay('position' => 'head')**)
3. Load the shop
4. Check JS console and source code -> error in JS console, JS variable is not known. In source code, JavaScript is added first, then JS variable definition.
5. In 1.6. bootstrap they are loaded in the correct sequence.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

Could you please provide us a demo module to test it.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by madsoliver** [comment]
Hi,

Can you reopen this?

**I am struggling with the same and here comes my explaination as well:**
How can I assign js-variable before inserting javascript in `head`? I am struggling with undefined js-variable since the js-variables assigned with `Media::addJsDef() `comes **after** the script i register with `registerJavascript()`
         
```
Media::addJsDef(['myvar' => 'example']);
$this->context->controller->registerJavascript('module-'.$this->name.'-script-head', 
'modules/'.$this->name.'/views/js/myscript.js', [
    'position' => 'head',
]);
```
Result:
```
<script type="text/javascript" src="http://localhost/modulos/modules/mymodule/views/js/myscript.js" ></script>
<script type="text/javascript">
        var myvar = "example";
</script>
```
But I need:
```
<script type="text/javascript">
        var myvar = "example";
</script>
<script type="text/javascript" src="http://localhost/modulos/modules/mymodule/views/js/myscript.js" ></script>

```
