### ISSUE TITLE
Category tree wrong current category on homepage

### ISSUE THREAD

**Issue by rtvt** [PrestaShop/PrestaShop#16300]
When you click on homepage after any category page - category tree links module shows previous category instead of home category, when show Current category selected in module settings.

Steps to reproduce:
1. Go to Design - Theme - chose layout - enable left column on homepage to show category tree block.
2. Go to Modules - Category tree links - configure - Set show Current category - save.
3. Go to front office - homepage - you can see All categories here in categories tree block.
3. Now go to any category (clothes/women for example) - you can see Women title in left categories block.
4. Now click go to homepage by click on logo for example - you can see same Women title in categories block. So customers can't see all categories list on home page anymore.

PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @rtvt,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10763
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10763
