### ISSUE TITLE
Permission denied (13)

### ISSUE THREAD

**Issue by ITFGouws** [PrestaShop/PrestaShop#16315]
Notice on line 101 in file /home/gdpintck/public_html/farminabox/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php71) failed: Permission denied (13)

**Comment by khouloudbelguith** [comment]
Hi @ITFGouws,

Thanks for your bug report.
>SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php71) failed: Permission denied (13)

About this issue, it is a server permission issue.
Thanks to check with your hist & feedback.

**Comment by bet0x** [comment]
@ITFGouws In cPanel, logging on your account, you will see Multi PHP, change the session_save_path to something inside your home directory. More here: https://documentation.cpanel.net/display/84Docs/MultiPHP+INI+Editor+for+cPanel

**Comment by khouloudbelguith** [comment]
@bet0x, thanks for your feedback.
@ITFGouws, It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I close the issue, feel free to open a new one when needed.

Thanks!
