### ISSUE TITLE
Cart rules - problems when it is present at the same time a condition on carriers and the free shipping

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#16322]
Hi
I found an error in the "Cart Rules" when it is present a conditions on carriers (so I want to limit the discounts only on some carriers) and I want to offer the shipping selecting the "free shipping" option in the "Actions" section.

![3](https://user-images.githubusercontent.com/653230/68419636-ebbf5e00-019a-11ea-8d91-ec6cb7c8cf88.jpg)
![4](https://user-images.githubusercontent.com/653230/68419637-ebbf5e00-019a-11ea-971f-245dfa0b4eda.jpg)

the carrier option works well if I select an amount o a percentage discount. 
so with the same conditions the result is not applied in the cart summary if I offer the shipping

![1](https://user-images.githubusercontent.com/653230/68419605-d64a3400-019a-11ea-8423-e300091ddc57.jpg)
![2](https://user-images.githubusercontent.com/653230/68419607-d6e2ca80-019a-11ea-925c-c88a5baa4e49.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Could you please confirm these steps:
1. Create a cart rule without code
2. In the Condition Tab: Restrictions 
2.1 Carrier: select some carriers
2.2 Product: select one category & select one Attribute 
3. As an action, Free shipping
4. In the FO, in the checkout page => all carriers are free?

Thanks!

**Comment by Maofree** [comment]
hi
check the first 2 images, the second image is the wrong result, where the chosen carriers are not Gratis. The second two images are the result of the removal of the condition on the carriers.

1. Create a cart rule without code (yes without code)
2. In the Condition Tab: Restrictions
2.1 Carrier: select some carriers
2.2 Product: select one category or select one Attribute (I think this condition is not important, any condition is fine)
3. As an action, Free shipping
4. In the FO, in the checkout page => none selected carriers are with free shipping

is it clearer now?
bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I think your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15525

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by nicolas-grzybowski** [comment]
No fix ? I always had thé bug on PS 1.7.8.7 ...
