### ISSUE TITLE
Clean languages (again) in localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16321]
**Is your feature request related to a problem? Please describe:**

Decision has been made to arbitrate on what languages a localization pack should contain or not. As a result, we have decided to keep only official languages (from a country point of view instead of regionally) part of the localization pack and allow the import of other related languages directly in the International > Translations part of the back office.

For instance, the 🇫🇷 localization pack (in International > Localization) will only contain the _French_ language (since it is the only official language). If you're looking for the _Breton_ language, you will be able to download it (in International > Translations > Add / Update a language).

**Describe the solution you'd like:**

**Algeria** pack: remove French
**Azerbaijan** pack: remove Russian
**Brazil** pack: add Portuguese
**Canada** pack: add English
**China** pack: delete Uyghur

And this is where we reach the sensitive part...

**Spain** pack: remove Catalan, Galician, and Basque since they are considered official only regionally
**Finland** pack: add Swedish (_sic_)
**Hong Kong** pack: its two official languages are Yue and English

Another tricky part...

**India** pack: we cannot add Hindi and the other official language is English, other official languages are official regionally
**Israel** pack: remove Arabic
**Jersey** pack: add English
**Morocco** pack: remove French
**Moldavia** pack: remove Russian and Ukrainian
**Serbia** pack: delete all languages except Serbian 
**Singapour** pack: add English and keep Tamil
**Tunisia** pack: remove French

/ ! \ We must make sure that removing languages from some localization packs will not cause issues during the update!

**Comment by eternoendless** [comment]
> We must make sure that removing languages from some localization packs will not cause issues during the update!

I don't think that languages are removed during the upgrade

**Comment by eternoendless** [comment]
> Brazil pack: add Portuguese

There's already Brazilian Portuguese in it

> Canada pack: add English

It's already in that pack

> Jersey pack: add English

It's already in that pack

> Singapour pack: add English and keep Tamil

Both are already added, should we keep Malaysian and Simplified Chinese?

**Comment by matks** [comment]
@eternoendless Is this issue fully fixed by https://github.com/PrestaShop/PrestaShop/pull/16489 or is there a few more items to add ?

**Comment by eternoendless** [comment]
@matks It depends on @LouiseBonnard 's response
