### ISSUE TITLE
Bot Registration

### ISSUE THREAD

**Issue by Leenwt** [PrestaShop/PrestaShop#16327]
**Describe the bug**
Over the past couple of days we have been receiving random registrations from a bot script, I have been unable to fix the problem without enabling a recaptch which is a hurdle for the legitimate customers.

**To Reproduce**
N/A

**Screenshots**
![Random-registrations](https://user-images.githubusercontent.com/21257941/68468622-4e9f0c80-0210-11ea-84e9-2ef2910bb633.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Leenwt,

You can use PrestaShop Geo Location Feature. It is really very good to block the IP.
What is the exact solution did you find?
Thanks!

**Comment by Leenwt** [comment]
@khouloudbelguith I have yet been able to fix the issue, Blocking ip's is great and all but not when they are coming from hundreds of ip addresses! 😆 

I was hoping someone would pick this up and write a sophisticated regex or something that detects random character entry like the customer names are!

For now I am just deleting them as part of a daily task! 😢

**Comment by khouloudbelguith** [comment]
@Leenwt, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Leenwt** [comment]
@khouloudbelguith I could produce all this but its not a configuration issue, It's a flaw in the design of the Auth controller. a simple bot is targeting the authentication form exactly the same way that PR #13604 was.

**Comment by khouloudbelguith** [comment]
@Leenwt, but this issue is fixed in the PS1.7.6.0 & we attempt, from front-office, to create a customer with an URL as first name or last name. 
In your case, the Lastname & Firstname are not URLs.
![image](https://user-images.githubusercontent.com/16067358/68479973-e6fab880-0233-11ea-9766-c7104f2686d2.png)

Thanks!

**Comment by Leenwt** [comment]
@khouloudbelguith I understand this by by patching the email issue they have just designed the bot to use random characters. I am not the only one having this issue. https://www.prestashop.com/forums/topic/960660-bot-customers/

**Comment by khouloudbelguith** [comment]
You are probably being spammed.
See :
- http://build.prestashop.com/news/fighting-against-spamming-again/
- http://build.prestashop.com/news/fighting-against-spamming/

Thanks!

**Comment by matks** [comment]
Hi @Leenwt 

Unfortunately the very best protection against such spam is a reCAPTCHA. As you have said, even if we forbad URLs to be used as firstname or lastname, "they have just designed the bot to use random characters". Regexp or validation on backend side would be a cat-and-mouse game between us and the bot.

ReCAPTCHA was designed to stop bots from submitting any form. It's the exact solution to use for this specific usecase.

**Comment by matutin0** [comment]
Thanks a lot matks!
Do you know what could be a good way to integrate reCAPTCHA in user registration form?

**Comment by khouloudbelguith** [comment]
Hi @matutin0,

Using, for example, this module: https://addons.prestashop.com/en/website-security-access/18478-re-captcha-anti-spam-recaptcha.html, you no longer need to place a line of code on your templates. Everything is automatic for Prestashop.

Thanks!

**Comment by matutin0** [comment]
Thank you, but I've found a free module that works perfectly on PrestaShop v1.7.6.1, adding a reCAPTCHA verification check box when trying to create a new account, so no need to pay those 50€ + TAX for such a simple thing.

EICAPTCHA:
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

It's the last version of the module for PS 1.7, released in March 2018, but still seems to work like a charm. It's reCAPTCHA v2 only though. Remember to activate the option "Enable Captcha for account creation" in module's settings.

**Comment by khouloudbelguith** [comment]
Hi @matutin0,

Thanks for your feedback.
@Leenwt, I close the issue, feel free to open a new one when needed.

Thanks!
