### ISSUE TITLE
Customers export from the BO - Wrong 50 limit

### ISSUE THREAD

**Issue by Slews** [PrestaShop/PrestaShop#16328]
Hello,

When you use the "export" button of the customer grid from the Backoffice:
![image](https://user-images.githubusercontent.com/52968867/68471864-6b8f0c00-021f-11ea-8eea-c3d070c2414c.png)

The file is limited to 50 entries. It should extract all the Customers.

In the PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController::exportAction(CustomerFilters $filters)
There is no filter setting. So the default values of the Filter are the following:

    public static function getDefaults()
    {
        return [
            'limit' => 50,
            'offset' => 0,
            'orderBy' => 'date_add',
            'sortOrder' => 'DESC',
            'filters' => [],
        ];
    }

The issue can be handled adding: `$filters->set('limit', null);` at the top of the controller.

Best regards.

**Comment by khouloudbelguith** [comment]
Hi @Slews,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1.
It is OK with PS1.7.5.2
I used this script to create a lot of customers
```
<?php

ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
define('PS_SHOP_PATH', 'shop.com'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$psXML = <<<XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
 <customer>
   <id />
   <id_default_group>3</id_default_group>
   <id_lang>1</id_lang>
   <email>test@test.com</email>
   <firstname>test</firstname>
   <lastname>test</lastname>
   <passwd>testtt</passwd>
 </customer>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'customers' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
for ($i = 1; $i <= 60; $i++) {
    $xml = $webService->add( $opt );
}

$xml = $webService->add( $opt );
```
It is aregression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
Thanks for diving into this @Slews 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/1.7.6.x

Thank you!

**Comment by khouloudbelguith** [comment]
Hi,

With PS1.7.6.2build1, we can export a maximum 100 customers.
![image](https://user-images.githubusercontent.com/16067358/68478829-24aa1200-0231-11ea-9be3-10ed062e05b6.png)

Thanks!

**Comment by Slews** [comment]
@marionf the thing is I don't think my """solution""" is good enought to be put directly on the core code.
It was mostly to help you to quickly understand the issue.
Adding $filters->set('limit', null) to the action would ask to do the same thing for all Grid Controller exportAction(). And I don't think this would be the best way.
I do think a more DRY compliant solution would be preferable. But for now, I don't have the possibility (the time basically :p) to dive more and build a more proper fix, sorry.

Maybe I'm wrong and this is actually the best way to fix the issue, but still, I think it needs further look to ensure the solution pulled is the proper one.

@khouloudbelguith in fact, the filter you are showing is used for the grid display, not for the export functionality.

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0
Only 50 customers are exported.

**Comment by PierreRambaud** [comment]
The problem must be the same with Categories, Manufacturers and Suppliers :thinking:

**Comment by khouloudbelguith** [comment]
Same with Categories & Manufacturers pages.

**Comment by Progi1984** [comment]
Merged in #16742

**Comment by florianeb-meme** [comment]
Hello, 
We have the same issue with the abandonned carts.

**Comment by Progi1984** [comment]
@florianeb-meme Please open  an issue relative to your problem, with a test scenario. Thanks for your contribution.
