### ISSUE TITLE
Product price from products in the pack displayed when "Show price" is disabled

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#16329]
**Describe the bug**
Product price from products in the pack displayed when "Show price" is disabled

**To Reproduce**
1. Create a pack

![image](https://user-images.githubusercontent.com/15104724/68472964-07217c00-0222-11ea-9a89-6c47c74f86a7.png)

2. Disable "Show price"

![image](https://user-images.githubusercontent.com/15104724/68472982-14d70180-0222-11ea-86b4-67ff9696adbe.png)

3. Check product page. Pack price is hidden but not products price

![image](https://user-images.githubusercontent.com/15104724/68473020-2c15ef00-0222-11ea-878a-7418897c3119.png)

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & PS1.7.6.2 build1.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@idnovate 

I think the prices of the product in the pack should be hidden if "show price" is disabled for these product and not for the pack, what do you think ?

**Comment by idnovate** [comment]
Hi,

we have tested hiding the price of one of the product in the pack and it's
still displayed.
The TPL to display the price of the products inside of the pack doesn't
have the "show_price" control.

Regards,
David

--

[image: www.idnovate.com] <http://www.idnovate.com/>

<https://www.prestashop.com/es/expertos/agencias-web/idnovate>

👉 Échale un vistazo a todos nuestros módulos
<https://addons.prestashop.com/109_idnovate> 😀

<https://addons.prestashop.com/109_idnovate>

Web
www.idnovate.com
Teléfono (+34)931514565
Correo electrónico info@idnovate.com
Dirección

@Sant Cugat Business Park
Avda. Via Augusta 15-25
08174 - Sant Cugat del Vallès
Barcelona - España

**Comment by idnovate** [comment]
@marionf 

Apologize if we didn't understand your message, for us, the correct behavior should be that disabling the show price in the product pack, the product pack and all the products in the pack should have the price hidden.

Regards,
David

**Comment by mrochapt** [comment]
Hi,
As I understand from the posts above, this issue has been solved in 1.7.7.3.
The problem is that I am experiencing the exact same behaviour in 1.7.7.4.
Is there any solution available or anything that has to be done to change this behaviour?
Greetings and thank for your time.

**Comment by matks** [comment]
> Hi,
> As I understand from the posts above, this issue has been solved in 1.7.7.3.
> The problem is that I am experiencing the exact same behaviour in 1.7.7.4.
> Is there any solution available or anything that has to be done to change this behaviour?
> Greetings and thank for your time.

Hello @mrochapt can you try on a freshly installed 1.7.7.4 shop to make sure this behavior comes from the shop, not one of the installed modules?

If it's confirmed
- it's possible another issue (different from the one solved) produces same outcome, so it looks like same issue but it's 2 issues that trigger the same effects
- it's possible an error was introduced in 1.7.7.4 that reverted the fix (it happens unfortunately 😢 )

Anyway, if you can confirm on fresh 1.7.7.4 shop the bug can be observed please open a new bug report so we can add it for future roadmap

**Comment by mrochapt** [comment]
Hi,
I can confirm I am using a fresh 1.7.7.4 install.
On a previous server I had version 1.7.6.5 and I don't recall having this issue... but I could be wrong.

**Comment by mrochapt** [comment]
Hello,
Just to be sure, I installed version 1.7.7.5 on a fresh VM with Ubuntu.
There is nothing else in there besides Prestashop.
I still get the same behaviour.

**Comment by NeOMakinG** [comment]
@mrochapt would you mind create a new issue for this? I think it's a merge from another branch who removed the fix, we need to reproduce it ourself and fix it :)

Edit: I'll reopen this one

**Comment by NeOMakinG** [comment]
@hibatallahAouadni please, could you reproduce it and confirm that this behavior came back? 🙏 

Thanks a lot

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

I didn't manage to reproduce the issue with 1.7.7.5, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/122192871-54e97600-ce94-11eb-8d0e-9c25997c8a8e.png)

![image](https://user-images.githubusercontent.com/23308427/122192888-57e46680-ce94-11eb-984e-4f4f521b55c2.png)

Thanks!

**Comment by mrochapt** [comment]
Hi,
Maybe I misunderstood the problem.
What was reproduced above is not showing any prices. What I am aiming for is not showing the prices of the products in the pack, but still show the price of the pack.
This should be achieved by disabling the "show price" in the sub-products, but not for the pack itself.
Does this make sense, or am I asking too much of the tool?

**Comment by hibatallahAouadni** [comment]
Hello @mrochapt 

I think this option is not only for the products in the pack but also for the pack itself. This means that when we disbaled this option, all the prices should be hidden (the price of the pack and the prices of the products).

Ping @PrestaShop/product-team could you please confirm my point :pray: unless I misunderstand the functionality of this option.

**Comment by marionf** [comment]
@hibatallahAouadni yes, as specified in the [specs](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit.md): 
> Show price: This checkbox appears when you unselect “available for order” checkbox and it’s checked. If you uncheck it, the product price isn’t displayed on the product page and product lists in front-office. For a pack, the price of the pack and the prices of the products contained in the pack are not displayed

**Comment by hibatallahAouadni** [comment]
@mrochapt I think it's quite clear now :wink: 
_PS: if you encounter any issue, please feel free to open a new issue, thanks!_

**Comment by mrochapt** [comment]
Thank you for your explanation.
I guess this feature does more than expected, and as such is of little use to me.
The point was to have the price of the pack shown, but not the price of the sub-products, witch I don't intend on selling directly.
Thanks anyway.
