### ISSUE TITLE
Customer Review Anonymisation

### ISSUE THREAD

**Issue by MathildeJoli** [PrestaShop/PrestaShop#16339]
Be able to remove the customer lastname on the front of the Avis Client module, having the choice of 
- Full name (First name + Last name) : Melodie Dupont 
- Partial name (First name + Last name first letter).  Melodie D

**Comment by khouloudbelguith** [comment]
Hi @MathildeJoli,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment]
Hello @MathildeJoli ,

This is indeed an interesting feature, I add it to the to do list for a future version of this module ! 
Thanks !

@jolelievre we should add a configuration option allowing the merchant to choose if he wants to display the full name or only the first letter. Wdyt ?

**Comment by jolelievre** [comment]
Yep! That's a good idea!

**Comment by Oksydan** [comment]
@khouloudbelguith PR avalible

**Comment by jf-viguier** [comment]
@MathildeJoli I've found a bug with anonymisation : if comments come from product_comment module before version 4.0, customer_name values are not empty with registered customers, so anonymisation is not done.

**Comment by jf-viguier** [comment]
I've posted a pr to fix this https://github.com/PrestaShop/productcomments/pull/92
