### ISSUE TITLE
Email Theme permissions settings are not saved when trying to enable them

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16337]
**Describe the bug**
It is impossible to re-enable the permissions settings for the Email Theme page **once they have been disabled**.
The modification does not seem to be saved when enabling the permissions.

When I go to the Permissions page, the Email Theme page permissions (first email theme row, the parent one) are unchecked, I checked them, See a confirmation message, but when I refresh the boxes are unchecked again...

See video:
https://drive.google.com/file/d/1aU2dbka6r1mFvhQpOYjaZg9C3pXz_nNg/view

⚠️**This means that any new profile created won't have access to Email Theme, as per default all permissions are unchecked when creating a new profile
SuperAdmin is the only account to have access to email Theme**

**To Reproduce**
1. Go to 'Advanced Parameters > Team > Permissions' and select a profile you can edit
2. Unchecked all the Email Theme permissions (2 rows) -> See confirmation message
3. Refresh the page, Check all boxes -> See confirmation message
4. Refresh the page, scroll to the Email Theme rows, the first one is unboxed
5. You can try to check this specific row's boxes again, but this time there is no confirmation message and after refreshing the boxes are still unchecked

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @samuel-pires,

I have the same behavior as PS1.7.6.2build1 & PS1.7.6.1.
Also, when we create an employee with this permission, the Email theme page cannot be displayed.
This page doesn't exist in the previous version PS1.7.5.2.
So, we don't have the same issue with PS1.7.5.2.

What do you think: it should be fixed in the PS1.7.6.x or develop?

Thanks!

**Comment by ghost** [comment]
As decided during today's Daily, we'll fix it for 1.7.7
