### ISSUE TITLE
Copy Croatian tax rates in EU localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16336]
**Is your feature request related to a problem? Please describe:**

So far, Croatia was not considered part of the EU in PrestaShop. It has been fixed for version 1.7.7. (cf. #15618) so Croatia and its tax rates must be reported in all European packs.
 
**Describe the solution you'd like:**

🇭🇷 _What are the Croatian tax rates again?_

25% Standard Rate
13% Reduced Rate
5% Reduced Rate
0% Zero Rate

🇪🇺 _What European packs are concerned?_ 

Austria / Italy / Belgium / Latvia / Bulgaria / Lithuania
Croatia / Luxembourg / Cyprus / Malta / Czechia / Netherlands
Denmark / Poland / Estonia / Portugal / Finland / Romania
France / Slovakia / Germany / Slovenia / Greece / Spain
Hungary / Sweden / Ireland / United Kingdom

**Specifications:**

As a merchant, I want to be able to sell all over Europe without having to import all European taxes manually. 

Following this statement, a German merchant must be able to sell his/her products to Croatia at the maximum tax rate of 25%. So his/her store must, by default, contains:

- all German tax rates (here, 19% and 7%)
- the Croatian tax rate (here, 25%)

Each European pack must contain the other European tax rates.

**Comment by colinegin** [comment]
@LouiseBonnard could you detail what should happen and is not working currently ? 
And what should be the impact of fixing this ?

**Comment by LouiseBonnard** [comment]
@colinegin, I'm doing some research about it, I'll keep you posted. ;-)

**Comment by LouiseBonnard** [comment]
@eternoendless, I found a piece of explanation by digging into PrestaShop's GitHub history. It is a bit old but I cannot find a more recent one... all EU localization packs share the same tax rule on virtual products and it requires each tax rate to be gathered and marked with the `eu-tax-group="virtual"` mention. As far as I can see, it has always been coded like that. Unfortunately, I cannot find why.

cf. https://github.com/PrestaShop/PrestaShop/commit/028015a8b2b910139e92f4e18f0aebd9bc766587

**Comment by sam-pires** [comment]
@LouiseBonnard Need more info.
What is it going to be used for? How can QA test?
