### ISSUE TITLE
Bullets of bulleted lists are removed by default

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#16333]
By default, PrestaShop changes the behaviour of bulleted lists by removing the bullets:
https://github.com/PrestaShop/PrestaShop/blob/4f5d70f1ae3a9ceb5251a850551e79d8ff62a0d7/themes/classic/_dev/css/partials/_commons.scss#L14-L17

So, every time I make a bulleted list, I don't have the bullets, and that's quite annoying. Would it be possible to remove this piece of code from the default theme?

If we want a list of "unbulleted" items, we could use multiple `<div>` or add a class like `list-unstyled` to the `<ul>`.

**Comment by khouloudbelguith** [comment]
Hi @yannicka,

Thanks for your report.
Ping @@PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by dennispw** [comment]
Since most of the `ul` and `ol` element used in the theme, such as in the footer, navigation, pagination etc. this snippet below could be an option. Chances are, if a `ul` or `ol` has a class it will most likely be to remove that styling. Snippet below only removes the bullets if the list actually has a class.

```
ul[class],
ol[class] {
  list-style: none;
}
```

**Comment by yannicka** [comment]
I do not think that remove bullets/numbers to ul/ol when they have a class is a good idea.

I think the best thing to do is to have the behaviour expected from the browser: have the bullets/numbers and remove them explicitly by adding a class like `list-unstyled`.

If there is a notion of retrocompatibility, it's possible to wait for the next major version: 1.8.

**Comment by rdy4ever** [comment]
I do believe most use cases for bulleted lists will be in cms pages content. This way we don't mess with the global styles. PR here: #16340

**Comment by yannicka** [comment]
I also think that this is the most common use. So thank you for the PR.

However I think that bulleted lists can be used elsewhere, like in pages: https://github.com/PrestaShop/ps_checkpayment/pull/25.
