### ISSUE TITLE
Fatal error on any admin change

### ISSUE THREAD

**Issue by alphaonex86** [PrestaShop/PrestaShop#16341]
**Describe the bug**
`[09-Nov-2019 15:47:41 Europe/Paris] PHP Warning:  require(/home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/getPrestashop_SearchParameters_ResolverService.php): failed to open stream: No such file or directory in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/appProdProjectContainer.php on line 1136
[09-Nov-2019 15:47:41 Europe/Paris] PHP Fatal error:  require(): Failed opening required '/home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/getPrestashop_SearchParameters_ResolverService.php' (include_path='/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear_exception:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/console_getopt:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear-core-minimal/src:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/archive_tar:.:/usr/share/php7:/usr/share/php') in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/appProdProjectContainer.php on line 1136
[09-Nov-2019 15:47:41 Europe/Paris] PHP Warning:  require(/home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/getTwig_Controller_ExceptionService.php): failed to open stream: No such file or directory in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/appProdProjectContainer.php on line 1136
[09-Nov-2019 15:47:41 Europe/Paris] PHP Fatal error:  require(): Failed opening required '/home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/getTwig_Controller_ExceptionService.php' (include_path='/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear_exception:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/console_getopt:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear-core-minimal/src:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/archive_tar:.:/usr/share/php7:/usr/share/php') in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/prod/ContainerZ5xnfp1/appProdProjectContainer.php on line 1136`

**To Reproduce**
0. Bug produced with most option change
1. Go to Traffic and SEO
2. Click on URL rewriting to Yes or no
3. Error 500

**Additional information**
PrestaShop version: 1.7.6.1, 1.7.5.2
PHP version: 7.3, 7.2

**Comment by khouloudbelguith** [comment]
Hi @alphaonex86,

PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by alphaonex86** [comment]
Hi,
I have already try, but no change.
Cheers,

**Comment by khouloudbelguith** [comment]
@alphaonex86, Could you please follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by alphaonex86** [comment]
No red, only Image Processing (ImageMagick) and Memcached in yellow.

**Comment by khouloudbelguith** [comment]
@alphaonex86, the mod_rewrite is enabled on your server?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by alphaonex86** [comment]
The missing info: Linux Gentoo, Nginx 1.16.1-r1
Here is error 500, fatal error, then unlinked to rewrite_rule
My conf:
`server {
    listen 127.0.0.1;
    server_name shop;
    root /home/user/Desktop/www/shop/;
    index index.html index.php;
    location / {
        try_files $uri $uri/ /index.php?$args;
        rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
        rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
        rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
        rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
        if (!-e $request_filename) {
            rewrite ^/.*$ /index.php last;
        }
    }
    location /admin_vMnFGqUp4WN3yj4t/ {                                  # [REQUIRED EDIT] the name of your admin directory
        if (!-e $request_filename) {
            rewrite ^/.*$ /admin_vMnFGqUp4WN3yj4t/index.php last;   # [REQUIRED EDIT] the name of your admin directory
        }
    }
    location ~ \.php$ {
            try_files $fastcgi_script_name /index.php$uri&$args;
            fastcgi_intercept_errors on;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/run/php.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_read_timeout 3600;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }
}`

**Comment by khouloudbelguith** [comment]
@alphaonex86, In my case, I did not manage to reproduce the issue with PS1.7.6.1 & Nginx server.
It is a server configuration issue.
here's my nginx configuration
```
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	# Add stdout logging
        error_log /var/log/nginx/error.log info;
        access_log /var/log/nginx/access.log;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files $uri $uri/ /1750/index.php?$args;
		# Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
		# AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
	}
	# Gzip Settings, convert all types.
        gzip on;
        gzip_vary on;
        gzip_proxied any;

        # Can be enhance to 5, but it can slow you server
        # gzip_comp_level    5;
        # gzip_min_length    256;

        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;

        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
	# Symfony controllers
        location /1750/admin-dev/ {                                  # [REQUIRED EDIT] the name of your admin directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /1750/admin-dev/index.php last;   # [REQUIRED EDIT] the name of your admin directory
            }
        }

        # Cloudflare / Max CDN fix
        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        # Do not save logs for these
        location = /1750/favicon.ico {
            log_not_found off;
            access_log off;
        }
        location = /1750/robots.txt {
            auth_basic off;
            allow all;
            log_not_found off;
            access_log off;
        }


	error_page 404 /1750/index.php?controller=404;

        location ^~ /sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }
        location ^~ /twitter.svg {
            alias /var/www/errors/twitter.svg;
            access_log off;
        }
        location ^~ /gitlab.svg {
            alias /var/www/errors/gitlab.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off; 
    		deny all;
	}
        
	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}

```
I created from this file https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
Thanks to check & feedback.

**Comment by alphaonex86** [comment]
Same problem with your configuration file.

**Comment by khouloudbelguith** [comment]
@alphaonex86, did you edit it? or just copy-paste?

Thanks!

**Comment by alphaonex86** [comment]
Copy and paste + edit server name.
PS: the bug seam randomly occur (80% of bug, 20% of the time work).

**Comment by khouloudbelguith** [comment]
@alphaonex86, when debug mode is enabled, are there any exceptions displayed?

Thanks!

**Comment by alphaonex86** [comment]
Few warning: 

WARNING16:36:03 | translation | Translation not found.Hide context[▼   "id" => "SEO options"   "domain" => "AdminShopparametersFeature"   "locale" => "en-US" ]
-- | -- | --


Few deprecation I test with version 1.7.5.2:
User Deprecated: The AbstractGridDefinitionFactory::setHookDispatcher method is deprecated as of 1.7.5.1 Please use the constructor instead
Enabling the "sensio_framework_extra.router.annotations" configuration is deprecated since version 5.2. Set it to false and use the "Symfony\Component\Routing\Annotation\Route" annotation from Symfony itself.

**Comment by khouloudbelguith** [comment]
@alphaonex86, this is just a deprecation & a warning.
It is not an error.
It couldn't help to understand what's wrong.

THanks!

**Comment by alphaonex86** [comment]
Ok, you should have the info. If you need more info, request me.

**Comment by khouloudbelguith** [comment]
@alphaonex86, the issue is related to your server configuration.
This is a config file by default
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
It is provided by PrestaShop & you should edit it to be compatible with your server.
For example, you should edit the root: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L5
You should edit the admin folder name
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf#L56

Thanks!

**Comment by alphaonex86** [comment]
Already try, no change, as dev, for me it's linked with php, not http server.

**Comment by khouloudbelguith** [comment]
@alphaonex86, thanks to follow these steps:
0. Enable debug mode
1. Clear cache manually
2. Give the right permissions to your Project_Folder
3. Enable SEO & URL & save
4. check if there is an exception displayed
for example "No route found for "GET /configure/shop/seo-urls/options": Method Not Allowed (Allow: POST)" 

In my case, it is OK
https://drive.google.com/file/d/1ZgxS5hirxeuSTHaaZAmQxkl7qMaCSfDx/view
THanks!

**Comment by alphaonex86** [comment]
1. Done
2. Done
3. Done
4. Get error 500 from log:

> [11-Nov-2019 19:03:00 Europe/Paris] PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(/home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/getAnnotations_CacheService.php): failed to open stream: No such file or directory in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php:1211
Stack trace:
#0 /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php(1211): require()
#1 /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php(2005): Container9yf7poi\appDevDebugProjectContainer->load('getAnnotations_...')
#2 /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php(1617): Container9yf7poi\appDevDebugProjectContainer->getAnnotationReaderService()
#3 /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php(2299): Container9y in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php on line 1211
[11-Nov-2019 19:03:00 Europe/Paris] PHP Fatal error:  Container9yf7poi\appDevDebugProjectContainer::load(): Failed opening required '/home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/getAnnotations_CacheService.php' (include_path='/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear_exception:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/console_getopt:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear-core-minimal/src:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/archive_tar:.:/usr/share/php7:/usr/share/php') in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php on line 1211
[11-Nov-2019 19:03:00 Europe/Paris] PHP Fatal error:  require(): Failed opening required '/home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear_exception:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/console_getopt:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/pear-core-minimal/src:/home/user/Desktop/www/shop.bolivia-online.com/vendor/pear/archive_tar:.:/usr/share/php7:/usr/share/php') in /home/user/Desktop/www/shop.bolivia-online.com/var/cache/dev/Container9yf7poi/appDevDebugProjectContainer.php on line 1211

Cheers,

**Comment by khouloudbelguith** [comment]
@alphaonex86, As you can see in your error log file, there are only cache errors.
Did you use a caching like Memcached or APC?

Thanks!

**Comment by alphaonex86** [comment]
Hi, it's default prestashop. No more than change the SEO option.
Then I don't configure and use any cache.

**Comment by khouloudbelguith** [comment]
@alphaonex86, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by alphaonex86** [comment]
Done without error.
Bug remain here.

**Comment by khouloudbelguith** [comment]
@alphaonex86, Despite our several trials, we could not reproduce your issue with the provided information.
https://drive.google.com/file/d/11NoB-EpZlGBcizGyfq8UNFL5OIpYlywT/view
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by alphaonex86** [comment]
Hi,
I wish paid the support to fix, not by hours... (have a fixed price)
The problem is in the core, nginx is officially supported by prestashop, and I use the default prestashop configuration.

**Comment by alphaonex86** [comment]
Same bug under Linux debian, clearly bug into the php, then no other way than drop from our datacenter. Cheers,

**Comment by khouloudbelguith** [comment]
@alphaonex86,

>The problem is in the core, nginx is officially supported by prestashop, and I use the default prestashop configuration.

we provide an example of configuration here:
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf :)
You must write your own rules, like we do for Apache. You must not use a rewrite where you don't need it.
More because it's an example and you can customize this part by everything you want.
Also, you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/10156#issuecomment-416482457, it is our developer's configuration.

Thanks!

**Comment by alphaonex86** [comment]
For now I search just do work the base prestashop as demo. Then I need need write my own rules.
Here the wrong php include call will not be fixed by http server nor customized rule.
You just miss understand how php and http server work.
