### ISSUE TITLE
Module and services 

### ISSUE THREAD

**Issue by rekondaren** [PrestaShop/PrestaShop#16345]
Hi,

I downloaded a module that took to long to install so I refreshed the page and now when I click on Module and services it sends me to a blank page and also when I click on module catalogs it says try again.
How do I solve this problem?

PHP-version: 7.2.24
PrestaShop version: 1.7.6.1

**Comment by rdy4ever** [comment]
Hi @rekondaren 
Try to go to your website root directory via ftp or file manager in CPanel, go to modules folder, locate the module you were trying to install and rename/delete it.

**Comment by khouloudbelguith** [comment]
Hi @rekondaren,

What is the exact name of this module?
Is it compatible with PrestaShop 1.7.6.1?
It is not well installed in your case, so you have issues during the configure.
Thanks!

**Comment by rekondaren** [comment]
> Hi @rekondaren
> Try to go to your website root directory via ftp or file manager in CPanel, go to modules folder, locate the module you were trying to install and rename/delete it.

Hi,

Thank you very much I deleted it and it worked.
