### ISSUE TITLE
re-sending email with status change

### ISSUE THREAD

**Issue by mjamroz** [PrestaShop/PrestaShop#16346]
**Describe the bug**
Variables related with emails are not displayed in an email template (at least "bankwire" template)

**To Reproduce**
1. Go to order details view in backoffice
2. Click on "resend an email' (for example for status "waiting for bankwire")
![Screenshot_2019-11-10_23-55-18](https://user-images.githubusercontent.com/505646/68552279-89be5d00-0415-11ea-8237-b5a1ad97f426.png)

3. sent email still has {bankwire_details} instead of value.

adding 

`
$templateVars['{bankwire_owner}'] = Configuration::get('BANK_WIRE_OWNER');                                                              
$templateVars['{bankwire_address}'] = nl2br(Configuration::get('BANK_WIRE_ADDRESS'));                                                 
$templateVars['{bankwire_details}'] = nl2br(Configuration::get('BANK_WIRE_DETAILS'));    
`
to 1618 line of `controllers/admin/AdminOrdersController.php` fix the problem with this particular (bankwire) template. Moving file to override dir is a bit scary since that particular function is one big if/else with ~1200 lines of code.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @mjamroz,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1Bg9Tuiuhf7oFsIeGT4IYW_MAFHCl_guQ/view
Thanks to check & feedback.

**Comment by mjamroz** [comment]
Hi @khouloudbelguith ,
ahh, I am sorry - i just repeat it but with disabled all external modules and overrides and it works like on your screen record (i mean - it works properly). 

Sorry for taking your time, i will close this issue and try to locate source of error in my installation.

cordialement,
michał

**Comment by khouloudbelguith** [comment]
@mjamroz, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
