### ISSUE TITLE
Problem with cart rule when it is limited only on some products

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#16351]
Hi
the shopkeeper has created a discount using the cart rule like I show in these images
all is ok in the front office, there is a problem only when the product that has this discount "Sconto Villaggio Meraviglie" is in the cart with other products that they have not this discount. This discount is applied to all total product price, not only to the discounted product.

https://shop.natur.it/home/3228-159-magnolmin.html
with this product is possible to use the discount with code "KAXTCY7J"
if you add another product to the cart you can see that the total discout value include all products

I can pass you the access to this site

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/68584320-8a8bd900-047f-11ea-9c14-d9c6269588b0.png)
![2](https://user-images.githubusercontent.com/653230/68584321-8a8bd900-047f-11ea-85e8-1da2213234e2.png)
![3](https://user-images.githubusercontent.com/653230/68584322-8a8bd900-047f-11ea-8b6c-35c39327e352.png)
![4](https://user-images.githubusercontent.com/653230/68584324-8b246f80-047f-11ea-81f9-370fdfdefa4a.png)
![6](https://user-images.githubusercontent.com/653230/68584879-0c303680-0481-11ea-98e1-018b647d2387.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @maofree,

But this is a restriction for Product selection ( what are the exact products should be added to the cart to have a valid cart rule)and not an action to be applied to those products only.
In the action Tab, you are selecting this option: "Apply a discount to
Order (without shipping)" => so the discount is applied on the total.
![image](https://user-images.githubusercontent.com/16067358/68586383-d8571000-0484-11ea-956f-54364e9d1d72.png)

Thanks!

**Comment by Maofree** [comment]
Hi
so it is necessary to select the option "selected products" ?

**Comment by Maofree** [comment]
yes it works now with that option
thanks

**Comment by khouloudbelguith** [comment]
@maofree, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
