### ISSUE TITLE
UPC should allow 13 digits

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#16354]
**Describe the bug**
We have an integration with products integrations which push datas to our feed with Web Services. 

When the product updates prices and availability, it's creating dublons because Prestashop doesn't accept zero's in the begining of UPC code. The integration works with UPC and brand manufacturer informations to update the quantity and prices on a daily base.

The problem is we can't really modify the UPC pushed by supplier. So when it's sync prices and availability on a daily base, the product are dupplicated because it doesn't update the same product.

**To Reproduce**
1. Catalog >Products > Edit a existing Product
2. Modify UCP product codes with 0095205842258 and save. (two zeros)

**Screenshots**
![2019-11-11_09h34_13](https://user-images.githubusercontent.com/16780421/68595233-0cbbd380-0467-11ea-8812-f25d8761e68f.png)
![2019-11-11_09h38_55](https://user-images.githubusercontent.com/16780421/68595287-278e4800-0467-11ea-8157-7d06579e4991.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.20

**Comment by khouloudbelguith** [comment]
Hi @8ternity,

UPC (technically refers to UPC-A) consists of 12 numeric digits that are uniquely assigned to each trade item.
But in your case, you have 13 numeric digits.
If you try with this 009520584225 => OK
https://drive.google.com/file/d/1Vo-Ky0JwuxIgHyMM-CKIe78ff8FggmD_/view
Thanks to check & feedback.

**Comment by 8ternity** [comment]
@khouloudbelguith I do understand. The problem is the UPC is pushed by a integration product catalog. It comes from the manufacturer itself.

**Comment by khouloudbelguith** [comment]
@8ternity, so it is not a PrestaShop issue?

Thanks!

**Comment by 8ternity** [comment]
Yes it was if the UPC has 13 digits. It's the original UPC codes provided by Xerox Corporation.

**Comment by khouloudbelguith** [comment]
@8ternity, so can I close the issue?

Thanks!

**Comment by 8ternity** [comment]
@khouloudbelguith No. it's an actual UPC. we must allow 13 digits on UPC codes.

**Comment by khouloudbelguith** [comment]
@8ternity, thanks!
Ping @PrestaShop/prestashop-product-team @marionf what do you think of this improvement?

Thanks!

**Comment by marionf** [comment]
Hello @8ternity 

EAN (European Article Number) is a standardized barcode with a 12 or 13 digit product identification number.
The Universal Product Code (UPC) is a 12-digit barcode commonly used for sales packaging in the United States.
Your reference isn't the UPC but the EAN-13, so you should fill the EAN-13 field
