### ISSUE TITLE
Problem with automatic generated .htaccess 'Primary script unknow'

### ISSUE THREAD

**Issue by cd2500** [PrestaShop/PrestaShop#16350]
Yesterday I installed latest PS 1.7.6.1. I'm getting this error in the logs when I open a product:
[proxy_fcgi:error] [pid 552] [client xxxxxxx] AH01071: Got error 'Primary script unknown', referer: https://xxx/index.php/sell/catalog/products/13? token......
I did a research over the net and came to the conclusion, that this must be something wrong in the .htaccess of Prestashop. It's default one created from BO. The only lines I have extra are the secured login folder for where Prestashop is installed.
I'm using php 7.3.1.1 all latest updates on that Debian9 server. Tried also to reboot the server, but nothing changed with this error.
Found also this over the net related to same problem: http://www.coders.pro/2017/01/got-error-primary-script-unknown-update-php-fpm-apache-2-4/
PS version before in use was 1.7.2. with several problems with php 7.2., so I upgraded it to php 7.3. and also the Prestashop version to 1.7.6.1. Did not upgrade the older shop. Installed a new one, because they are demo shops and not shops in production.
Strange that on same server and same php-version I'm running a WP-Site and there are no errors.

**Comment by khouloudbelguith** [comment]
Hi @cd2500,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by cd2500** [comment]
Why is the 1-click module than forcing a php upgrade to 7.3. ? I was not able to upgrade, because the module was blocking the php version and forcing by message "please upgrade to php 7.3. before you upgrade Prestashop". This is weird information. 
PS version in use before was 1.7.2. with php 7.0. upgraded to php 7.2., also not working. Reverted to 7.0. working, but also with some minor error messages. Seems that no PS 1.7. version is really working well with php 7.x series.

**Comment by khouloudbelguith** [comment]
@cd2500, what is the exact version of the 1-click upgrade did you use?
I tried with different servers (PHP7.2 & PHP7.1) & they are well working.
https://drive.google.com/file/d/1ce1wxlZ5Zw4doLJ9r2V2gu9x8GX59GPs/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @cd2500,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
