### ISSUE TITLE
Free gifts are not added in cart anymore

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16366]
1. Create a cart rule with a free gift
2. Add a product to the cart
3. Add the cart rule
4. You don't see the free gift in the cart
5. The discount line isn't displayed
6. The amount of free gift is 0,00€ 
7. Free gift isn't displayed in the order confirmation and BO order

![capture d'écran_2137](https://user-images.githubusercontent.com/13449658/68661216-e0718700-053a-11ea-8415-d986f25ea9d0.png)

It was working in 1.7.6

![capture d'écran_2136](https://user-images.githubusercontent.com/13449658/68661243-eb2c1c00-053a-11ea-8d74-c701ec62638b.png)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Did you use the develop branch?
It is OK with me.
I attached a screen record
https://drive.google.com/file/d/1HpunOITAFSx1I7LeX5QNJnHEmq7QpGCa/view
Thanks to check & feedback.

**Comment by marionf** [comment]
Yes it was on develop but, I can't reproduce it anymore
