### ISSUE TITLE
Faceted search module Issue with the hook exception on displayLeftColumn

### ISSUE THREAD

**Issue by Djolhan** [PrestaShop/PrestaShop#16362]
The exception position on the Faceted search module is not working.

**To Reproduce**
Exemple to reproduce (Same way for other pages. it's juste an exemple) :

1 - Go to appearence > theme and logo > Choose the layout > add left column to cms page
2 - Go to position
3 - Search displayleftcolumn, 
4 - Edit Faceted search module hook
5 - add cms in exception

The module will not disappear. Exception wont work.

**Additional information**
All prestashop 1.7 version.
Php 7.2 and 7.3
Module version v3.4.0 and before that same issue, on version v2.2.0 it worked correctly.

**Comment by khouloudbelguith** [comment]
Hi @Djolhan,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Your module ps_facetedsearch, before adding the cms in the exception, it was displaying in the cms page?
For example, in your page "delivery", the ps_facetedsearch is displaying?

Thanks!

**Comment by Djolhan** [comment]
hi @khouloudbelguith . I know the compatibility, anyway, working for my tests.

Module was showing on the left column before adding exception.
Display in delivery, legals mentions, etc. But, in my exemple, i talked about cms, but, it's same way on other pages, modules, contact etc. Every where you want to add exception, it's not working.

**Comment by khouloudbelguith** [comment]
@Djolhan, `ps_factedsearch` by default is displayed in the categories page.
So, if you add the category in the exception, in the FO, it will not be displayed.
I attached a screen record
https://drive.google.com/file/d/18RAOxEG8LZ5lG6U6d_BdQBasrpMhgFJT/view
Thanks to check & feedback.

**Comment by Djolhan** [comment]
Seems to work. ok.

**Comment by khouloudbelguith** [comment]
@Djolhan, so can I close the issue?

Thanks!

**Comment by Djolhan** [comment]
yes, you can, thanks.

**Comment by khouloudbelguith** [comment]
@Djolhan, thanks!
Feel free to open a new one when needed.

Thanks!
