### ISSUE TITLE
Problem with shipping in 1.7.5

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16364]
Hi, how can I exclude a category from free shipping?

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

Are you creating a cart rule Free shipping?
You can add your specific category to the unselected items as a Product restriction.
![image](https://user-images.githubusercontent.com/16067358/68662559-58d94780-053d-11ea-8239-38d3a9626ea5.png)

![image](https://user-images.githubusercontent.com/16067358/68662496-36dfc500-053d-11ea-9642-8dde0ca1dc46.png)

Thanks to check & feedback.

**Comment by Webgaict** [comment]
Yes I have already created the cart rule but if I add a product with the category not selected and one with the selected category. I still get free shipping.

**Comment by khouloudbelguith** [comment]
@Webgaict, the only solution is that as described previously.
"Give the rule some generic conditions and a code (so we can test it); then, under restrictions, tick Product selection.
In the “Add a rule concerning” select box, choose categories, then hit add. A new box will appear below, where you can choose the category you want to restrict this voucher too.
Then, in the action tab, if you select a discount percentage, you must make sure to check the “selected Products” box, under “Apply a discount to”. This will make sure other products are not affected by the price reduction.
This, however, limits us in the case we want to use another rule like free shipping on specific categories only. 

Thanks!

**Comment by Webgaict** [comment]
Can I apply this rule (attached image) only for some categories? Also by changing the code.
![shipping](https://user-images.githubusercontent.com/56969939/68675032-508e0600-0557-11ea-83a0-897c4740693b.png)

**Comment by khouloudbelguith** [comment]
@Webgaict, no this applied only if you have total  > exact price or Weight > exact value.
But you can use a custom module on our add-ons market place
https://addons.prestashop.com/en/
Thanks!

**Comment by Webgaict** [comment]
So my free shipping is from € 300 how can I exclude only one category or certain products? With the cart rules it is applied only when there are individual products in the excluded category, if together I put other products it becomes free when it should not be.

**Comment by khouloudbelguith** [comment]
@Webgaict, sorry this feature doesn't exist by default in PrestaShop.
But you can find a lot of module in our addons Market place
For example:
https://addons.prestashop.com/en/shipping-costs/46559-advance-free-shipping.html
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
