### ISSUE TITLE
Free shipping as visitor

### ISSUE THREAD

**Issue by Majusek** [PrestaShop/PrestaShop#16361]
Hi I tkink that I have a smiliar problem.

I have a diffrent carriers for diffrent countries.
When client is a visitor (not logged yet) and his localization is diffrent that default countrie set in shop, shipping cost in cart is free.
If client is a visitor (not logged yet) and his localization is the same as default countrie set in shop the shipping cost is correct.

I suppose that the geolocalization work correctly, but shop doesn't set shpping cost if default countrie is not the same as client's countrie localization.

Is this normal situation? How to repair this?

Another thing is that, when i try to disable Visitor's group for one of carrier than nothing happen. Still appear in cart.
But After this modification: https://github.com/PrestaShop/PrestaShop/pull/13517 it start work.
Why before that modification when I disabled visitor's group that function didn't work?

PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @Majusek,

>I have a diffrent carriers for diffrent countries.
When client is a visitor (not logged yet) and his localization is diffrent that default countrie set in shop, shipping cost in cart is free.
If client is a visitor (not logged yet) and his localization is the same as default countrie set in shop the shipping cost is correct.
I suppose that the geolocalization work correctly, but shop doesn't set shpping cost if default countrie is not the same as client's countrie localization.
Is this normal situation? How to repair this?

This situation is not foxed after applying this fix? 

>Another thing is that, when i try to disable Visitor's group for one of carrier than nothing happen. Still appear in cart.

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2build1 & develop branch(1.7.7.0version).
https://drive.google.com/file/d/1AgbVHEcp9f3IUitlF6Z8Ic0fkoHL8MIL/view

Thanks!

**Comment by Majusek** [comment]
Hi @khouloudbelguith 

thanks for Your reply. 

Your example is very simple. After add this fix is working as on your record.
But if you have more than one coutry / area add in shipping than is the problem.
When You visit Your shop from antoher country than default set in shop than this fix doesn't work.

Best regards

**Comment by khouloudbelguith** [comment]
@Majusek, no I tried with develop branch( the fix is merged)
I followed these steps:
0. France & Spain are enabled
1. Create two Zones France & Spain
2. Edit the Zone for France from Europe to France
3. Edit the Zone for Spain from Europe to Spain
4. Create two carriers no available for Vistors
4.1 the first carrier is only available for France
4.2 the second carrier is only available for Sapin
5. France is the country by default
6. My localization is fixed to another place (not France & Sapin)
7. Go to the FO as a Visitor, add the Product to the cart
8. The shipping line is not added

I attached a screen record
https://drive.google.com/file/d/1XbvHDvaEhY0ajfQKBdmC2Jdq89lla-at/view

Thanks to check & feedback.

**Comment by Majusek** [comment]
@khouloudbelguith  thanks for your feedback.

I describe my configuration what I have:

1. I'm haveing many Zones. Sometimes zone have a few countries or sometimes zone is representing only one country.
2. To reproduce my configuration you need use three zones, one per country for example France, Spain, Germany.
3. Add three carriers, one will be for France, second for Spain and Germany, third for all countries.
4. For first and second zones add some prices. Third carrier will be for Personal pickup with cost 0.
5. Set France as default countrie in admin panel.
6. Test like this:
- Visit shop from France - default country set in shop - as not loged user. Next add product to car. What cost do you see? In my example when I testing, have normal cost.
- Visit shop from Spain or Germany as not loged user. Add product to cart. What cost do you see? In my situation I have "free" cost. But I want the cost get from Spain or German.

My questions are:
1. Why if I visit shop from diffrent country than default country set in shop I have free shipping?
2. Why system don't work as the same when I visit shop from default country?
3. Is this  the bug or is this standard situation?

Best regards

**Comment by khouloudbelguith** [comment]
@Majusek, I have a question:

1. The first carrier for France, is it available for visitors or no?
2. The second carrier for Spain and Germany, is it available for visitors or no?
3. The third carrier for all zones, is it available for visitors or no?
4. In your BO => International => Localization, the option "Set default country from browser language" is enabled or no?

![image](https://user-images.githubusercontent.com/16067358/68838257-7b469e80-06be-11ea-854c-5e7310e7d3ee.png)

Thanks!

**Comment by Majusek** [comment]
Hi @khouloudbelguith thanks for your feedback

1. Yes
2. Yes
3. Yes
4. No

Best regards

**Comment by khouloudbelguith** [comment]
@Majusek, so, your visitor can see all carriers?
![image](https://user-images.githubusercontent.com/16067358/68855315-45191700-06de-11ea-81c2-a06dd5efe3b8.png)

Thanks!

**Comment by Majusek** [comment]
@khouloudbelguith 
Sorry, I told you wrong. Visitor is uncheked for third carrier. Third carrier is for all countries.

**Comment by khouloudbelguith** [comment]
@Majusek, In my case:
1. Visit shop from France - default country set in shop - as not logged user.
=> the carrier is displayed in France (default country)
2. Visit shop from Spain - not default country - as not logged user.
=>  the carrier is displayed in France (default country)

I attached a screen record
https://drive.google.com/file/d/13VKYvU096Zs8rZ1b436MEV8gJu05EAQ8/view

Thanks!

**Comment by Majusek** [comment]
@khouloudbelguith  ok, thanks a lot for this testing.

I see that it works for you, but I still have no ideas why it doesn't work for me.

**Comment by khouloudbelguith** [comment]
@Majusek, it is fixed in the next version PS1.7.7.0.
Thanks!

**Comment by Majusek** [comment]
@khouloudbelguith  do you know when we could expect new version?

**Comment by khouloudbelguith** [comment]
@Majusek, you can follow our project here: https://github.com/PrestaShop/PrestaShop/projects/7
I close the issue, feel free to open a new one when needed.

Thanks!
