### ISSUE TITLE
Increase Admin customer Logout time

### ISSUE THREAD

**Issue by nenes25** [PrestaShop/PrestaShop#16367]
**Describe the bug**
Hello,
For one customer i need to increase the logout time in back-office.
This value is hardcoded to 900 in class AdminController.php
( see : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L2834 )
In order to do it properly, i want to override the class AdminController.php.
Unfortunately this class implements private methods and the function init cannot be override.

I know the "Remember Me" function and i've already check the issue #12043 
This issue is more related with the fact that core classes shoud not use private function in order the keep the legacy overrides working.

**To Reproduce**
1. Create an override of AdminController.php
2. Override the function init with the same content
3. Change only the value 900 to something else

**Screenshots**
![image](https://user-images.githubusercontent.com/7163132/68664877-5b3da080-0541-11ea-9845-0f3166a6f1b5.png)

**Additional information**
PrestaShop version: develop

In order to fix this, we could imagine multiples solutions : 
- Remove usage of private methods
- Add a configuration

Regards,

**Comment by khouloudbelguith** [comment]
Hi @nenes25,

I think your issue is similar to this issue: #15396 about using protected instead of private.
Thanks to check & feedback.

**Comment by nenes25** [comment]
Hi @khouloudbelguith ,

You're right, this issue can be related with the use of public/private argument and methods in core classes

My question is,  if it is pertinent or not in this specific case ?
Or if a configuration( or protected class argument ) instead of the hardcoded value will solve the need ?

In my case to suit my needs i had to make change directly in the core class which is the worst thing to do ...

Regards,

**Comment by khouloudbelguith** [comment]
@nenes25, If you have some usecases where you wanted to do something with PrestaShop and you could not because of a private property/function, you can create a Pull Request to make it available, we'll consider the change and if it is relevant we'll change it for the next version. But sometimes we'll keep some things locked as we are afraid of the dangerous mistakes their usage can bring.

Thanks!

**Comment by jf-viguier** [comment]
@nenes25 I've started a PR https://github.com/PrestaShop/PrestaShop/pull/16880
Join the discussion
