### ISSUE TITLE
Infinite scroll - Backward button excludes other pages

### ISSUE THREAD

**Issue by Allbutfancy** [PrestaShop/PrestaShop#16368]
Hello you amazing Github people!

**Describe the bug**:

Anybody else had the problem that when you activate the inifiniy scroll on your webshop and scrool down to page two (in the url). Then when someone clicks on a products and wants to go back by using the backward button in their brower, they're sent back to the (inifinity scroll page 2) but they're not able to see the other pages.

**To Reproduce**
1. Activate infinity scroll
2. Scroll down to url page 2 or above on a category page
3. Click at a product on page 2 or above
4. After arriving at the product page, click the backward buttons in your browser.
5. You're back at page 2 in your infinity scroll but without any of the previous pages being displayed.

PrestaShop version: 1.7.6.1
PHP version: 7.2.24

Thanks in advance! :) 
Best regards

**Comment by khouloudbelguith** [comment]
Hi @Allbutfancy,

Are you using a custom module to enable the infinity scroll or just you are increasing the product number of products per Page in the BO => Product Settings page?
![image](https://user-images.githubusercontent.com/16067358/68666932-22072f80-0545-11ea-8430-41e949fcad39.png)

Thanks!

**Comment by Allbutfancy** [comment]
Hello @khouloudbelguith 
Thank you for your response! We just decided to go back to pagination due to the loading speed, that might change if we increase it to 100 products.

But thanks once again!
Best regards,

**Comment by khouloudbelguith** [comment]
@Allbutfancy, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
