### ISSUE TITLE
Cash on Delivery (COD) missing translation

### ISSUE THREAD

**Issue by P1X3L0V4** [PrestaShop/PrestaShop#16369]
**Describe the bug**
Module Cash on Delivery (COD) - ps_cashondelivery has at least one missing translation string visible in the back office despite the fact that it is correctly translated in the International > Translations Manager.

Sting in the backoffice: Cash on Delivery (COD)
Should be (example): Płatność przy odbiorze
(Polish translation)

**To Reproduce**
1. Go to International> Translations
2. Choose Installed modules translation, Cash On Delivery, Language version (Polish in our case)
3. Translate phrase "Cash on delivery (COD)" and save
4. Go to Orders
5. Choose an Order with "Cash on delivery (COD)" payment method
6. The phrase is not translated both on the list and inside order edit mode.

**Screenshots**
![Image of Translations](https://i.imgur.com/IlluYaI.png)
![Image of Orders](https://i.imgur.com/VG3j2O7.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22
COD Module: 1.0.6

**Comment by khouloudbelguith** [comment]
Hi @P1X3L0V4,

The issue is fixed with the develop branch (1.7.7.0 version)
https://drive.google.com/file/d/1P9BWXAbAwLzpFJ4KyfdP-btH2QunzT5V/view
Thanks to check & feedback.

**Comment by ziegenberg** [comment]
Could this fix be backported to 1.7.6.3?

**Comment by khouloudbelguith** [comment]
Hi @ziegenberg,

It is not a regression, so it cannot be fixed in the next patch PS1.7.6.3.

Thanks for your understanding!

**Comment by ziegenberg** [comment]
So this can be closed than, as it's fixed in 1.7.7.0?

**Comment by khouloudbelguith** [comment]
@ziegenberg, yes!
But, I'm waiting for @P1X3L0V4's feedback.

Thanks!

**Comment by P1X3L0V4** [comment]
> @ziegenberg, yes!
> But, I'm waiting for @P1X3L0V4's feedback.
> 
> Thanks!

Thank you for the update! Issue closed 👍
