### ISSUE TITLE
Back office: Viewed products - date is showing product id - not date

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#16363]
In back office I noticed in the VIEWED products area that the product id is showed instead of the date. 

<img width="828" alt="Screenshot 2019-11-12 at 09 19 04" src="https://user-images.githubusercontent.com/46492443/68658765-f6c51600-052d-11ea-9bcb-2d2d4a6510a6.png">

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2build1 & develop branch.
![image](https://user-images.githubusercontent.com/16067358/68659668-f598e680-0537-11ea-95d7-889c94777edf.png)

With PS1.7.5.2, we have ID & not Date => so it is correct.
![image](https://user-images.githubusercontent.com/16067358/68659693-047f9900-0538-11ea-8fa2-fc0d54acaf71.png)

I will add to our bug roadmap.

Thanks!
