### ISSUE TITLE
Link List widget 3.0.4 shows No Records Found PrestaShop 1.7.6.1 

### ISSUE THREAD

**Issue by TommyLazo** [PrestaShop/PrestaShop#16382]
The firs time I opened the Link widget it showed 2 items, then I tried to add a new block and it worked only there was no entry that I could modify or delete, so I reset the widget.
After that it showed "No Records Found" , but when I preview the prodpage it shows two default columns, when I add a new block it works  and the third column is visible, but the widget still shows the "No records found" message.
Tried resetting , re-enabling, reinstalling the widget, but still the same.
Any suggestions on how to solve this issue ?
Thank you in advance 

**Screenshots**
![image](https://user-images.githubusercontent.com/57686463/68709355-34618780-059e-11ea-9cb2-3a88a7051a1c.png)

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
HI @TommyLazo,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_linklist v3.0.4.
I attached a screen record
https://drive.google.com/file/d/1XZJBve7BK6Tzd_N8o8aSVguI9yZYXboz/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TommyLazo** [comment]
I managed to find a solution to this issue.
The root cause was the language setup, my primary language was set as Lithuanian and english was disabled. But the admin interface was still in English. So when I enabled English and set it as primary language the Link list started to show all the entries.

**Comment by khouloudbelguith** [comment]
@TommyLazo, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by pepisign** [comment]
Hello,
I have the same issue with PrestaShop 1.7.6.5 and Link List 3.2.0
My shop language is Bulgarian, but BO is in English. Enabling English didn't help solving the problem. Link Widget is still showing no records, although the links appear on my shop page.

**Comment by khouloudbelguith** [comment]
Hi @pepisign,

We are awre of this issue, it is added to our debug roadmap.
This ticket is a duplicate of #16434
Please follow #16434
Thanks!
