### ISSUE TITLE
Product customization not displayed on order view page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16389]
**Describe the bug**
Product customization is not displayed on new order page

**To Reproduce**
1. Go to FO and order the product "Mug personnalisable"
2. Display the order in BO
3. The customization isn't displayed

**Screenshots**
![capture d'écran_2139](https://user-images.githubusercontent.com/13449658/68751300-a3bc9300-0601-11ea-91f3-8a8bfad7cd80.png)

Legacy page

![capture d'écran_2138](https://user-images.githubusercontent.com/13449658/68751317-aae3a100-0601-11ea-98f7-181ad13e64c7.png)

**Please note the customization can be an image and should be also displayed in this case**

![capture d'écran_2140](https://user-images.githubusercontent.com/13449658/68751648-3b21e600-0602-11ea-8874-4031c98f407e.png)

Design  

Customized product in product list: 
![Custo 1](https://user-images.githubusercontent.com/27484094/69863555-6f9dcf00-129d-11ea-8869-1dfbf8133a43.png)

Customized pack in product list:
![Capture d’écran 2019-11-28 à 18 11 03](https://user-images.githubusercontent.com/27484094/69863619-952ad880-129d-11ea-9187-dd27c4b17908.png)

The link "View pack content" opens the following popup : 
![Capture d’écran 2019-11-28 à 15 45 29](https://user-images.githubusercontent.com/27484094/69864434-2f3f5080-129f-11ea-9631-4afea0693ee1.png)

Note that the customizable elements (text or image) related to the pack only appear in product list, not in popup.  

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
@MatShir @matks @sarahdib @Robin-Fischer-PS FYI

**Comment by marionf** [comment]
To be reproduced when the page will be fully migrated

**Comment by Robin-Fischer-PS** [comment]
New bugs linked to product customization : 

* When updating the quantity of a product with customization, the "Total Tax Included" is not updated after saving **=> Still KO** :negative_squared_cross_mark: 
* Probably linked to this bug, when I change the quantity of the product with customization on migrated page, there is 4 product (2 + 2 on this case) : 
![image (3)](https://user-images.githubusercontent.com/55688534/72062518-3d3db380-32d8-11ea-8d91-bc4246918af0.png)
But when I check the Legacy page, there is in fact the 2 "original" product with the customization, and 2 "new" product without the customization, instead of 4 "original" with customization

**Comment by MatShir** [comment]
> * Probably linked to this bug, when I change the quantity of the product with customization on migrated page, there is 4 product (2 + 2 on this case) :
>   ![image (3)](https://user-images.githubusercontent.com/55688534/72062518-3d3db380-32d8-11ea-8d91-bc4246918af0.png)
>   But when I check the Legacy page, there is in fact the 2 "original" product with the customization, and 2 "new" product without the customization, instead of 4 "original" with customization

@Robin-Fischer-PS could you explicit the steps we can't really reproduce it ?

**Comment by Robin-Fischer-PS** [comment]
@MatShir Noob ! Here is a screenrecord with the scenario : 
https://drive.google.com/file/d/1TW7vfJj6kCLtcCmuWvqeqx5hIPaHGG-e/view?usp=sharing

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17381
