### ISSUE TITLE
Missing columns on new order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16391]
**Describe the bug**
Missing columns on the new order page

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit a product and fill the field stock location
2. Order this product in FO
3. See the order in BO
4. Stock location and Available quantity are missing

**Screenshots**
![capture d'écran_2142](https://user-images.githubusercontent.com/13449658/68752884-5261d300-0604-11ea-9390-6ff70a14c805.png)

Legacy

![capture d'écran_2141](https://user-images.githubusercontent.com/13449658/68752919-660d3980-0604-11ea-8b12-e003b042016e.png)

**Solution**
The stock location column is hidden only when none of the products has a stock location only on the website. The column is only displayed at the corresponding pagination. If only a product on page 2 of the list has a stock location then the stock location column appears on page 2 and hidden in the other pages.
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
@MatShir 

Is it wanted to not display these columns ?

**Comment by marionf** [comment]
To be reproduced when the page will be fully migrated

**Comment by Progi1984** [comment]
Fixed in #17135
