### ISSUE TITLE
Missing button to display the content of a pack in the new order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16393]
**Describe the bug**
The button to display the content of a pack in the new order page is missing

**To Reproduce**
1. Go to FO and order the product "Pack Mug + affiche encadrée"
2. Display the order in BO
3. There isn't the button "Package content" to display the content of the pack

**Screenshots**
![capture d'écran_2147](https://user-images.githubusercontent.com/13449658/68754836-cb165e80-0607-11ea-9d68-e77346942e78.png)

Legacy

![capture d'écran_2146](https://user-images.githubusercontent.com/13449658/68754848-d10c3f80-0607-11ea-94ba-dc497c745362.png)

**New design**

A link ("View pack content") is displayed below the products in a pack on product list:
![Capture d’écran 2019-11-28 à 15 40 06](https://user-images.githubusercontent.com/27484094/69815006-b637ee80-11f5-11ea-82d2-9936d0859367.png)

It opens the products from the pack in a popup: 
![Capture d’écran 2019-11-28 à 15 43 29](https://user-images.githubusercontent.com/27484094/69815085-da93cb00-11f5-11ea-8e27-0653f1c142fb.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
@MatShir @matks @sarahdib @Robin-Fischer-PS FYI

**Comment by marionf** [comment]
To be reproduced when the page will be fully migrated

**Comment by Progi1984** [comment]
Fixed in #16722
