### ISSUE TITLE
Total tax incl is 0,00 on new order page for a customizable product

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16390]
**Describe the bug**
Total tax incl is 0,00 on new order page

**To Reproduce**
1. Go to FO and order the product "Mug personnalisable"
2. Display the order in BO
3. Total tax incl is 0,00

**Screenshots**
![capture d'écran_2144](https://user-images.githubusercontent.com/13449658/68753847-f5ffb300-0605-11ea-8bb7-2c64c2e8e7f5.png)

Legacy 

![capture d'écran_2145](https://user-images.githubusercontent.com/13449658/68753858-fb5cfd80-0605-11ea-9687-2de1fdedb9e2.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
@MatShir @matks @sarahdib @Robin-Fischer-PS FYI

**Comment by marionf** [comment]
To be reproduced when the page will be fully migrated

**Comment by Hlavtox** [comment]
This doesnt work even on front office. Maybe related to this? https://github.com/PrestaShop/PrestaShop/pull/15171 It fixed the issue for me on FO.

**Comment by Progi1984** [comment]
Fixed in #16150
