### ISSUE TITLE
[Catalog price rule page] Replace "reduction" with "discount"

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#16402]
This issue is following the test of the catalog price rule page (add / edit action)

For more consistency with the discount features, we need to change the word "reduction" which is used both in the catalog price rule list and add / edit with "discount" :

Reduction type ==> Discount type
Reduction with or without taxes ==> Discount with or without taxes
Reduction ==> Discount

Thanks !

**Comment by LouiseBonnard** [comment]
In my opinion, we need to distinguish two things:

- in PrestaShop, discounts stand for both 'cart rules' (= promo codes) and 'catalog price rules' (= reductions), cf. https://github.com/PrestaShop/PrestaShop/pull/13716#discussion_r285951623

- in this case, the reduction type refers to the form of the catalog price rule (= it refers to the form of one of the discount type) and is either an amount or a percentage

I'm afraid that replacing 'reduction' with 'discount' will bring more confusion - and this part is already pretty confusing. In my mind, 'discount type' means 'cart rule' or 'catalog price rule', and not 'amount' or 'percentage'. Also, the good thing about naming it 'reduction type' is that it reminds the user that he/she is creating a reduction (which are the catalog price rules' aim but which is not that clear when you are creating a discount for the first time).

**Comment by colinegin** [comment]
I agree with you @LouiseBonnard , let's leave it the way it is now (on top of that, it's one issue less to do ;) ) Thanks for your quick answer !
