### ISSUE TITLE
Wrong cms page title using CMS::getLinks function

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#16409]
**Describe the bug**

**To Reproduce**
1. multi-store enabled
2. created one cms page, with different title in each store
3. Try to use somewhere CMS::getLinks(), you'll see that page title is always this one from first store, even if you will try to use it on second store

**Additional information**
PrestaShop version: 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

I found a bug with PS1.7.6.1, but it is fixed with PS1.7.6.2build1
It is ok with PS1.7.6.2build1.
I attached a screen record
https://drive.google.com/file/d/1fFe79dZkBA_El6dtWm6jbHbLY5O5L-9Z/view
Thanks to check &feedback.

**Comment by kpodemski** [comment]
This fix is not related to back office but to this specific function

**Comment by khouloudbelguith** [comment]
@kpodemski, thanks!
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2build1.
https://drive.google.com/file/d/1b3ABzdi_SzvMeUxVft1egkgIhE9L78Jy/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by kpodemski** [comment]
@khouloudbelguith I've sent pull request already :D thanks
