### ISSUE TITLE
Module Gives Error googlecustomerreviewssnippet 

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#16411]
Hello,

I download the module : https://github.com/albangonzalez/googlecustomerreviewssnippet

But when I try to upload on PS give me error. I have PS 1.7.5

Do you know why?
Thank you

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
