### ISSUE TITLE
Frontend Translation mixed up when switching languages

### ISSUE THREAD

**Issue by 23b** [PrestaShop/PrestaShop#16412]
This bug is triggered in various ways i will describe a easily reproducible way here:

- Start with a fresh installation of Prestashop 1.7.6.1
- Add 2 or more additional language packs (German and French in my case)
- Create a customer account
- Change customer firstname to a **invalid** one like "John.P" by direct SQL update
- Log in with the Customer on the Frontend
- Switch between the frontend languages

Now notice how some parts of the page will correctly update languages while others will remain in the previous language.

**Comment by khouloudbelguith** [comment]
Hi @23b,

Yes, I manage to reproduce the issue with PS1.7.6.1.
But, I cannot edit the firstname from the database manually => this is incorrect behavior.
From the BO / FO, it is impossible to add ta custom with an invalid name.
Editing it manually => this is an insecure way.
![image](https://user-images.githubusercontent.com/16067358/68872169-de0b5a80-06fd-11ea-8cb2-29977ecf342f.png)

How you can reproduce the issue without editing the firstname from the database?

Thanks!

**Comment by 23b** [comment]
I understand that the username will not be able to register like that. Although a customer could be setup like that through migration from a older Prestashop version.

The real problem is that we have an instance which shows the exact same issue without having modified customer names. I have spend several days trying to track down the origin on that instance without avail. The only requirement there in that the customer has to be logged while switching languages. I just hope that fixing the bug as described above will ultimately solve our, harder to reproduce issue.
Although I have found a rather strange fix for the bug in that case: If there is a missing resource while loading the frontend (like a missing img/script) before the language is switched the bug will not appear. 

My impression is that the underlying issue is somehow related to cookie processing. But I cannot wrap my head around how the Prestashop core uses different values for **id_lang** while rendering a single page.

**Comment by khouloudbelguith** [comment]
@23b, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
https://drive.google.com/file/d/145kDUL7wa97HLjM-xqtvwvZtoJWNXWnq/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by 23b** [comment]
Good news. My colleague found a fix by changing the first lines of Context::getTranslator() as follows.
```
public function getTranslator($isInstaller = false)
    {
        if (null !== $this->translator) {
            if ($this->language->locale === $this->translator->getLocale()) {
                return $this->translator;
            }
        }
...
```
We trust your judgement whether or not this is a good implementation. But at least it will provide a leg up in finding a proper fix.

**Comment by khouloudbelguith** [comment]
@23b, great!

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!
