### ISSUE TITLE
Problem with product on 1.7.5

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16427]
Hello,
I have a product with 1323 combinations when I try to modify it in any way it gives me the error "Could not update settings" how can I proceed?
Thanks for help!

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

I have an issue similar to your problem reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9809
It is added to our bug roadmap.
Thanks to check & feedback.

**Comment by Webgaict** [comment]
An imminent solution does not exist? Because as far as I can see the problem dates back to about a year ago.

**Comment by khouloudbelguith** [comment]
@Webgaict, sorry, it is not fixe yet.
Your ticket is a duplicate of #9809
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #9809
