### ISSUE TITLE
Improve error message on module installation

### ISSUE THREAD

**Issue by lichesser** [PrestaShop/PrestaShop#16428]
**Describe the bug**

When uploading a module with a large ZIP file in the BO you can get the error message `This value should not be null.`. The message is not helpful and should instead explain the reason and probable causes.

Reason: The upload of the file failed somehow. On a technical side it means `$fileUploaded` is `null` . The relevant code in `ModuleController -> importModuleAction` is around [here](https://github.com/PrestaShop/PrestaShop/blob/e7ad37e4642951fdbf07504425280bc708837358/src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php#L519-L543)

Cause: Can be multiple. One possible cause is that the PHP setting `post_max_size` is smaller than the filesize of the uploaded module ZIP-file. (The case when the file is bigger than `upload_max_filesize` is already handled correctly) .

I suggest to provide a better error message for the `$fileUploaded` is `null` case:

_Your uploaded file might exceed the upload_max_filesize and the post_max_size directives in php.ini, please check your server configuration._ to be localized in _Admin.Notifications.Error_, as suggested in https://github.com/PrestaShop/PrestaShop/issues/16428#issuecomment-584697861.

**To Reproduce**
1. In the BO open the "Module manager"
2. Click on "Upload a module"
3. Upload a module ZIP file bigger than `post_max_size` 
4. Installation fails
5. Click on "What happened?" in the error modal
6. See the unhelpful error message "This value should not be null."

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
HI @lichesser,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.6.1 & PS1.7.6.2build1.
![image](https://user-images.githubusercontent.com/16067358/68950117-cbeff180-07bb-11ea-8d31-46e0bcc2fe4f.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by LouiseBonnard** [comment]
Hi @lichesser, thanks for raising this issue! Do you already know the error message you would like to read here? We could think about something better, indeed. :-)

**Comment by lichesser** [comment]
Hi @LouiseBonnard,

I have no specific error message in mind.

Maybe something along the lines of

`File upload failed. Maybe the file is too large. Try checking the configuration for post_max_size and upload_max_filesize`

As I'm unfamiliar with the code base and how this plays together with the symfony validation code it's unclear to me if this case can even be "nicely" handled with the current `constraints <-> validation` approach.

AFAIK to detect this specific error case you need to check if  `$fileUploaded === null` and if at the same time `$_SERVER['CONTENT_LENGTH'] > 0` for the `POST` request then it's `post_max_size` is too small.

**Comment by LouiseBonnard** [comment]
In your opinion, could the following error message apply here?

 _Your uploaded file might exceed the upload_max_filesize and the post_max_size directives in php.ini, please check your server configuration._ in _Admin.Notifications.Error_

> As I'm unfamiliar with the code base and how this plays together with the symfony validation code it's unclear to me if this case can even be "nicely" handled with the current constraints <-> validation approach. AFAIK to detect this specific error case you need to check if $fileUploaded === null and if at the same time $_SERVER['CONTENT_LENGTH'] > 0 for the POST request then it's post_max_size is too small.

@PrestaShop/prestashop-core-developers, any information to share about it?

**Comment by lichesser** [comment]
Looks ok to me. Except that it probably should read `exceed` not `exceeds`

**Comment by LouiseBonnard** [comment]
@lichesser, absolutely, thanks for notifying this typo. ;-)

**Comment by go-sudo** [comment]
Hi
Same issue and resolved, post_max_size must be greater than max file upload

**Comment by LouiseBonnard** [comment]
HI @go-sudo, thanks for this information! If you have already fixed it on your end, feel free to share your solution here with a pull request. :-)

**Comment by PierreRambaud** [comment]
Already fixed by #21009

**Comment by LouiseBonnard** [comment]
Bad timing, it is fixed but the message previously validated (https://github.com/PrestaShop/PrestaShop/issues/16428#issuecomment-584697861) has not been taken into account... I reopen this issue and set it as an _improvement_ instead. Hopefully, someone could take it as a good first issue. :-)
