### ISSUE TITLE
Retira Titulo do email 

### ISSUE THREAD

**Issue by FabricioBottassi** [PrestaShop/PrestaShop#16438]
boa tarde 

alguem sabe mo dizer como tira o nome que aparece na minha loja como ( a minha Loja ) dos contesto do email?

Já fiz de tudo para editar mais não encontrei 

![image](https://user-images.githubusercontent.com/57812967/68972064-b386d380-07c9-11ea-8412-c1b7856096ea.png)

**Comment by khouloudbelguith** [comment]
Hi @FabricioBottassi,

Please, send your request in English.
English is the norm on GitHub
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @FabricioBottassi,

Your issue is incomplete, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
