### ISSUE TITLE
Product pagination not working in BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16430]
**Describe the bug**
In back office, on product page, the pagination is not working : I cannot change go to next page, or change number of products displayed per page.

**To Reproduce**
1. Go to Product page on BO
2. Try to change number of products displayed per page.

**Screenshots**
https://drive.google.com/file/d/1drtwAVL3WnTchqcJcUEeUxz1zw_Ho69G/view?usp=sharing

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Same issue with develop branch
