### ISSUE TITLE
Admin HTTP ERROR 500, dependency on a non-existent parameter "mail_themes_dir"

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#16449]
Hi, I get the following error when I try to log in to the administrator, did it happen to someone else?

Thanks

Log-file: `The service "prestashop.core.mail_template.theme_folder_catalog" has a dependency on a non-existent parameter "mail_themes_dir". Did you mean this: "themes_dir"?`

PrestaShop version: 1.7.5.2
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @kenlog,

Are you using PS1.7.5.2? or did you make an upgrade to PS1.7.6?
Because The mail template generator is a new feature added to PS1.7.6 in this PR: https://github.com/PrestaShop/PrestaShop/pull/12046

Thanks to check & feedback.

**Comment by kenlog** [comment]
Hi @khouloudbelguith thanks for the speed of the reply, I tried to perform the automatic update but it doesn't seem to have succeeded, after which it is no longer possible to access the admin panel. I think this update attempt probably altered the db causing the problem. 

You are aware of a similar situation and how I could try to get out of it. 
Thanks.

**Comment by khouloudbelguith** [comment]
@kenlog, now your current version is PS1.7.5.2 or PS1.7.6.?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by kenlog** [comment]
@khouloudbelguith current version is PS1.7.5.2 I looked at the log in autoupgrade but last reference dates back to [2019-06-03 10:53:45] does not seem to have written anything else recently. :confused:

**Comment by khouloudbelguith** [comment]
@kenlog, did you made the upgrade since when?
In your file: Project_Folder/app/config/config.yml those lines exist:?
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/app/config/config.yml#L16
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/app/config/config.yml#L17

Thanks!

**Comment by kenlog** [comment]
Hi @khouloudbelguith I ran the update a couple of days ago. I have checked and the following parameters mail_themes_uri and mail_themes_dir  are not present in config.yml

**Comment by khouloudbelguith** [comment]
@kenlog, now check if this file is displayed in your path
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/src/PrestaShopBundle/Resources/config/services/core/mail_template.yml

Thanks!

**Comment by kenlog** [comment]
@khouloudbelguith It exists

**Comment by khouloudbelguith** [comment]
@kenlog, so that's the problem.
The file, it doesn't exist in the PS1.7.5, it is added during the upgrade, but your file /project_folder/app/config/config.yml is not updated.
Try to add those lines in your file: Project_Folder/app/config/config.yml those lines:
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/app/config/config.yml#L16
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/app/config/config.yml#L17

Thanks!

**Comment by kenlog** [comment]
@khouloudbelguith Added and this is the result: `PHP Fatal error: Uncaught Symfony\\Component\\Yaml\\Exception\\ParseException: A YAML file cannot contain tabs as indentation at line 16 (near "\tmail_themes_uri: "/mails/themes"").`

**Comment by kenlog** [comment]
@khouloudbelguith Added and this is the result: `PHP Fatal error: Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: The service "prestashop.core.currency.grid_data_factory" has a dependency on a non-existent service "prestashop.core.grid.data_provider.currency".`

**Comment by khouloudbelguith** [comment]
@kenlog, during the upgrade to PS1.7.6, you have a problem.
Have you a backup before the upgrade?

Thanks!

**Comment by kenlog** [comment]
Yes sure, in the meantime, thank you for your help. @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@kenlog, thanks to check & feedback.

**Comment by kenlog** [comment]
@khouloudbelguith In conclusion I preferred to update the latest version 1.7.6.2 by migrating the data.

**Comment by khouloudbelguith** [comment]
@kenlog, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
