### ISSUE TITLE
 E-mail blocked by spamhaus

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#16446]
Hi,

Some order confirmations are not received by our teams. In fact, with each order, 5 people must receive this confirmation.

When the problem happens, some people do not receive the order confirmation or all.

We checked with our provider and it seems that spamhaus blocks Prestashop IP addresses:
- 178.33.107.228/32
- 46.105.33.33/32

Do you be aware of these problems?

The Prestashop version used is 1.6.1.3

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

You are probably being spammed.
See :

http://build.prestashop.com/news/fighting-against-spamming-again/
http://build.prestashop.com/news/fighting-against-spamming/

[The maintenance of PrestaShop 1.6.1.x is now being performed exclusively by volunteers to fix critical issues only](http://build.prestashop.com/news/1.6.1.x-what-s-next/)
For this reason, we are closing your issue.

Thanks!
