### ISSUE TITLE
[Order List] Bulk action to open multiple orders in new tabs

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#16455]
**Is your feature request related to a problem? Please describe.**
To open multiple orders in a new tab with the bulk actions.
**Describe the solution you'd like**
Add "Open in new tabs" in the bulk action list. 

If the browser blocks the opening of commands in other tabs, a modal will be displayed to the user to explain how to solve the problem.

**Comment by LouiseBonnard** [comment]
Here are the elements of wording needed:

_Open in new tabs_ in _Admin.Actions_

_We are unable to open all selected orders in new tabs, you might have exceeded the number of tabs allowed. Check your browser settings to open multiple tabs._ in _Admin.Notifications.Warning_

OR

_We are unable to open all selected orders in new tabs, you might have exceeded the number of tabs allowed. Check your browser settings to modify this number._ in _Admin.Notifications.Warning_
