### ISSUE TITLE
Amount cart rule don't removed from total

### ISSUE THREAD

**Issue by Oxyde59** [PrestaShop/PrestaShop#16452]
Hi everybody,

I'm on PS 1.7.5 and I use multi shops
I creat my first cart rule for a 200€ discount on a specific product, but I don't undestand why, the discount is displayed, but not remove from the total.
I know the rule is OK, because when I change de discount from amount to a percent one (20% for example), it work fine (displayed and remove)

We already post some help on prestashop forum here https://www.prestashop.com/forums/topic/1008801-r%C3%A8gle-panier-non-appliqu%C3%A9e-au-total/?fbclid=IwAR0u9KBvNUpV0U-QGkvmqW2s9522OUZ6K-l9EHlSecdiuio1JU2NByhudLc
where u can see some screenshots with the discount in amount (doesn't work), an the discount in percent (work fine)

Can u help us ?

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Oxyde59,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1YunQYYMH6kJZio0TSFmcRP1VssTIObn2/view
Thanks to check & feedback.

**Comment by Oxyde59** [comment]
Did u try with multi shops ?
Here is my result :
https://drive.google.com/file/d/1n3IcVOmFHx6XYCxnDLUn4mix5iVAxTnt/view

**Comment by khouloudbelguith** [comment]
@Oxyde59, yes, it is OK.
https://drive.google.com/file/d/1srNEJP8Y-LtdIuO4zrvNx3EtrtFavBkh/view
Have you tried to contact the theme author about this issue?
Thanks to check with them & feedback.

**Comment by Oxyde59** [comment]
You are wright, i just try on another shop with the classic theme and it work.
I'm going to contact the theme autor, you can close this bug
Thank you !

**Comment by khouloudbelguith** [comment]
Hi @Oxyde59,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Oxyde59** [comment]
I have some news ...
Please could you reopen ?
I could reproduce the problem with the classic theme, so it's not the theme.
We have 2 shops, only one is impacted.
But i forgot to give you a detail : our theme on the impacted shop is on a child_theme

**Comment by Oxyde59** [comment]
Could you test like this with this in first step :  make a child_theme of "classic"

**Comment by khouloudbelguith** [comment]
@Oxyde59, thanks to provide me the exact steps to reproduce the issue.

**Comment by Oxyde59** [comment]
1/ make a child_theme of theme "classic" named "child_classic"
2/ switch the shop to this "child_classic" theme
3/ make a amount discount for a product and test as explain before

**Comment by khouloudbelguith** [comment]
@Oxyde59, I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2
https://drive.google.com/file/d/1xjFobgmUOSS7BkutJ8WANI-vfUIbOqzO/view
I used this child theme
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/3863037/childtheme-example.zip)
downloaded from this repository: https://github.com/PrestaShop/childtheme-example

Thanks to check & feedback.

**Comment by Oxyde59** [comment]
Rhaa f*** :(
thanks for trying.
I can reproduce with our shop, but not with a new shop ...
I don't undestand... Where the total of the cart is calcutated ?

**Comment by khouloudbelguith** [comment]
@Oxyde59,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!
