### ISSUE TITLE
Module::isRegisteredInHook() not manage multistore

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#16458]
**Describe the bug**
If multistore enabled and 2 shops configured, result of Module::isRegisteredInHook() is not good

Hook::isModuleRegisteredOnHook() is good thanks to id_shop usage in query

Module developers use this to check if a hook used by the module is been registered but it do not manage multistore, for example in an upgrade script or configuration checker script

**To Reproduce**
1. Create a new instance of PrestaShop
2. Go to BO > Shop parameters > General
3. Set Enable Multistore to YES 
4. Go to BO > Advanced Parameters > Multistore
5. Create another shop and configure it
6. Set Context to one Shop with shop selector in header
6. Go to BO > Modules > Module Manager
7. Click on Upload a module and use provided testregisteredhooks.zip
8. Install module and go to module testregisteredhooks configuration page
9. All check is green
10. Click on Manage Hooks
11. Unhook one hook used by the module
12. Go to module testregisteredhooks configuration page
13. See results is different

**Screenshots**
<img width="490" alt="configuration" src="https://user-images.githubusercontent.com/5262628/69075395-9eac7900-0a31-11ea-8521-6d72946318da.png">
Module configuration show different result

**Test module**
[testregisteredhooks.zip](https://github.com/PrestaShop/PrestaShop/files/3859849/testregisteredhooks.zip)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Matt75,

I have the same issue with PS1.7.6.1 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/69126279-2503a200-0aa8-11ea-87a9-4c3e6cb39455.png)

I’ll add this to the debug roadmap.
Thanks!
