### ISSUE TITLE
Bad link to Module Catalog from homepage

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16466]
**Describe the bug**
From BO dashboard, I see advertisements for modules. When I click on them am I redirected to my backoffice module catalog on the generic listing page, not on the module I clicked.

**To Reproduce**
1. Go to BO dashboard
2. See the modules advertisement (see screenshot below)
3. Click on advertisement
4. You arrive on standard module catalog page in BO, you dont see the module you have clicked on

**Screenshots**
![Capture d’écran 2019-11-19 à 17 43 26](https://user-images.githubusercontent.com/3830050/69166808-22c73500-0af4-11ea-8f56-842a048dfe54.png)

**Additional information**
PrestaShop version: develop

**Comment by khouloudbelguith** [comment]
Hi @matks,

I have the same issue with PS1.7.5.2 & PS1.7.6.1 & PS1.7.6.2build1.
https://drive.google.com/file/d/1bqLDvaKaCQzhAKcgax5a_7oWDDT9fgPT/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by matks** [comment]
I checked a few others:
- some modules, when I click it works and the module is installed successfully( @PrestaShop/prestashop-product-team is that alright ? I click on a link on dashboard and it installs the module ?!)
- some modules have this behavior

**Comment by colinegin** [comment]
Hello @matks,

To be honest, this is a reallyyyy weird behaviour, I don't know why some modules are installed when clicking on it, while other modules block just bring you to the Module Catalog page.

What I know is that this list of modules on the dashboard (randomly displayed 2 by 2) are brought by the Gamification module which is installed by default on a PrestaShop store. 

IMO, if we were able to change this behaviour, the easiest would be to have a single behaviour for every module : when clicking on the module block, the user is brought to the Module Catalog page with a search filter on the module's name. This gives the user the opportunity to "read more" information about the module and "Install" the module in just one click. 
![image](https://user-images.githubusercontent.com/35263827/69350960-ce01f680-0c7a-11ea-979e-60f28e264249.png)

@matks do you think this behaviour could be handled by the gamification module ?

Thanks !

**Comment by khouloudbelguith** [comment]
Same issue with clicking on this link: `Link to your Google Analytics account` => redirection to the Module Manager page, The ps_googleanalytics is not installed.
https://drive.google.com/file/d/1NIwqoNSuc4kpWCumypgrJRIJ6X5HFBKO/view

Thanks!

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I think the bug doesn't exist anymore in `develop` branch.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

It seems those advertisement are not displayed any more :tada: 
So we have no issue :wink: 

![image](https://user-images.githubusercontent.com/23308427/154554578-7f9b67fe-b525-405f-a127-73514491fe5d.png)

Closing the issue!
Thanks.
