### ISSUE TITLE
Ios

### ISSUE THREAD

**Issue by joesibarani** [PrestaShop/PrestaShop#16464]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @joesibarani,

Thanks to add a clear description & the exact steps to reproduce the issue.

**Comment by khouloudbelguith** [comment]
Hi @joesibarani,

Your issue is incomplete, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
