### ISSUE TITLE
Bad shipping costs when $currency_special is used

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#16476]
**Describe the bug**
When you want to validate an order with a currency other than that of the current context, for example when the payment method supports only one currency, you can force the currency identifier into the variable $currency_special, which allows you to calculate each element on the basis of this new currency.
The calculation of the products is done without any problems, but for the shipping costs it does not work at all and gives the amount of the first currency as a value, which can either offer a price of shipping costs too low or too high.

For example, $22 becomes 22€, which is not really the same thing.

The function $cart->getOrderTotal(true, Cart::ONLY_SHIPPING) returns exactly the same problem and gives the amount of the wrong currency as if a cache does not allow to take into account the new currency associated with the basket.

**To Reproduce**
I don't really have a method to reproduce the problem since it is linked to a payment module that only accepts one currency.
Personally I use it on the following hook:
- hookDisplayPayment()
- hookPaymentOptions()

when choosing the payment and validating the payment.

**Screenshots**
![bug panier changement devise](https://user-images.githubusercontent.com/595633/69242117-75f6c180-0ba0-11ea-91af-cbf5120b0542.png)

**Additional information**
PrestaShop version: All
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jeckyl,

Paypal module is it a good module to reproduce the issue?
With Paypal, we can select only one currency
![image](https://user-images.githubusercontent.com/16067358/69244302-033c1500-0ba5-11ea-8611-8336d51f8146.png)

Thanks!

**Comment by jeckyl** [comment]
> Paypal module is it a good module to reproduce the issue?

And were you able to reproduce this problem?

**Comment by Eolia** [comment]
Add the id_curency in the cache_id of getPackageShippingCost() function and it's done ;) 
`$cache_id = 'getPackageShippingCost_'.(int)$this->id.'_'.(int)$address_id.'_'.(int)$id_carrier.'_'.(int)$use_tax.'_'.(int)$default_country->id.'_'.(int)$id_zone.'_'.(int)$this->id_currency;`

**Comment by khouloudbelguith** [comment]
@jeckyl, in my case.
I tried to enable the PayPal module for the $ currency.
![image](https://user-images.githubusercontent.com/16067358/69249546-55356880-0bae-11ea-9f88-d8b9462ef768.png)

When I try to create a new order with the € currency, in the last step"Pay with an obligation to pay"
=> error => Transaction refused because of an invalid argument  => not  reproduced.
But, I select $ => ok.

Thanks!

**Comment by jeckyl** [comment]
@khouloudbelguith it seems that the module refuses any payment when the front office currency does not match the currency selected in the preferences. It's convenient, it avoids any worries. However, you will have to explain to me why this module uses radio buttons more than checkboxes?

@Eolia Thanks to you, but I just tested it and the currency always stays the same when I test $cart->getOrderTotal(true, Cart::ONLY_SHIPPING) but maybe it fixes for the validateOrder(), I'll check this point now.

**Comment by khouloudbelguith** [comment]
@jeckyl, 
>However, you will have to explain to me why this module uses radio buttons more than checkboxes?

Paypal module is not provided by PrestaShop, you can contact the module author about this in our add-ons market place: https://addons.prestashop.com/en/contact-us?id_product=1748

Thanks!

**Comment by jeckyl** [comment]
@Eolia I just finished my test and it doesn't seem to correct the validation of the payment and shipping costs which is always the same.

**Comment by jeckyl** [comment]
@khouloudbelguith I will focus on my developments and not deal with the inconsistencies of others.

The fact is that the operation of PrestaShop is in error and that it must be corrected.

**Comment by khouloudbelguith** [comment]
@jeckyl, Could you please provide me a demo module to test it & reproduce the issue.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by jeckyl** [comment]
@Eolia I don't know if I've already said it, but the result of $params['cart']->getOrderTotal(true, Cart::BOTH); with the new currency makes the same calculation error on shipping costs.

**Comment by jeckyl** [comment]
@khouloudbelguith I would have to develop a module for you just to test it, which is very time-consuming. I use 2 of my payment modules to test several scenarios, which is not easy because this bug is so huge.
I understand why it was never reported, and that all other payment solutions have preferred to refuse payments that are not in the said currency, which is a pity.

**Comment by khouloudbelguith** [comment]
@jeckyl, thanks a lot!
Waiting for your feedback.

**Comment by Eolia** [comment]
In my paypal version i have added a default currency for the module if the customer's currency not allowed

		// Eolia add to force currency if current currency is not accepted by Paypal
		// See https://developer.paypal.com/docs/classic/api/currency_codes/
		$paypal_currencies = array('AUD', 'BRL', 'CAD', 'CZK', 'DKK', 'EUR', 'HKD', 'HUF', 'ILS', 'JPY', 'MYR', 'MXN', 'NOK', 'NZD', 'PHP', 'PLN', 'GFP', 'RUB', 'SGD', 'SEK', 'CHF', 'TWD', 'THB', 'TRY', 'USD');
		$currency_module = $this->getCurrency((int)$this->context->cart->id_currency);
		if(!in_array($currency_module->iso_code, $paypal_currencies)) {
			$default_currency = Configuration::get('PAYPAL_DEFAULT_CURRENCY');
			if($default_currency)
				$this->context->cart->id_currency = Currency::getIdByIsoCode(Configuration::get('PAYPAL_DEFAULT_CURRENCY'));
			else
				$this->_errors[] = $this->l('Currency not accepted by Paypal');
		}
		// End of Eolia add

**Comment by jeckyl** [comment]
I try, but it never changes anything, no matter how hard the currency is forced, it always gives the wrong result

> $old_currency = (int)$params['cart']->id_currency;
>                 $currency_payment = new Currency(Currency::getIdByIsoCode('EUR'));
>                 $this->context->currency = (int)$currency_payment;
>                 $this->context->cart->id_currency = Currency::getIdByIsoCode('EUR');
>                 $params['cart']->id_currency = $this->context->cart->id_currency;
>                 $montant = $params['cart']->getOrderTotal(true, Cart::BOTH);
>                 $this->context->currency = new Currency($old_currency);
> 

The final amount is false.

Cart in USD
![Capture d'écran 2019-11-20 18 35 41](https://user-images.githubusercontent.com/595633/69262973-b0725580-0bc4-11ea-9000-e090b25fbc18.jpg)

Cart in EUR
![Capture d'écran 2019-11-20 18 35 53](https://user-images.githubusercontent.com/595633/69263040-cd0e8d80-0bc4-11ea-85d5-4876fec4b082.jpg)

getOrderTotal(true, Cart::BOTH) in EUR
![Capture d'écran 2019-11-20 18 36 10](https://user-images.githubusercontent.com/595633/69263072-e1eb2100-0bc4-11ea-8c3f-ec27585105b7.jpg)

getOrderTotal(true, Cart::BOTH) in USD converted into EUR
![Capture d'écran 2019-11-20 18 36 28](https://user-images.githubusercontent.com/595633/69263093-ec0d1f80-0bc4-11ea-942f-8b6c769dca3c.jpg)

So, we can clearly see that the calculation is the price of the products in EUR plus the shipping costs in USD.

**Comment by jeckyl** [comment]
In 1.6 here is a solution:

 I found something, in validateOrder() the basket is instantiated again
![Capture d'écran 2019-11-20 19 52 18](https://user-images.githubusercontent.com/595633/69269536-86736000-0bd1-11ea-8752-c0454543c53b.jpg)

 So it is impossible to have the right id_currency in the Map.

It is then necessary to force the right id_currency in the context: 

![Capture d'écran 2019-11-20 19 54 10](https://user-images.githubusercontent.com/595633/69269590-a9057900-0bd1-11ea-891b-3e5358899eb9.jpg)

 This only occurs on validateOrder(), so we can assume that it will have no impact on the rest.

However, to correct the calculation of shipping costs by getOrderTotal(true, Cart::BOTH) I had to intervene on getTotalShippingCost() and force the flush on the function call: 

`$delivery_option_list = $this->getDeliveryOptionList($default_country, true);`

 the problem with something so touchy is that you'd have to take so many things back to check all the side effects, it's crazy. 


For the 1.7 it is even more complex to fix.

**Comment by khouloudbelguith** [comment]
Hi @jeckyl,

I'm still waiting for the demo module, thanks!
@Eolia, about this solution: https://github.com/PrestaShop/PrestaShop/issues/16476#issuecomment-556093873
What is the exact file did you edit?

Thanks!

**Comment by jeckyl** [comment]
sorry @khouloudbelguith but I'm not going to have time to do that.

**Comment by khouloudbelguith** [comment]
@jeckyl, I'm trying to reproduce the issue.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jeckyl,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
