### ISSUE TITLE
Log when creating order

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#16472]
**Describe the bug**
Every time user created order, prestashop logs warning.

**To Reproduce**
1. Create any order
2. Go to BO logs
3. You can see new log every time order is created "Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart"

**Additional information**
Log is created in FrontController.php init function:
                PrestaShopLogger::addLog('Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart', 1, null, 'Cart', (int) $this->context->cookie->id_cart, true);

**Comment by tdavidsonas88** [comment]
@margud will test it and let you know about fixing it

**Comment by khouloudbelguith** [comment]
Hi @margud,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9866
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #9866

**Comment by khouloudbelguith** [comment]
Hi @tdavidsonas88,

If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
