### ISSUE TITLE
I cannot change the position of pages - no 6 dots button

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#16487]
Hello,
I want to change the order of pages I have created some time ago. I just noticed I cannot change their order. I do not have these 6 dots that I have to press in order to change the order. Please, take a look at the video I have made showing the problem. What is weird, I am able to change orders of categories. It does not matter if I am in All shops mode or select any shop. Is there any way to fix it?

Video: https://drive.google.com/file/d/1_NSickpjDzCWa-VpxaDWkHCv5v2j95Jy/view

I am using PS 1.7.6.1
Server information Linux #1 SMP Tue Jul 23 08:31:06 EDT 2019 x86_64
Server software version: Apache/2.4.6 () mod_fcgid/2.3.9 Phusion_Passenger/5.3.7 
PHP version: 7.2.24 
MySQL version: 10.1.41-MariaDB-cll-lve

**Comment by khouloudbelguith** [comment]
Hi @banan44,

In your case, you are sorting by ID & not by position
![image](https://user-images.githubusercontent.com/16067358/69320166-ebb26a00-0c40-11ea-92c2-8ff2260a28f5.png)
You need just to sort by position
![image](https://user-images.githubusercontent.com/16067358/69320222-0a186580-0c41-11ea-8514-ea6dc65c98b5.png)
https://drive.google.com/file/d/1abjyCc_sWwuTXOO_ZInCf8jgNO94MgMS/view
I close the issue, feel free to open a new one when needed.

Thanks!
