### ISSUE TITLE
Combination EAN is ignored

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16497]
**To Reproduce**
1. Make a product with attributes. Assign some EAN.
2. Make some attributes. Assign different EANs to them.
3. Go to FO, only the EAN of the base product is visible.

$product.reference_to_display - changing as it should.
$product.ean13 - not changing.

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1Kz51qLQ03CqMtTB_IpXnUZOy4rBN8JWG/view
Thanks to check & feedback.
