### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#16508]
Every time I click on the logo in the frontend I get error www.castellon.plantoflife.com redirected you too many times.

**Comment by khouloudbelguith** [comment]
Hi @edensh89,

No, I did not manage to reproduce the issue with your shop.
It is ok.
I attached a screen record
https://drive.google.com/file/d/1_x7PM4dmGRhrgjxN4C-_2D61ksx5cOri/view

Thanks to check & feedback.
