### ISSUE TITLE
Add a check for minimum PHP memory on install

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#16507]
The [System requirements documentation](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/) states that the minimum recommended memory for PHP should be set to 256Mb. To my understanding, this is not enforced by the installer, putting the install process at risk of crashing.

A check on this requirement should be added to the install process.

**Comment by aecarlosae** [comment]
Hello @eternoendless, the System requirements documentation says **that is a recommendation per script**:

> **Server RAM:** The more the merrier. **We recommend** setting the memory allocation per script (memory_limit) to a minimum of 256M.

**Comment by PierreRambaud** [comment]
@eternoendless only available in HTTP context:
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/controllers/http/process.php#L300

need to be refactor and placed in ConfigurationTest.php instead
