### ISSUE TITLE
BO - can't enable/disable Newsletter option & Enabled option  when the field "Partner offers" is required

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16509]
**Describe the bug**
In the BO => Customers page => we can't enable/disable Newsletter option & Enabled option  when the field "Partner offers" is required
![image](https://user-images.githubusercontent.com/16067358/69433369-c9e9dd80-0d3b-11ea-97c6-65504e72a3dc.png)

**To Reproduce**

1. Go to BO => Customers => Click on Set required fields for this section
2. Check the "Partner offers" option
3. Save
4. Create a new customer from BO with enabling Partner offers => the customer is successfully saved
5. In the Customers list page, try to disable this customer or try to enable the Newsletter option
6. see the error

It is ok with ps1.7.5.2.
https://drive.google.com/file/d/1huf8kkW0-q8lr-JXR1mJOqt0VPNXHAMp/view
**Screenshots**
https://drive.google.com/file/d/1mXJIaUM45ce8y4ugDsdrXPuu_upecjEc/view

**Additional information**
PrestaShop version: 1.7.6.1, 1.7.6.2build1, develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0
https://drive.google.com/file/d/1naq1sws0f1cQZum0FiGHkFwp0ldWwQLC/view

**Comment by colinegin** [comment]
After discuting with @Robin-Fischer-PS we have decided to rollback the new behaviour that has been introduced in 1760 (PR #13887) to enable merchants to disable partners offers in the BO even though this is a required field.

**Comment by Progi1984** [comment]
Merged in #16648

**Comment by CatchMeZZo** [comment]
When will the fix be available? It takes to long time for this kind of bug...
