### ISSUE TITLE
Add Khmer as a new supported language

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16502]
**Is your feature request related to a problem?**
It is not a bug, but a default parameter to update.

**Describe the solution you'd like**
For the 1.7.7 version, following recent activity on Crowdin, it would be nice to add Khmer (`km-KH`) as a new supported language in PrestaShop.

**Why?**
Some languages are available in Crowdin for translation but not available in PrestaShop because of a low completion level on Crowdin. But when translators are very active and/or showed interest in an unavailable language, it could be nice to add it to the software so that they can see the results of their Crowdin translations quickly in their own shop, and therefore continue translation work.

**How?**
Here is the process I know: to activate a language and have it available in the language drop-down, you need to add it to files _[all_languages.json](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json)_ and _[app/Resources/legacy-to-standard-locales.json](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/legacy-to-standard-locales.json)_.

UPDATE: the [TranslationFiles repository](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/available_languages.json) is up-to-date!

Once the language is officially available (after the release of the version adding it), I will have to update the Locale table in Sandrine.

**Comment by LouiseBonnard** [comment]
Here is the main information about it:

Khmer ( ភាសាខ្មែរ )
km-KH (km being the language code for Khmer and KH the country code for Cambodia)

**Comment by Progi1984** [comment]
Merged with #16690
