### ISSUE TITLE
Add to cart doesn't work

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#16519]
Add to cart button doesn't work.
Open https://www.castellon.plantoflife.com/ scroll down and click on Add to cart
Get an error - "Error adding. Please go to product detail page and try again".
After trying to add to cart click on something/ refresh the page cause this error - ERR_TOO_MANY_REDIRECTS

PrestaShop version: 1.7.3.0
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @edensh89,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log

Does this issue occur before upgrading the ps_shoppingcart module to 2.0.3?
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by edensh89** [comment]
Yes it was reproduce before upgrade ps_shoppingcart.
I don't see errors when debug mode is on.
This issue reproduce every time after click on add to cart and refresh the page.

I see these errors in the php error log:
[25-Nov-2019 09:25:14 Europe/Madrid] PHP Notice:  Undefined index: search_string in /plantoflife.com/castellon/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 464

[25-Nov-2019 09:25:14 Europe/Madrid] PHP Notice:  Trying to get property of non-object in plantoflife.com/castellon/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 464

**Comment by khouloudbelguith** [comment]
@edensh89, issue fixed?

Thanks!

**Comment by edensh89** [comment]
No, I will try to reinstall and will see if it works.
