### ISSUE TITLE
when change any thing in admin dashboard and click save redirect to login page 

### ISSUE THREAD

**Issue by osamachihadeh** [PrestaShop/PrestaShop#16516]
Hello
i can not do any edit in website, E.x. when i change language and save page transfer me to login page without save any thing. Then I try to add new supplier when click save transfer me to login page without save agin .
 any solution

**Comment by khouloudbelguith** [comment]
Hi @osamachihadeh,

Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
`if ($this->context->cookie->last_activity + 900 < time()) {`

By this:

`if ($this->context->cookie->last_activity + 3600 < time()) {`

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @osamachihadeh,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
