### ISSUE TITLE
Product title in uppercase

### ISSUE THREAD

**Issue by ChoshimWy** [PrestaShop/PrestaShop#16513]
I want to display the product name on the first page but not in all uppercase. Can I change it directly in the background template? If not, can I tell you the specific change method，Thank you!

**Comment by khouloudbelguith** [comment]
Hi @WeiRuJian,

You need just to replace this:
```
.h1, .h2, .h3 {
    text-transform: uppercase;
    color: #232323
}
```
by this
```
.h1, .h2, .h3 {
    color: #232323
}
```
in the file /Project_Folder/themes/your_theme/assests/css/theme.css line 6399 after reformating code.

![image](https://user-images.githubusercontent.com/16067358/69522458-b61fc080-0f61-11ea-8fd9-f2e0a3b1733d.png)
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ChoshimWy** [comment]
I modified it in your way but it didn't work.

**Comment by khouloudbelguith** [comment]
Hi @WeiRuJian, 

You need to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks!

**Comment by ChoshimWy** [comment]
> Hi @WeiRuJian,
> 
> You need to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
> Thanks!

Thanks
I closed the cache, cleared the browser data and re entered the website, but it still hasn't changed。
I don't know what the problem is

**Comment by khouloudbelguith** [comment]
@WeiRuJian, if you use the dev-tools, inspect the code "product title", & disable the "`text-transform: uppercase;`" it will be ok, you need just to comment this line in your file.

![image](https://user-images.githubusercontent.com/16067358/69853810-17a89d80-1288-11ea-9512-4fec14bd2619.png)

![image](https://user-images.githubusercontent.com/16067358/69853885-2ee78b00-1288-11ea-889f-1165329e9492.png)

Thanks!

**Comment by ChoshimWy** [comment]
> @WeiRuJian, if you use the dev-tools, inspect the code "product title", & disable the "`text-transform: uppercase;`" it will be ok, you need just to comment this line in your file.
> 
> ![image](https://user-images.githubusercontent.com/16067358/69853810-17a89d80-1288-11ea-9512-4fec14bd2619.png)
> 
> ![image](https://user-images.githubusercontent.com/16067358/69853885-2ee78b00-1288-11ea-889f-1165329e9492.png)
> 
> Thanks!

The product details page is shown correctly, while the product display page is shown in capitals. Maybe there is something wrong with my description, thank you!

**Comment by ChoshimWy** [comment]
> @WeiRuJian, if you use the dev-tools, inspect the code "product title", & disable the "`text-transform: uppercase;`" it will be ok, you need just to comment this line in your file.
> 
> ![image](https://user-images.githubusercontent.com/16067358/69853810-17a89d80-1288-11ea-9512-4fec14bd2619.png)
> 
> ![image](https://user-images.githubusercontent.com/16067358/69853885-2ee78b00-1288-11ea-889f-1165329e9492.png)
> 
> Thanks!
Can you visit my website to have a look？ Thanks！
https://www.boromikey.com

**Comment by khouloudbelguith** [comment]
@WeiRuJian, you need to edit this file
![image](https://user-images.githubusercontent.com/16067358/69855736-7243f880-128c-11ea-8a3b-beb48c144393.png)
And this line: `text-transform: none;`
![image](https://user-images.githubusercontent.com/16067358/69855784-8982e600-128c-11ea-8bcd-c090cd19cf80.png)

Thanks!

**Comment by ChoshimWy** [comment]
> @WeiRuJian, you need to edit this file
> ![image](https://user-images.githubusercontent.com/16067358/69855736-7243f880-128c-11ea-8a3b-beb48c144393.png)
> And this line: `text-transform: none;`
> ![image](https://user-images.githubusercontent.com/16067358/69855784-8982e600-128c-11ea-8bcd-c090cd19cf80.png)
> 
> Thanks!

Ok, I'll try, thank you very much!
