### ISSUE TITLE
[ORDER PAGE] New hooks

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#16523]
**New hooks mapping**
We will add new hooks on the top with the other button. This hooks will force the module to have the same design as the other one.

![68310376-30ba9600-00b0-11ea-86f3-52e5dffa2435](https://user-images.githubusercontent.com/43613217/69533736-ac558780-0f78-11ea-923f-7c7578e124bc.jpg)

**Known limitation**
Mapping requires that "when there is not enough space for all buttons to be rendered, a dropdown list appears instead and buttons are put inside" => this is a responsive feature, need someone experienced in front (not @matks 😛 )

**Workaround for limitation instead:**

if 1 or 2 buttons are added (like module test) they are displayed
if more than 2 buttons are added, it displays 1st button THEN next buttons are in dropdown (see screenshot below)
=> these 2 usecases can be seen with the test module, when you refresh there is a 50% luck you have usecase 1 or 2

**Comment by MatShir** [comment]
#16144

**Comment by matks** [comment]
@MatShir it's "Order page", not "Create order" 😉

**Comment by MatShir** [comment]
> @MatShir it's "Order page", not "Create order"

Indeed :roll_eyes:, thanks

**Comment by matks** [comment]
⚠️ Dont forget to register these new hooks in database and in the devdocs !
