### ISSUE TITLE
Installation error v1.7.6.1

### ISSUE THREAD

**Issue by augustu5** [PrestaShop/PrestaShop#16529]
**Describe the bug**
At the configuration step of installation process I'm getting an error: 
1: Unable to write into "pl-PL"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer")

**To Reproduce**
1. Initialize installation process 

**Screenshots**
![PHP PrestaShop Info](https://user-images.githubusercontent.com/12048630/69550971-382cdb00-0f9c-11ea-9742-baf11a9b8e49.png)

**Comment by khouloudbelguith** [comment]
Hi @krystian-3c,

The `memory_limit` must be to a minimum of 256M.
Thanks to increase it in the PHP's config, check & feedback.

PR: https://github.com/PrestaShop/PrestaShop/pull/16527

Thanks!

**Comment by augustu5** [comment]
Error persists after raising the memory limit. 
![PHP PrestaShop Info (1)](https://user-images.githubusercontent.com/12048630/69587689-97174200-0fe6-11ea-95c8-4ab0a36f4c3b.png)


If the error relates to directory in app/Resources/translations folder access permissions are not the problem.

**Comment by khouloudbelguith** [comment]
HI @krystian-3c,

In my case, I did not manage to reproduce the issue with PS1.7.6.1 with Poland's country & Polish language.
https://drive.google.com/file/d/1UpAfkwSfY55iGJtzS9hNk_fp7TARevXy/view

>If the error relates to directory in app/Resources/translations folder access permissions are not the problem.

Thanks to check again your directory permission.
In the meantime, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by augustu5** [comment]
Same with PS1.7.6.2
There are no errors in apache error log.
It is not correlated with specific country/language.
Permissions seems ok.
It could have something to do with the fact that it is running on Ubuntu on Windows  - it is developer instance not a production one (https://www.microsoft.com/store/productId/9N9TNGVNDL3Q).

![install](https://user-images.githubusercontent.com/12048630/70861977-379db980-1f36-11ea-9f83-806b57f400aa.jpg)
![info](https://user-images.githubusercontent.com/12048630/70861978-3a98aa00-1f36-11ea-94df-a6a432f6e821.png)
![permission](https://user-images.githubusercontent.com/12048630/70861980-3c626d80-1f36-11ea-84f7-a6b508256715.png)

**Comment by khouloudbelguith** [comment]
@krystian-3c, did you use OS windows10? and you are using Ubuntu on Windows?

Thanks!

**Comment by augustu5** [comment]
yes

**Comment by khouloudbelguith** [comment]
@krystian-3c, did you use Ubuntu 16.04 to 18.04?

Thanks!

**Comment by augustu5** [comment]
Just like in link I provided above.  Ubuntu 18.04.2 LTS.

**Comment by khouloudbelguith** [comment]
@krystian-3c, thanks for your feedback.
I will try to prepare an environment similar to yours, check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @krystian-3c,

When using this environment: Windows 10 - Ubunutu 18.04TLS, did you find any problems during the Mysql installation?
In my case, the MySQL service cannot be started.

Thanks!

**Comment by augustu5** [comment]
I didn't come across any problem related with the fact that it is a virtualization. 
The problem was that i tried to install PS on mounted drive. 
/mnt/c/(...)
I guess the problem was related with windows file permissions rather then linuxes (file permissions looked good from linux perspective).
When I moved instance folder from /mnt to /var/www everything worked fine.

**Comment by khouloudbelguith** [comment]
@krystian-3c, Thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by augustu5** [comment]
The problem is related to mounted files permissions.
It's convenient to use mounted drives, so here is a solution:
https://www.turek.dev/post/fix-wsl-file-permissions/
Remember to restart (relogin) your Windows.
