### ISSUE TITLE
PayU transaction

### ISSUE THREAD

**Issue by MFdoom23** [PrestaShop/PrestaShop#16536]
I got problem with PayU transaction, message after check ouut purchase  [code=0], [message=Failed to connect to secure.payu.com port 443: Connection refused] any help?

**Comment by khouloudbelguith** [comment]
Hi @MFdoom23,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
