### ISSUE TITLE
No create order button in orders listing for SF pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16549]
## Describe the bug

I noticed an issue on migrated Orders listing (available at URL `/admin-dev/index.php/sell/orders/orders/`).

The "create an order" button is not there ... and actually the top item of each BO page is not there at all.
![Capture d’écran 2019-11-26 à 14 19 35](https://user-images.githubusercontent.com/3830050/69636854-cdd97080-1057-11ea-92b9-9c3822cb4c68.png)

This is actually because of PR https://github.com/PrestaShop/PrestaShop/pull/16090 who aimed to make "Edit an order" display as close as possible from original mock-up.

So this is the design, thanks to PR https://github.com/PrestaShop/PrestaShop/pull/16090
![Capture d’écran 2019-11-25 à 18 22 00](https://user-images.githubusercontent.com/3830050/69636786-ab475780-1057-11ea-87fa-4bc24b0346b7.png)

Without this PR, "Edit an order" migrated page looks like this:
![Capture d’écran 2019-11-25 à 18 21 52](https://user-images.githubusercontent.com/3830050/69636793-aedade80-1057-11ea-85bd-554da34f8c45.png)

However an unexpected side-effect of PR is that it modifies also "Create an order" and "Orders listing" migrated pages.

## Possible solutions

1) Put the banner back, so we get this display on Order page:
![Capture d’écran 2019-11-25 à 18 21 52](https://user-images.githubusercontent.com/3830050/69636793-aedade80-1057-11ea-85bd-554da34f8c45.png)
This is the most simple because this way, the page behaves like all other BO pages.

2) Hack further into the legacy layout to have listing display correct, but edit order identical to mock-up. However this might break other things.

**Comment by matks** [comment]
ping @TristanLDD @MatShir

**Comment by MatShir** [comment]
@matks as discussed, let's keep the original header and just try to edit the content the title as on the design.
