### ISSUE TITLE
Adding a product to cart takes long time compared to other stores

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16554]
**Describe the bug**
It takes long time to add anything to cart. It's almost 2x slower than PS 1.6 or other stores. 3x slower than Shopify. (Rough measurement from clicking add to cart button, to popup shown.)

**Prestashop 1.7 - 2,3 seconds to 2,6 seconds**

**Other platforms**
Prestashop 1.6 - 1,3 seconds (on the same server)
shopify - 0,7 seconds

**Czech well known ecommerce stores**
alza.cz - 1,1 seconds
czc.cz - 1,0 seconds
megapixel.cz - 1,4 seconds
lekarna.cz - 0,9 seconds

**Additional information**
![config](https://user-images.githubusercontent.com/6097524/69652221-9a0b4480-1071-11ea-99b6-8ae8c4c21978.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I tried with PS1.7.6.1 & PS1.7.5.2
PS1.7.6.1: time from clicking add to cart button, to popup shown = 462.27 ms
PS1.7.5.2: time from clicking add to cart button, to popup shown = 528.49 ms

I tried with an incognito browser.
I attached a screen record
https://drive.google.com/file/d/1LDbSIMCX_hB0QccewS3fJdepv_OG16jg/view
Thanks to check & feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith 

It takes 1802 ms in my case. Can you point me to a direction, how we can find out where is a problem? Otherwise, the website runs OK.

![Výstřižek](https://user-images.githubusercontent.com/6097524/69657906-7baa4680-107b-11ea-9cf6-399b60d59324.JPG)

From what I see, cart is slowing it down a lot. It almost doubles the amount of queries to the database. 

**Page load in anonymous window and cleared cookie**
![clearcart](https://user-images.githubusercontent.com/6097524/69658340-49e5af80-107c-11ea-95c6-e18676e66449.JPG)


**Page load with an customer logged in and 7 items in cart**
![withcart](https://user-images.githubusercontent.com/6097524/69658333-46522880-107c-11ea-9e42-a00834b2c8ed.JPG)

**Comment by khouloudbelguith** [comment]
@Hlavtox, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version, clear cache, check & feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith Found out cart rules have huge impact on this.
![cartrule](https://user-images.githubusercontent.com/6097524/69755397-69520a80-1158-11ea-8b18-ab40d890b599.JPG)

Can you please try to record it with some cart rules made and activated? Like on my setup:
- XX % discount on all orders over XX amount, quantity 9999999, no code
- free gift on all orders over XX amount, quantity 9999999, no code
- a few vouchers like this (5 maybe) - with code, quantity 99999, will give XX % discount on the order

**Comment by khouloudbelguith** [comment]
@Hlavtox, so it is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/16568? is it?
Can we close this issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
