### ISSUE TITLE
Export language seems to be KO in 176

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16555]
**Describe the bug**
In PS 1761 and 1762 build 2, the export of language seems to be KO, the zip file created does not contains any translations.

**To Reproduce**
1. Go to International > Translations > Export a language
2. Export a language
3. ZIP file is created, with only one xlf file in it (without any translation in it). In 1.7.5.2, there is around 10 files (with translations).
See ZIP files.

**Files**

[classic.ru-RU 175.zip](https://github.com/PrestaShop/PrestaShop/files/3893168/classic.ru-RU.175.zip)

[classic.ru-RU 1762.zip](https://github.com/PrestaShop/PrestaShop/files/3893169/classic.ru-RU.1762.zip)

**Additional information**
PrestaShop version: 1.7.6.1 - 1.7.6.2 build 2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I tried with PS1.7.6.1
1. Exporting the language before the translation, I have this zip file
[classic.pl-PL.zip](https://github.com/PrestaShop/PrestaShop/files/3895991/classic.pl-PL.zip)

2. After translating some expression of the classic theme, I have this zip file:
[classic.pl-PL (1).zip](https://github.com/PrestaShop/PrestaShop/files/3895999/classic.pl-PL.1.zip)

Same with PS1.7.6.0:
1. Exporting the language before the translation, 
[classic.en-US (1).zip](https://github.com/PrestaShop/PrestaShop/files/3896007/classic.en-US.1.zip)
2. Exporting the language after translating some expression of the classic theme
[classic.en-US (2).zip](https://github.com/PrestaShop/PrestaShop/files/3896009/classic.en-US.2.zip)

With PS1.7.5.2, Exporting the language before the translation
[classic.en-US.zip](https://github.com/PrestaShop/PrestaShop/files/3896034/classic.en-US.zip)

Ping @PrestaShop/prestashop-core-developers what do you think, is it a new behavior or a regression?

Thanks!

**Comment by colinegin** [comment]
Any news from this issue ? Is it a regression ?

**Comment by PierreRambaud** [comment]
@khouloudbelguith COuld you tell us if it's a regression from 1.7.5.2 :thinking: 
If translations are missing, it's a bug no? :thinking:

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

Yes, I tried with PS1.7.5.2=> we have a folder of files generated.
[classic.en-US.zip](https://github.com/PrestaShop/PrestaShop/files/4035843/classic.en-US.zip)
It is not the same behavior as PS1.7.6.2, we have only one file exported
[classic.en-US (1).zip](https://github.com/PrestaShop/PrestaShop/files/4035875/classic.en-US.1.zip)
If we change the translations of the theme => the file is well generated the next time.
So all files are generated after translating the theme (translations are missing: it is not the case).
So, we need to check if it is a wanted behavior in PS1.7.6 or a regression.

Thanks!

**Comment by PierreRambaud** [comment]
@khouloudbelguith I don't think, do you have any idea @matks ?

**Comment by thbl** [comment]
+1 @khouloudbelguith any new on this ?

**Comment by khouloudbelguith** [comment]
@PrestaShop/prestashop-core-developers friendly reminder :)

**Comment by thbl** [comment]
@pierreavizou  @matks did you look at this ?

**Comment by eternoendless** [comment]
I have verified the problem.

**Comment by thbl** [comment]
@colinegin  @eternoendless why is this removed from the 1.7.6.5 milestone ?

**Comment by eternoendless** [comment]
@thbl Unfortunately this is too broken to be fixed in the 1.7.6.x branch. #18293 fixes  the export but produces other regressions in the translation interface.

A full refactoring is in the making for 1.7.7.0. It will simplify the feature architecture, put into practice some design decisions that have been made by the product team (eg. "what should be included in the theme translations export"), and fix this problem. If you really need to export a theme, apply my PR, export, and rollback the changes.

**Comment by eternoendless** [comment]
This feature is being retro-specified before refactoring: https://github.com/PrestaShop/prestashop-specs/pull/120

**Comment by colinegin** [comment]
We need to :
- validate specs written by @eternoendless --> @LouiseBonnard 
- check #19242 issue which should fix this issue too

**Comment by hibatallahAouadni** [comment]
This issue still persist with PS1.7.7.3_build1

**Comment by matks** [comment]
Yes, it has been postponed to 1.7.8 https://github.com/PrestaShop/PrestaShop/issues/23766

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/issues/23766 (PR  https://github.com/PrestaShop/PrestaShop/pull/24049) if I am not wrong

**Comment by marionf** [comment]
@khouloudbelguith Can you confirm if this issue is well fixed by https://github.com/PrestaShop/PrestaShop/pull/24049 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, this issue is fixed with https://github.com/PrestaShop/PrestaShop/pull/24049.
Now we can export the classic theme using these option
![image](https://user-images.githubusercontent.com/16067358/115888171-e9b29300-a452-11eb-82f1-e987b38de9c6.png)
Now, we will have all xlf files
[translations_export_en-US (1).zip](https://github.com/PrestaShop/PrestaShop/files/6366084/translations_export_en-US.1.zip)

I will close the issue as it is fixed.

Thank you!
