### ISSUE TITLE
Override SearchProvider.php

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#16556]
Maybe I am wrong but I am trying to overrid /ps_facetedsearch/src/Product/SearchProvider.php

I chance Private fonction to Protected and here is what I did to remove $sortNameAsc and  $sortNameDesc in the Product List Filters

Create : override/modules/ps_facetedsearch/src/Product/SearchProvider.php

```
if (!defined('_PS_VERSION_'))
	exit;
class SearchProviderOverride extends SearchProvider
{
	    protected function getAvailableSortOrders()
    {
        $sortPosAsc = new SortOrder('product', 'position', 'asc');
        $sortPriceAsc = new SortOrder('product', 'price', 'asc');
        $sortPriceDesc = new SortOrder('product', 'price', 'desc');
        $translator = $this->module->getTranslator();
        return [
            $sortPosAsc->setLabel(
                $translator->trans('Relevance', [], 'Modules.Facetedsearch.Shop')
            ),
            $sortPriceAsc->setLabel(
                $translator->trans('Price, low to high', [], 'Shop.Theme.Catalog')
            ),
            $sortPriceDesc->setLabel(
                $translator->trans('Price, high to low', [], 'Shop.Theme.Catalog')
            ),
        ];
    }
}
```

**Comment by khouloudbelguith** [comment]
Hi @Dupflo,

Usually, if we have used `private` methods it is because we consider this to be an internal behavior and that overriding this part alone is not recommended, but we can check.

Can you also tell us what you are trying to achieve? Overrides might not be a good way to do it, especially because it makes your shop very specific and might create issues when upgrading the shop or adding new modules.

Thanks!

**Comment by Dupflo** [comment]
Hi @khouloudbelguith 

I want remove this two items
![image](https://user-images.githubusercontent.com/39828779/69710128-1a2bbb80-10ff-11ea-9c5c-9c1d3fde4a60.png)

**Comment by khouloudbelguith** [comment]
@Dupflo, but the "Sort by" filter is displayed by default, not when `ps_facetedesearch` is installed.
If you try to uninstall the `ps_facetedsearch` module or disable it => the "Sort by" filter is still displayed.
I attached a screen record
https://drive.google.com/file/d/1kR_gt3rTOS5mDVsBFc0Jhhpzi0eQZ7tg/view
Thanks to check & feedback.

**Comment by Dupflo** [comment]
True

**Comment by khouloudbelguith** [comment]
@Dupflo, so you don't need to override this function, is it?

Thanks!

**Comment by Dupflo** [comment]
I remove directly from the .php file and it works

**Comment by khouloudbelguith** [comment]
@Dupflo, thanks for your feedback.
Ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think?
Can we change  Private function to Protected: https://github.com/PrestaShop/ps_facetedsearch/blob/master/src/Product/SearchProvider.php#L75?

Thanks!

**Comment by PierreRambaud** [comment]
I uninstall ps_facetedsearch and to remove elements in the drop down you need to change this class:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Product/Search/SortOrdersCollection.php#L51

@matks any idea about how to change this class properly?

**Comment by matks** [comment]
Looks like injection is done at the very high level `ProductListingFrontController::getProductSearchVariables()`

`$provider->runQuery` uses `$this->sortOrderFactory->getDefaultSortOrders()` which instantiates a new `SortOrdersCollection` class

So it seems there is no "proper" way to customize this behavior 😢

**Comment by Dupflo** [comment]
Thanks for you help guys

**Comment by khouloudbelguith** [comment]
@Dupflo, so, can we close this issue?

Thanks!

**Comment by Dupflo** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@Dupflo, thanks!
Feel free to open a new one when needed.

Thanks!

**Comment by Triloworld** [comment]
Yes. This is still valid 2023 for 7.x.x.x and 8.0.
After disabling module `ps_facetedsearch` there isn't proper example to override sort order.
Conclusion same as : https://github.com/PrestaShop/PrestaShop/issues/16556#issuecomment-559509797
Pleas @khouloudbelguith re-open it as there is now locked `src` and this should be in hook / override example as part of simple change in shop

I suggest add Hook and manage it in that way - from adding by external module to order and remove when needed as simple UI action

**Comment by piotrmerton** [comment]
Yes, the Hook to manage sort orders is very much needed.
