### ISSUE TITLE
Invalid category vars at line 374 in file classes/Link.php

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#16562]
I have multisotre and I uploaded new theme the second shop I'm creating.
Before uploading the theme everything works good and now nothing works.

This is urgent.
Please check https://www.plantoflife.com/

This is the error I get:
Invalid category vars
at line 374 in file classes/Link.php

369.             if (is_array($category) && isset($category['id_category'])) {
370.                 $category = new Category($category, $idLang);
371.             } elseif ((int) $category) {
372.                 $category = new Category((int) $category, $idLang);
373.             } else {
374.                throw new PrestaShopException('Invalid category vars');
375.             }
376.         }
377.         return $category;
378.     }
379.

**Comment by khouloudbelguith** [comment]
Hi @edensh89,

The Schema of URLs is updated in your case
By default, we have like this:
![image](https://user-images.githubusercontent.com/16067358/69727495-f37f7c00-1122-11ea-82de-58e168b09c0b.png)
In your case, you have like this
![image](https://user-images.githubusercontent.com/16067358/69727595-2b86bf00-1123-11ea-8743-c90ae799ed01.png)
Is it?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @edensh89,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Develoo** [comment]
Bonjour,
J'ai le méme erreur, c'est quoi la solution.
Merci pour votre réponse
Cordialement
