### ISSUE TITLE
"Orders > Products" : Use UI Kit for Input Number 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#16567]
**Is your feature request related to a problem? Please describe.**
Create a component Input Number in UI Kit

**Comment by prestascott** [comment]
@PrestaShop/prestashop-product-team

**Comment by prestascott** [comment]
Epic: #16587

You can find the redesign of the input number in UI Kit here: [Link to InVision prototype](https://invis.io/S9UXGJA73B5)

**Comment by colinegin** [comment]
Should it be part of the EPIC then ?

**Comment by prestascott** [comment]
Yes, it's already part of the epic and has its own issue : #16599

**Comment by MatShir** [comment]
@prestascott It seems the issue is done by https://github.com/PrestaShop/PrestaShop/issues/16599, can we close this issue ?

**Comment by prestascott** [comment]
@MatShir Yes, issue is done by #16599 so we can close this issue.
