### ISSUE TITLE
Error message when change text in cms page for privacy policies

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#16561]
Hi, 

i want to change text in cms page for "privacy policies" but text could not be saved and I get the message

![image](https://user-images.githubusercontent.com/44971218/69722710-1193af00-1118-11ea-8014-b318204a1ea1.png)

and the new text is not saved and the old text is still there. In html editor looks everthing fine after adding the text but it want not save it. 

Are there a limit of signs? If yes in which file can I change it? 

I would be very happy for any help

PS 1.7.5.1

**Comment by didi-2018** [comment]
My text contains a java script code to disable Facebook Pixel 

hre Einwilligung jederzeit durch die Deaktivierung des Facebook-Pixel-Trackings widerrufen. Zu diesem Zweck k&ouml;nnen Sie durch Klick auf den nachstehenden Link ein Opt-Out-Cookie setzen, welches das Facebook Pixel-Tracking deaktiviert:<br />
<a href="javascript:void(0)" onclick="if (typeof fbpOptOut == 'function') { fbpOptOut(); } else { alert(atob('QUNIVFVORzogRmVobGVuZGVyIEZhY2Vib29rLVBpeGVsIE9wdE91dC1Db2RlIQ==')); }">Facebook-Pixel deaktivieren</a><br />

This is the reason why the text is not saved. 

I really need that function in cms page. Can you please help me????

**Comment by didi-2018** [comment]
My text contains a java script code to disable Facebook Pixel Cookie

`Ihre Einwilligung jederzeit durch die Deaktivierung des Facebook-Pixel-Trackings widerrufen. Zu diesem Zweck k&ouml;nnen Sie durch Klick auf den nachstehenden Link ein Opt-Out-Cookie setzen, welches das Facebook Pixel-Tracking deaktiviert:<br />
<a href="javascript:void(0)" onclick="if (typeof fbpOptOut == 'function') { fbpOptOut(); } else { alert(atob('QUNIVFVORzogRmVobGVuZGVyIEZhY2Vib29rLVBpeGVsIE9wdE91dC1Db2RlIQ==')); }">Facebook-Pixel deaktivieren</a><br />`

I really need this code in cms page. 

Can you please help me with that? 🙏🏻

**Comment by dlascelles** [comment]
I had the same issue recently. 

Go to **classes/CMS.php** and around line 66

**change this:** 'content' => array('type' => self::TYPE_HTML, 'lang' => true, 'validate' => 'isCleanHtml', 'size' => 3999999999999),

**to this:** 'content' => array('type' => self::TYPE_HTML, 'lang' => true, 'size' => 3999999999999),

in order to avoid validation.

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

In your case, this text is invalid.
That's why you have this error.
It is normal behavior.
I close the issue, feel free to open a new one when needed.

Thanks!
