### ISSUE TITLE
Error in the console when creating a supplier

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16569]
**Describe the bug**
When we try to create a supplier without description & we save => an error in the console is displayed.
There is no alert that it is required.

**To Reproduce**
1. Go to BO => Catalog => Suppliers page
2. Create a supplier without a description & save
3. See an error in the console "An invalid form control with name='supplier[description][1]' is not focusable."
![image](https://user-images.githubusercontent.com/16067358/69744608-c93cb700-1140-11ea-8f4e-1e9670653ab2.png)

PS1.7.6.1 => OK
**Screenshots**
https://drive.google.com/file/d/1f3r_xo_gSlT9q1i18RtLaOEgILLg0dnh/view

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed in #17180
