### ISSUE TITLE
Cart rules slow down the page - hundreds of duplicated queries

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16568]
**What is wrong**
Having cart rules active slow down the page incredibly and **triples the amount of queries** and **slows down the page by 50%**. **We need speed!**

I am having only 2 vouchers active.
https://drive.google.com/file/d/1MrE4w-KlFN-UOSlGWnovFhmxMrroDeWt/view?usp=sharing

A big part of this is the same query, which comes from **CartRule.php::checkValidity()** and is repeated 141 times:

```
SELECT SQL_NO_CACHE count(*)
FROM ps_orders o
LEFT JOIN ps_order_cart_rule od ON o.id_order = od.id_order
WHERE o.id_customer = 5
AND od.id_cart_rule = 48
AND 8 != o.current_state LIMIT 1
```

**Comparsion**
![RULES](https://user-images.githubusercontent.com/6097524/69763682-43376500-116e-11ea-9093-a18d14b936ae.png)

**Digged deeper**
Cart.php getDeliveryOptionList is called 30 times on CMS page and 60 times on cart page. >
Cart.php getDeliveryOption is called 18 times on CMS page and 36 times on cart page. >
Cart.php getTotalShippingCost is called 18 times on CMS page and 36 times on cart page. >
Fees.php processCalculation is called 7 times on CMS page and 13 times on cart page. >
**Why is cart presented so many times?** 1x In general purpose variables, 1x in shoppingcartmodule,
2x on cart page

**Voucher list**
![codes](https://user-images.githubusercontent.com/6097524/69739313-c8535780-1137-11ea-9053-58d9ccdb6534.JPG)

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

How many cart rules have you in your BO?
In the FO, are you navigating as a customer (you just registered) or as a visitor( not registered yet)?
Could you please try to enable profiling mode
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith I have profiling enabled all the time.

You can see the list of cart rules in the first post.
12 cart rules in total.
ID 47+48 are without code, for orders above XXX amount.
The rest are cart rules wtih a code.

**Scenario 1 - Both rules applied**
![1p](https://user-images.githubusercontent.com/6097524/69750001-ffcbff00-114b-11ea-86c4-e671349d0491.JPG)
![1c](https://user-images.githubusercontent.com/6097524/69750015-05c1e000-114c-11ea-9bb9-3da53c5bf067.JPG)

**Scenario 2 - 1 rule applied**
![2p](https://user-images.githubusercontent.com/6097524/69750021-0a869400-114c-11ea-9a13-9360be7c4f04.JPG)
![2c](https://user-images.githubusercontent.com/6097524/69750023-0a869400-114c-11ea-8af0-3f89a9d7823e.JPG)

**Scenario 3 - no rule applied**
![3p](https://user-images.githubusercontent.com/6097524/69750028-0eb2b180-114c-11ea-85c8-ff3167c59ad9.JPG)
![3c](https://user-images.githubusercontent.com/6097524/69750030-0eb2b180-114c-11ea-9824-21a67f95126f.JPG)

**Comment by Hlavtox** [comment]
@khouloudbelguith 

**Scenario 4 - all cart rules disabled**
400 ms faster load time and half the queries.
![nocartrule](https://user-images.githubusercontent.com/6097524/69755082-b97c9d00-1157-11ea-9899-215879211516.JPG)

**Comment by Hlavtox** [comment]
@khouloudbelguith I updated the Issue description, please, read it again and try to test.

**Comment by khouloudbelguith** [comment]
@Hlavtox, I added 204 cart rules using this script
```
<html><head><title>pUT DATA</title></head><body>
<?php

// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://prestashop.local/1761');
define('PS_WS_AUTH_KEY', 'DIHAUR5XYEEN8UFFRN7C4TJ3R2PDEQ9R');
require_once('PSWebServiceLibrary.php');
$i=4;
for ($i; $i <= 1000; $i++) {
$psXML = <<<XML
<prestashop>
<cart_rule>
  <id/>
  <date_from>2019-05-08 14:00:00</date_from>
  <date_to>2019-12-20 16:00:00</date_to>
  <quantity>1</quantity>
  <quantity_per_user>1</quantity_per_user>
  <reduction_percent>12</reduction_percent>
  <name>
  <language id ="1">"product_WS"</language></name>
  <active>1</active>
</cart_rule>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
$opt = array( 'resource' => 'cart_rules' );
$opt['postXml'] = $xml->asXML();
$xml = $webService->add( $opt );
}
?>
```

In the BO => Cart rule page, I have "Load Time" = 791 ms & just 55 queries.
In the FO => Cart page => I have "Load Time"= 163 ms & 189 queries.

In my case, this query

```
SELECT SQL_NO_CACHE count(*)
FROM ps_orders o
LEFT JOIN ps_order_cart_rule od ON o.id_order = od.id_order
WHERE o.id_customer = 5
AND od.id_cart_rule = 48
AND 8 != o.current_state LIMIT 1
```

Is called one time.

I attached a screen record
https://drive.google.com/file/d/1yNeJHlDPbY7uaW62ZGh-IR0_zVHo9ixQ/view
Thanks to check & feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith Can you try it with my exact database dump?

Just ensure that some languages with ID 1 and 2 exist.
And change ID of the gift product in cart rule 48 to something that exist.

I am sure you will experience the same performance drop.

Also, it is very different if you test it on localhost than on any normal hosting....

**Comment by khouloudbelguith** [comment]
@Hlavtox, data added
![image](https://user-images.githubusercontent.com/16067358/69882092-5746a800-12cf-11ea-9ccc-04a1454c544e.png)

In the BO => Cart rule page, I have:
1. Load time = 825 ms
2. Queries = 56

In the FO => Cart page => I have:
1. Load time = 172 ms
2. Queries = 177

This query

```
SELECT SQL_NO_CACHE COUNT(*) FROM `ps_orders` o
LEFT JOIN ps_order_cart_rule ocr ON (ocr.id_order = o.id_order)
WHERE o.id_customer = 0
AND ocr.id_cart_rule = 1 LIMIT 1

```
Is called two times only

I attached a screen record
https://drive.google.com/file/d/1jk6NGxli85aCKh6VEFOXLeWslzWd9pRz/view

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith I tried now and made this table. 

Something had to be slightly tweaked in 1.7.6.2. The query is now repeated 11 times. Before it was 141 times. And it only happens for a logged in customer.

Still, if we think about it. Cannot this be optimized somehow? **90 extra queries on every page with just 1 product in cart?**

![loadtime](https://user-images.githubusercontent.com/6097524/69887041-3f7a1e80-12e5-11ea-90ad-66617e46929f.JPG)

**Comment by khouloudbelguith** [comment]
**Case 1:**
- cart rule "Čistící pasta zdarma pro objednávky nad 3 000 Kč" active
- cart rule "Zákaznická sleva 30% pro objednávky nad 2 000 Kč" not active
- one product added to the cart + a gift

=>
- Load Time | 381 ms 
- Querying Time | 126 ms
- Queries | 251

**Case 2:**
- cart rule "Čistící pasta zdarma pro objednávky nad 3 000 Kč" active
- cart rule "Zákaznická sleva 30% pro objednávky nad 2 000 Kč" active
- one product added to the cart + a gift
=>
- Load Time | 387 ms
- Querying Time | 174 ms
- Queries | 264

**Case 3:**
- cart rule "Čistící pasta zdarma pro objednávky nad 3 000 Kč" active
- cart rule "Zákaznická sleva 30% pro objednávky nad 2 000 Kč" active
- three products added to the cart + a gift
=>
- Load Time | 337 ms
- Querying Time | 110 ms
- Queries | 254


In my case, with PS1.7.6.2, same cart rules as you, I don't have 90 extra queries on every page with just 1 product in cart
I attached a screen record
https://drive.google.com/file/d/13dklTBwDkXE3OcV0EA-SdSigyHulThxl/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
