### ISSUE TITLE
Catalog price rules condition groups are not sent in the save POST request

### ISSUE THREAD

**Issue by ravloony** [PrestaShop/PrestaShop#16572]
**Describe the bug**

When I edit a catalogue price rule in my shop, then click on "add a new condition group", then add a condition to the group (a category for example) and try to save the form, the form saves but the condition group I just added disappears. I tracked it down to this method: https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminSpecificPriceRuleController.php#L359

That regular expression never matches, because the POST request does not contain anything starting with `condition_group_`.

It seems the form does not generate the necessary inputs to save the added data.

**To Reproduce**
1. Go to 'Discounts > Catalogue Price rules'
2. Edit a price rule
3. Click on "Add a new condition group"
4. In the form that is now present, add a condition to the group. It doesn't matter which condition.
5. Save the form
6. The condition group and condition have disappeared.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @ravloony,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1A68d-bcUxbB7t-8yKEpXCWNdXZSKM8ZZ/view

Thanks to check & feedback.

**Comment by ravloony** [comment]
It seems to have been fixed by https://github.com/PrestaShop/PrestaShop/commit/352478c4de4803a6c034aaba3ae0e18c79131b6e#diff-9cf43e3cb58aa12f818237c17ebfc8ca

I downloaded https://raw.githubusercontent.com/PrestaShop/PrestaShop/352478c4de4803a6c034aaba3ae0e18c79131b6e/admin-dev/themes/default/template/controllers/specific_price_rule/helpers/form/form.tpl from this commit, and replaced my version with it, and the problem went away.

**Comment by ravloony** [comment]
I am using Firefox 70.0b2, in case that helps. It seems the `live` jquery handler did not have time to execute before the page was submitted. The commit referenced above switches to using `on` which does. This could come back again, so I would recommend adding inputs to the form when the options are added, so the form submit can't break like that again.

**Comment by ravloony** [comment]
I am closing this, as it no longer happens for me since that commit. Thanks for your help @khouloudbelguith !

**Comment by khouloudbelguith** [comment]
@ravloony, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
