### ISSUE TITLE
Missing Lithuanian stop words / blacklist for search

### ISSUE THREAD

**Issue by jusurb** [PrestaShop/PrestaShop#16575]
**Is your feature request related to a problem? Please describe.**
It seems when loaded Lithuanian language it uses English stop words

**Describe the solution you'd like**
I want Lithuanian descriptions indexed without LT stop words that are useless

Opened a pull request with updated LT stop words

**Comment by khouloudbelguith** [comment]
Hi @Gamesh,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & PS1.7.6.2build2.
![image](https://user-images.githubusercontent.com/16067358/69795299-35b0c800-11cc-11ea-8c67-460fd9e63958.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by LouiseBonnard** [comment]
Might be fixed on Crowdin, cf. https://github.com/PrestaShop/PrestaShop/pull/16576#issuecomment-628665479. Let's wait for the right translation and check if it solves this problem.

**Comment by LouiseBonnard** [comment]
It's all fixed thanks to the Crowdin translation, @Gamesh! I close this issue and the related PR then. :-)
