### ISSUE TITLE
Possible to add crypto currency support?

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#16577]
**Is your feature request related to a problem? Please describe.**
When you want to add new currency, there is no LTC or BTC available on the list. It would be nice to have crypto currency support there.

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
We are working on a reimplementation of CLDR.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by MatShir** [comment]
Hi @mrabsinthe,

I am happy to tell you that on the next version 1.7.7, you could add any currency as you want and customize it as you wish. Check the feature's progress on this issue #11660. But we will not automatically update the exchange rate for customs currencies, I invite you to check on the Pretsashop's marketplace to find a solution.

**Comment by mrabsinthe** [comment]
@MatShir it is good news indeed!
