### ISSUE TITLE
ps_facetedsearch slider filter not refreshed correctly after updateProductList

### ISSUE THREAD

**Issue by davideapvd** [PrestaShop/PrestaShop#16580]
**Describe the bug**
When changing any attribute from the faceted search, if having a slider, the refreshSliders call does not work correctly, if I put a setTimeout(refreshSliders, 0) here https://github.com/PrestaShop/ps_facetedsearch/blob/20ddf724e763e9b99f0199fda2f2bbf7eb5cede8/_dev/front/events.js#L31 probably the call gets scheduled after other things and the slider is rebuilt correctly.

**To Reproduce**
1. Go to category page with faceted search with a slider
2. Click on a filter
3. the slider is not rebuilt correctly

**Additional information**
PrestaShop version: 1.7.6.1
ps_facetedsearch version: 3.4.0

**Comment by khouloudbelguith** [comment]
Hi @davideapvd,

I did not manage to reproduce the issue with PS1.7.6.1 & the ps_facetedsearch v3.4.0.
I attached a screen record
https://drive.google.com/file/d/1Ja9k2fz6LVMMwLuh8JqGLLFVgRF-sbOx/view
Thanks to check & feedback.

**Comment by davideapvd** [comment]
would it be possible to add an id on the generated facet html, not a progressive one, so we can at lease hide them from css easily?

**Comment by davideapvd** [comment]
can you test from the chrome inspector to simulate a slower bandwidth from the network tab?

**Comment by khouloudbelguith** [comment]
@davideapvd, I attached a screen record
https://drive.google.com/file/d/18VPZhujN2ymbZLVQDuTzMNOrppAWFAOg/view
Thanks to check & feedback.

**Comment by davideapvd** [comment]
really appreciated, thanks, I'll try to understand what my theme based on the classical one has to do with this bug, feel free to close it in the meantime.

**Comment by khouloudbelguith** [comment]
@davideapvd, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by davideapvd** [comment]
@khouloudbelguith probably I understood the issue here, with minify enabled I've put my js files after the footer bundle that prestashop creates with /modules/ps_facetedsearch/views/dist/front.js, normally (without js minify and bundling) we have first the theme js and then the ps_facetedsearch one, with bundling enabled (expecially in my case) the order is swapped so updateProductList from the ps_facetedsearch module is run before the theme replaces the dom facets in updateProductListDOM, the way I see it is that ps_facetedsearch should not listen directly to updateProductList but something from the theme like updateProducListDOM (made up event name), so the theme could fire that event after we are sure the DOM content is updated.

what do you think?

**edit**
for example adding here https://github.com/PrestaShop/PrestaShop/blob/4b3d2262083d310ea9b74e2f7b245ebfaa973ac4/themes/classic/_dev/js/listing.js#L164

`prestashop.emit('updateProductListDOM')`

and here https://github.com/PrestaShop/ps_facetedsearch/blob/20ddf724e763e9b99f0199fda2f2bbf7eb5cede8/_dev/front/events.js#L29 change to

`  prestashop.on('updateProductListDOM', () => {`

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think?

Thanks!
