### ISSUE TITLE
[UI Kit] Single buttons

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16589]
Epic: #16587 

Button design will change into more rounded buttons. This change will be applied for all the buttons in the back office.

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

## [Primary button] Solid button without icon

Solid buttons will be used for actions like saving after editing, deleting a product, adding a product.

```
btn-without-icon { 
    Font-family: 'Open Sans';
    Font-weight: Bold;
    Font-size: 14px;
    Padding-top: 7px;
    Padding-bottom: 7px;
    Padding-left: 15px;
    Padding-right: 15px;
    Radius: 4px;
}
````

**Before and after**

![Before - Save](https://user-images.githubusercontent.com/54888056/69815143-031bc500-11f6-11ea-89cd-b0d094875dba.png)

![After - Save](https://user-images.githubusercontent.com/54888056/69815239-32cacd00-11f6-11ea-9e78-df7583760a14.png)

### Hover

Buttons get lighter.

    Color: #7CD5E7;

![Hover - Save](https://user-images.githubusercontent.com/54888056/69815261-3fe7bc00-11f6-11ea-82aa-d784565891ab.png)

### Click

Buttons get darker.

    Color: #21A6C1;

![Click - Save](https://user-images.githubusercontent.com/54888056/69815277-4413d980-11f6-11ea-8017-8418556a2ea9.png)

### Disable

Buttons are almost transparent.

    Color: #D3F1F7;

![Disable - Save](https://user-images.githubusercontent.com/54888056/69815290-49712400-11f6-11ea-9ff7-95f34245fc24.png)

---

## Solid button with icon

```
/* Space between the icon and the text: 10px. */
    
icon {
    Height: 20px;
    Width: 20px;
}
````

**Before and after**

Material icon used is called ["vertical_align_bottom"](https://material.io/resources/icons/?icon=vertical_align_bottom&style=baseline).

![Before-Button-Icon](https://user-images.githubusercontent.com/54888056/69815658-124f4280-11f7-11ea-8e11-a10c14e0ec8b.png)

![After-Buttons-Icon](https://user-images.githubusercontent.com/54888056/69815390-7ae9ef80-11f6-11ea-96a9-b633977ca36f.png)

---

## [Secondary button] Outline button without icon

Outline buttons without icon will be used for "Learn more", "Cancel" & "Help" buttons.

    Border: 1px;
    Border-color: #759299;

**Before and after**

![Before-Button-Outline](https://user-images.githubusercontent.com/54888056/69816901-a7ebd180-11f9-11ea-9e98-c73155c22a03.png)

![After-Button-Outline](https://user-images.githubusercontent.com/54888056/69816904-aa4e2b80-11f9-11ea-8641-16ab98307509.png)

**Comment by jf-viguier** [comment]
In Vision link is not publicly accessible, Please open it.

**Comment by prestascott** [comment]
Thank you for your feedback @jf-viguier 
I will update InVision links. :)

**Comment by colinegin** [comment]
@prestascott what's the status of this issue ?
