### ISSUE TITLE
It is possible to add negative Amount for Order Payment from the Back Office 

### ISSUE THREAD

**Issue by tdavidsonas88** [PrestaShop/PrestaShop#16582]
**Describe the bug**
It is possible to add negative Amount for Order Payment from the Back Office. Then message is thrown: An unexpected error occurred. [PrestaShopException code 0]. The actual exception is: Property Order->total_paid_real is not valid.

According to as I understand negative payments should not be saved to the database or at least total sum of payments from the db should not be negative.

**To Reproduce**
1. Go to Front Office and create new order.
2. Go to Back Office and go into that order page
3. Scroll down to Payment section and add new payment with negative amount: -5.548
4. See error: An unexpected error occurred. [PrestaShopException code 0]

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![Screenshot from 2019-11-28 12-51-45](https://user-images.githubusercontent.com/32385991/69800450-f5f2dc00-11dd-11ea-8003-61380ef05876.png)
![Screenshot from 2019-11-28 12-52-21](https://user-images.githubusercontent.com/32385991/69800463-fb502680-11dd-11ea-8b96-fa318348badd.png)

**Additional information**
Have Behat integration 2 failing tests written in file /Order/add_payment.feature on the Github Pull request: https://github.com/PrestaShop/PrestaShop/pull/16525

**Comment by khouloudbelguith** [comment]
Hi @tdavidsonas88,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & PS1.7.6.2build2 & the develop branch.
![image](https://user-images.githubusercontent.com/16067358/69805065-25a2e380-11e0-11ea-9abe-f28c28cae4ca.png)
Ping @matks, @marionf, @colinegin, this issue could be fixed during the migration of the order page?
Related to https://github.com/PrestaShop/PrestaShop/issues/13809
Thanks!

**Comment by tdavidsonas88** [comment]
@rokaszygmantas - would like some advice how we can contribute

**Comment by MatShir** [comment]
You can't add negative value to the payment method. To balance an overdue by the clients, it is recommended to make a credit slip.

**Comment by Progi1984** [comment]
Fixed in #17241

**Comment by radioeventos** [comment]
A payment can be positive or negative. Another thing is that the Total cannot be negative, but partial refunds must be allowed and that these are recorded.
It is a very serious problem for the accounting of a store that the exact accounting balance of a customer cannot be known.

**Comment by matks** [comment]
> A payment can be positive or negative.

You wish it to happen but it's PrestaShop @PrestaShop/product-team that decides what happens or not in the project.

I understand you find it very useful to have positive or negative payments but there is more than "is it easy or not to use" when it comes to payments.

AFAIK Product team is actually in the process of getting some law compliance people so that they can tell us what can be done or what cannot be done in order to comply with the law.

**Comment by VipinNethues** [comment]
I am getting issue related to it.

**PS 1.7.8.0**

**Error:** 
Property Order->total_paid is not valid
at line 1046 in file classes/ObjectModel.php

**How to reproduce it:**
1.  Create a voucher of amount 20$ (in any currency)  - 
2. add products in you cart on front shop less then voucher amount, in our case let it be 18$  (cart total must be less then voucher ammount)
3. Apply that voucher now you will see  ->  Total (tax incl.)-₹0.01  on cart summery.
4. choose address and payment option and proceed.
Now you will get that error, check attached image. 
  
![Property-Order-total_paid-is-not-valid](https://user-images.githubusercontent.com/20845330/161262414-eb7ac7c9-26db-482e-ab78-77b7379ad06d.png)

Looking for solution, if its already fixed please provide PR link for that fix.
Thanks

**Comment by MatShir** [comment]
@VipinNethues please create a dedicated issue [here](https://github.com/PrestaShop/PrestaShop/issues/new/choose)
