### ISSUE TITLE
[UI Kit] Buttons with dropdown

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16594]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

### Button with dropdown

This button with dropdown is used at this page:
- Module Manager (Configure, disable, uninstall, enable mobile, reset)
```
/* Space between the icon and the text: 10px. */

icon {
    Height: 10px;
    Width: 10px;
    Padding-left: 15px;
    Padding-right: 15px;
}
```

**Before and after**

Material icon used is called ["keyboard_arrow_down"](https://material.io/resources/icons/?icon=keyboard_arrow_down&style=baseline).

![Before - Button dropdown](https://user-images.githubusercontent.com/54888056/69817499-082f4300-11fb-11ea-876e-19e515c476f3.png)
![After - Button dropdown](https://user-images.githubusercontent.com/54888056/69817512-0c5b6080-11fb-11ea-8d09-9a448d70c2a5.png)
![After - Button dropdown open](https://user-images.githubusercontent.com/54888056/69817517-0feee780-11fb-11ea-9ad5-7cbe01b67f86.png)

**Comment by colinegin** [comment]
@prestascott what's the status of this issue ?
