### ISSUE TITLE
[UI Kit] Long sticky alerts

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16607]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

Those sticky alerts stay on the screen and until the user has solve the issue.

## Info sticky alert

Maximum number of lines before the "...": 2. 

```
h2 {
    Font-weight: Bold;
    Color: #363A41;
}
    
p1 {
    Font-weight: Regular;
}
    
showmore {
    Font-weight: Bold;
    Font-size: 14px;
    Color: #25B9D7;
}
    
icon {
    Color: #25B9D7;
    Size: 20px;
}
    
div {
    Background-color: #BEEAF3;
    Padding: 15px;
    Radius: 5px;
} 
    
Space between text and icon: 15px;
````    

**Before and after**

Material icons used are the same than the ["Short sticky alerts"](https://github.com/PrestaShop/PrestaShop/issues/16606).

![Before - Long sticky alert](https://user-images.githubusercontent.com/54888056/69822047-a45e4780-1205-11ea-8c35-ab04ef5b63ea.png)
![After - Long sticky alert](https://user-images.githubusercontent.com/54888056/69861359-82fa6b80-1298-11ea-8301-31d4bd58fea1.png)

**Comment by davidglezz** [comment]
insufficient contrast between the background color and the icon color

**Comment by prestascott** [comment]
Hi @davidglezz, thank you for your feedback. I updated this warning alert by changing the background color in order to increase the contrast with the icon. :)
