### ISSUE TITLE
[UI Kit] Breadcrumbs

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16605]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

Links are blue and the current page is the same color as the body because it is static (unclickable).

## Breadcrumb

```
text-button {
    Font-weight: Bold;
    Font-size: 12px;
    Color: #25B9D7;
}
    
static-text {
    Font-weight: Regular;
    Font-size: 12px;
    Color: #363A41;
}
````

**Before and after**

![Before - Breadcrumb](https://user-images.githubusercontent.com/54888056/69821816-fa7ebb00-1204-11ea-9c88-1a9405170389.png)
![After - Breadcrumb](https://user-images.githubusercontent.com/54888056/69821818-fc487e80-1204-11ea-8c52-2b3f0a1d3d9e.png)

**Comment by NeOMakinG** [comment]
Should we do this improvement on the UI Kit breadcrumb or on the theme.css one ?

If we do it on the uikit, we'll need to change the core breadcrumb into the UI Kit one, if we do it into the theme.css breadcrumb we'll never use bootstrap breadcrumbs..
