### ISSUE TITLE
[UI Kit] Cards

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16608]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

## Theme cards
Design > Theme Catalog

```
card {
    Radius: 5px;
}
    
img {
    Height: 285px;
    Width: 285px;
}
    
title {
    Font-size: 14px;
    Font-weight: Bold;
    Color: #363A41;
}
    
price {
    Font-size: 14px;
    Font-weight: Bold;
    Color: #708090;
}
    
text button {
    Font-size: 14px;
    Font-weight: Bold;
    Color: #25B9D7;
}
````

**Before and after**

![Before - Theme cards](https://user-images.githubusercontent.com/54888056/69822172-fdc67680-1205-11ea-9957-19abd44c5e1e.png)
![After - Theme cards](https://user-images.githubusercontent.com/54888056/69822177-ff903a00-1205-11ea-9963-ecaecdb1ee6d.png)

### Hover
```
/* Card gets a shadow. */
card {
    Box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.1).
}
````
---

## Module cards

Modules > Module Catalog

    /* Maximum lines of description text: 4. */

**Before and after**

![Before - Module cards](https://user-images.githubusercontent.com/54888056/69822192-08810b80-1206-11ea-9999-f388e3af5442.png)
![After - Module cards](https://user-images.githubusercontent.com/54888056/69822197-0a4acf00-1206-11ea-8d81-3d2dd4e05a7c.png)

**Comment by eternoendless** [comment]
@prestascott @colinegin These cards are only used in the module & themes pages, I'm not sure that it's worth it putting them in the UI kit. Moreover these elements are going to be extracted from the core and handled by MBO only, which cannot use newer additions to the UI kit...

**Comment by colinegin** [comment]
@TristanLDD wdyt ?

**Comment by TristanLDD** [comment]
As seen with @NeOMakinG, the BO uses the wrong bootstrap component for modules cards and actually uses bootstrap's cards for content blocks. So using them now would be a little bit complicated as we would have to fix a few classes first. 

@eternoendless About MBO, do you mean that MBO won't ever be able to support design improvements or updates ?

**Comment by prestascott** [comment]
> As seen with @NeOMakinG, the BO uses the wrong bootstrap component for modules cards and actually uses bootstrap's cards for content blocks. So using them now would be a little bit complicated as we would have to fix a few classes first.
> 
> @eternoendless About MBO, do you mean that MBO won't ever be able to support design improvements or updates ?

ping @eternoendless, wdyt?

**Comment by colinegin** [comment]
ping @Matt75 do you think this could be integrated in MBO ?

**Comment by Matt75** [comment]
As the module catalog page stay in Core yet, not before few months (years ?)

**Comment by colinegin** [comment]
Haha, true, but we could still add it to MBO in the meantime.
I've added the mbo label.
