### ISSUE TITLE
[UI Kit] Checkboxes

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16602]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

Checkboxes can be found in the tables and at these pages:
- Orders > Invoices
- Design > Positions

## Checkbox on

Material icon used is called ["check_box"](https://material.io/resources/icons/?icon=check_box&style=baseline).

```
checkbox-on {
    Color: #25B9D7;
    Size: 20px;
    Margin-right: 10px;
    Margin-left: 40px;
    Margin-bottom: 10px;
}
````

## Checkbox off

Material icon used is called ["check_box_outline_blank"](https://material.io/resources/icons/?icon=check_box_outline_blank&style=baseline).

```
checkbox-off {
    Color: #B3C7CD;
    Size: 20px;
    Margin-right: 10px;
    Margin-left: 40px;
    Margin-bottom: 10px;
}
````

**Before and after**

![Before - Checkboxes](https://user-images.githubusercontent.com/54888056/69821412-da9ac780-1203-11ea-8922-f7fa366512f9.png)
![After - Checkboxes](https://user-images.githubusercontent.com/54888056/69821420-dcfd2180-1203-11ea-9e1d-4405164065d5.png)

## Unselect

Material icon used is called ["indeterminate_check_box"](https://material.io/resources/icons/?icon=indeterminate_check_box&style=baseline). It will be used for bulk actions.

```
checkbox-unselect {
    Color: #25B9D7;
    Size: 20px;
    Margin-right: 10px;
    Margin-left: 40px;
    Margin-bottom: 10px;
}
````

**Comment by NeOMakinG** [comment]
This component is already a part of the UI Kit, but only refactored pages benefits of the uikit, did some adjustement anyway on the PR behind
