### ISSUE TITLE
[UI Kit] Dropdowns

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16609]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

The width of dropdowns depends on the size of the longest text but for some cases, it must respect bootstrap column.
When the dropdown is opened, the arrow icon points up.

## Dropdown

Dropdowns can be found at:
- Stats' modules page (Available quantities, Carrier distribution, Catalog evaluation, and so on)
- Modules > Module Manager
- Modules > Module Catalog
- Design > Theme & Logo

```
dropdown {
    Color: #363A41;
    Padding-left: 15px;
    Padding-right: 15px;
    Padding-top: 7px;
    Padding-bottom: 7px;
    /* Space between text & icon: 15px */
    Border-color: #B3C7CD;
    Radius: 4px;
}
````

**Before and after**

Material icons used is called ["keyboard_arrow_down"](https://material.io/resources/icons/?icon=keyboard_arrow_down&style=baseline).

![Before - Dropdown closed](https://user-images.githubusercontent.com/54888056/69822343-6e6d9300-1206-11ea-9d4a-c5cbca7c3e00.png)
![After - Dropdown closed](https://user-images.githubusercontent.com/54888056/69822348-70375680-1206-11ea-990e-d26d143f61ce.png)

### Hover

    Font-weight: Semibold;
    Color: #25B9D7;
    Background-color: #F0FCFD;

**Before and after**

Material icon used is called ["keyboard_arrow_up"](https://material.io/resources/icons/?icon=keyboard_arrow_up&style=baseline).

![Before - Dropdown opened](https://user-images.githubusercontent.com/54888056/69822386-8218f980-1206-11ea-9b79-9e79ea2dc1bd.png)
![After - Dropdown opened](https://user-images.githubusercontent.com/54888056/69822389-834a2680-1206-11ea-86bc-ff72d5160de2.png)

### Click

    Font-weight: Semibold;
    Color: #ffffff;
    Background-color: #25B9D7;

**Comment by NeOMakinG** [comment]
This component is not a part of the UI Kit, it should be replaced by these ones which are based on button style + dropdown styles

![image](https://user-images.githubusercontent.com/14963751/70043765-578dbe80-15c1-11ea-8c2c-a8092a586540.png)

Edit : Needs to speak about it, we may need to add it to the UI Kit

**Comment by NeOMakinG** [comment]
I need to find out why I've a strange pixel calculated by Bootstrap
