### ISSUE TITLE
var/cache issues

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16617]
**Describe the bug**
A white screen after hitting "clean cache" button.

**To Reproduce**
1. Enable debug mode from website backend and hit "clean cache" button.  Often that leads to a white screen without any error in the browser. To get cache cleaned successfully and to return to website backend you need to hit F5 in browser on this white screen page.

At httpd.log there will be an error:
[proxy_fcgi:error] [client xx.xx.xx.xx:56464] AH01071: Got error 'PHP message: PHP Fatal error:  require(): Failed opening required '/var/public_html/var/cache/dev/Containerxxxxxxx/getPrestashop_Core_Admin_PagePreferenceInterfaceService.php' (include_path='/var/public_html/vendor/pear/pear_exception:/var/public_html/vendor/pear/console_getopt:/var/public_html/vendor/pear/pear-core-minimal/src:/var/public_html/vendor/pear/archive_tar:.:/usr/local/share/pear') in /var/public_html/var/cache/dev/Containerxxxxxxx/appDevDebugProjectContainer.php on line 1708\nPHP message: PHP Fatal error:  require(): Failed opening required '/var/public_html/data/var/cache/dev/Containerxxxxxxx/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/var/public_html/vendor/pear/pear_exception: /var/public_html/vendor/pear/console_getopt: /var/public_html/vendor/pear/pear-core-minimal/src:/var/public_html/vendor/pear/archive_tar:.:/usr/local/share/pear') in /var/public_html/var/cache/dev/Containerxxxxxxx/appDevDebugProjectContainer.php on line 1708\n', referer: https://mywebsite.com//adminxxxxxxxxxx/index.php/configure/advanced/performance/?_token=xxxxxxxxxxxxxxxxxxxxxxxx

**Screenshots**

**Additional information**
Deleting everything from /var/public_html/var/cache does not help Prestashop just recreate all deleted files and folders "dev" or "prod" depending from the current mode (debug or not).
PrestaShop version: 1.7.6.1
PHP version: 7.1, 7.2, 7.3.
Apache 2.41
VPS webserver is fully compliant to https://github.com/PrestaShop/php-ps-info/
chown and chmod are correct for var/cache
getPrestashop_Core_Admin_PagePreferenceInterfaceService.php - is present in corresponding directory and not empty.

If you will be unable to reproduce the issue please post here your webserver ini/conf files. So I try to make changes on my VPS and test the issue again.

**Comment by khouloudbelguith** [comment]
Hi @rss9090,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Second, in your case, the `var/cache/prod/appParameters.php` file is recreated with 000 permissions? 

Did you use `opcache`?
I think you have an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10998
Thanks to check & feedback.

**Comment by ghost** [comment]
Hi, khouloudbelguith

I know about recommended PHP versions but tried 7.3 after having no luck with 7.1 and 7.2. Also forgot to say that problem appears not only in dev mode but in prod too. And seems while webserver works under php7.3 the issue remains only in dev (debug) mode.

Considering Opcache I thought this way too and tried with opcache.enabled=0 before creating ticket here but problem persists. Yes I don't forgot to reload apache and php-fpm after disabling Opcache in php.ini. Considering the ticket: #10998 not likely my case because he was unable to finish its request. In my case request finishes with success message but from the second time (after page renewed by F5 in a browser).

For the getPrestashop_Core_Admin_PagePreferenceInterfaceService.php file owner is user "www" in group "www", www means Apache, permissions are 644 so they are correct. For the var/cache, var/cache/dev and var/cache/dev/Containerxxxxx owner is also "www" with permissions 755.

For the var/cache/prod/appParameters.php file owner is user "www" in group "www", www means Apache, permissions are 644 so I assume that they are correct.

**Comment by khouloudbelguith** [comment]
@rss9090, you need to follow these steps: https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-476361695
```
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.fast_shutdown = 0
```
Fixed with this PR: https://github.com/PrestaShop/docker/pull/193

Thanks to check & feedback.

**Comment by ghost** [comment]
I'm sorry but you wrote opcache.revalidate_freq = 0 twice is that a mistake?
tried with 
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.fast_shutdown = 0

No effect on the issue,
By the way what is the minimal RAM requirements for a webserver to work OK with PS 1.7.6.1? Load is low.

**Comment by khouloudbelguith** [comment]
@rss9090, thanks to follow this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ about the `System requirements for PrestaShop 1.7`.
You can follow this configuration: https://github.com/PrestaShop/docker/blob/master/base/config_files/php.ini#L1832
for the `opcache`.

Thanks!

**Comment by ghost** [comment]
Thank you but this link is well known. I need exact information how many GB of RAM webserver should have minimally to run PS 1.7.6.1 flawlessly. At  https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/  there is no such info.

Copied opcache settings from here https://github.com/PrestaShop/docker/blob/master/base/config_files/php.ini#L1832
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.max_wasted_percentage=10
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.revalidate_path=0
opcache.fast_shutdown=0
opcache.enable_file_override=1
opcache.max_file_size=0

No effect on the issue.

**Comment by ghost** [comment]
used whole php.ini from here https://github.com/PrestaShop/docker/blob/master/base/config_files/php.ini#L1832
Problem went worse - unable to turn off dev mode because of 500 error.

**Comment by ghost** [comment]
Returned to my version of php.ini rebooted. 
When installing new template got error - Cannot rename "/var/public_html/var/cache/dev/ContainerZoyjmmg/getPrestashop_Core_Query_DoctrineSearchCriteriaApplicatorServicxxxxxx" to "/var/public_html/var/cache/dev/ContainerZoyjmmg/getPrestashop_Core_Query_DoctrineSearchCriteriaApplicatorService.php".

F5 in browser do the trick.

**Comment by Hlavtox** [comment]
This is not a problem of your server, clearing cache doesnt work. https://github.com/PrestaShop/PrestaShop/issues/11105

**Comment by khouloudbelguith** [comment]
@Hlavtox, this is a double click on the clear cache.
If we click once => OK
Thanks!

**Comment by ghost** [comment]
I don't doubleclick.
Okay if it's an unfixed bug then what possible could be a workaround - to disable cache at all by uninstalling corresponding php extensions?

**Comment by Hlavtox** [comment]
@khouloudbelguith  It's not ok, it does no work - https://drive.google.com/file/d/1hDoTiBSzKMLK1FzAU0nWVQ-1cuQLOaDG/view?usp=sharing

**Comment by khouloudbelguith** [comment]
@rss9090,

>I need exact information about how many GB of RAM webserver should have minimally to run PS 1.7.6.1 flawlessly. At  https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/  there is no such info.

I just forwarded your question to the team core.
- We recommended minimum by a process is 256mo but it's for ONE process => so overall a few Go is recommended as explained in this section: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
- The exact information depends on how many parallel accesses you want to manage and you also need some RAM for MySQL, apache and other services
- It mostly depends on the shop's activity. But let's say that, for starters, 2GB of RAM is enough.

Just keep in mind that, if everything goes fine and the shop grows, will come a time where it won't be enough anymore.

@rss9090, I used this configuration
>opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.max_wasted_percentage=10
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.revalidate_path=0
opcache.fast_shutdown=0
opcache.enable_file_override=1
opcache.max_file_size=0

![image](https://user-images.githubusercontent.com/16067358/69868110-16d43380-12a9-11ea-93f1-b85601ba76a3.png)

I tried to clear cache, disable debug mode => OK
I attached a screen record
https://drive.google.com/file/d/1MiaI6O1Eel6WB2EU7_sF1kSRAHEMpQ0e/view

Thanks!

**Comment by ghost** [comment]
> 
> 
> @khouloudbelguith It's not ok, it does no work - https://drive.google.com/file/d/1hDoTiBSzKMLK1FzAU0nWVQ-1cuQLOaDG/view?usp=sharing

And if you hit F5 shop completes cache clearing? What error you see in httpd.log?

**Comment by Hlavtox** [comment]
`[29-Nov-2019 13:17:32 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/removed-ids.php' (include_path='/srv/www/eshop-teka.cz/public/new/vendor/pear/pear_exception:/srv/www/eshop-teka.cz/public/new/vendor/pear/console_getopt:/srv/www/eshop-teka.cz/public/new/vendor/pear/pear-core-minimal/src:/srv/www/eshop-teka.cz/public/new/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/appProdProjectContainer.php on line 1611
`

**Comment by Hlavtox** [comment]
And before, it threw this:

```
[29-Nov-2019 13:01:13 Europe/Prague] PHP Warning:  require(/srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/getPrestashop_Translation_DatabaseLoaderService.php): failed to open stream: No such file or directory in /srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/appProdProjectContainer.php on line 1633
[29-Nov-2019 13:01:13 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/getPrestashop_Translation_DatabaseLoaderService.php' (include_path='/srv/www/eshop-teka.cz/public/new/vendor/pear/pear_exception:/srv/www/eshop-teka.cz/public/new/vendor/pear/console_getopt:/srv/www/eshop-teka.cz/public/new/vendor/pear/pear-core-minimal/src:/srv/www/eshop-teka.cz/public/new/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/eshop-teka.cz/public/new/var/cache/prod/ContainerOksxc3x/appProdProjectContainer.php on line 1633
[29-Nov-2019 13:01:14 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/eshop-teka.cz/public/new/var/cache/prod/": rmdir(/srv/www/eshop-teka.cz/public/new/var/cache/prod/): Directory not empty. in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/eshop-teka.cz/public/new/classes/Tools.php(3431): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

**Comment by khouloudbelguith** [comment]
@Hlavtox, this is a cache issue.
Clearing the cache manually solves the issue.
But, in my case, with PS1.7.6.1, when I try to clear cache from the BO => OK => Succesful alert as you can see in my screen record.

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
> Hlavtox, this is a double click on the clear cache.
> If we click once => OK
> Thanks!

Tested double and triple clicks on a cache button - confirm faulty behaviour with white screen. But if I hit F5 then I successufily back to shop admin interface and got 2 or 3 "cache cleared successful" messages. But in my case even one click sometimes lead to such error.
@Hlavtox  
> `[29-Nov-2019 13:17:32 Europe/Prague] PHP Fatal error: require(): Failed opening required '/srv/www/eshop-teka.cz/public/new/va............

How much RAM do you have on your webserver?

**Comment by Hlavtox** [comment]
@rss9090 256MB RAM

**Comment by ghost** [comment]
@Hlavtox 
> 256MB RAM

put there 2048+ MB RAM and try to test again please

**Comment by khouloudbelguith** [comment]
@rss9090,
>Tested double and triple clicks on a cache button - confirm faulty behaviour with white screen

If you click more than one => error, we are aware of this issue => it is added to our bug roadmap as reported here: https://github.com/PrestaShop/PrestaShop/issues/11105

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith
How much RAM do you have on your webserver? Do you have a swap partition or swapfile enabled and in use? If yes of what size?

**Comment by khouloudbelguith** [comment]
@rss9090,
![image](https://user-images.githubusercontent.com/16067358/69871291-b21dd680-12b2-11ea-8a95-137460efcd66.png)
here's my configuration
![image](https://user-images.githubusercontent.com/16067358/69871338-d2e62c00-12b2-11ea-8fd7-ce1940748bd9.png)

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
Thank you, could you provide also phpinfo() output from your webserver?

**Comment by khouloudbelguith** [comment]
@rss9090, yes!
[phpinfo().pdf](https://github.com/PrestaShop/PrestaShop/files/3905505/phpinfo.pdf)

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
phpinfo().pdf
As far as I can see you use php_mod? And mcrypt (pecl-mcrypt) doesn't needed?

**Comment by khouloudbelguith** [comment]
@rss9090,

>As far as I can see you use php_mod?

Yes!
>
The mcrypt extension was deprecated for 7.1 & I 'm using PHP7.2.
https://github.com/PrestaShop/PrestaShop/pull/6265

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
Yes I know that it's deprecated but there is php72-pecl-mcrypt package and what would be better to install it or not? Does PS 1.7.6.2 use it or not?

**Comment by khouloudbelguith** [comment]
@rss9090, those are the PHP extensions required & recommended
![image](https://user-images.githubusercontent.com/16067358/69882427-64b06200-12d0-11ea-8a8f-c8dc0e76eb4f.png)
You can  follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith and what about php72-tokenizer? Seems like a php modules list is incomplete?

**Comment by ghost** [comment]
@khouloudbelguith if we install only modules that listed in the tool we will get an error during the PS installation "PrestaShop installation requires the SimpleXML extension to be enabled." 
So can you request from your tech team a complete required php72-modules list and post here please,
Also ask them please is there any specific settings if apache/proxy_fcgi is used?

**Comment by khouloudbelguith** [comment]
@rss9090, in this file: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ConfigurationTest.php#L89
You can check all the tests done during the install of PrestaShop.

Thanks!

**Comment by ghost** [comment]
> 
> 
> @rss9090, in this file: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ConfigurationTest.php#L89
> You can check all the tests done during the install of PrestaShop.
> 
> Thanks!

Prestashop don't perform all necessary checks during install and it's well-known. Publish complete modules list please,

Considering mentioned above cache error - it happens only if mod_proxy_fcgi used in mod_php there is no such issue but it's awfully slow. So would you try to configure your test server with Apache mpm_event + mod_proxy_fcgi to reproduce the issue?

**Comment by khouloudbelguith** [comment]
@rss9090, Thanks for your feedback.
I will try to reproduce the issue using this environment & I will feedback.

**Comment by khouloudbelguith** [comment]
@rss9090, I will try with this server
[phpinfo.pdf](https://github.com/PrestaShop/PrestaShop/files/3917370/phpinfo.pdf)
Is it ok?

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
Could you post here your httpd.conf and other webserver ini/conf files (if used)? Also as far as I can see there is a PHP 7.1  instead of  recommended PHP7.2

**Comment by khouloudbelguith** [comment]
@rss9090, I tried with this command in my terminal
`> apache2ctl -M`
I have all this module apache enabled
```
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 pagespeed_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)
```
I used a server with PHP-fpm folwing this link: http://keksus.com/upgrade-php5-to-php7-1-on-debian.html
Here's the second server, I'm trying to configure
[phpinfo (1).pdf](https://github.com/PrestaShop/PrestaShop/files/3917452/phpinfo.1.pdf)

Thanks!

**Comment by ghost** [comment]
I need to see an exact config file.

**Comment by khouloudbelguith** [comment]
@rss9090, the `php.ini` file? 

Thanks!

**Comment by ghost** [comment]
httpd.conf and if you change something in other files apache24/Includes/*.conf post them too please

**Comment by khouloudbelguith** [comment]
Hi @rss9090,

I will check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
@rss9090, here's the Apache configuration file
[apache2.conf.zip](https://github.com/PrestaShop/PrestaShop/files/3922194/apache2.conf.zip)
Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
Thank you for the file provided but following parts of the config are missing

```
# Include list of ports to listen on
Include ports.conf

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf
```

**Comment by khouloudbelguith** [comment]
@rss9090, those lines are missing in your case? isn't?
In my config file, they are added.
Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
In your archive file there is an only apache2.conf file. Missing files should be added to archive from/with the corresponding folders.

**Comment by khouloudbelguith** [comment]
@rss9090, so, do you need to provide you the other files?
Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
sure

**Comment by khouloudbelguith** [comment]
@rss9090, all files attached:

[conf-available.zip](https://github.com/PrestaShop/PrestaShop/files/3932967/conf-available.zip)
[mods-enabled.zip](https://github.com/PrestaShop/PrestaShop/files/3932968/mods-enabled.zip)
[ports.conf.zip](https://github.com/PrestaShop/PrestaShop/files/3932969/ports.conf.zip)
[sites-available.zip](https://github.com/PrestaShop/PrestaShop/files/3932970/sites-available.zip)

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
Thank you for config files provided. Have you tried to clear cache (debug mode enabled) on this webserver configuration on a Prestashop 1.7.6.2?

**Comment by ghost** [comment]
@khouloudbelguith 
Also as far as I can see from your config files to handle .php files you use:
```
ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/run/php/php7.2-fpm.sock|fcgi://localhost/projet/
ProxyPassReverse ^/(.*\.php(/.*)?)$ unix:/run/php/php7.2-fpm.sock|fcgi://localhost/projet/
```
In my case I use:
```
<FilesMatch \.php$>
        SetHandler proxy:fcgi://127.0.0.1:9000
</FilesMatch>
```
Also in my case there is no difference how to get an error using TCP socket or UNIX socket with SetHandler.

**Comment by ghost** [comment]
@khouloudbelguith 
Alternative configurations I tried:
1. Using Apache 2.4 mpm_prefork  + mod_php (non-threaded)  - no errors
2. Using Apache 2,4 mpm_worker + mod_fcgid - no errors

**Comment by khouloudbelguith** [comment]
Hi @rss9090,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
https://drive.google.com/file/d/1LVL2kw3-AiPVN5-f9ucGI1QgXFQ6Bdf3/view
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by xprojects-de** [comment]
Hallo zusammen,

ich bin auch bei ALL-Inkl und konnte ein bisschen mehr rausfinden. Der Fehler tritt jedenfalls bei mir immer an der selben Stelle in den PHP-Scripten auf wenn ich den contao/install-Path aufrufe (nach Login!):

_**ssh-xxx@xxx:/www/htdocs/xxx$ cat errorlog.txt 
[29-May-2020 22:25:13 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1531904 bytes) in /www/htdocs/xxx/DOMAIN/var/cache/prod/ContainerJFegKaP/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php on line 512
[29-May-2020 22:25:13 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1531904 bytes) in /www/htdocs/xxx/DOMAIN/vendor/composer/ClassLoader.php on line 444**_

Auszüge aus dem Code:
appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php on line 512
`   public function getRemovedIds(): array
    {
        // this is Line 512
        return require $this->containerDir.\DIRECTORY_SEPARATOR.'removed-ids.php';
    }`
ClassLoader.php on line 444
`/**
 * Scope isolated include.
 *
 * Prevents access to $this/self from included files.
 */
function includeFile($file)
{
    // this is line 444
    include $file;
}`

Das Memory-Limit liegt per Default bei 256MB was ich eigentlich gar nicht mal sooo schlampig finde! ... und hier scheint das Array der removed-ids den "Überlauf" zu verursachen.
Bei mir funktioniert es dann erst wenn ich wirklich auf 1GB gehe! Das finde ich ehrlich gesagt schon sehr massiv. Komme aus der Hochsprachenprogrammierung (Java und C++ bei Bosch) und sehe solche emensen Memoryanforderungen eigentlich eher selten in Hochsprachen!

Das Ganze tritt hier ja bei der DependencyInjection auf. Eventuell hat da ja vielleicht der eigens erstellte Contao-HTTP-Kernel noch ein Problem? Mit DI haben wir uns auch schon rumgeschlagen :-) .. Möglicherweise verursachen die vielen "includes" der Files aber auch solche Memory-Lasten!?

Vielleicht hilft die Info ja weiter!!

Danke für euren Einsatz!

Grüße
