### ISSUE TITLE
Latest version prestashop file is not found on the link - PrestaShop v 1.7.6.2 Stable

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#16618]
**Describe the bug**
 PrestaShop v 1.7.6.2 Stable - file missing

**To Reproduce**
1. Go to 'https://www.prestashop.com/en/previous-versions'
2. Click on 'PrestaShop v 1.7.6.2 Stable - download button'
3. See error - https://download.prestashop.com/download/releases/prestashop_1.7.6.2.zip?_ga=2.116999429.2007158038.1574926980-73866645.1574661170

**Screenshots**
![prestashop1762](https://user-images.githubusercontent.com/39614089/69846580-77a83f80-129a-11ea-9ada-a38c013cd060.png)

**Additional information**
PrestaShop version: 1762
PHP version: N/A

**Comment by matks** [comment]
@PeeyushAgrawalWebkul thanks for telling us 😉 
You can download 1.7.6.2 from page https://www.prestashop.com/en/download while we fix the link bug

**Comment by matks** [comment]
> @PeeyushAgrawalWebkul thanks for telling us 😉
> You can download 1.7.6.2 from page https://www.prestashop.com/en/download while we fix the link bug

EDIT: nope, this link is broken too 😞 although it worked yesterday. Sorry we're going to fix it real quick. You can download 1.7.6.2 from github https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.2

**Comment by matks** [comment]
@PeeyushAgrawalWebkul links are now valid again 😉 

thank you again for telling us !

**Comment by PeeyushAgrawal** [comment]
@matks 

Your welcome!
