### ISSUE TITLE
Missing charts on BO dashboard

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#16614]
**Describe the bug**
On fresh install of PS 1.7.6.1, I have no charts in dashboard tab.
In web developper console I have the following error:
`TypeError: window[charts[chart_id].chart_type] is not a function`
Related to line 178 of dashboard.js file

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![no-dahsboard-graph](https://user-images.githubusercontent.com/7419525/69823151-69a9de80-1208-11ea-9ef2-74390ec017d3.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2
Web server: Nginx 1.15.9

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2.
![image](https://user-images.githubusercontent.com/16067358/69853090-3ad24d80-1286-11ea-91bb-84f58c799ea4.png)
Could you please try to re-install the `dashtrends` module, clear cache, check & feedback.

Thanks!

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith,

Thanks for your answer. You're right, `dashtrend` (and other dash* modules) were missing on **actionAdminControllerSetMedia** and **actionOrderStatusPostUpdate** hooks so I reset them and now graphs are come back!

Thanks a lot for your help, I close this ticket :)

**Comment by khouloudbelguith** [comment]
@Klemart3D, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
