### ISSUE TITLE
ps_facetedsearch price slider issue

### ISSUE THREAD

**Issue by Emmanuel974** [PrestaShop/PrestaShop#16619]
Hi,

The price slide of the faceted filter is not responsive?
Take a look at my screen please.

Best regards,

Chrome
PS 1.7.5.2
PHP 7.0.33-0+deb9u3 (cli)
![issue-slider-facet](https://user-images.githubusercontent.com/38462724/69847800-9d7d1680-1291-11ea-8d5f-ac67e4c9097a.png)

**Comment by khouloudbelguith** [comment]
Hi @Emmanuel974,

It is OK with PS1.7.6.2 & the default theme classic provided by PrestaShop.
https://drive.google.com/file/d/1odR6F9Kj0_8iTBKzTabEdxkUN13_dyq-/view
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Emmanuel974** [comment]
Hi thank you.
