### ISSUE TITLE
[UI Kit] Dropdowns under icon

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16610]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

The width of dropdowns depends on the size of the longest text.
When the dropdown is opened, the arrow icon points up.
Dropdown is aligned on the right.

## Dropdown under icon

```
dropdown-under-icon {
    Margin-top: 10px,
    Color: #363A41;
    Padding-left: 15px;
    Padding-right: 15px;
    Padding-top: 7px;
    Padding-bottom: 7px;
    /* Space between text & icon: 15px */
    Border-color: #B3C7CD;
    Radius: 4px;
}
````

**Before and after**

Material icon is called ["configuration"](https://www.materialui.co/icon/configuration).

![Before - Dropdown under icon](https://user-images.githubusercontent.com/54888056/69822562-f81d6080-1206-11ea-840b-d0cfda75d175.png)
![After - Dropdown under icon](https://user-images.githubusercontent.com/54888056/69822565-f9e72400-1206-11ea-97b8-ebf3f4c4f0d8.png)

### Hover

    Font-weight: Semibold;
    Color: #25B9D7;
    Background-color: #F0FCFD;

### Click

    Font-weight: Semibold;
    Color: #ffffff;
    Background-color: #25B9D7;

**Comment by colinegin** [comment]
@prestascott what's the status of this issue ?

**Comment by LouiseBonnard** [comment]
Done by https://github.com/PrestaShop/prestashop-ui-kit/pull/71, I close this issue, thanks @prestascott and @NeOMakinG!
