### ISSUE TITLE
[UI Kit] Modals

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16613]
Epic: #16587 

[Link to InVision prototype](https://projects.invisionapp.com/d/main#/console/18908855/393895461/preview)

Modals were positioned on the top of the screen and by doing that, users can still see and read what is on the background so it didn't allow him to focus on the modal. 
Modals position will change and will be centered on the screen.

## Modal

```
modal {
    Box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.1).
}  
    
title {
    Font-size: 16px;
    Font-weight: Bold;
    Color: #363A41;
    Margin-left: 20px;
    Margin-top: 20px;
    Margin-bottom: 20px;
}
    
/* 100 characters max per line. */
body {
    Font-size: 14px;
    Font-weight: Regular;
    Color: #363A41;
    Margin-left: 20px;
    Margin-bottom: 30px;
}
````

**Before and after**

Material icon used is called ["close"](https://material.io/resources/icons/?icon=close&style=baseline).

![Before - Modal](https://user-images.githubusercontent.com/54888056/69823134-5d258600-1208-11ea-9288-887d936045cf.png)
![After - Modal](https://user-images.githubusercontent.com/54888056/69823135-5e56b300-1208-11ea-95ca-b1db3db05c88.png)

**Position before and after**

![Before - Modal position](https://user-images.githubusercontent.com/54888056/69823145-644c9400-1208-11ea-9f77-e31976976d6e.png)
![After - Modal position](https://user-images.githubusercontent.com/54888056/69823146-66165780-1208-11ea-87d3-523f83273cc7.png)

**Comment by muyncky** [comment]
Extremely smooth. I love it.
