### ISSUE TITLE
#15621 causes errors on upgrade if table contains extra columns

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16624]
**Describe the bug**
I don't use multistore, but got some warnings during autoupgrade from 1.7.6.1 to 1.7.6.2 regarding ps_product_lang and ps_category_lang, complaining that column count is not correct.

I think it's pretty common for modules to modify database structure and add own columns, the upgrade sql scripts are not prepared for this.

**To reproduce**
- Install 1.7.6.1
- Add some columns to product or category lang table.
- Run auto upgrade to 1.7.6.2
- See the errors

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

>Add some columns to product or category lang table.

How did you add those columns? manually from the database?

Thanks!

**Comment by Hlavtox** [comment]
In my case, some of them were added by one import module, some of them manually. But I know a lot of modules that add custom columns to the database during installing. This is usually not a problem, because every time I upgraded, the scripts just add something or slightly change the column type.

![Výstřižek](https://user-images.githubusercontent.com/6097524/69887210-2625a200-12e6-11ea-8810-69694f8e4943.JPG)

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.1 during an upgrade using the 1-click upgrade v4.10.0.
I have these errors
```
SQL 1.7.6.2 1136 in INSERT INTO `ps_category_lang` SELECT `entity`.`id_category`, 1, `entity`.`id_lang`, `entity`.`name`, `entity`.`description`, `entity`.`link_rewrite`, `entity`.`meta_title`, `entity`.`meta_keywords`, `entity`.`meta_description` FROM `ps_category_lang` entity LEFT JOIN `ps_category_lang` entity2 ON `entity2`.`id_shop` = 1 AND `entity`.`id_category` = `entity2`.`id_category` WHERE `entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1
SQL 1.7.6.2 1136 in INSERT INTO `ps_product_lang` SELECT `entity`.`id_product`, 1, `entity`.`id_lang`, `entity`.`description`, `entity`.`description_short`, `entity`.`link_rewrite`, `entity`.`meta_description`, `entity`.`meta_keywords`, `entity`.`meta_title`, `entity`.`name`, `entity`.`available_now`, `entity`.`available_later`, `entity`.`delivery_in_stock`, `entity`.`delivery_out_stock` FROM `ps_product_lang` entity LEFT JOIN `ps_product_lang` entity2 ON `entity2`.`id_shop` = 1 AND `entity`.`id_product` = `entity2`.`id_product` WHERE `entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1
```
https://drive.google.com/file/d/1TjuX7E_L1Avp7qoYT0WgrqagBEs8-kgk/view
Ping @PierreRambaud @jolelievre what do you think? this is a normal behavior or a bug?

Thanks!

**Comment by mishkop** [comment]
Hi - similar problem here when upgrading to 1.7.6.3 from 1.7.4.2:
I have got this warning after upgrade:

SQL 1.7.6.2 1136 in INSERT INTO `ps_category_lang` SELECT `entity`.`id_category`, 1, `entity`.`id_lang`, `entity`.`name`, `entity`.`description`, `entity`.`link_rewrite`, `entity`.`meta_title`, `entity`.`meta_keywords`, `entity`.`meta_description` FROM `ps_category_lang` entity LEFT JOIN `ps_category_lang` entity2 ON `entity2`.`id_shop` = 1 AND `entity`.`id_category` = `entity2`.`id_category` WHERE `entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1

The shop doesnt work after upgrade - goes to error 500 (not able to load)... Is there any simple solution like delete/clear cells/columns in database or so? Thank you a lot! M.

**Comment by PierreRambaud** [comment]
Hello everyone,

at it says in the [devdoc](https://devdocs.prestashop.com/1.7/modules/creation/good-practices/#dos-and-donts):

- Create your own database tables, do not alter PrestaShop’s.
- Don’t edit the SQL structure of PrestaShop tables.


Kind regards
