### ISSUE TITLE
[SEO | IMPROVEMENT] Add category bottom description

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16627]
**Problem**
It would be very useful if you guys could add a second description field to a category, which would show up under the product list.

For SEO purposes, merchants usually add a lot of text to category description. Upper description is not very good place for this, because people will usually not read it and it just occupies space.

Collapse is one solution, but hidden text has less "value" for the robots.

**Solution**
Make a "copy" of category description and show it under a product list.

**Inspiration - my implementation**
![Výstřižek](https://user-images.githubusercontent.com/6097524/69887381-ed39fd00-12e6-11ea-9856-f936af87a12a.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by LouiseBonnard** [comment]
Having another text block right in a category page, right under the list of products, to display a longer description of the category seems to be a common practice, actually. And it sure is useful for SEO purposes. What do you think, @prestascott and @TristanLDD?

**Comment by prestascott** [comment]
Thank you @Hlavtox,

I agree with you about SEO purposes. The more content (keywords, description, links, etc…) a page has, the better it will be referenced on Google. 
On the other hand, I don’t think all of our users will need this feature so it is important to give them the option to add and remove the description block as they want. 

- If they want, users can add a bottom description block on their category page
- If they don’t want, they still have a preview of their disabled tinymce editor so they know what to expect by checking the box

This is my design proposition on the back office:

![bo-bottomdescriptionblock1](https://user-images.githubusercontent.com/54888056/75037588-d30e5600-54b4-11ea-8a8b-5e2dc62e5f6a.png)
![bo-bottomdescriptionblock2](https://user-images.githubusercontent.com/54888056/75037590-d4d81980-54b4-11ea-833d-318f3d3e8264.png)

Wdyt?

**Comment by Hlavtox** [comment]
@prestascott Nice, but if the checkbox is not checked, I would hide the text editor, otherwise it has no sense, no?

In this state, the checkbox just occupies additional space above the textarea and adds 1 more click to people who want to add the bottom description. 😎

**Comment by prestascott** [comment]
@Hlavtox Like I said, the text editor still appears so users know that if they check the box, it would be enable.
By checking the box, the bottom block appears. 

If I leave the text editor without an activation component like above, it means that it will appear by default on the category page. By doing that, users will think that if they leave the text editor blank, it will show an empty box like when your description box above is empty. 

This is why it is important to show a disabled text editor when it is not activated.

**Comment by Hlavtox** [comment]
@prestascott

Sorry, I don't get your point... Additional arguments: 😄 

- The main description is also optional and you don't show any checkbox. You don't show any checkbox anywhere in prestashop.
- Required/Optional is solved by the red asterix in the label, isn't it? If you want to emhasize that something is optional, I would add "(optional)" to the label.
- Product descriptions are also optional and I don't think that users **think** that there will be an empty box, if they don't fill it.

**Comment by prestascott** [comment]
@Hlavtox 

I did user tests between different designs I made and most of all approved that it’s definitely useful to have a disabled text editor so they can read through it. They don’t have to switch the toggle to view content they wrote before.
In fact, we don’t have this same behaviour with the checkbox in PrestaShop but we have it with a toggle so we'll go for that solution for more consistancy.

This is my latest design proposition on the back office:

![solution 1](https://user-images.githubusercontent.com/54888056/78229838-cc6df800-74d0-11ea-8f26-d9053df19c3f.png)

**Comment by Hlavtox** [comment]
@prestascott 

So, tell me, why we don't have this toggle anywhere in Prestashop? 
**No toggle** in manufacturer admin - short description and long description.
**No toggle** in product admin - short description and long description. 

I believe you that it actually is user convinient, but have in mind, that majority of Prestashop merchants are power users. We don't want to scroll two pages to save a product, we don't want to do any other click than needed. If something is not clear, it takes one try and you will remember it forever, doesnt it?

I still don't understand `By doing that, users will think that if they leave the text editor blank, it will show an empty box like when your description box above is empty.`. That would be a shitty software if it showed empty box... 😄 It's one condition in the template, the same as everywhere.

**Comment by alexandrebru83** [comment]
Agree with your proposition Hlavtox, but without checkbox or switch, just if empty don't display the block like the main description.

**Comment by Hlavtox** [comment]
@alexandrebrubeyonds Man, of course it will not display. Like any other field in Prestashop. 👍

**Comment by alexandrebru83** [comment]
Yes of course. I talk about Prestascott´s proposition to add checkbox or switch

**Comment by Hlavtox** [comment]
@alexandrebrubeyonds Yeah, I disagree with Scott's proposition on that. There is no single field in Prestashop that would behave like that. It's clear that if the field is empty, it won't display... 😄

**Comment by MatShir** [comment]
The behavior describe by @prestascott would be the ideal, but it is true that we can change a behavior for a specific field and not to apply to every field. The BO now is not consistent enough, and we don't want to add another layer of inconsistencies.
