### ISSUE TITLE
[HOOK | IMPROVEMENT] Add a displayFooterCategory hook

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16628]
**Example use case**
A lot of modules need to show content under category and they have no other option than to hook to footer and append the content via JS.

**Solution**
Add a default {displayFooterCategory} hook under product list. Life will be easier for developers, code complexity lower and the page speed higher.

**Example - blog posts related to category**
![category](https://user-images.githubusercontent.com/6097524/69887542-c0d2b080-12e7-11ea-83af-f2d856563d61.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by colinegin** [comment]
Great idea ! I add it to our backlog.

Thanks @Hlavtox

**Comment by matks** [comment]
@Hlavtox What about the hook `displayWrapperBottom` ?  It's displayed under all sections.

https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/layouts/layout-both-columns.tpl#L92

It seems to be in the perfect location.

![Capture d’écran 2020-01-21 à 16 07 28](https://user-images.githubusercontent.com/3830050/72816380-547d8900-3c68-11ea-92bd-67cddafd6220.png)

**Comment by Hlavtox** [comment]
@matks Hi, it could work, but wouldn't look too nice if the left column is longer than the category content.

There was this hook in 1.6, I think it wouldn't hurt to add it back...

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/17410

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17410

**Comment by Hlavtox** [comment]
@matks Thank you boss 🍻

**Comment by web-plus** [comment]
Hello,

do you think you can add also displayHeaderCategory hook? It would be great for my module, which displays top sellers for each category.

Thank you!
