### ISSUE TITLE
linked orders 1.7.6.1

### ISSUE THREAD

**Issue by pnshurba** [PrestaShop/PrestaShop#16639]
I am using prestashop 1.7.6.1
![Снимок экрана 2019-12-01 в 12 58 33](https://user-images.githubusercontent.com/39360984/69912438-58e0af00-143a-11ea-8944-5baeb75e83f0.png)
![Снимок экрана 2019-12-01 в 12 58 26](https://user-images.githubusercontent.com/39360984/69912439-58e0af00-143a-11ea-91ab-9c408fd2fb85.png)

 but I don't find any useful information on linked orders how they created and how they can be resolved. Please, my attached screenshots of Prestashop. I complete one order from frontend but in admin panel, I can see two invoices against one order and they both contains each other's invoice ids please help me to solve this problem

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

Split order in two orders?
This issue of split orders.
In your case,
1. Do you have more than one carrier?
2. For product 1 which can be shipped to the customer's address => in the BO => Product details page => Shipping Tab => you have selected a specific Carrier?
3. For the product 2 which cannot be shipped to the customer's address => in the BO => Product details page => Shipping Tab => all carriers are available?
4. The product1 which has an order1 => the carrier select is carrier1?
5. The product2  which has an order2 => another carrier is selected?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
