### ISSUE TITLE
"Recalculate shipping costs after editing the order" does not update invoice

### ISSUE THREAD

**Issue by ziezo** [PrestaShop/PrestaShop#16637]
When the option "Recalculate shipping costs after editing the order" is set, the shipping cost is correctly recalculated when an order is modified.

If an invoice existed before modifying the order, the invoice is changed to match the modified order except for the shipping cost, which do not change on the invoice.

Tested on PS1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @ziezo,

I have the same issue with PS1.7.6.2.
But, when an order is made, I can change the customer information from the order page in the customer section. These changes update the invoice with the new information even after the invoices were sent to the customer. So a merchant can have different invoices for the same order which it's not legal.
It is not legal to change the invoice after a generation.
You can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/12394
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ziezo** [comment]
Hi @khouloudbelguith 

PrestaShop is not a certified accounting system. Not only the invoice addresses can be changed as noted in #12394 almost a year ago, pretty much anything can be changed after an invoice has been generated. You can change order amounts, add products, delete them, you name it - it is all reflected on the invoice. All except shipping cost changes, those are not copied to the invoice - very confusing to me...

Because of this non-accounting approach in PS we actually use the "invoice" as a quoting tool. We can make an offer to an customer, send them the pro-forma invoice. If he comes back for an order, we can adapt the order and "invoice" as needed and send things out. Very convenient actually.

So it would be great if the shipping cost recalculation is reflected on the invoice!

**Comment by matks** [comment]
Ping @MatShir I think you explored this question regarding invoices, legal requirements and accounting ?

**Comment by khouloudbelguith** [comment]
Hi,

Since this issue is closed, similar issue re-opened here: https://github.com/PrestaShop/PrestaShop/issues/16718

Thanks!
