### ISSUE TITLE
In supplier the language does not change on the whole page

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#16646]
**Describe the bug**
When I change language in area description, the change isn't apply to the whole page

**To Reproduce**
1. Go to back office 
2. Click on catalog -> brands & suppliers -> suppliers add new supplier
3. Switch language in the description area 

**Screenshots**
https://drive.google.com/file/d/1GIoKlFsVbOsoNjfeEUr6fniH24l1z-ts/view

**Additional information**
PrestaShop version: 1.7.7.

**Comment by matks** [comment]
Unfortunately this is a known issue 😢 and it works with all inputs of the same kind. **All inputs using tinyMCE WYSIWYG editor have this issue** because the "translatable" capability for tinyMCE is quite hacky ...

**Comment by MatShir** [comment]
@matks Could it be fixable? Why did it use to work?

**Comment by matks** [comment]
> @matks Could it be fixable? Why did it use to work?

I dont know if it ever worked before.

Yes, it's fixable, and fixing it will fix all usecases where we use tinyMCE translatable inputs. However it needs @NeOMakinG help, I cant do this one.

**Comment by Progi1984** [comment]
Fixed in #17444
