### ISSUE TITLE
Prestashop not compatible with PHP 7.3.12

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16649]
The admin panel is not really useable, when you use PS on PHP 7.3.12 - Some commands are not working propperly and the debug mode kills the whole Backend.

Screenshot: https://s19.directupload.net/images/191202/4rkoai9a.jpg

PrestaShop version: 1.7.5.1
PHP version: 7.3.12 (works fine on 7.2)

**Comment by khouloudbelguith** [comment]
Hi @1d0navan,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version.
