### ISSUE TITLE
[ORDER PAGE] Cancel products button

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#16650]
**User story**

As a merchant, I want to cancel my products or my orders before they are paid in case of an incorrect order. 

**Specs**

The cancel button only is shown by default on the creation of an order. 
The button **disappears** when the order is **considered as paid**

When pressing the button, the product list takes the full with of the page and the column cancel is added. 
On the column cancel, a checkbox and quantity input is displayed. Checking the checkbox will prefill the quantity input with the quantity of the product ordered.
The quantity input can still be editable.

Pressing the button cancel will reduce the quantity of the products selected if there still some left otherwise it deletes the product from the list.

![before cancel button](https://user-images.githubusercontent.com/43613217/69956873-85abc980-1501-11ea-9a02-33365caa01fe.png)

To cancel products at least one of the product must be selected.

**When all the products are canceled, the status automatically changes for "Canceled".**

**Comment by colinegin** [comment]
Hello @matthieu-rolland, do you confirm this feature is already managed by @Progi1984's PR ? https://github.com/PrestaShop/PrestaShop/pull/16150

**Comment by colinegin** [comment]
Dependent with #15820

**Comment by jolelievre** [comment]
@colinegin There is a slight difference between the feature in #16150 and this one, the first is just product removal (like an edition), the second one is more advanced and deals with product refund, restock, ... It's more like a refund than a delete

**Comment by colinegin** [comment]
Waiting for this final issue to be merged before starting making full tests for 1.7.7 release.
cc @SimonGrn @Robin-Fischer-PS @sarahdib

**Comment by Robin-Fischer-PS** [comment]
@MatShir Could you add in the spec that "The functionality is only available when merchandise return is activated" ? Thanks !
