### ISSUE TITLE
Notice: Undefined index:

### ISSUE THREAD

**Issue by muyncky** [PrestaShop/PrestaShop#16657]
**Describe the bug**
In [Order.php:944](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#L944) the index `id_order_state` is called. While the SQL-query mostly provides`current_state` index and sometimes `id_order_state`. This gives a notice, and it is difficult to work on the website with debugging mode on. 

**To Reproduce**
1. Turn on debugging
2. Go to a customer page (there, orders are loaded)

Changing the following lines solves the problem.

```
            $res[$key]['order_state'] = $indexedOrderStates[$val['id_order_state']]['name'];
            $res[$key]['invoice'] = $indexedOrderStates[$val['id_order_state']]['invoice'];
            $res[$key]['order_state_color'] = $indexedOrderStates[$val['id_order_state']]['color'];
```

to

```
            $res[$key]['order_state'] = $indexedOrderStates[$val['current_state']]['name'];
            $res[$key]['invoice'] = $indexedOrderStates[$val['current_state']]['invoice'];
            $res[$key]['order_state_color'] = $indexedOrderStates[$val['current_state']]['color'];
```

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1
Migration: Database upgraded from v1.6 with existing (test) orders and customers.

**Comment by khouloudbelguith** [comment]
Hi @muyncky,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.2 after an upgrade from PS1.6.1.24 with the 1-click upgrade v4.10.0.
I attached a screen record
https://drive.google.com/file/d/1BX5qXYyYkKn-ix5hiqcVhIUFCCzc1Nbz/view
Thanks to check & feedback.

**Comment by muyncky** [comment]
I think some of the records of `ps_order_history` are missing in my situation.

**To Reproduce**:
1. Delete all history of order 1: `DELETE FROM ps_order_history WHERE ps_order_history.id_order = 1`
2. Visit customer "John Doe" `id_customer = 1`

I know that the order history should not be incomplete, but it did happen to me without me doing anything special.

In that case, wouldn't it be better if we call `current_state` if `id_order_state` is not available. Like this:

classes/Order.php:943 till 947
```
        foreach ($res as $key => $val) {
            $res[$key]['order_state'] = $val['id_order_state'] ? $indexedOrderStates[$val['id_order_state']]['name'] : $indexedOrderStates[$val['current_state']]['name'];
            $res[$key]['invoice'] = $val['id_order_state'] ? $indexedOrderStates[$val['id_order_state']]['invoice'] : $indexedOrderStates[$val['current_state']]['invoice'];
            $res[$key]['order_state_color'] = $val['id_order_state'] ? $indexedOrderStates[$val['id_order_state']]['color'] : $indexedOrderStates[$val['current_state']]['color'];
        }
```
I thought about an if statement in the SLQ-query, but that is inefficient .. I think.

Maybe it's too much for solving a notice, I don't know ;-)

**Comment by khouloudbelguith** [comment]
@muyncky, I deleted, but it is OK.
https://drive.google.com/file/d/1w9npahqw9J86XgIBhilUxrmLUDUIX0JQ/view

Thanks!

**Comment by muyncky** [comment]
If you run this query `DELETE FROM ps_order_history WHERE ps_order_history.id_order = 1`, one more `order_history`, `id_order_history=6`, will be deleted.

**Comment by khouloudbelguith** [comment]
@muyncky, yes!
Now, we have an exception
https://drive.google.com/file/d/1WpCwUjfUfG3nSi5DsI7x8By0UUCTl8qs/view
but, in my case, this issue is reproduced only if I delete run those commands manually.
This is not logic.
IN your case, during the upgrade, the table ps_order_history is not well copied?

Thanks!

**Comment by muyncky** [comment]
Alright!

The upgrade went like this (with autoupgrade v4.9.0):
1. PrestaShop 1.6.1.3 upgrade to 1.6.1.24 (because upgrade to 1.7.x directly was not possible)
2. PrestaShop 1.6.1.24 upgrade to 1.7.6.1

Also, I have a module that changes the order history, but doesn't really delete it. This is the code:
```
                $history = new OrderHistory();
                $history->id_order = (int)$order_reference->getFirst()->id;
                $history->id_employee = (int)$this->context->employee->id;
                $history->changeIdOrderState(4, $order_reference->getFirst());
                $history->add();
```

I know it's abnormal! But things like this can still happen.

Can I request a file change for this?

**Comment by khouloudbelguith** [comment]
@muyncky, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`.
I think, that your module has an effect on the upgrade.
Because we recommend, in order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!

**Comment by muyncky** [comment]
Thanks!

> Can you please provide us the log of your upgrade?

[log.txt](https://github.com/PrestaShop/PrestaShop/files/3950221/log.txt) (for privacy reason some folders are changed, and company names are removed.)

> I think, that your module has an effect on the upgrade.

Possibly, but removing `order_history` records is a bit too far fetched in my opinion. Plus, there should always be a initial payment status. Later the module (custom made) makes the order "complete".

> remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production

All done.

**Comment by khouloudbelguith** [comment]
@muyncky, as I can see in your log file, the ps_order_history is well saved
`[2019-10-12 10:44:18] ps_order_history table has been saved.`
And the database successfully updated.
`[2019-10-12 10:45:02] Bijwerken database geslaagd`
So, `order_history` records are not deleted during the upgrade.

Thanks!

**Comment by muyncky** [comment]
I remembered something else. After the update I placed orders, which gave errors. So there was no status given to the orders.
Unfortunately, I cannot find the issue back in the log.

**Comment by khouloudbelguith** [comment]
Hi @muyncky,

Despite our several trials, we could not reproduce your issue with the provided information.
In my case, this issue is reproduced only if I delete run those commands manually.
This is not logic.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!
