### ISSUE TITLE
Remove conversion rates from localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16656]
**Is your feature request related to a problem? Please describe:**

Localization packs are here to provide to our merchants some essential information about a country. Among other elements, it contains the official currency used in the country and its conversion rate.

Yet, this data (which is constantly changing and that needs to be updated manually) is not used from localization packs but retrieved thanks to a daily-updated API elsewhere. So this information should simply be removed from all localization packs - and this way we could avoid brand new packs to contain this useless information.

**Describe the solution you'd like:**

Go in each localization pack in _[develop/localization](https://github.com/PrestaShop/PrestaShop/tree/develop/localization)_ and remove the official currency's conversion rates indicated.

**Comment by sam-pires** [comment]
@Progi1984 Needs to be done on localization file and then report it on PrestaShop
