### ISSUE TITLE
[ORDER PAGE] Standard Refund button

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#16653]
**User story**

As a merchant, I want to refund my orders to my customer before there are shipped in the case for order mistaken.

**Specs**

Standard refund only **appears when the merchandise returns are activated and the order is considered as paid** and **disappears when the order is considered as shipped.**

When the user presses the button a column "Refund" is added with a checkbox and the input quantity.

A quantity must be selected to refund a product. 

Before refunding the products, the user can choose to **generate a credit slip** and/or **voucher** and **repay the shipping costs** (option appears if you select generate a voucher or credit slip)

![before standard refund](https://user-images.githubusercontent.com/43613217/69959536-ad9e2b80-1507-11ea-9441-ec63cce2c0dd.png)

When all the products are refunded order status change to Refunded.
A product can't be refund multiple times. 

After refunding, it shows on a column "Refunded", the quantity and the price of the refund per products.

![after standard refund](https://user-images.githubusercontent.com/43613217/69959612-e211e780-1507-11ea-945a-934fe5441d37.png)

**Comment by matks** [comment]
Some exploratory work done by @zuk3975 :

The legacy button behavior was:
- reinjects product quanity (basically adds the refunded quantity back)
- deletes Product from order
- updates order carrier weight
- synchronizes stock
- deletes customizations (if selected )
- generates credit slips and vouchers (optional)

All of this is spread accross controllers.

So we need to
1. handle the interface behavior with javascript => probably similar to partial refund, so we should be able to reuse some parts or at least use it as an inspiration
2. make the backend work (see above)

Extra items to explore: if you press "standard refund" again on that order, then you can see a little icon which shows that you cannot select the same product for refund again

**Comment by MatShir** [comment]
One PR might work for this issue as well #16654, to study!

**Comment by MatShir** [comment]
@LouiseBonnard 
A suggestion about the name of the button, since the button affects only the products and the other button is called "Cancel products" and "Return products". We could rename it "Refund products". And then change the partial refund as the refund button. 
WDYT?

Wdty @matthieu-rolland as well now that you know everything about them? :wink:

**Comment by LouiseBonnard** [comment]
@MatShir, I'm afraid the wording itself is not enough to make the user understand all the actions induced by the button. I think there is a bigger UX rework to do, including both design and wording) and it is clearly too late to be part of the 1.7.7 scope...

Let's keep it iso for 1.7.7 and start working on it for 1.7.8, I'll schedule a meeting when you get back to share my notes. ;-)
