### ISSUE TITLE
Cart total quantity refresh issue

### ISSUE THREAD

**Issue by kexuejia** [PrestaShop/PrestaShop#16665]
**Description**
Cart total quantity not updated after adding or removing product from cart .
Issue appeared after update from 1.7.5.2 to 1.7.6.2

**To Reproduce**
1. Add product to cart from product page or quickview 
2. Click on Cart or Proceed to checkout 
3. Increase quantity for product on this page
![cart?action=show](https://user-images.githubusercontent.com/25119923/70031048-19899e00-15b3-11ea-8fb6-810e050591e5.png)
4. Amount for product updated, but on the top cart button quantity is not 
![Not updated cart](https://user-images.githubusercontent.com/25119923/70031372-c06e3a00-15b3-11ea-99df-f517e267c071.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @kexuejia,

I manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2 & ps_shoppingcart v2.0.3.
https://drive.google.com/file/d/1MUFgasEOKJ2X65scn8cXpVkGWujRNlNe/view
It was ok with ps_shoppingcart v2.0.2.
It is a module regression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by kexuejia** [comment]
seems module ps_shoppingcart.js receives wrong event.resp 
![event response is undefined](https://user-images.githubusercontent.com/25119923/70035066-e21eef80-15ba-11ea-9114-03a714d2ca15.png)
event has only reason, but resp is undefined
![log](https://user-images.githubusercontent.com/25119923/70035363-5eb1ce00-15bb-11ea-8416-69612c110fde.png)

**Comment by kexuejia** [comment]
on version ps_shoppingcart.js v2.0.2 no condition for event.resp 
![js](https://user-images.githubusercontent.com/25119923/70036226-0380db00-15bd-11ea-92e1-b4e9d7e97e52.png)

**Comment by khouloudbelguith** [comment]
Hi,

The same issue when we delete a product from the shopping cart, it is not updated.
![image](https://user-images.githubusercontent.com/16067358/70123403-e4448500-1672-11ea-9cca-7f352089a2a3.png)

Thanks!

**Comment by arouiadib** [comment]
> seems module ps_shoppingcart.js receives wrong event.resp
> ![event response is undefined](https://user-images.githubusercontent.com/25119923/70035066-e21eef80-15ba-11ea-9114-03a714d2ca15.png)
> event has only reason, but resp is undefined
> ![log](https://user-images.githubusercontent.com/25119923/70035363-5eb1ce00-15bb-11ea-8416-69612c110fde.png)

~~yes @kexuejia, I don't see why the test against `resp` was added in first `if`. I think the test should look like:
https://github.com/PrestaShop/ps_shoppingcart/pull/54
But if it is necessary to send `resp` in the emitted object, we can keep the module untouched and modify in theme:
https://github.com/PrestaShop/PrestaShop/pull/16892~~

The PR: https://github.com/PrestaShop/PrestaShop/pull/16948
@khouloudbelguith  @colinegin 
~~I hope someone help me decide between the two PRs, or guide me to create another PR with the appropriate approach~~

**Comment by khouloudbelguith** [comment]
Hi @arouiadib,

Thanks a lot!
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by zozo202600** [comment]
Hi,
we have the same issue. Do you know when it will be done from your side ?
Best Regards

**Comment by kexuejia** [comment]
> Hi,
> we have the same issue. Do you know when it will be done from your side ?
> Best Regards

I just downgrade  ps_shoppingcart  to v2.0.2.

**Comment by zozo202600** [comment]
> > Hi,
> > we have the same issue. Do you know when it will be done from your side ?
> > Best Regards
> 
> I just downgrade ps_shoppingcart to v2.0.2.

Can you send  the downgrade? What is the procedure please to downgrade to v2.0.2?

**Comment by khouloudbelguith** [comment]
Hi @zozo202600, you can follow this link: https://github.com/PrestaShop/ps_shoppingcart/releases

Thanks!

**Comment by zozo202600** [comment]
I tried to download it but i didnt success to install it, what is the procedure to downgrade to this version? How do i need to install it ?
Thank you in advance for your quick answer

**Comment by khouloudbelguith** [comment]
@zozo202600, thanks to check with this module cloned from GitHub
[ps_shoppingcart.zip](https://github.com/PrestaShop/PrestaShop/files/4117424/ps_shoppingcart.zip)

Thanks!

**Comment by zozo202600** [comment]
thank you very much it is finally working

**Comment by colinegin** [comment]
Fixed by #17074

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17633
