### ISSUE TITLE
Cart Price Rules not working when more than one setted

### ISSUE THREAD

**Issue by fra93ita** [PrestaShop/PrestaShop#16669]
Hi! After upgrading to 1.7.6.1 cart price rules won't work if more than one is setted, i'll explain better, if i set up two price rules to be active during same period, having products setted to combination and cart rule setted one to one type of combination(20% off) and the other combination has the same cart rule plus another one(like black fryday event)(20%+20%), when i do change combination the price of the main combination get changed in the database and it keeps changing (price seams to reduce by some soft of calculation based on the sales)at every refresh of the page; i've upgraded to 1.7.6.2 thinking that bug was fixed but it's still there; the only way i can set sales is via coupon code, if i do set those price rules from the product editing page, i get the same error( immo seams related to the templates, but even in debug mode i'm not able to identify the problem); since 1.7.6.1 update i get another error (access denied) going to the modules updates page, first i got redirected to the dashboard and going back to modules updates page i got access denied error, even if i've logged in to the addons.prestashop account.
What do you think about this? I'm the only one getting this type of error?

**Comment by khouloudbelguith** [comment]
Hi @fra93ita,

Can you confirm these steps:
1. Create a cart rule1
1.1 has no code
1.2 Condition: Restrictions => Product selection => Add an attribute `Color - White`
![image](https://user-images.githubusercontent.com/16067358/70060923-ac423100-15e3-11ea-8bd4-d6cb94d81e8a.png)
1.3 Actions: Apply a discount => Percent (20%)

2. Create a cart rule2
2.1 has no code
2.2 Condition: Restrictions => Product selection => Add an attribute `Size - S`
![image](https://user-images.githubusercontent.com/16067358/70061010-d693ee80-15e3-11ea-865f-8a20647b6ced.png)
2.3 Actions: Apply a discount => Percent (20%)

3. Go to the FO => add a product with `Color - White` & `Size - S` => cart rules are not well calculated?
![image](https://user-images.githubusercontent.com/16067358/70061134-0a6f1400-15e4-11ea-9f17-f2cedff9422d.png)

Thanks!

**Comment by fra93ita** [comment]
Ok you are talking about Basket Rules; making them in this way everything seams to work, but i was actually refering to Catalog Price Rules:
![screen1](https://user-images.githubusercontent.com/11248632/70102011-1fc15e00-1637-11ea-8fee-a275a817672b.PNG)
![screen2](https://user-images.githubusercontent.com/11248632/70102084-5bf4be80-1637-11ea-8b1d-7d6ff88f0700.PNG)
In my case i setting two rules that overlaps make the price change from this:
![screen6](https://user-images.githubusercontent.com/11248632/70102435-75e2d100-1638-11ea-921c-e3f488f09ffa.PNG)
One rule for a Home category (20% off) and one for a Size attribute 250ml 20% that i thinks should be 40% off on that products 
![screen3](https://user-images.githubusercontent.com/11248632/70102166-9cecd300-1637-11ea-990a-8ce8fe7019d9.PNG)
![screen4](https://user-images.githubusercontent.com/11248632/70102200-af670c80-1637-11ea-972f-6608c36b281c.PNG)
up there the original price, to this:
![screen7](https://user-images.githubusercontent.com/11248632/70102540-b80c1280-1638-11ea-9048-e4f53f405770.PNG)
![screen8](https://user-images.githubusercontent.com/11248632/70102581-d6720e00-1638-11ea-8c57-4f9a0e9ebf3d.PNG)
as you can see in the follows, loading category page, the visualized prices is somewhat committed 
![screen9](https://user-images.githubusercontent.com/11248632/70102640-0caf8d80-1639-11ea-80e3-1f3c1e0ea568.PNG)

**Comment by fra93ita** [comment]
Here is the product page view with debug mode enable:
![screen10](https://user-images.githubusercontent.com/11248632/70102790-80ea3100-1639-11ea-9f1c-e5a32968c719.PNG)
I've still havent explored that error

**Comment by khouloudbelguith** [comment]
@fra93ita, the behavior in PrestaShop is that The catalog price rules do not accumulate with each other.
For your case, You need just edit the second catalog price rule.
When you have a condition of size => change the percent discount to 40%
![image](https://user-images.githubusercontent.com/16067358/70132086-c29fc980-1683-11ea-8cd1-d50a2d2061c0.png)
It will be OK.
Thanks to check  & feedback.

**Comment by fra93ita** [comment]
Ok now template show correct value, but problem still occur, it mess up with price when i switch between combinations:
![screen1](https://user-images.githubusercontent.com/11248632/70192624-9ffdc700-16fc-11ea-920f-a73482a400f2.PNG)
![screen2](https://user-images.githubusercontent.com/11248632/70192655-bb68d200-16fc-11ea-9e72-ee8935c92763.PNG)

**Comment by khouloudbelguith** [comment]
@fra93ita,
>it mess up with price when i switch between combinations

In your case, 
1. first combinations => discount =40% => final price = 21.16-40%= 12.70
2. second combination => discount=20% => final price = 7.33-20%= 5.87

What is the exact problem with prices?

Thanks!

**Comment by fra93ita** [comment]
Price start from 29.90 and 17.90 not 21 or 7.3, and refreshing that page/changing combos(exactly when Page is loaded, on fronoffice obv) , lower the price more and change it permanentely on the database

**Comment by fra93ita** [comment]
I've tested a clean install, with default theme, and i don't get any errors, everythings wors as it should; so probably i have to explore the error on the theme (maybe after the update to 1.7.5 theme broke)

**Comment by fra93ita** [comment]
OK the problem it's only mine so we cannot consider it a bug; btw  if i do use the catalog price rules, setting the start price within the rule, everything works; if i choose "Leave the initial price" price starts messing on combination changing or page refresh
Edit: nevermind, when rule end, price show up changed with final values: initial price setted in the rules - sale %; damn, i dunno where to start (mybe i'll disable all overrides, and continue checking)

**Comment by khouloudbelguith** [comment]
Hi @fra93ita,

Thanks for your feedback.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
