### ISSUE TITLE
not receive email

### ISSUE THREAD

**Issue by storygram** [PrestaShop/PrestaShop#16676]
Hello,
I have a problem, the client does not receive an email when completing an order,
Please help.

**Comment by khouloudbelguith** [comment]
Hi @storygram,

Thanks for your report.
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email.
Thanks to check & feedback.

**Comment by storygram** [comment]
hello, I tried, I send an email and I receive nothing, I updated the platform to the latest version and now I receive the 500 Server Error

**Comment by storygram** [comment]
info_outline Informatii despre configuratie
Aceste informatii trebuie furnizate daca vei raporta vreo problema in modulul nostru de erori sau pe forum.

info_outline Informatii despre server
Informatii despre server Linux #1 SMP Thu Jun 20 11:00:35 EDT 2019 x86_64

Versiunea de software a serverului: LiteSpeed

Versiunea de PHP: 7.2.24

Limita de memorie: 512M

Timpul maxim de executie: 300

Limita maxima la incarcare de fisier: 256M

info_outline Informatii despre baza de date
Versiunea de MySQL: 10.2.27-MariaDB-cll-lve

Server MySQL: localhost

Baza de date MySQL: r67409ambi_pr144

Utilizator MySQL: r67409ambi_pr144

Prefix tabele: ps3o_

Motor MySQL: InnoDB

Driver MySQL: DbPDO

info_outline Informatiile magazinului
Versiunea de Prestashop: 1.7.6.2

URL magazin: http://www.ambientdecor.ro/

Calea magazinului: /home2/r67409ambi/public_html

Tema folosita acum: interior_th

info_outline Configurare e-mail
Metoda de e-mail: Folosesti functia PHP mail().

info_outline Informatiile tele
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

info_outline Verifica-ti configurarea
Parametri obligatorii: Da

Parametri optionali: Da

**Comment by OneDotIT** [comment]
Hello,
If you are having trouble with PHP function mail(), you could sign-up with an SMTP provider instead and let them handle the Email infrastructure.

> hello, I tried, I send an email and I receive nothing, I updated the platform to the latest version and now I receive the 500 Server Error

That seems to be a separate issue, what was the update procedure ? how did you update ??

**Comment by storygram** [comment]
we updated with the help of 1-Click Upgrade

**Comment by storygram** [comment]
can i give you ftp access data for verification?

**Comment by khouloudbelguith** [comment]
@storygram,

>I updated the platform to the latest version and now I receive the 500 Server Error

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by storygram** [comment]
this? *ERROR* v1.7.6.2 2019/12/04 - 10:51:13: Invalid category vars at line 388 in file classes/Link.php

**Comment by khouloudbelguith** [comment]
@storygram, did you use the module Megamenu?

Thanks!

**Comment by storygram** [comment]
No,just this ps_emailalerts

**Comment by khouloudbelguith** [comment]
@storygram,
The Schema of URLs is updated in your case?
By default, we have like this:
![image](https://user-images.githubusercontent.com/16067358/69727495-f37f7c00-1122-11ea-82de-58e168b09c0b.png)
Thanks!

**Comment by storygram** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by storygram** [comment]
![seo](https://user-images.githubusercontent.com/58422218/70145559-0c4edb00-16a9-11ea-8212-a44e1a08ef54.jpg)

**Comment by khouloudbelguith** [comment]
@storygram, issue closed?
Is it fixed?

Thanks!

**Comment by storygram** [comment]
no,no work

**Comment by storygram** [comment]
https://www.ambientdecor.ro/  no work :(

**Comment by khouloudbelguith** [comment]
@storygram, can you try to enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

Thanks!

**Comment by storygram** [comment]
PrestaShopException]
Invalid category vars
at line 388 in file classes/Link.php

**Comment by storygram** [comment]
I get another error, enter the site

**Comment by storygram** [comment]
![seo](https://user-images.githubusercontent.com/58422218/70146328-a06d7200-16aa-11ea-8b9d-f73771efb71a.jpg)

**Comment by khouloudbelguith** [comment]
@storygram, it is a `homefeatured` module issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by storygram** [comment]
what is the problem module?

**Comment by storygram** [comment]
now I get HTTP ERROR 500 again

**Comment by khouloudbelguith** [comment]
@storygram, 
![image](https://user-images.githubusercontent.com/16067358/70147753-34d4d600-16a5-11ea-8842-6339feb515a5.png)
It could be incompatible with PS version, you need to check the module author.
Thanks!

**Comment by storygram** [comment]
and do I have to get in touch with the installer theme installer?

**Comment by OneDotIT** [comment]
Hello,
The 500 is presented at the homepage, for example the inner-pages are working
https://www.ambientdecor.ro/produse-noi

I could see version 1.7.6.2 is the upgrade, but from which version did you update ? it might give as a clue.

I did a search about homefeatured https://github.com/PrestaShop/homefeatured, and it is the older version of ps_featuredproducts https://github.com/PrestaShop/ps_featuredproducts.
@khouloudbelguith seems to be correct, did you upgrade from version 1.6 ? You need to update the modules

**Comment by khouloudbelguith** [comment]
@storygram, you need to contact the module author
As I see, it is provided by `Prestahero`
![image](https://user-images.githubusercontent.com/16067358/70148332-3f439f80-16a6-11ea-8b9c-c58acace985a.png)

Thanks!

**Comment by storygram** [comment]
from this version PrestaShop 1.7.5
v2.4.1 , 
I also changed the theme compatible with this version

**Comment by storygram** [comment]
from here I bought the theme https://addons.prestashop.com/en/3-templates-prestashop

**Comment by khouloudbelguith** [comment]
@storygram, You should contact the module author via your addons.prestashop.com account.

Thanks!

**Comment by storygram** [comment]
ok,Thanks very much

**Comment by khouloudbelguith** [comment]
@storygram, I will close the issue, since it is not a PrestaShop module.
Thanks!

**Comment by storygram** [comment]
Hi,
I have configured SMTP Server, the client receives email notification, but I do not receive, what needs to be changed?

**Comment by khouloudbelguith** [comment]
@storygram,
- did you use the ps_emailalert? what is the exact version?
- Test your email configuration is well working? did you receive an email test?

Thanks!

**Comment by storygram** [comment]
the email configuration works, I could not install ps_emailalert receive the error in the image, now I have installed Email alerts
v2.1.1 - by PrestaShop

**Comment by storygram** [comment]
![11](https://user-images.githubusercontent.com/58422218/70218971-b2075600-174c-11ea-8577-b017c50ef2cf.jpg)

**Comment by khouloudbelguith** [comment]
@storygram, this module is installed from the Module Catalog page (option 1) or by uploading this module via the "install a module" button (option2)?
![image](https://user-images.githubusercontent.com/16067358/70219389-060e3c80-1745-11ea-9744-4fa4fdfaffef.png)

Thanks!

**Comment by storygram** [comment]
![11](https://user-images.githubusercontent.com/58422218/70219831-360e0d80-174e-11ea-92bf-cc8a3e40e925.jpg)

here I send my email? I want to receive an email notification when I receive a new order

**Comment by khouloudbelguith** [comment]
@storygram, yes!
It should work.
It is ok in my case.
![image](https://user-images.githubusercontent.com/16067358/70220766-5f776b00-1747-11ea-8d51-2c33d7036cea.png)

Thanks!

**Comment by storygram** [comment]
to me it does not work :(

**Comment by khouloudbelguith** [comment]
@storygram, the email address in your case
![image](https://user-images.githubusercontent.com/16067358/70223648-5341dc80-174c-11ea-9bb5-36a0bb997f44.png)
, is it the same for your address employee?

Thanks!

**Comment by storygram** [comment]
![11](https://user-images.githubusercontent.com/58422218/70224238-9bb1c800-1755-11ea-9c44-c6ece83b7cfa.jpg)

**Comment by khouloudbelguith** [comment]
@storygram, not this address mail
Employee address mail.
![image](https://user-images.githubusercontent.com/16067358/70224466-9c466080-174d-11ea-9d1e-dd91847e7e52.png)

Thanks!

**Comment by storygram** [comment]
![11](https://user-images.githubusercontent.com/58422218/70229930-dde00700-175f-11ea-876e-a69ff0ed7fcc.jpg)

**Comment by storygram** [comment]
is the same as in  ps_emailalert

**Comment by khouloudbelguith** [comment]
@storygram, it is the same.
I will re-open the issue.
I tried with PS1.7.6.2 & PS1.7.6.1 & ps_emailalert module v2.1.1 & it is OK.
New order mail is well received.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @storygram,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
