### ISSUE TITLE
Error during prestashop first installation of Prestashop 1.7.6.2

### ISSUE THREAD

**Issue by mg2812** [PrestaShop/PrestaShop#16680]
During the first clean installation of Prestashop version 1.7.6.2 on localhost have error:

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: Unable to write into "en-US"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer")

![image1](https://user-images.githubusercontent.com/7617391/70137551-37343180-169f-11ea-9ab5-6975dec9c644.JPG)
![image2](https://user-images.githubusercontent.com/7617391/70137553-37343180-169f-11ea-9c04-8167f1fa10a9.JPG)
![image3](https://user-images.githubusercontent.com/7617391/70137555-37ccc800-169f-11ea-8f90-bb53030006d2.JPG)

**Comment by khouloudbelguith** [comment]
Hi @mg2812,

I did not manage to reproduce the issue with PS1.7.6.2.
Thanks to check your directory permission.
In the meantime, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by mg2812** [comment]
Thank you for your replay.
I did new clean installation of Prestashop 1.7.6.2 and have the same error.
Php error log:
[04-Dec-2019 19:21:00 Europe/Moscow] PHP Warning:  file_put_contents(D:\OSPanel\domains\ps1762.ru/var/cache/prod\cacert.pem): failed to open stream: No such file or directory in D:\OSPanel\domains\ps1762.ru\classes\Tools.php on line 2118

After I close tab in Chrome and tried install again. I had next error:
![screen_1](https://user-images.githubusercontent.com/7617391/70161840-c3f5e400-16cd-11ea-915f-040403ebb50d.JPG)
Do you have any ideas?

**Comment by khouloudbelguith** [comment]
@mg2812, it is a permission issue.
>PHP Warning: file_put_contents(D:\OSPanel\domains\ps1762.ru/var/cache/prod\cacert.pem): failed to open stream

Thanks to check the permissions of your files.

Thanks!

**Comment by mg2812** [comment]
Thank you! Which permissions you mean. I try to install to localhost.
![screen_2](https://user-images.githubusercontent.com/7617391/70163071-dec95800-16cf-11ea-9773-fc116c0c624b.JPG)

**Comment by khouloudbelguith** [comment]
@mg2812, thanks to check the permission section in our official documentation: http://doc.prestashop.com/display/PS17/Installing+PrestaShop
![image](https://user-images.githubusercontent.com/16067358/70164083-d9b0dc80-16c0-11ea-808b-d67cb745f410.png)

Thanks!

**Comment by mg2812** [comment]
Thanks! But I try to install Prestashop 1.7.6.2 on my own computer with Windows 10. I am use Openserver with Apache + PHP 7.1 + MySQL-5.6, all files and folders are writeable. Prestashop 1.7.0.5 install without problem. Any ideas?

**Comment by khouloudbelguith** [comment]
@mg2812, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Give the right permissions & try to re-install again.
Thanks to check and feedback.

**Comment by mg2812** [comment]
Thanks! I did everything. All permissions right. Tha same error!!!
![70137551-37343180-169f-11ea-9ab5-6975dec9c644](https://user-images.githubusercontent.com/7617391/70242287-a1250780-1781-11ea-9db7-2a963391980a.jpg)

I check https://github.com/PrestaShop/PrestaShop/issues/14812 also, but no found any solutions.

**Comment by khouloudbelguith** [comment]
@mg2812, we need to retrieve errors in your file `/Project_folder/var/logs/` path.
Thanks!

**Comment by mg2812** [comment]
Php error logs:
[05-Dec-2019 16:48:51 Europe/Moscow] PHP Warning:  file_put_contents(F:\OSPanel\domains\ps1762.ru/var/cache/prod\cacert.pem): failed to open stream: No such file or directory in F:\OSPanel\domains\ps1762.ru\classes\Tools.php on line 2118
[05-Dec-2019 16:57:09 Europe/Moscow] PHP Warning:  PDO::query(): MySQL server has gone away in F:\OSPanel\domains\ps1762.ru\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 104
[05-Dec-2019 16:57:09 Europe/Moscow] PHP Warning:  PDO::query(): Error reading result set's header in F:\OSPanel\domains\ps1762.ru\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 104

Thanks!

**Comment by khouloudbelguith** [comment]
@mg2812, could you please check if the connection to MySQL and re-establish it if needed.
You can follow this link [PHP:mysqli_ping](https://www.php.net/manual/en/mysqli.ping.php) for info on that. 
Also, it could be a problem in `max_allowed_packet` in the `my.ini/my.cnf` file
Try to increase it & restart the MySQL service once you are done, you can follow this link: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet
Thanks to check & feedback.

**Comment by mg2812** [comment]
I did all your recomedation. Increase max_allowed_packet from 32M till 256M. But the same error!
PHP error logs the same:
[05-Dec-2019 19:24:58 Europe/Moscow] PHP Warning:  file_put_contents(H:\OSPanel\domains\ps1762.ru/var/cache/prod\cacert.pem): failed to open stream: No such file or directory in H:\OSPanel\domains\ps1762.ru\classes\Tools.php on line 2118
Thanks

**Comment by khouloudbelguith** [comment]
@mg2812, what is the exact language/country did you use during the install?
Did you download the zip folder from the official site? https://www.prestashop.com/en/previous-versions

Thanks!

**Comment by mg2812** [comment]
Yes, I downloaded from prestashop.com. Country: Russia, language: Russian, English. 
I use two shops with Prestashop 1.6.1. Never have problem with install. Also I no have problem and  error with Prestashop 1.7.5 install.

**Comment by mg2812** [comment]
I did new clean installation of Prestashop 1.7.5.2  Everything is OK. After  I tried upgrade to 1.7.6.2 be 1-Click upgrade module. I have nevt error:
[INTERNAL] H:\OSPanel\domains\ps1762.ru\src\Core\Data\Layer\AbstractDataLayer.php line 198 - PrestaShop\PrestaShop\Core\Data\Layer\DataLayerException: Unable to write into "ru-RU"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer") #0 H:\OSPanel\domains\ps1762.ru\src\Core\Data\Layer\AbstractDataLayer.php(102): PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->saveReadPropagationResult('ru-RU', Object(PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleData)) #1 H:\OSPanel\domains\ps1762.ru\src\Core\Localization\CLDR\LocaleDataSource.php(62): PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->read('ru-RU') #2 H:\OSPanel\domains\ps1762.ru\src\Core\Localization\CLDR\LocaleRepository.php(60): PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleDataSource->getLocaleData('ru-RU') #3 H:\OSPanel\domains\ps1762.ru\classes\Currency.php(826): PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleRepository->getLocale('ru-RU') #4 H:\OSPanel\domains\ps1762.ru\admin2812\autoupgrade\latest\install\upgrade\php\ps_1760_copy_data_from_currency_to_currency_lang.php(57): CurrencyCore->refreshLocalizedCurrencyData(Array, Object(PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleRepository)) #5 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #6 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader.php(395): call_user_func_array('ps_1760_copy_da...', Array) #7 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader.php(360): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') #8 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader.php(284): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...') #9 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.5.2') #10 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader.php(101): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.5.2') #11 H:\OSPanel\domains\ps1762.ru\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 H:\OSPanel\domains\ps1762.ru\admin2812\autoupgrade\ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

May be it is help you! Thanks and best reagards!

**Comment by khouloudbelguith** [comment]
@mg2812, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by khouloudbelguith** [comment]
PS: I tried to install PS1.7.6.2 with PHP7.1.33, with Russian language & Russia country => OK, no problem.

Thanks!

**Comment by mg2812** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3932130/log.txt)
Attached log.txt
Thanks!

**Comment by khouloudbelguith** [comment]
@mg2812, this issue is probably related to your server.
PHP Warning: file_put_contents(H:\OSPanel\domains\ps1762.ru/var/cache/prod\cacert.pem): failed to open stream` and the CLDR cache that is only in the cache

it looks like a problem related to your env, either of permission, or the path point where it should be, or lack of space.

Thanks!

**Comment by mg2812** [comment]
Thanks! But how can I fix this problem? How I told you error only witn 1.7.6 ver. Early ver. 1.7.5 install without errors. Also during installation process Prestashop 1.7.6  check system configuration and haven't error.
Thanks!

**Comment by khouloudbelguith** [comment]
@mg2812, thanks to check if you have enough space on your server.

Thanks!

**Comment by mg2812** [comment]
Thanks! I have enough spase 32Gb. I think something wrong with path, but how fix it?

**Comment by khouloudbelguith** [comment]
@mg2812, here's a [tuto](https://www.youtube.com/watch?v=cANFwuJqdgM&t=1s) to install PrestaShop step by step.
>I think something wrong with path

What is the exact path?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mg2812,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by augustu5** [comment]
@mg2812 try https://github.com/PrestaShop/PrestaShop/issues/16529#issuecomment-575635077
