### ISSUE TITLE
When I Install a new Language currency_lang values are not correctly set

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#16686]
**Describe the bug**
During installation the `currency_lang` values are not correctly set.

**To Reproduce**
I already have two languages in my shop (French, English), and two currencies (Euro, Dollar). And I have customization on one of them (let's say Euro).
If I install a new Language the currency_lang for the new Language are correctly added in the database, but their value are incorrect. They don't match the default value of the new language (name, symbol and pattern are not correct). It seems the data from the default language are copied in the other languages instead of using the CLDR data.

![Capture d’écran 2019-12-04 à 16 33 26](https://user-images.githubusercontent.com/13801017/70156181-d3683380-16b3-11ea-825f-11c96845e710.png)

If I go and edit the incorrect currency the symbol and pattern are a bit better (they still use the transformation used but at least they respect the language specification).

![Capture d’écran 2019-12-04 à 16 36 47](https://user-images.githubusercontent.com/13801017/70156498-512c3f00-16b4-11ea-8248-23e1cfd80579.png)

And if i use the 'Reset default settings' (on official currencies) the custom values are reset and the names are also correct.

**Solution**
All these behavior are logical from the form point of view, the issue is not on the form but on the Language installation. When a Language/Localization pack is installed the currency_lang should have correct values:
 - name: translated name of the currency (or ISO code for unofficial currency)
 - symbol: symbol from CLDR for the installed language
 - pattern: empty

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17373
