### ISSUE TITLE
Specific prices show "- 0 CZK" discount flag in product lists

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16684]
**To Reproduce**
1. Make a customer group 4. Make a customer, put him this group. Log in as this customer.
2. Set up a specific price for a product, as shown on a screenshot below. All currencies, all countries, just for user group 4.
3. Go to a category, where this product is assigned. See "-0 CZK" discount flag.

**Additional information**
PrestaShop version: 1.7.6.2

**Images**
![specific](https://user-images.githubusercontent.com/6097524/70154795-63f14480-16b1-11ea-91aa-25e35c35b514.JPG)
![specific0](https://user-images.githubusercontent.com/6097524/70154797-63f14480-16b1-11ea-9c3c-34da76442cc3.JPG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I think it is the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/16633.
Thanks to check & feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith No no it's different.

Just try to reproduce it as I said and you will see.
- Create another customer group. Go to FO, register on the store as customer. Go to BO, add customer to this group and set his default group to this group.
- Create product. Set price to 200. Assign it to some category.
- Create a specific price to this product, for customers from the group you created. Final price 100.
- Go to FO, to the category where you added the product, see the -0 EUR flag.

**Comment by khouloudbelguith** [comment]
@Hlavtox, I attached a screen record
https://drive.google.com/file/d/1QHPjVgKh-qgyjrluZuemghUFn2K--hpG/view
Thaks to check & feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith I am sorry for bothering you. The problem is in the template, not PS core.

I am using https://github.com/PrestaShop/classic-rocket and there is a bug in a template. In classic theme, the code for displaying these flags are wrapped in `{if $product.has_discount}`. This condition is missing in classic-rocket. @prestarocket 

![classic](https://user-images.githubusercontent.com/6097524/70242910-f78a4a00-1771-11ea-9660-4ea0f40496dc.JPG)

**Comment by Hlavtox** [comment]
@prestarocket made a PR https://github.com/PrestaShop/classic-rocket/pull/119

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme, they are the only ones to help you with it.
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith On one side, yes.

But on the other side, you took the theme under your wings and it's in your repo... :-)
https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points

**Comment by khouloudbelguith** [comment]
@Hlavtox, you need to create an issue in the theme repository.
https://github.com/PrestaShop/classic-rocket/issues
Thanks!
