### ISSUE TITLE
Logo doesn't appears in pdf

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#16683]
Hello,

Logo is correctly added in admin for order and mails. But doesn't display in PDF (order, ..). It seems that {logo_path} in pdf -> header.tpl doesn't work. If I get the link to the logo manually (https://name_of_website/img/name_of_logo.jpg) in thie tpl, it's ok, the logo is displayed.

PS 1.7.5.2

Thanks

**Comment by khouloudbelguith** [comment]
Hi @sirius82,

It is the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/15088
As you can see the PR is closed: https://github.com/PrestaShop/PrestaShop/pull/15109 because of self signed certificate (Not working with TCPDF).
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @sirius82,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
