### ISSUE TITLE
Error in form_shipping.html.twig 

### ISSUE THREAD

**Issue by pyp31** [PrestaShop/PrestaShop#16695]
**Describe the bug**
At line 156 of the file /src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_shipping.html.twig : 
```
{{ include('@PrestaShop/Admin:Product/ProductPage/Forms/form_warehouse_combination.html.twig', { 'warehouses': warehouses, 'form': form }) }}
```
to work it is necessary to replace":" by" /"
```
{{ include('@PrestaShop/Admin/Product/ProductPage/Forms/form_warehouse_combination.html.twig', { 'warehouses': warehouses, 'form': form }) }}
```
**To Reproduce**

this error appeared in the BO product management
with advanced stock management activated

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

EDITED by @matks: [see below](https://github.com/PrestaShop/PrestaShop/issues/16695#issuecomment-791514517)

**Comment by khouloudbelguith** [comment]
Hi @pyp31,

Thanks for your report.
Can you please add steps to reproduce the issue in a new comment.
In your BO => Shop Parameters => Product Settings page => is there any exception after enabling "stock management"?

Thanks!

**Comment by pyp31** [comment]
there is no exception in 
BO => Shop Parameters => Product Settings page =>

exception is in 
 BO => Catalog => Product when you select a product or add a new product

error is in debug 
Template "@PrestaShop/Admin:Product/ProductPage/Forms/form_warehouse_combination.html.twig" is not defined.

**Comment by khouloudbelguith** [comment]
@pyp31, I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/109DpTn1KJG3874yhMFVbQyNtMOp1274j/view
PS: Stock management is enabled by default.

Thanks!

**Comment by pyp31** [comment]
I guess it's because I use a module that uses this file maybe wkwarehouse.
in all cases this file contains an error ( typing), we have to replace  : by /

https://drive.google.com/open?id=1k-LbH_YwMIEIa6HxDDHs1EYdBp6bVk76

Regards

**Comment by khouloudbelguith** [comment]
@pyp31, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by GuillaumeEqui-Clic** [comment]
If you want to reproduce this bug:
in table ps_configuration, PS_ADVANCED_STOCK_MANAGEMENT value 1

If you go to a product page then the include is called.

You have this error : 
CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Template "@PrestaShop/Admin:Product/ProductPage/Forms/form_warehouse_combination.html.twig" is not defined."

Because the link is false, the link should be : 
@PrestaShop/Admin/Product/ProductPage/Forms/form_warehouse_combination.html.twig

**Comment by khouloudbelguith** [comment]
Hi @marketiweb85,

>If you want to reproduce this bug:
in table ps_configuration, PS_ADVANCED_STOCK_MANAGEMENT value 1

But this is will be incorrect, we cannot edit the database to reproduce an issue.
We need to find the exact steps to reproduce the issue from the BO or FO.

Thanks!

**Comment by GuillaumeEqui-Clic** [comment]
As you wish, but this is just a typo. The person wanted to write / and wrote :

**Comment by dandumit** [comment]
Thank you very much @pyp31  !!! You saved me ! I cannot believe that this error it's still present even now and no one it's fixing it.
It's a simple fix. I have hit this because I have migrated from 1.6.1.8 to 1.7.7.1 and probably it's because I have used to have advanced stock activated  !
Daniel

**Comment by matks** [comment]
Hi @marketiweb85 I have checked and you're right 😉  would you submit a PR with your fix to be credited?

@khouloudbelguith PS_ADVANCED_STOCK_MANAGEMENT is an option that comes from PS 1.6 . In PS 1.7 we cannot activate it, but if a shop upgrades from PS 1.6 to PS 1.7.7 it might have this option enabled.

So I think here we can accept the following steps:

1. Install PS 1.7.7
2. Open MySQL base, in table ps_configuration, modify `PS_ADVANCED_STOCK_MANAGEMENT` value to 1
3. Open a Product page.
4. Enable stock management for this product
![Capture d’écran 2021-03-05 à 17 00 31](https://user-images.githubusercontent.com/3830050/110140860-d715c900-7dd4-11eb-911f-242426b7d223.png)

5. See the error

And @marketiweb85 there's a typo, if we fix the typo it is fixed!

**Comment by dandumit** [comment]
This is still persistent in 1.7.7.8 . please merge it properly since it's annoying
