### ISSUE TITLE
Add product doesn't work

### ISSUE THREAD

**Issue by deshiloh** [PrestaShop/PrestaShop#16692]
Hi ! 
I have a problem when i want to create a new product. 
When i submit the form only with title, the page is refresh and i have no confirmation message that said that the product was created, and the product is not created. When i try the second time it works. 

What could possibly go wrong ? 

Thanks

**Comment by khouloudbelguith** [comment]
Hi @deshiloh,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by deshiloh** [comment]
Thanks and sorry for that ^^

Server : Apache/2.4.7 (Ubuntu)
PHP : 5.6.20-1+deb.sury.org~trusty+1
MySQL : 5.5.47-0ubuntu0.14.04.1
Prestashop version : 1.6.1.6

When the dev mode is set to false i have to error message in logs etc. 
When the dev mode et set to true : i have the js error message : 

`VM1896 jquery.validate.js:2 Uncaught TypeError: Cannot read property 'settings' of undefined
    at Function.staticRules (VM1896 jquery.validate.js:2)
    at e.fn.init.rules (VM1896 jquery.validate.js:2)
    at HTMLInputElement.<anonymous> (VM1896 jquery.validate.js:2)
    at VM1858 jquery-1.11.0.min.js:2
    at Function.grep (VM1858 jquery-1.11.0.min.js:2)
    at x (VM1858 jquery-1.11.0.min.js:2)
    at e.fn.init.filter (VM1858 jquery-1.11.0.min.js:2)
    at t.validator.elements (VM1896 jquery.validate.js:2)
    at t.validator.checkForm (VM1896 jquery.validate.js:2)
    at t.validator.form (VM1896 jquery.validate.js:2)
staticRules @ VM1896 jquery.validate.js:2
rules @ VM1896 jquery.validate.js:2
(anonymous) @ VM1896 jquery.validate.js:2
(anonymous) @ VM1858 jquery-1.11.0.min.js:2
grep @ VM1858 jquery-1.11.0.min.js:2
x @ VM1858 jquery-1.11.0.min.js:2
filter @ VM1858 jquery-1.11.0.min.js:2
elements @ VM1896 jquery.validate.js:2
checkForm @ VM1896 jquery.validate.js:2
form @ VM1896 jquery.validate.js:2
(anonymous) @ VM1896 jquery.validate.js:2
dispatch @ VM1858 jquery-1.11.0.min.js:3
r.handle @ VM1858 jquery-1.11.0.min.js:3
`
In dev mode all works well.

**Comment by khouloudbelguith** [comment]
@deshiloh,

I did not manage to reproduce the issue with PS1.6.1.24 & PS1.7.6.2.
https://drive.google.com/file/d/1cqR4vEDzCEdzyQC5TqzF3gXNz9_twwcs/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
I will close the issue, thanks!
