### ISSUE TITLE
Email alert 

### ISSUE THREAD

**Issue by Carlo-Vernetti** [PrestaShop/PrestaShop#16694]
I don't get a warning email when someone signs up on my site. 
I've got PS 1.7.5.2
thank you

**Comment by khouloudbelguith** [comment]
Hi @Carlo-Vernetti,

By default, if a new customer is registered, the employee will receive a notification in his BO by enabling this option in the BO => Advanced Parameters => Administration page
![image](https://user-images.githubusercontent.com/16067358/70215619-271f5f00-173e-11ea-98a1-c2ac2b561ccc.png)
But receiving an email, you can check our addons Market place: https://addons.prestashop.com so you can find a lot of modules to get an email when a new customer gets registered in your store, for example, this module: https://addons.prestashop.com/fr/emails-notifications/25863-get-email-when-customer-register-or-login.html

PS: the ps_emailalerts module provided by PrestaShop has no option to "mail" merchant about new user registration

![image](https://user-images.githubusercontent.com/16067358/70215954-e6741580-173e-11ea-8f2f-53ca6afe4b75.png)

Thanks!
