### ISSUE TITLE
BO link excl. /index.php/ in path

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#16707]
Currently the PS BO link looks like:
```
http://localhost/ps/pslrel18/adminX/index.php/configure/advanced/system-information/?_token=...
```
but `index.php` is well known as "redundand" and it may be misleading even in this context where it can not be normally stripped (as the following character after `index.php` is `/` and not `?`)

consider changing the URL generator and routing to format excl. the `/index.php/` part in the path like:
```
http://localhost/ps/pslrel18/adminX/configure/advanced/system-information/?_token=...
```

Currently there is also an issue as the default BO homepage URL looks like `http://localhost/subdir/admin-dev/index.php?controller=AdminDashboard&token=...`, but if the `index.php` part is removed (which should well behaved code allow, as this routing is trully based on autoindex, as the `index.php` is follwed by `?`), then the BO link does not contain the `/index.php/` part which seems currently required - i.e. the link does not work.

**This issue should resolve not adding the "index.php" by default (added for example when you log in) once the issue https://github.com/PrestaShop/PrestaShop/issues/16631 is resolved.**

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

In my case, the URL of the information page is `https://prestashop.tn/ps/ps_17/admin-dev/configure/advanced/system-information/?_token=`, there is no `index.php`, this page is migrated to Symfony, it is different from the dashboard page.
>then the BO link does not contain the /index.php/ part which seems currently required - i.e. the link does not work

No, it is well worked in mu case

I attached a screen record
https://drive.google.com/file/d/10NDib4mj7WG4HCHiH3pxsym-qbi63-8F/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
