### ISSUE TITLE
The Attribute-> name property is empty.

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#16703]
Hello, 

I am very stuck on the last importation of my sheets... I want to export this sheet as product variants 

[importvariants.xlsx](https://github.com/PrestaShop/PrestaShop/files/3926778/importvariants.xlsx)

Here is what I got... The Attribute-> name property is empty.

![image](https://user-images.githubusercontent.com/39828779/70235164-9d35bd00-1762-11ea-8089-a700b6556182.png)

![image](https://user-images.githubusercontent.com/39828779/70235024-492ad880-1762-11ea-878d-513087ea171b.png)

I use last version Prestashop 1.7.6.2 and PHP 7.2

If you want here are my other sheets to reproduce my catalog:
-> categories [import_categories.xlsx](https://github.com/PrestaShop/PrestaShop/files/3926797/import_categories.xlsx)
-> products [import_products.xlsx](https://github.com/PrestaShop/PrestaShop/files/3926795/import_products.xlsx)

**Comment by khouloudbelguith** [comment]
Hi @Dupflo,

I tried with your first file,
You have incorrect lines at the end of the files
For example "Colonne 1"
![image](https://user-images.githubusercontent.com/16067358/70245068-c6ac1400-1775-11ea-8ebf-2f16bcd8e353.png)
![image](https://user-images.githubusercontent.com/16067358/70245108-d6c3f380-1775-11ea-8c76-397be71911b3.png)
I tried with the first lines & they are well imported
[com.xlsx](https://github.com/PrestaShop/PrestaShop/files/3927384/com.xlsx)

Thanks to check & feedback.

**Comment by Dupflo** [comment]
@khouloudbelguith 

I update it and still not working ...
[variants.xlsx](https://github.com/PrestaShop/PrestaShop/files/3927880/variants.xlsx)

**Comment by Dupflo** [comment]
I did my best to update with only what I needed and still not working..
[importvariants.xlsx](https://github.com/PrestaShop/PrestaShop/files/3927965/importvariants.xlsx)

**Comment by Dupflo** [comment]
Looks like color is not imported

**Comment by khouloudbelguith** [comment]
@Dupflo, I think, that there is aline not good.
As I said I tried with this file 
[com.xlsx](https://github.com/PrestaShop/PrestaShop/files/3928133/com.xlsx) & it is ok

thanks to try to import the combinations of the 25 first products, check & feedback.

**Comment by Dupflo** [comment]
It works ... so somme value in my full document are wrong, which column do you think can be wrong according to the error ?

**Comment by Dupflo** [comment]
I got it ! Finally after looking for some empty space

**Comment by khouloudbelguith** [comment]
@Dupflo, great!
Feel free to open a new one when needed.

**Comment by hr194** [comment]
Hi,

can you please help me

 

Test Pro (ID: No ID) cannot be saved

Property Product->name is empty

these errors are annoying me
