### ISSUE TITLE
[IMPROVEMENT] Flush var/cache automatically after moving prestashop install

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16715]
**Why I opened this**
I was moving my Prestashop install from a test subdomain to a live folder and had a little bit of trouble with cache.

I couldn't access some page in admin due to cache issues, than I tried to delete the cache by FTP, but there are thousands of files and it started to cache itself again in the middle of the process. Then it started the caching to the original folder I moved it from and all sorts of weird stuff.

**Could this be done?**
Prestashop would check on "startup" if the folder is still the same? And if not, then automatically flush whole var/cache?

In the end, I made myself a little script to flush it, but it would save others the headache, what do you think?

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

To move a Project to a new domain without errors, we need to follow these steps:
1. made a backup for my files & my database
2. upload the store's files to the new server
3. import the old store's database to the new server
4. In file /app/config/parameters.php, configure the my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in the Table ps_shop_url, change with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. clear cache manually by deleting all the folder into var/cache (prod & dev) => could solve your issue

The last step is important to delete all cache.
Your improvement to execute the last step automatically isn't?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Exactly, because it takes incredibly long to delete it by an FTP client. PHP can do it in like 1 second 🎉.

And if somebody tries to open the FO or BO, you can start again and the cache is a mix of old cache and new cache and it does all kinds of weird stuff.

**Comment by khouloudbelguith** [comment]
@Hlavtox, ok thanks for these clarifications.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by colinegin** [comment]
Hello @PrestaShop/prestashop-core-developers what do you think ?

**Comment by PierreRambaud** [comment]
We already have a `Clear Cache` button is the BO
![image](https://user-images.githubusercontent.com/1462701/70439329-0c2b5280-1a90-11ea-8bad-4fde75ec835a.png)

More if you copy all your directories into a new one (with FTP) be sure to don't copy the var/cache directory.
I think this behaviour is useless and will consume memory for a very very small part of Prestashop's users.

**Comment by Hlavtox** [comment]
@PierreRambaud You mean the button that doesn't work? 😄 

```
if (currentdir != lastdirfromconfig) {
    flushCache();
}
```

Execution time will not even be measurable and memory... like 60 bytes?

**Comment by PierreRambaud** [comment]
@Hlavtox If you want to check if the directory isn't the same, you need to do a checksum on the directory content. If as me you configure your preproduction like your production server (and every other system administrator), the path remains the same.
Maybe it's time to simply don't copy the `var/cache` directory when playing with FTP :thinking:

**Comment by Hlavtox** [comment]
@PierreRambaud I didn't mean content comparing. Just if the path is the same.

I had the dev install on a subdomain, then I just swapped the folder names.

Nevermind, if you think it's useless, you can close it.

**Comment by PierreRambaud** [comment]
@Hlavtox I'm sorry but I think yes, it will cost memory, because the data must be stored somewhere, and to be properly executed, it must check the checksum of the directory, not only the path (more because of integration / preproduction / production logic).

**Comment by Hlavtox** [comment]
@PierreRambaud Getting back to this. I started this thread because stuff like this: https://github.com/PrestaShop/PrestaShop/issues/18535#issuecomment-611675731

I understand that advanced system administrators can handle this, but personally, I don't know anybody who would run Prestashop on a dedicated server. Who uses Prestashop? People who want to save money (at least they think they will do from the beginning), and these people run it on shared hostings. You just get your FTP access and here you go. Like 50% of all Prestashop installs I see run the default theme, maybe with changed colors.

Can you brief me in, why would you want to compare the checksums of the directories? My idea, originally, was something like this:

```
if ($pathfrompsconfig != $currentpath) {
      flushCache();
}
```
