### ISSUE TITLE
Error - Unclear alert when adding a profile's name more than 32 chars

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16725]
**Describe the bug**
 Unclear alert when adding a profile's name more than 32 chars

**To Reproduce**
1. Go to BO => Advanced Parameters => Team => Profiles
2. Create a profile with a name more than 32 chars
3. Save

With PS1.7.5.2, it was very clear
![image](https://user-images.githubusercontent.com/16067358/70320110-2eb93380-1824-11ea-92c1-2e272efabe16.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/70320136-409ad680-1824-11ea-9036-a1601bd115e2.png)

**Additional information**
PrestaShop version: 1.7.6.2, 1.7.6.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
This is a critical issue because it breaks the automatic test.
Related to https://github.com/PrestaShop/PrestaShop/issues/16514

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by khouloudbelguith** [comment]
Nightly is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16727

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16906
