### ISSUE TITLE
SMTP problem

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16728]
I try to send emails via SMTP. I set up all config in setting and when i make Email config test its works well but when i go to Design -> Email Theme -> send a test mail i get "Cannot send test email for layout layout_name"

PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @simon12q,

I did not manage to reproduce the issue with PS1.7.6.2 & PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/70325134-95911980-1831-11ea-85b7-c0cef3b3fe8e.png)
The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check with your host & feedback.

**Comment by ghost** [comment]
@khouloudbelguith ok but now try test via Design -> Email Theme -> Email Themes -> modern
For example 'account' layout -> Send a test email
![test email faild](https://i.imgur.com/ATa0Xsr.jpg)

**Comment by khouloudbelguith** [comment]
@simon12q, it is well working if SMTP is well configurated.
https://drive.google.com/file/d/1p8TDKUydNeIkMqboYzUcGWETJBZyEjId/view

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith ok thank you.
SMTP looks ok becouse "Test your email configuration" works well for me but other not.
So probably it is some problem with my server.

**Comment by khouloudbelguith** [comment]
@simon12q, you are welcome!
Feel free to open a new one when needed.

Thanks!
