### ISSUE TITLE
Missing chart in Shop Search stats for new employees

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#16730]
**Describe the bug**
The pie chart in the _Shop Search_  tab in the Stats page does not appear on BO of a new employee.
Even with all permissions enabled or with the SuperAdmin profile.

**To Reproduce**
Steps to reproduce the behavior (a shorter way probably exists):
1. Go to 'Team'
2. Create a new profile with all permissions enabled
3. Create a new employee, assign it the new profile you created
4. Connect to the BO with the new employee credentials
5. (**If on a fresh install**) Go to the Front-Office and use the search with a couple of keywords, do at least twice a search with each word -> to generate search stats
6. Go to Stats > Shop search and see the missing pie chart - Make sure the period includes today
7. you can try to set the profile of the employee to SuperAdmin, the result is the same

**Screenshots**
On the initial SuperAdmin employee account
![Capture d’écran 2019-12-06 à 15 03 10](https://user-images.githubusercontent.com/25405887/70330553-18b86c80-183e-11ea-9293-78a047c024f1.png)

On the newly created employee account (all permissions enabled or SuperAdmin)
![Capture d’écran 2019-12-06 à 15 03 20](https://user-images.githubusercontent.com/25405887/70330819-97ada500-183e-11ea-8db9-338e605283b4.png)

**Additional information**
On the new employee profile, when accessing the "Shop Search" tab, the page keeps loading for unlimited time (at least 10 minutes and still loading in my case)(see screenshot)

Might be related to #13178

PrestaShop version: 1.7.6.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @sam-pires,

It is a regression.
With PS1.7.5.2 => OK
https://drive.google.com/file/d/18F9hBYhAImbneipqXKZYyY96El1n55Uu/view
I have the same issue with PS1.7.6.0 & PS1.7.6.2.
I’ll add this to the debug roadmap.
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16746
