### ISSUE TITLE
Asset registering by theme.yml is not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16749]
Tried to register a custom CSS using the documentation.
https://devdocs.prestashop.com/1.7/themes/getting-started/asset-management/

Added the code to theme.yml
![Výstřižek](https://user-images.githubusercontent.com/6097524/70460901-ae126580-1ab7-11ea-9fb9-cd4fc52cbee8.JPG)

File exists
http://eshop-teka.cz/themes/trendo/assets/css/colors.css

**But it's not loading. Tried to completely delete the cache, still nothing.**

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by kpodemski** [comment]
Have you tried to delete folders in /config/themes/? these are cached .yml files

**Comment by Hlavtox** [comment]
@kpodemski Then the store stops working. Tried to delete cache but still the same error :-/

![not working](https://user-images.githubusercontent.com/6097524/70461271-938cbc00-1ab8-11ea-8908-1eea28edb0d2.JPG)

**Comment by kpodemski** [comment]
@Hlavtox it's not normal behavior :) .yml files have nothing to do with loading catalog files

**Comment by Hlavtox** [comment]
@kpodemski When I put back the json file, the site started working just fine.

Strange... 🤷🏽‍♂️

**Comment by Hlavtox** [comment]
@kpodemski I added it manually to the json file and it works! ;-) Thank you

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox, @kpodemski,

We have an improvement added to our bug roadmap about the theme.json to be deleted when cache is cleared: #13558 
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith So you think it will fix even this issue with the error? If so, good!!!

Do you think it would work when I deactivate and activate the theme again? I didn't want to do it, because it changes the active hooks.

**Comment by khouloudbelguith** [comment]
@Hlavtox, you need just to delete the json file to fix your issue now.

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith I tried to do it after @kpodemski advice, but it threw the error I posted above. 🤷🏽‍♂️ Finally, I added the strings to the compiled json file and it started working.

**Comment by matks** [comment]
Thank you @kpodemski
