### ISSUE TITLE
AdminSpecificPriceRule clears smarty cache on every page load.

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#16744]
**Describe the bug**
AdminSpecificPriceRule controller has the following code
```
public function postProcess()
{
      Tools::clearSmartyCache();
      return parent::postProcess();
}
```

this code runs on every page load of that controller and cause the smarty cache to be rebuilt. the part Tools::clearSmartyCache(); needs to have a condition so it only gets rebuilt if needed.

**To Reproduce**
1. Go to the AdminSpecificPriceRule in the backoffice.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Thanks for your report.
The Catalog price rule in the PS1.7.7 version was migrated to Symfony
Here's the new controller: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CatalogPriceRuleController.php
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
