### ISSUE TITLE
Tax included price shows wrong price (excluded price)

### ISSUE THREAD

**Issue by Speedycobra** [PrestaShop/PrestaShop#16752]
**Describe the bug**
Tax included price shows wrong price (excluded price)
I have applied tax rule IVA ES 21% on my shop. But on front office, tax is not applied. Even I have set tax included price to show from backofficec. Can anyone help me?
In the back office there is 131.404958 as tax excl. and 158.999999 as tax incl. but it shows me  131.404958 as tax incl.

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/33927215/70520214-7b12b500-1b3d-11ea-83cb-e37f58457d33.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.3.12

**Comment by khouloudbelguith** [comment]
Hi @Speedycobra,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version, check and feedback.

**Comment by Speedycobra** [comment]
Hi @khouloudbelguith 
have downgraded to PHP version: 7.2.25 and still get the same results !!

**Comment by khouloudbelguith** [comment]
@Speedycobra, the tax rule `IVA ES 21%` is applied to all countries?

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith 
no it is not .. have several tax rules active ... IVA ES 21% is set on product 
</br>
![Skärmklipp4](https://user-images.githubusercontent.com/33927215/70525891-9f27c380-1b48-11ea-93a9-c2e0c4fc5248.JPG)

![Skärmklipp2](https://user-images.githubusercontent.com/33927215/70525014-acdc4980-1b46-11ea-9599-c22327d0cc33.JPG)

**Comment by khouloudbelguith** [comment]
@Speedycobra, in your BO => International => Taxes => Tx rules page => when you edit this Tax rule, is it enalbled for all countries?
![image](https://user-images.githubusercontent.com/16067358/70525928-b6ff4780-1b48-11ea-8a5d-d136ab2f8f04.png)

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith  no it wasent ... but it is now and still same results
![Skärmklipp5](https://user-images.githubusercontent.com/33927215/70526401-c5019800-1b49-11ea-89c2-8cacc864fb21.JPG)

**Comment by khouloudbelguith** [comment]
@Speedycobra, did you use the module VAT number?

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith no I havent ... if European VAT number Module is what you are reffering too

**Comment by khouloudbelguith** [comment]
@Speedycobra, are you navigating into the FO as a visitor/guest or customer?

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith I have tried both ways logged in as customer and as guest / visitor no changes
</br>
Thanks!

**Comment by khouloudbelguith** [comment]
@Speedycobra,
Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith 
an email is sent with link and login 

Thanks!

**Comment by khouloudbelguith** [comment]
@Speedycobra, I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@Speedycobra, in your case, only visitors can see 
Included Taxes = 0Euro, Geolocalisation enabled
If Geolocalisation is disabled => Included Tax <>0
Customers => Included Tax <>0

Thanks!

**Comment by Speedycobra** [comment]
@khouloudbelguith 
Thank you for help !!

**Comment by khouloudbelguith** [comment]
@Speedycobra,

Thanks!
Feel free to open another one when needed.
