### ISSUE TITLE
Update Specific Price Rule Via Api Does not Trigger apply Rule To Product

### ISSUE THREAD

**Issue by sanctusmob** [PrestaShop/PrestaShop#16751]
I am updating a price rule by changing only the "FROM" and "TO" date via Web Service. After this does not Trigger the apply Rule To Product so the table specific_price to be updated. 

The specific price rule
`"2"	"Happy Hours"	"1"	"0"	"0"	"0"	"1"	"-1,000000"	"12,000000"	"1"	"percentage"	"2019-12-10 20:55:00"	"2019-12-11 08:55:00"`

two of the product with the specific price 

```
"753744"	"2"	"0"	"75"	"1"	"0"	"0"	"0"	"0"	"0"	"0"	"-1,000000"	"1"	"0,120000"	"1"	"percentage"	"2019-12-09 20:55:00"	"2019-12-10 08:55:00"
"753745"	"2"	"0"	"85"	"1"	"0"	"0"	"0"	"0"	"0"	"0"	"-1,000000"	"1"	"0,120000"	"1"	"percentage"	"2019-12-09 20:55:00"	"2019-12-10 08:55:00"
```

the date values are not updating in specific price.

PrestaShop version: 1.7.5.1
PHP version: 7.2.25

**Comment by khouloudbelguith** [comment]
Hi @sanctusmob,

I did not manage to reproduce the issue with PS1.7.6.2
I used this script
```php
<html><head><title>pUT DATA</title></head><body>
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 10/12/19
 * Time: 10:02
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop.com');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'shop.com',
    'Key',
    false);

$id = 51; //ID specific rule Here
$xml = $ws->get(array('resource' => 'specific_prices', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
$xml->specific_price->from = '2019-12-10';
$xml->specific_price->to = '2019-12-30';
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'specific_prices';
$xml = $ws->edit($opt);
$xml = $ws->get(array('resource' => 'specific_prices', 'id' => $id));
echo "AFTER\n";
echo $xml->asXML();
```
https://drive.google.com/file/d/1aBMnIQ44c0mB8_sZ5zfBDK2UclfKQ1-S/view

Thanks to check & feedback.

**Comment by sanctusmob** [comment]
I am updating a price rule aka resource specific_price_rules. In web interface Admin --> Catalog -->      Discounts --> Catalog Price Rules. 
When updating a Catalog Price Rule from WebUI this also updating the specific price from products where they are in the rules of the "Catalog Price Rule". 
When you do the same via web service does not.

**Comment by khouloudbelguith** [comment]
@sanctusmob, I attached a new screen record
https://drive.google.com/file/d/1LcnMqLu1ahf6KSBF0BD6G5S8jC_2fRmu/view
Thanks to check & feedback.

**Comment by sanctusmob** [comment]
I see you are testing in 1.7.6.2. I am in 1.7.5.1.
So is already fixed. Thank you.

**Comment by khouloudbelguith** [comment]
@sanctusmob, thanks for your feedback.
Feel free to open another one when needed.
