### ISSUE TITLE
PayPal Module Sandbox fails

### ISSUE THREAD

**Issue by shorrog** [PrestaShop/PrestaShop#16769]
Prestashop 1.7.6.2, PHP 7.2.5

I configured the standard "PayPal v5.0.3 - by PrestaShop" module to be in Sandbox mode on my development environment
I tested a refund to a customer. The refund was generated on the customers real account. ie even though in Sandbox the refund was generated.
![image](https://user-images.githubusercontent.com/16224215/70619993-08253f00-1c0e-11ea-88dc-efe9075c8bb9.png)

**Comment by khouloudbelguith** [comment]
Hi @shorrog,

Thanks for your report.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks!

Best regards, Khouloud
