### ISSUE TITLE
Implement Sitelinks Searchbox schema

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#16767]
**Is your feature request related to a problem? Please describe.**
Implement Sitelinks Searchbox schema

**Describe the solution you'd like**
Google Search can expose a search box scoped to your website when it appears as a search result. This search box is powered by Google Search. However, if you wish to power this search box with your own search engine, or if you want search results also to include an associated mobile app, you can do so using structured data embedded on your website.

**Describe alternatives you've considered**
Implement Sitelinks Searchbox schema

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by matks** [comment]
Closing because of https://github.com/PrestaShop/PrestaShop/issues/37421
