### ISSUE TITLE
Minor bug in Cache class

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#16779]
Hello,

classes/Cache.php, line 462
```if (isset($this->sql_tables_cached[$table][$key])) {```
to
```if (isset($this->sql_tables_cached[$table][$key]) && isset($this->sql_tables_cached[$table][$key]['count'])) {```

**Comment by khouloudbelguith** [comment]
Hi @zapper,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
In the meantime, could you provide steps to reproduce the issue due to this bug?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @zapper,

As described in this comment: https://github.com/PrestaShop/PrestaShop/pull/16819#issuecomment-568438515
I did not manage to reproduce the issue with develop branch.
It is ok with PS1.7.6.2 also.
https://drive.google.com/file/d/1wUvQu-VJTSUgiBGNZOiWJBxf3I7uZiJk/view
Waiting for your feedback.

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
