### ISSUE TITLE
Can't edit carrier if new range values are inferior to previous range in carrier wizard

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#16773]
**Describe the bug**
On fresh install of PS 1.7.6.1, I can't add a new range of weigh or price if this new range have values inferiors of previous range. 

My issue is similar but not a duplicate of #16521 because in my case I can't click to "Finish" button because it's disabled:

![finish](https://user-images.githubusercontent.com/7419525/70629173-d7530300-1c29-11ea-8245-03ca4f6d5e44.png)

**To Reproduce**
1. Go to Carriers list and select default "My carrier"
2. Go to step 2 - Shipping destinations and costs
3. Change first value of first existing range (superior or equal) "0.000000" to "500" (keep "10000" as second value)
4. Add a new range
5. Set first value of this new range (superior or equal) to "0"
6. Set second value of this new range (inferior) to "500"
7. Does strange "Ranges are overlapping" error is displayed ??

**Screenshots (French interface)**
![weight](https://user-images.githubusercontent.com/7419525/70629873-ee462500-1c2a-11ea-885a-7dc7931fb192.png)
![price](https://user-images.githubusercontent.com/7419525/70629874-eedebb80-1c2a-11ea-9025-95cea2d7868f.png)

For french SEO:
Erreur "Les tranches se chevauchent" à l'étape 2 "Destinations d'expédition et coûts" lors de l'édition d'un transporteur.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

Thanks for your report.
>Does strange "Ranges are overlapping" error is displayed

This is a red alert, you cannot continue editing ranges with incorrect information.
So, following your steps is normal behavior to have this alert => we don't have permission to edit this ranges like that.
You need to correct the ranges before continuing to edit the carrier.

>in my case I can't click to the "Finish" button because it's disabled 

You need just to edit the ranges like that
![image](https://user-images.githubusercontent.com/16067358/70635007-703a4c00-1c33-11ea-831d-34e4d65bf18a.png)

Thanks to check & feedback.

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith,

Thanks for your answer.

> This is a red alert, you cannot continue editing ranges with incorrect information.

What is incorrect? My ranges are not overlapping...

> we don't have permission to edit this ranges like that.

I read [the official doc](http://doc.prestashop.com/display/PS17/Carriers#Carriers-Panel2:Shippinglocationsandcosts) but I didn't found any comment about right or wrong way to add a new range. Where is it wrote?

In my real case (not simple test case above), I have a carrier with 30 ranges for each kilogram from 1 to 30 kilos, like this:

![30_ranges](https://user-images.githubusercontent.com/7419525/70637433-84804800-1c37-11ea-8b5f-e47121259851.png)

My first range is from 0 to 1 kilograms (kg) but now I want a range from 0 to 0.5 kg and another range from 0.5 to 1 kg. How can I do that?

For me:
- Red alert wording is wrong
- PrestaShop must allow adding a new range with values lower than last range and without overlapping with another range
- Or we should be able to reorder ranges as we want to allow adding new range with low values without having to shift by copy/past all previous values (and prices/weights)

**Comment by khouloudbelguith** [comment]
@Klemart3D, in our official doc

To create another range = click the "Add new range" button. PrestaShop will add a new column of zone fields. **Start again by fixing** the **lower** and **upper** limits of this range, then filling the prices per zone.

So, in your case, you need to re-create the lower & the upper limits from the beginning.
 https://drive.google.com/file/d/1SGlIQpwSiv2xxG5cDtWiIkaeCFwB8ngP/view

Thanks!

**Comment by Hlavtox** [comment]
@Klemart3D 

> My first range is from 0 to 1 kilograms (kg) but now I want a range from 0 to 0.5 kg and another range from 0.5 to 1 kg. How can I do that?

Don't you see the ranges are overlapping?
And I don't think Prestashop has a magic ball  so it knows which range to select. Or what do you expect it to do, when the product weighs 0.2 kg?

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith, thanks for your answer. I read what you wrote but it's not written we have to insert values upper than previous (last) range inserted, I think it missing in doc to really understand how carrier wizard works.
In some projects I have some carriers with tens of weight ranges and hundreds of zones with DIFFERENT prices for each (so I can't use "All" cell shortcut to set column prices globally like your doing in your video sample). My only way to do it it's to copy/past each cell to next range for each zone. I timed it yesterday it took me 4.5 hours...

Hi @Hlavtox, I think you don't understand, my question implicitly suggests to REPLACE 0-1 (kg) range by two NEW ranges (0 kg - 0.5 kg AND 0.5 kg - 1 kg ranges). So finally, first range is superior or equal (>=) to 0 and strictly inferior (<) to 0.5 and new range is >=  0.5 and < 1 so **ranges are not overlapping**, error message displayed is wrong:

![overlapping](https://user-images.githubusercontent.com/7419525/70707098-ab8e5680-1cd7-11ea-84c4-8199b04047ac.png)

**Comment by khouloudbelguith** [comment]
@Klemart3D, for now, you cannot add a range between two ranges.
You can only add a new range at the left & this new range cannot be reordered.
![image](https://user-images.githubusercontent.com/16067358/70707749-36238580-1cd9-11ea-99a2-75489597eb39.png)

Thanks!

**Comment by Klemart3D** [comment]
@khouloudbelguith, I understand but system must be improved.

**Comment by khouloudbelguith** [comment]
@Klemart3D, thanks for your feedback.
So, can we close this issue & can you create a new improvement to describe your suggestion:
1. Add a range between two ranges
2. Re-order ranges

Do you agree with that?

Thanks!

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith,

Thanks for your answer.

1. It not only "between" two range, it's also to create a new range before the first (see attached below).
2. Right, a reorder system will be very useful!

I've created a Feature request #16823, so you can close this ticket.

![overlapping-first-range](https://user-images.githubusercontent.com/7419525/70896271-b5260000-1ff0-11ea-9658-0f2343f9eb3a.png)

**Comment by khouloudbelguith** [comment]
@Klemart3D, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
