### ISSUE TITLE
Redirect 404 when i change id product in URL

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#16781]
Hello,

I have a issue. When I change in URL, the product id, I get a 404 error because attribute id is empty.

Exemple :
I have this URL https://fr.preprod.moondreamwebstore.fr/rideau-occultant-total/rideau-100-occultant-dream-vieux-rose-mc343-745-3273.html
When i change the number 745 (product id) in 15 (other product id), i have a 404

https://fr.preprod.moondreamwebstore.fr/rideau-occultant-total/rideau-100-occultant-dream-vieux-rose-mc343-15-3273.html
-->
https://fr.preprod.moondreamwebstore.fr/rideau-occultant-uni/rideau-occultant-uni-beige-coquille-mc634-15-.html

Can you help me please ?

Thanks a lot

Prestashop 1.7.6.0
PHP 5.6

**Comment by khouloudbelguith** [comment]
Hi @ShaimyWinda,

Did you use any custom module to change the Shema of URLs? 
By default, in the BO => Shop Parameters => Traffic & SEO page, the Route to products => `{category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html`
![image](https://user-images.githubusercontent.com/16067358/70694016-f51e7780-1cbe-11ea-9975-41f18fe073c0.png)

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment]
Hi @khouloudbelguith,

My route is : {category:/}{rewrite}-{id}-{id_product_attribute}.html
I have to keep this because my company wants it.


Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, okay thanks!
About your second product with friendly URL =`rideau-occultant-uni-beige-coquille-mc634`, if you click on the Preview button from the BO, it redirects to 404 also?
![image](https://user-images.githubusercontent.com/16067358/70694714-90fcb300-1cc0-11ea-8030-3bbe9ba433bc.png)
Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith Yes i have error 404 

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by ShaimyWinda** [comment]
@khouloudbelguith  I've done the steps and I still have the error

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, this issue occurs, only with this product?

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith No, All products 

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, 
>About your second product with friendly URL =rideau-occultant-uni-beige-coquille-mc634, if you click on the Preview button from the BO, it redirects to 404 also

if you disable the friendly URL, this issue occurs again?

thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith 
I just tested it, I don't have any mistakes.
However, I had a blank page with this link: https://fr.preprod.moondreamwebstore.fr/index.php?id_product=15&id_product_attribute=0&rewrite=rideau-occultant-uni-beige-coquille-mc634&controller=product

Then there was a redirection to this link:
https://fr.preprod.moondreamwebstore.fr/index.php?id_product=15&rewrite=rideau-occultant-uni-beige-coquille-mc634&controller=product

Thanks

**Comment by ShaimyWinda** [comment]
Hi @khouloudbelguith 
Have you seen my last message?
Thanks !

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, as you can see in your link: `https://fr.preprod.moondreamwebstore.fr/index.php?id_product=15&id_product_attribute=0&rewrite=rideau-occultant-uni-beige-coquille-mc634&controller=product`

the `id_product_attribute=0`, this is incorrect, so that's why you have a redirection.
Could you please try to delete all the combinations for this product & regenerate them again.

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment]
@khouloudbelguith I delete one combination and generate, The attribute id does not exist

![Capture](https://user-images.githubusercontent.com/25744417/70786238-798afc00-1d8c-11ea-950a-159d21459d3c.JPG)

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, ok as I understand, did you delete an attribute? or an attribute value?
The last combination has no information about the attribute selected.

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith You just had to wait, attribute ID is displayed. But despite everything, I still have a 404 error.
Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ShaimyWinda** [comment]
Hi @khouloudbelguith 
I hope you had a good weekend.
I looked in the logs and I don't see any errors ... It's strange

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, We need PHP error logs. If you don't have it, you should ask to your hosting provider.

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith I know but the file is empty .. not error php ...

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, could you please provide me your exact server information.
You can find it in the BO => Advanced Parameters => Information page.

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith 
_Informations sur votre serveur Linux #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.1.33-2+0~20191128.28+debian9~1.gbpc60685

Limite de mémoire : 512M

Temps maximal d'exécution : 3600

Taille max. pour envoi de fichiers : 128M_

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, as always, I have the combination is missing
![image](https://user-images.githubusercontent.com/16067358/71014713-ab84c100-20f2-11ea-808e-cfc10d7712e3.png)
PS: if I click on the preview button => OK
I will send the screen record by email.

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith Try other product. Same issus ...

Thanks

**Comment by ShaimyWinda** [comment]
Hello @khouloudbelguith ,

I noticed something else, if I disable simplified url and change the product id, I don't have an error but the attribute id is no longer displayed

![Capture24](https://user-images.githubusercontent.com/25744417/71072989-d537f980-217f-11ea-8d2f-8d7e6231ab5b.JPG)

**Comment by ShaimyWinda** [comment]
@khouloudbelguith I found the error, it comes from version 1.7.6.0

This is the canonicalRedirection() function in ProductController. If I put the code of version 1.7.4.2 everything works fine

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, did you make an upgrade from PS1.7.4.2 previously?
Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith , Yes I was in 1.7.4.2 and when we switched to version 1.7.6.0, it didn't work anymore. So I looked at the functions of the file and noticed this error

Thanks

**Comment by ShaimyWinda** [comment]
On the other hand, it redirects well but it's not the right attribute

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, did you used the 1-click upgrade? which version?
Have you any errors during the upgrade?

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith , it was an agency specialized in Prestashop that made the migration. I override the file and put in the modifications. I have no redirection error but the id of the attribute does not change. But if I change in the master file (so without override) everything works very well

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, great to hear that is fixed.
As you didn't use a module provided by Prestashop, we can't do anything with this. 
You should contact the agency, they are the only ones to help you with it.

PS: in my case, I did not manage to reproduce the issue => it is OK.
I will close the issue, feel free to open a new one when needed.
Thanks!
