### ISSUE TITLE
{shop_name} is not updated

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#16798]
Hello,

I am using Prestashop 1.7.6 and I changed the name of the shop because of a wrong display but the old one is still appeared...

Here is the change
![image](https://user-images.githubusercontent.com/39828779/70799162-296e6280-1da9-11ea-8d1f-186f699f1714.png)

Database is updated well 

![image](https://user-images.githubusercontent.com/39828779/70799187-3b500580-1da9-11ea-86ea-d7537f31cb4e.png)

However email object and footer are still wrong

![image](https://user-images.githubusercontent.com/39828779/70799255-63d7ff80-1da9-11ea-84ec-e7e2fd921548.png)

This is a single store

**Comment by Dupflo** [comment]
Got it name on ps_shop was not updated

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16499
