### ISSUE TITLE
Misplaced asterisk in Link Widget Add/Edit page

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#16797]
**Describe the bug**
An asterisk to mark a mandatory field is misplaced in the Link Widget Add/edit page.

It is located at the bottom of the page in the middle of nowhere.

**To Reproduce**
1. Go to 'Link Widget'
2. Click on 'Add or Edit'
3. Scroll down to the bottom of the page
4. See the asterisk

**Screenshots**
https://drive.google.com/file/d/1mF5S7XZsJFDuSoafP0-LKmERomBb1177/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @sam-pires,

What is the exact version of the link Widget module did you use?
If it is v3.0.3, you need to upgrade it, it is not the last version.

Thanks to check & feedback.

**Comment by sam-pires** [comment]
I was in v3.0.3 and upgraded it 👍 

Though in v3.0.4 the asterisk is not displayed at all however the "name" field is required.
see screenshot if let empty.

![Capture d’écran 2019-12-13 à 17 48 05](https://user-images.githubusercontent.com/25405887/70817165-4dde3500-1dd1-11ea-88c9-595a2b9a7e91.png)

**Comment by khouloudbelguith** [comment]
@sam-pires, about this issue, this is a behavior added to ps_linklist: The block name must be set in all language to be created.
I just create an improvement about this previously: https://github.com/PrestaShop/ps_linklist/issues/58
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
@sam-pires, I will close this issue.

Thanks!
