### ISSUE TITLE
Upgrade from 1.6 to 1.7.6.2 gives issues with tables

### ISSUE THREAD

**Issue by faranm** [PrestaShop/PrestaShop#16793]
Hi,

After upgrading from Prestashop 1.6 to 1.7.6.2 i got this error,

[PrestaShopDatabaseException]
Table 'nasiha_dk_db.nsps_translation' doesn't exist

I run on PHP 7.2.25.
<img width="1194" alt="Frontpage" src="https://user-images.githubusercontent.com/38395467/70741604-f205a480-1d1b-11ea-8cf2-5d9f29eec118.png">
<img width="1440" alt="Upgrade" src="https://user-images.githubusercontent.com/38395467/70741608-f5992b80-1d1b-11ea-8761-36882c5d04f2.png">

**Comment by khouloudbelguith** [comment]
Hi @faranm,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Can you access to the Back Office?
Did you use an old version of the 1-click upgrade?
It is 1.6.7 in your case.
![image](https://user-images.githubusercontent.com/16067358/70790277-0b970280-1d95-11ea-95c5-e6fe0c01daeb.png)
This version is compatible with PS1.5 & not PS1.6
![image](https://user-images.githubusercontent.com/16067358/70790373-3c773780-1d95-11ea-8ead-ce64d28ac8f4.png)
https://addons.prestashop.com/fr/migration-donnees-sauvegarde/5496-.html
Thanks to check and feedback.

**Comment by faranm** [comment]
I have done the upgrade manually by following this guide:
https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

Reason why I have done it manually is because I could not access the back office. My web host have upgraded the PHP server to 7.2 and after that I could not access the back office in PS 1.6. The front worked perfectly.

I have cleared the the cache by deleting the folder in var/cache/dev and var/cache/prod but not solve the issue. Got still the same error messages. The same case is for the back office.
<img width="1194" alt="Back Office" src="https://user-images.githubusercontent.com/38395467/70823019-2a21eb80-1ddf-11ea-8f7f-08bf9c56ab8f.png">

**Comment by khouloudbelguith** [comment]
@faranm,

>My web host have upgraded the PHP server to 7.2 and after that I could not access the back office in PS 1.6

PrestaShop 1.6 is not compatible with PHP7.2, you can follow this [link](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart) for more details.

The BO is not accessible in your case? is it possible to try to import your language Danish from the BO?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @faranm,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
