### ISSUE TITLE
Related Products miniatures and names not displays in BO

### ISSUE THREAD

**Issue by kazzo** [PrestaShop/PrestaShop#16799]
**Describe the bug**
I Have exactly the same issue as in #13531.
When I disable friendly URLs related products show up.
In phppsinfo got all green except yellow PHP version, mine is 5.6.38 but it shouldn't matter cause required is 5.6 (Ortezjan got 7.2 and problem also occurred).
I have in phpinfo mbstring set as above except oniguruma version it not appears in mine.
I have no access to PHP log but in Apache error log I have:
AH01071: Got error 'Primary script unknown\n', referer: https://admirsklep.pl/admin516ncnsa4/index.php/sell/catalog/products/1?_token=TOjqsgkbEghAGWICydVkBAx6QzciwWrUL_41eqOJRKU

**To Reproduce:**
1.     Go to 'product page'
2.     Click on 'product'
3.     Scroll down to 'add related products'
4.     See error

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment]
Hi @kazzo,

Thanks to provide me information about your server.
You can find it in the BO => Advanced Parameters => Information.
When debug mode enabled, is there any exception displayed?
Thanks!

**Comment by kazzo** [comment]
Sorry. I forgot.
Server Information: Linux #192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019 x86_64 
Server software version: PHP version: 5.6.38
Memory limit: 1024M 
Maximum running time: 120
Maximum file size for upload: 128M
MySQL version: 10.1.43-MariaDB
MySQL engine: InnoDB
MySQL driver: DbPDO

No exceptions are displayed.
Thanks

**Comment by khouloudbelguith** [comment]
@kazzo, the` Server software version` is empty.
I need to know your exact server software.

Thanks!

**Comment by kazzo** [comment]
Arrrgh! I lost it during paste 
Server software version: Apache/2
Sorry!

**Comment by khouloudbelguith** [comment]
@kazzo, the employee language is the same default language?
if no, your employee language is disabled?

Thanks!

**Comment by kazzo** [comment]
Polish is shop default.
Employee language is Polish.
Polish is the only enabled language (English is disabled).
Thanks!

**Comment by khouloudbelguith** [comment]
@kazzo, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.2.
https://drive.google.com/file/d/1JgVToOE7KiftaBm6onfGjomxI5elDZan/view
Could you please navigate to your BO => Design => Image Settings page => Click on the "Regenerate thumbnails" button, check & feedback.

**Comment by kazzo** [comment]
I've already done it and it not solves the problem. 
When I add related product it wors fine via ajax, but when leave editor and back to edit, related product name is for example (ref:00267) - there's no product name and image name is ".jpg", so I got 404.
[https://drive.google.com/open?id=1HGPf0ad22RGCJ-5jrg76Ch3Gp2gGddHV](https://drive.google.com/open?id=1HGPf0ad22RGCJ-5jrg76Ch3Gp2gGddHV)
Thanks!

**Comment by khouloudbelguith** [comment]
@kazzo,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by kazzo** [comment]
So, I did it earlier and no, no progress.
When friendly Url is Off the miniature images are displayed but related product name is still without its name - for example (ref:00267).

**Comment by khouloudbelguith** [comment]
@kazzo, in your BO => International => Translations => Update the Polish language, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/71070583-5e98fd00-217b-11ea-91e2-053a08056b55.png)

Thanks!

**Comment by kazzo** [comment]
Nope, still the same :(

**Comment by khouloudbelguith** [comment]
@kazzo, could you please provide me a screenshot from your BO => Design => Images Settings 
![image](https://user-images.githubusercontent.com/16067358/71159559-214d7180-2246-11ea-9624-3120879fa540.png)

Thanks!

**Comment by kazzo** [comment]
Here You are:
![images](https://user-images.githubusercontent.com/8221944/71181877-53c29300-2275-11ea-9a37-3a40fa5614ce.jpg)
But I think the problem is elsewhere.
Look at this:
![Related_Err](https://user-images.githubusercontent.com/8221944/71182231-0135a680-2276-11ea-84fa-e53f403b587f.jpg)
Last two positions represents the same product. I added related products and leave, then back to edit and there are no images and product names. As You see when I added another related it works fine but when leave and back to edit got same situation.
When I turn off friendly links, images appears, but no names.
Thanks!

**Comment by khouloudbelguith** [comment]
@kazzo, I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1XSRNEvV7EeE7yJ99G5hjGfSv5s2BuTV1/view
In the FO, they are well displayed?
What is the exact browser did you use?
Thanks!

**Comment by kazzo** [comment]
I use PS 1.7.6.1 on localhost (PHP 7.2.11) and cannot reproduce this issue too.
In the FO related products works perfect, problem is only in BO.
I use Firefox, but the same issue is in Crome and Opera too.
Phppsinfo says all OK, but in Apache error log I have:
AH01071: Got error 'Primary script unknown\n', referer: https://admirsklep.pl/admin516ncnsa4/index.php/sell/catalog/products/1?_token=TOjqsgkbEghAGWICydVkBAx6QzciwWrUL_41eqOJRKU

So I wonder if there is maybe rewrite rules problem in .htaccess on my hosting configuration (nazwa.pl).

**Comment by khouloudbelguith** [comment]
@kazzo, thanks tp provide me your PHP info file.
you can follow this documentation to know how to create your file php.ini: https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page
Thanks!

**Comment by kazzo** [comment]
OK, 
Here is [phpinfo as html](https://drive.google.com/open?id=1JwIbzeaVpFW86XmYyMgWwxA9TKWuqc_1) 
and maybe [.htaccess](https://drive.google.com/open?id=1JeWvVtf-w7gcv8iBBu1zFAM48iGPTU6y) yet - mostly generated by PS.

**Comment by khouloudbelguith** [comment]
@kazzo, you are using PHP-FPM
This error `Primary script unknown\n` is related to your server.
It is almost always related to a wrongly set `SCRIPT_FILENAME`.
So, could you please check with your host & feedback.

**Comment by kazzo** [comment]
I upload test.php to shop directory (it printis out $_SERVER superglobal)

The most interesting values are:
[HOME] => /home/admir/ftp
[SCRIPT_URI] => https://admirsklep.pl/test.php
[SCRIPT_URL] => /test.php
[HTTP_HOST] => admirsklep.pl
[PATH] => /bin:/usr/bin:/usr/local/bin
[DOCUMENT_ROOT] => /home/admir/ftp
[CONTEXT_DOCUMENT_ROOT] => /home/admir/ftp
[SCRIPT_FILENAME] => /home/admir/ftp/bisk_sklep/test.php
[REQUEST_URI] => /test.php
[SCRIPT_NAME] => /test.php
[PATH_TRANSLATED] => /home/admir/ftp/bisk_sklep/test.php
[PHP_SELF] => /test.php

had to remove .htaccess of course.

**Comment by khouloudbelguith** [comment]
@kazzo, did you tried to contact your host?
Have you any feedback from them?

Thanks!

**Comment by kazzo** [comment]
So, not yet. I wonder what should I ask about?
Thanks!

**Comment by khouloudbelguith** [comment]
@kazzo, about this error
`This error Primary script unknown\n` is related to your server.

Thanks!

**Comment by kazzo** [comment]
My host said: 
> Hello,
> I tried to verify the cause of the error, but unfortunately it was not possible on my side.
> I suggest you check what functionalities and plugins work within the store. Probably one of them is generating errors or is not available.
>
So, I'm on my own?
Thanks & Merry Xmas.

**Comment by khouloudbelguith** [comment]
Hi @kazzo,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
