### ISSUE TITLE
Broken links after 1.7.5.1 upgrade to 1.7.6.2

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#16795]
Hi,

I upgraded my Prestashop 1.7.5.1 to 1.7.6.2 with 1-click upgrade v4.10. 
After the upgrade I have faced several 500 error pages at the backend, like Catalog>categories or catalog>discounts>create new rule etc..
And when I have taken the site to debug mode I got errors at the frontend too.

I searched around forums and tried to upgrade "faceted search module "but could not because I have taken error too when I click the upgrade button. I also tried manual upload with filezilla the latest module files from github but not fixed..

How can I fix that issue pls ? 

![Screen Shot 2019-12-11 at 12 36 05](https://user-images.githubusercontent.com/58822578/70787260-5b7ac700-1d9f-11ea-8eea-811b638f373f.png)

![Screen Shot 2019-12-11 at 12 35 48](https://user-images.githubusercontent.com/58822578/70787288-66355c00-1d9f-11ea-800a-f6a5853d296d.png)

**Comment by khouloudbelguith** [comment]
Hi @ibrahimfsasmaz,

This issue is fixed previously as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14617
As a Provisional solution thanks to try with this SQL query

> ```
> ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> ```

Thanks to check & feedback.

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> This issue is fixed previously as reported in this ticket: #14617
> As a Provisional solution thanks to try with this SQL query
> 
> > ```
> > ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> > ```
> 
> Thanks to check & feedback.

hello,

I tried but nothing change I am getting the same errors

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> This issue is fixed previously as reported in this ticket: #14617
> As a Provisional solution thanks to try with this SQL query
> 
> > ```
> > ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> > ```
> 
> Thanks to check & feedback.

![Screen Shot 2019-12-13 at 23 14 44](https://user-images.githubusercontent.com/58822578/70829314-6add2d00-1dfe-11ea-8e89-646ff1f65c38.png)

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> This issue is fixed previously as reported in this ticket: #14617
> As a Provisional solution thanks to try with this SQL query
> 
> > ```
> > ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> > ```
> 
> Thanks to check & feedback.

I still display these errors below at debug mode 

![Screen Shot 2019-12-13 at 23 25 05](https://user-images.githubusercontent.com/58822578/70829920-0327e180-1e00-11ea-962b-781b739ec629.png)

![Screen Shot 2019-12-13 at 23 24 48](https://user-images.githubusercontent.com/58822578/70829927-07ec9580-1e00-11ea-81ed-558ca7bfaa45.png)

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> This issue is fixed previously as reported in this ticket: #14617
> As a Provisional solution thanks to try with this SQL query
> 
> > ```
> > ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> > ```
> 
> Thanks to check & feedback.

the upgrade does not work for the faceted search too

![Screen Shot 2019-12-13 at 23 36 49](https://user-images.githubusercontent.com/58822578/70830828-2a7fae00-1e02-11ea-9ef2-2ce32e2cef7b.png)

**Comment by ibrahimfsasmaz** [comment]
hello ,

is there professional service pls ? Someone can pls fix it for me ?

**Comment by ibrahimfsasmaz** [comment]
still could not fix it. I tried manual upgrade to fix but as it is already latest version, I have taken error 28.
so I have no idea for the moment how to fix it...
I need help pls

**Comment by khouloudbelguith** [comment]
Hi @ibrahimfsasmaz,

Sorry for the late response.
Could you please try to uninstall the `ps_facetedsearch` module with removing the folder.
You need to clear the cache manually by deleting all the folders into var/cache (prod & dev).
Now, try to navigate to the BO => Module Catalog => Search for the module & install it.
About the second exception: `Declaration of HTML`, thanks to provide the whole exception (pdf file).
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`
Thanks to check and feedback.

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> Sorry for the late response.
> Could you please try to uninstall the `ps_facetedsearch` module with removing the folder.
> You need to clear the cache manually by deleting all the folders into var/cache (prod & dev).
> Now, try to navigate to the BO => Module Catalog => Search for the module & install it.
> About the second exception: `Declaration of HTML`, thanks to provide the whole exception (pdf file).
> Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`
> Thanks to check and feedback.

there is no "faceted search" under module catalog unfortunately.
pls find below the log file

[log.txt](https://github.com/PrestaShop/PrestaShop/files/3975357/log.txt)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, the upgrade was done ok.
>[2019-12-11 00:25:20] All files upgraded
>[2019-12-11 01:25:41] Database upgraded

The upgrade of your modules was corrupted due to a cache issue.
>[2019-12-11 03:25:48] [INTERNAL] /home/270565.cloudwaysapps.com/qndngdkwzh/public_html/var/cache/prod/classes.php line 3134 - Cannot redeclare class Symfony\Component\Config\ConfigCache

Could you please try to uninstall the `blockreassurance` module with removing the folder, clear cache & try to install it again from the Module Catalog page.

>there is no "faceted search" under module catalog unfortunately.

You can find it in our GitHub repository
https://github.com/PrestaShop/ps_facetedsearch/releases
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3977499/ps_facetedsearch.zip)

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> blockreassurance

there is no blockreassurance module under Module Catalog

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, the upgrade was done ok.
> 
> > [2019-12-11 00:25:20] All files upgraded
> > [2019-12-11 01:25:41] Database upgraded
> 
> The upgrade of your modules was corrupted due to a cache issue.
> 
> > [2019-12-11 03:25:48] [INTERNAL] /home/270565.cloudwaysapps.com/qndngdkwzh/public_html/var/cache/prod/classes.php line 3134 - Cannot redeclare class Symfony\Component\Config\ConfigCache
> 
> Could you please try to uninstall the `blockreassurance` module with removing the folder, clear cache & try to install it again from the Module Catalog page.
> 
> > there is no "faceted search" under module catalog unfortunately.
> 
> You can find it in our GitHub repository
> https://github.com/PrestaShop/ps_facetedsearch/releases
> [ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3977499/ps_facetedsearch.zip)
> 
> Thanks!

 I tried to upload the module zip latest version downloaded from 
https://github.com/PrestaShop/blockreassurance/releases

But had error message
Oops... Upload failed.

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, 
>I tried to upload the module zip latest version downloaded from

Did you try with this zip?
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3982407/ps_facetedsearch.zip)
>there is no blockreassurance module under Module Catalog

Did you check if this module is installed in the module Manager page before installing it again?

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz,
> 
> > I tried to upload the module zip latest version downloaded from
> 
> Did you try with this zip?
> [ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3982407/ps_facetedsearch.zip)
> 
> > there is no blockreassurance module under Module Catalog
> 
> Did you check if this module is installed in the module Manager page before installing it again?
> 
> Thanks!

Hi,
this is not the one that I could not install.
https://github.com/PrestaShop/blockreassurance/releases

blockreassurance is not installing

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, from GitHub you need to unzip the folder, run `composer install` & zip it again.
Thanks to try with this folder
[blockreassurance.zip](https://github.com/PrestaShop/PrestaShop/files/3987544/blockreassurance.zip)

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, from GitHub you need to unzip the folder, run `composer install` & zip it again.
> Thanks to try with this folder
> [blockreassurance.zip](https://github.com/PrestaShop/PrestaShop/files/3987544/blockreassurance.zip)
> 
> Thanks!

Hello,
I have uploaded the modules but ;
1- stil having that error 500 at BO>Catalog>Categories   &   BO>Catalog>Brands&suppliers 
2- BO>Customers>CustomerService  &  BO>Customers>MerchandiseReturn  does not display anything 
  
![Screen Shot 2019-12-21 at 01 00 48](https://user-images.githubusercontent.com/58822578/71295733-3c2afd80-238e-11ea-8447-d04edf3280c5.png)
![Screen Shot 2019-12-21 at 01 01 45](https://user-images.githubusercontent.com/58822578/71295735-3df4c100-238e-11ea-838d-f0b1227a3055.png)

**Comment by ibrahimfsasmaz** [comment]
it looks that there is no other solution than waiting 1.7.6.3 , 1.7.6.2 has lots of bugs

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, could you please provide me a screenshot from the Database, the structure of the table `ps_admin_filter`
![image](https://user-images.githubusercontent.com/16067358/71350970-da77b880-2572-11ea-82ba-f5ea9e0a5570.png)

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, could you please provide me a screenshot from the Database, the structure of the table `ps_admin_filter`
> ![image](https://user-images.githubusercontent.com/16067358/71350970-da77b880-2572-11ea-82ba-f5ea9e0a5570.png)
> 
> Thanks!

mine is like below, pls have a look 

![Screen Shot 2019-12-23 at 21 07 38](https://user-images.githubusercontent.com/58822578/71373478-53552f80-25c8-11ea-919f-43d4ac635959.png)

**Comment by ibrahimfsasmaz** [comment]
I changed the filter id as varchar 255 but nothing has changed I still the error below at BO>Catalog>Categories

![Screen Shot 2019-12-23 at 21 11 28](https://user-images.githubusercontent.com/58822578/71373666-058cf700-25c9-11ea-8c56-fda41be531ac.png)

![Screen Shot 2019-12-23 at 21 11 47](https://user-images.githubusercontent.com/58822578/71373673-0a51ab00-25c9-11ea-855d-1b0d5cb0f50a.png)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, I need to check in your structure, that they are not null
![image](https://user-images.githubusercontent.com/16067358/71406277-f3966d00-2637-11ea-8509-8cd9cac7d77e.png)
Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, I need to check in your structure, that they are not null
> ![image](https://user-images.githubusercontent.com/16067358/71406277-f3966d00-2637-11ea-8509-8cd9cac7d77e.png)
> Thanks!

this is what I display 

![Screen Shot 2019-12-24 at 14 43 32](https://user-images.githubusercontent.com/58822578/71411792-df646700-265b-11ea-8fde-d594268d5caf.png)
![Uploading Screen Shot 2019-12-24 at 14.43.39.png…]()

**Comment by ibrahimfsasmaz** [comment]
ok I installed phpmyadmin and this is what I display

![Screen Shot 2019-12-24 at 15 35 05](https://user-images.githubusercontent.com/58822578/71413397-0d00de80-2663-11ea-98d8-49ea6b903caf.png)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, could you please check if you have an override of the class `HTMLTemplateOrderSlipCore`?

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, could you please check if you have an override of the class `HTMLTemplateOrderSlipCore`?
> 
> Thanks!

I do not have that override
![Screen Shot 2019-12-24 at 18 46 27](https://user-images.githubusercontent.com/58822578/71418855-c79dda80-267d-11ea-882e-ef59324585a5.png)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, thanks to check under the `pdf` folder.

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, thanks to check under the `pdf` folder.

![Screen Shot 2019-12-24 at 18 51 02](https://user-images.githubusercontent.com/58822578/71418974-5f9bc400-267e-11ea-99ee-d3e6d4859319.png)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, exactly, you have 4 overrides.
![image](https://user-images.githubusercontent.com/16067358/71419202-85b96800-266e-11ea-8f12-f153c8605f68.png)
By default, those files do not exist: https://github.com/PrestaShop/PrestaShop/tree/1.7.6.2/override/classes/pdf
You need to check those overrides are provided by which module & check the compatibility.

Thanks to check & feedback.

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, exactly, you have 4 overrides.
> ![image](https://user-images.githubusercontent.com/16067358/71419202-85b96800-266e-11ea-8f12-f153c8605f68.png)
> By default, those files do not exist: https://github.com/PrestaShop/PrestaShop/tree/1.7.6.2/override/classes/pdf
> You need to check those overrides are provided by which module & check the compatibility.
> 
> Thanks to check & feedback.

I do not think that there is a relation between these files and the problem. Even if I rename/remove them the problem is not fix

![Screen Shot 2019-12-24 at 20 13 15](https://user-images.githubusercontent.com/58822578/71421101-d8ece400-2689-11ea-82c5-6261843d4440.png)

**Comment by ibrahimfsasmaz** [comment]
I installed a new module and now it is completely gone.... perfect ! wonderful !
full of bugs

![Screen Shot 2019-12-24 at 22 07 40](https://user-images.githubusercontent.com/58822578/71423358-fe81e980-2699-11ea-9039-7e4f8fc35b88.png)

![Screen Shot 2019-12-24 at 22 07 50](https://user-images.githubusercontent.com/58822578/71423359-03df3400-269a-11ea-970c-a7438bd05649.png)

![Screen Shot 2019-12-24 at 22 08 00](https://user-images.githubusercontent.com/58822578/71423362-06da2480-269a-11ea-95a7-8be3d75ab9e3.png)

![Screen Shot 2019-12-24 at 22 08 10](https://user-images.githubusercontent.com/58822578/71423363-0a6dab80-269a-11ea-9c7c-b01555e92387.png)

![Screen Shot 2019-12-24 at 22 08 19](https://user-images.githubusercontent.com/58822578/71423366-0d689c00-269a-11ea-9c64-754de5024386.png)

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, 
>I do not think that there is a relation between these files and the problem. Even if I rename/remove them the problem is not fix

You need to clear the cache manually by deleting all the folders into var/cache (prod & dev) after renaming those files.

>I installed a new module and now it is completely gone.... perfect ! wonderful !
full of bugs

What is the exact module did you installed? is it Advanced Pack?

Thanks!

**Comment by ibrahimfsasmaz** [comment]
ok I removed all had created a new clone copy from the beginning...

Now what I have is that 1.7.5.1 upgraded to 1.7.6.2 with 1-click upgrade and I have same error.

**Comment by khouloudbelguith** [comment]
Hi @ibrahimfsasmaz,

In order to avoid problems, remember to check the compatibility of your modules and theme & overrides beforehand.
As explained here: https://github.com/PrestaShop/PrestaShop/issues/16795#issuecomment-568771079, try to rename those overrides & you need to clear the cache manually by deleting all the folders into var/cache (prod & dev) after renaming those files.

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> Hi @ibrahimfsasmaz,
> 
> In order to avoid problems, remember to check the compatibility of your modules and theme & overrides beforehand.
> As explained here: [#16795 (comment)](https://github.com/PrestaShop/PrestaShop/issues/16795#issuecomment-568771079), try to rename those overrides & you need to clear the cache manually by deleting all the folders into var/cache (prod & dev) after renaming those files.
> 
> Thanks!

nothing works....
Is there another way to migrate to a clean 1.7.6.2 without loosing any data or module or theme pls ?

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, before upgrading, you need to check if your modules & your theme & your overrides are compatible with the new release PS1.7.6.2.
So, if your overrides are not compatibles for example with PS1.7.6.2 => you will have a lot of issues, that's the problem.

In your case, as I said before, some overrides occurs a lot of problems & your last module has issues with PS1.7.6.2 also, you need to contact the module author about this issue.

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, before upgrading, you need to check if your modules & your theme & your overrides are compatible with the new release PS1.7.6.2.
> So, if your overrides are not compatibles for example with PS1.7.6.2 => you will have a lot of issues, that's the problem.
> 
> In your case, as I said before, some overrides occurs a lot of problems & your last module has issues with PS1.7.6.2 also, you need to contact the module author about this issue.
> 
> Thanks!

which module do you mean pls ? I can remove that or ask to developer ? If I remove that the issue will be fixed ?

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, according to this comment: https://github.com/PrestaShop/PrestaShop/issues/16795#issuecomment-568792924
You have issues after installing a module, isn't? this module.

Also, you need to check what are the modules that create those overrides
![image](https://user-images.githubusercontent.com/16067358/71470000-2329ae80-27cb-11ea-86c6-f06cb68242a1.png)

Thanks!

**Comment by ibrahimfsasmaz** [comment]
> @ibrahimfsasmaz, according to this comment: [#16795 (comment)](https://github.com/PrestaShop/PrestaShop/issues/16795#issuecomment-568792924)
> You have issues after installing a module, isn't? this module.
> 
> Also, you need to check what are the modules that create those overrides
> ![image](https://user-images.githubusercontent.com/16067358/71470000-2329ae80-27cb-11ea-86c6-f06cb68242a1.png)
> 
> Thanks!

no there is a misunderstanding there is no relation with that module..

without installing any module after 1-click upgrade , I had several issues from 1.7.5.1 to 1.7.6.2.
even if I upgrade the faceted search and all other modules the problem has not fixed..

I am having 500 error when I try access BO>Catalog>Categories and several other links at backend..

After all (while nothing has fixed yet) I tried to install a new module to check if it will work or not "Advanced Pack 5 - Create ​​bundles of products"

and after installing the module the site completely stopped working

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz,

>After all (while nothing has fixed yet) I tried to install a new module to check if it will work or not "Advanced Pack 5 - Create ​​bundles of products"
and after installing the module the site completely stopped working

About this module, you should contact the module author via your addons.prestashop.com account about these new errors

>without installing any module after 1-click upgrade , I had several issues from 1.7.5.1 to 1.7.6.2.
even if I upgrade the faceted search and all other modules the problem has not fixed

At last, you have these issues
![image](https://user-images.githubusercontent.com/16067358/71471405-af3dd500-27cf-11ea-94e6-bbeb9aceccd2.png)
this is related to your overrides.
You need to clear the cache manually by deleting all the folders into var/cache (prod & dev) after renaming those files.
Thanks!

**Comment by ibrahimfsasmaz** [comment]
hello,

we cloned the site and fixed the DB structure.
now we have 1 live site and 1 clone copy;

- we fixed the clone copy first. the clone copy works perfectly fine
- we tried to do the exact same fix to live site, after fixing the clone copy. But we are having trouble at live.

at live site the "BO>catalog>discounts>create discount or edit existing" does not work. Sometimes it works for a few minutes than after stops working again.

when we turn on the debug mode, this time discounts work properly but "BO>catalog>categories" stops working.

the only difference between live site (mysql 5.5) and clone copy(mysql 5.6) is the mysql versions.

Do you have any idea about how to fix pls ?

**Comment by khouloudbelguith** [comment]
@ibrahimfsasmaz, as you can see in this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
PrestaShop needs the following server configuration in order to run: MySQL v5.6 minimum, a recent version is recommended.
Please upgrade your Mysql server, clear cache, check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ibrahimfsasmaz, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by khouloudbelguith** [comment]
8
