### ISSUE TITLE
Demo navbar "hide/show" button prevents user to use menu in mobile view

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16802]
**Describe the bug**
On PS demo demo.prestashop.com, the navbar "hide/show" button prevents user to use menu in mobile view because it appears on top of it.

**To Reproduce**
1. Go to https://demo.prestashop.com using a mobile device
2. Try to use the left top menu, its cannot be done because of the "hide/show" button

**Screenshots**
<img width="188" alt="Capture d’écran 2019-12-13 à 17 08 28" src="https://user-images.githubusercontent.com/3830050/70814165-3bf99380-1dcb-11ea-8d27-73180b8d24dc.png">

**Comment by khouloudbelguith** [comment]
Hi,

Ping @Quetzacoalt91 what do you think?

Thanks!

**Comment by Quetzacoalt91** [comment]
Hi there, 

For sure we can update the interface in order to remove this overlap, but I don't know what we could display instead.
I could center this div, or if we need something else, we'll have to call our designer for help. :)

**Comment by marionf** [comment]
@matks as it's not about the open source project, maybe we can close this issue and open it on Jira, wdyt ?

**Comment by matks** [comment]
> @matks as it's not about the open source project, maybe we can close this issue and open it on Jira, wdyt ?

As long as the bug is registered somewhere relevant I'm Ok with it 😄

**Comment by marionf** [comment]
Issue reported here: https://github.com/PrestaShop/live-demo-devices/issues/16
