### ISSUE TITLE
Localisation issues

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16808]
**Describe the bug**
1. PS Installer bug: changing the language don't change country name translation.

2. Shop bug:  changing the language don't change country name translation.

**To Reproduce**
Just start an installer on a clean server and change the language or change the language later using admin interface (yes corresponding language pack was downloaded in case of admin interface)
**Screenshots**
![presta-lang-bug](https://user-images.githubusercontent.com/35946301/70837453-6750a280-1e0c-11ea-9767-fbf465c4dec3.jpg)

**Additional information**
Affected PrestaShop version: 1.7.6.1, 1.7.6.2
No such bug on 1.7.3.2
PHP version: any including 7.2

**Comment by khouloudbelguith** [comment]
Hi @rss9090,

Have you the same issue with this ticket: #12168?

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 
> Have you the same issue with this ticket: #12168?
> 
> Thanks!

I think yes.

**Comment by khouloudbelguith** [comment]
@rss9090,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12168
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #12168
