### ISSUE TITLE
Decimals issue with no solution yet v-1.7.6.2

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#16805]
I have a problem and i don't know if is a bug.
The problem it's on currency decimals.

![image](https://user-images.githubusercontent.com/11914764/70820734-fd4de400-1d9e-11ea-921c-89e49be608ef.png)

Real Price is "**$1,122.51**" (MXN)

I see in forums the same problem and possible solution and i did tried but isn't works:
I have "_main--es-ES--numbers_" file but not exist
![image](https://user-images.githubusercontent.com/11914764/70821272-4bafb280-1da0-11ea-900e-49d30c0a3895.png)

modifying "_/localization/CLDR/core/common/main/_" with this [reference](https://www.rolige.com/es/blog/cambiar-el-simbolo-y-la-posicion-de-la-moneda-en-prestashop-176-n9)
This is my file:
![image](https://user-images.githubusercontent.com/11914764/70823773-52d9bf00-1da6-11ea-9c4a-5a18d2ae3bb4.png)

modifying "_js/tools.js"
![image](https://user-images.githubusercontent.com/11914764/70823978-c4b20880-1da6-11ea-9608-bc39ed887269.png)
![image](https://user-images.githubusercontent.com/11914764/70823998-ced40700-1da6-11ea-8bce-eca768425cec.png)

and modifying database:
![image](https://user-images.githubusercontent.com/11914764/70824053-f62ad400-1da6-11ea-99de-c85371b7bfdc.png)

PrestaShop version: 1.7.6.2
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @P41N3ST,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version.
The first part of feature #[10052](https://github.com/PrestaShop/PrestaShop/issues/10052) is almost done which the implementation of the CLDR (the data needed to manage a maximum of currencies), Check the PR #10455

It's planned to remove the number of the decimal parameter in Shop parameters > General, as you can see here: #12223
And it's also planned to add this feature in CLDR part 2: #11660

Thanks to check & feedback.
