### ISSUE TITLE
Customer management backend [PHP Notice] Undefined index: _route

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#16812]
Hi I am getting the following notice: `PHP Notice:  Undefined index: _route in /../src/PrestaShopBundle/Controller/Admin/CommonController.php on line 121`

I think it has to do with the paginator.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.3.12

**Comment by khouloudbelguith** [comment]
Hi @kenlog,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version.

**Comment by kenlog** [comment]
Hi @khouloudbelguith it's probably caused by the php version, thanks :wink:

**Comment by khouloudbelguith** [comment]
@kenlog, thanks for your feedback.
Feel free to open a new one when needed.

**Comment by FeyaParis** [comment]
Hello,
I have the same error on all admin page :
PHP Notice: Undefined index: _route in /../src/PrestaShopBundle/Controller/Admin/CommonController.php on line 121

Prestashop : 1.7.6.5 but it was also appearing on 1.7.6.4
Php : 7.2.28

This solution fix it :
// $routeName = $request->attributes->get('caller_route', $request->attributes->get('caller_parameters', ['_route' => false])['_route']);
$routeN1 = $request->attributes->get('caller_parameters', ['_route' => false]);
if (!isset($routeN1['_route'])) {
    $routeN1['_route'] = false;
}
$routeName = $request->attributes->get('caller_route', $routeN1['_route']);

But I would prefer to not edit prestashop core files.

Anyone can help please ?

**Comment by FeyaParis** [comment]
Found the problem
If anyone else has this problem it's caused by :
Login As Customer v0.7.2 - par PrestaShopModul

**Comment by soymiguelfigueroa** [comment]
> 
> 
> Found the problem
> If anyone else has this problem it's caused by :
> Login As Customer v0.7.2 - par PrestaShopModul

@FeyaParis I don't understand your reply, can  you give us more information about?

**Comment by FeyaParis** [comment]
When Login As Customer v0.7.2  is installed this error happen once it's uninstalled everything is ok
