### ISSUE TITLE
Product page does not show 'instead of %price%' when pack components price is >= 1000 euros

### ISSUE THREAD

**Issue by cesarfierro** [PrestaShop/PrestaShop#16811]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by cesarfierro** [comment]
Prestashop 1.7.6.1
B2B enabled.

Product page does not show 'instead of %price%' when pack components price is >= 1000 euros

To reproduce just create a pack with the sum of the prices of its components be less than 1000 euros.
Go to the front office and click on the product, you will see the 'instead of' label under the price.
Now increase the price of any component so that the total sum is greater than or equal to 1000 euros. If you chick the product again, the 'instead of' tag will be gone.

Regards
Cesar
![Anotación 2019-12-14 100302](https://user-images.githubusercontent.com/47951167/70847468-b1fa0b00-1e5c-11ea-8b7f-0f201c46b57a.png)
![Anotación 2019-12-14 100718](https://user-images.githubusercontent.com/47951167/70847469-b1fa0b00-1e5c-11ea-960e-eb645e6e68a8.png)

**Comment by mariem-abid** [comment]
Hi @cesarfierro,

Are you using the template by default of Prestashop?

Thanks!

**Comment by cesarfierro** [comment]
Hello
I have checked it with Cassic Theme and I get the same result.
![Captura1](https://user-images.githubusercontent.com/47951167/71161702-c0239f00-2241-11ea-96b0-7b691ec39f5f.PNG)
![Captura2](https://user-images.githubusercontent.com/47951167/71161703-c0239f00-2241-11ea-93dc-2a256ef935c1.PNG)

**Comment by khouloudbelguith** [comment]
Hi @cesarfierro,

What is your exact version PrestaShop did you use?

Thanks!

**Comment by cesarfierro** [comment]
Hello
I have tested it with 1.7.6.1 and 1.7.6.2

Regards

**Comment by cesarfierro** [comment]
And B2B enabled

**Comment by khouloudbelguith** [comment]
@cesarfierro, with fresh install PS1.7.6.2, I don't have the expression` instead of`
![image](https://user-images.githubusercontent.com/16067358/71177214-c595df00-226b-11ea-84df-0408425b4ca3.png)
Did you edit your classic theme?

Thanks!

**Comment by cesarfierro** [comment]
No, I don´t edit it. 

I tried with a new pack of two components and set your prices. I have obtained the same result as you, no 'instead of'

But if you use my prices:
Pack 800.00, T-shirt 250.00 and Pantalon 749.99, the expression is showed.

Regards.
![Captura3](https://user-images.githubusercontent.com/47951167/71199165-444f4400-228d-11ea-9954-d79af9f79157.PNG)
![Captura4](https://user-images.githubusercontent.com/47951167/71199166-44e7da80-228d-11ea-9f4d-67ddc5f4e756.PNG)

**Comment by khouloudbelguith** [comment]
@cesarfierro, no with fresh install PS1.7.6.2.
I don't have this expression
![image](https://user-images.githubusercontent.com/16067358/71241111-13155900-230b-11ea-933f-4d4410536e29.png)

Thanks!

**Comment by cesarfierro** [comment]
I have been upgrading since  1.6, may be time for a fresh install.

Thanks for your time!

**Comment by khouloudbelguith** [comment]
@cesarfierro, yes!
With PS1.6.1.24, it was displayed
![image](https://user-images.githubusercontent.com/16067358/71244361-9d14f000-2312-11ea-85a9-9a1b12ef6202.png)
But, not the same behavior with PS1.7.6.2.
I close the issue, feel free to open a new one when needed.

Thanks!
