### ISSUE TITLE
Multistore configuration - 2nd shop shows products from other shops

### ISSUE THREAD

**Issue by lordchukz** [PrestaShop/PrestaShop#16810]
Hi everyone, I need an advice/help in multistore configuration
![Screen Shot 2019-12-14 at 08 04 29](https://user-images.githubusercontent.com/36967295/70845184-caadf500-1e4b-11ea-8e00-0eb6589c0323.png)
 on prestashop, hopefully this is the right place to be to get a valid response.

I decided to create a multishop environment for my site’s categories since it’s growing and I would love to improve user experience so they find the relative products of their interest based on the category niche.

I was able to create new shops with 2 default groups.

Default 1 - Mainly Europe and maybe rest of the world
Default 2 - Africa

The domain names are all registered and different from each other representing each category niche (example, shoes category gets shoes.com as category).

All shops are actually underdevelopment except for the main shop and one second shop: https://lordsutensili.com

Here is the structure.
		
Default1
	Mainsite
		mainsite.eu
	shop1
		shop1.com
	shop2
		shop2.com
	shop3
		shop3.com
Default2
	shop4
		shop4.africa

Everything working super fine, but I have a few hiccups 1 doubt.

Question: Sto wise, is this decision harmful for my overall ranking? If so, please can somebody give me an alternative solution.

Hiccups:

1, Each shop was created with designated categories, which are te only products that appear in the front end, unfortunately, the controller’s still include other products in them such as in the new product section, offers, best sales and also the producers appear in the sitemap page. 

I share products and their relative quantities among all shops.

How can I share orders and customers?

2, How possible is it for me to make each shop representing a particular category and their products get the link juice from main shop.

Let me explain myself better, Mainsite is the head office where all administrative operations are performed while the various shops are the operative offices where purchase should be performed.

I want to make main site neutral where visitors can only access by direct link, while I need to redirect the organic searches(indexed urls) to the various shops that handle the specific products.

Hopefully I am able to explain myself properly.

Big thanks in advance to who would assist me.

Best wishes.

**Comment by mariem-abid** [comment]
Hi @lordchukz,

Could you please follow this documentation: http://doc.prestashop.com/display/PS17/Managing+Multiple+Shops

Thanks for check and feedback.

**Comment by lordchukz** [comment]
Thank you @mariem-abid for your kind response.

I actually found and implemented a solution for shared customers.

Shared cart remains disabled as each store should have a separate order history.

I unfortunately still don't have a solution for "_the controller’s still include other products in them such as in the new product section, offers, best sales and also the producers appear in the sitemap page._"

Also, a solution for question number 2 would be much appreciated.

Thanks once again for your attention and time.

Regards.

**Comment by khouloudbelguith** [comment]
Hi @lordchukz,

>How can I share orders and customers?

If you have already registered customers & orders, it will be not possible to enable those options, this is impossible

But we will work on it as reported here: https://github.com/PrestaShop/PrestaShop/issues/16804
>How possible is it for me to make each shop representing a particular category and their products get the link juice from main shop.

Ping @marionf what do you think?

Thanks!

**Comment by marionf** [comment]
Hello @lordchukz 

> I want to make main site neutral where visitors can only access by direct link, while I need to redirect the organic searches(indexed urls) to the various shops that handle the specific products.

I am not sure to understand what you want to do and mean by "redirect the organic searches(indexed urls) to the various shops"

Do you have an example ?

**Comment by lordchukz** [comment]
Thanks @khouloudbelguith, Now I have customers shared thanks to the link @mariem-abid shared 
(I exported all ps_customer tables via phpmyadmin, dropped the tables and was able to switch the share customer feature on. Then I only imported the ps_customer sql file previously exported and had all customers restored without errors).

Orders are ok to be shop dedicated with it's order history for better marketing and analytics.
Naturally, #16804 is worth working on for other merchants that prefer sharing orders.

@marionf, let me try explain myself better. 

Main shop is the head office that distributes all informations to other shops, it has been fully indexed by google. 

New shops are meant to give better experience to niche users since product categories in main shop are far from each other, "a tools shop has nothing to do with a clothing shop, as a result when someone visits main shop from indexed urls for clothes and sees also tools, this person might get confused since he/she was expecting to see only clothes). This also might cause high bounce rate.

Unfortunately I did not foresee this when I started, but understanding this reality, I intend to make necessary amendments.

As a result, I need main shop to be accessible only by users who has a direct link, while the main shop urls that are already on google (indexed) be redirected to dedicated shop. This also will help the entire systems from being penalised for duplicate/copied content. (From see aspects I have read through, it is not best to have same contents from different urls. Please correct me if I'm wrong)

I really don't know the possibilities to achieve this. I tried with a redirect module and realised I have to do it manually for every url.
Moreover, with the redirect module, anybody that access main shop by direct url can only view the landing page thus by navigating to another product page will be redirected to that **product page dedicated shop** creating also a bad user experience (because user might want to remain on main shop.

A simplified example is in the attached image.

When someone clicks on an indexed url Main-shop via google search, the person should be taken to Dedicated-shop landing page.

I know it is possible to tell google that site has been moved, unfortunately it is intended for only the domain excluding the category paths. It is impossible for me to use this feature since I have 4 sub shops.

Thanks a lot for your attention.

Regards.

![Screen Shot 2019-12-19 at 08 42 25](https://user-images.githubusercontent.com/36967295/71155317-b5ffa180-223d-11ea-98f7-47827121b7d3.png)

**Comment by lordchukz** [comment]
Forgot to mention this.

Each shop were dedicated their specific categories without sharing any, but unfortunately I cannot create the shop without selecting main  "home" category.

I tried creating a main "home" category for one shop (as a test) but the shop category (example "tools") can be attributed only to one main "home" category.

If I should do this, main shop will loose "tools" category. There is a way to allocate a sub-category to 2 "home" categories simultaneously?

The controller’s still include other shop products in them such as in the new product section, offers, best sales and also the producers appear in the sitemap page.

See video: https://www.dropbox.com/s/l0949u76f23u6it/ScreenRecord%202019-12-19%2009-10-17.mov?dl=0

**Comment by lordchukz** [comment]
Happy new year all, I'm sure you all had a great time these festive days. 

Just to know if there has been an update to this issue. 

Thanks.

**Comment by marionf** [comment]
Hello @lordchukz 

Thank you very much and happy new year to you too !

> I need main shop to be accessible only by users who has a direct link, while the main shop urls that are already on google (indexed) be redirected to dedicated shop

Unfortunately, there is no such option basically with PrestaShop to do that
You should look if there is such a module on our marketplace: https://addons.prestashop.com/

**Comment by lordchukz** [comment]
Thanks @marionf, unfortunately there is no module on Addons for this need.

Kind regards.
