### ISSUE TITLE
The price range slider seems not to see all specific prices

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#16822]
**Describe the bug**

The price range slider seems not to see all specific prices (only the first specific price seems to be taken into account):

1. The highest price displayed is incorrect

2. When we move the cursor of the slider, the product is filtered, because only the lowest price is considered

**To Reproduce**

1. Create a category

2. On this category, create a product (50 € tax excl.)

3. Create a specific price (from quantity 3, 40 € tax excl.)

4. Create a specific price (from quantity 5, 30 € tax excl.)

5. Show price range slider (tax excl.)

6. Go on the shop, on the created category

*Note: the prices and quantities do not matter, they are only examples.*

*Note 2: this is a simplified example with only one product.*

**Screenshots**

The slider, from 30 (lowest price) to 40 (the price of quantity 3) instead of (two possibilities):

1. 30 (lowest price) to 50 (highest price)
2. 30 (lowest price) to 30 (if we consider only the lowest price)

![image](https://user-images.githubusercontent.com/22885898/70894603-9d00b180-1fed-11ea-85b6-2754fb284d1c.png)

Before filter:
![image](https://user-images.githubusercontent.com/22885898/70894963-53649680-1fee-11ea-8ccf-693017015d88.png)

After filter:
![image](https://user-images.githubusercontent.com/22885898/70894994-64150c80-1fee-11ea-9084-151cdbfa0ef4.png)

**Additional information**

PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @yannicka,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2 & ps_facetedsearch v3.4.0.
![image](https://user-images.githubusercontent.com/16067358/70899297-a8a4a600-1ff6-11ea-8cae-9736c2792f51.png)
![image](https://user-images.githubusercontent.com/16067358/70899356-c114c080-1ff6-11ea-8f35-14a0f01ee9ec.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud

**Comment by luisfbmelo** [comment]
Is this already fixed? I'm having this issue on version 3.4.1.

**Comment by khouloudbelguith** [comment]
Hi @luisfbmelo,

Sorry not yet.
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @khouloudbelguith 

While reproducing this issue #22621 I didn't manage to reproduce your issue with PS1.7.6.9 and FacetedSearch v3.7, see the attached screen record below:

https://drive.google.com/file/d/158hPfA2ZQCPFKrvc9WlXXvfiQ8B-iF47/view

Please check and feedback.
Thanks!

**Comment by PierreRambaud** [comment]
I don't know if it's the right behavior now (with this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/300)

If I search for products that cost 15, it now finds all products with this price and shows a discount if possible.
![image](https://user-images.githubusercontent.com/1462701/103357099-a2bf1d00-4ab2-11eb-9da4-5778a230e9be.png)

And if I search for products that cost 10, it displays only specific prices:
![image](https://user-images.githubusercontent.com/1462701/103357146-bf5b5500-4ab2-11eb-99c6-975fafc117c3.png)

**Comment by marionf** [comment]
> If I search for products that cost 15, it now finds all products with this price and shows a discount if possible.
![image](https://user-images.githubusercontent.com/1462701/103357099-a2bf1d00-4ab2-11eb-9da4-5778a230e9be.png)

@PierreRambaud 

I think in this case the first product shouldn't be displayed, as with the discounted price it's not in the price range selected.
If there is a specific price, we should take it into account and not the crossed out price

**Comment by PierreRambaud** [comment]
> > If I search for products that cost 15, it now finds all products with this price and shows a discount if possible.
> > ![image](https://user-images.githubusercontent.com/1462701/103357099-a2bf1d00-4ab2-11eb-9da4-5778a230e9be.png)
> 
> @PierreRambaud
> 
> I think in this case the first product shouldn't be displayed, as with the discounted price it's not in the price range selected.
> If there is a specific price, we should take it into account and not the crossed out price

Not sure the way how faceted search indexes prices will allow this behaviour :sweat_smile:
