### ISSUE TITLE
Can't use Title 1 2 3 in text editor, presta 1.7.6.1

### ISSUE THREAD

**Issue by Mduclain** [PrestaShop/PrestaShop#16827]
Hi, 
In admin/product page, when I format text with Title 1 2 3 and save, my text is notre in title 1 2 3 but in paragraph

**Comment by mariem-abid** [comment]
Hi @Mduclain,

I did not manage to reproduce the issue with PS:1.7.6.2.
I attached a video record.
https://drive.google.com/file/d/1mSaB8oEd6_uQoACyUO8VHzbeO2jx85LU/view

Thanks for check and feedback.

**Comment by Mduclain** [comment]
Hi, 

Thx for your reply. 
I found it by myself, I just did it wrong during my first tries ... It works fine

**Comment by khouloudbelguith** [comment]
Hi @Mduclain,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
