### ISSUE TITLE
Error 500 - upgrade 1.7.4.3 to 1.7.6.2

### ISSUE THREAD

**Issue by Swanlefta** [PrestaShop/PrestaShop#16825]
Hello, I am asking you today because I am at an impasse.
After doing the update to 1.7.2.6 I get an error 500, after activating the debug I end up with a more complete error detail, can you direct me a little and help me find a solution for fix that.

Thank you in advance for your help. 🙏
(sorry for my bad English, I'm French)

Error :

<img width="1076" alt="Capture d’écran 2019-12-12 à 15 52 30" src="https://user-images.githubusercontent.com/58937709/70899609-44361680-1ff7-11ea-8d45-10a480858fa0.png">

Configuration :

<img width="2334" alt="Capture-d-cran-2019-12-12-18-26-14" src="https://user-images.githubusercontent.com/58937709/70899680-629c1200-1ff7-11ea-8402-d6f7ca272f1f.png">

**Comment by khouloudbelguith** [comment]
Hi @Swanlefta,

What is the exact version of the 1-click upgrade v4.10.0?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Swanlefta** [comment]
Problem solved, ty

**Comment by khouloudbelguith** [comment]
@Swanlefta,

Thanks for your feedback.
Feel free to open a new one needed.
