### ISSUE TITLE
Question: The product payment selection causes the price to increase. The price of the product is automatically modified directly. The background price is also automatically changed. For the first feedback, I do n’t know if the release method is wrong. Please inform me if there is something wrong! Thank you!

### ISSUE THREAD

**Issue by golden1688** [PrestaShop/PrestaShop#16835]
**Describe the bug**

Question: The product payment selection causes the price to increase. The price of the product is automatically modified directly. The background price is also automatically changed. How to do? 

For the first feedback, I do n’t know if the release method is wrong. Please inform me if there is something wrong! Thank you!

**To Reproduce**
1. Go to 'shopping.dog'
2. Click on ' Any product'
3. Scroll down to 'Product style, choose back and forth, you will find that the price automatically increases'
4. See error:You will find that the price increases automatically

**Video**
[20191216_172434mov.zip](https://github.com/PrestaShop/PrestaShop/files/3972022/20191216_172434mov.zip)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.25
How to do?

**Comment by khouloudbelguith** [comment]
Hi @golden1688,

Thanks for your report.
Did you make any changes to the Core of PrestaShop?
Those products are created manually? or imported via csv file?
In the BO => Shop Parameters => Product Settings page => "Quantity discounts based on " => `Products` or `Combinations`?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by golden1688** [comment]
Hello there!
Great technical support:
Make it easier for you to check and find out the problem. How do I send you an account password? Thank you!
                                                             Your loyal customer golden1688

**Comment by golden1688** [comment]
Hello there!
1. The core files have not been modified since the program was installed.
Just buy and install the application module
2. The products are collected by AliExpress modules, and the module developers have ruled out their modules.
3. The product has no set combination

**Comment by golden1688** [comment]
> 嗨@ golden1688，
> 
> 感谢您的举报。
> 您是否对PrestaShop的核心进行了任何更改？
> 这些产品是手动创建的？或通过CSV文件导入？
> 在BO =>商店参数=>产品设置页面=>“基于” => `Products`或`Combinations`？的数量折扣
> 我们需要检索PHP错误日志和调试模式报告，以找出问题所在。
> 您不知道如何获取此信息吗？请阅读以下文章：[http](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/) :
> [//build.prestashop.com/howtos/misc/how-to-create-bug-report/](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/)
> 
> 谢谢！
Hello there!
1. The core files have not been modified since the program was installed.
Just buy and install the application module
2. The products are collected by AliExpress modules, and the module developers have ruled out their modules.
3. The product has no set combinationGreat technical support:
Make it easier for you to check and find out the problem. How do I send you an account password? Thank you!
                                                             Your loyal customer golden1688

**Comment by khouloudbelguith** [comment]
@golden1688, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by golden1688** [comment]
> @ golden1688，能否请您提供给我进入您的商店进行测试的权限。
> 这是一个公共空间。
> 您可以通过电子邮件向我提供凭据。
> 我的地址邮件：[khouloud.belguith@prestashop.com请](mailto:khouloud.belguith@prestashop.com)
> 放心！
> 
> 谢谢！

Hello there!
I have mailed you, please check the mail, thank you!

**Comment by khouloudbelguith** [comment]
@golden1688, thanks!
I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@golden1688, when debug mode enabled, I did not find any exception.
The price is increasing when selecting any combination.
We need PHP error logs. If you don't have it, you should ask your hosting provider.

Thanks!

**Comment by golden1688** [comment]
> @golden1688, when debug mode enabled, I did not find any exception.
> The price is increasing when selecting any combination.
> We need PHP error logs. If you don't have it, you should ask your hosting provider.
> 
> Thanks!

Hello there! Great technical support:
I have already asked the server vendor to take a PHP error diary. If there is a reply, I will send it to you immediately. Thank you!
                             Yours faithful customers

**Comment by khouloudbelguith** [comment]
@golden1688, great!
Waiting for your feedback.

Thanks!

**Comment by golden1688** [comment]
Hello there!
Great technical support:
I enabled the PHP error journal according to the instructions of the server vendor. After several hours, no files were found. Do I need to wait? The account password of the server has been sent to you by email. You can log in, check and find the cause of the problem! Thank you!
                                                        Your loyal customers

> @ golden1688，太好了！
> 等待你的反馈。
> 
> 谢谢！
Hello there!
Great technical support:
I enabled the PHP error journal according to the instructions of the server vendor. After several hours, no files were found. Do I need to wait? The account password of the server has been sent to you by email. You can log in, check and find the cause of the problem! Thank you!
                                                        Your loyal customers

**Comment by khouloudbelguith** [comment]
@golden1688,  I did not find any exception in the FO.
Could you please provide me the log file, you can find it in this path `Project_PrestaShop_Folder/var/logs`.

Thanks!

**Comment by golden1688** [comment]
> @ golden1688，我在FO中没有发现任何异常。
> 您能否提供给我日志文件，您可以在此路径中找到它`Project_PrestaShop_Folder/var/logs`。
> 
> 谢谢！
Hello there!
Great technical support:
Okay, thank you!
I found that there are many files in it. Are they packaged and sent to you together? Or do you log in to choose?
Thank you!

                                                        Your loyal customer G

**Comment by khouloudbelguith** [comment]
@golden1688, you can provide me the zip folder.

Thanks!

**Comment by golden1688** [comment]
> @golden1688, you can provide me the zip folder.
> 
> Thanks!
Hello there!
Great technical support:
Okay, thank you!
Attachment of diary file in email!
                                                       Your loyal customer G

**Comment by khouloudbelguith** [comment]
@golden1688, Thanks!
I will check & feedback.

**Comment by khouloudbelguith** [comment]
@golden1688, I found those errors
>[2019-12-08 02:19:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function find() on boolean" at /home/mallax/shopping.dog/modules/g_aliexpress/g_aliexpress.php line 643 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function find() on boolean at /home/mallax/shopping.dog/modules/g_aliexpress/g_aliexpress.php:643)"} []

This error is related to the `g_aliexpress` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
>[2019-12-16 21:55:04] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/getPrestashop_Module_ManagerService.php' (include_path='/home/mallax/shopping.dog/vendor/pear/pear_exception:/home/mallax/shopping.dog/vendor/pear/console_getopt:/home/mallax/shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear')" at /home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php line 1633 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/getPrestashop_Module_ManagerService.php' (include_path='/home/mallax/shopping.dog/vendor/pear/pear_exception:/home/mallax/shopping.dog/vendor/pear/console_getopt:/home/mallax/shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') at /home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php:1633)"} []

You need to clear cache manually by deleting all the folder into var/cache (prod & dev).
>*ERROR* 	v1.7.6.1	2019/12/17 - 03:10:46: Property Product->price is empty. at line 1004 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.1	2019/12/17 - 04:30:09: Property Combination->id_product is empty. at line 1004 in file classes/ObjectModel.php

I think those errors related to this: `The products are collected by AliExpress module`
Thanks to check and feedback.

**Comment by golden1688** [comment]
> @ golden1688，我发现了那些错误
> 
> > [2019-12-08 02:19:00] request.CRITICAL：未捕获的PHP异常Symfony \ Component \ Debug \ Exception \ FatalThrowableError：“在/home/mallax/shopping.dog上调用布尔函数成员find（）” /modules/g_aliexpress/g_aliexpress.php第643行{“ exception”：“ [object]（Symfony \ Component \ Debug \ Exception \ FatalThrowableError（code：0）：在/ home / mallax上以布尔值调用成员函数find（） /shopping.dog/modules/g_aliexpress/g_aliexpress.php:643）“} []
> 
> 此错误与`g_aliexpress`模块有关。
> 由于它不是Prestashop提供的模块，因此我们无法执行任何操作。
> 您应该通过addons.prestashop.com帐户与模块作者联系，他们是唯一可以帮助您的人。
> 
> > [2019-12-16 21:55:04] request.Critical：未捕获的PHP异常Symfony \ Component \ Debug \ Exception \ FatalErrorException：“编译错误：require（）：无法打开所需的'/home/mallax/shopping.dog/ var / cache / prod / ContainerJogrhcg / getPrestashop_Module_ManagerService.php'（include_path ='/ home / mallax / shopping.dog / vendor / pear / pear_exception：/home/mallax/shopping.dog/vendor/pear/console_getopt：/ home / mallax /shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear'）“ /home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php第1633行{“ exception”：“ [object]（Symfony \ Component \ Debug \ Exception \ FatalErrorException（code：0）：编译错误： require（）：无法打开所需的'/ home / mallax / shopping。dog / var / cache / prod / ContainerJogrhcg / getPrestashop_Module_ManagerService.php'（include_path ='/ home / mallax / shopping.dog / vendor / pear / pear_exception：/home/mallax/shopping.dog/vendor/pear/console_getopt：/ home /mallax/shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear'）在/home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php:1633）“} []dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633）“} []dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633）“} []
> 
> 您需要通过将所有文件夹删除到var / cache（prod＆dev）中来手动清除缓存。
> 
> > _错误_  	v1.7.6.1 2019/12/17-03:10:46：属性Product-> price为空。在文件类 	/ObjectModel.php 
> > _错误_ v1.7.6.1 2019/12/17第12 行1004 ：属性组合-> id_product为空。在文件class / ObjectModel.php的第1004行
> 
> 我认为这些错误与此有关：`The products are collected by AliExpress module`
> 感谢检查和反馈。

Hello there!
Great technical support:
Thanks for your check and feedback!
I immediately contacted the module developers and asked them to fix the problem! Thank you!
                                      Your loyal customer G

**Comment by golden1688** [comment]
> > @ golden1688，我发现了那些错误
> > > [2019-12-08 02:19:00] request.CRITICAL：未捕获的PHP异常Symfony \ Component \ Debug \ Exception \ FatalThrowableError：“在/home/mallax/shopping.dog上调用布尔函数成员find（）” /modules/g_aliexpress/g_aliexpress.php第643行{“ exception”：“ [object]（Symfony \ Component \ Debug \ Exception \ FatalThrowableError（代码：0）：在/ home / mallax上以布尔值调用成员函数find（ ）/shopping.dog/modules/g_aliexpress/g_aliexpress.php:643）“} []
> > 
> > 
> > 此错误与`g_aliexpress`模块有关。
> > 由于它不是Prestashop提供的模块，因此我们无法执行任何操作。
> > 您应该通过addons.prestashop.com帐户与模块作者联系，他们是唯一可以帮助您的人。
> > > [2019-12-16 21:55:04] request.Critical：未捕获的PHP异常Symfony \ Component \ Debug \ Exception \ FatalErrorException：“编译错误：require（）：无法打开所需的'/ home / mallax / shopping.dog/ var /缓存/产品/ ContainerJogrhcg / getPrestashop_Module_ManagerService.php'（include_path ='/ home / mallax / shopping.dog /供应商/ pear / pear_exception：/home/mallax/shopping.dog/vendor/pear/console_getopt： / home / mallax /shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear '）“ /home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php第1633行{“ exception”：“ [object]（Symfony \ Component \ Debug \ Exception \ FatalErrorException（代码：0） ：编译错误：require（）：无法打开所需的'/ home / mallax / shopping。狗/ var /缓存/产品/ ContainerJogrhcg / getPrestashop_Module_ManagerService.php'（include_path ='/ home / mallax / shopping.dog /供应商/ pear / pear_exception：/home/mallax/shopping.dog/vendor / pear / console_getopt：/ home /mallax/shopping.dog/vendor/pear/pear-core-minimal/src:/home/mallax/shopping.dog/vendor/pear/archive_tar:.:/opt/alt/php72/ usr / share / pear'）在/home/mallax/shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php:1633）“} [] dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633 ）”} [] dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633）”} []dog / vendor / pear / pear-core-minimal / src：/home/mallax/shopping.dog/vendor/pear/archive_tar：。：/ opt / alt / php72 / usr / share / pear'）在/ home / mallax /shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php:1633）”} [] dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633）“} [] dog / var / cache / prod / Cond / ContainerJogrhcg / appProdProjectContainer.php：1633）“} []dog / vendor / pear / pear-core-minimal / src：/home/mallax/shopping.dog/vendor/pear/archive_tar：。：/ opt / alt / php72 / usr / share / pear'）在/ home / mallax /shopping.dog/var/cache/prod/ContainerJogrhcg/appProdProjectContainer.php:1633）”} [] dog / var / cache / prod / ContainerJogrhcg / appProdProjectContainer.php：1633）“} [] dog / var / cache / prod / Cond / ContainerJogrhcg / appProdProjectContainer.php：1633）“} []
> > 
> > 
> > 您需要通过将所有文件夹删除到var / cache（prod＆dev）中来手动清除缓存。
> > > _错误_   	v1.7.6.1 2019/12 / 17-03：10：46：属性Product-> price为空。在文件类/ObjectModel.php 
> > > _错误_ v1.7.6.1 2019/12/17第12行1004：属性组合-> id_product为空。在文件类/ ObjectModel.php的第1004行
> > 
> > 
> > 我认为这些错误有关：`The products are collected by AliExpress module`
> > 感谢检查和反馈。
> 
> 你好！
> 强大的技术支持：
> 感谢您的检查和反馈！
> 我立即联系模块开发人员，并要求他们解决问题！谢谢！
>                                       您的忠实客户G

Hello there!
Great technical support:
I contacted the AliExpress module developer, and they said it was not their module problem, what should I do? The following is the original reply from the developer:

This problem is not caused by our module. You can clear cache and test again. If it is a problem with our module, the price will not update anymore if the module is disabled. But when we disabled our module, prices are still updated. How to do?
Could you please help us check again? Thank you!


                                      Your loyal customer G

**Comment by golden1688** [comment]
Hello there!
Great technical support:
I contacted the AliExpress module developer, and they said it was not their module problem, what should I do? The following is the original reply from the developer:

This problem is not caused by our module. You can clear cache and test again. If it is a problem with our module, the price will not update anymore if the module is disabled. But when we disabled our module, prices are still updated. How to do?
Could you please help us check again? Thank you!

                                      Your loyal customer G

**Comment by khouloudbelguith** [comment]
@golden1688, but those products are just imported with this module.
I tried to create a product manually & it is OK
I attached a screen record
https://drive.google.com/file/d/1Vup8w31FweCAiCJKhvGUazxd5DkJhy7-/view
You need to import a new product with this module & check prices.
Thanks to check & feedback.

**Comment by golden1688** [comment]
> @golden1688, but those products are just imported with this module.
> I tried to create a product manually & it is OK
> I attached a screen record
> https://drive.google.com/file/d/1Vup8w31FweCAiCJKhvGUazxd5DkJhy7-/view
> You need to import a new product with this module & check prices.
> Thanks to check & feedback.



Hello there!
Great technical support:
Thank you very much for your help, and have contacted the module developer in time! Thank you!
                                              Your loyal customer G

**Comment by khouloudbelguith** [comment]
@golden1688, Thanks!

Waiting for your feedback.

**Comment by golden1688** [comment]
> @ golden1688，谢谢！
> 
> 等待您的反馈意见。

Hello there!
Great technical support:
The reason was found. It turned out that the Advance SEO module called the product update function, which caused the problem.
right now
The problem has been solved. Advance SEO developers have added a product controller file override / controllers / front / ProductController.php. Thank you very much for your help, thank you!
                                                                      Your loyal customer, G

**Comment by khouloudbelguith** [comment]
@golden1688, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
