### ISSUE TITLE
Total order price error

### ISSUE THREAD

**Issue by smag-dev** [PrestaShop/PrestaShop#16832]
when adding a product to the cart with price XX.05 € and adding a discount voucher of 10%, the total price of the order is wrong

1. Prestashop clean installation
2. Create a discount voucher on total order with 10% off
3. add to cart product Mountain fox cushion (reference: demo_15)
4. Click on cart to view products
5.Add discount voucher and see total order price with value error

**Screenshots**
Cart Rule
![Screenshot from 2019-12-16 15-26-34](https://user-images.githubusercontent.com/14795225/70923808-68f2b400-2020-11ea-856a-b50dbe609711.png)
![Screenshot from 2019-12-16 15-27-12](https://user-images.githubusercontent.com/14795225/70923809-68f2b400-2020-11ea-821f-da2b139ebdcf.png)
![Screenshot from 2019-12-16 16-21-33](https://user-images.githubusercontent.com/14795225/70923810-698b4a80-2020-11ea-9639-7439b6f53ea1.png)

Total order price with value error
![Screenshot from 2019-12-16 16-20-56](https://user-images.githubusercontent.com/14795225/70924017-c38c1000-2020-11ea-8a1b-910f71be78c7.png)

**Additional information**
PrestaShop version: 1.7.6.1, 1.7.6.2 (I did not test with lower versions)
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @aguia10,

Thanks for your report.
What is the exact error with the order price?
![image](https://user-images.githubusercontent.com/16067358/70974818-fda0f480-20a8-11ea-9c67-d83deb8afcfb.png)
Total products =23.25 Tax included
Discount= 10%
Total = Total products - discounts = 23.25 -10% = 20.925 => after rounding => 20.93
Discount = 23.25 - (23.25-10%)  = 23.25-20.925 = 2.325 =>after rounding => 2.33

In your BO => Shop Parameters => General => You can find "Round mode" & "Round type.
You can configure it.
"Round mode" => "Round down towards zero, when it is half way there"
In the FO => 
![image](https://user-images.githubusercontent.com/16067358/70975993-4c4f8e00-20ab-11ea-84d2-e6dc2419cf2a.png)

Thanks to check & feedback.

**Comment by smag-dev** [comment]
Hi @khouloudbelguith ,

Thanks for your reply!

In both cases, the order prices (my example and your example) are wrong because the customer sees:
my example: 23.25 - 2.33 = 20.93 and  correct is 20.92
your example: 23.25 - 2.32 = 20.92 and  correct is 20.93

For me the problem is in the "round type" which by default is set to "Round each line", if the discount is a line first must be rounded and then subtracted from the total!
example : 
Total products =23.25 Tax included
Discount= 10%
Discount = 23.25*10% = 2.325  => after rounding => 2.33
Total = Total products - discounts = 23.25 -10% = 20.92

I did the same test (with others values) on a clean install of prestashop 1.6.1.24 and the values ​​are correct in both examples: 
Using :Round up away from zero, when it is half way there (recommended)
![Screenshot from 2019-12-18 17-21-42](https://user-images.githubusercontent.com/14795225/71108762-adff1d80-21bb-11ea-9361-ddeec70208dd.png)
![Screenshot from 2019-12-18 17-19-43](https://user-images.githubusercontent.com/14795225/71108778-b5bec200-21bb-11ea-92f8-2a97623e10ec.png)

Using :Round down towards zero, when it is half way there
![Screenshot from 2019-12-18 17-24-12](https://user-images.githubusercontent.com/14795225/71108826-cb33ec00-21bb-11ea-9d97-80d4992eee83.png)
![Screenshot from 2019-12-18 17-25-10](https://user-images.githubusercontent.com/14795225/71108840-d129cd00-21bb-11ea-8a9f-9d1c74e305bf.png)

Thanks

**Comment by khouloudbelguith** [comment]
Hi @aguia10,

Thanks for your feedback.
We have a different rounding problem, it is an issue that should be specified & fixed by our developers.
We are aware of this issue.
Your ticket is a duplicate of #9779
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9779

**Comment by smag-dev** [comment]
Hi @khouloudbelguith 

What version of prestashop will it be possible to fix?

Thanks

**Comment by khouloudbelguith** [comment]
@aguia10, Our product Team should specify this issue & then our Devs will fix it.
It is planned by our product team.

Thanks!
