### ISSUE TITLE
If the shop name contains special chars => the email subject will be incorrect

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16847]
**Describe the bug**
If the shop name contains special chars => the email subject will be incorrect.
For example if the shop name is äöüß ) => subject email => `[&auml;&ouml;&uuml;&szlig;]`
https://github.com/PrestaShop/PrestaShop/pull/16500#commitcomment-36445923
Thanks @JBWModules

**To Reproduce**
1. Go to BO => Shop Parameters => Contact
2. change Shop name `äöüß`
3. Check emails (Order confirmation email for example)
![image](https://user-images.githubusercontent.com/16067358/71082512-82ffd400-2191-11ea-8e40-ec5fb21c152a.png)

With PS1.7.6.1, as you can see in this ticket: https://github.com/PrestaShop/PrestaShop/issues/16499#issuecomment-557434129
the `Shop name` defined in the multistore page
If we change it in the multistore page => Ok
![image](https://user-images.githubusercontent.com/16067358/71082671-c78b6f80-2191-11ea-9ee0-9e5c14b06d1f.png)
With PS1.7.5.2 => OK

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud related to https://github.com/PrestaShop/PrestaShop/pull/16500

**Comment by PierreRambaud** [comment]
I was just following the patches in https://github.com/PrestaShop/PrestaShop/issues/16499 :sweat_smile:

**Comment by Progi1984** [comment]
I reopen it because I cherry pick the PR for 1.7.8.

**Comment by Progi1984** [comment]
Closed in #17608
