### ISSUE TITLE
1-Click Upgrade cannot update PrestaShop from 1.7.4.3 to 1.7.6.2

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#16845]
**Describe the bug**
Error occurred:
[2019-12-17 06:48:51] [INTERNAL] /home/virtwww/w_wedding***/http/admin***/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Call to a member function get() on null

See the log files in attach.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3977908/log.txt)
[PHP_errors.log](https://github.com/PrestaShop/PrestaShop/files/3977913/PHP_errors.log)

**Additional information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.38
MySQL version: 5.7.13-6-log
1-Click Upgrade version: 4.4.0

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

>1-Click Upgrade version: 4.4.0

The 1-click upgrade is an old version, the latest version is 4.10.0.
Did you not upgrade your module before?

THanks!

**Comment by weddingtextile** [comment]
I had two attempts to update the system.
First time I previously updated 1-Click to 4.10.0, but error occurred:
...
All files upgraded. Now upgrading database...
[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:" " jqXHR: " "

I hate this error.
So I tried to update with 1-Click 4.4.0.

One more moment, the pre-upgrade checklist (**1-Click 4.10.0**) had the message that my php version is obsolete.

**Comment by khouloudbelguith** [comment]
@weddingtextile,

>All files upgraded. Now upgrading database...
[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:" " jqXHR: " "

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

I need the log file when using the 1-click upgrade v4.10.0 & not the other version.

>So I tried to update with 1-Click 4.4.0.

This is a previous version, that's why you have issues during the upgrade, the upgrade of your database is corrupted.

Thanks!

**Comment by weddingtextile** [comment]
The third attempt was successful, but there are problems...

Faceted search cannot rebuild price index.
I have only 500 products and earlier the index updated in a few seconds.
The operation interrupted by timeout.

There are other errors, see the log file in attach.
[PHP_errors.log](https://github.com/PrestaShop/PrestaShop/files/3980866/PHP_errors.log)

**Comment by weddingtextile** [comment]
Faceted search cannot rebuild price index because I have products that are related to several categories. I removed additional links but only "Index all missing prices" works.

**Comment by khouloudbelguith** [comment]
@weddingtextile, thanks for your feedback.
>The third attempt was successful

Great!
What is the exact version of `ps_facetedsearch` did you use?
>[19-Dec-2019 00:12:36 Europe/Kiev] PHP Fatal error:  Maximum execution time of 120 seconds exceeded

In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```
Thanks to check & feedback

**Comment by weddingtextile** [comment]
Faceted search version is 3.4.0

In my php.ini file:
max_execution_time = 120
max_input_time = 60
memory_limit = 512

I had products that are related to several categories.
"Index all missing prices" and "Rebuild entire price index" didn't work. Error occurred: "PHP Fatal error: Maximum execution time of 120 seconds exceeded".

I removed additional product links to categories and "Index all missing prices" works now. A new index created in 1 second.
But "Rebuild entire price index" doesn't work. Error occurred: "PHP Fatal error: Maximum execution time of 120 seconds exceeded".

**Comment by khouloudbelguith** [comment]
@weddingtextile,

>PHP Fatal error: Maximum execution time of 120 seconds exceeded".

In your php.ini file, try to edit the `max_execution_time` from 120 to 300 for example, check & feedback.

Thanks!

**Comment by weddingtextile** [comment]
I tested that, not help.

**Comment by khouloudbelguith** [comment]
@weddingtextile, same errors?

Thanks!

**Comment by weddingtextile** [comment]
There are same errors in php_errors log file.
What is the problem?
See the log file in attach.
[PHP_errors.log](https://github.com/PrestaShop/PrestaShop/files/3983376/PHP_errors.log)

**Comment by khouloudbelguith** [comment]
@weddingtextile,

>[19-Dec-2019 13:30:06 Europe/Kiev] PHP Fatal error:  Uncaught exception 'Exception' with message 'Kernel Container is not available' in /home/virtwww/w_wedding***/http/src/Adapter/ContainerFinder.php:77

About this error, did you use a custom payment module?

Thanks!

**Comment by weddingtextile** [comment]
No, I didn't.
My list:
1) Cash on delivery (COD) v1.0.6 - by PrestaShop
2) Bank transfer v2.0.4 - by PrestaShop

**Comment by khouloudbelguith** [comment]
@weddingtextile, thanks to provide me a screenshot about your table ps_currency.
![image](https://user-images.githubusercontent.com/16067358/70512851-bbb80180-1b30-11ea-8f91-42ec62a53e2d.png)

Thanks!

**Comment by weddingtextile** [comment]
![ps_currency](https://user-images.githubusercontent.com/44600313/71245434-58db1d00-231d-11ea-9193-9a93af8e4bce.jpg)

**Comment by khouloudbelguith** [comment]
@weddingtextile, thanks for your feedback.
Could you please try to re-install the `ps_facetedseach` module by following these steps:
1. Uninstall the module with removing the folder
2. Try to clear cache manually by deleting all the folder into var/cache (prod & dev).
3. Go to the BO => Module Catalog page => install the module again

Thanks!

**Comment by weddingtextile** [comment]
I tried twice to reinstall the module.
It didn't help. There were same errors in the log file (((
Moreover, the function "Index all missing prices" also stopped working.
The strangest thing was after installing the module, I had to restart the web server.

So I restored the system from the archive.

**Comment by khouloudbelguith** [comment]
Hi @weddingtextile,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
THe phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by weddingtextile** [comment]
I know about this file.
The file is on my site.
[PHP PrestaShop Info.zip](https://github.com/PrestaShop/PrestaShop/files/3994451/PHP.PrestaShop.Info.zip)

**Comment by khouloudbelguith** [comment]
@weddingtextile, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
@weddingtextile, you have a proxy error

It is a server issue, thanks to check with your host & feedback.

Thanks!

**Comment by weddingtextile** [comment]
Delete image, please!!!!

**Comment by khouloudbelguith** [comment]
@weddingtextile, done :)

**Comment by weddingtextile** [comment]
It is not a server issue.
You didn't see the real problem because "Apache optimization = True".
I set "Apache optimization = False" and a real error is in the log file:
[23-Dec-2019 17:38:07 Europe/Kiev] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /home/virtwww/w_wed***/http/classes/SpecificPrice.php on line 528

**Comment by khouloudbelguith** [comment]
@weddingtextile, sorry, but I tried again & same issue occurs.
Thanks!

**Comment by weddingtextile** [comment]
You can’t understand a real problem in the browser.
See info from log files.

PHP_errors.log:

[23-Dec-2019 18:20:28 Europe/Kiev] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /home/virtwww/w_wed***/http/classes/SpecificPrice.php on line 528

error_ul14_apache_aux1_19-12-23.log:

[Mon Dec 23 18:20:28 2019] [error] [client 31.202.111.85] proxy: Error reading from remote server returned by /modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php, referer: https://weddingtextile.com/admin***/index.php?controller=AdminModules&configure=ps_facetedsearch&token=829dc41

**Comment by khouloudbelguith** [comment]
@weddingtextile,

`Maximum execution time of 120 seconds`
IN your PHP info what is the exact value of `max_execution_time`?
![image](https://user-images.githubusercontent.com/16067358/71369400-f434f200-25aa-11ea-9790-8543296f0a9d.png)

Thanks!

**Comment by weddingtextile** [comment]
The algorithm is not working. More precisely, the algorithm is not working with my data.
I set the value of max_execution_time = 300, but this didn't solve the problem.

Here is the proof.
PHP_errors.log:
[23-Dec-2019 18:49:11 Europe/Kiev] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /home/virtwww/w_wed***/http/classes/SpecificPrice.php on line 528

error_ul14_apache_aux1_19-12-23.log:
[Mon Dec 23 18:48:59 2019] [error] [client 31.202.111.85] proxy: Error reading from remote server returned by /modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php, referer: https://weddingtextile.com/admin***/index.php?controller=AdminModules&configure=ps_facetedsearch&token=829dcc5c25a330741

See https://github.com/PrestaShop/PrestaShop/issues/16845#issuecomment-567263662

**Comment by khouloudbelguith** [comment]
@weddingtextile, 
>I have products that are related to several categories

How many categories related to a product, I need to reproduce the issue in my local.

Thanks!

**Comment by weddingtextile** [comment]
See https://github.com/PrestaShop/PrestaShop/issues/16845#issuecomment-567409214

Maybe I didn’t delete all the additional categories links.
You have access to my data and can write a query to the database (I do not know from which tables select data).
Everything worked before the update. Faceted Search version was 2.2.0.

**Comment by khouloudbelguith** [comment]
@weddingtextile, With this SQL command:
`select * from ps_category_product ORDER BY id_product`, you can get all products associated to categories.
For each product, you have 2 or 3 categories.

Thanks to check & feedback.

**Comment by weddingtextile** [comment]
I will not find the problem in the module Faceted Search without debugging.
At the same time, I noticed that "Clear cache" function does not work. The table ps_layered_price_index is not cleared.

First of all, I want to fix errors when working in BO.
See https://github.com/PrestaShop/PrestaShop/issues/16845#issuecomment-567455330
Maybe these errors are related to the menu "Quick Access".
Look at my "Quick Access" menu in BO.

**Comment by khouloudbelguith** [comment]
@weddingtextile, I need t know this error
![image](https://user-images.githubusercontent.com/16067358/71585736-e685ec00-2b17-11ea-8f56-4e5de1373f41.png)
Did you try to check your host about it?
I tried to enable debug mode & it is enabled also.
It is the same error when rebuilding the index.
![image](https://user-images.githubusercontent.com/16067358/71585826-3369c280-2b18-11ea-8e72-d3b4ebe58ac7.png)
It is a bad Gateway or Proxy Error
Thanks to check with them & feedback.

**Comment by weddingtextile** [comment]
This is the same error: "Maximum execution time of 120 seconds exceeded".
See the log files from server:
[PHP_errors.log](https://github.com/PrestaShop/PrestaShop/files/4010695/PHP_errors.log)
[error_ul14_apache_aux1_19-12-30.log](https://github.com/PrestaShop/PrestaShop/files/4010699/error_ul14_apache_aux1_19-12-30.log)

**Comment by weddingtextile** [comment]
Delete image, please!

**Comment by khouloudbelguith** [comment]
@weddingtextile, as you can see in the second log file, you have this error
>[Mon Dec 30 16:16:21 2019] [error] [client ***.**.**.***] proxy: Error reading from remote server returned by /admin***/index.php/security/compromised, referer: https://weddingtextile.com/admin***/index.php/security/compromised
[Mon Dec 30 16:16:26 2019] [error] [client ***.**.**.***] (20014)Internal error: proxy: error reading status line from remote server 195.234.4.56:20006, referer: https://weddingtextile.com/admin***/index.php?controller=AdminModules&configure=ps_facetedsearch&token=ac169b08c8a7af66c6629e140fde4165
[Mon Dec 30 16:16:26 2019] [error] [client ***.**.**.***] proxy: Error reading from remote server returned by /modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php, referer: https://weddingtextile.com/admin***/index.php?controller=AdminModules&configure=ps_facetedsearch&token=ac169b08c8a7af66c6629e140fde4165

The "proxy: error reading status line from remote server" error message caused by the race condition that the backend server closed the pooled connection after the connection check by the proxy and before data sent by the proxy reached the backend
For more details, you can follow this link: https://httpd.apache.org/docs/2.2/en/mod/mod_proxy_http.html
It seems that your application takes more time to respond that apache ProxyTimeout so you have this error: Maximum execution time of 120 seconds exceeded.

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!

**Comment by weddingtextile** [comment]
The table ps_layered_filter_block is growing fast (100-200 megabytes per day).
Faceted search version is 3.4.1
