### ISSUE TITLE
Default Newsletter module sends email when customer is buying some product

### ISSUE THREAD

**Issue by emeraldlab** [PrestaShop/PrestaShop#16846]
**Describe the bug**
The default module of the newsletter send emails when customers are buyng some product. I don't want this happens. It must send emails only if the customers decides to subscribe to the newsletter and not when is going to bui something. 
At this link: http://helpme.emeraldlab.it/prestashop/bug-newsletter.mp4
you can see the bug

Is it a bug? How to fix it?

Thank you,
emeraldlab

**Screenshots**
Here the default module settings:
![Cattura](https://user-images.githubusercontent.com/59014398/71081626-dec95d80-218f-11ea-8ca9-4452b177023c.JPG)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @emeraldlab,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version.
Second, you need to leave blank the `Welcome voucher code `to disable by default.
![image](https://user-images.githubusercontent.com/16067358/71085902-d6295500-2198-11ea-9f09-ce0738c97d56.png)

If it is not empty, a welcome voucher is sending to the customer.

Thanks

**Comment by emeraldlab** [comment]
Thank you for the PHP info!
But I don't want to remove the code because I need that when a user subscribe to the newsletter he will receive the code.
But I need that this happens only when the user subscribe to the newsletter and not when is buying one of the products.

**Comment by khouloudbelguith** [comment]
@emeraldlab, no, this code is a welcome voucher.
So, if a new account is created => this welcome voucher is sent (the new customer could be subscribed to the newsletter yes or no)

>not when is buying one of the products.

This welcome voucher is sent because you create a new customer in the checkout page.

>I need that this happens only when the user subscribe to the newsletter 

If you subscribe to the newsletter with this block
![image](https://user-images.githubusercontent.com/16067358/71089535-5eabf380-21a1-11ea-8971-c7d2c3ec1af0.png)
There is no welcome voucher sent.

Thanks!

**Comment by emeraldlab** [comment]
Ok, thank you very much.

**Comment by khouloudbelguith** [comment]
@emeraldlab, you are welcome!
Feel free to open a new one when needed.

Thanks!

**Comment by emeraldlab** [comment]
@khouloudbelguith there is a way to make the system send an email to new newsletter subscriber? 
I search in lots of configuration but I didn't find anything useful.

**Comment by khouloudbelguith** [comment]
@emeraldlab, you can find some module in our Market place addons
https://addons.prestashop.com/en/

Thanks!
