### ISSUE TITLE
PS team 9.%

### ISSUE THREAD

**Issue by qqqqq4211** [PrestaShop/PrestaShop#16854]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qqqqq4211** [comment]
Bb

**Comment by khouloudbelguith** [comment]
Hi @qqqqq4211,

Thanks for your report.
This issue will be re-opened if you can give us specific details.

Thanks!
