### ISSUE TITLE
Bad wording when installation is checking compatibility

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16859]
**Describe the bug**
During installation, at step "Checking PS compatibility", if there is an error, a message is displayed, asking the user to click the "Refresh information" button. But the button itself is named only "Refresh". It should be identical, so either rename the button "Refresh information" or change error wording to '...click  "Refresh" to test...'

**To Reproduce**
1. Install PS with an error in compatibility (for example, PHP config "memory_limit" under 256M)
2. See error and button

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/55688534/71155607-5c4ba700-223e-11ea-88fd-ea9fc76989b3.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I have the same issue with PS1.7.5.2 & PS1.7.6.2 & develop.
I’ll add this to the debug roadmap.
Thanks!

**Comment by LouiseBonnard** [comment]
@khouloudbelguith, @Robin-Fischer-PS, thanks, I'm in favor of modifying the error notification instead of the button: _(...), and then click "Refresh" to test the compatibility of your new system._
