### ISSUE TITLE
Uncaught ReferenceError: prestashop is not defined

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#16850]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24798703/71092245-2dcebd00-21a7-11ea-821b-4ae327b4d954.png)

I cant figure out how to resolve, seem some reference to prestashop is missed in some file
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

could you please check those errors are displayed in which files
You need just to move the mouse under `file.js`
For example
![image](https://user-images.githubusercontent.com/16067358/71096211-35de2b00-21ae-11ea-8643-2c0d69d8fd2b.png)
Thanks to check & feedback.

**Comment by matteolavaggi** [comment]
Hi, file are

themes/core.js
themes/classic/assets/theme.js
modules/ps_shoppingcarts/ps_shoppingcarts.js

**Comment by khouloudbelguith** [comment]
@matteolavaggi, those errors are displayed in the BO or FO?
On which page exactly?

Thanks!

**Comment by matteolavaggi** [comment]
FO , on all page. BTW i've restored a complete backup! im sure is a single prestashop word changed in some file during today work!
Thanks

**Comment by khouloudbelguith** [comment]
@matteolavaggi, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
