### ISSUE TITLE
Search by product name & category doesn't work in the second of the Stocks page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16851]
**Describe the bug**
In the BO => Catalog => Stocks page => Search by product name & category doesn't work in the second page.

**To Reproduce**
1. Fresh install PS1.7.6
2. Go to the BO => Catalog => Stocks page => select the second page
3. Try to search by a product name "Brown" which exists on the second page => "No product matches your search. Try changing search terms." => NOK
4. Try to search by a category "Art" "No product matches your search. Try changing search terms." => NOK

**Screenshots**
https://drive.google.com/file/d/1q7O8pCON1wMmPHLkqzx5zY8n_newVGJp/view

**Additional information**
PrestaShop version: PS1.7.7(develop), PS1.7.6.2, PS1.7.5.2, PS1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by Progi1984** [comment]
Fixed by #17881
