### ISSUE TITLE
Unable to load template 'file:catalog/_partials/miniatures/product.tpl'

### ISSUE THREAD

**Issue by Mx74** [PrestaShop/PrestaShop#16853]
Hello,

Working with Prestashop 1.7.6.1, with the classic theme. I did install some others theme, but uninstall them. 
In the back office, I was playing with the theme appearance, trying to configure the module "New product" on the home page. when suddenly I got "Oops! An Error Occurred
The server returned a "500 Internal Server Error"."

I search on the web, switch in dev mode, and got:

SmartyException
HTTP 500 Internal Server Error
Unable to load template 'file:catalog/_partials/miniatures/product.tpl'

The file product.tpl is where it's supposed to be. 

Some search later, one solution proposed was to delete both dev & prod folders in var/cache, but it failed solving the issue. 
I have seen several similar issues, but none of solution proposed were working for me. 

Any idea?

**Comment by khouloudbelguith** [comment]
Hi @Mx74,

Thanks for your feedback.
Thanks to provide me the whole exception displayed in your case.
> did install some others theme, but uninstall them.

Did you delete them from the BO? or just removing the theme folder manually?
Thanks!

**Comment by Mx74** [comment]
I did everything from the BO, nothing by ftp or whatever. 

The whole exception display:


Symfony Exception
Symfony Docs
Symfony Support
SmartyException
HTTP 500 Internal Server Error
Unable to load template 'file:catalog/_partials/miniatures/product.tpl'

    Exception Logs 2 Stack Trace 

SmartyException
in vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (line 96)

        public function render(Smarty_Internal_Template $_template)
        {
            // checks if template exists
            if (!$_template->source->exists) {
                $type = $_template->source->isConfig ? 'config' : 'template';
                throw new SmartyException("Unable to load {$type} '{$_template->source->type}:{$_template->source->name}'");
            }
            if ($_template->smarty->debugging) {
                if (!isset($_template->smarty->_debug)) {
                    $_template->smarty->_debug = new Smarty_Internal_Debug();
                }

Smarty_Template_Compiled->render(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (line 383)

                    $smarty->_debug->end_template($tpl);
                    $smarty->_debug->end_render($tpl);
                }
            } else {
                if (isset($tpl->compiled)) {
                    $tpl->compiled->render($tpl);
                } else {
                    $tpl->render();
                }
            }
        }

Smarty_Internal_Template->_subTemplateRender('file:catalog/_partials/miniatures/product.tpl', 'ps_newproducts|1|8', null, 9999, 31536000, array('product' => object(ProductListingLazyArray)), 0, true) in var/cache/dev/smarty/compile/4a/8d/f4/4a8df44403a47041b050fac755e17268c2a7c3e7_0.module.psnewproductsviewstemplat.cache.php (line 37)

        <?php
    $_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, $_smarty_tpl->tpl_vars['products']->value, 'product');
    if ($_from !== null) {
    foreach ($_from as $_smarty_tpl->tpl_vars['product']->value) {
    ?>
          <?php $_smarty_tpl->_subTemplateRender("file:catalog/_partials/miniatures/product.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 9999, $_smarty_tpl->cache_lifetime, array('product'=>$_smarty_tpl->tpl_vars['product']->value), 0, true);
    ?>
        <?php
    }
    }
    $_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);?>

content_5dfa41b3900a11_92372732(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php (line 123)

                if ($_template->startRenderCallbacks) {
                    foreach ($_template->startRenderCallbacks as $callback) {
                        call_user_func($callback, $_template);
                    }
                }
                $unifunc($_template);
                foreach ($_template->endRenderCallbacks as $callback) {
                    call_user_func($callback, $_template);
                }
                $_template->isRenderingCache = false;
            } catch (Exception $e) {

Smarty_Template_Resource_Base->getRenderedTemplateCode(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (line 114)

                    array_merge($_template->cached->file_dependency, $this->file_dependency);
            }
            if ($_template->source->handler->uncompiled) {
                $_template->source->handler->renderUncompiled($_template->source, $_template);
            } else {
                $this->getRenderedTemplateCode($_template);
            }
            if ($_template->caching && $this->has_nocache_code) {
                $_template->cached->hashes[ $this->nocache_hash ] = true;
            }
            if ($_template->smarty->debugging) {

Smarty_Template_Compiled->render(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_updatecache.php (line 38)

        {
            ob_start();
            if (!isset($_template->compiled)) {
                $_template->loadCompiled();
            }
            $_template->compiled->render($_template);
            if ($_template->smarty->debugging) {
                $_template->smarty->_debug->start_cache($_template);
            }
            $this->removeNoCacheHash($cached, $_template, $no_output_filter);
            $compile_check = (int)$_template->compile_check;

Smarty_Internal_Runtime_UpdateCache->updateCache(object(Smarty_Template_Cached), object(Smarty_Internal_Template), false) in vendor/smarty/smarty/libs/sysplugins/smarty_template_cached.php (line 143)

                if ($_template->smarty->debugging) {
                    $_template->smarty->_debug->end_cache($_template);
                }
                return;
            } else {
                $_template->smarty->ext->_updateCache->updateCache($this, $_template, $no_output_filter);
            }
        }
        /**
         * Check if cache is valid, lock cache if required

Smarty_Template_Cached->render(object(Smarty_Internal_Template), false) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (line 211)

                if (!isset($this->cached) || $this->cached->cache_id !== $this->cache_id
                    || $this->cached->compile_id !== $this->compile_id
                ) {
                    $this->loadCached(true);
                }
                $this->cached->render($this, $no_output_filter);
            } else {
                if (!isset($this->compiled) || $this->compiled->compile_id !== $this->compile_id) {
                    $this->loadCompiled(true);
                }
                $this->compiled->render($this);

Smarty_Internal_Template->render(false, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 232)

                    ob_start();
                    $template->_mergeVars();
                    if (!empty(Smarty::$global_tpl_vars)) {
                        $template->tpl_vars = array_merge(Smarty::$global_tpl_vars, $template->tpl_vars);
                    }
                    $result = $template->render(false, $function);
                    $template->_cleanUp();
                    if ($saveVars) {
                        $template->tpl_vars = $savedTplVars;
                        $template->config_vars = $savedConfigVars;
                    } else {

Smarty_Internal_TemplateBase->_execute(object(Smarty_Internal_Template), null, null, null, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 116)

         * @throws SmartyException
         * @return string rendered template output
         */
        public function fetch($template = null, $cache_id = null, $compile_id = null, $parent = null)
        {
            $result = $this->_execute($template, $cache_id, $compile_id, $parent, 0);
            return $result === null ? ob_get_clean() : $result;
        }
        /**
         * displays a Smarty template

Smarty_Internal_TemplateBase->fetch() in classes/module/Module.php (line 2447)

            if ($cache_id !== null) {
                Tools::restoreCacheSettings();
            }
            return $template->fetch();
        }
        /**
         * @param string $template
         * @param string|null $cache_id

ModuleCore->fetch('module:ps_newproducts/views/templates/hook/ps_newproducts.tpl', 'ps_newproducts|1|8') in modules/ps_newproducts/ps_newproducts.php (line 206)

                }
                $this->smarty->assign($variables);
            }
            return $this->fetch($this->templateFile, $this->getCacheId('ps_newproducts'));
        }
        public function getWidgetVariables($hookName, array $configuration)
        {
            $products = $this->getNewProducts();

Ps_NewProducts->renderWidget('displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2)) in classes/Hook.php (line 975)

            return $module->{$method}($params);
        }
        public static function coreRenderWidget($module, $hook_name, $params)
        {
            return $module->renderWidget($hook_name, $params);
        }
        /**
         * @return \PrestaShopBundle\DataCollector\HookRegistry|null
         */

HookCore::coreRenderWidget(object(Ps_NewProducts), 'displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2)) in classes/Hook.php (line 927)

                    if ($moduleInstance instanceof WidgetInterface) {
                        if (0 !== $key && true === $chain) {
                            $hook_args = $output;
                        }
                        $display = Hook::coreRenderWidget($moduleInstance, $hook_name, $hook_args);
                        if ($array_return) {
                            $output[$moduleInstance->name] = $display;
                        } else {
                            if (true === $chain) {

HookCore::exec('displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2), null) in config/smarty.config.inc.php (line 167)

            return $result;
        }
        unset($hook_params['h']);
        return Hook::exec($params['h'], $hook_params, $id_module);
    }
    function smartyCleanHtml($data)
    {
        // Prevent xss injection.

smartyHook(array('h' => 'displayAdminAfterHeader'), object(Smarty_Internal_Template)) in classes/Smarty/SmartyLazyRegister.php (line 83)

                    } else {
                        $args[] = &$arguments[$a];
                    }
                }
                return call_user_func_array($item, $args);
            }
        }
        public static function getInstance($smarty)
        {

SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayAdminAfterHeader'), object(Smarty_Internal_Template))) in var/cache/dev/smarty/compile/2e/2e/30/2e2e3075c94c59ca385c7580f1b2d8c19eeaebab_0.file.header.tpl.php (line 537)

                    <?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['l'][0], array( array('s'=>'For security reasons, you must also delete the /install folder.','d'=>'Admin.Login.Notification'),$_smarty_tpl ) );?>
                </div>
    <?php }?>
                <?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['hook'][0], array( array('h'=>'displayAdminAfterHeader'),$_smarty_tpl ) );?>
    <?php } else { ?>

content_5dfa41b3708626_01094246(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php (line 123)

                if ($_template->startRenderCallbacks) {
                    foreach ($_template->startRenderCallbacks as $callback) {
                        call_user_func($callback, $_template);
                    }
                }
                $unifunc($_template);
                foreach ($_template->endRenderCallbacks as $callback) {
                    call_user_func($callback, $_template);
                }
                $_template->isRenderingCache = false;
            } catch (Exception $e) {

Smarty_Template_Resource_Base->getRenderedTemplateCode(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (line 114)

                    array_merge($_template->cached->file_dependency, $this->file_dependency);
            }
            if ($_template->source->handler->uncompiled) {
                $_template->source->handler->renderUncompiled($_template->source, $_template);
            } else {
                $this->getRenderedTemplateCode($_template);
            }
            if ($_template->caching && $this->has_nocache_code) {
                $_template->cached->hashes[ $this->nocache_hash ] = true;
            }
            if ($_template->smarty->debugging) {

Smarty_Template_Compiled->render(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (line 216)

                $this->cached->render($this, $no_output_filter);
            } else {
                if (!isset($this->compiled) || $this->compiled->compile_id !== $this->compile_id) {
                    $this->loadCompiled(true);
                }
                $this->compiled->render($this);
            }
            // display or fetch
            if ($display) {
                if ($this->caching && $this->smarty->cache_modified_check) {
                    $this->smarty->ext->_cacheModify->cacheModifiedCheck(

Smarty_Internal_Template->render(false, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 232)

                    ob_start();
                    $template->_mergeVars();
                    if (!empty(Smarty::$global_tpl_vars)) {
                        $template->tpl_vars = array_merge(Smarty::$global_tpl_vars, $template->tpl_vars);
                    }
                    $result = $template->render(false, $function);
                    $template->_cleanUp();
                    if ($saveVars) {
                        $template->tpl_vars = $savedTplVars;
                        $template->config_vars = $savedConfigVars;
                    } else {

Smarty_Internal_TemplateBase->_execute(object(Smarty_Internal_Template), null, null, null, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 116)

         * @throws SmartyException
         * @return string rendered template output
         */
        public function fetch($template = null, $cache_id = null, $compile_id = null, $parent = null)
        {
            $result = $this->_execute($template, $cache_id, $compile_id, $parent, 0);
            return $result === null ? ob_get_clean() : $result;
        }
        /**
         * displays a Smarty template

Smarty_Internal_TemplateBase->fetch('header.tpl') in classes/controller/AdminController.php (line 1866)

            $this->context->smarty->assign('baseAdminUrl', __PS_BASE_URI__ . basename(_PS_ADMIN_DIR_) . '/');
            $this->context->smarty->assign(
                array(
                    'page' => $this->json ? json_encode($page) : $page,
                    'header' => $this->context->smarty->fetch($header_tpl),
                    'footer' => $this->context->smarty->fetch($footer_tpl),
                )
            );
            $this->smartyOutputContent($this->layout);

AdminControllerCore->display() in classes/controller/Controller.php (line 312)

                        $this->{'displayAjax' . $action}();
                    } elseif (method_exists($this, 'displayAjax')) {
                        $this->displayAjax();
                    }
                } else {
                    $this->display();
                }
            } else {
                $this->initCursedPage();
                $this->smartyOutputContent($this->layout);
            }

ControllerCore->run() in classes/Dispatcher.php (line 515)

                if (isset($params_hook_action_dispatcher)) {
                    Hook::exec('actionDispatcher', $params_hook_action_dispatcher);
                }
                // Running controller
                $controller->run();
                // Execute hook dispatcher after
                if (isset($params_hook_action_dispatcher)) {
                    Hook::exec('actionDispatcherAfter', $params_hook_action_dispatcher);
                }

DispatcherCore->dispatch() in admin483ve7877/index.php (line 97)

        if (!headers_sent()) {
            header('Content-Type: text/html; charset=utf-8');
        }
        // Prepare and trigger LEGACY admin dispatcher
        Dispatcher::getInstance()->dispatch();
    }

**Comment by khouloudbelguith** [comment]
@Mx74, thanks for your feedback.
Could you please try to rename the folder /Project_Folder/modules/`ps_newproducts` to /Project_Folder/modules/`ps_newproducts_old`, and try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Mx74** [comment]
Hello,

It looks like Filezilla somehow struggle deleting thge folder ContainerQq2njit. As if the files inside were recreated faster than they are deleted
Now it gives me this:


(1/1)                                     FatalErrorException                                                                  Compile  Error: require(): Failed opening required  '/homepages/27/d625361112/htdocs/prestashop/var/cache/dev/ContainerQq2njit/removed-ids.php'   (include_path='/homepages/27/d625361112/htdocs/prestashop/vendor/pear/pear_exception:/homepages/27/d625361112/htdocs/prestashop/vendor/pear/console_getopt:/homepages/27/d625361112/htdocs/prestashop/vendor/pear/pear-core-minimal/src:/homepages/27/d625361112/htdocs/prestashop/vendor/pear/archive_tar:.:/usr/lib/php7.2')
--
in appDevDebugProjectContainer.php line 1686

**Comment by Mx74** [comment]
I renamed ContainerQq2njit folder to ContainerQq2njit_old instead of deleting it, and now I can access my back office again. 

I have to check everything and see if I got others errors

**Comment by khouloudbelguith** [comment]
@Mx74, As you can see in your error, there are only cache errors.
Did you use a caching like Memcached or APC?

Thanks!

**Comment by Mx74** [comment]
Yep, got errors again. I can acces my catalog, products, everything, but I go to modify my theme appearence, it crashes again:

Unable to load template 'file:catalog/_partials/miniatures/product.tpl'

**Comment by Mx74** [comment]
I have no memory using any special cache function or module

**Comment by Mx74** [comment]
I did your procedure again, could access my BO again, but then it crashes again when i try to access the parameters page. It not usable as it is.

Accessing the shop parameters pages created a cache folder in dev named "ContainerAuwagus" Renaming this one allows me to access the BO again. So yes, it's definitively cache erros, but how to solve them?

**Comment by khouloudbelguith** [comment]
@Mx74, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by Mx74** [comment]
I'm on a mutualized hoster, can't do that

**Comment by khouloudbelguith** [comment]
@Mx74, could you please try to contact your host provider to try with those commands.
It is helpful to delete cache from the prod & dev environment.

Thanks!

**Comment by Mx74** [comment]
Ok, I could do it by SSH.

Now I get:



Notice: Trying to get property 'id' of non-object

    Exception Logs 2 Stack Trace 

Symfony\Component\Debug\Exception\ ContextErrorException
in src/Core/Product/Search/ProductSearchContext.php (line 59)

        {
            if ($context) {
                $this->idShop = $context->shop->id;
                $this->idLang = $context->language->id;
                $this->idCurrency = $context->currency->id;
                $this->idCustomer = $context->customer->id;
            }
        }
        /**
         * @param int $idShop

ProductSearchContext->__construct(object(Context)) in classes/ProductAssembler.php (line 44)
ProductAssemblerCore->__construct(object(Context)) in modules/ps_newproducts/ps_newproducts.php (line 238)
Ps_NewProducts->getNewProducts() in modules/ps_newproducts/ps_newproducts.php (line 211)
Ps_NewProducts->getWidgetVariables('displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2)) in modules/ps_newproducts/ps_newproducts.php (line 197)
Ps_NewProducts->renderWidget('displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2)) in classes/Hook.php (line 975)
HookCore::coreRenderWidget(object(Ps_NewProducts), 'displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2)) in classes/Hook.php (line 927)
HookCore::exec('displayAdminAfterHeader', array('smarty' => object(Smarty_Internal_Template), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 2), null) in config/smarty.config.inc.php (line 167)
smartyHook(array('h' => 'displayAdminAfterHeader'), object(Smarty_Internal_Template)) in classes/Smarty/SmartyLazyRegister.php (line 83)
SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayAdminAfterHeader'), object(Smarty_Internal_Template))) in var/cache/dev/smarty/compile/2e/2e/30/2e2e3075c94c59ca385c7580f1b2d8c19eeaebab_0.file.header.tpl.php (line 537)
content_5dfb584c443fc4_55688228(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php (line 123)
Smarty_Template_Resource_Base->getRenderedTemplateCode(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (line 114)
Smarty_Template_Compiled->render(object(Smarty_Internal_Template)) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (line 216)
Smarty_Internal_Template->render(false, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 232)
Smarty_Internal_TemplateBase->_execute(object(Smarty_Internal_Template), null, null, null, 0) in vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (line 116)
Smarty_Internal_TemplateBase->fetch('header.tpl') in classes/controller/AdminController.php (line 1866)
AdminControllerCore->display() in classes/controller/Controller.php (line 312)
ControllerCore->run() in classes/Dispatcher.php (line 515)
DispatcherCore->dispatch() in admin483ve7877/index.php (line 97)

**Comment by khouloudbelguith** [comment]
@Mx74, did you removed the `ps_newproducts` module or not?

Thanks!

**Comment by Mx74** [comment]
yes, and it's recreated every time

**Comment by khouloudbelguith** [comment]
@Mx74, I think, it is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/14768

Thanks to check & feedback.

**Comment by Mx74** [comment]
No, sorry, I don't see the similarity. 

I gave up and restored both files and DB at a previous date.

It's anyway weird to be able to break Prestashop so badly by using only built-in features from the backoffice...

Thank you for your time and help

**Comment by khouloudbelguith** [comment]
@Mx74, you are welcome!
I will close the issue, feel free to open a new one when needed.

Thanks!
