### ISSUE TITLE
PrestaShop 1.7.X : "Cart::getDeliveryOption()" method with a payment module.

### ISSUE THREAD

**Issue by sdev-pfischer** [PrestaShop/PrestaShop#16864]
**Describe the bug**
When you process to a payment with a payment module which needs an external page to process to your payment, the selected carrier is always redefined to the first after the payment on all versions 1.7.X.X of PrestaShop.

**To Reproduce**
1. Go to the front and add a product to your cart.
2. Process to the payment.
3. Full the customer information
4. If you have 2 carriers, free for the first and charged for the second, select the second.
5. Select a payment by a payment module (here, Atos - Worldline payment method).
6. Process to the payment.
7. You are redirected to the payment page of Atos - Worldline.
8. Enter your credit card (or PayPal, Amex, ...) information.
9. Validate.
10. You are redirected to the confirmation page of PrestaShop.
11. You observe that the selected carrier is not correct and that the order amount is different to the amount paid.

**Screenshots**
https://image.noelshack.com/fichiers/2019/51/4/1576752037-capture-d-ecran-2019-12-19-a-10-15-57.jpg

In this screenshot, we have the parameter "$use_cache" setted to "true" by default for the method "Cart::getDeliveryOption()". But, the method "PaymentMethod::validateOrder()" use this method and doesn't set any parameter. So, the parameter "$use_cache" is still at "true".

To resolve our problem, we have written an override of the "Cart::getDeliveryOption()" method and setted the parameter "$use_cache" to "false".

**Additional information**
PrestaShop version: 1.7.X.X
PHP version: 5.6

**Remark**
We notice that payment modules like "cheque" or "payplug" have not this problem because they don't have redirected to an other page. On the other hand, after our observations on many forums, it seems that modules requiring a redirection to process to the payment also need an override to the "Cart" class.

**Comment by khouloudbelguith** [comment]
Hi @sdev-pfischer,

I did not manage to reproduce the issue with PS1.7.6.2 & Paypal v5.0.3.
I attached a screen record
https://drive.google.com/file/d/1BwdBotJ7NeejjrHZuwcIPcygkr7BdMF4/view
Thanks to check & feedback.

**Comment by sdev-pfischer** [comment]
Hello @khouloudbelguith,

Thank you for your feedback.

Indeed, your module PayPal does not need a redirection to process to the payment. You have an "iframe".

In fact, we have this error when we have a payment module which needs a redirection to process to the payment. The redirection is not in a new tab so we exit the PrestaShop website and we will redirected on it when the payment process is finished.

I am sorry if my explanations was not clear.

I will try to give you a screen record to demonstrate it.

**Comment by sdev-pfischer** [comment]
Hi,

There is the link with a demonstration : https://drive.google.com/file/d/1G4eNR_UF0WsButVKRdfNHaHWLuuw0Le3/view?usp=sharing

Thank you for your feedback.

**Comment by khouloudbelguith** [comment]
@sdev-pfischer, I did not manage to reproduce the issue with a custom payment module similar to yours
https://drive.google.com/file/d/1NO0cWD-4W_lE8guzM7azHJv0o1XBSKT3/view

Thanks!

**Comment by sdev-pfischer** [comment]
@khouloudbelguith,

Thank you for your feedback.

It is strange... When I debug the cart before the redirection to Atos, I have the good carrier. But after the payment process, the carrier is redefined to the first.

**Comment by khouloudbelguith** [comment]
@sdev-pfischer, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by sdev-pfischer** [comment]
@khouloudbelguith,

My agency is the author of this module and we need to understand this error caused by the "Cart::getDeliveryOption()" method.

Can you tell us which module do you use for your test please ?

**Comment by khouloudbelguith** [comment]
@sdev-pfischer, KBC: Credit Card

Thanks!

**Comment by sdev-pfischer** [comment]
@khouloudbelguith,

Thank you for your feedback.

For information, there is the override we've done to resolve our problem :

`class Cart extends CartCore`
`{`
` ` ` ` `public function getDeliveryOption($default_country = null, $dontAutoSelectOptions = false, $use_cache = true)`
` ` ` `  `{` 
` ` ` ` ` ` ` ` `return parent::getDeliveryOption($default_country, $dontAutoSelectOptions, false);`
` ` ` ` `}`
`}`
