### ISSUE TITLE
Error in upgrade to prestashop 1.7.5.2 to 1.7.6.0

### ISSUE THREAD

**Issue by Jojo-Kaly** [PrestaShop/PrestaShop#16870]
Hi !

I open a new post because I have exactly the same problem than #15185 (https://github.com/PrestaShop/PrestaShop/issues/15185). I put CHMOD on 755 on folders and 644 on files but I still have the error.
Do you have a solution, please ?

Thank you.

**Comment by khouloudbelguith** [comment]
Hi @Jojo-Kaly,

You have permission denied on your server.
It is not allowed to write on your disk & there is no space available on it.
If you don't have access, you can check with your host to give the right permission.
Give the write and read access.
`$ chown -hR www-data:www-data ./Project_Folder_name`
Thanks!

**Comment by Jojo-Kaly** [comment]
Why is it allowed to write on my server while I have settled the permissions on 755 for folders and 644 for files ?
The space is unlimited.
What is it this code : $ chown -hR www-data:www-data ./Project_Folder_name ?

Thank you

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, Some hosts might require you to use` CHMOD 777`, although it is not recommended for anything more than a one-time need.
If you have to use CHMOD 777, make sure to switch to a safer setting (for instance, 775 for folders and 664 for files) once you are done upgrading.
To give the write and read access, you can use this command
`chown -hR www-data:www-data ./Project_Folder_name`
https://en.wikipedia.org/wiki/Chown
https://www.elated.com/understanding-permissions/

Thanks!

**Comment by Jojo-Kaly** [comment]
Thank you, khouloudbelguith.
I use CHMOD 777 for module/autoupgrade/classes folder (and its files) but I still have the same error...

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Jojo-Kaly** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3988949/log.txt)
The log is in attached file. Thank you for your help.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly,
I found these errors
```
[2019-11-30 21:37:47] [INTERNAL] /homepages/14/d450210053/htdocs/modules/autoupgrade/classes/ZipAction.php line 111 - ZipArchive::close(): Can't open file: Permission denied
[2019-11-30 21:37:47] Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.
[2019-11-30 21:37:47] Unable to open archive
```

It is a permission issue, thanks to check again & feedback.

**Comment by Jojo-Kaly** [comment]
I don't know what I have to check...   :-(

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, could you please try to contact your host.
You have a permission issue on your server.
Thanks to check with them & feedback.
Also, in your BO => Advanced Parameters => Information page => Check your configuration if it is OK
![image](https://user-images.githubusercontent.com/16067358/71350708-28d88780-2572-11ea-8138-13e0e3cc2d19.png)

Thanks!

**Comment by Jojo-Kaly** [comment]
OK, I will try to contact my host.
Required parameters and optional parameters are OK.
Thank you, khouloudbelguith.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @Jojo-Kaly,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
