### ISSUE TITLE
Creating an order with product with combination and shipped status leads to payment error

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16871]
**Describe the bug**
When creating an order from BO with product "Hummingbird printed sweater - size S", and choosing a status "shipped", the order is created BUT the order status is "payment error".

This is true on `develop` branch (1.7.7.0) but I dont reproduce the bug with `1.7.6.x` branch so it seems to be a regression.

**To Reproduce**
1. Go into BO on "Create an order" legacy page (not symfony) (URL `/admin-dev/index.php?controller=AdminOrders&id_order=8&vieworder`)
2. Choose customer "John Doe"
3. Add product "Hummingbird printed sweater - size S" to cart
<img width="988" alt="Capture d’écran 2019-12-19 à 16 04 42" src="https://user-images.githubusercontent.com/3830050/71184789-8fac2700-227a-11ea-8158-9c343b28f2ee.png">

4. Choose order status "shipped"
5. Click "create order" button
6. You should be redirected to "view an order" page for the order you just created and see a "payment error" warning:
<img width="701" alt="Capture d’écran 2019-12-19 à 16 05 46" src="https://user-images.githubusercontent.com/3830050/71184741-7e631a80-227a-11ea-8ca5-ea2dc7ee130f.png">

Some more notes:
- adding the product "The best is yet to come" in the cart is fine so the issue does not happen with any product
- other order statuses provide the same behavior, for example "payment accepted"

**Additional information**
PrestaShop version: develop
PHP version: 7.2

**Comment by matks** [comment]
Some more infos, as extra
- obviously we see the same issue while migrating the page to Symfony 😬it was 1st spotted by @Robin-Fischer-PS 
- issue might come from `PaymentModule` class, lines 320 to 322 which set order status to payment error

**Comment by khouloudbelguith** [comment]
Hi @matks,

I did not manage to reproduce the issue with the develop branch (PS1.7.7.0.)
I attached a screen record
https://drive.google.com/file/d/1lKXwjYYOWX_YxN3zYBpb1xg-CZ7QDFYv/view
Thanks to check & feedback.

**Comment by matks** [comment]
😅 I dont know what to say ... it fails on my computer, and it does fail for @Robin-Fischer-PS too ...

**Comment by khouloudbelguith** [comment]
@Robin-Fischer-PS, have you the same issue on the develop branch?

Thanks!

**Comment by khouloudbelguith** [comment]
@matks, thanks!
I will try to re-install the shop & check.

Thanks!

**Comment by Robin-Fischer-PS** [comment]
Yes, I tried on develop branch too @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@matks, @Robin-Fischer-PS, After fresh install develop => same issue
https://drive.google.com/file/d/1UIEaAgGFy4eepFjjgCfFEFEnn44nNCvv/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by MatShir** [comment]
@PrestaShop/prestashop-qa @PrestaShop/prestashop-product-team  Have you reproduce it?

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

Yes, I manage to reproduce the issue with 1.7.7.x branch using
Orders page in legacy: https://drive.google.com/file/d/1QpT2RZtF-gXfddpkhXMRgtQqwsaUbxFi/view
Orders page migrated to Symfony: https://drive.google.com/file/d/1YOn_dqiTHne-fwdd_UJkaMNuMy0Wy1QY/view

Thanks!

**Comment by MatShir** [comment]
Thanks the problem seems to occur only for combination

**Comment by matthieu-rolland** [comment]
Fixed in this PR:  #17404

**Comment by sam-pires** [comment]
Damn, too fast 🔥 
Thanks @matthieu-rolland 

We need to trim the bakclog with Mateus before you run out of issues
