### ISSUE TITLE
Blank page on admin product (edit or new) only on prod (and no error in logs)

### ISSUE THREAD

**Issue by romain-le-mercier** [PrestaShop/PrestaShop#16873]
Hi,

I get a blank page when I go to the admin product form (new or edit product) only when on **production** mode. I have no errors in logs (I tripple checked).

When i'm on **dev** mode, the profiler is not working on this page (but everything else is working just fine). 
The profiler web page shows an unserialize error. I can't paste you the serializes content because it's way to long but the backtrace goes like this : 
`Symfony\Component\Debug\Exception\
ContextErrorException
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php (line 56)
##very long serialized##
FileProfilerStorage->createProfileFromData('47ef3e', array('token' => '93d35d', 'parent' => null, 'children' => array('47ef3e'), 'data' => array('request' => object(RequestDataCollector), 'time' => object(TimeDataCollector), 'memory' => object(MemoryDataCollector), 'validator' => object(ValidatorDataCollector), 'ajax' => object(AjaxDataCollector), 'form' => object(FormDataCollector), 'exception' => object(ExceptionDataCollector), 'logger' => object(LoggerDataCollector), 'events' => object(EventDataCollector), 'router' => object(RouterDataCollector), 'cache' => object(CacheDataCollector), 'translation' => object(TranslationDataCollector), 'security' => object(SecurityDataCollector), 'twig' => object(TwigDataCollector), 'db' => object(DoctrineDataCollector), 'swiftmailer' => object(MessageDataCollector), 'dump' => object(DumpDataCollector), 'ps.hooks_collector' => object(HookDataCollector), 'guzzle' => object(GuzzleCollector), 'config' => object(ConfigDataCollector)), 'ip' => '78.244.194.95', 'method' => 'GET', 'url' => 'https://elicityl-oligotech.websenso.dev/admin8690f4bsc/index.php/sell/catalog/products/614?_token=ggEOMtnv2rM0PwokdfbZ5JKxVK9TkT-8SY2IGuJoDyo', 'time' => 1576770954, 'status_code' => 200))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php (line 124)
FileProfilerStorage->read('93d35d')
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php (line 88)
Profiler->loadProfile('93d35d')
in vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php (line 154)
ProfilerController->toolbarAction(object(Request), '93d35d')
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 152)
HttpKernel->handleRaw(object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 69)
HttpKernel->handle(object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
Kernel->handle(object(Request), 1, false)
in admin8690f4bsc/index.php (line 86)`

I don't know if it can simply be reproduced on a clean install.
I tried disabeling override and/or non-prestashop modules but it didn't work.
I managed to track down the execution of the code before the blank page, I endded in the vendor abyss : "/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php" line 158 : $this->dispatcher->dispatch(KernelEvents::VIEW, $event);
A try/catch did nothing.

**Additional information**
PrestaShop version: 1.7.6.0
Server information Linux #768030 SMP Tue Jun 18 08:31:24 UTC 2019 x86_64
Server software version: Apache/2.4.25
PHP version: 7.3.13-1+0~20191218.50+debian9~1.gbp23c2da
Memory limit: 512M
Max execution time: 90

**Comment by khouloudbelguith** [comment]
Hi @romain-le-mercier

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version, check & feedback.

**Comment by romain-le-mercier** [comment]
I'll try on PHP 7.2 and get back to you but I have other prestashop (1.7.5.1) running on the same server and PHP 7.3 without the issue.

**Comment by khouloudbelguith** [comment]
@romain-le-mercier,  I'm happy to hear that there is no issue with php7.3  on your staging server but as I said, currently PrestaShop is not compatible with php7.3. So some parts of the application might work, but there is no guarantee it works globally. Explications about why can be read here: http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @romain-le-mercier,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
