### ISSUE TITLE
Error in upgrade from Prestashop 1.7.5.2 to 1.7.6.2

### ISSUE THREAD

**Issue by Jojo-Kaly** [PrestaShop/PrestaShop#16889]
**Describe the bug**
When I try to upgrade Prestashop from 1.7.5.2 to 1.7.6.2, I have the error in the screenshot.
Thank you for your help !

**Screenshot**
<img width="1440" alt="Capture d’écran 2019-12-20 à 16 01 26" src="https://user-images.githubusercontent.com/59056657/71294535-18a98800-2379-11ea-961a-1310e2ef79fd.png">

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Jojo-Kaly,

What is the exact version of the 1-click upgrade did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Jojo-Kaly** [comment]
I have 1-click upgrade v4.10.0.
I have backed up my Prestashop. So, I will try again to uprade it and provide you the log...
Thank you.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, thanks!
Waiting for your feedback.

PS: As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

**Comment by Jojo-Kaly** [comment]
The logs are in attached file.
At a time, a message asked me "Do you want to restore V1.7.5.2... ?". After this, the upgrade stop it.
Thank you for your help.
<img width="1440" alt="Capture d’écran 2019-12-24 à 15 10 14" src="https://user-images.githubusercontent.com/59056657/71416637-944d5280-2661-11ea-93c7-7d84cd0a9e21.png">
![Uploading Capture d’écran 2019-12-24 à 15.10.45.png…]()


[log.txt](https://github.com/PrestaShop/PrestaShop/files/3998496/log.txt)

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, it is a size problem during the upgrade of your Database.
Thanks to check your configuration in the `php.ini` file & try to increase them

```
upload_max_filesize

post_max_size

max_file_uploads

memory_limit

max_input_vars

max_input_time

max_execution_time

set_time_limit
```

Thanks!

**Comment by Jojo-Kaly** [comment]
I don't found the php.ini file. Should I create it ? What values should I put in it ?
Thank you.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, no it is a configuration file: https://www.php.net/manual/en/configuration.file.php
You can check your host for more details.

Thanks!

**Comment by Jojo-Kaly** [comment]
I set the configuration in the php.ini like this :

upload_max_filesize = 32M
post_max_size = 16M
max_file_uploads = 40
memory_limit = 256M
max_input_vars = 2000
max_execution_time = 60

But I still have the same error (log in attached file) !
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4006197/log.txt)

What does mean "_The table with name "_db_prefix_already exists_" ?

Thank you for your help.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, as you can see in your log
>Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.
[2019-11-30 21:37:47] Unable to open archive

You have a permission issue in your server.
Thanks to check the permissions.

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by Jojo-Kaly** [comment]
Thank you, khouloudbelguith,

I typed the login and the password ("prestashop" for both) but the web page doesn't open...   :-(

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, it is just a phpinfo file equivalent to the phpinfo() function.
thanks to try with this file
[test.php.zip](https://github.com/PrestaShop/PrestaShop/files/4010156/test.php.zip)
I deleted the credential check.

Thanks!

**Comment by Jojo-Kaly** [comment]
Thank you, it's OK.

But there is no red parameter.
<img width="1440" alt="Capture d’écran 2019-12-30 à 16 31 59" src="https://user-images.githubusercontent.com/59056657/71588553-35388380-2b22-11ea-8a4b-e4ff0595162e.png">
<img width="1440" alt="Capture d’écran 2019-12-30 à 16 32 07" src="https://user-images.githubusercontent.com/59056657/71588557-379add80-2b22-11ea-87f4-0aa9e5ea39fb.png">

<img width="1440" alt="Capture d’écran 2019-12-30 à 16 31 48" src="https://user-images.githubusercontent.com/59056657/71588531-25b93a80-2b22-11ea-9999-d0587767f27f.png">

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, thanks to increase these configurations to the recommended value, check & feedback.

```
max_input_vars
upload_max_filesize
post_max_size
```

Thanks!

**Comment by Jojo-Kaly** [comment]
I increased configuration to the recommended value but I still have the same error...

[log.txt](https://github.com/PrestaShop/PrestaShop/files/4010441/log.txt)

<img width="1440" alt="Capture d’écran 2019-12-30 à 17 59 40" src="https://user-images.githubusercontent.com/59056657/71591997-c01f7b00-2b2e-11ea-8a70-7723b298b441.png">

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, have you an extra module that adds a table in the database?
Thanks to check & feedback.

**Comment by Jojo-Kaly** [comment]
I know that the first two tables of my database (db_prefix...) were added by Colissimo module. Do you think this module is causing the upgrade error ?
<img width="1440" alt="Capture d’écran 2019-12-31 à 10 24 37" src="https://user-images.githubusercontent.com/59056657/71616709-f05f2c00-2bb7-11ea-8647-bcb9e39a4932.png">

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, yes!

You can see the error
>[2019-12-30 17:50:09] 17:50:08 ERROR     [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "The table with name ''._db_prefix_' already exists." ["exception" => Doctrine\DBAL\Schema\SchemaException { …},"command" => "prestashop:schema:update-without-foreign","message" => "The table with name ''._db_prefix_' already exists."]
[2019-12-30 17:50:09] In SchemaException.php line 109:

The upgrade is stopped due to this module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Jojo-Kaly** [comment]
Do you think set this option on "yes" can resolve the problem ?

Thank you

<img width="1440" alt="Capture d’écran 2019-12-31 à 10 45 04" src="https://user-images.githubusercontent.com/59056657/71617322-e12dad80-2bba-11ea-8338-296f27a46f98.png">

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, this issue occurs during the upgrade of your database schema.
I think this is will not help you but you can check.

Thanks!

**Comment by Jojo-Kaly** [comment]
I disabled non-native modules and the update worked !
Thank you very much for your help, khouloudbelguith !

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, Great!
