### ISSUE TITLE
Sort doesn't work in the monitoring page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16887]
**Describe the bug**
In the BO => Catalog => Monitoring 
1. List of products with combinations but without available quantities for sale => the sort by ID & Reference & Name & Status do not work.
2. List of products without combinations and without available quantities for sale => the sort by ID & Reference & Name & Status do not work
3. List of disabled products => the sort by ID & Reference & Name do not work.
4. List of products without images => the sort by ID & Reference & Name do not work.
5. List of products without description => the sort by ID & Reference & Name & Status do not work.
6. List of products without price => the sort by ID & Reference & Name & Status do not work.

**To Reproduce**
1. Go to the BO => Catalog => Monitoring 
2. Try to sort 

**Screenshots**
https://drive.google.com/file/d/1XpSydmm2_5-hpHic5l63_g9O-3ZU5XWD/view

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @matks

**Comment by Progi1984** [comment]
Fixed by #17279
