### ISSUE TITLE
Simplify rendering of forms for 1.7.8 pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16891]
Hello @tdavidsonas88 I have another topic you can tackle in order to get more familiar with PrestaShop stack and that would be really useful for 1.7.7 😄 .

Since @sarjon 's PR https://github.com/PrestaShop/PrestaShop/pull/15130 we are able to render entire forms inside migrated pages using the single twig statement ` {{ form_rest(...) }}`.

**Before**
```
        {{ ps.form_group_row(cmsPageForm.content, {}, {
          'label': 'Page content'|trans({}, 'Admin.Design.Feature'),
          }) }}

        {{ ps.form_group_row(cmsPageForm.is_indexed_for_search, {}, {
          'label': 'Indexation by search engines'|trans({}, 'Admin.Design.Feature'),
          }) }}

        {{ ps.form_group_row(cmsPageForm.is_displayed, {}, {
          'label': 'Displayed'|trans({}, 'Admin.Global'),
          }) }}

        {% if cmsPageForm.shop_association is defined %}
          {{ ps.form_group_row(cmsPageForm.shop_association, {}, {
            'label': 'Shop association'|trans({}, 'Admin.Global')
            }) }}
        {% endif %}
```

**After**
```
        {% block cms_page_form_rest %}
          {{ form_rest(cmsPageForm) }}
        {% endblock %}
```

Basically, since we updated our [Twig Form Theme](https://symfony.com/doc/current/form/form_themes.html), the `{{ form_rest(...) }}` statement is able to construct the full html markup for our forms without us having to write it ourselves as we used to do for all pages before.

So benefit n°1 is "we write less code". Benefit n°2 is that modules are able to modify the structure of the form, so they can alter the form display without having to override any twig statement if the full form is rendered using `{{ form_rest(cmsPageForm) }}`

So your assignment is to modify all forms created during 1.7.7 development phase and constructed with the standard "I write the html markup myself" and modify them so that they are rendered by `{{ form_rest(cmsPageForm) }}` instead, although we want to keep the exact same display. @sarjon did it for 2 pages in https://github.com/PrestaShop/PrestaShop/pull/15130/ so you can use it as an example.

You might need to improve our Form Theme while doing it (https://github.com/PrestaShop/PrestaShop/pull/15130/ does it a little).

Target pages:
- Catalog > Files add/edit form (migrated by @RaimondasSapola) (see [form](https://github.com/RaimondasSapola/PrestaShop/blob/5d27cd8eb56dbb21524745e7bbac5cebdf292a9a/src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Attachment/Blocks/form.html.twig))
- Catalog > Supplier add/edit form (migrated by @zuk3975) (see [form](https://github.com/zuk3975/PrestaShop/blob/1ca2cd4c84215a801c220c8b38016b3f2c249983/src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/Blocks/form.html.twig))

This issue is a subset of bigger issue https://github.com/PrestaShop/PrestaShop/issues/16482

**Comment by tdavidsonas88** [comment]
@matks @rokaszygmantas what's the easiest way to find out all forms created during 1.7.7 development phase? 

Is it just these two related to this issue:
Catalog > Files add/edit form (migrated by @RaimondasSapola) (see form)
Catalog > Supplier add/edit form (migrated by @zuk3975) (see form)

?

**Comment by matks** [comment]
I add the `must-have` label as this is a requirement from eternoendless

**Comment by LouiseBonnard** [comment]
@matks, do you already know who will be in charge at Invertus?

**Comment by sam-pires** [comment]
FYI - Need to use `form_widget`, not `form_rest` (remark from @eternoendless, to ping if more info needed about that)

So it is also necessary to correct pages already modified.

**Comment by eternoendless** [comment]
This issue has ben superseded by #16482

@matks are you Ok to close this one?

**Comment by matks** [comment]
Yes 😄
