### ISSUE TITLE
Exception displayed when creating new profile

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#16899]
**Describe the bug**
In page 'Advanced Parameters > Team > profile', when creating a new profile, an exception is displayed

**To Reproduce**
1. Go to 'Advanced Parameters > Team > profile'
2. Click on 'Add new profile'
3. Fill form and click on save'

**Screenshots**
![image](https://user-images.githubusercontent.com/48441421/71345752-78b15180-2566-11ea-870a-b39e57d4c986.png)

**Additional information**
PrestaShop version: develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi,

Same issue with the `Delete` action.

Thanks!
