### ISSUE TITLE
http 500 error after Order confirmation

### ISSUE THREAD

**Issue by 06463771** [PrestaShop/PrestaShop#16898]
After placing order I am facing http 500 error. Order confirmation email is also recieved and even order is also showing in admin but at the customer page its showing error. My prestashop version is 1.7.5.0. Please give me solution ASAP.

Thanks.

Store URL - http://www.picfair.in

>[Edited by Khouloud]

**Comment by khouloudbelguith** [comment]
Hi @06463771,

I deleted the credentials.
This is a public space.
Let's be safe!

Thanks!

**Comment by 06463771** [comment]
ok

**Comment by khouloudbelguith** [comment]
@06463771, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by 06463771** [comment]
Prestashop Version :- 1.7.5.0

Debug Mode Report :- ON

PHP Error Log :- 

[23-Dec-2019 01:12:22 Asia/Calcutta] PHP Fatal error:  Uncaught Error: Call to a member function getPluginConfig() on null in /home/nkh94n2gnruv/public_html/modules/sendinblue/sendinblue.php:3597
Stack trace:
#0 /home/nkh94n2gnruv/public_html/modules/sendinblue/sendinblue.php(3421): Sendinblue->getApiConfigValue()
#1 /home/nkh94n2gnruv/public_html/classes/Hook.php(966): Sendinblue->hookOrderConfirmation(Array)
#2 /home/nkh94n2gnruv/public_html/classes/Hook.php(355): HookCore::coreCallHook(Object(Sendinblue), 'hookorderConfir...', Array)
#3 /home/nkh94n2gnruv/public_html/classes/Hook.php(903): HookCore::callHookOn(Object(Sendinblue), 'displayOrderCon...', Array)
#4 /home/nkh94n2gnruv/public_html/controllers/front/OrderConfirmationController.php(126): HookCore::exec('displayOrderCon...', Array)
#5 /home/nkh94n2gnruv/public_html/controllers/front/OrderConfirmationController.php(96): OrderConfirmationControllerCore->displayOrderConfirmation(Object(Order))
#6 /home/nkh94n2gnruv/public_html/classes/controller/Controller.php(281): OrderConfirmationControllerCore->initCo in /home/nkh94n2gnruv/public_html/modules/sendinblue/sendinblue.php on line 3597


Other things I don't know as I am not a developer.

**Comment by khouloudbelguith** [comment]
Hi @06463771,

It is a `sendinblue` module issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
