### ISSUE TITLE
Product images not showing in google chrome browser

### ISSUE THREAD

**Issue by amarmib2** [PrestaShop/PrestaShop#16895]
hi
I have uploaded my products in Prestashop 1.7.6.2 after uploading I checked in all the web browser on pc everything was working fine all the images was loading properly.

But when I checked in mobile only in google chrome browser products was not showing properly.
when I click on "rings category" some products images are showing and some are not showing.

can someone help me with this.

PHP version 7.2

![Screenshot_2019-12-22-16-54-28-492_com android chrome](https://user-images.githubusercontent.com/58510133/71321278-28da7800-24dd-11ea-8dee-38ab1b85cc8d.jpg)

**Comment by khouloudbelguith** [comment]
Hi @amarmib2,

Thanks for your report.
Could you please navigate to your BO => Design => Images Settings page => Click on "Regenerate thumbnails", check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @amarmib2,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
