### ISSUE TITLE
Remove the Franc CFA currency from the Ivory Coast + Senegal localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16904]
**Is your feature request related to a problem? Please describe:**

It has been stated this weekend that, in 2020, the Franc CFA currency will be replaced by the Eco currency.

🌍 _Which African countries are concerned?_

All the members of the Union Economique et Monétaire Ouest-Africaine (UEMOA): Benin, Burkina Faso, Ivory Coast, Guinea-Bissau, Mali, Niger, Senegal, Togo.

⏱ _When will it come into effect?_ 

In the course of 2020, there is no date confirmed so far. So let's keep it in mind while we wait for a more precise date, then we will be able to create the PR to fix it.

**Describe the solution you'd like:**

Remove the _Franc CFA_ currency from both the [Ivory Coast](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/ci.xml) and the [Senegal](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/sn.xml) localization packs and replace it with the _Eco_ currency.

⚠️ Must be part of the 1.7.8!

**Comment by LouiseBonnard** [comment]
It's here, the Franc CFA has reached its end, cf. https://www.lemonde.fr/afrique/article/2020/05/21/la-france-acte-officiellement-la-fin-du-franc-cfa-en-afrique-de-l-ouest_6040339_3212.html.

**Comment by Progi1984** [comment]
@LouiseBonnard 1.7.8 ?

**Comment by Progi1984** [comment]
@LouiseBonnard After discussion with @PrestaShop/prestashop-core-developers, I can remove from localizationPacks the FranckCFA in these two files. But the "Eco" currency is not actually defined in CLDR so I can't add it.

Ok with that ?

**Comment by LouiseBonnard** [comment]
Let's wait for the 1.7.8. @sowbiba told me yesterday that the _Eco_ should definitely replace the _Franc CFA_ next September but it might be delayed. Without further information, I suggest we keep it as is for version 1.7.7 and include this change in the next minor version. :-)

**Comment by sowbiba** [comment]
I will let you know if it happens or when the date is defined

**Comment by Progi1984** [comment]
@LouiseBonnard I move this issue to "Blocked" column waiting for more informations.

@sowbiba Thanks ;)

**Comment by colinegin** [comment]
Edit - I remove it from the 178 kanban until the Eco currency is added to the CLDR

**Comment by LouiseBonnard** [comment]
Oh, nice, thanks! Can I close this issue then?

**Comment by PierreRambaud** [comment]
@LouiseBonnard We can close this issue. We should only rely on updating CLDR :smile_cat:
