### ISSUE TITLE
Ghost Product in the Monitoring Page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16903]
**Describe the bug**
If you create a new product and directly leave to the dashboard, for example, the Monitoring page shows an empty product in the list of products

**To Reproduce**
1. Go to BO => Products => Click on "Add a new Product"
2. Leave the product page without saving
3. Go to the BO => Catalog => Monitoring page => you can see an empty product in all lists of products

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/71355410-406a3d00-257f-11ea-8ae4-865c9c5c2016.png)
![image](https://user-images.githubusercontent.com/16067358/71355506-92ab5e00-257f-11ea-9318-f2d60c364afc.png)

**Additional information**
PrestaShop version: 1.7.5.2, 1.7.6.2, develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/9945

**Comment by khouloudbelguith** [comment]
ping @boubkerbribri

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Could you test this issue with latest version ? (I think the migrated Products page fix this bug)

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

The problem still persist on New Product Page with 8.1.x and develop, see the attached screen record below:

[issue_16903.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/bf4627e8-a7c7-422b-b763-ea41e44df8db)

Thanks!

**Comment by MatShir** [comment]
Hi @hibatallahAouadni, 
It is the expected behavior. Before, the ghost product could only be seen on the monitoring page after a failed product creation. Now the product can be seen from the product list. Now the ghost product is now a product in draft without name and reference. 
I'm closing the issue ;)
