### ISSUE TITLE
Free shipping in promocode 

### ISSUE THREAD

**Issue by pnshurba** [PrestaShop/PrestaShop#16910]
I am creating  cart rules a free shipping promo code.  When customers use it, they don’t have any delivery methods displayed.  The system writes there are no available ways. 
If delivery is paid and the promotion is not applicable then there are delivery methods.  please help me. 

![5732C5F8-2748-4873-A99A-4652AAD6850E](https://user-images.githubusercontent.com/39360984/71369687-95787400-25bc-11ea-9ce5-043619e1ca78.jpeg)
![213D7FC1-DD52-432E-8C39-687098D72883](https://user-images.githubusercontent.com/39360984/71369688-95787400-25bc-11ea-8e19-029bb6e8fb2e.jpeg)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

First PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version.
Second, I think you have an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10903

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @pnshurba,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
