### ISSUE TITLE
BO - Impossible to open an order (after upgrade 1.7.6.2.)

### ISSUE THREAD

**Issue by shana0780** [PrestaShop/PrestaShop#16918]
**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

Hello,

After downloading the module Paypal, it's impossible to open the orders in the back-office.

![image](https://user-images.githubusercontent.com/59194234/71443954-565a3800-270e-11ea-8117-44f8973f3cfe.png)

and it's the same if I try to download invoices per date

![image](https://user-images.githubusercontent.com/59194234/71443976-7d186e80-270e-11ea-8581-15528eeeb259.png)

**Comment by khouloudbelguith** [comment]
Hi @shana0780,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account: https://addons.prestashop.com/en/contact-us?id_product=1748, they are the only ones to help you with it.
Thanks!
