### ISSUE TITLE
FO - error when opening order history and contact

### ISSUE THREAD

**Issue by shana0780** [PrestaShop/PrestaShop#16916]
**Additional information**
PrestaShop version: 1.7.6.2.
PHP version: 7.2

After the upgrade from 1.6.1.8 to 1.7.6.2., i have now a problem with the opening of order history and contact.

![order](https://user-images.githubusercontent.com/59194234/71423821-413cc500-268c-11ea-98e5-7c85550603a8.jpg)
![contact](https://user-images.githubusercontent.com/59194234/71423822-41d55b80-268c-11ea-9ee4-fed230288f46.jpg)

**Comment by shana0780** [comment]
This is the complete error for the contact form.


(1/1) ContextErrorExceptionNotice: Undefined index:
--
in Order.php line 944
at OrderCore::getCustomerOrders(64)in contactform.php line 391
at Contactform->getTemplateVarOrders()in contactform.php line 326
at Contactform->getWidgetVariables(null, array())in contactform.php line 275
at Contactform->renderWidget(null, array())in Hook.php line 975
at HookCore::coreRenderWidget(object(Contactform), null, array())in smartyfront.config.inc.php line 85
at {closure}(object(Contactform), array())in smartyfront.config.inc.php line 76
at withWidget(array(), object(Closure))in smartyfront.config.inc.php line 87
at smartyWidget(array('name' => 'contactform'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyWidget', array(array('name' => 'contactform'), object(SmartyDevTemplate)))in 0a17c2944b0ab634ae2238d38a38d8b0b712a610_2.file.contact.tpl.php line 90
at Block_15168836775e027c1bc0f246_82425832->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_15168836775e027c1bc0f246_82425832), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_15168836775e027c1bc0f246_82425832), object(Block_4917398335e027c1bc2e337_67127468))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_4917398335e027c1bc2e337_67127468))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_4917398335e027c1bc2e337_67127468', 'page_content', 1)in f56aebcb08d8d4c9acb280f990bf8baca1695316_2.file.page.tpl.php line 97
at Block_5109576355e027c1bc2d372_56542909->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_5109576355e027c1bc2d372_56542909), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_5109576355e027c1bc2d372_56542909))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_5109576355e027c1bc2d372_56542909', 'page_content_container', 1)in f56aebcb08d8d4c9acb280f990bf8baca1695316_2.file.page.tpl.php line 181
at Block_8226052865e027c1bc2a8c8_15476489->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_8226052865e027c1bc2a8c8_15476489), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_8226052865e027c1bc2a8c8_15476489), object(Block_16657445985e027c1bc45a96_68993516))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_16657445985e027c1bc45a96_68993516))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_16657445985e027c1bc45a96_68993516', 'content', 2)in ba55acd0e1d998d0117dfdd3e82c2cb823811bc1_2.file.layout-left-column.tpl.php line 84
at Block_14439007185e027c1bc445e4_05477956->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_14439007185e027c1bc445e4_05477956), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_14439007185e027c1bc445e4_05477956), object(Block_2133171555e027c1bc69c36_96454812))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_2133171555e027c1bc69c36_96454812))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_2133171555e027c1bc69c36_96454812', 'content_wrapper')in 3a8d9dfee36bd07e910b9f1d945de3faf79cc41d_2.file.layout-both-columns.tpl.php line 87
at content_5e027c1bc71aa3_79371537(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-left-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in ba55acd0e1d998d0117dfdd3e82c2cb823811bc1_2.file.layout-left-column.tpl.php line 38
at content_5e027c1bc46b73_48602734(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-left-column.tpl', null, 'layouts/layout-left-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-left-column.tpl')in f56aebcb08d8d4c9acb280f990bf8baca1695316_2.file.page.tpl.php line 33
at content_5e027c1bc30046_30415969(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-left-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in 0a17c2944b0ab634ae2238d38a38d8b0b712a610_2.file.contact.tpl.php line 43
at content_5e027c1bc100d9_44288393(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-left-column.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('contact.tpl', null, 'layouts/layout-left-column.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('contact.tpl', null, 'layouts/layout-left-column.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('contact.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment]
Hi @shana0780,

I think that during the upgrade some records of `ps_order_history` are missing in your case.
Try to change the following lines solves the problem in this file: `PrestaShop/classes/order/Order.php`

```
            $res[$key]['order_state'] = $indexedOrderStates[$val['id_order_state']]['name'];
            $res[$key]['invoice'] = $indexedOrderStates[$val['id_order_state']]['invoice'];
            $res[$key]['order_state_color'] = $indexedOrderStates[$val['id_order_state']]['color'];
```

to

```
            $res[$key]['order_state'] = $indexedOrderStates[$val['current_state']]['name'];
            $res[$key]['invoice'] = $indexedOrderStates[$val['current_state']]['invoice'];
            $res[$key]['order_state_color'] = $indexedOrderStates[$val['current_state']]['color'];
```

Thanks to check & feedback.

**Comment by shana0780** [comment]
Thank you very much Khouloud.
It's working now :)

I hope it's the last time.

Happy holidays

**Comment by khouloudbelguith** [comment]
@shana0780, you are welcome!
I close the issue, feel free to open a new one when needed.

Thanks & Happy holidays!

**Comment by ghost** [comment]
> Merhaba @ shana0780 ,
> 
> Ben yükseltme sırasında `ps_order_history`sizin durumda bazı kayıtları eksik olduğunu düşünüyorum .
> Aşağıdaki satırları değiştirmeyi deneyin bu dosyadaki sorunu çözer:`PrestaShop/classes/order/Order.php`
> 
> ```
>             $res[$key]['order_state'] = $indexedOrderStates[$val['id_order_state']]['name'];
>             $res[$key]['invoice'] = $indexedOrderStates[$val['id_order_state']]['invoice'];
>             $res[$key]['order_state_color'] = $indexedOrderStates[$val['id_order_state']]['color'];
> ```
> 
> için
> 
> ```
>             $res[$key]['order_state'] = $indexedOrderStates[$val['current_state']]['name'];
>             $res[$key]['invoice'] = $indexedOrderStates[$val['current_state']]['invoice'];
>             $res[$key]['order_state_color'] = $indexedOrderStates[$val['current_state']]['color'];
> ```
> 
> Kontrol ve geri bildirim için teşekkürler.

Hello sir ;
we face the same problem.
We upgraded from version 1.6 to version 1.7.6.5, but we are having the same problem.

**Comment by khouloudbelguith** [comment]
HI @zafer0zturk,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by studubls** [comment]
I have some problem of my store "**Order History** " , someone please help me. it urgently required 
after order confirmation when i want to see my order history there show me some error , see below 


(1/1) ContextErrorExceptionNotice: Undefined offset: 64
--
in Order.php line 944
at OrderCore::getCustomerOrders(28)in HistoryController.php line 72
at HistoryControllerCore->getTemplateVarOrders()in HistoryController.php line 55
at HistoryControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

![Order-History Error Page](https://user-images.githubusercontent.com/75385804/100907324-302d4280-34f0-11eb-850b-551c1d639a67.png)

**Comment by khouloudbelguith** [comment]
Hi @studubls 

This issue is currently closed, can you open a new one with more information about your configuration

Thanks!
