### ISSUE TITLE
Admin Panel HTTP 500 internal server error in Prestashop 1.7.6.2

### ISSUE THREAD

**Issue by hzouba** [PrestaShop/PrestaShop#16924]
Hello,

Everything worked perfectly until i did translate a word in the classic theme from English to French and i cleared the cache, then it's happened, a 500 error only in the dashboard, the front is OK, but in Debug Mode ON the dashboard is working, only when it's OFF it's not OK.

When Debug Mode is ON i did not see any weird errors in my browser, but when i checked the error logs it show this :

`[Thu Dec 26 03:50:10.307763 2019] [:error] [pid 21101] [client XXX.1.28.54:52663] File does not exist: /home2/XXXXX/public_html/adminXXXXX/themes/new-theme/public/index.php, referer: https://www.XXXXXXXXXXXXXXX.com/adminXXXXX/index.php/improve/international/translations/?lang=qc&type=back&locale=fr-CA&_token=Gw31j7XXXXXkUjHFslVJMV5872MXXXXXRziTEIKqkXg1I`

I tried to back to initial translation, but still not working.

Please Help!!

**Server information :**
Server software version: Apache
PHP version: 7.2.25
Memory limit: 512M
Max execution time: 30
Upload Max File size: 1G

**Comment by khouloudbelguith** [comment]
Hi @hzouba,

>Upload Max File size: 1G

"1G" is not a valid maximum size.
Thanks to change it to 1000M for example, check & feedback.

Thanks!

**Comment by hzouba** [comment]
Hi @khouloudbelguith 

I guess it's what Prestashop shows, but in my php.ini the values are like this :

max_input_vars = 5000
allow_url_fopen = On
allow_url_include = Off
asp_tags = Off
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 30
max_input_time = 60
memory_limit = 256M
post_max_size = 128M
session.gc_maxlifetime = 1440
upload_max_filesize = 128M
zlib.output_compression = Off

Thank you!

**Comment by khouloudbelguith** [comment]
@hzouba, that's ok.
Thanks!

You have an error in the new-thems folder & not the classic theme, is it a custom theme?

Thanks!

**Comment by hzouba** [comment]
Thanks @khouloudbelguith 

No, the new-theme is an administration theme right ?
It seems that what i did with the translation in the classic theme to test things, triggered the error, because as i said everything worked fine before that.

**Comment by khouloudbelguith** [comment]
@hzouba, in my case, I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/11TlQzWEbW7veoup12TX7Xs4-MQruSS5Y/view
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by hzouba** [comment]
@khouloudbelguith 
Thanks a lot you saved my life :)
I removed the both Prod & Dev in var/cache and it work again perfectly, no more errors.

**Comment by khouloudbelguith** [comment]
@hzouba, you are welcome!
Feel free to open a new one when needed.

Thanks!
