### ISSUE TITLE
ContextErrorException on local host

### ISSUE THREAD

**Issue by AbdulRehmanYounas** [PrestaShop/PrestaShop#16926]
**Describe the bug**
When I move PrestaShop form server to localhost. Everything work fine but when I click on admin site module & service or advance parameter>performence. Its show me 500 error. 

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/58478086/71477748-7a507300-280d-11ea-84eb-e4c331e6577e.png)

**Additional information**
PrestaShop version: 1.7.4.2
PHP version: 7.3.11
![FireShot Screen Capture #021 - 'PHP PrestaShop Info' - localhost](https://user-images.githubusercontent.com/58478086/71477830-06fb3100-280e-11ea-9334-173704c2592a.png)

**Comment by khouloudbelguith** [comment]
Hi @AbdulRehmanYounas,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version, check & feedback.

**Comment by BryanFernandoOrtiz** [comment]
Thanks for the info.

**Comment by khouloudbelguith** [comment]
@AbdulRehmanYounas, any news?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @AbdulRehmanYounas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
