### ISSUE TITLE
Official way to login via API

### ISSUE THREAD

**Issue by camillo777** [PrestaShop/PrestaShop#16935]
**Is your feature request related to a problem? Please describe.**
I am making a mobile app to integrate with PrestaShop via the web services API.
I don't find any official information about how to login a user with the API.
I understood there is as well a change in 1.7 authentication which does not allow to publish the hashing algorithm so I am still struggling to understand what is going to be the preferred method of doing this.

**Describe the solution you'd like**
I need to be able to login to PrestaShop in a mobile app via web services API.

**Describe alternatives you've considered**
I understood now the only way it works is sending user and password in clear text and authenticate via php on server side. Is it correct? How to do it?

**Additional context**

**Comment by khouloudbelguith** [comment]
Hi @camillo777,

You can follow this link: http://forge.prestashop.com/browse/BOOM-4406?focusedCommentId=159405&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-159405

We have already an issue about improving the Webservice documentation: https://github.com/PrestaShop/docs/issues/342
 
Thanks to check & feedback.

**Comment by camillo777** [comment]
Hello @khouloudbelguith ,
thank you, but I already tried with this solution but it did not seem to work.
I am trying with the test user (John DOE --> pub@prestashop.com) with a super simple script:

```
<?php

$debug = true;

$password = '123456789'; // from USER INPUT
$passwd = 'c2f9ab1c7ba6be048f11b082fcadac5a'; // from DB

    if (password_verify($password, $passwd) == true) {
  	session_start();
        $response = array();
        $response['status'] = 'succes';
        $response['message'] = "You did it!";
        setcookie("userId", $info->id);
        header('Content-type: application/json');
        echo json_encode($response);
    } else {
	$response = array();
        $response['status'] = 'error';
        $response['message'] = 'Wrong password';
        header('Content-type: application/json');
        echo json_encode($response);
    }

?>
```

Any idea why it is not working as expected?
Am I doing something wrong?

Thank you,
Camillo

**Comment by khouloudbelguith** [comment]
@camillo777, you need to use the PrestaShop webservice and filter with email and password like below:
`http://domain.com/api/customers/?filter[email]=pub@prestashop.com&filter[passwd]=$2y$10$9DpcoWmtTs97ST4Ycgvh/eKb/gefnsghJ8FfzXr.kiLngktGFcKTu`

My solution:

check password with PHP:

1. Get customer by email:
http://domain.com/api/customers?filter[email]=customer@domain.com

2. verify "passwd":
password_verify(the_input_password, passwd);
You can follow this link:
http://php.net/manual/es/function.password-verify.php


Thanks!

**Comment by camillo777** [comment]
Hello @khouloudbelguith ,
tried again and it seemed to work this time.
I will leave here my working solution as a reference for other users.
**BEWARE**: with this solution (working with PS1.7) password is sent in clear.

```
<?php

require_once('./PSWebServiceLibrary.php');

$url = "http://x.x.x.x"; // PS shop domain without "/api"
$key = "*** YOUR API KEY ***";
$debug = false; //true;

// get information from PrestaShop
$webService = new PrestaShopWebservice($url, $key, $debug);

$email = 'pub@prestashop.com'; // $_REQUEST['email'];
//$password = '123456789';  
$password = $_REQUEST['password'];

$optUser = array(
    'resource' => 'customers',
    'filter[email]' => '[' . $email . ']',
    'display' => '[id,email,lastname,firstname,passwd]'
);

$resultUser = ($webService->get($optUser));

foreach ($resultUser->customers->customer as $info) {

    if (password_verify($password, $info->passwd) == true) {
  	session_start();
        $response = array();
        $response['status'] = 'succes';
        $response['message'] = "You did it!";
        setcookie("userId", $info->id);
        header('Content-type: application/json');
        echo json_encode($response);
    } else {
	$response = array();
        $response['status'] = 'error';
        $response['message'] = 'Wrong password';
        header('Content-type: application/json');
        echo json_encode($response);
    }
}

?>
```

**Comment by khouloudbelguith** [comment]
@camillo777, thanks a lot for your feedback.
Since it is OK, I will close the issue, feel free to open a new one when needed.

Thanks!
