### ISSUE TITLE
Sub-categories are not displayed anymore in FO menu with mobile

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16932]
**Describe the bug**
Sub-categories are not displayed anymore in FO menu with mobile

**To Reproduce**
1. Go to the FO with a mobile
2. Click on the menu
3. Click on "Clothes" or "Accessories"
4. Sub-categoriies are not displayed

**Screenshots**
![capture d'écran_2208](https://user-images.githubusercontent.com/13449658/71510602-af9da500-288f-11ea-97d6-a7e24d4bc72a.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by marionf** [comment]
Reopened, as it's a regression it should be fixed on 1.7.7.x instead of develop

**Comment by NeOMakinG** [comment]
PR opened for the 1.7.7.x branch :)

**Comment by Progi1984** [comment]
Fixed by #17438
