### ISSUE TITLE
Module override merger does not preserve formatting

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#16949]
**Is your feature request related to a problem? Please describe.**
Currently the override merger does not preserve new lines formatting

**Describe the solution you'd like**
Update the merger/generator code to preserve new lines.

Empty new lines are currently stripped by this code:
### this is also dangerous as even new lines in regular strings are removed
- for new files https://github.com/PrestaShop/PrestaShop/blob/1acd93b614a2ad2634cdf4726fdef36c38c2569f/classes/module/Module.php#L3114
- for already existing override files https://github.com/PrestaShop/PrestaShop/blob/1acd93b614a2ad2634cdf4726fdef36c38c2569f/classes/module/Module.php#L3045

and the code should merge the overrides to produce code like the CS-fixer does (with already CS-fixed files).

**Comment by mvorisek** [comment]
Simple and elegant solution can be to apply CS fixer on the override output, but it will require the CS fixer package for prod. Is this solution welcomed, should I submit a PR for it?

**Comment by mvorisek** [comment]
Simple and elegant solution is to apply CS fixer on the override output.

It requires the CS fixer package for prod (not only for dev as of now), is this solution welcomed as a PR?

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

>Simple and elegant solution is to apply CS fixer on the override output.

https://medium.com/@mickael_andrieu/chez-prestashop-on-a-fait-le-choix-de-php-cs-fixer-et-la-configuration-est-disponible-%C3%A0-la-racine-b21b9cbfa944
https://github.com/PrestaShop/PrestaShop/issues/15545#issuecomment-533179788
Thanks!

**Comment by PierreRambaud** [comment]
Since the file is generated, I don't see any reason to keep formatting :thinking:

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by mvorisek** [comment]
At least this:

> this is also dangerous as even new lines in regular strings are removed

is a bug, so @hibatallahAouadni please relabel and reopen.

Code should be probably merged with https://github.com/nikic/PHP-Parser instead of regular expressions.

**Comment by hibatallahAouadni** [comment]
> Since the file is generated, I don't see any reason to keep formatting

So why you didn't answer @PierreRambaud ?

@PierreRambaud Do you see that we should reopen this issue?
