### ISSUE TITLE
Sign error with gift discount

### ISSUE THREAD

**Issue by Jojo-Kaly** [PrestaShop/PrestaShop#16958]
Hi !

I have an issue with "total discount" (total bons de réduction) of gift discount. I have a negative number instead of a positive number like free delivery (frais de port offerts). Because of that, my customers can't pay(transaction refused because of an invalid argument. The totals of the cart item amounts do not match order amounts.).

How to fix this issue, please ?

Thank you

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

<img width="1440" alt="Signe1" src="https://user-images.githubusercontent.com/59056657/71581743-f2b57d80-2b06-11ea-96cc-9a61302bb7db.png">
<img width="1440" alt="Signe2" src="https://user-images.githubusercontent.com/59056657/71581745-f812c800-2b06-11ea-8273-428e05726060.png">
<img width="1440" alt="Signe3" src="https://user-images.githubusercontent.com/59056657/71581746-fba64f00-2b06-11ea-85f5-cd96834a2f87.png">

**Comment by khouloudbelguith** [comment]
Hi @Jojo-Kaly,

Thanks for your report.
>Because of that, my customers can't pay(transaction refused because of an invalid argument

In the FO => you have an exception? what the exact custom module did you use? have you tried to contact the module author about the issue?

Thanks!

**Comment by Jojo-Kaly** [comment]
Hi, khouloudbelguith,

I dont have an exception in my FO.
I have Alt sup theme on my shop, but I dont have specific module for discount code.
So, I think it's a Prestashop 1.7 bug...

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly,

> my customers can't pay(transaction refused because of an invalid argument

This error is displayed in the FO or BO? On which page?

Thanks!

**Comment by Jojo-Kaly** [comment]
I have this error on Paypal logs :

_Error code: 10413;Short message: Transaction refused because of an invalid argument. See additional error messages for details.;Long message: The totals of the cart item amounts do not match order amounts.;_

Customers tell me that they can't pay, with Paypal or with credit cart, but I don't know exactly what is displayed on their screens.

Thank you.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, have you tried to contact the module author about this issue?
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by Jojo-Kaly** [comment]
I will try to contact the Paypal module author. But I don't think this module is at fault because the sign error is causing by Prestashop discount function. Moreover, the customer can't pay by credit cart either...

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, I tried with PS1.7.6.2 & the PayPal module v5.1.0. & it is ok
https://drive.google.com/file/d/1s7TxupJxuAE7tAYIWO-zUy8tm7qSpUmD/view

Thanks!

**Comment by Jojo-Kaly** [comment]
OK, thank you. I will try after I update Prestashop to 1.7.6.2 version.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, thanks!
Waiting for your feedback!
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

**Comment by Jojo-Kaly** [comment]
I found that I have this problem only when I do not put a promo code (so that all customers automatically take advantage of the gift without having to enter a code). In your video, you put free delivery and not a gift.
I did update 1.7.6.2 and the problem is still there.

**Comment by khouloudbelguith** [comment]
@Jojo-Kaly, I tried with a gift & it is OK with PS1.7.6.2 & the Paypal module.
I attached a screen record
https://drive.google.com/file/d/1ESadp24EdCvP3tmb7wkyz49_NGpVOrBV/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Jojo-Kaly, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
