### ISSUE TITLE
Why does the Web Service returns every field as CDATA?

### ISSUE THREAD

**Issue by fukawi2** [PrestaShop/PrestaShop#16954]
**Describe the bug**
Any request to the web service returns every field wrapped in CDATA tags.

My understanding is that CDATA is meant to wrap *character* data that *could* be misinterpreted as part of the XML document, or to avoid encoding characters such as `<` and `&` as `&lt;` and `&amp;` respectively.

Wrapping _everything_ in CDATA tags is unnecessary and makes the responses difficult to read during development, and can make client-side processing of the response unnecessarily more difficult.

For example, a request to `/api/orders/1` returns this (truncated) response:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <order>
    <id>
      <![CDATA[1]]>
    </id>
    <id_address_delivery xlink:href="<REDACTED>/api/addresses/5">
      <![CDATA[5]]>
    </id_address_delivery>
    <id_address_invoice xlink:href="<REDACTED>/api/addresses/5">
      <![CDATA[5]]>
    </id_address_invoice>
    <id_cart xlink:href="<REDACTED>/api/carts/1">
      <![CDATA[1]]>
    </id_cart>
    <id_currency xlink:href="<REDACTED>/api/currencies/1">
      <![CDATA[1]]>
    </id_currency>
    <id_lang xlink:href="<REDACTED>/api/languages/1">
      <![CDATA[1]]>
    </id_lang>
    <id_customer xlink:href="<REDACTED>/api/customers/2">
      <![CDATA[2]]>
    </id_customer>
    <id_carrier xlink:href="<REDACTED>/api/carriers/2">
      <![CDATA[2]]>
    </id_carrier>
```
Every single one of those values is the primary key of data in another resource in the API. They are not characters (strings), they are integers that do not need to be wrapped in CDATA tags. Other examples in the same response include timestamps, hex represented cryptographic hashes, and decimal values (eg, money amounts); none of these need to be or should be treated as character strings.

My questions are:
1) Is there a reason I'm missing why this should be encoded as CDATA values?
2) Can we cleanup the web service by using CDATA more sparingly and only where it actually makes sense?

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @fukawi2,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi @fukawi2 and sorry for the delay.

> Is there a reason I'm missing why this should be encoded as CDATA values?

It has been added because it was easy and all fields can be surrounded by a CDATA.

> Can we cleanup the web service by using CDATA more sparingly and only where it actually makes sense?

Not sure it's a good idea to add complexity in the legacy code because of human readers.

**Comment by fukawi2** [comment]
Hi @PierreRambaud, I've changed jobs since opening this GH issue. It's no longer relevant to me. You can close if it's not something you want to implement.

**Comment by PierreRambaud** [comment]
Thank you @fukawi2 and sorry again for the delay :sweat:
