### ISSUE TITLE
Faceted search: still shows products with no available stock after filtering

### ISSUE THREAD

**Issue by Twabi2** [PrestaShop/PrestaShop#16952]
**Describe the bug**
This bug was previously mentioned by me and others, eg #15056, #15220. Despite update PrestaShop/ps_facetedsearch#132 that should have fixed this, this bug still exists.
Basically, faceted search still shows products as available, even if that specific combination has no stock available. For example, if I filter on T-shirts with size XL, it will show me any product that ever had this combination and still has at least 1 size available (even if this size is not XL).

I've uploaded a video demonstrating this behavior here: https://www.youtube.com/watch?v=m4eaysaZ3nc

**To Reproduce**

1. Go to products in BO
2. Click on product "Hummingbird printed shirt"
3. Go to "Combinations" tab
4. Set quantity for the first 2 combinations ("Size - S, Color - White" and "Size - S, Color - Black") to 0
5. Click Save
6. In the FO, go to the Men's category
7. On the left, apply filter for size S
8. Despite having no stock available in size S, the product is still shown

**Additional information**
PrestaShop version: 1.7.6.1
FacetedSearch version: 3.4.0

**Comment by khouloudbelguith** [comment]
Hi @Twabi2,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.2 & ps_facetesearch v3.4.0.
Same issue with PS1.7.5.2 & ps_facetesearch v2.2.1
https://drive.google.com/file/d/10UOuHPQd-ODn-h-JBRZme4cCki515Vs0/view
Ping @PierreRambaud https://github.com/PrestaShop/ps_facetedsearch/pull/132

Thanks!

**Comment by valmerci** [comment]
I'm having the same problem, any progress on this issue? Visitors are complaining about user-friendliness :s

**Comment by valmerci** [comment]
Any news please?!? My online shop is only way to reach clients nowadays as the corresponding shop in the street is closed due to Corona measurements. The offer online is too big to have convenient shopping experience online with filter on size not working properly....

Thank you very much for understanding the urgency (to keep making a living) and your kind support on this issue! Most appreciated. Thank you in advance.

**Comment by khouloudbelguith** [comment]
Hi @valmerci,

Sorry not yet.
PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by ghost** [comment]
Bug still persist. 1.7.6.4 + module 3.4.1.

**Comment by MiroslavVo** [comment]
It's a very annoying issue that makes more difficult for users to browse through available products (and that unfortunately means lost sales). I hope someone will finally fix it soon.

**Comment by Hlavtox** [comment]
@Twabi2 @khouloudbelguith 

This is not a bug, but how it's done.

Stock filtering works by comparing "available for order", not the quantity itself. There was already a big discussion and rage. 😄 See https://github.com/PrestaShop/PrestaShop/issues/14518

**Comment by Twabi2** [comment]
I politely disagree. This is about combinations (i.e. and XL shirt) that are out of stock AND are not available for order (as you can see from the above examples). There is no logical reason why they should show up in the filter. See also all the other shop owners having the same issue, and all the clients emailing me about this. It simply does not make sense in its current form.

**Comment by Hlavtox** [comment]
@Twabi2 Sorry, I didn't see the video. Now I see the bug, it should not display this combination if "order out of stock items" is allowed.

**Comment by superskyman100** [comment]
> Bug still persist. 1.7.6.4 + module 3.4.1.

Bug persists 1.7.6.4 + module 3.5.0

**Comment by rudy1976s** [comment]
I have the same issue on Prestashop 1.7.6.5 and module 3.5.0.
Any news regarding patch or some "do it yourself" workaround to fix it ? This is a very frustrating bug !

**Comment by colinegin** [comment]
Hello @marionf any news on this bug ? Is it planned to work on it ?

**Comment by Kerami82** [comment]
The same problem  :( . Wait for fix.

**Comment by superskyman100** [comment]
You may wait very long, there is ages this problem is reported. I had to buy a module can't rely on hypothetic Prestashop releases.

**Comment by rudy1976s** [comment]
> You may wait very long, there is ages this problem is reported. I had to buy a module can't rely on hypothetic Prestashop releases.

What module did you choose ? I am very in hurry and I need to fix this issue "yesterday"  :)

**Comment by superskyman100** [comment]
same reason i choose to buy a module... i use this one, really good  : 
https://www.sunnytoo.com/product/easy-filter-module-for-prestashop1-7

I had to ask BEFORE buying if they could make some few integrations so that the module integrate correctly with my design > they did it in 5min. 

Support is super efficient and the module is well done (i am not seller hu, just tell you my experience is good with this module, rarely the case with other half finished works on PS marketplace)

**Comment by Kerami82** [comment]
I know. I had this problem on prestahop 1.6  :(.

**Comment by marionf** [comment]
@colinegin This bug is in the [EPIC](https://github.com/PrestaShop/PrestaShop/issues/9684) in top (first) position

**Comment by yiannis54** [comment]
For anyone that need a quick fix for the specific issue, you can follow the solution from the forum https://www.prestashop.com/forums/topic/1021601-bug-faceted-search-doesnt-filter-products-with-attributes-stock-0/?tab=comments#comment-3298966

This worked great for me, as I'm not using the "Show the number of matching products".

**Comment by Laimonas-Mituzas** [comment]
Bug still persist. 1.7.6.9 + module 3.7.1

**Comment by Hlavtox** [comment]
@hibatallahAouadni pls retest, I reworked the availability, maybe it is fixed

**Comment by sLorenzini** [comment]
Hello,

I reproduce the issue with:

- ps 1761 , Faceted search module 3.4.0 / 3.8.0 versions
- ps1778, Faceted search module 3.7.1 / 3.8.0 versions
- ps 1786 (1.7.8.x branch), Faceted search module 3.7.1 / 3.8.0
- ps 8.0.0 (develop branch), Faceted search module 3.8.0  

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
This issue is fixed with version v3.14.1 of ps_facetedsearch.

Now a new filter is available for In stock, Available and Not available products.

<img width="255" alt="Screenshot 2024-01-08 at 14 01 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a5f9c835-8bc0-45b6-8b20-43201249eed9">

**Comment by Prestafan1234** [comment]
@florine2623 This is still not solved in neither module version 3.14.1 or 3.15.1. If a product is out of stock it still shows when using the filter. Here is an example from a client's shop. 6 products are shown in the result, but it is only the first product that is in stock in the chosen size 39.

![billede](https://github.com/PrestaShop/PrestaShop/assets/50907712/f541195d-18a0-453f-99f0-eebc31ecbd39)

We can add the extra filter, but it makes no sense to first filter for alle products in a specific size and then have to filter again to see the ones that are in stock (or out of stock). It is misleading and not very good UX

**Comment by Laimonas-Mituzas** [comment]
Confirm that not fixed module version v3.16.1

**Comment by Hlavtox** [comment]
@Laimonas-Mituzas Can you please specify the precise steps to reproduce the issue? With screnshots?

- Show how the product is configured, what combinations does it have, what stock the combinations have.
- Show what you select in the filter, what it shows and what is wrong.

Thanks!

**Comment by Laimonas-Mituzas** [comment]
Here you are
![bea-1](https://github.com/user-attachments/assets/1cbd2dbc-ca21-4e8f-82e6-431f9891c180)
![bea-2](https://github.com/user-attachments/assets/1fa290a0-8f00-4909-bcc3-72070f212421)
![bea-3](https://github.com/user-attachments/assets/df6c3ee7-6ccd-4f86-bd6b-5d4c7fd8cbfe)
using PS 1.7.6.9
helped for me this solution
https://www.prestashop.com/forums/topic/1021601-bug-faceted-search-doesnt-filter-products-with-attributes-stock-0/?do=findComment&comment=3468731
implied only for file ps_facetedsearch/src/Product/Search.php
ps_facetedsearch/src/Filters/Block.php left without changes

**Comment by Hlavtox** [comment]
@Laimonas-Mituzas OK, I see you did not select products only in stock. Why do you think it's the issue that it displays all products? :-)

**Comment by Laimonas-Mituzas** [comment]
Because it is turned off, else what is the function of this  :)
![image](https://github.com/user-attachments/assets/afa5c7b9-2dde-4419-af0a-d78453d55a1a)

**Comment by Hlavtox** [comment]
No, the function is for something else. This function puts the products out of stock to the end of the list, but does not hide them.
