### ISSUE TITLE
On reset, modules are hooked in the wrong place

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16968]
This bug seems to impact all front office modules, including ps_shopping cart, ps_mainmenu, ps_searchbar module and Newsletter subscription module.

Exemple with shopping cart
If you reset the module or if you uninstall the module, clone the module from github and install it, then on FO, the cart is hooked on the wrong display.

<img src="https://user-images.githubusercontent.com/55688534/67095830-2b57e300-f1b7-11e9-8a25-680343b2efb1.png">

### Hook used is displayTop (screen with release)

<img src="https://user-images.githubusercontent.com/55688534/67095830-2b57e300-f1b7-11e9-8a25-680343b2efb1.png">

### Instead of hook displayNav2 (screen with release)

<img src="https://user-images.githubusercontent.com/55688534/67095891-47f41b00-f1b7-11e9-9671-29a27a892af2.png">

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2 & ps_facetedsearch v3.4.0.
![image](https://user-images.githubusercontent.com/16067358/71625042-f8ce5b80-2be5-11ea-8790-920c1cce7134.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by colinegin** [comment]
I think this issue not only impacts ps_shopping cart but all modules. What do you think @khouloudbelguith @sowbiba ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Yes, I think it impacts with all modules, I tried with ps_mainmenu module & ps_searchbar module and Newsletter subscription module => same issue.

Thanks!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_shoppingcart#55
