### ISSUE TITLE
When ps_crosselling module is installed too, display its informations into modal

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16969]
Spec:

If https://github.com/PrestaShop/ps_crossselling is installed too, then we can display the "Customers who bought this product also bought..." block into the shopping cart modal into https://github.com/PrestaShop/ps_shoppingcart/blob/master/modal.tpl#L4

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment]
This issue is a duplicate of #17709. I close this one in favor of the other one ;)
Thanks !
