### ISSUE TITLE
Add to cart modal not working on mobile

### ISSUE THREAD

**Issue by giwrgos88** [PrestaShop/PrestaShop#16971]
When i click on add to cart on desktop it shows the checkout modal, where on mobile it doesn't. On network tab from chrome i saw that on desktop there is call to ps_shoppingcart ajax url where on mobile is missing.

Is it a bug or im missing something?

![screen-shot-2017-11-07-at-7 50 41-pm](https://user-images.githubusercontent.com/3164113/32509203-4facfdb8-c3f5-11e7-8286-727da4cb490f.jpg)

**Comment by khouloudbelguith** [comment]
Hi @giwrgos88,

I did not manage to reproduce the issue with PS1.7.6.2 & ps_shoppingcart v2.0.3.
https://drive.google.com/file/d/1l98gC1zKx7dPuAt92444QbehbZAzrPUc/view
What is the exact version of the PrestaShop & ps_shoppingcart module did you use?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @giwrgos88, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
