### ISSUE TITLE
Broken cart

### ISSUE THREAD

**Issue by Keeldome** [PrestaShop/PrestaShop#16970]
When I press "Add to cart" I get redirect to empty cart instead actually adding product to the cart.
I checked the problem and found out that  ` initContent() ` of that module doesn't work. Could help me solve the problem?

**Comment by khouloudbelguith** [comment]
Hi @Keeldome,

I did not manage to reproduce the issue with PS1.7.6.2 & ps_shoppingcart v2.0.3.
I attached a screen record
https://drive.google.com/file/d/1KgVqO4BoXgr53w_LplmTwJDuEbX8iTl4/view
What is the exact version of the PrestaShop & ps_shoppingcart module did you use?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Keeldome, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
