### ISSUE TITLE
Personalized links

### ISSUE THREAD

**Issue by qalastar** [PrestaShop/PrestaShop#16979]
Hello,

I have an issue with this module but I'm not sure if the issue come from the module or theme.

Here is the issue : when I create a new personalized link and add it to my menu, on my website, when I click on this new personalized links from my menu, the background to show that I'm really on this page doesn't appear.

For example, if I click on the "bon" page, the background is ok.
<img width="55" alt="capture d ecran 2019-01-24 a 22 36 10" src="https://user-images.githubusercontent.com/18168804/51710202-ab865900-2028-11e9-9704-304b91f6978e.png">

Now if I click on the "accueil" page, the background is still orange instead of blue.
<img width="132" alt="capture d ecran 2019-01-24 a 22 36 36" src="https://user-images.githubusercontent.com/18168804/51710211-b345fd80-2028-11e9-891c-e2eddd13659f.png">

Do you know how I can solve this issue ?

Thanks a lot for your support.

**Comment by khouloudbelguith** [comment]
Hi @qalastar,

Thanks for your report.
Do you still have the same issue?
Have you tried to contact the theme author about this issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @qalastar, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
