### ISSUE TITLE
ignore categories authorizations

### ISSUE THREAD

**Issue by xpech** [PrestaShop/PrestaShop#16978]
The menu displays categories whereas the customer have no permission to access to.

**Comment by khouloudbelguith** [comment]
Hi @xpech,

Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9924?
If yes, it is fixed.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @xpech, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by rvalery** [comment]
Hi @khouloudbelguith,

You said 

> Have you the same issue with this ticket: #9924?
If yes, it is fixed.

But I don't see any commits in the module ps_mainmenu that would have fixed it. There is no update and the user groups are still not taken into account when creating the menu. I have proposed a pull request to correct this but it is still waiting for someone to review it.

Do you have more information on how to fix it in our shop, without creating an override file like I did ?

**Comment by khouloudbelguith** [comment]
Hi @rvalery,

The issue #9924 is fixed with this PR: https://github.com/PrestaShop/ps_mainmenu/pull/20

Thanks!

**Comment by rvalery** [comment]
@khouloudbelguith Thanks for your answer.
I see that this PR has been merged into the dev branch of the module ps_mainmenu, but not in the master branch. Do you know if the dev branch will eventually be merged into the master ? Because right now the version of the module ps_mainmenu included with Prestashop is 2.1.1, and it does not contain the fix.
Thanks for your time.

**Comment by khouloudbelguith** [comment]
@rvalery, infact, a new release is not provided yet.
https://github.com/PrestaShop/ps_mainmenu/releases
The last release is 2.1.1.
So this PR: https://github.com/PrestaShop/ps_mainmenu/pull/20, it is still not added to any release.

Thanks!

**Comment by rvalery** [comment]
OK thanks for the info, I will wait for the next release then.
