### ISSUE TITLE
Not compatible with CronJobs module

### ISSUE THREAD

**Issue by Casper-O** [PrestaShop/PrestaShop#16983]
Its not compatible with the CronJobs module from Prestashop https://github.com/PrestaShop/cronjobs

header() redirection is not executed, if you have to many entries in your sitemap
https://github.com/PrestaShop/gsitemap/blob/master/gsitemap.php#L260

https://github.com/PrestaShop/gsitemap/blob/master/gsitemap.php#L266

**Comment by khouloudbelguith** [comment]
Hi @Casper-O,

Sorry for the late response.
Do you still have the same issue?

Thanks!

**Comment by Casper-O** [comment]
Its 4 years ago i reported this bug, i am not able to tell if the issue is still there...

**Comment by khouloudbelguith** [comment]
@Casper-O, thanks for your feedback.
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.6.2), please open a new one.

Thanks!
