### ISSUE TITLE
Bug if same category appear multiple times.

### ISSUE THREAD

**Issue by marcuslind90** [PrestaShop/PrestaShop#16981]
If you have the following category structure:

- Category A
- Category A-1
- Category A-1-1
- Category A-2
- Category A-2-1

And you set both Category A, Category A-1 and Category A-2 to be displayed in the mainmenu, there will be a bug where any repeating category will get top: 0; in its css by the javascript.

**Comment by khouloudbelguith** [comment]
Hi @marcuslind90,

Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9938?
If yes, it is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/13677
Thanks to check & feedback.

**Comment by marcuslind90** [comment]
@khouloudbelguith Closing since it is 2 years old.
