### ISSUE TITLE
No correct link for "Home" (2nd level) category

### ISSUE THREAD

**Issue by manfield** [PrestaShop/PrestaShop#16980]
I  tested with a fresh installed PS 1.7.5.
If I add Home category to the main menu - in order to list all product - the link is / instead of /2-home

**Comment by khouloudbelguith** [comment]
Hi @manfield,

You can create a new link with the label "Home" & Link= `http://shop.com/2-home` then try to add this new link to the Selected items.
https://drive.google.com/file/d/1oeB1gumY3GjPH-NgUm16QI9EtTdIuOin/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @manfield, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
