### ISSUE TITLE
Call by widget

### ISSUE THREAD

**Issue by reanim8ed** [PrestaShop/PrestaShop#16982]
What's the correct way to call this module with widget on the cart page?
I have tried:
 {widget name='ps_crossselling' hook='displayShoppingCart' cart=$cart}

But the page returns 500 error then.

**Comment by khouloudbelguith** [comment]
Duplicate of #9648

**Comment by khouloudbelguith** [comment]
Hi @reanim8ed,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/ps_crossselling

Thank you!
