### ISSUE TITLE
Sitemap does not add 2 id in url

### ISSUE THREAD

**Issue by enriquetortola** [PrestaShop/PrestaShop#16984]
Good,

I'm having a little problem with the sitemap, which is not adding the 2 ids that the product has in the sitemap and this is causing the products not to be indexed correctly.

What possible solution can this drawback have?

**Comment by khouloudbelguith** [comment]
Hi @enriquetortola,

Thanks for your report.
I have the same behavior as PS1.7.6.2 & PS1.7.5.2 & gsitemap v4.1.0.
![image](https://user-images.githubusercontent.com/16067358/71664822-c98d2b00-2d5a-11ea-87a5-cca48992257b.png)
All product's combinations, which have own URLs in Prestashop too, are not listed in sitemap.xml
We have a PR introduced in PS1.7.6.2: https://github.com/PrestaShop/PrestaShop/pull/15964
Ping @PrestaShop/prestashop-product-team @jolelievre what do you think?

Thanks!

**Comment by colinegin** [comment]
Hello,

Indeed since 1.7.6.2, the canonical url (with only 1 product id) displays the content of the default attribute. Is it what you are looking for ? 

Have a nice day,

Coline

**Comment by khouloudbelguith** [comment]
Hi @enriquetortola,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
