### ISSUE TITLE
Tools::getIsset(Tools::getValue('id_shop')) return false

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#16987]
Hi,

In multistore mode, Tools::getIsset(Tools::getValue('id_shop')) return false;
With this URL : https://domain.com/modules/gsitemap/gsitemap-cron.php?token=XXXXX&id_shop=21
line 52 in gsitemap-cron.php

gsitemap version : 4.1.0
Prestashop version : 1.7.4.3

**Comment by khouloudbelguith** [comment]
Hi @01park,

Sorry for the late response.
Do you still have the same issue?

Thanks!

**Comment by 01park** [comment]
Hi,

I don't have this issue because I fixed it, but I noticed that when I update my PS to a new version I always gets overwrite with the broken version. Thats why I suggest to update the module version to the fixed one.

**Comment by khouloudbelguith** [comment]
@01par,

>I don't have this issue because I fixed it

What is the exact solution did you find?
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by 01park** [comment]
I will send you my gsitemap
[gsitemap.zip](https://github.com/PrestaShop/PrestaShop/files/4066597/gsitemap.zip)

**Comment by khouloudbelguith** [comment]
@01park, thanks!
But, would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/gsitemap
It is more easy for our developer to review your code.
Thank you!

**Comment by 01park** [comment]
Hi,

I don't know what it means to make a pull + the fix I applied I found here on Github to. I believe it was Quetzacoalt91 who fixed it.

**Comment by khouloudbelguith** [comment]
@01park, Issue fixed by this PR: https://github.com/PrestaShop/gsitemap/pull/106? is it?

Thanks!

**Comment by 01park** [comment]
Yes, I believe that's the one.

**Comment by khouloudbelguith** [comment]
@01park, since it fixed, I will close the issue.
PS: a new release for the gsitemap is not released yet.

Thanks!
