### ISSUE TITLE
Use image 'legend' when available

### ISSUE THREAD

**Issue by Pixep** [PrestaShop/PrestaShop#16989]
The sitemap should use images' legend field, as defined in products' BO page, when available. It is currently using the product name and meta description, regardless of the legend value.

From sitemap.php:
```
    'title_img' => htmlspecialchars(strip_tags($product->name)),
    'caption' => htmlspecialchars(strip_tags($product->meta_description)),
```

**Comment by khouloudbelguith** [comment]
Hi @Pixep,

I have the same behavior as PS1.7.6.2 & PS1.7.5.2 & `gsitemap` module v4.1.0.
![image](https://user-images.githubusercontent.com/16067358/71664065-de1bf400-2d57-11ea-8ae1-23809c12cc38.png)
It is good improvement.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by Pixep** [comment]
FYI, after rebasing https://github.com/Pixep/gsitemap/commit/95f5ab24d3e19dc44350f496f83bc50fd5ea5c4f some times ago, I found that `$product_image['legend']` didn't hold the legend anymore. It could be me, or a breaking change, I didn't spend much time investigating. Does this ring a bell?

**Comment by Hlavtox** [comment]
Resolved as image captions have been deprecated and removed
