### ISSUE TITLE
404 error when check the presence of the image files on the server

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#16985]
Hello,

```
PS 1.7.5.0
Sitemap 4.1.0
```

When I check the box "Check this box if you wish to check the presence of the image files on the server" I can't generate a sitemap, it return 404 error.

Without check, the sitemap is generate.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
