### ISSUE TITLE
Sitemap includes child-categories of inactive parent category

### ISSUE THREAD

**Issue by lichesser** [PrestaShop/PrestaShop#16992]
Hello,

PrestaShop: 1.7.6.1

if a category ist set to inactive (active = 0) it correctly doesn't get included in the generated sitemap anymore, but "active" child-categories of the inactive parent category are still included.

This seems unintuitive. Maybe a new solution for `getCategoryLink` is needed. I think it should be possible to use `getNestedCategories`  to get the correct category tree.

**Comment by khouloudbelguith** [comment]
Hi @lichesser,

Thanks for your report.
I have the same behavior as PS1.7.6.2 & PS1.7.5.2 & gsitemap v4.1.0.
The Inactive category is not included in the generated sitemap.
but "active" child-categories of the inactive parent category are still included.
Ping @PrestaShop/prestashop-product-team what do you think, is this a normal behavior?

Thanks!

**Comment by Hlavtox** [comment]
@lichesser This is not a bug. When you disable a parent category, their children are still accessible by anyone normally. The disabled category just disappears from breadcrumbs.

**Comment by MatShir** [comment]
Agree with @Hlavtox, if the subcategories are still actives/enabled, why hide them if the category parent is disabled.
We can have a parent category that is used for discount, like 'Products with 50%' as a category but disabled, so only the merchant knows this category.

The feature here that I can see is to propose to disable all the child category when disabling a parent category. So I close the issue for now, I can be reopened if there is more interest in the feature.
