### ISSUE TITLE
Position not persisted

### ISSUE THREAD

**Issue by ludohenin** [PrestaShop/PrestaShop#16996]
It's possible to move the slides around with drag-n-drop but it's not persisted. Worst, when manually edited in the DB, this position reset (set to 0) when the slide is edited (aka. saved).

**Comment by khouloudbelguith** [comment]
Hi @ludohenin,

Sorry for the late response.
I did not manage to reproduce the issue with PS1.7.6.2 & ps_imageslider v3.0.0.
https://drive.google.com/file/d/11_68Eo1ORY3N3WOJjcIEsynEj5VlnsX6/view
I close the issue, feel free to open a new one when needed.

Thanks!
