### ISSUE TITLE
Fatal error code

### ISSUE THREAD

**Issue by Lupi1986** [PrestaShop/PrestaShop#16993]
Hi there,

I've tried to install gsitemap, but I got an error message… Now my module area shows this error code :

[PrestaShop] Fatal error in module file :/home/xxxxxxxx/public_html/modules/gsitemap/gsitemap.php:
Uncaught Error: Call to undefined method Gsitemap::trans() in /home/xxxxxxxx/public_html/modules/gsitemap/gsitemap.php:47 Stack trace: #0 [internal function]: Gsitemap->__construct() PrestaShop/gsitemap#1 /home/xxxxxxxx/public_html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(124): ReflectionClass->newInstance() PrestaShop/gsitemap#2 /home/xxxxxxxx/public_html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(157): Core_Foundation_IoC_Container->makeInstanceFromClassName('gsitemap', Array) PrestaShop/gsitemap#3 /home/xxxxxxxx/public_html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(170): Core_Foundation_IoC_Container->doMake('gsitemap', Array) PrestaShop/gsitemap#4 /home/xxxxxxxx/public_html/Adapter/Adapter_ServiceLocator.php(52): Core_Foundation_IoC_Container->make('gsitemap') PrestaShop/gsitemap#5 /home/xxxxxxxx/public_html/classes/module/Module.php(1370): Adapter_ServiceLocator::get('gsitemap') PrestaShop/gsitemap#6 /home/xxxxxxxx/public_html/controllers/admin/AdminModulesController.php(1443): ModuleCore::getModulesOnDisk(true, false, 4) PrestaShop/gsitemap#7 /home/xxxxxxxx/public_html/classes/controller/Controller

Could you please help me ?

Best regards,

Lupi

**Comment by khouloudbelguith** [comment]
Hi @Lupi1986,

I did not manage to reproduce the issue with PS1.7.6.2 & gsitemap module v4.1.0.
https://drive.google.com/file/d/1ZtWl3VA7gtnBpCmpNc6Cdoi4vmTTr91c/view
Did you try to install this module from the BO => Modules => Module Catalog Page?

Thanks!

**Comment by Lupi1986** [comment]
Hi,

It was such a long time ago... I've had to find a solution by myself and
got rid of your module.

Lupi1986

**Comment by khouloudbelguith** [comment]
@Lupi1986, sorry for the late response!
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by gabi861** [comment]
Hello! i have the same problem, can you tell me how did you solve the problem?
