### ISSUE TITLE
Bug install

### ISSUE THREAD

**Issue by pandiheberge** [PrestaShop/PrestaShop#16990]
Hello,

It is not possible to install it on prestashop 1.6.1.23

2 erreurs

    Une erreur est survenue pendant l'extraction du module (le fichier peut être corrompu).
    Impossible de mettre à jour le module Google sitemap : erreur lors de l'extraction de la dernière version.

Thank you for your help

**Comment by khouloudbelguith** [comment]
Hi @pandiheberge,

Thanks for your report.
I have the same issue with PS1.6.1.23 & Google sitemap v3.2.2.
![image](https://user-images.githubusercontent.com/16067358/71661515-b5433100-2d4e-11ea-8e49-4be460103ecc.png)
It is ok with PS1.7.6
Ping @colinegin, this module is not compatible yet with PS1.6 yet? this module can be supported?

Thanks!

**Comment by colinegin** [comment]
Hello @khouloudbelguith ,

it's weird, the version 3.2.2 of this module is supposed to be working on 1.6 versions only. 
The version 4.0.0+ is for 1.7 versions.

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Yes, Google sitemap v4.1.0, is well installed with PS1.7.6.
But with PS1.6.1.24, Google sitemap v3.2.2 NOK.

Thanks!

**Comment by marionf** [comment]
Hello,

PrestaShop 1.6 [isn't maintained anymore](http://build.prestashop.com/news/1.6.1.x-what-s-next/). The maintenance for this version is now being performed exclusively by volunteers to fix critical issues.
You can open an issue on the [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues). Please keep in mind that only critical issues will be acknowledged.

Regards
