### ISSUE TITLE
504 Gateway Timeout upon sitemap generation

### ISSUE THREAD

**Issue by Fixmetal** [PrestaShop/PrestaShop#16995]
Hello,
I've got an odd problem which I can't debug really. I've got PS 1.7.5.2 with single store on Ionos shared hosting, PHP 7.2, MySQL 5.5, Apache 2.4.
The gsitemap module keeps getting timeouts while trying to create a sitemap regardless of id_shop=1 (Italian language) or id_shop=2 (English language).
I've put 900seconds as max_execution_time=900 in my php.ini but that doesn't really help.
I keep getting a 504 Gateway Timeout.
Manual or cron act just the same.

**Comment by khouloudbelguith** [comment]
Hi @Fixmetal, @sickboards,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/16991?

Thanks!

**Comment by sickboards** [comment]
I don't think so as it sometimes works and sometimes it just stops after creating 2 sub files

**Comment by khouloudbelguith** [comment]
Hi @sickboards, 

In my case, with PS1.7.6.2 & `gsitemap` v4.1.0, we are redirected to the "Module Catalog" page after clicking to regenerate sitemap.
I attached a screen record
https://drive.google.com/file/d/19cSxMqTYP8nm0SVIbRfv7utYhkx70Xg6/view
The error 504, it is a gateway timeout: The server was acting as a gateway or proxy and did not receive a timely response from the upstream server

Thanks!

**Comment by sickboards** [comment]
I am guessing you don't have 18k products?

**Comment by khouloudbelguith** [comment]
@Fixmetal, I have 42464 products.
![image](https://user-images.githubusercontent.com/16067358/71813530-213cd680-307a-11ea-86dd-14b71f895229.png)

Thanks!

**Comment by Fixmetal** [comment]
> Hi @Fixmetal, @sickboards,
> 
> Is it the same issue with this ticket: #16991?
> 
> Thanks!

I think we have ~12000 products. Numbers are big but not that big.
Thanks

**Comment by khouloudbelguith** [comment]
@Fixmetal, thanks to check if this PR: https://github.com/PrestaShop/gsitemap/pull/127 is fixing your issue?

Thanks!

**Comment by Fixmetal** [comment]
I may be wrong but it seems to me that #127 is merged in dev branch only...or am I misreading this?

**Comment by khouloudbelguith** [comment]
@Fixmetal, not this PR: https://github.com/PrestaShop/PrestaShop/pull/127
You need to check this one: https://github.com/PrestaShop/gsitemap/pull/127, it is a fix into the gsitemap module, only one file changed: https://github.com/PrestaShop/gsitemap/pull/127/files

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Fixmetal,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
