### ISSUE TITLE
Controller paths in sitemap XML - causing 404 errors in Search Console

### ISSUE THREAD

**Issue by TeapotJames** [PrestaShop/PrestaShop#16994]
Is anyone else getting controller paths in the output of their XML file?

If I visit the XML output file - https://www.angelalangford.com/1_en_0_sitemap.xml I can see the following paths…

https://www.angelalangford.com/index.php?controller=product
https://www.angelalangford.com/index.php?controller=category
https://www.angelalangford.com/index.php?controller=cms

These paths are giving me 404 errors in Search Console.

In the back office for the module I can see options for [cms], [product] and [category] alongside the usual options. If I click these to disable them and regenerate the sitemap I don't get an CMS pages, Products or Categories showing in the sitemap, so obviously I've left them unticked as I want these in the XML file, but doing that means I now have the unwanted controller paths in the XML file . Anyone else getting this with version 4.1.0 of the module?

![Screen Shot 2019-12-06 at 13 26 40](https://user-images.githubusercontent.com/15928931/70326284-151bea00-182c-11ea-8408-74031e9d7957.png)

**Comment by khouloudbelguith** [comment]
Hi @TeapotJames,

I tried with PS1.7.6.2 & `gsitemap` v4.1.0.
I don't have those links
Here's my sitemap generated
[1_en_0_sitemap.pdf](https://github.com/PrestaShop/PrestaShop/files/4019931/1_en_0_sitemap.pdf)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @TeapotJames,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by xrdm** [comment]
Same problem is presents in module version 4.2.0
and PS 1.7.6.8

The issue seems to be in generation link -> .../modules/gsitemap/gsitemap-cron.php?token=c14c0889a4&id_shop=1

If I create the sitemap by "GENERATE SITEMAP" the sitemap is correctly generated
After if I use generation link the sitemap exclude categories, products and cms pages.

**Comment by bcsirt** [comment]
Hi have the same issue.
Can prestashop correct this problem ?

**Comment by DaniGithub** [comment]
I have the same issue 👍 Using PS1.7.7.1 and module version 4.2.0 (which is the latest as of this moment)
