### ISSUE TITLE
[PrestaShopException] Link to database cannot be established:SQLSTATE[42000] [1044] Access denied for user 'froncare'@'localhost' to database 'froncare' at line 102 in file classes/db/DbPDO.php

### ISSUE THREAD

**Issue by froncare** [PrestaShop/PrestaShop#17015]
[PrestaShopException]
Link to database cannot be established:SQLSTATE[42000] [1044] Access denied for user 'froncare'@'localhost' to database 'froncare'
at line 102 in file classes/db/DbPDO.php

This message is keep showing up what should I do

**Comment by arouiadib** [comment]
Hi @froncare,

* Is the user `froncare` exist in database?
* Is the user `froncare` granted privileges to access database `frontcare`?
You can grant him all privileges by executing the SQL command:

```
> GRANT ALL PRIVILEGES ON frontcare.* TO 'frontcare'@'localhost';
> FLUSH PRIVILEGES;
```


* Do you have the correct password in `app/config/parameters.php`?

What is your PrestaShop version? Even if I believe it is not a PrestaShop issue.

**Comment by froncare** [comment]
yes Froncare is the database name and 
I have no idea how to check and do Is the user froncare granted privileges to access database frontcare?
You can grant him all privileges by executing the SQL command:
> GRANT ALL PRIVILEGES ON frontcare.* TO 'frontcare'@'localhost';
> FLUSH PRIVILEGES;

**Comment by khouloudbelguith** [comment]
Hi @froncare,

When this message appears, it means your database is down.
The problem comes from your web host. 
Your issue is not related to PrestaShop => it is an error on your server.

Try to connect to your MySQL server in command line if you can, `mysql -u MYSQL_USER -p DATABASE_NAME -h DATABASE_HOST` try to connect by replacing values.

 Please contact your hosting provider, which is the only one that can do anything.

Thanks!

**Comment by ctcamp** [comment]
Hi there
I have just moved 2 of my Prestashop websites to a new server. Version 1.6.
I am having the same error come up on both the sites and it seems the settings.inc.php file contains the right information.
The new host is not able to find the problem on their side.
Could anybody please help me give the Host more specific information, so they can sort the problem out for me.
Thanks in advance
ct

![Capture](https://user-images.githubusercontent.com/53556970/108844098-4ffe6f00-75e4-11eb-97c9-1edf7d45be03.PNG)
![Capture1](https://user-images.githubusercontent.com/53556970/108844105-512f9c00-75e4-11eb-821d-7f5ada57de73.PNG)
