### ISSUE TITLE
paypal safari mac

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#17012]
hello, can you test if paypal in context, have an issue also, paypal in genreal latest version on latest version of prestashop. I think multiple currencies are the problem...ajax reload or something, tested with safari mac

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

I did not manage to reproduce the issue with PS1.7.6.2 & Paypal v5.0.3.
I attached a screen record
https://drive.google.com/file/d/1zA_1T9a14ZS_Dadsivvgm_zDJh3N23HT/view
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account:https://addons.prestashop.com/en/contact-us?id_product=1748, they are the only ones to help you with it.
Thanks!
