### ISSUE TITLE
LayoutExtension cannot find the {$content} string in legacy layout template

### ISSUE THREAD

**Issue by augustu5** [PrestaShop/PrestaShop#17021]
After manual upgrade (https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/) to 1.7.6.2 almost on every admin page I get an Error:
![image](https://user-images.githubusercontent.com/12048630/71738629-7056f180-2e57-11ea-8dab-295cd343e6c1.png)

There are some exceptions, for example I can view orders, but for the most pages there's this rendering exception. 

I've tried to clean cache (symfony style, and manually).
Also I've double checked file permissions. 
I also compared database structure to PS fresh installation. 
Still nothing. 

Fresh installation works fine.

Any ideas what else I could try?

**Comment by khouloudbelguith** [comment]
Hi @krystian-3c,

Seems to be similar to those tickets: 

- https://github.com/PrestaShop/PrestaShop/issues/10853#issuecomment-439609080
- https://github.com/PrestaShop/PrestaShop/issues/10786#issuecomment-426221903

PS: You can find the full schema for 1.7.6.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.2/install-dev/data/db_structure.sql
Thanks to check the solution & feedback.

**Comment by khouloudbelguith** [comment]
Hi @krystian-3c,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
