### ISSUE TITLE
Remove Google+ from social modules

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17026]
Google+ is no longer available since April 2019.
We need to remove it from both native social modules.

Pull requests are already created:
- https://github.com/PrestaShop/ps_socialfollow/pull/13
- https://github.com/PrestaShop/ps_sharebuttons/pull/29

**Comment by jf-viguier** [comment]
Please merge

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

As written by the support team, `Google+ is only available for G Suite accounts through work or school. Consumer accounts (typically ending in @gmail.com) were shut down on April 2nd, 2019.`
https://support.google.com/plus/announcements/9195238
I’ll add this to the debug roadmap
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/16040

**Comment by Progi1984** [comment]
Two PR have been merged.
