### ISSUE TITLE
An unexpected error occurred when creating a new address with unregistered customer email

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17031]
**Describe the bug**
A red alert is displayed "`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerByEmailNotFoundException code 0]`" when creating a new address with unregistered customer email

**To Reproduce**
1. Go to BO => Customers => Addresses page
2. Click Add a new Address
3. Set unregistered customer email for the first filed for example test@test.com
4. Click outside
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/71822757-f8c2d580-3095-11ea-84fe-d5f41f78d338.png)

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17191
