### ISSUE TITLE
Adresses page - Required Fields cannot be selected which occurs issues in the BO & the FO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17032]
**Describe the bug**
In the BO => Customers => Addresses page => the required Fields cannot be selected which occurs issues in the BO & the FO

**To Reproduce**
1. Go to BO => Customers => Addresses page
2. Click on the button "Set required fields for this section"
3. Select all options
4. Save
5. A green alert is displayed
6. Click on the button "Set required fields for this section" again => the files are not selected => **NOK**
https://drive.google.com/file/d/1sdn7gWMhIA42IbjrH0zoA-rhE93l6RBP/view
7. In the **BO** => Click Add a new Address & set all required fields with the required symbol
8. Save => see error
![image](https://user-images.githubusercontent.com/16067358/71822394-06c42680-3095-11ea-9fe7-b334640e88f4.png)
9. In the **FO** => try to create an order with `John Doe` => In the checkout page, we have an exception
![image](https://user-images.githubusercontent.com/16067358/71823399-66233600-3097-11ea-884e-31f4b98ff8d6.png)

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by zuk3975** [comment]
I think this is related https://github.com/PrestaShop/PrestaShop/issues/9845

**Comment by MatShir** [comment]
fixed by #17526

**Comment by colinegin** [comment]
Hello @khouloudbelguith the bug is on develop or on the 1.7.7.x branch ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Same issue with branch 1.7.7.x.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #17526
