### ISSUE TITLE
It is not possible to create an alternative currency

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17040]
**Describe the bug**
In the BO => International => Currencies page, it is not possible to create an alternative currency.

**To Reproduce**
1. Go to BO => International => Currencies page
2. Click on Add new currency "Create an alternative currency"
3. Set the Currency name field for example "test"
4. Set the ISO code field for example "en"
5. Save
6. See error => the page is refreshed
![image](https://user-images.githubusercontent.com/16067358/71889133-ca023900-3141-11ea-9b78-41523a287f9b.png)

It is detected by the nightly, related to this pr: https://github.com/PrestaShop/PrestaShop/pull/16668
**Screenshots**
https://drive.google.com/file/d/1yACauJvAiAfBu8LY81RFmSIVUVobZA8t/view

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @jolelievre

**Comment by marionf** [comment]
Reopened, as it's  a regression the PR should be on 1.7.7.x instead of develop

**Comment by marionf** [comment]
Fixed on 1.7.7.x by: https://github.com/PrestaShop/PrestaShop/pull/17291
