### ISSUE TITLE
Manage newsletter subscription in a modern ajax way in ps_emailsubscription module

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17054]
Newsletter subscription in ps_emailsubscription module uses an old fashion "post to home page" form with several issues :
- After subscribing, the user is redirected to the home page.
- If the module is hooked several time, a buggy message tel the user that his email has already been used (see https://github.com/PrestaShop/PrestaShop/issues/15629)

I suggest to manage newsletter subscription in ajax. This is more elegant and avoid full page reload. I've got a PR for that : https://github.com/PrestaShop/ps_emailsubscription/pull/48

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by colinegin** [comment]
I like the idea ! Thanks @jf-viguier for this detailed explanation and PR.
@TristanLDD @PrestaShop/prestashop-core-developers wdyt ?

**Comment by jf-viguier** [comment]
Thanks @colinegin.
For the UX, I've sticked to actual behavior, I've just placed alert message above the form to match other ps behaviors (customer subscription, login).

**Comment by colinegin** [comment]
ping @TristanLDD @prestascott what do you guys think ?

**Comment by TristanLDD** [comment]
Hi @jf-viguier, 
Thanks for the PR, I like the idea a lot! 

It seems to have some problems to display the confirmation or error messages though: 

- The error message for an invalid email address for example doesn't seem to appear. Here is the message in the current module: 
![Capture d’écran 2020-02-19 à 18 22 52](https://user-images.githubusercontent.com/27484094/74858242-45f8bf00-5345-11ea-88c0-a8423a60060c.png)

- The confirmation message doesn't display properly either, the green box is there but there is no text inside: 
![Capture d’écran 2020-02-19 à 18 27 22](https://user-images.githubusercontent.com/27484094/74858375-80faf280-5345-11ea-9976-78ea1fd451fe.png)

I'm not sure if the problem could come from my side though, what do you think?

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_emailsubscription#48
