### ISSUE TITLE
Can't create new customer

### ISSUE THREAD

**Issue by Lucian06** [PrestaShop/PrestaShop#17053]
When a new customer registers in my shop he/she gets ID = 0 and then can't log in. When I try to edit or delete the user from the back-end I get the User does not exist error.

**To Reproduce**
1.Install Prestashop 1.7.6.1 on a new server
2. Import some customers from the old shop(PrestaShop 1.7.5.2) via the import tool
3.Upgrade to PrestaShop 1.7.6.2
4. Create new users

**Screenshots**
![users](https://user-images.githubusercontent.com/17837474/71916582-ec6a7580-3186-11ea-8d4c-290f1465f8c7.PNG)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.24

**Comment by khouloudbelguith** [comment]
Hi @Lucian06,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.2 after an upgrade from PS1.7.6.1 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1Wvde3tp9wI_3mlugnvkf6Xd7xyaBLdSj/view
Thanks to check & feedback.

**Comment by Lucian06** [comment]
Hi @khouloudbelguith 

Have you tried to import some users via Advanced parameters > Import

Please tell me if I can help you with something else?

**Comment by khouloudbelguith** [comment]
@Lucian06, before the upgrade? or after the upgrade?
If before the upgrade yes, well tested as you can see in my screen record

Thanks!

**Comment by Lucian06** [comment]
It was a problem with the customer's table. I drop and re-create the table and now it works. 

Thank you

**Comment by khouloudbelguith** [comment]
@Lucian06, great!
Feel free to open a new one when needed.

Thanks!
