### ISSUE TITLE
Error update for 1click upgrade from prestashop 1.7.6.1 to 1.7.6.2 

### ISSUE THREAD

**Issue by kostya07** [PrestaShop/PrestaShop#17057]
I tried to update from prestashop 1.7.6.1 to 1.7.6.2 from 1click upgrade v4.10.1  from Menor channels. 
and get an 500 error. 

PHP 7.2,  MySQL 5.7

![Screenshot_59](https://user-images.githubusercontent.com/19917921/71923134-ff844200-3194-11ea-99fa-8831933a5503.jpg)

![Screenshot_44](https://user-images.githubusercontent.com/19917921/71918874-f80c6b00-318b-11ea-8802-6c938b4034c9.jpg)

Server log
[Tue Jan 07 17:32:19.922181 2020] [core:alert] [pid 27067:tid 140316220507904] 
.htaccess: Option MultiViews not allowed here, referer 

Can you help me?

**Comment by khouloudbelguith** [comment]
Hi @kostya07,

You need to add or update the line AllowOverride to include `Options=All,MultiViews` to your Apache virtual host, the vhost configuration file should then look like:

```
<Directory /var/www/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride Indexes Options=All,MultiViews
Order allow,deny 
allow from all 
</Directory>
```
If you had other `AllowOverride` directives you only need to add the` Options=All,MultiViews` one. For more details, you need to check your host.

Thanks to check & feedback.

**Comment by kostya07** [comment]
Thx.
how to perform an update on a server where the MultiViews parameter is not supported and there is no way to activate it?

**Comment by khouloudbelguith** [comment]
@kostya07, you need to check your host about this issue.
Thanks!
