### ISSUE TITLE
issue upgrade for 1.7.4 version

### ISSUE THREAD

**Issue by ENsports** [PrestaShop/PrestaShop#17062]
Hello,

i have an issue to upgrade my prestashop. All arrow are in green, I start the upgrade and then I have a message error (see picture)

Thank you in advance.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![upgrade fail](https://user-images.githubusercontent.com/59645603/71967585-dc44ab80-3203-11ea-905c-fe60adeb5f93.png)

**Additional information**
PrestaShop version: 1.7.4
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ENsports,

It is not allowed to write on your disk & there is no space available on it.
If you don't have access, you can check with your host to give the right permission.
Give the write and read access.
`$ chown -hR www-data:www-data ./Project_Folder_name`
Some hosts might require you to use` CHMOD 777`, although it is not recommended for anything more than a one-time need.
If you have to use CHMOD 777, make sure to switch to a safer setting (for instance, 775 for folders and 664 for files) once you are done upgrading.
Thanks to check & feedback.

**Comment by ENsports** [comment]
Hello thank you, but for what folders I need to change the CHMOD ?

**Comment by khouloudbelguith** [comment]
@ENsports, Your Project_Folder PrestaShop.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ENsports,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
