### ISSUE TITLE
Add an hook to ps_emailsubscription for newsletter registration/unregistration

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17075]
Actually, a module with external registration (like mailchimp, mailjet, sendinblue, ...) cannot plug to the ps_emailsubscription module.
Adding a hook to handle this should be great.

**Comment by sarahdib** [comment]
Hi @jf-viguier,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team  what do you think of this improvement?

Thanks!

**Comment by jf-viguier** [comment]
It could be useful for adding an extra email address check : a captcha, spam filter, ...

**Comment by jf-viguier** [comment]
My PR https://github.com/PrestaShop/ps_emailsubscription/pull/49

**Comment by marionf** [comment]
It seems a good idea :+1:
