### ISSUE TITLE
Migrate "Customer Service > Merchandise Returns > View & Edit" page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17081]
Part of Symfony migration project
Type: page

# Status

Todo:
- [ ] #19420 Migrate view

**Comment by matks** [comment]
According to @JevgenijVisockij user can also edit on this page, so I modify the name of the page.

**Comment by matks** [comment]
According to @JevgenijVisockij this page could benefit, through migration, of small UX improvements
=> to be seen with @MatShir and @TristanLDD

**Comment by LouiseBonnard** [comment]
Hey guys, interesting feedback linked with the merchandise returns page: #19199.

**Comment by MatShir** [comment]
@JevgenijVisockij, be careful on your migration PR, there is a Pr for the https://github.com/PrestaShop/PrestaShop/issues/19199 that will be merged for the 1.7.7 very soon.
thanks @LouiseBonnard

**Comment by JevgenijVisockij** [comment]
Hey. I separated merchandise return into smaller parts to make it easier to review, test and merge. Currently plan is:

1. Initial merchandise return view migration. Only view with state saving, no PDF printing or product list.
2. Product LIst for merchandise return view
3. PDF printing. Start replacing all PDF printing in modern controller so die is no longer used.
4. Rename the remaining merchandiseReturn classes/files into orderReturn for code consistency. 

Maybe we can update todo to include this list?

**Comment by matks** [comment]
@JevgenijVisockij I created a new GitHub issue to follow this complex topic. https://github.com/PrestaShop/PrestaShop/issues/24421

In the new issue is the roadmap you suggested 😉
