### ISSUE TITLE
Cannot change activation state on many requested products

### ISSUE THREAD

**Issue by Leo-pold-02** [PrestaShop/PrestaShop#17083]
**Describe the bug**
Cannot change activation state on many requested products / Error message

**To Reproduce**
1. Go to Catalogue
2. Click on Products
3. Try to Deactivate a Product(on the green hook)
or
Same isse when i go to the product page (settigs) and klick on deactivate and safe

If i try deactivating a newly set up product it works. 
My guess it that itt has something to do with my shopdate that i imported from the 1.6. prestashop via 1 click upgrade and with @khouloudbelguith great help to change the database setting. But i guess i must have missed something important. 
See here : https://github.com/PrestaShop/PrestaShop/issues/16282

Additional information
PrestaShop version: 1.7.6.1.
PHP version: 7.1.
All Modules Uptodate

Would realy appreciate your help. Thanks!

**Comment by sarahdib** [comment]
Hello @Leo-pold-02 

Thank you for the report. 

Can you send us a screenshot with the error ?

Sarah

**Comment by Leo-pold-02** [comment]
Hello,

Sure!

if i klick the green hook on the product list under status:
![Bildschirmfoto 2020-01-09 um 15 37 15](https://user-images.githubusercontent.com/57262480/72081961-b6043600-32ff-11ea-96f3-e64085615ff1.jpg)

If im in the product and want to deactivate it or channge visibility settings under Product options:
![Bildschirmfoto 2020-01-09 um 16 48 30](https://user-images.githubusercontent.com/57262480/72082060-e2b84d80-32ff-11ea-9749-960de3c56629.jpg)

Debug mode is on

**Comment by sarahdib** [comment]
Hello @Leo-pold-02 

Thank you for the screenshot.
I didn't reproduce the problem.
I install a shop using prestashop 1.6.1.24 then upgrade to 1.7.6.2 and try to enable/disable product.

**Comment by Leo-pold-02** [comment]
Hey @sarahdib 
Thanks for your help. Unfortunatly im allready in the middle of the final design process and i did the miggration to the 1.7. shop with the difficult database move of the new tables and such. 
@khouloudbelguith helped me with it. So i dont have a chace of going back to the old prestaverison and do it all over again since it took me a good week to make it happen before :)
I was hoping there is a simple error in the Database file or such. or a workaround or something. 
Strangly i can edit product descriptions and such, just the disabling does not work now. 
Any other ida how to fix it without doing the whole process again? 
Best Leo

**Comment by sarahdib** [comment]
Hello @Leo-pold-02 

Unfortunately, we can not reproduce the problem. 
You can try to contact our support team they will help you with the upgrade. 

I'll close this issue.

**Comment by Leo-pold-02** [comment]
Hi Sarah, 
I found this error in the console maybe that helps. 
The issue also occures if i want to change the assigned category of a product. 

![Bildschirmfoto 2020-01-09 um 21 51 06](https://user-images.githubusercontent.com/57262480/72153871-611ff880-33af-11ea-970a-df21d8b9943c.png)

I can try to fine more bug reports if you tell me where i should look, thanks!

**Comment by Leo-pold-02** [comment]
Would be great if you could reopen this since i really need to try and solve the issue, thanks a lot sarah!

**Comment by Leo-pold-02** [comment]
Hi @sarahdib 
Woudl you have any other tip for me how to fix this? 
Would really apreciate your help. 
Does the new screenshot help at all?
Best
Leo

**Comment by fyndpriser** [comment]
I have the same problem after upgrading to 1.7.6.3
https://imgur.com/BAcBZf9

**Comment by fyndpriser** [comment]
When I select multiple products to disable them the error message appears.
If I enter any product to disable it I can do so without any problem
https://imgur.com/Yrd9ipV

**Comment by Leo-pold-02** [comment]
@fyndpriser ok im sorry. please let me know if you find a souloution. I tried opening another ticket for it but with no relults unfortunatly.

**Comment by fyndpriser** [comment]
Try the below commands.
update ps_product_shop SET date_upd = "2020-02-03 07:59:28";
update ps_product SET date_upd = "2020-02-03 07:59:28";

OR

update ps_product_shop SET date_add = "2020-02-03 07:59:28";
update ps_product SET date_add = "2020-02-03 07:59:28";

**Comment by Leo-pold-02** [comment]
Dear @fyndpriser , thanks for the input. Could you advise me where and how i can do these commands. Im very new to this whole database stuff so i am afraid to destroy things. Would be so nice if you or someone could help me here with a more detailes step by step guide. Thanks!

**Comment by Lucekvip** [comment]
Hi, I had the same problem with mass changes after upgrade from 1.6... to 1.7.6.5  the reason was that description in resume/option tab on products was to long I guess that in older versions of Presta limit was different. In 1.7 I couldn't also save any changes after edit product because of character limit, that's how I discovered the solution, after changing descriptions in resume tabs on few products mass changes for that products started to work, then I've change all of them and now it's ok. Maybe this will help you. Regards.

**Comment by popkutt** [comment]
In my case it was a forbidden character * in product link_rewrite, table ps_product_lang, imported directly to MySQL.
