### ISSUE TITLE
Update the number of PrestaShop stores in the installer

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17099]
When installing PrestaShop, the number of PrestaShop stores mentioned is _250,000_ while it should be _300,000_ as officially communicated.

<img width="618" alt="Capture d’écran 2020-01-10 à 16 06 38" src="https://user-images.githubusercontent.com/32565890/72163034-52dbd780-33c3-11ea-9488-c4ddebdf00d1.png">

**Comment by Progi1984** [comment]
Fixed in #17100
