### ISSUE TITLE
New translation system for email subjects on ps_emailalerts

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17096]
We need to replace `Mail::l()` function with new translation system for email subjects on `ps_emailalerts` module. This module is the only one to use this old translation function.

Ex : replace `Mail::l('Product out of stock', $id_lang)`
with `$this->trans('Product out of stock', array(), 'Emails.Subject')`

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think?

Thanks!
