### ISSUE TITLE
Admin Tables Sorting Broken?

### ISSUE THREAD

**Issue by mcdado** [PrestaShop/PrestaShop#171]
If I go to the BO > Catalog > Categories, the table isn't sorting correctly. Somehow always sort by position. Moreover, if you are in a nested category, when trying to sort the list, you will always be pulled back to the root. I addressed this in Pull Request #163

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
