### ISSUE TITLE
Private function can't be overrided

### ISSUE THREAD

**Issue by Onliste** [PrestaShop/PrestaShop#17102]
https://github.com/PrestaShop/ps_categoryproducts/blob/84c308c249bfd8ecb710450614c4d291e8799d3a/ps_categoryproducts.php#L327

**Comment by khouloudbelguith** [comment]
Hi @Onliste,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
