### ISSUE TITLE
French traduction 

### ISSUE THREAD

**Issue by tunam007** [PrestaShop/PrestaShop#17109]
Good morning,

I contact you because I have a problem with the module, I created in the mail folder of the module the mails in French but it always sends the mails of follow-up in English. And in prestashop translation, the email is displayed in french but I can't modify it. Could you help me?

**Comment by hibatallahAouadni** [comment]
Hello @tunam007 

This issue is related to this one #9585, it means when we fix the latest, your problem should be fix.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9585
