### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by xavivag** [PrestaShop/PrestaShop#17108]
Emails subject cannot be translated.

**Comment by stephR** [comment]
I confirm too.. I see that some strings in the ps_reminder.tpl file are written with different methods : 
```
 $this->trans(
                    'Discount for your cancelled cart',
                    array(),
                    'Modules.Reminder.Admin')
```
and others like this : 
```
Mail::l(
                        'Your cart and your discount', 

```

Do you know why ?

**Comment by khouloudbelguith** [comment]
Hi @xavivag, @Le-Bodyguard, @stephR, 

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9599?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @xavivag,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
