### ISSUE TITLE
With cache enable and multishop in ps 17.4.4 disabled products are shown

### ISSUE THREAD

**Issue by al699** [PrestaShop/PrestaShop#17105]
I have a lot of broken links because ps_categoryproducts show disabled products until I save again the config in the module.

I am not sure if is a cache problem.

PHP: 7.1.17
SO: ‪Debian 9.4‬
PPlesk Onyx 17.8.11

**Comment by khouloudbelguith** [comment]
Hi @al699,

Sorry for the late response.
Do you still have the same issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @al699,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
