### ISSUE TITLE
Stock manager use wrong idshop to display title

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#17114]
Hello,

I notice something strange in Stock manager.

I started my shop with multishop option.
So in the database, in product table, I have idshop = 0 and idshop = 1

A little bit after, I thought that I made a mistake and I finally decide to return in "one shop" option.

But I can see now, In Stock Manager, I have some product without title.
After deactivate multishop, it seems Stock Manager use only idshop 0, instead check which idshop is currently run.

I'm not sure about my explanation, don't hesitate if you have any questions :)

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
What is the exact version of the PS did you use?
Can you please add steps to reporduce the issue in a new comment.

Thanks!

**Comment by BenTen** [comment]
Sorry I forgot to write, it's 1.7.5.0

**Comment by khouloudbelguith** [comment]
@BenTen, Can you please add steps to reporduce the issue in a new comment.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
