### ISSUE TITLE
Incorrect price due to cache

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17111]
In ps_featuredproducts, ps_specials, ...
The current cache strategy "getCacheId()" does not use all the variables that affect the price, proving that incorrect values are shown in the price to many customers.

For example, two escenarios:

- If the first customer (the one that triggers the regeneration of the cache) has a specific discount: Then the discounted price is saved and shown to all customers.
- If a client applies a tax rule and another does not.

As a temporary solution I have disabled the module cache.

This issue can be fixed by adding this method to `ps_featuredproducts` (and others) module class: 

```php
protected function getCacheId($name = null)
{
    $cacheId = parent::getCacheId($name);
    if (!empty($this->context->customer->id)) {
        $cacheId .= '|' . $this->context->customer->id;
    }
		
    return $cacheId;
}
```

https://user-images.githubusercontent.com/194784/132044777-e6432430-4765-407b-b36f-a916e059c5ec.mov

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Agree with the problem, same problem already appeared with faceted search months ago :)

**Comment by jf-viguier** [comment]
@PierreRambaud how did you solve this in faceted search ?

**Comment by jf-viguier** [comment]
The cache should be customer dependant instead of group dependant but what's the best way to do that ?

**Comment by davidglezz** [comment]
we have to collect all the parameters that affect the price of the products and override the getCacheId() method.

I can do a pull request, but first let's discuss what the parameters / variables are.

- Original vars (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/Module.php#L2437-L2460) plus:
- customer if exist, or:
- Country
- state
- ??

**Comment by davidglezz** [comment]
updated description with a video
