### ISSUE TITLE
Add to cart doesn't work if site hasn't finished loading or if loading was somehow interrupted

### ISSUE THREAD

**Issue by darylstone** [PrestaShop/PrestaShop#17118]
**Describe the bug**

If you visit any prestashop store, switch directly to a product page and try to add directly a product to cart, the product won't be added to cart. Instead you will be redirected to an empty cart.
 
I was able to reproduce that issue on every 1.7 installations of mine and on any random demo from addons.prestashop.com. 

An example from addons.prestashop.com, which has also the same issue: 
https://demomodules.lineagrafica.es/17/lgcookieslaw/01/en/art/3-13-the-best-is-yet-to-come-framed-poster.html#/19-dimension-40x60cm

However, that issue appears also if the site hasn't been loaded the way it should have - caused by 2g, 3g internet connection or any interrupted loading. If you refresh the page afterward, the issue still exists, as it seems to be cached with that issue.

**To Reproduce**

1. Use a slow network or a slow VPN (opera browser has one included). Otherwise you may download and use opera GX also, this one has function to limit internet speed.
2. Clear Browser history incl. all other stuff like cache
3. Go to any Prestashop store and go to the product page
4. Click quickly on add to cart
5. See error

I did record it also (only 298kb :)) ) :
https://filebin.net/7nn3i4w63mi45vz4/20200111_221412__2_.mp4?t=0shilusq

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by stephR** [comment]
I confirm.. same problem on 1.7.6.1...

**Comment by darylstone** [comment]
> I confirm.. same problem on 1.7.6.1...

True, I have been able to reproduce that also on 1.7.6.1. Perhaps the issue started with 1.7 - at least I have not been able to reproduce that on 1.6. Which means, there might be hope for a solution- :)

**Comment by khouloudbelguith** [comment]
Hi @darylstone, @stephR,

I tried with a very very slow connection & the products are well added to the cart.
I used PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/18bFaNwqicEHRSMQiBaUkmkwY-Ujg18tp/view
What is the exact version ps_shoppingcart did you use?
Maybe the issue related to this ticket: https://github.com/PrestaShop/PrestaShop/issues/11631.

Thanks to check & feedback.

**Comment by darylstone** [comment]
> Hi @darylstone, @stephR,
> 
> I tried with a very very slow connection & the products are well added to the cart.
> I used PS1.7.6.2.
> I attached a screen record
> https://drive.google.com/file/d/18bFaNwqicEHRSMQiBaUkmkwY-Ujg18tp/view
> What is the exact version ps_shoppingcart did you use?
> Maybe the issue related to this ticket: #11631.
> 
> Thanks to check & feedback.

Hi khouloudbelguith, thanks for your reply! :)

I tried it using the current version 2.0.3 of ps_shoppingcart but also using the earlier one v 2.0.2. 
I'm not sure if the issue is the same but I don't think it is. Because the issue from ticket #11631 seems to be fixed already in a current version like 1.7.6.2, isn't it? Anways, I will setup a fresh installation again and try it local instead of online. Maybe that might help tracing the issue.

Thank you!

**Comment by khouloudbelguith** [comment]
@darylstone,

> Because the issue from ticket #11631 seems to be fixed already in a current version like 1.7.6.2, isn't it?

No, it fixed in the next version PS1.7.7.0.
>Anways, I will setup a fresh installation again and try it local instead of online. Maybe that might help tracing the issue.

Thanks, waiting for your feedback.

**Comment by darylstone** [comment]
Hi @khouloudbelguith,

I see, might be related to the same issue though. I did just do a fresh installation and tried it out. 

**1. Stock Management enabled & allow ordering of out-of-stock products**
1.1. Works sometimes but not always using slow 3G network. 
1.2 Using opera GX network limit with 64-124kb/s it never works.

**2. Stock management disabled**
Same issue, doesn't work for me. 

Could you try it maybe again? Using 3G slow network it seems to work just by luck.

I did record it also.

https://filebin.net/hu3x177fozsdpc8w/20200115_154109.mp4?t=lk9iydrg

I think it is realted to javascript, if javascript loading is interrupted or not fully loaded, the add to cart doesn't work - no matter if ajax is enabled or not. Atleast that's my only explanation.

**Comment by khouloudbelguith** [comment]
@darylstone, I tried again with PS1.7.6.2 & it is ok.
I attached a new screen record
https://drive.google.com/file/d/1RNM4ZdnlkCVDqzElSP0-6qDPSqFrhK7O/view
Thanks to check & feedback.

**Comment by darylstone** [comment]
Hi @khouloudbelguith 

thank you, that's funny. :)) 
I just tried on your demo and it doesn't work for me. Curious why it doesn't work for me but works for you. :))) I'm able to reproduce that also on my laptop and smartphone. Strange.

I will do more tests and get back to you. :)

**Comment by khouloudbelguith** [comment]
@darylstone, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @darylstone,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
