### ISSUE TITLE
Missing pagination for hreflang

### ISSUE THREAD

**Issue by GuillaumeEqui-Clic** [PrestaShop/PrestaShop#17122]
When a page has pagination, the pagination in the hreflang does not appear.
No link to the current page itself is present.

Example :
https://equi-clic.com/gb/10-competition-and-performance?page=2

We have the alternate pages :
`<link rel="alternate" href="https://equi-clic.com/fr/10-performance" hreflang="fr-fr">`
`<link rel="alternate" href="https://equi-clic.com/gb/10-competition-and-performance" hreflang="en-gb">`
`<link rel="alternate" href="https://equi-clic.com/es/10-para-el-concurso" hreflang="es-es">`

We should have the alternate pages :
`<link rel="alternate" href="https://equi-clic.com/fr/10-performance?page=2" hreflang="fr-fr">`
`<link rel="alternate" href="https://equi-clic.com/gb/10-competition-and-performance?page=2" hreflang="en-gb">`
`<link rel="alternate" href="https://equi-clic.com/es/10-para-el-concurso?page=2" hreflang="es-es">`

Guideline : "Each language version must list itself as well as all other language versions.".

PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @marketiweb85,

Thanks for your report.
Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/13737?

Thanks to check & feedback.

**Comment by GuillaumeEqui-Clic** [comment]
Thanks @khouloudbelguith 

It's not the same issue. The problem is in FrontController function getAlternativeLangsUrl()

**Comment by khouloudbelguith** [comment]
@marketiweb85, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2 & branch 1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/72886086-77ac4500-3d09-11ea-9eb3-bdf00cd83a64.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Related to #13737

Thanks!

**Comment by khouloudbelguith** [comment]
@marketiweb85, thanks for your feedback.
I have the same behavior as PS1.7.6.3 & PS1.7.5.2 & branch 1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/72886086-77ac4500-3d09-11ea-9eb3-bdf00cd83a64.png)

Ping @PrestaShop/prestashop-product-team what do you think?
Related to #13737

Thanks!

**Comment by ngodefroy** [comment]
Hello @marketiweb85 @MatShir I can see the page number, however the mention "page" doesn't appears as stated in the https://github.com/PrestaShop/PrestaShop/issues/17122.
If the mention page isn't mandatory then its OK for me.
![Capture d’écran 2020-08-17 à 14 41 51](https://user-images.githubusercontent.com/69145330/90397408-14fd0b00-e098-11ea-973c-55d41eb65f93.png)

**Comment by MatShir** [comment]
@ngodefroy You can't reproduce the issue?

**Comment by ngodefroy** [comment]
@MatShir  just reproduced it.
forgive me for the last pic I updated, i Wasnt on the second page ^^
![Capture d’écran 2020-08-17 à 15 17 39](https://user-images.githubusercontent.com/69145330/90400556-f1888f00-e09c-11ea-9462-80d710d0ee23.png)
