### ISSUE TITLE
pspixel error 500

### ISSUE THREAD

**Issue by Mduclain** [PrestaShop/PrestaShop#17128]
Hi, 

presta 1.7.6.1
facebook pixel 1.1.6

When an user creates a new account on my website, he gets an error 500. 
No error when an user logs in

![image](https://user-images.githubusercontent.com/58939347/72246512-29a18e00-35f3-11ea-998f-0f3431d025b7.png)

(1/1) FatalThrowableErrorCall to a member function format() on boolean
--
in pspixel.php line 491
at Pspixel->getUserInformations()in pspixel.php line 347
at Pspixel->hookHeader(array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in Hook.php line 970
at HookCore::coreCallHook(object(Pspixel), 'hookHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in ets_hook line 499
at Ets_Hook::callHookOn(object(Pspixel), 'displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in ets_hook line 356
at Ets_Hook::exec17('displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16), null, false, true, false, null, false, array(array('file' => '/home/gmtgjkqs/shop/classes/controller/FrontController.php', 'line' => 556, 'function' => 'exec', 'class' => 'Hook', 'type' => '::')))in Hook.php line 36
at Hook::exec('displayHeader')in FrontController.php line 556
at FrontControllerCore->initContent()in FrontController.php line 37
at FrontController->initContent()in AuthController.php line 87
at AuthControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in Dispatcher.php line 36
at Dispatcher->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment]
Hi @Mduclain,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/en/contact-us?id_product=27646
Thanks!

**Comment by Mduclain** [comment]
Hi, 

pspixel is Facebook pixel ? 
![image](https://user-images.githubusercontent.com/58939347/72248382-50fa5a00-35f7-11ea-894f-4cb3cc7d0cba.png)

**Comment by khouloudbelguith** [comment]
Hi @Mduclain,

In your `Project_folder/modules/your_module/config.xml` file, you can find the `name` of the module, it the technical name & you can find the `displayName`, it the name displayed in the module manager page.
Thanks!
