### ISSUE TITLE
[BO IMPROVEMENT] Don't set UPGRADE as a main button in module list

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17137]
**Current situation**
UPGRADE action replaces CONFIGURE in module list, when the update is available.

I don't know about other merchants, but you usually go to module list to configure something. It's good to know that update is available, but maybe a better way would be to show a yellow label under module name and not replacing the button.

One accidental click can fuck up the module config or make the shop unusable, if something is not 100% compatible. Not to mention merchants who modified the modules somehow.

**My proposal**
Keep upgrade button in the dropdown and instead, show a label, that update is available.

**Comment by micka-fdz** [comment]
Very good idea! Accidental update of modules by merchants is a nightmare for us (web agencies).

**Comment by jf-viguier** [comment]
Yes, this is definitively a major issue that has to be improved.
It should be nice to allow merchant to configure a module but to disallow upgrade it.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox, 

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think about this improvement.

Thanks!

**Comment by LouiseBonnard** [comment]
@TristanLDD, @prestascott, what do you think about this suggestion?

**Comment by prestascott** [comment]
Hi @Hlavtox, 

Thank you for your feedback, we are currently on it and a label can be a workaround for this button text replacement.

Thanks!

**Comment by jherry** [comment]
Be aware that when installing a new version of a module, if there is a PHP cache (opcache), the upgrade file is not executed (/upgrade/upgrade-vx.x.x.php) and may cause damages if this treatment is important (new table in database for exemple). So the fact that the module can be upgraded must be visible. I will try to create an issue for this but I need to check if it's not already done.

**Comment by micka-fdz** [comment]
Hi @prestascott. Any news here?

**Comment by Hlavtox** [comment]
@micka-fdz @jf-viguier @prestascott 

Hi everyone, PR made https://github.com/PrestaShop/PrestaShop/pull/25314

**Comment by jf-viguier** [comment]
Thanks for your work  @Hlavtox

**Comment by prestascott** [comment]
It's good to me!
