### ISSUE TITLE
[FO IMPROVEMENT] Add 'Best selling' sort order to all product lists

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17136]
I think Prestashop's product list is missing a very usable sort order - sorting by sales.

This sale order is available on 'Best Sellers' page, but not in categories. I think it would be good if it was everywhere.

**Comment by micka-fdz** [comment]
I already had this request from some merchants. I think it could be a good improvement!

**Comment by jf-viguier** [comment]
Good idea, by the way, best Sellers page compute sales from the begining, it should be from X months only.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by marionf** [comment]
PR of @dgonzalez360: https://github.com/PrestaShop/ps_facetedsearch/pull/172

**Comment by marionf** [comment]
@jf-viguier @Hlavtox @micka-fdz 
Could you please test the PR of @dgonzalez360 and confirm if it fit with your need ?

**Comment by Hlavtox** [comment]
@marionf Sorry, I forgot to look at it. I will test the PR soon. 🌷

**Comment by sector7digital** [comment]
in 10 years we sure will have sort by sales available won't we (with the possibility to set the months responsible for calculations). or will it become a 200 Euro module like many others thanks to prestashop completely overpriced modules pricing policies which are a damn insult? I mean i just bought a module for 80 bucks which only creates a useless link. what the fuck is wrong with your module pricing policies???????????? Why can't he sell his module for the 10 bucks that it's worth? Why do you assholes force him to sell it for 70? You couldn't have acted more greedy and braindead when you put a useless fucked up care plan  on top of everything and call it included for free the first month's which it really isn't as you have raised all prices for the price of the care plan. Is this behavior even legal? Goin on not supporting you in any way anymore, not as long as you suck that big. Earn money the proper way, not by using module devs for your fucking schemes! Hilarious behavior!
And if you think you have to feel insulted, think again! Who here should really feel insulted? YES EXACTLY the module devs and then  the customers.

**Comment by Hlavtox** [comment]
@oliiix Mr, few points.
- This feature was implemented last week by me, so you can get it for absolutely for free in the default ps_facetedsearch module. You can thank my clients because they paid for the work.
- Whatever you think of Addons is not related to open source project, this a completely different team ran by the community.
- If the module author decided to sell a module that just adds a useless link for 80 bucks and you bought it, who is the idiot here? 🤣 Any I think it won't be THAT useless if you bought it no?
- Also, if you don't like the official marketplace, you can write the module yourself for completely free!!! Isn't it awesome? Or you can buy it from other authors from outside. So much freedom.

Regards

**Comment by oliiix** [comment]
the module should not only have created a useless link you arrogant ass. that's my fucking point. and the dev showed me the payment options he had available made by prestashop. And yes I'm writing them myself if i have time, how do you think i managed :'D oh a completely different team? yeah sure! you're prestashop are you not, like they are prestashop, are they not? but nothing to expect from a "company" that behaves like assholes, right? Nothing to say towards the business care plan or shit like that? OF COURSE NOT
