### ISSUE TITLE
[SF Migration] Build an example module for 1.7.7

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17138]
## Build an example module for 1.7.7

This modules must demonstrate:
- how to use the new hooks in "Edit an order" page
- how to insert a "upload image" input inside the Symfony form managing "Edit a Supplier" page

This module must promote the best practices.

**Update:**

We built 2 modules. See https://github.com/PrestaShop/PrestaShop/issues/17138#issuecomment-599570114

**Comment by jf-viguier** [comment]
yes please

**Comment by rokaszygmantas** [comment]
I'm on it :slightly_smiling_face:

**Comment by matks** [comment]
@eternoendless I need the "all example modules" repository we discussed about, to host all of our example modules 😄

**Comment by matks** [comment]
Linked to https://github.com/PrestaShop/PrestaShop/issues/17275

**Comment by tdavidsonas88** [comment]
> @eternoendless I need the "all example modules" repository we discussed about, to host all of our example modules

Yup, that would be helpful for SEO purposes and backlinking when writing documentation

**Comment by jf-viguier** [comment]
@matks any news for uploading stuff ? We need this

**Comment by matks** [comment]
> @matks any news for uploading stuff ? We need this

WIP, but dont worry it will be delivered, at max, the same day we deliver 1.7.7.0 😊

**Comment by matks** [comment]
@olecorre @jf-viguier I remember you asked for this "upload image" example 😊 

Could you tell us more specifically what you had in mind ?
To me, a "upload image" input
- allows preview of already registered image (and you can replace it)
- maybe resize the image ?

So "image upload" inputs of Product Categories page are eligible, then ?

**Comment by jf-viguier** [comment]
I don't need the resize stuff but uploading, deleting, replacing and preview.
Thanks @matks

**Comment by matks** [comment]
@jf-viguier @olecorre 2 example modules for 1.7.7.x have been delivered in repository https://github.com/PrestaShop/example-modules
- Order Page hooks module 
- Extend a Symfony Form module 2

Documentation has been written for Order Page hooks module => https://devdocs.prestashop.com/1.7/modules/sample_modules/order_view_page_new_hooks/
Documentation for Extend a Symfony Form module 2 is WIP

Feel free to try (must be installed on `1.7.7.x` shop) and tell us your feedback 😊

**Comment by jf-viguier** [comment]
Thanks
