### ISSUE TITLE
Redirection chain on Add to cart action

### ISSUE THREAD

**Issue by j0r1s** [PrestaShop/PrestaShop#17153]
**Background**
I've been preparing the migration from a Prestashop 1.6 to 1.7 for a customer of mine on an alternate staging host. Everything was working perfectly fine so we decided to transfer the website (files + database) to the main production host.

**Describe the bug**
On the new host, when a product is added to cart, I get a 302 redirection chain that ends with a TOO_MANY_REDIRECTS error in Chrome (79).
More or less the same happens in Firefox, the redirection is cached, and then I have to manually clear the cookies in order to make the site work again (same happens in Chrome).

**To Reproduce**
The site is currently in maintenance mode so it's not accessible from a common IP.
1. Go to a product page
2. Open your favourite browser's console and keep an eye on the network tab
3. Click on 'Add to cart' button
4. See redirection chain in devtools.

**Screenshots**

The redirection chain :
![image](https://user-images.githubusercontent.com/35805130/72276729-ecf48780-3630-11ea-9a3b-2da50e02495e.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.1
Host: OVH, shared
Block cart module : 2.0.3 (not sure it's related)
Cache disabled, debug mode enabled

Since it was working on the staging host, I suspect an error related to the apache configuration / htaccess.
Here is the content (generated by Prestashop) of the former :
```
# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

<IfModule mod_rewrite.c>
  <IfModule mod_env.c>
    SetEnv HTTP_MOD_REWRITE On
  </IfModule>

RewriteEngine on


#Domain: mydomain.tld
RewriteRule . - [E=REWRITEBASE:/]
RewriteRule ^api(?:/(.*))?$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^mydomain.tld$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType font/woff2 .woff2
<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
```

I've looked around github / prestashop's forum / google and found that #15973 might be related, I tried to add the `?action=show` query string parameter to the form action url but to no extent.

The theme I use is Sting but the same problem happens with the default theme.
I also tried to disable multilang since I was thinking it might be a language redirection issue, it had no effect.
I also tried to disable ssl, for the same reasons but it didn't work neither.
I have no error in the Symfony logs nor in the Apache error logs.
Apache mod_security has been disabled and OVH firewall as well.

Any help would be greatly appreciated, I can provide any further informations if needed.

**Comment by khouloudbelguith** [comment]
Hi @j0r1s,

Thanks for your report.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
>Block cart module : 2.0.3 (not sure it's related)

Is it a blockcart module or ps_shoppingcart module?
ps_shoppingcart module is compatible with PS1.7
The blockcart module is compatible with PS1.6 only, it is replaced by ps_shoppingcart.

>#15973 might be related

No, I don't think, it is related=> if the parameter `&action=show` doesn't exist in your URL => redirection to the home page => it is not your case.

Thanks!

**Comment by j0r1s** [comment]
hi @khouloudbelguith !

Thanks for your attention.

>Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).

Done, still getting the redirection chain.

>Is it a blockcart module or ps_shoppingcart module?

My bad, you're right, it's `ps_shoppingcart` module I'm using, but I don't think it's related either since the same bug happens when I disable the `ps_shoppingcart` module via the back-office (even after running `rm -rf var/cache/*`).

Let me know if I can do anything else to help further troubleshooting.

**Comment by khouloudbelguith** [comment]
@j0r1s, You need to enable debug mode in your store and debug request which is sent for product add to cart in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. add the product to cart
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by j0r1s** [comment]
@khouloudbelguith, I already did so, debug mode is enabled but the only response I get is a 302 redirection, there are no error nor content :

![image](https://user-images.githubusercontent.com/35805130/72527036-1e0acd00-3868-11ea-8bb6-627238e0a68a.png)
![image](https://user-images.githubusercontent.com/35805130/72527068-311d9d00-3868-11ea-8910-02a24e46b769.png)
![image](https://user-images.githubusercontent.com/35805130/72527088-3975d800-3868-11ea-9bdc-b91aa51b8984.png)

And then the redirection chain happens until I get a `TOO_MANY_REDIRECTS` error :
![image](https://user-images.githubusercontent.com/35805130/72527159-69bd7680-3868-11ea-96ca-6f89bfc5aacf.png)

**Comment by khouloudbelguith** [comment]
@j0r1s, Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by j0r1s** [comment]
Done !

I've noticed that everytime I change Friendly Urls configuration in back-office I get an Error 500 (that is not caught by symfony nor logged in OVH error logs).

After reloading the page I still get the flash message that the configuration has been updated and I checked that the `.htaccess` file had been regenerated :
`cat .htaccess`
```
# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>

RewriteEngine on


#Domain: maccarton.fr
RewriteRule . - [E=REWRITEBASE:/]
RewriteRule ^api(?:/(.*))?$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType font/woff2 .woff2
<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
```

Cleared cache and retried, same redirection chain happened.

Thanks for helping me, I already tried so much debug that I feel kinda helpless.

**Comment by khouloudbelguith** [comment]
> I change Friendly Urls configuration in back-office I get an Error 500

What is the exact error?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by j0r1s** [comment]
>What is the exact error?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

As stated before, I have nothing in OVH (host) error logs.
No error logs neither in Prestashop back-office, the error 500 is not caught by Prestashop framework, it's a generic error 500 from Chrome :
![image](https://user-images.githubusercontent.com/35805130/72547033-1fe68780-388c-11ea-8cde-38db121102b9.png)

After further troubleshooting, the error 500 happens only when disabling friendly urls, if it can help.

Actually I don't know, it's not happening anymore, I've tried to switch the friendly URLs option a few times with or without manually clearing the cache everytime and the error doesn't show.

It's also worth noting that adding a product to cart without friendly URLs enabled  doesn't work neither, same redirection chain happens and still nothing in any log.

Are there some logs I'm missing ? You're talking about debug mode report ? Should there be something written anywhere else than in `var/logs/dev.log` ?

For the record here is a sample from my `defines.inc.php` :
```php
define('_PS_MODE_DEV_', true);
...
define('_PS_DEBUG_PROFILING_', false);
```

I wish I could use `define('_PS_DEBUG_PROFILING_', true);` but since it's an ajax call I cannot get the rendered html response, is there any way to write this output to a file or something else ?

**Comment by musicpanda** [comment]
I wrote some time ago a manual how to debug Ajax:
https://www.prestashop.com/forums/topic/994407-how-to-debug-ajax-errors-jqxhr-unexpected-token-technical-error/

**Comment by j0r1s** [comment]
Thanks @musicpanda !

Maybe someone with more Prestashop knowledge could help me debug the headers since I'm getting no Response since it's a 302 :

Response headers :
```
cache-control: no-store, no-cache, must-revalidate
cache-control: post-check=0, pre-check=0
content-type: text/html; charset=utf-8
date: Thu, 16 Jan 2020 17:38:54 GMT
expires: Mon, 26 Jul 1997 05:00:00 GMT
last-modified: Thu, 16 Jan 2020 17:38:54 GMT
location: ../
pragma: no-cache
server: Apache
set-cookie: PrestaShop-958968da9e44871bcb99b2bfd90ddc2c=def502004fffc45f0aabd7bb6b03c7df94e3ab2c70ab2dd6afb626eb949c6311b1a7f357774f3739c4df048da9e51af1d10662bf8cd901917e1c19ba7d59eae4e2514a3c0d6967456736a0f915b0ac79fe8be04476fa87ee7d0817f5105e304e75a8c094dfb297f82bf668a609e3572e59a1661d3166eb676c1d007783a323aee688ee85743ccec069a5392cd07c2caac4382c9d9d6679fe5af1c4319972308220a2ff7b214a4d166eee4b9bda4f063a30efde45dee4c1388cdd6aeacb57ea22ff229d15d7181f7f788ebf641b6f37e98d5f01d4c5ea428dc585004dfab65a839a19f6f40081bf5b922790f9dae6668b8ed2a068a72581dd5164fc5221cabd84cb44ade817bf3628ae15dc7193e6dde2da21eeb09e0e975b580e1308adf5e0e0e84b02a9fe3013709c5ad6a913d38949f885773abe1452092325b2c9206e1c5d4a022a9aeab1e7; expires=Wed, 05-Feb-2020 17:38:54 GMT; Max-Age=1728000; path=/; domain=maccarton.fr; secure; HttpOnly
set-cookie: SERVERID585=202014|XiCfs|XiCer; path=/
status: 302
x-iplb-instance: 17197
x-powered-by: PHP/7.1
x-robots-tag: noindex, nofollow
```

Request headers :
```
:authority: maccarton.fr
:method: POST
:path: /index.php?controller=cart
:scheme: https
accept: application/json, text/javascript, */*; q=0.01
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7
content-length: 96
content-type: application/x-www-form-urlencoded; charset=UTF-8
cookie: PHPSESSID=7629d43a18c865d67793a89e1b3eb99a; view=grid; PrestaShop-958968da9e44871bcb99b2bfd90ddc2c=def50200ec5eb26572fb08704ab73be6bd93b2ae6ace1de2168622bffc392f97b6cd75d8b65841764d3d90da4bb37571a1ae4cf73e0e6b9e9813ce4578958dbe821e32504f699c6a80781c53447bef25c6f76dd247a09189a9db4c757bceb5708ae9b1da97dcbfd4e6bb33883812a5771ec54546ce862f29b52048f8e6707d319e0a5b1331536f398cf9f37aab3298b304c15d7535dc783f4f2d50aa298e216289b8415b64325e14236ff60a7c1924485a0dbbd793b36f0482e0a3ed2e28f040346e05a1f48826c64be20d2305affc957ef10ed70c07935d0adbad0e3cea515020977fef5d7dde6c3f35aa091e840369416363820cc1f0e2595097d5514c8d9c2fdf5f3c4c494614d58c0b13e0e1e2cbdb0e4365d05f6cc548dc6deb75a8d64fe51efee252c62f441fe8f1c9edb7780e36bb41c731c869e98d76f2; SERVERID585=202014|XiCfq|XiCer
origin: https://maccarton.fr
referer: https://maccarton.fr/index.php?id_product=8&rewrite=maquette-moulin-a-vent&controller=product&id_lang=2
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
x-requested-with: XMLHttpRequest
```

Query string parameters:
```
controller: cart
```

Form data :
```
token: d52870175306f6855736912fa7a43caf
id_product: 8
id_customization: 0
qty: 5
add: 1
action: update
```

We can see the 'location: ../` from the response headers.

I'm not sure the subsequent headers from the redirects are relevant, I can provide if needed.

**Comment by khouloudbelguith** [comment]
@j0r1s, The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
>Are there some logs I'm missing ? You're talking about debug mode report? Should there be something written anywhere else than in var/logs/dev.log

Yes, you can find some log files in the path `/var/logs`

This issue could be due to 3rd party modules. if you are using 3rd party modules, try disabling them to test it.

Also, in the BO => Shop Parameters => SEO & URLs page => Set up URLs section, try with combination of "Disable Apache's MultiViews option" on/off and "Disable Apache's mod_security module" on/off

Thanks to check & feedback.

**Comment by j0r1s** [comment]
>Yes, you can find some log files in the path /var/logs


```sh
~/var/logs $ ls -la
total 40487
drwx---r-x+ 2 *** users        4 janv. 17 10:28 .
drwx---r-x+ 5 *** users        8 janv.  9 00:00 ..
-rw----r--+ 1 *** users 41414920 janv. 16 17:52 dev.log
-rw----r--+ 1 *** users     6203 janv.  9 06:00 prod.log
```
And nothing after the 13th of January when I (the website have been in debug mode for more than one week):
```sh
~/var/logs $ cat dev.log | grep ERROR
```

> This issue could be due to 3rd party modules. if you are using 3rd party modules, try disabling them to test it.
I've disabled all non Prestashop modules from the admin, manually cleared cache and retried, I got an error 500 when adding a product to cart :
![image](https://user-images.githubusercontent.com/35805130/72606228-7f8d7300-391e-11ea-85d7-7d87cb448779.png)

It's not the first time I get this one.

It's in `override/controllers/front/CartController.php:52`, it's been installed by a module, [Sell By X Units](https://addons.prestashop.com/en/cross-selling-product-bundles/25969-sell-by-x-units.html).

I ran :
```sh
mv override/controllers/front/CartController.php override/controllers/front/CartController.php.bak
rm -rf var/cache/dev
```

And then the error 500 disappears, but the 302 redirection chain comes back.

> Also, in the BO => Shop Parameters => SEO & URLs page => Set up URLs section, try with combination of "Disable Apache's MultiViews option" on/off and "Disable Apache's mod_security module" on/off

I've tried all combinations possible and manually cleared cache between every tentative.

When both options are disabled the site is not working, I get the 302 redirection chain even on the home page :

![image](https://user-images.githubusercontent.com/35805130/72609952-7c968080-3926-11ea-93bc-a102eba65409.png)

Here is the corresponding `.htaccess` :
```
# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>


# Disable Multiviews
Options -Multiviews

RewriteEngine on


#Domain: maccarton.fr
RewriteRule . - [E=REWRITEBASE:/]
RewriteRule ^api(?:/(.*))?$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^maccarton.fr$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType font/woff2 .woff2
<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
```

Actually I can't get the website to work anymore, the 302 redirection happens even on the homepage, on any browser, no matter what settings I use for Multviews / mod_security.

At this point I have lost so much time, I think I will try a fresh install from the host control panel and check if it's working.

**Comment by musicpanda** [comment]
You shouldn't remove an override of an active module. That is bound to give problems. Instead you should disable the module.

Did you try disabling pretty urls and deleting .htaccess?

Your initial image showed /en/ directories involved in the redirect. That raises the question how many language you have installed in the old and new configurations

**Comment by j0r1s** [comment]
> You shouldn't remove an override of an active module. That is bound to give problems. Instead you should disable the module.

The module was already disabled in back-office.

> Did you try disabling pretty urls and deleting .htaccess?

Yes many different times

> Your initial image showed /en/ directories involved in the redirect. That raises the question how many language you have installed in the old and new configurations

Two languages on both, it's always been like that.

**Comment by musicpanda** [comment]
"The module was already disabled in back-office."
Try uninstalling it. Sometimes modules stay partially active when just disabled.

**Comment by j0r1s** [comment]
>Try uninstalling it. Sometimes modules stay partially active when just disabled.

I've renamed the override to its original name but now it's working for some reason. I still get the redirection chain on the add to cart action.

(I'm constantly manually clearing cache)

**Comment by musicpanda** [comment]
Did you also delete class_index.php when you emptied the cache? Without doing that Prestashop will still try to read the override even if it isn't there.

**Comment by j0r1s** [comment]
```
find . -type f -name "class_index.php"
./var/cache/dev/class_index.php
```

I always `rm -rf var/cache/dev` but the error 500 isn't happening, Prestashop must have been reading the override when it shouldn't have but I don't think it's related to the initial problem.

**Comment by khouloudbelguith** [comment]
@j0r1s, 
>It's in override/controllers/front/CartController.php:52, it's been installed by a module, Sell By X Units.

As it's not the a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.

Could you please provide me a screenshot from your Schema of URLs section
![image](https://user-images.githubusercontent.com/16067358/72615521-34cb2580-3935-11ea-96d4-9540149d76e5.png)

Thanks!

**Comment by j0r1s** [comment]
![image](https://user-images.githubusercontent.com/35805130/72616723-d05d9580-3937-11ea-97a4-cfb35e44a950.png)

I had an error on this form initially, there was 'disable-this-rule-hash' in faceted_filter field, I've instead put the required parameters in the field to validate the form (and enable / disable friendly urls). But again, it's working on another host.

**Comment by khouloudbelguith** [comment]
@j0r1s, could you please try to change the "Route to category which has the "selected_filter" attribute for the "Layered Navigation" (blocklayered) module" from `{id}-{selected_filters}-{rewrite}` to
`{id}-{rewrite}{/:selected_filters}`, clear cache, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/72912358-cf63a400-3d3b-11ea-9b6c-2ffff40fdaad.png)

Thanks!

**Comment by j0r1s** [comment]
Hello @khouloudbelguith !

Sorry for the late feedback. I've tried to change the route, cleared cache, but same redirection chain happens.

**Comment by khouloudbelguith** [comment]
@j0r1s, the override is removed or not?
Thanks!

**Comment by j0r1s** [comment]
I uninstalled the module, and same problem happens.

**Comment by khouloudbelguith** [comment]
@j0r1s, In your BO => Modules => Module Manager page => search for the `ps_shoppingcart` module, click on the configure & check if the `Ajax cart` option is enabled or disabled?
![image](https://user-images.githubusercontent.com/16067358/73372416-7655bc00-42b7-11ea-9935-faf9f599d4a3.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @j0r1s,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
