### ISSUE TITLE
[FO IMPROVEMENT] Search within CMS pages

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17166]
Hi,
Search module does not searching information within CMS pages for useful informations.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Is it the ps_searchbar module?
https://github.com/PrestaShop/ps_searchbar
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
