### ISSUE TITLE
Gsitemap prestashop module multilingual issue

### ISSUE THREAD

**Issue by noione** [PrestaShop/PrestaShop#17173]
**Describe the bug**
Sitemap is generated only for the default language, the other languages are not generated 

**To Reproduce**
1. Go to the module gsitemap
2. Click on generate sitemap

The sitemap is generated only for the default language not for the others

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment]
Hi @noione,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2 & gsitemap module v4.1.0.
I attached a screen record
https://drive.google.com/file/d/1-0bX9-ORRCkOhW8sTvNJrEbdm8Dx8qTG/view
Thanks to check & feedback.

**Comment by noione** [comment]
Hello @khouloudbelguith,
Thank you for your feedback, i've tried to check my logs and i see this error : 
[Wed Jan 29 11:49:36.007284 2020] [php7:notice] [pid 20243] [client XXXXXXXX:55697] PHP Notice:  Undefined index: fr in /var/cache/prod/smarty/compile/99/79/7f/99797fae64f9edf75220d0ffaeba1ef1bc500e95_0.file.modal_translation.tpl.php on line 39, referer: /index.php?controller=AdminModules&configure=gsitemap&token=XXXXXXXXX

I didn't make any changes on the modal_translation.tpl
Do you have any idea please ?
Thank you

**Comment by khouloudbelguith** [comment]
Hi @noione,

This is a cache issue.
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by noione** [comment]
Already done and still having the same error on my logs
i've also tried to reinstall the gsite module but in vain

**Comment by khouloudbelguith** [comment]
@noione, thanks to provide me the debug mode report & the logs under `/var/logs/` folder.

Thanks!

**Comment by noione** [comment]
I have no error when i enable the debug mode, but on the logs file i have this warning in multiple time : 
[2020-01-29 15:05:53] translation.WARNING: Translation not found. {"id":"Install","domain":"AdminActions","locale":"fr-FR"} []
Is it about the gsite module ? 
Thank you

**Comment by khouloudbelguith** [comment]
@noione, thanks to navigate to your Back office => International => Translations => Update all your languages.
![image](https://user-images.githubusercontent.com/16067358/73364670-3d174f00-42ab-11ea-8ea8-47a092d6dbd8.png)

Thanks!

**Comment by noione** [comment]
Thank you, i've the update of languages but i still can't have the multilingue on my gsite
I have this error on the dev debug file : 
[2020-01-29 15:51:00] translation.WARNING: Translation not found. {"id":"Enable mobile","domain":"AdminActions","locale":"fr-FR"} []
and the same error on the logs file
PHP Notice:  Undefined index: it in /var/cache/prod/smarty/compile/99/79/7f/99797fae64f9edf75220d0ffaeba1ef1bc500e95_0.file.modal_translation.tpl.php on line 39, referer: admin/index.php?controller=AdminModules&configure=gsitemap&token=60e309d5478ce99eefca9ee92b321ef6

**Comment by khouloudbelguith** [comment]
@noione, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Try to navigate to the BO => International => Localization => Import the France pack.
![image](https://user-images.githubusercontent.com/16067358/73367993-8d44e000-42b0-11ea-8b58-c62f1272bba3.png)

Thanks!

**Comment by noione** [comment]
@khouloudbelguith thank you, i've done all steps but still having only one language when i generate the sitemap
In fact my default language of the store is Frensh
Thank you

**Comment by khouloudbelguith** [comment]
@noione,

>In fact my default language of the store is Frensh

What are the exact languages enabled in your shop?
Did you use the multistore context?
Are you sign in with a super admin employee?

Thanks!

**Comment by noione** [comment]
The languages installed and enabled on the store are : FR - EN - DE - ES - IT 
I don't use the multistore context, only one store with multiple languages 
Yes i have only one employee and it's a super admin

**Comment by khouloudbelguith** [comment]
@noione, those languages: EN - DE - ES - IT are added manually from the BO => International => Localization => Languages page?
![image](https://user-images.githubusercontent.com/16067358/73446982-12d29980-435e-11ea-883b-f7e47ff70b87.png)

Thanks!

**Comment by noione** [comment]
@khouloudbelguith Yes 
![Capture d’écran 2020-01-30 à 12 51 52](https://user-images.githubusercontent.com/8407882/73448012-43b3ce00-4360-11ea-95d2-d794462a7f98.png)

**Comment by khouloudbelguith** [comment]
@noione, it could be a problem during the creation.
Try to delete them & now add those new languages from the Back office => International => Translations => Add or Update all your languages section.

![image](https://user-images.githubusercontent.com/16067358/73451292-93e25e80-4367-11ea-9d27-1b8d7912ce8a.png)

Thanks!

**Comment by noione** [comment]
@khouloudbelguith  I can't delete them i have more than 26000 product with it's translation 
I've already tried an update but still have the issue, please do you have any suggestion ?
Thank you

**Comment by khouloudbelguith** [comment]
@noione, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by noione** [comment]
@khouloudbelguith i've found the solution if anyone got the same issue, the problem was on the gsitemap module.
On line 263 in gsitemap.php the limit of the function addLinkToSitemap was 25000 i've increase it to the total of my products of my store and it works.
Thank you

**Comment by khouloudbelguith** [comment]
@noione, thanks for your feedback.
This issue is fixed with this PR: https://github.com/PrestaShop/gsitemap/pull/127

Thanks!
