### ISSUE TITLE
Password Recovery Front Office- Not Working several shops 1.7.5.2 and 1.7.6.1

### ISSUE THREAD

**Issue by ruifox** [PrestaShop/PrestaShop#17170]
**Describe the bug**
When we are trying to recover password, the system sends the link to create the new password, but after setting the new password we submit, and gives an error notification
"We cannot regenerate your password with the data you've submitted"

**Extra info**
We can receive e-mails without issues
We can change the clients password on the back-office
Its default Theme and there aren't changes on the controllers/classes.

**To Reproduce**
1. Go to 'Customer account / login.'
2. Click on 'Recover Password' and put the client e-mail to recover password
3. Check Mail  'click the link on the recover email'
4. Put the new passwords Submit
5. See error/notification

**Additional information**
PrestaShop version: Several shops 1.7.5.2 and 1.7.6.1 
PHP version: 5.6.40 / 7.2.26 / 7.3.13

**Comment by khouloudbelguith** [comment]
Hi @ruifox,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
I did not manage to reproduce the issue with PS1.7.6.2
I attached a screen record
https://drive.google.com/file/d/1JT-I-HliN7zHZJTb0nLzHZ0zHAMQ08-k/view
THanks to check & feedback.

**Comment by ruifox** [comment]
Hi @khouloudbelguith 

Thanks for the info.

Even so I changed the PHP, and I tried to update one of the shops to 1.7.6.2, after updating, it still didn't work, gave the same issue.

NOT WORKING | CLIENT 1 | CLIENT SERVER | 1.7.5.2  | 5.6.40 | 5.6.45
WORKING         | CLIENT 2 | SERVER 1           | 1.7.5.1  | 7.2.26 | 5.5.64
NOT WORKING | CLIENT 3 |SERVER 1            | 1.7.6.1  | 7.2.26 | 5.5.64
WORKING         | CLIENT 4 | CLIENT SERVER  | 1.7.5.2  | 7.2.26 | 10.2.30
NOT WORKING | CLIENT 5 | SERVER 3           | 1.7.5.2  | 7.2.26 | 5.5.64('https://delipro.eu/') (updated)(rollbacked after)
WORKING         | CLIENT 6 | SERVER 1           | 1.7.6.0  | 7.3.13 | 5.5.64
WORKING         | CLIENT 7 | SERVER 3           | 1.6.1.20| 7.3.13 | 5.5.64

On all this shops I didn't change controllers / classes only applied modules and changed visuals.

I can't figure the problem source. Because the issue it's only on the new password updating.

Any ideas into where I should look into?

**Comment by khouloudbelguith** [comment]
@ruifox, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ruifox** [comment]
@khouloudbelguith,

One of the shops has this info (if I could find the problem on this one, probably I can fix the others):

**Informação do servidor** Linux #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
**Versão do software do servidor**: Apache
**Versão do PHP**: 7.2.26
**Limite de memória:** 128M
**Versão do MySQL:** 5.5.64-MariaDB
**Versão do PrestaShop**: 1.7.5.2
**URL da loja:** http://delipro.eu/
**Tema gráfico utilizado neste momento:** classic

**Video** : "https://drive.google.com/open?id=1HY4L2b9pdw2WUrp4PUxZ5Omn7dnF2sgn"

Browser / tested on several browsers and several PC

There is no error on error_log.
There was no error on javascript console.log related with this.

**Only information that happens on LOGs is : Apache SSL/TLS access**

2020-01-16 12:29:25 | Access | 148.63.2.116 | 200 | GET / HTTP/1.0 |   |   | 15.0 K | Apache SSL/TLS access
2020-01-16 12:29:28 | Access | 148.63.2.116 | 302 | GET /a-minha-conta HTTP/1.0 |   |   | 389 | Apache SSL/TLS access
2020-01-16 12:29:28 | Access | 148.63.2.116 | 200 | GET /inicio-de-sessao?back=my-account HTTP/1.0 |   |   | 10.8 K | Apache SSL/TLS access
2020-01-16 12:29:31 | Access | 148.63.2.116 | 200 | GET /recuperar-palavra-passe HTTP/1.0 |   |   | 10.6 K | Apache SSL/TLS access
2020-01-16 12:29:33 | Access | 148.63.2.116 | 200 | POST /recuperar-palavra-passe HTTP/1.0 |   |   | 10.5 K | Apache SSL/TLS access
2020-01-16 12:29:40 | Access | 148.63.2.116 | 200 | GET /recuperar-palavra-passe?token=1248ba72964c19fd2e5bbde8a5be3eb2&id_customer=4&reset_token=eb7d3745af4808997107db026e987c79b1611902 HTTP/1.0 |   |   | 10.7 K | Apache SSL/TLS access
2020-01-16 12:29:50 | Access | 148.63.2.116 | 200 | POST /recuperar-palavra-passe HTTP/1.0 |   |   | 10.8 K | Apache SSL/TLS access

I tried updating this shop to latest prestashop version, after that, it breaks the theme, even so after trying again the steps to recover password, it gives the same error. 

Any ideas where to look at?

**Comment by khouloudbelguith** [comment]
Hi @ruifox,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
