### ISSUE TITLE
Facing [PrestaShopDatabaseException] Issue

### ISSUE THREAD

**Issue by selfcart** [PrestaShop/PrestaShop#17176]
HI,

I am facing [PrestaShopDatabaseException] issue I dont know how to resolve it. Please help me out in this. I am attaching the screenshot too.  

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2
Debug mode : ON
Shop URL : http://www.selfcart.co
![Opera Snapshot_2020-01-15_154200_www selfcart co](https://user-images.githubusercontent.com/59916083/72426726-4afba900-37b0-11ea-8824-ea6f40e039fc.png)

**Comment by khouloudbelguith** [comment]
Hi @selfcart,

What is the exact version of the ps_facetedsearch module did you use?
Is it a fresh install PS1.7.6.2 or an upgrade from a previous version?

THanks!

**Comment by selfcart** [comment]
It is a fresh install

**Comment by khouloudbelguith** [comment]
@selfcart, what is the exact version of the `ps_facetedsearch` module did you use?

Thanks!

**Comment by selfcart** [comment]
I don't know which module is this and how to get details about it. I am not a developer.
may its Faceted search Version 2.1.2

**Comment by selfcart** [comment]
Faceted search Version 2.1.2

**Comment by selfcart** [comment]
I have updated Faceted search Module and the issue is resolved but I got this message (below mentioned ) please check and tell me is it important to make cron job as I don't know how to make it

You can set a cron job that will rebuild price index using the following URL:
http://www.selfcart.co/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=84e668c78e

You can set a cron job that will rebuild attribute index using the following URL:
http://www.selfcart.co/modules/ps_facetedsearch/ps_facetedsearch-attribute-indexer.php?token=84e668c78e
A nightly rebuild is recommended.

**Comment by khouloudbelguith** [comment]
@selfcart, thanks for your feedback.
Yes, it is the faceted search module, it should be updated.
About this
![image](https://user-images.githubusercontent.com/16067358/72436720-69a67380-37a1-11ea-9ce7-547a7537176b.png)

It is just alert information if you want to use cron.
Since it is fixed, I will close the issue, feel free to open a new one when needed.

THanks!

**Comment by selfcart** [comment]
Thanks
