### ISSUE TITLE
Search results issues

### ISSUE THREAD

**Issue by fullhugo** [PrestaShop/PrestaShop#17178]
I type the full name exactly as in the store, but the results are a lot of products with no relation, and the good one even doesn't appear on the first results.

**Comment by khouloudbelguith** [comment]
Hi @CrAzYk69,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14350
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #14350
