### ISSUE TITLE
Token invalid when trying to edit a translation

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17188]
**Describe the bug**
Token invalid when trying to edit a translation

**To Reproduce**
1. Go to BO > international > translations
2. Select a translation type and a language (no matter which one)
3. Click on edit
4. See the page invalid token

**Screenshots**
![capture d'écran_2274](https://user-images.githubusercontent.com/13449658/72447506-bb58f900-37b5-11ea-97e5-cff654d32588.png)

**Additional information**
PrestaShop version: 1.7.7.x, develop
PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #17482
