### ISSUE TITLE
Unknown column id_log in ps_currency

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#17185]
During update from 1.7.5.0 to 1.7.6.2 in multiple enviroments I always end up with the following error when trying access BO > currencies.

Uncaught Exception: An exception occurred while executing 'SELECT c.`id_currency`, c.`iso_code`, cs.`conversion_rate`, c.`active`, cl.`name`, cl.`symbol` FROM ps_currency c INNER JOIN ps_currency_shop cs ON c.`id_currency` = cs.`id_currency` INNER JOIN ps_currency_lang cl ON c.`id_currency` = cl.`id_currency` WHERE (cs.`id_shop` IN (?, ?, ?, ?)) AND (cl.`id_lang` = ?) AND (c.`deleted` = 0) GROUP BY c.`id_currency` ORDER BY id_log desc LIMIT 10 OFFSET 0' with params [4, 1, 3, 2, 1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_log' in 'order clause'

There is not id_log column and I do not see it in the sql structure.  Problem replicated on multiple enviroments. Both single site and multisite setups. Disabling overrides and non-native modules does not help.

**Comment by khouloudbelguith** [comment]
Hi @krasnycz,

Thanks for your report.
What is the exact version of the 1-click upgrade did you use?
Have you any errors during the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by krasnycz** [comment]
1-Click v4.10.1. I uninstalled and removed the module. Did clean install of the module.

Log attached.

[log.txt](https://github.com/PrestaShop/PrestaShop/files/4065392/log.txt)

**Comment by khouloudbelguith** [comment]
> Both single site and multisite setups. Disabling overrides and non-native modules does not help.

The options do not work in the PS1.7.6
![image](https://user-images.githubusercontent.com/16067358/72447578-e3485c80-37b5-11ea-90b5-37fe4a22a963.png)
as reported here:
https://github.com/PrestaShop/PrestaShop/issues/14596
https://github.com/PrestaShop/PrestaShop/issues/9965

About your issue, could you please provide me a screenshot from your table ps_currency & the structure of this table.

Thanks!

**Comment by krasnycz** [comment]
![image](https://user-images.githubusercontent.com/15078106/72452069-35d94700-37bd-11ea-9aaf-b46501efabfd.png)

![image](https://user-images.githubusercontent.com/15078106/72452096-47baea00-37bd-11ea-8fc8-97354f81bb7e.png)

**Comment by khouloudbelguith** [comment]
@krasnycz, thanks for your feedback.
About the last currency `CZK` which have id_currency=4, did  you delete this currency before or after the upgrade?

![image](https://user-images.githubusercontent.com/16067358/72509888-c01abd00-3848-11ea-9030-e451bf03d8f9.png)
Could you please try to re-import the Czech pack with selecting the currency symbol, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/72510553-ee4ccc80-3849-11ea-95ca-27531d67cbd9.png)

Thanks!

**Comment by krasnycz** [comment]
Well this is old PS install and I really do not have idea why this currency was deleted.

I tried to import CZK as you requested and it makes no difference.

This is multistore install with multiple domains. 1 language a currency per domain allowed. Only primary domain with CZK currency is showing currency symbol per price. Other multistore domains does not show currency (EUR, PLN). It only shows price and info about taxes.

**Comment by khouloudbelguith** [comment]
@krasnycz, could you please confirm these stesp:
1. Install PS1.7.5.0 with Czech pack
2. Enable multistore
3. One language a currency per domain allowed
3.1 CZK currency & czech laguage for the first shop
3.2 Euro currency & English language for the second shop
4. You have some orders in all shops
5. Make an upgrade to PS1.7.6.2 using the 1-click upgrade v4.10.1.
6. Check the currency page

Thanks!

**Comment by krasnycz** [comment]
Well it works fine. The problem is if you have delted language in the database! Can I simply remove deleted language from the database?

**Comment by khouloudbelguith** [comment]
@krasnycz, no, let's be safe.
But this issue will be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16287 as reported here: https://github.com/PrestaShop/PrestaShop/issues/15934
Since, it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks!
