### ISSUE TITLE
Undefined method when trying to add a language or a pack

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17189]
**Describe the bug**

**To Reproduce**
1. Go to BO > International > Translations
2. Select a language to add
3. Click on "Add or edit a language"

1. Go to BO > International > Localisation
2. Select a localization pack
3. Click on "Import"

However, the language & the pack is well imported

**Screenshots**
![capture d'écran_2276](https://user-images.githubusercontent.com/13449658/72450133-20165280-37ba-11ea-8142-0876d41791c1.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: 7.3

**Comment by PierreRambaud** [comment]
![image](https://user-images.githubusercontent.com/1462701/72451226-e6dee200-37bb-11ea-9e6d-baa8cba6d10e.png)
Do you run `composer install` after switching branch? :)

**Comment by marionf** [comment]
Indeed, I forgot that :sweat_smile: 
Thx !
