### ISSUE TITLE
Empty columns on orders tab when creating an order

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17197]
**Describe the bug**
Columns "products" and "state" are empty on orders tab when creating an order

**To Reproduce**
1. Go to BO > Orders > Add a new order
2. Select a customer with existing orders (pub@prestashop.com)
3. Click on "orders" tab
4. See "products" and "state" columns are empty

**Screenshots**
![capture d'écran_2282](https://user-images.githubusercontent.com/13449658/72508870-be4ffa00-3846-11ea-92ba-f32ae321884c.png)

![capture d'écran_2281](https://user-images.githubusercontent.com/13449658/72508879-c0b25400-3846-11ea-8bad-2cf148f3d5d1.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17448
