### ISSUE TITLE
Change JQuery targeting of add-to-cart form by native targeting

### ISSUE THREAD

**Issue by Fabuloops** [PrestaShop/PrestaShop#17194]
**Is your feature request related to a problem? Please describe.**

I would like to put the button "add-to-cart" outside of the form. The form's submitting still work's if you add "form" attribute in the button element... but the JS function "add-to-cart" prevents me from doing it

**Describe the solution you'd like**

The solution is to change this line 
```let $form = $(event.target).closest('form');```
By this line
```let $form = $(event.target.form);```

The form's submitting still work's whithout the "form" attribute in the button element if you keep the button inside the form element.

https://github.com/PrestaShop/PrestaShop/blob/675626f689becd95c9bf3161e368f74dcfbf11c0/themes/_core/js/cart.js#L85

**Comment by khouloudbelguith** [comment]
Hi @Fabuloops,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi,
Buttons don't have `form` attribute. It should be use with the `data` (`data-form` maybe).

**Comment by Fabuloops** [comment]
Hi,

You don't need to put a `form `attribute on your button to have this attribute set in native javascript  element. This attribute always target the form if the button is inside the form. But if the button is outside, you can target with a form attribute on the button.

https://codepen.io/fabuloops/pen/VwYGXEp

https://www.w3schools.com/tags/att_form.asp

With this feature we will be able to add the `add-to-cart` button where we want.

**Comment by PierreRambaud** [comment]
Oh, never used this form attribute :open_mouth: 
So yes, we can change the button behavior :+1:

**Comment by Fabuloops** [comment]
thank you, it's will be very useful =)
