### ISSUE TITLE
Wrong sort price and/or product limit/offset on listing page

### ISSUE THREAD

**Issue by soulardromain** [PrestaShop/PrestaShop#17212]
**Describe the bug**
On category page (without ps_facetedsearch), search page, manufacturer page, supplier page, new products page, prices drop page:
When sort by low price, a product of second page (without its reduction) should be on the first page (with its reduction)
>Edit by Khouloud

Steps to reproduce the issue:
1. Disable ps_facetedsearch module
2. Edit the Product "Hummingbird printed sweater" => specific price = 50%
![image](https://user-images.githubusercontent.com/16067358/72607198-76050a80-3920-11ea-9271-442c720d4bed.png)

3. Go to the FO => Home page
4. sort by price from low to high 
5. Go to the next page
6. See error

https://drive.google.com/file/d/1uVy8vx_z1HrEqELEBx-GMKy3odytXClU/view
**To Reproduce**
1. Add a specific price on a product.
2. Sort any listing page except bestsellers page by price.
3. Use pagination.
4. See error: wrong order

**Comment by khouloudbelguith** [comment]
Hi @soulardromain,

I did not manage to reproduce the issue with PS1.7.6.2.
The ps_facetedsearch is disabled
I attached a screen record
https://drive.google.com/file/d/1lQc-9K7AMO6qkz0jOUTk-mkI75REa_Dy/view
Thanks to check & feedback.

**Comment by soulardromain** [comment]
Hi,

In your video, the bug is present:
Just before you go to second page, see price of last product ($22.68).
On the second page, the price of the first product is $21.54

**Comment by khouloudbelguith** [comment]
@soulardromain, sorry, you are right.
Yes, I have the same issue with PS1.7.5.2 & PS1.7.6.2 but this issue is fixed using the faceted search module as described here: https://github.com/PrestaShop/PrestaShop/issues/10010#issuecomment-467024493

Thanks to check & feedback.

**Comment by soulardromain** [comment]
The faceted search is only on category page but this bug is also present in search page, manufacturer page, supplier page, new products page, prices drop page.
And maybe some people don't use the faceted search on category page.

**Comment by khouloudbelguith** [comment]
@soulardromain, thanks for your feedback.
Steps to reproduce the issue:
1. Disable ps_facetedsearch module
2. Edit the Product "Hummingbird printed sweater" => specific price = 50%
![image](https://user-images.githubusercontent.com/16067358/72607184-6d143900-3920-11ea-8e99-ca748f24d879.png)

3. Go to the FO => Home page
4. sort by price from low to high 
5. Go to the next page
6. See error

https://drive.google.com/file/d/1uVy8vx_z1HrEqELEBx-GMKy3odytXClU/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by soulardromain** [comment]
I have created a pull request : #16698

**Comment by colinegin** [comment]
@MatShir @marionf wdyt of this PR ? Should we accept it before reworking the page or after ?

**Comment by marionf** [comment]
@colinegin the issue is in FO, so not related to the migration of BO product page

**Comment by colinegin** [comment]
Sorry i misread the issue :)
I put it in the 178 kanban then !
Thanks
