### ISSUE TITLE
Add order_confirmation/Initial-order-status to the list over "statuses" to be able to resend order_conf email

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#17224]
The "initial" order status, the one using email template `order_conf` should be at the top of the status list, with a button to resend order_conf email.
![Screenshot 2020-01-17 13 43 09](https://user-images.githubusercontent.com/30602638/72614652-1bc17500-3933-11ea-81a6-3249811dfc76.png)

`/orders/orders/{order-id}/view`

PS 1.7.7.x

@colinegin @marionf

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team @matks what do you think of this improvement?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith We already have this topic

https://github.com/PrestaShop/PrestaShop/issues/14754

**Comment by khouloudbelguith** [comment]
@Hlavtox, yes!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Your ticket is a duplicate of #14754
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14754
