### ISSUE TITLE
Order page - The Choose button for the custom doesn't work when creating a new order

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17226]
**Describe the bug**
In the branch 1.7.7.x, in the BO => Orders => new order page (Migrated page): `/admin-dev/sell/orders/orders`
When we set a customer, the choose button doesn't work
![image](https://user-images.githubusercontent.com/16067358/72617476-51695c80-3939-11ea-947f-51fc53efe635.png)
https://drive.google.com/file/d/1fJZmUN7nlCi6QcSBFsmjjuzud_-fVDkK/view

**To Reproduce**
1. Go to the URL: shop.com/admin-dev/sell/orders/orders
2. Add a new customer
3. Set the first letters `pub@` & click on the button Choose for the customer displayed

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17232 and https://github.com/PrestaShop/PrestaShop/pull/17229
