### ISSUE TITLE
PrestaShop Checkout nothing happens clicking on create account

### ISSUE THREAD

**Issue by sabueXo** [PrestaShop/PrestaShop#17237]
Hi,

Im trying to activate PrestaShop Checkout but when I fill email and password and crlick on cnreate account or log in, nothing happens.

![image](https://user-images.githubusercontent.com/60075674/72687758-55e07180-3b01-11ea-8530-6b4d9ba01f5e.png)

PrestaShop version: 1.7.5.2
PrestaShop Checkout: v1.2.9
PHP version: 7.1.29

**Comment by sarahdib** [comment]
Hello @sabueXo 

Thank you for your report.

@v4lux can you check this ?

**Comment by sabueXo** [comment]
Hi, any info about this?

Thanks!

**Comment by khouloudbelguith** [comment]
Ping @v4lux friendly reminder :)

**Comment by Matt75** [comment]
Better to contact PrestaShop Checkout support team https://addons.prestashop.com/contact-form.php?id_product=46347

OR  support-checkout-download@prestashop.com

**Comment by khouloudbelguith** [comment]
Hi @sabueXo,

As @Matt75 said, you should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
