### ISSUE TITLE
activation/deactivation newsletter ps_emailsubscription

### ISSUE THREAD

**Issue by mauweb** [PrestaShop/PrestaShop#17234]
** Describe the bug **
I went from prestashop 1.7.5.2 to 1.7.6.2
now in customer modification the BO does not show the activate / deactivate newsletter subscription button, I tried to reset the module but nothing, I tried to uninstall and reinstall it but nothing.
the version of ps_emailsubscription is v2.5.1

** To Reproduce **
1. Go to 'customers'
2. Click on 'edit'
3. Scroll down to 'Date of birth'
4. See error 'the NO / YES button is missing'

** ** Screenshots
I attach image

** Additional information **
rstaShop version: 1.7.6.2
PHP version: 7.2.26
![Cattura](https://user-images.githubusercontent.com/47330829/72662911-d497ba80-39ec-11ea-8f4f-68a3cd7f5c36.JPG)

**Comment by sarahdib** [comment]
Hello @mauweb 
 
In 1.7.5.2 there isn't an activation/deactivation button for newsletter in the customer page
<img width="1280" alt="Capture d’écran 2020-01-20 à 15 42 51" src="https://user-images.githubusercontent.com/3034677/72735407-0d29c680-3b9c-11ea-82e7-e2525b738859.png">

It's the same in 1.7.6.2
<img width="1269" alt="Capture d’écran 2020-01-20 à 15 43 09" src="https://user-images.githubusercontent.com/3034677/72735445-1f0b6980-3b9c-11ea-932c-0037ffe3b69a.png">


This button is directly in the module ps_emailsubscription 
<img width="1275" alt="Capture d’écran 2020-01-20 à 15 48 15" src="https://user-images.githubusercontent.com/3034677/72735568-5c6ff700-3b9c-11ea-841d-ddf1a21771b4.png">

**Comment by mauweb** [comment]
ottimo grazie mille

**Comment by khouloudbelguith** [comment]
Hi @mauweb,

Thanks!
As @sarahdib said, This button (enable/disable) `newsletter subscription` is directly in the module ps_emailsubscription or in the BO => Customers list page.
![image](https://user-images.githubusercontent.com/16067358/72808203-58ee7580-3c59-11ea-9135-6d9dc8040d55.png)

I will close the issue, feel free to open a new one when needed.

Thanks!
