### ISSUE TITLE
I try to update prestashop from 1.7.6.1 to prestashop 1.7.6.2 and I get  error

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17236]
**AUTHOR: @Marcelozippo**

**Describe the bug**
I try to update prestashop from 1.7.6.1 to prestashop 1.7.6.2 and I get the following error, I have updated 1Click to the latest version.

|Información del servidor Linux #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64
Versión del software del servidor: Apache
Versión PHP: 7.2.26
Límite de memoria: 1024M
Tiempo máx. de ejecución: 600
Tamaño máx. para la subida de archivos: 256M
theme warehouse

Video Error: https://drive.google.com/file/d/1cntpd7KW9JbXVe3qKAw_VtlCTSBvCJt4/view

Issue created from bad PR https://github.com/PrestaShop/PrestaShop/pull/17235

**Comment by Marcelozippo** [comment]
Hi, I solve the problem by unzipping with cpanel and updating prestashop manually with "default directory"

Thank you

**Comment by Marcelozippo** [comment]
Thank @matks

**Comment by matks** [comment]
Well, good news 😄
