### ISSUE TITLE
1click upgrade fails from 1.6.1.24 to 1.7.6.2

### ISSUE THREAD

**Issue by Lumyo** [PrestaShop/PrestaShop#17239]
**Describe the bug**
When trying to upgrade prestashop using the 1click upgrade module (v4.10.1), the upgrade fails before the update of the DB.
I tried upgrading to 1.7.0.0 and 1.7.1.0 and those failed also but with different errors

You can see the upgrade log here
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4084717/log.txt)

**Screenshots**
![upgradePrestashop](https://user-images.githubusercontent.com/7013086/72703331-465c3980-3b90-11ea-8a1f-1741fe6bdc6b.JPG)

**Additional information**
PrestaShop version: 1.6.1.24
PHP version: 7.0.33 (Same error with 7.3.13)

**Comment by khouloudbelguith** [comment]
Hi @Lumyo,

I did not manage to reproduce the issue with PS1.7.6.3 (just released in a few hours) after an upgrade from PS1.6.1.24 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1vuFcJdj1nNl8-bvEuQVqZEAju75QelUz/view
The log attached, is it when using PHP7.0 or PHP7.3, because PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Comment by Lumyo** [comment]
Hello @khouloudbelguith ,

Thanks for your reply.

The attached log was from the php 7.0 attempt.
But the error was exactly the same when attempting with 7.3

I've just made another attempt updating to 1.7.6.3 using PHP 7.2.26, and again, I've got the exact same error, as the one at the end of the attached log in my original message.

```
[INTERNAL] /data/vhosts/mysite.com/httpdocs/shop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php line 102 - Error: Call to undefined method Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass::setHotPathEvents() 

#0 /data/vhosts/mysite.com/httpdocs/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): Symfony\Bundle\FrameworkBundle\FrameworkBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 

#1 /data/vhosts/mysite.com/httpdocs/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 

#2 /data/vhosts/mysite.com/httpdocs/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() 

#3 /data/vhosts/mysite.com/httpdocs/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 

#4 /data/vhosts/mysite.com/httpdocs/shop/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() 

#5 /data/vhosts/mysite.com/httpdocs/shop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() 

#6 /data/vhosts/mysite.com/httpdocs/shop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 

#7 /data/vhosts/mysite.com/httpdocs/shop/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 

#8 /data/vhosts/mysite.com/httpdocs/shop/admin728pqamwg/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 

#9 {main}

```

**Comment by Lumyo** [comment]
@khouloudbelguith 

Okay, I've finally managed to do the upgrade.
I found out in my log, that the php module RegisterListenersPass.php from where the error was coming, was also present in the module "mdstripe" i had installed

`[2020-01-20 07:23:37] modules/mdstripe/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php added to archive. 4137 files left.`

I've uninstalled the mdstripe module + removed it, and after that the upgrade worked fine.
I guess there was an import conflict between those 2 version of the module.

**Comment by khouloudbelguith** [comment]
@Lumyo, thanks for your feedback.

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
