### ISSUE TITLE
Сannot edit order when choosing payment option "Cash on delivery"

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#17230]
**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 5.6.38
Cash on delivery version: 1.0.6

**Comment by sarahdib** [comment]
Hello @weddingtextile 

Please can you use the template with all steps in order to help you

Thank you

**Comment by weddingtextile** [comment]
![01 Confirm order](https://user-images.githubusercontent.com/44600313/72903231-8c063700-3d35-11ea-82bb-3cc2f9c6e29c.png)
![02 Order part1](https://user-images.githubusercontent.com/44600313/72903249-93c5db80-3d35-11ea-9d4f-77cbb115f339.png)
![02 Order part2](https://user-images.githubusercontent.com/44600313/72903258-988a8f80-3d35-11ea-94a8-008c77392148.png)
![02 Order part3](https://user-images.githubusercontent.com/44600313/72903270-9c1e1680-3d35-11ea-8298-303c42ed6f33.png)
![02 Order part4](https://user-images.githubusercontent.com/44600313/72903275-9fb19d80-3d35-11ea-84bf-2cfb96e7f4c2.png)

**Comment by weddingtextile** [comment]
![02 Order part5](https://user-images.githubusercontent.com/44600313/72903583-25cde400-3d36-11ea-8b6a-4027f82755a0.png)

Documents "Delivery slip" and "Invoice" are automatically created!!!!
Therefore I cannot edit the order.

**Comment by khouloudbelguith** [comment]
@weddingtextile, when ordering with the COD payment, the status generated is `Processing in progress`.
In the BO => Shop Parameters => Order Settings => Stuses Tab => if you edit this status, you can see that:
1. Set the order as paid => is selected so => the invoice is generated
2. Show delivery PDF => is selected so => the Delivery slip is generated => so, it is not possible to edit the order.

You can customize this status.

Thanks to check & feedback.

**Comment by weddingtextile** [comment]
Thanks!
It's helped.

**Comment by khouloudbelguith** [comment]
@weddingtextile, you are welcome!
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by weddingtextile** [comment]
Why new order didn't create with status "Awaiting Cash On Delivery validation"?

**Comment by khouloudbelguith** [comment]
@weddingtextile, the COD module accepts cash on delivery payments.

Thanks!
