### ISSUE TITLE
Errore nei sistemi PayPal [10525] Invalid Data Ulteriore messaggio di errore: This transaction cannot be processed. The amount to be charged is zero.

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#17240]
Payment amount request was sent t "0" for many gateway (paypal - credit card - stripe)

PS 1.7.6.1
PHP 7.2

AFter checkout we get: Errore nei sistemi PayPal
[10525] Invalid Data
Ulteriore messaggio di errore: This transaction cannot be processed. The amount to be charged is zero.

**Comment by matteolavaggi** [comment]
The redirect function of the gateway payment (paypal or credit card), with error code, make user LOGOUT from store.
Login
Place an order 
Select paypal
Redirect back with errore (no value sent to paypal)
https://www.sixrace.it/it/module/paypal/error?error_code=10525&error_msg=Invalid+Data&msg_long=This+transaction+cannot+be+processed.+The+amount+to+be+charged+is+zero.

Customer is logged out from prestashop

**Comment by matteolavaggi** [comment]
![image](https://user-images.githubusercontent.com/24798703/72711483-6e847200-3b69-11ea-8d98-1aa4d7faf917.png)
![image](https://user-images.githubusercontent.com/24798703/72711498-7512e980-3b69-11ea-81b3-f5d263b48c03.png)
![image](https://user-images.githubusercontent.com/24798703/72711519-7a703400-3b69-11ea-9412-db54ccb1396f.png)
![image](https://user-images.githubusercontent.com/24798703/72711551-86f48c80-3b69-11ea-9d70-74b162c8cc93.png)
![image](https://user-images.githubusercontent.com/24798703/72711561-8c51d700-3b69-11ea-9ebf-9031c62b9c74.png)
![image](https://user-images.githubusercontent.com/24798703/72711578-92e04e80-3b69-11ea-93bd-8e2ef0275e78.png)



So how this is possible?

**Comment by Betafer** [comment]
I think because if you remove Paypal commission the amount is negative 3,4% + 0,35€

**Comment by matteolavaggi** [comment]
i've tryed also with 10€, same error.

After the redirect to the website , customer are also logged out from the shop

**Comment by matteolavaggi** [comment]
i've updated paypal to last release and setup in-site payment, now i get this error in BO:

Notice alla linea 1090 nel file /var/www/htdocs/www.sixrace.it/modules/paypal/paypal.php
[8] Trying to get property 'paid' of non-object

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com:  [account](https://addons.prestashop.com/en/contact-us?id_product=1748), they are the only ones to help you with it.
Thanks!
