### ISSUE TITLE
FO in Arabic should be RTL

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17245]
**Describe the bug**
The FO should be in RTL when in Arabic (and other RTL language too).

**To Reproduce**
1. On BO, install Algeria localization pack
2. Go on FO, change language to Arabic
3. Display is still Left To Right instead of Right To Left

It was OK on 1760, 1761, 1762.

**Screenshots**
In 1.7.6.2 
![image (5)](https://user-images.githubusercontent.com/55688534/72720757-f030cb80-3b7a-11ea-8c8e-b9197d9ccd7a.png)

In 1.7.6.3
![image (6)](https://user-images.githubusercontent.com/55688534/72720795-02126e80-3b7b-11ea-8877-c02aa6d58d68.png)

**Additional information**
PrestaShop version: 1.7.6.3 build 1
PHP version: N/A

**Comment by Progi1984** [comment]
@Robin-Fischer-PS Hi, Have you followed the process for generating stylesheet : https://devdocs.prestashop.com/1.7/themes/reference/rtl/#stylesheet-generation?
