### ISSUE TITLE
Outdated social network links in the installer

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17256]
**Describe the bug**
When install is finished, the installer displays multiple social network buttons to share the good news. According to the code in it, I think they are all outdated

- twitter "share" button works but refers to a VIMEO movie that does not exist anymore
- did not try facebook
- google+ is dead
- in pinterest "share button" code I see we provide the link http://img-cdn.prestashop.com/logo.png that is dead (could not test, I have no pinterest account)
- did not try Linkedin

**To Reproduce**
Install prestashop, when progress bar is done you see the "share" buttons.

**Screenshots**
<img width="953" alt="Capture d’écran 2020-01-20 à 18 47 02" src="https://user-images.githubusercontent.com/3830050/72747694-aa452900-3bb5-11ea-8e45-601f034aab89.png">

**Comment by eternoendless** [comment]
I'd suggest removing them altogether.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
It is handled by @TristanLDD's project to redesign the installer - but it must be prioritized. :-)

**Comment by eternoendless** [comment]
So I went ahead and created a PR to remove them 😉
