### ISSUE TITLE
Problem with the logo on the invoice

### ISSUE THREAD

**Issue by catamofe** [PrestaShop/PrestaShop#17252]
Hi
**Describe the bug**
I already put the logo in the logo/theme menu. But it doesn't work for the invoices and emails. The invoice doesn't show the logo.
**To Reproduce**
1. Go to 'orders'
2. Click on 'one order'
3. download the invoice
4. The invoice doesn't show the logo, and it is on the "appereance", "theme/logo" section

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.3

**Comment by sarahdib** [comment]
Hello @catamofe 

PrestaShop 1.7.5.2 is not compatible with PHP version 7.3 can you try to switch to an older version of PHP and try again to display the logo.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thank you

**Comment by catamofe** [comment]
Hello @sarahdib,

Thanks for your answer. I went back to php version 7.2 and it doesn't work either. I emptied cache and erase cookies also.
Any other idea?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @catamofe,

Thanks for your feedback.
SSL is enabled in your BO?
If yes, I think your issue is similar to this: https://github.com/PrestaShop/PrestaShop/issues/15088
As you can see here: https://github.com/PrestaShop/PrestaShop/pull/15109#issuecomment-522501213
It is a self signed certificate.
Thanks to check & feedback.

**Comment by catamofe** [comment]
It doesn't work, but I create a banner and put it with url of the image.
Thanks

**Comment by khouloudbelguith** [comment]
@catamofe, so, can I close the issue?

Thanks!

**Comment by catamofe** [comment]
yes thank you

**Comment by khouloudbelguith** [comment]
@catamofe, thanks!
Feel free to open a new one when needed.

Thanks!
