### ISSUE TITLE
in RTL logo size is not fixed size please  fix it 

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17262]
in rtl when i add logo (big size ) its change page style 
![image](https://user-images.githubusercontent.com/1392266/72757543-e938a600-3bd8-11ea-81f8-a1dbc7d27774.png)

in category in menu need fixed <when i press on category its show sub cat and show over logo and other things 
![image](https://user-images.githubusercontent.com/1392266/72757578-040b1a80-3bd9-11ea-91a3-7c504bf6e9f4.png)

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

What is the exact version did you use of PrestaShop?
What are the exact `Width` & `Height` of your image?
Is it the issue that the menu is hiding the logo?
Same behavior with a no RTL language
![image](https://user-images.githubusercontent.com/16067358/72797951-52a0cf00-3c42-11ea-8891-bf186c08d6df.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
