### ISSUE TITLE
DNI and Postal code not added when creating a supplier

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17268]
**Describe the bug**
When creating a supplier, if DNI and Zip/postal code are filled, these fields will not be filled in the created supplier.

**To Reproduce**
1. Go to Supplier, create a new supplier
2. Fill the DNI and Zip/postal code fields and create
3. Open the supplier : DNI and Zip/postal code fields are empty
4. Edit the supplier, add again DNI and Zip code and save
5. Open the supplier : DNI field is still empty, Zip code is filled

>Edit By Khouloud
Other issues reported when selecting Spain country, please see: https://github.com/PrestaShop/PrestaShop/issues/17268#issuecomment-576634443

**Screenshots**
https://drive.google.com/file/d/181rP_-rIIkXvGHGpzEwp2X5l72wzJGsT/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A
Other info : Tested with a shop installed in English, with country "France"

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

>**To Reproduce**
>Steps to reproduce the behavior:
>- Go to Supplier, create a new supplier
>- Fill the DNI and Zip/postal code fields and create
>- Open the supplier : DNI and Zip/postal code fields are empty
>- Edit the supplier, add again DNI and Zip code and save
>- Open the supplier : DNI field is still empty, Zip code is filled

I have the same issue with 1.7.7.x branch.
With PS1.7.6.2, in the supplier page, when France country is selected, the zip code field is displayed by default.
![image](https://user-images.githubusercontent.com/16067358/72799578-d8724980-3c45-11ea-8d0c-c71da5ffc57a.png)
=> well saved => regression
The `dni` field in the not displayed by default when France is selected.
But it is not the same behavior with 1.7.7.x branch
![image](https://user-images.githubusercontent.com/16067358/72799722-1ec7a880-3c46-11ea-9f47-85acd5a20fb9.png)

In the PS1.7.6.2, when we select Spain country (`dni` is displayed & well saved).

In the Branch 1.7.7.x
If we select Spain country, set all required fields => Save => error
![image](https://user-images.githubusercontent.com/16067358/72799989-a6151c00-3c46-11ea-8e05-c4903deaa607.png)

**Comment by khouloudbelguith** [comment]
`Spain` is the second top country where visitors came from, so I will change the severity from Minor to Major.

Thanks!

**Comment by zuk3975** [comment]
This page doesn't check required fields of addresses at all(customized in customer->addressess -> set required fields). Im on it

Edited: Sadly its the same issue for Brands too.

**Comment by zuk3975** [comment]
Sorry, re-checked. Seems like legacy page just didn't have DNI field. Post code was a mistake in handler. Fixed in #17305 
According to legacy Supplier and brand addresses wasn't dependant from Customer->addresses->required fields, so it seems to be fine for now.
