### ISSUE TITLE
Debug Mode 500 error

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#17260]
Hi, in my prestashop 1.7.6.1 I have on the debug mode and I have this message: 
![image](https://user-images.githubusercontent.com/54579601/72753944-fea8d280-3bce-11ea-8d06-afc3ed5c900a.png)

When I tried to make the debug mode of my site crashes and I get an Internal server error.

Do you know why this keeps happening to my site?

**Comment by khouloudbelguith** [comment]
Hi @sotirisa,

Are you using any third-party module?
There must be a module currently implementing the config file on its own, are you maybe able to find the string anywhere else in the main folder/subfolders?

Thanks to check & feedback.

**Comment by sotirisa** [comment]
Hi after the update to 1.7.6.3 all is ok now thank you.

**Comment by khouloudbelguith** [comment]
@sotirisa, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
