### ISSUE TITLE
2 feature in classic theme ( category)

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17263]
can you add category  image in menu ? (icon if possible )
![image](https://user-images.githubusercontent.com/1392266/72757388-7e876a80-3bd8-11ea-9406-a22d148a02e4.png)

can you add sub category images in main  category ?
![image](https://user-images.githubusercontent.com/1392266/72757443-a4147400-3bd8-11ea-8c91-2b79ca07c862.png)

fix brand page and make it more stylish .

classic rocket dose not support Arabic and home page not showing well

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Using the Classic theme:
* If I upload a cover image after the category thumbnail, it erases the thumbnail.
* If I upload a thumbnail image after the cover image, the thumbnail image, in the FO is not displayed.
* If I delete the "Category Cover Image" the "Category thumbnail" is deleted too.
* If I try to add a thumbnail image, in the FO, it is not displayed

In fact, we will offer a category thumbnail feature, we will enable merchants to choose to have different cover image and thumbnail as reported here: https://github.com/PrestaShop/PrestaShop/issues/12760
Thanks to check & feedback.

>classic rocket dose not support Arabic and home page not showing well

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via https://github.com/PrestaShop/classic-rocket/issues.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
