### ISSUE TITLE
Gather in the same location all example modules

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17275]
We have multiple example modules (for different purposes) in multiple locations 😅 .

https://github.com/sarjon/demo-grid-module
https://github.com/sarjon/orderhooks
https://github.com/friends-of-presta/demo-cqrs-hooks-usage-module
https://github.com/friends-of-presta/products
https://github.com/friends-of-presta/masterclass
https://github.com/friends-of-presta/customers

We should gather them at a single place and explain what they are intended for.

**Comment by khouloudbelguith** [comment]
Ping @eternoendless @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment]
We could add them in the documentation like it's done for Rubygems
https://guides.rubygems.org/run-your-own-gem-server/ 
GemInABox and Gemirro came from the contributors code

**Comment by matks** [comment]
Repository created https://github.com/PrestaShop/example-modules
