### ISSUE TITLE
DNI number issue

### ISSUE THREAD

**Issue by Maros4444** [PrestaShop/PrestaShop#17270]
Hello,

I am using prestashop 1.7.1.1. I'm having trouble with Slovakia VAT number in creating a new customer account - when a customer enters an VAT in any format in the VAT field, they receive an invalid format notification. The only way to get around this is to leave this field blank (I set this VAT field to optional) and then enter its VAT number in address creation. Can you help me in this way?

**Comment by khouloudbelguith** [comment]
Hi @Maros4444,

Thanks for your report.
This issue occurs when creating a new address country and not a new customer account? is it?
![image](https://user-images.githubusercontent.com/16067358/72802225-93511600-3c4b-11ea-8443-b12e3e58e554.png)

Did you use this module: https://github.com/PrestaShop/vatnumber?

Thanks!

**Comment by Maros4444** [comment]
This issue occurs when a customer tries to create an account with filling an VAT field number - after he clicks to create an account, he will get "invalid format" notification. 
![attachment1](https://user-images.githubusercontent.com/60134271/72806175-e9768700-3c54-11ea-820b-9ffca5ca3c93.png)

The same happens when he creates an account without entering a number and then clicks on his account - he enters the information to edit - he also recieves "invalid format" notification 
![attachment2](https://user-images.githubusercontent.com/60134271/72806466-876a5180-3c55-11ea-9e3c-3b55748db4a2.png)

According to vatnumber module - I have tried it, but the issue still ocurres

The only way to get around this is when customer leave this VAT field blank (because is optional) when creating an account. Then he can enter the VAT number when creating his first address - there's no problem with VAT number here in creating address.

Do you have a solution to this issue?

Big Thanks!!

**Comment by khouloudbelguith** [comment]
@Maros4444, thanks for your feedback.
B2B is enabled in your case.
In my case, I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
 https://drive.google.com/file/d/1iWgRGwPvHW08CtgCm4pmDAHloQ6fFz3M/view
Thanks to check & feedback.

**Comment by Maros4444** [comment]
@khouloudbelguith so is there any way to fix my issue? I have tried everything, issue still occurs.

**Comment by khouloudbelguith** [comment]
@Maros4444, Your issue is it similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/9884?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith He is talking about DNI field, not VAT field. In Slovakia, they have the names a bit different.

@Maros4444 If you write VAT field, everyone means the tax number - Slovakian “IČ DPH” field.

**Comment by Maros4444** [comment]
@Hlavtox @khouloudbelguith Sorry guys, I meant DNI field, not VAT.

**Comment by khouloudbelguith** [comment]
@Maros4444, B2B is enabled in your case? is it?
![image](https://user-images.githubusercontent.com/16067358/72881009-40856600-3d00-11ea-8e8f-55a8a396737e.png)

It is this field "the Identification number"?
![image](https://user-images.githubusercontent.com/16067358/72880939-22b80100-3d00-11ea-8aa4-b3950d1be42b.png)
In my case, it is OK with PS1.7.6.3 when creating new customer & updating customer information
https://drive.google.com/file/d/10u6Nzd6mgussbOS5ibhScqstuJhBLiYU/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Maros4444** [comment]
@khouloudbelguith Yes, I have enabled B2B mode.

This is info about our test server (it is the same as live version)
- server setup and configuration:
![config](https://user-images.githubusercontent.com/60134271/72886057-68c59280-3d09-11ea-8927-a5941bf81bfc.png)

- error logs: 
[fpm-php.log](https://github.com/PrestaShop/PrestaShop/files/4096549/fpm-php.log)

- console log:
![console](https://user-images.githubusercontent.com/60134271/72886549-47b17180-3d0a-11ea-8b1b-ed2a6193c3e4.png)

Thanks for your suggestions!

**Comment by khouloudbelguith** [comment]
@Maros4444,

You have these errors:
>[13-Jan-2020 13:18:59 Europe/Bratislava] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /home/probugas/files/probugas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91

It may be easier to check if the connection to MySQL and re-establish it if needed, you need to check your host for more details.
>[13-Jan-2020 13:18:06 Europe/Bratislava] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\MethodNotAllowedException' in /home/probugas/files/probugas/app/cache/prod/appProdProjectContainerUrlMatcher.php:683

Could you please try to clear the cache manually by deleting all the folder into app/cache (prod & dev).
>[22-Jan-2020 11:14:17 Europe/Bratislava] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

You need to update your php.ini file as recommended, you need to check your host for more details.
Thanks to check and feedback.

**Comment by Maros4444** [comment]
@khouloudbelguith 

Yes, we know about first two errors - they are no longer up-to-date as they are from the time of the prestashop migration to the new server.

Last error - we will resolve the last error with our provider, but I think that this error has nothing to do with the DNI problem.

We also tried a one click upgrade, after which many things didn't work, but the issue with the DNI field was fixed. So I think it´s some kind of bug for prestashop 1.7.1.1 version.

Do you have some another advice on this issue?

**Comment by khouloudbelguith** [comment]
@Maros4444, I think this issue is similar to this: http://forge.prestashop.com/browse/BOOM-2754 fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/7856 (it is closed & replaced by this PR: https://github.com/PrestaShop/PrestaShop/pull/7898)

Thanks to check & feedback.

**Comment by Maros4444** [comment]
@khouloudbelguith, changing validate from isSiret to isGenericName in classes/Customer.php worked for me.

-   changed from:       'siret' => array('type' => self::TYPE_STRING, 'validate' => 'isSiret'),
                       to:        'siret' => array('type' => self::TYPE_STRING, 'validate' => 'isGenericName'),

This change means that the customer can enter any values ​​in this field (without verification), but it's better than not creating an account at all when customer fill out this DNI (Siret) field.

Thank you very much for your suggestions!

**Comment by khouloudbelguith** [comment]
@Maros4444, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!
