### ISSUE TITLE
"The CSRF token is invalid. Please, try to resubmit the form"

### ISSUE THREAD

**Issue by ocaste** [PrestaShop/PrestaShop#17277]
Hi, sorry cause my English;

I'm working on 1.7 prestashop  version, when going to Custom page, all the page seems somthing going wrong cause can see all page correctly.

Creating a new product, this error ocurred: "The CSRF token is invalid. Please, try to resubmit the form"
![Captura de pantalla 2020-01-17 a las 15 17 04](https://user-images.githubusercontent.com/60144911/72816617-be962e00-3c68-11ea-8081-3bef453319c2.png)
![Captura de pantalla 2020-01-17 a las 15 13 41](https://user-images.githubusercontent.com/60144911/72816652-ceae0d80-3c68-11ea-862a-99b8e92665a4.png)
![Captura de pantalla 2020-01-17 a las 15 17 04](https://user-images.githubusercontent.com/60144911/72816669-d372c180-3c68-11ea-9e05-bfbc8d6cb7b0.png)

**Comment by khouloudbelguith** [comment]
Hi @ocaste,

You need to increase the max_input_vars from 1000 to 15000 in your PHP configuration, this is a limitation of PHP which - by default - can manage only 1000 fields.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @ocaste,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Houmeid** [comment]
Hey @khouloudbelguith ! I've got the same problem when i try to create a new product.
"The CSRF token is invalid. Please try to resubmit the form."
And  as u said, i've modified the php.ini file but nothing changed.
I'm working on 1.7 prestashop version, when i'm on the custom page, it seem like something is wrong cause i can't see the page correctly (sorry for my english i used to talk in french)
thanks for your help

**Comment by khouloudbelguith** [comment]
Hi @Houmeid,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by Houmeid** [comment]
No problem @khouloudbelguith thanks !

**Comment by Houmeid** [comment]
Hey @khouloudbelguith it's done, i've create a new issue thanks for the help

**Comment by Cristian6600** [comment]
Good day i have the same problem probe aumentar 
try increasing max_input_vars from 1000 to 15000

**Comment by giff715** [comment]
You need to make sure your new 15000 setting is not commented out

check your php.ini file under ;max_input_vars 1500 MAKE SURE the " ; " is not infront of the "max_var_input" section
like this            max_input_vars = 15000      then save and restart the Apache server in your settings.

If you have a  ";" infront of these settings they will not be an active rule
