### ISSUE TITLE
blockreassurance not hooked on footer and header by default

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17278]
**Describe the bug**
blockreassurance not hooked on footer and header by default

**To Reproduce**
1. Fresh install of PS
2. Go to Module manager, search blockreassurance and configure it
3. Click on 'Display' tab
4. Select above header or below header and above footer or below footer
5. Go in FO homepage, you don't see it because it's only hooked on displayReassurance
6. If I reset the module it's ok, the module is hooked on displayFooterAfter, displayFooterBefore and displayNavFullWidth

**Additional information**
PrestaShop version: 1.7.7 and blockreassurance 4.1.1
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed in #17349
