### ISSUE TITLE
Remove the dependency to Google Font in the BO

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#17274]
**Describe the bug**
If PrestaShop has to be installed on a private network with no access to the web, it will not have a mean to access to Google Font:
For text style and some icons, there are two sans-serif fonts in the BO:
https://fonts.google.com/specimen/Ubuntu
https://fonts.google.com/specimen/Open+Sans

**To Reproduce**
relative to #10456

**Additional information**

- Check with default sans-serif of Mac, Windows, Android and iOS if their default sans-serif font include all the icons. Then is it possible to remove the dependency. This would be the best choice: no additional weight in the installer, cleaned CSS, and no new dependency to manage
- Otherwise, the best is to actually include those files in the PrestaShop core/installer. This way, no need for network to display the BO icons.

I checked, the distribution license of the files make them suitable to be included in the PrestaShop project.

If UX designers could also check what icons are used in the fonts, and add a list to the devdocs, that would be awesome.

**Comment by khouloudbelguith** [comment]
Hi @ttoine,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/12772?

Thanks!

**Comment by ttoine** [comment]
It's a different issue: in #12772 this is a "material" icon problem.
here, this will have an impact on text look'n feel, plus, fonts include a few icons and other special characters that might be used in the BO.

I am curious to know if #16209 fixed this issue or not.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers

**Comment by NeOMakinG** [comment]
Should be fixed in next UIKit release

**Comment by LouiseBonnard** [comment]
Hi @ttoine and @NeOMakinG, I close this ticket since https://github.com/PrestaShop/prestashop-ui-kit/pull/102 has been merged, feel free to reopen it if need be. :-)
