### ISSUE TITLE
Free Shipping voucher not deleted after creating an order on BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17276]
**Describe the bug**
When creating an order on BO, if the merchant select the "Free shipping" option, then unselect it, a voucher is created. Since it's not used, the customer can see this voucher on FO in the "Voucher" section, and it can be used, because the "Total available" is still at "1".

**To Reproduce**
1. Go to BO page "Create order"
2. On the form, select then unselect the "Free shipping" option
3. Go to FO (with ou without creating the order on BO, it does not change the behaviour), on the Voucher list of the customer
4. See the "Free Shipping" voucher created by the "Create order" page on BO
5. You can use this voucher on FO

This happens on both Legacy and Migrated page.

**Screenshots**
![free shipping voucher](https://user-images.githubusercontent.com/55688534/72816123-fd77b400-3c67-11ea-913e-b81b6d776202.png)

**Additional information**
PrestaShop version: 1.7.6.x - 1.7.7.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.5.2 & PS1.7.6.3
https://drive.google.com/file/d/1kTYFWE2ZUSiklS1_ZIRcgUs8OzqihGGF/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by Progi1984** [comment]
Fixed by #17421
