### ISSUE TITLE
Combination / Attributes - bad refresh at product detail

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#17289]
**Describe the bug**
After upgrade from 1.7.6.2 to 1.7.6.3 products attributes bad refresh at product detail. If i click to any attribute, other attributes cant refresh. After full reload in browser, attributes show ok.
Look on video: 
https://www.loom.com/share/e1d847ad226a46df93db0c0bf298395a
another:
https://www.loom.com/share/b6f74599e8814dcc9ce61436bb3d4c54

**To Reproduce**
1. Go to 'Product detail'
2. Click on 'some attribute and look to other attributes, they can´t refresh'

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2
Tested on classic theme and custom theme.

**Comment by khouloudbelguith** [comment]
Hi @TaccCZ,

I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1wK1oFAYDXrozFd1qieBIIVxAgBZYoFtf/view
Have any errors during the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by TaccCZ** [comment]
Dear  @khouloudbelguith,
here is zipped log: https://drive.google.com/file/d/1mC4rhE4jnCPdriM4sxf10J9cl_7WBFTy/view?usp=sharing

I didn't see any upgrade errors. I returned from the backup version of PS 1.7.6.2 and on this version everything works fine. If I upgrade to 1.7.6.3 again, the bug will reappear.

Thank you for you help.

**Comment by khouloudbelguith** [comment]
@TaccCZ, in your log file, `all files upgraded` & `Database upgrade OK`.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TaccCZ** [comment]
Hi,
**1. Server setup and configuration:**
Server information Linux #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64
Server software version: Apache/2.4.25 (Debian)
PHP version: 7.2.26-1+0~20191218.33+debian9~1.gbpb5a34b
Memory limit: 512M
Max execution time: 600
Upload Max File size: 250M
MySQL version: 10.1.41-MariaDB-0+deb9u1
MySQL server: localhost
MySQL name: devstrojnipily_4
MySQL user: devstrojnipily.4
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPD

**2. PS Install Version: 1.7.3.3**

**3. In PS 1.7.6.3 Changed/missing files have been detected after upgrade.** (PS 1.7.6.2 is ok)
Updated files (20)
admin/autoupgrade/index.php
admin/autoupgrade/backup/index.php
config/defines.inc.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/BitrixInstaller.php
vendor/composer/installers/src/Composer/Installers/CraftInstaller.php
vendor/composer/installers/src/Composer/Installers/Concrete5Installer.php
vendor/composer/installers/src/Composer/Installers/AsgardInstaller.php
vendor/composer/installers/src/Composer/Installers/KirbyInstaller.php
vendor/composer/installers/src/Composer/Installers/ShopwareInstaller.php
vendor/composer/installers/src/Composer/Installers/SilverStripeInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/TYPO3CmsInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/WordPressInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MediaWikiInstaller.php


**4. PHP config** 
is here: https://drive.google.com/open?id=11Ycx5GynmfvpT4V9pmyMtrFX4UlDFqu3

**5. I found some bug in "debug mode"** https://www.loom.com/share/ad3a175447bc4e3f99f8b3d246475bea
There is a problem in the English language that I show in the video. Can it have coherence? This problem does not occur in the Czech language.

**6. Error log**
is here: https://drive.google.com/open?id=1OQtrYAZgl1NIeROdPRmZ6lu8cP2a6ltN

**7. PHP Error log**
all is ok

**8. Javascript console**
all is ok

Thank you

**Comment by khouloudbelguith** [comment]
@TaccCZ, could you please provide me a screenshot from your Database => Table `ps_currency_lang`.
It similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/15946#issuecomment-559557259

Thanks!

**Comment by TaccCZ** [comment]
Here: 
![image](https://user-images.githubusercontent.com/37780517/72897519-6e7ba200-3d22-11ea-8dce-054ea97e8197.png)
same in PS 1.7.6.2 and 1.7.6.3

**Comment by khouloudbelguith** [comment]
@TaccCZ, your second language is English? is it?

Thanks!

**Comment by TaccCZ** [comment]
Yes, I filled in the second line "name" and "symbol" in EN adminstration no longer error. However, the problem with loading combinations in product detail is still not resolved.

**Comment by khouloudbelguith** [comment]
@TaccCZ, You need to enable debug mode in your store and debug request which is sent for product edition in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. edit the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by TaccCZ** [comment]
I make videos:
admin 
https://www.loom.com/share/b1d788fe595e42d79188468b815a5fc2
frontend 
https://www.loom.com/share/ac0f1e8d52c94ddca6b8346b7a780daa

Debug mod does not display any error. :(

**Comment by khouloudbelguith** [comment]
@TaccCZ, try to click on this error
![image](https://user-images.githubusercontent.com/16067358/72900224-c79a0480-3d27-11ea-8645-dd2e4c5eb373.png)
you should see the error message in the "Response" or "Preview" tab.
![image](https://user-images.githubusercontent.com/16067358/72901640-6aec1900-3d2a-11ea-8019-475b68deba18.png)

Thanks!

**Comment by TaccCZ** [comment]
It is only addthis plugin, if I disable it, same problem:
https://www.loom.com/share/b3f449a70fe9455a9424f7ed294c222f

**Comment by khouloudbelguith** [comment]
@TaccCZ, this issue occurs only when a friendly URL is enabled?
Could you please try to disable friendly URL, clear cache, check & feedback.

**Comment by TaccCZ** [comment]
I disabled friendly URL, no change
https://www.loom.com/share/1e65af17e6db46a09059d3f882f26d79

**Comment by khouloudbelguith** [comment]
@TaccCZ, did you check if you have some overrides or some custom modules not compatible with the new version PS1.7.6.3?

Thanks to check & feedback.

**Comment by TaccCZ** [comment]
I checked overrides, nothing here. All modules disabled. But the same problem...

**Comment by khouloudbelguith** [comment]
@TaccCZ, I found this error `Primary script unknown\n` is related to your server.
Are you using PHP-FPM?
It is almost always related to a wrongly set SCRIPT_FILENAME.
So, could you please check with your host & feedback.

**Comment by TaccCZ** [comment]
@khouloudbelguith , i will check the server. But this "problem" is showed in version 1.7.6.2 and everything works fine. So I don't think this will be the case. Both versions 1.7.6.3 and 1.7.6.2 are on the same server with the same configuration.
Version 1.7.6.2 - https://www.strojni-pily.eu/ works fine.

**Comment by TaccCZ** [comment]
@khouloudbelguith, I guess I found the mistake that makes it.
File: themes/core.js. 
When you rewrite this file from the previous version 1.7.6.2 to the new 1.7.6.3, everything works as it should. The files are different in data.
So there must be a bug.

**Comment by khouloudbelguith** [comment]
@TaccCZ, but in my case, I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16852 added to PS1.7.6.3 & modifying `themes/core.js`.

Thanks!

**Comment by TaccCZ** [comment]
@khouloudbelguith 
Thanks for the answer, I don't know what caused it. Maybe he is testing on a small sample of data. I have 4 types of combinations, you tested on 2 types (basic + color combinations).

But the error must be in core.js, since the older version of PS everything works normally.

Thank you

**Comment by khouloudbelguith** [comment]
Ping @NeOMakinG what do you think?
This PR: https://github.com/PrestaShop/PrestaShop/pull/16852 is related to this issue reported by the @TaccCZ.

PS: in my case => OK.

Thanks!

**Comment by webeshop** [comment]
My clients have the same problem as @TaccCZ . Bug is in core.js.

**Comment by khouloudbelguith** [comment]
Ping @NeOMakinG friendly reminder :) 

Thanks!

**Comment by khouloudbelguith** [comment]
@TaccCZ, @webeshop, is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/17437?

Thanks!

**Comment by webeshop** [comment]
@khouloudbelguith Yes, I think so.

**Comment by khouloudbelguith** [comment]
@TaccCZ, @webeshop, we are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17437
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #17437
