### ISSUE TITLE
ps_facetedsearch 3.4.0 upgrade to 3.4.1

### ISSUE THREAD

**Issue by karopka** [PrestaShop/PrestaShop#17299]
Prestashop 1.7.6.2
ps_facetedsearch 3.4.0

I'm trying to upgrade facetedsearch to 3.4.1 version. System says that upgrading successfully finished, but ather refreshing the page, module version is still 3.4.0 and asking for upgrade.

**Comment by khouloudbelguith** [comment]
Hi @karopka,

Could you please check the version of your module in this file
Project_Folder/modules/ps_facetedsearch/config.xml
https://github.com/PrestaShop/ps_facetedsearch/blob/master/config.xml#L5

Thanks to check & feedback.

**Comment by karopka** [comment]
3.4.1
but it's still asks me to update:
![image](https://user-images.githubusercontent.com/18676256/72954923-95ce7f80-3db3-11ea-8f59-8b4f30bc9100.png)

**Comment by khouloudbelguith** [comment]
@karopka, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
In my case, it is OK: https://drive.google.com/file/d/151Ki7Yy48xzmnBucmKHcN9iz1_c_zLpk/view
Thanks to check and feedback.

**Comment by karopka** [comment]
1. I cleared cache manually.
2. I disabled opcache and cleared cache manually.
3. I disabled opcache, purged cache on cloudflare and cleared cache mannually.

I don't want to reinstall module because afraid to lost settings.
Nothig helps. 

Does this bug will prevent me to future upgrades?

**Comment by khouloudbelguith** [comment]
@karopka,

>Does this bug will prevent me to future upgrades?

no, it is just a cache issue.

You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by karopka** [comment]
I had tried it. Also I had tried to open admin page in incognito mode, to clear cache. I had disabled cache subsystems at the prestashop, at the server, at the cloudflare. I had tried to delete cached files manually. It is no helps.

Let it be.

**Comment by khouloudbelguith** [comment]
@karopka, thanks for your feedback.

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!
