### ISSUE TITLE
Remove forgotten branches

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17298]
This issue is feature request solely to improve git readability.

Remove branches like `master`, `1.7.6.0-beta` and if possible also the feature branches like `LouiseBonnard-patch-4` - create a PR from them instead.

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
I removed branches that looks unnecessary, however
- not sure about `1.7.6.0-beta`, need @eternoendless confirmation
- not sure about `master` branch, dont want to break some github workflow linked to it 😅

**Comment by mvorisek** [comment]
>     * not sure about `master` branch, dont want to break some github workflow linked to it 😅

I understand, but it is 3 years old... Tagged by `1.7.2.0` .git tag which is also part of the `develop` history, so if needed, it can be restored anytime. :)

same for the `1.7.6.0-beta`, tagged by `1.7.6.0-beta.1`.

**Comment by eternoendless** [comment]
Done!

**Comment by eternoendless** [comment]
For information:

- The `master` branch hasn't been used for years (the default branch for this repo is `develop`)
- The `1.6.1.x` branch is now obsolete because of https://github.com/PrestaShop/PrestaShop-1.6
