### ISSUE TITLE
Add displayProductPriceBlock hook in cart-detailed-product-line.tpl

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#17295]
**Is your feature request related to a problem? Please describe.**
Hook `displayProductPriceBlock` is executed almost always that product price is displayed except on `/themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl`

**Describe the solution you'd like**
Add hook 

`{hook h='displayProductPriceBlock' product=$product type="unit_price"}`

after the price is displayed at `/themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl`.

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
So, do you suggest to replace this line: https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl#L61
by this
`{hook h='displayProductPriceBlock' product=$product type="unit_price"}`?

Thanks!

**Comment by khouloudbelguith** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/17296

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by colinegin** [comment]
Seems nice !

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/17509/

**Comment by idnovate** [comment]
Sorry I did the change at https://github.com/PrestaShop/PrestaShop/pull/17296/files#diff-4dd59963e40fe140a0670e109663ef85 but I mixed commits :confounded:

Not sure if it should be displayed before or after `unit_price` and which should be the `type`...

**Comment by matks** [comment]
Then let's keep your PR 😉 so you'll get the mentions (and the glory !). I'll close mine.

**Comment by idnovate** [comment]
> Then let's keep your PR 😉 so you'll get the mentions (and the glory !). I'll close mine.

No problem

**Comment by colinegin** [comment]
Fixed by : https://github.com/PrestaShop/PrestaShop/pull/17296
