### ISSUE TITLE
Cart not refreshed when adding voucher with a gift product

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#17290]
**Describe the bug**
If you create a voucher with a free gift, when you add it in the checkout page the cart is not refreshed.

**To Reproduce**
1. Create a cart rule with a gift product and with a coupon code

![image](https://user-images.githubusercontent.com/15104724/72876686-5d696b80-3cf7-11ea-8e92-09722333220d.png)

![image](https://user-images.githubusercontent.com/15104724/72876702-68bc9700-3cf7-11ea-82bb-2303719387f0.png)

2. Add a product to the cart
3. Go to the checkout (not the cart summary)
4. Add the coupon code

![image](https://user-images.githubusercontent.com/15104724/72876606-298e4600-3cf7-11ea-8fd6-57a9cd848d81.png)
![image](https://user-images.githubusercontent.com/15104724/72876776-a28d9d80-3cf7-11ea-89eb-926de8cc922d.png)

![image](https://user-images.githubusercontent.com/15104724/72876628-3ad75280-3cf7-11ea-91de-3680d4119a6f.png)

5. After refreshing the page

![image](https://user-images.githubusercontent.com/15104724/72876650-488cd800-3cf7-11ea-9612-f4554b886dc3.png)

6. If you delete the voucher, the cart is not updated neither. The gift is not removed:

![image](https://user-images.githubusercontent.com/15104724/72876822-ba652180-3cf7-11ea-9785-86005feaad8a.png)

![image](https://user-images.githubusercontent.com/15104724/72876853-c94bd400-3cf7-11ea-8ef2-1100fce87316.png)

**Additional information**
PrestaShop version: 1.7.6.3

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2 & PS1.7.6.3 & branch 1.7.7.x.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
