### ISSUE TITLE
Submit Prestashop to Packagist

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17303]
Submit `prestashop/prestashop` package to Packagist, so that PrestaShop can be installed like:

```
composer create-project prestashop/prestashop
```

or if some libs from PrestaShop are needed, so it can be added to some other project like:
```
composer require prestashop/prestashop
```

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by sam-pires** [comment]
Hi
I'll ping @PrestaShop/prestashop-core-developers.
Wdyt guys?

**Comment by ttoine** [comment]
I like the use case.

**Comment by matks** [comment]
It might require to do a little more steps than just submitting to packagist 🤔 I think `composer require` and `composer create-project` have different behaviors

**Comment by mvorisek** [comment]
> It might require to do a little more steps than just submitting to packagist 🤔 I think `composer require` and `composer create-project` have different behaviors

Yes, the goal is to be able to:
- install PrestaShop by composer
- add prestashop to some other project to use PrestaShop libs. I tried today, but found out PrestaShop is not at Packagist at all... Also added this use-case to the issue description.

**Comment by PierreRambaud** [comment]
Why not, but PrestaShop is not designed to be included as a package, it's an application :)

**Comment by PierreRambaud** [comment]
PIng @eternoendless Could you confirm :)

**Comment by mvorisek** [comment]
@eternoendless can you reply, so PS libs can be included in another projects?

**Comment by eternoendless** [comment]
The submitting part is easy, but there are some complications:

- The versioning scheme won't really be semver compliant until the next major
- What happens if you upgrade via composer?

**Comment by mvorisek** [comment]
> The versioning scheme won't really be semver compliant until the next major

that is fine, developers can require a specific version if needed

> What happens if you upgrade via composer?

upgrade will upgrade packages to the latest matching packages, composer hooks are never run for non-root packages

**Comment by eternoendless** [comment]
> upgrade will upgrade packages to the latest matching packages, composer hooks are never run for non-root packages

I mean your shop will be broken if the database scheme is not updated, etc.

**Comment by mvorisek** [comment]
Yes, care needs to be taken by the developer.

The advantage of having PrestaShop on composer is that PrestaShop libs can be incuded in other projects. To maintain integrity, we can simply check against database (value stored in configuration table) the current installed version and throw if the version is not equal.

**Comment by eternoendless** [comment]
> The advantage of having PrestaShop on composer is that PrestaShop libs can be incuded in other projects

How so?

**Comment by mvorisek** [comment]
`composer require prestashop/prestashop` and then use anything from the exisitng PS ecosystem. For some uses just static libs, for other include config and interact with the DB of some existing installation.

**Comment by eternoendless** [comment]
There you go https://packagist.org/packages/prestashop/prestashop

**Comment by mvorisek** [comment]
@eternoendless thank you ❤️

For anyone interested, here is an example `composer.json` to require PrestaShop:
```
{
    "type": "library",
    "require": {
        "prestashop/prestashop": "^1.7.7"
    },
    "config": {
        "platform": {
            "php": "7.2.5"
        },
        "sort-packages": true
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/PrestaShop/php-cssjanus",
            "canonical": false
        },
        {
            "type": "vcs",
            "url": "https://github.com/PrestaShop/CsaGuzzleBundle",
            "canonical": false
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
