### ISSUE TITLE
Upgrade all packages to the latest versions - mainly Symfony and Twig

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17300]
This is a feature request to upgrade all packages to the latest versions.

It is important as custom modules or other custom code is currently limited by the PrestaShop old dependencies like `symfony/symfony` 3.4 or `twig/twig` 1.x.

TODOs:

- [x] SOLVED/MERGED create PR for "prestashop/blockreassurance" and "prestashop/productcomments" to support Symfony 4.x and 5.x (currently these packages requires "symfony/css-selector" of version 3.4)
- [ ] (solve issue #17351 first) create PR for "prestashop/circuit-breaker", "prestashop/blockreassurance", "prestashop/productcomments" to allow Guzzle "^6.2.1" (first 6.x version without security holes as advised by Packagist)
- [ ] (solve TODO above first) replace "guzzlehttp/cache-subscriber" archived/deprecated package with "kevinrob/guzzle-cache-middleware" package, required by: "prestashop/blockreassurance", "prestashop/productcomments", suggested by: "prestashop/circuit-breaker"
- [ ] create PR for "prestashop/prestashop" to allow Symfony packages "^3.4 || ^4.4 || ^5.0"
- [ ] create PR for "prestashop/prestashop" to allow "twig/twig" package "^1.38 || ^2.7 || ^3.0"
- [ ] (only dev, not strictly required by PrestaShop) make sure every dependency is using "phpunit/phpunit" package "^7.5 || ^8.5"
- [ ] (only dev, not strictly required by PrestaShop) make sure every dependency is tested against PHP 7.2 - PHP 7.4

notes:
- based on https://gist.github.com/mvorisek/91ffee6254aed784daff3f1a0994d11a#gistcomment-3153227
- TODOs should be solved in the same order

**Comment by mvorisek** [comment]
`csa/guzzle-bundle`: reported https://github.com/csarrazi/CsaGuzzleBundle/issues/258

**Comment by mvorisek** [comment]
`guzzlehttp/cache-subscriber`: archived project - https://github.com/guzzle/cache-subscriber , can this dependency be removed/replaced?

**Comment by mvorisek** [comment]
`guzzlehttp/log-subscriber`: not directly required by PrestaShop

**Comment by mvorisek** [comment]
`prestashop/blockreassurance`: it requires https://github.com/guzzle/cache-subscriber which is deprecated

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Ping @matks @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by mvorisek** [comment]
`prestashop/translationtools-bundle`: it requires `twig/twig` < 3.0 in the `composer.json`.

**Comment by mvorisek** [comment]
`friendsofphp/php-cs-fixer`: requires `php-cs-fixer/diff` < 2.0 which is fine (internal CS fixer dependency), IGNORE

**Comment by mvorisek** [comment]
TODOs:

- [ ] create PR for https://github.com/csarrazi/CsaGuzzleBundle/issues/258
- [ ] get rid of "guzzlehttp/cache-subscriber" archived/deprecated package, required by: "prestashop/blockreassurance", "prestashop/productcomments", suggested by: "prestashop/circuit-breaker"
- [ ] create PR for "prestashop/blockreassurance" and "prestashop/productcomments" to support Symfony 4.x and 5.x (currently these packages requires "symfony/css-selector" of version 3.4)
- [ ] create PR for @TODO "", "" to allow Guzzle "^6.2.1" (first 6.x version without security holes as advised by Packagist)
- [ ] create PR for @TODO "", "" to allow Symfony 4.x and 5.x
- [ ] create PR for @TODO "", "" to allow Twig 3.x

notes:
- based on https://gist.github.com/mvorisek/91ffee6254aed784daff3f1a0994d11a
- TODOs should be solved in the same order

**Comment by mvorisek** [comment]
See https://github.com/mvorisek/PrestaShop/pull/1/commits for upgrade steps of PrestaShop itself:
![image](https://user-images.githubusercontent.com/2228672/73122410-f5c85000-3f84-11ea-9b8e-d2946bf3a0c0.png)

**Comment by matks** [comment]
We need @eternoendless opinion on this. This is a major technical change, he is the lead developer so it must happen under his approval 😊

**Comment by eternoendless** [comment]
I think it's hard for PrestaShop to support multiple major versions of Symfony and Twig at the same time, all while keeping breaking changes at the minimum.

**Comment by PierreRambaud** [comment]
We also keep in mind PrestaShop is an application and not a library, we are building a zip containing all our dependencies, if we consider people are able to change Symfony's packages versions, it will be impossible for us to support everything at the same time :sob: 

I'm in favor of closing this issue, we will increase dependencies when it will be possible and needed.

**Comment by eternoendless** [comment]
Yeah, that's also why we distribute lock files as well. Thanks for enthusiasm @mvorisek but dependency versions must be bumped individually and carefully.
