### ISSUE TITLE
Impossible to change default attribute

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#17315]
**Describe the bug**
Default attribute is not saved correctly.

**To Reproduce**
1. Go to catalog > products in admin
2. Click on combinations/attributes tab (Assuming you already have multiple attributes)
3. Try to change default attribute by checking second radio button
4. Default attribute is not set to second attribute

(In ajax save, "attribute_default" is set to 1 for every combination 😕)

**Screenshots**
https://www.dropbox.com/s/spjddcuvzq0ngwt/Capture%20d%27%C3%A9cran%202020-01-23%2010.49.22.png?dl=0

**Additional information**
PrestaShop version: 1.7.3.2
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Daaaaad** [comment]
Hi @khouloudbelguith,

I think you have everything in hand to reproduce the error : 
- There are no errors in PHP error log nor javascript console (I would have reported them)
- I already specified the version of PrestaShop and already have addressed the problem (see my capture)

**Comment by khouloudbelguith** [comment]
@Daaaaad, in my case, I did not manage to reproduce the issue with PS1.7.6.3
I attached a screen record
https://drive.google.com/file/d/18PZI1kvmqiVxq8MKllDvp97Mf0k80iuA/view
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Daaaaad** [comment]
My bad @khouloudbelguith, sorry... I was mistaken: 

On FO when you choose a combination, the URL change and contains the chosen combination ID. That was the reason why I could not see default attribute change.

Have a great weekend! ;)

**Comment by khouloudbelguith** [comment]
@Daaaaad, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
