### ISSUE TITLE
Error while trying to preview or view an order of a deleted customer

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17311]
**Describe the bug**
Error while trying to preview or view an order of a deleted customer

**To Reproduce**
1. Go to BO > Customers > Customers
2. Delete John Doe
3. Go on the migrated order list
4. Try to click on the preview, nothing is happening
5. Try to view the order 
6. See errors

**Screenshots**
**Error in the console after clicking on the preview**
![capture d'écran_2301](https://user-images.githubusercontent.com/13449658/72968832-9cb1be00-3dc4-11ea-9910-38f9aa9d27fd.png)

**Error after clicking on view**
![capture d'écran_2299](https://user-images.githubusercontent.com/13449658/72968231-5dcf3880-3dc3-11ea-8eb7-fb95b8cc745b.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by MatShir** [comment]
What use happens if it is deleted?

**Comment by MatShir** [comment]
**With gdpr module:**
![image](https://user-images.githubusercontent.com/43613217/73345943-47beed80-4285-11ea-8bb0-0f9bd48461fd.png)

**Without gdpr module**
![image](https://user-images.githubusercontent.com/43613217/73346468-2f9b9e00-4286-11ea-8ce3-8d999e56aebe.png)
An errour occurs when we try to change the address. So we should remove the drop list and button to change the address.
Need to test if I try add the uer back what happened 

**Order list**
![image](https://user-images.githubusercontent.com/43613217/73346213-c61b8f80-4285-11ea-880c-aacc508038de.png)

The order is still accessible and visible.

**Comment by sam-pires** [comment]
1. Make sure the customer is well saved in the order when we delete a customer.
2. Test the behavior when the deletion is done via the GDPR module
3. TBS


⚠️ Wait for the work on the Order pages to be done before working on this one

**Comment by MatShir** [comment]
### **Specs:**
When an customer is deleted, all the customer information is removed except for the addresses that are still linked to the order. So the edit, change the address button and the private note should be removed. The name of the customer will be replaced by "Deleted customer".

### **Screenshots**
**Order customer panel**
![image](https://user-images.githubusercontent.com/43613217/73866780-b97ad680-4845-11ea-9c1c-07f99958098f.png)


**Order header**
![image](https://user-images.githubusercontent.com/43613217/73860936-a0b9f300-483c-11ea-9049-527032f26768.png)

**Order list**
![image](https://user-images.githubusercontent.com/43613217/73861598-8b919400-483d-11ea-94ec-b03bb83e0e76.png)
