### ISSUE TITLE
Update license headers for 2020 for PS 1.7.7

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17314]
I write this issue so we dont forget about it. We need to update all license headers for 2020 (right now, they are set for 2019).

However we might change how we handle dates into license headers, see https://github.com/PrestaShop/PrestaShop/issues/17007.

So we need to
- wait for answer for https://github.com/PrestaShop/PrestaShop/issues/17007 to come up
- then apply this answer for 1.7.7

This is mandatory for the 1.7.7.0 release.

**Comment by sam-pires** [comment]
Waiting for legal team answer for the moment.

**Comment by matks** [comment]
No answer, so we update all filers following our usual system. See https://github.com/PrestaShop/PrestaShop/pull/17565

**Comment by matks** [comment]
The same question is valid for all native modules. When we do release them, do we need to update all license headers ?

**Comment by matks** [comment]
Done in https://github.com/PrestaShop/PrestaShop/pull/17579 for year 2020. Hopefully we'll have an answer soon for the modules 😄
