### ISSUE TITLE
Error 403 - Zendesk

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#17321]
Hi,

We are having trouble saving the Zendesk module settings. We have already spoken with the developers of the module which they say the problem is not theirs but the Prestashop's. Can you see what's going on?

I put all the data from the Zendesk account and when I save it, the following error appears:

1. Go to 'modules/zendesk'
2. Click on 'configuration'
3. Configure the parameters and click save

http://prntscr.com/p89hvl

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment]
Hi @JorgeNogueiraLFMPro,

As it's a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com [account](https://addons.prestashop.com/fr/contactez-nous?id_product=23617), they are the only ones to help you with it.
Thanks!

**Comment by matks** [comment]
> We are having trouble saving the Zendesk module settings. We have already spoken with the developers of the module which they say the problem is not theirs but the Prestashop's. Can you see what's going on?

There might be an issue in PrestaShop code, however
- we have no access to the Zendesk module, so we cannot test it
- "they say it's an issue in prestashop" is very vague and very unclear
- module developers are supposed to create modules that work with prestashop 😅 how come they build and sell something that does not work ? it's very strange to say that (maybe they mean something customized into your shop is the issue? )

We will be happy to check if something can work if they reach us or if you can provide a more detailed answer. Without one of these items, there's nothing we can do.
