### ISSUE TITLE
Free shipping voucher changes taxes total on product 

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#17333]
We created a voucher for free shipping (with no coupon code) after a specific amount.
Our store is displaying all the prices tax excluded (in Canada).
Order total and total paid is correct, but on the invoice, tax breakdown is wrong.

In order->getProductTaxesDetails method, it will split the total_shipping_tax_excl from all the product unit price to calculate the tax breakdown. And will try to readd the tax of the shipping with Tools::spreadAmount. It could work if you only have one tax, but does not give accurate result in Canada, with 2 levels of tax.

*****************************Additional information**
PrestaShop version: 1.7.4.0

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

I followed these steps:
1. Create Tax1=20% & Tax2=10%
2. Create a tax rule one after another with Tax1 & Tax2
3. Create a cart rule with free shipping with Minimum amount  =12 Tax included
4. Create a product with this Tax rule created (Tax excluded = 20 euro => Tax included = 26.4 Euro)
5. Go to to the the BO => Orders => Invoices => Enable "tax breakdown"
6. Go to the FO => Create an order with the last product created
7. Go to the BO => Order => Edit the status of the last order to payment accepted to generate the invoice
8. View the invoice
![image](https://user-images.githubusercontent.com/16067358/73055065-3c864f00-3e8c-11ea-8f98-ad4ca094ffa1.png)

The tax breakdown is incorrect in this case?

Thanks!

**Comment by cedricfontaine** [comment]
No it seems correct. Could you try not with tax rule one after another, but Combine.

**Comment by khouloudbelguith** [comment]
@cedricfontaine, I tried with Combine & it is OK also.
![image](https://user-images.githubusercontent.com/16067358/73369291-a5b5fa00-42b2-11ea-8ca1-66e5e9940ef7.png)

Thanks!

**Comment by cedricfontaine** [comment]
Ok so it seems to be fixed ?

**Comment by khouloudbelguith** [comment]
@cedricfontaine, I tested the last release 1.7.6.3.
So, it seems to be fixed.
Can we close the issue?
Thanks!

**Comment by cedricfontaine** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@cedricfontaine, thanks!
Feel free to open a new one when needed.

Thanks!
