### ISSUE TITLE
Update/remove platform to PHP 7.1.3 in all modules before PrestaShop 1.7.7 is released

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17352]
Example: https://github.com/PrestaShop/productcomments/blob/acd28a927fb95023f2c12075012ab916d934ce41/composer.json#L36

Important as this override is used also for tests.

Preferred way is to remove platform from all modules and setup proper PHP 7.1 - 7.3 CI tests.

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
I don't see any reason to do it. Our modules are also compatible with old PrestaShop instances. This is why we keep the compatibility with PHP 5.6 when it's possible.
