### ISSUE TITLE
Product features without key get Duplicated on refresh

### ISSUE THREAD

**Issue by JeremiePRepo** [PrestaShop/PrestaShop#17350]
**Describe the bug**
Occasionnaly product features without key get duplicated when you refresh page after validating changes.

**To Reproduce**
1. Go to a product page in back office
2. Add a feature, without key and a custom value
3. Save
4. Refresh the page with F5 or with the browser button
5. If the product feature get not duplicated, repeat.

**Screenshots**
See video capture here : [https://www.loom.com/share/e4d4fcc89a2f4137b67dd5602403281c](https://www.loom.com/share/e4d4fcc89a2f4137b67dd5602403281c)

**Additional information**
PrestaShop version: 1.7.6.3, 1.7.6.2, maybe older releases
PHP version: 7.2.24

**Comment by khouloudbelguith** [comment]
Hi @Jewem,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9680
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9680

**Comment by JeremiePRepo** [comment]
Ok, sorry and ty
