### ISSUE TITLE
Can't edit order shipping for deleted/edited carriers

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#17355]
**Describe the bug**
If order was placed using carrier that is no longer available (`deleted` set to `1` in `carrier` table) its shipping can't be edited in BO (e.g. to add a tracking number). BO silently chooses the first available carrier as the new one.

**To Reproduce**
1. FO: Add new order
2. BO: Modify or delete carrier that was chosen by a customer (in step 1)
3. BO: Navigate to order and click "Edit" next to shipping method

You can't simply add tracking number without changing a carrier. Moreover it's very easy to miss that PrestaShop has silently selected a new carrier for you!

**Screenshots**
![carrier](https://user-images.githubusercontent.com/452972/73122789-0f6b9680-3f89-11ea-8f54-b6c9da849441.png)

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @rmilecki,

There are two cases:
1. If the carrier selected by the customer has deleted or disabled => this behavior `"BO should still allow adding tracking number *without forcing BO user to select a new carrier."` it is incorrect.
How you can add a tracking number to a carrier deleted( doesn't exist anymore)? => this is confusing for the employees.

2. If the carrier selected by the customer has edited => the carrier is still displayed & you can add the tracking number.

I attached a screen record
https://drive.google.com/file/d/1m2xUOc2Wrslgp_2_F_P4FDK1bYBTYgWb/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @rmilecki,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
