### ISSUE TITLE
Breaking compatibility changes should be easily identifiable in Changelog

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17370]
Today, breaking compatibility changes in new versions are identified:
- by looking at the release note
- by checking PRs with dedicated labels

But they cannot be easily found by looking at changelog. This should be modified as developers usually check the changelog to look for BC breaks.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
@eternoendless May I create a Pull Request aiming for our Changelog Writer tool to allow this ?

**Comment by PierreRambaud** [comment]
@matks I agree to improve the ChangeLog Writer tool to improve it :)

**Comment by eternoendless** [comment]
Yep, just do it

**Comment by matks** [comment]
ChangeLog tool has been updated. Future changelogs will highlight BC breaks :)
