### ISSUE TITLE
Exception in the Pages Configuration page - Theme & Logo

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17374]
**Describe the bug**
In the BO => Design => Theme & Logo page => Pages Configuration Tab => an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/73178156-f8f04700-4110-11ea-8c32-0c3827e25e7d.png)

PS1.7.6.3 & Theme Customization module v1.1.0 =>ok
https://drive.google.com/file/d/1RnGWIPD9JRXvPpXJ_GbRd_KobMP2yco7/view

**To Reproduce**
1. Go to  BO => Design => Theme & Logo page => Pages Configuration Tab 
2. See error

**Additional information**
PrestaShop version: 1.7.7.x branch
PHP version: 7.1
Theme Customization module v1.1.0

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_themecusto#20
