### ISSUE TITLE
[BO] JS error in tinymce on "add new supplier" page

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#17376]
**Describe the bug**
When going on the "add a supplier page" (the page with the form to add a supplier), we sometimes have a javascript error related to tinymce.

It's not all the time, I had to refresh the page at least 20 times to reproduce this 😓 

This is blocking some automated tests made by the QA team, so this issue should be taken seriously.

**Steps to reproduce the behavior:**
1. Go to **admin-dev/sell/catalog/suppliers/new**
2. Check for the error in the console
3. Refresh until you have the error

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/1784781/73192654-a1120a00-4129-11ea-9a07-edf9a36d1afb.png)

**Additional information**
PrestaShop version: 1.7.7.x

**Comment by khouloudbelguith** [comment]
Same issue with 1.7.7.x

![image](https://user-images.githubusercontent.com/16067358/73195074-86419480-412d-11ea-966e-12b68db0d725.png)
ps1.7.6.3 => OK
Thanks!

**Comment by NeOMakinG** [comment]
Impossible to debug this since we don't have source files of current tinymce and I was not able to build this version from the official TinyMCE repository, it should wait the upgrade of tinymce which is possibly breaking change for some modules (wdyt @eternoendless  @PierreRambaud  ?)

**Comment by colinegin** [comment]
@eternoendless @PierreRambaud any news about @NeOMakinG 's comment ? what should we do ?

**Comment by matks** [comment]
@eternoendless must tell us whether we can upgrade TinyMCE version in **migrated pages** . This would create a small BC but would fix a lot of issues related to TinyMCE, and as pages get migrated, this would fix them.

**Comment by Progi1984** [comment]
@NeOMakinG Could check that #17651 fixes this issue ?

**Comment by NeOMakinG** [comment]
It looks like #17651 fixed it :)

**Comment by NeOMakinG** [comment]
Feel free to open it again if you see the error!
