### ISSUE TITLE
Redirection to Add a new Address page instead of Edit Address page while editing the customer information - BO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17382]
**Describe the bug**
In the BO => Customers page => Click on "View" button to show the Information page of the customer "John Doe"
![image](https://user-images.githubusercontent.com/16067358/73258366-d5d39f00-41c5-11ea-8633-eaa3897b3b9b.png)
Try to edit any Address => redirection to a New Address page, after save => new address is added.

**To Reproduce**
1. Go to the BO => Customers page 
2. Click on the "View" button to show the Information page of the customer "John Doe"
3. Try to edit any Address
![image](https://user-images.githubusercontent.com/16067358/73258517-25b26600-41c6-11ea-9f66-01dda82ec5b1.png)
=> redirection to Add a new address page => save => an address is added to this customer.

It was ok with PS1.7.6.3: https://drive.google.com/file/d/1q3eqjMmkUbVS7IIA9hIzh5WZ4lEymfdM/view

**Screenshots**
https://drive.google.com/file/d/1Lig36aQOrYQ_lrvzuaQWP2y-8mGFjxlJ/view

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @Robin-Fischer-PS

**Comment by Progi1984** [comment]
Fixed in #17445
