### ISSUE TITLE
statsbestcustomers module doesn't return anything if visits are not logged

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17383]
**Describe the bug**
 if visits are not logged, best customers should be returned with total Money Spent

**To Reproduce**
1. Desactivate connection logging with PS_STATSDATA_CUSTOMER_PAGESVIEWS to false in configuration (statsdata module)
2. Empty connections table
3. Go to stats /Best customers
4. See error : no result

**Additional information**
PrestaShop version: all
PHP version: all
Module version: all

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

The module adds a list of the best customers to the Stats dashboard.3
The list of customers and not the list of visitors.
![image](https://user-images.githubusercontent.com/16067358/73261239-f6065c80-41cb-11ea-81c2-aadb416523b4.png)
https://drive.google.com/file/d/1xsH7doHGidzZ9qJsW_eI2Otq0Mfjon4q/view

Thanks to check & feedback.

**Comment by jf-viguier** [comment]
@khouloudbelguith yes, the module returns best customers but uses connection table in sql to return the number of visits. I'll do a PR

**Comment by jf-viguier** [comment]
Check my PR here https://github.com/PrestaShop/statsbestcustomers/pull/8

**Comment by khouloudbelguith** [comment]
@jf-viguier, 
>the module returns best customers but uses connection table in sql to return the number of visits

if the "Save page views for each customer" is disabled the number of visits is changed too.
https://drive.google.com/file/d/1Kl4iNctGeUh4frEniAazZ83eR7kdJndF/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Any news?

Thanks!

**Comment by jf-viguier** [comment]
@khouloudbelguith I've answered to review on my pr, are you waiting for something else ?

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/statsbestcustomers/pull/8

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thanks for your issue and your PR :slightly_smiling_face: 
It seems that your PR is already merged https://github.com/PrestaShop/statsbestcustomers/pull/16
It will be released with the next version BestCustomer v2.0.3

Thanks!
