### ISSUE TITLE
Exception on View order with a pack product

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17398]
**Describe the bug**
On migrated page, with an order containing a pack product, there is an exception error.

**To Reproduce**
1. Go to FO, create an order with a pack
2. Go to BO, view order (migrated page) : Error

**Screenshots**
![screencapture-localhost-ps177-admin-dev-index-php-sell-orders-orders-6-view-2020-01-29-11_02_05](https://user-images.githubusercontent.com/55688534/73347675-4ba03f00-4288-11ea-8e5d-c4f0b02a5d8d.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Issue not reproduced
https://drive.google.com/file/d/1T6RbFhwoR28Xke9oFVZ3K_4q_03Zc3XW/view

Thanks!
