### ISSUE TITLE
forgotten space in select html tag

### ISSUE THREAD

**Issue by elaugier** [PrestaShop/PrestaShop#17394]
Seem there is a bug on html generation with select tag. 

`<selectid="xxx">[...]</selectid="xxx">`
 instead of 
`<select id="xxx">[...]</select id="xxx">`

for example:
1. Go to 'Store Setting'
2. Click on 'Products'
3. Scroll down to 'Pagination'

**Screenshots**
![Screenshot Error](https://i.paste.pics/603ed22131feb413507bacda4909f85e.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.4

**Comment by JBWModules** [comment]
Your version is not compatible with PHP 7.4. - downgrade to 7.2

**Comment by khouloudbelguith** [comment]
Hi @elaugier,

I did not manage to reproduce the issue with PS1.7.6.3
![image](https://user-images.githubusercontent.com/16067358/73338752-949bc780-4277-11ea-8b55-5f1595081987.png)

PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by elaugier** [comment]
thank you for all informations :)
Indeed, Bug solved with PHP 7.2 rollback.

**Comment by khouloudbelguith** [comment]
@elaugier,  great!
Feel free to open a new one when needed.

Thanks!
