### ISSUE TITLE
The pop up is not displayed when adding a new currency

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17397]
**Describe the bug**
In the BO => International => Localization => Currencies page, try to add a new currency, an error in the console is displayed
![image](https://user-images.githubusercontent.com/16067358/73342388-bf3d4e80-427e-11ea-8de4-05a631349d8c.png)
When you try to select a currency, the pop up is not displayed as in the branch 1.7.7.x
![image](https://user-images.githubusercontent.com/16067358/73342549-16432380-427f-11ea-8ac7-87f753a621fe.png)
Try to Click on save => see exception

**To Reproduce**
1. Go to the BO => International => Localization => Currencies page
2. Add a new currency => en error in the console
3. Select a currency 
4. See error: the pop up is not displayed
5. Complete all fields
5. Save
6. See error => the shop is completely broken
![image](https://user-images.githubusercontent.com/16067358/73342817-a2ede180-427f-11ea-89b1-20ea2b1899be.png)
PS:  => After a new install develop => this exception is not displayed anymore.
https://drive.google.com/file/d/1GX18DtRV_17jXJ8xXJSWdlhlkESZ4OE5/view

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by PululuK** [comment]
Hi @khouloudbelguith 
Can you add **1.7.7.x** label please ?
Thank you

**Comment by khouloudbelguith** [comment]
@PululuK, It is ok with branch 1.7.7.x
https://drive.google.com/file/d/1B1GrWDhxYqIjTqLegWxQPIKzMOucQ3oe/view

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17923
