### ISSUE TITLE
Items going out of list container

### ISSUE THREAD

**Issue by 21shadow** [PrestaShop/PrestaShop#17396]
items of select are going outside of its container
![error](https://user-images.githubusercontent.com/42492678/73326449-328f9200-4278-11ea-9f97-e69ca06aec96.png)

**Comment by JBWModules** [comment]
Are you using PHP 7.3?

**Comment by khouloudbelguith** [comment]
Hi @21shadow,

I did not manage to reproduce the issue with PS1.7.6.3
![image](https://user-images.githubusercontent.com/16067358/73338963-fd833f80-4277-11ea-94b8-74fce8204369.png)
What is the exact version PHP did you use?
If it is PHP7.3 or PHP7.4, PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks to check & feedback.

**Comment by 21shadow** [comment]
It worked
I was using php 7.4 
Thanks for explaining.

**Comment by khouloudbelguith** [comment]
@21shadow, great!
Feel free to open a new one when needed.

Thanks!
