### ISSUE TITLE
Prestashop on Apache + Nginx as proxy + Fast-CGI - Web Service API error 401

### ISSUE THREAD

**Issue by adi5497** [PrestaShop/PrestaShop#17392]
I'm trying to config a PrestaShop on VPS. Everything is working, despite one, web services API. When I'm trying to go https://example.com/api, web services ask me about auth key. After entering it into username field and leaving password blank, it works. But while I'm trying access to API via remote app I'm getting error 401 unauthorized. I know that it's server fault becaus on previous host everything worked fine. I'm useing Debian 9 and Apache 2+Nginx as proxy+PHP 7.0 with FastCGI

**Comment by khouloudbelguith** [comment]
Hi @adi5497,

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks for your understanding!
