### ISSUE TITLE
Reversed product sorting

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17400]
**Describe the bug**
Product sorting (by position) is reversed when `ps_facetedsearch` module is disabled.
Parameter in URL is `?order=product.position.desc` instead of `?order=product.position.asc`

**To Reproduce**
1. Disable module `ps_facetedsearch`
2. Go on category page
3. Sort by : **Name, A to Z**
4. Sort by : **Relevance**
5. See reversed product sorting

**Additional information**
PrestaShop version: 1.7.x

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2 & PS1.7.5.2.
The Position of the products is reversed.
https://drive.google.com/file/d/1gO0mKklp7a-f3ihgpkD_MwbxLCER2MXm/view
I’ll add this to the debug roadmap.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #17402
