### ISSUE TITLE
Switch 'Reorder' into 'Rearrange' in the products listing

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17412]
Hellooo! One small thing that could be nice, I don't know if this PR can handle this part: when you select a filter ('Stationery', for instance), a new column appears called 'Position' and it allows users to reorder their products. 'Reorder' in the sense of organizing them the way you want. Yet, the term is often misunderstood during translation and it is sometimes turned into 'Order again'. 

<img width="1525" alt="Capture d’écran 2019-08-26 à 12 25 40" src="https://user-images.githubusercontent.com/32565890/63684753-eb4f3200-c7fd-11e9-8c21-f93bba2c0396.png">

Could it be possible to change this wording and write it 'Rearrange' (which is, I think, more suitable to the notion of position) or 'Reorganize' instead of 'Reorder'? I hope it will allow a better understanding and a more accurate translation later.

cf. @marionf, @sarahdib

_Originally posted by @LouiseBonnard in https://github.com/PrestaShop/PrestaShop/pull/14267#issuecomment-524811268_

**Comment by colinegin** [comment]
@LouiseBonnard as it is a good first issue maybe we should not put in the backlog for 178 but let the new contributors handle it, wdyt ?

**Comment by LouiseBonnard** [comment]
@MatShir, friendly reminder for the products' listing! @Julievrz, for information.

**Comment by matks** [comment]
ping @JevgenijVisockij I guess it can be embedded in the migration of the page ? 😉

**Comment by JevgenijVisockij** [comment]
> ping @JevgenijVisockij I guess it can be embedded in the migration of the page ? wink

Of course, I see no reason it couldn't be

**Comment by hibatallahAouadni** [comment]
@MatShir I see that this feature is well implemented on 1.7.8.0:

![image](https://user-images.githubusercontent.com/23308427/155343137-fee2e210-f8b7-4e3c-bbc7-f20d0e75a96b.png)

So, shall we close the issue and change the milestone?

**Comment by MatShir** [comment]
Let's keep it open to be sure we don't miss it while migrating the page ;)

**Comment by kpodemski** [comment]
FYI: as for now, the sorting feature is missing on the new product list page

**Comment by MatShir** [comment]
Closing this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/32833
