### ISSUE TITLE
Cart not updated

### ISSUE THREAD

**Issue by magalupi** [PrestaShop/PrestaShop#17414]
Bonjour,

depuis quelques jours, le panier ne se met pas à jour. 
Lorsqu'un client choisi de mettre un produit dedans il ne se passe rien.
Il faut soit appuyer sur F5 soit cliquer sur son compte client pour que le panier s'actualise.
Si pas de compte, il n'y a pas la possibilité de mettre dans le panier.

Cela me pénalise lourdement, auriez vous une idée de la raison du problème?
Je suis sur le theme classic 1.0.0

D'avance merci.
 Marc DELPIT.
https://deco-cadres.fr/<!--

**Comment by khouloudbelguith** [comment]
Hi @magalupi,

In your BO => Modules => Module Manager page => search for the `ps_shoppingcart` module, click on the configure & check if the `Ajax cart` option is enabled or disabled?
![image](https://user-images.githubusercontent.com/16067358/73372416-7655bc00-42b7-11ea-9935-faf9f599d4a3.png)

Thanks!

**Comment by magalupi** [comment]
hi khouloudbelguith
the Ajax cart option is enabled

![image](https://user-images.githubusercontent.com/60297887/73373812-81115080-42b9-11ea-95a9-b084708eb20b.png)

**Comment by khouloudbelguith** [comment]
@magalupi, what is the exact version of PrestaShop did you use? and what is the exact version of the `ps_shoppingcart` module did you use?

Thanks!

**Comment by magalupi** [comment]
Prestashop 1.7.1.2    ps_shopping cart  v2.0.3

**Comment by khouloudbelguith** [comment]
@magalupi, I did not manage to reproduce the issue with PS1.7.6.3 & ps_shoppingcart module v2.0.3.
I attached a screen record
https://drive.google.com/file/d/1lktYBzVXs7GZRhgyo4CLEFcrj6em2UIO/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by magalupi** [comment]
I try to give you all that
Prestashop 1.7.1.2
Informations du serveur : Linux #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
Version du logiciel serveur : Apache/2.4.25 (Debian)
Version de PHP : 7.1.32-1+0~20190902.23+debian9~1.gbp9d1be7

I have cleared the cache
Navigateur google chrome cache cleared to.

I send you a video in mail.

**Comment by khouloudbelguith** [comment]
@magalupi,

>I send you a video in mail.

Sorry, I didn't receive any screen record.
My address mail: khouloud.belguith@prestashop.com
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@magalupi, the screen record is well received.
In my case, it is OK.
As I said before, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by magalupi** [comment]
Hi khouloudbelguith,

debog mode,

Notice à la ligne 227 du fichier /var/www/production/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: advice

Notice à la ligne 228 du fichier /var/www/production/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: link_advice

and I think that is the php error log...

1157-tableau-contemporain-abstrait-bleu-50x150.html:1171 GET https://2018.deco-cadres.fr/img/cms/sur-mesure.jpg net::ERR_CERT_COMMON_NAME_INVALID
JsWidget.js:98 window loaded
JsWidget.js:114 jQuery defined
JsWidget.js:116 call 2
bottom-62b933.js:259 Uncaught TypeError: Cannot read property 'resp' of undefined
    at Object.<anonymous> (bottom-62b933.js:259)
    at Object.n.emit (bottom-62b933.js:258)
    at Object.<anonymous> (bottom-62b933.js:215)
    at Object.<anonymous> (bottom-62b933.js:70)
    at fire (bottom-62b933.js:69)
    at Object.fireWith [as resolveWith] (bottom-62b933.js:70)
    at done (bottom-62b933.js:194)
    at XMLHttpRequest.<anonymous> (bottom-62b933.js:204)
(anonymous) @ bottom-62b933.js:259
n.emit @ bottom-62b933.js:258
(anonymous) @ bottom-62b933.js:215
(anonymous) @ bottom-62b933.js:70
fire @ bottom-62b933.js:69
fireWith @ bottom-62b933.js:70
done @ bottom-62b933.js:194
(anonymous) @ bottom-62b933.js:204
load (async)
send @ bottom-62b933.js:204
ajax @ bottom-62b933.js:188
jQuery.<computed> @ bottom-62b933.js:197
(anonymous) @ bottom-62b933.js:215
n.emit @ bottom-62b933.js:258
(anonymous) @ bottom-62b933.js:216
(anonymous) @ bottom-62b933.js:70
fire @ bottom-62b933.js:69
fireWith @ bottom-62b933.js:70
done @ bottom-62b933.js:194
(anonymous) @ bottom-62b933.js:204
load (async)
send @ bottom-62b933.js:204
ajax @ bottom-62b933.js:188
jQuery.<computed> @ bottom-62b933.js:197
(anonymous) @ bottom-62b933.js:216
dispatch @ bottom-62b933.js:100
elemData.handle @ bottom-62b933.js:92

Thank's before

**Comment by khouloudbelguith** [comment]
@magalupi,

>Notice à la ligne 227 du fichier /var/www/production/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: advice

- What is the exact version of the psaddonsconnect module did you use?
- Have you added a new module?
- Have you written/changed a module?
- Have you edited a tpl file?
- Have you changed the js file content of your theme?

Thanks!

**Comment by magalupi** [comment]
I don't know when the problem started, but yes I installed 2 modules recently, Sendinblue, and another made to sell custom.
I don't find the psaddonsconnect
Is it possible that I give you my credentials, so that you log into my back office, I don't speak Hebrew in fact

**Comment by khouloudbelguith** [comment]
@magalupi,
>Is it possible that I give you my credentials

Sorry, it is not possible, but, I'm trying to help you to find the exact problem, we must first try to reproduce your issue.
Thanks for your understanding!

>I don't find the psaddonsconnect

Here's the exact module
![image](https://user-images.githubusercontent.com/16067358/73451912-fb4cde00-4368-11ea-9d26-bd204cc98050.png)

You need to enable debug mode in your store and debug request which is sent for the product add in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. add the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

To turn on the Debug mode on PrestaShop 1.7, follow these steps:

1. Got to Advanced Parameters > Performance
2. In the Debug Mode section, set “Debug Mode” to “Yes”.
3. Click the “Save” button.

Thanks!

**Comment by magalupi** [comment]
OK thank you, I understand.
the version of psaddonsconnect is v1.0.1

**Comment by khouloudbelguith** [comment]
@magalupi, is it possible to upgrade your `psaddonsconnect` module?

Thanks to follow these steps:
You need to enable debug mode in your store and debug request which is sent for the product add in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. add the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Waiting for your feedback.

Thanks!

**Comment by magalupi** [comment]
Im  working on the debug mode
This is when im on the product

![image](https://user-images.githubusercontent.com/60297887/73462418-1117ce80-437c-11ea-94ed-933a955682d0.png)

And when i clic on put in basket
![image](https://user-images.githubusercontent.com/60297887/73462605-60f69580-437c-11ea-8929-d9810cfdf153.png)

**Comment by magalupi** [comment]
![image](https://user-images.githubusercontent.com/60297887/73462849-b29f2000-437c-11ea-8ae1-fb76f20491dc.png)

**Comment by khouloudbelguith** [comment]
@magalupi,
Have you edited a .tpl file?
Have you changed the js file content of your theme?

Thanks!

**Comment by magalupi** [comment]
I can't upgrade it 
![image](https://user-images.githubusercontent.com/60297887/73463125-090c5e80-437d-11ea-8b2e-72006305a56c.png)

**Comment by khouloudbelguith** [comment]
@magalupi,

Have you edited a .tpl file?
Have you changed the js file content of your theme?

Thanks!

**Comment by magalupi** [comment]
I did not change anything on .tpl and js file

**Comment by khouloudbelguith** [comment]
@magalup, you have an error js your theme.
Does this issue occur after installing the new custom module?

Thanks!

**Comment by magalupi** [comment]
I do not know, I noticed the problem in early January, the module was installed in November, maybe that is the reason

**Comment by khouloudbelguith** [comment]
@magalupi, could you please try to re-install the ps_shoppingcart module, check & feedback.

Thanks!

**Comment by magalupi** [comment]
ok i re-install the ps_shoppingcart module 
I disable the custom module but it doesn't change anything

**Comment by magalupi** [comment]
re-install the ps_shoppingcart module don't change anything

**Comment by Zakhar023** [comment]
> Bonjour, alors si jamais,  je viens de faire une mise à jour vers 1.7.6.3 cela règle le problème dans mon cas (deux jours que je bloquais dessus)... J'avais également la Prestashop 1.7.1.2 ps_shopping cart v2.0.3.

Cordialement,
Z

**Comment by khouloudbelguith** [comment]
@magalupi, I did not manage to reproduce the issue with PS1.7.1.2 & ps_shppingcart module v2.0.3.
https://drive.google.com/file/d/1y7jnBjja4z6zpg7xsq9MHHf7jzsk6BJ_/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
