### ISSUE TITLE
PS 1.7.5.2 Slow Back End Page 

### ISSUE THREAD

**Issue by arditec** [PrestaShop/PrestaShop#17411]
**Describe the bug**
We have a prestashop in version 1.7.5.2 takes a long time to load certain sections of the backoffice. For example, when creating a new product it takes between 15 and 20 seconds to load.
We have reviewed the server that hosts it and resources are fine (50% memory, CPU between 0-1%, sufficient disk space), we have updated the modules and made several tests with different cache configurations and the problem persists.

When we activate the debug mode, there is a parameter “config” showing times of 13000ms, which seems to be the reason of the slow response. I have searched forums but I have not found anything that explains the function of this "config".
I’m attaching the report, I’d appreciate if someone could help me.
Thank you.

**Screenshots**
![prestashop_debug](https://user-images.githubusercontent.com/60429653/73366728-b6fd0780-42ae-11ea-926b-95f40ebada86.jpg)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.27

**Comment by khouloudbelguith** [comment]
Hi @arditec,

Thanks to follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

Also, you can check the `ps_quest` table if it has a lot of data.

Thanks!

**Comment by arditec** [comment]
Hi,

We have the configuration of the cache as you indicate.

I can't find the "statsdata", can you tell me more?

Can you tell me what the debug refers to with "config"?

Thank you.

**Comment by khouloudbelguith** [comment]
@arditec,

>I can't find the "statsdata", can you tell me more?

![image](https://user-images.githubusercontent.com/16067358/73670498-9adfd880-46a9-11ea-925e-fe5d69deab60.png)

>Can you tell me what the debug refers to with "config"?

Profiling for hooks is broken as reported here: #9659, here's the PR: #16231 to fix the issue.
But it can help us to get information about the time needed to run queries.

Thanks!

**Comment by arditec** [comment]
Hi,

Is this?
![stats-web](https://user-images.githubusercontent.com/60429653/73673136-6de1f480-46ae-11ea-869c-5594ae515661.jpg)

I mean this "config":
![debug-web](https://user-images.githubusercontent.com/60429653/73673309-b4cfea00-46ae-11ea-906e-848df1277350.jpg)

Thanks for your help.

**Comment by khouloudbelguith** [comment]
@arditec,

>Is this?

No, this is the Stats Dashboard module.
I mean the `Data mining for statistics` module.
![image](https://user-images.githubusercontent.com/16067358/73732692-ea221980-473a-11ea-9f99-cca9e9ffef5b.png)

Could you please try to click on the ObjectModel instances link & provide me a screenshot
![image](https://user-images.githubusercontent.com/16067358/73735859-30c64280-4740-11ea-82e1-4f441d736f4b.png)
![image](https://user-images.githubusercontent.com/16067358/73735929-476c9980-4740-11ea-90e7-016983735e97.png)

Thanks!

**Comment by arditec** [comment]
Hi @khouloudbelguith,

> No, this is the Stats Dashboard module. I mean the Data mining for statistics module.

The statsdata module is not installed:
![statsdata](https://user-images.githubusercontent.com/60429653/73741075-cca87c00-4749-11ea-9aa6-1ee6d77f1614.jpg)

Should I install it?

> Could you please try to click on the ObjectModel instances link & provide me a screenshot

![objectmodel](https://user-images.githubusercontent.com/60429653/73741224-16916200-474a-11ea-85eb-50f359158552.jpg)

Thanks!

**Comment by khouloudbelguith** [comment]
@arditec,

>Should I install it?

This module must be enabled if you want to use statistics only.

Did you check the ps_guest table if it has a lot of data?

For information, in debug mode, the compiler emits debug symbols for all variables and compiles the code as-is. In release mode some optimizations are included:

- unused variables do not get compiled at all
- some loop variables are taken out of the loop by the compiler if they are proven to be invariants
- code written under #debug directive is not included etc.

Thanks!

**Comment by arditec** [comment]
@khouloudbelguith,

> Did you check the ps_quest table if it has a lot of data?

The "ps_quest" table does not exist in the database, is it possible?
![ps_quest](https://user-images.githubusercontent.com/60429653/73757531-a266b680-4769-11ea-8808-703f657af96a.jpg)

This is a capture of the tables sorted by size:
![tablas](https://user-images.githubusercontent.com/60429653/73759280-02f6f300-476c-11ea-95c9-ea04bc1c352c.jpg)

Thanks

**Comment by khouloudbelguith** [comment]
@arditec,

sorry, it is `ps_guest`.

Thanks!

**Comment by arditec** [comment]
@khouloudbelguith,

Ok, "ps_guest" is currently empty.

In this database there are two different table prefixes "acd_" and "acs_". Can the problem be related to this?

Thanks

**Comment by khouloudbelguith** [comment]
@arditec, how did you get different prefix?
Did you make new install with the same database, you just changed the prefix?

Thanks!

**Comment by arditec** [comment]
@khouloudbelguith,

I do not know, this prestashop it was not installed by us...

Thanks

**Comment by khouloudbelguith** [comment]
@arditec, in your file Project_folder/app/config/parameters.php, check the exact prefix used in your case.

Thanks!

**Comment by arditec** [comment]
@khouloudbelguith,

>in your file Project_folder/app/config/parameters.php, check the exact prefix used in your case

'database_prefix' => 'acd_'

Thanks

**Comment by khouloudbelguith** [comment]
@arditec, `acd_` this is the prefix used in your case.

Thanks!

**Comment by khouloudbelguith** [comment]
@arditec, in your database, all tables are duplicated?

Thanks!

**Comment by arditec** [comment]
@khouloudbelguith,

I think all native prestashop tables are duplicated. "acd_" has some more

Thanks

**Comment by khouloudbelguith** [comment]
@arditec, I think those duplicated tables have an effect on your performance.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @arditec,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
