### ISSUE TITLE
404 error when saving my email translation

### ISSUE THREAD

**Issue by qtrompeau** [PrestaShop/PrestaShop#17429]
**Describe the bug**
Hi,
After modifying email translation, when i try to save i get a 404 error.

**To Reproduce**
Go to 'BO > International > Translations'
Click on 'Email translations > body > "theme" (evolution) > Français
Scroll down to 'Save or Save and stay'
See error
**Screenshots**
https://drive.google.com/file/d/1HNcvrQ3x6MfDZefkDxvs2Qu2RxWbe3Bz/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.26

Thanks

**Comment by khouloudbelguith** [comment]
Hi @qtrompeau,

I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1YPQ5UPdV38aFg1Wn5per7MkJCXI4qfYl/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by qtrompeau** [comment]
Hello,
Here's the PHP error log. 
https://drive.google.com/file/d/1YB8UuiPbUgDGyt12Ih8F7yX7XQ8-PxsT/view?usp=sharing

I don't know what you're expecting exactly for the debug mode report, here's a video.
https://drive.google.com/file/d/1CTJkLCVvw-Q_b0QIV2iJRrBO6mUMbQTg/view?usp=sharing

Thanks for your help

**Comment by khouloudbelguith** [comment]
@qtrompeau,

>Link to database cannot be established: SQLSTATE[HY000] [1203] User g***********a already has more than 'max_user_connections' active connections at line 127 in file classes/db/DbPDO.php

That means that the specific database user has already used up all the concurrent connections at that moment and more cannot be processed.
The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration
You need to increase your `max_user_connections` (https://dev.mysql.com/doc/refman/8.0/en/user-resources.html)

>I don't know what you're expecting exactly for the debug mode report

When debug mode is enabled, try to translate your email template => it could display some exceptions.

Thanks!

**Comment by qtrompeau** [comment]
Here's the video of the debug mode report (you'll have to download it for a good quality)
https://drive.google.com/open?id=1bDza2QB28UdHP9wSW-XgdVh9DyQgV-2A

I'll do these changes in MySQL configuration. I'll let you know

**Comment by khouloudbelguith** [comment]
@qtrompeau, thanks!
No, there is no exception when translation the emails.

>I'll do these changes in MySQL configuration. I'll let you know

Waiting for your feedback.

Thanks!

**Comment by qtrompeau** [comment]
I found this too in my php error logs, maybe it could be helpful to us.
https://drive.google.com/open?id=1O-iClfqOEZrFclxAgW6GONFnNA7mFVpJ

**Comment by khouloudbelguith** [comment]
@qtrompeau,

>"Attempted to call function "mcrypt_get_iv_size"

mcrypt is not installed in your server, thanks to install it.

Did you use the evolution theme?

Thanks!

**Comment by qtrompeau** [comment]
Okay i'll. Yes i do.

Thanks

**Comment by khouloudbelguith** [comment]
@qtrompeau,

>2020-01-09 11:59:28] request.CRITICAL: Uncaught PHP Exception PrestaShopException: "[ThemeRepository] Theme configuration file not found for theme at `/home/situx/developpement.situx.fr/themes/evolution/config/theme.yml`." at /home/situx/developpement.situx.fr/src/Core/Addon/Theme/ThemeRepository.php line 145 {"exception":"[object] (PrestaShopException(code: 0): [ThemeRepository] Theme configuration file not found for theme at `/home/situx/developpement.situx.fr/themes/evolution/config/theme.yml`. at /home/situx/developpement.situx.fr/src/Core/Addon/Theme/ThemeRepository.php:145)"} []

This error is related to your theme.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by qtrompeau** [comment]
Hello,

Here's the answer of my theme author :
https://drive.google.com/file/d/1MPu69COfJnPlh-OCexaulT5DnYN2z8nF/view?usp=sharing

Thanks

**Comment by espacious** [comment]
Same problem here. Any new info on how to resolve?

**Comment by khouloudbelguith** [comment]
@qtrompeau, Could you please provide me your theme to test it.
This is a public space.
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by espacious** [comment]
Prestashop 1.7.6.2
Warehouse Version 4.3.2
I will try to provide the .zip of theme

**Comment by khouloudbelguith** [comment]
@espacious,
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by espacious** [comment]
I sent you an email with link to the theme and dev.log.
Thanks.

**Comment by khouloudbelguith** [comment]
@espacious, thanks!
I will check & feedback.

**Comment by qtrompeau** [comment]
I sent you my theme too. Thanks

**Comment by qtrompeau** [comment]
I encouter the same issue while using classic theme.

**Comment by khouloudbelguith** [comment]
@qtrompeau, I tried with the classic theme & your theme & it is OK
https://drive.google.com/file/d/1zQC_M4-J1sLs4954g33HdpNvcZTXFWJQ/view
Could you please check if this file `/home/situx/developpement.situx.fr/themes/evolution/config/theme.yml` exists in your folder.

Thanks!

**Comment by khouloudbelguith** [comment]
@espacious, you provided me a lot of folders, what is the exact name of the theme folder?
Is it `theme_4_3_2`?

Thanks!

**Comment by qtrompeau** [comment]
Yes he exists. And he's not blank

**Comment by khouloudbelguith** [comment]
@espacious, I tried with your theme & it is OK
https://drive.google.com/file/d/1W8e7pGjn-Ah7hiwdxyQmwtWZ0EkR_9a7/view

@qtrompeau, I tried with PS1.7.6.2 & it is ok
https://drive.google.com/file/d/1dNr8jdhHNeYgcc7FRVH3Z5WQx_4VxwLu/view

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by espacious** [comment]
> @espacious, you provided me a lot of folders, what is the exact name of the theme folder?
> Is it `theme_4_3_2`?
> 
> Thanks!

Yes should be that one.
Also my theme has the theme.yml intact.
But you are testing on 1.7.6.3, we are on 1.7.6.2 if matters.

**Comment by khouloudbelguith** [comment]
@espacious, yes tested with PS1.7.6.2 & it is ok as I said previously.

Thanks!

**Comment by espacious** [comment]
@khouloudbelguith @qtrompeau i think i found the problem.
Disabling the "ModSecurity" in my Cpanel resolves the issue.
I suggest to reenable "ModSecurity" once you finished translating.
Or better is there a way to disable joust part of "ModSecurity" ?
