### ISSUE TITLE
Specific prices are deleted on manual order add from code

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#17427]
I had an issue while I was creating order manually from code. I was creating order without cart and by default id_cart is 0 in new Order object. After calling add function to insert an order all specific prices were deleted. I found out that after order add function calls SpecificPrice class method deleteByIdCart which in my case id_cart was 0 and because of that all specific prices were deleted. I know that I should not create an order without cart but in my opinion there should also be a check if id_cart > 0 and only then delete cart by id.

**Comment by khouloudbelguith** [comment]
Hi @zapper,

Thanks for your report.
Could you please add steps to reproduce the issue in a new comment.
>I was creating order manually from code

Did you use a custom module?

Thanks to provide the script added & created to reproduce the issue.

Thanks!

**Comment by lukaslau** [comment]
It was my own custom script.

To reproduce the issue just add a bunch of specific prices for few products. Then just create an order executing this code (you need to change few missing vars depending on your demo version).

After calling add function specific prices gets deleted.

$newOrder = new Order();
$newOrder->id_customer = 1;
$newOrder->id_shop = 1;
$newOrder->id_shop_group = 1;
$newOrder->id_address_delivery = $id_address;
$newOrder->id_address_invoice = $id_address;
$newOrder->id_lang = 1;
$newOrder->id_cart = 0;
$newOrder->id_carrier = $id_carrier;
$newOrder->id_currency = $id_currency;
$newOrder->round_mode = 2;
$newOrder->round_type = 2;
$newOrder->conversion_rate = 1.000000;
$newOrder->recyclable = 0;
$newOrder->gift = 0;
$newOrder->carrier_tax_rate = 21.00;
$newOrder->date_add = date('Y-m-d H:i:s');
$newOrder->current_state = 10;
$newOrder->secure_key = $secure_key;
$newOrder->reference = Order::generateReference();
$newOrder->payment = 'Bank wire';
$newOrder->module = 'ps_wirepayment';
$newOrder->round_mode = Configuration::get('PS_PRICE_ROUND_MODE');
$newOrder->round_type = Configuration::get('PS_ROUND_TYPE');
$newOrder->invoice_date = '0000-00-00 00:00:00';
$newOrder->delivery_date = '0000-00-00 00:00:00';
$newOrder->total_paid_real = 0;
$newOrder->total_wrapping_tax_excl = 0;
$newOrder->total_wrapping_tax_incl = 0;
$newOrder->total_wrapping = 0;
$newOrder->total_shipping_tax_excl = 0;
$newOrder->total_shipping_tax_incl = 0;
$newOrder->total_shipping = 0;
$newOrder->total_products = 0;
$newOrder->total_products_wt = 0;
$newOrder->total_discounts_tax_excl = 0;
$newOrder->total_discounts_tax_incl = 0;
$newOrder->total_discounts = 0;
$newOrder->total_paid = 0;
$newOrder->total_paid_tax_excl = 0;
$newOrder->total_paid_tax_incl = 0;
$newOrder->add();

**Comment by khouloudbelguith** [comment]
@zapper, It will help us if you can attach the exact script a`ddNewOrder.php`.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @zapper,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
