### ISSUE TITLE
Folder /img does not allow .webp

### ISSUE THREAD

**Issue by SharmPRO** [PrestaShop/PrestaShop#17425]
In /img the .htaccess file does not allow .webp files not a standard for optimization, would be great if updated.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @SharmPRO,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10356
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10356
