### ISSUE TITLE
The combination B is not refreshed when I change the combination A

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17437]
**Describe the bug**
The combination B is not refreshed when I change the combination A if the same product has a completely different combination as Tshirt S white and Tshirt M black. 

**To Reproduce**
1. Go to Product Page
2. Create a combination t-shirt with **size S** and **black** as default
3. Create a combination t-shirt with **size M** and **white**
4. Save
5. Go in the FO
6. Change the size S to **M**
The color doesn't refresh and when clinking on the add to cart, it says the color isn't available

**Screenshots**
If applicable, add screenshots or screen records to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by EnricoGentiletti** [comment]
Open themes/core.js

Search for
`(".quickview .product-variants .page-product:not(.modal-open) .row .product-variants").replaceWith(e.product_variants),`

And replace it with:
`(".product-variants").replaceWith(e.product_variants),`

**Comment by sowbiba** [comment]
@EnricoGentiletti :+1: 
It's done here https://github.com/PrestaShop/PrestaShop/pull/17457/files#diff-a1d15e7a995aaa0459241b4974f0e4feR172
with more specific selector

**Comment by lgomez2** [comment]
I have the same problem after update to 1.7.6.3. Price is not refreshed when I change the combination. What I must do to solve this problem? I don't know what files I must replace.

**Comment by MatShir** [comment]
Hi @lgomez2,
I'm happy to say that the patch 1.7.6.4  that fixe the issue will be released at the beginning of March.
If you really can't wait, you can find the solution #17457 in the file changed tab but it is still in test.

**Comment by Emiliotorrecilla** [comment]
hi @MatShir,
I have the same error as Lgomez2.
I update to 1.7.6.3 and all my products with combinations don´t update price.
I have changed core.js and added "," and followed the steps outlined in #17457 .
Please, any other solution for this problem?

**Comment by sroubekog** [comment]
Hi @Emiliotorrecilla you can try to use this, it works for me. Unpack it and copy file to /themes/
[core.zip](https://github.com/PrestaShop/PrestaShop/files/4198254/core.zip)

**Comment by Emiliotorrecilla** [comment]
Hi @sroubekog, 
I have tried it but doesn´t work for me.
The following error appears in the console:
"Error in source mapping: request failed with status 404"
"Resource URL: Mysite / themes / core.js"
"URL source mapping: core.js.map"
![imagen](https://user-images.githubusercontent.com/61007998/74441630-784f7b80-4e70-11ea-8d8f-9bf2502b7e29.png)

**Comment by sroubekog** [comment]
@Emiliotorrecilla There is a chance you have some problem in your template, try to switch it to default classic template. My core.js is from 1.7.6.3 and I just add changes guys suggest in #17457, nothing else.

**Comment by sowbiba** [comment]
Hello
https://github.com/PrestaShop/PrestaShop/pull/17457#issuecomment-586209028

**Comment by zenerry** [comment]
is there any solution to apply to 1.7.5.2?
Can't update entire PS right now (stock sync compatibility reason)
Thanks.

**Comment by MatShir** [comment]
Hi @zenerry,
The bug here is present on the 1.7.6 version. I could not reproduce it in 1.7.5.2. Your bug might be different, could you please share all your steps. 

But if your bug is indeed this one. The best option remains to update the shop but you can retrieve the code used in the [PR ](https://github.com/PrestaShop/PrestaShop/pull/17457) and apply it on your shop with the help of a PrestaShop expert.

**Comment by scorp1czech** [comment]
Same problem in version 1.7.8.1

Problem in this starts by inserting IDs to request link in select combination. Look at screen, request has more than one product_id and return only last in list, but you need return first from list.

First screen: you can see bad values for request.
![error_cause](https://user-images.githubusercontent.com/1717967/145018192-db925c5e-f3b4-41d9-85c7-d85972d5a5dc.png)
Here you see product after open from product list, all is okey, URL is okey.
![test01](https://user-images.githubusercontent.com/1717967/145018206-4222aad0-7606-4315-89fb-6d27b7db765e.png)
After change combination from 100g to 1000g change href of product and return bad data some like price, code and etc.
![test02](https://user-images.githubusercontent.com/1717967/145018239-0d74ea7c-29ea-4f99-9fbb-63dde36cadb0.png)

How i can fix this?

**Comment by MatShir** [comment]
@scorpio-angel I suggest you to reopen an issue with the detail steps, so we can reproduce your bug properly :)
Thanks in advance

**Comment by pewube** [comment]
> 

templates/catalog/_partials/miniatures/product.tpl

Try to change div class name "product-actions" (div.outer-functional > div.functional-buttons) and check request URL after changing attribute

![image](https://user-images.githubusercontent.com/58422606/147585646-ec2a5ae7-4325-4f1f-b6c6-0df021ceaa42.png)
