### ISSUE TITLE
Group access is lost when saving Category object model

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17449]
**Describe the bug**
Group access is lost when $category->save() is executed. Access group is always reinit to the 3 default groups.

**To Reproduce**
1. Go to category admin page id_category X
2. Uncheck a group in group access or check and non default group (i.e. pro group).
3. Save this category in another place (controller or module code) with `$category = new Category(X; $category->save();`
4. See error : group access is lost and reinit to the 3 default groups.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7

The bug is probably linked to the Category::cleanGroups() method that is launched by $category->save()
It's may be the same bug as https://github.com/PrestaShop/PrestaShop/issues/11289

**Comment by jf-viguier** [comment]
I've made a PR https://github.com/PrestaShop/PrestaShop/pull/17450

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2.
https://drive.google.com/file/d/1rFY4n3g7uEMeJMViPG44zZ8pKh_hFdRa/view
I used this script
```php
<?php
require dirname(__FILE__).'/config/config.inc.php';
$category = new Category();
$category->id = 9;
$category->active = 0;
$category->id_parent = 2;
$category->name = array((int)Configuration::get('PS_LANG_DEFAULT') => 'Art');
$category->link_rewrite = array((int)Configuration::get('PS_LANG_DEFAULT') =>  'art');
$force_ids = true;
//this will force ObjectModel to use your ID
$category->force_id = (bool) $force_ids;
$category->add();
echo "Done, Category well updated";
?>
```
I’ll add this to the debug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I tried to use the develop branch to reproduce the issue.
But when using this script with develop branch
```php
<?php
require dirname(__FILE__).'/config/config.inc.php';
$category = new Category();
$category->id = 9;
$category->active = 0;
$category->id_parent = 2;
$category->name = array((int)Configuration::get('PS_LANG_DEFAULT') => 'Art');
$category->link_rewrite = array((int)Configuration::get('PS_LANG_DEFAULT') =>  'art');
$force_ids = true;
//this will force ObjectModel to use your ID
$category->force_id = (bool) $force_ids;
$category->add();
echo "Done, Category well updated";
?>
```
I have this error
![image](https://user-images.githubusercontent.com/16067358/73754769-35e9b880-4765-11ea-9f7c-9a6eeff40533.png)

Thanks!

**Comment by jf-viguier** [comment]
Because id category 9 already exists : write $category->save(); instead of ->add

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17450
