### ISSUE TITLE
Improve feature wording in Product Settings page

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17447]
**Is your feature request related to a problem? Please describe:**

In the Shop Parameters > Product Settings page of the back office, an option exists to enable or disable the display (on the product page) of unavailable product attributes. A text that is not clear enough and that does not mention the fact that the option applies to both situations:

- the products only have a single combination
- the attribute has no product in all possible combinations

For example, the 'White' attribute won't be displayed in the following case:

S - White => 0
S - Black => 1

M - White => 0
M - Black => 1

<img width="1023" alt="Capture d’écran 2020-01-30 à 17 42 16" src="https://user-images.githubusercontent.com/32565890/73470262-e03d9680-4387-11ea-9e30-cc7d5fdc1cd4.png">

**Describe the solution you'd like:**

Since we cannot modify the wording in patch versions, let's figure out a better wording for the 1.7.8. Meanwhile, we will add this information to the user documentation. Here is a better wording, suggested by @Junebyun and validated by @MatShir: 

_Display unavailable attributes on the product page_ in _Admin.Shopparameters.Feature_
With the following tooltip: _If an attribute is not available in every product combination, it will not be displayed._ in _Admin.Shopparameters.Help_

**Additional context:**

cf. #9948 + #17345

**Comment by ghost** [comment]
Or maybe add simple hint sign [ ? ] to explain how the option really works?

**Comment by LouiseBonnard** [comment]
@PrestaShark, why not! It could be a tooltip or a help text. But whatever the form of the message, it will be released with the 1.7.8. Hence the creation of this issue, so that we can do it in the next few weeks and then integrate to PrestaShop's next minor version. ;-)

**Comment by Junebyun** [comment]
@MatShir hey! This is the suggested wording to better explain this feature: 

**Display unavailable attributes on the product page**   
(action: **YES / NO**)

**tool tip:** _If an attribute is not available in every product combination, it will not be displayed._
