### ISSUE TITLE
Free shipping over certain amount by zones..

### ISSUE THREAD

**Issue by jviure** [PrestaShop/PrestaShop#17453]
Hi! It s not possible to set free shiping over certain amount by zones? In the shop country over 30$.. out of the  shop country over 80$.. etc. It s possible? Thaaanks!

**Comment by khouloudbelguith** [comment]
Hi @jviure,

Is it free shipping by Zone or by country?
If it is by Zone, you just follow this screenshot
![image](https://user-images.githubusercontent.com/16067358/73522982-22a7b780-440a-11ea-9ed1-75027d4913c8.png)

Thanks to check & feedback.

**Comment by jviure** [comment]
Many thanks!! works great :)

**Comment by khouloudbelguith** [comment]
@jviure, thanks!
Feel free to open a new one when needed.

Thanks!
