### ISSUE TITLE
Can't modify orders prior to upgrade

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#17452]
Hi,
I upgraded from 1.7.3 to 1.7.6 and how I can't modify orders prior to the upgrade, when I try to modify an open order  by deleting or adding a new product I get this message:
![image](https://user-images.githubusercontent.com/12675798/73496048-08dd8480-43b8-11ea-8cc8-c3a49fda55c4.png)
I know it's difficult to say what could be the reason, but maybe someone can give me a clue where to look. I guess it must be something related to DB structure, but there are many tables involved on storing orders information that I don't know where are the particular tables that may affect the process of modifying the content of an order.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @omar2886,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source) 
 - Module Autoupgrade version
 - Have you any errors during the upgrade
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by omar2886** [comment]
Thanks as usual @khouloudbelguith , I'll try to dig a lil more but seem too complex for me, so if I can't I'll just leave it like that

**Comment by khouloudbelguith** [comment]
@omar2886, thanks!

Feel free to open a new one when needed.
