### ISSUE TITLE
order states

### ISSUE THREAD

**Issue by Artisancosmethic** [PrestaShop/PrestaShop#17464]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Artisancosmethic,

Thanks to provide us a clear description & steps to reproduce the issue in a new comment.

Thanks!

**Comment by Artisancosmethic** [comment]
Hi
i have too many order states for my customers and i would like to delete some of them but i can just modify them. Can at least hide them for my cusromers?
![presta1](https://user-images.githubusercontent.com/60512390/73545781-4d126880-443c-11ea-90b4-9f15c1d08c78.png)

**Comment by khouloudbelguith** [comment]
@Artisancosmethic, this is not possible now.
But we have an improvement similar to this added to our bug roadmap.
Your ticket is a duplicate of #14752
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14752
