### ISSUE TITLE
Can't add an amount using "," in block payment in order page migrated

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#17475]
**Describe the bug**

**To Reproduce**
1. Go to the order page migrated 
2. Select an order 
3. Try to add a payment with a "," like 5,80

**Screenshots**
Migrated : https://drive.google.com/file/d/1Yq-H3O9_Yk2ZKE3FO5uDmrF3vPF8wklj/view
Legacy : https://drive.google.com/file/d/1Gjo_9kVEREleGFhzArcJt7Hbro5WyA6T/view

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by jolelievre** [comment]
@sarahdib  I wonder if we have the same issue on other number inputs? Like refund amount, add/edit products an so on?

**Comment by colinegin** [comment]
@atomiix have you seen @jolelievre 's comment ?

**Comment by boubkerbribri** [comment]
With @atomiix PR, it was fixed in all float inputs => it displayed the same error message 
![image](https://user-images.githubusercontent.com/48441421/76342477-f3d10b00-62fe-11ea-92c0-0deea5583e99.png)
Only quantity inputs accept numbers with ',' but parsing it to an int.

**Comment by Progi1984** [comment]
Fixed by #17476
