### ISSUE TITLE
Não traduz o painel de controle para português na versão 1.7.6.3

### ISSUE THREAD

**Issue by MarcelRoos** [PrestaShop/PrestaShop#17474]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @MarcelRoos,

Please, send your request in English.
English is the norm on the GitHub. 
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @MarcelRoos,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
