### ISSUE TITLE
Bug with products comments module

### ISSUE THREAD

**Issue by YanisseZ** [PrestaShop/PrestaShop#17484]
**Describe the bug**
When i submit a comment the send button send me on my cart.
I don't have an error.

**Screenshots**
[https://youtu.be/iAUUoM9RNgU](https://youtu.be/iAUUoM9RNgU)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.13

**Comment by khouloudbelguith** [comment]
Hi @YanisseZ,

I did not manage to reproduce the issue with PS1.7.6.3 & the productcomments module v4.0.1.
I attached a screen record
https://drive.google.com/file/d/1wXykiKLbrAaEEkUYmi3dS7XN6ki5ic80/view
Did you use a custom theme not provided by PrestaShop?
The productcomments module is it overridden by your theme?

Thanks to check & feedback.

**Comment by YanisseZ** [comment]
Hi @khouloudbelguith 
it seems to come from the theme that I use its name is cactuplant

**Comment by khouloudbelguith** [comment]
@YanisseZ, as it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
