### ISSUE TITLE
The control panel is not translated into Portuguese and any other language in version 1.7.6.3

### ISSUE THREAD

**Issue by MarcelRoos** [PrestaShop/PrestaShop#17488]
The control panel is not translated into Portuguese and any other language in version 1.7.6.3

**Comment by khouloudbelguith** [comment]
Hi @MarcelRoos,

I did not manage to reproduce the issue with PS1.7.6.3.
![image](https://user-images.githubusercontent.com/16067358/73731015-06708700-4738-11ea-8aed-4f8295c6bc21.png)

Could you please try to navigate to your BO => International => Translations => try to update your Portuguese language.
![image](https://user-images.githubusercontent.com/16067358/73730987-fce71f00-4737-11ea-83b8-fc9dd4697cfb.png)

Thanks to check & feedback.

**Comment by MarcelRoos** [comment]
![telaprestashop](https://user-images.githubusercontent.com/60578212/73781057-641fc600-476e-11ea-9e0f-89f7e981051c.jpg)
as the image in mine does not translate. The installation was done through Softaculous. I've reinstalled several times.

**Comment by khouloudbelguith** [comment]
@MarcelRoos, the employee's language in your case is Portuguese?
![image](https://user-images.githubusercontent.com/16067358/73823828-5c593380-47f9-11ea-9eda-c707a34abd7f.png)

Thanks!

**Comment by MarcelRoos** [comment]
you're right. that was the problem. thank you

**Comment by khouloudbelguith** [comment]
@MarcelRoos, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
