### ISSUE TITLE
Several issues after the 1.7.6.3 update

### ISSUE THREAD

**Issue by BeReal86** [PrestaShop/PrestaShop#17486]
First of all, I know that 1.7.6 does not fully support the php version 7.3. But I have been using it since version 1.7.6.1. I had no problems. I share pictures of the problems I have experienced below.

 
I have two different sites. a site updated without problems. The other site was updated without problems, but I found some problems. The first problem is related to the theme. I installed and deleted several different themes. Maybe it was because of this. How can I solve this.?

My other problem is related to the Customer Reassurance module. This module has become very transparent as it appears in the pictures. It gets better when I reset the module and update it again.

The languages selected on my two sites are the same, but the module names differ after updating. 

I mentioned above. The files were not edited, I just installed a few themes and removed them. I had problems with the themes I installed and removed them. maybe a problem caused by them

@khouloudbelguith 
https://drive.google.com/file/d/1NrS9kQXh1Pel7U3Ua6nAJ1YFyQaDtqUm/view?usp=sharing

Instead of sharing the pictures, I made a short video shoot. I hope it is better understood.
If you want to make a better review, if you give you a contact address I can reach, I can provide you with login information.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.3
MySQL: 10.1.41-MariaDB

**Comment by khouloudbelguith** [comment]
Hi @BeReal86,

>First of all, I know that 1.7.6 does not fully support the php version 7.3.

As you said, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.
I'm happy to hear that there is no issue with php7.3 on your staging server but as I said, currently Prestashop is not compatible with php7.3. So some parts of the application might work, but there is no guarantee it works globally. Explications about why can be read here: http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

>The first problem is related to the theme. I installed and deleted several different themes. Maybe it was because of this

What is the exact problem? is it on the `Homepage Configuration` page?
In my case, fresh install PS1.7.6.2 & PS1.7.6.3, I have this
PS1.7.6.3: ![image](https://user-images.githubusercontent.com/16067358/73727379-a2e35b00-4731-11ea-8377-1cd5cc8946e1.png)
PS1.7.6.2: ![image](https://user-images.githubusercontent.com/16067358/73727403-aecf1d00-4731-11ea-8d7a-f3013982bb67.png)

I don't have these buttons like you 
![image](https://user-images.githubusercontent.com/16067358/73727484-da520780-4731-11ea-8b71-a1003ab107d2.png)

>My other problem is related to the Customer Reassurance module. This module has become very transparent as it appears in the pictures. It gets better when I reset the module and update it again.

The version of blockreassurance module v3.0.1 is old.
we refactored this module, the new version of this module is v4.1.1 => the images used in this new release are svg.

>The languages selected on my two sites are the same, but the module names differ after updating.

Those modules are provided by PrestaShop, are they native modules?

Thanks!

**Comment by BeReal86** [comment]
As you can see in the video in the first minutes, when I enter the theme part before updating, the MENU tab is everything in place. But after the update, there are no pictures of the modules or categories in the MENU section. and there are also two of them all except my shop on the left. (Video 4:28).

I do not have exactly what I uploaded, but I found two of them. I made a mistake by setting up free trials of these. Themes did not work properly, they caused many problems.
https://www.hiddentechies.com/bizkick-responsive-theme-prestashop.html
https://apollotheme.com/products/ap-hell-free-prestashop-themes-for-halloween-gifts

I did not take any action on the blockreassurance module. I converted it to its old version because it caused problems in the new version after the update. I downloaded the blockreassurance to its old version, then I added the current version. and the problem there has been fixed.

I think I could backup. I'm going to do a clean install again. What do you think?

when is the 1.7.7 version released? Is there an released date?

**Comment by khouloudbelguith** [comment]
@BeReal86, About the theme issues.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author, they are the only ones to help you with it.
>I think I could back up. I'm going to do a clean install again. What do you think?

You can check the backup if it is well working before making a new install.

>when is the 1.7.7 version released? Is there a released date?

You can follow our project 1.7.7 here:
https://github.com/PrestaShop/PrestaShop/projects/7

Can we close this issue?

Thanks!

**Comment by BeReal86** [comment]
@khouloudbelguith  Thanks for all.

Yes we close this issue.

**Comment by khouloudbelguith** [comment]
@BeReal86, you are welcome!
I will close the issue, feel free to open a new one when needed.

Thanks!
