### ISSUE TITLE
unable to update, active, reload module in prestashop 1.7.6.x

### ISSUE THREAD

**Issue by MoiRouhs** [PrestaShop/PrestaShop#17481]
Hi, I'm working with 2 pages, there are host in differents enterprises, but the two site are the 
same problem with modules differents, modules cannot be updated actived or reloaded.
I  add information the error.

[modules-bugs.zip](https://github.com/PrestaShop/PrestaShop/files/4148513/modules-bugs.zip)

**Comment by khouloudbelguith** [comment]
Hi @MoiRouhs,

About this error:
`"Error sent by Paygreen. You may need to be logged."`
Try to connect your back office to the addons marketplace and see if the error is still there.
About the other error, have you tried to contact the module author about this issue?
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
Hi @MoiRouhs,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
