### ISSUE TITLE
Improve ps_emailalerts template

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17480]
We need to improve template of `ps_emailalerts` account page.

- Add breadcrumb like on other account pages : `Home > Your account`
- Smarty inheritance from `customer/page.tpl` instead of `page.tpl`
- Use `{block name='page_title'}...{/block}` to insert page title

This module is very important for merchants and should not be neglected.

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by micka-fdz** [comment]
PR available here : https://github.com/PrestaShop/ps_emailalerts/pull/43

**Comment by micka-fdz** [comment]
Linked to #17131

**Comment by Progi1984** [comment]
@micka-fdz PR merged : PrestaShop/ps_emailalerts#43
