### ISSUE TITLE
faceted search and order by price

### ISSUE THREAD

**Issue by hejmi** [PrestaShop/PrestaShop#17487]
**Describe the bug**
No price filter appears, everything else seems to be working since I upgrade to ps 1.7.6.3
When I try to index missing prices, nothing happens - wheel spinning "running, 96 left to index" never ending. 
DB ps_layered_price_index is empty. 
Index everything doesn't work either, DB ps_layered_price_index still empty.
![Skärmavbild 2020-02-03 kl  18 46 51](https://user-images.githubusercontent.com/5301960/73677073-cd8fce00-46b5-11ea-9afb-f56bea034ea5.png)
![Skärmavbild 2020-02-03 kl  18 47 07](https://user-images.githubusercontent.com/5301960/73677078-cf599180-46b5-11ea-95f2-21c2f54f6159.png)
![Skärmavbild 2020-02-03 kl  18 48 07](https://user-images.githubusercontent.com/5301960/73677091-d41e4580-46b5-11ea-8293-a235d4882397.png)

ps_layered_filter_shop also empty.
Sort/order by price doesn't work, never ending loading with wheel spinning.. 
Using ps faceted search 3.4.1 

96 products, all activated with price and using same tax. There will be 2 different taxes, but for now only one is activated. 

**To Reproduce**
1. Go to Modules, faceted search 3.4.1. 
2. Click on Rebuild priceindex 
3. No error,

2. Click on Index missing prices
3. Spinning wheel

4. db table ps_layered_price_index empty. 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @supermikey,

I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1 & the ps_facetedsearch v3.4.1.
I attached a screen record
https://drive.google.com/file/d/1zM2IAAlrc2_PRLQ_XNMsP-N2ncUSmpEG/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hejmi** [comment]
Hi!
Thank you for your answer.
I had ps 1.7.5.0 and updated first ps_facetedsearch to 3.4.1. without any positive results. Didn't work with the older faceted search 2.x.x. either
Updated ps with 1-click to 1.7.6.3 and the results are the same. 
I have Apache 2.4, php 7.2
Apache: /var/log/apache/apache_error.log - doesn't exist
Apache: /var/log/apache/php_error.log - doesn't exist

I'm trying with a fresh installation of 1.7.6.3 right now on another server, but here's what I get in debug mode:

(1/1) ContextErrorExceptionNotice: Undefined index: type
--
in 7574f820e652ec6b3c282075686bf7e02e6b8e69_2.module.labmegamenuviewstemplates.php line 82
at content_5e3950282102a4_42243829(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in Module.php line 2447
at ModuleCore->fetch('module:labmegamenu/views/templates/hook/labmegamenu.tpl', 'labmegamenu\|1\|1\|3\|18')in labmegamenu.php line 1325
at Labmegamenu->renderWidget('displayMegamenu', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 975
at HookCore::coreRenderWidget(object(Labmegamenu), 'displayMegamenu', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 927
at HookCore::exec('displayMegamenu', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayMegamenu'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayMegamenu'), object(SmartyDevTemplate)))in 905267f51390a0d9edd63657d2d0bddb920e9ea2_2.file.header.tpl.php line 142
at Block_7941482535e395028070f66_88742154->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_7941482535e395028070f66_88742154), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_7941482535e395028070f66_88742154))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_7941482535e395028070f66_88742154', 'header_top')in 905267f51390a0d9edd63657d2d0bddb920e9ea2_2.file.header.tpl.php line 36
at content_5e395028075b57_57114899(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('file:_partials/header.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 0, false)in 9c10b98df260a7c9be22e9cb6d0464c47528bcce_2.file.layout-both-columns.tpl.php line 224
at Block_4467501345e395027ec9f35_18222727->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_4467501345e395027ec9f35_18222727), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_4467501345e395027ec9f35_18222727))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_4467501345e395027ec9f35_18222727', 'header')in 9c10b98df260a7c9be22e9cb6d0464c47528bcce_2.file.layout-both-columns.tpl.php line 64
at content_5e395027ed9ae6_48097015(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in b540fed606e0b2cd80c521f4fcc00d9c4feea416_2.file.layout-full-width.tpl.php line 42
at content_5e395027ea5fb7_36251551(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 1206928603f2fadf155ad808c73764a0dac15688_2.file.page.tpl.php line 33
at content_5e395027e802f0_50078269(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in ac9e0db0c713e0247f50dffe4a97b3d160aa3911_2.file.index.tpl.php line 33
at content_5e395027e59022_48971170(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('index.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('index.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('index.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28


Console:


TypeError: "container.node.targetFront is null"
    _getVisibleChildren resource://devtools/client/inspector/markup/markup.js:2205
    _updateChildren resource://devtools/client/inspector/markup/markup.js:2113
    _mutationObserver resource://devtools/client/inspector/markup/markup.js:1422
    emit resource://devtools/shared/event-emitter.js:190
    emit resource://devtools/shared/event-emitter.js:271
    getMutations resource://devtools/shared/fronts/inspector.js:425
markup.js:410:15
TypeError: "container.node.targetFront is null"
    _getVisibleChildren resource://devtools/client/inspector/markup/markup.js:2205
    _updateChildren resource://devtools/client/inspector/markup/markup.js:2113
    _mutationObserver resource://devtools/client/inspector/markup/markup.js:1422
    emit resource://devtools/shared/event-emitter.js:190
    emit resource://devtools/shared/event-emitter.js:271
    getMutations resource://devtools/shared/fronts/inspector.js:425
markup.js:410:15
TypeError: "container.node.targetFront is null"
    _getVisibleChildren resource://devtools/client/inspector/markup/markup.js:2205
    _updateChildren resource://devtools/client/inspector/markup/markup.js:2113
    _mutationObserver resource://devtools/client/inspector/markup/markup.js:1422
    emit resource://devtools/shared/event-emitter.js:190
    emit resource://devtools/shared/event-emitter.js:271
    getMutations resource://devtools/shared/fronts/inspector.js:425
markup.js:410:15
Could not write session state file  
Object { operation: "move", path: "/Users/michael/Library/Application Support/Firefox/Profiles/ta44rt8a.default-release/sessionstore.jsonlz4", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:467:17
Could not write session state file  
Object { operation: "move", path: "/Users/michael/Library/Application Support/Firefox/Profiles/ta44rt8a.default-release/sessionstore.jsonlz4", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:467:17
Protocol error (unknownError): node is null box-model.js:228:19
Could not write session state file  
Object { operation: "move", path: "/Users/michael/Library/Application Support/Firefox/Profiles/ta44rt8a.default-release/sessionstore.jsonlz4", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:467:17
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended 15 LoginManager.jsm:473:13
TypeError: parent is null: canMutationImpactCurrentStyles@resource://devtools/client/inspector/shared/style-change-tracker.js:63:24
onMutations@resource://devtools/client/inspector/shared/style-change-tracker.js:80:41
emit@resource://devtools/shared/event-emitter.js:190:24
emit@resource://devtools/shared/event-emitter.js:271:18
getMutations/<@resource://devtools/shared/fronts/inspector.js:425:12
event-emitter.js:195:21
TypeError: this.doc is null: _selectionWalker@resource://devtools/client/inspector/markup/markup.js:992:20
Down@resource://devtools/client/inspector/markup/markup.js:173:33
_onShortcut@resource://devtools/client/inspector/markup/markup.js:1153:36
_initShortcuts/</<@resource://devtools/client/inspector/markup/markup.js:1140:39
emit@resource://devtools/shared/event-emitter.js:190:24
emit@resource://devtools/shared/event-emitter.js:271:18
handleEvent@resource://devtools/client/shared/key-shortcuts.js:268:27
19 event-emitter.js:195:21
TypeError: currentNode is null: canMutationImpactCurrentStyles@resource://devtools/client/inspector/shared/style-change-tracker.js:62:20
onMutations@resource://devtools/client/inspector/shared/style-change-tracker.js:80:41
emit@resource://devtools/shared/event-emitter.js:190:24
emit@resource://devtools/shared/event-emitter.js:271:18
getMutations/<@resource://devtools/shared/fronts/inspector.js:425:12
event-emitter.js:195:21
TypeError: "state is null"
    restoreState resource://devtools/client/inspector/shared/highlighters-overlay.js:869
    restoreFlexboxState resource://devtools/client/inspector/shared/highlighters-overlay.js:825
    onMarkupLoaded resource://devtools/client/inspector/inspector.js:1331
    newListener resource://devtools/shared/event-emitter.js:149
    emit resource://devtools/shared/event-emitter.js:190
    emit resource://devtools/shared/event-emitter.js:271
    _onMarkupFrameLoad resource://devtools/client/inspector/inspector.js:1662
    _initMarkup resource://devtools/client/inspector/inspector.js:1649
    onNodeSelected resource://devtools/client/inspector/inspector.js:1288
highlighters-overlay.js:1011:15
TypeError: "state is null"
    restoreState resource://devtools/client/inspector/shared/highlighters-overlay.js:869
    restoreFlexboxState resource://devtools/client/inspector/shared/highlighters-overlay.js:825
    onMarkupLoaded resource://devtools/client/inspector/inspector.js:1331
    newListener resource://devtools/shared/event-emitter.js:149
    emit resource://devtools/shared/event-emitter.js:190
    emit resource://devtools/shared/event-emitter.js:271
    _onMarkupFrameLoad resource://devtools/client/inspector/inspector.js:1662
    _initMarkup resource://devtools/client/inspector/inspector.js:1649
    onNodeSelected resource://devtools/client/inspector/inspector.js:1288
highlighters-overlay.js:1011:15
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended 36 LoginManager.jsm:473:13
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.4.19
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580 OpenGL Engine
FBO Texture Target: TEXTURE_2D
No messages returned from https://snippets.cdn.mozilla.net/6/Firefox/70.0.1/2019103002…n_x86_64-gcc3/sv-SE/release/Darwin%2019.2.0/default/default/. 2 ASRouter.jsm:143
Use of nsIFile in content process is deprecated. 15 NetUtil.jsm:253:8
DebuggeeWouldRun: debuggee `http://2020.veganmarket.se/themes/core.js:39' would run event-collector.js:526:18
TypeError: node.ownerDocument is null
HTMLTooltip.js:879:15
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.isDeadWrapper] highlighters.js:721
TypeError: this.highlighterEnv is null markup.js:259:17
TypeError: this._refMap is null walker.js:514:5
Use of nsIFile in content process is deprecated. 8 NetUtil.jsm:253:8
DebuggeeWouldRun: debuggee `http://2020.veganmarket.se/themes/core.js:39' would run event-collector.js:526:18
Säkerhetsfel: innehåll på http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/8b05d51ede908907d65695558974d86f.svg försökte ladda http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/D795CA29.png, men kan inte ladda extern data när den används som en bild. 2
Säkerhetsfel: innehåll på http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/c1a65805f759901a39d10eb854c1dcf2.svg försökte ladda http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/CE61D04B.png, men kan inte ladda extern data när den används som en bild. 2
Säkerhetsfel: innehåll på http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/ffddcb3736980b23405b31142a324b62.svg försökte ladda http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/43D69FB1.png, men kan inte ladda extern data när den används som en bild. 2
Säkerhetsfel: innehåll på http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/b1db819132e64a3e01911a1413c33acf.svg försökte ladda http://2020.veganmarket.se/themes/laber_siemonsalazar_homepage11/assets/css/8DF66D4B.png, men kan inte ladda extern data när den används som en bild. 2
Use of nsIFile in content process is deprecated. 6 NetUtil.jsm:253:8
[Exception... "Favicon at "http://2020.veganmarket.se/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.isDeadWrapper] highlighters.js:721
TypeError: this.highlighterEnv is null markup.js:259:17
TypeError: this._refMap is null walker.js:514:5
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.4.19
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580 OpenGL Engine
FBO Texture Target: TEXTURE_2D
[Exception... "Favicon at "http://2020.veganmarket.se/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
Use of nsIFile in content process is deprecated. 10 NetUtil.jsm:253:8
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.isDeadWrapper] highlighters.js:721
TypeError: this.highlighterEnv is null markup.js:259:17
TypeError: this._refMap is null walker.js:514:5
Use of nsIFile in content process is deprecated. 10 NetUtil.jsm:253:8
Use of nsIFile in content process is deprecated. 4 NetUtil.jsm:253:8
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.4.19
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580 OpenGL Engine
FBO Texture Target: TEXTURE_2D
No messages returned from https://snippets.cdn.mozilla.net/6/Firefox/70.0.1/2019103002…n_x86_64-gcc3/sv-SE/release/Darwin%2019.2.0/default/default/. 2 ASRouter.jsm:143
[Exception... "Favicon at "http://2020.veganmarket.se/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.4.19
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580 OpenGL Engine
FBO Texture Target: TEXTURE_2D 2
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
[Exception... "Favicon at "http://2020.veganmarket.se/img/app_icon.png" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended 6 LoginManager.jsm:473:13
[Exception... "Favicon at "http://2020.veganmarket.se/img/app_icon.png" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended 2 LoginManager.jsm:473:13
[Exception... "Favicon at "http://2020.veganmarket.se/img/app_icon.png" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
[Exception... "Favicon at "http://2020.veganmarket.se/img/app_icon.png" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 236"  data: no] FaviconLoader.jsm:236:22
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.4.19
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580 OpenGL Engine
FBO Texture Target: TEXTURE_2D 4

**Comment by khouloudbelguith** [comment]
@supermikey, you have a lot of errors related to:

1. labmegamenu module
2. laber_siemonsalazar_homepage11 theme

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by hejmi** [comment]
Hi and thank you for helping out!

I installed a fresh version of ps 1.7.6.3 & ps_faceted 3.4.1 
Now everything works as it should!

**Comment by khouloudbelguith** [comment]
@supermikey, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
