### ISSUE TITLE
Customer/Guest account double entries

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17493]
Hi,

On the forum you can read the problem that exist for years now in PrestaShop.
https://www.prestashop.com/forums/topic/303041-multiple-customer-id-with-same-email-id/?do=findComment&comment=1798911

I want to look into this and I'm here to help to make a huge improvement for this.

Situation: You make a credit slip for customer, let's call him Adam. 
Adam has only 1 guest account. 
Adam get's your e-mail about the creditslip: A new credit slip has been made. Login to view it.
Adam has no customer account, so he creates one.
Double customer in database now. (1 guest, 1 customer)

Adam still can't view credit slip. Because new created account on same email address has no order history.

1) You can create unlimited guest accounts for the same email address at this moment?
2) Why not merge accounts automatically when you have the same email address? 
3) When you have already 1 guest account, just make a account to prevent double customer accounts?

https://github.com/PrestaShop/PrestaShop/issues/10122
This issue 10122 and 16872 needs priority because alot of customer history is being a mess now?

**Comment by khouloudbelguith** [comment]
Hi @sdwebdesign,

Thanks for your report.
In fact, the Guest account is not transformed into a customer account, it creates a second account
Issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10122
Also, guest tracking issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/9650#issuecomment-415055890

Your ticket is it a duplicate of #10122? 

Thanks!

**Comment by ghost** [comment]
The account creation, and guest creation is a basic feature that it not working fine, so I hope with my example above, the issue #10122 gets more attention to work on a solution for this problem.

My problem in 1.7.6.3: You can create unlimited guest accounts for the same email at this moment?

This problem is there since PrestaShop version 1.3 until now. Let's fix it please together.

**Comment by khouloudbelguith** [comment]
@sdwebdesign, thanks a lot for your feedback.
This issue #10122 is assigned to our product team.

Since your ticket is duplicate of #10122, I need to close it.
But, you need to follow this ticket: #10122 & add your suggestion in a new comment.

Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #10122
