### ISSUE TITLE
Prestashop forum is down

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17492]
Try to open link
https://www.prestashop.com/forums/topic/1014312-ajouter-la-page-magasins-au-menu-horizontal/

And You will be redirected to https://www.prestashop.com/forums/

Every topic links not working - Google also.

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

About your problem on the forum, you can send an email to this address forum@prestashop.com and describe your issue.

Thanks!

**Comment by matks** [comment]
FYI problem is solved 😉
