### ISSUE TITLE
Images do not showing AFTER Login

### ISSUE THREAD

**Issue by dtwfung** [PrestaShop/PrestaShop#17503]
PS 1.7.6.1, images do not show AFTER login. Before login (either mobile, PC), all images are working normally.

**To Reproduce**
1. Go to 'https://cop9gun.com/prshop175/en/eski/548-tactical-boot-black.html '
2. You can see all images showing properly
3. Login to "testing@gmail.com" (password is password)
4. All images cannot display with same link in step 1 ('https://cop9gun.com/prshop175/en/eski/548-tactical-boot-black.html ')
5. When inspect image, it refers different link
5.1 WITH login ==>https://cop9gun.com/prshop175/2577-large_default-r2DrNZuUz0/tactical-boot-black.jpg
5.2 WITHOUT login ==> https://cop9gun.com/prshop175/2577-large_default/tactical-boot-black.jpg
6. Any account/any product will have same problem.

**Screenshots**
BEFORE login, 
![BeforeLogin](https://user-images.githubusercontent.com/11907298/73809055-e5c63100-480c-11ea-88e2-9f777623932b.jpg)
After login
![AfterLogin](https://user-images.githubusercontent.com/11907298/73809060-ea8ae500-480c-11ea-961f-2d11e631b7de.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version:  7.1.33

**Comment by khouloudbelguith** [comment]
Hi @dtwfung,

Thanks to navigate to your BO => Design => Image Settings page => scroll down & click on the "Regenerate thumbnails" button.
![image](https://user-images.githubusercontent.com/16067358/73822297-08008480-47f6-11ea-9036-9d10e2a23ed8.png)

Thanks to check & feedback.

**Comment by dtwfung** [comment]
As regenerate all thumbnails will cause timeout, do you know whether Only "home-default" type I have to regenerate ?

**Comment by khouloudbelguith** [comment]
@dtwfung, you can select the format "large_default"
![image](https://user-images.githubusercontent.com/16067358/73833245-f3c68280-4809-11ea-8e26-d94e9b2c5848.png)

Thanks!

**Comment by PrestaShark** [comment]
I have the same issue at 1.7.6.1 on asian sever.
Notice that image link gets additional chars

https://cop9gun.com/prshop175/5281-home_default-r2DrNZuUz0/5ku-optima-doctor-vortex-mount-for-glock-pistol.jpg

When -r2DrNZuUz0 was removed image apear

https://cop9gun.com/prshop175/5281-home_default/5ku-optima-doctor-vortex-mount-for-glock-pistol.jpg

Any security breach?

**Comment by PrestaShark** [comment]
When do You notice that issue? Let me guess CPanel? Any errors on BO when debug mode is ON?

**Comment by ghost** [comment]
Its watermark module fault... 
Uninstall it . lol

**Comment by dtwfung** [comment]
Alright, it seems the watermark module is faulty... I tried regenerate images but NO filename with hashed key generated,
![imp-p-dir](https://user-images.githubusercontent.com/11907298/73903528-51bf9c80-48d4-11ea-8a18-11ef31291fe1.jpg)

**Comment by khouloudbelguith** [comment]
Hi @dtwfung,

I did not manage to reproduce the issue with PS1.7.6.2 & PS1.7.6.3 & the Watermark module v2.0.0.
https://drive.google.com/file/d/1YHfheuuDbgH6rLHKfq05be97BuKFG5_x/view
Feel free to open a new one when needed.

Thanks!

**Comment by dtwfung** [comment]
Have you select the option "Logged in customers can see images without watermark" in Watermark module, check image of any old products when login ?  Thx. again

**Comment by khouloudbelguith** [comment]
@dtwfung, yes!
I attached a screen record
https://drive.google.com/file/d/1JQIm_7zOvLAhn6ndkdAYTvWO3yOh8fkW/view

Thanks to check & feedback.

**Comment by dtwfung** [comment]
In my case, I select Home-default and large-default only.
According to watermark module, it requests me to regenerate thumbnail. Have you do it in your case ?
When you inspect image url, are they refer same jpg, I meant e.g. login customer view 2577-large_default-r2DrNZuUz0.jpg (with hashed key) and other view 2577-large_default.jpg ?

Thx again

**Comment by khouloudbelguith** [comment]
@dtwfung, 
It is ok
https://drive.google.com/file/d/1qyGzLxsmGk-7eto34J8wY2G8X78MAmZ4/view

Thanks!

**Comment by ghost** [comment]
@dtwfung notice that @khouloudbelguith use higher version of Prestashop 1.7.6.2 and .3 instead of .1 in Your case. Try to upgrade store. Also try to switch PHP version to 7.2 if possible.

**Comment by dtwfung** [comment]
Can you check the image path and filename of the cloth BEFORE and AFTER LOGIN, see if they are different ...Thx.
My environment，before and after login are refer different filename (the filename under img/p directory...
Thx again

**Comment by khouloudbelguith** [comment]
@dtwfung, @PrestaShark,

I tried with PS1.7.6.1 & PHP7.1 & it is OK 
https://drive.google.com/file/d/1yXW9w7EuLHLvwmis9UaAT1DddRNGpD17/view

Thanks!

**Comment by dtwfung** [comment]
I tried to use PHP 7.2 but error when login to PS BO.
Back to PHP 7.1,  the URL path is different with customer login and logout. 
When customer login, there is hashed key in the path ==> https://cop9gun.com/prshop175/497-home_default-**r2DrNZuUz0**/element-seemore-railway-reflax-sight-yellow.jpg
See attached pictures.

Really want to know what is URL in your environment, before login and after login !
![URL-login](https://user-images.githubusercontent.com/11907298/73949545-80ba2a80-4935-11ea-93f5-5b81f59c739d.jpg)
![URL-logout](https://user-images.githubusercontent.com/11907298/73949561-87e13880-4935-11ea-9a9b-4609c7ae760c.jpg)

**Comment by khouloudbelguith** [comment]
@dtwfung,
After login
![image](https://user-images.githubusercontent.com/16067358/73950053-96aaf980-48fb-11ea-9ff8-031e0047cfbf.png)
Before login
![image](https://user-images.githubusercontent.com/16067358/73950136-b2ae9b00-48fb-11ea-8e41-775d4410b273.png)

Thanks!

**Comment by ghost** [comment]
@dtwfung this is very interesting case.
Have the same in my customer from Bangladesh. Let me guess? Error is "SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13)" and You are using CPanel?

**Comment by khouloudbelguith** [comment]
@dtwfung, @PrestaShark,

>ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13)" and You are using CPanel?

This is a permission issue in the server.

Thanks!

**Comment by ghost** [comment]
Thats why GC library can't do anything.

**Comment by khouloudbelguith** [comment]
@dtwfung, any news?

Thanks!

**Comment by dtwfung** [comment]
> @dtwfung this is very interesting case.
> Have the same in my customer from Bangladesh. Let me guess? Error is "SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13)" and You are using CPanel?

Yes, I'm using CPanel ! Anything I can do ?!

**Comment by dtwfung** [comment]
> @dtwfung, any news?
> 
> Thanks!

Yes, I'm using CPanel ! Anything I can do ?!

**Comment by dtwfung** [comment]
I just tried to test this case on another fresh installation (PS 1.7.6.1, PHP 7.1). This installation are on the same platform as above installations, using Cpanel. 
https://cop9gun.com/prshopupd/home-accessories/20-customizable-mug.html (Login account setting are same.)
Before Login & after login, ALL images show properly.
Difference are I REGENERATE ALL images in one goal (Much few products than other two installation, Only demo products in this installation.) But, In other TWO installations, 3000+ products and regenerate will cause timeout. I have to regenerate images by image types. 

I think I can close this issue. 
Many thanks for your assistance.

**Comment by khouloudbelguith** [comment]
@dtwfung, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
