### ISSUE TITLE
dni not editable in bo

### ISSUE THREAD

**Issue by mauweb** [PrestaShop/PrestaShop#17506]
** Describe the bug **
(nation Italy ... I don't know if the problem is also for other nations)
the tax code field (dni) even if it is present in the "address format" but is set to "not mandatory" in the BO customer form the form for any modification does not appear
if set "mandatory" appears.
In the FO everything is ok

** To Reproduce **
1. go to BO: international - locality - country
2. required tax code number "NO"
3. go to BO customers - edit - addresses
4. the tax code field is not present

1. go to BO: international - locality - country
2. required tax code number "SI"
3. go to BO customers - edit - addresses
4. the tax code field is present

** ** Screenshots
I add image

** Additional information **
PrestaShop version: 1.7.6.2
PHP version: 7.2.26

---------------------------------------------------------------

** Descrivi il bug **
(Nazione Italia ... non so se il problema è anche per le altre nazioni)
il campo codice fiscale (dni) anche se è presente nel "formato indirizzo" ma è impostato su "non obbligatorio" nella scheda cliente del BO non appare il modulo per una eventuale modifica
appare settato "obbligatorio".
Nel FO tutto ok

** Per riprodurre **
1. andare in BO: internazionale - località - nazione
2. richiesto numero codice fiscale obbligatorio "NO"
3. andare in clienti BO - modifica - indirizzi
4. il campo codice fiscale non è presente

1. andare in BO: internazionale - località - nazione
2. richiesto numero codice fiscale obbligatorio "SI"
3. andare in clienti BO - modifica - indirizzi
4. il campo codice fiscale è presente

** ** Screenshots
aggiungo immagine

**Informazioni aggiuntive**
Versione PrestaShop: 1.7.6.2
Versione PHP: 7.2.26
![presta](https://user-images.githubusercontent.com/47330829/73830499-11451d80-4805-11ea-9288-15645036976c.jpg)

**Comment by khouloudbelguith** [comment]
Hi @mauweb,

In the BO => International => locations => countries page => when the option "Do you need a tax identification number?" is enabled, did you tried to update the address & click save?, because, it is ok with PS1.7.6.3.
I attached a screen record
[AwesomeScreenshot-2020-2-5-1580899894850.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4159067/AwesomeScreenshot-2020-2-5-1580899894850.webm.zip)
This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/11726 in the PS1.7.6.0, it fixes this issue: https://github.com/PrestaShop/PrestaShop/issues/9891
Thanks to check & feedback.

**Comment by mauweb** [comment]
thanks khouloudbelguith for the reply.
I'll explain better why this isn't the problem.

I would like the "dni" field to be displayed in customer edit even if "Do you need a tax code?" It is "disabled"

**Comment by khouloudbelguith** [comment]
@mauweb, thanks for these clarifications.
This issue is fixed in the next major version PS1.7.7.0.
https://drive.google.com/file/d/116nrEq597uvySxIbjxoAzGZqEUqLdy79/viewhttps://drive.google.com/file/d/116nrEq597uvySxIbjxoAzGZqEUqLdy79/view
Since it is fixed, I will close the issue.

Thanks!

**Comment by mauweb** [comment]
great thank you very much khouloudbelguith
