### ISSUE TITLE
Clean LegacyHookSubscriber description

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17511]
There is a lot of data about hooks inside class phpDoc of [LegacyHookSubscriber](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/LegacyHookSubscriber.php). It should be put in a better location (hook.xml or devdocs) and the class should be cleaned.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

**Comment by jolelievre** [comment]
Yes we just saw this with @matks It's only some PHPDoc to remove

**Comment by eternoendless** [comment]
Done here: https://github.com/PrestaShop/docs/pull/661

@matks can we consider this one done?

**Comment by matks** [comment]
> Done here: [PrestaShop/docs#661](https://github.com/PrestaShop/docs/pull/661)
> 
> @matks can we consider this one done?

Yes indeed.
