### ISSUE TITLE
Deprecate, if relevant, the HookManager

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17512]
With @jolelievre we have explored the code and it looks like
- in 1.7.0 version the class [HookManager](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/HookManager.php) was created to wrap legacy `Hook::exec()` calls
- but it was replaced in 1.7.1 by HookDispatcher / [LegacyHookSubscriber](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/LegacyHookSubscriber.php) combination

So we should be able to deprecate HookManager __after__ checking this analysis is accurate 😄

**Comment by khouloudbelguith** [comment]
pING @PrestaShop/prestashop-core-developers

**Comment by eternoendless** [comment]
@matks what's the status on this?

**Comment by matks** [comment]
The two classes hold 2 different responsibilities.

One day the should be merged but today they cannot replace each other.
