### ISSUE TITLE
This Combination Does Not Exist For This Product. Please Select Another Combination.

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#17529]
Hi,

I am using PS version 1.5. In product page, I have the following error for some products (not for all) - "**This Combination Does Not Exist For This Product. Please Select Another Combination.**" I don't know what to do. I have set a combination (Sizes) and also assigned a default combination but it is not visible in front.

I have gone through more forums related to this issue but I found nothing.

Can anyone please help me ?

Thanks,

**Comment by khouloudbelguith** [comment]
Hi @Gaja-A,

This is an old version PrestaShop.
We only support PrestaShop 1.7.

I will close the issue, feel free to open a new one when needed.

Thanks for your understanding!
