### ISSUE TITLE
How can i remove the discount percentage from product list?

### ISSUE THREAD

**Issue by TucoSalamanca** [PrestaShop/PrestaShop#17536]
Hello so for some reason i have the discount percentage shown twice and i suspect this is because i run custom theme and 1 its from the original and 1 is from the custom theme

On the attached picture you'll see what im talking about, im trying to remove the red percentage(top-right one) so it will only display the gray one(top-left one).

I've tried tweaking around in product.tpl with little succes as i don't really know how to code, hope you guys can help, thanks.

Im using prestashop 1.7.6.0 

![44444 jpg 240039c8afd121f396a8ec27e368761d](https://user-images.githubusercontent.com/60016174/73952898-45553700-4908-11ea-89c7-b74c3955a3fd.jpg)

**Comment by khouloudbelguith** [comment]
Hi @TucoSalamanca,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
