### ISSUE TITLE
No states available in "states" choosing field in Tax rule creation.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#17541]
**Describe the bug**
Creating a new tax rule for USA, there are no states listed in the states select field. Only available is "all states"

**To Reproduce**
1. Go to 'International > Taxes > Tax rules'
2. Click on 'add new tax rule'
3. You can choose the country, eg. United States
4. You can not choose a state, only "all" is available.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version:  1.7.6.1
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment]
Hi @grzegorzgit,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.3.
You can Select only one state or more.
![image](https://user-images.githubusercontent.com/16067358/74016392-aaee0580-4992-11ea-97cb-84ca8c216660.png)
![image](https://user-images.githubusercontent.com/16067358/74016409-b17c7d00-4992-11ea-9afd-b03f4599f5a0.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by grzegorzgit** [comment]
Hey, thx for quick response.
I have found what the problem really is. In console theres error 
![image](https://user-images.githubusercontent.com/24461669/74024669-a3365d00-49a2-11ea-9617-9ef2341ff0e7.png)
which is this code:
![image](https://user-images.githubusercontent.com/24461669/74024727-be08d180-49a2-11ea-9abc-7c80d71ad3e6.png)

So it looks like jQuery size() is deprecated from version 1.8, it should be length property.
This is how it looks:
![image](https://user-images.githubusercontent.com/24461669/74025207-b564cb00-49a3-11ea-862a-1684ed23abd1.png)
So the reason is that I switched to jQuery 3.4. Although I've caused the error, it would be good to update Prestashop to work with newer jQuery.

**Comment by khouloudbelguith** [comment]
@grzegorzgit, 
>So the reason is that I switched to jQuery 3.4. 

Did you make a switch to jQuery 3.4 manually?

Thanks!

**Comment by grzegorzgit** [comment]
Yes, I wanted to solve the Chromium Lighthouse error "Includes front-end JavaScript libraries with known security vulnerabilities.". I got back to jQuery 1.1 and the states are there.

**Comment by khouloudbelguith** [comment]
@grzegorzgit, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!
