### ISSUE TITLE
Backoffice product catalog search bar not working

### ISSUE THREAD

**Issue by iriarh** [PrestaShop/PrestaShop#17552]
Hi there ....
Today i noticed that the upper product catalog bar in the backoffice is not working and the reset button is replaced by a "save & refresh" button also the position row has arrows instead of buttons 
I did a prestashop update and tried to reset some modules relevant to the catalog to no avail.
I attach a photo of the tab and rows ...
![2020-02-07_12-56-49](https://user-images.githubusercontent.com/40428036/74027226-6e310700-49b0-11ea-9646-bd77979719d3.png)

to check visit
https://bombcosmetics.shop

**Comment by iriarh** [comment]
I solved the issue ..it was a glitch in the product bulk filter action..

**Comment by nunsaciu** [comment]
hi iriarh,

I'm in trouble with the same issue but i don't understand where the glitch is! Can you give more details about this?
Many thanks!
