### ISSUE TITLE
The typo of the value of an order considered as paid is still small.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17551]
The green style of the value when an order is considered as paid is still small.
See in the screenshot below.

![download (3)](https://user-images.githubusercontent.com/43613217/73864198-859db200-4841-11ea-8e44-317a1e17d7ab.png)

_Originally posted by @MatShir in https://github.com/PrestaShop/PrestaShop/issues/15971#issuecomment-582508738_

**Comment by Progi1984** [comment]
Fixed by #17568
