### ISSUE TITLE
Bad display in categories page when sorting data

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17563]
**Describe the bug**
When sorting a tab which has bulk action and position selector, the display of the tab is broken.

**To Reproduce**
1. Go to Categories
2. Sort the tab (for example, by ID)
3. Bulk action checkbox display is not OK

**Screenshots**
![pr17547 bad display](https://user-images.githubusercontent.com/55688534/74041027-2a94c800-49c5-11ea-9ce8-d241362d3286.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I have the same issue with 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/74041844-b529f700-49c6-11ea-9830-316b63cf7621.png)
I’ll add this to the debug roadmap.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17650

**Comment by khouloudbelguith** [comment]
Hi!

I manage to reproduce the issue on develop branch (1780).
I will re-open the issue.
![image](https://user-images.githubusercontent.com/16067358/99089962-479e9d00-25ce-11eb-8f6f-ac5940924810.png)

Thanks!
