### ISSUE TITLE
The cart does not load with the active cart rule

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#17574]
**Describe the bug**
After updating to 1.7.6.3, the cart does not load with the active cart rule active, only if a code is set.
If not completed to apply automatically, the page loading and loading.

Error got :
PHP Fatal error:  Allowed memory size of 385875968 bytes exhausted (tried to allocate 12288 bytes) in /home/dual34/public_html/classes/CartRule.php on line 614

**To Reproduce**

**Screenshots**
![1](https://user-images.githubusercontent.com/5030991/74092222-a1b38480-4ac9-11ea-833d-11e3f5bedf2a.jpg)
![2](https://user-images.githubusercontent.com/5030991/74092228-ae37dd00-4ac9-11ea-8b44-30d3a912873e.jpg)

Worked on 1.7.6.2

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jajarom,

>PHP Fatal error: Allowed memory size of 385875968 bytes exhausted (tried to allocate 12288 bytes) in /home/dual34/public_html/classes/CartRule.php on line 614

It is a size problem.
Thanks to check your configuration in the `php.ini` file & try to increase them

```
upload_max_filesize

post_max_size

max_file_uploads

memory_limit

max_input_vars

max_input_time

max_execution_time

set_time_limit
```

Thanks!

**Comment by jajarom** [comment]
I think the issue is not that. If that voucher is created, the website also cannot load (after the client login the web is error 500)

**Comment by florine2623** [comment]
Thanks for your feedback. The error 500 is too vague, could you activate debug mode and PHP error log please ? And send a screenshot.
https://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jajarom,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
