### ISSUE TITLE
Autoupdate fails to update module 1.7.5.1 to 1.7.6..

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#17572]
Autoupdate fails to update module 1.7.5.1 to 1.7.6

Tried to 1.7.6.0 / 3

It fails at classes/controller/FrontController.php line 353 - Trying to get property 'logged' of non-object

Probably is some module issue but i had disable other non prest modules before update.
I have located FrontController.php line 353 file but lines dont have numbers, so cant find 353 one sadly

PHP version: 7.2.

Any advice?

[FrontController.zip](https://github.com/PrestaShop/PrestaShop/files/4174995/FrontController.zip)

**Comment by khouloudbelguith** [comment]
Hi @GTriber,

What is the exact version of the 1-click upgrade did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`.

Thanks!

**Comment by GTriber** [comment]
Hi @khouloudbelguith 

Using version v4.10.1 ( tried with reinstall this module ) No luck.

As for log i only saved "classes/controller/FrontController.php line 353" error. As i need it to recover 1.7.5.1, so website could work in week, so log file is empty :(

No clue what to do as im not technical person. In debug mode i dont have any serious issues ( few translations only ).

If log is need it i will do another try before night and will provide it tomorrow. 

PS: I also tried manual upgrade with zips from download folder, same issue.

Best Wishes

**Comment by khouloudbelguith** [comment]
@GTriber, 

>If log is need it i will do another try before night and will provide it tomorrow.

We need to retrieve the error log in order to find out what's wrong.
Waiting for your feedback.

Thanks!

**Comment by GTriber** [comment]
@khouloudbelguith adding log 
[log.zip](https://github.com/PrestaShop/PrestaShop/files/4181051/log.zip)

And update stuck on:
"All files upgraded. Now upgrading database...
Database upgraded. Now upgrading your Addons modules...
75 modules will be updated."

After an hour ive  just cancel.

**Comment by khouloudbelguith** [comment]
@GTriber, The upgrade is stopped when upgrading your modules.
Did you disable non-native modules before the upgrade?

Thanks!

**Comment by GTriber** [comment]
@khouloudbelguith  Yes i did.

**Comment by khouloudbelguith** [comment]
@GTriber, did you used which option?
- In the autoupgrade configuration page?
- On the Performance page?

Thanks!

**Comment by GTriber** [comment]
@khouloudbelguith 

I used 1-click upgrade

**Comment by khouloudbelguith** [comment]
@GTriber, thanks to provide me the list of modules installed in your case
![image](https://user-images.githubusercontent.com/16067358/74160475-c1f45800-4c1d-11ea-8937-845decde722f.png)

Thanks!

**Comment by GTriber** [comment]
I have manage to solve it.
 I manually disable all modules ( non prestashop ones ).  Error still was but updating went till the end.

Module that appears was cause the issue is called google-merchant-center ( wasnt up to date i think ).
Thank you for help.

Have a great week.

**Comment by khouloudbelguith** [comment]
@GTriber,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
