### ISSUE TITLE
Token Error Message on site Design -> Template & Logo 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17571]
Hi, 

if I go to **Design -> Template & Logo** I get the following token error message at the end of the site: 

![image](https://user-images.githubusercontent.com/44971218/74089060-60a57b00-4a9d-11ea-896c-67f1f24fba36.png)

PS 1.7.6.3
PHP 7.2.1
Server: nginx/1.14.0

**Comment by khalidzuhd** [comment]
SSL

**Comment by didi-2018** [comment]
@khalidzuhd  SSL is always on and on all pages

**Comment by didi-2018** [comment]
the trouble maker is module **ps_mbo** 

the same trouble maker as in my ticket **[#13255](https://github.com/PrestaShop/PrestaShop/issues/13255)**

I can not imagine that nobody else have that troubles with that module!?

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I did not manage to reproduce the issue with PS1.7.6.3 & Nginx 1.14.0.
https://drive.google.com/file/d/1L_1y_agkZUISuoVphS5SGDd7IhU1P66a/view
I used the ps_mbo module v1.1.1.
But it could be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15592#issuecomment-534950199

Thanks to check & feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith thanks for answering. What should I exactly check? I use ps_mbo Version 1.1.1 too

**Comment by khouloudbelguith** [comment]
@didi-2018, try to check this fix: https://github.com/PrestaShop/PrestaShop/issues/15592#issuecomment-534950199
Thanks to enable the HTTPS variables in your server, clear cache, check & feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith add this: **SetEnvIf X-Forwarded-Proto "https" HTTPS=on** to htaccess in PS main folder? If yes it brings nothing sorry :-(

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks to provide me your PHP info file.
You can follow this link: https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  can I send you link to my .php file as private message? Maybe it contains sensible datas. But I do not know how to send private message 🙈

**Comment by khouloudbelguith** [comment]
@didi-2018,
You can provide me the .php file by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  Email sent ;-)

**Comment by khouloudbelguith** [comment]
@didi-2018, it is ok in your case
![image](https://user-images.githubusercontent.com/16067358/74155440-e566d500-4c14-11ea-8df2-665a27fe52f0.png)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  I sent you error log in email ;-)

**Comment by khouloudbelguith** [comment]
@didi-2018, I just sent you an email.
Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith my host provider needs more information, please.

**Comment by khouloudbelguith** [comment]
@didi-2018, I did not manage to reproduce the issue in your shop.
It is OK, there is no token error.
I sent you a screen record by email.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  yes the token problem is gone. And have you checked this [#17584](https://github.com/PrestaShop/PrestaShop/issues/17584) during your login? This is still there.

**Comment by khouloudbelguith** [comment]
@didi-2018, so can we close this issue?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  I like to check if it is related to one of the other Presta Modules. Please keep it open till tomorrow. Is it okay?

**Comment by khouloudbelguith** [comment]
@didi-2018, okay!
Waiting for your feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith  I found the trouble maker, it is a NON-Prestashop Module. You can close it. Sorry 🙈

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks!
I will close the issue, feel free to open a new one when needed.

Thanks!
