### ISSUE TITLE
Error in the console: Failed to load `product_page.css` Or  `translations.css` net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17584]
>Edit by khouloud

We must use Nginx to reproduce the issue
**Steps to reproduce the issue:**
1. Go to the BO => Products page => Edit any product
2. See an error in the console
`1?_token=RrNvR8AZ34e…ngn-vjT5ZNpQtAI:171 GET http://127.0.0.1:8081/admin-dev/themes/new-theme/public/product_page.css?1.7.6.3 net::ERR_ABORTED 404 (Not Found)`
![image](https://user-images.githubusercontent.com/16067358/74235768-0b9d7b00-4cd0-11ea-81d0-010a5b0dcf56.png) 
=> PS: this issue is not reproduced with 1.7.7.x branch
3. Go to the BO => International => Translations page
4. Select the "Type of translation": BO and "Select your language"
5. Click on Modify
6. See an error in the console
`?lang=de&type=back&l…ngn-vjT5ZNpQtAI:172 GET http://127.0.0.1:8081//admin-dev/themes/new-theme/public/translations.css?1.7.6.3 net::ERR_ABORTED 404 (Not Found)`
![image](https://user-images.githubusercontent.com/16067358/74235933-659e4080-4cd0-11ea-887a-128376bea13a.png)
=> PS: this issue is reproduced with 1.7.7.x branch

In the PS1.7.5.2 on same server => OK
https://drive.google.com/file/d/1uACUc5q9l3zw_h2uA87Sd87rowrreI2F/view

such file does not exist in that path

**error log:**
```
2020/02/10 12:29:06 [error] 15940#15940: *59402 open() "/var/www/myshopdomian.com/web/prestafolder/admin/themes/new-theme/public/product_page.css" failed (2: No such file or directory), client: XXX.XXX.XX.XXX, server: myshopdomain.com, request: "GET /admin/themes/new-theme/public/product_page.css?1.7.6.3 HTTP/1.1", host: "myshopdomain.com", referrer: "https://myshopdomain.com/admin/index.php/sell/catalog/products/1560?_token=Te0qTSf-Ty9bnSiftRTdnOKblwu7yl8FsYdm7Bs7ruw"
2020/02/10 12:29:24 [error] 15942#15942: *59423 open() "/var/www/myshopdomain.com/web/prestafolder/admin34399run4/themes/new-theme/public/product_page.css" failed (2: No such file or directory), client: XXX.XXX.XX.XXX, server: myshopdomain.com, request: "GET /admin/themes/new-theme/public/product_page.css?1.7.6.3 HTTP/1.1", host: "myshopdomain.com", referrer: "https://myshopdomain.com/admin/index.php/sell/catalog/products/1560?_token=Te0qTSf-Ty9bnSiftRTdnOKblwu7yl8FsYdm7Bs7ruw"
2020/02/10 12:43:33 [error] 15943#15943: *59740 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /var/www/clients/client3844/web7857/web/prestafolder/classes/db/Db.php:794
Stack trace:
#0 /var/www/clients/client3844/web7857/web/prestafolder/config/alias.php(47): DbCore->escape('configuration', false)
#1 /var/www/clients/client3844/web7857/web/prestafolder/config/alias.php(52): pSQL('configuration')
#2 /var/www/clients/client3844/web7857/web/prestafolder/classes/Configuration.php(155): bqSQL('configuration')
#3 /var/www/clients/client3844/web7857/web/prestafolder/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()
#4 /var/www/clients/client3844/web7857/web/prestafolder/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')
#5 /var/www/clients/client3844/web7857/web/prestafolder/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load('Tools')
#7 /var/www/clients/client3844/web7857/web/prestafolder" while reading response header from upstream, client: 162.158.94.161, server: myshopdomain.com, request: "GET /admin/index.php/configure/advanced/performance/?_token=Te0qTSf-Ty9bnSiftRTdnOKblwu7yl8FsYdm7Bs7ruw HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7857.sock:", host: "myshopdomain.com", referrer: "https://myshopdomain.com/admin/index.php/configure/advanced/performance/?_token=Te0qTSf-Ty9bnSiftRTdnOKblwu7yl8FsYdm7Bs7ruw"
```

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

This is a fresh install PS1.7.6.3?
In the release 1.7.6.3, this file doesn't exist
https://github.com/PrestaShop/PrestaShop/tree/1.7.6.3/admin-dev/themes/new-theme/public
In which page, this error is displayed?
There are some steps to follow to get this error? or just open Back office?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  

**yes** fresh 1.7.6.3 install

on product page in back office

**Comment by khouloudbelguith** [comment]
@didi-2018, it is ok in my case
https://drive.google.com/file/d/18LfXQHOMAhwaxva3fwY11_vBxU5ZSlQe/view
What is the exact language/country did you use during the install?
Did you download the PrestaShop release from our official link?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  installed "Deutsch" (german) during install. Yes download from official Presta site

**Comment by khouloudbelguith** [comment]
@didi-2018, it is ok in my case with a fresh install using Nginx
I just have an error similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/17038 (related to the gamification module).
Did you install any custom module or custom theme?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith NO just installed fresh PS 1.7.6.3 and product_page.css is missing. I have send you an email with login details for my fresh install, there you can check please :)

**Comment by khouloudbelguith** [comment]
@didi-2018, I have the same issue with PS1.7.6.0 & PS1.7.6.2 & PS1.7.6.3 using Nginx.
But this issue is fixed in the next release 1.7.7.0
I attached a screen record
https://drive.google.com/file/d/17cqH7c9vPXxmFHEDMFGleAnsYzqTtJSa/view

Thanks to check & feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith  I can check if 1.7.7 is avaible ;-)

**Comment by khouloudbelguith** [comment]
@didi-2018, 1.7.7.0 is not available yet.
But you can download the latest build 1.7.7.x from [Nightly builds](https://storage.googleapis.com/prestashop-core-nightly/2020-02-11-1.7.7.x-prestashop_1.7.7.0.zip) where test reports are available here: https://nightly.prestashop.com/

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith okay, thank you!

I have the same issue with same path but /translation.css under international -> translation

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks for your feedback.
I manage to reproduce the issue with 1.7.7.x branch & PS1.7.6.3 & PS1.7.6.0 & PS1.7.6.1 & PS1.7.6.2.
https://drive.google.com/file/d/1pRR3H5gbtfdbgSWTLi7oAOhbcUYogxXt/view
![image](https://user-images.githubusercontent.com/16067358/74235306-fb38d080-4cce-11ea-8e99-85312bf7bda3.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PierreRambaud** [comment]
FYI, I reproduce both errors on Nginx and Apache. It's not depending on the http service:
```
GET /admin-dev/themes/new-theme/public/index.php?controller=AdminDashboard&token=9a9797785ae70b633af16e6c9bcdc361 HTTP/1.1
Host: ps-develop.localhost
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Accept: text/css,*/*;q=0.1
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Referer: http://ps-develop.localhost/admin-dev/index.php/improve/international/translations/?lang=en&type=back&locale=en-US&_token=dRH6AD7n68T9Fzd6Lqbpv_AfoR0Fct1I5tJQiZeK2oU
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6
Cookie: id_employee=1; iso_code=en; autoupgrade=0c25ef267a92c2a946a5d487315ec619; install_baf12c02e8ee=8gul5m57p5lmr5tn25t0ks2fts; PHPSESSID=bqchebvrrs8jfdqmjaujvepuaj; PrestaShop-64535a7e386d524be29031e743a7e746=def50200d5c03e3de110df2ef3c9a6ee7a56496decde974e89a06752ef8312663279a3216fcf890f424e434ccab2d943fde70cd4af029fbe107326c092e18564312d350e178f6a8430e7ee6c03dc999bf3830577c778af407989ef194bd12866c4ca4c71d6b68d45637a66dfa19dc2b1daf30325136e91188ed4c7ef2770e99b32e07eca7bb6aab568c5f671f1c3beb6a28affb22ebbb960150e560043d5fb971aae21b5b6876c14d9dbc8d05e8dab135dc36c7262b291862510b44282b7c4fb8cd1724777c5ef292d8deedad315b195651820c9684f9b792702a07b5dcf8ff7308a1fe456d03bed4cd60be3a9abe8e021d37782943a8c0c96c21f2207806515f33bbe86975c28e4cb51bf3f5e7499146a42ce2d1f8400165c9df92fbe14aed856799dfdf832dfc5ee24923449a7bb299d9e5e5e754912d5feefd78f3eb476d4f54f8a3889429d6142818f4754f29a6601ea62ce3676ba898c301f59737b780e269b0a5977898022f0bc13afabd1e720299678

HTTP/1.1 404 Not Found
Date: Wed, 12 Feb 2020 09:19:27 GMT
Server: Apache/2.4.38 (Debian)
Status: 404 Not Found
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-XSS-Protection: 0
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
```

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17613

**Comment by didi-2018** [comment]
@matks 
I removed:

{% block stylesheets %}
  {{ parent() }}
  <link rel="stylesheet" href="{{ asset('themes/new-theme/public/product_page.css') }}">
{% endblock %}
 
now dev tools show:

![image](https://user-images.githubusercontent.com/44971218/75117910-0b10c700-5676-11ea-9fa3-74fcc934f727.png)

and the same with removing code:

{% block stylesheets %}
  {{ parent() }}

  <link rel="stylesheet" href="{{ asset('themes/new-theme/public/translations.css') }}">
{% endblock %}

![image](https://user-images.githubusercontent.com/44971218/75118016-9e49fc80-5676-11ea-82fa-73a70a9124a7.png)

**Comment by matks** [comment]
@didi-2018 So it works ? 😊 I cant see the error anymore

**Comment by didi-2018** [comment]
@matks  The mentionted errors are gone and now are new there. Now the fonts cant be downloaded. I dont know if that is really a fix if after that 8 new ones are there.
