### ISSUE TITLE
Error http 500 on page module

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#17599]
Good morning when I try to enter the modules page it gives me 500 server error and if I activate the debug mode it gives me this error (attached)
How can I proceed?

Thanks for help.
![error](https://user-images.githubusercontent.com/56969939/74232391-f8d37800-4cc8-11ea-9fd9-185b253dbb4c.png)

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

You have an issue with the `blockcontact` module.
If you are using this one: https://github.com/PrestaShop/blockcontact, this module is compatible with PS1.6 and it has been remade for PrestaShop 1.7: https://github.com/PrestaShop/ps_contactinfo

Thanks to check & feedback.

**Comment by Webgaict** [comment]
Hi,
I use version 1.7.5.1 so do I have to upload those files to the ps_contactinfo folder?

**Comment by khouloudbelguith** [comment]
@Webgaict, you need just to remove the folder `modules/blockcontact`.
Now, you can access to the BO => Module Catalog page => search for the `ps_contactinfo` & install it if not installed.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
