### ISSUE TITLE
No bankwire payment method possible on 1 shop, other shops work fine (multistore)

### ISSUE THREAD

**Issue by johanmeer** [PrestaShop/PrestaShop#17595]
Hi, since a while we facing a issue on one of one of 6 shops. On one the bankwire paymentmethod is not working anymore. On the other sites it is working fine. 

Debug is showing this: 
![Schermafbeelding 2020-02-10 om 23 23 40](https://user-images.githubusercontent.com/47300140/74196206-09e69f80-4c5d-11ea-89ed-fe58fada526e.png)

Already tried to switch theme, that is not working. Also reset the bankwire module. It is the standard module that comes with the installation of prestashop. Also disabled cache etc.. 

I hope there is someone who can help me

Thanks! 

This is the error log: 

`[Mon Feb 10 23:20:59.075692 2020] [proxy_fcgi:error] [pid 3121:tid 139768184608512] [client 62.194.59.29:44866] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function addOrderPayment() on null in /var/www/vhosts/makeup4all.nl/httpsdocs/classes/PaymentModule.php:365\nStack trace:\n#0 /var/www/vhosts/makeup4all.nl/httpsdocs/modules/ps_wirepayment/controllers/front/validation.php(64): PaymentModuleCore->validateOrder(174530, '10', 14.95, 'Bankoverschrijv...', NULL, Array, 1, false, '162238a022701bd...')\n#1 /var/www/vhosts/makeup4all.nl/httpsdocs/classes/controller/Controller.php(280): Ps_WirepaymentValidationModuleFrontController->postProcess()\n#2 /var/www/vhosts/makeup4all.nl/httpsdocs/classes/Dispatcher.php(515): ControllerCore->run()\n#3 /var/www/vhosts/makeup4all.nl/httpsdocs/index.php(28): DispatcherCore->dispatch()\n#4 {main}\n thrown in /var/www/vhosts/makeup4all.nl/httpsdocs/classes/PaymentModule.php on line 365', referer: https://www.bellamilan.nl/module/supercheckout/supercheckout`

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Could you please try to re-install the ps_wirepayment module with removing the folder  `modules/ps_wirepayment`, clear cache, check & feedback.
Also, you have an error with the `supercheckout` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @johanmeer,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
