### ISSUE TITLE
Empty option in template compilation's select of performances page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17590]
**Describe the bug**
The first option of the template compilation's dropdown in performance page is empty

**To Reproduce**
1. Go to Advanced parameters > Performances
2. Click on 'Template compilation' dropdown

**Screenshots**
![capture d'écran_2296](https://user-images.githubusercontent.com/13449658/74168547-38975280-4c2a-11ea-864a-f63dfd080b65.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17612
