### ISSUE TITLE
Product comments v10.0.0 - from PrestaShop

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#17591]
**Describe the bug**
I have updated Prestashop 1.7.5.1 to 1.7.6.3. Installed Product comments v10.0.0 - from PrestaShop
But they are not there, not on product page.
I went to configuration, set everything On. Cleaned cache, same thing.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.3

**Comment by didi-2018** [comment]
@GTriber have you checked the hooks of module? The module should be hooked in the following hooks:

![image](https://user-images.githubusercontent.com/44971218/74175073-646c0580-4c35-11ea-9d82-d19a069a614f.png)

If not, hook it there.

**Comment by khouloudbelguith** [comment]
Hi @GTriber,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by GTriber** [comment]
@didi-2018 @khouloudbelguith 

Hook and changing PHP did the job!!!

I had other outdated module hooked in that place. Wish i have both but sadly i cant.

Thank you so much :)

**Comment by khouloudbelguith** [comment]
@GTriber, thanks for your feedback.
Since it is fixed, I will close the issue.

Thanks!
