### ISSUE TITLE
Backend notification delay

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#17609]
Hello

I did upgrade my PS to 1.7.6.3 i was facing an error with mysql connection when the upgrade has finished.

so I changed the password and replace it on setting file and it works now

I noticed that orders and new customers notification are coming in delay

Even when I check the orders menu and reply to my customers the notification come after that.

Version de PrestaShop : 1.7.6.3
Version de MySQL : 10.3.22-MariaDB
Version du logiciel serveur : Apache
Version de PHP : 7.1.33
Limite de mémoire : 4096M
Temps maximal d'exécution : 7000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

> did upgrade my PS to 1.7.6.3 i was facing an error with mysql connection when the upgrade has finished

What does the exact error occur?

>I noticed that orders and new customers notification are coming in delay

How long is the delay?

Thanks!

**Comment by go-sudo** [comment]
Hello

between 2 and 4 hours and for some orders it does not show even after 24 hours

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by go-sudo** [comment]
Hello @khouloudbelguith 

I appreciate your help and here is the apache and nginx errors log

[apache.txt](https://github.com/PrestaShop/PrestaShop/files/4192045/apache.txt)

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo,

You have these errors:
>2020-02-11 18:02:40	Error	78.116.242.111		[client 78.116.242.111] ModSecurity: [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/50_plesk_basic_asl_rules.conf"] [line "2807"] [id "33340814"] [rev "3"] [msg "Protected by Atomicorp.com Basic Non-Realtime WAF Rules: Remote File Injection attempt in ARGS"] [data "https:/"] [severity "CRITICAL"] Warning. Match of "beginsWith http://%{SERVER_NAME}/" against "MATCHED_VAR" required. [hostname "iptv366.com"] [uri "/chat/server.php"] [unique_id "XkLeMNwVjUe4LyAHQiX3MwAAAVc"], referer: https://iptv366.com/fr/module/cdkeys

You should check your host.

>2020-02-12 07:50:30	Error	188.62.242.218		AH01068: Got bogus version 10, referer: https://iptv366.com/modules/spthemeconfigurator/views/css/front/configCss-1.css

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by go-sudo** [comment]
Hello @khouloudbelguith 

I appreciate your help ; problem resolved 

> Hello,
> 
> The reported error message is not related to the website security at this case.
> 
> The cause of the error appearing is the false positive detection by ModSecurity.
> From the error message I have found that one of the website's modules sends request which falls under one of the ModSecurity rules.
> To make the error disappear, you need to disable this ModSecurity rule.
> 
> 1. Log into Plesk.
> 2. Go to Domains >  iptv366.com > Web Application Firewall.
> 3. Specify the ID of the rule from the error message, it is 33340814 in the section "Switch off security rules" and click OK.
> 
> Please let me know if you need further assistance.
> Best regards,
> 
> Plesk

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, Great!
Feel free to open a new one when needed.

Thanks!
