### ISSUE TITLE
displayBanner hook is missing

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17606]
**Describe the bug**
displayBanner hook is missing in database and in hook.xml

**Additional information**
PrestaShop version: 1.7.*
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I have the same issue with PS1.7.6.3 & PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/74251343-4a412e80-4cec-11ea-9574-9f67876d13ae.png)
With PS1.6.1.24, it is not missing
![image](https://user-images.githubusercontent.com/16067358/74251401-5f1dc200-4cec-11ea-9b72-007efac5a932.png)

I’ll add this to the debug roadmap.

Thanks!

**Comment by jf-viguier** [comment]
Thanks @khouloudbelguith can you paste here the hook part in hooks.xml of PS1.6.1.24 ?

**Comment by khouloudbelguith** [comment]
@jf-viguier,

https://github.com/PrestaShop/PrestaShop/blob/1.6.1.24/install-dev/data/xml/hook.xml

Thanks!

**Comment by jf-viguier** [comment]
The hook is not there, I guess it's a module that have created the hook in database with registerHook

**Comment by PierreRambaud** [comment]
As I said in your pull reuqest, the hook should be created by the module and not the Core :thinking:

**Comment by khouloudbelguith** [comment]
@jf-viguier, it is the Banner block module.
![image](https://user-images.githubusercontent.com/16067358/74253259-26cbb300-4cef-11ea-8dcf-d43118dd72ae.png)

@PierreRambaud said, if we install a module that create the `displayBanner` hook, it will be displayed.

Thanks!

**Comment by jf-viguier** [comment]
@PierreRambaud I don't understand, the hook is launched in header.tpl in the core classic theme. We have modules that uses that hook : it has to be in the database and hooks.xml.

**Comment by jf-viguier** [comment]
> As I said in your pull reuqest, the hook should be created by the module and not the Core 🤔

@PierreRambaud I disagree. The hook is launched in the core, it's in the doc and should be created by the core.
We don't use prestashop banner modules, we use our own banner module with is a modern widget module that don't have hardcoded hooks but can be hooked to any hook in positions bo menu.
This hook has to be in the database & hooks.xml, otherwise it will not be in the list of this bo page.

By the way, there is no other hook on top of the header block.

**Comment by PierreRambaud** [comment]
Ohh I understand (Sorry, little bit tired :sweat_smile: )
My bad, at least I learnt something new today ! 
I validate your pull request :)

**Comment by jf-viguier** [comment]
Thanks @PierreRambaud take care of you.
