### ISSUE TITLE
Error variable doesn't exist when editing a product quantity for an order

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17618]
**Describe the bug**
Error when editing a product quantity for an order

**To Reproduce**
1. Go to the migrated order listing
2. View an order in "awaiting payment"
3. Edit the product quantity
4. Click on Save
5. See 500 error in the console

**Screenshots**
![capture d'écran_2315](https://user-images.githubusercontent.com/13449658/74335782-3acdee00-4d9d-11ea-83d2-99b2f2b211d3.png)

![capture d'écran_2314](https://user-images.githubusercontent.com/13449658/74335789-3c97b180-4d9d-11ea-9987-b2313be494f3.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17641
