### ISSUE TITLE
Cant install in shop - 1.7.4.3

### ISSUE THREAD

**Issue by ROGPreez** [PrestaShop/PrestaShop#17629]
Hi there, i was looking forward to using this module, but it doesen't seems to work on mu 1.7.4.3 store?

Have you any fixes?
Try to install through modules on admin page.

**Comment by khouloudbelguith** [comment]
Hi @ROGPreez,

What is the exact module do you need to install it?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ROGPreez,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
