### ISSUE TITLE
Problem ContextErrorException

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#17627]
Hello everyone, 
hope you can help me. 
I notice with Debugmode that I have this issue. 
What should I do?
Attached photo of the problem.
PS version: 1.7.5

<img width="1295" alt="Schermata 2020-02-12 alle 17 25 31" src="https://user-images.githubusercontent.com/47249256/74355899-c0fa2c80-4dbd-11ea-9ed5-7e6aa26ac135.png">

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

It is a theme issue.
![image](https://user-images.githubusercontent.com/16067358/74356785-39152200-4dbf-11ea-889c-9cf65fddcf96.png)
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
