### ISSUE TITLE
Bug in select cover image product

### ISSUE THREAD

**Issue by nesrine3ayadi** [PrestaShop/PrestaShop#17623]
Hello,
I use Prestashop 1.7.6.0, I have a problem in product detail: i can not change cover image.
The right form which supposed to be shown on th right does not exist
Morever, i have this errors on console !
Any help please ??

![image](https://user-images.githubusercontent.com/11909333/74347207-05cb9680-4db1-11ea-8116-9b1dc9f9e0df.png)

**Comment by khouloudbelguith** [comment]
Hi @nesrine3ayadi,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nesrine3ayadi** [comment]
Version de PrestaShop : 1.7.6.0
Version de PHP : 7.2.27
Version du logiciel serveur : Apache
Version de MySQL : 5.5.64-MariaDB
Informations sur votre serveur Linux #1 SMP 

I dont have acces to Server, i just can access to BO and FTP files
Is that enough for you ?

**Comment by khouloudbelguith** [comment]
@nesrine3ayadi, 
You need to enable debug mode in your store and debug request which is sent for product edit in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. edit product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by nesrine3ayadi** [comment]
![image](https://user-images.githubusercontent.com/11909333/74349953-4b8a5e00-4db5-11ea-89e7-f9f3dc4518c7.png)
![image](https://user-images.githubusercontent.com/11909333/74350054-71affe00-4db5-11ea-9c4b-83d45b95f4ab.png)
![image](https://user-images.githubusercontent.com/11909333/74350075-7c6a9300-4db5-11ea-9820-4cdf21ead4c5.png)

So ?

**Comment by khouloudbelguith** [comment]
@nesrine3ayadi, you have an error 500 in your console
Click on the Network tab
![image](https://user-images.githubusercontent.com/16067358/74350707-5f828f80-4db6-11ea-8802-ae3157320002.png)

 you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by nesrine3ayadi** [comment]
![image](https://user-images.githubusercontent.com/11909333/74350980-c86a0780-4db6-11ea-839c-55930570417a.png)

**Comment by khouloudbelguith** [comment]
@nesrine3ayadi, thanks to provide me all the exception displayed.

Thanks!

**Comment by nesrine3ayadi** [comment]
![image](https://user-images.githubusercontent.com/11909333/74351450-6c53b300-4db7-11ea-89dd-2366ed383184.png)
![image](https://user-images.githubusercontent.com/11909333/74351491-75dd1b00-4db7-11ea-8c25-61f60847f89f.png)
![image](https://user-images.githubusercontent.com/11909333/74351531-81304680-4db7-11ea-9810-9a8ee21b608c.png)
![image](https://user-images.githubusercontent.com/11909333/74351576-960cda00-4db7-11ea-9033-16dddab8eedf.png)

Do you mean this !

**Comment by khouloudbelguith** [comment]
@nesrine3ayadi, this issue occurs with the `posstaticblocks` module.
![image](https://user-images.githubusercontent.com/16067358/74352395-b8532780-4db8-11ea-8467-a2be2930946c.png)
As it's not a module provided by Prestashop, we can't do anything with this.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
