### ISSUE TITLE
Category Change in product

### ISSUE THREAD

**Issue by LordMarZ** [PrestaShop/PrestaShop#17635]
Hello guys, i have found an issue, maybe you know how to fix it

i have change the main category in some products on my website, and now those products are not showing

just like this one: 
https://darksidebros.com.uy/superheroes/thanos-gold-infinity-gauntlet-mini-replica-13cm.html

i have rebuilt the search index and clear cache (from BO and FTP) but still cant get the product to show.

the product shows in the category pages: 

https://darksidebros.com.uy/jolisearch?s=gauntlet (the 3rd product at the right) but when you open the link, there is no product showing. 

also this other issue that started when changing category from products.

this product:
https://darksidebros.com.uy/jolisearch?s=mountain

when i open it, instead of showing no product, it shows another product... 

thanks for your help!

**Comment by khouloudbelguith** [comment]
Hi @LordMarZ,

Thanks for your report.
In the BO => Catalog => Product details page => Options Tab => what is the Visibility of your Product?
![image](https://user-images.githubusercontent.com/16067358/74418755-2ba47a00-4e49-11ea-9a28-acdda775734d.png)

Thanks!

**Comment by LordMarZ** [comment]
Hello there, visibility is everywere, as it was before changing category

thanks!

**Comment by khouloudbelguith** [comment]
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by LordMarZ** [comment]
i have fixed it. 

the error started happening when i changed the main category for a lot of products. meaning the links changed

i have a "friendly urls" module, i had to clear the modules cache in order to fix all the new urls to the products that changed category

thanks for your help and sorry for taking your time, sometimes an answer leads to another way to fix it.

have a nice day and keep up the excellent job you are doing!
cheers

**Comment by khouloudbelguith** [comment]
@LordMarZ, thanks for your feedback.

As it's not a provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
