### ISSUE TITLE
Faceted Search - The price filter is not working when using a non default currency

### ISSUE THREAD

**Issue by IsaacVe** [PrestaShop/PrestaShop#17632]
**Describe the bug**
When you search for a currency that is not the default, the price filter does not work.

**Screenshots**
With the default currency it works
![image](https://user-images.githubusercontent.com/17584143/74374681-dca90700-4dac-11ea-9ea4-20fa3cf71b53.png)
But when switching to another currency it doesn't work anymore
![image](https://user-images.githubusercontent.com/17584143/74374660-d61a8f80-4dac-11ea-9e95-59b0c79802c6.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment]
Hi @IsaacVe,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.3 & ps_facetedsearch v3.4.1.
https://drive.google.com/file/d/1MX0cuTCW01ACRmXB75MnVG_Fj_NRnBOT/view
What is the exact version `ps_facetedsearch` did you use?
Could you please try to configure it by editing the template & rebuilding the entire price index & building attributes & features indexes & clearing the cache.

Thanks to check & feedback.

**Comment by IsaacVe** [comment]
I'm using 1.7.6.2 & ps_facetedsearch v3.4.1. to reproduce it you must import the Perú location package.

with the sign "PEN" it works but with the new sign "S/" after downloading the Peru location package, the price filter no longer works.
![image](https://user-images.githubusercontent.com/17584143/75182109-ad2fbe00-570d-11ea-9ab2-8837d3c1fcc5.png)

**Comment by khouloudbelguith** [comment]
@IsaacVe, I imported the Peru pack, But the currency added is `PEN` automatically.
It is not "S/".
So, in the FO, search with a price is well working in the second currency `PEN`.

I attached a screen record
https://drive.google.com/file/d/1Qyk4Uoo_vPQcuPdpPgQ-v6ZYo3W1MFKq/view
Thanks to check & feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
