### ISSUE TITLE
While Prestashop handling web service request, debug mode is working in reverse manner

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#17639]
**Describe the bug**
while requesting prestashop web service if there is any error and debug mode is disabled then still error is shown in the response and when the debug mode is enabled then it doesn't show that error.

**To Reproduce**
1. Go to ['prestashop/classes/webservice/WebserviceRequest.php'](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php)
2. If there are any PHP issues in this file for example
```php 
$this->xyz = $params['xyz'];  // i added it only for demonstration
```
3. Now enable and configure the Prestashop web service and request any API. for example : https://domain.com/prestashop/api/addresses/1?ws_key=UK83DACD4K9YECBTK65BNK8YMKDRGS7S

4. If Prestashop debug mode is enabled then it will give an error response as shown in the below attachment.
![WEBSERVICE](https://user-images.githubusercontent.com/39614089/74422668-f746b300-4e74-11ea-9c90-0487646d8d3f.png)

5. If Prestashop debug mode is disabled then it will not show the error.

**Additional information**
PrestaShop version: 1.6.x.x, 1.7.x.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

I tried with PS1.7.6.3
I added this line `$this->xyz = $params['xyz'];` before this: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php#L239

When debug mode is disabled, I have error 500
When debug mode is enabled, I have this exception
![image](https://user-images.githubusercontent.com/16067358/74426967-9a3c0480-4e56-11ea-9c22-1b18c10445ab.png)


Thanks to check & feedback.

**Comment by surajkumar-webkul** [comment]
@khouloudbelguith 
Please put `$this->xyz = $params['xyz'];` it anywhere after this line https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php#L498 where custom error handler has been already set up.
For example, put that code at [this line](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php#L513)

**Comment by khouloudbelguith** [comment]
@PeeyushAgrawalWebkul, no error founded in this case.
https://drive.google.com/file/d/1DLGoesxjHdbIQV4PvSh49OePZuPIVMrj/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
