### ISSUE TITLE
1-Click Upgrade From 1.7.6.1 to 1.7.6.3 not working

### ISSUE THREAD

**Issue by z72diego** [PrestaShop/PrestaShop#17631]
Hi, just tried to upgrade, two times, from 1.7.6.1 to 1.7.6.3 using the 1-Click upgrade module but no luck... here is the log:

> Analyzing the situation...Shop deactivated. Now downloading... (this can take a while)
> Download complete. Now extracting...
> File extraction complete. Removing sample files...
> All sample files removed. Now backing up files.
> File backup skipped.
> Database backup skipped. Now upgrading files...
> 22236 files will be upgraded.
> 21436 files left to upgrade.
> 20636 files left to upgrade.
> 19836 files left to upgrade.
> 19036 files left to upgrade.
> 18236 files left to upgrade.
> 17436 files left to upgrade.
> 16636 files left to upgrade.
> 15836 files left to upgrade.
> 15036 files left to upgrade.
> 14236 files left to upgrade.
> 13436 files left to upgrade.
> 12636 files left to upgrade.
> 11836 files left to upgrade.
> 11036 files left to upgrade.
> 10236 files left to upgrade.
> 9436 files left to upgrade.
> 8636 files left to upgrade.
> 7836 files left to upgrade.
> 7036 files left to upgrade.
> 6236 files left to upgrade.
> 5436 files left to upgrade.
> 4636 files left to upgrade.
> 3836 files left to upgrade.
> 3036 files left to upgrade.
> 2236 files left to upgrade.
> 1436 files left to upgrade.
> 636 files left to upgrade.
> All files upgraded. Now upgrading database...
> Database upgraded. Now upgrading your Addons modules...
> 62 módulos serán actualizados.
> 55 modules left to upgrade.
> 45 modules left to upgrade.

**Comment by z72diego** [comment]
Upgrade log:
[upgrade_log.txt](https://github.com/PrestaShop/PrestaShop/files/4194494/upgrade_log.txt)

**Comment by khouloudbelguith** [comment]
Hi @z72diego,

Thanks for your report.
As you can see in your log file, there are no errors during the upgrade.
The files are well upgraded
The Database is well upgraded
During the upgrade of your modules, the upgrade is just stopped.
What is the exact version of the 1-click upgrade did you use?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by z72diego** [comment]
Hi @khouloudbelguith yes, it stops when it reaches the modules update, i don't understand why. In the log attached there is an error:

Alert detected during install.
[INTERNAL] /var/www/vhosts/distribuidorademafer.com.ar/httpdocs/classes/controller/FrontController.php line 353 - Trying to get property 'logged' of non-object

**Comment by z72diego** [comment]
1-Click Upgrade v4.10.1

**Comment by khouloudbelguith** [comment]
@z72diego, do you have some custom modules installed?
Your issue seems similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/17572

Thanks to check & feedback.

**Comment by z72diego** [comment]
Yes, i have a few ones. Anyway it's rare. Prestashop Core should be updated with no problems although I have installed any module.. Even before updating, I selected "disable non-native modules". I will try manually disabling the non-native modules and try to update.

**Comment by khouloudbelguith** [comment]
@z72diego, thanks for your feedback.
This option is not working in PS1.7
![image](https://user-images.githubusercontent.com/16067358/74453672-ff0d5400-4e82-11ea-8686-92e2f741a70d.png)
as reported here: 
https://github.com/PrestaShop/PrestaShop/issues/9965

Waiting for your feedback.

**Comment by z72diego** [comment]
Hi @khouloudbelguith just tried an upgrade disabling first all non-Prestashop modules and the same thing happened but not a single module was upgraded, pleas check the log:

> All files upgraded. Now upgrading database...
> Database upgraded. Now upgrading your Addons modules...
> [Ajax / Server Error for action upgradeModules] textStatus: "error " errorThrown:"Service Unavailable " jqXHR: "

I disabled all modules from the module area clicking "disable" in the option menú.

Despite this error, ps and the database seems to have been updated correctly. I will continue testing..

I notice that although the modules are deactivated, the menus are still available.. and you can even enter the configuration. in PS 1.6 this was more neat. It really amazes me how there are such basic flaws in this PS 1.7.

**Comment by z72diego** [comment]
Tested a lot of modules and functions and everything seems to be ok, with the passing of the days I will know if there is any error.

Thanks for your help @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@z72diego, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!
