### ISSUE TITLE
Blank page while trying to open manage profile

### ISSUE THREAD

**Issue by yourizuring** [PrestaShop/PrestaShop#17646]
**Describe the bug**
Ap page builder works fine without themes, but doesn't work when the themes are installed at all.

**To Reproduce**
1. Go to Module Manager
2. Click on Ap Page Builder
3. Click on Manage Profile
4. See the blank page.

**Screenshots**
![image](https://user-images.githubusercontent.com/47860706/74430674-aa0b1700-4e5d-11ea-98b4-3d9ad65098d4.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: Not specified

**Comment by khouloudbelguith** [comment]
Hi @yourizuring,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
