### ISSUE TITLE
 Uncaught Exception: Kernel Container is not available in /Adapter/ContainerFinder.php:77

### ISSUE THREAD

**Issue by roditi3811** [PrestaShop/PrestaShop#17644]
**Describe the bug**
This error appears only in backoffice, when browsing the modules or orders pages.
I see it appears when installing a clean PS v1.7.6.3 downloaded from the official site, so it looks like the error is straight from PS?
The error appears even if I completely delete the default payments modules.
Is there any way of knowing who exactly is producing this error?

**To Reproduce**
1. Go to admin backend
2. Click on 'modules' or 'orders' or 'dashboard' or etc....
3. See error in 'error.log'

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: PHP 7.3.14

Installed default PS release (wget https://download.prestashop.com/download/releases/prestashop_1.7.6.3.zip)

Error.log output:

`[error] 10154#10154: *5913833 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /XXX/src/Adapter/ContainerFinder.php:77
Stack trace:
#0 /XXX/classes/Tools.php(796): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer()
#1 /XXX/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))
#2 /XXX/classes/Notification.php(133): ToolsCore::displayPrice(20.9, Object(Currency), false)
#3 /XXX/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '0')
#4 /XXX/adminvee/ajax.php(125): NotificationCore->getLastElements()
#5 {main}
  thrown in /XXX/src/Adapter/ContainerFinder.php on line 77" while reading response header from upstream, client: XXX, server: XXX, request: "POST /admin/ajax.php?rand=1581588984761 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "XXX", referrer: "https://XXX/admin/index.php?controller=AdminDashboard&token=967ac7cbb5c5317e9548a884d0b4c730"
`

**Comment by khouloudbelguith** [comment]
Hi @roditi3811,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by roditi3811** [comment]
Oh....I understand, thanks for the fast reply.

**Comment by khouloudbelguith** [comment]
@roditi3811, thanks!
Feel free to open a new one when needed.

Thanks!

**Comment by roditi3811** [comment]
Sure, no worries.
