### ISSUE TITLE
[ORDER PAGE] Prev/Next order button 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17648]
Missing part of the order page migration and redesign project.

**User Storie**

As a merchant, I want to go to the next order without leaving the page.

**Detailed specification**
On the action bar button, add the arrow next prev on the left
![image](https://user-images.githubusercontent.com/43613217/74432693-3ff37180-4e5f-11ea-82f3-5488c6d6a802.png)

WIP specs to update it
https://invis.io/YKTGGFZAMCB#/388660077__Order_Details_-_Private_Note

**Comment by matthieu-rolland** [comment]
This will be tested by QA during the test of the 1.7.7 release.

**Comment by colinegin** [comment]
ping @Robin-Fischer-PS i close this issue as we have a scenario related to this feature in our order tests. Is this ok for you ?

**Comment by Robin-Fischer-PS** [comment]
@colinegin Yes, OK for me. I'm going to add this to our QA scenario :)
