### ISSUE TITLE
Provide useful data attributes into Link Widget hook list for puppeter tests

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17657]
PR https://github.com/PrestaShop/PrestaShop/pull/17477 has broken some puppeeter tests because they used the hook ID selectors. Modifying the hook list has modified the `<li>` IDs generated from hook list. Basically if we modify the order of items in hook.xml file, it changes the IDs 😄 

The puppeeter tests should not rely on such generated IDs which can change often. Instead Link Widget should provide reliable attributes targetable by puppeeter tests. @boubkerbribri and I agreed on a `data-hook-name` attribute.

We need to add these `data-hook-name` to `<li>` items in Link Widget hook list so that QA team can adapt their tests and fix them in a reliable way.

**Comment by matks** [comment]
Critical because it breaks nighthly tests

**Comment by SimonGrn** [comment]
I think I love you

**Comment by Progi1984** [comment]
After discussion with @boubkerbribri, we need to add 
- `data-hook-name` on `select2 li`
- `data-hook-name` on  `div class="card js-grid-panel" id="{{ grid.id }}_grid_panel"`  (`src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid_panel.html.twig`)

**Comment by colinegin** [comment]
Has it been done already ? Is it on the develop branch ?

**Comment by Progi1984** [comment]
It's a `WIP` from my side :)

**Comment by Progi1984** [comment]
PR PrestaShop/ps_linklist#88

**Comment by boubkerbribri** [comment]
Thank you @Progi1984 , this was fixed by PrestaShop/ps_linklist#88 :tada:
