### ISSUE TITLE
ppxo_paypal_legacy_gettoken_initxo when user close dialog before load ?

### ISSUE THREAD

**Issue by LINUX3932** [PrestaShop/PrestaShop#17654]
When user closes the [PayPal] dialog pop up before it fully loads, the paypal buy button no longer works unless the page is refeshed by the user.

The error reported is **ppxo_paypal_legacy_gettoken_initxo**

Issue referenced in [this post](https://github.com/paypal/paypal-checkout-components/issues/681#issuecomment-402312665)

> This is now an unsupported integration. I would suggest asking prestashop to upgrade to the latest PayPal integration.

PrestaShop version: 1.7.6.3
Current theme in use: classic

**Comment by khouloudbelguith** [comment]
Hi @LINUX3932,

Did you use this module: https://addons.prestashop.com/en/payment-card-wallet/46347-prestashop-checkout-built-with-paypal.html?

Thanks!

**Comment by LINUX3932** [comment]
Module used:
PayPal v5.1.1 - by PrestaShop.

Many thanks

**Comment by khouloudbelguith** [comment]
@LINUX3932,

As it's not a module provided by the Prestashop Core team, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it: https://addons.prestashop.com/en/contact-us?id_product=1748
Thanks!
