### ISSUE TITLE
Having CSS Issues with tv_electronic_electron_1_7_v1 theme purchased on Prestashop

### ISSUE THREAD

**Issue by Sifaso** [PrestaShop/PrestaShop#17658]
I am having many css files inside public_html/themes/tv_electronic_electron_1_7_v1/assets/css that is confusing me. 
Inside  all_theme_custom_1_1.css, I saw the first and second color I applied through the back office of my prestashop.

Please I need help on how I can change the mega menu color, font-size, cart icon and account sign in icon color. All are on the header. I also want to change the footer background color.
Thanks as I look forward for solution.

**Comment by khouloudbelguith** [comment]
Hi @hostsifa,

As it's not the default theme, provided by Prestashop "tv_electronic_electron_1_7_v1", we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
