### ISSUE TITLE
Monitoring page - The title List of products without description is not correct

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17653]
**Describe the bug**
In the BO => Catalog => Monitoring Page, the title "List of products without description " is not correct.
It should be like this: "List of products without description **and** summary" if this is the wanted behavior
Ping @PrestaShop/prestashop-product-team what do you think? what is the exact behavior in this case, display all products without description **and** summary or display all products without description **only**?

**To Reproduce**
1. Go to BO => Catalog => Product Page
2. Create a new Product with an empty description **and** not an empty summary
3. BO => Catalog => Monitoring Page => In the section  "List of products without description ", the last product is not displayed

**Screenshots**
https://drive.google.com/file/d/1bgYA-xvmi3VnPPvldLI1VCcqgToHREXE/view

**Additional information**
PrestaShop version: 1.7.5.2, 1.7.6.3, 1.7.7.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by colinegin** [comment]
I agree with you @khouloudbelguith, we should specify "description and summary".
@LouiseBonnard do you think we could change the string ? Wdyt ?

**Comment by LouiseBonnard** [comment]
Indeed, the title of this section does not fully match the behavior. My opinion is: the behavior should match the wording. So all products that have no description, whether or not the summary field is empty, should be listed here.

But that being said, it is probably easier to adapt the wording to the current behavior. In this case, the title of this section should be _List of products without description and summary_ in _Admin.Catalog.Feature_.
