### ISSUE TITLE
Bug price impact of declinations in AllShop

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#17669]
Hi, 

I have a problem with the price impacts of the declinations. I have a site with 12 shops and I would like to put price impacts for each declination.
When I put myself in all shop, I can see the change in BO but in the front, the impact is not there and also when I see the BO in the FR shop, or others shop, I see that there is no impact.

You can see screenshots

Thanks!

**Screenshots**
![all-shop](https://user-images.githubusercontent.com/25744417/74510692-98307f00-4f04-11ea-9ead-d26dc94363da.JPG)
![shop-fr](https://user-images.githubusercontent.com/25744417/74510706-9ebef680-4f04-11ea-8570-5c7b302c933a.JPG)
![shop-de](https://user-images.githubusercontent.com/25744417/74510713-a383aa80-4f04-11ea-8c48-b80dec0e668e.JPG)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @ShaimyWinda,

I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1fJblDw-u9IZiQeG05DgW0VJ8ifn2sw47/view
Thanks to check & feedback.

**Comment by ShaimyWinda** [comment]
@khouloudbelguith Hi,

Can you test in PS 1.7.6.0 ?

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, it is ok with PS1.7.6.0 also
https://drive.google.com/file/d/15WN4g-bgOFYCP1yXwi00_IMS7IQhqB46/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith ,

Here's the only error I have 
`[Fri Feb 14 14:06:29.262479 2020] [php7:error] [pid 22713] [client 45.90.224.168:40914] script '/var/www/preprod.moondreamwebstore.fr/adminmoon/themes/new-theme/public/index.php' not found or unable to stat, referer: https://fr.preprod.moondreamwebstore.fr/adminmoon/index.php/sell/catalog/products/122?_token=3nRyB3x8zQoBHvWQ8VmoFXWpODShSl2jNHEsbsClsAM`

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, this error, I think is another problem similar to this: https://github.com/PrestaShop/PrestaShop/issues/17584
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. EDit the product price impact
6. save the product
7. wait for an error, you should see red request information in Network tab
8. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith 
I don't have a mistake, I see a JSON. On the other hand in the json, I don't see impact_price.

Thanks

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, It will help us if you can attach a screen record when using the dev tools.

Thanks!

**Comment by Gaja-A** [comment]
@khouloudbelguith , I hereby attach the screen record
https://drive.google.com/file/d/1k8z6TUWhAHyaMfOGQKktPPKJ37nSguaP/view

Thanks !

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, those shops are in the same default Group? is it?
What is the exact configuration of your shop Group?
![image](https://user-images.githubusercontent.com/16067358/75260673-4207e980-57ea-11ea-90d9-dca4278a0b80.png)

Thanks!

**Comment by Gaja-A** [comment]
@khouloudbelguith, Yes they are in the same default group. Here is our configuration : 

![Shop_group](https://user-images.githubusercontent.com/51961329/75261319-1f2a0500-57eb-11ea-8c86-d658ff961204.JPG)

Thanks !

**Comment by khouloudbelguith** [comment]
@ShaimyWinda, I tried with this configuration and it is OK
https://drive.google.com/file/d/1U4-qxtOCxKVFi5BZg0AIiAXK03jYVHfQ/view
Could you provide me the log file into `/Project_Folder/var/logs/`.

Thanks!

**Comment by Gaja-A** [comment]
@khouloudbelguith , Here is our log file :
[prod.log](https://github.com/PrestaShop/PrestaShop/files/4254906/prod.log)

Thanks !

**Comment by florine2623** [comment]
Hello @ShaimyWinda ,
You have a critical error : 
``
[2020-02-24 15:44:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "AdminRedirectControllerCore" from the global namespace. Did you forget a "use" statement?" at /var/www/preprod.moondreamwebstore.fr/override/modules/magicredirect/controllers/admin/AdminRedirectController.php line 23 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AdminRedirectControllerCore\" from the global namespace.\nDid you forget a \"use\" statement? at /var/www/preprod.moondreamwebstore.fr/override/modules/magicredirect/controllers/admin/AdminRedirectController.php:23)"} []
``
The problem might come from your module Magicredirect. You can contact the developer of that module to get answer.
Please check and give us feedback.

**Comment by Gaja-A** [comment]
@khouloudbelguith , Ok we will take a look into it but in fact, we bought this module yesterday and tested it in our preprod but the problem of the impact price exists before and also in our prod. 
PS : In prod, we haven't even installed that module yet.

Thanks !

**Comment by florine2623** [comment]
Hello @Gaja-A 
Is it a fresh install or has it been upgraded (from which version) ? 
Thanks !

**Comment by Gaja-A** [comment]
Hi @florine2623 , It is a fresh install (v1.3.9). Thanks !

**Comment by Gaja-A** [comment]
Hi @florine2623 , in fact I'm talking about the module which is a fresh install. But in case of our prestashop, it is upgraded from version 1.7.4 to 1.7.6.

Thanks !

**Comment by florine2623** [comment]
Hello @ShaimyWinda ,
What is the exact version of PrestaShop you were using ? 1.7.4.X ?
And if you used one-click upgrade, what is the exact version you used ?
Thanks!

**Comment by Gaja-A** [comment]
Hi @florine2623 , The exact version of our prestashop we are using is **1.7.6.0** and the version we used before were 1.7.4.2.
Thanks !

**Comment by florine2623** [comment]
Hello @Gaja-A ,

I have not managed to reproduce your issue.
**I migrated from 1.7.4.2 to 1.7.6.3 using 1-click upgrade v4.10.1.**
Here are the results :
I'm changing the first combination :
![Capture d’écran 2020-02-26 à 16 14 29](https://user-images.githubusercontent.com/16019289/75358442-2ddbef00-58b3-11ea-8cd3-751b0ee6c5d1.png)
I put 20€ impact on price :
![Capture d’écran 2020-02-26 à 16 14 35](https://user-images.githubusercontent.com/16019289/75358452-32080c80-58b3-11ea-8237-c90acd1e7f85.png)
On FO, the price of first combination is well impacted : 
![Capture d’écran 2020-02-26 à 16 14 48](https://user-images.githubusercontent.com/16019289/75358456-346a6680-58b3-11ea-836e-5c0eb4cecbdf.png)
On FO, other combination price is not impacted by price : 
![Capture d’écran 2020-02-26 à 16 14 55](https://user-images.githubusercontent.com/16019289/75358465-36ccc080-58b3-11ea-9b28-7ba94b1afac2.png)

Have you had any errors during the upgrade ? If yes, please check you log file and send me that file.
your_admin/autoupgrade/tmp/log.txt

Thanks to check and feedback.

**Comment by Gaja-A** [comment]
Hi @florine2623 , Have you tried it from 1.7.4.2 to **1.7.6.0** ? 
And we have no errors in our_admin/autoupgrade/tmp/log.txt.

Thanks !

**Comment by florine2623** [comment]
Hi @Gaja-A ,

I have tried with PS version 1.7.6.0. Please check the following video : 
Price impact on product with multishop after upgrade : 
https://drive.google.com/file/d/1LYf00aQ1N2YTabiugYOcHIk48NfBEgM8/view

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Please contact the Support Team PrestaShop : https://addons.prestashop.com/en/388-support

Thanks!
