### ISSUE TITLE
HTTP ERROR 500 on clear cache

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#17668]
Hello

Since I update to the last version I'm getting an error when I clear Cache in Prestashop
Fluche cahce
https://drive.google.com/file/d/1hoGU7Jqua8QV7PwdFAWoAPQLEm5kpPrM/view

**Additional information**
Version de PrestaShop : 1.7.6.3
Version de MySQL : 10.3.22-MariaDB
Version du logiciel serveur : Apache
Version de PHP : 7.1.33
Limite de mémoire : 4096M
Temps maximal d'exécution : 7000
Taille max. pour envoi de fichiers : 200M

Regards
[cache.txt](https://github.com/PrestaShop/PrestaShop/files/4202175/cache.txt)

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Did you use opcache?

Thanks!

**Comment by didi-2018** [comment]
@go-sudo @khouloudbelguith  I have that 500 error in all 1.7.x.x versions I used all the years and everytime I clear cache. Refresh the page clears the cache.

**Comment by khouloudbelguith** [comment]
@didi-2018, did you use opcache?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith no I do not use! Since 08.2018 I use Memcache from hosting provider. But it also occures without having any cache enabled

**Comment by khouloudbelguith** [comment]
@didi-2018, it could a permission issue on `/var/cache/prod/`.

**Comment by didi-2018** [comment]
> @didi-2018, it could a permission issue on `/var/cache/prod/`.

@khouloudbelguith do you have an idea how I can solve this?

**Comment by khouloudbelguith** [comment]
@didi-2018, you need to check your host about the permissions.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  My host checked all permissions and everything is okay. I get the following error message: 

2020/02/27 14:34:55 [error] 8209#8209: *23006 FastCGI sent in stderr: "PHP 
message: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in 
/var/www/clients/client3844/web7857/web/prestafolder/classes/db/Db.php:794
Stack trace:
#0 
/var/www/clients/client3844/web7857/web/prestafolder/config/alias.php(47): 
DbCore->escape('configuration', false)
#1 
/var/www/clients/client3844/web7857/web/prestafolder/config/alias.php(52): 
pSQL('configuration')
#2 
/var/www/clients/client3844/web7857/web/prestafolder/classes/Configuration.php(155): 
bqSQL('configuration')
#3 
/var/www/clients/client3844/web7857/web/prestafolder/classes/Configuration.php(209): 
ConfigurationCore::loadConfiguration()
#4 
/var/www/clients/client3844/web7857/web/prestafolder/classes/PrestaShopAutoload.php(171): 
ConfigurationCore::get('PS_DISABLE_OVER...')
#5 
/var/www/clients/client3844/web7857/web/prestafolder/classes/PrestaShopAutoload.php(130): 
PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load('Tools')
#7 /var/www/clients/client3844/web7857/web/prestafolder" while reading 
response header from upstream, client: 162.158.94.169, server: 
mydomain.com, request: "GET 
/adminfolder/index.php/configure/advanced/performance/?_token=a57afpxz4ZHRGNGDIgunXlSNsga1ixUVoxugX0hukDs 
HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7857.sock:", host: 
"mydomain.com", referrer: 
"https://mydomain.com/adminfolder/index.php/configure/advanced/performance/?_token=a57afpxz4ZHRGNGDIgunXlSNsga1ixUVoxugX0hukDs"

My host says: 
It is a php error from prestashop. The Tools class is not found in the source code. Recognize follow stack traces that indicate an error in the code in 99% of the errors.
Presta definitely have to debug again.

(I hope the translation from german is good 🙈)

**Comment by khouloudbelguith** [comment]
@didi-2018, is it similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/11105#issuecomment-585609734?

Thanks!

**Comment by didi-2018** [comment]
> @didi-2018, is it similar to this issue: [#11105 (comment)](https://github.com/PrestaShop/PrestaShop/issues/11105#issuecomment-585609734)?
> 
> Thanks!

@khouloudbelguith should this comment be the fix? 

I never click twice. Why should I? I only click once. But I am using a touchpad not a pc-mouse. If that  info may help.

**Comment by khouloudbelguith** [comment]
@didi-2018, in your case the `var/cache/prod/appParameters.php` file is recreated with 000 permissions? 

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith it is generated with 644 permissions

**Comment by khouloudbelguith** [comment]
@didi-2018, I did not manage to reproduce the issue with PS1.7.6.3.
But, you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12667#issuecomment-544963403 as a solution.

Thanks!

**Comment by didi-2018** [comment]
> @didi-2018, I did not manage to reproduce the issue with PS1.7.6.3.
> But, you can follow this comment: [#12667 (comment)](https://github.com/PrestaShop/PrestaShop/issues/12667#issuecomment-544963403) as a solution.
> 
> Thanks!

this seams to be working. Hope it causes not new errors. Thank you ♥ @khouloudbelguith 😘

**Comment by khouloudbelguith** [comment]
@go-sudo, any news?

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

on a fresh Prestashop installation, I get this error when I'm with FPM Application server by apache on Plesk

`mod_fcgid: stderr: PHP Fatal error: require(): Failed opening required **/var/www/vhosts//httpdocs/var/cache/prod/Container6uvjijv/getPrestashop_AccessDenied_ListenerService.php'** (include_path='/var/www/vhosts//httpdocs/vendor/pear/pear_exception:/var/www/vhosts/httpdocs/vendor/pear/console_getopt:/var/www/vhosts//httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/a/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts//httpdocs/var/cache/prod/Container6uvjijv/appProdProjectContainer.php on line 1633, referer: https:///admin4444/index.php?controller=AdminSuperSpeedStatistics&token=9ef17b4727093652309176a57391f360`

 So I switch to FastCGI and now I can clear the cache with success
![image](https://user-images.githubusercontent.com/11594433/77700859-5c81de00-6fb5-11ea-8f13-be90daea9aed.png)

here is the apache log with FastCGI

GET /adminxxxxddxx/index.php/configure/advanced/performance/clear-cache?_token=OsifWwt7VJ4QbFhfk8jLfP8BjvEelj4ibAlyGjUjF04 HTTP/1.0

Solved

Regards

**Comment by metacreo** [comment]
Switch to mod_php :) using FastCGI is NOT solution

**Comment by jmrftrs** [comment]
LOL! What's NOT a solution is to have to go away from FPM because it's not working FOR YEARS with Prestashop.

**Comment by metacreo** [comment]
the engine turns into a real trash heap, they do not support the Apache server because they pushing their hosting. I often encountered this error before, but on the last branch of php 7.3.27 and later I did not encounter an error. 

Maybe we can compare our php and apache configs to find issue?
