### ISSUE TITLE
Specs for calculation of discounts  - Discount of a cart rule with percentage reduction restricted to selection of products

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#17666]
When a cart rule is created with percentage reduction on a selection of products, the discounts subtotal is calculated on final price and not on unit price of that selection of products.

**To Reproduce**

1. Go to BO => Catalog => Discounts => Create a new cart rule
   1.1 Give a name to the cart rule.
   1.2 As conditions => Restrictions => product selection => Choose 2 products (`demo_1` Hummingbird printed t-shirt and `demo_3` Hummingbird printed sweater).
   1.3 As an action => Apply a discount Percent = 100% => Apply a discount to: "Selection of products".
2. Go to FO, add whatever products in cart, but including `demo_1` and/or `demo_3`.
3. Increase the quantity of `demo_1` and `demo_3` to 10 for example.
4. See behaviour in screenshot.

**Screenshots**
![selection of products - percentage reduction cart rule - discounts calculation](https://user-images.githubusercontent.com/23559010/74471876-41de2480-4ea1-11ea-87ac-a5e87c26767f.png)

**Additional information**
PrestaShop version: 1.7.7.x, 1.7.6.3
PHP version:  7.2

**Comment by khouloudbelguith** [comment]
Hi @arouiadib,

Thanks for your report.
I have the same behavior as PS1.7.5.2 & PS1.7.6.3.
But, I think, it is normal behavior.
Ping @PrestaShop/prestashop-product-team @MatShir what do you think?
We apply 100% for a product selection & there is no quantity specified in this case
![image](https://user-images.githubusercontent.com/16067358/74524589-9de78e00-4f1f-11ea-9aa2-6ba796865ab9.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/17665

**Comment by colinegin** [comment]
I'm not sure I understood the same as you @khouloudbelguith.
If I understand correctly @arouiadib 's screenshot, the problem in my opinion is that the discount is supposed to be equal to $478.40 but it actually displays -$507.40 in the bottom.
Am I correct @arouiadib ?

**Comment by arouiadib** [comment]
Closed as (Duplicate) of #17665

**Comment by hibatallahAouadni** [comment]
Duplicate of #17665
