### ISSUE TITLE
site "new-products" show randow products as "new" - PS 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17662]
Hello, 

PS site "new-products" do not show all the new products, it show random products and mark them as "new". 

My PS setting for new products is 60 days. In my PS 1.7.5.1 the site new-products only show new products from last 60 days. But in PS 1.7.6.3 the site show random products. In my case 316 products. It starts with 2 products add on 31.08.2018 than 2 from 30.08.2019 than from 27.08.2018 and so on and so on. 

It seems there is a wrong behavior!?? It seems that the site only sort by day and month and ingnore the year.

Can you please check it? That would be very nice 😊

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

Thanks for your report.
Could you please try to install the `ps_newproducts` module, configure it with `Number of days for which the product is considered 'new'` and check if the same issue occurs if you click on "All new products" link
![image](https://user-images.githubusercontent.com/16067358/74519410-ea2dd080-4f15-11ea-9dca-64cd09798597.png)

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith it is installed and configured

**Comment by didi-2018** [comment]
@khouloudbelguith I reseted module but I have the same issue. There is not datatable for it, right? Could it be cause 1.7.6.3 is new installed? But I do not understand why all products from 2018 and 2019 are shown there? Sort in Category works. But not in module and not on site new-products

**Comment by khouloudbelguith** [comment]
@didi-2018, in your BO => Advanced Parameters => Database => create an SQL command 
```Select COUNT(*) from  ps_product where `date_add` > '2019-12-14 00:00:00'``` and check the result.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith 

![image](https://user-images.githubusercontent.com/44971218/74535925-3f2e0e80-4f37-11ea-9412-b80815c8b0c4.png)

**Comment by khouloudbelguith** [comment]
@didi-2018, in the Fo, you should have 45 products displayed.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith I have in normal Category 37 new products today. 

https://dev.madamedessous.com/Alle-Produkte

and on site new-products I have today 317 products marked as new and random.

https://dev.madamedessous.com/neue-artikel

**Comment by khouloudbelguith** [comment]
@didi-2018, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  only that error today: 

/img/app_icon.png" failed (2: No such file or directory)

I do not know for what it is

**Comment by khouloudbelguith** [comment]
@didi-2018, what about your log file `/Project_folder/var/logs/`?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  only prod.log from 12.02.20 with a lot of clear cache errros and dev.log from 09.02.20 with a lot of translation not found.

**Comment by khouloudbelguith** [comment]
@didi-2018, this a fresh install PS1.7.6.3 or an upgrade from a previous version?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith fresh install from 07.02.20
it works fine in my 1.7.5.1 

https://madamedessous.com/Alle-Produkte
https://madamedessous.com/neue-artikel

**Comment by khouloudbelguith** [comment]
@didi-2018, if it is a fresh install from 07.02.20 => so all products are considered as new products.
How can you have products created 30.08.2019 & your shop creation is 07.02.20?
Did you import your product from the import page?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith yes all imported from database from 1.7.5.1 cause I could not upgrade without having a lot of errors.

**Comment by didi-2018** [comment]
@khouloudbelguith database exported as OpenDocumentSpredsheet from 1.7.5.1 and imported as the same in database from 1.7.6.3

**Comment by khouloudbelguith** [comment]
@didi-2018, I think, there is a problem during the upgrade of your database manually.
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.3 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith I did not upgrade the database. I installed a fresh 1.7.6.3 and imported products and all that belong to the products (attributes, features ect.) as OpenDocumentSpredsheet from 1.7.5.1 database. I changed nothing in new database, only filled in product datas.

**Comment by didi-2018** [comment]
@khouloudbelguith  I can see that the date in ps_products_shop is NOT right. There is an issue with the year! I will import the table new and I come back to you.

**Comment by khouloudbelguith** [comment]
@didi-2018,

Thanks!
Waiting for your feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith  Yes, it was my fault! With the import the year and the day had the false position. The day was the year and the year was the day. 🙈

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks for the feedback.
I will close the issue, feel free to open another one if needed. 

Thanks!
