### ISSUE TITLE
Impossible login to Backoffice prestashop 1.7.6.2 maybe cookies

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#17675]
**Describe the bug**
Nothing appens when try to login in backoffice with firefox or chrome 80
i can only login with opera

**To Reproduce**
Tty to login
**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.27
[Uploading Registrazione schermo 2020-02-14 alle 14.25.17.mov.zip…]

Got this error in chrome console: 
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

removing cookies solve the problem only for few time.

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

Does the Project folder name contain a symbol `+`?

Thanks!

**Comment by Betafer** [comment]
No

**Comment by khouloudbelguith** [comment]
@Betafer,

Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
`if ($this->context->cookie->last_activity + 900 < time()) {`

By this:

`if ($this->context->cookie->last_activity + 3600 < time()) {`

Thanks to check & feedback.

**Comment by Betafer** [comment]
Thanks, how to disable  IP check in classes/Cookie.php ?

**Comment by khouloudbelguith** [comment]
@Betafer, You can comment this condition: `&& (!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP'))`
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cookie.php#L240

Thanks!

**Comment by Betafer** [comment]
Thanks

**Comment by khouloudbelguith** [comment]
@Betafer, issue solved?

Thanks!

**Comment by Betafer** [comment]
We are doing another job, as soon as it finished i will test.

**Comment by khouloudbelguith** [comment]
@Betafer,
Thanks!
Waiting for your feedback.

**Comment by Betafer** [comment]
I don't have this rows in ps_configuration table
2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

**Comment by Betafer** [comment]
ops sorry: the search of phpmyadmin 
i got:
www.betafer.it | 0000-00-00 00:00:00 | 2020-01-16 21:43:04
-- | -- | --
  | Modifica | Copia | Elimina | 232 | NULL | NULL | PS_SHOP_DOMAIN_SSL | www.betafer.it

**Comment by Betafer** [comment]
<img width="1465" alt="Schermata 2020-02-16 alle 21 35 04" src="https://user-images.githubusercontent.com/5024055/74612288-51a97300-5104-11ea-971b-e67715a294e9.png">

Hello, i have no cookie ip check in backoffice

**Comment by khouloudbelguith** [comment]
@Betafer, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by Betafer** [comment]
now seems to work correct, apparently the problem has solved itself (I haven't removed the cache)

Thanks

**Comment by khouloudbelguith** [comment]
@Betafer, thanks for your feedback.
Since it is fixed, I will close the issue, feel free to open a new one when needed.


Thanks!
