### ISSUE TITLE
Errors: [ERROR 1824] Element '{urn:oasis:names:tc:xliff:document:1.2}file

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#17670]
Invalid resource provided: "1.2"; Errors: [ERROR 1824] Element '{urn:oasis:names:tc:xliff:document:1.2}file

When I try to export my theme, I got this error

**Invalid resource provided: "1.2"; Errors: [ERROR 1824] Element '{urn:oasis:names:tc:xliff:document:1.2}file**

**To Reproduce**
1. add a custom theme
2. go to translation and translate for a non latin language
3. go back to theme and try to export the theme

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 5+

**Comment by khouloudbelguith** [comment]
Hi @vincent-dp,

Have you tried to contact the theme author about the issue?
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by vincent-dp** [comment]
I am the theme author.
But you can use classic rocket, you will get the same problem.
it comes from the api prestashop use to generate translation files

**Comment by khouloudbelguith** [comment]
@vincent-dp, I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2 & the Classic rocket theme.
[classic-rocket.zip](https://github.com/PrestaShop/PrestaShop/files/4204206/classic-rocket.zip)
I used the Greek language.
I attached a screen record
https://drive.google.com/file/d/1qVV45p4Fg52WUN9QuSN-Xnnk3itokOlV/view
Thanks to check & feedback.

**Comment by vincent-dp** [comment]
Ok, it seems to be on my side. I don't know how to solve it tho :(

**Comment by khouloudbelguith** [comment]
@vincent-dp, what is the exact language did you used to translate your theme?
Is it your default language?
Is it the language of your employee?

Thanks!

**Comment by vincent-dp** [comment]
Hebrew,
it is the default language of one of my test shop and the language of the person that makes translation and have access to my back office

**Comment by khouloudbelguith** [comment]
@vincent-dp, using your language is ok also.
https://drive.google.com/file/d/1VyPQ_r-fyzo5j8lNdm8RjuuIBvSrf9gF/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by vincent-dp** [comment]
I will find where the problem comes from, I thought it was a well none issue.

**Comment by khouloudbelguith** [comment]
@vincent-dp, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by vincent-dp** [comment]
Thanks :)

**Comment by LucasVollebergh** [comment]
> I will find where the problem comes from, I thought it was a well none issue.

What was the problem? I have this issue as well (on another theme)
Thanks!

**Comment by vincent-dp** [comment]
delete the content of the `translations` folder in your theme forlder

**Comment by LucasVollebergh** [comment]
Hi, this did not work for me.  I still have the error. 
thanks anyway

**Comment by vincent-dp** [comment]
Basicaly, this error means something wrong with the build. So, check your theme for errors, most of the time it's in the `theme.yml` file in `config` forlder

**Comment by vincent-dp** [comment]
use the theme validator here:
https://validator.prestashop.com/auth/login

**Comment by LucasVollebergh** [comment]
I found the problem.

Had to use NL and NL on the ISO language settings instead of BE. (even when it should have been BE, PS messed up the ISO format I think)

**Comment by vincent-dp** [comment]
mmh, I'd say it's fishy, you must have fixed your solution before you tried that. Have you tried to reproduce just to be sure?
