### ISSUE TITLE
Access Denied Prestashop 1.7.6.2 in some section of backoffice

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#17682]
**Describe the bug**
Got error access denied in shop preference, advanced etc

**To Reproduce**
Go in admin tabs 
**Screenshots**
Here there is workaround but seems not a good one:
https://www.prestashop.com/forums/topic/876786-solved-prestashop-17-access-denied-as-admin-in-bo/

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by kcalliauw** [comment]
I noticed that this might be some kind of rewrite issue. 
On my local environment the admin generates URL's like this:

`http://localhost/admin3k4l2mtr/index.php/configure/advanced/emails/?_token=...`
removing the /index.php part, with a resulting URL like this:
`http://localhost/admin3k4l2mtr/configure/advanced/emails/?_token=...`
... send me to the correct page.

rewrite and friendly URL's seem to be working elsewhere properly (like on the front)

**Comment by Betafer** [comment]
Found the issue was a configuration of php, but now i don't know which, I have to ask to the developer

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

To fix this issue you need to replace the 'ps_access' table in DB with the one from clean PS1.7 installation.
You can, for example, install PrestaShop separately, copy & paste the table ps_access to your shop.
Or you can follow this solution in this comment to solve your issue #9513 (comment)
Before any modification, you can make a backup of your old database.
Thanks to check & feedback

**Comment by kcalliauw** [comment]
@khouloudbelguith I'm having this issue on a clean install of 1.7.6.3. Does that mean that my issue is different somehow?

**Comment by khouloudbelguith** [comment]
@Betafer, the PrestaShop download is from [our official link](https://www.prestashop.com/en/previous-versions)?
What is the exact `Language/Country` did you use during the install?

Thanks!

**Comment by Betafer** [comment]
Yes, Italy - Italian

**Comment by khouloudbelguith** [comment]
@Betafer, It is Ok in my case, https://drive.google.com/file/d/1unV6DTSqbwkpWXSHJfuNyDY8kJQe7adC/view
I used PHP5.6.40.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Betafer** [comment]
Hello, you can close for now, it seems to work now, i will reopen if it will give the problem again

thanks !

**Comment by khouloudbelguith** [comment]
@Betafer, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!
