### ISSUE TITLE
Prestashop webservice not working in DIrectAdmin default settings

### ISSUE THREAD

**Issue by adi5497** [PrestaShop/PrestaShop#17685]
Hello, I'm trying to fix problem with webservice on VPS. I dont know where is the problem but:

VPS -> VestaCP -> Apache+Nginx+FastCGI = Webservice working
VPS -> DirectAdmin -> Apache+Nginx+FastCGI = Webservice not working

On DirectAdmin server I'm getting
`IP - - [15/Feb/2020:19:41:12 +0000] "GET /api/ HTTP/1.0" 401 2452 "-" "-"`
All day I'm tring to fix it but without result. Maybe DirectAdmin default setting (or nginx?) are not correct for PS?

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @adi5497,

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
