### ISSUE TITLE
Missing Payment methods

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#17681]
I have run into a problem this morning with the basket, all 3 payment methods have vanished from the basket area, all are still installed into the store and seem to be all ok, but on the checkout page they have vanished so I'm unable to take any payments on the site

I have cleared all the cache from within the store as well as from the c/panel folders and there's no difference, I have tried to reinstall the modules and checked for updates still not showing up in the checkout area, for now, I have put the site into Maintenance mode so nobody gets upset trying to make purchases, the only way for you to reproduce it is to make a purchase on the site and see for yourself but not while its in maintenance mode.

I have not made any changes or installed anything new in a while and it was all working fine 2 days ago so what's gone wrong I haven't changed anything in weeks it's just stopped working? below is a screenshot from a test product I put through to show there's NO payment options able to be selected.

![missing payment methods](https://user-images.githubusercontent.com/52738920/74585809-5d504900-4fe1-11ea-9ebd-d68377ec03bd.jpg)

**Screenshots**

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.4

**Comment by didi-2018** [comment]
@Allthejam  Prestashop 1.7.5.2 is NOT working with PHP 7.3 and PHP 7.4. Your changes belong to changes in PHP version! Please change it down to max. PHP 7.2. and check.

**Comment by Allthejam** [comment]
I have done that this morning and it's still not working, however it was all working perfectly for a couple of months until this morning. I'm lost I can get any payment method to show on the checkout.

**Comment by didi-2018** [comment]
@Allthejam you changed back to PHP 7.2 ?

Have you checked the hooks of modules? Design -> Positions 
possible hooks are: displaypayment and displaypaymentEU

**Comment by Allthejam** [comment]
I've had a look and all are still hooked apart from Payment cloud, I have removed it because I do not use it.

![2020-02-15_131824](https://user-images.githubusercontent.com/52738920/74587655-e6717b00-4ff5-11ea-872d-e76b853de9c3.jpg)

**Comment by Allthejam** [comment]
I have also just noticed that when I try and add an item to cart it opens the new window but does not add any items into the cart, to add an item I have to open the specific item and ad from the items own page, this is a new problem...

See below: 

![2020-02-15_132517](https://user-images.githubusercontent.com/52738920/74587761-de660b00-4ff6-11ea-881e-4ce3ae3214d3.jpg)

**Comment by didi-2018** [comment]
@Allthejam  please try to remove that module hooked in displayPaymentEU. In my case it helped me! This hook is not needed 😉

**Comment by Allthejam** [comment]
Done.....

No change still have now payment options showing on the checkout page, any other ideas, I'm pulling my hair out here.
Thank you.

**Comment by didi-2018** [comment]
@Allthejam what does your error log and Server log files say? Have you checked them?

**Comment by didi-2018** [comment]
@Allthejam debug mode any errors shown? Have you cleared cache in Folder /var/cache/prod ?

**Comment by Allthejam** [comment]
I'm constantly getting this: 
**Swift Error: Expected response code 250 but got code \"\", with message \"\"**
This I think was from the auto email service that is now working after I updated the info

I have been getting this ever since the payment modules stopped working at 1424hrs yesterday
**Exception on hook paymentOptions for module . Unable to create order code (Person c1593420-60e4-46f0-8236-0a138d005e4d does not support currency \'978\')**

Yes I cleared all cache from within Presta and from the host files /var/cache/prod this morning hoping that would fix the issue.

![cart error](https://user-images.githubusercontent.com/52738920/74589672-7d92fe80-5007-11ea-81ea-6f6b7d8e02d7.jpg)

**Comment by Allthejam** [comment]
I have tried multiple currencies to make payment and it makes no difference, I have even deleted a lot of optional currencies that we had that all worked for us in the past just to keep Dollars, Pounds and Euros but this also has made no difference.

**Comment by Allthejam** [comment]
I put it into Debug Mode see screenshot, the thing is I have no idea what it all means or even where to start with it.
![debug mode](https://user-images.githubusercontent.com/52738920/74590211-bf727380-500c-11ea-9e46-861c0ed79e0d.jpg)

**Comment by didi-2018** [comment]
@Allthejam all I can do for you is try to use a Backup from your Hosting provider from that point of time when your Shop worked. Or you have to wait till monday till one of the presta poeple can answer you. But I do not think that they could really help you. I would use a Backup from one of the days before when All was working. Backup from files and Database.

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

Thanks for your report.
As @didi-2018 said, PrestaShop is not compatible with PHP 7.3 and PHP 7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

>I've had a look and all are still hooked apart from Payment cloud, I have removed it because I do not use it.

Could you please try to disable non-native module one by one, clear cache, check & feedback.

>I have also just noticed that when I try and add an item to cart it opens the new window but does not add any items into the cart, to add an item I have to open the specific item and ad from the items own page, this is a new problem...

About this issue, it is a cookies issue.
1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
if ($this->context->cookie->last_activity + 900 < time()) {

By this:

if ($this->context->cookie->last_activity + 3600 < time()) {

Thanks to check & feedback.

**Comment by Hlavtox** [comment]
@didi-2018 Prestashop 1.7.6 is working just fine with PHP 7.3, just some minor warnings in console, but everything is OK.

**Comment by khouloudbelguith** [comment]
@Hlavtox, I'm happy to hear that there is no issue with php7.3 on your staging server but as I said, currently PrestaShop is not compatible with php7.3. So some parts of the application might work, but there is no guarantee it works globally. Explications about why can be read here: http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

Thanks!

**Comment by Allthejam** [comment]
Thank you all for your help so far, I have tried various versions of PHP now and currently on 7.2.
I have also cleared all the cookies, deleted manually from in the system folders and mad the changes to the coding on line 2757 which wasn't easy to find, I have refreshed everything and ran some test orders and still, I have no payment options showing.

I should have VivaWallet and Coingate, they all worked before but have since disappeared from this page, I have reset them, uninstalled and reinstalled them and updated the API's and still nothing.

Any more ideas?  Thank you all for your help...

![2020-02-19_114227](https://user-images.githubusercontent.com/52738920/74827071-06ae7c00-530d-11ea-9510-8dc07c9f5009.jpg)

**Comment by khouloudbelguith** [comment]
@Allthejam, thanks to navigate to your BO => Design => Positions => 
Search for the hook `displayPaymentReturn` and `paymentOptions` hook and provide me screenshots.

`Display non-positionable hooks` should be selected.
![image](https://user-images.githubusercontent.com/16067358/74828761-f64bd080-530f-11ea-9fe2-e040a9b5def5.png)
![image](https://user-images.githubusercontent.com/16067358/74828781-01066580-5310-11ea-9083-441cca41f994.png)

Thanks!

**Comment by Allthejam** [comment]
Thank you, I've checked that and it was all showing already. I tried this a few days ago when I uninstalled them, unhooked and reinstalled all from scratch again, still made no difference, See bellow. 
![test](https://user-images.githubusercontent.com/52738920/74830581-c272aa00-5313-11ea-8cea-9239eeec01fc.jpg)

**Comment by Allthejam** [comment]
I have even today installed and signed up for the PrestaShop Checkout account to test it out but even its not showing on the checkout page, I don't know anymore...

**Comment by Allthejam** [comment]
![2020-02-19_125346](https://user-images.githubusercontent.com/52738920/74832152-ee435f00-5316-11ea-9eca-904f33524263.jpg)

**Comment by khouloudbelguith** [comment]
@Allthejam, in your BO => Payment => Preferences page => did you check all the restrictions?
1. Currency restrictions
2. Group restrictions
3. Country restrictions
4. Carrier restrictions

Thanks!

**Comment by Allthejam** [comment]
Geolocation by IP address set to NO
All Language packs are enabled
All Currencies are enabled

All  Groups are set as standard and no restrictions, I have tried testing orders from both guest and a logged-in account as well as a subscriber


This carrier will be proposed for those delivery zones:
•	Africa
•	Asia
•	Central America/Antilla
•	Europe
•	Europe (non-EU)
•	North America
•	Oceania
•	South America
And it will be proposed for those client groups:
•	Visitor
•	Guest
•	Customer
 
Thank you.

**Comment by khouloudbelguith** [comment]
@Allthejam, could you please disable all the payment module except the module `bank transfer` provided by PrestaShop.

Thanks to check & feedback.

**Comment by Allthejam** [comment]
Ok, that did something. I did that and enabled the back transfer option the result is that I now have pay by bank transfer on the checkout page, as soon as I enabled any other payment option everything goes again. What's next to get other options back working?

**Comment by khouloudbelguith** [comment]
@Allthejam,

>I enabled any other payment option

What are those exact payment methods?

Thanks!

**Comment by Allthejam** [comment]
Vivawallet is the prefered option
Coingate
Prestashop checkout

As soon as I enable anything else nothing appears on checkout I even lose bank transfer

**Comment by khouloudbelguith** [comment]
@Allthejam, those modules are not provided by the PrestaShop team core.
As they are not provided by Prestashop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Allthejam** [comment]
I think the problem might be with Vivawallet, 

Ok, Thank you for all your help, its something to work from

Thank you

**Comment by duvalsoft** [comment]
That seem like be related with this issue:
https://github.com/PrestaShop/PrestaShop/issues/11379

Basicaly , do you have more that one carrir with the same name?

**Comment by PascalB67** [comment]
Hello, same problem with a new migration .... cb module not display. 
Excellent ... 1.7.8.1 !
