### ISSUE TITLE
make prestashop 1.7 can choose no default compilation  

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17683]
hello 
i have problem with presta i cannot make product have many combination with no default option and without choosing option make all image for all attribute showing 

and there is something ...    
i there is bug that i can add 10 product in cart and there is 2 product in stock and disable out stock option

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Thanks for your report.
>i have problem with presta i cannot make product have many combination with no default option

You need to create a standard product with combinations and there is no "Default combination" selected?
![image](https://user-images.githubusercontent.com/16067358/74635355-1e97cb80-5166-11ea-9522-7ab86a20eaa6.png)

>without choosing option make all image for all attribute showing

You need to display all thumbnails for all combinations, only the main image is changed when selecting a combination?

>i there is bug that i can add 10 product in cart and there is 2 product in stock and disable out stock option

The "Allow ordering of out-of-stock products" option is disabled in your case?
![image](https://user-images.githubusercontent.com/16067358/74635513-746c7380-5166-11ea-9253-0b4fd1ecfaf0.png)
But, you can add products that are out of stock?

Thanks!

**Comment by khalidzuhd** [comment]
I ment you shouldn't allow buyers to add in countity number more than it have ...
And it didn't allow to add out of stock 
![Screenshot_2020-02-18-16-33-06-531_com bella bella](https://user-images.githubusercontent.com/1392266/74745470-9f40ef80-526c-11ea-9631-77342e83173d.jpg)
If i have 3 product  in stock ... The client should not add in countity number more than its in the stock
Make product counter limited ...
Sory my en is weak

**Comment by khouloudbelguith** [comment]
@khalidzuhd,

>If i have 3 product in stock ... The client should not add in countity number more than its in the stock

In fact, The customer can't add a product out of stock.
The "Add to cart" button is disabled.
I attached a screen record
https://drive.google.com/file/d/10NEIz8UTxq_wWU8THBI6RAO4ZyISScup/view

But we have this issue: https://github.com/PrestaShop/PrestaShop/issues/13374, it could be related and it is fixed in the next major PrestaShop version 1.7.7.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15623

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
