### ISSUE TITLE
When you try to change the shipping address of an order it changes the invoice address instead

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17695]
**Describe the bug**
When you try to change the shipping address of an order it changes the invoice address instead

**To Reproduce**
1. Go to Orders > Orders > View an order
2. Click on change for the shipping address
3. Select another address than the current one
4. See the invoice address is changed instead of shipping address

**Screenshots**
https://drive.google.com/file/d/11XRbNaOTmbqodv-Mz4UTKtkhFkRE-Yy9/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed in #17700
