### ISSUE TITLE
Customer page issue

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#17691]
Hi @khouloudbelguith ,

I have an issue with the customer page on the Back office. In fact, I can't see my customers in this page. However, I see their addresses in Addresses page.
In Front Office, I success to connect without issue.

I checked logs and I don't see the problem. I have disabled no prestashop modules and I also deleted the cache without success ...

Can you help me?

Thank you.

Prestashop 1.7.6
PHP 5.6.40

![Screenshot](https://user-images.githubusercontent.com/47451841/74640350-adf5ac80-516f-11ea-9342-e9bcb07c02e7.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Amulliez,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source): is it fresh install or an upgrade from a previous version?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Amulliez** [comment]
Hi @khouloudbelguith,

I'm sorry for the inconvenience, I just found the origin of the problem.

Thank you.

Have a nice day.

**Comment by khouloudbelguith** [comment]
@Amulliez, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
