### ISSUE TITLE
Prestashop loads old carts for logged in users

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#17716]
**Describe the bug**
When the option "Re-display cart at login" is turned on, and customer has some old abandoned cart, it will get loaded even if the customer also has some never ordered carts.

The cart should be loaded only if it's the last one from the customer's carts.

>Edit by Khouloud

**Steps to reproduce**
1. In the BO => Shop Parameters => Customer Settings => Disable "Re-display cart at login"
2. Go to the FO => login with your customer
3. Add some products to the cart
4. Sign out ( a new line is added to the BO => Shopping carts page)
5. Go to the FO => login with your customer
6. Add some products to the cart
7. Complete checkout
8. In the BO => Shop Parameters => Customer Settings => Enable "Re-display cart at login" again
9. Go to the FO => login with your customer
10. You will have old products in the cart.

**Comment by khouloudbelguith** [comment]
Hi @daresh,

Thanks for your report.
Is it the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/15521
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15533 to fix the issue.

Thanks to check & feedback.

**Comment by daresh** [comment]
Hi @khouloudbelguith 

I think it's not the same. It's not about guests but about old abandoned carts.

For example, if the customer (a logged in one) has:
Cart with an order from today
Cart with an order from yesterday
Abandoned cart from last year

And he logs in, he'll have that old cart from last year loaded only because it is an abandoned cart.

**Comment by khouloudbelguith** [comment]
@daresh, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.3 and PS1.7.5.2.
1.7.6.3: https://drive.google.com/file/d/186EUvgVbyTD-Yieyo9Z1vB2I-0VhRM6z/view
1.7.5.2: https://drive.google.com/file/d/1jADJJcVfpqVkVchDpa-N0PdCoUR2rDmh/view

1. In the BO => Shop Parameters => Customer Settings => Disable "Re-display cart at login"
2. Go to the FO => login with your customer
3. Add some products to the cart
4. Sign out ( a new line is added to the BO => Shopping carts page)
5. Go to the FO => login with your customer
6. Add some products to the cart
7. Complete checkout
8. In the BO => Shop Parameters => Customer Settings => Enable "Re-display cart at login" again
9. Go to the FO => login with your customer
10. You will have old products in the cart.

I’ll add this to the debug roadmap.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17712
