### ISSUE TITLE
Improvement - Show an error message about the syntax of {-:id_product_attribute}

### ISSUE THREAD

**Issue by MauroKali** [PrestaShop/PrestaShop#17713]
>Edited by Khouloud

## Solution

{category:/}{id}-{id_product_attribute}-{rewrite}.html
Even if there is no id_product_attribute

category = men
id = 95
id_product_attribute = None
**Product route = {category:/}{id}-{id_product_attribute}-{rewrite}.html**
Result
**men/95--tshirt.html** ==> should work

--------------------------
Hi,

As suggested here: https://github.com/PrestaShop/PrestaShop/issues/17713#issuecomment-588093146
**Is your feature request related to a problem? Please describe.**
In the BO => Shop Parameters => SEO & URLs page, when we change the route of the `Route to products` to incorrect form, we should have an error
For example change this `{category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html` to `{category:/}{id}{id_product_attribute}-{rewrite}{-:ean13}.html`

=> It is not ok in the FO => So we should have an error message when saving this.

>It would be possible to show an error message about the syntax of {-:id_product_attribute} ?

if we put {id_product_attribute} instead of {-:id_product_attribute} there is no message but it's a source of bug

thanks!

-----------------------------------
Hello to all of you, 

I just migrated a website from prestashop 1.6 to 1.7.6.3. 
And I have an issue regarding product URLs (only products)

II miss the id_product_attribute. The table on database is empty - so I miss an element on the URL and I have a 404 error. 

The structure of the URL should be: 

{category:/}{id}-{id_product_attribute}-{rewrite}.html

and I have (for exemple)
**men/95--tshirt.html** ==> 404 error 

If I put manually a 0 for exemple it's ok. 
**men/95-0-tshirt.html** ==> OK 

How can I fix it ? 

thanks for your precious help

**Comment by khouloudbelguith** [comment]
Hi @MauroKali,

In the Back Office => Shop Parameters => Traffic & SEO page, what is the exact "Route to products"?
![image](https://user-images.githubusercontent.com/16067358/74746780-38203c80-5266-11ea-8b99-b09ac38282df.png)

Thanks!

**Comment by MauroKali** [comment]
the same you showed me but it does not work - 404 errors. and empty space for id_product_attribut

**Comment by khouloudbelguith** [comment]
@MauroKali, did you use a custom module to rewrite of URLs?

Thanks:

**Comment by MauroKali** [comment]
@khouloudbelguith nope, any module for rewriting the URLs. 
thanks

**Comment by khouloudbelguith** [comment]
@MauroKali, 

Could you please try to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

**Comment by MauroKali** [comment]
hello @khouloudbelguith 
thanks for your answer but I've already done it at least 1000 times :)

**Comment by MauroKali** [comment]
actually I found a solution but it's quite dirty. 
I modified the dispatcher.php as mentionned on https://github.com/PrestaShop/PrestaShop/issues/11773

**Comment by khouloudbelguith** [comment]
@MauroKali, as I understand, you changed this 
`{category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html`
by this
`{category:/}{id}{-: }-{rewrite}{-:ean13}.html`?

This incorrect, it is not possible.
About the bad URL when the product has combinations, we have this issue #9784, it is added to our bug roadmap.
Thanks!

**Comment by MauroKali** [comment]
@khouloudbelguith 
My products do not have combinations - I changed the rule in this way: 

{category:/}{id}-{rewrite}.html

**Comment by khouloudbelguith** [comment]
@MauroKali, no, it is not possible to remove the `{-:id_product_attribute}` from URL.

Thanks!

**Comment by MauroKali** [comment]
@khouloudbelguith 
I understand - but it seems there is no another solution at the moment

**Comment by khouloudbelguith** [comment]
@MauroKali, yes!
As I said, the bad URL when the product has combinations, we have this issue #9784, it is added to our bug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
@MauroKali, so, can we close the issue?

Thanks!

**Comment by MauroKali** [comment]
Hello @khouloudbelguith 

yes but I have a suggestion as well :) 

It would be possible to show an error message about the syntax of {-:id_product_attribute} ? 

if we put {id_product_attribute} instead of {-:id_product_attribute} there is no message but it's a source of bug 

thanks

Mauro

**Comment by khouloudbelguith** [comment]
Hi @MauroKali,

I updated the issue.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @MauroKali, @khouloudbelguith, good news: we already have a wording for that! See below:

_The route %routeRule% is not valid_ in _Admin.Shopparameters.Feature_

**Comment by colinegin** [comment]
Hello @MauroKali ,

Are you able to make a PR to add this error message ?

Thanks !
