### ISSUE TITLE
I should be able to see orders placed in other shops of the same group, if the group shares orders

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17727]
**Describe the bug**
I should be able to see orders placed in other group stores, if the group shares orders

**To Reproduce**
1. Go to Shop parameters > General and enable multistore
2. Go to Advanced parameters > Multistore
3. Click on Add new shop group "all shared group"
4. Share customers, share available quantities to sell, share orders
5. Create a new store "shop3" in "all shared group"
6. Create a new store "shop4" in "all shared group"
7. Make an order in FO in shop3
8. Go to orders > orders migrated listing
9. Select shop4
10. You should see the order make in shop3 because orders are shared in this group

**Screenshots**
![capture d'écran_2364](https://user-images.githubusercontent.com/13449658/74816827-2e491880-52fc-11ea-9b10-45e21b8c9364.png)

![capture d'écran_2365](https://user-images.githubusercontent.com/13449658/74816834-32753600-52fc-11ea-91d4-a2df69672d72.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17767 17767
