### ISSUE TITLE
Private note in order page migrated cannot be emptied

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17726]
**Describe the bug**
In migrated order view page, the private note of a customer cannot be emptied, since the "Save" button is deactivated when the field is empty.

**To Reproduce**
1. Go to order view page (migrated)
2. Click on "Private note". If the private note is empty, write something in it, save, and refresh
3. Empty the "private note" field
4. The "Save" button becomes grey, and cannot be clicked, it is not possible to empty the field.

**Screenshots**
https://drive.google.com/file/d/1a6Af_Ra9RTgeZeJG6YgvdKiMABTaGkXy/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17799
