### ISSUE TITLE
Exception when accessing a non existing order via URL

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17732]
**Describe the bug**
When a user try to access a non existing order (with a bad id) via URL in migrated page, there is an exception. On Legacy, there is a redirection on the order list.

**To Reproduce**
1. Go to a non existing order via URL, for example : /admin-dev/index.php/sell/orders/orders/647/view
2. An exception is displayed

**Screenshots**
![non existing order](https://user-images.githubusercontent.com/55688534/74821152-761f6e00-5303-11ea-9eb3-f54683ebba4e.png)

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I tried with 1.7.7.x branch.
I have a redirection to the Dashboard page without exception
https://drive.google.com/file/d/183yhV_2wN2DufUluhKuWpUkJoFoGVMdc/view

Thanks!

**Comment by Robin-Fischer-PS** [comment]
My bad @khouloudbelguith , the good URL is /admin-dev/index.php/sell/orders/orders/647/view ! I'me editing the issue.

**Comment by Progi1984** [comment]
Fixed by #17839
