### ISSUE TITLE
Wrong use of microdata sku - it is necessary to add also the mpn tag

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17739]
Hi
it is wrong to associate the micro tag SKU to the product reference it should be the MPN tag, instead for the SKU you should use the product ID, because normally it is used as product identificator

in the product-details.tpl at line 24
it is necessary to remplace this line
`<span itemprop="sku">{$product.reference_to_display}</span>`
with
`<span itemprop="mpn">{$product.reference_to_display}</span>`

and add this code in product-details.tpl
`<meta itemprop="sku" content="{$product.id}{if isset($product.id_product_attribute) && $product.id_product_attribute}-{$product.id_product_attribute}{/if}" />`

and if you want to add the micro tag of brand it is necessary to add this code

`    {if isset($product_manufacturer->id) && $product_manufacturer->name}
        <meta itemprop="brand" content="{$product_manufacturer->name}" />
    {/if}`

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/74831354-63159980-5315-11ea-956d-7b3bfc2c3cf1.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by Maofree** [comment]
after fix

![1](https://user-images.githubusercontent.com/653230/74867802-96781880-5355-11ea-814c-25db867d745b.png)

**Comment by Hlavtox** [comment]
That's wrong.
SKU = your stock code = product reference
MPN = manufacturer's code = product mpn in 1.7.7, unused in 1.7.6

Product ID is only for internal purposes of Prestashop.

**Comment by Maofree** [comment]
Hi
I don't know that new entry on 1.7.7
normally in the feed file like for google shopping or other external file, it is used like referal the product id to avoid duplications

**Comment by Maofree** [comment]
https://support.google.com/merchants/answer/7052112
from here you can see that <g:id> is the identificator and must be univocal, it can be the sku like you said or the product id like I say,
if you use in the sku the produt id, google will see the same value in the file got by google merchant center (created by a module) and in the front office of your site

yes you can use the product reference, but how much website has univocal codes in their sites since they are inserted by hand, and before the next 1.7.7 that mcn value is missing

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by Maofree** [comment]
hi
fixed the sku for combinations adding - $product.id_product_attribute if present (like in the combination urls and in the id passed to external system like for google shopping)

`<meta itemprop="sku" content="{$product.id}{if isset($product.id_product_attribute) && $product.id_product_attribute}-{$product.id_product_attribute}{/if}" />`

of course if in the next version prestashop will manage also mpn codes, the strategy can be different (however the id solution is better to be sure to use univocal values)

bye

**Comment by khouloudbelguith** [comment]
@maofree, thanks a lot for your fix suggestion.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Hlavtox** [comment]
@maofree @khouloudbelguith 

```
Best practices

These are best practices that can help you go beyond the basic requirements to optimize your product data for performance. 

Use SKUs as IDs where possible. SKUs help us to understand the structure of your landing page. Since SKUs are unique, they can also help prevent you from accidentally reusing IDs.
```

https://support.google.com/merchants/answer/6324405?hl=en

```
SKU:
The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.
```

https://schema.org/Product

**Comment by Maofree** [comment]
@Hlavtox 
so it is a good solution that one suggested. On 1.7.x the combinations have an own page so it is necessary to add the id product attribute to it like in the google shopping feed passed to google merchant center

**Comment by Hlavtox** [comment]
This has been correctly implemented, SKU is using reference and ID as a fallback, MPN is MPN. :-)
