### ISSUE TITLE
PrettyCI is returning faulty reports

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17744]
It seems since 1 or 2 days, PrettyCI (which is enabled on pull requests) return faulty reports.

Most of the time the issue is that it complains some files are not right although the PR does not modify them.
It seems also it does not 100% follow our PHP CS Fixer configuration.

## Issues on 1.7.6.x branch

- https://github.com/PrestaShop/PrestaShop/pull/17457/

## Issues on 1.7.7.x branch

Example of faulty PRs (target branch 1.7.7.x)
- https://github.com/PrestaShop/PrestaShop/pull/17741 (now fixed)
- https://github.com/PrestaShop/PrestaShop/pull/17736/

This should have been solved by https://github.com/PrestaShop/PrestaShop/pull/17532 (applied to both 1.7.7.x and develop) but it seems it's not 😅

**Comment by matks** [comment]
Help @mnapoli 🙏

**Comment by matks** [comment]
We decided to temporarily disable PrettyCI and use a Github Action instead

**Comment by matks** [comment]
I relaunched PrettyCI on https://github.com/PrestaShop/PrestaShop/pull/17741 and now it passes so it seems some of the issues are random

**Comment by matks** [comment]
Issue seems fixed on branches 177x and develop, still broken on 176x but as this branch receives very few patches, we prefer to keep PrettyCI enabled.

**Comment by mnapoli** [comment]
Hi!

Here is what I did to check that out:

- clone this repository
- I am on the `develop` branch
- `rm composer.json composer.lock`
- `mv .prettyci.composer.json composer.json`
- `composer install`
- I run `pretty`

-> Passed. This is the same behavior as on PrettyCI, it looks OK.

But when I tried the same thing for the 1.7.6.x branch I realized there was no `.prettyci.composer.json` file. That means the latest version of PHP CS Fixer is used.

If I `rm vendor` (to make sure to start from scratch) and run `pretty`, I end up indeed with a large diff.

This issue might now appear because when I upgraded the runners to PHP 7.4, all dependencies also got updated (people kept asking about it for some time).

A solution could be to set up a `.prettyci.composer.json` file in that branch as well? (to target a specific version of php-cs-fixer)

**Comment by matks** [comment]
@mnapoli We encountered multiple different issues, on PRs which target different bases.

**Indeed 1.7.6.x branch has a dedicated set of issues which are most likely related to:**
- no `.prettyci.composer.json` file but we created a PR for that and we have crazy issues https://github.com/PrestaShop/PrestaShop/pull/17721
- 1.7.6.x branch PHP compatibility range is PHP 5.6 to PHP 7.2, which creates issues with your usage of PHP7.4

**But we also encounter random issues on PRs which target 1.7.7.x branch:**
- sometimes timeouts (more than 300 seconds)
- sometimes PrettyCI tells us our codestyle does not meet single_line_throw rule although we made sure to disable it in https://github.com/PrestaShop/PrestaShop/pull/17532 (edited)
- sometimes PrettyCI tells us other codestyle issues such as https://github.com/PrestaShop/PrestaShop/pull/17777/checks?check_run_id=460454860 but the "faulty" files are unrelated to the PR

We're sure it's random because re-running PrettyCI on these PRs either fixes the issue (PrettyCI approves the PR) or provides another issue or returns again the same issue 😛

**Comment by matks** [comment]
Exemples of faulty builds:
- https://github.com/PrestaShop/PrestaShop/pull/17777/checks?check_run_id=460454860
- https://github.com/PrestaShop/PrestaShop/pull/17765/checks?check_run_id=458158728
- https://github.com/PrestaShop/PrestaShop/pull/17711/checks?check_run_id=460415677
- https://github.com/PrestaShop/PrestaShop/pull/17457/checks?check_run_id=460132636

**Comment by mnapoli** [comment]
Thank you for those links, I will look into this. Random errors are the best kind of errors 😅

**Comment by matks** [comment]
@mnapoli I'm sorry to put pressure, but if at the end of the day, PrettyCI keeps sending us false results I'll have to disable it because right now it is hindering multiple developments and consuming developer time (see https://github.com/PrestaShop/PrestaShop/pull/17526 last comments for example). I'll replace it with a Github Action temporarily until PrettyCI comes back faultless. Right now we have contributors submitting valid Pull Requests and they see PrettyCI turn bright red, then they either ask us (good usecase) or try to find the issue in their code (bad usecase as it is time-consuming and might disinterest them from contributing).

**Comment by mnapoli** [comment]
👍  I definitely understand

**Comment by mnapoli** [comment]
Hi @matks, I'm really sorry about your experience.

I am a developer, I understand that PrettyCI isn't living up to the job here. I am looking into things, but I want to find an immediate solution here. Let's try a different strategy: migrating to GitHub Action would be something to try I think. It seems you may have considered/tried that above.

Here is an example of a template that I tried:

```yaml
name: php-cs-fixer
on: [push, pull_request]

jobs:
  build:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.1.2
        with:
          args: --diff --dry-run
```

You may want to run additional steps like running `composer install`.

This is an example of output you would get: https://github.com/mnapoli/test-ci-code-style/runs/467479615 AFAICT this works, let me know if this helps.

**Comment by matks** [comment]
> Hi @matks, I'm really sorry about your experience.
> 
> I am a developer, I understand that PrettyCI isn't living up to the job here. I am looking into things, but I want to find an immediate solution here. Let's try a different strategy: migrating to GitHub Action would be something to try I think. It seems you may have considered/tried that above.

We disabled PrettyCI and replaced it with a GA in https://github.com/PrestaShop/PrestaShop/pull/17746

Indeed we know we can use GA instead, but we were happy supporting French PHP community through the use of PrettyCI 😉 .

**Comment by matks** [comment]
Following https://prettyci.com/goodbye we now know we need to fully replace PrettyCI with GA

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17746 for 1.7.7.x branch and a merge onto develop will fix develop branch too
