### ISSUE TITLE
Exception when adding a new discount with invalid amount - invalid discount

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17747]
**Describe the bug**
In the BO => Orders => new migrated Order details page or legacy page when we add a new discount with an invalid amount for example `-10` => an exception is displayed

**To Reproduce**
1. Go to BO => Orders => new migrated Order details page `admin-dev/index.php/sell/orders/orders/5/view` or the legacy page
2. Click on "Add a new discount" button
2.1. Type = Amount
2.2. Value = -10
3. Click Add
![image](https://user-images.githubusercontent.com/16067358/74853905-da135800-533e-11ea-8006-6f9496b2e6ba.png)
![image](https://user-images.githubusercontent.com/16067358/74853952-ea2b3780-533e-11ea-8c23-5527f7b66fc7.png)

**Additional information**
PrestaShop version: 1.7.7.x, 1.7.6.3, 1.7.5.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @colinegin new issue in the Order page

**Comment by khouloudbelguith** [comment]
Hi,

Same issue with an invalid percent value
An exception detected when we add a new discount = `-10%`
![image](https://user-images.githubusercontent.com/16067358/74854942-4b9fd600-5340-11ea-811f-d4f34e51abe7.png)

![image](https://user-images.githubusercontent.com/16067358/74854891-3b87f680-5340-11ea-9b21-e82e3f0424f3.png)

Reproduced with 177x branch, PS1.7.6.3 and PS1.7.5.2

Thanks!

**Comment by Hlavtox** [comment]
Isn't this the same as this? https://github.com/PrestaShop/PrestaShop/issues/13809

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox, 

We have different exceptions:
#13809: Property Order->total_paid is not valid
#17747: Property CartRule->reduction_prcent is not valid / Property Order->total_discounts is not valid

They are not similar but they are just related.

Thanks!

**Comment by colinegin** [comment]
The behaviour should be the same as in the cart rule page. When adding a discount value (in %) containing a "-", this error message is displayed : 
![image](https://user-images.githubusercontent.com/35263827/75331055-5dbece80-5882-11ea-9907-ba790ebb60a9.png)

And when adding a discount value (in amount) containing a "-", this error message is displayed : 
![image](https://user-images.githubusercontent.com/35263827/75331107-762ee900-5882-11ea-95a5-5a6321028363.png)

So IMO we should be consistent and do the same in the order page. 

After discussing with @TristanLDD and @LouiseBonnard the wording for error messages should be the same as in the cart rule page and the error message should be located on top of the order page. When a error occurs, the pop-up is closed and the user has to re-open it to add a cart rule.

**Comment by LouiseBonnard** [comment]
@colinegin, as long as we stay consistent and display the same error message when the same mistake is done, it suits me fine! :-)

**Comment by LouiseBonnard** [comment]
@atomiix, as @colinegin said, and especially if the error notification is displayed on the top of the page and not in the modal, I prefer to keep the wording consistent and use the same error notifications as in the cart rule page.

**Comment by Hlavtox** [comment]
@LouiseBonnard @colinegin 

Wouldn't it be better to go upfront the employee and just remove the minus from the input, so he can enter the discount with minus or not? Maybe it would be even easier to do and more comfortable for employees.

Because, when you look on it from the other side, the discount is really -15%, why should he be forced to enter positive value?

**Comment by Progi1984** [comment]
Fixed by #17852
