### ISSUE TITLE
Admin area product listing, pagination is disabled

### ISSUE THREAD

**Issue by stevearmen** [PrestaShop/PrestaShop#17751]
**Describe the bug**
In catalog -> products, pagination is disabled and even typing the page number in the input field, it still goes to first page.

**To Reproduce**
1. Review Image

**Screenshots**
[https://imgur.com/mHW5tGg](https://imgur.com/mHW5tGg)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.3.11

**Comment by florine2623** [comment]
Hi @stevearmen ,
Can you change your PHP version to 7.2 ?
You can see the compatibility chart here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Please check and give us feedback, thanks.

**Comment by khouloudbelguith** [comment]
Hi @stevearmen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
