### ISSUE TITLE
Wrong shipping in BO order view page

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#17755]
**Describe the bug**
Shipping price in Back Office order view page differs from Front Office for same order. Occurs in both legacy and migrated pages.
** NOTE ** Its associated with demo data. (the fixtures). With new order it works as expected

**To Reproduce**
1. Go to Orders->select order to view-> find products block
2. Check Shipping price
3. Go to Front office->find the same product->add to cart->check shipping price
4. In FO and BO the shipping prices are different. FO has the correct one.

**Screenshots**
1. migrated page BO ![Screenshot from 2020-02-20 11-20-03](https://user-images.githubusercontent.com/31609858/74919322-16909380-53d3-11ea-9838-8ecce8a88da9.png)
2. legacy page BO ![Screenshot from 2020-02-20 11-20-16](https://user-images.githubusercontent.com/31609858/74919323-17292a00-53d3-11ea-8628-a4abafcb70b8.png)
3. FO ![Screenshot from 2020-02-20 11-23-33](https://user-images.githubusercontent.com/31609858/74919597-7dae4800-53d3-11ea-8390-83b2a6163579.png)

**Additional information**
PrestaShop version: 1.7.7, 1.7.6
PHP version: N/A

**Comment by zuk3975** [comment]
It only occurs with dummy data (the fixtures).
If i create the order myself its working fine.

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

In fact, I have this issue only with orders created by default during the installation PS1.7.6.3 and 1.7.7.x branch.
Is this the exact issue? the order by default?

When I create a new order manually with the same product, it is OK.

Thanks!

**Comment by zuk3975** [comment]
> Hi @zuk3975,
> 
> In fact, I have this issue only with orders created by default during the installation PS1.7.6.3 and 1.7.7.x branch.
> Is this the exact issue? the order by default?
> 
> When I create a new order manually with the same product, it is OK.
> 
> Thanks!

Yes, its the same issue.
I guess its not urgent, but still important for development, so could be fixed at some point.

**Comment by khouloudbelguith** [comment]
@zuk3975, thanks your feedback.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.3, and 1.7.7.x branch.

I will add this issue to our bug roadmap.

Thanks!

**Comment by khouloudbelguith** [comment]
Ping @colinegin, @MatShir, @matks, this issue could be fixed in the 1.7.7.0?

Thanks!

**Comment by Hlavtox** [comment]
What is wrong with this? It's just an order created with an old carrier and a price of 2 EUR. 😄

**Comment by colinegin** [comment]
@marionf do you think it would be easy to modify the fixtures on our side ?

**Comment by marionf** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/17765

**Comment by Progi1984** [comment]
Fixed by #17765
