### ISSUE TITLE
Shipping block missing in the Add a product block

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#17761]
There is a feature regression on the 177x branch, on the order page > view order > add product.

When adding a product to a "payment accepted" order, if choosing the option "create a new invoice", there should be a new block displayed to define shipping information for the new invoice. This was available in the legacy page : 
![image](https://user-images.githubusercontent.com/35263827/74948726-ff669b80-53fc-11ea-932d-c6ef5d159d09.png)

In 177x it is no longer displayed, it should be put back.

**Comment by colinegin** [comment]
ping @Robin-Fischer-PS

**Comment by MatShir** [comment]
@zuk3975, I'm not sure but I think one of your PR fix this?

**Comment by colinegin** [comment]
I think this issue is a duplicate of #18020 . So we can close it.
Do you confirm @khouloudbelguith ?

**Comment by khouloudbelguith** [comment]
@colinegin, yes!

**Comment by khouloudbelguith** [comment]
Duplicate of #18020
