### ISSUE TITLE
Specific price applied to all stores

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#17766]
**Describe the bug**
If you want to apply a specific price to all shop and to a customer group together, the price is wrong on front-office.

**To Reproduce**
Two ways in fact:
1) Use multistore and try to add a specific price to a product **for all store  AND for a customer group**. Price on front office is false.
2) If you don't use multistore and you programmatically add a specific price, the problem on front-office is the same because id_shop will be set to 0.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Max84,

I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1_-UJafNdGWu6Jhg5k2rMFJW-rzLVNwIM/view

Thanks to check & feedback.

**Comment by Max84** [comment]
Hi @khouloudbelguith 

Please could you try to create a customer group with ID 4?
After your screen record, i tried again. You can see it here. On this video, with group ID 6, it's OK.
Just after, I tried with group ID 4.
https://drive.google.com/file/d/1BrrCuM634mhCK6C_C4R47uMG_x1P_cxJ/view?usp=sharing

And the behavior is very strange. It doesn't happen with group with another id than "4".
I don't have cart rules or something like this.

Do you get it too?

Thanks.

**Comment by khouloudbelguith** [comment]
@Max84, It is ok with a Group customer ID =4.
I attached a screen record
https://drive.google.com/file/d/1SjqF1HdXmLoxvxcY3oYq_qyZsqEQFZ_2/view

Thanks!

**Comment by Max84** [comment]
@khouloudbelguith
Strange, I'll check again.
Thanks.

**Comment by khouloudbelguith** [comment]
@Max84, thanks!
Waiting for your feedback!

**Comment by Max84** [comment]
@khouloudbelguith

I close this issue. My database was corrupted. A specific price exists with id_product = 0.
I installed again Prestashop, and now I see the same thing than you.

Thanks for you feedback :)
