### ISSUE TITLE
Prestashop 1.7.6.3. Modules Hook is Missing

### ISSUE THREAD

**Issue by ecoguido** [PrestaShop/PrestaShop#17768]
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by ecoguido** [comment]
In prestashop 1.7.6.3 is not possible to edit the content of modules, modules hook is missing. How to edit the content of each modules please?

**Comment by khouloudbelguith** [comment]
Hi @ecoguido,

Thanks for your report.
In your case, it is not possible to configure a module? 
![image](https://user-images.githubusercontent.com/16067358/74959843-98041800-540b-11ea-8cca-07f18fec8405.png)


Thanks!

**Comment by ecoguido** [comment]
Hi,
Thank you for your response. These configure allow me to change thinks like display or not the module, change the size of it; but there is no option for editing the content of this module. Apparently, the current version of presta no longer have hook manager (https://www.sunnytoo.com/forums/topic/hook-position-missing). The previous version was so easy to edit each module / part of home page. In this version 1.7.6.3 everything is hidden, so difficult to find and edit particular section of the page.

**Comment by khouloudbelguith** [comment]
@ecoguido, thanks for these clarifications.
Thanks to navigate to your BO => Design => Positions page.
You Can click on the "Transplant module" button, you will be redirected to `Transplant a module` page.
![image](https://user-images.githubusercontent.com/16067358/75018625-9e3bd800-548f-11ea-9b8b-bf1e377143fc.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @ecoguido,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
