### ISSUE TITLE
Create order : Shipping is tax incl instead of excl

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17773]
**Describe the bug**
On the new migrated create order page (/sell/orders/orders/new), in the summary of the order, the "Total shipping" is displayed tax incl., but according to the label (and to Legacy page), it should be tax excl.

**To Reproduce**
1. Go to Create Order migrated page
2. Add a product, and a shipping (not free)
3. See Summary : Shipping is displayed tax incl.

**Screenshots**
![create order shipping excl](https://user-images.githubusercontent.com/55688534/75022533-86b41d80-5496-11ea-8787-2630fd87fb74.png)

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17853
