### ISSUE TITLE
Fix Display Bug on Tabs in BO

### ISSUE THREAD

**Issue by TristanLDD** [PrestaShop/PrestaShop#17774]
There is a display bug on all migrated pages using tabs: 

![Capture d’écran 2020-02-21 à 10 58 46](https://user-images.githubusercontent.com/27484094/75024120-37bbb780-5499-11ea-9673-57cac53b54ce.png)

It seems to be linked to the notifications we have in Module manager:

![Capture d’écran 2020-02-21 à 10 52 35](https://user-images.githubusercontent.com/27484094/75024495-c9c3c000-5499-11ea-99d8-013eb6ec3b8f.png)

**Comment by khouloudbelguith** [comment]
Hi @TristanLDD,

Same issue with PS1.7.5.2 and PS1.7.6.3.
I tried with 1.7.7.x branch => OK
![image](https://user-images.githubusercontent.com/16067358/75028859-56be4780-54a1-11ea-93b7-3e841f585782.png)
![image](https://user-images.githubusercontent.com/16067358/75028873-5c1b9200-54a1-11ea-966c-ab74a14b618e.png)

Thanks!

**Comment by TristanLDD** [comment]
Oh I didn't know it has been fixed in 1.7.7, good news! Thanks @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@TristanLDD, since it is fixed, I will close the issue.

Thanks!
