### ISSUE TITLE
PS 1.7.6.3 e-mail Theme translate

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#17789]
Hello!

I try to translate some text in the e-mail Theme like discribed here https://github.com/PrestaShop/PrestaShop/pull/14809

But my text is not applied
![image](https://user-images.githubusercontent.com/50954519/75121434-9c932f80-569c-11ea-8feb-6fb2ebe4c2fe.png)

![image](https://user-images.githubusercontent.com/50954519/75121388-2c84a980-569c-11ea-8226-f1e88ec3a8df.png)

And after letter generation and other peration (like clear cash) the translated text change on the English again....

What is wrong?
Thanks!

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by photinia73** [comment]
And one else...
If it possible to specify the Logo size for Outllok, because this program show the logo tooo big
![image](https://user-images.githubusercontent.com/50954519/75121558-d6186a80-569d-11ea-927a-eb587dc62f5b.png)

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

Thanks for your report.
This PR: https://github.com/PrestaShop/PrestaShop/pull/14809 is added to PS1.7.7.0 and you are using PS1.7.6.3.
New Feature in the PS1.7.7.0
![image](https://user-images.githubusercontent.com/16067358/75141373-19e88f80-56f1-11ea-8906-ecb3afc02267.png)

But, we have a similar issue fixed in the PS1.7.6.1.
https://github.com/PrestaShop/PrestaShop/pull/14719
In fact, I tried with PS1.7.6.3 and it is well working.
I attached a screen record
https://drive.google.com/file/d/1ZLlfB4-ZTagyK2CIzo6LkjTv0Wd5-CCW/view

Thanks to check & feedback.

**Comment by photinia73** [comment]
I have another view than yours No translation in the e-mail Theme ((I can translate it only  in International -> translationMay be there is  update or something else to change this module? З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 11:34Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] PS 1.7.6.3 e-mail Theme translate (#17789) Hi @photinia73,Thanks for your report.This PR: #14809 is added to PS1.7.7.0 and you are using PS1.7.6.3.New Feature in the PS1.7.7.0But, we have a similar issue fixed in the PS1.7.6.1.#14719In fact, I tried with PS1.7.6.3 and it is well working.I attached a screen recordhttps://drive.google.com/file/d/1ZLlfB4-ZTagyK2CIzo6LkjTv0Wd5-CCW/viewThanks to check & feedback.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by khouloudbelguith** [comment]
@photinia73,
>I have another view than yours No translation in the e-mail Theme

Yes!
This is the new feature in the PS1.7.7.0.

In the PS1.7.6. does not exist, but it working in the PS1.7.6.3 from International => Translations page, as recorded in the video.

Thanks!

**Comment by photinia73** [comment]
-->I do this from the International => TranslationsAnd the BO show me that changes are applied. But in the Design->e-mail Theme after generation or without it (I tried all variants) the preview show the text without translation. And the real letter too (( З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 15:38Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] PS 1.7.6.3 e-mail Theme translate (#17789)

**Comment by khouloudbelguith** [comment]
@photinia73, this issue will be fixed in the next major version PS1.7.7.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14809 to fix the issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
