### ISSUE TITLE
Sometimes subcategories go over the menu and prevent clicking on it

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17794]
**Describe the bug**
Sometimes on categories pages, subcategories go over the menu and prevent clicking on it

**To Reproduce**
1. Go to the front-office and click on Accessories
2. Try to click on Art
3. You can't because the subcategories go over
4. See error in the console

**Screenshots**

![capture d'écran_2391](https://user-images.githubusercontent.com/13449658/75142187-d42cc680-56f2-11ea-9ed9-b0307ffa9a74.png)

![capture d'écran_2392](https://user-images.githubusercontent.com/13449658/75142171-cecf7c00-56f2-11ea-833f-26697d778db4.png)

https://drive.google.com/open?id=1stnlle9F4Zwg4MV0oyfS-_bc9jPNOt3a

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17843
