### ISSUE TITLE
Cannot open some of the pages on back-end

### ISSUE THREAD

**Issue by rahulprbh** [PrestaShop/PrestaShop#17793]
Hello
I dont know what to do but im unable to open some of the page on backend categories,brands,pages,seo, etc please let me know any solution.Here im attaching error log please help me.
Thank You
![Screenshot (21)](https://user-images.githubusercontent.com/61406020/75135143-9afe5180-5706-11ea-8359-4b9d27b4eed0.png)
![Screenshot (22)](https://user-images.githubusercontent.com/61406020/75135146-9cc81500-5706-11ea-80de-42fa425082d9.png)
![Screenshot (23)](https://user-images.githubusercontent.com/61406020/75135148-9cc81500-5706-11ea-8fd8-fa5434b00fca.png)

 help me out

**Comment by khouloudbelguith** [comment]
Hi @rahulprbh,

This issue is fixed previously as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14617
As a Provisional solution thanks to try with this SQL query

> ```
> ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> ```

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @rahulprbh,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
