### ISSUE TITLE
1.7.6.3 - Product pictures OK into admin panel, but 404 / not visible for users

### ISSUE THREAD

**Issue by julienrobin28** [PrestaShop/PrestaShop#17791]
When adding a product, picture is uploaded fine, made available through that link https://www.luoss.fr/prestashop/img/p/2/9/29.jpg and visible from any function of the admin interface (excepted product preview).

When browsing the shop as user, products pictures are not visible. Doing "F12" on firefox show that it tries to access https://www.luoss.fr/prestashop/29-home_default/usb-c-multifunction-adapter.jpg which is not the correct link, so it gets a 404

Using PHP Version 7.2.27
Fresh install of PrestaShop for test, with nothing special touched.

**Comment by khouloudbelguith** [comment]
Hi @julienrobin28,

Thanks to navigate to your BO => Design => Image Settings page => scroll down & click on the "Regenerate thumbnails" button.
![image](https://user-images.githubusercontent.com/16067358/73822297-08008480-47f6-11ea-9036-9d10e2a23ed8.png)

Thanks to check & feedback.

**Comment by julienrobin28** [comment]
Hi, thanks for the trick

Unfortunately, it didn't solve the issue
Also, just for information, changing the PHP version does nothing more

If useful, I may try on another server just to see if this bug is server configuration related

**Comment by khouloudbelguith** [comment]
@julienrobin28,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by julienrobin28** [comment]
Your guess is right! it's related to friendly URL : when it's enabled, the problem with picture appears. When it disabled, the problem with the picture disappears.

Is there something that would cause this issue with friendly URL?

At PrestaShop installation and even now from the back office, it says
Check your configuration :
Required parameters: OK
Optional parameters: OK

EDIT : One more information : I did a second try not using the shared web hosting provider, but my own server instead, using Debian 10 and 

`apt update && apt upgrade -y && apt install apache2 libapache2-mod-php php-zip php-mysql php-curl php-gd php-intl php-xml php-mbstring default-mysql-server -y && a2enmod rewrite && systemctl restart apache2
`
Friendly URL wasn't enabled by default. And enabling it is even worst and gives "404 Not Found" as soon as we try to enter the shop as user (the admin back office is the only one to be still working)
Look like there is something broken with Friendly URL on this 1.7.6.3 version (but I'm not sure I used Friendly URL in the past with others versions)

**Comment by khouloudbelguith** [comment]
@julienrobin28,

>Look like there is something broken with Friendly URL on this 1.7.6.3 version (but I'm not sure I used Friendly URL in the past with others versions)

No, it is well working with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/17ijMEjseZ3yLTQGgHmMKFx00j0ywgU2c/view

It seems that it is a server issue.
You need to check with your host.
It could be that the rewrite mod is not enabled
You need to run this command `RUN a2enmod rewrite`.

Thanks to check & feedback.

**Comment by julienrobin28** [comment]
Hi,

$_SERVER['HTTP_MOD_REWRITE']  is On on both server :
phpinfo output attached [phpinfo.pdf](https://github.com/PrestaShop/PrestaShop/files/4250052/phpinfo.pdf)

And for the second test on Debian 10, everything to know about the host, is the commands I played yesterday to install it, which includes a2enmod rewrite : 

`apt update && apt upgrade -y && apt install apache2 libapache2-mod-php php-zip php-mysql php-curl php-gd php-intl php-xml php-mbstring default-mysql-server -y && a2enmod rewrite && systemctl restart apache2`

If it works with some server but not every server, you're probably right : there is something different into those server settings - unfortunately PrestaShop just says that everything is OK, which may be some part of the issue here.

Is it possible that some other requirement are needed to have Friendly URL working?

Thanks for your time

**Comment by khouloudbelguith** [comment]
@julienrobin28, you have some information on the Traffic & SEO page.
"Enable this option only if your server allows URL rewriting (recommended)."
![image](https://user-images.githubusercontent.com/16067358/75253331-960cd100-57de-11ea-81e2-373e10125146.png)
If it is not enabled, you should have this message
![image](https://user-images.githubusercontent.com/16067358/75253425-cfddd780-57de-11ea-8792-8cbf5842ebce.png)

Thanks!

**Comment by julienrobin28** [comment]
I looked again just in case, but I don't have this warning : seems that mod_rewrite is definitely enabled, and the problem is caused by something else (but difficult to know what exactly)

I'll try to look at the .htaccess file this evening, with Friendly URL enabled, to see if everything is generated fine inside of it

**Comment by khouloudbelguith** [comment]
@julienrobin28, thanks!
Waiting for your feedback.

**Comment by julienrobin28** [comment]
So I looked a little bit, for product pictures being in img/p/2/5 (zipped here : [img-p-2-5.zip](https://github.com/PrestaShop/PrestaShop/files/4252795/img-p-2-5.zip)

With Friendly URL off, first page is getting "https://www.luoss.fr/img/p/2/5/25-home_default.jpg" which is fine
With Friendly URL On, first page is getting "https://www.luoss.fr/25-home_default/usb-c-multifunction-adapter.jpg" which isn't working

For languages, Friendly URL is working
https://www.luoss.fr/index.php?id_lang=1 or https://www.luoss.fr/index.php?id_lang=2 (without friendly URL)
https://www.luoss.fr/en/ or https://www.luoss.fr/fr/ (with friendly URL)

Here are the htaccess files, with and without friendly URL enabled
[htaccess-files.zip](https://github.com/PrestaShop/PrestaShop/files/4252810/htaccess-files.zip)

The code added by Friendly URL enabling, looking like regular expressions, is here :

```# Images
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteCond %{HTTP_HOST} ^www.luoss.fr$
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>
```
I guess there is something wrong in it about jpg pictures, or in the way the server interprets it?
From my limited understanding about the issue I guess everything happen into those lines, but may be they should be compared to some working configuration?

**Comment by florine2623** [comment]
Hello @julienrobin28 ,
Could you please send a screenshot of your informations page ?
Back-office > Advanced Parameters > Information
Thanks!

**Comment by julienrobin28** [comment]
Hi @florine2623 

Here it is

![bo-informations](https://user-images.githubusercontent.com/33288584/75356766-ad1bf380-58b0-11ea-853c-739ef972dce3.png)

Thanks again for your time on this issue, hoping this will help at the end

**Comment by florine2623** [comment]
Hello @julienrobin28 ,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration.
You can contact your webhost or [Support Team PrestaShop](https://addons.prestashop.com/en/388-support) for more info.

Thanks!
