### ISSUE TITLE
Module constants are not allowed at install / activate / deactivate

### ISSUE THREAD

**Issue by aecarlosae** [PrestaShop/PrestaShop#17806]
**Describe the bug**
Modules that have class constants in its main class definition, fails at install or activation / deactivation process.

**To Reproduce**
1. Create a module with its elemental definition (Module::__construct(), Module::install(), Module::uninstall().
2. Add in the module class definition a constant ( const MY_CONSTANT)
3. Generate the .zip module file
4. Go to your backoffice -> modules -> module manager
4. Try to install the .zip module file

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @aecarlosae,

Thanks for your report.
Could you please provide me a demo module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by aecarlosae** [comment]
Hi @khouloudbelguith, I sent you the demo module by mail.

**Comment by khouloudbelguith** [comment]
@aecarlosae, thanks for your feedback.
I tried with PS1.7.6.3 and it well working.
I attached a screen record
https://drive.google.com/file/d/1euGNEOJZMHyYvhl2hLHDJ0J18azr26nj/view
Thanks to check and feedback.

**Comment by aecarlosae** [comment]
Excellent, well it's only an issue related with PS1.7.5.1 then. 

Thank you @khouloudbelguith.

**Comment by khouloudbelguith** [comment]
@aecarlosae, thanks for your feedback.
Since it is fixed with PS1.7.6, can we close this issue?

Thanks!

**Comment by aecarlosae** [comment]
Yes @khouloudbelguith, I'm closing it. Greetings!
