### ISSUE TITLE
Faceted search -  when one ore more filters are applied add to basket not work properly

### ISSUE THREAD

**Issue by pantagru** [PrestaShop/PrestaShop#17807]
**Describe the bug**
I have activeted faceted search filters per price, brand, region.
When I apply one or more filter, in all products filtered, the action add to basket open a pop-up with quantity 0 and no product is added to the cart, althought the message say "Product successfully added to your shopping cart".
The only way is refresh the page or, in case of pagination, go the another page.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/41157394/75176522-994b8280-5734-11ea-926c-55b6b278f608.png)
![immagine](https://user-images.githubusercontent.com/41157394/75176107-d4998180-5733-11ea-826a-95daffc179d1.png)

**Additional information**
PrestaShop version: 1.7.2.4
PHP version: 7.1
Faceted search version: 3.4.1

**Comment by khouloudbelguith** [comment]
Hi @pantagru,

I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.2.4 and the ps_facetedsearch v3.4.1.
I attached a screen record
https://drive.google.com/file/d/1VUghwZ5HKnbhKbBCJDdIp1O3wAQ3esBG/view

Thanks to check & feedback.

**Comment by pantagru** [comment]
Hi, 
looking at your video, the behaviour is a little bit different, you click on quick view to open a pop-up with information, then you click on add to basket.
In my case I add to basket directly in the catalog list.
You can see what I mean by this develop link:
http://ciboreat.gammadev.it/
>Edited by Khouloud

**Comment by khouloudbelguith** [comment]
@pantagru, I removed the credentials.
This is a public space.
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment]
@pantagru, you are using a custom theme.
Have you tried to contact the theme author about this issue?
Thanks to check with them and feedback.

**Comment by pantagru** [comment]
I changed the name of the template, from classic to cibor, but it's a classic theme version 1.0.0
Ideated by PrestaShop Team

**Comment by khouloudbelguith** [comment]
@pantagru, but using the classic theme, we can't add to basket directly in the catalog list.
We need to click on the Quick view
![image](https://user-images.githubusercontent.com/16067358/75257027-aa53cc80-57e4-11ea-98ae-1f29ed1797a6.png)

Thanks!

**Comment by pantagru** [comment]
You are right, we have chanced our customization, using the right quick view and everything run well.
Thank you

**Comment by khouloudbelguith** [comment]
@pantagru, great!
I will close the issue, feel free to open a new one when needed.

Thanks!
