### ISSUE TITLE
Bad validation of customer emails in BO

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#17809]
**Describe the bug**

When we have wrong object value in back-office, in some controllers, we can't tell exactly what's wrong, FormBuilder doesn't give us anything even tho we have `try` `catch`

>Edit by Khouloud

**Steps to reproduce the issue:**
1. Go to the FO => Create a new account with an email: `test@test.com.777` => OK
2. Go to the BO => Customers page => Edit the last customer-created
3. See error

It is ok with PS1.7.5.2.
It is a regression.

With PS1.7.6.3 and PS1.7.6.0, when we try to create a customer with the email `test@test.com.777`
=> we have an error
![image](https://user-images.githubusercontent.com/16067358/75232624-d2790680-57b7-11ea-9e74-c2fcbefdff97.png)

With PS1.7.5.2 => it is successfully added.

----------------------------------------------------------------
**To Reproduce**
1. go to ps_customers
2. change e-mail address for some customer to for example some.email@gemail.com.77
3. go to back-office
4. try to edit this customer

check screenshot

**Screenshots**

![image](https://user-images.githubusercontent.com/2137763/75186004-5f37ac00-5747-11ea-98af-2334499729f7.png)

We should have exact information what's wrong here, not a notice because of failure of FormBuilder.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 and PS1.7.6.3.
Steps to reproduce the issue:
1. Go to the FO => Create a new account with an email: `test@test.com.777` => OK
2. Go to the BO => Customers page => EDit the last customer-created
3. See error
![image](https://user-images.githubusercontent.com/16067358/75232312-4bc42980-57b7-11ea-947f-4c10a0873489.png)

It is ok with PS1.7.5.2.
It is a regression.

With PS1.7.6.3 and PS1.7.6.0, when we try to create a customer with the email `test@test.com.777`
=> we have an error
![image](https://user-images.githubusercontent.com/16067358/75232624-d2790680-57b7-11ea-9e74-c2fcbefdff97.png)

With PS1.7.5.2 => it is successfully added.

I’ll add this to the debug roadmap.

Thanks!

**Comment by matks** [comment]
edited, see below

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/17846 was merged and fixed the error

**Comment by matks** [comment]
Hi @kpodemski !

I split this issue in 2 parts as there were 2 items to fix here: the error, and how to handle the error message. Let's continue exploring the 2nd part together in https://github.com/PrestaShop/PrestaShop/issues/17893 !
