### ISSUE TITLE
Property Product->id_tax_rules_group is not valid

### ISSUE THREAD

**Issue by dinospla** [PrestaShop/PrestaShop#17814]
**Describe the bug**
i try to import products with csv file and i take error  Property Product->id_tax_rules_group is not valid

**Screenshots**
![idtax](https://user-images.githubusercontent.com/61296901/75199137-f19d7700-576a-11ea-9485-87d1a30b1841.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0.33

**Comment by arouiadib** [comment]
Could you please show a sample line from your csv? (at least elements with information about taxes).

**Comment by dinospla** [comment]
![Στιγμιότυπο στο 2020-02-25 09-12-17](https://user-images.githubusercontent.com/61296901/75223905-1bc55800-57b0-11ea-8a4f-4be06b0bda1d.png)

**Comment by khouloudbelguith** [comment]
Hi @dinospla,

In your case, the `Tax rules ID` is not valid.
![image](https://user-images.githubusercontent.com/16067358/75228821-0ef53400-57b1-11ea-9432-9b813a3e0525.png)
In the BO => Advanced Parameters => Import page => you can download a sample Products csv file.
You can check the column `Tax rules ID` as an example.
You can find the `Tax rules ID` in the BO => International => Taxes => Tax Rules page
![image](https://user-images.githubusercontent.com/16067358/75229052-70b59e00-57b1-11ea-9ea0-610833fee569.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @dinospla,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
