### ISSUE TITLE
Missing translation in BO for ps_emailalerts "Modules > Mailalerts > Shop"

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17810]
>Edit by Khouloud

**Steps to reproduce the issue**
1. Add a new language in addition to the English language
2. Install the ps_emailalert module
3. Go to the FO => Your account => My alerts
4. Select the second language added previously
5. "No mail alerts yet." expression is not translated
6. Go to the BO => International => Translations page
6.1. Type of translation => Themes translations
6.2. Select your theme
6.3. Select your language
7. The "No mail alerts yet." expression is missing

Missing translation in Classic Theme  "Modules > Mailalerts > Shop" for "No mail alerts yet." from /modules/ps_emailalerts/views/templates/front/mailalerts-account.tpl

![image](https://user-images.githubusercontent.com/44971218/75185288-159a9180-5746-11ea-8a41-8ee074490fe0.png)

![image](https://user-images.githubusercontent.com/44971218/75185425-5beff080-5746-11ea-9838-ca52cd2b541c.png)

![image](https://user-images.githubusercontent.com/44971218/75185463-7033ed80-5746-11ea-9a3c-cc9c186ac61e.png)

Translation is needed in FO Customer Account -> "My Alerts" 

![image](https://user-images.githubusercontent.com/44971218/75185581-a2454f80-5746-11ea-968d-bab15e8b15b3.png)

PS 1.7.5.1 and 1.7.6.3
PHP 7.2.1
nginx/1.14.0

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2 and the Mailalerts module v2.1.1.
![image](https://user-images.githubusercontent.com/16067358/75227700-fbe16480-57ae-11ea-9a4d-1fa086f6a820.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/9697

**Comment by LouiseBonnard** [comment]
Indeed, I've checked Crowdin and this string (_No mail alerts yet._) disappeared after the 1.7.3 catalog. I guess it has been lost when exporting the 1.7.4 and further catalogs, it needs to be reintegrated.

**Comment by kmorgen** [comment]
Seems that the e-mail **SUBJECT** on mails from the latest Mail Alert module (ps_emailalerts V2.2.2) is still not translatable.

In 2.2.1 I guess it was at least possible to use/edit Lang.php to translate subjects.

**Comment by Vipmart** [comment]
Unable to edit email translation under 'ps_emailalerts:
productoutofstock
order_changed

**Comment by concaten** [comment]
Hi there,

Some email object of ps_emailalerts are still missing to translation in **2.2.2 version** 
like "Product out of stock" and "New order :"
Do you confirm ?

**Comment by Vipmart** [comment]
Yes!

**Comment by kmorgen** [comment]
Yes, and also in current **V2.3.0**

**Comment by JMauclair** [comment]
Hi,

It seems that object translations for the emails :
productoutofstock
new_order
return_slip
productcoverage
order_changed
customer_qty

are still missing ?

![image](https://user-images.githubusercontent.com/46693396/124523176-425cbf80-ddf6-11eb-80c3-f645e8fd9cff.png)

**Comment by ProteanCode** [comment]
Still missing in 1.7.7.6

{l s='Notify me when available' d='Modules.Emailalerts.Shop'}

**Comment by borsiorsi** [comment]
> Még mindig hiányzik az 1.7.7.6
> 
> {ls = 'Értesítés, ha elérhető' d = 'Modules.Emailalerts.Shop'}

Check this out: https://github.com/PrestaShop/PrestaShop/issues/9599#issuecomment-937547682
