### ISSUE TITLE
"Set order as shipped" not to close payments

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#17831]
PS 1.7.6
How is it possible to make PS not to close payments when an order est set to a status that has the option "Set order as shipped" ticked (like  Shipped status) no to close payments on the order.
Sometimes you'll ship an order which payment has nos been done or completed, so you don't want PS to automatically add the payment for various reasons:
- Once the payment is added, it will be recorded in the system as received on that date, while it could take several days until you really receive it in your account
- The shipped order could be refused and return to sender for X reasons. In that case, if the customer asks for it again, your employees may see that that order is already 100% paid and wont send it COD, so customer may get a free order or one for what he has only paid an advance
While you consider the possibility of changing this behavior? is it possible to change this on PS? maybe on the code?
Thanks

**Comment by didi-2018** [comment]
@omar2886 please remove hook here: 

![image](https://user-images.githubusercontent.com/44971218/75331522-2997dd80-5883-11ea-9912-01f0bd4d69bd.png)

unhook "set order as paid" will solve your problem ;-)

**Comment by florine2623** [comment]
Hello @omar2886,
You need to unselect 2 options in the Shipped order status :
Shop Parameters > Order Settings > Statuses
![Capture d’écran 2020-02-26 à 11 12 52](https://user-images.githubusercontent.com/16019289/75334961-02440f00-5889-11ea-8700-6e478fe8a529.png)

Please check and feedback to us your results.

**Comment by omar2886** [comment]
OMG, I feel so stupid, after many years using PS I still struggle configuring orders statuses, which has caused me thousands of serious problems with my installation that I'm still suffering nowadays.
Thanks @didi-2018 , that was it. @florine2623 there is no need to uncheck the first option.
Thanks!
