### ISSUE TITLE
Add IDs in the page Information about customer

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#17838]
**Is your feature request related to a problem? Please describe.**
When developing the automated tests, it's hard to check the page content( tables, forms).

**Describe the solution you'd like**
Add IDs for all tables and forms
1 - **Ids** for all blocks
2 - **Classes** or **IDs** for the customer information( Social title, Age...)
3 - Classes **column-name** for all tables to identify all columns 

**Additional context**
All these blocks don't contain IDs
![Information about customer J  DOE • prestashop](https://user-images.githubusercontent.com/24647495/75337201-d460c980-588c-11ea-8538-3b551460b053.png)

![Information about customer J  DOE](https://user-images.githubusercontent.com/24647495/75337361-2275cd00-588d-11ea-87c6-05c1cdcf43f1.png)

Thank you!

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by matks** [comment]
Needed to do tests 😉

**Comment by colinegin** [comment]
Does it have any impact on the user ?

**Comment by matks** [comment]
> 3 - Classes **column-name** for all tables to identify all columns

These are tables built using `tr` and `td` so there are no columns, only rows.
Where would you need the class ? In the tr ? In each td ?

> Does it have any impact on the user ?

Nothing, and it will even help module developers to customize the page

**Comment by nesrineabdmouleh** [comment]
@matks Yes in each td to identify their content :)

**Comment by matks** [comment]
@nesrineabdmouleh Please see PR https://github.com/PrestaShop/PrestaShop/pull/17965 and tell me if it looks good 😊

**Comment by nesrineabdmouleh** [comment]
@matks Thank you so much, very good :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17965/
