### ISSUE TITLE
Back office - Promotional tab

### ISSUE THREAD

**Issue by Katlo123** [PrestaShop/PrestaShop#17834]
While clicking on the "promotional tab", "blog" etc. in the Back office, prestashop gives a following error (attached).  It has been for 3 days now, no updates or fixing.  And meanwhile I cannot update these parts of shop.. 

<img width="1172" alt="Screenshot 2020-02-26 at 09 33 13" src="https://user-images.githubusercontent.com/61497393/75332359-277e5080-587c-11ea-8d81-e233580b9780.png">

PrestaShop version: 1.7

**Comment by florine2623** [comment]
Hello @Katlo123 ,
Could you specify what "promotional tab" you are talking about. Is it the Discounts tab in PrestaShop (Catalog > Discounts) or is it a tab from a module ?
![Capture d’écran 2020-02-26 à 11 21 56](https://user-images.githubusercontent.com/16019289/75335749-484da280-588a-11ea-91f3-6ad8b87502f0.png)

Thanks, please check and feedback.

**Comment by Katlo123** [comment]
Hi Florine,

These 2 blocks are affected: 

<img width="207" alt="Screenshot 2020-02-26 at 10 23 24" src="https://user-images.githubusercontent.com/61497393/75335979-47187780-5882-11ea-8be6-9bb78c1c35ff.png">
<img width="206" alt="Screenshot 2020-02-26 at 10 23 33" src="https://user-images.githubusercontent.com/61497393/75335982-4849a480-5882-11ea-81bb-be132628838e.png">

**Comment by florine2623** [comment]
Hello @Katlo123 ,
Thanks for your feedback. This is a theme issue, you should contact the developer of your theme to fix the 500 error.
I will close this ticket as this is not a PrestaShp issue.
Thanks
