### ISSUE TITLE
The button add to cart is enabled when minimal quantity > quantity of the product - it shouldn't

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17848]
**Describe the bug**
In the FO => Product details page, the button add to cart is enabled when minimal quantity > quantity of the product but it shouldn't
Same issue with a product that has combinations.

**To Reproduce**
1. Go to Bo => Catalog => Product details page
2. Create a new product
3. Set minimal quantity =5 and quantity =2
4. Click on the preview button
5. On the FO, the button add to cart is enabled and we can click on it => it should be disabled
![image](https://user-images.githubusercontent.com/16067358/75357223-5531bc80-58b1-11ea-9c01-e3fc11af8275.png)

Tried with 1724 => OK
![image](https://user-images.githubusercontent.com/16067358/75356922-df2d5580-58b0-11ea-88d1-bcd0cac694a5.png)

With the branch 1.7.7.x => the button is also enabled, but when we click "add to cart" we have an alert
`The product is no longer available in this quantity.`
![image](https://user-images.githubusercontent.com/16067358/75357368-91651d00-58b1-11ea-8964-62ff4222fafc.png)

When we refresh the page => products are well added to cart
![image](https://user-images.githubusercontent.com/16067358/75357433-a8a40a80-58b1-11ea-8a90-ce66a69c6bf2.png)
Related to this: https://github.com/PrestaShop/PrestaShop/issues/13374

**Additional information**
PrestaShop version: 1.7.4.2, 1.7.5.2, 1.7.6.3, 1.7.7.x
PHP version: 7.2

**Comment by arouiadib** [comment]
Thank you @khouloudbelguith for mentioning precisely the exact version (1.7.2.4)  after which the behaviour was broken. That helps a lot :+1:

**Comment by khouloudbelguith** [comment]
The same issue with a product which has combinations

Thanks!

**Comment by arouiadib** [comment]
En Principe, the PR I created should also fix this issue.

But theoretically, other things may not work. Like switching back and forth combinations from FO. As you know, such operations require AJAX and maybe the disabled button will have unwanted behaviour. I have strong belief that a processing is done differently  between the two things: initial page loading vs AJAX loading.  So thank you @khouloudbelguith for raising this issue. Let me put more thought about it and feedback. Meanwhile, I have put my PR to WIP.

**Comment by arouiadib** [comment]
@khouloudbelguith, I have modified the PR to fix that issue too.  Now even if you switch between de combinations in FO product page, the add to cart button get disabled if quantity of combination is lower than minimal allowed quantity. Thank you very much

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17901
