### ISSUE TITLE
Add a modal to confirm or cancel delete action for one row [1/1]

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17847]
Add a modal like on product list to confirm or cancel delete for one row

⚠ Add this modal **with the following message** - edited by @LouiseBonnard following #17082:

`title` = _Delete selection_ in _Admin.Actions_
`confirm_message` = _Are you sure you want to delete the selected item(s)?_ in _Admin.Global_

`confirm_button_label` = _Delete_ in _Admin.Actions_
`close_button_label` = _Cancel_ in _Admin.Actions_

---

Already migrated pages for which it must be added:
- [x] Customers > Addresses
- [x] Customers > Customers > View > Addresses
- [x] Customers > Customers > View > Vouchers
- [x] Customer service > Order message
- [x] Catalog > Files
- [x] Catalog > Brands > Brands
- [x] Catalog > Brands > Addresses
- [x] Catalog > Suppliers
- [x] Catalog > Monitoring
- [x] Design > Pages
- [x] International > Localization > Languages
- [x] International > Localization > Currencies
- [x] Appearence > Pages (categories + pages)
- [x] Shop parameters > Traffic & SEO > SEO&URLs
- [x] Advanced parameters > Email  
- [x] Advanced parameters > Team > Employees  
- [x] Advanced parameters > Team > Profiles  
- [x] Advanced parameters > Database > SQL Manager  
- [x] Advanced parameters > Database > DB Backup
- [x] Advanced parameters > Webservice 
- [x] International > Taxes > Taxes
- [x] Shop parameters > Contact > Contacts

**Comment by jolelievre** [comment]
This is such a pain to reopen this one each time 😅

**Comment by marionf** [comment]
Yes, it was to avoid to make an issue by page (such a pain also) :sweat_smile:

**Comment by Progi1984** [comment]
@marionf No more checkbox. ;)

**Comment by Progi1984** [comment]
:muscle: @marionf
