### ISSUE TITLE
Add a modal to confirm or cancel delete in bulk actions [2/2] 

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17845]
Add a modal to confirm or cancel delete in bulk action instead of the browser one

Already migrated pages for which it must be added:
- [x] Catalog > Monitoring
- [x] Advanced parameters > Email  
- [x] Advanced parameters > Team > Employees  
- [x] Advanced parameters > Team > Profiles  
- [x] Advanced parameters > Database > SQL Manager  
- [x] Advanced parameters > Database > DB Backup
- [x] Advanced parameters > Webservice 
- [x] Shop parameters > Contact > Contacts
- [x] Shop parameters > Traffic & SEO > SEO&URLs

**Comment by marionf** [comment]
@PrestaShop/prestashop-qa 
@SimonGrn 
Auto tests will need to be updated

**Comment by boubkerbribri** [comment]
> @PrestaShop/prestashop-qa
> @SimonGrn
> Auto tests will need to be updated

@marionf Thank you for the alert, we will keep an eye on this issue

**Comment by Progi1984** [comment]
@marionf The last PR comes to be merged.
