### ISSUE TITLE
Trying to update stock via webservice

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#17857]
Im trying to update stock via webservice

> https://example.com/api/stock_availables

and im using PSWebServiceLib ...This is my code:

```php
$xmlStockResponse = $this->webService->get(['url' => $this->url . '/api/stock_availables?schema=blank']);
$addXMLStock = $xmlStockResponse->stock_available;
$addXMLStock->id = self::getStockMaxId();
$addXMLStock->id_product = $psProductId;
$addXMLStock->id_product_attribute = '0';
$addXMLStock->id_shop = '1';
$addXMLStock->id_shop_group = '0';
$addXMLStock->quantity = self::getStock($registeredSku);
$addXMLStock->depends_on_stock = '0';
$addXMLStock->out_of_stock = '0';
$addXMLStock->location = '';
try{
    $addedStockResponse = $this->webService->edit([
        'resource' => 'stock_availables',
        'putXml' => $xmlStockResponse->asXML(),
    ]);
    var_dump($addedStockResponse);
}catch(PrestashopWebserviceException $e){
        echo $e->getMessage()."\n";
}
```

when i start the "script" on terminal only show this:
 > This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error.

Don't know if is a bug or my stupidity can you help me?

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @P41N3ST,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Second, you can use this script to update stock available:
```
<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'shop.com');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'shop.com',
    'key',
    false);
$id = 1; //ID order Here
$xml = $ws->get(array('resource' => 'stock_availables', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
$xml->stock_available->quantity = 1000;
$xml->stock_available->physical_quantity = 5;
$xml->stock_available->reserved_quantity = 4;
//$xml->order->shipping_number = 10;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'stock_availables';
$xml = $ws->edit($opt);
$xml = $ws->get(array('resource' => 'stock_availables', 'id' => $id));
echo "AFTER\n";
echo $xml->asXML();
```
But the `physical_quantity` and `reserved_quantity` are not updated as reported here: https://github.com/PrestaShop/PrestaShop/issues/15976.
It is added to our bug roadmap.
Also, for more details you can follow our official documentation: http://doc.prestashop.com/display/PS16/Web+service+tutorial

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15976

**Comment by QueeNFrisk** [comment]
Ok, thanks, sorry for the disturbances

**Comment by felipeseo** [comment]
hello, I have a similar problem, prestashop with webservice does not let me edit or delete stock, but in my case I use nodejs which is javascript.
