### ISSUE TITLE
Fix TinyMCEEditor that shouldn't handle language switching

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#17855]
**Describe the bug**
To fix this initial issue https://github.com/PrestaShop/PrestaShop/issues/16646
A feature was added into TinyMCEEditor in this PR https://github.com/PrestaShop/PrestaShop/pull/17444
So it is now able to dispatch an event `selectedLangauge` when its parent navigation switches tab
However this feature is already managed by the `TranslatableField` component
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/components/translatable-field.js#L31

This breaks the separation of responsibility:
- TinyMCEEditor is responsible of initiating rich text areas, it is also able to detect a `'shown.bs.tab'` event from its parent This is necessary because tab switching breaks the editor content, so it reset its content to respond correctly to the tab switching (that may or may not be related to a language switch)
- TranslatableField is able to manage tab navigation for languages (to my knowledge it is the equivalent of TranslatableInput but for text areas)

**Refacto**
Steaps to fix this architectural mix:
- remove from TinyMCEEditor the event features
- to fix the initial issue (brand/supplier forms) add the TranslatableField in the form js (for supplier it's https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/supplier/supplier-form.js#L53)

Here is an example of a correct form https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/manufacturer/index.js#L63

**Possible Improvement**
It appears in this case a component was simply forgotten, to avoid this problem in the future maybe we could create component that would include both `TranslatableInput` and `TranslatableField` Or we could merge the two components into one

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17907
