### ISSUE TITLE
.rtlfix files should not be in public folders of BO themes

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#17862]
**Is your feature request related to a problem? Please describe.**
As we decided to avoid pushing the assets on the repo, we need to keep .rtlfix files as they are used to fix some bugs while on RTL languages.

But they should'nt be in the asset's folder, we should extract it somewhere and a backend change has to be done

**Describe the solution you'd like**
Change the path of the rtlfix to another which is not in asset's folder

> Edit by @mparvazi 
## How to get rid of .rtlfix

**1) Delete theme.rtlfix**

**2) Create rtl.scss**
`admin-dev/themes/new-theme/scss/rtl.scss`
The content of rtl.scss is exactly same as theme.rtlfix (it's better to be redesigned for Sass)

**3) Use webpack to build rtl.css**
 `admin-dev/themes/new-theme/.webpack/common.js`

![webpack](https://user-images.githubusercontent.com/85633460/148946687-2374ffe1-c303-4523-96b0-f84ce7dc38f1.png)

**3) Add a condition to prevent rtl.css to be transformed by CSSJanus**
`src/Core/Localization/RTL/StylesheetGenerator.php`

![proccess](https://user-images.githubusercontent.com/85633460/148949309-0514f991-0683-4565-a552-c2456b1a229f.png)

**4) If shop language is RTL then add rtl.css**
`classes/controller/AdminController.php`

![shop](https://user-images.githubusercontent.com/85633460/148947911-1fcdb7c1-a69b-45cc-abd2-ec2e15992751.png)

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by NeOMakinG** [comment]
@Progi1984 don't assign me, rtlfix path is related to backend stuff

**Comment by mparvazi** [comment]
## How to get rid of .rtlfix

**1) Delete theme.rtlfix**

**2) Create rtl.scss**
`admin-dev/themes/new-theme/scss/rtl.scss`
The content of rtl.scss is exactly same as theme.rtlfix (it's better to be redesigned for Sass)

**3) Use webpack to build rtl.css**
 `admin-dev/themes/new-theme/.webpack/common.js`

![webpack](https://user-images.githubusercontent.com/85633460/148946687-2374ffe1-c303-4523-96b0-f84ce7dc38f1.png)

**3) Add a condition to prevent rtl.css to be transformed by CSSJanus**
`src/Core/Localization/RTL/StylesheetGenerator.php`

![proccess](https://user-images.githubusercontent.com/85633460/148949309-0514f991-0683-4565-a552-c2456b1a229f.png)

**4) If shop language is RTL then add rtl.css**
`classes/controller/AdminController.php`

![shop](https://user-images.githubusercontent.com/85633460/148947911-1fcdb7c1-a69b-45cc-abd2-ec2e15992751.png)

**Comment by Progi1984** [comment]
@mparvazi Are you ready to make a PR ?

**Comment by mparvazi** [comment]
@Progi1984 
This PR https://github.com/PrestaShop/PrestaShop/pull/27611 should be merged first, because it will be done most of stuff for this issue.
