### ISSUE TITLE
"Data from PrestaShop Addons is invalid, and cannot fallback on cache." - 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17866]
Hi, 

I just checked my logs under advanced settings -> Log-Data and I saw this log:

Data from PrestaShop Addons is invalid, and cannot fallback on cache.

![image](https://user-images.githubusercontent.com/44971218/75444784-5ec82c80-5964-11ea-8ec9-f2ba5e0a3698.png)

Sorry, I can not provide more infos.

PS 1.7.6.3
PHP 7.2.1
nginx/1.14.0

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

It might be a temporary Addons issue or a timeout issue.
Now it's fixed.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  Hello, same issue today. The page "Logs" is not loaded with SSL it is loaded insecure.

**Comment by matks** [comment]
> @khouloudbelguith Hello, same issue today. The page "Logs" is not loaded with SSL it is loaded insecure.

You're quick ! 😄 Same root cause: issue on Addons API, currently being fixed
See http://status.prestashop.com/ to monitor API status
