### ISSUE TITLE
Order view all products becomes refunded

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#17867]
**Describe the bug**
If I open order in migrated page and use partial refund of one product, then trying to add new products results in all of them being `refunded`

**To Reproduce**
1. Go to `admin-dev/orders/orders/[orderId]/view` to reach migrated order view page
2. Make sure status is payment accepted.
3. Click partial refund -> fill quantity -> refund.
4. See that product is marked with 'refunded' in list.
5. Search for another product -> add
6. See that this added product is also marked with 'refunded'

**Expected behavior**
Only refunded product must be marked with 'refunded'.

**Screenshots**
Migrated page: ![Screenshot from 2020-02-27 14-43-41](https://user-images.githubusercontent.com/31609858/75446256-b9b35100-596f-11ea-9010-990aaac6556d.png) Legacy page: ![Screenshot from 2020-02-27 14-44-20](https://user-images.githubusercontent.com/31609858/75446265-c0da5f00-596f-11ea-876b-04a1ccf6e849.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

Same issue with 1.7.7.x branch.
Thanks!

**Comment by atomiix** [comment]
This issue should be fixed with #17801

**Comment by Progi1984** [comment]
Fixed by #17801
