### ISSUE TITLE
Replace http with https in socials' urls in the ps_sharebuttons module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17876]
Hi
I've seen that in ps_sharebuttons.php in the function getWidgetVariables it is necessary to replace http with https for socials' urls for facebook and pinterest
`http://www.facebook.com`
into
`https://www.facebook.com`

and

`http://www.pinterest.com`
into
`https://www.pinterest.com`

bye

**Screenshots**
![22](https://user-images.githubusercontent.com/653230/75466981-520aff00-598b-11ea-8425-52f3033c8ba5.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2
Module version: 2.0.1

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?
I created a PR: https://github.com/PrestaShop/ps_sharebuttons/pull/34 for @maofree suggestion :slightly_smiling_face: 

Thanks!

**Comment by matks** [comment]
I think no need for Product confirmation, it makes perfect sense.
Fixed by https://github.com/PrestaShop/ps_sharebuttons/pull/34, will be delivered with next release of ps_sharebuttons
