### ISSUE TITLE
in catalog/listing/product-list.tpl it is necessary to remplace the h2 with the h1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17878]
Hi
in the pages: new products, best sales and price drops it is missing the H1 tag like for other pages as product or category or brand

so to solve this problem it is necessary to edit catalog/listing/product-list.tpl and remplace the h2 with the h1

bye

**Screenshots**
![4](https://user-images.githubusercontent.com/653230/75471839-03616300-5993-11ea-86ee-9281f66dcfa7.png)
![5](https://user-images.githubusercontent.com/653230/75471864-0c523480-5993-11ea-87e2-ebbfa1ba9940.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I have the same behavior with PS1.7.6.3 and PS1.7.5.2
`new-products`
`best-sales`
`prices-drop`

Ping @PrestaShop/prestashop-product-team what do you think?

Related to this: https://github.com/PrestaShop/PrestaShop/issues/10470, https://github.com/PrestaShop/PrestaShop/issues/10444

Thanks!

**Comment by colinegin** [comment]
Yes I agree we should fix this bug. Thanks @maofree for this feedback
