### ISSUE TITLE
CmsPageException codice 0, to create new cms page

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17880]
Hi
I manage a new website, very big, it is has a strange error

`Si è verificato un errore inaspettato. [PrestaShop\PrestaShop\Core\Domain\CmsPage\Exception\CmsPageException codice 0]`

it happens only in this website, I've tried to remove all cms pages, then create a new one but I get the same error when I try to push on the save button.

What does this type of error refer to? on the internet I found several even though they refer to other things

thanks

**Screenshots**
![3](https://user-images.githubusercontent.com/653230/75481216-f9dff700-59a2-11ea-8d1d-e0ca606cd78c.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I did not manage to reproduce the issue with PS1.7.6.3.
I tried all these situations
- Renaming the Home category page to "information" from the database manually => OK
- Using Multi-languages => OK
- Disable the employee language => OK
- Using One language => OK

Have you any field required not except the title and Friendly URL?

Thanks!

**Comment by khouloudbelguith** [comment]
Could be related to this: https://github.com/PrestaShop/PrestaShop/issues/16725 & https://github.com/PrestaShop/PrestaShop/issues/16514

**Comment by Maofree** [comment]
Hi
this case is similar to #16514 but on cms pages
in this site there are 11 languages, the error is present with and without accent url option
the strange thing is that removing all cms page already present and creating a new example cms page with just aaaaaa for each titles, the error continue to be present. I'll continue to do some tests in the next days

![1](https://user-images.githubusercontent.com/653230/75606277-5bab7880-5aeb-11ea-8bf2-55eb0dde63ea.png)

**Comment by khouloudbelguith** [comment]
@maofree, thanks!
Waiting for your feedback.

**Comment by Gipielle** [comment]
This error is present in both version PS 1.7.6.2 and 1.7.6.3
maybe is due to an update from version 1.5 passed to 1.6 and immediately to 1.7
Maybe something in the update process did not go correctly.

**Comment by Gipielle** [comment]
Using debug un PS 1.7.6.3:

CRITICAL                 22:06:08 | php | Uncaught Notice: Undefined variable: previewUrl
-- | -- | --
CRITICAL                 22:06:08 | request | Uncaught PHP Exception  Symfony\Component\Debug\Exception\ContextErrorException: "Notice:  Undefined variable: previewUrl" at  /Design/CmsPageController.php  line 299

**Comment by Gipielle** [comment]
Fixed, 

the problem was almost certainly due to a failure to update the ps_cms table.

setting the table correctly everything works.
![tabella-giusta](https://user-images.githubusercontent.com/53569015/76172467-a3d73480-6196-11ea-9132-8fb8844da939.jpg)
![tabella-sbagliata](https://user-images.githubusercontent.com/53569015/76172469-a5a0f800-6196-11ea-9537-5f8879999790.jpg)

**Comment by Gipielle** [comment]
In old table missing column indexation and the id_shop column was not necessary

**Comment by khouloudbelguith** [comment]
Ping @maofree any news?

Thanks!

**Comment by Maofree** [comment]
hi
you can close this topic, it was due from a wrong upgrade
thanks

**Comment by Gipielle** [comment]
Look here, there is another problem
https://www.prestashop.com/forums/topic/1003257-undefined-variable-previewurl-when-trying-to-add-html-code-to-cms-page/?tab=comments#comment-3206945
