### ISSUE TITLE
actionCartUpdateQuantityBefore

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#17888]
**Describe the bug**
Using 1.7.6.3 PS i found out one issue with actionCartUpdateQuantityBefore hook.
In ps_hook_alias we can see that alias is actionBeforeCartUpdateQty and name is actionCartUpdateQuantityBefore. Looks all good but in ps_hook instead of using name and title as actionCartUpdateQuantityBefore there is only actionbeforecartupdateqty.
Because of this only actionbeforecartupdateqty hook works and actionCartUpdateQuantityBefore doesn't.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @margud,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/13518?

Thanks!

**Comment by margud** [comment]
Yes it is.

**Comment by khouloudbelguith** [comment]
@margud,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12578 to fix the issue.
Your ticket is a duplicate of #13518
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #13518
