### ISSUE TITLE
Order validation takes more than 2 minutes regardless of server its running on

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#17895]
#### Describe the bug

If I click on buy in the shopping cart so one of the validation method becomes called and it takes more than 2 minutes to finish.

The payment method is irrevelant, its the execution time of `validateOrder` in `PaymentModule.php`

Its also not important if the app is behind nginx proxy like traefik or nginx itself, I ran it without proxying anything and problem still persisted.

From what I remember the longest time was spent there:

```
// Hook validate order
                    Hook::exec('actionValidateOrder', array(
                        'cart' => $this->context->cart,
                        'order' => $order,
                        'customer' => $this->context->customer,
                        'currency' => $this->context->currency,
                        'orderStatus' => $order_status,
                    ));
```

and at sending mail.

The logs from the whole thing:
![mailchimp](https://user-images.githubusercontent.com/43477801/75598814-05b0e380-5a9f-11ea-9a9f-762562c2f775.png)

#### Expected behavior

I think that on bare metal dedicated server this should end under 10 seconds, not 2 minutes+

#### Steps to Reproduce

You can use [prestashop/prestashop](https://hub.docker.com/r/prestashop/prestashop/ ) `1.7-7.2-apache` since I am working on that but I mount a files of existing shop (1.7.6.1) into /var/www/html

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2

Tell me what should I inspect since I am already like 10 hours on with this thing, I am suspecting an email misconfiguration which I will check tomorrow, but it should be a something more than that

**Comment by Gipielle** [comment]
I'm also interested in this

**Comment by didi-2018** [comment]
me too with 1.7.6.3

**Comment by ProteanCode** [comment]
This had something to do with email configuration in my case. Check if you can send test email in your admin panel.

Now its working but I am not really sure if this was the real reason. @Gipielle  @didi-2018  could you check if you can send the test email without getting a Timeout? If you are running docker environment the sendmail may not be installed on alpine-based images but this is something you probably do not get crossed with

**Comment by khouloudbelguith** [comment]
Hi @ProteanCode,

About the "Frontcontroller::init" error, it is a different issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/9866

>Tell me what should I inspect since I am already like 10 hours on with this thing, I am suspecting an email misconfiguration which I will check tomorrow, but it should be a something more than that

In my case, When the email is not well configured, it is well working also
https://drive.google.com/file/d/1UZBNIJ232LqTPAJzIQ6UYdJ-JIgzNmwN/view

The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ProteanCode,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
