### ISSUE TITLE
Method getClientIp() returns proxy IP instead of the forwarded IP

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#17892]
As the title says.

I host the shop using docker and jwilder's nginx proxy.

The $_SERVER has my real IP address, but getClientIp() returns the REMOTE_ADDR which is a proxy IP.

You can see this behavious in Maintenance controller where you return the 'currentIp' variable to template

* PrestaShop version: 1.7.6.1
* PHP version: 7.2

Solution proposal: use the remote IP method from Tools class

**Comment by khouloudbelguith** [comment]
Hi @ProteanCode,

Thanks for your report.
Is it similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/13074?

Thanks!

**Comment by ProteanCode** [comment]
> Hi @ProteanCode,
> 
> Thanks for your report.
> Is it similar to this issue: #13074?
> 
> Thanks!

I noticed this while investigating why payment gateways are not opening (got 504 while waiting for payment processor). It looks like external content could not load on the web page so I am going to use network_mode host in docker since using Prestashop behind web proxy is a dreadful experience.

**Comment by khouloudbelguith** [comment]
@ProteanCode, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17785 to fix the issue: https://github.com/PrestaShop/PrestaShop/issues/13074
Maybe related https://github.com/PrestaShop/PrestaShop/issues/17117

Thanks to check & feedback

**Comment by ProteanCode** [comment]
> Hi @ProteanCode,
> 
> Thanks for your report.
> Is it similar to this issue: #13074?
> 
> Thanks!

Also sorry for wrong prestashop version, this buf occurs on 1.7.6.1, not 1.7.6.3

**Comment by khouloudbelguith** [comment]
@ProteanCode, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17785 to fix the issue: https://github.com/PrestaShop/PrestaShop/issues/13074
Maybe related https://github.com/PrestaShop/PrestaShop/issues/17117

Thanks to check & feedback

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
