### ISSUE TITLE
Add new CMS page issue

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#17894]
Hi, 
I have this issue in my edit or new cms page:
 
![Screen Shot 2020-02-29 at 3 22 48 AM](https://user-images.githubusercontent.com/20775532/75595791-ffbd0180-5aa2-11ea-8151-ec800e3270d0.png)

the JS error is: TypeError: tinyMCE.activeEditor.getBody(...) is null
cms_page_form.bundle.js:25:6336

I've also cleaned the var/cache/prod. Also, we have upgraded the presta from 1.7.5.2 to 1.7.6.3.
thanks in advance

**Comment by samberrry** [comment]
solved

**Comment by surflibre** [comment]
Hi,
How did you solved it ?

**Comment by samberrry** [comment]
@surflibre 
Hi, 
It's interesting for me that how I fixed it..
May be it was https issue I mean activating ssl on all pages, I don know waht happened exactly, so soryy for that

**Comment by surflibre** [comment]
Hi,
After many hours of testing, search with differents websites under PS 1.7.8 with this bug, I've found an heavy solution :
I've downloaded the official prestashop's Github archives, and I've replaced the new-theme in /admin/themes.
Works for me, 
Solved

**Comment by samberrry** [comment]
@surflibre ,
great. 
Thanks for sharing

**Comment by surflibre** [comment]
try it yourself, and if it works you can thank me!

**Comment by Dan88Hus** [comment]
> Hi, After many hours of testing, search with differents websites under PS 1.7.8 with this bug, I've found an heavy solution : I've downloaded the official prestashop's Github archives, and I've replaced the new-theme in /admin/themes. Works for me, Solved

you are hero, saved my days
