### ISSUE TITLE
I can't upgrade my prestashop store

### ISSUE THREAD

**Issue by YanisseZ** [PrestaShop/PrestaShop#17896]
#### Describe the bug

I can't upgrade prestashop i have a warning on the line 
`PHP's max_execution_time setting has a high value or is disabled entirely (current value: 300 seconds)`

**Screenshots**

[Screen](https://image.noelshack.com/fichiers/2020/09/6/1582963260-capture.png)

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 7.2.19

**Comment by monix12** [comment]
I have the same problem. How to solve it? i have prestashop 1.7.6.3
