### ISSUE TITLE
BO - Quick search - redirect to the Categories list page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17908]
#### Describe the bug

In the BO, When we search a category with the quick search, we are always redirected to the Categories list page instead of the Edit category page

#### Expected behavior
Redirection to the Categories list page
**Explain what you expected to happen instead.**
Redirection to the Edit category page

#### Steps to Reproduce

1. Go to BO
2. Search with the "Women" category for example in the top of the page
![image](https://user-images.githubusercontent.com/16067358/75667640-4c0d6a80-5c78-11ea-8987-0f972740f37d.png)

3. Click on the "Edit" button
![image](https://user-images.githubusercontent.com/16067358/75667683-5b8cb380-5c78-11ea-8dd0-40f6c560e481.png)

3. Redirection to the Categories list page  instead of the Edit category page

It is ok with PS1.7.5.2
https://drive.google.com/file/d/1yZ9d7uD_NwqDhRP5irBRR-cVIgTlTZz3/view

#### Additional information

* PrestaShop version: 1.7.6.0, PS1.7.6.3, Branch 1.7.6.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/14672

**Comment by Betafer** [comment]
Hello, is this a workaround for fix this ?

**Comment by Progi1984** [comment]
@Betafer A PR #17920 has been created but need to be tested by our QA Team.

**Comment by Progi1984** [comment]
Fixed by #17920
