### ISSUE TITLE
Sort product table (in email, invoices and order view) by reference id

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#17903]
Hello, 

for working better and faster is it would be advisable that both in the orders in the emails and in the pdf the products were ordered by reference

so as to speed up the pickup from the warehouse, as well as avoid errors.

_EDIT:_

**Specs:**
Sort the table of products in alphabetical order of references:
- the invoice file, 
- the credit slip file, 
- the delivery slip file, 
- the order preview on the order list, 
- the products table on the order page, 
- the cart summary on the shopping cart page.

**Comment by khouloudbelguith** [comment]
Hi @Gipielle,

Thanks for your report.
I think it could be a good improvement.
In the Order details page & in the email, products are not sorted.
![image](https://user-images.githubusercontent.com/16067358/75664589-fb474300-5c72-11ea-942f-ac42fee3dbe3.png)
![image](https://user-images.githubusercontent.com/16067358/75664620-07cb9b80-5c73-11ea-9a97-97e4ea04058f.png)

In the PDF, products are sorted by name
![image](https://user-images.githubusercontent.com/16067358/75664809-5ed17080-5c73-11ea-8e5c-d9e3611e90ce.png)

Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by MatShir** [comment]
Hi @Gipielle,
That is a great idea, it makes sense to sort it by references. As a merchant, do you have a nomenclature for all your products to distinguish them from each other?

But do you think sorting by reference is the main working method for a merchant? Do you think It might interest to sort/regroup by alphabetical, by suppliers or even categories?

**Comment by Gipielle** [comment]
Hello,

in my case I have all the coded articles,
working with only one supplier, ordering by supplier is not a problem for me.

We had made the change in prestashop 1.5 which was then lost in the update to 1.7.

I noticed that it works much better with the ordered codes, for a variety of reasons.

I asked that it be included in prestashop in order not to lose the changes with each update and because I think it can be useful not only for me.

**Comment by Gipielle** [comment]
Is there a quick method of solving this problem?

**Comment by MatShir** [comment]
Your feature request is a good start for sorting the product in the product table on the order pages related. On a further step, we might need to think for a more complete feature if more merchant has a different way of working.

@Gipielle, I'm sorry for the moment there is no fix for you right now.
PrestaShop is an open-source project, so anyone can contribute to propose a fix at any time.
If you have the technical knowledge or have someone that could don't hesitate to propose a pull request (find more information [here](https://devdocs.prestashop.com/1.7/contribute/)). We will be happy to add your feature to the PrestaShop core.

**Comment by Gipielle** [comment]
Ok, Thinking about simple and functional solutions, complex solutions in my opinion create more problems

**Comment by Gipielle** [comment]
From prestashop forum:

 PS 1.7.3.

Found a solution for this...

classes/order/OrderInvoice.php

somewhere around row 130 where getProductsDetail

change

' ORDER BY od.`product_name`');

to

' ORDER BY od.`product_reference`');

**Comment by Gipielle** [comment]
> Your feature request is a good start for sorting the product in the product table on the order pages related. On a further step, we might need to think for a more complete feature if more merchant has a different way of working.
> 
> @Gipielle, I'm sorry for the moment there is no fix for you right now.
> PrestaShop is an open-source project, so anyone can contribute to propose a fix at any time.
> If you have the technical knowledge or have someone that could don't hesitate to propose a pull request (find more information [here](https://devdocs.prestashop.com/1.7/contribute/)). We will be happy to add your feature to the PrestaShop core.

Usually warehouses are organized by codes and not by article name. If you use the prestashop documents to collect the products in the warehouse, you do it by code.

**Comment by mathieumallet37** [comment]
I have a solution to propose for sorting products in the order view in prestashop 1.7.5.

You have to change the "getProduct" function in AdminOrdersController.php 
You will find this function in "controllers/admin/AdminOrdersController/"

Search for the getProduct function and below the line: 
`$products = $order->getProducts();`

insert this :

`usort($products, function($a, $b) {
    return strcmp($a['reference'], $b['reference']);
});`
