### ISSUE TITLE
Back office product statistics

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17905]
Hello 
I have problem with back office main page
In statistics the images didnt load correct...
![Screenshot_2020-03-01-21-10-33-272_com android chrome](https://user-images.githubusercontent.com/1392266/75632096-80920f80-5c01-11ea-86a6-0e55fea08127.jpg)
![Screenshot_2020-03-01-21-10-57-041_com android chrome](https://user-images.githubusercontent.com/1392266/75632100-84be2d00-5c01-11ea-8249-b8ac0b85dc1e.jpg)

![IMG_20200301_211438](https://user-images.githubusercontent.com/1392266/75632118-b2a37180-5c01-11ea-81fe-a3c6d6ee4204.jpg)

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Thanks for your report.
What is the exact problem of the product's image?
They are not well displayed?
The images displayed are incorrect?
Could you please try to navigate to the BO=> Design => Image Settings page => Try to "Regenerate thumbnails".

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
