### ISSUE TITLE
Wrong display in checkout page for registered customers without address

### ISSUE THREAD

**Issue by ZioCan** [PrestaShop/PrestaShop#17906]
In the checkout page there is a link for the logout (`<a href="https://www.mydomain.com/?mylogout=">`) that cover the entire area of the address form, so a clicking on the address form area (a field or even a empty space) cause the logout of the customer.
I have a multishop with two different domains, each shop has a different theme but the problem is present on both shops, the theme's author says this problem occur with the Classic theme too.
Other users with PS 1.7.6.3 (and other themes) have the same problem.

Chekout page HTML code:
`<div class="col-md-8">`
` <section id="checkout-personal-information-step" class="checkout-step -reachable -complete">`
`   ... Personal informations ...`
` </section>`
` `
` <a href="https://www.www.mydomain.com/?mylogout=">   <!- THIS ROW CAUSE THE PROBLEM ->`

` <section id="checkout-addresses-step" class="checkout-step -current -reachable js-current-step -clickable">`
`   ... Addresses ...`
` </section>`
` `
` <section class="checkout-step -unreachable" id="checkout-delivery-step">`
`     ... Shipment ...`
` </section>`
` `
`  <section class="checkout-step -unreachable" id="checkout-payment-step">`
`     ... Payment ...`
` </section>`
` `
`  </a>   <!- THIS ROW MUST NOT BE HERE->`
`</div>`

#### Steps to Reproduce
Put a product in cart
Register with name and password but DO NOT enter any address
Go to the checkout
Now PS prompt for an address, but when you try to enter it you will be logged out
If you sign in again, your cart is still there, you can go at the checkout again and the problem remain
Looking at the HTML source of the page, i can see the logout link (`<a href="...?mylogout=">`) repeated many times in the page, but often this tag it's open and closed without content in it (`<a ...></a>`), so it's useless but not dangerous.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.3.15

**Comment by khouloudbelguith** [comment]
Hi @ZioCan,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by ZioCan** [comment]
Switched to PHP 7.2.28, nothing changed, the problem remains

**Comment by khouloudbelguith** [comment]
@ZioCan, I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1lefFka3egQXMax7BUeBT1kRC3kOLmiH4/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ZioCan** [comment]
Solved! Not a Prestashop problem, but a wrong translation in theme, these two:
`Connected as [1]%firstname% %lastname%[/1].`
`Not you? [1]Log out[/1]`
in the translation there was a blank spaces between / and 1

**Comment by khouloudbelguith** [comment]
@ZioCan, thanks for your feedback.

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by rafafximenes** [comment]
Thank you very much, I had this problem.
The problem is really in the table
"ps_translation" in the "translation" field. Some records with [/ (space)].
That it serves for others who are with the same problem.

**Comment by Mwaqas1** [comment]
> Solved! Not a Prestashop problem, but a wrong translation in theme, these two: `Connected as [1]%firstname% %lastname%[/1].` `Not you? [1]Log out[/1]` in the translation there was a blank spaces between / and 1

Thank you so much - indeed this is something which needs a sharp eye like you to rectify and tell others. thanks again

**Comment by fmozzati** [comment]
Thanks for your help. I read several forums and some had the same problem, but you were more specific where to find the error!

**Comment by ysraelcm** [comment]
YOU ARE A GOD !!!
You saved my life. :)

I was actively searching and couldn't find the right answer until I came here and saw your great solution.
Thank you for sharing your valuable knowledge and experience.

Kind regards !!!
