### ISSUE TITLE
Can't add a payment in migrated view order page when using an RTL language

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17916]
#### Describe the bug

Can't add a pyament in new order page when using an RTL language because of the date

#### Steps to Reproduce

1. Install Arabic
2. Open an order with the migrated page
3. Try to add a payment

**Screenshots**
![capture d'écran_2410](https://user-images.githubusercontent.com/13449658/75681292-96e8ab80-5c93-11ea-828d-89e95dac2ce5.png)

![capture d'écran_2409](https://user-images.githubusercontent.com/13449658/75681301-9e0fb980-5c93-11ea-8116-21ecaa9241b3.png)

It was ok in legacy

![capture d'écran_2411](https://user-images.githubusercontent.com/13449658/75681324-a831b800-5c93-11ea-882f-b80a83eb68f5.png)

#### Additional information

* PrestaShop version: 1.7.7.x

**Comment by Progi1984** [comment]
Fixed by #17975
