### ISSUE TITLE
Referrer doesn't recognize the data mining for statistics module

### ISSUE THREAD

**Issue by yourizuring** [PrestaShop/PrestaShop#17922]
#### Describe the bug

A clear and concise description of what went wrong.
When looking in the referrers section, one of the boxes say 'The module 'Data mining for statistics' must be activated and configurated in order to have all the statistics', while the Data mining for statistics module is already configured.
#### Expected behavior

Explain what you expected to happen instead.
The text in the box should be replaced with something else by now.
#### Steps to Reproduce

1. Go to Traffic & SEO
2. Click on 'Referrers'
3. Scroll down a bit to the box without a title.
4. The box says 'The module 'Data mining for statistics' must be activated and configurated in order to have all the statistics'.
5. Go to 'Module Manager'
6. Search for the Data mining for statistics module'
7. If it's already enabled, configure it.
8. Go back to Traffic & SEO and click on the 'Referrers'
9. Scroll down a bit to the box
10. It still says 'The module 'Data mining for statistics' must be activated and configurated in order to have all the statistics'

**Screenshots**
![image](https://user-images.githubusercontent.com/47860706/75687178-b08ef080-5c9d-11ea-9f16-a0d2c5bb4883.png)
![image](https://user-images.githubusercontent.com/47860706/75687243-ca303800-5c9d-11ea-8cfa-89de547266ce.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: Not specified.

**Comment by khouloudbelguith** [comment]
Hi @yourizuring,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

The Referrers page is removed from 8.0.0 thanks to @Progi1984 
https://github.com/PrestaShop/PrestaShop/pull/27098
I will close this issue.

Thanks!
