### ISSUE TITLE
In RTL I have to click 3 times on the checkbox to select the product

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17924]
#### Describe the bug

In RTL I have to click 3 times on the checkbox to select the product to cancel, to refund or to return

#### Expected behavior

It should work when I check the box the first time as in legacy

#### Steps to Reproduce

1. Install Arabic or another RTL language
2. Choose arabic as language in your employee profile
1. Go to orders > orders (migrated page)
2. Click to view an order in "waiting payment" status
3. Click on "Cancel products"
4. Check the box
5. Nothing happens

**Please note, there are the same checkboxes and the same issue with standard refund and return products features**

**Screenshots**

https://drive.google.com/file/d/1dOEesSFOPgfLSKh2wCcfrCF1kH18qpIH/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by weeeeeeeeeeeeeeewewe** [comment]
It works on Persian language.

**Comment by marionf** [comment]
I have the same issue in Persian with 1.7.7.x branch

**Comment by Arman-Hosseini** [comment]
Sorry, I checked it in **1.7.6.x** Branch.

**Comment by tdavidsonas88** [comment]
Not sure how to get these check boxes to appear from the screenshots: 
![image](https://user-images.githubusercontent.com/32385991/76198699-34ddf800-61f7-11ea-98fc-587001e0a32d.png)
 I think I'm missing in order state or something. 

Tried to go for orders with statuses 'Awaiting cash/check/bank' payment but the button from the screenshot did not appear. The closes I've got was `Partial Refund` button but when clicking it no checkboxes appeared like in your screenshot.

**Comment by tdavidsonas88** [comment]
Core team helped me: `Customer Service > Merchandise return: you toggle it on`, it was needed to see the return checkboxes!

**Comment by tdavidsonas88** [comment]
@matks I take this issue, was able to replicate and see that the issue is javascript related when checkboxes are clicked for the first time numbers are not appearing in the checkboxes.

**Comment by Progi1984** [comment]
Fixed by #18054
