### ISSUE TITLE
Button "tranform a guest into a customer" missing on view order page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17934]
### Describe the bug

Button "tranform a guest into a customer" missing on order page

### Steps to Reproduce

1. Go to the FO and make an order as a guest (don't fill password field)
2. Go to the BO and display the order
3. The button "Tranform a guest into a customer" that was on legacy page is missing

**Screenshots**
![capture d'écran_2419](https://user-images.githubusercontent.com/13449658/75763884-462d8d00-5d3d-11ea-87e3-77c63be99eb9.png)

![capture d'écran_2420](https://user-images.githubusercontent.com/13449658/75763903-4d549b00-5d3d-11ea-81dd-6494dbb81a7f.png)

### Expected behavior

![download](https://user-images.githubusercontent.com/43613217/75797773-e8696700-5d75-11ea-85a5-8e26313f001e.png)

The fields "account registered" and "total spent" will be hidden when the customer is a **guest**.
Below the customer name, we will add "Guest" in grey (Open sans semibold 14px  #6C868E)

The feature is available on the customer page. The order is not the place to handle customer management. We shouldn't encourage the merchant to transform Guest to a Customer account by letting a button on the order page.

### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by marionf** [comment]
Ping @MatShir for specs
https://github.com/PrestaShop/prestashop-specs/pull/70

**Comment by Progi1984** [comment]
Fixed by #17985
