### ISSUE TITLE
Strenghten the CI by checking mandatory modules can be installed

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17937]
Our CI just failed because GDPR module cannot be installed on latest versions. Instead of having Puppeeter finds out because GDPR checkbox does not exist, we should check after automatic PS install that mandatory modules are correctly installed.

A 1st basic implementation would be to check `modules/X` folder exists.

@SimonGrn @boubkerbribri can you please tell me what are the mandatory modules to be installed for your tests to run ? I already know about GDPR, what else ? `ps_legalcompliance` ? `ps_checkout` ?

**Comment by boubkerbribri** [comment]
I checked, and for now, we need `GDPR` and `ps_legalcompliance`.
Thanks @matks

**Comment by matks** [comment]
I created a bash script that does the job but I cannot add it in your tests 😢 
```
# Check mandatory modules were installed successfully
mandatory_modules=( ps_legalcompliance psgdpr )
for module in "${mandatory_modules[@]}"
do
	if [ ! -d "modules/$module" ]
    then
      echo "Module $module cannot be found in modules folder"
      exit 1
    fi
done
```

@boubkerbribri As you guys install PS using the graphical interface, in order for this to be run it would need
1. install PS using puppeter to click on buttons in installer
2. check the modules
3. continue other sanity tests

**Comment by marionf** [comment]
Hey @matks @boubkerbribri, I just came across this issue, is it still relevant or can we close it ?

**Comment by matks** [comment]
@marionf We did not observe this issue since a long time so I think we can close it. There is no more value to do it.
