### ISSUE TITLE
Save after adding an attachment in product page gives an error

### ISSUE THREAD

**Issue by JoshaMunnik** [PrestaShop/PrestaShop#17933]
#### Describe the bug

After adding an attachment in the product page, Save (or any of the other buttons that will do a save) will give an error. 

#### Expected behavior

After Save the green "Settings Updated." should popup.

#### Reason

This happens when one or more file attachments have been deleted.

After adding a new attachment, the id of that attachment is used as the value for the checkbox in the new table row. However this is not a valid value for Symfony's ChoiceType ; which expects a checkbox value that is one higher then checkbox value of the previous attachment in the table.

So long no file attachment has been deleted, the id of the attachment will be the same as the checkbox value. Once one or more attachments have been deleted, the id be different.

ChoiceType does not recognize the checkbox value and will throw an exception.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2.27 & 7.2.23

**Comment by khouloudbelguith** [comment]
Hi @JoshaMunnik,

I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1rVUUgxnBXd205se3OVENQ1o0pjBuA107/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JoshaMunnik** [comment]
I'll see if I have time to create a new empty shop. As last test you could try to delete an attachment via the Catalog -> Files section and then try to add another attachment.

**Comment by khouloudbelguith** [comment]
@JoshaMunnik, it is OK
https://drive.google.com/file/d/1dOpBFoaM2W-741RIPBp3NnSts0U42HRk/view
Waiting for your feedback.

**Comment by JoshaMunnik** [comment]
I tried with a new shop and it is indeed working. The checkbox values are the ids of the attachments.

With my shop the checkbox values are indexed numbers from 0 to number of attachments - 1. My shop has about a 1000 attachments, but that shouldn't matter?

Thank you for looking into it; i'll try to figure out why my shop is behaving differently.

**Comment by khouloudbelguith** [comment]
@JoshaMunnik, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by JoshaMunnik** [comment]
I found the error, it turned out I had two entries in ps_attachment with no related entries in ps_attachment_lang.

This causes the choices list to have non unique id_attachment values (2x null); so Symfony switched to using the index instead of the id_attachment value. Which in turn caused an error when trying to save after attaching a new file (since the javascript code created a new table row with a checkbox using the id_attachment of the newly saved file).

Removing these two entries from the database fixed the problem.
