### ISSUE TITLE
Shipping address shouldn't be filled for an order with only virtual products

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17935]
#### Describe the bug

Virtual products are not delivered, so shipping address shouldn't be filled for an order with **only** virtual products

#### Expected behavior

Don't display shipping address

#### Steps to Reproduce

1. Go to the FO and order a virtual product (ex: Illustration vectorielle Renard)
2. Go to the BO and view the order
3. See the shipping address

**Screenshots**

![capture d'écran_2421](https://user-images.githubusercontent.com/13449658/75764772-a96bef00-5d3e-11ea-94fd-040ea74df9b7.png)

![capture d'écran_2422](https://user-images.githubusercontent.com/13449658/75764792-b12b9380-5d3e-11ea-85ab-ebb9ec931d4b.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by MatShir** [comment]
@LouiseBonnard  @TristanLDD 
Do you think we should add a wording if the shipping address is not displayed? or leave it empty?

**Comment by LouiseBonnard** [comment]
When checking out, there is a message to explain the personal address is used for the invoice only:

<img width="736" alt="Capture d’écran 2020-03-06 à 18 24 26" src="https://user-images.githubusercontent.com/32565890/76106815-eef71900-5fd7-11ea-8e39-117d1efbdafb.png">

So I would leave it blank in the Order View page of the back office.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18202
