### ISSUE TITLE
Backoffice unavailable

### ISSUE THREAD

**Issue by yourizuring** [PrestaShop/PrestaShop#17944]
Is this only happening for me or am I the only one who can not access the back office to Prestashop (the 2nd one I made, not the first one)?

![image](https://user-images.githubusercontent.com/47860706/75782921-eeece400-5d5f-11ea-9593-bb19492fa607.png)

**Comment by khouloudbelguith** [comment]
Hi @yourizuring,

After a fresh install, when you click on the "backoffice" link, you will be redirected to the not found page, is it the first click?
Because if you just clicked before, the folder will be automatically renamed to `adminxxx`.
So when you clicked the second time, you will be redirected to a not found page because the admin folder doesn't exist.
Thanks to check and feedback.

**Comment by yourizuring** [comment]
Can you please fix it, because I am actually at work right now while typing
this email, and I have to work on it sooner than later.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op di 3 mrt. 2020 om 15:05 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@yourizuring, could you please check in your Project_Folder, the exact name of your `admin-folder`.
For example, in this case it is `admin-dev`

Thanks!

**Comment by yourizuring** [comment]
I can't connect to the server in FileZilla for some oddly reason

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op di 3 mrt. 2020 om 15:22 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@yourizuring, after solving issues on your server, you need to check the admin folder and feedback.

Thanks!

**Comment by yourizuring** [comment]
What exactly do you mean by that?

Op di 3 mrt. 2020 om 15:38 schreef khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment]
@yourizuring, you need to check the `admin` folder name of your Project.
It is not `admin,` it is renamed automatically after fresh install to `adminxxxx`.

Thanks!

**Comment by didi-2018** [comment]
@yourizuring and please check if you have deleted the folder 'install' after install prestashop. Otherwise you can not access your backoffice ;-)

**Comment by khouloudbelguith** [comment]
@yourizuring, you can follow our official [documentation](http://doc.prestashop.com/display/PS17/Installing+PrestaShop) for mor details.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @yourizuring,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
