### ISSUE TITLE
Stock bug in Prestashop 1.7.6.0

### ISSUE THREAD

**Issue by antonincizek25** [PrestaShop/PrestaShop#17945]
I have Prestashop 1.7.6.0 multistore and has a problem with stocks. 

The problem is following - I have one item out of stock

This item should't buy anybody, but after some time this item without any increasing stock quantity has automatickly rising number in stock from 0 to 1.
So my customers buy a products which I do not have for sale. 
Please help me to solve this issue. I do not use any software for adjusting the stock, or anything like this.

**Comment by khouloudbelguith** [comment]
Hi @antonincizek25,

>has automatickly rising number in stock from 0 to 1

In your Shop group configuration, the `Share available quantities to sell` is enabled or not?
Did you cancel any order recently?

Thanks!

**Comment by antonincizek25** [comment]
No, to share available quantities has been disabled. I haven't canceled any order, because I knew it transfer the stock quantity from the order to stock.

**Comment by khouloudbelguith** [comment]
@antonincizek25,

>has automatickly rising number in stock from 0 to 1

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @antonincizek25,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
