### ISSUE TITLE
can not enable "Memcached via PHP::Memcache PECL" - 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17940]
Hello, 

I can not enable Memcached via PHP with PECL on 1.7.6.3. PECL Memcached is installed on server. But I can not choose it in BO:

![image](https://user-images.githubusercontent.com/44971218/75771192-c2c66880-5d49-11ea-9934-3cd9156811a3.png)

![image](https://user-images.githubusercontent.com/44971218/75771247-e4bfeb00-5d49-11ea-98b0-dfa7b06a1d83.png)

PS 1.7.6.3
PHP 7.2.1
nginx/1.14.0

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I followed those links to install Memcached
https://www.itzgeek.com/how-tos/linux/debian/how-to-install-memcached-on-debian-9.html
https://serversforhackers.com/c/installing-php-7-with-memcached
You need to follow this link: https://www.php.net/manual/en/memcache.installation.php to install Memcached via **PHP::Memcache** not PHP::Memcache**d**.
In your case, Memcached installed via PHP::Memcached not via PHP::Memcache.

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  please look here at you post: https://github.com/PrestaShop/PrestaShop/issues/15681

it is the same after install "memcache**d**" with 'd'

**Comment by khouloudbelguith** [comment]
@didi-2018, In my post, I m selecting the second option, in your screenshot, you need to select the first option is it?

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith  you are right! My hosting provider understoud it false. You can close it. 

SORRY for waisting your time :-(

**Comment by khouloudbelguith** [comment]
@didi-2018, thanks for your feedback.
Fell free to open a new one when needed.

Thanks!
