### ISSUE TITLE
Can't cancel 'Reorder' in the products listing

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17942]
#### Describe the bug
Once you press reorder, you cannot cancel the action unless you move a product.
Not even updating the page.
If you change something and you don't want to save, you can't.

#### Expected behavior
Possibility of cancel / not rearrange list if you unintentionally press the button or do not want modifications.

#### Steps to Reproduce
1. Select a category in the product list
2. Press the Reorder
3. Try to cancel, there is no button or something that can be done to cancel and the save and update button does not work unless you move a product.

**Screenshots**
![reorder](https://user-images.githubusercontent.com/194784/75777681-ab41ac80-5d56-11ea-92d9-53fc52d7c678.gif)

#### Additional information
* PrestaShop version: 1.7.6, 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
I think we should be able to cancel the feature, thanks @davidglezz and @khouloudbelguith. Indeed, there is no button nor action to undo it. Except for the radio button 'Unselect' in the filters dropdown and it does not really allow the users to disable the feature...

Note that it might be done at the same time that PR #17412.
