### ISSUE TITLE
Can't access FO admin after account was transfered guest to customer by the merchant

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17955]
### Describe the bug

After transforming the Guest account to a Customer through the back office, the customer's merchant can't access his account since the password is randomly generated and never transferred to him.

### Expected behavior

After transforming the Guest account to a Customer through the back office, the customer's merchant should be able to access his account.

### Steps to Reproduce

1. Command a product with a Guest account
2. Go to Customer view page or Order view page (1.7.6)
3. Click on "Transform guest account to customer account"
- It sends an email with email and generates a random password
4. A customer receives an email with only his email and no password

![image](https://user-images.githubusercontent.com/43613217/75791915-8f95d080-5d6d-11ea-995e-5d478eea44fb.png)

So the customer can't access his account, except by resetting his password.

**Why?** 
The old template used to send in the password but for security reasons, we have hidden it on the new template design.

### Solution

Add a link to reset the password (the same from password_query template) with a new wording.
![image](https://user-images.githubusercontent.com/43613217/75792573-72153680-5d6e-11ea-9b8e-74764b892a11.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/14414 & https://github.com/PrestaShop/PrestaShop/issues/9650

**Comment by marionf** [comment]
@MatShir 

It's not a regression there was the same issue with old email templates and old PS version

![capture d'écran_2432](https://user-images.githubusercontent.com/13449658/75862319-062ede80-5dff-11ea-8c51-3d2c510259de.png)

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/5889 to hide the password variable from emails.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #18234
