### ISSUE TITLE
The product name in the cart isn't changed according to the selected language

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17958]
#### Describe the bug

The product name in the cart isn't changed according to the selected language

#### Expected behavior

The product name in the cart changes accordingly to the selected language

#### Steps to Reproduce

1. Go to international > localization > add a second language (ex: EN)
2. Go to catalog > products > edit a product (ex: mug the best is yet to come)
3. Enter a different product name in each languages
4. Go to orders > orders > add new order
5. Select a customer
6. Add the product "mug the best is yet to come" to the cart
7. Select english language
8. The product name is still in FR instead of EN

**Screenshots**
https://drive.google.com/file/d/1gIBfRjlptHgXfLf69wk60GOD8K1iih_g/view?usp=sharing

![capture d'écran_2429](https://user-images.githubusercontent.com/13449658/75797534-9b859080-5d75-11ea-9497-03193223debd.png)

![capture d'écran_2430](https://user-images.githubusercontent.com/13449658/75797542-9de7ea80-5d75-11ea-849a-613fddcbfc56.png)

![capture d'écran_2431](https://user-images.githubusercontent.com/13449658/75797550-a0e2db00-5d75-11ea-8b15-8a798aa6d6a5.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by Arman-Hosseini** [comment]
Assign this to me.

**Comment by jolelievre** [comment]
Sorry @Arman-Hosseini I didn't see your message, I assigned you to this issue ;)

**Comment by jolelievre** [comment]
Hi @Arman-Hosseini just to know, did you have time or this issue?
If not, no worries I can take your place

**Comment by Arman-Hosseini** [comment]
Hi @jolelievre, I'm involved in family problems and unfortunately my grandfather was infected with the COVID-19 virus.
Can you also send your email? I want to talk about working in PrestaShop.
Thank you for taking my place.

**Comment by jolelievre** [comment]
Ho @Arman-Hosseini I'm sorry to hear that.. I hope he gets well soon.
No worries for the issue I take over.

**Comment by Progi1984** [comment]
Fixed by #18348
