### ISSUE TITLE
Can edit product with 0 quantity in the Order page 2/2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17967]
### Expected Behavior 

I shouldn't be allowed to save if I edit a quantity to 0.

### Actual Behavior

I can save a product modification if I edit a quantity to 0.

### Steps to reproduce it

**Edit behavior** as the same issue
1. Go to BO > orders > orders > View an order
2. Click on Edit a product
3. Select a product and change the quantity for 0
4. The product list displays the product with the quantity for 0 and a Total of 0

![image](https://user-images.githubusercontent.com/43613217/75873566-6712e280-5e10-11ea-8c73-72f5d6c899ed.png)

Dependant of #17963
I shouldn't be able to add a product with 0 quantity to the order 1/2 

_Originally posted by @MatShir in https://github.com/PrestaShop/PrestaShop/issues/17963#issuecomment-594462417_

**Comment by jolelievre** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18168
