### ISSUE TITLE
Mail service is not working 

### ISSUE THREAD

**Issue by jitendwi** [PrestaShop/PrestaShop#17966]
#### Describe the bug

PHP Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in classes/mail.php

#### Expected behavior

It should be successfully sending mail from Email testing area. As i created testing php mail function in root folder of website and it is working proper but from Prestashop then showing error please check Configuration.

#### Steps to Reproduce

1. Go to 'Dashboard - Email'
2. Click on 'Testing Email Configuration'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1

**Comment by jitendwi** [comment]
![E-mail • Zirkart](https://user-images.githubusercontent.com/61782797/75872291-e49c1a00-5e33-11ea-8e92-d083b3da2985.jpg)
![error_log - cPanel File Manager v3](https://user-images.githubusercontent.com/61782797/75872599-799f1300-5e34-11ea-8a40-396c7ff9cc66.jpg)

**Comment by jitendwi** [comment]
![error_log - cPanel File Manager v3](https://user-images.githubusercontent.com/61782797/75872630-8885c580-5e34-11ea-92e1-ac857df69fc0.jpg)

**Comment by khouloudbelguith** [comment]
Hi @jitendwi,

>PHP Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in classes/mail.php

You should install & enable the intl extension on your server.
![image](https://user-images.githubusercontent.com/16067358/67494320-4de77180-f679-11e9-8f6b-9c5900ba7978.png)
About the mail configuration, here's an example used in the Dockerfile to fix sending emails
https://github.com/PrestaShop/PrestaShop/pull/17824/files

Thanks to install it & feedback.

**Comment by jitendwi** [comment]
Hi ,
          Please check as i have taken screenshot of my PHP info. Please suggest if anything is missing.
![phpinfo  ](https://user-images.githubusercontent.com/61782797/75873707-64c37f00-5e36-11ea-885f-1a740a64a578.jpg)

**Comment by khouloudbelguith** [comment]
@jitendwi, could you please follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
Or simply download this file
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4280558/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by jitendwi** [comment]
As i enabled all Extensions and Modules but situation is same if you need to access of my website then i can provide you .

**Comment by khouloudbelguith** [comment]
@jitendwi, this error `"PHP Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in classes/mail.php"` is always displayed?

Or just the test mail is not working?

Thanks!

**Comment by jitendwi** [comment]
yes test mail is not working and confirmation mail also not working for example if any order or registration or confirmation mail should send to customer and admin but it is not working

**Comment by khouloudbelguith** [comment]
@jitendwi, Use PHP's mail() function. This option is recommended by default. In the event that this does not work, then use the SMPT option below.

If it is not working, it is a server issue not a PrestaShop issue.
https://drive.google.com/file/d/1U92WDm24-uyEW-zElBA8SFy_NhuSClmr/view

Thanks!

**Comment by jitendwi** [comment]
As i tried already it php mail function and it is proper working .

**Comment by khouloudbelguith** [comment]
@jitendwi, have you tried with your host?

Thanks to check with them & feedback.

**Comment by jitendwi** [comment]
https://zirkart.com/testmail.php

**Comment by khouloudbelguith** [comment]
@jitendwi, I have 404 not found
![image](https://user-images.githubusercontent.com/16067358/75902459-51b5ac80-5e40-11ea-85a7-5f6dd46634c2.png)

Thanks!

**Comment by jitendwi** [comment]
Please check now again because it was mailtest so i rename it . now it is https://zirkart.com/testmail.php

**Comment by jitendwi** [comment]
if you can give mail address then i an put your email address

**Comment by jitendwi** [comment]
![My subject -email](https://user-images.githubusercontent.com/61782797/75911636-dc64ce80-5e75-11ea-870f-9122d0d9591c.jpg)
![testmail php - cPanel File Manager v3](https://user-images.githubusercontent.com/61782797/75911668-ea1a5400-5e75-11ea-8e59-7b672b1a498c.jpg)

**Comment by jitendwi** [comment]
Please check above as it is working in core Php mail function

**Comment by khouloudbelguith** [comment]
@jitendwi, My address mail: khouloud.belguith@prestashop.com
If the function mail() is disabled, it will display under `disable_functions` list.
If you use email account from your hosting? is it ok?
have you tried with SMTP method?

Thanks!

**Comment by jitendwi** [comment]
mail function is working proper as i got 3 email . i think you used the above url.

**Comment by jitendwi** [comment]
i got 5 mails

**Comment by jitendwi** [comment]
It is definitely bug in Prestashop

**Comment by khouloudbelguith** [comment]
@jitendwi,

>It is definitely a bug in Prestashop

No, it is not a PrestaShop bug.
In a server well configured, the sent email test is well working as recorded in my previous video.
Also, I sent you a fix example: https://github.com/PrestaShop/PrestaShop/pull/17824/files in a Dockerfile was done to fix a server issue to get emails.
have you tried with the SMTP method?

Thanks!

**Comment by jitendwi** [comment]
Actually i was activated smtp also but same error throwing . Please check configuration. if you need then i can send access of backoffice of website and Cpanel also.

**Comment by khouloudbelguith** [comment]
@jitendwi, The information for these fields should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.
Your web host can tell you whether or not your username is mandatory, as well as the password information, and the encryption to use.

In my case, I tried with two different servers & two different hosts and they are well working.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by jitendwi** [comment]
I checked root folder - there is docker file is available. Most imp.:- Website was migrated from one host to another
