### ISSUE TITLE
I shouldn't be able to add a product with 0 quantity to the order 1/2

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17963]
#### Describe the bug

I can add a product with 0 quantity to the order & another product is added

#### Expected behavior

I shouldn't be able to add a product with 0 quantity to the order

#### Steps to Reproduce

1. Go to BO > orders > orders > View an order
2. Click on Add a product
3. Select a product and change the quantity for 0
4. Another product is added to the order with quantity 1
5. If I refresh the page, it disappears

**Screenshots**

https://drive.google.com/file/d/117N5MEnHc9KbgicqnSJ0QtSOZVY9mI1D/view?usp=sharing

Legacy behavior: 

![capture d'écran_2433](https://user-images.githubusercontent.com/13449658/75864515-6bd09a00-5e02-11ea-8680-e00b6572a1e5.png)

Dependant of #17967
Can edit product with 0 quantity in the Order page 2/2 

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by marionf** [comment]
@MatShir Need some specs / mock-up

**Comment by MatShir** [comment]
**Edit behavior** as the same issue
1. Go to BO > orders > orders > View an order
2. Click on Edit a product
3. Select a product and change the quantity for 0
4. The product list displays the product with the quantity for 0 and a Total of 0

![image](https://user-images.githubusercontent.com/43613217/75873566-6712e280-5e10-11ea-8c73-72f5d6c899ed.png)

**Comment by colinegin** [comment]
I reproduce it with pack products. But I notice this product is removed when you reload the page.
Do you have this also @marionf ?

**Comment by marionf** [comment]
> 5. If I refresh the page, it disappears

@colinegin Yes

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/18168
