### ISSUE TITLE
Cannot apply discount in order PS 1.7.6.2 

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#17962]
Try to add discount in order with reduction "amount"

got this error: An error occurred during the OrderCartRule creation

1. Go to order
2. Click on add a new discount
3. Insert discout name: Discout
4. Set discount as amount
5. set amount

click add

<img width="404" alt="Schermata 2020-03-04 alle 10 18 11" src="https://user-images.githubusercontent.com/5024055/75863924-87877080-5e01-11ea-9d23-7d566a4462ae.png">

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

I did not manage to reproduce the issue with PS1.7.6.3.
https://drive.google.com/file/d/1pb2vNxlSx_Ii4vf58dVhpnhzzVDYoZIe/view
What is the exact status of your order?
What is the exact value amount? is it a decimal?

Thanks!

**Comment by Gipielle** [comment]
![cartrule](https://user-images.githubusercontent.com/53569015/75867822-74779f00-5e07-11ea-8198-5ee1cb416893.jpg)

**Comment by Gipielle** [comment]
Update to 1.7.6.3 same error

**Comment by khouloudbelguith** [comment]
@Gipielle, you have a duplicate data in your database table ps_cart_rule_lang.
Did you delete any data from the database manually?

Thanks!

**Comment by Betafer** [comment]
No

**Comment by Gipielle** [comment]
> @Gipielle, you have a duplicate data in your database table ps_cart_rule_lang.
> Did you delete any data from the database manually?
> 
> Thanks!

no

**Comment by khouloudbelguith** [comment]
@Betafer, What is the exact status of your order?
What is the exact value amount? is it a decimal?
Is there any exception displayed when debug mode enabled?

Thanks!

**Comment by Gipielle** [comment]
Status of order awaiting bankwire payment
Total order amount 1.424,00 €

**Comment by khouloudbelguith** [comment]
@Gipielle, what is the exact structure of your table ps_cart_rule_lang?
![image](https://user-images.githubusercontent.com/16067358/75868896-0c29bd00-5e09-11ea-9ed0-96b094db2d4a.png)

Thanks!

**Comment by Betafer** [comment]
<img width="927" alt="Schermata 2020-03-04 alle 11 18 31" src="https://user-images.githubusercontent.com/5024055/75869488-ea7d0580-5e09-11ea-8559-265868f4321e.png">

I'm working with 2 computer ...

**Comment by khouloudbelguith** [comment]
@Betafer, https://github.com/PrestaShop/PrestaShop/issues/17962#issuecomment-594432580

Thanks!

**Comment by Betafer** [comment]
Table ps_cart_rule_lang with more data than  cart_rule 

Solved. 
Thanks

**Comment by khouloudbelguith** [comment]
@Betafer, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
