### ISSUE TITLE
[EPIC] - Shouldn't allow to add/edit the product with 0 quantity.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17968]
## User Story

It shouldn't be allowed to add the product to my order or edit a product with 0 quantity.

## Specs

Disable the save button if the value is 0 in quantity.
A product can't be displayed if the quantity is 0. 

## Issues to fix

- [x] #17963 - I shouldn't be able to add/edit a product with 0 quantity to the order 1/2
- [x] #17967 - Can edit product with 0 quantity in the Order page 2/2

**Comment by arouiadib** [comment]
Hello @MatShir ,
Thank you very much.
While working on this, I have a question. Don't we need to extend this behaviour to minimal allowed quantity for product/combintation and not only check against quantity = 0?
Wdyt?

**Comment by MatShir** [comment]
To be confirmed, but there is already a minimum check, you can add negative
values. It just makes weird behavior on the list when the quantity is equal
to 0.
