### ISSUE TITLE
Remove useless currency wording/exception

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#17969]
#### Is your feature request related to a problem?

The currency feature has evolved along the developments and some error messages are not useful any more:
`Cannot find a real currency matching this couple of ISO code and numeric ISO code`
Along with the exception code `CurrencyConstraintException::ISO_CODES_MISMATCH`

Because:
- for official currencies the numeric is code is now automatically filled
- for unofficial ones the numeric iso code is now null

#### Describe the solution you'd like

Remove all the code related to this removed feature:
- in controller for error messages
- in the exception for useless code
- in the behat context for unused statement
- DON'T FORGET to clean the default catalog as well and clean this useless message

**Comment by jolelievre** [comment]
Ping @LouiseBonnard

**Comment by LouiseBonnard** [comment]
Since this feature evolved a lot, let's make a full check after the merge of PR #17385 to spot, perhaps, other useless wordings.

**Comment by LouiseBonnard** [comment]
@jolelievre, PR #17385 has been merged! We can look for useless wording now. ;-)

**Comment by Progi1984** [comment]
Fixed by #18652
