### ISSUE TITLE
[ORDER PAGE] Check all legacy links are correctly redirected to new page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17970]
We need to go through all PrestaShop code looking for `AdminOrders` links and make sure they are correctly redirected to new migrate Orders pages.

This can be done by 3 ways:
- using redirection mechanism such as `getAdminLink()` abilities
- modifying the link (especially for hardcoded appended links in Javascript)
- adding `_legacy_link` tags on new routes

List of bad links fixed:
- link to order on timeline in Customer Service
- link to order from "Customers > Outstanding" page (only visible in B2B mode)
- link to order from "Customers > Merchandise returns" page
- search results page (example `/admin-dev/index.php?controller=AdminSearch&token=XXX`)

Links that are correctly redirected from legacy page to symfony page:
- dashboard and tab links
- search redirects (not search page)
- notification about new order
- customer page

**Comment by matks** [comment]
To be done after https://github.com/PrestaShop/PrestaShop/pull/17959 is merged

**Comment by Progi1984** [comment]
Fixed by #17959
