### ISSUE TITLE
The stock is not correctly recalculated after editing product quantity in the order

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17971]
#### Describe the bug

The stock is not correctly recalculated after editing product quantity in the order

#### Expected behavior

Display the correct quantity in stock after editing the product quantity

#### Steps to Reproduce

1. Go to BO > orders > orders > view
2. Click on edit to change a product quantity
3. Increase or decrease the product quantity for +1 or -1
4. See the quantity in stock is increased of +2 or decreased of -2
5. If you save, the quantity in stock is correct

**Screenshots**
https://drive.google.com/file/d/18Vqi8NzBhrFfFjgnKvQ_mK0JFWtKaKiu/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by marionf** [comment]
@MatShir FYI

**Comment by Progi1984** [comment]
Fixed by #18061
