### ISSUE TITLE
New invoice not displayed in documents tab before reloading the page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17977]
#### Describe the bug

If you add a new product and choose to create a new invoice, the invoice is not displayed in documents tab before reloading the page

#### Expected behavior

The invoice should be displayed in the documents tab without reloading the page

#### Steps to Reproduce

1. Go to BO > orders > orders > View order
2. Click on add a product
3. Select a product and select "Create a new invoice"
4. Click on add
5. The new invoice isn't displayed in the documents tab, you have to reload the page to see it

#### Additional information

https://drive.google.com/file/d/1S4yKh_4l7ddrWvyHmBIonMx4_kyydWRP/view?usp=sharing

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #18196
