### ISSUE TITLE
Add product to Order - Difference between Products price and Total price

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#17976]
#### Describe the bug

The products price is incorrect when adding a product to an existing order

#### Expected behavior

A correct price with 2 decimals rounded

#### Steps to Reproduce

1. Create an order
2. Go to 'Admin > Orders'
2. Edit the order created
3. Add a product
4. See that there is a difference of 0.01 between Products price and Total Price

**Screenshots**

https://drive.google.com/file/d/1iAXV8yAC3HadGs0MO36UQ63xmAOM33u2/view

#### Additional information

* PrestaShop version: 1.7.7.0

**Comment by colinegin** [comment]
@sarahdib this issue is supposed to be fixed thanks to the work on PR #18617 , could you test it when you have some time ? Thanks !

**Comment by sarahdib** [comment]
@colinegin It's fixed :)
<img width="696" alt="Capture d’écran 2020-04-27 à 11 38 23" src="https://user-images.githubusercontent.com/3034677/80357705-a8a59400-887b-11ea-9f5f-29cda11288e9.png">

**Comment by colinegin** [comment]
Amazing !! Thanks ;)
