### ISSUE TITLE
Editing an address in the order should create a new address

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17978]
#### Describe the bug

If you change an address (billing or shipping address) in the order, the new address will be updated in all customer orders.

#### Why 

The order page does not dissociate between modifying an erroneous address and entering a new address.

#### Expected behavior

Editing an address in the order should:
- create a new address 
- it only updates the address of the current order

#### Steps to Reproduce

1. Go to BO > orders > orders > View order
2. Click on edit address
3. Change the address and save
4. The address has been edited and changed for both billing and delivery

**Screenshots**

https://drive.google.com/file/d/1Rx7oDD_8YLr0cMDwLDGm9-qw8aTFfN6Y/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by marionf** [comment]
@MatShir FYI

**Comment by Progi1984** [comment]
Fixed by #18124
