### ISSUE TITLE
Prestashop 1.7.5.0 not sending order confirmation email with ps_emailalerts 

### ISSUE THREAD

**Issue by gacalixto** [PrestaShop/PrestaShop#17984]
Hello!
When a customer places an order on my shop , neither him or the shop receives an order confirmation email.
Another email alerts like the "out of stock" one are sent correctly.

* PrestaShop version: 1.7.5.0
* PHP version: 7.2.24

**Comment by khouloudbelguith** [comment]
Hi @gacalixto,

Thanks for your report.
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email.
Thanks to check & feedback.

**Comment by gacalixto** [comment]
Hi @khouloudbelguith, the test email is sent without problems.
I deactivated the ps_emailalerts module and kept placing new orders, but for some reason the order confirmation emails are still being sent to the customer emails.

**Comment by gacalixto** [comment]
also, a correction to my original issue, the "new_order" email is never being sent, only the "order_conf" one

**Comment by khouloudbelguith** [comment]
@gacalixto,

The "order confirmation emails" is not related to the `ps_emailalert`.
The Order confirmation email is sent when this option "Send an email to the customer when his/her order status has changed." is selected.
![image](https://user-images.githubusercontent.com/16067358/75985468-aa428380-5eec-11ea-8cf5-7510e3c65a3f.png)

The ps_emailalerts module is enabled

A customer receives those emails
![image](https://user-images.githubusercontent.com/16067358/75985546-c8a87f00-5eec-11ea-9ae3-153b7edddd28.png)
An employee receives those emails
![image](https://user-images.githubusercontent.com/16067358/75985656-fe4d6800-5eec-11ea-869f-40cabbf3720f.png)

Thanks to check & feedback.

**Comment by gacalixto** [comment]
Now i get it, i misunderstood the emails structure, sorry for that.
But how and when can the vendor get an email when the order is placed? Is it only sent when the payment is approved?

**Comment by khouloudbelguith** [comment]
@gacalixto, The employee can receive a new order email when:
1. installing the `ps_emailalert` module
2. New order option is enabled
![image](https://user-images.githubusercontent.com/16067358/75988073-525a4b80-5ef1-11ea-8364-57e802d61298.png)
3. The email address of the employee is added in the "E-mail addresses" section
![image](https://user-images.githubusercontent.com/16067358/75988171-761d9180-5ef1-11ea-9eab-2a19d649321d.png)

Thanks!

**Comment by gacalixto** [comment]
I already set that up, as you can see on my image attachment.
![Screenshot_20200305_110234](https://user-images.githubusercontent.com/29805452/75988812-ed8ef900-5ed0-11ea-89a6-bcf615d9045d.png)
The vendors are, still, not receiving any emails.
Also, for some reason, the "Email addresses" field is being reset for some reason anytime that i go to another page and come back to the module page

**Comment by khouloudbelguith** [comment]
@gacalixto, what is the exact version of the `ps_emailalert` module did you use?

Thanks!

**Comment by gacalixto** [comment]
i'm using the `ps_emailalert` v2.1.1

**Comment by khouloudbelguith** [comment]
@gacalixto, could you please try to re-install the `ps_emailalert` module with removing the folder, clear cache, check and feedback.
Thanks!

**Comment by gacalixto** [comment]
Yesterday i unistalled it and reinstalled it, but today the module is not uninstalling.
`[Thu Mar 05 11:40:16.769878 2020] [fcgid:warn] [pid 6259] [client 177.76.171.177:39996] mod_fcgid: stderr: PHP Warning:  include_once(/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:16.769910 2020] [fcgid:warn] [pid 6259] [client 177.76.171.177:39996] mod_fcgid: stderr: PHP Warning:  include_once(): Failed opening '/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php' for inclusion (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:20.531567 2020] [fcgid:warn] [pid 5479] [client 177.76.171.177:53826] mod_fcgid: stderr: PHP Warning:  include_once(/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=ej9gyVtfKA3UHPFWid7i9ECALBOsGWK0jJMbG3Jw_l0
[Thu Mar 05 11:40:20.531598 2020] [fcgid:warn] [pid 5479] [client 177.76.171.177:53826] mod_fcgid: stderr: PHP Warning:  include_once(): Failed opening '/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php' for inclusion (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=ej9gyVtfKA3UHPFWid7i9ECALBOsGWK0jJMbG3Jw_l0
[Thu Mar 05 11:40:21.324011 2020] [fcgid:warn] [pid 6322] [client 177.76.171.177:40000] mod_fcgid: stderr: PHP Warning:  include_once(/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.324042 2020] [fcgid:warn] [pid 6322] [client 177.76.171.177:40000] mod_fcgid: stderr: PHP Warning:  include_once(): Failed opening '/var/www/clients/client20/web42/web/modules/ps_emailalerts/MailAlert.php' for inclusion (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/modules/ps_emailalerts/ps_emailalerts.php on line 31, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.324050 2020] [fcgid:warn] [pid 6322] [client 177.76.171.177:40000] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.324066 2020] [fcgid:warn] [pid 6322] [client 177.76.171.177:40000] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.324072 2020] [fcgid:warn] [pid 6322] [client 177.76.171.177:40000] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php' (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903406 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getSecurity_Authentication_Listener_Anonymous_MainService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903432 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getSecurity_Authentication_Listener_Anonymous_MainService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903436 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getSecurity_Authentication_Listener_Anonymous_MainService.php' (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903442 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903453 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Warning:  require(/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
[Thu Mar 05 11:40:21.903457 2020] [fcgid:warn] [pid 3565] [client 177.76.171.177:39998] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/getPrestashop_AccessDenied_ListenerService.php' (include_path='/var/www/clients/client20/web42/web/vendor/pear/pear_exception:/var/www/clients/client20/web42/web/vendor/pear/console_getopt:/var/www/clients/client20/web42/web/vendor/pear/pear-core-minimal/src:/var/www/clients/client20/web42/web/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/clients/client20/web42/web/var/cache/prod/ContainerAgpxnti/appProdProjectContainer.php on line 1148, referer: https://lincevet.com.br/admin298biw6xn/index.php/improve/modules/manage?_token=uUaPBN1_pYIHyOdvtwiNrfPJyaU3ifOk5KY6QW4IjTg
`

this error is showing on my error log.

**Comment by khouloudbelguith** [comment]
@gacalixto,
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by gacalixto** [comment]
i deleted them and it still doesn't let me uninstall the mail alerts module.

**Comment by khouloudbelguith** [comment]
@gacalixto, it could be a permission issue on your server.
Thanks to check and feedback.

**Comment by gacalixto** [comment]
I changed permissions and it still doesn't let me unintsall it. Even when i choose not to delete module folders.

**Comment by gacalixto** [comment]
@khouloudbelguith 
I unistalled it and cleared my cache, i believe the module was corrupted in some way, now i re-install it ?

**Comment by khouloudbelguith** [comment]
@gacalixto, yes!
Remove the module folder if it still exists.
Try to install it from the Module Catalog page.

Thanks!

**Comment by gacalixto** [comment]
After reinstalling it, it worked with the pay by check and "wire transfer" payment methods when placing an order.
But our shop uses a third party pament module called "Mercado Pago" that's very useful for the Brazillian market(our case), ehn using this module as payment method, the `new_order` email is not sent

**Comment by khouloudbelguith** [comment]
Hi @,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
@gacalixto, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment]
Hi @gacalixto,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
