### ISSUE TITLE
PrettyCI is shutting down

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17983]
This year we will have to change PrettyCI for something else.

https://prettyci.com/goodbye

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers

Thanks!

**Comment by matks** [comment]
Already done in https://github.com/PrestaShop/PrestaShop/issues/17744

**Comment by khouloudbelguith** [comment]
@matks, can we close this issue as a duplicate?

Thanks!

**Comment by matks** [comment]
I think yes :)

**Comment by khouloudbelguith** [comment]
Duplicate of #17744

**Comment by davidglezz** [comment]
Sorry for these useless issues.
Now I see: https://github.com/PrestaShop/PrestaShop/issues/17744#issuecomment-593347233
