### ISSUE TITLE
Optimize the 1.7.7 translation catalog

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17993]
### Admin.Advparameters.Feature

- [x] ‘MPN’ to be localized in **Admin.Catalog.Feature** instead
cf. https://crowdin.com/translate/prestashop-official/35796/en-en

### Admin.Advparameters.Notification

- [x] ‘Are you sure that you would like to delete this entity: ‘ to be changed into **Are you sure you want to delete this entity:** without the extra space at the end
cf. https://crowdin.com/translate/prestashop-official/35798/en-en#5831278

- [x] ‘Advanced stock management has incorrect value. Not set for product %name% ‘ to be written without the extra space at the end

- [x] ‘Advanced stock management is not enabled, cannot enable on product %name% ‘ to be written without the extra space at the end

- [x] ‘Advanced stock management is not enabled, warehouse not set on product %name% ‘ to be written without the extra space at the end

- [x] ‘Warehouse did not exist, cannot set on product  %name% ‘ to be written without the extra space at the end

- [x] ‘Incorrect value for "Depends on stock" for product %name% ‘ to be written without the extra space at the end

- [x] ‘Advanced stock management is not enabled, cannot set "Depends on stock" for product %name% ‘ to be written without the extra space at the end

### Admin.Catalog.Feature

- [x] ‘MPN’ is written three times, is there any reason to have so many duplicates?
cf. https://crowdin.com/translate/prestashop-official/35748/en-en#q=mpn

- [x] ‘Payment: ‘ to be written without the extra space at the end

- [x] ‘Message to: ‘ to be written without the extra space at the end

- [x] ‘Product: ‘ to be written without the extra space at the end

### Admin.Catalog.Notification

- [x] ‘The display of your brands is enabled on your store. Go to %sShop Parameters > General to edit settings.%s’ needs its last variable changed into **The display of your brands is enabled on your store. Go to %sShop Parameters > General%s to edit settings.**

- [x] ‘The display of your brands is disabled on your store. Go to %sShop Parameters > General to edit settings.%s’ needs its last variable changed into **The display of your brands is disabled on your store. Go to %sShop Parameters > General%s to edit settings.**

- [x] ‘The display of your suppliers is enabled on your store. Go to %sShop Parameters > General to edit settings%s.’ needs its last variable changed into **The display of your suppliers is enabled on your store. Go to %sShop Parameters > General%s to edit settings.**

- [x] ‘The display of your suppliers is disabled on your store. Go to %sShop Parameters > General to edit settings%s.’ needs its last variable changed into **The display of your suppliers is disabled on your store. Go to %sShop Parameters > General%s to edit settings.**

- [x] ‘Selected products were successfully cancelled.’ to be changed into **Selected products were successfully canceled.**

### Admin.International.Feature

Most strings about the 'Currencies' page, mentioned here, will be changed with PR #17385.

### Admin.Design.Feature

- [x] ‘Translate emails’ to be localized in **Admin.Actions** instead

### Admin.International.Notification

- [x] ‘Oops... it looks like this ISO code already exists. If you are: <ul><li>trying to create an alternative currency, you must type a different ISO code</li><li>trying to modify the currency with ISO code %isoCode%, make sure you did not check the creation box</li></ul>’ to be written with placeholders instead?
cf. https://crowdin.com/translate/prestashop-official/35838/en-en#5833736

### Admin.Navigation.Footer

- [x] ‘Load time: ‘ to be written without the extra space at the end

### Admin.Notifications.Error

- [x] ‘Incorrect value for "Depends on stock" for product %name% ‘ to be written without the extra space at the end

- [x] ‘Selected language cannot be used because is disabled’ to be changed into **Selected language cannot be used because it is disabled**

- [x] ‘This field is invalid, it must contain a positive integer’ : positive integer ?

- [x] ‘Cannot translate emails body contents’ to be changed into **Cannot translate emails body content**

### Admin.Orderscustomers.Feature

- [x] ‘Include amount of initial voucher: ‘ to be written without the extra space at the end

- [x] ‘Exclude amount of initial voucher: ‘ to be written without the extra space at the end

- [x] ‘Amount of your choice: ‘ to be written without the extra space at the end

- [x] ‘This order has been partially paid by voucher. Choose the amount you want to refund: ‘ to be written without the extra space at the end

- [x] ‘Product(s) price: ‘ to be written without the extra space at the end

- [x] ‘Product(s) price, excluding amount of initial voucher: ‘ to be written without the extra space at the end

### Admin.Orderscustomers.Notification

- [x] ‘This product is out of stock: ‘ to be written without the extra space at the end

- [x] ‘A return product was successfully created.’ to be changed into **The product was successfully returned.**

### Admin.Shopparameters.Help

- [x] ‘We are thrilled to introduce you to the fuzzy search, one of the new features from 1.7.7! Please note that it is still in beta version, so feel free to share improvement ideas on GitHub to have it enhanced.’ to be localized in **Admin.Shopparameters.Notification** instead

- [x] ‘Disabling this option will require exact spelling for the search to match result.’ to be changed into **Disabling this option will require exact spelling for the search to match results.**

- [x] ‘Only words this maximum size or smaller will be used during the search.’ to be changed into **Only words fewer or equal to this maximum length will be searched.**

- [x] ‘This parameter will only be used if fuzzy search is activated, the lower the value, the more tolerant your research will be.’ to be changed into **This parameter will only be used if the fuzzy search is activated: the lower the value, the more tolerant your search will be.**

- [x] ‘Allow the customer to ship orders to multiple addresses. This option will convert the customer's cart into one or more orders .’ to be changed into **Allow the customer to ship orders to multiple addresses. This option will convert the customer's cart into one or more orders.**

- [x] ‘Allows you to delay shipping at your customers' request .’ to be changed into **It allows you to delay shipping if your customers request it.**

- [x] ‘Maximum approximate strings allowed by fuzzy search’ to be changed into **Maximum approximate words allowed by fuzzy search**

### Admin.Actions

- [x] ‘Search Reference’ to be changed into **Search reference**

- [x] ‘Search Customer’ to be changed into **Search customer**

- [x] ‘Search Total’ to be changed into **Search total**

- [x] ‘Search Payment’ to be changed into **Search payment**

- [x] ‘Search Company’ to be changed into **Search company**

- [x] ‘Edit address’ to be changed into **Edit existing address**

- [x] ‘Change address’ to be changed into **Select another address**

### Admin.Global

- [x] ‘First name ‘ to be written without the extra space at the end

- [x] ‘Package Item’ to be changed into **Package item**

- [x] ‘Card number’ to be localized in **Admin.Orderscustomers.Feature** instead

### Modules.Blockreassurance.Admin

- [x] ‘Choose SVG for best customization. Other accepted file formats: jpg, png, gif’ must be changed into **Choose SVG for better customization. Other allowed formats are: .gif, .jpg, .png**

### Modules.Livetranslation.Admin

- [x] ‘Live translation cannot be enabled. The English Upside Down language is missing and cannot be installed. Please reset the module to try again. ‘ to be written without the extra space at the end

### Shop.Theme.Catalog

- [x] ‘mpn’ must be changed into **MPN**
cf. https://crowdin.com/translate/prestashop-official/35700/en-en#5823192

- [x] ‘%1$s: ‘ is a mistake / fixed

### Shop.Theme.Checkout

- [x] ‘ (additional cost of %giftcost% %taxlabel%)’ to be written without the extra space at the beginning

## RECENTLY MERGED 1.7.7 WORDINGS TO DELETE BECAUSE MODIFIED

https://github.com/PrestaShop/PrestaShop/pull/17385 in ...Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig

- [x] Reset settings = **Reset** (in **Admin.Actions**)
- [x] Price: %price% (Special discount %discount%) = **%price%** (in **Admin.International.Feature**)
- [x] Reset default settings = **Restore default settings** (in **Admin.International.Feature**)

https://github.com/PrestaShop/PrestaShop/pull/18164 in src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php

- [x] Invalid action: this order already has an invoice. = **Invalid action: this order has already been paid.** (in **Admin.Notifications.Error**)
- [x] Invalid action: this order has no invoice. = **Invalid action: this order has not been paid.** (in **Admin.Notifications.Error**)

_I recommend we wait for the merge, then modify the wordings mentioned here._

**Comment by matks** [comment]
I move this PR back to "In progress" as I see discussions are still going on in https://github.com/PrestaShop/PrestaShop/pull/18201

**Comment by colinegin** [comment]
New catalog extract needed.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18201
