### ISSUE TITLE
Filter in movements and stock does not reset

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18000]
#### Describe the bug

When filters are activated on Movements (or Stock) page, if you change tab to "Stock" (or Movement, you got the idea...), and then go back to "Movements", the filters appears to be reset (at "None", all checkboxes unchecked), but if you add a new filter, it will combine with the older filters.

#### Expected behavior

Filters should either be really reset, or filters should stay displayed.

#### Steps to Reproduce

1. Go to BO > Catalog > Stocks > Movements : All movements are displayed
2. Add Filter, for example "Movement type" set to "Product return" : Data are filtered
3. Go to "Stock" tab, then go back to "Movements" : All movements are displayed, and filters appears to be reset.
4. Add another filter (for example, check "Accessories" category) : Only data with "Accessories" category AND movement type "Product return" are displayed, even if there is no shown filter on movement type.

**Screenshots**

https://drive.google.com/file/d/1Q6UXU9rspcWKQPgaEKEzgZGBJkzwNvam/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7 and 1.7.6.2 at least
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.3 and PS1.7.5.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/27329
