### ISSUE TITLE
Set default country from browser language KO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18008]
#### Describe the bug

When in BO, "Set default country from browser language" is set to Yes, it does not work : On FO, when creating an address, the pre-filled country is the "Default country" set in BO instead of the country of the browser.

#### Steps to Reproduce

1. Go to BO > International > Localization > Configuration
2. Set "Default country" to a country different from your browser language (Spain for example)
3. Set "Set default country from browser language" to Yes
4. Go to FO, create a customer, create an address with the customer : Country is filled with "Spain", it should be filled with the country of the browser

**Screenshots**
Config in BO : 
![set default country KO BO](https://user-images.githubusercontent.com/55688534/76007817-f43c6100-5f0e-11ea-8167-b9e49620c126.png)

Result in FO when creating address with new customer (with browser in French) : 
![set default country KO FO](https://user-images.githubusercontent.com/55688534/76007867-05856d80-5f0f-11ea-9fb7-54d90e4aa66e.png)

#### Additional information

* PrestaShop version: 1.7.6 and 1.7.7 at least
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I have the same issue with PS1.7.5.2 & PS1.7.6.3 & PS1.7.7.x.
Previously reported https://github.com/PrestaShop/PrestaShop/issues/10744

Thanks!

**Comment by Gipielle** [comment]
Same issue in PS 1.7.6.3

**Comment by pdalexis** [comment]
Hi @LouiseBonnard and @khouloudbelguith, I have the same issue with PS 1.7.6.8.

**Comment by bimlas** [comment]
The working principle of automatic country determination is to search for a country with the same ISO code based on the language code of the browser. If the language code set in your browser does not match the ISO code of a country (eg Czech language code `CS`, country ISO code `CZ`), Prestashop will not be able to determine the country. In this case, returns the default country.

1.7.7.x

https://github.com/PrestaShop/PrestaShop/blob/948ecce8461176c507512c977633731bc3550a24/classes/Tools.php#L660-L668

I don't know exactly what the language code of your browser is, but I think the language and country code may be similarly different as in the Czech Republic, so the country definition doesn't work.

There is a bug fix in 1.7.8 (https://github.com/PrestaShop/PrestaShop/pull/17123), but I don't see an explanation for exactly how this fix works. I think the error will still persist, but I can't test it.

**Comment by matks** [comment]
Assigned to @Amoifr
