### ISSUE TITLE
Cannot find translation word in backend of Prestashop

### ISSUE THREAD

**Issue by simontingkamlee** [PrestaShop/PrestaShop#18011]
Hi,
I am doing a bi-lingual site with English and Chinese. On the front end, there is a word "Testamonial" in the testimonial block which I want to translate to Chinese. I cannot find it in the backend under the International --> Translation in the ttcmstestamonial module. I checked the source code and trace it to 

/var/www/html/modules/ttcmstestimonial/views/templates/hook/ttcmstestimonial.tpl. In there, there's the line

<h1 "class=...">{l s='Testimonial' d='Shop.Theme.Catalog'}</h1>
but I cannot find where I can translate "Testimonial' in the back end. Please advise.
![2020-3-6 error](https://user-images.githubusercontent.com/54059552/76064363-75a1fb00-5fc4-11ea-84bb-f060a5cd85f5.png)

Regards,
Simon Lee

**Comment by khouloudbelguith** [comment]
Hi @simontingkamlee,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
