### ISSUE TITLE
Changing the position of the features is not possible when the features are sorted in descending order

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18015]
#### Describe the bug

Changing the position of the features is not possible when the features are sorted in descending order

#### Expected behavior

Features position change must be possible regardless of the order in which the features are sorted

#### Steps to Reproduce

1. Go to BO => catalog => Attributes and Features => Features
2. Sort features in ascending order => the position change button is displayed
3. Now Sort features in descending order
4. The position change button is not displayed

**Screenshots**

**Ascending sort the position button is displayed**
![features position ascending](https://user-images.githubusercontent.com/40635814/76074595-e5e85680-5f9b-11ea-89f2-fae93644b689.png)

**Descending sort the position button is NOT displayed**
![feature position descending](https://user-images.githubusercontent.com/40635814/76074695-0adcc980-5f9c-11ea-8da7-7ef16506b13a.png)

#### Additional information

This behaviour is also present for the attributes

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi,

This issue occurs in all pages
1. Categories page (migrated to Symfony or legacy)
2. Attributes page
3. Features page
4. Pages page
5. Page categories
6. Link widget page
7. Carriers page

Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think? is this normal behavior?

Thanks!

**Comment by colinegin** [comment]
We should review this issue when working on the migration of this page.
Ping @MatShir

**Comment by florine2623** [comment]
This has been fixed here : https://github.com/PrestaShop/PrestaShop/pull/37042
