### ISSUE TITLE
New invoice information block is missing in Order view page

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#18020]
#### Describe the bug

In Order view page when I try to add a product with new invoice, I should see the checkobox "free shipping" according to legacy behavior.
![Screenshot from 2020-03-06 15-07-11](https://user-images.githubusercontent.com/31609858/76086328-91090800-5fbc-11ea-943b-ad988c16a309.png)

#### Expected behavior

The checkbox with "free shipping" checkbox should appear when "create new invoice" is selected.

#### Steps to Reproduce

1. Go to `admin-dev/sell/orders/orders/{orderId}/view
2. Make sure order status is not "delivered" and you can add products.
3. Make sure your order has invoice. (to generate one, click `generate invoice` in Documents tab
4. Click `Add product`, search and select the product.
5. In right side of the screen you should see select box with invoices, select option `create new invoice`
6. The new block 'new invoice information' should appear which should contain a checkbox of "free shipping"

#### Additional information

* PrestaShop version: 1.7.7x
* PHP version: N/A

**Comment by zuk3975** [comment]
being fixed in https://github.com/PrestaShop/PrestaShop/pull/17348

**Comment by Progi1984** [comment]
Fixed by #18544
