### ISSUE TITLE
Best sellers page still displayed in footer FO when deactivated

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18028]
#### Describe the bug

When, in BO, the "Display best sellers" parameter is set to "No", the link to this page is still shown in FO, in the footer, with a 404 error when clicking on it.

#### Expected behavior

The link to this page should not appear when option is set to No.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > General
2. Set "Display best sellers" to "No"
3. Go to FO. In the footer, the "Best sales" link is displayed, and redirect to 404 error

**Screenshots**

https://drive.google.com/file/d/1kAffDdsbctL8LilmMtBpdNcO16myNJdo/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7, 1.7.6.2
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi,

>In the footer, the "Best sales" link is displayed

The Best sales link is added by the Link Widget module
![image](https://user-images.githubusercontent.com/16067358/76098691-35457b80-5fca-11ea-8088-ab97a3027997.png)

Thanks!

**Comment by LouiseBonnard** [comment]
Indeed, these two options should be related to each other. In short: if you disable the 'best sales' page, it should automatically uncheck this option in the Design > Link Widget section of the back office or in the Link List module.

**Comment by matks** [comment]
Pull Request on ps_linklist https://github.com/PrestaShop/ps_linklist/pull/142
