### ISSUE TITLE
ps_emailalerts and ps_emailsubscription have 1.6 template emails inside /mails/en/

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18036]
Hi
I've found a little bug in ps_emailalerts and ps_emailsubscription
into these two modules go in their folder
/mails/en/
anche check their html files
they have the 1.6 template, not the 1.7 like for the other languages
this problem is present only for english language

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/76144820-4357d280-6084-11ea-8f61-31164aeaa56b.png)
![2](https://user-images.githubusercontent.com/653230/76144821-4488ff80-6084-11ea-9d42-e19d56df46bc.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2
* ps_emailalerts version: 2.1.1
* ps_emailsubscription version: 2.5.1

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks to navigate to your BO => Design => Email Theme page => Generate emails section

- Select your email theme => modern
- Select your language => English
- Select the theme you want to overwrite => Core
- Overwrite templates => Yes
- Click Generate emails

Now you can check this link: shop.com/modules/ps_emailalerts/mails/en/new_order.html

Thanks to check & feedback.

**Comment by Maofree** [comment]
hi
yes thanks
after the update from that page, those emails have the modern template
thanks

**Comment by khouloudbelguith** [comment]
@maofree, great!
I close the issue, feel free to open a new one when needed.

Thanks!
