### ISSUE TITLE
Weird behaviour when filling the quantity field with letters of symbols

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18031]
On order page > Add a product, when performing this action, you can still save it and this will add a fake product with zero quantity. It will removed when reloading the page.

**Comment by colinegin** [comment]
Related to #17968

**Comment by jolelievre** [comment]
I don't understand this one, what is this "stock field" you mention? If it's the "quantity" field then what is the difference with issue #17968 ?

**Comment by arouiadib** [comment]
@jolelievre , yes you are right. it is the quantity field (didn't read your comment before pushing PR :) )

**Comment by jolelievre** [comment]
OK, I wait for a confirmation rom @colinegin But if the problem comes from quantity, then this issue is a duplicate And a PR has already been proposed that fixes the validation server side rather than on front which is more robust regarding our domain rules

**Comment by arouiadib** [comment]
@jolelievre I totally agree with you that we should never rely on front-end validation alone. Server-side first. Really thank you for your PR because I was struggling to find where to modify server side and now I am learning from your code).

**Comment by colinegin** [comment]
Indeed, my bad I used the wrong word. I did mean "quantity". I'm changing it in the title / desc for clarification ;)
This is related to #17968 but this is a new issue to be added to this EPIC, as the problem is not that you try to edit the quantity with 0, but try to edit the quantity field with letters or symbols.

**Comment by jolelievre** [comment]
Ok, but it's actually the same problem of validation of data, so it's already been managed in this PR https://github.com/PrestaShop/PrestaShop/pull/18168

**Comment by colinegin** [comment]
Amazing 💃

**Comment by Progi1984** [comment]
Fixed by #18200
