### ISSUE TITLE
Incompatible webpack version to build admin-dev

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#18032]
#### Describe the bug

When I do:

`npm install` on /admin-dev/

I get this error:

```
> cldr-data@28.0.5 install /var/www/html/admin-dev/node_modules/cldr-data
> node install.js

Whops {} deepEqual { url:
   [ 'https://github.com/unicode-cldr/cldr-core/archive/28.0.2.zip',
     'https://github.com/unicode-cldr/cldr-dates-...
npm WARN expose-loader@0.7.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

```
Current webpack version 1. cldr-data requieres 2, 3 or 4

https://github.com/PrestaShop/PrestaShop/blob/7ef207dd32335c7fa68193711f7afa4b084e0629/admin-dev/package.json#L26

#### Expected behavior

npm install without errors

#### Steps to Reproduce

1. Git clone
2. cd admin-dev
3. npm intall

#### Additional information

* PrestaShop version: git
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

I manage to reproduce the issue with the branch 1.7.6.x, 1.7.7.x, and the develop branch.
I have these errors
```
> cldr-data@28.0.5 install /projet/issue-18032/admin-dev/node_modules/cldr-data
> node install.js

Whops {} deepEqual { url:
   [ 'https://github.com/unicode-cldr/cldr-core/archive/28.0.2.zip',
     'https://github.com/unicode-cldr/cldr-dates-...
npm WARN expose-loader@0.7.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prestashop-admin@1.0.0 No description
npm WARN prestashop-admin@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cldr-data@28.0.5 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cldr-data@28.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-09T08_21_26_392Z-debug.log
```
Ping @PrestaShop/prestashop-core-developers @NeOMakinG what do you think?

Thanks!

**Comment by NeOMakinG** [comment]
Hello, @davidglezz 

What are you trying to build using this package.json/webpack config ? I need to understand a bit more :)

**Comment by davidglezz** [comment]
Build all assets like https://devdocs.prestashop.com/1.7/development/compile-assets/ with [./tools/assets/build.sh
](https://github.com/PrestaShop/PrestaShop/blob/develop/tools/assets/build.sh) but I don't know how I did it, now I see that package.json is never built:
https://github.com/PrestaShop/PrestaShop/commit/66c87c6defb5fe01248b0a53a1533c810a04ec85#diff-ac34b5d9a6987c6e11c7a5177612bb9eR27

On the other hand, what is the purpose of that package.json? it can't be built by what I said.

**Comment by NeOMakinG** [comment]
Well I never used that package.json at all and it seems that it's not used anymore, we use package.json inside `/admin-dev/themes/new-theme` and `/admin-dev/themes/default` and they works fine, I think this is what you search for 😃

**Comment by Progi1984** [comment]
@NeOMakinG May be if it's unuseful, may be we must remove it.

**Comment by PierreRambaud** [comment]
Agreed, if not needed remove these files :)

**Comment by NeOMakinG** [comment]
I'll try to take a look if it's really not used, but it looks like no

**Comment by NeOMakinG** [comment]
I confirm this seems to have been created on the 1.7 beta release (more than 4 years ago), and it looks like the webpack conf has never been usable...
