### ISSUE TITLE
product-variants block does not change ajax refresh.

### ISSUE THREAD

**Issue by corsik** [PrestaShop/PrestaShop#18038]
After installing the update 1.7.6.3. product variants have ceased to be updated.
The .product-variants block does not change ajax refresh.

```
{block name='product_variants'}
{include file='catalog/_partials/product-variants.tpl'}
{/block}
```
I restored the old Core.js and it worked

This code would be good to make in theme.js for the possibility of its modification and verification.
#### Additional information

* PrestaShop version: 7.2
* PHP version: 1.7.6.3.

**Comment by khouloudbelguith** [comment]
Hi @corsik,

Thanks for your report.
Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/17437?
Thanks to check and feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
