### ISSUE TITLE
Quantity discount based on parameter does not work

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18049]
#### Describe the bug

When setting the "Quantity discount based on" parameter to "Products", it does not work

#### Expected behavior

When "Quantity discount based on" is set to "Products", if there is a cart rules or a specific price based on quantity, the discount should be applied as soon as we have in cart the required number of products, **even if there are different combinations in cart**.

When "Quantity discount based on" is set to "Combinations", if there is a cart rules or a specific price based on quantity, the discount should be applied only if there is the required number of products **in one combination**, and the discount will be applied only to this combination.

#### Steps to Reproduce

1. Go to Shop Parameters > Products Settings > Products (general)
2. Set "Quantity discounts based on" to "Products
3. Go to Catalog > Discounts > Catalog Price Rules
4. Create a cart rules with a reduction starting from quantity 3 (for example)
5. Go to FO, to a product with multiple combination available
6. Add 3 different combination to cart
7. Go to cart : There is no discount applied, it should be (since we have 3 combination from the same product)

**Screenshots**

https://drive.google.com/file/d/15q6jwbElhMi-PWSfen80WolJbRo5ZAH0/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi,

The price of products is NOK in:
1. Shopping cart FO
2. the final summary.
3. Order confirmation page
4. BO => order details page

PS: the Total is correct in all pages
![image](https://user-images.githubusercontent.com/16067358/76208445-f993f700-61ff-11ea-95aa-4be21506d44c.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #18427
