### ISSUE TITLE
Error while update from 1.7.5.2 to 1.7.6.4 with 1-Click module - resulting in broken shop

### ISSUE THREAD

**Issue by icemansparks** [PrestaShop/PrestaShop#18042]
#### Describe the bug

I tried to update a shop running version 1.7.5.2 with the 1-Click module.
Files are updated correctly as far as i can tell, but when it comes to the db update an error occurs, resulting in an "seemingly updated shop" with the new version number but a nun functioning backoffice and frontoffice after refreshing the pages.
Only a restore of files and database could fix the problem, an update is still not possible though.

#### Expected behavior

After the update completes, the shop should be usable again.

#### Steps to Reproduce

i downloaded the whole ftp files and also a backup of the database to my local system and installed everything in MAMP - the error still occurs, so i can cancel out the hosting provider.

**Error log**

[log.txt](https://github.com/PrestaShop/PrestaShop/files/4303612/log.txt)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.28

**Comment by khouloudbelguith** [comment]
Hi @icemansparks,

Thanks for your report.
In your log file, you have this error
```
[2020-03-08 16:58:24] [INTERNAL] /Applications/MAMP/htdocs/classes/Tools.php line 4331 - Cannot redeclare cmpPriceAsc() (previously declared in /Applications/MAMP/htdocs/override/classes/Tools.php:4229)
[2020-03-08 16:58:24] [INTERNAL] /Applications/MAMP/htdocs/classes/Tools.php line 4331 - Symfony\Component\Debug\Exception\FatalErrorException: Compile Error: Cannot redeclare cmpPriceAsc() (previously declared in /Applications/MAMP/htdocs/override/classes/Tools.php:4229)
#0 {main}
```

The autoupgrade is just stopped due to an override of the `Tools.php` class.
In order to avoid problems during the upgrade, remember not to change core files, check the compatibility of your modules and your overrides.

Thanks to check & feedback.

**Comment by icemansparks** [comment]
Hi @khouloudbelguith thank you very much for mentioning this, i was not aware that these override files exist and didn't think that they were added somehow since i am just working in the themes sub directory.

There are two files in the override/classes folder:
Tools.php and Cart.php - Cart seems to have been added by the Klarna Payment module as far as i can tell.

However, simply removing the Tools.php file has the effect that the page cannot be loaded anymore and shows a 500 error and the backend is also not responding at this point.
The difference in the Tools.php just seem to be the following lines:

```
    public static function getCMSContent($id_cms,$id_lang){
        $cms = new CMS($id_cms, $id_lang);
        return $cms->content;
    }
```

**Comment by khouloudbelguith** [comment]
@icemansparks, and the `Tools.php` was added by which module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by icemansparks** [comment]
Finally found the culprit module. The Tools.php was apparently added by some kind of outdated HTMLBox module which was already not included in the shop anymore, but somehow removing the module did not remove the tools file at the time. Manually checking everything revealed that i can delete the file for good now...

Thank you so much for your help!

**Comment by khouloudbelguith** [comment]
Hi @icemansparks,

Thanks for your feedback.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
