### ISSUE TITLE
Blockreassurance in prestashop 1.7.6.4 unistalled

### ISSUE THREAD

**Issue by jose73wrc** [PrestaShop/PrestaShop#18055]
when updating from prestashop 1.7.6.2 to 1.7.6.4 with click upgrade the blockreassurance module is uninstalled and there is no way to install it,
some help?

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.26

**Comment by khouloudbelguith** [comment]
Hi @jose73wrc,

I did not manage to reproduce the issue with PS1.7.6.4 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/16qAoL6p2i_sMjlbmRg4YZHyd5Gxn76mo/view
In your case, in the BO => Modules => Module manager page => search for the Blockreassurance => if there is no result, go to the Module Catalog page and search for this module and try to install it.

Thanks to check & feedback.

**Comment by jose73wrc** [comment]
![image](https://user-images.githubusercontent.com/61972321/76223907-d5deaa00-621b-11ea-849a-6be1898b0aa5.png)

**Comment by jose73wrc** [comment]
![image](https://user-images.githubusercontent.com/61972321/76224184-ea22a700-621b-11ea-8e52-9e7a9a6bcda4.png)

**Comment by jose73wrc** [comment]
I got that I had to update the module, I gave him accept and it came out that it was not installed.
and with the latter that you indicate directly to me the error that I have attached comes out.

**Comment by khouloudbelguith** [comment]
@jose73wrc, in your `Project_Foldor/modules/`, the folder `blockreassurance` exits or no?

Thanks!

**Comment by jose73wrc** [comment]
yes

**Comment by jose73wrc** [comment]
![image](https://user-images.githubusercontent.com/61972321/76225196-73d27480-621c-11ea-91b9-200e975aef7a.png)

**Comment by khouloudbelguith** [comment]
@jose73wrc, could you please rename the `blockreassurance` folder to `blockreassurance_old`, clear cache & try to install the module again.

Thanks!

**Comment by jose73wrc** [comment]
the error also comes out

**Comment by jose73wrc** [comment]
The theme developer comments the following:

Please access to your database (phpMyAdmin), then remove the "prstshp_reassurance" table AND "prstshp_reassurance_lang" table.

Now I observe that after trying to install, it does not create the tables

**Comment by khouloudbelguith** [comment]
@jose73wrc, so this issue occurs due to your theme?

Thanks!

**Comment by jose73wrc** [comment]
no.
I only asked for help
After trying, he told me the following:

Sorry, I also can not install this module.
Please try to open a ticket to PrestaShop here:
https://github.com/PrestaShop/PrestaShop/issues

**Comment by khouloudbelguith** [comment]
@jose73wrc, could you please try to install this module
[blockreassurance.zip](https://github.com/PrestaShop/PrestaShop/files/4307632/blockreassurance.zip)
Cloned from this [repository](https://github.com/PrestaShop/blockreassurance/releases)

Thanks to check & feedback.

**Comment by jose73wrc** [comment]
![image](https://user-images.githubusercontent.com/61972321/76233049-e1d06900-6227-11ea-9017-1c2f5bc5ac57.png)

**Comment by jose73wrc** [comment]
![Anotación 2020-03-09 170414](https://user-images.githubusercontent.com/61972321/76233200-265c0480-6228-11ea-88e1-004c5caab948.png)
![Anotación 2020-03-09 170415](https://user-images.githubusercontent.com/61972321/76233212-29ef8b80-6228-11ea-9caa-2f336d08b704.png)

**Comment by khouloudbelguith** [comment]
@jose73wrc,

Could you please provide me the credentials of your shop to test it.
This is a public space.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by jose73wrc** [comment]
The credentials of backoffice?

**Comment by khouloudbelguith** [comment]
@jose73wrc, yes!
You can just create a new employee with few permissions.
Thank!

**Comment by jose73wrc** [comment]
What permissions do you need?

**Comment by khouloudbelguith** [comment]
@jose73wrc, the back office.
Thanks!

**Comment by jose73wrc** [comment]
I have already sent to you,
You already tell me if the permissions are correct

**Comment by khouloudbelguith** [comment]
@jose73wrc, yes!
But I don't have the right permissions for the module Page
![image](https://user-images.githubusercontent.com/16067358/76236735-6d002d80-622d-11ea-8d03-4e12c7e0cf61.png)

Thanks!

**Comment by jose73wrc** [comment]
ready

**Comment by khouloudbelguith** [comment]
@jose73wrc, thanks!
Waiting for your feedback.

**Comment by jose73wrc** [comment]
ready, you have access

**Comment by jose73wrc** [comment]
I hope you find the solution

**Comment by khouloudbelguith** [comment]
@jose73wrc, could you please navigate to your BO => International => Translations page => Update your languages.
Thanks to check & feedback.

**Comment by jose73wrc** [comment]
I only have Spanish activated,
If I activate English, all products are changed and Spanish recognizes it as Basque

**Comment by jose73wrc** [comment]
What I can do?

**Comment by khouloudbelguith** [comment]
@jose73wrc, could you please navigate to your BO => International => Translations page => Update your language Spanish.
![image](https://user-images.githubusercontent.com/16067358/76298692-29073a00-62ba-11ea-927b-6dba6c67bd75.png)

Thanks!

**Comment by jose73wrc** [comment]
it's already updated
and now?

**Comment by khouloudbelguith** [comment]
@jose73wrc, could you please provide me a screenshot about the structure of your table `PREFIX_reassurance_lang`
![image](https://user-images.githubusercontent.com/16067358/76311041-59f26980-62d0-11ea-959d-450986893ab8.png)
PS: PREFIX is the prefix of your tables, It could be for example `ps_`.

Thanks to check & feedback.

**Comment by jose73wrc** [comment]
![image](https://user-images.githubusercontent.com/61972321/76311955-55c74b80-62d2-11ea-8baa-0561d4b6d432.png)

**Comment by jose73wrc** [comment]
it is this?

**Comment by khouloudbelguith** [comment]
@jose73wrc, no, this the whole database, I need just the structure of your table `PREFIX_reassurance_lang`.

Thanks!

**Comment by jose73wrc** [comment]
I don't have that table, another technician told me to remove it to install the module, and that the table would be created when installing the module

**Comment by jose73wrc** [comment]
He told me this, after removing them:
You don't need to do anything.
"prstshp_reassurance" AND "prstshp_reassurance_lang" are tables of "blockreassurance" module.
They are created when installing "blockreassurance" module.

**Comment by jose73wrc** [comment]
Do I have to restore the database?

**Comment by khouloudbelguith** [comment]
@jose73wrc, did you delete all tables created by the `blockreassurance` module manually?
Before deleting those tables, this issue occurs also?
Thanks!

**Comment by jose73wrc** [comment]
Yes, I deleted them manually.
Yes, the problem occurred before eliminating them.
the technician tried in several ways to install the module and could not, he told me to delete the 2 tables before installing the module again but it was impossible.
I asked him if he retrieved the copy of the database and he told me that it was not necessary, that they would be created again when installing the module.

**Comment by khouloudbelguith** [comment]
@jose73wrc,

Follow these steps:

1.  Unzip (decompress) the module archive file
2.  Using your FTP software
3.  Place the folder in your PrestaShop /modules folder
4.  Connect to the BackOffice of your shop
5.  Go to Back Office >> Modules >> Module Catalog page
6.  Locate the new module in the list, scrolling down if necessary.
7. Click Install.

Thanks!

**Comment by jose73wrc** [comment]
it does not work

**Comment by jose73wrc** [comment]
It can not be installed

**Comment by khouloudbelguith** [comment]
@jose73wrc,
We need to retrieve the PHP error log in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by jose73wrc** [comment]
I've seen it and I'm not sure what I have to do

**Comment by khouloudbelguith** [comment]
@jose73wrc, thanks to provide me those file logs.

Thanks!

**Comment by jose73wrc** [comment]
Could you find out something?

**Comment by khouloudbelguith** [comment]
@jose73wrc, I need to retrieve the log file to understand what's wrong.
You need to attach here, the log file.

Thanks!

**Comment by jose73wrc** [comment]
how can i see those logs?

**Comment by khouloudbelguith** [comment]
@jose73wrc, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
