### ISSUE TITLE
Missing gift message in migrated View order page

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18058]
#### Describe the bug

When "Gift wrapping" option is set to "Yes", the customer can add a gift wrapping to his order, and a gift message. In Legacy, the gift message was displayed in BO on "Shipping" block. This info is missing on Migrated page.

#### Steps to Reproduce

1. Go to Shop parameters => Order settings => Gift options
2. Set "Gift wrapping" to "Yes"
3. Go to FO, make an order, add a gift and a gift message
4. Go to BO : The message is nowhere to be found on migrated order view message

**Screenshots**

Legacy : 
![message gift](https://user-images.githubusercontent.com/55688534/76218284-4386d800-6214-11ea-9034-730fc59593eb.png)

Migrated : 
![message gift migrated](https://user-images.githubusercontent.com/55688534/76218618-d1fb5980-6214-11ea-8eac-3e84326b947f.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/18091

**Comment by Progi1984** [comment]
Fixed by #18091
