### ISSUE TITLE
change of hompage settings, no login to Presta possible

### ISSUE THREAD

**Issue by radiobaws** [PrestaShop/PrestaShop#18069]
We needed to change our shop from .com to .de, to get an SSL zertificate, so we initally set up our prestashop on .com which now gets forwarded automatically to .de, but now we actually can't login in Presta anymore.
We actually asked the presta support before we made the changes with our host, but they did not tell us about the fact that we can't login to our Presta from radioskateboards.de anymore.

How can we set up new login data/change .com to .de to login again?

Thank you in advance.

Best,
Heidi

**Comment by khouloudbelguith** [comment]
Hi @radiobaws,

You can move your Project to a new domain without errors following these steps:

1. made a backup for my files & my database
2. upload my store's files to your new server
3. import the old store's database to the new server
4. In file /app/config/parameters.php, configure my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in Table ps_shop_url, change with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. clear the cache manually by deleting all the folder into var/cache (prod & dev).

Thanks to check & feedback.

**Comment by marionf** [comment]
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!
