### ISSUE TITLE
Cannot translate Serbian in 1.7.6.0

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#18062]
#### Describe the bug

Cannot access the translation interface for the Serbian language:
![Screencap 1.7.6](https://user-images.githubusercontent.com/32565890/75902804-e6b8a580-5e40-11ea-9fc1-10d1f5c067ab.png)

#### Expected behavior

You should be able to access like in < 1.7.5

![Screencap 1.7.5](https://user-images.githubusercontent.com/32565890/75902659-aa854500-5e40-11ea-8995-0fadfefea2cd.png)

#### Steps to Reproduce

1. Install serbian
2. Go to International > Translations
3. Try to translate BO wordings in Serbian

#### Additional information

* PrestaShop version: 1.7.6.0 and later
* PHP version: Indifferent

**Comment by Progi1984** [comment]
Fixed by #18064
