### ISSUE TITLE
Add localization pack for Armenia

### ISSUE THREAD

**Issue by mrAKAR** [PrestaShop/PrestaShop#18079]
#### Describe the solution you'd like

I have added a localization pack for Armenia, please include it in future versions.

#### Additional context

Thank you very much for such hard work :)

**Comment by khouloudbelguith** [comment]
Ping @LouiseBonnard

**Comment by LouiseBonnard** [comment]
It's all fine for me, thanks a lot. I add it to PrestaShop 1.7.8!

**Comment by LouiseBonnard** [comment]
We need to wait for the next CLDR update.

**Comment by LouiseBonnard** [comment]
We need to check the CLDR update, released yesterday. See https://github.com/PrestaShop/PrestaShop/issues/21678.
