### ISSUE TITLE
Error in Production Config Plugin *Bug

### ISSUE THREAD

**Issue by julio899** [PrestaShop/PrestaShop#18075]
#### Describe the bug
`Notice en línea 1453 en archivo /var/www/html/PrestaShop/classes/Link.php
[8] Undefined index: entity`

When I enter to view the Initial View of configuration
in Develop it's Equals the code
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Link.php

exist not validation previus beffore use the position `entity`

#### Expected behavior
![Error el 2020-03-10 07 11 25](https://user-images.githubusercontent.com/2575745/76308515-55628c80-62a1-11ea-9d85-8346f19962da.png)
![Error](https://user-images.githubusercontent.com/2575745/76308536-5f848b00-62a1-11ea-9ff9-3faac4ba3d89.png)

LOCATION -> /classes/Link.php
#### Steps to Reproduce
install some plugin extra or independent and go to config these plugin

1. Go to 'http://localhost/prestashop/admin-dev/index.php?controller=AdminModules&configure=name_plugin'
2.  Click to Config
3. See error

**Screenshots**

![Error el 2020-03-10 07 11 25](https://user-images.githubusercontent.com/2575745/76308515-55628c80-62a1-11ea-9d85-8346f19962da.png)
![Error](https://user-images.githubusercontent.com/2575745/76308536-5f848b00-62a1-11ea-9ff9-3faac4ba3d89.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: PHP 7.2.24

**Comment by khouloudbelguith** [comment]
Hi @julio899,

Have you tried to contact the module author about this issue?
PS: We are still working on the 1.7.7.0 version, is not stable yet.
The last stable version released is PS1.7.6.4.
Thanks to check & feedback.

**Comment by julio899** [comment]
> Hi @julio899,
> 
> Have you tried to contact the module author about this issue?
> PS: We are still working on the 1.7.7.0 version, is not stable yet.
> The last stable version released is PS1.7.6.4.
> Thanks to check & feedback.

Thanks @khouloudbelguith by you response, but in 1.7.6 I can see the same code fragment.
![imagen](https://user-images.githubusercontent.com/2575745/76364931-799f8700-62fc-11ea-8de1-251527d4f6ac.png)

**Comment by khouloudbelguith** [comment]
@julio899, so you are not using the last version of PrestaShop downloaded from [our Official link](https://www.prestashop.com/en/previous-versions)?
You are using PrestaShop cloned from GitHub?
Have you tried to contact the module(payus) author about your issue?

Thanks!

**Comment by julio899** [comment]
hi @khouloudbelguith  I'm but what do you need?.

right now i resolved this, and coming soon I go to share the solution.
thanks.

**Comment by khouloudbelguith** [comment]
@julio899, thanks!
Waiting for your feedback.

**Comment by julio899** [comment]
> @julio899, thanks!
> Waiting for your feedback.

Hi @khouloudbelguith 
well for me, I don't know by what happened this,  but work in my case.

I need remove this file in you folder the prestashop in my case his name is *PrestaShop*
`/var/www/html/PrestaShop/config/xml`
![imagen](https://user-images.githubusercontent.com/2575745/76952947-45236080-68e4-11ea-9fb2-0bd34d72cac8.png)

you can remove the forder `xml` that exist into forder `config`

and then await till generate again the dir to push clear cache.
![imagen](https://user-images.githubusercontent.com/2575745/76952996-58363080-68e4-11ea-8cfd-d98acc35b3e9.png)

and after i can run without problems.
![imagen](https://user-images.githubusercontent.com/2575745/76952894-2cb34600-68e4-11ea-91dd-ae96d145670a.png)

**Comment by khouloudbelguith** [comment]
@julio899, this is a cache issue.
Since it is fixed, I will close the ticket, feel free to open a new one when needed.

Thanks!
