### ISSUE TITLE
The function array_key_exists() is deprecated on PHP 7.4

### ISSUE THREAD

**Issue by quentin244** [PrestaShop/PrestaShop#18083]
#### Describe the bug
The function array_key_exists() is deprecated on PHP 7.4
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\wamp64\www\prestashop_1.7.6.3\src\Adapter\EntityMapper.php on line 99

#### Expected behavior

We migth using another function to verify the array key

#### Steps to Reproduce

1. Go to url of your site Prestashop
2. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.4

**Comment by Gipielle** [comment]
PS 1.7.6 is not compatible with php 7.4

**Comment by khouloudbelguith** [comment]
Hi @quentin244,

PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by mickaelandrieu** [comment]
it's only deprecated for objects, not for arrays.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
Will be solved with all compatibility issues in PS 1.7.8 when we enable php7.4 😄
https://github.com/PrestaShop/PrestaShop/issues/16477

**Comment by PierreRambaud** [comment]
Duplicates of #16477
