### ISSUE TITLE
Last update of order hooks before beta

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#18084]
#### Is your feature request related to a problem?

We decided to rename/move a few of order view page's hook for more consistency

#### Describe the solution you'd like

See details in the linked PR

https://github.com/PrestaShop/PrestaShop/pull/17734

**Comment by jolelievre** [comment]
This issue is tagged as major/must-have because it needs to be validated/merged as a priority

Indeed some doc articles and the example module depend on it, and these articles will soon be used as a support to help module's developer migrate their order related modules

**Comment by Progi1984** [comment]
Fixed by #17734
