### ISSUE TITLE
module, it doesn't work

### ISSUE THREAD

**Issue by storygram** [PrestaShop/PrestaShop#18085]
I bought a Google Cusomer Reviews Hiddentechies module, it doesn't work, the seller says the problem is from the prestashop, can you help me?
Pretashop 1.7.61

**Comment by khouloudbelguith** [comment]
Hi @storygram,

Thanks for your report.
This module is bought from the Addons PrestaShop Marketplace?
What is the exact name of this module?
Thanks to provide me a link to this module?

Thanks!

**Comment by storygram** [comment]
https://www.hiddentechies.com/google-customer-reviews-prestashop-module.html

**Comment by matks** [comment]
> the seller says the problem is from the prestashop

We will need a lot more details, "it does not work" is not accurate enough

The module developer can open a github issue, like you did, with details and if indeed the issue comes from prestashop we might fix it.

**Comment by storygram** [comment]
This is not displayed on the page, I made all the settings and nothing
![Untitled](https://user-images.githubusercontent.com/58422218/76402088-8f0fc200-638b-11ea-826b-cf5ecf1b54aa.jpg)

**Comment by khouloudbelguith** [comment]
@storygram,

As it's not a module provided by Prestashop, we can't do anything with this. 
@matks said, "The module developer can open a GitHub issue, like you did, with details and if indeed the issue comes from PrestaShop we might fix it."

Thanks for understanding!

**Comment by storygram** [comment]
ok,tnks

**Comment by khouloudbelguith** [comment]
@storygram, I close the issue, feel free to open a new one when needed.

Thanks!
