### ISSUE TITLE
Add a quoting system

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#18088]
#### Is your feature request related to a problem?

Yes. As a web developer in an agency, I've a lot of customers (B2B) who ask to have a quoting system.

#### Describe the solution you'd like

PrestaShop currently allows the creation of a shopping cart that can be transformed into an order.

Would it be possible to add a second system that allows you to transform a cart into a quote?

The features, parameters, etc. would of course have to be specified, but is the idea possible?

#### Alternatives you've considered

There is modules, but I think a native module OR a native feature would be better.

**Comment by Gipielle** [comment]
Great idea ! I have had this idea for years

**Comment by khouloudbelguith** [comment]
Hi @yannicka,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment]
As you just said, there are a lot of existing modules which provide a quoting system, so I don't think this is critical to add one natively. We try to offer native features which will be useful for most of our users and a quoting feature seems quite specific in my opinion (although I know in B2B this is a very important feature). 

But maybe we could add features / options in the code and back-office which will make it easier for developers to develop quoting features. What do you think @yannicka ? Why were you thinking a native module or feature would be better ?

**Comment by matks** [comment]
> There is modules, but I think a native module OR a native feature would be better.

Why a native module would be better ? Or a native feature 😊?
Would it be that PrestaShop module would be better quality than existing modules ?
Or is it the price (native module = free) 😄?

Modules allow
- people who want them to install them
- people who dont want them to uninstall them (else they have a useless part - for them - in their shop)

**Comment by Gipielle** [comment]
No problem to pay modules, but often modules add unnecessary complexity, mistakes, and better work for traders.

Personally I would be well disposed to pay a version of prestashop that didn't require me hours and hours of work to fix problems.

**Comment by matks** [comment]
> Personally I would be well disposed to pay a version of prestashop that didn't require me hours and hours of work to fix problems.

So a suitable solution for you would be a module developed and *sold* by PrestaShop (= level of quality is guaranteed) which enables quoting capabilities ?
I ask this because native (= free) modules can have limited capabilities while sold modules can be a lot more complete.

**Comment by felixd** [comment]
Any updates, progress on this issue?

**Comment by matks** [comment]
Hello @felixd if nobody replied since 2020, I guess it's because nobody is interested in doing that.

I will close this issue because I think if nobody volunteered to do it in 4 years, I don't see why it would change soon. I prefer not to give wrong expectations.

If you wish a quoting system in PrestaShop: the 2 most efficient to get it is to either build it or pay someone to build it (and then submit it to the community 😉 )
