### ISSUE TITLE
Enable SSL on All Pages does not work on backend admin

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#18099]
**Describe the bug**
When you set CONFIGURE > SHOP PARAMETER > GENERAL > ENABLE SSL ON ALL PAGES = YES it only works on Frontend pages but no on Backend Admin pages. There is no option to force this on backend.

**To Reproduce**

1. Set CONFIGURE > SHOP PARAMETER > GENERAL > ENABLE SSL ON ALL PAGES = YES
2. Go to Frontend page using non-ssl HTTP and it will automatically redirect to HTTPS (this works fine).
3. Go to Backend Admin login page using non-ssl HTTP and it will give you a warning but will not redirect you to HTTPS.
4. Then go to any other back admin page using non-ssl HTTP and it will allow you view that page unsecurely and will not redirect you to HTTPS.

**Suggestion**
(1) If this is intended behavior, then the the ENABLE SSL ON ALL PAGES setting should be renamed to ENABLE SSL ON ALL FRONTED PAGES.
(2) There should be an option to FORCE SSL on admin backend pages. A warning on login screen is insufficient as I could accidentally end up on http somehow, when I want to actually always be in https.

**Additional information**
PrestaShop version: 1.7.6.4
PHP version: 7.2.28

**Comment by khouloudbelguith** [comment]
Hi @sharkooon,

I tried with PS1.7.6.4.
In the FO and the BO => I have the same behavior.
I attached a screen record
https://drive.google.com/file/d/1yOoyLVbtISHLwmRQK8sKQLHYt0A89ZZo/view

Thanks to check and feedback.

**Comment by Gipielle** [comment]
I agree sharkooon, 
there has always been this problem. I didn't even notice it anymore.

Better get it fixed.

**Comment by didi-2018** [comment]
@khouloudbelguith I can not agree. Everything works fine with php 7.2.1 and nginx/1.14.0. 
Have you tried on nginx?

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

I tried with Nginx server=> same behavior
I attached a screen record
https://drive.google.com/file/d/1HtWMLhkTzUC6kfXEMUEk8-A8c1oao1HN/view

Thanks!

**Comment by didi-2018** [comment]
@khouloudbelguith   okay, too bad. For me it is working. BO and FO all pages with SSL. No problems at my 1.7.6.4 installation 👍

**Comment by khouloudbelguith** [comment]
@sharkooon, any news?

Thanks!

**Comment by marionf** [comment]
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Comment by jesusemarquezz** [comment]
Hi, I have the same problem, what additional information do you require to help me with this problem?

this is my version of php:
`PHP 7.1.33-17+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:47:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-17+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans`

and this is my version of apache:
`Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-04-13T17:19:17`

My problem is the same, when activating the Option "**Activate SSL on all pages**" the Administrative part of Presta Shop does not allow me to make any changes and every time I save, I redirect to make login, while having this option enabled if it works for me perfectly the Store on the Client's Side and I do not get the Error of "**ERR_TOO_MANY_REDIRECTS**", when through the database I disable the option "**Activate SSL on all pages**" the opposite happens, if it saves me and the administrative part works perfectly , but then the client-side store stays at "**ERR_TOO_MANY_REDIRECTS**" I hope I could have explained better xD Thanks in advance

**Comment by jesusemarquezz** [comment]
This is My Video Problem [Video](https://streamable.com/z9gg95)
