### ISSUE TITLE
New invoice is not displayed in Documents tab if you don't refresh the page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18096]
#### Describe the bug

New invoice is not displayed in Documents tab if you not refresh the page

#### Expected behavior

Display new invoice in Documents tab without having to refresh the page, as in legacy

#### Steps to Reproduce

1. Go to orders > orders
2. Click on View for an order in "payment accepted" status
3. Add a product to the order and select "Create a new invoice"
4. The new invoice is not displayed in Documents tab, you have to refresh the page

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf 

It is duplicate of https://github.com/PrestaShop/PrestaShop/issues/17977
Is it?

Thanks!

**Comment by marionf** [comment]
Yes
