### ISSUE TITLE
[-] [FO] SEF URL scheme not working anymore from version 1.5.3

### ISSUE THREAD

**Issue by ldecoker** [PrestaShop/PrestaShop#181]
Even if you define custom SEF URL scheme, the dispatcher always use the default one.
This is due to a modification in the Dispatcher class - function loadRoutes(): the default routes are loaded in the routes array after the custom ones and so custom ones are overwritten.

In 1.5.2, default routes were loaded at first step of this method.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
