### ISSUE TITLE
Duplicate address after editing an address

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18100]
#### Describe the bug

Following this [comment](https://github.com/PrestaShop/PrestaShop/issues/18072#issuecomment-597524637)
Go to your profile, edit an address. Put numbers in the first name field in order to trigger a validation error. Then remove the number, and save. It will create a duplicate address.

#### Expected behavior

Edit the address instead of creating a new one when the customer wants to edit his address

#### Steps to Reproduce

1. Log in, if you don't have an address, create it
2. Go to your profile, edit an address
3. Put numbers in the first name field in order to trigger a validation error
4. Then remove the number, and save
5. see the error => It will create a duplicate address

**Screenshots**

https://drive.google.com/file/d/144L_Jbnf1oWeeecEPamqk-246TKCOuN-/view

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18103

**Comment by valentintur** [comment]
Have this problem in PrestaShop 1.7.6.9
