### ISSUE TITLE
Order confirmation slow 

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#18108]
Order confirmation is slow

the solution is this from prestashop forum:

SOLVED :

The shop has no stock management, and it was desactivated in the back office.

 I tested multiple files with var-dump and found that in file:

./classes/order/OrderDetail.php

commenting this line

//$this->checkProductStock($product, $id_order_state);

solved my problem and order confirmation are 'fast'

I used this solution in prestashop 1.5 for long time, now with prestashop 1.7 is there a way to implement this when stock management is desctivated in the backoffice, that is, without having to modify the core files

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Gipielle,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1_1ObfDXPPmetY7bx5KOgmJ_vV_XSoNVQ/view

Thanks to check and feedback.

**Comment by Gipielle** [comment]
Hello, 
try to add 20-30 different products with different quantity

**Comment by khouloudbelguith** [comment]
@Gipielle, I attached a screen record
https://drive.google.com/file/d/1n4If81rPVpQOdPh8UWAv5-736sAEiL3S/view
Thanks to check & feedback.

**Comment by Gipielle** [comment]
Thanks, so mabye is one page checkout module

**Comment by khouloudbelguith** [comment]
@Gipielle, this module is bought from the Addons Market place?

Thanks!

**Comment by Gipielle** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@Gipielle,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
