### ISSUE TITLE
[Order page] Improve error message in partial refund

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18106]
Currently in the partial refund block, if the user does not fill the quantity field but only the price field, he gets the following error message : "Please enter a positive quantity." This leads to misunderstanding. We should modify this error to tell the user to add a quantity in the quantity field.

What do you think @LouiseBonnard ?

**Comment by LouiseBonnard** [comment]
Hi @colinegin, what about _Please add a product quantity._?

**Comment by colinegin** [comment]
Should this be located in the global wording improvement issue for 177 ?

**Comment by LouiseBonnard** [comment]
Sure! Once the PR done, I'll add it to the list of wordings to be merged [here](https://github.com/PrestaShop/PrestaShop/issues/17993).

**Comment by jolelievre** [comment]
But if we use a generic message like `Please add a product quantity.` Then the message won't be understanding when the user inputs 0 or less

**Comment by LouiseBonnard** [comment]
Why would the user type 0 or less if he/she has to indicate the quantity refunded?

It might be a little naive but we have a lot of error notifications stating that negative amounts are not allowed, or that users must type a positive value, etc. wouldn't it be better to have fields that simply block negative signs in case a user types one? Like inputs are allowed only if it matches the required format. I'd save a lot of notifications...

😇

**Comment by LouiseBonnard** [comment]
@jolelievre and @colinegin, I have better wording to gather the two information: _Positive product quantity is required_ in _Admin.Notifications.Error_, thanks!

Also, so that it can be studied for PrestaShop 1.7.8 or any future future version, I'll create a feature request following my last comment. It'd be a great improvement to be able to set some kind of input rules depending on the nature of the field.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18420
