### ISSUE TITLE
Extra columns of attribute_lang table deleted on ps upgrade

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#18113]
#### Describe the bug

A clear and concise description of what went wrong.

Extra columns of attribute_lang table have been deleted on a patch prestashop upgrade.
Others extra columns in other tables are not impacted by upgrade.

#### Steps to Reproduce
1. Add a column named description to ps_attribute_lang 
2. It's not mandatory, but you can add this column to the Attribute object model with an override
3. Upgrade Prestashop from 1.7.6.2 to  1.7.6.4 with autoupgrade module
4. The description have been deleted

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with 1.7.6.4 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/14n6uQ_jHsdxgzWqHBNQ0h7qPlxrRCiem/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by jf-viguier** [comment]
Thanks khouloudbelguith. We had this bug in other upgrades too.
@matks is this bug can be related to doctrine stuff ? https://devdocs.prestashop.com/1.7/modules/concepts/overrides/

**Comment by matks** [comment]
> Thanks khouloudbelguith. We had this bug in other upgrades too.
> @matks is this bug can be related to doctrine stuff ? https://devdocs.prestashop.com/1.7/modules/concepts/overrides/

I dont see how 🤔 do you have an idea in mind ?

SQL auto-upgrade step for 1.7.6.2 => 1.7.6.3 is https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/install-dev/upgrade/sql/1.7.6.3.sql
No SQL auto-upgrade step for 1.7.6.3 => 1.7.6.4

**Comment by jf-viguier** [comment]
@matks Maybe doctrine delete/create tables ?
cf : https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/install-dev/upgrade/php/ps_1763_update_tabs.php
I've checked sql script : nothing here, the bug is somewhere else. Do you have an idea ?
