### ISSUE TITLE
[CREATE ORDER] Issues on vouchers adding gift products to the manually created cart

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18119]
**ISSUE UPDATED**

Several issues related to vouchers with gift products added to the manually created order have appeared. To make it clear what are the expected behaviours, I've updated the [specifications on the create order page](https://github.com/PrestaShop/prestashop-specs/blob/MatShir-create-order/back-office/orders/orders/Create%20new%20order.md) (available in section III - voucher). Please review it and tell me if you have any comments or questions.

ping @matks @zuk3975 @Robin-Fischer-PS @MatShir 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - - - - - 

**Current behavior**

Small difference between Legacy and Migrated page.

If I add a voucher with a Gift and another discount (amount, percentage...), if I remove the voucher : 
- Legacy : Voucher AND gift are deleted from the order
- Migrated page : Only the voucher is deleted, the gift stays in the order

For reminder, when adding a voucher only with a Gift, it is not possible to remove it either in Legacy or in Migrated page. The voucher is not displayed in the list.

Screenrecord of Legacy behavior : 
https://drive.google.com/file/d/1ShPcag0h5oNLtV4EpYCokMvtuwu8jEcs/view?usp=sharing

Screenrecord of Migrated behavior : 
https://drive.google.com/file/d/1IO8hy7bJoj9vyY1KYRaMfck_nJdyQSjg/view?usp=sharing

**Expected behavior**

Voucher gifts with or without other cart rules actions should be displayed on the voucher list.
If the voucher is deleted, it deletes the gift from the product list.

_Originally posted by @Robin-Fischer-PS in https://github.com/PrestaShop/PrestaShop/pull/17179#issuecomment-598200694_

**Comment by Progi1984** [comment]
Fixed by #17179
