### ISSUE TITLE
Prestashop 1.7.6.4 does not report modified or missing files

### ISSUE THREAD

**Issue by Dric78** [PrestaShop/PrestaShop#18114]
After upgrading to prestashop 1.7.6.4, the list of modified or missing files in "Admin>Configure>Advanced>System information" is no more working. Files modified or deleted are no more reported.

After investiguation, the problem is not located in this version code but on prestashop's api : the list of md5 for this version in not avaiable at http://api.prestashop.com/xml/md5-17/1.7.6.4.xml

Could you please correct it ? Thanks in advance :-)

* PrestaShop version: 1.7.6.4
* PHP version: not relevant

**Comment by khouloudbelguith** [comment]
Hi @Dric78,

Thanks for your report.
This link: http://api.prestashop.com/xml/md5-17/1.7.6.4.xml is not found
But http://api.prestashop.com/xml/md5-17/1.7.6.3.xml => OK
Ping @PrestaShop/prestashop-core-developers

Thanks!

**Comment by eternoendless** [comment]
Ooops! I'll fix that right away

**Comment by eternoendless** [comment]
It should be fixed now. Thanks for the report!

**Comment by Dric78** [comment]
Now working as expected. Perfect.

Thanks for the quick fix :-)
