### ISSUE TITLE
JS and CSS not loading

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#18126]
Hello!

I have an issue with PrestaShop 1.7.6.4 where the JavaScript and CSS files aren't getting loaded properly.
The same problem on version 1.7.5.2. It happens that for some requests Prestashop does not load media, Css and JavaScript.
After refreshing the site everything is OK again.

Linux #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64
Server: Apache
PHP version: 7.1.27 - 7.3.3

![2020-03-12_21-38-53](https://user-images.githubusercontent.com/1309982/76565270-7fd36600-64aa-11ea-8334-2f9b1e041266.jpg)

**Comment by bullmade** [comment]
Hi @elrosi 
Are you using any cache modules?
And are you using PrestaShop native Caching (Memcache, APC, etc?)

I've seen conflicts between those, as one cache system does not clear the others, if you are using multiple.

**Comment by khouloudbelguith** [comment]
Hi @elrosi,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Second, thanks to check the table `PREFIX_shop_url`, the `domain`, `domain_ssl` and the `physical_uri` are correctly set.

Finally, could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by SharakPL** [comment]
Just had to deal with this issue when I moved my shop to another server. Turning off SSL fixed the problem. SSL seems to be enabled on the server, but my nginx configuration isn't properly configured yet.
