### ISSUE TITLE
Last breadcrumb element "Your account" is not clickable in the Your account blocks

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18122]
#### Describe the bug

In the "Your account" blocks, the last breadcrumb element is not clickable.
For example in the  "Your address" page
![image](https://user-images.githubusercontent.com/16067358/76544453-5bff2880-6488-11ea-929d-a47f67e861b4.png)

#### Expected behavior

We should have `Home / Your account / Your address`

So, `Your account` is clickable

#### Steps to Reproduce

1. Go to FO 
2. Sign in
3. Go to "Your account" page
4. Check all blocks
5. The last breadcrumb element is not clickable

It is not the same case with PS1.7.6

**Screenshots**
PS1.7.6.4: https://drive.google.com/file/d/1YdUwkeHvEPqe6s4x_41mtf6XoSJR-R6j/view
PS1.7.7: https://drive.google.com/file/d/1aErDxq9Q6c7oX-bCPXOj2Y_VK2nDNvvr/view

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/pull/14710

**Comment by jolelievre** [comment]
I believe it's voluntary The last breadcrumb element is not supposed to be clickable
In this case I'd say the real problem is that the breadcrumb doesn't include the parent page "Your account" And the last breadcrumb element should be "You addresses" in the example case

**Comment by sam-pires** [comment]
#14710 makes sense in the product pages, but in this situation we should have the same behavior as @jolelievre explained.

Though, as we are currently working on defining clearly the breadcrumbs rules with @prestascott (#17131)  I would say "let's drop this one" untill we define the rules. 

wdyt?

**Comment by Hlavtox** [comment]
@khouloudbelguith I have fixed this in my PR.

https://github.com/PrestaShop/PrestaShop/pull/16837

**Comment by clotairer** [comment]
Thank you @Hlavtox !

**Comment by matks** [comment]
May be fixed by https://github.com/PrestaShop/PrestaShop/pull/18221 for `1.7.7.x` and https://github.com/PrestaShop/PrestaShop/pull/16837 for `develop`

**Comment by jolelievre** [comment]
Is it useful to merge the one targeting develop? Since it will be merged from 177x to develop later anyway?

**Comment by Progi1984** [comment]
Fixed in 1.7.7.x branch
