### ISSUE TITLE
Issue with ps_featuredproducts when flip the screen on Mobile and Tablets

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#18121]
Hi there is an issue with the module ps_featuredproducts when flip the screen on Mobile and Tablets
IOS or Android, it show all product one on top the other.

The carousel stop working

PS 1.7.6.3
ps_featuredproducts v. 2.0

![WhatsApp Image 2020-03-12 at 1 28 20 PM](https://user-images.githubusercontent.com/46203943/76543910-f00bc880-6465-11ea-92c3-bfa03b73dd3f.jpeg)
![WhatsApp Image 2020-03-12 at 1 27 44 PM](https://user-images.githubusercontent.com/46203943/76543916-f13cf580-6465-11ea-9ecd-9bc6b126ca72.jpeg)

**Comment by khouloudbelguith** [comment]
Hi @msaustral,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/107xkSAewTDqXICjuvzdDEGOa4uPKCIud/view
Thanks to check and feedback.

**Comment by msaustral** [comment]
Hi, sorry the module that you are trying is popular products, the module that have the issue is featured products 2.0 that now it is a carousel, it does not fail on the emulator but it does on real equipment.

**Comment by msaustral** [comment]
Hi sorry the issue is with the classic-rocket

**Comment by khouloudbelguith** [comment]
@msaustral, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
