### ISSUE TITLE
Faceted search category filter not working in 1st depth categories

### ISSUE THREAD

**Issue by sunchayn** [PrestaShop/PrestaShop#18128]
#### Describe the bug

When I filter by category within a category with depth of 1 it does not apply the filter properly. The filter only works when I enter a deeper depth. The manufacturer filter works however in a 1st depth category.

It shows the correct number of products but when I select the desired filter it does not properly apply it. The URL does change for example to `mysite/4-1st-depth?q=Catégories-Test`
but the the category will be completely ignored when I'm in 1st depth.

PS: by 1st I mean the categories listed under the Home directly. 
![1st depth](https://user-images.githubusercontent.com/14861869/76584326-e329bc00-64db-11ea-805c-18b786340aaf.PNG)

**Configuration**
![config](https://user-images.githubusercontent.com/14861869/76583943-d6589880-64da-11ea-84aa-1434bd967360.PNG)

All of my products are attached to exactly one category.

#### Additional information

* PrestaShop version: 1.7.6.2
* Faceted search version: 3.4.1
* PHP version: 7.2.19

**Comment by khouloudbelguith** [comment]
Hi @mazentouati,

I did not manage to reproduce the issue with PS1.7.6.4 and ps_facetedsearch module v3.4.1.
I attached a screen record
[Untitled_ Mar 17, 2020 11_48 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4343012/Untitled_.Mar.17.2020.11_48.AM.webm.zip)
Category filter depth => 1 is the category by default.
![image](https://user-images.githubusercontent.com/16067358/76849293-6f721100-6845-11ea-9cbe-18d7c83c80fe.png)

We have already an issue with an unlimited filter depth as reported here: https://github.com/PrestaShop/PrestaShop/issues/16067

Thanks to check and feedback.

**Comment by sunchayn** [comment]
Hi @khouloudbelguith, Yes what's described in that issue is exactly the problem. I've tried 0 depth at the beginning then tried with 4 depth. I've downgraded the module version to `2.2.1` and it's working as expected with 0 depth.

**Comment by khouloudbelguith** [comment]
@mazentouati, thanks for your feedback.
Your ticket is a duplicate of #16067
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #16067
