### ISSUE TITLE
"Install latest instead ?" installer feature seems buggy

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#18138]
#### Describe the bug

"Install latest instead ?" installer feature seems buggy. It seems either not working (do not download latest version" or does not work well (need to re-click on "yes please" button to make it work).

#### Expected behavior

When I download and run 1.7.6.3 installer, if I accept, I expect 1.7.6.4 version to be downloaded instead and installed.

#### Steps to Reproduce

1. Go to prestashop.com and download 1.7.6.3 ZIP archive
2. Unzip it and launch install
3. As 1.7.6.4 is out, you should be prompted the following screen
<img width="565" alt="Capture d’écran 2020-03-13 à 11 44 12" src="https://user-images.githubusercontent.com/3830050/76614725-f317bf00-6520-11ea-8cca-67cf4c62639d.png">
4. If you click on "Yes please", you might see one the following usecases:
- "Downloading X ..." is shown then page stops running, and you still see the yes/no button
- "Downloading X ..." is shown then page refreshs and it starts installing PS 1.7.6.3 ! (although PS 1.7.6.4 was supposed to be donwloaded instead)

#### Additional information

* PrestaShop version: 1.7.6.3

**Comment by khouloudbelguith** [comment]
Hi @matks,

I did not manage to reproduce the issue with PS1.7.6.2 and PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1WalP-1EL46DOXKE43fdUifC-fru2xTlk/view
Thanks to check and feedback.
