### ISSUE TITLE
Shop parameters > Orders setting > Error

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18141]
Navigate in shop parameter orders settings i got this error:

admin_17.js:19 Uncaught ReferenceError: $ is not defined
    at admin_17.js:19
(anonymous) @ admin_17.js:19
jquery-confirm.js:40 Uncaught ReferenceError: jQuery is not defined
    at jquery-confirm.js:40
    at jquery-confirm.js:42
(anonymous) @ jquery-confirm.js:40
(anonymous) @ jquery-confirm.js:42
admin-order.js:14 Uncaught ReferenceError: $ is not defined
    at admin-order.js:14
(anonymous) @ admin-order.js:14
config.js?v=1.2:18 Uncaught ReferenceError: $ is not defined
    at config.js?v=1.2:18
(anonymous) @ config.js?v=1.2:18
jquery-confirm.js:40 Uncaught ReferenceError: jQuery is not defined
    at jquery-confirm.js:40
    at jquery-confirm.js:42
(anonymous) @ jquery-confirm.js:40
(anonymous) @ jquery-confirm.js:42
config.js?v=1.3:14 Uncaught ReferenceError: $ is not defined
    at config.js?v=1.3:14

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

I did not manage to reproduce the issue with PS1.7.6.4.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Betafer** [comment]
<img width="1993" alt="Schermata 2020-03-16 alle 13 25 45" src="https://user-images.githubusercontent.com/5024055/76758353-d205d700-6789-11ea-9a87-b43781398570.png">

Here the screenshot, Go to Shop parameters, order setting, in browser console got this errors

**Comment by Betafer** [comment]
Browser Chrome Ver 80

**Comment by Betafer** [comment]
Are modules problem: AmazonPay and other two modules.

Except this: 
GET https://www.betafer.it/modules/ps_advertising/logo.png net::ERR_BLOCKED_BY_CLIENT

**Comment by khouloudbelguith** [comment]
@Betafer,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Betafer** [comment]
Ok thanks
