### ISSUE TITLE
Refund buttons/actions should rely on paid status instead of invoice

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#18157]
#### Describe the bug

For now the condition to display and authorize the partial refund button, and the standard refund button is to check if order has an invoice. This was done because when the order is set a paid status the invoice is automatically generated. But the two conditions are not equivalent because an order can be manually generated, in which case you can then refund it even though it has not been paid.

#### Expected behavior

The buttons should be visible:
- when the order has been paid.
- when at least one payment is added to the order

The invoice is not a guaranty that any payment has been validated.

#### Steps to Reproduce

Steps to reproduce the **expected** behavior:

1. Go to an unpaid order
2. In the Documents Tab click on the "Generate an invoice" button
3. The refund buttons **must not** be visible
4. Add a payment to the order, the buttons are now visible

Second scenario

1. Go to another unpaid order
2. Switch the status to "Payment accepted"
3. The buttons are visible

Third scenario

1. Go to an unpaid order
2. Add a partial payment
3. The buttons are visible even though there is No invoice and no status as paid

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Same behavior with PS1.7.6.4 and PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/76749751-53a33800-677d-11ea-9f20-94d41b7eec42.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #18164
