### ISSUE TITLE
ProductAssembler class assigns wrong product attributes in multistore website (from another shop) - have a solution from branch#17573

### ISSUE THREAD

**Issue by gwyneblaidd** [PrestaShop/PrestaShop#18155]
Hi guys!

I have faced a problem with some module (not really important which - it utilizes PS function) when a shop in a multistore missed showing prices for some products (multistore website). Quick debug showed it's connected with the wrong product_attribute that belongs to the product from another shop (the same product, but another shop). The product is shared among shops but each shop has its combinations. I have found that problems occur in ProductAssemblerCore::addMissingProductFields() function. This function is not adapted for getting product attributes in connection to the store.

check this code from original PS file classes/ProductAssembler.php

private function addMissingProductFields(array $rawProduct)
    {
        $idShop = (int) $this->searchContext->getIdShop();
        $idLang = (int) $this->searchContext->getIdLang();
        $idProduct = (int) $rawProduct['id_product'];
        $prefix = _DB_PREFIX_;

        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
        if (!Validate::isUnsignedInt($nbDaysNewProduct)) {
            $nbDaysNewProduct = 20;
        }

        $now = date('Y-m-d').' 00:00:00';

         $sql = "SELECT
                    p.*,
                    pl.*,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
	            ON sa.id_product = p.id_product 
		    AND sa.id_shop = $idShop
		WHERE p.id_product = $idProduct";

        $rows = Db::getInstance()->executeS($sql);
        if ($rows === false) {
            return $rawProduct;
        }

        return array_merge($rows[0], $rawProduct);
    }
You can see. that function returns columns from the product table, that have no association with a shop (like product_shop). This has a great problem with some essential data stored there. For example, cache_default_attribute from the product table. cache_default_attribute is different for each shop and proper value is stored in product_shop. So, if the script picks up this cache_default_attribute (like in my case) this cache_default_attribute is taken randomly from the product table (it depends on which shop product was added at first so it keeps value connected to that store). If this product was added to shop1 (for example) at first it will contain product_attribute for this shop. If we add this product to another shop2 product table will not be changed (it will be saved in product_shop table). So, running ProductAssemblerCore::addMissingProductFields() function in shop1 will return proper combination from (cache_default_attribute ), but wrong for another shop2 (this combination still will be from shop1). If those combinations are not shared between shops PS will not return any associated with combination data (because this is restricted data from another shop). In my case, I am getting 0 prices in this case (my all prices depends on combinations).

I have a solution in my case for a problematic sql query. It is to join table product_shop that will give product data per shop, so it can fix many other parts in the PS core that uses that function. Check this changed code:|

$sql = "SELECT
                    p.*,
                    pl.*,
                    ps.cache_default_attribute,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_shop ps
                    ON ps.id_product = p.id_product
                    AND ps.id_shop = $idShop
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product 
			        AND sa.id_shop = $idShop
			    WHERE p.id_product = $idProduct";
In that modified code I am extracting additionally only one field ps.cache_default_attribute from shop associated table product_shop. But I think we can replace all fields from the product table and use product_shop instead, so it can be like ps.*.

**Comment by gwyneblaidd** [comment]
hi @khouloudbelguith 

Previous #17573 was closed. Lets continue pls. t can help a lot

Use this code 

 ```
  $order_products = [123];
           $showPrice = true;

            $assembler = new ProductAssembler($this->context);

            $presenterFactory = new ProductPresenterFactory($this->context);
            $presentationSettings = $presenterFactory->getPresentationSettings();
            $presenter = new ProductListingPresenter(
                new ImageRetriever(
                    $this->context->link
                ),
                $this->context->link,
                new PriceFormatter(),
                new ProductColorsRetriever(),
                $this->context->getTranslator()
            );

            $productsForTemplate = array();

            $presentationSettings->showPrices = $showPrice;

            if (is_array($order_products)) {
                foreach ($order_products as $productId) {
                    $productsForTemplate[] = $presenter->present(
                        $presentationSettings,
                        $assembler->assembleProduct(array('id_product' => $productId)),
                        $this->context->language
                    );
                }
            }

print_r($productsForTemplate);exit;
```

**Comment by gwyneblaidd** [comment]
Check print_r($productsForTemplate); content. Before running code note cached_attribute_id from both shops for the product you used.

**Comment by khouloudbelguith** [comment]
Hi @gwyneblaidd,

I tried to replace this [line](https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/classes/ProductAssembler.php#L68) by  your solution
```
$sql = "SELECT
                    p.*,
                    pl.*,
                    ps.cache_default_attribute,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_shop ps
                    ON ps.id_product = p.id_product
                    AND ps.id_shop = $idShop
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product 
			        AND sa.id_shop = $idShop
			    WHERE p.id_product = $idProduct";
```
Then I followed these steps:

1. Enable Multistore context
2. Create a second shop
3. Create a product P1 in all shops
4. Create some combinations for P1 in the first shop
5. Create other combinations for P1 in the second shop
6. Put some additional price per each combination in the second shop => I have an error 500 on console when saving
[Products • 1764_1763.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4343765/Products.1764_1763.webm.zip)

After this [line](https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/controllers/front/ProductController.php#L303)
I edited this code
```
//Begin
            $order_products = [23];
            $showPrice = true;
            $assembler = new ProductAssembler($this->context);
            $presenterFactory = new ProductPresenterFactory($this->context);
            $presentationSettings = $presenterFactory->getPresentationSettings();
            $presenter = new ProductListingPresenter(
                new ImageRetriever(
                    $this->context->link
                ),
                $this->context->link,
                new PriceFormatter(),
                new ProductColorsRetriever(),
                $this->getTranslator()
            );
            $productsForTemplate = array();
            $presentationSettings->showPrices = $showPrice;
            if (is_array($order_products)) {
                foreach ($order_products as $productId) {
                    $productsForTemplate[] = $presenter->present(
                        $presentationSettings,
                        $assembler->assembleProduct(array('id_product' => $productId)),
                        $this->context->language
                    );
                }
            }

            print_r($productsForTemplate);exit;

            //End
```

In the FO => Product details => shop1
I have this result
[shop1_23-54-product.pdf](https://github.com/PrestaShop/PrestaShop/files/4343923/shop1_23-54-product.pdf)
`[cache_default_attribute] => Array ( [type] => variable [value] => 54 ) `
In the FO => Product details => shop2
I have this result
[shop2_23-56-product.pdf](https://github.com/PrestaShop/PrestaShop/files/4343928/shop2_23-56-product.pdf)
` [cache_default_attribute] => Array ( [type] => variable [value] => 56 )`

Thanks to check and feedback.

**Comment by gwyneblaidd** [comment]
@khouloudbelguith 
installing clean  PS to show how to reproduce properly, will note in next days

**Comment by khouloudbelguith** [comment]
@gwyneblaidd, thanks!
Waiting for your feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
