### ISSUE TITLE
I can't create a new product (The CSRF token is invalid. Please try to resubmit the form.)

### ISSUE THREAD

**Issue by Houmeid** [PrestaShop/PrestaShop#18165]
hey everyone i'm a begginer in prestashop

I've installed prestashop 1.7.6
When i go on the administration page, and i try to create a new product it doesn't works and it shows me an error The CSRF token is invalid. Please try to resubmit the form.
It seem like something went wrong cause even the administration page is not displayed correctly
And as @khouloudbelguith said, i've modify my php.ini file  to increase the max_input_vars from 1000 to 15000. But it still doesn't works.
thank u in advence for your help (and sorry for my bad english)

* PrestaShop version: 1.7.6
* PHP version: 7.3.13

**Comment by MarcelaNeira** [comment]
Me pasa exactamente igual y ya he modificado el php.ini y el  .htaccess y nada funciona, lo tengo instalado en local, he cambiado de versión de Pretashop pero sigue sin funcionar

**Comment by khouloudbelguith** [comment]
Hi @Houmeid,

Thanks for your report.
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by Houmeid** [comment]
Indeed, i've downgrade my php version to 7.2 and everything is fine now. Thanks @khouloudbelguith

**Comment by Houmeid** [comment]
@martaymarcela Bajé mi version de Php y todo està bien ahora

**Comment by khouloudbelguith** [comment]
@Houmeid, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by hamus1** [comment]
Bonjour,
j'ai remis la version de php comme explique mais le probleme est toujours le meme

**Comment by Houmeid** [comment]
Bonjour @hamus1. Dans mon cas, ce qui avait fonctionné c'était une réinitialisation de Php. Genre j'ai supprimé la version 7.3 puis j'ai installé la version 7.2.

**Comment by hamus1** [comment]
oui, c'est ce que j'ai fait et c'est toujours le meme soucis
![Capture d’écran 2020-06-16 à 1 34 37 PM](https://user-images.githubusercontent.com/55998752/84774813-409b4080-afd6-11ea-8cdf-970d0b7919d7.png)

**Comment by Houmeid** [comment]
Essayez alors de passer à php 7.1.x. Généralement d'après ca que j'ai pu lire sur différent forum, ce problème est lié à la version de php que vous avez installé. (quelle est la version de ps que vous utilisez ?) @hamus1

**Comment by hamus1** [comment]
La version de php est 7.2 comme sur la capture d'écran.

**Comment by Houmeid** [comment]
quelle est la version de Prestashop que vous avez installé, vous pouvez le verifier dans le coin supérieur gauche de votre interface d'administration. @hamus1

**Comment by hamus1** [comment]
1.7

**Comment by Houmeid** [comment]
Les version 1.7.0 à 1.7.3 de prestashop sont compatibles avec la version 7.1 de php 
Les versions 1.7.4 à 1.7.6 sont compatibles avec la version 7.2 de php. @hamus1

**Comment by hamus1** [comment]
Oui je sais, ma version prestashop est la toute dernière soit 1.7.6 et la j'ai fait l'upgrade de php depuis 7.1 vers la 7.2
J'ai redemarré le pc, le serveur mais le problème persiste

**Comment by Houmeid** [comment]
Je vois, dans ce cas, je vous invite à ouvrir un autre ticket (vu que celui ci est deja cloturé), et à décrire votre probleme plus en détail @hamus1

**Comment by AtomusEs** [comment]
Cool!! It worked for me! I downgrade from php v. 7.4 to 7.1 and it works!!
