### ISSUE TITLE
My website is down after migration

### ISSUE THREAD

**Issue by ArnasL** [PrestaShop/PrestaShop#18181]
```
Notice: tempnam(): file created in the system's temporary directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 249

Warning: rename(/tmp/class_index.phpyIYMSI,/var/www/MYDOMAIN.COM/public_html/app/cache/dev/class_index.php): No such file or directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 255

Notice: tempnam(): file created in the system's temporary directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 249

Warning: rename(/tmp/class_stub.php8qwTTo,/var/www/MYDOMAIN.COM/public_html/app/cache/dev/class_stub.php): No such file or directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 255

Notice: tempnam(): file created in the system's temporary directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 249

Warning: rename(/tmp/namespaced_class_stub.phpCyX1U4,/var/www/MYDOMAIN.COM/public_html/app/cache/dev/namespaced_class_stub.php): No such file or directory in /var/www/MYDOMAIN.COM/public_html/classes/PrestaShopAutoload.php on line 255

Warning: require_once(/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php): failed to open stream: No such file or directory in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86

Fatal error: require_once(): Failed opening required '/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php' (include_path='/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear_exception:/var/www/MYDOMAIN.COM/public_html/vendor/pear/console_getopt:/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear-core-minimal/src:/var/www/MYDOMAIN.COM/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86
```

I have changed my server to new one and I get this error when I try to open website front office or BO. I can't understand what's going on. My cache is disabled but I can see app/cache/prod folder. I don't even have app/cache/dev folder and I can't understand why system are looking for it (I deciding it by this error) Does anyone have idead how to fix it? Thanks in advance

#### Additional information

* PrestaShop version: 1.7.3.0
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ArnasL,

To move a Project to a new domain without errors, please follow these steps:

1. made a backup for my files & my database
2. upload my store's files to your new server
3. import the old store's database to the new server
4. In file /app/config/parameters.php, configure my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in Table ps_shop_url, change with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. clear the cache manually by deleting all the folder into app/cache (prod & dev).

=> OK => no problems.

Thanks to check & feedback.

**Comment by PululuK** [comment]
Hi @khouloudbelguith 

looking here:

_Fatal error: require_once(): Failed opening required '/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php' (include_path='/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear_exception:/var/www/MYDOMAIN.COM/public_html/vendor/pear/console_getopt:/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear-core-minimal/src:/var/www/MYDOMAIN.COM/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86_

I think this is clearly a cache issue !

@ArnasL 
**You can just runin your root prestashop  site folder :**
 
_php -d memory_limit=-1 ./bin/console cache:clear_

**Comment by khouloudbelguith** [comment]
@PululuK, yes!
It is the last step: `clear the cache manually by deleting all the folder into app/cache (prod & dev).`

Thanks!

**Comment by ArnasL** [comment]
> Hi @ArnasL,
> 
> To move a Project to a new domain without errors, please follow these steps:
> 
>     1. made a backup for my files & my database
> 
>     2. upload my store's files to your new server
> 
>     3. import the old store's database to the new server
> 
>     4. In file /app/config/parameters.php, configure my PrestaShop site.
>        4.1. DB_SERVER: database's server;
>        4.2. DB_NAME: Name of the database from step 5;
>        4.3. DB_USER: User associated with the database;
>        4.4. DB_PASSWD: The user's password;
> 
>     5. in Table ps_shop_url, change with the
>        5.1. domain => new domain
>        5.2. domain_ssl => new domain_ssl
>        5.3. physical_uri => new physical_uri
> 
>     6. clear the cache manually by deleting all the folder into app/cache (prod & dev).
> 
> 
> => OK => no problems.
> 
> Thanks to check & feedback.

The domain is the same, just a new server. I have deleted prod cache (dev doesn't even exist). I think this problem is related to permissions. Because I can't see cache/dev folder. Also missing /var/ folder. Does anyone can guide me how can I fix it?

**Comment by ArnasL** [comment]
> Hi @khouloudbelguith
> 
> looking here:
> 
> _Fatal error: require_once(): Failed opening required '/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php' (include_path='/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear_exception:/var/www/MYDOMAIN.COM/public_html/vendor/pear/console_getopt:/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear-core-minimal/src:/var/www/MYDOMAIN.COM/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86_
> 
> I think this is clearly a cache issue !
> 
> @ArnasL
> **You can just runin your root prestashop site folder :**
> 
> _php -d memory_limit=-1 ./bin/console cache:clear_

I get this response when I run this code:
`Could not open input file: ./bin/console`

**Comment by PululuK** [comment]
> > Hi @khouloudbelguith
> > looking here:
> > _Fatal error: require_once(): Failed opening required '/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php' (include_path='/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear_exception:/var/www/MYDOMAIN.COM/public_html/vendor/pear/console_getopt:/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear-core-minimal/src:/var/www/MYDOMAIN.COM/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86_
> > I think this is clearly a cache issue !
> > @ArnasL
> > **You can just runin your root prestashop site folder :**
> > _php -d memory_limit=-1 ./bin/console cache:clear_
> 
> I get this response when I run this code:
> `Could not open input file: ./bin/console`

Hi @AAymeric 
Sorry man !
For your Pretashop version you must use :
_php -d memory_limit=-1 ./app/console cache:clear_

**Comment by khouloudbelguith** [comment]
@ArnasL,

>Also missing /var/ folder. Does anyone can guide me how can I fix it?

For your PrestaShop version, the var folder doesn't exist
https://github.com/PrestaShop/PrestaShop/tree/1.7.3.0

Thanks!

**Comment by ArnasL** [comment]
> > > Hi @khouloudbelguith
> > > looking here:
> > > _Fatal error: require_once(): Failed opening required '/var/www/MYDOMAIN.COM/public_html/app/cache/dev/appParameters.php' (include_path='/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear_exception:/var/www/MYDOMAIN.COM/public_html/vendor/pear/console_getopt:/var/www/MYDOMAIN.COM/public_html/vendor/pear/pear-core-minimal/src:/var/www/MYDOMAIN.COM/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/MYDOMAIN.COM/public_html/config/bootstrap.php on line 86_
> > > I think this is clearly a cache issue !
> > > @ArnasL
> > > **You can just runin your root prestashop site folder :**
> > > _php -d memory_limit=-1 ./bin/console cache:clear_
> > 
> > 
> > I get this response when I run this code:
> > `Could not open input file: ./bin/console`
> 
> Hi @AAymeric
> Sorry man !
> For your Pretashop version you must use :
> _php -d memory_limit=-1 ./app/console cache:clear_

Getting this error now:

  [Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Cannot dump definition because of invalid class name (NULL)

**Comment by ArnasL** [comment]
Ok, but I still think prestashop can't create new files and folders after migration, how to recheck these privileges?

> @ArnasL,
> 
> > Also missing /var/ folder. Does anyone can guide me how can I fix it?
> 
> For your PrestaShop version, the var folder doesn't exist
> https://github.com/PrestaShop/PrestaShop/tree/1.7.3.0
> 
> Thanks!

Ok, but I still think prestashop can't create new files and folders after migration, how to recheck these privileges? When I delete prod folder in app/cache I think dev folder should be created but in my case it's not.

**Comment by ArnasL** [comment]
@PululuK anyway something happend after that line of code. Now I can see in FO maintenance mode On and in BO I see new error:


```
Whoops, looks like something went wrong.
1/1 RuntimeException in bootstrap.php.cache line 2802: Unable to write in the logs directory (/var/www/mydomain.com/public_html/app/logs)

    in bootstrap.php.cache line 2802
    at Kernel->buildContainer() in bootstrap.php.cache line 2757
    at Kernel->initializeContainer() in bootstrap.php.cache line 2533
    at Kernel->boot() in bootstrap.php.cache line 2564
    at Kernel->handle(object(Request), '1', false) in index.php line 86
```

**Comment by khouloudbelguith** [comment]
@ArnasL,

If you don't have access, you can check with your host to give the right permission.
Give the write and read access.
`$ chown -hR www-data:www-data ./Project_Folder_name`
Some hosts might require you to use` CHMOD 777`, although it is not recommended for anything more than a one-time need.
If you have to use CHMOD 777, make sure to switch to a safer setting (for instance, 775 for folders and 664 for files) once you are done upgrading.
Thanks to check & feedback.

**Comment by ArnasL** [comment]
Almost everything is fixed now. Thanks for everyone for help! Last thing which is not working, friendly SEO urls. Trying now debug this
I also changed my PHP version to 7.0 from 7.2 because of a lot of incompatibility.

**Comment by ArnasL** [comment]
mod_rewrite is enabled I don't have any idea why it's not working
Here is my presta info
https://www.dropbox.com/s/welm6m1qya9erjo/Screenshot%202020-03-17%2022.14.46.png?dl=0

**Comment by khouloudbelguith** [comment]
@ArnasL, `mod_rewrite` is a useful Apache module that can be used effectively to ensure human-readable URLs.
First, we need to activate `mod_rewrite`. It’s available but not enabled with a clean Apache 2 installation.
`sudo a2enmod rewrite`
You need to change the default Apache configuration file
```
<VirtualHost *:80>
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

    . . .
</VirtualHost>
```

For more details, thanks to check with your host and feedback.

**Comment by ArnasL** [comment]
Yes, now all good, problem solved. Thanks

**Comment by khouloudbelguith** [comment]
@ArnasL, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!
