### ISSUE TITLE
Error in select input backend

### ISSUE THREAD

**Issue by sergicp** [PrestaShop/PrestaShop#18187]
In backend of prestashop, when you click (for example in translations) on the select input merge the word "select" with "id = ..." (selectid="idofclass...") and the selects do not display well.

Version 1.7.6.4 stable.

Any solution? Thank you.

**Comment by khouloudbelguith** [comment]
Hi @sergicp,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sergicp** [comment]
server setup and configuration:

Linux #1 SMP Thu Oct 27 07:16:29 CEST 2016 x86_64

Versión del software del servidor: Apache

Versión PHP: 7.4.3

Memory limit: 1024M

T. Max Execution: 600

Max filesize upload: 1024M

PrestaShop version (source): 1.7.6.4

debug mode report: No errors

PHP error logs: No errors

apache error log: No errors

javascript console log: No errors

screenshots:

![Imagen1](https://user-images.githubusercontent.com/62307885/76943397-91c86500-68ff-11ea-8f4f-1ff22ce291a2.png)
![Imagen4](https://user-images.githubusercontent.com/62307885/76943402-93922880-68ff-11ea-9b29-2de32694b400.png)

THANKS¡¡

**Comment by khouloudbelguith** [comment]
@sergicp, PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by sergicp** [comment]
Change to PHP 7.2 and solved

Thank¡¡

**Comment by khouloudbelguith** [comment]
@sergicp, Great!
Feel free to open a new one when needed.

Thanks!
