### ISSUE TITLE
BO - New order page - an exception is displayed when we double click on the "Add to cart" button

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18199]
#### Describe the bug

In the BO => New order page (migrated), an exception is displayed when we double click on the "Add to cart" button.
![image](https://user-images.githubusercontent.com/16067358/76964515-26908a00-6923-11ea-8dcb-99bce0769a95.png)

#### Expected behavior

The quantity of the product must be increased and no exception displayed.
We can click on the "Add to cart" button multiple times.
It is Ok on the legacy page.

#### Steps to Reproduce

1. Go to BO => Order page `shop.com/admin-dev/sell/orders/orders`
2. Click on `Add new order` button
3. Choose a customer
4. Search for a product
5. Click add to cart => OK
6. Click add to cart again
7. see error

**Screenshots**
[Untitled_ Mar 18, 2020 2_22 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4349168/Untitled_.Mar.18.2020.2_22.PM.webm.zip)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18208
