### ISSUE TITLE
1-click upgrade module: Upgrade button not working

### ISSUE THREAD

**Issue by Pasc00l** [PrestaShop/PrestaShop#18193]
Hello,

I have installed the 1-click upgrade module to upgrade my prestashop 1.7.1.2 to 1.7.6
The module installation was ok but when I click on the upgrade button, nothing happens.

All verified points are ok excepted a warning on the max-execution-time that is on 300 seconds at the moment. But as I have a mutualized hosting at ovh, I cannot change this value.

Please could you help ?

Thank you very much
Pascal

**Comment by khouloudbelguith** [comment]
Hi @Pasc00l,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - 1-click upgrade version
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Pasc00l** [comment]
Hello,

I have a mutualized hosting so I don't have access to all logs...
The module version is 4.10.1

Anyway here are some information...

My configuration:

INFORMATIONS SUR VOTRE SERVEUR
Informations du serveur : Linux #1 SMP Wed Nov 13 11:24:26 CET 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.1.32

Limite de mémoire : 512M

Temps maximal d'exécution : 300

Taille max. pour envoi de fichiers : 128M

INFORMATIONS SUR LA BASE DE DONNÉES
Version de MySQL : 5.6.46-log

Serveur MySQL : spacedogshop.mysql.db:3306

Nom MySQL : spacedogshop

Utilisateur MySQL : spacedogshop

Préfixe des tables : pre5248_

Moteur MySQL : InnoDB

Connecteur MySQL : DbPDO

 INFORMATIONS DE LA BOUTIQUE
Version de PrestaShop : 1.7.1.2

URL de la boutique : http://www.novomeo.fr/shop/

Thème actif : PRS036

 INFORMATIONS SUR LA CONFIGURATION MAIL
Méthode d'envoi d'e-mails : Vous utilisez la fonction mail() de PHP

 VOS INFORMATIONS
Votre navigateur : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

 VÉRIFIEZ VOTRE CONFIGURATION
Paramètres requis : ok

Paramètres optionnels : ok



I found in the error log some lines about the upgrade

(index.shtml,index.htm,index.html,index.cgi,index.php3,index.php,index.wml,index.asp,index.php4,index.php5,index.php6) found, and server-generated directory index forbidden by Options directive
[Tue Mar 17 16:33:30 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 16:33:30 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 16:33:30 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:05 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:05 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:05 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?tab=AdminSelfUpgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:37 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:37 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:07:37 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:13 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:13 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:13 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:33 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:33 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67
[Tue Mar 17 17:08:33 2020] [error] [client 35.157.180.241] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=686402587bd987590e0ea130285e9f67


And in the chrome console I see also some errors

[DOM] Found 2 elements with non-unique id #addons_login_button: (More info: https://goo.gl/9p2vKq) <button id=​"addons_login_button" class=​"btn btn-primary btn-block btn-lg" type=​"submit">​…​</button>​ <button id=​"addons_login_button" class=​"btn btn-primary btn-block btn-lg" type=​"submit">​…​</button>​
index.php?controller=AdminSelfUpgrade&token=79694f6f846b82fb5f39c2db94570301:1 [DOM] Found 2 elements with non-unique id #addons_login_form: (More info: https://goo.gl/9p2vKq) <form id=​"addons_login_form" method=​"post">​…​</form>​ <form id=​"addons_login_form" method=​"post">​…​</form>​
index.php?controller=AdminSelfUpgrade&token=79694f6f846b82fb5f39c2db94570301:1 [DOM] Found 2 elements with non-unique id #password_addons: (More info: https://goo.gl/9p2vKq) <input id=​"password_addons" name=​"password_addons" type=​"password" value autocomplete=​"off" class=​"form-control ac_input">​ <input id=​"password_addons" name=​"password_addons" type=​"password" value autocomplete=​"off" class=​"form-control ac_input">​
index.php?controller=AdminSelfUpgrade&token=79694f6f846b82fb5f39c2db94570301:1 [DOM] Found 2 elements with non-unique id #username_addons: (More info: https://goo.gl/9p2vKq) <input id=​"username_addons" name=​"username_addons" type=​"text" value autocomplete=​"off" class=​"form-control ac_input">​ <input id=​"username_addons" name=​"username_addons" type=​"text" value autocomplete=​"off" class=​"form-control ac_input">​
jquery-1.11.0.min.js:4 POST http://www.novomeo.fr/shop/admin1108/autoupgrade/ajax-upgradetab.php 500 (Internal Server Error)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
refreshChannelInfos @ upgrade.js:130
(anonymous) @ upgrade.js:125
dispatch @ jquery-1.11.0.min.js:3
r.handle @ jquery-1.11.0.min.js:3
trigger @ jquery-1.11.0.min.js:3
e.event.trigger @ jquery-migrate-1.2.1.min.js:2
(anonymous) @ jquery-1.11.0.min.js:3
each @ jquery-1.11.0.min.js:2
each @ jquery-1.11.0.min.js:2
trigger @ jquery-1.11.0.min.js:3
n.fn.<computed> @ jquery-1.11.0.min.js:4
(anonymous) @ upgrade.js:236
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
jquery-1.11.0.min.js:4 POST http://www.novomeo.fr/shop/admin1108/autoupgrade/ajax-upgradetab.php 500 (Internal Server Error)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ upgrade.js:626
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
jquery-1.11.0.min.js:4 POST http://www.novomeo.fr/shop/admin1108/autoupgrade/ajax-upgradetab.php 500 (Internal Server Error)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ upgrade.js:687
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
2jquery-1.11.0.min.js:4 POST http://www.novomeo.fr/shop/admin1108/autoupgrade/ajax-upgradetab.php 500 (Internal Server Error)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
doAjaxRequest @ upgrade.js:429
(anonymous) @ upgrade.js:537
dispatch @ jquery-1.11.0.min.js:3
r.handle @ jquery-1.11.0.min.js:3

**Comment by khouloudbelguith** [comment]
@Pasc00l,

In order to avoid problems during the upgrade, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

You have this error
>jquery-1.11.0.min.js:4 POST http://www.novomeo.fr/shop/admin1108/autoupgrade/ajax-upgradetab.php 500 (Internal Server Error)

The browser displays a 500 Internal Server Error.
![image](https://user-images.githubusercontent.com/16067358/76952291-2a191680-690d-11ea-85ba-cc2e6b87e5d4.png)
You need to turn on the Debug mode on PrestaShop 1.7, follow these steps:

- Got to Advanced Parameters > Performance
- In the Debug Mode section, set “Debug Mode” to “Yes”.
- Click the “Save” button.

If you can’t access your dashboard, you can still enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

Thanks to check and feedback.

**Comment by Pasc00l** [comment]
Hello,

The debug mode is already activated and I have access to the dashboard.

**Comment by khouloudbelguith** [comment]
@Pasc00l, could you please try to re-install the `autoupgrade` module with removing the folder, clear cache manually by deleting all the folder into var/cache (prod & dev), check and feedback.

Thanks!

**Comment by Pasc00l** [comment]
Hello 
I did it but as I told I have a mutualized hosting, and thus I have no access to the var folder of the server
The same error occurs

**Comment by khouloudbelguith** [comment]
@Pasc00l,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4353237/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by Pasc00l** [comment]
I have installed the file: http://www.novomeo.fr/shop/phppsinfo.php

![image](https://user-images.githubusercontent.com/8983725/77057787-c6f2b700-69d4-11ea-824d-87a2c99ed1f7.png)

**Comment by khouloudbelguith** [comment]
@Pasc00l, the `mod_rewrite` is not enabled in your case?
It is required.
![image](https://user-images.githubusercontent.com/16067358/77061401-75e5c180-69da-11ea-8cd6-fe336fb598d1.png)

Thanks to check and feedback.

**Comment by Pasc00l** [comment]
I have checked with OVH and the mod_rewrite is activated in Apache for my shared hosting
https://apache.cloudweb-infos.hosting.ovh.net/

Maybe is it a question of htaccess file ?
For info my prestashop is installed into /www/novomeo/shop

**Comment by khouloudbelguith** [comment]
@Pasc00l, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Pasc00l** [comment]
this file is present but empty

**Comment by khouloudbelguith** [comment]
@Pasc00l, thanks to provide me file logs into the folder `/Project_Folder/var/logs/`.

Thanks!

**Comment by Pasc00l** [comment]
[log-errors-18-03-2020.log.gz.txt](https://github.com/PrestaShop/PrestaShop/files/4355190/log-errors-18-03-2020.log.gz.txt)
[spacedogsoftware.com-18-03-2020.log.gz.txt](https://github.com/PrestaShop/PrestaShop/files/4355192/spacedogsoftware.com-18-03-2020.log.gz.txt)

**Comment by khouloudbelguith** [comment]
@Pasc00l, are there any PHP caching modules enabled in your case?
You have those errors:
`[Wed Mar 18 22:59:18 2020] [error] [client 207.46.13.128] [host novomeo.be] AH01630: client denied by server configuration: /homez.742/spacedog/www/novomeo/.htaccess`
=>This is a permission issue on your server.

`[Wed Mar 18 13:47:20 2020] [error] [client 95.182.150.166] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=79694f6f846b82fb5f39c2db94570301`
=> I think it will come from timeout.

Thanks to check with your host and feedback.

**Comment by Pasc00l** [comment]
I don't know if it's a time out, the error 500 appears directly after the click.
Here is the htaccess file of the shop folder ,do you need the htaccess of the upper folders ?

# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>

RewriteEngine on


#Domain: www.novomeo.fr
RewriteRule . - [E=REWRITEBASE:/shop/]
RewriteRule ^api$ api/ [L]

RewriteRule ^api/(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType application/font-woff2 .woff2
<IfModule mod_headers.c>
    <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /shop/index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again

**Comment by khouloudbelguith** [comment]
@Pasc00l, you are using Apache, so the `.htaccess` file is generated automatically by PrestaShop.
You can regenerate the file `.htaccess` following these steps:

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by khouloudbelguith** [comment]
@Pasc00l,

>I don't know if it's a time out, the error 500 appears directly after the click.

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Thanks!

**Comment by Pasc00l** [comment]
Hello, I did it the htaccess has been regenerated but it does not solve the issue

**Comment by khouloudbelguith** [comment]
@Pasc00l, did you check the issue with your host? as described [here](https://github.com/PrestaShop/PrestaShop/issues/18193#issuecomment-601239728)?

Thanks to check with your host and feedback.

**Comment by Pasc00l** [comment]
Hello,
If did the regeneration of the htaccess but still the same.
What do I have to check now ?

**Comment by khouloudbelguith** [comment]
@Pasc00l,

>`[Wed Mar 18 13:47:20 2020] [error] [client 95.182.150.166] [host www.novomeo.fr] End of script output before headers: ajax-upgradetab.php, referer: http://www.novomeo.fr/shop/admin1108/index.php?controller=adminselfupgrade&token=79694f6f846b82fb5f39c2db94570301`
=> I think it will come from timeout.

it is a server issue not related to .htaccess file.

Thanks to check with your host about this error and feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
