### ISSUE TITLE
Add a warning when registering a product activated at €0

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18203]
#### Is your feature request related to a problem?

I can publish an enabled product at 0€ in the Front Office. I can be annoying to handle.

#### Describe the solution you'd like

Add a notification to warn the merchant that he will publish a product at 0€.

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

What's this improvement's status? is it **`TBS`** or **`ToDo`**?

Thanks!
