### ISSUE TITLE
Inconsistency in the exibition of products with combinations having minimal quantities

### ISSUE THREAD

**Issue by amaurigabriel** [PrestaShop/PrestaShop#18209]
Hi,

I have a product with two combinations, one of them with minimal_quantity of 25 and the other with minimal_quantity of 1 (check the product [here](https://php72.paradadigital.com.br/acessorios-para-casa/10-25-brown-bear-cushion.html)).

If I set the combination **Cor: Branco**, the quantity input is set to 25, as expected. If I change back to combinaton **Cor: Preto** the input is set to 1. I don't think this is the expected behavior, but even if this is intended, the request used to render the product info send the parameter **quantity_wanted=25**. If the quantity input is set to 1, the parameter **quantity_wanted** should be 1 as well.

We have a module that uses this hook to display information based in the quantity wanted by the user. As the parameter **quantity_wanted** is **25** but the quantity input is rendered with **1**, the information displayed by our module became inconsistent.

![image](https://user-images.githubusercontent.com/1836086/76978224-330de600-6915-11ea-9e99-0ded1215ca51.png)
![image](https://user-images.githubusercontent.com/1836086/76978274-428d2f00-6915-11ea-98fa-e509528ab9b6.png)

If I change back to **Cor: Branco** we have the same unexpected behavior. The hook tell us that the customer want **1** units of the product, but the input is rendered with **25**.

This issue only happens in PS Version >= 1.7.6.

**Comment by khouloudbelguith** [comment]
Hi @amaurigabriel,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.4, and the branch 1.7.7.x.
[Untitled_ Mar 19, 2020 12_17 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4354131/Untitled_.Mar.19.2020.12_17.PM.webm.zip)
But I think, it is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/14744

Thanks to check & feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by amaurigabriel** [comment]
Hi @sarahdib ..

Sorry but what additional details do you need from me? I don't know if this is the same error reported in #14744... I just found this unexpected behavior.
