### ISSUE TITLE
BO - Filter doesn't work in the Categories page and the Employees - an exception displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18218]
#### Describe the bug

In the BO => Catalog => Categories page & the BO => Team => Employees page,
when we try to search by any filter => an exception is displayed

1. In the BO => Catalog => Categories page 
![image](https://user-images.githubusercontent.com/16067358/77060157-6c5b5a00-69d8-11ea-9a48-0b7ead70ec0c.png)
2. In the BO => Team => Employees page
![image](https://user-images.githubusercontent.com/16067358/77060205-7da46680-69d8-11ea-918a-ba279663fd47.png)

#### Steps to Reproduce

1. Go to BO => Catalog => Categories page
2. Search by any filter
3. See error
4. Go to BO => Team => Employees page
5. Search by any filter
6. See error

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by SimonGrn** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/pull/18130 ?

**Comment by Progi1984** [comment]
Fixed by #18228
