### ISSUE TITLE
Shipping method choice is displayed when a cart contains a pack of virtuals products

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18215]
#### Describe the bug

If we add only virtual product to the cart and checkout the "shipping method choice" is not displayed that's the good behaviour . But if the virtuals products are in a pack the "shipping method choice" is displayed

#### Expected behavior

As the pack contains only virtual products therefore the cart contains only virtual products and the choice of delivery method should not be displayed

#### Steps to Reproduce

1. Go to BO and create a pack that contains only virtuals products
2. Go to FO and add the previously created pack in the cart and proceed to checkout

**Screenshots**

![virtuals product pack cart issue](https://user-images.githubusercontent.com/40635814/77057901-f86b8280-69d4-11ea-9ce2-1cadd24976bb.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I have the same issue with PS1.7.5.2 and PS1.7.6.4.
@SD1982, it is not a regression, I will remove the 1.7.7.0 milestone.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment]
Thanks for your report @SD1982 ! Yes you're right @khouloudbelguith we should remove it from 177 kanban. Thanks !

**Comment by NeOMakinG** [comment]
Need backend logic and a condition inside the template (it's mainly backend stuff)

**Comment by florine2623** [comment]
Maybe related to https://github.com/PrestaShop/PrestaShop/issues/24850
