### ISSUE TITLE
Error while update from 1.7.5.1 to 1.7.6.4 with 1-Click module

### ISSUE THREAD

**Issue by Tim74330** [PrestaShop/PrestaShop#18212]
Hello,

I tried to update a shop running version 1.7.5.1 with the 1-Click module.
Files are updated correctly, but when it comes to the db update an error occurs 

[INTERNAL] /homepages/20/d650581117/htdocs/boutique/admin817horzu1/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null #0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #1 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array) #2 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') #3 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...') #4 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.5.1') #5 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.5.1') #6 /homepages/20/d650581117/htdocs/boutique/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /homepages/20/d650581117/htdocs/boutique/admin817horzu1/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}

the last operation before the crash is 
[OK] SQL 1.7.6.0 ALTER TABLE `ps_currency` ADD `precision` int(2) NOT NULL DEFAULT 6 AFTER `numeric_iso_code`
[OK] SQL 1.7.6.0 ALTER TABLE `ps_currency` ADD KEY `currency_iso_code` (`iso_code`)
[DROP] SQL `ps_currency_lang` table has been dropped.
[OK] SQL 1.7.6.0 /* Localized currency information */ CREATE TABLE `ps_currency_lang` ( `id_currency` int(10) unsigned NOT NULL, `id_lang` int(10) unsigned NOT NULL, `name` varchar(255) NOT NULL, `symbol` varchar(255) NOT NULL, PRIMARY KEY (`id_currency`,`id_lang`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8

On 1&1 server, with PHP 7.3
Can you help me please ?
Thanks

**Comment by khouloudbelguith** [comment]
Hi @Tim74330,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by Tim74330** [comment]
Hi @khouloudbelguith ,

I have downgrade the php version on 7.2, But i have the same error.

Do you have an idea please ?

**Comment by khouloudbelguith** [comment]
@Tim74330, after downgrading the PHP version, Did you make a rollback for your backup and check the upgrade again?

Thanks!

**Comment by Tim74330** [comment]
Yes, i have restore all files and database, and i use the 1clicupgrade again. 
The result is the same..

**Comment by khouloudbelguith** [comment]
@Tim74330, what is the exact version of the 1-click upgrade did you use?

Thanks!

**Comment by Tim74330** [comment]
It's the V4.6.0
On the backoffice, it is indicated that it is up to date, but I see that the last version on the prestashop site is the v4.10.1 !

I imagine that it should be updated?

Thanks.

**Comment by khouloudbelguith** [comment]
@Tim74330, yes!
It is an old version => you should update your version to 4.10.1.
Issue reported here:https://github.com/PrestaShop/PrestaShop/issues/15194 

Thanks!

**Comment by Tim74330** [comment]
It is working now !!

I'm sorry for the inconvenience, I should have checked this before !

Thanks you so much.

**Comment by khouloudbelguith** [comment]
@Tim74330, you are welcome!
Feel free to open a new one when needed.

Thanks!
