### ISSUE TITLE
Excluding products from categories in the discount code does not work

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#18211]
Hi,
PS 1.7.6.4
PHP 7.2

1) Make discount code SALE
2) Exclude Category One from disctount
3) Add **Product One** from **Category One** to the cart
4) Add Product Two from Category Two to the cart
5) Apply SALE code
6) Code is applied to both products but should not be applied to the Product One from Category One that was excluded from the discount exception.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Thanks for your report.
You should apply a discount to Selected product(s).
![image](https://user-images.githubusercontent.com/16067358/77056651-015b5480-69d3-11ea-9639-13e4b4a264d2.png)

Thanks to check & feedback.

**Comment by Betafer** [comment]
<img width="1003" alt="Schermata 2020-03-19 alle 11 18 39" src="https://user-images.githubusercontent.com/5024055/77056899-6b73f980-69d3-11ea-8d3e-c383e7ac9048.png">

**Comment by ghost** [comment]
:O wow sorry for my ignorance!

**Comment by khouloudbelguith** [comment]
@PrestaShark, feel free to open a new one when needed.

Thanks!

**Comment by ghost** [comment]
But... when Product One is also in Category One and Category Three (not in exception) then discount apply.

**Comment by khouloudbelguith** [comment]
@PrestaShark, it is normal behavior, the product belongs to a selected category of product's restriction => so the cart rule is applied.
But we have a related issue added to our bug roadmap.
https://github.com/PrestaShop/PrestaShop/issues/15525

Thanks!!

**Comment by khouloudbelguith** [comment]
@PrestaShark, can we close the issue?

Thanks!
