### ISSUE TITLE
ApplyProductCalculation and ProductlazyArray variable mismatch

### ISSUE THREAD

**Issue by jonasburneika** [PrestaShop/PrestaShop#18225]
If you want to display product availability in the cart, and show availability_message, it returns the wrong text. Like it always has the in-stock product, it doesn't show the message for available_later text. My client had products where the stock was 0. But in the cart, it displays an "in stock" label.

I tried it in PS 1.7.6.2 version. 
Long story short :D 
src/Adapter/Presenter/Product/ProductLazyArray.php:773 line always gets $product['quantity'] more than 0. In Cart class applyProductCalculations() method is clearly visible, that $product['quantity'] is overwriten by cart_quantity. 

`    protected function applyProductCalculations($row, $shopContext, $productQuantity = null)
    {
        if (null === $productQuantity) {
            $productQuantity = (int) $row['cart_quantity'];
        }

        if (isset($row['ecotax_attr']) && $row['ecotax_attr'] > 0) {
            $row['ecotax'] = (float) $row['ecotax_attr'];
        }

        $row['stock_quantity'] = (int) $row['quantity'];
        // for compatibility with 1.2 themes
        $row['quantity'] = $productQuantity;`
So in ProductLazyArray.php we need to take **stock_quantity instead** of **quantity**

#### Expected behavior
In cart show product availability when out of stock with the allowed order option. like _Delivery in 10-15days.

#### Steps to Reproduce

add product with 0 quantity, select Allow orders. 
Set Label when out of stock.
Add 
```
    {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
``` 
in `templates/checkout/_partials/cart-detailed-product-line.tpl`

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by jonasburneika** [comment]
My pull request: https://github.com/PrestaShop/PrestaShop/pull/18226

**Comment by khouloudbelguith** [comment]
Hi @jonasburneika,

I think your issue is related to this improvement: https://github.com/PrestaShop/hummingbird/issues/839
Is it?
>Add `{block name='product_availability'}` in `templates/checkout/_partials/cart-detailed-product-line.tpl`

I have an exception in the FO
![image](https://user-images.githubusercontent.com/16067358/77082034-d3d6d100-69fb-11ea-8664-44bafd055331.png)

Thanks to check and feedback.

**Comment by jonasburneika** [comment]
@khouloudbelguith yes this is relevent to your sugested issue. And sorry I mean to add this code:

```
    {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
```

**Comment by khouloudbelguith** [comment]
@jonasburneika, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2
In the BO => The product is out stock with Allow orders
![image](https://user-images.githubusercontent.com/16067358/77087876-efde7080-6a03-11ea-9c54-385d5077bc87.png)

In the FO => Product details page => OK
![image](https://user-images.githubusercontent.com/16067358/77088987-85c6cb00-6a05-11ea-8f40-bbc6d40f8075.png)

In the Shopping cart page => the product_availability is incorrect
![image](https://user-images.githubusercontent.com/16067358/77089059-9e36e580-6a05-11ea-83a9-167a161ca03d.png)

I’ll add this to the debug roadmap.

Thanks!
