### ISSUE TITLE
[ORDER PAGE] Display correction - 2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18236]
New front-end enhancements to improve the order page
## Part 2 

- [x] In the mobile view, the product block is on the bottom of the page, below the message block. 

To prevent merchants from scrolling down the page to check their order, we should move up the product block below the customer block.

- [x] The currency selector in the payment block takes up the entire width of the column which reduces the size of the next column. The selector should have the size of its contents.

- [x] when adding a product, the buttons are not aligned
![image](https://user-images.githubusercontent.com/43613217/77091476-e7d4ff80-6a08-11ea-9829-af24d5651be7.png)
- [x] when adding a product, the quantity background color is not round
- [x] on tablet view, add a product and add a discount overlap
![image](https://user-images.githubusercontent.com/43613217/77091851-6893fb80-6a09-11ea-89f6-e8e40dec1b8e.png)
- [x] the contour of the status block is not quite like the others one: radius and shadow are missing.
- [x] To make tabs from the status, carrier... block scrollable instead of overlapping tabs on mobile view
- [x] The spacing between the vertical blocks must be 30px
- [x] Order listing, we still have the spacing from the hidden dropdown button in the status label

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18329
