### ISSUE TITLE
Possibility to add multiple time the same product in an order view page

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18237]
#### Describe the bug

On a order view it is possible to add multiple time the same product and it's not cumulated to the first added a new (same) product is added

#### Expected behavior

When adding again a product in a order the only the quantity should be updated

#### Steps to Reproduce

1. Go to BO => sell => orders
2. Select any order and click on view
3. On the view order page add a new product
4. Now add the same product added before

**Screenshots**
![multiple time added product](https://user-images.githubusercontent.com/40635814/77155762-4f895a00-6a9e-11ea-9d96-391fce2a3d81.png)

**Screenrecord**
https://drive.google.com/file/d/1xJ5hflon-UT9KaAgNfgb2D3OnBo-x-r1/view?usp=sharing

#### Additional information
* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

Same issue with PS1.7.6.4, PS1.7.5.2, and the branch 1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/77322301-d09d5700-6d13-11ea-85bd-3dd0717db5a2.png)

PS: the Available quantity is not updated immediately => if we refresh the page => it will be OK.

![image](https://user-images.githubusercontent.com/16067358/77322394-f296d980-6d13-11ea-8c1a-513b44f336df.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20145
