### ISSUE TITLE
[IMPROVEMENT] Possibility to give gift with every product, that fits the voucher

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18241]
#### Is your feature request related to a problem?
We came across this situation last week at our store. We wanted to make a promotion and give some gifts to every product of some type bought. For example, a free soundbar to every TV.

So, I made a cart rule, I limited it to specific products.
You add it to cart, you get the gift.

**BUT, you add a second TV, you don't get another piece of the gift.**
**BUT, you add a different TV, you don't get another piece of the gift.**

#### Describe the solution you'd like

Would it be possible to add a feature, if the merchants want to:
_give only 1 piece of gift per cart rule_ (current situation)
OR
_give a piece of gift for every product that applies to that cart rule?_

**Comment by MatShir** [comment]
Hi @Hlavtox,
One workaround you could apply:
- Create a non-displayed category called TV for example
- Go in cart rule, select in Condition, the category TV in product selection
- Then apply free gifts in action. 
- Add the product you want to have a gift with to the category TV

Try it out, tell what you think :) 

Thanks for your report anyway. The workaroud is not the best solution. Your feature has been shared with our product team.

**Comment by Hlavtox** [comment]
@MatShir Oh, maybe on the second read, I expressed myself badly. It adds the gift to the cart just fine. But it always applies the cart rule just once, understand?

Only workaround would be to have one cart rule for each product. And even then, it wouldn't add a second piece if you added 2 pieces of the same product to cart.

**Comment by MatShir** [comment]
Hi @Hlavtox,
Actually, I'm the one who read too fast, my apologies. Except for pack products, indeed you can't add a gift for each product, it is only one per cart.

**Comment by Hlavtox** [comment]
@MatShir Like, you can just write it to the short description, but it's necessary (or at least very very good) to have the gift in the order. For organizational purposes, reducing stock, invoicing etc.

Our temporary solution:
NOT **Free soundbar to every TV** BUT **Order any TV and get a soundbar for free** 😄
