### ISSUE TITLE
Unable to clone git repository

### ISSUE THREAD

**Issue by presteus** [PrestaShop/PrestaShop#18247]
#### Describe the bug

Unable to clone prestashop repository.

#### Expected behavior

Cloning repository.

#### Steps to Reproduce

1. git clone -b develop --depth 1 https://github.com/PrestaShop/PrestaShop.git

**Results**

```shell
git clone -b develop --depth 1 https://github.com/PrestaShop/PrestaShop.git
Cloning into 'PrestaShop'...
remote: Enumerating objects: 12056, done.
remote: Counting objects: 100% (12056/12056), done.
remote: Compressing objects: 100% (9253/9253), done.
remote: Total 12056 (delta 5018), reused 6255 (delta 2325), pack-reused 0
Receiving objects: 100% (12056/12056), 20.39 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (5018/5018), done.
fatal: cannot create directory at 'tests-legacy/Unit/classes': File exists
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

#### Additional information

* Debian buster
* PHP version: 7.3-fpm
* PrestaShop version: git develop version

**Comment by presteus** [comment]
I solved the problem by setting git config **ignorecase** property to **true**
`git config --global core.ignorecase true`

I think the documentation should reflect this for case-sensitive filesystem.

**Comment by matks** [comment]
> I solved the problem by setting git config **ignorecase** property to **true**
> `git config --global core.ignorecase true`
> 
> I think the documentation should reflect this for case-sensitive systems.

Thanks for telling us. The documentation is an open source repository, do you feel like adding your statement into it ? (see https://github.com/PrestaShop/docs)

Else I'll do it, but this is an opportunity to become a contributor 😉

**Comment by presteus** [comment]
> 
> 
> > I solved the problem by setting git config **ignorecase** property to **true**
> > `git config --global core.ignorecase true`
> > I think the documentation should reflect this for case-sensitive systems.
> 
> Thanks for telling us. The documentation is an open source repository, do you feel like adding your statement into it ? (see https://github.com/PrestaShop/docs)
> 
> Else I'll do it, but this is an opportunity to become a contributor 😉

PR send :)
https://github.com/PrestaShop/docs/pull/491

**Comment by presteus** [comment]
Hello,

Today I have launch my docker with the workaround with a system prune but the workaround stop to work.

```shell script
# Reset docker
docker system prune -af
docker-compose up
```
Result:
```shell script
+ git clone -b develop --depth 1 https://github.com/PrestaShop/PrestaShop.git .
Cloning into '.'...
remote: Enumerating objects: 12069, done.
remote: Counting objects: 100% (12069/12069), done.
remote: Compressing objects: 100% (8111/8111), done.
remote: Total 12069 (delta 5110), reused 7599 (delta 3480), pack-reused 0
Receiving objects: 100% (12069/12069), 20.06 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (5110/5110), done.
fatal: cannot create directory at 'tests-legacy/Unit/classes': File exists
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Git config:
```shell script
git config --global -l
user.name=developer
user.email=developer@prestashop.local
core.ignorecase=true
```

It is possible to explain me why the directory **tests-legacy/Unit** have 2 directory **classes** and **Classes** before I analyze this problem ?

Thanks by advance.

N.B: I will publish my docker soon to  help.

**Comment by matks** [comment]
> It is possible to explain me why the directory **tests-legacy/Unit** have 2 directory **classes** and **Classes** before I analyze this problem ?

I'm afraid the people who created these 2 directories and the obvious confusion between them are long gone. So we'll never know if there was a valid reason.

However I see tests-legacy/Unit/classes contains only 1 unit tests. So we could move it into tests-legacy/Unit/Classes and get rid of the confusion quite easily.

**Comment by presteus** [comment]
Hi,

You can find the docker image at https://github.com/presteus/.prestashop-18247. The image is based on **7.3-fpm-buster** but i have test with **7.3-fpm-stretch** and the error happens too.

N.B: On Windows, the problem do not appears.

**Comment by khouloudbelguith** [comment]
Hi @presteus,

I have an error in the Step 7/12
```
Step 7/12 : RUN set -eux;     apt-get install -y         libfreetype6-dev         libicu-dev         libjpeg62-turbo-dev         libxml2-dev         libzip-dev         wget         unzip         git         npm     && docker-php-ext-configure gd         --with-freetype-dir=/usr/include         --with-jpeg-dir=/usr/include     && docker-php-ext-configure zip         --with-libzip=/usr/include     && docker-php-ext-install         bcmath         exif         gd         iconv         intl         mysqli         pdo_mysql         soap         zip     && apt-get remove -y --purge         libfreetype6-dev         libicu-dev         libjpeg62-turbo-dev         libxml2-dev         libzip-dev     && npm cache clean -f     && npm install -g n     && n 8.17.0
 ---> Running in 2533f911d5d2
+ apt-get install -y libfreetype6-dev libicu-dev libjpeg62-turbo-dev libxml2-dev libzip-dev wget unzip git npm
Reading package lists...
Building dependency tree...
Reading state information...
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libfreetype6-dev
E: Unable to locate package libicu-dev
E: Unable to locate package libjpeg62-turbo-dev
E: Unable to locate package libxml2-dev
E: Unable to locate package libzip-dev
E: Unable to locate package wget
E: Unable to locate package unzip
E: Package 'git' has no installation candidate
E: Unable to locate package npm
ERROR: Service 'issue_18247_php' failed to build: The command '/bin/sh -c set -eux;     apt-get install -y         libfreetype6-dev         libicu-dev         libjpeg62-turbo-dev         libxml2-dev         libzip-dev         wget         unzip         git         npm     && docker-php-ext-configure gd         --with-freetype-dir=/usr/include         --with-jpeg-dir=/usr/include     && docker-php-ext-configure zip         --with-libzip=/usr/include     && docker-php-ext-install         bcmath         exif         gd         iconv         intl         mysqli         pdo_mysql         soap         zip     && apt-get remove -y --purge         libfreetype6-dev         libicu-dev         libjpeg62-turbo-dev         libxml2-dev         libzip-dev     && npm cache clean -f     && npm install -g n     && n 8.17.0' returned a non-zero code: 100

```
![image](https://user-images.githubusercontent.com/16067358/77642410-e4d49480-6f5d-11ea-86cc-1d111feb9a46.png)


Thanks!

**Comment by presteus** [comment]
That's weird, I running this actually.
Do you run on Windows or Linux ?

**Comment by khouloudbelguith** [comment]
@presteus, Debian GNU/Linux 8 (jessie) 64 bits

Thanks!

**Comment by presteus** [comment]
I see several _Unable to locate_, he seems to be a network issue between your host and docker.
Can you check this ?

P.S: I have push a little fix for typo on docker-run.

**Comment by khouloudbelguith** [comment]
@presteus,
>Can you check this ?

How can I check this?
I'm using other Virtual Environments using Docker and they are OK.

Thanks!

**Comment by presteus** [comment]
@khouloudbelguith You can use docker utilities like _docker network_ to inspect the network between your container and your host.

I closed this issue due to commit https://github.com/PrestaShop/PrestaShop/pull/18285

Thanks all for your interest.
