### ISSUE TITLE
[Orders Page] - Wrong number of orders displayed with filter 'New Client'

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#18248]
#### Describe the bug

When filtering by column 'New Client' in orders page, the number of orders displayed in `h3.card-header-title` is wrong (it displays the total number of orders)

#### Expected behavior

The correct number of orders displayed

#### Steps to Reproduce

1. Go to 'BO > Orders' page
2. Filter by column 'New client' Value 'Yes'
Expected number of orders displayed : 1
Actual Number of orders displayed : 5
![image](https://user-images.githubusercontent.com/48441421/77184215-cb4fca80-6acf-11ea-91f5-a972369d2ba5.png)

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by boubkerbribri** [comment]
ping @khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi!

Same issue with the branch 1.7.7.x.
It is a regression.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #18288
