### ISSUE TITLE
Doc for theme translation 1.7

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#18249]
Missing doc on how to translate theme using the xlf files.
How do you add a theme translation with xlf ?
How do you import / update theme translation with xlf ?

**Comment by khouloudbelguith** [comment]
Hi @thbl,

Thanks for your report.
Thanks to check those links:
1. https://build.prestashop.com/howtos/translation/how-to-translate-your-theme/
2. https://build.prestashop.com/news/new-translation-system-prestashop-17/
3. https://build.prestashop.com/news/translation-news-171/

Thanks to check and feedback.

**Comment by thbl** [comment]
@khouloudbelguith  in 1.7.6.4
https://build.prestashop.com/howtos/translation/how-to-translate-your-theme/
"2. Export the language from the translation page"
This doesn't work properly, it only exportssome strings not all.
"3. Copy the file into the translation file of your theme"
If i try install an translation by adding the xlf this way, it dosent load / register the translations in PS

**Comment by thbl** [comment]
@khouloudbelguith also this article is 3 years old and for 1.7.1.1...

**Comment by thbl** [comment]
@khouloudbelguith  do you know if its a bug in 1.7.6.4 or cause the doc dosen't match ?

**Comment by khouloudbelguith** [comment]
@thbl,

>This doesn't work properly, it only exportssome strings not all.

Issue reported here: https://github.com/PrestaShop/PrestaShop/issues/16555

>If i try install an translation by adding the xlf this way, it dosent load / register the translations in PS

It is ok in my case, I used PS1.7.6.4 and this [theme](https://github.com/PrestaShop/childtheme-example).
I attached a screen record
[Untitled_ Mar 23, 2020 11_57 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4368801/Untitled_.Mar.23.2020.11_57.AM.webm.zip)

Thanks to check and feedback.

**Comment by thbl** [comment]
@khouloudbelguith i see, so for now there is just no export option ? (that works)

**Comment by khouloudbelguith** [comment]
@thbl, as commented [here](https://github.com/PrestaShop/PrestaShop/issues/16555#issuecomment-572112630)
If we change the translations of the theme => the file is well generated the next time.
So all files are generated after translating the theme (translations are missing: it is not the case).

Thanks!

**Comment by thbl** [comment]
@khouloudbelguith is there any work around to export all missing translations ?

**Comment by khouloudbelguith** [comment]
@thbl, please follow this issue: https://github.com/PrestaShop/PrestaShop/issues/16555.
We are still waiting for the developers' response.

I will close this issue.
Thanks!

**Comment by thbl** [comment]
@khouloudbelguith  okay will do, tho #16555 is 5 month old without reply from dev team

**Comment by thbl** [comment]
@khouloudbelguith  how about import function ?
