### ISSUE TITLE
Regenerate "not found" images automatically

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18257]
#### What I found

If there is no thumbnail generated for an image in PrestaShop, it will generate the thumbnail automatically on the fly. But, it doesn't do so for "not found images", so there was no image shown in my case.

And second thing, if you go to Appearance > Image settings, go to Thumbnail Regeneration, select image category you want to regenerate, it will not regenerate "not found" images. It will regenerate them only if you select Image type > Everything, which can be quite time and resource consuming.

#### Solution that would be good

Regenerate "image not found" image on the fly, if it does not exist.

#### Specs

Only available from the activation of a feature flag for 8.1

Generate the missing image when the image is only called from the browser

#### Context

PrestaShop 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by khouloudbelguith** [comment]
related to: https://github.com/PrestaShop/PrestaShop/issues/9926

**Comment by Hlavtox** [comment]
@MatShir This is not fixed yet.

If you delete thumbnails of placeholder images, their thumbnails are not regenerated again.

![Snímek obrazovky 2023-04-21 140353](https://user-images.githubusercontent.com/6097524/233630915-62cbbe31-fb05-415b-ad5c-7dbb49aec136.jpg)

**Comment by MatShir** [comment]
close in favor of https://github.com/PrestaShop/PrestaShop/issues/32351
