### ISSUE TITLE
PrestaShop CMS page dropdown weird display

### ISSUE THREAD

**Issue by simeon9446** [PrestaShop/PrestaShop#18256]
Hello, 

I installed PrestaShop on localhost. I followed instructions from YouTube tutorial.
Everything seems to be alright except the one thing.
Some of  PrestaShop (1.7.6) CMS dropdowns is bugged and not responsive.
How to fix this?

Image of issue:
![cms-dropdown-bug](https://user-images.githubusercontent.com/27215653/77238481-038f0000-6bd9-11ea-8971-702d50c2598d.png)

**Comment by PaulLayout** [comment]
Yes, I have the same problem.
![sin_nombre](https://user-images.githubusercontent.com/62504091/77248985-36b7aa80-6c3e-11ea-8853-ff553aa3aacc.png)
![sin_nombre2](https://user-images.githubusercontent.com/62504091/77248986-37e8d780-6c3e-11ea-84cf-b8f24842c90f.png)

**Comment by JBWModules** [comment]
Wrong PHP Version - Prestashop 1.7.6 is only compatible to PHP 7.2

**Comment by khouloudbelguith** [comment]
HI @simeon9446, @PaulLayout,

PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by PaulLayout** [comment]
> HI @simeon9446, @PaulLayout,
> PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
> For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
> Next Major release PS1.7.7 will be compatible with PHP7.3.
> You need to downgrade your PHP version.
> Thanks!

Thanks @khouloudbelguith . I could fix it! Thank you so much!
