### ISSUE TITLE
web Desain

### ISSUE THREAD

**Issue by ikocunha93** [PrestaShop/PrestaShop#18261]
<!DOCTYPE html>
<html>
    <head>
        <title>login page</title>
    </head>
    <body>
    <marquee>By IKO<br>Web Desain</marquee>
    <div class="sonika">
    <form>
        <p>Username</p>
        <input type="text" name="" placeholder="Username">
        <p>Password</p>
        <input type="Password" name="" placeholder="Enter password">
         <br>   
        <br>
         <button onclick="window.location.href = 'https://youtu.be/svZG8-skWwE';">Submit</button>
        <br>
        <br>
        <a href="#">Forget Password</a>
    </form> 
    </div>

        
    </body>
</html>

**Comment by ikocunha93** [comment]
body {
margin:0px;
padding:0px;
font-family:Sans-serif;
background-color:black;   
}
.sonika{
    position:absolute;
    top:50px;
    left:55px;
    width:250px;
    height:420px;
    padding:80px 40px;
    box-sizing:border-box;
    background-color:aqua;
    transform:translate{-50%,-50%};
    border:5px solid red;
}
marquee{
    color:red;
}

**Comment by khouloudbelguith** [comment]
Hi @iko93,

Thanks for your report.
What is the exact issue in your case?
Thanks to provide us a clear description of your issue.

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
