### ISSUE TITLE
1-Click Upgrade error to update database because of max_execution_time

### ISSUE THREAD

**Issue by adi5497** [PrestaShop/PrestaShop#18264]
Hi, I have beed trying to update PrestaShop to 1.7.6.4 but in the end of proccess it said error to upgrade DB because of max_execution_time. I see that PS has been upgraded but DB not (i have looked into ps__configuration table and there is an old ver 1.7.6.1). There is any way to force update again to upgrade DB too?

**Comment by khouloudbelguith** [comment]
Hi @adi5497,

It is a size problem.
Thanks to check your configuration in the `php.ini` file & try to increase them

```
upload_max_filesize

post_max_size

max_file_uploads

memory_limit

max_input_vars

max_input_time

max_execution_time

```
And enable `set_time_limit`


Thanks!

**Comment by adi5497** [comment]
> Hi @adi5497,
> 
> It is a size problem.
> Thanks to check your configuration in the `php.ini` file & try to increase them
> 
> ```
> upload_max_filesize
> 
> post_max_size
> 
> max_file_uploads
> 
> memory_limit
> 
> max_input_vars
> 
> max_input_time
> 
> max_execution_time
> ```
> 
> And enable `set_time_limit`
> 
> Thanks!
Hi @khouloudbelguith, 
Actually I have changed this after this error but I'm not able to upgrade PS and DB again. PS have been updated, it may be the reason, but DB is still old version.

**Comment by adi5497** [comment]
Hi @khouloudbelguith,
Actually I have changed this after this error but I'm not able to upgrade PS and DB again. PS have been updated, it may be the reason, but DB is still old version.

**Comment by khouloudbelguith** [comment]
@adi5497, If you have a backup of your 1.7.6.1 shop, I'd strongly suggest to roll back and try to make a new upgrade.

Thanks to check and feedback.

**Comment by adi5497** [comment]
Hi @khouloudbelguith,
Can i wait to new ver and upgrade this then? It should be ok?

**Comment by khouloudbelguith** [comment]
@adi5497, the `max_excustion_time`, it is a server issue, not a PrestaShop core issue.
You need to increase it, then make a new upgrade.

Thanks!

**Comment by adi5497** [comment]
@khouloudbelguith, i know :) But if I will wait for another update and if next update will be successfully installed, DB will be upgraded correctlly?

**Comment by khouloudbelguith** [comment]
@adi5497, if something went wrong with your update and don't have some of the database columns that were added for 1.7.6.4
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.4 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by adi5497** [comment]
@khouloudbelguith, so I need just to simply set PREFIX and run this SQL?

**Comment by khouloudbelguith** [comment]
@adi5497, you need to check if there are missing columns in your database schema before.
If something is missing, you can run the SQL that fixes your problem.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @adi5497,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
