### ISSUE TITLE
BO - Order page - an exception is displayed after filter with a customer

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18263]
#### Describe the bug

In the BO => Order page => (migrated), an exception is displayed when we filter by a customer 

#### Expected behavior

It should be ok

#### Steps to Reproduce

1. Go to BO => Orders page
2. Filter by a customer
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/77297229-42ac7680-6ce9-11ea-81e6-f86fe69e36ae.png)
[Orders • 177x.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4368045/Orders.177x.webm.zip)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
ping @boubkerbribri

**Comment by Progi1984** [comment]
Fixed by #18305
