### ISSUE TITLE
Brands issue

### ISSUE THREAD

**Issue by BudrysLP** [PrestaShop/PrestaShop#18262]
#### Describe the bug

After disabling brand it is removed from products.

So when it will be enabled again products doesn't have it anymore.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Disable brand
2. Brand disapears from products
3. Edit that product and Save changes
5. Enable brand
6. Edited product doesn't have any brand

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @BudrysLP,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.3 and PS1.7.6.4.
I attached a screen record
[Product • 1763en.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4368177/Product.1763en.webm.zip)
Thanks to check and feedback.

**Comment by BudrysLP** [comment]
You forgot about save product when You edit it.

**Comment by khouloudbelguith** [comment]
@BudrysLP,

>You forgot about save product when You edit it.

Thanks for these clarifications.
Yes, in this case, you just save changes and then there is no brand attached to this product, so the previous value is deleted.
I think it is normal behavior.
What do you think?

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
