### ISSUE TITLE
BO - Files page - Filter doesn't work, it just refresh the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18271]
#### Describe the bug

In the BO => Catalog => Files page, when we try to search by any filter => nothing happens, the page is just refreshed.

#### Steps to Reproduce

BO - Files page - Filter doesn't work, it just refresh the page
1. Go to BO => Catalog => Files page
2. Search by any filter
3. See error

**Screenshots**
[Files • 177x.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4370230/Files.177x.webm.zip)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Could be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/18218

**Comment by Progi1984** [comment]
Fixed by #18228
