### ISSUE TITLE
[View Order] - Help Card is not displayed in sidebar

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#18279]
#### Describe the bug

When we click on button 'help', the sidebar is not opened in the same page, it redirect us to `http://shopUrlBO/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop.com%252Fen%252Fdoc%252FAdminOrders%253Fversion%253D1.7.7.0%2526country%253Den/Help?_token=UPht_KhRc6klvl4uiSIxiDHFRXsy4HwKZrsGxn1fLz4`

#### Expected behavior

SideBar opened in the same page

#### Steps to Reproduce

1. Go to 'BO > Orders' page
2. View first order (for exemple)
3. Click on button 'Help'
4. Link is opened in a new page
![image](https://user-images.githubusercontent.com/48441421/77406977-bddb5e80-6db5-11ea-96a7-645847043c63.png)

* PrestaShop version: branch 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18437
