### ISSUE TITLE
Impossible to update from 1.7.5.2 to 1.7.6.4

### ISSUE THREAD

**Issue by pdsolutions** [PrestaShop/PrestaShop#18276]
#### Describe the bug

Can't update from brand new installation of PS 1.7.5.2  to 1.7.6.4

#### Expected behavior

A normal update

#### Steps to Reproduce

1. Installed the a brand new Prestashop 1.7.5.2 in Spanish with php 7.2.2.8
2. Installed the 1 click update from Prestashop modules using the website backend
3. Updated all modules from "Updates tab"
4. Unchecked "Back up my files and database and images"
5. Checked "Keep the customized email templates"
6. Folder permission is 755 and 644 for files (to discard any write permission problem)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

**This is the error of the backend after the update:**

> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Cannot use object of type Symfony\\Component\\HttpFoundation\\ParameterBag as array in /var/www/vhosts/pixeldraw.net/wya/src/Adapter/Security/Admin.php:91\nStack trace:\n#0 /var/www/vhosts/pixeldraw.net/wya/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\\PrestaShop\\Adapter\\Security\\Admin->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#1 /var/www/vhosts/pixeldraw.net/wya/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#2 /var/www/vhosts/pixeldraw.net/wya/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\Eve...\n', referer: https://www.wya.es/tienda18/index.php?controller=AdminSelfUpgrade&conf=6&token=12df83913df03902b6058e56f2d87164

**This is the error of the front-end after update:**

> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'tienda'@'localhost' (using password: YES) in /var/www/vhosts/pixeldraw.net/wya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/vhosts/pixeldraw.net/wya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'tienda', 'Dmr26%%%%y20S9s...', Array)\n#1 /var/www/vhosts/pixeldraw.net/wya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(44): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'tienda', 'Dmr26%%%%y20S9s...', Array)\n#2 /var/www/vhosts/pixeldraw.net/wya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'tienda', 'Dmr26%%%%y20S9s...', Array)\n#3 /var/www/vhosts/pixeldraw.net/wya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(942): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/vhosts/pixeldraw.net/wya/...\n', referer: https://www.wya.es/es/

The Prestashop 1.7.5.2 were downloaded from here: https://www.prestashop.com/es/versiones-anteriores

**Comment by pdsolutions** [comment]
I just managed to update after 1 day of hard work disabling modules, templates, htaccess rules, so the problem was the DB password.

Looking closer to this line: connect(Array, 'tienda', 'Dmr26%%%%y20S9s...', i saw that **Dmr26%%%%y20S9s** **does not match the password from /app/config/parameters.php -> Dmr26%%y20S9snt9?**

This a a very weird bug, somehow, on update everything mess up if you use strong passwords like Dmr26%%y20S9snt9?

**Comment by khouloudbelguith** [comment]
Hi @pdsolutions,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9564
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9564
