### ISSUE TITLE
"update address" page title is changed when an error is triggered

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18283]
#### Describe the bug

The main title of the "edit address" page is changed when a error is triggered in the form

#### Expected behavior

The title must remain the same

#### Steps to Reproduce

1. Go to FO => account => addresses
2. If you don't have address => create one
3. Click on update address
4. In first name field try to set a number and save
5. An error is triggered and the title of the page is changed

**Screenshots**

**Before the error was triggered**
![capture d'écran_6](https://user-images.githubusercontent.com/40635814/77412108-bc159900-6dbd-11ea-9142-ee38e6dd0550.png)

**After triggering the error**
![capture d'écran_7](https://user-images.githubusercontent.com/40635814/77412182-d3548680-6dbd-11ea-8175-127e4cdef1ef.png)

#### Additional information

* PrestaShop version: 1.7.6.x , 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I think this PR: https://github.com/PrestaShop/PrestaShop/pull/18103 should fix the problem, is it?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

I have the same issue with PS1.7.5.2, PS1.7.6.4, PS1.7.6.3, and the branch 1.7.6.x.

Thanks!
