### ISSUE TITLE
Orders -> Any order opens as first order always with id_order=1

### ISSUE THREAD

**Issue by ArnasL** [PrestaShop/PrestaShop#18282]
#### Describe the bug

I have upgraded my PrestaShop from 1.6 to 1.7 with fresh installation and data export, import.

In BO -> Orders whenever I try to edit any order it opens me first order. So every edit order button has same link with same ID = 1. If I change ID manually by it's order ID I can view and edit order. How can I fix this issue?

Also noticed that total orders shows: 3473 (as it was after import), but I have got 10 new orders and it has to be total orders: 3483. But as I said earlier I can manually open order to edit by this URL: https://domain.com/admin3vzc1sj/index.php?controller=AdminOrders&id_order=3483&token=0495d0d0f7da91a2b529fde1612847c0&vieworder=3483

Orders list screenshot:
https://www.dropbox.com/s/toc146mk8lsdv3i/Screenshot%202020-03-24%2011.41.28.png

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @ArnasL,

Thanks for your report.
>I have upgraded my PrestaShop from 1.6 to 1.7 with a fresh installation and data export, import.

So, did you make an upgrade manually, you didn't use the 1-click upgrade module?

Thanks!

**Comment by ArnasL** [comment]
I have been using MigrationPro and I always use this module and never had any issues, so I think it's not module related issue.

**Comment by ArnasL** [comment]
If it's not possible to fix it I'm okey with all order history deletion and starting new orders ID numbering from 4000 and 04000 reference. How is that possible?

**Comment by khouloudbelguith** [comment]
@ArnasL,

I did not manage to reproduce the issue after an upgrade from PS1.6.1.24 to PS1.7.6.4 using the 1-click upgrade v4.10.1.
I attached a screen record
[Modules • PrestaShop.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4374898/Modules.PrestaShop.webm.zip)
 
>If it's not possible to fix it I'm okey with all order history deletion and starting new orders ID numbering from 4000 and 04000 reference. How is that possible?

In the `ps_orders` table `Operations` Tab, you need to set the "AUTO_INCREMENT"= 4000 and save, then the id of the next cart created will be 4001.
![image](https://user-images.githubusercontent.com/16067358/77420419-47952700-6dca-11ea-9f6a-9a555898e3b7.png)
You need to make a backup before to be safe.

>I have been using MigrationPro

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
