### ISSUE TITLE
Fix on statsbestvouchers native module

### ISSUE THREAD

**Issue by mircobabini** [PrestaShop/PrestaShop#18281]
#### Describe the bug

When invoices are not generated for all order or not generated at all, the stats are incomplete.

#### Expected behavior

I want to see the used vouchers in stats for every complete order, not just for orders with an invoice.

#### Steps to Reproduce

1. Go to Prestashop admin panel
2. Disable the invoice generation
3. Create an order with a voucher
4. Check the voucher stats. It won't be affected.

#### Additional information

* PrestaShop version: Any
* PHP version: Any
* Pull request: [statsbestvouchers#3](https://github.com/PrestaShop/statsbestvouchers/pull/3)

**Comment by khouloudbelguith** [comment]
Hi @mircobabini,

I did not manage to reproduce the issue with PS1.7.6.4 and the `Best vouchers` module v2.0.0.
I attached a screen record
[Stats • ps1764.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4374529/Stats.ps1764.webm.zip)
Thanks to check and feedback.

**Comment by mircobabini** [comment]
How is this possible? The query checks the o.invoice_date column in mysql, how can it be compiled in your case with invoices deactivated? What value fills into that field in your database?

**Comment by khouloudbelguith** [comment]
@mircobabini, you can try with this shop: https://panicky-property.machine-shuffle.prestashop.net/admin-dev
`Email address`: demo@prestashop.com
`Password`: prestashop_demo

Thanks!

**Comment by sarahdib** [comment]
@mircobabini 

The voucher appear in the stats only if the order is validated. 
When the status is waiting for payement the voucher doesn't appear.

You want that the voucher appear even if the status is waiting for payement ?

**Comment by mircobabini** [comment]
@sarahdib thanks for the answer. Please, check [this pull request I made](https://github.com/PrestaShop/statsbestvouchers/pull/3/commits/91023cab605218e4769257cd4e377805d46df8e5).

I'm talking about the query. That query get only results with an o.invoice_date. But sometimes (when invoices are deactivated) the o.invoice_date in NOT set. That's why you should change that query using o.date_add instead of o.invoice_date.

By the way, I get what you mean when you say that the voucher should appear in the stats only if the order is validated. Good to know, but that query is still wrong, because if you use the "invoice_date" to check if the order is validated, you are not covering all validated orders.

**Comment by khouloudbelguith** [comment]
@mircobabini, the problem that we cannot reproduce the issue following these steps:
1- Disable Invoices
2- Add a new order with a discount  from the BO
3- Change the status to "Payment accepted" 
4- check statsbestvouchers => OK

Thanks!

**Comment by sarahdib** [comment]
@mircobabini 

Can you give us a case when the voucher should appear and it didn't ? 

Thank you :)

**Comment by mircobabini** [comment]
Well, I currently have a website which is acting like I described above.
By the way... I'm thinking that it can be some conflict with another module.

If it's just me, then it's not an issue. Thanks!
