### ISSUE TITLE
Javascript error (parseJSON) detected for action "backupFiles"

### ISSUE THREAD

**Issue by ashtonlance** [PrestaShop/PrestaShop#18296]
#### Describe the bug

Trying to use the autoupgrade. The backup process fails at the same time everytime I try.

#### Expected behavior

Autoupgrade backs my files up and completes the process

**Screenshots**

<img width="1433" alt="Screen Shot 2020-03-24 at 8 39 37 PM" src="https://user-images.githubusercontent.com/13652692/77490194-9e255400-6e10-11ea-90bf-4ed0c7de91fc.png">

#### Additional information

* PrestaShop version:  1.7.5.2
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @ashtonlance ,
Despite our several trials, we could not reproduce your issue with the provided information.
Here's my result :
![Capture d’écran 2020-03-25 à 14 35 40](https://user-images.githubusercontent.com/16019289/77542160-096d3580-6ea6-11ea-8280-92addca81e36.png)

What is the version of the 1-click upgrade are you using ? I am using v1.10.1

Thanks!

**Comment by ashtonlance** [comment]
@florine2623 Thanks for checking into this!
I'm using 1-click upgrade v4.10.1
![Screen Shot 2020-03-25 at 9 47 07 AM](https://user-images.githubusercontent.com/13652692/77543190-b2ec0100-6e7d-11ea-976b-82573f7da88e.png)

**Comment by florine2623** [comment]
Hi @ashtonlance ,
You could check these few things : 
- allow_url_fopen is activated on your host
- activate debug mode in PrestaShop
- send us error log in /var/logs

Thanks to check and update!

**Comment by ashtonlance** [comment]
Thanks @florine2623 

allow_url_fopen is activated

Here's a screenshot of the network tab right after the error happens:
![Screen Shot 2020-03-25 at 12 44 13 PM](https://user-images.githubusercontent.com/13652692/77562673-b2139900-6e96-11ea-8039-58334823b59b.png)

And here's the log file:
[dev.log](https://github.com/PrestaShop/PrestaShop/files/4382247/dev.log)

**Comment by florine2623** [comment]
Hi @ashtonlance ,
Could you send me the following file : 
```your_shop/admin/autoupgrade/tmp/log.txt```
Thanks!

**Comment by ashtonlance** [comment]
@florine2623 Sure!

[log.txt](https://github.com/PrestaShop/PrestaShop/files/4387517/log.txt)

**Comment by florine2623** [comment]
After checking your file, we have noticed that the copy of the files suddenly stops during the upgrade. You should check with your host if you have enough storage space.
Thanks!

**Comment by ashtonlance** [comment]
Hi, I'm not sure that's true. We're currently using approx 2% of our available disk space.

**Comment by florine2623** [comment]
Could you check with your host directly ?

**Comment by ashtonlance** [comment]
My host says my disk usage is normal, with plenty of room left -- the memory usage and cpu usage is well below 5%.

They said they didn't see any logs or errors that threw any red flags.

**Comment by khouloudbelguith** [comment]
Hi @ashtonlance,

In the BO => 1-click upgrade configuration page => the "Disable non-native modules" option is enabled?
Thanks to disable it, check and feedback.

**Comment by ashtonlance** [comment]
Hi @khouloudbelguith 

That setting has been toggled off the whole time.

**Comment by sarahdib** [comment]
Hello @ashtonlance 

Can you try to save manually the image, disable the option who saves images and try again ?

Thank you

**Comment by ashtonlance** [comment]
Hi @sarahdib 

The option to backup images has been turned off this whole time.

**Comment by sarahdib** [comment]
@ashtonlance it's weird because in the log the image is back up and the same for modules non-native.

are you sure you saved the change ?

**Comment by ashtonlance** [comment]
Yes, here's how the toggle looks

![image](https://user-images.githubusercontent.com/13652692/77926727-73098d00-7274-11ea-8698-6597a65afbd8.png)

**Comment by khouloudbelguith** [comment]
Hi @ashtonlance,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4407790/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by ashtonlance** [comment]
Hello!

Thanks for your help. Screenshot is below.

![Screenshot_2020-03-31 PHP PrestaShop Info](https://user-images.githubusercontent.com/13652692/78030610-5cc10700-7330-11ea-9728-5897d00efa19.png)

**Comment by khouloudbelguith** [comment]
@ashtonlance, 
Use the following settings to optimize the performances:
```
[Date]
date.timezone = UTC

[Session]
session.auto_start = Off

[PHP]
short_open_tag = Off
display_errors = Off

magic_quotes_gpc = off
; Increase this value if you are able to do it
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
upload_max_filesize = 20M
post_max_size = 22M
; Increase this value if you work with products with a lot of combinations
max_input_vars = 20000
allow_url_fopen = on

```

For more details, you can follow this [link](https://devdocs.prestashop.com/1.7/scale/optimizations/).

Thanks!

**Comment by ashtonlance** [comment]
Hi,
I've updated my config to replicate the settings you recommended and tried the upgrade again.

Same error at the same file as before.

![Screenshot_2020-03-31 PHP PrestaShop Info](https://user-images.githubusercontent.com/13652692/78032220-b0cceb00-7332-11ea-86b9-93ab0c73c424.png)

**Comment by khouloudbelguith** [comment]
@ashtonlance, It will help us if you can attach a screen record while upgrading for the first.
I need to check in your screen record that:

- "Disable non-native modules" is "Enabled"
- "Back up my files and database" is "Disabled"
- "Back up my images" is "Disabled"

PS: thanks to make a backup of your Database and your Files to be safe!

Thanks!

**Comment by ashtonlance** [comment]
Hi,

I expect that disabling the backups will fix the issues — as that’s where the auto upgrade is breaking. But half the appeal of the auto upgrade is the automated backups. Is there another route? I’m happy to post a screen recording.

**Comment by khouloudbelguith** [comment]
@ashtonlance, in your BO => Advanced Parameters => Database => DB Backup Tab, you can make a backup of your Database.
![image](https://user-images.githubusercontent.com/16067358/78145388-1d2e1400-7431-11ea-927e-08bd09f059aa.png)

>I expect that disabling the backups will fix the issues

So your issue is fixed or not checked yet?

Thanks!

**Comment by ashtonlance** [comment]
Ended up making manual backups and then upgrading.

Kinda defeats the point of the module but hopefully this was just a fluke.

**Comment by khouloudbelguith** [comment]
@ashtonlance, Great!
Feel free to open a new one when needed.

Thanks!
