### ISSUE TITLE
Make order reference configurable

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18295]
#### Background

The first time I do for my every customer is changing order reference to be generated as numeric. Usually we also add a year prefix before the order number.

#### Proposed solution

Make order reference configurable in an easy way, by a field in Prestashop settings. In the same way, as you configure URLs for example.
![urls](https://user-images.githubusercontent.com/6097524/77486815-fe2bf280-6e30-11ea-8589-df15bfb1d26f.JPG)

This system would also be useful for setting invoice and returns numbering format. Nearly every professional invoicing software uses this way to define numbering of documents.

#### Solution

Create a new field in Settings > Order settings, called **Order reference format**.
User will enter the rule to generate the order reference into this field. Like this:
`1{yyyy}{nnnnn}`

Prestashop will then assign following reference
`1202054321`

#### Additional specs

- There would be also a preview shown under the field, for user to see that he entered the spec correctly.
- It would not introduce any BC breaks.
- After upgrade, we would set the format to lettered, so nothing changes for the merchant, if he does not want to use it.

#### Options to enter

| Key  | Meaning |
| ------------- | ------------- |
| 0-9  | Fixed numbers  |
| A-Z  | Fixed letters  |
| -  | Dash character  |
| {aaa}  | Random lettered string 3 characters long|
| {nnn}  | Random numbered string 3 characters long  |
| {yy}  | Year  |
| {yy}  | Year  |
| {yyyy}  | Year  |
| {mm}  | Month  |
| {dd}  | Day  |
| {oi}  | Order ID  |
| {ci}  | Customer ID  |

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
I think the issue of "Improving the order reference" is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/13212
Ping @MatShir @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by tswfi** [comment]
One more idea for customization

`{customer_number}` => allows merchant to pre or postfix the number with the customer number

this would allow the merchant to define something like 

```{customernumber}{rand(5)}{ymd}```

or any other combination.

maybe even make the field "smarty" template so that it can contain some woodoo also :)

and of the default can be the current {random_alphanum(6)} or something like that.

And actually the current implementation does not guarantee that the references stay unique, that should probably be fixed also :)

**Comment by Hlavtox** [comment]
@matks I saw your comment in @tswfi 's issue. 
> However this is quite a lot of job. It's not the same size as the mail theme refacto or the CLDR refacto, but this is nonetheless a big job. In fact changing the code is not so long, what is very long is to check everywhere in the code and the shop whether this breaks something 😄 as Order IDs are a central piece of data for PrestaShop and are used in a lot of places.

Personally, I think it's not dangerous at all, if we allow user to enter only 0-9, A-Z and dash. I have always changed order reference to NUMBERIC and I have never encountered any issue in 5+ years of me using Prestashop. Order reference is a just a string, nothing more. It will never contain special characters, so no worries about escaping it anywhere also.

**Comment by matks** [comment]
@Hlavtox I think I wrote a mistake, I thought it was about changing "order numeric IDs" into strings. But it was not the point of the issue. My comment was out of topic 😅 .

**Comment by Hlavtox** [comment]
@tswfi Updated the variable table, do you think we need something more?

**Comment by tswfi** [comment]
@Hlavtox what do you mean `updated the variable table`?

**Comment by Hlavtox** [comment]
@tswfi I mean the options/variables we can use during order reference generation. Look to the issue description. ;-)
