### ISSUE TITLE
Impossibile cancellare l'indirizzo.

### ISSUE THREAD

**Issue by francescangemi** [PrestaShop/PrestaShop#18292]
Impossibile eliminare uno o più indirizzi di un account cliente.
![FireShot Capture 014 - Indirizzo - shop pastadicanossa it](https://user-images.githubusercontent.com/48442917/77450152-301e6400-6df3-11ea-9c4f-055b6c886747.png)

**Comment by khouloudbelguith** [comment]
Hi @francescangemi,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by khouloudbelguith** [comment]
@francescangemi, you just closed your issue.
Is it fixed?

Thanks!
