### ISSUE TITLE
BO - Order page - Filter doesn't work, it does not show any result

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18291]
#### Describe the bug

In the BO => Order page, the filter doesn't work, it does not show any result.

#### Steps to Reproduce

1. Go to 'Bo => Order page
2. Search by any filter except "Customer" reported here: https://github.com/PrestaShop/PrestaShop/issues/18263
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/77447794-5e4e7480-6df0-11ea-9876-5acf5565e415.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh @boubkerbribri 
Detected by https://github.com/PrestaShop/PrestaShop/pull/18290/checks?check_run_id=530891105

**Comment by Progi1984** [comment]
Fixed by #18294
