### ISSUE TITLE
Cannot save or update customer in BO

### ISSUE THREAD

**Issue by simontingkamlee** [PrestaShop/PrestaShop#18301]
I am using Prestashop 1.7.6.4. When I edited and tried to save data of an existing customer, I get the following error:

An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]

I searched in the database. Someone has reported something liked this but I cannot find the solution in those post. Can someone let me know the solution to this? Many many thanks.

Regards,
Simon

**Comment by khouloudbelguith** [comment]
Hi @simontingkamlee,

Thanks for your report.
Did you use a fresh install PS1.7.6.4 or an upgrade from an old version?
In my case, I did not manage to reproduce the issue with PS1.7.6.4.
We have an issue already fixed: https://github.com/PrestaShop/PrestaShop/issues/17809

Thanks to check and feedback.

**Comment by simontingkamlee** [comment]
An upgrade from P.S 1.7.6.3 to 1.7.6.4

 

Simon

**Comment by simontingkamlee** [comment]
I’m sorry. How can I fix this? Which part of the codes/files should I replace? Can you send me the changes and steps to make the change please. Thanks.

 

Regards,

Simon

**Comment by khouloudbelguith** [comment]
@simontingkamlee, 
the problem was almost certainly due to a failure to update the `ps_customer` table.
Thanks to provide me a screenshot of your the `ps_customer's` structure
![image](https://user-images.githubusercontent.com/16067358/77529244-880aa880-6e8f-11ea-8118-3a04da4f50d3.png)

Thanks!

**Comment by simontingkamlee** [comment]
Here's my ps_customer table's structure.

Simon

----- Original Message -----
From: "PrestaShop/PrestaShop"
<reply@reply.github.com>
To:"PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
Cc:"simontingkamlee" <simonlee@hago-group.com>, "Mention"
<mention@noreply.github.com>
Sent:Wed, 25 Mar 2020 03:55:54 -0700
Subject:Re: [PrestaShop/PrestaShop] Cannot save or update customer in
BO (#18301)

	@simontingkamlee [1],
 the problem was almost certainly due to a failure to update the
ps_customer table.
 Thanks to provide me a screenshot of your the ps_customer's structure
 [2] 

	Thanks! 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4]. 

Links:
------
[1] https://github.com/simontingkamlee
[2]
https://user-images.githubusercontent.com/16067358/77529244-880aa880-6e8f-11ea-8118-3a04da4f50d3.png
[3]
https://github.com/PrestaShop/PrestaShop/issues/18301#issuecomment-603774708
[4]

**Comment by florine2623** [comment]
Hi @simontingkamlee ,

Please send the screenshot of ```ps_customer``` structure once again, i did not receive it.
Could you upload it on GitHub directly and not by email please ?

Thanks!

**Comment by simontingkamlee** [comment]
Sorry, here's the screenshot:

![customer](https://user-images.githubusercontent.com/54059552/77544802-7ef7f680-6ee4-11ea-8e04-b2ab8b426230.jpg)

**Comment by florine2623** [comment]
Hi @simontingkamlee ,

Could you send me the data that your want to save in the customer page ?

**Comment by simontingkamlee** [comment]
![customer 2](https://user-images.githubusercontent.com/54059552/77550927-9dfa8680-6eec-11ea-8852-d5cd059cb26c.jpg)

**Comment by florine2623** [comment]
So, it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.4
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.4 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by simontingkamlee** [comment]
Can you be more specific and advise which tables I should look for. There are 2800+ lines in the schema and it's kind of difficult to compare.

Here's the schema of my database.
[schema.sql.zip](https://github.com/PrestaShop/PrestaShop/files/4382120/schema.sql.zip)

I am using php 7.3 instead of 7.1. Could this be the problem?

**Comment by khouloudbelguith** [comment]
@simontingkamlee,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

**Comment by simontingkamlee** [comment]
I will try to downgrade from php7.3 to 7.2 and see if that would help. 

I found something peculiar though. The problematic customer records were imported. 

I tried to create a new customer from the front end and saved it. Then go into the back end, opened the new customer record, edited and saved it. There’s no problem. 

I compared the new customer and the imported customer record in phpMyAdmin, I couldn’t see anything wrong with the imported customer record in the “customer” table. Is there somewhere else I should look? I suspect there’s something that is not imported properly. Can you let me know where I should look? Is there an error log that would give me some hints of what went wrong? I turned on debug mode but it does not show me the error. Thanks.

Regards,
Simon

**Comment by florine2623** [comment]
Hi @simontingkamlee ,
Did you use PrestaShop import tool to import your customers ? Or another one ?
Thanks!

**Comment by simontingkamlee** [comment]
Yes, I used prestashop import to import the list generated by your
export module.

Simon

----- Original Message -----
From: "PrestaShop/PrestaShop"
<reply@reply.github.com>
To:"PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
Cc:"simontingkamlee" <simonlee@hago-group.com>, "Mention"
<mention@noreply.github.com>
Sent:Thu, 26 Mar 2020 06:36:56 -0700
Subject:Re: [PrestaShop/PrestaShop] Cannot save or update customer in
BO (#18301)

	Hi @simontingkamlee [1] ,
 Did you use PrestaShop import tool to import your customers ? Or
another one ?
 Thanks! 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3]. 

Links:
------
[1] https://github.com/simontingkamlee
[2]
https://github.com/PrestaShop/PrestaShop/issues/18301#issuecomment-604435236
[3]

**Comment by florine2623** [comment]
Can you send me the exact name of the module or the link of the module you are using ?

**Comment by simontingkamlee** [comment]
![export customer module](https://user-images.githubusercontent.com/54059552/77717833-612dad00-701c-11ea-942b-d9a00aac5854.png)

**Comment by khouloudbelguith** [comment]
Hi @simontingkamlee,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
