### ISSUE TITLE
BO - Orders - Undefined when search for customers

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18304]
#### Describe the bug

In BO when add a new order => search a customer return undefined

#### Expected behavior

The customer should be displayed

#### Steps to Reproduce

1. Go to BO => Sell => Orders => Add new
2. In "search customer" field search for "doe"
3. See error

**Screenshots**

![capture d'écran_11](https://user-images.githubusercontent.com/40635814/77527671-da969580-6e8c-11ea-88c0-174ff382beab.png)

#### Additional information
Not reproduced with 1.7.7.x and 1.7.6.x

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I have the same issue with develop branch.
When we click "`Details`" => Redirection to the Dashboard page => NOK
When we click "`Choose`" => The details of the `anonymous@psgdpr.com` are displayed => NOK.

Thanks!
