### ISSUE TITLE
[Create order] Product images are wrong in cart details

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18312]
In Create order page, when clicking on Details of a previously created cart, product images displayed are not correct. See screenshot below : the products in the cart use the combination "White", but associated images show black products. 

![image](https://user-images.githubusercontent.com/35263827/77568364-cf615b00-6ec8-11ea-8219-baf9de981f4d.png)

It is correct once you use the cart in the new cart.

I have tested it in 1.7.6.4, it works correctly.

**Comment by zuk3975** [comment]
just a note - technically its more like Order->Shipping Carts page bug (as the `details` redirects to cart view page), which is not yet enabled. Anyway, its only accessible from order create page in 1.7.7.x so I guess its not wrong to call it order bug. Ill take a look.

**Btw the page doesnt seem to show gift products either.**

**Comment by zuk3975** [comment]
blocked by https://github.com/PrestaShop/PrestaShop/pull/17179

**Comment by colinegin** [comment]
@zuk3975 it does show gift products. You don't see it on the screenshot but in this cart I had added 2 cart rules with the t-shirt as a gift product.

**Comment by zuk3975** [comment]
> @zuk3975 it does show gift products. You don't see it on the screenshot but in this cart I had added 2 cart rules with the t-shirt as a gift product.

Oh right, gift products show up, but those supposed to be marked as GIFT I guess instead of having prices. Same as in create order page.

**Comment by colinegin** [comment]
About your last comment, we need to discuss with @MatShir to see what's the expected behaviour on this page. Thanks !

**Comment by Progi1984** [comment]
Fixed by #18334
