### ISSUE TITLE
Prestashop 1.7.6.3 Template change problem

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18316]
By changing from a non default template to default and back all layout is messed up

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

Your ticket is a duplicate of #16838
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #16838
