### ISSUE TITLE
Add datatables rowreorder

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#18320]
#### Is your feature request related to a problem?
YES

The tables on Prestashop are not responsive 

#### Describe the solution you'd like
integrate the 
https://datatables.net/extensions/rowreorder/examples/initialisation/responsive
A clear and concise description of what you'd want to happen.

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your report.
Can you please provide us some screenshots about your problem.

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

I installed the htmlbox module and I added the code

```
`<script language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script language="javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script language="javascript" src="https://cdn.datatables.net/rowreorder/1.2.6/js/dataTables.rowReorder.min.js"></script>
<script language="javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script class="init">
	
$(document).ready(function() {
	var table = $('#sansat').DataTable( {
 rowReorder: {
 selector: 'td:nth-child(2)'
 },
 responsive: true
	} );
} );
`
```
but I get this error message on console 
![image](https://user-images.githubusercontent.com/11594433/77652761-1144dc80-6f6f-11ea-8620-95225cfeb340.png)

Regards

**Comment by florine2623** [comment]
Hi @go-sudo ,
Is it a PrestaShop module ? Could you send us the link ?

Thanks!

**Comment by go-sudo** [comment]
Hello

I sue the HTML box https://mypresta.eu/modules/front-office-features/html-box.html then  I added the code as its described on this link 

https://datatables.net/extensions/rowreorder/examples/initialisation/responsive

regards

**Comment by kpodemski** [comment]
You should contact mypresta.eu, not PrestaShop core developers here

**Comment by go-sudo** [comment]
HI @kpodemski I think you don't understand the matter and it would more polite to start your comment with "Ho, Hello , Bonjour) 
any way this module HTMLbox is just a tool to integrate js and css files the error is the same when I add the js file on front controllers or in the header 

the function is not working 

Regards

**Comment by kpodemski** [comment]
Hi ;)

@go-sudo your issue is completely unrelated to PrestaShop, you're trying to integrate external, third party script into PrestaShop, you're including jquery in higher version than this one used in PrestaShop, you're using third party module, in here you can report issues related to PrestaShop itself, not third party modules, scripts etc.

**Comment by sarahdib** [comment]
Hello @go-sudo 

You need to contact the module developer

I close this issue.

Thank you.

**Comment by go-sudo** [comment]
@khouloudbelguith 

I tried to use also CreativeElements to edit page, so I inserted the code on HTML widget as you see the tables are working but not on live mode 

![data](https://user-images.githubusercontent.com/11594433/77921116-3e5afd00-7297-11ea-9140-34d74c3d4d27.png)

![tableko](https://user-images.githubusercontent.com/11594433/77921987-5bdc9680-7298-11ea-8b74-b7af5cb2077f.png)

![table](https://user-images.githubusercontent.com/11594433/77922273-c1308780-7298-11ea-991b-51869201f11d.png)

link page
http://bit.ly/31tF5JO

Regards,

**Comment by go-sudo** [comment]
Hi
for people who search to integrate a responsive table I recommend 

https://fooplugins.github.io/FooTable/docs/components/filtering.html#options

Regards
