### ISSUE TITLE
blockreassurance - ajax save request failed with 404 page

### ISSUE THREAD

**Issue by charles-lebrun** [PrestaShop/PrestaShop#18328]
### Describe the bug

when I edit some option in the module or i try to save when a save button exist
an ajax request is send to this URL
https://MY_URL/adminxxxxxxx/index.php?controller=AdminBlockListing&token=TOKEN

the page respond with a 200 code and page not found content
So it's not possible to edit some configuration of the module

#### Expected behavior

can edit and save modification

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3.15

**Comment by florine2623** [comment]
Hi @charles-lebrun ,
The version of PHP you are using is not compatible with your version of PrestaShop.
For PS 1.7.6.4, you should be using PHP 7.2
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by charles-lebrun** [comment]
Hello
Hi just switch to PHP 7.2.28 and i got exactly the same error

**Comment by florine2623** [comment]
What version of he module are you using ?
I tried both versions v3.0.1 and v4.1.1, it worked fine.

**Comment by charles-lebrun** [comment]
I'm using version 4.1.1
i can uninstall and reinstall if you think it can help

**Comment by florine2623** [comment]
Yes please

**Comment by charles-lebrun** [comment]
ok I reinstall completely the module and i reset config
now it seems to work :)

**Comment by florine2623** [comment]
Ok perfect :)
Thanks for the feedback.
