### ISSUE TITLE
BO - Order page - The option "Amount of your choice:" is not displayed when we try to return a discounted product 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18333]
#### Describe the bug

In the BO => Order => Order details page, the option "Amount of your choice:" is not displayed when we try to return a discounted product 

#### Steps to Reproduce

1. Go to BO => Customer Service => Merchandise Returns page
2. Enable returns and Save
3. Create a cart rule with a discount 20% for example without code or with code
3. Go to the FO => Add to cart more than 2 products => Process to checkout 
4. Go to BO => Order => Order details page => change the status of the last order to `shipped`
5. Click on the "Return products" button
6. Select a product to return
7. See error: The option "Amount of your choice:" is not displayed
![image](https://user-images.githubusercontent.com/16067358/77669978-dac68c00-6f85-11ea-98f5-e4b4f70eee6c.png)

It was well displayed in the PS1.7.6.4
![image](https://user-images.githubusercontent.com/16067358/77669916-c8e4e900-6f85-11ea-88fb-d7116915e3ce.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @colinegin @PrestaShop/prestashop-product-team, there is an option is missing in the Order page.

Thanks!

**Comment by khouloudbelguith** [comment]
Related to #18319

**Comment by MatShir** [comment]
The field was deliberated removed. The objective of the field was to customize the voucher value but it was only displayed when a voucher was applied. So to customize a voucher on return product, the order has to have a voucher applied in the order.  

To harmonize the behaviors, we put the specific custom edition into the partial refund button and set return product button with straightforward options.
@colinegin if it fine with you I will close this issue.

**Comment by colinegin** [comment]
I'm ok with this decision. @MatShir can you put the link to the related specifications so that everyone can access it ? Thanks !

**Comment by MatShir** [comment]
Find [here](https://github.com/PrestaShop/prestashop-specs/blob/master/Order%20Page%20View.md) the updated specs. Thanks @khouloudbelguith
