### ISSUE TITLE
Wrong currency sign in new order list

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18330]
#### Describe the bug

In order listing, when an order is made in a currency different from the default one, the currency sign is wrong : It's the sign from the default currency instead of the one from the order.

#### Expected behavior

Order's currency sign should be displayed.

#### Steps to Reproduce

1. In BO : Add a second currency to shop
2. In FO : Make an order with the new currency
3. In BO : Go to order list, the currency sign of the created order is wrong

**Screenshots**

On this example, order was made in DZD. In listing, the total price is wrong ("€13,848.70" instead of "DZD13,848.70"). The detail of each product is OK.
![order listing currency wrong](https://user-images.githubusercontent.com/55688534/77663253-27f23000-6f7d-11ea-8e22-addf1b394562.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
@Robin-Fischer-PS Or maybe the sign is good but the order total should be converted into the currency ? So in your example it should be 101,30€ (= 13,848.70DZD).

@MatShir question for PM I guess
Shoud orders, in the listing, be displayed _in the currency they were paid_ or displayed _in the shop main currency_ ?

**Comment by Robin-Fischer-PS** [comment]
@matks In Legacy (176x) the currency sign was modified. But the conversion is also a good solution, if the merchant does not have in mind all conversion rates !

**Comment by MatShir** [comment]
@matks @Robin-Fischer-PS  good suggestion, so If the merchant has multishop enable. It will display the order on the shop's default currency. I'm doing a few tests on 176, I will confirm you soon as I can.

**Comment by MatShir** [comment]
@matks @Robin-Fischer-PS I recommend displaying the currency used by the Front-Office customer. The order page is not a page for managing order turnover. If a customer has a problem with his order, it will be easier to find it if the total of his order matches the customer's order total. This also allows keeping coherence between the detailed order page and the order list.

But it's interesting as a suggestion, Magento allows to display the total in the default currency and the customer's one if the merchant wishes.

**Comment by matks** [comment]
OK I add the "PM ✔️" label as we have confirmation we must display the currency being used to pay the order

**Comment by Progi1984** [comment]
Fixed by #18419
