### ISSUE TITLE
Back office bug

### ISSUE THREAD

**Issue by V4LVE** [PrestaShop/PrestaShop#18335]
#### Describe the bug

Im trying to edit my store. I can access the store, but everytime i try to change something it crashes back to the login screen to the back office

#### Expected behavior

Being able to actually edit my store.

#### Steps to Reproduce

1. Log on
2. Click on Design
3. Click on Theme and logo
4. Change the image
5. Press save
6. Crashes me back to login screen 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

I entered debug mode and it get me this when i try to connect to the back office.

![image](https://user-images.githubusercontent.com/62727649/77706109-bf797200-6fc1-11ea-9e46-92e98319dd9d.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by JBWModules** [comment]
Wrong PHP Version, Prestashop 1.7.6. is only compatible to PHP 7.2

**Comment by sarahdib** [comment]
Hello @V4LVE 

Thank you for the report
PrestaShop 1.7.6 isn't compatible withe php 7.3.

You need to contact your hosting provider and ask him to switch to php 7.2 like @JBWModules said.

Have a  nice day.

**Comment by V4LVE** [comment]
I changed it to 7.2 still same issue

Den fre. 27. mar. 2020 kl. 09.35 skrev Sarah Dib <notifications@github.com>:

**Comment by V4LVE** [comment]
I get a permission error now, please help

[image: image.png]
[image: image.png]

Den fre. 27. mar. 2020 kl. 17.02 skrev V4LVE_ <alex802c@gmail.com>:

**Comment by khouloudbelguith** [comment]
Hi @V4LVE,

If it is a permission issue, you need to check the problem with your host.
PS: the screenshot is not uploaded, you need to sign in to GitHub et upload pictures here.

Thanks!

**Comment by V4LVE** [comment]
Here are the pics 
![image](https://user-images.githubusercontent.com/62727649/77778420-40337f00-7051-11ea-9121-00b98a54a683.png)
![image](https://user-images.githubusercontent.com/62727649/77778440-4590c980-7051-11ea-9c96-6f8ed470fedd.png)

**Comment by khouloudbelguith** [comment]
@V4LVE, it is a server issue.
You need to check with your host.

Thanks!
