### ISSUE TITLE
Add the language and the shop concerned in the admin logs controller

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18340]
#### Describe the bug

The indicators present in the logs are not complete enough to allow us to understand the origin of certain problems, mainly when we are in a multiboutique context. 

#### Expected behavior

It will be interesting for example to know in which language and shop the action was made on the object. It's a little more verbose I think.

**Comment by PululuK** [comment]
Hi @marionf 

I will open my PR

Thanks

**Comment by marionf** [comment]
Good to hear, thank you @PululuK

**Comment by PululuK** [comment]
Hi @marionf @LouiseBonnard 
Could you give me access to edit this issue and assign it to me please? I will turn it into an **EPIC** dedicated to **Logs**. See https://github.com/PrestaShop/PrestaShop/pull/21075

Thanks
