### ISSUE TITLE
1-Click Upgrade error no funciona

### ISSUE THREAD

**Issue by s3rgiobl** [PrestaShop/PrestaShop#18349]
Hola,

Intento actualizar prestashop 1.7.5 a la ultima version estable pero el boton "Upgrade Prestashop Now" no funciona, no hace nada.

La versión instalada de 1-Click Upgrade es 4.10.1

¿Solución?

**Comment by sarahdib** [comment]
Hello 

Please, send your request in English.
English is the norm on GitHub

Thank you!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
