### ISSUE TITLE
Unable to update project with composer due to prestashop/php-cssjanus repository

### ISSUE THREAD

**Issue by presteus** [PrestaShop/PrestaShop#18344]
#### Describe the bug

Unable to update project with composer due to prestashop/php-cssjanus repository.
A RuntimeException occured when cloning prestashop/php-cssjanus repository.

#### Expected behavior

Project updated

#### Steps to Reproduce

1. Clone Prestashop develop branch
2. Use composer
```shell script
    COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction
```
3. See error

**Screenshots**

```shell script
Loading composer repositories with package information
Failed to clone the git@github.com:prestashop/php-cssjanus.git repository, try running in interactive mode so that you can enter your GitHub credentials

[RuntimeException]                                                                                           
Failed to execute git clone --mirror 'git@github.com:prestashop/php-cssjanus.git' '/root/.composer/cache/vcs/git-github.com-prestashop-php-cssjanus.git/'
Cloning into bare repository '/root/.composer/cache/vcs/git-github.com-prestashop-php-cssjanus.git'...       
Host key verification failed.                                                                                
fatal: Could not read from remote repository.                                                                
                                                                                                             
Please make sure you have the correct access rights and the repository exists.
```

#### Additional information

* PrestaShop version: Develop branch
* PHP version: 7.3
* Docker image: php-fpm-buster

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers  What do you think about this issue ?

**Comment by matks** [comment]
@presteus it seems your CLI cannot fetch repository https://github.com/PrestaShop/php-cssjanus

Maybe a firewall issue 🤔? Or you used too heavily github recently and you reached GitHub Download Limit (if yes, try providing github authentication to composer as authenticated rate limit is higher than anonymous rate limit) ?

**Comment by presteus** [comment]
@matks Thank you, this is the reason

```shell script
 curl -i https://api.github.com/users/octocat
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1585321868
Content-Length: 250
X-GitHub-Request-Id: E055:12386:450DCD:5202E6:5E7E13F7

{"message":"API rate limit exceeded for 109.208.112.146. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Workaround**
Create a Github Token at https://github.com/settings/tokens
Configure composer
```shell script
composer config github-oauth.github.com "$GIT_TOKEN"
```

**Comment by qualityangel** [comment]
I have the same here, but don't know how to integrate the composer config solution given by @presteus

**Comment by matks** [comment]
@qualityangel you can read about it here http://allan-simon.github.io/blog/posts/solve-composer-github-api-limitation/

**Comment by qualityangel** [comment]
> @qualityangel you can read about it here http://allan-simon.github.io/blog/posts/solve-composer-github-api-limitation/

Your the best! thanks!
