### ISSUE TITLE
[BO] Can't remove discount added from a cart rule on product selection after adding a product in order

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#18379]
#### Describe the bug

Can't remove discount added from a cart rule on product selection after adding a product in order

#### Expected behavior

Can remove discount added from a cart rule on product selection after adding a product in order

#### Steps to Reproduce

1. Create a product A (100€, 100 items in stock, available)
2. Create a cart rule:
  - has no code
  - product selection on previous created product with 100 euro tax included
  - discount amount of 500 EUR tax included
3. In BO, add the product to a previous order
4. The discount has been added to order
5. **ERROR :** The discount can't be removed

Edit by @Robin-Fischer-PS :
6. Go back to the order after trying to delete the discount
7. The voucher is no longer displayed but the discount is still applied in the total of the order

Video from @Robin-Fischer-PS : 
https://drive.google.com/file/d/1yXPaN5rDVTXcLychf1ft3e_3RbblR3QT/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x branch

**Comment by khouloudbelguith** [comment]
Hi,

This issue could be reproduced when https://github.com/PrestaShop/PrestaShop/pull/18205 is merged.
In the PS1.7.6.4 => there is no exception.
https://drive.google.com/file/d/1x-CPIv-Fl8PpWKI92wucIaFLjGTEmPpM/view?usp=sharing

Thanks!

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

I added 2 more steps, after trying to delete, the voucher is no longer displayed but the discount is still applied.

**Comment by Progi1984** [comment]
@khouloudbelguith #18205 is merged

**Comment by khouloudbelguith** [comment]
@Progi1984, @Robin-Fischer-PS,

>Edit by @Robin-Fischer-PS :
>6. Go back to the order after trying to delete the discount
>7. The voucher is no longer displayed but the discount is still applied in the total of the order

I have the same issue with the branch 1.7.7.x

Thanks!

**Comment by Hlavtox** [comment]
@Progi1984 @colinegin If the discount has no code, it should not be deletable, hm? (If the desired behavior is the same as in FO.)

In my opinion, a better way would be NOT TO apply any vouchers automatically, when changing/creating order in BO. This way you keep full control of the order in BO.

(I think it would be impossible to tell Prestashop not to use this voucher in this order, it would add it every time you change something in it. And you would be deleting it over and over again.)

**Comment by colinegin** [comment]
ping @MatShir, i let you check @Hlavtox's comment and see if you need to update specs

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-product-team

**Comment by MatShir** [comment]
> @Progi1984 @colinegin If the discount has no code, it should not be deletable, hm? (If the desired behavior is the same as in FO.)
> 
> In my opinion, a better way would be NOT TO apply any vouchers automatically, when changing/creating order in BO. This way you keep full control of the order in BO.
> 
> (I think it would be impossible to tell Prestashop not to use this voucher in this order, it would add it every time you change something in it. And you would be deleting it over and over again.)

Hi @Hlavtox,

Why do we need to apply any voucher automatically?
- Merchants with a large catalogue depend on the automation of its cart rules. 
- We can also imagine that the e-commerce team is not aware of all the discounts applied. 

The cart rule specific to a product can be added to the order when this product is added.
It should, therefore, be possible to remove the cart rule.
If the product is deleted then the cart rule should be deleted as well because it does not meet any of the cart rules' requirements.

**Comment by Progi1984** [comment]
Fixed by #18532
