### ISSUE TITLE
ps_shoppingcart don't work if add a second languaje

### ISSUE THREAD

**Issue by cbatista8a** [PrestaShop/PrestaShop#18372]
#### Describe the bug

When adding a second language to prestashop, the ps_shoppingcart module cannot find the url of the controller in charge of updating the cart.

#### Expected behavior

The modal dialog is expected to appear indicating whether to proceed with the checkout and the cart is updated in the front office.

#### Steps to Reproduce

1- Add a second language
2- On the home page add product to cart
3- Nothing happens.
4- refresh the page to see the updated cart

**Screenshots**

#### Additional information

PrestaShop version: 1.7.6.3
Server software version: nginx / 1.16.1
PHP version: 7.2.29
MySQL version: 10.4.12-MariaDB

**Comment by Gipielle** [comment]
Check in CMS page if the url is setted

**Comment by cbatista8a** [comment]
> Check in CMS page if the url is setted

yes 
data-refresh-url="http://localhost/it/module/ps_shoppingcart/ajax"

if i edit the html and remove the language from the url then it works

**Comment by khouloudbelguith** [comment]
Hi @cbatista8a,

I did not manage to reproduce the issue with PS1.7.6.4 and the `ps_shoppingcart` module v2.0.3.
I attached a screen record
https://drive.google.com/file/d/1EMkn3Zpy6XZHo1oKlCwnNno4B-zUcipu/view?usp=sharing
What is the exact version of `ps_shoppingcart` did you use?
In your BO => Modules => Module Manager page => search for the `ps_shoppingcart` module, click on the configure & check if the `Ajax cart` option is enabled or disabled?
![image](https://user-images.githubusercontent.com/16067358/73372416-7655bc00-42b7-11ea-9935-faf9f599d4a3.png)

Thanks!

**Comment by cbatista8a** [comment]
ps_shoppingcart version is v2.0.3
and ajax is activated, but even deactivating it does not change the behavior
https://drive.google.com/open?id=1an7jJ5OTyOTuZuMeV-hqbJ3HMI186h2Q

url with more than one active language
https://drive.google.com/open?id=1neB3BWxMmvvItqsuaRbzdPSi1IUWdVhr

error in ajax call to update cart
https://drive.google.com/open?id=13hiunhfQLeHsJ1gifcgmCxCfdt6ixess
https://drive.google.com/open?id=1aVCeWzbATZqGqSvPXFSzH53EGLq5MvT0

**Comment by khouloudbelguith** [comment]
@cbatista8a,

>but even deactivating it does not change the behavior

We are aware of this issue, please follow this: https://github.com/PrestaShop/PrestaShop/issues/10025 => Cart without ajax not functioning.

It could be a problem in your Nginx configuration, thanks to check this [link](https://github.com/PrestaShop/PrestaShop/blob/e51d7eaa0164118b88d8cdcddbbe60e64aff7c64/docs/server_config/nginx.conf.dist)
Recently, this file is updated to show how to use multishop and multilanguage as fixed [here](https://github.com/PrestaShop/PrestaShop/pull/12082/files).

Thanks to check and feedback.

**Comment by cbatista8a** [comment]
# [REQUIRED EDIT IF MULTILANG]
    rewrite ^/it$ /it/ redirect;
    rewrite ^/it/(.*) /$1;

on Nginx and it's work finally

**Comment by khouloudbelguith** [comment]
@cbatista8a, Great!

Since, it is fixed, I will close the issue.
Feel free to open a new one when needed.

Thanks!
