### ISSUE TITLE
BO - Order - Wrong declination reference displayed on pack composition

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18370]
#### Describe the bug

In the BO => Order page => when a pack is ordered => the combination reference is not displayed, product reference is displayed instead.

#### Steps to Reproduce

1. Go to a declination detail 'T-shirt imprimé colibri Taille - S, Couleur - Blanc
2. Add a reference: demo_1_S_BLANC
3. Create a pack product
4. Add the declination to the pack: the declination reference is displayed. i.e. `demo_1_S_BLANC`
5. Save
6. Go t the FO => add the pack created to the cart and process to checkout
7. Go to the BO => Orders page => View the last Order created
8. Click on the link "View pack content" 
9. The product reference `demo_1` is displayed instead of declination reference `demo_1_S_BLANC`
![image](https://user-images.githubusercontent.com/16067358/77918911-d27b9300-729c-11ea-9a49-9df53c415639.png)
![image](https://user-images.githubusercontent.com/16067358/77919432-78c79880-729d-11ea-9f85-4c377b33edf9.png)

#### Additional information

* PrestaShop version: 1.7.5.2, PS1.7.6.4, develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/17957

**Comment by PululuK** [comment]
Hi @khouloudbelguith 

Can you check if this PR https://github.com/PrestaShop/PrestaShop/pull/17972 fixes this issue? If not, you can assign it to me please!

Thanks

**Comment by khouloudbelguith** [comment]
@PululuK, no, I have the same issue with develop branch also.

Thanks!

**Comment by PululuK** [comment]
> @PululuK, no, I have the same issue with develop branch also.
> 
> Thanks!

But ... In your screen, I see Prestashop 1.7.7.0 🤔 ?

**Comment by khouloudbelguith** [comment]
@PululuK, in the develop branch, the version is still 1.7.7.0: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/install_version.php#L27

Thanks!

**Comment by PululuK** [comment]
Yes yes .. My bad, sorry @khouloudbelguith  !
