### ISSUE TITLE
FO - An error on favicon when maintenance mode is enabled

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#18385]
#### Describe the bug

On fresh install of PS 1.7.6.4, if "Maintenance" mode is enabled, I get a 503 error on favicon.

#### Expected behavior

Get a 200 on favicon file.

#### Steps to Reproduce

Steps to reproduce the behavior: Firefox V74

1. Install PS 1.7.6.4
2. Enable "Maintenance"
3. Go to front and check favicon status on "Network" devtool's tab. For me: 503/404
4. Try to change favicon in BO + clear cache
5. Go back to front and check favicon status on "Network" devtool's tab. For me: 503 /404
![image](https://user-images.githubusercontent.com/16067358/78046921-0c6d9780-7378-11ea-9aac-259121098e76.png)

May be related to my specific server config but I want to know if it can be reproducible?
Thanks for your answer.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1
* Apache

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

I attached a screen record
https://drive.google.com/file/d/1irt5owIVodWgvUROSwMAddkMpG62vR-j/view?usp=sharing
The error 503 is not for the favicon, it for the shop URL.
`503 Service Unavailable`
The server cannot handle the request (because it is overloaded or down for maintenance). Generally, this is a temporary state.
=> In our case, our shop is in a maintenance mode => 503 is normal behavior.

Thanks to check and feedback.

**Comment by Klemart3D** [comment]
Well, it's strange you don't have favicon ressource in your loaded data.
I checked with Firefox v74.0 + Chrome v80.0, I have it both:

![503 favicon with FF + chrome](https://user-images.githubusercontent.com/7419525/78034337-e3450b00-7367-11ea-8728-43c6e2e13ab3.png)

But another way to detect problem is favicon is not loaded (in your browser tab title).
We must find the "preston" favicon even if shop is maintenance is not it?

**Comment by khouloudbelguith** [comment]
@Klemart3D, I tried with firefox v74, I have a 404 error
![image](https://user-images.githubusercontent.com/16067358/78042041-cad9ee00-7371-11ea-9f1d-30d64ab2089b.png)
Reproduced with PS1.7.5.2, PS1.7.6.4, and the branch 1.7.7.x.
Thanks to check and feedback.

**Comment by Klemart3D** [comment]
404 is also a bad response!
The link to favicon must be like when shop in not in maintenance, by sample the good favicon link for my shop is:  _favicon?1575295785_  not _/favicon.ico_

I think it's because it missing a `<link rel="icon">` tag in [layout-error.tpl](https://github.com/PrestaShop/PrestaShop/blob/7633be8294d90148d2bdfe3fd1c2d403e72ec91b/themes/classic/templates/layouts/layout-error.tpl) like in [head.tpl](https://github.com/PrestaShop/PrestaShop/blob/7633be8294d90148d2bdfe3fd1c2d403e72ec91b/themes/classic/templates/_partials/head.tpl#L53). But I'm not sure if `$shop.favicon_update_time` variable is instantiate for errors layout?
If it can be confirmed by an integrator, i can make a pull request.

**Comment by khouloudbelguith** [comment]
@Klemart3D, thanks for your feedback.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
