### ISSUE TITLE
TAX Included

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#18397]
I'm struggling to get my site to say TAX Included, no matter what I try it always says TAX Excluded, what am I missing here or is it an issue?

Thank you in advance

Allthejam

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

Thanks for your report.
In your BO => Shop Parameters => Customer Settings page => Groups Tab => Edit Group you want =>change the "Price display method" to Tax included.
![image](https://user-images.githubusercontent.com/16067358/78036932-28b70780-736b-11ea-95bb-2fd914c8c423.png)

Thanks to check and feedback.

**Comment by Allthejam** [comment]
Thank you for that, it was about the only thing I hadn't tried, one quick one see image, but how do I get the **£** symbol to appear on the left side of the price 
![2020-03-31_152256](https://user-images.githubusercontent.com/52738920/78037496-8e06fa80-7363-11ea-92b9-2306581e503d.jpg)

**Comment by khouloudbelguith** [comment]
@Allthejam, Great!
>but how do I get the £ symbol to appear on the left side of the price

This feature will be available in the next version PS1.7.7.0.
![image](https://user-images.githubusercontent.com/16067358/78038611-4f763d80-736d-11ea-951d-dd744acc6c16.png)

Since it is OK, I will close the issue, feel free to open a new one when needed.

Thanks!
