### ISSUE TITLE
Español - Error showing the quantity of products in each brand

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18395]
#### Describe the bug

En el apartado marcas de mi web, cuando hay 0 productos dentro de una marca, se muestra "producto 0".
Cuando hay 1 producto en esa marca, se muestra "producto 1"
Cuando hay más de 2 productos, se muestra "2 productos"
Lo correcto es que siempre se muestre "# productos" (siendo # el número de productos que hay de esa marca)

#### Expected behavior

Lo correcto es que siempre se muestre "# productos" (siendo # el número de productos que hay de esa marca)

#### Steps to Reproduce

1. Go to 'marcas'
2. Scroll down to 'cualquier marca'

**Screenshots**

https://imgur.com/a/lHuO6L0

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.4.4

--------------------------------------------------------------------------------------------------------------

<! -
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
->

#### Describe the bug

In the brands section of my website, when there are 0 products within a brand, "product 0" is displayed.
When there is 1 product in that brand, "product 1" is displayed
When there are more than 2 products, "2 products" is displayed
The correct thing is that "# products" is always shown (being # the number of products of that brand)

#### Expected behavior

The correct thing is that "# products" is always shown (being # the number of products of that brand)

#### Steps to Reproduce

1. Go to 'brands'
2. Scroll down to 'any brand'

** Screenshots **

https://imgur.com/a/lHuO6L0

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.4.4

**Comment by khouloudbelguith** [comment]
Hi @alfonsolr09,

First, PrestaShop is not compatible with PHP 7.3 and PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Second, I did not manage to reproduce the issue with PS1.7.6.4 and the default theme Classic.
![image](https://user-images.githubusercontent.com/16067358/78043418-9a934f00-7373-11ea-90c7-4230fe42c7ee.png)

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by alfonsolr09** [comment]
¿puede ser que el error lo provoque el idioma?
mi tienda está en español

-------------------------------------------------
Could it be that the error is caused by the language?
my store is in spanish

**Comment by alfonsolr09** [comment]
mi version de php que pone en prestashop es esta Versión PHP: 7.2.29
la otra versión es la que pone en el plesk de mi proovedor de alojamiento

---------------------------------

my version of php that puts in prestashop is this PHP Version: 7.2.29
the other version is the one that puts in the plesk of my hosting provider

**Comment by alfonsolr09** [comment]
@khouloudbelguith 
debe ser por el idioma de la tienda, al cambiarlo se produce el error. ¿puedes comprobar en castellano?

------------------------------

It must be for the language of the store, when changing it the error occurs. Can you check in spanish?

**Comment by khouloudbelguith** [comment]
@alfonsolr09, thanks to check this screen record to fix the issue.
It is a translation of the Spanish language
https://drive.google.com/file/d/1clP1Hp4r_EFU5gCs5R1411kSknC3i95e/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/78132145-80617b80-741c-11ea-890d-d58c7ba2f03c.png)

Thanks!

**Comment by alfonsolr09** [comment]
@khouloudbelguith thankssssssss !!!

:)
:+1:
