### ISSUE TITLE
Missing modal to confirm or cancel the deletion of a customer address (in bulk)

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18414]
#### Describe the bug

It was planned to add a modal to confirm or cancel the bulk deletion during the migration of the page but it was not done #10557

#### Expected behavior

Add a modal to confirm or cancel the deletion of many rows

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #18464
