### ISSUE TITLE
Missing modal to confirm or cancel the deletion of an order message (in bulk)

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18415]
#### Describe the bug

It was planned to add a modal to confirm or cancel the bulk deletion during the migration of the page but it was not done #10555

#### Expected behavior

Add a modal to confirm or cancel the deletion of many rows

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by zuk3975** [comment]
The bulk action in `/sell/customer-service/order-messages` is generic as in all other pages, should i make it custom, or are we planning to add bulk action modals to all pages with some generic message?

**Comment by Progi1984** [comment]
Fixed by #18641
