### ISSUE TITLE
Reduced left menu has become scrollable until he disappears

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18412]
#### Describe the bug

In the BO, the reduced left menu has become scrollable until he disappears 

#### Steps to Reproduce

1. Go to BO => Shop Parameters => Merchant Expertise / Search page
2. Reduce the Left menu 
2. Make a zoom of your window  >= 125% 
3. Try to Click on the icon Shop Parameters
4. See error => the reduced left menu has become scrollable until he disappears 

**Screenshots**
https://drive.google.com/file/d/1RQpuGzUDK8xN-7O9YisEeyzzflEGo7O7/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/78117634-2d7cc980-7406-11ea-977a-9fc3234ebe35.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
The issue could be related to this PR: https://github.com/PrestaShop/PrestaShop/pull/17426
Ping @NeOMakinG 
Issue reproduced by @SD1982 also.

Thanks!

**Comment by NeOMakinG** [comment]
Hey @khouloudbelguith Do you have an error in your console ? It looks like it's linked to a JS error/problem

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG, no errors.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #18416

**Comment by Gipielle** [comment]
Please stop develop this useless features and use the resources to solve the serious problems of prestashop, I think that no merchant is interested in this game within prestashop. Perhaps they would prefer concrete solutions to the specific prestashop problems.
