### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /src/Adapter/ContainerFinder.php:77

### ISSUE THREAD

**Issue by Franejre** [PrestaShop/PrestaShop#18421]
Hello everyone i have a big probleme 

i have a module payement , everything works fine , but when get redirect to my prestashop i get on error 500 page , if i stay on the page and refresh it i get a error "this shopping cart id have been already use"

here is the error log i have find

[01-Apr-2020 13:20:02 Europe/Paris] PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /home/cbdptlvp/public_html/src/Adapter/ContainerFinder.php:77
Stack trace:
#0 /home/cbdptlvp/public_html/classes/Tools.php(796): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer()
#1 /home/cbdptlvp/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))
#2 /home/cbdptlvp/public_html/classes/PaymentModule.php(429): ToolsCore::displayPrice(9, Object(Currency), false)

kernel error ? how i can solve this  ?

Prestashop 1.7.6.4 fresh from this morning i have totaly erase the last one to avoid any upgrade error and i still have this error

**Comment by matks** [comment]
@Franejre How do you reach back PrestaShop ? You must go through a regular controller to ensure the setup is correct

Have a look for https://github.com/PrestaShop/PrestaShop/issues/14648

**Comment by khouloudbelguith** [comment]
Hi @Franejre,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by Franejre** [comment]
ok because i thinks it could be a error due to prestashop 1.7.6.4? as the error kernel is in prestashop file and not in module files

**Comment by khouloudbelguith** [comment]
@Franejre, as you can see this [comment](https://github.com/PrestaShop/PrestaShop/issues/14648#issuecomment-515520400)
This is a module issue.
Please contact the module author and feedback.
In the meantime, what is the exact name of your module? bought from the Marketplace Addons PrestaShop?

Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
