### ISSUE TITLE
addons / customer-messages-detail.php fails with special character

### ISSUE THREAD

**Issue by germain-italic** [PrestaShop/PrestaShop#18423]
Not sure if I should post here because the bug applies to addons.prestashop.com and not in Prestashop itself. Anyways, let's report.

#### Describe the bug

Typing the "lower than" character (`<`) in a message will cause the message to be cut/sliced.

#### Expected behavior

The character should be escaped properly with html entity (`&laquo;`) and the message should be displayed completely.

#### Steps to Reproduce

1. Open a thread at https://addons.prestashop.com/en/customer-messages-detail.php (my error appeared in thread #779112)
2. Type "hello < world" and save
4. See error: only "hello <" is displayed.

**Screenshots**

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Germain-Italic,

Thanks for your report.
Please be aware that this bug tracker should be used to report issues only. If you need help, you can ask on this [link](https://addons.prestashop.com/en/contact-us).

Thanks!

**Comment by germain-italic** [comment]
I don't need help, I found the cure myself.
I'm actually reporting an issue...
