### ISSUE TITLE
BO - Currencies Cancel button is not displayed at the good place

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18428]
#### Describe the bug

In BO => currencies => add new the cancel button is not displayed at the good place

#### Expected behavior

The cancel button should be displayed at the good place

#### Steps to Reproduce

1. Go to BO => International => Localization => currencies => add new
2. See error

**Screenshots**

**In 1.7.6.x it was like this :** 
![176](https://user-images.githubusercontent.com/40635814/78227160-2a004580-74cd-11ea-81ff-562bd26f2136.png)

In 1.7.7.x and develop it's like this : 
![177](https://user-images.githubusercontent.com/40635814/78227250-469c7d80-74cd-11ea-8272-aa57cb62295d.png)

#### Additional information

* PrestaShop version: 1.7.7.x , develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

Same issue with 177X Branch.

Thanks!!

**Comment by Progi1984** [comment]
Fixed by #18438
