### ISSUE TITLE
Error on update and hook a module 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18431]
#### Describe the bug

When I try to update or hook a module there is an error

#### Steps to Reproduce

1. Go to Modules 
2. Click on the update -> update all
3. See error

<img width="1268" alt="Capture d’écran 2020-04-02 à 13 34 15" src="https://user-images.githubusercontent.com/3034677/78251987-70b46680-74f2-11ea-9a1e-70b51fdd8f74.png">

1. Go to Design -> Positions -> Transplant a Hook
2. See the error
<img width="1275" alt="Capture d’écran 2020-04-02 à 13 33 30" src="https://user-images.githubusercontent.com/3034677/78252005-790ca180-74f2-11ea-8ea1-b1bbd7505a6b.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by apacios** [comment]
I have the same issue when installing a module.
It give an error but the module is well installed.

For all the modules I'm installing with the Symfony console, I'm getting this error : `ERROR     [app] The addon with id 26233 does not have name.` which seems to be the User Guide.

**Comment by khouloudbelguith** [comment]
Hi,

I have the same exception in only one shop when I make a search in the BO
![image](https://user-images.githubusercontent.com/16067358/78254426-2e8d2400-74f6-11ea-8516-8cd01dc322d5.png)
=> 
![image](https://user-images.githubusercontent.com/16067358/78254448-3baa1300-74f6-11ea-96aa-e71f45dc7d49.png)

Thanks!

**Comment by jaxtheking** [comment]
This message with the same exact id (26233) showed up in my logs.
We had never seen it before upgrading to 1.7.6.4.
Furthermore, in Advanced Parameters > Logs this error was associated with one of my admin users, who would've hardly been installing a module or transplanting a hook...

**Comment by Progi1984** [comment]
@sarahdib @khouloudbelguith I didn't reproduce any of your behaviors. Can I have a sample video ?

**Comment by jolelievre** [comment]
Maybe it comes from a module, having the complete list of installed modules might be useful for you @Progi1984 To make sure you have the same context

**Comment by Progi1984** [comment]
@jolelievre Actually, i'm on a fresh install. May be you have another plugins @sarahdib / @khouloudbelguith ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984, @sarahdib,

As I said previously, this issue was reproduced only with one shops in 1764, other shops 1764 => OK
Today, I tried again with 176x branch => OK => no errors
https://drive.google.com/file/d/15ztRhpSuCvNhxRuyJjd783eP-me2Zynm/view?usp=sharing

Ping @sarahdib 
Thanks!

**Comment by NereoEgeo** [comment]
Hello, I have PS 1.7.6.2 on the main domain and a test installation on a subfolder, on both the installation I see in the log the same message with my admin user:
The addon with id 26233 does not have name

Same day, different time 2020-04-01 10:35 for the main domain, 	2020-04-01 19:15 for the subfolder installation.

I have installed only a template from Leo and the wizard date delivery module

**Comment by sarahdib** [comment]
I think it was a problem from the API. Now it's OK
