### ISSUE TITLE
Refactor DeleteProductFromOrderHandler

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#18432]
- [x] #18564 : Refactor two handlers : 
- src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
- src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php

because updateOrder are nearly the same.

- [ ] Refactor handler src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php for using src/Adapter/Order/Refund/OrderProductRemover.php as service.

**Comment by colinegin** [comment]
Can be done after the beta has been released.

**Comment by colinegin** [comment]
@Progi1984  could you describe the issue more in details please ?

**Comment by Progi1984** [comment]
@colinegin It's technical for avoiding duplicate code in our codebase.

**Comment by colinegin** [comment]
Blocked by #19646 - to be done once merged

**Comment by matthieu-rolland** [comment]
This issue is treated in this PR:  #19981

**Comment by matthieu-rolland** [comment]
Issue closed, the refactor is not was planned in this issue.
