### ISSUE TITLE
Faceted Search Module Performance

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#18439]
#### Describe the bug

Mysql CPU is overloaded (more than 150%) when Faceted Search is active.
When disable, the mysql CPU is normal (between 10 and 30%).

#### Steps to Reproduce

Prestashop with multistore actived, about 10 shops with 1 domain for each.
about 10.000 products
about 1.000 categories

#### Additional information

Example in my mysql-slow.log

`# Query_time: 4.879676  Lock_time: 0.000061 Rows_sent: 0  Rows_examined: 0
use xxxxxx;
SET timestamp=1585834661;
REPLACE INTO ps_layered_filter_block (hash, data) VALUES ("d2e10829da5c6df4f959395a680ddb28", "a:1:{s:......`

This log file contains only this kind of queries (it's cache queries no ?)

This problem occured with the update of the module Faceted Search.

* PrestaShop version:  1.7.6.4
* PHP version: 7.1
* Module Faceted Search version: 3.5.0

**Comment by khouloudbelguith** [comment]
Hi @BoutiquesInternet,

The more products and categories you have, the more combination are saved in the database, this is why this table `ps_layered_filter_block` is growing. Don't hesitate to add the clear-cache script in a cron  :wink: 
I think you have an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/17318

Thanks to check and feedback.

**Comment by BoutiquesInternet** [comment]
Hi @khouloudbelguith ,

Thanks for your rapidity and for sharing this ticket.
I will try this solution and come back to you in few days if this works for me !

**Comment by khouloudbelguith** [comment]
@BoutiquesInternet, thanks!
Waiting for your feedback.

**Comment by BoutiquesInternet** [comment]
For a quick return :

I clear the cache manualy just for testing but the performance is not better and it fills up very fast (about 50 Mo in 20 min for 3.350 entries in the table).

So I think clearing the cache daily is not the solution here.

This is ugly but I just commented the function insertIntoCache() in Block.php file to temporarily resolve the issue

**Comment by khouloudbelguith** [comment]
@BoutiquesInternet, thanks for your feedback.
Ping @jocel1 @PierreRambaud what do you think?

Thanks!

**Comment by BoutiquesInternet** [comment]
Ok I'm stupid my bad, I got DDos by chinese bot

**Comment by khouloudbelguith** [comment]
@BoutiquesInternet, since it is ok.
I will close the issue, feel free to open a new one when needed.

Thanks!
