### ISSUE TITLE
 Modules not working propertly with default client groups 

### ISSUE THREAD

**Issue by Devcitaw** [PrestaShop/PrestaShop#18430]
I'm having a weird issue with my prestashop 1.7.6.4
I thought my image slider was not working properly because it wasn't updating its content in the front office, but then I noticed that my link widget and my highlighted products weren't updating its contents either.
I can see them, but the content is not the one I've put in them (link widget shows an old list, image slider doesn't change at all no matter what I change, Highlight just respond to id and not to product order and so)
I have tried cleaning the cache, reinstalling the product, pretty much everything.

While testing other stuff, I happened to notice that the modules works fine as long as I'm not within one of the three default client groups (guest, visitor, client).

I would greatly appreciate if you could help me figure this problem.

For now I'll try to fix it not using the default customer groups.
![Captura1](https://user-images.githubusercontent.com/48606042/78251603-f8d14680-74c7-11ea-8ab2-7e70c82f1169.PNG)
![Captura3](https://user-images.githubusercontent.com/48606042/78251609-fa9b0a00-74c7-11ea-9355-fc186d2769af.PNG)

![Captura2](https://user-images.githubusercontent.com/48606042/78251608-fa027380-74c7-11ea-9a84-f41b3436458a.PNG)
![Captura4](https://user-images.githubusercontent.com/48606042/78251614-fb33a080-74c7-11ea-8701-6df7127e901c.PNG)

**Comment by khouloudbelguith** [comment]
Hi @Kimcitaw,

memcached is enabled in your shop?
Is it similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/18171?

Thanks!

**Comment by Devcitaw** [comment]
Hi @khouloudbelguith,

Thanks for answering.

I've just checked and no, I have the caching in "Use cache: NO".
If I turn it on it shows this:

![Captura5](https://user-images.githubusercontent.com/48606042/78258038-08a15880-74d1-11ea-8581-64dc6941d538.PNG)

I've read the issue you tagged and tested the link widget (Trying to modify the content of the current one) and at first It wasn't showing changes but a minute after It did, so I guess is not the same problem.

**Comment by khouloudbelguith** [comment]
@Kimcitaw, I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1gJ97zKW6pxFgx5ZbWbrTrNPgduFXaar7/view?usp=sharing
I tried with a Customer Group.

Thanks to check and feedback.

**Comment by Devcitaw** [comment]
I know, I've checked other similar issues and forums and it seems the problem can't be replicated.

I've tried now to set again the original customer groups and everyting seems to have changed at how it should be, BUT if I make a new change, it doesn't affect the FO ... Again.
Even in the custom groups. 
I must create a new customer group and asign it as a defaault to see the changes :/

**Comment by khouloudbelguith** [comment]
@Kimcitaw,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Devcitaw** [comment]
Host:  Dreamhost
 Server setup and configuration: 
	Server information Linux #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64
	Server software version: Apache
	PHP version: 7.2.24
	Memory limit: 90M
	Max execution time: 30
	Upload Max File size: 64M

PrestaShop version (source) 1.7.6.4  (Downloaded directly from the PS webpage)

Logs attached
[access.log](https://github.com/PrestaShop/PrestaShop/files/4422634/access.log)
[error.log](https://github.com/PrestaShop/PrestaShop/files/4422635/error.log)


Please let me know if I forgot something.

**Comment by khouloudbelguith** [comment]
@Kimcitaw, about these errors
`[core:error] [pid 20948] [client 190.139.246.139:60848] End of script output before headers: index.php,`
=> I think it will come from timeout, it is a server issue.

Thanks to check with your host and feedback.

PS: in your access.log, I couldn't find any errors.

Thanks!

**Comment by Devcitaw** [comment]
So, i've been doing some test and I found a "solution" to this.

The one thing I must do is change the cache type from mySQL to File System. So far is working.
I can go back to mySQL but from time to time I must go back to File System again.

**Comment by khouloudbelguith** [comment]
Hi @Kimcitaw,

Thanks for your feedback.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
