### ISSUE TITLE
BO - Strange behavior in the add new Product page when the employee language is different from the default language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18447]
#### Describe the bug

When the default language is different from the employee's language, a strange behavior occurred when trying a new product.

#### Expected behavior

It should be like 1764
https://drive.google.com/file/d/1Av2ZukiF_ZyUkZKygCTjKVKc2cIOMnSl/view?usp=sharing

As described [in the specs](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#elements-in-all-tabs-epic):
Only the name in the employee language must be filled. If the name of the product is not indicated for the other languages, after saving the name of the product in the employee's language is retrieved and displayed for all the other languages. 

#### Steps to Reproduce

1. Install a new shop 1.7.7.x with `English` language and `France` country => the default language is English
2. Go to BO => Profiles page => Employee page => change the employee's language to "French
3. Go to the BO => Catalog => Products page
4. Click Add a new Product
5. Enter the product's name in the first language "Fr"
6. Select the second language "En"
7. the product name of this product is just copied from the other language => not the same behavior with PS1.7.6 => the field should stay empty at this step
8. Save
9. See error "Impossible de mettre à jour les paramètres" => The product name in the "Fr" is deleted automatically
![image](https://user-images.githubusercontent.com/16067358/78277631-1bd61780-7515-11ea-9e1d-e8fa6f789612.png)

**Screenshots**
https://drive.google.com/file/d/1K7lqT7znx4s5iPlOjxRSrv_qL7ibQelV/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #19086
