### ISSUE TITLE
must_have_modules_list.xml - ID 26233 - name missing

### ISSUE THREAD

**Issue by Cookyah** [PrestaShop/PrestaShop#18444]
Hi,
I use the fonction getModulesOnDisk() of class Module.php for one of my custom module and currently this function return an error because the file "must_have_modules_list.xml" available in "/config/xml/" contain an error.

The ID of module 26 233 (Guide Utilisateur - PrestaShop 1.7 (en anglais)) has an empty name.
Yesterday this work fine and today don't. 
I think you made an update and an error come up.
Can you please correct the xml file ?

When I noticed the error, I installed a new prestashop 1.7.6.3 locally, the error is also present so I open this issue.

Thank you for reading me, and please forgive me for my bad english. :)

#### Steps to Reproduce

1. Go to /config/xml/must_have_modules_list.xml and open it
2. Search ID 26233
3. See empty <name>

**Screenshots**
[https://i.gyazo.com/4c8e2b44da98413d582874694076b8a3.png](https://i.gyazo.com/4c8e2b44da98413d582874694076b8a3.png)
[https://i.gyazo.com/4d0d3afd6f39eec898f9e4c41da30462.png](
https://i.gyazo.com/4d0d3afd6f39eec898f9e4c41da30462.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Cookyah, 

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need to delete cache from your shop & your browser.
Thanks to check and feedback.

**Comment by Cookyah** [comment]
Hi @khouloudbelguith thanks for your quick reply.

I already try to clear cache of Prestashop manually and of my browser, it didn't work. :/
I use Google Chrome so I also try to change my browser to go on firefox and install a fresh prestashop, the same error show up.

If I set a custom text like "test" to fill the field <name></name> in the "must_have_modules_list.xml" file, it's work.

Did I need to manually delete the file "must_have_modules_list.xml" ?
This file should be recreated automatically with addons api ?

Regards

**Comment by khouloudbelguith** [comment]
@Cookyah, Thanks to delete the `must_have_modules_list.xml` file into the path `PROJECT_FOLDER/confix/xml`, check & feedback.
It should be automatically created.

Try to make a backup first to be safe!

Thanks!

**Comment by Cookyah** [comment]
@khouloudbelguith 

Thanks, deleting the `must_have_modules_list.xml` correct the problem.
I think there was a problem with the previous update of this file.

I close the issue.

Thanks you so mutch for your time and expertise. :)
Regards

**Comment by khouloudbelguith** [comment]
@Cookyah, Great!

Feel free to open a new one when needed.

Thanks!
