### ISSUE TITLE
All modules Changelog are not displayed in the backoffice

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/PrestaShop#18450]
#### Describe the bug

In the modules updates screen admin/index.php/improve/modules/updates changelog are not displayed.

![changelog](https://user-images.githubusercontent.com/720961/78335515-094bf480-758e-11ea-8018-4e668de0f877.png)

#### Expected behavior

When there is a new version of a module the changelog MUST BE provided before the merchant decide to upgrade or not.

#### Additional information

Could be that this information is only available if you have authenticated the shop with the PrestaShop addons platform. This can't be the expected behavior.

Sample addons API call with a changelog inside:
https://api-addons.prestashop.com/?method=listing&action=module&id_module=296&format=json

The addons API is documented here:
https://docs.google.com/document/d/1gEoTVJQXmNZHZM-pGTx0ztAP-578Xybezx-EALGthCA/edit
(private PrestaShop document)

* PrestaShop version: at least all 1.7.6.x

**Comment by khouloudbelguith** [comment]
Hi @toutantic,

I have the same issue with PS1.7.5.2, PS1.7.6.4, and the branch 1.7.7.x.
Ping @eternoendless 
Thanks!

**Comment by atomiix** [comment]
Hi,

After investigation, here is how this page works:

We call api-addons.prestashop.com with `method=listing` and `action=`

* must-have
* service
* native
* native (with `&iso_code=all`)
* customer (if the BO is connected to addons)

We then iterate on modules installed on the shop and map the api informations with those modules but none of those API calls return the key `changeLog` needed to show the changelog on the update page of the BO.

Adding this keyon the api-addons API would solve the issue.

**Comment by LouiseBonnard** [comment]
We need to create a Jira ticket to have this checked with the platform team.

**Comment by sam-pires** [comment]
Here is the issue in the Platforms team's Jira: http://forge.prestashop.com/browse/PLFS-2424 (PS employees only)

**Comment by sam-pires** [comment]
Waiting for the Platforms team to work on the API on their side before continuing working on it

**Comment by colinegin** [comment]
The work on the API will allow to display modules' changelog. Nothing to do on core side.

We then need to work on PrestaShop native modules to include the module's changelog

**Comment by LouiseBonnard** [comment]
@colinegin and @atomiix, PlatForms ticket has just been noted as _done_, see [here](http://forge.prestashop.com/browse/PLFS-2424).

**Comment by colinegin** [comment]
Amazing !

**Comment by matks** [comment]
> @colinegin and @atomiix, PlatForms ticket has just been noted as _done_, see [here](http://forge.prestashop.com/browse/PLFS-2424).

According to @atomiix even though the work is done, it is not available on the Production API.

Since we have no Pre-Production API, there's no way to test this feature yet. We must wait for Addons API to be updated in Production then we can test.

**Comment by Progi1984** [comment]
Fixed by #19778
