### ISSUE TITLE
Checkout process stops after payment

### ISSUE THREAD

**Issue by januszszymanski** [PrestaShop/PrestaShop#18455]
I get an error 500 when trying to approve a payment.

![Screenshot from 2020-04-03 14-41-46](https://user-images.githubusercontent.com/28387074/78361908-74f78700-75b9-11ea-9680-f06055f3bc59.png)

Logs:
```
*ERROR* 	v1.7.6.4	2020/04/03 - 11:38:53: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 11:43:36: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 12:18:36: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 12:21:44: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 12:34:53: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 12:36:58: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
*ERROR* 	v1.7.6.4	2020/04/03 - 12:39:12: Property OrderPayment->id_currency is empty. at line 1003 in file classes/ObjectModel.php
```

If i replace in `/var/www/page/classes/order/OrderPayment.php`
```
            'id_currency' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true),
            'amount' => array('type' => self::TYPE_FLOAT, 'validate' => 'isNegativePrice', 'required' => true),
```
to 
```
            'id_currency' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => false),
            'amount' => array('type' => self::TYPE_FLOAT, 'validate' => 'isNegativePrice', 'required' => false),
```
checkout starts to work "correctly" (Both items(id_currency and amount) need to be changed from true to false)

#### Steps to Reproduce

1) Go through all the steps when ordering
2) Click order confirmation
3) Checkout process stops after payment

![Screenshot from 2020-04-03 14-41-46](https://user-images.githubusercontent.com/28387074/78361908-74f78700-75b9-11ea-9680-f06055f3bc59.png)
**Screenshots**

#### Additional information

* PrestaShop version:  1.7.6.4
* PHP version: 7.2.28
* Stripe payment module: v2.0.8 - by 202 ecommerce

**Comment by khouloudbelguith** [comment]
Hi @spink90,

Did you use a custom payment module? what is this exact module?
Does this issue occur with other payments module provided by PrestaShop?
>I get an error 500 when trying to approve a payment.

PrestaShop has a debug mode, which can be used to see the non-obvious errors on your shop.
To turn on the Debug mode on PrestaShop 1.7, follow these steps:

1. Got to Advanced Parameters > Performance
2. In the Debug Mode section, set “Debug Mode” to “Yes”.
3. Click the “Save” button.

Thanks to check and feedback

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
