### ISSUE TITLE
unable to upload product image in PrestaShop 

### ISSUE THREAD

**Issue by rawan321** [PrestaShop/PrestaShop#18466]
im not able to choose or drop a pic from anywhere for my product image.
im using prestashop_1.7.4.4
its not clickable.
any one have an idea?
![Untitled](https://user-images.githubusercontent.com/63139645/78420084-89d52880-7654-11ea-931a-573d99e05044.png)

**Comment by khouloudbelguith** [comment]
Hi @rawan321,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TristanLDD** [comment]
Hi @rawan321,
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can provide more details.
Thank you!
