### ISSUE TITLE
FO - Exception in the Brand page,  the prices-drop, new-products, best-sales page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18460]
#### Describe the bug

When the debug mode is enabled, In the FO => Brands => specific brand page => an exception is displayed

it is ok with PS1.7.7.x, PS1.7.6.4
#### Steps to Reproduce

1. Enable debug mode
2. In the BO => Shop Parameters => General page
3. Enable "Display brands" 
4. Go to FO => Sitemap => Brands page
5. Click on any Brand to see the list of products for example "Graphic Corner"
6. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/78376245-5354ca80-75ce-11ea-9db9-f107c2056f06.png)
https://drive.google.com/file/d/1eRxpm02TZd_HPrwSdV61yWzkuJFDPz4r/view?usp=sharing

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi,

Same issue in the prices-drop, new-products, best-sales pages.

Thanks!

**Comment by sam-pires** [comment]
@PierreRambaud  A similar bug has been fixed by a PR recently, to be checked, might be related

**Comment by PierreRambaud** [comment]
I confirm that I don't manage to reproduce the issue with latest version of PrestaShop. (1.7.7.x & develop branches)

**Comment by PierreRambaud** [comment]
@sam-pires FYI, the problem is already fixed :wink:
