### ISSUE TITLE
Error when accessing connected users stats w/ maintenance mode and IPv6 whitelisted addresses

### ISSUE THREAD

**Issue by jevarg** [PrestaShop/PrestaShop#18469]
#### Describe the bug

When a user has a whitelisted **IPv6** address in the maintenance mode, there is an exception thrown in **statslive** module when trying to access number of users online (both customers and visitors).

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

In order to see the actual error I suggest you to enable _debug mode_.

1. Activate _Maintenance mode_
2. Add any IPv6 address as whitelisted
3. Go to _Stats_

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by jevarg** [comment]
Forgot to mention, I have made a quick PR
https://github.com/PrestaShop/statslive/pull/11

**Comment by khouloudbelguith** [comment]
Hi @jevarg,

The Maintenance IP filtering doesn't support ipv6 client addresses as reported here: https://github.com/PrestaShop/PrestaShop/issues/16032
https://drive.google.com/file/d/1jFCVKJp3UPvBcFuVzgIsiN2isrDQlFMH/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/78546679-1cfd9200-77fe-11ea-9bbf-469a41229f16.png)

Thanks to check and feedback.

**Comment by jevarg** [comment]
Hi @khouloudbelguith 
My issue is not about maintenance mode supporting ipv6 whitelist.

Whether or not ipv6 maintenance whitelist works, I think the intended behavior is not to have an exception thrown when trying to access **statslive**.
As you can see in my PR: https://github.com/PrestaShop/statslive/pull/11 this is just a quick fix to ignore whitelisted ipv6 in statslive and not about ipv6 being actually filtered or not.

**Comment by khouloudbelguith** [comment]
@jevarg, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.4 and `statslive` module v2.0.2.
![image](https://user-images.githubusercontent.com/16067358/78581765-9912cc80-7834-11ea-9956-00d91031dca4.png)
I’ll add this to the debug roadmap.

Thanks!
