### ISSUE TITLE
FO - `ps_brandlist` module - The title link for the Brands is not working when "Display brands" is enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18463]
#### Describe the bug

When the `ps_brandlist` module is installed and the option "Display brands" is enabled, in the FO => Categories page => the title link for the Brands is not working.
It is working only when the "Display suppliers" option is enabled **and** "Display brands" is enabled.
PR related: https://github.com/PrestaShop/PrestaShop/pull/14665

#### Expected behavior

The title should be working independently from the supplier's option.

#### Steps to Reproduce

1. Install `ps_brandlist` module
2. Try to configure your smarty by disabling the cache set the option "Template compilation" to Force compilation and clear cache.
2. Go to BO => Shop Parameters => General page => Enable "Display brands" and disable "Display suppliers" option
3. Clear cache
3. Go to the FO => Categories page
4. Try to click on the **BRANDS** title => it is not working

If you the "Display suppliers" option => it will be OK.

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/78380435-24415780-75d4-11ea-9604-c4ae9877a780.png)
https://drive.google.com/file/d/1I6jL2RM6F8oLRgEslhXmi2UOVOmd99h8/view?usp=sharing
#### Additional information

* PrestaShop version: 1.7.7.x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_brandlist#8
