### ISSUE TITLE
Discount code is applied on products with specific price when cart rule reduction_exclude_special = 1

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#18474]
Discount code is applied to products with specific price when cart rule setting reduction_exclude_special = 1 and reduction_product = -2.

Steps to reproduce:
1. Add specific price to product;
2. Create cart rule, select products for cart rule one with specific price and one without;
3. Select that cart rule is only applied to selected products (reduction_product = -2) and exclude products with specific price (reduction_exclude_special = 1);
4. Go to FO, add products to cart, try to use discount code;
5. Discount should be applied to both products;

Bug found in classes/CartRule.php line 1208-1210.
Both in_array should be surrounded with brackets before &&

Before
`if (in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                            || in_array($product['id_product'] . '-0', $selected_products)
                            && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {`

After
`if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                            || in_array($product['id_product'] . '-0', $selected_products))
                            && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {`

**Comment by lukaslau** [comment]
I see this bug is fixed in src/Core/Cart/CartRuleCalculator.php

**Comment by khouloudbelguith** [comment]
Hi @zapper,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13704 to fix the issue.
Your ticket is a duplicate of #10300
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10300
