### ISSUE TITLE
Module upgrade files with spaces are interpreted

### ISSUE THREAD

**Issue by glegarand** [PrestaShop/PrestaShop#18489]
#### Describe the bug

When a module upgrade file contains a space, it is interpreted in the upgrade process.
Ex: upgrade-2.1.0 .php (space before .php) + upgrade-2.1.0.php
Both files are interpreted

#### Expected behavior

Files that don't match the upgrade file pattern strictly shouldn't be interpreted.

#### Steps to Reproduce

1. Increment the version number of your module
2. Create an according upgrade file in the module upgrade directory
3. Put some basic SQL ALTER TABLE query.
4. Copy the file and add a space before .php in the file name
5. Go to admin, locate module and upgrade it
6. See error
7. Click on the upgrade button again, green modal appears that upgrade is successful
8. Module version is updated. However, the table schema remains untouched

**Screenshots**

Files:
![image](https://user-images.githubusercontent.com/5107273/78651245-5ac2ef00-78c0-11ea-866e-42e9835134b2.png)

File content:
![image](https://user-images.githubusercontent.com/5107273/78651447-a37aa800-78c0-11ea-8595-1ad9671ab5c0.png)

Error on first update:
![image](https://user-images.githubusercontent.com/5107273/78651299-6f06ec00-78c0-11ea-8d14-27f08177c829.png)

Success on second update:
![image](https://user-images.githubusercontent.com/5107273/78651373-8ba32400-78c0-11ea-85f7-f341c82507d4.png)

Table schema after update:
![image](https://user-images.githubusercontent.com/5107273/78651702-fb191380-78c0-11ea-88a6-31a1ea5d163f.png)

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.3.x

**Comment by khouloudbelguith** [comment]
Hi @glegarand,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version, check, and feedback.

**Comment by glegarand** [comment]
The problem is not related to PHP 7.3. 
I guess that in the classes/module/Module.php class, in the loadUpgradeVersionList() method, it would be best to use the glob() function with an appropriate file mask instead of using scandir(). You would then make sure that only the files with the right names are processed, not the ones with wrong names.

**Comment by khouloudbelguith** [comment]
@glegarand, I tried with this module
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/4446001/mymodule.zip)
I tried to upgrade this module to 1.1.0
[mymodule_1.1.0.zip](https://github.com/PrestaShop/PrestaShop/files/4446007/mymodule_1.1.0.zip)
But I have this error
```
 Error!
Could not perform action update for module undefined
```

Thanks to check and feedback.

**Comment by florine2623** [comment]
Hi @glegarand ,
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
