### ISSUE TITLE
error 500 at the conclusion of the order

### ISSUE THREAD

**Issue by miraago** [PrestaShop/PrestaShop#18483]
**Error 500 when the customer confirms an order.**
The order notification email does not reach the customer or the seller
in the Back Office the order is reported.

subject to use prestashop version 1.7.3

the customer will see an error 500 at this address https://www.mysite.it/module/ps_wirepayment/validation

if I set the site in debug mode, this error will come out at the conclusion of the order

(1/1) UndefinedMethodException
Attempted to call an undefined method named "newCalculator" of class "Cart".
--
in PaymentModule.php line 1063
at PaymentModuleCore->createOrderCartRules(object(Order), object(Cart), array(object(Order)), 0, 0, '10')in PaymentModule.php line 490
at PaymentModuleCore->validateOrder(291, '10', 28.48, 'Bonifico bancario', null, array('{bankwire_owner}' => 'Holder name', '{bankwire_details}' => 'IBAN : Number Iban', '{bankwire_address}' => 'Bank Address''), 1, false, 'fcd11fd5710fb3d2dc7cb117e42bd170')in validation.php line 64
at Ps_WirepaymentValidationModuleFrontController->postProcess()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

![Cattura](https://user-images.githubusercontent.com/44875966/78583529-3f5fd180-7837-11ea-9ecc-5f20355f69ff.PNG)

**Comment by khouloudbelguith** [comment]
Hi @miraago,

Have you any [override](https://github.com/PrestaShop/PrestaShop/tree/develop/override/classes) of the Class `cart.php`?
This issue occurs only when using the ps_wirepayment module?
Have you any custom modules related to the checkout page?

Thanks!

**Comment by miraago** [comment]
Hi @khouloudbelguith 
Thanks for the reply.

_Have you any override of the Class cart.php? ---_ I have not made any changes, I think not !!!

_This issue occurs only when using the ps_wirepayment module?_ --- The error occurs with any payment form.

_Have you any custom modules related to the checkout page?_ ---   No, no custom forms.

**Comment by khouloudbelguith** [comment]
@miraago, What is the exact version of the `ps_wirepayment` module did you use?
Could you please provide me the file log into `Project_Folder/var/logs/`.

Thanks!

**Comment by miraago** [comment]
@khouloudbelguith thank

 _What is the exact version of the ps_wirepayment module did you use?_ --- v2.0.4 
Could you please provide me the file log into Project_Folder/var/logs/. 
[logs.zip](https://github.com/PrestaShop/PrestaShop/files/4442897/logs.zip) ---- see Attachment

**Comment by khouloudbelguith** [comment]
@miraago,

>This issue occurs only when using the ps_wirepayment module? --- The error occurs with any payment form.

So, this issue is not related to the `ps_wirepayment` module.
Could you please check again if you have any **override/file** in this path
`/Project_Folder/override/classes/` or into the path `/Project_Folderoverride/classes/checkout`

Thanks!

**Comment by miraago** [comment]
@khouloudbelguith thank
I don't know how to override it, attached the whole classes folder of the path /Project_Folder/override/

[classes.zip](https://github.com/PrestaShop/PrestaShop/files/4444181/classes.zip)

**Comment by khouloudbelguith** [comment]
@miraago, yes as expected, you have an override of the class `cart.php`.
[Cart.php.txt](https://github.com/PrestaShop/PrestaShop/files/4444511/Cart.php.txt)
This is the whole issue: you need to check this override is provided by which module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by miraago** [comment]
@khouloudbelguith thank

sorry,
if i disable all modules that are not prestashop should it work?

**Comment by khouloudbelguith** [comment]
@miraago,

Did you disabled those modules from the BO => Performance page 
![image](https://user-images.githubusercontent.com/16067358/57448844-4d395b00-7252-11e9-8540-45c85b383047.png)
If yes, this option doesn't work, here's a ticket: https://github.com/PrestaShop/PrestaShop/issues/9965

Thanks!

**Comment by miraago** [comment]
@khouloudbelguith 
Hello 
hi, sorry if I didn't answer.

no, in modules i have disabled all the modules that are not prestashop, but the error remains the same.

my site is not crowded because i am still adding products, but probably the problem was already there for some time !!!

**Comment by Cavilezg1989** [comment]
@miraago you can solve this issue? i have de same error but i can´t find the solution
