### ISSUE TITLE
BO - drop-down list filter doesn't work totally as expected

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18480]
#### Describe the bug

This behavior was observed on all drop-downs of migrated page filters

In the list filters when using the drop-down lists the selection of the empty item brings back to the last selection used

#### Expected behavior

The empty item in the drop-down list should bring up all the items in the list

#### Steps to Reproduce

1. Go to BO on a migrated page that contain a list with drop-down filter
2. On the drop-down list select one one the item and click on search
3. Only the required items are displayed on the list
4. Now on the drop-down select another item and click on search
5. The list is refreshed an the new required items are displayed
6. Now select the blank item in the drop-down list and click on search
7. The list should display all the items but not ( the list display the items from step 5 )

**Screenshots**

**The error in 1.7.7.x (also reproductible in 1.7.6.x) :** 
https://drive.google.com/file/d/1Fds2N2JuKehaQmoul6ep6cPRHffn-d_P/view

#### Additional information

* PrestaShop version: 1.7.7.x and 1.7.6.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I have the same issue with PS1.7.7.x for example `Orders` page
Same issue with PS1.7.6.4 for example `Categories` page
Same issue with PS1.7.5.2 for example `E-mail` page

In the legacy pages => OK.
So it is a regression in all migrated pages.

Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith and @SD1982, indeed it must be corrected on all migrated grids. I add it to the 1.7.8 kanban! Work is being done to add a modal on migrated grids, cf. #17847, let's fix this issue in the meantime. :-)

**Comment by colinegin** [comment]
ping @TristanLDD @prestascott has one of you had time to work on the dropdown design issue ?

**Comment by prestascott** [comment]
Hi, 

In my opinion, we should definitely fix this issue because it must display all the items when the blank value is selected in the dropdown select. 

However, this dropdown select can be improved by replacing the blank value with a short wording such as "All". It will be clearer for users instead of facing a blank value.

Here is my design proposition:
![All1](https://user-images.githubusercontent.com/54888056/83498837-b70b4f00-a4bc-11ea-9955-2031428ea979.png)
![All2](https://user-images.githubusercontent.com/54888056/83498846-bb376c80-a4bc-11ea-9777-bcddcd69c240.png)

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-product-team A question :) Is that change applies on all Yes/No Choices filters in BackOffice ?

@PrestaShop/prestashop-core-developers  If we remove the blank line, it implies that we change the status to required to true (Not a BC, but I have to modify all YesAndNoChoiceType). And add a new value ("All") in the YesAndNoChoiceType (#BCBreak). Are you agree with that ?

**Comment by colinegin** [comment]
@Progi1984 i'd say yes for better consistency but let's wait for @prestascott opinion.
Thanks !

**Comment by TristanLDD** [comment]
@Progi1984 Yes, that change will concern all yes/no filters in BO.

**Comment by Progi1984** [comment]
Blocked by #13448
