### ISSUE TITLE
Sitemap generator issue on image files

### ISSUE THREAD

**Issue by cryptolikely** [PrestaShop/PrestaShop#18484]
Hello! I found one small bug on last addon gsitemap. I'm trying to generate sitemap 30k products. On links .. everything works.. but when i check "Check this box if you wish to check the presence of the image files on the server" .. I got gateway error. I mention.. I have this settings on php:

asp_tags = Off
display_errors = On
max_execution_time = 10000
max_input_time = 300
max_input_vars = 10000
memory_limit = 2048M
post_max_size = 64M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php72"
upload_max_filesize = 128M
zlib.output_compression = Off
extension = php_mysql.dll
extension = php_gd2.dll
allow_url_fopen = On
allow_url_include = Off
enable_dl = Off
file_uploads = On
safe_mode = off
mod_security = off
JSON = ON
ctype = ON
mySQL = INNODB

I'm pretty sure.. is not a settings issue..  it's a module issue. Thank you and waiting for your reply.

**Comment by khouloudbelguith** [comment]
Hi @zsocialmedia,

Here's the PR: https://github.com/PrestaShop/gsitemap/pull/127 to fix the issue.
Your ticket is a duplicate of #16991
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #16991

**Comment by cryptolikely** [comment]
@khouloudbelguith  is not the same issue. it's different issue. Module was fixed in previous ticket. for links but not for images. 
Thank you

**Comment by khouloudbelguith** [comment]
@zsocialmedia, you just said that you have 30k products and you have the gateway error.
The other issue is reproduced when we have >25000 products fail with a gateway.
YOu can check this comment also: https://github.com/PrestaShop/PrestaShop/issues/16988#issuecomment-509004256

Thanks!
