### ISSUE TITLE
Theme installation error during silent installation

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/PrestaShop#18499]
#### Describe the bug

Silent installation fail when using the option --theme

#### Expected behavior

The installation succeed and the selected theme is activated

#### Steps to Reproduce
1 set-up a proper environment to install PrestaShop (mysql, apache,...)
2 unzip prestashop 1.7.6.4
3 unzip [classic-rocket](https://github.com/PrestaShop/classic-rocket/releases)  into themes/classic-rocket
4 launch the silent installation
php install/index_cli.php --language=en --country=fr --domain=test.localtest.me --db_server=localhost --db_user=presta  --db_password=presta --db_name=test --firstname=John --lastname=doe --email=test@test.com --password=azerty01 --newsletter=0 --theme=classic-rocket

Result:
The module is invalid and cannot be loaded.

#### Additional information
After a successful installation if you upload classic-rocket throught the web form it works.

But if you unzip it directy in the folder and then click on "use this theme" in the web interface it fails with this error message: "Cannot install module ps_searchbarjqauto. The module is invalid and cannot be loaded."

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

#### Bonus
Documentation is outdated:
http://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script

**Comment by khouloudbelguith** [comment]
Hi @toutantic,

I have the same issue with PS1.7.6.4 and PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/78686167-038a4200-78f3-11ea-960a-2c55f4954735.png)

It is related to this issue: https://github.com/PrestaShop/PrestaShop/issues/12727

Thanks!

**Comment by Progi1984** [comment]
Found the problem.

The classic-rocket theme needs a specific module : `ps_searchbarjqauto`. And the API doesn't find it on Addons.
