### ISSUE TITLE
BO-Exception when deleting discount in order view

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18498]
#### Describe the bug

An exception is displayed when adding 2 discount and deleting them and also if we go back to the order view the discount are deleted but one of them are still displayed

#### Expected behavior

no exception should be displayed when deleting a discount

#### Steps to Reproduce

1. Go to BO => orders => orders detail 
2. Add a discount (ex : 5% )
3. Add a second discount ( ex : 5 euros )
4. Delete the amount discount first
5. Delete the percent discount
(also reproducible if both discount are % discount but not if they are both amount discount )
6. And bonus : if we go back to the order view detail the discounts are deleted but the 5% discount is still applied

**Screenshots**
![capture d'écran_8](https://user-images.githubusercontent.com/40635814/78674186-85726f00-78e3-11ea-985b-8dd432a7f048.png)
![capture d'écran_9](https://user-images.githubusercontent.com/40635814/78674205-8b685000-78e3-11ea-8334-efa59e1d3312.png)

Edit by @Robin-Fischer-PS :

Please check if with there steps, the bug is also fixed : 
https://drive.google.com/file/d/1q7A2ASSAXirr_8R-Q-ixNppRQH2uwzfj/view

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by arouiadib** [comment]
Hello @SD1982 ,

Thank you for your explanation of the issue.

I think this is the same issue [mentioned here ](https://github.com/PrestaShop/PrestaShop/issues/11059)

regards

**Comment by colinegin** [comment]
Related to : https://github.com/PrestaShop/PrestaShop/issues/18379

**Comment by colinegin** [comment]
Should we close this issue @SD1982 as you no longer reproduce it ?

**Comment by SD1982** [comment]
Hi @colinegin maybe we can wait until #18532 is done and merged just to be sure

**Comment by Progi1984** [comment]
Fixed by #18532
