### ISSUE TITLE
Bug in place photos in Products

### ISSUE THREAD

**Issue by arie78** [PrestaShop/PrestaShop#18496]
#### Describe the bug

I have a problem with photos in the products category. When i make a new product, and put photos and safe it i cant see the photos in my webshop.

#### Expected behavior

When I place a photo, it is not visible in the webshop after publication. I tried some X to post a product but to no avail without photos

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @arie78,

Thanks for your report.
Could you please navigate to your BO => Design => Images Settings page => Click on "Regenerate thumbnails", check & feedback.

Thanks!

**Comment by arie78** [comment]
Geachte heer/mevrouw,

Hartelijk dank dat u contact met ons opneemt. Wij zullen uw e-mail zo spoedig mogelijk beantwoorden,

Met vriendelijke groet,

Arie Schaap
+31(0)686039317

EVAS-91 LTD
Tsar Simeon I" 72
8000 Burgas Bulgarije
+31(0)850026080

**Comment by khouloudbelguith** [comment]
@arie78, can I delete your last comment, I think, it is automatically replied?

Thanks!

**Comment by arie78** [comment]
Yes ofcoures


khouloudbelguith schreef op 2020-04-07 17:24:

**Comment by arie78** [comment]
Hi,

I did what you told me to do but there is no differents.

Kind regards,

Arie

khouloudbelguith schreef op 2020-04-07 17:22:

**Comment by khouloudbelguith** [comment]
@arie78, could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by arie78** [comment]
Where can I find this file? Sorry that i don't now where it is, i am 
just start with PrestaShop,

Kind regards,

Arie

khouloudbelguith schreef op 2020-04-07 18:05:

**Comment by khouloudbelguith** [comment]
@arie78, in your `/Project_Folder/`, it could be hidden.
You need to used ctrl+h to display it.

Thanks!

**Comment by arie78** [comment]
i can't find it

khouloudbelguith schreef op 2020-04-07 18:49:

**Comment by marionf** [comment]
Hello @arie78 

I can't reproduce your issue with PrestaShop 1.7.6.4, as you can see below, images are well displayed:

![capture d'écran_2509](https://user-images.githubusercontent.com/13449658/78788937-c2566880-79ac-11ea-8da8-73eb6d5dc984.png)

It seems that your issue is not a PrestaShop's core bug but most likely a configuration problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Comment by arie78** [comment]
your colleague yesterday indicated something, I ask where that folder is but you give me a completely different answer?
