### ISSUE TITLE
Broken link favicon generator

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#18494]
#### Describe the bug

Link to generate favicon is broken

#### Steps to Reproduce

1. Go to theme
2. Click on the link 
![Capture d’écran de 2020-04-07 13-48-19](https://user-images.githubusercontent.com/5064590/78665729-894bc480-78d6-11ea-847b-144b27ed81e3.png)

I can do a PR but I need to know if the generator exists on another url or if I replace with another url

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/blob/7633be8294d90148d2bdfe3fd1c2d403e72ec91b/src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/logo_configuration.html.twig#L147

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2
When I click on the link `favicon generator on PrestaShop Marketplace`
![image](https://user-images.githubusercontent.com/16067358/78666759-1ba09800-78d8-11ea-8c3b-92f657acb836.png)

=> redirection 
![image](https://user-images.githubusercontent.com/16067358/78666837-3ecb4780-78d8-11ea-87c4-57fb016ed1fa.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by ghost** [comment]
The url is https://addons.prestashop.com/create-favicon.php?pab=1

I need to know if the generator exists on another url or if I replace with another url or i just remove the url  before make a PR

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think, it is related to PrestaShop Core or it is related to addons issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Issue fixed.
https://drive.google.com/file/d/1r-lQ5DH8Bj8ckCgPU0BsSMlZahNkPfmv/view?usp=sharing
Thanks!

**Comment by ghost** [comment]
Nice job !

**Comment by ghost** [comment]
Arf j'avais un PR facile :)

**Comment by matks** [comment]
> Arf j'avais un PR facile :)

Une PR pour corriger addons.prestashop.com ? 😄j'ai loupé un truc ?

**Comment by ghost** [comment]
Je voulais virer le lien cassé ( joke )

**Comment by ghost** [comment]
Mais il est réparé du coup ...

**Comment by matks** [comment]
(j'ai viré mon message quand j'ai compris)

Next time ! 😄 

Si tu veux des PRs faciles il est possible d'améliorer le code en corrigeant/rajoutant la phpDoc comme dans https://github.com/PrestaShop/PrestaShop/pull/18259 ou https://github.com/PrestaShop/PrestaShop/pull/18185

**Comment by ghost** [comment]
J'en ai encore un pour addons :)  je vais créer une issue du coup 

Merci de ne pas renvoyer une iframe http 

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php#L49

![addon-2](https://user-images.githubusercontent.com/5064590/78679416-793de000-78ea-11ea-80f2-0015df8012b5.png)
