### ISSUE TITLE
No activa SSL en Prestashop 1.7.5.2.

### ISSUE THREAD

**Issue by vicenlegaspi** [PrestaShop/PrestaShop#18502]
Activo SSL  en Prestashop 1.7.5.2. y posteriormente guardo, pero sigue marcada la opción No.

No permite activarlo.

**Comment by khouloudbelguith** [comment]
Hi @vicenlegaspi,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
