### ISSUE TITLE
Remove call to profile.prestashop.com

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#18503]
#### Describe the bug

I can't access the community forum of Prestashop, I get this message error 

> Banned You do not have permission to view this site.

#### Steps to Reproduce

Access to multiple back-office websites at the same time, 
I should be log in one single website and log out from other websites then restart my router to get a new IP Adress so I can access the forum.

**Screenshots**
![image](https://user-images.githubusercontent.com/11594433/78682446-e56a1500-78e5-11ea-8c4b-c1826c1bf460.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* Version de PHP : 7.2.29

Regards,

**Comment by ghost** [comment]
I think it's the avatar api .... i remove this call  because if prestashop is down your back office is very slow ....

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

You can't access to this link: https://www.prestashop.com/forums/?

Is it?

Thanks!

**Comment by matks** [comment]
> I think it's the avatar api .... i remove this call because if prestashop is down your back office is very slow ....

We are working on both removing the call and allowing people to fetch it in smarter ways 😊 https://github.com/PrestaShop/PrestaShop/pull/18346

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

Yes I'm banned only when I access to back-office with my Gmail which is linked to Prestashop forum

once I log in two websites with this mail (gmail) I get banned, 

Regards

**Comment by marionf** [comment]
@go-sudo 

So, if I understand well, when you are banned from the forum, the API can no longer retrieve your avatar and it causes the BO to crash ?

> We are working on both removing the call and allowing people to fetch it in smarter ways blush #18346

@matks So a fix is already on the way ?

**Comment by matks** [comment]
> @matks So a fix is already on the way ?

Yes, when PR https://github.com/PrestaShop/PrestaShop/pull/18346 is merged there will not more calls to profile.prestashop.com and no more issues 😄 

@go-sudo to fix immediately your BO you can remove the bad call in https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Employee.php#L585
```
public function getImage()
    {
        return Tools::getAdminImageUrl('prestashop-avatar.png');
    }
```
This wil grant you access to your BO. However it modifies a Core file, be careful to restore it before next upgrade.

EDIT: see PR https://github.com/PrestaShop/PrestaShop/pull/18622 where I do the same

**Comment by go-sudo** [comment]
Hello @matks 

I can not access to the forum anymore, I'm using PS 1.7.8.6

I removed this 

```
public function getImage()
    {
        $defaultSystem = Tools::getAdminImageUrl('pr/default.jpg');
        $imageUrl = null;

        // Default from Profile
        $profile = new Profile($this->id_profile);
        $defaultProfile = (int) $profile->id === (int) $this->id_profile ? $profile->getProfileImage() : null;
        $imageUrl = $imageUrl ?? $defaultProfile;

        // Gravatar
        if ($this->has_enabled_gravatar) {
            $imageUrl = $imageUrl ?? 'https://www.gravatar.com/avatar/' . md5(strtolower(trim($this->email))) . '?d=' . urlencode($defaultSystem);
        }

        // Local Image
        $imagePath = $this->image_dir . $this->id . '.jpg';
        if (file_exists($imagePath)) {
            $imageUrl = $imageUrl ?? Context::getContext()->link->getMediaLink(
                str_replace($this->image_dir, _THEME_EMPLOYEE_DIR_, $imagePath)
            );
        }

        // Default from System
        $imageUrl = $imageUrl ?? $defaultSystem;

        // Hooks
        Hook::exec(
            'actionOverrideEmployeeImage',
            [
                'employee' => $this,
                'imageUrl' => &$imageUrl,
            ]
        );

        return $imageUrl;
    }
```

butt the back office shows this error

![image](https://user-images.githubusercontent.com/11594433/175664073-f510ad2c-1118-4009-aee9-365cf64ee79f.png)

Regards
