### ISSUE TITLE
[IMPROVEMENT] Implement payment restrictions by product basis

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18507]
#### Is your feature request related to a problem?

For example. There are certain products, that merchants wants to be paid in advance. Expensive stuff, stuff made on request, stuff customized on request etc.

There is no possibility to limit payment options now.

#### Describe the solution you'd like

Add payment restrictions to product in the same fashion, as there are shipping restrictions.
If they are empty, or all checked, all payment options are available. 
If there are only some options checked, show only these payment methods.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @Hlavtox, thanks for this idea! You would like to apply payment methods restrictions per product (following the shipping options example below), right? If yes, what would be the connection with advanced payment?

![Capture d’écran 2020-04-16 à 11 32 20](https://user-images.githubusercontent.com/32565890/79440407-3f4d9780-7fd6-11ea-8109-a838f3366c80.png)

**Comment by Hlavtox** [comment]
@LouiseBonnard Exactly. I think it would be a solution good for general public. Hm? :-)

**The connection to advanced payment**

Usually, in 99% of ecommerce stores in central europe, you have these payment methods:
- Bank wire
- Card payment/Paypal etc.
- Cash on delivery
- Payment during personal pickup
Let's say that cash on delivery is used in like 50% of orders.

But, as a merchant, you sometimes sell some goods that are either: very very expensive, made on order or customized on order. 

Now, some people are assholes. They order something, then they don't want it and they are too lazy to cancel the order. Then, they will not pick up the package and not pay it. (You can sue them for the shipping if you want.)

And you as a merchant are left with a product that you will sell in 3 years maybe and you have money in it. That's why many merchants want to force advance payment for some products.

**My proposed solution would allow to tick only the payment methods you want.**

**Comment by LouiseBonnard** [comment]
@Hlavtox, it's a great feature indeed, aha! Apply payment restrictions per product is a nice idea, yet it implies orders to support multiple payments (with multiple payment methods) and this is not the case currently.

**Comment by Hlavtox** [comment]
@LouiseBonnard Why do you want to implement multiple payments for one order?

For example, in carrier situation:
If you have two carriers and two products.
And you limit one product to one carrier and the second product to second carrier.
You go to cart and see "no carriers available"

I would do it the same in the payment situation. It would be the merchant's responsibility, that there is always at least one payment method, hm? :-)
