### ISSUE TITLE
[IMPROVEMENT] Add warranty information to products

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18506]
#### Background
It would be very useful to have warranty information listed on product page. 

Some products have only the warranty given by the law - 2 years.
Some products have extended warranty from the manufacturer, or lifetime warranties.

I implemented this internally and I think it would be good for other merchants.

#### My proposal - BO

- There would be an editable field "**Warranty**" available in product settings.
- There would be an optional editable field "**Warranty details**" available in product settings. This field would contain more information about the warranty. Like "There is a lifetime warranty for this product. You need to register on manufacturers website after purchase to get it."
- There would be a possibility to set default value in Prestashop settings, as there is for example for "In Stock" texts. This value would show up, if there would be no warranty specified in product settings.

#### My proposal - FO

There would be for example a "Warranty: 5 years" displayed next to product references. With a "more information" link, that would display a modal with **Warranty details**.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
PS: in the FO, we can use the hook `displayProductExtraContent` as explained here: https://github.com/PrestaShop/PrestaShop/pull/6216

Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith There could definitely be a module for this. 

That's another question for guys in charge of the business model. I don't know how far Prestashop's team want to go in implementing new features and limiting paid addons space. :-)

**Comment by LouiseBonnard** [comment]
Exactly, this is a feature covered by several modules (some of them using this `displayProductExtraContent` hook mentioned in PR #6216) so, at this point, it does not need to be native. Also, this piece of information could be displayed in the _Summary_ or _Description_ fields. I close this issue for now, thanks for this improvement idea, @Hlavtox!
