### ISSUE TITLE
FO - `ps_supplierlist` module - The link of supliers list is incorrect when id_supplier > 1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18528]
#### Describe the bug

When the `ps_supplierlist` module is installed and the option `Display suppliers` is enabled, in the FO => Categories page => the link of suppliers list is incorrect for id_supplier >1

#### Steps to Reproduce

1. Install the `ps_supplierlist` module
2. Try to configure your smarty by disabling the cache set the option "Template compilation" to Force compilation and clear cache.
3. Go to BO => Shop Parameters => General page => Enable "Display suppliers" option
4. Go to BO => Catalog => Suppliers page => Create more than two suppliers
4. Go to BO => Catalog => Products page => assign the suppliers created to some products
6. Clear cache
7. Go to the FO => Categories page (`shop.com/2-home`)
8. Try to click on the suppliers => always redirection to the first supplier

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/78792006-dd2adc00-79b0-11ea-991f-3994ca3d7a89.png)

#### Additional information

* PrestaShop version: 1.7.5.2, 1.7.6.4, 1.7.7.x
* PHP version: 7.2
* Module version: 1.0.3

**Comment by Progi1984** [comment]
Fixed by @okom3pom in PrestaShop/ps_supplierlist#7
