### ISSUE TITLE
Empty state order list page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18526]
**SPEC**

Add an empty state on the order list page

**WHY**
Empty states are a way to improve the user experience of your product, from onboarding to encouraging users to interact with PrestaShop.

**DESIGN**
https://invis.io/5FRLCBENAS4#/419281734_Order

**Comment by Progi1984** [comment]
We are waiting for the design.

**Comment by colinegin** [comment]
I just came accross this issue. Is it really necessary ? I guess in 99% cases, there won't be empty order listings, because merchant cannot remove orders.
Wdyt @MatShir ?

**Comment by colinegin** [comment]
ping @TristanLDD, what's the status of the empty state ?

**Comment by MatShir** [comment]
The design is done, we are waiting for the wording to have the final result. @Junebyun @LouiseBonnard 😉

**Comment by colinegin** [comment]
Can you share the design in the issue description please ?

**Comment by MatShir** [comment]
@TristanLDD I will let you edit the description with the Invision link with the final result :)

**Comment by Junebyun** [comment]
@MatShir @TristanLDD here's the empty state for the order list page 😃 

**Manage your orders**
_Find all your orders on this page and access their main information in one click: check the cart total, the payment method, the shipping details, or if it comes from a new client. You can even update the status from the listing!_

**Comment by Progi1984** [comment]
Fixed by #19597
