### ISSUE TITLE
Bad display of customizable product on create order page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18527]
**Current behaviour**

![create order customizable](https://user-images.githubusercontent.com/43613217/78791592-62fa5780-79b0-11ea-914b-99493c3176c1.png)

**Expected behaviour**

The label "Type here" for the customization to be aligned with "Customization" and without the scroll bar.

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by Progi1984** [comment]
Fixed by #18566
