### ISSUE TITLE
How to get the shipping cost and tax

### ISSUE THREAD

**Issue by augustinejenin** [PrestaShop/PrestaShop#18522]
In my prestashop site (1.6.1.5),

I have updated 
1.handling cost 25 euro
2. shipping cost 3 euro
3. tax 21%

I need to show these in add to cart popup page.
I use this below code to get the handling cost - Configuration::get('PS_SHIPPING_HANDLING')
How can i get the other information in prestashop?
![tax_rate](https://user-images.githubusercontent.com/26268454/78781451-e53d4880-79bd-11ea-86ed-dcccbdf78c4d.png)
![managemnt_cost](https://user-images.githubusercontent.com/26268454/78781469-ee2e1a00-79bd-11ea-8d59-4238bc0248a4.png)
![shipping_cost](https://user-images.githubusercontent.com/26268454/78781481-f2f2ce00-79bd-11ea-8c28-0de639105383.png)

Please help me how can show this values in my cart popup?
@Prestaworks

**Comment by marionf** [comment]
Hello,

As you can see [here](http://build.prestashop.com/news/1.6.1.x-what-s-next/) : we don't maintain 1.6 version anymore.
The maintenance of PrestaShop 1.6 is now being performed exclusively by volunteers to fix critical issues.
Furthermore, we don't provide support on Github. You can ask your question on [the forum](https://www.prestashop.com/forums/)

Regards
