### ISSUE TITLE
Die() in Customer class

### ISSUE THREAD

**Issue by menno-comm-on** [PrestaShop/PrestaShop#18521]
#### Describe the bug

Why oh why do you die()?
In classes/Customer.php, method getByEmail, line 445, you check if the email address is valid, and if not  you kill the script.

#### Expected behavior

Throw an exception, return false, log a fatal error, whatever. Just don't kill the script. The current way can cause some nasty and hard to find issues, and it simply doesn't look good to clients.

#### Steps to Reproduce

---

**Screenshots**

---

#### Additional information

* PrestaShop version: 1.7.6.3 to current
* PHP version: N/A

**Comment by matks** [comment]
> Why oh why do you die()?

The code is 8 years old so unfortunately the developer who wrote it is gone for a long time 😢but you're right, there's no need to die here

**Comment by marionf** [comment]
@matks Is there something to do here ? Refacto ?

**Comment by matks** [comment]
> @matks Is there something to do here ? Refacto ?

It's "just" bad code to fix 😢. The task itself is easy, what's hard is to find all places where this code is used to make sure they behave correctly with the fixed version.

For this particular issue, it'll easy I can do the PR in 1 minute. But the global topic is to remove irrelevant usages of php `die()` function in all PrestaShop

**Comment by matks** [comment]
@menno-comm-on See https://github.com/PrestaShop/PrestaShop/pull/18531

**Comment by matks** [comment]
@menno-comm-on fixed on `develop` branch 😉thanks for the reporting
