### ISSUE TITLE
Add select Protocol HTTP/HTTPS in process install

### ISSUE THREAD

**Issue by vBlackOut** [PrestaShop/PrestaShop#18525]
Hello,

Please add selectbox option to select http or https protocol on install change on database 

**PS_SSL_ENABLED** = 1 or 0 if select option aditionnal options
**PS_SSL_ENABLED_EVERYWHERE** = 1 or 0 if select option aditionnal options

thank you for you approve on change this.

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers WDYT of this improvement ?

**Comment by Progi1984** [comment]
@marionf Actually, we have an option in CLI :

![image](https://user-images.githubusercontent.com/1533248/84771839-56126980-afda-11ea-9bf7-30c7103d9da6.png)

So an option in Process Install is logical.

**Comment by Progi1984** [comment]
@marionf And the PR is here #19791. The PR may fix #10482
