### ISSUE TITLE
Boolean given in CacheMemcached.php on line 82, referer: https://www.google.com/

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#18523]
Hello

I noticed this error log on apache log so I disabled the Memcached open on the backend and I stopped the Memcached server, 
mod_fcgid: stderr: PHP Warning: in_array() expects parameter 2 to be array, boolean given in  /httpdocs/classes/cache/CacheMemcached.php on line 82, referer: 
#### Describe the bug
I can't access anymore to the website with the current session, I must restart the browser or launch Firefox

--
![image](https://user-images.githubusercontent.com/11594433/78781279-db085380-7997-11ea-8e0e-4949f9fc581d.png)

#### Additional information

* PrestaShop version:  7.2.29 
* PHP version: 1.7.6.3 

Regards

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers Could you try to reproduce it ? Thanks

**Comment by go-sudo** [comment]
Hi @marionf 

maybe this screen will help 

![image](https://user-images.githubusercontent.com/11594433/78871217-4822f400-7a3f-11ea-8991-1a91f1878dd3.png)

Regards and I'm ready to provide any additional information 

Regards

**Comment by go-sudo** [comment]
Hello

any news please I still get this error when Memcached is enabled on the server

Regards

**Comment by marionf** [comment]
Hello @matthieu-rolland as you are the one for the issues today, could you try to reproduce this one ?

**Comment by CristianDeluxe** [comment]
<img width="1440" alt="Captura de pantalla 2020-05-13 a las 1 15 29" src="https://user-images.githubusercontent.com/156531/81754789-4ec9de80-94b7-11ea-8fe8-28fe13227158.png">
Same here with PrestaShop v1.7.6.5 Stable

Edit:
-----
The memcached service was stopped, when it was started the error disappeared, in case you can try to replicate the error.

**Comment by Progi1984** [comment]
I may have a clue.
It seems that getVersion can return false if there are no servers.

Extension : https://pecl.php.net/package/memcached
Repository : https://github.com/php-memcached-dev/php-memcached
Source : https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c#L2816
Test : https://github.com/php-memcached-dev/php-memcached/blob/master/tests/experimental/getversion.phpt

**Comment by Progi1984** [comment]
I reproduce the error.

1. Install Memcached extension (On ubuntu, `sudo apt-get install php7.2-memcached`)
2. In database, add a memcached server (`INSERT INTO ps_memcached_servers ( ip, port, weight)
VALUES('127.0.0.1', 12345, 1);`) while I don't have one.
3. Go to Configure > Advanced Parameters > Performances

@CristianDeluxe It reproduce your bug.
@go-sudo : Your memcached server is available or not ?

**Comment by Progi1984** [comment]
The problem seems exist since version 1.7.0.x in accordance with the code and since [its implementation](https://github.com/PrestaShop/PrestaShop-1.6/blob/1.6.1.0/classes/cache/CacheMemcached.php) in 1.6.1.0
