### ISSUE TITLE
Duplicating a product duplicates the SEO content 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18529]
#### Is your feature request related to a problem?

When a duplicate a product, it duplicates as well the meta-title, the meta-description and the friendly URL in the SEO tab. So it creates duplicated content which is bad for the SEO if the merchant does not notice it.

#### Describe the solution you'd like

The solution still needs to be discussed but here are the following ideas:
- Add in BO a warning/tip message to explain that different meta's are needed for each product.
- Add warning on the duplication actions to be careful with the SEO product content.
- Empty the SEO fields on the duplication

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

Could you please specify the issue status :sweat_smile: 
Ping @PrestaShop/product-team :wink: 

Thanks!

**Comment by Hlavtox** [comment]
@MatShir I think this is a non-existent problem. Will we warn the merchant that by duplicating a product, he is creating a duplicate content with the same name, description and information - even more important than meta tags? :-)

**Comment by MatShir** [comment]
simplifed URL is not really update, not like balise title and meta description. I found the behavior a little bit tricky
