### ISSUE TITLE
FO - checkout - The Shipping cost is incorrect in the cart detail when using a cart rule "Free shipping"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18533]
#### Describe the bug
When there is a free shipping voucher, in the checkout page => cart details, the shipping line is incorrect, the shipping cost is displayed instead of FREE.

#### Expected behavior

What should be done is to display FREE on the shipping line instead of the initial pricen when there is a free shipping voucher

#### Steps to Reproduce

Steps to reproduce the **fixed** issue in the branch 177x
In the **BO**:
1. Add cart rule free shipping from € 35,-
2. Add cart rule free gift to the value of € 3,95,- with every order
3. Add cart rule free gift to the value of € 17,95,- for orders from € 75, -
4. All carriers should **not be free**

In the **FO**:
1. Add a product to the shopping cart with a value of less than 35 euros to see the shipping costs.
2. Add a product to the shopping cart with a value over 35 euros to see the free shipping label.

at this step, in the cart details, the shipping cost is always displayed with 177x branch, in the PS1.7.6.4, it is free

**Screenshots**
**177x branch**
![image](https://user-images.githubusercontent.com/16067358/78660439-5b15b700-78cd-11ea-80d0-069a08366a8c.png)

**1764**
![image](https://user-images.githubusercontent.com/16067358/78660425-55b86c80-78cd-11ea-93b1-e234f8c0f583.png)

#### Additional information

* PrestaShop version:  1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18884
