### ISSUE TITLE
web migration from one domain to another

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18535]
#### Describe the bug
I copy all the files and the database, I modify the parameters ps_shor_url and ps_configuration and when I try to enter the backoffice in the new domain it shows a screen with HTTP ERROR 500
Does anyone know what i should do?

#### Expected behavior

///

#### Steps to Reproduce

////
**Screenshots**

///

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.29

**Comment by Hlavtox** [comment]
@alfonsolr09 Did you change database credentials in app/config/parameters.php?

If it still doesnt work, put php file thats inside the zip to your prestashop root and run it. It will clear the cache.
[flushCache.zip](https://github.com/PrestaShop/PrestaShop/files/4453540/flushCache.zip)

**Comment by alfonsolr09** [comment]
I change it on paramethers.php yes.
Im going to try your zip

**Comment by alfonsolr09** [comment]
@Hlavtox where i have to put it? I have my shop on a subdomain. Like myshop.com/presta17

**Comment by Hlavtox** [comment]
@alfonsolr09 Put flushCache.php to presta17 folder. Then run myshop.com/presta17/flushCache.php, then BO should work.

**Comment by florine2623** [comment]
Hi @alfonsolr09 and @Hlavtox ,

Thanks for replying @Hlavtox 
@alfonsolr09 you can also clear cache manually via FTP

Please let me know if you manage to migrate your shop properly.
Thanks

**Comment by alfonsolr09** [comment]
It worked perfectly.
I have another problem, currently I have a presta 1.5, I want to upload presta 1.7  to that same domain. The version of php I have is 5.6.34, do I need to update to upload loans 1.7?
Which version should i upgrade to?

**Comment by florine2623** [comment]
Perfect !
What do you mean by "loan" ? the web host ?
Here's the compatibility chart of PrestaShop version : 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks !

**Comment by alfonsolr09** [comment]
presta

**Comment by florine2623** [comment]
When you update from PS1.5 to PS1.7, you will need to upgrade version of PHP of course

**Comment by alfonsolr09** [comment]
Yes, but can i have the two prestashops versions in the same server?
@florine2623
