### ISSUE TITLE
Product sold understock on v1.7.6.3

### ISSUE THREAD

**Issue by fabio-zetaweb** [PrestaShop/PrestaShop#18538]
Hello,

It's happened to me several times to receive orders with products sold under stock despite those products, in quantity settings, had the rule "Use default behavior (Reject orders)".

![understock](https://user-images.githubusercontent.com/56585945/78871210-a6ec6b80-7a47-11ea-9b25-1cfa99753634.jpg)

Have such cases happened before?

**Comment by florine2623** [comment]
Hi @fabio-zetaweb ,

What version of PrestaShop are you using ?
Please check if a module manages the stock of your shop.

Please check and let me know!

**Comment by fabio-zetaweb** [comment]
Hi,

1.7.6.3 and no module that manages stock.

**Comment by florine2623** [comment]
Hi @fabio-zetaweb ,
I could not manage to reproduce your error on neither PS 1.7.6.4 nor 1.7.6.3, please see screenshot below : 
![Capture d’écran 2020-04-10 à 17 47 25](https://user-images.githubusercontent.com/16019289/79003780-8e697780-7b53-11ea-99a4-a84f679e4f1f.png)
![Capture d’écran 2020-04-10 à 17 47 55](https://user-images.githubusercontent.com/16019289/79003786-91fcfe80-7b53-11ea-8d9f-29c76fb1435a.png)

Is it possible that multiple customer were on the same product and bought it a the same time ?
Thanks

**Comment by fabio-zetaweb** [comment]
Hi,
even I couldn't reproduce the error by myself but for sure the error exists.

Yes, it's been that the case. In fact the same product has been purchased at the same time (within a few tenths of a second). But as you can see from the image of the previous order, the stock for that product was already -1.

![ordine-2](https://user-images.githubusercontent.com/56585945/79200216-640b0900-7e36-11ea-9c58-6ae404f6f4ab.jpg)

**Comment by florine2623** [comment]
Hi @fabio-zetaweb ,
As I can't reproduce the issue, I suggest you to use a module.
You could use a module like that one that will "book" the product for one cart. So you won't face any negative stocks or out-of-stock issues : https://addons.prestashop.com/en/stock-supplier-management/21707-temporary-product-reservation-lonely-stock.html
Thanks !

**Comment by davideapvd** [comment]
Hello, I can give an hint to why this is happening, if you proceed with the checkout and are at the payment step, and set the product quantity to zero, prestashop lets you proceed with the payment and the quantity goes to -1.
If for example you are at the shipping or any previous step, an error is raised and you are redirected to the cart page with an error message.

can this issue be reopened?

this has been tested with 1.7.8.5
