### ISSUE TITLE
Dashboard perpetually loading

### ISSUE THREAD

**Issue by SportshubPH** [PrestaShop/PrestaShop#18534]
#### Additional information

* PrestaShop version: 1.6.1
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @SportshubPH ,
Please check you PHP compatibility first

You can try a few things : 
- Inspect the page to see if there are errors
- Activate debug mode
- Clear cache
- Check if a module is blocking the loading process

Thanks!

**Comment by florine2623** [comment]
Hi @SportshubPH ,
I have an update : 
PrestaShop 1.6 [isn't maintained anymore](http://build.prestashop.com/news/1.6.1.x-what-s-next/). The maintenance for this version is now being performed exclusively by volunteers to fix critical issues.
You can open an issue on the [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues). Please keep in mind that only critical issues will be acknowledged.
