### ISSUE TITLE
ps_imageslider - url should be optional

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#18536]
#### Describe the bug

In every ps_imageslider's slider, the url is mandatory. 
A slider can be used to show a store front or have just a visual. The link shouldn't be mandatory.

Note : the # trick doesn't work here.

**Comment by florine2623** [comment]
Hi @jf-viguier 
Thanks for the recommandation, I will let our product team know.
Thanks !

**Comment by florine2623** [comment]
Hello @PrestaShop/prestashop-product-team !

What do you think about @jf-viguier 's request on ps_imageslider module ?
Thanks !

**Comment by gabrielobleite** [comment]
I'd like to take this issue, but I was trying first to run the project here unsuccessfuly. What steps I must follow to run the program on localmachine?

**Comment by gabrielobleite** [comment]
Hello! Can I take this issue to resolve?

**Comment by LouiseBonnard** [comment]
@gabrielobleite, sure, you're welcome! [Here](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests) is a link to help you create the pull request. ;-)

**Comment by gabrielobleite** [comment]
Hello, I have a question.

I found where, in the generate module, I have to change to remove Required info from URL. But I did not found where to change it, I noticed that the code in generated in some way, but I did not found where.

Have some clue where I can found that?

Thanks in advance and hope is all good with you during this pandemic situation.

**Comment by LouiseBonnard** [comment]
Dear @gabrielobleite, thank you very much, I hope all is good for you as well!

It might be the `true` value on line 758 in the module file ([here](https://github.com/PrestaShop/ps_imageslider/blob/master/ps_imageslider.php)), I guess you need to turn it into `false`. @PrestaShop/prestashop-core-developers, can you confirm? are there other files to check?

**Comment by eternoendless** [comment]
@LouiseBonnard not enough. The url is validated per language [here](https://github.com/PrestaShop/ps_imageslider/blob/master/ps_imageslider.php#L327-L335) and [here](https://github.com/PrestaShop/ps_imageslider/blob/master/ps_imageslider.php#L346-L348)

The `url` value is also required at the ObjectModel entity level as well [here](https://github.com/PrestaShop/ps_imageslider/blob/master/Ps_HomeSlide.php#L53). There may be other places impacted by that as well.

**Comment by gabrielobleite** [comment]
Thanks @LouiseBonnard and @eternoendless . I will check all the links and verify how to proceed with the changes.

**Comment by gabrielobleite** [comment]
Pull Request created. I did change the URL required property, but did not changed the others URL restrictions such as Size or Format.

**Comment by Progi1984** [comment]
PR : https://github.com/PrestaShop/ps_imageslider/pull/49
