### ISSUE TITLE
Cannot save private note in order detail pages, got undefined error

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18542]
Cannot save private note in order detail pages, got undefined error and the note will not be saved.

Doing the same thing in customer information page, it works, so i think is a problem related to the buttom in order page the is not the same of customer details page.

<img width="699" alt="Schermata 2020-04-09 alle 11 47 24" src="https://user-images.githubusercontent.com/5024055/78882272-241fdc80-7a58-11ea-87ed-942b94885c0b.png">

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Betafer ,
Are you using any module related to the products ?
Can you try to put debug mode on ?
Can't you add an internal note on all orders ?

Please check and let me know!

**Comment by Betafer** [comment]
Hi florine

Are you using any module related to the products ?
No
Can you try to put debug mode on ?
Yes, i got this notice
<img width="616" alt="Schermata 2020-04-09 alle 12 47 52" src="https://user-images.githubusercontent.com/5024055/78887622-7d8c0980-7a60-11ea-8a3d-9d8085827728.png">

Can't you add an internal note on all orders ?

Yes

**Comment by florine2623** [comment]
Hi,
Clear all caches from BO and FO and let me know.
Thanks !

**Comment by Betafer** [comment]
Done, nothing change

**Comment by florine2623** [comment]
When you inspect the page, is there an error showing ?

**Comment by Betafer** [comment]
No, only that notice in debug mode.

**Comment by florine2623** [comment]
I could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
You can contact the support team so they can look into your shop : https://addons.prestashop.com/en/support/16298-prestashop-support-plan.html
Thanks !

**Comment by Betafer** [comment]
Fixed, the problem was caused by a tpl file from prestashop version 1.5
