### ISSUE TITLE
BO - Emails page - The SMTP configuration card is not opened when selecting the option "Set my own SMTP parameters (for advanced users ONLY)"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18549]
#### Describe the bug

In the BO > Advanced Parameters => Emails page - The SMTP configuration card is not opened when selecting the option "Set my own SMTP parameters (for advanced users ONLY)".
We should click save => so the page is refreshed.
It is not the same behavior as the 177x branch and PS1.7.6.4.
![image](https://user-images.githubusercontent.com/16067358/78907018-6826d780-7a80-11ea-8384-e21607b46561.png)

#### Expected behavior

The SMTP configuration card should be opened when selecting the option "Set my own SMTP parameters (for advanced users ONLY)".

#### Steps to Reproduce

1. Go to BO > Advanced Parameters => Emails page
2. Select the option "Set my own SMTP parameters (for advanced users ONLY)".
3. See error => The SMTP configuration card is not opened 

**Screenshots**

develop => NOK => https://drive.google.com/file/d/1RrRIUB05XTkA2OYGoxKhbQCdaZwVkIAx/view?usp=sharing
177x => OK: https://drive.google.com/file/d/1OUTuDkTYWowzbU5vBkHdWiWxd7yU4zFD/view?usp=sharing

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by Macrisu** [comment]
Well, it seems is not the only problem.
SMTP email sending is not working in 1.7.6.4 at all, atleast with gmail (less secure option enabled on gmail and app passwords)

PHP 7.3

**Comment by khouloudbelguith** [comment]
Hi @Macrisu,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by Macrisu** [comment]
I tried to install with php 7.4 and I had errors
For me, it's also working with 7.3, except few minor details... apparently!

Clearly I did not pay attention to the compatibility chart...
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart
Downgrading now!

**Comment by Macrisu** [comment]
Downgraded to PHP 7.2
All working, except SMTP - gmail

**Comment by khouloudbelguith** [comment]
@Macrisu, your issue is different, can you open a new issue with more information about your configuration.

Thanks!
