### ISSUE TITLE
PrestaShop must be compatible with PHP 8.0

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#18547]
PHP 8.0 is out and PrestaShop must be compatible

**Related issues:**
- [x] https://github.com/PrestaShop/PrestaShop/issues/17300
- [x] https://github.com/PrestaShop/PrestaShop/issues/20739
- [x] https://github.com/PrestaShop/PrestaShop/issues/17351
- [x] #25921
- [x] #25922

**Comment by Gipielle** [comment]
:-) mvorisek you are a dreamer !

**Comment by eternoendless** [comment]
I think it will be harder than with PHP 7.4 though, since it's a major version they may remove deprecated code and introduce a lot of breaking changes.

But of course we'll keep a close eye as they release more information about what it will change.

**Comment by kpodemski** [comment]
PHP 8...... .......PrestasHoP 8

**Comment by davidglezz** [comment]
PHP 8.0.0 Alpha 1 available for testing!
https://www.php.net/index.php#id2020-06-25-1

**Comment by lil5** [comment]
Any update on the matter?

PHP 8.0.0 has been released 

https://www.php.net/archive/2020.php#2020-11-26-3

**Comment by matks** [comment]
Hi, our current php compatibility roadmap is

| PHP version     | will be compatible with | status
| ------------- | ---------------------------------|--------------------
| php7.3 | PrestaShop 1.7.7.0 | done ✅ 
| php7.4 | PrestaShop 1.7.8.0 | done ✅ 
| php8.0 | PrestaShop 1.7.9.0 | to do

**Comment by mariochacondev** [comment]
Hi guys, any chance of this happening anytime soon?

**Comment by matks** [comment]
@mariochacondev Not soon, no.

PrestaShop 1.7.8 will bring php7.4 compatibility and be delivered in summer 2021. PrestaShop 1.7.9 will bring php8.0 compatibility and be delivered somewhere around end of 2021 or beginning of 2022.

Sorry about that, but PrestaShop is a big software, we try to maintain a range of compatibility* and php8 is a very big jump (see https://24daysindecember.net/2020/12/21/a-perfect-storm/ for example).

*It's easy to be compatible with php8 only. It's harder to become compatible with php8 _and_ keep old php7 versions running 😄

**Comment by mariochacondev** [comment]
Alright, I can understand. I just want to be prepared for a project that is due very soon. Thanks for the info

Cheers Mario

**Comment by mvorisek** [comment]
related issues:
- upgrade Symfony & Twig: https://github.com/PrestaShop/PrestaShop/issues/17300
- upgrade Guzzle: https://github.com/PrestaShop/PrestaShop/issues/17351

**Comment by eternoendless** [comment]
What is particularly tricky is that support for PHP 8 requires updating several dependencies, which means a significant number of breaking changes.

**Comment by mvorisek** [comment]
@eternoendless That is correct. But used Symfony receives only security fixes, used Guzzle is already EOL and does not even receive security fixes... Is there any reason to not update these deps in 1.7.8.0? It will need to be done someday and Symfony 4.4 as well as the latest Guzzle support the minimal PHP 7.1.

**Comment by rblaurin** [comment]
@mvorisek, I think the keywords are: Semver, Guzzle and Modules.
But you are right, it will need to be done someday, and I would greatly appreciate if we had at least a new class to wrap Guzzle in 1.7.8.

**Comment by eternoendless** [comment]
1.7.9 will be a semi-major in that respect, because we will update a lot of dependencies – including Guzzle and Symfony.

**Comment by mvorisek** [comment]
@eternoendless my question what is the objective to not do so in 1.7.8?

**Comment by eternoendless** [comment]
@mvorisek Because it's a lot work, and that would delay 1.7.8 by several months. Furthermore, php 7.4 compatibility has already been added to 1.7.8, so we really don't want to delay it any longer than necessary. 1.7.8 is due to be frozen on April and released before the summer, and 1.7.9 by end of year (hopefully).

**Comment by ChazyTheBest** [comment]
@eternoendless Is "a lot of work" something that some PRs can't solve?

**Comment by matks** [comment]
> @eternoendless Is "a lot of work" something that some PRs can't solve?

The needed work to support php8 is actually a lot more than some PRs.

Here are the parts I can think of:
- for each of our php composer dependency, check that it supports php8 too, if not we need to upgrade this dependency and make sure all the code relying on this dependency is updated too
- find in PrestaShop codebase all code statements not php8 compliant, fix them
- have QA team run a full no-regression QA campaign for both php7 and php8 versions to find all issues we might have forgotten

(there might be more parts)

It's a lot more than just some PRs.

**Comment by eternoendless** [comment]
@PierreRambaud I believe that some dependencies require us to bump Symfony to 4.4 to provide support for PHP 8, could you please share which ones?

**Comment by mvorisek** [comment]
Error handlers for `set_error_handler` must account for https://php.watch/versions/8.0/fatal-error-suppression if they want to keep ignoring `@` operator, eg. https://github.com/PrestaShop/PrestaShop/blob/1.7.7.4/classes/controller/Controller.php#L687 must be replaced with:

```
if ((error_reporting() & ~(\PHP_MAJOR_VERSION >= 8 ? 4437 : 0)) === 0) {
    return false;
}
```

**Comment by PierreRambaud** [comment]
> @PierreRambaud I believe that some dependencies require us to bump Symfony to 4.4 to provide support for PHP 8, could you please share which ones?

ping @atomiix :wink:

**Comment by atomiix** [comment]
@eternoendless @PierreRambaud
`php 8` requires `doctrine/orm` `^2.8`
`doctrine/orm` `^2.8` requires `doctrine/common` `^3.0`

`symfony/symfony` `3.4` requires `doctrine/common` `^2.4`

so the only way to get `php 8` working is to update `symfony/symfony` to at least `4.2`

**Comment by matks** [comment]
@atomiix

**Comment by matks** [comment]
Do we close this issue @atomiix ? Step "all native modules must be compatible with PHP 8.0 (CI must add check for PHP 8.0)" is not done yet. We can open another issue (or many issues) for the last step.

**Comment by atomiix** [comment]
@matks I guess we can close it yes, actually, except for `productcomments` & `blockreassurance` that we don't know yet if they are compatible with php8, the other seems to be!

**Comment by PierreRambaud** [comment]
I'm not sure we can close this one until all our modules are compatible and integrate into the composer.json file

**Comment by andromaque** [comment]
I have a question regarding PHP version that will be supported. The last years, PrestaShop has always been (very) late regarding the PHP version supported, with a tendency to be available mainly on discontinued versions (e.g. 1.7.7 on PHP 7.3 which is not active since 1 year and will be unsupported next month, 1.7.8 which will be released at the same time that PHP 7.4 ends active support etc.) 

PHP 8.1 will be released last month, will this version be supported directly by PrestaShop 8.0 ? This new PS version could be a good opportunity to resync PS cycle with PHP cycle and be in line with other major CMS 🙂

**Comment by eternoendless** [comment]
> PHP 8.1 will be released last month, will this version be supported directly by PrestaShop 8.0 ? This new PS version could be a good opportunity to resync PS cycle with PHP cycle

Yes (TBC by @atomiix), and that is our plan.

**Comment by matks** [comment]
> @matks I guess we can close it yes, actually, except for `productcomments` & `blockreassurance` that we don't know yet if they are compatible with php8, the other seems to be!

@atomiix can you provide a status update 😊  ? still to be done ?

**Comment by atomiix** [comment]
Little update on PHP 8/PHP 8.1:
- The develop branch is already compatible with PHP 8
- We still have to update the CI on native modules so they are tested with PHP 8/PHP 8.1 independently
- Even if PrestaShop already works with PHP 8, a fork of [laminas-code](https://github.com/atomiix/laminas-code) & laminas-eventmanager should be used to be 100% compatible from 7.2 to 8.0/8.1
- To be fully compatible with PHP 8.1, we need:
  - [tactician-bundle](https://github.com/thephpleague/tactician-bundle/pull/127)
  - [smarty](https://github.com/smarty-php/smarty/pull/678)
  - to check pelago/emogrifier
  - to check phpspec/prophecy
  - some other small changes in PrestaShop's code

**Comment by matks** [comment]
FYI some modules have CI attempting to run php8 and it fails

https://github.com/PrestaShop/statsbestcustomers/pull/22
https://github.com/PrestaShop/statscatalog/pull/21

**Comment by DracoBluee** [comment]
Since prestashop 8 has not been released, maybe support for php 8.1?  :)

**Comment by eternoendless** [comment]
Compatibility with PHP 8.1 is now tracked in a dedicated issue: #27888

**Comment by idnovate** [comment]
Could you please update this table?

https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by Caleydon** [comment]
@idnovate : PrestaShop 8.x PHP compatibility chart is here 
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart
