### ISSUE TITLE
FORM FIELDS - newsletter checkbox

### ISSUE THREAD

**Issue by MauroKali** [PrestaShop/PrestaShop#18543]
Hello, 

I encouter a strange issue on form fields - checkbox of newsletter. The value does not change if the checkbox is checked or not. It remains at value=1. I have no errors on console. 

Prestashop version : 1.7.6.4

this is the code on forms-field.tpl 

`
{block name='form_field_item_checkbox'}
   <span class="custom-checkbox">
       <input name="{$field.name}" id="ff_{$field.name}" type="checkbox" value="1" {if $field.value}checked="checked"{/if} {if $field.required}required{/if}>
       <span><i class="fa fa-check rtl-no-flip checkbox-checked" aria-hidden="true"></i></span>
        <label for="ff_{$field.name}">{$field.label nofilter}</label >
    </span>
{/block}
`

**Comment by florine2623** [comment]
Hi @MauroKali ,

What exactly is the issue ?
I've created 2 accounts. One with newsletter subscription and the other one without.
It works fine : 
Customer news letter has checked his subscirption to the newsletter
Customer test test has not
![Capture d’écran 2020-04-09 à 15 52 21](https://user-images.githubusercontent.com/16019289/78902509-2d21a580-7a7a-11ea-8c05-2df54636d0de.png)

Let me know if you have more questions,
Thanks

**Comment by MauroKali** [comment]
hello @florine2623 
and thanks for your feedback. 

Well, if I check the subscription it's ok :) 
![image](https://user-images.githubusercontent.com/24568905/78903787-ed5bbd80-7a7b-11ea-83a1-681e6248cead.png)

But the issue it's that even if I am not optin I receive a mail as my subscription is validated.

**Comment by florine2623** [comment]
Hi @MauroKali 
You need to check the configuration of the newsletter module. There you can choose the option of sending an email verification / confirmation to the customer.
If the customer does not want to receive the newsletter anymore, he can unsubscribe directly from his customer account.

**Comment by MauroKali** [comment]
hi @florine2623 

this option is set as NO but I reach the mails as well

![image](https://user-images.githubusercontent.com/24568905/78909457-d620ce00-7a83-11ea-9f11-981b099b79dc.png)

**Comment by florine2623** [comment]
This is the right configuration !
Could you show me the email you receive please ?

**Comment by MauroKali** [comment]
![image](https://user-images.githubusercontent.com/24568905/78915554-66631100-7a8c-11ea-9580-77600bc1e060.png)

**Comment by florine2623** [comment]
Hi @MauroKali ,
It is a bug, it has been fixed. 
Please check that issue : https://github.com/PrestaShop/PrestaShop/issues/17990

Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #17990

**Comment by MauroKali** [comment]
thank you @florine2623 :)
