### ISSUE TITLE
Add link to good first issue label in the README

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#18553]
Improve the _Contributing_ section of the README with the following information:

1. add a link to the list of **good first issues** so that beginners can contribute

2. update to **75** the number of translation projects available on Crowdin

**Comment by colinegin** [comment]
I think this should be linked to the Good first issue project (which could be considered an EPIC).

**Comment by Progi1984** [comment]
Fixed by #18501
