### ISSUE TITLE
Product delivery in and out of stock not shown in FO

### ISSUE THREAD

**Issue by mcube27** [PrestaShop/PrestaShop#18559]
#### Describe the bug

The product $product.delivery_in_stock and $product.delivery_out_stock are configured in the general settings and also in the product but the span delivery-information is empty.

```
<div class="tax-shipping-delivery-label">
              TTC
  span class="delivery-information"></span>
</div>
```

#### Expected behavior

It should be written the text I set in the settings

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/10844608/78969774-12960d80-7b08-11ea-8183-c06b887eed4a.png)

![image](https://user-images.githubusercontent.com/10844608/78969885-5db02080-7b08-11ea-9eb3-aca742656122.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1.33

**Comment by florine2623** [comment]
Hi @mcube27 ,
In your code snippet there's a missing chevron in front of "span".
The problem might come from your theme, please contact the developer of the theme and let me know !

**Comment by mcube27** [comment]
Hi,

Sorry it was a typo in my copy/paste. 

Here is the code in the tempate "product-prices" :
```
<div class="tax-shipping-delivery-label">
      {if isset($configuration.taxes_enabled) && !$configuration.taxes_enabled}
          {l s='No tax' d='Shop.Theme.Catalog'}
      {elseif $configuration.display_taxes_label}
          {$product.labels.tax_long}
      {/if}
      {hook h='displayProductPriceBlock' product=$product type="price"}
      {hook h='displayProductPriceBlock' product=$product type="after_price"}
      {if isset($product.additional_delivery_times)}
        {if $product.additional_delivery_times == 1}
          {if $product.delivery_information}
            <span class="delivery-information">{$product.delivery_information}</span>
          {/if}
       {elseif $product.additional_delivery_times == 2}
          {if $product.quantity > 0}
	     <span class="delivery-information">{$product.delivery_in_stock}</span>
	  {* Out of stock message should not be displayed if customer can't order the product. *}
	  {elseif $product.quantity <= 0 && $product.add_to_cart_url}
		<span class="delivery-information">{$product.delivery_out_stock}</span>
	  {/if}
	{/if}
      {/if}
</div>
```
Looking into the code it looks like ` {if $product.delivery_information}` doesn't exist. And my theme has the same template as the classic. So when someone uses the default delivery times, it might not appear at all.

Is that correct ?

**Comment by florine2623** [comment]
Hi @mcube27 ,
Thanks for the details. I can't reproduce your issue.
Please check with the developer of your theme.
When I test it with the classic theme it works correctly.
Here are the screenshots : 
Configuration : 
![Capture d’écran 2020-04-16 à 14 26 45](https://user-images.githubusercontent.com/16019289/79456622-1dacda00-7fef-11ea-8d47-49fd495f5a5a.png)
In Stock : 
![Capture d’écran 2020-04-16 à 14 31 55](https://user-images.githubusercontent.com/16019289/79456672-31f0d700-7fef-11ea-9a5e-adabc6ea9834.png)

Out of stock : 
![Capture d’écran 2020-04-16 à 14 32 00](https://user-images.githubusercontent.com/16019289/79456683-35845e00-7fef-11ea-9010-b87f5b7f0831.png)
