### ISSUE TITLE
Ecotax value is reduced each time a product is saved

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#18550]
#### Describe the bug

Ecotax value is reduced each time a product is saved.

1. Be sure to have ecotax enabled and set to a specific tax rule (20% in France, for example)
- go to International > Taxes page and enable ecotax
- then refresh page add tax ON ecotax
<img width="856" alt="Capture d’écran 2020-04-10 à 16 54 31" src="https://user-images.githubusercontent.com/3830050/78999942-f7e58800-7b4b-11ea-95db-756c78dc18ca.png">
2. Create a new product and set price without tax to 100, click "save" then refresh the page.
3. Set ecotax value to 10, save, refresh the page. You should see that ecotax amount is 8.3 because 20% tax has been applied.
4. ecotax value is now 8,3333 (=> 10/1,20)
5. do not touch anything, **save again**, refresh the page
6. ecotax value is now 6,944444 (8,333/1,20)
7. and so on....

#### Additional information

* PrestaShop version: 1.7.6 and probably lower versions too
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @prestamodule ,
I could partially reproduce your issue until step 4 with PS version 1.7.5.2 and 1.7.6.4.
Could you please check on your side if step 5 to 7 are still a problem, if yes, can you send me a screenshot please ?
Thanks !

**Comment by matks** [comment]
@prestamodule I though this bug was crazy so I checked too, no issue on 1.7.7.x
Which field do you update for price ? The one on "Essentials" 1st tab or the one in "Pricing" tab ?
When you say "refresh", you mean "click save then reload all page using F5" ?

**Comment by prestamodule** [comment]
@matks I’m talking about 1.7.6, we did not tested on 1.7.7 to be honest.
I use the Pricing.
Refresh the page using F5 yes, so the product object is refreshed...
focus on ecotax value

**Comment by marionf** [comment]
This issue is a duplicate of #10026
@prestamodule you can follow this issue and comment on it if you want

**Comment by marionf** [comment]
Duplicate of #10026

**Comment by matks** [comment]
Might be fixed by https://github.com/PrestaShop/PrestaShop/pull/18580

**Comment by Progi1984** [comment]
@matks Merged

**Comment by matks** [comment]
@prestamodule It's now merged into `1.7.7.x` 😄 
https://github.com/PrestaShop/PrestaShop/pull/18580

However we have released 1.7.6.5 and, [unless a major regression is found or a major security issue is reported](https://build.prestashop.com/news/ps17-patch-release-lifecycle/#when-is-it-decided-to-release-a-patch-), there will be no 1.7.6.6 release, so there will be no backport into `1.7.6.x` branch.

This being said, the patch is very easy to apply to a shop.
And 1.7.7.0 is now very close to release, with public beta phase expected to start next week 😀
