### ISSUE TITLE
error 500 creation de compte nouveau client

### ISSUE THREAD

**Issue by eyalkrief** [PrestaShop/PrestaShop#18555]
[PrestaShopException]
La longueur du champ Customer->passwd est actuellement 60 caractères. Il doit être entre 0 et 32 caractères.
at line 1003 in file classes/ObjectModel.php

998.             }
999. 
1000.             $message = $this->validateField($field, $this->$field);
1001.             if ($message !== true) {
1002.                 if ($die) {
1003.                     throw new PrestaShopException($message);
1004.                 }
1005. 
1006.                 return $error_return ? $message : false;
1007.             }
1008.         }
ObjectModelCore->validateFields - [line 292 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 559 - classes/ObjectModel.php]
ObjectModelCore->add - [line 262 - classes/Customer.php] - [2 Arguments]
CustomerCore->add - [line 516 - classes/ObjectModel.php] - [2 Arguments]
ObjectModelCore->save - [line 195 - classes/form/CustomerPersister.php]
CustomerPersisterCore->create - [line 59 - classes/form/CustomerPersister.php] - [2 Arguments]
CustomerPersisterCore->save - [line 193 - classes/form/CustomerForm.php] - [4 Arguments]
CustomerFormCore->submit - [line 60 - controllers/front/AuthController.php]
AuthControllerCore->initContent - [line 292 - classes/controller/Controller.php]
ControllerCore->run - [line 515 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]
****************************

#### Describe the bug

Each time a customer want to create an account i get this error

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

I know its due to mew way to import paswword but i don't know how to fix it please i need help

* PrestaShop version: 1.7.6.4
* PHP version: 5.6

**Comment by eyalkrief** [comment]
![Capture321](https://user-images.githubusercontent.com/7167028/78926082-c2359600-7a9c-11ea-9739-ce46a26c34a5.PNG)

**Comment by florine2623** [comment]
Hi @eyalkrief ,
Please upgrade your PHP version. to 7.2 and try again.
Here are PS system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks !

**Comment by eyalkrief** [comment]
Hi and thanks for your answer, i did the change 7.2, but instill get same message error :
PrestaShopException]
La longueur du champ Customer->passwd est actuellement 60 caractères. Il doit être entre 0 et 32 caractères.
at line 1003 in file classes/ObjectModel.php
I know This issues is due to last update and the solution os an overide on class but i dont know exactly wich step

**Comment by florine2623** [comment]
Did you do a migration ? Is yes what tool did you use ?
From what version to 1.7.6.4 ?

**Comment by eyalkrief** [comment]
no migration at all, just using oneclick update tools, Get some error when upgrading (php version) so i change for 5.6 and update was ok, but now i get this error when customer create account
im very disapointed cause on phpadmin password is set to 255 varchar
and classes/customer is set 255 varchar
I dont know what to do.. and i'm loosing customers

**Comment by eyalkrief** [comment]
im on ovh domain(sorry for my english i'm french lol)

**Comment by eyalkrief** [comment]
![tempsnip3](https://user-images.githubusercontent.com/7167028/78983847-4af81480-7b25-11ea-8c8f-89f895037659.png)

**Comment by eyalkrief** [comment]
any idea or help ? pls ?

**Comment by florine2623** [comment]
Can you check your override folder ?
Please comment the override folder and check again if you can create an account.
Change ```override``` to ```_override```
Please check and let me know

**Comment by eyalkrief** [comment]
The problem is solved : an old overide solved by deleting it
Thank alot for your help

Le jeu. 16 avr. 2020 à 15:03, florine2623 <notifications@github.com> a
écrit :

**Comment by florine2623** [comment]
You are welcome @eyalkrief .
I will now close this issue !
