### ISSUE TITLE
Error on upgrade to 1.7.6.2 ERROR: SQL error: Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#18561]
During upgrade to 1.7.6.2, there is an error, so upgrade is not complete. 
Error:
`ERROR: SQL error: Column count doesn't match value count at row 1`
It's due to SQL in '1.7.6.2.sql': 
`INSERT INTO `PREFIX_product_lang` SELECT
`entity`.`id_product`, 1, `entity`.`id_lang`, `entity`.`description`, `entity`.`description_short`, `entity`.`link_rewrite`, `entity`.`meta_description`, `entity`.`meta_keywords`, `entity`.`meta_title`, `entity`.`name`, `entity`.`available_now`, `entity`.`available_later`, `entity`.`delivery_in_stock`, `entity`.`delivery_out_stock`
FROM `PREFIX_product_lang` entity
LEFT JOIN `PREFIX_product_lang` entity2 ON `entity2`.`id_shop` = 1 AND `entity`.`id_product` = `entity2`.`id_product`
WHERE `entity2`.`id_shop` IS NULL;`

It's because 2 fields that are added in 1.7.0.0.sql upgrade file:
`ALTER TABLE  `PREFIX_product_lang` ADD  `social_sharing_title` VARCHAR( 255 ) NOT NULL;
ALTER TABLE  `PREFIX_product_lang` ADD  `social_sharing_description` VARCHAR( 255 ) NOT NULL;`
Is the term "NOT NULL" a mistake for these fields?

#### Steps to Reproduce

1. Launch an upgrade to versions >= 1.7.6.2

#### Solutions

Remove "NOT NULL" for fields "social_sharing_title" and "social_sharing_description" in 1.7.6.2.sql
OR
Add values in "INSERT INTO" for fields "social_sharing_title" and "social_sharing_description" in 1.7.6.2.sql

**Comment by bm-services** [comment]
Besides, fields "social_sharing_title" and "social_sharing_description" are not created during installation of 1.7.x but are created in 1.7.0.0.sql. Why?

**Comment by bm-services** [comment]
What are these fields for?

**Comment by florine2623** [comment]
Hi @bm-services ,
Are you using One-click upgrade module to do so ?
From which version are you trying to upgrade ?
Thanks

**Comment by bm-services** [comment]
From 1.6.1.1 and no with One-click upgrade because many times, it didn't give database error when we used it.

**Comment by florine2623** [comment]
Okay, so you are **not** using one click-upgrade to upgrade your shop ?
How are you doing the upgrade ? Are you using any tool ?

**Comment by bm-services** [comment]
"Okay, so you are not using one click-upgrade to upgrade your shop?" No
To upgrade we use a tool we developped, but it used files are these give in PRestaShop zip install, in folder install/upgrade/sql and install/upgrade/php.

**Comment by florine2623** [comment]
Okay thanks for the clarification !
Here's the structure of the tables in 1.7.0.0. You can compare with what you have : https://github.com/PrestaShop/PrestaShop/blob/1.7.0.0/install-dev/data/db_structure.sql

"social_sharing_title" and "social_sharing_description" are not present in 1.7.0.0 nor 1.7.6.2. These fields might come from an external module that is installed in the shop.

Please check and let me know.

**Comment by bm-services** [comment]
But these fields are present here: 
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.0.0.sql
Why?

**Comment by bm-services** [comment]
And it's present in zip of 1.7.6.4 that we can download here: https://www.prestashop.com/en/download

**Comment by florine2623** [comment]
On going issue. I'll get back to you ASAP.

**Comment by florine2623** [comment]
Hi @bm-services ,
The 2 fields ```social_sharing_title``` and ```social_sharing_description``` were actually dropped in 1.7.2.0 via the ```drop_column_from_product_lang_if_exists```  function.

The two files mentioned do not have the same purpose:
- db_structure.sql is used for fresh install and create the whole database structure from nothing
- 1.7.0.0.sql is used for an upgrade from 1.6 to 1.7.0 (or higher), like all the other sql files in the upgrade folder, so it only contains the modification/updates to apply on the database based on its state in a 1.6 shop

You should also know that that ```db_structure.sql``` represents (almost) the whole database structure of the latest version, whereas each of the ```1.7.x.y.sql``` files includes incremental changes from the immediate previous version only

So if you are doing a manual upgrade without any module, you should take that into account.

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
