### ISSUE TITLE
BO - Order page - Missing modal to confirm or cancel the creation of the new invoice

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18573]
#### Describe the bug

- In the Migrated order page when we select `Create a new invoice` and click "Add" => There is no alert displayed
![image](https://user-images.githubusercontent.com/16067358/78980411-20568d80-7b1e-11ea-938b-0ad9aae838b0.png)

#### Expected behavior

We should have a modal to confirm or cancel the creation of the new invoice

#### Steps to Reproduce

1. Go to `admin-dev/sell/orders/orders/{orderId}/view
2. Make sure order status is not "delivered" and you can add products.
3. Make sure your order has invoice. (to generate one, click `generate invoice` in Documents tab
4. Click `Add product`, search and select the product.
5. In right side of the screen you should see select box with invoices, select option `create new invoice`
6. Click Add 
7. see error => there is no modal to confirm or cancel the creation of the new invoice

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by matks** [comment]
@marionf Should we solve this ticket by adding a pop-up or a modal ?
Pop-up is this annoying dirty little box displayed in screenshot.
Modal is the pretty box we used for bulk delete confirm action for example.

**Comment by marionf** [comment]
A modal seems better if possible :+1:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18635
