### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined - error in the admin product pages when are installed extra modules for those pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18571]
Hi
I've found a problem in the admin product pages whit some extra modules;
the problem happens when these modules don't use the hook actionAdminControllerSetMedia to load some extra js files, but displayBackOfficeHeader
in this case their files will be load before the main.bundle.js that should load Jquery
it should be necessary to load it before of others js files to remove all possible problems without these hooks

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/78985590-754bd100-7b29-11ea-8155-22441779839e.png)
![2](https://user-images.githubusercontent.com/653230/78985592-78df5800-7b29-11ea-9145-a6ad0e452d5a.png)
![3](https://user-images.githubusercontent.com/653230/78988004-fefe9d00-7b2f-11ea-9480-4e7c0ec100e4.png)
![4](https://user-images.githubusercontent.com/653230/78988007-00c86080-7b30-11ea-9f1f-1bf4e57c545d.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @maofree ,

Does the jQuery not defined error have an impact on the native functionality in the Back-office ?
If yes, could you please specify ?

Thanks !

**Comment by Maofree** [comment]
hi
I've done some tests, it seems that they do not affect the correct functioning of the page, however I have not checked if those modules work 100%, however the saving of prestashop is not affected by those errors

**Comment by ets-soft** [comment]
Prestashop 1.7 seems not to use jQuery in Symfony pages, you need manually add Jquery js libray when you want to use jquery on those pages.

**Comment by Maofree** [comment]
I think the jquery is loaded from this file
main.bundle.js

the problem is due from some modules that use the hook displayBackOfficeHeader, if they kept following prestashop updates these errors would not exist

**Comment by florine2623** [comment]
Thanks @maofree and @ets-soft for the details.
As you said @maofree , the issue comes from these modules. If you could inform the module's developer that would be awesome !
I will now close this issue as it cannot be reproduced.

**Comment by MaximusBaton** [comment]
this problem has an impact on the native functionality in the Back-office!

```
...
// ./admin/functions.php
function includeDatepicker($id, $time = false)
....
```
this function add jquiry.ui* files before jquery was included in 'main.bundle.js'

![image](https://user-images.githubusercontent.com/10597367/96377342-e67dd800-118d-11eb-84d0-a950d4ff4438.png)

(prestashop 1.7.6.8)

**Comment by navid59** [comment]
So, now what is the solution?

How can I add jQuery in my back-office module ?
I tried to add **$this->context->controller->addJquery()** in  **hookBackOfficeHeader()**
But is not helping  at all.

What will be the solution to call jQuery in back-office module?

**Comment by MaximusBaton** [comment]
I made a workaround with a hope of a fix with next update
`./themes/javascript.tpl`
```
{if isset($js_def) && is_array($js_def) && $js_def|@count}
<script type="text/javascript">
{foreach from=$js_def key=k item=def}
var {$k} = {$def|json_encode nofilter};
{/foreach}
</script>
{/if}

{if isset($js_files) && $js_files|@count}
    {foreach from=$js_files key=k item=js_uri}
        {if $js_uri === '/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js' }
            {assign var="mainBundleDefined" value="y"}
        {/if}
    {/foreach}
    {if isset($mainBundleDefined)}
        <script type="text/javascript" src="/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js"></script>
    {/if}
    {foreach from=$js_files key=k item=js_uri}
        {if isset($mainBundleDefined) }
            {if $js_uri !== '/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js' }
                <script type="text/javascript" src="{$js_uri}"></script>
            {/if}
        {else}
            <script type="text/javascript" src="{$js_uri}"></script>
        {/if}
    {/foreach}
{/if}

{if isset($js_inline) && $js_inline|@count}
<script type="text/javascript">
{foreach from=$js_inline key=k item=inline}
{$inline}
{/foreach}
</script>
{/if}
```

**Comment by NicolaModugno** [comment]
> I made a workaround with a hope of a fix with next update
> `./themes/javascript.tpl`
> 
> ```
> {if isset($js_def) && is_array($js_def) && $js_def|@count}
> <script type="text/javascript">
> {foreach from=$js_def key=k item=def}
> var {$k} = {$def|json_encode nofilter};
> {/foreach}
> </script>
> {/if}
> 
> {if isset($js_files) && $js_files|@count}
>     {foreach from=$js_files key=k item=js_uri}
>         {if $js_uri === '/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js' }
>             {assign var="mainBundleDefined" value="y"}
>         {/if}
>     {/foreach}
>     {if isset($mainBundleDefined)}
>         <script type="text/javascript" src="/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js"></script>
>     {/if}
>     {foreach from=$js_files key=k item=js_uri}
>         {if isset($mainBundleDefined) }
>             {if $js_uri !== '/YOUR_ADMIN_FOLDER_NAME/themes/new-theme/public/main.bundle.js' }
>                 <script type="text/javascript" src="{$js_uri}"></script>
>             {/if}
>         {else}
>             <script type="text/javascript" src="{$js_uri}"></script>
>         {/if}
>     {/foreach}
> {/if}
> 
> {if isset($js_inline) && $js_inline|@count}
> <script type="text/javascript">
> {foreach from=$js_inline key=k item=inline}
> {$inline}
> {/foreach}
> </script>
> {/if}
> ```

I have rewritten/semplified your great workaround @MaximusBaton :)

```
{if isset($js_def) && is_array($js_def) && $js_def|@count}
<script type="text/javascript">
{foreach from=$js_def key=k item=def}
var {$k} = {$def|json_encode nofilter};
{/foreach}
</script>
{/if}

{if isset($js_files) && $js_files|@count}
    {foreach from=$js_files key=k item=js_uri}
        {if $js_uri|strstr:"/themes/new-theme/public/main.bundle.js" }
            <script type="text/javascript" src="{$js_uri}"></script>
        {/if}
    {/foreach}
    {foreach from=$js_files key=k item=js_uri}
        {if ! $js_uri|strstr:"/themes/new-theme/public/main.bundle.js" }
            <script type="text/javascript" src="{$js_uri}"></script>
        {/if}
    {/foreach}
{/if}

{if isset($js_inline) && $js_inline|@count}
<script type="text/javascript">
{foreach from=$js_inline key=k item=inline}
{$inline}
{/foreach}
</script>
{/if}
```

Nicola :)
