### ISSUE TITLE
Croatia - wrong Zone

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#18578]
#### Describe the bug

Croatia is in EU from 1. julija 2013 and it should be placed into Europe zone when made fresh install. Right now it is in Europe (non-EU) zone

#### Expected behavior

Should be placed in Europe zone

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @malcek ,
Thanks for the recommandation.
I will let our Product Team know.
Thanks !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team !

This request seems very relevant, what do you think ?

Thanks !

**Comment by khouloudbelguith** [comment]
Hi, 

it is duplicate of https://github.com/PrestaShop/PrestaShop/issues/9630
we need to close this issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @malcek,

Your ticket is a duplicate of #9630
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #9630
