### ISSUE TITLE
Bad total tax amount on 1.7.6.2

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18583]
Hi, client noticed me of bad tax amount in specific situation. 

@khouloudbelguith Can you please please check it on current 1.7.7, if it still happens?

#### Currency
currency = CZK - Czech koruna
currency->precision = 0 - set manually in ps_currency table

#### Settings
Round up if in middle (default)
Round each line
Tax 21%

#### Current behavior
Products with tax: 1200
Shipping: 165
Total without tax: 1128
**Total tax: 238**
Total with tax: 1365

![Výstřižek](https://user-images.githubusercontent.com/6097524/79011617-b0b7c100-7b64-11ea-999d-02169c54af5e.JPG)

#### Expected behavior

Products with tax: 1200
Shipping: 165
Total without tax: 1128
**Total tax: 237 (236,9 precisely)**
Total with tax: 1365

![sssss](https://user-images.githubusercontent.com/6097524/79011809-26bc2800-7b65-11ea-852a-4a42a3e4d692.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I did not manage to reproduce the issue with PS1.7.6.4 and the branch 1.7.7.x.
1.7.7.x: 
![image](https://user-images.githubusercontent.com/16067358/79442303-abc99600-7fd8-11ea-9d3c-a863d2a50a3f.png)
https://drive.google.com/file/d/1XjmXvtuQhHj1mac7YyN2akIe3xvCrFmP/view?usp=sharing
1.7.6.4
![image](https://user-images.githubusercontent.com/16067358/79442496-e7646000-7fd8-11ea-95ba-44061f97f092.png)
https://drive.google.com/file/d/14AtELqiw0poELuA41D-7PUwCIbzucfsz/view?usp=sharing

Thanks to check and feedback.

**Comment by Hlavtox** [comment]
@khouloudbelguith 

Thank you for checking it. I digged deeper and found out it was caused by incompatibility between OPC and COD module.
When I set shipping price to 130 and COD price to 35, total tax is 238.
When I set shipping to 165, total tax is correct - 237.

I will solve this with the developers of these modules.

Thank you for your time! 🌷

**Comment by khouloudbelguith** [comment]
@Hlavtox, you are welcome!
Feel free to open a new one when needed.

Thanks!
