### ISSUE TITLE
"500 Internal Server Error".

### ISSUE THREAD

**Issue by 2CanD** [PrestaShop/PrestaShop#18588]
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

---
This error shows up after I was trying to give the ' featured products'  another hook on my website. Now I can't log in again to restore it.

**Comment by idnovate** [comment]
Turn on errors (https://www.prestashop.com/forums/topic/224525-how-to-turn-on-error-reporting-for-debug-information-blank-page-500-internal-server-error/)

**Comment by 2CanD** [comment]
Thnx, find it on my FTP, but now the program says; "read-only", so can't change the settings.

**Comment by sarahdib** [comment]
Hello @2CanD 

Can you give us more information : 
- PrestaShop version,
- Php Version
- Module version

And a screenshot or screen record of the error.

Thank you

**Comment by 2CanD** [comment]
Hi,

PS 1.7
PHP 7.2 by Strato.nl
Apparel theme 

It happens when I changed the hook of the featured products.



Verstuurd vanaf mijn iPhone

**Comment by sarahdib** [comment]
@2CanD Which 1.7 prestashop version ?

**Comment by 2CanD** [comment]
I don’t know, how can I check it?
I started the site last November 2019. 


Verstuurd vanaf mijn iPhone

**Comment by sarahdib** [comment]
@2CanD 
In the header of the back office : 
<img width="631" alt="Capture d’écran 2020-04-15 à 18 39 45" src="https://user-images.githubusercontent.com/3034677/79363760-9d339e00-7f48-11ea-9ef8-b573a2fd7372.png">

**Comment by 2CanD** [comment]
The whole problem is, I Can’t reach the backoffice. The Error shows up!

Verstuurd vanaf mijn iPhone

**Comment by sarahdib** [comment]
@2CanD 
I'm sorry we can not reproduce the problem. You can try to contact our support. I'll close this issue.
