### ISSUE TITLE
ps_facetedsearch not considers "PS_ORDER_OUT_OF_STOCK" flag

### ISSUE THREAD

**Issue by ftardio** [PrestaShop/PrestaShop#18585]
I notice module ps_facetedsearch are not considering when you are not using stock management at your store. The result is that, every time you load a category, module are querying stocks from database for all the products and combinations. This can't be a big deal if you're managing a few products and combinations, but if your products have hundred of combinations, query time can be huge, making faceted search module useless.

I have dug a little at the code, and I have made a minimal modification at /src/Adapter/MySQL.php, at useFiltersAsInitialPopulation method. I modified this, at 736 line:

```
$this->setSelectFields(
  [
    'id_product',
    'id_manufacturer',
    /*'quantity',*/
    'condition',
    'weight',
    'price',
  ]
);
if (!Configuration::get('PS_ORDER_OUT_OF_STOCK')) {
  $this->addSelectField('quantity');
}
```

I don't know if those changes are 100% suitable, but in my case it's working and query from faceted search module goes from 24 seconds of execution time to 0.4 seconds (I'm not using stock management, but I'm using products with a huge number of combinations).

This is a minimal change at module, but this can save a lot of time for database queries. Can you check this and if right, implement this in future releases? Thanks!

**Comment by sarahdib** [comment]
Hello @ftardio 

Could you give us more information : 
- PrestaShop Version
- ps_facetedsearch version
- PHP version

Thank you

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
