### ISSUE TITLE
Drag & Drop to change position doesn't save new positions in database (bug in the function ajaxProcessUpdatePositions() ?)

### ISSUE THREAD

**Issue by JulienDucharlet** [PrestaShop/PrestaShop#18581]
PrestaShop version: 1.7.6.4
PHP version: 7.3

Module development : 
function ajaxProcessUpdatePositions() doesn't work properly

on drag and drop to change position of items in the grid, changes are not saved in database

the post ajax with the action updatePositions is visible in the console with a status code 200, but no header or response

**Comment by sarahdib** [comment]
Hello @JulienDucharlet 

PrestaShop 1.7.6.4 isn't compatible with PHP version 7.3 Could you try to change the PHP version to 7.2 and feedback ?

You can find here the compatibility of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thank you
