### ISSUE TITLE
GDPR Complience 

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#18587]
Hello everyone,
the last PrestaShop versions added a feature to be compatible with GDPR rules for user privacy. But there is one thing left. PrestaShop does not ask user for cookie usage. 
Does not this violate the GDPR compliance?

Thanks in advance.

**Comment by vhessam** [comment]
I think this is a necessary feature which should be added out of box..

**Comment by alfonsolr09** [comment]
Hello, in theory I think it is mandatory to notify of the use of cookies, I personally put it on my website with a free module and it works wonderfully. In the official prestashop store there are also modules, but they are all paid.
I attach the link from where I downloaded it for free.
https://mypresta.eu/modules/front-office-features/european-union-cookie-law.html

**Comment by samberrry** [comment]
Nice, but we need this feature out of box, I think this is necessary.
Thanks for your help @alfonsolr09

**Comment by sarahdib** [comment]
Hello @vhessam 

This feature is available on the official marketplace : https://addons.prestashop.com/en/search?search_query=cookie

Thank you
