### ISSUE TITLE
All modules in the Back Office was mixed

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#18608]
#### Describe the bug

Today I discovered that all modules in the Back Office that was structured accordanly to their categories was mixed.
Almoust of them are in the category OTHERS (((
![image](https://user-images.githubusercontent.com/50954519/79159776-56776400-7de1-11ea-987d-5b510ee9d578.png)

PS 1.7.6.3
PHP версія: 7.1.33-14+0~20200320.35+debian8~1.gbpb15fae

I have no idea what happend. All cash I cleaned...

![image](https://user-images.githubusercontent.com/50954519/79161826-d0f5b300-7de4-11ea-80be-84ef0397a075.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sarahdib** [comment]
Hello @photinia73,

this bug appear all the time ? 

Thank you

**Comment by photinia73** [comment]
Hello!This is very strange. I find the course when turn ON debug mode. It was from impossible to connect to my account in the app-store. But in the same time I saw that I am logged in…. I disconnected and entered again. Now Ok. But how it happened I have no idea. I did not change anything…. З повагоюКричмарівська Світлана От: Sarah DibОтправлено: вторник, 14 апреля 2020 г. в 15:23Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] All modules in the Back Office was mixed (#18608) Hello @photinia73,this bug appear all the time ?Thank you—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sarahdib** [comment]
Hello @photinia73 

This happen sometimes when our api is slow.

I close the issue since it's ok now.

Thank you

**Comment by photinia73** [comment]
Thanks! З повагоюКричмарівська Світлана От: Sarah DibОтправлено: вторник, 14 апреля 2020 г. в 16:53Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] All modules in the Back Office was mixed (#18608) Hello @photinia73This happen sometimes when our api is slow.I close the issue since it's ok now.Thank you—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
