### ISSUE TITLE
Smarty cache mixed in multistore shops with different themes

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#18601]
I have multistore with two shops. If I use same theme for both shops, all is fine. But if you use different theme for each shop, there are issues with tpl smarty cache. 
For example, here is video showing, that when I switch to Classic theme for one shop, this shop shows error. It's loading tpl file from cache, that is only used by the other theme and not by Classsic.
https://www.dropbox.com/s/h1q6tec0c5c07nt/presta17multi%20-%20Google%20Chrome%202020-04-13%2013-40-37.mp4?dl=0

Even if you fix this error (with "if" condition to include tpl file only for shop that use it), you get other issues. The common issue may be that different part of common modules (top menu) or theme parts (footer) has different HTML structure in one theme and it will not be shown well in the other theme. It depends which theme you load first -> this cache will be used and the other shop will be broken, because CSS will not load for the incorrect HTML classes / id's  coming from another theme.

* PrestaShop version: 1.7.6.4
* PHP version: 7.2
![bugsmartymultistore](https://user-images.githubusercontent.com/3237634/79118816-2b642480-7d8f-11ea-9d23-6be179ae5c31.jpg)

**Comment by khouloudbelguith** [comment]
Hi @web-plus,

I did not manage to reproduce the issue with PS1.7.6.4, I used three different themes in 3 different shops and they are ok
I attached a screen record
https://drive.google.com/file/d/1gZ5mKDa1PPEqHTWUH4vW8Q5I0D1JVNJ6/view?usp=sharing
You have an issue with the module `wphomefeatured` module, is it provided by your theme?

Thanks!

**Comment by khouloudbelguith** [comment]
There is an issue related to themes and multistore reported here: https://github.com/PrestaShop/PrestaShop/issues/9763 fixed in the next release 1770 with this PR: https://github.com/PrestaShop/PrestaShop/pull/13804

Thanks!

**Comment by web-plus** [comment]
Thank you for reply.  OK, it may be fixed in DEV version, as you say, I didn't try in dev build. 
I tested with 1.7.6.4 and there it's not working (tested on clean test installation and reported by client on another shop).

**Comment by khouloudbelguith** [comment]
@web-plus,

I tried again with 1765 and 4 stores with different themes and they are ok.
https://drive.google.com/file/d/1oA2p2FTk22OBBTq9RrRIQkQs5oxWGkDa/view?usp=sharing
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by web-plus** [comment]
> @web-plus,
> 
> I tried again with 1765 and 4 stores with different themes and they are ok.
> https://drive.google.com/file/d/1oA2p2FTk22OBBTq9RrRIQkQs5oxWGkDa/view?usp=sharing
> Despite our several trials, we could not reproduce your issue with the provided information.
> It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
> I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
> 
> Thanks!

I'm sorry, but I don't see how your video proofs that what I reported is working. On your video, I see that shop 2 a 3 has broken header layout. That's one of issues that I described. Also, I don't see you testing that one of your themes includes some tpl file, which doesn't exist in any other theme...

**Comment by khouloudbelguith** [comment]
@web-plus, as I said this issue was fixed in the next version 1.7.7.x with this PR: https://github.com/PrestaShop/PrestaShop/pull/13804 to fix shared smarty compilation ID across shops / themes.

Thanks!

**Comment by web-plus** [comment]
ok, thanks
