### ISSUE TITLE
BO - Customer View page - Wrong number of "Last emails"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18602]
#### Describe the bug

In the BO => Customers => Customer View page, the number of last emails is incorrect.
![image](https://user-images.githubusercontent.com/16067358/79132341-72134800-7daa-11ea-875a-632de130ae88.png)

In the PS1.7.5.2, there are no numbers
![image](https://user-images.githubusercontent.com/16067358/79132297-5a3bc400-7daa-11ea-8e24-ff1e8aaf0e73.png)

#### Expected behavior

The correct number of last Emails 

#### Steps to Reproduce

1. Configure your shop to receive Email
2. Go to FO, sign in with "pub@prestashop.com" and create an order
3. there are two emails went
4. BO => Customers => Customer View page 
5. Last Emails section => check number => NOK

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/79132147-13e66500-7daa-11ea-91a6-e0022702fdc3.png)
![image](https://user-images.githubusercontent.com/16067358/79132739-27460000-7dab-11ea-94bd-824cb040e44b.png)

#### Additional information

* PrestaShop version: 177x,1764, 1760
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by Progi1984** [comment]
Fixed by #18607
