### ISSUE TITLE
BO - gsitemap - the button Uncheck all/ Check all is not displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18603]
#### Describe the bug

In the BO => gsitemap configuration page, the button `Uncheck all/ Check all` is not displayed
So, it is difficult now to check and uncheck all options manually.
It was ok with PS1.7.6.4 & PS1.7.5.2 and gsitemapv4.1.0

#### Expected behavior

It should be displayed
![image](https://user-images.githubusercontent.com/16067358/79133324-219cea00-7dac-11ea-9284-32f94bf176f8.png)
![image](https://user-images.githubusercontent.com/16067358/79133328-23ff4400-7dac-11ea-845f-7876aceffe8e.png)

#### Steps to Reproduce

1. Go to BO => Module manager page
2. configure gsitemap module
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/79133363-30839c80-7dac-11ea-96aa-b6f1a6a2dab6.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2
* Module version: 4.1.0

**Comment by Progi1984** [comment]
PR PrestaShop/gsitemap#134

**Comment by Progi1984** [comment]
Fixed by PrestaShop/gsitemap#134
