### ISSUE TITLE
BO - New employee page - Help Card is not displayed in sidebar

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18615]
#### Describe the bug

In the BO => Team => Employees Tab => Add anew employee page, When we click on the button 'help', the sidebar is not opened in the same page, it redirect us to `shop.com/admin-dev/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop.com%252Fen%252Fdoc%252FAdminEmployees%253Fversion%253D1.7.6.0%2526country%253Den/Help?_token=pKbqyg0aj7rVlQAJSXFU1rliXcpAEgdxcp-id8R3BWE
`
#### Expected behavior

SideBar opened in the same page

#### Steps to Reproduce

1. Go to the BO => Team => Employees Tab => Add anew employee page
2. Click on button 'Help'
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/79221548-4d74aa00-7e56-11ea-8c58-f8a522a76db8.png)

#### Additional information

* PrestaShop version: 177x,1760,1764
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/18279

**Comment by Progi1984** [comment]
Fixed by #18637
