### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by Pierpaolo-Amarante** [PrestaShop/PrestaShop#18612]
#### Describe the bug

Hi, I'm new and I have this 500 error in the BO,
I was on the BO side in the module manager section and I was configuring the modules when I finished configuring I realized that the module manager section had an internal 500 error on "alerts" and "updates". If you enable debugging and click on "alerts" and "updates" the page returns to work, if you disable debugging the page returns to error 500, 
does anyone know why?
I checked in the server logs they gave me this information that pulls too much for me I don't know what you're talking about, I put it in attachment so that I can see
#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to the BO
2. click module manager
3. scroll to "alerts" and "updates".

**Screenshots**

![logs](https://user-images.githubusercontent.com/47488488/79216357-4f863b00-7e4d-11ea-8e92-938c6ac6b108.PNG)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.27

**Comment by khouloudbelguith** [comment]
Hi @Pierpaolo-Petros,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/15m8WzmjWiqrn7JFeYnEr8zISm-vKOKc3/view?usp=sharing
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Pierpaolo-Amarante** [comment]
scusami ora ho letto ero impegnato, grazie della risposta, leggo l'articolo da te fornito e ti rispondo

**Comment by Pierpaolo-Amarante** [comment]
Salve e grazie del aiuto, spero di darti più informazioni possibili.

uso server Vhosting
Versione Prestashop 1.7.6.4

ecco i log del server
![log error](https://user-images.githubusercontent.com/47488488/79863398-fe8bbf00-83d7-11ea-9e1b-4946f10e4cf9.PNG)

configurazione php
![php1](https://user-images.githubusercontent.com/47488488/79863426-09deea80-83d8-11ea-8710-b235350fc456.PNG)

informazione da prestashop
![info presta](https://user-images.githubusercontent.com/47488488/79863456-1400e900-83d8-11ea-9172-91495bc819f1.PNG)

video del debug
https://drive.google.com/file/d/1pZf8OGwoVkBVfDIMxmUHTpMoQSIlqJVM/view?usp=sharing

Grazie di tutto

**Comment by khouloudbelguith** [comment]
Hi @Pierpaolo-Petros,

What is the exact module did you try to translate it, is it provided by PrestaShop?
This issue is different from the first comment, is it? 

Thanks!

**Comment by Pierpaolo-Amarante** [comment]
Grazie a te. @khouloudbelguith 
Si e diverso il primo lo risolto tramite il provider del server.

Dopo la risoluzione di questo problema ho fatto un check del BO e ho riscontrato quest'altro errore 500 nella traduzione dei moduli, tutti i moduli mi capita questo error 500, 
ho fatto delle ricerche e forse sono riuscito a trovare la soluzione ma essendo alle prime esperienze non vorrei modificare il codice. sto valutando come risolvere, ti metto il link di ciò che ho trovato, dammi riscontro.

https://github.com/PrestaShop/PrestaShop/pull/15871

Cosa mi Consigli, Grazie!!!

**Comment by khouloudbelguith** [comment]
Hi @Pierpaolo-Petros,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by Pierpaolo-Amarante** [comment]
HI @khouloudbelguith 
Sorry I'm new, but I'm a fast learner.
Thanks for the support.

Yes and different the first is solved through the server provider.

After solving this problem I did a BO check and found this other error 500 in the translation of the modules, of all the modules I found error 500,
I've done some research and maybe I found the solution but being at the first experiences I don't want to modify the code. I'm considering how to solve it, I'll put you the link of what I found, give me feedback.
https://github.com/PrestaShop/PrestaShop/pull/15871

**Comment by PierreRambaud** [comment]
Hi @Pierpaolo-Petros Could you check your PHP logs that are store on the server?
The 500 error is a generic status saying the server has a problem, we need the exact error to understand what happened and help you finding a solution.

**Comment by Pierpaolo-Amarante** [comment]
Hi @PierreRambaud, Thanks a lot, see if that's okay?
I'm waiting for your feedback

![log](https://user-images.githubusercontent.com/47488488/80408380-60ac5e80-88c7-11ea-8f7c-55aed945fd8d.PNG)

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud, Thanks a lot, see if that's okay?
> I'm waiting for your feedback
> 
> ![log](https://user-images.githubusercontent.com/47488488/80408380-60ac5e80-88c7-11ea-8f7c-55aed945fd8d.PNG)

We need to server log / php log, this one doesn't contains information relative to the error.

**Comment by Pierpaolo-Amarante** [comment]
hi 

> > Ciao @PierreRambaud , grazie mille, vedi se va bene? 
> > Sto aspettando il tuo feedback
> > ![log](https://user-images.githubusercontent.com/47488488/80408380-60ac5e80-88c7-11ea-8f7c-55aed945fd8d.PNG)
> 
> Abbiamo bisogno di server log / php log, questo non contiene informazioni relative all'errore.

Thanks for your answer,
I'm not very practical, but I'm committed.

I didn't have the php logs, I had them activated by my provider and I did some tests on the '500 error' since the file was new.

**Comment by Pierpaolo-Amarante** [comment]
[farmahopephp.log.zip](https://github.com/PrestaShop/PrestaShop/files/4546258/farmahopephp.log.zip)

**Comment by Pierpaolo-Amarante** [comment]
[prod.zip](https://github.com/PrestaShop/PrestaShop/files/4546267/prod.zip)

**Comment by PierreRambaud** [comment]
I see two redundant errors in your logs:
```
[2020-04-25 13:32:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function isUsingNewTranslationSystem() on null" at /data/vhosts/farmahope.\
it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php line 208 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function isUsingNe\
wTranslationSystem() on null at /data/vhosts/farmahope.it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php:208)"} []                                                                                                                                                                           
[2020-04-27 20:19:50] request.CRITICAL: Uncaught PHP Exception SoapFault: "Could not connect to host" at /data/vhosts/farmahope.it/httpdocs/farmahope/modules/farmadatimulti/classes/FarmaDatiAPI.php line 999 {"e\
xception":"[object] (SoapFault(code: 0): Could not connect to host at /data/vhosts/farmahope.it/httpdocs/farmahope/modules/farmadatimulti/classes/FarmaDatiAPI.php:999)"} []
```

Can you try to disable your `farmadatimulti` module?

**Comment by Pierpaolo-Amarante** [comment]
> Vedo due errori ridondanti nei tuoi registri:
> 
> ```
> [2020-04-25 13:32:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function isUsingNewTranslationSystem() on null" at /data/vhosts/farmahope.\
> it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php line 208 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function isUsingNe\
> wTranslationSystem() on null at /data/vhosts/farmahope.it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php:208)"} []                                                                                                                                                                           
> [2020-04-27 20:19:50] request.CRITICAL: Uncaught PHP Exception SoapFault: "Could not connect to host" at /data/vhosts/farmahope.it/httpdocs/farmahope/modules/farmadatimulti/classes/FarmaDatiAPI.php line 999 {"e\
> xception":"[object] (SoapFault(code: 0): Could not connect to host at /data/vhosts/farmahope.it/httpdocs/farmahope/modules/farmadatimulti/classes/FarmaDatiAPI.php:999)"} []
> ```
> 
> Puoi provare a disabilitare il tuo `farmadatimulti`modulo?

Of course I can disable it, but this module acts as a filter for drugs, i.e. it allows me to upload through 'misan' code the drugs that can be sold online.

I can disable it, test it, and update you.

Thank you very much

**Comment by Pierpaolo-Amarante** [comment]
I deactivated the pharmacology module, but the translation of the forms has always been "error 500".
I emailed the developer of the farmadati module, with you indications of the critical error of the API.

How you can fix this:
[2020-04-25 13:32:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function isUsingNewTranslationSystem() on null" at /data/vhosts/farmahope.\
it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php line 208 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function isUsingNe\
wTranslationSystem() on null at /data/vhosts/farmahope.it/httpdocs/farmahope/src/Adapter/Translations/TranslationRouteFinder.php:208)"}

**Comment by PierreRambaud** [comment]
@PrestaShop/prestashop-product-team Did you already see the problem? I'm not able to reproduce :/

**Comment by PululuK** [comment]
Hi @PierreRambaud  @Pierpaolo-Petros  @khouloudbelguith 

This can happen when modules using the new translation system return unexpected values
Could related to : https://github.com/PrestaShop/PrestaShop/pull/15871
See here (how you can reproduce ): https://github.com/PrestaShop/PrestaShop/pull/15871#issuecomment-540955173

Thanks

**Comment by marionf** [comment]
> @PrestaShop/prestashop-product-team Did you already see the problem? I'm not able to reproduce :/

Absolutely not, @PierreRambaud as you didn't reproduced the issue, I close it

**Comment by Pierpaolo-Amarante** [comment]
> Hi @PierreRambaud @Pierpaolo-Petros @khouloudbelguith 
> 
> This can happen when modules using the new translation system return unexpected values
> Could related to : #15871
> See here (how you can reproduce ): [#15871 (comment)](https://github.com/PrestaShop/PrestaShop/pull/15871#issuecomment-540955173)
> 
> Thanks

Hello guys, @PierreRambaud @PululuK @khouloudbelguith 
I made the changes you recommended in the related to: # 15871, although I am not practical but with a little calm I did it, now it does the callback, this however has not solved the problem, now it tells me that all the modules they do not exist, I am not a programmer but it is as if we were missing a file that locates these modules and therefore declares them non-existent. I tried to play the video at this link:
https://drive.google.com/file/d/17flm4-xHoBJ-fuLGHdaJlehwRP67JrIR/view?usp=sharing

Regardless, thank you for your support

**Comment by PululuK** [comment]
Hi @Pierpaolo-Petros 

I found a lead. But you must first assure me that you have a development platform! (I advise you not to test anything directly in production)
