### ISSUE TITLE
BO - Orders & Invoices page - an exception is displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18626]
#### Describe the bug

In the BO => Orders & Invoices Page, an exception is displayed

In the install page, randomly, we have
![image](https://user-images.githubusercontent.com/16067358/79257563-17511d80-7e8a-11ea-84ba-6ff455431591.png)

#### Steps to Reproduce

1. Go to BO => Orders page & Invoices page
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/79257131-78c4bc80-7e89-11ea-99d4-8e4f16114992.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
This regression is displayed after the merge of this PR: https://github.com/PrestaShop/PrestaShop/pull/18425

Thanks!

**Comment by PululuK** [comment]
Hi @khouloudbelguith 

Conflict with https://github.com/PrestaShop/PrestaShop/pull/18220 recently merged

**Comment by presteus** [comment]
You have a second problem with this class, why the name of the class and the filename do not respect recommandation
**Class name:** HTMLTemplateDeliverySlipCore
**Filename:** HTMLTemplateDeliverySlip.php

My attempt to play with PrestaShop is a pain since 2 weeks :(

**Comment by Matt75** [comment]
@presteus This files classe name and files name are same since 1.3 or less. Change it will be a breaking change

**Comment by eternoendless** [comment]
> You have a second problem with this class, why the name of the class and the filename do not respect recommandation
> **Class name:** HTMLTemplateDeliverySlipCore
> **Filename:** HTMLTemplateDeliverySlip.php

This is unrelated to the reported issue and it has to do with the legacy [override system](https://devdocs.prestashop.com/1.7/modules/concepts/overrides/).

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18628
