### ISSUE TITLE
No more statistic after an upgrade from 1.6

### ISSUE THREAD

**Issue by emilieatelier** [PrestaShop/PrestaShop#18624]
#### Describe the bug

1.7.6.1 prestashop, the statistics don t work. I can t see any actual data.

#### Expected behavior

Before on the 1.6 everything work normaly

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![image](https://user-images.githubusercontent.com/63663739/79252810-81fe5b00-7e82-11ea-976f-fcc9d9fc9345.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by MatShir** [comment]
Hi @emilieatelier,
Could you please provide us with more info and all step of your upgrade? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
 
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

@PrestaShop/prestashop-support, Have encountered any similar problems?

**Comment by emilieatelier** [comment]
@MatShir you speake only English or maybe french?

**Comment by khouloudbelguith** [comment]
Hi @emilieatelier,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by khouloudbelguith** [comment]
Hi @emilieatelier,

English is the norm on the GitHub
Thank you!

**Comment by emilieatelier** [comment]
@khouloudbelguith  ok no problem, becaus I saw that sometimes i find the french language. I will try to do the bug report

**Comment by emilieatelier** [comment]
![image](https://user-images.githubusercontent.com/63663739/80293947-78b79d00-8764-11ea-803c-2a26f1bfeb01.png)


![image](https://user-images.githubusercontent.com/63663739/80293953-8705b900-8764-11ea-9bd9-e5a9c593944c.png)


it s enought or you need more if yes what i have to click

**Comment by florine2623** [comment]
Hi @emilieatelier ,
Is this issue happening only on the Dashboard page ?  Of no data is shown in the Stats tab ?
Thanks!

**Comment by emilieatelier** [comment]
@florine2623 on the dashboard page i see any number from the statistics. When i enter to the statistic page I see only the number of visit on my page and regestration anything else.

![image](https://user-images.githubusercontent.com/63663739/80758761-6fe51380-8b36-11ea-85ff-6256c101f85f.png)

**Comment by sarahdib** [comment]
Hello @emilieatelier ,

Could you try to reset the module : Data mining for statistics ?

Thank you

**Comment by emilieatelier** [comment]
@sarahdib yes of course, and i uninstall and install again and nothing change

**Comment by florine2623** [comment]
Hi @emilieatelier ,
Please check in the log file if you had any errors during the upgrade.
Or send me the log file. You can find it in your_admin/autoupgrade/tmp/log.txt
Thanks

**Comment by emilieatelier** [comment]
The same question that in the other issu, where i can find it?

**Comment by florine2623** [comment]
In your FTP in path :  your_admin/autoupgrade/tmp/log.txt

**Comment by emilieatelier** [comment]
You know what, yesterday I contacted a company who will help me with my prestashop because their are different problem that i have to repair. I hope that they will help me
