### ISSUE TITLE
404 Error when I want to go on Product Page

### ISSUE THREAD

**Issue by guirou62** [PrestaShop/PrestaShop#18634]
Hi,

#### Describe the bug

I created a new product with a new attribute, I have changed the product URL in "SEO & URL". On the front office, on a category page, I click on my new product, I have a 404 error.

#### Expected behavior

I would like to see my product page

#### Steps to Reproduce

1. Go to Catalog > Attributs & caracteristics
2. Click on Add an new attribute
3. Put 'Conditionnement' to Name and Public Name
4. Click on Save
5. Click On "Conditionnement" attribute and on "Add a value"
6. On Value input, put "2.5 kg" and another value "7 kg"
7. Create a new Product (Name, Image, Price), select Product with declinaisons, I put This product in category Homme, Clothes and Men (Main Category is Men)
8. Go to 'Declinaisons'
9. On the right, select Conditionnement 2.5 kg and 7kg. (I add 10€ on 7.5 kg)
10. Click on 'Online' and Save the product.
11. Go to "Shop Parameters > Trafic & SEO"
12. For Product routing => {rewrite}-{id}{-:id_product_attribute}.html (I used all important keywords)
13. Go on the front office, on the category 'Men' and click on your new product. You should have a 404 error.

=> If you go on old product, there is no problem, so ... I dunno from where the problem come from ...

**Screenshots**

![image](https://user-images.githubusercontent.com/11886380/79324941-a43eba00-7f10-11ea-996b-54336babaf2c.png)
![image](https://user-images.githubusercontent.com/11886380/79324993-b882b700-7f10-11ea-9653-6c637ffe47b9.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.11

Thank you for your help :)

Guillaume

**Comment by MatShir** [comment]
I was able to reproduce the issue with PrestaShop version 1.7.5.0, 1.7.6.4 and 1.7.7.x
I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thank you!

**Comment by guirou62** [comment]
Honnestly, I didn't and I don't know how to fix this problem but I'm really interested if you found a solution.

**Comment by guirou62** [comment]
Hi,
Did you find some solution to solve this problem ? I'm looking again but I don't find one.
Thank you

**Comment by florine2623** [comment]
This issue is fixed on 8.1.x, 9.0.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/40c9cb7e-c347-44fb-b03e-633d27bc170d



So I'm closing the issue.
