### ISSUE TITLE
Display more than 7 related products

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#18636]
Prestashop 1.7.6.4
Is it possible to change the number of products show in "related products" block?
If yes, how can I do?
Thanks

**Comment by MatShir** [comment]
Hi @centoasa,
It seems we can add a nice amount f product related. See the screenshot bellow.
![screencapture-192-168-42-42-prestashop-admin-dev-index-php-sell-catalog-products-19-2020-04-15-14_51_11](https://user-images.githubusercontent.com/43613217/79339138-b9274780-7f28-11ea-866e-c1b061632ad7.png)
![screencapture-192-168-42-42-prestashop-index-php-2020-04-15-14_52_21](https://user-images.githubusercontent.com/43613217/79339144-baf10b00-7f28-11ea-923a-9a083fd37116.png)

Could you please provide us with more info on your need?
Thank you for your understanding,

**Comment by centoasa** [comment]
On your screenshot only 7 products are show: how can I add much more products show on frontend?

**Comment by MatShir** [comment]
Hi @centoasa,
You are right, you can't configure it from the software. It seems to be blocked at 7 products. 
From the Back office, we can add as many we want but only 7 is displayed. We could check on the page migration the reason @matks.

For your business how much related-product to you need to display? What do you sell that requires related-product? I would like to understand your need.

I sorry to say but there are no updates for your need planned on the 1.7.7 next version but probably could be included in the 1.7.8.

In the meantime, if your objective is more to do cross-selling, we have 2 natives modules that you can download in the 
module catalogue:
- cross-selling: suggest the products that are often bought together 
- viewed product: old product reviewed by your customer 

If the module doesn't suit your need, you can find an advanced module in the [addons marketplace](https://addons.prestashop.com/fr/505-ventes-croisees-packs-produits)

**Comment by MatShir** [comment]
It seems to be fixed on 8.1 new product page :)

**Comment by florine2623** [comment]
It is indeed fixed with 8.1:

<img width="1184" alt="Screenshot 2023-07-05 at 09 23 28" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b760a5e9-f22e-4446-8220-0f1a915dbc8b">
<img width="857" alt="Screenshot 2023-07-05 at 09 25 16" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6b5b4ceb-ac2a-4a4a-bc8e-059c70e2a964">

I'm closing the issue!
