### ISSUE TITLE
wrong order total in FO

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#18640]
After doing the rollback on computing precision (with this pr: #18617), a bug was revealed in the cart page in FO:

<img width="1153" alt="Capture d’écran 2020-04-15 à 15 00 25" src="https://user-images.githubusercontent.com/1784781/79340043-0eb02400-7f2a-11ea-8999-68749fd1ed0c.png">

The cart order total is wrong, here is how to reproduce this behavior:

### How to reproduce

0- Note that this PR (#18617) should be merged before you can reproduce this issue

1- In BO make a product with price TTC 44.157 and TVA 20%. (you can also change the price of an existing product)

2- Add a 20% discount on the product

3- In fo, order this product with a quantity of 2 (2 items)

4- go to cart and see total price

**PS**: if you have demo products installed, just use the **Hummingbird printed t-shirt** and change its price to TTC 44.157, the 20% reduction should already be applied to this product. Be sure it has a 20% tax.

### Additional information

* PrestaShop version: 1.7.7
* PHP version: All compatible versions

**Comment by jolelievre** [comment]
Closed by #18617 Thank you @matthieu-rolland
