### ISSUE TITLE
Fancybox is not a function - when trying to add new order in the admin panel

### ISSUE THREAD

**Issue by alexmixaylov** [PrestaShop/PrestaShop#18643]
#### Describe the bug
After a new installation of PrestaShop, I have problems.
When I go to the Orders page in admin panel (/admin-dev/index.php/sell/orders/orders/new)
and try to add new order I get this javascript error -  `Uncaught TypeError: $(...).fancybox is not a function`.  And clients search does not work

#### Steps to reproduce the behavior:
1. Go to '/admin-dev/index.php/sell/orders/orders'
2. Click on 'New Order'
3. Try to search the client
4. See the error in the browser console, because of this error client search does not work

![js](https://user-images.githubusercontent.com/9370004/79344193-29899500-7f38-11ea-9a7d-7b7d6414a18f.png)

#### Additional information
* Debian Apache2
* PHP version: 7.3
* PrestaShop version: 1.7.7.0

**Comment by khouloudbelguith** [comment]
Hi @alexmixaylov,

Thanks for your report.
I did not manage to reproduce the issue with 1.7.7.x branch and PHP v7.3.15.
I attached a screen record
https://drive.google.com/file/d/1yeQIJwzpDsERzaSGaL105tGJu1Ja6fhW/view?usp=sharing
First, PS1.7.7.0 is not released yet, it is still in progress.
Second, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.


Thanks to check and feedback.
