### ISSUE TITLE
Subcategory product shows in unselected parent category 

### ISSUE THREAD

**Issue by mcube27** [PrestaShop/PrestaShop#18644]
#### Describe the bug

I add a product to a subcategory and not to its parent.
The product still appears in the parent category page.

#### Expected behavior

If I do not select the parent category, it does not show up.

* PrestaShop version: 1.7.6.4
* PHP version: 7.31.4

**Comment by khouloudbelguith** [comment]
Hi @mcube27,

First, In the ps_facetetedsearch's configuration module, we have an option `Show products from subcategories`, you should disable this option.
![image](https://user-images.githubusercontent.com/16067358/79429304-a6b01b00-7fc7-11ea-81ff-06f48b36380b.png)

Second, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by mcube27** [comment]
Thank you, it worked.

I find it strange to be in the facetedsearch.

It would be nice to have it directly in each parent category or in a category global config.

In any case, thank you so much for helping me out here.

**Comment by khouloudbelguith** [comment]
@mcube27, thanks for your feedback.
Since it is ok, I will close the issue.
Feel free to open a new one when needed.

Thanks!
