### ISSUE TITLE
GSitemap module doesn't take into account the selected store when creating the sitemap on a multistore setup.

### ISSUE THREAD

**Issue by jagui** [PrestaShop/PrestaShop#18649]
#### Describe the bug

GSitemap module doesn't take into account the selected store when creating the sitemap on a multi-store shop.

The method `createSitemap($id_shop = 0)` takes a parameter indicating the current store which is never actually passed. As a result of that, the module ignores the selected shop in the admin toolbar.

To further complicate things, if you have a multi-store deployment with two stores and four languages, where the first and second languages are enabled for the first store and the remaining two languages are enabled for the second store, creating the sitemap would create the sub-sitemaps for all the four languages, which clearly is not the expected outcome.

#### Expected behaviour

That a single sitemap is created per shop, containing only the sub-sitemaps for the shop's enabled languages.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. Create a vanilla shop with two stores.
2. Ensure there are four languages installed.
3. Enable two non-overlapping languages per store.
4. Go to the Google Site Map module configuration page.5. Go to the Google Site Map module configuration page.
6. Select one of the stores in the admin toolbar and generate the sitemap
7. Select the other store and generate the sitemap.
8. Check that the *same* sitemap has been generated and it contains *all* the installed languages

**Comment by khouloudbelguith** [comment]
Hi,

This issue can't be reproduced with PS1.7.6.5 and `gsitemap` v4.1.0.

Thanks!
