### ISSUE TITLE
 Change Admin Panels language

### ISSUE THREAD

**Issue by enakhi** [PrestaShop/PrestaShop#18657]
I Can't Change Panels language
![image](https://user-images.githubusercontent.com/8220546/79399723-5d48d700-7f99-11ea-845e-513f725f70aa.png)
because of this:
![image](https://user-images.githubusercontent.com/8220546/79399829-a0a34580-7f99-11ea-9bb6-9466bbd2b79c.png)
select and id must be separated

**Comment by PululuK** [comment]
Hi @enakhi 

See https://github.com/PrestaShop/PrestaShop/issues/18187

Thanks

**Comment by florine2623** [comment]
Hi @enakhi ,
I have not managed to recreate your issue.
What version of PrestaShop and PHP are you using ?

**Comment by enakhi** [comment]
we use prestashop 1.7.6.4 and php 7.4
and this problem exist on any where "<select " is used.
![image](https://user-images.githubusercontent.com/8220546/79461279-31663980-800b-11ea-8df7-55526b10bf81.png)
![image](https://user-images.githubusercontent.com/8220546/79461321-417e1900-800b-11ea-8475-4de278f6567c.png)
![image](https://user-images.githubusercontent.com/8220546/79461522-843ff100-800b-11ea-8c8b-08dad9296d6d.png)

**Comment by PululuK** [comment]
@enakhi , PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by enakhi** [comment]
Thanks alot.
