### ISSUE TITLE
"myweb.com/en/" page not found how to fix NGINX  

### ISSUE THREAD

**Issue by ballprogrammer** [PrestaShop/PrestaShop#18655]

**Comment by khouloudbelguith** [comment]
Hi @ballprogrammer,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1Qdqpx_HN6ogvAjlDNOJ-_AsrC8UM5Vqj/view?usp=sharing
It could be a problem in your Nginx configuration, thanks to check this [link](https://github.com/PrestaShop/PrestaShop/blob/e51d7eaa0164118b88d8cdcddbbe60e64aff7c64/docs/server_config/nginx.conf.dist)
Recently, this file is updated to show how to use multishop and multilanguage as fixed [here](https://github.com/PrestaShop/PrestaShop/pull/12082/files).

Thanks to check and feedback.

**Comment by ballprogrammer** [comment]
@khouloudbelguith 

i will try update php

**Comment by khouloudbelguith** [comment]
@ballprogrammer,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.


Thanks!

**Comment by ballprogrammer** [comment]
![1587042382804@2x](https://user-images.githubusercontent.com/6511752/79459891-31bc0000-801e-11ea-9c91-8f2b983ec933.jpg)
i 
![1587042492518@2x](https://user-images.githubusercontent.com/6511752/79459904-3680b400-801e-11ea-8b43-90a316dca850.jpg)

i reinstall prestashop but can't fix

TwT

please help me

**Comment by khouloudbelguith** [comment]
@ballprogrammer, as I said in my last comment
PrestaShop is not compatible with PHP7.3.
![image](https://user-images.githubusercontent.com/16067358/79460242-d0cc0200-7ff4-11ea-8b61-4a23f7961063.png)

Also, you need to check your Nginx configuration, you can check this file is updated to show how to use multishop and multilanguage as fixed [here](https://github.com/PrestaShop/PrestaShop/pull/12082/files).

Thanks!

**Comment by ballprogrammer** [comment]
ok i will try 7.2

**Comment by khouloudbelguith** [comment]
@ballprogrammer, thanks!
Waiting for your feedback.

**Comment by ballprogrammer** [comment]
![1587042382804@2x](https://user-images.githubusercontent.com/6511752/79464338-24a20f80-8024-11ea-8661-d10ca4e768bc.jpg)


It same problem

**Comment by ballprogrammer** [comment]
![1587045104477@2x](https://user-images.githubusercontent.com/6511752/79464734-a5f9a200-8024-11ea-8ba6-bebc805c6c14.jpg)
It same problem

**Comment by ballprogrammer** [comment]
i get config from this
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist

i don't know what wrong

**Comment by khouloudbelguith** [comment]
@ballprogrammer, it a server issue, your nginx configuration, you need to check it.
Also, you need to check your Nginx configuration, you can check this file is updated to show how to use multishop and multilanguage as fixed [here](https://github.com/PrestaShop/PrestaShop/pull/12082/files).

THanks!

**Comment by ballprogrammer** [comment]
i'll try agin

**Comment by khouloudbelguith** [comment]
@ballprogrammer, thanks!
Waiting for your feedback.

**Comment by ballprogrammer** [comment]
i recheck many time but i don't know what wrong
can you help me ?


server {
    listen   80;
    listen   [::]:80;
    server_name nextshop.upbrand.asia;
    
    rewrite  ^ https://\$server_name\$request_uri? permanent;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl on;
    ssl_certificate /etc/nginx/ssl-certs/nginx.crt;
    ssl_trusted_certificate /etc/nginx/ssl-certs/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl-certs/nginx.key;

    server_name  nextshop.upbrand.asia;
    root         /var/www/html/nextshop.upbrand.asia/public_html;
    index index.php index.html;

    # Redirect 404 errors to prestashop
    error_page 404 /index.php?controller=404;

    # Gzip Settings, convert all types.
    gzip on;
    gzip_vary on;
    gzip_proxied any;

    # Can be enhance to 5, but it can slow you server
    # gzip_comp_level    5;
    # gzip_min_length    256;

    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;

    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # HSTS (Force clients to interact with your website using HTTPS only)
    # For enhanced security, register your site here: https://hstspreload.org/
    # WARNING: Don't use this if your site is not fully on HTTPS!
    # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" preload; always;

    # Cloudflare / Max CDN fix
    location ~* \.(eot|otf|ttf|woff(?:2)?)$ {
        add_header Access-Control-Allow-Origin *;
    }

    # Do not save logs for these
    location = /favicon.ico {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    # [REQUIRED EDIT IF MULTILANG]
    # rewrite ^/fr$ /fr/ redirect;
    # rewrite ^/fr/(.*) /$1;
    rewrite ^/en$ /en/ redirect;
    rewrite ^/en/(.*) /$1;

    # Images
    rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
    rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
    rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
    rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;

    # AlphaImageLoader for IE and fancybox
    rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

    # Web service API
    rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

    # Installation sandbox
    rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;

    # [REQUIRED EDIT] Change this block to your admin folder
    location /admin318qijoji/ {
        if (!-e $request_filename) {
            rewrite ^/.*$ /admin318qijoji/index.php last;
        }
    }


    # File security
    # .htaccess .DS_Store .htpasswd etc
    location ~ /\. {
        deny all;
    }
    # Source code directories
    location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor|var)/ {
        deny all;
    }
    # Prevent exposing other sensitive files
    location ~ \.(yml|log|tpl|twig|sass)$ {
        deny all;
    }

    # Prevent injection of php files
    location /upload {
        location ~ \.php$ {
            deny all;
        }
    }
    location /img {
        location ~ \.php$ {
            deny all;
        }
    }

    # PHP FPM part
    location ~ \.php$ {
        # Verify that the file exists, redirect to index if not
        try_files $fastcgi_script_name /index.php$uri&$args =404;

        fastcgi_index  index.php;

        # Environment variables for PHP
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        include       fastcgi_params;

        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # [REQUIRED EDIT] Connection to PHP-FPM - choose one
        # fastcgi_pass 127.0.0.1:9000;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;

        fastcgi_keep_conn on;
        fastcgi_read_timeout 30s;
        fastcgi_send_timeout 30s;

        # In case of long loading or 502 / 504 errors
        # fastcgi_buffer_size 256k;
        # fastcgi_buffers 256 16k;
        # fastcgi_busy_buffers_size 256k;
        client_max_body_size 10M;
    }

}

**Comment by khouloudbelguith** [comment]
@ballprogrammer, 

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by ballprogrammer** [comment]
I think that are not a "server issue", 
PrestaShop use default in http but not work on https
because another system in the same system don't have a problem
@khouloudbelguith
