### ISSUE TITLE
Allow users to better handle avatars

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#18653]
### Is your feature request related to a problem?

Currently, as a PrestaShop user, it's not very easy to manage my avatar since it is fetched from the related forum profile (if there is any) and this call slows down the back office.

Nice improvement, I agree on cutting off the call to the PrestaShop service to gain performance but I'm not in favor of creating a module for that. Could we remove the call and create a better built-in feature to handle avatars?

_Originally posted by @LouiseBonnard in https://github.com/PrestaShop/PrestaShop/pull/18346#issuecomment-611000014_

### Describe the solution you'd like:

Selecting an avatar is quite a basic feature so the idea here is to first offer users a simple way to define their avatar (points 1, 2, 6). Next, it is to make it flexible enough to have a great base for users willing to go further to be able to extend its usage or management (points 3, 4, 5). It includes:

1. :heavy_check_mark: **Cut off the call** to the PrestaShop service to gain performance, fixed by #18622, thanks @matks!

⚠️ do not forget to delete the information notification, cf. https://github.com/PrestaShop/PrestaShop/issues/18653#issuecomment-621243509

2.  :heavy_check_mark: #20114 **Add an image upload field** to the avatar in order to allow users to define their own profile picture - could be the same characteristics as the image upload fields of the Design > Theme & Logo page with the following allowed formats: .gif, .jpg, .png., and .svg

3. :heavy_check_mark:  #20207 **Create a hook** so that this space can also be used by modules or any other extensions requested by users.

4. :heavy_check_mark: #20207 **Manage its calls** in case several images use this hook: the last item using this hook will be the one displayed.

5. :heavy_check_mark: #20207 **Allow a Gravatar option field** for users who want to use it.

6. :heavy_check_mark: #20430 **Extend the avatar usage to profiles** and allow the SuperAdmin profile (only) to assign a default avatar to an employee category in the Team > Profiles section of the back office. 

:notebook: Avatar are displayed in Logs Page

### Alternatives you've considered

#18346

**Comment by Progi1984** [comment]
@LouiseBonnard We shouldn't lock user to some formats. So `.svg` should be authorized.

Another question : how can developer/user choose between multiple avatars ?

**Comment by matks** [comment]
Note: in My Profile BO page there is a wording explaining current system:
<img width="699" alt="Capture d’écran 2020-04-29 à 16 20 52" src="https://user-images.githubusercontent.com/3830050/80607237-91120b00-8a35-11ea-8c2d-a6bf08cedc81.png">

So we should remove it when we remove current system

**Comment by LouiseBonnard** [comment]
@Progi1984 and @matks, except for the multiple avatar management that needs to be discussed, are those steps okay for you?

**Comment by Progi1984** [comment]
No problem for me ;)

**Comment by colinegin** [comment]
ping @LouiseBonnard is this issue ready to go to dev ?
