### ISSUE TITLE
In offline mode the clear cache display an error

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18650]
#### Describe the bug

In offline mode the clear cache display an error

#### Steps to Reproduce

1. Go to admin (in local)
2. Click on advanced settings -> performances
3. Turn off the internet 
4. Click on clear cache
5. See error

**Screenshots**

<img width="1206" alt="Capture d’écran 2020-04-15 à 16 46 14" src="https://user-images.githubusercontent.com/3034677/79353632-994d4f00-7f3b-11ea-83a0-eb67a5b24e95.png">

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by Matt75** [comment]
This call should be removed from Core when [MBO v2.0.0](https://github.com/PrestaShopCorp/ps_mbo/pull/89) is released, this XML is related to recommended modules.

**Comment by apacios** [comment]
I'm getting the same issue in "Theme catalog" when I'm offline :

**With ps_mbo 1.x.x installed :** 
![withMbo1x](https://user-images.githubusercontent.com/35840830/79362340-c3f0d500-7f46-11ea-9c31-9f0cea0eb79b.png)

**Without ps_mbo :** 
![withoutMbo](https://user-images.githubusercontent.com/35840830/79362357-c81cf280-7f46-11ea-9fe1-a24072d4de95.png)

**Comment by Matt75** [comment]
@sarahdib I have same problem on PrestaShop 1.7.6.0

**Comment by sarahdib** [comment]
@matt75 
1.7.6.3 it's ok 
<img width="1276" alt="Capture d’écran 2020-04-15 à 18 52 43" src="https://user-images.githubusercontent.com/3034677/79365012-5e064c80-7f4a-11ea-819b-a656859813b2.png">

**Comment by jolelievre** [comment]
That's surprising that it works on 1.7.6.3 There are many calls in the core that make the shop fail offline, but I thought they were here for a long time And not related to the 1.7.6 scope

There's an epic related to these issues https://github.com/PrestaShop/PrestaShop/issues/12851

**Comment by Matt75** [comment]
Related to https://github.com/PrestaShop/PrestaShop/pull/12959
It's only when debug mode is enabled !

**Comment by LouiseBonnard** [comment]
Hi @Matt75, is this issue fixed by #12959?

**Comment by kpodemski** [comment]
I could not reproduce this issue using PrestaShop 8.0. I'm closing it.
