### ISSUE TITLE
updating modules gives error 500 and need backup

### ISSUE THREAD

**Issue by eduardob1978** [PrestaShop/PrestaShop#18664]
#### Describe the bug

When try to upgrade a module or use a new template. the page crack and give error 500

#### Expected behavior
Update modules and work normally

#### Steps to Reproduce

1. Go to any module
2. Click on 'update
4. See error on screen

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.3.16

**Comment by khouloudbelguith** [comment]
Hi @eduardob1978,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check and feedback.

**Comment by eduardob1978** [comment]
Version is been changed to 7.2 and 7.1 and still giving HTTP ERROR 500 and breaking the web and need a back up

**Comment by khouloudbelguith** [comment]
@eduardob1978,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by eduardob1978** [comment]
host  tuboxtienda.com<http://tuboxtienda.com>


server setup and configuration

Windows 10
Apache server linux#1
Version PHP 7.2.29
Version Mysql 10.3.22-MariaDB
Navegador Chrome

PrestaShop version 1.7.6.1<http://1.7.6.1>

debug mode report
HTTP ERROR 500

PHP error logs

apache error log

javascript console log

screenshots

In the logs doesn't say anything. Just when I tried to update any module or do any change of template or modules. The page crack with an error HTTP ERROR 500 and I need to restore the shop from the day before



Enviado desde BlueMail<http://www.bluemail.me/r?b=15824>
En 16 abr. 2020, en 13:07, khouloudbelguith <notifications@github.com<mailto:notifications@github.com>> escribió:

@eduardob1978<https://github.com/eduardob1978>,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

  *   host
  *   server setup and configuration
  *   PrestaShop version (source)
  *   debug mode report
  *   PHP error logs
  *   apache error log
  *   javascript console log
  *   screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
@eduardob1978,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by eduardob1978** [comment]
I send some attachment, hope this could help you. Thanks

Enviado desde BlueMail<http://www.bluemail.me/r?b=15824>
En 16 abr. 2020, en 14:59, khouloudbelguith <notifications@github.com<mailto:notifications@github.com>> escribió:

@eduardob1978<https://github.com/eduardob1978>,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by eduardob1978** [comment]
Also I have this file

Enviado desde BlueMail<http://www.bluemail.me/r?b=15824>
En 16 abr. 2020, en 14:59, khouloudbelguith <notifications@github.com<mailto:notifications@github.com>> escribió:

@eduardob1978<https://github.com/eduardob1978>,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by khouloudbelguith** [comment]
@eduardob1978, there are no files attached, you need to sign in to GitHub and upload files here.

Thanks!

**Comment by eduardob1978** [comment]
[tuboxtienda.com-Apr-2020.gz](https://github.com/PrestaShop/PrestaShop/files/4487593/tuboxtienda.com-Apr-2020.gz)
![IMG_20200416_152028](https://user-images.githubusercontent.com/57547778/79465958-438cab80-7ffc-11ea-8cf8-ad963af75d1f.jpg)
![IMG_20200416_152042](https://user-images.githubusercontent.com/57547778/79466025-530bf480-7ffc-11ea-830d-03960fb3535e.jpg)
![IMG_20200416_152053](https://user-images.githubusercontent.com/57547778/79466079-61f2a700-7ffc-11ea-8ef4-19fc1121dc6b.jpg)
![IMG_20200416_152121](https://user-images.githubusercontent.com/57547778/79466123-720a8680-7ffc-11ea-9b3e-0c2207f1069b.jpg)
![IMG_20200416_152146](https://user-images.githubusercontent.com/57547778/79466173-83539300-7ffc-11ea-8e00-a2e032569ee4.jpg)

**Comment by khouloudbelguith** [comment]
@eduardob1978, there are no errors in your file.
Can you check the file log in your `/project_folder/var/logs/`
Thanks!

**Comment by eduardob1978** [comment]
the only logs there is the file that i sent to you before. its ok I will delete prestashop and try to instal again everything, because this it looks deeper that i thought, thank you very much for your help

**Comment by khouloudbelguith** [comment]
@eduardob1978, thanks for your feedback.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
