### ISSUE TITLE
Looking for the usable order management module

### ISSUE THREAD

**Issue by antonincizek25** [PrestaShop/PrestaShop#18679]
Hello, 

I am looking for the usable Prestashop Module where you can manage orders all in one place. So I would be able to print invoices, automatickly marked new orders which are ready to shipp and generate csv files for the transporters. 

Is there anyone who can help me and suggest some usable Prestashop module?

**Comment by florine2623** [comment]
Hi @antonincizek25 ,
You can do that directly on the back-office of your shop under these tabs :
![Capture d’écran 2020-04-17 à 14 02 12](https://user-images.githubusercontent.com/16019289/79567194-0e439480-80b4-11ea-8270-60bc05401fb7.png)

Please, if you are not reporting a bug or a new feature request, do not post on GitHub. The forum is the place for you : https://www.prestashop.com/forums/
Thanks
