### ISSUE TITLE
Product Quantities Wrong after Upgrade to PS 1.7.6.4

### ISSUE THREAD

**Issue by Sascha211** [PrestaShop/PrestaShop#18675]
It seems like the stock available value is not properly updated in front office and product settings, while the amounts in Catalog -> Stocks are correct. Additionally, it is not possible to change the quantity while editing the product. Saving the product after modifying the quantity brings back the former amount. 
Clearing all Caches did not solve the issue. 

### **Screenshots**

**Catalog -> Stocks: Available 0 _(Correct)_**
![](https://www.prestashop.com/forums/uploads/monthly_2020_04/1.png.20098af72263a3e030f19714516821a6.png)

**Catalog -> Products: Quantity 0 _(Correct)_**

![](https://www.prestashop.com/forums/uploads/monthly_2020_04/2.png.646bb8efa8a9aa65cbd34dcd46bdf66b.png)

**Catalog -> Products -> Edit Product: Quantity 6 _(Incorrect)_**

![](https://www.prestashop.com/forums/uploads/monthly_2020_04/3.png.e14b993ac0554320febc7e58d1a90dbb.png)

![](https://www.prestashop.com/forums/uploads/monthly_2020_04/4.png.a8ea0897f3f6591fa9b45fe7d00aee9e.png)

Changing the value here is not possible, after saving the former value returns.

 

**Front Office: Quantity available 6 _(Incorrect)_**

![](https://www.prestashop.com/forums/uploads/monthly_2020_04/5.png.d2fdeaec654b20d5a275407df381e8df.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by florine2623** [comment]
Hi @Sascha211 ,
What tool did you use to do your upgrade ? From which version to 1.7.6.4 ?

Thanks!

**Comment by Sascha211** [comment]
Hi @florine2623,
I used 1-Click Upgrade from 1.7.3.3.

**Comment by florine2623** [comment]
I have done an upgrade 1.7.3.3 > 1.7.6.4 using one-click upgrade.
I could not managed to reproduce the error. Please look at the screenshots : 
**Upgrade** 
![Capture d’écran 2020-04-17 à 11 59 59](https://user-images.githubusercontent.com/16019289/79558705-e00a8880-80a4-11ea-9209-04187fe06f70.png)
![Capture d’écran 2020-04-17 à 12 09 46](https://user-images.githubusercontent.com/16019289/79558717-e436a600-80a4-11ea-95c3-4fd11140f8cb.png)
**Catalog > Stock**
![Capture d’écran 2020-04-17 à 12 14 05](https://user-images.githubusercontent.com/16019289/79558790-0af4dc80-80a5-11ea-8c2a-0121680af6bd.png)
**Catalog > Products**
![Capture d’écran 2020-04-17 à 12 14 38](https://user-images.githubusercontent.com/16019289/79559086-6f17a080-80a5-11ea-9b07-ef03d16497b2.png)
**Catalog > Product > Edit**
![Capture d’écran 2020-04-17 à 12 15 32](https://user-images.githubusercontent.com/16019289/79558962-468fa680-80a5-11ea-88a4-23452adcc2d2.png)
![Capture d’écran 2020-04-17 à 12 16 45](https://user-images.githubusercontent.com/16019289/79559011-56a78600-80a5-11ea-9cdf-1cb152cfc679.png)

**Comment by Sascha211** [comment]
Dear @florine2623,
thank you for putting so much effort into this issue to reproduce it. I finally figured out that the problem is related to Memcached. If caching is disabled, the problems in BO and FO are gone. I'm now trying to achieve the same performance in FO with Apc.

**Comment by matthieu-rolland** [comment]
@Sascha211 
so this issue is not related to a bug in prestashop?

**Comment by Sascha211** [comment]
@matthieu-rolland 
This issue is related to prestashop, because the cache aging does not work properly when using Memcached. The only thing you can do outside PS is flushing the entire Memcached server, which is not really convenient. 

I'm able to reproduce the issue as follows:
Memcached activated: FO shows quantities and prices that are several days old
Memcached deactivated: FO values are correct
Memcached activated: Old values return
Memcached flushed for entire server: FO behaves as expected. After buying something, FO is still showing old quantity.

For me it looks like cached valuables are never or after a much too ling time cleared. Till now, I'm using Apc Caching instead of Memcached which is working fine, but not as fast as Memcached.

**Comment by khouloudbelguith** [comment]
Hi @Sascha211,

I did not manage to reproduce the issue with PS1.7.6.5.
I attached a screen record
https://drive.google.com/file/d/1slh01lNJDE1BodYHODVfEq-vGVTjRsUc/view?usp=sharing
Thanks to check it.

Related to this issue: https://github.com/PrestaShop/PrestaShop/issues/18171, it is added to our bug roadmap.

Thanks!

**Comment by Sascha211** [comment]
Dear @khouloudbelguith,

I reproduced all steps from your screen record and my installation of PS 1.7.6.4 is showing old quantities after changing the stocks in BO with Memcached activated as described before. Probably PS 1.7.6.5 has an improved caching behavior? 
I'll continue using Apc Caching, it is not as fast as Memcached but it works without errors. 

Thank you and all the best

Sascha

**Comment by ibrahimfsasmaz** [comment]
I have the same issue and could not fix, 

1. step: When create a product with combinations for example S M L XL, 1 piece for each size for example, means that you will have 4 in stock in total

2. step: then if you delete these combinations  and go to the product list under "catalog>products", there are still 4 pieces seen under "Quantity" column 

3. step: and after if you generate new combinations , and add new quantity , that new quantity has added on top of the deleted 4. For example if you generated new 4 combination , you will see 8 at products list but infact you only have 4.

 

How can we fix that pls?

prestashop 1.7.7.8
<img width="1421" alt="Screen Shot 2022-02-09 at 13 42 36" src="https://user-images.githubusercontent.com/58822578/153256999-eb828d82-3235-4515-9c27-d26a5020305b.png">

<img width="1132" alt="Screen Shot 2022-02-09 at 13 41 44" src="https://user-images.githubusercontent.com/58822578/153256914-c4cd1947-6b7c-44b4-a7fd-342c175ab6ee.png">

**Comment by ibrahimfsasmaz** [comment]
still no reply and no solution , no fix
