### ISSUE TITLE
Fatal error when editing customer with invalid email

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18676]
#### Describe the bug

Somehow a customers email with special characters passed through our OPC module. When our employee wanted to edit it, Prestashop crashes with fatal error.

#### Expected behavior

Cope with this kinds of errors and show the edit screen. Should be more "bulletproof".

#### Steps to Reproduce

1. Make a customer.
2. Go to ps_customers and change his email to "testš@test.cz"
3. Go to BO > Customers > find the customer > Edit
4. See the error

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
I could not reproduce your issue with the provided information on 1.7.6.4.
Please see screen record : 
https://drive.google.com/file/d/1p8Rt7_9GHXgTF8zdMKiZ4w_hNtJwxz40/view
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 It was fixed in 1.7.6.4, I will upgrade. https://github.com/PrestaShop/PrestaShop/issues/17809

Thank you for your time! 🌷

**Comment by zelarg** [comment]
Another observation is that Prestashop shall not allow invalid email entering DB in first place. There's HTML5 validation on form, but Validation::isEmail does not conform to this, as HTML5 validation is not always enforced.

What about modifying existing regexp there (classes/Validation.php), to something like this? 

`filter_var($email, FILTER_VALIDATE_EMAIL)`

**Comment by khouloudbelguith** [comment]
Duplicate of #17809
