### ISSUE TITLE
Error in the themes/core.js.map

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#18673]
#### Describe the bug

Hello!
On the pages that are looking Ok I see the Error in the DevTools failed to parse SourceMap: https://te.com.ua/themes/core.js.map
How to find what this is the error?... 

![image](https://user-images.githubusercontent.com/50954519/79472752-e64d2600-800c-11ea-8a2b-eec8c6893588.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1Z9MNc7OWoj5gbvu1DpvNvy3TYQk9KqYQ/view?usp=sharing
Thanks to check and feedback.

**Comment by photinia73** [comment]
Can you send me the link to the file core.js.map from 1.7.6.4?

**Comment by khouloudbelguith** [comment]
@photinia73, https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/themes/core.js.map

Thanks!

**Comment by photinia73** [comment]
I don`t understand how it possible, but it wasn`t file core.js.map in the Theme/… only core.js….I copied the file into the folder and there is no error now….  З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: четверг, 16 апреля 2020 г. в 19:48Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] Error in the themes/core.js.map (#18673) @photinia73, https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/themes/core.js.mapThanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by florine2623** [comment]
Hi @photinia73 ,
Ok good if there's no more error.
I'll close this ticket now.
Thanks !
