### ISSUE TITLE
back end's modules not classified into each correct category

### ISSUE THREAD

**Issue by yuxiayuzhou** [PrestaShop/PrestaShop#18684]
#### Describe the bug

My back end's modules are not placed into corresponding category for unknown reason. This can be seen in attached screenshot. It only falls into 2 categories: theme module and others. This is strange. It was not like this.

#### Expected behavior

It should be placed correctly into each category.

#### Steps to Reproduce

1. Go to back end
2. Click on 'module manager'
3. See error

**Screenshots**

see in attached.
![bug](https://user-images.githubusercontent.com/53670538/79570209-23004680-810d-11ea-8639-89bf3307e4e1.png)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @yuxiayuzhou ,
I could not manage to reproduce your issue, please see screenshot below : 
![Capture d’écran 2020-04-17 à 15 50 25](https://user-images.githubusercontent.com/16019289/79576223-3a1a4680-80c3-11ea-92ba-019de7ca1dd1.png)
Is it a fresh install ?

**Comment by yuxiayuzhou** [comment]
@florine2623  sorry, it is me again. a newbie.
The tricky thing is sometimes it follows into the right categories, but sometimes not. It does not happen always. I dot know whether somethere i have changed caused this instability. For the time being, it is still having the issue. But maybe tomorrow, when i open it again, it is gone....

**Comment by khouloudbelguith** [comment]
Hi @yuxiayuzhou,

I did not manage to reproduce the issue with PS1.7.6.5.
![image](https://user-images.githubusercontent.com/16067358/80091857-1e4eee80-8562-11ea-97dc-5a4f593a98a1.png)
It is not a PrestaShop core issue, it is related to the API.
You can follow the PrestaShop status [here](http://status.prestashop.com/).
I close the issue, feel free to open a new one when needed.

Thanks!
