### ISSUE TITLE
Product url with attributes and Google crawl budget

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#18687]
#### Is your feature request related to a problem?

For very large catalog, with a lot of product with combinations, Prestashop will have a lot of different URLs. For combination, we only have one URL to be indexed, the default one, sent as canonical. => That's ok.

Problem is that Google will still crawl the other non indexed pages and it will count toward your crawl budget. 
So with attributes in URL, everyday we're losing crawl from Google on the most important page of the website.

**Comment by hibatallahAouadni** [comment]
Hello @cedricfontaine 

I'm really sorry for the late response :confounded: 
Could you please propose any solution for this problem :sweat_smile: 

Thanks in advance.

**Comment by hibatallahAouadni** [comment]
Hello @cedricfontaine ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
