### ISSUE TITLE
A product allowed to be ordered out of stock with a minimum quantity cannot be added to the BO order.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#18695]
Be aware of the EPIC - Errors when adding a product with minimum quantity in order page #19595

**Describe the bug**
A product allowed be order when it is out of stock and has required minimum quantity can't be added to order even when the required minimum is respected

**Expected behavior**

We have an incorrect alert when the product is out of stock Following these steps:

**Steps to reproduced**

1. Create a productA with Quantity=0 and minimal quantity=10 and Allow orders
2. Go to `admin-dev/sell/orders/orders/{orderId}/view
3. Make sure order status is not "delivered" and you can add products.
4. Click Add product, search and select the last product created productA with quantity=1
5. check alert => NOK (Error! Product with id "22" is out of stock.)
 => it is not out of stock => it should be displayed `Error! Minimum quantity of "10" must be added`
6. Click Add product, search and select the last product created productA with quantity=10
it displays:"
Error!
An unexpected error occurred. [PrestaShopDatabaseException code 0]: Duplicate entry '19-0-2-0-0000-00-00 00:00:00-0000-00-00 00:00:00-0-0-1-0-0-1-0' for key 'id_product_2'", instead of just adding the product in the order

https://drive.google.com/file/d/1B-vnVzqsNDxPNRTYuTvgl3DLjl7r44Ii/view?usp=sharing

Thanks!

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/18614#issuecomment-613537868_

**Comment by sowbiba** [comment]
https://drive.google.com/file/d/1ABR8NiFIwC7ae10OGaslrolxNEZIJdhn/view

The alert is correct for me. Maybe fixed by another PR

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19698
