### ISSUE TITLE
Checkout problem with shipping address

### ISSUE THREAD

**Issue by Frankie-IT** [PrestaShop/PrestaShop#18699]
#### Describe the bug

Hi everyone, I have a problem with shipments to Europe, let me explain better.

When I am in checkout and I select a destination like Germany or Greece, after clicking continue, instead of going to the next screen and viewing the default courier, I always stay in the address screen. But if I change the destination in Italy and click continue it works and makes me move on.

- No shipping management module installed, I use the native Prestashop system
- In the default courier settings the Europe zone is spit with its prices based on weight.
- In the payment settings in the limitations of countries Germany and Greece are ticked to authorize to see the payment forms.
- Everything is active in the Location settings in the Zones, Nations and Provinces sections.
- IP geolocation is turned off.

I applied this fix but it doesn't work [15399](https://github.com/PrestaShop/PrestaShop/pull/15399/files)

#### Expected behavior

I want the checkout system not to get stuck in the shipping addresses section.

#### Steps to Reproduce

https://youtu.be/6aBiFECcwzE

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by matthieu-rolland** [comment]
Hello @Frankie-IT,

I didn't manage to reproduce your issue on 1.7.6.x or 1.7.7.x, could you check if you have an error displayed in the console when you click on continue ?

**Comment by Frankie-IT** [comment]
Hi @matthieu-rolland ,

You mean console errors in the browser?
See this video : https://youtu.be/JbJgSkIALD8

**Comment by khouloudbelguith** [comment]
Hi @Frankie-IT,

As you can see in your screen record
![image](https://user-images.githubusercontent.com/16067358/80093699-45f38600-8565-11ea-8de3-c6c09d616473.png)
It is a theme issue.
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
