### ISSUE TITLE
Prestashop is not compatible with MySQL 8.

### ISSUE THREAD

**Issue by Katakurinna** [PrestaShop/PrestaShop#18705]
#### Describe the bug

I have Ubuntu 18.04 server.
Im trying to install the last version of Prestashop, and install MySQL 8.
With much errors, I see the problem is that prestashop is not compatible with mysql 8. I think it is because of the new MYSQL 8 password system.

#### Expected behavior

The expected behavior is that it works.

#### Steps to Reproduce

1. Install mysql 8
2. Install prestashop
3. In database connection point, use the mysql 8 data to connect.
4. Dont connect.

**Screenshots**

https://www.prestashop.com/forums/topic/1020325-no-se-ha-encontrado-el-servidor-de-la-base-de-datos/?tab=comments#comment-3221204
Here I open a thread with the error.

#### Additional information

* PrestaShop version: 1.8
* PHP version: 7.3
* MySQL version: 8

**Comment by Katakurinna** [comment]
This error happened to me because the default version of mysql in ubuntu 18.04 is mysql 8.
And you say in the installation manual that the command 'apt install default-mysql-server' is used
https://devdocs.prestashop.com/1.7/basics/installation/#installing-a-local-environment

**Comment by Tanguy-SALMON** [comment]
In my memory, it's possible to use MySQL 8 without any problem.
If you can connect in CLI, you should to be able to set the Prestashop connexion.

**Comment by Katakurinna** [comment]
Its fail. I think its because mysql 8 change password system.

**Comment by matks** [comment]
Dont know if it helps / if it's related but I remember struggling as weel with mysql8 on MacOS
Issue was this one https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

Decided to go back to mysql5 😅

**Comment by Katakurinna** [comment]
Yea, I think if you change to native version, its work. But I prefer use mysql 5.7.

**Comment by matthieu-rolland** [comment]
@Katakurinna This issue doesn't seem to be related to prestashop, if you can't connect to your mysql even in CLI then prestashop won't be able to do so either... ;)

Therefore I close this issue.
