### ISSUE TITLE
Enable/Disable button didn't work in BO searching a product

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#18708]
If you search a product in BO using quick search, you cannot enable or disable it by the result, instead it will go into the product page.

Here the video of the problem:
https://drive.google.com/file/d/1i4U6YKkVmrOTnquWQIhvScxWxiPFyGj1/view

Searching it in product section the enable disable button works correctly

* PrestaShop version: 1.7.6.3 and 1.7.6.4
* PHP version: 7.2.29

**Comment by Maofree** [comment]
hi
I've reproduced this bug on a clean prestashop 1.7.6.4
https://drive.google.com/file/d/1-v8EBJNZCZFV-XNDAXAxFGwjG3qkF9p3/view

it is due from the link on the product row, so it is not possible to push on the button to active or disable the produt

bye

**Comment by matthieu-rolland** [comment]
Thank you @Gipielle , I reproduced the issue on 1.7.6.x and 1.7.7.x

**Comment by khouloudbelguith** [comment]
Hi!

This issue is fixed in the develop branch (1780).
I close the ticket.

Thanks!
