### ISSUE TITLE
variable catalog > products

### ISSUE THREAD

**Issue by Nietnagel** [PrestaShop/PrestaShop#18701]
hello i noticed an error. Pre-tax retail price at catalog > products > price must be 
at Retail price and Cost Price different variables.
it makes no sence that unter Cost Price the variable shows Pre-tax retail price.
It must be Pre-tax cost price

Greetings.
![2](https://user-images.githubusercontent.com/63917252/79641589-c77b9a80-8198-11ea-8d6c-44d052dd3dfa.JPG)

---
**Edited by Louise B. the 04th August:**

> take into account that the wording Price (excl) is used in the supplier table in the options tab as well

**Comment by matthieu-rolland** [comment]
Ping @colinegin @MatShir 

do you have any idea if this is actually an issue?

**Comment by LouiseBonnard** [comment]
Hi @Nietnagel, if I understand well, you think that the name of the fields on this tab (see screenshot below) should be changed to be more relevant? or is it about the German translation?

![Capture d’écran 2020-04-22 à 12 01 28](https://user-images.githubusercontent.com/32565890/79969132-589c8b00-8491-11ea-9ba2-d2860384128d.png)

**Comment by Nietnagel** [comment]
Hello your right.
retail price > price (tax excl.) and cost price > price (tax excl.) are not the same.
I think it is a problem with the german translation. in german version it is like this
retail price > selling price (tax excl.) and cost price > selling price (tax excl.)
and must be like this
retail price > selling price (tax excl.) and cost price > purchasing price (tax excl.)

I changed the translation but when i did it, both word are changing because they are the same variable. retail price > price (tax excl.) and cost price > price (tax excl.)

**Comment by LouiseBonnard** [comment]
Very clear, thanks. One solution could be to precise each field, see example below. What do you think?

![Capture d’écran 2020-04-23 à 14 17 09](https://user-images.githubusercontent.com/32565890/80098568-66274300-856d-11ea-8652-bb5b89e20031.png)

**Comment by Nietnagel** [comment]
i think this is a very good solution. Thanks for your support!

**Comment by MatShir** [comment]
@Junebyun @LouiseBonnard for this wording, you have to take into account that the wording Price (excl) is used in the supplier table in the options tab as well

**Comment by marionf** [comment]
Specs updated here: https://github.com/PrestaShop/prestashop-specs/pull/136
