### ISSUE TITLE
catalog > versions and features 

### ISSUE THREAD

**Issue by Nietnagel** [PrestaShop/PrestaShop#18702]
The Table name at catalog > versions and features is in the german version wrong and a change in the translation file brings no change.
"Maßnahmen" is the wrong translation. It must be "Eigenschaften"
![111](https://user-images.githubusercontent.com/63917252/79641545-7075c580-8198-11ea-9322-a08ce786b6e6.JPG)

**Comment by matthieu-rolland** [comment]
ping @LouiseBonnard  do you think there is actually a problem with the wording here?

@Nietnagel: you don't manage to change the wording? Could you please tell us exactly how you try to modify the wording, with a precise list of steps to execute? So that we try to reproduce your issue, ex:

## Steps to reproduce:
1/ ....
2/ ...
Etc...

Also, what prestashop version are you on?

**Comment by LouiseBonnard** [comment]
Hi, I've just changed the translation in [Crowdin](https://crowdin.com/translate/prestashop-official/35766/en-de#5828388). @Nietnagel, feel free to contribute to the German project on Crowdin if you spot other translation mistakes. It should be fixed, I let you check in a couple of days and close this issue, thanks!

**Comment by Nietnagel** [comment]
Hello,

i thought that the translation is wrong, so i changed the translation for german language.
Prestashop shows me 4 search results for "Maßnahmen" I changed all four with no solution.
In the left menu the translation is right. But in the main window not.
I use prestashop 1.7.6.4

**Comment by LouiseBonnard** [comment]
Hi, can you tell me where did you change the translation? On Crowdin or in the International > Translations section of the back office?

**Comment by Nietnagel** [comment]
yes of course. i changed the translation in the International > Translations section of the back office

**Comment by LouiseBonnard** [comment]
@Nietnagel, is the translation still wrong? I've changed it in Crowdin, it should be available after you update the language in the International section of the back office. Let me know if it is fixed or not. Vielen Dank!

**Comment by Nietnagel** [comment]
im sorry. the problem isn`t fixed. it is still called Maßnahmen. When i changed the translation  under International > Translations at the back office there wasn`t a effect too.

**Comment by LouiseBonnard** [comment]
I neither can succeed in having this translation modified, there must be a bug somewhere.

**Comment by marionf** [comment]
This is fixed with PS 1.7.7.0

![capture d'écran_2800](https://user-images.githubusercontent.com/13449658/94822259-bd75ed00-0402-11eb-9c2d-f0569e354b8d.png)
