### ISSUE TITLE
After changing language from the language selector I get ContextErrorException from the contact information module.

### ISSUE THREAD

**Issue by joaolago1113** [PrestaShop/PrestaShop#18707]
#### Describe the bug

After changing language from the language selector, the contact information module broke. 
After disabling the contact information module from the back office the page loaded normally when I changed the language from the language selector.

#### Expected behavior

Page should have loaded normally without crashing.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. From back office, in the contact information module, choose a state for your address with N number of characters, e.i. Maine with N equalling 5.
2. From the language selector pick a language whose id on the ps_lang table exceeds N, e.i a language whose id on the database table is 6.
3. Watch as "ContextErrorException; Notice: Uninitialised string offset: 6" pops in the screen.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/22820692/79697194-37f9e880-8279-11ea-91fa-d6ba9b6abd48.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by matthieu-rolland** [comment]
@joaolago1113 

Tt seems very strange that the bug occurs when the language id is above the country's number of characters 🤯   

But... I reproduced it in 1.7.7.x and 1.7.6.x
