### ISSUE TITLE
1.7.6.4 Order Status Blank White Page

### ISSUE THREAD

**Issue by burakgit** [PrestaShop/PrestaShop#18710]
#### Describe the bug

White pages suddenly, it was working well before at localhost.. 
- When i try to change order status, white blank page, if i refresh it, it says already assigned this statue. No problem about saving.. just cant see the succesfull refresh.
- Also Under Orders, if i try to sort by order status, it gives blank white page
- Also when i create new status, it also gives blank page but after going order status, it has created. refresh is not working.. 
- It send email notification to customer.. 

it is bankwire order.. 

#### Expected behavior
refreashed page with success text. 

#### Versions
I trasfered localhost to live. it was 1.6.0.4, paid module to transfer localhost, it is working under localhost. again trasfered to live. 
PHP 7.2 without fast cgi
Prestashop 1.7.6.4 version

### Error Mode Gives, 

mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/username/www.domain.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636, referer: https://www.domain.com/adminpanel/index.php?controller=AdminOrders&token=d11e478b2dd6bb49d1f2d8116dfe021a
s
cleared cache manual var/cache / prodf 
checked file permissions 755 644
Php version lowered to 7.2 
Restart VPS server 
Cleared Template Cache
https://github.com/PrestaShop/php-ps-info used this, everyting looks ok, except file permissions but they are 755, 777 is not needed. 
![image](https://user-images.githubusercontent.com/32361879/79734114-da0fe400-82fe-11ea-870b-b349f3060a79.png)

### What i found
- Interneal debug mode gives nothing. But the link changes like this, when i click status change.
index.php?controller=AdminOrders&vieworder=&id_order=5213&token=d11e .. bla bla
index.php?controller=AdminOrders&vieworder&token=d11e478 bla bla 
(white screen link, no id_order) **Same as localhost.**

After refreshed and succesfull new status changed for order console error log:
![image](https://user-images.githubusercontent.com/32361879/79731700-51dc0f80-82fb-11ea-8069-5155444b89b9.png) **same as localhost**

Also Localhost Chrome Console link waits without order id and then returns back succesfully. 
![image](https://user-images.githubusercontent.com/32361879/79732724-bcda1600-82fc-11ea-96ea-775e850c463a.png)
This is live website. stays with white screen
![image](https://user-images.githubusercontent.com/32361879/79732866-f27eff00-82fc-11ea-8a3b-7da90dcf1bda.png)

200 and 302 difference of course. 

I am tired, what can i do ? 
It is highly commercial big website, but i can not fix the issue. Very very bad. Cant do anything. 

is there any option to reset all STATUS ? Database table ect ?

**Comment by matthieu-rolland** [comment]
Hello @burakgit , I didn't manage to reproduce your white page issue... 

Could you please give a us more precise description of what should be done in order to reproduce this bug? And how did you change the status, from what status to what other one?

Thank you !

**Comment by burakgit** [comment]
Hello @matthieu-rolland 

- Created an user account and , create an order by using bank wire module, everything was ok. 
- This is normal ordering scenario, from admin panel i try to change "preparing" status but it gives blank page, mail received by client. Refreshed page, everything is normal. But everytime, every status gives white page. 

Also

- under orders tab, if you use pagination, for example just select "bankwire type" it also gives blank page. Red dots are working, but yellow marks gives a blank page, refresh is not working. 
![image](https://user-images.githubusercontent.com/32361879/79786925-d60bb280-834e-11ea-8e8a-b0ad78573f74.png)

If you ask before, it was old version, i transfered old live version to localhost with paid prestashop addons. We transfered data to new 1.7.6.4, everything was fresh, module added orders, customers, old status situations, CMS pages ect. it is most popular transfer software, also there is no problem under localhost. 

In addition, Hosting provider sent me detailed logs about some faults, i dont know it is related or not with this situation. 

Mon Apr 20 00:48:08 2020] [error] [client ip] PHP Fatal
error: Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException:
Failed to remove directory
"/home/domain/var/cache/dev/":
rmdir(/home/domain/var/cache/d ev/):
Directory not empty. in
/home/domain/vendor/symfony/sy mfony/src/Symfony/Component/Filesystem/Filesystem.php:180,
referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 00:48:08 2020] [error] [client ip] Stack trace:,
referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 00:48:08 2020] [error] [client ip] #0
/home/domain/classes/Tools.php (3431):
Symfony\\Component\\Filesystem\\Filesystem->remove(Array), referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 00:48:08 2020] [error] [client ip] #1 [internal
function]: ToolsCore::{closure}(), referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 00:48:08 2020] [error] [client ip] #2 {main},
referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 00:48:08 2020] [error] [client ip] thrown in
/home/domain/vendor/symfony/sy mfony/src/Symfony/Component/Filesystem/Filesystem.php
on line 180, referer:
https://domain/index.php/improve/modules/manage? _token=PGI2yXTfM2-5NaJf6XHtWT9boDkgKfyxXbxBPQBX5iQ
[Mon Apr 20 07:41:21 2020] [error] [client 5.101.0.209] client denied by
server configuration:
/home/domain/vendor/phpunit
[Mon Apr 20 07:41:22 2020] [error] [client 5.101.0.209] client denied by
server configuration:
/home/domain/vendor/phpun

**Comment by burakgit** [comment]
i investigate by using wrong statment to understand which line is stucking. 

under controller/admin/adminorderscontroller.php

line 562

Tools::redirectAdmin(self::$currentIndex . '&id_order=' . (int) $order->id . '&vieworder&token=' . $this->token);


this redirection is not working. Why ? i dont know. it stucks in there. 

### UPDATE**i delete this line, it is working, but "it says while we were sending email a fault  happened. "
also mail is receving by customer. no fault.** 
![image](https://user-images.githubusercontent.com/32361879/79801791-71a91d00-8367-11ea-932d-fee9e4e0f726.png)
under orders, sorting by anything else problem is still active. 

what is going on ? 

is there any php mode / apache .. ect preventing redirection or somethin else ? 

what about /**tools/ under htaccess files,** there is 3 or more different htaccess how can i re create them ? 

@matthieu-rolland

**Comment by burakgit** [comment]
it is general save problem, most of SAVE buttons gives blank page which is relate with controller=adminXXXX 

When i replace JS folder to JS_OLD, it is fixed the Orders tab paging white screen problem. i dont know what is going on. 

Most of them is related with admin related things,

-  index.php?controller=AdminOrders&vieworder=&id_order=5213&token=d11e478b2dd6bb49d1f2d8116dfe021a
-  contoller=AdminAddresses
contoller=admincartrules
controller=adminmodules
controller =adminpdf
do they have common things ? i can easy local to live to fix it, but i dont have any hope.

**Comment by khouloudbelguith** [comment]
@burakgit, what is the exact tool did you use to make an upgrade to the PS1.7.6.4.
Is it the 1-click upgrade? if yes, what is the exact version did you use? have you any errors during the upgrade?

Thanks!

**Comment by burakgit** [comment]
@khouloudbelguith  it is not one click update, commercial one. i fixed it accidently, it is caused by one module. But i used deactive all thirdaprty modules ect, if i completly uninstall it is fixed.. 
thank you.

**Comment by khouloudbelguith** [comment]
Hi @burakgit,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
