### ISSUE TITLE
Exception on all FO pages when adding a language and a category in menu

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#18711]
We have a bug appearing when a new category is added to the menu in fo, and a new language is added in BO.

## How to reproduce:
1- Go to BO add a language
2- Add a category in BO
3- In the menu module, add the new category to the menu
4- go to FO, change language

see error:
<img width="1082" alt="Capture d’écran 2020-04-20 à 11 39 28" src="https://user-images.githubusercontent.com/1784781/79737466-a4b5c700-82fb-11ea-8d83-be3032fd50c2.png">

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18743
