### ISSUE TITLE
error 500 when u wanna search between customers 

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#18714]
Hi
In customer page when I wanna search between customer I get error 500 with that account that I am using and I understood this problem its happen when I am using Persian lang.
the source of this problem back to the Persian numeral that your team added in the panel because when u wanna set a date limitation u will got error too.
pls delete this Persian numeral from your system or fix it this problem completely.
it's a few months that I have a lot of problems with Persian panel and most of them back to these numbers that use in the date part or stock or price and so on. 

* PrestaShop version: 1.7.6.4 Persian lang
* PHP version: 7.2

**Comment by matthieu-rolland** [comment]
@IranDec hello, on what page exactly do you get the 500 error, customer listing? Customer detail?

> the source of this problem back to the Persian numeral that your team added in the panel because when u wanna set a date limitation u will got error too.

ping @LouiseBonnard do you know what he is talking about?

**Comment by LouiseBonnard** [comment]
@matthieu-rolland, I think you're supposed to try to reproduce the issue to qualify the bug. ;-)

**Comment by IranDec** [comment]
Hi @matthieu-rolland 
check this image
https://ibb.co/Lvq1ZcP

**Comment by LouiseBonnard** [comment]
Dear @IranDec and @matthieu-rolland, it looks related to datetimepickers so I've done some research and... it might be fixed by PR #17975! Can you guys confirm?

**Comment by IranDec** [comment]
Hi @LouiseBonnard 
thanks for your follow-up
yes, I think its the same problem but how can I test that before release?
"Convert Arabic/Persian digits to Latin digits in DatePickerType"
 but my problem, it doesn't relate only to DatePickerType, its related to each place that uses Arabic/Persian digits.
in sign up form or in-stock page or the product page.

is it possible to add "Jalali Calendar" into the Persian Panel?

**Comment by LouiseBonnard** [comment]
Unfortunately, this feature is still in progress, cf. PR #11571. By the way, you can use [Vagrant](https://github.com/PrestaShop/vagrant) to test PrestaShop. ;-)

If this issue regards the Jalali Calendar, let's redirect to PR #11571, complete it with your information and close this issue to avoid duplicate.
