### ISSUE TITLE
Address still get duplicated

### ISSUE THREAD

**Issue by peter9x** [PrestaShop/PrestaShop#18725]
After update to 1.7.6.5, still get the error when editing an address in the checkout as Guest, a new address was created instead of replacing it.

<img width="776" alt="Captura de ecrã 2020-04-20, às 17 11 25" src="https://user-images.githubusercontent.com/63051215/79774098-40f6c280-832a-11ea-8995-5c938134103e.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.24

**Comment by peter9x** [comment]
In ps 1.7.6.3 the checkout edit address form looks like this 
<img width="563" alt="Captura de ecrã 2020-04-20, às 21 57 44" src="https://user-images.githubusercontent.com/63051215/79799252-14ef3780-8352-11ea-867a-54f3d39ec022.png">

In ps 1.7.6.5 is missing the id_address and id_customer... 
<img width="551" alt="Captura de ecrã 2020-04-20, às 21 57 55" src="https://user-images.githubusercontent.com/63051215/79799340-351ef680-8352-11ea-9b2b-94657deda175.png">

I check the CustomerAddressFormCore.php and the the id_address is present, but not pass to html form...

Any suggestions ?

**Comment by peter9x** [comment]
I try this and work perfect!

<img width="990" alt="Captura de ecrã 2020-04-20, às 22 17 33" src="https://user-images.githubusercontent.com/63051215/79800805-d313c080-8354-11ea-8442-2fb7bc1ef3d4.png">

**Comment by sam-pires** [comment]
Hi @tblack-it,
This bug has been fixed on PrestaShop 1.7.6.5 with this PR: https://github.com/PrestaShop/PrestaShop/pull/18103

And  on PrestaShop 1.7.7, here is the PR: https://github.com/PrestaShop/PrestaShop/pull/18073


I didn't manage to reproduce it on both versions.

Do you have more info?

**Comment by sam-pires** [comment]
I'll close the issue.

If you still have the problem please comment it.
