### ISSUE TITLE
install/upgrade/upgrade.php running into error on manual 1.7.6.5 installation

### ISSUE THREAD

**Issue by schenkelchen** [PrestaShop/PrestaShop#18723]
#### Describe the bug

I try to update my version 1.7.6.1 to 1.7.6.5 by following the manual way. (https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/)
After finishing all file operations the very last step is to run upgrade.php. But this attempt fails when trying to run the file via ssh access as well as via my browser.

#### Expected behavior

There should appear a confirmation only that database fields have been updated. When I create another copy of my version 1.7.6.1 and upgrade to 1.7.6.4 it's working fine. But for 1.7.6.5 I get error messages as shown in the screenshots.

#### Steps to Reproduce

Following the manual upgrade steps on https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

**Screenshots**

![https://raw.githubusercontent.com/schenkelchen/screenshots/master/1765-upgrade-php-in-browser.PNG](https://raw.githubusercontent.com/schenkelchen/screenshots/master/1765-upgrade-php-in-browser.PNG)
![https://github.com/schenkelchen/screenshots/raw/master/1765-upgrade-php-in-ssh.PNG](https://github.com/schenkelchen/screenshots/raw/master/1765-upgrade-php-in-ssh.PNG)

#### Additional information

* PrestaShop version: 1.7.6.1, upgrade to 1.6.7.5
* PHP version: 7.2
* MySQL version: 5.6

**Comment by sarahdib** [comment]
Hello @schenkelchen 

I reproduce the issue : 
<img width="914" alt="Capture d’écran 2020-04-21 à 12 06 30" src="https://user-images.githubusercontent.com/3034677/79853812-d3e63a00-83c8-11ea-95d0-c402a8732a4e.png">


Thanks for your feedback :)

**Comment by atomiix** [comment]
Fixed by #19010
