### ISSUE TITLE
BO - ORDER - INVOICE - Impossible to reassign a product to another invoice

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18721]
#### Describe the bug

In BO order if we have multiple invoice in an order when trying to reassign a product to another invoice the save button have no effect.

#### Expected behavior
The invoice reassignment should work

#### Steps to Reproduce

1. Go to BO => order => order => select an order
2. Add a product with a new generated invoice to the order
3. Try to edit the invoice of one of the product
4. Click on save 
5. See error the invoice is not updated

**Screenshots**

https://drive.google.com/file/d/1sgSxXBvW5ROAtxGZqv6nje-7i6soiaz6/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by marionf** [comment]
Hello @SD1982 could you add to do label please ?

**Comment by SD1982** [comment]
Hello @marionf  i have added the "to do" label

**Comment by marionf** [comment]
Thank you @SD1982 
Did you try to reproduce it on 1.7.6.x ? To be sure it's not a regression ?

**Comment by SD1982** [comment]
Hello @marionf this behaviour has been reproduced in 1.7.6.x

**Comment by marionf** [comment]
All right, so I add the 1.7.6.x label, this way we are sure it's not a regression of 1.7.7

**Comment by zuk3975** [comment]
Failed to reproduce on 1.7.7.x

**Comment by khouloudbelguith** [comment]
Hi @marionf,

After a discussion with @SD1982, this issue is regression.
It is ok with PS1.7.6.7.
https://drive.google.com/file/d/1IGjkzlGjghCsEk_xO-tR8vghjNnq2wFs/view?usp=sharing

Thanks!

**Comment by jolelievre** [comment]
I also tried it even with the branch from https://github.com/PrestaShop/PrestaShop/pull/20145 which modifies a lot of things regarding order editing and multi invoice The bug is still present

**Comment by Progi1984** [comment]
Fixed by #20906
