### ISSUE TITLE
Faceted search navigation

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#18722]
It isnt a bug but rather questions.
On PC its working fine but on mobile when i check the filters instead button "search" i have "yes". Thats misleading. Not sure if its due to translation ( using polish ). If yes i cant fie a want to change it. 
Second:
I know i cant place Faceted search navigation on front page only on catalog. But on left side panel i have "featured sale product list" ( see screen ). Is it possible to move Faceted search navigation above this one?

Cheers

Prestashop version: 1.7.6.3
![Screenshot_2020-04-20 Strona główna](https://user-images.githubusercontent.com/60825638/79767456-a6967f00-8329-11ea-8541-1b159047c36b.png)

**Comment by sarahdib** [comment]
Hello @GTriber 

1. do you talk about this button (see the screenshot)
<img width="376" alt="Capture d’écran 2020-04-21 à 11 32 31" src="https://user-images.githubusercontent.com/3034677/79850260-eca02100-83c3-11ea-857b-d711257683fa.png">
2. You can change the position the position in design -> pages search displayleftcolumn and drag and drop the module to change the position.

Thank you

**Comment by GTriber** [comment]
Yes, this button.  For me is translated to "Tak" ( means "Yes" in english ). I rather have it like "search" either "filter". As clients on mobile are disoriented how to search after filter choice.

2. Omg so easy Thank you so much. 👍 

> 
> 
> Hello @GTriber
> 
>     1. do you talk about this button (see the screenshot)
> 
> 
> <img alt="Capture d’écran 2020-04-21 à 11 32 31" width="376" src="https://user-images.githubusercontent.com/3034677/79850260-eca02100-83c3-11ea-857b-d711257683fa.png">
> 2. You can change the position the position in design -> pages search displayleftcolumn and drag and drop the module to change the position.
> 
> Thank you

**Comment by sarahdib** [comment]
Hello @GTriber, you're welcome :)

Ping @LouiseBonnard I didn't find this translation. 
I search in theme translation and module translation but I didn't find it.
Could you check please ? 
Thank you :)

**Comment by GTriber** [comment]
Hello @sarahdib  

I have tried to search in translation. No luck.
> 
> Hello @GTriber, you're welcome :)
> 
> Ping @LouiseBonnard I didn't find this translation.
> I search in theme translation and module translation but I didn't find it.
> Could you check please ?
> Thank you :)

**Comment by LouiseBonnard** [comment]
Okay, it might be localized in _Shop > Theme > Global_. Search for 'Yes' in this repertory in the International > Translations section of the back office to customize its translation in Polish. :-)

**Comment by GTriber** [comment]
@sarahdib @LouiseBonnard 

Only one "Yes" ( "Tak" ) was found in all translations :) Wasnt this one.

Will search more :)

**Comment by GTriber** [comment]
Found it. Thank you so much. @sarahdib @LouiseBonnard 

Looks like my theme had its own ps_facetedsearch.tpl ( located in theme / modules folder ) file . Edited and looks fine now.

Best Wishes and have a nice day.
