### ISSUE TITLE
Blank page in Back office

### ISSUE THREAD

**Issue by crabbi33** [PrestaShop/PrestaShop#18729]
Hello

I have a problem

When i want to acces to module management panel in BO got a white page, same problem when i want to access to paiment options

I set debug mode on ..... and nothing white page no problem report....
I try to disable all my module in DB but nothing more

If someone got an idea

PS 1.7.6.5
local wamp 
php 7.1 (same problem with 7.2)

PS: sorry for my bad english

**Comment by rdy4ever** [comment]
Hi @crabbi33 
There may be a problem with the prod cache.
Manually delete` var/cache/prod` folder from the website's root folder.

**Comment by crabbi33** [comment]
Thx for your answer
i try your proposition but nothing .....
i ll try to replace module table in my DB with those from a clean version...

thx

**Comment by crabbi33** [comment]
So i replace all module table on my DB ..... but nothing

( ps_module, ps_module_access, ps_module_carrier, ps_module_country, ps_module_currency, ps_module_group, ps_module_history, ps_module_preference, ps_module_shop) 

.....

**Comment by sam-pires** [comment]
Hi @crabbi33 
We'll need more info.
Does it happen on a fresh install or an upgrade? Do you have any log?

**Comment by crabbi33** [comment]
> 
> 
> Hi @crabbi33
> We'll need more info.
> Does it happen on a fresh install or an upgrade? Do you have any log?

Hi, 
it's an upgrade from 1.7.2.4 where i had the same problem ... I thought an upgrade remove it ....
In debug mode nothing happen...
Where can i find logs ? (sorry ....)

**Comment by sam-pires** [comment]
Ok, it often comes from modules in this situation.
You can try to disable modules before doing the upgrade and then reactivate them one by one to see if one generates this problem.

About logs, no problem 👍,  there is a paragraph "Adding logs" about the different kinds of logs you can share and where to find them, in this article on our tech blog:
https://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Hope it helps :)

**Comment by crabbi33** [comment]
I don't know how it happend but i think it must be the origin of my problem ....i don't have var folder .....

**Comment by sam-pires** [comment]
🤔 
Sadly, I can't really help you here.

I guess the best is to try to get some help on the forum or through support.

Have a look on the forum if someone had the same problem, or share your issue:
https://www.prestashop.com/forums/

Otherwise, PrestaShop's paid support could help: https://www.prestashop.com/en/support

Let me know if you found some help.

**Comment by crabbi33** [comment]
> 
> 
> 🤔
> Sadly, I can't really help you here.
> 
> I guess the best is to try to get some help on the forum or through support.
> 
> Have a look on the forum if someone had the same problem, or share your issue:
> https://www.prestashop.com/forums/
> 
> Otherwise, PrestaShop's paid support could help: https://www.prestashop.com/en/support
> 
> Let me know if you found some help.

ok thx for help

i find an error in FO, in my store with 1.7.2.4 with the same problem if it can get some indication :

ContextErrorException in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105: Notice: Undefined index: seo_availability

    **in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105
    at ErrorHandler->handleError('8', 'Undefined index: seo_availability', '/homepages/6/d745525897/htdocs/presta/app/cache/dev/smarty/compile/layouts_layout_full_width_tpl/ac/77/6c/ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php', '1105', array('_smarty_tpl' => object(Smarty_Dev_Template))) in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105
    at content_5e99c708cb2130_05660036(object(Smarty_Dev_Template)) in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 324
    at content_5e160277c55911_35648761(object(Smarty_Dev_Template)) in smarty_internal_templatebase.php line 188
    at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl', object(SmartyDev), false, true, false) in SmartyDev.php line 41
    at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl') in FrontController.php line 671
    at FrontControllerCore->smartyOutputContent('catalog/product.tpl') in FrontController.php line 655
    at FrontControllerCore->display() in Controller.php line 225
    at ControllerCore->run() in Dispatcher.php line 379
    at DispatcherCore->dispatch() in index.php line 28**

**Comment by khouloudbelguith** [comment]
Hi @crabbi33,

Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Or could you please try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks!

**Comment by crabbi33** [comment]
> 
> 
> Hi @crabbi33,
> 
> Could you please try to run those command lines to remove the cache:
> `rm -fR /Projet_PrestaShop/var/cache/*`
> 
> ```
> php -d memory_limit=-1 ./bin/console cache:clear
> php -d memory_limit=-1 ./bin/console cache:clear --env=prod
> ```
> 
> Or could you please try to open your shop in an incognito browser.
> You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
> Thanks!

`Hello`

1) i create a file cc.php with the 2 command
```
<?php
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
?>
```
2) i put it in the root

3) i execute it 

4) got 

Parse error: syntax error, unexpected 'memory_limit' (T_STRING) in /homepages/6/d745525897/htdocs/presta/bonjour.php on line 3
'''

**Comment by khouloudbelguith** [comment]
@crabbi33,

The file `bonjour.php` is a custom file.

Thanks!

**Comment by crabbi33** [comment]
> 
> 
> @crabbi33,
> 
> The file `bonjour.php` is a custom file.
> 
> Thanks!

sorry wrong link

if i execute cc.php, got :

Parse error: syntax error, unexpected 'memory_limit' (T_STRING) in /homepages/6/d745525897/htdocs/presta/cc.php on line 3

**Comment by khouloudbelguith** [comment]
@crabbi33,
Can you please try to execute those commands without creating a file. 
You can run them using a terminal. 

Thanks!

**Comment by crabbi33** [comment]
> 
> 
> @crabbi33,
> Can you please try to execute those commands without creating a file.
> You can run them using a terminal.
> 
> Thanks!

Sorry but i don't know how i can do it ....

**Comment by khouloudbelguith** [comment]
@crabbi33,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev). and try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by crabbi33** [comment]
> 
> 
> @crabbi33,
> 
> Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev). and try to open your shop in an incognito browser.
> You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
> Thanks to check and feedback.

Done without succes.....

**Comment by florine2623** [comment]
Hi @crabbi33 ,
Are you sure debug mode is on ? Can you check on the file /config/defines.inc.php and send a screenshot?
Do you have any error when you open the console ? Right-click > inspect element
Thanks!

**Comment by crabbi33** [comment]
Hi

I investigate in my module folder and i find the origin of the problem. It is the module jsonmodule. after commenting this folder all is fine.... i can acces to module and paiement.

I have only one eror in FO when debug mode on

ContextErrorException in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105: Notice: Undefined index: seo_availability

    in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105
    at ErrorHandler->handleError('8', 'Undefined index: seo_availability', '/homepages/6/d745525897/htdocs/presta/app/cache/dev/smarty/compile/layouts_layout_full_width_tpl/ac/77/6c/ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php', '1105', array('_smarty_tpl' => object(Smarty_Dev_Template))) in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 1105
    at content_5e99c708cb2130_05660036(object(Smarty_Dev_Template)) in ac776c302f1a89b1213a2493a23db4c5dd35aedd.file.product.tpl.php line 324
    at content_5e160277c55911_35648761(object(Smarty_Dev_Template)) in smarty_internal_templatebase.php line 188
    at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl', object(SmartyDev), false, true, false) in SmartyDev.php line 41
    at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl') in FrontController.php line 671
    at FrontControllerCore->smartyOutputContent('catalog/product.tpl') in FrontController.php line 655
    at FrontControllerCore->display() in Controller.php line 225
    at ControllerCore->run() in Dispatcher.php line 379
    at DispatcherCore->dispatch() in index.php line 28

thx

**Comment by florine2623** [comment]
Could you clear your cache and hard refresh your browser and test again ?

**Comment by crabbi33** [comment]
> 
> 
> Could you clear your cache and hard refresh your browser and test again ?

done ...but same message

**Comment by florine2623** [comment]
You could try a fe other things :
- clear cache manually following the path of error `presta/app/cache/dev/`
- clear browser cache
- unable all overrides
- unable modules one by one to see which one might cause an issue

Please check and let me know

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
