### ISSUE TITLE
facet filter can not be reseted

### ISSUE THREAD

**Issue by ptidav** [PrestaShop/PrestaShop#18726]
#### Describe the bug

Hello, i created a filter with the faceted search function.
I have a problem, it is impossible to remove the filters in the "active filters" section or using the "clean all" button in the faceted search component when i navigate to another page or if i open a product sheet and i go back.

Issue is the same with the classic theme.

#### Expected behavior

I should be able to remove/reset filters of the faceted seach when i browse products page or if i go back from consulting a product sheet.

#### Steps to Reproduce

1. go to modules
2. open faceted search
3. add a filter template
4. select some products categories
5. activate some filters
6. validate template
7. go to website, activate one or more filters
8. open a product sheet or browse products on page 2,3 or 6, etc
9. click on the cross of an item filter in the active filter section / click on "clean all" in the faceted search component

<img width="596" alt="Capture d’écran 2020-04-20 à 18 28 30" src="https://user-images.githubusercontent.com/49609556/79777448-91c0e800-8337-11ea-9dfb-f567ea6b73ab.png">

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2.29

Thanks for your help

**Comment by sam-pires** [comment]
Hello @ptidav,

I didn't manage to reproduce this bug on PS 1.7.6.5 with Faceted Search v3.5.0

Which version of the module do you use?
Please update the module if you don't use the latest version, and let me know :)

**Comment by ptidav** [comment]
Hello,
i use the latest version 3.5
Thanks

**Comment by khouloudbelguith** [comment]
Hi @ptidav,

I did not manage to reproduce the issue with PS1.7.6.5 and the ps_facetedsearch v3.5.0.
I attached a screen record
https://drive.google.com/file/d/1NOP6-aLEjoKCeYqVqznp3zaCT7yLQOfj/view?usp=sharing
You module is it overridden by your theme? could you please check with your theme author and feedback.

Thanks!

**Comment by ptidav** [comment]
@khouloudbelguith 
re-read my problem : i've the bug IF i open a product sheet or i browse the products pages.
Just apply filters and disable/reset them without open a product sheet or navigate functions normally.

**Comment by khouloudbelguith** [comment]
@ptidav, thanks for these clarifications.
I tried again, but it is ok.
I attached a new screen record
https://drive.google.com/file/d/14lMEP9zBnlT7L77u1gIn8vcZzyEDhog9/view?usp=sharing
Thanks to check and feedback.

**Comment by ptidav** [comment]
Ok it is working for you.
For me same issue with classic theme.
Prestashop has been installed from 1.7.6.3 directly, it's not an upgrade.
I use a professional theme, the developper tell me, as you, he doesn't have this issue.

if someone could tell me where i must begin to investigate to check filter behavior ?....

Thanks

**Comment by khouloudbelguith** [comment]
@ptidav,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ptidav** [comment]
I found the source of this issue. It's due to a seo module.
I realized it by looking at the browser address bar, when i remove the filters, the url is badly modified...
I'll contact the developper

**Comment by sam-pires** [comment]
Thanks @ptidav
