### ISSUE TITLE
Wrong redirection when using the quick search for a category (Second)

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#18732]
In Prestashop 1.7.6.3 and 1.7.6.4

Unsing the quick search in BO and searching for a category
If you click in the category link now it goes always in modify both (pencil right) and also category name (wrong) category name should go into the cateogoty so you can see list of subcategory.

Before, the situation was worse, it has been corrected in part with this fix: #17920

@PululuK 

https://drive.google.com/file/d/1u86zLqlufVgceh3hl640UF7lMKl_hVQ3/view

* PrestaShop version: 1.7.6.x
* PHP version: 7.2.29

**Comment by sam-pires** [comment]
Hi @Gipielle,

Just to be sure, the behavior you expect is the following, right?

In the breadcrumb result:
![Capture d’écran 2020-04-22 à 17 32 25](https://user-images.githubusercontent.com/25405887/80001924-420d2880-84bf-11ea-85ed-c5ddca29ff00.png)

- When clicking on the category **name** -> go to the category's **list page** (where it lists its subcategories)
- When clicking on the category **pencil**  -> go to the category's **edit page**

**Comment by Gipielle** [comment]
Yes, correct

**Comment by Gipielle** [comment]
Hello, the fix is for 1.7.8 only ?

**Comment by PululuK** [comment]
Hi @Gipielle 

Sorry for the delay ... I proposed a solution here https://github.com/PrestaShop/PrestaShop/pull/18937

Thank you !
