### ISSUE TITLE
Rename PrestaShop stats modules to better indicate they are about stats

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#18738]
**Problem**
As discussed by @Progi1984 shared in [this discussion](https://github.com/PrestaShop/core-weekly-generator/pull/29#discussion_r404771828):
"Module name for "stats" doesn't indicate that they are about statistics."

**Solution:**
Rename these modules in the code to indicate they are about stats

**To do**
- [x] Define the names = _{{module_name}} stats_, following https://github.com/PrestaShop/PrestaShop/issues/18738#issuecomment-617855001
- [ ] Update the names everywhere it has to be done

**List of modules :**
```
'statsbestcategories': 'Best categories',
'statsbestcustomers': 'Best customers',
'statsbestmanufacturers': 'Best manufacturers',
'statsbestproducts': 'Best-selling products',
'statsbestsuppliers': 'Best suppliers',
'statsbestvouchers': 'Best vouchers',
'statscarrier': 'Carrier distribution',
'statscatalog': 'Catalog statistics',
'statscheckup': 'Catalog evaluation',
'statsdata': 'Data mining for statistics',
'statsequipment': 'Browsers and operating systems',
'statsforecast': 'Stats Dashboard',
'statslive': 'Visitors online',
'statsnewsletter': 'Newsletter',
'statsorigin': 'Visitors origin',
'statspersonalinfos': 'Registered customer information',
'statsproduct': 'Product details',
'statsregistrations': 'Registrations statistics modules',
'statssales': 'Sales and orders',
'statssearch': 'Shop search',
'statsstock': 'Available quantities',
'statsvisits': 'Visits and Visitors',
```

**Comment by Progi1984** [comment]
I can work on it. ;) when you will have specified this ;)

**Comment by sam-pires** [comment]
Ok some questions 🙂 

Do we have constraints in the naming?
(type of char, char limit, etc.)

Where do these name will appear?
- module Manager/catalog in the BO
- Core-weekly
- Anywhere else will put the name (somewhere specific to have in mind)
- brochures introducing all PrestaShop built-in modules

Do we have to have an English name only, or are they going to be translated into every language we support?
If so, how are they translated?  through Crowdin?

**Comment by Progi1984** [comment]
May be @LouiseBonnard or @colinegin can help you on this

**Comment by LouiseBonnard** [comment]
> Do we have constraints in the naming?
(type of char, char limit, etc.)

No constraint but the shorter the better, think about the translation!

> Where do these name will appear?

And on Addons very soon. ;-)

> If so, how are they translated? through Crowdin?

Built-in modules are translated via Crowdin, in the _Modules_ repertory of each version. And the name is also translated.


Looking for more relevant names makes sense, but a constraint I can see is that their translation won't be available for previous versions of PrestaShop. For instance, if you rename _Carrier distribution_ into  _Carrier statistics_, this new wording will only be pushed with the next minor release so it will 1/ only be translated for users on PrestaShop 1.7.8+ and 2/ remain untranslated for users on previous versions.

Unless we decide to separate the modules translation catalog from the core translation catalog and push modules new wordings outside the release cycle. I believe this topic was raised by @eternoendless some months ago but I can't find any related issue. :-(

**Comment by sam-pires** [comment]
Thks @LouiseBonnard,

According to your response, I would advise creating a simple nomenclature for these names.
Such as: "{{module_name}} stats"

Short, easy to translate (maybe not even needed), solves the pb
wdyt?

**Comment by LouiseBonnard** [comment]
Why not, at the beginning/end of the module name does not look too problematic. But we must make sure it improves the user experience. :-)

**Comment by sowbiba** [comment]
If we change the module name, it will never be translated for older versions than 1.7.8
For example : if "Best categories" becomes "Best categories stats" and have it' s translation in french "Module de statistiques sur les catégories", In all french shops lower than 1.7.8 it'll always be "Best categories stats" once the module is released, even if 1.7.8 is released

Having the translation within the modules won't solve this problem because this new system will be available only for 1.7.8+ shops

**Comment by LouiseBonnard** [comment]
Yes, thanks a lot, @sowbiba! Let's wait for the @PrestaShop/product-team and @PrestaShop/prestashop-core-developers to decide what should be done regarding statistics modules before going any further on this issue.

**Comment by ldeprestashop** [comment]
This issue is close because we will merge on two modules. 

  - #23348 
  - #23349
