### ISSUE TITLE
Bug - Admin interface prestashop 1.7.6 - Styles are broken ?

### ISSUE THREAD

**Issue by valros76** [PrestaShop/PrestaShop#18730]
#### Describe the bug

Hi, my admin interface had a problem. Since 2 days, all styles are broken and I can't make any modifications

#### Expected behavior

I don't modify this website since 6 days. Just have any commands.

#### Steps to Reproduce

1. Go to 'admin'
2. Click on 'products', 'modify product', 'performances'
3. On products page, I have all tabs one one page. On performances page, select lists are brokens and I can't select options.

**Screenshots**

![FireShot Capture 294 - Performances • Aux Essences Elfiques - auxessenceselfiques fr](https://user-images.githubusercontent.com/25286025/79802255-ed9f6700-835f-11ea-9366-b14f99c6663d.jpg)

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.4

**Comment by sarahdib** [comment]
Hello @valros76 

PrestaShop is not compatible with php version 7.4 Could you ask your hosting provider to downgrade php version to 7.2 and feedback ?

**Comment by WernerCD** [comment]
Rocking 1741 and it looks like my hosting provider updated the backend default from 7.2 to 7.4. Jacked everything up.

Rolling back to 7.2 fixed it.

Yes, I need to update but I'll do that in the near future.
