### ISSUE TITLE
Error on front : get() on null

### ISSUE THREAD

**Issue by Spidlace** [PrestaShop/PrestaShop#18741]
Hi !
I have a problem with productcomments module.

#### Describe the bug

When I install module from catalog, no problem ! 
I configure the module but when i go to the front, i have an error : 

```
(1/1) FatalThrowableErrorCall to a member function get() on null
--
in productcomments.php line 939
```

In my partial, hook with name : 

```
{block name='product_reviews'}
    {hook h='displayProductListReviews' product=$product}
{/block}
```

**Screenshots**

![Screenshot_2020-04-21 Screenshot](https://user-images.githubusercontent.com/4738601/79852044-6fc27680-83c6-11ea-9d5d-469f0e3ee41c.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2.25

**Comment by sam-pires** [comment]
Hello @Spidlace,
I couldn't reproduce the bug on my side.

Can you tell me which version of the module you use, please?
Do you use other modules on the product pages?

**Comment by sam-pires** [comment]
Hi @PrestaShop/prestashop-core-developers, does that error ring a bell?

**Comment by Spidlace** [comment]
Hi @sam-pires,

Thanks for your response.
The version of the module is 4.0.1

The bug doesn't happen on the product page, but on my homepage
But for your question, I have two specific modules (not by Prestashop) use on product page : 
- AN Product Extra Tabs Premium
- AN Product Videos

I try to disable this modules but error is here again :-/

**Comment by khouloudbelguith** [comment]
Hi @Spidlace,

I did not manage to reproduce the issue with PS1.7.6.5 and the Product Comments module v4.0.1.
I attached a screen record
https://drive.google.com/file/d/14lMEP9zBnlT7L77u1gIn8vcZzyEDhog9/view?usp=sharing
Did you use a custom theme, is it?
You have other issues
![image](https://user-images.githubusercontent.com/16067358/80122602-0d1bd700-858e-11ea-9c3c-73751343c176.png)
 Thanks to check and feedback.

**Comment by Spidlace** [comment]
Hi @khouloudbelguith,

Thanks for your response ! :-)

Yes I use a custom theme, his name is "Agave"
I try to activate classic theme and everything works ! But with Agave theme, I have errors I display on first post...

The bug appear here (line 6) : 
```php
public function hookDisplayProductListReviews($params)
    {
        /** @var ProductLazyArray $product */
        $product = $params['product'];
        /** @var ProductCommentRepository $productCommentRepository */
        $productCommentRepository = $this->context->controller->getContainer()->get('product_comment_repository');
        $commentsNb = $productCommentRepository->getCommentsNumber($product->getId(), Configuration::get('PRODUCT_COMMENTS_MODERATE'));
        $averageGrade = $productCommentRepository->getAverageGrade($product->getId(), Configuration::get('PRODUCT_COMMENTS_MODERATE'));

        $this->context->smarty->assign(array(
            'product' => $product,
            'product_comment_grade_url' => $this->context->link->getModuleLink('productcomments', 'CommentGrade'),
            'nb_comments' => $commentsNb,
            'average_grade' => $averageGrade,
        ));

        return $this->context->smarty->fetch('module:productcomments/views/templates/hook/product-list-reviews.tpl');
    }
```

On this line : `$productCommentRepository = $this->context->controller->getContainer()->get('product_comment_repository');`

With Classic theme and Agave theme, this line go to getContainer() in "classes/controller/Controller.php" 
But here is the difference : 

- In classic theme : getContainer() call get() function in "vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php"

- In agave theme : getContainer() create error...

Everything happen in the plugin I think...

**Comment by florine2623** [comment]
Hi @Spidlace ,

Thanks for the details.
That is indeed an issue with the Agave theme.
To get that fixed, you will need to contact the developer of that theme. This is is not a core issue from PrestaShop.

Thank you for understanding !
