### ISSUE TITLE
Invalid taxes breakdown in order slips for orders with discount

### ISSUE THREAD

**Issue by shaffe-fr** [PrestaShop/PrestaShop#18742]
#### Describe the bug
As explained by Vincent Beudez in [the Forge Ticket PSCSX-8967](http://webcache.googleusercontent.com/search?q=cache:BoLG5U2056kJ:forge.prestashop.com/browse/PSCSX-8967), PrestaShop has made the choice to ignore discount for order slips.
However, when creating an order slip for an order with discount, the taxes breakdown uses the total discount of the order, resulting an incorrect taxes breakdown in the Order Slip PDF.

#### Expected behavior

I expect the taxes breakdown to be computed from the credit slip amount only and to ignore the total_discounts_tax_excl.

#### Steps to Reproduce

1. Create an order with :
    * 2 products for a total of 100 € with a 20% VAT
    * Add a 10 % cart discount (order total 90 €)
2. Create an order slip for 1 product (45 €)
3. Open the order slip PDF
4. The taxes breakdown total taxes should be 9 € (45 * 0.2) but it is 7 € ((45 - 10) * 0.2).

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7, develop
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @shaffe-fr ,
I tested on PS 1.7.6.5 and I've chosen to get 45€ refund on that order (third option) : 
![Capture d’écran 2020-04-23 à 15 58 26](https://user-images.githubusercontent.com/16019289/80107619-9b3a9200-857b-11ea-94d9-9570ee3569a2.png)
The credit slip I have : 
![Capture d’écran 2020-04-23 à 16 08 10](https://user-images.githubusercontent.com/16019289/80108843-0cc71000-857d-11ea-86cd-42657093213d.png)

The formula to calculate VAT (for example 20%) : **PRICE * 1.2**
In our case : 45 * 1.2 = 7.5 -> OK
45 * 0.2 is not the right formula

**Comment by shaffe-fr** [comment]
I was talking about the tax breakdown, on your screenshot the total tax is 5.83€.

**Comment by shaffe-fr** [comment]
Thanks for your feedback @florine2623. The problem is about the Taxes breakdown, the total tax you highlighted is indeed correct, but the one in the table on the left is different.

**Comment by florine2623** [comment]
Hi @shaffe-fr ,
I'm sorry I didn't understand well your request.
I've checked on PS 1.7.7, I do not have that error anymore : 
![Capture d’écran 2020-04-30 à 17 53 20](https://user-images.githubusercontent.com/16019289/80731783-a5c0d280-8b0b-11ea-9e85-0a8cc09bbcd1.png)

Your issue will be fixed in the version 1.7.7 of PrestaShop that will come out soon!
Thanks!

**Comment by florine2623** [comment]
Fixed on 1.7.7.

**Comment by shaffe-fr** [comment]
Indeed, I was only able to reproduce the bug on 1.7.5 and 1.7.6. Thanks for checking.
