### ISSUE TITLE
error brand prestashop1.7.6.4

### ISSUE THREAD

**Issue by vadrien1999** [PrestaShop/PrestaShop#18750]
Hello, I'm on prestashop 1.7.6.4. I have an error on google search console that I cannot resolve. I've had a lot of mistakes so far, but I've always managed to fix them. But the brand problem I can't solve it. Could you help me please. I would also like to point out that I have already followed the following tutorials:
#12687
#18692
#14558
#12694

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by sam-pires** [comment]
Hello @vadrien1999,

We need more info :)
Can you share the error in the console please?

I believe this could be related to missing "brand" rich snippets, example on Google support: https://support.google.com/webmasters/thread/10162757?hl=en

I saw your comments on related issues. 
We have to do a broader analysis on rich snippets to improve everything.

**Comment by vadrien1999** [comment]
Hello, thank you for helping me. Here are the errors surround
![Produits - Google Chrome 22-04-20 19_34_01 (2)_LI](https://user-images.githubusercontent.com/64008376/80014602-ce741700-84d0-11ea-88ab-d79b7b5f9535.jpg)

**Comment by khouloudbelguith** [comment]
Hi @vadrien1999,

Thanks for your feedback.
Did you use the Classic theme provided by PrestaShop or custom theme?

Thanks!

**Comment by vadrien1999** [comment]
> Salut @ vadrien1999 ,
> 
> Merci pour vos commentaires.
> Avez-vous utilisé le thème classique fourni par PrestaShop ou un thème personnalisé?
> 
> Merci!

hello, this is a custom theme, called Angarthème. But I can provide you with the information you need without worry.

**Comment by khouloudbelguith** [comment]
@vadrien1999, 

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
In the meantime can you try to switch your shop to the Classic theme and check if you ave the same issue.

Thanks!
