### ISSUE TITLE
ContextErrorException Warning: Illegal string offset 'display_prices_tax_incl'

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#18755]
Prestashop 1.7.6.5 (updated to check if the problem is solved - as the problem was the same with 1.7.6.1 as well) - both versions with the same problem
After updating quite many translations in my Multilanguage shop it is no longer possible to make an order, as there is the following error already after clicking on "go to checkout":

**Warning: Illegal string offset 'display_prices_tax_incl'**

Also, it was not possible to have a few sentences translated and saved, they stay empty, even after saving or resetting - maybe this is connected or just seperate topic.
[errormessage.zip](https://github.com/PrestaShop/PrestaShop/files/4511569/errormessage.zip)

**Comment by florine2623** [comment]
Hi @tom75 ,
What languages are you using ?
Do you use any module for checkout ?
What are the exact steps to reproduce the bug ?
Where is the bug located ?
Please check and let me know.

**Comment by decom-media** [comment]
Languages are: De, en, nl, pl, pt, fr, es
No special Modules for checkout, payment modules just from paypal (and Braintree)
Steps to reproduce: put one item in the cart, click on checkout – error is shown (if debug mode is enabled) when paypal module is disabled, it is possible to use payment with braintree module, if paypal is enabled, paypal payment cannot be used as clicking on pay with paypal is generating the same error then with debug mode enabled (with debug mode disabled, just empty page with "false")

**Comment by florine2623** [comment]
I could not manage to reproduce your error neither on 1.6.7.5 and 1.7.5.2.
In your error the module Braintree in mentioned. Please make sure your module is up-to-date. If that's already the case, you will need to contact the developer of the module as the problem come from the module itself and not PrestaShop core solution.
Thanks!

**Comment by decom-media** [comment]
even if i disable all payment modules it is the same error... so, i do not think that this is coming from any payment module.

also, it just happened like this after adding a few translations

**Comment by michaesc** [comment]
This problem affects me as well, with Prestashop 1.7.6.7.
