### ISSUE TITLE
Help box in BO have their markup duplicated

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#18759]
#### Describe the bug

It's not a really a bug but it would make these harder to maintain, the markup is duplicated, so the time we wants to update helpbox, we would need to update it on the whole BO.

#### Expected behavior

Using a reusable twig file, I opened a PR to fix this issue

#### Additional information

* PrestaShop version: develop

https://github.com/PrestaShop/PrestaShop/pull/18184

**Comment by Progi1984** [comment]
Fixed by #18184
