### ISSUE TITLE
Http error 404

### ISSUE THREAD

**Issue by TamasFelix** [PrestaShop/PrestaShop#18758]
I started identifying traffic for [kiwigym.ro](https://www.kiwigym.ro) in google analytics with 404 error
I checked the log from the server
The problem is on every page, I identify traffic on
https://www.kiwigym.ro/preworkout-creatine/muscletech-neurocore-pro-series-50-serv
and then
https://www.kiwigym.ro/preworkout-creatine/muscletech-neurocore-pro-series-50-serv-324

-324 is id from product, I want to mention that I use Pretty URLs

ip-*.12*.*.12 - - [20/Apr/2020:05:06:51 +0000] "GET /preworkout-creatine/muscletech-neurocore-pro-series-50-serv-324 HTTP/1.0" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
ip-*.12*.*.12 [20/Apr/2020:05:06:51 +0000] "GET /index.php?controller=404 HTTP/1.0" 404 45653 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"

Can it be done in this case?

Best Regards,

**Comment by florine2623** [comment]
Hi @TamasFelix ,
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by TamasFelix** [comment]
I solved, there are two possibilities
1 - edit htacces
RewriteEngine On
Rewritecond %{REQUEST_URI} [0-9-]$
RewriteRule ^(.*)-([0-9])+$ /$1 [R=301,L]
2- /override/controllers/front/ProductController.php -> Here the redirect change was made in the comment / * Override georgeb

Works, example:
https://www.kiwigym.ro/sanatate-incheieturi/universal-nutrition-animal-flex-44plicuri-153
or 
https://www.kiwigym.ro/concentrate-proteice/dymatize-iso-100-2-2-kg-95
