### ISSUE TITLE
BO - Product page - Cannot add a specific price

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18751]
#### Describe the bug

In the BO => Product page, when we try to add a specific price, we have an alert `undefined` and an exception in the console

#### Expected behavior

Specific prices should well be added.

#### Steps to Reproduce

1. Go to BO => Product page
2. Create a new product
3. Try to add a specific price

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/79881717-ddd06300-83f1-11ea-924b-972b10850277.png)
![image](https://user-images.githubusercontent.com/16067358/79881798-f8a2d780-83f1-11ea-8c95-69f3659201ef.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by MatShir** [comment]
Before adding to the ToDo column, we need to check if it impacts or can be solve during the migration of the product page.

**Comment by zuk3975** [comment]
the form field for combinations (it is hidden by css when adding a new product) doesn't have a default value, so it is not submitted and therefore issues "undefined index".
This shouldn't be hard to fix if its only enough to provide default value or a "isset/empty" check.
