### ISSUE TITLE
Favicon downloaded from PS's favicon generator is not uploadable

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#18752]
#### Describe the bug

The downloaded file from PrestaShop's favicon generator tool (https://addons.prestashop.com/en/create-favicon.php?success=1) is not uploadable.

#### Steps to Reproduce

1. Go to https://addons.prestashop.com/create-favicon.php?pab=1
2. Upload an image and generate a favicon
3. Download a the generated file named only "favicon"
4. Go to BO > Design > Theme & logo > Favicon > Browse : file cannot be uploaded in PrestaShop (file is disabled):
![bad favicon](https://user-images.githubusercontent.com/7419525/79881474-8631f780-83f1-11ea-8110-41f62134cbc9.jpg)

To solve: You must adding manually missing extension ".ico" in filename:

![good favicon](https://user-images.githubusercontent.com/7419525/79881895-196b2d00-83f2-11ea-834e-72362b921507.jpg)

[EDIT] Adding downloading window screenshot:

![dl favicon](https://user-images.githubusercontent.com/7419525/79883487-44568080-83f4-11ea-9c7d-651d1aad452f.jpg)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1
* MacOS: 10.14.6
* Firefox: 75.0

**Comment by sam-pires** [comment]
Hello @Klemart3D,

It seems to come from Firefox. Works fine on Chrome.

As it is a problem related to the Addons website and not the PrestaShop project, I'll close this issue and share the bug with the Addons team.

Thanks

**Comment by sam-pires** [comment]
Hi @Klemart3D, FYI the bug has been fixed by the Addons team

**Comment by Klemart3D** [comment]
Thanks @sam-pires, I confirm, now favicon file is well formed:

![favicon](https://user-images.githubusercontent.com/7419525/81561298-48dadd00-9393-11ea-9fb1-92c563dab671.jpg)
