### ISSUE TITLE
Return to the page product - FO after login 

### ISSUE THREAD

**Issue by salvacal** [PrestaShop/PrestaShop#18762]
Edit:
**Actual**

When you are visiting a product page and want to login,  it’s tiring for the visitor to find again the page! Please check the issue. Thank You for support.

**Wanted behaviour**

When I log in or create an account on the product page or the checkout, as a merchant want to be redirected to my product page or the checkout.

**Comment by florine2623** [comment]
Hi @salvacal ,
What version of PS are you using ?
Thanks

**Comment by salvacal** [comment]
V. 1.7.6.5 but I checked also on V. 1.7.6.4 same issue. Check at https://rosabakehouse.com
Thank you

**Comment by florine2623** [comment]
When you are on a product page and want to connect, it actually redirects you to your account.

**Comment by sarahdib** [comment]
@salvacal it's not a bug but an improvement of the create account process.

@PrestaShop/prestashop-product-team what do you think about that ? when a user click on create account from a product page, after the registration the customer is redirected to the product page instead of the account page.

**Comment by MatShir** [comment]
We should do the same when we are on the checkout, it's a nice improvement. Your feedback is shared to the product team, in the meantime the project is open-source so anyone can contribute to your feature request.

**Comment by MatShir** [comment]
hi @salvacal,
Your feature request is still a nice improvement. I'm keeping it open :)
