### ISSUE TITLE
[Google Sitemap] Why does the module allow adding sites blocked by robots?

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18768]
#### Describe the bug 

In the settings of Prestashop's Google Sitemap module, there are options to add "service" pages (login, my-account, cart etc. etc.) to sitemap.

But these adresses are blocked from bots in robots.txt.

Google Search Console is then sending me emails and notifying me "Coverage problems", because they can't crawl these pages, even they are included in the sitemap.

These are the errors.
![error1](https://user-images.githubusercontent.com/6097524/80244495-483f0880-8669-11ea-83b1-9b8294416f3b.JPG)

The pages shown are credit-slip, my-account and address
![error2](https://user-images.githubusercontent.com/6097524/80244500-49703580-8669-11ea-8d8e-673a9b4caef2.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
By service pages, do you mean those that you can checkmark ?
![Capture d’écran 2020-04-23 à 18 23 03](https://user-images.githubusercontent.com/16019289/80123804-ae575d00-858f-11ea-98f0-dc961412da54.png)

And when you talk about addresses, are you talking about the URL of the pages ?

Could you send me a screenshot of the exact message Google Search Console is sending you ?

Thanks !

**Comment by Hlavtox** [comment]
@florine2623 Yes exactly these.

These are the errors.
![error1](https://user-images.githubusercontent.com/6097524/80244495-483f0880-8669-11ea-83b1-9b8294416f3b.JPG)

The pages shown are credit-slip, my-account and address
![error2](https://user-images.githubusercontent.com/6097524/80244500-49703580-8669-11ea-8d8e-673a9b4caef2.JPG)

**Comment by florine2623** [comment]
Hi @Hlavtox ,
Sorry for taking so long to answer. I'll ping our dev team, they will give you an answer.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
@Hlavtox is having issues with Google Sitemap, is there something we can do ?
Thanks a lot!

**Comment by Hlavtox** [comment]
@florine2623 No worries 🌹 It's few seconds to disable these pages from sitemap, but I think we can completely hide it from the list, if it's blocked anyway. What do you think?

**Comment by colinegin** [comment]
Yes you are right @Hlavtox , but what I don't understand is why these pages are blocked from bots in robots.txt.

**Comment by matks** [comment]
Hello, sorry for late answer

> @Hlavtox is having issues with Google Sitemap, is there something we can do ?

Well if there is a bug, it has been reproduced by @florine2623 ... then we must add it to the roadmap and plan to fix it 😄  I see no problem here. Just a bug, just some work to do.

@Hlavtox Is that something you could submit a PR for ? 😉
