### ISSUE TITLE
Wrong image path in the ColorPicker when using renderOptions in the module admin controller

### ISSUE THREAD

**Issue by ramtin2025** [PrestaShop/PrestaShop#18766]
#### Describe the bug

![image](https://user-images.githubusercontent.com/3217101/79991256-51906f80-84c7-11ea-90e9-8d2cb428f2ff.png)

"colocpicker" plugin has a default imageFolder that is not correct for AdminControllers. PrestaShop has overriden it in the "form.tpl" file but this has not been done in the "option.tpl" file.

#### Expected behavior
![image](https://user-images.githubusercontent.com/3217101/79992328-9537a900-84c8-11ea-9248-365aaaf5503f.png)

#### Steps to Reproduce

This problem becomes apparent when we using fields_options with at least one field of "color" type in the "adminControllers" or "moduleAdminControllers".

**Screenshots**
[image](https://user-images.githubusercontent.com/3217101/79991256-51906f80-84c7-11ea-90e9-8d2cb428f2ff.png)

#### Additional information

* PrestaShop version: 1.7.x (Tested in 1.7.6)
* PHP version: 7.2

**Comment by Matt75** [comment]
We use a field color like this in our [module cart banner](https://github.com/PrestaShopCorp/pscartbanner/) without this issue 🤔


https://github.com/PrestaShopCorp/pscartbanner/blob/2df81d6a88d923bdb86c76083bf1e940483858e9/controllers/admin/AdminPsCartBannerController.php#L46

**Comment by ramtin2025** [comment]
> We use a field color like this in our [module cart banner](https://github.com/PrestaShopCorp/pscartbanner/) without this issue 🤔
> 
> https://github.com/PrestaShopCorp/pscartbanner/blob/2df81d6a88d923bdb86c76083bf1e940483858e9/controllers/admin/AdminPsCartBannerController.php#L46

The default path of imageFolder (in the colorPicker) is: "../../../img/admin/" and it working well **just** in the root folder. If PrestaShop is in a different directory(e.g /shop/), it won't work.
