### ISSUE TITLE
BO - When creating a category, the simplified URL is not filled automatically when using multilang

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18763]
#### Describe the bug

Simplified URL is not filled automatically when using multilang.

#### Steps to Reproduce

1. Go to back office and add a second language
2. Go to Category and add a category (fill only the default language)
3. Save
4. Go to the new category and change the language to the second one 
5. See that the title is filled automatically but the Simplified URL is not 
6. See in FO when the second language is selected that there is only the id of the category 
<img width="311" alt="Capture d’écran 2020-04-22 à 13 16 00" src="https://user-images.githubusercontent.com/3034677/79975605-87b7fa00-849b-11ea-8848-a1f74651c30d.png">

With PrestaShop 1.7.6
<img width="330" alt="Capture d’écran 2020-04-22 à 13 16 08" src="https://user-images.githubusercontent.com/3034677/79975634-956d7f80-849b-11ea-9e23-89deb962df56.png">

**Screenshots**

PrestaShop 1.7.7
https://drive.google.com/file/d/12UqMtillJayZLwt-bXQG2UxXVNY_GWDP/view

PrestaShop 1.7.6
https://drive.google.com/file/d/15xtqPmgB9qxfKTFHt1Rkz-nRLT3_gt1Y/view

#### Additional information

* PrestaShop version: 1.7.7.
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #19063
