### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by emilieatelier** [PrestaShop/PrestaShop#18761]
![image](https://user-images.githubusercontent.com/63663739/79969389-b9c45e80-8491-11ea-972a-71ae3879085b.png)

I wanted to add another language in my shop (turn to English) and I have this problem.

Je voulais ajouter une langue suplementaire a mon magazyn (anglaise) mais cette erreur la se monter.

**Comment by florine2623** [comment]
Hi @emilieatelier ,
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by florine2623** [comment]
Also, enable debug mode to see what the specific error is please.

**Comment by emilieatelier** [comment]
@florine2623 I will try to do it

**Comment by emilieatelier** [comment]
![image](https://user-images.githubusercontent.com/63663739/80293947-78b79d00-8764-11ea-803c-2a26f1bfeb01.png)


![image](https://user-images.githubusercontent.com/63663739/80293953-8705b900-8764-11ea-9bd9-e5a9c593944c.png)


it s enought or you need more if yes what i have to click

**Comment by florine2623** [comment]
Hi @emilieatelier ,
Please do not open the Symfony toolbar. I just need to see the error on the said page.
But from your screenshot the HTTP Status in 200, meaning that there is no error.
Thanks!

**Comment by emilieatelier** [comment]
@florine2623 where i can find the Symfony bar? I have still this problem so their is a problem.

**Comment by florine2623** [comment]
@emilieatelier 
- just enable debug mode in Preferences
- go to the page that has error 500
- see the error
- screenshot

Thanks!

**Comment by emilieatelier** [comment]
![image](https://user-images.githubusercontent.com/63663739/82020436-5c36c280-9689-11ea-9ce0-444ab37e3b11.png)

voila

**Comment by florine2623** [comment]
It seems like you have files missing, in another issue you said that you upgraded your shop. That probably is why it's not working properly anymore.
Please check the log file of that upgrade and check for "fatal error".
Or send me the log file if you don't know how to read log files.
Thanks!

**Comment by emilieatelier** [comment]
@florine2623 where i cand find the log file of this upgrade?

**Comment by florine2623** [comment]
In your FTP in path : your_admin/autoupgrade/tmp/log.txt

**Comment by emilieatelier** [comment]
You know what, yesterday I contacted a company who will help me with my prestashop because their are different problem that i have to repair. I hope that they will help me
