### ISSUE TITLE
Friendly URLs - 404

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#18760]
Hello, 

I have few hundreds products. And for many of them i have error 404 on preview and on live shop.
Only with Friendly URLs enabled. With Friendly URLs disabled same products works fine.

Cant figure out why. Links look similar to products, that working fine. No clue what to do with it.
Copy not working product and give new ID doesnt change anything.

I.E 
404 error on enabled product: 
/strona-glowna/1317-super-koszulka-z-dlugim-rekawem-i-guziczkami-venerdi.html
No error - Friendly urls disabled:
/index.php?id_product=1317&rewrite=super-koszulka-z-dlugim-rekawem-i-guziczkami-venerdi&controller=product
No error on other products with similar links.
/25-vermont-7at8036.html

I tried to change name, reset SEO link, clear cache. No clue what to do. I dont want to disable Friendly URLs.

Any tips?

Prestashop version: 1.7.6.5

**Comment by GTriber** [comment]
Ok i did some digs. Around 15-20% of links are down with 404 error.

One product example:
Link with Friendly url enabled  - 404 error
strona-glowna/929-koszula-venerdi.html
Link with Friendly url disabled  - no error

In product SEO option / Friendly url window:
"koszula-venerdi" ( so name of the product ) Looks normal.

But i went to the shop website and searched for this specific product. Clicked and got 404 error but when i check the link i saw its different: 
strona-glowna/929-koszula-venerdi1583.html ( no idea whats "1583" )

Went to the panel again and in product SEO option / Friendly url window:
I changed "koszula-venerdi" to "koszula-venerdi1583" and all works.

Still dont know how to get rid of "1583" from link and whats that. Not a category / attributes etc ID.  {category:/}{id}-{rewrite}{id_product_attribute}.html

In all those products with 404 error, each have other number at the link end.

Searched for any module, that could cause it. No luck.  Like i said its in 15-20% of products.

**Comment by florine2623** [comment]
Hi @GTriber ,
I could not manage to reproduce your issue with PS 1.7.6.5.
Please try the following : 
- regenerate .htaccess (manually via FTP & by just saving SEO & URL in the BO)
- clear cache from BO and manually
- check for module that rewrite link with friendly URL
- if you check the URL Format, the URL for the product should be the following : 
```{category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html```

Please check and let me know!

**Comment by GTriber** [comment]
@florine2623 

Hello, 

Could duplicated products do such issue?

I have like 30+ products with same name. Because they are similar just other models.


In product SEO option / Friendly url window looks like that:
"koszula-venerdi"
But in link ID is ofc different.

Presta could automatically add numbers to all of those due to same  Friendly url name in SEO?

**Comment by florine2623** [comment]
_Could duplicated products do such issue ?_
No. I tried with duplicate products with same name, it works correctly.

_In product SEO option / Friendly url window looks like that:
"koszula-venerdi"
But in link ID is ofc different._
I don't understand what you mean, please specify.

_Presta could automatically add numbers to all of those due to same Friendly url name in SEO?_
No, I've tried andmy duplicate products show correctly.

What about what I said earlier, did you try everything ?

**Comment by GTriber** [comment]
I have attached SEO option of same product.

Product 1 name: Koszula meska Venerdi, so link should be: /927-koszula-meska-venerdi.html
But that link gave me 404.
If i add that strange number at the end /927-koszula-meska-venerdi1581.html it works

![Screenshot_2020-04-23 Produkt • Sklep sportowy Odyssey333](https://user-images.githubusercontent.com/60825638/80113132-3171b680-8582-11ea-9123-394f0d8d184d.png)

Product 2 name: Koszula meska Venerdi, so link should be: /933-koszula-meska-venerdi.html
But that link gave me 404.
If i add that strange number at the end /933-koszula-meska-venerdi1591.html it works

SEO Option - Friendly Url window in all those 404 error products shows "koszula-meska-venerdi"
If i add numbers to them, they are working. 

So if several products have same name "koszula-meska-venerdi" in SEO Friendly Url window , could make 404 error?

I did try wit clearing cache and other options.  It not a big deal i manage to add random numbers to links and they are working but it bother me why. As other products dont have such problems.

Thank you for your time :)

**Comment by florine2623** [comment]
Earlier you wrote that the product route is : ```{category:/}{id}-{rewrite}{id_product_attribute}```
Can you check for your product the ```id_product_attribute``` to see if it matches with what you have at the end of the URL ?

**Comment by GTriber** [comment]
Full link on the shop is: /933-koszula-meska-venerdi1591.html#/507-rozmiar-39_176_182_cm_
 So id_product_attribute would be /507-rozmiar-39_176_182_cm_

**Comment by florine2623** [comment]
Could you screenshot the FORMAT URL in SEO & URL ?

**Comment by GTriber** [comment]
hello, 

I have 968 product to check. After 5 pages ( around 100 products ) 20+ gives 404 error and need to add silly numbers. 

![Screenshot_2020-04-24 SEO URL • Sklep sportowy Odyssey](https://user-images.githubusercontent.com/60825638/80199049-2f126980-8621-11ea-9528-a7fd8981a1ef.png)

![Screenshot_2020-04-24 Wszystkie2](https://user-images.githubusercontent.com/60825638/80200033-561d6b00-8622-11ea-94f7-4e49e340cb4c.png)

**Comment by PierreRambaud** [comment]
@GTriber Can you provide us the exact list of product that are falling in 404?
Are all of them having a character in common, like the `'`?

**Comment by marionf** [comment]
Hello,
Since we had no news from you for more than 30 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!
