### ISSUE TITLE
404 error when editing product route pattern

### ISSUE THREAD

**Issue by EukaPS** [PrestaShop/PrestaShop#18765]
* Nginx / PHP-fpm (docker)
* Nginx conf file based on https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist
* PrestaShop v1.7.6.5 fresh install
* PHP version: 7.3
* Product with combinations

Everything is working well, but when I go to "SEO & Urls" and change the product route pattern to "{rewrite}-{id}{-:id_product_attribute}.html" - have the IDs at the end for SEO purpose - I got an 404 error (index.php?controller=404) when trying to access to a product page with combinations. It seems that the URL with the "id_product_attribute" is no more accessible and make a redirect. The URL with only the ID is still working. It also cause combinations selection issues on the product page.

What i've tried : 
- Disable / enable friendly URLs
- Delete product & regenerate combinations
- Multiple Nginx configurations

Not sure if it's an core PrestaShop issue, or related with nginx request routing not handled with the default configuration file. Any help will be appreciate !

Thanks, feel free to ask for more informations !

**Comment by florine2623** [comment]
Hi @EukaPS ,
Could you change PHP version to 7.2. PS 1.7.6.5 is available with 7.2.
You can have more info here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by EukaPS** [comment]
Hello, thanks for your reply.
I've changed for PHP 7.2 but the issue seems still here.
Here is how to reproduce :

1/ With the default product route pattern ({id}{-:id_product_attribute}-{rewrite}.html), everything is ok, this product (with combination) page is working :
http://mywebsite.local/fr/3-26-myproduct.html#/1-interior-red/30-exterior-blue

2/ When I switch the product route pattern to {rewrite}-{id}{-:id_product_attribute}.html - having the IDs at the end - the product page return an 404 error with the following URL :
http://mywebsite.local/fr/index.php?controller=404#/1-interior-red/30-exterior-blue

Turning the friendly URL to OFF allow me to view the product page without error, with the following URL : 
http://mywebsite.local/index.php?id_product=3&id_product_attribute=26&rewrite=my-product&controller=product&id_lang=1#/1-interior-red/30-exterior-blue

So I believe the issue is related to the default nginx configuration file not handling this specific case but can't figure how to adjust the rules. Any idea to go further on that issue ?

Thanks for your help !

**Comment by florine2623** [comment]
Thanks for the details !
I've tried what you said on Apache server : 
- default product route pattern ({id}{-:id_product_attribute}-{rewrite}.html) -> OK
- new product pattern {rewrite}-{id}{-:id_product_attribute}.html -> OK
- Friendly URL OFF -> OK

For nginx configuration, here's the file you can use to customize your server configuration : https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf

**Comment by EukaPS** [comment]
@florine2623 I've also used this nginx configuration file and the result is the same.

@khouloudbelguith As you added a bug flag, it seems related to the PS core and not the nginx configuration right ? Your seems to do your test with docker & nginx, any idea ?

Thanks for your help !

**Comment by khouloudbelguith** [comment]
Hi @EukaPS,

I just added the `Bug` label because the type of this issue is a bug and not a feature.
![image](https://user-images.githubusercontent.com/16067358/80191368-dee1da00-8615-11ea-9db8-ff526f395cf6.png)

Thanks :wink:

**Comment by EukaPS** [comment]
@khouloudbelguith Thank your for answering. I've seen that you do some of your tests on docker/nginx-fpm. Would it be possible for you to test - edit the product route pattern - just to let me know if you can reproduce or not with the default nginx configuration ? Thanks for helping, have a great day.

**Comment by khouloudbelguith** [comment]
Hi @EukaPS,

I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1yIQEODZmjoJetjcpnc2BV9wTDWIU-exT/view?usp=sharing
You have an issue with your configuration.
Here's my configuration
```
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6
        listen 443 ssl;

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name prestashop.com;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	# Add stdout logging
        error_log /var/log/nginx/error.log info;
        access_log /var/log/nginx/access.log;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location /1764/ {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files $uri $uri/ /1764/index.php?$args;
		# Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$1$2$32x.jpg last;
                rewrite ^/1764/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$1$2$3$42x.jpg last;
                rewrite ^/1764/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$1$2$3$4$52x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$62x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$72x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$82x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$92x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+2x.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$102x.jpg last;
                rewrite ^/1764/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;

                rewrite ^/1764/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/1764/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
		# AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/1764/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/1764/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
	}
	# Gzip Settings, convert all types.
        gzip on;
        gzip_vary on;
        gzip_proxied any;

        # Can be enhance to 5, but it can slow you server
        # gzip_comp_level    5;
        # gzip_min_length    256;

        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;

        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
	# Symfony controllers
        location /1764/admin-dev/ {                                  # [REQUIRED EDIT] the name of your admin directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /1764/admin-dev/index.php last;   # [REQUIRED EDIT] the name of your admin directory
            }
        }

        # Cloudflare / Max CDN fix
        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        # Do not save logs for these
        location = /1764/favicon.ico {
            log_not_found off;
            access_log off;
        }
        location = /1764/robots.txt {
            auth_basic off;
            allow all;
            log_not_found off;
            access_log off;
        }


	error_page 404 /1764/index.php?controller=404;

        location ^~ /sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }
        location ^~ /twitter.svg {
            alias /var/www/errors/twitter.svg;
            access_log off;
        }
        location ^~ /gitlab.svg {
            alias /var/www/errors/gitlab.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off;
    		deny all;
	}

	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

	# Source code directories
	location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor|var)/ {
    		deny all;
	}
	# Prevent injection of php files
    	location /1764/upload {
        	location ~ \.php$ {
            		deny all;
        	}
    	}
	location /1764/img {
        	location ~ \.php$ {
            		deny all;
        	}
    	}

}
```
I followed this [doc](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf)
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by EukaPS** [comment]
@khouloudbelguith Did your test used a product containing combination ? The product URL in your video does not seems to contain the "id_product_attribute" as in my case or in the URLs accessibles from https://xxx.demo.prestashop.com/en/. 

Also, have you tried to click on a color to switch to another variant ? The URL should change and contains this "id_product_attribute".

ex: 
- white : https://xxx.demo.prestashop.com/en/men/1-**1**-hummingbird-printed-t-shirt.html#/1-size-s/8-color-white
- Black : https://xxx.demo.prestashop.com/en/men/1-**2**-hummingbird-printed-t-shirt.html#/1-size-s/11-color-black

I continue to investigate, anyway, thanks for helping.

**Comment by EukaPS** [comment]
Hello @khouloudbelguith,

You were correct, I had an issue with my nginx configuration file. It's now fixed but i'm still facing an issue with friendly url & nginx + updated product pattern route. I realize that the test you did doesn't cover my root issue.

Could you please give me a last try on it : 
- Nginx / PHP-fpm (docker)
- Nginx conf file :

`server {
    listen   80; ## listen for ipv4; this line is default and implied
    listen   [::]:80 default ipv6only=on; ## listen for ipv6

    # SSL Ipv4 & v6
    # listen 443 ssl;
    # listen [::]:443 ssl;

    root /prestashop;
    index index.php index.html index.htm;

    # Make site accessible from http://localhost/
    server_name _;

    # Add stdout logging
    error_log /dev/stdout info;
    access_log /dev/stdout;

    # Redirect 404 errors to prestashop
    error_page 404 /index.php?controller=404;

    # Gzip Settings, convert all types.
    gzip on;
    gzip_vary on;
    gzip_proxied any;

    # Can be enhance to 5, but it can slow you server
    # gzip_comp_level    5;
    # gzip_min_length    256;

    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;

    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

   # Symfony controllers
    location /admin/ {                                  # [REQUIRED EDIT] the name of your admin directory
        if (!-e $request_filename) {
            rewrite ^/.*$ /admin/index.php last;   # [REQUIRED EDIT] the name of your admin directory
        }
    }

    # Cloudflare / Max CDN fix
    location ~* \.(eot|otf|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
    }

    # Do not save logs for these
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    # multilangual support
    rewrite ^/fr$ /fr/ redirect;
    rewrite ^/fr/(.*) /$1;

    rewrite ^/en$ /en/ redirect;
    rewrite ^/en/(.*) /$1;

    location / {

        # Redirect pretty urls to index.php
        try_files $uri $uri/ /index.php?$args;

        # Images
        rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
        rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
        rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
        rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;

        # AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
    }

    # File security
    # .htaccess .DS_Store .htpasswd etc
    location ~ /\. {
        deny all;
    }
    # Source code directories
    location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor)/ {
        deny all;
    }
    # Prevent exposing other sensitive files
    location ~ \.(yml|log|tpl|twig|sass)$ {
        deny all;
    }

    # Prevent injection of php files
    location /upload {
        location ~ \.php$ {
            deny all;
        }
    }
    location /img {
        location ~ \.php$ {
            deny all;
        }
    }

    location ~ \.php$ {
        # Verify that the file exists, redirect to index if not
        try_files $fastcgi_script_name /index.php$uri&$args;
        fastcgi_index  index.php;
        include fastcgi_params;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;

        fastcgi_pass unix:/var/run/php-fpm.sock;

        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
    }

}
`

PrestaShop v1.7.6.5 fresh install
- PHP version: 7.2
- Multilingual : fr & en
- Product with combinations
- SEO product route to "{rewrite}-{id}{-:id_product_attribute}.html"
- Add rules to support multilingual redirect

With this configuration, could you please, from a listing page, instead of clicking on the product name or thumbnail, hover the product and click on an attribute color to directly access to the dedicated variant page.

In your video record, we can see (as in my case now) that you access the product with the thumbnail or product name, and the product-name-1-1.html is > 301 > to product-name-1.html which happen with the default combination. So it's working with the default combination but not with the other ones.

Another test is to go to a product page where everything is working, click on an another color to change the variant ; The URL should switch to "product-name-4-22.html" ; Now refresh the page with this new URL and it should also 404 (= try to access directly to a variant url).

Everything is working great with the default product route, only having this issue when I switch the ID's at the end.

If you have a few minutes could you please have a look on that as a last try ?
Thanks for your help & have a great day !

**Comment by EukaPS** [comment]
@khouloudbelguith any chance you could have a look on this please ? The test you did doesn't cover the issue i'm reporting. Thanks for your help.

**Comment by DerekVerheijen** [comment]
@EukaPS 

I have got the same issue. Did you resolve this?
I got this when I try to upgrade version 1.7.5 to the latest version.

Doesn't work after upgrade:
{category:/}{rewrite}{-:ean13}-{id}{-:id_product_attribute}.html
Works after upgrade:
{category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html

I am also having 2 languages enabled.
