### ISSUE TITLE
Error 500 when I use Leoblog gestion

### ISSUE THREAD

**Issue by lascapade** [PrestaShop/PrestaShop#18773]
Hello,

I try to add a blog to my website, using leoblog gestion free version.

When I want to edit and save a category or a blog, I have this message : 

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

Here you have the message whe i'm in debug mode : 

![Capturebugblog](https://user-images.githubusercontent.com/64192974/80076089-f05eaf80-854b-11ea-8c5f-14598e617025.JPG)

I don't know anything about development so I don't know what to do.

Can you help me to solve this issue ?

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @lascapade ,
Please contact the developer of the module Leoblog directly.
PrestaShop GitHub is for reporting bug of the core solution as well as new features you'd like to see on PS.
Thanks.
