### ISSUE TITLE
Email deleting increase delete larger than 100

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#18771]
In backoffice if you want to delete emails the maximum amount you can select is 100 at a time

Can this be increase to steps like 500 - 1000 or all

This is very time consuming

**Comment by florine2623** [comment]
Hi @01park ,
There's an option on the top right corner where you can choose to "erase all" emails :
![Capture d’écran 2020-04-23 à 10 23 32](https://user-images.githubusercontent.com/16019289/80076483-8b578980-854c-11ea-842f-7da650660efe.png)

**Comment by 01park** [comment]
Hi,

Thanks for that. I noticed this option already.

My question maybe was not clear. This erase all doest not work for if you want to delete a certain date range.  In my case I had over 100.000 emails I wanted to delete. In the current situation I would need to process the function a 1000 times to delete all emails within that date range.
