### ISSUE TITLE
Module vendors conflicts with prestashop vendors

### ISSUE THREAD

**Issue by didacrios** [PrestaShop/PrestaShop#18770]
#### Describe the bug

I'm having  errors in Prestashop Backoffice throwed from a Symfony Vendor in a module. 

The module use a package that includes symfony http-foundation a version grater than the one installed in the prestashop installation (prestashop 1.7.4.1) 

It seams that a backoffice component is trying to use the http-foundation from my module vendor instead of the prestashop ones. 

If I remove the vendor from the module there is no errors

#### Expected behavior

Installing vendor from a module should not conflict with other modules nor main installation

#### Steps to Reproduce

1. Install `composer require endroid/qr-code` in a module
2. Login in backoffice
3. See error

#### Additional information

* PrestaShop version: 1.7.4.1
* PHP version: 7.2.25

**Comment by Matt75** [comment]
Did you try with composer options [prepend-autoloader](https://getcomposer.org/doc/06-config.md#prepend-autoloader) ? 


[Example with our module PrestaShop Checkout](https://github.com/PrestaShopCorp/ps_checkout/blob/329aa9f35700442e2725155892941fa6373f5655/composer.json#L9)

**Comment by didacrios** [comment]
Many thanks @Matt75 taking note of that

**Comment by didacrios** [comment]
Hi, I am reopening the issue because seems that some kind of conflict still happening with  some packages.

We are trying to use for example, doctrine in a new module, but installing the current version (2.9.3) seems that cause conflicts as  `doctrine/dbal` uses `symfony/console` when trying to access to the Prestashop Backoffice.

This is the error thrown:

```
(1/1) ClassNotFoundException
Attempted to load class "Event" from namespace "Symfony\Contracts\EventDispatcher".
Did you forget a "use" statement for e.g. "Symfony\Component\EventDispatcher\Event", "Symfony\Component\Workflow\Event\Event" or "Checkout\Models\Events\Event"?

in ConsoleEvent.php line 24 (from the symfony/console vendor from my module)
```

This is the module `composer.json` config and packages

```json
// modules/modulename/compose.json
    "config": {
      "preferred-install": "dist",
      "classmap-authoritative": true,
      "optimize-autoloader": true,
      "prepend-autoloader": false
    },
  "require": {
    "doctrine/orm": "2.9.3",
    "doctrine/cache": "^1.0"
  },
  "require-dev": {
    "wsdl2phpgenerator/wsdl2phpgenerator": "^3.4",
    "phpunit/phpunit": "^5.2"
  },
```

Could manage downgrading the `doctrine/dbal` version to the same as the Prestashop (2.5.14) but not with the `"prepend-autoloader": false` with that case.

Any ideas on that?

**Comment by Matt75** [comment]
Hi @didacrios 

You should constrains package version to same of your current PrestaShop version, if you known problematic dependencies of your package, try to require it with a restricted version into your composer.json

You can check [composer.json of PrestaShop Checkout module](https://github.com/PrestaShopCorp/ps_checkout/blob/master/composer.json) as example.
We restricted package version to same of PrestaShop composer.json ; for better backward compatibility with choose version 1.7.5 as reference but in your case check 1.7.4.1 : https://github.com/PrestaShop/PrestaShop/blob/3a30faca1d6c53396d2745362aff37f4104330de/composer.json#L19

You must always set `prepend-autoloader` to `false` in any case inside a PrestaShop module.

Also it recommend to set `platform` inside your `config` node.

**Comment by didacrios** [comment]
Thanks for the help @Matt75 ! So no way of having upgraded versions for vendors in the modules 👍🏼
