### ISSUE TITLE
[Wishlist 1.7] Add an item to a wishlist

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18779]
As a logged-in user I can add a product to the favorites from the product sheet or any other navigation page with product blocks in a wishlist.

**Specifications details :** https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.z7kd61kwmzqt

**Design :** https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412354283

**Comment by hibatallahAouadni** [comment]
Ping @NeOMakinG could you please specify this issue status, is it **`To Do`** or **`WIP`** ?
Thanks in advance!

**PS**: if there is a **PR** could you please link it and add the label **`PR available`** :sweat_smile: (I know I'm asking for a lot)

**Comment by NeOMakinG** [comment]
@hibatallahAouadni same, let's use https://github.com/PrestaShop/blockwishlist/pull/77
