### ISSUE TITLE
[Wishlist 1.7] Create a new wishlist

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18783]
**1. As a logged-in user, I can create a wishlist from the Wishlist area in My Account by clicking on New wishlist.
2. As a logged-in user, I can create a wishlist from the product page or from the product blocks (in the navigation pages).**

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.z6spb3cbd3dd

Desktop design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412699587
Mobile design : https://projects.invisionapp.com/d/main?origin=v7#/console/19575472/412358493/preview?scrollOffset=2497

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta

**Comment by sibiant** [comment]
Pretsshop version : 1.7.8.6
Wishlist block : v2.1.2 (https://addons.prestashop.com/en/undownloadable/9131-wishlist-block.html)

Wishlist block installed , when click on the icon on the product image showing Product added. But where I can see the my wishlist products. I checked the account page it is not there.

How to show wish list link in header ?
