### ISSUE TITLE
[Wishlist 1.7] Modify and delete a wishlist

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18784]
**As a logged-in user, I can edit a wishlist that I have created.**

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.ko7bcxp6j38w

Desktop design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412699587
Mobile design : https://projects.invisionapp.com/d/main?origin=v7#/console/19575472/412358493/preview?scrollOffset=2528

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta
