### ISSUE TITLE
[Wishlist 1.7] Edit and delete a favorite item

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18781]
As a logged-in user, I can edit and delete a favourite product.

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.9cu7p4o5o4x5

Desktop design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/413193096
Mobile design : https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/19575472?scrollOffset=2901

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta
