### ISSUE TITLE
[Wishlist 1.7] Add a favorite product to cart

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18782]
**As a logged-in user, I can add a favourite product to the shopping cart.**

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.filtgrmbe6dn

Desktop design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/413193096
Mobile design : https://projects.invisionapp.com/d/main?origin=v7#/console/19575472/413195192/preview?scrollOffset=3195

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta
