### ISSUE TITLE
[Wishlist 1.7] Configure the module and view statistics

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18786]
**1. As a merchant I can change the wordings.
2. As a merchant I can view statistics**

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.dhytw6kh9hlx

Desktop design : 
https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412284846
https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412284844

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta

**Comment by liviu-v** [comment]
I can not find anywhere how can I translate this module in other language, can any one to help with this?
