### ISSUE TITLE
[Wishlist 1.7] See my saved favorites items 

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18780]
1. As a logged-in user I can view and sort my favourite products.
2. As a logged-in user I can see how many of my favourite products are in a wishlist.

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.3uwqeomy9upw

Design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412699586

**Comment by hibatallahAouadni** [comment]
Ping @NeOMakinG could you please specify this issue status, is it **`To Do`** or **`WIP`** ?
Thanks in advance!

**PS**: if there is a **PR** could you please link it and add the label **`PR available`** :sweat_smile: (i'm really sorry :confused: )

**Comment by NeOMakinG** [comment]
Hey @hibatallahAouadni 

It's been done months ago, inside : https://github.com/PrestaShop/blockwishlist/pull/77

I won't search for every PRs, let's link it to the merge one ^^
