### ISSUE TITLE
[Wishlist 1.7] Share a wishlist

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#18785]
1. As a logged-in user, I can get a link to share a list
2. As a user of the site (connected or not), I can open the wishlist of another user in a dedicated page/with a public url. 

Specifications details : https://docs.google.com/document/d/1VVvudmIFIgc2pRXdy5eES9J9XRjJCQSWsZ2RFgJeGkM/edit#heading=h.mj2i3cdzu0qs

Desktop design : https://projects.invisionapp.com/share/43WEL7XMU2W#/screens/412702154
Mobile design : https://projects.invisionapp.com/d/main?origin=v7#/console/19575472/412358494/preview?scrollOffset=2528

**Comment by hibatallahAouadni** [comment]
PR fixes this issue: https://github.com/PrestaShop/blockwishlist/pull/77
Thanks to @NeOMakinG & @lolath-presta
