### ISSUE TITLE
Mail settings

### ISSUE THREAD

**Issue by Leous88** [PrestaShop/PrestaShop#18793]
original text is in spanish - translated
Hello, it seems awkward to me that all the mail configuration part is always visible from the customer service panel, these options should be in store configuration or another. since if only the personnel who see customer service activated this profile, without administration or modification of the store's own structure, this section is still there, it cannot be hidden. I think it should be modified.

**Comment by florine2623** [comment]
Hi @Leous88 ,
What do you mean the mail config part is always visible ? Do you mean in the Back-office or in the shop directly ?
What version of PrestaShop are you using ?
Thanks!

**Comment by Leous88** [comment]
in back office

[image: image.png]
Leonardo González Muñoz.

Ingeniero en Administración de Empresas.

Master Business Administration (cursando).

CEO | Profesional Independiente  | Asesor Tributario y Financiero.
+56 9 3363 2861 <+56+9+3363+2861>
leonardog698@gmail.com
Talca, Chile


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
26/04/20
22:54:13

**Comment by florine2623** [comment]
Hi @Leous88 ,
Please answer via GitHub.
If you have sent an attachment I can't see it on GitHub. Please resend it.

**Comment by Leous88** [comment]
![Captura de pantalla 2020-04-26 22 53 53](https://user-images.githubusercontent.com/44386425/80984907-7ad0ca00-8dfc-11ea-934c-9e7abc71b527.png)

**Comment by florine2623** [comment]
Hi @Leous88 ,
Thank you for answering !
So what exactly is the issue here ? You don't want the email config to be shown in the Customer Service page ? Where would you see that page ?

**Comment by Leous88** [comment]
in configuration for example. since the logical thing is that in the group
of donfiguracion are all the configurations. furthermore, the restrictions
can be used in a better way.
At the current location, ANY employee can change or view the information,
creating conflicts for the store owner.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/05/20
12:08:56

**Comment by sarahdib** [comment]
@Leous88 
You can create employee with restriction.

First you create a profil : http://doc.prestashop.com/display/PS17/Profiles
Second you can add permission : http://doc.prestashop.com/display/PS17/Permissions
and then create an employee with his new profil : http://doc.prestashop.com/display/PS17/Employees

If you need more help to create or configure an employee, please contact our merchant success team.
