### ISSUE TITLE
Order confirmation email - Missing product list

### ISSUE THREAD

**Issue by Nesta78** [PrestaShop/PrestaShop#18790]
In 1.7.6.5, when the customer receive order confirmation by email, there is no product list details.

<img width="697" alt="Capture d’écran 2020-04-23 à 15 59 29" src="https://user-images.githubusercontent.com/64215260/80120073-c7114400-858a-11ea-90af-ed5b05c5f7df.png">

Any tips ?
Thank you !

Prestashop version: 1.7.6.5

**Comment by florine2623** [comment]
Hi @Nesta78 !
What version of PHP are you using ?
Do you use any module regarding the products/emails ?
Thanks!

**Comment by Nesta78** [comment]
Hi and thank you for the answer !
I'm using 7.2 php. version. And it's a fresh installation. I'm using a few modules, but none are related to products or emails I think.
So it's not a known bug ? 
Thank you :)

**Comment by florine2623** [comment]
I've tried with a fresh install of PS 1.7.6.5 and PHP 7.2., it works correctly : 
![Capture d’écran 2020-04-24 à 11 06 51](https://user-images.githubusercontent.com/16019289/80195128-b78e0b80-861b-11ea-831c-9a0d69509332.png)

Can you check if you have the file ```/mails/your_language/order_conf_product_list.tpl``` via FTP ?

**Comment by Nesta78** [comment]
Ok thank you, so it's a problem with my installation ...
Here are files I've got.

<img width="1185" alt="Capture d’écran 2020-04-24 à 11 23 49" src="https://user-images.githubusercontent.com/64215260/80196897-3e43e800-861e-11ea-95bb-ae93b485bb37.png">

<img width="1185" alt="Capture d’écran 2020-04-24 à 11 24 06" src="https://user-images.githubusercontent.com/64215260/80196923-44d25f80-861e-11ea-8e57-9e266324dffe.png">

Thank you for your help, I appreciate it very much :)

**Comment by florine2623** [comment]
Can you try adding these files in your folder ?
[Archive.zip](https://github.com/PrestaShop/PrestaShop/files/4527914/Archive.zip)

Let me know if it works.

**Comment by Nesta78** [comment]
Into this folder ?

<img width="979" alt="Capture d’écran 2020-04-24 à 11 31 51" src="https://user-images.githubusercontent.com/64215260/80197666-3afd2c00-861f-11ea-969c-c5719d527eb4.png">

Even if there is no other .tpl in the folder ?

**Comment by florine2623** [comment]
Yes !

**Comment by Nesta78** [comment]
You are the best !
It's working now :)

A huge thank you to you !

**Comment by Nesta78** [comment]
Do you know if it's possible to add product image in the email ?

**Comment by florine2623** [comment]
You're welcome !

It is possible, but you will have to contact a PrestaShop agency of PrestaShop support so they can help you !
https://www.prestashop.com/en/experts
https://addons.prestashop.com/en/388-support

Thanks !

**Comment by 01park** [comment]
Hi,

I have the same issue, I added the two files to the mail/language/ 

But not changed. What im I doing wrong?
