### ISSUE TITLE
Can't install theme in dev but use it in prod

### ISSUE THREAD

**Issue by mcube27** [PrestaShop/PrestaShop#18795]
#### Describe the bug

I use a theme in production and in order to modify its assets for my child theme I tried to install it in dev mode on my computer.

Prestashop works fine with classic theme, the theme can be uploaded with the zip.

When I choose to use the theme, it does not load and show a connection reset page.

If I reload it, it show this :
![image](https://user-images.githubusercontent.com/10844608/80181799-d386b280-8605-11ea-85b5-542047b6a080.png)

I don't know what is wrong...

* PrestaShop version: 1.7.6.5 (git co 1.7.6.5 after git clone)
* PHP version: 7.2.4

**Comment by florine2623** [comment]
Hi @mcube27 ,
I could not manage to reproduce your issue.
When I do it, it works fine for theme classic and PS 1.7.6.5.
What did you change in the theme ? Is the theme compatible with your PS version ?

**Comment by mcube27** [comment]
The issue came from my apache config. Somehow I had to add 
`<IfModule mpm_winnt_module>
   ThreadStackSize 8888888
</IfModule>`
And then it worked like a charm. 
Thank you for your help and sorry to bother you with non related bug !
