### ISSUE TITLE
Use placeholders in strings to improve the translation consistency

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#18809]
#### Is your feature request related to a problem?

Some strings currently contain other strings in it, like _Your data is cached in order to sort it and filter it. You can refresh the cache by clicking on the "Refresh cache" button._. It is not ideal because:

1/ the string in the wording might change,
2/ it is therefore subject to inconsistency, especially in the translation.

So, for the 1.7, here are the non-exhaustive list of wordings I've found.

#### Describe the solution you'd like:

- [x] _There is a huge quantity of data, so each connection corresponding to a referrer is indexed. You can also refresh this index by clicking the "[1]" button. This process may take a while, and it's only needed if you modified or added a referrer, or if you want changes to be retroactive._ in _Admin.Shopparameters.Help_

[1] = _Refresh index_ in _Admin.Shopparameters.Feature_
 

- [x] _Your data is cached in order to sort it and filter it. You can refresh the cache by clicking on the "[1]" button._ in Admin.Shopparameters.Help

[1] = _Refresh cache_ in _Admin.Shopparameters.Feature_

- [x] _You can also decide to move your images to the new storage system. In this case, click on the "[1]" button below. Please be patient. This can take several minutes._ in Admin.Design.Notification
 
[1] = _Move images_ in _Admin.Design.Feature_

- [x] _Step 1: On the left side, select the attributes you want to use (Hold down the "Ctrl" key on your keyboard and validate by clicking on "[1]")_ in _messages_

[1] = _Add_ in _messages_? _Admin.Actions_?

- [x] _If there is no existing module for your carrier, then you can register that carrier by hand using the information that it can provide you: shipping rates, regional zones, size and weight limits, etc. Click on the "[1]" button below to open the Carrier Wizard, which will help you register a new carrier in a few steps._ in _Admin.Shipping.Help_

[1] = _Add new carrier_ in _Admin.Shipping.Feature_

- [x] _This will copy the images too. If you wish to proceed, click "[1]". If not, click "[2]"._ in _Admin.Catalog.Notification_

[1] = _Yes_ in _Admin.Global_?
[2] = _No_ in _Admin.Global_?
 

- [x] _This is the code users should enter to apply the voucher to a cart. Either create your own code or generate one by clicking on "[1]"._ in _Admin.Catalog.Help_

[1] = _Generate_ in _Admin.Actions_?

 
- [x] _Please click on "[1]"._ in _messages_

[1] = _Generate these combinations_ in _messages_
 

- [x] _You can review this credit slip and download your invoice from the <a href="{history_url}">"[1]"</a> section of your account by clicking <a href="{my_account_url}">"[2]"</a> on our shop._ in _Emails.Body_

[1] = _My credit slips_ in _Shop.Theme.Customeraccount_
[2] = _My account_ in _Shop.Navigation_

- [x] _Not all images have been moved. The server timed out before finishing. Click on "[1]" again to resume the moving process._ in _Admin.Design.Notification_

[1] = _Move images_ in _Admin.Design.Feature_
 

- [x] _Be careful! Please check your theme in an RTL language before generating the RTL stylesheet: your theme could be already adapted to RTL.\nOnce you click on "[1]", any RTL-specific file that you might have added to your theme might be deleted by the created stylesheet._ in _Admin.Design.Help_
 
[1] = _Adapt to RTL_ cannot be found, cf. screenshot

![Capture d’écran 2020-04-24 à 15 50 52](https://user-images.githubusercontent.com/32565890/80220044-93462500-8643-11ea-8ebb-3ec4104699b0.png)

➡️ pas trouvé

- [x] _Click on the "[1]" button and select the backup file from your hard drive._ in _Admin.Advparameters.Help_

[1] = _Browse_ in _Admin.Actions_

➡️ pas trouvé

- [x] _Click on the "[1]" button and please wait patiently for the import process to conclude. This may take several minutes._ in _Admin.Advparameters.Help_

[1] = _Go_? - there is no _Go_ button!

➡️ pas trouvé
 

- [x] _Be careful! Please check your theme in an RTL language before generating the RTL stylesheet: your theme could be already adapted to RTL.
Once you click on "[1]", any RTL-specific file that you might have added to your theme might be deleted by the created stylesheet._ in _Admin.Design.Help_
 
[1] = _Adapt to RTL_ cannot be found, cf. screenshot

![Capture d’écran 2020-04-24 à 15 50 52](https://user-images.githubusercontent.com/32565890/80220044-93462500-8643-11ea-8ebb-3ec4104699b0.png)

➡️ pas trouvé

- [x] _You are editing this page for a specific shop or group. Click "[1]" to check all fields, "[2]" to uncheck all._ in _Admin.Design.Help_ 

[1] = _Yes_ in _Admin.Global_?
[2] = _No_ in _Admin.Global_?
 

- [x] _You can review your order and download your invoice from the <a href="{history_url}">"[1]"</a> section of your customer account by clicking <a href="{my_account_url}">"My account"</a> on our shop._ in _Emails.Body_

[1] = _Order history_ in _Shop.Theme.Customeraccount_? _Shop.Navigation_?
[2] = _My account_ in _Shop.Navigation_
 

- [x] _Click "[1]"._ in _Admin.Advparameters.Help_

[1] = _Add New_ in _Admin.Actions_

- [x] _Fill in the fields and click "[1]"._ in _Admin.Advparameters.Help_

[1] = _Save_ in _Admin.Actions_? _Admin.Global_? _messages_?
 

- [x] _You can then view the query results by clicking on the [1] action in the dropdown menu_ in _Admin.Advparameters.Help_

[1] = _Edit_ in _Admin.Actions_? _Admin.Global_? _messages_?

- [x] _You can also export the query results as a CSV file by clicking on the [1] button_ in _Admin.Advparameters.Help_

[1] = _Export_ in _Admin.Actions_? _messages_?

- [x] _To add combinations, you first need to create proper attributes and values in [1]Attributes & Features[/1]. <br> When done, you may enter the wanted attributes (like "size" or "color") and their respective values ("XS", "red", "all", etc.) in the field below; or simply select them from the right column. Then click on "[1]": it will automatically create all the combinations for you!_ in _Admin.Catalog.Help_

[1] = _Generate_ in _Admin.Actions_

➡️ pas trouvé

- [x] _You can specify product reference(s) for each associated supplier. Click "[1]" after changing selected suppliers to display the associated product references._ in _Admin.Catalog.Help_

[1] = _Save_ in _Admin.Actions_? _Admin.Global_? _messages_?

➡️ pas trouvé

 
- [x] _If your server stops before the process ends, you can resume the indexing by clicking "[1]"._ in _Admin.Shopparameters.Feature_

[1] = _Add missing products to the index_ in _Admin.Shopparameters.Feature_

- [x] _Click on "[1]" to index the category on your shop_. in _Admin.Catalog.Help_

[1] = _Displayed_ in _Admin.Global_

➡️ pas trouvé

- [x] _Oops! Please correct the item(s) below, and then click "Refresh information" to test the compatibility of your new system._ in _Install_

[1] = _Refresh information_? - there is no _Refresh information_ button!

- [x] _Oops! Please correct the item(s) below, and then click "[1]" to test the compatibility of your new system._ in _Install_
 
[1] = _Refresh_ in _Install_

- [x] _You are editing this page for a specific shop or group. Click "[1]" to check all fields, "[2]" to uncheck all._ in _messages_

[1] = _yes_ in _messages_?
[2] = _no_ in _messages_?
 

- [x] _Your theme has been correctly reset to its default settings. You may want to regenerate your images. See the Improve > Design > Images Settings screen for the '[1]' button._ in _Admin.Design.Notification_

[1] = _Regenerate thumbnails_ in _Admin.Design.Feature

➡️ pas trouvé

- [x] _Display or hide the "[1]" button on category pages for products that have attributes forcing customers to see product details._ in _Admin.Shopparameters.Help_

[1] = _Add to cart_ in _Shop.Theme.Actions_?

➡️ pas trouvé

- [x] _By default, the [1] button is hidden when a product is unavailable. You can choose to have it displayed in all cases._ in _Admin.Shopparameters.Help_

[1] = _Add to cart_ in _Shop.Theme.Actions_?

➡️ pas trouvé

- [x] _Display the "[1]" button when a product has attributes_ in _Admin.Shopparameters.Feature_

[1] = _Add to cart_ in _Shop.Theme.Actions_?

➡️ pas trouvé

# Modules

## ps_legalcompliance

- [ ] _The order will only be confirmed when you click on the button '[1]' at the end of the checkout!_ in _Modules.Legalcompliance.Shop_

[1] = _Order with an obligation to pay_ in _Shop.Theme.Actions_ or _Shop.Theme.Checkout_

## ps_cleaner

- [ ] _Please read the disclaimer and click "[1]" above_ in _Modules.Pscleaner.Admin_

[1] = _Yes_ in _Admin.Global_?

**Comment by LouiseBonnard** [comment]
Hey guys, I could not find some strings mentioned in the issue description. I noted them as 'pas trouvé', aha, can I let you check?

**Comment by Progi1984** [comment]
Fixed by #18902
