### ISSUE TITLE
New invoice not displayed in the "Add new cart rule" block if you don't refresh the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18805]
#### Describe the bug

New invoice is not displayed in the "Add new cart rule" block if you don't refresh the page

#### Expected behavior

Display new invoice in the "Add new cart rule" block without having to refresh the page, as in legacy

#### Steps to Reproduce

1. Go to orders > orders
2. Click on View for an order in "payment accepted" status
3. Add a product to the order and select "Create a new invoice"
4. Add a new discount
5. The new invoice not displayed in the "Add new cart rule" block, you have to refresh the page

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/80212870-925bc600-8638-11ea-9693-32f456361083.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #18812
