### ISSUE TITLE
Add widget interface to be able to move product comment grade (stars) to another position

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#18817]
I develop themes and I would like to move product comment grade (stars) to better position (for example below heading).  At the moment it's not possible without moving whole hook "DisplayProductAdditionalInfo" (which also includes social sharing and another modules may use it).
It would be great if the productcomments module supports widget interface, so that developers can move it to another place in theme easily.

**Comment by PierreRambaud** [comment]
Hi @web-plus and thanks for your suggestion.

Ping @PrestaShop/prestashop-product-team, what do you think?
FYI, we already do that for the faceted search module, it's a good improvement.

**Comment by LouiseBonnard** [comment]
Sounds good, @web-plus, thanks for this suggestion! What is the difference between using a hook and a widget interface?

**Comment by PierreRambaud** [comment]
@LouiseBonnard Everything is in the devdoc: https://devdocs.prestashop.com/1.7/modules/concepts/widgets/

**Comment by web-plus** [comment]
> Sounds good, @web-plus, thanks for this suggestion! What is the difference between using a hook and a widget interface?

With widget interface, I can move this particular module in theme where I want, without moving the whole DisplayProductAdditionalInfo hook (which includes other modules so it's often not suitable).

**Comment by LouiseBonnard** [comment]
Great, thank you very much for your replies, it is definitely a nice improvement. It might be worth extending it to other modules like the social media share buttons module, for instance. I'll check that!

**Comment by web-plus** [comment]
> Great, thank you very much for your replies, it is definitely a nice improvement. It might be worth extending it to other modules like the social media share buttons module, for instance. I'll check that!

Happy to hear that! Widget interface is very useful feature in 1.7, makes theme developers life easier, so I'm sure many other developers will appreciate that too.
