### ISSUE TITLE
Filter products by the stock of matched variants, not just any of them

### ISSUE THREAD

**Issue by darioesposito** [PrestaShop/PrestaShop#18815]
Hi,

i have prestashop 1.7.6.3, as title topic suggest when i choose a filter they show all the product even the unavialable, i found the topic here and on other website but the solution is from a previous version of prestashop. 

Also i have the file but the code it's totally different so i can't fix this with provided solution.

Any help or suggestion? 

Thank you

**Comment by PierreRambaud** [comment]
Hi @darioesposito,

Could you please redo your issue's content with the following template https://github.com/PrestaShop/PrestaShop/issues/new?template=feature_request.md 
or if you think it's a bug https://github.com/PrestaShop/PrestaShop/issues/new?template=bug_report.md

Kind regards

**Comment by marionf** [comment]
Hello,
Since we had no news from you for more than 30 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!
