### ISSUE TITLE
HelperForm in AdminController :: Back value in helper form tpl_vars['back'] is not correctly calculated

### ISSUE THREAD

**Issue by manudas** [PrestaShop/PrestaShop#18821]
https://github.com/PrestaShop/PrestaShop/blob/5fe8128a3b28fc0a85d15d633ed3ac3a271a317e/classes/controller/AdminController.php#L2593

Hello, I came across this and thought that you may want to fix it:

Instead of 
`Tools::safeOutput(Tools::getValue(self::$currentIndex . '&token=' . $this->token));`

which return an empty string, it should be just 
`Tools::safeOutput(self::$currentIndex . '&token=' . $this->token);`

Please feel free to tell me if I'm wrong or if I can help in something else
Thank you

**Comment by PierreRambaud** [comment]
Hi @manudas and thanks for your report.

Could you please create a pull request with your fix? We will be glad to review, test and merge it :)

**Comment by manudas** [comment]
Hey @PierreRambaud
As per your request, I sent a Pull Request. This is my first PR to the Prestashop community. Sorry if for whatever reason I did something wrong.

I hope it will be of help for the community.
Regards
