### ISSUE TITLE
Tutorial demonstration has platform incompatibility

### ISSUE THREAD

**Issue by jyothi0093** [PrestaShop/PrestaShop#18829]
tutorial demonstration is not compatible with differ browser platforms.
Browser -chrome
![Screenshot from 2020-04-27 11-22-19](https://user-images.githubusercontent.com/63452509/80338236-6ed38e00-8879-11ea-9c02-8ff67a35ddd1.png)

* PrestaShop version: 1.7.7.0
* PHP version:  7.2.30-

**Comment by PierreRambaud** [comment]
Hi @jyothi0093 and thanks for your report.

I manage to reproduce the problem when using a resolution under 1600 in width.

@PrestaShop/prestashop-product-team What do you think?

**Comment by jyothi0093** [comment]
> Hi @jyothi0093 and thanks for your report.
> 
> I manage to reproduce the problem when using a resolution under 1600 in width.
> 
> @PrestaShop/prestashop-product-team What do you think?

 i would suggest using media queries as manually setting the resolution would not resolve the problem if its accessed from different devices.

**Comment by sam-pires** [comment]
Hello,
What is the problem exactly?
Is it only a responsive problem depending on the width or are there any other problems?

**Comment by sam-pires** [comment]
As we haven't had any more info to reproduce or identify the problem in details we are closing the issue.

Thanks
