### ISSUE TITLE
New Widget

### ISSUE THREAD

**Issue by MichaelJunior1** [PrestaShop/PrestaShop#18827]
<!--
Hello, I'm Mike.When i changed the code from Popular Posts to Older Posts is showing me this..... 

The new widget with id "<b>Older Posts</b>" has an invalid type: <b>OlderPosts</b> Error 500

**Comment by PierreRambaud** [comment]
Hi @MichaelJunior1 
Since your issue does not have any content, and title, I close it.
Feel free to reopen if you can provide us information :)
