### ISSUE TITLE
Symfony total disappointment!

### ISSUE THREAD

**Issue by wdammak** [PrestaShop/PrestaShop#18826]
Thousands and thousands of issues and bugs are linked to the cache and therefore to Symfony! On a blank installation, it takes a 50th error just to set up another theme and a few modules! 
by deactivating the cache mode to be able to know the errors the site becomes a gas bomb! with super slow loading and each time you have to manually delete the cache/var/dev!
I ask the team to study this technological choice which at no time encouraged me to prefer ps1.7 to ps1.6!
I ask if ps1.8 will not return to pretty or another more stable and lighter technology! there really it's heavy this Symfony !!!!

**Comment by matks** [comment]
Hi @wdammak we will keep Symfony for PS 1.8 as we believe it's the future.

Actually Symfony seems to be the choice for most major projects which want to use a very reliable framework: [you can see](https://symfony.com/projects) that Drupal, Joomla!, Magento, eZ Platform and Shopware have chosen the same path.

Don't let bugs and issues blind you: Symfony is a must-have in PHP and has probably saved PHP from dying in front of other backend technologies like Python or NodeJS.

You might want to read our [series of article](https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-1-current-architecture/) explaining the issues happening over the years for 1.7 and the path we are following to solve them for good. It also explains what we aim for in the future (Symfony for backend and Javascript - probably Vue.js - for frontend).

PS 1.7 can become better by working together on it. PrestaShop is an open source, community project. If you find that it does not fit your needs now, then you can _invest_ into having it fixed. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by PierreRambaud** [comment]
Hi @wdammak 

As @matks said we wil not remove Symfony from the project.
I'm closing this issue.

Kind regards

**Comment by wdammak** [comment]
@matks 
you ignore Laravel?!

**Comment by matks** [comment]
> @matks
> you ignore Laravel?!

I dont think switching from Symfony to Laravel would do any good to PrestaShop. In term of features, quality and popularity they are equal. Moreover Laravel is built on top of Symfony components so if you think Laravel is good, you consequently think Symfony is good.

Moving from PrestaShop legacy homemade framework to Symfony framework is a huge work that was started 3 years ago and is painful as any similar changes. Changing framework is always a painful move although it brings huge benefits.
If we dismiss Symfony for Laravel now we must restart from zero. Do you want us to go back to 3 years ago and do the work again ? 😉
