### ISSUE TITLE
BO - When creating an order, the status selected by default in the drop-down is canceled

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18831]
**EDIT:**
#### Describe the bug

When the user chooses a payment method, the create order page assigns an automatic status defined by a hard-coded list in the code. When the payment module was not associated with a status in the create order page, the status "payment accepted" is assigned by default.

#### Expected behaviour

To remove the hard-coded list associating the status and payment method.
The default value of the payment method in the droplist is "Choose a payment method" or empty value (wording still to be defined). When the user selects a payment method, it does not affect the list. 
The default value of the status droplist is "Choose a status" or empty value (wording still to be defined). 
So to create the order, the user has to select an order status. An error message is thrown if the user has not chosen a status or payment method.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. Go to BO->Order
2. Click on Create order
3. Add a product
4. Scroll down to the bottom of the page
5. See the status selected by default

**Screenshots**
Legacy 
<img width="1038" alt="Capture d’écran 2020-04-27 à 10 36 30" src="https://user-images.githubusercontent.com/3034677/80352114-ae977700-8873-11ea-932f-59c36156400b.png">

Migrated
<img width="1042" alt="Capture d’écran 2020-04-27 à 10 37 08" src="https://user-images.githubusercontent.com/3034677/80352137-b820df00-8873-11ea-9107-b1d16c84f900.png">

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #18875
