### ISSUE TITLE
Ecotax is displayed tax excl instead of tax incl in FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18835]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1) I enable ecotax in international > VAT
2) I define a tax for my ecotax of 20%
![Capture du 2018-03-15 16-05-05](https://user-images.githubusercontent.com/13449658/57296604-a7f57a00-70cd-11e9-8ad8-e0ea447b0693.png)

3) I set ecotax = 1€ tax incl
The price tax excl is not well recalculated (issue https://github.com/PrestaShop/PrestaShop/issues/9855)
![Sans titre2](https://user-images.githubusercontent.com/13449658/62777849-fcced500-baae-11e9-8214-2190a45183c7.png)

4) I save my product, reload the page ==> the ecotax = amount Tax Excl. The VAT on the ecotax has disappear in the nature. And the product price tax incl is also wrong (should be 12€): issue [#10026](https://github.com/PrestaShop/PrestaShop/issues/10026)
![Capture du 2018-03-15 16-40-38](https://user-images.githubusercontent.com/13449658/57296620-b0e64b80-70cd-11e9-9774-7c7df8e4eb12.png)

5) The amount displayed on FO is not correct. It displays the Ecotax Tax Excl (0.83) whereas it should display Tax Incl (1€)
 ![Capture du 2018-03-15 16-43-03](https://user-images.githubusercontent.com/13449658/57296633-bb084a00-70cd-11e9-9e8c-65fea3979ab0.png)

#### Additional information

* PrestaShop version: 1.7.5, 1.7.6, 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
Fix on BO is done in https://github.com/PrestaShop/PrestaShop/pull/18580

Fix on FO is not done yet

**Comment by jocel1** [comment]
@matks do you plan to change the computed value in the ProductLazyArray or introduce a new variable (like value_with_tax ?) in the getEcotax() function ? (+ change the product-prices.tpl to use it)

**Comment by matks** [comment]
> @matks do you plan to change the computed value in the ProductLazyArray or introduce a new variable (like value_with_tax ?) in the getEcotax() function ? (+ change the product-prices.tpl to use it)

I planned to change the value but if you ask, I guess it's because, as a theme/module developer you'd like to be choose what you want to display ?

So maybe a new variable would be nice indeed 😄

**Comment by jocel1** [comment]
Yes I'm thinking about backward compact where I guess a few themes already handle this issue :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20499 on FO
