### ISSUE TITLE
token error while adding related product

### ISSUE THREAD

**Issue by servidiomarco** [PrestaShop/PrestaShop#18839]
#### Describe the bug

Hi, 
when creating a new product and adding its related products as Products Editor (all permission for Products are granted) I get a token error.
when I try to do the same logged in as SuperAdmin everything works fine. 
#### Expected behavior

related products added on product creation.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.2.4
* PHP version: 7.1

**Comment by PierreRambaud** [comment]
Hi @servidiomarco and thanks for your report.
Can you give us more information, what do you mean by "Products Editor", is it only a profile name?
If yes, could you add screenshots of permissions your profile has exactly?

kind regards

**Comment by servidiomarco** [comment]
hi @PierreRambaud, yes it is a profile name - you can see the permission in the following screenshot
<img width="414" alt="Screen Shot 2020-04-27 at 17 55 40" src="https://user-images.githubusercontent.com/21959141/80399074-867a3900-88b0-11ea-9da1-8f6d60c02c23.png">

**Comment by PierreRambaud** [comment]
I did not manage to reproduce the error as you can  see on my screenshot, I add a new product and a related product to its.
![image](https://user-images.githubusercontent.com/1462701/80465686-bf132480-893b-11ea-8dbc-ad891abd97f9.png)

If  you're using custom modules, try to disable them, or add permissions to the profile.

**Comment by servidiomarco** [comment]
Hi @PierreRambaud I'm able to add related products myself with super Admin profile as shown on your screenshot but the issue occurs when another user profile is trying to do so. 
My guessing, receiving the token error back, is that this is happening when a different user tries to modify a products that hasn't been created by it.

**Comment by PierreRambaud** [comment]
I tried with a new user with new profile with the same permissions as yours and I still don't get any token errors :thinking: 
Do you use custom modules?

**Comment by servidiomarco** [comment]
@PierreRambaud no I don't use any custom modules

**Comment by PierreRambaud** [comment]
Could you please provide us more information about the system, your browser, php version, etc, please?

**Comment by servidiomarco** [comment]
@PierreRambaud I updated PS version, token error is gone.
Thanks

**Comment by PierreRambaud** [comment]
> @PierreRambaud I updated PS version, token error is gone.
> Thanks

Good to know :)
