### ISSUE TITLE
Ecotax not saved in a specific shop context when multistore is enabled

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18838]
#### Describe the bug

Ecotax not saved in a specific shop context when multistore is enabled

#### Steps to Reproduce

1. Enable the multistore in Shop parameters > General
2. Add a second shop in Advanced parameters > Multistore
3. Set an URL for the shop created 
4. Go to International > Taxes 
5. Put "use ecotax" on Yes
6. Save
7. Select an ecotax
8. Save
9. It's not saved

It's a regression of 1.7.6.0 (since the migration of this page in symfony) as in legacy page there was checkboxes in a specific shop context and it was working

**Screenshots**

https://drive.google.com/file/d/1SKVWg0dYdOed3Wi_mJEV6848qVTH_nd9/view?usp=sharing

Symfony page from 1.7.6.0

![capture d'écran_2577](https://user-images.githubusercontent.com/13449658/80470478-5bd8c080-8942-11ea-8eb0-22a8872de9df.png)

Legacy page < 1.7.6.0

![capture d'écran_2576](https://user-images.githubusercontent.com/13449658/80470498-62673800-8942-11ea-9947-240e9b71411c.png)

#### Additional information

* PrestaShop version: 1.7.6.0, 1.7.6.4, 1.7.7.x
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
This issue still persist with PS1.7.7.3_build1

**Comment by marionf** [comment]
@hibatallahAouadni yes, it wasn't supposed to be fixed in 1.7.7.3 ;)

**Comment by ghost** [comment]
Hello @marionf && @hibatallahAouadni 

I am currently working on the tax multishop and I realised that the problem was solved

https://www.okom3pom.com//videos/ecotax-issue-18838.webm

Thomas

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Yep :tada: it's been fixed!
Closing the issue.

Thanks!
