### ISSUE TITLE
Invalid order of city in customers address tab

### ISSUE THREAD

**Issue by jyothi0093** [PrestaShop/PrestaShop#18830]
customers address section has city above country and state, i think it should be listed after country and state as well as pincode should be listed below state.
![Screenshot from 2020-04-27 12-43-58](https://user-images.githubusercontent.com/63452509/80344227-dcd18280-8884-11ea-97e4-52ed3d3134f5.png)

**Comment by PierreRambaud** [comment]
HI @jyothi0093 and thanks for your report.

Ping @PrestaShop/prestashop-product-team what do you think?

**Comment by jyothi0093** [comment]
@PrestaShop/prestashop-product-team  im not able to access this.

**Comment by sam-pires** [comment]
hello @jyothi0093,

Thanks for the feedback 👍 Can you tell me a bit more about it.
Why is it a problem to have the city above the country in the form?

Is your feedback only about the form or about the address that is printed on the delivery slip afterward as well?

What are the benefits of changing the order of the "City" field in this form?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @jyothi0093,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
