### ISSUE TITLE
BO - Customer View page - there is no green alert after editing a voucher

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18842]
#### Describe the bug

In the BO => Customers => Customer view page, when we try to edit a voucher, there is no alert
:heavy_check_mark: `Successful update.` displayed

#### Expected behavior

The green alert should be displayed like in the legacy page
![image](https://user-images.githubusercontent.com/16067358/80367388-481e5300-888b-11ea-89a9-f2316478cde0.png)

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts page
2. Add new cart rule for the "John DOE" customer
3. Go to BO => Customers => Customer view page "John DOE"
4. Try to edit a voucher
5. Click save
6. No alert displayed

#### Additional information

* PrestaShop version: 1.7.6.0, 1.7.6.5
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/18841

**Comment by colinegin** [comment]
Rebase on 1.7.6.x needed, thanks !

**Comment by Progi1984** [comment]
I do it ;)

**Comment by Progi1984** [comment]
Fixed by #18975
