### ISSUE TITLE
BO - Order page - The total is incorrect in the "Add new cart rule" block after editing a product price if you don't refresh the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18844]
#### Describe the bug

In the BO => Order details page, the total is incorrect in the "Add new cart rule" block after editing a product price if you don't refresh the page

#### Expected behavior

Display the correct total in the "Add new cart rule" block after editing a product price without having to refresh the page.

#### Steps to Reproduce

1. Go to orders > orders
2. Click on View for an order in "payment accepted" status
3. Edit a product price
4. Add a new discount
5. The total is incorrect in the "Add new cart rule" block, you have to refresh the page

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/80377216-43619b00-889b-11ea-860e-bce44b5139ec.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @@PrestaShop/prestashop-product-team,

This issue **cannot** be reproduced with PS1.7.6 because we are blocked with this issue: https://github.com/PrestaShop/PrestaShop/issues/15716 which fixed in the 177.
So I think, it is a regression 177x.
What do you think?

Thanks!

**Comment by Progi1984** [comment]
Fixed by #19058
