### ISSUE TITLE
Select all not being selected

### ISSUE THREAD

**Issue by jyothi0093** [PrestaShop/PrestaShop#18858]
Hi select all in the below screenshot, either both the dropdown value along with select all should be selected or none of the options has to be selected by default.
![Screenshot from 2020-04-28 12-17-39](https://user-images.githubusercontent.com/63452509/80456845-e83bb100-894b-11ea-9e96-202295779225.png)

**Comment by sarahdib** [comment]
Hello @jyothi0093 

Thank you for your feedback.

I reproduce the issue : https://drive.google.com/file/d/19QhCf4fcb51p4cJkpJ0ISKrqFh6whf6O/view

Using 1.7.6 and 1.7.7

**Comment by aniketJivtode** [comment]
Hi, Can I work on this issue ?

**Comment by LouiseBonnard** [comment]
Sure, @aniketJivtode!

**Comment by matks** [comment]
PR to fix this bug https://github.com/PrestaShop/PrestaShop/pull/26215
