### ISSUE TITLE
from date and to date column doesnt display complete date filled.

### ISSUE THREAD

**Issue by jyothi0093** [PrestaShop/PrestaShop#18857]
from date and to date which is used for filtering data has only partial display of data
prestashop version-1.7.7.0

![Screenshot from 2020-04-28 11-42-46](https://user-images.githubusercontent.com/63452509/80454378-942ecd80-8947-11ea-96e0-4b65f8018cb2.png)

**Comment by sarahdib** [comment]
@jyothi0093 

It's the normal behavior in order to display all information.
