### ISSUE TITLE
Minimal quantity of 0 on product cause add to cart 0

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#18850]
#### Describe the bug

When the minimal quantity of a product is set to 0 (disable the fonctionality) in the B.O. the default value in add to cart part is by default 0… 

#### Expected behavior

The quantity to add to cart must be at least 1. There is no reason a customer order 0 product when it clicks on the «Add to cart» button …

#### Steps to Reproduce

1. Go to B.O. > Catalog > Product
2. Click on 'Quantities'
3. Set minimal quantity to 0
4. Go to F.O. > and show the Product detail page
5. The add to cart input has a value of «0» 

**Screenshots**

![image](https://user-images.githubusercontent.com/29065423/80396367-d0fdb480-88b4-11ea-949c-d37b7d583b97.png)
![image](https://user-images.githubusercontent.com/29065423/80396394-d9ee8600-88b4-11ea-83cb-dbd804730c56.png)

#### Additional information

* PrestaShop version: see on 1.7.5.0 / 1.7.6.2
* PHP version: 5.6.30 ( for the 1.7.6.2) / 7.0.33 (for the 1.7.5.0)

**Comment by sarahdib** [comment]
Hello @thalassa-web  

Thanks for this improvement.

@PrestaShop/prestashop-product-team  what do you thin k about this ?

**Comment by Progi1984** [comment]
A PR #18853 from @thalassa-web has been created.

**Comment by LouiseBonnard** [comment]
Hi @thalassa-web, thanks for your contribution here! Indeed 0 disables this feature, it means there is no minimum quantity mandatory to order this product. But you need to make sure the previous field, _Quantity_, is filled with a value bigger than 0 - it is not the case on the first screenshot. And then the customer should be able to order the product in the desired quantity, starting at 1 obviously.

FYI @MatShir

**Comment by hibatallahAouadni** [comment]
@MatShir what's this issue's status, is it **`To Do`** or need more specs **`TBS`**?

**Comment by florine2623** [comment]
This is fixed on PPV2 in 8.0.x, 8.1.x and 9.0.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/a2b00eb3-607f-4592-847b-68f018a8b7d6



I'm closing the issue.
