### ISSUE TITLE
@outlook email does not receive emails

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/PrestaShop#18856]
#### Describe the bug

Any customer with @outlook.com domain does not receive any emails from my shop.
I use an external SMTP for sending emails.

Test email does not arrive at outlook.com inbox, or any other sent emails.

**I've checked the spam folder.**

No problem with other email providers **yet**.

#### Expected behavior

receive email.

#### Steps to Reproduce

USE SMTP - SSL 465

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by Macrisu** [comment]
Fixed:

1. get composer.json from develop branch, and put it in root.
https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json
2. Run _composer update_ with 4096 Mb RAM for memory in php.ini
This will update vendor/swiftmailer to v6
3. Get the new Mail.php from classes in the delevop branch
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php

Now I need to find out why all emails are going intro outlook spam folder.

**Comment by sarahdib** [comment]
Hello @Macrisu 

Could you tell us what is the parameter you put in smtp configuration in order to try to reproduce ?

Thank you

**Comment by Macrisu** [comment]
I use an external Smtp that is working for other email addresses.
the problem seems to be Outlook.com system.
For exemple:
- I get in the Spam folder the first registratuo  email.
- I do not get at all the mesage for password reset, not a trace of it in Inbox or spam.
The shop system is working, the problem seems to be the Outlook filter system.
Nothing in the smtp log...

Steps to reproduce:
Create an user account with email @outlook.com
See if you receive the original registration email.
Try to reset the password and if you receive the message with password reset link.

**Comment by sarahdib** [comment]
@Macrisu 
The issue seems linked to outlook not PrestaShop.

**Comment by matks** [comment]
@Macrisu unfortunately mail providers spamming strategy will always be very obscure 😢indeed we cannot solve this with software
