### ISSUE TITLE
modulo "1-Click Upgrade" / ERRORE 500

### ISSUE THREAD

**Issue by viosan** [PrestaShop/PrestaShop#18863]
Ciao, alla fine di gennaio ho installato il modulo "1-Click Upgrade", cercando di passare dalla v 1.7.5.0 alla v 1.7.6.0. Come sapete, il modullo crea un backup, che trovo sul server:
https://www.screencast.com/t/mHKMaFKe8o
https://www.screencast.com/t/R0HRnUvkKf
In questi giorni ho provato ad andare tornando alla vecchia versione, dalla v 1.7.5.6 alla 1.7.5.0 attraverso questo modulo, ma quando l'ho fatto tutto è stato bloccato, il sito e l'amministratore non sono più accessibili, mi dà sempre "erroe 500", e non so come riattivarlo.

Mi potete aiutare per favore.

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by alfonsolr09** [comment]
tried to clean the cache of prestashop?

**Comment by sarahdib** [comment]
Hello @viosan 
Please could you wrote in english ?

Thank you

**Comment by alfonsolr09** [comment]
send a image of the error 500 pls

**Comment by alfonsolr09** [comment]
@sarahdib this said

Hi, at the end of January I installed the "1-Click Upgrade" module, trying to switch from v 1.7.5.0 to v 1.7.6.0. As you know, the modullo creates a backup, which I find on the server: https://www.screencast.com/t/mHKMaFKe8o https://www.screencast.com/t/R0HRnUvkKf En these days I have tried to go back to the old one version, from v 1.7.5.6 to 1.7.5.0 through this module, but when I did everything was blocked, the site and the administrator are no longer accessible, it always gives me "erroe 500", y no tan reactivate it. Can you help me please. <! -

**Comment by viosan** [comment]
https://www.screencast.com/t/7Ehnelt7Sl

**Comment by alfonsolr09** [comment]
did you check the php version? did you clear the cache after downgrading version?

**Comment by viosan** [comment]
php 7.2.
Sorry, running I didn't express myself well:
while I was in the dashboard, in the "1-Click Upgrade" module, when I finished the downgrade process from v 1.7.5.6 to v 1.7.5.0, the final entry indicated an error in loading the files. When I left the form, everything crashed: in the admin you could no longer log in, and the site gave me error 500. Everything here .... all dead.
CANNOT ACCESS THE DASHBOARD (The page does not work) - CANNOT ACCESS THE SITE (error 500).

Thanks.

**Comment by viosan** [comment]
![Annotazione 2020-04-29 094317](https://user-images.githubusercontent.com/63297464/80572279-47f29480-89fe-11ea-8db4-08d01ca25566.jpg)

**Comment by florine2623** [comment]
Hi @viosan ,
It seems like your are missing a table in your database.
I suggest you to get in touch with your host and restore a back-up of your site from when your website was still up and running.
Please check with your host and let met know the outcome!

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
