### ISSUE TITLE
Unable to add a new product

### ISSUE THREAD

**Issue by crabbi33** [PrestaShop/PrestaShop#18869]
After an importation of ps_product related table from a ps1.7.2.4 to a ps1.7.5.6 with forced ID, i can't add a new product

got  that

[<a href="https://zupimages.net/viewer.php?id=20/18/gtc9.png"><img src="https://zupimages.net/up/20/18/gtc9.png" alt="" /></a>](url)

[<a href="https://zupimages.net/viewer.php?id=20/18/y5ex.png"><img src="https://zupimages.net/up/20/18/y5ex.png" alt="" /></a>](url)

If someone have an idea !!!

**Comment by florine2623** [comment]
Hi @crabbi33 ,
Did you import ps_product manually ?
If you want to do an update, please use a tool for that. You will avoid database issue.

Here is the database schema for PS 1.7.6.5 :
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.5/install-dev/data/db_structure.sql

You can compare it with 1.7.6.2 and see what you are missing : 
https://github.com/PrestaShop/PrestaShop/blob/1.7.2.x/install-dev/data/db_structure.sql

Thanks!

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
