### ISSUE TITLE
Division by zero in AdminCustomerThreadsController.php on line 718

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#18879]
#### Describe the bug

Multi shop, Update to 1.7.6.4, white screen on customer thread view in back office.
No errors, even in debug mode (;__;), find this in the server log :

Division by zero in /controllers/admin/AdminCustomerThreadsController.php on line 718
==> 'total_ok' => isset($total_ok) ? Tools::displayPrice($total_ok, $this->context->currency) : false,

var_dump($total_ok) ==> float(INF)

Find that conversion_rate of currency has been reset to 0.000000 for all shop exclude the one whit ID = 1.  Some orders have been create and have that zero conversion rate.
The view of a customer thread related to one of these order crash the admin.

#### Expected behavior

Just working and be happy...

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @rflorent ,

I can't reproduce your issue :
![Capture d’écran 2020-04-30 à 10 32 57](https://user-images.githubusercontent.com/16019289/80689728-07624c00-8ace-11ea-9aac-037cadaac020.png)

Please clear cache and check if you have errors on the console.
Make sure you don't have any module that might override that page.

Thanks!

**Comment by rflorent** [comment]
Hi @florine2623 ,

My multishop configuration is the following : 
Two groups, with two shop on each group.

This multishop has been upgraded from 1.6 to 1.7.5.2 and 1.7.5.2 to 1.7.6.4.
The bug described is on the view of a customer thread and not on the list.

By the way, this bug is due to a missing conversion rate on currency, in some orders related to a thread, who can tell when this occurs ? when migrating to 1.7.5.2 or 1.7.6.4 ?

You can also try to change conversion rate of currency on the shops by the backend ui, I have a error message "You cannot change the conversion as it is use by the shop xxxx".

Thanks

**Comment by florine2623** [comment]
I've created 2 groups with 2 shops in each group.
I still can't reproduce your issue.

Regarding your upgrade, did you use a tool of did you do it manually ?

I've have succeeded in changing the currency rate.
I think those 2 issues might not be related.

**Comment by rflorent** [comment]
![bug-prestashop-conversion-rate](https://user-images.githubusercontent.com/8590540/80734913-339ebc80-8b10-11ea-83cf-bbb68cc0470d.jpeg)
![bug-prestashop-devise](https://user-images.githubusercontent.com/8590540/80734921-36011680-8b10-11ea-99d1-f6a96b3f5f1f.jpeg)

I use a migrating tool purchased on the prestashop addons.
First you can see that conversion rate is zero on the main shop.
And If I want to edit it, there is an error.

**Comment by rflorent** [comment]
For information, I update the conversion rate to 1 on orders instead of 0, directly in database which fix the admin crash when displaying a customer thread.
So I don't understand why if I can set a conversion rate to zero, this will crash ?
Try to make an order with a zero conversion rate. Create a customer thread on that order and try to view it in the admin.

**Comment by florine2623** [comment]
Hi @rflorent ,
This is not crashing. The error just means that your are using euro as default currency in your shop and can't change default currency rate. 
If you want to change the currency rate of default currency:
- go to International > Localization
![Capture d’écran 2020-05-07 à 11 23 12](https://user-images.githubusercontent.com/16019289/81277832-3d1aae00-9055-11ea-9da1-a8286a1d48e2.png)

- you need to change the default currency by another one first
- change the currency rate of euro
- put back euro as default currency

Please check and let me know

**Comment by rflorent** [comment]
Hi @florine2623 
Then the error message is not explicit.
I'm editing the rate not changing the currency.
Anyway it don't explain why I get zero rate after upgrade or migrate.
Sorry but like often, when I open an issue on prestashop, it's always working on prestashop team's side or more details is needed and finally, there is no solutions.

Thanks for your time

**Comment by rflorent** [comment]
Do you try this ?

Try to make an order with a zero conversion rate. Create a customer thread on that order and try to view it in the admin.

**Comment by florine2623** [comment]
@rflorent ,
If the message is not explicit enough, feel free to add an improvement issue stating exactly what message you'd like to see.
So did you try what I said earlier ? It will allow you to change the currency rate of euro.

It is not possible :
![Capture d’écran 2020-05-07 à 15 26 04](https://user-images.githubusercontent.com/16019289/81299811-1a998c80-9077-11ea-9af3-dac0928708ea.png)
Please change your currency rate with the method I gave you earlier.

**Comment by rflorent** [comment]
@florine2623 

thanks, your answer is focused on this part of the issue and not why my currency have a zero rate after upgrade / migration, which lead to different issues as mentionned. I understand that it's hard to find and this issue probably rely on a pretashop version with a buggy multishop feature, or a bug from migrating tools (purchased on addons...).
So, I will close as I think there is no explications and solutions.

Again, thanks for your help and have a nice day
