### ISSUE TITLE
Thai currency symbol (฿ - Baht) is not displayed correctly in PDF invoice

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#18874]
#### Describe the bug

`฿` symbol is not displayed in invoice.

#### Steps to Reproduce

1. Import "Thailand" location
2. Create an order
3. Generate invoice
4. Check invoice. `฿` symbol is replaced with `?`

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/15104724/80496462-8722d600-8969-11ea-8c7b-72c2d7bbb479.png)

#### Additional information

* PrestaShop version: 1.7.6.5

**Comment by Tanguy-SALMON** [comment]
Is it a wrong setting? I have a Thai shop (ps 1.7.5.1), fully in Thai language. 
On the shop, there is only one currency set, THB.
On the invoice, I don't have the ฿, but THB. But it's ok for us.

![image](https://user-images.githubusercontent.com/6756795/80507017-8c4f4780-89a0-11ea-8ef2-439d52760cf9.png)

**Comment by idnovate** [comment]
Maybe it's related with this https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.6/#cldr

**Comment by Tanguy-SALMON** [comment]
I just set a PS1763 by importing the Thai language, I get the ฿ symbol.

![image](https://user-images.githubusercontent.com/6756795/80508567-66c33d80-89a2-11ea-873a-7f7f9647b895.png)

**Comment by idnovate** [comment]
Not sure which is the problem then, but I tested it because of this https://www.prestashop.com/forums/topic/1007915-probl%C3%A8me-affichage-symbole-devise-sur-facture-presta-1752/

**Comment by florine2623** [comment]
Hi @idnovate and @Lathanao ,
I could not reproduce the issue on PS 1.7.6.5, here my result :
![Capture d’écran 2020-04-30 à 10 52 22](https://user-images.githubusercontent.com/16019289/80691604-c9b2f280-8ad0-11ea-9757-5679aa4e3e79.png)
I'm using language English and currency Baht.

@idnovate 
Did you import the localization pack with country Thailand with all content ?
![Capture d’écran 2020-04-30 à 10 56 08](https://user-images.githubusercontent.com/16019289/80692122-6ffef800-8ad1-11ea-9db2-74aa6e21d842.png)
Did you create the language manually ? Is the symbol of Baht displayed ?
![Capture d’écran 2020-04-30 à 10 55 35](https://user-images.githubusercontent.com/16019289/80692161-81480480-8ad1-11ea-9ae4-9ee6dec83d1c.png)

Thanks!

**Comment by idnovate** [comment]
I imported Thailand pack automatically.

**Comment by Tanguy-SALMON** [comment]
By checking your invoice, you can see the interrogation mark is at the end to the value, it should be at the beginning. IMO, it's a wrong configuration.

IMO, what you could check could be :
 - Check if in thai language version, you have the right Thai character like there : 
![image](https://user-images.githubusercontent.com/6756795/80719915-5cca4780-8b26-11ea-9323-891ca9dba849.png)
 - Delete all no primary currencies then reinstall them again
 - Change the front end language by a common on like 'en' and generate invoice
 - Try to use the local pack by desactive this option:
![image](https://user-images.githubusercontent.com/6756795/80718585-897d5f80-8b24-11ea-8c22-f3d3f2f4fda8.png)
 - Install again a new Prestashop with the same version and check the invoice.
      -> if you still have the problem, install again, and try set to the default language as 'en'

**Comment by idnovate** [comment]
I installed a fresh PS 1.7.6.5 in English, import Thailand language pack and couldn't reproduce the issue. Not sure which is the problem with the other installation as I have imported package the same way and I have not edited any currency.

**Comment by florine2623** [comment]
Hi @idnovate ,
Could you update your language and try again ?
Please check and let me know !

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
