### ISSUE TITLE
BO - New currency page issues

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#18882]
#### Describe the bug

The migration of the admin currency page to symfony does not seem to be finished.

#### Expected behavior

Finish migration and make the currency page great again.

#### Steps to Reproduce

1. Go to currency page in BO
2. Id column is missing
3. Bulk action is missing (delete, disable, enable)
4. Show SQL query is missing
5. Export to SQL Manager is missing
6. We cannot filter by currency name
7. We cannot filter by cyrrency symbol

**Screenshots**

![currency](https://user-images.githubusercontent.com/16455155/80542667-be1adb00-89ad-11ea-9e74-f2bc599b3925.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by MatShir** [comment]
Nice catch !

**Comment by matks** [comment]
Hi ! I just realized this modifies a migrated page in the BO 😅 .

So I was surprised to read
> The migration of the admin currency page to symfony does not seem to be finished.

So I just installed a PS 1.7.5 instance to see what the page looked like before the migration. Here it is:
<img width="1231" alt="Capture d’écran 2020-05-29 à 09 50 36" src="https://user-images.githubusercontent.com/3830050/83235332-ffabcb00-a191-11ea-9faa-73995d861b50.png">

So "The migration of the admin currency page to symfony does not seem to be finished." is a bit inaccurate 😅 we actually migrated the page following its structure before (issue https://github.com/PrestaShop/PrestaShop/issues/10189 for details)

**Comment by matks** [comment]
This being said, that does not mean this improvement (and huge work by @PululuK) is not welcomed !

Only thing we must be careful about: bulk delete. I believe we already discussed about it and we said "deleting currencies in a shop can have huge impact on the shop behavior so we better not allow people to do it using bulk".
ping @MatShir

**Comment by PululuK** [comment]
I completely agree with you @matks , it is indeed an improvement. 
I expressed myself poorly, my sincere apologies I did not want to devalue your beautiful work.

As you can see this page is not consistent with the rest of the migrated pages, that's why I had the impression that it was not finished.

Thank you and Sorry.

**Comment by matks** [comment]
> I completely agree with you @matks , it is indeed an improvement.
> I expressed myself poorly, my sincere apologies I did not want to devalue your beautiful work.
> 
> As you can see this page is not consistent with the rest of the migrated pages, that's why I had the impression that it was not finished.
> 
> Thank you and Sorry.

Eyh eyh eyh 😅 no no no don't be sorry I was not angry !

I was actually worried I did a mistake (especially because the page was migrated in 1.7.6 so ... if I did a mistake, it's been almost 1 year it's there, unfixed) that is why I just wanted to correct the statement.

You did a big work on this page 👍 thank you so much
