### ISSUE TITLE
'Unable to update settings' error saving any product that have a large amount of combinations

### ISSUE THREAD

**Issue by shelve71** [PrestaShop/PrestaShop#18881]
Hi,
i receive the error message 'Unable to update settings'  when i try to saving any product with a large amount of combination. In my case the product have 1050 combinations. 

With orther products with less combinations, all works fine.

I also switched on the "Debug mode" ( I attach screenshot of console error)
![Screenshot_](https://user-images.githubusercontent.com/64500934/80540130-04217000-89a9-11ea-9fd2-6a617283b1b5.jpg)

#### Additional information

Server information Linux #1 SMP Tue Oct 9 18:14:47 EEST 2018 x86_64
Server software version: Apache
PHP version: 7.0.33
Memory limit: 768M
Max execution time: 120
Upload Max File size: 128M
MySQL version: 5.6.40-84.0-log PrestaShop version: 1.7.6.4 

How can solve this issue ?

Thanks for the support.

**Comment by florine2623** [comment]
Hi @shelve71 ,
Can you try to increase the value of the PHP.ini setting `max_input_vars` to 2000 and try again ?
Thanks!

**Comment by shelve71** [comment]
Hi Florine,
my value is already higher. It is 27.000 because i received allert system message from prestashop. 
After this, i had system message  'Unable to update settings' when tried to update products with considerable combinations.

Thanks.

**Comment by florine2623** [comment]
It seems like this kind of error is a memory limit one.
I'd advise you to check with your host if you could allow even more memory than now.
Also, if that's possible, could you try to set your combinations in several times ?
Thanks

**Comment by shelve71** [comment]
Hi, thanks for the reply, what do you mean for "try to set your combinations in several times" ?
For each product, prestashop generate combinations of all options, all at once. If i want add new combinations, i before have to delete all old combinations and after generate the new combinations, all at once.

Thanks.
Antonio

**Comment by florine2623** [comment]
Hi @shelve71 ,
What I'm trying to say is that having 1050 combinations might not be ideal.
I don't know how your products are constructed. 
For example, if you have **color** and **size** attributes, instead of having 1 product with those 2 combinations, you could have _one product in blue_ with combination of sizes and _one product in red_ with combinations of sizes.
I don't know if that's clear ?
Thanks

**Comment by shelve71** [comment]
Hi,
thanks, it is clear now!

Antonio
