### ISSUE TITLE
Design of content page

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#18880]
#### Is your feature request related to a problem?

Hello!
In the PS 1.7.6.3 I can`t found the possibility to choose different variants of design (3 column, one big column and one small, etc) Like in the PS 1.7.5.2 for example. 
This option was in the Design->Theme and Logo->
How this option is realized in the PS 1.7.6.3?

Thanks

**Comment by prestascott** [comment]
Hello @photinia73,

You can find the possibility to choose different variants of design here:
Design > Theme & Logo > Choose Layouts

Here is a screenshot where you can find this section: 
![image](https://user-images.githubusercontent.com/54888056/80620768-b3605480-8a46-11ea-8acc-3f0f56daa422.png)

**Comment by photinia73** [comment]
O thank you very much! I didn`t notice )) З повагоюКричмарівська Світлана От: PrestaScottОтправлено: среда, 29 апреля 2020 г. в 19:25Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] Design of content page (#18880) Hello @photinia73,You can find the possibility to choose different variants of design here:Design > Theme & Logo > Choose LayoutsHere is a screenshot where you can find this section:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
