### ISSUE TITLE
BO - adding voucher while creating new Order

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#18889]
#### Describe the bug

It's regression, we can't add new voucher while creating new order from BO.

#### Expected behavior

After adding new voucher, it should be automatically applied to an order, this is how it worked in 1.7.6

#### Steps to Reproduce

1. Add new order, fill the data
2. Add new voucher, create new one
3. Save it
4. See that voucher is not applied to an order

#### Additional information

* PrestaShop version: 1.7.7 dev branch
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @kpodemski ,

I could not manage to reproduce the error. Please check my screen record : 
https://drive.google.com/file/d/1hD0UU3cfbl5Peb1WDOIG3WNK5fe04DZk/view

Please use PHP version 7.3 and try again.

Thanks!

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
