### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by operator2010** [PrestaShop/PrestaShop#18894]
#### Describe the bug

When there is a space between the IP Adresse Maintenance Mode will not work

#### Expected behavior

Escape spaces after and before , (comma)

#### Steps to Reproduce

1. Go to 'Settings' > 'Main' > 'Maintenance'
2. Click on ''> insert new IP with empty spacer
3. Scroll down to 'Save'
4. See error -> No error -> Test Frontend if visible

**Screenshots**

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by PululuK** [comment]
Hi @operator2010,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

But in any case I managed to reproduce your issue.

@PrestaShop/prestashop-product-team @khouloudbelguith  What do you think about allowing spaces in Maintenances IP ?

**Comment by prestascott** [comment]
Hi @operator2010 ,

You must downgrade your PHP version into 7.2. 
Please check: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks :)

**Comment by PululuK** [comment]
> Hi @operator2010 ,
> 
> You must downgrade your PHP version into 7.2.
> Please check: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> Thanks :)

@prestascott Even with a compatible version of PHP, you can reproduce this issue !
What do you think about allowing spaces in Maintenances IP ?

**Comment by prestascott** [comment]
Hello @operator2010 & @PululuK,

I managed to reproduce the issues. 
Here are the screenshots with the space:
![image](https://user-images.githubusercontent.com/54888056/80610534-c4ef2f80-8a39-11ea-9bd2-cd49e2e1988e.png)
![image](https://user-images.githubusercontent.com/54888056/80610557-cae51080-8a39-11ea-8d72-abb944ad24a8.png)

Here are the screenshots without the space:
![image](https://user-images.githubusercontent.com/54888056/80610586-d1738800-8a39-11ea-828d-aaa94e09ae84.png)
![image](https://user-images.githubusercontent.com/54888056/80610600-d59fa580-8a39-11ea-9a71-dcde53da65c9.png)
