### ISSUE TITLE
Show last visible status order on order history page

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#18892]
**EDIT**
On front office > customer order history page, show the last visible order status.
At some point of the order flow, it might get a specific order status that the merchant decides not to display to the customer (option available in the status configuration). When the order gets this status, nothing is displayed in the customer account, which can create confusion for the customer.
With this improvement, it will show in the customer account the last status the order had before getting this "invisible" status.

Edge case : if the first status an order gets is "invisible" for the customer, then show nothing.

**Initial description :**
We received some complains from customer that can't see the order-status on the order history page. Our reply was always its there, or click on details. I never understood why they where not seeing anything until I realised that we use statuses that are invisible for the customers.  Once an order is shipped, we change status for administrations reasons. The customer does not need to see this status. 

When the status is not there, customers think that their order was not processed  and think they have to reorder. It causes a bit of confusion.

I attached a screenshot with two orders. One order is cancelled, the other is put in to the next status phase. As you can see its empty ( status will show up once you click on details ).  

Request: show on the order history page the last visible status for customer. Just like in the order detail page.

<img width="1228" alt="Screenshot 2020-04-29 at 12 59 04" src="https://user-images.githubusercontent.com/46492443/80594551-1fc55e80-8a1b-11ea-8e27-139361322d0c.png">

Prestashop 1.7.6.5

**Comment by prestascott** [comment]
Hello @01park ,

Thank you for your report. I tried to reproduce the bug in 1.7.6.5 and 1.7.5.2 versions, here is the screenshot:
![image](https://user-images.githubusercontent.com/54888056/80612404-37f9a580-8a3c-11ea-94b9-02afb613b87c.png)
I can see both status. 

Can you tell us which payment status are invisible and what PrestaShop version did you use?

Thank you :)

**Comment by 01park** [comment]
Hi,

After we ship, the order can be set to another status. We don't want the customer to see this.

<img width="1230" alt="Screenshot 2020-04-29 at 17 41 37" src="https://user-images.githubusercontent.com/46492443/80623617-60849e00-8a42-11ea-90f1-09439f7bc85d.png">


I have already select and deselect to set this order to pay or shipped, but this status or all other statuses that we created ourself will make sure the status is also not seen on the order history page.

**Comment by florine2623** [comment]
Hi @01park ,
I'm not sure I understand what your issue is here.

On PS1.7.6.5, here's what i have with this configuration :
I hide this status from customer :
![Capture d’écran 2020-05-07 à 14 15 29](https://user-images.githubusercontent.com/16019289/81293284-56c7ef80-906d-11ea-9466-f7fbacfe7f6d.png)
I don't see the status as a customer : 
![Capture d’écran 2020-05-07 à 14 14 34](https://user-images.githubusercontent.com/16019289/81293325-6a735600-906d-11ea-8f79-2eeb22bfbe2e.png)
As the merchant, in my BO I see the order status :
![Capture d’écran 2020-05-07 à 14 14 58](https://user-images.githubusercontent.com/16019289/81293347-77904500-906d-11ea-9d78-baac1252202f.png)

Is that clear enough for you ?

**Comment by 01park** [comment]
Hi

The issue is that the customer sees no status. My request was, that instead of seeing nothing, the customer can see that last visible status, just like the see once the click on details .

**Comment by florine2623** [comment]
Thanks for the recommandation ! This will be sent to the product-team, they will decide if the issue is relevant !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team !

In order status setting, it is possible to hide an order status to a customer in his account :
![Capture d’écran 2020-05-07 à 14 15 29](https://user-images.githubusercontent.com/16019289/81310500-6ef73900-9084-11ea-89c9-48c57bac2dda.png)
 @01park would like to hide that status, but show another previous status to the customer.

Is this something relevant enough to implement ?

Thanks !

**Comment by PabloGBarcelo** [comment]
> Hi @PrestaShop/prestashop-product-team !
> 
> In order status setting, it is possible to hide an order status to a customer in his account :
> ![Capture d’écran 2020-05-07 à 14 15 29](https://user-images.githubusercontent.com/16019289/81310500-6ef73900-9084-11ea-89c9-48c57bac2dda.png)
> @01park would like to hide that status, but show another previous status to the customer.
> 
> Is this something relevant enough to implement ?
> 
> Thanks !

We use some hidden status for our internal system and we want to hide from customers, but they don't know actual status and felt worried about what happend with their orders. I think that its better to give 'last readable status' than nothing.

**Comment by 01park** [comment]
@PabloGBarcelo 

Im not looking how to hide it, I'm looking for the customer to see the last visible status. Just like on  the order detail page.

**Comment by colinegin** [comment]
I find this idea very interesting ! 
I put it in "to do", but do not hesitate to make a PR to add this improvement ! 

Thanks,

**Comment by matthieu-rolland** [comment]
Thank you for the suggestion @01park, the PR is ready to be reviewed:  #20096
