### ISSUE TITLE
Accented & special characters misinterpreted in customer service messages

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#18890]
#### Describe the bug

Accented & special characters misinterpreted in customer service messages (SAV in french).

#### Expected behavior

A well interpretation of accented & special characters as customer wrote it in original message.

#### Steps to Reproduce

1. In FO, write a message with accented & special characters as customer
2. In BO, in SAV > SAV page (in FR), message is wrong interpreted

**Screenshots**

![sav-accents](https://user-images.githubusercontent.com/7419525/80588058-e808e780-8a17-11ea-8871-90b84275b059.jpg)

Some messages are unreadable!
![accents](https://user-images.githubusercontent.com/7419525/80588094-f8b95d80-8a17-11ea-86c8-a572163bf1a2.jpg)

#### Additional information

* PrestaShop version: 1.7.6.4 (fresh install, classic theme, no core/override change)
* PHP version: 7.1

**Comment by prestascott** [comment]
Hi @Klemart3D, 

Please update your PHP version to 7.2 and take a look a this documentation: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I tried to reproduce the bug and there is no issue on special characters. Here is the screenshot:
![image](https://user-images.githubusercontent.com/54888056/80614900-51502100-8a3f-11ea-9b4d-ac0e25684bdb.png)


Do you have an error when you inspect in console mode?

**Comment by Klemart3D** [comment]
Hi @prestascott,

Thanks for your answer.
I can't update a PHP version just for an accent issue. As [explained in devdocs](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart), PrestaShop 1.7.6.x must supports PHP 7.1 (if don't, please change it to "Not supported").

Error is also in source code as pointed by developer tool (FF/Chrome):
![screen 1](https://user-images.githubusercontent.com/7419525/80622514-34205000-8a49-11ea-88f6-e498b103ca62.jpg)


Here is my phppsinfo:

![PHP PrestaShop Info](https://user-images.githubusercontent.com/7419525/80621438-924c3380-8a47-11ea-9506-4fcd6cbe9f49.png)

**Comment by Klemart3D** [comment]
Perhaps similar to: #9726
Possibly PR (merged for 1.7.7.0): #15840

**Comment by prestascott** [comment]
Please go to: \themes\default\template\controllers\customer_threads\helpers\view\concerned_file

and replace these lines: {$message.message|escape:‘html’:’UTF-8’|nl2br} 
by: {$message.message|unescape:‘html’:’UTF-8’|nl2br}

You can also remove these lines: |escape:‘html’:’UTF-8’|nl2br when there is $message.message.

**Comment by Klemart3D** [comment]
Thanks @prestascott, there what I did:

1 - In`/admin***/themes/default/template/controllers/customer_threads/helpers/view/message.tpl`
I changed: `{$message.message|escape:‘html’:’UTF-8’|nl2br}`
By: `{$message.message}`
EDIT (my previous suggestion): `{$message.message|unescape:‘html’:’UTF-8’|nl2br}`

2 - In`/admin***/themes/default/template/controllers/customer_threads/helpers/view/timeline_item.tpl`
I changed: `{$timeline_item.content|nl2br}`
By: `{$timeline_item.content|unescape:'html':'UTF-8'|nl2br}`

3 - In `/admin***/themes/default/template/controllers/orders/helpers/view/view.tpl`
I changed: `{$message['message']|escape:'html':'UTF-8'|nl2br}`
By: `{$message['message']}`

Now, messages are well displayed. Do have we to create a PR for this?

**Comment by Allba** [comment]
For my installation worked only when i deleted "|unescape:‘html’:’UTF-8’|nl2br".
Thanks to both of you.

**Comment by florine2623** [comment]
Hi @Klemart3D ,
There's no PR for that issue. If you have one, do not hesitate to create one.
Thanks !

**Comment by Klemart3D** [comment]
Hi @florine2623 ,
So if no PR, issues are closed? Problem isn't here?
I asked if I have to work on a PR, but if you close issue that means is there no problem.
Have you try to reproduced it? On which versions? Is it fixed on v1.7.7?
A better support is required.

**Comment by florine2623** [comment]
Hi @Klemart3D ,
No, because that issue can't be reproduced in neither PS1.7.6.5 and PS1.7.7.

Please see the screenshots below :
**PS1.7.6.5**
![Capture d’écran 2020-05-07 à 16 49 35](https://user-images.githubusercontent.com/16019289/81309068-d1e7d080-9082-11ea-95ce-70c06b9977ea.png)
![Capture d’écran 2020-05-07 à 16 47 49](https://user-images.githubusercontent.com/16019289/81309113-ddd39280-9082-11ea-9ebd-0edcaea9a78a.png)
**PS1.7.7.**
![Capture d’écran 2020-05-07 à 16 48 20](https://user-images.githubusercontent.com/16019289/81309168-eaf08180-9082-11ea-9f44-f943a472bb86.png)
![Capture d’écran 2020-05-07 à 16 48 20](https://user-images.githubusercontent.com/16019289/81309270-0c516d80-9083-11ea-9242-f1edadd4fe04.png)
Thanks!

**Comment by alfonsolr09** [comment]
@florine2623 thats a bug or a php error?

**Comment by Betafer** [comment]
The problem is present in prestashop 1.7.6.5 with PHP 7.2

**Comment by alfonsolr09** [comment]
in version 1.7.6.4 it also exists.  what should i do to fix it?  or will it be fixed in a later version of prestashop?
 @Betafer

**Comment by Betafer** [comment]
> in version 1.7.6.4 it also exists. what should i do to fix it? or will it be fixed in a later version of prestashop?
> @Betafer

If you can fix it it would be better.
Thanks

**Comment by alfonsolr09** [comment]
Ping @florine2623

**Comment by alfonsolr09** [comment]
@florine2623

**Comment by ChineseNorris** [comment]
Hi,

the solutions posted seems to work for messages between customer and store, but won't work if the message is sent from the observations box from carrier checkout page.
However with the help from @manu20gm from the forums solves the display issue by decoding the $message with html_entity_decode() function in /Backo
Officefolder/themes/default/template/controllers/orders/helpers/view/view.tpl 
`{html_entity_decode($message['message']|escape:'html':'UTF-8'|nl2br)}`

forum link: https://www.prestashop.com/forums/topic/962368-ps175-error-caracteres-tiles-y-%C3%B1-en-mensajes-de-clientes-solucionado/
This error is present with 1.7.6.5 and php 7.2

**Comment by Betafer** [comment]
The problem is still present in prestashop 1.7.6.6 with PHP 7.2.32

' is changed by `&amp;#039;`

<img width="742" alt="Schermata 2020-07-22 alle 08 49 11" src="https://user-images.githubusercontent.com/5024055/88143948-641a6200-cbf8-11ea-84c3-9708e4b55f90.png">

**Comment by ChineseNorris** [comment]
@Betafer Did you tried the solution I mentioned?

**Comment by Betafer** [comment]
yes, it work, thanks.
it would be nice if the fix was implemented in prestashop and not having to do it after every update.

**Comment by Maofree** [comment]
hi to all
this problem continue to be present in the 1.7.6.8
it is necessary to replace "escape" with "unescape"
into
`{$message.message|unescape:'html':'UTF-8'|nl2br}`
/admin***/themes/default/template/controllers/customer_threads/helpers/view/message.tpl

and

`{$message['message']|unescape:'html':'UTF-8'|nl2br}`
/admin***/themes/default/template/controllers/orders/helpers/view/view.tpl

it is necessary to add a bugfix
bye

**Comment by alfonsolr09** [comment]
@florine2623 what appens with this bug?

**Comment by joaolago1113** [comment]
@maofree Sounds like a very bad idea. What if someone sends an HTML encoded message of a script?

**Comment by Maofree** [comment]
@joaolago1113 you can suggest another solution to fix that problem

**Comment by ChineseNorris** [comment]
@maofree @joaolago1113 @alfonsolr09 

You guys can check this PR with the fix:

https://github.com/PrestaShop/PrestaShop/pull/15840

It will be released in the 1.7.7 release but you guys can do it easily, it's only one lane modification.

**Comment by HartLarsson** [comment]
The fix i've applied on PS 1.7.6.7 is on file:
/<admin_folder>/themes/default/template/controllers/customer_threads/helpers/view/**message.tpl**:


from: 
`<p class="message-item-text">{$message.message|escape:'html':'UTF-8'|nl2br}</p>`
to: 
`<p class="message-item-text">{$message.message|html_entity_decode|escape:'html':'UTF-8'|nl2br}</p>`

A compact and simplified version, since html_entity_encode already uses UTF8, can be:
`<p class="message-item-text">{$message.message|html_entity_decode|escape:'html'|nl2br}</p>`

Same for the message inside the order:
/<admin_folder>/themes/default/template/controllers/orders/helpers/view/**view.tpl**

from:
`{$message['message']|escape:'html':'UTF-8'|nl2br}`

to:
`{$message['message']|html_entity_decode|escape:'html':'UTF-8'|nl2br}`
