### ISSUE TITLE
Header issue PS 1.7.6.4

### ISSUE THREAD

**Issue by romanzkromrize** [PrestaShop/PrestaShop#18903]
Hello guys, on mobile version of my eshop www.erotic-house.cz, i have problem with logo and cart. Sometimes it loads fine, but after swaping up and down logo and cart button dissapear. Sometimes its hidden after page load, but after swaping up and down it appear. 
It looks like this problem is only on home page of eshop.
I tried disable cache, clear cache. But iam total newbie so i probably need help :(

Iam using Love and Sex theme
Thnk you and sorry for my english. 
R.

**Comment by florine2623** [comment]
Hi @romanzkromrize ,
This is a theme issue. You should contact the developer of the theme directly.

Thanks!
