### ISSUE TITLE
FO - Detail discount is not good in multicurrency context

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18900]
#### Describe the bug

If discount a applied to a cart in EUR everything is good ( detail discount, total discount )  but if we switch to USD the detail discount is not good ( the total is still good ) maybe related with this issue #18810

#### Expected behavior

The detail discount should be good in every currencies

#### Steps to Reproduce

1. Go to BO => international => localisation and add USD currency
2. GO to BO => catalog => discount and create a 10% discount
3. Go to FO set the currency to EUR and create a cart with some items
4. Apply the previuously created discount check the detail discount and the total discount they should be identical 
5. Switch currency to USD see error

**Screenshots**

**Currency in EUR €**
![capture d'écran_25](https://user-images.githubusercontent.com/40635814/80609342-41810e80-8a38-11ea-957f-aba156c8c4b3.png)

**Currency in USD $**
![capture d'écran_26](https://user-images.githubusercontent.com/40635814/80609446-5b225600-8a38-11ea-84a1-949f700e04fc.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Robin-Fischer-PS** [comment]
Note : This bug appears with all currencies (except the default one).

**Comment by Progi1984** [comment]
Fixed by #18993
