### ISSUE TITLE
Pdf Invoice missing all product lines!

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/PrestaShop#18905]
#### Describe the bug

When I generate the PDF invoice, the generated file is missing the lines with product details!

Is not a template folder.
I've replaced for test the /pdf folder with the original one from 1.7.6.5 and 1.7.64.

There is no error in error.log and debug function is not helping.

I really do not want to reinstall Prestashop, I have a lot of customizations made and PDF should be like an external module.
How can I debug this?

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Generate PDF invoice for any order.

![missing](https://user-images.githubusercontent.com/16325429/80646864-2f25c580-8a76-11ea-8ff7-921116e511c1.jpg)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.76.5
* PHP version: 7.2

**Comment by Macrisu** [comment]
Same problem on Delivery slips!

**Comment by florine2623** [comment]
Hi @Macrisu ,

For the invoice : 
Can you heck if you have the files /mails/your_language/order_conf_product_list.tpl ?
If not, could you add these files into the folder /mails/your_language/order_conf_product_list.tpl ?
[Archive.zip](https://github.com/PrestaShop/PrestaShop/files/4556783/Archive.zip)

Regarding the delivery slips : 
Do you have the file pdf/delivery-slip.product-tab.tpl ?
If not, please add it.
[delivery-slip.product-tab.tpl.zip](https://github.com/PrestaShop/PrestaShop/files/4556816/delivery-slip.product-tab.tpl.zip)

Also, if you make any change to the original files,, make sure you do not delete or override any info.

Thanks!

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by Jannick6000** [comment]
My brother-in-law just updated his prestashop installation and now the same thing is happening to his shop. i've checked the files, they are all there, where they should be. And this is both in front-end, and backend.
