### ISSUE TITLE
During the installation of prestashop, 503 appears

### ISSUE THREAD

**Issue by Lingshuirong** [PrestaShop/PrestaShop#18908]
![深度截图_选择区域_20200430182344](https://user-images.githubusercontent.com/35438727/80700300-0baf5900-8b10-11ea-86a5-4297ddfcbc1c.png)

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: V1.7
* PHP version: php7.2
![深度截图_选择区域_20200430182344](https://user-images.githubusercontent.com/35438727/80700337-1d90fc00-8b10-11ea-88a8-0b5cd1546879.png)

**Comment by florine2623** [comment]
Hi @Lingshuirong ,

Please make sure the version of PHP you're using is compatible with the version of PrestaShop you are trying to install.
Here's the link to the compatibility : 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

503 error is a server error, you must check with your host directly.

Thanks!

**Comment by Lingshuirong** [comment]
> Hi @Lingshuirong ,
> 
> Please make sure the version of PHP you're using is compatible with the version of PrestaShop you are trying to install.
> Here's the link to the compatibility :
> https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> 503 error is a server error, you must check with your host directly.
> 
> Thanks!

There is no problem with the compatibility check. All the extensions are installed

**Comment by matks** [comment]
@Lingshuirong This error comes from the server, not PrestaShop. See https://airbrake.io/blog/http-errors/503-service-unavailable

The server you are using seems either unfit for PrestaShop or not properly configured. Maybe try another host ?
