### ISSUE TITLE
Prestashop: Seo product changes are not preserved

### ISSUE THREAD

**Issue by bruno-rc** [PrestaShop/PrestaShop#18906]
Hello guys,

once the product is loaded and I make any changes in the form of the Seo product, it behaves as the saving was successful, but I update F5, the save is not stored and returns as before

Prestashop version 1.7.6.4! 
Php 7.1 T

- i tried cleaning cache
- in debug mode "no error"
- tried to update to version 1.7.6.5
- disable seo friendly and activate

Is there a method to check if something database side or some file has been removed and maybe restore it?
thanks to those who can give me some advice :)

**Comment by florine2623** [comment]
Hi @bruno-rc ,

Please upgrade to PHP 7.2 first and try again.

I couldn't manage to reproduce your issue. Here's a screen record : 
https://drive.google.com/file/d/1s-fH0W9ooWFFmEPLclC0SBrc_f2E_K9y/view

Thanks!

**Comment by bruno-rc** [comment]
Hi thanks for the answer, I tried to increase the php to other versions without, no results!
In my case I respect your video, even when I change the description or the meta title of the SEO area, it gives me confirmation that it has saved the changes but as soon as I update the changes there are not!

**Comment by florine2623** [comment]
Do you have errors when you open the console ?
Is that a fresh install or have you migrated from a previous version ?

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by bruno-rc** [comment]
Thanks everyone for the various answers, I solved it ..
PrestaShop SEO expert v3.2.9 by turning it off he started saving again
