### ISSUE TITLE
Webservices: udpating stock available do not call Hook::exec('actionUpdateQuantity'

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#18912]
my project prestashop version 1.7
and I'm Webservices API 
I experienced, that Prestashop does not call Hook::exec('actionUpdateQuantity',...) when one puts (HTTP PUT) new quantity of a product using webservice request to the resource <stock_availables>. In my opinion, it should.
plz reply
@khouloudbelguith

**Comment by florine2623** [comment]
Hi @dharmendravirasat ,

What exact version of PS are you using ?
What version of PHP are you using ?
Could you share the exact steps to reproduce the issue please ?

Thanks!

**Comment by dharmendravirasat** [comment]
Prestashop version 1.7.6.5 
PHP 7.3
My catalog on Prestashop is managed by an external service (an external website) that uses the Prestashop API to publish the products and manage the quantities of the products.
and I have a custom module.
In module using hook actionUpdateQuantity 
If I use an external service to modify the quantities of the products (via API), this module does not work
@florine2623 @khouloudbelguith 
plz reply 
thanks

**Comment by dharmendravirasat** [comment]
I have checked the issue is id_product_attribute value not coming when I using Webservices API 
In hook actionUpdateQuantity params in don't have a value of id_product_attribute
every time coming id_product_attribute=0;
kindly suggest the solution to resolve query
plz reply 
thanks

**Comment by florine2623** [comment]
Hi again @dharmendravirasat ,
Could you provide the exact steps to reproduce your issue ? If that issue can be reproduced, we will be able to help you.
Thanks!

**Comment by dharmendravirasat** [comment]
It's simple
I'm not getting id_product_attribute value.
(I have custom module ) in have a hooks 
actionUpdateQuantity  in params id_product_attribute  value is blank/0 when I update product stock quantity with Webservice API

**Comment by BenTen** [comment]
Is it the same case?
https://github.com/PrestaShop/PrestaShop/pull/13213

**Comment by florine2623** [comment]
Hi @BenTen & @dharmendravirasat ,
Yes, it seems like your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/13006.
This issue is getting fixed. Please follow the PR https://github.com/PrestaShop/PrestaShop/pull/13213 to know where it's at.
This is a duplicate, so I will close your issue.
Thanks!

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/13006

**Comment by BenTen** [comment]
@dharmendravirasat
