### ISSUE TITLE
BO - Error when viewing an order with custom product made on secondary shop

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18913]
#### Describe the bug

In a "All shops" context, when trying to display an order made on a secondary shop (not the default one), with a customized product in the order, there is an error.

#### Expected behavior

Order should be displayed as usual

#### Steps to Reproduce

On BO, configure : 
1. Multistore ON
2. A second shop
3. On the second shop context, configure a customizable product

On FO : 
4. Make an order with the customizable product

Back on BO : 
5. In "All shops" context, try to see the previously created order details : An unexpected error occurs
6. In "Second shop" context : It's OK.

In 1.7.6 it was OK.

**Screenshots**

https://drive.google.com/file/d/1FdSglE_TAkBT8TKqYI9PXPHXItUT6CeJ/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #18923
