### ISSUE TITLE
BO - Can't upload a child theme

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18914]
#### Describe the bug

After creating a child theme I try to upload it in my back office 

#### Steps to Reproduce

1. Go to Appearance -> Theme & logo -> Advanced customization
2. Click on upload a theme child
3. Select the child theme in the issue
[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/4558401/child_classic.zip)

**Screenshots**

1.7.7.0
<img width="1265" alt="Capture d’écran 2020-04-30 à 14 46 57" src="https://user-images.githubusercontent.com/3034677/80712565-6b970700-8af2-11ea-852e-5c3758c90bf8.png">

1.7.6.5
<img width="1268" alt="Capture d’écran 2020-04-30 à 14 46 50" src="https://user-images.githubusercontent.com/3034677/80712621-810c3100-8af2-11ea-8df2-67705e762404.png">

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #19032
