### ISSUE TITLE
ps_contactinfo module improvements

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [PrestaShop/PrestaShop#18928]
**New description**

I'd like to extend the original issue, the original issue title is flexible enough to make this seem possible.

**Is your feature request related to a problem?**
- The phone number provided to front page by module ps_contactinfo is not clickable. Using smartphone it is comfortable that phone number is active, the same as email address.
- The eMail Address should be encoded to be protected against SPAM bots

**Describe the solution you'd like**
- enclose the phone number in <a> tags
- For eMail Address make use of Smarty mailto & encode function for better spam bot protection (see #9180)

**Alternatives you've considered**
none

**Additional context**
none

**Original description :**
The phone number provided to front page by module ps_contactinfo is not clickable. 
Using smartphone it is comfortable that phone numer is active, the same as email address.

**Comment by florine2623** [comment]
Hi @Laimonas-Mituzas ,

Thanks for the suggestion, I will let our product team know about your request.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team !

What do you think about this improvement on module ps_contactinfo ?
On v3.1.0, on mobile, phone number and email can't be clicked to shoot an action.

Thanks!

**Comment by LouiseBonnard** [comment]
Nice improvement, @Laimonas-Mituzas, thanks! Indeed, when on a desktop device, the email address is clickable, it makes sense to allow the same when on a mobile device (including the phone number).

**Comment by gabrielobleite** [comment]
Still need to be done?

**Comment by ziegenberg** [comment]
I'd like to extend the original issue, the original issue title is flexible enough to make this seem possible.


#### Is your feature request related to a problem?

- The phone number provided to front page by module ps_contactinfo is not clickable. Using smartphone it is comfortable that phone number is active, the same as email address.
- The eMail Address should be encoded to be protected against SPAM bots

#### Describe the solution you'd like

- enclose the phone number in `<a>` tags
- For eMail Address make use of Smarty mailto & encode function for better spam bot protection (see #9180)

#### Alternatives you've considered

none

#### Additional context

none

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,

FYI, part of this issue is fixed by @henri9813 's PR : #25067
