### ISSUE TITLE
Create order : Voucher gift and gift not displayed

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18920]
#### Describe the bug

On create order, when adding a gift voucher, the voucher is not displayed in voucher list, and the gifted product is not displayed in product list.

#### Expected behavior

Behavior is described in specification : 
https://github.com/PrestaShop/prestashop-specs/blob/MatShir-create-order/back-office/orders/orders/Create%20new%20order.md#iii-voucher

#### Steps to Reproduce

1. Go to Discount
2. Create a voucher with a gift (any product)
3. Go to order, create an order
4. Add a product to the order, then add the gift voucher
5. Voucher is not displayed in voucher list, and gifted product is not displayed in product list.
6. When creating the order, the gift product is in the order, so it's "only" a display bug.

**Screenshots**

https://drive.google.com/file/d/19M0mv47F8_JyI2q0ygz_TnmD56fr946t/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matthieu-rolland** [comment]
This PR is blocked because we can't reproduce it on the 1.7.7.x branch

It's only on the beta build. (Edit by @Robin-Fischer-PS )
