### ISSUE TITLE
New front controller for overrided module throws Not Found page

### ISSUE THREAD

**Issue by didacrios** [PrestaShop/PrestaShop#18921]
#### Describe the bug

In order to maintain an original module we decided to override, but arised the need for creating custom front controller to handle post requests.

The Prestashop Dispatcher does not found the controller due to the following lines:
https://github.com/PrestaShop/PrestaShop/blob/c7237f5ae32a0a7130bda19e9b45facda4850cc9/classes/Dispatcher.php#L389-L401

#### Expected behavior

The dispatcher only search for module controllers,  and do not look into overrided ones if any, it should search in the overrided dir too.

#### Steps to Reproduce

1. Override an existing module
2. Create a new front controller in the overrided module that not exists in the original module
3. Access to the url from the new front controller
4. See error 404

#### Additional information

* PrestaShop version: 1.7.4.1
* PHP version: 7.2.19

**Comment by PierreRambaud** [comment]
Thanks for your suggestion @didacrios  but the override system is progressively going away, so we're not going to implement this feature as requested. IMO You should have a look on the devdoc to implement your own controller: https://devdocs.prestashop.com/1.7/modules/concepts/controllers/
