### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#18933]
Before I upgrade to 1.7.6.5 I made a back up from my store incl. DB.

My store is ever since not performing well, so I decided to see if everything would work better on a other server.

When I want to restore the back-up in CPANEL, I get this error:

SyntaxError: Unexpected token < in JSON at position 0

I can see in MYPHPadmin that the database is partially recovered, but that the amount of rows are off from the original. 

How to solve this?

Prestashop 1.7.6.5
PHP 7.2.30

**Comment by Progi1984** [comment]
Hi, It seems that it's a hosting provider problem. Please contact your hosting provider for checking and repairing your database. Thanks

**Comment by 01park** [comment]
No its not a hosting problem. I have more PS site on this host, and they back up perfectly.

Database is not showing any repair issues. 

Something in the db is causing the issue.

**Comment by Progi1984** [comment]
I have bad understood your problem. Sorry. Have you checked the import file and see where the problem was ?

**Comment by 01park** [comment]
The backup file is the full database. I use Cpanel to make a backup and use Cpanel to restore this on the second server. During the restore process the error appears. 

To make sure it was not the server. I build a new prestashop and migrated all information from Store A to Store B. I don't like this process because it does not actual transfer all data 100% correctly, for that I prefer to make a backup and restore this.

Do you know how I can detect the error in the database? Could it be caused by installed Modules ( although I tried with most of them off ).

**Comment by florine2623** [comment]
Hi @01park ,
Did you use 1-click upgrade to upgrade your website ?
If yes, there's a log file, you can see on there if any errors occurred during migration.
Thanks

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
