### ISSUE TITLE
can't enable cache using memcached

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#18934]
#### Describe the bug

Try to enable cache (with memcached server) result in butto show "OFF" again after save
#### Expected behavior

Cache button need to show YES

#### Steps to Reproduce

Go to cache, > yes > select memcached > add server > save. 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/24798703/80823971-d5400f80-8bdd-11ea-8a4a-cdff14760329.png)

AFTER HIT SAVE AND PAGE RELOAD:

![image](https://user-images.githubusercontent.com/24798703/80823991-dec97780-8bdd-11ea-8bf8-95a2b794908f.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sarahdib** [comment]
hello @matteolavaggi 

Did you install memcache pecl in your server?

Thank you

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
