### ISSUE TITLE
error displaying multiple images in one product

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18935]
#### Describe the bug

When a product has multiple images, a carousel is created with two arrows on the sides.
this carousel, in google chrome if you press the left arrow an error is created in which the images are passed infinitely

#### Expected behavior

same function as the right arrow

#### Steps to Reproduce

1. Go to a product
2. Click on left arrow
3. See error

**Screenshots**

https://youtu.be/regjYRyjWM8
https://youtu.be/sCV_RynDnDo

#### Additional information

* PrestaShop version: 1.7.6.4 - 1.7.7
* PHP version: 7.2.29

**Comment by alfonsolr09** [comment]
the error keeps happening in version 1.7.7

**Comment by Progi1984** [comment]
Hi @alfonsolr09,

Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!

**Comment by alfonsolr09** [comment]
@Progi1984 try multiple images in google chrome

**Comment by alfonsolr09** [comment]
important this error only happens in google chrome

**Comment by Progi1984** [comment]
@alfonsolr09 We try to reproduce in local. But don't succeed. Which version of Google Chrome do you have ? Have you tried on an another computer ?

**Comment by alfonsolr09** [comment]
Yes

**Comment by alfonsolr09** [comment]
https://github.com/PrestaShop/PrestaShop/issues/18968#issuecomment-624707940
