### ISSUE TITLE
Disable maintenance mode for BO-logged in users

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18932]
#### Is your feature request related to a problem?

It's annoying to add ip addresses to exceptions every day/hour my public ip changes.

#### Describe the solution you'd like

It would be good to automatically show FO to users, that are logged in BO.

Or add it as an option - “Enable store for logged in employees”.

#### Specifications

https://github.com/PrestaShop/prestashop-specs/pull/183/files

**Comment by Gipielle** [comment]
Right !

**Comment by LouiseBonnard** [comment]
Hi @Hlavtox, thanks for this nice improvement idea! It is because you have dynamic IP addresses, right?

@PrestaShop/prestashop-core-developers, would it be possible to enable the same profile's different IP addresses to access the front office when a store is in maintenance?

**Comment by Hlavtox** [comment]
@LouiseBonnard Yes, it's using IPv6 and changing all the time...

1. We could add a checkbox to Maintenance settings:

"Enable store for logged in employees" / "This setting will automatically display the store to logged in employees, even if the shop is in maintenance mode".
This checkbox would change a config value of, for example, **PS_MAINTENANCE_ALLOW_EMPLOYEES**

2.  We could do something like following in **classes/controller/FrontController::displayMaintenancePage:**

```
// If employee is logged in and it's allowed to let them in.
if (isset($this->context->employee) && Configuration::get('PS_MAINTENANCE_ALLOW_EMPLOYEES') === true) {
  return;
}
```

**Comment by PierreRambaud** [comment]
@LouiseBonnard Everything is possible.
We can add a checkbox and I think the @Hlavtox fix is right, there is nothing complicated here :)

**Comment by Hlavtox** [comment]
@PierreRambaud I tried it and it could not be done this way, unfortuantely. :( 

$this->context->employee is empty when accessing it in that file...

**Comment by PierreRambaud** [comment]
> @PierreRambaud I tried it and it could not be done this way, unfortuantely. :(
> 
> $this->context->employee is empty when accessing it in that file...

I'm sure it's not complicated, the employee is not available when we are outside the admin directory, but we can change id if needed.

**Comment by Hlavtox** [comment]
@PierreRambaud If it's not complicated, good.

BUT, we need to be careful when we do it, because there are some pieces in the code that detect if it's BO or FO by this variable `if (isset($this->context->employee))`. I had a module that added empty Employee object to **$this->context->employee** and it fucked up half of the system, payment modules didn't work etc... 😄

**Comment by PierreRambaud** [comment]
> @PierreRambaud If it's not complicated, good.
> 
> BUT, we need to be careful when we do it, because there are some pieces in the code that detect if it's BO or FO by this variable `if (isset($this->context->employee))`. I had a module that added empty Employee object to **$this->context->employee** and it fucked up half of the system, payment modules didn't work etc...

:scream: Ok so it's maybe not a good first issue :sweat:

**Comment by Hlavtox** [comment]
Implemented in https://github.com/PrestaShop/PrestaShop/pull/30169
