### ISSUE TITLE
Back Office Notification Icon includes Data of deactivated Settings

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#18938]
Hello,

using PrestaShop 1.7.6.4,

everything works.

 

But in the Back Office, top right corner, where your notifications with Last Orders/Messages, my Icon does not resett and always claims there is something. When I click on it, no Messages, No Notifications, no Last Orders that are not marked.

I found the reason for it.

Menu - Configure  -> Advanced Parameters -> Administration

Ive set Notifications On for new Messages and Orders, but Off for new Customers.

But, he still counts the deactivated numbers into the icon.

So the issue is, that PrestaShop Devs need to exclude these datas, if the setting is deactivated!

Thanks

**Comment by carlfriedrich** [comment]
Is there a change that this fix is backported to 1.7.7 ?

**Comment by carlfriedrich** [comment]
@Progi1984 Is there a chance that this fix gets backported to 1.7.7 ?

**Comment by Progi1984** [comment]
@carlfriedrich I don't think so. Only regressions can be added in a patch version for 1.7.7.x.

**Comment by carlfriedrich** [comment]
@Progi1984 Well, isn't that one? It's quite irritating to have the notifications show a number constanty when there actually is none.

**Comment by carlfriedrich** [comment]
@Progi1984 So would you accept a merge request to fix this in 1.7.7.x?
