### ISSUE TITLE
Module Section Category sorting "broken" after Updating Modules

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#18939]
Hello,

using PrestaShop 1.7.6.4,

in the last couple of days there was an Upgrade Release of Link list (I had 3.0.4. if I remember correct) to 3.1.0 and some other PrestaShop Module, I think it was Contact Form from 4.XX to 4.1.1.

After upgrading, my Module Manager in the Backend is somehow broken:
No Module pre sorted into a Category anymore

All Modules now are sorted into 2 Categories:
Theme modules
Other

Empty Categories:
Administration
Design & Navigation
Promotions & Marketing
Product Page
Payment
Shipping & Logistics
Traffic & Marketplaces
Customers
Facebook & Social Networks
Specialized Platforms 

The Shop still works as before, and every module works.
As I did not made a full Backup because these Updates seemed not critical, I can not make any statement of how to reproduce this situation or what exactly triggered it, or any log.

EDIT: I could make out that this is a user-related issue.
I created a different User with different User Group and different Permissions, and with this user the Module Manager looks healthy and sorted properly.

Thanks

**Comment by Progi1984** [comment]
@6xthFNGR It may be a problem with connection with Addons (which permits to fetch categories). If i remember, there is a cache (24h) before refreshing. Could you empty your cache or check it a new time ? Thanks

**Comment by pitkz** [comment]
Hello,

Caching was disabled and cleared several times. Sadly, no impact.
Have you seen my EDIT, explaining that new User Accounts/Groups do not suffer the same impact?

What - User specific - Settings could be the reason for the issue?

Thanks you

**Comment by pitkz** [comment]
Hello,

well, I upgraded to 1.7.6.5, cleared the cache a dozens of times, deactivated caching entirely and what not.
I could not fix it.
Today I log into the Shop: Every module is sorted again.
Cant say why, as this is no predictable behavior.

Hope you can fix it futurewise.

**Comment by Matt75** [comment]
It's fixed in 1.7.7, see https://github.com/PrestaShop/PrestaShop/pull/16658

**Comment by pitkz** [comment]
I think this issue could maybe have been due to CacheAPC,
as the Bug cleared itself without intervention, this would make sense to me:
#19174 

Thanks
