### ISSUE TITLE
Admin Password recovery page - BO 

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#18930]
In BO page, if you forgot password and click recover password, the message after email sent shows in RTL

- Go to admin login page
- Click recover password
- Insert admin email and click sent
- See pop message of sucess

### PS 1.7.6.5
PHP 7.2

**Comment by Progi1984** [comment]
Hi @Borgas 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by florine2623** [comment]
Hi @Borgas ,
I can't reproduce your issue on PS1.7.6.5.
Here's what I received in Left To Right:
![Capture d’écran 2020-05-07 à 14 40 39](https://user-images.githubusercontent.com/16019289/81295881-63e6dd80-9071-11ea-891b-2aa066d64488.png)
And the message after entering my email address :
![Capture d’écran 2020-05-07 à 14 44 00](https://user-images.githubusercontent.com/16019289/81295785-40bc2e00-9071-11ea-9be1-436557653314.png)

Make sure the language of the BO is configured : 
![Capture d’écran 2020-05-07 à 14 48 39](https://user-images.githubusercontent.com/16019289/81296246-e66f9d00-9071-11ea-8164-9e954acc430d.png)

Thanks!

**Comment by Borgas** [comment]
@Progi1984 maybe was a issue with Firefox
Uninstalled and fresh install of firefox and no issues with BO recovery acess

Closed!

**Comment by Progi1984** [comment]
Thanks @Borgas :)
