### ISSUE TITLE
Panier avec produits n'existant plus

### ISSUE THREAD

**Issue by jerome77oak** [PrestaShop/PrestaShop#18931]
Bonjour,

Je vous expose le soucis que je rencontre.

Une cliente ajoute des produits dans son panier mais ne finalise pas sa commande. Son panier et donc garder en l'état par le site.

La commerçante supprime (met hors ligne) un des produits de ce dit panier car elle ne le fabrique plus.

La cliente revient sur son panier quelques jours plus tard, finalise sa commande...le produit supprimé et quand même commandé!!

(Précision, la commerçante n'utilise pas le système de stock car elle fabrique au fur et à mesure ses produits)

Comment faire en sorte que le passage du panier à la commande, il y ait un contrôle de l’existence du produit? (paramètre?, module?)

Merci d'avance pour votre aide.

On me dit que ce bug n'existait pas avant la version 1.7?

(PS1.7.1.2)

Jérôme

**Comment by florine2623** [comment]
Hi @jerome77oak ,

Please, send your request in English.
English is the norm on GitHub
Thanks!
