### ISSUE TITLE
Customer Reassurance

### ISSUE THREAD

**Issue by BERNARD-EMMANUELLE** [PrestaShop/PrestaShop#18941]
Après avoir mis à jour le module Customer Reassurance, voici ce qui s'affiche:

![REASSURANCE 1](https://user-images.githubusercontent.com/64680799/80858834-5fc75400-8c5c-11ea-8dcd-d77e1f17b70d.JPG)

![REASSURANCE 2](https://user-images.githubusercontent.com/64680799/80858847-71106080-8c5c-11ea-9c11-71a4211bbd95.JPG)

Que dois-je faire?

**Comment by florine2623** [comment]
Hi @BERNARD-EMMANUELLE ,

Please, send your request in English.
English is the norm on GitHub.
Also, what is the version of PrestaShop you are using ?
What is the version of module Reinsurance available in your BO ?

Thanks!

**Comment by BERNARD-EMMANUELLE** [comment]
Prestashop 1.7.1.2 , Customer Reassurance v4.1.1

**Comment by florine2623** [comment]
I can't reproduce your issue.
After I upgraded my module to v4.1.1, here's what I have : 
![Capture d’écran 2020-05-04 à 17 24 52](https://user-images.githubusercontent.com/16019289/80982999-55f44b00-8e2c-11ea-9555-44c630fad69a.png)

Do you have any error on console ? What happens when debug mode in enabled ?

Thanks!

**Comment by florine2623** [comment]
Hi @BERNARD-EMMANUELLE ,
Please answer via GitHub, if you answer by email, I can't see what you wrote.
Thanks

**Comment by BERNARD-EMMANUELLE** [comment]
![debug 1](https://user-images.githubusercontent.com/64680799/81286849-04350600-9062-11ea-9119-c223631fd5dd.JPG)

**Comment by florine2623** [comment]
Could you Reinitialize your module ?

**Comment by BERNARD-EMMANUELLE** [comment]
Yes, but no change.

**Comment by florine2623** [comment]
Do you have any data in your database in table ps_psreassurance ?

**Comment by BERNARD-EMMANUELLE** [comment]
![module](https://user-images.githubusercontent.com/64680799/81318632-d914db80-908e-11ea-8de2-14a1fede4d31.JPG)

**Comment by florine2623** [comment]
Hi @BERNARD-EMMANUELLE ,
These are the files of your Reassurance module.
Is there a way you could screenshot the table ps_psreassurance in your database directly ?
Thanks!

**Comment by avionicom** [comment]
Hello, I've the same @BERNARD-EMMANUELLE issue. PS 1.7.6.5 and module 4.1.1.
Following last upgrade, noticed that no icons where shown. So tried to restore the module and also uninstall and reinstall again. The icons are now shown, but are different from the original ones and also the colour is not anymore black, but a rose one. What happened?

**Comment by avionicom** [comment]
![immagine](https://user-images.githubusercontent.com/2458781/82566342-0deb5d00-9b7c-11ea-9c9a-4028fbdf1add.png)

**Comment by avionicom** [comment]
I noted in database that have both tables: ps_psreassurance (image posted) and also ps_reassurance

**Comment by avionicom** [comment]
![immagine](https://user-images.githubusercontent.com/2458781/82566656-86521e00-9b7c-11ea-881c-e8c7c0583d47.png)
this is ps_reassurance table, probably related to the old module version 3.0.1?

**Comment by florine2623** [comment]
Hi @avionicom ,
Yes, ps_reassurance table is related to the old version.

The rose color is the color attributed to these icon.
If you want to change them, you need to go to the Appearance tab :
![Capture d’écran 2020-05-25 à 12 15 53](https://user-images.githubusercontent.com/16019289/82803875-92422680-9e81-11ea-9166-bf858fe9fccb.png)
Thanks!

**Comment by florine2623** [comment]
Hi @BERNARD-EMMANUELLE ,
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by Dupflo** [comment]
First time I saw that, I update 1.7.6.1 to 17.6.5

- First behavior : blockreassurance was totally reset and downgrade to an old version but look at what I saw on modules pages 

![image](https://user-images.githubusercontent.com/39828779/84321732-0237f880-ab74-11ea-9c57-09b951783a65.png)

![image](https://user-images.githubusercontent.com/39828779/84321749-0a903380-ab74-11ea-9efa-4705a77b2242.png)

Then I remove the module and I tried to reinstall it by the addons and by zip file but I can't

<img width="1785" alt="Capture d’écran 2020-06-10 à 23 39 12" src="https://user-images.githubusercontent.com/39828779/84321597-c0a74d80-ab73-11ea-9ece-ee0e458ec213.png">

**Comment by Matt75** [comment]
Can you check in var/logs if you find an error line related to this module ?

**Comment by Dupflo** [comment]
> Can you check in var/logs if you find an error line related to this module ?

No error inside
