### ISSUE TITLE
Translations - Copy Feature broken, wrong directory path to theme/classic/lang

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#18940]
#### Describe the bug

The copy feature in International > Translation does not work.

#### Expected behavior

I should be able to copy one language to another

#### Steps to Reproduce

1. Go to Design > Theme & Logo > Advanced customization
2. Download current theme
3. Upload child theme
4. Go to 'International > Translation
5. Scroll down to 'Copy'
6. Copy from classi to chlid_classic
7. See error

**Screenshots**

![Capture d’écran 2020-05-14 à 12 12 44](https://user-images.githubusercontent.com/16019289/81922400-58993200-95dc-11ea-9c00-3f700eaa89ee.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by TristanLDD** [comment]
Hi @6xthFNGR, thanks for your report

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by pitkz** [comment]
Hello,

I would be happy to provide you such info, but thats too much of a work!
Screenshots: Its will just show you the red error msg box with the msg I told you, that the is trying to look for "lang/en-EN.php" but can not find it.

As I use standard Theme and a completly unmodified PS, this should be easy to reproduce.

Debug Mode Report may be something I can try to create the next time I maintance the shop.


PS: 1.7.6.4 to 1.7.6.5 minimum
PHP version: 7.1.33
MySQL version: 8.0.19

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
Sorry if that's too much work for you !
Could you at least give the exact steps to reproduce your issue ?
Thanks!

**Comment by pitkz** [comment]
@florine2623 
I would rather ask you to not close some other threads that are urgent claiming to wait for 1.7.7 and now not replying anymore, rather than asking for the reproducing steps for this matter because this isnt urgent like the other ;o)

Usual procedure without any special flavor that is why I didnt felt a need to provide them.
Here you go:

Install stock PS 1.7.6.4 or 1.7.6.5,
Go to your Theme Menu, download the Theme, do not add anything to the Theme, Reupload it,
Go for your Translation Menu and Copy any Language from classic to your new child theme..
Doesnt work.
Prompts wrong file directiories, see first post.

Ty

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
Beta version is out now, you can try it ! 

Please stay tuned regarding this issue.
Thanks

**Comment by khouloudbelguith** [comment]
Hi @6xthFNGR,

Sorry for the late response.
We are aware of this issue, it is added to our bug roadmap.
Your issue is a duplicate of #16132.
So, I close this ticket, feel free to open a new one when needed.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #16132
