### ISSUE TITLE
[BO][IMPROVEMENT] Allow check all in product combinations

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#18949]
## Is your feature request related to a problem?

It is true that life expectancy has increased in recent years. But we still have to manage our time wisely.

#### Imagine the following situation : 

![improve_combinaison](https://user-images.githubusercontent.com/16455155/80908797-2f96b880-8d23-11ea-8585-677cc30175ec.png)

The user wishes to generate all the possible combinations (**sizes**, **colors**, **etc etc**)

- **size** : (4 values)
- **colors** : (14 values)
- **etc etc** : (N values)

In this case, the number of boxes he must check  =  **4 + 14 + N**

## Describe the solution you'd like

Consider the same situation but this time with a check all :

![improve_combinaison (1)](https://user-images.githubusercontent.com/16455155/80909370-0cbad300-8d28-11ea-9b33-398d79390740.png)

In this case, the number of boxes he must check = **3**

**Comment by alfonsolr09** [comment]
@PululuK How do you have version 1.7.7?

**Comment by PululuK** [comment]
> @PululuK How do you have version 1.7.7?

Hi @alfonsolr09 

I'm using develop branch ... See https://devdocs.prestashop.com/1.7/basics/installation/

Thanks

**Comment by Hlavtox** [comment]
Yes! Just yesterday, I was making a product - a tshirt with an alphabet letter on it... + few colors, few sizes. Good 35 checkboxes to check. 😃

**Comment by marionf** [comment]
Seems a nice idea @PululuK 
FYI @MatShir

**Comment by Progi1984** [comment]
Fixed by @jolelievre & @NeOMakinG in #23865
