### ISSUE TITLE
Duplicate Order

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#18946]
Hi
When I received an order it's tagged with payment accepted, but when I change the status to being prepared, "en cours de preparation" I noticed in payment section that order is a duplicate message 

Attention 900 MAD payé au lieu de 450 MAD 

**Screenshots**
![image](https://user-images.githubusercontent.com/11594433/80868516-bd729500-8c8a-11ea-8dea-12e472b0a2f7.png)

![image](https://user-images.githubusercontent.com/11594433/80868525-c7949380-8c8a-11ea-9c23-724303a53653.png)

#### Additional information
* Version de PrestaShop : 1.7.6.4
* Version du logiciel serveur : Apache
* Version de PHP : 7.2.30
* Limite de mémoire : 100128M
* Temps maximal d'exécution : 9000
* Taille max. pour envoi de fichiers : 200M

**Comment by Matt75** [comment]
Can you check this issue : https://github.com/PrestaShop/docs/issues/508

**Comment by rdy4ever** [comment]
I think both statuses set the order as being paid. It's kindof a bug, but to mitigate, set just one of them to do this.

**Comment by colinegin** [comment]
Hello @go-sudo ,

did you change anything in the configuration of "payment accepted" or "processing in progress" statuses ?

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
