### ISSUE TITLE
Hook missing/misspelt in DB: (actionAuthenticationBefore)

### ISSUE THREAD

**Issue by hamsn** [PrestaShop/PrestaShop#18945]
#### Describe the bug

**CustomerLoginForm.php** contains **actionAuthenticationBefore**
But the database hooks table does not contain **actionAuthenticationBefore**, 
instead there is **actionbeforeauthentication** probably misspelled?

#### Expected behavior

Using **hookActionAuthenticationBefore** in code does not fire the hook.
Renaming it in the DB hooks table from actionbeforeauthentication to actionAuthenticationBefore, fixed the issue.

#### Steps to Reproduce

Calling function hookActionAuthenticationBefore ( ) does nothing

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by 01park** [comment]
Hi,

I was just reading this, where exactly can this be changed?

**Comment by hamsn** [comment]
The references are found:
**in install folder:**
data/xml/hook_alias.xml
**after installation:**
in db: ps_hooks table

Also found this prefix in upgrade sqls

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/12578
