### ISSUE TITLE
1.7.6.4 (1/1) ContextErrorException Warning: Declaration of Cart::getProducts

### ISSUE THREAD

**Issue by oksican** [PrestaShop/PrestaShop#18943]
(1/1) ContextErrorExceptionWarning: Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true)
--
in Cart.php
at ErrorHandler->handleError(2, 'Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true)', '/home/canmulti/public_html/eticaret/override/classes/Cart.php', 0, array('className' => 'Cart', 'classDir' => '/home/canmulti/public_html/eticaret/'))in PrestaShopAutoload.php line 152
at require_once()in PrestaShopAutoload.php line 152
at PrestaShopAutoload->load('Cart')in DebugClassLoader.php line 159
at DebugClassLoader->loadClass('Cart')
at spl_autoload_call('Cart')in FrontController.php line 410
at FrontControllerCore->init()in Controller.php line 273
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by oksican** [comment]
Thanks;

I'm waiting for help

**Comment by florine2623** [comment]
Hi @oksican ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by florine2623** [comment]
When you disable your overrides, do you still have this issue ?

**Comment by florine2623** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by anthonike** [comment]
Hola muy buenas tardes, tengo el mismo problema

en ErrorHandler -> handleError ( 2, 'Declaración de Cart :: getProducts ($ refresh = false, $ id_product = false, $ id_country = NULL, $ fullInfo = true) debería ser compatible con CartCore :: getProducts ($ refresh = false, $ id_product = false, $ id_country = NULL, $ fullInfos = true, bool $ keepOrderPrices = false) ',' /home/larider/web/laridershop.com/public_html/override/classes/Cart.php ', 0, matriz ( 'className' => 'Carrito', 'classDir' => '/home/larider/web/laridershop.com/public_html/') )

pueden ayudarme? gracias
