### ISSUE TITLE
Meta refurbished

### ISSUE THREAD

**Issue by fbsoft** [PrestaShop/PrestaShop#18942]
#### Describe the bug

I had inspected my product page, on classic theme, and i found that itemProp, itemCondition has the meta condition as refurbished.

#### Expected behavior

To show the real condition of the item

#### Steps to Reproduce

1. Create product 
2. Assign condition
3. Add attributes with different prices

**Screenshots**

![image](https://user-images.githubusercontent.com/5354671/80859784-fd764f80-8c6b-11ea-957f-0d43fd9d3507.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

Solution: Upon inspecting the code, it seems that $product.condition comes out blank, therefor skipping directly to the else part

        {if $product.condition == 'new'}
        <meta itemprop="itemCondition" content="new" />
        {else if $product.condition == 'used'}
        <meta itemprop="itemCondition" content="used" />
        {else}
        <meta itemprop="itemCondition" content="refurbished" />
        {/if}

temp solution: Change order of if

**Comment by eternoendless** [comment]
Hi @fbsoft where did you find that piece of code? Because I can't find it anywhere in  the project: https://github.com/PrestaShop/PrestaShop/search?q=itemCondition&unscoped_q=itemCondition

**Comment by fbsoft** [comment]
Hey, yes indeed, i've dl the files from git and it's not there.I found it in my Install in themes/classic/templates/catalog/_partials/miniatures/product.tplBut this is not a fresh Install... I did an upgrade using 1-click upgrade plugin, from 1.7.4... 3 I think, to 1.7.6.4. After a few days I've noticed this error, and I think that the files from the classic theme were left intact, and not upgraded, therefore the error.. Sry, it's my bad, in regards to this.CheersOn May 7, 2020 13:41, Pablo Borowicz <notifications@github.com> wrote:
Hi @fbsoft where did you find that piece of code? Because I can't find it anywhere in  the project: https://github.com/PrestaShop/PrestaShop/search?q=itemCondition&unscoped_q=itemCondition

**Comment by colinegin** [comment]
Hello @fbsoft ,

Thanks for getting back to us. As you found where the error is coming from, I close the issue but feel free to open a new one if needed.

Thanks !
