### ISSUE TITLE
Order preview broken on develop

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#18957]
#### Describe the bug

Order preview broken on develop : it does not open. Errors in console

#### Expected behavior

Order preview works

#### Steps to Reproduce

1. Go to Orders listing
2. Click, next to the ID, on the small arrow (see screenshot) it should open an order preview, it does not

**Screenshots**
<img width="109" alt="Capture d’écran 2020-05-04 à 11 55 09" src="https://user-images.githubusercontent.com/3830050/80954789-570e8380-8dfe-11ea-8f50-10a344c9d078.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment]
Error in console:
```
order.bundle.js?1.7.7.0:388 Uncaught TypeError: this.lock is not a function
    at d.value (order.bundle.js?1.7.7.0:388)
    at HTMLSpanElement.<anonymous> (order.bundle.js?1.7.7.0:388)
    at HTMLSpanElement.dispatch (main.bundle.js:49)
    at HTMLSpanElement._.handle (main.bundle.js:49)
value @ order.bundle.js?1.7.7.0:388
(anonymous) @ order.bundle.js?1.7.7.0:388
dispatch @ main.bundle.js:49
_.handle @ main.bundle.js:49
```

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19947
