### ISSUE TITLE
Slow Order List Backoffice

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#18956]
Go to Orders
The page isn't completly loaded until the PKI data isn't loaded.
For some strange reason it takes a lot of time.

What can I do to troubleshoot this?

PrestaShop version: 1.7.6.4

**Comment by Progi1984** [comment]
Hi @seederp2p 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by seederp2p** [comment]
PHP 7.2.24-0ubuntu0.18.04.4
PrestaShop version: 1.7.6.4
No apache errors
Java script console:
jquery-1.11.0.min.js:4 XHR finished loading: POST "https://mywebsite.whatever/whatever/index.php?controller=AdminGformrequest&token=d2ef186…".
jquery-1.11.0.min.js:4 XHR finished loading: POST "https://mywebsite.whatever/whatever/index.php/common/notifications?_token=0MhNU91LJj0A1xDvRY_aPbw2yFat9hkpn7H4sVqPEFY&rand=1588598651054".
content.js:5 --------init----------- https://mywebsite.whatever/whatever/index.php?controller=AdminOrders&token=b1a995e…
util.js:232 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
jquery-1.11.0.min.js:4 XHR finished loading: GET "https://mywebsite.whatever/whatever/index.php?controller=AdminStats&token=873…jax=1&action=getKpi&kpi=netprofit_visit&rand=1588598651083&_=1588598649198".
jquery-1.11.0.min.js:4 XHR finished loading: GET "https://mywebsite.whatever/whatever/index.php?controller=AdminStats&token=873…jax=1&action=getKpi&kpi=conversion_rate&rand=1588598651067&_=1588598649195".
jquery-1.11.0.min.js:4 XHR finished loading: GET "https://mywebsite.whatever/whatever/index.php?controller=AdminStats&token=873…1&action=getKpi&kpi=average_order_value&rand=1588598651075&_=1588598649197".
jquery-1.11.0.min.js:4 XHR finished loading: GET "https://mywebsite.whatever/whatever/index.php?controller=AdminStats&token=873…ajax=1&action=getKpi&kpi=abandoned_cart&rand=1588598651070&_=1588598649196".
﻿
​
The part that gets to much time to load is this the "getkpi":

conversion_rate: 20 seconds to load
abandoned_cart: 20 seconds to load
average_order_value: 20 seconds to load
netprofit_visit: 7 seconds to load

**Comment by TristanLDD** [comment]
@PrestaShop/prestashop-core-developers  WDYT? Do you manage to reproduce with the provided informations?

**Comment by Progi1984** [comment]
On 1.7.7.x, the page Orders has been completly rebuild and I didn't reproduce your error.

**Comment by seederp2p** [comment]
Just for the record: "Amazing" answer. You reply stating that you didn't find this problem on a DIFFERENT version that it is NOT yet available.

"Top notch" support. I know that this is a "free" product but I've using your platform for many years now and invested a lot on paid modules from your module store.

I don't really think that this is a quality answer. You could have at least provide a workarround.

And by the way this is not an error but a performance issue!!

**Comment by procent85** [comment]
Why it was closed since the problem was not resolved?

@Progi1984  @eternoendless

**Comment by Progi1984** [comment]
@procent85 As I said : 
> On 1.7.7.x, the page Orders has been completly rebuild and I didn't reproduce your error.

**Comment by procent85** [comment]
@Progi1984 
Wait... what does version 1.7.7.0 have in common with the problem described by OP, which has a problem with version version 1.7.6.4? Nothing.
Your answer is totally pointless and did not help in any way to solve the problem

**Comment by matks** [comment]
I am locking this conversation because I can see some heated comments very harsh and that do not comply with our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).

To sum it up:
- this bug will not be fixed on Prestashop 1.7.6
- Order list has been re-built from scratch in incoming version PrestaShop 1.7.7 and it seems bug is gone without implementation ; so we consider this bug is "fixed" in 1.7.7 version
- this is an Open Source Project, not a commercial product, there is no such thing as "free support" ; only people contributing

PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by eternoendless** [comment]
"This issue cannot be reproduced in 1.7.7.0" --> this means the issue has been fixed. There's nothing more to discuss.
