### ISSUE TITLE
BO - View order pagination does not display right number of products

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18959]
#### Describe the bug

At the first access to an order (with minimum 9 products), the pagination is OK, with 8 products. If you change page (to page 2 for example), the last product on page 1 is present at the top of page 2.
If you return to page 1, only 7 products are displayed instead of 8.

#### Expected behavior

Pagination should always display 8 products per page.

#### Steps to Reproduce

1. Create an order with at least 9 different products
2. View the order : First page displays 8 products.
3. Go to page 2 : Last item of page 1 is displayed at top of page 2, it should not
4. Go back to page 1 : Only 7 products are displayed.

**Screenshots**

On my example : "Coussin renard" is displayed at top of page 2, it should not. When back on page 1, it is not displayed, it should.
https://drive.google.com/file/d/17-T7sofE5_ifkv5GDHXRnFqIjTRiOVlM/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #19039
