### ISSUE TITLE
Forgotten block inside migrated Order page : Linked orders

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#18967]
#### Describe the bug

When we migrated Order page, we forgot (because we did not it existed) the "Linked orders" block at the bottom of the page

I can see it in the code but I dont know how to make it appear. Maybe when orders are split ? Apparently in the code, orders are considered to be "brothers" a.k.a "linked" when they share the same reference.

See the code https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl#L1276

⚠️ it seems this "order brothers" concept also impacts payment block
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl#L409

**Comment by matks** [comment]
Reported by @Robin-Fischer-PS

**Comment by colinegin** [comment]
ping @MatShir what should be done with this issue ?

**Comment by matks** [comment]
> ping @MatShir what should be done with this issue ?

Fix it

We forgot about it, but I just assigned it to me and I will do it

**Comment by matks** [comment]
So this is what I found:

- when 2 orders (or more) orders share the same _reference_ and _cart ID_ they are considered orders
- this block appears:
<img width="1216" alt="Capture d’écran 2020-06-10 à 17 37 18" src="https://user-images.githubusercontent.com/3830050/84288541-a0f73180-ab41-11ea-8c23-1b7ccbfb22f5.png">
- also if there is a payment and the amount is not equal to what should be paid, the following warning appears:
<img width="696" alt="Capture d’écran 2020-06-10 à 17 40 49" src="https://user-images.githubusercontent.com/3830050/84288604-b1a7a780-ab41-11ea-97b3-723a67c86b02.png">

**Comment by Progi1984** [comment]
@matks Can we close this issue ?

**Comment by matks** [comment]
> @matks Can we close this issue ?

Yes we can :)
