### ISSUE TITLE
Cart and shipping costs

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#18978]
Hello,

**1.** Is it possible to remove delivery costs in the cart? In the options I can choose as the default way, but customers think, after adding to the cart, that this is the only option.

I add one product to the cart and, for example, PLN 15 courier service. Whatever I set up, the client thinks that this is the only option and does not go to realization.

**2.** Can you, for example, switch the "Delivery method" to the top of the order above: "Personal data"?

There's no way o have delivery options in the cart by the way?

Have a nice day.

**Comment by florine2623** [comment]
Hi @GTriber ,
1. Natively, it is not possible to remote the delivery cost in the cart. But you could hide it with CSS if you wish, the issue with that is that the customer might think that the delivery cost is free altogether.
The delivery cost shown in the cart is the least expensive one for the customer, where he gets to the 3rd step "delivery method", he'll be able to choose whatever carrier he wants.
2. It is not possible either. Delivery method can only be displayed once the delivery address has been saved.
Natively, is it not possible to show all delivery cost directly in the cart. You will need custom dev.

Thanks!

**Comment by GTriber** [comment]
@florine2623 

'But you could hide it with CSS if you wish'

I so wish i could do that. Where i can find it? What to change, delete.

Thank you.

**Comment by colinegin** [comment]
ping @florine2623 for paid support. 
I close this issue, i let you reply to @GTriber
