### ISSUE TITLE
donwload link for Geotargeting does not work - 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#18976]
Hello, 

I like to try the Geotargeting function but the download link for .zip package does not work in my case.

![image](https://user-images.githubusercontent.com/44971218/81052837-75d74d80-8ec4-11ea-8bc6-0f72c18ca757.png)

I there another link or way to get the package? 

Thanks a lot for helping ♥

**Comment by matks** [comment]
@didi-2018 MaxMind has changed their access strategy, now you need to signup to their database. See https://github.com/PrestaShop/PrestaShop/issues/17193
