### ISSUE TITLE
themes/core.js.map #12452

### ISSUE THREAD

**Issue by przemko2000** [PrestaShop/PrestaShop#18973]
Can you please reopen bug #12452?
It was closed due to "Can't reproduce" and after it was closed many people commented that the problem still exists - up to the most current version 1.7.6.5. More information in the original (closed) ticket:
https://github.com/PrestaShop/PrestaShop/issues/12452

**Comment by xmovu** [comment]
Hello,

I'm sorry but I had to recover the store from a working backup as it wasn't functional and we really need the store working properly.

If this happens again, I'll certainly do it.
However, I can tell you that the same products, modules, template, PHP version, Prestashop version etc are now working fine, so it's not exactly easy to reproduce this issue indeed.

**Comment by Hlavtox** [comment]
@przemko2000 Nothing like this is happening on a classic/classic-rocket theme. MAP file errors are there, because in the minified CSS file, there are references to them, but they do not exist.

In #12452, all the errors on the screenshot are caused by buggy leo modules and "apppagebuilder". The developer himself needs to fix it.

**Comment by PierreRambaud** [comment]
Source maps (.map files) are only useful for development/debugging. They help map compressed files to their original source code. They are only used by the development toolbar so their presence or not should have no impact on your shop's performance.

Unfortunately, we are still not able to reproduce on the latest release. If you are working in a development environment, I recommend you to use PrestaShop from the source and not the Zip Archive.
