### ISSUE TITLE
[PHP Compatibility] Unable to Access Translations or add Team Members w/ PHP 7.4

### ISSUE THREAD

**Issue by SemoTech** [PrestaShop/PrestaShop#18970]
#### Describe the bug

Fresh install of PrestaShop 1.7.6.5 and unable to access "Translations" page/section or create any additional accounts if using PHP 7.4

#### Expected behavior

Ability to create Team member accounts in PHP 7.4 given it's current version.

#### Steps to Reproduce

Steps to reproduce the behavior (using Firefox on Mac):

1. Go to 'Advanced Parameters'
2. Click on 'Team'
3. Click on 'Add new employee' top right
4. Fill out form
5. Notice that pull-down/selector for Language is locked in Firefox (displays empty in Safari)
6. Notice that all the options for "Permission profile " are listed and cannot be selected.
7. Press Save
8. Get Error "An unexpected error occurred. [PrestaShopException code 0]"

**Screenshots**

![image](https://user-images.githubusercontent.com/1452100/80998146-6eef0300-8e10-11ea-8957-a6177070d2ff.png)

Had to downgrade accounts to PHP 7.3 and testing that now. 
When is PHP 7.4 compatibility expected?
Thanks! 

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.4

**Comment by alfonsolr09** [comment]
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by alfonsolr09** [comment]
<img src="https://image.prntscr.com/image/oljXupBuTn2F753-zkBdSg.png" />

**Comment by SemoTech** [comment]
Thank you @alfonsolr09 I downgraded to PHP 7.2 for now, and will wait to go to PHP 7.3 once v1.7.7 is out.  Great platform otherwise, well done everyone!

**Comment by alfonsolr09** [comment]
i think 1.7.8 may be compatible with php 7.4
