### ISSUE TITLE
Order page, shipping fee become 0 if id carrier is deleted

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#18971]
1/ make an order with a carrier (not free one)
2/ rename the carrier
3/ change the address of the customer

Shipping fee will be change to 0.00 {currency}

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

**Comment by TristanLDD** [comment]
Hi @BenTen

I did not manage to reproduce the issue with the last version PS 1.7.6.5
I attached a video record:
https://drive.google.com/file/d/16BhNb0Umfdzg0Wcr6CjLWBaZAoprwSqW/view?usp=sharing

Thanks for check and feedback

**Comment by BenTen** [comment]
For some reason shipping fee is set to 0 on my shop and database.

Maybe I forgot a step to reproduce, I need to check it again.

**Comment by colinegin** [comment]
I close this issue as we cannot reproduce your issue.
Feel free to open a new one if you have more information to share with us.
