### ISSUE TITLE
BO Create order - Cannot add a customized product

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18987]
#### Describe the bug

On BO Create an order, when trying to add a customized product, even if all the required fields are filled, there is an error : "Please fill in all the required fields."

#### Expected behavior

This message should only appears when a required field is not filled.

#### Steps to Reproduce

1. Configure a customizable product, with required fields
2. On BO, create an order
3. Add the customizable product to the order
4. Fill all required fields, click on "Add to cart"
5. The following error is displayed : "Please fill in all the required fields."

**Screenshots**

![cannot add custom product](https://user-images.githubusercontent.com/55688534/81077624-82bc6700-8eed-11ea-9418-019831f671d5.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matthieu-rolland** [comment]
The bug is not there anymore in 1.7.7.x
