### ISSUE TITLE
When using bulk import, old combinations are still accesible, even if it no longer exists

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#18994]
The import script is set to drop reset all id's, but when it first had a product on https://www.newvanherck.be/ceinturen/2567-6779-floris-van-bommel-75216-01.html#/17-kleur-blauw/3-materiaal-leer
now it is on https://www.newvanherck.be/ceinturen/2567-7841-floris-van-bommel-75216-01.html

The url used in the breadcrumb is https://www.newvanherck.be/ceinturen/2567-floris-van-bommel-75216-01.html, which remains the same in both cases.

Is there a way the new page is always displayed (using the url of the breadcrumb maybe)?

It is really confusing for customers that the product is still there, but not available and with price 0 EUR

**Comment by TristanLDD** [comment]
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by nielsverhoeven84** [comment]
Tristan, did you check both links?

**Comment by nielsverhoeven84** [comment]
The PS version is 1.7.5.2

It even seems to be that if you modify the second number in the url to something that contains at least 1 letter, it redirects as it should. Only with numbers it shows wrong.

https://www.newvanherck.be/ceinturen/2567-6779-floris-van-bommel-75216-01.html#/17-kleur-blauw/3-materiaal-leer

6779 can be any number, e.g.

https://www.newvanherck.be/ceinturen/2567-4544656456464564655465445665-floris-van-bommel-75216-01.html#/17-kleur-blauw/3-materiaal-leer
