### ISSUE TITLE
Login loop - some customers cannot continue with checkout.

### ISSUE THREAD

**Issue by fruitfreak** [PrestaShop/PrestaShop#19000]
#### Describe the bug

Some customers cannot create an order as guest or with account. 
We're using stock checkout system.
Nor can they login as an existing customer.
It loops at customer login or at a given level in the checkout process - usually after typing name / email -> continue, meaning you can keep filling your information and press continue, it will not continue.

I experienced this myself in chrome - deleting cookies solved it for me. 
But I cannot ask so many customers to do that.
A guess from the reports I get is that around 10% of the customers experience this issue.
Usually it works if / when customers try a different browser - sometimes not.

This issue has existed for a while and during the last few updates - since 1.7.6.X at least.

#### Expected behavior

I expect login / placing orders to go smooth without looping back to login

#### Steps to Reproduce

Put a product in the card > 100 DKK and continue with checkout.
If you get to the payment section it works, in your case. :-)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

Thanks for any help - much appreciated :-)
Kind regards
Ivan

**Comment by fruitfreak** [comment]
Forgot the URL:
https://plante-protein.dk/

**Comment by TristanLDD** [comment]
Hi @fruitfreak 

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I'm truly sorry that we can't help you more about that issue.
Thank you

**Comment by pozen80** [comment]
fixed? same problem. someone can help me?
