### ISSUE TITLE
In Symfony listings, drag-and-drop require "sorting" to be ASC

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19008]
#### Describe the bug

Drag-and-drop on Symfony listings needs the listing to be sorted by ascending positions. Else it is not displayed and not usable (see steps to reproduce).

#### Expected behavior

Drag-and-drop should:
- require position column to be sorted (indeed, if rows are unsorted, "moving a row with drag-and-drop" does not inform the software of the desired ordering) => this should be told to user, right now it's not obvious
- drag-and-drop should work no matter whether column would be sorted ASC or DESC

#### Steps to Reproduce

1. Go to BO, on Design > CMS Page listing
2. Drag-and-drop works: on the left, there is a small blank column where you can grab a handle and move rows
3. Sort listing by descending position: see screenshot below
4. Blank column at the left is not visible anymore. Drag-and-drop does not work

**Screenshots**
<img width="189" alt="Capture d’écran 2020-05-06 à 15 42 17" src="https://user-images.githubusercontent.com/3830050/81184030-3128e080-8fb0-11ea-9672-2f2466c90dfc.png">

**Comment by matks** [comment]
The logic which hides the handle column is in GridPresenter
```
    /**
     * @param GridInterface $grid
     *
     * @return ColumnInterface|null
     */
    public function getOrderingPosition(GridInterface $grid)
    {
        $searchCriteria = $grid->getSearchCriteria();
        /** @var ColumnInterface $column */
        foreach ($grid->getDefinition()->getColumns() as $column) {
            if ($column instanceof PositionColumn &&
                strtolower($column->getId()) == strtolower($searchCriteria->getOrderBy()) &&
                'asc' == strtolower($searchCriteria->getOrderWay())
            ) {
                return $column;
            }
        }

        return null;
    }
```

**Comment by jolelievre** [comment]
This will also probably require some update in the `PositionUpdater` to handle repositioning in both sides, and update the javascript extension so that it informs on the way the grid was ordered (unless it can be detected based on the sent data)

**Comment by jolelievre** [comment]
In product listing, when you filter by category there is this additional Position column as well, when the grid is not order by position the header contains a `Reorder` button:

![Capture d’écran 2020-05-06 à 16 30 35](https://user-images.githubusercontent.com/13801017/81189639-17d76280-8fb7-11ea-96b5-9fc73b581148.png)

Clicking on the button resorts the grid in the expected position, this might a quick and efficient way to improve the UX of this feature

It also adds a `Save and refresh button` to validate the modifications, I'm not sure about this one but it has its advantages (only save after everything is order, a sign request to order everything)

@TristanLDD how do you think we should handle this? inspired from product listing? exactly the same? or something completely different? ^^
(I couldn't find scott's github nickname but of course his advice is also welcomed)

**Comment by matks** [comment]
Looks like issue comes from `position-extension.js` way of computing "new position"
```
    for (i = 0; i < rowsNb; i += 1) {
      rowData = regex.exec(rowsData[i]);
      positions.push({
        rowId: rowData[1],
        newPosition: paginationOffset + i,
        oldPosition: parseInt(rowData[2], 10),
      });
    }
```

It considers "new position is pagination offset plus row number", so if sort is not the right direction, it is mistaken.
