### ISSUE TITLE
[BO] - Error displayed on new address page

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#19001]
#### Describe the bug

When trying to go new address page or edit address page, an error is displayed

#### Expected behavior

Page displayed correctly

#### Steps to Reproduce

**For new address page :**
1. Go to 'BO > Customers > Addresses page'
2. Click on 'Add new address'
3. See error
![image](https://user-images.githubusercontent.com/48441421/81166283-c5387f00-8f93-11ea-93b9-c02f1ddf81d3.png)

**For edit address page :**

From addresses page : 
1. Go to 'BO > Customers > Addresses page'
2. Click on 'edit address'
3. See error
![image](https://user-images.githubusercontent.com/48441421/83002755-b3d01900-a00d-11ea-8c17-a0852aa3c19c.png)

From view customer page
1. Go to 'BO > Customers 
2. Go to view customer with an address
3. Click on 'Click on edit address'
![image](https://user-images.githubusercontent.com/48441421/83003023-06a9d080-a00e-11ea-9178-e41f2e43c68c.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by SD1982** [comment]
Fixed by #19338
