### ISSUE TITLE
Deny orders of out of stock items OR Inactive Products not working

### ISSUE THREAD

**Issue by testakis** [PrestaShop/PrestaShop#19002]
#### Describe the bug

The shopping cart allows checkout with inactive product or product whose quantity is upper than available stock.

#### Expected behavior

If I add a product to cart and don't checkout, then if I go to BO > Catalog > Products and set the product inactive or set its quantity to 0, and then if I go to shopping cart, I will see the product is still in the cart. Then when I click on "PROCEED TO CHECKOUT",  NO error message is appears. And unfortunately the shopping cart allows the customer to complete the order.  

In BO>Shop Parameters> Product Settings> Allow ordering of out-of-stock products: NO
In BO>Shop Parameters> Product Settings> Enable stock management: YES

#### Steps to Reproduce

1. Add a product to cart and don't checkout
2. Go to BO > Catalog > Products and set the product inactive or set its quantity to 0.
3. Then go to shopping cart, you will see the product is still in the cart.
4. Then click on "PROCEED TO CHECKOUT". NO error message is appears.
5. The shopping cart allows the customer to complete the order.
6. I received "backorder paid" indication in backoffice.

In BO>Shop Parameters> Product Settings> Allow ordering of out-of-stock products: NO
In BO>Shop Parameters> Product Settings> Enable stock management: YES

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

The system should deny orders of out of stock items OR Inactive Products not working.
Is there a solutions about this issue?

* PrestaShop version: 1.7.2.3
* PHP version: 5.6.40

**Comment by florine2623** [comment]
Hi @testakis ,

I can't reproduce your issue on PS 1.7.6.5.
Having the same configuration as you :
![Capture d’écran 2020-05-07 à 10 29 08](https://user-images.githubusercontent.com/16019289/81272392-b910f800-904d-11ea-96e9-439ba7aea287.png)


Here's the result : 
![Capture d’écran 2020-05-07 à 10 28 25](https://user-images.githubusercontent.com/16019289/81272361-adbdcc80-904d-11ea-8393-a8f3adf2d6c9.png)

You could upgrade to the latest version for PrestaShop to have a panel of features.

Thanks!

**Comment by testakis** [comment]
Hi  florine2623,

thank you for your response. 
If I upgrade to the latest version, except from the above message that appears in this case, is the system allow to customer to checkout order of out of stock items OR Inactive Products? 

Thanks!

**Comment by florine2623** [comment]
Hi @testakis ,
No the button is not clickable in the cart as you can see in the screenshot above :)

Thanks!
