### ISSUE TITLE
Doctrine Entities from Core are inaccessible in front office

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#19015]
#### Describe the bug

When trying to access the core Doctrine entities (like `PrestaShopBundle\Entity\Lang`) in front office an error is thrown:

![Capture d’écran 2020-05-06 à 18 36 48](https://user-images.githubusercontent.com/13801017/81203732-938ddb00-8fc8-11ea-8201-466a75b4d1ea.png)

#### Expected behavior

The core entities should be usable in Front office, this would help (amongts other thins) to manage some multi lang Doctrine entities. The problem is that in FrontOffice the container is a light one built by the core it is based on those two classes:

https://github.com/PrestaShop/PrestaShop/blob/1.7.6.5/src/Adapter/ContainerBuilder.php
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.5/src/Adapter/Container/DoctrineBuilderExtension.php

So the extension correctly scans the modules and add their namespaces in Doctrine, but it doesn't do it for core entities from the `PrestaShopBundle\Entity\` namespace. So we need to add a dedicated CompilerPass to add this namespace, inspired from `ModulesDoctrineCompilerPass`.

#### Steps to Reproduce

You will need the example module from this PR https://github.com/PrestaShop/example-modules/pull/20

1. Clone the branch
2. Only copy (or link) the `demodoctrine` folder into your `modules` folder
3. Install the module
4. Configure the module via Module manager
5. Since no data is present you should redirected to the Generate quotes page
6. Click on `Generate quotes` button, the tables and the demo quotes should be installed
7. Go to the front office homepage, you should see the error regarding the `Lang` entity

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: N/A

**Comment by jolelievre** [comment]
This issue has been re-scoped to 177 Because adding access to core entities is considered a new feature not a bug fix

And if it had been integrated in next 176 patch it would mean only the last patch version allows to use the core entities, which really reduces the version compatible and highlights even more the fact that it is a feature and not a bug fix

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19016
