### ISSUE TITLE
1.7.6.x Known Google SEO Search Console Bug #12687 "Either 'offers', 'review' or 'aggregateRating' should be specified" asking for 1.7.6.5 fix instead of waiting for 1.7.7

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19017]
Hello,

the Bug is already know with a few topics.
Issue is, the #12687 Ticket is closed referring to upgrade to PS 1.7.7

May I ask if it is possible to pull and replace just the necessary template.tpl files from 1.7.7 to 1.7.6.x, so all people with this version can fix this crucial bug instantly?
Google SEO is really banning everything out and is not listing anything at the moment! which is a major drawback like you can imagine...

Dont want to make a big issue out of this, just asking the Devs. if .tpl replacement may fix it, as I dont want upgrade to 1.7.7 (1-Click Upgrade is not even listing this option right now) and I dont want to mess with the stable shop - as I bet many user ask for this too, as this topic is going on since a while and many users in the PS Forum and in GitHub wrote smth. about this, I would appreciate if you could reply quickly what files to manually replace.

Some 1.7.6.6 micro Update so it can be 1-Click Installed would be nice too, if there is more needed than just replacing a few files.

Thanks

**Comment by Hlavtox** [comment]
@6xthFNGR Replace your microdata with this.

```

<meta property="og:title" content="{$page.meta.title}"/>
<meta property="og:description" content="{$page.meta.description}"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="{$urls.current_url}"/>
<meta property="og:site_name" content="{$shop.name}"/>

{if isset($product) && isset($product.cover) && $page.page_name == 'product'}
    <meta name="thumbnail" content="{$product.cover.bySize.large_default.url}" />
    <link rel="previewimage" href="{$product.cover.bySize.large_default.url}" />
    <meta property="og:image" content="{$product.cover.bySize.large_default.url}"/>
{else}
    <meta property="og:image" content="{$urls.shop_domain_url}{$shop.logo}"/>
{/if}
<script type="application/ld+json">
{
    "@context" : "http://schema.org",
    "@type" : "Organization",
    "name" : "{$shop.name}",
    "url" : "{$urls.pages.index}",
    "logo" : {
        "@type":"ImageObject",
        "url":"{$urls.shop_domain_url}{$shop.logo}"
    }
}

</script>

<script type="application/ld+json">
{
    "@context":"http://schema.org",
    "@type":"WebPage",
    "isPartOf": {
        "@type":"WebSite",
        "url":  "{$urls.pages.index}",
        "name": "{$shop.name}"
    },
    "name": "{$page.meta.title}",
    "url":  "{$urls.current_url}"
}


</script>
{if $page.page_name =='index'}
    <script type="application/ld+json">
{
	"@context":	"http://schema.org",
	"@type": "WebSite",
    "url" : "{$urls.pages.index}",
	"image": {
	"@type": "ImageObject",
    "url":"{$urls.shop_domain_url}{$shop.logo}"
	},
    "potentialAction": {
    "@type": "SearchAction",
    "target": "{'--search_term_string--'|str_replace:'{search_term_string}':$link->getPageLink('search',true,null,['search_query'=>'--search_term_string--'])}",
     "query-input": "required name=search_term_string"
	 }
}


    </script>
{/if}
{if isset($product) && $page.page_name == 'product'}
    <script type="application/ld+json">
    {
    "@context": "http://schema.org/",
    "@type": "Product",
    "name": "{$product.name}",
    "description": "{$page.meta.description}",
    "category": "{$product.category_name}",
	"sku": "{$product.reference}",
    {if $product.ean13}
    "gtin13": "{$product.ean13}",
    {/if}
    {if isset($product.cover)}"image" :"{$product.cover.bySize.home_default.url}",{/if}
    {if $product_manufacturer->name}"brand": {
        "@type": "Thing",
        "name": "{$product_manufacturer->name|escape:'html':'UTF-8'}"
    },{/if}
    {if isset($nbComments) && $nbComments && $ratings.avg}"aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{$ratings.avg|round:1|escape:'html':'UTF-8'}",
        "reviewCount": "{$nbComments|escape:'html':'UTF-8'}"
    },{/if}
    {if isset($product.weight) && ($product.weight != 0)}
    "weight": {
        "@context": "https://schema.org",
        "@type": "QuantitativeValue",
        "value": "{$product.weight}",
        "unitCode": "{$product.weight_unit}"
    },{/if}
    {*{if empty($combinations)}*}
  {if $product.show_price}	
    "offers": {
        "@type": "Offer",
        "priceCurrency": "{$currency.iso_code}",
        "name": "{$product.name|strip_tags:false}",
        "price": "{$product.price_amount}",
        "url": "{$product.url}",
        "priceValidUntil": "{$smarty.now + (60*60*24*15)|date_format:"%Y-%m-%d"}",
        {if $product.images|count > 0}
        "image": {strip}[
        {foreach from=$product.images item=p_img name="p_img_list"}
        "{$p_img.large.url}"{if not $smarty.foreach.p_img_list.last},{/if}
        {/foreach}
        ]{/strip},
        {/if}
        {if $product.ean13}
        "gtin13": "{$product.ean13}",
        {else if $product.upc}
        "gtin13": "0{$product.upc}",
        {/if}
        "sku": "{$product.reference}",
        {if $product.condition == 'new'}"itemCondition": "http://schema.org/NewCondition",{/if}
        {if $product.show_condition > 0}
        {if $product.condition == 'used'}"itemCondition": "http://schema.org/UsedCondition",{/if}
        {if $product.condition == 'refurbished'}"itemCondition": "http://schema.org/RefurbishedCondition",{/if}
        {/if}
        "availability":{if $product.quantity > 0} "http://schema.org/InStock"{else} "http://schema.org/OutOfStock"{/if},
        "seller": {
            "@type": "Organization",
            "name": "{$shop.name}"
        }
    }
	{/if}	

}


    </script>
{/if}
{if isset($breadcrumb.links[1])}
<script type="application/ld+json">
    {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
    {foreach from=$breadcrumb.links item=path name=breadcrumb}
    {
    "@type": "ListItem",
    "position": {$smarty.foreach.breadcrumb.iteration},
    "name": "{$path.title}",
    "item": "{$path.url}"
    }{if !$smarty.foreach.breadcrumb.last},{/if}
    {/foreach}]
    }
    </script>
{/if}

```

**Comment by pitkz** [comment]
Hello,

thank you for your quick reply!
I was thinking it is about PrestaShop /themes/classic/templates/catalog/_partials/product-prices.tpl aswell as /themes/classic/templates/catalog/_partials/miniatures/product.tpl

But I can not determe clearly that its about them. The miniatures/product.tpl defintly is something "infected", as Google Search Console puts errors for these minuatures listed f.e. on the New Products Block on the Front End start page.

May I please seek your advise again to make say dummy proof which files should be replaced by parts of the code?
I am in touch with the PS Forum where already some more people try to use your solution, so it would be great to not make something up by myself but tell them exact advises.

Thank you

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
I would advise you to wait for PS1.7.7 if your issue is non-blocking.

In PS1.7.7, you will have a lot more features on hand. Please take a look at : 
https://github.com/PrestaShop/PrestaShop/projects/7
Thanks!

**Comment by pitkz** [comment]
Hello @florine2623

well you did not read the first post:
This inquery is due to the 2 dozen people who are asking for a solution,
and the issue is "blocking" as No PrestaShop Customer using <1.7.6.5 is enlisted with his products at Google!
This topic can be closed as soon as it is stated where to put the code mentioned by @Hlavtox

Have a look into the PSForum where right in this moment people are commenting about this subject, and since I announced this Bug Ticket to them, more replies already occured!

Thanks

**Comment by pitkz** [comment]
I dont want to spam and open another issue - but @florine2623 would be great if you receive a notification by this msg and just reopen it again so @Hlavtox may say the proper locations, or you simply add it!

**Comment by pitkz** [comment]
Hey,

@florine2623 @Hlavtox dont you get a notification if I tag you :/ ?
a quick reply solves all the issue! Cmon ;)


Greets

**Comment by Hlavtox** [comment]
@6xthFNGR Send me a link to the website that throws you this error. 

PS: I am not a member of PS dev team, just trying to help you. :-)

**Comment by pitkz** [comment]
@Hlavtox I just asked for the path for the file to replace these source code. No need for personal support. Its not "my website" that needs it, its a standard PS 1.7.6.5 that many in the community got, which needs it :)

Appreciate your help. Thanks!

**Comment by grizado** [comment]
> @Hlavtox I just asked for the path for the file to replace these source code. No need for personal support. Its not "my website" that needs it, its a standard PS 1.7.6.5 that many in the community got, which needs it :)
> 
> Appreciate your help. Thanks!

Any news on the files to be edited with the above code?
Thank you.

**Comment by pitkz** [comment]
I would still appreciate if @florine2623 would reopen this issue, as @Hlavtox sadly did not provided the link yet. For PS Team its maybe solved with 1.7.7, but simply stating the file directories would bring immidiatly hotfix for users, and like you can see, others are interessted alot! Its a fundamental problem at the moment, as non PS Shop has good SEO because of this! Meaning, PS Shops lack behind the competitors Shops alot, no matter all the other great features - if you are not enlisted in THE major search engine (Google) you have more than a hard time.

@grizado sadly I dont know anything more yet.

**Comment by Hlavtox** [comment]
@grizado @6xthFNGR I am in the same position of you. I had to fix many bugs in PS for myself or pay somebody to do it. So next time, just accept it as it is and do it yourself.

Do not worry, microdata is helpful, but it will definitely not hurt your positions in search engines. The competition is just better. :-)

Put the code I gave you to head.tpl and delete all inline microdata from product-prices.tpl and the rest. Or just use https://github.com/prestarocket-agence/classic-rocket/releases/download/3.0.2/classic-rocket.zip

**Comment by grizado** [comment]
@Hlavtox Thank you very much.
By "and the rest" you mean all productxxx.tpl existing in "/public_html/themes/classic/templates/catalog/_partials"?

**Comment by cyrocostsolution** [comment]
https://www.youtube.com/watch?v=SpRBeXVwkdo

**Comment by thepixelabs** [comment]
> @grizado @6xthFNGR I am in the same position of you. I had to fix many bugs in PS for myself or pay somebody to do it. So next time, just accept it as it is and do it yourself.
> 
> Do not worry, microdata is helpful, but it will definitely not hurt your positions in search engines. The competition is just better. :-)
> 
> Put the code I gave you to head.tpl and delete all inline microdata from product-prices.tpl and the rest. Or just use https://github.com/prestarocket-agence/classic-rocket/releases/download/3.0.2/classic-rocket.zip

I managed to solve most my problems

For anyone wondering -
From that classic rocket theme quoted, you need to copy microdata-jsonld.tpl 
I also copied pagination-seo.tpl

Then open the file /themes/your theme/templates/_partials/head.tpl
Under head_seo block include the following close to the {/block} closing tag
```
{include file="_partials/microdata-jsonld.tpl"}
{include file="_partials/pagination-seo.tpl"}
```

On product pages the search console shows far better results, the only missing fields i have are for actually fields i didnt fill, like SKU (which is reference number on product page).

The problem is that all other products on that page (if you have addition products shown below), or even at the homepage, only the "Type" "name" and "price" gets filled in. However that is too fixable.
