### ISSUE TITLE
BO - Catalog price rules - Possibility to create catalog price rule with a % value greater than 100%

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19013]
#### Describe the bug

In BO => catalog => discount => catalog price rules it is possible to create a catalog price rule with a value in % greater than 100%

#### Expected behavior

it shouldn't be possible

#### Steps to Reproduce

1. Go to BO => catalog => discount => catalog price rule
2. Click on add a new catalog price rule with the following parameters: 
                                   - name => the name you want
                                   - from quantity => 150
                                   - reduction type => percentage
                                   - reduction => 150
The other parameters can be those by default
3. Click on "Save" ( the catalog price rule is created without error ) 
4. Go to FO and create a cart with one produtct and set the quantity to 150

**Screenshots**
![capture d'écran_55](https://user-images.githubusercontent.com/40635814/81198872-4149bb80-8fc2-11ea-8931-7864e0d8abf3.png)

#### Additional information

* PrestaShop version: 1.7.7 
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

This issue is fixed during the migration.
It is fixed in the next release 1.7.8.0.
![image](https://user-images.githubusercontent.com/16067358/89915850-2d33dc80-dbf7-11ea-9f11-efe37a84c0d9.png)

Thanks!
