### ISSUE TITLE
Inconsitency in module symfony services access

### ISSUE THREAD

**Issue by zulus** [PrestaShop/PrestaShop#19011]
### Describe the bug

Registered symfony services are available in backend via simple `$this->get()`, but in frontend I have only access to doctrine via `$this->context->controller->getContainer()->get()`

#### Expected behavior

I would like to have stable way to access my services in frontend and backend.

#### Steps to Reproduce

1. Register symfony service as described at https://devdocs.prestashop.com/1.7/modules/concepts/services/
2. Try use it in frontend hook

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by Matt75** [comment]
Since PrestaShop 1.7.3 there are in fact 3 containers :
- legacy front container available on front office of the shop.
- legacy admin container available on administration of the shop.
- Symfony container available on administration of the shop **but only for migrated controllers**.

So if you want to share services between theses 3 containers, you can create a common-services.yml and import it.

Example : https://github.com/PrestaShopCorp/ps_checkout/pull/349

**Comment by zulus** [comment]
Oh thanks, so would be nice to have this in documentation ;)

**Comment by matks** [comment]
> Oh thanks, so would be nice to have this in documentation ;)

This is true, thanks for the tip 👍

**Comment by matks** [comment]
EDIT: it's already there 😄but maybe not obvious

https://devdocs.prestashop.com/1.7/modules/concepts/services/#services-in-legacy-environment

@zulus Could you tell us if this is clear ?

**Comment by zulus** [comment]
@matks there is no information about "common-services.yml". Only about 3 different contexts. How to register for each one and how to use it in concrete controller.

I've read from module code that I have `Module::get()` method and it internally calls `Module::isSymfonyContext` and decide what to do.

From my point of view is a nightmare. Only way to make sure that hook will always work in same way between version is to always register everything in all 3 files or in mentioned common-services.yml. It also not always possible, for example I haven't access to validator service in legacy context, so if I add @Assert annotations to my doctrine entity, it become useless on frontend.

**Comment by Matt75** [comment]
Yes, I am frustrated too with this for [ps_mbo](https://github.com/PrestaShopCorp/ps_mbo/pull/89) and [ps_checkout](https://github.com/PrestaShopCorp/ps_checkout/pull/349) but I have to support old versions of PrestaShop so I have to do with that...

So I add [a custom function who test if `Module::get()` exist to retrieve my services](https://github.com/PrestaShopCorp/ps_checkout/blob/ca5c348f1b68d82d3c0f9fa1c0a96c5be7df3fbd/ps_checkout.php#L1106). (Please note `PrestashopCheckout\Configuration` class used in this code will be removed soon, don't judge me with that ^^)

**Comment by zulus** [comment]
Backward compatibility is always problem. But I'm talking about fresh modules that I want only for nevest prestashop. Scope of this ticket is clarification where should I put my service to make it always working in same way in any context.

For now `common-services.yaml` should be documented. 

Would be nice to have a list of common services that are available on all contexts / concrete context that are part of api. As mentioned before, one of them is doctrine and it's sub services, but symfony validator no, so if regular symfony developer (like me) will want use `@Assert` annotation together with symfony form component, will hit the wall.

**Comment by PierreRambaud** [comment]
What do you think if we improve the documentation or internal tools to be able to retrieve common services, front services and admin services?

**Comment by hibatallahAouadni** [comment]
Hello @zulus ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
