### ISSUE TITLE
BO - Catalog price rule - Currency sort and filter not working as expected

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19014]
#### Describe the bug

In BO => catalog => discount => catalog price rule the currency column filter always return null
And the sort fonctionnality doesn't sort correctly

#### Expected behavior
Filtering and sorting should work correctly

#### Steps to Reproduce

BEFORE reproduce => create some catalog price rule with different currency ( eur and dollards )

1. Go to BO => catalog => discount => catalog price rule
2. In currency column enter Eur and clic on search
3. See error the research result return null (see screen record 1 )
4. Now reset the research and try to sort the currency column 
5. See second error ( the column is not correctly sorted see screen record 2 )

**Screen record 1**
https://drive.google.com/file/d/1v40j44L2VGQun5Mj_bN9GFimi1XzxX5_/view?usp=sharing

**Screen record 2**
https://drive.google.com/file/d/1x2aIvlEjuKaujAXHuFG-e2Yw5Z9Dj7Fk/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by sam-pires** [comment]
is this a regression ?

**Comment by SD1982** [comment]
Hi @sam-pires  No this behaviour was already present in 1.7.6
