### ISSUE TITLE
PDF mailing invoice in BO language instead of customer language

### ISSUE THREAD

**Issue by superskyman100** [PrestaShop/PrestaShop#19024]
#### Describe the bug

Shop is multi-language with BO in english
In FO, if customer uses another language than English and is registered, as, for example, Portuguese, the invoice is sent in English language instead of Portuguese

#### Expected behavior

The PDF invoice should be e-mailed in the CUSTOMER LANGUAGE. Not in the BO language.

#### Steps to Reproduce

1. Create order with another language than the BO language
2. Validated payment on the BO 
3. Go to customer email box > the invoice is in BO language instead of being in customer language 

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by Matt75** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18352

**Comment by florine2623** [comment]
Hi @superskyman100 ,
As @Matt75  said, your issue is fixed by #18352, please keep an eye on PS future versions.
I will close your issue !

@Matt75 thank you !

**Comment by superskyman100** [comment]
Ok we tried to fix the problem on our Prestashop 1.7.6.4, it's not working

**Comment by Matt75** [comment]
@superskyman100 You should make some changes to be compatible with 1.7.6, this is made for 1.7.8

**Comment by Ctibor67** [comment]
I have PS 1.7.8.8 - BO in Czech lang, FO deutch, english. And pdf invoice is in czech. Shouldn't there be a template somewhere in the given language (similar to emails)?
