### ISSUE TITLE
Working with npm is eating computer resources - improve resources usage

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19028]
When we work on Javascript files for PrestaShop, we usually use `npm run watch` to recompile JS files automatically however it seems to consume huge computer resources. If we work too long, we sometimes have to kill it and restart it.

@NeOMakinG I dont know if we can do something about it. Is there something we can optimize to make npm lighter ? In webpack configuration ?

**Comment by PierreRambaud** [comment]
I was more for computing all js files in one instead of having 65 compiled files.

**Comment by eternoendless** [comment]
Having one giant uber file is bad practice, it's slower to download and the browser needs to load a whole lot of code that won't be used.

**Comment by PierreRambaud** [comment]
> Having one giant uber file is bad practice, it's slower to download and the browser needs to load a whole lot of code that won't be used.

So, as I already said, the more files we compiled, the more time it will take like in any other languages. :)

**Comment by zuk3975** [comment]
Im checking some older branch (started on Aug 9, 2019) and npm watches works fine there. So I guess we introduced this stuff somewhere around splitting 1.7.7 and develop which is when we stopped pushing assets (not sure what was done there exactly, but i hope its optimizable)

**Comment by NeOMakinG** [comment]
@PierreRambaud correct me if I'm wrong but webpack itself says that the more chunks you've, faster the build will be (related to treeshaking probably and other things). 

![image](https://user-images.githubusercontent.com/14963751/81535034-59765d80-9369-11ea-8f35-998cf14630af.png)

"Only compile the code that you're currently working on". Maybe we can do something there ? But you'r issue looks strange tbh, webpack recompile chunks that are changing, firstly this means that is you modify a file that is only contained on the order page for example, it will recompile the order page chunks only, secondly, this means that if you modify a file that is common on multiple chunks, you'll rebuild every chunks using it.

I'm gonna think about a way of lighting this, but this not easy regarding our projet :)

**Comment by NeOMakinG** [comment]
> Im checking some older branch (started on Aug 9, 2019) and npm watches works fine there. So I guess we introduced this stuff somewhere around splitting 1.7.7 and develop which is when we stopped pushing assets (not sure what was done there exactly, but i hope its optimizable)

Stop pushing assets means that every swapping branch, you rebuild every assets, that's of course a strong job for a computer, but having a watcher running shouldn't burn too much resources AFTER the initial build :/

**Comment by PierreRambaud** [comment]
@NeOMakinG You're right. 
The recommandation about `smaller = faster` is legit, the less code you have, the less execution time you get :sweat_smile: 
The problem here is: we are not using smaller libraries. As example, we recompile each time the grid component. extensions They are not manage as a library. 
The whole backend "front" part is badly manage :/

@eternoendless We are only doing it for js files. we have only one big theme.css file for all pages.

@zuk3975 I totally agree with @NeOMakinG running in watch mode is fast and don't consume too much resources.

**Comment by NeOMakinG** [comment]
We did a lot of improvements in the last 2 years, I guess we can't really do more, it's now way faster
