### ISSUE TITLE
 fix the modal popup used to select the categories or products in the conditions of cart rules

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#19036]
Hi!
Please I think it's time to fix the modal popup used to select the categories or products in the conditions of cart rules:
Catalog -> Réductions -> Règles de Panier -> Conditions -> Restrictions

When you have thousands of products or hundreds of categories, it's impossible to navigate in this popup system to choose anything, and even impossible when you have to select not 1 very specific, but many different conditions.
<img width="677" alt="popup" src="https://user-images.githubusercontent.com/12675798/81299664-10bb5d80-9066-11ea-9b19-6839e2933cb6.png">

For the category selection you can just use the menu tree as on admin products page. For product would be good to have a jquery instant search as the one you have in admin orders page in order to add new products to an existing order.
Thanks

**Comment by florine2623** [comment]
Hi @omar2886 ,
Thanks for the recommandation, I will let our Product Team know !
Please stay tuned.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team !

Can this be implemented ?

Thanks!

**Comment by LouiseBonnard** [comment]
Dear @omar2886, thanks a lot for your issue! You're right, it should be improved for large catalogs. I've just added this improvement idea to the cart rules EPIC so that it could be studied during the rework of this page.

**Comment by colinegin** [comment]
Hello @omar2886,

Thanks for your feedback, it is indeed a nice improvement ! 
As it is a duplicate of the following issue #13710, I close it. You can now follow this issue !

Thanks,

Coline

**Comment by khouloudbelguith** [comment]
Duplicate of #13710
