### ISSUE TITLE
Duplicate product empty thumbnail

### ISSUE THREAD

**Issue by ArturCritec** [PrestaShop/PrestaShop#19030]
When i duplicate a product fail the thumbnail image

![Screenshot_1](https://user-images.githubusercontent.com/56640981/81275297-603f6080-9049-11ea-90cc-b8f49de00a69.png)

**Comment by florine2623** [comment]
Hi @ArturCritec ,

I didn't manage to reproduce your issue on PS1.7.6.5 : 
![Capture d’écran 2020-05-07 à 13 46 06](https://user-images.githubusercontent.com/16019289/81290954-372ec800-9069-11ea-81b9-8cea0a9f538f.png)
What version of PS are you using ?
Did you duplicate from the products list page ? Or from the product page itself ?
Thanks!

**Comment by ArturCritec** [comment]
Is an old website and is using the version 1.6.0.6.
I duplicated the product in the product list, when I edit the product the images are there and the images are all right on the website, the only problem is even in the product list.

**Comment by florine2623** [comment]
PrestaShop 1.6 [isn't maintained anymore](http://build.prestashop.com/news/1.6.1.x-what-s-next/). The maintenance for this version is now being performed exclusively by volunteers to fix critical issues.
You can open an issue on the [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues). Please keep in mind that only critical issues will be acknowledged.
Thanks!
