### ISSUE TITLE
Order ID number frame to small - Back office

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#19034]
The order id number frame is too small, it only shows 4 digits. in my option this should be at least minimum of 5 or 6. It would improve the vision better. 

<img width="621" alt="Screenshot 2020-05-07 at 12 41 55" src="https://user-images.githubusercontent.com/46492443/81290679-6b51bb00-9060-11ea-92f8-5f71dec5a8c2.png">

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

Is this issue relevant ?

In PS1.7.7, this is how it looks : 
![Capture d’écran 2020-05-07 à 13 52 30](https://user-images.githubusercontent.com/16019289/81291431-056a3100-906a-11ea-8d9a-bfa0420e105d.png)

Thanks !

**Comment by 01park** [comment]
Yes, because in my example you see id 2074, but in fact I was looking for 20741.

Yes, you can input more than 4 digits, but it would be nice to also see what you entered after search. The width of the table is to small

**Comment by colinegin** [comment]
From what i can see you can put at least 5 digits in 177, so I guess this is an improvement we have made when redesigning the order listing.
Can you confirm @MatShir and @TristanLDD ?

If yes, we can consider this issue fixed.

**Comment by 01park** [comment]
Maybe I am not clear, its not about how many you can input, but the amount that is visible after input. It only shows 4 digits, but what if you have lets say an order id of 100532. Me, I would like to see the full number instead of only 1005

**Comment by colinegin** [comment]
Yes I understood clearly what you were asking, but if you look at the screenshot florine posted, there are actually 5 visible digits on the new order listing.

**Comment by 01park** [comment]
Oh, sorry I missed the part that he is on 1.7.7 I'm on 1.7.6.5

**Comment by colinegin** [comment]
Yes it will be available in 177, which should be released soon ! ;)
