### ISSUE TITLE
All carriers disabled

### ISSUE THREAD

**Issue by cprats** [PrestaShop/PrestaShop#19045]
#### Describe the error

I have a very rare problem in the frontoffice when choosing a carrier. And it doesn't always happen and it only happens for some clients. There are clients that do not get any selected carrier. But, they are customers, who have already made regular purchases in the purchase. What I do, when I find out that the client tells me about this error, is to make a new order for the backoffice using the cart, then the client presses F5 in his browser and the carrier already comes out. Very rare ... How can we solve it ...

#### Expected behavior

That the carrier exited correctly.

#### Steps to reproduce

Explained above.

#### Additional Information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
[cliente.pdf](https://github.com/PrestaShop/PrestaShop/files/4597983/cliente.pdf)

**Comment by atomiix** [comment]
Hi @cprats 

Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!
