### ISSUE TITLE
SHOW PRODUCTS UNDER SUBCATEGORIES ON CATEGORY PAGE

### ISSUE THREAD

**Issue by Natthew99** [PrestaShop/PrestaShop#19040]
By default, category page displays list of subcategories and then the whole list of products, belonging to parent category.

Subcat1
Subcat2
Subcat3

List of products belonging to parent category...

How can I display products, belonging to subcategories, under subcategory name??

What I need is:

Subcat1

prod-1-1
prod-2-1
prod-3-1
prod-4-1

 
Subcat2

prod-1-2
prod-2-2
prod-3-2
prod-4-2

 
Subcat3

prod-1-3
prod-2-3
prod-3-3
prod-4-3

PrestaShop 1.7.6.1

THANKS YOU

**Comment by atomiix** [comment]
Hi @Natthew99 

Thanks for your feedback. What do you think @PrestaShop/prestashop-product-team?

**Comment by colinegin** [comment]
@atomiix can you add label related to what it refers to ? BO / FO, Categories, etc.
I'm not sure I understand the need with the current description.

**Comment by atomiix** [comment]
@colinegin From what I understand it's when in the FO you click on "Clothes" for instance, then you'll have subcategories on the left : Men - Women, and all products from those categories in the main part. What @Natthew99 would like to achieve is having all those products separated by the subcategory they belong to.

**Comment by marionf** [comment]
@Natthew99 You don't want to display in parent category the products belonging on the subcategory ?

**Comment by khouloudbelguith** [comment]
Hi @Natthew99,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
