### ISSUE TITLE
Bug on register textareaLang type in HelperOption

### ISSUE THREAD

**Issue by carlead** [PrestaShop/PrestaShop#19041]
#### Describe the bug

When you make an ModuleAdminController using HelperOptions with textareaLang required and you submit the form, an error displayed like the filed is empty and is required.

#### Expected behavior

I expect when i submit my form HelperOptions, the value of my textareaLang was saved.

#### Steps to Reproduce

1. Make an ModuleAdminController using HelperOptions and a field with this options :
`'title' => $this->module->l('xxxxxxxxxxxx', 'XxxxxXxxxxxx'),
'desc' => $this->module->l('xxxxxxxxxxxx', 'XxxxxXxxxxxx'),
'validation' => 'isCleanHtml',
'required' => true,
'autoload_rte' => true,
'lang' => true,
'rows' => 5,
'cols' => 40,
'type' => 'textareaLang'`
2. Click on the submit button
3. See error like the filed is empty and it's required

**Correction**
In AdminController.php in classes/controller, in function processUpdateOptions(), you forgot in two lines a test on textareaLang (line 1458 and 1470) :
`if (isset($values['type']) && $values['type'] == 'textLang')`
=>
`if (isset($values['type']) && in_array($values['type'], array('textLang', 'textareaLang')))`

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by atomiix** [comment]
Hi @carlead 

Thanks for your feedback, could you provide us a simple module to reproduce this bug?

**Comment by florine2623** [comment]
Since we had no news from you for 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
