### ISSUE TITLE
An http 502 error occurred during installation...

### ISSUE THREAD

**Issue by aunhappy** [PrestaShop/PrestaShop#19046]
#### Describe the bug

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: HTTP 502 - error -
502 Bad Gateway

#### Expected behavior

install successfully

#### Steps to Reproduce

just install normally

**Screenshots**

![Snipaste_2020-05-08_17-57-37](https://user-images.githubusercontent.com/15842120/81395010-79cdce80-9155-11ea-80de-a3fdc4f7e80c.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
* Server: CentOS 7.8.2003(Py2.7.5)

**Comment by atomiix** [comment]
Hi @aunhappy 

Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!
