### ISSUE TITLE
Cancelling order of pack with "Decrement both" option does not restock individual items

### ISSUE THREAD

**Issue by johwech** [PrestaShop/PrestaShop#19054]
#### Describe the bug

When a pack is ordered with the "Pack quantities" option "decrement both" and the order gets cancelled, the pack amount gets restocked, the item stock not.
So after a cancelled order the "before order" stock state is not the same as before the cancelled order.

Example: 
```
Initial

Stock:
Product A   Stock 24
Six-Pack A  Stock  4

Order 2x Six-Pack A

Stock: 
Product A   Stock 12
Six-Pack A  Stock  2

Cancel Order

Stock: 
Product A   Stock 12
Six-Pack A  Stock  4

```
#### Expected behavior

The stock of the items and the packs to be the same as before the cancelled order.

#### Steps to Reproduce

1. Create Product
2. Create Pack of the Product with "Pack quantities" option "decrement both" 
3. Order Pack
4. Check Stock of Pack and Product, should now be decremented correctly
5. Cancel Order
6. Pack stock is same as before, Product stock stays the same as after the order was placed

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by atomiix** [comment]
Hi @johwech 

Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!
