### ISSUE TITLE
Duplicate product result in 500 error page (product is still duplicated)

### ISSUE THREAD

**Issue by imagicuus** [PrestaShop/PrestaShop#19053]
#### Describe the bug

When duplicating a product in some situations a 500 error page is shown. This happens in a multistore installation and only with products that have features and/or combinations. When I duplicate a simple product without features/combinations no error is shown.

When the error is shown the product is still created, but there are no features and images in the created product.

#### Expected behavior

Just like a simple product a product with features/combinations should also be nicely duplicated

#### Steps to Reproduce

1. In a multistore environment with all shops selected go to products
2. Use the copy function to duplicate a product
3. The 500 error page is shown

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

**Comment by atomiix** [comment]
Hi @imagicuus 

Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!

**Comment by imagicuus** [comment]
My installation is quite standard I would say. I've tried the same thing with debug mode on and it resulted in the following error:

Duplicate entry '200-434-3' for key 'id_product'<br /><br /><pre>INSERT INTO `ps_product_supplier` (`id_product`, `id_product_attribute`, `id_supplier`, `product_supplier_reference`, `product_supplier_price_te`, `id_currency`) VALUES ('200', '434', '3', '', '0.000000', '1')</pre>

So I guess it's a combination of having a supplier selected and have a combination in the product. I'm still thinking this has something to do with the PrestShop core

**Comment by imagicuus** [comment]
Error looks similar to this old issue: https://web.archive.org/web/20180318141337/http://forge.prestashop.com/browse/PSCSX-9828
