### ISSUE TITLE
Rebuild search index cron job

### ISSUE THREAD

**Issue by Sandeep-singh97** [PrestaShop/PrestaShop#19062]
Open rebuild search index URL that appears at Shop parameters - Search in a private tab (without login) or in a cron
Error. It requires BO login. Index is not rebuilt.
Prestashop version 1.7.6

* PHP version: 7.1.33

**Comment by atomiix** [comment]
Hi @Sandeep-singh97 

Thanks for your feedback. However I'll close this issue because index rebuilding **should** requires BO login for safety reasons.

**Comment by Sandeep-singh97** [comment]
How can I set rebuild search index cron using easy cron??
Please help me
