### ISSUE TITLE
Allow validation errors translation

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#19061]
#### Is your feature request related to a problem?

When you send data to Prestashop, for example throw webservice, all data are validated. If data arn't valid, you'll get an error, for example:
Property Product->description_short length (889) must be between 0 and 800

#### Describe the solution you'd like

Allow these texts to be translated too. It'll be better for UX.

Thanks :)

**Comment by atomiix** [comment]
Hi @Max84 

Thanks for your feedback. Could you provide detailed steps to reproduce the issue and screenshots so we can better identify you demand? Thanks.

**Comment by Max84** [comment]
Hi @atomiix 
I did a mistake, during my test, my default language was wrong.
You can close this feature request. Prestashop has already it.
Thanks.
