### ISSUE TITLE
[Wishlist 1.7] Technical story : data migration from wishlist module 1.6 to module 1.7 

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#19060]
As a merchant, I can, during the migration of Prestashop from 1.6 to 1.7, recover all the data from the Wishlist module present on 1.6.

**Comment by matks** [comment]
ping @lolath-presta was this achieved in blockwishlist v2 ?

**Comment by NeOMakinG** [comment]
Seen with @Quetzacoalt91 , its done
