### ISSUE TITLE
Delivery and billing address displayed twice

### ISSUE THREAD

**Issue by doeselschnecke** [PrestaShop/PrestaShop#19064]
### Describe the bug

When using a different language (in my case de-DE), the addresses in the oder confirmation mail were shown twice, because HTML Tag `<span data-text-only=1>` seems to not work in other languages. 

#### Expected behavior

Show the addresses once, not twice.

#### Steps to Reproduce

1. Set front end language to German
2. Make an order
3. Read the sent order confirmation mail
**Screenshots**

<img width="966" alt="Screenshot 2020-05-11 at 14 49 36" src="https://user-images.githubusercontent.com/65049045/81563855-26e35980-9397-11ea-87db-d7286cd3181c.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by atomiix** [comment]
Hi @doeselschnecke 

Thanks for your contribution. Though, I get the same behavior whatever the language I set for the front-end. @PrestaShop/prestashop-product-team do you know what's the expected behavior?

**Comment by Hlavtox** [comment]
@doeselschnecke What's wrong with this? This is how Prestashop is behaving since forever.

**Comment by doeselschnecke** [comment]
It’s super easy to fix it though. I’ve made a pull request #19050, it only has to be merged into the current branch. I’ve been using git for a while, but GitHub is new to me. I’m not sure if I have to do something with the pull request or if an admin has to approve it for merging

**Comment by colinegin** [comment]
Hello @doeselschnecke , 

indeed, the order confirmation email shows the delivery address and the billing address. Why is it a problem for you ?

**Comment by doeselschnecke** [comment]
> Hello @doeselschnecke ,
> 
> indeed, the order confirmation email shows the delivery address and the billing address. Why is it a problem for you ?

It shows it TWICE. Look on the screenshot attached above. After Germany is the customers name and address again. It's a bug in the classic email template.

**Comment by colinegin** [comment]
Indeed, you're right ! I did not read all the address until the end.
We should fix this bug, do you know if this is a regression of it has been like that in previous versions too ?

**Comment by doeselschnecke** [comment]
I don't know if it's a regression or if has been like this in earlier versions, too. I assume, that it is a regression, maybe caused by switching to PHP 7 or due to changing to a new system or so. I've been using PrestaShop for about a month now, but really like the coding style. 

I don't know if it was working in earlier versions, but it seems like it did. The text only version was probably generated with
`<span data-text-only=1></span>`
but this seems to be obselete. Most templates are written correctly meanwhile, but the order_conf seems like there's one old left-over.

Like I mentioned earlier, it's an easy fix though. For perfection, the 
`{% if templateType == 'txt' %}`
` 	{{ 'Delivery address'|trans({}, 'Emails.Body', locale)|raw }} `
` 	{delivery_block_txt} `
` {% endif %} `
would need one more line break. I don't know how to do line breaks in the text version though.

<img width="336" alt="Screenshot 2020-05-11 at 16 10 40" src="https://user-images.githubusercontent.com/65049045/81667056-1c7e9980-9443-11ea-81cf-67fda7cf6d3b.png">

With the above mentioned code the text version looks like this. If somebody knows how to insert a line break between "Delivery address:" (Lieferadresse:) and the address itself without having to change all translations, it would look even better.

With the current stable version, the text version looks like this (no "Delivery address:" or "Billing address:" is shown:
<img width="346" alt="Screenshot 2020-05-11 at 16 10 11" src="https://user-images.githubusercontent.com/65049045/81667318-68c9d980-9443-11ea-9dc0-c682723c6480.png">

**Comment by colinegin** [comment]
@atomiix did you check if this was working differently before 1.7.6 ? Did you also check with PHP version < 7.3 ? 
Indeed FYI @doeselschnecke , PrestaShop 1.7.6.5 is not compatible with PHP 7.3

**Comment by doeselschnecke** [comment]
Thanks. Good to know. I read somewhere that it's compatible with PHP 7.2 and 7.3.

I'm currently using 7.2 though. The duplicate addresses are shown on PHP 7.2, too. The old HTML Tag looks like it was used back in PHP 5.5 times (just an assumption).
