### ISSUE TITLE
BO - Bad redirection when trying to access Orders when unauthorized

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19075]
#### Describe the bug

When an employee cannot access the orders pages, and when his default page is "orders", but try to access it via URL, there is an infinite redirection to orders.

#### Expected behavior

Redirection should target any page this user has access to.

#### Steps to Reproduce

1. With Admin, go to BO > Advanced Parameters > Team > Add new Employee
2. Create the employee, with "Orders" as Default Page, and Logistician as Profile
3. Go to Permissions tab, change permissions of Logistician, remove all permissions in "Orders"
4. Disconnect, and connect with the newly created employee
5. Since his default page is Orders, and his profile has no access to this page, there is an infinite redirection.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #19103
