### ISSUE TITLE
BO - No access to employee's profile when not an admin

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19077]
#### Describe the bug

When an employee has a profile without the following permission : _Advanced Parameters > Team > Employee_ (so when he's not an admin, since no non-admin users should access this page), he cannot access his user profile.

#### Expected behavior

User profile should always be accessible, no matter which permission the user has.

#### Steps to Reproduce

1. With SuperAdmin profile, go to BO > Advanced Parameters > Add new employee
2. Create an employee with a "basic" profile (Logistician, Translator for example)
3. Login with this employee account, try to access his profile => Access denied
4. With SuperAdmin account, change permission to this employee's profile, and give access to Advanced Parameters > Team > Employee
5. With employee account, try to access his profile => OK

But this "solution" in not a good workaround, since it will also give access to the "Advanced Parameters > Team > Employee" page to a standard employee...

**Screenshots**

On this screenrecord, I try to access "Profile" page with a Logistician profile, it does not work. I had the "Advanced Parameters > Team > Employee" permission with a SuperAdmin account, go back to the Logistician profile, now "Profile" page is accessible

https://drive.google.com/open?id=1l29QaaN0AfH-79hTUBfwV-YaM-97Luoe

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #19089
