### ISSUE TITLE
Emails Send as Text causing email MIME attachments, MIME causing issues with certain devices (iOS iPhone), no option to deactivate or fix it within PS BO

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19070]
Hello,

my PS 1.7.6.5 is set at Menu - Configure - Advanced Parameters - Emails to
"send Emails in text format".
I have multiple issues with this:

a)
Even when choosing to only send Text emails, he still attaches the Mail Logo. There is no option to disable it, and when the Mail Logo is deleted he picks the Shop Logo instead.
I think this is the reason for my main issue:

b)
iPhones: They receive an Email, with the proper title, without any content text, but with a MIME attachment - but this attachment can not be opened.
I think it is a security reason of iPhone triggering something, and preventing to download the email. When an iPhone user choose the "download full email" button at the top of the stream, nothing gets triggered - no more content shows up.

The only work around at the moment for me is, to choose the option to Send Emails as HTML or as both, but only the HTML variant will be displayed properly on iOS/iPhone.
My Thunderbird, Webmailers, Android Apps - non got an issue with the Text Variant or the HTML Variant.
As I am not familiar with MIME Protocol, I may not speculate for the reasons and leave it to the question:
I wished/expect PS would behave that I can choose to send only text based emails, without additional MIME protocol, without attachments like an Email Logo - for best compatibility and more security for the customer, who only receives plain, unencrypted, text!

- One hint I read, was that the text has to be ASCII to be send as plain text? Dont know if thats true, or if utf-8 or some iso`s would be okay aswell, but it would be generally great to have an option in the BO to set the email text encoding?

c) Ive edited my Menu - Improve - International - Translations - Email Translation - of Body - of my actual Theme (custom classic theme but it contains just 1 line edited css for the front office slider), so basically he uses the classic theme, so basically again the core theme as far as I understand the policy of falling back if no own values are set within a child theme?), but when I check the email theme again they seem part wise altered.
Text that I have changed is added back again. But just with some amount.
For example: In my case right now, the first 3 Templates are still the "custom" one - but all other ~69 are back to standard.

This is an issue, as some theme has missing data that I receive alerts for.
When I add my template, so there is no missing data and save it, still - he wents back again, causing empty mails for customers which I can not fix.

Thanks

PS: 1.7.6.4 to 1.7.6.5
PHP 7.1.3

**Comment by sarahdib** [comment]
hello @6xthFNGR 

a) it's indicated when you submit the logo that if there is no logo for email, the shop logo will be used
<img width="1278" alt="Capture d’écran 2020-05-12 à 09 38 10" src="https://user-images.githubusercontent.com/3034677/81652783-8fccdf00-9434-11ea-954c-a99010cc5496.png">
This is not an issue but an improvement 
@PrestaShop/prestashop-product-team what do you think about add an option to disable logo in the email.

b) @PrestaShop/prestashop-core-developers can you check this point please ? 

c) I'm sorry but I didn't understand this point, you try to change translation for some mail but it didn't work ?

Thank you

**Comment by pitkz** [comment]
Hey @sarahdib 

a) yes, it is a feature request - tho the "Send Email as Text" Feature is useless if you attach a picture again, so this shouldnt have come up in the first place.

c) yes, I explained the Menu which I took and that I changed my Email "Templates". But only some of them are saved (3) but most of them are resettet (all other).

Ty

**Comment by LouiseBonnard** [comment]
Hi there, thanks @6xthFNGR and @sarahdib! I agree with the first point. By definition, plain text emails should not display any picture. Regarding the other points, let's wait for the @PrestaShop/prestashop-core-developers to answer. :-)

**Comment by Hlavtox** [comment]
Hello @6xthFNGR, I don't exactly understand your b) point.

Why don't you just enable to send both versions of email? This works perfectly on all current devices and email clients.

**Comment by cruftex** [comment]
That a logo is attached, even when text only emails is selected, feels more like a bug to me, since the email logo is only relevant for HTML messages. That a MIME message is generated is an effect of the attachment.

Now the title reads:
> Emails Send as Text causing email MIME attachments, MIME causing issues with certain devices (iOS iPhone), no option to deactivate or fix it within PS BO

I suggest changing the title to:
> Logo is attached for text only emails

and changing to bug.

**Comment by cruftex** [comment]
Ping @PrestaShop/prestashop-product-team see comment above.

**Comment by 0x346e3730** [comment]
ping @PrestaShop/product-team for @cruftex's comments above

**Comment by MhiriFaten** [comment]
Ping @PrestaShop/product-team could you confirm this issue before testing it ?
We are still waiting for your confirmation.

Thank you

**Comment by Hlavtox** [comment]
@MhiriFaten I am a member of product council and I confirm it, you can continue. :-)

**Comment by fabienvallon** [comment]
+1
