### ISSUE TITLE
Attribute not in combination

### ISSUE THREAD

**Issue by shelve71** [PrestaShop/PrestaShop#19087]
Hi,
i need to assign at a product an attribute with two options like "Kind of printing: 'Matt Varnish' or 'Gloss Varnish'" but i can't understand how to do in prestashop. I tried with combinations but it is not good for me because i have problems to manage the stock. For example if i have in stock 10 T-Shirt black and 5 T-Shirt Red, when i assign the attribute "Kind of printing" they became 4 combinations so i can't manage the quantity of stock because i will have 4 fields "quantity in stock" instead of 2. 

Could you suggest me some solution ?

Thanks

**Comment by florine2623** [comment]
Hi @shelve71 ,
Actually this is normal.
If you have one product of each 2 combinations, you have 2 products.
- Product in Matt Varnish
- Product in Gloss Varnish

If you have one product with 4 combinations (Matt Varnish, Gloss Varnish, Red and Blue), you have 4 products.
- Product in Matt Varnish in Red
- Product in Matt Varnish in Blue
- Product in Gloss Varnish in Red
- Product in Gloss Varnish in Blue

You can manage the stock directly in the product page of in the stock tab, like so :
![Capture d’écran 2020-05-12 à 14 24 55](https://user-images.githubusercontent.com/16019289/81691059-8192b900-945c-11ea-88a1-de6d4ee15602.png)
![Capture d’écran 2020-05-12 à 14 25 24](https://user-images.githubusercontent.com/16019289/81691069-85bed680-945c-11ea-82c4-3ebf6d3199db.png)
Thanks

**Comment by shelve71** [comment]
Hi,
the problem is that i sell customized products.

I have in stock only these 2 (not personalized) products:
10 Products Red
5 Products Black

With an extra cost, i can personalize the products in stock with "Matt Varnish" or "Glossy Varnish". 

How i can manage in prestashop this case ?

Thanks.
Antonio

**Comment by florine2623** [comment]
Hi @shelve71 ,

For that you need a module like that one : https://addons.prestashop.com/en/combinaisons-customization/19536-product-options-bundles-and-customization.html
In the description it says : "The price will be automatically calculated based on the customization made by your customer."
It seems to fit your need.
What your are asking is not possible natively.

These are support questions, for more request, you can contact directly our support team : https://addons.prestashop.com/en/388-support

I will close this issue, it has nothing to do with bug or improvement :)
Thanks!
