### ISSUE TITLE
How set rebuild search index cron job using easy cron?

### ISSUE THREAD

**Issue by Sandeep-singh97** [PrestaShop/PrestaShop#19084]
How set rebuild search index cron job using easy cron?
Please help me.
 PrestaShop version: 1.7.6.1
* PHP version: 7.1.33

**Comment by Sandeep-singh97** [comment]
Please help....

**Comment by Sandeep-singh97** [comment]
Hi,
 How to set rebuild search index cron job using easy cron ?
PrestaShop version: 1.7.6.1
PHP version: 7.1.33

**Comment by florine2623** [comment]
Hi @Sandeep-singh97 ,

You can contact directly the support at PrestaShop to get personalized help :
https://addons.prestashop.com/en/388-support
I will take care of your request !

Thanks!
