### ISSUE TITLE
When change address shipping fee is rounded

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#19082]
When I change the address of a customer on a order page, the shipping fee paid is rounded.
15.94 EUR become 16.00 EUR

Note that my default currency is JPY

If I change a price on the carrier page, the shipping fee will rounded from this new price.
(Even if the shipping fee is twice more than before, the shipping fee paid by customer need to stay the same)

The invoice of front office and PDF become differents.

PS 1.7.5
PHP 7.2

**Comment by colinegin** [comment]
Hello @BenTen ,

Thanks for your feedback.

About your first issue, it's related to the fact that there is no decimal associated with the JPY currency. So even though the carrier price is set up to 15.94, the front office will actually show the closest round price, which is 16. 

About your second issue, i did not manage to reproduce it with an order with "Payment accepted" status. Could you give me more details about the steps you followed to reproduce your issue ?

Thank you very much,

Coline

**Comment by BenTen** [comment]
The Carrier price is set in JPY but when the customer pay with an other currency (here EUR), the carrier price is convert (here 15.94).

**Comment by colinegin** [comment]
I've just tested it again by setting a new carrier price at 15.94 JPY, with a customer paying in euros, and from what I can see the price is correctly converted (as you can see on the screenshot)
![image](https://user-images.githubusercontent.com/35263827/81831947-3b158b00-953e-11ea-9b6a-dde3704c75c6.png)

Am I missing something ?

**Comment by BenTen** [comment]
Try with the same setting than me.

1/ Set your shop in JPY and add a currency EUR or USD for example
2/ Made an order in EUR
3/ Change the address of the customer in BO (by order page)

See the price rounded on shipping parts.

**Comment by florine2623** [comment]
Hi @BenTen ,
I followed your steps, and I couldn't reproduce your issue.
The order has been made :
![Capture d’écran 2020-05-18 à 17 01 32](https://user-images.githubusercontent.com/16019289/82228337-49421d80-9929-11ea-8579-b44c480b1c01.png)
After changing the address via BO :
![Capture d’écran 2020-05-18 à 17 01 16](https://user-images.githubusercontent.com/16019289/82228346-4d6e3b00-9929-11ea-828b-deffa3fc1c57.png)
The shipping cost is still the same.

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
Feel free to open another one if you can provide more details.

Best regards.
