### ISSUE TITLE
Automatically check for module updates does not work

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19097]
#### Describe the bug

In Advanced Parameters, the "Automatically check for module updates" option does not seems to work.
When installing an old version of a module, when this option is disabled, the updates are still displayed for this module.

#### Expected behavior

Updates should not be displayed when option is disabled.

#### Steps to Reproduce

1. Go to Bo > Advanced Parameters > Administration > General
2. Disable "Automatically check for module updates"
3. Install a old version of a module
4. Go on module page, there is the "update" button, it should not

**Screenshots**

faceted_search is in version 3.4.0, last version is 3.5.0, but there should not be the "Update" button, since it's deactivated.

![automatic update](https://user-images.githubusercontent.com/55688534/81712807-59638400-9475-11ea-89db-722f977b12c9.png)

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7
* PHP version: N/A

**Comment by florine2623** [comment]
@MatShir 

This option is not available after 1.7.8.x.

**1.7.8.x** :
<img width="1178" alt="Screenshot 2023-08-30 at 15 03 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/42e9dc3d-01b5-4468-9180-faaa1d8ea8f3">

**8.0.x** : 
<img width="1219" alt="Screenshot 2023-08-30 at 15 01 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a3d5bded-7445-4974-a970-67236073c064">

What should be done with this issue ?

**Comment by MatShir** [comment]
With the differentiation, it is not relevant anymore

**Comment by MatShir** [comment]
thanks @florine2623 for the update
