### ISSUE TITLE
Custom image type is deleted after upgrade

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#19094]
**A)**	Custom image type is deleted after upgrade from 1.7.6.4 to 1.7.6.5.
 
**Steps to Reproduce:**
1. Before upgrade PS 1.7.6.4 go to the Design - Image Settings and add new image type:
For example: different_colour_variant, 50px x 50px for product
![before_1764](https://user-images.githubusercontent.com/38213520/81692454-b6077480-945e-11ea-8f52-b1e82c5cc084.JPG)
2. Upgrade to PS 1.7.6.5
3. go to the Design - Image Settings. You can see type different_colour_variant is deleted.
![after_1765](https://user-images.githubusercontent.com/38213520/81692463-b9026500-945e-11ea-9a59-c5b50b4bbb05.JPG)
This is strange behavior.

**B)**	Similar behavior is for disabled modules. Some disabled modules are re-enabled after upgrade. Modules position (ordering) is removed or changed in the Design – Position. Now we must add hooks again a sort(ordering) modules again – this is tiresome.

For example PS modules: Newsletter, Custom text blocks, Banner, social media share buttons, Customer reassurance...
but position/hook is removed for non standard (paid) modules too. 

Thank you
Best regards
PN

#### Additional information

* PrestaShop version: 1.7.6.4 to 1.7.6.5
* PHP version: 7.0.33-0+deb9u7

**Comment by florine2623** [comment]
Hi @PeNov ,

I could not managed to reproduce your issue.
I upgraded from PS 1.7.6.4 to 1.7.6.5 with module 1-click upgrade v4.10.1
![Capture d’écran 2020-05-12 à 17 28 53](https://user-images.githubusercontent.com/16019289/81713936-ccb9c580-9476-11ea-820f-705e1f4d2db8.png)

Image setting still exists :
![Capture d’écran 2020-05-12 à 17 33 36](https://user-images.githubusercontent.com/16019289/81713916-c6c3e480-9476-11ea-9b3f-d87400785d55.png)

Did you use 1-click upgrade ?
Did you have any error ?
Do you have errors on your log file ?

Please check and let me know!

**Comment by PeNov** [comment]
Hello Florine2623,
yes, I used 1-click upgrade module v.: 4.10.1

**Server log during upgrade - until now:**
[server_log.txt](https://github.com/PrestaShop/PrestaShop/files/4618963/server_log.txt)
1-click upgrade log:
[1click_log.txt](https://github.com/PrestaShop/PrestaShop/files/4619011/1click_log.txt)

Server info:  Linux 1 SMP Wed Apr 29 12:54:11 CEST 2020 x86_64
Apache/2.4.25 (Debian)
Verze PHP: 7.0.33-0+deb9u7
512M
600
128M
Verze MySQL: 10.1.41-MariaDB-0+deb9u1

![PS_SV_info](https://user-images.githubusercontent.com/38213520/81756765-f09ffa00-94bc-11ea-913a-2dd8e3c693d5.png)

Status for upgrading each modules missing in my 1-clik upgrade log:
I highlighted this behavior on your file:
![missing](https://user-images.githubusercontent.com/38213520/81757065-d9add780-94bd-11ea-9369-41882a1dadf8.JPG)

Thank you
Best regards
PN

**Comment by florine2623** [comment]
Hi @PeNov ,
Sorry for the very late answer.
As I tried again, I still can't manage to reproduce the issue.
I'll close your issue.
