### ISSUE TITLE
select boxes are broken in 1.7.6.3

### ISSUE THREAD

**Issue by jansanto** [PrestaShop/PrestaShop#19099]
`<selectid="import_theme_import_from_ftp" name="import_theme[import_from_ftp]" class="custom-select"><option value="">-</option><option value="abcd.zip">abcd.zip</option>      <small class="form-text">This selector lists the Zip files that you uploaded in the '/themes' folder.</small>
    </selectid="import_theme_import_from_ftp">`

**Comment by colinegin** [comment]
Hello,

Could you please provide us with more info? We need more details to understand your problem and see if we reproduce it:

- host

- server setup and configuration

- debug mode report

- PHP error logs

- apache error log

- Javascript console log

- screenshots

 ...

You don't know how to get this information? Please read the following article:

http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
