### ISSUE TITLE
Back Office order detail trow 500 erro when NOT in debug mode

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#19093]
#### Describe the bug

Try to open a order detail from customer account login generate a 500 error

#### Expected behavior

Open details

#### Steps to Reproduce

www[20171]: PHP Fatal error:  Uncaught Error: Cannot use object of type Product as array in /var/www/htdocs/www.sixrace.it/modules/ps_viewedproduct/ps_viewedproduct.php:186#012Stack trace:#012#0 /var/www/htdocs/www.sixrace.it/modules/pagecache/pagecache.php(1683): Ps_Viewedproduct->renderWidget('displayProductA...', Array)#012#1 /var/www/htdocs/www.sixrace.it/override/controllers/front/ProductController.php(25): PageCache::execDynamicHooks(Object(ProductController))#012#2 /var/www/htdocs/www.sixrace.it/classes/controller/Controller.php(308): ProductController->displayAjax()#012#3 /var/www/htdocs/www.sixrace.it/override/classes/Dispatcher.php(166): ControllerCore->run()#012#4 /var/www/htdocs/www.sixrace.it/index.php(28): Dispatcher->dispatch()#012#5 {main}#012  thrown in /var/www/htdocs/www.sixrace.it/modules/ps_viewedproduct/ps_viewedproduct.php on line 186

www[20153]: PHP Fatal error:  Uncaught Error: Cannot use object of type Product as array in /var/www/htdocs/www.sixrace.it/modules/ps_viewedproduct/ps_viewedproduct.php:186#012Stack trace:#012#0 /var/www/htdocs/www.sixrace.it/modules/pagecache/pagecache.php(1683): Ps_Viewedproduct->renderWidget('displayProductA...', Array)#012#1 /var/www/htdocs/www.sixrace.it/override/controllers/front/ProductController.php(25): PageCache::execDynamicHooks(Object(ProductController))#012#2 /var/www/htdocs/www.sixrace.it/classes/controller/Controller.php(308): ProductController->displayAjax()#012#3 /var/www/htdocs/www.sixrace.it/override/classes/Dispatcher.php(166): ControllerCore->run()#012#4 /var/www/htdocs/www.sixrace.it/index.php(28): Dispatcher->dispatch()#012#5 {main}#012  thrown in /var/www/htdocs/www.sixrace.it/modules/ps_viewedproduct/ps_viewedproduct.php on line 186

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2

**Comment by matteolavaggi** [comment]
I dont tink is a ps_viewedproduct related issue. Try to disable it with no luck.


In debug mode the order datail page work with no problem

**Comment by florine2623** [comment]
Hi @matteolavaggi ,
After disabling the module ps_viewedproduct, what error do you have with debug mode on ?

I'm using PS 1.7.6.5 and Viewed products block v1.2.1, I do nat have that issue.

Please check and let me know!

**Comment by matteolavaggi** [comment]
The same error so is not related to that 500 problem, i cant see any other php error related using the id order url to filter log

**Comment by florine2623** [comment]
Could you try to comment the module directly from your FTP  and try again ?
`ps_viewedproduct` becomes `_ps_viewedproduct`
Please try and let me know !

**Comment by matteolavaggi** [comment]
Same problem also with directory name changed

**Comment by florine2623** [comment]
Can you send a screenshot of the error with debug mode ?

**Comment by matteolavaggi** [comment]
Hi, thanks but read my issue post, when debug mode is enabled the order detail page work with no problem

**Comment by florine2623** [comment]
Try to deactivate your module pagecache and et me know the outcome.

**Comment by matteolavaggi** [comment]
Same problem, cache is not used in login page for user.

**Comment by matteolavaggi** [comment]
Why in debug mode work?

**Comment by florine2623** [comment]
What do you mean "cache is not used in login page" ?
If there is an issue with the page cache module, you should contact the dev of that module directly.

**Comment by matteolavaggi** [comment]
@florine2623 thanks for your answer but this discussion seem that have the only goal to fill empty page.

1) i've try to disable page cache module and report above that the problem is not related to cache module
2) page cache module does not chache personal page of logged in users

Why this bug ONLY happen in debug mode? is something related to prestashop error handling i can suspect, when debug mode allow execution of error page the backoffice order detail work (and not throw any errror), when disable debug mode prestasthop throw error and stop page render.

Any good idea or i need to close this issue ?

Thanks

**Comment by matteolavaggi** [comment]
There is NO PHP erro rlog entry, only web server 500 error:
naws01 nginx: T=0.959 [93.39] [www.sixrace.it] [-] 500 "GET /it/index.php?controller=order-detail&id_order=1472 HTTP/2.0" "https://www.sixrace.it/it/cronologia-ordini" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-" UT="0.960"



[93.39.] [www.sixrace.it] - - "GET /it/index.php?controller=order-detail&id_order=1472 HTTP/1.1" 500 - "https://www.sixrace.it/it/cronologia-ordini"


[93.39.] [www.sixrace.it] - - "GET /it/index.php?controller=order-detail&id_order=1472 HTTP/1.1" 500 - "https://www.sixrace.it/it/cronologia-ordini"

After MANY TROUBLE we try to activate and deactivate debug mode 10 times, we can get this screen error but i'm not shure if its ok or not .. debug mode is a bit buggy, we real not know if its enable or not before see some error ...



(1/1) FatalErrorExceptionError: Cannot declare class BT_GactBaseDynTags, because the name is already in use
--
in base-dynamic-tags_class.php line 12
at BT_GactHookDisplay->displayHeader()in hook-display_class.php line 42
at BT_GactHookDisplay->run()in hook-ctrl_class.php line 54
at BT_GactHookCtrl->run()in gadwordstracking.php line 298
at GAdwordsTracking->execHook()in gadwordstracking.php line 264
at GAdwordsTracking->hookDisplayHeader()in pagecache.php line 1720
at PageCache::execHook()in Hook.php line 24
at Hook::coreCallHook()in Hook.php line 355
at HookCore::callHookOn()in Hook.php line 907
at HookCore::exec()in FrontController.php line 556
at OrderDetailController->initContent()in OrderDetailController.php line 35
at OrderDetailController->initContent()in Controller.php line 291
at OrderDetailController->run()in Dispatcher.php line 387
at Dispatcher->dispatch()in index.php line 28
at {main}()in index.php

**Comment by florine2623** [comment]
Again, this issue is relate to your module page cache. The problem does not come from PrestaShop core.
Please uninstall your module or contact the developer of that module.
I will close your ticket. Thank you for understanding.
