### ISSUE TITLE
CSV import extremely slow on PS 1.5.3.1

### ISSUE THREAD

**Issue by Pepozzo** [PrestaShop/PrestaShop#191]
Hello,

I'm trying to update my store with the new CSV file. With 1.4.x i split this CSV in smaller parts (about 250/300 lines per file) and everything worked always fine.

But with 1.5.3.1 also a file with 50 lines fails to be updated and I receive "Error 500".

Server configuration is the same. Nothing was changed.

Thanks,
Stefano

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
