### ISSUE TITLE
Wrong language identifier, shop is gone!

### ISSUE THREAD

**Issue by karamanh** [PrestaShop/PrestaShop#19101]
Under Localization > Advanced, I changed Language Identifier to something wrong I guess, and now my shop is gone. I've been looking in the database but could not found anything. There's a lot of tables  related to languages, but I could not find anything that would affect this. 
Version: 1.7.6.5
Thanks in advance,
//Hasan

When you enable debug mode if you see the error message: 
public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168
you can follow the solution below.
---
Thank you all, this is how I solved the problem.

Inside config.inc.php I commented out:

```
/*setlocale(LC_COLLATE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_TIME, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_NUMERIC, 'en_US.UTF-8', 'en_US.utf8');*/
```

Then i was able to reach my site again, I set the default language from drop down list under Localization, and did not touch anything in the Advanced section. Everything is working now.

For some reason images did not load properly, I needed to regenerate urls (htaccess) and now everything is perfect.

**Comment by kpodemski** [comment]
Look for the PREFIX_language table.

**Comment by colinegin** [comment]
Hello @Peytuk ,

and thanks @kpodemski for your help !

Could you check the PREFIX_language table and tell us if it is working well again ? 

Thanks

**Comment by karamanh** [comment]
Hello there @kpodemski @colinegin 
I've checked the table, but I'm not sure which one I edited by mistake, `language_code` or `iso_code`. They seem both correct to me. The problem is with the Turkish language by the way.
![image](https://user-images.githubusercontent.com/38075062/81802690-37264080-951f-11ea-893a-ef2d00207343.png)
Edit: I tried everything with language_code tr-tr, tr-TR etc.

**Comment by rdy4ever** [comment]
Hi @Peytuk 
What do you mean by "gone"? Where do you get the error? In the FO or in the BO? What's the error? You should enable [debug mode](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/) for a detailed error.

**Comment by rdy4ever** [comment]
Also, you could try to set English as active and default, to see if you can regain access to to shop

**Comment by Hlavtox** [comment]
@Peytuk Change **language_code** of turkish language to **tr-TR**

**Comment by karamanh** [comment]
Hi there @rdy4ever
The error I get is HTTP ERROR 500 
Console output is: Failed to load resource: the server responded with a status of 500 ()

Hi @Hlavtox I've already tried tr-tr, tr-TR, tr, TR (just to make sure) none of them seem to work.

**Comment by rdy4ever** [comment]
> Hi there @rdy4ever
> The error I get is HTTP ERROR 500
> Console output is: Failed to load resource: the server responded with a status of 500 ()
> 
> Hi @Hlavtox I've already tried tr-tr, tr-TR, tr, TR (just to make sure) none of them seem to work.

That's a generic server error. You need to enable debug mode in order to display a more detailed error. See how to enable it: https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/

**Comment by karamanh** [comment]
@rdy4ever I just enabled debug mode and this is the output:
Fatal error: Class 'Smarty_Internal_Undefined' not found in /home/toy4geek/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168

I'll be googling at the same time, but I wanted to share with you, maybe I get a quicker guidance here.

And below are the lines starting from 167, I'm not deep into this enough to understand what's going on..

```
if (!class_exists($class)) {
     return $this->$property_name = new Smarty_Internal_Undefined($class);
}
```

**Comment by kpodemski** [comment]
Use `tr-tr`, after that delete `/var/cache/prod` and `/var/cache/dev`

If this still doesn't help i'm not sure if you only modified language ;)

**Comment by rdy4ever** [comment]
This is how your row should look like for Turkey:
![image](https://user-images.githubusercontent.com/12268701/81848671-2648ef80-955e-11ea-9890-0ba7ea404353.png)

**Comment by karamanh** [comment]
@kpodemski Hi,
I just removed both folders, still getting the same error. I submitted a ticket to my hosting provider. I am 100% sure I did not change anything else. Actually I did not have any chance to change anything, the second I changed the parameter in the first message, the page refreshed and since then all I see is HTTP 500 ERROR.

@rdy4ever they appear to be same 
![image](https://user-images.githubusercontent.com/38075062/81848836-614b2300-955e-11ea-892e-67ab169d0dc1.png)

**Comment by rdy4ever** [comment]
I think you should set English as active.

**Comment by karamanh** [comment]
@rdy4ever I am just going to set active in English row to 1 and 0 for the Turkish row am I right?

**Comment by rdy4ever** [comment]
Yes, just to try

**Comment by karamanh** [comment]
@rdy4ever nope.. Not working.

**Comment by rdy4ever** [comment]
Then something else might be wrong. Don't you have any backup to restore?

**Comment by rdy4ever** [comment]
OH, and just one more thing to make sure. I know it's dumb but it happened to me once: you might wanna check you're editing the right database (in case you may have more, maybe one used for tests or whatever). Just make sure the db you're editing is the same one defined in `app/config/parameters.php`

**Comment by Peytuk** [comment]
Thank you all, this is how I solved the problem. 

Inside config.inc.php I commented out:
```
/*setlocale(LC_COLLATE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_TIME, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_NUMERIC, 'en_US.UTF-8', 'en_US.utf8');*/
```
Then i was able to reach my site again, I set the default language from drop down list under Localization, and did not touch anything in the Advanced section. Everything is working now.

**Comment by karamanh** [comment]
Thank you all, this is how I solved the problem. 

Inside config.inc.php I commented out:
```
/*setlocale(LC_COLLATE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_TIME, $locale.'.UTF-8', $locale.'.utf8');
setlocale(LC_NUMERIC, 'en_US.UTF-8', 'en_US.utf8');*/
```
Then i was able to reach my site again, I set the default language from drop down list under Localization, and did not touch anything in the Advanced section. Everything is working now.

@rdy4ever @kpodemski @Hlavtox @colinegin
