### ISSUE TITLE
Change product status in the BO search results

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#19105]
#### Describe the bug

You cannot change the product status in the BO search results when you click on enable / disable.

#### Steps to Reproduce

1 - Go to BO
2 - Search for a product in the search bar
3 - In the results table, click on the enable (✔️) or disable (❌) icon
4 - You are redirected to the product page, but the product status is always the same

**Screenshots**

See Screenshot : https://drive.google.com/file/d/1cpuYBronnQlCnZJXWRGngaigbuAUIb8v/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by colinegin** [comment]
Hello @PululuK,

I note it as an improvement, as I don't think it was expected that you could modify the status directly from the search listing. Clicking on any element of the search line will actually just open the product page. 
But it could be a nice improvement, i just want to make sure that it is ok for the UX team. 
Ping @TristanLDD @prestascott what do you think about this improvement ?

**Comment by TristanLDD** [comment]
Indeed, today's behavior is weird and it would be a nice improvement to be able to change status from the search results. Thanks for the report @PululuK
