### ISSUE TITLE
Purchasing not working in mobile broswer in prestashop v 1.5.0.17

### ISSUE THREAD

**Issue by augustinejenin** [PrestaShop/PrestaShop#19106]
#### Describe the bug

Purachasing is working fine in PC. When taking in mobile it dowsnt not work. when add to cart it takes to a blank page and confirmd order button takes to 404 page.

#### Expected behavior

We need the product purchase should be also work in mobile browser too.

#### Steps to Reproduce

Take in mobile broswer
1. Go to ' http://www.quesoslarra.com/ '
2. Click on ' product and add to cart then it will show an empty page.'
3. See the page. How to make purchasing works exactly like in the web view.

**Screenshots**

#### Additional information

* PrestaShop version: 1.5.0.17
![img1](https://user-images.githubusercontent.com/26268454/81798124-4a400d00-952d-11ea-8973-f1b00935f02c.jpg)

* PHP version: 5.3

**Comment by colinegin** [comment]
Hello @augustinejenin, thanks for your feedback. 

Unfortunately, PrestaShop 1.5 is has not been maintained for a few years already. 
If you are looking for support to fix your issue, you can check all options here : https://addons.prestashop.com/fr/388-support or contact a sales person to see what's the best option for your need.

Thanks !
