### ISSUE TITLE
Payment can be negative 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#19113]
#### Describe the bug

Payment can be negative, normaly it's forbiden to edit an invoice but if it's allow we need to add a négative payment.

#### Additional information

* PrestaShop 1.7
* PHP 7.
![facture](https://user-images.githubusercontent.com/5064590/81817829-84a9aa00-952d-11ea-89ba-2e7c08d7c5d0.png)
2

**Comment by ghost** [comment]
And normaly an ( avoir compta en français ) have to be generate.

**Comment by colinegin** [comment]
Hello @okom3pom ,

Thanks for your feedback, could you give me more details about the steps you've followed to get this error message ? 
I've added manually a payment in the order, and I got a successful update message.

Thanks !

**Comment by ghost** [comment]
Hello @colinegin .

Step 1 i have an order with a confirmed payment and an invoice

![step1](https://user-images.githubusercontent.com/5064590/81910667-88403e00-95cc-11ea-81a9-72f6a008ae25.png)

Step 2  i edit the price of a product 

![step2](https://user-images.githubusercontent.com/5064590/81910791-b02fa180-95cc-11ea-836d-5fb1db3f3686.png)

Step 3 i have a bad amount an a bad invoice

![step3](https://user-images.githubusercontent.com/5064590/81911101-1ddbcd80-95cd-11ea-802d-263d429a0fb2.png)

Step 4 i can't add a negative payement 

![step4](https://user-images.githubusercontent.com/5064590/81911782-09e49b80-95ce-11ea-88df-c00e6660b959.png)

![step4-1](https://user-images.githubusercontent.com/5064590/81911797-0ea94f80-95ce-11ea-9495-a747e1363b18.png)

I hop you understand my bad english.

Regards

**Comment by florine2623** [comment]
Hi @okom3pom ,
Thanks for the details !
I think the issue here is that the shipping price has been changed after you modified the price of a product. It went from 2€ to 7€.
So the issue isn't that you can't add a negative price, am I right ? Could you confirm ?
I have managed to reproduce the same issue on my test shop.
Thanks!

**Comment by ghost** [comment]
No i tried with an other order and no shipping price.

**Comment by ghost** [comment]
The issue is :

We can't add a negative price.

**Comment by florine2623** [comment]
Could you explain why you would want to add a negative amount on an order ?

**Comment by ghost** [comment]
Because it's the law and to have good statistics.

Otherwise it's VAT fraud

**Comment by ghost** [comment]
En français : 

On ne peut pas envoyer une facture de 100 € par exemple.

Faire une remise de 20 €  sans générer un avoir.

Ca voudrait dire que le client va récupérer la TVA sur 100 € alors qui'il a payé que 80 €  il devrait récupérer la TVA sur 80€ et pas sur 100 € 
En cas de contrôle d'un client le marchand risque gros. C'est pareil en Belgique je ne connais pas les règles des autres pays mais je pense que c'est la même chose.

Les stats sont également fausses avec cette permission d'édition de facture.

**Comment by matks** [comment]
I remember another discussion on this topic. It was about whether or not people should be allowed to manually modify invoices once created.*

**Basically this can be linked to the bigger question "Should PrestaShop enforce or not laws for every country ?"**

If I remember correctly (@PrestaShop/prestashop-product-team can correct me if I'm wrong) we checked with a lawyer to be sure about whether or not an invoice could be modified. And his answer :
1) It cannot be done. PrestaShop can be used anywhere in the world, and laws differ for every country. So unless a huge work is done to implement every law into PrestaShop, it will never comply to rules in the whole world.

Moreover laws evolve (so we would need to release new versions to follow laws evolution).
And actually PrestaShop cannot enforce anything. If the merchant really wants to modify something that is protected, well, he can hire a php developer to modify the code anyway. So it's pointless to try to enforce rules in PrestaShop, you cannot force people to follow them.

2) PrestaShop should not be a "rule enforcer". If you can modify an invoice in PrestaShop, it does not mean you have the right to do it ! PrestaShop is a tool, just like paper or pen. A paper invoice can be edited by writing on it with a pen, it does not become legal. PrestaShop must behave as close as possible to the real workflow of the merchant, but if a topic cannot be easily enforced (see previous point) then we simply allow people to do it, and trust them.

PrestaShop is not here to be a police officer telling people what they can do or not. Merchants, and only them, are responsible for complying with laws by, when required, not using some PrestaShop features. It's like a gun in the USA 😄buying a gun does not give you permission to kill even though you can do it.

*Edit: Ah ! I remember now. We have discovered, while migrating the "View/edit an order" page that some bulk actions on payments modify the existing invoices and were checking whether or not it was OK.

Edit2: you could consider that PrestaShop is a core software project that does 80% of the work (and this is enough for most merchants), but if you want something that fit 100% of your needs (here, making sure your shop disables VAT fraud) then you must customize it, either by using modules or by enhancing it yourself. PrestaShop can be seen as a development platform you use as a foundation, and you build your final product on top of it.

**Comment by MatShir** [comment]
> En français :
> 
> On ne peut pas envoyer une facture de 100 € par exemple.
> 
> Faire une remise de 20 € sans générer un avoir.
> 
> Ca voudrait dire que le client va récupérer la TVA sur 100 € alors qui'il a payé que 80 € il devrait récupérer la TVA sur 80€ et pas sur 100 €
> En cas de contrôle d'un client le marchand risque gros. C'est pareil en Belgique je ne connais pas les règles des autres pays mais je pense que c'est la même chose.
> 
> Les stats sont également fausses avec cette permission d'édition de facture.

@okom3pom The payment tab is only to enter positive because is to track the client payment. 
But If you want to generate a credit slip to correct an amount on the invoice, you can do it by pressing a partial refund and select the wanted amount.

**Comment by MatShir** [comment]
@okom3pom Have you try to add a discount, I might solve your pb ?

**Comment by prestascott** [comment]
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Comment by ghost** [comment]
Since I am using 1.7 in production I am sorry but you are wrong. Please ask the merchants what they think about the invoices modified by prestashop?   

_If I remember correctly (@PrestaShop/prestashop-product-team can correct me if I'm wrong) we checked with a lawyer to be sure about whether or not an invoice could be modified. And his answer :

It cannot be done. PrestaShop can be used anywhere in the world, and laws differ for every country. So unless a huge work is done to implement every law into PrestaShop, it will never comply to rules in the whole world.
Moreover laws evolve (so we would need to release new versions to follow laws evolution).
And actually PrestaShop cannot enforce anything. If the merchant really wants to modify something that is protected, well, he can hire a php developer to modify the code anyway. So it's pointless to try to enforce rules in PrestaShop, you cannot force people to follow them.

PrestaShop should not be a "rule enforcer". If you can modify an invoice in PrestaShop, it does not mean you have the right to do it ! PrestaShop is a tool, just like paper or pen. A paper invoice can be edited by writing on it with a pen, it does not become legal. PrestaShop must behave as close as possible to the real workflow of the merchant, but if a topic cannot be easily enforced (see previous point) then we simply allow people to do it, and trust them._
