### ISSUE TITLE
Missing translations display suppliers & brands on Shop > settings page BO

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19117]
#### Describe the bug

Missing translations display suppliers & brands on Shop.

![image](https://user-images.githubusercontent.com/52157233/81842643-9fd7e200-954c-11ea-84f9-d376f6e332cb.png)

#### Expected behavior

Should be translated in french.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @clotaire202 ,
Thanks for the report :)
This will be fixed !

**Comment by LouiseBonnard** [comment]
Fixed with Crowdin, the 1.7.7 catalog was not fully translated in French yet. I close this issue, thanks!
