### ISSUE TITLE
Feature Request: Multiple System Feature for Environments like Old-Backup, Live, Backup-Live, Testing with Synchronisation between them

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19118]
Hello,

as User of PS I dislike the "simple" maintenance Feature.
I rather would prefer a System like the "big players" got, with multiple Servers or Environments, so your Shop is always accessible without any loss of data between them.

The usual Shop system is the "main live system" in my thoughts, so when maintenance is activated, you can redirect for another IP.
I could set up a copy of the Live Shop System being available under the maintenance IP,
but if done so you have troubles to sync. the data from the "Maintenance Live System" back to your "Main Live System".

So it would be great if there would be some kind of a sync feature, to include the new orders, new customers, the messages wrote within the system and other changes of the "Backup System" as soon as you are done with modifying your "Main Live System".

As soon as there is some kind of sync feature, you could even think of new possibility, like running a Backup Server with 100% up-to-date Data (Orders/Customers etc.) but with an older Shopsystem. 

For example: I run 1.7.6.5. as my "Main Live System" at the moment. As soon as 1.7.7. is available, I would put this onto my "Testing System" and configure it. If it works, I would go into maintenance mode and redirect all customers to the "Maintenance Live System" which is a 1:1 copy of the 1.7.6.5.
Now I can upgrade my "Main Live System" to 1.7.7, and deactivate maintenance again, so this shop is getting accessed again. The new Data from the "Maintenance Live System" will be integrated into my "Main Live", so the shop has all the data.
Now I would perform the same for my "Maintenance Live System" and upgrade to 1.7.7.

My "Backup System" would still work on 1.7.6.5,
and in case my 1.7.7 Main Live, Maintenance Live and Testing Systems have some errors, I could go for maintenance mode again and redirect the Users to the "Backup System" still running 1.7.6.5 but with all the customers/orders/messages from the "Main Live".
Now I have time to clear all the issues of the other Systems,
and later when I turn maintenance mode off so the User sees "Main Live" again - all the new customer/order/message data could be synced from the "Backup" to the "Main Live" and others.

Also you could do another System for doing all the Updates and Testing: After Upgrading a System and checking everything works, you could than sync down the upgrades from the "Testing" to your "Main Live System" and the "Maintenance Live" System - this time only syncing PS Core files and Modules, but no customer data/orders/messages.

I think you get my point already, that some Synchronization Feature would be great, which again should be "modular" so any User can simply configure as many Systems as he likes in the Back Office, and simple select what parts of what System will get synced in which direction. Maybe this can even be automated, so if you are really rich in Storage Space, you could perform automated Backups and always roll back to any of them for any part of the shop you desire.

By this, an always Live System could be accomplished, with the possibility to have Backups of older Software Versions but with all the new Data, and on the other hand newer software versions of the system to testing and preparing updating of the other systems.
Also you can have multiple physical instances, like running the software at different physical servers, so in case you have some hardware issue or connectivity issue, the domain could be redirected to some system that is available.

Would be nice to see this today in a year if you have nothing more urgent to do :)

Thanks

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
Thanks for the recommandation, you request will be analyzed!
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

Is this something that could be implemented ?

Thanks!

**Comment by matks** [comment]
Hello, sorry for late answer but I think this cannot be done in PrestaShop.

PrestaShop is an application mainly powered by PHP, CSS, JS and HTML. It does not allow us to provide capabilities like Backup, switch between Versions, Enabling or disabling live systems. This would rather been done at the level of the infrastructure you are using, possibly powered by something like [kubernetes](https://kubernetes.io/).

I might have misunderstood the topic though. Wdyt @PierreRambaud ?

**Comment by matks** [comment]
Hello again, no more answers from maintainers team. Even though we could try to walk this way with PHP, I don't think this is a good thing for PrestaShop. Hosting environments have tools a lot more efficient to achieve this. PrestaShop software must focus on its main features: be a e-commerce CMS, allow people to sell, be customizable
