### ISSUE TITLE
Tax incl. is mentioned in cart for B2B customers

### ISSUE THREAD

**Issue by Cameros-agency** [PrestaShop/PrestaShop#19110]
#### Describe the bug

Hello,
We're having an issue on Prestashop 1.7.6.5 with cart total. The shop is located in France. It seems like Prestashop always calculate total with taxes even if customer has an adress with VAT number and is located in a EU country.
For example, you can see in this picture a cart where customer has an german address  without VAT number. Taxes are included regarding taxes rules we defined so everything is ok.
![cart_withtaxes](https://user-images.githubusercontent.com/6168624/81811234-99ce0b00-9524-11ea-8f20-962ce7ac4cfc.jpg)

But if i change the address with one with VAT number (still in Germany), subtotal is calculated without taxes but on every payement module (here ps_checkpayment and system_pay) taxes are added wich should not be the case.
![total_including_taxes_foreign_with_VAT](https://user-images.githubusercontent.com/6168624/81811322-bb2ef700-9524-11ea-80fe-7092a5e5ca0f.jpg)

If we look at Product.php in getPriceStatic we can see this code checking for VAT number in the address.
`
if ($usetax != false
        && !empty($address->vat_number)
        && $address->id_country != Configuration::get('VATNUMBER_COUNTRY')
        && Configuration::get('VATNUMBER_MANAGEMENT')) {
        $usetax = false;
    }
`
This code or similar is not present in Cart.php.
#### Expected behavior
We tried overriding Cart getOrderTotal and added these verification. Taxes are not included anymore for a UE foreign address with a VAT number.
`public function getOrderTotal(
        $with_taxes = true,
        $type = Cart::BOTH,
        $products = null,
        $id_carrier = null,
        $use_cache = true
    )
    {
        if (Tax::excludeTaxeOption()) {
            $with_taxes = false;
        }
        $address = Address::initialize($this->{Configuration::get('PS_TAX_ADDRESS_TYPE')}, true);
        if ($with_taxes != false
            && !empty($address->vat_number)
            && $address->id_country != Configuration::get('VATNUMBER_COUNTRY')
            && Configuration::get('VATNUMBER_MANAGEMENT')) {
            $with_taxes = false;
        }
        return parent::getOrderTotal($with_taxes, $type, $products, $id_carrier, $use_cache);
    }`

Is this behaviour normal or is something missing ?

#### Steps to Reproduce

1. add some products to Cart
2. create 2 addresses, one with VAT number in foreign country, one without
3. Select address with a VAT number

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

Best regards
Cimeos Development team.

**Comment by florine2623** [comment]
Hi @CIMEOS ,

You can add a new tax rule and apply it to your product. 

For example "No Tax for EU", your FR tax is activated while other EU countries are not :
![Capture d’écran 2020-05-14 à 10 49 24](https://user-images.githubusercontent.com/16019289/81913788-ba539f00-95d0-11ea-9923-d27526a0130b.png)
In the product page :
![Capture d’écran 2020-05-14 à 10 51 37](https://user-images.githubusercontent.com/16019289/81913947-f1c24b80-95d0-11ea-9bf7-c51a11371259.png)
The result in the cart is the following with address in Germany :
![Capture d’écran 2020-05-14 à 10 53 28](https://user-images.githubusercontent.com/16019289/81914133-2e8e4280-95d1-11ea-9fe8-d9beb505ca14.png)
In France :
![Capture d’écran 2020-05-14 à 10 53 18](https://user-images.githubusercontent.com/16019289/81914151-35b55080-95d1-11ea-91e2-519f5f11f646.png)

**Comment by Cameros-agency** [comment]
Hello @florine2623 ,
Thank you for your reply !
You're right but you did your test as an individual, not as a company. Here are more information about our issue.

A tax rule with 20.00% tax for EU country is defined in back-office. This tax is applied to every customer in those countries. However, if the customer is a company (i.e. has a VAT number) we noticed that product prices in cart are taxes excluded, which is behaviour defined by this code in Product.php:
`if ($usetax != false && !empty($address->vat_number) && $address->id_country != Configuration::get('VATNUMBER_COUNTRY') && Configuration::get('VATNUMBER_MANAGEMENT')) { $usetax = false; }`

but total in every payment module (i.e. ps_checkpayment, systempay etc...) is taxes included wich should not because the customer is a company.
This is what is displayed without the override mentioned above:
![total_including_taxes_foreign_with_VAT2](https://user-images.githubusercontent.com/6168624/81919607-58973300-95d8-11ea-852b-c31a54b1285f.jpg)

and this is what is displayed with override mentioned above:
![total_foreign_VAT_should_be2](https://user-images.githubusercontent.com/6168624/81919642-6482f500-95d8-11ea-9d15-4ab8aacad937.jpg)

Thanks again for your reply !
Cimeos Develoment Team

**Comment by florine2623** [comment]
Hi @CIMEOS ,
Thanks for the clarification !
I did manage to reproduce this on my PS 1.7.6.5.
Price for customers :
![Capture d’écran 2020-05-15 à 17 39 33](https://user-images.githubusercontent.com/16019289/82069122-2e766b80-96d3-11ea-93b3-7c8cc4fb39fd.png)
Price for B2B customers : 
![Capture d’écran 2020-05-15 à 17 40 11](https://user-images.githubusercontent.com/16019289/82069151-37673d00-96d3-11ea-944e-224f8540ebce.png)
This is my cart as a B2B customer :
![Capture d’écran 2020-05-15 à 17 42 54](https://user-images.githubusercontent.com/16019289/82069458-9b8a0100-96d3-11ea-9ea8-78f8ba644f45.png)

If you have a PR for that, you could send it.
Mean while, I will put this into our roadmap.
Thanks!

**Comment by LouiseBonnard** [comment]
Hi there, thanks @florine2623 and @CIMEOS! I'm not sure to understand where does the issue comes from: is it a code issue or a wording issue?

I understand that, when in a B2B context, the FO product page does not mention '_TTC_' (✅) while the checkout mentions '_(tax incl.)_' (❎). It should be '_(tax excl.)_' instead.

If the code is right, it just displays the wrong string (only the string needs to be fixed). If the code is not right, it needs to be fixed while making sure it brings the right string. :-)

**Comment by Cameros-agency** [comment]
Sorry for this late response.
Hi @LouiseBonnard, thanks for your reply!
I forgot to mention that B2B client mode is disabled. Most targeted customers are private individual, that's why we detect companies accounts regarding VAT number only. We did not define a "Company" group for customers.

@LouiseBonnard I think this is a **code issue** since an override of Cart.php getOrderTotal solved it.
![CartWithTaxes](https://user-images.githubusercontent.com/6168624/82792124-28208600-9e6f-11ea-8311-8d72b2a295c6.jpg)
As you can see in this screenshot, the order total on left is taxes included (i.g. 86.99€). However, since the account who's ordering is a company (has a VAT number) the order total should be 72.49€ and taxes displayed underneath should be at 0.00€.
If I override getOrderTotal function with this:
```
public function getOrderTotal(
        $with_taxes = true,
        $type = Cart::BOTH,
        $products = null,
        $id_carrier = null,
        $use_cache = true
    ) {

        if (Tax::excludeTaxeOption()) {
            $with_taxes = false;
        }
        $address = Address::initialize($this->{Configuration::get('PS_TAX_ADDRESS_TYPE')}, true);
        if ($with_taxes != false
            && !empty($address->vat_number)
            && $address->id_country != Configuration::get('VATNUMBER_COUNTRY')
            && Configuration::get('VATNUMBER_MANAGEMENT')) {
            $with_taxes = false;
        }
        return parent::getOrderTotal($with_taxes, $type, $products, $id_carrier, $use_cache);
    }
```
then I get the expected behaviour, taxes are not included anymore for a company account as you can see in next screenshot:
![cartWithoutTaxes](https://user-images.githubusercontent.com/6168624/82793709-a8e08180-9e71-11ea-9d1a-29b91a9536b4.jpg)

As I mentioned in the description, I based the override on Product.php getPriceStatic line 3200 to 3215:
```
// retrieve address informations
$address = Address::initialize($id_address, true);
$id_country = (int) $address->id_country;
$id_state = (int) $address->id_state;
$zipcode = $address->postcode;

if (Tax::excludeTaxeOption()) {
    $usetax = false;
}

if ($usetax != false
    && !empty($address->vat_number)
    && $address->id_country != Configuration::get('VATNUMBER_COUNTRY')
    && Configuration::get('VATNUMBER_MANAGEMENT')) {
    $usetax = false;
}

```

Hope those pieces of information helps!

**Comment by Hlavtox** [comment]
@CIMEOS You need to use https://github.com/PrestaShop/vatnumber in order to display taxes correctly for foreign business customers. You set your "home" country and it will automatically set tax rate to 0 if a foreign customer fills the VAT number.

Has some bugs https://github.com/PrestaShop/PrestaShop/issues/19634, but works.

**Comment by Cameros-agency** [comment]
Hi @Hlavtox, thanks for your suggestion! 
However, vatnumber module is already configured with our "home" country. As you can see in this screenshot. 
![VATModuleConf](https://user-images.githubusercontent.com/6168624/84353890-3fc27300-abc0-11ea-855f-5e6d1cb818bd.jpg)

It works perfectly on each product but once you get to the order total, taxes are still included.

**Comment by Hlavtox** [comment]
@CIMEOS I think the issue is with your aftermarket module. 🤔

Try with the Prestashop official vatnumber module and I think it will work fine.

**Comment by Cameros-agency** [comment]
@Hlavtox 
I don't know why but the official vatnumber module wasn't available in "installed modules" section in back-office, even if I could see it with FTP. I installed 2.1.0 version from[ here](https://github.com/PrestaShop/vatnumber) and now it works! Taxes are not included anymore for foreign business customers. Thanks a lot! I close this issue.

**Comment by Hlavtox** [comment]
@CIMEOS You're welcome bro. 🍺 

It's not officially supported on 1.7, it works fine though. Just disable the online VIES vat number validation. The validation service can be unavailable and customer's will not be able to save the address. I made a issue for this. https://github.com/PrestaShop/PrestaShop/issues/19634
