### ISSUE TITLE
Productcomments error with product as array

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#19122]
#### Describe the bug

With productcomments v4, the hookDisplayProductListReviews trying to handle a ProductLazyArray but never check if the params it not an array (as it could be used with modules). So, the $product->getId() throw an error.

#### Expected behavior

Firsly, check that $params['product'] is not an array with an existing ID inside it.

#### Steps to Reproduce

1. Install productcomments v4
2. Install a module using a product listing (like Cross Selling On Cart)
3. Add a product to cart and show it

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @PrestaEdit ,

Could you specify the PS version you are using ?

On PS 1.7.6.5 and PS 1.7.7.0, using module productcomments v4.0.1, I could not reproduce your issue. I have also installed cross-selling in v2.0.0.

I successfully made an order.

Do you have screenshots of your error ?

Thanks!

**Comment by PrestaEdit** [comment]
Hi @florine2623 ,

Every PS 1.7 version ; it's not the cross-selling module but the "Cross Selling On Cart", by Presta-Module. It's the one I've in example, but there is surely so many others as it.

**Comment by florine2623** [comment]
Hi @PrestaEdit ,
Ok thanks for the details.
But I can't reproduce your issue. Could you send me the error ? Or a screenshot ?
Thanks!

**Comment by PrestaEdit** [comment]
Hi @florine2623 ,

There is.

![572](https://user-images.githubusercontent.com/2631425/82034177-20f2be80-969e-11ea-9530-6705054993a4.png)

**Comment by florine2623** [comment]
Could you check Design > Positions > Search for module Product comment and see it is hooked on displayProductListReviews like so :
![Capture d’écran 2020-05-15 à 14 26 30](https://user-images.githubusercontent.com/16019289/82050250-17765000-96b8-11ea-81f7-083b22cddcc0.png)
Thanks!

**Comment by PrestaEdit** [comment]
Of course, is it. If not, it will not throw this error.

The error is that the $params['product'] is handled as a LazyArray, but it's not everytime the case.

**Comment by florine2623** [comment]
When disabling cross selling on cart module, do you face the issue ?

**Comment by PrestaEdit** [comment]
No ; but it's quite normal.

I say you than this module use a product list with an array of products ; it's work great. The fact is that this specific hook of productcomments think we already sent a LazyArray. It's not the case. This module is an exemple, but it could be done on a lot of them.

**Comment by florine2623** [comment]
@PrestaEdit ok thanks for clearing that up. These 2 modules are not compatible then.
I will ping our dev team.
Please stay tuned.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

@PrestaEdit is having issues in having 2 modules working together. (One from PrestaShop, other from Presta-Module)
Is there something that can be done on our end ?

Thanks!

**Comment by NeOMakinG** [comment]
Hey @PrestaEdit .

Managed to reproduce it on develop also

![image](https://user-images.githubusercontent.com/14963751/84054289-79725e80-a9b3-11ea-84be-8ef57abeebd3.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@NeOMakinG could you please add the label "bug" or "improvement" ?
And the severity if it's a bug ?

**Comment by marshom** [comment]
Hello,
We have the same problem as PrestaEdit, with Prestashop 1.7.6.5, the last update of Productcomments module 4.1.0, and some module who made a list of some product, who generate a 500 error with the getid function of Productcomments : 

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getId() on array in /xxxx/modules/productcomments/productcomments.php:968\nStack trace:\n#0 /xxxx/classes/Hook.php(970): ProductComments->hookDisplayProductListReviews(Array)\n#1 /xxxx/classes/Hook.php(355): HookCore::coreCallHook(Object(ProductComments), 'hookdisplayProd...', Array)\n#2 /xxxx/classes/Hook.php(907): HookCore::callHookOn(Object(ProductComments), 'displayProductL...', Array)\n#3 /xxxx/config/smarty.config.inc.php(167): HookCore::exec('displayProductL...', Array, NULL)\n#4 /xxxx/classes/Smarty/SmartyLazyRegister.php(83): smartyHook(Array, Object(Smarty_Internal_Template))\n#5 /xxxx/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/0a/51/f1/0a51f1d352e807eada7822356cc8c3530f5b42e8_2.module.jsellersubscriptionviewst.php(148): ...\n'

#smarty compile file L.148
echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['hook'][0], array( array('h'=>'displayProductListReviews','product'=>$_smarty_tpl->tpl_vars['product']->value),$_smarty_tpl ) );

any hope that this will resolved soon ?
For now we have disable the Productcomment module.
Thanks in advance

**Comment by marshom** [comment]
Hello @NeOMakinG , @florine2623 , @marionf 
Any news about this problem ?
Thank you

**Comment by NeOMakinG** [comment]
It should be handled by a @PrestaShop/prestashop-maintainers , just keep an eye when it's assigned to someone or when it has a linked PR

**Comment by PrestaEdit** [comment]
Hi everyone,

It's like this PR solve this issue: https://github.com/PrestaShop/productcomments/pull/60
