### ISSUE TITLE
On BETA 1.7.7, order page not full translate

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#19129]
#### Describe the bug

In the details of a command, there are still some untranslated terms in French
“Add a discount“
from
Validated orders placed...

#### Steps to Reproduce

Install Prestashop 1.7.7.0 in french langage

**Screenshots**

![Capture d’écran 2020-05-14 à 14 56 12](https://user-images.githubusercontent.com/2854750/81937069-627a5f80-95f3-11ea-9004-55a3b4218d8d.png)

#### Additional information

* PrestaShop version: 1.7.7.1 beta 1
* PHP version: PHP 7.2

**Comment by florine2623** [comment]
Hi @olecorre ,
Thanks for the report ! I managed to reproduce this issue. 
This will be added to our roadmap.
Thanks!

**Comment by colinegin** [comment]
FYI @LouiseBonnard

**Comment by LouiseBonnard** [comment]
Hello @olecorre, thanks a lot for your report! You're right, French translation has not reached 100% on Crowdin yet, this is why some new wordings are still in English. It should be fully available by the weekend, I'll check next week. ;-)

**Comment by LouiseBonnard** [comment]
It should be all translated now, I've finished the translation on Friday night. All the strings mentioned have been translated into French. Can you please check and confirm? If a string remains untranslated at this point, it is a bug!

**Comment by colinegin** [comment]
Hello @florine2623 do you reproduce this problem ?

**Comment by Robin-Fischer-PS** [comment]
Hi @colinegin @olecorre ,

The "Add a discount" is now correctly translated in French on 1.7.7.x branch (I also checked some other missing translations : They are now OK).

So this issue is fixed :)
