### ISSUE TITLE
[SF Migration] Use Symfony components for authentication instead of legacy system

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19124]
We should use Symfony to authenticate user instead of legacy system.

@rokaszygmantas already implemented it into https://github.com/PrestaShop/PrestaShop/pull/13733

However
- we must check nothing has changed at session & cookie level to ensure compatibility with legacy pages
- we must try, when possible, to keep old login system functional because some modules use it to bypass authentication (example: SSO or firebase authentication)
- if we cannot keep compaibility, the breaking change in authentication system must be explained in documentation and new authentication system must be explained
- whether or not we break old behavior, the new system must be designed to be easily extensible to allow modules to authenticate users

**Comment by matks** [comment]
We expect to deliver this for 1.7.8 along with the migration of the display of the page (see https://github.com/PrestaShop/PrestaShop/issues/12953) but we'll take all the time needed for it, don't worry 😄

**Comment by toutantic** [comment]
An important requirement is to make sure that we make it easy for a module to replace the authentification system with an external system. For example to integrate with an SSO system.
But I guess the standard symfony component will make that easier.

**Comment by cedricfontaine** [comment]
With the hook displayAdminLogin we have implemented our own oAuth2 authentication system. We still rely on Prestashop employee table but authentication is managed outside. It works well for us.

**Comment by LukasK13** [comment]
> With the hook displayAdminLogin we have implemented our own oAuth2 authentication system. We still rely on Prestashop employee table but authentication is managed outside. It works well for us.

Hey @cedricfontaine 
It would be awesome if you could share your solution.
Thank you.

**Comment by matks** [comment]
PrestaShop 9 uses Symffony authentication component 🪨 

Fixed by https://github.com/PrestaShop/PrestaShop/pull/35983
