### ISSUE TITLE
Different shipping costs in the order history page (FO)

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19132]
#### Describe the bug

There are different shipping costs in the order history page (FO) when order is placed with tax. In the subtotal table is shipping cost correct with tax. But in the next table is cost without tax.

The problem is in the getShipping funcion, in the file
src/Adapter/Presenter/Order/OrderDetailLazyArray.php

#### Steps to Reproduce

1. made clean PS 1.7.7 beta1 installation (but the bug is also in previous PS versions)
2. eshop has setup as tax payer (20%)
3. carrier has also cost with tax
4. place an order and go to order history in your customer account.
5. see the different shipping costs

Screenshot: https://pasteboard.co/J8l1So6.png

#### Additional information

* PrestaShop version: 1.7.7 beta1 (also in previous PS 1.7 versions)
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Caleydon ,
This is not a bug, the page is showing delivery fee tax incl. and tax excl. :
![Capture d’écran 2020-05-15 à 10 37 07](https://user-images.githubusercontent.com/16019289/82030190-60b6a780-9698-11ea-9416-746ca571524d.png)
Thanks!

**Comment by Caleydon** [comment]
I know but why? On the one page is under same label different value? It should be added inc. tax and excl. tax labels. But is there any good reason display customer who place the order with tax, shipping cost without tax?

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

In the Customer Account > Order History > Details
Some fields are not clear enough : _Shipping & Handling_ and _Shipping Cost_ have different prices. One is Tax incl and the other tax excl, it should be mentioned somewhere.
![Capture d’écran 2020-05-15 à 10 37 07](https://user-images.githubusercontent.com/16019289/82065855-ece3c180-96ce-11ea-85b4-cfd54801b577.png)

Can this be done ?

Thanks!

**Comment by MatShir** [comment]
@Caleydon Nice catch, IMO the best solution will be to have the page displays with a tax or without tax depending on the customer group, like B2B business could display without tax and B2C with tax included for example.

So step 1: should be to align the information
step 2: coordinate the value depending on the customer group setting and with the tax policy
