### ISSUE TITLE
unit_price_ratio will be reset to zero when Product constructer is called with $full = false and product.update() is called

### ISSUE THREAD

**Issue by tsarnow** [PrestaShop/PrestaShop#19130]
#### Describe the bug

The unit_price_ratio in table product will be reset to zero in php when a product is load via the Product constructor with the parameter `$full = false` and updated afterwards. 

#### Expected behavior

The field unit_price_ratio shouldn't be overwritten because the product wasn't fully loaded. 

#### Steps to Reproduce

1. Go to 'Catalog > Articles'
2. Select an article
3. Go to tab 'Prices'
4. Enter a price and a unit for `price per unit`
5. run the code below 
6. reload the 'Prices' tab and the number is now gone

**Code**
This code line causes the issue:
`$product = new Product($id_product, false, $this->context->language->id);`
`$product->update();`

The problem is in Product.php in function getFieldsShop due to $this->unit_price is null because it wasn't loaded in the first place
``` 
public function getFieldsShop()
{
    $fields = parent::getFieldsShop();
    if (null === $this->update_fields || (!empty($this->update_fields['price']) && !empty($this->update_fields['unit_price']))) {
        $fields['unit_price_ratio'] = (float) $this->unit_price > 0 ? $this->price / $this->unit_price : 0;
    }
    $fields['unity'] = pSQL($this->unity);

    return $fields;
}
```

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.22

**Comment by florine2623** [comment]
Hi @tsarnow ,
I couldn't reproduce your issue.
Please check my screen record :
https://drive.google.com/file/d/1MqnsWPt0pfmgAaqfDnh-TktlxRY9I7Yv/view
Thanks!

**Comment by tsarnow** [comment]
Hi @florine2623, the problem is not the screen function. 
The problem happens if some extension for example runs the following php code (as mentioned in the ticket as well): 

`$product = new Product($id_product, false, $this->context->language->id);
$product->update();`

We used the extension `advanced seo` which get called every page reload and these guys used the mentioned code above. This behavior in prestashop is error prone and should be avoided. 

Is this more clear? I tried to narrow the issue down to source code level so you can't really reproduce it with a regular setup.

**Comment by florine2623** [comment]
Hi @tsarnow ,
Thanks for the clarification! The problem comes from an external module ?

**Comment by tsarnow** [comment]
Hi @florine2623 yes it was triggered by the extension advanced seo. 
So I investigated the problem and it gets boiled down to the PHP problem mentioned above.

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers hey guys, could you help to reproduce this one?
Is it an issue from PS side or on the module? How problematic is it?

**Comment by eternoendless** [comment]
This is not a bug, the module's implementation is wrong. 

Partial updates on an ObjectModel only work well when you specify the exact fields you want to update using `$product->setFieldsToUpdate()`. By default, ObjectModel assumes all the fields are supposed to be updated (which obviously won't yield good results if the object has been partially loaded).

This has been like so since 1.5

I'd really like getting rid of this ObjectModels for the next major...
