### ISSUE TITLE
Add hook "displayAfterTitle" in the theme

### ISSUE THREAD

**Issue by cdcvince** [PrestaShop/PrestaShop#19135]
**Problem**
We need a hook at the very top of the page, before all the loading of js and css, for example for A/B test or analytics modules.

**Solution**

Add directly after "</title>" in the file _themes/classic/templates/_partials/head.tpl_ the code :
```
{block name='hook_after_title_tag'}
      {hook h='displayAfterTitleTag'}
{/block}
```

**Comment by NeOMakinG** [comment]
ping @PrestaShop/prestashop-core-developers wdyt ?

I don't know if this is already existing

**Comment by PierreRambaud** [comment]
Hi,
What kind of changes do you need to do on your template? There are hooks for stylesheets and javascript, there are also `actionFrontControllerSetVariables` and `actionFrontControllerAfterInit`. Could you tell us more about what you wanted to do?

**Comment by cdcvince** [comment]
I need a place to execute JS code before everything else, basically for loading A/B test ok analytics code for performance etc ...

I am the developper of a best seller module on Prestashop, and during installation of the module, the tpl file is modified to add this hook.

This is not a good practice, and having this hook in the core theme like "displayAfterBodyOpeningTag" would be much better.

**Comment by PierreRambaud** [comment]
This is something you should be able to do by extending smarty blocks.
https://www.smarty.net/docs/en/language.function.block.tpl

Not sure it's a good idea to add hooks for one use case. Otherwise we will have to do it for `title`, `body`, `html` and all other html tags :thinking:

**Comment by cdcvince** [comment]
It is already done for the body tag (and it's very useful) in the file layout-both-column.tpl :

```
    {block name='hook_after_body_opening_tag'}
      {hook h='displayAfterBodyOpeningTag'}
    {/block}

    {block name='hook_before_body_closing_tag'}
      {hook h='displayBeforeBodyClosingTag'}
    {/block}
```

Also, the title tag is remarkable since it's the first instruction of a html page, and it's unique.

With your solution of extending smarty block, how do you proceed in a clean way with a module? If the file has already been extended?

**Comment by PierreRambaud** [comment]
@cdcvince You are right these hooks are already in the templates.
Feel free to create a pull request, we will be glad to merge it :)
Don't forget to edit the hook.xml file and the SQL file to be sure they have a description :)
