### ISSUE TITLE
Remove Google+ share button in the ps_sharebuttons module

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19147]
Please remove support already terminated Google+ social network in the ps_sharebuttons module.

![ps_sharebuttons](https://user-images.githubusercontent.com/2806752/81981428-945de700-9630-11ea-9f1a-54747cd49d5d.png)

#### Additional information

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.2

**Comment by PululuK** [comment]
Hi @Caleydon 
See https://github.com/PrestaShop/ps_sharebuttons/pull/29

**Comment by Caleydon** [comment]
Sorry for duplicate issue.
