### ISSUE TITLE
Different global font-size on order history page (BO)

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19144]
#### Describe the bug

Order history page (BO) has defined global font 2px smaller than on other pages. Tested on clean PS installation.

#### Steps to Reproduce

See on the video: https://vimeo.com/418580145/d0a0dbbc4c

#### Additional information

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Caleydon ,
Thanks for the report, please stay tuned !
