### ISSUE TITLE
"Prices drop" page mislabeled title

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19145]
#### Describe the bug

"Prices drop" page mislabeled title. “Prices drop” doesn’t mean “On sale”. The product On sale does not have to have a reduced price. It’s two different types of promotion. The page should be correctly titled as “Prices drop”.

Edit the getListingLabel function in the file /controllers/front/listing/PricesDropController.php in order to fix the issue.

![prices-drop-page](https://user-images.githubusercontent.com/2806752/81980429-df76fa80-962e-11ea-8b90-1cdd8398c4c9.png)

#### Additional information

* PrestaShop version: 1.7.7 beta 1 (also in the previous 1.7 versions)
* PHP version: 7.2

## SPECS

- [ ] In the BO product page > Princing tab, it should be "Display the "Price drop!" flag on the product page, and on product listings.". If you check the box and verify the flag on the product page and product listing, it should be "Price drop!" => Done in PR #24109
- [ ] On the prices-drop page in FO, the h1 and the breadcrumb should be "Prices drop" => Done in #23858

**Comment by florine2623** [comment]
Hi @Caleydon ,
Thanks for the report.
Please stay tuned !

Also, keep in mind that this title can be changed manually directly in Shop Parameters > Traffic & SEO

Thanks!

**Comment by florine2623** [comment]
Hi @Junebyun ,

Should this page title be changed on future versions ?

Thanks!

**Comment by Caleydon** [comment]
Maybe you don't understand the issue. The Page title, Meta description and URL is defined correct in Shop Parameters > Traffic & SEO. It's "Prices drop". But the H1 title and page breadcrumb is defined in the code - see getListingLabel function in the file /controllers/front/listing/PricesDropController.php. And there is defined as "On sale".

**Comment by florine2623** [comment]
After checking with our team, this is not a mislabeled title .
If you need to change the title of the page as you desire, you can do it directly on the Traffic & SEO page.

I think what you mean is that you want a new feature that allow you to have a page a price drop ?
- On sale : products that you had put a certain amount of sale on
- Price Drop : You decreased the price of a product without is being a discount

Could you confirm ?

**Comment by Caleydon** [comment]
You didn't understand the point of this issue. On the "Prices drop" page are products with special price and no On sale. Please look at image. I hope you will understand now.

![on-sale-vs-special-price](https://user-images.githubusercontent.com/2806752/82429559-68a58b80-9a8c-11ea-9c96-17f9d4b727f2.png)

**Comment by LouiseBonnard** [comment]
Hi there, you're right, the wording is mixed up in the theme between the _Specials Block_ module and the _Prices Drop_ page - it is supposed to be more or less the same but it combines 1/ special prices like products benefit from specific prices as well as 2/ special prices like when products are on sale. So the wording needs to be studied to be more accurate and then harmonized.

**Comment by Hlavtox** [comment]
@LouiseBonnard @Caleydon @florine2623 

Caleydon is right, prices-drop controller is listing every product, that has some kind of discount on it. It's not a page that lists on-sale products.

I promoted creation of the page here, I think it would be useful... https://github.com/PrestaShop/PrestaShop/issues/15384

**Comment by Junebyun** [comment]
Hi there, I think we should harmonize:

- the text in the footer of the FO "_Prices drop_" 

- and the H1 title of the page "_On sale_" (appearing once you click on "_Prices drop_")

by either "_Sale_" or "_Promotion_". Both are widely used terminologies and I think users won't have problems in understanding it. Also, only products that have some kind of discount are listed in the "_Prices drop_" page, so it matches the context.

**Comment by Caleydon** [comment]
> 
> 
> Hi there, I think we should harmonize:
> 
>     * the text in the footer of the FO "_Prices drop_"
> 
>     * and the H1 title of the page "_On sale_" (appearing once you click on "_Prices drop_")
> 
> 
> by either "_Sale_" or "_Promotion_". Both are widely used terminologies and I think users won't have problems in understanding it. Also, only products that have some kind of discount are listed in the "_Prices drop_" page, so it matches the context.

Please use the same phrase. Do you think it's correct for customers, when they click on "Prices drop" link and get page with "Promotion" name? Why are you trying use variations of this word? Different in the link and different on the target page? Name the page same as the link. Other variantions of the word you can use in the page meta-description.

**Comment by LouiseBonnard** [comment]
Dear @Caleydon, this issue precisely exists to think about a more consistent customer experience. ;-)

You might have misunderstood @Junebyun, her idea is to **select the most accurate wording and apply it everywhere** to offer the customers a harmonized shopping experience = the text in the footer, the title of the page, the name of the URL, etc.

**Comment by Junebyun** [comment]
Dear @Caleydon, perhaps I wasn't clear enough in my comment. :p

My suggestion is to indeed harmonize everything to either "_Sale_" or "_Promotion_". 

Between those 2 terminologies, I would go with "_Sale_", as it is a page that shows products that have reduced prices. Plus, it will also be consistent with the "_on sale_" tag.

**Comment by Caleydon** [comment]
Please note that "On sale" is something different from "Price drop / Promotion". The product can has "On sale" sticker but no special / lower price. Plase stop operate with "On sale" here again. It's completely different feature of PrestaShop nothing to do with special product price. Do you understand that?

Whe you add "On sale" sticker on the product, it's graphic sticker only. There is no other feature. You can add  "On sale" sticker also for new products or every product in your catalog. 

When you setup special price, the product will be listed on "Prices drop" page - currenty wrong labeled as "On sale" page. And it is an issue I want to correct in the PrestaShop.

Please read again my post where is all explained
https://github.com/PrestaShop/PrestaShop/issues/19145#issuecomment-631355506

**Comment by Caleydon** [comment]
As I read your post in paralel ticket https://github.com/PrestaShop/PrestaShop/issues/15384#issuecomment-653549034
you are completely out of topic. You didn't understand the issue.

**Comment by Progi1984** [comment]
Thanks @marionf
