### ISSUE TITLE
Credit slip numbering need reset each year + other invoicing improvements

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19149]
It’s missing feature.... Please rework Credit slip numbering. Right now the Credit slip number is inthe ffact database table ID of the slip record. It’s not allow reset numbering each year or other numbering manipulation. It’s a big issue for an accountants. So Credit slips generated by PrestaShop can’t be used in the business accounting. 

Then the ability to reset the Credit slip numbering and ability add current year in the number (same as Invoce numbering) could be cool. 

Another improvement - the Credit slip should display number of related invoice.

And the last improvement - add ability to define indetifier of the invoice and credit slip numbering queue. If merchant have more than one eshop, each one must generate own unique numbering queue of the invoices and credit slips. 
Example: 
Eshop 1: invoice queue start with 2020100001
Eshop2: invoice queue start with 2020200001
This feature is also important when merchant run PrestaShop in multi-store mode.

**Comment by florine2623** [comment]
Hi @Caleydon ,

In total you want these 4 features :
- Be able to reset Credit Slip number every year
- Add current year automatically in Credit Slip number
- In a Credit Slip, display the invoice number related
- In Multishop, be able to set an identifier in Credit Slip number
example :
store 1 : CS1-XXX
store 2 : CS2-XXX

Can you confirm ?

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by Caleydon** [comment]
> 
> 
> Hi @Caleydon ,
> 
> In total you want these 4 features :
> 
>     * Be able to reset Credit Slip number every year
> 
>     * Add current year automatically in Credit Slip number
> 
>     * In a Credit Slip, display the invoice number related
> 
>     * In Multishop, be able to set an identifier in Credit Slip number
>       example :
>       store 1 : CS1-XXX
>       store 2 : CS2-XXX
> 
> 
> Can you confirm ?

Yes, all features are correct except for the last one. Multishop ID can't be added into numbering! 

An example: I've got 3 eshops on 3 different domains and also I've got one physical store. All is one business subject. Every eshop and store has own document numbering. It's mean I have 4 different queues (sources) of invoices and their order and credit slips etc. Each document type should have unique and increasing number without numbering gap.

So you should be able setup numbering in the PrestaShop following way:

Eshop #1 (fifth number "1" is invoice queue identifier)
- first invoce number in 2020: 2020100001
- first credit slip number in 2020: 2020100001

Physical store (fifth number "5" is invoice queue identifier)
- first invoce number in 2020: 2020500001
- first credit slip number in 2020: 2020500001

Eshop #2 (fifth number "3" is invoice queue identifier)
- first invoce number in 2020: 2020300001
- first credit slip number in 2020: 2020300001

Eshop #3 (fifth number "6" is invoice queue identifier)
- first invoce number in 2020: 2020600001
- first credit slip number in 2020: 2020600001

The invoice queue for each source of my business should produced unique numbering. It is mean, you couldn't use multistore ID in the document numbering.
