### ISSUE TITLE
Wrong price on discounted products

### ISSUE THREAD

**Issue by narciscotaie-smart2pay** [PrestaShop/PrestaShop#19156]
#### Describe the bug

A shopping cart with a product with discound has a different total price when I increase the quantity.

#### Expected behavior

The total price should be product's price x quantity.

#### Steps to Reproduce

1. Install prestashop 1765
2. Open the browser  and go to the shop front page
3. Search for "HUMMINGBIRD PRINTED T-SHIRT", notice it costs 28.68 and has a 20% discount
4. Add 2 of the above items to the cart
5. Go to the shopping cart page
6. Notice the total amount, it's with 0.01 cent higher

**Screenshots**

![image](https://user-images.githubusercontent.com/62748744/82041212-7a63e900-96b0-11ea-9488-5998432138b8.png)

#### Additional information

* PrestaShop version: 1765
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @narciscotaie-smart2pay ,

First, please change your PHP version to 7.2. PHP 7.3 is not compatible with PrestaShop 1.7.6.5.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

This is actually not a bug.

Here's the calculation :
**Discount 20%**
28.68 * 0.80 = 22.944
**2 items**
22.944 * 2 = 45.888
**Rounding of 45.888**
45.89

Thanks!
