### ISSUE TITLE
Make releases for 2.x

### ISSUE THREAD

**Issue by soullivaneuh** [PrestaShop/PrestaShop#19152]
The module is used on stable PS 1.7 but no tag is done.

This is problematic for composer installation.

**Comment by florine2623** [comment]
Hi @soullivaneuh ,

Could you specify your issue with steps to reproduce ou screenshots ?
What version of PS are you using ? What version of ps_sharebuttons ?

Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
