### ISSUE TITLE
Contact Block not showing correctly on website

### ISSUE THREAD

**Issue by JSMOnline** [PrestaShop/PrestaShop#19150]
#### Describe the bug

We needed to update phone number. I went into the 2 contact modules we have installed (Contact block v1.4.1 - by PrestaShop and Contact information block v1.2.1 - by PrestaShop) and updated to the correct number. I clicked save.
When checking the website, the number has not updated. I have done hard refresh and had others check but it's still the old number. 
It is now the correct one in the module, but not on the website.
#### Expected behavior

Contact block information to be reflected on website as required.

#### Steps to Reproduce

1. Go to module - contact block
2. Click on configure
3. Update information
4. Click Save
5. Check website www.bokay.com.au. Phone number in header and footer should be updated to 08 9489 9800 but it still displays the old phone number. 

**Screenshots**

n/a

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by Caleydon** [comment]
Did you clean PrestaShop's cache in Advanced Parameters > Performance?

**Comment by florine2623** [comment]
Hi @JSMOnline ,
With the theme you are using, there's probably another module to change. I advise you to contact directly the developer of the theme.
Or you can contact the support [here](https://addons.prestashop.com/en/388-support).
Thanks!

**Comment by JSMOnline** [comment]
I am not sure which settings to change – can you advise please?

**Comment by florine2623** [comment]
Clear cache of your website in Advanced Parameters > Performances

Again, this is not a core issue, you can contact the support for help : 
https://addons.prestashop.com/en/388-support
