### ISSUE TITLE
Compile Error Prestashop

### ISSUE THREAD

**Issue by kekkopaciello** [PrestaShop/PrestaShop#19162]
Fatal Compile Error: Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required '/web/htdocs/www.pacielloantichita.it/home/vendor/composer/../../src/Core/Group/Provider/DefaultGroups.php' (include_path='/web/htdocs/www.pacielloantichita.it/home/vendor/pear/pear_exception:/web/htdocs/www.pacielloantichita.it/home/vendor/pear/console_getopt:/web/htdocs/www.pacielloantichita.it/home/vendor/pear/pear-core-minimal/src:/web/htdocs/www.pacielloantichita.it/home/vendor/pear/archive_tar:.:/php7.3/lib/php')

anyone knows how to resolve?

**Comment by florine2623** [comment]
Hi @kekkopaciello ,
Is this a fresh install ?
What version of PrestaShop are you using ?
Please check and let me know!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
