### ISSUE TITLE
Problem with second combination

### ISSUE THREAD

**Issue by The-Land-Lord** [PrestaShop/PrestaShop#19166]
I have a problem with combinations.

I can see attributes, create combinations, but when I return to these combinations when they are created, the second one is not modifiable and the stock field disappears.
 Another curious fact is that if you allow the second combination to be eliminated, but if you go back into the product, the combination that was in position 3 and that after deleting the problem is now in position 2 has the same problem. I have tried to trace in debug mode, but can't find where the error might be. Can someone help me?

![image](https://user-images.githubusercontent.com/64405332/82124929-bd05ee00-97a2-11ea-9028-383171aab8f1.png)

I'm tracing the error, but all data about my combinatios is ok. The last file, when I lost the trace is CombinationController.php, in this code, when render the combination:

 

return $response->setContent($this->renderView(
            '@Product/ProductPage/Forms/form_combination_collection.html.twig',
            array(
                'combinationForms' => $forms,

#### Additional information

PHP 7.1.33 and Prestashop 1.7.5.2 . but I try with differents PHP versipones and the problem remains.

**Comment by florine2623** [comment]
Hi @The-Land-Lord ,
When you enable debug mode, do you see any error ?
When you open your console, do you have errors ?
Please check and let me know!

**Comment by The-Land-Lord** [comment]
Hi @florine2623 , 

thanks for your response. I don't see errors in console or debug mode when I see the combinations, but, if I try to activate the product or change any values in the combinations  there are a error:


![image](https://user-images.githubusercontent.com/64405332/82200168-fbb0bb00-98fe-11ea-9cdb-fd6c78dc8dd0.png)
![image](https://user-images.githubusercontent.com/64405332/82200383-34e92b00-98ff-11ea-83af-d0f1b4e4732b.png)
![image](https://user-images.githubusercontent.com/64405332/82200492-5d712500-98ff-11ea-903e-26b82dd9c04a.png)


I understand this error is normal with my problem, because if there are not quantity field, when update it's impossible update quantity field

**Comment by florine2623** [comment]
Thanks for the screenshots. As you said, this error in your screenshot occurs when you try to update a product with no quantity. When you edit a combination using the "pen" can you modify the quantity ?
Are you using any module for your combinations/products ?
If yes try to disable all overrides and let me know.
`overrides` folder becomes `_overrides`

**Comment by The-Land-Lord** [comment]
Hi, 


in the overrides folder, there are subfolders that contains the same file index.php withe the same code:


header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: ".gmdate("D, d M Y H:i:s")." GMT");

header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");

header("Location: ../");
exit;



By other hand, I disable the overrides in PrestaShop:

![image](https://user-images.githubusercontent.com/64405332/82425203-7ce68a00-9a86-11ea-935d-39abb47dbd70.png)




Thanks,

**Comment by The-Land-Lord** [comment]
More information about my problem.

I can change quantity value in stocks module but in the product-combinations module it is not visible.

This is the information about my PrestaShop:


![image](https://user-images.githubusercontent.com/64405332/82457700-05305380-9ab6-11ea-8b9f-59a89bac09b4.png)
![image](https://user-images.githubusercontent.com/64405332/82457767-1bd6aa80-9ab6-11ea-9955-2f11d8c60b73.png)

**Comment by The-Land-Lord** [comment]
Update about the problem. 
The origin of the problem is the theme. If I change and use the default theme, works fine, but if you select the theme that we have chosen for the store, no works. I thought that the issues only affected the approval of the store by the client, not the administration .....

**Comment by hibatallahAouadni** [comment]
Hello @The-Land-Lord 

Sorry for the late response. 
Glad to hear that problem is not related to PrestaShop Core :tada: 
Closing this issue :wink: 

Thanks!
