### ISSUE TITLE
Confirmation button on Checkout should be disabled if Terms and conditions are not approved

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#19161]
#### Describe the bug

On checkout, with PaymentOption of type Binary, I don't approve Terms and conditions but I can validate my order.

#### Expected behavior

On checkout, if Terms and conditions is not approved, all confirmation buttons should be disabled.

#### Steps to Reproduce

1. Install a payment module with a PaymentOption of type Binary.
For example : [module Payment Example v2.0.0](https://github.com/PrestaShop/paymentexample/pull/14) or [module Atos](https://addons.prestashop.com/en/payment-card-wallet/1-sips-10-worldline-atos-15-16-17.html)
2. Add a Product to Cart
1. Go to Cart
2. Click on Proceed to checkout
3. On step Payment, don't approve Terms and conditions
4. See confirmation button seems disabled
5. Click on confirmation button
6. See Order confirmation page

**Screenshots**

![checkout-payment-confirm](https://user-images.githubusercontent.com/5262628/82065448-662ee480-96ce-11ea-801c-2c040301056c.png)

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Epic** : #17034

**Comment by Matt75** [comment]
Should be fixed in this function of Core JS : https://github.com/PrestaShop/PrestaShop/blob/03032d6adb19836240047b5658988f1e64c823ee/themes/_core/js/checkout-payment.js#L84

Possible buttons :
1. `button[type="submit"]` ([module Payment Example v2.0.0](https://github.com/PrestaShop/paymentexample/pull/14))
2. `input[type="submit"]`
3. `input[type="image"]` ([module Atos](https://addons.prestashop.com/en/payment-card-wallet/1-sips-10-worldline-atos-15-16-17.html) generated by binaries)

**Comment by clotairer** [comment]
We already have a similar problem on stripe official module. It's a little tricky to retrieve if the checkbox is check. [JS use DOM id](https://github.com/202-ecommerce/stripe_official/blob/develop/_dev/js/payments.js), and it's not very good.

It could be nice to "emit" Prestashop javascript event to catch if all conditions are OK to enable the Submit button.

**Comment by Matt75** [comment]
Ping @NeOMakinG

**Comment by pitkz** [comment]
Could this Topic not be flagged as minor? EU Shops are getting suited at court if they do not comply with the GDPR, or with their need to clear for Terms and Condtions! PS is literally not safely usable by this bug - just because it works, does not mean it works legally!

**Comment by NeOMakinG** [comment]
Gonna looks at this in some days, dont worry @6xthFNGR

**Comment by hostisoft** [comment]
It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?

**Comment by NeOMakinG** [comment]
@hostisoft please create an issue and describe the exact step to reproduce, so we gan take a look

**Comment by starqus** [comment]
> It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?

Did you solve?
I have same problem with 1.7.8 
Button work fine with opera browser but does not work in chrome and opera mini etc..

**Comment by NeOMakinG** [comment]
> > It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?
> 
> Did you solve? I have same problem with 1.7.8 Button work fine with opera browser but does not work in chrome and opera mini etc..

Is it really the same problem? There is another issue where button stay disabled, which has a PR opened

**Comment by Jingael** [comment]
> > It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?
> 
> Did you solve? I have same problem with 1.7.8 Button work fine with opera browser but does not work in chrome and opera mini etc..

Me too. I updated to 1.7.8 and the pay button is disabled always....

**Comment by NeOMakinG** [comment]
It's already pushed on 1.7.8.x, you'll get it inside the next minor
