### ISSUE TITLE
Property Address->id_city is empty

### ISSUE THREAD

**Issue by boutanes** [PrestaShop/PrestaShop#19175]
[PrestaShopException]
Adresse de la propriété-> city est vide.
à la ligne 944 dans les classes de fichiers / ObjectModel.php

939.}
940. 
941. $ message = $ this-> validateField ($ field, $ this -> $ field);
942. if ($ message! == true) {
943. if ($ die) {
944. lever une nouvelle PrestaShopException ($ message);
945.}
946. return $ error_return? $ message: faux;
947.}
948.}

**Comment by florine2623** [comment]
Hi @boutanes ,
You need to change the address format in the country configuration.
International > Locations > Edit the country > Add City :
![Capture d’écran 2020-05-18 à 11 09 30](https://user-images.githubusercontent.com/16019289/82195094-1e8ba100-98f8-11ea-80e9-3d162c4fd9a3.png)
Thanks!

**Comment by boutanes** [comment]
> Salut @boutanes ,
> vous devez changer le format d'adresse dans la configuration du pays.
> International> Emplacements> Modifier le pays> Ajouter une ville: Merci!
> ![Capture d'écran 2020-05-18 à 11 09 30](https://user-images.githubusercontent.com/16019289/82195094-1e8ba100-98f8-11ea-80e9-3d162c4fd9a3.png)

merci

**Comment by florine2623** [comment]
You're welcome !

**Comment by frenchfriez** [comment]
Hi
I have the same issue, I did the correction already 
![Changed format](https://user-images.githubusercontent.com/71665846/98025693-5638c780-1e0a-11eb-9b83-0637513821ba.png)

But I still have the same issue when I import:
![prestashop import addresses error](https://user-images.githubusercontent.com/71665846/98025778-6fda0f00-1e0a-11eb-8340-67c408e41df0.png)

I also have the "Property Country->need_identification_number is empty" problem, I did set the option the tax number requirement to "NO"already

**Comment by mosilver** [comment]
Hi @frenchfriez, have you resolved this 

Country->need_identification_number is empty
Address->id_country is empty

issue when importing Addresses? We have exactly the same now.

**Comment by lmanliang** [comment]
but I didn't need city column
how can I do ?
