### ISSUE TITLE
 I would like to see my admin area like this

### ISSUE THREAD

**Issue by longerzoom** [PrestaShop/PrestaShop#19176]
Is your feature request related to a problem?
I want to pay attention to the inconvenient location of the block in orders

![b2dac8ecfe02](https://user-images.githubusercontent.com/1009343/82889835-a3f00080-9f4b-11ea-80bc-bdad8a9d187e.jpg)

Many people were grateful to you. Thank

**Comment by sowbiba** [comment]
Thanks for your time

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by eternoendless** [comment]
@longerzoom Can you please clearly explain the problem in english?

**Comment by longerzoom** [comment]
> @longerzoom Can you please clearly explain the problem in english?

Hey, eternoendless.
I have shown this location in the image quite well in the new version of PS1.7.7.0.
What I saw in 1.7.7.0 upset me more than impressed.
I want to have a function to change the discount for each item. Not a general discount.
I want my template to look like the one I made in Photoshop...
Sorry about my Russian to English translator.

**Comment by florine2623** [comment]
Hi @longerzoom ,

You want a new feature that allows you to change the discount for each product in the order page ?

Keep in mind that if you need some custom code for your own liking, this is not the place. You can contact a PrestaShop partner agency : https://www.prestashop.com/en/experts
Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
