### ISSUE TITLE
Design > Positions - wrong checkbox display

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#19170]
#### Describe the bug

icons are not positioned well

#### Steps to Reproduce

1. Go to design
2. Click on positions
3. See error

**Screenshots**

<img src="https://image.prntscr.com/image/rQCOxVabR2GXuj_QotsM4g.png" />

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by alfonsolr09** [comment]
I also add that I like this page more in the current version of prestashop 1.7.6.4 having a background to distinguish

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
I can't reproduce your issue :
![Capture d’écran 2020-05-18 à 11 14 20](https://user-images.githubusercontent.com/16019289/82195599-cacd8780-98f8-11ea-955f-c748e8cf032e.png)
What screen resolution are you using ?
Thanks!

**Comment by alfonsolr09** [comment]
Probably you have to put spanish languaje

**Comment by alfonsolr09** [comment]
@florine2623

**Comment by alfonsolr09** [comment]
I use 22" screen

**Comment by florine2623** [comment]
I still can't reproduce your issue with your details.
I leave this issue closed !

**Comment by alfonsolr09** [comment]
@florine2623 
ok, you post in forums that it is very important that we test the version and report bugs.  I report them but since you are not able to reproduce it you close the thread ...

Thats good....
 :'/
