### ISSUE TITLE
Add a JavaScript event when Terms and conditions are approved

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#19189]
#### Is your feature request related to a problem?

In checkout process in payment step, add a [Javascript Event](https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/) when customer approve Terms and conditions to help payment modules to know if they can process to payment or not.

For modules [PrestaShop Checkout](https://github.com/PrestaShopCorp/ps_checkout), [Stripe](https://github.com/202-ecommerce/stripe_official) and [others](https://addons.prestashop.com/en/481-payment).

[PrestaShop Checkout](https://github.com/PrestaShopCorp/ps_checkout) use [PayPal Javascript SDK](https://developer.paypal.com/docs/checkout/) to manage Payment Button on checkout page and we use a callback to enable/disable it.
Currently we have to create your own event to check if Terms and conditions are approved.

[Stripe](https://github.com/202-ecommerce/stripe_official) use [Stripe Javascript SDK](https://stripe.com/docs/js) and [use their own event](https://github.com/PrestaShop/PrestaShop/issues/19161#issuecomment-629974094) to check if Terms and conditions are approved.

#### Describe the solution you'd like

Add a [Javascript Event](https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/) in [Core Js](https://github.com/PrestaShop/PrestaShop/blob/03032d6adb19836240047b5658988f1e64c823ee/themes/_core/js/checkout-payment.js#L84)
https://github.com/PrestaShop/PrestaShop/blob/03032d6adb19836240047b5658988f1e64c823ee/themes/_core/js/checkout-payment.js#L68

**Comment by matks** [comment]
Looks good 👍 
ping @NeOMakinG

**Comment by NeOMakinG** [comment]
Taking this when I've some times after the API implement of wishlist module

**Comment by matks** [comment]
@Matt75 This is now done for PS 1.7.8 😄 https://github.com/PrestaShop/PrestaShop/pull/19428

How critical is this topic for PS Checkout ?
If it's very critical 👀 there might be a window for backporting this into 1.7.7, you know who to talk to ...

**Comment by Matt75** [comment]
@matks Not critical, we manage it for older versions yet
