### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by JayWilliams74** [PrestaShop/PrestaShop#19187]
#### Describe the bug
I have been trying to upload my product file into Prestashop without any success. However the file that I am working on is not necessarily in the same order or same headings as the expected file even though I know you can map the columns!

So I tried using the column headings and copy-paste the relevant info into the columns and tried again and got the same result that it would not upload saying that it did not like the ID number.

On the 1st occasion, I left the ID number blank as I had when uploading Categories, Suppliers, Manufacturers etc. 
The 2nd time I inputted the ID numbers from 1 onwards, knowing I had no products in the existing product file.
Thirdly & Fourth - I have tried with only the "Sample Product" file data without ID and with ID's from 15 onwards as I have now had to resort to inputting products manually and got the same messages.

Screen Shots of all pages through the process are attached and have been produced today to ensure that it was not a one-off issue.
![Products • After Dark - Google Chrome 18_05_2020 15_26_22](https://user-images.githubusercontent.com/65467851/82225603-52c58880-991d-11ea-8585-a3b52d3806a8.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_27](https://user-images.githubusercontent.com/65467851/82225608-5527e280-991d-11ea-98c6-e9565c68a20d.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_38](https://user-images.githubusercontent.com/65467851/82225614-578a3c80-991d-11ea-84d8-1d98573f32f8.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_41](https://user-images.githubusercontent.com/65467851/82225623-59ec9680-991d-11ea-8c01-c9a5a0ee4cd6.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_44](https://user-images.githubusercontent.com/65467851/82225629-5ce78700-991d-11ea-9b8e-e1756a330db4.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_47](https://user-images.githubusercontent.com/65467851/82225634-5eb14a80-991d-11ea-84a6-de3091a913b6.png)
![Products • After Dark - Google Chrome 18_05_2020 15_26_50](https://user-images.githubusercontent.com/65467851/82225649-607b0e00-991d-11ea-8ae7-4ff97e0603e7.png)
![Products • After Dark - Google Chrome 18_05_2020 15_27_02](https://user-images.githubusercontent.com/65467851/82225655-62dd6800-991d-11ea-87c1-a672d48201c8.png)
![Products • After Dark - Google Chrome 18_05_2020 15_19_17](https://user-images.githubusercontent.com/65467851/82225664-64a72b80-991d-11ea-8f55-94b082166faf.png)
![Products • After Dark - Google Chrome 18_05_2020 15_21_25](https://user-images.githubusercontent.com/65467851/82225680-696bdf80-991d-11ea-9e46-13294acb6a88.png)
![Products • After Dark - Google Chrome 18_05_2020 15_21_51](https://user-images.githubusercontent.com/65467851/82225691-6c66d000-991d-11ea-8299-a11520179f4e.png)
![Products • After Dark - Google Chrome 18_05_2020 15_21_58](https://user-images.githubusercontent.com/65467851/82225700-6e309380-991d-11ea-9c79-2865ce422cad.png)
![Products • After Dark - Google Chrome 18_05_2020 15_23_44](https://user-images.githubusercontent.com/65467851/82225706-7092ed80-991d-11ea-916a-2ccd6c487603.png)

I have tried to attach the csv files but it will not allow so I have included in .txt & .pdf but it is exact as your own Sample file without the EAN's so that the #####+12 or change of cell type to Number with 0 decimal places does not cause any issues.

[test upload csv.txt](https://github.com/PrestaShop/PrestaShop/files/4644773/test.upload.csv.txt) 

[test upload csv.pdf](https://github.com/PrestaShop/PrestaShop/files/4644772/test.upload.csv.pdf)

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @JayWilliams74 ,
Sorry but we don't do any support on PS 1.6.
For that, please contact the support team here :
https://addons.prestashop.com/en/388-support

Also, please keep in mind that this is a public platform, you should not be showing your back-office url. Please change it.

Thanks for your understanding !

**Comment by marionf** [comment]
@florine2623 we can close this issue if there is nothing to do on our side
