### ISSUE TITLE
BO - Order detail - Voucher is displayed multiple time

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19184]
Be aware of the EPIC - BO - Display and update error on cart rule in the order #19594 to solve this issue

#### Describe the bug

When creating an order from the BO if a cart rule authorizing several uses per user is added and then we add products to this order from the BO a new line of vouchers is added for each product added

#### Expected behavior

For one voucher we should have only one display

#### Steps to Reproduce

1. Go to BO => Orders => Orders
2. Click on "Add new order"
3. Select a customer for the order
4. Add a product to the order
5. Click on "add new voucher"
6. In the voucher creation modal create a voucher with the following parameter : 
![capture d'écran_13](https://user-images.githubusercontent.com/40635814/82220401-d9c73080-991e-11ea-813f-10e8e8ed7455.png)
![capture d'écran_14](https://user-images.githubusercontent.com/40635814/82220413-dd5ab780-991e-11ea-9692-c8a729431ec6.png)
![capture d'écran_15](https://user-images.githubusercontent.com/40635814/82220417-e055a800-991e-11ea-9501-79f8795d8e89.png)
7. When the voucher is created add it to the order
8. Then click on "Create the order"
9. In the Order detail click on the "add a product" and add a product
10. See error
![capture d'écran_16](https://user-images.githubusercontent.com/40635814/82221025-b81a7900-991f-11ea-8855-31bc2d978edb.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by zuk3975** [comment]
followed the steps and I see different behavior.
![Screenshot from 2020-05-21 14-47-04](https://user-images.githubusercontent.com/31609858/82556279-176fc780-9b72-11ea-9116-3c1838d1d89b.png)

The discount is shown single and I don't even see the "discounts" tab in summary :sob:

**Comment by SD1982** [comment]
hi @zuk3975 yes it seems that you have find another behaviour but it seems you don't have totally the same parameters than mine ( i forgot to notify this one )

**Your screenshot**
![capture d'écran_23](https://user-images.githubusercontent.com/40635814/82804669-f87b7900-9e82-11ea-9d75-405b1c71ade8.png)

**My screenshot**
![capture d'écran_22](https://user-images.githubusercontent.com/40635814/82804692-04ffd180-9e83-11ea-94d7-0a8a10f012a0.png)

So we can consider than the issue you discovered is a new one but maybe they are related ?
Can you declare the new issue that you detected please ?

**Comment by zuk3975** [comment]
hmm it needs further investigation if you want to separate issues and see how its really behaving in one or another situation.
Anyway to sum up, the bug seems to be related with tax excluded/included config and it sometimes duplicates the cart rules and sometimes doesn't show "discounts" tab in the summary block.

**Comment by MatShir** [comment]
I create this issue to work on the @zuk3975  issue https://github.com/PrestaShop/PrestaShop/issues/19609. It doesn't seem to be the same bug.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19698
