### ISSUE TITLE
Product link on customer thread don't link properlly

### ISSUE THREAD

**Issue by runningz** [PrestaShop/PrestaShop#19192]
#### Describe the bug

When i click on product link on customer thread, the link gos to product list instead of the product details.

#### Expected behavior

Open product detail backoffice page

#### Steps to Reproduce

1- Add a customer question from order history page, for a purchased product.
2- In backoffice, open customer service and open the recent thread.
3- Click on product link

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @runningz ,

Thanks for the report !
I managed to reproduced this issue on both PS 1.7.6.5 and PS 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by runningz** [comment]
Fixed on https://github.com/PrestaShop/PrestaShop/pull/19191
