### ISSUE TITLE
Bulk Action "Assign to a new Zone" for Translation - Locations - States is not appearing if selected

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19190]
#### Describe the bug

If you go for your BO - Menu  Improve - Translation - Locations - States and select Bulk Action - "Assign to a new Zone", the site refreshes but is not displaying the desired Bulk Action afterwards.

This only applies to the States Menu.

Doing the same action for the Countries does work as expected.

Feature Request: Instead of choosing Bulk Action - Assing to a new Zone - and waiting for the refresh of the page, it would be great to directly display these options. Also it would be great to display such options at the start of the page, and not only at the end.

#### Expected behavior

Should work like with Countries.

#### Steps to Reproduce

- If you go for your BO - Menu  Improve - Translation - Locations - States and select Bulk Action - "Assign to a new Zone".
- See nothing happend

* PrestaShop version: 1.7.6.5 minimum
* PHP version: 7.1.3 to 7.2.3 and higher

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
Thanks for your report !
I did manage to reproduce this issue on both PS 1.7.6.5 and PS 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by pitkz** [comment]
Hello,
thanks for your reply.
This bug is NOT major as there is for example #19161 "Confirmation button on Checkout should be disabled if Terms and conditions are not approved" which play a way more signifcant role!

Please change this to minor, and the other to major.
Thanks

**Comment by marionf** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog.
This issue is a duplicate of #9971
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!
