### ISSUE TITLE
DB_PREFIX is ignored in docker container

### ISSUE THREAD

**Issue by jusurb** [PrestaShop/PrestaShop#19201]
**Describe the bug**
DB_PREFIX is completly ignored if set to `''` (empty string) or `null` or `~` and always fallsback to `ps_`

**To Reproduce**
1. Add  `DB_PREFIX: ''` to docker-compose.yaml
2. docker-compose up -d
3. Check prestashop DB, all tables should be without `ps_` prefix

**Screenshots**
<img width="274" alt="image" src="https://user-images.githubusercontent.com/171747/70378847-f3a32700-192d-11ea-9b08-5d432ef8640e.png">

**Additional information**
PrestaShop version: 1.7.7.2
PHP version: 7.2

**Comment by PierreRambaud** [comment]
Hi @Gamesh 
I transfer this issue to the main repository.
I manage to reproduce it without docker or anything else. If a have an empty prefix, it fallbacks to `ps_`
