### ISSUE TITLE
Faceted search does not work properly in a Multistore

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#19204]
#### Describe the bug

In the case of using a multistore and a multicurrency, the facet navigation incorrectly displays the price in the second multistore.

#### Expected behavior

In the first e-shop I use CZK (main - the exchange rate is 1) EUR (secondary - the exchange rate is calculated). https://www.strojni-pily.eu/4-pasove-pily-na-kov-rucni - everything works properly.
In a second e-shop, I only use EUR (the exchange rate is 1). However, the module converts the main currency EUR again according to some exchange rate. https://www.fenozashop.sk/4-pasove-pily-na-kov-rucne

More on video.

#### Steps to Reproduce

Steps to reproduce the behavior: https://www.loom.com/share/3d31a03f8dca40df9bb2d5716b84863c

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2
* Faceted search version: 3.5.0

**Comment by florine2623** [comment]
Hi @TaccCZ ,
I could not manage to reproduce your issue in PS 1.7.6.5 and faceted_search 3.5.0:
first shop :
![Capture d’écran 2020-05-20 à 17 03 35](https://user-images.githubusercontent.com/16019289/82462678-2bf18880-9abc-11ea-9273-b23a79de7a77.png)

second shop :
![Capture d’écran 2020-05-20 à 17 04 03](https://user-images.githubusercontent.com/16019289/82462691-30b63c80-9abc-11ea-92ad-ea5999367de3.png)

In my case, I checked my 2 shops : 
![Capture d’écran 2020-05-20 à 17 07 16](https://user-images.githubusercontent.com/16019289/82462879-6a874300-9abc-11ea-83a1-3efdbcfd1b63.png)

Can you check on your side ? Thanks!

**Comment by TaccCZ** [comment]
Thanks for the reply, but I may have misidentified the issue. there are two currencies on the first e-shop. Everything is alright.
![image](https://user-images.githubusercontent.com/37780517/82470613-dcb05580-9ac5-11ea-8866-a5eda26eb262.png)

There is one currency in the second e-shop and it is bad in the slider. It looks like from the first e-shop where € is converted back to € in the second e-shop.

![image](https://user-images.githubusercontent.com/37780517/82470596-d91cce80-9ac5-11ea-9392-c5932a014e95.png)



![image](https://user-images.githubusercontent.com/37780517/82470628-e043dc80-9ac5-11ea-85b7-3742c1aed2e8.png)

![image](https://user-images.githubusercontent.com/37780517/82470637-e33ecd00-9ac5-11ea-96dc-7448b02759fe.png)

**Comment by florine2623** [comment]
Please take a look at your conversion_rate in ps_currency. They should not be the same.
For example in my case, I have :
![Capture d’écran 2020-05-22 à 14 59 47](https://user-images.githubusercontent.com/16019289/82670451-71898f00-9c3d-11ea-8a2d-ad92926de073.png)

You can go to International > Localization > Currencies > Edit your exchange rate manually 
![Capture d’écran 2020-05-22 à 15 01 33](https://user-images.githubusercontent.com/16019289/82670388-5454c080-9c3d-11ea-9aab-c91d8032f587.png)

Or click on :
![Capture d’écran 2020-05-22 à 15 01 00](https://user-images.githubusercontent.com/16019289/82670310-312a1100-9c3d-11ea-96d4-128a46deee34.png)

**Comment by TaccCZ** [comment]
Thank you for answer.
I tried to adjust the currency conversion for the base table "ps_currency" which is now correct:
![image](https://user-images.githubusercontent.com/37780517/82725373-cfb97f00-9cdc-11ea-83c8-d4ebe2383fc3.png)


But for the 1st multistore I use two currencies (CZK + EUR) and for the 2nd multistore I only want EUR where I have exchange rate 1, because CZK in the 2nd multistore cannot be. EUR only. And in 2 multistore I enter prices manually without conversion. This is clearly seen in the "ps_currency_shop" table in the database:
![image](https://user-images.githubusercontent.com/37780517/82725385-e9f35d00-9cdc-11ea-8bf5-9c9877b57ee8.png)


Once again, I inform you that in the 2nd multistore EUR I have prices adjusted (fixed) without conversion. are other than EUR in the 1st multistore ...

**Comment by florine2623** [comment]
@TaccCZ ,
Even after changing your currency rate you still face the same issue ?

**Comment by TaccCZ** [comment]
Dear @florine2623 , 
yes, if i change currency to "normal" currency rate, for all tables: ps_currency + ps_currency_shop, here is the same issue in second shop. So I turned off price filter... because it lists meaningless amounts and it just confuses customers.

**Comment by florine2623** [comment]
With all the info, I still can't reproduce your issue.
I advise you to contact the support : https://addons.prestashop.com/en/388-support
Or contact an PrestaShop Partner agency : https://www.prestashop.com/en/experts
Thanks!
