### ISSUE TITLE
Products redirection only working on Mobile device

### ISSUE THREAD

**Issue by Heine76** [PrestaShop/PrestaShop#19207]
Hie,
 I'm here to be helped because i met an issue with ps_category products.
All items in the box are not clickable on PC but the redirection still working on a mobile device.

I don't know why and i would a solution for this. 
May someone helps me ? 

1. Going randomly on a product, for example " https://thevapingbar.fr/resistances/473-670-resistances-qf-skrr.html#/97-resistance-qf_meshed_020_ohm"
2. Click on a product in same category products (5 AUTRES PRODUITS DANS LA MÊME CATÉGORIE)
![image](https://user-images.githubusercontent.com/28921808/82325412-80710700-99db-11ea-849e-9770015506b0.png)

3. The redirection didn't work on computer but works on a mobile device

* PrestaShop version: 1.7.3.2
* PHP version: 7.1
Ps:  Hope you're understanding me, i'm french and have some problems in english too. 
Sorry for that ;)

**Comment by florine2623** [comment]
Hi @Heine76 ,
This is a theme related issue. It has nothing to do with PrestaShop core.
I would advise you to contact the developer of the theme directly. If you bought the theme through Addons, you can contact the dev of the theme through your Addons account.
I will close this issue, thanks for understanding !
