### ISSUE TITLE
Upgrade to 1.7.6.5

### ISSUE THREAD

**Issue by JayWilliams74** [PrestaShop/PrestaShop#19209]
#### Describe the bug

I have just upgraded from 1.6 to v 1.7.6.5 and when I go into my admin page I get an error 500 message. (See screenshot Below)

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

![An Error Occurred_ Internal Server Error - Google Chrome 19_05_2020 14_34_48](https://user-images.githubusercontent.com/65467851/82333294-7270b580-99de-11ea-9ee1-317eefa05af6.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @JayWilliams74 ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- PrestaShop version (source)
- debug mode report
- screenshots
- if you are using 1-click upgrade or another tool

Thanks!

**Comment by JayWilliams74** [comment]
Hi 
I was going from 1.6.1.24 to 1.7.6.5 using 1-click upgrade
I cannot gain access to anything within Prestashop Admin to run any Debug Mode

I chose the Active version within 1 click options

**Comment by florine2623** [comment]
Go to you file config/defines.inc.php :
Change this :
`define('_PS_MODE_DEV_', false);`
To :
`define('_PS_MODE_DEV_', true);`

**Comment by JayWilliams74** [comment]
Thank you...

![https___euphoric-nights uk_store_store_admin_ - Google Chrome 20_05_2020 11_14_29](https://user-images.githubusercontent.com/65467851/82434791-4cedb580-9a8b-11ea-9061-d2d8d1eea9af.png)
![https___euphoric-nights uk_store_store_admin_ - Google Chrome 20_05_2020 11_14_01](https://user-images.githubusercontent.com/65467851/82434801-4f500f80-9a8b-11ea-95a8-f4092344cb10.png)

**Comment by florine2623** [comment]
You have a missing table in your shop : YOUR_PREFIX_currency_lang.
If one missing table occurred, it is possible that there are multiple issue your upgrade.
Can you check you upgrade log file ?
your_admin/autoupgrade/tmp/log.txt
If you have fatal error, please send the file.

**Comment by JayWilliams74** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4658126/log.txt)

As requested

**Comment by florine2623** [comment]
Can you check your PHP version ? Should be 7.2 max.
Could you also delete all cache ?

**Comment by JayWilliams74** [comment]
HI Florine
Yes php is 7.2

**Comment by JayWilliams74** [comment]
Google Crome cashe cleared

**Comment by florine2623** [comment]
Cache from PrestaShop not from Google !
Can you delete folders `/dev` and `/prod` from `/var/cache` ?

If that does nothing, you will need to create manually that table running that query on PHPMyAdmin:
```
/* Localized currency information */
CREATE TABLE `PREFIX_currency_lang` (
  `id_currency` int(10) unsigned NOT NULL,
  `id_lang` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `symbol` varchar(255) NOT NULL,
  PRIMARY KEY (`id_currency`,`id_lang`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8 COLLATION;
```

Thanks!

**Comment by JayWilliams74** [comment]
I am not an experienced programmer so not truely sure if i am doing this correctly.
![phpadmin page](https://user-images.githubusercontent.com/65467851/82483060-abd51e00-9acf-11ea-9b27-538bc8fa2e58.jpg)

**Comment by JayWilliams74** [comment]
??

**Comment by JayWilliams74** [comment]
I have saved as it was and I got the following debug info.
![The slug ROLE_MOD_TAB__READ is invalid (500 Internal Server Error) - Google Chrome 21_05_2020 15_46_22](https://user-images.githubusercontent.com/65467851/82571204-85b88800-9b7a-11ea-9d7b-9a66c964a4fc.png)

**Comment by florine2623** [comment]
When I said to run the query :
```
/* Localized currency information */
CREATE TABLE `PREFIX_currency_lang` (
  `id_currency` int(10) unsigned NOT NULL,
  `id_lang` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `symbol` varchar(255) NOT NULL,
  PRIMARY KEY (`id_currency`,`id_lang`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8 COLLATION;
```
You should have run it directly on the SQL tab of PHPMyAdmin, not create it manually.

I advise you to do a rollback. If correcting an error generates another one, you might have to correct a bunch of errors before you get your shop working properly.

You can let our team do the migration, please contact the support team of PrestaShop [here](https://addons.prestashop.com/en/388-support).
Thank you for your understanding.

**Comment by JayWilliams74** [comment]
This is NO GOOD to me!!!
I am not a Software Programmer!!
I this that as a SOFTWARE SUPPORT you should get an understanding of level of knowledge! I purposely Left a response for over 24hrs, then followed it by a Double ? to see if I was going to get a response to my request to confirm if I was doing the right thing. Yet had no response so I had to go with what I thought!

I was using PRESTASHOP's OWN Upgrade SOFTWARE to migrate me from 1.6 to 1.7 and IT FAILED causing my SITE to FAIL!!!  Not my Problem! If I had used any other method then It would be my issue!!

If files were deleted during YOUR SOFTWARE UPGRADE Process then YOU FIX IT!!!!!!!!!

The whole reason WHY i was upgrading to 1.7 was due to the fact I had an issue with the csv import not working on 1.6 which I reported on here and YOU @florine2623 told me was not supported on HERE. 

I was ending up having to build each product of over 1000 products individually, so I thought the Product Import would actually work on 1.7 as IT IS SUPPOSED TO as part of the CORE SOFTWARE (and not as an ADD-ON!! chargeable or free). If, as a software company @Prestashop offer a solution as part of the CORE SOFTWARE then anyone would EXPECT it to work as designed.

Likewise, If you are running an upgrade from one version to another then IT should not FAIL to complete the Upgrade Using the Companies OWN Upgrade Program. IF options are given as to what version of the upgrade is installed then (Unless it was a COMPLETE BETA SYSTEM with UNTESTED and UNVERIFIED changes to CORE programming) I, nor would any other USER at any LEVEL!!! would expect it to fail - shutdown a site and have anyone have to build missing tables and effectively write script that could have a detrimental effect on the Core Software workings. That is what a Software Developer or Software Support is there to do!!!

I suggest that Someone from PrestaShop makes contact with me directly through email- I will give them access to my Admin Site etc - After FULL Verification!!! And you resolve whatever issues have been caused and get MY SITE up and running within the next 24hrs so that I can continue where I left off and none of my existing work is lost.

**Comment by matks** [comment]
@JayWilliams74 You are mistaken. On this github repository there is no software support. This is an open source project.

I think the reason why you seem angry is that you are mistaken: again this github repository is not free a software support area, but a bug tracker.

You can find help
- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support
