### ISSUE TITLE
webservice create order set total_paid_real with shipping fees

### ISSUE THREAD

**Issue by pibrom** [PrestaShop/PrestaShop#19219]
#### Describe the bug

When I try to create an order with Prestashop webservice, with products ans shipping cost, I 've got an issue on total_paid_real value, that is required, but unkown without method of calculation of shipping costs.
It result the création of my order with a status 'Payment error', because there is a difference between what is stored in the order_payment table and in the orders table, field total_paid and total_paid_real

#### Expected behavior

The total_paid_real field must be calculated as the field total_paid, with addition of total_product and total_shipping cost.

* PrestaShop version: 1.7
* PHP version: 7.2

**Comment by LouiseBonnard** [comment]
Dear @pibrom, thank you for this issue. Can you please indicate if this is a bug or an improvement of the web service? And on what PrestaShop version you are experiencing this issue? Many thanks in advance!

**Comment by pibrom** [comment]
I think this is a bug.
I managed to work around the problem by adding a line in PaymentModule Override 
$amount_paid = $cart_total_paid field control;

**Comment by LouiseBonnard** [comment]
Hi @pibrom, thank you for this information, we still need to reproduce your issue on our end to qualify it but feel free to create a pull request to share your fix!

**Comment by pibrom** [comment]
It's not a fix, it's a tinkering!
I couldn't find the code that was used to validate an order placed via the webservice.

**Comment by hibatallahAouadni** [comment]
Hello @pibrom 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by Alessio6976** [comment]
Hi,

have you solved this problem? I still have this issue. The total_paid_real creates me many issue. Also if I force this value in the XML, the webservice takes the amount of the order, DON'T consider the decimals, and write the number in the DB. But the result is having a "Payment error" couse the amounts are different. I solved (for now) removing the decimals numbers and setting both (total_paid and total_paid_real) without decimals (but it's not pretty...)

How can I solve this issue? I'm using 1.7.8

thank you
Ale

**Comment by pibrom** [comment]
Hello. I don't remember how I solved this issue as my code worked well so far.
I will have to transpose my work on a New Prstashop 8 instance, i'll check on this new version if the bug still exists or not.

**Comment by Alessio6976** [comment]
Thank you pibrom!
I think it is a little bug on how it manage the decimals, but I don't know where can I update the webservice...where to find "api" folder...
