### ISSUE TITLE
Add/modify data in one of the Blocks in the Admin Customer View 

### ISSUE THREAD

**Issue by LouisAUTHIE** [PrestaShop/PrestaShop#19217]
#### Describe the bug

I would like to add some data generated by my module in the first Block on the Backoffice/Admin Customer View Page => The personal_information block. But the only hook I found is the displayAdminCustomers one. But its position is not the one I want to use do display my data. What can I do if I don't just want to override the twig of this block in my module by putting an Ajax Request to get my data and insert it in the block ? Is there any way to override something or a hook to use to manage to succeed in my request ?

#### Expected behavior

What I expect is a method to hook my module or to override something to be able to add my content to the controller and pass it to the view. And I will override the view then to show my data.

#### Steps to Reproduce

Nothing

**Screenshots**

<img width="554" alt="image" src="https://user-images.githubusercontent.com/65625876/82373621-247ba200-9a1e-11ea-8c26-fc5f6c26f22f.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @WebHelpers64 ,
I will transfer your question to our dev team, play stay tuned.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

Could you take a look at @WebHelpers64 's question ?

Thanks a lot.

**Comment by matks** [comment]
Hi @WebHelpers64,
- if you want to modify how the data is displayed you need to override the Twig template
- if you want to modify the data being injected in the view you need to override/decorate the controller (see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/override-decorate-controller/)

An alternative to override/decorate the controller would be to listen to the `kernel.view` Symfony event (see [doc](https://symfony.com/doc/current/reference/events.html#kernel-view)) to alter the Response being returned by Symfony but that would seem overkill IMO

**Comment by PierreRambaud** [comment]
Hi @WebHelpers64 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!
