### ISSUE TITLE
Cannot remove cart rules on cart if there is no code generated

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19215]
#### Describe the bug

Remove a cart rules from the cart summary is not enable if the cart rule have any code generated.

#### Expected behavior

If we consider the cart rules cannot be removed, the remove button should be hidden.
If we consider the cart rules can be removed, it shoud be work...

We don't know exactly what's expected?

#### Steps to Reproduce

1. Create a new cart rule. Set 10% for a specific customer.
![image](https://user-images.githubusercontent.com/52157233/82352407-33eaf300-99fe-11ea-816d-a4ee571a756b.png)
2. In the front office (classic theme or an other). Add something to cart.
3. On you cart summary, try to remove the cart rules
![image](https://user-images.githubusercontent.com/52157233/82352630-89bf9b00-99fe-11ea-98fa-28c2828f7796.png)
4. We have Ajax requests send but the voucher is not removed
![image](https://user-images.githubusercontent.com/52157233/82352881-eae76e80-99fe-11ea-9cfe-ece4086b2ab0.png)

#### Additional information

* PrestaShop version: 1.7.6.5 and 1.7.7.0
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @clotaire202 ,

On PS 1.7.7.0 this feature has changed.
When a cart rule is set for a specific customer, he won't be able to remove it :
![Capture d’écran 2020-05-20 à 12 24 25](https://user-images.githubusercontent.com/16019289/82435663-e5d4fe80-9a94-11ea-801a-6dbaa8d6d3b8.png)
If a cart rule has a generated code, the removal is possible :
![Capture d’écran 2020-05-20 à 12 25 31](https://user-images.githubusercontent.com/16019289/82435725-043afa00-9a95-11ea-8af9-c1b664af32fc.png)

Thanks!

**Comment by clotairer** [comment]
It's clear, themes need hide the "trash" button if promo code has no code.

Thank you for your precision.

I close !
