### ISSUE TITLE
Problem with URL Friendly and product's images url

### ISSUE THREAD

**Issue by cesar-cardinale** [PrestaShop/PrestaShop#19218]
#### Describe the bug

I used a module named Migration Pro to migrate all products from a Magento 1.9 in my Prestashop 1.7.6.4. Everything work fine, but I think there is a bug here, in the url of the images of the product, so everywhere in Front-Office (categories, product page ..), the url generated is 'http://website.com/idproduct-home_default/.jpg', the name of the product is missing juste before '.jpg'. When I disable URL Friendly everything come back and images url are good and images are shown.
I already have delete .htaccess, regenerate it, regenerate the thumbnails ...

#### Expected behavior

I need some explain of how can I fix this problem please !

**Screenshots**

[https://imgur.com/a/o9YKmNW.png](https://imgur.com/a/o9YKmNW.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1.33

**Comment by LouiseBonnard** [comment]
Hello @cesar-cardinale, thanks for your issue, have you tried to contact the Migration Pro support? It seems to be related to the module rather than to the PrestaShop core... @PrestaShop/prestashop-core-developers, can you confirm?

By the way, I fixed the link to your screenshot because it was wrong, it works fine now. :-)

**Comment by cesar-cardinale** [comment]
I just send them a ticket on the support, waiting for their answer.
I don't think it's a problem related to the module but more related on the wrong generation of the image and now I can't reset that link rewrite on the images url.

**Comment by cesar-cardinale** [comment]
Okay, I wrote a script who set 
`$product->link_rewrite[$lang] = Tools::link_rewrite($product->name[$lang])`
 and now everything work.
