### ISSUE TITLE
Create product an forget the feature with a customized value generate troubles

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19212]
#### Describe the bug

If you create a new product, and you forget to select a feature but add a value, the product is created but the feature cannot be edited or deleted

#### Expected behavior

An error should be throw if a feature is not selected.

#### Steps to Reproduce

1. Go to Catalog > Products
2. Click on "New products"
3. Fill in a title
4. Click on "Add a feature"
5. Don't select a "Feature" but fill in some data on "OR Customized value"
6. Save
7. Delete the feature with the trash icon.
8. Save the product and reload the page : the feature is back !

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/52157233/82348476-3b5bcd80-99f9-11ea-9689-2ff7b8cc2d82.png)

#### Additional information

* PrestaShop version: 1.7.6.5 & 1.7.7.0
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @clotaire202 ,

I could not reproduce the issue on neither PS 1.7.6.5 nor PS 1.7.7.0.
Here's the screen records :
On PS 1.7.6.5
https://drive.google.com/file/d/1bh_XwyJ9OZfJYB1XDWEQlXJ2V-q_FqZf/view
On PS 1.7.7.0
https://drive.google.com/file/d/1VbI21A41pq5g-Df0VTW3kbVb8-j8iIql/view

What version of PHP are you using ?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi there, I manage to reproduce this issue on PS 1.7.7: https://drive.google.com/file/d/1pC-bGS-RQksX6Qpn7SM_D7iFBoXgXg1_/view

**Comment by MatShir** [comment]
I put the issue to minor since the feature does not appears in FO, I will see with the migration team if it can be resolved on the migration of the product page. 
thanks @clotaire202

**Comment by khouloudbelguith** [comment]
Hi!

Sorry for the late response.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16306.
To be informed when it's fixed, please subscribe to the issue mentioned above.
If you have the solution, you could create a PR, and I'll link it to the original issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #16306
