### ISSUE TITLE
"Cannot read property 'replace' of undefined" when deleting a category

### ISSUE THREAD

**Issue by Llorx** [PrestaShop/PrestaShop#19220]
Easy:
- Install PrestaShop 1.7.6.5. All default (I've selected spanish).
- Go to categories and try to delete one.
- Error:
![image](https://user-images.githubusercontent.com/702490/82389811-5bad7b80-9a3d-11ea-9a83-7382795c4c05.png)
![image](https://user-images.githubusercontent.com/702490/82389818-62d48980-9a3d-11ea-8257-8e2aac1b1866.png)

Even the doprdowns are not working: 
![image](https://femto.pw/6gti.gif)

The bug is that there's no space between "select" and "id":
![image](https://user-images.githubusercontent.com/702490/82390099-13428d80-9a3e-11ea-84b8-6dd42e5a196a.png)

**Comment by LouiseBonnard** [comment]
Dear @Llorx, thanks for this issue! Does this bug concern the category or the employee page? All dropdown selectors are broken?

**Comment by florine2623** [comment]
Hi @Llorx ,
Can you make sure you are using PHP 7.2 max ?
Thanks!

**Comment by Llorx** [comment]
Yes, all dropdowns are broken, no matter the menu you enter. Regarding PHP version, I was using PHP 7.3.18 as is a supported version (at least that's what the installer said).

**Comment by florine2623** [comment]
Please check this : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

PHP 7.3 is only available for 1.7.7.0. For now this version is still a beta version. So do not use it is production.

I will now close this issue.

**Comment by dr7tbien** [comment]
He conseguido soluciuones este problema bajando la versión de PHP. Se ha solucionado:

1. Poder escribir en cietos campos del back office. Antes no se podía
2. Que los deplegables funcionen adecuadamente. Antes no funcionaban
3. Que se puedan suprimir categorías. Antes no se podía
