### ISSUE TITLE
FrontController names in modules hook-exceptions are wrong spelled with a dash

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#19226]
#### Describe the bug

Go to back-office, chose an arbitrary module (ps_emailsubscription for example), and try to make this module disappear from the displayFooterBefore hook in some Core FrontController which have a $php_self thant contain a dash (exeple : 'my-account').

--

#### Expected behavior

you should go to your front-office (after clearing the cache), navigate to the desired Core FrontController (http://something.com/mon-compte in my case) : The module (ps_emailsubscription) should not show up in this page.

#### Steps to Reproduce

When you go to chose an exception from the Core FrontControllers list, you have to notice that this list is generated based on Core FrontController files names :examples :- controllers/front/MyAccountController.php ==> myaccount- controllers/front/ChangeCurrencyController.php ==> changecurrencySo if you select myaccount for example, it will be stored in the DB (${prefix}_hook_module_exceptions table) as it is (myaccount). Then, in the rendering phase (precisely in Hook::excec()), the algorithm was comparing this DB value (myaccount) to current context controller php_self (my-account)(myaccount ?= my-account)==> BUG !

**Screenshots**

https://user-images.githubusercontent.com/39015823/82111516-3c190900-9746-11ea-8eee-8be7b6b7ef40.png

#### Additional information

* PrestaShop version: develop

The user opened a PR there : https://github.com/PrestaShop/PrestaShop/pull/19163

**Comment by dali-rajab** [comment]
The PR is updated (and moved) here https://github.com/PrestaShop/PrestaShop/pull/21168
