### ISSUE TITLE
Cant update-edit a product if use negative value on product combination price impact after first save

### ISSUE THREAD

**Issue by Knut33** [PrestaShop/PrestaShop#19222]
On version 1.7.6.5
When adding a product combination that has a negative price impact you can save it, But on edit you get error, "Cant Save" on save.
After deleting the combination line with negative price impact you can edit and save the product again.

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @Knut33 ,
PS 1.7.6.5 in not compatible with PHP 7.3, please change it to 7.2 and try again.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by Knut33** [comment]
Hi
I changed to PHP-versjon: 7.2.31-1, Still same problem with using  negative value on product combination,  price impact. ERROR "You cant update settings"

**Comment by Knut33** [comment]
No The problem is still there using php7.2.
To trigger the problem, you need to add negative number on product option price impact and save then do some changes and save again, and do changes and save.
first changes not trigger the error.

**Comment by florine2623** [comment]
I can't reproduce your issue.
Please check my screen record :
https://drive.google.com/file/d/1Q7TtN-PHeQ87mf8qkxjXtrYg6BDBFCey/view
I tried editing and saving the changes multiple times.

**Comment by Knut33** [comment]
Hi After try to replicate the problem now after some while, i cant reproduce the error, so maybe it was wrong php (php7.3) that cause it, So your solution was correct.
Tank you. then its solved
