### ISSUE TITLE
Handling of Composer/Autoload for modules.

### ISSUE THREAD

**Issue by Kioob** [PrestaShop/PrestaShop#19224]
#### Describe the bug

Without proper classmap-cache initialization, for each module, the autoload code is dramatically slow.

Actually, on our deploiement with 69 modules installed, Composer\Autoload\ClassLoader::findFileWithExtension() is called 8000 per PHP hit ; which is useless and can be terribly slow on some setup.

I had to execute  "composer dump-autoload --optimize --no-dev --classmap-authoritative" for each module to fix the problem.

#### Expected behavior

Your documentation should mention the problem :
    https://devdocs.prestashop.com/1.7/scale/optimizations/#3-composer-autoloading-optimizations

And you probably should provide a small shell script to rebuild the composer cache from each module.

#### Steps to Reproduce

1. Install Prestashop with some modules using composer.
2. Build a "non-authoritative" cache for each.
3. Edit Composer\Autoload\ClassLoader::findFileWithExtension() to add syslog(LOG_WARNING, "foo")
4. Cry

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.31

To fix that, I used : 
```bash
CURRENT=`pwd` 
for FILE in `find . -name 'composer.json'` ; do
    DIR=$CURRENT/`dirname $FILE`
    echo [$DIR]
    cd $DIR || continue
    composer dump-autoload --optimize --no-dev --classmap-authoritative
done
cd $CURRENT
```

**Comment by matks** [comment]
Thanks for opening the issue, let's see what we can do about that 👍

**Comment by matks** [comment]
ping @Quetzacoalt91 you might be interested

**Comment by Quetzacoalt91** [comment]
We chose not to force the classmap authoritative parameter on every module because the composer documentations says there might be side effects.

From https://getcomposer.org/doc/articles/autoloader-optimization.md:
> This option makes the autoloader always return very quickly. On the flipside it also means that in case a class is generated at runtime for some reason, it will not be allowed to be autoloaded. If your project or any of your dependencies does that then you might experience "class not found" issues in production. Enable this with care.

But on previous tests on PS Ready, we managed to gain ~25% of execution time if we forced this mode on all modules, even the ones we do not own.

I would consider recommending this mode for everyone, and eventually fallback on the `optimized` mode if something does not work properly.

**Comment by eternoendless** [comment]
Hey @Kioob, thanks for the head up. I've requested an update to our release manager so that the autoloader optimization is performed on the project's modules.

Regarding the documentation, I'm not sure I understand what you expect it to say. Why not consider submitting a pull request?

**Comment by matks** [comment]
> Hey @Kioob, thanks for the head up. I've requested an update to our release manager so that the autoloader optimization is performed on the project's modules.

I can confirm that this optimization is now being done on PrestaShop modules being distributed through Addons API (when they have a Composer setup).

As for 3rd-party modules, it is up to the vendor.

**Comment by matks** [comment]
I think we did all we could on this topic
