### ISSUE TITLE
quantity field in product page show 0 when minimal quantity =0 

### ISSUE THREAD

**Issue by taoufiqaitali** [PrestaShop/PrestaShop#19233]
#### Describe the bug

when minimal_quantity =0 it show 0 in quantity field on product page

#### Expected behavior

show 1 when minimal quantity =0

**Screenshots**

![image](https://user-images.githubusercontent.com/22837086/81834499-86c13800-9530-11ea-9bf1-ca11e9d372bf.png)
![image](https://user-images.githubusercontent.com/22837086/81834572-a193ac80-9530-11ea-93f4-8f0d58edcb4b.png)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/19116)

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7

**Comment by florine2623** [comment]
Hi @taoufiqaitali ,
Having the minimal quantity set to 0 means that a customer can buy 0 product. That's why 0 is shown in the front.
If you don't want 0 to be shown you can set it at 1 or any other quantity that matches your need.
Thanks.

**Comment by taoufiqaitali** [comment]
Hi @florine2623 
but customer cant by the product we can just uncheck "available for order option"
if we use the minimal quantity as you said, it have no sense to buy 0 quantity
