### ISSUE TITLE
Order message problem

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#19234]
On prestashop 1.7.6.5 when I receive a message in the order, for example in French, the result is the following:

Bonjour
J&#039;ai suivi vos instructions
C&#039;est juste une demande de devis pour le moment.
Je suis revendeur et doit faire une cotation &agrave; mon client.
Je passerai commande quand lui-m&ecirc;me m&#039;aura command&eacute;.
Faites svp un bon prix revendeur et vue la quantit&eacute;
cordialement

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

**Comment by florine2623** [comment]
Hi @Betafer ,
What exactly is your issue here ?
Thanks!

**Comment by Betafer** [comment]
Hello:

here you can see the problem: 

<img width="471" alt="Schermata 2020-05-20 alle 16 26 21" src="https://user-images.githubusercontent.com/5024055/82458175-a7e8d200-9ab6-11ea-9b41-535d61338197.png">

**Comment by alfonsolr09** [comment]
the same happens with the accents in the messages that clients send through the web contact

**Comment by Betafer** [comment]
Ok, it's a bug

**Comment by florine2623** [comment]
Hi @Betafer ,
Your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/18890
The solution has been given.
I will close this issue!
