### ISSUE TITLE
Prestashop dashboard stats

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#19232]
Hi there, 

Is there a way to place Google Analytics or Facebook pixel instead of Prestashop dashboard stats?

I have been struggling with no near accurate stats from PS. Not sure what they are counting to be honest.

Google Analytics / Facebook pixel show me good stats.

Would like to implement to the back office dashboard.

Tried to fix Prestashop with some guides but no luck. While Google Analytics / Facebook pixel show in example 10 peoples online, Presta in same time shows 300+

Best Wishes

**Comment by florine2623** [comment]
Hi @GTriber ,
Indeed if you need very accurate data, you can use external modules.
It is not possible natively to replace your Dashboard page entirely by Google Analytics or Facebook Pixel. The only way to get the info needed would be to get customized code.
For that you can contact one of PrestaShop's partner agencies : https://www.prestashop.com/en/partners
Thanks!
