### ISSUE TITLE
Problem during the first installation of PrestaShop 1.7.6.5

### ISSUE THREAD

**Issue by sterzuccio** [PrestaShop/PrestaShop#19237]
During the first installation of PrestaShop I get this error:

<img width="649" alt="Schermata 2020-05-20 alle 15 51 07" src="https://user-images.githubusercontent.com/14995053/82454171-baacd800-9ab1-11ea-9310-41715430cfb2.png">

During the first installation I had a first problem with pelago module and I downgraded from v2.2.0 to v2.1.1, after doing the downgrade I received this problem.

PrestaShop version: 1.7.6.5
PHP version: 7.3.15

**Comment by florine2623** [comment]
Hi @sterzuccio ,
You should use PHP 7.2 for PrestaShop 1.7.6.5 :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Please check and let me know.

**Comment by sterzuccio** [comment]
@florine2623 I changed the compose.lock file using the version 1.7.6.5 downloaded from the site and the installation was successful. However, I will now try to do a new installation using your advice and let you know.

**Comment by florine2623** [comment]
Ok if it works, I close this ticket !
