### ISSUE TITLE
Notify when a module registers to a hook but implements no hook listener

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#19230]
Following #15702

#### Is your feature request related to a problem?

When a module registers to a hook using `$this->registerHook()`, no check is performed to make sure that said module implements a hook method to listen to those hooks. This could happen for example when there's a typing mistake in the hook name.

#### Describe the solution you'd like

In debug mode, throw an exception like this when that happens:

> Hook with the name %hookName% has been registered by %moduleClassName%, but the corresponding method %functionName% has not been defined in the Module class.

**Comment by LouiseBonnard** [comment]
To be checked with @eternoendless & @PierreRambaud before.
