### ISSUE TITLE
product image error when sharing

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#19247]
#### Describe the bug

I have completely modified a product. Now when I copy the link and paste it, for example, on WhatsApp, the image does not load as it does on other products.

I have duplicated this product and the same is still happening with the duplicate.

with other products it shows well and even if I modify them completely, the new image shows.

but with that product of the video specifically it doesn't work well

can you give me any idea what may be happening?

#### Expected behavior

photo should be displayed on all products

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.31

Thanks

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
Could you regenerate your images ?
Design > Image Settings > Regenerate product thumbnails

Please check and let me know.

**Comment by alfonsolr09** [comment]
Email settings?
Does it have something to do with the images in the email?

**Comment by florine2623** [comment]
I meant "Design > Image Settings > Regenerate product thumbnails". 
I'm sorry.

**Comment by alfonsolr09** [comment]
I did it yesterday and it's still bad

**Comment by alfonsolr09** [comment]
I'm going to try again, yesterday I regenerated all of them.  Which one should I select to regenerate only the specific models?

**Comment by florine2623** [comment]
You can select all Product images to regenerate.
Clear cache from Advances Parameters > Performance and try again

Does it only happen with that product (that has been duplicated) and the product "model" ?
What are the differences between these 2 products and the others from your shop ?

**Comment by alfonsolr09** [comment]
with the duplicate product of the wrong product it was solved (automatically).  
now the error continues with the first wrong product.  the difference is none, I have reviewed the database and everything is exactly the same as the others except name, description, price and little else

**Comment by florine2623** [comment]
Could you try to delete the image and reupload it ?

**Comment by alfonsolr09** [comment]
I did it yesterday and it's still the same

**Comment by florine2623** [comment]
Can you send me an export of that product only via sql. I will try to upload it in my store to see what is going on.

**Comment by alfonsolr09** [comment]
How can I export only that product?

**Comment by florine2623** [comment]
Go to your products page
Export your products
Open the export and only leave the line regarding the product
Example :
[product_2020-05-25_120905.xlsx](https://github.com/PrestaShop/PrestaShop/files/4676681/product_2020-05-25_120905.xlsx)
With the file I will be able to import it to my test shop.

**Comment by alfonsolr09** [comment]
This???

**Comment by alfonsolr09** [comment]
This 
https://drive.google.com/file/d/1F2h7jyzAT8ntn43xONOzz0wXD7mkzjQz/view?usp=drivesdk

**Comment by alfonsolr09** [comment]
I think its the same

https://drive.google.com/file/d/1F5zvE12NpyIAP2OYnzASQAqWxn9-0uwa/view?usp=drivesdk

**Comment by alfonsolr09** [comment]
Not all product settings appear in this file, are you sure it will work for you?

**Comment by florine2623** [comment]
Yes it will work, in the import feature, you can choose to ignore some column if they are not needed.
I can't reproduce your issue again :/
When you recreate entirely this product from scratch, do you have this issue ?

**Comment by alfonsolr09** [comment]
how to initialize the product from scratch?

**Comment by florine2623** [comment]
I meant recreate the same product, without duplicating it.
You can go directly to your Product page in the BO and add a new product with the same info manually.

**Comment by alfonsolr09** [comment]
I already did it and the new product works perfectly

**Comment by florine2623** [comment]
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

**Comment by alfonsolr09** [comment]
Only appens with this product... Dont close the issue 
If you want i give you conection to my backoffice website
@florine2623

**Comment by alfonsolr09** [comment]
@florine2623

**Comment by florine2623** [comment]
You can buy a support plan if you want some customized help :
https://addons.prestashop.com/en/388-support

**Comment by jolelievre** [comment]
Hi @alfonsolr09 

Just a hint, not sure if it will help you but you can check in the source code at the meta:

```
<meta property="og:image" content="http://yourwebsite.com/2-large_default/hummingbird-printed-t-shirt.jpg">
```

which is used to display links. And check if the url is correct and accessible. Also you can try changing the cover of your product to see if it fixes your problem.

**Comment by alfonsolr09** [comment]
> Puede comprar un plan de soporte si desea ayuda personalizada:
> https://addons.prestashop.com/en/388-support

I think it is a bug, but since you are not able to reproduce it, you close the ticket

**Comment by alfonsolr09** [comment]
> Hola @ alfonsolr09
> 
> Solo una pista, no estoy seguro de si te ayudará, pero puedes verificar el código fuente en el meta:
> 
> ```
> <meta property="og:image" content="http://yourwebsite.com/2-large_default/hummingbird-printed-t-shirt.jpg">
> ```
> 
> que se usa para mostrar enlaces. Y verifique si la url es correcta y accesible. También puede intentar cambiar la cubierta de su producto para ver si soluciona su problema.

thanks, how should i check the source code for example in whatsapp?

**Comment by alfonsolr09** [comment]
in case someone else happens, I have deleted the product (it is deleted from the database)
then I copied the product id 446 and changed the id to 447 in the three tables of the database
the wrong product was id 447 (I deleted it from prestashop and copied it from id 446 in the database)
I comment it in case someone else happens
