### ISSUE TITLE
Remove Shudrum/ArrayFinder (not compatible 8.1) and use Symfony/PropertyAccess instead

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19243]
https://github.com/Shudrum/ArrayFinder is being used in PrestaShop classes Theme and PhpParameters.

However this dependency is maintained by a single person (so if he decides to abandon the project, it will go stale) and contain a single PHP class (it seems a bit overkill to have a Composer dependency with a single class in it). https://github.com/symfony/property-access seems to provide the same capabilities while fixing the 2 issues and is already bundled into PrestaShop as we use the Symfony framework

# To do list

1) https://github.com/PrestaShop/PrestaShop/pull/25611
2) https://github.com/PrestaShop/PrestaShop/pull/25919
3) https://github.com/PrestaShop/PrestaShop/pull/25937
4) https://github.com/PrestaShop/PrestaShop/pull/26923

**Comment by eternoendless** [comment]
Unfortunately removing this dependency would be a breaking change, so we can't do it until the next major (unless we're forced to for some reason).

**Comment by matks** [comment]
> Unfortunately removing this dependency would be a breaking change, so we can't do it until the next major (unless we're forced to for some reason).

## Possible workarounds
- remap classes autoload by using custom autoloader so another new class can do the job
- put file with same namespace and name inside the core but content is different

Only the file location would change.

## Possible reasons to justify the BC
- probably a waste of CPU as a single-file library is not worth it
- package is maintained by a single developer and does not seem to evolve so it could become abandoned (can be fixed by forking)
- if Symfony component provides the same feature, we currently have duplicated code so removing one of the occurrence gets a better, lighter and cleaner project

**Comment by matks** [comment]
I think this topic is not a must-have so I wont be able to make it reach merge point for 8.0.0 😭

**Comment by atomiix** [comment]
If we want PrestaShop 8.0 to be compatible with PHP 8.1, this topic should be a must-have 😅

**Comment by matks** [comment]
> If we want PrestaShop 8.0 to be compatible with PHP 8.1, this topic should be a must-have 😅

Then @MatShir can we label this issue as Must-have for 8.0.0 ?

It cannot be scoped for 8.1 because it requires a BC break so it has to be in a major version.

**Comment by MatShir** [comment]
We will discuss it on the next backlog refinement :)

**Comment by matks** [comment]
Last step https://github.com/PrestaShop/PrestaShop/pull/26923

**Comment by matks** [comment]
Thank you @atomiix
