### ISSUE TITLE
Error upgrading Ebay module

### ISSUE THREAD

**Issue by Tattiii** [PrestaShop/PrestaShop#19253]
Modules->Module Catalogue-> EBAY Module - > Upgrade->

ERROR! Exception thrown by module Ebay on our upgrade. Error sent by addons.You may need to be logged

![Error Ebay](https://user-images.githubusercontent.com/65728344/82585620-31b79e80-9b8e-11ea-8b49-5916de5bd3a3.PNG)

* PrestaShop version: 1.7.6
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @Tattiii ,
You need to be logged in your Addons account to be able to upgrade any modules.
Click on button "Connect To Addons marketplace"
Thanks!
