### ISSUE TITLE
Webservice associations setter is being called with empty values when emptying cart rows via webservice

### ISSUE THREAD

**Issue by elboletaire** [PrestaShop/PrestaShop#19252]
#### Describe the bug

The only way to get an empty cart (without entirely removing it) is by sending an xml with the `associations/cart_rows` fields empty, like so:

~~~xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<prestashop>
  <cart>
    <id>2793</id>
	<!-- [...] -->
    <associations>
      <cart_rows/>
    </associations>
  </cart>
</prestashop>
~~~

If you try to send the `associations` without that empty `<cart_rows/>` you won't be able to empty the cart. So far so good. The problem is that, when sending such xml, even though it works removing the cart_rows, you'll get an SQL error because in the background prestashop will try to update the cart_product rows, failing obviously because it has no data about such rows.

#### Expected behavior

To be able to empty a cart, without entirely removing it nor getting errors from prestashop.

#### Steps to Reproduce

1. Using your prestashop webservice, create a cart and add some products to it
2. Ensure you have debugging enabled in prestashop, otherwise the error will be ignored and everything will seem to work well.
3. Send an xml as described above, to remove the fields.

#### Additional information

* PrestaShop version: >= 1.7
* PHP version: Doesn't matter

#### Possible workaround

In `WebserviceRequest.php`, [the setter method is being dynamically called](https://github.com/PrestaShop/PrestaShop/blob/75d1932ef65c14f313307f30aec1b6f8374e87d2/classes/webservice/WebserviceRequest.php#L1642):

~~~php
<?php

$setter = $this->resourceConfiguration['associations'][$association->getName()]['setter'];
if (!is_null($setter) && $setter && method_exists($object, $setter) && !$object->$setter($values)) {
    $this->setError(500, 'Error occurred while setting the ' . $association->getName() . ' value', 85);

    return false;
}
~~~

As you can see, it's called without checking for `$values`, which could be the easy workaround here. Just add an `&& !empty($values)` to the already existing if, and should be fixed.

**Comment by florine2623** [comment]
Hi @elboletaire ,
I will ping our dev team, please stay tuned!
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
Could you take a look at @elboletaire 's issue please ?
Thanks!

**Comment by matthieu-rolland** [comment]
@florine2623 I reproduced this error in 1.7.7, I also get this error message:

**You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. From CartCore->setWsCartRows() Query was : INSERT INTO `ps_cart_product`(`id_cart`, `id_product`, `id_product_attribute`, `id_address_delivery`, `quantity`, `date_add`, `id_shop`)**

This issue should probably be fixed on develop, what do you think @PrestaShop/prestashop-product-team ?

Steps to reproduce (after having Webservice enabled and configured, with all rights)

1/ Create a cart using the webservice  (POST on `/api/carts`)
2/ Update the created cart, remove everything between `<cart_rows>` 
3/ See error

**Comment by colinegin** [comment]
ping @florine2623 @matthieu-rolland there are no sufficient labels for us to know if this issue should be fixed in priority.

**Comment by matthieu-rolland** [comment]
@colinegin I just put "minor" as the severity (the issue is that it's not possible to empty a cart via webservice), the issue is not a regression.

**Comment by elboletaire** [comment]
https://github.com/PrestaShop/PrestaShop/issues/9972#issuecomment-816610039
