### ISSUE TITLE
Contact Form Multiple Clicks Lots Of same mails 1.7.6.4

### ISSUE THREAD

**Issue by burakgit** [PrestaShop/PrestaShop#19258]
#### Is your feature request related to a problem?

Double, twice or lots of clicks generates lots of same emails from the panel, button should be disabled. 

#### Describe the solution you'd like

disabled button. 

Version 1.7.6.4
Different Theme not classic.

**Comment by florine2623** [comment]
Hi @burakgit ,

Using theme Classic PS 1.7.7.0, when clicking multiple times on Send button, the message is only sent once.
If you are using another theme, please contact directly the developer of the theme !
Thanks!

**Comment by burakgit** [comment]
@florine2623 
any change commit ? for this. i couldnt download 1.7.7.0 beta from https://www.prestashop.com/en/previous-versions. It gives network fault, any version couldnt be dowloaded.
