### ISSUE TITLE
content of unit price field translation

### ISSUE THREAD

**Issue by shelve71** [PrestaShop/PrestaShop#19254]
Hello,
someone can help me how to translate the content Price per unit description field (i mean per kilo, per liter,..) ?

Switching the language is not possibile change content of the field,

Thanks.
Antonio

screenshoot: https://prnt.sc/sl9i2i

**Comment by alfonsolr09** [comment]
https://prnt.sc/slc43z 

you mean only this back office translation?

**Comment by shelve71** [comment]
no, i mean the frontoffice content. 
I write the content of this field in backoffice but how i can traslate it in forntoffice ?

Thanks.

**Comment by alfonsolr09** [comment]
automatically appears when entering a price

https://prnt.sc/sld299
https://prnt.sc/sld2k6

**Comment by florine2623** [comment]
Hi @shelve71 ,
@alfonsolr09 has the right answer :)
Thanks!

**Comment by shelve71** [comment]
yes, actually when entering a price appear "por Kilo", but only for all languages.
I need to have "por kilo" for a language and "per chilo" for another language. 

How to change translation when language changes ?

**Comment by alfonsolr09** [comment]
> https://prnt.sc/slc43z 
> 
> you mean only this back office translation?

Probably this, but select another languaje
