### ISSUE TITLE
Bug fix remove_from_cart_url

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#19278]
#### Describe the bug

Can not delete product from cart with customization

#### Expected behavior

Delete product from cart

#### Steps to Reproduce

1. Create product with customization
2. Add in cart
3. Delete from cart

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @dariusakafest ,

Could you specify the version of PrestaShop you are using ?
With PS 1.7.6.5, removing a customizable product from cart has no issue. 
Please check my screen record :
https://drive.google.com/file/d/1OJafbu2zNEnrID51-D0optB3FUlG7njX/view

Thanks!

**Comment by dariusakafest** [comment]
I just created a customization using php without any fields.

**Comment by fest73** [comment]
@florine2623 I just created a customization using php without any fields.

**Comment by florine2623** [comment]
@dariusakafest 
I'm sorry i don't understand what you mean.
Can you tell me how you created a customization using php without any fields ?
I will follow your steps and try to reproduce the issue.

**Comment by prestascott** [comment]
Hello @dariusakafest,

Since we had no news from you for 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!

**Comment by fest73** [comment]
@florine2623 You can simply create a customization in the code. You don't need to bind any fields to it. It will need to be linked to the basket, and put the product into the basket through the code. Then go to the checkout page and try to delete the item
