### ISSUE TITLE
Syntax error in SQL upgrade file

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#19273]
#### Describe the bug

Upgrading to PS 1.7.7.0 triggers an error in a SQL command. Fortunately the concerned query is not critical as it only add hooks descriptions in the database.

#### Expected behavior

All SQL queries must be understandable and runnable.

#### Steps to Reproduce

Install the autoupgrade module.

* Use the "Local archive" channel and store the zip file of PrestaShop 1.7.7.0-beta.1 in the folder `<admin>/autoupgrade/download/`

![Capture d’écran du 2020-05-22 11-45-38](https://user-images.githubusercontent.com/6768917/82661446-f23b9180-9c23-11ea-9283-01518add0363.png)

* Run the upgrade, and wait for the database Upgrade step
* The upgrade will succeed but warn about the query it could not run.

> SQL 1.7.7.0 1064 in INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES (NULL, 'displayAdminOrderTop', 'Admin Order Top', 'This hook displays content at the top of the order view page', '1'), (NULL, 'displayAdminOrderSide', 'Admin Order Side Column', 'This hook displays content in the order view page in the side column under the customer view', '1'), (NULL, 'displayAdminOrderSideBottom', 'Admin Order Side Column Bottom', 'This hook displays content in the order view page at the bottom of the side column', '1'), (NULL, 'displayAdminOrderMain', 'Admin Order Main Column', 'This hook displays content in the order view page in the main column under the details view', '1'), (NULL, 'displayAdminOrderMainBottom', 'Admin Order Main Column Bottom', 'This hook displays content in the order view page at the bottom of the main column', '1'), (NULL, 'displayAdminOrderTabLink', 'Admin Order Tab Link', 'This hook displays new tab links on the order view page', '1'), (NULL, 'displayAdminOrderTabContent', 'Admin Order Tab Content', 'This hook displays new tab contents on the order view page', '1'), (NULL, 'actionGetAdminOrderButtons', 'Admin Order Buttons', 'This hook is used to generate the buttons collection on the order view page (see ActionsBarButtonsCollection)', '1') (NULL, 'displayFooterCategory', 'Category footer', 'This hook adds new blocks under the products listing in a category/search', '1'), (NULL, 'displayBackOfficeOrderActions', 'Admin Order Actions', 'This hook displays content in the order view page after action buttons (or aliased to side column in migrated page)', '1'), (NULL, 'actionAdminAdminPreferencesControllerPostProcessBefore', 'On post-process in Admin Preferences', 'This hook is called on Admin Preferences post-process before processing the form', '1'), (NULL, 'displayAdditionalCustomerAddressFields', 'Display additional customer address fields', 'This hook allows to display extra field values added in an address form using hook ''additionalCustomerAddressFields''', '1'): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(NULL, 'displayFooterCategory', 'Category footer', 'This hook adds new blocks un' at line 10

**Screenshots**

![image](https://user-images.githubusercontent.com/6768917/82661309-b0125000-9c23-11ea-9bf4-305415711cae.png)

#### Additional information

* PrestaShop version: 1.7.6.4 -> 1.7.7.0
* PHP version: N/A

**Comment by sam-pires** [comment]
Hello, 
this issue is not tracked, even though the PR has been reviewed.
Can we have some status please? 🙂

**Comment by Progi1984** [comment]
Fixed by #19274
