### ISSUE TITLE
[BO][IMPROVIMENT][BACKUP CONTROLLER]

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#19285]
1 - Go to BO > Advanced Params > Databases > Backups
2 - Create a backup

## Is your feature request related to a problem?

* 1 - **Done in #19286** Use icon download instead of eyes (to remain consistent with the other controllers (see SQL management for example)
![backup-icon](https://user-images.githubusercontent.com/16455155/82685342-54ac8600-9c54-11ea-925c-8387172a0955.png)

* 2 - **Done in #19286** Add a button to return to the list after download

* 3 - click on the download button

![back-to-list](https://user-images.githubusercontent.com/16455155/82685772-0d72c500-9c55-11ea-8c6a-052d115d93a6.png)

* 4 - Add filter by backup date

**Comment by florine2623** [comment]
Hi @PululuK ,

Thanks for the recommandation !
The product team will be answering your request.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@PululuK has some great ideas on Database backup in BO.
Could you take a look please ?

Thanks!

**Comment by SD1982** [comment]
Hi @PrestaShop/prestashop-product-team I put this issue back in "To do" because points 1 and 2 are done by #19286 but point 3 does not yet have a PR !

**Comment by SD1982** [comment]
Hi @PierreRambaud I reopen this issue only points 1 and 2 are dealt with by #19286 there is always point 3 to do !

**Comment by colinegin** [comment]
I close this issue as part of the work has already be done and merged.
I just created a new issue #19919 so that we know what's left to do !
Thanks
