### ISSUE TITLE
Direct Links on dashboard stats

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#19284]
As the prestashop statistics aren't accurate. Need an advice.

I am using Google Analytics and all seems fine there.

At prestashop stats i see same statistics plus "Direct Links".

I.e

I have 100 visits on Google Analytics from some sources. On presta i see that 100 and sources plus 3200 from "Direct Links".

Is there any way to disable / hide Direct Links ones?

**Comment by florine2623** [comment]
Hi @GTriber ,
Are you talking about Stats > Visitors online ?
![Capture d’écran 2020-05-22 à 17 51 27](https://user-images.githubusercontent.com/16019289/82685699-e87e5200-9c54-11ea-9775-599f7a1f67b5.png)
Natively, no you can't hide that. You would need some custom code for that feature.
Thanks!

**Comment by GTriber** [comment]
@florine2623 Hello, 

Yes about that.  Seems it possible could be fixed by my ISP. 

Not a big deal tho :)


Thank you..
Have a wonderful weekend.
