### ISSUE TITLE
Subject fields appear blank in email translation

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#19288]
#### Describe the bug

Subject's translation is not displayed in the input field when I saved it from the email translation section

#### Steps to Reproduce

1) Install a module which contains email (a mails folder inside the module).
2) To translate the email subjects in any language go to the International > Translations > Email translations like this screenshot https://prnt.sc/sm3ntw
3) Select email body translation
4) Fill subject in input field https://prnt.sc/sm3omn
5) Save and stay
6) Now after saving, there is no content in the input field https://prnt.sc/sm3ntw
The entered subject is not appearing.

**Screenshots**
https://prnt.sc/sm3ntw
https://prnt.sc/sm3omn
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
* PrestaShop version: 1.7.7.0
* PHP version: 7.2.0

**Comment by SD1982** [comment]
I was able to reproduce the issue with PrestaShop version develop , 1.7.7.x and 1.7.6.x

I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@SD1982 Hi,
I already send a pull request https://github.com/PrestaShop/PrestaShop/pull/19289 to resolve this issue.
Thanks-
