### ISSUE TITLE
Linklist - Add multistore header

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19295]
As a merchant I want to be able to switch between contexts when I have many stores, so I can choose the store(s) I want to configure and easily see which store I am configuring

[Specifications of multistore header](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)

[Specs for ps_linklist module](https://github.com/PrestaShop/prestashop-specs/blob/master/modules/ps_linklist.md)

**Comment by kpodemski** [comment]
This is partially done in https://github.com/PrestaShop/ps_linklist/pull/114

One thing left is:

> Given I am a merchant in a multistore context, when I am in the back-office and when I try to change context, if I have not saved my modifications then a modal is displayed with 2 choices: Save & Cancel.

@matthieu-rolland do we have any ETA on this modal?

cc @marionf

**Comment by marionf** [comment]
I created a new issue for this point: https://github.com/PrestaShop/PrestaShop/issues/24227
Thank you @kpodemski :)
