### ISSUE TITLE
Missing displayOrderConfirmation for GoogleAnalytics and FB Pixel

### ISSUE THREAD

**Issue by jonasburneika** [PrestaShop/PrestaShop#19293]
#### Describe the bug

In Classic Theme displayOrderConfirmation hook is missing. This hook is very important for Orders Conversion ratings. Please inform your modules providers that this hook is no available or please add this hook to a template. 

#### Expected behavior
To have all the needed hooks for order conversions monitoring. 
#### Steps to Reproduce
Initiate Google Analytics code with conversion tracking in ps_googleanalytics module, make some orders and see, that in google analytics there no conversion was registered.
PrestaShop comes with default Google Analytics module

https://github.com/PrestaShop/ps_googleanalytics

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

Please add a new Hook to the module install method.

```
 if (parent::install() &&
            $this->registerHook('displayHeader') &&
            $this->registerHook('displayAdminOrder') &&
            $this->registerHook('displayFooter') &&
            $this->registerHook('displayHome') &&
            $this->registerHook('displayFooterProduct') &&
            **$this->registerHook('displayOrderConfirmation') &&**
            $this->registerHook('actionProductCancel') &&
            $this->registerHook('actionCartSave') &&
            $this->registerHook('displayBackOfficeHeader') &&
            $this->registerHook('actionCarrierProcess')
        ) {
            return $this->createTables();
        }
```

**Comment by jonasburneika** [comment]
my Pull request: https://github.com/PrestaShop/ps_googleanalytics/pull/53

**Comment by Quetzacoalt91** [comment]
Hi @jonasburneika,

The hook `displayOrderConfirmation` actually exists on the classic theme. It is being displayed here https://github.com/PrestaShop/PrestaShop/blob/36b4b18d5927de38cb879ed5f757b4eccf6ebf46/themes/classic/templates/checkout/order-confirmation.tpl#L30-L32

And sent by the controller via a variable:
https://github.com/PrestaShop/PrestaShop/blob/36b4b18d5927de38cb879ed5f757b4eccf6ebf46/controllers/front/OrderConfirmationController.php#L96

https://github.com/PrestaShop/PrestaShop/blob/36b4b18d5927de38cb879ed5f757b4eccf6ebf46/controllers/front/OrderConfirmationController.php#L121-L127

Having `displayOrderConfirmation` & `displayOrderConfirmation1` may trigger two times the events on Google Analytics, and might generate wrong reports. Can you please double check on your side?

**Comment by jonasburneika** [comment]
Hi, @Quetzacoalt91 thanks for your explanation. It seems correct, but I have maybe 3 separate projects with this error. That customer had complained about not seeing GA and FB pixel conversions. After adding directly hook to .tpl file, conversions were registered.

I will look deeper into this.
Thx again, @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
On our side we used the module with the classic theme, and orders are reported properly (interface on the screenshot is written in French, but shows the created orders).

![image](https://user-images.githubusercontent.com/6768917/82912237-bf1b3a00-9f64-11ea-9520-bccdce1f4b72.png)

If you're using the classic theme on the 3 shops, you should check the module is properly registered on the hook "displayConfirmation" in the back office page "IMPROVE > Design > Positions".

**Comment by matks** [comment]
Hi @jonasburneika it seems this issue is going nowhere so I close it. Feel free to tell us if you got some new items and we might reopen it 😉
