### ISSUE TITLE
[webservice][1.7.7.0 beta1] PHP notice with webservice on php7.4

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#19305]
#### Describe the bug
A php notice is displayed into webservice response, so XML is broken and webservice becomes KO.
The error is:
 [PHP Notice #8] Trying to access array offset on value of type null (C:\xampp2\htdocs\prestashop-1.7.7b1\classes\webservice\WebserviceOutputBuilder.php, line 716)

#### Expected behavior
I should get XML without PHP Notice

#### Steps to Reproduce
You can use the PSWebServiceLibrary.php lib in order to try to create a product with it.
You can use my joined test file.

**Screenshots**
N/A

#### Additional information
* PrestaShop version: 1.7.7.0 beta 1
* PHP version: 7.4.5 

[test.zip](https://github.com/PrestaShop/PrestaShop/files/4677087/test.zip)

**Comment by matks** [comment]
@Max84 thank you for feedback 😉 

We really need tests for webservice 😭

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers Could you try to reproduce this issue ?

**Comment by matks** [comment]
@Max84 Just had a look, but this is actually not an issue.

PS 1.7.7. is not compatible with php7.4 . It is compatible with php7.3 and next minor version (PrestaShop 1.7.8) will be compatible with php7.4

The message you have comes from php7.4 "Trying to access array offset on value of type null"

**Comment by matks** [comment]
@Max84 thanks anyway for the feedback, it will be fixed with all other php7.4 issues for 1.7.8 😉

**Comment by Max84** [comment]
@matks I understand, it's not a problem, but do you think i should open an issue for documentation?
Because php 7.3 and 7.4 are current versions, and INSTALL.txt + https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ tell PHP 7.1.3+. So we can think php 7.4 is ok.

**Comment by matks** [comment]
@Max84 We might improve the doc to tell people to scroll a bit to check what php versions are compatible
A bit below in the page we have an accurate table https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

What we mean by "compatible with php7.1.3+" is "PS 1.7, in general, is compatible with php7 ... but for the latest versions the work to make it compatible is in progress" 😅
