### ISSUE TITLE
Multistore - Add new header on already migrated pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19300]
As a merchant I want to be able to switch between contexts when I have many stores, so I can choose the store(s) I want to configure and easily see which store I am configuring 

[Specs header](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)

This header should be displayed on all pages already migrated

As specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-3-the-page-can-be-displayed-only-in-all-shops-context), some pages can be displayed only in "all shops" context and the others contexts are not displayed in the header

List of theses pages:
- Shipping > Carriers > Add new carrier
- International > Localization > Languages
- Shop parameters > Order settings > Statuses
- Shop parameters > Order settings > Statuses > Add new order status & add new order return status
- Advanced parameters > Team > Profiles
- Advanced parameters > Team > Permissions
- Advanced parameters > Multistore > AdminShopGroup
- Advanced parameters > Multistore > AdminShop
- Advanced parameters > Multistore > AdminShopUrl
- Advanced parameters > Multistore > Add new shop group
- Advanced parameters > Multistore > Add new shop
- Advanced parameters > Multistore > Add new URL

**Comment by matthieu-rolland** [comment]
The backend part has been merged, currently working on frontend part

edit: Turns out there was more backend to do as well, the PR is now open

**Comment by NeOMakinG** [comment]
@matthieu-rolland don't hesitate to ping me anywhere you want, I can also do the front-end part myself if you want!
