### ISSUE TITLE
Multistore - Shop Parameters > General > Maintenance - Add specific settings dropdown

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19314]
## Log 
24/03/2021 - Blocked by multistore header #23292 

## Description

As a merchant, I want to be able to see if a parameter has a different value for another store when I am in "all shops" context, so I can know to which stores the change I am making will be applied

[Specs specific settings dropdown](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#specific-settings-drop-down-only-from-178)

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/23894
