### ISSUE TITLE
Prestashop support

### ISSUE THREAD

**Issue by JayWilliams74** [PrestaShop/PrestaShop#19337]
*****************************************************
TIME CRITICAL RESPONSE REQUIRED!!!!!
*****************************************************************8

#19209 - CLOSED without being RESOLVED!!!! 
FAILURE of @florine2623 to RESOLVE ISSUE

I this that as a SOFTWARE SUPPORT you should get an understanding of level of knowledge! I purposely Left a response for over 24hrs, then followed it by a Double ? to see if I was going to get a response to my request to confirm if I was doing the right thing. Yet had no response so I had to go with what I thought!

I was using PRESTASHOP's OWN Upgrade SOFTWARE to migrate me from 1.6 to 1.7 and IT FAILED causing my SITE to FAIL!!!  Not my Problem! If I had used any other method then It would be my issue!!

If files were deleted during YOUR SOFTWARE UPGRADE Process then YOU FIX IT!!!!!!!!!

The whole reason WHY i was upgrading to 1.7 was due to the fact I had an issue with the csv import not working on 1.6 which I reported on here and YOU @florine2623 told me was not supported on HERE. 

I was ending up having to build each product of over 1000 products individually, so I thought the Product Import would actually work on 1.7 as IT IS SUPPOSED TO as part of the CORE SOFTWARE (and not as an ADD-ON!! chargeable or free). If, as a software company @Prestashop offer a solution as part of the CORE SOFTWARE then anyone would EXPECT it to work as designed.

Likewise, If you are running an upgrade from one version to another then IT should not FAIL to complete the Upgrade Using the Companies OWN Upgrade Program. IF options are given as to what version of the upgrade is installed then (Unless it was a COMPLETE BETA SYSTEM with UNTESTED and UNVERIFIED changes to CORE programming) I, nor would any other USER at any LEVEL!!! would expect it to fail - shutdown a site and have anyone have to build missing tables and effectively write script that could have a detrimental effect on the Core Software workings. That is what a Software Developer or Software Support is there to do!!!

I suggest that Someone from PrestaShop makes contact with me directly through email- I will give them access to my Admin Site etc - After FULL Verification!!! And you resolve whatever issues have been caused and get MY SITE up and running within the next 24hrs so that I can continue where I left off and none of my existing work is lost.

**Comment by matks** [comment]
@JayWilliams74 I have explained everything here https://github.com/PrestaShop/PrestaShop/issues/19209#issuecomment-633588885

This is a bug tracker, not a support area. Consequently I close this issue.
