### ISSUE TITLE
Analytics doesn't track right

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#19342]
#### Describe the bug

After installing the analytics module and after running for some days bounce rate is close at zero and that is wrong. I think that something has to do with the plugin. Because I install the code manually and the bounce rate was normal but I can not track my purchases like that.

#### Expected behavior

Bounce rate is 30-40% in most sites. I saw this also in p.s 1.6 but I thought that maybe is wrong because it is old now.

* PrestaShop version: 1.7.6, 1.7.5
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @sotirisa ,

Could you specify what version of the module you are using ?
What theme are you using ?
Also, can you check if the module is hooked on all of these hooks ?
Design > Positions > Show by Google Analytics
![google_analytics](https://user-images.githubusercontent.com/16019289/83260884-cdfb2a00-a1ba-11ea-9a30-23057ec0944a.png)

Please check and let me know!

**Comment by sotirisa** [comment]
Hi, and thank you for the response.
The version of the module is 3.2.0.
My theme is the [warehouse ](https://themeforest.net/item/warehouse-responsive-prestashop-16-theme-blog/3178575)theme.
and the module is hooked in all these hooks.

I have also seen it on other sites with another theme.

**Comment by florine2623** [comment]
There is a current rework being done on that module that might fix your issues.
But, we've tested this module a few weeks ago and had nothing out of the ordinary regarding bounce rates.

For now, I will close your issue, please keep an eye on our upgrade of that module.
Thank you for your understanding !
