### ISSUE TITLE
Round mode and Round typ

### ISSUE THREAD

**Issue by mahdimedia** [PrestaShop/PrestaShop#19350]
I use Bahrain currency
Are three decimal places

Round mode and Round typ
It does not work forever and there is no effect

I want to round the number up next even value

![gpjDPV](https://user-images.githubusercontent.com/2321818/82884916-1b725f80-9f4d-11ea-81ab-14cf019bb0be.png)

![tQ5RSB](https://user-images.githubusercontent.com/2321818/82885221-8754c800-9f4d-11ea-8ce5-5e8baca0f5ec.png)

**Comment by sarahdib** [comment]
@mahdimedia 

Could you provide me more information : 
PrestaShop Version : 
Php Version : 

Thank you

**Comment by mahdimedia** [comment]
PrestaShop Version : 1.7.7 and 1.7.6
Php Version : 7.1

**Comment by florine2623** [comment]
Hi @mahdimedia ,

What exactly is the issue here ? 
How can I reproduce it ? Please share the steps !
Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
