### ISSUE TITLE
Class not found exception 

### ISSUE THREAD

**Issue by LokeshVarman** [PrestaShop/PrestaShop#19352]
Sorry, Since i am new to this. Please help me .Thanks in advance

![image](https://user-images.githubusercontent.com/30750553/82891510-7ca92b80-9f6b-11ea-9c52-442847b5f6da.png)

**Comment by sarahdib** [comment]
Hello @LokeshVarman 

Please could you explain the step to reproduce and your prestashop version ?

Thank you

**Comment by LokeshVarman** [comment]
Prestashop 1.7.5.6

**Comment by florine2623** [comment]
Hi @LokeshVarman ,
Please share the exact steps so we can reproduce the issue to help you.

If you need personalized help, please contact the support at PrestaShop : https://addons.prestashop.com/en/388-support
Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
