### ISSUE TITLE
Multistore - Orders > Invoices - Add checkboxes

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19381]
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

Documentation: https://devdocs.prestashop.com/1.7/development/multistore/configuration-forms/

Implementation example: https://github.com/PrestaShop/PrestaShop/pull/24393

Example of [multistore form](https://github.com/prestashop/prestashop/blob/b852579779071e6af6c70b7c585ae99a4480f3d3/src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/MaintenanceType.php)

Exemple of [data configuration class
](https://github.com/prestashop/prestashop/blob/cf717ae668ff649cb7baf58446e8989213536c40/src/Adapter/Shop/MaintenanceConfiguration.php)

**Comment by MeKeyCool** [comment]
@PrestaShop/product-team , 
> [Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

link is broken.

I found this one : [https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md). Is it the good link ?

**Comment by MeKeyCool** [comment]
Seen with @eshraw, `Invoice number` field is linked to Order `Invoice number` and as to be an integer (it was previously a Number)
