### ISSUE TITLE
After upgrade from 1.7.5.1 to 1.7.6.5 i can't view some customers from backend

### ISSUE THREAD

**Issue by rriempie** [PrestaShop/PrestaShop#19394]
Hi,

After upgrade from 1.7.5.1 to 1.7.6.5 i can't view some customers from backend and some customers are having problems logging in or can't login at all. I used the 1-click-upgrade module and did get some errors and did not completely finish. 

I finished the upgrade manually and everything is working now except i can't view the customers from the backend and get an error.

Unexpected error: [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]

Who can help?

Prestashop 1.7.6.5
PHP 7.2

Changing the php version doesn't help. When i tried to upgrade the database i also got an error:

Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: in /home/XXX/public_html/classes/Currency.php:219 Stack trace: #0 /home/XXX/public_html/classes/Currency.php(811): CurrencyCore->__construct('1') #1 /home/XXX/public_html/classes/Currency.php(557): CurrencyCore::getCurrencyInstance('1') #2 /home/XXX/public_html/classes/Currency.php(468): CurrencyCore::addCldrDatasToCurrency(Array, true) #3 /home/XXX/public_html/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php(47): CurrencyCore::getCurrencies(true, false) #4 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #5 /home/XXX/public_html/src/PrestaShopBundle/Install/Upgrade.php(482): call_user_func_array('ps_1760_copy_da...', Array) #6 /home/XXX/public_html/src/PrestaShopBundle/Install/Upgrade.php(825): PrestaShopBundle\Install\Upgrade->upgradeDb(Array) #7 /home/XXX/public_html/install/upgrade/upgrade.php(92): PrestaShopBundle\Install\Upgrade->run() #8 {main} thr in /home/XXX/public_html/classes/Currency.php on line 219

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.

![capture d'écran_2627](https://user-images.githubusercontent.com/13449658/83020496-da4f7d80-a028-11ea-8070-525366ebc284.png)

![capture d'écran_2628](https://user-images.githubusercontent.com/13449658/83020484-d58ac980-a028-11ea-9f8d-249f85a2bbac.png)

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Comment by blessedmajome** [comment]
> Hi,
> 
> After upgrade from 1.7.5.1 to 1.7.6.5 i can't view some customers from backend and some customers are having problems logging in or can't login at all. I used the 1-click-upgrade module and did get some errors and did not completely finish.
> 
> I finished the upgrade manually and everything is working now except i can't view the customers from the backend and get an error.
> 
> Unexpected error: [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]
> 
> Who can help?
> 
> Prestashop 1.7.6.5 PHP 7.2
> 
> Changing the php version doesn't help. When i tried to upgrade the database i also got an error:
> 
> Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: in /home/XXX/public_html/classes/Currency.php:219 Stack trace: #0 /home/XXX/public_html/classes/Currency.php(811): CurrencyCore->__construct('1') #1 /home/XXX/public_html/classes/Currency.php(557): CurrencyCore::getCurrencyInstance('1') #2 /home/XXX/public_html/classes/Currency.php(468): CurrencyCore::addCldrDatasToCurrency(Array, true) #3 /home/XXX/public_html/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php(47): CurrencyCore::getCurrencies(true, false) #4 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #5 /home/XXX/public_html/src/PrestaShopBundle/Install/Upgrade.php(482): call_user_func_array('ps_1760_copy_da...', Array) #6 /home/XXX/public_html/src/PrestaShopBundle/Install/Upgrade.php(825): PrestaShopBundle\Install\Upgrade->upgradeDb(Array) #7 /home/XXX/public_html/install/upgrade/upgrade.php(92): PrestaShopBundle\Install\Upgrade->run() #8 {main} thr in /home/XXX/public_html/classes/Currency.php on line 219

Hie, have you fixed this?

**Comment by rriempie** [comment]
Yes, it is fixed.
I don’t even remember what the problem was.

I can be closed.
