### ISSUE TITLE
After updating to 1.7.7.0, my module stopped working

### ISSUE THREAD

**Issue by eramirezprotec** [PrestaShop/PrestaShop#19403]
#### Describe the bug

After updating from 1.7.6.5 to 1.7.7.0, my module stopped working.

#### Expected behavior

My module uses the following hooks:

- backOfficeHeader
- actionAdminControllerSetMedia
- displayAdminProductsExtra
- actionProductSave
- actionProductDelete

The last three are not working.

I already uninstalled and installed the module and deleted the cache. It's still not working. 

#### Steps to Reproduce

1. Create new module
2. Register this hook: displayAdminProductsExtra
3. Use something like dump or error_log, and also, if possible, return a .tpl or a .twig
4. In the BO, enter to Catalog -> Product and select any product
5. The "Modules" tab is not present, and no code within the hook is being executed

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.4

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers Could you try to reproduce this issue ?

**Comment by PierreRambaud** [comment]
Duplicates of #19246

**Comment by eramirezprotec** [comment]
I don't think this ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19246. In that ticket, there is only one problem being mentioned: the displayAdminProductsExtra hook not working.

But this ticket also mentions that there are two more hooks not working: actionProductSave and actionProductDelete.

@PierreRambaud

**Comment by matks** [comment]
Reopening then

Thank you for testing the beta !

**Comment by colinegin** [comment]
ping @jolelievre do you reproduce this issue ?

**Comment by PierreRambaud** [comment]
Hi everyone,
I'm not able to reproduce the issue with the latest changes on 1.7.7.x branch.
The `displayAdminProductsExtra` hook is proplery handle :)

**Comment by pardvm** [comment]
@eramirezprotec  ?

**Comment by eramirezprotec** [comment]
@pardvm 

This ticket was opened on May 27.

The answer provided by @PierreRambaud indicates that this problem is not happening when working with the latest changes in the 1.7.7.x branch, which includes a lot of new code.

If the time arrives for it, we will check that everything works correctly.
