### ISSUE TITLE
Unable to save product, post error 504

### ISSUE THREAD

**Issue by crc30** [PrestaShop/PrestaShop#19405]
#### Describe the bug
When we update the products only with combinations, post request show error 504
When turn on dev mode result in green success message confirmation but products are not updated after a refresh we cant see the modification in any fields

#### Steps to Reproduce

1. Go to 'product with combinations'
2. Click on 'save'
3. See error

**Screenshots**
![error_ps](https://user-images.githubusercontent.com/19255388/83010638-d6b3fa80-a018-11ea-803c-dfb1d475c1b0.jpg)

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.1

**Comment by marionf** [comment]
Hello,

Despite our several trials, and as you can see in the screenrecord below, we could not reproduce your issue with the provided information on the last 1.7.7 version.

https://drive.google.com/open?id=1Peq0LfXMJd9lc-i2EhgZkIul_mF8Ed5w

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.
