### ISSUE TITLE
Hook for modifying TinyMce

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#19408]
It would be useful to alter the `tinySetup(config)` function.

Maybe add a (PHP)-hook somewhere to assign a JS-variable: `tinyMceOverrides` so one can do something like this:

    function hookTinyMceConfigDefault(&$config){
          $config['toolbar1' = "code,colorpicker,bold,italic,underline,strikethrough,blockquote,link,align,bullist,numlist,table,image,media,mysuperspecialtoolbarmagictrick";
    }

Then in `js/admin/tinymce.inc.php`  something like:

    
      $.each(tinyMceOverrides, function (index, el) {
           config[index] = el;
       });

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers WDYT of this improvement ?

**Comment by PierreRambaud** [comment]
Look a good idea :+1:

**Comment by marionf** [comment]
@PierreRambaud Could you update the labels ?
Is there something to specify or is it ready to be developed ?

**Comment by PierreRambaud** [comment]
ping @NeOMakinG it's up to you to define the best way to customize TinyMce :wink:

**Comment by NeOMakinG** [comment]
@onklmaps does it has to alter the whole config, like if the var exist, take the var, else take the default config used in prestashop? I'll need some helps for the backend part @PierreRambaud :p

**Comment by madsoliver** [comment]
@NeOMakinG Like you say sounds like the best way (if the var exist, take the var, else take the default config) 😃

@PierreRambaud maybe declare entire ` var default_config` via PHP, then the new hook can change the config like the following? 

    function hookTinyMceConfig(&$config) {
          $config['toolbar2'] = 'alignleft aligncenter alignright';
    }

**Comment by PierreRambaud** [comment]
@onklmaps @NeOMakinG Agreed! But maybe use `var defaultTinyMceConfig` to be less generic in the variable name :)

**Comment by PierreRambaud** [comment]
@NeOMakinG There is already a PHP hook to change JavaScript settings: `actionAdminControllerSetMedia`
