### ISSUE TITLE
Multistore - Shop parameters > Traffic & SEO > Search engines > Add new search engine - Add information message

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19417]
Currently, this page don’t have shop association block.
In this case, the element is added for all shops, no matter the context selected

To avoid frustration, we should inform the merchants of this behavior:
Display an information message on this page: "Note that this feature is available in all shops context only. It will be added to all your stores."

This is specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-2-add-new-pages-without-shop-association-block)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/23441

![image](https://user-images.githubusercontent.com/16067358/121928672-af71bd80-cd40-11eb-9bf1-f43a5db67d5f.png)

Thank you!

**Comment by matks** [comment]
Hello @marionf the message has been added to the migrated "Shop parameters > Traffic & SEO > Search engines > Add new search engine" page

But it was added only on the "Add new" not the "Edit". Is it the expected behavior?

**Comment by marionf** [comment]
> But it was added only on the "Add new" not the "Edit". Is it the expected behavior?

@matks, yes that's the expected behavior
