### ISSUE TITLE
displayAdminOrderTabLink and displayAdminOrderTabContent not available

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19439]
#### Describe the bug

We create a test module to show that displayAdminOrderTabLink and displayAdminOrderTabContent  are not available.

![image](https://user-images.githubusercontent.com/52157233/83138854-b86aff00-a0eb-11ea-8626-da84588ac56c.png)

The tab cannot be displayed.

[This code always return 0](https://github.com/PrestaShop/PrestaShop/blob/6cd77a56c5c7705589185c8ce5709f109c5b54af/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig#L114) : 
if hookcount('displayAdminOrderTabLink') > 0 or hookcount('displayAdminOrderTabContent') > 0

#### Expected behavior

displayAdminOrderTabLink and displayAdminOrderTabContent must be displayed

So we try tom [comment this line](https://github.com/PrestaShop/PrestaShop/blob/6cd77a56c5c7705589185c8ce5709f109c5b54af/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig#L114) 

![image](https://user-images.githubusercontent.com/52157233/83138744-8e194180-a0eb-11ea-96a0-e00f4e5a6dca.png)

#### Steps to Reproduce

1. Install 1.7.7
2. [Install this module](https://github.com/PrestaShop/PrestaShop/files/4695351/tottesthooks.zip) prepared by @jhoarau 
3. See the bug or don't see the tab

Please note I'm focus on these new hooks, but I found that "hookcount" twig function is used for hook displayAdminProductsExtra. So we had this hook on the test module and it looks like "Module tab" on product page is not displayed... I am not sure defining displayAdminProductsExtra
is enought to show Module tab. To be verify...

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
Function `hookCount()` has a bug which is why it is not usable for now.

Bugfix is on the way https://github.com/PrestaShop/PrestaShop/pull/19216

**Comment by clotairer** [comment]
I confirm your PR #19216 fix our bug 

Thank you
