### ISSUE TITLE
Prestashop 1.7.6.5 - order_conf email is missing variables (BUG)

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#19436]
When creating my own Order Status, and applying an existing email template to it, when the email is sent, there is missing information.

Steps to reproduce :
- BO : Create new order status, choose option Send Mail and chose template
- FO : Place an order
- BO : Change order status with your newly create status
- Mail received with missing variables
![Capture d’écran 2020-06-01 à 16 31 44](https://user-images.githubusercontent.com/16019289/83419649-b07dc880-a425-11ea-8495-94c40e90684f.png)
![Capture d’écran 2020-06-01 à 16 31 54](https://user-images.githubusercontent.com/16019289/83419653-b2478c00-a425-11ea-909e-cd4ca5a0b806.png)

Expected behavior :
Emails should be sent with all info available.

**Comment by florine2623** [comment]
Hi @thbl ,
What version of PrestaShop are you using ? PHP version ?
Can you detail the exact steps to reproduce your issue ?
Thanks!

**Comment by thbl** [comment]
@florine2623 
php 7.2 prestashop 1.7.6.5
steps alrady descriped in link

**Comment by florine2623** [comment]
Does the email address of the customer receiving this contain capital letters ?
It might be linked to : https://github.com/PrestaShop/PrestaShop/issues/19294
Please check and let me know

**Comment by thbl** [comment]
@florine2623 
No the issue is that if you change ordre status in BO that send a "order_conf" email all vairables shows as variables etc.{total_products}....
But if customer places order and mail i send from the front end action variables are resolved correct and show info they contain

**Comment by florine2623** [comment]
I can't reproduce your issue on PS 1.7.6.5, please check my screenshot after changing order status :
![Capture d’écran 2020-05-28 à 18 11 01](https://user-images.githubusercontent.com/16019289/83166079-ababd280-a10e-11ea-81c1-5d5e36dc054e.png)

**Comment by thbl** [comment]
@florine2623  did you make a new ordre status and give it email template of order_conf ?

**Comment by florine2623** [comment]
I have reproduced your issue in both PS 1.7.6.5 and PS 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Steps to reproduce :
- BO : Create new order status, choose option Send Mail and chose template
- FO : Place an order
- BO : Change order status with your newly create status
- Mail received with missing variables

Examples:
![Capture d’écran 2020-06-01 à 16 31 44](https://user-images.githubusercontent.com/16019289/83419509-744a6800-a425-11ea-84b4-370331d36b97.png)
![Capture d’écran 2020-06-01 à 16 31 54](https://user-images.githubusercontent.com/16019289/83419521-790f1c00-a425-11ea-99d5-ad555945fa55.png)


Thanks!

**Comment by Hlavtox** [comment]
This is normal behavior, you cannot just create any variable in the email and expect it to be filled...

Only these ones can be used:
```
                $data = array(
                    '{lastname}' => $customer->lastname,
                    '{firstname}' => $customer->firstname,
                    '{id_order}' => (int) $order->id,
                    '{order_name}' => $order->getUniqReference(),
                    '{nbProducts}' => count($virtual_products),
                    '{virtualProducts}' => $links,
                );
```

If you want to resend order confirm, you can use the code I posted to the thread, works OK. https://github.com/PrestaShop/PrestaShop/issues/14754#issuecomment-623364507 🚀

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team could you please check if this is the expected behavior as @Hlavtox mentioned or it's a bug?

**Comment by Hlavtox** [comment]
Invalid issues, I confirm what I said two years ago. You need to assign required variable via a hook. Only basic variables are available for basic order status emails.
