### ISSUE TITLE
Fatal error on Design > Theme & logo > Page configuration

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19446]
#### Describe the bug

Fatal error on Design > Theme & logo > Page configuration, seems to be a regression on 1.7.7.x

#### Expected behavior

No exception

#### Steps to Reproduce

1. Go to Design > Theme & logo > Page configuration
2. See error

**Screenshots**

![capture d'écran_2629](https://user-images.githubusercontent.com/13449658/83168562-f24efc00-a111-11ea-9a03-f4d860b94be3.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
From the error we can see it comes from ps_themecusto

However we dont know if ps_themecusto is wrong OR 1.7.7 code makes it crash

**Comment by florine2623** [comment]
Hi @marionf & @matks ,
I managed to reproduce the issue with PrestaShop version 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed.
Thanks!

**Comment by colinegin** [comment]
Investigation needed to know if the bug should be fixed in the core or in the theme custo module.

Edit :
We need to update the version of the module in composer.json.

**Comment by eternoendless** [comment]
Fixed in the module's release v1.2.0 https://github.com/PrestaShop/ps_themecusto/pull/20

Make sure that the module version is 1.2.0 in composer.lock and update it as necessary.

**Comment by Progi1984** [comment]
I have the good version : 
![image](https://user-images.githubusercontent.com/1533248/83646182-9bcf3b00-a5b3-11ea-9165-c0c308258168.png)

And I don't have the problem :
![image](https://user-images.githubusercontent.com/1533248/83646272-ba353680-a5b3-11ea-88c9-7a4c469149dd.png)

It's Fixed ;)

**Comment by Progi1984** [comment]
Need to update the `composer.lock`
