### ISSUE TITLE
Replace "defunct" material-design-icons

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#19440]
#### Is your feature request related to a problem?

[material-design-icons project](https://github.com/google/material-design-icons) was pretty much abandoned by Google. Even though new icons were added in the font, the github project (and npm package) was abandoned years ago.

#### Describe the solution you'd like

Replace the library with [Material Design Icons DX](https://github.com/jossef/material-design-icons-iconfont). This change will not break anything but add all the new icons for developers to use.

**Comment by florine2623** [comment]
Hi @rdy4ever ,
Thanks for the recommendation, please stay tuned as I ping our product team.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

@rdy4ever would like to have a new library available in PS to use new icons, is this possible ?

Thanks!

**Comment by rdy4ever** [comment]
> Hi @PrestaShop/prestashop-core-developers ,
> 
> @rdy4ever would like to have a new library available in PS to use new icons, is this possible ?
> 
> Thanks!

Actually, it's the kindof the same library, just updated/upgraded.

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
Hey @rdy4ever,

Why not, but it's been 13 months without any commit on this one too, and there is only one maintainer on the npm page, I'm not sure but I think we don't add library with only one maintainer on npm ! Is there any other library up to date and with some moovement ?

What do you think @PrestaShop/prestashop-core-developers ?

**Comment by rdy4ever** [comment]
I couldn't find one... but 13 months is better then... 3 years, right?

**Comment by NeOMakinG** [comment]
Of course, was just asking if another option is more viable ;)

**Comment by rdy4ever** [comment]
@NeOMakinG At least this one has all the icons present in Google's iconfont. It's a bit frustrating as a theme developer to try and add an icon showcased in the official docs, just to see a blank square instead :)
And then you might say, "no biggie, I'll just update the npm package" just to realize there is no more recent pack.

**Comment by NeOMakinG** [comment]
Waiting for the advice of more peoples of the team and I'm gonna work on this, don't worry

**Comment by Progi1984** [comment]
Ping @eternoendless @PierreRambaud

**Comment by PierreRambaud** [comment]
@NeOMakinG DO IT!

**Comment by NeOMakinG** [comment]
Opened a PR for this ! @rdy4ever
