### ISSUE TITLE
Generated voucher not displaying in the cart summary for a customer

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19442]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Vouchers that were generated by the module are not displayed in the cart summary. 

![image](https://user-images.githubusercontent.com/52157233/83151826-56b39080-a0fd-11ea-90ae-178a225665fd.png)

In voucher settings, setting "Highlight" is enabled

![image](https://user-images.githubusercontent.com/52157233/83151859-6632d980-a0fd-11ea-93b3-ec3df0ce760a.png)

#### Steps to Reproduce

- Generate a new voucher to a specific customer with a code
- Add some product to the cart
- Check voucher in the cart summare

Voucher is not displayed in the cart summary.

We sale on addons store a [module that use this feature](https://addons.prestashop.com/fr/fidelisation-parrainage/7301-programme-de-fidelite-avance-loyalty-points.html). We need to show a coupon generated for the user. If not he will forget to use it if he want and he need get the code on his account page... To complicated. 

For us it's a regression. We work on a PR.

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by clotairer** [comment]
The PR is published. We just add a check to verify if voucher code is defined or not. If the voucher is not defined then, the voucher is now in 1.7.7 automatically applied and the highlight is not necessary.

**Comment by florine2623** [comment]
Hi @clotaire202 ,
I have managed to reproduce the issue, it is indeed a regression.
Thanks for the PR !

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19456
