### ISSUE TITLE
Exception on FO on subcategories pages

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19451]
#### Describe the bug

On FO, when trying to access subcategories pages (Best Sales, New Products, or Search), there is an Exception.

#### Expected behavior

It should work :stuck_out_tongue: 

#### Steps to Reproduce

1. Go to FO, then Prices drop or New products or Best sales or make a search (and press Enter, do not use autocompletion search)
2. See error

**Screenshots**

![screencapture-localhost-ps178-fr-recherche-2020-05-29-09_40_40](https://user-images.githubusercontent.com/55688534/83234414-7ea00400-a190-11ea-9ba8-3494094eb84f.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by matks** [comment]
Changed introduced by https://github.com/PrestaShop/PrestaShop/pull/16928

**Comment by matks** [comment]
A bit strange that such a "big red screen" mistake was able to slip through puppeeteer 🤔 

@SimonGrn did you enable the Link Checker ? Should'nt it have spotted that ?

**Comment by matks** [comment]
Bugfix is here https://github.com/PrestaShop/PrestaShop/pull/19501

**Comment by boubkerbribri** [comment]
@matks 
> A bit strange that such a "big red screen" mistake was able to slip through puppeeteer thinking

Our sanity tests does not test this pages (New products, Best sales and searh).

But the weird thing, we have a functional test (Search product on FO) which fails on local machine but not in the nightly (for 3 days in a row). We are investigating this matter.

> @SimonGrn did you enable the Link Checker ? Should'nt it have spotted that ?

For the linkchecker, we did not enable it, why ? because we still have some js and request errors in BO, and since we wanted to add it as a github action, it will block all PRs from merging.

**Comment by matks** [comment]
> Our sanity tests does not test this pages (New products, Best sales and search).

Search page is quite an important FO page, I suggest adding a test on it in the future 😉 I think "searching for products" is an important customer behavior

> For the linkchecker, we did not enable it, why ? because we still have some js and request errors in BO

Would it be possible to have the list of these errors in a github issue ? So we can identify and fix it

**Comment by boubkerbribri** [comment]
> Would it be possible to have the list of these errors in a github issue ? So we can identify and fix it

I will create the issues

**Comment by SimonGrn** [comment]
> > Our sanity tests does not test this pages (New products, Best sales and search).
> 
> Search page is quite an important FO page, I suggest adding a test on it in the future  I think "searching for products" is an important customer behavior

We have to balance features and time. We could add this test, but that means 1 or 2 more minutes for sanity tests. We had to make choices and searching in FO wasn't categorized as important as "installing", "creating products" or "completing a checkout". Reminder: the scope for sanity tests was decided with the Product team.
We can create a test for searching but I'm not sure this is necessary. As you can see here, this behavior was obvious enough for our testers to spot.

**Comment by boubkerbribri** [comment]
We found why nightly haven't found the big Red screen : 
Our tests are executed in production mode (debug mode = false), and the error only occurs when testing on dev mode (debug mode = true).
