### ISSUE TITLE
Multistore - Catalog > Products > Add / edit - Update message when a group is selected

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19459]
Currently, this page isn't working in a group context
The current information message is "You can't add or edit a product in this shop context: select a shop instead of a group of shops." 

For a better understanding, we should update the current message for the following one:
"Note that this page is available in a single shop or in all shops context. Switch context to work on it."

This is specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-6-the-page-is-displayed-only-when-a-specific-shop-or-all-shops-is-selected)

**Comment by Progi1984** [comment]
I close as the wording is already correct : https://github.com/PrestaShop/PrestaShop/pull/27680#discussion_r815949933.

Thanks @Julievrz
