### ISSUE TITLE
Prestahop checkout not work

### ISSUE THREAD

**Issue by srn87** [PrestaShop/PrestaShop#19469]
I am on the main screen of the native module of prestashop checkout of paypal and I try to log in with my paypal account, when I click on it it stays in the same place, it does not advance to any other side.

![paypalproblem](https://user-images.githubusercontent.com/66142800/83313111-b187dd80-a20c-11ea-95dd-37986ac79cec.png)

PD:
I have not put the data clearly for security measure but when I put the correct data from my paypal it does not work, it stays on the same screen that you see in the capture.

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.31

**Comment by Matt75** [comment]
What is ps_checkout version ?
Can you check in `var/logs/ps_checkout` if errors are logged ?

**Comment by srn87** [comment]
Hi @Matt75 it is 1.4.1 version of prestashop checkout.

Yes, it tells me that there is an error in the login that the credentials are not correct, but I use the same credentials that I use for paypal.es user and pass equal no?

**Comment by Matt75** [comment]
No here it’s PrestaShop Checkout account not PayPal account

1. Create a PrestaShop Checkout account or sign in with an existing PrestaShop Checkout account
2. Sign in with your PayPal Account when you have been successfully signed in with your PrestaShop Checkout account.

**Comment by srn87** [comment]
fixed, you have solved 2 problems for me 1 week for it in 5 min, you are a genius, thank you very much @Matt75
