### ISSUE TITLE
(1/1) ContextErrorException Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by hybitu** [PrestaShop/PrestaShop#19460]
Hello!

I have a fresh installation of Prestashop 1.7, my theme is classic, I traied to diactivate the subscription module, but when I reloaded the backed of my prestashop I get this error:

[localhost.zip](https://github.com/PrestaShop/PrestaShop/files/4702022/localhost.zip)

The module said it needed to be upgraded but I selected deactivate it, I guess it was the thing that triggered the error, but I cannot be sure. I cannot access now to my administration area.

I hope someone could at least tell me how to restore modules status in datable. to try.

**Comment by florine2623** [comment]
Hi @almajime ,
Please make sure the version of PHP is compatible with the version of PrestaShop :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
If you are using 1.7.6.5, PHP version should be 7.2 max.
Thanks!

**Comment by matks** [comment]
Indeed the message "Warning: "continue" targeting switch is equivalent to "break" ..." is usually prompted when using php7.3
