### ISSUE TITLE
Display backoffice orders

### ISSUE THREAD

**Issue by SolucionesIE** [PrestaShop/PrestaShop#19476]
I have a problem with viewing orders in the backoffice in Prestashop 1.7.6.5.
It opens like this:
![screencapture-magiaviral-mvadmin-index-php-2020-05-31-00_36_59](https://user-images.githubusercontent.com/66195002/83345325-5ec72800-a2d7-11ea-922e-4d2d924c3120.png)

Thanks for your help.
Regards

**Comment by florine2623** [comment]
Hi @SolucionesIE ,
Could you enable debug mode ?
What version of PHP are you using ?
Thanks!

**Comment by SolucionesIE** [comment]
Notice on line 101 in file /home/magiaviral/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13)

**Comment by SolucionesIE** [comment]
![screencapture-magiaviral-mvadmin-index-php-2020-06-01-07_57_17](https://user-images.githubusercontent.com/66195002/83411275-8a343a80-a3dd-11ea-8ae9-3a4447ce054b.png)

**Comment by florine2623** [comment]
Clear your cache and check if you still have errors.

**Comment by SolucionesIE** [comment]
When accessing the advanced parameters it gives me this:
![screencapture-magiaviral-mvadmin-index-php-configure-advanced-performance-2020-06-01-09_47_38](https://user-images.githubusercontent.com/66195002/83421057-2154be80-a3ed-11ea-91d2-13281b2690e3.png)

**Comment by florine2623** [comment]
Clear cache manually from /var/cache folder.

This seems to be a permission issue. You need to check with your host directly regarding the server configuration.

Also make sure, the version of PS you are suing is compatible with the version of PHP : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I will close this ticket as this is not a core issue from PrestaShop.
