### ISSUE TITLE
Multiple column sorting using Grid component

### ISSUE THREAD

**Issue by gadnis** [PrestaShop/PrestaShop#19471]
#### Is your feature request related to a problem?

First, this is a question and if the answer is "No", than it is a feature request 😁
Question: - Is it possible to sort multiple columns with grid component? No? Than why not?

#### Describe the solution you'd like

It would be great to be able sort by multiple columns. Excel has this option, why not have it here too? Example: I need to sort product list by category first and by quantity second. Or first by active products and than by quantity. I believe there is many cases where this is very useful. Sadly I did not find how to do that.

I believe this is related to the strict `SearchCriteriaInterface`, 
it has separated `orderBy` and `sortOrder` filter types. 
I believe these two should be a single variable, to be able collect all possible sorting values in one array.
Later apply sorting array in the loop using `DoctrineSearchCriteriaApplicator::applySorting(...)`

What do you thing about multiple column sorting feature?

**Comment by jolelievre** [comment]
Hi @gadnis 

Indeed it is not possible to sort Grid by multiple values as of now. As to why I'd say the feature has been mainly designed depending on the UX, in which you can only select one column for sorting.. So the query matches this behaviour and only sort based on a single column, the `SearchCriteriaInterface` (as you pointed) also reflects this behaviour

That said I understand your need, this might be a nice feature to add but it would require multiple UX and architectural changes. Maybe a new `SearchCriteria` interface to manage multiple sorting (to avoid a breaking change on the existing one).

But the most difficult challenge to me would the UX perspective:
- how do you select multiple columns that are "sorting" (as opposed to the usual One click -> one sort)
- how do you manage the priority between these columns (first ID desc, the Date asc, ...)
- how do you unselect a column for sorting

I think this feature would need to more defined along with @PrestaShop/prestashop-product-team (if it is ever integrated ^^, no guaranty of course).

Thanks for this proposal anyway!

**Comment by gadnis** [comment]
@jolelievre thanks for your answer! At least I am sure now that this is not integrated 😁 

Regarding the UX perspective, I like [vuetable2](https://www.vuetable.com/guide/sorting.html#multi-column-sorting) feature how they deal with multi-column sorting. The user can use Alt+Click to multi-sort (select/unselct)
Actually [vuetable](https://www.vuetable.com/) is the reason I created this post. 

But as you've said, this require architectural changes and I believe there's no one interested to change it only for this feature 😁  

Thanks again for you reply ;)

**Comment by jolelievre** [comment]
Damn `vuetable` 😅

The feature can be interesting though, but I don't know if it will be prioritized over some other expected features, it's worth trying though ^^

If you are motivated and want to add this feature feel free to propose a Pull Request though, we will help you as much as we can

**Comment by colinegin** [comment]
ping @TristanLDD @prestascott what do you think about this feature ?

**Comment by prestascott** [comment]
Hi everyone,

Thank you @gadnis for your report. 

This might be a nice feature but we didn't encounter this need from our merchants yet... First, we need to identify use cases for this feature so that way it can be useful. But for the moment, it's not required. 
Can you provide us some use cases please?

Sorting columns like we currently have is enough for our users.

**Comment by gadnis** [comment]
@prestascott actually I can't remember now, this post was almost 3 months ago 😁  Probably you are right, if user use filters, the multiple sorting is not required.. well maybe in a very rare scenarios. 

What I really miss in prestashop is filtering by 'greater than number', 
example: filters quanty by ">0". But this is other topic 😁. 

So this topic probably can be closed.. 😁

**Comment by MatShir** [comment]
Thanks @gadnis, the issue will be reopened if more users are interested.

**Comment by VdomaNet** [comment]
Very strange... Nobody needs it? 
I have products that are not available (of course I don't want to remove from the list). 
I would like to show them at the end of the list.
It seems to make sense? That is everyone does it in another way? Very strange...
