### ISSUE TITLE
"500 Internal Server Error". After "PrestaShop Marketplace in your Back Office" module update.

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#19483]
I got a notification that there was an update for "PrestaShop Marketplace in your Back Office" module.
After the update was finished and i clicked to return to dashboard i got the following error..

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by DPStudioGR** [comment]
Hi...
Can you please tell me how i can disable this module from database, or what is its name in the php database?

**Comment by Matt75** [comment]
Hi @Stampa-Stampa 

This is a cache issue, we released a new version of ps_mbo on last Friday to fix it.

Please follow instruction provided with the new version : https://github.com/PrestaShopCorp/ps_mbo/releases/latest

**Comment by DPStudioGR** [comment]
Thanks ...it worked
