### ISSUE TITLE
[PrestaShop 1.7.7.0] Logo is not displayed if I use theme from 1.7.6 or other versions

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#19484]
#### Describe the bug

If I use the theme from PrestaShop 1.7.6 in 1.7.7, the shop logo is not displayed:
https://prnt.sc/srdrc6

It happened because the path to the logo in 1.7.7 looks like this:
src="{$urls.img_ps_url}{$shop.logo}"

and in 1.7.6 like this:
src="{$shop.logo}"

This small change will cause many problems, because after upgrade from for example PrestaShop 1.7.6 to 1.7.7 almost all users (literally thousand of shops) will have the same problem with the missing logo and this will generate many questions on the forum, GitHub and also tons of unnecessary work for developers.

If possible, I recommend using the old logo path:
src="{$shop.logo}"

Thanks in advance

#### Additional information

* PrestaShop version: 1.7.7.0

**Comment by florine2623** [comment]
Hi @Angar90 ,
With the classic theme, I have no issue.
If you are using another theme, please make sure it is compatible with PS 1.7.7.0.
Please check with the developer of the theme.
Thanks!
