### ISSUE TITLE
Droplist to change the number of products in the list

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19486]
**User story**
As a merchant, when I have more than 50 products on the order page I would like to check them quickly to edit one without having to go through all the pages.

**Solution**
The best solution would have been a search but because we are stabilizing at the beta phase. The simpler solution, we will be to add a drop list to change the number of products displayed by pages.

**Detailed specs**

On the left-bottom of the product list, a droplist can change the number of products on the product list. The possible value is 8, 20, 50, or 100.

<img width="1124" alt="Capture d’écran 2020-06-03 à 17 18 43" src="https://user-images.githubusercontent.com/27484094/83656134-79431f00-a5bf-11ea-9c33-63b9c3ffb7a5.png">
Invision link: https://invis.io/YKTGGFZAMCB#/392128609_Products_-_Pagination

The selected value will be saved and shared to all the orders
If a merchant selects 20 on one order then, on the next order, the product list will display the 20 products per page.

**Comment by Progi1984** [comment]
Fixed by #19582
