### ISSUE TITLE
Errow with tax exempt customers

### ISSUE THREAD

**Issue by jose73wrc** [PrestaShop/PrestaShop#19482]
when a customer with a tax exempt location is registered,
There are several errors, whether or not we have marked show taxes, it should always show the prices of the products without taxes, like the total of the invoice, the total with taxes should not appear in the cart.
Something similar happens with transport taxes, it does not calculate correctly, it adds the products with taxes included plus the shipping costs without taxes and the sum indicates it as total (taxes included),
I have tried the classic theme and the same thing happens,
it is easy to reproduce and it does not matter the options that we mark always gives some error.
I await your news,
Regards,

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.3.1

**Comment by florine2623** [comment]
Hi @jose73wrc ,

You can check for these parameters :
- Create a Tax Rule and choose No Tax
- Create a customer group and display Tax Excluded
- In Carriers, choose No Tax

Check also this issue, as it might be related : https://github.com/PrestaShop/PrestaShop/issues/19110

Please, check and let me know.

**Comment by jose73wrc** [comment]
Hi @florine2623 ,
everything is checked,
I have seen the article and reviewed it,
but I still have the same doubts,
I want to show the articles with taxes and for companies to visualize without taxes.
I could show all the articles with the 2 prices with taxes and without taxes, but calculating the total is something else.
What to create a carrier with taxes and another without taxes?
How do I indicate that if a company is exempt from tax, the articles are displayed and added without taxes?

**Comment by jose73wrc** [comment]
Carrier, products, and customer are all tax exemptions working properly.
If any product, carrier or customer address has taxes, the error appears in the cart.
That an online sales platform fails in the calculations of the cart seems very serious to me.

**Comment by MatShir** [comment]
Hi @jose73wrc, 
Thank you for your feedback and we do take cart calculation seriously.
We need a bit more info, could provide us an example of the steps of what went wrong on the calculation (like when I add this product at 30euro, I have this tax instead of...)?

**Comment by jose73wrc** [comment]
Hi @MatShir ,
I have any product, they all have a default 21% tax, for it to be good it would have to have the same product but without taxes as well.
I add any product to the cart, the client's area is exempt from taxes, because the client will see:
- if the option to see without taxes is checked, exactly the same as if you will pay taxes, both in subtotal and in total.
- If the option to see products with taxes included is checked, you will not see the products without taxes, you will see it normal with taxes included and also the total with taxes included.

If the customer is exempt from taxes, they should see the products and the totals of the cart without taxes, which never happens, the only way that would happen would be:
product with tax exemption + customer with tax exemption for the area + carrier with exempt taxes.

Another thing that I observe is that the carrier should indicate whether or not it carries the included tax.

**Comment by jose73wrc** [comment]
A client registers from the Canary Islands, an area that does not have taxes if you are a company.
because you just have to try to add to the cart a product that you have for trial and that the total comes out without taxes.

**Comment by florine2623** [comment]
You can use a module available on Addons in order to do what you want : https://addons.prestashop.com/en/b2b/7923-billing-ht-without-vat-b2b.html#specifications
With B2B mode on, in a certain country, if a customer is a PRO no tax will be shown, therefore the customer will not be paying the tax.
Thanks

**Comment by jose73wrc** [comment]
@florine2623 
view any product with 21% tax
€ 30 + 21% = € 36.3
product without tax 30 €
product with tax € 36.30

carrier without tax 10 €

A tax exempt customer must see:
€ 30 + shipping € 10 = € 40 (tax excluded)

what we really see:
€ 30 + shipping € 10 = € 40
Total taxes included € 46.30

the problem is in the product that for prestashop to calculate without taxes has to meet 3 points:
1 the product is created tax exemption
2nd the shipment must be configured without taxes
3º the client must be in a group exempt from taxes.

If the client was only in the tax exemption group, it is not possible to view any product on the web, it must be in clients and in clients exempt from taxes.

The customer that is exempt from taxes only visualizes products that are exempt from taxes on the web.

Those responsible for third-party modules tell me that it is a fault of prestashop and not of the modules.

Thanks

**Comment by jose73wrc** [comment]
I have B2B activated
