### ISSUE TITLE
The list of products researched is hidden when adding a product

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19488]
#### Describe the bug

In the tablet view, the list of products researched is hidden when adding a product by the order totals.
![image](https://user-images.githubusercontent.com/43613217/83388085-26663d80-a3ee-11ea-9949-9935a6866cdd.png)

#### Expected behavior

To be displayed on the top of the order totals.
![image](https://user-images.githubusercontent.com/43613217/83388114-2f570f00-a3ee-11ea-8a9a-12e21df6791c.png)

#### Steps to Reproduce

1. Reduce the window size on the order view
2. Add a new product

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #19546
