### ISSUE TITLE
Award images are broken in Module Catalog in the BO

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#19498]
## Describe the bug
Display bug. 
In the BO in module catalog on modules with an "award". The award image is broken.

See screenshot:
![Capture d’écran 2020-06-01 à 11 05 25](https://user-images.githubusercontent.com/25405887/83400369-ff663680-a402-11ea-9037-eec32983f9ca.png)

#### Expected behavior
The award image should not be broken

#### Steps to Reproduce

On PS 1.7.6.5
1. Go to 'Modules > Module catalog'
2. Stay on the "Module Catalog" tab
3. Search for an awarded module > example: "Smartsupp free live chat" (see screenshot)

#### Additional information

* PrestaShop version: PS 1.7.6.5

**Comment by sam-pires** [comment]
Hello @Matt75,
I am not sure, is it related to MBO?

**Comment by Matt75** [comment]
Not related to MBO, image link is `https://medias2.prestastore.com/themes/prestastore/img/front/sprites/badges/awards-customer-satisfaction-up-and-coming.png`
MBO not manage Module Catalog yet, it's Core Module Catalog btw

**Comment by colinegin** [comment]
We need some investigation to know where this comes from.

**Comment by Matt75** [comment]
@colinegin This come from Addons API, image links are into xml retrieved from Addons

**Comment by sam-pires** [comment]
Thanks @Matt75!
I created a Jira ticket for the Platforms team: http://forge.prestashop.com/browse/PLFS-2474 (for PS employees only - related to Addons, not the OS project)

**Comment by colinegin** [comment]
It has been fixed, so it can be tested now !

**Comment by matks** [comment]
I think this is fixed now
<img width="246" alt="Capture d’écran 2020-07-09 à 11 18 25" src="https://user-images.githubusercontent.com/3830050/87021946-194f2200-c1d6-11ea-9a7a-8b594bc6e887.png">
<img width="249" alt="Capture d’écran 2020-07-09 à 11 19 34" src="https://user-images.githubusercontent.com/3830050/87021950-1a804f00-c1d6-11ea-8680-913925f35bbc.png">

Screenshots from PS 1.7.7.0 and PS 1.7.6.7

@PrestaShop/qa-functional would you like to perform more advanced tests or can we mark this issue as fixed ?

**Comment by Robin-Fischer-PS** [comment]
@matks I also checked, it's OK for me so QA :heavy_check_mark:
