### ISSUE TITLE
Multistore - Advanced parameters > Performance - Display only all shops context and add information message

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19492]
This page doesn't have checkboxes in all shops context, no matter the context selected changes are applied for all stores.

We should display in the header only the all shops context
We should add an information message: "Note that this page is available in all shops context only, this is why your context has just switched."

[Specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-3-the-page-can-be-displayed-only-in-all-shops-context)

**Comment by kpodemski** [comment]
Hello @marionf 

Can you please take a look here https://github.com/PrestaShop/PrestaShop/pull/26089 ?
