### ISSUE TITLE
Error Migrating Prestashop

### ISSUE THREAD

**Issue by KwabeaAtakora** [PrestaShop/PrestaShop#19491]
Trying to migrate my Prestashop Application to AWS. Followed all the steps here https://www.prestashop.com/en/blog/how-to-migrate-prestashop-to-a-new-server and i get the error below

Notice: Undefined index: type
--
in 8b032dc79d5e7fed3b4903a6acad53de7ce2ce46_2.module.ttmegamenuviewstemplatesh.php line 83
at content_5ed3fa41531231_96514705(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in Module.php line 2447
at ModuleCore->fetch('module:ttmegamenu/views/templates/hook/ttmegamenu.tpl', 'ttmegamenu\|1\|1\|3\|94')in ttmegamenu.php line 1350
at Ttmegamenu->renderWidget('displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 975
at HookCore::coreRenderWidget(object(Ttmegamenu), 'displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 927
at HookCore::exec('displayNav2', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart)), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayNav2'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayNav2'), object(SmartyDevTemplate)))in b76ea68e0c38ad7654cbdbfe65970b84adaada72_2.file.header.tpl.php line 56
at content_5ed3fa4144acb9_70204616(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('file:_partials/header.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 0, false)in e485a7a7a90874eea4f4c9f61a6207149b884778_2.file.layout-both-columns.tpl.php line 195
at Block_20271053625ed3fa413fa831_81400148->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_20271053625ed3fa413fa831_81400148), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_20271053625ed3fa413fa831_81400148))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_20271053625ed3fa413fa831_81400148', 'header')in e485a7a7a90874eea4f4c9f61a6207149b884778_2.file.layout-both-columns.tpl.php line 62
at content_5ed3fa4140c8c3_09362082(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in 0fc604c03705ab4ee0b76123a4fa890bad672eb7_2.file.layout-full-width.tpl.php line 42
at content_5ed3fa413f2aa7_43715989(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 2377483a33ca02dc70704ca851549fb06d82e4c8_2.file.page.tpl.php line 33
at content_5ed3fa413eb473_28431799(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in 3b0b3dbe8839140c10cef8205f4d185cee6f855c_2.file.index.tpl.php line 33
at content_5ed3fa413e1329_74072406(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('index.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('index.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('index.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

* PrestaShop version: 1.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @KwabeaAtakora ,
You have an issue with module `ttmegamenu`, please contact the developer of the theme/module to correct this issue.
This is not a PrestaShop Core issue.
Thank you for understanding!

**Comment by KwabeaAtakora** [comment]
@florine2623 Thanks. Will do that
