### ISSUE TITLE
Multistore - Advanced parameters > Team > Profiles - Add information message

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19493]
This page is available only in all shops context, other contexts are not displayed in the header.

We should add an information message: "Note that this page is available in all shops context only, this is why your context has just switched."

[Specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-3-the-page-can-be-displayed-only-in-all-shops-context)

**Comment by matthieu-rolland** [comment]
Here are the list of issues I dealt with in a single PR (this issue is one of them)

#19410 #19413 #19414 #19416 #19421 #19422 #19423 #19492 #19494 #19493

I dealt with all these issues in this PR: #24032
