### ISSUE TITLE
Multistore - Shop parameters > Order settings > Statuses > Add new / edit order status - Add information message

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19496]
Currently, this page don’t have shop association block.
In this case, the element is added for all shops, no matter the context selected

To avoid frustration, we should inform the merchants of this behavior:
Display an information message on this page: "Note that this feature is available in all shops context only. It will be added to all your stores."

The All Shops context should be forced.

This is specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-2-add-new-pages-without-shop-association-block)

**Comment by matks** [comment]
Hi @marionf is there UX mock-up for this message ?

If not, maybe you can tell me a basic layout for it, like "just a small text in a block with red border" and I can do something simple that can be improved later ?

**Comment by marionf** [comment]
@matks there is no mock-up as this kind of info is in the UI-kit: https://cdn.rawgit.com/PrestaShop/prestashop-ui-kit/master/index.html#alerts

![capture d'écran_2752](https://user-images.githubusercontent.com/13449658/89278348-44e2f200-d646-11ea-9a68-225ec563d8e7.png)

**Comment by matks** [comment]
All right, thanks !
Here is how it looks:
![Capture d’écran 2020-08-04 à 12 01 01](https://user-images.githubusercontent.com/3830050/89281323-34cd1180-d64a-11ea-8048-550ba1df5a04.png)

**Comment by marionf** [comment]
It looks perfect, tkanks :+1:

**Comment by matks** [comment]
@marionf In order to fix this issue, I can add the information message.

But I can select any shop context (single shop, group of shop, all shops) in this Back Office page, using the Multistore header.

Should I also _force_ the All Shops context?

**Comment by marionf** [comment]
@matks Yes, all shops context should be forced and the user not be able to select another context through the context selector

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/24180
