### ISSUE TITLE
Wrong price displayed before adding a product on a order

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19490]
### Describe the bug

When I add the same product in the order that was previously discounted, the price of the product on the add interface displays the new price, but when it is added, it displays the old price. 

![image](https://user-images.githubusercontent.com/43613217/83390576-60d1d980-a3f2-11ea-8779-bf5114209aef.png)

**Displays price on the add interface:**
35.9 € tax excl 
43.08 € tax incl

**Price displayed after the add:**
28.72 € tax excl 
34.46 € tax incl

### Expected behavior

When I add the same product in the order that was previously discounted, the price of the product on the add interface and after the add action should remains the same (the discounted one) 
The user can edit the price while adding the product, but in this case, a warning modal will be displayed the previous prices will be updated

Displays price on the add interface:
28.72 € tax excl 
34.46 € tax incl

The price displayed after the add:
28.72 € tax excl 
34.46 € tax incl

#### Steps to Reproduce

1. Product A at 20 Euro
2. Add the product to an order
3. edit the price to 10 Euro
4. Add the same product again 

price display add interface =/= price edited in the order

See the add interface and the product price before and after

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by colinegin** [comment]
Calculation is correct, the display is correct after you save the product.
The display is incorrect in the form.

**Comment by colinegin** [comment]
Hello,

what's the status of this issue ?

**Comment by colinegin** [comment]
Specs to be done today by @MatShir

**Comment by MatShir** [comment]
This issue should be fixed by https://github.com/PrestaShop/PrestaShop/issues/20010.
To be reproduced

**Comment by marionf** [comment]
I removed this issue of the kanban to keep only the EPIC: https://github.com/PrestaShop/PrestaShop/issues/20161 as the same PR fixes all the issues, this way we keep a better readability of the kanban
