### ISSUE TITLE
Theme not selectionable 

### ISSUE THREAD

**Issue by niccolobusato** [PrestaShop/PrestaShop#19504]
#### Describe the bug
Can't select .zip of a theme from fronted. input select is not clickable!

#### Expected behavior

Open the input select and select the zip file

#### Steps to Reproduce

1. Go to 'Design'
2. Click on 'Theme & Logo'
3. Scroll down to 'mport from FTP '

**Screenshots**

<img width="1005" alt="Schermata 2020-06-01 alle 16 54 42" src="https://user-images.githubusercontent.com/44100360/83421734-d8226000-a428-11ea-99e4-66d2c3f2d8fc.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.4.1

**Comment by florine2623** [comment]
Please downgrade to 7.2.
PrestaShop is only compatible with 7.2 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
