### ISSUE TITLE
1.7.6.4 - Charts not displayed

### ISSUE THREAD

**Issue by anthhh** [PrestaShop/PrestaShop#19509]
Dear Users!

Im using Prestashop 1.7.6.4 with php 7.2.27

The charts of product sale in back office are not displayed (check the attached screenshot)

Changing the php to 5.6 solves the isssue but i have to run on 7.2 as the other modules requires that.

There are no errors in the server log, however there are some in the console (attaching screenshot)

Any clues?

![charts](https://user-images.githubusercontent.com/66274776/83445065-9a373300-a44c-11ea-8c0d-011a71c16b0b.png)

Best regards

**Comment by florine2623** [comment]
Hi @anthhh ,

I don't have the same info on my shop PS 1.7.6.5 with PHP 7.2 of 5.6:
![Capture d’écran 2020-06-02 à 16 48 08](https://user-images.githubusercontent.com/16019289/83534269-ed62c180-a4f0-11ea-8c6c-619fb6062856.png)
Are you using any external module for statistics ?

Thanks!

**Comment by anthhh** [comment]
Hi @florine2623 
Look for NVD3 module in your prestashop. This is a default addon

**Comment by MatShir** [comment]
Hi @florine2623, could you try on 5.6 with some orders in payment accepted? thank you

**Comment by florine2623** [comment]
@anthhh yes I'm using NDV3 Charts v2.0.1, I still can't display the charts

@MatShir I tried with PHP 5.6, and have orders paid in my shop, still no chart.

**Comment by prestascott** [comment]
Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
