### ISSUE TITLE
Export in CSV the whole list instead of the current page on the BO list page

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#19527]
Export into csv from the BO list is allways **limited**.  

#### Describe the solution you'd like

I would expect all records from Listing are exported ( without any _pagination limit).

AdminController "processExport function"  calls getList function with parameter $limit=false
(default value of parameter $limit = null)

in AdminController "getList function"  is the $limit allways set ( mainly by _pagination/default_pagination value)

**solution:**
in AdminController "getList function":
 to set the value of  $shouldLimitSqlResults sooner and the variable $limit to set  based on $shouldLimitSqlResults  value
```
        $shouldLimitSqlResults = $this->shouldLimitSqlResults($limit);
        if ($shouldLimitSqlResults) {
            $limit = $this->checkSqlLimit($limit);
        }
```

**Comment by florine2623** [comment]
Hi @Eva-F ,
I will ping our dev team to get their point of view.
Please stay tuned !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
What do you think about that ?

**Comment by MatShir** [comment]
@PrestaShop/prestashop-product-team Do you think we should enhance the export system in the listing page ?

**Comment by LouiseBonnard** [comment]
Yep, I think it'd be great, thanks! Can you let us know which version of PrestaShop you use, @Eva-F? On a 1.7.6.5 version, I can manage to export the whole listing of my products, and not only the 20 items displayed on the page.

**Comment by Eva-F** [comment]
version 1.7.6.3
for now I am using override
**override/classes/controller/AdminController.php**
```
  class AdminController extends AdminControllerCore
{
    protected function checkSqlLimit($limit)
    {
        if ($limit === false) {
            return $limit;
        }
        return parent::checkSqlLimit($limit);
    }
}
```

**Comment by matks** [comment]
> Export into csv from the BO list is allways **limited**.
> 
> #### Describe the solution you'd like
> I would expect all records from Listing are exported ( without any _pagination limit).
> 
> AdminController "processExport function" calls getList function with parameter $limit=false
> (default value of parameter $limit = null)
> 
> in AdminController "getList function" is the $limit allways set ( mainly by _pagination/default_pagination value)
> 
> **solution:**
> in AdminController "getList function":
> to set the value of $shouldLimitSqlResults sooner and the variable $limit to set based on $shouldLimitSqlResults value
> 
> ```
>         $shouldLimitSqlResults = $this->shouldLimitSqlResults($limit);
>         if ($shouldLimitSqlResults) {
>             $limit = $this->checkSqlLimit($limit);
>         }
> ```

Please consider 2 things:
- some people want to export the paginated list, some want the full list
- exporting the full list might crash some servers/browsers (for example if it's too much data for memory)

I think the right way to export the full list is in the Export page 🤔 isn't it ?

**Comment by MatShir** [comment]
Why not it would be a useful page that could be combined with the import page?
How exporting from another page (Export page) changes the performance rather than export on the related pages?

**Comment by LouiseBonnard** [comment]
I succeed in getting the whole list directly from a specific page, see screenshot below:

<img width="1356" alt="Capture d’écran 2020-06-04 à 14 45 36" src="https://user-images.githubusercontent.com/32565890/83758275-18285380-a672-11ea-9014-f06bc7d4163c.png">

Perhaps we should just add a modal when the user clicks on the icon to export to make him/her decide whether he/she wants to export the whole list or only the items paginated? Or simply turn it as a parameter in the Configure section of the back office?

**Comment by sam-pires** [comment]
Hi @prestascott 
I think you did some research about listing export while working on tables, am I right?

**Comment by marsaldev** [comment]
@LouiseBonnard Or something like this?
![Schermata 2020-06-04 alle 15 10 03](https://user-images.githubusercontent.com/48283112/83760772-b538bb80-a675-11ea-9974-fffa90d23e27.png)

**Comment by LouiseBonnard** [comment]
@marsaldev, why not! As long as we allow the user to choose between the two options. ;-)

**Comment by Eva-F** [comment]
> Please consider 2 things:
> 
>     * some people want to export the paginated list, some want the full list
> 
>     * exporting the full list might crash some servers/browsers (for example if it's too much data for memory)
> 
> 
> I think the right way to export the full list is in the Export page 🤔 isn't it ?

to be true - export only one page doesn't make for me too sense - but i can be wrong .
But I am understand your fears about memory crash - maybe also time limit could be a problem -
therefore some upper limit is neccessary to set - imho . ( into getList?? or into processExport?? ).

BTW what happens when I write Sql query into "Advanced Parameter->Database" 
```
select * from ps_product limit 0,10000000
 ```
and try to export?


- I agree with LouiseBonard (two items in menu - "Export all" and "Export"), where Export all will be limited by some upper limit value.

- it would be fine if AdminController "processExport function" has the $limit as parameter
(something like:)
```
 public function processExport($text_delimiter = '"', $limit=null)
    {
        // clean buffer
        if (ob_get_level() && ob_get_length() > 0) {
            ob_clean();
        }
// origin-  $this->getList($this->context->language->id, null, null, 0, false);
// $limit=null means the $limit is set to _pagination 
        $this->getList($this->context->language->id, null, null, 0, $limit);
        if (!count($this->_list)) {
            return;
        }

```

**Comment by prestascott** [comment]
Hi everyone, 

Thank you @Eva-F for your report.

In my interviews I found out that merchants wanted to choose which columns they wanted to export. 
Here are some quotes from them:
- _"We never export what we want"_ 
- _"An interface or a step before export to select columns we want to export"_

This is the reason why I request to show a modal after clicking on 'Export' which allows users to choose what they want to export. In fact, it's clear to me that if users click on this button, they expect to export all of the list and not only the first page. 

This is my design proposition (please don't mind the drag and drop feature):
![image](https://user-images.githubusercontent.com/54888056/90406274-37495580-e0a5-11ea-9297-2580ced698f6.png)

Wdyt?

**Comment by LouiseBonnard** [comment]
As discussed with @prestascott, let's keep the two options proposition in the settings panel, cf. the screenshot below:

![Capture d’écran 2020-08-27 à 18 17 32](https://user-images.githubusercontent.com/32565890/91468096-c74f8200-e891-11ea-9584-cc973f77e6e0.png)

1. Export this page = export only the items displayed on the page
2. Export all pages = export all the items the listing contains

Note that the wording might be improved, here are other possibilities: Export/Export all, Export this page/Export all items, etc.

---

In addition to the pagination optimization, another good improvement is, following Scott's mockups above, to give the possibility to the user to select which column(s) he/she wants to export. So **reunite in a single pop up window the ability to select the number of items as well as the columns to export**.

@PrestaShop/prestashop-core-developers, could this be done in the meantime as a broad improvement of the export feature?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers friendly reminder :wink: 
I think we have the Product Team approval and we need yours.

> @PrestaShop/prestashop-core-developers, could this be done in the meantime as a broad improvement of the export feature?

**Comment by matks** [comment]
Hi, sorry for late answer

> Export this page = export only the items displayed on the page

Can be done, just needs to be given a priority and assigned to a kanban. It's already what is implemented if I understand.

> Export all pages = export all the items the listing contains

Can be done, just needs to be given a priority and assigned to a kanban. Needs to be done carefully but nothing scary.

> give the possibility to the user to select which column(s) he/she wants to export

Can be done, needs to be given a priority and assigned to a kanban. Can be tricky depending on the lists because the data in the column can come from very different places. On some lists in the Back Office it might not be possible (depends on the data).

**Comment by tammynewbie** [comment]
How
