### ISSUE TITLE
Useless code: $cart_rules & $available_cart_rules declared but unused

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#19531]
Are these code lines useless? These variables are not referenced anywhere. I have commented out and couldn't see any missfunction.

https://github.com/PrestaShop/PrestaShop/blob/22978dd19a69b3a8f6f128b29826819c33b3da3c/controllers/front/CartController.php#L492-L502

**Comment by florine2623** [comment]
Hi @idnovate ,
I will ping our dev team to get their point of view.
Please stay tuned!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
Could you check this please ?
Thanks!

**Comment by PierreRambaud** [comment]
> available_cart_rules

I confirm the code is useless, feel free to create a pull request and we will merge it really fast :)

**Comment by idnovate** [comment]
And what about `$cart_rules`?

**Comment by matks** [comment]
> And what about `$cart_rules`?

Same 😄 nice catch !
