### ISSUE TITLE
Cannot access the gamification configuration page after disabling it

### ISSUE THREAD

**Issue by bpato** [PrestaShop/PrestaShop#19548]
Edit:
#### Describe the bug

when gamification module is not active tries to redirect to AdminHome Controller and fails.

![Captura](https://user-images.githubusercontent.com/28157986/83656812-51a08680-a5c0-11ea-80c6-a7e89ad4386a.PNG)

https://github.com/PrestaShop/gamification/blob/master/controllers/admin/AdminGamificationController.php#L13L22

#### Steps to reproduce 
it tries to redirect to ?controller=AdminHome

1: go to module manager and open the configuration page in a new window
2: disable de module
3: reload the configuration page
#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: N/A

**Comment by MatShir** [comment]
Hi @bpato,
Could you please provide us with more info? What kind of errors do you encounter when it fails?
We need more details on the issue to help us the prioritization 

Thank you!

**Comment by bpato** [comment]
![Captura](https://user-images.githubusercontent.com/28157986/83656812-51a08680-a5c0-11ea-80c6-a7e89ad4386a.PNG)

it tries to redirect to ?controller=AdminHome

1: go to module manager and open the configuration page in a new window
2: disable de module
3: reload the configuration page

**Comment by MatShir** [comment]
I was able to reproduce the issue with PrestaShop version 1.7.7.
I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thank you!

**Comment by colinegin** [comment]
IMO, this is normal that you don't have access to the configuration page once you disable the module.
The only thing that could be improved is the "page not found" message. But this is not a bug.

Or maybe there's something i misunderstood ?
What do you think @MatShir ?

**Comment by Matt75** [comment]
@colinegin Yes AdminHome doesn't exist, it should be AdminDashboard instead 👌

**Comment by MatShir** [comment]
Other modules link banner, for example, allow to configure it even when it is not activated. So this module, in particular, I understand there is not configuration to do when it is disabled. 
IMO, Page not found is not very professional when other modules allow to do it. It could be expected from the merchant to try to click on _Configure_. So I might be more improvement issue with for ex a page that explains the module principal. Wdyt ? @colinegin 
@Matt75 if you change it to AdminDashboard will it redirect to the dashboard page ?

**Comment by Matt75** [comment]
Yes it should redirect on AdminDashboard 

AdminHome is replaced by AdminDashboard since PrestaShop 1.6.0.1
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.6.0.1.sql#L35

**Comment by colinegin** [comment]
Oh ok I get it now :)

**Comment by MatShir** [comment]
If we redirect to the AdminDashboard, it could be frustrating if the merchant want to manage his modules. AdminDashbord is just the default redirection in PS.

**Comment by Matt75** [comment]
@MatShir Related to https://github.com/PrestaShop/PrestaShop/pull/19448
If a merchant request a disabled module configuration page or a ModuleAdminController of a disabled/uninstalled module, he should see an explicit error.

**Comment by Progi1984** [comment]
@bpato  Sorry the module `gamification` is now managed by the `PrestaShopCorp` organization. Could you create a new issue on their issues board : https://github.com/PrestaShopCorp/gamification/issues/new ? Thank you for your help.
