### ISSUE TITLE
CustomMoneyType and ResizableTextType looks unused and throw an error when used

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19544]
#### Describe the bug

When we try to use CustomMoneyType or ResizableTextType, we have an error : 

Could not load type "PrestaShopBundle\Form\Admin\Type\CustomMoneyType": class does not implement "Symfony\Component\Form\FormTypeInterface".

#### Expected behavior

This Form Type sould probably be removed because I don't find 

<pre>
./src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:32:class CustomMoneyType extends AbstractTypeExtension
./src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml:6:        class: 'PrestaShopBundle\Form\Admin\Type\CustomMoneyType'
</pre>

Please note: Service _form.type.extension.money_ is not used too.

Edit: same bug with ResizableTextType

#### Steps to Reproduce
>Edited by Khouloud

1. Enable debug mode
1. Install PS 1.7.7 and install this module 
[checkboform_with_buggy_types.zip](https://github.com/PrestaShop/PrestaShop/files/8451434/checkboform_with_buggy_types.zip)
2. Click on configure
3. See error

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform) 

2. Uncomment CustomMoneyType on file Checkboform\Form\Type\SettingsType::buildForm

See the error 
![image](https://user-images.githubusercontent.com/52157233/83647773-907d0f00-a5b5-11ea-8961-62c7a8f29be7.png)

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7
* PHP version: N/A

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers Wdyt ?

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers Wdyt ?

**Comment by sLorenzini** [comment]
hello @202-ecommerce, tested on 1.7.7.8 version and no error appears. 
On 1.7.8.X can't install the module.

Other steps or details to test?

thanks

**Comment by clotairer** [comment]
Hi,

Bug still remain on PrestaShop 8. You probably not uncomment line on the module file.
I preprared for you a zip for PrestaShop 8 and types uncommented

[checkboform_with_buggy_types.zip](https://github.com/PrestaShop/PrestaShop/files/8428473/checkboform_with_buggy_types.zip)
.

**Comment by clotairer** [comment]
I worked on this issue. Removing is not a good way. I found ResizableTextType is used on Profil Grid in the head of the table.

I look for a solution to let ResizableTextType an CustomMoneyType reusable on a module context.

**Comment by khouloudbelguith** [comment]
Hi @202-ecommerce, @clotairer,

I manage to reproduce the issue with PS1778 & PS1785.
![image](https://user-images.githubusercontent.com/16067358/162428293-9eec2b44-b5bc-4c9c-81f9-9f71d74e4d26.png)
so I can confirm that this behavior is indeed a bug.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by 202-ecommerce** [comment]
I closed this issue and the PR associated. I've no time to work on this to propose a better way to reuse CustomManeyType and ResizableTextType.
It probably a bad uses of these object instead of real bug.
Don't waste time with this.
