### ISSUE TITLE
Form Type help and popover tooltip not display properly

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19540]
#### Describe the bug

If you want to create a Form type with a tooltip or help. It can't be display simulaneous. You need to split the form_row

#### Expected behavior

If you declare a 
```php
$builder
	->add('CHECKBOFORM_YESANDNO', YesAndNoChoiceType::class, [
		'label' => 'Yes and No',
		'help' => 'Help me I\'m famous !',
		'label_attr' => [
			'popover' => 'Tooltip me I\'m famous !',
		],
	]);
```
It should display : 
![image](https://user-images.githubusercontent.com/4932192/83625717-b1813800-a594-11ea-9040-c7b1cd2cb743.png)

#### Steps to Reproduce

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform)

2. If you define in your twig template, _popover tooltip_ will not be displayed

```twig
{% block form_rest %}
	{{ form_rest(settings) }}
{% endblock %}
```
![image](https://user-images.githubusercontent.com/4932192/83626053-34a28e00-a595-11ea-8dc4-27f064b05d84.png)

3. If you define a specific form_row in your twig template, _help_ will not be displayed

```twig
{{ form_row(settings.CHECKBOFORM_YESANDNO) }}
{% block form_rest %}
	{{ form_rest(settings) }}
{% endblock %}
```
![image](https://user-images.githubusercontent.com/4932192/83626256-73d0df00-a595-11ea-9c18-4c983aabb058.png)

#### Additional information

* PrestaShop version: 1.7.7+
* PHP version: N/A

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers could confirm this behaviors?
First time, I occur a bug like this.
@202-ecommerce Have you find this issue in 1.7.6 ?

**Comment by clotairer** [comment]
I confirm it doesn't work on 1.7.6. Same bug.

Defaut behaviour of form_row has a default alignment not coherent with form_rest :
{{ form_row(settings.CHECKBOFORM_YESANDNO) }}

![image](https://user-images.githubusercontent.com/52157233/83645275-93c2cb80-a5b2-11ea-9295-07cc8d779caa.png)

**Comment by florine2623** [comment]
Hi @clotaire202 ,
Sorry for the belated answer, I downloaded your module and installed it in PS 1.7.7.0, it seems like you've changed it :
![Capture d’écran 2020-06-26 à 16 44 28](https://user-images.githubusercontent.com/16019289/85869698-570e7c80-b7cc-11ea-83e2-77b5b80265d4.png)
Do you still face the issue ?

**Comment by 202-ecommerce** [comment]
@florine2623

The tooltip is displayed but the help text under the fiels not. So the bug still remain.
