### ISSUE TITLE
Implement Native Lazy Loading

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#19549]
#### Is your feature request related to a problem?

The idea is a small optimization which allows to improve loading time.

#### Describe the solution you'd like

Add `loading=lazy` on `img` tags.

#### Additional context

Reference : https://web.dev/native-lazy-loading/
Reference : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility

**Comment by eternoendless** [comment]
To be implemented in the classic theme & maybe faceted search as well?

**Comment by rdy4ever** [comment]
This will be great in the future, but for now I think I'm gonna stick with the [lazysizes](https://github.com/aFarkas/lazysizes) I've been using for years. At 7.59 kb it's a bargain for me and it always worked like a charm.

**Comment by Progi1984** [comment]
@colinegin https://caniuse.com/#feat=loading-lazy-attr : 67% of all users. 
@matks Thanks for the link

Advantage : if the browser doesn't support it, the image is loaded as usual ;)
