### ISSUE TITLE
Cannot change activation state on many requested products

### ISSUE THREAD

**Issue by BudrysLP** [PrestaShop/PrestaShop#19541]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

When I try to activate some products I get that error "Cannot change activation state on many requested products". When I try t edit the same products I can't do that and also get error.

#### Steps to Reproduce

1. Go to products
2. Click on activate
3. Go to product
4. Try to save

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1.3.3

**Comment by MatShir** [comment]
Hi @BudrysLP,
I try:
1. Go to the product lists
2. Go to offline/deactivated product
3. Activate the product
4. Save the product
No errors detected.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots/videos
 
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by BudrysLP** [comment]
You could not have that issue. What is weired I have it only for some products, not for all.

**Comment by florine2623** [comment]
Hi @BudrysLP ,
Did you do an upgrade of your shop ?
Is there anything special about the products that an't be saved ? 
When debug mode is on, do you have an error ?
Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Comment by popkutt** [comment]
In my case it was a forbidden character * in product link_rewrite, table ps_product_lang, imported directly to MySQL.
