### ISSUE TITLE
Button Add to cart doesn't work

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19554]
Hello,
I use a product with attributes "Book 1" and "Book 2" but the button "Add to cart" doesn't work. If I press it nothing happens.
If I change a quantity to e.g. 3 and then I press the button, the quantity is changed to 1 and again nothing happens. It means no product is added to the cart and no new screen displays. I also switched on the debug mode but no log file was generated.

Product detail
![image](https://user-images.githubusercontent.com/33311857/83725283-f7e0a080-a641-11ea-92c1-6197cc44eddb.png)

Configuration
![image](https://user-images.githubusercontent.com/33311857/83725321-0929ad00-a642-11ea-8c0c-2bbba149d229.png)

**Comment by florine2623** [comment]
Hi @juraj1000 ,
Could you share the exact steps to reproduce your issue please ?
Thanks!

**Comment by juraj1000** [comment]
Exact steps:
- Home page Popular products 
- Select product > there is displayed product detail info
- press button Add to cart > nothing happens and the cart is empty
This issue is only with one product which uses combination, the product is activated.

**Comment by florine2623** [comment]
I can't reproduce the issue.
You forgot to mention that this product is a PACK.
Can you give me more details about the 2 products in the pack ?

**Comment by juraj1000** [comment]
The product is not pack, it has only the text description about packs of 2 books, the product is "Product with combinations"

**Comment by florine2623** [comment]
I can't reproduce your issue.
Have you checked your shopping_cart module and enable ajax cart ?

**Comment by juraj1000** [comment]
Ajax cart is enabled, how can I check shopping_cart module?

**Comment by florine2623** [comment]
Can you check in the product page if you have any special configuration ? For example, allow only a certain amount of products to the cart.

**Comment by juraj1000** [comment]
I'm sending configuration of the product. There is only special configuration for attributes, there are used attributes "Book 1" and "Book 2". Both attributes have 3 values, so the system generated 9 combinations. But 6 combinations were deleted because only 3 combinations are relevant.

![image](https://user-images.githubusercontent.com/33311857/83803301-9efa2200-a6ac-11ea-9983-d4567324f00a.png)

![image](https://user-images.githubusercontent.com/33311857/83803320-a6b9c680-a6ac-11ea-94d6-6ebd7e7ebd38.png)

![image](https://user-images.githubusercontent.com/33311857/83803701-4f682600-a6ad-11ea-8ea6-614594645dc4.png)

![image](https://user-images.githubusercontent.com/33311857/83803711-52631680-a6ad-11ea-81e2-746a1f9035e5.png)

![image](https://user-images.githubusercontent.com/33311857/83803720-55f69d80-a6ad-11ea-8ba8-119c729b4b07.png)

![image](https://user-images.githubusercontent.com/33311857/83803738-58f18e00-a6ad-11ea-9799-74699512f6d7.png)

**Comment by florine2623** [comment]
I used a product with combination and a specific price like yours. Still can't be reproduce.

Is that the only product that can't be added to your cart or all products ?

**Comment by juraj1000** [comment]
Yes, it is relevant only for one product

**Comment by florine2623** [comment]
Try to duplicate that product and add the duplicated product to the cart.

**Comment by juraj1000** [comment]
I found out how reproduce the error:
- create mandatory customization field "Pack" in Customization for the product
![image](https://user-images.githubusercontent.com/33311857/84010989-bddf0980-a975-11ea-86c0-2b31e3fa71a0.png)
- then delete this customization field from the product
=> and now it is not possible to add this product to the cart, it seems there is still check for mandatory field "Pack" but this field is not visible on the screen because it was deleted

I found also a second issue if there is used mandatory field "Pack":
- select this product with a quick view as a business user in the shop
- press button Add to cart
=> nothing happens and mandatory customization field "Pack" is not visible on the screen

**Comment by florine2623** [comment]
I can't reproduce your issue. Please check my screen record : https://drive.google.com/file/d/12rJW8N7A7XpBualXJt5-M2YZmuviPaoq/view

**Comment by juraj1000** [comment]
Could you please try to reproduce it again:
- use product with combinations (see above)
- don't use stocks

**Comment by florine2623** [comment]
I can't reproduce your issue. You can check my screen record here : https://drive.google.com/file/d/1p_rAQ6U271OoKIn8RWTvnMQhKOV4yBf-/view

If that is the only product that you can't add to cart, try to duplicate that product and add the duplicated product to the cart.

**Comment by juraj1000** [comment]
I duplicated the product and there is exactly the same issue, it is not possible to add it to the cart

**Comment by florine2623** [comment]
So the issue comes with that product. I don't know what are the characteristics of that product. So I can't help you. I you need some supervised help, you can contact the support here : https://addons.prestashop.com/en/388-support

I'll close the issue as it is not an PrestaShop core bug but most likely a customization problem.
