### ISSUE TITLE
Form Type error are not managed on each fields

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19555]
#### Describe the bug

When you use default PrestaShop\PrestaShop\Core\Form\FormHandler it's impossible to manager form type errors.

![image](https://user-images.githubusercontent.com/4932192/83726575-02039e80-a644-11ea-805d-66369a36e1e1.png)

You can just send an error the top of the page.

![image](https://user-images.githubusercontent.com/4932192/83727141-e77df500-a644-11ea-9612-1093187f1c39.png)

Please note PrestaShop use HTML5 validation and don't validate all field properly. For instance, number type are just casted, mandatory select has no "empty option"... That's why this feature is not useful on default PrestaShop forms.

#### Expected behavior

Have the possibility to display form error.

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @202-ecommerce ,
Please stay tuned as I ping our dev team !
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
What do you think about that ?
Thanks!

**Comment by PierreRambaud** [comment]
Hey @matks @zuk3975 it's up to you :wink:

**Comment by kpodemski** [comment]
Hello @202-ecommerce 

Is this still relevant for PrestaShop 8? 🤔

**Comment by hibatallahAouadni** [comment]
Hello @202-ecommerce 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
