### ISSUE TITLE
Do not mention tax in invoice labels when tax is disabled

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19558]
Hello,
I use configuration for Tax options "Enable tax" = No

![image](https://user-images.githubusercontent.com/33311857/83729510-0336ca80-a648-11ea-8b94-438a9b77d472.png)

But there are incorrect texts in an invoice if this configuration is used.  
I expect: 
- not to display "Tax rate" in the header for items
- to use the texts "Base Price", "Unit Price" and "Total" without "(Tax excl.)"  in the header for items
- not to display summary line "Total (Tax excl.)" 
![image](https://user-images.githubusercontent.com/33311857/83730385-47769a80-a649-11ea-8c7a-fb8a2a388e6c.png)

Configuration
![image](https://user-images.githubusercontent.com/33311857/83730164-f8c90080-a648-11ea-81f0-8f994d9686af.png)

**Comment by florine2623** [comment]
Hi @juraj1000 ,
Thanks for your request.
This is an improvement you'd like to see, I don't think it is "incorrect".
I will ping our product team to know what they have to say on that topic !
Please stay tuned.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team and @LouiseBonnard ,
Could you take a look at this request ?
Thanks!

**Comment by LouiseBonnard** [comment]
Hi @juraj1000, by default it is mentioned in the invoice labels although the field is empty. I am wondering how helpful it can be to the users, it is just part of the invoice template: values are empty and labels are mentioned tax excluded... 

Perhaps we should let people vote for it in order to estimate how required it is, the PrestaShop feedback tool should be available soon. We keep in touch! :-)

**Comment by Hlavtox** [comment]
@LouiseBonnard This is not "Vote for it", this is a legal requirement not to display anything about VAT anywhere, if you are not VAT payer.

- No tax rate
- No tax incl./tax excl.
- No VAT number in your information in the invoice header.
- (optional) A statement that you are not a VAT payer.

**Comment by LouiseBonnard** [comment]
Okay @Hlavtox, thanks for this information. In which case(s) would a merchant disable tax on his/her store? We'd be interested in studying some examples!

**Comment by Hlavtox** [comment]
@LouiseBonnard At least in Czech republic, it goes like this:

1. You register yourself either as a physical person doing business or you create some kind of company, like private limited (SARL in France). You get assigned an ID number and you can go do business.
2. You **can have** assigned VAT number from the financial bureau, but it's **only for communication purposes**. You are **not VAT liable person** at this stage (you don't add VAT to your products).
3. It's **forbidden to state VAT number anywhere**, to show anything about tax everywhere. You would confuse the other side of the business by this.

____

4. You can switch to VAT payer on your own will OR if your revenue in last 12 months becames greater than 1 million CZK (37k EUR approximately). 
5. Then you need to state your VAT number and state if prices shown are with or without VAT.

This rules goes for information in the store, on invoices, offers, delivery lists etc.

**Comment by LouiseBonnard** [comment]
Dear @Hlavtox, thank you very much for this precious information! I've studied your answers and checked with the legal team this week and, you're right about that: if the merchant is exempt from VAT, it should not be mentioned in the invoice. So the invoice template should be adapted according to the option selected with the switch button to enable/disable tax.

Read (🇫🇷) more [here](https://cabinet-antoine.fr/factures-les-mentions-obligatoires?debut_comments=10).

**Comment by Progi1984** [comment]
@LouiseBonnard Ok with these files ?
**Before :**
[FA000004-1.pdf](https://github.com/PrestaShop/PrestaShop/files/5277479/FA000004-1.pdf)

**After :**
[FA000004-6.pdf](https://github.com/PrestaShop/PrestaShop/files/5277477/FA000004-6.pdf)

**Comment by Progi1984** [comment]
And the PR #21153
