### ISSUE TITLE
BO Virtual product: Download the file will get the first one instead the last (active)

### ISSUE THREAD

**Issue by MLE-Coding** [PrestaShop/PrestaShop#19553]
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The bug is at the backoffice products detail page at virtual products. You edit a virtual product and add a new download file to this product, you are able to download this file (see screenshot) ![image](https://user-images.githubusercontent.com/63242596/81045831-5259d600-8eb7-11ea-859a-3b8b24f6da80.png)<br>but if there are more than one file downloads available for this product. this download link will only get the first file and not the active one.
| Category?     | BO
| How to test?  |  - Add a virtual product (0€)<br>- Add a File download to this product<br>- The first file is downloadable on the frontoffice<br>- Add another file download to this product to replace the first one<br>- Disable the first<br>- Try to download the file with the link. you will get the first download file and not the last (active) download.

**Comment by SD1982** [comment]
Hi @MLE-Coding I have tried to reproduce the issue you describe here but I have not been able to reproduce.
https://drive.google.com/file/d/1BOEbYXFYgagmLMxHLSXvlR-AowpNXecP/view?usp=sharing
