### ISSUE TITLE
Currency symbol

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19559]
Hello,
I use only currency EUR in my e-shop, but there is displayed symbol € and I need to display ISO code EUR in screens and also in emails, pdf.... How can I change € to EUR? I couldn't find any configuration for it.

Configuration
![image](https://user-images.githubusercontent.com/33311857/83733136-6bd47600-a64d-11ea-8c56-91dd45d5c974.png)

**Comment by florine2623** [comment]
Hi @juraj1000 ,

In PS 1.7.6.5, you can't change that manually. You will need t change it in your database in `ps_currency_lang`.
In PS 1.7.7.1, you will be able to change currency format and symbol :
![Capture d’écran 2020-06-04 à 12 02 07](https://user-images.githubusercontent.com/16019289/83743633-477f9600-a65b-11ea-8bd0-959e749d2a75.png)
You can test that feature in the beta version by downloading PS 1.7.7.0 beta.

Thanks!

**Comment by juraj1000** [comment]
Hello,
thanks for hint about currency symbol in PS 1.7.6.5. Is it also possible to configure format with currency in PS 1.7.6.5?
