### ISSUE TITLE
Date and DateRange picker Type with time

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19550]
#### Is your feature request related to a problem?

helper forms supply date time picker. You can found it on Cart Rules.

![image](https://user-images.githubusercontent.com/4932192/83669276-941e8f00-a5d1-11ea-9e00-97dc3947dd69.png)

#### Describe the solution you'd like

With DatePickerType or DateRangeType we cannot pick a time :

![image](https://user-images.githubusercontent.com/4932192/83669361-bdd7b600-a5d1-11ea-955c-737836a8f4d6.png)

**Comment by florine2623** [comment]
Hi @202-ecommerce ,
Thanks for the recommandation. I will ping our product team, please stay tuned !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,
What do you think about this ?
Thanks!

**Comment by colinegin** [comment]
ping @florine2623 if i understand correctly, this issue is a duplicate of the following one : https://github.com/PrestaShop/PrestaShop/issues/11329
Do you confirm ?

**Comment by prestascott** [comment]
Hi @202-ecommerce,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #11329. To be informed when it's fixed, please subscribe to the issue mentioned above.

I close the ticket.

Thank you!

**Comment by prestascott** [comment]
Duplicate of #11329

**Comment by 202-ecommerce** [comment]
Thank you.
I updated #19537 and replaced by #11329
