### ISSUE TITLE
Does not save changes, but show updated message

### ISSUE THREAD

**Issue by Muzz-as** [PrestaShop/PrestaShop#19563]
#### Describe the bug

Does not save eny changes on pruduct page but show updated message. Only in product. CMS or Catalog page - is OK. Only in FireFox and Google Chrom. Opera working fine.
Debug mode report without errors. What's the problem?

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2
* FireFox Version 77.0.1
* Theme: Classic (standart)

**Comment by florine2623** [comment]
Hi @Muzz-as ,
I can't reproduce your issue.
Can you try to deactivate the overrides ?
Check you log file to see if there are any fatal errors ?
Thanks!

**Comment by Muzz-as** [comment]
Deactivate the overrides allready. No error message in server-log.
I Have only one Error in "Symfony Profiler": Matched route"admin_get_form_images_combination".
and json-File at: ...../index.php/sell/catalog/products/attributes/form-images/.....is Empty

**Comment by Muzz-as** [comment]
> Hi @Muzz-as ,
> I can't reproduce your issue.
> Can you try to deactivate the overrides ?
> Check you log file to see if there are any fatal errors ?
> Thanks!

 Only combination added products, only FireFox and Chrome. Opera is fine.

**Comment by florine2623** [comment]
When you enable debug mode, do you have an error ?

**Comment by Muzz-as** [comment]
> When you enable debug mode, do you have an error ?

No error message

**Comment by florine2623** [comment]
When you inspect the element, do you have error in the console ?

**Comment by Muzz-as** [comment]
I found a error. This happens then "Development Mode" on Cloudflare and memcashed is turned on together. That's why I can't save product after update.

**Comment by Muzz-as** [comment]
> When you inspect the element, do you have error in the console ?

I found a error. This happens then "Development Mode" on Cloudflare and memcashed is turned on together. That's why I can't save product after update.

**Comment by PierreRambaud** [comment]
Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Thank you!
