### ISSUE TITLE
Incorrect content of localization pack for country Slovakia

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19561]
Hello,
there is incorrect content of localization pack for country Slovakia (SK). If I import language sk then there are used incorrect date formats "Y-m-d" and "Y-m-d H:i:s".
The correct formats are:
- Date format:   d.m.Y 
- Date format (full):    d.m.Y H:i:s
Could you please change it in the localization pack for Slovakia?

**Comment by florine2623** [comment]
Hi @LouiseBonnard ,
Could you take a look at this ? Can this be implemented ?
Thanks!

**Comment by LouiseBonnard** [comment]
Nice catch, thanks @juraj1000! Of course, it is very easy, you just need to create a pull request to modify this information, located in the [all_language.json](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json) file.
