### ISSUE TITLE
id_group_shop instead of id_shop_group in webservice parameter

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#19566]
#### Describe the bug

There is a typo in the name of id_shop_group parameter for webservice, see official doc: https://devdocs.prestashop.com/1.7/development/webservice/tutorials/advanced-use/manage-multishop/#define-shop-specific-override)

#### Expected behavior

Activate multishop, with 2 groups (eg: "Default" and "Stores"), with at least 1 shop in each group. Activate webservices and create a key with full access (all resources and all shops). Create a product for the second groups's shop. Get products from /api/products?id_shop_group=2 you won't see the product you previously create.

#### Steps to Reproduce

Activate multishop, with 2 groups (eg: "Default" and "Stores"), with at least 1 shop in each group. Activate webservices and create a key with full access (all resources and all shops). Create a product for the second groups's shop. Get products from /api/products?id_shop_group=2 you won't see the product you previously create.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @NeOMakinG & @loicsapone ,
Thanks for the Issue and the PR !

The issue can be reproduce and PS 1.7.6.5 and 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed.
