### ISSUE TITLE
APCU on php 7.2 complete brake backend 

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#19578]
#### Describe the bug

Another time prestashop decide to dead with a standard and common component.

We install on our server apcu and apcu-bc for php 7.2.
We dont do other things on our prestashop.

Some Backend page start to be unavailable with error 500.

Default backend page and order page for example work.

performance page does not work.

Try to uninstall apcu from the server dows not solve the problem:

www[12389]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache". in /var/www/htdocs/www.sixrace.it/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:41#012Stack trace:#012#0 /var/www/htdocs/www.sixrace.it/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(212): Doctrine\Common\Cache\ApcCache->doFetch('DoctrineNamespa...')#012#1 /var/www/htdocs/www.sixrace.it/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(185): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()#012#2 /var/www/htdocs/www.sixrace.it/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(78): Doctrine\Common\Cache\CacheProvider->getNamespacedId('PrestaShopBundl...')#012#3 /var/www/htdocs/www.sixrace.it/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Cache\CacheProvider->fetch('PrestaShopBundl...')#012#4 /var/www/htdocs/www.sixrace.it/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(281): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('PrestaShopBundl...')#012#5 /var/www/htdocs/www.sixrace.it/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php(45): Doctrine\ORM\EntityManager->getClassMetadata('PrestaShopBundl...')#012#6 /var/www/htdocs/www.sixrace.it/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(698): Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory->getRepository(Object(Doctrine\ORM\EntityManager), 'PrestaShopBundl...')#012#7 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/getPrestashop_Core_Admin_AdminFilter_RepositoryService.php(8): Doctrine\ORM\EntityManager->getRepository('PrestaShopBundl...')#012#8 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/appProdProjectContainer.php(1632): require('/var/www/htdocs...')#012#9 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/getPrestashop_Core_Search_Builder_RepositoryService.php(8): ContainerU6lzt6a\appProdProjectContainer->load('getPrestashop_C...')#012#10 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/appProdProjectContainer.php(1632): require('/var/www/htdocs...')#012#11 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/getPrestashop_Core_Search_BuilderService.php(8): ContainerU6lzt6a\appProdProjectContainer->load('getPrestashop_C...')#012#12 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/appProdProjectContainer.php(1632): require('/var/www/htdocs...')#012#13 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/getPrestashop_FiltersBuilder_ResolverService.php(8): ContainerU6lzt6a\appProdProjectContainer->load('getPrestashop_C...')#012#14 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/appProdProjectContainer.php(1632): require('/var/www/htdocs...')#012#15 /var/www/htdocs/www.sixrace.it/var/cache/prod/ContainerU6lzt6a/appProdProjectContainer.php(1966): ContainerU6lzt6a\appProdProjectContainer->load('getPrestashop_F...')#012#16 /var/www/htdocs/ww in /var/www/htdocs/www.sixrace.it/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 41

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @matteolavaggi ,
Could you deleted your cache in /var/cache ?
Let me know the outcome!

**Comment by rdy4ever** [comment]
You can disable cache from `app/config/parameters.php`
Set 
`'ps_cache_enable' => 0`

**Comment by florine2623** [comment]
Since we had no news from you for, I'll close this ticket. Feel free to open another one if you can give specific details.
