### ISSUE TITLE
Duplicate combination product results in 500 error page (product is still duplicated)

### ISSUE THREAD

**Issue by imagicuus** [PrestaShop/PrestaShop#19574]
**Describe the bug**
When duplicating a product in some situations a 500 error page is shown. This happens in a multistore installation and only with products that have features and/or combinations. When I duplicate a simple product without features/combinations no error is shown.

When the error is shown the product is still created, but there are no features and images in the created product.

**Expected behavior**
Just like a simple product a product with features/combinations should also be nicely duplicated

**Steps to Reproduce**

- Activate multistore, All Shops environment in BO
- Have Suppliers ready
- Go to Products list
- Try to duplicate a product with combinations -> OK
- Edit that product > in tab Option, choose a Supplier > Save
- Go back to your product list
- Duplicate the newly edited product -> NOK 500 error
- After refreshing the page, product has been duplicated

**Error shown with debug mode :**
![Capture d’écran 2020-06-05 à 17 44 51](https://user-images.githubusercontent.com/16019289/83897730-3f585100-a756-11ea-807a-82df2cb679a5.png)
So I guess it's a combination of having a supplier selected and have a combination in the product. 

Error looks similar to this old issue: https://web.archive.org/web/20180318141337/http://forge.prestashop.com/browse/PSCSX-9828

**Comment by florine2623** [comment]
Hi @imagicuus ,
I could not manage to reproduce our issue in PS 1.7.6.5.
I followed your steps with the specification mentioned.
Please see my screen record :
https://drive.google.com/file/d/1BY75x-Ghhh_voSqHGnJp3487D6XzzbI0/view
Is there anything special in your product page ? Some configuration ?

**Comment by imagicuus** [comment]
Hi @florine2623, 

Thx for checking this out. Because of the SQL error shown I think having a supplier in the options tab might also have something to do with this.

**Comment by florine2623** [comment]
Do you mean this tab ?
![Capture d’écran 2020-06-04 à 18 19 59](https://user-images.githubusercontent.com/16019289/83782397-0e154d80-a690-11ea-9436-12c9dbacca29.png)

**Comment by imagicuus** [comment]
@florine2623 yes indeed. I've recorded the 2 situations. Duplicating a product without supplier and with supplier selected. Wait until the end to see the error: https://drive.google.com/file/d/1uhr5ruNEIuWm34Us0mspEu-_GPksdc6i/view?usp=sharing

**Comment by florine2623** [comment]
Ok thanks for your video, it is clearer.
I still can't reproduce your issue though.

In your supplier list, could you check if they are all available for all your shops of your multistore ?

**Comment by imagicuus** [comment]
Yes, all suppliers are available in all shops. Have you tried it with a product with combinations?

When I look at the SQL error my hypothesis is the following: In the supplier database it wants to add the line with the original "product ID" and the original "product attribute ID" instead of using the newly generated ID's for the duplicated product.

Duplicate entry '200-434-3' for key 'id_product'<br /><pre>INSERT INTO `ps_product_supplier` (`id_product`, `id_product_attribute`, `id_supplier`, `product_supplier_reference`, `product_supplier_price_te`, `id_currency`) VALUES ('200', '434', '3', '', '0.000000', '1')</pre>

**Comment by florine2623** [comment]
@imagicuus 
I did manage to reproduce your issue with a product with combination in a multistore in PS 1.7.6.5 and PS 1.7.7.0.

Steps to reproduce :
- Activate multistore, All Shops environment in BO
- Have Suppliers ready
- Go to Products list
- Try to duplicate a product with combinations -> OK
- Edit that product > in tab Option, choose a Supplier > Save
- Go back to your product list
- Duplicate the newly edited product -> NOK 500 error
- After refreshing the page, product has been duplicated

Error shown with debug mode :
![Capture d’écran 2020-06-05 à 17 44 51](https://user-images.githubusercontent.com/16019289/83896362-5302b800-a754-11ea-85f3-04e541fc4b5f.png)


I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
