### ISSUE TITLE
Attribute name is not updated

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19583]
Hello,
I use attributes for products in PS 1.7.6.5. If I change attribute Name then it is correctly displayed in detail screen, but it is not updated in screen for attribute list.

BO > Catalog > Attributes & Features > choose Edit and attribute detail screen is displayed > change Name > Save > system returns back to the screen for attribute list but there is not updated attribute Name
After cache clearing there is still an incorrect old attribute name

**Comment by juraj1000** [comment]
The similar issue exists also for Features

**Comment by florine2623** [comment]
Hi @juraj1000 ,
I can't reproduce your issue on neither Attributes  nor Features.
Please check my screen recording : https://drive.google.com/file/d/1iRJZ-CgkKr6W2Jto2pSe6_32iTvQpgyo/view

Are you using multi language ? Maybe you only changed it for one language ?

Have you tried enabling debug mode and check for errors ?
Thanks!

**Comment by juraj1000** [comment]
It' strange, now it works correctly, so I'm closing this issue
