### ISSUE TITLE
Product image missing when Upgarde Prestashop

### ISSUE THREAD

**Issue by augustinejenin** [PrestaShop/PrestaShop#19586]
#### Describe the bug

We upgraded prestashop 1.5.0.17 to 1.6.1.24. After updrade complete product images are not available.How can we fix this.
This is the image url after upgrade.
http://quesoslarra.testme.es/64-large_default/queso-larra-cu%C3%B1a-estuche.jpg.

I tried regenerating thumbnail but we got errors.
preferences->images
Original image cannot be found or is empty (/home/quesoslarr/domains/quesoslarra.testme.es/public_html/img/p/3/7/37.jpg) for Product ID 19
Original image cannot be found or is empty (/home/quesoslarr/domains/quesoslarra.testme.es/public_html/img/p/4/0/40.jpg) for Product ID 8

#### Expected behavior

We need to get the product images.

#### Steps to Reproduce

1. Go to 'http://quesoslarra.testme.es/'
2. see the products dont have images.

#### Additional information

* PrestaShop version: 1.6.1.24
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @augustinejenin ,
Did you do a back-up of all files before doing the migration ?
If yes, you can copy the folder /img of your old shop to your new shop !
Let me know the outcome!

**Comment by augustinejenin** [comment]
HI  its ok. we got the images.
after we upgraded to 1.6 design is broken how we can fix this. do we need to do extra css by our own?
please take a look into these sites.
live :http://www.quesoslarra.com/
Upgrded: http://quesoslarra.testme.es/

How we can fix the design issues?

**Comment by florine2623** [comment]
It is not broken CSS, it is the new theme for PS 1.6. If you want another theme, you will have to choose a template here : https://addons.prestashop.com/en/3-templates-prestashop

I will now close the issue, as it is not related to a core problem !
Thanks!
