### ISSUE TITLE
Update product's quantity in the order does not update the discount

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19592]
Be aware of the EPIC - BO - Display and update error on cart rule in the order #19594 to solve this issue

#### Describe the bug

I create a cart rule on the product Brown bear at 9 euro with an automated discount of 50% on the total of the order.
On the back-office, when I update the quantity on the order the discount is not updated

#### Expected behavior

The discount should apply the 50% reduction on all the product amount even if after they are updated 

#### Steps to Reproduce

1. Create a cart rule of 50% reduction on the total of the order with **no code** specifically applied to a product
2. Add the product to any order
3. edit the product quantity

**Screenshots**

After editing the quantity, the discount is not updated
![image](https://user-images.githubusercontent.com/43613217/83863550-c3451580-a723-11ea-92e0-1e1bc730c973.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by matks** [comment]
Back to WIP because https://github.com/PrestaShop/PrestaShop/pull/19646 Travis is not happy

**Comment by MatShir** [comment]
The same problem appears also when the price of the product is edited. Check the issue #19890 caught by @sowbiba
