### ISSUE TITLE
1-click Upgrade - not start

### ISSUE THREAD

**Issue by shoppresta** [PrestaShop/PrestaShop#19596]
#### Describe the bug

I can't open Module 1-Click-Upgrade version: 4.10.1 prestashop 1.7

#### Expected behavior

Upgrade prestashop 1.7.6.4 > 1.7.6.5

#### Steps to Reproduce

1. Go to 'backend prestashop 1.7.6.4'
2. Click on '1-click Upgrade '

**Screenshots**

[Wed May 27 13:59:39.760726 2020] [fcgid:warn] [pid 25906] (104)Connection reset by peer: [client XX.XX.XX.XXX:XXXXX] mod_fcgid: error reading data from FastCGI server, referer: https://www.XXXXXXX.it/adminXXXXXXXX/index.php?controller=AdminCustomerThreads&viewcustomer_thread=&id_customer_thread=25&token=XXXXXXXXXX
[Wed May 27 13:59:39.761458 2020] [core:error] [pid 25906] [client XX.XX.XX.XXX:XXXXX] End of script output before headers: index.php, referer: https://www.XXXXXXX.it/adminXXXXXXXX/index.php?controller=AdminCustomerThreads&viewcustomer_thread=&id_customer_thread=25&token=XXXXXXXXXXX

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.24
* Module 1-Click-Upgrade version: 4.10.1 prestashop 1.7

**Comment by florine2623** [comment]
Hi @shoppresta ,
Can you disable your overrides and try again ?
`override` becomes `_overrides` in FTP.
Thanks

**Comment by shoppresta** [comment]
Hi, I have disabled override in ftp but it doesn't work.
the same error log apache:
[Fri Jun 05 23:36:55.642293 2020] [fcgid:warn] [pid 28508] (104)Connection reset by peer: [client XX.XX.XX.XXX.:XXXXX] mod_fcgid: error reading data from FastCGI server, referer: https://www.XXXXXXX.XX/adminXXXXX/index.php?controller=AdminDashboard&token=XXXXXXXXXXXXXXXXXXXXXX
[Fri Jun 05 23:36:55.642483 2020] [core:error] [pid 28508] [client XX.XX.XX.XXX:XXXXX] End of script output before headers: index.php, referer: https://www.XXXXXX.XX/adminXXXXXXXXX/index.php?controller=AdminDashboard&token=XXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by florine2623** [comment]
You need to contact your server and specify your error : Connection reset by peer: mod_fcgid

I'll close this issue since it is not a PrestaShop issue.
