### ISSUE TITLE
Provide a small block to tell webservice status

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19590]
#### Is your feature request related to a problem?

Webservice page is quite short on informations. You can turn on the webservices, create keys, and that's all.

I am missing the following informations:
- where is webservice endpoint (it's in devdocs)
- even though webservice is enabled it might not work, some other config settings might be needed

#### Describe the solution you'd like

A small block in API page to show these infos:
<img src="https://user-images.githubusercontent.com/3830050/82816059-bfe79980-9e9a-11ea-92c4-9d6185efe6f7.png">

I have made a PR for that https://github.com/PrestaShop/PrestaShop/pull/19335

**Comment by matks** [comment]
@PrestaShop/prestashop-product-team can you validate the feature is OK (and then I can validate/update/finish the PR) ?

**Comment by colinegin** [comment]
What are the different status which will be available ?

**Comment by matks** [comment]
> What are the different status which will be available ?

The idea I have is to actually send a HTTP request to the webservice endpoint and see if it answers back.
If it answers back, status is considered VALID
If no answer or bad answer, status is considered NOT VALID and I display a link to Developer Documentation "troubleshooting webservice" section

So it's "enabled and it works" or "enabled but I cannot reach it"

**Comment by colinegin** [comment]
How will you display it ? Like an error message ? 
IMO it perfectly makes sense, we just need to decide how we should display it to make it clear for the user.

**Comment by matks** [comment]
> How will you display it ? Like an error message ?

In my PR I suggest to display it like this:
<img src="https://user-images.githubusercontent.com/3830050/82816059-bfe79980-9e9a-11ea-92c4-9d6185efe6f7.png">

I can improve the text and the color of course 😄 

I chose to display it under the list of API keys, on top of the form.

**Comment by colinegin** [comment]
ping @LouiseBonnard @Junebyun for the wording review.
ping @TristanLDD @prestascott for the webservice status block.

If this is ok for you, then you can go on @matks ;)

**Comment by Junebyun** [comment]
_Webservice is enabled. Main entry point is http://localhost:8080/apb 
It seems that the webservice endpoint is not functional. If you are using httpd/apache2, you need to enable URL rewriting on your server.
Read the [developer documentation](link) to learn more about it._

@matks for the second setence there's a choice between _**allow** URL rewriting_ or _**activate** URL rewriting_, could you confirm to me which verb matches the context? Thank you :)

**Comment by matks** [comment]
So I have the ✅ for wording
I am waiting for the ✅ on UX

... but is it still needed ? it's a really small text block, nothing critical

<img src="https://user-images.githubusercontent.com/3830050/82816059-bfe79980-9e9a-11ea-92c4-9d6185efe6f7.png">

**Comment by colinegin** [comment]
Is it urgent ? 
If yes then you can go without UX (Tristan and Scott are off today)
If no, then maybe we can wait for @TristanLDD's opinion who will be back tomorrow.

**Comment by matks** [comment]
No urgent at all, it's for 1.7.8 😄 it's rather I dont want to waste @TristanLDD energy on minor issues like this one while he has so much bigger decisions to explore

I feel bad disturbing him for this ; I feel like the little kid yelling "papa ! can I pick this ? papa ! can I go outside ? papa ! can I read this book !"

**Comment by colinegin** [comment]
You can call him "Daddy Tristan". 
In any case, I don't think this will be a problem.

**Comment by prestascott** [comment]
Hi everyone, 

I like this feature, thanks! I'm good for the PR :)

**Comment by elboletaire** [comment]
~Isn't this a duplicate of #19335 ?~

Sorry, I was digging all the issues and PR combined, and didn't realize that is actually a PR and not an issue (this stuff doesn't happen in gitlab xD)
