### ISSUE TITLE
Adding a second product in the order does not update correctly the cart list 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19591]
Be aware of the EPIC - BO - Display and update error on cart rule in the order #19594 to solve this issue

#### Describe the bug

I create a cart rule on the product Brown bear at 9 euro with an automated discount of 50% on the total of the order.

On the back-office, when I add product the product to the order it apply a 50% reduction in the total of the order. But when I add again the same product,  the discount is updated but it keeps the old discount line on the cart rule list.

#### Expected behavior

The cart rule line should be updated

#### Steps to Reproduce

1. Create a cart rule of 50% reduction on the total of the order with **no code** specifically applied to a product
2. Add the product to any order
3. Add the product a second time

**Screenshots**

![2 discount same product](https://user-images.githubusercontent.com/43613217/83862963-f89d3380-a722-11ea-9768-fdd5312b558b.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19698
