### ISSUE TITLE
Discount total not display on tax excl order

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19609]
followed the steps and I see different behavior.

#### Describe the bug

When I create an order with a customer that displays the price as tax excluded and I add a discount of 10% on the total of the order, the discount total in summary disappears. The discount also does not update, the value displayed on the cart rule is incorrect.

#### Expected behavior
The discount should be updated when the product is added with the right display on the total summary.

#### Steps to Reproduce

1. Edit customer group, to displays price with tax excluded
2. Click on "Add new order"
3. Select a customer for the order from the customer group
4. Add a product to the order
5. Click on "add new voucher"
6. In the voucher creation modal create a voucher with the following parameter : 
![capture d'écran_13](https://user-images.githubusercontent.com/40635814/82220401-d9c73080-991e-11ea-813f-10e8e8ed7455.png)
![capture d'écran_14](https://user-images.githubusercontent.com/40635814/82220413-dd5ab780-991e-11ea-9692-c8a729431ec6.png)
![capture d'écran_15](https://user-images.githubusercontent.com/40635814/82220417-e055a800-991e-11ea-9501-79f8795d8e89.png)
7. When the voucher is created add it to the order
8. Then click on "Create the order"
9. In the Order detail click on the "add a product" and add a product
10. See error
![Screenshot from 2020-05-21 14-47-04](https://user-images.githubusercontent.com/31609858/82556279-176fc780-9b72-11ea-9116-3c1838d1d89b.png)

_Originally posted by @zuk3975 in https://github.com/PrestaShop/PrestaShop/issues/19184#issuecomment-632043396_

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19698
