### ISSUE TITLE
The minimum quantity is not respected when I add a product

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19607]
Be aware of the EPIC - Errors when adding a product with minimum quantity in order page #19595

#### Describe the bug

When an edit the quantity of product with min quantity required then delete in the order and I add the product again, it does not throw an error.

#### Expected behavior

Display the error message: "Error! Minimum quantity of "X" must be added when I add the product again.

#### Steps to Reproduce

1. Order a product with a min quantity=3
2. Edit the product quantity on BO in the order page quantity=2
3. Delete the product 
4. Add the product again with the quantity =2
5. Error, it should display an error message: Error! Minimum quantity of "3" must be added

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sowbiba** [comment]
I can't reproduice this issue

https://drive.google.com/file/d/1tyZpUyV7CV5zfbufow_r055bORr5vJNp/view

**Comment by matks** [comment]
Back to WIP because https://github.com/PrestaShop/PrestaShop/pull/19646 Travis is not happy
