### ISSUE TITLE
CategoryChoiceTreeType, ChoiceCategoriesTreeType ShopChoiceTreeType "required" attibute doesn't validate fields

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19612]
#### Describe the bug

When you use a Material Tree Type from PrestaShopBundle, you can set required to true.

You can see the red star at the right if the label, but you can validate. There is no HTML5 validation

![image](https://user-images.githubusercontent.com/4932192/83938823-f517b400-a7d7-11ea-9a67-6b3ac38a8bc3.png)

#### Expected behavior

Manage HTML5 validation.

#### Steps to Reproduce

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform)
2. See error by validating the form

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7
* PHP version: N/A

**Comment by NeOMakinG** [comment]
Hey @202-ecommerce,

I manage to reproduce the issue with PrestaShop version 1.7.x.x and on the develop branch.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by NeOMakinG** [comment]
For material checkboxes, we needs to manage it using JS on the UIKit side

For radio, I did a PR on the core

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers I need a backend dev, in order to setup the required feature for material checkboxes, as the class needs to be at the top of the material tree
