### ISSUE TITLE
[1.7.7-beta.1][1-click Upgrade] Error messages when gamification module is not installed

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#19615]
#### Describe the bug

When upgrading to 1.7.7-beta.1, I get some error messages during the database upgrade process if I don't have the gamification (Merchant Expertise) module installed. This doesn't brake the upgrade, but I get error messages.

#### Expected behavior

Table PREFIX_condition is dropped when you uninstall the "Merchant Expertise" module. So I suppose this table should be upgraded by the module itself, and not PrestaShop, to avoid these messages.

#### Steps to Reproduce

1. In PrestaShop 1.7.6.x, uninstall the Merchant Expertise (gamification) module
2. Go to 1-click Upgrade and upgrade to 1.7.7-beta.1
3. See the error messages

#### Additional information

* PrestaShop version: 1.7.7-beta.1
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @rblaurin ,
First of all, keep in mind that PS 1.7.7.0 is a beta version and should not be used in production.

I will try to reproduce your issue. Could you tell me which version of PS are you starting from ?

**Comment by rblaurin** [comment]
Yes, don't worry, I know it is a beta version. I am just testing and trying to help.
I started from 1.7.6.2, but I think you can reproduce it starting from any version.

**Comment by florine2623** [comment]
Hi @rblaurin ,
I uninstalled gamification module and did the migration with 1-click upgrade successfully.
What kind of error do you have ?

I would advise you to install PS 1.7.7.0 on a subdomain or locally to do your tests.

**Comment by rblaurin** [comment]
Thanks @florine2623 

I forgot to mention something that maybe is the reason why you didn't see error messages: My `debug mode` was active.

As I said before, the errors doesn't brake the installation. But some error messages are shown, and as a developer I think they shouldn't.
In other words, I have **successfuly upgraded** to 1.7.7 beta (in a local installation, don't worry), but **with some error messages**.

They are shown because, as you know, when upgrading to 1.7.7 the upgrade module executes the `install/upgrade/sql/1.7.7.0.sql` script.

In this script, you will find some lines changing `PREFIX_condition` table (lines 86, 277, 278, 279, 280). But this table shouldn't exist if you uninstalled the gamification module. I would say this table should be upgraded by the gamification module itself (as it is responsible to create and drop this table), to avoid error messages

Anyway, if you think this is not a bug, feel free to close this issue, as it will not brake anything and, seemingly, it is not visible if you don't have debug mode active.

**Comment by florine2623** [comment]
Thanks for the details.
I'll close this issue now !

**Comment by rblaurin** [comment]
Well, it ended up fixed as a Bug in #20192 
Thanks.
