### ISSUE TITLE
An exception has been thrown during the rendering of a template ("PrestaShopBundle\Twig\LayoutExtension cannot find the {$content} string in legacy layout template").

### ISSUE THREAD

**Issue by Tatyart31** [PrestaShop/PrestaShop#19616]
Hello, after installing a template I got this error

prestashop version 1.7.6.4
template 
TB_FASHION_SKY_128  

####

in src/PrestaShopBundle/Resources/views/Admin/layout.html.twig (line 34)
    layoutHeaderToolbarBtn is defined ? layoutHeaderToolbarBtn : [],    layoutDisplayType is defined ? layoutDisplayType : '',    showContentHeader is defined ? showContentHeader : true,    headerTabContent is defined ? headerTabContent : '',    enableSidebar is defined ? enableSidebar : false,    help_link is defined ? help_link : ''  )  )) %}{% import '@PrestaShop/Admin/macros.html.twig' as ps %}
Template->displayWithErrorHandling(array('filter_category' => '', 'filter_column_id_product' => '', 'filter_column_name' => '', 'filter_column_reference' => '', 'filter_column_name_category' => '', 'filter_column_price' => '', 'filter_column_sav_quantity' => '', 'filter_column_active' => '', 'last_offset' => '0', 'last_limit' => '20', 'last_orderBy' => 'id_product', 'last_sortOrder' => 'desc', 'limit' => 20, 'offset' => 0, 'orderBy' => 'id_product', 'sortOrder' => 'desc', 'has_filter' => false, 'has_category_filter' => false, 'selected_category' => null, 'has_column_filter' => false, 'products' => array(array('id_product' => '53', 'reference' => 'F545', 'price' => '35,16 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'Blusa premaman smanicata tinta unita', 'link_rewrite' => 'blusa-premaman-smanicata-tinta-unita', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '118', 'name_category' => 'Maglie e Camicie', 'price_final' => '42,90 €', 'nb_downloadable' => null, 'sav_quantity' => '3', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_118.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => 'https://www.assodifiorimaternity.it/118/blusa-premaman-smanicata-tinta-unita.jpg'), array('id_product' => '51', 'reference' => 'F995', 'price' => '45,00 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'Abito premaman in cotone', 'link_rewrite' => 'abito-premaman-in-cotone-', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '113', 'name_category' => 'Abiti', 'price_final' => '54,90 €', 'nb_downloadable' => null, 'sav_quantity' => '3', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_113.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => 'https://www.assodifiorimaternity.it/113/abito-premaman-in-cotone-.jpg'), array('id_product' => '49', 'reference' => 'A4419', 'price' => '65,57 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'Maglia Premaman e Allattamento con cerniere invisibili', 'link_rewrite' => 'maglia-allattamento-gravidanza-cerniereinvisibili-morbida', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '107', 'name_category' => 'Maglie e Camicie', 'price_final' => '80,00 €', 'nb_downloadable' => null, 'sav_quantity' => '4', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_107.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => 'https://www.assodifiorimaternity.it/107/maglia-allattamento-gravidanza-cerniereinvisibili-morbida.jpg'), array('id_product' => '47', 'reference' => 'A0255', 'price' => '106,48 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'Abito corto elagante Premaman e Allattamento', 'link_rewrite' => 'abito-corto-elegante-premaman-allattamento', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '102', 'name_category' => 'Abiti', 'price_final' => '129,90 €', 'nb_downloadable' => null, 'sav_quantity' => '3', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_102.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => 'https://www.assodifiorimaternity.it/102/abito-corto-elegante-premaman-allattamento.jpg'), array('id_product' => '42', 'reference' => 'FSPE', 'price' => '47,54 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'Fascia Lunga Elasticizzata Porta Bebè', 'link_rewrite' => 'fascia-lunga-elasticizzata-porta-bebe', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '96', 'name_category' => 'Per la mamma', 'price_final' => '58,00 €', 'nb_downloadable' => null, 'sav_quantity' => '4', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_96.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => 'https://www.assodifiorimaternity.it/96/fascia-lunga-elasticizzata-porta-bebe.jpg'), array('id_product' => '38', 'reference' => 'f245', 'price' => '56,48 €', 'id_shop_default' => '1', 'is_virtual' => '0', 'name' => 'jeans premaman aderente', 'link_rewrite' => 'jeans_premaman', 'active' => '1', 'shopname' => 'Il mio negozio', 'id_image' => '93', 'name_category' => 'Jeans e pantaloni', 'price_final' => '68,90 €', 'nb_downloadable' => null, 'sav_quantity' => '3', 'badge_danger' => '0', 'total' => '14', 'image' => '<img src="/img/tmp/product_mini_93.jpg?time=1591503995" alt="" class="imgm img-thumbnail" />', 'image_link' => ...

**Comment by matks** [comment]
Dear @Tatyart31,

thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report.

Moreover,
- your log message is too big for us to work with. I had to cut it
- if issue happens because of custom theme, you need to contact the theme developer as this is not code that belongs to PrestaShop (so we cannot fix it)

Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
