### ISSUE TITLE
Bug on prestashop 1.7.6.5 cannot modify translations

### ISSUE THREAD

**Issue by Souhaibbek** [PrestaShop/PrestaShop#19619]
![4554](https://user-images.githubusercontent.com/44231763/83979448-38704080-a906-11ea-9b71-1365272c7ab1.PNG)

#### Describe the bug

I can't modify my translations

#### Expected behavior

any help please

**Comment by NeOMakinG** [comment]
Hello @Souhaibbek,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by florine2623** [comment]
Hi @Souhaibbek ,
Please check your version of PHP and make sure it is compatible with your version of PrestaShop :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks

**Comment by Roca01000** [comment]
Hello, I also have the same Bug my php version is good 7.2 Prestashop version 1.7.6.5
What could be the problem if PHP is ok?
Thanks

<img width="1082" alt="Capture d’écran 2020-06-24 à 12 40 35" src="https://user-images.githubusercontent.com/67385990/85602023-3d93f600-b64f-11ea-9507-ec3edea88aa2.png">
