### ISSUE TITLE
Bug with with price slider and sorting by price

### ISSUE THREAD

**Issue by Pnowfr** [PrestaShop/PrestaShop#19617]
#### Describe the bug

I have a bug with the price slider that does not appear, and sorting by price which displays no products.

#### Expected behavior

filter and sorting products by price

#### Steps to Reproduce

1. Go to https://terredebaobab.com/4-boucles-d-oreilles?order=product.price.asc
here are 58 items, none displayed, and the price slider is not displayed.

#### Additional information

* PrestaShop version: 1.7.6.5
* Ps_facetedsearch version 3.5.0
* PHP version: 7.2

Thank you, 
Peter

**Comment by NeOMakinG** [comment]
Hello @Pnowfr,

I just tested it on 1.7.6.5 and it looks like it's working.

Also, I tested on your shop using chrome version 83.0.4103.61 (Official Build) and it looks like it's working, which browser are you using ? (See the screen)

![image](https://user-images.githubusercontent.com/14963751/84009429-87a08a80-a973-11ea-8d13-7bcf1b564fe8.png)

Thanks

**Comment by Pnowfr** [comment]
Bonjour Valentin, 

Je ne comprends pas, je suis sur Chrome aussi Version 83.0.4103.97 (Build officiel) (64 bits)
Et la glissière de prix ne s'affiche pas ( j'ai rien entre "Matière" et "Forme") : 

![image](https://user-images.githubusercontent.com/60473985/84028207-fe03b380-a998-11ea-9c21-da45085a971d.png)

Et lorsque je tri par prix croissant ou décroissant, j'ai le nombre de produit mais ils ne s'affichent pas : 
![image](https://user-images.githubusercontent.com/60473985/84028329-2d1a2500-a999-11ea-935d-1ce6eed66757.png)

Idem sur Firefox, Edge, etc.
Alors comment ça peut se faire ?

Dzięki  ;)

**Comment by NeOMakinG** [comment]
I just tested it again, take look at this screen, you can see the url and also the slider and filter on :(

I just tested it on firefox too, and on PS 1.7.6.5, everything looks fine... This is so strange.

![image](https://user-images.githubusercontent.com/14963751/84055116-a8d59b00-a9b4-11ea-9fb7-15ebf98aab40.png)

By the way, without any filter, it looks like there are only 47 products, can you check inside your browser console if there are any JS errors ? 

Also, the strange thing is that it looks like you're not on the link you sent inside the issue regarding the left column and the category's description. Maybe you can provide us the link you're on your screen ?

Damn!

Btw: I don't speak polish at all :P

But please, speak english, this issue can be usefull to anyone that can read it :)

**Comment by Pnowfr** [comment]
Thank you,

Currently on Home page (Accueil) there are 56 products : https://terredebaobab.com/2-Accueil
(there were 67 of them, it's an operating site launched 2 days ago)

On "Boucle d'oreilles" page 46 products : https://terredebaobab.com/4-boucles-d-oreilles

I still don't have the price slider : 

![image](https://user-images.githubusercontent.com/60473985/84064698-bea28a80-a9cb-11ea-9d7f-be7b74743e27.png)

I found an error in the console on each page : 

DevTools failed to load SourceMap: Could not load content for https://terredebaobab.com/themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

![image](https://user-images.githubusercontent.com/60473985/84064893-1ccf6d80-a9cc-11ea-81b9-16e15446ad7f.png)
 
I have the same problem on each category: no price slider, and sorting by price which makes the products disappear.

![image](https://user-images.githubusercontent.com/60473985/84065250-bc8cfb80-a9cc-11ea-94e2-44946538006c.png)
(https://terredebaobab.com/4-boucles-d-oreilles?order=product.price.asc)

Peter ;)

**Comment by Pnowfr** [comment]
Hi, 


I noticed something else strange, if I activate the weight slider in the module faceted search it will appear! But te price slider not : 
![image](https://user-images.githubusercontent.com/60473985/84119209-b898c200-aa3c-11ea-8a52-813827fda03e.png)

![image](https://user-images.githubusercontent.com/60473985/84119281-cf3f1900-aa3c-11ea-8e3f-724d6ebcd906.png)

Any idea ?

I am in Madagascar, not in France, can this have an impact on the display of the site?

**Comment by Pnowfr** [comment]
Hi

I had confirmation that the price slider is visible in France but not in Madagascar. 
Anyone know why?

**Comment by florine2623** [comment]
Hi @Pnowfr ,
Could you clear your cache in PrestaShop's BO, as well as your browser cache and try again ?
Thanks!

**Comment by Pnowfr** [comment]
already done, several times, back end and front end
always the same

**Comment by florine2623** [comment]
You might need to check your overrides on modules.
You can go to your FTP and comment the override folder like so : `_override`
The theme can also be the root of the cause. Have you tried with classic theme of PrestaShop ?

**Comment by Pnowfr** [comment]
Thank you for your reply,
It's the classic theme thithout overrides. (I try to comment the folder, no change.)
I removed and reinstalled the faceted filter module, same thing.
People in France see the slider but me in Madagascar no...
it's crazy this story

**Comment by florine2623** [comment]
Can you try to comment your module one by one ?
One of your module might have a conflict with ps_facetedsearch

**Comment by Pnowfr** [comment]
Hi, 
no changes, 
but if I deactivate the facet filter module (facetedsearch), sorting by price works correctly.

**Comment by florine2623** [comment]
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
So I'll close this issue.
