### ISSUE TITLE
Hidden information for Payment in BO

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19622]
Hello,
I use PS 1.7.6.5 and there can be hidden information in BO > Orders > Payments for Invoice number and the buttons Detail and ADD
![image](https://user-images.githubusercontent.com/33311857/84012504-f1bb2e80-a977-11ea-9d5f-8b51d86441e8.png)

You can reproduce it if you zoom the screen in your web browser:
- start BO > Orders > Order detail > Payments
- e.g. in Mozilla Firefox press "Ctrl +" more times and you can will see incorrect result

**Comment by florine2623** [comment]
Hi @juraj1000 ,
This issue is fixed in PS 1.7.7.0 beta. When the release version is out, you can upgrade it :)
I'll close this issue.
