### ISSUE TITLE
Customer group column/filter in list of customers

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19621]
#### Is your feature request related to a problem?

Feature Request: Please add “Customer group” column into customer list Back-office > Customers > Customers. Is quite important when merchant need see and filter customers by customer group.

![customer-group](https://user-images.githubusercontent.com/2806752/84009155-25e02080-a973-11ea-876a-332ab9a8aee4.png)

**Comment by florine2623** [comment]
Hi @Caleydon ,
Thanks for the recommandation, I will ping our product team so they can make the decision !
Please stay tuned!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,
What do you thing about the improvement idea of adding a new filter in Customer page in BO ?
Thanks!

**Comment by Caleydon** [comment]
Of course customer can be assigned into multiple groups. But the column could display default customers group.

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 

It seems good idea to add a new column Customer Group :clap: 
Ping @PrestaShop/product-team fiendly reminder :wink: 

Thanks!

**Comment by Hlavtox** [comment]
@Caleydon Already done bro, it should be in v8 :-) https://github.com/PrestaShop/PrestaShop/pull/28183
