### ISSUE TITLE
"Unit price" ratio is saved instead of raw value

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19620]
#### Describe the bug

"Unit price" field in BO product page is wrong. I save a number, I refresh, another number is displayed (because of bad rounding). I save 900,00, I refresh and 900,025900 is displayed 😄 

#### Expected behavior

I save 900.00, I refresh, unit price is still 900.00.

#### Steps to Reproduce

1. Go to Back-Office, open a product page
2. Click on "Prices "tab
3. Input 900.00 in "unit price" field, then hit "save", then refresh page
4. The field contains now 900.025900 instead.

PrestaShop version: develop

Added a screenshot with all details below

**Comment by matks** [comment]
<img width="1102" alt="Capture d’écran 2020-06-08 à 10 21 00" src="https://user-images.githubusercontent.com/3830050/84008223-cfbead80-a971-11ea-89c4-90e15c73cd5f.png">

**Comment by matks** [comment]
Simple php script to see what happens
```
<?php

$unit_price = 900.0;
$price = 13.9;

$ratio = $price/$unit_price;
var_dump($ratio);
// float(0.015444444444444)

$ratio_rounded = round($ratio, 6); // this is what happens when ratio is stored into database with 6 digits

$unit_price_after_round = $price/$ratio_rounded;
var_dump($unit_price_after_round);
// float(900.0259000259)
```

**Comment by matks** [comment]
# Possible solutions

## Hard BC break: store unit_price instead of unit_price_ratio

`$unit_price_ratio` is the data being stored in the database, and is rounded. This is what creates this strange behavior "I save field X, I refresh, X field has changed". It's because X is not saved directly into database, it is being converted into another number (the ratio) and this other number is the one being stored, keeping any rounding issues on the way.

This could be solved by storing into database unit_price instead of unit_price_ratio but that would be a massive change to Product persistence model, breaking any SQL query which use it.

## Soft BC break: store unit_price AND of unit_price_ratio

Another solution would be to store both properties into database. It's not really a BC break because nothing will be broken from this change however since the 2 values slightly differ, people using one value or another will have different results.

Not the best

## Mitigate impact

We could reduce the rounding issues by using a higher precision for the computation than from the storing.

This means:
1. Store ratio with 8 or 10 digits to have more accurate unit_price values
OR
2. Oblige people to input unit_price with 2 or 4 digits only

There will still be rounding issues, but it will have a lower impact

**Comment by marionf** [comment]
@matks @florine2623 Could you add missing labels (bug or improvement or refacto), the severity if it's a bug ? Is it a regression of develop branch ?

**Comment by matks** [comment]
> @matks @florine2623 Could you add missing labels (bug or improvement or refacto), the severity if it's a bug ? Is it a regression of develop branch ?

It's an old bug, I think it was always there (but we found it while working on the migration of the page).

**Comment by hibatallahAouadni** [comment]
Related to this issue #12078
