### ISSUE TITLE
issue with product variation

### ISSUE THREAD

**Issue by dylanpaddeu** [PrestaShop/PrestaShop#19624]
hello,
I'm on dedicate server + php7.3 + prestashop 1.7.6.5 + mariadb +nginx + wk gérer déclinaison. 
when I click on BO product list on the the product with 22k variation i get 504 gateaway timeout  eror.
regard dylan

**Comment by florine2623** [comment]
Hi @dylanpaddeu ,
PrestaShop 1.7.6.5 is compatible with PHP 7.2 max.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Error 504 is a server error, not an error with PrestaShop itself, so I'll close this issue.
Thanks!
