### ISSUE TITLE
Update the German tax rates

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#19628]
#### Is your feature request related to a problem?

Following this [announcement](https://www.lepoint.fr/monde/allemagne-un-plan-de-relance-de-l-economie-de-130-milliards-d-euros-devoile-04-06-2020-2378416_24.php) (🇫🇷), Germany will temporary lower its tax rates until the end of the year.

VAT rates will be reduced from 19% to 16% and from 7% to 5%. Since it is not handled dynamically in the software, we have to change it manually in the code.

#### Describe the solution you'd like

In the [German localization file](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/de.xml):

    <tax id="1" name="MwSt. DE 19%" rate="19" eu-tax-group="virtual"/>
    <tax id="2" name="MwSt. DE 7%" rate="7"/>

should be

    <tax id="1" name="MwSt. DE 16%" rate="16" eu-tax-group="virtual"/>
    <tax id="2" name="MwSt. DE 5%" rate="5"/>

**Comment by LouiseBonnard** [comment]
@didi-2018, I've just created a pull request to have it fixed in the next 1.7.7 minor version. You can follow this issue to know when those new tax rates will be available in PrestaShop. :-)

**Comment by didi-2018** [comment]
@LouiseBonnard thank you very much ♥ but it is much more than only change from 19% to 16%. If a customer bought an item in June 2020 and returns it in July 2020 the shop has in July 16% tax but the return must be credited with 19%. Have you considered this??

**Comment by LouiseBonnard** [comment]
You're welcome, @didi-2018! Unfortunately, we are not able to handle those cases... on our end, we can just update the rates, after that it is the user's responsibility to make sure there is no inconsistency. But it still has to be updated manually by the user so he/she should be aware of this change. :-)

**Comment by didi-2018** [comment]
Good morning @LouiseBonnard, no you havn´t understoud. I´ll try explain again: 

costumer orders 28.06.20 with 19% tax
package is shipped 29.06.20 with 19% tax
tax change 01.07.20 to 16% 
customer returns 10.07.20
credit slip must be with 19% cause the customer shipping date was in June with 19%

That is the problem, that prestashop need to handle. There must be a query in prestashop if shipping date is June or July

This will be a big problem for all german Prestashop users :-(

**Comment by LouiseBonnard** [comment]
@PrestaShop/prestashop-core-developers, what do you think?

**Comment by Progi1984** [comment]
Fixed in 1.7.7.x by #19897
