### ISSUE TITLE
Make PrestaShop support varnish out-of-the-box

### ISSUE THREAD

**Issue by aecarlosae** [PrestaShop/PrestaShop#19633]
#### Describe the bug

Hello guy!
I have a server with **Varnish service** enable. After successfully login to the Backoffice (BO), if I click or try to run a BO function (e.i Create a product, edit a customer...), I get automatically log out.

I thought it was a IP changing issue and tried to disable "Check the cookie's IP address" but the problem was not fixed.

After some hours trying to find a solution, I read that **Prestashop** do not have Varnish Support.

Will **Prestashop**  have Varnish Support?

#### Steps to Reproduce

1. Install and enable **Varnish** service in your server
2. Log in in your backoffice
3. Click on some link, try to create a product or do any other action
4. After some clicks or actions, **Prestashop** ends session and you will need to re-login

#### Additional information

* PrestaShop version: 1.7.6.1 & 1.7.6.5
* PHP version: 7.2.31

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers Could you check this issue ?

**Comment by matks** [comment]
Hi @aecarlosae what do you mean by "varnish support" ? Do you mean Edge Side Includes ?

Also I think varnish should be configured on front-office only 🤔 you do not need it for BO, do you ?

**Comment by aecarlosae** [comment]
Hi @matks, I mean [Varnish](https://en.wikipedia.org/wiki/Varnish_(software)). It's just an HTTP accelerator for speeding up servers but when it is enabled, Prestashop backoffice automatically ends sessions after some clicks on any link.

I wanna know if PS need some extra configurations in order to work with this server service or it's a bug.

It's a server service, it applies to BO and Front

**Comment by matks** [comment]
AFAIK, PrestaShop does not work out-of-the-box with Varnish but some people succeeded in making it happen ... and sell this knowledge 😉 see https://www.softizy.com/blog/varnish-cache-prestashop-black-friday/ for example

**Comment by aecarlosae** [comment]
Should I add this as a new **Feature Request**?

**Comment by matks** [comment]
> Should I add this as a new **Feature Request**?

Well, you can indeed 😊 

One note: I think making PS varnish-compliant is easier and more useful on front-office (because lot of customers and you need short response times) than for back-office

**Comment by aecarlosae** [comment]
Yes, it's on front-office but Backoffice must not be affected wrongly. I'm going to added as a new Feature.

**Comment by ksaandev** [comment]
Would be good to have varnish in native prestashop !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@aecarlosae is suggesting using Varnish on PrestaShop.
Do you think that could be done ?

Thanks!

**Comment by matks** [comment]
> Hi @PrestaShop/prestashop-product-team ,
> 
> @aecarlosae is suggesting using Varnish on PrestaShop.

Hi, if I am not wrong, the feature request is rather 😉 :
- make PS varnish-compliant on front-office
- make PS varnish-compliant on back-office
- explain in devdocs how to setup Varnish to be used on PS BO and/or FO

**Comment by LouiseBonnard** [comment]
Interesting, thanks @aecarlosae! Using varnish has already been mentioned in several documents regarding the software's performance. It seems to be mostly used by stores with large catalogs. @matks, what would be your technical recommendation? Should it be labeled _waiting for dev_ instead?

**Comment by matks** [comment]
@LouiseBonnard The benefits of Varnish are large, there is no discussing that 😄 the question is rather prioritization.

@ldeprestashop an example of something hard to prioritize: possibly great benefits but can be time-consuming to do for developers

**Comment by ldeprestashop** [comment]
I agree @matks : varnish can be a major feature for huge site be we must focus on one direction. 

We don't have any ressources for study (and develop) any sides of eCommerce, so we will must make choice for futures releases.

Maybe Varnish on a future release if  we will decide to focus  on huge sites. 

It’s very complicate for Product Management to chose one feature because we must give up many others.

**Comment by matks** [comment]
@ldeprestashop I think we can close this issue for now because we are not likely to implement it soon.

@aecarlosae I close this issue. This does not mean we dont care or we dont think this is interesting, it's rather that we have so much topics to handle, this one cannot reach the top of our pile of things to do. But if you are interested in the topic feel free to invest yourself in it 😉  .

**Comment by aecarlosae** [comment]
Ok @matks I'm going to generate a solution and when it is ready, I'll tell you about. Thanks!
