### ISSUE TITLE
Configuration for text for product with combinations

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19636]
Hello,
I use PS 1.7.6.5 with products with combinations. There is also used the character dash "-" in values for attributes. If there are more attributes the PS uses dash as a separator in text item in an invoice. 
It is confusing for a business user because he doesn't know what is separator and what is the attribute.

I propose to create a possibility for configuration of such text item.

_Current text_
Product ABC - Size : X-M - Color : blue-green

_Required text_
Product ABC (Size: X-M, Color: blue-green)

Size and Color are attributes, X-M and blue-green are attribute values.

**Comment by sarahdib** [comment]
Hello @juraj1000 you can change the separator in your combinations by / 
Product ABC (Size: X/M - Color: blue/green)

@PrestaShop/prestashop-product-team  What do you think about that ?
Allow customer to configure the attribute separator in the invoice.

Thank you

**Comment by LouiseBonnard** [comment]
Hello there, yep, it'd be nice to better distinguish the attribute name from its value. I ping our super Product Content Manager @Junebyun so that she can let us know what she thinks about this wording. ;-)

**Comment by Junebyun** [comment]
Hello! Thank you for opening this issue @juraj1000 :)
Concerning the wording, I'd go with @sarahdib 's suggestion:

_Product ABC (Size: X/M - Color: blue/green)_

I'd rather keep the dash to seperate the attributes and its values!

**Comment by juraj1000** [comment]
Hi,
the solution with separator / is not suitable. We use attributes as time period from-to, e.g. 2020-2022 or 10-12 for years and months. If there was / as a separator it would look like 2020/2022 or 10/12 and it is not clear that it means period from-to. 
Therefore we'd like to have a possibility for configuration of this text. Also take into account that currently it is not possible to use brackets as begin and end of the text.
I can also imagine that some eshops could require to display every attribute on the new line, e.g.:

_Product ABC 
Size: X-M
Color: blue-green_

Therefore the configuration of such texts would be helpful.

**Comment by Junebyun** [comment]
Hello @juraj1000 Could you show me a screenshot of what your invoice looks like? I tried to generate an invoice and as you can see attributes values are separated by a comma so it matches what you wanted:
![image](https://user-images.githubusercontent.com/64894223/86005198-9c24ef80-ba14-11ea-9789-1f6461549ea6.png)

**Comment by juraj1000** [comment]
Hello,
I generated a new invoice and there is not any comma.

![image](https://user-images.githubusercontent.com/33311857/86112957-ec5d8980-bac8-11ea-98ca-5849ab4c09fd.png)

**Comment by Junebyun** [comment]
Hello, @juraj1000, indeed you are right. I tried to generate other invoices again and for some reason I have "Size : M- Color : Black"  

Solution needed: Product ABC (Size: X-M, Color: blue-green)

**Comment by juraj1000** [comment]
Hello @Junebyun,
I think, any configuration could solve this requirement much better than hardcoding, e.g. see my previous comment with more text lines

**Comment by Junebyun** [comment]
@juraj1000 I think we could first fix space and character problems : 
_Product ABC (Size: X-M, Color: Blue-Green)_
instead of the current _Product ABC - Size : X-M- Color : Blue-Green_ text


and then secondly consider whether or not to create either a drop down list with several characters (dash, comma, slash) or allow users to customize it as they like.

**Comment by Progi1984** [comment]
@LouiseBonnard The separator between attributes is a configuration of the Shop (Menu `Configure > Shop > Product Preferences` : Fieldset `Product Page` : Configuration `Separator of attribute anchor on the product links`).

Else Changes for this label will impact multiple locations :

![image](https://user-images.githubusercontent.com/1533248/94165179-3c5ea900-fe8a-11ea-969c-211eb3ca3736.png)
![image](https://user-images.githubusercontent.com/1533248/94165425-7d56bd80-fe8a-11ea-85db-891f013dbb4a.png)


(Available in the PR #21141 )
