### ISSUE TITLE
Currency exchange rate feed url in 1.7.7.x

### ISSUE THREAD

**Issue by molszews** [PrestaShop/PrestaShop#19635]
#### Describe the bug

In 1.7.7.x `src/Core/Currency/ExchangeRateProvider.php` was introduced with hardcoded currency feed url: https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/Core/Currency/ExchangeRateProvider.php#L48
As this is not part of the config (`defines_uri.inc.php`) anymore, I'm afraid about making further updates of the online shop - they may break the compatibility and existing functionality, some shops require frequent updates of currency rates and use specialized services for providing such feed.

#### Expected behavior

`_PS_CURRENCY_FEED_URL_` defined in `defines_uri.inc.php` will be referenced instead of having hardcoded values in exchange rate related logic.

#### Additional information

* PrestaShop version: 1.7.7

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers could you check this issue please :) ?

**Comment by PierreRambaud** [comment]
Hi and sorry for the delay.

This constant is used by a service `prestashop.core.exchange_rate.provider` stored in `services/core/currency.yml`. You can easily change this value data by overriding this service call :)

https://devdocs.prestashop.com/1.7/modules/concepts/services/#override-an-existing-symfony-service

Kind regards

**Comment by HartLarsson** [comment]
just a question about EURO -> USD rates:

from prestashop api: http://api.prestashop.com/xml/currencies.xml

![image](https://user-images.githubusercontent.com/16102074/112027818-dbade180-8b37-11eb-81ea-a541893459b4.png)

from ecb: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

![image](https://user-images.githubusercontent.com/16102074/112027893-eec0b180-8b37-11eb-9629-61a7b7dadafe.png)

The rate are different.
Can you explain where Prestashop gets the rates value?
Is important to know the source.

Thank you
