### ISSUE TITLE
installing prestashop 1.7.8.0

### ISSUE THREAD

**Issue by bmihm** [PrestaShop/PrestaShop#19638]
I install the shop with composer and all work ok.
when I try to open the admin shop there is strange look like css is not loaded. 
i verify the css tag with chrome and the css link is not there.

I use xampp and windows 10 and I have around 10 shops installed on my computer that are all working. 

I want to install a new one in a new folder and is not working,

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**
![image](https://user-images.githubusercontent.com/64200021/84086528-6463f280-a9e8-11ea-83e2-49cff2fe90e8.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

the shop is correctly installed.

![image](https://user-images.githubusercontent.com/64200021/84086762-e81ddf00-a9e8-11ea-811a-7b9ab7f4f318.png)

* PrestaShop version: last version from github develop branch
* PHP version: 7.3.18

**Comment by sarahdib** [comment]
Hello @bmihm 

in your console you need to do a "make install" 

Thank you

**Comment by bmihm** [comment]
Hi @sarahdib . 
I have a Windows. how to make install?

**Comment by matks** [comment]
> Hi @sarahdib .
> I have a Windows. how to make install?

There's plenty of solutions you can find on Google 😉 example https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows

**Comment by bmihm** [comment]
this is how is look my admin.
![image](https://user-images.githubusercontent.com/64200021/84127555-b8e68c80-aa3f-11ea-96a3-2424d456e626.png)

This is how my shop is looking .

![image](https://user-images.githubusercontent.com/64200021/84127663-d7e51e80-aa3f-11ea-981d-77b1e8eaa3ea.png)

**Comment by bmihm** [comment]
why is this now, a few days ago I install the developer version and it's work perfectly.

**Comment by eternoendless** [comment]
https://devdocs.prestashop.com/1.7/development/compile-assets/#build-all-assets-at-once
