### ISSUE TITLE
Incorrect modern email template for new order

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19637]
Hello,
I use PS 1.7.6.5 with modern email theme. But if a business user place an order and the PS sends the  email "New order" then there is used old classic template. There should be modern template.
![image](https://user-images.githubusercontent.com/33311857/84082596-688c1200-a9e0-11ea-8e69-413651e8b53d.png)

**Comment by sarahdib** [comment]
hello @juraj1000 

I didn't reproduce 
<img width="671" alt="Capture d’écran 2020-06-09 à 17 14 56" src="https://user-images.githubusercontent.com/3034677/84166291-ffa2a980-aa74-11ea-931b-8a6b8d4a29da.png">

Did you re-generate email ?

Thank you

**Comment by juraj1000** [comment]
Could you please send me exact info how I could regenerate it?

**Comment by florine2623** [comment]
You need to go to Improve > Design > Email Theme > Generate emails

**Comment by juraj1000** [comment]
I regenerated it successfully, thanks. I had to set: 

- Select the theme you want to overwrite = classic

- Overwrite templates = Yes
