### ISSUE TITLE
Prestashop falsely sends "Item out of stock" mails to customers

### ISSUE THREAD

**Issue by lisapowerlifts** [PrestaShop/PrestaShop#19641]
I'm using Prestashop with the Braintree Module. After a Payment is authorized by the customer it takes approx. 2 hours to be completed and the Prestashop order status changes from blue to green. We had the following situation:

1.) Product got sold out (5 orders, 5 products in stock). All 5 orders still payment processing via Paypal (using Braintree Module).
2.) Product in store marked as sold out (correct)
3.) After 2 hours all 5 order went pink "out of stock (payed)" and the payment went through.
4.) Customers got an email saying their payed for item is out of stock!!!

3. and 4. shouldn't have happened. The item is now out of stock (after the 5 orders), but these 5 customers were still able to get it. The E-Mail to the customers is misleading.

Thank you very much,
Lisa

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

**Comment by mecene** [comment]
We have the exact same issue using the Braintree's paypal payment solution.
If the last item is bought using paypal, the order status become "Awaiting for Braintree validation",
once the Brantree validation is confirmed (1-2 hours later) the status changed to "backorder (paid)" and a misleading "Out of stock, waiting for replenishment" email is sent to the customer.

It seems that the braintree payment confirmation status check the current stock of the purchased article despite having already decremented the stock.

- PrestaShop: 1.7.2.2
- PHP version : 5.6

Also tested on:

- PrestaShop version: 1.7.6.5
- PHP version: 7.2.30

**Comment by mecene** [comment]
@lisapowerlifts 
I may have found a quick fix for this issue.
The module dynamicaly change the status of the order which triger an email notification.
When a client use Paypal to order an item, the Braintree validation takes up to two hours to confirm the payment and then change the status of the order using the functions "hookDisplayBackOfficeHeader" from braintreeofficial/braintreeofficial.php.
This function seems to allow the client to Backorder even though this option is not turned on in the Prestashop admin and change the order status depending on the current stock.


                    foreach ($ps_order_details as $order_detail) {
                        // Switch to back order if needed
                        $product_stock = StockAvailable::getQuantityAvailableByProduct($order_detail['product_id'], $order_detail['product_attribute_id']);
                        if (Configuration::get('PS_STOCK_MANAGEMENT') && $product_stock <= 0) { // fix  < 0
                            $paid_state  = Configuration::get('PS_OS_OUTOFSTOCK_PAID');
                        }
                    }

I believe that replacing <= 0 by < 0 on line 837 is a quick and bad fix but seems to be working for us.

Best regards

**Comment by lisapowerlifts** [comment]
Thank you very much! That would mean the problem ist in the Braintree-Module, not with Prestashop?

By changing to <0 one technically disables the if bracket (commenting it out should have the same effect?), since the case <0 never is true.

I guess for a clean solution one would have to rewrite the bracket to only detect products that have been sold too many times...

I just deactivated the mail-notification for out of stock orders to the customers in the backoffice. Thats a quick fix, but obviously also not a perfect solution.

**Comment by mecene** [comment]
I guess you could comment the whole section but as Prestashop is still a little buggy, I am quite sure that under certain conditions orders to negative stock are possible.
Best regards

**Comment by florine2623** [comment]
Hi @lisapowerlifts @mecene ,
I could not reproduce the issue using Check Payment and Bank Transfert with manual processing of the orders.
Please check with Braintree developers for that issue.

Thanks!
