### ISSUE TITLE
Pack::isInStock - Incorrect value when changing shop context in a script

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#19649]
#### Describe the bug

In a module I made, I can create/update products stock for some selected shops.
So I made a loop to switch the shop in the context.
But when I tried to get the current stock of a pack, something weird happens.
I use the method Pack::isInStock and if in the first shop I have no quantity, this method always return false for the other shops.

#### Expected behavior

Getting the right quantity depending on the current shop in the context.

#### Steps to Reproduce

1. Have a pack product with no stock in a shop
2. For the same product put some stock on a second shop
3. Make a script wich connect to the first shop, call the method Pack::isInStock. There is no stock (it's ok). In the same script, switch to the second shop and call the same method. There is no stock … Here it's not ok.

**Screenshots**

![ps_bug](https://user-images.githubusercontent.com/29065423/84147394-9fecd400-aa5d-11ea-907e-f97ed77246e4.png)

#### Additional information

* PrestaShop version: 1.7.4.0
* PHP version: 7.1

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers could you check ?

**Comment by hibatallahAouadni** [comment]
Hello @thalassa-web 

Sorry for the late response :confused: 
Ok, let's resume to make it clear, you're developing a module where you use the method **`Pack::isInStock`** and you encounter problem:

1. Create a **Pack X** with no stock (qty=0) in **Store A**
2. Switch to **Store B**, add some stock to the **Pack X** (for exemple: qty=50)
3. **Store A**: call the method **`Pack::isInStock`**, there is no stock => **OK**
4. **Store B**: call the method **`Pack::isInStock`**, there is no stock => **NOK**

Is that so? if so, could you please tell me if the stores are sharing the same stock or no?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @thalassa-web ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
