### ISSUE TITLE
Terminology Best sellers/Best sales

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19643]
#### Describe the bug

There is used different terminology for the same functionality: Best sellers/Best sales

#### Expected behavior

I expect unified terminology, otherwise it is confusing for a business user

#### Steps to Reproduce

1. e-shop FO
2. Scroll down to 'Products' => see link 'Best sales'
3. Click on 'Best sales' => see 'Best sellers'  in the header of new page

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/145817318-4de181d3-0288-4ddd-aaff-974f418540ce.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by TristanLDD** [comment]
Hi @juraj1000, thanks for your report. 

Indeed, these terminologies should be unified. We'll take that in account and make the change as soon as possible :) 

Thank you

**Comment by Junebyun** [comment]
Hi @juraj1000 I think we could harmonize it with "_**Best Sellers**_" everywhere: 

- in the footer of the FO footer ("_Products_" column)

- as the head title once you click on it

"_Best sellers_" is also used when you activate the Top-sellers block module, so it will be consistent with it! 

I thought that "_Best sales_" might be confused as a "_list of products which price are reduced_", thus meaning "_best promotions_". 

@TristanLDD wdyt?
