### ISSUE TITLE
incorrect work ps_facetedsearch 

### ISSUE THREAD

**Issue by sofiaulakova** [PrestaShop/PrestaShop#19658]
#### Describe the bug

The multilevel filtering module on my site does not work correctly after the update. The price half-price bar is not displayed on all category pages. Only sometimes in subcategories. What should I do? I don’t understand what the problem is, I am not a programmer and I don’t know where the error is possible. I asked tech support for my topic, they said that they also don’t know what the problem is and that others are fine. 
Here is my site https://amberheart.ru/ru/ 

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**
![image](https://user-images.githubusercontent.com/49074257/84173329-d0e0ff00-aa85-11ea-907b-92f85a803fd8.png)
![image](https://user-images.githubusercontent.com/49074257/84173368-de968480-aa85-11ea-85a1-b5c405402817.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by TristanLDD** [comment]
Hi @sofiaulakova, thanks for your report 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

@PierreRambaud, have you already heard about such problem on the faceted search module by chance?

**Comment by sofiaulakova** [comment]
*    host:  https://cp.beget.com/  
*  server setup and configuration - PrestaShop version (source): ​​​1.7.6.4
*  Server setup:
*  Operating system  Linux #1 SMP Fri Nov 2 12:51:30 MSK 2018 x86_64 
*  Type and version of webserver (Apache, Nginx, IIS, other).  Apache/2.4.10 (Unix)
*  Version of PHP.  7.1.33
*  Version of MySQL/MariaDB.  5.7.21-20-beget-5.7.21-20-1-log
*  Make sure you have emptied PrestaShop’s cache! done
*  Browser setup:
*  Operating system. opera
*  Version of the browser. 68.0.3618.165
*  Make sure you have emptied your browser’s cache! done
*  I don’t know where to look and I can’t find the error log.
> 
>>
>>Среда, 10 июня 2020, 17:06 +03:00 от TristanLDD < notifications@github.com >:
>> 
>> 
>>Hi  @sofiaulakova , thanks for your report
>>Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
>>*  host
>>*  server setup and configuration - PrestaShop version (source)
>>*  debug mode report
>>*  PHP error logs
>>*  apache error log
>>*  Javascript console log
>>*  screenshots
>>...
>>You don't know how to get this information? Please read the following article:  http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
>>Thank you!
>>@PierreRambaud , have you already heard about such problem on the faceted search module by chance?
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>----------------------------------------------------------------------
>С уважением,
>Софья Кулакова
>
>Графический дизайнер
>SMM менеджер
>
>8 (962) 257-35-94
>vk.com/skulakova1 
  
>Среда, 10 июня 2020, 17:06 +03:00 от TristanLDD < notifications@github.com >:
> 
> 
>Hi  @sofiaulakova , thanks for your report
>Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
>*  host
>*  server setup and configuration - PrestaShop version (source)
>*  debug mode report
>*  PHP error logs
>*  apache error log
>*  Javascript console log
>*  screenshots
>...
>You don't know how to get this information? Please read the following article:  http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
>Thank you!
>@PierreRambaud , have you already heard about such problem on the faceted search module by chance?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
----------------------------------------------------------------------
С уважением,
Софья Кулакова

Графический дизайнер
SMM менеджер

8 (962) 257-35-94
vk.com/skulakova1

**Comment by florine2623** [comment]
Hi @sofiaulakova ,
Please answer only via GitHub and not by email.
What exactly does not work ?
What version of ps_facetedsearch are you using ?
How can I test if the bug is present ? Please share the steps to reproduce the bug.

Thanks!

**Comment by sofiaulakova** [comment]
The slider doesn't work on some pages in the categories section. For example, I go to the category of beads and the slider with the price does not work, but if I go to the subcategory of pendants, it shows. And so everywhere in all categories. I attached screenshots in the first message

**Comment by sofiaulakova** [comment]
Module version v3. 5. 0

**Comment by florine2623** [comment]
Have you tried with theme classic ?
This error might come from your theme. Please verify.

**Comment by sofiaulakova** [comment]
I can’t check it, because my site stops working, giving an error of 500. And when I want to switch back to my topic, a message appears in the admin panel saying that this is not possible. I had to backup two times

**Comment by PierreRambaud** [comment]
> I can’t check it, because my site stops working, giving an error of 500. And when I want to switch back to my topic, a message appears in the admin panel saying that this is not possible. I had to backup two times

You should see with the creator of your theme. Despite several tries, we are not able to reproduce your issue.
