### ISSUE TITLE
$carrier.extraContent not showing

### ISSUE THREAD

**Issue by sirdoy** [PrestaShop/PrestaShop#19652]
Hi, in the shipping.tpl file there is this part of code:
```
<div class="carrier-extra-content" {if $delivery_option !=$carrier_id} style="display:none;" {/if}>
  {$carrier.extraContent nofilter}</div>
<div class="clearfix"></div>
```
but it doesn't display anything.
Is it normal for the variable $carrier.extraContent to display nothing?

**Comment by TristanLDD** [comment]
Hi @sirdoy,  thanks for the report. 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots

You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
