### ISSUE TITLE
Error on Prestashop Admin Page

### ISSUE THREAD

**Issue by KwabeaAtakora** [PrestaShop/PrestaShop#19656]
Hi,

I get the error below on my admin page after migrating. The shop works well though.

Notice: tempnam(): file created in the system's temporary directory in /var/www/urban/classes/PrestaShopAutoload.php on line 258

Warning: rename(/tmp/class_index.phpXFECOe,/var/www/urban/var/cache/dev/class_index.php): No such file or directory in /var/www/urban/classes/PrestaShopAutoload.php on line 264

Notice: tempnam(): file created in the system's temporary directory in /var/www/urban/classes/PrestaShopAutoload.php on line 258

Warning: rename(/tmp/class_stub.phpHDZuio,/var/www/urban/var/cache/dev/class_stub.php): No such file or directory in /var/www/urban/classes/PrestaShopAutoload.php on line 264

Notice: tempnam(): file created in the system's temporary directory in /var/www/urban/classes/PrestaShopAutoload.php on line 258

Warning: rename(/tmp/namespaced_class_stub.phpPTyoMx,/var/www/urban/var/cache/dev/namespaced_class_stub.php): No such file or directory in /var/www/urban/classes/PrestaShopAutoload.php on line 264

Warning: require_once(/var/www/urban/var/cache/dev/appParameters.php): failed to open stream: No such file or directory in /var/www/urban/config/bootstrap.php on line 87

Fatal error: require_once(): Failed opening required '/var/www/urban/var/cache/dev/appParameters.php' (include_path='/var/www/urban/vendor/pear/pear_exception:/var/www/urban/vendor/pear/console_getopt:/var/www/urban/vendor/pear/pear-core-minimal/src:/var/www/urban/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/urban/config/bootstrap.php on line 87

**Comment by TristanLDD** [comment]
Hi @KwabeaAtakora, thanks for your report.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by KwabeaAtakora** [comment]
@TristanLDD I ve solved it. I had to set the permissions to directories and files to 777

**Comment by stefann-sasori** [comment]
I solved it by setting 777 chmod to img folder

**Comment by ibnubasir96** [comment]
hai?

**Comment by ibnubasir96** [comment]
Im still stuck with the problem , despite i have change files to 777

**Comment by ibnubasir96** [comment]
how to set permissions to directories?

**Comment by ediathome** [comment]
Using the command line:
`chmod -R 777 myshop/*`
