### ISSUE TITLE
1.7.7 beta - Creating a command from the backoffice does not work - JS errors in console - fancybox is not a function

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#19659]
I have a js error

"TypeError: y(...).fancybox is not a function"

impossible to choose a customer and if I create one, the window does not review on the creation of order

**Comment by TristanLDD** [comment]
Hi @olecorre, thank you for the report. 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by olecorre** [comment]
Host : http://preprod17.optimumlight.com (private preprod)
Server : apache with PHP 7.2, no SSL
PrestaShop 1.7.7.0 beta from github
No debug mode
No apache error or PHP error
Screenshots joins

Two JS errors, test with firefox and chrome

<img width="1435" alt="Capture d’écran 2020-06-10 à 11 21 44" src="https://user-images.githubusercontent.com/2854750/84250741-bc941500-ab0c-11ea-90fe-070ca6a8f833.png">

![Capture d’écran 2020-06-10 à 11 18 13](https://user-images.githubusercontent.com/2854750/84250770-c584e680-ab0c-11ea-9150-7b2f9bcedc8f.png)

**Comment by TristanLDD** [comment]
@PrestaShop/prestashop-core-developers WDYT?

**Comment by olecorre** [comment]
I had the same problem with my local version.

**Comment by olecorre** [comment]
Oups beta downlaod from https://download.prestashop.com/download/releases/prestashop_1.7.7.0-beta.1.zip

**Comment by matks** [comment]
@olecorre I cannot reproduce on Chrome 🤔 
I have some errors in Console but not the same as you:
<img width="1432" alt="Capture d’écran 2020-06-11 à 11 54 21" src="https://user-images.githubusercontent.com/3830050/84371823-89b85280-abda-11ea-8bfa-f02070f32136.png">

<img width="1439" alt="Capture d’écran 2020-06-11 à 11 56 17" src="https://user-images.githubusercontent.com/3830050/84371848-9341ba80-abda-11ea-9fda-07b7af96a67c.png">

It looks like you are on Chrome too though.

Maybe a bad 1st page load and now bad JS is cached into your browser ? Could it be possible to wipeout the JS to be 100% sure ? You can do this by doing
- open page
- open developer tool
- right click on "refresh" page to open advanced refresh menu (see below)
- empty cache

<img width="513" alt="Capture d’écran 2020-06-11 à 11 57 33" src="https://user-images.githubusercontent.com/3830050/84372002-ca17d080-abda-11ea-9a88-b6abebe19ace.png">

**Comment by matks** [comment]
- and my chrome error console do not prevent me from creating/choosing customers
- and to be sure, I downloaded the same ZIP

**Comment by matks** [comment]
Also other possible "fun" usecase; if you have opened a PrestaShop in the same location (same server, same URL) before with another version, it's possible your browser has put jQuery in cache. In 1.7.7. we updated jQuery version so if your browser tries to open the page with old jQuery version it will break.

Clearing the cache should work in this usecase

**Comment by matks** [comment]
@olecorre I think we found and fixed the issue ! 😄 https://github.com/PrestaShop/PrestaShop/pull/19796
