### ISSUE TITLE
[Shipping tab ] - Package dimension 1/4

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19666]
As a merchant, I want to be able to manage carriers' information for my products.

Here is the list of the elements of shipping tab:

* **Width**: By default it’s filled with 0.        
I set the width, carriers that does not accept products greater than this width are not displayed in front-office.        
The dimension unit displayed next to the field is the one defined in International &gt; Localization.      
To separate decimals a dot or a comma can be used, both should work no matter the language.
* **Height**: By default it’s filled with 0.      
I set the height, carriers that does not accept products greater than this height are not displayed in front-office.      
The dimension unit displayed next to the field is the one defined in International &gt; Localization.     
To separate decimals a dot or a comma can be used, both should work no matter the language.
* **Depth**: By default it’s filled with 0.     
I set the depth, carriers that does not accept products greater than this depth are not displayed in front-office.      
The dimension unit displayed next to the field is the one defined in International &gt; Localization.      
To separate decimals a dot or a comma can be used, both should work no matter the language.    
* **Weight**: By default it’s filled with 0.     
I set the weight, carriers that does not accept products greater than this weight are not displayed in front-office.     
The weight unit displayed next to the field is the one defined in International &gt; Localization.     
To separate decimals a dot or a comma can be used, both should work no matter the language.

**Comment by MatShir** [comment]
**Width, Height, Depth, Weight fields**
Decimal fields. When there is more than 15 numbers, it says "settings updated" and everything after the 15th number is not saved.

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter more than 3 numbers after the dot/comma and save, you have a success message "settings updated" but when you refresh the page, everything after the 3rd number is deleted. 

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”.

**Comment by zuk3975** [comment]
tech reminder:
These package dimensions will also occur in Carriers page, so we might need to implement some reusable Value Object (in carrier domain maybe) instead of asserting these one by one in UpdateProductShippingCommand (once we migrate carriers, those assertions will duplicate, which suggest that packageDimension should actually have dedicated VO).
TODO: think about above mentioned stuff and refactor UpdateProductShippingCommand and ProductConstraintException codes related to dimensions etc.
