### ISSUE TITLE
[Virtual Product tab] - Associated files 3/4

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19664]
As a merchant, I want to be able to manage my virtual products

**Associated files ?**: There is two radio buttons: Yes & No. By default, No is checked.      
If you check Yes, new fields are displayed:      
  * **Browse file**: You can search and upload a file. This field disappears after uploading a file and clicking on save. It’s replaced by “Download file” and “Delete this file” actions, so you can upload only one associated file.
  * **Filename**: This field is automatically completed with the name of the file uploaded, but you can edit it.
  * **Number of allowed download**: Once this number reaches, the customer can’t download the file anymore. If you try to download it, a message is displayed “You have reached the maximum number of downloads allowed.” The number of downloads allowed is displayed in the mail download\_product sent to the customer.
  * **Expiration date**: Date field. After this date, the customer can’t download the file anymore. If you try to download it, a message is displayed “Expiration date has passed, you cannot download this product.”. The expiration date is displayed in the mail download\_product sent to the customer.
  * **Number of days**: Once this number reaches, the customer can’t download the file anymore. If you try to download it, a message is displayed “The product deadline is in the past.”
  * **Delete file**: Once the file uploaded and clicking on Save, you can delete the file. When you click on “delete this file”, a modal is displayed to cancel or confirm the action. If you confirm the deletion, the file is deleted, and “delete file” and “download file” actions are replaced by the browse file field.
  * **Download file**: Once the file uploaded and clicking on Save, you can download your file.

**Comment by zuk3975** [comment]
there is also following properties that doesn't have related inputs:

- active
- is_shareable

Those properties seems to be unused, is that alright?

**Comment by MatShir** [comment]
@zuk3975, I don't find any information on any resources (1.7,1.6). It might can from an old code (a removed feature or a feature never implemented). So, it can be removed or keep it hidden, as you wish.
