### ISSUE TITLE
[SEO tab] - Redirection page 2/2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19678]
As a merchant, I want to be able to manage my SEO information for my products.

**Redirection when offline**: Dropdown with 5 options:                
1\) **Permanent redirection to a category \(301\)**: When my product is offline, I choose a category to redirect to.      
This is a "definitive" redirection and therefore this parameter is saved in the browser cache and even when I reactivate the product, the redirection can still be effective until the browser cache is cleared.       
2\) **Temporary redirection to a category \(302\)**: When my product is offline, I can choose a category to which my current product is redirected.             
The new category will only be displayed when my product is offline, it is not saved in the browser cache      
3\) **Permanent redirection to a product \(301\)**: When my product is offline, I choose another product to redirect to. This is a "definitive" redirection and therefore this parameter is saved in the browser cache and even when I reactivate the product, the redirection can still be effective until the browser cache is cleared.         
4\) **Temporary redirection to a product \(302\)**: When my product is offline, I can choose a product to which my current product is redirected.            
The new product sheet will only be displayed when my product is offline, it is not saved in the browser cache           
5\) **No redirection \(404\)**: When my product is offline, if I try to accede to the product in font-office a message is displayed: “This product is no longer available.” and the product isn’t displayed.        
If I click on Preview, I can see the product but a message is displayed “This product is not visible to your customers.”
* **Target category**: This search field is displayed if you select in the dropdown Permanent redirection to a category or Temporary redirection to a category.        
There is a placeholder: “To which category the page should redirect ?”           
If no category is selected, the Main Category is used.         
You can search by category name. When you start typing, if there are results, they are displayed under and you can click on it. Then, the selected category is displayed under the field.
* **Target product**: This search field is displayed if you select in the dropdown Permanent redirection to a product or Temporary redirection to a product.          
There is a placeholder: “To which product the page should redirect ?”              
You can search by product name or reference. When you start typing, if there are results, they are displayed under and you can click on it. Then, the selected product is displayed under the field.           
Delete selected category or product: You can remove the selected product or category by clicking on the cross. When you click on it, you have a modal to cancel or confirm the action.
* **Information message**: No redirection \(404\) = Do not redirect anywhere and display a 404 "Not Found" page.     
Permanent redirection \(301\) = Permanently display another product or category instead.     
Temporary redirection \(302\) = Temporarily display another product or category instead.

**Comment by Tanguy-SALMON** [comment]
Hey,
I case a product is definitely no longer available (for ever), I wonder about the possibility to replace an awful 404, by a far more elegant solution, an 410?

**Comment by MatShir** [comment]
Hey @Lathanao,
It seems a lot of work to have 410 which does not differ a lot from a 404. Does It mean we will have to save all the URL of the deleted products and at every request check if they have existed to flag the redirection as 410 instead of 404? I don't know if we save then. Does it have much more impact on SEO?

**Comment by Tanguy-SALMON** [comment]
Ahah, good question about the SEO! People who have tried should not be many.
It's just that there is a right code to apply in the case a product in definitely discontinued.
It is just a suggestion.
