### ISSUE TITLE
[Pricing tab] - Specific prices 3/4

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19673]
As a merchant, I want to be able to manage the prices of my products.

**Add a specific price**: You can’t add the same specific price with same conditions twice. If you try, you have an error message “A specific price already exists for these parameters.” and the second specific price isn’t created.     
This button opens a form with the following fields :      
  * **Currencies**: Dropdown with all the currencies enabled. You can select one currency or select “all currencies”, so that the specific price is available in all currencies.      
  By default, “all currencies” is selected.
  * **Countries**: Dropdown with all the countries enabled & disabled. You can select one country or select “all countries”, so that the specific price is available in all countries.            
  By default, “all countries” is selected.
  * **Groups**: Dropdown with all customer groups. You can select one group or select “all groups”, so that the specific price is available for all customer groups.             
  By default, “all groups” is selected.
  * **Customers**: There is a placeholder: “All customers”.         
  If no customer is selected, the specific price is available for all customers.      
  You can search a customer by name, Lastname, or email. Enabled customers with the corresponding name, Lastname or email address are displayed under the field.         
  When you search a customer, results are highlighted in the dropdown when using a keyboard and hover with mouse \([issue 14052](https://github.com/PrestaShop/PrestaShop/issues/14052)\). You can click, to select it.     
  If you enter something and no results are found, when you click outside the field, what has been entered is deleted. 
  You can select only one customer. 
  You can remove it by clicking on the cross. When you click on it, you have a modal to cancel or confirm the action.
  * **Combinations**: This dropdown is displayed only for a product with combinations.     
  All the combinations are listed. You can select one combination or select “apply to all combinations”, so that the specific price is available for all combinations.       
  By default, “Apply to all combinations” is selected.        
  Display the following information message under the field: "Note that if you want to base a quantity discount on a product, it will apply to all of its combinations. Go in Shop Parameters &gt; Product Settings to modify it" \([issue 12363](https://github.com/PrestaShop/PrestaShop/issues/12363)\).
  * **Available from**: Datefield. The specific price is applied only from the selected date and hour.       
  When you click on the field a calendar is displayed and you can choose a date and also hour and minutes \([improvement 11329](https://github.com/PrestaShop/PrestaShop/issues/11329)\).            
  If you enter a wrong value \(numbers or letter\), when you click outside the field, the date previously selected \(when you opened the calendar\) is completed.
  * **Available to**: Datefield. The specific price is applied until the selected date and hour.       
  When you click on the field a calendar is displayed and you can choose a date and also hour and minutes \([improvement 11329](https://github.com/PrestaShop/PrestaShop/issues/11329)\).             
  If you enter a wrong value \(numbers or letter\), when you click outside the field, the date previously selected \(when you opened the calendar\) is completed.
  * **Starting at**: Quantity from which the specific price is applied.      
  By default, it’s set to 1.         
  In front-office, the specific price isn’t displayed if this quantity isn’t reached.
  * **Product price tax excl**: To separate decimals a dot or a comma can be used, both should work no matter the language. This value changes the original product price tax excl.          
  In front-office, this price is displayed instead of the other.
  * **Leave initial price**: If the checkbox is not checked, you can fill the product price tax excl field. Otherwise, the product price tax excl field is disabled.           
  By default, the checkbox is checked. 
  * **Apply a discount of**: By default, it’s set to 0.000000         
  You can fill the discount amount or percent.          
  To separate decimals a dot or a comma can be used, both should work no matter the language.
  * **Apply a discount in**: Dropdown allowing to choose if the specific price is in amount or in percent.     
  There are 2 options: Default currency symbol & %.           
  By default, the default currency symbol is selected.
  * **Apply a discount**: Dropdown with 2 options: tax included and tax excluded.         
  It’s not displayed if you select a reduction in percent.
  * **Apply**: When you click on it, the specific price is created and you have a success message “Settings updated”.
  * **Cancel**: If you click on Cancel, the form with all specific prices fields is closed. If you click again on Add a specific price, every field are reset to their default values.
* **List of specific prices & catalog price rules**: You see the specific price with all the details: rule, combination, currency, country, group, customer, fixed price, impact, period, from, actions \(delete, update\). Rule column contains “--” for a specific price.             
Here are also listed the catalog price rules that apply to this product. The rule column contains the name of the catalog price rule.          
Actions edit & delete are not displayed for a catalog price rule.
* **Edit a specific price**: You can edit an existing specific price. It opens a modal with all the fields described above. You can close the modal by clicking on the cross, on cancel, or pushing ESC key. You can save your changes by clicking on Apply. A success message “Settings updated” is displayed.
* **Delete a specific price**: You can delete a specific price by clicking on the trash. When you click on it, you have a modal to cancel or confirm the action.

---
### - Issues in **price tab** sorted by priority high to low :
**Regression on develop**
- [x] https://github.com/PrestaShop/PrestaShop/issues/18751#event-3336713500

**Must-have**
- [ ] #12363

**Should-Have**
- [x] #21705
- [x] #22552

**Nice to Have**
- [ ]  #12911
- [x]  #20223

**Feature**
- [x] #14052

**Comment by MatShir** [comment]
**Starting at**
Integer field. If you enter more than 9 numbers and save, an error message is displayed "No reduction value has been submited."

![capture d'écran_1847](https://user-images.githubusercontent.com/13449658/61873571-92326c80-aee6-11e9-946f-4af80c772ee8.png)

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter a number with decimal (ex 30,5 or 30.5) and save, an error message is displayed "Invalid quantity"

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter anything other than numbers and save, an error message is displayed "Invalid quantity"

![capture d'écran_1848](https://user-images.githubusercontent.com/13449658/61873712-e63d5100-aee6-11e9-9c46-c7afaea789da.png)

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

**Impact on product price tax excl**
Decimal field. If you enter more than 10 numbers before the dot/comma and save, an error message is displayed "Invalid price/discount amount"

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter anything other than numbers and save, the specific price is created with a product price tax excl at 0€

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter more than 6 numbers after the dot/comma and save, the specific price is create and everything after the 6th number is deleted

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

**Apply a discount of**
If you enter more than 10 numbers before the dot/comma and save, an error message is displayed "Invalid price/discount amount"

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter anything other than numbers and save, an error message is displayed "No reduction value has been submited"

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”. 

If you enter more than 6 numbers after the dot/comma and save, the specific price is create and everything after the 6th number is deleted 

- [ ] Instead of this, we should have an error displayed under the field: “This value is not valid”.

**Comment by MatShir** [comment]
### - Issues in **price tab** sorted by priority high to low :
**Regression on develop**
- [x] https://github.com/PrestaShop/PrestaShop/issues/18751#event-3336713500

**Must-have**
- [ ] #12363

**Should-Have**
- [ ] Add dates (add / update) onto specific prices #21705
- [ ] #22552

**Nice to Have**
- [ ]  #12911
- [x]  #20223

**Feature**
- [x] https://github.com/PrestaShop/PrestaShop/issues/14052

**Comment by kmorgen** [comment]
For some reason the Specific Prices have never got the time/hour settings back in PS 1.7

It is quite frustrating not beeing able to make one-day offers for Black Friday etc here anymore.

In voucher/discount settings the Time section works fine, so maybe there is a quickfix/mod to get it to work again in Specific Prices too?

![specific-prices-time](https://user-images.githubusercontent.com/4300688/143232556-62bc659e-ab27-4077-ac11-538e6d196728.png)
