### ISSUE TITLE
vendor/phpoffice/phpexcel/ can I delete these ?

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#19675]
In the BO of my shop I can find a liost of changes files.
In this list there are many that start with:

vendor/phpoffice/phpexcel/

What are they for as I don't use any Excel with PS and can I delete them all ?

**Comment by matks** [comment]
PrestaShop is able to import data from Excel files as well as CSV files which is why it has these files.

Removing these files might break your "Import" page 🤔 however you should check why they appear as "changed"

**Comment by frevab** [comment]
I never import data from Excel file so there also no reason why these files appear as "changed" unless a PS update changed them.
As long as they cannot be misused. I read somewhere something about files in the vendor folders but I guess these are save.

**Comment by matks** [comment]
Don't worry you are probably safe. The "files in vendor folder" you are talking about is https://build.prestashop.com/news/critical-security-vulnerability-in-prestashop-modules/ but I dont think it's the same issue

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
