### ISSUE TITLE
Order number as an order reference

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19688]
#### Is your feature request related to a problem?
Very often companies want to use value of an order number as "Order Reference" in an invoice. They want to use the Order Reference - without leading zeroes, without any characters, without year (e.g: Order Reference = 1020). It is common that this reference is often used also in bank transfer as a payment reference number which is required for clearing, searching.... In our local bank transfers can't be used characters as the payment  reference number.

#### Describe the solution you'd like
We'd like to have a configuration that order number will be used as the Order Reference (without leading zeroes, without any characters, without year ) in the order. It would replace current character values in Order Reference (e.g. ASDFG1POL) and it would be used in BO, invoices, credit memos, emails.... as Order Reference.

#### Additional context
Example
![image](https://user-images.githubusercontent.com/33311857/84259080-38e02580-ab18-11ea-8e8f-08dd6ec624ff.png)

**Comment by TristanLDD** [comment]
Hi @juraj1000, thanks for your report. 

We'll discuss about this improvement with the product team and come back to you as soon as possible. 

Thank you

**Comment by Hlavtox** [comment]
@juraj1000 Look at this and vote for it, we need to pull PS team of the "lettered order reference is a great idea" bubble 🗡️ 😄 https://github.com/PrestaShop/PrestaShop/issues/13212 https://github.com/PrestaShop/PrestaShop/issues/18295

**Comment by juraj1000** [comment]
How can I vote for it?

**Comment by marionf** [comment]
@juraj1000 your issue is a duplicate of #13212, please follow this issue and comment on it if needed

**Comment by marionf** [comment]
Duplicate of #13212
