### ISSUE TITLE
Fixtures are always installed when using the CLI installer

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#19696]
## Describe the bug

When you use the CLI installer (`install-dev/index_cli.php`) to install a shop, there is no option to disable the fixtures installation.

#### Expected behavior

There should be a parameter to disable fixture installation when using the CLI install script.

#### Steps to Reproduce

1. launch the `install-dev/index_cli.php` with your relevant parameters to silently install a shop
2. fixtures are installed by default
3. there is no parameter to avoid that

This is my script installation parameters:
```sh
php index_cli.php \
--language='en' \
--country='fr' \
--domain='localhost' \
--base_uri='/prestashop/' \
--db_name=prestashop \
--db_user=root \
--db_password=melon \
--password=prestashop_demo \
--email=demo@prestashop.com
```

#### Additional information

* PrestaShop version: `develop` but seems to be like that since a few versions
* PHP version: doesn't really matter, but tested in 7.2

**Comment by Progi1984** [comment]
@SimonGrn I just check on `develop` branch :

```
php install-dev/index_cli.php \
	--language=en \
	--country=fr \
	--domain='127.0.0.1' \
	--base_uri='/PrestaShop/' \
	--db_server=127.0.0.1 \
	--db_user=root \
	--db_password=root \
	--db_name=prestashop \
	--step=database,fixtures,theme,modules,addons_modules
-- Installation successful! --
```
** I have fixtures **

```
php install-dev/index_cli.php \
	--language=en \
	--country=fr \
	--domaine='127.0.0.1' \
	--base_uri='/PrestaShop/' \
	--db_server=127.0.0.1 \
	--db_user=root \
	--db_password=root \
	--db_name=prestashop \
	--step=database,theme,modules,addons_modules
-- Installation successful! --
```
** I have no fixtures **

**Comment by eternoendless** [comment]
@SimonGrn Are you perchance installing in prod mode?

**Comment by SimonGrn** [comment]
Indeed I am.
It's weird to have to specify *all* the steps except `fixtures`to not have them, but I guess this is intended that way.

**Comment by eternoendless** [comment]
How about we added a `--no-fixtures` option as a shortcut?

**Comment by SimonGrn** [comment]
You devs know better than me what would be a good option, I'll let you choose 😄 
I tried to find some documentation about this script and [found this ](http://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script) but it doesn't explain what are the steps (also pretty sure the default values are wrong ?).

**Comment by Progi1984** [comment]
Added an option `--fixtures(=0/=1/)` in #19757
