### ISSUE TITLE
Missing data on product listing with Faceted Search

### ISSUE THREAD

**Issue by iqit-commerce** [PrestaShop/PrestaShop#19691]
#### Describe the bug

When ps_facetedsearch(latest 3,5,0 version) module is enabled in removes some products variable which are normally avaiable for category listigns or others. Also in older version of ps_facetdesearch it was working fine

#### Expected behavior
should return variable value
#### Steps to Reproduce

Add {$product.manufacturer_name} in themes > template name > template > catalog > _partials > miniatures > product.tpl
Activate faceted search filter in left column in category page

when it is activated manufactureer name is not showed, when it is deactivated it works.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
* Ps_facetedsearch: 3.5.0

**Comment by TristanLDD** [comment]
Hi @iqit-commerce, thanks for the report

@PierreRambaud have you heard about this problem on the faceted search module?

**Comment by iqit-commerce** [comment]
Hello @TristanLDD and @PierreRambaud . Were you able to reproduce this bug?

**Comment by PierreRambaud** [comment]
@iqit-commerce I'm not able to reproduce the problem, could you send me a video or screenshot for a better understanding?

**Comment by iqit-commerce** [comment]
@PierreRambaud It seems to be not actuall anymore with latet ps 1.7.6.7 realase

**Comment by MamaTux** [comment]
I have this exactly bug on a PS 1.7.6.8 I hoped to release tomorrow!
When I disable the ps_facetedsearch module (version 3.6.0) I get the manufacturer name in the product listings. When I enable it, they are gone :(

**Comment by MamaTux** [comment]
@iqit-commerce I use the latest version of Warehouse theme - can you reproduce it?
