### ISSUE TITLE
Two confidentiality checkbox on customer sign-up

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#19705]
On a fresh 1.7.7 beta 1 install on php 7.2, there is two checkbox for confidentiality at customer creation time.
Let's see this 
![double-confidentialite](https://user-images.githubusercontent.com/16720275/84298857-1669fe80-ab50-11ea-9d0f-f22fb60c66f5.png)

**Comment by Matt75** [comment]
Due to https://github.com/PrestaShop/ps_legalcompliance

**Comment by florine2623** [comment]
Hi @jf-viguier ,
In GDPR module, you can choose to display or not this checkbox :
![Capture d’écran 2020-06-11 à 12 17 28](https://user-images.githubusercontent.com/16019289/84373952-98543900-abdd-11ea-9182-d1c373d134d9.png)
Thanks!
