### ISSUE TITLE
Add new UI kit for cards in MBO

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#19702]
The new ui for cards has been integrated in the core, it would be a nice improvement to add it in MBO too.

See the initial issue here : https://github.com/PrestaShop/PrestaShop/issues/16608

**Comment by Matt75** [comment]
MBO didn't use UIKit yet, currently MBO reuse only Core components

**Comment by marionf** [comment]
I close this issue as MBO isn't in the scope of the core
