### ISSUE TITLE
Recompile CSS with CCC activated

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#19700]
#### Describe the bug

I have activated Smart cache some months ago to improve performance.
Since I made this, when I clear cache from back office, it takes about 10 minutes to recompile, and the front is unavailable during this time.

So now if I do some modification in tpl files, I clear the cache manually by deleting folder var/cache/prod.

But if I do modifications on css files, it's not recompiled.
Can I clear manually css cache files ?

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by TristanLDD** [comment]
Hi @guigplt, thanks for your report

Could you be more precise about the steps to reproduce your issue please ? 
Thank you

**Comment by guigplt** [comment]
In Advanced paramaters > Performances, activate smart cache for stylesheet.
(I also activated smart cache for javascript and Apache optimization).

Then I click on Clear cache button.
Sometimes it takes 5-6 minutes, sometimes 10 minutes to recompile, and the website is unavailable during this time.

So my question is : can I clear css cache files in themes/[theme_folder]/assets/cache ?

**Comment by florine2623** [comment]
Hi @guigplt ,
You can delete them manually, just keep the index.php file in the folder.
Thanks!

**Comment by guigplt** [comment]
Hi,
Thanks for your reply.
I have tested it yesterday by deleting only the css cache file concerned, and it worked, the cache file is regenerated when I refresh the page.
