### ISSUE TITLE
Add best sellers to the sort filter inside categories when using ps_facetedsearch

### ISSUE THREAD

**Issue by dgonzalez360** [PrestaShop/PrestaShop#19719]
It would be nice to sort products inside the category by best sellers. 

I have made the change and created a pull request, it's available at 

https://github.com/PrestaShop/ps_facetedsearch/pull/172

Can this be included in the next releases? What else should I do to include this change?

**Comment by Hlavtox** [comment]
Hi @florine2623, maybe you can merge it with my feature request? https://github.com/PrestaShop/PrestaShop/issues/17136

@dgonzalez360 I will test the PR and let you know! 🚀

**Comment by marionf** [comment]
Duplicate of #17136

**Comment by marionf** [comment]
Thank you for the PR @dgonzalez360, I closed this issue because it's a duplicate
Please follow and comment on the other issue mentionned above
