### ISSUE TITLE
Cannot access Stock BO page for user which is not super-admin on 1.7.6.5 (or translation admin)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19713]
#### Describe the bug

On 1.7.6.5, a user who is not super-admin cannot access "Stock" page EVEN if I give him the necessary rights.

Bug reported by Mads Oliver Jenssen on open source slack

#### Expected behavior

People who have the right access should be able to access the page 😄 

#### Steps to Reproduce

1. Install 1.7.6.5
2. Modify "Logistician' employee profile, give him all accesses to "Stock" page
3. Create new employee, assign him the "Logistician" profile
4. Login as new employee, try to access 'Stock page'
- on first attempt: blank page
- if you refresh, you see a hundred of "access denied" messages

**Screenshots**

<img width="567" alt="Capture d’écran 2020-06-11 à 15 32 42" src="https://user-images.githubusercontent.com/3830050/84391128-d6ab2180-abf8-11ea-8473-c47dda264b21.png">

#### Additional information

In "Network" tab in developer tools I see hundred of ajax calls to URL `http://localhost/admin/index.php/api/i18n/admin_domain` with HTTP response 302

<img width="504" alt="Capture d’écran 2020-06-11 à 15 33 41" src="https://user-images.githubusercontent.com/3830050/84391257-03f7cf80-abf9-11ea-8cf2-57e4bf865979.png">

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by matks** [comment]
Issue comes from  `PrestaShopBundle\Controller\Api\I18nController::listTranslationAction()` security config  `* @AdminSecurity("is_granted('read', request.get('_legacy_controller'))")`

**Comment by PierreRambaud** [comment]
@matks The real issue is not here :sweat_smile: 
The problem is the Stock page requires translations, to retrieve these translations you need to have Translations permissions which is logic. 
Otherwise, if you remove this check, anyone is able to retrieve all translations which is a security issue.

As a workaround, he can give translations read access.

**Comment by eternoendless** [comment]
What does the stock page have to do with the translations page?

**Comment by matks** [comment]
> What does the stock page have to do with the translations page?

There are ajax API calls being fired by Stocks page towards API endpoint `/api/i18n/{page}` and if BO user does not have access to Translation BO page, these API calls are being refused (response is HTTP 302) which make the Stocks page crash

This is a design error in the security of the page.

Also Stocks page crash in a hard way instead of providing some nice error message

**Comment by eternoendless** [comment]
Okay, however I can't see any reason to enforce access restrictions for reading translations once the user is logged in.

**Comment by PierreRambaud** [comment]
> Okay, however I can't see any reason to enforce access restrictions for reading translations once the user is logged in.

We should add a comment above the API endpoint to explain why there are no access restrictions.
Translations can contain sensitive data (yes already seen people writing private data like email, phone number, etc in translations and it helps for social engineering ^^)

**Comment by colinegin** [comment]
Does @PierreRambaud 's PR fixes this issue ?

**Comment by matks** [comment]
> Does @PierreRambaud 's PR fixes this issue ?

Yes

I update this PR status

**Comment by Progi1984** [comment]
Fixed in 176x #19718 & 177x #19716
