### ISSUE TITLE
Wrong order total when cancelling a product on an order having cart rules

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#19717]
#### Describe the bug
There is a bug when canceling a product from an order having cart rules, order total is wrong.

Also this block should not be displayed when canceling a product:
<img width="845" alt="Capture d’écran 2020-06-11 à 15 20 18" src="https://user-images.githubusercontent.com/1784781/84403377-ea10b980-ac05-11ea-9625-58a353259bfc.png">

And the reduction values table is not updated.

#### Expected behavior
Canceling a product (quantity: one) should have the same impact as deleting it. Cart rules reduction values should be updated and the order total to be paid should be the same.

#### Steps to Reproduce

1. In FO, create an order with 2 products (quantity one for each product), go through completion of the order
2. In FO, create a second order, the exact same order: with the 2 same products and quantity of one for each product.
3. In BO, go the order detail page of the first order you created, and delete one product.
4. In BO, go to the second order you created and cancel one product.

**There are 3 problems:**
- The two orders end up with two different total order values.
- In both cases, the reduction amount table is not updated
- When canceling a product, this block appears (it should only appear for refunds)
<img width="845" alt="Capture d’écran 2020-06-11 à 15 20 18" src="https://user-images.githubusercontent.com/1784781/84403377-ea10b980-ac05-11ea-9625-58a353259bfc.png">

**Comment by matthieu-rolland** [comment]
this issue is linked with the product deletion refactor in this issue #18432 , I'll deal with both in the same PR.

**Comment by Hlavtox** [comment]
Hi @matthieu-rolland, 

didn't you think about just ditching the old logic and just recalculate the whole order with every change in BO? 

I think it will save you an insane amount of hassle. There are so many conditions that you need to check when doing anything with the order...

https://github.com/PrestaShop/PrestaShop/issues/17769

**Comment by matthieu-rolland** [comment]
@Hlavtox the issue we have right now is we have a different logic for: updating product quantity, doing a cancel product, and doing a delete product, when in all cases this is a change a quantity. @sowbiba have been working on a service dealing with quantity update and re-calculations of all things needing changement (cart rules update, product weights updates, shipping cost updates, etc...)

We're working on this.

**Comment by colinegin** [comment]
Related to #18432

**Comment by Progi1984** [comment]
Fixed by #19981 (@matthieu-rolland)
