### ISSUE TITLE
Logo upload failiure

### ISSUE THREAD

**Issue by drqp1983** [PrestaShop/PrestaShop#19723]
When I went to the Theme & logo section and tried to upload theme logos and favicon I clicked save and it sent me to Error screen: The server returned a "500 Internal Server Error".

#### Expected behavior

It should have saved the changes and take me back to the Theme & logo section.

#### Steps to Reproduce

1. Go to 'Design'
2. Click on 'Theme & logo'
3. On header, logo click on browse
4. Select the logo file "jpeg"
5. Click Save
6. See Error screen

**Screenshots**
![1](https://user-images.githubusercontent.com/66806621/84449598-1d097c00-ac0b-11ea-93c2-0ca294ea65c2.jpg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 5.6

**Comment by drqp1983** [comment]
What should I do? I already tried uninstalling and installing Prestashop. It did not fix the issue.

**Comment by florine2623** [comment]
Hi @drqp1983 ,

Please, change your admin link, this is a public space, let's be careful !

Now, what version of PHP are you using ?

Can you enable debug mode and see what error is displayed.
Advances Parameters > Performance > Debug YES
Or manually if you don't have access to that page :
In config/defines.inc.php, change :
`define('_PS_MODE_DEV_', false);`
to
`define('_PS_MODE_DEV_', true);`

Thanks!

**Comment by drqp1983** [comment]
You are right, thank you for pointing it out!!! I'll change it.

Ok, I will check what you instructed.

**Comment by drqp1983** [comment]
Ok, the php version is 5.6
Here is the erro shown
![image](https://user-images.githubusercontent.com/66806621/84546449-a0d07080-acbe-11ea-9121-e0c35dd10d63.png)

**Comment by drqp1983** [comment]
Hello, Can you help me fix this issue? - I already changed my admin link.

**Comment by drqp1983** [comment]
Hello, apparently I was trying to upload a larger than allowed file. Thank you!! for your help.
