### ISSUE TITLE
issues after php version upgrde(7.2)

### ISSUE THREAD

**Issue by augustinejenin** [PrestaShop/PrestaShop#19724]
#### Describe the bug

my prestashop version is 1.6 and we upgrder server php version to 7.2 . now we got soe errors. Is prestashop 1.6 not working with php 7.2? do we need to upgrade prestashop to 1.7?

error:
Warning: count(): Parameter must be an array or an object that implements Countable in /home/..
![presta](https://user-images.githubusercontent.com/26268454/84466646-78814b80-ac97-11ea-8f16-1fdf12f01fbd.png)
/public_html/ingeniopresta/controllers/front/ProductController.php on line 254

#### Expected behavior

need to remove the bugs.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.6
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @augustinejenin ,

Prestashop 1.6 is available with PHP 7.1 max. You can check this doc : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

If you need help migrating your site, please contact our support team here : https://www.prestashop.com/en/support

Thanks!
