### ISSUE TITLE
Missing remove link button in product description editor

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#19726]
Hello, 
in prestashop 1.5 i had a button to remove the links in the product description editor, now in prestahsop 1.7 i have to enter the link and remove the url, it'0s possible to implement the remove link button in ps 1.7 ? How ? Thanks

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @Gipielle ,
Here's how to do it :
https://drive.google.com/file/d/1UIpoeDC2gbZO07IlgiJinhzFJGZ24GYw/view

Thanks!

**Comment by Gipielle** [comment]
Hello, 
sorry but maybe I said that badly, i know how to do it, but, with prestashop 1.5 i have only to click to a bottun for disable the link, without enter and delete the url 
<img width="335" alt="Schermata 2020-06-12 alle 14 09 41" src="https://user-images.githubusercontent.com/53569015/84501238-78dd0f00-acb6-11ea-886f-38b1e446b3b1.png">

**Comment by florine2623** [comment]
We do not do support here. This is a bug report/improvement platform.

If you need customized help, please contact the support : https://addons.prestashop.com/en/388-support
