### ISSUE TITLE
V1.7.6.5 - Dropdowns, Connections & Error

### ISSUE THREAD

**Issue by twoex** [PrestaShop/PrestaShop#19720]
Hey everyone,

Did a fresh install and I have noticed some issues with the latest version.. not sure if everyone is experiencing this as well, but I have tried in several browsers & systems and the issue is there (for me)..

The following areas I am seeing with broken drop down lists;

**========= 1. DROP DOWN MENU ISSUES =========**
**[SELL SECTION]**
**[ORDERS]** Invoices :  Invoice Model 
**[CATALOG]**  Products > Basic Settings : Drop down beside Product Name in header
**[CATALOG]** Categories > Displayed Column
**[CATALOG]** Brands & Suppliers > Enabled Column
**[CUSTOMERS]** Social Title, Enabled, Newsletter, Partner Offers
**[CUSTOMERS]** Edit Customer > Birthdate, 

**[IMPROVE SECTION]**
**[Email Theme]** > All drop down items
**[Email Theme]** > Pages > Displayed columns
**[Shipping]** > Preferences > Carrier Options Section
**[International]** > Taxes : Enabled Column & Based on under tax options
**[International]** > Translations : Drop downs under Modify, Export, Copy

**[SHOP PARAMETERS]**
**[General]** Round mode, Round type, Main shop activity, 
**[Order Settings]** page for terms and conditions and gift wrapping tax
**[Product Setting]** Quantity discounts based on, Default pack stock management, Default order by , Default order method 

**[ADVANCED PARAMETERS]**
Template Compilation, Caching type, Clear cache
**E-mail:** Language column, Send emails to
**Email SMTP Section:** All content is shifted outside the bounding box
**Import:** What do you want to import, 
**Employees** : Profile, Active
**Database** : Select your default file encoding
**Webservice**: Enabled

I have attached an image to show one section of what it looks like;

![PS - Drop Down](https://user-images.githubusercontent.com/66793225/84419013-fa18a100-abe5-11ea-933e-ab31dd95b18b.png)

**========= 2. CONNECTION ISSUE  =========**
**Theme Catalog** says : trouble connecting to addons

**========= 3. DUPLICATING PRODUCT =========**
- page has a broken smart template, shows all the tabs listed under the entire first page as you scroll
- when saving the product says unable to save product
- The CSRF token is invalid. Please try to resubmit the form.

**========= 4. EMAIL Section under Advanced =========**
- 3rd bounding box has content outside of the box and runs under the menu

**========= 5. Design & Theme Logo =========**
- was unable to click browse and select image to replace the logo

That is so far what I have found... hopefully I this post isn't too long and is somehow helpful.

Thank you

[ UPDATE ]
So this issue only happens if you try and setup PrestaShop to be under a subdomain.. if I switch it to be the top level, it works fine... (e.g. shop.address.com vs address.com)

**Comment by florine2623** [comment]
Hi @twoex ,
Thanks for the thorough message !

1. DROP DOWN MENU ISSUES 
Can you make sure the system requirement for PrestaShop are met :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

2. CONNECTION ISSUE
Make sure you don't have a firewall that block the connection to Addons

3. DUPLICATING PRODUCT
Here's my screen record to duplicating a product : 
https://drive.google.com/file/d/1mZs4yIAC5tvDOOn6PB4eVdjJDCi6NuXg/view
I don't see the issue, could you specify it with screenshots ?

4. EMAIL Section under Advanced
The e-mail page on my test shop is fine. Make sure the PHP version you are using is compatible with PS 1.7.6.5

5. Design & Theme Logo
https://drive.google.com/file/d/1MV69UDF_EyHTbo6X9KPo7kLuX4yQKAd8/view

Thanks again for your report. Please check and let me know if everything is good on your side.

**Comment by cutteren** [comment]
Hi i have the same problem here, thanks to TWOEX for this explanation. Did anybody come up with a solution?  Ive tried in all the browsers available and reinstalled it all so many times now. same problem still.

**Comment by florine2623** [comment]
Hi @cutteren 
Try to install PrestaShop with a compatible version of PHP.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by cutteren** [comment]
> Hi @cutteren
> Try to install PrestaShop with a compatible version of PHP.
> https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> Thanks!

thank you, i uploaded this file to my server and tried it, but it wont let me login when running that php file. i use the password that is given in the readme but no luck. My php should be working tho

**Comment by florine2623** [comment]
You just need to enter `prestashop` for both login and password

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
