### ISSUE TITLE
Email configuration - missing checkboxes on PS 1.7.7.0 beta 1

### ISSUE THREAD

**Issue by MDWeb-Lille** [PrestaShop/PrestaShop#19728]
#### Describe the bug

The checkboxes are missing in the configuration for sending emails

#### Expected behavior

There should be checkboxes to select either the sending format (HTML, text or both) and also the sending function (mail, SMTP, don't send mail, etc.).

#### Steps to Reproduce

1. Go to back office
2. Click on "Advanced parameters"
3. Click on "E-mail"
4. See problem

**Screenshots**

![image__6_](https://user-images.githubusercontent.com/3178858/84501838-7dee8e00-acb7-11ea-83fe-b2f0f885d685.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.9
* Browsers : Firefox, Chrome, Safari

**Comment by florine2623** [comment]
Hi @MDWeb-Lille ,

There are present :
![Capture d’écran 2020-06-12 à 15 08 26](https://user-images.githubusercontent.com/16019289/84505748-957d4500-acbe-11ea-872e-9745fed02e9a.png)

Can you make sure you follow these system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
