### ISSUE TITLE
ps_shoppingcart: the number of products does not update in the basket

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#19733]
#### Describe the bug

On any version of PrestaShop 1.7, when you add products to the shopping cart and display this cart, if you change the quantity of products, the number of products displayed by the cart in blue n top right is not updated in real time.

#### Expected behavior

Normally, the number of products in the basket must correspond in real time to the number of products in the basket.

**Screenshots**

## First status, display of the basket with products

![Capture d'écran 2020-06-12 18 13 32](https://user-images.githubusercontent.com/595633/84523456-a470f100-acd8-11ea-9c41-304337d6fea7.jpg)

## Second step, we change the quantities of the products but the total number of products in the basket is always the same.
![Capture d'écran 2020-06-12 18 13 54](https://user-images.githubusercontent.com/595633/84523575-ccf8eb00-acd8-11ea-989b-07f2dbb323f6.jpg)

## And after refreshing the browser window the shopping cart shows the correct total quantity.
![Capture d'écran 2020-06-12 18 14 06](https://user-images.githubusercontent.com/595633/84523628-e8fc8c80-acd8-11ea-9af1-7ee60e425cce.jpg)

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by jf-viguier** [comment]
This bug is in 1.7.7 beta 1 too.

**Comment by jeckyl** [comment]
This bug is already fixed
[https://github.com/PrestaShop/ps_shoppingcart/blob/1.7.0.x-prev/ps_shoppingcart.js](https://github.com/PrestaShop/ps_shoppingcart/blob/1.7.0.x-prev/ps_shoppingcart.js)

**Comment by jeckyl** [comment]
https://github.com/PrestaShop/ps_shoppingcart/pull/59

**Comment by matks** [comment]
PR approved https://github.com/PrestaShop/ps_shoppingcart/pull/59 waiting for QA now

**Comment by matks** [comment]
PR merged, this bug will be fixed by next release of ps_shoppingcart module https://github.com/PrestaShop/ps_shoppingcart/pull/59
