### ISSUE TITLE
List of native 1.6 modules available, or not, for 1.7 and how can I migrate a data...

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#19735]
Dear staff,
we are going to migrate to the 1.7.X version finally.
**Preamble**
we had to migrate to 1.7 and not update, because we tried to update but it didn't work unfortunately.
***
While using 1.6, we activated some native free modules into the module section. 
Some of these have implemented useful functions for the management of the e-commerce site, but are no longer available in 1.7.x version, an example:
**Loyalty and rewards points module**
I didn't find it in the free version even in the paid one (I mean the same module, I know there are other paid module to do that).
Another example:
**Wishlist module**
This one too I didn't find.
**My question is:**
is there a list of modules that are no longer available into 1.7 version?
If yes, where I can find it?
**My second question is:**
Can the data contained in the database linked to those modules used but no longer available be migrated to the new 1.7?
Some clients had gained loyalty points, they risk to lose them?
For wishlist too?
Thanks a lot for any reply.
E.

**Comment by matks** [comment]
For Wishlist module, there is currently a massive rework happening into the `new-module` branch https://github.com/PrestaShop/blockwishlist/tree/new-module

The output of this rework will be a new version of wishlist module, compatible with 1.7

For "loyalty and reward" points I dont know, let's wait for more people answers

**Comment by ballashop** [comment]
HI @matks thanks a lot for your reply.
Do you know a link that shows the list of modules no longer used on 1.7?
Thanks a lot.
E.

**Comment by Matt75** [comment]
New version of wishlist module will keep your previous data. **Please note this new version will be compatible only 1.7.7+**

No new native version for loyalty module but you can find modules on Addons will keep your data from 1.6 : https://addons.prestashop.com/fr/recherche?search_query=Loyalty

All others native modules should be available on 1.7 if I don’t miss one

**Comment by matthieu-rolland** [comment]
Hi @ballashop , check this out:

https://devdocs.prestashop.com/1.7/modules/introduction/#main-differences-between-1-6-and-1-7-modules

I close this issue.

**Comment by ballashop** [comment]
HI @Matt75 
thanks a lot, do you know how we can migrate data from 1.6 to 1.7?
@matthieu-rolland 
Thanks a lot for the link.

**Comment by Matt75** [comment]
@ballashop modules migrate data automatically

**Comment by ballashop** [comment]
@Matt75 
thanks to reply so fast, unfortunately we had to use a module migration to migrate form 1.6 to 1.7 version. So we need to migrate data in other way then the update one.
If you have any suggestions it would be fantastic, thanks a lot.

**Comment by Matt75** [comment]
You have to check tables used by module in your previous database then export it

**Comment by ballashop** [comment]
@Matt75 
thanks a lot, I'll check asap.
