### ISSUE TITLE
you cannot delete a file that has been uploaded to a product 

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#19737]
#### Describe the bug

you cannot delete a file that has been uploaded to a product file

#### Steps to Reproduce

1. Go to options
2. Click on Attached files
3. upload a file
4. Save
5. See error (can´t delete it)

**Screenshots**

<img src="https://image.prntscr.com/image/bauMVvzJRzuevsLZSUKKXg.png" />

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.32

**Comment by matthieu-rolland** [comment]
@alfonsolr09 I didn't reproduce your issue on 1.7.6.4:

To detach the file from the product (so that it doesn't appear on the product page), just uncheck the checkbox.

To delete the file, go to the "Files" page in BO, select the file and delete it.

I close this issue.

**Comment by alfonsolr09** [comment]
thats perfect!! thankss
:)
