### ISSUE TITLE
Original invoice number in credit slip

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19731]
#### Describe the bug
If an e-shop company creates a credit slip there must be printed also number of Original invoice in credit slip pdf, it is a legal requirement.

#### Expected behavior
Could you add Original invoice number to the credit slip pdf?

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19707
