### ISSUE TITLE
Selling price on product page

### ISSUE THREAD

**Issue by dasafefe** [PrestaShop/PrestaShop#19734]
My shop version is 1.7.6.5. 
When we create a new product, the selling price doesn't show up on the product page. Any help to fix it?

**Comment by matthieu-rolland** [comment]
Hi @dasafefe , I didn't reproduce your issue on 1.7.6.5, however:

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you!

**Comment by dasafefe** [comment]
Resent again as the previous email returned.


-------- Forwarded Message --------
Subject: 	Re: [PrestaShop/PrestaShop] Selling price on product page 
(#19734)
Date: 	Wed, 17 Jun 2020 13:05:04 +0800
From: 	acool <cs@acool.global>
To: 	PrestaShop/PrestaShop 
<reply@reply.github.com>, 
Matthieu Rolland <notifications@github.com>
CC: 	Mention <mention@noreply.github.com>



Hi Matt,

Below please find the information and we have attached the video for 
this problem as well:

 1. server setup and configuration:

  * Operating system: Linux #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64
  * Type and version of webserver (Apache, Nginx, IIS, other): Apache/2
  *   Version of PHP: 7.3.14
  * Version of MySQL/MariaDB: 10.4.12-MariaDB/InnoDB

     2. PrestaShop version (source) : 1.7.6.5

     3. Browser setup: Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

    4.  Current theme in use: classic

    5.PHP error logs/apache error log: no error message

    6. Console log:

D1

   7.  Screen shot

D2

    8. Video: when we refresh the browser, the selling price appears for 
a very short time and disappears again.

We have found that this problem only happen to Simple Product. Noted in 
your Demo PrestaShop, those simple products have got the selling price 
on the product page but we have deleted all the pre-built in simple 
products. As we are quite in an urgent case, please advise whether & how 
we could reinstall the sample simple products (those in your demo 
prestasshop) that we could edit it to test. Please advise.


Regards,

@dasafefe

**Comment by florine2623** [comment]
Hi @dasafefe ,

Please answer only via GitHub and not by email.
The version of PHP is not compatible with your version of PrestaShop. PS 1.7.6.5 should be used with PHP 7.2, not 7.3. Please downgrade it and let me know if you still face the issue.
You can also check PrestaShop system requirements here: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by dasafefe** [comment]
Hi,
We have tried PHP 7.2, the problem still exists. It only happens to Simple Product. Please advise what to do next. Thanks

**Comment by florine2623** [comment]
You need to check if catalog mode is enable.
Shop parameters > Product settings :
![Capture d’écran 2020-06-19 à 14 17 16](https://user-images.githubusercontent.com/16019289/85131723-a6d2ce00-b237-11ea-8814-fe85e39cfdf1.png)

**Comment by dasafefe** [comment]
Yes, we have enabled it.
![catalog mode](https://user-images.githubusercontent.com/66122115/85189027-b99fde00-b2dd-11ea-95a0-b74eaf8dcd07.JPG)

**Comment by dasafefe** [comment]
Please advise whether & how we could reinstall the sample simple products (those in your demo
Prestashop) that we could edit it to test.

**Comment by PierreRambaud** [comment]
@dasafefe We are not able to reproduce the issue with the default classic theme. If you bought a custom theme, you should see it with the creator.

**Comment by sarahdib** [comment]
@dasafefe 

You need to disable catalog mode in order to see the price in the front office.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
