### ISSUE TITLE
Manual changes for shipping cost in BO

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19742]
#### Describe the bug
Sometimes we want to create an order in BO and we can't use any shipping price which is defined in BO, we've to use an individual shipping price. But it is not possible to edit the shipping price in BO.

#### Expected behavior
The shipping price would be possible to edit and change.

#### Steps to Reproduce
BO > Orders > Orders > detail info > section Shipping > Shipping cost

**Screenshots**
![image](https://user-images.githubusercontent.com/33311857/84603963-0bd2a080-ae93-11ea-948a-cda0b5c7840e.png)

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by matthieu-rolland** [comment]
It seems like this is a feature request rather than a bug. Please re-create this issue as a feature request:  https://github.com/PrestaShop/PrestaShop/issues/new/choose
