### ISSUE TITLE
Wrong payload sent when saving import configuration

### ISSUE THREAD

**Issue by joemugen** [PrestaShop/PrestaShop#19746]
#### Describe the bug

When saving the import configuration, everything seems to be fine but when you're back on this screen later, you will see an "undefined" choice in the select instead the name of your saved configuration.
And when you load it, each fields will be set to `undefined`.

If you look at the network tab and more precisely on the payload sent when you save the configuration, you will see this:

```
ajax	"1"
action	"saveImportMatchs"
tab	"AdminImport"
token	"ee20d0f98a45013400a34a36bd0e4ea6"
skip	"1"
newImportMatchs	"undefined"
type_value[0]	"undefined"
type_value[1]	"undefined"
type_value[2]	"undefined"
type_value[3]	"undefined"
type_value[4]	"undefined"
type_value[5]	"undefined"
type_value[6]	"undefined"
type_value[7]	"undefined"
type_value[8]	"undefined"
type_value[9]	"undefined"
type_value[10]	"undefined"
type_value[11]	"undefined"
type_value[12]	"undefined"
type_value[13]	"undefined"
type_value[14]	"undefined"
type_value[15]	"undefined"
type_value[16]	"undefined"
type_value[17]	"undefined"
type_value[18]	"undefined"
type_value[19]	"undefined"
type_value[20]	"undefined"
type_value[21]	"undefined"
type_value[22]	"undefined"
type_value[23]	"undefined"
type_value[24]	"undefined"
type_value[25]	"undefined"
type_value[26]	"undefined"
type_value[27]	"undefined"
type_value[28]	"undefined"
type_value[29]	"undefined"
type_value[30]	"undefined"
type_value[31]	"undefined"
type_value[32]	"undefined"
type_value[33]	"undefined"
type_value[34]	"undefined"
type_value[35]	"undefined"
type_value[36]	"undefined"
type_value[37]	"undefined"
type_value[38]	"undefined"
type_value[39]	"undefined"
type_value[40]	"undefined"
type_value[41]	"undefined"
type_value[42]	"undefined"
type_value[43]	"undefined"
type_value[44]	"undefined"
type_value[45]	"undefined"
type_value[46]	"undefined"
type_value[47]	"undefined"
type_value[48]	"undefined"
type_value[49]	"undefined"
type_value[50]	"undefined"
type_value[51]	"undefined"
type_value[52]	"undefined"
type_value[53]	"undefined"
type_value[54]	"undefined"
type_value[55]	"undefined"
type_value[56]	"undefined"
type_value[57]	"undefined"
type_value[58]	"undefined"
type_value[59]	"undefined"
type_value[60]	"undefined"
type_value[61]	"undefined"
type_value[62]	"undefined"
type_value[63]	"undefined"
type_value[64]	"undefined"
type_value[65]	"undefined"
```

#### Expected behavior

Once the import configuration is saved, I'd like to load it later :)

#### Steps to Reproduce

1. Go to 'Avanced Settings > Import > Fill the form and upload a file to import (Products in my case)'
2. Click on 'Next Step'
3. Give a name to the field : Save your data matching configuration
4. Once you're on the match fields table, Save the import configuration
5. Look at the payload sent or try to refresh an load your previous saved configuration

**Screenshots**

When you name it and save it:

![image](https://user-images.githubusercontent.com/14120614/84631715-21c17f00-aeee-11ea-998b-5e4fe04af64f.png)

And when you try to load it:
![image](https://user-images.githubusercontent.com/14120614/84631844-5cc3b280-aeee-11ea-947e-b3b4c456fb63.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2.30 (PrestaShop Docker default config)

**Comment by matthieu-rolland** [comment]
I didn't manage to reproduce your bug exactly, is the table and its fields correctly filled after uploading the import file and clicking next?

<img width="1187" alt="Capture d’écran 2020-06-15 à 16 51 01" src="https://user-images.githubusercontent.com/1784781/84672169-8699cb00-af28-11ea-8e10-13d98e6ec657.png">

**Comment by joemugen** [comment]
> I didn't manage to reproduce your bug exactly, is the table and its fields correctly filled after uploading the import file and clicking next?
> 
> <img alt="Capture d’écran 2020-06-15 à 16 51 01" width="1187" src="https://user-images.githubusercontent.com/1784781/84672169-8699cb00-af28-11ea-8e10-13d98e6ec657.png">

Really? It's weird.
I tried again with the product import file example after a full cache clean and it's still doing the same on Firefox 77.

![bug_import](https://user-images.githubusercontent.com/14120614/84686943-26f9ea80-af3d-11ea-88c2-c7dd45fc56f1.gif)

**Comment by florine2623** [comment]
Hi @joemugen ,

Thanks for the report.
It is indeed a bug in PS 1.7.7.0, I managed to reproduce it.
The name of the import after being saved is always `undefined` :
![Capture d’écran 2020-06-18 à 15 52 49](https://user-images.githubusercontent.com/16019289/85028954-0a97c100-b17c-11ea-8f4a-66c168f013c2.png)

This is a regression, in PS 1.7.6.5, it was working correctly :
![Capture d’écran 2020-06-18 à 15 52 35](https://user-images.githubusercontent.com/16019289/85029009-1d11fa80-b17c-11ea-914d-c3fbbb64387d.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by joemugen** [comment]
Hey @florine2623 , there is already a pull request ready: https://github.com/PrestaShop/PrestaShop/pull/19738
