### ISSUE TITLE
Problem with set accesses by tabs

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#19759]
#### Describe the bug

When i add tab in section "More", i can not set access in list accesses by tabs

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create tab module in section More
2. Go to accesses by tabs
3. Set access this tab module
4. Update page, access not setted

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1

**Comment by sarahdib** [comment]
Hello @dariusakafest 

Could you tell me if this tab the problem is in the BO or FO ?

Thank you

**Comment by fest73** [comment]
@sarahdib BO

**Comment by PierreRambaud** [comment]
@dariusakafest Could you please provide us a module to reproduce your issue? It will be easier for us to understand what exactly happened.

**Comment by prestascott** [comment]
Hello @dariusakafest,

Since we had no news from you for more than 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!
