### ISSUE TITLE
Error 500 when deleting the default category

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#19751]
#### Describe the bug

After bulk deleting the default Prestashop's categories, an error 500 occured on the frontend. The backend was still working. I found out with the debug mode that it cames from the following file: classes/Link.php
It seems that even after the deletion some data still remains and triggers the "throwError" when the category object is incorrectly formed. After that 1st fix, I had to fix a ternary condition for when the variable $category is not an object.

#### Expected behavior

Having no error when you're deleting the default category

#### Steps to Reproduce

Install an 1.7.6.x shop, delete the default category, you shouldn't have any error in FO and BO

#### Additional information

* PrestaShop version: 1.7.6.x

Created the issue for this PR : https://github.com/PrestaShop/PrestaShop/pull/16778

**Comment by matthieu-rolland** [comment]
Issue reproduced on 1.7.6.5, and also on 1.7.7 (after selecting the first element in the warning modal).

**Comment by NeOMakinG** [comment]
Looks like I'm not able to reproduce it at all, closing it
