### ISSUE TITLE
Cart rule credit has different behavior after first use by customer

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#19758]
#### Describe the bug

As a merchant, I create an assigned cart rule with 100€ credit to a specific customer. This cart rule requires no code so it is automatically assigned to that customer.
The customer can use it multiple times until credit is no longer available.
The problem is, once used, the cart rule is not applied automatically anymore, a code is required.
It is sometimes hard for a customer to find that code because the email sometimes goes to spam.

#### Expected behavior

After the first use of this cart rule, no code should be required as it was on the first use.

#### Steps to Reproduce

1. In BO, create a Cart Rule
2. Choose partial use, no code, a specific customer and 100€
3. In FO, log in to that customer account
4. Place a first order > **OK**
5. Place a second order > **NOK** a code needs to be entered to get the voucher

**Screenshots**

https://drive.google.com/file/d/1xpwJNfBEa7RTid5qiHoo8J6-oekeIaTw/view

#### Additional information

* PrestaShop version: 1.7.6.5, 1.7.7.0
* PHP version: 7.2

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-product-team 
What do you think about that ? 
Create a voucher without code, with no code require and partial use. 
We made a first order the cart rule is automatically apply the first time but the second time a code is generated, if the total amount isn't used. 
The improvement is to not use a code for the second time.

**Comment by colinegin** [comment]
@florine2623 The customer is supposed to receive an email with the new code. Why do you say it's not easy to find this code ?

**Comment by florine2623** [comment]
@colinegin 
Sorry for taking so long to answer.
A PrestaShop user has brought that issue to me. I created the issue for him.
Sometimes the email goes into spam and the customer can't find the code.

**Comment by colinegin** [comment]
ping @PrestaShop/prestashop-core-developers is this something that should be fixed in the core or do you think it's related to the email provider ? 

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @florine2623 

I may misunderstand but I believe when you set **Total available** and **Total available for each user** to **`1`**, the user has the right to use the voucher only one time. (see the screenshot below from your screen record)

![image](https://user-images.githubusercontent.com/23308427/108474585-dd159100-728f-11eb-99bb-23f5453f1357.png)

Please check and feedback.
Thanks!

**Comment by florine2623** [comment]
Thanks all.
I'm closing this issue since I don't have any news from the original author of this request.
