### ISSUE TITLE
Error when installing without debug mode disabled

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19754]
#### Describe the bug

When installing PS with debug mode disabled (from git repo, not from a realease zip), there is an error during the install.

On 1.7.6.x and 1.7.7.x branches only, not on develop.

#### Expected behavior

No error during install :stuck_out_tongue: 

#### Steps to Reproduce

1. Install PS from git repo (176, 177 but not on develop)
2. Go to BO > Advanced parameters > Performance
3. Disable "Debug mode"
4. Reinstall PS, with demo products
5. An error occurs at "Create database tables" step
6. Restart install. A new error occurs at "Create default shop and languages" step
7. Restart install : It's OK

**Screenshots**

![install without debug mode step 0](https://user-images.githubusercontent.com/55688534/84663083-f86c1780-af1c-11ea-9c55-69194880c86a.png)

![install without debug mode](https://user-images.githubusercontent.com/55688534/84663096-fbff9e80-af1c-11ea-8027-1a2fa18a5ed3.png)

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Ping @PierreRambaud 

You asked it there : https://github.com/PrestaShop/PrestaShop/pull/19694#issuecomment-642062354
I do it here ;)

**Comment by Progi1984** [comment]
Fixed by #19788
