### ISSUE TITLE
Incorrect help text for Tax in Tax rules

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19766]
#### Describe the bug
There is an incorrect help text for Tax in Tax rules: "Total tax 9%".

#### Expected behavior
There should be explained what the field Tax means.

#### Steps to Reproduce
BO > International > Taxes > New tax rule > Tax > Help text

**Screenshots**
![image](https://user-images.githubusercontent.com/33311857/84699504-ea84b980-af51-11ea-8334-23c4fe236b7a.png)

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by sarahdib** [comment]
@Junebyun could you check this in french it's ok but in english the translation is not ok.

**Comment by Junebyun** [comment]
@sarahdib indeed the translation is not accurate. 
In the 1.7.2 version the text was _(Total tax: %s)_ in English and _(Taxe totale : %s)_ in French but since the 1.7.3 and forth the English text was _(Total tax: 9%)_ and _(Taxe totale appliquée)_ in French.

We can either keep:

- _(Total tax: %s)_ in English and _(Taxe totale : %s)_ in French OR

- _**(Total tax applied)**_ in English and _**(Taxe totale appliquée)**_ in French

I would go with the second option! :)

**Comment by LouiseBonnard** [comment]
It's weird, nice catch @juraj1000! I wonder why the variable has been hardcoded... I dug a bit and found the commit that introduced the change ([here](https://github.com/PrestaShop/PrestaShop/commit/e15d73076262313229f1b06c26577cddf0dacd2d#diff-21c9ebbacec5a9ec2ffa89f9c5370019)) but it looks like the value was `9%` anyway, @Quetzacoalt91, @PrestaShop/prestashop-core-developers, any idea about why it has been changed? or what does it stand for?

So it is not a translation issue, @sarahdib, but a wording issue. One thing is sure, you're right @Junebyun, this is supposed to be a tooltip and here it does not explain anything, quite the contrary! At this step, the user is expected to select the tax he wants to use for this tax rule. Is a tooltip necessary? I find it rather explicit already with the label and the dropdown selector.

🤔

**Comment by Quetzacoalt91** [comment]
I made these changes to replace `sprintf` calls with placeholders. For this 9%, I basically moved this value into the string only to avoid a useless call of the method `sprintf`. At that moment I didn't suggest to make the wording better.

**Comment by l-delin** [comment]
> It's weird, nice catch @juraj1000! I wonder why the variable has been hardcoded... I dug a bit and found the commit that introduced the change ([here](https://github.com/PrestaShop/PrestaShop/commit/e15d73076262313229f1b06c26577cddf0dacd2d#diff-21c9ebbacec5a9ec2ffa89f9c5370019)) but it looks like the value was `9%` anyway, @Quetzacoalt91, @PrestaShop/prestashop-core-developers, any idea about why it has been changed? or what does it stand for?
> 
> So it is not a translation issue, @sarahdib, but a wording issue. One thing is sure, you're right @Junebyun, this is supposed to be a tooltip and here it does not explain anything, quite the contrary! At this step, the user is expected to select the tax he wants to use for this tax rule. Is a tooltip necessary? I find it rather explicit already with the label and the dropdown selector.
> 
> 🤔

I agree with @LouiseBonnard, I believe this tooltip is not necessary, it should be removed. It doesn't explain anything and doesn't help the user. If anything, it makes things more confusing.

**Comment by florine2623** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29740
