### ISSUE TITLE
I can't place the order, with a 100% voucher code

### ISSUE THREAD

**Issue by KoreLewi** [PrestaShop/PrestaShop#19764]
##### In standard  Prestashop checkout module, i got the error "Please make sure you've chosen a payment method  ", even if my cart value is 0 (eg. i have a 100% discount)

Screeshoot: https://prnt.sc/t07j06

#### Steps to Reproduce

1. Just create a 100% discount code, apply it, and try to place the order.

#### Additional information

* PrestaShop version: 1.7.6

#### Update: 
After enabled the Terms of Service checkbox in BO->Order settings, a new checkox displayed in Payment Methods page, and if i check this chexbox, the error message gone, and the button will be enabled.  But I don’t understand what these two have to do with each other?

**Comment by sarahdib** [comment]
Hello @KoreLewi 

could you tell me which version 1.7.6 exactly did you use ?

Could you check the restriction in the tab payement -> preferences.

Thank you

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Comment by Maarten1973** [comment]
Hello koreLewi,

How did you solve this issue? I've got the same problem.
