### ISSUE TITLE
PayPal module 5.1.3 discount bug

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#19779]
HI

It seems when a cart contains a discount voucher in the cart (in ps_cart_rule table), the paypal module only calculates discounts which are based on percentages and not amounts.

Therefore, the value for reduction_percentage must in ps_cart_rule must be set while the value for "reduction_amount" is ignored.  This results in a total without discount being sent over to PayPal for payment collection.

It seems only the paypal module suffers this issue, other payment modules correctly will also check the reduction_amount value for a cart rule when calculating discounts.

I identified the problem in the following file:

/modules/paypal/classes/MethodEC.php
in the method _getDiscountsList

Kind Regards
Musaffar

**Comment by Matt75** [comment]
PayPal module is not provided by PrestaShop, please contact module developer here : https://addons.prestashop.com/contact-form.php?id_product=1748

**Comment by musaffar-patel** [comment]
Hi

The author of the module in the module list and all licensing headers is named as "Prestashop".  The module itself also contains the following line in the constructor method:

$this->author = 'PrestaShop';

Who is the author if not Prestashop?  Please advise.

Kind Regards
Musaffar

**Comment by Matt75** [comment]
It’s a partnership, module developer is @202-ecommerce

**Comment by musaffar-patel** [comment]
Hi Matt

Thanks, I've reported the bug to them.

Due to this being an official Prestashop module, it would be helpful if you or another member of the Prestashop team could report the bug to them along with me as this would help expedite the resolution of the bug.   In my my view, this is a serious bug which prevents fixed amount cart rules to be used.

Kind Regards
Musaffar

**Comment by Matt75** [comment]
I’ve ping them on my last message, I’m sure they will response soon.

**Comment by musaffar-patel** [comment]
Hi

Super! many thanks

Kind Regards
Musaffar

**Comment by 202-ecommerce** [comment]
Hi @musaffar-patel 

Thank you for this information.

Please to not hesitate to [contact our support team](https://addons.prestashop.com/en/contact-us?id_product=1748) for getting quick response for your specific case. If it's already done, our team will answer you as soon as possible

Best regards
Clotaire for 202 ecommerce

**Comment by tvorgul** [comment]
Hello,

@musaffar-patel Thank you again for this information.
This issue has been already fixed and the version 5.1.4 will be released on addons at the end of this week or by the beginning of next week.

Do not hesitate to use our [official repository](https://github.com/202-ecommerce/paypal) for reporting any issue or contact our [support team](https://addons.prestashop.com/en/contact-us?id_product=1748) if you have any additional questions. 
Also, do not hesitate to contact our support team for getting the fixed version as soon as possible.

Regards,
Tetiana
202 ecommerce

**Comment by musaffar-patel** [comment]
Thanks, I've forwarded your message to my client who spotted the issue.

All the best for now
Musaffar
