### ISSUE TITLE
[Ajax / Server Error for action upgradeFiles] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: ".

### ISSUE THREAD

**Issue by bxpeke** [PrestaShop/PrestaShop#19772]
Got this error if I try the 1-click update module in version 1.4.7.1.
I read some answers on the forum but I must admit some older "solutions" I didn't get at all...

this is the log.txt:

on request...

**Comment by colinegin** [comment]
Hello @bxpeke ,

Thanks for your feedback.
Could you please give us more information to be able to reproduce this problem ?
Is your current PrestaShop version 1.4.7.1 or is it the module's version ? 
Note that if you are on PrestaShop 1.4, you will have to use the version 1.X.X of the module to be able to upgrade to the 1.6 version. And then you will be able to use the 2.X.X version to upgrade to the latest version of PrestaShop, 1.7.6.5.

Thanks

**Comment by bxpeke** [comment]
hi @colinegin 

Yes my current Prestashop version is 1.4.7.1.
I used 1-click upgrade module v4.10.1 , which states it updates from versions  V1.4.0.1 till V1.7.7.0.

where can I find the modules you refer to?

Thanks

**Comment by florine2623** [comment]
Hi @bxpeke ,
I would advise you to let our support team to do it.
https://www.prestashop.com/en/support

Going from a version 1.4 to 1.7 requires some knowledge. Also the PHP version won't be compatible after migrating, that might break your website.

The error you're having is a PHP error : `Using array_key_exists() on objects is deprecated`
The PHP version on your hosting provider might not be compatible with whatever PS version you are using.
You can find here some info on PS system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Also, your admin is on display, this is a public space, please change it.
