### ISSUE TITLE
Capital characters in product name

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19781]
#### Describe the bug
There is displayed a product name at product detail screen always with capitals "HUMMINGBIRD PRINTED T-SHIRT". The product is defined in catalog with the name "Humming Bird T-Shirt" and it is displayed correctly at all other screens, e.g. homepage.  It is also correctly displayed at pdf output, e.g. invoice, delivery slip... It is incorrect only at product detail and quickview screens.
The product name should be displayed by the same way at each screen and it should be displayed how it is defined in the catalog. If an e-shop company requires capitals, the product name can be defined with capitals. Currently it is confusing for end user and also it is more complicated to read it.
Keep into account there can be used also special characters in the name, e.g "x". If the product name is "Table 70x50cm" currently it is converted to "TABLE 70X50CM". And it is really quite complicated to read it.

#### Expected behavior
Display product name as it is defined, do not convert it to capitals.

**Screenshots**
Product detail screen
![image](https://user-images.githubusercontent.com/33311857/84759206-b3042480-afc6-11ea-8c56-23cfcf71c19c.png)

Homepage
![image](https://user-images.githubusercontent.com/33311857/84759883-9a483e80-afc7-11ea-9717-f0238f48e097.png)

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by sarahdib** [comment]
Hello @juraj1000 

You can edit the default template with child theme option.
https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/

Thank you
