### ISSUE TITLE
AJAX CART on MOBILE

### ISSUE THREAD

**Issue by MauroKali** [PrestaShop/PrestaShop#19786]
Hello, 

I have an issue about ajax cart on mobile: 

When I add a product I get the message (a product is added, etc) and I see the number of products in the cart. BUT if I click on the cart preview it is not refreshed and I do not see the last product updated. 

I need to refresh the page in some way in order to see all the products. 

edit: FYI: no errors on console 

* PrestaShop version: 1.7.6.4

**Comment by colinegin** [comment]
Hello @MauroKali ,

Thanks for your feedback.
I think this is related to this bug : https://github.com/PrestaShop/PrestaShop/issues/19733
Could you check if this is also happening on desktop ? 

Thanks,

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
