### ISSUE TITLE
Capital characters in menu items and categories

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19784]
#### Describe the bug
There are incorrectly displayed menu items and categories, sometimes they are converted to capital letters.
- Menu item Clothes
It is displayed as "CLOTHES" but it is defined as "Clothes" in the configuration.
- Category Men
Some times it is displayed as "MEN' and some times it is displayed as "Men" but it is defined as "Men" in the configuration.

It should be always displayed as it is defined in the catalog. If an e-shop company requires capitals, it can be defined with capitals. Currently it is confusing for end user and also it is more complicated to read it.
Keep into account there can be used also special characters in the category, e.g "x". If the category name is "Products 80x60 kWh" currently it is converted to "PRODUCTS 80X60  KWH". And it is really quite complicated to read it.

#### Expected behavior
Display menu items and categories as they are defined, do not convert them to capitals.

**Screenshots**
![image](https://user-images.githubusercontent.com/33311857/84762724-7981e800-afcb-11ea-9785-17d66e2103a4.png)

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by Hlavtox** [comment]
@juraj1000 The visibility is better in my opinion.

If you don't want it to be capital, just set **text-transform: none** on the items you dont want to capitalize. It's only a matter of styling and the default template.

**Comment by sarahdib** [comment]
Hello @juraj1000

You can edit the default template with child theme option.
https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/

Thank you
