### ISSUE TITLE
BO and Store Front shut down due to unknown reason.

### ISSUE THREAD

**Issue by MobileStarChart** [PrestaShop/PrestaShop#19783]
Site: https://www.zamonji.com/, debug mode on.
Error
![image](https://user-images.githubusercontent.com/8614425/84761428-f927ab00-affb-11ea-9e05-69f1470d54e3.png)

![image](https://user-images.githubusercontent.com/8614425/84761462-05ac0380-affc-11ea-869a-c284bbedf67d.png)

I really have no idea about those errors, wish someone help, thanks!

**Comment by sarahdib** [comment]
Hello @MobileStarChart 

Could you contact our support team in order to help you solve this.

Thank you

**Comment by rdy4ever** [comment]
Hi @MobileStarChart 
You might be out of disk space or the file permissions are wrong on the server (you need to set 0755 for folders and 0644 fir files).
