### ISSUE TITLE
Impossible to log in to Backoffice in PrestaShop 1.7.2.0

### ISSUE THREAD

**Issue by gagzu** [PrestaShop/PrestaShop#19797]
**Error description:** nothing is shown when trying to log in.

We enter user (mail) and password, it tries to log in but nothing happens.
Inspecting browser’s console but no error is shown, nor even a clue to follow.

**Additional information:**
PrestaShop version: 1.7.2
PHP version: 7.1.33
Database client version: libmysql - 5.1.73

**We've tried this:**
- Empty the cache and cookies
- Verified PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL on ps_contiguration table
- Cache manual deletion on app/cache/dev and app/cache/prod
- Deactivation of IP check at clases/Cookie.php commenting the condition:
	`(!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP’))`

In the route /PROJECT_FOLDER/classes/controller/AdminController.php
	**we’ve replaced this:**
	`if ($this->context->cookie->last_activity + 900 < time()) {`

**by this:**
`if ($this->context->cookie->last_activity + 3600 < time()) {`

**Comment by sarahdib** [comment]
Hello @gagzu 

This is not a bug from prestashop software. Could you contact our support team 

Thank you
