### ISSUE TITLE
No High DPI support in ImageRetriever

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#19798]
#### Describe the bug

Image retriever only generates low res images.

#### Expected behavior

All images should be generated correctly.

#### Steps to Reproduce

1. Turn on "Generate high resolution images" option
2. Regenerate all images, make sure the high res images are there
3. Delete thumbnails for one selected image of a product
4. Go to product page
5. Check the thumbnails folder - only low res images are regenerated

* PrestaShop version: 1.7.6.5

**Comment by florine2623** [comment]
Hi @daresh ,
Do you have example of high resolution images that I can do the test with ?
By "delete thumbnail", do you mean delete the cover image of a product in the BO ?
Thanks!

**Comment by daresh** [comment]
Hi!

You don't need any specific high resolution image to perform this test, you can use any image.

By "delete thumbnail" I mean manually delete a thumbnail from the server. The best way to see if the whole set of images got generated is to look directly into the folders.

Another case may be something like this:
- upload images to a product 
- turn on "high dpi" after some time after the shop starts working

The images will not be retrieved without a full regeneration. I specifically adress the ImageRetriever class here, that has no 2x support, only normal size images.

**Comment by prestascott** [comment]
Hi @daresh, 

Sorry we don't understand the bug. Can you provide us a video so we can help please? 
Thank you!

**Comment by daresh** [comment]
The high DPI images are not something that you see right away, cause you need a theme using them and a high density screen, but you can check it this way:

1. have a shop with the option to generate high DPI images turned off
2. go to some folder of any image on your FTP, like img/p/4
4. delete the thumbnails from that folder manually (the xxx_default images, home_default, large default etc.)
5. visit the product page of a product having this image
6. check out the folder again - you'll see the images got regenerated - that's how ImageRetriever class works
7. turn on the high DPI generation in images settings
8. delete the thumbnails again
9. visit product page
10. check out the folder - you'll see regenerated thumbnails, but only low resolution, no high res images, because the ImageRetriever does not have support for the high DPI (2x) images

**Comment by florine2623** [comment]
Hi @daresh,

Indeed after regenerating the images with option Generate high resolution images = YES, the images regenerated are the same weight/size. This issue is present on PS 1.7.6.5 and PS 1.7.7.0.

With a product with images :
- Go to Design > Image Settings > Generate all thumbnails
- Enable option Generate high resolution images
- Regenerate all thumbnails and choose Erase previous images = NO
- Review the images, and see that they are the same.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by daresh** [comment]
Hi @florine2623 

Thanks for the reply, but you're mixing things here. The bug in this topic is about the ImageRetriever, that takes action when you visit the product page, not when you regenerate the images in the back office.

You can check out this bug this way:
1. have a shop with no High DPI support
2. turn on High DPI support
3. go to product page
4. check out image folder on your server - img/p

You will see no high DPI images, which should be there, because it's how ImageRetreiver works, it regenerates thumbnails on demand, when product's page is visited, not when you regenerate in back office.

I'll see what I can do with that pull request :)

**Comment by khouloudbelguith** [comment]
Hi @daresh,

Isn't your issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/13957 which fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16097?

Thanks!

**Comment by daresh** [comment]
Hi @khouloudbelguith 

no, it's something totally different. The issue you mentioned is about knowing the 2x support is turned on in the tpl files.

My issue is about the 2x images not being generated on the server at all by a function that is responsible for generating normal images on demand.

**Comment by khouloudbelguith** [comment]
@daresh, thanks!
