### ISSUE TITLE
Customer always lands on the details of his account, whatever he does...

### ISSUE THREAD

**Issue by pattex1** [PrestaShop/PrestaShop#19808]
Hello everybody,
I have a problem that unfortunately occurs again and again:
Our customers had and still have technical difficulties with the ordering process on our side. Whenever the user is logged in, he always lands on the details of his account, no matter what he wants to call up. Therefore, the order did not work. The problem does not exist with every customer, but with too many. It also seems to happen across browsers and on all end devices. In other words, once a customer has the problem, he always has it everywhere.

Maybe someone has already experienced this and there is a plausible explanation / solution?
Thanks for any feedback.

* PrestaShop version: 1.7.6.3
* PHP version: 7.3.6

**Comment by colinegin** [comment]
Hello @pattex1 ,

Please, send your request in English.

English is the norm on GitHub

Thank you!

**Comment by pattex1** [comment]
thanks - and sorry therefore. i translated it

**Comment by rdy4ever** [comment]
Hi @pattex1 
Could you provide more details about your shop? You can find them in Advanced->Information. Also, could you provide your shop url so I could take a quick test (as a client)?

**Comment by pattex1** [comment]
Thank you for investigating.
the url is www.fine-liquids.com

Here are the  shop details:

Server information Linux #1 SMP Sat Sep 21 01:19:55 CDT 2019 x86_64
Server software version: Apache
PHP version: 7.2.31
Memory limit: 512M
Max execution time: 1000
Upload Max File size: 256M

Database information
MySQL version: 5.6.41-84.1
MySQL server: 127.0.0.1

Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO


Changed/missing files have been detected.

Missing files (2)
/autoupgrade/index.php
vendor/composer/installers/src/Composer/Installers/CiviCrmInstaller.php
Updated files (6)
autoupgrade/backup/index.php
config/defines.inc.php
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MediaWikiInstaller.php

**Comment by rdy4ever** [comment]
Could you please remove the database details and admin directory name? This is a public space.

**Comment by rdy4ever** [comment]
Hi @pattex1 
I was able to place a test order on your website (Horia Test). However, your website is very slow and it looks like it's dragging some silenced errors behind. I suspect the theme as a culprit. You should try to place an order while the site is in debug mode ([how](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/)) and see if you get any errors displayed. It might be the theme or some module, but something must be wrong to make your shop so slow. Also, you could try to switch to the default theme and see if the shop gets better performance.

**Comment by pattex1** [comment]
hi.
the problem was caused ba amazon pay. i deactivated it and now it seems to run.

**Comment by colinegin** [comment]
This is great news ! 
I close this issue as there is no longer any problem, do not hesitate to create a new issue if your bug is persistent.
