### ISSUE TITLE
Prestashop 1.7.6.3 problem in paypal 

### ISSUE THREAD

**Issue by Mejdios** [PrestaShop/PrestaShop#19817]
Dear Friend 
paypal discount not working prestashop 1.7.6   
Thanks for Help

**Comment by Matt75** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19779

**Comment by colinegin** [comment]
Hello @Mejdios ,

I close this issue as this is a duplicate of #19779. Please follow this issue.

Thanks !
