### ISSUE TITLE
Product comments module doesn't support multi-store properly

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#19811]
#### Describe the bug

Well, same story :)

Configuration adapter doesn't take into account multi-store, because of that `productcomments` module won't work properly with few stores with different settings.

I've reported this over a year ago here:
https://github.com/PrestaShop/PrestaShop/pull/12544

#### Expected behavior

If you have few stores:
- Store A
- Store B

settings from each store should be properly read when you are using this:
`'@=service("prestashop.adapter.legacy.configuration").get("PRODUCT_COMMENTS_ALLOW_GUESTS")'`

#### Steps to Reproduce

1. install multi-store, two stores at least
2. disable comments for guests in context of "All shops"
3. enable comments for guests in context of Store B
4. try to add a comment as a non logged user

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by colinegin** [comment]
Hello @kpodemski ,

I've followed the steps that you wrote down and I'm not sure to understand where is the problem.
In the shop where I've enabled comments for guests, I can write comments even though I'm not logged --> correct
In the shop where I didn't change the configuration (it uses the configuration done in All shops), I cannot write comments as a guest --> correct

So if I understand correctly, the problem is that comments waiting for review are shared between shops while they should be separated according to the shop where it was written.

Am I correct ?

Thanks a lot

**Comment by matks** [comment]
FYI @marionf did some research about all modules multistore capabilities
Here is what she said about module productcomments https://github.com/PrestaShop/productcomments/pull/52

We can ask here when she's back (she's off this week) what she found exactly

**Comment by kpodemski** [comment]
@colinegin @matks 

i think that those problems are related to this method:
https://github.com/PrestaShop/productcomments/blob/master/productcomments.php#L63

we should force context of all shops during installation, i didn't have module before, i've installed it in context of one store and because of that settings were messed up

i'll make a PR

**Comment by kpodemski** [comment]
@colinegin @matks 

ready, with detailed explanation of the issue

https://github.com/PrestaShop/productcomments/pull/58

**Comment by colinegin** [comment]
FYI @marionf

**Comment by marionf** [comment]
Hello @kpodemski and thank you for the PR
Product comments module is partially compatible with the multistore, which means that some of its options / features might not be available or correctly working in a multistore context.
For example, all the reviews are displayed in the BO, even if you select a specific shop in the context: #19932

**Comment by kpodemski** [comment]
@marionf i think i can improve this part of the module if you don't have anyone assigned to this already, what do you think?

**Comment by marionf** [comment]
@kpodemski, yes sure :+1: 
I created an [EPIC](https://github.com/PrestaShop/PrestaShop/issues/19933) with all issues about productcomments module, feel free to take the issue you want 
Let me know if something is not clear or if you need help on an issue :wink:
