### ISSUE TITLE
[SEO] Not possibile to specify different meta title for different product variants?

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#19816]
Hello, I am experiencing an issue with PS 1.7.6.4 from the SEO perfspective.
In my store I have a lot of products with variants that at the momento have the very same meta title, which is a SEO issue.

From what I see in the cp there is no way to handle that data field by hand, am I right?

I searched the Issues section before opening this issue but I didn't find this exact problem, so maybe I am doing something wrong.
Thanks in advance.

**Comment by colinegin** [comment]
Hello @masiorama ,

Thanks for your feedback. 
In Traffic & SEO > SEO & URLs > SEO options, you are able to enable the option "display attributes in the product meta title".

![image](https://user-images.githubusercontent.com/35263827/84900558-92ad9600-b0aa-11ea-9e89-d24a9472aa0d.png)

Did you already try to use this option ?

Thanks for your reply.

**Comment by masiorama** [comment]
Well, I was not aware of that, and it does solve my problem indeed. Thank you very much!

**Comment by colinegin** [comment]
You're welcome, I'm happy I was able to help you ! :)
