### ISSUE TITLE
[BO - employees page] - Filter are not working

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#19812]
#### Describe the bug
Filter are not working on Employees page on BO
#### Expected behavior
Filter should work

#### Steps to Reproduce

1. Go to 'BO - employees Page'
2. Filter by any column of the grid (id = 1 for example)
3. Click on search
4. See error : Page is refreshed, list of employees is the same, filter column is empty (not filter is applied)

**Screen record of the bug :**  
[Bug employees page.zip](https://github.com/PrestaShop/PrestaShop/files/4791151/Bug.employees.page.zip)

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: 7.2

**Comment by matks** [comment]
PR WIP again https://github.com/PrestaShop/PrestaShop/pull/19828

**Comment by Progi1984** [comment]
Fixed by #19828
