### ISSUE TITLE
Wrong content in search field in backend orders panel causes 500 error.

### ISSUE THREAD

**Issue by Demacri** [PrestaShop/PrestaShop#19824]
#### Describe the bug

Writing pipe in search field in backend orders panel causes error.

#### Expected behavior

No error.

#### Steps to Reproduce

1. Go to orders page in admin panel.
2. Click on the customer search field
3. write something like "aaa|bbb" (the pipe causes the error)
4. See 500 Internal Server Error

**Screenshots**

https://imgur.com/kvfuu5X

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.3.16

**Comment by florine2623** [comment]
Hi @Demacri 

Could you use PHP 7.2 ?
Here are the system requirements of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Let me know if that fixes your issue.
Thanks!

**Comment by Demacri** [comment]
> Hi @Demacri
> 
> Could you use PHP 7.2 ?
> Here are the system requirements of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> Let me know if that fixes your issue.
> Thanks!

Changed to 7.2.29 same issue.
It's not really a problem as a customer generally doesn't have a pipe in its name but i wanted to report it cause maybe can cause security issue or something else(?)
Thanks for the support.

**Comment by florine2623** [comment]
This issue has been fixed in PS 1.7.7.0. 
![Capture d’écran 2020-06-17 à 16 57 23](https://user-images.githubusercontent.com/16019289/84914206-a3b2d300-b0bb-11ea-803d-e766f93f9e70.png)

You can wait for the release candidate and upgrade your shop :)
I will close this issue.
Thanks!
