### ISSUE TITLE
Hooks displayAdminOrderTabLink or displayAdminOrderTabContent are displayed with raw HTML

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19822]
#### Describe the bug

When you use displayAdminOrderTabLink or displayAdminOrderTabContent, you'll see HTML content.
![image](https://user-images.githubusercontent.com/52157233/84900007-c3410000-b0a9-11ea-9eb8-a086277216ed.png)

#### Expected behavior

Content should be not escape.

#### Steps to Reproduce

1. Install https://github.com/PrestaShop/PrestaShop/files/4695351/tottesthooks.zip
2. See error on order page

#### Additional information

* PrestaShop version: develop / 1.7.7.x
* PHP version: N/A

**Comment by colinegin** [comment]
@matks I've seen your comments on the PR, so you validate the bug ?

**Comment by matks** [comment]
> @matks I've seen your comments on the PR, so you validate the bug ?

Yes, it's indeed an issue for modules. What is not clear yet is the solution. We must find something that provides enough freedom while keeping the software secure

**Comment by kpodemski** [comment]
@matks what you mean "secure"? you want to filter something... what comes from module... which is installed by... merchant? if i'd like to do mess in store i have 99999 options to do that if someone is installing my module

**Comment by matks** [comment]
> @matks what you mean "secure"? you want to filter something... what comes from module... which is installed by... merchant? if i'd like to do mess in store i have 99999 options to do that if someone is installing my module

If I follow @PierreRambaud thoughts, I think we must "secure" (= escape) included items that contain user input (mainly to avoid XSS).

So if for example we have a Product Reviews module, the content sent from this module must be escaped 😉 (even in the BO, in the page where admin can monitor the reviews submitted). Here this hook belongs in Order page and there is no clear guideline stating that user input will find its way here, so we can assume it's safe to use `|raw`

If at some point we _know_ a specific field is intended to contain HTML submitted by user, we might apply it relevant security rules. For example if we know it's content generated by a WYSIWYG, we can assume it will be HTML without Javascript so we can use twig `escape(js)` which allows HTML but refuses scripts 😉

**Comment by matks** [comment]
@kpodemski By the way, @PierreRambaud confirmed `|raw` is fine here (see the PR https://github.com/PrestaShop/PrestaShop/pull/19820)

**Comment by kpodemski** [comment]
Ok, thanks, tho like i said, securing back office is tricky, i literally can do whatever I want if my module is on the server...

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/19820
