### ISSUE TITLE
Cannot log out from customer account

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19825]
Hi, I encountered an issue, where I couldn't log out of customer's account in FO. You clicked on logout and it just refreshed the page.

It seems to be hosting-provider specific (https://www.wedos.com/), I did not encounter it on other providers.

The fix was to add this to .htaccess:

```
<IfModule mod_expires.c>
ExpiresDefault "access plus 1 days"
ExpiresByType text/html "access plus 0 minutes"
</IfModule>
```

Can this be somehow prevented (for the future users)?

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
I can't reproduce your issue on a PS 1.7.6.2 fresh install. Indeed it must be a server issue.
You can see my screen record here :
https://drive.google.com/file/d/12y0hw7C6mOJeSQyOOtrqiXPJyeIf3QJk/view

Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

@Hlavtox is having some issue on the FO when logged in as a customer. He found a way to fix this issue by changing the .htaccess. What do you think about that ?

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 Yes, it does not happen on any store hosted on our servers. Only on WEDOS.

But it seems it happens on other providers also.
https://www.prestashop.com/forums/topic/515637-customers-cant-log-out/

**Comment by PierreRambaud** [comment]
@Hlavtox Could you share the exact apache configuration which is used to run your PrestaShop?
If we can reproduce the issue it could help :sweat_smile:

**Comment by Hlavtox** [comment]
@PierreRambaud 

http://janwis.cz/info.php

**Comment by Hlavtox** [comment]
@PierreRambaud 

This is the config. http://janwis.cz/info.php
They have some kind of proxy cache enabled on the servers, which need to be turned off by the customer support. Then it started to work. It even caches static files like images, csv files etc. Otherwise, Prestashop worked fine.

**Comment by PierreRambaud** [comment]
Look like it's a problem with the proxy cache which cannot remove the cookie from the user. But with the latest 1.7.6.7, you shouldn't have the problem since something change in the cookie when you log out

**Comment by Hlavtox** [comment]
@PierreRambaud Closing this, let's hope it's fixed 💃
