### ISSUE TITLE
getPreviewUrl function generates a wrong URL if the admin language is different then the default language

### ISSUE THREAD

**Issue by blinkythefirst** [PrestaShop/PrestaShop#19832]
Hello,

I'm developing a module to remove the ID from the URL and i ran into an issue with the preview URL.

I tracked down the issue to this function:

https://github.com/PrestaShop/PrestaShop/blob/11057fd1b1acb9b43e0712f1683810c63d151586/src/Adapter/Product/AdminProductWrapper.php#L889-L915

Based on the code, here is an example. 

Have a multi-language store. The admin language ($context->language->id) is English and the default language ($id_lang) is German, so two different language id.

Have a simple schema route to product: {rewrite}-{id}.html

The generated URL will be like this: https://mydomain.com/de/english-product-friendly-url-1.html
A German base URL with an English product rewrite.

I have to say, this is a minor issue when the ID is in the URL, because the system can identify the product by the ID and the canonical redirection instantly redirects to the proper URL. 

But when i removed the ID from the schema and try to identify the product based on the rewrite for the given language determined by the base URL i can't, because in this case i try to find this English rewrite as a German, so it leads to a 404 page.

I don't know which language is intended to used here, the default or the admin, but currently this is not ok using the default for the base URL and the admin for the product rewrite, also for the category rewrite.

Thanks to check & feedback.

**Comment by florine2623** [comment]
Hi @blinkythefirst ,

Yu can't remove the IDs of the product URL.
You will have an error like this :
![Capture d’écran 2020-06-18 à 15 21 25](https://user-images.githubusercontent.com/16019289/85025224-66138000-b177-11ea-98c4-beea236d8cc2.png)
Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
