### ISSUE TITLE
price specification not found for currency "" when checking for SAV with attachnment

### ISSUE THREAD

**Issue by GDM-Pixel** [PrestaShop/PrestaShop#19834]
#### Describe the bug

Trying to access a customer message in SAV result in 500 error if there's an attachment to the message

#### Expected behavior

Display message from customer, with attachment

#### Steps to Reproduce

1- Send test message from contact form, with an attachment
2- From Dashboard, try to open the message
3- Error 500

**Screenshots**

See here : https://www.youtube.com/watch?v=7mc0K91OvJs

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3.18-1+0~20200515.59+debian10~1.gbp12fa4f

**Comment by florine2623** [comment]
Hi @GDM-Pixel ,
Please check PS system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Your version of PHP is not compatible with PS 1.7.6.4.
Thanks!
