### ISSUE TITLE
Avatar isn't displayed in log page

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#19844]
#### Describe the bug
Avatar isn't displayed in log page
Maybe related to : #18622 

#### Steps to Reproduce

1. Go to BO > advanced parameters > Logs
2. See error

**Screenshots**
<img width="1280" alt="Capture d’écran 2020-06-18 à 14 33 04" src="https://user-images.githubusercontent.com/3034677/85022014-f7342800-b172-11ea-9a2f-4e675f00cc51.png">

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1.3

**Comment by colinegin** [comment]
Remove the alt tag from the image.

**Comment by NeOMakinG** [comment]
@Progi1984 Do you think it's relevant, but it looks fine on develop even if it's calling profile.prestashop.com

**Comment by LouiseBonnard** [comment]
Wait for https://github.com/PrestaShop/PrestaShop/pull/19946 to be merged.
