### ISSUE TITLE
ps_emailalerts module not properly installed

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#19842]
#### Describe the bug

Try to install newest (2.2.0) ps_emailalerts module on clean installation, you'll notice that settings are missing and table in DB is not created

#### Expected behavior

You should be able to install module which is fully working :)

#### Steps to Reproduce

1. You need to have **clean** installation
2. Install ps_emailalerts module
3. See that settings are missing

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @kpodemski ,

In PS 1.7.6.5 and PS 1.7.7.0, I could install v2.2.0 of ps_emailalerts.
When you say that settings are missing, what exactly is missing ?
Thanks!

**Comment by kpodemski** [comment]
@florine2623 all settings are "NO" and you don't have example e-mail in "emails list", do you have this issue?

screenshot:
![image](https://user-images.githubusercontent.com/1533248/86144924-97d10300-baf6-11ea-9e69-daa149acd86d.png)

**Comment by florine2623** [comment]
My settings are all to NO indeed and I don't have an email in the field "Email addresses".

**Comment by florine2623** [comment]
Hi @Progi1984 ,
A new version of ps_emailalerts has been released last week, can the problem come from it ?
Is this even a bug ?
Thanks!

**Comment by kpodemski** [comment]
@florine2623 try to visit some out of stock product and you'll see that it is a huge issue :)

**Comment by florine2623** [comment]
@kpodemski what do you mean ?

**Comment by kpodemski** [comment]
@florine2623 module is not creating table in database, it's impossible to use it, module is **completely** broken without this fix, you can't subscribe for a notification to get an email when product is back in stock etc.

**Comment by Progi1984** [comment]
> Hi @Progi1984 ,
> A new version of ps_emailalerts has been released last week, can the problem come from it ?
> Is this even a bug ?
> Thanks!

@florine2623 I think the problem can come from here : 

And from this PR https://github.com/PrestaShop/ps_emailalerts/pull/20

If the system has not the old module (1.6), then the install doesn't set configuration.

**Comment by Progi1984** [comment]
PR : PrestaShop/ps_emailalerts#61

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/ps_emailalerts/pull/58

**Comment by matks** [comment]
Module released https://github.com/PrestaShop/ps_emailalerts/releases/tag/v2.2.1 => bug fix has been delivered
