### ISSUE TITLE
I can't modify or create a new product (The CSRF token is invalid. Please try to resubmit the form.) 

### ISSUE THREAD

**Issue by hamus1** [PrestaShop/PrestaShop#19853]
Can't modify or add a new product. When click on Save, i've this  message: The CSRF token is invalid. Please try to resubmit the form.

* PrestaShop version: 1.7.6
* PHP version: 7.2
Help please
![capturegit](https://user-images.githubusercontent.com/55998752/85031952-2ba9e300-b177-11ea-8a3b-2a6b830dbd06.png)

**Comment by florine2623** [comment]
Hi @hamus1 ,
Please, send your request in English.
English is the norm on GitHub
Thank you!

**Comment by mfnew** [comment]
Had same issue, found a fix on the prestashop forums

in your php.ini file try increasing max_input_vars to more than it is now.

Increased mine to 1500 and it fixed it.

Not sure if this helps you, but on prestashop forum more people had success with this.

[https://www.prestashop.com/forums/topic/588511-the-csrf-token-is-invalid-please-try-to-resubmit-the-form/](Prestashop thread)

**Comment by florine2623** [comment]
@mfnew thanks for the comment :)

@hamus1 don't forget to check if you meet all system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by florine2623** [comment]
@hamus1 I'll close your issue as you are not using our template properly.

**Comment by hamus1** [comment]
I've edit my message, please reopen @florine2623

**Comment by Matt75** [comment]
> in your php.ini file try increasing max_input_vars to more than it is now.
> 
> Increased mine to 1500 and it fixed it.

We recommend to set 20000 : https://devdocs.prestashop.com/1.7/scale/optimizations/

**Comment by hamus1** [comment]
@Matt75 Same problem 
i've add this in my php.ini 
memory_limit = 128M
max_execution_time = 300;
max_input_time = -1;
post_max_size = 25M;
upload_max_filesize = 20M;
max_input_vars = 10000;
suhosin.get.max_vars = 10000;
suhosin.post.max_vars = 10000;
my php.ini is in this path according to php.info: 
/Applications/MAMP/bin/php/php7.4.2/conf/php.ini

**Comment by Matt75** [comment]
Try to disable opcache or improve opcache configuration.
Check all requirements https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by mfnew** [comment]
Yes make sure it's not cached, always clear og disable cache while debugging
