### ISSUE TITLE
Symfony controller from module without a tab has no authorization role created

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#19857]
#### Describe the bug

When a module is installed `ModuleTabRegister` is in charge of creating the associated Tab, which creates the appropriate authorization roles

If the module creates its tab automatically (via `$tabs` property) or manually everything is fine, but if there is a controller (with permission via annotation) without tab no roles will be created thus an Exception will be thrown when trying to access it

For legacy controllers the service automatically scans the controller classes present in `controllers/admin` and adds undeclared tabs (tab not visible in the menu but used for security)

#### Expected behavior

The `ModuleTabRegister` service must be able to scan the `routing` file from module and detect the routes that have a `_legacy_controller` option These undeclared controllers must be automatically added in invisible tabs

#### Steps to Reproduce

A test module should be provided to validate this behaviour, it must contain:
- a Symfony controller with routing using `_legacy_controller`
- no legacy controller classes in the `controllers/admin` folder
- the `configure` method of the module must redirect to the Symfony route

Without the fix an exception should be thrown with missing autorization role, when the behaviour is fiex roles are automatically added and the controller is accessible

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #19903
