### ISSUE TITLE
Error executing product save 

### ISSUE THREAD

**Issue by xonox** [PrestaShop/PrestaShop#19869]
Hi 

I've reported a issue a while ago, but it stills happen every time.

Issue: [https://github.com/PrestaShop/PrestaShop/issues/10479](https://github.com/PrestaShop/PrestaShop/issues/10479)

This problem seems a bit weird.

But I stumble upon this problem every time.

The problem seems to be on around line 241 (prestahop 1.7.5.6)

public $pack_stock_type = Pack::STOCK_TYPE_DEFAULT;

Error: Cannot declare self-referencing constant 'Pack::STOCK_TYPE_DEFAULT'

Because Pack is a subclass of Product.

And in the super class Product it seems not be possible reference a subclass Pack constant.

I makes some sense.

Not sure what is causing this issue.

But this issue is very common to me. Happens every time in every host I try.

If in the Product class I replace public $pack_stock_type = Pack::STOCK_TYPE_DEFAULT; with public $pack_stock_type = 3; the error goes away.

This happens for example when I try to update the stock or save a product.

I develop a Prestashop extension and I call the $product->save() method or StockAvailableCore::setQuantity($product->id, 0, $stock, (int) $id_shop).

If in the Product class I replace public $pack_stock_type = Pack::STOCK_TYPE_DEFAULT; with public $pack_stock_type = 3; the error goes away.

**Comment by florine2623** [comment]
PS 1.7.5.6 does not exist.

I can't reproduce the issue in PS 1.7.6.5 nor PS 1.7.7.0, following these steps :
- create standard product A
- create pack product containing product A
- delete product A
Result that I have in my BO :
![Capture d’écran 2020-06-19 à 16 32 48](https://user-images.githubusercontent.com/16019289/85144101-f8d11f00-b24a-11ea-85e8-cb32bfd7a0ab.png)

I'll close your issue.
