### ISSUE TITLE
/1) ContextErrorException Avvertenza: vsprintf (): troppi argomenti

### ISSUE THREAD

**Issue by Tatyart31** [PrestaShop/PrestaShop#19860]
Buonasera, dopo aver tradotto alcuni testi 
Mi compare questo errore
Prestashop 1.7.6.5
Php 7.2
Il back office funziona solo in modalità di debug
L'errore accedendo al sito è questo:

1/1) ContextErrorExceptionAvvertenza: vsprintf (): troppi argomenti
--
nella riga 340 di Translate.php
at TranslateCore :: checkAndReplaceArgs ( '% year% M2V Communications% copyright%', array ('PrestaShop ™', '2020', '©') )nella riga 255 di Translate.php
at TranslateCore :: getModuleTranslation ( 'jxmegalayout', '[1]% 3 $ s% 2 $ s - Software e-commerce di% 1 $ s [/ 1]', 'block', array ('PrestaShop ™', '2020' , '©'), falso )nella riga 234 di smartyfront.config.inc.php
a smartyTranslate ( array ('s' => '[1]% 3 $ s% 2 $ s - Software e-commerce di% 1 $ s [/ 1]', 'mod' => 'jxmegalayout', 'sprintf' => array ('PrestaShop ™', '2020', '©'), 'tags' => array ('<a class="_blank" href="http://www.prestashop.com">'), 'js' => false , 'pdf' => false , 'd' => null ), oggetto ( SmartyDevTemplate ) )in 46dc894f434550487df05e4ced3127ca91df78e7_2.file.block.tpl.php linea 38
a content_5eeb2962cc3960_84567041 ( oggetto ( SmartyDevTemplate ) )nella riga 123 di smarty_template_resource_base.php
at Smarty_Template_Resource_Base -> getRenderedTemplateCode ( oggetto ( SmartyDevTemplate ) )nella riga 114 di smarty_template_compiled.php
su Smarty_Template_Compiled -> render ( oggetto ( SmartyDevTemplate ) )nella riga 216 di smarty_internal_template.php
su Smarty_Internal_Template -> render ( false , 0 )nella riga 232 di smarty_internal_templatebase.php
su Smarty_Internal_TemplateBase -> _execute ( oggetto ( SmartyDevTemplate ), null , null , null , 0 )nella riga 116 di smarty_internal_templatebase.php
at Smarty_Internal_TemplateBase -> fetch ( null , null , null , null , false , true , false )nella riga 40 di SmartyDevTemplate.php
su SmartyDevTemplateCore -> fetch ()nella riga Module.php 2409
at ModuleCore -> display ( '/ modules / jxmegalayout /', '/views/templates/hook/layouts/block.tpl' )nella linea jxmegalayout.php 1968
at Jxmegalayout -> renderLayoutFront ( array ( array ( array ( array ( array ('id_item' => '1', 'id_layout' => '1', 'id_parent' => '0', 'type' => 'wrapper', 'sort_order' => '1', 'specific_class' => 'container', 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' = > null , 'col_xl' => null , 'col_xxl' => null , 'module_name' =>null , 'id_unique' => 'it_IHHEFKZKZBAJ', 'origin_hook' => null , 'extra_css' => null ),array ('id_item' => '16', 'id_layout' => '1', 'id_parent' => '0', 'type' => 'row', 'sort_order' => '2', 'specific_class' => null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' => null , 'col_xl' => null , 'col_xxl' = > null , 'module_name' => null , 'id_unique' => 'it_SPIKQQCKWOOB', 'origin_hook' => null , 'extra_css' =>null ))), array ( array ( array('id_item' => '2', 'id_layout' => '1', 'id_parent' => '1', 'type' => 'row', 'sort_order' => '3', 'specific_class' = > '', 'col' => '', 'col_xs' => '', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' => ' ',' col_xxl '=>' ',' nome_modulo '=>' ',' id_unique '=>' it_VYFQKHIHBILU ',' origin_hook '=>' ',' extra_css '=>' '), array (' id_item '= > '11', 'id_layout' => '1', 'id_parent' => '1', 'type' => 'row', 'sort_order'=> '4', 'specific_class' => 'text-center text-md-left align-items-md-center well-1 mt-4', 'col' => '', 'col_xs' => '' , 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' => '', 'col_xxl' => '', 'nome_modulo' => '', ' id_unique '=>' it_NAQJYMDXBABW ',' origin_hook '=>' ',' extra_css '=>' '), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_NAQJYMDXBABW ',' origin_hook '=>' ',' extra_css '=>' '), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_NAQJYMDXBABW ',' origin_hook '=>' ',' extra_css '=>' '), array('id_item' => '231', 'id_layout' => '1', 'id_parent' => '1', 'type' => 'row', 'sort_order' => '2', 'specific_class' = > '', 'col' => '', 'col_xs' => '', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' => ' ',' col_xxl '=>' ',' nome_modulo '=>' ',' id_unique '=>' it_MRAJWIJATWDJ ',' origin_hook '=>' ',' extra_css '=>' '), array (' id_item '= > '235', 'id_layout' => '1', 'id_parent' => '1', 'type' => 'row', 'sort_order'=> '1', 'specific_class' => '', 'col' => '', 'col_xs' => '', 'col_sm' => '', 'col_md' => '', 'col_lg' = > '', 'col_xl' => '', 'col_xxl' => '', 'module_name' => '', 'id_unique' => 'it_DIFEADMFEWZW', 'origin_hook' => '', 'extra_css' => '')), array ( array'', 'id_unique' => 'it_DIFEADMFEWZW', 'origin_hook' => '', 'extra_css' => '')), array ( array'', 'id_unique' => 'it_DIFEADMFEWZW', 'origin_hook' => '', 'extra_css' => '')), array ( array('id_item' => '17', 'id_layout' => '1', 'id_parent' => '16', 'type' => 'col', 'sort_order' => '1', 'specific_class' = > null , 'col' => 'col-12', 'col_xs' => 'col-12', 'col_sm' => 'col-sm-12', 'col_md' => null , 'col_lg' => null , 'col_xl' => null , 'col_xxl' => null , 'module_name' => null , 'id_unique' => 'it_JELKCWDLZZVQ', 'origin_hook' => null , 'extra_css' => null ))),array ( array ( array('id_item' => '3', 'id_layout' => '1', 'id_parent' => '2', 'type' => 'col', 'sort_order' => '1', 'specific_class' = > '', 'col' => 'col-12', 'col_xs' => 'col-12', 'col_sm' => 'col-sm-12', 'col_md' => 'col-md-3 ',' col_lg '=>' ',' col_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_JETBIURJRXHF ',' origin_hook '=>' ' , 'extra_css' => ''), array ('id_item' => '5', 'id_layout' => '1', 'id_parent' => '2', 'type' => 'col ',' sort_order '=>' 2 ',' specific_class '=>' ',' col '=>' col-12 ',' col_xs '=>' col-12 ',' col_sm '=>' col- sm-12 ',' col_md '=>' col-md-3 ',' col_lg '=>' ',' col_xl '=>' ',' col_xxl '=>' ',' nome_modulo '=>' ', 'id_unique' => 'it_YHODPXMJMHBK', 'origin_hook' => '', 'extra_css' => ''), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_YHODPXMJMHBK ',' origin_hook '=>' '', 'extra_css' => ''), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_YHODPXMJMHBK ',' origin_hook '=>' '', 'extra_css' => ''), array('id_item' => '7', 'id_layout' => '1', 'id_parent' => '2', 'type' => 'col', 'sort_order' => '3', 'specific_class' = > '', 'col' => 'col-12', 'col_xs' => 'col-12', 'col_sm' => 'col-sm-12', 'col_md' => 'col-md-3 ',' col_lg '=>' ',' col_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_BPBYIABMCQWO ',' origin_hook '=>' ' , 'extra_css' => ''), array ('id_item' => '9', 'id_layout' => '1', 'id_parent' => '2', 'type' => 'col ',' sort_order '=>' 4 ',' specific_class '=>' ',' col '=>' col-12 ',' col_xs '=>' col-12 ',' col_sm '=>' col- sm-12 ',' col_md '=>' col-md-3 ',' col_lg '=>' ',' col_xl '=>' ',' col_xxl '=>' ',' nome_modulo '=>' ', 'id_unique' => 'it_VANUWRRQWTDI', 'origin_hook' => '', 'extra_css' => ''), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_VANUWRRQWTDI ',' origin_hook '=>' '', 'extra_css' => ''), arraycol_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ',' id_unique '=>' it_VANUWRRQWTDI ',' origin_hook '=>' '', 'extra_css' => ''), array('id_item' => '232', 'id_layout' => '1', 'id_parent' => '2', 'type' => 'col', 'sort_order' => '5', 'specific_class' = > '', 'col' => 'col', 'col_xs' => 'col', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' = > '', 'col_xxl' => '', 'nome_modulo' => '', 'id_unique' => 'it_OJDWWYTCUZXE', 'origin_hook' => '', 'extra_css' => '')), array ( array ('id_item' => '12', 'id_layout' => '1', 'id_parent' => '11', 'type' =>'col', 'sort_order' => '1', 'specific_class' => null , 'col' => 'col-12', 'col_xs' => 'col-12', 'col_sm' => 'col- sm-12 ',' col_md '=>' col-md-6 ',' col_lg '=> null ,' col_xl '=> null ,' col_xxl '=> null ,' module_name '=> nullnull , 'col_xxl' => null , 'module_name' => nullnull , 'col_xxl' => null , 'module_name' => null, 'id_unique' => 'it_YVZQORLDYDLA', 'origin_hook' => null , 'extra_css' => null ), array ('id_item' => '14', 'id_layout' => '1', 'id_parent' => '11', 'type' => 'col', 'sort_order' => '2', 'specific_class' => 'text-md-right mt-4 mt-md-0', 'col' => 'col -12 ',' col_xs '=>' col-12 ',' col_sm '=>' col-sm-12 ',' col_md '=>' col-md-6 ',' col_lg '=> null ,' col_xl '=> null ,' col_xxl '=> null ,' module_name '=> null ,'id_unique '=>' it_ORMIUZWGEDAF ',' origin_hook '=> null ,' extra_css '=> null ), array('id_item' => '221', 'id_layout' => '1', 'id_parent' => '11', 'type' => 'col', 'sort_order' => '3', 'specific_class' = > '', 'col' => 'col', 'col_xs' => 'col', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' = > '', 'col_xxl' => '', 'nome_modulo' => '', 'id_unique' => 'it_SCQFXYICXGFM', 'origin_hook' => '', 'extra_css' => '')), array ( array ('id_item' => '18', 'id_layout' => '1', 'id_parent' => '17', 'type' =>'module', 'sort_order' => '1', 'specific_class' => null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg '=> null ,' col_xl '=> null ,' col_xxl '=> nullcol_xl '=> null ,' col_xxl '=> nullcol_xl '=> null ,' col_xxl '=> null, 'module_name' => 'jxcompareproduct', 'id_unique' => 'it_DNXEADYNSOXY', 'origin_hook' => 'displayFooter', 'extra_css' => null )), array ( array ('id_item' => '233', 'id_layout' => '1', 'id_parent' => '231', 'type' => 'col', 'sort_order' => '1', 'specific_class' => '', 'col' => ' col ',' col_xs '=>' col ',' col_sm '=>' ',' col_md '=>' ',' col_lg '=>' ',' col_xl '=>' ',' col_xxl '=>' ',' nome_modulo '=>' ',' id_unique '=>'it_IPQZNLSZHYBC ',' origin_hook '=>' ',' extra_css '=>' ')), array ( array('id_item' => '236', 'id_layout' => '1', 'id_parent' => '235', 'type' => 'col', 'sort_order' => '1', 'specific_class' = > '', 'col' => 'col-1', 'col_xs' => 'col-1', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' => '', 'col_xxl' => '', 'module_name' => '', 'id_unique' => 'it_QRULEZIPCMRV', 'origin_hook' => '' ',' extra_css '=>' ')) ), array ( array ( array ('id_item' => '4', 'id_layout' => '1', 'id_parent' =>'3', 'type' => 'module', 'sort_order' => '1', 'specific_class' => null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' => null , 'col_xl' => nullnull , 'col_xl' => nullnull , 'col_xl' => null, 'col_xxl' => null , 'module_name' => 'ps_linklist', 'id_unique' => 'it_LJQGOCEPFSEK', 'origin_hook' => 'displayFooter', 'extra_css' => null )), array ( array ('id_item '=>' 6 ',' id_layout '=>' 1 ',' id_parent '=>' 5 ',' type '=>' module ',' sort_order '=>' 1 ',' specific_class '=> null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' => null , 'col_xl '=> null ,' col_xxl '=> null ,' module_name '=>' ps_categorytree ',' id_unique '=>' it_PXTCFPJFXASG ',' origin_hook '=>' displayFooter ',' extra_css '=>null )), array ( array ('id_item' => '8', 'id_layout' => '1', 'id_parent' => '7', 'type' => 'module', 'sort_order' => ' 1 ',' specific_class '=> null ,' col '=> null ,' col_xs '=> null ,' col_sm '=> null ,' col_md '=> null ,' col_lg '=> null ,' col_xl '=> null , 'col_xxl' => null , 'module_name' => 'ps_customeraccountlinks', 'id_unique' => 'it_BBHOSBGTFLOW', 'origin_hook' => 'displayFooter ',' extra_css '=> null )), array ( array('id_item' => '10', 'id_layout' => '1', 'id_parent' => '9', 'type' => 'module', 'sort_order' => '1', 'specific_class' = > null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' => null , 'col_xl' => null , 'col_xxl' => null , 'module_name' => 'ps_contactinfo', 'id_unique' => 'it_BLRBWBKDPIHQ', 'origin_hook' => 'displayFooter', 'extra_css' => null )),array ( array ('id_item' => '13', 'id_layout' => '1', 'id_parent' => '12', 'type' => 'block', 'sort_order' => '1', ' specific_class '=> null ,' col '=>null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null , 'col_lg' => null , 'col_xl' => null , 'col_xxl' => null , 'module_name' => ' copyright ',' id_unique '=>' it_KZKJRGULJCJN ',' origin_hook '=> null ,' extra_css '=> null )), array ( array (' id_item '=>' 15 ',' id_layout '=>' 1 ', 'id_parent' => '14', 'type' => 'content', 'sort_order' => '1', 'specific_class' =>null , 'col' => null , 'col_xs' => null , 'col_sm' => null , 'col_md' => null, 'col_lg' => null , 'col_xl' => null , 'col_xxl' => null , 'module_name' => 'banner-4', 'id_unique' => 'it_DGGHSPRVVFWQ', 'origin_hook' => null , ' extra_css '=> null )), array ( array (' id_item '=>' 234 ',' id_layout '=>' 1 ',' id_parent '=>' 233 ',' type '=>' module ',' sort_order '=>' 1 ',' specific_class '=>' ',' col '=>' ',' col_xs '=>' ',' col_sm '=>' ',' col_md '=>' ',' col_lg ' => '', 'col_xl '=>' ',' col_xxl '=>' ',' module_name '=>' ps_emailsubscription ',' id_unique '=>' it_GYEPFOUCKDSJ ',' origin_hook '=>' displayFooter ',' extra_css '=>' ') ), array ( array('id_item' => '237', 'id_layout' => '1', 'id_parent' => '236', 'type' => 'module', 'sort_order' => '1', 'specific_class' = > '', 'col' => '', 'col_xs' => '', 'col_sm' => '', 'col_md' => '', 'col_lg' => '', 'col_xl' => ' ',' col_xxl '=>' ',' nome_modulo '=>' blockreassurance ',' id_unique '=>' it_FFPIHULKDHAS ',' origin_hook '=>' displayFooterAfter ',' extra_css '=>' ')))), 3 , array('<! - begin module / jxmegalayout // views / templates / hook / layouts / layout.tpl -> <div class = "module"> <! - inizio modulo: ps_linklist / views / templates / hook / linkblock .tpl -> <! - begin /web/htdocs/www.assodifiorimaternity.it/home/themes/theme1511/modules/ps_linklist/views/templates/hook/linkblock.tpl -> <div class = "link- block footer-block "> <h3 class =" d-none d-md-block link-list-title "> Informazioni </h3> <h3 class =" d-flex justify-content-between align-items-center compresso d-md-none elenco-titoli-titolo "data-target =" # link_block_11395 "data-toggle =" collapse "> Informazioni <i class =" fa fa-angle-down "aria-hidden =" true "> </ i> </h3> <ul id = "link_block_11395"class = "list-default-sm collapse d-md-block"> <li> <a id = "link-cms-page-1-6" class = "cms-page-link" href = "https: // www.assodifiorimaternity.it/content/1-spedizione-e-consegna-del-tuo-ordine "title =" I tuoi capi premaman preferiti in poco tempo a casa tua! Pronti per essere indossati. "> Spedizione e consegna del tuo ordine </a> </li> <li> <a id = "link-cms-page-2-6" class = "cms-page-link" href = "https://www.assodifiorimaternity.it/content/ 2-privacy-policy "title =" Privacy "> Informativa sulla privacy </a></li> <li> <a id = "link-cms-page-3-6" class = "cms-page-link" href = "https://www.assodifiorimaternity.it/content/3-termini- e-condizioni "title =" Benvenuto sul nostro sito web "www.assodifiorimaternity.it". L & # 039; accesso e l & # 039; uso di www.assodifiorimaternity.it sono attività regolate dalle presenti Condizioni Generali d & # 039; Uso. L & # 039; accesso e l & # 039; uso di questo sito web così come l & # 039; acquisto dei prodotti su www.assodifiorimaternity.it, presuppone la lettura, la conoscenza e l & # 039; accettazione di queste condizioni Generali d & # 039 ; Uso. "> Termini e condizioni </a> </li> <li><a id = "link-cms-page-4-6" class = "cms-page-link" href = "https://www.assodifiorimaternity.it/content/4-negozio-premaman-terni" title = " Ciao sono Cristina Sabatini e vi accompagnerò nel mio mondo fiorito di abbigliamento premaman qui a Terni "> L & # 039; idea nasce da qui ... </a> </li> <li> <a id =" link-cms- page-5-6 "class =" cms-page-link "href =" https://www.assodifiorimaternity.it/content/5-pagamento-sicuro "title =" Paga i tuoi acquisti premaman in tutta sicurezza su assodifiorimaternity. "" Pagamento sicuro </a> </ li> <li> <a id = "link-cms-page-7-6" class = "cms-page-link" href = "https://www.assodifiorimaternity.it/content/7-resi-e -restituzioni "title =" Resi e cambi "> Resi e restituzioni </a> </li> </ul> </div> <! - end /web/htdocs/www.assodifiorimaternity.it/home/themes/ theme1511 / modules / ps_linklist / views / templates / hook / linkblock.tpl -> <! - end module: ps_linklist / views / templates / hook / linkblock.tpl -> </div> <! - end modules / jxmegalayout // views / templates / hook / layouts / layout.tpl -> ',' ',' <! - begin modules / jxmegalayout // views / templates / hook / layouts / layout.tpl -> <classe div = "modulo"> <! - modulo start: ps_categorytree / views / templates / hook / ps_categorytree.tpl -> <! - begin /web/htdocs/www.assodifiorimaternity.it/home/themes/theme1511/modules/ps_categorytree/views/templates/ hook / ps_categorytree.tpl -> <div class = "blocco-categorie footer-block-list"> <h3 class = "d-none d-md-block link-list-title"> Categorie </h3> < h3 class = "h6 d-flex justify-content-between align-items-center d-md-none link-list-title" data-target = "# category-top-menu" data-toggle = "collapse"> Categorie <i class = "fa fa-angle-down" aria-hidden = "true"> </i> </h3> <ul id = "category-top-menu" class = "categoria-top-menu collapse d- md-block "> <li class =" home-category "> <a class ="h4 "href =" https://www.assodifiorimaternity.it/2-home "> Home </a> </li> <li> <ul class =" link-block "> <li data-depth =" 0 "> <a href="https://www.assodifiorimaternity.it/13-idee-regalo"> Idee regalo </a> </li> <li data-depth =" 0 "> <a href =" https : //www.assodifiorimaternity.it/14-baby-wrap "> Baby wrap </a> </li> <li data-depth =" 0 "> <a href =" https://www.assodifiorimaternity.it / 17-abbigliamento "> Abbigliamento </a> </li></ul> </li> </ul> </div> <! - end /web/htdocs/www.assodifiorimaternity.it/home/themes /theme1511/modules/ps_categorytree/views/templates/hook/ps_categorytree.tpl -> <! - end module: ps_categorytree / views / templates / hook / ps_categorytree.tpl -> </div> <! - end modules / jxmegalayout // views / templates / hook / layouts / layout.tpl -> ',' ',' <! - start modules / jxmegalayout // views / template / hook / layouts / layout.tpl -> <div class = "module"> <! - begin module: ps_customeraccountlinks / ps_customeraccountlinks.tpl -> <! - begin /web/htdocs/www.assodifiorimaternity.it /home/themes/theme1511/modules/ps_customeraccountlinks/ps_customeraccountlinks.tpl -> <div class = "block_myaccount_infos footer-block"> <h3 class = "d-none d-none d-md-block link-list-title"> <a href = "https://www.assodifiorimaternity.it/account" rel = "nofollow"> Il tuo account </a> </h3> <h3 class = "d-flex justify-content-between align-items-center compresso d-md-none link-list-title "data-target = "# account-list-block" data-toggle = "collapse"> Il tuo account <i class = "fa fa-angle-down" aria-hidden = "true"> </i> </ h3 > <ul id = "account-list-block" class = "list-default-sm collapse d-md-block"> <li> <a href = "https://www

****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
-->

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @Tatyart31 ,
Please, send your request in English.
English is the norm on GitHub.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by florine2623** [comment]
I'll close your issue as you are not using our template properly.
