### ISSUE TITLE
Shipping cost is taxes exluded for EU B2B customers

### ISSUE THREAD

**Issue by Cameros-agency** [PrestaShop/PrestaShop#19867]
Hi,
We're having an issue about taxes included or not on shipping cost. Our shop is located in France and when foreign European business customers proceed to checkout, shipping costs are taxes excluded. 

1. Add product to your cart
2. Proceed to checkout
4. Create an address in a European country (e.g. Germany) address without VAT number  
3. Create the same address with a VAT number
5. Select a non-free shipping method
6. Shipping cost are taxes included wich is ok
7. Change address with the one with VAT number
8. Shipping cost are taxes excluded

Prestashop vatnumber module is installed and configured with Home country to France. A tax rule with 20.00% tax for EU country is defined in back-office and it is applied to our delivery methods. B2B client mode is disabled.

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
* vatnumber version 2.1.0

**Comment by florine2623** [comment]
Hi @CIMEOS ,
I managed to reproduce the same issue in PS 1.7.6.5 and 1.7.7.0 with vatnumber v2.1.0.

With a European country + VAT number = the shipping fee tax needs to be tax included ?
Thanks!

**Comment by Hlavtox** [comment]
@CIMEOS @florine2623 That's how it's suppsed to be.

You sell to VAT liable person in EU, the whole order is without VAT.

**Comment by Cameros-agency** [comment]
@florine2623 @Hlavtox 
Indeed, after lots of research, the whole order has to be without VAT, my bad.
However, there is another issue in back-office. If you proceed to checkout and confirm the order, you can see in order details in back-office that shipping costs are taxes included. Here is a screenshot.
![order_detail_back](https://user-images.githubusercontent.com/6168624/85390371-0a673f00-b549-11ea-873d-c551a6e12f9f.jpg)
On the invoice, shipping costs are taxes excluded.
![invoice](https://user-images.githubusercontent.com/6168624/85390392-1226e380-b549-11ea-9eff-8740b79d3a49.jpg)
Can you reproduce this? Should I open a new issue for this one?

**Comment by Cameros-agency** [comment]
Nevermind, with Prestashop official VAT number module, taxes are not applied.
