### ISSUE TITLE
Not possible to delete or edit name of attached files

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19877]
#### Describe the bug
There is not possible to delete attached files for the product in BO.
There is not possible to edit the Title of attached files for the product in BO.

#### Expected behavior
Add a new button to the product where will be possible to delete attached file.
Add a new button to the product where will be possible to edit the Title.

#### Steps to Reproduce
1. Go to BO > Catalog > Products > select any product with detail info > Options
2. Add a new pdf file to the product 
3. After upload you'll see the new file in the table, but it is not possible to delete this file and also not possible to edit Title of this file

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by PierreRambaud** [comment]
Hi and thanks for your report.

When you upload a theme, there is a link below saying you need to go to `Catalog -> Files` to be able to edit / rename / remove the file.
You also have a checkbox if you want to remove the file from the product.

![image](https://user-images.githubusercontent.com/1462701/85268688-1e427080-b477-11ea-8760-a8dc90a63a10.png)


Kind regards

**Comment by juraj1000** [comment]
Hello,
I think now I understand it. It is quite discomfortable. If you have 100 products with 100 different attached files then you have to select correct file for every product. And there is 100 files for selection. 
Would it be possible to change it and upload one file only to one product?

**Comment by miszun** [comment]
Hi,
the problem still exists in Prestashop 1.7.8.3.
If you haven't added a file via Catalog>Files only via button available on Product's Option tab, there is no way of removing it.  At least I can't find any way to remove it.  The file is not shown in Catalog>Files.  Button for adding file is still there, tempting to use for quick file attachment way.  What's worse, even though the file is unchecked on the Product>Options tab, the link to this file still remains on the product page.  Can anyone help with removing it?
Thank you in advance
