### ISSUE TITLE
Multiple catalogs

### ISSUE THREAD

**Issue by niccolobusato** [PrestaShop/PrestaShop#19872]
#### Is your feature request related to a problem?

Ability to have multiple catalogs within specific categories for each

#### Describe the solution you'd like

Ability to have multiple catalogs within specific categories for each

#### Alternatives you've considered

show only (filter) category related to the product type (on product creation)

#### Additional context

very useful when you have many products of various kinds or multi-vendor stores

**Comment by florine2623** [comment]
Hi @niccolobusato ,
On what page of the BO would you want to see the 'catalog' ?
Can you share screenshots with the feature you would like to see ? So it'll be clearer for our team.
Thanks!

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
