### ISSUE TITLE
why dont implement and theme update system like a wordpress

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#19879]
#### Is your feature request related to a problem?

is a good idea implement a theme update sistem, like a wordpress, whit this adapt the themes to the new prestashop core are more efficient, whit this is more easy make child theme too, bacause this dont broken the personalizations

#### Describe the solution you'd like

implement a theme update sistem

**Comment by matks** [comment]
Wordpress update system is one of the most efficient I have ever seen :) but copying it is no easy task. They achieved something great with, I guess, hard work and lot of time and resources.

We currently do not have the required amount of time and resources to do it as other huge (and critical) topics need our energy and time but, yeah, if we could get some inspiration for PrestaShop auto-upgrade, Wordpress would be a great subject 😄 

I close the issue as I think I have provided a complete answer that need no further explanations 😉
