### ISSUE TITLE
Remove duplicated info_outline icon in stock alert

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#19881]
#### Describe the bug

Duplicated info_outline icon in stock alert

#### Expected behavior

![image](https://user-images.githubusercontent.com/16455155/85200067-a2b8b600-b2f4-11ea-97fc-d7861ee13cf1.png)

#### Steps to Reproduce

1. Go to BO > Stock
2. Make sure that you are in ALL SHOP 
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16455155/85200092-ce3ba080-b2f4-11ea-891f-b64eb5f344fe.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by PierreRambaud** [comment]
Thanks for the report, and of course for the linked Pull request :heart:

**Comment by marionf** [comment]
@PierreRambaud Could you add missing labels like BO ? Stock if it concerns the stock page and maybe multistore if the issue happens in a multistore context ? And keep only one severity label ? 
Thanks :wink:

**Comment by PierreRambaud** [comment]
> @PierreRambaud Could you add missing labels like BO ? Stock if it concerns the stock page and maybe multistore if the issue happens in a multistore context ? And keep only one severity label ?
> Thanks

I did not try if it concerns the multistore, but since it concerns the single store, the multistore will be obviously tested during the QA test (I hope :thinking: )
