### ISSUE TITLE
Unable to write in en-US in installation process

### ISSUE THREAD

**Issue by Arman-Hosseini** [PrestaShop/PrestaShop#19885]
When I try to install PrestaShop, this error appears: 

        1: Unable to write into "en-US"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer")

Version: **1.7.6.5**
Same issue: #14812
I was read that issue, but It didn't help.

**Comment by PierreRambaud** [comment]
Hello @Arman-Hosseini,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Kind regards,

**Comment by Arman-Hosseini** [comment]
Hi @PierreRambaud ,
In fact, this is a bug. Maybe I need to open a bug report issue?
