### ISSUE TITLE
No db entry for actionCustomerLogoutBefore or actionCustomerLogoutAfter

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#19894]
#### Describe the bug

There are no entries in the ps_hook table for actionCustomerLogoutBefore or actionCustomerLogoutAfter, so you can't hook modules to them.

I'm testing on 1.7.6, but I don't see them in the database for 1.7.7 either.

Adding the entries to the db, resolves the issue

#### Expected behavior

You should be able to hook to these positions.

#### Steps to Reproduce

1. With a module that provides hook code to these hook, try to transplant the module to them.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by PierreRambaud** [comment]
Hi and thanks for your report.

I manage to reproduce the issue.

It's not a regression and it's a very old issue #3690

Thanks again ;)
