### ISSUE TITLE
 1.7.6 translation section, improvements in the management of expressions

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#19891]
Hi,
I did not understand how to search for translations, I think there is something that escapes me, I would suggest inserting the lost phrases as in 1.6, and make the search easier:
if I enter a phrase, the system should show first all the fields containing the word, then on the left decide to filter according to our needs, or have a filter like "every".
Example:
I'm looking for to translate to Italian language the following words customer, werehouse, country  etc... shown in the image.
<img width="1243" alt="Schermata 2020-06-22 alle 11 31 08" src="https://user-images.githubusercontent.com/28685316/85278597-72545180-b485-11ea-85ea-577ba8a93486.png">
I apologize if this has already been discussed.
Thanks for any reply.
Balla.

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!

**Comment by ballashop** [comment]
@sarahdib 
I'm desolated
Thank you.
Balla
