### ISSUE TITLE
Update product's price in the order does not update the discount

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19890]
Be aware of the EPIC - BO - Display and update error on cart rule in the order #19594 to solve this issue

#### Describe the bug

On the back-office, when I create a percentage discount and then change the product's price on the order, the discount is not updated.

#### Expected behavior

The discount should apply the 50% reduction on all the product amount even if after they are updated 

#### Steps to Reproduce

1. Add the product to any order
2. Create a cart rule of 50% in the order page
3. edit the product price
4. See error - wrong discount total

**Screenshots**

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sowbiba** [comment]
https://www.loom.com/share/b25b212a9af34b679f747977d435e291

**Comment by marionf** [comment]
@MatShir Could you add FO/BO labels and the version concerned by this issue ? :wink:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20083
