### ISSUE TITLE
Deleted categories 302 redirects

### ISSUE THREAD

**Issue by rederijker** [PrestaShop/PrestaShop#19892]
#### Describe the bug
Deleted categories are redirected with status code 302 at address prestashop-site/index.php? Controller=404 

All non-existent  address similar to path id-categoryname redirects at prestashop-site/index.php?Controller=404

#### Expected behavior

prestashop should return 404 status code without redirects 

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2

**Comment by PierreRambaud** [comment]
HI and thanks for your report.

I manage to reproduce, and you're right, we shouldn't have a 302 redirect to the 404 page. :+1:

**Comment by rederijker** [comment]
thank you so much @PierreRambaud. it is a very serious SEO issue

**Comment by kevin-schmitt** [comment]
Hello,

Can you assign to me please for first contribution :) ?

**Comment by colinegin** [comment]
Go ahead @kevin-schmitt ! Just don't forget to associate this issue to your PR :)

**Comment by Xaconi** [comment]
Hi!

If there's no one else with this, can you assign me? 😃

**Comment by PierreRambaud** [comment]
> Hi!
> 
> If there's no one else with this, can you assign me?

Let's go! :+1:
