### ISSUE TITLE
BO - Product / Specific price edit return error

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19907]
## Describe the bug

When trying to update a specific price for a product a error notification is displayed

#### Expected behavior

The specific price should be updated correctly

#### Steps to Reproduce

1. Go to BO => Catalog => product
2. Select a product and add a specific price
3. Try to update the previously created specific price

**Screenshots**

https://drive.google.com/file/d/1qGKArUi4KA0EDrX_dSDp2DrrpaUPRHsb/view?usp=sharing

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by marionf** [comment]
Hello @SD1982 
A similar issue has been fixed yesterday: https://github.com/PrestaShop/PrestaShop/issues/18751 by this PR: https://github.com/PrestaShop/PrestaShop/pull/19865
Could you update your develop branch and check if you still have this issue ?

**Comment by SD1982** [comment]
Hi @marionf Oups my bad it seems that my shop was not up to date !! I close this issue
