### ISSUE TITLE
Carrier Selection & Range has no effect issue

### ISSUE THREAD

**Issue by davidhardik** [PrestaShop/PrestaShop#19905]
#### Describe the bug

There is issue in selecting the delivery carrier and not putting the Handling charges/Free Shipping. When giving the ranges to Individual Carrier it shows the prices without respecting the ranges set. 

If added the Handling charge & Free shipping condition then also it shows all the carrier above the free shipping range and showing all the carrier as "Free Shipping".

Using Prestashop 1.7.6.4. 

#### Expected behavior

I expected it to work like if we select the ranges only those carrier falling in that range should be active with its prices and others should disable. Also, Carrier preferences should have Tax option and also it should be conditional where even if we select the Free shipping amount it should respect the range option and automatically pick up the ranges and display the cost or free shipping accordingly.

#### Steps to Reproduce

**1st Way - Without Handling/Free shipping charges**
1. Click on Carrier -> Add a new Carrier -> Enter the name, etc and then add the range for all countries selected between 0-199 -> Select/Deselect Add Handling Cost -> Add the range cost ->Finish 
2. Create another Carrier having range -> 200-700 and price range anything you want.
3. Add the product above 200 you will find that both carrier will have their price range where the 1st carrier shouldn't have the price range and should be either disabled or free.

**2nd Way - With Handling/Free shipping charges**
1. Click on Carrier -> Add a new Carrier -> Enter the name, etc and then add the range for all countries selected between 0-199 -> Select/Deselect Add Handling Cost -> Add the range cost ->Finish 
2. Create another Carrier having range -> 200-700 and price range anything you want.
3. Add the product above 200 you will find that both carrier will have their prices set to Free
4. Go to Carrier Preferences and add free ship starts at xyz amount with Handling charges

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3.16

**Comment by sarahdib** [comment]
Hello @davidhardik 

PrestaShop 1.7.6.4 isn't compatible with php 7.3 could you downgrade your php version and try again ?
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thank you!

**Comment by davidhardik** [comment]
Hi,

Just checked with lower version of PHP, same issue. Kindly let me know what else I can do?

Thank you

**Comment by florine2623** [comment]
Hi @davidhardik ,
You can choose the option Disable carrier in Carrier Editing Page when it is out of range :
![Capture d’écran 2020-06-25 à 12 32 24](https://user-images.githubusercontent.com/16019289/85703783-f99d0180-b6df-11ea-82b8-a690edaabb6d.png)
Thanks!

**Comment by prestascott** [comment]
Hello @davidhardik,

Since we had no news from you for more than 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!
