### ISSUE TITLE
Option "Allow ordering of out-of-stock products" doesn't work.

### ISSUE THREAD

**Issue by AnatoleRozan** [PrestaShop/PrestaShop#19909]
I enabled all of the options :
<img width="893" alt="1" src="https://user-images.githubusercontent.com/38098728/85393875-01c53780-b54e-11ea-9126-28f3ded6479c.png">
<img width="452" alt="2" src="https://user-images.githubusercontent.com/38098728/85393889-0689eb80-b54e-11ea-9ef4-a3533a1a69e6.png">
<img width="573" alt="3" src="https://user-images.githubusercontent.com/38098728/85393892-0853af00-b54e-11ea-8cb3-62ca395baca6.png">

And it is still impossible to buy an out of stock product.
<img width="1792" alt="4" src="https://user-images.githubusercontent.com/38098728/85393948-23262380-b54e-11ea-93b1-b1e1430b42e9.png">

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: PHP7

**Comment by AnatoleRozan** [comment]
Fixed with this Topic : https://www.prestashop.com/forums/topic/591210-ps-1704-out-of-stock-orders-not-working/
(message by keizer)

Could some validate this problem and solution? Because I don't know if it's the proper one.

**Comment by rdy4ever** [comment]
> Fixed with this Topic : https://www.prestashop.com/forums/topic/591210-ps-1704-out-of-stock-orders-not-working/
> (message by keizer)
> 
> Could some validate this problem and solution? Because I don't know if it's the proper one.

That solution is wrong. This way the button will always be active, even if you have "allow out of stock" disabled for a product.
This condition will work:
`{if !$product.add_to_cart_url}disabled{/if}`

As you can see, that's the [original condition](https://github.com/PrestaShop/PrestaShop/blob/afc4b86c4a5634ddcdae87e08865590c6c4850b6/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl#L53) in classic theme.

This condition in your theme is clearly wrong:
`{if !$product.add_to_cart_url || $product.quantity_wanted>$product.quantity}`
because the last part only checks product quantity, regaldless if allow out of stock is active.

**Comment by AnatoleRozan** [comment]
> > Fixed with this Topic : https://www.prestashop.com/forums/topic/591210-ps-1704-out-of-stock-orders-not-working/
> > (message by keizer)
> > Could some validate this problem and solution? Because I don't know if it's the proper one.
> 
> That solution is wrong. This way the button will always be active, even if you have "allow out of stock" disabled for a product.
> This condition will work:
> `{if !$product.add_to_cart_url}disabled{/if}`
> 
> As you can see, that's the [original condition](https://github.com/PrestaShop/PrestaShop/blob/afc4b86c4a5634ddcdae87e08865590c6c4850b6/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl#L53) in classic theme.
> 
> This condition in your theme is clearly wrong:
> `{if !$product.add_to_cart_url || $product.quantity_wanted>$product.quantity}`
> because the last part only checks product quantity, regaldless if allow out of stock is active.

Ok, how do you feel about that. Is it a Prestashop issue? I enabled all the options (as you can see in the attached files) but it is still impossible to order the out-of-stock products.

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

<img width="1170" alt="Capture d’écran 2020-06-23 à 14 30 01" src="https://user-images.githubusercontent.com/3034677/85403677-15789a00-b55e-11ea-8bc9-442a7e27ca1e.png">

<img width="1280" alt="Capture d’écran 2020-06-23 à 14 31 35" src="https://user-images.githubusercontent.com/3034677/85403805-4953bf80-b55e-11ea-9c47-ee1960aa1e35.png">


Thank you!

**Comment by rdy4ever** [comment]
> > > Fixed with this Topic : https://www.prestashop.com/forums/topic/591210-ps-1704-out-of-stock-orders-not-working/
> > > (message by keizer)
> > > Could some validate this problem and solution? Because I don't know if it's the proper one.
> > 
> > 
> > That solution is wrong. This way the button will always be active, even if you have "allow out of stock" disabled for a product.
> > This condition will work:
> > `{if !$product.add_to_cart_url}disabled{/if}`
> > As you can see, that's the [original condition](https://github.com/PrestaShop/PrestaShop/blob/afc4b86c4a5634ddcdae87e08865590c6c4850b6/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl#L53) in classic theme.
> > This condition in your theme is clearly wrong:
> > `{if !$product.add_to_cart_url || $product.quantity_wanted>$product.quantity}`
> > because the last part only checks product quantity, regaldless if allow out of stock is active.
> 
> Ok, how do you feel about that. Is it a Prestashop issue? I enabled all the options (as you can see in the attached files) but it is still impossible to order the out-of-stock products.

Have you tried with just this condition? It should work.
`{if !$product.add_to_cart_url}disabled{/if}`

**Comment by AnatoleRozan** [comment]
> > > > Fixed with this Topic : https://www.prestashop.com/forums/topic/591210-ps-1704-out-of-stock-orders-not-working/
> > > > (message by keizer)
> > > > Could some validate this problem and solution? Because I don't know if it's the proper one.
> > > 
> > > 
> > > That solution is wrong. This way the button will always be active, even if you have "allow out of stock" disabled for a product.
> > > This condition will work:
> > > `{if !$product.add_to_cart_url}disabled{/if}`
> > > As you can see, that's the [original condition](https://github.com/PrestaShop/PrestaShop/blob/afc4b86c4a5634ddcdae87e08865590c6c4850b6/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl#L53) in classic theme.
> > > This condition in your theme is clearly wrong:
> > > `{if !$product.add_to_cart_url || $product.quantity_wanted>$product.quantity}`
> > > because the last part only checks product quantity, regaldless if allow out of stock is active.
> > 
> > 
> > Ok, how do you feel about that. Is it a Prestashop issue? I enabled all the options (as you can see in the attached files) but it is still impossible to order the out-of-stock products.
> 
> Have you tried with just this condition? It should work.
> `{if !$product.add_to_cart_url}disabled{/if}`

It works, thank you very much @rdy4ever !!!
This problem is weird. Maybe some people will report it in the future...

**Comment by rdy4ever** [comment]
> This problem is weird. Maybe some people will report it in the future...

It's not weird if you understand what the condition does. Plus, it's not present in the classic theme so it could be a problem only in old 3rd party themes that were not updated by their author.
Glad your shop is OK now.
