### ISSUE TITLE
AdminCustomerController not found

### ISSUE THREAD

**Issue by jevans1808** [PrestaShop/PrestaShop#19910]
I'm working on a fix on my local setup to an issue I've found in 1.7.6.2 with regards to admin pages linking to a customer entry e.g. clicking the customer link in an order can't return CustomerController. I've found this to be due to the Customer Controller now being handled via the twig templates and Symfony, but it doesn't appear as though the other links have been updated to reflect this. So I've been updating these to reflect the url required to access a customer entry, but the issue I am now getting is Invalid Token. Is anyone aware of how the security tokens are handled when moving from an old style controller to a new Symfony controller and how I might get around this issue

#### Expected behavior

When clicking on the link, it will take the user to the customer page requested, as it does in 1.6

#### Steps to Reproduce

1. Go to either an order, or a message in the customer services
2. Click on the name of the customer that links to their account
3. See error, where the AdminCustomerController is not found. I have attempted my own fix for this which has come across a roadblock.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @jevans1808 

This bug seems fixed in the last stable version 1.7.6.5.

You can upgrade in order to fix this issue.

Thank you!
