### ISSUE TITLE
Customer Service, not possible to configure gmail

### ISSUE THREAD

**Issue by roberto3211** [PrestaShop/PrestaShop#19916]
Prestashop 1.7.6.5.
PHP 7.2
In Customer Service menu, it is not possible to configure a gmail account.
See error below, I tested as well with the option validate=yes OR novalidate=yes.

I followed carefully all suggestions on gmail site about configuration.
Tested with different email accounts, same result.
Tested with different computer clients and users.
On the contrary, same account with same configuration, can fit on Thunderbird and Outlook (on my computer) without problems!!

Could the error be on server? Is there any other configuration to set on server?
It is not specified in the Help if there is any prestashop server port configuration that can block connection.
Examples with gmail configuration could help a lot of desperate forum people. 

![prestashop_issue_gmail_configuration](https://user-images.githubusercontent.com/45822595/85459257-44186400-b5a2-11ea-95cf-ffa71010c2c5.png)

**Comment by roberto3211** [comment]
In reference to my post and to prevent any doubt, I attach the check that on the server the port 993 is open.
![OpenPort993](https://user-images.githubusercontent.com/45822595/85777226-b8c5dc80-b721-11ea-8d46-e0ed4506bfc0.png)

**Comment by florine2623** [comment]
Hi @roberto3211 ,
Have you enable IMAP in your gmail account ?
![Capture d’écran 2020-06-26 à 11 22 41](https://user-images.githubusercontent.com/16019289/85842074-60cdbb00-b79f-11ea-9f7e-3887a4b6cef2.png)
Thanks!

**Comment by roberto3211** [comment]
Yes, sure, as explained in my previous posts, I tested also the gmail configuration connecting to Outlook and Thunderbird on my personal computer.
Therefore the error in not in the gmail configuration. Moreover port 993 on webserver results open.
The issue should be carried out from an error in the program or due to a webserver configuration that I do not know.
Thanks

**Comment by Progi1984** [comment]
@roberto3211 I think the problem come from you server or your provider which doesn't permit to contact gmail.

Do you try from your hosting to `telnet imap.gmail.com 993`

If the return is : `Connected to imap.gmail.com.`, you don't have any error
If the return is : `telnet: connect to address imap.gmail.com: Connection refused`, your provider block outcoming connection.

**Comment by khouloudbelguith** [comment]
Hi @roberto3211,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by roberto3211** [comment]
Thanks to everyone.
I share here the solution I found to help anyone with the same issue.
My service Provider have a software Firewall which was blocking the port I was trying to use.
The detection software "open port finder" showed the port open and it was confusing me, but when I asked to my provider they confirmed they had to modify the firewall configuration.
