### ISSUE TITLE
Pagination should not impact the add product button in the order page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19918]
#### Describe the bug
The pagination and the buttons should be above the fold.

![image](https://user-images.githubusercontent.com/43613217/85525352-4eba1400-b609-11ea-9b22-88a292a14a82.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/27484094/83656134-79431f00-a5bf-11ea-9c33-63b9c3ffb7a5.png)

#### Steps to Reproduce

1. Open an order

**Screenshots**

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by marionf** [comment]
@MatShir Could you add the severity, FO/BO labels and the version concerned by this issue ? :wink:

**Comment by Progi1984** [comment]
@MatShir Do you accept this on smaller screens ?

![image](https://user-images.githubusercontent.com/1533248/85869281-c637a100-b7cb-11ea-8f5c-0b5ac632a3e6.png)

**Comment by Progi1984** [comment]
Fixed by #19937
