### ISSUE TITLE
BO - Product has no Save button bar

### ISSUE THREAD

**Issue by robinspruce** [PrestaShop/PrestaShop#19914]
#### Describe the bug

When i try to add or edit a product, the bar at the bottom with the save buttons does not appear

#### Expected behavior

On adding or editing a product the Save bar is at the bottom of the page

#### Steps to Reproduce

For me i got to Catalog>Products and either add a new or edit an existing one.

Selecting each of the product tabs, Description, Quantity, Shipping Price etc does not display the save buttons on the bar at the bottom of the page.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.3.18

**Comment by prestascott** [comment]
Hello @robinspruce, thank you for your report!

PrestaShop 1.7.5.1 isn't compatible with php 7.3 could you downgrade your php version and try again?
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thank you!

**Comment by robinspruce** [comment]
Hi Scott

Many thanks for coming back to me.  I have requested the hosting company
roll it back to 7.1, as i dont seem to be able to change it.  Just a note
also to say that the doc in the link refers to PHP 7.1 or later.

will test as soon as i hear back from them.

Kind regards

Robin

*~ Robin Spruce ~*
+1 649 431 4242

**Comment by robinspruce** [comment]
Hi Scott

Finally got the server reset to PHP7.1 and the save bar is now back.

Many thanks for your help.

Kind regards
Robin

*~ Robin Spruce ~*
+1 649 431 4242
