### ISSUE TITLE
BO - Customers / Wrong redirection after creating a new address from the customer detail page

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19912]
#### Describe the bug

After creating a new address from the customer detail page we are redirected to the addresses list instead of the customer detail page

#### Expected behavior

We should be redirected to the customer detail page

#### Steps to Reproduce

1. Go to Customers => Customers 
2. Select any customer and go to the customer detail page
3. Scroll down to the bottom of the page and in the address block click on the + icon to add a new address
4. Fill all the required fields and click on save 
5. See Error => redirected to the addresses list page instead of the customer detail page

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by marionf** [comment]
Hello @SD1982 
Could you add the bug label and the status (to do, TBR or TBS) ?
Are you sure it's not a regression of develop branch ?

**Comment by SD1982** [comment]
Hi @marionf i added the bug label status and it's not a regression

**Comment by marionf** [comment]
Humm, I don't see the bug label, I add it :)

**Comment by SD1982** [comment]
Oups i forgot to add this one ! Thanks @marionf

**Comment by boubkerbribri** [comment]
This issue is back on develop after this [PR](https://github.com/PrestaShop/PrestaShop/pull/20261) was merged.

**Comment by boubkerbribri** [comment]
I changed it to critical since the nightly fail on develop
