### ISSUE TITLE
URLs not Working after generating .htaccess

### ISSUE THREAD

**Issue by KwabeaAtakora** [PrestaShop/PrestaShop#19927]
Hi,

I 've migrated my prestashop site to an AWS server. However, when I click on the menus I get page not found errors. mod_rewrite has been enabled, php curl has been enabled. I 've also generated the friendly url. The url to my site is myurbanscents.com

The image beneath shows an error I am experiencing in my prestashop back office 
Kindly help me out 
![IMG-20200624-WA0006](https://user-images.githubusercontent.com/31692415/85622883-0e818280-b657-11ea-9a69-30ca51033b8d.jpg)

**Comment by florine2623** [comment]
Hi @KwabeaAtakora ,
Do you have access toy our BO ?
If yes, you can regenerate your htaccess, by going in Shop Parameters > Traffic & SEO > Save all block (no need to change the config)
Let me know how it goes, thanks!

**Comment by KwabeaAtakora** [comment]
@florine2623 I ve done that but the issue persists

**Comment by florine2623** [comment]
Try to : 
- Check in database, table `ps_configuration` if the url is correct
- Set permissions of img folder to 755 (recursive)

**Comment by KwabeaAtakora** [comment]
ps_configuration in the database? @florine2623

**Comment by florine2623** [comment]
Yes.
The values to check are : PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL :
![Capture d’écran 2020-06-25 à 15 57 32](https://user-images.githubusercontent.com/16019289/85733630-a1c0c380-b6fc-11ea-845c-a55985927a29.png)

**Comment by KwabeaAtakora** [comment]
Ok for me those are in ps_shop_url. Yes. The values are there as myurbanscents.com

**Comment by florine2623** [comment]
Have you tried to set permissions of img folder to 755 (recursive) ?
Check in you log file for any error in /var/log.
Also what is your version of PS and PHP ?

**Comment by KwabeaAtakora** [comment]
Done that img folder is set to 777 recursive

PS 1.7 php 7.2

**Comment by KwabeaAtakora** [comment]
The error at the back office is solved the categories can be seen however, the issue with the menus and It is not working persists

**Comment by florine2623** [comment]
Check in Traffic & SEO if these paths are correct :
![Capture d’écran 2020-06-26 à 09 15 43](https://user-images.githubusercontent.com/16019289/85830962-c3b65680-b78d-11ea-87ea-76d9e2fc907b.png)

**Comment by KwabeaAtakora** [comment]
Hi, 

The paths are correct. Attaching an image of the page
![trafficseo](https://user-images.githubusercontent.com/31692415/85843172-5952e580-b790-11ea-91c1-99357b3e987f.png)

**Comment by florine2623** [comment]
Search for Fatal error in your error log please, or send me the file directly

**Comment by KwabeaAtakora** [comment]
[logs.zip](https://github.com/PrestaShop/PrestaShop/files/4838372/logs.zip)
Above is my error log file

**Comment by Progi1984** [comment]
@KwabeaAtakora You have a fatal errror with `ttpopupnewsletter` module. Could you try to disable it ?

**Comment by KwabeaAtakora** [comment]
Alright

**Comment by KwabeaAtakora** [comment]
@Progi1984 Alright on it

**Comment by florine2623** [comment]
Hi @KwabeaAtakora ,
Did it resolve the issue ?

**Comment by KwabeaAtakora** [comment]
No it didnt

**Comment by florine2623** [comment]
Delete your cache and try again

**Comment by KwabeaAtakora** [comment]
Done that

**Comment by florine2623** [comment]
I can't reproduce the issue. I will close this issue. You might need to contact the support team here :
https://www.prestashop.com/en/support
Or a PrestaShop Agency :
https://www.prestashop.com/en/experts
