### ISSUE TITLE
Total amount is not calculated correctly

### ISSUE THREAD

**Issue by maperezr14** [PrestaShop/PrestaShop#19928]
The total amount is not calculated correctly, it should be the sum of sub-total + taxes, however this does not happen.

The cost of the product (taxes included) is 105.17 per unit.

The cost of the product (taxes excluded) is 89.13 per unit.

For 6 units the sub-total is 534.18 (tax excl.)
Taxes  (18%) 96.26
The Total purchase should be 630.44 , But the cart shows 538.18

**Comment by florine2623** [comment]
Hi @maperezr14 ,
What is the PS version you're using ?
Please send screenshots of that.
Thanks!

**Comment by maperezr14** [comment]
Hello, my PS version is 1.7.5, attached to this email are screenshots of my
shopping carts, I must specify that the amount of the subtotal is based on
the prices of the product without taxes included.

I understand, the total purchase should then be subtotal + tax, but this
does not happen.

**Comment by florine2623** [comment]
Please answer via GitHub, I don't see your screenshot.
If there's anything special about the product (combinations, discounts, etc), please specify it too.

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
