### ISSUE TITLE
Invalid theme structure on addons uploading

### ISSUE THREAD

**Issue by faadgoras** [PrestaShop/PrestaShop#19925]
Hello
I have issue with my 1.6 version theme creation when I try to upload it on addons store prestashop it give me error
Invalid Theme structure 
attached is screenshot of error
![prestashoperror](https://user-images.githubusercontent.com/67382724/85600491-fade1800-b666-11ea-9148-99628deb9353.png)

**Comment by florine2623** [comment]
Hi @faadgoras ,
PrestaShop is for PrestaShop software only.
Please contact mboumba.ext@prestashop.com for Addons issue.
Thanks!
