### ISSUE TITLE
BO: change address from detail order page cause a wrong carrier price update.

### ISSUE THREAD

**Issue by henrygri** [PrestaShop/PrestaShop#19939]
BO: change address from detail order page cause a wrong carrier price update.

If the address is updated from the order detail page and the courier has price ranges, the default range is applied by not checking the total price of the order.

If the order status is "Payment accepted" appear the message "Payed ... instead ...". 

Prestashop version 1.7.6.5

The steps to reproduce the bug are the follow:

- Clean install of Prestashop 1.7.6.5;
- The courier used must have at least two range;
- Place an order from FO or use a demo order;
- Open the interested order;
- Use the address box update button (not the switch address button) to change the order address (delivery or invoice address, it is the same);
- A new address is created when update the address;
- Return to order page and the carrier price change to default range price;
- If the order has "Payment Accepted" status, prestashop show "Payed ... instead ..." message.

![image](https://user-images.githubusercontent.com/42743088/85722340-7a64f900-b6f2-11ea-96db-c25ea6bd88c3.png)
![image](https://user-images.githubusercontent.com/42743088/85722516-a7191080-b6f2-11ea-892c-9f1615ffb9fd.png)
![image](https://user-images.githubusercontent.com/42743088/85722582-bac47700-b6f2-11ea-9e0e-736d6d5e07e6.png)
![image](https://user-images.githubusercontent.com/42743088/85722656-cd3eb080-b6f2-11ea-9fb9-adca8b29fe45.png)
![image](https://user-images.githubusercontent.com/42743088/85722805-f3645080-b6f2-11ea-92a0-6ad05e8e872b.png)
![image](https://user-images.githubusercontent.com/42743088/85722751-e5aecb00-b6f2-11ea-995d-9a3982ec853a.png)
![image](https://user-images.githubusercontent.com/42743088/85722895-06772080-b6f3-11ea-98d8-86b7d71bb2da.png)

if the order status is already "Payment accepted" in the order page is show the "Payed ... instead ..." alert:
![image](https://user-images.githubusercontent.com/42743088/85723667-bf3d5f80-b6f3-11ea-8a4e-e04c74559be9.png)

**Comment by florine2623** [comment]
Hi @henrygri ,
This page has totally been remodeled in PS 1.7.7.0.
You can see in my screen record that when I change the address of an order I manually created, there's no warning :
https://drive.google.com/file/d/1WA4OB7bTMxaegnNzvA7BiJTJ7ovXcODf/view

The reason you might have the warning might be because you change some configuration in your carrier before updating your order.

**Comment by henrygri** [comment]
Hi @florine2623 ,
I tried PS 1.7.7.0 and it worked correctly.

Thanks for your support
