### ISSUE TITLE
Stats - Orders not counted

### ISSUE THREAD

**Issue by Nesta78** [PrestaShop/PrestaShop#19930]
Hi,

In stats pages in back-office, some of my orders are not counted.
I don't use Invoices, so I just modified the Adminstatscontroller.php by replacing "invoice_date" by "date_add".
But with no luck ... any idea ?

It's ok on main dashboard of the back-office, but not in stats tabs
<img width="1475" alt="Capture d’écran 2020-06-25 à 10 19 20" src="https://user-images.githubusercontent.com/64215260/85683622-b043b680-b6cd-11ea-8c12-0eb136dae2a0.png">
<img width="1475" alt="Capture d’écran 2020-06-25 à 10 20 01" src="https://user-images.githubusercontent.com/64215260/85683633-b33ea700-b6cd-11ea-8075-997f750186cc.png">

Thank you guys !
* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Nesta78 ,
In my test shop I have no issues with statistics and dashboard.
Please see the screenshots below :
![Capture d’écran 2020-06-25 à 10 40 47](https://user-images.githubusercontent.com/16019289/85686606-65776e00-b6d0-11ea-9d32-7583165fc85f.png)
![Capture d’écran 2020-06-25 à 10 40 41](https://user-images.githubusercontent.com/16019289/85686619-68725e80-b6d0-11ea-8b5c-7546825ae60c.png)

If you don't use invoices, it is better to change this option to NO :
![Capture d’écran 2020-06-25 à 10 40 53](https://user-images.githubusercontent.com/16019289/85686631-6c05e580-b6d0-11ea-90ff-094a811f5c66.png)
Thanks!

**Comment by Nesta78** [comment]
Hi and thank you for your answer :)
My invoice option is already turned to OFF.
I read on prestashop forums that is it a known bug of Prestashop : orders are counted in stats only when an invoice is generated. But when you don't use Invoices, it's a problem ... :(

**Comment by florine2623** [comment]
I've just tested and there's no bug.

I have made an order, status of order Shipped, so it is considered as accepted.
The Dashboard and Statistics did update :
![Capture d’écran 2020-06-25 à 11 54 42](https://user-images.githubusercontent.com/16019289/85698251-c9069900-b6da-11ea-8d9f-3619e289a677.png)
![Capture d’écran 2020-06-25 à 11 54 56](https://user-images.githubusercontent.com/16019289/85698265-cc018980-b6da-11ea-913d-bc9830738966.png)
![Capture d’écran 2020-06-25 à 11 55 23](https://user-images.githubusercontent.com/16019289/85698278-ce63e380-b6da-11ea-9fce-9cb1bad6d6c4.png)

**Comment by Nesta78** [comment]
That's strange ...
As you can see, i just had 2 new orders. But it not displayed in stats ...

![Capture d’écran 2020-06-25 à 15 04 17](https://user-images.githubusercontent.com/64215260/85725730-afbf1600-b6f5-11ea-85fb-02c229430776.png)

![Capture d’écran 2020-06-25 à 15 05 05](https://user-images.githubusercontent.com/64215260/85725752-b483ca00-b6f5-11ea-89c2-764eeb24cf5c.png)

<img width="1966" alt="Capture d’écran 2020-06-25 à 15 04 40" src="https://user-images.githubusercontent.com/64215260/85725778-bbaad800-b6f5-11ea-9768-9f5a162ca97c.png">

<img width="1744" alt="Capture d’écran 2020-06-25 à 15 09 35" src="https://user-images.githubusercontent.com/64215260/85725962-ebf27680-b6f5-11ea-8af3-9bb7ec19b166.png">

**Comment by florine2623** [comment]
Weird behavior indeed.
What version of module Sales and orders are you using ? Upgrade it if needed.
![Capture d’écran 2020-06-25 à 15 14 17](https://user-images.githubusercontent.com/16019289/85726625-9074b880-b6f6-11ea-9e4c-7332d6ffea54.png)

**Comment by Nesta78** [comment]
I use v2.0.0.
Just tried to clean restore it ... but no changes ...

<img width="1950" alt="Capture d’écran 2020-06-25 à 15 16 09" src="https://user-images.githubusercontent.com/64215260/85726980-ecd7d800-b6f6-11ea-962e-973b9686bb3d.png">

**Comment by florine2623** [comment]
> I don't use Invoices, so I just modified the Adminstatscontroller.php by replacing "invoice_date" by "date_add".

Could you disable this override and test again please ?

**Comment by Nesta78** [comment]
Just tried (and cleared cache) but no changes ... :(

**Comment by Nesta78** [comment]
The weird thing is that it's working on prestashop dashboard, but not in stats details ...

<img width="2560" alt="Capture d’écran 2020-06-25 à 16 10 07" src="https://user-images.githubusercontent.com/64215260/85736094-7a6af600-b6fe-11ea-8c42-d920ecba211e.png">

<img width="2560" alt="Capture d’écran 2020-06-25 à 16 10 31" src="https://user-images.githubusercontent.com/64215260/85736116-7fc84080-b6fe-11ea-9a82-58a8efa98657.png">

**Comment by florine2623** [comment]
Can you unable all overrides, clear cache and refresh page ?
When you click on export CSV, what is the result ?

**Comment by prestascott** [comment]
Hello @Nesta78,

Since we had no news from you for more than 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!
