### ISSUE TITLE
Order object is empty in payment module

### ISSUE THREAD

**Issue by harpreet43** [PrestaShop/PrestaShop#19945]
While following the payment module documentation , i found that $params['order'] object is empty and it doesn't return $total_to_pay amount. Please resolve this bug.

$total_to_pay = $params['order']->getOrdersTotalPaid();

**Comment by florine2623** [comment]
Hi @harpreet43 ,
Could you follow the bug template please and explain how to reproduce the issue ?
Thanks

**Comment by harpreet43** [comment]
Yaah! I hv followed prestashop documentation https://devdocs.prestashop.com/1.7/modules/payment/ for payment module and downloaded the sample payment module from https://github.com/PrestaShop/paymentexample.

but in paymentexample.php:-

-----
public function hookPaymentOptions($params)
    {
        if (!$this->active) {
            return;
        }

        if (!$this->checkCurrency($params['cart'])) {
            return;
        }

       **$total_to_pay` = $params['order']->getOrdersTotalPaid();  // But this block of code is not working as the $param['order'] is empty**


        $payment_options = [
            $this->getOfflinePaymentOption(),
            $this->getExternalPaymentOption(),
            $this->getEmbeddedPaymentOption(),
            $this->getIframePaymentOption(),
        ];

        return $payment_options;
    }

**Comment by Matt75** [comment]
This one is more up-to-date https://github.com/PrestaShop/paymentexample/pull/14

In hook `PaymentOptions`, `Order` is not created yet, you can only rely on `Cart` object.
`Order` object is created by `PaymentModule::validateOrder()`

You can use
`$params['cart']->getOrderTotal()`

**Comment by harpreet43** [comment]
Thanks
