### ISSUE TITLE
BO - order detail / Discount is deleted when deleting another discount

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19949]
#### Describe the bug

In an order we have a product with discount of 50% on the total of the order cumulated with another discount . If we delete the product the 2 discount are deleted

#### Expected behavior

The discount not related to the deleted product should not be deleted

#### Steps to Reproduce

1. Create a cart rule with 50% reduction on the total of the order with no code specifically and applied to a product
2. In FO create an order with any product and checkout
3. In Bo go to the previously created order and add the product with the rule => the 50 % discount is applied 
4. Add another discount ( for exemple 5% ) => the 5 % discount is applied
5. Delete the product related to the 50% discount
6. See error => the 2 discount are deleted

**Screenshots**

https://drive.google.com/file/d/1rVEr6K9cAJqfv2K-kSTsK5Jjkhd3eppW/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20083
