### ISSUE TITLE
Add the Platin (XPT) currency

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/PrestaShop#19941]
#### Missing Currency iso_code

We would like to add in Prestashop currency panel XPT (Platin).

#### Expected behavior

We would like to add here XPT (Platin) https://api.prestashop.com/xml/currencies.xml
and also update currency price automaticly to other currency. Looks like USD EURO etc. This problem because of the currency is not exist here https://api.prestashop.com/xml/currencies.xml

**Screenshots**

![XPT](https://user-images.githubusercontent.com/50143631/85733287-be60f980-b704-11ea-838f-a648663919e5.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @aytekinazmi12 ,
First please downgrade your PHP version to 7.2.
You can check this doc to have a full view of PS requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I will ping our product team to let them know about your improvement request. Please stay tuned.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@aytekinazmi12 would like to see a new currency added to PrestaShop : Platin XPT.
Is this possible ?

Thanks!

**Comment by aytekinazmi12** [comment]
can you help me?

**Comment by LouiseBonnard** [comment]
Hi @aytekinazmi12, thanks for your issue! Why would you like to have this currency natively instead of adding it manually in the back office? @MatShir, could it be handled by the CLDR? Its ISO 4217 code is `XPT`.

**Comment by aytekinazmi12** [comment]
> 
> 
> Hi @aytekinazmi12, thanks for your issue! Why would you like to have this currency natively instead of adding it manually in the back office? @MatShir, could it be handled by the CLDR? Its ISO 4217 code is `XPT`.

Hi I added it on the back office already but it is not updating. please see the screenshot.

**Comment by aytekinazmi12** [comment]
Hello,

can you help me?

**Comment by matks** [comment]
@LouiseBonnard @aytekinazmi12 Hi, I'm sorry but ... what is Platin XPT used for ?

The goal to add new currencies is to enable customers to pay with this currency.
From https://en.wikipedia.org/wiki/Platinum_coin I dont see any country using XPT as official currency. So ... why adding it ?

**Comment by aytekinazmi12** [comment]
My client wants to sell on the site, therefore I need it.

**Comment by matks** [comment]
> My client wants to sell on the site, therefore I need it.

Yes I understand that 😄 but https://api.prestashop.com/xml/currencies.xml is a file used by every PrestaShop websites in the world (and we estimate there are 300,000 shops in the world).

So if _a big part of these 300,000 shops_ might need Platin XPT we could consider integrating Platin XPT into it.

But if it's just you, we are not going to modify this file 😄 we cannot modify a system used by 300,000 people just to fit the needs of a single user. I think you understand that.

Consequently you need to find another way to automatically update the rates 😉 .

It is a simple rate, stored in database. A basic php script should to the job. You need to find a reliable source for this rate, then have some regular update of it (like a cronjob) check the latest rate value and update the value you use in the store.

If you cannot develop it yourself you can look for a PrestaShop agency/expert on https://www.prestashop.com/en/partners

If, however, we find that a huge number of merchants could benefit of the adding of Platin XPT into the currencies being monitored by PrestaShop, then we might integrate it 😉

**Comment by colinegin** [comment]
Hi !

The great news is that you will soon be able to create any type of currency, both official and unofficial, thanks to the new currency customization we have developed in 1.7.7. You can find more information here : https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/.

We expect to release the stable 1.7.7.0 version in a few weeks, stay tuned ! :)

**Comment by aytekinazmi12** [comment]
> 
> 
> Hi !
> 
> The great news is that you will soon be able to create any type of currency, both official and unofficial, thanks to the new currency customization we have developed in 1.7.7. You can find more information here : https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/.
> 
> We expect to release the stable 1.7.7.0 version in a few weeks, stay tuned ! :)

Hello @colinegin,

that's good news!
Thank you! I am waiting :)
