### ISSUE TITLE
[1.7.7] $cart->getProductsWithSeparatedGifts() does not contain required information

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19956]
**Steps to Reproduce**

1. Create a cart rule that gives free gift to order.
2. Go to FO and recreate this situation.
3. Call **$this->context->cart->getProductsWithSeparatedGifts()** somewhere in the code or from your module and print it.
4. **is_gift** value in the gifted product should be **1**, it's **empty**.

**Cause**
$refresh = true in getProductsWithSeparatedGifts()

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
🆙

**Comment by matthieu-rolland** [comment]
Hello @Hlavtox, thank you for the issue, I just tried to reproduce it, but I didn't manage, here's what I did:

1/ In BO, I created a cart rule with a free gift
2/ In FO, I added one product in my cart, meeting the conditions for the free gift
3/ In FO, cart page, I see that the free gift is correctly added, and when I call `$this->context->cart->getProductsWithSeparatedGifts()`, I see that the product I added to the cart has **is_gift** set to false, and the product added as a free gift has **is_gift** set to true, which is the normal behavior.

Maybe this bug manifests itself in more specific conditions?

**Comment by matthieu-rolland** [comment]
I close this issue until a clearly reproducible scenario is defined.

**Comment by Hlavtox** [comment]
@matthieu-rolland @matks @Progi1984 @jf-viguier 

1. Add this to cart.
2. Refresh page and see the output. No is_gift=true anywhere.
http://test.trendo.cz/art/5-today-is-a-good-day-framed-poster.html

BTW @matthieu-rolland, how it can work for you when the logic that sets this flag is disabled by a condition that is not met?
![1](https://user-images.githubusercontent.com/6097524/90036403-502bc280-dcc3-11ea-9bf2-43a7a899753c.JPG)

**Comment by matthieu-rolland** [comment]
@Hlavtox I'm not familiar with this feature, but it just does work when I debug in the backend, whether it is in the cart, or on the product page, without doing anything special. Am I missing something obvious? I'm reopening the issue, I'll take the time to debug this.

Meanwhile, could you tell me where exactly do you call `$this->context->cart->getProductsWithSeparatedGifts()` from ? 

<img width="465" alt="Capture d’écran 2020-08-12 à 17 52 58" src="https://user-images.githubusercontent.com/1784781/90037668-c3820400-dcc4-11ea-99af-353340b8becb.png">

**Comment by matthieu-rolland** [comment]
@hlavtox, about your second capture, where does it come from ? 

I don't have this in my codebase, on 1.7.7:

<img width="798" alt="Capture d’écran 2020-08-12 à 18 10 37" src="https://user-images.githubusercontent.com/1784781/90039615-2d031200-dcc7-11ea-8e5a-44cfe5b6eb88.png">

(`classes/Cart.php:767`)

**Comment by matthieu-rolland** [comment]
@Hlavtox see this commit:

https://github.com/PrestaShop/PrestaShop/commit/9d5c1e04bdcba22b84671e3c167bbe86f4401d51

Your 1.7.7 might not be up to date.

**Comment by matthieu-rolland** [comment]
@Hlavtox it seems like your 1.7.7 is not up to date, your second capture does not match the code of this method on 1.7.7:

https://github.com/PrestaShop/PrestaShop/blob/4ad2a245ad117db10eeec696537b6808d5666a03/classes/Cart.php#L767

**Comment by Hlavtox** [comment]
@matthieu-rolland I will confirm with the latest code and let you know. But if its fixed - good!

**Comment by matthieu-rolland** [comment]
yeah, right

**Comment by Hlavtox** [comment]
@matthieu-rolland @matks Fixed in current 1.7.7 code! You were right. 🚀
