### ISSUE TITLE
[1.7.7] hookdisplayAdminOrder is not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19958]
#### Describe the bug

This hook is not working. It outputs nothing to order admin screen.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by Matt75** [comment]
@Hlavtox see https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/#order-view-page-layout-modifications

**Comment by Hlavtox** [comment]
@Matt75 see https://devdocs.prestashop.com/1.7/modules/core-updates/img/order-view-page-hooks.jpg

No word about hookdisplayAdminOrder removed....

**Comment by Matt75** [comment]
@Hlavtox Yes it was missing inside https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/#modified-hooks

**Comment by Hlavtox** [comment]
@Matt75 Sorry, but I am either blind or stupid. 😄 

- No word about this hook being renamed
- No word about this hook being removed
- The hook is on the layout image displayed in the same position as in 1.7.6
- Hook still present in twig template _{{ renderhook('displayAdminOrder', {'id_order': orderForViewing.id}) }}_

So, the hook is removed or not?

**Comment by Matt75** [comment]
`hookdisplayAdminOrder` => `hookDisplayAdminOrder` ?


![displayAdminOrder](https://user-images.githubusercontent.com/5262628/85863695-d055a180-b7c3-11ea-993b-3657be76a9a5.png)

**Comment by Hlavtox** [comment]
@Matt75 Can you tell me why this is not working? It's a piece of code from official GA module. I changed Display to capital letter, but still the same.

  ```
  /**
     * Hook admin order to send transactions and refunds details
     */
    public function hookDisplayAdminOrder()
    {
        echo "TEST";
        echo $this->_runJs($this->context->cookie->ga_admin_refund, 1);
        unset($this->context->cookie->ga_admin_refund);
    }
```

**Comment by Matt75** [comment]
Don't use `echo`, you must return a `string` like template rendering or just `return '<p>TEST</p>';`

**Comment by Hlavtox** [comment]
@Matt75 Ahaaaaaaaaa!!! It's working now.

Now, I am adding some refund functionality to google analytics module. https://github.com/PrestaShop/ps_googleanalytics/pull/43

It relies on outputting some data, which was already present. 
```
    public function hookdisplayAdminOrder()
    {
        echo $this->_runJs($this->context->cookie->ga_admin_refund, 1);
        unset($this->context->cookie->ga_admin_refund);
    }
```

How should I approach it, when the module needs a tweak to be compatible with 1.7.7? I suppose it's not good to mix more things into single PR.

Ping @PierreRambaud and @SimonGrn

**Comment by Hlavtox** [comment]
I also think that getting information over $this->context->cookie->ga_admin_refund is not working.

**Comment by PierreRambaud** [comment]
@Hlavtox I recommend you to don't mix things in a single PR and create a new one if you think it's relevant ;)

**Comment by Progi1984** [comment]
@Hlavtox Your problem is solved ?

**Comment by Hlavtox** [comment]
@Progi1984 Yes, I will maybe open a new one to make things more clear. Thanks!
