### ISSUE TITLE
Wrong language code for French Canada in Prestashop 1.7.6.5

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#19966]
I install a new version for testing if you resolved the issue of wrong locales for French (Canada) and still have wrong language iso code.

To reproduce:
1. Install a Fresh Prestashop 1.7.6.5;
2. Select French (Canada) has default language;
3. After installation, Internalisation > Localisation;
4. Scroll down to Advanced;

See: 
![Wrong language iso code](https://user-images.githubusercontent.com/16780421/85879009-9e364680-b7a7-11ea-9061-0d0336a71fdd.png)

It's supposed to be "fr" has language identification, not qc.

I reported since version 1.7.5.1 version and will cause problems with Google, Search engines bots, modules translations, products translations. 

Also, in Language ISO code, reported in [issue #16004](https://github.com/PrestaShop/PrestaShop/issues/16004), it will not worked well.

Does by changing manually the iso code and country code will worked with locales in this version now? Because when i change it, it's not getting the error i get with previous build.

I change languages codes and Prestashop seems to accept the changes (compared to version 1.7.5.1, it's wasn't working). Did all locales errors is okay on this version?

![New language modified](https://user-images.githubusercontent.com/16780421/85879475-6f6ca000-b7a8-11ea-8d47-6dafed620114.png)

Thanks.

**Comment by 8ternity** [comment]
Other related issue: After changing to proper locales (fr) and (ca), i can't translate default theme translations, also can't translate default e-mail subject or email heading. It's totally broken again the translation module. It's more 9 months without any fix for this when i started reported the issue in October 2019.

**Comment by Progi1984** [comment]
We are aware of this issue, it is already in our debug backlog.This issue is a duplicate of #16004.To be informed when it's fixed, please subscribe to the issue mentioned above.Thank you!

**Comment by Progi1984** [comment]
Duplicate of #16004
