### ISSUE TITLE
Do not display any shipping method in the summary when ordering virtual products only

### ISSUE THREAD

**Issue by Nakira** [PrestaShop/PrestaShop#19963]
#### Describe the bug

The first (in terms or order) shipping method is chosen for an order with one virtual product and shown in the order summary.

#### Expected behavior

Not showing the shipping method in order summary when only virtual products in order

#### Steps to Reproduce

1. Go to BO > Shop Preferences > Order Preference 
2. Activate order summary
3. Save
4. In BO :  Create a virtual product
5. As a customer  add the virtual product to your cart
6. Checkout , create account, put address and view product summary

![image (10)](https://user-images.githubusercontent.com/3797348/85873577-9db2a580-b7d1-11ea-9cb5-7392017f6892.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: the one used in https://demo.prestashop.com/

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-product-team I ping you because it's a small improvement which can be easily implemented ;)

**Comment by NeOMakinG** [comment]
Partially front-end one, a backend dev should create the logic of "Order only containing virtual product" and adding a condition to `themes/classic/templates/checkout/_partials/order-final-summary.tpl`
