### ISSUE TITLE
Cant deleted category ver 1.7.6.5

### ISSUE THREAD

**Issue by bbaoden** [PrestaShop/PrestaShop#19975]
Hello, 
I cant deleted categories

**Comment by bbaoden** [comment]
![bug 1](https://user-images.githubusercontent.com/34534006/85956965-7c111400-b9b3-11ea-9d01-ce75d1ee7855.png)
![bug 2](https://user-images.githubusercontent.com/34534006/85956967-7ddad780-b9b3-11ea-92ab-fb1aea605850.png)
-the selection box has a bug
-product page too
-cant enable debug mode

**Comment by bbaoden** [comment]
I'm using php 7.4 version

**Comment by Progi1984** [comment]
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).Thank you!

**Comment by bbaoden** [comment]
https://truemapal.com/admin123
user:cs@truemapal.com
pwd:Quangle123
can you cehck it buy yourself,
i have try to reinstall for new domain but it same error
i'm using a2hosting, 
prestashop version 1.7.6.5

**Comment by bbaoden** [comment]
if you need fpt please email me at bbaodenx3@gmail.com

**Comment by Progi1984** [comment]
@bbaoden I removed one of your comment, because it contains login & password 

We need a scenario which permits to  core developers to fix the problem. Could you explain the process for having your problem ?

**Comment by bbaoden** [comment]
When i enable debug mode 
![bug3](https://user-images.githubusercontent.com/34534006/86000327-a0163900-ba37-11ea-805f-18b01c8703c1.PNG)

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /home/ebajessh/public_html/sales/src/Adapter/EntityMapper.php on line 99

**Comment by bbaoden** [comment]
I send a test shop dont worries about the password
some option form is faild show
![bug 1](https://user-images.githubusercontent.com/34534006/86000406-b623f980-ba37-11ea-967c-7f1466a3a759.png)
![bug 2](https://user-images.githubusercontent.com/34534006/86000417-b7552680-ba37-11ea-9fda-7ec15e7e0f08.png)

**Comment by Progi1984** [comment]
@bbaoden Which version of PHP do you use ?

**Comment by bbaoden** [comment]
lasted version 7.4

**Comment by bbaoden** [comment]
my shop is new set up,
if you need fpt and user for check it, i can send by e-mail to you

**Comment by Progi1984** [comment]
@bbaoden Actually, PrestaShop don't support PHP 7.4. It will be supported in 1.7.8 (#16477).

Please use a lower version (PHP 7.2 in 1.7.6.5).

The PHP compatibility chart is available here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by bbaoden** [comment]
thank you

**Comment by Progi1984** [comment]
@bbaoden You're welcome. I close your ticket but if you have any problem, please reopen it.
