### ISSUE TITLE
[1.7.7] Image customization cannot be zoomed or viewed from order admin

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19974]
#### Steps to Reproduce

1. Add a customization field to product, file type, optional.
2. Go to FO, customize the product by uploading an image. Add it to cart. Order it.
3. Go to BO > Orders > Your order
4. Attached image to product cannot be zoomed, does not link anywhere. 

#### How we can solve this
1. Add `private $link;` and `$this->link= _THEME_PROD_PIC_DIR_ . $this->value;`
to `/src/Core/Domain/Order/QueryResult/OrderProductCustomizationForViewing.php`

2. Change `<img src="{{ customization.image }}" alt="{{ customization.name }}">` to `<a href="{{ customization.link }}" target="_blank"><img src="{{ customization.image }}" alt="{{ customization.name }}"></a>` in `/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig` or open it in a modal.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by Progi1984** [comment]
In 1.7.6.x, the image was downloadable with a click on the image :

![image](https://user-images.githubusercontent.com/1533248/85990566-843c7400-b9f2-11ea-9f21-e08aac7c4599.png)

In 1.7.7.x, the image is not zoomable or downloadable : 

![image](https://user-images.githubusercontent.com/1533248/85991350-9a96ff80-b9f3-11ea-9ef8-071adc4716ba.png)
