### ISSUE TITLE
Small fuzzy search issue

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19973]
Hi! I have been testing fuzzy search. It works amazing and always finds what I want (thanks @Lathanao), except one situation.

I have approximately 300 products with name like **Kuchyňský dřez XXXXXXXXXXX** (Kitchen sink)
These products have a feature specifying color, that has a value of **Odstíny bílé** (Shades of white)

If I search **dřez bílé** = **800 products**.
If I search **dřes bílé** = **800 products**.
But if I search **dřez bílý** = **only 7 non related products**.

I can't understand why is it like that. I would not matter, but Czech language has several "endings" for adjectives, depending of the word they are connected to. **bílý** is the correct spelling for **dřez**.

Can you check it out @Lathanao? Thanks!

**My search settings:**
Search inside word: YES
Search for exact ending: NO
Fuzzy search: YES
Maximum approximate words allowed by fuzzy search: 4 (Default)
Maximum word length: 15 (Default)
Minimal word length: 4 (Default)

Prestashop 1.7.7
PHP 7.2

**Comment by Tanguy-SALMON** [comment]
Hey,
If you can send me your DB, I will take a look.

**Comment by Hlavtox** [comment]
@Lathanao Sent you an email. Thanks! 🚀

**Comment by Tanguy-SALMON** [comment]
You have very few result with "bílý" because this word exist in your DB and has very few related products.
You were waiting for the utilisation of the 'fuzzy search' functionality, but in this case, it's not used.
So, Search class just return products related to "bílý". 

You can try:
SELECT id_product FROM `ps_search_word` psw
INNER JOIN `ps_search_index` psi ON (psw.id_word = psi.id_word)
WHERE `word` LIKE '%bile%'

Related products (all products whatever the stock, status, etc..):
- bile: 1,724
- bily: 23

When Search class create the result for FO, some product are removed because stock, status, etc... and the result is what you described, 800 vs 7.

**Comment by Hlavtox** [comment]
@Lathanao Hmmmmm. Can we somehow use fuzzy search even if a the same word was found? I think it would not be so huge performance drawback, what do you think?

**Comment by Tanguy-SALMON** [comment]
We weren't looking to make working the Fuzzy Search in case some words are found.
Not sure 100%, but in your case, the problem you have is about some synonymes.

So, to solve this problem, you have just to set some synonymes here:
![image](https://user-images.githubusercontent.com/6756795/85944301-ec8e4580-b95f-11ea-8f9e-a1ad786a4e6c.png)

**Comment by Tanguy-SALMON** [comment]
Just to confirm, with a synonyme setup, it's well working:

![image](https://user-images.githubusercontent.com/6756795/85944639-a1296680-b962-11ea-82b2-f476954d5f6a.png)

**Comment by Progi1984** [comment]
@Hlavtox Have you seen the answer from @Lathanao ?

@Lathanao Thank you for your help :heart_eyes_cat:

**Comment by Hlavtox** [comment]
@Progi1984 @Lathanao Hi guys, thank you for your time in the first place.

I have been testing Lathanao's proposed solution and it works good! I have been worried, if I set an alias **černý->černé**, if it actually still finds stuff, that is originally indexed as **černý**, if you know what I mean. But it works as intended, great!!!

The “fuzzy even if found” idea is nonsense, it would find hundreds of nonsense products.

I suggest we can close this then! 🚀

**Comment by Progi1984** [comment]
Thanks @Hlavtox & Thanks @Lathanao :heart_eyes_cat:
