### ISSUE TITLE
Prestashop issue

### ISSUE THREAD

**Issue by borisep** [PrestaShop/PrestaShop#19977]
#### Describe the bug
I cant enter to my back office of my Prestashop online shop

A clear and concise description of what went wrong.
I am trying to enter to back office and after entering my password it is show me:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
#### Expected behavior

Explain what you expected to happen instead.
I am expecting to enter to my back office 
#### Steps to Reproduce

1. Go to '...https://beerabar.lv/ugq8swzi5gyxa5cf/index.php?controller=AdminLogin&token=6c6b5e3ed63994519680353d8430b74f&redirect=AdminDashboard'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by Progi1984** [comment]
Hello,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support
Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

**Comment by borisep** [comment]
I don’t have questions
I want someone to solve technical problem.
I can’t find any contact from Prestashop
What can i do?

**Comment by Progi1984** [comment]
@borisep If you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support
Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/
