### ISSUE TITLE
Add id_order variable in PaymentModule

### ISSUE THREAD

**Issue by luciobenini** [PrestaShop/PrestaShop#19987]
#### Is your feature request related to a problem?

**id_order** variable is missing in **order_conf** template.

https://github.com/PrestaShop/PrestaShop/blob/a588597e720b051e92e0b20580c9102e29f5437e/classes/PaymentModule.php#L590-L644

#### Describe the solution you'd like

I would need to add the **id_order** variable to email **order_conf** template. Is it possibile?

**Comment by matks** [comment]
@luciobenini Hi, I can see the variable `id_order` at line 628. Are you sure this is not already fixed ?

**Comment by luciobenini** [comment]
Sorry, my fault. I have an older version.

**Comment by matks** [comment]
> Sorry, my fault. I have an older version.

Time to upgrade then 😄 

Thanks for the feedback anyway, have a nice day ! ✋
