### ISSUE TITLE
Mollie 500 error

### ISSUE THREAD

**Issue by GitHarm** [PrestaShop/PrestaShop#19985]
Hello,

I have a Mollie problem. I finally managed to solve the problem I couldn't add payment methods. So that's done, but now when I click "order with obligation to pay" it leads me to a 500 error page. When debugging I see the what I added in the attachment.

Does someone know what to do?
![Schermafbeelding 2020-06-29 om 11 35 03](https://user-images.githubusercontent.com/12151052/86012873-ca0f3180-ba1e-11ea-9f04-615369f70f6b.png)

**Comment by Progi1984** [comment]
@GitHarm It seems link to `MolliePayment` module. Have you tried to contact them on Addons Marketplace ?

**Comment by GitHarm** [comment]
@Progi1984 Yes you are right. It's fixed already. It was a stock problem...
When the customer wanted to pay, Mollie edited the stock, and that gave a problem which lead to the 500 error.

**Comment by Progi1984** [comment]
Perfect. Thanks ;)
