### ISSUE TITLE
cart rule error with "Send a free gift" option enabled

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#19993]
Hi
I found a new bug about cart rule
it happens when it is enabled the "Send a free gift" option. (look at the image to replicate the issue)

1) create a cart rule following the attached images
2) go in the front-office to add a product to the cart
3) now the gift will appear in the cart with a quantity of 1
4) go to the cart summary
5) remove the product previously added in the cart
6) now you can see that the gift item will have a quantity of 2
7) try to remove it from the cart (it will not possible)

the product if removed should remove the gift item if it is present only itself

I've created a video to see this bug
https://drive.google.com/file/d/1pJoWjDmygGHOSXsyHmFFRR7DT_X_KwPc/view

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/86057377-5f321a80-ba5f-11ea-87cb-cb275fc44a90.png)
![2](https://user-images.githubusercontent.com/653230/86057378-60634780-ba5f-11ea-9f57-e7d6fce94aac.png)
![3](https://user-images.githubusercontent.com/653230/86057380-60fbde00-ba5f-11ea-9fc0-158460ca127e.png)
![4](https://user-images.githubusercontent.com/653230/86057383-61947480-ba5f-11ea-83c9-78eda8ddfd0b.png)
![5](https://user-images.githubusercontent.com/653230/86057386-62c5a180-ba5f-11ea-989b-25b2a5090188.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

bye

**Comment by Progi1984** [comment]
I check on 1.7.7.x. I didn't reproduce the bug.

I check on 1.7.6.x. I reproduce the bug.

**Comment by Progi1984** [comment]
@maofree Thank you for your contribution. This has been fixed on the 1.7.7.x branch.

**Comment by Maofree** [comment]
thanks
