### ISSUE TITLE
seeker problom.

### ISSUE THREAD

**Issue by drmsjee9** [PrestaShop/PrestaShop#19994]
Desktop/seeker-master/seeker# ./seeker.py 
[+] Checking Dependencies...
Traceback (most recent call last):
  File "./seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@shah:/home/musharaf/Desktop/seeker-master/seeker# seeker
bash: seeker: command not found

**Comment by matks** [comment]
I think this is not the right place 😅 PrestaShop is php only, not python.

You probably are looking for one of them: https://github.com/search?q=python+seeker&ref=opensearch

**Comment by fahdbadan** [comment]
[+] checking dependencies... traceback (most recent call last): file "./seeker.py" line 32 in import requests modulenotfounderror: no module named 'requests'🥴🥴🙄

**Comment by Swethan73** [comment]
[+] checking dependencies... traceback (most recent call last): file "./seeker.py" line 32 in import requests modulenotfounderror: no module named 'requests

**Comment by Swethan73** [comment]
[+] checking dependencies... traceback (most recent call last): file "./seeker.py" line 32 in import requests modulenotfounderror: no module named 'requests
