### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by cgermanb** [PrestaShop/PrestaShop#20004]
Hi, I try to upgrade gsitemap in prestashop and after i get this error, and now i cant access to prestashop, can you help me please?

Fatal error: Uncaught Error: Class 'ComposerAutoloaderInit53666501d6988215ffba5a499c528e38' not found in /opt/bitnami/apps/prestashop/htdocs/modules/gsitemap/vendor/autoload.php:7 Stack trace: #0 /opt/bitnami/apps/prestashop/htdocs/src/Adapter/ContainerBuilder.php(236): include_once() #1 /opt/bitnami/apps/prestashop/htdocs/src/Adapter/ContainerBuilder.php(129): PrestaShop\PrestaShop\Adapter\ContainerBuilder->loadModulesAutoloader(Object(FrontContainer)) #2 /opt/bitnami/apps/prestashop/htdocs/src/Adapter/ContainerBuilder.php(93): PrestaShop\PrestaShop\Adapter\ContainerBuilder->buildContainer('front') #3 /opt/bitnami/apps/prestashop/htdocs/classes/controller/FrontController.php(1968): PrestaShop\PrestaShop\Adapter\ContainerBuilder::getContainer('front', true) #4 /opt/bitnami/apps/prestashop/htdocs/classes/controller/Controller.php(184): FrontControllerCore->buildContainer() #5 /opt/bitnami/apps/prestashop/htdocs/classes/controller/FrontController.php(271): ControllerCore->init() #6 /opt/bitnami/apps/prestashop/htdocs/classe in /opt/bitnami/apps/prestashop/htdocs/modules/gsitemap/vendor/autoload.php on line 7

**Comment by LouiseBonnard** [comment]
Hello @cgermanb, thanks for your issue! We need further information to understand how to reproduce your issue, could you please provide us with more details?

- full description
- host
- server setup and configuration
- PrestaShop version
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- etc.

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/), thanks!

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
