### ISSUE TITLE
Unicode 6 + prestashop 1.7.6.1

### ISSUE THREAD

**Issue by tutijaja** [PrestaShop/PrestaShop#20003]
Hello,

I can’t seem to find out if Unicode 6 is supported by prestashop version 1.7.6.1

Could someone please confirm it if that is the case?

Best regards,

**Comment by LouiseBonnard** [comment]
Hi @tutijaja, I'm glad to let you know it will be supported in the next minor version! You can find the related issue [there](https://github.com/PrestaShop/PrestaShop/issues/11083) and more information about PrestaShop 1.7.7 here: https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release - stable version should be released in a few weeks. :-)

**Comment by LouiseBonnard** [comment]
I close this issue since it looks already fixed, thanks!
