### ISSUE TITLE
adding cart rule causes FO 500 Error - PS 1.7.6.5

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#20019]
Hi, 

if I add a cart rule the FO gets 500 Error and BO orders detail page get 500 Error too. After a few time acitvate and deactivate the cart rule NO item can be added to the cart. It is a very strange behavior. After deleting PS cache and browser cache I have 500 Error in FO too! 

Here is my cart rule:

![image](https://user-images.githubusercontent.com/44971218/86258650-56eef200-bbbb-11ea-911d-799a2709e9df.png)

![image](https://user-images.githubusercontent.com/44971218/86258720-6c641c00-bbbb-11ea-89da-2a1995cfc80a.png)

![image](https://user-images.githubusercontent.com/44971218/86258800-83a30980-bbbb-11ea-830e-cdc3130d8d11.png)

Do I something wrong? I dont think so. I like to have a cart rule of 3% without any purchase amount, from now until 31.12.20 .

PS 1.7.6.5
PHP 7.2.24

**Comment by didi-2018** [comment]
it seems to be a problem with ps_legalcompliance

![image](https://user-images.githubusercontent.com/44971218/86261909-79830a00-bbbf-11ea-827f-66f0367a3496.png)
![image](https://user-images.githubusercontent.com/44971218/86262016-9f101380-bbbf-11ea-9ce1-f6c81b2d4fed.png)

**Comment by LouiseBonnard** [comment]
Hi @didi-2018, thanks for your report! A 500 error is usually related to the server... and here I cannot reproduce it. Did you try to refresh the page that provoke this error? Does it also happen when performing other actions in your back office?

**Comment by didi-2018** [comment]
@LouiseBonnard no it is only related to the cart rule. If that rule is deactivated everything is fine. I now added a discount code and everything works. But it should also work without a discount code. 

Could it be in relation that I change the german tax today from 19% to 16%? Maybe there is now a problem with the ps_legalcompliance?

**Comment by LouiseBonnard** [comment]
@didi-2018, thanks for your answer, I'm unfortunately still not able to reproduce it... @PrestaShop/prestashop-core-developers, any idea of where this issue might come from when reading the error screenshot?

**Comment by didi-2018** [comment]
@LouiseBonnard it must be a cache problem. After deleting a few times the PS cache I can open a product page in FO but putting an item into basket is not possible. 🤷‍♀️ Chrome DevTools show a 500 Error with the cart

**Comment by didi-2018** [comment]
@LouiseBonnard this is what I have in dev.log file: 

php.INFO: User Deprecated: AdminMarketing is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. {"exception":"[object] (ErrorException(code: 0): User Deprecated: AdminMarketing is a deprecated tab since version 1.7.0 and \"Default\" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. at /hp/cy/aa/cp/www/Presta_1763/classes/Tab.php:348)"} []

[2020-07-02 13:30:43] php.DEBUG: Warning: filemtime(): stat failed for /hp/cy/aa/cp/www/Presta_1763/admin34399run4/themes/default/css/theme.css {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/hp/cy/aa/cp/www/Presta_1763/classes/Media.php\",\"line\":269,\"trace\":[{\"file\":\"/hp/cy/aa/cp/www/Presta_1763/classes/Media.php\",\"line\":240,\"function\":\"getMediaPath\",\"class\":\"MediaCore\",\"type\":\"::\"}],\"count\":1})"} []

[2020-07-02 13:30:45] doctrine.DEBUG: SELECT name FROM i79e_module WHERE active = 1 [] []

**Comment by didi-2018** [comment]
I could find out what it causes! It is the Exit PopUp Module from Knowband I bought. I will contact the developer. Sorry for having stolen your time 🤦‍♀️. I will close this issue now.
