### ISSUE TITLE
Catalog Price Rule without condition group doesn't appear in the product editor

### ISSUE THREAD

**Issue by Rolige** [PrestaShop/PrestaShop#20021]
#### Describe the bug

When a Catalog Price Rule is created without condition group, this rule is not listed in the Price tab in the product editor.

#### Expected behavior

Display the Catalog Price Rule created.

#### Steps to Reproduce

1. Create a Catalog Price Rule without any condition group
2. Go to the product list and edit some product
3. The Catalog Price Rule created is not listed

**Screenshots**

https://streamable.com/jc22a9

#### Additional information

* PrestaShop version: 1.7.8 / 1.7.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Rolige ,
Thanks for your report !
I did manage to reproduce the issue in PS 1.7.7.0 and PS 1.7.6.5.
I will add this to our debug roadmap, please stay tuned.
