### ISSUE TITLE
Same name carriers don't show in Shipping > Preferences > Default carrier

### ISSUE THREAD

**Issue by Rolige** [PrestaShop/PrestaShop#20023]
#### Describe the bug

There are missing carriers in the list of "**Shipping > Preferences > Carrier options > Default carrier**", the problem occurs with carriers with the same name.

#### Expected behavior

Display the complete list of carriers availables.

#### Steps to Reproduce

1. Create more than one carrier with the same name
2. In the carrier selection in "**Shipping > Preferences > Carrier options > Default carrier**" will display only one

**Screenshots**

<img width="1469" alt="error-01" src="https://user-images.githubusercontent.com/2866694/85910363-97292b80-b7db-11ea-9561-c364c141525e.png"> 
<img width="1336" alt="error-02" src="https://user-images.githubusercontent.com/2866694/85910368-9d1f0c80-b7db-11ea-8ac2-069c516240d6.png">

#### Additional information

* PrestaShop version: Develop / 1.7.7.x
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Rolige ,
Thanks for the report.
I did manage to reproduce the issue on PS 1.7.7.0.
Thank you for the PR, I will add this tp the debug roadmap !
