### ISSUE TITLE
Updating order state throw webservice add a payment line

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#20025]
#### Describe the bug

Updating order state throw webservice add a new payment line.

#### Expected behavior

It's should add a new payment line because only order state change, it's a new order history only.

#### Steps to Reproduce

1. Create an order and add one payment line. Take care to not generate invoice.
2. Change order's state throw webservice (my php script is attached). This state must be able to generate invoice.
3. Check order payment (see screenshoot)

This bug only appear if invoice isn't generated AND if the new order state generates invoice.

**Screenshots**

![before](https://user-images.githubusercontent.com/6622400/86342981-a0414f00-bc58-11ea-9e84-8d7e12f4777d.png)
![after](https://user-images.githubusercontent.com/6622400/86342976-9fa8b880-bc58-11ea-984f-f98c26f89f51.png)

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: N/A

[add_order_state_ps15.zip](https://github.com/PrestaShop/PrestaShop/files/4863235/add_order_state_ps15.zip)

**Comment by florine2623** [comment]
Hi @Max84 ,
This page has totally been remodeled in PS 1.7.7.0, no fix will be done on PS 1.7.6 (apart from security bugs).
After following your steps, in PS 1.7.7.0, this is the result :
1. Created an order and add one payment line. No invoice generated
2. Change order's state that generates invoice : payment accepted
![Capture d’écran 2020-07-02 à 12 12 40](https://user-images.githubusercontent.com/16019289/86346529-59a22380-bc5d-11ea-8211-98c50d7aee6f.png)
3. Check order payment
![Capture d’écran 2020-07-02 à 12 10 55](https://user-images.githubusercontent.com/16019289/86346378-1ba4ff80-bc5d-11ea-9273-a6bd62fb34b8.png)

The payment has been updated in the payment block.

**Comment by BlackKerio** [comment]
@sarahdib @florine2623 I am surprised. The error needs to be corrected. does not apply to forms on this site. but  Updating order state throw **WEBSERVICE** .  thank you
