### ISSUE TITLE
In Multistore, product attributes aren't displayed when created for a specific shop

### ISSUE THREAD

**Issue by Rolige** [PrestaShop/PrestaShop#20022]
#### Describe the bug

In the product editor, within a multi-store with a shop context selected, it's not possible to use attributes that were created specifically for a specific store.

#### Expected behavior

Show the product attributes associated to the shop in context.

#### Steps to Reproduce

1. In a multi-store, create attributes and assign different shops for each one
2. try using them in the product editor

**Screenshots**

https://streamable.com/17qk9a

#### Additional information

* PrestaShop version: Develop / 1.7.7.x
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Rolige ,
Thanks for the report, I managed to reproduce the issue in multistore PS 1.7.7.0 and PS 1.7.6.5.
Thank you for your PR, I will add this to the debug roadmap !

**Comment by florine2623** [comment]
Hi @Rolige ,
Your issue seems to be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9686
If that's the case please let me know, I will close your issue, so you can follow the main one directly here : https://github.com/PrestaShop/PrestaShop/issues/9686
Thanks!

**Comment by marionf** [comment]
Duplicate of #9686
