### ISSUE TITLE
Custom feature value does not save in multilanguage shop

### ISSUE THREAD

**Issue by TVBZ** [PrestaShop/PrestaShop#20027]
#### Describe the bug

A product custom feature value is not saved in backoffice when there are multiple languages installed AND the default language is NOT english.

When only 1 language is installed (any language) and set as default, it works fine.
When multiple languages are installed and enabled, and English is set as default, it works fine.

#### Expected behavior

Custom feature value should be saved.

#### Steps to Reproduce

1. Install fresh PS 1.7.6.5 
2. Install and enable second language, and make it default language
3. Add a predefined feature
4. Now add a product using a predefined feature AND a custom feature
 
=> only the predefined feature is saved

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by NKoonen** [comment]
To make the bug even more complete. The employee should use the same language as the shop's default language, of it's not te same the user can't edit/create a custom feature.

**Comment by florine2623** [comment]
Hi @TVBZ ,
First you need to downgrade your PHP version. You can have a full overview of PrestaShop system requirement here :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Just a reminder that PS 1.7.7. will be out soon, no fix will be done on PS 1.7.6.5 (apart from security bugs).

I manage to reproduce your issue in PS 1.7.6.5 :
![Capture d’écran 2020-07-02 à 15 12 45](https://user-images.githubusercontent.com/16019289/86363167-c0800680-bc76-11ea-8065-5aa6d2fc855a.png)
![Capture d’écran 2020-07-02 à 15 12 50](https://user-images.githubusercontent.com/16019289/86363173-c2e26080-bc76-11ea-8256-fd79a87ab655.png)

And also in PS 1.7.7.0 :
![Capture d’écran 2020-07-02 à 15 18 54](https://user-images.githubusercontent.com/16019289/86363748-924ef680-bc77-11ea-8d30-d92fa9cff7ae.png)
![Capture d’écran 2020-07-02 à 15 18 49](https://user-images.githubusercontent.com/16019289/86363757-94b15080-bc77-11ea-8f47-6442a9aadd1b.png)

I will add the to our debug roadmap; please stay tuned !
Thanks!

**Comment by TVBZ** [comment]
Hi @florine2623. Thanks!

Just downgraded php to 7.2. Sadly the problem persists.

**Comment by kexuejia** [comment]
hi, my temporary solution is  in product class do change  the function :
```
public function addFeaturesCustomToDB($id_value, $lang, $cust)
   {

     if (trim($cust)=='') {

       $sql = 'SELECT f.`value`'
           .' FROM `'. _DB_PREFIX_.'feature_value_lang` f '
           .' WHERE f.id_feature_value = '.$id_value.' and id_lang<>'.$lang;
       $cust=  Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($sql);


     }

       $row = array('id_feature_value' => (int) $id_value, 'id_lang' => (int) $lang, 'value' => pSQL($cust));

       return Db::getInstance()->insert('feature_value_lang', $row);
   }
```

**Comment by khouloudbelguith** [comment]
Hi @TVBZ,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13751
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #13751

**Comment by omidamini** [comment]
here is my solution for this problem that works perfectly fine :) . 

class AdminProductsController extends AdminProductsControllerCore
{
    public function processFeatures($id_product = null)
    {
        if (!Feature::isFeatureActive()) {
            return;
        }

        $id_product = (int) $id_product ? $id_product : (int) Tools::getValue('id_product');

        if (Validate::isLoadedObject($product = new Product($id_product))) {
            // delete all objects
            $product->deleteFeatures();

            // add new objects
            $languages = Language::getLanguages(false);
            $form = Tools::getValue('form', false);
            if (false !== $form) {
                $features = isset($form['step1']['features']) ? $form['step1']['features'] : [];
                if (is_array($features)) {
                    foreach ($features as $feature) {
                        if (!empty($feature['value'])) {
                            $product->addFeaturesToDB($feature['feature'], $feature['value']);
                        } 
                        else
                        {
                            $defaultValue = isset($feature['custom_value'][array_key_first($feature['custom_value'])])?$feature['custom_value'][array_key_first($feature['custom_value'])]:'';
                            $idValue = $product->addFeaturesToDB($feature['feature'], 0, 1);
                            foreach ($languages as $language) {
                                $valueToAdd = (isset($feature['custom_value'][$language['id_lang']]))
                                    ? $feature['custom_value'][$language['id_lang']]
                                    : $defaultValue;

                                $product->addFeaturesCustomToDB($idValue, (int) $language['id_lang'], $valueToAdd);
                            }
                            
                        }
                    }
                }
            }
        } else {
            $this->errors[] = $this->trans('A product must be created before adding features.', [], 'Admin.Catalog.Notification');
        }
    }
}
