### ISSUE TITLE
Using Symfony Request service in Prestashop module

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#20020]
I'm currently developing a custom module for Prestashop and because Prestashop 1.7 is now based on Symfony I am investing some extra time in using the Symfony platform as much as possible rather than using plain old php or Prestashop libraries.

Prestashop now provides a way to obtain a container to Symfony services which can be used anywhere in a module. I am attempting to use this access the Symfony\Component\HttpFoundation\Request services but without luck. Below is what I have tried so far:

`$request = $this->container->get('symfony.component.httpfoundation.request');`

and also

`$request = $this->container->get('request');`

but both result in the error:

`You have requested a non-existent service `

Is it possible to use Request service via the container?

Kind Regards
Musaffar

**Comment by matks** [comment]
Http Requests are not services into Symfony

However you can fetch them by using RequestStack service

Try
```php
$this->container->get('request_stack')->getCurrentRequest();
```

See https://symfony.com/doc/current/service_container/request.html

**Comment by LouiseBonnard** [comment]
@matks, thanks a lot for your answer. I don't really know how to qualify this issue, is there something to be fixed or developed here?

**Comment by matks** [comment]
> @matks, thanks a lot for your answer. I don't really know how to qualify this issue, is there something to be fixed or developed here?

It was rather a question, it could be answered on devdocs.prestashop.com 😉

**Comment by LouiseBonnard** [comment]
Alright then, I close this ticket, thanks! @musaffar-patel, feel free to browse the [developer documentation](https://devdocs.prestashop.com) or the PrestaShop [community forums](https://www.prestashop.com/forums) to have an answer to your question. In case you don't find it, you can consider creating your issue or documentation request on this dedicated repository. ;-)

👉 https://github.com/PrestaShop/docs/issues
