### ISSUE TITLE
Facetted search not showing feature custom values

### ISSUE THREAD

**Issue by TVBZ** [PrestaShop/PrestaShop#20036]
#### Describe the bug

Using the facetted search module on product listing I realised not all my features where in the facetted search.
After inspecting I can see it's the custom values that are missing. All predefined values are there.

#### Expected behavior

I would expect custom values to be listed as well, and also to be compared with predefined values to avoid duplicates.
For example I have a custom value for "Weigth" feature: "400 grams".
If a predefined value excists that is identical to "400 grams" (in current language), it should just add up.

But in general, it would be pleasing to just be able to filter on custom values also.
If not, I would have to make many predefined values that might only be used once.

#### Steps to Reproduce

1. Install PS
2. Add some features and predefined feature values
3. Add some products using predefined values, and add some product using custom values
4. Enable the Facetted search module, enable the feature and rebuild index and all that.
5. See the result in front end. The facetted search only show predefined values.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @TVBZ ,
Thanks for your request.
I will ping out product team and they will decide the outcome of the issue !
Please stay tuned.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,
@TVBZ has an improvement to suggest.

In product editing page, when adding a customized value feature, it would be great to see that value in the faceted search.
Version of Faceted Search used : 3.5.0
![Capture d’écran 2020-07-02 à 18 00 09](https://user-images.githubusercontent.com/16019289/86382378-0bf1df00-bc8e-11ea-9890-7a147847d789.png)
![Capture d’écran 2020-07-02 à 18 02 04](https://user-images.githubusercontent.com/16019289/86382864-380d6000-bc8e-11ea-8189-689677303917.png)
![Capture d’écran 2020-07-02 à 18 02 18](https://user-images.githubusercontent.com/16019289/86382892-3a6fba00-bc8e-11ea-99e4-38e5c3c6d7aa.png)

What do you think about that ?
Thanks!

**Comment by MatShir** [comment]
It makes sense @TVBZ for your feedback. @PierreRambaud as you work on this module, do you think it is doable?

**Comment by PierreRambaud** [comment]
> It makes sense @TVBZ for your feedback. @PierreRambaud as you work on this module, do you think it is doable?

Everything is doable :wink:

**Comment by vlskrbek** [comment]
Please review this and plan it to fix this. As this is missing.
I thought that Prestashop have the field for weight or size but it has not. So you cannot simply write the numbers to features and filter by it. This is missing in prestashop. A lot of products has such a property. I understand that not all of them but even this is very needed.
Please consider that to develope it.
If you want some help I think I can do something but first I need what should I do or show where to start.
