### ISSUE TITLE
Improvement - being able to replace an existing image in product sheet page

### ISSUE THREAD

**Issue by NoZTurn** [PrestaShop/PrestaShop#20035]
#### Is your feature request related to a problem?

you can't replace an exist image with another one. if you want to do so now, you have an upload a new one and delete the old, the associate the new image to its combination.

#### Describe the solution you'd like

I add a new suggestion.

Now, if you want to do replace an image, you have to delete an image and then upload a new one, then associate the new uploaded image to its related combinations.

So I suggest if we can add an option in a proper process, that upload and replace a specific image with a new one, this is better than delete an image and upload a new one, especially in the case that one image is associated with many combinations.

With the new feature added, it's much more simple, you just need to upload and replace a new one, and all its associated combinations relationships remain the same.

About where to place the option, I give 2 suggestions:
1)when clicking on one image there pops an upload image window, after we select an image, the new image will replace the clicked one while the image_id and its associated combinations relationships remain the same.
2)considering now when we click one image, the options result is select one image, so to avoid the conflict, we can add the upload and replace option on the frame on the right when one image is selected.

https://projects.invisionapp.com/d/main?origin=v7#/console/20852909/438849540/preview?scrollOffset=193

#### Additional context

No screenshots.

**Comment by florine2623** [comment]
Hi @NoZTurn ,
Thanks for your request.
Could you provide screenshots of what you would like to see on PrestaShop ?
Maybe something like @rblaurin did ?
Thanks!

**Comment by NoZTurn** [comment]
> Hi @NoZTurn ,
> Thanks for your request.
> Could you provide screenshots of what you would like to see on PrestaShop ?
> Maybe something like @rblaurin did ?
> Thanks!

hello,florine2623, thanks for your quick reply.
I tried my best to made a picture to show my meaning blow,
![product-image-edit](https://user-images.githubusercontent.com/2842182/86411824-abfa3900-bc8b-11ea-81e1-051d70156b8c.jpg)
I don't if you can understand, I'm willing to provide and expain any your questions.

I also find an online demo for this, hope can help you understand easier.
https://0.s3.envato.com/files/41640075/index.html
Thanks!

**Comment by florine2623** [comment]
Ok thanks for the details.
I will pint our product team to let them know about your request.
Please stay tuned!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@NoZTurn would like to be able to replace an existing image with another one from the product sheet page in the BO.
Details are explained in the screenshot sent earlier.
What do you think about that ?

Thanks!

**Comment by colinegin** [comment]
Seems like a nice idea, wdyt @MatShir ?

**Comment by NoZTurn** [comment]
> Hi @PrestaShop/prestashop-product-team ,
> 
> @NoZTurn would like to be able to replace an existing image with another one from the product sheet page in the BO.
> Details are explained in the screenshot sent earlier.
> What do you think about that ?
> 
> Thanks!

Thanks, @florine2623 ,you totally got my meanning, and I think your new issue title can explain the issue more accurate, thanks you.

@colinegin thanks for your reply and opinion.

**Comment by MatShir** [comment]
@PrestaShop/prestashop-designers We could merge both issues https://github.com/PrestaShop/PrestaShop/issues/12773. They seem really relevant. WDYT?

**Comment by prestascott** [comment]
Hi everyone,

Thank you @NoZTurn for your report.

Implementing hover features is really smart. However, we should only be able to replace the image cover by clicking on the current image cover and not on the others. 

This improvement is really interesting and I think we should mix your idea and ideas from issue #12773 like adding bulk actions in order to delete few images at the same time for example.

**Comment by NoZTurn** [comment]
> Hi everyone,
> 
> Thank you @NoZTurn for your report.
> 
> Implementing hover features is really smart. However, we should only be able to replace the image cover by clicking on the current image cover and not on the others.
> 
> This improvement is really interesting and I think we should mix your idea and ideas from issue #12773 like adding bulk actions in order to delete few images at the same time for example.

@prestascott thanks for your attention, the ultimate wanted feature is an image replacement while its combination and color id remains unchanged,and hover feature is only one feasible method from my personal aspact, if you can mix other ideas to achieve image replacement function, that's also very well.
