### ISSUE TITLE
1.7.6.6 shows customer ressurance text everywhere on homepage

### ISSUE THREAD

**Issue by thepixelabs** [PrestaShop/PrestaShop#20037]
#### Describe the bug

After upgrade from 1.7.6.5 to 1.7.6.6 using manual steps at: 
https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/
Downloaded the file, extracted, removed "img" and "override" folder (p.s, there is a typo in the guide, it's written in plural), removed vendor folder from existing shop, copied files and chowned to www-data, used the URL to upgrade database, logged to admin and cleared cache as well

Now my hompage is cluttered with the customer assurance module being hooked everywhere:
displayAfterBodyOpeningTag
displayFooterAfter
displayFooterBefore
displayNavFullWidth
etc..

Not using the default theme.

I remember being able to configure the module and set where I can see the policies, when clicking configure on the module now, i cannot see that configuration, not sure whether it's moved, disappeared or i just remember it being there and it's some place else.

#### Expected behavior

Upgrade and get the same page as before

#### Steps to Reproduce

1. Install prestashop 1.7.6.5
2. Upgrade to 1.7.6.6 manually

**Screenshots**
![image](https://user-images.githubusercontent.com/4767242/86384925-1d3fe900-bc98-11ea-9537-a1ad50587159.png)
![image](https://user-images.githubusercontent.com/4767242/86384971-2d57c880-bc98-11ea-97b3-3f52c415bf5a.png)

#### Additional information
I have SSH access to the machine, prestashop installed manually and not using a hosting service.
* PrestaShop version: 1.7.6.6
* PHP version: 7.2

_The issue was of course fixed by removing relevant hooks, but that still weird that it surfaced after upgrading.
I also still cannot find the easy configuration page, not sure if my memory serves me right and it was in the module config or not, if it was.. then it isnt showing (as written above)_

**Comment by florine2623** [comment]
Hi @pixelicous ,
Following your steps I couldn't reproduce your issue.
Reassurance module stayed on the hooks it was before.
Are you using classic theme ?

**Comment by thepixelabs** [comment]
@florine2623 I am using "Apparel" theme, which is a free theme you can find online.
Something must be up with my setup. I created a child theme of that theme to custom some areas, that worked. However if i jump back and forth to original theme, 2 modules i completely disabled become re-enabled - "customer reassurance" and the "my account block", so even though i removed the customer reassurance hooks, they are back.

**Comment by matks** [comment]
FYI someone reported a similar issue https://build.prestashop.com/news/prestashop-1-7-6-7-maintenance-release/#comment-4982835584

**Comment by thepixelabs** [comment]
> FYI someone reported a similar issue https://build.prestashop.com/news/prestashop-1-7-6-7-maintenance-release/#comment-4982835584

thanks for this, it seems like all hooks are actually gone (following what i wrote above), i only have displayReassurance hook now. I also pretty sure I'm right and the module configuration is missing a piece now where it shows where you can place the module (kind of like the default paypal "experience" tab), now i only have the option to configure the text but not where will it appear

**Comment by thepixelabs** [comment]
I did a "reset" for the module, then upgraded it again. It seems like all functionality is back. I can actually change the links of the policies, where they appear etc. I now have "content, "display" and "appearance" once again
