### ISSUE TITLE
Search result in grid are not ok

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#20045]
#### Describe the bug

Search result in grid are not ok when we go to the previous page

#### Steps to Reproduce

1. Go to category "accessoires" & search in the description field "maison" you have two results -> It's OK
2. Click on the previous button of the browser you have one result -> Not OK
3. Reset and search in the description field "maison" in Home category you have three result -> It's Ok

**Screenshots**
https://drive.google.com/file/d/1bmiG8cfDH2KvKc5IbtnG6WcJsTNMittm/view
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: N/A

**Comment by florine2623** [comment]
I'm closing the issue as it is fixed in 8.1.3.


https://github.com/PrestaShop/PrestaShop/assets/16019289/111fe7ca-246f-4c5c-95de-74e04f2ab6b1
