### ISSUE TITLE
Activar imagen del producto en albaran

### ISSUE THREAD

**Issue by Sonialopezjuarez** [PrestaShop/PrestaShop#20042]
Buenos dias,
Tengo la version 1.7.6.5.
No funcuiona activar imagen en albaran pedido
Me pueden ayudar?
Gracias,

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
English is the norm on GitHub.
Also, you need to use the template to explain all details about your issue.
If you need customized help, please contact the support team here : https://addons.prestashop.com/es/388-soporte
I will your issue.

**Comment by Sonialopezjuarez** [comment]
sorry.
I write it to you in English
Thank you
