### ISSUE TITLE
using webservice - Impossible to change product detail lines in orders 

### ISSUE THREAD

**Issue by gusman126** [PrestaShop/PrestaShop#20043]
Using the prestashop webservice I am adding an order.
I add the client -> Ok
I add the address -> Ok
I add the cart -> Ok
I add the main data of the order -> Ok
I add the product details lines -> KO - Ignore
`
$webService = new PrestaShopWebservice($url, $api, false);
$xml = $webService->get(array('url' => $url .'api/orders/?schema=blank'));
$xml->order->valid                      = 1;
$xml->order->date_add = $date;
$xml->order->date_upd = $date;
$xml->order->shipping_number = '';
$xml->order->payment                = $payment;        
$xml->order->total_discounts            = $total_discounts ;
$xml->order->total_discounts_tax_incl   = $total_discounts_tax_incl;
$xml->order->total_discounts_tax_excl   = $total_discounts_tax_excl;
$xml->order->total_paid             = $total_paid;
$xml->order->total_paid_tax_incl        = $total_paid_tax_incl ;
$xml->order->total_paid_tax_excl        = $total_paid_tax_excl ;
$xml->order->total_paid_real        = $total_paid_real;
$xml->order->total_products         = $total_products;
$xml->order->total_products_wt      = $total_products_wt;
$xml->order->total_shipping             = $total_shipping;
$xml->order->total_shipping_tax_incl    = $total_shipping_tax_incl;
$xml->order->total_shipping_tax_excl    = $total_shipping_tax_excl;
		
$xml->order->carrier_tax_rate = '';
		
$xml->order->total_wrapping = $order->total_wrapping;
$xml->order->total_wrapping_tax_incl = $order->total_wrapping_tax_incl;
$xml->order->total_wrapping_tax_excl = $order->total_wrapping_tax_excl;
....
foreach($products as $pro){
		
	$xml->order->associations->order_rows->order_row[$lin]->id             = $lin;
	$xml->order->associations->order_rows->order_row[$lin]->product_id             = $pro['id_product'];
	$xml->order->associations->order_rows->order_row[$lin]->product_attribute_id   = $pro['id_product_attribute'];
	$xml->order->associations->order_rows->order_row[$lin]->product_quantity       = $pro['quantity'];
	$xml->order->associations->order_rows->order_row[$lin]->product_name = $pro['product_name'];
	$xml->order->associations->order_rows->order_row[$lin]->product_reference          = $pro['product_reference'];
	$xml->order->associations->order_rows->order_row[$lin]->product_ean13= $pro['product_ean13'];
	$xml->order->associations->order_rows->order_row[$lin]->product_isbn = '';
	$xml->order->associations->order_rows->order_row[$lin]->product_upc = '';
	$xml->order->associations->order_rows->order_row[$lin]->product_price          = $pro['original_price'];
	$xml->order->associations->order_rows->order_row[$lin]->unit_price_tax_incl = $pro['unit_price_tax_incl'];
	$xml->order->associations->order_rows->order_row[$lin]->unit_price_tax_excl = $pro['unit_price_tax_excl'];
	$lin++;
}

$opt = array( 'resource' => 'orders' );
$opt['postXml'] = $xml->asXML();
$xmlres = $webService->add( $opt );

`
I add the order -> Ok, with original prices of the product, do not use my prices
I read the order using webservice and I read the order details lines
I change the details of each product detail line and the order

`
foreach($xmlres->order->associations->order_rows->order_row as $order_detail){
				
$id = $order_detail->id;
$webService = new PrestaShopWebservice($url, $api,false);

$opt = array(
	'resource' => 'order_details',
	'id' => (int)$id					
);
$xmldt = $webService->get($opt);
					
$xmldrdt =$xmldt->asXML();
$xmldt->order_detail->unit_price_tax_incl = round($pros[$lin]['unit_price_tax_incl'],6);
$xmldt->order_detail->unit_price_tax_excl = round($pros[$lin]['unit_price_tax_excl'],6);
$xmldt->order_detail->total_price_tax_incl = round($pros[$lin]['unit_price_tax_incl'] * $order_detail->product_quantity,6);
$xmldt->order_detail->total_price_tax_excl = round($pros[$lin]['unit_price_tax_excl'] * $order_detail->product_quantity,6);

$webService = new PrestaShopWebservice($url, $api, false);
$opt = array( 'resource' => 'order_details','id' => (int)$id);
$opt['postXml'] = $xmldt->asXML();
$xmlresm = $webService->edit( $opt );

}
`

I send the modification of the order detail line -> KO, error does not work, "bad Requested"

#### Steps to Reproduce

Use webservice, 
Read xml Order blank, 
add data, 
change prices products in details orders
send webservice ADD or edit option

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers could you check this please ? :)

**Comment by BlackKerio** [comment]
@gusman126  The question is, why change the price of the product in the order? If I am not mistaken, this option is not even BO

**Comment by gusman126** [comment]
> @gusman126 The question is, why change the price of the product in the order? If I am not mistaken, this option is not even BO

Because I have several stores, each store has a different price for the products, when I want to centralize the orders, I want the prices to be the same as other stores, other ERP,

**Comment by sowbiba** [comment]
```php
<?php
error_reporting(-1);
ini_set('display_errors', 'on');

//Instance de l'objet
$ws = new PrestaShopWebservice(
                            'http://prestashop176x.develop',
                            'RJRS2R4YBRSL4IBIYYD46BDEC35LAGNU',
                            true);

//On récupère le format XML de base
$xml = $ws->get(array('url' => 'http://prestashop176x.develop/api/orders/5'));


foreach($xml->order->associations->order_rows as $order) {
	$id = $order->order_row->id;
	$opt = array(
		'resource' => 'order_details',
		'id' => (int)$id
	);
	$xmldt = $ws->get($opt);
	var_dump((int)$xmldt->order_detail->id);

	$xmldt->order_detail->unit_price_tax_incl = round(999, 6);
	$opt['putXml'] = $xmldt->asXML();
	$xml2 = $ws->edit($opt);
}
```

If you use `$opt['putXml']` and not `$opt['postXml']` it works well for me
