### ISSUE TITLE
(1/1) ContextErrorException Notice: Undefined index: id_order

### ISSUE THREAD

**Issue by estebangarviso** [PrestaShop/PrestaShop#20041]
#### Describe the bug

Here is the html error 500 message that I get when I follow the steps explained below.
[contacto.zip](https://github.com/PrestaShop/PrestaShop/files/4867745/contacto.zip)

#### Expected behavior

Help I need a solution please.

#### Steps to Reproduce

1. As a customer go to contactform url and send a test request
2. As a employee response the email in customer service in BO
3. As a customer click the url (https://domain.com/contact?id_customer_thread=3&token=eqCAApTwNZab) to reply the email
4. You can see the error

**Screenshots**

![image](https://user-images.githubusercontent.com/52897189/86432873-209e9900-bcc7-11ea-9650-ea0816a8d326.png)

#### Additional information
* PrestaShop version: 1.7.6.5
* contactform 4.2.0
* Información del servidor Linux #1 SMP Tue Jul 23 08:31:06 EDT 2019 x86_64
* Versión del software del servidor: LiteSpeed
* Versión PHP: 7.2.31
* Límite de memoria: 768M
* Tiempo máx. de ejecución: 300
* Tamaño máx. para la subida de archivos: 128M

**Comment by estebangarviso** [comment]
I overrided the contactform.tpl in my child theme line 65:

Before->`{if $contact.orders}`

After->`{if $contact.orders && isset($contact.orders[0]['id_order'])}`

But I think Prestashop Team need to fix the php file, more specific the "getTemplateVarOrders" function

**Comment by florine2623** [comment]
Hi @estebangarviso ,
So the override was the issue ?
Thanks!

**Comment by estebangarviso** [comment]
> Hi @estebangarviso ,
> So the override was the issue ?
> Thanks!

Sorry I mean that i overrided the tpl to solve this problem.

The problem happens when a customer send a request from /contact url and this customer doesn't have a order. So the script statement `{if $contact.orders}` in the contact.tpl pass like true with a empty new Product:: call without a id_order.
Then if you override this with `{if $contact.orders && isset($contact.orders[0]['id_order'])}` your saying that if it not exist a id_order, the statement is false.

**Comment by khouloudbelguith** [comment]
Hi @estebangarviso,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.7, PS1.7.5.2, 1.7.7.x branch and the `contactform` module v4.2.0.
![image](https://user-images.githubusercontent.com/16067358/87438204-88ba7c80-c5ef-11ea-9ec5-db93a07d0c7a.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PierreRambaud** [comment]
Hey @khouloudbelguith I didn't manage to reproduce the issue, is it still present?

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

Yes, I did not manage to reproduce the issue with the 178x branch and 177x branch using the `contactform` module v4.3.0.
https://drive.google.com/file/d/1WQR-GXY1ko5jWPU_cNQCUQVXEiIcdjCt/view?usp=sharing

I will close the issue.

Thank you!
