### ISSUE TITLE
We need to find out why bug #20044 is not breaking the product page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20047]
#### Describe the bug

We have confirmed a JS error in 1.7.6.6 code thanks to @JBWModules through his bug report https://github.com/PrestaShop/PrestaShop/issues/20044 .

We expect this code error to break the FO product page, which should prevent actions such as "switching from one combination to another" (example: a Tshirt available in S, M, L and black or white) or "adding products to cart". But these actions work well in 1.7.6.6 ZIP to the best of our knowledge.

We need to understand why the issue reported in https://github.com/PrestaShop/PrestaShop/issues/20044 is not breaking the page.

**Comment by sarahdib** [comment]
Test the minimal quantity : https://drive.google.com/file/d/1gAWLzJitBq07q1OS8jP0YnlP4mGKdJos/view
Test the attribute : https://drive.google.com/file/d/1FcLPQPhPrXb50nllxhVgMpqrUcapojmV/view

**Comment by matks** [comment]
We have identified that in 1.7.6.6, on the FO product page

1. the JS event `updateProduct` is correctly fired
2. some JS code, including part (100% ? not sure) JS code from the Core works
3. some JS crashes (hence the console error)
4. the JS code listening that is called AFTER the crash on the event does NOT receive the event

Since most of Core behavior belongs to 2. ; this is why they are not broken and it was not seen during QA test campaign for 1.7.6.6
