### ISSUE TITLE
cart without free transport

### ISSUE THREAD

**Issue by cgermanb** [PrestaShop/PrestaShop#20040]
Hi, I see a recurring question on google:
When starting the purchase, free transport appears in the cart by default, there should be a way to remove it and that it appears only when the user is about to select the transport.
Some change the translation from free to configuring or to agree, but I don't think it is the correct solution.

**Comment by florine2623** [comment]
Hi @cgermanb ,
You can choose the default carrier to show in the cart in Shipping > Preferences :
![Capture d’écran 2020-07-03 à 10 57 11](https://user-images.githubusercontent.com/16019289/86452106-24103f80-bd1c-11ea-9bd5-bdcdc154d117.png)
So in your cart, the shipping price of your default carrier will be displayed :
![Capture d’écran 2020-07-03 à 10 58 03](https://user-images.githubusercontent.com/16019289/86452167-34281f00-bd1c-11ea-97d5-e09028a3c200.png)
Thanks!
