### ISSUE TITLE
Home category ID not correctly set when installing Prestashop to a Multi-Master MariaDB Galera Cluster

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#20050]
Related to [this](https://github.com/PrestaShop/PrestaShop/pull/16813) commit

When applying the patch installation goes fine but 
home category is  written to forcefully have ID 2 in ps_shop table (hardcoded?)
so categories are "broken" and not visibile in BO

Hardcoding categories ID cannot work in a non-unity autoincrement enviornment as home category 
is not predictable and it will get a different value in ps_category table due to AI offset,
so installer should take care of this.

How to reproduce :
- Deploy a Prestashop fresh install to a Multi-Master Galera Cluster 
- Check the inconstency of "Home"  ID category between ps_category / ps_shop

**Comment by florine2623** [comment]
Hi @gennaris ,
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by gennaris** [comment]
Hi @florine2623 ,
Note that I was asked to open this issue after reporting the problem in #16813 

This is related to the deployment of prestashop in a **multiple servers / nodes** to obtain HA / horizonal scaling, 
it can be reproduced by installing the latest 1.7.6.6 on every compatible webserver.

The only relevant configuration to reproduce this bug is the **database** which must be deployed in a 3-nodes (or more) 
MariaDB Galera Cluster (any version) with Multi-Master.
 
This is a pretty common scenario when deploying applications a HA enviornment.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
Coud you take this issue please ? It is about PS deployment.
Thanks !

**Comment by matks** [comment]
Hi, honestly we have never seen someone deploy a PrestaShop on a Multi-Master Galera Cluster. It's nice to know 😄 it's always good to know how people use and deploy your software but we have zero knowledge of this very specific config/setting and consequently cannot help you

Only thing that could help you is https://github.com/PrestaShop/PrestaShop/issues/15019

**Comment by gennaris** [comment]
Ok I will see how to deal with it , but keep in mind that #15019 is an incomplete/wrong patch, 
because even if installation succeed, it will lead to the error reported here.
