### ISSUE TITLE
Logo SVG Prestashop 1.7

### ISSUE THREAD

**Issue by acanopo** [PrestaShop/PrestaShop#20053]
I think that a module can be the solution to upload svg logo in prestashop 1.7, one that has been created correctly has been created and it can be a temporary solution until prestashop implements another solution.

https://www.xn--comercioelectronicoespaa-nlc.es/tienda/inicio/34-log-en-formato-svg.html

**Comment by florine2623** [comment]
Hi @acanopo ,
Could you follow the template of the improvement issue ?
Thanks!

**Comment by florine2623** [comment]
Hi @acanopo ,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
