### ISSUE TITLE
Autoupgrade failed: container is null - Call to a member function get() on null

### ISSUE THREAD

**Issue by kevindepoortere** [PrestaShop/PrestaShop#20051]
#### Describe the bug

I have an error during the 1 click upgrade proccess.
At then end, during database upgrade I have some problems with currency table
```
[INTERNAL] /var/www/preprod-bellopasso/admin402v3zqsj/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null
#0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang()
#1 /var/www/preprod-bellopasso/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array)
#2 /var/www/preprod-bellopasso/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') 
#3 /var/www/preprod-bellopasso/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...')
#4 /var/www/preprod-bellopasso/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.5.1')
#5 /var/www/preprod-bellopasso/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.5.1'
#6 /var/www/preprod-bellopasso/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#7 /var/www/preprod-bellopasso/admin402v3zqsj/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#8 {main}
```

#### Steps to Reproduce

1. Go to 1 click upgrade page
2. Launch the upgrade
3. Wait for Database upgrade

**Screenshots**

![image](https://user-images.githubusercontent.com/2325159/86464058-00a2c000-bd2f-11ea-9af0-9dec18135188.png)

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.3

**Comment by matks** [comment]
Hi, php7.3 is not yet supported by PrestaShop. That might be the reason for your issue

**Comment by kevindepoortere** [comment]
I will try with PHP 7.2, I need to configure another environment before. 
Unfortunately, I'm not sure that the problem comes from the PHP version, because, minors PHP version are supposed to send notice or warning, not error.

The error is : 
`/var/www/preprod-bellopasso/admin402v3zqsj/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null `

It seems to come from a currency data problem. Perhaps I need to configure some data before executing upgrade.php

**Comment by kevindepoortere** [comment]
Also, one more thing, before doing the upgrade I've activated multishop option. As I had some problems with multishop, I choose to upgrade to see if there was some bug fix.

**Comment by florine2623** [comment]
You can check all the system requirements here :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by kevindepoortere** [comment]
Hi,
Here you can see the requirements.
![image](https://user-images.githubusercontent.com/2325159/86491147-3749fc00-bd6a-11ea-9090-84e9c2aee723.png)
![image](https://user-images.githubusercontent.com/2325159/86491157-44ff8180-bd6a-11ea-888e-ec44be56b5b4.png)
![image](https://user-images.githubusercontent.com/2325159/86491168-4fba1680-bd6a-11ea-8f36-747c1448b0bf.png)

I just need to upgrade post_max_size & upload_max_filesize but in my case, it doesn't seems to be the problem.
By the way, since I've done the upgrade, I can't login anymore to the back office.

**Comment by kevindepoortere** [comment]
Here is the error when I try to connect to the backoffice : 

`[php7:error] [pid 19296] [client 193.56.244.104:50291] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Cannot use object of type Symfony\\Component\\HttpFoundation\\ParameterBag as array in /var/www/preprod-bellopasso/src/Adapter/Security/Admin.php:91\nStack trace:\n#0 /var/www/preprod-bellopasso/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\\PrestaShop\\Adapter\\Security\\Admin->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#1 /var/www/preprod-bellopasso/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#2 /var/www/preprod-bellopasso/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Com in /var/www/preprod-bellopasso/src/Adapter/Security/Admin.php on line 91, referer: https://preprod.bello-passo.com/admin402v3zqsj/index.php?controller=AdminLogin&token=edf71773f60ef06f74e928b9411fd0e7
`

Maybe linked to : https://github.com/PrestaShop/PrestaShop/issues/15815 ?

**Comment by florine2623** [comment]
Is your issue the same as this one : https://github.com/PrestaShop/PrestaShop/issues/20079 ?

**Comment by kevindepoortere** [comment]
@florine2623 I don't think so.

For the login problem, it seems to be the same as #15815 issue.
For the initial problem, it's about currency_lang, the update try to do get on null, so probably a needed currency value is empty on my project.

**Comment by matks** [comment]
For the login issue, we have multiple reports of it https://github.com/PrestaShop/PrestaShop/issues/20079
In the thread are provided solutions that worked for some people.

> For the initial problem, it's about currency_lang, the update try to do get on null, so probably a needed currency value is empty on my project.

No this is different. Look at error:
```
[INTERNAL] /var/www/preprod-bellopasso/admin402v3zqsj/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null
```
And here is the line 55 of file ps_1760_copy_data_from_currency_to_currency_lang.php :
```
    $localeRepoCLDR = $container->get('prestashop.core.localization.cldr.locale_repository');
```

It failed because `$container` is null.

Which means this is a duplicate issue as https://github.com/PrestaShop/PrestaShop/issues/16845 explains the same situation.

Can you tell us which version of auto-upgrade module you used ?

> Unfortunately, I'm not sure that the problem comes from the PHP version, because, minors PHP version are supposed to send notice or warning, not error.

We agree that this is what PHP versions are supposed to do ... but I am afraid this is far from reality 😞  PHP7.3 come with some BC breaks in it that can crash your code that was running fine with php7.2 .

**Comment by khouloudbelguith** [comment]
Hi @kevindepoortere,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
