### ISSUE TITLE
Prestashop 1.7.6.5, Mail alerts 2.2.0:  Table 'prestashop.ps_mailalert_customer_oos' doesn't exist

### ISSUE THREAD

**Issue by Xionoxid** [PrestaShop/PrestaShop#20068]
Hello, 

I've an error: Table 'prestashop.ps_mailalert_customer_oos' doesn't exist when I click on the button 'My Alerts' in my account. 
The table is not found in my database. I've installed it from the Module Catalog in the backend.

Prestashop version: 1.7.6.5
PHP version: 7.2.21
MySQL version: 5.7.26

Error:
`[PrestaShopDatabaseException]
Table 'prestashop.ps_mailalert_customer_oos' doesn't exist<br /><br /><pre> SELECT ma.`id_product`, p.`quantity` AS product_quantity, pl.`name`, ma.`id_product_attribute` FROM `ps_mailalert_customer_oos` ma JOIN `ps_product` p ON (p.`id_product` = ma.`id_product`) INNER JOIN ps_product_shop product_shop ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1) LEFT JOIN `ps_product_lang` pl ON (pl.`id_product` = p.`id_product` AND pl.id_shop IN (1)) WHERE product_shop.`active` = 1 AND (ma.`id_customer` = 2 OR ma.`customer_email` = '******') AND pl.`id_lang` = 1 AND ma.id_shop IN (1) </pre>
at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 613 - classes/db/Db.php] - [1 Arguments]
DbCore->executeS - [line 281 - modules/ps_emailalerts/MailAlert.php] - [1 Arguments]
MailAlert::getProducts - [line 111 - modules/ps_emailalerts/MailAlert.php] - [2 Arguments]
MailAlert::getMailAlerts - [line 58 - modules/ps_emailalerts/controllers/front/account.php] - [2 Arguments]
Ps_EmailAlertsAccountModuleFrontController->initContent - [line 292 - classes/controller/Controller.php]
ControllerCore->run - [line 515 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]`

**Comment by sarahdib** [comment]
Hello @Xionoxid 

Thank you for your feedback!

I reproduce the issue :
1. Install module mail alert
2. Activate notification for out of stock product
3. Go to FO in the customer account
4. Click on my alert 
5. See the error 
<img width="1274" alt="Capture d’écran 2020-07-06 à 14 27 52" src="https://user-images.githubusercontent.com/3034677/86593211-17e2e700-bf95-11ea-817f-ca112317fe6e.png">

**Comment by MarcinZbikowski** [comment]
I think the problem is in ps_emailalerts.php in line 118
`if ($delete_params && $this->uninstallPrestaShop16Module()) {`

In my case it's fresh install, not migration from PS 1.6, so I simply changed that line to:
`if ($delete_params) {`

Now module works.

**Comment by hibatallahAouadni** [comment]
Hello @sarahdib 

I didn't manage to reproduce the issue with ps_emailalerts v2.2.1 and PS17.7.0, see the attached screen record below:

https://drive.google.com/file/d/1ZrDIoU8z1EbC55xoq4PYg62FrmYjkbSu/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Xionoxid 

As I mentioned above I didn't manage to reproduce the issue with ps_emailalerts v2.2.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/112360995-3760a200-8cd3-11eb-9afb-d2f9c0fe110c.png)

So, I close this issue :wink: 
Thanks!
