### ISSUE TITLE
1.4 link to PayPal merchant not working

### ISSUE THREAD

**Issue by Newshound15** [PrestaShop/PrestaShop#20065]
<!--
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************

Customers cannot pay

#### Expected

Checkout page should leave Prestashop and go to PayPal merchant payment

#### Steps to Reproduce

**Screenshots**

![image](https://user-images.githubusercontent.com/67871986/86538004-15c44e00-beeb-11ea-987e-491d109c110f.png)

#### Additional information

* PrestaShop version: 1.4
* PHP version: N/A  No idea what this means !!

**Comment by Newshound15** [comment]
![Payment screen](https://user-images.githubusercontent.com/67871986/86538015-342a4980-beeb-11ea-9db0-e5def1822ee3.jpeg)

**Comment by Newshound15** [comment]
Instead of customers going to PayPal merchant page, they get this.
![Payment screen](https://user-images.githubusercontent.com/67871986/86538048-68056f00-beeb-11ea-88ea-b8754899da30.jpeg)

**Comment by sarahdib** [comment]
Hello

PrestaShop 1.4 has reached end of life and is no longer officially maintained.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
