### ISSUE TITLE
Prestashop 1.7.6.5 disable autologin after registration

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#20062]
Version : 1.7.6.5

By default customer when register, atuo login with activated account.

I want that by default customer dont login and his account is deactivated by default

**Comment by kpodemski** [comment]
You should search for a module to do that.

You can search for "customer activation module", or "customer acceptation" at addons.prestashop.com

**Comment by pks891618** [comment]
But there must be  option customer must be disabled by default

**Comment by kpodemski** [comment]
There's no such an option by default in PrestaShop and it's weird to even have it, PrestaShop is not a B2B software by default

**Comment by pks891618** [comment]
@kpavlovsky, ok does it mean that if Prestashop don't design for B2B software then why there is an option for B2B in admin ?

Sir instead of giving a solution, you are just giving an explanation of the Prestashop complexity

its a request to you guys that if you are not able to give correct solution don't use GitHub to  show the limitation of your or the platform you are using.

I see your profile sir, you are a developer and instead of saying that "There's no such an option by default in PrestaShop and it's weird to even have it, PrestaShop is not a B2B software by default" you have to just let me know either you know or not.

**Comment by kpodemski** [comment]
@pks891618 

I gave you a solution, it's a third party module with this feature :)

https://addons.prestashop.com/pl/bezpieczestwa-dostepu/27191-customer-activation-b2b-login-account-activation.html

https://addons.prestashop.com/pl/klantendienst/30524-customer-account-activation-new-account-moderation.html

https://addons.prestashop.com/pl/klantendienst/6863-customer-activation-activation-compte-client.html

**Comment by pks891618** [comment]
Sorry but if i need to just purchase the module then why i will come to GitHub and raise the issue :)

**Comment by kpodemski** [comment]
You can open a feature request then:
https://github.com/PrestaShop/PrestaShop/issues/new?template=2_feature_request.md

**Comment by rdy4ever** [comment]
> Sorry but if i need to just purchase the module then why i will come to GitHub and raise the issue :)

Prestashop is an open source software. This means you get to use it for free, but you are not entitled to get customer support from any of its contributors. They may help you, if thy feel like it. If you need customer support, then you should pay for a [support plan](https://addons.prestashop.com/en/388-support). 
Being open source, everyone can help voluntarily, including yourself. But you don't get to DEMAND the project contributors to add features that you may need. You can, however, create a feature request ticket and present your ideea. If the Prestashop team consider it to be useful, they may add it in the software via a PR.
If a feature you want to have is not present, then you may buy a module to add it. That's how it works. If you don't want to buy modules, then you can switch to another e-commerce software. There are, however, other open source projects where most of the modules come from contributors and are free. Drupal is one of them. It even has a [commerce distro](https://drupalcommerce.org/). But to use Drupal, you need way more technical skills then to use Prestashop. So there's that.

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. You can open a feature request and explain exactly what is the feature you want.
@kpodemski gave you the list of the modules you can buy if you need a quick solution.

Thanks for your understanding! and thank you @rdy4ever and @kpodemski 👍

**Comment by pks891618** [comment]
@kpodemski  ah got your point will take care last time.
