### ISSUE TITLE
Translation issue in customer account creation or customer information before payment of the order

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#20072]
#### Describe the bug

Because of a country translation bug, customers abandon their cart because they don't find their country in the list while providing their shipping information.

#### Expected behavior

Countries list must be translated to the selected language of the shop. 
EG:
- a shop is in French, all countries must be listed in their French translation
- a shop in in English, all countries must be listed in their English translation

So customer can find their country in their langage, validate their account and confirm the order.

#### Steps to Reproduce

1/ Browse multi-lang website like shop.marc-folly.com (URL is given as an example) and select the English version in the top menu
2/ Add something to the cart
3/ Go to checkout
4/ Start to add information about yourself (like creating an account, or being a guest customer)
on step 2, "Adresses", select your country. Some are translated (United Kingdom) some are not (Etats-Unis)

-> Customers from the United States of America won't find their countries, listed as Etats-Unis. So they can't validate their address and go to the next step, and then abandon their cart.

**Screenshots**

On the English version of the website, some country names are translated some not:
![Selection_833](https://user-images.githubusercontent.com/4619685/86594956-3eeee800-bf98-11ea-9b4f-a6236dc2742b.png)
![Selection_832](https://user-images.githubusercontent.com/4619685/86594963-42826f00-bf98-11ea-80dd-89a81c7098c0.png)

Note than on the French version, United Kingdom is well translated in French as Royaume-Uni:
![Selection_834](https://user-images.githubusercontent.com/4619685/86595160-9a20da80-bf98-11ea-831b-17b6280d7d22.png)

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.2

**Comment by florine2623** [comment]
This issue is fixed.

<img width="797" alt="Screenshot 2023-09-29 at 10 39 27" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ecbcffe7-1c21-4352-8e2d-0374db70d530">
<img width="768" alt="Screenshot 2023-09-29 at 10 39 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/eac81761-dcf1-4e73-8e0b-91151930e14c">
