### ISSUE TITLE
<br /> displayed in check address after order

### ISSUE THREAD

**Issue by antoine1003** [PrestaShop/PrestaShop#20075]
#### Describe the bug

After making a command paid by check, if the address specified in backend contains lines break, the `<br />` tag is not interpreted in HTML.

#### Expected behavior

The address should be display with line break.

#### Steps to Reproduce

(Before follow those steps, the address needs to be set up in backend : Paiements / Check => click on Configure)

1. Any product and click `Add to cart`
2. Go to cart and follow steps until payment
3. Select payment mode `check`

**Screenshots**

_Backend : _

![Backend](https://user-images.githubusercontent.com/15017551/86646682-bd22ad00-bfdf-11ea-8f12-051e73f6390e.PNG)
 
_Frontend : _

![Frontend](https://user-images.githubusercontent.com/15017551/86646469-94021c80-bfdf-11ea-9097-0f3c3f7b4ec4.PNG)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.10

**Comment by sarahdib** [comment]
Hello @antoine1003 

Thank you for your feedback!

I was able to reproduce the issue.
<img width="440" alt="Capture d’écran 2020-07-07 à 10 39 10" src="https://user-images.githubusercontent.com/3034677/86750395-3650ed00-c03e-11ea-8dc6-fabba917173a.png">

I’ll add this to the debug backlog. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by antoine1003** [comment]
Hey Sarah,
I nobody does, I'll correct it in the week 😃

**Comment by Sinepel** [comment]
Hello,

I did the PR to correct on the ps_checkpayment module : https://github.com/PrestaShop/ps_checkpayment/pull/33

Have a good day :)

**Comment by Sinepel** [comment]
@sarahdib Hi, PR is merged ! :)

**Comment by Progi1984** [comment]
Thanks @Sinepel
