### ISSUE TITLE
The style of confirmation box for "single delete" has changed on some BO pages in 1.7.6.6

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20085]
#### Describe the bug

The style of confirmation box for "single delete" has changed on some BO pages in 1.7.6.6, such as "Attributes" or "Features" listings.

#### Expected behavior

We should, as much as possible, keep the style of the window used before. This change, by the way, broke some e2e tests.

**Screenshots**

![image (1)](https://user-images.githubusercontent.com/3830050/86789000-197cdf80-c067-11ea-8083-a435c9b8b703.png)

#### Additional information

* PrestaShop version: 1.7.6.6

---
Updated by @marionf 
This behavior is expected, we need to update the tests

**Comment by matks** [comment]
ping @boubkerbribri @Robin-Fischer-PS 

This bug was reported by QA during 1.7.6.6 build and was considered not blocking for release.

**Comment by marionf** [comment]
@matks as it's a regression, we should fix it for the 1.7.7
@Robin-Fischer-PS @boubkerbribri  Are there other pages in addition to Attributes & Features ?

**Comment by matks** [comment]
> @matks as it's a regression, we should fix it for the 1.7.7
> @Robin-Fischer-PS @boubkerbribri Are there other pages in addition to Attributes & Features ?

Any listing still being rendered by legacy (= not symfony) code, that has a "single delete" action.

**Comment by marionf** [comment]
@PrestaShop/qa-automation We need to update the tests
This new modal is expected to fix an XSS

**Comment by boubkerbribri** [comment]
@marionf I will fix the tests.
Please ping me if confirmation Box style of legacy page change (because this one is the different from the one on symfony pages).

Thanks

**Comment by boubkerbribri** [comment]
Tests were fixed as part of #19997
