### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by katerinatikhonova** [PrestaShop/PrestaShop#20082]
#### estaba instalando un modulo de enlace autorizacion de cliente en mi prestashop cuando ocurrio el error 500

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sarahdib** [comment]
Hello 

Please, send your request in English.
English is the norm on GitHub

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Please be carful when you submitting screenshots, your BO link is visible. Don't send your BO URL in public platform.

Please change your admin folder for **security reason**.

Thank you!
