### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by katerinatikhonova** [PrestaShop/PrestaShop#20087]
#### Describe the bug

Hello 

I was installing the module when suddenly the error 500 appeared so now I cant edit the page :(

http://tienda.katerinatihonova.com/

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

**Please be carful when you submitting screenshots, your BO link is visible.**

Thank you!
