### ISSUE TITLE
Create Back-Office page(s) to manage customer and employee sessions SQL tables

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20084]
In PS 1.7.6.6, in order to correctly handle user session expiration, two new SQL tables have been added to PrestaShop MySQL schema: `ps_customer_session` and `ps_employee_session`. These SQL tables are used for security purposes.

Each customer/employee will create one row inside one of these tables. Over time these tables will become very big.

Thanks to @kpodemski who performed a quick benchmark, we know these tables scale quite well 😊 however we should provide merchants some basic capabilities to
- monitor the content of these tables
- clean irrelevant (= old, unused anymore) rows

I suggest three features:

- [x] Add timestamps to rows
  
  Add timestamps `created_at` and `updated_at` fields to the 2 tables. This will help us 
  identify "old and unused" rows. An old and unused row has 2 very old timestamps.

- [x] Create a new Back-Office page
  
  With 2 listings using [The Grid](https://devdocs.prestashop.com/1.7/development/components/grid/) to allow merchants to
  
  - see, search, filter and sort these tables content
  - be able to use "single delete" and "bulk delete" actions on selected rows

- [x] Create a special action "clean old rows" inside this new BO page
  
  This would delete all rows with timestamps older than 1 or 2 months.

**Comment by matks** [comment]
ping @PrestaShop/prestashop-core-developers @PierreRambaud @kpodemski

**Comment by marionf** [comment]
@matks Is it a regression of 1.7.6.6 ? Or an improvement ?

**Comment by matks** [comment]
> @matks Is it a regression of 1.7.6.6 ? Or an improvement ?

Improvement 😉

**Comment by PierreRambaud** [comment]
You know I approve since we already had this discussion :kissing_heart:

**Comment by matks** [comment]
> You know I approve since we already had this discussion 😘

I pinged you in case you wanted to provide additional ideas / suggestions to the topic 😉

**Comment by sowbiba** [comment]
What would be cool is to automatize the cleaning but we cannot control that. However, we can make a script/route to do it and advice the admins to put it in a cron job

**Comment by PierreRambaud** [comment]
> What would be cool is to automatize the cleaning but we cannot control that. However, we can make a script/route to do it and advice the admins to put it in a cron job

Symfony console command is the solution to this problem :+1:

**Comment by marionf** [comment]
I moved this issue in blocked column, specs & mock-ups should be done before the development

**Comment by HadesStyx** [comment]
you're crazy

**Comment by Progi1984** [comment]
@PierreRambaud We close ?

**Comment by matks** [comment]
@PierreRambaud PR https://github.com/PrestaShop/PrestaShop/pull/21120 states it fixes this issue partially. What's left to do?
