### ISSUE TITLE
Trivial design issues in autoupgrade module display

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20097]
## End of process "no errors reported" badly written

After successfull upgrade to 1.7.6.6, autoupgrade module displays a console return a bit weird:
<img width="1182" alt="Capture d’écran 2020-07-01 à 16 28 33" src="https://user-images.githubusercontent.com/3830050/86904449-07f01200-c111-11ea-96a5-26a5812b9c01.png">
The last line is missing the number "zero". What we want to say is "zero errors reported" but we have "errors reported".

## Mix of French and English in the module page

<img width="798" alt="Capture d’écran 2020-07-03 à 09 30 13" src="https://user-images.githubusercontent.com/3830050/86904585-3968dd80-c111-11ea-96d5-7b6663211b12.png">

**Comment by marionf** [comment]
Hello @matks 
This message will be removed in the new version of the upgrade module, so I close this issue

**Comment by marionf** [comment]
Little change, I re-open this issue

**Comment by gericfo** [comment]
Hello, 
We are currently working on these messages for the new version of the module. I close this issue.
