### ISSUE TITLE
Template product-list.tpl contains not unique id attribute

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#20093]
**the html output with not unique id="js-product-list-bottom"** 
```
<div id="js-product-list-bottom">
          
    <div id="js-product-list-bottom"></div>
          
</div>
```

is caused by
**themes/classic/templates/catalog/listing/product-list.tpl** template
```
        <div id="js-product-list-bottom">
          {block name='product_list_bottom'}
            {include file='catalog/_partials/products-bottom.tpl' listing=$listing}
          {/block}
        </div>
```
and

**themes/classic/templates/catalog/_partials/products-bottom.tpl** template
```
<div id="js-product-list-bottom"></div>

```

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers WDYT about that, is it a bug ? An improvement ?

**Comment by matks** [comment]
> @PrestaShop/prestashop-core-developers WDYT about that, is it a bug ? An improvement ?

Using duplicate id attribute values is invalid HTML, as HTML specification clearly states that attributes must be unique.

Most browsers can handle duplicate ids, but theoretically they can cause issues if the JavaScript is parsing or calling DOM elements based on these id values.

This is a bug, and the primary issue will be for modules, and this might hurt SEO (I dont know if SEO score is impacted by HTML validity, do you know @NeOMakinG ?)

**Comment by NeOMakinG** [comment]
@matks nothing proof, but as long as Google robots are parsing html pages, the SEO could be impacted, but none can prove it exactly, also I think as long as Google can read the page, it shouldn't be impacting too much..

But that can cause accessibility access and invalid the HTML for a validator as W3C.

Btw I'm not sure we're able to change a behavior not buggy inside a patch version, maybe we should wait for the major in order to keep module working :/

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers what's the statuts of this issue? can we close it?

**Comment by NeOMakinG** [comment]
Hey @hibatallahAouadni ,

Don't close it, this is something we need to fix as it's not respecting standards at all :)

**Comment by hibatallahAouadni** [comment]
Hi @NeOMakinG , ok

Ping @marionf, should I add to Epic? or add another label?
