### ISSUE TITLE
Properly define common logic to be able to reuse it everywhere, specially in modules

### ISSUE THREAD

**Issue by elboletaire** [PrestaShop/PrestaShop#20099]
#### Is your feature request related to a problem?

Creating modules in prestashop > 1.7 is currently a PITA due to how most of the code is structured. There's a lot of code that you need to copy-paste, because there are no helpers or these helpers are meant for specific entities, like products. Taking products as an example, there's a lot of logic here that could be generic and not specific to products, ie:

- Get persisted parameters.
- List parameters updater service.
- The pagination limit choices (how is this specific to products?!)
- In general, all the pagination related logic (this could be easily done if using Doctrine instead of... whatever is being used now).
- JS stuff, like the remove entities js, which includes a modal and some javascript specifically written for products. 
- View widgets, like the column filters.

#### Describe the solution you'd like

I'd like to be able to create modules more easily, not requiring me to be copying most of the logic from other parts of prestashop because it's logic specifically written for products or other entities, even though all that copied logic could be the same for any entity.

I also miss more generic template files. For example an easier way to create index pages for entities, without requiring us to import every time all the catalog-required scripts, nor all the desired modal forms, nor the pagination...

Another thing I did found disturbing was the need to create a custom js delete method, because the one used by products is specific for them. In this case I would expect a generic `#remove_modal` with some generic scripts to remove entities. In the end, you're using a lot of html attributes to do this logic, I don't get why is it that specific, when it could be dynamic for all the entities.

#### Alternatives you've considered

Creating my custom module of dependencies with all my generic stuff in there, but I do think prestashop should ease it to us.

#### Additional context

![imatge](https://user-images.githubusercontent.com/153305/86905248-168af900-c112-11ea-8de5-b4d8a72f11c7.png)

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers wdyt of this improvement ?

**Comment by elboletaire** [comment]
This has been tagged as `Modules`, but they would actually be core changes and improvements (even though these improvements would benefit everyone, including module and theme developers).

**Comment by elboletaire** [comment]
https://github.com/PrestaShop/PrestaShop/issues/9972#issuecomment-816610039
