### ISSUE TITLE
[BO Addresses page] - Error after saving new address

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#20095]
#### Describe the bug

An error occurs when trying to add a new address in BO

#### Expected behavior

Address saved, no errors shown

#### Steps to Reproduce

1. Go to 'BO -> Addresses page'
2. Click on 'Add new address'
3. Fill the inputs and click on save

![image](https://user-images.githubusercontent.com/48441421/86892863-19c9b900-c101-11ea-9bd0-07366af1730a.png)

#### Additional information

* PrestaShop version: branch develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20149
