### ISSUE TITLE
 Image before the product name on the delivery note

### ISSUE THREAD

**Issue by Sonialopezjuarez** [PrestaShop/PrestaShop#20101]
#### Describe the bug

The image before the product name on the delivery note is not visible

#### Expected behavior

I expected the image of the product to be seen at dawn

#### Steps to Reproduce

1. I go to orders -> delivery notes
2. active product image
3. I give to save
4. And the product image is not seen in the delivery

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![Captura](https://user-images.githubusercontent.com/63241644/86912506-6e7b2d00-c11d-11ea-8af6-64000f1ecb37.PNG)
[W2000006.pdf](https://github.com/PrestaShop/PrestaShop/files/4890281/W2000006.pdf)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.31

**Comment by marionf** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information with PrestaShop 1.7.6.7

![capture d'écran_2710](https://user-images.githubusercontent.com/13449658/86928681-2a942200-c135-11ea-93c3-123c3a538d29.png)

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thank you!
