### ISSUE TITLE
TrackingNumberUpdate hook not executed if mail fails

### ISSUE THREAD

**Issue by sethsnel** [PrestaShop/PrestaShop#20105]
#### Describe the bug

In my module I've registered a hook with this name "actionAdminOrdersTrackingNumberUpdate".
When I update an TrackingNumber, this update gets saved in database. But if sending a mail to the customer fails, then executing the hook also fails.

#### Expected behavior

Always execute the hook when tracking number gets successfully updated to database. Even though email was not able to be sent to customer.

#### Steps to Reproduce

1. Go to a order in admin
2. Update tracking number
3. actionAdminOrdersTrackingNumberUpdate hook is not executed if sending out mail fails

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

#### Proposed fix
In: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/controllers/admin/AdminOrdersController.php
On line: 506, move Hook:exec to above the if($order_carrier->sendInTransitEmail($order))

I was not able to find this controller and hook:exec anymore in 1.7.7 and develop branch. So I'm unsure how to fix it. Otherwise I would have send in a pull request.

**Comment by sethsnel** [comment]
It seems that it might have been already fixed in 1.7.7:
https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php

I am however reliant on this fix. Is there an estimation 1.7.7 will hit Alpha release?

**Comment by marionf** [comment]
Hello @sethsnel 

We already released the [1.7.7.0 beta](https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/) about 2 months ago and we are going to release the first release candidate very soon, so stay tuned !
Of course, you can test the beta right now or wait a few week to test the release candidate :)

As your problem is fixed in 1.7.7.0 I close this issue, feel free to open a new one if needed !

**Comment by sethsnel** [comment]
@marionf hmm I seem to be unable to upgrade 1.7.7. from beta release channel with the 1-click upgrade module.
In what other way could I easily upgrade? Do you have a suggestion?

![image](https://user-images.githubusercontent.com/3225809/86930653-83fd5080-c137-11ea-9594-9d441287caaf.png)

**Comment by marionf** [comment]
You shouldn't upgrade your production shop to a beta version as it's a pre-release, this why the upgrade to the 1.7.7.0 isn't possible
But you can download it and test it :)

**Comment by sethsnel** [comment]
It's actually not really a production shop. It's a shop in production environment we use solely to develop Prestashop modules.

So they only way to upgrade is manually by uploading version 1.7.7 to the server?

**Comment by marionf** [comment]
You can choose to use a local archive in the autoupgrade module

**Comment by sethsnel** [comment]
@marionf thanks for the support!
