### ISSUE TITLE
Module activation blocked 1.7.5.1

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#20119]
When I try to install the "Form builder pro" module it gives me an error like this: The gformbuilderpro module could not be enabled. Unable to install override: The initContent method in the CmsController class is already canceled by the appagebuilder module version 2.2.3 at 2019-06-18 15:14:41 .blocked "
How can I solve it?

**Comment by florine2623** [comment]
Hi @Webgaict ,
For this issue you should contact the developer of the module or the support team here : https://addons.prestashop.com/en/388-support
Thanks!
