### ISSUE TITLE
Lithuanian translation errors

### ISSUE THREAD

**Issue by SH4LT1S** [PrestaShop/PrestaShop#20110]
Image 1: https://ibb.co/WfPm5N0 
EN version: https://ibb.co/yN0cpSd

Image 2: Should say not "Su PVM" but "PVM Suma" below full price
https://ibb.co/7jDh003
EN: https://ibb.co/x3rLQL4

**Comment by florine2623** [comment]
Hi @SH4LT1S ,
Could you follow the issue template ?
Explain the steps to reproduce the issue ?
What version of PS you are using ?
etc
Thanks!

**Comment by SH4LT1S** [comment]
1.7.6.7

Front page as customer, change language to Lithuanian and just add something to basked,

**Comment by florine2623** [comment]
Regarding the Title (P. and P.), should it be changed to something specific ?
If you need to change it, you can go to Shop Parameters > Customers > Titles

For the first image, in the consent bar, you need to change the module GDPR.

**Comment by florine2623** [comment]
Hi @Junebyun ,

@SH4LT1S would like to change the mention "Included taxes" in the shopping cart, to "tax amount" in Lithuanian.
EN : https://ibb.co/7jDh003
LT : https://ibb.co/x3rLQL4

PVM Suma : VAT amount
Su PVM : with tax

Thanks!

Do you think that's relevant ?

**Comment by SH4LT1S** [comment]
> Regarding the Title (P. and P.), should it be changed to something specific ?
> If you need to change it, you can go to Shop Parameters > Customers > Titles
> 
> For the first image, in the consent bar, you need to change the module GDPR.

When its **P** and **P**, customers cant tell the difference between Ponas (Mister - **Mr.**) and Ponia (Missus - **Mrs.**) so in Lithuanian it should be full title not the short version.

**Comment by SH4LT1S** [comment]
> Hi @Junebyun ,
> 
> @SH4LT1S would like to change the mention "Included taxes" in the shopping cart, to "tax amount" in Lithuanian.
> EN : https://ibb.co/7jDh003
> LT : https://ibb.co/x3rLQL4
> 
> PVM Suma : VAT amount
> Su PVM : with tax
> 
> Thanks!
> 
> Do you think that's relevant ?


In English **Total (tax incl.)** means that the price shown (in my screenshot 9,34) includes taxes. = Total (tax included)
And then below it says **Included taxes:** (my screenshot 1.62) so customers know how much from total amount of 9.34 is taxes (1.62)
In Lithuanian **Viso (su PVM)** mean same as in English (price including taxes) but below **Su PVM** 1.62 should say **PVM suma**

**Comment by LouiseBonnard** [comment]
Hi @SH4LT1S, thanks a lot for bringing this issue! For global translation errors, please go to the Lithuanian project on [Crowdin](https://crowdin.com/project/prestashop-official/lt) and subscribe to suggest a more accurate translation. @Junebyun here will be there to onboard you and help you find the original Lithuanian translation of the wording mentioned here. ;-)

If you need a more customized translation, know that you can edit it in the International > Translations section of your back office. @SH4LT1S, @Junebyun, I let you guys close this issue when it is fixed on Crowdin!

**Comment by Junebyun** [comment]
Hi @SH4LT1S thanks for opening this issue! 

Changing the translation "_Su PVM_" to "_PVM suma_" (VAT amount) would require to change the original english string "_included taxes_" so that the translation is accurate. 
However, I think changing this text for PrestaShop users will not be convenient as there can be other taxes than the VAT,  depending on the country. The text "_included taxes_" is more general and not so confusing in english, so I don't think we should change the original string. 

I suggest you to customize this translation for your shop. To change the translation '_Su PVM_' to '_**PVM suma**_', you can do it in your shop's BO in International > Translations > select Themes translations and then Shop > Theme > Checkout like shown below:
![image](https://user-images.githubusercontent.com/64894223/88374292-ce1e3d00-cd99-11ea-8abc-d75d534a9c1c.png)

Let me know if this solves your problem so that I can close this issue! Thank you :)

**Comment by SH4LT1S** [comment]
> Hi @SH4LT1S thanks for opening this issue!
> 
> Changing the translation "_Su PVM_" to "_PVM suma_" (VAT amount) would require to change the original english string "_included taxes_" so that the translation is accurate.
> However, I think changing this text for PrestaShop users will not be convenient as there can be other taxes than the VAT, depending on the country. The text "_included taxes_" is more general and not so confusing in english, so I don't think we should change the original string.
> 
> I suggest you to customize this translation for your shop. To change the translation '_Su PVM_' to '_**PVM suma**_', you can do it in your shop's BO in International > Translations > select Themes translations and then Shop > Theme > Checkout like shown below:
> 
> 
> Let me know if this solves your problem so that I can close this issue! Thank you :)

If it is possible to change it so easily, then ok, thanks for the reply! But please take a look to the first screenshot for the "I agree" box.

**Comment by LouiseBonnard** [comment]
@SH4LT1S, I've found out where the first checkbox message must be translated in Lithuanian: you need to go to the configuration panel of the PrestaShop's **Official GDPR Compliance** module in Modules > Module Manager and edit/translate the consent message, see my screenshot below.

<img width="1394" alt="Capture d’écran 2020-07-27 à 17 07 49" src="https://user-images.githubusercontent.com/32565890/88558642-1b194200-d02c-11ea-833e-36495ef2abe5.png">

I let you confirm that it works on your end!

**Comment by florine2623** [comment]
@SH4LT1S ,
As we have no answer from you for more than 30 days, I'll close your issue.
Thanks!
