### ISSUE TITLE
Display discount without decimals

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20115]
#### Is your feature request related to a problem?
We use product prices without decimals. Also we use discounts and we want to display discount as percentage of amount. It works correctly but the percentage is displayed with 2 decimal places, we'd like to display percentage without decimal places.  

#### Describe the solution you'd like
Example:
Product price: 170,00 €
Required discount: 31,00 €
Discount definition: 18,2353 %

Displayed price without discount: 170,00 €
Displayed price with discount: 139,00 €
Displayed discount: 18,24 % 
Required displayed discount: 18 %

If there was defined discount as 18% the displayed price with discount would be 139,40 € and it is not correct price.

#### Additional context
Add a new configuration for displayed discount percentage where would be possible to define:
- number of decimals for displayed discount percentage 
- how to round displayed discount percentage (up, down ...)

**Comment by florine2623** [comment]
Hi @juraj1000 ,
Thanks for the suggestion. I will ping our product team know about it !
Stay tuned !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@juraj1000 has a feature request.
When using no decimals in the price display, he would like to have the discount percentage in FO also without decimals.
Now the discount percentage looks like that in both 1.7.6.5 and 1.7.7.0 :
![Capture d’écran 2020-07-09 à 10 41 26](https://user-images.githubusercontent.com/16019289/87017948-ed7d6d80-c1d0-11ea-9cc0-fffc4ca5326c.png)

What do you think about that ?

**Comment by juraj1000** [comment]
Hi,
we use decimals in price display like 170,00 € or 139,00 €, so this requirement is only for displaying discount percentage without decimals

**Comment by colinegin** [comment]
Hello @juraj1000 , 

I'm not sure I get your point. You said you use prices without decimals, so if I understand correctly, when setting a discount in percentage (18%), then the display price will be 139€ and not 139,40€. Am I wrong ?

**Comment by juraj1000** [comment]
Hello @colinegin,
we use prices without decimals, but we display prices with decimals. It means we use amounts in € without cents but we   always display cents as zeros, e.g.:    
170,00 € 
139,00 €

**Comment by colinegin** [comment]
I don't see any cents in the example above (screenshot)...

**Comment by juraj1000** [comment]
There are not any cents in the example. This example was created by florine2623 and not by me. I hope now the requirement is clear. Or should I create other example with zero cents?

**Comment by marionf** [comment]
Hello @juraj1000 

With the next version (PS 1.7.7), you will be able to configure the number of decimal for your currency in International > Localization > Currencies

![capture d'écran_2731](https://user-images.githubusercontent.com/13449658/88189905-e5461900-cc39-11ea-9c69-2f4ed2b180c2.png)

![capture d'écran_2732](https://user-images.githubusercontent.com/13449658/88190124-30602c00-cc3a-11ea-8eb4-d0697ae7ebd4.png)

**Comment by juraj1000** [comment]
Hello @marionf,
it seems it is misunderstanding. We want to use € with 2 decimal places and there will be used also cents e.g. for shipping costs. Also for product price with discount there will be displayed price with 2 decimals, but there will be 00 cents. Now everything works correctly with amounts there is not necessary to change anything.

But we'd like to display discount percentage without decimals, now it is always displayed with 2 decimals and we require any  configuration for displaying percentage value.

_Example_
Basic price: €170.00 => OK
Discount price: €139.00 => OK
Discount percentage: **18.24 %** => not OK, we want to display **18%**

![image](https://user-images.githubusercontent.com/33311857/88204920-4d9df600-cc4c-11ea-9947-8199fa204ccd.png)

**Comment by marionf** [comment]
The paremeter to choose the number of decimal is general and applied for all amounts
We can't add a specific parameter allowing to choose the number of decimals just for the discount, this is a very specific need
