### ISSUE TITLE
BO Notifications bell not showing anything

### ISSUE THREAD

**Issue by Djangoum** [PrestaShop/PrestaShop#20129]
#### Describe the bug

New customer registrations and new orders are not beeing shown in my BO notification section

#### Expected behavior

When a new customer or new order is registered, the notification is shown in the bell and within the proper section

#### Steps to Reproduce

1. Make an order in the FO
2. Open BO
3. Look at notifications at the top right section
4. Notice that there is nothing shown there 

(the same with new customers and messages)

**Screenshots**

![image](https://user-images.githubusercontent.com/9842183/87085962-0ddd1480-c231-11ea-90cb-64ceb02ab5e9.png)

Notifications seems to be correctly enabled in configuration 
![image](https://user-images.githubusercontent.com/9842183/87086914-8395b000-c232-11ea-8f52-d65d3c15d539.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

In my error.log file i've found the following every time we open the BO : 

`[Thu Jul 09 20:00:53.432808 2020] [:error] [pid 24437] [client xxxxxxxxxxxxxxxxxxxxxx] PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /var/www/html/src/Adapter/ContainerFinder.php:77\nStack trace:\n#0 /var/www/html/classes/Tools.php(796): PrestaShop\\PrestaShop\\Adapter\\ContainerFinder->getContainer()\n#1 /var/www/html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#2 /var/www/html/classes/Notification.php(133): ToolsCore::displayPrice(2.66, Object(Currency), false)\n#3 /var/www/html/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '2305')\n#4 /var/www/html/adminpanel/ajax.php(125): NotificationCore->getLastElements()\n#5 {main}\n  thrown in /var/www/html/src/Adapter/ContainerFinder.php on line 77, referer: https://xxxxxxxxxxxxxxxxxxx.xxxxx/admin/index.php?controller=AdminDashboard&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

* PrestaShop version: 1.7.6.7
* PHP version: 7.0.33

![image](https://user-images.githubusercontent.com/9842183/87086116-598fbe00-c231-11ea-8926-4505b6d759aa.png)

Please, for us is a very useful feature this BO notifications and i would like to solve the problem! 

Thank you very much !! 👍

**Comment by florine2623** [comment]
Hi @Djangoum ,
I can't reproduce your issue in PS 1.7.6.7.
Did you upgrade your shop ? or is it a fresh install ?

When you enable debug mode and re-do the steps, are there any errors on the way ?

Thanks!

**Comment by Djangoum** [comment]
My shop is an upgrade i upgraded from 1.7.5.x  to 1.7.6.7.

When i do the steps with the debug mode ON. I get no more than not found translations.

**Comment by florine2623** [comment]
Can you check the version of the notification module ?
I'm using v2.1.0.

**Comment by Djangoum** [comment]
Hi! If you mean ps_emailalerts i'm using v2.2.0 

![image](https://user-images.githubusercontent.com/9842183/87179423-01af9080-c2df-11ea-95d3-7bba237a3d65.png)

**Comment by rdy4ever** [comment]
Hi @Djangoum 
Try to hit Ctrl+F5 to force refresh and clear browser cache in the BO. This could do the trick.

**Comment by Djangoum** [comment]
@rdy4ever  I really feel so dumb. The cache clearing solved the problem. Not even think on that could be something Front End related. 

Well, this issue can be closed, sorry for wasting your time @rdy4ever  and @florine2623 i really appreciate you help! 

Thank you very much 😄

**Comment by rdy4ever** [comment]
> @rdy4ever I really feel so dumb. The cache clearing solved the problem. Not even think on that could be something Front End related.
> 
> Well, this issue can be closed, sorry for wasting your time @rdy4ever and @florine2623 i really appreciate you help!
> 
> Thank you very much 😄

No problem @Djangoum 
I've been scratching my head with this one too before thinking to just clear browser cache, so I know exactly how you feel :)

**Comment by matks** [comment]
Thank you @rdy4ever for helping 😉
