### ISSUE TITLE
Webservice returns 401 error for Preflight checks by browser

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#20121]
Hi

I'm developing a web app which will consume Prestashop webservice APIs from a different server.  I have correctly set up the cross domain policy headers on the Prestashop server and these have been tested and are working as expected.

However, when the app attempts to consume an Webservice API request, the browser first performs a preflight check by performing an OPTIONS request.  This request is generated by the browser and headers cannot be added to this request, therefore authentication data is not included in this request.

However, Prestashop returns a 401 Unauthorized error with the following message:
Welcome to PrestaShop Webservice, please enter the authentication key as the login. No password required

As far as I can determine from research, Prestashop should not be requesting authentication for an OPTIONS request, only subsequent non OPTION requests should be authenticated,

Kind Regards
Musaffar

**Comment by matks** [comment]
> However, when the app attempts to consume an Webservice API request, the browser first performs a preflight check by performing an OPTIONS request. This request is generated by the browser and headers cannot be added to this request, therefore authentication data is not included in this request.

This is the default security behavior for browsers indeed.

I think PS webservice was built for server-to-server exchanges, not browser-to-server. This is why OPTIONS requests are not handled.

**Comment by musaffar-patel** [comment]
Hi

Does it not make sense to handle option requests? Or at the very least would be great to disable authenticating them otherwise it is impossible to consume webservices from other web based apps.

In the mean time, would you know which file I should modify to prevent authenticating an Options request?

Kind Regards
Musaffar

**Comment by matks** [comment]
The entry point for webservice http requests is https://github.com/PrestaShop/PrestaShop/blob/develop/webservice/dispatcher.php

> Does it not make sense to handle option requests?

Yes indeed.

I think for this usecase the OPTION request only needs a basic HTTP 200 response with body `Allow: OPTIONS, GET, POST`, right ?

@PierreRambaud would it make sense to have, somewhere in the BO, a small setting On/Off to enable, and when you enable it then the webservice endpoint returns HTTP 200 response with body `Allow: OPTIONS, GET, POST` to any OPTIONS request being sent ? It's safe AFAIK and it allows browsers to use the webservice.

ping @NeOMakinG who might discuss that too

**Comment by musaffar-patel** [comment]
Thanks, your suggestion to have a switch in the back office makes good sense.  In the mean time I'll take a look at dispatcher.php, thanks for pointing me in the right direction.

Kind Regards
Musaffar

**Comment by PierreRambaud** [comment]
> The entry point for webservice http requests is https://github.com/PrestaShop/PrestaShop/blob/develop/webservice/dispatcher.php
> 
> > Does it not make sense to handle option requests?
> 
> Yes indeed.
> 
> I think for this usecase the OPTION request only needs a basic HTTP 200 response with body `Allow: OPTIONS, GET, POST`, right ?
> 
> @PierreRambaud would it make sense to have, somewhere in the BO, a small setting On/Off to enable, and when you enable it then the webservice endpoint returns HTTP 200 response with body `Allow: OPTIONS, GET, POST` to any OPTIONS request being sent ? It's safe AFAIK and it allows browsers to use the webservice.
> 
> ping @NeOMakinG who might discuss that too

Why not only using `Allow: GET, POST` the browser should not trigger the `OPTIONS` :thinking:

**Comment by leccyril** [comment]
hello what news ? i am developing a dashboard in vuejs, GET is working but POST or PUT is returning no status header preflight error ? what workaround can i do please ?

thanks

**Comment by leccyril** [comment]
for me i put this

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS'){
  header('HTTP/1.1 200 OK');
  die();
}

and now it is working

**Comment by matks** [comment]
I move this issue to `To Do` as this is needed for webservice. It will be assigned a priority.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33664
