### ISSUE TITLE
Ajax Cart can't be switched off in 1.7.

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#20133]
#### Describe the bug

When deactivating ajax cart in module ps_shoppingcart, the cart button on product page does not do anything anymore.

#### Expected behavior

Redircetion to cart page after adding to cart

#### Steps to Reproduce

a. Deactivate ajax cart in module ps_shoppingcart
1. Go to Product page
2. Click on 'Add to cart
3. Nothing happens

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![grafik](https://user-images.githubusercontent.com/47666330/87133682-f6854200-c297-11ea-890d-4913e24ac2f0.png)

#### Additional information

* PrestaShop version: 1.7.7Beta
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10025
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10025
