### ISSUE TITLE
www - non www redirect for multistore htaccess automatic implement code

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#20134]
For multistore I suggest that this piece of code would be automatic loaded when a new htaccess is created.

RewriteEngine on
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

For multistore users its very frustrating to find out the htaccess was renewed and then that all redirections for the www. or non www are going to the main store without this code.

I now manually always edit the htaccess file, but since PS generates the file, maybe it can generate it with this incl.

**Comment by florine2623** [comment]
Hi @01park ,
Thanks for the suggestion.
I will ping our dev and product team about it.
Please stay tuned!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers & @PrestaShop/prestashop-product-team ,

@01park is suggesting an improvement for .htaccess in multistore environment.
What do you think about it ?

Thanks!

**Comment by qualityangel** [comment]
Yes please!

**Comment by PierreRambaud** [comment]
I didn't manage to reproduce the issue, could you please give us more information, at least copy your htaccess file?

**Comment by 01park** [comment]
Hi,

I am using the standaard htaccess file. This " issue " is already around since PS 1.6

**Comment by matks** [comment]
Hi, it seems we didn't manage to reproduce the issue, although we use standard htaccess file :/ .

I'm afraid we have no other ideas about how to reproduce your issue. There must be something in your shop / setup / server that makes the issue observable, and without it we cannot confirm this issue.

I close this issue. It does not mean this discussion is over 😉  you can reopen another issue with more informations ; but without something we can use to observe the bug, we cant work on this so I close it.

**Comment by 01park** [comment]
Hi,

The issue I am referring to you is this:

https://www.prestashop.com/forums/topic/215667-no-www-on-shop-domain-and-htaccess-redirects/

The solution is offered here to.

This problem is still in 1.7.7

I don't think it's a real problem, but it is an issue for multi-store users

**Comment by bullmade** [comment]
@matks @florine2623 the issue can only be reproduced in a multistore enviroment.

Also, the solution offered in the post that @01park sent, does not seem to work in PS 1.7.
