### ISSUE TITLE
Impossible to affect payment method to a shipping method 

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#20130]
Hi, I can't affect payement method to a shipping method. When I create a new shipping method, all payement method are automatically associated. However, if I try to modify assignation or even just click on "Save", all tickbox become unchecked and it's impossible to check them anymore.

**The main problem is that there is no error message, no warning, nothing.**

I noticed I had 2 carrier with same name and I saw related problem with this case in recent topics here.

Prestashop 1.7.6.6
PHP : 7.0.33

**Comment by florine2623** [comment]
Hi @passio777x ,
Is your issue related to https://github.com/PrestaShop/PrestaShop/issues/20128 ?
Thanks!

**Comment by passio777x** [comment]
Hi, no it's not the same issue. My problem is that ANYONE checkbox can't be checked even if carrier names are differents.

**Comment by passio777x** [comment]
I paid a developper team, expert in prestashop... They cannot solve the problem in 2 days. Who can help ?

**Comment by matks** [comment]
@passio777x I am sorry but if I try this on PS 1.7.6.6, it works very well, no issue with any checkboxes 🤔  . If I cannot see it fail, I dont see how we can help you.

Did someone customize your shop ? Issues can be introduced by customizations, overrides, installed modules ...

What you can do is
- install a new shop (to perform a test) and verify it works well => just to make sure on a "fresh new shop" everything is OK
- and if on the new shop it works it means something is wrong inside your shop => maybe transfer the data into the new shop to solve it ?

**Comment by passio777x** [comment]
> @passio777x I am sorry but if I try this on PS 1.7.6.6, it works very well, no issue with any checkboxes 🤔 . If I cannot see it fail, I dont see how we can help you.
> 
> Did someone customize your shop ? Issues can be introduced by customizations, overrides, installed modules ...
> 
> What you can do is
> 
> * install a new shop (to perform a test) and verify it works well => just to make sure on a "fresh new shop" everything is OK
> * and if on the new shop it works it means something is wrong inside your shop => maybe transfer the data into the new shop to solve it ?

Thank you Matks, could it be a good idear to create a new shop, and export produts, category, customers and orders ?
Could you tell me the best way to proceed and which tables exports ?

**Comment by matks** [comment]
> Could you tell me the best way to proceed and which tables exports ?

@passio777x We have very good user feedback about this module: https://addons.prestashop.com/fr/migration-donnees-sauvegarde/8934-outil-de-migration-prestashop-passez-a-prestashop-17.html

**Comment by SimonGrn** [comment]
Hello,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support
Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

**Comment by matks** [comment]
@passio777x someone had a similar issue and found a solution => https://github.com/PrestaShop/PrestaShop/issues/20173#issuecomment-658793572
