### ISSUE TITLE
Module added as widget in smarty is displayed no matter if is disabled

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#20138]
#### Describe the bug

When you add widget in your .tpl like this {widget name="module_name"} and module is disabled, widget is still displayed.

#### Expected behavior

Widget shouldn't be displayed when module is disabled.

#### Steps to Reproduce

1. Go to file (open it with editor) index.tpl in theme/classic/templates/index.tpl, add {widget name="ps_imageslider"} after {block name='hook_home'}.
2. Go to homepage of your shop. Two widgets should be displayed.
3. Go to BO of your shop. Disabled  ps_imageslider module.
4. Go back to homepage of your shop. One widget will be displayed even if module is disabled.

#### Additional information

* PrestaShop version: 1.7.7

**Comment by florine2623** [comment]
Hi @Oksydan ,
Thanks for the report !
I did manage to reproduce the issue in PS 1.7.7.0.
I will add this to our debug roadmap. Thanks also for the PR.
