### ISSUE TITLE
Facetedsearch module, when I am on a category page, order of products configured in BO is not taken into account

### ISSUE THREAD

**Issue by Fredcor13** [PrestaShop/PrestaShop#20146]
#### Describe the bug

I'm on prestashop 1.7.6.4 and version 3.5.0 of faceted search module.

**First problem:**
when facetedsearch module is active, When I am on a category page, the order of the products configured in the back office in the category is not taken into account
When module is desactived all is right

**Second problem:**
when I m on a category page and When I try to filter products, it's spinning in the void, nothing happens.

**Comment by matks** [comment]
Hi @Fredcor13 

I cannot reproduce your 2 issues.

I checked a 1.7.6.4 shop with facetedsearch module v3.5.0 . When I am in a category page, it works fine for me. Order of products, when sorted "by relevance" is the one I have chosen in my BO page.

And I cant filter products without issues, no spinning in the void.

In BO page "Shop Parameters > Product Settings" you have modified no settings ?

Note that with "faceted search" v3.0.6 I had the issue (it's the default version embedded with v3.5.0). But upgrading to v3.5.0 fixed the issue.

Can you check again and provide clear steps about how to reproduce ?
```
<!--
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
-->

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
```

Also it would be better to create 2 issues for the 2 problems 😉  it will be easier to manage

**Comment by Fredcor13** [comment]
hi Matks,

thanks for your answer.

I know that in precedent version of the module that was this issue because I had it on another of my websites, and I immediately upgrade the module in last version 3.5.0 here, but.. I confirm that in my case i've always this issue after upgrade.
and I confirm that the module is the source of the problem because as soon as I deactivate it everything is ok.

In the In BO configuration page "Shop Parameters> Product Settings", I configured to display 50 products per page, displayed according to their position in the category. (see the capture here: <img width="1245" alt="Capture d’écran, le 2020-07-15 à 19 13 25" src="https://user-images.githubusercontent.com/68123661/87576063-1d48db80-c6d1-11ea-8e59-723c3ebc58f2.png">)


Regarding the configuration of the module itself here is the configuration that I have:
<img width="1455" alt="Capture d’écran, le 2020-07-15 à 19 29 13" src="https://user-images.githubusercontent.com/68123661/87576393-9c3e1400-c6d1-11ea-9abe-142b5c53c548.png">



To describe the problem here:

For example, in my category id 78:
https://afbat.demo-myod.fr/78-le-volet-bois
(acces restricted, I could give you login and password by private message)
In BO the order of product is the following:
<img width="1449" alt="Capture d’écran, le 2020-07-15 à 19 32 35" src="https://user-images.githubusercontent.com/68123661/87576838-4322b000-c6d2-11ea-85d9-698f55861d4b.png">

but in front order is not the same:
<img width="809" alt="Capture d’écran, le 2020-07-15 à 19 36 48" src="https://user-images.githubusercontent.com/68123661/87577028-8c72ff80-c6d2-11ea-8476-33588456b0ab.png">


and as soon as I deactivate the faceted filter module, in front, order of product is ok and respected
<img width="823" alt="Capture d’écran, le 2020-07-15 à 19 39 32" src="https://user-images.githubusercontent.com/68123661/87577276-ed9ad300-c6d2-11ea-9f0c-3f4cc1331103.png">



It would be easier if I give you some access to the BO no?
I can do this on private message if you want.

Regards.

Frédéric.

**Comment by khouloudbelguith** [comment]
Hi @Fredcor13,

This issue is fixed with this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/125 as reported here: https://github.com/PrestaShop/PrestaShop/issues/15062
Cold you please check this fix [comment:](https://github.com/PrestaShop/PrestaShop/issues/15062#issuecomment-604990175), it could solve your issue.

Thanks to check and feedback.

**Comment by sarahdib** [comment]
@Fredcor13 

This issue is a duplicate of #15062 

I close this issue since there is a fix available, feel free to open a new one if it's needed.

Thank you :)
