### ISSUE TITLE
Product Comments issue with PS 1.6

### ISSUE THREAD

**Issue by zekirdekorg** [PrestaShop/PrestaShop#20147]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.6
* PHP version: 7.3
screenshots:
https://ibb.co/pnLp1Qs 
english description of the error: 

"2 errors
Error removing module (file may be corrupt).
Product Comments Module failed to upgrade: Error while extracting final version. "

I also uploaded the files module/productcomments 

from https://github.com/PrestaShop/productcomments 

thanks

**Comment by matks** [comment]
Hi, I see multiple issues here:
- you say you are using PS 1.6 but PrestaShop 1.6 is no more supported => see http://build.prestashop.com/news/1.6.1.x-what-s-next/)
- PS 1.6 latest version is not compatible with php7.3 (unless you are using a customized version)
- I dont think module https://github.com/PrestaShop/productcomments is compatible with PS 1.6

Consequently I dont think we can help you as you are trying to use a module built for PS 1.7 with PS 1.6 which is old software.

I suggest upgrading to PS 1.7 😉
