### ISSUE TITLE
Dashboard activity loading issue

### ISSUE THREAD

**Issue by smithikakart** [PrestaShop/PrestaShop#20152]
prestashop versino 1.7.6.4 dashboard activity version 2.0.2 issue is once i enabled debug in the backoffice dashboard activity keep on loading only here i have attached the screenshot
<img width="283" alt="Screenshot 2020-07-12 at 4 13 00 PM" src="https://user-images.githubusercontent.com/67721911/87244398-9b4f7d00-c45a-11ea-8ff3-1c9ecf2348bd.png">

**Comment by matks** [comment]
Hi @smithikakart I dont have this issue when I install a new 1.7.6.4 shop.

Can you check if there are errors in the console ?

Something that could help would be infos like

host
server setup and configuration
PrestaShop version (source)
debug mode report
PHP error logs
apache error log
javascript console log
screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards

**Comment by S4hosting** [comment]
Console log : 

> A cookie associated with a cross-site resource at http://prestashop.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Php Error log : but this error not related to dashboard activity

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ProductCommentsPostCommentModuleFrontController::addCommentGrades() must be of the type array, boolean given, called in /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php on line 87 and defined in /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php:113
Stack trace:
#0 /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php(87): ProductCommentsPostCommentModuleFrontController->addCommentGrades(Object(PrestaShop\Module\ProductComment\Entity\ProductComment), false)
#1 /home/smithikakart/smithikamobiles.in/classes/controller/Controller.php(312): ProductCommentsPostCommentModuleFrontController->display()
#2 /home/smithikakart/smithikamobiles.in/classes/Dispatcher.php(515): ControllerCore->run()
#3 /home/smithikakart/smithikamobiles.in/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php on line 113

Server Error log : null

Server configuration : 

<img width="1094" alt="Screenshot 2020-07-13 at 7 43 57 PM" src="https://user-images.githubusercontent.com/67721911/87314673-36bb1d80-c541-11ea-83d7-235c154279da.png">

**Comment by khouloudbelguith** [comment]
Hi @smithikakart,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1PBsrI3eokkAx4qRfpZP7badISWlcHP8I/view?usp=sharing
What is the exact version of the `produtcomments` module did you use?
Did you try to re-install it, clear cache, check and feedback?

Thanks!

**Comment by S4hosting** [comment]
Here i have attached reproduce issue video

https://www.dropbox.com/s/r3axlv46iioiiv2/VIDEO-2020-07-14-19-07-41.mp4?dl=0

**Comment by khouloudbelguith** [comment]
@smithikakart, What is the exact version of the `produtcomments` module did you use?
Did you try to re-install it, clear cache, check and feedback?

Thanks!

**Comment by S4hosting** [comment]
see product comment i didn't try here i have asked about dashboard board activity issue for product comments let me try that solution tomorrow...

Product comments version is : V4.0.1

**Comment by khouloudbelguith** [comment]
@smithikakart, you have an error related to productcomments module
>PHP Fatal error: Uncaught TypeError: Argument 2 passed to ProductCommentsPostCommentModuleFrontController::addCommentGrades() must be of the type array, boolean given, called in /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php on line 87 and defined in /home/smithikakart/smithikamobiles.in/modules/productcomments/controllers/front/PostComment.php:113

This module is displayed in the dashboard activity
![image](https://user-images.githubusercontent.com/16067358/87441361-4e52de80-c5f3-11ea-8ea4-936e27b8673b.png)

Thanks!

**Comment by S4hosting** [comment]
as u like said its product comments module issue only i have removed that one but cant reinstall for prestashop 1.7.6.4 version can u help in that...

**Comment by SimonGrn** [comment]
Hello,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support
Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/
