### ISSUE TITLE
Carriers duplicated in database after upgrade 1.7.6.5 -> 1.7.6.7

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#20151]
Hi, 

since PS version 1.7.6.5 I get double order notifications for the same order:

![image](https://user-images.githubusercontent.com/44971218/87228316-b362c600-c3a0-11ea-8b9c-41b1381de6e9.png)

* PrestaShop version: 1.7.6.5 to 1.7.6.7
* PHP version: 7.2.24

**Comment by matks** [comment]
Hi @didi-2018 is it happening only for this order or for all orders ? I am especially wondering if it does this for orders created before the upgrade and for orders created after the upgrade

**Comment by didi-2018** [comment]
@matks Hi! It happens for all orders. I found out that all carriers were twice in the database with the same ID. I removed all duplicates and now it is working. I get only 1 notification for 1 order.

**Comment by matks** [comment]
> @matks Hi! It happens for all orders. I found out that all carriers were twice in the database with the same ID. I removed all duplicates and now it is working. I get only 1 notification for 1 order.

Ok, that's nice to know you found the issue.
But

> I found out that all carriers were twice in the database with the same ID.

It's scary 😱  . Very strange, I dont see how an upgrade could duplicate stuff 🤔  .

I close the issue as it seems closed. have a nice day !
