### ISSUE TITLE
Issue after upgrading 1.7.6.5 to 1.7.6.7 in Back Office

### ISSUE THREAD

**Issue by krupers** [PrestaShop/PrestaShop#20150]
Hello,
I just installed (thank God on dev store) 1.7.6.7 version precisely file by file verify what I modified and what not, but if FO is okay and everything is working, my BO is totally in chaos:
- User profile is rolled over, all dropdown lists are like a list of elements one below another
- Modules list has issue is style "class="module-item module-item-list col-md-12module-item-list-isNotActive" (missing space between "12" and "module"
- Products are on grey background and tabs are like not working

I just clicked after upgrade like always to empty cache, to clean all the data - nothing is working.

**Comment by matks** [comment]
Hi,

> I just installed (thank God on dev store) 1.7.6.7 version precisely file by file verify

Do you mean you did not use the auto-upgrade module ?

What you describe looks like CSS/JS issue, possibly from cache. Any error in the console when browsing the pages ?

**Comment by krupers** [comment]
No, I just did the auto-upgrade, as usual :)
Just verified before upgrade all list of modified files to be sure that any of my modification get lost.
Even have log list if you want to see it.

Nothing is like really CSS/JS scripts, but I did the clean :/


Everything I have (only marked some details):

Screens are:
- modules issue
- products issue
- clients issue
- client edit issue
- product tab
- modules tab in product
- console log

![modules](https://user-images.githubusercontent.com/9113275/87225537-231b8580-c38e-11ea-9738-b0f93c8a26b7.PNG)
![products](https://user-images.githubusercontent.com/9113275/87225591-96bd9280-c38e-11ea-97e1-3f3208d7f0ce.PNG)
![modules](https://user-images.githubusercontent.com/9113275/87225540-2747a300-c38e-11ea-8e71-ecfc35074c86.PNG)
![clients](https://user-images.githubusercontent.com/9113275/87225541-2878d000-c38e-11ea-84da-a2d40947fdce.PNG)
![edit_client](https://user-images.githubusercontent.com/9113275/87225543-2a429380-c38e-11ea-9787-908c1afda2d6.PNG)
![product_tab](https://user-images.githubusercontent.com/9113275/87225544-2c0c5700-c38e-11ea-88b5-b0287096370c.PNG)
![modules_tabs](https://user-images.githubusercontent.com/9113275/87225546-2dd61a80-c38e-11ea-8f19-10ed5b1d9f9e.PNG)
![console](https://user-images.githubusercontent.com/9113275/87225548-2f9fde00-c38e-11ea-83a6-cc991639b888.png)

**Comment by PululuK** [comment]
Hi @krupers 

Can you check your php compatibility please : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by krupers** [comment]
Oh gosh... You are amazing, I forgot about it.
Od production site I have 7.2.31 - on dev I just switched unintentionally to 7.4.7....
Now everything is working I think!

Thank you!!!
