### ISSUE TITLE
Orders Bug - Missing Creation - PS 1.6

### ISSUE THREAD

**Issue by Detertecnic** [PrestaShop/PrestaShop#20158]
#### Missing Order Creation

Sometimes happens that orders are not created and they go into cart abandoned (or sometimes they disappear from my back office). In the beginning, I found this bug only with customers using Gestpay (axerve), but last week it happened with Paypal. Gestpay already did all verifications and they did not find any bug in their system. They also said that it could be due to order discount, but I checked, and it wasn't. Is there anyone who found the same problem? Do you have any solution?

#### Additional information

* PrestaShop version: 1.6.1.4
* PHP version:

**Comment by matks** [comment]
Hi, I'm sorry but PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope, for critical issues only.

We cannot help you as this software is too old, so I close this issue 😞  .
