### ISSUE TITLE
Al actualizar productos o algún módulo no se refleja el cambio en el Backoffice 

### ISSUE THREAD

**Issue by pepevazquez** [PrestaShop/PrestaShop#20172]
Cuando intento actualizar cualquier producto o algún módulo el cambio no se ve reflejado en el Administrador pero si en el Front, y eso me esta complicando mucho para administrar el sitio.

El día de ayer 13 de Junio de un momento a otro se resolvió el problema pero no entiendo de que manera, si no hice absolutamente nada, solo deje inactivo el sitio por 2 horas y cuando inicie sesión de nuevo encontre resuelto eso.
Pero hoy 14 de Junio comencé a trabajar de nuevo y presento los mismos problemas.

Tengo actualmente la versión 1.7.6.1 y lo configuré Multitienda.

**Comment by arouiadib** [comment]
> Thanks for opening this issue! We will help you to keep its state consistent

@prestashop-issue-bot

You are sending a mail to everyone subscribed to the repository, whenever someone opens an issue.  Then number of useless mails per day:

Number of opened issues * Number of subscribed people . On Average ~1000 mails per day  that do not serve a vital purpose IMO



Thanks

**Comment by matks** [comment]
> > Thanks for opening this issue! We will help you to keep its state consistent
> 
> @prestashop-issue-bot
> 
> You are sending a mail to everyone subscribed to the repository, whenever someone opens an issue. Then number of useless mails per day:
> 
> Number of opened issues * Number of subscribed people . On Average ~1000 mails per day that do not serve a vital purpose IMO
> 
> Thanks

Thank you for this feedback. We think you are right 😄  we will remove this welcome message from the bot
