### ISSUE TITLE
BO - Adresses page - Incorrect behavior after creating a new address with an invalid field Address1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20170]
#### Describe the bug

In the BO => Addresses page, when we try to create a new address with invalid field Address1 (too long > 128 chars), there is a redirection to the Address list page with an unclear alert
![image](https://user-images.githubusercontent.com/16067358/87413035-0cfa0900-c5ca-11ea-9db0-221356611396.png)

#### Expected behavior

After clicking save => no redirection to the Address list page and display a clear alert as the PS1.7.6
![image](https://user-images.githubusercontent.com/16067358/87413138-32871280-c5ca-11ea-8328-e1bd4ff858ed.png)

#### Steps to Reproduce

1. Go to the BO => Addresses page
2. Create a new address
3. Set an invalid field Address 1 ( too long > 128 chars )
4. Click save
5. See error

**Screenshots**

https://drive.google.com/file/d/1uz469CCWwT5tAuPAaS0qqDrTZ7WKbtvV/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x, 1770beta1
* PHP version: 7.1

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/20263/

**Comment by khouloudbelguith** [comment]
The redirection issue is fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/20263

**Comment by matks** [comment]
I noticed the same issue happens in "edit an address" usecase. I reopen this issue and I do the PR immediately https://github.com/PrestaShop/PrestaShop/pull/20303

**Comment by Progi1984** [comment]
Fixed  by #20303
