### ISSUE TITLE
Explore upgrade capabilities of Softaculous

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#20177]
#### Describe the bug

Following the issue #20079, we're exploring the update process of softaculous to better understand how that bug can happen.

**Update:** I've reach softaculous to ask them to have a look at their upgrade tool. I'll update this issue when I'll get more information from their side.

**Comment by marionf** [comment]
Any news @atomiix ?

**Comment by atomiix** [comment]
@marionf nope 😕

**Comment by matks** [comment]
@atomiix I think we can close this issue?

**Comment by atomiix** [comment]
Yep
