### ISSUE TITLE
Problem with backend on 1.7.6.0

### ISSUE THREAD

**Issue by Webmasterciccio** [PrestaShop/PrestaShop#20175]
Good evening, I just installed prestashop on the hosting "dominiofaidate.it" when I try to enter the modules or in the "Shop parameters" or "Advanced parameters" a white page appears with the word "Access denied"
What can I do?
Thanks for your help

**Comment by Webmasterciccio** [comment]
![Immagine](https://user-images.githubusercontent.com/68300801/87470702-70615680-c61d-11ea-995b-4f7c4c006ed3.png)

**Comment by prestascott** [comment]
Dear @Webmasterciccio,

Thanks for your issue. 
Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 
Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Webgaict** [comment]
Hi, I had the same problem, I have not installed any template on the platform there is only the default one. I need a solution as soon as possible. The version of the php I use is 7.3

**Comment by SimonGrn** [comment]
PrestaShop 1.7.6.0 version is only compatible with PHP 7.2 maximum. Check the [compatibility here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support
Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/
