### ISSUE TITLE
Sql error on autoupgrade on ps_condition table

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#20179]
#### Describe the bug

When migrating from ps 1.7.6 to 1.7.7 beta 1 there are sql errors on ps_condition table if gamification module is not installed.

#### Additional information

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.1

**Comment by prestascott** [comment]
Hi @jf-viguier, thanks for your report.

Could you please provide us with more info?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots

Thank you :)

**Comment by PierreRambaud** [comment]
@jf-viguier What do you mean by migrating data?

**Comment by jf-viguier** [comment]
@PierreRambaud I mean upgrading from 1.7.6 to 1.7.7 with autoupgrade module.

**Comment by SimonGrn** [comment]
What is the exact version you started from ?

**Comment by jf-viguier** [comment]
version 1.7.6.7

**Comment by sarahdib** [comment]
Hello @jf-viguier 

I was able to reproduce the issue.

Step to reproduce : 
1. upgrade prestashop 1.7.6.x to 1.7.7.0 without the module gamification 
2. see the error 
<img width="985" alt="Capture d’écran 2020-07-16 à 11 22 46" src="https://user-images.githubusercontent.com/3034677/87654822-bc181b00-c757-11ea-8a18-ec5533d866dc.png">


I think this table is related to gamification only, there is no impact on the shop upgraded

Thank you!

**Comment by jf-viguier** [comment]
That's it, thanks @sarahdib 
We always unistall the gamification module because it slow down prestashop.

**Comment by ksaandev** [comment]
I uninstall gamification too 😁

**Comment by Progi1984** [comment]
Fixed by #20192
