### ISSUE TITLE
Sort order (Price: Low to high) as default. But how? Prestashop 1.7.6

### ISSUE THREAD

**Issue by PrestaQuestion** [PrestaShop/PrestaShop#20189]
Hi,

Like the title says, can someone help me out to change the default sort by in the code. Prestashop 1.7.6.
I tried everything but nothing works. The pagination doesnt work either in my prestashop backoffice.
So changes in the code is my only option.

Thanks!

**Comment by florine2623** [comment]
Hi @PrestaQuestion ,
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
- version of faceted search module
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by PrestaQuestion** [comment]
Hi,

I shared a screenshot: [Screenshot](https://snipboard.io/Z7Stdx.jpg)

Like you can see it is Prestashop 1.7.6.2. In the screenshot you can see that i setup the pagnitation on productprice Low to High.

But in the front nothing is changing.

I also shared the module Faceted search module and the options i selected there.

In the bug mode report i can't find nothing that brings me to a solution for this problem.

Thanks for the time.

**Comment by florine2623** [comment]
Hi @PrestaQuestion ,
I can't reproduce your issue on my shop. I am using PS 1.7.6.5. I am also using classic theme.
The issue probably comes from your theme. Can you try to put classic theme and see if the behavior changes ?

**Comment by PrestaQuestion** [comment]
Hi,

Thanks for your reply. You are right! The classic theme it is good. But i use a theme that i bought.

Where does it lie?

**Comment by PrestaQuestion** [comment]
Hi, i found it.

Thanks for the time, the new theme had a filter installed. In the code i changed it.

Tip: If you have this problem, search for the filter that is used in the theme. Enable only 1 filter. The filter of the backoffice wasn't working because of the enabled filter of the new theme.
