### ISSUE TITLE
Contact form - don't receive emails

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#20191]
Hello,

My contact us form stopped to send emails, I can see messages only in the BO > Customer service.
I'm using PHP's mail and receive orders emails.

I'm expecting to receive also an email when user submit the contact us form.

1. Click on Contact Us
2. Submit the form
3. Your message has been successfully sent to our team.
4. No email received but message is shown in the customer service in BO

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @edensh89 ,
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email.

The information for the fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks!

**Comment by Hlavtox** [comment]
@edensh89 Go to module config and check if sending is enabled ;-) I spent a long time searching for the cause, then I found out it's disabled by default 🤦

https://github.com/PrestaShop/PrestaShop/issues/16689

**Comment by edensh89** [comment]
@Hlavtox Thanks but which module?

**Comment by Hlavtox** [comment]
@edensh89 Contact Form module, there is a special module installed for that

**Comment by edensh89** [comment]
@Hlavtox Seems like I don't have it installed.

**Comment by Hlavtox** [comment]
@edensh89 If you go to module manager and put **contactform** into search box, it finds nothing?

**Comment by edensh89** [comment]
@Hlavtox Ok, I found the issue.
The recaptcha module cause issues and contact form wasn't shown correctly, I did uninstall to the recaptcha module and now everything seems to work good.

Thank you very much!

**Comment by SimonGrn** [comment]
Thanks @Hlavtox for your help :pray:
