### ISSUE TITLE
BO - Error 500 - Too few arguments to function PrestaShopBundle\EventListener\BackUrlRedirectResponseListener::__construct()

### ISSUE THREAD

**Issue by Cryptex1030** [PrestaShop/PrestaShop#20197]
#### Describe the bug

90% of the BO content is no longer accessible. All pages show the same error 500.

#### Expected behavior

:)

#### What's the actual result?

> FatalThrowableError
> 
> Type error: Too few arguments to function PrestaShopBundle\EventListener\BackUrlRedirectResponseListener::__construct(), 1 passed in /home/clients/97df990520e096c0f62aa56c78bb3a07/web/var/cache/dev/Container7kfjuti/appDevDebugProjectContainer.php on line 2042 and exactly 2 expected

#### Steps to Reproduce

Don't know how. Nothing has changed on the store for several weeks.

But, I found a temporary solution, or less I found where the problem comes from.

**In /src/PrestaShopBundle/EventListener/BackUrlRedirectResponseListener.php**

    /**
     * @param BackUrlProvider $backUrlProvider
     */
    public function __construct(
        BackUrlProvider $backUrlProvider
        // LegacyContext $legacyContext
   ) {
        $this->backUrlProvider = $backUrlProvider;
        // $context = $legacyContext->getContext();
        // if (null !== $context && $context->employee instanceof Employee) {
            // $this->employeeId = $context->employee->id;
        // }
    }

By removing these lines, no more problems. I know this is not a solution but I don't know where the problem comes from.

**Screenshots**

Error when I go to Module list page :
![2020-07-15 18_05_59-Window](https://user-images.githubusercontent.com/52559716/87684186-3c537600-c782-11ea-91aa-21f5d9144ff5.jpg)

PrestaShop Information :
![2020-07-16 16_23_11-Window](https://user-images.githubusercontent.com/52559716/87684228-4aa19200-c782-11ea-8560-b928d531569c.png)

#### Additional information

- PrestaShop 1.7.6.3
- PHP 7.1
- Apache 2.2.34

**Comment by florine2623** [comment]
Hi @Cryptex1030 ,
Can you delete you cache ? in var/cache/dev and var/cache/prod
Did you install a theme / module ? or try to do a migration before the error happened ?
Thanks!

**Comment by Cryptex1030** [comment]
Sorry, I forgot to specify. The cache was manually deleted, as well as in /var/cache/ also.

I installed the store directly with its theme, I also implemented several modules, everything has been working fine for several months. This problem appeared suddenly.

No migration, directly installed in 1.7.6.3 and never updated.

Edit : Little mistake, I'm on 1.7.6.**3**

**Comment by florine2623** [comment]
I can't reproduce the issue in my test shop.
Did you implement any overrides ?
Can you send me the log file please ?

**Comment by Cryptex1030** [comment]
I have not done any override, but maybe there is in the theme.

Of course, which one do you want?

**Comment by florine2623** [comment]
In /var/logs -> exception.log / prod.log / dev.log

**Comment by Cryptex1030** [comment]
I send you Github invitation

**Comment by florine2623** [comment]
Thanks for the invitation. You have a lot of Fatal error, could you send me a screenshot of the bottom page of the modified files, there are probably some files missing. BO > Advanced Parameters > Informations

**Comment by Cryptex1030** [comment]
![2020-07-17 15_34_42-Informations • TafitNutri](https://user-images.githubusercontent.com/52559716/87791741-1641da80-c843-11ea-8463-98f27d7218e8.png)

**Comment by SimonGrn** [comment]
It looks like a lot of files were modified.
Did you change something in your environment ?
We only use Github for issues and problems related to the software, and it looks that your issue is related to your environment.

**Comment by SimonGrn** [comment]
Hello @Cryptex1030 ,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
This issue is about your own environment. Try to find why you have so much modified files.
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/).

Thank you
