### ISSUE TITLE
Blocklayered is very slow with many products in category

### ISSUE THREAD

**Issue by ihor-sviziev** [PrestaShop/PrestaShop#202]
Hi all. I have ~10000 products in one category, i was added blocklayered for filter by attributes, but after i was clicked on attribute, i have waiting ~60 seconts. I was refactored this block module. I was tested it at prestashop 1.4.9. Please see https://github.com/igor-svizev/prestashop-blocklayered/ , test it with other versions and merge into main branch of prestashop.
PS: I haven't time for make pull request.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
