### ISSUE TITLE
Options that can't be changed via ini_set()

### ISSUE THREAD

**Issue by KsaR99** [PrestaShop/PrestaShop#20206]
#### Describe the bug

PHP ini settings: `realpath_cache_size` and `realpath_cache_ttl` can only be changed via `php.ini` file or `httpd.conf` but not via `ini_set()`.
Because these options has mode "PHP_INI_SYSTEM"

[These options in php manual](https://www.php.net/manual/en/ini.core.php#ini.sect.performance)
> **Changeable** PHP_INI_SYSTEM

[More about PHP_INI_SYSTEM](https://www.php.net/manual/en/configuration.changes.modes.php)
> PHP_INI_SYSTEM Entry can be set in php.ini or httpd.conf

#### Expected behavior
N/A
#### Steps to Reproduce

```php
if (ini_set('realpath_cache_size', '1M') === false) {
    echo 'Cannot set "realpath_cache_size" ini option', PHP_EOL;
}
if (ini_set('realpath_cache_ttl', '300') === false) {
    echo 'Cannot set "realpath_cache_ttl" ini option';
}
```

**Screenshots**
![1](https://user-images.githubusercontent.com/7098217/87776406-04067300-c828-11ea-8bd0-8e3da6bb4904.png)
![2](https://user-images.githubusercontent.com/7098217/87776410-0537a000-c828-11ea-84c2-8549484795e5.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
* File where bug occured: https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/classes/Windows.php#L35-L36

**Comment by florine2623** [comment]
Hi @KsaR99 ,
Could you follow the bug or improvement template so we can help you ?
Please explain exactly what you want or what the problem is.
Thanks!

**Comment by KsaR99** [comment]
@florine2623 I've edited issue with template.

**Comment by SimonGrn** [comment]
Hello @KsaR99,
what exactly is the problem ? Are you saying that the lines 
https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/classes/Windows.php#L35-L36
are useless and are not working on Windows ?
Please explain.
Thank you.

**Comment by KsaR99** [comment]
> what exactly is the problem ? Are you saying that the lines
> https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/classes/Windows.php#L35-L36
> 
> 
> are useless and are not working on Windows ?

Yeah, that what I mean i.e. it looks like dead-code (The code doesn't change ini values at all).

**Comment by SimonGrn** [comment]
@KsaR99 Thank you for your answer. We will take a look.
@PierreRambaud do you know if this code is ever executed on Windows ?

**Comment by ksaandev** [comment]
Hi, I remember having trouble with `ini_set()` on some server configurations. Cannot remember exactly what was the issue, but basically some environments do not let you modify some of php.ini settings. In my case I could not modify request timeout.

So maybe it's not all windows environments, only yours

**Comment by PierreRambaud** [comment]
@SimonGrn This code is always executed on windows. Even if we are not supporting IIS, we support Windows for local environment.
I create a pull request to remove these calls

**Comment by SimonGrn** [comment]
> @SimonGrn This code is always executed on windows. Even if we are not supporting IIS, we support Windows for local environment.
> I create a pull request to remove these calls

My bad, it _is_ executed, it's just useless and doesn't have any impact.
Thanks for your input.
