### ISSUE TITLE
Backoffice system information take huge time to load

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#20202]
In back office system information takes minutes to load

all prestashop version in my store got this problem, is not a bug problem but it is

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Gipielle ,
Do you have an error in the console or in your log file ?
Can you check if all system requirements are met ?
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by Gipielle** [comment]
Hi, thanks for the replay:

Console i got this:

Questa pagina utilizza la proprietà non standard “zoom”. Al suo posto è possibile utilizzare calc(), oppure  “transform” insieme a “transform-origin: 0 0”. index.php
Caricamento non riuscito per lo <script> con sorgente “https://www.betafer.it/modules/ps_googleanalytics/views/js/GoogleAnalyticActionLib.js”.

System requirements are ok, i can also report that phppsinfo.php works 1 on 10

**Comment by florine2623** [comment]
i can also report that phppsinfo.php works 1 on 10 : sorry i don't understand what you are trying to say

**Comment by Gipielle** [comment]
This, https://github.com/PrestaShop/php-ps-info, now i have removed the password id it works so i made a screenshot

<img width="1779" alt="Schermata 2020-07-17 alle 17 57 49" src="https://user-images.githubusercontent.com/53569015/87806408-1f3ca700-c857-11ea-9cf5-8d232ffe2f69.png">
<img width="1910" alt="Schermata 2020-07-17 alle 17 58 00" src="https://user-images.githubusercontent.com/53569015/87806398-1ba92000-c857-11ea-9ee4-daf317c8ed45.png">

**Comment by matks** [comment]
Hi, I am sorry but "it's very long to load" is not something we can work with 🤔 . It depends on shop database size, on server capabilities, on specific settings ... too many variables you can adjust and modify.

Boosting your shop performances is an area with multiple paths. Can be database config fine-tuning, can be server I/O fine-tuning ... basically on our test shops there's nothing noticeable.

I close this issue as we cannot fix something that we cannot work on.

This does not mean this discussion is over 😉 if you find some more accurate informations (something you can describe with https://github.com/PrestaShop/PrestaShop/issues/new?template=1_bug_report.md) we might understand what's going on and maybe reopen the issue if we find a way to reproduce your behavior. But "open" issues are "things that we know what need to do / what we need to fix" and this issue does not meet this definition
