### ISSUE TITLE
Cart parameter hook DisplayAdminOrder

### ISSUE THREAD

**Issue by jrpp18** [PrestaShop/PrestaShop#20208]
#### Describe the bug

Cart object parameter in hookDisplayAdminOrder is uninitialized. It is there, as parameter received, but with all fields as null.

#### Expected behavior

Receive cart object initialized or remove it as a parameter.

#### Steps to Reproduce

1. Dump in a module all parameters in displayAdminOrder hook.
2. go to any order admin page.
4. See parameter with key 'Cart' dumped

**Screenshots**

![image](https://user-images.githubusercontent.com/1701545/87778033-d53dcc00-c82a-11ea-9d5e-8520cc3244ff.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2.8

**Comment by florine2623** [comment]
Hi @jrpp18 
Thanks for the report, I will ping our developer team so they can answer you more precisely
Please stay tuned!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
When dumping all parameters in displayAdminOrder hook, Cart information is null. Is that the normal behavior ?
Thanks!

**Comment by matks** [comment]
Hi @jrpp18 I dont understand why there should be a "Cart" object on a BO page which manages Orders.

"Cart" object only makes sense on FO pages, where customer has a "Cart" object that contains the items he has put in his cart, and will (hopefully) checkout.

There is no such a thing as a "Cart" on BO pages where you are logged in as an Employee. If there was a Cart object on the legacy page, it looks like it was a nonsense to me 🤔 

EDIT: we could even completely remove the Cart object on BO pages 😅  actually

**Comment by khouloudbelguith** [comment]
Hi @jrpp18,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
