### ISSUE TITLE
BO - Orders page - Strange behavior after editing the country

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20217]
#### Describe the bug

In the BO => Orders => New Order page, it is impossible to edit the country of an address.
When we try to change the country and save, all the addresses do not appear anymore 

#### Expected behavior

The address should be updated

#### Steps to Reproduce

1. Go to BO => Orders 
2. Click on "Add new Order"
3. Create a new customer or choose an old one for example `pub@prestashop.com`
4. add a product to cart
5. try to edit the address (Delivery OR Invoice)
6. change the country
7. save
8. see the error, the block address is empty, there is no more addresses displayed
9. if you try to create a new order for this customer, all previous addresses are not displayed

**Screenshots**

https://drive.google.com/file/d/1uKSvz3VRz2NiTRPOkfN9X7vXN4KB_jV8/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x, develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20284
