### ISSUE TITLE
Sub categories thumbnails not visible in main menu module

### ISSUE THREAD

**Issue by Verlonimo** [PrestaShop/PrestaShop#20219]
Hi,

#### Bug

Adding thumbnails to subcategories or categories which have no sub categories, thumbnails are not visible.

#### Expected behavior

Thumbnails should be visible on all categories where thumbnails are uploaded.

#### Steps to Reproduce

A.

1. Create category with no subcategories
2. Upload menu thumbnail
3. Thumbnail not visible

B.

1. Create category with subcategories
2. Upload menu thumbnail to subcategory
3. Thumbnail of that subcategory is not visible

#### Possible quick fix

Uncomment 746 line in ps_mainmenu.php

`if (isset($category['children']) && !empty($category['children'])) {`

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by sarahdib** [comment]
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Add in the native template a miniature for subcategory in the menu.

Thank you!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_mainmenu#36
