### ISSUE TITLE
Upgrade issue - errorThrown jqXHR - 1.7.6.2 to 1.7.6.7

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#20214]
#### Describe the bug
I try to upgrade my PS 1.7.6.2 to PS 1.7.6.7 with differents methods (from archive, locally ) but nothing works

![image](https://user-images.githubusercontent.com/11594433/87794504-a0d40b00-c83e-11ea-906e-af1c3a7ee3cf.png)

[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " "

1. Go to 'Module upgrade'
2. Click on 'upgrade now'

**Screenshots**

#### Additional information

Informations sur votre serveur Linux #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.32

Limite de mémoire : 6028M

Temps maximal d'exécution : 30000

Taille max. pour envoi de fichiers : 800M

**Comment by florine2623** [comment]
Hi @go-sudo ,

What do you mean "nothing works" ?
Do you have an error ? If yes, please specify

I did the upgrade from 1.7.6.2 to 1.7.6.7 :
![Capture d’écran 2020-07-17 à 16 46 30](https://user-images.githubusercontent.com/16019289/87799188-3a0a1e00-c84d-11ea-814f-cb834a91a86b.png)
![Capture d’écran 2020-07-17 à 17 11 55](https://user-images.githubusercontent.com/16019289/87801850-a3d7f700-c850-11ea-9020-7a22614cf10c.png)

My upgrade was successful

**Comment by go-sudo** [comment]
Hello @florine2623 
Yes I have this error [Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " "

regards

**Comment by florine2623** [comment]
Can you send me your log file ?
admin/autoupgrade/tmp/log.txt

**Comment by go-sudo** [comment]
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4965353/log.txt)
Hi @florine2623 

here the file of the 2 websites 

https://drive.google.com/file/d/1sfiVeHk4T6wjNXY5aW2HYYyQlskHoWAw/view?usp=sharing

**Comment by go-sudo** [comment]
Hi @florine2623 

you can find it here https://techpc.ma/log.txt
the file is too big
Regards

**Comment by florine2623** [comment]
Can you zip it and send the zip file ?

**Comment by go-sudo** [comment]
Hi @florine2623 
https://drive.google.com/file/d/1TNck2tQPOAIkRPl6Yfue88rXdYLs-QjR/view?usp=sharing
[log _teck.zip](https://github.com/PrestaShop/PrestaShop/files/4965873/log._teck.zip)

**Comment by florine2623** [comment]
Thanks!
What is the repercussion of the error on your shop ?

**Comment by go-sudo** [comment]
Hi @florine2623 
You are welcome , there is no error all works fine but I can't update to the last version as I said with the differents methods 
with folder latest also from archive it gives same thing same error

Regards

**Comment by florine2623** [comment]
What version of module autoupgrade are you using ?
I'm using 4.10.1 and I haven't had errors.

**Comment by go-sudo** [comment]
Hi @florine2623 
I'm using v4.10.1 - par PrestaShop
![image](https://user-images.githubusercontent.com/11594433/88435093-71526f00-cdf9-11ea-979d-ad098d95b64f.png)

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

As can I see in your log file, the upgrade is stopped in the Backup step.
Could you please try to disable the "Back up my images" option, save and check again.
![image](https://user-images.githubusercontent.com/16067358/88549353-7a715500-d020-11ea-86df-b2373e24c86a.png)

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith and Welcome Back !!

It works finally, you saved my day , you are the best
thank you 

1.7.6.7

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, Great!
Feel free to open a new one when needed.

Thanks!
