### ISSUE TITLE
Provide generic CSP headers for a fresh installation

### ISSUE THREAD

**Issue by thepixelabs** [PrestaShop/PrestaShop#20229]
#### Describe the bug

I am adding a content security policy header for my web server to restrict XSS vulnerabilities, I do this in "REPORT-ONLY" mode to avoid site breakup.
It seems like even when using the classic theme, i am getting CSP error reports.
Other third party module errors I received were removed by disabling those affected modules.
This forces using unsafe-inline and unsafe-eval in a very problematic CSP policy "script-src"
#### Expected behavior

Using default modules such as the cart shouldn't produce CSP errors in console.
The bottom.js file generated includes a comment that throws CSP errors, is this a false positive? Using report services for such logs is a common practice for security, this would just throw many errors that would need to be filtered.

#### Steps to Reproduce

1. Add a header to the web server such as in the case of nginx - 
` add-header Content-Security-Policy-Report-Only "default-src 'self'; script-src 'self'; connect-src 'self' https://www.google-analytics.com; img-src 'self' data:; style-src 'self';base-uri shop.address.com;form-action 'self';frame-ancestors 'self'; font-src 'self' https://fonts.gstatic.com" always;`

**Screenshots**

![image](https://user-images.githubusercontent.com/4767242/87871444-fa604500-c9b8-11ea-95e1-4b49270b5d7d.png)

bottom-js
![image](https://user-images.githubusercontent.com/4767242/87871438-df8dd080-c9b8-11ea-8320-d75ee4ac8acc.png)

cart js
![image](https://user-images.githubusercontent.com/4767242/87871490-588d2800-c9b9-11ea-843e-2ce651e88bd9.png)

![image](https://user-images.githubusercontent.com/4767242/87871457-1bc13100-c9b9-11ea-9ad0-7d66d78347c4.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* NGINX 1.16.1

Using google analytics while enabling CSP is currently a problem. Generating server nonces automatically per request is not an option, prestashop currently doesn't support that.
Is there a solution for this?
It opens up a world of vulnerabilities, and these are out of the box files for all i know.

**Comment by thepixelabs** [comment]
Hi, this is an important security topic. Would love to get a response, it can currently open up a world of vulnerabilities due to unsafe content security policy.

**Comment by sarahdib** [comment]
@PierreRambaud  could you check this issue :) 

Thank you

**Comment by matks** [comment]
> Hi, this is an important security topic. Would love to get a response, it can currently open up a world of vulnerabilities due to unsafe content security policy.

Hi, please wait 😄  the answer will come but our hands are quite full right now but don't worry these are just warnings, there is nothing dangerous there. It's just a tool that tells you to follow a best practice, nothing more.

**Comment by thepixelabs** [comment]
> > Hi, this is an important security topic. Would love to get a response, it can currently open up a world of vulnerabilities due to unsafe content security policy.
> 
> Hi, please wait 😄 the answer will come but our hands are quite full right now but don't worry these are just warnings, there is nothing dangerous there. It's just a tool that tells you to follow a best practice, nothing more.

This is not "just a tool", if i enable policy to allow scripts to only be executed from self and known addresses, i can block more attack surface.

Currently i have to allow "unsafe-inline" and "unsafe-eval". While the latter is optional AND really just an error, the first one causes site functionality problems when not enabled, the whole shopping cart functionality is out the window. Thus i have to enable "unsafe-inline" under the script-src definition which is a very bad practice if you use CSP.

![image](https://user-images.githubusercontent.com/4767242/88033918-9ff5ee80-cb48-11ea-845b-b3c6e6a13494.png)

**Comment by PierreRambaud** [comment]
I confirm using `unsafe-inline` and `unsafe-eval` is bad practice, but regarding what you're trying to do, you must add all hashes in your header configuration as you see on this screenshot.
![image](https://user-images.githubusercontent.com/1462701/88180084-1e2bc100-cc2d-11ea-83ca-17b4a379dd56.png)

It's the same for your first message when a script is requesting googletagmanager.com, you must add this line too.

**Comment by thepixelabs** [comment]
@PierreRambaud When allowing googletagmanager.com I allow a specific address, I know of approving hashes but if it was 1 or 2 elements on the front page or others, ok. However I cant allow that specific hash because the cart module at the top generates a different hash per page, though it is the same element.

I dont have that issue on the backoffice as i have excluded my specific ip from that.

**Comment by PierreRambaud** [comment]
@pixelicous This is because PrestaShop includes many (many many) javascript directly in the template instead of using only scripts, same for stylesheets. It's because of modules and legacy parts. If you're going to use CSP, you have two choices:
 - add all hashes you found
 - accept unsafe inline and eval.

**Comment by PierreRambaud** [comment]
But FYI, I will work as soon as possible on a generic CSP configuration for a fresh PrestaShop installation. :wink:

**Comment by thepixelabs** [comment]
@PierreRambaud Thanks for your reply. I actually don't remember observing any errors besides these two.
I'm not using any modules that trigger any problems, forcing me to use unsafe-inline and unsafe-eval.

The two errors i observe are generated from the same files everytime. while one of them is even flagging due to some text in a comment.

Anyhow I think integration of the default module cart would benefit from this change. Afterall there are far more complicated modules and files that get imported into the workspace that do not trigger this.

On my hand I'm still left with these unsecure strings, but i guess it will have to do for now.
I'll keep the comment open for you to decide whether you want to track this or close.

**Comment by PierreRambaud** [comment]
@pixelicous We will keep this issue open, and will do our best to provide a standard CSP configuration :)

**Comment by thepixelabs** [comment]
@PierreRambaud If you mean you will sort the javacsript inline issues that's great, but otherwise, the CSP configuration by itself isn't the issue here.

Thanks for the support!

**Comment by PierreRambaud** [comment]
@pixelicous The CSP configuration in your example isn't complete, this is why you have many reports in your browser. :thinking:

**Comment by thepixelabs** [comment]
@PierreRambaud Alright, waiting for a standard config :)

**Comment by PierreRambaud** [comment]
We plan to implement #12970 with a part about the CSP configuration.
I'm closing this one, feel free to follow the other issue, I will do my best to discuss about configuration as soon as possible.
