### ISSUE TITLE
Deprecated using function array_key_exists(); With objects PHP7.4

### ISSUE THREAD

**Issue by Trackhe** [PrestaShop/PrestaShop#20228]
#### Describe the bug

array_key_exists(); using with objects is now Deprecated in PHP7.4 and it want be removed at PHP8
Use isset() or property_exists() instead in
/var/www/html/dev/src/Adapter/EntityMapper.php
on line 99

i tried to patch it with 

```
$entity->id = (int) $id;
    foreach ($object_datas as $key => $value) {
        if (array_key_exists($key, $entity_defs['fields'])
        || array_key_exists($key, $entity)) {
            $entity->{$key} = $value;
        } else {
            unset($object_datas[$key]);
        }
}
```

to

```
$entity->id = (int) $id;
    foreach ($object_datas as $key => $value) {
        if (array_key_exists($key, $entity_defs['fields'])
        || property_exists($entity, $key))  {
            $entity->{$key} = $value;
        } else {
            unset($object_datas[$key]);
        }
}
```

But it give me an error.

`
Fatal error: Uncaught Error: Cannot access protected property Shop::$id_shop in /var/www/html/dev/src/Adapter/EntityMapper.php:100 Stack trace: #0 /var/www/html/dev/classes/ObjectModel.php(264): PrestaShop\PrestaShop\Adapter\EntityMapper->load() #1 /var/www/html/dev/classes/shop/Shop.php(128): ObjectModelCore->__construct() #2 /var/www/html/dev/classes/shop/Shop.php(411): ShopCore->__construct() #3 /var/www/html/dev/config/config.inc.php(118): ShopCore::initialize() #4 /var/www/html/dev/admin750ino7z2/index.php(40): require('/var/www/html/d...') #5 {main} thrown in /var/www/html/dev/src/Adapter/EntityMapper.php on line 100
`

#### Expected behavior

Flawless working in Debug Mode ^^'

#### Steps to Reproduce

Use the 
1.7.7 PrestaShop Version in German with 
apache2 and 
php 7.4

**Comment by davidglezz** [comment]
array_key_exists() is NOT deprecated, the deprecation is using the function with objects

**Comment by matks** [comment]
Hi ! Please note that 1.7.7 will not be php7.4-compatible, but 1.7.8 will be https://github.com/PrestaShop/PrestaShop/issues/16477

**Comment by Trackhe** [comment]
oh cool thank you. @matks
