### ISSUE TITLE
[BO][PRODUCTS] Add product count filtered

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#20221]
#### Is your feature request related to a problem?

Add product count filtered. Display number of products filtereds look Categorie page for example.

![Capture du 2020-07-18 15-48-37](https://user-images.githubusercontent.com/16455155/87853958-95e8ab80-c90e-11ea-89da-9992b8181e1f.png)

#### Describe the solution you'd like

![Capture du 2020-07-18 15-47-29](https://user-images.githubusercontent.com/16455155/87853939-781b4680-c90e-11ea-8658-ab49cd673afe.png)

**Comment by sarahdib** [comment]
Hello, 

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?
Add the number of product filtered.

Thanks!

**Comment by marionf** [comment]
It seems a nice idea :+1:

**Comment by MatShir** [comment]
Done on 8.1 :)
