### ISSUE TITLE
[BO][PRODUCT][SPECIFIC PRICE TAB] Add id_specific_price in list

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#20223]
## Is your feature request related to a problem?

In my option, in a list the Ids of the objects must be displayed. It is very useful for developers to debug faster in some cases.

## Before 

![Capture du 2020-07-18 16-43-53](https://user-images.githubusercontent.com/16455155/87855024-eb748680-c915-11ea-8ddf-9b65e666d5d9.png)

## After

![Capture du 2020-07-18 16-45-59](https://user-images.githubusercontent.com/16455155/87855073-37273000-c916-11ea-92c7-83170dcb7784.png)

**Comment by sarahdib** [comment]
Hello, 

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?
Add the id of the specific price.

Thanks!

**Comment by marionf** [comment]
Nice idea @PululuK :+1:
