### ISSUE TITLE
Issue login Backoffice 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#20234]
Hello

I appreciate you help, there are 2 or 3 scenario.
when I log with my account i'm rejected only if I disable the cache  the same thing from my colleague (BE) he is facing the issue
as you will see on the video I tried to log in with my account anami@ rejected but with my colleague's account (MZ) it works
as for my 3thd (BE) colleague he has the same issue so he works on other computer and network 
We are facing that issue even on mobile sometimes we should switch from mobile version to desktop version  to log in 
I don't understand what the problem 

#### Additional information

Version de PrestaShop : 1.7.6.6
Version du logiciel serveur : Apache
Version de PHP : 7.1.33
Limite de mémoire : 2028M
Temps maximal d'exécution : 3000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by alep93** [comment]
do you have find a solution?

**Comment by go-sudo** [comment]
Hi @alep93 are you facing the same issue ?

**Comment by florine2623** [comment]
Hi @go-sudo ,
Does this happen after an upgrade ? If yes, from which version ?

Can you check the cookie's lifetime in your BO in Advanced Parameters > Administration :
![Capture d’écran 2020-07-23 à 10 42 21](https://user-images.githubusercontent.com/16019289/88267593-5684db00-ccd1-11ea-8a4d-33306143074e.png)

Also this is a private platform, please change your admin link.
Thanks!

**Comment by go-sudo** [comment]
HI @florine2623 
The issue is on different version of PS , I'm facing that even with older version and for 2 websites  1.7.6.6 and 1.7.6.7

![image](https://user-images.githubusercontent.com/11594433/88268724-ce033c00-ccca-11ea-9fa3-c575230f3d90.png)

Regards

**Comment by florine2623** [comment]
Can you delete your cache from server in /var/cache ?
Delete browser cache as well.
Try to use another browser to login.
Comment gamification module and try to log in again.

**Comment by go-sudo** [comment]
Hi @florine2623 

[videos.zip](https://github.com/PrestaShop/PrestaShop/files/4969069/videos.zip)
I did, but after 3 hours I'm getting the same error on Firefox and Chrome with my email I'm rejected but with my colleague's mail I can access 



Regards

**Comment by SimonGrn** [comment]
Hello,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/).

Thank you

**Comment by go-sudo** [comment]
HI @SimonGrn 
I think that you did not read my issue, I told you that i can not login to my back office so I just added an other information perhaps it may helps about this module , so please reopen my issue because every time my prestashop cache is full I'm facing that isse
Regards

**Comment by go-sudo** [comment]
HI @florine2623 @khouloudbelguith 

I'm facing always the same issue it's not a module issue but prestashop matter so please reopen this article

Regards

**Comment by go-sudo** [comment]
Bonjour @SimonGrn, J'ai expliqué plusieurs fois que je suis rejeté à chaque fois j'essaye de mon connecter avec mon compte et qu'il me faut vider le cache du site aussi du navigateur. je suis désolé mais vous n'avez peut être rien compris 
si j'ai ajouté l'image concernant le message d'erreur rencontré avec le module mais c'était uniquement pour ajouter un détail mais cela vous dérange je vous informe que j'ai retiré cette information 
maintenant on revient s'il vous plaît à notre problème de base qui le cache .

Cordialement,

**Comment by go-sudo** [comment]
Bonjour @SimonGrn, J'ai expliqué plusieurs fois que je suis rejeté à chaque fois j'essaye de mon connecter avec mon compte et qu'il me faut vider le cache du site aussi du navigateur. je suis désolé mais vous n'avez peut être rien compris 
si j'ai ajouté l'image concernant le message d'erreur rencontré avec le module mais c'était uniquement pour ajouter un détail mais cela vous dérange je vous informe que j'ai retiré cette information 
maintenant on revient s'il vous plaît à notre problème de base qui le cache .

et voici le retour du plesk 

Hello again, 

Thank you for your patience.

I've checked the information about the issue and I found these errors in the access_log of the domain iptv366.com
[Thu Jul 23 10:22:45.866256 2020] [fcgid:warn] [pid 18904:tid 139730930861824] [client 172.68.11.11:34390] mod_fcgid: stderr: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- , referer: https://iptv366.com/fr/connexion?back=my-account
Most likely this is connected to the original issue. For example, this error is discussed here:
https://www.prestashop.com/forums/topic/960128-php-fatal-error-uncaught-smarty-0missing-template-parameter/
https://stackoverflow.com/questions/58686542/smartyexception-0missing-template-parameter-with-prestashop

Then I checked other Plesk and system logs, and I did not find anything related to this issue with the PrestaShop. 
Therefore, I can say that in this case, the issue arises from the outside of the Plesk. Most likely it is connected to the PrestaShop itself.

I've found an article about login issues, you may refer to it:
https://bobcares.com/blog/prestashop-admin-login-problem/

Also, I've checked the PrestaShop forum for similar cases, here are the links to them, please check it:

https://www.prestashop.com/forums/topic/910115-solved-16117-cant-login-to-admin-pannel/
(Disabling the "customers expertise" module and/or renaming gamification folder helped here)

https://www.prestashop.com/forums/topic/566159-17-cant-login-backend/
(Changing the permissions and Line 'locale' at the app/config/parameters.php)

https://www.prestashop.com/forums/topic/921994-i-cant-login-in-prestashop-back-office/
(PHP issue)

Also, this issue is discussed here:
https://stackoverflow.com/questions/11335073/prestashop-cant-login-in-admin

Please note, that you may enable the error reporting for debug information:
https://www.prestashop.com/forums/topic/224525-how-to-turn-on-error-reporting-for-debug-information-blank-page-500-internal-server-error/
I would suggest using this debug option to check if there will be an error on login. 

After that, you may check the error online or check it on the PrestaShop forum:
https://www.prestashop.com/forums/

If this doesn't help, please contact them directly via this link:
https://www.prestashop.com/en/support

Please let me know if you have any Plesk related questions.
Best regards,

Vladislav Kolosovskii
Technical Support Engineer
Plesk
