### ISSUE TITLE
Invalid category vars

### ISSUE THREAD

**Issue by hbmichel** [PrestaShop/PrestaShop#20239]
Good morning,

Could you help me with this please ?
```
[PrestaShopException]
Invalid category vars
at line 388 in file classes/Link.php

383.             if (is_array($category) && isset($category['id_category'])) {
384.                 $category = new Category($category, $idLang);
385.             } elseif ((int) $category) {
386.                 $category = new Category((int) $category, $idLang);
387.             } else {
388.                 throw new PrestaShopException('Invalid category vars');
389.             }
390.         }
391. 
392.         return $category;
393.     }
LinkCore->getCategoryObject - [line 441 - classes/Link.php] - [2 Arguments]
LinkCore->getCategoryLink - [line 64 - var/cache/dev/smarty/compile/9b/5f/cd/9b5fcd2fbf758086bc3898baa9ddbf680ec639eb_2.module.ttcategoryfeatureviewstem.cache.php] - [2 Arguments]
content_5f157110799977_22980346 - [line 123 - vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php] - [1 Arguments]
```

**Comment by SimonGrn** [comment]
Dear @hbmichel,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by hbmichel** [comment]
Dear Simon
I paid 99€ for your help.
If i was able to do it myself I wouldn't pay.
I was trying to put the website into English, French and German.
So please help me to solve this issue and optimize the website to work correctly.
The main page should be English.
Thanks a lot
Kind regards
Michel HB

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SimonGrn** [comment]
Hello @hbmichel,
If you paid for an intervention, it was in the [PrestaShop dedicated support](https://www.prestashop.com/support).
This is not the support, this is Github, a place to report bugs in the software. 

You didn't use the template for issue (you likely deleted everything to past a log message). We cannot work with that as it's missing a lot of crucial informations.

If you need help for your specific case, please head over our [support team](https://www.prestashop.com/support), or our [forums](https://www.prestashop.com/forums/).
This issue will stay closed, feel free to open a new one with all the details needed.

Thank you for your understanding.

**Comment by hbmichel** [comment]
Do you want me to give you access to my account and you can have a look?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SimonGrn** [comment]
Hello @hbmichel,

please find all the necessary information in my previous comment.
This conversation is now locked.

Thank you for your understanding.
