### ISSUE TITLE
BO - Orders page - Cannot change the address selected in the New Order page - The address-details is not updated

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20238]
#### Describe the bug

In the BO => Orders => New Order page, it is impossible to change the address selected
With  branch 1.7.7.x => OK
#### Expected behavior

The address should be changed

#### Steps to Reproduce

1. Go to BO => Orders
2. Click on "Add new Order"
3. Create a new customer or choose an old one for example `pub@prestashop.com`
PS: this customer has more than one address
4. add a product to cart
5. Try to change the address of the customer, The address-details is not updated (Delivery OR Invoice)
 
**Screenshots**

https://drive.google.com/file/d/1N0Yh-c5-Y75rtlXnWu8z8ZTQ70a0nAyl/view?usp=sharing

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by MatShir** [comment]
The issue is blocked, the defined behavior need to be challenged again!

**Comment by Progi1984** [comment]
I removed the "waiting for PM" as @MatShir answered in the PR.
