### ISSUE TITLE
BO duplicated request for notifications

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#20230]
#### Describe the bug
The request for notifications is repeated, one is done by the backofice itself and the other is ps_faviconnotificationbo. and so every minute or time interval.

#### Expected behavior
It would be best just to make a request at each time interval.
if another notification module were added ... would the request be made 3 times? this is not desired.

#### Steps to Reproduce
- open any page of the back-office and inspect the network.
- Then http requests to notifications appear 2 times every time interval instead of once.

**Screenshots**
![image](https://user-images.githubusercontent.com/194784/87873170-82494d80-c9bf-11ea-8a14-e9d1368f54f6.png)

#### Additional information
* Priority: lowest
* PrestaShop version: 1.7.8.0 and previous
* PHP version: 7.2

**Comment by sarahdib** [comment]
@atomiix  could you check this bug report ? 

Thank you :)

**Comment by atomiix** [comment]
Hi @davidglezz,

I agree that for this particular case, it's not optimal **but** those calls are made asynchronously so it won't make the BO any slower and for other cases where you might want a different refresh rate of those notification, it allows you to do so.

That being said, if we put appart the freedom of the refresh rate, one solution could be to fire an event when the first call is made that other modules could listen to instead of making their own call.

What do you think @PrestaShop/prestashop-core-developers ?

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
Started the work on this but the default theme hasn't an event system like new-theme (which is completely useless tbh as the Event API is fine enough)

This means that modules will need to listen to this event using 2 system (Official JavaScript `Event API`, and `events` npm package)

I don't really know what to do, an idea @PrestaShop/prestashop-maintainers ?

**Comment by PierreRambaud** [comment]
I don't think we have something to change right now. Maybe we will have to refactor the ps_faviconnotification module.
But since these calls are only in the BO, it costs nothing to keep them right now.

**Comment by MatShir** [comment]
@NeOMakinG @PierreRambaud Should we close this issue then ?

**Comment by davidglezz** [comment]
I would say this is a wontfix issue, since the solving cost is much greater than the tiny inconvenience.
I only had created the issue to notify it, but I understand that you want to keep board cleaner.

**Comment by MatShir** [comment]
@davidglezz thanks for the input
