### ISSUE TITLE
Redirect to Homepage on "Proceed to payment"

### ISSUE THREAD

**Issue by alep93** [PrestaShop/PrestaShop#20249]
#### Describe the bug

Sometimes when a customer want to proceed to checkout process and click to "Proceed to payment" in cart page, will be redirect to homepage.

#### Steps to Reproduce

1. Go to "cart"
2. Click on 'Proceed to payment'
3. Prestashop Redirect to Homepage

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Thank you!

**Comment by DianaEFB** [comment]
Hello alep93.
Have you found a solution to this problem? I am experiencing the same situation.
