### ISSUE TITLE
Problems with converting currencies when calculating shipping costs

### ISSUE THREAD

**Issue by vipdpcolor** [PrestaShop/PrestaShop#20240]
#### Describe the bug

Our shop has 2 currencies set up (polish zł and euro). We have our default currency set to euro, as it is the one used by most countries, which means we had to set up the product prices and delivery options in euro as well. Switching the currency in the front office as a customer converts the product prices properly (as seen on the first screenshot). However, it doesn't convert shipping cost (screenshot 2), which means that it changes 20 euro to 20 zł instead of 20 euro to 84,74 zł which is the correct value according to our currency settings (screenshot 3).

#### Expected behavior

Shipping costs should convert based on the values set up in the admin panel, just like the product prices. Alternatively, the delivery settings should have options for all currencies instead of just the main one.

#### Steps to Reproduce

1. Enable 2 currencies
2. Set up one of them as a default one
3. Set up shipping cost in one of the currencies
4. Add a product to cart and upon seeing the shipping cost change the shop's currency

**Screenshots**

Screenshot 1 https://i.imgur.com/da91JVh.jpg
Screenshot 2 https://i.imgur.com/4JiZ18s.jpg
Screenshot 3 https://i.imgur.com/09DKe1r.jpg

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

**Comment by sarahdib** [comment]
Hello @frntdev 

We can't reproduce
<img width="718" alt="Capture d’écran 2020-07-20 à 17 47 47" src="https://user-images.githubusercontent.com/3034677/87958001-455d8380-cab1-11ea-9c17-049082085d7e.png">
<img width="710" alt="Capture d’écran 2020-07-20 à 17 48 23" src="https://user-images.githubusercontent.com/3034677/87958009-47274700-cab1-11ea-9444-1f5a588067e1.png">

have you installed modules that are not native

**Comment by vipdpcolor** [comment]
Interesting. We have a module for validating vat numbers with VIES (cant check which one right now), Prestashop Currency and language by country from mypresta to set the language to polish for polish customers and DPD/FedEx modules. I'll have to check if it's the VIES module causing it, honestly didn't think that would be the case because it was calculating the prices of products properly. Plus I saw some people with the same issue on the forums, so my first assumption was that something broke.

**Comment by vipdpcolor** [comment]
So, after some testing I figured out that it's actually caused by the official DPD module, which is bit surprising. I'll try to contact their devs. Sorry for the false alarm.
