### ISSUE TITLE
Order Duplicate at same time

### ISSUE THREAD

**Issue by alep93** [PrestaShop/PrestaShop#20248]
#### Describe the bug

Sometimes when a customer place an order, in admin panel i see two order with same reference (different ID) at same time. In first order i see the products that customer bought, in second order i don't see anythings and order status get in waiting for supplying also if a product quantity is greater then 10 qty.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Thank you!
