### ISSUE TITLE
[BO] Removing a cart rule associated to a product, or a generic shop cart rule is not possible

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#20246]
#### Describe the bug

This bug was reported on this PR https://github.com/PrestaShop/PrestaShop/pull/20083#issuecomment-659477917
The PR reverts a previously fixed bug https://github.com/PrestaShop/PrestaShop/issues/18379

But the reason behind this is probably very different, it was actually intended to have this behaviour during the PR development. The problem comes from the `CartRule::autoAddToCart` and `CartRule::autoRemove` methods that automatically reassign the discounts after they have been removed.

Before the PR #20083 we created and assigned the cart rules manually, which resulted in many bugs, unexpected behaviour or different behaviour from the FO which relies on legacy logic to auto add/remove cart rules based on their criteria. Now the BO matches this behaviour so it's much more stable, but it removes the possibility to fine tune an order and remove some discounts.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create a product A (100€, 100 items in stock, available)
2. Create a cart rule:
  2.1. has no code
  2.2. product selection on the previous created product with 100 euro tax included
  2.3. the discount amount of 500 EUR tax included
3. In BO, add the product to a previous order
4. The discount has been added to the order
5. try to remove the discount => impossible

**Screenrecording**

https://drive.google.com/file/d/1EWqM6DyjdPlp1-0XuKnmaQPZrXSLPpGg/view?usp=sharing

**Possible solution**

We could remove the `autoAdd` feature from the BO services/handlers, but it's a bad solution because it could result in unexpected/different behaviour from the FO. Besides even if we don't use `CartRule::autoAddToCart` in the handlers this bethod is called (by default) in other places, like `Cart::getCartRules` `FrontController::init` so it could be called afterwards in many other unexpected situations.

So both BO and FO need to rely on the same logic, and we should update the behaviour of `CartRule::autoAddToCart`. For now the cart rules don't have the possibility to detect that they have been removed from an order or a cart. We need to add this kind of feature, this probably implies changing the DB structure, like adding a soft delete on `OrderCartRule` or adding a additional field in the `cart_cart_rule` to table to perform soft delete.

## Product decision

Before we start digging into this problem, the expected feature and behaviour needs to be discussed with the @PrestaShop/prestashop-product-team This unwanted behaviour was already anticipated for generic Shop rules that apply on all Orders (without code), and they are also automatically added after removal. This was discussed and validated with @MatShir but maybe we under estimated the impact especially for Product cart rules.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by kpodemski** [comment]
I think that y'all should keep behavior from 1.6.

1. Creating a new order. You can see discount added automatically but you can remove it.
2. Editing existing order, you shouldn't add any discounts automatically.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20335
