### ISSUE TITLE
1.7.6.7

### ISSUE THREAD

**Issue by letwang** [PrestaShop/PrestaShop#20251]
![ED19418EB9A4EAB7E32D7E251B0B354E](https://user-images.githubusercontent.com/3644168/87959182-0fd28d80-cae5-11ea-917c-d567849affaa.jpg)

**Comment by SimonGrn** [comment]
Dear @letwang, 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by matks** [comment]
(also we do not speak this language and because this is a screenshot we cant even use translate.google.com to understand)
