### ISSUE TITLE
PayPal duplicate Transaction

### ISSUE THREAD

**Issue by alep93** [PrestaShop/PrestaShop#20250]
#### Describe the bug

Sometimes when a customer place an order with PayPal, i receive two same transaction and i will be forced to refund one of each order.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @alep93 

If your module is PrestaShop Checkout please, contact support team on module configuration page > Subtab Help > there are an email address
If your module is PayPal Official, please contact support team on Addons : https://addons.prestashop.com/en/contact-us?id_product=1748

Thank you!
