### ISSUE TITLE
Remove Google+ in install page

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#20267]
## Is your feature request related to a problem?

Remove Google+ in install page.

![links](https://user-images.githubusercontent.com/16455155/88102269-8d5ad400-cb9f-11ea-9a33-4900fe2a9aa2.png)

![google+mort](https://user-images.githubusercontent.com/16455155/88102179-6c927e80-cb9f-11ea-946a-68a194dcda08.png)

## Additional information
- PrestaShop version: 1.7.7.x
- PHP version: N/A

**Comment by PierreRambaud** [comment]
Hi @PululuK 
We will backport #17340 (Issue #17256) on the 1.7.7.x branch :wink: 
Thanks
