### ISSUE TITLE
Prestashop nginx - Site goes 404 after new user registration

### ISSUE THREAD

**Issue by orangepixsamuele** [PrestaShop/PrestaShop#20275]
When a new user regist himself in the website, site goes 404, but if he refresh the page, it works normally... Some idea?

Prestashop 1.7.6.5
Nginx 1.16.1

ssl.conf:
#
# HTTPS server configuration
#

server {
    listen       443 quic reuseport;
    listen       443 http2 ssl;
    listen       [::]:443 quic reuseport;
    listen       [::]:443 http2 ssl;
    server_name  _;

    ssl_certificate      /var/lib/jelastic/SSL/jelastic.chain;
    ssl_certificate_key  /var/lib/jelastic/SSL/jelastic.key;

    ssl_session_timeout  5m;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;

    add_header alt-svc 'h3-23=":443"; ma=86400';

    include /etc/nginx/aliases.conf;
    index  index.html index.htm index.php;
  
 

    location / {
		root   /var/www/webroot/ROOT;
    
    	location /admin-dev/ {
			if (!-e $request_filename) {
              rewrite ^/.*$ /admin-dev/index.php last;
          }
 		}
    	location / {
	      	if (!-e $request_filename) {
            	rewrite ^/.*$ /index.php last;
        	}
    	}
    	
    	location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
 			expires 30d;
			add_header Cache-Control "public, no-transform";
		}

		location ~ \.php$ {
			include /etc/nginx/fastcgi_params;
			fastcgi_pass unix:/var/run/php-fpm.socket;
			fastcgi_param SCRIPT_FILENAME /var/www/webroot/ROOT$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_script_name;
			fastcgi_param DOCUMENT_ROOT /var/www/webroot/ROOT;
		}
    
    }
    
    location ~ /\. { deny all; access_log off; log_not_found off; }

    location ~ \.php$ {
			location ~ /\. { deny all; access_log off; log_not_found off; }
			include /etc/nginx/fastcgi_params;
			fastcgi_pass unix:/var/run/php-fpm.socket;
			fastcgi_param SCRIPT_FILENAME /var/www/webroot$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_script_name;
			fastcgi_param DOCUMENT_ROOT /var/www/webroot;
    }
  
  	# File security
    # .htaccess .DS_Store .htpasswd etc
    location ~ /\. {
        deny all;
    }
    # Source code directories
    location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor|var)/ {
        deny all;
    }
    # vendor in modules directory
    location ~ ^/modules/.*/vendor/ {
        deny all;
    }
    # Prevent exposing other sensitive files
    location ~ \.(yml|log|tpl|twig|sass)$ {
        deny all;
    }

    # Prevent injection of php files
    location /upload {
        location ~ \.php$ {
            deny all;
        }
    }
    #location /img {
    #    location ~ \.php$ {
    #        deny all;
    #    }
    #}
  
  	
  
  
  	##
    # Gzip Settings
    ##

    gzip on;
    gzip_disable "msie6";                                             # Do people still use Internet Explorer 6? In that case, disable gzip and hope for the best!
    gzip_vary on;                                                     # Also compress content with other MIME types than "text/html"
    gzip_types application/json text/css application/javascript;      # We only want to compress json, css and js. Compressing images and such isn't worth it
    gzip_proxied any;
    gzip_comp_level 6;                                                # Set desired compression ratio, higher is better compression, but slower
    gzip_buffers 16 8k;                                               # Gzip buffer size
    gzip_http_version 1.0;                                            # Compress every type of HTTP request
  
  
    # [REQUIRED EDIT IF MULTILANG]
    rewrite ^/it$ /it/ redirect;
    rewrite ^/it/(.*) /$1;
  
    rewrite ^/en$ /en/ redirect;
    rewrite ^/en/(.*) /$1;
  
  	# Global rewrite not depending on languages
    rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;
    rewrite "^/c/([0-9]+)(\-[_a-zA-Z0-9-]*)/(.*)\.jpg$" /img/c/$1$2.jpg last;
    rewrite "^/c/([_a-zA-Z-]+)/(.*)\.jpg$" /img/c/$1.jpg last;
    rewrite "^/([a-z0-9]+)\-([a-z0-9]+)(\-[_a-zA-Z0-9-]*)/(\P{M}\p{M}*)*\.jpg$" /img/p/$1-$2$3.jpg last;
    rewrite "^/([0-9]+)\-([0-9]+)/(\P{M}\p{M}*)*\.jpg$" /img/p/$1-$2.jpg last;
    rewrite "^/([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$1$2.jpg last;
    rewrite "^/([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$1$2$3.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$1$2$3$4.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$4/$1$2$3$4$5.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8.jpg last;
    rewrite "^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?/(\P{M}\p{M}*)*\.jpg$" /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9.jpg last;
    rewrite "^/([0-9]+)\-(\P{M}\p{M}*)+\.html(.*)$" /index.php?controller=product&id_product=$1$3 last;
    rewrite "^/([0-9]+)\-([a-zA-Z0-9-]*)(.*)$" /index.php?controller=category&id_category=$1$3 last;
    rewrite "^/([a-zA-Z0-9-]*)/([0-9]+)\-([a-zA-Z0-9-]*)\.html(.*)$" /index.php?controller=product&id_product=$2$4 last;
    rewrite "^/([0-9]+)__([a-zA-Z0-9-]*)(.*)$" /index.php?controller=supplier&id_supplier=$1$3 last;
    rewrite "^/([0-9]+)_([a-zA-Z0-9-]*)(.*)$" /index.php?controller=manufacturer&id_manufacturer=$1$3 last;
    rewrite "^/content/([0-9]+)\-([a-zA-Z0-9-]*)(.*)$" /index.php?controller=cms&id_cms=$1$3 last;
    rewrite "^/content/category/([0-9]+)\-([a-zA-Z0-9-]*)(.*)$" /index.php?controller=cms&id_cms_category=$1$3 last;
    rewrite "^/module/([_a-zA-Z0-9-]*)/([_a-zA-Z0-9-]*)$" /index.php?fc=module&module=$1&controller=$2 last;
    rewrite "^/stock/([_a-zA-Z0-9-]*)/([_a-zA-Z0-9-]*)$" /index.php?controller=$1$2 last;
  
  # AlphaImageLoader for IE and fancybox
    rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

    # Web service API
    rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;
  
  # Symfony controllers Specific for 1.7

    location ~ /(international|_profiler|module|product|combination|specific-price)/(.*)$ {
        try_files $uri $uri/ /index.php?q=$uri&$args /admin-dev/index.php$is_args$args;
    }

}
<img width="807" alt="Schermata 2020-07-22 alle 11 09 16" src="https://user-images.githubusercontent.com/68639457/88158859-d5641000-cc0c-11ea-9424-ab38090fe17e.png">

**Comment by orangepixsamuele** [comment]
This happen because Tools::redirect link to "www.website.it" instead "https://www.websitelink.it".. is there something that i can do in ssl.conf to rebuild all url without https?

**Comment by sarahdib** [comment]
@PierreRambaud  could you take a look ? 

Thank you :)

**Comment by PierreRambaud** [comment]
Hi everyone,

The problem seems to be a misconfiguration in the Back Office, you must enable and force the HTTPS (which is better for your shop).

Kind regards,

**Comment by khouloudbelguith** [comment]
Hi @orangepixsamuele,

Since we had no news for more than 20 days, I will close the ticket. Feel free to open another one if you can give us specific details.

Thanks!
