### ISSUE TITLE
Bug when updating to Prestashop 1.7.6.5

### ISSUE THREAD

**Issue by malodeco** [PrestaShop/PrestaShop#20274]
I have an error message that appears when I update the module "module 1 click Upgrade"  to Prestashop 1.7.6.5

1. I downloaded the Module 1 Click Upgrade
2. I search the module in my catalogue and click on "Upgrade Prestashop Now!" 
3. The download starts
4. Then I have a message that appears in my activity log : 
"Backup of current files. Another 30,908 files. 
[Ajax / Erreur du serveur pour la sauvegarde d’actionFiles] textStatus: « error » errorThroarn: » " jqXHR: "
500 Server Error
Oops, something went wrong.
Try updating this page or do not hesitate to contact us if the problem persists. " 

I specify that I do not know at all about programming etc... so if you can explain me with simple words I would be very grateful. 

Thank you in advance
![Capture 11](https://user-images.githubusercontent.com/67692415/88153240-6d5dfb80-cc05-11ea-8402-2b0d4ea1c1cb.JPG)
![Capture 10](https://user-images.githubusercontent.com/67692415/88153247-7058ec00-cc05-11ea-8e96-cfa08e1d495f.JPG)

**Comment by khouloudbelguith** [comment]
Hi @malodeco,

Thanks for your report.
Can you please check if you have the same behavior as reported here: https://github.com/PrestaShop/PrestaShop/issues/9564#issuecomment-470146173

Thanks!

**Comment by malodeco** [comment]
Thank you for your answer.
 Could you explain it in simpler words, please? Because I’m not a programmer and I don’t understand

**Comment by khouloudbelguith** [comment]
@malodeco, your database password contains `%`?
For example, you can check the file `/app/config/parameters.php` and verify the 'database_password', if it is correct.

Thanks!

**Comment by malodeco** [comment]
I updated it again and I have another error message "Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it."
 How do I know if I am allowed to write to the disk? 

Thank you.

**Comment by khouloudbelguith** [comment]
@malodeco, Thanks to check our [documenation](http://doc.prestashop.com/display/PS17/Installing+PrestaShop) to explain how updating the file permissions.

Your issue that your database password contains `%` ? is it?

Thanks!

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
