### ISSUE TITLE
Error 500 when clicking on order

### ISSUE THREAD

**Issue by sobamartinez** [PrestaShop/PrestaShop#20277]
Bonjour,
j'ai besoin de changer l'état d'une commande, quand clique sur la commande pour l'affiche j'ai un message d'erreur 500.
![Capture d’écran 2020-07-22 à 14 43 18](https://user-images.githubusercontent.com/42717288/88178078-1c143300-cc2a-11ea-94e9-8e30755d8070.png)
![Capture d’écran 2020-07-22 à 14 43 18](https://user-images.githubusercontent.com/42717288/88178142-351ce400-cc2a-11ea-8250-15d17466c035.png)

**Comment by TristanLDD** [comment]
Hello @sobamartinez Please, thanks for your report
Please send your request in English, English is the norm on GitHub.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by sobamartinez** [comment]
Hello,
I need to change the state of an order, when click on the order for the poster I have a 500 error message.

Version prestashop 1.7.5.1

1.Commande
2. afficher

![Capture d’écran 2020-07-22 à 16 20 10](https://user-images.githubusercontent.com/42717288/88187881-618b2d00-cc37-11ea-90c1-d89c5a7aa096.png)

**Comment by sobamartinez** [comment]
[probleme01.MOV.zip](https://github.com/PrestaShop/PrestaShop/files/4960632/probleme01.MOV.zip)

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
