### ISSUE TITLE
Notification add to cart doesnt work - after upgrade PS 1.7.6.5 to 1.7.6.7 

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#20271]
We have after the upgrade an error, the information that the product in the shopping cart is not displayed, also the number on the shopping cart icon does not change.

We use the Page Cache Ultimate module, but all third-party modules were manually disabled before the upgrade. The cache has been cleared.

---
This error message is displayed by the Console:

Uncaught ReferenceError: ajaxGetProductUrl is not defined
    at Object.pushProductToDatalayer (bottom-4a325e1333.js:285)
    at Object.addToCart (bottom-4a325e1333.js:285)
    at Object.<anonymous> (bottom-4a325e1333.js:287)
    at Object.i.emit (bottom-4a325e1333.js:233)
    at Object.<anonymous> (bottom-4a325e1333.js:88)
    at Object.<anonymous> (bottom-4a325e1333.js:39)
    at u (bottom-4a325e1333.js:39)
    at Object.fireWith [as resolveWith] (bottom-4a325e1333.js:39)
    at S (bottom-4a325e1333.js:39)
    at XMLHttpRequest.<anonymous> (bottom-4a325e1333.js:39)
pushProductToDatalayer @ bottom-4a325e1333.js:285
addToCart @ bottom-4a325e1333.js:285
(anonymous) @ bottom-4a325e1333.js:287
i.emit @ bottom-4a325e1333.js:233
(anonymous) @ bottom-4a325e1333.js:88
(anonymous) @ bottom-4a325e1333.js:39
u @ bottom-4a325e1333.js:39
fireWith @ bottom-4a325e1333.js:39
S @ bottom-4a325e1333.js:39
(anonymous) @ bottom-4a325e1333.js:39
load (async)
send @ bottom-4a325e1333.js:39
ajax @ bottom-4a325e1333.js:39
m.<computed> @ bottom-4a325e1333.js:39
(anonymous) @ bottom-4a325e1333.js:88
dispatch @ bottom-4a325e1333.js:39
g.handle @ bottom-4a325e1333.js:39

Do you have any idea what might be causing this?

best regards
piotr

**Comment by TristanLDD** [comment]
Hello @pdkey, thanks for your report
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem, as so it can't be treated on Github. I encourage you to visit PrestaShop's support solutions https://www.prestashop.com/fr/support or forum https://www.prestashop.com/forums/ to get a personalized answer to the problem you encounter. 
Thank you
