### ISSUE TITLE
Cannot programmatically add feature (insert into database)

### ISSUE THREAD

**Issue by VeiJar1** [PrestaShop/PrestaShop#20276]
#### Describe the bug

I have a hook actionProductSave(), where I want to add a feature to product, if product is pack of products. I tried using Product::addFeatureProductImport() but it did not work, so I tried to do the sql query myself.

```php
$sql = 'INSERT INTO ps_feature_product (id_feature, id_product, id_feature_value) VALUES (1, 22, 2) ON DUPLICATE KEY UPDATE id_feature_value = 2';
$result = Db::getInstance()->execute($sql);
```

Hook triggers normally and whole save process gives no errors, but nothing is added into database.

Tried also with insert(): 

```php
$data2 = [
    'id_feature' => 1,
    'id_product' => 22,
    'id_feature_value' => 2
];

$result = Db::getInstance()->insert('feature_product', $data2);
```

But result is the same.

If you first use execute() and after that use insert(), you get an SQL-duplicate error on the form after saving. After you refresh the page, you can see it actually added the given feature for the pack despite the error.

Another problem is that, if you have both SQL-queries in code, you can't delete the feature. You get a http error 500.

#### Expected behavior

The feature values would save into the database without any errors, using only 1 query.

#### Steps to Reproduce

1. Create your custom module
2. Register hook: $this->registerHook('actionProductSave') on module install
3. Add feature from admin panel
4. Make a product pack
5. Add this code on mymodulex.php: 
```php
public function hookActionProductSave($params) {

    Logger::addLog('hookActionProductSave()', 1, null, null,  null, true);
    $product = $params['product'];
    $id_product = $product->id;

    if(Pack::isPack($id_product)) {
        $packItems = Pack::getItems($id_product, 1);
        foreach($packItems as $packItem) {
            $categories = $packItem->getCategories();  
            if(in_array(IDx, $categories, false)) {
                //If you comment out the $sql, insert method would not work on it's own.
                $sql = 'INSERT INTO ps_feature_product (id_feature, id_product, id_feature_value) VALUES (1, 22, 2) ON DUPLICATE KEY UPDATE id_feature_value = 2';
                $result = Db::getInstance()->execute($sql);
                //If you comment this table and result out, sql would not insert
                $data = [
                    'id_feature' => 1,
                    'id_product' => 22,
                    'id_feature_value' => 2
                ];
                $result = Db::getInstance()->insert('feature_product', $data);
            }
        }

    }
```
6. Save product pack
7. See error and refresh
8. See the feature added in succesfully
9. Delete the feature from admin
10. See http error 500 on form.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* Apache
* PHP version: 7.3

I'm really sorry if this is a messy bug report, this is my first one so bare with me.

I would also like to know if there's a third way of doing this without any errors, so our customer would be happy with our results. 

Thank you for your help!

**Comment by TristanLDD** [comment]
Hi @VeiJar1, thanks you for your first report :)  
@PrestaShop/prestashop-core-developers WDYT?

**Comment by matks** [comment]
Try
```php
Pack::addItem($packId, $productId, $quantity, $combinationId);
```

Also PS 1.7.6.5 is not fully compliant with php7.3, try php7.2 instead

**Comment by VeiJar1** [comment]
> Try
> 
> ```
> Pack::addItem($packId, $productId, $quantity, $combinationId);
> ```
> 
> Also PS 1.7.6.5 is not fully compliant with php7.3, try php7.2 instead

Hi, we already have a pack that contains products. I want to add features from these products into the pack itself. This way user can search the pack by features.

Did you test the code?

**Comment by matks** [comment]
> > Try
> > ```
> > Pack::addItem($packId, $productId, $quantity, $combinationId);
> > ```
> > 
> > 
> > Also PS 1.7.6.5 is not fully compliant with php7.3, try php7.2 instead
> 
> Hi, we already have a pack that contains products. I want to add features from these products into the pack itself. This way user can search the pack by features.
> 
> Did you test the code?

Ha, my bad, I read too fast. I saw "add products" instead of "add features".

**Comment by VeiJar1** [comment]
> > > Try
> > > ```
> > > Pack::addItem($packId, $productId, $quantity, $combinationId);
> > > ```
> > > 
> > > 
> > > Also PS 1.7.6.5 is not fully compliant with php7.3, try php7.2 instead
> > 
> > 
> > Hi, we already have a pack that contains products. I want to add features from these products into the pack itself. This way user can search the pack by features.
> > Did you test the code?
> 
> Ha, my bad, I read too fast. I saw "add products" instead of "add features".
@matks 
Happens to all of us :P
Just wondering why this is still "waiting for author" labeled?

Do you have time to test the bug itself?

**Comment by PierreRambaud** [comment]
If you insert the value in the database twice the error is logic, it's a duplicate.
The problem come from the fact that in `actionProductSave` you have to rely on `id_product` instead of `$product->id` because this one is empty.

I create a new product with the hook and everything is ok:
![image](https://user-images.githubusercontent.com/1462701/101375179-63d0e980-38af-11eb-9716-4dc44e3edb9d.png)

![image](https://user-images.githubusercontent.com/1462701/101375237-70554200-38af-11eb-89cf-94182971cd3f.png)

![image](https://user-images.githubusercontent.com/1462701/101375271-78ad7d00-38af-11eb-9517-d0d0a6ed4fb7.png)

**Comment by hibatallahAouadni** [comment]
Hello @VeiJar1 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
