### ISSUE TITLE
Can't create separate product combinations

### ISSUE THREAD

**Issue by aleksiuno** [PrestaShop/PrestaShop#20272]
#### Describe the bug

I've created second multishop store. In BO second store context i went to Catalogs > Products > Any productwith few combinations > Combinations. I've deleted default combination and tried to create a new one. I've got an error.
``Duplicate entry '96-1' for key 'product_default'<br /><br /><pre>UPDATE `ps_product_attribute` SET `id_product_attribute` = '15787',`id_product` = '96',`location` = '',`ean13` = '',`isbn` = '',`upc` = '',`quantity` = '0',`reference` = '',`supplier_reference` = '',`wholesale_price` = '0',`price` = '0',`ecotax` = '0',`weight` = '0',`unit_price_impact` = '0',`minimal_quantity` = '1',`low_stock_threshold` = NULL,`low_stock_alert` = '0',`default_on` = '1',`available_date` = '0000-00-00' WHERE `id_product_attribute` = 15787</pre>``
When I've checked the table I've noticed that it doesn't takes id_shop into account.

#### Expected behavior

When I try to delete and save a combination in any shop context I a

#### Steps to Reproduce

1. Create a second multishop store
2. Change a context to any of two stores
3. go to ``Catalogs > Products > Any productwith few combinations > Combinations``
4. Delete a default combination
5. Try to create a new combination

**Screenshots**

![Screenshot from 2020-07-22 10-22-14](https://user-images.githubusercontent.com/17498592/88147025-53bcb400-cc05-11ea-9868-1c03d8c6d71a.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @aleksiuno ,

I did manage to reproduce your issue in PS 1.7.6.5, although this issue has been corrected in PS 1.7.7.0. I suggest you wait for the release of PS 1.7.7 stable version and update your shop.

Here's the screen record of the issue in PS 1.7.7.0 :
https://drive.google.com/file/d/14-CzGyf4-9sbvtxy5ogVzxHkH6pnZZa8/view

I'll close this issue as it is fixed !
Thanks!
