### ISSUE TITLE
Small formal bug in carts/helpers/view/view.tpl

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#20286]
imho it is only formal bug and cannot cause a problem 

the file **admin/themes/default/template/controllers/carts/helpers/view/view.tpl**

![ps17](https://user-images.githubusercontent.com/3242659/88257825-f422df00-ccbe-11ea-864b-839efa45205d.png)
 
end of block inside of inner div can be  confusing

**Comment by matks** [comment]
@Eva-F thanks for the feedback, it is obviously an issue you are right 👍  

Doing the PR is very easy, do you want to do it or I do it ?

**Comment by Sinepel** [comment]
I can also take care of it if no one wants to do PR :)

**Comment by Eva-F** [comment]
> 
> 
> @Eva-F thanks for the feedback, it is obviously an issue you are right 👍
> 
> Doing the PR is very easy, do you want to do it or I do it ?

yes plz, do it yourself ..

**Comment by matks** [comment]
@Sinepel be my guest 😄

**Comment by Sinepel** [comment]
@matks Done #20289 :)

**Comment by LouiseBonnard** [comment]
@Progi1984, @matthieu-rolland, this issue is in the 1.7.8 kanban while milestoned for the 1.7.7... should I milestone it for the 1.7.8 instead? :-)

**Comment by Progi1984** [comment]
@LouiseBonnard Fixed. The PR has been fixed in 178 so I change the milestone.
