### ISSUE TITLE
All products in back office display a white page. v1.7.1.1 - php 5.6 - classic theme

### ISSUE THREAD

**Issue by Pnowfr** [PrestaShop/PrestaShop#20281]
Since 1 day, after adding and deleting a new category, all products (and add new product) in the back office spins for 20 seconds and displays a blank page.
I activated debug mode and checked all traces and logs, I did not find any error.

Thanks for your help.
Piotr

**Comment by kpodemski** [comment]
First of all, your are using ancient version of the PrestaShop, also, this is not really a place for such a issues, I think that you should ask for an advice on the forum or hire someone to check your store
