### ISSUE TITLE
cache issue with login to backoffice

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#20307]
Hello

I appreciate you help, there are 2 or 3 scenario.
when I log with my account i'm rejected only if I disable the cache the same thing from my colleague (BE) he is facing the issue
as you will see on the video I tried to log in with my account anami@ rejected but with my colleague's account (MZ) it works
as for my 3thd (BE) colleague he has the same issue so he works on other computer and network
We are facing that issue even on mobile sometimes we should switch from mobile version to desktop version to log in
I don't understand what the problem

https://www.youtube.com/watch?v=OXEzStsC-lA
https://www.youtube.com/watch?v=UQQaQZ6DE88
https://www.youtube.com/watch?v=dG-SVPJcET0
I did delete the cache from server in /var/cache ?
Delete browser cache as well.
Try to use another browser to login but after 3 hours I'm getting the same error on Firefox and Chrome with my email 

videos in attachment
[videos.zip](https://github.com/PrestaShop/PrestaShop/files/4970561/videos.zip)

I'm not talking here about any module issue it's just BACKOFFICE LOGIN MATTER 
Regards

Additional information
Version de PrestaShop : 1.7.6.6
Version du logiciel serveur : Apache
Version de PHP : 7.1.33
Limite de mémoire : 2028M
Temps maximal d'exécution : 3000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by florine2623** [comment]
Hi @go-sudo ,
This is not a PrestaShop core issue. Please contact the support or an agency if you need customized help.
https://addons.prestashop.com/en/388-support
https://www.prestashop.com/en/partners
Thanks!

**Comment by go-sudo** [comment]
Hi @florine2623 

how come it's not prestashop issue 

so read this 

Hello again, 

Thank you for your patience.

I've checked the information about the issue and I found these errors in the access_log of the domain iptv366.com
[Thu Jul 23 10:22:45.866256 2020] [fcgid:warn] [pid 18904:tid 139730930861824] [client 172.68.11.11:34390] mod_fcgid: stderr: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- , referer: https://iptv366.com/fr/connexion?back=my-account
Most likely this is connected to the original issue. For example, this error is discussed here:
https://www.prestashop.com/forums/topic/960128-php-fatal-error-uncaught-smarty-0missing-template-parameter/
https://stackoverflow.com/questions/58686542/smartyexception-0missing-template-parameter-with-prestashop

Then I checked other Plesk and system logs, and I did not find anything related to this issue with the PrestaShop. 
Therefore, I can say that in this case, the issue arises from the outside of the Plesk. Most likely it is connected to the PrestaShop itself.

I've found an article about login issues, you may refer to it:
https://bobcares.com/blog/prestashop-admin-login-problem/

Also, I've checked the PrestaShop forum for similar cases, here are the links to them, please check it:

https://www.prestashop.com/forums/topic/910115-solved-16117-cant-login-to-admin-pannel/
(Disabling the "customers expertise" module and/or renaming gamification folder helped here)

https://www.prestashop.com/forums/topic/566159-17-cant-login-backend/
(Changing the permissions and Line 'locale' at the app/config/parameters.php)

https://www.prestashop.com/forums/topic/921994-i-cant-login-in-prestashop-back-office/
(PHP issue)

Also, this issue is discussed here:
https://stackoverflow.com/questions/11335073/prestashop-cant-login-in-admin

Please note, that you may enable the error reporting for debug information:
https://www.prestashop.com/forums/topic/224525-how-to-turn-on-error-reporting-for-debug-information-blank-page-500-internal-server-error/
I would suggest using this debug option to check if there will be an error on login. 

After that, you may check the error online or check it on the PrestaShop forum:
https://www.prestashop.com/forums/

If this doesn't help, please contact them directly via this link:
https://www.prestashop.com/en/support

Please let me know if you have any Plesk related questions.
Best regards,

Vladislav Kolosovskii
Technical Support Engineer
Plesk

**Comment by SimonGrn** [comment]
I understand you're frustrated @go-sudo , but you need to understand that we cannot take the time to investigate such a weak signal, linked to your own environment.
You say yourself that it's working with an account and not with another account. Maybe investigate on this ? Maybe you have a permission problem ? Did you try by creating a new account, or checking your own cookies on your browser, or maybe you have an extension blocking something ?

We cannot reproduce your issue on our end and you're the first to post this exact problem, so we cannot help you here.
You will find some help on the forums, or on the Slack channel, or even in our support plan (all links already given).

Thanks for your understanding.

FYI I didn't lock the second issue you created [here](https://github.com/PrestaShop/PrestaShop/issues/20308) but you cannot continue creating bug reports about the same issue over and over again.
