### ISSUE TITLE
Cross Site Scripting Issue in PrestaShop Using File Upload Functionality

### ISSUE THREAD

**Issue by p1nk15amak** [PrestaShop/PrestaShop#20306]
An issue is discovered in PrestaShop  version 1.7.6.7 under the Catelog feature when using the file-upload functionality for uploading the Files for various products. This issue exists because it fails to implement file content checks and improperly handles the output, resulting in cross-site scripting attack that leads to cookie stealing or malicious actions.

#### Steps to Reproduce

1. Go to Catelog feature 
2. Click on File component and add the details accordingly.
3. Create a file with .html extension and enter the payload
     <script>alert('XSS!!');</script>within it. (Here its, uplod.html)
4. Upload the file
5. Login as customer and click on the file uploaded for the particular product.
6. You can see the XSS payload gets executed.

CVSS Score:
CVSS:3.0/AV:N/AC:H/PR:H/UI:R/S:C/C:H/I:H/A:N

![SS1](https://user-images.githubusercontent.com/49667959/88317314-b792ca00-cd36-11ea-8011-e10898092c67.PNG)
![SS2](https://user-images.githubusercontent.com/49667959/88317319-b9f52400-cd36-11ea-9819-9b6714187828.PNG)
![SS3](https://user-images.githubusercontent.com/49667959/88317322-bb265100-cd36-11ea-8c44-06d0bf73f226.PNG)

**Comment by matks** [comment]
Hi @p1nk15amak ! thank you for the report

Am I wrong if I guess that you had a look at [our newly opened bug bounty](https://build.prestashop.com/news/bug-bounty-program/) and that you found this while bug hunting, but since the CVS score is low, you reported it here ?

**Comment by PierreRambaud** [comment]
Hi,

This is something we already received on the Bug Bounty program. 
Unfortunately, this is not a security issue, as we allow to upload any files we wanted, (it's the same for SVG files), any users with admin employee can upload this kind of file, like he's able to upload a module or a theme with comprised data.

Kind regards
