### ISSUE TITLE
[1.7.7 beta] Create order from backoffice not working - cannot select customer

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20317]
#### Steps to Reproduce

1. Install 1.7.7 beta release.
2. Make some customers.
3. Go to Orders. Click create new order.
4. **Search for customer is not working.** 
5. **Clicking create new customer brings you to a fullscreen form, not modal. If you create a customer in this form, it shows a grey page with an alert.**

#### Additional information

* PrestaShop version: 1.7.7 beta
* PHP version: 7.2

**Comment by matks** [comment]
@Hlavtox Just had a look on `1.7.7.x`, it works well for me 🤔  . Did you use the 1.7.7 beta ZIP or did you use latest changes on `1.7.7.x` branch ?

**Comment by Hlavtox** [comment]
@matks I used the ZIP.

Is it enough to download the branch and run composer install?

**Comment by SimonGrn** [comment]
> 
> 
> @matks I used the ZIP.
> 
> Is it enough to download the branch and run composer install?

You can indeed `git clone`, switch to the `1.7.7.x` branch then go to the folder and run `composer install`.
You will then be able to install your shop as usual from the `/install-dev` folder.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you. I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you :) !

**Comment by farrum** [comment]
I have exactly same issue except my php version is 7.3 and am using Prestashop v1.7.7.1 . Cant search for customer when trying to create a new order.
