### ISSUE TITLE
BO - View an order page - Incorrect behavior after editing address with an invalid field Address1

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20323]
#### Describe the bug

In the BO => View order page, when we try to create edit address with invalid field Address1 (too long > 128 chars), there is a redirection to the Address list page even though this is a modal

#### Expected behavior

After clicking save => we should stay on the form, with a red message to tell us what is wrong

#### Steps to Reproduce

1. Go to the BO => View an order page
2. Click on "edit delivery address", it opens a modal
3. Set an invalid field Address 1 ( too long > 128 chars )
4. Click save
5. See error

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/issues/20323

**Comment by Progi1984** [comment]
Fixed  by #20303
