### ISSUE TITLE
Multishop All shops currency convertion update update only 1st shop not all - 1.7.7 but also in 1.7.6 and 1.6

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#20339]
Updated:

I have noticed that there is problem with currency conversion in multishop. 
Multishop only are affected.

When you have a multishops, usually you choose All shops to update all shops not separately.
In conversion you have button to update all currencies.
Even you are in All shop and you will click on update button the button will update only 1st shop, not all.

You need to go separate to every shop and click the update currencies conversion button.
In other way you can have currencies like 1:1. GBP vs rupee which may cause a loose.
Cron would update only the 1st shop not all when you use multishops.

I have found this problem testing 1.7.7 but it also exist on 1.6.

All shops and button update currencies should update all currencies on all shops not only on the 1st one.
The same should be with cron.

Now you need to got to every shop separately and update manually using button.
Cron for example in 1.6 prestashop would works only with 1st shop.
This is quite big potential loos when the merchant will not notice it.
.

My currency are:
kr Danish krone
$ Dollar
€ Euro
Ft? Forint
? Indian Rupee
kr Krona
kr Krone
L Pound
? Riyal
??? Ruble
Y Yen
Y Yuan

add the same and test it.

Problem exist on older presta so I think this is not new bug.

#### Additional information

* PrestaShop version: 1.7.7 beta and previous
* PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @adamus007p,

Thanks for your report.
The Exchange rate autoupdate is not working as reported here: https://github.com/PrestaShop/PrestaShop/issues/13825
I tried with 1.7.7.x branch, with Manual update and it is well working.
I attached a screen record
https://drive.google.com/file/d/1h_i83GR7bA5C5MTv1LiqDCUZVoXOWTWb/view?usp=sharing
Thanks to check and feedback.

**Comment by adamus007p** [comment]
Hello @khouloudbelguith ,

I will update my thoughts. The problem is not with one shop but with multishop.
I see that this problem is since 1.6 or earlier.

What I have noticed that even when you use All shop and click update currency button there is no update of all shops.

In other shops currencies are like 1 which is big error.


Please add more shops, use multishop and check how this button works.
Change shops and see.


Select every separate shop and click update button works, but not crone.
Select all shops and click button update currencies it will update only 1st shop.
When I have 4 shops, It will not update all. This is really really big bug.
As someone can change shop to .de and select currency in Indian Rupee and buy for "big discount" everything.

It should not words like that.

**Comment by adamus007p** [comment]
Updated:

I have noticed that there is problem with currency conversion in multishop.
Multishop only are affected.

When you have a multishops, usually you choose All shops to update all shops not separately.
In conversion you have button to update all currencies.
Even you are in All shop and you will click on update button the button will update only 1st shop, not all.

You need to go separate to every shop and click the update currencies conversion button.
In other way you can have currencies like 1:1. GBP vs rupee which may cause a loose.
Cron would update only the 1st shop not all when you use multishops.

I have found this problem testing 1.7.7 but it also exist on 1.6.

All shops and button update currencies should update all currencies on all shops not only on the 1st one.
The same should be with cron.

Now you need to got to every shop separately and update manually using button.
Cron for example in 1.6 prestashop would works only with 1st shop.
This is quite big potential loos when the merchant will not notice it.

**Comment by khouloudbelguith** [comment]
@adamus007p, I tried with a multishop and it is ok also.
I attached a screen record
https://drive.google.com/file/d/1A2pol5xIaW3v-PRQ4j-XfDopxKjO-Zh5/view?usp=sharing
Thanks to check and feedback.

**Comment by adamus007p** [comment]
@khouloudbelguith it it nice that's it is working on your end.
Maybe on clear fresh installation it is working.


What I can see that my version 1.7.7 not works (after update)
I have check also 1.6 - the same it does not works.
I have 4 multi shops.

**Comment by khouloudbelguith** [comment]
@adamus007p ,

>What I can see that my version 1.7.7 not works (after update)

Did you make an upgrade of your shop from an old version PrestaShop to PS1.7.7.0beta1?

Thanks!

**Comment by adamus007p** [comment]
yes upgrade not fresh install

**Comment by khouloudbelguith** [comment]
@adamus007p, 177 stable is not released yet.
The beta version is only for testing and currently, it is not possible to upgrade from beta version (1770beta1) to the stable version (1770 stable version).

What is your exact version PrestaShop did you before the upgrade?

Thanks!

**Comment by adamus007p** [comment]
Update from 1.6

**Comment by khouloudbelguith** [comment]
@adamus007p, I can confirm that this issue is not working in the PS1.6.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

But this issue is fixed in the PS1.7.6.7 / 1.7.7.x branch.
https://drive.google.com/file/d/1S1jD1ArLWrAgxxO5i7N2TMTRofkUvaeu/view?usp=sharing
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by adamus007p** [comment]
So maybe updates from 1.6 are affected.
@khouloudbelguith which tool do you use to record screen?

**Comment by khouloudbelguith** [comment]
@adamus007p, it is screencastify.

Thanks!

**Comment by simulbeni** [comment]
I created a solution for this issue.

![image](https://user-images.githubusercontent.com/437314/99756887-30066d80-2b14-11eb-8483-ba8b37e5bea5.png)

![image](https://user-images.githubusercontent.com/437314/99756917-4ad8e200-2b14-11eb-8689-bb6cfe79264d.png)

![image](https://user-images.githubusercontent.com/437314/99756958-5cba8500-2b14-11eb-8546-e29670260b55.png)

**Comment by momo1240** [comment]
Hello 
this issue is still present on Prestashop 1.7.8.7 with multistore configuration
enven if we decide to use the url to call the script as described here 
https://devdocs.prestashop-project.org/1.7/faq/pricing/
(myshop.com/adminname/cron_currency_rates.php?secure_key={my_secure_key})

still the exchange update works only for the first shop not all shops currency rates are updated

thank you

**Comment by adamus007p** [comment]
What I see that update currency via cron do not works. I am not use multishop anymore so I can not check if the problem still exist.
