### ISSUE TITLE
Faceted Search Problem

### ISSUE THREAD

**Issue by J147julie** [PrestaShop/PrestaShop#20336]
Am using Prestashop 1.7.6.7 and have configured the Faceted Search module which seems to have gone fine, however when testing it on the frontend it doesn't seem to be working (or if it is working it must take ages).  Is this a known error?  Have looked everywhere for a solution but no luck so far.

Any assistance would be appreciated as I am new to Prestashop and have probably done something wrong.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @J147julie,

Thanks for your report.
What is the exact issue with `ps_facetedsearch?`
Can you provide us steps to reproduce the issue in a new comment?
What is the exact version of `ps_facetedsearch` did you use?

Thanks!

**Comment by J147julie** [comment]
Hi


Thanks for the reply.  I am using version 3.5.0 with the settings as per the attachment.  When I go to my website front end jujak.co.uk and try to use the faceted search I just get the “waiting” circle for ages and nothing ever comes up.


Thanks









Sent from Windows Mail





From: khouloudbelguith
Sent: ‎Monday‎, ‎27‎ ‎July‎ ‎2020 ‎13‎:‎21
To: PrestaShop/PrestaShop
Cc: J147julie, Mention






Hi @J147julie,

Thanks for your report.
What is the exact issue with ps_facetedsearch?
Can you provide us steps to reproduce the issue in a new comment?
What is the exact version of ps_facetedsearch did you use?

Thanks!

**Comment by khouloudbelguith** [comment]
@J147julie, I tried with your shop and it is OK.
I attached a screen record
https://drive.google.com/file/d/1_8C-f-k5qEmZVdHgYxCEyeITv1J6PPAR/view?usp=sharing
Thanks to check and feedback.

**Comment by J147julie** [comment]
Can you try on the T shirt one and see if it works as this is the one I was looking at as it has more products.


Thanks






Sent from Windows Mail





From: khouloudbelguith
Sent: ‎Monday‎, ‎27‎ ‎July‎ ‎2020 ‎16‎:‎40
To: PrestaShop/PrestaShop
Cc: J147julie, Mention






@J147julie, I tried with your shop and it is OK.
I attached a screen record
https://drive.google.com/file/d/1_8C-f-k5qEmZVdHgYxCEyeITv1J6PPAR/view?usp=sharing
Thanks to check and feedback.

**Comment by J147julie** [comment]
Sorry that was boys - t shirts






Sent from Windows Mail





From: khouloudbelguith
Sent: ‎Monday‎, ‎27‎ ‎July‎ ‎2020 ‎16‎:‎40
To: PrestaShop/PrestaShop
Cc: J147julie, Mention






@J147julie, I tried with your shop and it is OK.
I attached a screen record
https://drive.google.com/file/d/1_8C-f-k5qEmZVdHgYxCEyeITv1J6PPAR/view?usp=sharing
Thanks to check and feedback.

**Comment by J147julie** [comment]
Seems to be when I try “size” or “size range” the problem is occuring






Sent from Windows Mail





From: khouloudbelguith
Sent: ‎Monday‎, ‎27‎ ‎July‎ ‎2020 ‎16‎:‎40
To: PrestaShop/PrestaShop
Cc: J147julie, Mention






@J147julie, I tried with your shop and it is OK.
I attached a screen record
https://drive.google.com/file/d/1_8C-f-k5qEmZVdHgYxCEyeITv1J6PPAR/view?usp=sharing
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
@J147julie, could you please Go to BO => Module manager => search from ps_facetesearch module, configure it.
Try to `Build attributes and features indexes`, `Clear cache`, check and feedback.
![image](https://user-images.githubusercontent.com/16067358/88643742-641bd580-d0c2-11ea-81db-6c0f2748b1ce.png)

Thanks!

**Comment by J147julie** [comment]
Hi,


Thanks for the reply.  I have done the below and still no difference.


Kind Regards


Julie






Sent from Windows Mail





From: khouloudbelguith
Sent: ‎Tuesday‎, ‎28‎ ‎July‎ ‎2020 ‎10‎:‎06
To: PrestaShop/PrestaShop
Cc: J147julie, Mention






@J147julie, could you please Go to BO => Module manager => search from ps_facetesearch module, configure it.
Try to Build attributes and features indexes, Clear cache, check and feedback.
 image 

Thanks!

**Comment by khouloudbelguith** [comment]
@J147julie, I did not manage to reproduce the issue with PS1.7.6.4 and the ps_facetedsearch v3.5.0
[Clothes.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4989007/Clothes.webm.zip)

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
