### ISSUE TITLE
Incorrect order of items in PayPal checkout

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20334]
#### Describe the bug
There is incorrect order of items in Paypal checkout if there is used payment method for Paypal with gift wrapping. It is confusing for the customer, because he can see items in different order also with different subtotal amount. 

#### Expected behavior
_Shopping cart_
There are displayed all items and subtotal with total correctly.
![image](https://user-images.githubusercontent.com/33311857/88413833-2e35d300-cddc-11ea-993f-70d08523053f.png)

_Paypal checkout_
There is displayed item "1 Gift Wrapping" as 4th item in the cart. It should be displayed as "Gift Wrapping" between Subtotal and Shipping. The Subtotal should be displayed without amount for gift wrapping. Currently there is Subtotal = €165,11 but correct is Subtotal = €164,00.
![image](https://user-images.githubusercontent.com/33311857/88413855-3b52c200-cddc-11ea-9a47-ffe00f1d764c.png)

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by Matt75** [comment]
Can you contact support team of PrestaShop Checkout module, on module configuration page you will see a subtab Help with an email address to contact them.

**Comment by khouloudbelguith** [comment]
Hi @juraj1000,

Thanks for your report.
If your module is PrestaShop Checkout please, contact support team on module configuration page > Subtab Help > there are an email address

I will close this issue.
