### ISSUE TITLE
Cant open the mondules section 

### ISSUE THREAD

**Issue by sha925** [PrestaShop/PrestaShop#20349]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by matks** [comment]
Hello,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report (see https://github.com/PrestaShop/PrestaShop/issues/new?template=1_bug_report.md)

Read more about how we expect the issues to be handled here. Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
