### ISSUE TITLE
Client name field 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#20347]
Hello,

A customer did subscribe on my website with mail address as name  so I tried to reproduce that but all the prestashop form and my APK do not allow me to subscribe like he does.

![image](https://user-images.githubusercontent.com/11594433/88459980-ef158980-ce90-11ea-8466-96fbf236a400.png)
![image](https://user-images.githubusercontent.com/11594433/88459996-0c4a5800-ce91-11ea-9dee-5b879fe93748.png)
![image](https://user-images.githubusercontent.com/11594433/88460008-18361a00-ce91-11ea-990c-f26b8f405fc6.png)
![image](https://user-images.githubusercontent.com/11594433/88460069-72cf7600-ce91-11ea-9582-4c981571ec12.png)
![image](https://user-images.githubusercontent.com/11594433/88460099-b5914e00-ce91-11ea-8c59-1bc883e5e86e.png)

Si I'am aking how he could subscribe with email as name 

Version de PrestaShop : 1.7.6.7
Version du logiciel serveur : Apache
Version de PHP : 7.2.32
Limite de mémoire : 6144M
Temps maximal d'exécution : 9000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by alfonsolr09** [comment]
how did you create an apk?

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/88537826-8eac5680-d00e-11ea-8afb-1f6a57f25d52.png)

Did you use any custom module for creating a user/sign in?

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

We use the on step checkout and even with this module we could not reproduce the issue playstore.ma the same thing on the application 
https://play.google.com/store/apps/details?id=com.playstore.androidapp&hl=fr

![88460099-b5914e00-ce91-11ea-8c59-1bc883e5e86e](https://user-images.githubusercontent.com/11594433/88612756-d28d7300-d083-11ea-88a6-39daf6c6dfda.png)

Regards

**Comment by khouloudbelguith** [comment]
@go-sudo, I did not manage to reproduce the issue with PS1.7.6.7.
It seems that your issue is related to this module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author, they are the only ones to help you with it.
Thanks!
