### ISSUE TITLE
Issue with Customer Reassurance Prestashop module

### ISSUE THREAD

**Issue by C-Ranalletta** [PrestaShop/PrestaShop#20350]
Hi, 
I have a problem with the customer reassurance Prestashop module, I've updated my Prestashop version to 1.7.6.7 but now the module doesn't work correctly.
I tried to uninstall it and after install it again but the system block my download and now I can't use this module.

Could you tell me how can I solve the problem?

**Comment by khouloudbelguith** [comment]
Hi @C-Ranalletta,

What is the exact version of the Customer Reassurance Prestashop module did you use?
>but now the module doesn't work correctly.

Is it an issue in the FO, it is not well displayed or you can't configure it from the BO?

Thanks!

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith now I'm trying to install the version v5.0.0 in my BO but the system leaves an error (like in the photo attached)
![customer reassurance error](https://user-images.githubusercontent.com/43338406/88548120-f1a5e980-d01e-11ea-8650-bce8a6733e31.png)

**Comment by khouloudbelguith** [comment]
@C-Ranalletta, I did not manage to reproduce this issue with PS1.7.6.7.
It is ok in my case
https://drive.google.com/file/d/15nhjTfCIusq3zPGRtS5fDS8xblBnbdaD/view?usp=sharing
Could you please try to install the module clone from GitHub: https://github.com/PrestaShop/blockreassurance/releases/tag/v5.0.0
You can follow these steps:

1. git clone https://github.com/PrestaShop/blockreassurance.git
2. cd blockreassurance/
3. git checkout tags/v5.0.0
4. composer install
5. Compress it and try to upload it.

Thanks!

**Comment by C-Ranalletta** [comment]
Hi @khouloudbelguith I've downloaded the file with the module in github tags v5.0.0 (file attached), and I tried to upload in my BO, but it doesn't recognize the file and leave me this error message " Upload failed, It doesn't seem a valid zip file"
Could you please help me?
 
[blockreassurance-5.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/4986470/blockreassurance-5.0.0.zip)
![Error upload](https://user-images.githubusercontent.com/43338406/88629914-2746e300-d0b0-11ea-91a0-6503b77fad26.png)

**Comment by khouloudbelguith** [comment]
@C-Ranalletta, this method is NOK.
You should follow these [steps](https://github.com/PrestaShop/PrestaShop/issues/20350#issuecomment-664413935) to install dependencies.
You can check with this module
[blockreassurance.zip](https://github.com/PrestaShop/PrestaShop/files/4986917/blockreassurance.zip)

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
HI @C-Ranalletta,

On this GitHub repository there is no software support. This is an open-source project.
You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

I will close the issue.

Thanks for your understanding!

**Comment by Angelo1974** [comment]
Hello everyone and thank you for your work:
I have the prestashop version 1.7.6.7 and the Customer Reassurance version 5.0.0. everything works also changing the color of the icons, but if you change one of the icons it all hangs and interferes, in my case, also with the reviews Comments products.
By resetting the module everything works again but if you change one of the icons it still freezes
