### ISSUE TITLE
Blank value not ackownledged by search on grid pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20353]
#### Describe the bug

Basically the "blank" value is not acknowledged by the filters system, it's ignored.

This issue was reported here https://github.com/PrestaShop/PrestaShop/pull/17215#issuecomment-661745374

#### Expected behavior

When selecting "blank" value on a drop-down list for input filters, it should reset the related filter.

#### Steps to Reproduce

Exemple on the order statuses listing page, report by @SD1982 :

The "send email to customer" filter is not good when selecting the "blank" choice after any other choice its just systematically returns to the choice selected before ( see screen record )
https://drive.google.com/file/d/1yZa7P4AvR_vxKyvl8a8-d-PIrExQFkhT/view?usp=sharing

The behaviour is the same for the "in transit" and "invoice" filters

This should happen on all Symfony pages using this input filter.

#### Additional information

* PrestaShop version: develop

**Comment by khouloudbelguith** [comment]
Hi @matks,

We have already an issue about the blank value reported here: https://github.com/PrestaShop/PrestaShop/issues/18480
I think we need to close this issue.
What do you think?

Thanks!

**Comment by matks** [comment]
Yes indeed.

Closed because duplicate of https://github.com/PrestaShop/PrestaShop/issues/18480
