### ISSUE TITLE
Display quantity in Paypal checkout

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20357]
#### Describe the bug
Hello,
we use Paypal module for payment. If there are more units for one item in the cart then there is displayed quantity and item text in the Paypal checkout, e.g.:
2 Cup of tee

It should be better to display it similar how it is in the PS cart , it means with "x" together with quantity, e.g.;
2x Cup of tee

It would be more easily to understand for the customers what the number means.

I've already written this incident via addons.prestashop.com to Paypal module, but I've got the answer that Paypal only displays data which comes form PS. Therefore it should be necessary to change it in PS. 

#### Steps to Reproduce
1. Create an order in FO with quantity 2 pieces for any item
2. Checkout with Paypal payment method
3. During checkout the PS calls paypal.com
4. Display items in Paypal checkout and you'll see quantity with  item texts

_Paypal checkout_
![image](https://user-images.githubusercontent.com/33311857/88541343-e0f07600-d014-11ea-83f6-5c834f18c3e9.png)

_Prestashop cart_
![image](https://user-images.githubusercontent.com/33311857/88541398-f82f6380-d014-11ea-9c5d-836784aab570.png)

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @juraj1000,

If your module is PrestaShop Checkout please, contact the support team on module configuration page > Subtab Help > there are an email address

Thanks!
