### ISSUE TITLE
CI/CD setup and persistent directory management

### ISSUE THREAD

**Issue by MrKappa** [PrestaShop/PrestaShop#20352]
**Issue:**
I'm working on CI/CD of a custom Prestashop environment and actually I'm facing the issue that I don't know/I can't find the list of folders that contain datas to be preserved during each deployment.

**What I did so far?**
I searched and I've found this #14086 

**What I need?**
Official or at least documented directory structure where data is mantained,

**What I would like?**
Unique folder which contains everything to be preserved during deployments (so I can symlink with a single entry)

**Extra**
Who already faced this problem: how did you solve or managed CI/CD with PS?

Thank you

**Comment by matks** [comment]
Some more informations can be found here https://devdocs.prestashop.com/1.7/development/architecture/

**Comment by khouloudbelguith** [comment]
Hi @MrKappa,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/).

Thank you!
