### ISSUE TITLE
Different settings depending on the language I have on BO

### ISSUE THREAD

**Issue by studio1one** [PrestaShop/PrestaShop#20369]
I have uploaded V. 1.7.6.7 with English language, I then added Swedish language as this will be the main language at the store. I uploaded products, contents, and added a theme from LeoTheme.
Then I notice that some translations was missing, I made a lot of research and then change my BO language in to English, then I saw that several translations that was  not visible in swedish, but now suddenly I found those when I change language on my BO, how come?
I also notice that if I want to expand my store to some more languages I can not work with a language "offline" as we have been able to do with previous versions.

Is this a bug? and is there already a fix for it?

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.32

**Comment by SimonGrn** [comment]
Dear @studio1one ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by khouloudbelguith** [comment]
Hi @studio1one,

Thanks for your report.

>Then I notice that some translations was missing, I made a lot of research and then change my BO language in to English, then I saw that several translations that was not visible in swedish, but now suddenly I found those when I change language on my BO, how come?

The translation of your theme is missing, You can follow this [ticket](https://github.com/PrestaShop/PrestaShop/issues/9818), it is added to our bug roadmap.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9818
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9818

**Comment by studio1one** [comment]
I also notice another issue.
As I wrote I have English and Swedish installed, english is deactivated.
I set my BO language to Swedish, go to a product and see that the language selector part is not there and only Swedish are set...... but when I change BO language to English and go to product page I see english language.
And as I also wrote about that in 1.7.6.7 it's not possible to prepare a language in the store anymore as it was in earlier versions, and I wonder why? and if there is a bug and if there is a fix for it?

![no-selector](https://user-images.githubusercontent.com/16121283/88774350-98a39600-d183-11ea-92e9-5150f97e0ef3.jpg)

And this is how it looks when BO is on Swedish ( english deactivated)
![swedish language](https://user-images.githubusercontent.com/16121283/88774615-f46e1f00-d183-11ea-85ff-dd5f0cbd6cb7.jpg)
But when I turn BO in English and go to same page, suddenly english part is visible on all products but not when I go into each product page.
![english-version](https://user-images.githubusercontent.com/16121283/88775001-6fcfd080-d184-11ea-9bcd-2511fc72ebdd.jpg)

**Comment by khouloudbelguith** [comment]
@studio1one,

>As I wrote I have English and Swedish installed, english is deactivated.
I set my BO language to Swedish, go to a product and see that the language selector part is not there and only Swedish are set...... but when I change BO language to English and go to product page I see english language.

Please follow this issue: https://github.com/PrestaShop/PrestaShop/issues/16626

>But when I turn BO in English and go to same page, suddenly english part is visible on all products but not when I go into each product page.

Issue reported here: https://github.com/PrestaShop/PrestaShop/issues/19777

Thanks!
