### ISSUE TITLE
Prevent deleting address being used in the cart

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#20365]
#### Describe the bug

Bug when delete address when use in shopping cart

#### Expected behavior

You can delete the address you are using in the basket. What is wrong, after that the client will not be able to place an order

#### Steps to Reproduce

1. Create customer
2. Create address
3. Use in shopping cart
4. Delete address by link site.ru/address?id_address=ID&delete=1&token=TOKEN

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @dariusakafest,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
[Untitled_ Jul 28, 2020 4_32 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4988948/Untitled_.Jul.28.2020.4_32.PM.webm.zip)
Thanks to check and feedback.

PS:
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

**Comment by fest73** [comment]
@khouloudbelguith  You forgot set the token

**Comment by khouloudbelguith** [comment]
@dariusakafest, thanks for these clarifications.
Yes, the address is well deleted (issue reproduced with PS1.7.6.7 and PS1.7.7.0beta1)
Ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think of this issue?

Thanks!

**Comment by matks** [comment]
Issue valid and PR merged 😄  thanks @dariusakafest
