### ISSUE TITLE
Product Characteristics

### ISSUE THREAD

**Issue by Stev71287** [PrestaShop/PrestaShop#20374]
I am having an issue with prestashop products add.

When i add a product and add a characteristics, when i save the characteristics is added without problem.

Whenever i save the product, the characteristics is added again and again.

Where can the issue be coming from?

**Comment by SimonGrn** [comment]
Dear @Stev71287 ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
