### ISSUE TITLE
2x thumbnail is not generated when changing/adding category image from BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20373]
1. Enable High-DPI images in Images settings.
2. Make a new category and add an image to it.
3. Go to img/c/ and find the category ID.
4. Only regular images are generated, no 2x formats.

**Thumbnails are generated ONLY IF you go to Image settings, select regenerate categories, and you select DELETE PREVIOUS IMAGES.**

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2
* This PR does not fix it: https://github.com/PrestaShop/PrestaShop/pull/16097

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

You just create an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20218 which is duplicate of #19798, is it?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith The other case was when the image was missing, this is a behavior when making an order.

I will check both cases with the PR you mentioned and let you know.

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks!
Waiting for your feedback.

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/19965

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19798
