### ISSUE TITLE
[BO LinkWidget Page] - Error displayed in page

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#20372]
#### Describe the bug
An error is displayed after opening page link widget
#### Expected behavior

Page correctly displayed

#### Steps to Reproduce

1. Go to 'BO > design > linkwidget'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/48441421/88775481-0bf9d780-d185-11ea-8048-87683e576b2c.png)

#### Additional information

* PrestaShop version: branch develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/ps_linklist/pull/102

To be fully fixed on develop we need to release a patch version of ps_linklist and integrate it into Core

**Comment by NeOMakinG** [comment]
@matks you sure ? 

It seems that https://github.com/PrestaShop/PrestaShop/pull/20381/files doesn't touch ps_linklist at all!

**Comment by matks** [comment]
> @matks you sure ?
> 
> It seems that https://github.com/PrestaShop/PrestaShop/pull/20381/files doesn't touch ps_linklist at all!

Yes I'm sure 😄 

https://github.com/PrestaShop/PrestaShop/pull/20381/ has nothing to do with this issue. A past mistake probably linked them together. The solution is in https://github.com/PrestaShop/ps_linklist/pull/102

**Comment by PierreRambaud** [comment]
We decided to fix the code in both side, in the module and in the Core :)
