### ISSUE TITLE
Multistore - Display the multistore compatibility of modules

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#20382]
As a user I want to know the compatibility of modules with the multistore feature, so I can know which module works or not

#### Describe the solution you'd like

A "learn more" link is displayed for each module in Module catalog and in Module manager, as you can see below:

![capture d'écran_2747](https://user-images.githubusercontent.com/13449658/88803759-3fe8f300-d1ad-11ea-8f44-3590d6a6a636.png)

![capture d'écran_2748](https://user-images.githubusercontent.com/13449658/88804179-d5848280-d1ad-11ea-923f-794a7c6cb42d.png)

This link opens a modal with differents tabs, according on what is filled in the module's product page on the marketplace:

![capture d'écran_2749](https://user-images.githubusercontent.com/13449658/88804122-c7366680-d1ad-11ea-8cab-0a89157698a1.png)

If the multistore compatibility is indicated on the marketplace, we should retrieve and display it in the "Overview" tab, below the existing content, like this:
"**Multistore compatibility:**
=> Yes: this module is compatible with the multistore feature. It can be either:
- configured differently from one store to another;
- configured quickly in the same way on all stores thanks to the all shops context or to the group of shops;
- or even activated for one store and deactivated for another.

=> Partially: this module is partially compatible with the multistore feature. Some of its options might not be available.
=> No: this module is not compatible with the multistore feature. It means that its configuration applies for all stores.
=> Not concerned: this module is not compatible with the multistore feature because it wouldn't be usefull"

**Comment by matthieu-rolland** [comment]
So, we currently don't have this information on our side.

As seen with @matks and @eternoendless , from now on module developers will have to declare the level of compatibility of their module in the code. 

I will fetch the information from the module itself, one consequence of this is that the information is only displayed for modules that can be found on the module manager page, not in the catalog.
