### ISSUE TITLE
Re-visiting order confirmation page is not working 

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20388]
#### Description

1. Make an order as a guest.
2. Refresh page.
3. You get redirected to login.

#### Expected behavior

I should be able to see the order confirmation when reloading the page.

#### Cause

In OrderConfirmationController, on line 65, there is a condition:

```
if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id || $this->secure_key != $order->secure_key) {
    Tools::redirect($redirectLink);
}
```

If ID of order's customer is not the same as the ID of customer in context, redirect to login page.
My order's customer ID is 1775, but context->customer->id is empty, because it gets cleared after order.

#### PR available
https://github.com/PrestaShop/PrestaShop/pull/25395

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
I have the same behavior as PS1.7.6.7.
https://drive.google.com/file/d/1Kx8XsD39oLmyWPMKjALZz3gSJbDciVXC/view?usp=sharing

Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by matks** [comment]
@Hlavtox I did not look at the code, but
```
My order's customer ID is 1775, but context->customer->id is empty.
```
seems the real issue

**Comment by Hlavtox** [comment]
@matks I guess that's the correct behaviour? Do we delete the condition?

**Comment by Hlavtox** [comment]
@khouloudbelguith @matks Will be fixed in https://github.com/PrestaShop/PrestaShop/pull/25395
