### ISSUE TITLE
Dni (Identification Number) Enabled But Not Mandatory in the first part of registration (with B2B Enable)

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#20380]
Dear PretaShop staff,
about a registration page, the dni (in Italian country Codice Fiscale) is not required by default option in the first part of registration, so I'd like to make this field Mandatory in both part.
For clarity, I have enabled the B2B option for business reasons.

**1 - Enable B2B option**
go to Shop parameters --> Customers settings --> Enable B2B mode to **yes**

<img width="1044" alt="Schermata 2020-07-29 alle 13 48 25" src="https://user-images.githubusercontent.com/28685316/88796617-40c85780-d1a2-11ea-832e-9ab26717cb5f.png">

**how to replicate the problem:**
**2 - Required DNI Field**
go to Customers --> Addresses --> Set required fields for this section

<img width="1246" alt="Schermata 2020-07-29 alle 13 43 28" src="https://user-images.githubusercontent.com/28685316/88796175-89334580-d1a1-11ea-8600-3a94c7ca17a5.png">

then check the "**dni**" checkbox

<img width="1030" alt="Schermata 2020-07-29 alle 13 44 09" src="https://user-images.githubusercontent.com/28685316/88796317-b849b700-d1a1-11ea-8f5c-1517bc3cb74f.png">

**3 - Add dni to the italian customers (at the moment we sell just to the Italian country)**
go to international --> location --> countries --> Italy

<img width="1029" alt="Schermata 2020-07-29 alle 13 51 24" src="https://user-images.githubusercontent.com/28685316/88796828-a0266780-d1a2-11ea-8758-559bca9cfb86.png">

and enable dni option, then put the dni into the address format if it isn't already there

![2](https://user-images.githubusercontent.com/28685316/88797016-f09dc500-d1a2-11ea-9609-5eea29f9b4c7.jpg)

In the first part of the register login the dni is still optional

![dni](https://user-images.githubusercontent.com/28685316/88798039-8a19a680-d1a4-11ea-90af-5a727f39a027.jpg)

this field becomes mandatory in the second part, in fact there is no longer the "**optional**" writing and there is an alert about that the field s empty:

![dni-02](https://user-images.githubusercontent.com/28685316/88798243-e54b9900-d1a4-11ea-8b1e-07db09bf60d2.jpg)

<img width="685" alt="Schermata 2020-07-29 alle 14 12 17" src="https://user-images.githubusercontent.com/28685316/88798680-93574300-d1a5-11ea-9089-45481c499c5a.png">

Why is it optional in the first part and mandatory in the second?
is there a specific reason?
Thanks a lot for your support.
Balla

**Comment by khouloudbelguith** [comment]
Hi @ballashop,

Thanks for your report.
>Why is it optional in the first part and mandatory in the second?
is there a specific reason?

In fact, there is a difference between the `Customer` creation section and the `Address` section.
In the second and the third step, you just added the `dni` to the Address format and you set it required in the `Address section` and not for the `Customer section`.
 
![image](https://user-images.githubusercontent.com/16067358/88805113-0b763680-d1af-11ea-8e49-753049f5bc5f.png)


Thanks!

**Comment by ballashop** [comment]
Hi @khouloudbelguith 
thanks for replying me, it could be a nonsense though.
Let me explain better, if I want the DNI field is mandatory, I would like in all parts of the form like this.
Don't you think it's more intuitive?
Even better if the DNI field appears only once.
I have disabled the ability to buy as a guest but only registration mode for business reasons.
how can I remove the DNI field from the first part?
Thanks a lot fo your support.
Balla

**Comment by khouloudbelguith** [comment]
@ballashop,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!

**Comment by ballashop** [comment]
Ok, thanks for your support.
Balla

**Comment by raidnet-ms** [comment]
In 1.7.8 the identification number is translated as DNI in italian (codice fiscale) while it is a french SIRET, at least so it is called in the backend and has a 12 characters limit.

In Italy we do not have SIRET.
We have 16 characters identification number and 11 number VAT (13 if you add nation).

that's clearly a bug.
We can't manage to translate the identification number with CODICE FISCALE because as a SIRET field, it will truncate everything after 12 characters (and our identification number is 16 characters).
We can't manage to rename SIRET into VAT because in the address field we already have another VAT field, and this would be very confusing for customers.

what to do?
