### ISSUE TITLE
Integrity constraint violation on admin customers list when joins address table

### ISSUE THREAD

**Issue by DelecroixQuentin** [PrestaShop/PrestaShop#20390]
#### Describe the bug

When a module joins the `ps_address` table to the customer list retrieval request, when you try to search for a customer by his first or last name, you get the error below because the `lastname`, `firstname` and `company` fields are common to both the `ps_customer` and `ps_address` tables

`email` can also cause an error if a table with an `email` field is join to the `ps_customer` table, so I also added the alias for this field.

![88841129-c7e6f100-d1dd-11ea-91b1-b377028fbbba](https://user-images.githubusercontent.com/8830801/88900051-25ffec80-d24f-11ea-8302-c4eed7cec934.png)

#### Steps to Reproduce

Module to test: [rockettest.zip](https://github.com/PrestaShop/PrestaShop/files/4999980/rockettest.zip)

- install the provided module.
- in the admin, go to Customers > Customers
- try to search for a customer by first or last name (company should also cause an error)
- you should have an error 500
- add the fix
- refresh the customers admin, it should work again

Fix: #20389 

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @DelecroixQuentin ,
Thanks for the report, I did manage to reproduce the issue.
Please stay tuned as our dev team will review your PR.

**Comment by DelecroixQuentin** [comment]
Fix with #19404
