### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by michel03422** [PrestaShop/PrestaShop#20392]
Bonjour
je viens d'installer la version  1.7.6.7 et j'ai plein de bug dans le back office

Cordialement
Michel Bouriez

**Comment by florine2623** [comment]
Hello @michel03422 

Please, send your request in English.
English is the norm on GitHub

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Please be carful when you submitting screenshots, your BO link is visible. Don't send your BO URL in public platform.

Thank you!
