### ISSUE TITLE
The server returned a "500 Internal Server Error". In installing Modules

### ISSUE THREAD

**Issue by pro8181** [PrestaShop/PrestaShop#20399]
Hi, 

When I go to "Ulepszenia" - "Moduły" - "Wybrane" I see below message. I can't edit installing modules on my site tomishop.pl

Also I can't go into "Ulepszenia" - "Wygląd" - "Pozycje" - No page found. I can't change positions of installing modules on my site.

Could you help me?

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @pro8181 ,
Please follow the bug report template, with thorough details of the error.
Once that's done, we will be able to help you.
For now, I close your issue.
Thanks!
