### ISSUE TITLE
Wrong Tax Detail in PDF invoice when there are multiple invoices

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#20393]
### Describe the bug

When an order has more than one Invoice, the invoice's "tax detail" is wrong: it takes all the order's products into account.

### Expected behavior
The invoice's "tax detail" should only take into account the products related to this invoice, not all the products in the order.

### Steps to Reproduce

1 - In FO, add a product to a cart and complete the order.
2 - In BO, go to the order you just made, and click on "generate invoice"
3 - Still in BO Order page, add a product **with a new invoice**

See the two invoices, the Tax Detail takes into account the total of the order's products and not only products in the invoice 

### Screenshots
**The order contains 2 products, on two distinct invoices:**
<img width="766" alt="Capture d’écran 2020-07-30 à 11 34 18" src="https://user-images.githubusercontent.com/1784781/88907310-c4448000-d258-11ea-84d1-fbf47774539d.png">

**The first invoice, see tax details, it takes all the products into account instead of just this invoice's product:**
<img width="755" alt="Capture d’écran 2020-07-30 à 11 34 34" src="https://user-images.githubusercontent.com/1784781/88907370-d32b3280-d258-11ea-93e5-8bbfb1a6fa71.png">

**The second invoice, same problem:**
<img width="763" alt="Capture d’écran 2020-07-30 à 11 34 46" src="https://user-images.githubusercontent.com/1784781/88907405-e1794e80-d258-11ea-8ad9-0b490a9f6863.png">

### Additional information

* PrestaShop version: 1.7.7.x / 1.7.6.x

**Comment by Progi1984** [comment]
Fixed by #20408
