### ISSUE TITLE
No css style backoffice prestashop 1.78 dev branche

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#20402]
I have installed prestashop 1.7.8 dev
butt when i login to the admin panel, there is no style on the page, there is no css loaded.

How is this possible?

Thanks,
Tim

**Comment by matks** [comment]
Did you compile the assets ? https://devdocs.prestashop.com/1.7/development/compile-assets/

**Comment by NeOMakinG** [comment]
Hey @qualityangel,

Since 1.7.8, we don't provide assets builded anymore as it's not a good practice, you've to follow the doc @matks sent before :)

**Comment by florine2623** [comment]
Hi @qualityangel ,
I can't reproduce your issue on PS develop branch :
![Capture d’écran 2020-07-31 à 14 25 33](https://user-images.githubusercontent.com/16019289/89034680-c2062280-d339-11ea-8e79-562ff0a8133e.png)
You need to do the following :
`git clone develop & composer install & make assets`
Thanks!

**Comment by qualityangel** [comment]
> Did you compile the assets ? https://devdocs.prestashop.com/1.7/development/compile-assets/

Again you guys are very helpful thank you so much! Worked like a charm
