### ISSUE TITLE
Tax Setting Presta 1.7.6.7

### ISSUE THREAD

**Issue by DrDetail123** [PrestaShop/PrestaShop#20400]
There is an error in the tax settings at Prestashop 1.7.6.7
It is not possible to save the tax setting. It is always tried to create a new tax rule
![2](https://user-images.githubusercontent.com/69029775/89005589-21960b00-d305-11ea-8e1e-652c3d2f61da.png)
![1](https://user-images.githubusercontent.com/69029775/89005593-22c73800-d305-11ea-8c00-ac8a9b99404a.png)

**Comment by florine2623** [comment]
Hi @DrDetail123 ,
I can't reproduce your issue on PS 1.7.6.7.
Please check my screen record :
https://drive.google.com/file/d/1fhNdc1bntAUHgMnxut5ZtfZR2Lka-Z-V/view

Please state what the steps to reproduce are. 
If it is a migration, which version did you start from ?

**Comment by khouloudbelguith** [comment]
Hi @DrDetail123,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
