### ISSUE TITLE
1.7.6.7 SELECT INPUT HTML ERROR ON ADMIN SITE

### ISSUE THREAD

**Issue by Ironzy** [PrestaShop/PrestaShop#20404]
**<selectid=**"currency_iso_code" name="currency[iso_code]" class="custom-select"><option value="XUA">ADB Unit of Account (XUA)</option><option value="AFN">Afghan Afghani (AFN)</option><option value="ALL">Albanian Lek (ALL)</option><option value="DZD">Algerian Dinar (DZD)</option><option value="AOA">Angolan Kwanza (AOA)</option><option value="ARS">Argentine Peso (ARS)</option><option value="AMD">Armenian Dram (AMD)</option><option value="AWG">Aruban Florin (AWG)</option><option value="AUD">Australian Dollar (AUD)</option><option value="AZN">Azerbaijani Manat (AZN)</option><option value="BSD">Bahamian Dollar (BSD)</option><option value="BHD">Bahraini Dinar (BHD)</option><option value="BDT">Bangladeshi Taka (BDT)</option><option value="BBD">Barbadian Dollar (BBD)</option><option value="BYN">Belarusian Ruble (BYN)</option><option value="BZD">Belize Dollar (BZD)</option><option value="BMD">Bermudan Dollar (BMD)</option><option value="BTN">Bhutanese Ngultrum (BTN)</option><option value="BOB">Bolivian Boliviano (BOB)</option><option value="BOV">Bolivian Mvdol (BOV)</option><option value="BAM">Bosnia-Herzegovina Convertible Mark (BAM)</option><option value="BWP">Botswanan Pula (BWP)</option><option value="BRL">Brazilian Real (BRL)</option><option value="GBP">British Pound (GBP)</option><option value="BND">Brunei Dollar (BND)</option><option value="BGN">Bulgarian Lev (BGN)</option><option value="BIF">Burundian Franc (BIF)</option><option value="XPF">CFP Franc (XPF)</option><option value="KHR">Cambodian Riel (KHR)</option><option value="CAD">Canadian Dollar (CAD)</option><option value="CVE">Cape Verdean Escudo (CVE)</option><option value="KYD">Cayman Islands Dollar (KYD)</option><option value="XAF">Central African CFA Franc (XAF)</option><option value="CLP">Chilean Peso (CLP)</option><option value="CLF">Chilean Unit of Account (UF) (CLF)</option><option value="CNY">Chinese Yuan (CNY)</option><option value="CNH">Chinese Yuan (offshore) (CNH)</option><option value="COP">Colombian Peso (COP)</option><option value="COU">Colombian Real Value Unit (COU)</option><option value="KMF">Comorian Franc (KMF)</option><option value="CDF">Congolese Franc (CDF)</option><option value="CRC">Costa Rican Colón (CRC)</option><option value="HRK">Croatian Kuna (HRK)</option><option value="CUC">Cuban Convertible Peso (CUC)</option><option value="CUP">Cuban Peso (CUP)</option><option value="CZK">Czech Koruna (CZK)</option><option value="DKK">Danish Krone (DKK)</option><option value="DJF">Djiboutian Franc (DJF)</option><option value="DOP">Dominican Peso (DOP)</option><option value="XCD">East Caribbean Dollar (XCD)</option><option value="EGP">Egyptian Pound (EGP)</option><option value="ERN">Eritrean Nakfa (ERN)</option><option value="ETB">Ethiopian Birr (ETB)</option><option value="EUR">Euro (EUR)</option><option value="XBA">European Composite Unit (XBA)</option><option value="XBB">European Monetary Unit (XBB)</option><option value="XBC">European Unit of Account (XBC) (XBC)</option><option value="XBD">European Unit of Account (XBD) (XBD)</option><option value="FKP">Falkland Islands Pound (FKP)</option><option value="FJD">Fijian Dollar (FJD)</option><option value="GMD">Gambian Dalasi (GMD)</option><option value="GEL">Georgian Lari (GEL)</option><option value="GHS">Ghanaian Cedi (GHS)</option><option value="GIP">Gibraltar Pound (GIP)</option><option value="XAU">Gold (XAU)</option><option value="GTQ">Guatemalan Quetzal (GTQ)</option><option value="GNF">Guinean Franc (GNF)</option><option value="GYD">Guyanaese Dollar (GYD)</option><option value="HTG">Haitian Gourde (HTG)</option><option value="HNL">Honduran Lempira (HNL)</option><option value="HKD">Hong Kong Dollar (HKD)</option><option value="HUF">Hungarian Forint (HUF)</option><option value="ISK">Icelandic Króna (ISK)</option><option value="INR">Indian Rupee (INR)</option><option value="IDR">Indonesian Rupiah (IDR)</option><option value="IRR">Iranian Rial (IRR)</option><option value="IQD">Iraqi Dinar (IQD)</option><option value="ILS">Israeli New Shekel (ILS)</option><option value="JMD">Jamaican Dollar (JMD)</option><option value="JPY">Japanese Yen (JPY)</option><option value="JOD">Jordanian Dinar (JOD)</option><option value="KZT">Kazakhstani Tenge (KZT)</option><option value="KES">Kenyan Shilling (KES)</option><option value="KWD">Kuwaiti Dinar (KWD)</option><option value="KGS">Kyrgystani Som (KGS)</option><option value="LAK">Laotian Kip (LAK)</option><option value="LBP">Lebanese Pound (LBP)</option><option value="LSL">Lesotho Loti (LSL)</option><option value="LRD">Liberian Dollar (LRD)</option><option value="LYD">Libyan Dinar (LYD)</option><option value="MOP">Macanese Pataca (MOP)</option><option value="MKD">Macedonian Denar (MKD)</option><option value="MGA">Malagasy Ariary (MGA)</option><option value="MWK">Malawian Kwacha (MWK)</option><option value="MYR">Malaysian Ringgit (MYR)</option><option value="MVR">Maldivian Rufiyaa (MVR)</option><option value="MRO">Mauritanian Ouguiya (MRO)</option><option value="MUR">Mauritian Rupee (MUR)</option><option value="MXV">Mexican Investment Unit (MXV)</option><option value="MXN">Mexican Peso (MXN)</option><option value="MDL">Moldovan Leu (MDL)</option><option value="MNT">Mongolian Tugrik (MNT)</option><option value="MAD">Moroccan Dirham (MAD)</option><option value="MZN">Mozambican Metical (MZN)</option><option value="MMK">Myanmar Kyat (MMK)</option><option value="NAD">Namibian Dollar (NAD)</option><option value="NPR">Nepalese Rupee (NPR)</option><option value="ANG">Netherlands Antillean Guilder (ANG)</option><option value="TWD">New Taiwan Dollar (TWD)</option><option value="NZD">New Zealand Dollar (NZD)</option><option value="NIO">Nicaraguan Córdoba (NIO)</option><option value="NGN">Nigerian Naira (NGN)</option><option value="KPW">North Korean Won (KPW)</option><option value="NOK">Norwegian Krone (NOK)</option><option value="OMR">Omani Rial (OMR)</option><option value="PKR">Pakistani Rupee (PKR)</option><option value="XPD">Palladium (XPD)</option><option value="PAB">Panamanian Balboa (PAB)</option><option value="PGK">Papua New Guinean Kina (PGK)</option><option value="PYG">Paraguayan Guarani (PYG)</option><option value="PEN">Peruvian Sol (PEN)</option><option value="PHP">Philippine Piso (PHP)</option><option value="XPT">Platinum (XPT)</option><option value="PLN">Polish Zloty (PLN)</option><option value="QAR">Qatari Rial (QAR)</option><option value="RON">Romanian Leu (RON)</option><option value="RUB">Russian Ruble (RUB)</option><option value="RWF">Rwandan Franc (RWF)</option><option value="WST">Samoan Tala (WST)</option><option value="SAR">Saudi Riyal (SAR)</option><option value="RSD">Serbian Dinar (RSD)</option><option value="SCR">Seychellois Rupee (SCR)</option><option value="SLL">Sierra Leonean Leone (SLL)</option><option value="XAG">Silver (XAG)</option><option value="SGD">Singapore Dollar (SGD)</option><option value="SBD">Solomon Islands Dollar (SBD)</option><option value="SOS">Somali Shilling (SOS)</option><option value="ZAR">South African Rand (ZAR)</option><option value="KRW">South Korean Won (KRW)</option><option value="SSP">South Sudanese Pound (SSP)</option><option value="XDR">Special Drawing Rights (XDR)</option><option value="LKR">Sri Lankan Rupee (LKR)</option><option value="SHP">St. Helena Pound (SHP)</option><option value="XSU">Sucre (XSU)</option><option value="SDG">Sudanese Pound (SDG)</option><option value="SRD">Surinamese Dollar (SRD)</option><option value="SZL">Swazi Lilangeni (SZL)</option><option value="SEK">Swedish Krona (SEK)</option><option value="CHF">Swiss Franc (CHF)</option><option value="SYP">Syrian Pound (SYP)</option><option value="STN">São Tomé &amp; Príncipe Dobra (2018) (STN)</option><option value="TJS">Tajikistani Somoni (TJS)</option><option value="TZS">Tanzanian Shilling (TZS)</option><option value="THB">Thai Baht (THB)</option><option value="TOP">Tongan Paʻanga (TOP)</option><option value="TTD">Trinidad &amp; Tobago Dollar (TTD)</option><option value="TND">Tunisian Dinar (TND)</option><option value="TRY">Turkish Lira (TRY)</option><option value="TMT">Turkmenistani Manat (TMT)</option><option value="USN">US Dollar (Next day) (USN)</option><option value="USD">US Dollar (USD)</option><option value="UGX">Ugandan Shilling (UGX)</option><option value="UAH">Ukrainian Hryvnia (UAH)</option><option value="AED">United Arab Emirates Dirham (AED)</option><option value="XXX">Unknown Currency (XXX)</option><option value="UYI">Uruguayan Peso (Indexed Units) (UYI)</option><option value="UYU">Uruguayan Peso (UYU)</option><option value="UZS">Uzbekistani Som (UZS)</option><option value="VUV">Vanuatu Vatu (VUV)</option><option value="VEF">Venezuelan Bolívar (VEF)</option><option value="VND">Vietnamese Dong (VND)</option><option value="CHE">WIR Euro (CHE)</option><option value="CHW">WIR Franc (CHW)</option><option value="XOF">West African CFA Franc (XOF)</option><option value="YER">Yemeni Rial (YER)</option><option value="ZMW">Zambian Kwacha (ZMW)</option>      **<small class="form-text">ISO code (e.g. USD for Dollars, EUR for Euros, etc.).</small>
    </selectid="currency_iso_code">**

I'm unable to make any selections due to this.

**Comment by JBWModules** [comment]
Are you using PHP > 7.2.? Please note that Prestashop is not compatible to later versions

**Comment by florine2623** [comment]
Hi @IkeAbrokwah ,
Please follow the bug report template.
You need to give details about the error.
I'll close the issue now, feel free to open a new one when all details of the bug are explained
Thanks!

**Comment by Ironzy** [comment]
I'm using PHP 7.4.7
