### ISSUE TITLE
Url category allowing = character

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#20419]
#### Expected behavior

To give a warning

#### Steps to Reproduce

Steps to reproduce the behaviour:

edit a category url with a = instead of -

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks for your report.
I have the same behavior as PS1.7.6.7.
But, The `=` symbol is not listed as an unsafe character in the URL as you can see [here](https://developers.google.com/maps/documentation/urls/url-encoding#common-characters-that-need-encoding)

Thanks to check and feedback.

**Comment by 01park** [comment]
HI @khouloudbelguith 

I was not sure to report this or not, but I did because the link would not work with a = and Google gave an error.

Maybe there could be a check when only saving a category?

**Comment by khouloudbelguith** [comment]
@01park, with machine shuffle in my case, it is OK.
I tried again with a local shop, I have this error:
![image](https://user-images.githubusercontent.com/16067358/89174124-a5f6c100-d585-11ea-9a0d-519e027c3f4c.png)

You don't have any error?

Thanks!

**Comment by 01park** [comment]
Im not sure what you mean with machine shuffle.

I tried to change in category the link with = instead of - and got no warning. Save was a succes

**Comment by khouloudbelguith** [comment]
@01park, in fact, if the `Accented URL` is enabled => the `{id}={rewrite}` is well saved.
If the `Accented URL` is disabled => the `{id}={rewrite}` is not saved.

I have no error when  `{id}={rewrite}` is well saved.
https://drive.google.com/file/d/1DbXLGw2CoYtyrwitOUvQyUAPEG0g_Ihk/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @01park,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

THanks!
