### ISSUE TITLE
Wrong Base price In Invoice

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#20415]
#### Describe the bug

Invoice is showing the wrong Base price in product tax breakdown when purchasing 2 (or more) products in which one (or more) product is without tax.
https://prnt.sc/tryle8
It is showing correctly if tax rule applied to each product.
https://prnt.sc/trymai

#### Expected behavior

The base price must exclude the product price in which tax rule is not applied.
Like this: https://prnt.sc/tryr6o

#### Steps to Reproduce
>Edit by Khouloud
Steps to reproduce the issue:

1. Create a product with Price tax_excl = Price_tax_inclu = 12.90
2. Create a product with Price tax_excl = 29, Tx rule = 5%
3. Show the variable "$total_tax_excl" in the invoice tax-tab template.
4. Go to FO, Add the last two products to the cart and complete the checkout
5. Go to BO => Orders => change Order status "Payment accepted"
6. Download Invoice
7. Check the base Price

1) Add the first product in the cart in which no tax rule is applied.
2) Add another product in which tax rule is applied.
3) Purchase both products
4) Now download the invoice.
5) You will see that the base price is the summation of both products in tax breakdown.
Which is incorrect
https://prnt.sc/tryle8

**Screenshots**

https://prnt.sc/tryle8

#### Additional information

* PrestaShop version: 1.7.6.5 or later version
* PHP version: 7.0.0

**Comment by khouloudbelguith** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,

Thanks for your report.
Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/14646, is it?

Thanks to check and feedback.

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@khouloudbelguith , It is not a similar issue. Both issues conditions are different.

**Comment by khouloudbelguith** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,

I manage to reproduce the issue with PS1.7.6.7 and the 1.7.7.x branch.
Steps to reproduce the issue:

1. Create a product with Price tax_excl = Price_tax_inclu = 12.90
2. Create a product with Price tax_excl = 29, Tx rule = 5%
3. Show the variable "$total_tax_excl" in the invoice tax-tab template.
4. Go to FO, Add the last two products to the cart and complete the checkout
5. Go to BO => Orders => change Order status "Payment accepted"
6. Download Invoice
7. Check the base Price

![image](https://user-images.githubusercontent.com/16067358/89277301-f54ff680-d644-11ea-841c-16011de98ed7.png)

I’ll add this to the debug roadmap.
@PrestaShop/prestashop-product-team can we add this issue to this [Epic](https://github.com/PrestaShop/PrestaShop/issues/13822)?

Thanks!
