### ISSUE TITLE
Cant complete order/payment

### ISSUE THREAD

**Issue by brb944** [PrestaShop/PrestaShop#20417]
When i am about to finish the order and press pay i get ''no entry'' sign on the button and cant click it (its grayed out ) and under it it says Please make sure you've chosen a payment method and accepted the terms and conditions.
<img width="613" alt="Screenshot_13" src="https://user-images.githubusercontent.com/69077703/89101151-9f3d4200-d3fd-11ea-8945-8d25d5badf82.png">

**Comment by SimonGrn** [comment]
Dear @brb944,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
