### ISSUE TITLE
Prestashop doesn't allow me to download a free virtual product when doing the checkout.

### ISSUE THREAD

**Issue by mmarmucho** [PrestaShop/PrestaShop#20426]
Hello!

I have a virtual product that is free to download. When I do the checkout process, I need to choose a payment method even if it is free. I've configurated my web to pay with Paypal, but when pressing "pay with Paypal", nothing happens. It doesn't bring me to another screen, so I cannot finish the checkout process and therefore it doesn't send the email with the downloadable files.

I attach screenshots.

![Captura de pantalla 2020-08-03 a las 11 07 27](https://user-images.githubusercontent.com/69143778/89166599-958d1900-d57a-11ea-8baa-efb03a1c49fd.png)
![Captura de pantalla 2020-08-03 a las 11 06 49](https://user-images.githubusercontent.com/69143778/89166610-96be4600-d57a-11ea-84e5-d25032e561be.png)
![Captura de pantalla 2020-08-03 a las 11 06 32](https://user-images.githubusercontent.com/69143778/89166611-98880980-d57a-11ea-93ae-535bb8e71ece.png)

Does anyone know where the problem might be?

Thank you in advance to everyone :)

**Comment by khouloudbelguith** [comment]
Hi @mmarmucho,

I did not manage to reproduce the issue with PS1.7.6.7.
https://drive.google.com/file/d/1gzrE9Pqttjp58zc72iRWkFwpDzolwuqZ/view?usp=sharing
If your module is PayPal Official, please contact the support team on Addons: https://addons.prestashop.com/en/contact-us?id_product=1748

PS: You must follow the template to submit a complete bug report. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Thank you!
