### ISSUE TITLE
Erreur Jeton prestashop

### ISSUE THREAD

**Issue by ruby75019** [PrestaShop/PrestaShop#20421]
Bonjour, 
depuis l'installation de la nouvelle version Prestashop, j'ai sans cesse ce message qui apparaît. 

Je ne trouve aucune solution pour resoudre ce problème.

**Comment by SimonGrn** [comment]
Hello,
Please send your request in English. English is the norm on GitHub.
Also please do not post a screenshot with your full admin URL as it is a security issue for your shop.

Thank you
