### ISSUE TITLE
Specific price row disappearing in mysql

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#20423]
#### Describe the bug

ps_specific_price is empty after a few days of updating the specific prices (for example sales)

#### Steps to Reproduce

I have no idea on how to reproduce, if it's a module causing the error, how can I trace what's deleting the rows?

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
