### ISSUE TITLE
Ajax / Server Error for action backupFiles

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#20422]
Hello!
I try to update my PS from 1.7.6.6 to 1.7.6.7 but while back up in process the updating stop.
....
Backup files in progress. 29869 files left
Backup files in progress. 29469 files left
[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " "
![image](https://user-images.githubusercontent.com/50954519/89075411-d02e6000-d386-11ea-89c4-671922484223.png)
And this for a few times. I cant update myPS, pleace help.

* PHP version: 7.1.33

**Comment by estenolotienenadie** [comment]
Hello, were you able to solve this error?
Regards,
Alberto

**Comment by mostrosonido** [comment]
I have the same problem, any suggestions please !

[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " undefined"
