### ISSUE TITLE
Problem with adding a product to the cart

### ISSUE THREAD

**Issue by krzysztof-medpak** [PrestaShop/PrestaShop#20425]
#### Describe the bug

When adding a product to the cart, a message appears that there are not enough products in stock, although in fact they are available.

This problem in particular is easy to cause in private mode. This problem sometimes disappears by itself when you click the add to cart button again.

#### Expected behavior

I would like this problem not to occur with products that are in stock and should be added to the basket.

#### Steps to Reproduce

1. Go to 'https://medpak.com.pl/swanson-ashwagandha-zen-szen-indyjski-450-mg-100-kapsulek'
2. Click on button 'Dodaj do koszyka (Add to cart)'
3. See error in right corner.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 
![Opera Zrzut ekranu_2020-08-03_081812_medpak com pl](https://user-images.githubusercontent.com/69137333/89152320-37a10700-d563-11ea-8bdb-5552dd565f19.png)
7.2.31

**Comment by khouloudbelguith** [comment]
Hi @krzysztof-medpak,

I did not manage to reproduce the issue
[Swanson Ashwagandha (żeń-szeń indyjski) 450 mg - 100 kapsułek.webm.zip](https://github.com/PrestaShop/PrestaShop/files/5014721/Swanson.Ashwagandha.zen-szen.indyjski.450.mg.-.100.kapsulek.webm.zip)
On this github repository there is no software support. This is an open source project.
In fact, this github repository is not free a software support area, but a bug tracker.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!
