### ISSUE TITLE
Error en Idiomas y País

### ISSUE THREAD

**Issue by PATRICIOALE** [PrestaShop/PrestaShop#20424]
No se me permite cambiar idiomas, tampoco exportar idiomas, cambiar de pais, NADA, active la geolocalización y no me permite cambiar las opciones, incluso cuando ya estaba ACTIVADO, necesito ayuda.
Prestashop 1.7 versión.
![1A](https://user-images.githubusercontent.com/69128538/89136994-5c19c680-d504-11ea-93e5-e2fb8f4ee9ea.JPG)
![7A](https://user-images.githubusercontent.com/69128538/89136996-5d4af380-d504-11ea-9c60-3817865b3632.JPG)
![6A](https://user-images.githubusercontent.com/69128538/89136997-5d4af380-d504-11ea-8828-2fed3bdd2e95.JPG)
![5A](https://user-images.githubusercontent.com/69128538/89136999-5de38a00-d504-11ea-88c1-99b7ee0a1379.JPG)
![4A](https://user-images.githubusercontent.com/69128538/89137000-5de38a00-d504-11ea-84f0-bbdb236ff68b.JPG)
![3A](https://user-images.githubusercontent.com/69128538/89137001-5e7c2080-d504-11ea-8389-158c585a2e8e.JPG)
![2A](https://user-images.githubusercontent.com/69128538/89137002-5f14b700-d504-11ea-9f5d-6a786beb0a56.JPG)

**Comment by SimonGrn** [comment]
Hello,
Please send your request in English. English is the norm on GitHub.

Thank you
