### ISSUE TITLE
Installation ERROR "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory"

### ISSUE THREAD

**Issue by ericyau028** [PrestaShop/PrestaShop#20437]
When installing Prestashop, after the creation of the tables, there's an error

1. When installing via web access, Create file parameters is stricken through, and green
2. Create database tables is in red, installation progress at 12%
3. An error occurred during installation...

1: 00:12:25 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "prestashop:schema:update-without-foreign","message" => "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory"]

![error](https://user-images.githubusercontent.com/69161685/89205890-05d38300-d5eb-11ea-8022-517e800f98aa.jpg)

**Comment by khouloudbelguith** [comment]
Hi @ericyau028,

Thanks for your report.
Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15836
Thanks to follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/15836#issuecomment-538582525), check and feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ericyau028;

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
