### ISSUE TITLE
Product page images should be able to swipe on mobile for classic theme

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#20431]
For mobile browsing images on the product page should be able to swipe, clicking on a picture one by one to time consuming and old fashion.

I know they are modules that offer this, but I believe this should be a feature prestashop should have as its just more efficient and would improve the quality of browsing for the customer.

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by MatShir** [comment]
It's a good idea, it is now an UX standard on website. @PrestaShop/prestashop-designers, It could be integrated into the classic theme revamp, WDYT?

**Comment by prestascott** [comment]
Hi everyone,

Thank you for your report @01park.
Yes, it's a good idea ! Like @MatShir said, it's now common and a standard to have this behavior on mobile. We have already thought about this for the Classic Theme. 👍

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21611
