### ISSUE TITLE
BO - Orders page - Cannot view pack content

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20444]
#### Describe the bug

In the BO => Orders => Order details page => we cannot view pack content

#### Expected behavior

Pack content should be displayed after clicking on the "View pack content" button

#### Steps to Reproduce

1. Create a Pack product which contains some other standard products
2. Go to FO, add this pack to the cart and complete checkout
3. Go to BO => Orders => last created order details page
4. Click on "View pack content" button
5. See error => Nothing happens 

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/89283668-cdb15c00-d64d-11ea-94c4-648018f06aba.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #20461
