### ISSUE TITLE
Create a new Order State or Create a new Order Return State cannot work with empty color

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20441]
#### Describe the bug

On migrated Symfony pages "Create a new Order State" or "Create a new Order Return State" the "color" field can be empty bu the page crashes.

If you create a new "order state" or "order return state" and you do not fill the "color" field, leaving it empty, the page crashes. This is because color is actually needed 😅 

#### Expected behavior

You should not be able to submit the form without providing a valid value for the "color" field.

#### Steps to Reproduce

1. Go to migrated Order State page `/admin-dev/index.php/configure/shop/order-states` then "Add new order status" button
2. Fill in a name but leave "color" field empty
3. Submit the form

5. Go to migrated Order State page `/admin-dev/index.php/configure/shop/order-states` then "Add new order return status" button
6. Fill in a name but leave "color" field empty
7. Submit the form
8. See error

#### Additional information

* PrestaShop version: develop

**Comment by matks** [comment]
PR available https://github.com/PrestaShop/PrestaShop/pull/20442

**Comment by khouloudbelguith** [comment]
Hi @matks,

Issue reproduced in my case also
![image](https://user-images.githubusercontent.com/16067358/89282889-82e31480-d64c-11ea-9acf-1df1b9b0f9c4.png)

THanks!
