### ISSUE TITLE
If ID_product is not defined, we can't find combination by reference

### ISSUE THREAD

**Issue by camlafit** [PrestaShop/PrestaShop#20454]
### Describe the bug

If there is one row in SQL table product_attribute that has id_product = 25 and reference = demo_10

Then if I run `$id = Combination::getIdByReference(25, 'demo_1');` this will return the above record because a LIKE is used in the query instead of a equality.

`$id = Combination::getIdByReference(25, 'demo_1');` should return a result if there is a row that has id_product = 25 and reference = demo_1 not demo_10

<hr>

#### Describe the bug

Actually, we can find a combination by reference only related to a specific product.
We could be retrieve combination in global context without take in consideration a specific product.

> Reported [here](https://github.com/PrestaShop/PrestaShop/issues/26467) by @saiif

Combination::getIdByReference() returns wrong id 

#### Expected behavior

$id = Combination::getIdByReference(500);
return the same id 
$id = Combination::getIdByReference(5000);
cause like is used for the query 

#### Steps to Reproduce

$id = Combination::getIdByReference(500);
return the same id 
$id = Combination::getIdByReference(5000);

-------------------------------------------------------------------------

#### Expected behavior

Search reference without provide a product information
You can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/20454#issuecomment-668689318)
#### Steps to Reproduce

Not relevant

#### Additional information

* PrestaShop version: develop
* PHP version: 7.x

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

Is it similar to this [issue?](https://github.com/PrestaShop/PrestaShop/issues/9727)
Can you please provide us steps to reproduce the issue?

Thanks!

**Comment by SimonGrn** [comment]
Thank you for your issue @camlafit.
Your issue might be related to  #20443 ?

_Please be aware that your PR will only be taken into account if this issue is correctly reproduced and categorized._

**Comment by camlafit** [comment]
hello

@khouloudbelguith indeed could be related to #9727
@SimonGrn indeed could be related also to #20443 

In these two case, search reference looks outside product context (pack and stock)

But I can't confirm as I work on cron service, then I don't use BO in my usecase.

In my usecase I do directly 
```
$id_product_attribute = Combination::getIdByReference(0,$variant->sku)
```

**Comment by khouloudbelguith** [comment]
@camlafit, I did not manage to reproduce the issue with PS1.7.6.7 and I used this script
```
<?php
require dirname(__FILE__).'/config/config.inc.php';
$id_product_attribute = Combination::getIdByReference(1,"teting");
echo $id_product_attribute;

?>
```

I just edited the product_id =1 and I changed the reference of the second combination
![image](https://user-images.githubusercontent.com/16067358/89311555-72479400-d676-11ea-8b74-b0a7404f1c6c.png)

I run the script => `2` is displayed => OK

In your case, the `product_id=0`? I couldn't find any result => this is your main issue?

Thanks!

**Comment by camlafit** [comment]
Hello

With an equivalent test : 
 ```
<?php
require dirname(__FILE__).'/config/config.inc.php';
$id_product_attribute = Combination::getIdByReference(281,"404.03345.010_4");
echo $id_product_attribute."<br/>";

$id_product_attribute = Combination::getIdByReference('',"404.03345.010_4");
echo $id_product_attribute."<br/>";


$id_product_attribute = Combination::getIdByReference(0,"404.03345.010_4");
echo $id_product_attribute."<br/>";

$id_product_attribute = Combination::getIdByReference(null,"404.03345.010_4");
echo $id_product_attribute."<br/>";
```

Without patch I get : 
```
634



```
Looks logic as 634 is only set to id_product = 281

With patch  (behavior expected)
```
634
634
634
634
```

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

Thanks for these clarifications.
So, I think that your issue is an improvement "Although id product is not specified, the search is performed on the combination's reference"
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by camlafit** [comment]
Hello 

Any news about this issue and its PR related ?

Thanks

**Comment by PierreRambaud** [comment]
I see problems with what you're trying to do and also your pull request.
If you don't provide the product_id and because the reference is not unique, you will retrieve a product_attribute_id but maybe not the good one.
The second one is, the method `getIdByReference` is badly designed.
If you have multiple product like: `demo_1`, `demo_3`, `demo_10` and do `getIdByReference(PRODUCT_ID, 'demo_1')` you have a change to get the wrong product_id because of the `LIKE` in the SQL request.


What you probably want is: 

```php
    /**
     * For a given product_attribute reference, returns the product ids.
     *
     * @param string $reference
     *
     * @return int id
     */
    public static function getByReference($reference)
    {
        if (empty($reference)) {
            return [];
        }

        $query = new DbQuery();
        $query->select('pa.id_product_attribute, pa.id_product');
        $query->from('product_attribute', 'pa');
        $query->where('pa.reference = \'' . pSQL($reference) . '\'');

        return Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($query);
    }
```

**Comment by camlafit** [comment]
Hello

I don't understand your example. You talk about product but purpose is about combination. 
This use case is yet present in actual code. If we have a product with two combinations **demo_1** and **demo_10**  we can get only one of these two **id_product_attribute**

About method naming, purpose it to get ipa from reference. We can change it but we don't forget to provide a backward compatibility with existing getByReference method.

**Comment by PierreRambaud** [comment]
The issue is not waiting for dev, we continued in #20455 but since we had no answer we closed it :)

**Comment by saiif** [comment]
Hello
> Hello
> 
> I don't understand your example. You talk about product but purpose is about combination. This use case is yet present in actual code. If we have a product with two combinations **demo_1** and **demo_10** we can get only one of these two **id_product_attribute**
> 
> About method naming, purpose it to get ipa from reference. We can change it but we don't forget to provide a backward compatibility with existing getByReference method.

for compatibility issue improvement can be like this
>    public static function getByReference($reference, $exact = false)
> if ( $excat )  {
> $query->where('pa.reference = \'' . pSQL($reference) . '\'');

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-maintainers a new PR to fix the issue is opened
What do you think? can we change the status of this issue?

Thanks!

**Comment by camlafit** [comment]
Hello

But in this case we break existing behavior. 
If LIKE usage is not correct it's an another problem as initial code use yet this solution. In my mind we have two different problems  combination search (not be specific to a product) and reference restriction search (lazy or exact reference search)
This issue and PR related was to solve only first problem.

**Comment by matks** [comment]
The bad behavior identified by @PierreRambaud has been fixed in https://github.com/PrestaShop/PrestaShop/pull/26475

The behavior "If ID_product is not defined, we can't find combination by reference" is not a bug IMO. You should always have a ID_product. The function does not work if there is no ID_product.

**Comment by camlafit** [comment]
Hi

As reference should be unique is not necessary to provide a restriction related to product context.
As use case we have importation system. In this case we search a combination from its reference at this moment product is not known.

I'm not sure to provide a new method is a good idea. It'll a quasi duplicate code. cf #20455 and https://github.com/PrestaShop/PrestaShop/issues/20454#issuecomment-740755991
