### ISSUE TITLE
Wrong invoice total after editing a product

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#20467]
#### Describe the bug

When a product is edited, the invoice becomes completely false.
FYI: The total summary is correct

#### Expected behavior

To have the right total amount

#### Steps to Reproduce

1. Create cart in the FO: add 1 product, check it out
2. Go to BO, add a discount of 10 EUR (optional step) in the BO
3. From "view an order" page, generate an invoice in the BO (through the button or status)
3. Edit the product to a different price in the BO "view an order" page
4. See the error in the invoice: "total products" is zero

**Screenshots**

![screencapture-file-home-mshirlaw-Downloads-IN000001-30-pdf-2020-08-05-14_58_43](https://user-images.githubusercontent.com/43613217/89415466-2c4d0780-d72c-11ea-9edc-e6bcc3cc9def.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

The same issue with PS1.7.7.x and it is ok in the PS1.7.6.7.

Thanks!

**Comment by matks** [comment]
Hi ! I m trying to reproduce this on 1.7.7.x and I fail to reproduce it. What is the expected error ? The "Total products" equal to zero ?

**Comment by matks** [comment]
1. Create order in the FO
2. Add a discount of 10 EUR (optional step)
=> add the discount from the FO or the BO ?
3. Generate an invoice
=> do you mean "click on invoice button from the FO when logged-in" or "generate invoice from BO" ?
3. Edit the product to a different price
4. See the error in the invoice
=> what error should I see, and where do you fetch the invoice: BO ? FO ?

**Comment by matks** [comment]
OK, I found it.
I was modifying the product price inside the BO "Edit a product" page. But you need to use the dedicated interface INSIDE THE "View an order" page 😄 

I modify the scenario above

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20492
