### ISSUE TITLE
Wrong rounding of the cart rule 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#20462]
If a product at 20EUR is ordered without a discount.
And In the BO order page, you add 10 EUR discount

Then you will see the error, the 10 EUR discount becomes a 9.99 EUR discount

![screenshot_at_10-52-59](https://user-images.githubusercontent.com/43613217/89393114-a8ceee80-d70a-11ea-930b-6c8c78a7977c.png)

Case: 
If the product is at 14.30 EUR, the discount is at 9.99.
BUT you edit the product at 15 EUR, it goes at 10.00

If the product is at 17.00 EUR, the discount is at 9.99.
BUT you edit the product at 18.00 EUR, it goes at 10.00

_Originally posted by @MatShir in https://github.com/PrestaShop/PrestaShop/issues/20397#issuecomment-668510305_

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

Same issue with 1.7.7.x
It is OK with PS1.7.6.7

Thanks!

**Comment by HartLarsson** [comment]
Confirmed on version 1.7.6.7 and is a big problem!

**Comment by MatShir** [comment]
Hi @HartLarsson,
Weird, @khouloudbelguith couldn't reproduce it. Could you provide us your steps to reproduce it in 1.7.6.7?
You might face another issue.

**Comment by khouloudbelguith** [comment]
@MatShir, @HartLarsson,

Steps to reproduce the issue:
1. Create a product with Price tax included= 14.30, Tax rule =20%
2. Go to FO, add the last product created to the cart => complete the order
3. Go to the BO => Orders => View the last Order created
4. Add a new discount 10 euro
5. Try to update the product's price and check the discount value

I attached a screen record

[Your Screencasts - Screencastify.webm.zip](https://github.com/PrestaShop/PrestaShop/files/5027605/Your.Screencasts.-.Screencastify.webm.zip)

Thanks!

**Comment by jolelievre** [comment]
Fixed by #20482
Thank you @atomiix @SD1982
