### ISSUE TITLE
BO - Categories page - An exception is displayed when updating the Root category

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20463]
#### Describe the bug

In the BO => Catalog => Categories page, an exception is displayed when updating the **Root** category
![image](https://user-images.githubusercontent.com/16067358/89396935-7b387400-d70f-11ea-9426-bf503954ac19.png)

#### Expected behavior

Root category should be well updated

#### Steps to Reproduce

After enabling **multistore**, you can edit the Root category following these steps:
1. Go to BO => Shop Parameters => General => Enable multistore
2. Create a new shop
3.  BO => Catalog => Categories page
4. Add a new root category
5. Edit the Root category
![image](https://user-images.githubusercontent.com/16067358/89397454-29dcb480-d710-11ea-9310-9fd18ccdaf4c.png)

Or simply you can follow this link: `/admin-dev/index.php/sell/catalog/categories/1`
6. Save
7. See error

#### Additional information

* PrestaShop version: 1.7.6.0, 1.7.6.7, 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
It is ok with PS1.7.5.1

**Comment by matks** [comment]
Had a look at this

I found that

- category with ID 1 is named "Root" but `is_root_category` is false
- category with ID 2 is named "Home" but `is_root_category` is true

I'm feeling tired ... 😞 

(and all the logic to handle root category relies on whether or not a category is marked `is_root_category` obviously)

**Comment by kpodemski** [comment]
I think that there's no need to be able to edit main PrestaShop category (ID: 1), root categories are always lvl deeper which means that when you want to add a new "Root category", you're adding a subcategory for category ID: 1, I don't really remember any scenario where people would like to have this structure:

```
Root:
- Home
-- Regular category 1
-- Regular category 2

Root 2:
- Home for other shop
-- Regular category for second shop
-- Another category for second shop
```

It is tho very popular to have this structure:

```
Root:
- Home (this is real "main category")
-- Regular category 1
-- Regular category 2

- Home for other shop (this is real "main category")
-- Regular category for second shop
-- Another category for second shop
```

IMHO it's good enough to prevent people from editing category with `level_depth = 0`

**Comment by sowbiba** [comment]
Decision have been made that we no longer can edit the root category of a shop. Root category is the virtual category that is parent of the Home category of the shop. Technically, it's the one which has no parent (id_parent == 0)
