### ISSUE TITLE
google site map installation issues

### ISSUE THREAD

**Issue by sadgamaya** [PrestaShop/PrestaShop#20476]
Hi , I am not sure why I am unable to upload this module in my Prestashop 1.7 version.

https://github.com/PrestaShop/gsitemap/tree/master

![image](https://user-images.githubusercontent.com/29230212/89494767-84d7df80-d7d4-11ea-9c42-5eebccc1fb33.png)

shows this message whenever I try to upload, I unzipped the file and sipped the inside folder , but did not work, please guide.

Appreciate your help.

**Comment by florine2623** [comment]
Hi @sadgamaya ,
I can't reproduce your issue.
On my PS 1.7.6.7, I installed Google Sitemap module :
- git clone https://github.com/PrestaShop/gsitemap.git
- zip gsitemap folder
- install via BO
![Capture d’écran 2020-08-06 à 11 25 46](https://user-images.githubusercontent.com/16019289/89515634-af776780-d7d7-11ea-883a-ec162e04dc9e.png)

The module is natively already available via your BO.
If you need to upgrade it, the button Upgrade will be displayed.
Thanks

**Comment by SimonGrn** [comment]
Dear @sadgamaya 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by sadgamaya** [comment]
Thanks so much I followed the steps of what it showed and it worked, 

Two questions if anyone can help me with

Q1:
The alignment in mobile is like this and unable to scroll the language options.
![image](https://user-images.githubusercontent.com/29230212/89703103-60f7d380-d965-11ea-85d0-bf353cd18e3f.png)

Q2: The language selection window is at footer, is there a way I could bring it to the top.

Appreciate your help.

**Comment by khouloudbelguith** [comment]
Hi @sadgamaya,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!
