### ISSUE TITLE
Productcomments linkchecker

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#20485]
**FO - product page (in french)**
1. Go to 'FO'
2. switch language to FR
3. go to first product page
4. Open console (`F12` in chrome)
5. See error
![image](https://user-images.githubusercontent.com/48441421/84672304-b052f200-af28-11ea-9512-4eb992ae56ff.png)
PR: PrestaShop/productcomments#66

**Comment by matks** [comment]
I reopen this issue as there is one missing piece => this PR https://github.com/PrestaShop/PrestaShop/pull/20547

**Comment by matks** [comment]
Fixed in the Core thansk to https://github.com/PrestaShop/PrestaShop/pull/20547
