### ISSUE TITLE
Prestashop exception: Property customer > Optin is empty

### ISSUE THREAD

**Issue by agentile2020** [PrestaShop/PrestaShop#20480]
Hello,
I need help for following issue. Thank you in advance!

On the front, as a customer:
1. I click on check-out
2. In step 1 - Personal info - I order as a guest and fill in first name, name and email
3. I click on Continue and I get following error:

printscreen here: https://prnt.sc/tus973

```
[PrestaShopException]
Property Customer->optin is empty.
at line 1003 in file classes/ObjectModel.php

998.             }
999. 
1000.             $message = $this->validateField($field, $this->$field);
1001.             if ($message !== true) {
1002.                 if ($die) {
1003.                     throw new PrestaShopException($message);
1004.                 }
1005. 
1006.                 return $error_return ? $message : false;
1007.             }
1008.         }
ObjectModelCore->validateFields - [line 292 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 559 - classes/ObjectModel.php]
ObjectModelCore->add - [line 262 - classes/Customer.php] - [2 Arguments]
CustomerCore->add - [line 516 - classes/ObjectModel.php] - [2 Arguments]
ObjectModelCore->save - [line 195 - classes/form/CustomerPersister.php]
CustomerPersisterCore->create - [line 59 - classes/form/CustomerPersister.php] - [2 Arguments]
CustomerPersisterCore->save - [line 192 - classes/form/CustomerForm.php] - [4 Arguments]
CustomerFormCore->submit - [line 62 - classes/checkout/CheckoutPersonalInformationStep.php]
CheckoutPersonalInformationStepCore->handleRequest - [line 59 - classes/checkout/CheckoutProcess.php] - [1 Arguments]
CheckoutProcessCore->handleRequest - [line 264 - controllers/front/OrderController.php] - [1 Arguments]
OrderControllerCore->initContent - [line 292 - classes/controller/Controller.php]
ControllerCore->run - [line 515 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]
```

#### Additional information

PrestaShop version: 1.7.6.4
PHP version: 7.3.20
Current theme in use: at_movic

**Comment by agentile2020** [comment]
I'm closing the issue as I found the solution.

For info:

1. in the shop parameters / customer settings, I had disable the partner offers

2. in sell / customer settings, there is button "set required fiels for this section"
> click on it & tick off the "partner offers"

That's the point 2. that was causing above issue

Voilà :-)

**Comment by SimonGrn** [comment]
Hello @agentile2020 
Good thing you found a solution !
Small tip: please make sure you follow the template next time (you deleted everything...), as this issue would have been closed as is.

**Comment by khouloudbelguith** [comment]
HI @agentile2020,

Duplicate of https://github.com/PrestaShop/PrestaShop/issues/20801

**Comment by SimonGrn** [comment]
Duplicate of #20801

**Comment by dgdb1** [comment]
> I'm closing the issue as I found the solution.
> 
> For info:
> 
> 1. in the shop parameters / customer settings, I had disable the partner offers
> 2. in sell / customer settings, there is button "set required fiels for this section"
> 
> > click on it & tick off the "partner offers"
> 
> That's the point 2. that was causing above issue
> 
> Voilà :-)

Work great :)
