### ISSUE TITLE
Fatal Error: Interface 'PrestaShop\PrestaShop\Core\Session\SessionInterface' not found

### ISSUE THREAD

**Issue by compagniadelmontale** [PrestaShop/PrestaShop#20481]
**After rollback from a backup because I can't go inside BO after update to 1.7.6.7
now I have this issue:**

My situation:

Informazioni sul server Linux #1 SMP Thu Jun 18 05:28:41 EDT 2020 x86_64

Versione software del server: Apache

Versione di PHP: 7.1.33

Limite di memoria: 128M

Tempo di esecuzione massimo: 480

Dimensione Max. dei file da caricare: 10M

Versione MySQL: 10.1.45-MariaDB-cll-lve
Versione di PrestaShop: 1.7.6.4

my debug in attachment
![debug](https://user-images.githubusercontent.com/69155503/89535468-c5485500-d7f6-11ea-9954-224003598357.jpg)

this is server log:

Error | 86.110.149.90 | 500 | GET /Backoffice/index.php/configure/shop/preferences/preferences?_token=UCDRvES_nvdMqpF_P2QhsYJ8ygwerVjEQC-xdNtqzEM HTTP/1.0 |   |   | 949 | Accesso Apache

2020-08-06 15:11:14 | Warning | 86.110.149.90 |   | mod_fcgid: stderr: PHP Fatal error: Interface 'PrestaShop\\PrestaShop\\Core\\Session\\SessionInterface' not found in /var/www/vhosts/mysiteclasses/CustomerSession.php on line 28, referer: https://mysite/Backoffice/index.php/configure/advanced/system-information/?_token=UCDRvES_nvdMqpF_P2QhsYJ8ygwerVjEQC-xdNtqzEM

I receive back this error ehen I try to load BO page like Category, General setting an Themes setting.
what I can do?

thank You Enrico

**Comment by florine2623** [comment]
Hi @compagniadelmontale ,
Can you clear cache from both BO and manually from FTP ?
Thanks!

**Comment by compagniadelmontale** [comment]
I did it 25 times but nothing change.

**Comment by florine2623** [comment]
What pages are problematic ? Only Back or front as well ?
Did the rollback succeed ? Is your version back to 1.7.6.4 ?
What are the errors from autoupgrade log file ?

**Comment by compagniadelmontale** [comment]
What pages are problematic ? Only Back or front as well ? only BO
Did the rollback succeed ? Is your version back to 1.7.6.4 ? yes
What are the errors from autoupgrade log file ? no error. but after the upgrade BO is impossible to reach. that is why I rolled back.

**Comment by matks** [comment]
@compagniadelmontale is this file in your shop ?
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php

it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.

**Comment by matks** [comment]
You did rollback using auto-upgrade backup files ?

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale is this file in your shop ?
> https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php
> 
> it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.

yes it is in my shop. do I need to delete it?

**Comment by compagniadelmontale** [comment]
> You did rollback using auto-upgrade backup files ?

no, I did roll back from a server backup.

**Comment by compagniadelmontale** [comment]
> > @compagniadelmontale is this file in your shop ?
> > https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php
> > it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.
> 
> yes it is in my shop. do I need to delete it?

![Schermata 2020-08-06 alle 22 34 36](https://user-images.githubusercontent.com/69155503/89580208-49b9c880-d835-11ea-874c-f224edca15ed.png)
this is the content of classes folder.

**Comment by compagniadelmontale** [comment]
> > @compagniadelmontale is this file in your shop ?
> > https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php
> > it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.
> 
> yes it is in my shop. do I need to delete it?

![Schermata 2020-08-06 alle 22 34 36](https://user-images.githubusercontent.com/69155503/89580520-c056c600-d835-11ea-8b2f-70b670c2d439.png)
this is the content of classes folder.

**Comment by matks** [comment]
> > @compagniadelmontale is this file in your shop ?
> > https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php
> > it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.
> 
> yes it is in my shop. do I need to delete it?

It indicates your backup process had an issue. This file belongs to 1.7.6.6, not 1.7.6.4. It should not be inside a 1.7.6.4 backup.

Right now maybe your shop is a 1.7.6.4, maybe your shop is a 1.7.6.6, maybe your shop is a mix of the two. There was an issue with the backup you used 🤔  whether it was the backup itself or the process.

**Comment by compagniadelmontale** [comment]
> > > @compagniadelmontale is this file in your shop ?
> > > https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CustomerSession.php
> > > it's a file added in 1.7.6.6 . It should not be in PS 1.7.6.4. But the error you have seem to indicate this file is in your shop.
> > 
> > 
> > yes it is in my shop. do I need to delete it?
> 
> It indicates your backup process had an issue. This file belongs to 1.7.6.6, not 1.7.6.4. It should not be inside a 1.7.6.4 backup.
> 
> Right now maybe your shop is a 1.7.6.4, maybe your shop is a 1.7.6.6, maybe your shop is a mix of the two. There was an issue with the backup you used 🤔 whether it was the backup itself or the process.

so, what I can do?

**Comment by SimonGrn** [comment]
How did you restore your backup ? Did you wipe everything in your main folder then unzipped your backup, or did you just copy all the files from your backup into your folder ?
If you did #2 that means files created by the 1.7.6.7 installation were not deleted hence your problem.

There is nothing we can do in Github, since your problem is not related to PrestaShop itself but is about your configuration. If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by compagniadelmontale** [comment]
> How did you restore your backup ? Did you wipe everything in your main folder then unzipped your backup, or did you just copy all the files from your backup into your folder ?
> If you did #2 that means files created by the 1.7.6.7 installation were not deleted hence your problem.
> 
> There is nothing we can do in Github, since your problem is not related to PrestaShop itself but is about your configuration. If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

ok Thanks
