### ISSUE TITLE
Bug when cart empty

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#20496]
#### Describe the bug

When cart empty i want call method for get total cart

#### Expected behavior

Return value without notice

#### Steps to Reproduce

1. Create new cart
2. Call method getOrderTotal

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @dariusakafest ,
Could you explain exactly how I can reproduce the issue ?
Is the issue in the front in the cart or are you using the webservices ?
Thanks

**Comment by fest73** [comment]
@florine2623 No, i used in simple php file, created new Cart and call this method

**Comment by khouloudbelguith** [comment]
Hi @dariusakafest,

Could you please provide us the exact file that you used?

Thanks!

**Comment by fest73** [comment]
@khouloudbelguith I created a front controller file in my payment module, where I need a basket to get payment methods, I don't need to create it in the database.

**Comment by khouloudbelguith** [comment]
@dariusakafest, can you provide us a demo module?

Thanks!

**Comment by SimonGrn** [comment]
Hello @dariusakafest 
we cannot validate your PR until you help us reproduce your issue here.
Please provide us the file you used to find this issue.

Thanks in advance.

**Comment by khouloudbelguith** [comment]
Hi @dariusakafest,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
