### ISSUE TITLE
Changing variants trigger error

### ISSUE THREAD

**Issue by Whip** [PrestaShop/PrestaShop#20490]
#### Describe the bug
My products have combinations defined for them but in FO when I change the variant, an error appears saying "An error occurred while processing your request". The variant doesn't change, no information updates.
![2020-08-06 (2)](https://user-images.githubusercontent.com/11595460/89609717-4a367b80-d896-11ea-89a9-90dffb33ce84.jpg)

As far as I've been able to dig around this is my report:
1. Clicking on a variant triggers an ajax request. 
2. The URL itself seems wrong to me. The parameters keep repeating
```
https://www.mywebsite.com/index.php?controller=product&token=3e9851cf6d4c6febd33aeda13787eb5e&id_product=70&id_customization=0&group%5B2%5D=168&qty=1&token=3e9851cf6d4c6febd33aeda13787eb5e&id_product=11&id_customization=0&token=3e9851cf6d4c6febd33aeda13787eb5e&id_product=54&id_customization=0
````
3. The response from server is 500 error. When I enabled debugging, I got this error:
![2020-08-06](https://user-images.githubusercontent.com/11595460/89609723-515d8980-d896-11ea-81f6-09bc27b82ee7.jpg)

I've seen similar issues but they did not help and since I've updated my shop to latest version, they should have been fixed. I can not recall any change we would have made to cause this issue.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by SimonGrn** [comment]
Hello @VeeK727 
thank you for your report. What theme do you use ?
Did you see any error after updating ?
We can't reproduce your issue on our end so we will need all the information you can give us.

**Comment by Whip** [comment]
I'm using a theme called Portfox from Codezeel.
The updates went smoothly without any errors.

Another thing I noticed was that the repeating product ids in the above url is of the products that are appearing in section "Customers who bought this product also bought". Those products also have a div of "product-actions". Maybe the js is picking all three products and combining them together.

Do you have the "Customers who bought this product also bought" section in your test?

**Comment by SimonGrn** [comment]
We tried to reproduce with the Classic theme. We cannot support any third-party theme.
I highly encourage you to contact the developer of the theme.

**Comment by Whip** [comment]
Can you confirm if I change to default theme, the changes on this third party theme are not lost, right? I can switch back to it and have everything like it is currently?

**Comment by khouloudbelguith** [comment]
Hi @VeeK727,

Did you use an Nginx server?
I think your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10178#issuecomment-458094643
Thanks to check and feedback.

**Comment by Whip** [comment]
Its similar but not same. As Simon pointed out, it is indeed a theme issue. I changed to classic theme and no problem there. I contacted the theme developers and they issues a fix for it. I'll mention it here in case someone ends up with the same problem.

in file: **themes/THEMENAME/modules/ps_crosselling/views/templates/hook/ps_crosselling.tp**
Change
`{include file="catalog/_partials/miniatures/product.tpl" product=$product}`
to
`{include file="catalog/_partials/miniatures/product-nocart.tpl" product=$product}`
