### ISSUE TITLE
Hook actionAttributeCombinationSave is not triggered

### ISSUE THREAD

**Issue by c3do** [PrestaShop/PrestaShop#20494]
1. Go to backoffice
2. Add a combination to a product

The hook is called from Combination::setAttributes() that is not used when you add a combination.

**Comment by SimonGrn** [comment]
Dear @c3do
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.
Read more about how we expect the issues to be handled here. Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
