### ISSUE TITLE
You have requested a non-existent service "twig" after upgrading to 1.7.7.x

### ISSUE THREAD

**Issue by elboletaire** [PrestaShop/PrestaShop#20505]
#### Describe the bug

In 1.7.6, in modules' hooks, we'd easily access twig by doing this:

~~~php
$twig = $this->get('twig');
~~~

Allowing us to render custom twig templates on hooks, by just calling `render`:

~~~php
return $this->get('twig')->render(
    '@Modules/associationfeatures/views/templates/admin/Uptakes/details.html.twig',
    compact('uptakes')
);
~~~

After upgrading to 1.7.7 though, all my modules using this way to call twig started crashing with the error `You have requested a non-existent service "twig"`.

![imatge](https://user-images.githubusercontent.com/153305/89710063-2e0f0900-d980-11ea-9bcd-5da1e2d62372.png)

I've been trying to track it down without success, but at least **I've found a workaround** to make my modules work again as expected: instead of using `$this->get` for accessing the container from my hook, I directly get the instance from the `SymfonyContainer`:

~~~php
return SymfonyContainer::getInstance()->get('twig')->render(
    '@Modules/associationfeatures/views/templates/admin/Uptakes/details.html.twig',
    compact('uptakes')
);
~~~

Note that this only happens on modules hooks. But you can still use `$this->get('twig')` on a custom modules' controller.

#### Expected behavior

To be able to properly access the container, as we were able in 1.7.6. 

#### Steps to Reproduce

1. Try to get the instance of twig from a modules' hook via `$this->get('twig')`
2. See error

#### Additional information

* PrestaShop version: 1.7.7.x (commit 5caf1a27c3b7fa0313530182e5a74b25112c5a06)
* PHP version: 7.2

**Comment by matks** [comment]
First of all, thanks for trying 1.77. beta 😄 

It looks like the modules that used to be loaded on Symfony context were loaded on legacy context 🤔   could you mention one of the hooks you are using, to allow me to try to reproduce it ?

It makes me think it might be useful to provide some helper functions to debug this situation. Examples:
```
function myHook($params)
{
    $isItASymfonyContext = $this->isHookSymfonyContext();
    $isContainerAvailable = $this->canUseContainer();
}
```

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by elboletaire** [comment]
> It looks like the modules that used to be loaded on Symfony context were loaded on legacy context :thinking: could you mention one of the hooks you are using, to allow me to try to reproduce it ?

It happened to all my hooks which are actually printed from twig views (using the twig's `renderhook` helper method), i.e.:

- `displayAdminOrderSide`
- `displayAdminCustomers`
- `displayAdminProductsMainStepLeftColumnMiddle`

These are the one I have implemented and all them were crashing, I guess it's related to all hooks loaded from twig views.

**Comment by matks** [comment]
@elboletaire 
I tried with the following test module:
```
class TestModule extends Module
{
    public function __construct()
    {
        $this->name = 'testmodule';
        $this->author = 'matks';
        $this->version = '1.0.0';
        $this->ps_versions_compliancy = ['min' => '1.7.7.0', 'max' => _PS_VERSION_];

        parent::__construct();

        $this->displayName = $this->l('test module matks');
        $this->description = $this->l('test module matks');
    }

    public function hookDisplayAdminOrderSide()
    {
        return $this->get('twig')->render(
            '@Modules/testmodule/views/aaa.html.twig',
            ['hello' => 'hello!']
        );
    }

    public function install()
    {
        return parent::install()
            && $this->registerHook('displayAdminOrderSide');
    }

    public function uninstall()
    {
        return parent::uninstall();
    }
}
```

It works fine 🤔  and your work-around works fine too.

Would it be possible
- to retry after clearing Symfony cache (especially the dumped container) ?
- to retry on a fresh 1.7.7.x instance ?

**Comment by elboletaire** [comment]
Sorry for the (really) late reply, had no time to check it until now.

I've just checked using the nightly build (which is 1.7.8, not 1.7.7, but I guess no changes were made to this), and I can confirm that it works as expected. Using `$this->get('twig')` properly returns the Twig service.

I guess I had some problematic files due to https://github.com/PrestaShop/docs/issues/657

**Comment by kexuejia** [comment]
I just did update prestashop from 1.7.6.5 to 1.7.7.0 via 1-Click Upgrade and get the same issue. so far I managed to fix this only replacing $this->get('twig') with PrestaShop\PrestaShop\Adapter\SymfonyContainer::getInstance()->get('twig') in my module :(

**Comment by elboletaire** [comment]
@kexuejia make a diff between current and new installation and ensure you don't have old prestashop php files in the new installation

**Comment by kexuejia** [comment]
> @kexuejia make a diff between current and new installation and ensure you don't have old prestashop php files in the new installation
no old files :( only new and different .. i checked also default installation  https://download.prestashop.com/download/releases/prestashop_1.7.7.0.zip but no luck ... 
the problem appears only if use own hook in module like recommended here  https://devdocs.prestashop.com/1.7/modules/concepts/hooks/use-hooks-on-modern-pages/
despite that $this->isSymfonyContext() is true it's not possible to get service twig via $this->get('twig')

**Comment by nfacciolo** [comment]
Same problem after install directly 1.7.7.2 

This works: 
`PrestaShop\PrestaShop\Adapter\SymfonyContainer::getInstance()->get('twig');`

This render "You have requested a non-existent service "twig"": 
`$this->get('twig');`

**Comment by nfacciolo** [comment]
find out in two ps modules each time services are needed in display hook, the module uses `SymfonyContainer::getInstance();`

In ps_mbo version 2.0.1 file ps_mbo.php:
    
    /**
     * Override of native function to always retrieve Symfony container instead of legacy admin container on legacy context.
     *
     * {@inheritdoc}
     */
    public function get($serviceName)
    {
        if (null === $this->container) {
            $this->container = SymfonyContainer::getInstance();
        }

        return $this->container->get($serviceName);
    }

And in `ps_linklist` file ps_linklist.php:

    /**
     * @return LinkBlockRepository|LegacyLinkBlockRepository|null
     */
    private function getRepository()
    {
        if (null === $this->repository) {
            try {
                $this->repository = $this->get('prestashop.module.link_block.repository');
            } catch (Throwable $e) {
                try {
                    $container = SymfonyContainer::getInstance();
                    if (null !== $container) {
                        //Module is not installed so its services are not loaded
                        /** @var LegacyContext $context */
                        $legacyContext = $container->get('prestashop.adapter.legacy.context');
                        /** @var Context $shopContext */
                        $shopContext = $container->get('prestashop.adapter.shop.context');
                        $this->repository = new LinkBlockRepository(
                            $container->get('doctrine.dbal.default_connection'),
                            $container->getParameter('database_prefix'),
                            $legacyContext->getLanguages(true, $shopContext->getContextShopID()),
                            $container->get('translator')
                        );
                    }
                } catch (Throwable $e) {
                }
            }
        }

        // Container is not available so we use legacy repository as fallback
        if (!$this->repository) {
            $this->repository = $this->legacyBlockRepository;
        }

        return $this->repository;
    }

**Comment by Renrhaf** [comment]
Same here, used workaround from https://github.com/PrestaShop/PrestaShop/issues/20505#issuecomment-805884349 and https://github.com/PrestaShop/PrestaShop/issues/20505#issuecomment-738790230

**Comment by compsoul** [comment]
It still doesn't work:

public function renderWidget($hookName, array $configuration) 
{
  $this->smarty->assign($this->getWidgetVariables($hookName, $configuration));
   dump(SymfonyContainer::getInstance());
   die;
   //return $this->fetch('module:'.$this->name.'/views/templates/widget/carousel.tpl');
}

 public function getContent()
{
  dump(SymfonyContainer::getInstance());
  die;
  $route = $this->get('router')->generate('form');
  Tools::redirectAdmin($route);
} 
    
The first one returns null. The second, a valid instance.
