### ISSUE TITLE
Does changing anything in admin panel (a config, a new plugin installation) will restart opcache?

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#20504]
I am trying to optimize the performance of 1.7.6.4 instance and I am wondering if I can turn off automatic opcache reload (opcache.validate_timestamps=0).

I suppose that if I enable the OPCache in php.ini then I no longer need stuff like MemCached  / APC / XCached

I have read the docs at https://devdocs.prestashop.com/1.7/scale/optimizations/

**Comment by SimonGrn** [comment]
Hello @ProteanCode 
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
