### ISSUE TITLE
Prestashop 1.7.6.5 reserved product error 

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#20513]
Hello,

I am not sure how we produce that error but when go and check "catalog>stocks" , we have much more reserved products than real reserved products number.
I mean for example the product X has only 1 backorder when we check from orders list , but the reserved product X number is 4 when we check from the catalog>stocks

how can we fix that error pls ?

**Comment by khouloudbelguith** [comment]
Hi @ibrahimfsasmaz,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!
