### ISSUE TITLE
FO - Cannot create an order as a guest - "Password must be between 5 and 72 characters long" but it is optional

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20517]
#### Describe the bug

In the FO, when we try to order as a guest, the **Optional field** password cannot be empty

#### Steps to Reproduce

1. Go to FO => Add some products to the cart
2. Proceed to checkout
3. Create an account without a password (as a guest)
4. Click on continue
5. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/89765961-9cc2a280-daf7-11ea-8df4-4053d66a86f2.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
PIng @PrestaShop/qa-automation

**Comment by matks** [comment]
PR => https://github.com/PrestaShop/PrestaShop/pull/20941/
