### ISSUE TITLE
[Profile Edit][Responsive] unreachable on migrated pages from size 1023x1037

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20522]
#### Describe the bug

Depending on the size of my screen on migrated pages, I am not able to see the profile edit icon

#### Expected behavior

Being able to see the edit profile on various devices with screen size from 1023*1037 and less on migrated pages

#### Steps to Reproduce

1. Open a migrated page and set your screen size to 1023*1037 or less
2. See the profile edit icon isnt appearing 

**Screenshots**
![Capture d’écran 2020-08-10 à 15 39 42](https://user-images.githubusercontent.com/69145330/89790093-b842a300-db21-11ea-9739-ae076aac0518.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/89792578-073e0780-db25-11ea-8f7a-934bb62beeb4.png)

Thanks!

**Comment by NeOMakinG** [comment]
@ngodefroy it looks like it was wanted, as you can access to this page by opening the menu and by clicking there : 

![image](https://user-images.githubusercontent.com/14963751/90870592-1aa96800-e39a-11ea-9c81-0c8dc5948437.png)

The icon is intentionally hidden, wdyt @PrestaShop/prestashop-product-team ?

**Comment by marionf** [comment]
@NeOMakinG 

It seems the profil in the menu is displayed only on legacy pages 

![capture d'écran_2775](https://user-images.githubusercontent.com/13449658/90877025-b4c1de00-e3a3-11ea-8f87-bcb5936916f8.png)

And not on symfony pages

![capture d'écran_2776](https://user-images.githubusercontent.com/13449658/90877047-bf7c7300-e3a3-11ea-9a1a-7db2ace2b712.png)
