### ISSUE TITLE
[BO] [Vouchers]+[Discount] Error 500 when opening the pdf voucher

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20520]
Trying to add a discount when a voucher has been applied generate an error when opening the voucher

#### Expected behavior

I apply a client voucher then give him a 10% discount.
When I go to the vouchers window, I should be able to click on the voucher link and a new tab should open with a pdf voucher.

#### Steps to Reproduce

1. After placing an order, go to orders settings in the BO
2. click on "Add a discount" and place a 10% discount 
3. Update the order status to delivered
4. Click on partial refund 
![Capture d’écran 2020-08-10 à 14 52 03](https://user-images.githubusercontent.com/69145330/89784495-1028dc00-db19-11ea-9bcb-4bcbd7f4eb80.png)
5. Generate partial refund
6. Go into credit notes (vouchers) and click on "download credit note"
See error:
![Capture d’écran 2020-08-10 à 14 54 02](https://user-images.githubusercontent.com/69145330/89784671-57af6800-db19-11ea-9f4a-c6f6a27d4113.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi

Same issue in the PS1.7.7.x

Thanks!

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/20524

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20524
