### ISSUE TITLE
Select box bug on User's Language selection [Admin Panel]

### ISSUE THREAD

**Issue by nasimic** [PrestaShop/PrestaShop#20525]
Version : 1.7.6.7
![image](https://user-images.githubusercontent.com/55084308/89793476-f8f8e700-db36-11ea-8984-7d0b1b690ce8.png)

`<selectid="employee_language" name="employee[language]" class="custom-select">
    <option value="1">English (English)</option>
    <option value="2">Türkçe (Turkish)</option>
</selectid="employee_language">`

To fix add space between 'select' and 'id'

**Comment by khouloudbelguith** [comment]
Hi @nasimic,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
