### ISSUE TITLE
[Order History][Reorder button] the discount isnt reconducted 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20527]
#### Describe the bug

When trying to reorder a product with a discount, the discount isnt reconducted and you have to manually add the discount.

#### Expected behavior

When clicking on the reorder button from order history, the exact same order should be placed 

#### Steps to Reproduce

1. In the FO, Place an order 
2. In the BO, add a discount to that order
3. In the BO, set the status delivery to delivered
4. In the BO, Go to your account/order history
5. In the BO, Find that order and click the reorder button
==> the price isn't including the discount 

**Screenshots**

**Initial ordered with discount applied:**
![Capture d’écran 2020-08-10 à 17 55 15](https://user-images.githubusercontent.com/69145330/89803307-ed0b2600-db32-11ea-994d-341ffb382475.png)

**Reorder with the discount not appearing and not being able to add it on this page**
![Capture d’écran 2020-08-10 à 17 55 50](https://user-images.githubusercontent.com/69145330/89803140-be8d4b00-db32-11ea-87a0-0ebd3b0bccbf.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by SimonGrn** [comment]
Hello @PrestaShop/prestashop-product-team is this the intended behavior ?

**Comment by marionf** [comment]
Hello @ngodefroy 

If you configure a cart rule without a code, it should be reused automatically when you reorder (if the conditions are still met, for exemple expiration date, total quantity, quantity per user etc ...)
If you configure a cart rule with a code, it shouldn't be reused automatically and should be re-added manually by the customer in the cart by clicking on "Have a promo code ?"

Did you used a cart rule with or without a code ?

**Comment by ngodefroy** [comment]
@marionf  I used a cart rule without a code

**Comment by marionf** [comment]
Weird, I tried to reproduce it on 1.7.7.x and the cart rule is well automatically added to the cart

https://drive.google.com/file/d/14eMZhgEFnl4OI_h7AHIAsqAFFobanBXl/view?usp=sharing

Are you sure the total available and total available per user of your cart rule isn't reached ?

**Comment by ngodefroy** [comment]
As discussed with @marionf it's not an issue in this case, thus, Im closing it.
