### ISSUE TITLE
BO - Order / Product price is incorrect after adding a cart rule

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#20533]
#### Describe the bug

In BO after a product price edit if we add a discount the product price is incorrect

#### Expected behavior

The product price should be correct

#### Steps to Reproduce

1. Create a product with price => 14.30 € for example
2. Go to FO and create an order with the previously created product
3. Go to BO and go to the previously created order detail
4. Edit the produt price => The product price is correcly updated in the order detail
5. Add a discount => 10% for exemple
6. See error the product price is the price before the edit in step 4

**Screenshots**

https://drive.google.com/file/d/1iv8Qkd0SF7olOCXoz17H39Hoa--rEifH/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
**PS => for 176 it is not possible to add a discount after a product price edit**
* PHP version: 7.1

**Comment by SD1982** [comment]
@PrestaShop/prestashop-product-team this issue is probably related to #19490

**Comment by marionf** [comment]
Hello @SD1982 
As the behavior is different of 1.7.6 I add the regression label
Yes, it seems related, maybe it will be fixed by https://github.com/PrestaShop/PrestaShop/pull/20145, could you try to reproduce the issue with this PR ?

**Comment by SD1982** [comment]
Hi @marionf I haven't try to reproduce with #20145 but i can check it if the PR is ready for QA :+1:

**Comment by jolelievre** [comment]
I tested it, the PR #20145 fixes this issue

**Comment by marionf** [comment]
I removed this issue of the kanban to keep only the EPIC: https://github.com/PrestaShop/PrestaShop/issues/20161 as the same PR fixes all the issues, this way we keep a better readability of the kanban
