### ISSUE TITLE
Merchant should be able to set delivery information for each combination

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20536]
Related to https://github.com/PrestaShop/PrestaShop/issues/23659

#### Is your feature request related to a problem?

Yes, I cannot set different "label when out of stock and back order allowed" (available_later) text for different combinations of products.

- I am selling a t-shirt with three combinations - S, M, L.
- I have only **S** size in stock.
- The supplier has only **M** in stock.
- The supplier says L will take month to deliver.

How can I tell the customer that ordering M will take 3 days and L is on request?

#### Describe the solution you'd like

Merchant should be able to set available_later text for each combination. 
This text should change in FO when changing the combination. The same as product reference changes. If specific available_later text is set, it displays instead of the product's default one.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by marionf** [comment]
Ping @MatShir

**Comment by MatShir** [comment]
Hi @Hlavtox, 
It is a good improvement, also this input could fulfill by the warehouse system to have automated delivery information displayed for the customer.
How and where this label should be displayed on the product page on FO @prestascott @TristanLDD?

**Comment by Hlavtox** [comment]
@MatShir Hi, well, the first thing is - for all of my clients and our company, I have reverted to old-style of displaying the stock information. I do not find the current solution very good. The **$product.availability_message**, god knows where it comes from, eeeew.

The classic if quantity>0 show **$product.available_now**, else show **$product.available_later** works the best.
We change the available_later value by external update scripts that gets the information from our suppliers XML feeds.

Now, what I wanted to introduce are combination-specific delivery dates.
If a specific delivery information exists for the combination, it will be shown instead of the basic product one. On the same place.
Exactly how product references work.

___________

![out](https://user-images.githubusercontent.com/6097524/94170020-ce1ce500-fe8f-11ea-9c9b-fa404679a2d1.PNG)

**Comment by Hlavtox** [comment]
@MatShir 

I would like the merchant to be able to set these fields specifically for the combinations.
![product](https://user-images.githubusercontent.com/6097524/94170715-b003b480-fe90-11ea-81cd-7195e12ccf74.PNG)

Which is not possible now.
![combination](https://user-images.githubusercontent.com/6097524/94170720-b1cd7800-fe90-11ea-9992-0a5fec104a31.PNG)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/ux-team friendly reminder :wink: could someone please answer @MatShir question :pray: 
Thanks in advance!

**Comment by prestascott** [comment]
Hello everyone, 

Thanks @Hlavtox for the request!

Sorry for the late reply but here I am ✌️

@MatShir This label should be placed between the last combination and the "Add to cart" CTA because customers need to read the infos and be aware of the conditions before clicking the CTA.
See my proposition:
![image](https://user-images.githubusercontent.com/54888056/116877745-a14b6000-ac1e-11eb-83c2-52efa802c6c6.png)
Keeping it simple is the key, we don't need to make this text infos as an alert with background color. 
Customers will notice the text immediately because it appears.

**Comment by Hlavtox** [comment]
@prestascott Perfect!

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Thanks @prestascott for your quick reply :wink: and your proposition :clap: 
So, we have a PM :heavy_check_mark: and UX :heavy_check_mark: I will change the label **`TBS`** to **`To Do`**

Great work guys :rocket: and thanks @Hlavtox for your proposition :wink:

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/29411.
