### ISSUE TITLE
[FO] [INVOICE] display of "quantité" is not correctly aligned 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20545]
#### Describe the bug

On an pdf invoice, "Quantité" is not correctly aligned with the columns

#### Expected behavior

Quantité should be written instead of "Quantit
é" 

#### Steps to Reproduce

1. Go to FO and create an order 
2. Go to the BO => go to the detail of the previously created order
3. Generate the invoice for this order

**Screenshots**

[FA000003 (1).pdf](https://github.com/PrestaShop/PrestaShop/files/5057680/FA000003.1.pdf)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi!

I manage to reproduce the issue with PS1.7.6.7.

Thanks!

**Comment by marionf** [comment]
@NeOMakinG I applied the "front-end" label but I am not sure if it's well a front-end issue, I let you check :)
