### ISSUE TITLE
BO - Order detail / Total products price is not correctly calculated in specifics conditions

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#20542]
#### Describe the bug

In BO order detail the total product price of an order is not correctly recalculated after adding a discount

#### Expected behavior

The total should be correctly recalculated

#### Steps to Reproduce

1. Create 2 products with the following parameters : 
                  product n°1 => 10€ taxes included
                  product n°2 => 15€ taxes included
2. Go to FO and create an order with only the product n°1
3. Go to BO in the order detail of the previously created order => the total product price is correct
4. Add the second product => the total product price is correct
5. Add a discount ( 5€ ) => the total product price is correct
6. Edit the price of one of the product => the total product price is correct
7 Add a second discount ( 10%) => **the total product price is not correct**

**Screenshots**

https://drive.google.com/file/d/1819bZo0X_-n5G3DYgwfbIbsez_A9oZsG/view?usp=sharing

**Other steps to reproduce the issue:**

1. Create an order with a product which has a price of 10 euro for example
2. Go to BO > Orders > Order details page > edit the product price with 100 euro
3. Add a discount
4. see error => total products incorrect / Total incorrect

![image](https://user-images.githubusercontent.com/16067358/90511403-afbf1d80-e15c-11ea-8093-54acc4190cbe.png)

If you delete the discount, the total products incorrect / Total incorrect 
![image](https://user-images.githubusercontent.com/16067358/90511660-13494b00-e15d-11ea-8c8d-9234654aca2f.png)

#### Additional information

* PrestaShop version: 177
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

It is ok with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/89906812-25226f80-dbec-11ea-86e4-95d10a25d1eb.png)

Thanks!

**Comment by SD1982** [comment]
Hi @khouloudbelguith do you add the discount and then edit the product price or edit the product price and after add the discount ?
Because in 176 when i try to reproduce i can't because after editing a product price the "add a discount" button is not present on my side so i can't add the second discount
![2020-08-11_17-36](https://user-images.githubusercontent.com/40635814/89917610-476eba00-dbf9-11ea-988a-f10db5946638.png)

**Comment by khouloudbelguith** [comment]
@SD1982,

>"add a discount" button is not present on my side so i can't add the second discount

Just refresh the page, it should be displayed

Thanks!

**Comment by jolelievre** [comment]
I confirm that the PR https://github.com/PrestaShop/PrestaShop/pull/20145 also fixes this bug :)

**Comment by marionf** [comment]
I removed this issue of the kanban to keep only the EPIC: https://github.com/PrestaShop/PrestaShop/issues/20161 as the same PR fixes all the issues, this way we keep a better readability of the kanban

**Comment by khouloudbelguith** [comment]
Hi!

Other steps to reproduce the issue:
1. Create an order with a product which has a price of 10 euro for example
2. Go to BO > Orders > Order details page > edit the product price with 100 euro
3. Add a discount
4. see error => total products incorrect / Total incorrect

![image](https://user-images.githubusercontent.com/16067358/90511403-afbf1d80-e15c-11ea-8093-54acc4190cbe.png)

If you delete the discount, the total products incorrect / Total incorrect 
![image](https://user-images.githubusercontent.com/16067358/90511660-13494b00-e15d-11ea-8c8d-9234654aca2f.png)

Thanks!
