### ISSUE TITLE
Free Shipping voucher value not updated in Create Order on BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#20557]
#### Describe the bug

In create order on BO, when there is a free shipping voucher added, it's value is not modified when the carrier is changed.

#### Expected behavior

Free shipping voucher value should be updated each time the carrier is modified.

This was OK on 1.7.6.7.

#### Steps to Reproduce

1. Go to BO > Catalog > Discount > Create a discount with Free Shipping
2. Go to BO > Orders > Add new order
3. On the creation order, add the Free Shipping voucher (with default free carrier selected) : Value is 0€
4. Change to a carrier with a fee : Value of the voucher is still 0€, it should be at the value of the carrier fee
5. If doing the opposite, adding the voucher when a carrier with a fee is selected and then change it to a free carrier, the voucher value is still the carrier fee instead of 0 (see screenshots)

**Screenshots**

Screenrecord (between 0:25 and 0:38)

https://drive.google.com/file/d/1FxcNjSSEgkVfaDEqmFJlpocUI_OsyVTN/view?usp=sharing

Screenshots : 

Carrier with fee / Voucher at 0€

![create order free shipping voucher not updated 1](https://user-images.githubusercontent.com/55688534/90017612-17342380-dcac-11ea-867a-b060ce166509.png)

Free carrier / Voucher at 7€

![create order free shipping voucher not updated 2](https://user-images.githubusercontent.com/55688534/90017618-18655080-dcac-11ea-8ac0-65d86415b042.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I manage to reproduce the issue with 1.7.7.x branch
![image](https://user-images.githubusercontent.com/16067358/90023723-59616300-dcb4-11ea-9c6c-0fab1d63cbfb.png)

It is ok with PS1767

Thanks!

**Comment by atomiix** [comment]
I think this one has been fixed by #20755. Can you confirm @khouloudbelguith?

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I tried with 177x, It is OK
https://www.awesomescreenshot.com/video/798777?key=70f47468d663fc9e7d4c11b64688b430
When `177x` is the default carrier
![image](https://user-images.githubusercontent.com/16067358/91732163-2837cc80-eba8-11ea-9345-85e113770063.png)
When `My carrier` is the default carrier
![image](https://user-images.githubusercontent.com/16067358/91732261-48678b80-eba8-11ea-94d0-775fea96d048.png)

Thanks!
