### ISSUE TITLE
inovice issue on 1.7.6.7 after migrating data from 1.5

### ISSUE THREAD

**Issue by denishpatel21** [PrestaShop/PrestaShop#20558]
I'm having issue with invoice. It's not adding product tax details in tax tab like shipping tax details. It was working ok on 1.5 version. Also in the product tab tax rate repeating multiple times. Can you please help me to figure it out. Does is there wrong configuration or any other issue.

Also I have just noticed that customer placed order with multiple items via PayPal free module. I have received email showing he purchased multiple products but in the backoffice and invoice it's only showing one item. it's very strange. 

**Screenshots**
![1](https://user-images.githubusercontent.com/69586675/90021431-e2859380-dcce-11ea-9481-5c4d60a1cd13.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @denishpatel21 ,

Thanks for your report.
What is the exact tool did you use to make the upgrade from PS1.5 to PS1.7.6.7?

Thanks!

**Comment by khouloudbelguith** [comment]
@denishpatel21, If your module is PayPal Official, please contact support team on Addons : https://addons.prestashop.com/en/contact-us?id_product=1748
Thank you!

**Comment by denishpatel21** [comment]
I found issue with bank wire transfer also. I have noticed with test order and found that it shows only one product on order confirmation page + back office order page and in invoice as well. But the total amount shows with all total of all added products in the cart. i have received email and in that it showing all ordered products.

**Comment by khouloudbelguith** [comment]
@denishpatel21, What is the exact tool did you use to make the upgrade from PS1.5 to PS1.7.6.7?

Thanks!

**Comment by denishpatel21** [comment]
i had migrated data on fresh setup with https://addons.prestashop.com/en/data-migration-backup/32298-prestashop-migrator-safely-upgrade-prestashop-to-17.html this module but I don't it because of this module. As issue start from the order confirmation page.

**Comment by denishpatel21** [comment]
I have found below error log in backoffice after ordering multiple products.
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

**Comment by khouloudbelguith** [comment]
@denishpatel21, 
>Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

This is a different issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/9866
>I found issue with bank wire transfer also. I have noticed with test order and found that it shows only one product on order confirmation page + back office order page and in invoice as well. But the total amount shows with all total of all added products in the cart. i have received email and in that it showing all ordered products.

I did not manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/90031256-4ef79700-dcbd-11ea-9ba4-8903cbbbcae3.png)
![image](https://user-images.githubusercontent.com/16067358/90031009-0809a180-dcbd-11ea-88ee-56744611dda2.png)

It must be related to the migration, there is something missing during the migration.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
