### ISSUE TITLE
When reseting ps_customersignin the module isn't hooked anymore in FO

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#20552]
#### Describe the bug

When reseting ps_customersignin the module isn't hooked anymore in FO

#### Steps to Reproduce

1. Go to 'the BO -> module manager
2. Search ps_customersignin
3. Click on reset
4. Go to FO 
5. See that the module isn't hooked anymore 

**Screenshots**

https://drive.google.com/file/d/1YLSILr3OnNyAj4mGjCC2aoxqdokuwDBz/view

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7
* Module version : 2.0.2
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sarahdib,

I manage to reproduce the issue with PS1.7.6.7, develop branch, and ps_customersignin v2.0.2.
![image](https://user-images.githubusercontent.com/16067358/90007582-49895500-dc9b-11ea-9303-90a88699dd79.png)

Related to: https://github.com/PrestaShop/PrestaShop/issues/16968

Thanks!
