### ISSUE TITLE
Backoffice doesn't work after ugrade to 1.7.6.7

### ISSUE THREAD

**Issue by compagniadelmontale** [PrestaShop/PrestaShop#20561]
Hi to everyone,
my
Prestashop version is 1.7.6.7 from 1.7.6.4
php 7.2.32

after upgrade I can't get in to back office.
the log in page is reloading every time without any error.

- I cleaned manually the cache.
- cancelled cookies and browser cache
- debug mode no error

front office works perfectly, I don't know what I can do.

I tried to read old issues about this, but no solutions found!
![DOPOUPGRADE](https://user-images.githubusercontent.com/69155503/90028956-94669500-dcba-11ea-9463-52d76916b744.jpg)
[LOG INSTALLAZIONE.txt](https://github.com/PrestaShop/PrestaShop/files/5063457/LOG.INSTALLAZIONE.txt)
![login](https://user-images.githubusercontent.com/69155503/90029102-bcee8f00-dcba-11ea-8a37-2e4bea07a829.jpg)

any idea?

**Comment by khouloudbelguith** [comment]
Hi @compagniadelmontale,

Did you use a custom module for example `pagespeed` module?
Your issue seems to be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/14371#issuecomment-509956780

THanks!

**Comment by compagniadelmontale** [comment]
> Hi @compagniadelmontale,
> 
> Did you use a custom module for example `pagespeed` module?
> Your issue seems to be similar to this ticket: [#14371 (comment)](https://github.com/PrestaShop/PrestaShop/issues/14371#issuecomment-509956780)
> 
> THanks!

unfortunately, I don't have pagespeed module.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)
=>You can comment this condition: `&& (!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP'))`
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cookie.php#L243


5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
`if ($this->context->cookie->last_activity + 900 < time()) {`

By this:

`if ($this->context->cookie->last_activity + 3600 < time()) {`

Thanks to check & feedback.

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, Here are some things you can try :
> 
> 1/ Clear your browser cache and your cookies - 
> 
> 2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table
> 
> 3/ Manually clear smarty cache: remove all files from /var/cache/
> 
> 4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)
> =>You can comment this condition: `&& (!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP'))`
> https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cookie.php#L243
> 
> 5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
> replace this:
> `if ($this->context->cookie->last_activity + 900 < time()) {`
> 
> By this:
> 
> `if ($this->context->cookie->last_activity + 3600 < time()) {`
> 
> Thanks to check & feedback.


1/ Clear your browser cache and your cookies - **DONE**
 
2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table **EXISTS**

3/ Manually clear smarty cache: remove all files from /var/cache/ **DONE**

 4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP) **AFTER COMMENT I GET A BLANK PAGE BOTH IN BO THAN IN FO**

 5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes. **DONE**


thanks  I tryed but the situation goes worst. I wrote the answer in bold after your suggestions.

Enrico

**Comment by khouloudbelguith** [comment]
@compagniadelmontale,

>4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP) AFTER COMMENT I GET A BLANK PAGE BOTH IN BO THAN IN FO

Thanks for your feedback.
If this solution is not working => uncomment this line and try to clear cache manually by deleting all the folder into var/cache (prod & dev).

Thanks to check and feedback.

**Comment by compagniadelmontale** [comment]
Tried again, but nothing change.

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale,
> 
> > 4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP) AFTER COMMENT I GET A BLANK PAGE BOTH IN BO THAN IN FO
> 
> Thanks for your feedback.
> If this solution is not working => uncomment this line and try to clear cache manually by deleting all the folder into var/cache (prod & dev).
> 
> Thanks to check and feedback.

Tried again, but nothing change.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, could you please check this [solution](https://github.com/PrestaShop/PrestaShop/issues/20079#issuecomment-655625901)

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, could you please check this [solution](https://github.com/PrestaShop/PrestaShop/issues/20079#issuecomment-655625901)
> 
> Thanks!

I tried, but I have both tables in my database.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale,  try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, try to open your shop in an incognito browser.
> You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
> Thanks to check and feedback.

nothing happen! everything like before

**Comment by khouloudbelguith** [comment]
@compagniadelmontale,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale,
> 
> Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * host
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

Prestashop version is 1.7.6.7 from 1.7.6.4
php 7.2.32
server Unix with Apache
no error reported

**Comment by khouloudbelguith** [comment]
@compagniadelmontale,

I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1sswHfuEd41S7dE3dHa4yGTUC0xRid82V/view?usp=sharing
it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.7
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.7 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale,
> 
> I did not manage to reproduce the issue.
> I attached a screen record
> https://drive.google.com/file/d/1sswHfuEd41S7dE3dHa4yGTUC0xRid82V/view?usp=sharing
> it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.7
> The solution is to check if there are missing columns in your database schema.
> You can find the full schema for 1.7.6.7 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/install-dev/data/db_structure.sql
> Thanks to check & feedback.

in the first post I attached the screenshot and the installer log everything seems the same.

I also tried to reload the folders content as suggested in other post.

**Comment by compagniadelmontale** [comment]
> > @compagniadelmontale,
> > I did not manage to reproduce the issue.
> > I attached a screen record
> > https://drive.google.com/file/d/1sswHfuEd41S7dE3dHa4yGTUC0xRid82V/view?usp=sharing
> > it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.7
> > The solution is to check if there are missing columns in your database schema.
> > You can find the full schema for 1.7.6.7 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/install-dev/data/db_structure.sql
> > Thanks to check & feedback.
> 
> in the first post I attached the screenshot and the installer log everything seems the same.
> 
> I also tried to reload the folders content as suggested in other post.

I noticed that in the table structures there is a small difference:

`CREATE TABLE `prefixaccessory` (
  `id_product_1` int(10) UNSIGNED NOT NULL,
  `id_product_2` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

in your structure there is always this line:

` KEY `accessory_product` (`id_product_1`, `id_product_2`)`

could be a problem?

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, your previous PrestaShop 1764, is it a fresh install or an upgrade also from a previous version?

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, your previous PrestaShop 1764, is it a fresh install or an upgrade also from a previous version?
> 
> Thanks!

it is an upgrade, I started to use Prestashop from 1.7.1 always without problem.

**Comment by compagniadelmontale** [comment]
now I am a little bit frustrated, because I continue to receive orders but I can not manage them.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, What is the exact version of the 1-click upgrade did you use to make an upgrade from PS1.7.6.4 to PS1.7.6.7.?

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, What is the exact version of the 1-click upgrade did you use to make an upgrade from PS1.7.6.4 to PS1.7.6.7.?
> 
> Thanks!

it was the last, I checked before upgrade.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, have any special configuration in your shop.
I need all details to reproduce the issue.
Did you use the Multishop context for example?
Have you any custom modules?

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, have any special configuration in your shop.
> I need all details to reproduce the issue.
> Did you use the Multishop context for example?
> Have you any custom modules?
> 
> Thanks!

I don't use multishop, but I I use some custom modules. Everything is working in FO.
is there any way to disable custom modules via database?

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, you can disable the module by renaming the folder.
You cand find your custom module into the path /`PrestaShop_folder/modules/custom_module`, try to rename it `custom_module_old`.

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, you can disable the module by renaming the folder.
> You cand find your custom module into the path /`PrestaShop_folder/modules/custom_module`, try to rename it `custom_module_old`.
> 
> Thanks!

I don't have any custom_module folder.
I just use third party modules.

**Comment by khouloudbelguith** [comment]
@compagniadelmontale, a `custom_module` is just an example.
It is the name of the module that you are using.

Thanks!

**Comment by compagniadelmontale** [comment]
> @compagniadelmontale, a `custom_module` is just an example.
> It is the name of the module that you are using.
> 
> Thanks!

I tried to rename the customs module folder, but nothing change.

can I give you FTP access (in private) to check if something is wrong?

**Comment by khouloudbelguith** [comment]
@compagniadelmontale,

On this GitHub repository there is no software support. This is an open-source project.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.


You can find help also here:

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!
