### ISSUE TITLE
Problems on install

### ISSUE THREAD

**Issue by lexmagnus** [PrestaShop/PrestaShop#20562]
#### Describe the bug

I'm getting error during prestashop installation: "Trying to access array offset on value of type null". I don't change the code.
I already try 3 differents releases. In previous step of configuration I tried connect to DB and says that connection is ok.

#### Expected behavior

I expected a successfully installation

#### Steps to Reproduce

1. Store installation

**Screenshots**

https://ibb.co/g9qf9dX

#### Additional information

* PrestaShop version: 1.7.6.7, 1.7.6.6, 1.7.6.0
* PHP version: 7.4

**Comment by SimonGrn** [comment]
Hello,

PrestaShop 1.7.6.x is only compatible with PHP 7.2 maximum. You need to downgrade your PHP version.
You can check the requirement [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).

I close this issue, thanks for your understanding.
