### ISSUE TITLE
Tools not found when running PrestaShop with Docker for Mac

### ISSUE THREAD

**Issue by ks129** [PrestaShop/PrestaShop#20566]
#### Describe the bug

When trying to run PrestaShop develop branch with Docker for Mac, then I get:
```
prestashop-git_1  | * Launching the installer script...
prestashop-git_1  | PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /var/www/html/config/defines_uri.inc.php:69
prestashop-git_1  | Stack trace:
prestashop-git_1  | #0 /var/www/html/install-dev/init.php(136): require_once()
prestashop-git_1  | #1 /var/www/html/install-dev/index_cli.php(51): require_once('/var/www/html/i...')
prestashop-git_1  | #2 {main}
prestashop-git_1  |   thrown in /var/www/html/config/defines_uri.inc.php on line 69
prestashop-git_1  | 
prestashop-git_1  | Fatal error: Uncaught Error: Class 'Tools' not found in /var/www/html/config/defines_uri.inc.php:69
prestashop-git_1  | Stack trace:
prestashop-git_1  | #0 /var/www/html/install-dev/init.php(136): require_once()
prestashop-git_1  | #1 /var/www/html/install-dev/index_cli.php(51): require_once('/var/www/html/i...')
prestashop-git_1  | #2 {main}
prestashop-git_1  |   thrown in /var/www/html/config/defines_uri.inc.php on line 69
```
this error is not showing in Linux. Tools.php exist in classes folder.

#### Expected behavior

Should install PrestaShop successfully.

#### Steps to Reproduce

Docker for Mac version: 2.3.0.4

1. Run `docker-compose up` in `develop` branch in Mac (Docker for Mac)
2. Wait until this start installing PrestaShop.
3. See error.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop (1.7.8.0)
* PHP version: N/A

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers Could you check please this error on docker for mac ? 
Thank you :)

**Comment by PierreRambaud** [comment]
If someone with a OSx can have a check :sweat_smile:

**Comment by ks129** [comment]
Solved this by upgrading Docker Compose version.
