### ISSUE TITLE
Error in create order when disabling free shipping

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#20560]
#### Describe the bug

In BO > Create order, when an order has a free shipping voucher manually entered, if you try to uncheck the "free shipping" button in the Shipping block, an error is displayed.
If the free shipping button is set to ON again, a second free shipping voucher is created.

#### Expected behavior

When toggling OFF the free shipping button, no error should be displayed, and the voucher should be deleted (or the button should not be switchable).

#### Steps to Reproduce

1. Go to BO > Catalog > Discount > Create a discount with Free Shipping
2. Go to BO > Orders > Add new order
3. On the creation order, add the Free Shipping voucher
4. In "Shipping" block, set "Free shipping" to No : An error is displayed.
5. Switch back to yes : A second "Free Shipping" voucher is created (the total sum of the order is however OK)

**Screenshots**

https://drive.google.com/file/d/1FxcNjSSEgkVfaDEqmFJlpocUI_OsyVTN/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by atomiix** [comment]
This one should be fixed by #20755. @Robin-Fischer-PS can you have a look?

**Comment by Robin-Fischer-PS** [comment]
Yep @atomiix , it's fixed by #20755 ! Thanks :)
