### ISSUE TITLE
In French installer, bottom link "Contactez-nous" returns a 404 page when clicked

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20578]
#### Describe the bug

In French installer, bottom link "Contactez-nous" returns a 404 page https://www.prestashop.com/fr/contact-us when clicked

#### Expected behavior

Link returns a valid page

#### Steps to Reproduce

1. Install PrestaShop, select French as installer language
2. See link "Contactez nous" in the bottom (see screenshot)
3. Click link
4. You reach 404 page https://www.prestashop.com/fr/contact-us

**Screenshots**

![Capture d’écran 2020-08-13 à 15 26 23](https://user-images.githubusercontent.com/3830050/90140147-99d6e480-dd79-11ea-992a-2f1878263091.png)

**Comment by matks** [comment]
Tested on PS 177 but I guess same for develop

**Comment by Sinepel** [comment]
@matks 
I think it's the same problem on other languages.
Example: https://www.prestashop.com/de/contact-us should be https://www.prestashop.com/de/kontakt

`contact-us` is hard-coded :'( 

Should we make a `getContactLink` function in `InstallControllerHttp` with isocode link mapping? By default, return to EN if no isocode?

**Comment by matks** [comment]
I think URL https://www.prestashop.com/contact (without locale) should match the user IP to a locale then redirect user to the right place. We should only send user to the main URL and let prestashop.com send him wherever eligible 🤔 .

I tried using a proxy to test from Germany for example but I did not got redirected to https://www.prestashop.com/de/kontakt

**Comment by Sinepel** [comment]
@matks 
Me neither.

Do I make the modification in this sense and let you manage the redirection to prestashop.com/contact?

**Comment by matks** [comment]
Please let me reach out to team in charge of prestashop.com first 😉 I need to validate it's possible

**Comment by matks** [comment]
@Sinepel Apparently https://www.prestashop.com/contact is able to detect user locale and insert the right prefix
🇫🇷 => https://www.prestashop.com/fr/contact
🇬🇧 => https://www.prestashop.com/en/contact
🇩🇪 => https://www.prestashop.com/de/contact

But it stays "contact", and not "kontakt" for German for example.

**Comment by matks** [comment]
@Sinepel I see the code is already doing that :/

**Comment by Sinepel** [comment]
@matks No problem, so, we can close ! 👍

**Comment by matks** [comment]
Yes indeed :)
