### ISSUE TITLE
CSRF token invalid when trying to add a product

### ISSUE THREAD

**Issue by delphinelefevre** [PrestaShop/PrestaShop#20583]
I'm trying to add a product.
But i keep getting this message: The CSRF token is invalid. Please try to resubmit the form.
Some fields can not be blank he says, but they aren't.
What can I do to fix this?

**Comment by SimonGrn** [comment]
Dear @delphinelefevre ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
