### ISSUE TITLE
[FO] can't change color of a product: only the url changes

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20587]
# Describe the bug

On a product page, when I change the color of an article, it doesn't change the color on the front, only the url changes

#### Expected behavior

On a product page, when I change the color of an article, I expect to see the color of that article to change to what I set.

#### Steps to Reproduce

1. Go to product page and choose a product (a tshirt would do it) 
2. change the color from black to white or reverse
==>See the URL changing but not the picture of the tshirt according to the color

_Note: The right product go into the basket_ 

**Screenshots**

https://drive.google.com/file/d/1YVlnsvMKtiL9Wcqq2xv996ZzHJ6yocQe/view

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20556
