### ISSUE TITLE
BO - Customers / Wrong redirection after canceling the creating of a new address from the customer detail page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20595]
#### Describe the bug

After canceling the creating of a new address from the customer detail page we are redirected to the addresses list instead of the customer detail page

#### Expected behavior

We should be redirected to the customer detail page

#### Steps to Reproduce

1. Go to Customers => Customers
2. Select any customer and go to the customer detail page
3. Scroll down to the bottom of the page and in the address block click on the + icon to add a new address
4. Click on **Cancel** button
5. See Error => redirected to the addresses list page instead of the customer detail page

**Screenshots**

develop/ 1.7.7.x => NOK
https://drive.google.com/file/d/1uLRHXQDSp2vy58oO6Uy2RY9X8y4lLmyV/view?usp=sharing
1.7.6.7=> OK
https://drive.google.com/file/d/1gis090tKY8oGIDaNmycR3WPnX_pm4SLo/view?usp=sharing
#### Additional information

* PrestaShop version: 1.7.7.X, develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/19912

**Comment by Progi1984** [comment]
Fixed by #20603
