### ISSUE TITLE
optin is required

### ISSUE THREAD

**Issue by James7004** [PrestaShop/PrestaShop#20590]
Hi I have turn this off in my back office and still seem to be having issues 
when customers try and check out it come up with 

Error optin is required

**Comment by SimonGrn** [comment]
Dear @James7004 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
