### ISSUE TITLE
Live Edit not working in development branch due to config/smartyfront.config.inc.php

### ISSUE THREAD

**Issue by Zev23** [PrestaShop/PrestaShop#206]
#### The issue

When enter into Live Edit mode from admin backend, the FO page source shows one of the javascript variable _confirmClose_ has early string termination due to the word "won't":

> **Warning**: Invalid argument supplied for foreach() in **~/PrestaShop/controllers/admin/AdminModulesPositionsController.php on line 519**
> {"hasError" : false, "errors" : ""}
###### Output by pagesource

> development (Issue)
> var confirmClose = 'Are you sure? If you close this window, its position **won't** be saved';
> 
> master (Working):
> var confirmClose = 'Are you sure? If you close this window, its position **won\'t** be saved';
###### The difference of these branches:

> development: _config/smartyfront.config.inc.php_
> _return $params['js'] ? $msg : Tools::safeOutput($msg);_
> 
> master: _config/smartyfront.config.inc.php_
> _return $params['js'] ? addslashes($msg) : $msg;_
#### Workaround

What I have modified to make Live Edit work in development branch is to change the return order of expression:

> return $params['js'] ? **Tools::safeOutput($msg)** : $msg;

Output pagesource of the modified version:

> _var confirmClose = 'Are you sure? If you close this window, its position `won&#039;t` be saved';_

**config/smartyfront.config.inc.php** used in research and debug:

> Developement branch: _commit 06b339fab03fdcf3885f678d463baeb4567e72d8_
> Master branch: _commit 768fcf8f84c2cca11f254b36cc7cef557de9a03e_

Can someone please check whether this fixes as i not too sure the overall impact of this change?

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
