### ISSUE TITLE
Wrong display in BO - php 7.4

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#20604]
I had a similiar problem as reffered in the issue https://github.com/PrestaShop/PrestaShop/issues/19345# 

![ps20](https://user-images.githubusercontent.com/3242659/90368649-aeadc380-e06a-11ea-904e-45786dda265f.png)

(Missing space between "select" and "id" )

It is caused by different result of "preg_match_all"  function (php 7.4) in compile twig sources
instead of empty result of second parenthesized subpattern it returns array where offset = -1

![ps19](https://user-images.githubusercontent.com/3242659/90368658-b2d9e100-e06a-11ea-8972-b4254f2be54d.png)

**Fix suggestion** 

in vendor/twig/twig/src/Lexer.php ( and similiar sources that work with empty result of "preg_match_all")

![ps21](https://user-images.githubusercontent.com/3242659/90368689-c127fd00-e06a-11ea-96d9-322f96a90cfd.png)

to add condition with the offset checking :
```
        // push the template text first
        $text = $textContent = substr($this->code, $this->cursor, $position[1] - $this->cursor);
        if (isset($this->positions[2][$this->position][0]) && ($this->positions[2][$this->position][1]>-1)) {
            $text = rtrim($text);
        }
````

**Comment by khouloudbelguith** [comment]
Hi @Eva-F,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

I will close the issue, feel free to open a  new one when needed.
PS: You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Thanks!

**Comment by Eva-F** [comment]
thx for infos
