### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by samvado** [PrestaShop/PrestaShop#20602]
my import page looks like this, I can not use any of the pull down menus

I have win10 on a i7 with 12 gb ram and everything else works just fine
I use xampp latest version

![Clipboard01](https://user-images.githubusercontent.com/44218159/90304580-edab1000-ded6-11ea-9c36-f766814eda6f.jpg)

**Comment by SimonGrn** [comment]
Dear @samvado 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
