### ISSUE TITLE
Wrong validation while uploading product image more than defined size limit.

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#20613]
#### Describe the bug
Wrong validation while uploading product images more than the defined size limit.

#### Expected behavior

It must produce proper validation along with its unit.

#### Steps to Reproduce

1. Go to Advanced parameters and check product image upload size limit https://prnt.sc/u14x0j (currently 2 MB).
2. Now go to the Admin Product page and upload an image size more than 2 MB.
3. Now you will get this message: https://prnt.sc/u14ugs
4. The above message is not correct here size unit is not defined (i.e, it is KB or MB nothing defined).

**Screenshots**
https://prnt.sc/u14ugs

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.7, PS1.7.5.1, and 177x branch.
![image](https://user-images.githubusercontent.com/16067358/90490128-868f9480-e13e-11ea-8c1e-f0b7059205b3.png)
I’ll add this to the debug roadmap.

Related to: https://github.com/PrestaShop/PrestaShop/issues/15183
Thanks!
