### ISSUE TITLE
An error occurs during installation

### ISSUE THREAD

**Issue by denoll** [PrestaShop/PrestaShop#20617]
During installation, the following error occurs and the installation process is terminated.
ERROR:
psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

**Comment by SimonGrn** [comment]
Dear @denoll 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by denoll** [comment]
I don't need it, it's your system, I just pointed out the error to you. Try installing prestashop, and you will understand where and what the error is.It occurs when installing on any server and on any hosting.

**Comment by SimonGrn** [comment]
Hello, 
this is not about if we need your report or not, it's about respecting the people in front of you. We cannot work with your report as it's lacking all the details... we don't even know what version you're using, hence my answer. We have a template, yet you decided to delete everything ?

Please be respectful.

Thank you for your understanding.

Edit: FYI, I install PrestaShop a few times a day and never have I seen this error popping. So we need more details... especially PS version, language, PHP version, etc. All of this is detailed in the template.

**Comment by evgenij-sobolev** [comment]
Hello!
This bug occurs only if you select Russian or Ukrainian language during installation.

This issue is described in more detail here:
https://github.com/PrestaShop/PrestaShop/issues/20519
