### ISSUE TITLE
Improve error message when adding product in existing invoice

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#20612]
#### Describe the bug

In BO, in order view page, when I add a product that already exists in an order I get this error:
`This product is already in your order, please edit the quantity instead.`

This is fine, but when I have multi invoice and I add the product to an invoice that already contains the product I get the same error message, whereas I should get this error message:
`This product is already in the invoice #number, please edit the quantity instead.`

#### Expected behavior

When I add existing product in an invoice I get a more precise error message.

#### Steps to Reproduce

1. Go to an Order view page
2. Go in the document tab and generate invoice if no one exists
3. This will enable the multi-invoice features on the page
4. Add a product to any invoice
5. Add this same product to the same invoice you just added it to
6. You should see an error message (this is expected, this action is not authorize) with the appropriate content

**Screenshots**

![image](https://user-images.githubusercontent.com/13801017/90421207-53ef8880-e0b9-11ea-8be5-adb63af3a9c8.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by LouiseBonnard** [comment]
Hej @jolelievre, okay for the wording _This product is already in the invoice #%number%, please edit the quantity instead._, localized in _Admin.Notifications.Error_, thank you.

**Comment by matks** [comment]
The PR implementing this is doing a lot more than improving an error message.

**Comment by Progi1984** [comment]
Fixed by #20906
