### ISSUE TITLE
i downloaded presta store version 1.7.6.7 and it has some errors

### ISSUE THREAD

**Issue by rehanrida** [PrestaShop/PrestaShop#20611]
SQL query:

CREATE TEMPORARY TABLE `INNODB_SYS_SEMAPHORE_WAITS` (
  `THREAD_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OBJECT_NAME` varchar(4000) DEFAULT NULL,
  `FILE` varchar(4000) DEFAULT NULL,
  `LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_TIME` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_OBJECT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_TYPE` varchar(16) DEFAULT NULL,
  `HOLDER_THREAD_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `HOLDER_FILE` varchar(4000) DEFAULT NULL,
  `HOLDER_LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `CREATED_FILE` varchar(4000) DEFAULT NULL,
  `CREATED_LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WRITER_THREAD` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `RESERVATION_MODE` varchar(16) DEFAULT NULL,
  `READERS` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WAITERS_FLAG` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LOCK_WORD` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LAST_READER_FILE` varchar(4000) DEFAULT NULL,
  `LAST_READER_LINE` int(11) UNSIGNED NOT NU[...]
MySQL said: Documentation

#1118 - Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 
![error](https://user-images.githubusercontent.com/69791743/90411379-439dd480-e0de-11ea-8426-3f91257ec57c.png)

**Comment by khouloudbelguith** [comment]
Hi @rehanrida,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
