### ISSUE TITLE
setCurrentState to the same id_order_state

### ISSUE THREAD

**Issue by bertoferrero** [PrestaShop/PrestaShop#20623]
#### Describe the bug

It happens at every webservice PUT request for updating any order field. The order_state is reprocessed without checking if the order already has the state, sending the state's email and triggering all related hooks.

#### Expected behavior

If the order already has the requested state, avoid to execute the setCurrentState's body

#### Steps to Reproduce

Create an order state with the email sending option set to on, put an order to this state and then, send again the same put request using the WS. You will receive two emails because the order has changed twice to the same state.

#### Additional information

Fix related: https://github.com/PrestaShop/PrestaShop/pull/20622

**Comment by khouloudbelguith** [comment]
Hi @prestaquality,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.7 and the 177x branch.
![image](https://user-images.githubusercontent.com/16067358/90507693-987d3180-e156-11ea-9d64-779887981f47.png)
I’ll add this to the debug roadmap.

Thanks!

**Comment by bertoferrero** [comment]
> 
> 
> Hi @prestaquality,
> 
> Thanks for your report.
> I manage to reproduce the issue with PS1.7.6.7 and the 177x branch.
> ![image](https://user-images.githubusercontent.com/16067358/90507693-987d3180-e156-11ea-9d64-779887981f47.png)
> I’ll add this to the debug roadmap.
> 
> Thanks!

Thank you for your quick testing. I created a pull request for solving this but I don't know how to officialy link this issue to it https://github.com/PrestaShop/PrestaShop/pull/20622

**Comment by khouloudbelguith** [comment]
@prestaquality, Done :smile: 
Thanks!
