### ISSUE TITLE
Out of Stock mail notifications inconsistent between paid & free order

### ISSUE THREAD

**Issue by LiviaButtons** [PrestaShop/PrestaShop#20627]
#### Describe the bug
When allowing purchase of out-of-stock items, the notifications are inconsistent between free and paid items.

- **on purchasing out-of-stock item (or free item+shipping costs):**
   - status changes from: awaiting payment, out of stock (non-paid), payment accepted, out of stock (paid)   
![image](https://user-images.githubusercontent.com/42958830/90518341-f1ed5c80-e166-11ea-8d5f-04115fe044e3.png)
   - client receives only one email : order/payment confirmation despite final status being out-of-stock (paid)
   - if manually clicking to re-send the email for the last status, it does send out 
   - client is directed to confirmation of order page

- **on ordering free out-of-stick item (no shipping costs):**
   - status changes from: payment accepted, to out of stock (paid)
![image](https://user-images.githubusercontent.com/42958830/90518525-2eb95380-e167-11ea-9eb4-60e8620867ca.png)
   - client receives three emaills :  
       - payment accepted
       - order/payment confirmation
       - out of stock (paid)
   - client is redirected to order history page

#### Expected behavior
- same behaviour for paid and free items that are out of stock
- out-of-stock (paid) email to be sent on status change

#### Steps to Reproduce
1. Go to Back office and create two products with a stock of 0 and allowing purchases when the item is out of stock
    - one free product
    - one paid product
2. Go to 'Modules' » 'Alertes par e-mail' » 'Configure' and activate email notifications for clients
3. Go to 'Configure' » 'Paramètres de la boutique' » 'Paramètres de commande' » ' États de commandes'
4. Activate to send e-mails for 'En attente de réapprovisionnement (payé), ID 9 : 
![image](https://user-images.githubusercontent.com/42958830/90519138-efd7cd80-e167-11ea-82cd-3e854782edd7.png)
5. Complete two purchases as a client in the front-office: one of the free product (with free shipping), and one of the paid product

**Screenshots**
Mails for free, out-of-stock product: 
![image](https://user-images.githubusercontent.com/42958830/90519653-9cb24a80-e168-11ea-82c4-339e01a70f64.png)

Mails for paid, out-of-stock product:
![image](https://user-images.githubusercontent.com/42958830/90519758-b8b5ec00-e168-11ea-8b7b-e9a35d5f53d8.png)

#### Additional information
* PrestaShop version: 1.7.6.7
* Alertes par e-mail version: 2.2.0
* PHP version: 7.2.24-0ubuntu0.18.04.6

**Comment by khouloudbelguith** [comment]
Hi @LiviaButtons,

Can you please confirm these steps:
About the not free product.
1. Add this product to cart
2. complete checkout 
3. go to BO => Orders => order details page
4. we have two status "Awaiting check payment" and "On backorder (not paid)"
![image](https://user-images.githubusercontent.com/16067358/90529370-ee140700-e173-11ea-9f28-26b55df28cd2.png)

I have those emails `order_conf`, `outofstock` and `bankwire`
![image](https://user-images.githubusercontent.com/16067358/90529488-126fe380-e174-11ea-85e7-3f28b0f9230e.png)
5. at this step, you changed the status of the order to payment accepted isn't it?
![image](https://user-images.githubusercontent.com/16067358/90529827-6da1d600-e174-11ea-8bf2-a9155cd9d664.png)

At this step, did you change the order status to "On backorder (paid)" manually isn't?

If yes, in my case, I well received the email
I attached a screen record
https://drive.google.com/file/d/1GzL3QnmwIbFi4K80pB7wKHkaFTiYfUYN/view?usp=sharing

Thanks to check and feedback.

**Comment by LiviaButtons** [comment]
Hi @khouloudbelguith, thanks for the quick response. 

I think I should have specified, in this case it's specifically for when a product is "paid" for. So, it's when the client completes the payment (or you run a test payment with status "paid"), that you get to the status of "On backorder (paid)" automatically, without manually triggering it. 

Indeed, upon manually changing the status from that same order to something else (e.g. payment accepted, delivered, etc.) and then back to "On backorder (not paid)" the email does go out. But not when the payment status is handled automatically. 

See screenshot: when I manually change the status the email goes out, but not previously (even though it should have).
![image](https://user-images.githubusercontent.com/42958830/90533669-1eaa6f80-e179-11ea-866b-c27cdac6db4e.png)

**Comment by khouloudbelguith** [comment]
@LiviaButtons,

>So, it's when the client completes the payment (or you run a test payment with status "paid"), that you get the following statusses automatically (not manually changed):

How can I reproduce it (status changed **automatically**)? did you use a custom configuration?

Thanks!

**Comment by LiviaButtons** [comment]
@khouloudbelguith complete a purchase (can be refunded later), or in this case - configure Mollie payment with a test API, and upon payment set the status to paid. Sorry, should've made that more clear. 

So, choose any payment method during checkout: 
![image](https://user-images.githubusercontent.com/42958830/90536517-71395b00-e17c-11ea-9d8b-4a28645e468f.png)

Then, in test mode using Mollie, choose the status you want the product to have: 
![image](https://user-images.githubusercontent.com/42958830/90536581-8615ee80-e17c-11ea-94ac-d73d895e1884.png)

**Comment by khouloudbelguith** [comment]
@LiviaButtons,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by LiviaButtons** [comment]
Hi @khouloudbelguith, seems you're right. It actually makes sense, since the issue only occurs when there's a payment.... Thanks for looking into it! Will take it up with Mollie. 
EDIT : Bug within Mollie that's fixed in the recent release. 

Thanks for your time!

**Comment by khouloudbelguith** [comment]
Hi @LiviaButtons,

Great!
I close the issue, feel free to open a new one when needed.

Thanks!
