### ISSUE TITLE
BO - Order page - a resize window issue in the discount block

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20631]
#### Describe the bug

In the BO => Order => Order details page, the discount is not displayed correctly
![image](https://user-images.githubusercontent.com/16067358/90536015-cc1e8280-e17b-11ea-99d0-602aa1d5bd9f.png)
![image](https://user-images.githubusercontent.com/16067358/90536073-df315280-e17b-11ea-8698-6c6a89196192.png)

#### Expected behavior

It should be well displayed

#### Steps to Reproduce

1. Go to BO => Orders details page
2. add a discount with this name `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
3. save

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7, 177x
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
How would you want to fix this @PrestaShop/prestashop-product-team ?

![image](https://user-images.githubusercontent.com/14963751/90871549-89d38c00-e39b-11ea-9fb1-ad9d100e01d9.png)

I can make the whole table scrollable like on this screen

**Comment by marionf** [comment]
Ping @MatShir

**Comment by MatShir** [comment]
@NeOMakinG idea looks good to me! @TristanLDD WDYT ?

**Comment by NeOMakinG** [comment]
It looks good, but it means that you wont see end columns until you scroll :/

**Comment by prestascott** [comment]
Hi everyone,

Thank you @khouloudbelguith for your report!

It looks good to me but like @NeOMakinG said, users won't see columns until they scroll.
Maybe we can set a max-width for each column so users won't have to scroll too much to see columns?

Wdyt?

**Comment by NeOMakinG** [comment]
@PrestaShop/product-team Is this really in the 1.7.7 scope ? It looks a bit late to be in, but just tell me :)

**Comment by marionf** [comment]
@NeOMakinG It's not in the 1.7.7 kanban and it's not a regression of the 1.7.7, so not in the 1.7.7 scope

**Comment by NeOMakinG** [comment]
Alright, gonna do it on develop

**Comment by PululuK** [comment]
Fixed by #21554
