### ISSUE TITLE
BO - Products page - Incorrect wording when we try to delete a related product, a product feature...

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20632]
#### Describe the bug

In the BO => Catalog => Products page => Product details page => when we try to delete a related product, a product feature, a product brand, a product image, a product combination and bulk delete product combinations, a customization field, a virtual product associated file, a product in a pack, a specific price we have an incorrect wording

![image](https://user-images.githubusercontent.com/16067358/90537942-2a4c6500-e17e-11ea-89b0-fb99174bc6f4.png)

#### Expected behavior

We should have this message "Are you sure you want to delete this item?" in **Admin.Notifications.Warning** (updated by @LouiseBonnard on August 25th)

#### Steps to Reproduce

1. Go to BO => Catalog => Products page
2. Edit any product
3. Scroll down to Related product section
4. add a related product, a product feature, a product brand, a product image, a product combination, a customization field, a virtual product associated file, a product in a pack, a specific price
5. try to remove them (single and bulk for combinations)
6. pop up us is displayed to confirm the deletion
7. see error

**Screenshots**

https://drive.google.com/file/d/1UfHPy6_CHhN3mXO8meh1KJOZUBUJX9SC/view?usp=sharing

**For QA to check, you must try to delete:**
- [ ] A related product
- [ ] A feature
- [ ] A brand
- [ ] An image
- [ ] A generated combination
- [ ] Combinations in bulk
- [ ] A customization field
- [ ] An associated file to a virtual product
- [ ] A product in a pack
- [ ] A specific price
- [ ] A redirection to a category (in SEO tab)
- [ ] A redirection to a product (in SEO tab)
- [ ] The product currently edited

#### Additional information

* PrestaShop version: 1.7.5.1, 1.7.6.7, 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
This issue is reported by @SimonGrn 
Ping @LouiseBonnard @Junebyun 

Thanks!

**Comment by Junebyun** [comment]
Hi @khouloudbelguith I managed to reproduce the issue and indeed the wording is not correct! It should be modified to:
 "_**Are you sure you want to delete this?**_" in _Admin.Notifications.Warning.

**Comment by LouiseBonnard** [comment]
@Junebyun, I would even be more precise and write _Are you sure you want to delete this related product?_, what do you think? Localize it in _Admin.Notifications.Warning_ sounds perfect. ;-)

**Comment by Junebyun** [comment]
> @Junebyun, I would even be more precise and write _Are you sure you want to delete this related product?_, what do you think? Localize it in _Admin.Notifications.Warning_ sounds perfect. ;-)

@LouiseBonnard yes, sounds good to me! :)

**Comment by marionf** [comment]
There is the same bad wording when we try to delete a product feature, a product brand, a product combination and bulk delete product combinations, a customization field, a virtual product associated file

**Comment by marionf** [comment]
@LouiseBonnard @Julievrz 

As this does not only concern related products, do we define a specific message for each element (related products, combinations, brands, features, customizations fields, virtual product associated file) or do we define a standard message for all?

**Comment by Julievrz** [comment]
@marionf @LouiseBonnard  I think the more specific the better, but I don't know how much technical work it represents ? 
If that's too much work, maybe we can stick with a standard message.

**Comment by LouiseBonnard** [comment]
@Julievrz, @marionf, we already have the same kind of generic message, displayed in the confirmation modal window when the user deletes one or several rows in the tables of the back office. See [here](https://github.com/PrestaShop/PrestaShop/issues/17847). Maybe we can stick to this wording or adjust it a bit, like _Are you sure you want to delete this item/it?_.

**Comment by ThanasisMpalatsoukas** [comment]
Hey, i found the mentioned string in /admin-dev/themes/default/js/bundle/product/form.js, i changed it from
"are you sure to delete?" to
"Are you sure you want to delete this item?"

i will submit a pull request in a bit

**Comment by SimonGrn** [comment]
Hello @ThanasisMpalatsoukas 

thank you for your interest in this issue, but we already have a PR in QA state [here](https://github.com/PrestaShop/PrestaShop/pull/21239).

**Comment by ThanasisMpalatsoukas** [comment]
Sorry @SimonGrn  just noticed that now

**Comment by ngodefroy** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21239
