### ISSUE TITLE
upgrade from 1.7.5.2 to 1.7.6.7 failed

### ISSUE THREAD

**Issue by tao0103** [PrestaShop/PrestaShop#20639]
use 1 click extension to upgrade prestashop,but can't enter BO. The error:

(1/1) ClassNotFoundExceptionAttempted to load class "Repository" from namespace "PrestaShop\PrestaShop\Core\Cldr".Did you forget a "use" statement for e.g. "PrestaShop\PrestaShop\Core\Localization\Currency\Repository" or "PrestaShop\PrestaShop\Core\Localization\Locale\Repository"?
--
in AdminController.php line 1949
at AdminControllerCore->initHeader()in AdminLoginController.php line 143
at AdminLoginControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 97

Can someone help me fix it?
Thanks

**Comment by SimonGrn** [comment]
Dear @tao0103 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
