### ISSUE TITLE
Multistore - second store redirect to first store

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#20630]
I created multistore
Main store - plantoflife.com
second store - www.polfinest.com

When open polfinest.com (without www) it redirect to plantoflife.com

I changed polfinest url to be without www but it get into loop and doesn't work.
Same happened when I changed the main url to be with www.

I also added the following to the htaccess but still doesn't work.

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]
</IfModule>

Please I need your help.

* PrestaShop version: 1.7.6.2
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @edensh89,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
