### ISSUE TITLE
Currency sign too close from price on invoice

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#20633]
#### Describe the bug

When opening an invoice, the currency sign is covering the price (see screenshot attached).

#### Expected behavior

To have a bit more space between the currency signe and the price

#### Steps to Reproduce

1. Go to Orders
2. Click on Invoice
3. See the invoice

**Screenshots**
![Capture d’écran 2020-08-18 à 17 55 25](https://user-images.githubusercontent.com/1193727/90538225-8b743880-e17e-11ea-9645-8d3d5d6276ee.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/90539087-b1e6a380-e17f-11ea-976a-b81a25b451e2.png)

I attached a screenshot, thanks to check and feedback.

**Comment by arirangz** [comment]
Hi @khouloudbelguith,

Thanks for your feedback.

Do you have an idea where it can come from then? I didn't override any pdf template.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

On this github repository there is no software support. This is an open source project.
You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!

**Comment by arirangz** [comment]
thanks @khouloudbelguith,

It's probably not a support demand but a bug even if you can't reproduce the issue. The version you are testing is maybe a fresh install and not an upgraded version.

I think it's still interesting for you to know that this issue can happen on upgraded prestashop so it could be fixed for other people. Maybe some templates or css are not updated correctly during prestashop updates.

Let me know if it's still not a bug form your side and I will post on forums instead.

Thanks

**Comment by arirangz** [comment]
@khouloudbelguith 
Hello !
I figured out that this issue happen if you open the pdf with the default preview on Mac OS.

Could you please give a try to see if you can reproduce?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

I can't preview an invoice using BrowserStack.
![image](https://user-images.githubusercontent.com/16067358/116996867-5bed6800-acdc-11eb-89f8-e82ce1381f3a.png)
I don't use Mac OS.
@PrestaShop/qa-functional could you please try to reproduce the issue.

Thank you!

**Comment by arirangz** [comment]
@hibatallahAouadni  Hello
The test shouldn't be done in Safari but using the default mac os pdf viewer
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @arirangz 

You mean this ? 

![image](https://user-images.githubusercontent.com/23308427/116998338-5abd3a80-acde-11eb-89e4-c662cdd46c75.png)

Please check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

What is the exact language/country did you use during the install? and what is the language of your employee?

Thank you!

**Comment by arirangz** [comment]
Hello @hibatallahAouadni : You have to double click on the pdf, then it will open with the default mac os viewer

Hello @khouloudbelguith : we installed it in French/France. The admin language of the employee is English GB

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

This issue is reproduced by @sarahdib with 178x branch and develop branch.
![image](https://user-images.githubusercontent.com/16067358/117165063-764f4080-adc5-11eb-970d-2167d7b49c84.png)

’ll add this to the debug backlog so that it’s fixed.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by arirangz** [comment]
Hi @khouloudbelguith 
Thanks for the feedback.
Happy you could reproduce it.
As I mentioned in #24316  a quick fix is to change the font from Helvetica to freesans. The currency symbol issue will be fixed but you will see an issue in the pagination which will be maybe easier to fix. 

thanks

**Comment by florine2623** [comment]
I can't reproduce this bug on Preview application on mac.

![Image](https://github.com/user-attachments/assets/03fae8e6-4ee3-4967-8d02-d4e802c00a68)
