### ISSUE TITLE
Cannot create order on BO when customer cart/order history is empty

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#20643]
#### Describe the bug

On BO > Orders > Create order, when the selected customer has no previous cart or order, the cart/order list display a "Loading" message, and the rest of the page is not loaded, so I cannot create an order with this customer.

#### Expected behavior

If there is no cart and order for a customer, we should not have an "infinite loading", but instead an empty list, maybe with a message saying "no previous cart/order".

#### Steps to Reproduce

0. Create a new customer (from BO) so he does not have any cart/orders
1. Go to BO > Orders > Create order
2. Select the newly created customer
3. See the infinite loading of carts/orders, preventing the rest of the page from loading

**Screenshots**

![create order loading cart](https://user-images.githubusercontent.com/55688534/90645022-ba99b100-e235-11ea-9390-ff78dc18d58c.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by ngodefroy** [comment]
TEST OK
https://drive.google.com/file/d/1dB8QJoufX3yZloUxkvVCjJ-Xqu12J7Cr/view
