### ISSUE TITLE
[BO][ORDER][PRODUCTS] In some screen size, the base price is not visible 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20640]
#### Describe the bug

When I settle my screen to different size, the base price info are not readable. 

#### Expected behavior

The responsive screen should adapt itself to the page

#### Steps to Reproduce

1. Under BO>Order, Go to a client order
2. Open you console to be able to modify the screen sizes
3. verify responsive is on, then set your screen to 932x1556 until about 948x1556, you cannot see the prices 
4. See the attached video

**Screenshots**

https://drive.google.com/file/d/1t-ctlKWNjv6bPTNbGce1jbXdmlVWCDAn/view

#### Additional information

* PrestaShop version: 1.7.7 beta 2
* PHP version: N/A

**Comment by marionf** [comment]
@TristanLDD what do you think ?

**Comment by NeOMakinG** [comment]
I would say, having the price input upper the label on a bigger media query, but waiting for @TristanLDD advice

**Comment by ngodefroy** [comment]
TEST OK https://drive.google.com/file/d/1tZcsfNvcxtNebRH76ssMiNn9AH8hdZAi/view

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20729
