### ISSUE TITLE
[BO][CREATE AN ORDER] Errors in console 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20651]
A clear and concise description of what went wrong.

In BO, Open the console. Add a new order and see the errors in console

Explain what you expected to happen instead.

#### Steps to Reproduce

1. In BO, open your console and Go to Order>Create Order> Create a new customer or select existing customer and click on "details"
==>See the errors in console 

**Screenshots**

![Capture d’écran 2020-08-20 à 10 54 58](https://user-images.githubusercontent.com/69145330/90749323-98ef0700-e2d3-11ea-804c-9d1ce704b9bd.png)

select exisiting customer, click on "details"

![Capture d’écran 2020-08-20 à 10 55 19](https://user-images.githubusercontent.com/69145330/90749365-a73d2300-e2d3-11ea-87eb-b0fd4c112da5.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy, @marionf,

This issue isn't similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/18776?

Thanks!

**Comment by LouiseBonnard** [comment]
@sarahdib needs to have PR #20760 with the to be tested label to be able to test PrestaShop/welcome#67.
