### ISSUE TITLE
Overview Activity not Loading and not showing orders in control panel dashboard

### ISSUE THREAD

**Issue by trovaweb1** [PrestaShop/PrestaShop#20657]
Hi,

i'm trying to solve this issue that on BO dashboard i cannot see any statistics about orders and selling. As you can see in the screenshots i have several orders on these days but they not appear on dashboard.

---------------------------------------------------------------------------------------

Informazioni sul server Linux #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64

Versione software del server: Apache

Versione di PHP: 7.3.21

Limite di memoria: 1024M

Tempo di esecuzione massimo: 90

Dimensione Max. dei file da caricare: 128M

Versione di PrestaShop: 1.7.6.5

URL negozio: http://diamondlife.eu/

Percorso negozio: /home/diamondlife/public_html

Tema attualmente utilizzato: gorilla

![Screenshot_2020-08-20 Pannello di controllo • Diamond Life S R L ](https://user-images.githubusercontent.com/69973552/90777244-6c4ee580-e2fb-11ea-93fc-c360821a542e.png)
![Screenshot_2020-08-20 Pannello di controllo • Diamond Life S R L 1 ](https://user-images.githubusercontent.com/69973552/90777247-6ce77c00-e2fb-11ea-80c9-ac2e889528aa.png)

**Comment by SimonGrn** [comment]
Hello,

PrestaShop 1.7.6.5 is not compatible with PHP 7.3. You can check the compatibility [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).
Please downgrade your PHP version and come back if you still experience the issue.

Thanks.

**Comment by trovaweb1** [comment]
Changed PHP version to 7.1.33 and still get the issue

**Comment by SimonGrn** [comment]
Hello,
I am not able to reproduce your issue:
![image](https://user-images.githubusercontent.com/49909275/90786724-34986b80-e304-11ea-8802-ca22adcb63b5.png)

![image](https://user-images.githubusercontent.com/49909275/90786736-3b26e300-e304-11ea-80bc-df786ba85b6c.png)

You may have a module interfering with the dashboard.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by trovaweb1** [comment]
Trying to disable modules or use the option "disable non-native modules" could help to reproduce the issue for me?
