### ISSUE TITLE
Can't import bulk products

### ISSUE THREAD

**Issue by mioversolna** [PrestaShop/PrestaShop#20654]
I can't import my products if I load a file and click import my system is giving 500 Internal Server Error

**Comment by SimonGrn** [comment]
Dear @keremkutlu1234 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
