### ISSUE TITLE
BO - Orders page  - Vouchers block - Free shipping line is not added when a cart rule "Free shipping for a carrier selection" is  applied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20667]
#### Describe the bug

In the BO => Orders => New Order page, the "free shipping" line is not added to the Vouchers block when a cart rule "Free shipping for a carrier selection" is  applied

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts page
2. Create a cart rule Free shipping with a carrier selection "My carrier"
![image](https://user-images.githubusercontent.com/16067358/90888014-c01e0500-e3b5-11ea-8dc3-47b1d0dd3cb6.png)
3. Go to BO => Orders => Add new order page
4. add some product to the order
5. in the Shipping bock, select "My carrier"
6. See an error, the "free shipping" line is not added to the Vouchers block
![image](https://user-images.githubusercontent.com/16067358/90888208-1723da00-e3b6-11ea-8484-06f045b21f1d.png)

It was ok with PS1.7.6.7
![image](https://user-images.githubusercontent.com/16067358/90888295-476b7880-e3b6-11ea-8171-29383f4742a2.png)

**Screenshots**

https://drive.google.com/file/d/1zM-MNATxi-i82-nj3Bg5Yw5iSgflzmv3/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.0beta2build1, 177x
* PHP version: 7.2

**Comment by ngodefroy** [comment]
TEST OK https://drive.google.com/file/d/1fFdnDpeePboZloh2ghTyzvzMYhydqkfV/view
