### ISSUE TITLE
Allow a clean installation with no demo shop configured

### ISSUE THREAD

**Issue by kwaun** [PrestaShop/PrestaShop#20662]
Hi.

#### Is your feature request related to a problem?

Sometimes when I install PS I do not want the demonstration data so I have to delete it.

#### Describe the solution you'd like

IMHO a check box with "Do not install the demo shop" would be nice when installing PS.

#### Alternatives you've considered

I know right that there is a good official addon that removes the demo data (it leaves some pics around though) but there is always a better and optimal solution.

#### Additional context

Not needed I think.

**Comment by matks** [comment]
Like this ?

![Capture d’écran 2020-08-20 à 18 02 40](https://user-images.githubusercontent.com/3830050/90796270-5fd48800-e30f-11ea-8a15-f20f94203113.png)

**Comment by kwaun** [comment]
Yeah.

**Comment by SimonGrn** [comment]
Hello @kwaun ,
This setting exists but is only available when you **ARE** in DEBUG mode. I suggest you **enable** DEBUG mode before installing your shop.
By the way, we fixed this in the `develop` branch, and the checkbox is now available even if you're not in DEBUG mode.

**Comment by eternoendless** [comment]
This has been fixed in #19694 for 1.7.7

**Comment by SimonGrn** [comment]
My mistake, I wrote this totally wrong: you **NEED** debug mode to be able to see the checkbox. I updated my comment.

**Comment by khouloudbelguith** [comment]
Duplicate of #19694
