### ISSUE TITLE
BO - Orders page - An exception is displayed when we try to add a customized product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20671]
#### Describe the bug

In the BO => Orders => New Order page => an exception is displayed when we try a customized product 
![image](https://user-images.githubusercontent.com/16067358/90902466-ce2b5000-e3cc-11ea-8074-b2a29588293e.png)

#### Steps to Reproduce

1. Go to BO => Catalog => Products page
2. Create a product with **minimal quantity > 1** and with a **customized text** not required
![image](https://user-images.githubusercontent.com/16067358/90903660-8b6a7780-e3ce-11ea-9abe-537d668dbc05.png)

3. Go to BO => Orders page => Add a new Order page
4. Search for the last product created
4.1 => if the customization is empty => an exception is displayed in the console
(**this exception is displayed also when minimal quantity =1**)
4.2 => if the customization is not empty => an alert is displayed with wrong alert `Minimum quantity of 0 must be added to cart.`

#### Additional information

* PrestaShop version: 1.7.7.x, 1770beta2
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20684
