### ISSUE TITLE
Bug in the Admin Panel

### ISSUE THREAD

**Issue by AhmddQ** [PrestaShop/PrestaShop#20678]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by AhmddQ** [comment]
Hello, i just installed Prestashop 
and then i got the Bug in the Video here: 

https://youtu.be/3lKz5Zj6TMk

and i`ve tried to reinstall so many versions of prestashop new and old Versions, and everytime the same bug shows, it just dont want to fix... 
i hope you can fix it ASAP, thanks alot ^^ <3

**Comment by SimonGrn** [comment]
Dear @AhmddQ 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
