### ISSUE TITLE
BO - Orders page - increment/decrement button doesn't work when we try to add a product out of stock (allow order)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20670]
#### Describe the bug

In the BO => Orders page => New Order page => when we try to add an out of stock product with allowing order, the increment/decrement button doesn't work

#### Steps to Reproduce

1. Go to BO => Catalog => Products page
2. Add a product with quantity <= 0 with allow order selected
3. Go to BO => Orders => New Order page
4. Add the last product created
5. check the increment/decrement button
6. see error => we can't increment the product quantity

**But if you try to enter directly the quantity in the field and click on "Add to cart", it's working**

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/90896673-59ecae80-e3c4-11ea-9263-9f4e734aaf3a.png)
https://drive.google.com/file/d/10ob-O_t4_JSv1hhM5HweRPZ4J5IMcuuE/view?usp=sharing

#### Additional information

* PrestaShop version: 1770beta2, 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #20714
