### ISSUE TITLE
BO - Orders page - Order Message is not saved after creating a new order from BO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20686]
#### Describe the bug

In the BO => Orders => New Order page => when we add an order message => in the order page there is no message displayed
![image](https://user-images.githubusercontent.com/16067358/91038037-62362b00-e60a-11ea-9cb9-e11aad0e89f0.png)
![image](https://user-images.githubusercontent.com/16067358/91038113-872a9e00-e60a-11ea-9b7d-36875f09f570.png)

#### Expected behavior

It was ok with PS1.7.6.7
![image](https://user-images.githubusercontent.com/16067358/91038158-9c073180-e60a-11ea-8f59-8350be6c18e7.png)

#### Specs
https://github.com/PrestaShop/prestashop-specs/commit/002dd12effcceede6d725d9fa01c5dc75587f279

#### Steps to Reproduce

1. Go to BO => Orders => Add new Order page
2. Add some products to the cart
3. IN the Summary section => add an order message
4. Create the Order
5. see error => no message displayed

#### Additional information

* PrestaShop version: 1.7.7.0beta2build1, 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #20757
