### ISSUE TITLE
Problem with modules page

### ISSUE THREAD

**Issue by eduardob1978** [PrestaShop/PrestaShop#20685]
#### Describe the bug
Error 500 when entrered the module page

#### Expected behavior

see the modules page

#### Steps to Reproduce

click on modules
appeared error 500 page
**Screenshots**

![Captura de pantalla 2020-08-24 12 06 35](https://user-images.githubusercontent.com/57547778/91034757-ce626000-e605-11ea-8a62-fae853d89c70.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

Extra info:
I had this error in the debug

[INTERNAL] /homepages/8/d805048438/htdocs/clickandbuilds/PrestaShop/Mamba/modules/adyenofficial/adyenofficial.php line 35 - require_once(): Failed opening required '/homepages/8/d805048438/htdocs/clickandbuilds/PrestaShop/Mamba/modules/adyenofficial/vendor/autoload.php' (include_path='/homepages/8/d805048438/htdocs/clickandbuilds/PrestaShop/Mamba/vendor/pear/pear_exception:/homepages/8/d805048438/htdocs/clickandbuilds/PrestaShop/Mamba/vendor/pear/console_getopt:/homepages/8/d805048438/htdocs/clickandbuilds/PrestaShop/Mamba/vendor/pear/pear-core-

**Comment by khouloudbelguith** [comment]
Hi @eduardob1978,

You have an issue with the `adyenofficial` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
