### ISSUE TITLE
BO - Orders page - "Send an email to the customer with the link to process the payment." doesn't work

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20687]
#### Describe the bug

In the BO => Orders page => Add new order page => In the summary block, the button `Send an email to the customer with the link to process the payment.` doesn't work, we have an error in the console
![image](https://user-images.githubusercontent.com/16067358/91040922-5c8f1400-e60f-11ea-9145-d9c62095e552.png)

#### Expected behavior

It was ok with PS1.7.6.7
![image](https://user-images.githubusercontent.com/16067358/91041210-ea6aff00-e60f-11ea-8db2-c3a3142bb9e8.png)

#### Steps to Reproduce

1. Go to BO => Orders => Add a new Order page
2. Add some products to the cart
3. In the summary block => Click on the `Send an email to the customer with the link to process the payment.` button

#### Additional information

* PrestaShop version: 1.7.7.x, 1770beta2build1
* PHP version: 7.2

**Comment by ngodefroy** [comment]
TEST OK 
I didn't get any error in console while clicking on "send an email to the customer'
![Capture d’écran 2020-08-28 à 15 58 02](https://user-images.githubusercontent.com/69145330/91573985-55397480-e947-11ea-9d2e-7f47476db0dd.png)

**Comment by Progi1984** [comment]
Fixed by #20704 20704
