### ISSUE TITLE
Deleting languague fails with open_basedir restriction in effect

### ISSUE THREAD

**Issue by rozwell** [PrestaShop/PrestaShop#20682]
#### Describe the bug

Unable to delete a language because it fails on .htaccess and index.php files from PS_MODULE_DIR due to lack of testing whenever the path is actually a directory or not with open_basedir restriction in effect.

#### Expected behavior

Error should not be thrown, language shall be deleted.

#### Steps to Reproduce

1. Go to International => Localization => Languages
2. Click on 'delete' on a chosen language
3. Click OK to confirm

#### Additional information

* PrestaShop version: develop/1.7.7.x
* PHP version:  7.2.32 with open_basedir restriction

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-product-team should this be in the 177 scope or develop ? Feel free to change the PR description with the right answer!

**Comment by khouloudbelguith** [comment]
Hi @rozwell,

Have you this exception when deleting a language?
![image](https://user-images.githubusercontent.com/16067358/91027956-129d3280-e5fd-11ea-87a3-5852f755a5c0.png)
![image](https://user-images.githubusercontent.com/16067358/91028005-234da880-e5fd-11ea-99e8-fa18fffa1f97.png)

Thanks!

**Comment by marionf** [comment]
@NeOMakinG We need to reproduce the issue before, make sure it's not a regression and qualify it
The version mentionned here is the affected version, not the version where the issue will be fixed

**Comment by khouloudbelguith** [comment]
@marionf, @NeOMakinG,

I followed these steps:
set the open_basedir value (ex open_basedir = '/var/www/html/Prestashop')
Try to delete a language
I have this exception
![image](https://user-images.githubusercontent.com/16067358/91033516-c6a1bc00-e603-11ea-9374-e536afd55960.png)
I just reload the page
I have this error
![image](https://user-images.githubusercontent.com/16067358/91033543-d1f4e780-e603-11ea-83af-b29193e87c8f.png)


I have the same issue with PS1.7.6.7 and  177x branch.
But I'm not sure if it is a PrestaShop core issue or not.

Thanks!

**Comment by rozwell** [comment]
> Hi @rozwell,
> 
> Have you this exception when deleting a language?
> ![image](https://user-images.githubusercontent.com/16067358/91027956-129d3280-e5fd-11ea-87a3-5852f755a5c0.png)


Hi @khouloudbelguith,
Yes, that's the issue, just in my case it was failing on `.htaccess` file first, then `index.php`.

**Comment by khouloudbelguith** [comment]
@rozwell, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.7 and 177x branch.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by rozwell** [comment]
@khouloudbelguith, I've already sent a pull request for it #20681 :)
