### ISSUE TITLE
When creating category, select all groups by default

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20691]
#### Is your feature request related to a problem?

When me or an employee is creating a category, we often forget to check our extra customer groups. Then a customer is complaining that he cannot enter some specific category.

#### Describe the solution you'd like

When creating new category, select all customer groups by default, not just the 3 original ones.

#### Additional context

I think that customer groups are used mostly to set special prices for good customers, that buy in bulk, rather then to restrict access to some categories, so it will please majority of users.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
I agree with @Hlavtox, all groups should be ticked by default. I've made a brief search and it seems to be the only page where it is forgotten along with the customer creation form in the Customers section of the back office but the use case is not the same so here is my recommendation:

1. tick by default **all customers groups in the Catalog > Categories > Add new category page**
2. tick by default **only the _Customer_ group in the Customers > Customers > Add new customer page** - none if the store has no _Customer_ group anymore

**Comment by jolelievre** [comment]
I reopen this issue because the solution suggested for Webservice to use Symfony is not adapted
So I created this PR https://github.com/PrestaShop/PrestaShop/pull/27770 which reverts the use of Symfony

But it should also of course work as expected with the previous fix
