### ISSUE TITLE
Change order of discounts

### ISSUE THREAD

**Issue by baldemir** [PrestaShop/PrestaShop#20697]
Hi,

Thank you for putting great work on this project. I have a concern about Catalog Price Rules. Let's say I want to apply 10% discount on all products. So I created a price rule for this and it works as expected. When I wanted to apply a 50% discount for "Category 1" and created a price rule for "Category 1" products in "Category 1" still has 10% discount. So it doesn't work as I expected.

If I add 50% discount rule first and create 10% discount after then it works as I expected. 

So I think a feature to change order of Catalog Price Rules is necessary. What do you think? Am I missing something?

**Comment by khouloudbelguith** [comment]
Hi @baldemir,

We are aware of this issue.
Your ticket is a duplicate of #20185
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #20185
