### ISSUE TITLE
Discounts - Incorrect total with Free gift + Percent discount cart rule

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20690]
#### Describe the bug

The total Order is incorrect when he have two cart rules = free gift and a percent discount

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts => Cart rule page
2. Create a cart rule Percent discount 50%
![image](https://user-images.githubusercontent.com/16067358/91055866-83f0db80-e625-11ea-9864-fad6c64ccd79.png)
3. Create a second cart rule Free gift Product1 =110 euro
![image](https://user-images.githubusercontent.com/16067358/91055993-adaa0280-e625-11ea-975a-2fdee6e7b958.png)
4. From the FO/BO => add a product1(110euro) to the cart
5. Apply the Free gift rule
6. Apply the 50 cart rule
7. see the error the total is incorrect
The **total =0**  => NOK, the cart rule 50% is applied on gift also => NOK

**Screenshots**

FO
![image](https://user-images.githubusercontent.com/16067358/91056427-417bce80-e626-11ea-902c-53364bc592a1.png)
BO
![image](https://user-images.githubusercontent.com/16067358/91056610-7d169880-e626-11ea-9e67-376b9618d000.png)

with PS1.7.6.7 => OK
![image](https://user-images.githubusercontent.com/16067358/91057411-72a8ce80-e627-11ea-9ccc-91b8ff36cbe0.png)

#### Additional information

* PrestaShop version: 177x, 1770beta2build1
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Maybe related to this https://github.com/PrestaShop/PrestaShop/pull/16724

**Comment by jolelievre** [comment]
The problem seems to be that the gift cart rule is applied on each product in 177, and only one time on 176

**Comment by Progi1984** [comment]
Fixed by #20741
