### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by ilyassw** [PrestaShop/PrestaShop#20695]
Hi,
Prestshop version 1.7.6.7
I posted about my issue on presta forum but i didn't get an answer , so i hope i  will get one here .
I have problem setting up SMTP with port 587 and port 465 , if i use port 25 i can send and receive email without any issue ! note that port 25 is open on amazon light sale as well as port 587 and 465 ... but whenever i try port 587 encrypt ssl i get this error :   

  Error: Please check your configuration

Connection could not be established with host smtp.mydomain.com [ #0]   same issue when using port 587 . I repeat and insist both port are open .

Please i need help to sort this out . Thank you

**Comment by khouloudbelguith** [comment]
Hi @ilyassw,

The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.
On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!

**Comment by ilyassw** [comment]
Hi ,
I am not sure why you are closing this ticket ? The SMTP is not working on prestashop 1.7.6.7 ! don't just close this ticket like that ? yes i do have SMTP details ! but prestashop still give error mentioned above ! Error: Please check your configuration

Connection could not be established with host smtp.mydomain.com [ #0]

I still think this need to be resolved here i am afraid , it has to be an issue with swiftmailer so i need someone to clarify this if possible . Thanks

**Comment by khouloudbelguith** [comment]
@ilyassw,

>I still think this need to be resolved here i am afraid , it has to be an issue with swiftmailer so i need someone to clarify this if possible . Thanks

This github repository is not free a software support area, but a bug tracker.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
