### ISSUE TITLE
[BO][Attributes] Add new attributes button displayed 2x times

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20694]
#### Describe the bug

In the BO, I access the Attributes & Features Page.
I can see two buttons "Add new Attributes" (in different places) each redirecting to the same page

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to Attributes & Features
2. Clicl on Attributes
3. Check the two different "add new attributes" buttons

**Screenshots**

![Capture d’écran 2020-08-24 à 17 34 26](https://user-images.githubusercontent.com/69145330/91064929-2c0ba200-e630-11ea-8bec-2f30aff107a5.png)

#### Additional information

* PrestaShop version: 1.7.7 Beta 2
* PHP version: N/A

**Comment by marionf** [comment]
Hello @ngodefroy 
This is the wanted behavior on legacy pages, anyway this is not the case anymore with migrated pages and will be automatically fixed with the migration, so I close this issue
