### ISSUE TITLE
[BO][PRODUCTS] [COMBINATIONS] [BULKS ACTIONS] Error message & in console when editing 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20702]
#### Describe the bug

In the BO, products>combinations, When I do a bulk action on multiple products, I get a message error and an error in console and im not able to edit the quantity/price in this mode.

#### Expected behavior

Being able to make bulk actions on multiple products

#### Steps to Reproduce

1. Go to Products > Combinations Click on the Bulk action checkbox to tickles all the products
2. Modify some data like price or/and quantity
3. Apply results

**Screenshots**

https://drive.google.com/file/d/1Svmn3NMNkQLyDey3elV6HT6uO5id6EFv/view

<img width="1344" alt="Capture d’écran 2020-08-25 à 11 40 17" src="https://user-images.githubusercontent.com/69145330/91159009-c23ed700-e6c7-11ea-9dcb-ca995de0b0b8.png">

#### Additional information

* PrestaShop version: 1.7.7 beta 2 & 1.7.7.x
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I think this issue is related to `max_inpput_vars`.
You need to increase it to 5000 as recommended.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by ngodefroy** [comment]
> Hi @ngodefroy,
> 
> I think this issue is related to `max_inpput_vars`.
> You need to increase it to 5000 as recommended.
> https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> Thanks!

Thank you, after increasing max_input_cars, it worked, thus I close the issue :)
