### ISSUE TITLE
Make Module manager notifications/flash messages last longer

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#20700]
Make a module return false on install, try to install to get a error notification / flash message.
It works, but it shows for to short amount of time - no time to read if there is important information.

Should be longer, or better lasting forever until you close it with an x.

![Screenshot 2020-08-25 at 10 27 15](https://user-images.githubusercontent.com/30602638/91151696-4d1ad400-e6be-11ea-8ecf-8d026ad8c101.png)

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think of this improvement?

Thanks!

**Comment by marionf** [comment]
Hello @onklmaps 
It seems a good idea, do you feel to [make a pull request](https://github.com/PrestaShop/PrestaShop/tree/develop) to fix that ?

Thank you!
