### ISSUE TITLE
AbstractCommand should not use exec for calling another php

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#20708]
`AbstractCommand` and `Upgrade`/`Refresh` child classes use currently system/shell to invoke

commands to php apps that use Symfony Console like `doctrine:cache:clear-metadata` can/should be included directly instead of using `exec`

using `exec` was introduced lately, in past, install (using web or cli) did not require `exec` (nor `proc_open`)

if this is not a bug, than it is a feature request, help wanted

## how to replicate/test?

install using `/install-dev/index_cli.php` with `exec` and `proc_open` functions disabled

install should complete, currently, it fails with message:
```
Warning: exec() has been disabled for security reasons
```

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi, Could you tell us more about where this exec is? I only see one in DatabaseDump.php

**Comment by mvorisek** [comment]
> 
> 
> Hi, Could you tell us more about where this exec is? I only see one in DatabaseDump.php

@PierreRambaud in https://github.com/PrestaShop/PrestaShop/blob/9317b06b346c8ed1b022b02de6d1c1636380992b/src/PrestaShopBundle/Install/Install.php#L327

generally everywhere, where `AbstractCommand\AbstractCommand` is used - instead of invoking these commands thru shell, we should invoke the commands from the same process, which should be possible when the target libs use Symfony Console

**Comment by matks** [comment]
@mvorisek I am sorry but, like @PierreRambaud, I fail to understand this issue. I have been looking for `exec()` statements in both the Core code and the autoupgrade module, I cant find one.

Are we talking about https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Service/Command/AbstractCommand.php#L81 ?

If I get it correctly, you see "exec warnings" when running these commands ? Ah, this might from how Symfony Console runs these Commands under the hood.

**Comment by mvorisek** [comment]
@matks yes, for ex. for Doctrine ORM, we should mimic:

https://github.com/doctrine/orm/blob/2.7/bin/doctrine.php#L69

ie. call

ConsoleRunner https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php

directly

**Comment by PierreRambaud** [comment]
AFAIK, the `exec` / `passthru` / `system` are required for upgrade (MySQL dump as example). 
Also, this is already what we are doing with the AbstractCommand.php.
I didn't manage to reproduce your issue.
![image](https://user-images.githubusercontent.com/1462701/91302161-52ebe480-e7a6-11ea-9b19-b77c4d6202bf.png)

**Comment by mvorisek** [comment]
> MySQL dump as example

you mean calling `mysqldump` directly somewhere?

Please confirm, that you tried using latest `develop`.

Please confirm, your test reached https://github.com/PrestaShop/PrestaShop/blob/9317b06b346c8ed1b022b02de6d1c1636380992b/src/PrestaShopBundle/Install/Install.php#L327

**Comment by PierreRambaud** [comment]
> > MySQL dump as example
> 
> you mean calling `mysqldump` directly somewhere?
> 
> Please confirm, that you tried using latest `develop`.
> 
> Please confirm, your test reached
> 
> https://github.com/PrestaShop/PrestaShop/blob/9317b06b346c8ed1b022b02de6d1c1636380992b/src/PrestaShopBundle/Install/Install.php#L327

I confirm for both questions.
And I also confirm the mysqldump command is called in DatabaseDump.php
