### ISSUE TITLE
actionProductCancel hook not triggered on standard refund

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#20712]
#### Describe the bug
In 1.7.6, the **actionProductCancel** hook was triggered from the BO order page, when clicking on the button "cancel product", "standard refund" or "cancel product". In 1.7.7 it is triggered only when clicking on "cancel product".

#### Expected behavior
The **actionProductCancel** hook should be triggered on all kinds of cancellation / refunds.

#### Steps to Reproduce

Perform a "cancel product", a "standard refund" or a "return product", **actionProductCancel** hook should be triggered.

#### Additional information
* PrestaShop version: 1.7.7

**Comment by Progi1984** [comment]
Fixed by #20693
