### ISSUE TITLE
Add $delta_quantity to hookActionUpdateQuantity()

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#20715]
I am trying to update product stock in an external api. Using the hookActionUpdateQuantity($params)  I only get the qty after the change. But the external API requires me to make the stock change in either negative or positive change - in other words, how much the stock should change with and not the result after the change. I am surprised to see that there are no $params['previous_qty] and $params['qty_now']. 

As discussed on Slack with some of the core devs, this is the suggestion:

            Hook::exec(
                'actionUpdateQuantity',
                array(
                    'id_product' => $id_product,
                    'id_product_attribute' => $id_product_attribute,
                    'quantity' => $stock_available->quantity,
                    'deltaQuantity' => $deltaQuantity
                )
            );

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers could you check this ?

**Comment by eternoendless** [comment]
Yes that's right, just use `snake_case` in arguments naming to maintain style consistency. Here's where you should add it: https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Stock/StockManager.php#L192

**Comment by Sinepel** [comment]
@eternoendless @onklmaps 
Hello, can I do the PR? I also have this need at the moment :)
Thanks !

**Comment by eternoendless** [comment]
I suppose the first one to do it wins 😛

**Comment by matks** [comment]
@onklmaps PR merged 😉
