### ISSUE TITLE
Problems about integration between PrestaShop 1.7.6.7 and MercadoPago 4.1.1

### ISSUE THREAD

**Issue by RonaldoPontual** [PrestaShop/PrestaShop#20718]
#### Describe the bug

Mercado Pago's check out system gives you trouble in finalizing your payment. I can't simulate payment using either a credit card or a bank slip.

The PM module is not listed in the PrestaShop payment methods.

#### Expected behavior

The system is expected to perform the checkout

#### Steps to Reproduce

When trying to perform payment tests

**Screenshots**

![1](https://user-images.githubusercontent.com/37090641/91229615-8aa05100-e700-11ea-99c1-7841e4a5e846.jpg)
![2](https://user-images.githubusercontent.com/37090641/91229649-968c1300-e700-11ea-9c54-c5f1847b5dbf.jpg)
![3](https://user-images.githubusercontent.com/37090641/91229663-99870380-e700-11ea-9549-14ac59a2f395.jpg)
![5](https://user-images.githubusercontent.com/37090641/91229668-9be95d80-e700-11ea-8cd8-006aa731ac0e.jpg)
![6](https://user-images.githubusercontent.com/37090641/91229676-a0157b00-e700-11ea-9e5f-65ac226b2b14.jpg)
![22](https://user-images.githubusercontent.com/37090641/91229682-a60b5c00-e700-11ea-8844-789b734d2620.jpg)
![33](https://user-images.githubusercontent.com/37090641/91229690-a7d51f80-e700-11ea-8f30-9134ccced5a8.jpg)
![44](https://user-images.githubusercontent.com/37090641/91229694-a99ee300-e700-11ea-92e5-be231dafb03e.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
*MercadoPago 4.1.1

* PHP version: 5.6.38
* MySQL: 5.6.41-84.1
*Server Info: Linux #1 SMP Sat Sep 21 01:19:55 CDT 2019 x86_64
Server software: Apache
Memory limit: 512M
Max time execution: 30
Max size send file: 256M

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using a third-party modules, please contact the developper of the module.

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
