### ISSUE TITLE
When I activate the invoice and create one for a previous order, it generates a double invoice

### ISSUE THREAD

**Issue by jordiweblidera** [PrestaShop/PrestaShop#20728]
#### Describe the bug

When I activate the invoice and create one for a previous order, it generates a double invoice

#### Expected behavior

Only one invoice per order

#### Steps to Reproduce

*I used the [prestashop official demo](http://demo.prestashop.com/)*

1. **IMPORTANT**: Disable invoice
2. Create an order
3. Change order state to Payment accepted
4. Enable invoice
5. Go to order and generate invoice
6. Press download invoice, it generates [invoices.pdf](https://github.com/PrestaShop/PrestaShop/files/5129786/invoices.pdf) for two invoices #IN000000 and #IN000001

**Screenshots Video**

I have compressed a video with the bug, so you can replicate it: [InvoicesDuplicated.zip](https://github.com/PrestaShop/PrestaShop/files/5129757/InvoicesDuplicated.zip)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration.
https://drive.google.com/file/d/18-16ZsdfV2gh-ylz0Udy-jkBa_XI12uS/view

Thank you!

**Comment by jordiweblidera** [comment]
Hello,

You have not clicked on the "view invoice" button, but directly on the link to the invoice number. If you click on the "view invoice" button, it will generate two invoices.

If you look at the pdf you have generated, the payment method does not appear, as the bug assigns it to invoice number 0.

Regards,
Jordi

**Comment by jordiweblidera** [comment]
Hello @sarahdib,

You have not clicked on the "view invoice" button, but directly on the link to the invoice number. If you click on the "view invoice" button, it will generate two invoices.

If you look at the pdf you have generated, the payment method does not appear, as the bug assigns it to invoice number 0.

Regards,
Jordi
