### ISSUE TITLE
[BO][ATTRIBUTES & FEATURES] Filtrer by position not working 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20723]
#### Describe the bug

Under Attributes & Features> Attributes & Features, When I filter the search by a specific position, I get no result or no corresponding results

#### Expected behavior

Filter by position should give me the expected results

#### Steps to Reproduce

1. Go to Attributes & Filters
2. Click on Attributes or Features
3. Filter by position only
4. The matching numbers doesnt appears

**Screenshots**

https://drive.google.com/file/d/18DtiCTv8_mtnTQoBNbUFV9WM-qKx24UZ/view

#### Additional information

* PrestaShop version: 1.7.7 beta2 & 1.7.7.x
* PHP version: 7.2

**Comment by ngodefroy** [comment]
This page will be migrated in symfony on next version thus I close the issue.

**Comment by khouloudbelguith** [comment]
Duplicate of #9836
