### ISSUE TITLE
There is no easy way to find out if a voucher presented by CartPresenter provides free shipping

### ISSUE THREAD

**Issue by awitkutarahil** [PrestaShop/PrestaShop#20722]
#### Is your feature request related to a problem?

On Front Office, there is no easy way to find out if a voucher presented by CartPresenter provides free shipping or not. I suggest adding this little property as a boolean in the presented voucher object.

#### Describe the solution you'd like

Add the missing property into the object. See Pull Request https://github.com/PrestaShop/PrestaShop/pull/20721

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-product-team  could you check this improvement ?
Thank you !
