### ISSUE TITLE
Spam customers even when re-captcha is implemented

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#20732]
#### Describe the bug
I am on 1.7.6.4 and I have added the Google re-captcha script on both the signup page and the account creation at checkout and it seems to work, at least I am not able to click continue to register a new customer without completing the re-captcha challenge.

The issue is that I still get one or two spam customers registered per day. The email addresses are valid but names are garbage fortunately, looking like for instance: HUqTxPivECIZR.

I also added re-captcha to the newsletter signup and after that, no more spam registrations for the newsletter.

So, at this point I wonder if there is another way to register new customers that I am missing (webservices are not enabled) that the spammers are using?

#### Expected behavior

With re-captcha added to the signup form and on the checkout page, I would think robot customer creation should not be possible anymore?

#### Additional information
The shop is [givensa.com](https://givensa.com)

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by matks** [comment]
> #### Expected behavior
> With re-captcha added to the signup form and on the checkout page, I would think robot customer creation should not be possible anymore?

ReCAPTCHA will prevent quick spam on your website. Unfortunately there is services that use humans to solve ReCAPTCHA challenges in 10 seconds so these services can still spam you.

See https://anti-captcha.com/ for example

Basically reCAPTCHA cannot protect you from humans.

You might be able to filter some more using IP address whitelist. If you see IPs coming from a country you dont do business in, you can block them.

**Comment by matks** [comment]
@johanlantz we closed the issue because we believe unfortunately there is no solution inside the software 😞 

The solution can come from server configuration / services (like fail2ban or IP filtering) or modules (like reCAPTCHA). Solutions fit for your usecase. But the PrestaShop software itself cannot solve this topic for good.

**Comment by kordama1** [comment]
what I desperately need is an answer for 'what EXACTLY should I perform, to get the free Google reCAPTCHA module installed.. within the e-commerce ([motohaft.pl](http://motohaft.pl/)), that I gathered, from PRESTA pages: https://prestapros.com/en/blog/free-module-recaptcha-for-prestashop-registration-form. Thanks in advance for your prompt answer! The quuestion is just about to WHERE I should copy those 4 files into???

**Comment by matks** [comment]
@kordama1 The ZIP you download is a module. You don't copy it.

[Follow these instructions](https://prestabuilder.com/install-new-module-prestashop-1-7/) to install it

Note: PrestaPros is a company not affiliated to the PrestaShop open source. I dont know them, I dont know their product.
