### ISSUE TITLE
You may be not allowed to download this module (v1.7.6.7)

### ISSUE THREAD

**Issue by mark-alexandre** [PrestaShop/PrestaShop#20730]
Hi,

I'm working on a company and we have a dozen of Prestashop websites. In several of them, some of the plugins can't be upgraded, with an error message saying :

`You may be not allowed to download this module.
`

The strange thing behind it is that most of the plugins were upgraded successfully. But some others just fails with this exact same generic message. And in these plugins, there are several OFFICIAL plugins  (developped by Prestashop)  like "CM-CIC P@iement" as an example.

The issue is like this [one](https://github.com/PrestaShop/PrestaShop/issues/10387), but I'm with Prestashop v1.7.6.7 so what the hell is going on here? Have you some tips about this issue?

Thank you.

**Comment by matks** [comment]
@mark-alexandre Can you tell us what is the current version of the module and, if you know it, the "version you want to upgrade to" ?

**Comment by mark-alexandre** [comment]
Sure. In the website I'm currently working on, there are 2 fails :

- CM-CIC P@iement : v3.1.0 -> v4.2.0
- SEO Expert : v3.1.13 -> v4.0.0

Both are developped by Prestashop.

**Comment by matks** [comment]
@mark-alexandre Did you subscribe to the Addons option that allow you to benefit from major module updates ?

From https://addons.prestashop.com/en/content/1-faq

```
How do I take advantage of the updates?
The conditions for accessing updates are as follows:

You have a valid Zen option: you have access to all product updates;

In all other cases, you only have access to minor updates (bug corrections) or security updates.

Option Zen is extended support for a product sold on the PrestaShop Addons marketplace. It applies to a single product and includes both support and updates for the product concerned.
Option Zen includes two services:

- unlimited after-sales support during the period covered by the option;
- access to all module or theme updates.

Option Zen is available at a discount when purchasing the module or theme; you can also buy it in your customer account after buying the module or theme.
```

**Comment by mark-alexandre** [comment]
That's a very good question, and I have to ask my company for this. I'm going to reply when I have the answer.

**Comment by khouloudbelguith** [comment]
Hi @mark-alexandre,

Thanks!
Waiting for your feedback.

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!
