### ISSUE TITLE
FO - ps_categorytree Module - This module is not displayed in the mobile version 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20747]
#### Describe the bug

In the BO > Module Manager page > When we enable Mobile for the ps_categorytree mobile, it is still not displayed
![image](https://user-images.githubusercontent.com/16067358/91420190-9735be00-e854-11ea-97b2-c4be7d5992a7.png)

In the FO => It is not displayed
![image](https://user-images.githubusercontent.com/16067358/91420315-d106c480-e854-11ea-8f71-07bec1c198d7.png)

#### Steps to Reproduce

1. Go to BO > Design > Theme & Logo page > Page configurations => Category Page => Navigation Column > Enable mobile for => ps_categorytree Module
2. check the FO > Category page

#### Additional information

* PrestaShop version: 1.7.6.7, 1.7.7.0beta2build1
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team is this the normal behavior or a bug?

Thanks!

**Comment by marionf** [comment]
It seems to be a bug if you enabled the module for mobile and if it's not displayed in FO
Did you check if the module is well hooked ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is enabled for mobile, it is well displayed with the desktop but with a mobile No.
I attached a screen record
https://drive.google.com/file/d/1hzKROZBUSXARJyizMdFw11ez_o3ZIkyg/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/91457474-acc2dc00-e884-11ea-874e-1a2cc61df3d9.png)

Thanks!

**Comment by marionf** [comment]
Well, so it's a bug !

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/PrestaShop/pull/21620#issuecomment-719048677
