### ISSUE TITLE
Bulk deletion on Return order statuses KO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#20743]
#### Describe the bug

On BO > Parameters > Statuses, the deletion via Bulk Action of return statuses is not working. It was OK in 176.

Standard deletion is OK.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Order Settings > Statuses
2. Add a return status (if there is only the default one)
3. Select the status, bulk action, and click on "Delete selected"
4. Page is refreshed but the status is not deleted

**Screenshots**

https://drive.google.com/file/d/12CYlyZ9LH1Z36LGGvGVHvB-7dgS2gfc1/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by ngodefroy** [comment]
TEST OK: 
Add a return status
Delete by bulk action 
The status is well deleted @sarahdib  confirmed. 
https://drive.google.com/file/d/1nq3AFUfWmVUX6XegmmJUWqZ1UaI2qCXQ/view

Note: I had the following issue on my case but it's apparently a problem on my side:
![Capture d’écran 2020-09-01 à 11 32 46](https://user-images.githubusercontent.com/69145330/91833337-ddb95d00-ec46-11ea-8c75-657ca2a185c5.png)
&
https://drive.google.com/file/d/1UOOhWveX4QayPVHV5w1nqijNN-mftcfd/view

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20796
