### ISSUE TITLE
Internal PHP error

### ISSUE THREAD

**Issue by smithikakart** [PrestaShop/PrestaShop#20746]
Using Prestashop version 1.7.6.4 and php version is 7.2 getting internal php error

> [27-Aug-2020 00:18:04 Asia/Kolkata] PHP Fatal error:  Uncaught PrestaShop\PrestaShop\Core\Product\Search\Exception\InvalidSortOrderDirectionException: Invalid SortOrder direction `asc/`. Expecting one of: `ASC`, `DESC`, or `RANDOM`. in /home/smithikakart/public_html/src/Core/Product/Search/SortOrder.php:199
> Stack trace:
> #0 /home/smithikakart/public_html/src/Core/Product/Search/SortOrder.php(67): PrestaShop\PrestaShop\Core\Product\Search\SortOrder->setDirection('asc/')
> #1 /home/smithikakart/public_html/src/Core/Product/Search/SortOrder.php(125): PrestaShop\PrestaShop\Core\Product\Search\SortOrder->__construct('product', 'name', 'asc/')
> #2 /home/smithikakart/public_html/classes/controller/ProductListingFrontController.php(286): PrestaShop\PrestaShop\Core\Product\Search\SortOrder::newFromString('product.name.as...')
> #3 /home/smithikakart/public_html/classes/controller/ProductListingFrontController.php(580): ProductListingFrontControllerCore->getProductSearchVariables()
> #4 /home/smithikakart/public_html/controllers/front/listing/CategoryController.php(137): ProductL in /home/smithikakart/public_html/src/Core/Product/Search/SortOrder.php on line 199

**Comment by sarahdib** [comment]
Hello @smithikakart,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report.
Read more about how we expect the issues to be handled [[here].](https://build.prestashop.com/news/how-bug-reports-are-handled/) Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you

**Comment by S4hosting** [comment]
sorry to reopen this dont have the option to reproduce this error its internal php error log, am using the prestashop version 1.7.6.4 and the php version is 7.2 here i have attached the screenshot too daily its load the php error 
<img width="1294" alt="Screenshot 2020-08-27 at 1 29 59 PM" src="https://user-images.githubusercontent.com/67721911/91413960-7b88e280-e869-11ea-89ca-adcdc06ca910.png">
logs fully....

**Comment by matks** [comment]
@smithikakart the error says you are sending value `asc/` instead of `ASC` to the search. Error triggers when you search product name by ascending.

Do you use a a custom theme ? Try with Classic Theme, issue might come from there.

**Comment by S4hosting** [comment]
Anyway to find where it comes from asc/ or desc/ ?

**Comment by khouloudbelguith** [comment]
Hi @smithikakart,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!

**Comment by bm-services** [comment]
Hello,
To reproduce, it's easy:

- on a product list, change sort by "product name" and "asc"
- check server logs, you have something like this: 
`PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid SortOrder direction 'asc/'. Expecting one of: 'ASC', 'DESC', or 'RANDOM'.' in .../www/src/Core/Product/Search/SortOrder.php:120`

**Comment by Cas000q1** [comment]
Hello,

I had the same error on prestashop 1.7.8.8
it happend when the sort param in the url on category page was not propperly formatted as asc, desc, or random.
Then it throws that error and result in an 500 error page.

I fixed it by removing line 206 in .../www/src/Core/Product/Search/SortOrder.php 
throw new InvalidSortOrderDirectionException($direction);
And replaced it with:
$formattedDirection = 'asc';

So that if it's not propperly formatted it just falls back to asc instead of making an error and crashing the page

**Comment by joecoolio66** [comment]
This is still an issue with 8.0.4:

[14-Jul-2023 06:56:16 Canada/Atlantic] PHP Fatal error:  Uncaught PrestaShop\PrestaShop\Core\Product\Search\Exception\InvalidSortOrderDirectionException: Invalid SortOrder direction `desc)/**/AND/**/3398=3398/**/AND/**/(8774=8774`. Expecting one of: `ASC`, `DESC`, or `RANDOM`. in /home1/canadac3/public_html/src/Core/Product/Search/SortOrder.php:206

**Comment by HartLarsson** [comment]
1.7.6.9 - same bug
