### ISSUE TITLE
Recalculate shipping costs option not working when set to No

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#20744]
#### Describe the bug

When setting the "Recalculate shipping costs after editing the order" option to No, the shipping cost are still recalculated when editing the order in BO when the price of the order exceeds the carrier's "limit".

#### Expected behavior

The shipping cost should not be updated if option is set to No.

#### Steps to Reproduce

0. Have a carrier set up with a fee below a certain amount, free above it
1. Go to BO > Shop Parameters > Order Settings
2. Set "Recalculate shipping costs after editing the order" to No
3. On FO, make an order with this carrier, under the limit amount (50€ in my screenrecord)
4. On BO, edit the order to make it exceed the limit

**Screenshots**

On this screenrecord : The carrier is set to be at 8€40 under 50€, 2€40 over 50€. When editing the order in BO the shipping cost should not be updated when the total of the order is over 50€, but it is.

https://drive.google.com/file/d/13R8qxiwqy0xfjpdUmrNNiKVdP3HkXzj7/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #20798
