### ISSUE TITLE
[MULTISTORE] Pagination for shop disappears if you switch to page 2

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20753]
#### Describe the bug

After adding numerous shops in order to get pagination, Go into your list of shops lists and go to page 2.
The pagination disappears, you cant go back to page one.

#### Expected behavior

pagination should remain when switching pages

#### Steps to Reproduce

1. Create numerous shops (to get pagination) then Go to your shops lists
2. Click on page 2
3. See the pagination disappears 

**Screenshots**

https://drive.google.com/file/d/1c8V68rOYG3nYRQtA9Y7EHqCF4FEMTlT1/view

#### Additional information

* PrestaShop version: 1.7.7 Beta2
* PHP version: 7.2

**Comment by ngodefroy** [comment]
@marionf could you add this to the epic?
https://github.com/PrestaShop/PrestaShop/issues/19304
Thank you :)

**Comment by marionf** [comment]
@ngodefroy 
As this page isn't in the scope of the 1.7.8 multistore revamp, I rather added it to the migration issue

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I did not manage to reproduce the issue with 1767 and 177x branch.
It is ok on my side.
![image](https://user-images.githubusercontent.com/16067358/91581847-4ce53780-e94f-11ea-9495-3de5feb06267.png)

I attached a screen record
https://drive.google.com/file/d/1aUkLbMPgbACBGt9IdqqJCz5KmRubLOga/view?usp=sharing
Thanks to check and feedback.

**Comment by ngodefroy** [comment]
> Hi @ngodefroy,
> 
> I did not manage to reproduce the issue with 1767 and 177x branch.
> It is ok on my side.
> ![image](https://user-images.githubusercontent.com/16067358/91581847-4ce53780-e94f-11ea-9495-3de5feb06267.png)
> 
> I attached a screen record
> https://drive.google.com/file/d/1aUkLbMPgbACBGt9IdqqJCz5KmRubLOga/view?usp=sharing
> Thanks to check and feedback.

Just tested it again, it now works fine for me ! 
See: https://drive.google.com/file/d/1FFrl07kp36wLEOvUgxFMvfJjNMKKkL4h/view
Thus, I close the issue.
Thank you :)
