### ISSUE TITLE
SQLManagement - It cannot be added any sql with joins

### ISSUE THREAD

**Issue by bertoferrero** [PrestaShop/PrestaShop#20750]
#### Describe the bug

If you try to add any query with joins into the SQLManagement (AdminRequestSql), it is always rejected. The error is detected at the RequestSql::returnNameTable function, it is not properly using the $table['alias']['no_quotes'] content

#### Expected behavior

If the query is secure, it must be added

#### Steps to Reproduce

1. Go to Backend - Advanced settings - Data Base
2. Add any query with joins

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @prestaquality,

I did not manage to reproduce the issue with PS1.7.6.7.
I tried with this SQL query
`select  ps_orders. id_order,  ps_customer. firstname from ps_orders INNER JOIN ps_customer  ON ps_orders.id_customer=ps_customer. id_customer`  
It is OK
I attached a screen record
https://drive.google.com/file/d/1VvnoR-UlG56qI5WtgPV9hPFMUl9RBzXU/view?usp=sharing
Thanks to check and feedback.

**Comment by ksaandev** [comment]
@prestaquality What kind of JOIN are you using ?

**Comment by bertoferrero** [comment]
In my shop it doesn't matter the type of join :S. The bug I got was because the content of $table['alias']['no_quotes'] is not a string, so it cannot be directly checked with $table['alias']['no_quotes'] == $alias sentence. This sentence is only achieve if the sql has a join (left, inner, outer... ). I do not know why in my whop the $table['alias']['no_quotes'] content has two arrays ($table['alias']['no_quotes']['parts'][0]) and yours do not.

**Comment by khouloudbelguith** [comment]
@prestaquality, Could you give us more information to reproduce the issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @prestaquality,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
