### ISSUE TITLE
[MULTISTORE][FILTER] filtering shops on URL not working on first try

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20756]
#### Describe the bug

In the list of shops, I add a url on a shop name.
Then, I filter on the shop main in the url box ex "/nameoftheurl/"

#### Expected behavior

Being able to filter by URL

#### Steps to Reproduce

1. Go to multistore
2. go to your list of shops
2. Edit a shop URL under "Physical URL"
3. Search for this shop url using the name you added in the url box search
4. You get no results
5. Search a second time, you get the results 

**Screenshots**

https://drive.google.com/file/d/1ptIHb_3iJepI30GtkvEJ0_SWnSM10gE4/view

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I did not manage to reproduce the issue with PS1.7.6.7 and 177x branch.
I attached a screen record
https://drive.google.com/file/d/1NPL9Owv82qIa26aDl-AkgOwLIbVIPfMj/view?usp=sharing
Thanks to check and feedback.

**Comment by ngodefroy** [comment]
After reinstalling the shop, I could not reproduce the issue, this I close the issue
Thank you @khouloudbelguith
