### ISSUE TITLE
Module Dashproducts PHP 7.2 Warning in Server Log

### ISSUE THREAD

**Issue by Alcpaone** [PrestaShop/PrestaShop#20768]
<!--

Error message in Server Log:
[php7:warn] PHP Warning:  Invalid argument supplied for foreach() in /XXXXXX/prestashop/modules/dashproducts/dashproducts.php on line 219

#### Describe the bug

PHP Warnings in Server Logfile

#### Expected behavior

No Warnings in PHP Log.

#### Steps to Reproduce

PS 1.7.6.5
no special action needed

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

PS: English is not my first language. Sorry

**Comment by khouloudbelguith** [comment]
Hi @Alcpaone,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Alcpaone** [comment]
Sorry, I don't know why it was empty after saving...

Here again:

Warning Message in Server Log:

[php7:warn] PHP Warning:  Invalid argument supplied for foreach() in /XXXXXX/prestashop/modules/dashproducts/dashproducts.php on line 219

We use PHP 7.2
PS 1.7.6.5

**Comment by Alcpaone** [comment]
Modul Dashproducts

**Comment by demperador** [comment]
Hello,

I am having this same exact warning in version 1.7.7.6 and PHP 7.3.23 and mariadb 10.2.36

Regards.
