### ISSUE TITLE
[BO] [ORDERS] Trying to add 2x out of stock with allow order gets error message 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20769]
#### Describe the bug

In the BO => Orders page => New Order page =>  when we try to add an out of stock product 2x, we get an error message "failed to update quantity in cart"

#### Expected behavior

When out of stock allow orders is set, we should always be able to put orders.

#### Steps to Reproduce

1. Go to BO => Catalog => Products page
2. Add a product with quantity <= 0 with allow order selected
3. Go to BO => Orders => New Order page
4. Add a product one time=> Order is added 
5. Click again on Add to cart
==> You get the error message 

**Screenshots**

![Capture d’écran 2020-08-28 à 14 35 43](https://user-images.githubusercontent.com/69145330/91561367-c3783a00-e93b-11ea-87b7-f19529f9da16.png)

https://drive.google.com/file/d/1JGpchSB-jHIz5bU-mt6Q52bM25Lwop2H/view

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by marionf** [comment]
@ngodefroy is it a regression compared to 1.7.6.7 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf, @ngodefroy,

I manage to reproduce the issue with PS1.7.7.x
![image](https://user-images.githubusercontent.com/16067358/91577448-fc6adb80-e948-11ea-9ad5-4d34df5927a0.png)
It is ok with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/91577485-0db3e800-e949-11ea-9f30-4146ba681cfb.png)

Related to: https://github.com/PrestaShop/PrestaShop/pull/18208

Thanks!

**Comment by Progi1984** [comment]
Fixed by #20792
