### ISSUE TITLE
wget command on back office

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#20762]
#### Describe the bug

I try to connect to Prestashop backoffice with wget command : 
wget --save-cookies /var/www/xxxxxxxx/cookies.txt --keep-session-cookies --post-data 'email=xxxxxxxx&passwd=xxxxxxxx' https://xxxxxxxx.com/admin/ -O /dev/null

In order to export csv file of sql request in back office with this command :  
wget --load-cookies /var/www/xxxxxxxx/cookies.txt 'https://xxxxxxxx.com/admin/index.php/configure/advanced/sql-requests/1/export' -O /var/www/xxxxxxxx/export.csv

I do this with many websites (not Prestashop) and it works.
But connection to Prestashop back office with wget command and my credentials doesn't work.

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @guigplt,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Could you give us more information? What errors do you get?

**Comment by guigplt** [comment]
Hi,
I don't have error, just 302 response when executing the first wget command : redirected to /admin/index.php?controller=AdminLogin&token=bc481a3ebe97be186d8430c227465fe5

And when executing the second wget commande : redirected to /admin/index.php/security/compromised?uri=https%253A%252F%252Fxxxxxxxxxx.com%252Fadmin0%252Findex.php%252Fconfigure%252Fadvanced%252Fsql-requests%252F1%252Fexport&_token=DbNEVH5Bz8pBlCg_viln5cPITK443NUmOckrDNfY0Ys

**Comment by PierreRambaud** [comment]
This is because of the `_token` in the URL, which is not valid when you try to log in to your application.
You should create a first request to retrieve this data in order to create the request to be connected.

**Comment by guigplt** [comment]
Yes I already tried this but it doesn't work neither : 

```
wget --load-cookies /var/www/xxxxxxxx/cookies.txt 'https://xxxxxxxx.com/admin/index.php/configure/advanced/sql-requests/1/export' -O /var/www/xxxxxxxx/export.csv -o /var/www/xxxxxxxx/_token.txt
_token=$(grep _token=* /var/www/xxxxxxxxxx/_token.txt | awk -F"=" '{print $3}' | grep -v following)
echo "${_token}"
wget --load-cookies /var/www/xxxxxxxxxx/cookies.txt "https://xxxxxxxxxx.com/admin/index.php/configure/advanced/sql-requests/1/export?_token=${_token}" -O /var/www/xxxxxxxxxx/export.csv
```

I think the problem is before that because it should not redirect to /admin/index.php?controller=AdminLogin&token=bc481a3ebe97be186d8430c227465fe5.
That's why I tried to do the same thing with the first wget command and the `token`.
And I also tried to pass `stay_logged_in=1` and `redirect=AdminProducts` in `--post-data`.
But same problem...

**Comment by PierreRambaud** [comment]
> Yes I already tried this but it doesn't work neither :
> 
> ```
> wget --load-cookies /var/www/xxxxxxxx/cookies.txt 'https://xxxxxxxx.com/admin/index.php/configure/advanced/sql-requests/1/export' -O /var/www/xxxxxxxx/export.csv -o /var/www/xxxxxxxx/_token.txt
> _token=$(grep _token=* /var/www/xxxxxxxxxx/_token.txt | awk -F"=" '{print $3}' | grep -v following)
> echo "${_token}"
> wget --load-cookies /var/www/xxxxxxxxxx/cookies.txt "https://xxxxxxxxxx.com/admin/index.php/configure/advanced/sql-requests/1/export?_token=${_token}" -O /var/www/xxxxxxxxxx/export.csv
> ```
> 
> I think the problem is before that because it should not redirect to /admin/index.php?controller=AdminLogin&token=bc481a3ebe97be186d8430c227465fe5.
> That's why I tried to do the same thing with the first wget command and the `token`.
> And I also tried to pass `stay_logged_in=1` and `redirect=AdminProducts` in `--post-data`.
> But same problem...


It redirects to login because the cookie is not valid.
I don't see your request to login, could you give us all the information to reproduce please?

**Comment by guigplt** [comment]
The request to login is the first wget command : 
`wget --save-cookies /var/www/xxxxxxxx/cookies.txt --keep-session-cookies --post-data 'email=xxxxxxxx&passwd=xxxxxxxx' https://xxxxxxxx.com/admin/ -O /dev/null`

I don't understand why the cookie is not valid : I checked multiple times the email / passwd values...
Is there something else I have to pass in the --post-data, like the `token` ?

**Comment by PierreRambaud** [comment]
> The request to login is the first wget command :
> `wget --save-cookies /var/www/xxxxxxxx/cookies.txt --keep-session-cookies --post-data 'email=xxxxxxxx&passwd=xxxxxxxx' https://xxxxxxxx.com/admin/ -O /dev/null`
> 
> I don't understand why the cookie is not valid : I checked multiple times the email / passwd values...
> Is there something else I have to pass in the --post-data, like the `token` ?

You must check your connection request. Some pieces of information are missing.
![image](https://user-images.githubusercontent.com/1462701/91875259-8da8bd80-ec7b-11ea-855f-12dea90c174a.png)

```bash
wget --no-check-certificate --save-cookies cookies.txt --keep-session-cookies --post-data 'submitLogin=1&controller=AdminLogin&ajax=1&email=demo@prestashop.com&passwd=testtest' http://ps-develop.localhost/admin-dev/ -qO-
# {"hasErrors":false,"redirect":"http:\/\/ps-develop.localhost\/admin-dev\/index.php?controller=AdminDashboard"}
```

But after that, I'm not able to reuse the cookie :thinking:

**Comment by guigplt** [comment]
I tried to pass `ajax`, `token`, `controller`, `submitLogin`, `redirect` in --post-data and I'm still redirected to login.
I can't see Form Data in Google inspector : 
![image](https://user-images.githubusercontent.com/44002621/91882484-5211f180-ec83-11ea-9124-e562f59280ce.png)
Where do you find it ?

**Comment by PierreRambaud** [comment]
> I tried to pass `ajax`, `token`, `controller`, `submitLogin`, `redirect` in --post-data and I'm still redirected to login.
> I can't see Form Data in Google inspector :
> ![image](https://user-images.githubusercontent.com/44002621/91882484-5211f180-ec83-11ea-9124-e562f59280ce.png)
> Where do you find it ?

Just after clicking on the submit button (in the login form)

**Comment by guigplt** [comment]
That's what I do but I don't have form data...

Don't you have any idea why the cookie is not valid ?

**Comment by PierreRambaud** [comment]
> That's what I do but I don't have form data...
> 
> Don't you have any idea why the cookie is not valid ?

If you fix the security token it should be ok with this script, it's working for me, I'm properly connected :)
```
#!/bin/bash
wget --no-check-certificate --save-cookies cookies.txt --keep-session-cookies --post-data 'submitLogin=1&controller=AdminLogin&ajax=1&email=demo@prestashop.com&passwd=testtest' http://ps-develop.localhost/admin-dev/ -O /dev/null
wget  --no-check-certificate --load-cookies cookies.txt 'http://ps-develop.localhost/admin-dev/index.php/configure/advanced/sql-requests/1/export' -O export.csv -o _token.txt 
_token=$(grep _token=* _token.txt | awk -F"=" '{print $3}' | grep -v following)
echo "${_token}"
wget  --no-check-certificate --load-cookies cookies.txt "http://ps-develop.localhost/admin-dev/index.php/configure/advanced/sql-requests/1/export?_token=${_token}" -O export.csv
```

**Comment by guigplt** [comment]
It works perfect now !
I think it was because of `controller=AdminLogin` missing in `--post-data`
Thanks a lot @PierreRambaud 👍

**Comment by PierreRambaud** [comment]
> It works perfect now !
> I think it was because of `controller=AdminLogin` missing in `--post-data`
> Thanks a lot @PierreRambaud

You're welcome.

Don't hesitate to create a little tutorial on the devdocs, if you think it's relevant :wink:
