### ISSUE TITLE
Register a customer through webservice: login authentication fails (password problem) 1.7.6.5

### ISSUE THREAD

**Issue by alissimo** [PrestaShop/PrestaShop#20766]
Hi, 
I have prestashop 1.7.6.5 (ubuntu 20.04 with php 7.2.33)
I activated webservice and I can create correctly a customer with a php script following the example in the 1.7 docs 
The problem is that the login for this created user doesnt work: 'authentication failed' is the message. 
If i reset the password through the apposite web procedure login works.
If i create a customer directly from the website, the login works correctly... so the problem is only when customer is created by webservice, maybe because it uses a different encryption method?!?

The script is this:

```
require_once('PSWebServiceLibrary.php');
try {
    // creating webservice access
    $myapikey ='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    $webService = new PrestaShopWebservice('https://xxxxxxxx.xxxxxxxxx.xxx', $myapikey, false);
    // call to retrieve the blank schema
    $blankXml = $webService->get(['url' => 'https://xxxxxxxx.xxxxxxxxx.xxx/api/customers?schema=blank']);
    $customerFields = $blankXml->customer->children();
$customerFields->firstname = 'Test Name';
$customerFields->lastname = 'Test Surname';
$customerFields->email = 'test@mydomain.com';
$customerFields->password ='mypassword';

$createdXml = $webService->add([
   'resource' => 'customers',
   'postXml' => $blankXml->asXML(),
]);
$newCustomerFields = $createdXml->customer->children();
echo 'Customer created with ID ' . $newCustomerFields->id . PHP_EOL;
} catch (PrestaShopWebserviceException $ex) {
    // Shows a message related to the error
    echo 'Other error: <br />' . $ex->getMessage();
}

```

The user is created and I see a hashed password in the db for this user but login doesnt work...

**Comment by khouloudbelguith** [comment]
Hi @alissimo,

Thanks to check with this [solution](https://github.com/PrestaShop/PrestaShop/issues/16935#issuecomment-569725322), check and feedback.

Thanks!

**Comment by alissimo** [comment]
> Hi @alissimo,
> 
> Thanks to check with this [solution](https://github.com/PrestaShop/PrestaShop/issues/16935#issuecomment-569725322), check and feedback.
> 
> Thanks!

Hi, this link is for make external login with webservice... My problem instead is that traditional login (from the standard login form of my prestashop website) for the users created with the webservice doesnt work....

**Comment by khouloudbelguith** [comment]
@alissimo, I did not manage to reproduce the issue with PS1.7.6.7.
I used this script
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
 <customer>
   <email>test@test.com</email>
   <firstname>khouloud</firstname>
   <lastname>belguith</lastname>
   <passwd>abc123</passwd>
   <active>1</active>
   <associations>
      <groups>
        <group>
          <id>3</id>
        </group>
      </groups>
   </associations>
 </customer>
</prestashop>
```
Thanks to check if your customer is enabled
If not, you need to add the `<active>1</active>`

Thanks to check and feedback.

**Comment by SimonGrn** [comment]
hello @alissimo, 
please think about using the template and not deleting everything when you submit an issue.

Thanks in advance.

**Comment by alissimo** [comment]
> hello @alissimo,
> please think about using the template and not deleting everything when you submit an issue.
> 
> Thanks in advance.

sorry... you're right

**Comment by alissimo** [comment]
> @alissimo, I did not manage to reproduce the issue with PS1.7.6.7.
> I used this script
> 
> ```
> <prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
>  <customer>
>    <email>test@test.com</email>
>    <firstname>khouloud</firstname>
>    <lastname>belguith</lastname>
>    <passwd>abc123</passwd>
>    <active>1</active>
>    <associations>
>       <groups>
>         <group>
>           <id>3</id>
>         </group>
>       </groups>
>    </associations>
>  </customer>
> </prestashop>
> ```
> 
> Thanks to check if your customer is enabled
> If not, you need to add the `<active>1</active>`
> 
> Thanks to check and feedback.

yes, tried... even if i add active ... is the same... 
The problem is how webservice stores the password... seems different from how normal registration stores it...

**Comment by alissimo** [comment]
Found the issue!
The documentation here is wrong: the correct field is not 'password' but 'passwd'
https://devdocs.prestashop.com/1.7/webservice/tutorials/prestashop-webservice-lib/create-resource/

In this way it works...

**Comment by SimonGrn** [comment]
Thank you @alissimo.
Ping @PrestaShop/prestashop-core-developers we may need to update the documentation ?

**Comment by Progi1984** [comment]
@SimonGrn & @PierreRambaud Docs PR : PrestaShop/docs#700

**Comment by Progi1984** [comment]
@alissimo Documentation fixed ;)

**Comment by alissimo** [comment]
yes, thx :)
