### ISSUE TITLE
Chronology problem with actionOrderStatusPostUpdate 

### ISSUE THREAD

**Issue by guirou62** [PrestaShop/PrestaShop#20772]
#### Describe the bug

I created a module to automatically change some order states to others. I used actionOrderStatusPostUpdate to apply a new State after the initial change but when I look the order status history, the chronologic change is not the good one.

#### Expected behavior

The chronologic change is not the good one : I want the ID 1 became ID 17 but I have 17 became ID 1

#### Steps to Reproduce

1. Install this module => [ataviktest.zip](https://github.com/PrestaShop/PrestaShop/files/5142426/ataviktest.zip)
2. Check if "Atavik Test" have the good position (on hook actionOrderStatusPostUpdate )
3. Go on orders page, select one of them
4. Change the state order to "Awaiting check payment"
5. Look the current state, you'll see "Awaiting check payment" as last state instead of "Authorized. To be captured by merchant"
6. In chronology states, you'll see states go from "Authorized. To be captured by merchant" to "Awaiting check payment" instead of "Awaiting check payment" to "Authorized. To be captured by merchant"

**Screenshots**

![image](https://user-images.githubusercontent.com/11886380/91574822-89149a00-e947-11ea-8925-d761efe660bc.png)

#### Additional information

* PrestaShop version: 1.7.*
* PHP version: 7.2

Thanks

**Comment by khouloudbelguith** [comment]
Hi @guirou62,

Thanks for your report.
When I tried with PS1767, I have the same issue
![image](https://user-images.githubusercontent.com/16067358/91578237-2ffa3580-e94a-11ea-9a2c-a4ae4b8d297b.png)
When I tried with 177x branch, I have this error
![image](https://user-images.githubusercontent.com/16067358/91578316-44d6c900-e94a-11ea-9826-8ebb003f0a98.png)

Thanks to check and feedback.

**Comment by guirou62** [comment]
Hi @khouloudbelguith ,

You're welcome :)

Oh really, I tried on Prestashop 1.7.7.0 and I didn't have this issue but I can understand from where comes this problem only.
For the initial issue, I'll be really interested if you find a way to solve that :)

**Comment by khouloudbelguith** [comment]
@guirou62,

>Oh really, I tried on Prestashop 1.7.7.0 and I didn't have this issue but I can understand from where comes this problem only.

Is it a module issue?

Thanks!

**Comment by guirou62** [comment]
I thought it should be a compatibility problem but I saw no changes on your prestashop version ... In all cases, I don't think it comes from my module (the code is so small ^^)

**Comment by khouloudbelguith** [comment]
@guirou62, thanks for your feedback.
As written in the [doc](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/)
```
actionOrderStatusPostUpdate

   Called after the status of an order changes.
```

But in this case, the status is wrong
![image](https://user-images.githubusercontent.com/16067358/91586953-65a51b80-e956-11ea-95ce-f66d5f4f4753.png)

Ping @PrestaShop/prestashop-core-developers thanks to correct me if I'm wrong, Thanks!

**Comment by guirou62** [comment]
Hi,

If someone has an idea about how to change the order status after an order change, I'm really interested because I'm working on a new website which will be public in a couple of weeks.

Thanks

**Comment by PierreRambaud** [comment]
> Hi,
> 
> If someone has an idea about how to change the order status after an order change, I'm really interested because I'm working on a new website which will be public in a couple of weeks.
> 
> Thanks



> @guirou62, thanks for your feedback.
> As written in the [doc](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/)
> 
> ```
> actionOrderStatusPostUpdate
> 
>    Called after the status of an order changes.
> ```
> 
> But in this case, the status is wrong
> ![image](https://user-images.githubusercontent.com/16067358/91586953-65a51b80-e956-11ea-95ce-f66d5f4f4753.png)
> 
> Ping @PrestaShop/prestashop-core-developers thanks to correct me if I'm wrong, Thanks!


No you're right, I tried and everything is working well for me.


@guirou62 If you need to edit something after an order is saved you can use `actionObjectOrderUpdateAfter`.
https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/ => 
![image](https://user-images.githubusercontent.com/1462701/101469616-44849b80-3945-11eb-815e-dabd5f1000eb.png)

**Comment by hibatallahAouadni** [comment]
Hello @guirou62 ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by RomainMazB** [comment]
Don't need to re-open the issue because we already have one open, but this issue is a real one.

I've added more details about what happens in [this other issue's comment](https://github.com/PrestaShop/PrestaShop/issues/22218#issuecomment-812449744).

Just add a clear link for those who are facing the issue to easily solve the problem with a simple workaround.
