### ISSUE TITLE
BO - Features page - an exception is displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20777]
#### Describe the bug

In the BO > Catalog > Features page, an exception is displayed after some specific steps.

#### Steps to Reproduce

1. Go to BO > Catalog > Features page
2. Create a feature
3. View feature
4. Create values
5. Update feature
6. View updated feature
7. Update 1 value
8. Filter Feature by name => NOK

Other steps to reproduce the issue

1. Create feature
2. View feature
3. Create values
4. Update feature
5. View updated feature
6. Filter value by name
7. Update 1 value => KO

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/91582523-38556f00-e950-11ea-8540-343ceab5ee1e.png)
.

#### Additional information

* PrestaShop version: 1.7.6.7, 1.7.7.x
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/qa-automation

**Comment by Progi1984** [comment]
Fixed by #21045
