### ISSUE TITLE
Payment Module with 2 payment options

### ISSUE THREAD

**Issue by andredotsilva** [PrestaShop/PrestaShop#20771]
I'm developing a payment module that will provide in one module , two payment options. 
Can anyone guide me to develop that feature. 

one of them as been implemented , but i need to implement the second one, and put all the functions in a include file, and in hookPaymentOptions() method, call it and make work. 

Thanks fot the help

**Comment by matks** [comment]
I think everything is explained here https://devdocs.prestashop.com/1.7/modules/payment/

and with this example https://github.com/PrestaShop/paymentexample => https://github.com/PrestaShop/paymentexample/pull/14

**Comment by andredotsilva** [comment]
@matks thanks 
I'm using this exemple, but my issue is, i need to put all the payment process in other file, in a include folder... and i'm having touble with the call method
