### ISSUE TITLE
413 Request Entity Too large - when editing e-mail templates

### ISSUE THREAD

**Issue by mmursalov** [PrestaShop/PrestaShop#20782]
#### Describe the bug

Every time I  try to modify E-Mail templates and still getting the following error message every time I try to save it: 413 Request Entity Too large

I have reached out to the hosting and they have increased all the limits in php.ini and .htaccess but the issue is still there. They are telling me to raise it with Prestashop support team. What else needs to be done, as I am currently unable to make changes in e-mail templates.

The following limits were adjusted:

file_uploads = On
memory_limit = 2048M
max_input_vars = 2000
max_execution_time = 6000
post_max_size = 2048M
upload_max_filesize = 2048M
max_input_time=-1
max_input_vars=10000
suhosin.get.max_vars = 10000
suhosin.post.max_vars = 10000

#### Expected behavior

I should be able to customise E-mail templates

#### Steps to Reproduce

1. Go to 'Admin -> International -> Translations -> Modify Transaltions'
2. Choose  'Email Translations -> Body -> Select a theme -> Language' click Modify
3. Scroll down to 'Core emails' and then choose any template. Try to edit either HTML mode or TXT and hit Save. It will give 413 error emssage

**Screenshots**

Step 1: https://prnt.sc/u7yt1l
Step 2: https://prnt.sc/u7yt9t
Step 3: https://prnt.sc/u7ytiw
Step 4: https://prnt.sc/u7yttd
#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3.6

**Comment by khouloudbelguith** [comment]
Hi @mmursalov,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record

[Translations • 1767.mp4.zip](https://github.com/PrestaShop/PrestaShop/files/5149177/Translations.1767.mp4.zip)

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.
Thanks to check and feedback.

**Comment by mmursalov** [comment]
Hi,

Thank you for your swift response. Unfortunately, my earlier statement on the PHP version was incorrect. The one the web site is running on is 7.2.33 and one compatible with PrestaShop 1.7.6, but I keep getting this error message and I do not know what to do.

Below is the info from PrestaShop Admin page for PHP

PHP version: 7.2.33

Memory limit: 2048M

Max execution time: 6000

Upload Max File size: 2048M
---------------------------------

What should I do next please?

Thanks.
Murad.

**Comment by khouloudbelguith** [comment]
@mmursalov,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by mmursalov** [comment]
Hi,

Would it help if I give access to the FTP and the backend admin?

Things such as PHP, apache and javascript logs I cannot share, as I it is hosted on godaddy and I do not have access to that level.

Debug mode was on, but the link that you shared does not tell where it stores the debug report. Could you please advise?

The version of Prestashop is 1.7.6.7

Server information Linux  x86_64 --> it does not give an OS version.

Server software version: Apache

PHP version: 7.2.33

Memory limit: 2048M

Max execution time: 6000

Upload Max File size: 2048M

MySQL version: 5.6.49-cll-lve

**Comment by khouloudbelguith** [comment]
@mmursalov,

>Would it help if I give access to the FTP and the backend admin?

On this github repository there is no software support. This is an open source project.

>Things such as PHP, apache and javascript logs I cannot share, as I it is hosted on godaddy and I do not have access to that level.

You need to check it with your host.

>Debug mode was on, but the link that you shared does not tell where it stores the debug report. Could you please advise?

When Debug mode is enabled, you should do the same steps and check if there is any exception displayed.

Thanks!

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
If you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Thank you!
