### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by rahul2cool82** [PrestaShop/PrestaShop#20781]
Hello, rahul this side and I am getting an error while installing this module , can you please instruct me how to install this module on prestashop 1.7.6.3.
Thank you

**Comment by SimonGrn** [comment]
Dear @rahul2cool82 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
