### ISSUE TITLE
Price rounding does not work

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#20787]
After all updates, and many, many topics, problem for price rounding is still not solved.

So far, googled a lot of forums on PS, but no solution.

—— > Tried this fix :

Change the file “classes/Tools.php” and find the “public static function ps_round($value, $precision = 0, $round_mode = null)”

Add the following line:

if($precision == 0){ $precision = 2; } //Or any other number you want

<——–

Somehow the precision was always empty this fixed it for me.
Did something, but not exact.

When i use 4.94, incl. 21% tax, price round up to 4.95 – thats good.
If i use 4.95, incl 21% tax, price rounds up to 4.96 – not good.

Strange thing, when i use a combinations which add 10 incl, tax on price 4.95, price does displayes corrects at 14.95.

What am i doing wrong?

Using PS 1.7.5, price rounding in shop parameters is set at round up to closest value, using 2 decimals and rounding on each rule.

If i use round up when halfway there, price 4.94 becomes 4.95 – thats good.
But – the price + combination that became 14.95 (good ) now suddenly becomes 14.94 (wrong).

When looking in cart, product displays 4.95 (correct) but also shows (and counts) 4.96 (wrong).

excl. vat price is hardcoded to use 5 decimals (which i did not asked for, and use the 2 decimal setting in shop parameters) , which causes the problems of rounding in price incl. vat.

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by SimonGrn** [comment]
@loetje88 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 
Thank you
