### ISSUE TITLE
BO - Orders page - Delivery option is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20793]
#### Describe the bug

When we change the default carrier, in the BO > Orders => Add new order page => the Delivery option is not correct

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO > Shipping > Preferences
2. Change the default carrier to "My carrier"
![image](https://user-images.githubusercontent.com/16067358/91734366-26bbd380-ebab-11ea-9b27-476a92662bb9.png)
3. BO > Orders => Add new order page
4. Add some product
5. see the Delivery option is not correct
![image](https://user-images.githubusercontent.com/16067358/91734591-671b5180-ebab-11ea-937f-9e7c4a868892.png)
![image](https://user-images.githubusercontent.com/16067358/91734740-9762f000-ebab-11ea-91e2-ab60356b637a.png)

#### Additional information

* PrestaShop version: 1.7.6.7, 177x
* PHP version: 7.2

**Comment by Shock451** [comment]
Can I take on this issue?

**Comment by matks** [comment]
@Shock451 Please be our guest 😄

**Comment by khouloudbelguith** [comment]
Duplicate of #12682
