### ISSUE TITLE
Module manager UI availability

### ISSUE THREAD

**Issue by fkomaralp** [PrestaShop/PrestaShop#20797]
#### Is your feature request related to a problem?

I'm creating some modules on PrestaShop 1.7.6.5. I need to reinstall/uninstall(Without deleting module folder)/disable/enable my module sometimes. If I have a lot of modules in the Other section; non-installed modules cannot showing up. And "Other" sticky (like dragable) box area not showing up on the Other list's bottom. Therefore I need to go to "Other" section with different way. I dont have next version of PrestaShop. So I don't know what is going on next versions.

#### Describe the solution you'd like

IDK.

#### Alternatives you've considered

https://drive.google.com/file/d/1JPVP5qxQjnK2HqQflnZDd9ujWVIs1Dw6/view

Maybe need easy(or idk, what is true words) UI?

#### Additional context

None.

**Comment by khouloudbelguith** [comment]
Hi @fkomaralp,

>I'm creating some modules on PrestaShop 1.7.6.5. I need to reinstall/uninstall(Without deleting module folder)

In the BO > Module Manager page > when we try to uninstall a module, you have two options
1. Remove a module from folder
2. do not remove a module from folder

![image](https://user-images.githubusercontent.com/16067358/91823871-30d8e300-ec3a-11ea-904b-7fca2c740ce4.png)

>If I have a lot of modules in the Other section; non-installed modules cannot showing up

Yes, Uninstalled modules are not displayed in the `Module Manager` page but they are installed in` Module Catalog` Page

>And "Other" sticky (like dragable) box area not showing up on the Other list's bottom

You can select `Other` Category
![image](https://user-images.githubusercontent.com/16067358/91824346-e9068b80-ec3a-11ea-884b-d881a565f8fa.png)
![image](https://user-images.githubusercontent.com/16067358/91824400-fd4a8880-ec3a-11ea-8b90-bdb5c9449836.png)


Thanks to check and feedback.

**Comment by fkomaralp** [comment]
I'm realy sorry about that. I didn't discover the `Module Catalog` link. You are totally true. I was searching my uninstalled module in the `Module Manager` page.

**Comment by khouloudbelguith** [comment]
@fkomaralp, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!
