### ISSUE TITLE
Add 'action' parameter to actionProductCancel hook

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#20795]
#### Is your feature request related to a problem?

Some partners complain that Inside the `actionProductCancel` hook it's not easy to know which action triggered the hook, it could be **cancel product**, **standard refund**, **partial refund** or a **return product**, while it can be guessed based on the order history, there is a lot room for errors.

#### Describe the solution you'd like
Add an 'action' parameter to the `actionProductCancel` hook, indicating which refund action is being done.

**Comment by Progi1984** [comment]
Fixed by #20794
