### ISSUE TITLE
Add two payment options to module -> one of them is in a include folder, in class

### ISSUE THREAD

**Issue by andredotsilva** [PrestaShop/PrestaShop#20803]
Hi 

I'm trying to implement in one module, two different payment options. One of them is in an include folder, payment.php file. 

How can i call that file, and class, in tha second new PaymentOption(); ? 

Hope that someone could help me :) 

Best regards

**Comment by khouloudbelguith** [comment]
Hi @andredotsilva,

On this github repository there is no software support. This is an open source project.


You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!
