### ISSUE TITLE
Release 1.7.6.8 🚀

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#20804]
This issue tracks the status of the PrestaShop 1.7.6.8 release

The 1.7.6.8 version will be a security fixes release only.

### Information

Q | A
--|--
**Type** | Patch version
**Estimated release** | 2020-09-**
**Delivery date** | 2020-09-24

### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] [Release](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.8)
- [x] Available for upgrade
- [x] Docker image

**Comment by matks** [comment]
Thank you @PierreRambaud for delivering PrestaShop 1.7.6.8

## 🚀 ✅ STATUS UPDATE

1.7.6.8 is released !
- on GitHub
- on prestashop.com
- the release note is published https://build.prestashop.com/news/prestashop-1-7-6-8-maintenance-release/
- auto-upgrade module should be able to perform upgrades to 1.7.6.8
- docker images are available
