### ISSUE TITLE
Cannot edit a product that has been deleted

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20819]
#### Steps to Reproduce

1. Install 1.7.7 beta 2.
2. Delete all products from the product list.
3. Go edit (demo) Order with refrence **KHWLILZLL**.
4. Change price of the product.
5. You cannot enter price with and without tax. The rate is fixed to 0.

### Specs

When a product is deleted and related to an order, the product base price and the tax price can be edit. 
Normally when the product exists editing the base pricing applies the tax price in the tax price field, but if the product doesn't exist, the merchant will have to set by himself the right tax on the base price.
So, the tax price wouldn't update automatically if the base price is edit and vice versa.

#### Additional information

* PrestaShop version: 1.7.7 beta 2
* PHP version: 7.2

**Comment by sarahdib** [comment]
@Hlavtox I think this is related to the error displayed in this issue #20818 

https://drive.google.com/file/d/1I_d-b40uPkKFOCmsPpJ64puVlyJs7ffj/view
Maybe the field can only display prices with no possibility to change it ?  what do you think @PrestaShop/prestashop-core-developers  ?

**Comment by marionf** [comment]
FYI @MatShir

**Comment by MatShir** [comment]
FYI Reproduced in 1.7.6.8

**Comment by MatShir** [comment]
The question is should the order page be independent and could work with a product that does not exist.

**Comment by PierreRambaud** [comment]
@MatShir You should be able to see an order, or invoice, or everything even if the product is deleted (maybe introduce the soft delete here too). It's up to you to tell us what you want :sweat_smile:

**Comment by florine2623** [comment]
Hello @Hlavtox ,

This issue is related to https://github.com/PrestaShop/PrestaShop/issues/20178

I can do the same without deleting my product. It is only the case with demo products, not with my own.

i will close your issue :)
