### ISSUE TITLE
Question about add block ps_bestsellers to other file.tpl or CMS page.

### ISSUE THREAD

**Issue by Banhack** [PrestaShop/PrestaShop#20816]
We want to add the block of best sellers inside a .tpl file. How could we do?

Thx

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
