### ISSUE TITLE
Customers cannot reorder previous orders (order history, order again)

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#20827]
#### Describe the bug

We have found on our store that it is not always possible for customers to order previous orders again. 
I.e. the order again feature of a customers order history does not always work.

#### Expected behavior

I expect customers to be able to successfully re-order previous orders

#### Steps to Reproduce

1. Login to customer account who has made previous orders
2. Go to Account (Votre Compte), Order History (Historique de vos commandes)
3. Click on Order Again (Commander à nouveau)
4. You should now come to the Address selection of the Checkout
5. Click Continue (Continuer)
6. In some cases, you will not progress to delivery selection (mode de livrasion)

**Screenshots**

Not really necessary

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

#### How to fix

You didnt expect that did you ! I do actually know how to fix this after 1 day of investigation.

Firstly, the problem occurs because:

1. the cart that is created in the "[prefix]_cart" table comes with a pre-defined value for "id_carrier". 
2. (It also comes with "delivery_option" pre-defined, but that does not seem so important)
3. "id_carrier" references a delivery option that is invalid (no longer exists or is not active)

How to fix:

1. for the relevant "[prefix]_cart" entry, simply reset "id_carrier" to 0 (zero)
1. customers will then be able to continue to delivery selection in the checkout

How to code this solution?

1. firstly, is this an acceptable solution? It is for us- we are happy for customers to choose their preferred delivery 
2. how to target carts created from the re-order feature (so we can set "id_carrier" to 0)?

**Comment by florine2623** [comment]
Hi @jonpontet ,

I've successfully reproduced your issue in PS 1.7.6.5. 
However, this issue has been fixed in PS 1.7.8.0. Please check my screen record below :
https://drive.google.com/file/d/10aDZk9l2BD7gcTqVkrW-204Nb-vWLxwN/view

Thank you for looking into it.
I'll close your issue, feel free to open a new one if you find anything else !

**Comment by jonpontet** [comment]
@florine2623 thank you for your response. Are you able to highlight the commit that fixes this issue?

**Comment by jonpontet** [comment]
@florine2623 I need a response for this please. You are still only on v1.7.6.7 so the fact that this has been fixed in v1.7.8.0 does not help me at all - when will that be released ?

**Comment by matks** [comment]
> @florine2623 I need a response for this please. You are still only on v1.7.6.7 so the fact that this has been fixed in v1.7.8.0 does not help me at all - when will that be released ?

Probably in beginning of 2021 ; March or April I guess

**Comment by jonpontet** [comment]
@matks thank you

**Comment by jonpontet** [comment]
@florine2623 @matks I would like to implement this functionality before your official release because it is really hurting our business.

Can you please highlight to me the commit(s) that fix this problem?

Thanks

**Comment by matks** [comment]
Unfortunately we are many to work on this repository, so I dont know what commit exactly fixes this :/

You might find it
- by running a github PR search like https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Amerged+order+history+is%3Apr+milestone%3A1.7.7.0+
- by using the "history" feature of github on the right file https://stackoverflow.com/questions/17888643/view-the-change-history-of-a-file-using-github-com#:~:text=How%20you%20view%20one%20commit,you%20see%20the%20whole%20commit.
