### ISSUE TITLE
SAVE BUTTON NOT WORKING

### ISSUE THREAD

**Issue by mamortola1** [PrestaShop/PrestaShop#20823]
#### Describe the bug

the save button, whenever I want to save a change I have made, keeps loading and does not let me save successfully. Also whenever I am trying to import a csv file to upload products, after I click on import, the page does not charge. 

#### Expected behavior

I expected to make the change to the specific product, click save and that it saved successfully. Same for the import of the products.
<img width="278" alt="Screenshot 2020-09-01 at 17 38 25" src="https://user-images.githubusercontent.com/70644575/91987210-0e27f680-ed2e-11ea-8259-075c40008169.png">
<img width="278" alt="Screenshot 2020-09-01 at 17 38 25" src="https://user-images.githubusercontent.com/70644575/91987251-1ed86c80-ed2e-11ea-8317-83d8e835e27a.png">

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.6.1.17
* PHP version: N/A

**Comment by sarahdib** [comment]
Hello

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope.

You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you!
