### ISSUE TITLE
Problem with ps_mainmenu

### ISSUE THREAD

**Issue by mcmolto** [PrestaShop/PrestaShop#20826]
Good afternoon,

I have this problem for quite some time, see if someone can help me to fix it.

I use the classic Prestashop menu (I have version 1.7.5.2) with several items and one of them has a drop-down submenu. Everything works fine until I place the mouse over another of the elements and return to the drop-down menu that does not appear again until I reload the page. If I move the mouse across the page and I only go through that menu there is no problem, it is when I pass over one of the other menu items that automatically the one with the submenu sets it to display: none. I have tried to reinitialize the module and where looked it may be by assigning this display: none, but I can't find it. If I remove that line in the code inspector, it works fine, but hovering over another menu item brings it back.

I hope I have explained myself well. Can someone help me please?

A greeting.

**Comment by florine2623** [comment]
Hi @mcmolto ,

Could you explain the steps to reproduce as well as add some screenshot for more clarity ?

Thanks!

**Comment by mcdado** [comment]
> Hi @mcdado ,
> 
> Could you explain the steps to reproduce as well as add some screenshot for more clarity ?
> 
> Thanks!

wrong tag

**Comment by mcmolto** [comment]
Hi @florine2623, thanks for answering 

1. The submenu is seen if I put the mouse over the item.
2. I put the mouse on another menu item.
3. I go back to the first one and it no longer appears being the element as display: none.

![Step 1](https://user-images.githubusercontent.com/69503519/92093421-a0cea100-edd3-11ea-92c3-3a7e3c8c578a.png)
![Step 3 1](https://user-images.githubusercontent.com/69503519/92093420-a0360a80-edd3-11ea-84c5-c5b2089d0f07.png)
![step 3 2](https://user-images.githubusercontent.com/69503519/92093418-9f9d7400-edd3-11ea-8a29-55916d6d6b59.png)

**Comment by florine2623** [comment]
Hi @mcmolto ,

It seems like your are not using Classic theme and are using an external theme. In that regard, I suggest you to contact directly the developer of that theme.
You can also request support from our support team here : https://addons.prestashop.com/en/388-support

Thank you for your understanding, I'll close this issue.
