### ISSUE TITLE
Suppliers import missing [short_description] field issues

### ISSUE THREAD

**Issue by letwang** [PrestaShop/PrestaShop#20834]
Advanced Parameters -> Import

When you select Suppliers for import, the right side prompts for available fields:

ID
Active (0/1)
Name
Description
Short description
Meta title
Meta keywords
Meta description
Image URL
ID / Name of group shop
However, ps_supplier_lang does not contain short_description field.

Request the PrestaShop official to add the short_description field.

**Comment by florine2623** [comment]
Hello @letwang ,

could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by letwang** [comment]
Server information Darwin Darwin Kernel Version 18.6.0: Sun Apr 28 18:06:45 PDT 2019; root:xnu-4903.261.4~6/RELEASE_X86_64 x86_64

Server software version: Apache/2.4.34 (Unix) PHP/7.1.23 mod_perl/2.0.9 Perl/v5.18.4

PHP version: 7.1.23

Memory limit: 1G

Max execution time: 0

Upload Max File size: 1024M

PrestaShop version: 1.7.6.7

Shop URL: http://127.0.0.1/prestashop/

Shop path: /Users/workspace/prestashop

Current theme in use: classic
Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

MySQL version: 8.0.21

MySQL server: 127.0.0.1

MySQL name: prestashop

MySQL user: root

Tables prefix: ps_

MySQL engine: InnoDB

MySQL driver: DbPDO

**Comment by letwang** [comment]
<img width="1203" alt="2" src="https://user-images.githubusercontent.com/3644168/92292510-1bbcc680-ef50-11ea-8671-dcb39b77368d.png">
<img width="557" alt="1" src="https://user-images.githubusercontent.com/3644168/92292512-1e1f2080-ef50-11ea-8224-c6794dec450f.png">

**Comment by khouloudbelguith** [comment]
Hi @letwang,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.7 and 1.7.7.x branch.
In the Import page, the `Short description` field exists
![image](https://user-images.githubusercontent.com/16067358/92368377-efdc4500-f0f7-11ea-9e2b-11318cd3f497.png)
![image](https://user-images.githubusercontent.com/16067358/92368416-fe2a6100-f0f7-11ea-8418-9a7f5a1cb142.png)
In the BO > Suppliers page, the `Short description` field does'nt exist
![image](https://user-images.githubusercontent.com/16067358/92368544-27e38800-f0f8-11ea-837f-00b9cf7c56f6.png)

Ping @PrestaShop/prestashop-product-team, there are two solutions to fix the issue
1. Remove the `Short description` field from the import page
2. Add the Short description field to the supplier

What do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi there! You're absolutely right, there is no 'Short Description' section for the suppliers while there is one for the brands. Hard to tell if it has been removed on purpose or if it is missing... Most of the time, brands and suppliers share the same behavior but we can guess that the needs regarding their display might not be exactly the same. 

@letwang, is it a feature you would need for your suppliers? I can understand the content focus on the brands but I don't know for the suppliers.

**Comment by letwang** [comment]
The current behavior is inconsistent. There are places to import, but the database does not. Can they be consistent?

**Comment by LouiseBonnard** [comment]
Indeed the current behavior is inconsistent but before making any decision to make it consistent (either adding it to the supplier page or deleting it from the import), I wanted to ask you about the usage. Do you need the short description to handle your suppliers or not?

**Comment by letwang** [comment]
My problem has been solved. I added a field, and at the same time as a bug, I gave the official feedback.

**Comment by LouiseBonnard** [comment]
Alright so I would recommend to **add a short description field to the supplier page**.

**Comment by letwang** [comment]
good job!

**Comment by LouiseBonnard** [comment]
Oops... this issue must stay open in the debug backlog, otherwise it will never be fixed. But if you already fixed it on your end, @letwang, or if you think you can do it, do feel free to [contribute to this open source project](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines) by sharing your fix in a pull request. :-)

**Comment by kpodemski** [comment]
@PrestaShop/product-team 

I've submitted a PR to remove this field from the Importer. I don't think we need a `short_description` for suppliers, but if you want to keep Louise's suggestion feel free to close the PR.

https://github.com/PrestaShop/PrestaShop/pull/29739
