### ISSUE TITLE
Updates doesn't appear instantly  

### ISSUE THREAD

**Issue by xMarlin** [PrestaShop/PrestaShop#20837]
while i update or add new menu items or products or edit anything that related to be appear on frontend it doesn't show up instantly  , i have to wait for almost 2 hours to the updates shows up on the frontend , 
1 - i have tried a new installed browser 
2 - i have cleared the cache and cookies
3 - i have also tried it on new different machine
4 - i have also tried it on new server host
and nothing seems to be my issue 
after i made some researches i found alot of users complains of this issue and there's no fix for it since Version 1.7 to the latest version so i hope you guys to fix it as soon as possible , 
also i wanna mention that i have checked the database on my server side and i found the updates inside the tables but it still doesn't appear to frontend
thanks
i hope that i have clarify everything  
[ Sorry about my english ]

**Comment by SimonGrn** [comment]
Dear @xMarlin 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
