### ISSUE TITLE
Hardcoded color values on theme core switchEditAddressButtonColor

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#20833]
#### Describe the bug

https://github.com/PrestaShop/PrestaShop/blob/f3ea0384869e849e58a5663e4c8446733f27a0b3/themes/_core/js/checkout-address.js#L94-L103

#### Expected behavior
These values must be defined in theme. For example on data-color attribute or adding class.

#### Steps to Reproduce

0. Enable custom theme with diferent colors
1. Create invalid address
2. Select invalid address on cart (step 2)
3. Then, edit button change to hardcoded value.

**Screenshots**
Before change addres to invalid one
![image](https://user-images.githubusercontent.com/194784/92024529-9a521200-ed5e-11ea-805b-31db999d0394.png)

After
![image](https://user-images.githubusercontent.com/194784/92024424-7c84ad00-ed5e-11ea-8f5a-bb8191676178.png)

#### Additional information

* PrestaShop version: 1.7.6 and probably up to develop
* PHP version: 7.1

**Comment by kpodemski** [comment]
That's a good idea, and i think it's not BC if we decide to fetch `data-color` only if it exists and not have it by default

btw. i haven't noticed this piece of code for years, this is nasty solution 😱

**Comment by florine2623** [comment]
Hi @davidglezz ,
Thanks for the suggestion !
I'll ping our dev team to get their point of view on it.
Please stay tuned.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
The title says it all ! There are some hardcoded color values on a core file.
Is it possible to change this ? @davidglezz suggests creating an attribute for that.
Thanks!

**Comment by PierreRambaud** [comment]
Everything is possible, and of course, if we receive a pull request proposing to add a `data-color` in order to make this color configurable by the theme, we will be glad to review it and merge it :+1:
