### ISSUE TITLE
Multishop, Add Product, Edit Product, Symfony Exception Prestashop 1.7.6.3

### ISSUE THREAD

**Issue by thequickmick** [PrestaShop/PrestaShop#20832]
#### Describe the bug

After we use 10 Sub shops, we had a Critical Error. Is There A Maximum amount of Subshops?
I Create a new one, like every Time before.

I try to add a New Product and got a Symfony Error.

**Screenshots**

![error_presta](https://user-images.githubusercontent.com/60973509/92012607-f1e78200-ed4c-11ea-86c1-02775fa08236.PNG)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2 / 7.3

**Comment by florine2623** [comment]
Hi @thequickmick ,
There is no limit to the number of multishop you wish to have in your BO.
I've successfully managed to add 12 shops into my BO.
Here's my screenshot :
![Capture d’écran 2020-09-03 à 13 16 13](https://user-images.githubusercontent.com/16019289/92108445-b352d580-ede7-11ea-808e-66e272c857fe.png)


Could you clear your cache and try again ?
From BO > Advanced Parameters > Performances > Clear cache
From FTP > go to `/var/cache` > delete `/dev` and `/prod`

PrestaShop 1.7.6.3 is not compatible with PHP 7.3, here's more information about the system requirements :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!
