### ISSUE TITLE
Be able to set a value on submit buttons

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#20838]
#### Is your feature request related to a problem?

I am using helperForm and multiple_fieldsets. I would like to distinguish for which fieldset was the submit button pressed.

#### Describe the solution you'd like

the simpliest solution would be if I would be able to set value for submit button

like as:
````
           $form =  array(
                'legend' => array(... ),
                'input' =>   array(... ),
                'submit' => array(
                    'title' => $this->l('Save'),
                    'value' =>$myFieldsetID,
                ) );
````  

and write this value (if is set) into template admin../themes/default/template/helpers/form/form.tpl

instead of value="1"

![ps19](https://user-images.githubusercontent.com/3242659/92080466-e8e4c800-edc1-11ea-9080-7321a6279f9d.png)

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

@Eva-F has a suggestion regarding the setting of a value on submit buttons.
What is your opinion on it ?

Thanks!

**Comment by PierreRambaud** [comment]
It's a good idea, we should be able to use a custom value for the submit button :+1:

**Comment by hibatallahAouadni** [comment]
Hello @Eva-F 

We had @PierreRambaud approval, so . I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Eva-F** [comment]
I am sorry -  now i do not unfortunally have any time to do it. 
In my modules I have went around this problem either using overriding or using jquery command - not directly - although the direct change  ( as I  suggested in this issue) would be much simplier.
