### ISSUE TITLE
Secure calls to addons.prestashop.com behind Circuit Breaker

### ISSUE THREAD

**Issue by letwang** [PrestaShop/PrestaShop#20835]
There are too many prestashop remote Api calls in the website, which causes the website to be slow. In the case of the guest's poor internet speed, the speed is slower, and the slowness is unbearable.
## 1.hosts:
```
sudo vim /etc/hosts
127.0.0.1 api.prestashop.com
127.0.0.1 api-addons.prestashop.com
```
## 2.increase the cache validity period:
```
public function isFresh($file, $timeout = 604800)
     {
         $timeout = $timeout * 100000;// todo...

         if (($time = @filemtime(_PS_ROOT_DIR_. $file)) && filesize(_PS_ROOT_DIR_. $file)> 0) {
             return (time()-$time) <$timeout;
         }

         return false;
     }
```
https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/controller/AdminController.php#L4276

## 3.DNS
In addition, the calling methods of file_get_contents, Tools::file_get_contents, and stream have very poor performance, and DNS caching cannot be used. It is recommended that all CURL calls be transposed:
https://github.com/letwang/HookPHP/blob/master/vendor/Hook/Http/Curl.php

**Comment by florine2623** [comment]
Hi @letwang ,
Thanks for the suggestion.

Could you give the steps to reproduce in order to see the exact issue regarding the API calls ?

Thank you!

**Comment by letwang** [comment]
All the interfaces in the background, the more typical ones are:
http://127.0.0.1/prestashop1767/admin/index.php/improve/modules/manage?_token=

- PHP 7.1
- PrestaShop 1.7.6.7

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
All these calls are only in the backend, so people using the website are not affected. But the current cache is one week, it's enough I think, and shouldn't be improved. The real problem is, If addons.prestashop.com is slow, we should handle the request with a circuit breaker.

**Comment by Olivier-Henry** [comment]
hi,
i have a suggest for a little improvement of  current behavior. 
when i take a look on code, it appear than all api call are made at the same time when cache time has expired. So, if the one week cache expire on sunday, the first user to connect monday morning, will get all api call in first query. If each query take 30 seconds, you can calculate...

A simple way is divide to better reign, maybe refresh only one cache by day of week.
The user will have the same behavior only if he doesn't login to back office for 2 weeks...

Another possible way, would be to extract the code in a script executed by a periodic cron.

Best regards,
Olivier

**Comment by PierreRambaud** [comment]
> hi,
> i have a suggest for a little improvement of current behavior.
> when i take a look on code, it appear than all api call are made at the same time when cache time has expired. So, if the one week cache expire on sunday, the first user to connect monday morning, will get all api call in first query. If each query take 30 seconds, you can calculate...
> 
> A simple way is divide to better reign, maybe refresh only one cache by day of week.
> The user will have the same behavior only if he doesn't login to back office for 2 weeks...
> 
> Another possible way, would be to extract the code in a script executed by a periodic cron.
> 
> Best regards,
> Olivier

The problem with cron is that some people are not able to trigger them because of server configuration.

**Comment by Olivier-Henry** [comment]
Oh i see, and the minimum system requirements don't leave many possibilities... after thinking, my first suggest is not efficient, it has same behavior if the user login after one week.

**Comment by PierreRambaud** [comment]
> Oh i see, and the minimum system requirements don't leave many possibilities... after thinking, my first suggest is not efficient, it has same behavior if the user login after one week.

The circuit breaker is the solution here I think

**Comment by Progi1984** [comment]
@PierreRambaud I agree with you.

**Comment by letwang** [comment]
> > Oh i see, and the minimum system requirements don't leave many possibilities... after thinking, my first suggest is not efficient, it has same behavior if the user login after one week.
> 
> The circuit breaker is the solution here I think

I agree with you.

**Comment by matks** [comment]
Sorry for late answer. Topic confirmed, moved to `To Do` and added to epic https://github.com/PrestaShop/PrestaShop/issues/12851 . I also modified the title.

**Comment by letwang** [comment]
6666

**Comment by marionf** [comment]
Following the differentiation between the open-source project and the company to come in [V8](https://github.com/PrestaShop/PrestaShop/issues/24111), I close this issue as there will be no more calls to api.prestashop.com and api-addons.prestashop.com
