### ISSUE TITLE
Wrong search result

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20845]
Searching a product in customer site we found too many results, and in the wrong order. Even changing the settings the results remain the same.

If I search for "Kyrie 6", only products that have that string in their name should appear.

1. Go to searchbar
2. Search Kyrie 6
3. Relevant results are in page 3 (screenshot 2) but should be in page 1 (screenshot 1)

![Schermata 2020-09-03 alle 14 42 16](https://user-images.githubusercontent.com/70702218/92116580-4db91600-edf4-11ea-8596-347afb3bfa11.png)
![result](https://user-images.githubusercontent.com/70702218/92116570-48f46200-edf4-11ea-9dba-2a4863f7a728.png)

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @oimmaginazione ,
First downgrade your PHP version to 7.2 :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I can't reproduce your issue on PS 1.7.6.7 using Classic theme and these versions of search modules :
![Capture d’écran 2020-09-03 à 15 20 37](https://user-images.githubusercontent.com/16019289/92120269-1ef16e80-edf9-11ea-8c65-fe8cc551fe24.png)

![Capture d’écran 2020-09-03 à 15 18 53](https://user-images.githubusercontent.com/16019289/92120023-d639b580-edf8-11ea-9493-6069129e9cef.png)
All products displayed are related to my search "coussin colibri"

I'll close your issue as I can't reproduce it.
