### ISSUE TITLE
Error customized product quantity

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#20840]
#### Describe the bug
Customizable item quantity available 1.

If you add a customized product to cart , the system still allows you to add the product to the cart without customization.

#### Steps to Reproduce
1. Create a customizable product  with 1 quantity in BO
2. In FO add product with customization to cart
3. In FO add product without customization to cart (this should not be allowed because the product is already in cart  and available quantity is 1)

#### Additional information
PrestaShop version: 1.7.x

**Comment by florine2623** [comment]
Hi @Codencode ,
I can't reproduce your issue in PS 1.7.6.5.

I added the last customizable product to my cart :
![Capture d’écran 2020-09-03 à 13 25 06](https://user-images.githubusercontent.com/16019289/92109208-e6499900-ede8-11ea-8794-a7ba0c53eed8.png)
When there's no more stock available I can't add to cart the product :
![Capture d’écran 2020-09-03 à 13 22 31](https://user-images.githubusercontent.com/16019289/92109065-aa163880-ede8-11ea-90d3-06cdfa3d3f1e.png)

You need to check this option in BO > Products Settings > Products Stock
![Capture d’écran 2020-09-03 à 13 24 28](https://user-images.githubusercontent.com/16019289/92109254-f8c3d280-ede8-11ea-9f6e-ff2559f29033.png)

Thanks!

**Comment by Codencode** [comment]
Hi @florine2623,

you need to add the product with customization



![Screenshot_2020-09-03 Cart](https://user-images.githubusercontent.com/2463965/92120836-d71f1700-edf9-11ea-8a9a-8386e4d689ca.png)
![Screenshot_2020-09-03 Cart(1)](https://user-images.githubusercontent.com/2463965/92121022-13eb0e00-edfa-11ea-9dfe-c921e6eac20e.png)

the add to cart button is still active


![Screenshot_2020-09-03 Customizable mug](https://user-images.githubusercontent.com/2463965/92120838-d7b7ad80-edf9-11ea-9aaa-71d551c1cef4.png)

I tested with 1.7.6.5 - 1.7.6.6 - 1.7.6.7 - 1.7.7.0

Thanks!
