### ISSUE TITLE
[FO] [Filtering] error in console when filtering with price & size

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20841]
#### Describe the bug

If I filter a product by gender, size, price range then increase or decrease the price range, I get an error: "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."

#### Expected behavior

no errors in console

#### Steps to Reproduce

1. Filter your clothes by gender
2. select a size
3. select a price range
4. change price range
5. see error

**Screenshots**

<img width="1406" alt="Capture d’écran 2020-09-03 à 12 07 20" src="https://user-images.githubusercontent.com/69145330/92101854-058ef900-edde-11ea-8fe1-465fada683b0.png">

https://drive.google.com/file/d/1jx5fbjhCw8KHcRlJKvGHXfmlfiBiCVK0/view

#### Additional information

* PrestaShop version: 1.7.7 & 1.7.8
* PHP version: 7.2

**Comment by sarahdib** [comment]
@ngodefroy what is your module version ? We try with @marionf to reproduce but we couldn't

**Comment by ngodefroy** [comment]
> @ngodefroy what is your module version ? We try with @marionf to reproduce but we couldn't

Hello @sarahdib ,
I re tested it and don't reproduce the issue anymore, thus I close it.
Thank you
