### ISSUE TITLE
Can't translate the Contact Form Module

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#20844]
#### Describe the bug

Hello,

I can't translate the contact form module. I made a patch of this commit but it didn't work for me.

https://github.com/PrestaShop/PrestaShop/pull/15139

Thanks

**Screenshots**
**
![image](https://user-images.githubusercontent.com/25744417/92106573-e6479a00-ede4-11ea-80f3-fc66276aa9ff.png)
**

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 5.6

**Comment by florine2623** [comment]
Hi @ShaimyWinda ,
I can't reproduce your issue on neither PS 1.7.6.0 not PS 1.7.7.0, translating module ps_contactform v4.1.1 and v4.2.0 with another theme other than Classic.
![Capture d’écran 2020-09-03 à 14 47 07](https://user-images.githubusercontent.com/16019289/92116635-60cbe600-edf4-11ea-9d21-c96ed1913fe4.png)

For security purposes, please change your admin link.
Also you can upgrade your PHP version up to PHP 7.2 for your version of PrestaShop.
Make sur the theme you are using is compatible with your version of PrestaShop.

I'll close the issue as it is not reproducible.
Thanks!

**Comment by ShaimyWinda** [comment]
Hi @florine2623 
It's very strange, So why i have this issue?

thanks
