### ISSUE TITLE
Can not see Products comment made by customers 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20853]
#### Describe the bug
After purchasing my product,  clients had submitted some product feedbacks that are not displayed. Why?

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @wipprotection ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
