### ISSUE TITLE
Bad price calculation when adding specific price with taxes 

### ISSUE THREAD

**Issue by juancamunoz** [PrestaShop/PrestaShop#20851]
#### Describe the bug

When we add a discount with specific prices to a product that has a tax rule, the price shown on the website goes wrong.

#### Expected behavior

We have a product that costs 24.98€ with taxes (21%)
I add a specific price, impact 14,99€ taxes inc. 

The final price should be 9,99€. The result I have in the webpage is: 6.85€

#### Steps to Reproduce

1. Go to product page that has a tax rule on
2. Add specific price, impact, taxes included 
3. Save it

**Screenshots**
![imagen](https://user-images.githubusercontent.com/43283934/92212368-287ae500-ee92-11ea-9f40-e7a3d73c0e7d.png)
![imagen](https://user-images.githubusercontent.com/43283934/92212384-2f095c80-ee92-11ea-87d4-26c9225a3cd6.png)
![imagen](https://user-images.githubusercontent.com/43283934/92212399-3466a700-ee92-11ea-9db2-da7a921aa121.png)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @juancamunoz ,
I can't reproduce your issue on PS 1.7.6.7.
See below the screenshots :
![Capture d’écran 2020-09-04 à 11 48 20](https://user-images.githubusercontent.com/16019289/92226197-a647ec00-eea4-11ea-856f-f125ef427324.png)
![Capture d’écran 2020-09-04 à 11 48 25](https://user-images.githubusercontent.com/16019289/92226203-a811af80-eea4-11ea-9af1-b65e982faf82.png)
![Capture d’écran 2020-09-04 à 11 48 10](https://user-images.githubusercontent.com/16019289/92226208-aa740980-eea4-11ea-9d51-4071475fb989.png)

Please check if you do not have any Cart Rules of Catalog Price Rules in the Discount section.
Also, if you are logged in as a customer, depending on the group they are, there might be some discount applied to that group.

As I can't reproduce the issue, I'll close it.
Thanks!

**Comment by juancamunoz** [comment]
@florine2623 There's no cart rules or catalog price rules in the discount session. The version 1.7.5.2 and yours, are the same? doesn't it matters?

**Comment by SimonGrn** [comment]
>The version 1.7.5.2 and yours, are the same? doesn't it matters?

It means your problem is fixed in PrestaShop version 1.7.6.7. You need to upgrade your PrestaShop version to get the fix.
