### ISSUE TITLE
BO - Module / Error when trying to install module

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#20852]
#### Describe the bug

An error message is displayed when trying to install a module from the "module catalog" section and when trying to install a modul from the "upload module" button the install process seems to be stuck in a loop

#### Expected behavior

The module installation should work correctly

#### Steps to Reproduce

**Error from module catalog**
1. Go to BO/Improve/Modules/modules catalog
2. Select one of the free module and click on the install button
3. See error => a error message is displayed in the top right corner

**Error from the "upload module" button**
1. Go to BO/Improve/Modules/modules manager
2. Click on the "upload a module" button and select a zip module to upload
3. See error => the module install process is in a loop

**Screenshots**
**Error from the module catalog section**
https://drive.google.com/file/d/1FOPgIvVTvPTVTMLZmdquYzGrAbXBRNql/view?usp=sharing

**Error from the "upload a module" button**
The process is stuck on this step
![image](https://user-images.githubusercontent.com/40635814/92219460-e4401280-ee9a-11ea-8e0d-0c7082de0fba.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by eternoendless** [comment]
We might take this chance to improve the error reporting?

**Comment by khouloudbelguith** [comment]
Hi!

I found that with develop other actions do not work

- Reset
- Uninstall
- Disable

![image](https://user-images.githubusercontent.com/16067358/92257262-3736bb80-eed5-11ea-91d7-5658a9b9efc5.png)

Thanks!

**Comment by matks** [comment]
FYI the issue is actually a timeout:
```
[Thu Sep 10 18:03:47.109592 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /Users/mFerment/www/prestashop/PrestaShop/vendor/twig/twig/src/Node/Node.php on line 217, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.110985 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP Stack trace:, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.111014 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP   1. {main}() /Users/mFerment/www/prestashop/PrestaShop/admin-dev/index.php:0, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.111145 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP   2. AppKernel->handle() /Users/mFerment/www/prestashop/PrestaShop/admin-dev/index.php:82, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.111168 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /Users/mFerment/www/prestashop/PrestaShop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.111187 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /Users/mFerment/www/prestashop/PrestaShop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68, referer: http://localhost:8080/admin-dev/index.php/improve/modules/manage?_token=fV8LLcgcR7KHq5buwza1_heQuWbwKvxzr6kuzG8V0t0
[Thu Sep 10 18:03:47.111206 2020] [php7:notice] [pid 10145] [client ::1:58433] PHP   5. PrestaShopBundle\\Controller\\Admin\\Improve\\ModuleController->moduleAction() /Users/mFerment/www/prestashop/Pr
```
whose "critical part" seems to be
```
Symfony\\Bundle\\FrameworkBundle\\Console\\Application->run() /Users/mFerment/www/prestashop/PrestaShop/src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:67
```

**Comment by ngodefroy** [comment]
Also present on this page when trying to reset / uninstall / disable 

Got a 500 error https://drive.google.com/file/d/1JnMlNIdQTuf6oQLkggjv6BRR7zgKx2A1/view
