### ISSUE TITLE
Add a button to be able to remove supplier & brand logos

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#20857]
#### Is your feature request related to a problem?
I would like to remove the supplier logos but I can't.
----------------

This is currently not possible to delete the logo of a brand when uploaded by mistake.
You can either add a new logo or delete the brand. as reported [here](https://github.com/PrestaShop/PrestaShop/issues/14106)

#### Describe the solution you'd like
Remove button to unset logo.

#### Screenshot
![image](https://user-images.githubusercontent.com/194784/92238701-0a28df80-eeba-11ea-8b9d-9703e3433944.png)

#### Additional context
I consider this an important feature that could be implemented by taking advantage of the page migration

**Comment by florine2623** [comment]
Hi @davidglezz ,
Thanks for the suggestion ! I'll ping our product team in the next message.

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-product-team 
What do you think about that new feature ?
The product page will have to change too if the logo isn't displayed anymore :
![Capture d’écran 2020-09-04 à 14 54 58](https://user-images.githubusercontent.com/16019289/92241665-e4eaa000-eebe-11ea-8639-fb5819076765.png)

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @davidglezz, thanks for the suggestion, I agree, the user should be able to remove the logo if need be when editing the supplier as well as the brand information.

**Comment by davidglezz** [comment]
True, the button to remove the brands logo is also missing.
@florine2623 The product page already supports brands without a logo, so no changes would be necessary.

**Comment by Progi1984** [comment]
FYI @davidglezz The feature will be embed in 8.1 :)
