### ISSUE TITLE
Faceted search Slider Ranges with Price and Weight

### ISSUE THREAD

**Issue by Anncvl** [PrestaShop/PrestaShop#20858]
Hi!I'm using the last version of faceted search. I'm having troubles with the price and weight slider ranges. 
Right now, in prices they can slide in ranges of 1 ex: 1€, 2€, 3€ etc. Is there a way to change this ranges from 5 to 5? 0-5€, 5-10€ and so on . Same with the weight, in ranges of 100 grams per example.

Thank you in advance

**Comment by florine2623** [comment]
Hi @Anncvl ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You **must** follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 
Don't forget to add all information about your shop's system requirements, screenshots and steps to reproduce the issue.

Thank you
