### ISSUE TITLE
Allow customization of ps_faceted_search

### ISSUE THREAD

**Issue by jbenezech** [PrestaShop/PrestaShop#20865]
#### Is your feature request related to a problem?

A module can easily provide a custom search provider but often what the ps_faceted_search module does is 90% what is needed.  
At the moment, this module is difficult to reuse and customizing the search requires a completely new implementation.  

In my current project for instance, I need to be able to search products which are in 2 unrelated categories. This is a simple extra join in the query, but requires copy/paste of 99% of the ps_faceted_search module.

#### Describe the solution you'd like

PR to follow

**Comment by khouloudbelguith** [comment]
Hi @jbenezech,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
> Hi @jbenezech,
> 
> Thanks for your report.
> Ping @PrestaShop/prestashop-product-team what do you think?
> 
> Thanks!

It's ok, and already merged :D
