### ISSUE TITLE
The administrator cannot log in at the background

### ISSUE THREAD

**Issue by yoseqiu** [PrestaShop/PrestaShop#20868]
why？？？

有多个错误。

发现错误：StartTag: invalid element name 在国家_模块_列表.xml file.
发现错误：Premature end of data in tag author line 1 在国家_模块_列表.xml file.
发现错误：Premature end of data in tag module line 1 在国家_模块_列表.xml file.
发现错误：Premature end of data in tag modules line 1 在国家_模块_列表.xml file.
发现错误：AttValue: ' expected 在必须_有_模块.xml file.
发现错误：attributes construct error 在必须_有_模块.xml file.
发现错误：Couldn't find end of Start Tag badge line 1 在必须_有_模块.xml file.
发现错误：Premature end of data in tag badges line 1 在必须_有_模块.xml file.
发现错误：Premature end of data in tag module line 1 在必须_有_模块.xml file.
发现错误：Premature end of data in tag modules line 1 在必须_有_模块.xml file.

**Comment by SimonGrn** [comment]
Dear @yoseqiu 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
