### ISSUE TITLE
Dashboard - dashtrend module - incorrect behavior when selecting or unselecting a Tab

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20861]
#### Describe the bug

In the BO > Dashboard > Dashtrend  section > when we select/unselect any tab => see incorrect behavior

#### Expected behavior

Before
![image](https://user-images.githubusercontent.com/16067358/92251161-b673c180-eecc-11ea-8e88-ecd3411bc100.png)

After
![image](https://user-images.githubusercontent.com/16067358/92251141-ae1b8680-eecc-11ea-861e-2f6336faf38a.png)

#### Steps to Reproduce

1. Go to  BO > Dashboard > Dashtrend  section
2. select/unselect any tab

#### Additional information

* PrestaShop version: 177x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
PR available : https://github.com/PrestaShop/dashtrends/pull/32

**Comment by Progi1984** [comment]
Bug fixed in PrestaShop/dashtrends#32
