### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Serialc0de** [PrestaShop/PrestaShop#20867]
[https://imgur.com/a/PsgInJM](url)

**Comment by SimonGrn** [comment]
Dear @Serialc0de 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by hraudsepp** [comment]
https://www.prestashop.com/forums/topic/1027593-cannot-read-property-split-of-undefined-prestashop-1761-1767/
This forum maybe helpful for you.
Thank you.
