### ISSUE TITLE
BO - SEO & URL - when multistore is enabled, an exception is displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20863]
#### Describe the bug

When multistore is enabled, the SEO URL page => NOK
![image](https://user-images.githubusercontent.com/16067358/92260242-e379a180-eed7-11ea-97cf-c4527aa075bd.png)

When multishop feature is on, trying to enter `admin-dev/configure/shop/seo-urls` ends up with error (screenshot1). This is caused because (technically) form has inputs only when following if statement is true `if (!$this->isHostMode && !$this->isShopFeatureActive && $this->doesMainShopUrlExist)`. You can see it in code ShopUrlType.php::74. (and screenshot2)
#### Expected behavior

Expect to see working page with SEO configuration forms etc.. I am not aware why shouldn't those inputs exist when multishop is on, there might be a reason for that. Anyway it must be decided if it can be shown and/or what should be shown instead if those inputs are missing.

#### Steps to Reproduce

1. Enable Multistore
2. Create a new shop
3. Go to BO > Shop Parameters > SEO & URLs page

#### Screenshots

1.![Screenshot from 2020-08-05 12-32-17](https://user-images.githubusercontent.com/31609858/89396852-c191d100-d717-11ea-8942-48b8e16a57bc.png)
2.![Screenshot from 2020-08-05 12-38-05](https://user-images.githubusercontent.com/31609858/89397496-978cde80-d718-11ea-8359-7200e2dda506.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @marionf,

This issue ready o be tested, there is a PR available: https://github.com/PrestaShop/PrestaShop/pull/22079.
Or, we should wait for the specifications?

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 

I don't think there is a need of specifications here, the issue is quiet simple: there is an error and there shouldn't be
So, I think you can test the PR :)
If you have a question, let me know
