### ISSUE TITLE
Don't use {$base_url} gamification module

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20878]
#### Describe the bug

{$base_url} is not https

#### Steps to Reproduce

1. Go to 'AdminGamification'
2. Open console

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks for your report.
- What is the exact error in the console?
- The SSL option is enabled in your case?
- Did you `Https://?`

Thanks!

**Comment by ghost** [comment]
Hi @khouloudbelguith 

I actualy test the 1.7.7.0-beta2

Screenshot : 

![Capture d’écran de 2020-09-07 15-39-32](https://user-images.githubusercontent.com/5064590/92393604-6ee57380-f120-11ea-966b-f976b81a0d50.png)
![Capture d’écran de 2020-09-07 15-39-22](https://user-images.githubusercontent.com/5064590/92393614-70af3700-f120-11ea-91ea-510d7a864d72.png)

**Comment by khouloudbelguith** [comment]
@okom3pom, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.7 and 1770beta2
Gamification module v2.3.2
![image](https://user-images.githubusercontent.com/16067358/92394216-66da0380-f121-11ea-919f-7bd39b4e6ca3.png)
I’ll add this to the debug roadmap.

Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/9807, https://github.com/PrestaShop/PrestaShop/issues/12253

**Comment by Progi1984** [comment]
Fixed by #20940
