### ISSUE TITLE
Enable SSL and SLL on all page if url to install is SSL

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20875]
#### Is your feature request related to a problem?

Enable SSL and SLL on all page if url to install is SSL

#### Describe the solution you'd like

I test the last 1.7.7.0.beta2, if i install the shop from an https url when i go on the back office il have some mixed contents blocked and i can't close tutorial ... and other options.

If your screen resolution is low you can't acces to the option to enabled SSL on all page

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Hi @okom3pom,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/19791 to fix the issue
Your ticket is a duplicate of #10482
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10482

**Comment by ghost** [comment]
1.7.8.0 oh :) 

Sorry for duplicate.
