### ISSUE TITLE
Placing a module controller under 'parent_class_name' => 'AdminProducts' causes issues in AdminAccess

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#20872]
One of my modules had a AdminModuleController registered as a child of `AdminProducts` like this:

```
public function __construct()
{
         ....
        $this->tabs = [
            [
                'name' => 'My module controller',
                'class_name' => 'AdminMyModuleSettings',
                'visible' => true,
                'parent_class_name' => 'AdminProducts',
            ]
        ];
}
```

This made AdminProducts inaccessible for non-superadmin profiles in my shop. 
Also in AdminAccess the checkboxes for AdminProducts are unchecked, and when checking them I get a false positive (yet another issue): "Settings Updated".
Although when refreshing, the change did not take effect.

Changing the `parent_class_name` to something else solved the issue.

PS 1.7.6.7

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Thanks for your report.
I think your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10164, isn't?

Thanks to check and feedback.

**Comment by madsoliver** [comment]
Hi, thanks for the response, but no - this is another issue.

**Comment by khouloudbelguith** [comment]
@onklmaps, can you provide us a demo module to reproduce the issue.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
