### ISSUE TITLE
PrestaShop Addons returns an iframe in http instead of https

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20879]
#### Describe the bug

addons.prestashop.com return an iframe not https

#### Steps to Reproduce

Open console go to theme catalogue

I use ps_mbo 2.0.1 

Same issue closed : https://github.com/PrestaShop/PrestaShop/issues/18500 

![Capture d’écran de 2020-09-07 15-18-01](https://user-images.githubusercontent.com/5064590/92391647-59227f00-f11d-11ea-8bb0-77ee5d30c147.png)

![Capture d’écran de 2020-09-07 15-18-24](https://user-images.githubusercontent.com/5064590/92391681-6475aa80-f11d-11ea-8d3b-4cf1a92e8625.png)

#### Additional information

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php#L49

* PrestaShop version: N/A
* PHP version: N/A

**Comment by ghost** [comment]
Same for this url 

/adminXXXXX/index.php/modules/addons/modules/catalog/selection

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I did not manage to reproduce the issue with PrestaShop 1770beta2 and ps_mbo module v2.0.1.
I attached a screen record
https://drive.google.com/file/d/1VUiugNcQx6vHzMuk8CsssojEjd1JCJW3/view?usp=sharing

Thanks to check and feedback.

**Comment by ghost** [comment]
:D 

Please use https, if you don't use https, it is normal

**Comment by khouloudbelguith** [comment]
@okom3pom, yes you are right.
Still not fixed with ps_mbo v2.0.1.
I manage to reproduce the issue with PS1.7.6.7 and 1770beta2 using ps_mbo module v2.0.1.
I attached a screen record
https://drive.google.com/file/d/1OU1PTJ-pUtsS0Ep-3QPTmmI_4uwBAwYD/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/92394732-59714900-f122-11ea-8082-131b9e283886.png)

Ping @Matt75

Thanks!

**Comment by Matt75** [comment]
Issue is not in ps_mbo, we load external content from Addons, see https://github.com/PrestaShopCorp/ps_mbo/blob/master/src/AddonsSelectionLinkProvider.php#L78

Problem is on https://addons.prestashop.com/iframe/search-1.7.php page

**Comment by khouloudbelguith** [comment]
@Matt75, thanks for these clarifications.
As it is not a PrestaShop core issue.

I will close the ticket.

Thanks!

**Comment by Matt75** [comment]
@okom3pom I reported this issue to Addons team to fix source code of https://addons.prestashop.com/iframe/search-1.7.php

**Comment by Matt75** [comment]
@okom3pom Addons team has fixed this issue, thanks for reporting

**Comment by ghost** [comment]
Thank's
