### ISSUE TITLE
Data integrity / begintransaction / commit / rollback

### ISSUE THREAD

**Issue by JosephWong0610** [PrestaShop/PrestaShop#20870]
For Prestashop 1.7.6.7,

Just want to know Prestashop handled data integrity by using database transaction.

For example, when confirming order, this involves more than 1 tables, e.g. order and order details, if there is error occur during confirming order, will all data not saved?

**Comment by khouloudbelguith** [comment]
Hi @JosephWong0610,

Thanks for the report.
On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
