### ISSUE TITLE
[BO] [HELP BOXES] on  reduced screen size & while opening helpbox in another tab we get a blank page

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20877]
#### Describe the bug

Working on a reduced screen size (starting at 1199 x1556), when I click on the help boxes on some pages, it opens a tab with a blank page/
Also, on normal screen size, when I click on the button to open the help box in another tab, I get same blank page.

#### Expected behavior

Everywhere on the BO, I should be able to see the helpbox in a smaller screen size / opening the helpbox in another tab working.

#### Steps to Reproduce

**With reduced screen size:**
1. Set your screen size to 1199*1556 
2. Click on the Help box on one of the following pages:

- [ ] - Menu dashboard 

- [ ] - Orders-> shopping carts
- [ ] - Attributes & features -> attributes + features
- [ ] - Discounts->cart rules + catalog price rules
- [ ] - Customer Service-> 
- [ ] - Merchandise Returns->
- [ ] - Sell->Stats Help box not working
- [ ] - Pages configuration->Pages configuration 
- [ ] - Advanced customization 
- [ ] - Design-> Image settings 
- [ ] - Shipping Carriers-> 
- [ ] - Locations->Zones
- [ ] - Countries
- [ ] - States
- [ ] Shop parameters-
- [ ] Order settings ->Satuses
- [ ] Customer settings-> groups + titles
- [ ] Contact-> stores
- [ ] Traffic & SEO -> Search engines + referrers
- [ ] Search ->search + tags
- [ ] Shop parameters-> merchant expertise
- [ ] Advanced param-> menu
- [ ] team->permissions

3. ====>see the blank page that open in another tab

**On a normal screen size:**
Click on the box to open in new tab:
<img width="906" alt="Capture d’écran 2020-09-07 à 14 54 06" src="https://user-images.githubusercontent.com/69145330/92389900-36db3200-f11a-11ea-9bfc-23b638f7c482.png">

**Screenshots**

<img width="442" alt="Capture d’écran 2020-09-07 à 14 57 41" src="https://user-images.githubusercontent.com/69145330/92390053-7d309100-f11a-11ea-9657-10fa7a64425f.png">

#### Additional information

* PrestaShop version: 1.7.7.x & 1.7.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/92395726-187a3400-f124-11ea-9bfc-75321422addc.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by LouiseBonnard** [comment]
Hi there, it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20469. @ngodefroy, @khouloudbelguith, I let you confirm and close this issue?

**Comment by ngodefroy** [comment]
@LouiseBonnard IMO it's not a duplicate but it's closely linked to #20469 / It will be important to check that opening a new tab generate the help page and not a blank page - as it isn't mentioned in the issue..
Keeping that in mind, should I close the issue? What do you think @khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

I think they are just related.
In this issue, a blank page is displayed when we click on the help box.

Ping @ngodefroy what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
Yep, you're right, it is not explicitly mentioned but it is specified that the third button is expected to redirect to the documentation page in another window via _help.prestashop.com_: https://github.com/PrestaShop/PrestaShop/issues/20469#issuecomment-689132729. How about adding it to the previous issue so that it can reunite the two in one single issue?

**Comment by ngodefroy** [comment]
@LouiseBonnard Ok, so I just copy paste my issue into the comments section of #20469 ?

**Comment by LouiseBonnard** [comment]
Hi @ngodefroy, I've just done it in the description part, let me know if it is okay for you. ;-)

https://github.com/PrestaShop/PrestaShop/issues/20469#issue-673593463

**Comment by ngodefroy** [comment]
> Hi @ngodefroy, I've just done it in the description part, let me know if it is okay for you. ;-)
> 
> [#20469 (comment)](https://github.com/PrestaShop/PrestaShop/issues/20469#issue-673593463)

Thank you, it's good for me :)
