### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20885]
#### Describe the bug

Notifications not working, They stay at 7

#### Steps to Reproduce

1. Go to 'admin'
2. Click on 'Notifications'

#### Additional information

* PrestaShop version: 1.7.0.0-beta2
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20188 to fix the issue.
Your ticket is a duplicate of #20169
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #20169

**Comment by ghost** [comment]
Ok good;

You can explain to me how you find the duplications.

I looked in the issues before posting them but no result :)

**Comment by khouloudbelguith** [comment]
@okom3pom, you can search for issues with Labels:slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/16067358/92452285-27152980-f1be-11ea-8f9e-2887d41d4376.png)

Thanks!!
