### ISSUE TITLE
The name of the manufacturer does not go up any more in ps_facetedsearch

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#20880]
#### Describe the bug

The name of the manufacturer does not go up any more in ps_facetedsearch

#### Expected behavior

It would be necessary that the name of the manufacturer goes back as on the previous versions to be used in the product listing as before with {$product.manufacturer_name}

#### Steps to Reproduce

use version 3.5.0

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.32

**Comment by khouloudbelguith** [comment]
Hi @jeckyl,

I did not manage to reproduce the issue with PS1.7.6.7 and ps_facetedsearch v3.5.0.
I attached a screen record
https://drive.google.com/file/d/1GmBnAxfRqHbDEvr_yqa6dmpTAPShfZzc/view?usp=sharing
Thanks to check and feedback.

**Comment by jeckyl** [comment]
category with module activated
![category-with-ps_facetedsearch](https://user-images.githubusercontent.com/595633/92399207-3480d400-f12a-11ea-8c9e-81f99900231e.png)

category without module
![category-without-ps_facetedsearch](https://user-images.githubusercontent.com/595633/92399234-419dc300-f12a-11ea-9e47-57bc0f314380.png)

Home with or without module
![home-with-brand-on-product](https://user-images.githubusercontent.com/595633/92399265-4f534880-f12a-11ea-8fac-ac3d2bd10aaa.png)

As you can see, basic PrestaShop allows you to display the brand name under each product in the category page, so the module is a regression from the basic functionality and on older versions of the module it worked very well.

**Comment by khouloudbelguith** [comment]
@jeckyl, but in this case you are using a theme not provided by PrestaShop Core.
With the theme Classic, the Brand is not displayed
![image](https://user-images.githubusercontent.com/16067358/92402498-f1c1fa80-f12f-11ea-9586-dd7c0f29e1ab.png)
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by jeckyl** [comment]
The concern does not come from the template but from the basic variables proposed by PrestaShop and absent when activating this module, no link with the template it is indeed the module that causes this as shown very clearly in the screenshots provided since without this module and on the home page where it is not active it is displayed without the slightest concern.

Donc pourquoi nce module modifie les données affichées de base sur cette page et pas sur le reste du site ?

comment faire pour corriger le fonctionnement de ce module pour retrouver le fonctionne de base de PrestaShop ?

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
> Ping @PierreRambaud what do you think?
> 
> Thanks!

I think it's a good idea, this is something that can be added to the result :+1:

**Comment by iqit-commerce** [comment]
Issue is still valid in 3.6.0 of module and there is no connection with template with this issue

**Comment by jf-viguier** [comment]
Issue is still there with version 3.7.1

**Comment by jf-viguier** [comment]
The manufacturer name is displayed correctly if I uninstall faceted search module, so it's definitely a module bug.

**Comment by ioniks** [comment]
Hi,
on 1.7.7.1+ and ps_facetedsearch 3.7.1
The avalaible_later product message is not good when `ps_layered_filter_show_out_of_stock_last_on` is set to No, when set to Yes is good.

related a to #23838

**Comment by micka-fdz** [comment]
Hi. I think this issue has been fixed here: https://github.com/PrestaShop/PrestaShop/pull/28290

**Comment by matik4** [comment]
> Hi. I think this issue has been fixed here: #28290

This solved the issue for me 👌

PS 1.7.7.0

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni **micka-fdz** thought and **matick4** confirmed this issue has been fixed by #28290

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Thanks @matik4 & @leemyongpakvn @micka-fdz for the notice :rocket: 
Indeed the issue has been fixed with this PR #28290 as I didn't reproduce the issue with PS8.0.0 & ps_facetedsearch v3.8.0.
Closing the issue :tada: 

Thanks!

**Comment by HartLarsson** [comment]
I've exactly the same problem even with the fix in PR https://github.com/PrestaShop/PrestaShop/pull/28290 there is no change
