### ISSUE TITLE
Tax and tax name are not recorded

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#20887]
#### Describe the bug

Tax and tax name are not recorded

#### Expected behavior

The product needs to record the tax and its name

#### Steps to Reproduce

1. Create new order
2. Open table order_detail
3. Look columns tax_rate and tax_name

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @dariusakafest,

Thanks for your report.
I manage to reproduce the issue with PS1767 and PS1700beta2.
![image](https://user-images.githubusercontent.com/16067358/92451576-33e54d80-f1bd-11ea-9384-da667763af4a.png)
I’ll add this to the debug roadmap so that it’s fixed.
Thanks!
