### ISSUE TITLE
[BO] [Left Menu] scroll down not locked after sign out page

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20890]
#### Describe the bug

Click on orders>orders then click back on left menu scroll down and see that the menu can be scrolled down way after the last "sign out" page

#### Expected behavior

When you open for the first time the menu and you scroll down, it doesn't go belong the sign out, this behavior should be applied everywhere on the menu.

#### Steps to Reproduce

1. Go to orders>orders
2. Click on the menu
3. Scroll down 
4. See the menu bar not locked after "sign out"

**Screenshots**

https://drive.google.com/file/d/1-aEMAAZ7dla3V7kh_YkQ3Nn8MtzKaLa1/view

#### Additional information

* PrestaShop version: 1.7.7.x & 1.7.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I manage to reproduce the issue with PS1770beta2.
It is a regression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @NeOMakinG

**Comment by Progi1984** [comment]
Fixed by #20936
