### ISSUE TITLE
[BO] [Gamification][NOTIFICATIONS] IHM is broken under certain circumstances 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20892]
#### Describe the bug

When I connect on PS, I click on the crown in the top right corner to see the different badges, its ok they are correctly displayed.
If I switch to orders>orders for instance, then click back on the crown, the png badges are broken.

Same problem occurs when clicking on the notifications icon, the CSS is broken. 

#### Expected behavior

WAD

#### Steps to Reproduce

1. Go to Orders>orders (or any other menu)
2. Click on on the crown / the notifications icon
4. See the css is "broken"

**Screenshots**

https://drive.google.com/file/d/1lsa68eEh2q7YdfdWXJ5qL7va_xhjB3Mg/view

#### Additional information

* PrestaShop version: 1.7.7.x & 1.7.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I manage to reproduce the issue with PS1767 and the gamification module v2.3.2.
![image](https://user-images.githubusercontent.com/16067358/92464170-128c5d80-f1cd-11ea-8916-42e9ec78dfb0.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by ghost** [comment]
https://github.com/PrestaShop/gamification/pull/72

Dépend if you are on old controller or new controller

**Comment by SimonGrn** [comment]
@okom3pom are you sure this is related ?

**Comment by ghost** [comment]
@SimonGrn i don't see your message before, yes is related.

@ngodefroy check https://github.com/PrestaShop/gamification/pull/72#issuecomment-713427554

I just test in develop and it's ok too

**Comment by khouloudbelguith** [comment]
Hi!

This issue is fixed by https://github.com/PrestaShop/gamification/pull/78

Thank you!

**Comment by khouloudbelguith** [comment]
Duplicate of #22981

**Comment by aDamelincourt** [comment]
@hibatallahAouadni 
I manage to reproduce this issue with PrestaShop 1.7.7.3 build 1 and Gamification v2.3.2
![image](https://user-images.githubusercontent.com/79843007/112646778-21c0b900-8e48-11eb-855d-a8d0f80737a5.png)

**Comment by marionf** [comment]
Hello @aDamelincourt 

I think it's normal that you have the issue with PrestaShop 1.7.7.3 build 1 and Gamification v2.3.2 as it has been fixed in the version 2.3.3 of gamification module: https://github.com/PrestaShop/gamification/pull/78 that isn't yet released

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/gamification/pull/78
