### ISSUE TITLE
jquery-migrate is loaded two times in FO

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#20904]
#### Describe the bug

It seems like jquery-migrate is being loaded two times in FO.

#### Expected behavior

Jquery-migrate should be loaded only once.

#### Steps to Reproduce

1/ Go to FO's home page
2 Check the console

**Screenshots**
<img width="719" alt="Capture d’écran 2020-09-08 à 18 14 28" src="https://user-images.githubusercontent.com/1784781/92501772-48e2d080-f1ff-11ea-8ea8-0c3cfda5dd2a.png">

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by kpodemski** [comment]
@matthieu-rolland yes it is :)

https://github.com/PrestaShop/PrestaShop/commit/69d0ad6d9852c9fb851527a8e8e6696aea4c364f#diff-fc18ac94749cfd02190dea0a6901c491

IMO we could remove it from https://github.com/PrestaShop/PrestaShop/commit/69d0ad6d9852c9fb851527a8e8e6696aea4c364f#diff-79e3f0684afa87fb2c86eca2659f8172, it's loaded from core, earlier

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland yes it is :)
> 
> [69d0ad6#diff-fc18ac94749cfd02190dea0a6901c491](https://github.com/PrestaShop/PrestaShop/commit/69d0ad6d9852c9fb851527a8e8e6696aea4c364f#diff-fc18ac94749cfd02190dea0a6901c491)
> 
> IMO we could remove it from [69d0ad6#diff-79e3f0684afa87fb2c86eca2659f8172](https://github.com/PrestaShop/PrestaShop/commit/69d0ad6d9852c9fb851527a8e8e6696aea4c364f#diff-79e3f0684afa87fb2c86eca2659f8172), it's loaded from core, earlier

yep, that's what I did 👍  Pr coming soon

**Comment by Progi1984** [comment]
Fixed by #20920
