### ISSUE TITLE
Many POST request to /index.php?controller=statistics that returns 499 http code?

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#20907]
Prestashop: 1.7.6.4
PHP: 7.2

I am having a trouble with diagnosing this thing since I dont know if this is a bug or misconfiguration at my side.

By using traefik I got some of the logs about requests and there is a lot of

```
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:55:14 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350380 "project-secured@docker" "http://<proxy_ip>:80" 14ms
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:57:48 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350974 "project-secured@docker" "http://<proxy_ip>:80" 0ms
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:57:50 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350976 "project-secured@docker" "http://<proxy_ip>:80" 0ms
```

I lack a required knowledge to understand where the problem is so my main question is if these requests are made by prestashop core modules?

Any clue would be helpful

**Comment by khouloudbelguith** [comment]
Hi @ProteanCode,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
