### ISSUE TITLE
Improve product combination / variants loading

### ISSUE THREAD

**Issue by jbenezech** [PrestaShop/PrestaShop#20928]
#### Is your feature request related to a problem?

Some products can easily have thousands of combinations / variants. The current implementation is not optimal for such products and performance takes a big hit.
Improvements are already in progress for the admin product page and some improvements could also be implemented for the front end.

I currently have a product with over 2000 combinations. Changing between variants in the product page takes almost 3 seconds.

#### Describe the solution you'd like

At the moment, all combinations are queried from the database and loaded into memory in order to find the one with the correct id.  
Querying directly the desired id will improve performance.

PR to follow.

**Comment by SimonGrn** [comment]
Thanks for your issue @jbenezech
What do you think @PrestaShop/prestashop-core-developers ? Is this a real problem and a viable solution ?

**Comment by Progi1984** [comment]
@SimonGrn The @jbenezech PR is a good optimization.
