### ISSUE TITLE
Same stock product but different combinations

### ISSUE THREAD

**Issue by samuel-marcos** [PrestaShop/PrestaShop#20925]
Hello!

I'm new over here, I hope you can help me :)

I have a issue with that. My client sells bags. Each bag can be customizable or not. If it is customizable, my client wants to charge an extra fee (+5€).

It's very easy with attributes and combinations to get that, but if I create the attribute 'Customize' with options: Yes / No, the bag generates 1 bag with customize option and 1 bag without customization, when she only have 1 bag.

Is it possible with code fix that? I mean, if a client buys 1 bag without customization, the stock in the bag with customization also reduces by 1.

Thanks!!

**Comment by SimonGrn** [comment]
Hello,

**You must follow the template to submit a complete bug report**. 
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
