### ISSUE TITLE
Following migration, $_GET identifier parameters are missing on "View {..} Page"

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20934]
#### Describe the bug

Legacy pages "View {..} Page" (View Customer, View Order, View Category, View Attribute ...) usually have a URL that carry the identifier information with a http GET parameter `id_...`.

Example: `admin-dev/index.php?controller=AdminAttributesGroups&viewattribute_group=&id_attribute_group=1`
➡️ the `id_attribute_group` is the identifier

When we migrate a page to Symfony, most often, the new URL does carry the identifier information inside the URL path

Example: `http://localhost:8080/admin-dev/index.php/sell/catalog/categories/3`
➡️ `3` is the identifier

This means that, if a module was hooked on this page previously, retrieving the data using `Tools::getValue('id_{...}')` it will stop working with new migrated page.

#### Expected behavior

We believe we should attempt to provide a backward compatibility mechanism to preserve modules behavior. We might not be able to preserve all GET parameter from legacy page to Symfony page, but at least the "main identifier" should be kept (order ID for "View an Order" page ; customer ID for "View a Customer" page ...).

**Comment by Progi1984** [comment]
Fixed by #21025
