### ISSUE TITLE
Dashboard Trends not working Prestashop 1.7.5.1 and 1.7.6.

### ISSUE THREAD

**Issue by dbpwebmaster** [PrestaShop/PrestaShop#20933]
Hi, I'm working with Prestashop from a year now and this is the first time that this happen to me with module dash trends.   Since this week I'm having problems to see the sales, visitors, benefits and everything from this month, specific since 09-07-2020 until today in two sites that I have allowed in the same VPS, everything is in 0 as you can see:
![image](https://user-images.githubusercontent.com/71078431/92730884-c6672780-f34a-11ea-83b5-576783a43801.png)
![image](https://user-images.githubusercontent.com/71078431/92730998-e8f94080-f34a-11ea-8dc0-cf27b7a76d41.png)

![image](https://user-images.githubusercontent.com/71078431/92731443-6fae1d80-f34b-11ea-971a-e28b63188eba.png)
![image](https://user-images.githubusercontent.com/71078431/92731728-d92e2c00-f34b-11ea-8f24-8d72beef1bf2.png)

But if I selected from this week, 09-07-2020 until today 09-10-2020 the information is working good as you can see:
![image](https://user-images.githubusercontent.com/71078431/92731826-f531cd80-f34b-11ea-819d-6e8569e58567.png)
![image](https://user-images.githubusercontent.com/71078431/92731857-037fe980-f34c-11ea-9a03-118a57ab164c.png)

![image](https://user-images.githubusercontent.com/71078431/92733290-e4825700-f34d-11ea-9b38-d71d01e3cee4.png)
![image](https://user-images.githubusercontent.com/71078431/92733854-64102600-f34e-11ea-8162-d83d9b2745e4.png)

These are two different sites with two different versions of prestashop (1.7.5.1 and 1.7.6.0) and the only in common is that there are in the same VPS.   So my question is if there a problem of the hosting and where or what can be the problem or is a problem with Prestashop and this module specifically?

I already delete the module and reinstall again in both sites, reset the module many times, update the PHP Version many times and nothing is change, it still simply not working if I select this week and one or two day from last week or the entire month.

The Server information of every page are this:

Server information for Prestashop 1.7.5.1: 

Linux #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64

Software version of the server: Apache
PHP Version: 7.1.33
Memory limit: 128M
Max execution time: 3000
Max size for upload files: 128M

Database information:

MySQL Versión: 5.7.31
MySQL Server: 127.0.0.1

Server information for Prestashop 1.7.6.0: 

Linux #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64

Software version of the server: Apache
PHP Version: 7.2.33
Memory limit: 128M
Max execution time: 3000
Max size for upload files: 128M

Database information:

MySQL Versión: 5.7.31
MySQL Server: 127.0.0.1

Kind Regards.

**Comment by florine2623** [comment]
Hi @dbpwebmaster ,

I can't reproduce the issue on my test shops 1.7.5.1 and 1.7.6.5.
Could you check if you have data in the tab Statistics itself ?

Thanks

**Comment by dbpwebmaster** [comment]
I attach screenshots of the stadistics tab of both sites.   Its working fine without problems.

![image](https://user-images.githubusercontent.com/71078431/92752727-8fe7d780-f35f-11ea-9ccd-47a979c8e1f8.png)
![image](https://user-images.githubusercontent.com/71078431/92752751-95ddb880-f35f-11ea-945d-16f25be50cd7.png)
![image](https://user-images.githubusercontent.com/71078431/92752771-9bd39980-f35f-11ea-9f14-7036143ddd30.png)

![image](https://user-images.githubusercontent.com/71078431/92752791-a2621100-f35f-11ea-92d9-4d66c72df965.png)
![image](https://user-images.githubusercontent.com/71078431/92752813-a857f200-f35f-11ea-8e8a-43c52c27d4cd.png)
I couldn't see the sales stadistics for this page in PS 1.7.6.0

Kind Regards.

**Comment by khouloudbelguith** [comment]
Hi @dbpwebmaster,

Since 09-07-2020, have you any invoice generated?
If no, this is normal behavior.
About the `dashtrends` module (Dashboard widget), it is necessary to regenerate invoices so the statistics will be displayed, if you don't regenerate an invoice for an order, it will not be taken in consideration for the statistics.
For more details, you can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/15319
Thanks to check and feedback.

**Comment by dbpwebmaster** [comment]
Yes, I have invoices since 09-07-2020, the only day that I don't have invoices is in fact the 09-07-2020 but since the next day I have invoices, as you can see here the sales with their invoices from 09-08-2020:
![image](https://user-images.githubusercontent.com/71078431/92926794-f5e16700-f412-11ea-8071-22eb110f3e72.png)

And it is reflecting in dash trends ONLY if I filters from the 09-07-2020 to 09-11-2020 as you can see:
![image](https://user-images.githubusercontent.com/71078431/92927427-f75f5f00-f413-11ea-87d9-0ed1ea760d01.png)
![image](https://user-images.githubusercontent.com/71078431/92927388-e9a9d980-f413-11ea-92a4-948ba196e74e.png)
![image](https://user-images.githubusercontent.com/71078431/92927531-24137680-f414-11ea-9599-839e5e451179.png)



The problem is that if I filter selecting days from the past week to days of this week in the dashboard in general its not showing any data from this week.  Its not just sales, the visitors are not reflecting either, the benefit are not reflecting either, any information from this week.
![image](https://user-images.githubusercontent.com/71078431/92927243-b2d3c380-f413-11ea-9f40-cc4612d5fe98.png)
![image](https://user-images.githubusercontent.com/71078431/92927289-c2530c80-f413-11ea-887c-b549c78aba40.png)
![image](https://user-images.githubusercontent.com/71078431/92927332-d4cd4600-f413-11ea-9530-af6a6776719c.png)

And as I say in the beginning its not just happen with this website, its happen with all the sites with Prestashop that I have in my VPS.

**Comment by khouloudbelguith** [comment]
@dbpwebmaster, I did not manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/93102008-48d54b80-f6ab-11ea-91a4-43219cf1c67d.png)

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log


Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by dbpwebmaster** [comment]
I have the apache error logs provided by our hosting support (We don't have directly access or full administration from our server), that's all I have from them.  

Apache logs: [https://drive.google.com/file/d/1r0u4JqGVmQOkrc2uzZk_dNuLZWm5tRIt/view?usp=sharing](url)

Debug Report from Prestashop:
![image](https://user-images.githubusercontent.com/71078431/93214771-f42de100-f73b-11ea-8d26-200f0030b0c0.png)
![image](https://user-images.githubusercontent.com/71078431/93214790-fd1eb280-f73b-11ea-882a-5184123c6347.png)
![image](https://user-images.githubusercontent.com/71078431/93214811-03149380-f73c-11ea-9fee-c1279223391b.png)

Console log:

Frontend
![image](https://user-images.githubusercontent.com/71078431/93215301-98b02300-f73c-11ea-986e-5956b9953403.png)


Backend:
![image](https://user-images.githubusercontent.com/71078431/93215475-d90fa100-f73c-11ea-82a1-c4de4aee7675.png)


Kind Regards,
Daniela Moreno

**Comment by khouloudbelguith** [comment]
@dbpwebmaster, I need permissions to see your log file.
The request is sent.
Thanks!

**Comment by dbpwebmaster** [comment]
Permissions granted. 

Kind Regards,

**Comment by khouloudbelguith** [comment]
@dbpwebmaster, I find those errors
```
 ModSecurity: Access denied with code 403 (phase 2). Pattern match "*****" at REQUEST_HEADERS:********
client denied by server configuration: /home/****/public_html/index.php
```
Could you please check with your host and feedback.

**Comment by dbpwebmaster** [comment]
They just gave me this answer:
![image](https://user-images.githubusercontent.com/71078431/93252498-fa3bb600-f76b-11ea-990b-804aab38732b.png)


This mod_security may be affecting the dash trend module for all the domains with prestashop?

Kind Regards.

**Comment by dbpwebmaster** [comment]
Hi, I have a question?

The phpinfo() disabled may be a problem for the functionality of the module?

I also add the dev.log: https://drive.google.com/file/d/1rx9plOTpR85zgg8WQkuzfgWtpqUb_4-R/view?usp=sharing
And the prod.log: https://drive.google.com/file/d/1s1PY8NDMXBiRODscr3nRtCQfPR7pSpm0/view?usp=sharing

Kind Regards,
Daniela Moreno.

**Comment by florine2623** [comment]
Hi @dbpwebmaster ,
In the conversation with your host, it seems like they are talking about a WordPress file. You might have some WP files in your PrestaShop directory. Can you check your PS files to see if there are no extra files that are not necessary to PrestaShop itself.
Thanks!

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
