### ISSUE TITLE
Query Builder help with JOINs

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#20930]
Can you tell me if it is possible to nest queries in a SQL JOIN in the Query Builder?

I want to achieve this in SQL:

```
select o.id_order, r.code
from ps_orders o
left outer join (
	select ocr.id_order, cr.code
	from ps_order_cart_rule as ocr
	inner join ps_cart_rule as cr
	on ocr.id_cart_rule = cr.id_cart_rule
	) r
on o.id_order = r.id_order
```

So the LEFT OUTER JOIN needs to be on the result of the nested query (not on a table that exists already which IS supported by the Query Builder).

Is it possible?

Thanks!

I have posted already on the #general Slack channel but no response.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by jonpontet** [comment]
@SimonGrn thats great Simon so please remove the option ⛔ I need help
For questions about using PrestaShop !

**Comment by SimonGrn** [comment]
@jonpontet I suggest you read what's inside the template for this option.
