### ISSUE TITLE
Customized products - bug in quantity check

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#20948]
#### Describe the bug

Customized products can be sold even if there is no sufficient stock

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to https://demo.prestashop.com/#/en/front
2. Open product "Customizable mug"
3. Add product customization "Test1"
4. Increase qty to 300 (thats the overall available qty)
5. Add to cart
6. Click "continue shopping"
7. Add product customization "Test2"
8. Increase qty to 300
9. Add to cart
10. We have now 600 in cart where the total available qty is only 300 due to different customizations

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![grafik](https://user-images.githubusercontent.com/47666330/92872379-3e465800-f406-11ea-8066-e5272934c207.png)

#### Additional information

* PrestaShop version: 1.7.6.7 + 1.7.7BETA2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @jbwModules,

I managed to reproduce the bug in PS 1.6.7.6 and PS 1.7.7. beta 2. 
This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9974, so I will close it.
You can follow the updates on that issue directly.
Thanks!

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9974

**Comment by JBWModules** [comment]
Crazy, this is over 2 years old... Seems not many shops really working with customized products
