### ISSUE TITLE
New hook to be executed once a module has been upgraded

### ISSUE THREAD

**Issue by xiropot** [PrestaShop/PrestaShop#20944]
#### Is your feature request related to a problem?

I need to execute a module once another one (not some specific, just anyone else) gets updated.

#### Describe the solution you'd like

A new hook located in the right place.

**Comment by florine2623** [comment]
Hi @tapandagr ,

Please be more specific about the improvement you want to see by giving examples. If possible, you can add screenshots as well.
For now I close your ticket, feel free to open a new one, when all details are present.

Thanks!
