### ISSUE TITLE
issue in login error code :2s100/6

### ISSUE THREAD

**Issue by PicPaints** [PrestaShop/PrestaShop#20945]
#### Describe the bug

When i come to login in prestashop its give me ( The page you requested does not exist

Error code: 2S100/6 ) when imake reset password it said this email not registered and am sure that i have account because i have admin and password..

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**
![image](https://user-images.githubusercontent.com/71100967/92808548-847ac780-f3c4-11ea-8f9f-b1841e38ed36.png)
![image](https://user-images.githubusercontent.com/71100967/92808665-9ceae200-f3c4-11ea-98f3-42d7bc1e9edb.png)

#### Additional information

* PrestaShop version: 1.6.1.24
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @PicPaints ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by PicPaints** [comment]
Hello,

In this case, do you advise me to upgrade to the latest version of PrestaShop, after that it will work fine with me?

**Comment by PicPaints** [comment]
> 
> 
> Hello,
> 
> In this case, do you advise me to upgrade to the latest version of PrestaShop, after that it will work fine with me?

**Comment by Gacatokill** [comment]
Bonjour, toujours a la recherche de la solution ?Cordialement
