### ISSUE TITLE
FO - When we have two currencies enabled - the Currency block and the language block are not working anymore

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20950]
#### Describe the bug

I the FO, when we have more than two currencies enabled,  the Currency block and language block are not working anymore.

#### Steps to Reproduce

1. Go to BO > International > Localization > Create a new currency (you have more than two currencies and  two languages)
2. Go to FO
3. Try to change the language or the currency

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/92894861-3fce4b00-f41b-11ea-9c3f-d5e9ddebbaf1.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @matthieu-rolland this issue is related to this PR: https://github.com/PrestaShop/PrestaShop/pull/20920

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/qa-automation

**Comment by matthieu-rolland** [comment]
I'll have a look 🤔  Thanx @khouloudbelguith for the report 👍

**Comment by Progi1984** [comment]
Fixed by #20992
