### ISSUE TITLE
Prestashop is no longer present on Gitter?

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#20956]
Hi
today I try to go in Gitter to speak with someone about of prestashop, but I cannot find any channel

is there some solution like Gitter used by Prestashop?

thanks

**Comment by matks** [comment]
Yes indeed, we migrated to Slack 😉 https://github.com/PrestaShop/open-source/tree/master/slack

We provided warnings for a few months before the switch but if you were not active for a few months you might have missed it.

See you in Slack soon ✋ !
