### ISSUE TITLE
BO - Carriers page - Enable/Disale with bulk action is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20958]
#### Describe the bug

In the BO > Carriers page, Enable/Disable with bulk action => NOK

#### Steps to Reproduce

1. Go to BO > Carriers page
2. Try to Enable/Disable with bulk action

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/92935603-48d61100-f449-11ea-8ef5-4a1b6cd5fa9a.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #20960
