### ISSUE TITLE
Fix dirty fix implemented in #20953 for Behat and php7.2

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20954]
In PR https://github.com/PrestaShop/PrestaShop/pull/20939 we had to modify some Behat statements in order for CI to pass.

Without them, we had a very exotic error only for php7.2.

Because we needed to merge https://github.com/PrestaShop/PrestaShop/pull/20939 (it was a merge of 1.7.7.x into develop) we had to validate it, however as mentioned by @PierreRambaud this was a dirty fix. We need to explore deeper the root cause of the issue to provide a good fix.

This PR https://github.com/PrestaShop/PrestaShop/pull/20953 is expected to fail when run by Travis, and we need to find what must be adapted to make it pass.

**Comment by LouiseBonnard** [comment]
Root cause must be investigated.

**Comment by matks** [comment]
@PierreRambaud @jolelievre It seems someone managed to fix the Behat tests https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Scenario/Order/order_specific_prices.feature as they are back to initial version (before PR https://github.com/PrestaShop/PrestaShop/pull/20939 with nasty fix)

We can close this issue.
