### ISSUE TITLE
Prestashop 1.7.6.4 backend access issue

### ISSUE THREAD

**Issue by start10designs** [PrestaShop/PrestaShop#20957]
we are unable to access the backend of the Prestashop website.

Error Log

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 60 seconds exceeded" at /var/www/html/classes/controller/AdminController.php line 2028 {"exception":"[object] (Symfony\Component\Debug\Exception\FatalErrorException(code: 0): Error: Maximum execution time of 60 seconds exceeded at /var/www/html/classes/controller/AdminController.php:2028)"} []

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 60 seconds exceeded" at /var/www/html/src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php line 68 {"exception":"[object] (Symfony\Component\Debug\Exception\FatalErrorException(code: 0): Error: Maximum execution time of 60 seconds exceeded at /var/www/html/src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php:68)"} []

Anyone can please help

**Comment by florine2623** [comment]
Hi @start10designs ,
Please follow the template of issue in order to get an answer. We need more information about PS version, steps to reproduce, screenshots etc.

If not, you can contact the support team here : https://addons.prestashop.com/en/388-support

Thanks!

**Comment by matks** [comment]
@start10designs increase the max_execution_time in your php.ini file.

See https://stackoverflow.com/questions/1420249/maximum-execution-time-of-60-seconds-exceeded-error

**Comment by start10designs** [comment]
> @start10designs increase the max_execution_time in your php.ini file.
> 
> See https://stackoverflow.com/questions/1420249/maximum-execution-time-of-60-seconds-exceeded-error

@matks 
already tried that way but it's not working as I see the admin login page of the Prestashop the title is a little different
Look at this
https://prnt.sc/uhkmg2

**Comment by arirangz** [comment]
Hello !
I have exaclty the same problem with the admin tab renamed with a module name (in my case Paypal). This happen just after I disabled the module.
Now, every time I try to connect to my admin, I have a max execution time on the same line as in this issue.

Before that, I didn't have this issue.

@start10designs could you solve your issue?
Thans!

**Comment by arirangz** [comment]
Ok I figured out that the primary keys were not properly added on table. If it could help someone, check if you have all the auto increment on all tables.
