### ISSUE TITLE
[FO][CSS] [Adresses] different sizes of address block 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20952]
#### Describe the bug

Orders>Shopping carts, filtering on customer & date doesnt work.

#### Expected behavior

Comparing to 177x, the adresse blocks now have different sizes

#### Steps to Reproduce

1. Make first order
2. Reorder from the order history and details page
3. add a new adress
4. See the different sizes of address block 

**Screenshots**
Version 178 vs 177:
<img width="1362" alt="Capture d’écran 2020-09-11 à 11 09 49" src="https://user-images.githubusercontent.com/69145330/92899681-5080c000-f41f-11ea-813b-0cd3967db6b6.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I have the same issue with PS1.7.6.7,size window 990*1008px
![image](https://user-images.githubusercontent.com/16067358/92924232-e8d76e80-f438-11ea-86c1-de9f0b9b097c.png)
![image](https://user-images.githubusercontent.com/16067358/92924347-158b8600-f439-11ea-907a-ed6bf8a26775.png)

It is not a regression

Thanks!

**Comment by marionf** [comment]
@PrestaShop/ux-team wdyt ?

**Comment by prestascott** [comment]
Hi everyone!

Thank you for your report @ngodefroy. 

Address block size depends on its content, the more content the longer the block will be. In fact, it is a weird display and this can be seen as a bug from users' point of view. 

I suggest defining a standard height so no matter how long is the content, block will remain the same size.

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/21401
