### ISSUE TITLE
Prestashop beta 2

### ISSUE THREAD

**Issue by escaware** [PrestaShop/PrestaShop#20966]
Hello
Since I installed prestashop 1.7.7.0 beta 2 I cannot enter backoffice, in beta 1 if I could, I also installed it clean.

**Comment by SimonGrn** [comment]
Dear @escaware 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by matks** [comment]
@escaware Thanks for testing the beta 😉
