### ISSUE TITLE
SubmitRowAction Error

### ISSUE THREAD

**Issue by dagusia** [PrestaShop/PrestaShop#20968]
_"Oops... looks like an unexpected error occurred
Attempted to load class "SubmitRowAction" from namespace "PrestaShop\PrestaShop\Core\Grid\Action\Row\Type". Did you forget a "use" statement for another namespace? [Symfony\Component\Debug\Exception\ClassNotFoundException 0]"_

This is the message I get when I try to open
- Preferences -> Contact
- Catalog -> Brands and Suppliers

![image](https://user-images.githubusercontent.com/47856866/93020797-91bfce00-f5df-11ea-8138-ee78a7ef3ebf.png)
![image](https://user-images.githubusercontent.com/47856866/93020818-b3b95080-f5df-11ea-8675-aeced8acb412.png)

#### Additional information

* PrestaShop version: 1.7.7.0beta2
* PHP version: 7.4.8

**Comment by matks** [comment]
Weird, the right class is there 🤔 https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Action/Row/Type/SubmitRowAction.php

I notice you are running php7.4 .

PS 1.7.7 is not compatible with php7.4, only php7.3 . Could you retry with php7.3 ?

**Comment by dagusia** [comment]
Changing version didn't help

**Comment by khouloudbelguith** [comment]
Hi @dagusia,

Are you using the 1770beta2 downloaded from [PrestaShop official](https://www.prestashop.com/en/previous-versions)?
Thanks to navigate to your BO > Advanced Parameters > Information page and provide us a screenshot.

Thanks!

**Comment by dagusia** [comment]
This is 1770beta2. Sory I forgot to add that it is beta2.

![image](https://user-images.githubusercontent.com/47856866/93071714-c33ca600-f680-11ea-9645-b28169a002ab.png)

**Comment by khouloudbelguith** [comment]
@dagusia, thanks for your feedback.
I did not manage to reproduce the issue with PS1770beta2. using PHP v7.3.
I attached a screen record
https://drive.google.com/file/d/1dzxs-ypcKUTOpzHKiZ3DsmDAGK9gp9or/view?usp=sharing
Thanks to check and feedback.
