### ISSUE TITLE
Page Crawling issue on Multishop

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#20974]
#### Describe the bug

We have a website setup in multishop.

There are 11 shops and 6 languages.

Few shops are english only while like NL/FR/DE/AT have multiple languages. eg. FR has french and english, AT has German, French and english.

Our GOOGLE Merchant crawling get failed everyday for few products. 

I am attaching a screenshot of merchant senter crawling list. Randomly we getting site in other language also, eg.On english language its start displaying half content in german and half in english. Same time if somebody else open website page then it display correctly to that visitor. Sometimes it doesnot change content when we change language on site also.

On our dutch shop its giving CURRENCY as pound while there is only one currency enabled which is EURO. 

I think this is the issue in CLDR.

#### Expected behavior

It need give proper info based on shop and language selection not to give random content mixed language

#### Steps to Reproduce

Its so random in nature and almost impossible to get it exactly when we want.

**Screenshots**

![Screenshot 2020-09-14 162516](https://user-images.githubusercontent.com/437314/93077756-e8dca600-f6a6-11ea-9ff1-ac26324e4515.jpg)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @beniwal,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 
You deleted everything of the GitHub's template when creating the issue For example, we don't know your PS version, your PHP version, steps to reproduce the issue.

Thanks to edit your description.

**Comment by simulbeni** [comment]
Sorry, I updated my description. 

I am working with prestashop from 10 years and this is first of its kind where i have no clue about.

**Comment by khouloudbelguith** [comment]
@beniwal, are you using this [link](https://www.google.com/webmasters/tools/settings) to get information about Google Merchant crawling?
I'm trying to reproduce your issue.

Thanks!

**Comment by simulbeni** [comment]
@khouloudbelguith  We can add you as google merchant user if you want to check details. I can add as admin user on acceptance environment.

**Comment by kpodemski** [comment]
@beniwal why you don't use any module for google merchant but choose to crawler do the job? :)

**Comment by simulbeni** [comment]
@kpodemski We using channable to submit feed to google merchant. Data submitted to google is correct but when google check our website it gives wrong data like different currency and content in diff language.

**Comment by khouloudbelguith** [comment]
>We can add you as google merchant user if you want to check details. I can add as admin user on acceptance environment.

@beniwal, we need to reproduce the issue in our environment first.
The link provided is incorrect?
How can I get information and check it in my case?

Thanks!

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
