### ISSUE TITLE
remove/hide flag percent discount  on product page

### ISSUE THREAD

**Issue by Lajaca** [PrestaShop/PrestaShop#20976]
I would like remove/hide flag percent discount on product page 

I have triyed change on product.tpl code any body could help me

![Captura3](https://user-images.githubusercontent.com/71235516/93087403-c5126380-f698-11ea-9b0d-8dfe83b93a87.JPG)

Prestashop 1.7.6.5
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Lajaca,

Thanks for your issue.
On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
