### ISSUE TITLE
Product Page Size Combinations no displayed

### ISSUE THREAD

**Issue by Lajaca** [PrestaShop/PrestaShop#20970]
The size combinations are not displayed on product page and I cant select size

![Captura](https://user-images.githubusercontent.com/71235516/93030148-272f8200-f621-11ea-9b0d-08865a807922.JPG)

* PrestaShop version: prestashop:1.7.6.5
* PHP version: 7.3.22

**Comment by khouloudbelguith** [comment]
Hi @Lajaca,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.
Thanks to check and feedback.
In the next time, you must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Thank you

**Comment by Lajaca** [comment]
Thanks for your help!!!

**Comment by khouloudbelguith** [comment]
@Lajaca, thanks!
Waiting for your feedback.

**Comment by sarahdib** [comment]
Hello,

As the problem since to be the PHP version I close this issue. If the problem appear again feel free to open a new issue with more detail.

Thank you!
