### ISSUE TITLE
disappeared the sidebar of the administration menu in the back office

### ISSUE THREAD

**Issue by Clis87** [PrestaShop/PrestaShop#20979]
disappeared the sidebar of the administration menu in the back office
![screen](https://user-images.githubusercontent.com/71274665/93100935-ffd0c780-f6a9-11ea-8ddc-9c2940d58014.jpg)
how can I restore the menu?

**Comment by khouloudbelguith** [comment]
Hi @Clis87,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

I close the issue, feel free to create a new one when needed.

Thanks!
