### ISSUE TITLE
Contact form is not showed.

### ISSUE THREAD

**Issue by cabq2020** [PrestaShop/PrestaShop#20971]
Hi:
I am using Prestashop 1.7.6.7 and a paid Theme called Mega Electronics Store.
The issue is related to the contact form. I have everything configured, but the contact form is not shown in the browser. The debug error is as follows:

(1/1) SmartyExceptionUnable to load template 'file:layouts/layout-full-column.tpl' in 'page.tpl'
--
in smarty_internal_template.php line 195
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-column.tpl', null, 'layouts/layout-full-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-column.tpl')in 88555beb38b7fec7cf4389942194c85874398685_2.file.page.tpl.php line 33
at content_5f5eb1dc474c44_63191396(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-column.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 125
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in 6afc5109449ced3570e71bebdd4c61c914f45776_2.file.contact.tpl.php line 37
at content_5f5eb1dc46b782_99530777(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-column.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('contact.tpl', null, 'layouts/layout-full-column.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('contact.tpl', null, 'layouts/layout-full-column.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('contact.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

Any help please?

Thanks!

**Comment by SimonGrn** [comment]
Hello @cabq2020,

sadly your problem is related to your theme. We cannot offer support for third-party themes and modules, so I suggest you contact the theme developer directly.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I close this issue, thank you for your understanding.
