### ISSUE TITLE
Product price displayed as 0 in category page

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#20975]
#### Describe the bug

The product price is displayed incorrectly on the category page
The original price is **not 0** but the displayed price is 0

#### Expected behavior

The product price should be displayed correctly

#### Steps to Reproduce
>Edit by Khouloud
Steps to reproduce the issue:
1. Enable multishop context
2. create a new store
3. Create a standard product in all shops
4. select shop1, edit the last product created => generate combinations, 
5. change the combination by default
6. Go to FO > Category page
7. see error

https://drive.google.com/file/d/11FmNrvoC4VHVErmTlyWJlW7SjHqvKbum/view?usp=sharing

1. Enable multishop
2. Add a second shop
3. Switch to second shop
4. Having a product with attributes, delete all its attributes (or make it a "Simple product")
5. Open the product category page, the price will be displayed as 0

**Screenshots**

Expected
![localhost_tests_ps_multishop_attribute_en_3-clothes](https://user-images.githubusercontent.com/793712/93079395-f7fe2c80-f683-11ea-8d2a-ab1bc11aa536.png)

Actual
![localhost_tests_ps_multishop_attribute_second_en_3-clothes](https://user-images.githubusercontent.com/793712/93079416-fd5b7700-f683-11ea-9f7c-57ac5af7e200.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @unlocomqx,

Thanks for your report.
When I try this step `Having a product with attributes, delete all its attributes`, I have an exception in the console.
It is similar to this [ticket](https://github.com/PrestaShop/PrestaShop/issues/9664#issuecomment-471480370)
I tried with a standard product but I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1rUmOWMwB6oiPTaSt2yJMND8Sepe2PRd9/view?usp=sharing
Thanks to check and feedback.

**Comment by unlocomqx** [comment]
Thank you for looking into this.
Please try making the product a simple product then save (instead of manually deleting the attributes)
I will try to reproduce https://github.com/PrestaShop/PrestaShop/issues/9664#issuecomment-471480370

**Comment by khouloudbelguith** [comment]
@unlocomqx,
>Please try making the product a simple product then save (instead of manually deleting the attributes)

Yes, I tried with simple product & it is ok as recorded here:
https://drive.google.com/file/d/1rUmOWMwB6oiPTaSt2yJMND8Sepe2PRd9/view?usp=sharing

Thanks to check it.

**Comment by unlocomqx** [comment]
I checked the standard product, it works well. But it's not related to this bug at all.
This bug is only related to products having attributes on one shop and no attributes on another.
On the shop where they don't have attributes, the price is wrong in the category page.

**Comment by khouloudbelguith** [comment]
@unlocomqx,

I create a product with attributes on one shop and no attributes on another.
It is ok in my case with PS1.7.6.7.
I attached a new screen record
https://drive.google.com/file/d/1MZPV91l79oQipe1OPrzG3CKr4WSWdwDp/view?usp=sharing

Thanks to check it.

**Comment by unlocomqx** [comment]
Change the default attribute on the first shop and then view the category on the second shop, you will see the issue
I was able to reproduce it again
![image](https://user-images.githubusercontent.com/793712/93084995-d0f82880-f68c-11ea-97c7-246afb2c27c0.png)

**Comment by khouloudbelguith** [comment]
@unlocomqx, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.7 and PS1.7.7.0beta2.
Steps to reproduce the issue:
1. Enable multishop context
2. create a new store
3. Create a standard product in all shops
4. select shop1, edit the last product created => generate combinations, 
5. change the combination by default
6. Go to FO > Category page
7. see error
https://drive.google.com/file/d/11FmNrvoC4VHVErmTlyWJlW7SjHqvKbum/view?usp=sharing
I’ll add this to the debug roadmap.

Thanks!

**Comment by unlocomqx** [comment]
Thank you for your effort to reproduce it.
I made a PR which fixes this issue. https://github.com/PrestaShop/PrestaShop/pull/20964
