### ISSUE TITLE
Not all required files and folders are in proper way included in VCS

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#20985]
#### Describe the bug

Try to create own repository from origin repository.

#### Expected behavior

I can create own repository without headache.
All necessary files and folders are in proper way included in VCS.

#### Steps to Reproduce

```shell-script
$ cd /var/www/ && mkdir presta/ && cd presta/
$ git clone https://github.com/PrestaShop/PrestaShop.git .
$ git fetch && git checkout 1.7.7.x
$ rm -rf .git/
$ git init && git add . && git commit -m 'initial commit'
$ git remote add origin <your-remote-url>
$ git push -u origin master
// then
$ cd /var/www && mkdir presta2/ && cd presta2/
$ git clone <your-remote-url> .
$ composer install
$ mkdir app/logs // also please add .gitignore file in that folder - to keep in empty VCS
$ chmod +w -R admin-dev/autoupgrade app/config app/logs app/Resources/translations cache config download img log mails modules themes translations upload var
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42643563/93136762-c2d1f880-f6dc-11ea-930c-a229c3d934ab.png)

#### Additional information

* PrestaShop version: 1.7.6.x, 1.7.7.x
* PHP version: 7.3.22-FPM

**Comment by PierreRambaud** [comment]
Seems to be a permissions problem, are you sure your apache user has the right to create directories? 
Because these directories are automatically generated.

**Comment by matks** [comment]
Hi @LocalHeroPro it seems you are missing the override/classes folder. I think it's because it was put inside the github repository using `git add --force` although it's ignored in the `.gitignore`

However I dont think this is an issue. The `.gitignore` aims to be a file used for developers building prestashop (bugfix and feature), not for developers using it to setup a shop with customizations. If we did it, it should be a different .gitignore . It's somehow related to https://github.com/PrestaShop/PrestaShop/issues/14086

**Comment by PierreRambaud** [comment]
Ohh you're right @matks, forget they did this -_-
Unfortunately, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by LocalHeroPro** [comment]
@matks
> it seems you are missing the override/classes folder.

no. I have that folder and changes equal with source branch (1.7.6.x):
![image](https://user-images.githubusercontent.com/42643563/93238986-750fcb80-f782-11ea-874e-45df900d1966.png)

**Comment by LocalHeroPro** [comment]
Bump.
