### ISSUE TITLE
Translations overwritten by the upgrade process (1.7.7.0 beta 2)

### ISSUE THREAD

**Issue by daghb** [PrestaShop/PrestaShop#20982]
#### Describe the bug

After upgrading the shop to beta 2 of the 1.7.7.0 branch using Docker containers, I have managed to upgrade everything, except for translations that are in the database. I ran the install/upgrade/upgrade.php script with no errors. However, it seems that no translations are available in the database, only the English versions.

Page translations are OK. Product, classification/categories etc. are only available in English.

#### Expected behavior

All my products, menus and categories were available in two language versions in 1.7.6.x. I am using Norwegian as the default language and English as the only secondary language. After upgrading, I expect those two versions to be available in the database.

Whet is strange, is that after I re-translate a product in Norwegian, the changes are saved and available right away. To me, it seems that the upgrade process has overwritten the Norwegian translations, keeping the English in both versions and that there is nothing wrong with the new version at all except from the upgrade logic.

#### Steps to Reproduce

1. Create a shop in 1.7.6.x
2. Add at least two languages - English + 1 more
3. Add a product with text in both languages
4. Upgrade the database and Prestashop

#### Additional information

* PrestaShop version: 1.7.7.0 beta 2 official Docker image
* PHP version: Included in official docker image

**Comment by khouloudbelguith** [comment]
Hi @daghb,

Thanks for your report.
For the manual upgrade, I followed this link: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/ but I have this error
![image](https://user-images.githubusercontent.com/16067358/93188733-a3b98200-f741-11ea-81e2-abd1c61ccef4.png)
I tried the local archive upgrade using the 1-click upgrade v4.10.1
![image](https://user-images.githubusercontent.com/16067358/93188810-bcc23300-f741-11ea-8a11-df533a2adf27.png)
The upgrade is ok and the translations are ok
I attached a screen record
https://drive.google.com/file/d/1GHQ2axC2kvlFlbzqvIFj5Qd7g3BZWEkH/view?usp=sharing
PS: 177beta is not a stable version, it is still in progress.
You can follow this link: https://github.com/PrestaShop/PrestaShop/issues/18647
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @daghb,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
