### ISSUE TITLE
Product property hooks not available in cart (CartPresenter)

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#20989]
PR: #20980 

#### Describe the bug

The CartPresenter currently does not use the product assembler for Smart. This makes the available hooks for product properties not available in the cart.

#### Expected behavior

That the cart uses the same display/assemble logic as any other location in Prestashop.

#### Steps to Reproduce
>Edit by Khouloud
Steps to reproduce the issue
1. Create a custom module using this `actionGetProductPropertiesAfter` hook
```php
    public function hookactionGetProductPropertiesAfter( $params )
    {
        $params['product']['test20989'] = 'Test property issue 20989';
    }
```
2. Edit a theme's cart template: `templates/checkout/_partials/cart-detailed-product-line.tpl`.
Add `{$product.test20989}` anywhere

3. Go to FO > Add product to cart > go checkout page
4. see error
-------------------------------------------

1. Add custom product properties using the `actionGetProductPropertiesAfter` hook.
2. They are currently not available in the cart templates.

#### Additional information

* PrestaShop version: develop / 1.7.7.x (tested locally on 1.7.6.x as well)
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @JoryHogeveen,

I used this [module](https://github.com/PrestaShop/ps_qualityassurance) to display `$params`
![image](https://user-images.githubusercontent.com/16067358/93195033-0d895a00-f749-11ea-9924-449ab1774e11.png)
I have this result
![image](https://user-images.githubusercontent.com/16067358/93195060-1712c200-f749-11ea-8b65-b9635cbab250.png)

How can I add custom product properties using this hook?

Thanks!

**Comment by JoryHogeveen** [comment]
Hi @khouloudbelguith 

You can just add properties to the `product` item in the `$params`. These properties will then be available in Smarty.
Make sure you are adding it to the `$params` variable since it's passed by reference.

Cheers, Jory

**Comment by khouloudbelguith** [comment]
@JoryHogeveen, could you please provide us a demo module to reproduce the issue.
Thanks!

**Comment by JoryHogeveen** [comment]
Hi @khouloudbelguith 
Did the above instructions not work?

Example hook function:

```php
    public function hookactionGetProductPropertiesAfter( $params )
    {
        $params['product']['test20989'] = 'Test property issue 20989';
    }
```

Next, go to your theme's cart template: `templates/checkout/_partials/cart-detailed-product-line.tpl`.
Add `{$product.test20989}` anywhere you want and with the PR applied it will output `Test property issue 20989`. Without the PR it will probably result in an error.

**Comment by khouloudbelguith** [comment]
@JoryHogeveen, I have this exception following these steps
![image](https://user-images.githubusercontent.com/16067358/93203776-416a7c80-f755-11ea-9ac4-87d03717faac.png)

Thanks!

**Comment by JoryHogeveen** [comment]
Hi @khouloudbelguith 
Correct, that is the error when the patch isn't applied.

**Comment by khouloudbelguith** [comment]
@JoryHogeveen,

Thanks a lot for your feedback.
I manage to reproduce the issue with PS1.7.6.7 and PS1770beta2.
Steps to reproduce the issue
1. Create a custom module using this `actionGetProductPropertiesAfter` hook
```php
    public function hookactionGetProductPropertiesAfter( $params )
    {
        $params['product']['test20989'] = 'Test property issue 20989';
    }
```
2. Edit a theme's cart template: `templates/checkout/_partials/cart-detailed-product-line.tpl`.
Add `{$product.test20989}` anywhere

3. Go to FO > Add product to cart > go checkout page
4. see error

I’ll add this to the debug roadmap.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20980
