### ISSUE TITLE
progressive voucher discount bug passed to Payment gateway

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#20981]
#### Describe the bug

When a customer purcase items tha thave a % discount (for example 30%) the total is wrong.

Example list of product + accessoriesd (discounted)
![image](https://user-images.githubusercontent.com/16102074/93109810-ca7da700-f6b4-11ea-942b-6a18357051c7.png)

list of discount received for each accessories:
![image](https://user-images.githubusercontent.com/16102074/93109893-e6814880-f6b4-11ea-8f3f-85b8cd893dc0.png)

total order is wrong
![image](https://user-images.githubusercontent.com/16102074/93109925-f00ab080-f6b4-11ea-826e-fe211f36a528.png)

When customer use for example PAYPAL to pay the order, will receive this list of products (tax 22% free)

![image](https://user-images.githubusercontent.com/16102074/93110025-103a6f80-f6b5-11ea-8f3f-cf0829fb17a1.png)

And a wrong list of discounts!
![image](https://user-images.githubusercontent.com/16102074/93110083-221c1280-f6b5-11ea-8a53-74365a01a059.png)

Only the first discount is right the other are progresively lower (why?)

the total order calculated is also wrong must be 145.91€:
![image](https://user-images.githubusercontent.com/16102074/93110213-4f68c080-f6b5-11ea-847b-7671b657dea2.png)

#### Expected behavior

voucher calculated for a single product -30% each must be costant not progressive and the toal must be

![image](https://user-images.githubusercontent.com/16102074/93111209-97d4ae00-f6b6-11ea-9572-552000c4b450.png)

#### Steps to Reproduce

1. create 7 accessories same price 19€ (TAX 22% included)
2. Create 30% discount for each of them
3. Create a main product 39,08€ ttax 22% included
4. Add all 8 products to the cart

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,

I did not manage to reproduce the issue with PS1767.
FO
![image](https://user-images.githubusercontent.com/16067358/93191835-46273480-f745-11ea-92db-920a3914db59.png)

BO
![image](https://user-images.githubusercontent.com/16067358/93191775-34de2800-f745-11ea-8d4f-b47e74833bfb.png)

Also, we have the rounding issue as commented here: https://github.com/PrestaShop/PrestaShop/issues/20889#issuecomment-688714328
Thanks to check and feedback.

**Comment by HartLarsson** [comment]
on PS seems all working but the total is wrong.
(If the customer is Outside italy without taxation)
Plus when data is passed to Paypal all discounts become different.

the strange fact is when i try to simulate to send the same order to a USA adress the calculation is k, but when ad American Customer make the same order the total is different and wrong.
Is like Prestashop identify the customer that is outside italy and make some strange calculation.

**Comment by khouloudbelguith** [comment]
@HartLarsson,

When France is selected (Tax applied)
I have this
![image](https://user-images.githubusercontent.com/16067358/93205899-d91d9a00-f758-11ea-8c11-0c60f34a85f8.png)
When I have another outside country (tax not applied)
I have this
![image](https://user-images.githubusercontent.com/16067358/93205946-ec306a00-f758-11ea-936b-338cf49d268a.png)

>Plus when data is passed to Paypal all discounts become different.

Have you tried to contact the module author?

Thanks!

**Comment by HartLarsson** [comment]
i've opened a ticket too with Paypal official module developer here: https://github.com/202-ecommerce/paypal/issues/60

The strange thing is why Prestashop make error calculation if a USA customer try to purchase from Italian Store while if i try to simulate to send the item in USA the calculation is correct.
The adress is the same why prestashop change calculation?

Is there any part of the code that for some reason interact with cart total?

**Comment by khouloudbelguith** [comment]
@HartLarsson,

>The strange thing is why Prestashop make error calculation if a USA customer try to purchase from Italian Store while if i try to simulate to send the item in USA the calculation is correct.

When I try to use PS1767 an outside country (Tax not applied) => total ok
I attached a screenshot.
![image](https://user-images.githubusercontent.com/16067358/93227329-881b9f00-f774-11ea-8aa9-75919a345fbd.png)
Thanks to check and feedback.

**Comment by HartLarsson** [comment]
thank you for your test, seems working good.
The only problem i can detect could be a voucher generated by a plugin.

the voucher generated depends on a product in the cart, we can call it MAIN PRODUCT
And a list of products that are accessories,

the cart created for every accessories are like:

![image](https://user-images.githubusercontent.com/16102074/93228264-96b68600-f775-11ea-8561-9ea621d8cc1d.png)

![image](https://user-images.githubusercontent.com/16102074/93228416-bb126280-f775-11ea-90f5-2ce91b025783.png)
where 1 is the code of MAIN ARTICLE and 2 the accessory 

the action is:
![image](https://user-images.githubusercontent.com/16102074/93228481-cfeef600-f775-11ea-8403-b7fd1bf8b403.png)


I don't know if that kind of generated vouchers can create problems on cart calculation.

**Comment by khouloudbelguith** [comment]
@HartLarsson, I created discounts manually.
![image](https://user-images.githubusercontent.com/16067358/93236984-ca96a900-f77f-11ea-8654-b7695810d582.png)
For each cart rule
![image](https://user-images.githubusercontent.com/16067358/93237071-e437f080-f77f-11ea-9af6-81a9b0702a35.png)

So, do I need to add a standard product to each cart rule?

Thanks!

**Comment by HartLarsson** [comment]
Hi,
basically the accessories can be discounted only if the main product is present.
If them **main product** is called **A** and **B** & **C** are the 2 accessories, you must add **A** to the cart and **B** + **C** accessories to the cart too.

The discount working only if **A** is present in cart and discount of 30% only product B (for the voucher of B) and only product C (voucher for product C).

![image](https://user-images.githubusercontent.com/16102074/93239744-7ee5fe80-f783-11ea-9355-4f4487ae8f17.png)

marked 2 is the code of the accessory.

I've also discovered that official perstashop Paypal module 5.1.5 has a bug over vouchers. is why the first voucher discoutn is 5,70€ and progressively decfrease the value.

Don't specify a  **voucher code** so is applied automatically as soon as you add the MAIN product A and a coresponding accessory.

thanks

**Comment by khouloudbelguith** [comment]
Hi @HartLarsson,

Sorry for the late response.
> voucher generated by a plugin.

Can you please provide exact steps about vouchers (discounts) so I can create vouchers similar to your case.
Conditions Tab & Actions Tab.
In the conditions Tab, you have more than one product in "Product section"
>marked 2 is the code of the accessory.

In the actions Tab, you have a specif product, is it the reference of a combination?

You have 7 discounts with 7 different accessories, are they similar?

>main product is called A and B & C are the 2 accessories

The main product, do you mean the standard product that has combinations
The accessories, do you mean the combinations?

Can you correct me if I'm wrong!

Thanks!

**Comment by HartLarsson** [comment]
can i share with you my ecommerce site?
So is more easy for you to understand how all works.

**Comment by HartLarsson** [comment]
![image](https://user-images.githubusercontent.com/16102074/94590699-639ce800-0287-11eb-915d-65a7bb921e2c.png)

accessories are products that are managed by a plugin. The plugin permits to add to a product a list of accessories (other products) with the same price or a discounted version.
If you add a discount (when accessory is purchased with the product) the plugin creates a discount voucher (standard PS voucher) directly in the database.


the plugin in question is: https://addons.prestashop.com/it/cross-selling-product-bundle/23426-multi-accessories-pro.html

**Comment by khouloudbelguith** [comment]
@HartLarsson,

You need to contact the module author about this issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them.
I close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by HartLarsson** [comment]
I've contacted ecommerce 202 they have erleased a new version 5.2.0 that fix the problem.
I've reported here because this problem of a standard paypal official module can create problems to many installations.

The module for acessories is not affecting any prestashop calculation so was not there the problem.
