### ISSUE TITLE
Javascript error "migrateWarn is not defined" in themes/core.js when using alternate theme.

### ISSUE THREAD

**Issue by harisrnd** [PrestaShop/PrestaShop#20984]
#### Describe the bug

The following error is thrown:
Uncaught ReferenceError: migrateWarn is not defined
(themes/core.js, line 68)
If you delete the call to migrateWarn() it seems to work but I don't know if there are side effects.

#### Expected behavior
No error should be thrown

#### Steps to Reproduce
I am using a theme bought from prestashop addons("Premium Fashion Store", https://addons.prestashop.com/demo/FO33143.html). For example, the language menu throws the error.
1. Install the above theme(I haven't tested other themes)
2. Go to front page
3. Click on the language menu
4. See error in console

* PrestaShop version: 1.7.7.0-beta.2+build.1
* PHP version: 7.4

**Comment by matks** [comment]
Thank you for testing the beta !

**Comment by khouloudbelguith** [comment]
Hi @harisrnd,

PrestaShop177 is not compatible with PHP 7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2, PS177 is compatible with PHP7.3.
For more details, you can follow this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Next Major release PS1.7.8 will be compatible with PHP7.4.
You need to downgrade your PHP version.
About the theme, you should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by harisrnd** [comment]
Well, this is a javascript error, not a PHP one. However, I will consider your advice to downgrade PHP.
Contacting the theme developer was my first thought too. I quote his answer:
"Version 1.7.7 is a trial version. The problem may have occurred during migration. It is only my responsibility to fix any errors in the template. There is a bug in JQMIGRATE here - this error blocks all Javascript functions in the store".
He might be correct because after I did this minor hack in themes/core.js everything seems to work.
Ofcourse you know better than me.

Thanks you for your cooperation.

**Comment by matks** [comment]
@harisrnd the solution might come from https://github.com/PrestaShop/PrestaShop/pull/20992

**Comment by harisrnd** [comment]
It seems very relative if not the same problem.

**Comment by SimonGrn** [comment]
Hello @harisrnd,

do you still have the problem with the current version from git (not from the beta) ?

**Comment by harisrnd** [comment]
Hello,
I haven't tried to install from git. Not yet. 
It seems to work fine (so far) after I deleted the call to migrateWarn().

**Comment by khouloudbelguith** [comment]
@harisrnd, so can we close this issue?
It should be fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/20992

Thanks!

**Comment by harisrnd** [comment]
I 'm OK. Yes you can.
Thank you.

**Comment by khouloudbelguith** [comment]
@harisrnd, thanks!
I close the issue, feel free to open a new issue when needed.
