### ISSUE TITLE
Include wholesale price in orders table

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20996]
#### Is your feature request related to a problem?

Yes, client asked me to export a statistics of orders and a profit he has on them. However, wholesale prices are included only in _order_detail_ table, and not sumed up in _orders_ table.

#### Describe the solution you'd like

I would like to add total_wholesale_prices to _orders_ table.

#### Alternatives you've considered

Alternative is the way I need to do it now - get all products of order, sum them up. This would make it easier for other devs.

We can also display the profit on order screen in BO for the merchant.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

Thanks!

**Comment by MatShir** [comment]
@Hlavtox are you talking about your client as if you were a merchant? In B2B use cases between a manufacture and a client for example? :thinking: 
Or like your client as a Prestashop developer for your client that requests you to export the profit for a specific period? 

But I'm not sure the order is the best place, I'm afraid it will add complexity to this entity and overload it of information the order when you can associate easily product and orders. The feature looks goods, the dashboard displays for a specific period the profits but we could add an export option or add a new stats in the statistics pages.

**Comment by Hlavtox** [comment]
@MatShir Client requested that I make him a script, that will export him some order statistics. I wanted to calculated the margin he had on the order. I had to get this information from ps_order_detail table for each product.

Maybe you are right, better make it less complex. :-) As a developer, I do it only once... I will close this.
