### ISSUE TITLE
Option to disable sending email when changing order status

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20991]
#### Is your feature request related to a problem?

From time to time, when doing something special with orders, we want to change order status, but not send any emails, not to confuse the customer. 

It's annoying that merchant needs to go to order statuses, change the settings, then change the status and then change the settings back.

#### Describe the solution you'd like

We could add a checkbox under status selector.
If that checkbox is checked, it would not send any email, even if set so.

#### Design proposition
![status](https://user-images.githubusercontent.com/6097524/93203615-0405ef00-f755-11ea-91b5-c8bb4de74b52.PNG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
In the BO > Shop Parameters > Order Settings > Statuses page, we can disable the `send an email to the customer when his/her order status has changed. ` option.
![image](https://user-images.githubusercontent.com/16067358/93204091-c9e91d00-f755-11ea-9ab5-70aac916bc93.png)

Ping @PrestaShop/product-team what do you think of this improvement?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Sorry, updated the description... :-)

**Comment by LouiseBonnard** [comment]
Interesting! Where does the user manage its order statuses most frequently, in the order settings section or in the order itself? Does he want specific emails not be te sent or does he need to suspend some emails depending on the status and/or the order? @MatShir, @TristanLDD, any insight?

**Comment by Hlavtox** [comment]
@LouiseBonnard Too specific requirement, closing this ;-)
