### ISSUE TITLE
All pages 404 on clean install

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#20999]
#### Describe the bug

All pages are with 404 error.
```shell-script
2020/09/15 19:35:30 [error] 1488572#1488572: *1017 open() "/data/www/example.com/html/contact" failed (2: No such file or directory), client: xx.xx.xx.xxx, server: example.com, request: "GET /contact HTTP/1.1", host: "example.com", referrer: "http://example.com/"
```

#### Expected behavior

Provide working config, not part or scratch.

#### Steps to Reproduce

1. Make fresh install 1.7.6.x
     from zip file (https://download.prestashop.com/download/releases/prestashop_1.7.6.7.zip) or
     from github repository (https://github.com/PrestaShop/PrestaShop/tree/1.7.6.x)
2. Use provided config file for nginx
    https://devdocs.prestashop.com/1.7/basics/installation/nginx/
3. Get on all sub pages 404 error.

#### Additional information

* PrestaShop version: 1.7.6.x
* PHP version: PHP7.3.22-FPM

**Comment by sarahdib** [comment]
Hello @LocalHeroPro 

As indicated in [devdocs](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) PrestaShop 1.7.6. is not compatible with PHP 7.3

Please downgrade your php version.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration.

Thank you!

**Comment by LocalHeroPro** [comment]
I downgraded to PHP7.2 and I have the same issue.
Please provide proper config file for setup Prestashop.
And also sarahdib [4u](https://github.com/PrestaShop/PrestaShop/issues/21047).

**Comment by kpodemski** [comment]
It has to be related to your nginx configuration as I ran without any issues PrestaShop 1.7.6 on nginx

**Comment by LocalHeroPro** [comment]
Could you provide config file? After that we can update outdated Prestashop docs.

**Comment by LocalHeroPro** [comment]
sarahdib, also you write (and in hurry close topic with bug)
> As indicated in devdocs PrestaShop 1.7.6. is not compatible with PHP 7.3

and official package saying something different
![image](https://user-images.githubusercontent.com/42643563/93719082-ac1a1e80-fb80-11ea-8dca-ae4bfc17a700.png)
So where we have the truth?

**Comment by LocalHeroPro** [comment]
Hmmm it's interesting, because `admin-dev` working as expected, but on frontend only homepage working as expected.
Solution for that is to add in nginx config file
```apacheconfig
    location / {
        root   /var/www/presta.local/html;
        index  index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }
```
Please, reopen and add to example nginx config file to fix misleading Prestashop dosc.

**Comment by LocalHeroPro** [comment]
And also, it's look like your team double `server_name` twice.
```
# [REQUIRED EDIT] Your domain name goes here
server_name server_name example.com www.example.com;
```
I think it's unnecessary.

**Comment by matks** [comment]
> sarahdib, also you write (and in hurry close topic with bug)
> 
> > As indicated in devdocs PrestaShop 1.7.6. is not compatible with PHP 7.3
> 
> and official package saying something different
> ![image](https://user-images.githubusercontent.com/42643563/93719082-ac1a1e80-fb80-11ea-8dca-ae4bfc17a700.png)
> So where we have the truth?

Here is the truth 😄 : we have done an extensive work of deep testing of PrestaShop 1.7.7 to find and fix all compatibility issues that come with php7.3 . Consequently we can officially say "PrestaShop 1.7.7 is compatible with php7.3 because we have thoroughly checked everything works with php7.3".

However this extensive work was not done for PS 1.7.6 . So a big part of PrestaShop 1.7.6 is probably compliant with php7.3 and even php7.4 but not all of it.

The same work will happen for PS 1.7.8 and php7.4 : a very large testing campaign will be run to find and fix all issues that come with php7.4 and ensure they are fixed. This does not mean PS 1.7.7 is _completely_ broken with php7.3 . However we cannot guarantee PS 1.7.7 works fine with php7.4 . There is probably a large number of features working fine with php7.4 and a few ones which are broken.

**Comment by LocalHeroPro** [comment]
That clarifications don't mention about wrong docs and wrong compatibility and extensions checker.

**Comment by kalise0** [comment]
> Hmmm it's interesting, because `admin-dev` working as expected, but on frontend only homepage working as expected.
> Solution for that is to add in nginx config file
> 
> ```
>     location / {
>         root   /var/www/presta.local/html;
>         index  index.php;
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> ```
> 
> Please, reopen and add to example nginx config file to fix misleading Prestashop dosc.

This solved the problem by my side !

The documentation of prestashop seems ton contain errors / missing parts here : https://devdocs.prestashop.com/1.7/basics/installation/nginx/

double server_name instruction and missing part for rewrite.

**Comment by sveneusewig** [comment]
[prestashop_1.7.8.3.zip](https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.3/prestashop_1.7.8.3.zip)

```
404 Not Found
nginx/1.20.1
```

That's all there is to it with your Prestashop. Any php script and vhost can be run with my nginx, just not your Prestashop with your configuration [https://devdocs.prestashop.com/1.7/basics/installation/nginx/](https://devdocs.prestashop.com/1.7/basics/installation/nginx/).

```
XXX [notice] 15812#0: *3 "^/(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/(\d)(\d)(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/c/([\w.-]+)/.+\.jpg$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^images_ie/?([^/]+)\.(gif|jpe?g|png)$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^/api/?(.*)$" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
XXX [notice] 15812#0: *3 "^(/install(?:-dev)?/sandbox)/.*" does not match "/index.php", client: ::1, server: XXX, request: "GET / HTTP/1.1", host: "XXX"
```

I don't feel like checking your rewriting rules. Until recently it was still working.
