### ISSUE TITLE
[BO][Carriers] switching to free shipping blocked on step 2 "shipping locations and costs"

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20993]
#### Describe the bug

After adding a new carrier, I am not able to edit the kg weight ranges >= <
#### Expected behavior

Being able to edit the ranges 

#### Steps to Reproduce

1. Go to shipping/carriers
2. Edit a carrier that doesnt have free shipping enabled
3. On step 2 "Shipping locations and costs" switch the slicer to free shipping "YES"
4. Go to step 3
5. Ranges are asked while they shouldnt 

**Screenshots**

https://drive.google.com/file/d/1m-BnaUkwVeBr9-YTH9HnSzV3lmzK-lTa/view

#### Additional information

* PrestaShop version: 1.7.8 & 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

In your case, free shipping is enabled.
Can you try to disable the free shipping option, check, and feedback.
![image](https://user-images.githubusercontent.com/16067358/93230477-ff9efd80-f777-11ea-8e92-d48e6c8b488d.png)

Thanks!

**Comment by ngodefroy** [comment]
> Hi @ngodefroy,
> 
> In your case, free shipping is enabled.
> Can you try to disable the free shipping option, check, and feedback.
> ![image](https://user-images.githubusercontent.com/16067358/93230477-ff9efd80-f777-11ea-8e92-d48e6c8b488d.png)
> 
> Thanks!

After disabling free shipping on an existing one, it's not clickable at all. 
The problem seems to appears when I had a new carrier. 
If you can reproduce, I will  update the scenario. 
<img width="832" alt="Capture d’écran 2020-09-15 à 17 29 20" src="https://user-images.githubusercontent.com/69145330/93231389-fe220500-f778-11ea-8924-e5fc82f783e9.png">

**Comment by khouloudbelguith** [comment]
As discussed with @ngodefroy,

It is ok with PS1767.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi!

Also, we have an issue following these steps:

1. Go to shipping/carriers
2. Edit a carrier that doesn't have free shipping enabled
3. On step 2 "Shipping locations and costs" switch the slicer to free shipping "YES"
4. Go to the next step (error)
5. Try to disable free shipping
6. the "Add handling costs" is still disabled, we cannot enable it.

![image](https://user-images.githubusercontent.com/16067358/93353060-c7f98980-f83b-11ea-9b2a-e7950beb6af8.png)

Thanks!

**Comment by ngodefroy** [comment]
TEST OK 
https://drive.google.com/file/d/1LgJqTCUEYh8gXTc1nb6jktdNFq_TyVsq/view

Thank you @atomiix

**Comment by Progi1984** [comment]
Fixed by #21031
