### ISSUE TITLE
[Payments methods] [Configure] authent headband isnt static anymore

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20994]
#### Describe the bug

Accessing from payments methods>configure, I am redirected to ps_checkout module. There, the "authent & help" headband is floating when sliding up and down

#### Expected behavior

Conform to 1.7.7.x version> static headband

#### Steps to Reproduce

1. Go to payments methods
2. Click on configure
3. Scroll down to and see the headband "floating" 

**Screenshots**

https://drive.google.com/file/d/1lXKvAt5rkfKPQUkCympbsWRjAQnBXEEx/view

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I did not manage to reproduce the issue with the develop branch(1780)
![image](https://user-images.githubusercontent.com/16067358/93235833-645d5680-f77e-11ea-8ca6-e38dab6a0779.png)
https://drive.google.com/file/d/1Rpe7hknZVNocAAP_SPH_wvR5HIRzMt45/view?usp=sharing
Thanks to check and feedback.

**Comment by ngodefroy** [comment]
Didnt reproduce after reinstalling, thus, I close the issue.
