### ISSUE TITLE
Unsufficient URL escape of file name in customer thread (admin view)

### ISSUE THREAD

**Issue by jchazalon** [PrestaShop/PrestaShop#21008]
When, in table "$PREFIX_customer_message" the columns file_name contains filenames with special URL characters like "?", the following template fails to generate a clickable link.

https://github.com/PrestaShop/PrestaShop/blob/e3fad19753dcc155e087a6b36ad8b94b4ca02065/admin-dev/themes/default/template/controllers/customer_threads/helpers/view/message.tpl#L56

Because the "?" is not substituted to "%3F", clicking the resulting link for file names like "upload/5f5330169232?.pdf" generates a custom 404 error.

As the content of the database is (as I saw it) consistent with the content on the "upload/" directory of the server, I suggest that the template is fixed with a proper escaping of problematic URL characters. In my experience only the "?" is problematic, so I suggest to add a dedicated substitution the the template as follows:
`{$message.file_name|escape:'html':'UTF-8'}`
becomes
`{$message.file_name|escape:'html':'UTF-8'|replace:'?':'%3F'}`

This simple fix solved our repeated 404 errors on our deployed 1.7.6.5 Prestashop instance.

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-core-developers could you check this issue ? 

Thank you

**Comment by PierreRambaud** [comment]
Hi,

Nice catch, the escape is wrong, it must be `|escape:'url':'UTF-8'` instead of HTML :wink:

**Comment by jchazalon** [comment]
Thanks @sarahdib and @PierreRambaud for your interest in my small issue.

@PierreRambaud Actually the `:url:` option did not work for me either, leading me to the hack I suggested: my file paths are like `upload/fe45a215.pdf` and the URL escaping would substitute the slashes (`/`) that I need to keep. I think the `:html:` escape makes sense (we are writing HTML code after all) to some extent, but AFTER this HTML escaping there may be some characters which are special to URLs; some we want to keep (`/`) and some we want to remove (`?`).

My initial (unsuccessful) attempts were to:

- fix the file names in the uploads (why the hell is there non alphanum chars there after all?) — I failed to locate the part of the code responsible for that (files are sent using the "Contact us" form in our case);
- try to figure out how to split the file path then URL escape each part then recompose them — more complicated in the end.

I hope this clarifies a bit the reasons of my choice.

**Comment by PierreRambaud** [comment]
I tried the customer thread feature, anyway I don't understand how the filename can contain a `?`. Anyway in this case the fix must be done here: https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCustomerThreadsController.php#L634 by adding by encoding the `file_name`

**Comment by hibatallahAouadni** [comment]
Hello @jchazalon ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
