### ISSUE TITLE
Fatal Error: Interface 'PrestaShop\PrestaShop\Core\Session\SessionInterface' not found

### ISSUE THREAD

**Issue by Lajaca** [PrestaShop/PrestaShop#21007]
I cant access to advanced parametres / Team and Catalog/ Categories error 500

Until yesterday everything work well with 
* PrestaShop version: 7.7.6.5
* PHP version: 7.3.22

I didnt update last Prestashop version and change PHP version always was running on this versions

Fatal Error: Interface 'PrestaShop\PrestaShop\Core\Session\SessionInterface' not found (attached screenshots)

![Categoria](https://user-images.githubusercontent.com/71235516/93324777-a043fa80-f816-11ea-98f8-5b274c216e39.JPG)
![Equipo](https://user-images.githubusercontent.com/71235516/93324779-a1752780-f816-11ea-899e-16b2cc5fbaaa.JPG)

Anybody could help me!!!

* PrestaShop version: 7.7.6.5
* PHP version: 7.3.22

**Comment by sarahdib** [comment]
Hello @Lajaca 

PrestaShop 1.7.6.5 is not compatible with php version 7.3 as indicated [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) 

Please downgrade your php version.

Thank you

**Comment by Lajaca** [comment]
I have change PHP to 7.2.33 and there no changes and the same error advanced parametres / Team and Catalog/ Categories error 500 and Team
