### ISSUE TITLE
[BO][Languages] order ID is wrong when adding/deleting new language

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21004]
#### Describe the bug

In BO,Languages, the ID value should be forward sort when you add a new language.
I tried to add the new language a first time, it's sorted well. 
Then I delete and add a language again => wrongly sorted 

#### Expected behavior

The ID should be forward sorted

#### Steps to Reproduce

1. Go to Localizations>Languages
2. Click on add a new language
3. Fill all mandatory info
4. Save
5. check if the ID value is correct. If it IS, delete the language you just added and add it again.
6. You should see the ID not sorted correctly 

**Screenshots**

![Capture d’écran 2020-09-16 à 10 50 15](https://user-images.githubusercontent.com/69145330/93314787-8ac8d380-f80a-11ea-9ac3-cb941bb95929.png)

https://drive.google.com/file/d/1WfclET8WToreR0iID4bIbMnuW4tt6lnQ/view

#### Additional information

* PrestaShop version: 1.7.8 & 1.7.7
* PHP version: 7.2

**Comment by marionf** [comment]
Hi @ngodefroy 

> I tried to add the new language a first time, it's sorted well.
Then I delete and add a language again => wrongly sorted

I am not sure to understand the issue, the list is correctly sorted by ID ASC

**Comment by ngodefroy** [comment]
> Hi @ngodefroy
> 
> > I tried to add the new language a first time, it's sorted well.
> > Then I delete and add a language again => wrongly sorted
> 
> I am not sure to understand the issue, the list is correctly sorted by ID ASC

Hello @marionf 
It's sorted well by ID ASC, but why is the ID numbered 4 when there is 1, 2 before? Shouldnt it be 1, 2 and 3?
Thank you

**Comment by SimonGrn** [comment]
This is not an issue, ID incrementation is tied to the database engine. As long as the IDs are ranked correctly, this is normal.
You probably still have the ID 3 language in your database, it's just hidden.
