### ISSUE TITLE
Module Manager : This value should not be null

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#21009]
#### Describe the bug

If PHP configuration about `post_max_size` is too low, ZIP uploaded through Module Manager is not received so ZIP validation throw a constraint violation `This value should not be null`. But this message is not attached to a context so we don't know what is wrong.

#### Expected behavior

Error message should give an understandable information about what is wrong.

#### Steps to Reproduce

PHP Configuration `post_max_size` should be lower than ZIP filesize.

1. Go to Module Manager
2. Click on button Upload a Module
3. Select a ZIP to upload and validate

**Screenshots**

![Error](https://user-images.githubusercontent.com/5262628/93326350-f1ed8480-f818-11ea-8b2c-f7de703d0b9d.png)

#### Additional information

* PrestaShop version: 1.7.0.0 to 1.7.7.0
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @Matt75 
I reproduce this issue 
<img width="693" alt="Capture d’écran 2020-09-16 à 15 41 28" src="https://user-images.githubusercontent.com/3034677/93345481-28d09400-f833-11ea-81ea-5102b0b41ab0.png">

**Comment by wayneoutthere** [comment]
I know this is closed but I had the following experience just now:

* had a 11MB module 
* tried to upload it, got the 'this value should not be null' error above
* increased `post_max_size` limit to 15MB
* tried to upload it again, this time I got "Your limit is 10MB" (didn't get this at all first time when post_max was set to 10MB, got the null error...)
* went back into php.ini and searched the `upload_max_filesize=` and set to 15M
* tried to upload again, success

Hope this helps someone somewhere :)
