### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by robert8888** [PrestaShop/PrestaShop#21001]
I have problem with installation.

Config:
Wamp server on Windows 10: 
- PHP 7.32.21
- Apache 2.4.46
- MySql 5.7.31

- latest version of presta clone from repo.

I try to change memory limit and i still get error but after changing memory limit i don't get error detail but nothing more than literally HTTP 200 - parsererror. 

![image](https://user-images.githubusercontent.com/33148232/93270013-7526c000-f7b0-11ea-879b-3066aba2a4a1.png)

**Comment by robert8888** [comment]
( ! ) Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 36864 bytes) in Unknown on line 0
--


1 | 0.0001 | 410008 | {main}( ) | ...\index.php:0
2 | 0.0597 | 1081720 | InstallControllerHttp::execute( ) | ...\index.php:49
3 | 0.4287 | 8576984 | InstallControllerHttpProcess->process( ) | ...\controllerHttp.php:266
4 | 0.4291 | 8577008 | InstallControllerHttpProcess->processInstallModules( ) | ...\process.php:102
5 | 0.4771 | 9031472 | PrestaShopBundle\Install\Install->installModules( ) | ...\process.php:230
6 | 0.5623 | 11327736 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install( ) | ...\Install.php:1070
7 | 1.5993 | 16765584 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->checkAndClearCache( ) | ...\ModuleManager.php:314
8 | 1.5993 | 16765584 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->clearCache( ) | ...\ModuleManager.php:695
9 | 1.5993 | 16765584 | PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->clear( ) | ...\ModuleManager.php:708
10 | 1.6023 | 16788984 | Symfony\Bundle\FrameworkBundle\Console\Application->run( ) | ...\SymfonyCacheClearer.php:67
11 | 1.6971 | 16789872 | Symfony\Bundle\FrameworkBundle\Console\Application->doRun( ) | ...\Application.php:148
12 | 1.7159 | 17109944 | Symfony\Bundle\FrameworkBundle\Console\Application->doRun( ) | ...\Application.php:74
13 | 1.7173 | 17117640 | Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand( ) | ...\Application.php:255
14 | 1.7173 | 17117640 | Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand( ) | ...\Application.php:86
15 | 1.7238 | 17325600 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->run( ) | ...\Application.php:1005
16 | 1.7241 | 17326808 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute( ) | ...\Command.php:255
17 | 4.7032 | 17400800 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup( ) | ...\CacheClearCommand.php:133
18 | 41.4288 | 46242904 | Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp( ) | ...\CacheClearCommand.php:221
19 | 124.0890 | 239826936 | Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp( ) | ...\CacheWarmerAggregate.php:52
20 | 147.6256 | 288565984 | Twig\Environment->loadTemplate( ) | ...\TemplateCacheWarmer.php:62
21 | 147.6267 | 288566736 | Twig\Environment->loadClass( ) | ...\Environment.php:445
22 | 147.6270 | 288575184 | Twig\Environment->compileSource( ) | ...\Environment.php:482
23 | 147.6457 | 288774792 | Twig\Environment->parse( ) | ...\Environment.php:793
24 | 147.6457 | 288774792 | Twig\Parser->parse( ) | ...\Environment.php:735
25 | 147.6741 | 289083488 | Twig\NodeTraverser->traverse( ) | ...\Parser.php:143
26 | 147.6884 | 289083512 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:56
27 | 147.6887 | 289084448 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
28 | 147.6887 | 289085064 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
29 | 147.6897 | 289097720 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
30 | 147.6900 | 289097720 | Twig\NodeVisitor\EscaperNodeVisitor->leaveNode( ) | ...\NodeTraverser.php:85
31 | 147.6900 | 289097720 | Twig\NodeVisitor\EscaperNodeVisitor->doLeaveNode( ) | ...\AbstractNodeVisitor.php:41
32 | 147.6900 | 289097720 | Twig\NodeVisitor\EscaperNodeVisitor->escapePrintNode( ) | ...\EscaperNodeVisitor.php:81
33 | 147.6900 | 289097720 | Twig\NodeVisitor\EscaperNodeVisitor->isSafeFor( ) | ...\EscaperNodeVisitor.php:139
34 | 147.6900 | 289097720 | Twig\NodeTraverser->traverse( ) | ...\EscaperNodeVisitor.php:178
35 | 147.6900 | 289097720 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:56
36 | 147.6903 | 289105392 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
37 | 147.6903 | 289105392 | Twig\NodeVisitor\SafeAnalysisNodeVisitor->leaveNode( ) | ...\NodeTraverser.php:85
38 | 147.6903 | 289105392 | Twig\NodeVisitor\SafeAnalysisNodeVisitor->doLeaveNode( ) | ...\AbstractNodeVisitor.php:41
39 | 147.6903 | 289105392 | Twig\NodeVisitor\SafeAnalysisNodeVisitor->setSafe( ) | ...\SafeAnalysisNodeVisitor.php:86
40 | 148.8332 | 289102288 | Symfony\Component\Debug\ErrorHandler::handleFatalError( ) | ...\ErrorHandler.php:0
41 | 148.8333 | 289090768 | spl_autoload_call ( ) | ...\ErrorHandler.php:683
42 | 148.8333 | 289090848 | Composer\Autoload\ClassLoader->loadClass( ) | ...\ErrorHandler.php:683
43 | 148.8338 | 289091040 | Composer\Autoload\includeFile( ) | ...\ClassLoader.php:322


I suppose  that problem start here: 
19 | 124.0890 | 239826936 | Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp( ) | ...\CacheWarmerAggregate.php:52
20 | 147.6256 | 288565984 | Twig\Environment->loadTemplate( ) | ...\TemplateCacheWarmer.php:62

and then "traverserForVisitor" have a problem

**Comment by sarahdib** [comment]
Hello @robert8888 

As indicated in [devdocs](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) PrestaShop 1.7.6. is not compatible with PHP 7.3

Please downgrade your php version.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration.


Thank you!

**Comment by robert8888** [comment]
I've downgrade php to 7.2.33 and i still have the same problem.

error stack: 

( ! ) Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in D:\PROJEKTY\APKI\lubieksiazki\PrestaShop\vendor\twig\twig\src\Node\Node.php on line 217
--


1 | 0.0001 | 406424 | {main}( ) | ...\index.php:0
2 | 0.0535 | 1127408 | InstallControllerHttp::execute( ) | ...\index.php:49
3 | 0.2970 | 8735872 | InstallControllerHttpProcess->process( ) | ...\controllerHttp.php:266
4 | 0.2973 | 8735896 | InstallControllerHttpProcess->processInstallModules( ) | ...\process.php:102
5 | 0.3376 | 9313648 | PrestaShopBundle\Install\Install->installModules( ) | ...\process.php:230
6 | 0.3905 | 11571304 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install( ) | ...\Install.php:1070
7 | 5.9500 | 17481960 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->checkAndClearCache( ) | ...\ModuleManager.php:314
8 | 5.9500 | 17481960 | PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->clearCache( ) | ...\ModuleManager.php:695
9 | 5.9500 | 17481960 | PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->clear( ) | ...\ModuleManager.php:708
10 | 5.9522 | 17505584 | Symfony\Bundle\FrameworkBundle\Console\Application->run( ) | ...\SymfonyCacheClearer.php:67
11 | 6.0287 | 17506728 | Symfony\Bundle\FrameworkBundle\Console\Application->doRun( ) | ...\Application.php:148
12 | 6.0446 | 17844408 | Symfony\Bundle\FrameworkBundle\Console\Application->doRun( ) | ...\Application.php:74
13 | 6.0461 | 17852104 | Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand( ) | ...\Application.php:255
14 | 6.0461 | 17852104 | Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand( ) | ...\Application.php:86
15 | 6.0512 | 17937960 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->run( ) | ...\Application.php:1005
16 | 6.0515 | 17939112 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute( ) | ...\Command.php:255
17 | 8.0123 | 18154016 | Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup( ) | ...\CacheClearCommand.php:133
18 | 34.3257 | 40539296 | Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp( ) | ...\CacheClearCommand.php:221
19 | 91.7801 | 253466360 | Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp( ) | ...\CacheWarmerAggregate.php:52
20 | 104.0206 | 288212720 | Twig\Environment->loadTemplate( ) | ...\TemplateCacheWarmer.php:62
21 | 104.0216 | 288213504 | Twig\Environment->loadClass( ) | ...\Environment.php:445
22 | 104.0218 | 288221952 | Twig\Environment->compileSource( ) | ...\Environment.php:482
23 | 104.0306 | 288175112 | Twig\Environment->parse( ) | ...\Environment.php:793
24 | 104.0306 | 288175112 | Twig\Parser->parse( ) | ...\Environment.php:735
25 | 104.0470 | 288437296 | Twig\NodeTraverser->traverse( ) | ...\Parser.php:143
26 | 104.1085 | 288892008 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:56
27 | 104.1085 | 288892944 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
28 | 104.1085 | 288893560 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
29 | 104.1089 | 288894496 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
30 | 104.1089 | 288895112 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
31 | 104.1090 | 288895728 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
32 | 104.1107 | 288897304 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
33 | 104.1107 | 288897920 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
34 | 104.1108 | 288898536 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
35 | 104.1108 | 288899152 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
36 | 104.1108 | 288899768 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
37 | 104.1109 | 288900384 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
38 | 104.1109 | 288901320 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
39 | 104.1109 | 288901936 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
40 | 104.1109 | 288902552 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
41 | 104.1109 | 288903168 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
42 | 104.1110 | 288903784 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
43 | 104.1111 | 288904400 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
44 | 104.1111 | 288905016 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
45 | 104.1111 | 288905632 | Twig\NodeTraverser->traverseForVisitor( ) | ...\NodeTraverser.php:76
46 | 104.1111 | 288905632 | Twig\Node\Node->getIterator( ) | ...\NodeTraverser.php:71
47 | 104.1111 | 288905816 | __construct ( ) | ...\Node.php:217
