### ISSUE TITLE
Remove dependency on MomentJS

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#21012]
#### Describe the bug

MomentJS has announced that it a legacy project in maintenance mode. Not dead, but it is indeed done.
https://momentjs.com/docs/#/-project-status/

Would it make sense to remove the dependency on moment from this library? Especially now that Moment is a deprecated library, has a huge size and is not tree-shakeable.
The Momentjs team has recommended some libraries which can be used in its place.

Used in [admin-dev/themes/new-theme/package.json#L36](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/package.json#L36).

#### Expected behavior

Remove dependency on MomentJS

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-core-developers What do you think about that ?

**Comment by PierreRambaud** [comment]
I agree I don't even know where we use this library :sweat_smile:

**Comment by Progi1984** [comment]
@PierreRambaud : `admin-dev/themes/new-theme/.webpack/common.js` (l.250)

**Comment by NeOMakinG** [comment]
It's required for bootstrap datetime picker, the main maintainer  plane to remove it but for now we're blocked with it 

https://eonasdan.com/posts/state-of-my-picker

Also, this dependency should probably be inside the UIKit instead of the main project, but it won't resolve this issue at all

**Comment by PierreRambaud** [comment]
I think we can close this pull request if it's mandatory for our dependencies :)

**Comment by NeOMakinG** [comment]
Yes, it will be naturally removed when it will kicked from boostrap-datetime-picker
