### ISSUE TITLE
[IMPROVEMENT][FO][CART SUMMARY]  Add product link in summary cart 

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21010]
## Is your feature request related to a problem?

Several products may have similar names, in some cases customers have doubts if they have added the correct product to their cart.
In this case it would be interesting to add the product links, so that the customer can see the product page again.

### Before 

![image](https://user-images.githubusercontent.com/16455155/93329946-4a735080-f81e-11ea-90e8-03be3b623dfc.png)

### After

![image](https://user-images.githubusercontent.com/16455155/93330141-a047f880-f81e-11ea-9725-6efc59492761.png)

**Comment by sarahdib** [comment]
@PrestaShop/product-team could you check this improvement ?
Thank you!

**Comment by LouiseBonnard** [comment]
Hi @PululuK, thanks for this nice improvement! Product thumbnails are already clickable but it might be more explicit to also have the name redirecting to the product page.
