### ISSUE TITLE
Change Search from dropdown list to input field

### ISSUE THREAD

**Issue by HanaBenHammouda** [PrestaShop/PrestaShop#21024]
Hi, good evening,

I configure the module ps_facetedsearch in Prestashop 1.7, i need in my website to search Brand instead of dropdown list, i need to search brand in input field.

Really, I find myself blocked here. I need your help and I would be deeply grateful for your support.

![dropdownn](https://user-images.githubusercontent.com/36226026/93363618-6a673c00-f83f-11ea-82ef-90fa7e6b28ac.png)
![soscommunauté](https://user-images.githubusercontent.com/36226026/93363694-810d9300-f83f-11ea-8fd4-726d6fe551f9.png)

**Comment by florine2623** [comment]
Hi @HanaBenHammouda ,
If you need help for any specific development, you can contact an [agency](https://www.prestashop.com/en/experts), [support team](https://addons.prestashop.com/en/388-support) or the [forum](https://www.prestashop.com/forums/).

This place is only for bugs found !
Thanks!
