### ISSUE TITLE
Allow modules to participate in symfony compiler passes

### ISSUE THREAD

**Issue by jbenezech** [PrestaShop/PrestaShop#21028]
#### Is your feature request related to a problem?

This is a bit of a follow up to this one: https://github.com/PrestaShop/PrestaShop/pull/8342 .  
After this PR, modules can now register services, but cannot yet participate in building the container with their own compiler passes.  
It would be great to be able to do so to register custom listener tags and so on.  
Furthermore, modules can reuse third party Symfony bundles but these cannot be registered with the container. If modules could 
participate in the container building phase, they could also register these third party bundles themselves.

#### Describe the solution you'd like

I'm not sure the reason why modules cannot just "be" bundles if they implement the `BundleInterface` and be registered directly in the Kernel. Need more insight onto this.

#### Alternatives you've considered

The only alternative atm is to modify Prestashop's AppKernel I think, which is only viable for our own websites.

**Comment by florine2623** [comment]
Hi @jbenezech ,
Thanks for the suggestion.
Our teams will take a look at it and review your request.
Please stay tuned !

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
Hi, here's a beginning of an answer:

## About modules as bundles

> I'm not sure the reason why modules cannot just "be" bundles if they implement the `BundleInterface` and be registered directly in the Kernel. Need more insight onto this.

The main issues we encounter are these:

1. Bundles need to be activated inside [AppKernel](https://github.com/PrestaShop/PrestaShop/blob/develop/app/AppKernel.php) so if modules can act as bundles, then we need to make dynamic, able to register any installed module as bundle. I started something but it feels not very robust as it must handles different usecases (buggy modules, uninstall modules, etc ...). You can read the exploration and the obstacles we encountered in https://github.com/PrestaShop/PrestaShop/issues/14541

2. Bundles quite often come with dependencies fetched through Composer and currently we have issues with it https://github.com/PrestaShop/PrestaShop/issues/12586

## About modules registering CompilerPasses

If modules were bundles it would be very easy to do 😛 but without it, the same issue 1. will come: a shop can install a variable number of modules, some might have CompilerPasses, other not. How do you efficiently "detect" the ones you must register ? Using file/folder parsing our PHP Reflection is not performing unless you cache the result, then you open the door of "cache issues" and how to manage/clear the cache

**Comment by jbenezech** [comment]
Thanks a lot for pointing at #14541 which I had totally missed and which is what I had in mind, kind-off.  
Let's mark this issue as a duplicate and close it. I'll try to participate in the discussion in #14541

**Comment by khouloudbelguith** [comment]
Duplicate of #14541
