### ISSUE TITLE
[BO][Order settings] Reordering not displayed 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21023]
#### Describe the bug

In BO, go to order settings, and verify that "disable reordering option" is switched to no, then try to reorder a product on FO > reorder link not displayed

#### Expected behavior

Reorder link should be displayed when and only in the case disable reordering option is set to NO

#### Steps to Reproduce

1. Go to BO, set disable reordering opt to NO
2. In FO, order a product
3. Go to order history and try to reorder
4. See the link not appearing 

**Screenshots**
Enable guest checkout NO
<img width="941" alt="Capture d’écran 2020-09-16 à 17 31 24" src="https://user-images.githubusercontent.com/69145330/93359031-7274ab00-f842-11ea-9586-be0260a5fce5.png">

see reorder not appearing
<img width="1208" alt="Capture d’écran 2020-09-16 à 17 31 52" src="https://user-images.githubusercontent.com/69145330/93359119-83bdb780-f842-11ea-8755-5eff6428f7c9.png">

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by marionf** [comment]
Hi @ngodefroy 

I can't reproduce the issue

![capture d'écran_2787](https://user-images.githubusercontent.com/13449658/93436091-9bd91980-f8ca-11ea-97c4-b3a93946f032.png)

![capture d'écran_2788](https://user-images.githubusercontent.com/13449658/93436103-9e3b7380-f8ca-11ea-956c-922dbd19da26.png)

In the issue description you say "verify that disable reordering option is switched to no" but in your screenshot it's set on yes, maybe is the reason why you don't see the reorder link ?

**Comment by ngodefroy** [comment]
> Hi @ngodefroy
> 
> I can't reproduce the issue
> 
> ![capture d'écran_2787](https://user-images.githubusercontent.com/13449658/93436091-9bd91980-f8ca-11ea-97c4-b3a93946f032.png)
> 
> ![capture d'écran_2788](https://user-images.githubusercontent.com/13449658/93436103-9e3b7380-f8ca-11ea-956c-922dbd19da26.png)
> 
> In the issue description you say "verify that disable reordering option is switched to no" but in your screenshot it's set on yes, maybe is the reason why you don't see the reorder link ?

Hello Marion,

Yes, indeed your right ..went too quickly running the issue.
I will close the issue. 
Thank you :)
