### ISSUE TITLE
Display default carriers list(Transporteurs disponibles) in page product

### ISSUE THREAD

**Issue by hasanshaker** [PrestaShop/PrestaShop#21026]
1-
------------
![Capture d’écran 2020-09-17 085818](https://user-images.githubusercontent.com/25296917/93431128-0044aa80-f8c4-11ea-8a01-09addeb59061.png)

2-  
------------
![Capture d’écran 2020-09-17 085950](https://user-images.githubusercontent.com/25296917/93431280-34b86680-f8c4-11ea-9435-a252e2a3181d.png)

Thanks!

**Comment by SimonGrn** [comment]
Dear @hasanshaker 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
