### ISSUE TITLE
[FO] Put Display of delivery time in in Bold to make it more identifiable

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21039]
#### Describe the bug

In BO, Shop param>Product settings, I put a delivery time of in stock products.
I save, go to FO, check the delivery time of my products which is a bit "hidden" inside the whole description, making it Bold may help to quickly see the delivery time - as it is often an important point to customers.

#### Steps to Reproduce

1. Go to BO, Shop param>product settings
2. Set a Delivery time of in stock products and save
3. Check the result in FO on a product page.

**Screenshots**

![Capture d’écran 2020-09-17 à 14 53 48](https://user-images.githubusercontent.com/69145330/93472878-993fe980-f8f5-11ea-9c6b-135e9c502ff6.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

@prestascott, could you link it to the EPIC related?

Thank you

**Comment by prestascott** [comment]
Hi @ngodefroy!

Thanks for your report. :)

As discussed previously, I will add this improvement to the related Epic.

**Comment by matks** [comment]
Might be fixed by https://github.com/PrestaShop/PrestaShop/pull/21217/
