### ISSUE TITLE
[BO- Stores page] Sort by post code not working

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#21038]
#### Describe the bug

When sorting by post code, the result is incorrect

#### Expected behavior

Should be well sorted

#### Steps to Reproduce

1. Go to BO -> shop parameters -> Contact -> Stores
2. Click on column post code to sort by
3.Check that the sort is incorrect

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/48441421/93472431-eb343f80-f8f4-11ea-92de-21955fc65a06.png)

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: php 7.2

**Comment by khouloudbelguith** [comment]
I manage to reproduce the issue with PS1767

**Comment by khouloudbelguith** [comment]
Ping @matks @marionf this issue could be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10624?
Thanks!

**Comment by matks** [comment]
> Ping @matks @marionf this issue could be fixed in this ticket: #10624?
> Thanks!

Yes indeed :) when we migrate the page, fixing the sort is definitely part of "providing a fully functional page" 👍

**Comment by matks** [comment]
> > Ping @matks @marionf this issue could be fixed in this ticket: #10624?
> > Thanks!
> 
> Yes indeed :) when we migrate the page, fixing the sort is definitely part of "providing a fully functional page" 👍

So @PululuK fixed it before we did 😆
