### ISSUE TITLE
Improvement for ps_customtext

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21030]
After testing the new release of ps_customtext I found some improvement to do : 

- Go to admin -> modules -> ps_customtext
See that there is a button return to list but the button redirect to the same page 
https://drive.google.com/file/d/1zwf-AhLyEyJ-W3K7phr3NDn4adwcM-MT/view

- The description indicate that we can add several blocs but it's not possible in the module configuration
<img width="864" alt="Capture d’écran 2020-09-17 à 11 39 55" src="https://user-images.githubusercontent.com/3034677/93454562-76084080-f8db-11ea-93ff-d040d7c82806.png">

- Add a message when we save the modification to indicate that is ok

**Comment by hibatallahAouadni** [comment]
Hello @sarahdib & @Progi1984 

It seems the PR https://github.com/PrestaShop/ps_customtext/pull/46 has been merged :tada: 
So shall we close this issue as **`Fixed`**?

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni OK for closing
