### ISSUE TITLE
Faceted search error indexing prices

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#21036]
Hi there...
i decided to update my Faceted search module filter template and when i tried to index rebuild entire price index the process goes to 500/1050 prices and then Price indexing failed..
i am using the latest prestashop version and the module is at its latest version..
Can anyone tell me what can be wrong?

Thank you in advance

**Comment by florine2623** [comment]
Dear @Stampa-Stampa ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
