### ISSUE TITLE
[BO][Shop param] [Product settings] changes in the behavior with ordering Out of stock products

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21037]
#### Describe the bug

In 1767 & 177x, when I select "enable stock management" to "NO", "Allow ordering of out of stock products" activates itself automatically.
In 178x version, its not done automatically.
Thus, when I have "enable stock management" set to NO and swtich to NO "Allow orderring of out of stock products", then save, I get "update successful" - while it's not changed (bc not compatible) 

#### Expected behavior

It should be the same behavior as the previous versions: If stock management is desactivated, allow ordering gets automatically activated

@PrestaShop/product-team  could you confirm this is the right behavior to apply?

#### Steps to Reproduce

1. Go to 'Shop param> product settings>product stock
2. Switch  enable stock management  to NO
3. Click on Allow ordering of out of stock products to NO
4. See the Allow ordering of out of stock products switched back to "YES" while saving.

**Screenshots**

178 version:
https://drive.google.com/file/d/1EDomlnk-7e-y_ZFkHBqrgJTET_GUet4G/view

177x, 1767 version:
https://drive.google.com/file/d/1ynLiX-UEH2_CNg7rlV3vPbm0o_0mQvCE/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.3

## Specs

When I set "enable stock management" to "NO", then "Allow ordering of out of stock products" activates itself automatically if it was not and being not clickable.

![capture d'écran_2803](https://user-images.githubusercontent.com/13449658/95101070-0ba42c80-0732-11eb-9351-92cdcf526f47.png)

**Comment by matthieu-rolland** [comment]
closed, see issue #21819.
