### ISSUE TITLE
SSL enabled - The help sidebar doesn't work when using https://

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21044]
#### Describe the bug

When SSL is enabled & in all pages enabled also using `https://`
![image](https://user-images.githubusercontent.com/16067358/93487447-95b45e80-f905-11ea-8e0d-32c9afdfc2c1.png)
TRy to open help box => see error

#### Steps to Reproduce

1. Enable SSL & SSL in all pages
2. Try to navigate to any page using `https://` (legacy or migrated page)
3. click on "help"
![image](https://user-images.githubusercontent.com/16067358/93487992-22f7b300-f906-11ea-9a31-ab91cd9fbe44.png)

![image](https://user-images.githubusercontent.com/16067358/93488102-46baf900-f906-11ea-9df9-1cb0d523ebc4.png)

#### Additional information

* PrestaShop version: 1.7.6.7, develop(1780)
* PHP version: 7.1

**Comment by kpodemski** [comment]
There's a problem with SSL certificate for help.prestashop.com:
https://help.prestashop.com/api/?request=getHelp%3DAdminDashboard%26version%3D1.7.6.1%26language%3Dpl&callback=jQuery1110009818400962809393_1600376734021&_=1600376734022

**Comment by atomiix** [comment]
You were right, Thanks @kpodemski! It should be fixed now @khouloudbelguith 

Edit: not yet actually, but soon 😅

Edit 2: should be all good now!

**Comment by marionf** [comment]
@khouloudbelguith Could you verify and close the issue if it's ok for you ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is ok :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/16067358/94280028-354c9f00-ff4d-11ea-9a73-a72189b6714b.png)


Thanks!
