### ISSUE TITLE
actionProductCancel not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#21046]
#### Steps to Reproduce

1. Install 1.7.7 beta
2. Make a module which uses actionProductCancel. 
Or install Google Analytics module and put something like `file_put_contents(_PS_ROOT_DIR_ . '/hookActionProductCancel.txt', "test");` into `public function hookActionProductCancel`
3. Go to BO order view.
4. Click Partial refund. Enter 1 piece. Confirm.
5. The hook is not called and no logic is processed.

#### Additional information

* PrestaShop version: 1.7.7 beta
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
Here's the function after the changes :

```
public function hookActionProductCancel($params)
    {
        file_put_contents(_PS_ROOT_DIR_ . '/hookActionProductCancel.txt', "test"); 
        $hook = new PrestaShop\Module\Ps_Googleanalytics\Hooks\HookActionProductCancel($this, $this->context);
        $hook->setParams($params);
        $hook->run();
    }
```

I managed to do the partial refund :
![Capture d’écran 2020-09-18 à 10 24 35](https://user-images.githubusercontent.com/16019289/93575085-7b2bc500-f999-11ea-8970-7cdea6e04934.png)
![Capture d’écran 2020-09-18 à 10 27 57](https://user-images.githubusercontent.com/16019289/93575199-a3b3bf00-f999-11ea-8918-492ef08ea198.png)

**Comment by Hlavtox** [comment]
@florine2623 Did the file get created in PS directory or not? The refund goes through, but the hook is not called.

**Comment by florine2623** [comment]
@Hlavtox ,
Yes I created the file the PS directory.
How can I see that the hook is not called ?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Your issue is it similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20712? fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/20693.

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
