### ISSUE TITLE
Quantities disappeared from all my Prestashop Back-office 👀 

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21058]
Hi, I am on Prestashop 1.7.6.7
My Shop is my business and it's really important to solve it.
Since I shared my Quantities between my 2 shops (Multishop), ALL the quantities disappeared from Back-Office. (global product view or individual). This problem occurs if I select "All Shop" or only one. 
![Capture d’écran 2020-09-18 à 13 53 29](https://user-images.githubusercontent.com/43704805/93594799-d15b3100-f9b6-11ea-9347-83483e7d4e91.png)
![error-presta](https://user-images.githubusercontent.com/43704805/93594809-d61fe500-f9b6-11ea-95aa-b2cc10c73463.jpg)

Thank you for your help.

**Comment by florine2623** [comment]
Hi @passio777x ,
You need to activate the stock management in BO > Shop Parameters > Products > Products Stock :
![Capture d’écran 2020-09-18 à 14 06 19](https://user-images.githubusercontent.com/16019289/93595566-4713cc80-f9b8-11ea-9014-f5c1f637f7ab.png)
Thanks!

**Comment by passio777x** [comment]
Oh, thank you !!! sorry ! It's true that I disable it because in my products, all have been configure with : "Refuse order if quantity = 0".
All my products are now on "refuse", is there a way to modify all product with "accept order" or "use default (accept)" ?

**Comment by passio777x** [comment]
> Hi @passio777x ,
> You need to activate the stock management in BO > Shop Parameters > Products > Products Stock :
> ![Capture d’écran 2020-09-18 à 14 06 19](https://user-images.githubusercontent.com/16019289/93595566-4713cc80-f9b8-11ea-9014-f5c1f637f7ab.png)
> Thanks!

I am sorry ! Thank you so much !

**Comment by passio777x** [comment]
> Hi @passio777x ,
> You need to activate the stock management in BO > Shop Parameters > Products > Products Stock :
> ![Capture d’écran 2020-09-18 à 14 06 19](https://user-images.githubusercontent.com/16019289/93595566-4713cc80-f9b8-11ea-9014-f5c1f637f7ab.png)
> Thanks!

In my product, all has been configure with "refuse order if no stock", how to modify this with "accept" or "default (accept) ?
I tryed to modify out_of_stock value (all is on 2) but it doesnt work.
