### ISSUE TITLE
Product categories, relations always updated when not needed

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#21052]
Hello,
Prestashop 1.7.5.1, but it is for all versions I think.

On function updateCategories of product class (legacy) :
`

        // if none are found, it's an error
        if (!is_array($result)) {
            return false;
        }

`
If no results, $results will be an empty array, so it will not return false, code below will be executed, existing categories links will be deleted, re created, and most important, specific prices will be also deleted and re created, increasing time, resources...
I have 4,5 millions specific price lines in the database, specific price rule are applies too many times (delete features, add features, update categories...), 10 min to update one product...  Code needs to be refactored !!!!
I have checked the last version 1.7.7, this is still not improved ! same shits.

**Comment by florine2623** [comment]
Hi @rflorent ,

Please be more specific AND follow the issue template so that we can improve our solution.

I will close your issue. Feel free to open a new one when all information is gathered and well explained.

Thanks
