### ISSUE TITLE
Product save : categories relations always updated event not needed

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#21055]
#### Describe the bug
Edit a product, save it, categories relations will be deleted, recreate etc event if there's no changes.
Below the code concerned.

/Classes/Products.php ==>  function updateCategories

https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1340

    // if none are found, it's an error
    if (!is_array($result)) {
        return false;
    }

If no results, $results will be an empty array, so it will not return false, code after will be executed, existing categories links will be deleted, re created, and most important, specific prices will be also deleted and re created, increasing time, resources...
I have 4,5 millions specific price lines in the database, specific price rule are applies too many times (delete features, add features, update categories...), 10 min to update one product... Code needs to be refactored !!!!
I have checked the last version 1.7.7, this is still not improved ! same buggy code.

Don't close and don't tell me to be more specific @florine2623 

#### Expected behavior

Return false when categories update is not required, on a product save.+
Saving time, resources and brain

#### Steps to Reproduce

1. Edit one product
2. Don't edit categories links
3. Save

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2.33

**Comment by matks** [comment]
Hi, the tone of the comments on this issue is quite heated, please remember we have a Code of Conduct https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md that says:

- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members

So this statement does not look like welcoming and inclusive language:
```
I have checked the last version 1.7.7, this is still not improved ! same shits.
```

Please let us resume to a more friendly tone 😉

**Comment by matks** [comment]
@rflorent You are right, because the check `if (!is_array($result)` is not right the code continues in the next part of the function on mistake.

A simple fix like this fixes this issue 😉 https://github.com/matks/PrestaShop/commit/69b2d39d9f17aa52462d4a8404dca8fea6da59b0

Would you be willing to open a Pull Request ? This way you would be credited for the bugfix ? Else I can open the PR

**Comment by rflorent** [comment]
@matks sorry for the tone,  it's annoying to spend a lot of time fixing bugs, facing performance issues and have customer's dissatisfaction since I move to the 1.7 version... big mistake.

It's a small thing to fix, but it's the part a bigger thing. Let's see what I'm talking about : 
https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1345

If categories changes, old categories will be deleted, for each category deleted, the product specific prices will be deleted and recreated : 

https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1383

After this, the product specific prices will be deleted and recreated again
https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1352

So if I make 10 changes, product specific prices will deleted, recreated 11 times.
Same things, with the features, so product specific prices can be call maybe 20 times.
If you have millions specific price records, it's not usable at all.

**Comment by rflorent** [comment]
@matks I've done some tests, finally there's no fix to add on 
https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1340
It's only means that there is no categories relations to delete.
If $results is empty, and false is returned, new categories relations won't be created, as code below won't be executed. 
https://github.com/PrestaShop/PrestaShop/blob/bd864354584de312007fc7bd314f20173f0f6bdc/classes/Product.php#L1348
Comments on performances issues due to too many calls on SpecificPriceRules::applyAllRules are still relevant.

**Comment by matks** [comment]
> So if I make 10 changes, product specific prices will deleted, recreated 11 times.
> Same things, with the features, so product specific prices can be call maybe 20 times.
> If you have millions specific price records, it's not usable at all.

If I understand correctly, we could say that this process is all right for "single category update" as indeed we need to recompute and revalidate related data objects (like specific prices) after a change in category data ; but this is quite expensive for "bulk category update".

How are you updating categories ? Not one by one from the interface I believe. Are you using the webservices or a CSV Import ? Or a module ?

**Comment by rflorent** [comment]
I use the admin product form edition of Prestashop, no modules or webservice. It's not a mass action at all. It's about product's categories relations, not category entity directly. When saving, the big form is send, product's categories, product's features... all data in that form is handled in one submit.

The process is all right if you haven't a lot of specific prices otherwise it will cause performance issues. 
SpecificPriceRules::applyAllRule is call in several product class methods like deleteCategory, updateCategories,  addToCategories, deleteFeatures, addFeaturesToDB...

updateCategories will call many of theses methods, sometimes on each category relation like delete.
The result is a huge quantity of useless specific price queries, as it will erase all and re create all many times, it takes more than 10 min sometimes.

SpecificPriceRules::applyAllRule should be called one time after all theses product's actions and only if needed, because, it's will recreate all product specific prices according to all product's properties matched with the prices rules. 

I'm aware that product's methods can be call directly for partials actions and price have to be refresh. SpecificPriceRules::applyAllRule calls in product's class methods could be bypassed for the admin product edit action.
