### ISSUE TITLE
BO - Modules / No "see less", "see more" links in the modules list

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#21054]
#### Describe the bug

In the module list page there is no "see more", "see less" links

#### Expected behavior

The links should be displayed

#### Steps to Reproduce

1. Go to BO/Improve/Modules/Modules manager
2. Check in the modules listing
4. See error ( no "see more" "see less" links)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/40635814/93573057-fb9cf680-f996-11ea-95ba-6837fe06f7c8.png)
![image](https://user-images.githubusercontent.com/40635814/93573107-0788b880-f997-11ea-8fd0-b6674a55b81c.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by PierreRambaud** [comment]
The pagination has been removed here: https://github.com/PrestaShop/PrestaShop/issues/17871 with this pull request https://github.com/PrestaShop/PrestaShop/pull/19580

**Comment by PierreRambaud** [comment]
FYI I'm on it
