### ISSUE TITLE
[BO][Multistore][Theme] Virtual URL link returns exception 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21066]
#### Describe the bug

In the BO, add a new theme (I added the oslo theme)
Then go to multistore, add a shop with the new theme.
Add a virtul link, then click on it. You see a contexterrorexception.

#### Expected behavior

Get redirected to the page we clicked to. 

#### Steps to Reproduce

1. Go to BO, add a new theme (add oslo in my case)
2. Go to multistore, add a shop with the new theme
3. Add a virtual link
4. Click on that link.
5. See the error. 

**Screenshots**
<img width="1243" alt="Capture d’écran 2020-09-18 à 18 05 20" src="https://user-images.githubusercontent.com/69145330/93619920-86064a00-f9d9-11ea-98bc-f665f8831d06.png">

#### Additional information
**Note, this issue may have an impact on PR https://github.com/PrestaShop/PrestaShop/pull/20033 ?**

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by marionf** [comment]
@ngodefroy Maybe this error is related to the theme, could you try with another theme to be sure ?

**Comment by ngodefroy** [comment]
> @ngodefroy Maybe this error is related to the theme, could you try with another theme to be sure ?

I tried with another theme, same issue: 
![Capture d’écran 2020-09-21 à 14 08 14](https://user-images.githubusercontent.com/69145330/93764722-e54f9e80-fc13-11ea-99c6-9e68813f1c22.png)

**Comment by ngodefroy** [comment]
@marionf  Just tried with another one, this time, it worked ! 
Should I close the issue? Or can the 2 others themes be fixed by a PR?

**Comment by marionf** [comment]
The issue should rather be fixed in the themes, so I close it
