### ISSUE TITLE
 availability preferences -> All swapped in "Refuse Order"

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21061]
Hi, all my product have been modified and configured with "Refuse order" in preferences.
My wife had to change everything manually previous time it happened.
Now, I would like to know a way to modify this in database.

I though it was "out_of_stock" in ps_product, all in on "2", but modify this value do not affect availability preference. 

Thank you for your help.

**Comment by florine2623** [comment]
Hi @passio777x ,
You can change the availability preferences in the database, in table `ps_stock_available`, in column  `out_of_stock`
0 = Deny orders
1 = Allow orders
2 = Use default behavior (Allow orders)
![Capture d’écran 2020-09-18 à 15 10 11](https://user-images.githubusercontent.com/16019289/93601173-12f0d980-f9c1-11ea-800c-092c610dcca2.png)

If you want to change the Visibility of the product, you need to go to `ps_product`, column `available_for_order`
1 = available
0 = not available
![Capture d’écran 2020-09-18 à 15 10 36](https://user-images.githubusercontent.com/16019289/93601315-4f243a00-f9c1-11ea-86fb-f41bf942c08a.png)
Thanks!

**Comment by passio777x** [comment]
<img width="1498" alt="Capture d’écran 2020-09-18 à 15 25 41" src="https://user-images.githubusercontent.com/43704805/93602699-43d20e00-f9c3-11ea-852e-548bb07b0acc.png">
Thank you very much. I don't know why only this value changed in my DB, i'll modify them. Thank thank !

**Comment by passio777x** [comment]
Hi, I would like to understand why the out of stock colum value go back to 0 when my product are out of stock again... ?
