### ISSUE TITLE
Slow frontend with cache enabled

### ISSUE THREAD

**Issue by rederijker** [PrestaShop/PrestaShop#21077]
#### Describe the bug

Enable Memecache/memecached/apc cache slow down frontend

#### Expected behavior

Best performance of frontend

#### Steps to Reproduce

1. Go to ' Adv. Parameters'
2. Click on 'Performance.'
3. Scroll down to 'Cache'
4. Enable it
5. Choose cache
6. Set server ip ecc.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP Version: 7.2.33
* Memory limit: 512M
* Maximum execution time: 1800
* Max. Size of files to upload: 256M
Required parameters: OK
Optional parameters: OK

**Comment by sarahdib** [comment]
Hello @Cricchio 

In order to see the difference before the cache activation and after.
Could you send us more technical detail like 
- CPU Before/After
- RAM Before/After

Thank you!

**Comment by rederijker** [comment]
Sure!
### Before
![before](https://user-images.githubusercontent.com/67266943/93751836-03aa9f80-fbfe-11ea-9acd-b7e356e4cd99.png)
### During
![during-enable-cache](https://user-images.githubusercontent.com/67266943/93751840-04dbcc80-fbfe-11ea-8d45-8a505c4a65d2.png)
### Cache enabled
![cache-enabled](https://user-images.githubusercontent.com/67266943/93751839-04433600-fbfe-11ea-8c8e-8d4f88422c71.png)

**Comment by elrosi** [comment]
The speed of Prestashop is bad. For example, analysis via Google PageSpeed is a disaster especially for the mobile version.

**Comment by rederijker** [comment]
yes that's true, but the ttfb is really high. I tried another site on the same server and it doesn't have this performance. 
Category pages are the slowest. I also decreased the number of products per page, but nothing

**Comment by rederijker** [comment]
leave profiler debug
![profiling-1](https://user-images.githubusercontent.com/67266943/93769797-a45b8800-fc1b-11ea-87c1-315ec8587b79.png)

**Comment by waschier-design** [comment]
Thinking of pagespeed the actual version of prestashop is not very fast. 
Desktop is not very good. But mobile is a totally performance desaster.
You need a lot of work to get good speed results.

I think this should be one of the most important things to work on the next version of PrestaShop.

**Comment by rederijker** [comment]
@waschier-design I agree with you.

**Comment by khouloudbelguith** [comment]
Hi all!

We have an Epic about FO performance reported here: https://github.com/PrestaShop/PrestaShop/issues/19689
@Cricchio, can we close this ticket as it will be fixed in the last ticket?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Cricchio,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
