### ISSUE TITLE
BO 1.7.6.7 Tax Rules missing "TAX" field

### ISSUE THREAD

**Issue by toniGrabulosa** [PrestaShop/PrestaShop#21087]
Hi everyone,

I'm experiencing an issue related to Tax Rules section.

When I want to edit or add a new rule, everything is quite 'ok' but I cannot specify the TAX, because the field is missing. 

Check out my screenshot:

![image](https://user-images.githubusercontent.com/71640433/93757942-dcf16680-fc07-11ea-8957-6242b65c5ca5.png)

As you can see under "Comportamiento" (in english that field is called BEHAVIOR), it should appear "Tax" field (or IMPUESTOS in spanish).

Is that a bug, or am I missing something?

**Comment by sarahdib** [comment]
Hello @toniToniDev,

Unfortunately I couldn't reproduce the issue. 

<img width="1280" alt="Capture d’écran 2020-09-21 à 15 19 46" src="https://user-images.githubusercontent.com/3034677/93771565-fac9c600-fc1d-11ea-88e3-4440397e7b2c.png">

I also try with the 1.7.7.0 BETA and the field is display.

Did you update your pretashop to 1.7.6.7 or this is a new installation ?

Thank you!

**Comment by toniGrabulosa** [comment]
It's a new installation... and I don't understand why is not appearing... :-(

**Comment by toniGrabulosa** [comment]
That missing field issue could be something related to DataBase?¿

This project is based on a new PS installation, but I've hard-copied and replaced all product related DB tables and /img folder in order to get all my products imported from another PS.

**Comment by HartLarsson** [comment]
Have you verified to have PHP 7.2 version?

**Comment by toniGrabulosa** [comment]
Hey! Yes php 7.2! :-)

Actually I've solved it. It was something related to DB. Because.... that same installation I've pointed to another DB (a backup restored as an independent DB)... and the field was there again. 

Finally with that backup I hard-merged product related tables, and attributes and features and so on.... and I've got restored my last weeks work.

I'll close this issue, but.... anyway is something really strange and rare.

If you are courious about the issue, you can get in touch with me and I'll give you all the details, what tables I was hard-copying, etc...
