### ISSUE TITLE
Preview Product changes products in Mulit Store configuration

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#21098]
#### Describe the bug

If you have a multi store configuration (in our case a B2C, shop 1 and B2B shop 2) and you click on preview product on the product page when "all shops" is selected it screws up the product for shop 2. It changes the price to the price of shop 1 and it looses the default category. 

#### Expected behavior

Open the product in the in shop 1 and don't save / change anything

#### Steps to Reproduce

Create a multi store environment with shop dedicated categories and a product with different categories and prices per shop.
Set presta to all shops
Open the product, click on preview product
an error is thrown
change to shop 2 and see what is wrong

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @sickboards 

Could you send us a screenshot of the error displayed ?

Thank you

**Comment by khouloudbelguith** [comment]
Hi @sickboards,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

THanks!

**Comment by sickboards** [comment]
I can't seem to reproduce, but why is the product updated when you press preview, that seems to be unwanted behavior.
I will try to find a product that causes the error
