### ISSUE TITLE
Left admin panel isn't scroll able - on first tier of menu.

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#21095]
#### Describe the bug

From first tier of left admin panel I don't have scrollable panel and can't see full list of items.

#### Expected behavior

I want to the same happened as is right now when I pickup anything from submenu - second tier on left admin panel. We can see scroll bar on right side left admin panel.

#### Steps to Reproduce

1. Go to admin panel
2. Click on Advanced
3. Scroll down to '....' yyy you can't.

**Screenshots**

![image](https://user-images.githubusercontent.com/42643563/93809277-637c6700-fc4d-11ea-96b5-1c3cb4845537.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33-FPM

**Comment by SimonGrn** [comment]
Hello,
Did you try to click on the "Stop the onboarding" button ?

**Comment by LocalHeroPro** [comment]
I don't want to close that dialog.

**Comment by khouloudbelguith** [comment]
Hi @LocalHeroPro,

Thanks for your report.
The onboarding navbar is displayed, you need to stop the OnBording, to see all the main menu.
It could be a good improvement, ping @PrestaShop/product-team what do you think about this?

Thanks!

**Comment by MatShir** [comment]
Hi @khouloudbelguith,
It seems to be more like a bug, when I test on 1.7.6.8 I have a scroll bar on the left menu but it is not taking into account the tutorial.

**Comment by SimonGrn** [comment]
This is definitely a bug
