### ISSUE TITLE
Update delivery cost and taxe prices when changing the address

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#21099]
#### Describe the bug

When an address is edited in an Order, it won't update the shipping cost, taxes rules and the cart rules

#### Expected behavior

When an address is edited, the shipping cost, taxes rules and the cart rules are updated in an Order

#### Steps

I found a new issue following these steps: (All carriers are enabled & the United States is enabled)
1. In the FO you are logged with "John Doe"
2. Add the product demo_6 "The best is yet to come' Framed poster" to the cart, 
3. In the Address Step select "My address (Miami)"
4. In the Shipping Adress, select My light carrier = €2.00 tax incl. 
5. Continue checkout
6. In the BO > View the last order created
7. Add a new discount Free shipping
![image](https://user-images.githubusercontent.com/16067358/93324017-a2598980-f815-11ea-8b68-d015313b747b.png)
8. For shipping Address => select "Mon addressed(France)"
9. For invoice Address => select "Mon address(France)"

The Shipping well updated but `Discounts`, `Value discount`, and `Total` are incorrect
See error
![image](https://user-images.githubusercontent.com/16067358/93324287-f82e3180-f815-11ea-947a-0e8e2fc48654.png)

@jolelievre @PrestaShop/product-team this issue is reproduced with PS1767
![image](https://user-images.githubusercontent.com/16067358/93326485-28c39a80-f819-11ea-9190-d0423cc0508d.png)

>However maybe it is not exactly expected and we want the tax rate of the products to be updated when we change the address

I have a strange behavior about Product prices following these steps:
1. In the FO you are logged with "John Doe"
2. Add the product demo_6 "The best is yet to come' Framed poster" to the cart, 
3. In the Address Step select "My address (Miami)"
4. In the Shipping Adress, select My light carrier = €2.00 tax incl. 
5. Continue checkout
6. In the BO > View the last order created
7. Add a new discount Free shipping
8. For shipping Address => select "Mon addressed(France)"
9. For invoice Address => select "Mon address(France)"
![image](https://user-images.githubusercontent.com/16067358/93324759-9c17dd00-f816-11ea-9962-4a9dd77ed213.png)
10. **Delete the voucher**
![image](https://user-images.githubusercontent.com/16067358/93324838-b5b92480-f816-11ea-9a2e-64523e4a3e90.png)
@jolelievre this issue not reproduced with PS1767
![image](https://user-images.githubusercontent.com/16067358/93326547-40028800-f819-11ea-8e47-2c033f0b2e04.png)

Thanks!

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/20903#issuecomment-691182842_

**Comment by Progi1984** [comment]
Fixed by #20903
