### ISSUE TITLE
Cart does not exist after payment

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#21102]
#### Describe the bug

A few times everyday, we have customers who are able to pay for orders, but for whom orders are not actually created.

**This is going to be a difficult bug to identify as I have not been able to determine the steps to recreate it.**

#### Expected behavior

Customer should go to order confirmation page and order should be created after payment

#### Steps to Reproduce

1. Checkout your basket
1. Pay via bank/credit card
1. Sometimes, you are returned to the payment method section of the checkout

When/why/in what case you are returned to checkout (rather than confirmation) I do not know.

I know that this happens because the Cart cannot be found when returning from the payment gateway and thus an order cannot be created.

The logic (of our payment modue) relies on finding the appropriate Cart from the Cart ID that exists in the IPN (return URL from payment gateway). Thanks to logging in our module, we can see that often a Cart cannot be found for the given ID.

**So why is there a Cart ID if the Cart does not exist? Does the Cart get deleted?**

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
* Payment module: E Transactions by Credit Agricole v3.0.17 (https://github.com/E-Transactions-CA/CMS-ETR-Prestashop-1.5.x-1.6.x-1.7.x)

I am posting this hoping that someone can share some information that can help us resolve this mystery!

**Comment by sarahdib** [comment]
Hello,

It seems that your issue is not a PrestaShop core bug but most likely a module problem. Please contact the developper of the payment module.

Thank you!

**Comment by jonpontet** [comment]
@sarahdib it doesn't look that way to me but I will contact the developer and we will see!
