### ISSUE TITLE
Remove the "menu" tab in the BO menu and display an "access denied" message when trying to access to the AdminTabs controller

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#21107]
For the history, this page was present in 1.6 and allowed to add, edit, delete, activate / deactivate menus and reorganize them thanks to the position column.

![capture d'écran_2791](https://user-images.githubusercontent.com/13449658/93895714-6c724480-fcf0-11ea-8527-544737685059.png)

This page was deleted in 1.7.0 because merchants were removing menus and then didn't know how to re-add them because don't know how to find th the controller name.

This page reappeared in 1.7.8 following [the issue](https://github.com/PrestaShop/PrestaShop/issues/15048) opened by @idnovate 
The issue was identified as a bug (instead this was the wanted behavior) and the PR associated has been merged without being validated by PrestaShop's product team.

For the reasons mentioned above and as we only received one request to redisplay this page since the start of 1.7.0, the PrestaShop product team has decided to not restore this page in 1.7.8

The behavior in 1.7.8 should be the same as in 1.7.x:
- No "menu" tab in the BO menu 
- An "access denied" message when trying to access directly to the URL controller=AdminTabs 

We shouldn't delete the code and keep the controller in order to enable this page through a toggle for advanced users later (can't do it know as it's a new feature and 1.7.8 is feature frozen)

**Comment by LouiseBonnard** [comment]
Issue almost ready! I've just added the _waiting for dev_ label since @matks' review is requested on https://github.com/PrestaShop/prestashop-specs/pull/135. Once approved, we will be able to move this issue to the backlog.

**Comment by idnovate** [comment]
> * add a message in the code to indicate to the developers how to access to this page if they want to

How will we be able to access this page?

**Comment by matks** [comment]
> > * add a message in the code to indicate to the developers how to access to this page if they want to
> 
> How will we be able to access this page?

Hello, as you can see for PR https://github.com/PrestaShop/PrestaShop/pull/24330 developers who are experienced and know how to use this page will need to create the needed database entries in tabs and roles to access it. We dont remove code, we removed the database items that are needed to access the page. Inserting the needed database items will allow you to access it again 😉  .

**Comment by Progi1984** [comment]
Fixed in #24330 by @sowbiba
