### ISSUE TITLE
Mail themes cache

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#21104]
#### Describe the bug

When editing a mail theme the recently made edits won't be visible until a cache clear.
Even when cache is globally disabled in the store, and after regenerating mails, you still need to refresh cache.

#### Expected behavior

When cache is disabled have the theme edits after regenerating the templates visible.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by sarahdib** [comment]
@PrestaShop/product-team Could you check this ? 

The cache option seems to be apply only to the template not email.

**Comment by LouiseBonnard** [comment]
@sarahdib, is it not a bug?

**Comment by sarahdib** [comment]
@LouiseBonnard no it's an improvement I think

**Comment by NKoonen** [comment]
> @LouiseBonnard no it's an improvement I think

If people disable cache, you can't expect people to still clear cache.
Because if the cache was really disabled, there is nothing to clear.

**Comment by NKoonen** [comment]
Any news on this issue?
It's weird, when all of Prestahop's cache is disabled it still uses (smarty) cache.

**Comment by MatShir** [comment]
It is weird, could @PrestaShop/prestashop-core-developers have a look ? 😄 
It should be directly visible, WDYT ?

**Comment by PierreRambaud** [comment]
I agree, if we disable the Cache, we should have no cache, it's a bug, not an improvement :thinking:

**Comment by hibatallahAouadni** [comment]
Closing this issue in favor of #22968 (more details)

**Comment by hibatallahAouadni** [comment]
Duplicate of #22968
