### ISSUE TITLE
Slow Categories Page with a lot of Categories

### ISSUE THREAD

**Issue by maestrobo** [PrestaShop/PrestaShop#21106]
#### Describe the bug

**The Categories Page is getting very SLOW because of the TOP CATEGORY query that is calculated.**
I had to disable the "top_category" function of the page.
It is called in controllers/admin/AdminStatsController.php 
The Query that is the trouble is in getBestCategory:

    public static function getBestCategory($date_from, $date_to)
    {
        return Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
            '
		SELECT ca.`id_category`
		FROM `' . _DB_PREFIX_ . 'category` ca
		LEFT JOIN `' . _DB_PREFIX_ . 'category_product` capr ON ca.`id_category` = capr.`id_category`
		LEFT JOIN (
			SELECT pr.`id_product`, t.`totalPriceSold`
			FROM `' . _DB_PREFIX_ . 'product` pr
			LEFT JOIN (
				SELECT pr.`id_product`,
					IFNULL(SUM(cp.`product_quantity`), 0) AS totalQuantitySold,
					IFNULL(SUM(cp.`product_price` * cp.`product_quantity`), 0) / o.conversion_rate AS totalPriceSold
				FROM `' . _DB_PREFIX_ . 'product` pr
				LEFT OUTER JOIN `' . _DB_PREFIX_ . 'order_detail` cp ON pr.`id_product` = cp.`product_id`
				LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.`id_order` = cp.`id_order`
				WHERE o.invoice_date BETWEEN "' . pSQL($date_from) . ' 00:00:00" AND "' . pSQL($date_to) . ' 23:59:59"
				GROUP BY pr.`id_product`
			) t ON t.`id_product` = pr.`id_product`
		) t	ON t.`id_product` = capr.`id_product`
		WHERE ca.`level_depth` > 1
		GROUP BY ca.`id_category`
		ORDER BY SUM(t.`totalPriceSold`) DESC'
        );
    }

#### Expected behavior

To be fast.

#### Steps to Reproduce

My config:
Create at least 400 categories with level depth to 5-6.
With 2000 products in differents categories.

1. Go to CATEGORIES PAGE
2. NAVIGATE INSIDE THE CATEGORIES.

Either make it an OPTION that can be turn on/off or remove it.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by sarahdib** [comment]
Hello @maestrobo 

Prestashop 1.7.6.7 is not compatible with php version 7.3 https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements
You should downgrade your php version.

Could you send us some technical information like CPU and RAM ? 

Thank you!

**Comment by maestrobo** [comment]
model name : Intel(R) Xeon(R) CPU E7-8867 v3 @ 2.50GHz
cpu MHz   : 2493.990
8 GB
Apache 
Linux #1 SMP Mon Jan 8 10:22:35 CET 2018 x86_64 
MYSQL Version: 5.7.29-log 
PHP 7.3.18

**Comment by maestrobo** [comment]
It is load testing. I think you need to test how prestashop reacts with lot of products and categories. This issue seems to date back to PS 1.5, 1.6 and 1.7.

**Comment by khouloudbelguith** [comment]
Hi @maestrobo,

Is it your issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/13698?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @maestrobo,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
