### ISSUE TITLE
"You are not allowed to install modules" error while installing

### ISSUE THREAD

**Issue by elbek** [PrestaShop/PrestaShop#21109]
#### Describe the bug
While installing almost at the end I get following error:

```
An error occurred during installation...

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

    1: You are not allowed to install modules.
```
It provides no logs, no meaningful message. I am using this version prestashop_1.7.6.7.zip. 
php --version
PHP 7.4.3
It should at least give some stack trace. Or tell where the full log is. I cannot find installation logs anywhere in the system. 

#### Expected behavior

Installation should complete correctly. 

#### Steps to Reproduce
Download the above version and try to install it. 

**Screenshots**
it was asked [here](https://www.prestashop.com/forums/topic/1027374-1-you-are-not-allowed-to-install-modules-error/)

None answered. I have the same screenshot, happened at the same percentage. 

#### Additional information
Versions are provided above

**Comment by SimonGrn** [comment]
Hello @elbek ,
PrestaShop 1.7.6 is not compatible with PHP 7.4. You can see the requirements [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).
Please downgrade your PHP version and try again.

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @elbek,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
