### ISSUE TITLE
Cannot add root categories

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#21118]
#### Describe the bug

When adding mutistores, we need to add root categories - it is not possible to do that. 

I have checked v1.7.6.5 and v1.7.6.7 and do not find it is possible.

Also, the link "please click here" to define a new root category does not work:
[admin]/index.php/sell/catalog/categories?_token=[token]&addcategoryroot

If I make a mistake somewhere, you should add some documentation!

#### Expected behavior

On the Categories page we should be able to add new root categories - maybe depends on multistore being active.

#### Steps to Reproduce

The link "please click here" to define a new root category does not work when creating a new store:
[admin]/index.php/sell/catalog/categories?_token=[token]&addcategoryroot

#### Additional information

* PrestaShop version: v1.7.6.5 and v1.7.6.7
* PHP version: 7.2

**Comment by jonpontet** [comment]
Also worth noting is this error I get when trying to create a new store with a different root category (I had to add it directly to the DB). 
The error says I need to select a root category - but you can see that I have done this!
![image](https://user-images.githubusercontent.com/20968408/94021611-7eb5b680-fdb4-11ea-8fcc-c15941b4ea42.png)

**Comment by jonpontet** [comment]
Update ! Something has changed and I now have the add root category button

I just modified and saved a child category (of the single root category) so that could have been why

**Comment by jonpontet** [comment]
Unfortunately, I _can_ create the root category, but **it is not visible afterwards**

**Comment by florine2623** [comment]
Hi @jonpontet ,
I can't reproduce the issue.
I can add a root category from the link provided (_please click here_ link).

In Catalog > Category, you can choose to add a new root category and it will display in the dropdown menu in the multistore options.
![Capture d’écran 2020-09-24 à 10 27 44](https://user-images.githubusercontent.com/16019289/94120634-a5292f80-fe50-11ea-87be-bc7f889c3b07.png)
![Capture d’écran 2020-09-24 à 10 27 57](https://user-images.githubusercontent.com/16019289/94120642-a6f2f300-fe50-11ea-9ee4-1601aa1feb45.png)

Make sure the Root Category Display option is enabled :
![Capture d’écran 2020-09-24 à 10 29 23](https://user-images.githubusercontent.com/16019289/94120794-d570ce00-fe50-11ea-8323-1609de01104b.png)

Thanks!

**Comment by sirius82** [comment]
Hi,
I have the same problem with a new PS8.2. The "add a root category" button doesn't display. The link provided (_please click here_ link) opens the classic category page, not the root category page and without the button.
If I choose to save the new store in the default group,  I have only "Home" in the select "choose a root category". And if I save it, I receive an error : You must choose a root category. It's the same if I create a new shop group.
