### ISSUE TITLE
Wrong weight calculation on carrier selection

### ISSUE THREAD

**Issue by julienbruitte** [PrestaShop/PrestaShop#21111]
#### Describe the bug

When using warehouses for sending products, the list of carrier is wrong.

In fact, in the getPackageList function, there is a problem when calling : 

` $product['carrier_list'] = array_replace($product['carrier_list'], Carrier::getAvailableCarrierList(new Product($product['id_product']), $id_war, $product['id_address_delivery'], null, $this));`

This method will send the total weight for the cart to get the available carriers. However, as this is managed by different warehouses, it should only compute the weight for the current warehouse.

As the weight is computed on the total cart, the value will be greater than the package one, leading to carrier being disabled.

#### Expected behavior
Actual : 
3 products in the cart.
2 products from WH1 with a total weight of 1kg.
1 product from WH2 with a total weight of 1000kg.

Carrier with weight restriction for WH1 to max 2kg should be displayed but is not.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by SimonGrn** [comment]
Hello @julienbruitte 
there is no warehouse system in 1.7 anymore, how are you managing this exactly ? Is this through a module ?

BTW, PrestaShop 1.7.6.4 is not compatible with PHP 7.3. You can find the requirements [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/). Please downgrade your PHP version.

**Comment by khouloudbelguith** [comment]
Hi @julienbruitte,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

THanks!
