### ISSUE TITLE
Dashboard trends module not working PS 1.7.6.7

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#21129]
Hi after updating to PS 1.7.6.7 the sale chart stop showing sales

PS 1.7.6.7
PHP 7.2.33
Ps statistics module v. 2.0.3
Ps sale and order STT v. 2.0.0 

![image](https://user-images.githubusercontent.com/46203943/94055640-a6584f00-fdb3-11ea-80fc-00cd09bda704.png)

![image](https://user-images.githubusercontent.com/46203943/94055936-f9ca9d00-fdb3-11ea-8565-d29a0a246fc8.png)

**Comment by florine2623** [comment]
Hi @msaustral ,
I couldn't reproduce the issue in an upgraded shop from PS 1.7.6.2 to PS 1.7.6.7.
After I make a sale, the dashboard updates automatically.
![Capture d’écran 2020-09-24 à 12 07 42](https://user-images.githubusercontent.com/16019289/94131732-9184c580-fe5e-11ea-9cc7-431766d8b276.png)
![Capture d’écran 2020-09-24 à 12 07 36](https://user-images.githubusercontent.com/16019289/94131741-93e71f80-fe5e-11ea-8296-4492a8071e57.png)

Make sure the range of dates is on the right period :
![Capture d’écran 2020-09-24 à 12 08 10](https://user-images.githubusercontent.com/16019289/94131786-a82b1c80-fe5e-11ea-80fc-87362eefc8e6.png)

Thanks!

**Comment by msaustral** [comment]
Hi Florine, sorry, but if you could not reproduced it,  does it mean that it work?, there are many people with the same error, I found many chat with no solution and still it does not work for me.

don't you think a litter help will be better than just close the ticket??

The statistic is seeing the orders but the chart is not showing it!, we have no made any change, just update the PS
