### ISSUE TITLE
Problem displaying basket discounts

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#21127]
#### Description of the bug

When creating two discount rules, one applies to a category that takes into account discounted products. The other applies to the entire basket but not to discounted products.
 The value displayed in the basket for the first discount rule is not correct.

See Screenshot

![image](https://user-images.githubusercontent.com/4932192/94030478-25eb1b80-fdbe-11ea-8c25-d7d0c778f55a.png)

#### Expected behavior

Here we have :

-The 5% discount that applies to discounted products.
-The 20% discount that applies to unsold products.

With this cart : 
![image](https://user-images.githubusercontent.com/4932192/94030841-8ed29380-fdbe-11ea-8ed3-8c65770c6a09.png)

We may have : 

The 5% discount for the €34.46 Hummingbird printed sweater => 1.723€

![image](https://user-images.githubusercontent.com/4932192/94031714-7b73f800-fdbf-11ea-97f2-3b578769b6ed.png)

It is correctly displayed

But,

For the 20% discount for €22.68 Hummingbird cushion => 4.536€

it doesn't display properly 
![image](https://user-images.githubusercontent.com/4932192/94031901-aa8a6980-fdbf-11ea-9f2d-6e472fb4f500.png)

The displayed reduction is not correct

The final price is right it is the display of this discount that is not correct

Explain what you expected to happen instead.

It is expected that the displayed discount will be 4.536€.

#### Steps to Reproduce

I)

1.Create a new Category for products on sale
2.Put a product on sale in this category (mine is Hummingbird printed sweater)

II)

1. Create a new Cart Rule

Informations : 
![image](https://user-images.githubusercontent.com/4932192/94032989-cfcba780-fdc0-11ea-8d21-ab7a1e7f743b.png)

Conditions : 
![image](https://user-images.githubusercontent.com/4932192/94033220-06a1bd80-fdc1-11ea-9afb-df515ceaf64e.png)

Actions : 

![image](https://user-images.githubusercontent.com/4932192/94033312-20db9b80-fdc1-11ea-95b6-996d64caf2b2.png)

2. Create the second cart rule 

Informations : 
![image](https://user-images.githubusercontent.com/4932192/94033531-584a4800-fdc1-11ea-8ed0-6dedaf2fbf00.png)

Conditions : 
![image](https://user-images.githubusercontent.com/4932192/94033650-77e17080-fdc1-11ea-8344-2377ca956575.png)

Actions : 
![image](https://user-images.githubusercontent.com/4932192/94033726-8cbe0400-fdc1-11ea-87e3-e10c72d24503.png)

After

Add one discounted and one not discounted product to the basket.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @202-ecommerce ,
I managed to reproduce the issue in PS 1.7.7.0 and PS 1.7.8.
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by marionf** [comment]
Hello @florine2623 @202-ecommerce 

Your issue seems to be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19090
Could you please take a look at this issue and confirm if the issue is the same ?

Thank you !

**Comment by clotairer** [comment]
@florine2623 no PR nor solution for now.
Could you please tell us if it can be included on 1.7.7.0-RC ?
If we work on this issue, we have to schedule it. But if you include this in 1.7.8 we are not in a hurry.

Thank you !

**Comment by clotairer** [comment]
Yeah I confirm ! It looks like the same bug...

**Comment by marionf** [comment]
@clotaire202 the issue https://github.com/PrestaShop/PrestaShop/issues/19090 is planned for the 1.7.8
The 1.7.7 is frozen since a while and we are going to release the RC1 in few weeks: https://github.com/PrestaShop/PrestaShop/issues/18647, stay tuned !

**Comment by marionf** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19090
