### ISSUE TITLE
Category Tree links: When "home" is category root, "Home" link directs to www.mysite.com/2-home

### ISSUE THREAD

**Issue by Bewitching-Co** [PrestaShop/PrestaShop#21128]
#### Describe the bug

Category Tree links module: When Home is selected as category root, the "Home" link in FO directs to www.MYSITE.com/2-home. There is no "2-home" page and it delivers the 404 error page.
Home link in breadcrumbs works properly.
Inspect shows the following: 
`[<ul class="category-top-menu">
    <li><a class="text-uppercase h6" href="https://www.MYWEBSITE.com/2-home">Home</a></li>
    <li>)`
SEO preview shows the issue, as the homepage URL "2-undefined"

#### Expected behavior

When I click on HOME in the category tree links, I expect it to take me to: www/MYSITE.com, my homepage.

#### Steps to Reproduce

1. Go to Category tree links.
2. Select home as category root.
3. Go to FO and click home on category tree.
4. Tries to direct to www.MYSITE.com/2-home Page "2-home" is non-existent and delivers 404 error page
**Screenshots**
Settings in Category Tree Links:
![Category tree links home setting](https://user-images.githubusercontent.com/71606342/94046614-8bc3ad00-fd96-11ea-8741-1f140c6cb193.jpg)

Image below show what hovering over home link directs to in lower left corner:
![Tree link home url](https://user-images.githubusercontent.com/71606342/94046827-cf1e1b80-fd96-11ea-9c2e-77d26c871848.jpg)

SEO preview shows "undefined" home page:
![SEO preview](https://user-images.githubusercontent.com/71606342/94046919-ec52ea00-fd96-11ea-822e-0d32c6697e58.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.24

**Comment by florine2623** [comment]
Hi @Bewitching-Co ,
I can't reproduce your issue in PS 1.7.6.7 with the same configuration of Category Tree module.
The breadcrumb redirects to your homepage.
The Home link redirect to the products in your home category.
![Capture d’écran 2020-09-24 à 10 47 19](https://user-images.githubusercontent.com/16019289/94122960-7a8ca600-fe53-11ea-9b49-407001a78717.png)

You can also configure the Friendly URL when you edit the category :
![Capture d’écran 2020-09-24 à 10 49 32](https://user-images.githubusercontent.com/16019289/94123114-ac057180-fe53-11ea-8e30-4863add2b856.png)

Thanks!
