### ISSUE TITLE
Fatal Error during installation process 

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21134]
#### Describe the bug

Fatal Error during installation process 

#### Expected behavior

The trans() function should in translator not InstallControllerHttpSystem.

#### Steps to Reproduce

1. Download [develop branch](https://github.com/PrestaShop/PrestaShop) 
2. To get this message you must have at least one of the required extension disabled (Ex.: Disable **Intl** or **CURL**) 
3. Try to install

**Screenshots**

![image](https://user-images.githubusercontent.com/16455155/92786078-3bb51580-f3a8-11ea-8d20-0ce13843165b.png)

#### Additional information

* PrestaShop version: develop, 1.7.7.x
* PHP version: N/A
* By : @mushroot 
* PR : https://github.com/PrestaShop/PrestaShop/pull/20201

**Comment by florine2623** [comment]
Hi @PululuK ,
I couldn't reproduce the issue.
I dowloaded the develop zip, I made composer install & make assets and successfully installed my new shop.
![Capture d’écran 2020-09-24 à 11 35 24](https://user-images.githubusercontent.com/16019289/94128174-17ead880-fe5a-11ea-87af-f2a73fe30e4a.png)
![Capture d’écran 2020-09-24 à 11 35 29](https://user-images.githubusercontent.com/16019289/94128181-19b49c00-fe5a-11ea-852d-e27c0095f661.png)

Is there anything special about your server config ?
Thanks!

**Comment by PululuK** [comment]
> Hi @PululuK ,
> I couldn't reproduce the issue.
> I dowloaded the develop zip, I made composer install & make assets and successfully installed my new shop.
> Is there anything special about your server config ?
> Thanks!


@florine2623  I'm very sorry !
I just updated, see step 2 :
_To get this message you must have at least one of the required extension disabled (Ex.: Disable **Intl** or **CURL**)_ 

ping @SimonGrn

**Comment by SimonGrn** [comment]
Thank you @PululuK I'll try right away !

**Comment by SimonGrn** [comment]
I reproduce with a fresh install of `develop` & `1.7.7.x` and after deactivating `curl` and `intl`.
![image](https://user-images.githubusercontent.com/49909275/94240911-3d3c1d00-ff14-11ea-9b84-8ed6fef65133.png)

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

As discussed with @SimonGrn, it is ok with 1767.
![image](https://user-images.githubusercontent.com/16067358/94242302-1ed72100-ff16-11ea-826d-d5d6d8733efa.png)
It is a regression.

Thanks!

**Comment by matks** [comment]
@PululuK very nice catch

**Comment by PierreRambaud** [comment]
Original pull request updated: #20201

**Comment by marionf** [comment]
@jolelievre As it's a minor regression of the 1.7.7 it should be fixed in 1.7.7.X
I move it in 1.7.7.x kanban

**Comment by PierreRambaud** [comment]
> @jolelievre As it's a minor regression of the 1.7.7 it should be fixed in 1.7.7.X
> I move it in 1.7.7.x kanban

If your server is badly configured, you're not able to install PrestaShop without having any error message on what the problem is :( , it is really minor :thinking:

**Comment by PululuK** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/20201
