### ISSUE TITLE
Can't integrate gmail on prestashop 1.4.6.2

### ISSUE THREAD

**Issue by dutraveller** [PrestaShop/PrestaShop#21133]
Hello, I've tried everything that I've searched on internet and still can't get working a test email on my admin panel to use gmail.

These are the errors:

The SMTP connection failed to start [tls://smtp.gmail.com:587]: fsockopen returned Error Number 0 and Error String ''
[ssl://smtp.gmail.com:465]: fsockopen returned Error Number 110 and Error String 'Connection timed out'

I've added the gmail settings:

smtp server: smtp.gmail.com
user: xxxx@gmail.com
pass: xxxxx

Tried encription SSL and TLS with ports 587 and 465.

Still doesn't work. Can anyone help me here??

**Comment by florine2623** [comment]
Hi @dutraveller ,

PrestaShop 1.4 has reached end of life and is no longer officially maintained.
You can contact an [agency](https://www.prestashop.com/en/agencies), or the [support team](https://addons.prestashop.com/en/388-support) if you want to upgrade your shop.

Thank you
