### ISSUE TITLE
Faceted search module breaks sorting by price when using multiple customer groups

### ISSUE THREAD

**Issue by ioweb-gr** [PrestaShop/PrestaShop#21137]
#### Describe the bug

We have an eshop with multiple specific prices per group. While the faceted search is enabled, price sorting fails giving inconsistent results because it's mixing group prices.

#### Expected behavior

Products are sorted based on the actual price the user is seeing. 

#### Steps to Reproduce

Create multiple customer groups
Create 2 products 
Create multiple specific prices for a product's combinations. 

Let's say 
Product1 = P1 has price of 1.5
Product2 = P2 has price of 1.6
Group1 = G1 = General
Group2  = G2 = Other Group
Customer1 = C1 and has a group of general

One combination of P2 has a price of 1.4 for group G1 and a price of 1.6 for group G2. 

The faceted search module is only storing min price and max price but doesn't take into account the customer group. 
This will effectively set min_price = 1.4 for P2 in the layered_price_index table and min_price = 1.5 for P1. 

Therefore when C1 sorts the products by prices will see 
P2 < P1  because 1.4 < 1.5 but for the current user the price of the product will be 1.6 < 1.5 which is an error.

**Screenshots**

![image](https://user-images.githubusercontent.com/20220341/94143823-08c75300-fe79-11ea-916b-fea0afd4a385.png)

![image](https://user-images.githubusercontent.com/20220341/94143916-25fc2180-fe79-11ea-8a67-d0ba5c6bbc5a.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2
* Faceted Search Module Version: 3.6.0

**Comment by florine2623** [comment]
Hi @ioweb-gr ,
I can't reproduce your issue with PS 1.7.5.2, faceted_search v2.2.0 
![Capture d’écran 2020-09-24 à 17 00 59](https://user-images.githubusercontent.com/16019289/94165103-25b85200-fe8a-11ea-8701-077858aa2a84.png)
You can upload faceted_search v2.2.0 to your PS 1.7.5.2 :
[ps_facetedsearch-2.2.0.zip](https://github.com/PrestaShop/PrestaShop/files/5277115/ps_facetedsearch-2.2.0.zip)

I've tried also on the next PS version 1.7.7.0, faceted_search 3.5.0 too, it works :
![Capture d’écran 2020-09-24 à 17 18 15](https://user-images.githubusercontent.com/16019289/94165247-4da7b580-fe8a-11ea-8118-ea8f425ce0de.png)

For both versions, the products show up correctly with their prices low to high.
Thanks!

**Comment by ioweb-gr** [comment]
Please read up here it was successfully reproduced by others https://github.com/PrestaShop/PrestaShop/issues/19810#issuecomment-698363251 @florine2623
