### ISSUE TITLE
Ps_facetedsearch - Problem with ordering products and using the option "Show products from subcategories".

### ISSUE THREAD

**Issue by crv248** [PrestaShop/PrestaShop#21131]
#### Describe the bug

When the "Show products from subcategories" option is actived I tried to order the category products and when I'm in a parent category the order is wrong, then in a child category the order it's ok. I tried this [https://github.com/PrestaShop/PrestaShop/issues/15062](url) but doesn't works for me.

#### Steps to Reproduce

1. Module configuration
![image](https://user-images.githubusercontent.com/15896239/94118294-a3aa3800-fe4d-11ea-8a36-75dff2547d04.png)

2. Product configuration:
![image](https://user-images.githubusercontent.com/15896239/94118352-b91f6200-fe4d-11ea-8b7a-5270d06aa4ee.png)

3. Parent category ("Clothes") order:
![image](https://user-images.githubusercontent.com/15896239/94118425-d2c0a980-fe4d-11ea-94a0-7ef4e55fb695.png)

4. Parent category **wrong** result:
![image](https://user-images.githubusercontent.com/15896239/94118511-ed931e00-fe4d-11ea-8c08-7fd781582bd4.png)

5. Child category ("Men") order:
![image](https://user-images.githubusercontent.com/15896239/94118616-15828180-fe4e-11ea-8158-0dae60e6222a.png)

6. Chlid Category **correct** result:
![image](https://user-images.githubusercontent.com/15896239/94118740-3945c780-fe4e-11ea-8b62-22f18980a9c8.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1
* Module version: v3.5.0

**Comment by crv248** [comment]
Additional info:
I had a environment with the module version 3.4.0 and the Prestashop version 1.7.3.3 working correctly. I tried to use the 3.4 module version with the 1.7.6.7 and doesn't work.

**Comment by florine2623** [comment]
Hi @crv248 ,
The issue you mentioned #15062 has been fixed for PS 1.7.7.0
I have just done the tests in PS 1.7.7.0, with the same config in faceted_search v3.5.0 and and it works correctly :
In parent category :
![Capture d’écran 2020-09-25 à 11 03 00](https://user-images.githubusercontent.com/16019289/94248403-b6d90880-ff1e-11ea-9efd-7aaadff112b1.png)
![Capture d’écran 2020-09-25 à 11 02 49](https://user-images.githubusercontent.com/16019289/94248410-b9d3f900-ff1e-11ea-8c2a-b5757837732d.png)

In child category :
![Capture d’écran 2020-09-25 à 11 02 32](https://user-images.githubusercontent.com/16019289/94248419-be98ad00-ff1e-11ea-90b8-3660084ab7dc.png)
![Capture d’écran 2020-09-25 à 11 02 41](https://user-images.githubusercontent.com/16019289/94248425-c0fb0700-ff1e-11ea-907a-649007e0d9d1.png)

I suggest you to wait for the release of PS 1.7.7. and update your shop. In the meantime, if you have any questions you can contact the [support team](https://addons.prestashop.com/en/388-support) or any `https://www.prestashop.com/en/experts`.
Thanks!
