### ISSUE TITLE
Invalid SQL Statement During Update Of Table With Decimal Columns

### ISSUE THREAD

**Issue by fedetibaldo** [PrestaShop/PrestaShop#21132]
#### Describe the bug

When you run the suggested command `php bin/console prestashop:schema:update-without-foreign`, the ALTER queries produce invalid SQL statements for all those tables that have decimal values in them. With decimal values, I mean entity properties like the following:
```php
<?php
/**
 * @var float
 * 
 * @ORM\Column (name="a_decimal_column", type="decimal", precision=10, scale=6, nullable=true)
 */
private $aDecimalColumn;
```

When the tool runs the update query, this is what happens:
```
An exception occurred while executing 'ALTER TABLE table_name CHANGE a_decimal_column a_decimal_column NUMERIC(10 DEFAULT NULL , 6) DEFAULT NULL:                                   

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL   
  syntax; check the manual that corresponds to your MariaDB server version for the right  
  syntax to use near 'DEFAULT NULL , 6) DEFAULT NULL' at line 1
```
#### Expected behavior

It should work and produce valid SQL statements. In this case, `ALTER TABLE table_name CHANGE a_decimal_column a_decimal_column NUMERIC(10, 6) DEFAULT NULL`.

#### Steps to Reproduce

1. Create an entity with at least a decimal property
2. Update the schema (it works as expected during creation)
3. Do a small change to the entity (e.g. a different column name, from nullable to not nullable etc.)
4. Execute the update command
5. See the error

#### Additional information

The error lies in between lines 191 and 199 of the `PrestaShopBundle\Command\UpdateSchemaCommand` class file. In fact, if you comment this bit, everything works as expected.
```php
<?php
// line 191
if (preg_match('/DEFAULT/', $matches[0][$matchKey])) {
    $matches[0][$matchKey] =
        preg_replace('/DEFAULT (.+?)(,|$)/', 'DEFAULT ' .
            $oldDefaultValue . '$2' . ' ' . $extra, $matches[0][$matchKey]);
} else {
    $matches[0][$matchKey] =
        preg_replace('/(.+?)(,|$)/uis', '$1 DEFAULT ' .
            $oldDefaultValue . ' ' . $extra . '$2', $matches[0][$matchKey]);
}
```

* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* Symfony 3.4.26 (kernel: app, env: dev, debug: true)
* MariaDB 10.4.11

**Comment by florine2623** [comment]
Hi @fedetibaldo ,
Do you have a file example of the Entity you created ?
I will use it to make some tests.
Thanks!

**Comment by fedetibaldo** [comment]
Sure! As I said, it's any entity with at least a decimal property, but I'll provide a more complete example as soon as I get back to my work PC

**Comment by khouloudbelguith** [comment]
@fedetibaldo,

>but I'll provide a more complete example as soon as I get back to my work PC

Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @fedetibaldo,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
