### ISSUE TITLE
[BO] [Modules Manager] not able to upload a module 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21135]
#### Describe the bug

Uploading a module returns an error in console and we are unable to install it. 

#### Steps to Reproduce

1. Go to to FO, modules
2. add a module 
3. I t returns an error in console and an infinite charging icon

**Screenshots**

<img width="1113" alt="Capture d’écran 2020-09-24 à 11 12 20" src="https://user-images.githubusercontent.com/69145330/94125586-d147af00-fe56-11ea-9902-7c0c2fc30c93.png">

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by marionf** [comment]
Hello @ngodefroy 

Could you please indicate the duplicated issue ?

**Comment by SimonGrn** [comment]
Duplicate of #20852
