### ISSUE TITLE
Module upgrade broken

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#21140]
#### Describe the bug

Uploaded a new version of a module, the upgrade button showed in admin, I clicked on it, it did not upgrade the module, it is still showing the old version in the bo but the files are the new version.

#### Expected behavior

The module should be upgraded to the new version.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2.x

**Comment by florine2623** [comment]
Hi @Prestaworks ,
Which module are you trying to update ?
Thanks!

**Comment by Prestaworks** [comment]
at the time, it was the module for Amazon from addons. it updated in the xml files but not in the DB.
I have also experienced the same issue when I make a new release of a module on addons and have a new version on localhost, it dowloads an older version from addons instead of using the files on localhost.

**Comment by florine2623** [comment]
I don't have any issue when it comes to updating modules in the BO.

Regarding the module Amazon, you can contact the developer of the module through your Addons account if you have any issue. They will make sure to give you the updated version.
If you upload your latest module version to addons using the files on localhost, you will find the files from localhost in Addons.

If you are downloading the zip, you can install it like you install a new module.

If the upgrade is available from the module directly, you will see the Upgrade button.

If you have another issue, please contact the support team here or a partner agency to help you with that issue.
Thanks!

**Comment by Prestaworks** [comment]
Step 1, I have the wire payment module in my shop that needs an update from addons
![step1](https://user-images.githubusercontent.com/2902272/94252967-ec80f000-ff24-11ea-8fa0-23f8e5a77047.png)

I go in to the code and change the version of my local files to 2.2.4 (I simluate that I have made a new version of the module that I want to test on my local shop)
![step2](https://user-images.githubusercontent.com/2902272/94253050-091d2800-ff25-11ea-99ec-df718139d6bb.png)
the code says my local version is 2.2.4

I reload the upgrade page
![step3](https://user-images.githubusercontent.com/2902272/94253105-19350780-ff25-11ea-85e0-22dd47553814.png)
it still says the local version is the old version and the upgrade will go to the latest version on addons, ignoring my local files.

I click upgrade button
![step4](https://user-images.githubusercontent.com/2902272/94253172-3669d600-ff25-11ea-8825-9b6a4ccda80b.png)
The module is upgraded with success

![step5](https://user-images.githubusercontent.com/2902272/94253208-41246b00-ff25-11ea-8800-b84e88382e65.png)
All my localfiles (all my work) has now been replaced with version 2.1.0 from addons.

Module has been upgraded to 2.1.0
![step6](https://user-images.githubusercontent.com/2902272/94253292-6022fd00-ff25-11ea-901a-98cc9bc1e357.png)

and you say this is not a problem?

**Comment by Prestaworks** [comment]
@florine2623 
The example above is from PS 1.7.7.0

**Comment by Prestaworks** [comment]
@florine2623 can you confirm that it is expected behaviour that clicking the upgrade button will erase all local files?

**Comment by Prestaworks** [comment]
@khouloudbelguith can you ping florine so he looks at this and answer my question?

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks !

Done with a private message :+1:

**Comment by florine2623** [comment]
Hi @Prestaworks 
I couldn't reproduce your issue in PS 1.7.7.0.
The module that has to be updated, is updated correctly :
https://drive.google.com/file/d/1gocBakvUxzmMZh-4ydlSAsGl5uQ7L4mQ/view

When making any change to your module, if you want to keep the modifications after an upgrade, you need to put them in /override folder of your shop.

It is normal to not see your modifications done directly on the module files after an upgrade. They should be done in override folder.

**Comment by Prestaworks** [comment]
Hi @florine2623 
But the point of the issue is that I upload a newer module to the server than is available on addons
Prestashop 1.7.7.0 har version 1.0 of the module
Addons has version 1.1.0 of the module
I upload an unreleased version to the shop 1.2.0
I click upgrade, the 1.1.0 is downloaded from addons, overwriting the 1.2.0 version that is newer on the server.
Then after this I can upload 1.2.0 again and try again.

This is not how it has worked on 1.6 on 1.6 it started with looking at the local files and what version that was, if it was the highest version on the local files, it upgraded using the local files and only if addons had a newer version that was download.

It is a hugh difference and cause lots of issues for us that develops modules and maybe needs to make patch upgrades on local installations. 

Do you understand the issue?

**Comment by eternoendless** [comment]
If I got it right, you're trying to launch the upgrade process on a local module (to trigger the module's internal upgrade process for example). 

I don't think this is currently supported, [the Module Manager has a `$source` parameter](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/Core/Addon/Module/ModuleManager.php#L353) but it's the path to the zip archive, it's meant to replace the files.

Today you can trigger the upgrade from CLI using `bin/console prestashop:module upgrade somemodule` but it will retrieve it from Addons like the interface does. I think what you're asking for could be easily be implemented in the in this command using `prestashop.core.module.updater`. I think a simple parameter to trigger this behavior should suffice.

**Comment by Prestaworks** [comment]
@eternoendless yes I want it to work just like it did in 1.2 - 1.6
If the local version was higher than than the version in the db, the local version was used to upgrade and then it would check other sources like addons. It seems to do the reverse now, first it check addons agains the db and upgrade, if the db and addons are the same, then it will use the local files.
So it should just be a matter of reverse order.

**Comment by Prestaworks** [comment]
![Screenshot_2020-12-09 Meddelanden från moduler • KCO17](https://user-images.githubusercontent.com/2902272/101610594-c1c51480-3a08-11eb-900b-68d40d2f41e9.png)
This image shows an example where the upgrade tab gives me a "downgrade" of the module due to this issue.
