### ISSUE TITLE
How to go headless ?

### ISSUE THREAD

**Issue by oallouch** [PrestaShop/PrestaShop#21144]
Hi,

I'm upgrading my frontend to React and really need a complete REST API, with products and login endpoints, for instance.

When I search, I see mixed signals :
. at [PrestaShop-Day-Paris-2020](https://build.prestashop.com/news/CFP-PrestaShop-Day-Paris-2020/) , headless looks like a priority
. the marked is heading that way. Magento has a great REST API [(doc)](https://magento.redoc.ly/2.4.0-admin/)

But :
. I can't find any session about it at [PrestaShop-Day-Paris-2020](https://events.prestashop.com/prestashop-day-paris-2020/fr/sessions?searchtext=&page=1&group=Tech%20Talks)
. in the [roadmap page](https://github.com/PrestaShop/PrestaShop/projects/1), it doesn't look like it's planned, except 2 lines  "The PrestaShop webservice needs some refactoring and tests" in the backlog.

I need a long term strategy.

What's the plan ?

Thanks a lot,

Olivier Allouch

**Comment by eternoendless** [comment]
I think you'll find your answer here: [The Future Arhitecture](https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/).

We're too busy right now with a lot of subjects but having a public API (Webservices being a private API) is a priority, even though we don't yet know when we'll be able to start working on that.

Feel free to leave your comments on the article above or come [chat with us on Slack](https://join.slack.com/t/prestashop/shared_invite/zt-dkmbz5qf-I~FlEWwmRUOXunc5ui0Ucg).
