### ISSUE TITLE
Hide Header and Footer Index page

### ISSUE THREAD

**Issue by Lajaca** [PrestaShop/PrestaShop#21151]
Hi All

First of all Im not a developer and I need your help

Im trying to hide footer and header on index page due to I would like that looks like a landing page

I done some test changing custom CSS on same pages and everything work well on pages however I dont know how I have to do it on index page (HOME)

.cms-id-1 #header  {display:none;}
.cms-id-1 #footer  {display:none;}
.cms-id-1 .breadcrumb  {display:none;}
.cms-id-1 .page-header  {display:none;} 

Prestashop 1.7.6.7
Php_version:7.2.33 
Thanks!

**Comment by florine2623** [comment]
Hi @Lajaca ,
You can apply `display: none;` to `#header` and `.footer-container`.

Keep in mind that this platform is only for bug and new features issues.
If you need help on your shop, please contact the [support team](https://addons.prestashop.com/en/388-support) or the [partner agencies](https://www.prestashop.com/en/experts).

Thanks!

**Comment by Lajaca** [comment]
De: florine2623
Enviado: viernes, 25 de septiembre de 2020 9:23
Para: PrestaShop/PrestaShop
CC: Lajaca; Mention
Asunto: Re: [PrestaShop/PrestaShop] Hide Header and Footer Index page(#21151)

Closed #21151.
