### ISSUE TITLE
Wrong version number on the 1.7.6.8 installer from git

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#21157]
#### Describe the bug

The installer displays a wrong version number: `1.7.6.7` instead of `1.7.6.8` when using the [git repository](https://github.com/PrestaShop/PrestaShop/tree/1.7.6.x).

#### Expected behavior

The installer should display the correct version number (`1.7.6.8`).

#### Steps to Reproduce

1. Clone the github repository and switch to the `1.7.6.x` branch
2. Launch the installer

**Screenshots**

The version number in the installer:
![image](https://user-images.githubusercontent.com/49909275/94245700-f1d93d00-ff1a-11ea-96bf-72317172dcdc.png)

The version number in the BackOffice:
![image (1)](https://user-images.githubusercontent.com/49909275/94245817-1c2afa80-ff1b-11ea-9604-1ef9fb69a802.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: N/A

**Comment by SimonGrn** [comment]
Update: the problem exists only when you checkout from Git, as the create-release tool already update the version number (so the ZIP is okay).

**Comment by LouiseBonnard** [comment]
Hi @SimonGrn, this issue seems fixed, can we close it?

**Comment by SimonGrn** [comment]
Yes it is definitely fixed ! IDK why it didn't close itself automatically... sorry.
