### ISSUE TITLE
Successful payment & order conf : email non delivered

### ISSUE THREAD

**Issue by qtrompeau** [PrestaShop/PrestaShop#21150]
Hello,

When i buy a product on my shop (http://test.developpement-maymana.fr/) , i received the seller's order confirmation email, but i don't receveid the customer's order confirmation and successful payment emails. However, when I modify the order status to "In preparation" i receive the status email. I receive test emails and I also tried to disable my theme and theme modules.

Do you know how to fix this ? Thanks

**Comment by SimonGrn** [comment]
Dear @qtrompeau 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**, why did you delete everything ? 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
