### ISSUE TITLE
PaymentOptionsFinderCore should keep a local cache of payment methods to avoid multiple calls

### ISSUE THREAD

**Issue by popeio** [PrestaShop/PrestaShop#21156]
#### Describe the bug

The `PaymentOptionsFinderCore` class, which is essentially a `HookFinder` with some salt, is used in your multiple places in the codebase to find available payment methods.

Or rather: it seems to me that this hook is invoked only ONCE in the whole PrestaShop core, but many modules and themes developers abuse this class to load payment methods. Since it is a feature you provide

To give a specific example, I recently stumbled upon a PrestaShop installation with a theme and a module, both using the `::find()` method of this class, resulting in the whole chain of hooks search to be triggered **three times**, with issues both performance-wise and integrity-wise: in some cases, it seems that the third call, in this case coming from a Smarty template, returns zero methods (not a PrestaShop bug, of course).

#### Expected behavior

The class should keep a sort of cache of payment methods locally, and use it to return straightaway, instead of resolving to `parent::find()` multiple times.

Basically:
```
class PaymentOptionsFinderCore extends HookFinder
{
    /**
     * Introduce a local "cache"
     * @var array
     */
    protected $paymentOptions;

    /**
     * Collects available payment options from three different hooks.
     *
     * @return array An array of available payment options
     *
     * @see HookFinder::find()
     */
    public function find() //getPaymentOptions()
    {
        if (!$this->paymentOptions) {
            $this->paymentOptions = [];
        }

        if (count($this->paymentOptions) === 0) { // no cache? well, let's "parent::find()"
            ...
            $this->paymentOptions = $paymentOptions;
        }

        return $this->paymentOptions;
    }
}
```

#### Steps to Reproduce

Create a module extending the `CartPresenter` and overriding the `FrontController`, providing your implementation of the presenter instead of the base `CartPresenter` class.

In your subclass, use the standard `PaymentOptionsFinder` to retrieve the list of payment methods.

Log hooks being called and you will notice more than one call to the chain of `paymentOptions*` hooks.

**Logs**

1. First call
```
[09:15:41][displayPaymentEU] GET /en/order
1) /var/www/index.php(29): DispatcherCore->dispatch()
2) /var/www/classes/Dispatcher.php(515): ControllerCore->run()
3) /var/www/classes/controller/Controller.php(292): OrderControllerCore->initContent()
4) /var/www/controllers/front/OrderController.php(267): SeoSaCartPresenter->present(Object(Cart)) <- CUSTOM PRESENTER
5) /var/www/modules/custompaymentmethod/classes/SeoSaCartPresenter.php(58): PaymentOptionsFinderCore->present(false)
6) /var/www/classes/checkout/PaymentOptionsFinder.php(86): PaymentOptionsFinderCore->find()
7) /var/www/classes/checkout/PaymentOptionsFinder.php(43): PrestaShopBundle\Service\Hook\HookFinder->find()
8) /var/www/src/PrestaShopBundle/Service/Hook/HookFinder.php(70): PrestaShop\PrestaShop\Adapter\HookManager->exec('displayPaymentE...', Array, NULL, true)
9) /var/www/src/Adapter/HookManager.php(79): HookCore::exec('displayPaymentE...', Array, NULL, true, true, false, NULL)
```

2. Second call
```
[09:15:41][][displayPaymentEU] GET /en/order
1) /var/www/index.php(29): DispatcherCore->dispatch()
2) /var/www/classes/Dispatcher.php(515): ControllerCore->run()
3) /var/www/classes/controller/Controller.php(292): OrderControllerCore->initContent()
4) /var/www/controllers/front/OrderController.php(306): FrontControllerCore->initContent()
5) /var/www/classes/controller/FrontController.php(559): FrontControllerCore->assignGeneralPurposeVariables()
6) /var/www/classes/controller/FrontController.php(501): SeoSaCartPresenter->present(Object(Cart))
7) /var/www/modules/custompaymentmethod/classes/SeoSaCartPresenter.php(58): PaymentOptionsFinderCore->present(false)
8) /var/www/classes/checkout/PaymentOptionsFinder.php(86): PaymentOptionsFinderCore->find()
...
11) /var/www/src/Adapter/HookManager.php(79): HookCore::exec('displayPaymentE...', Array, NULL, true, true, false, NULL)
```

3. Third call
```
[2020-09-25 09:15:41][79.8.81.252][displayPaymentEU] GET /en/order
1) /var/www/index.php(29): DispatcherCore->dispatch()
2) /var/www/classes/Dispatcher.php(515): ControllerCore->run()
3) /var/www/classes/controller/Controller.php(312): FrontControllerCore->display()
4) /var/www/classes/controller/FrontController.php(678): FrontControllerCore->smartyOutputContent('checkout/checko...')
5) /var/www/classes/controller/FrontController.php(694): Smarty_Internal_TemplateBase->fetch('checkout/checko...', NULL, 'layouts/layout-...')
6) /var/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'layouts/layout-...', NULL, 0)
7) /var/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
...
55) /var/www/classes/Smarty/SmartyLazyRegister.php(83): smartyRender(Array, Object(Smarty_Internal_Template))
56) /var/www/config/smartyfront.config.inc.php(98): PrestaShop\PrestaShop\Core\Foundation\Templating\RenderableProxy->render(Array)
57) /var/www/src/Core/Foundation/Templating/RenderableProxy.php(52): CheckoutPaymentStepCore->render(Array)
58) /var/www/classes/checkout/CheckoutPaymentStep.php(89): PaymentOptionsFinderCore->present(false)
59) /var/www/classes/checkout/PaymentOptionsFinder.php(86): PaymentOptionsFinderCore->find()
60) /var/www/classes/checkout/PaymentOptionsFinder.php(43): PrestaShopBundle\Service\Hook\HookFinder->find()
61) /var/www/src/PrestaShopBundle/Service/Hook/HookFinder.php(70): PrestaShop\PrestaShop\Adapter\HookManager->exec('displayPaymentE...', Array, NULL, true)
62) /var/www/src/Adapter/HookManager.php(79): HookCore::exec('displayPaymentE...', Array, NULL, true, true, false, NULL)
```

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @popeio ,
Do you have an example of that module that can be installed and checked for any calls  in the logs ?
Thanks

**Comment by popeio** [comment]
> Hi @popeio ,
> Do you have an example of that module that can be installed and checked for any calls  in the logs ?
> Thanks

Hi @florine2623, thanks for your reply

Sure: I can either point you to an official module which does such a thing or, with a little bit of time (like: in a couple of days), provide you with a mock module which does so, just to highlight the behaviour

In general, consider that this behaviour is triggered in the case I described: when a module overrides the `FrontController` and provides its own implementation of the payment methods finder class, but such implementation extends the base class

Anyway, just let me know what you prefer to clarify this, I'll do my best to give you some additional context and some code as example!

**Comment by florine2623** [comment]
I'll be waiting for your example module thanks !
Thanks for the details.

**Comment by hibatallahAouadni** [comment]
Hello @popeio 

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks!
