### ISSUE TITLE
Missing canonical link on product pages

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#21152]
#### Describe the bug

When you try to override `head.tpl` in child theme, canonical link is missing on product pages.
I'll make a PR very soon.

#### Steps to Reproduce

1. Create `templates/_partials/head.tpl` file in child theme of `classic`
2. Override `{block name='head_seo_title'}...{/block}` (for example)
```
{extends file='parent:_partials/head.tpl'}

{block name='head_seo_title'}[TEST] {$page.meta.title}{/block}
```
3. Canonical link is missing on product pages

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @micka-fdz ,

I followed your steps 1 & 2 on PS 1.7.6.7. I don't see what's missing.
Could you be more precise about the canonical link of the product page ? Do you have an example ?
Thanks!

**Comment by micka-fdz** [comment]
Hi @florine2623,

This issue is about canonical link in `<head>` section : `<link rel="canonical" href="...">`.

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.8.
I used this child theme
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/5291773/childtheme-example.zip)
In the FO
![image](https://user-images.githubusercontent.com/16067358/94424829-22bfa900-018b-11eb-869b-8a78d8823046.png)

Thanks to check and feedback.

**Comment by micka-fdz** [comment]
Hi @khouloudbelguith,

I tried again with PS 1.7.6.7 and I have same issue.
Did you add override of `head.tpl` block in your child theme?

For example :
```
{extends file='parent:_partials/head.tpl'}

{block name='head_seo_title'}[TEST] {$page.meta.title}{/block}
```

**Comment by khouloudbelguith** [comment]
@micka-fdz, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.8 and 177x branch using this theme
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/5292501/childtheme-example.zip)
I added an override of `head.tpl` block in the child theme

For example :
```
{extends file='parent:_partials/head.tpl'}

{block name='head_seo_title'}[TEST] {$page.meta.title}{/block}
```
I’ll add this to the debug roadmap.

Thanks!
