### ISSUE TITLE
No product picture display of ID image greater than 9999999

### ISSUE THREAD

**Issue by Paman65** [PrestaShop/PrestaShop#21160]
#### Describe the bug

Good morning everyone 

It's a very strange problem on a prestashop installation, made some years ago by using 1.6.1.4 version. That's what happens:

When the 10 millionth product image is entered, the system does not display it anymore while all the other images with a lower ID keep being displayed with no problem

If I disable the URL REWRITE, all the photos are correctly displayed

I already made sure that in .htaccess there's the picture display with ID greater than 7 numbers, and it's present

`# Images
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]`

As if prestashop didn't take into consideration this instruction

Any tips?

Thanks you all

#### Additional information

* PrestaShop version: 1.6.1.4
* PHP version: 7.0.33

**Comment by florine2623** [comment]
Hello @Paman65 ,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by Paman65** [comment]
Hello
I did a clean install of version 1.7.6.8
I took the Image ID counter over 10 million
The same bug also occurs on 1.7.6.8 - see attached image
![image](https://user-images.githubusercontent.com/47444576/94287724-ef94d400-ff56-11ea-9b8e-6c18c728f0fe.jpg)

**Comment by Paman65** [comment]
If I disable the URL REWRITE, all the photos are correctly displayed - see attached image

Additional information

    PrestaShop version: 1.7.6.8
    PHP version: 7.1.33

![image2](https://user-images.githubusercontent.com/47444576/94290506-90d15980-ff5a-11ea-9b8f-77a86703964a.jpg)

**Comment by ghost** [comment]
@Paman65 

Open new issue with 1.7.6.x label i think is the best way.
