### ISSUE TITLE
Classic theme: Minus symbol missing if subtotal is discount type in checkout's summary subtotal

### ISSUE THREAD

**Issue by oscc-es** [PrestaShop/PrestaShop#21161]
#### Describe the bug

No minus symbol is showed before amount for discount-type subtotal at checkout's cart summary in Classic theme. 

#### Expected behavior

To keep consistency between the two cart summaries showed in the checkout page (see screenshot) the cart summary that is visible along all the checkout process (red circle in screenshot) should have a minus symbol before amount for discount-type subtotal.

#### Steps to Reproduce

1. At the BO enable a discount.
2. At the BO enable final summary at Shop parameters > Order Settings.
3. Make sure Classic theme is also enabled.
4. Go to FO and add any product that fits the discount conditions to your cart.
5. Go to the checkout page.
6. Complete all the steps before payment step.
7. Compare the cart summary in the payment step (blue circle in screenshot) with the 'general' cart summary (red circle).

**Screenshots**

![Screenshot_2020-09-25 Be](https://user-images.githubusercontent.com/57987628/94263050-c2cfc500-ff34-11ea-8925-d6350056fc9c.png)

#### Additional information

* Proposal to solv this issue:  [this PR](https://github.com/PrestaShop/PrestaShop/pull/21065)
* PrestaShop version: develop
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @oscc-es,

Thanks for your report.
I manage to reproduce the issue with 1768.
In the cart page => ok
![image](https://user-images.githubusercontent.com/16067358/94266525-90c16180-ff3a-11ea-99bf-7fe186efb31c.png)
In the checkout page => NOK
![image](https://user-images.githubusercontent.com/16067358/94266603-ab93d600-ff3a-11ea-8be8-9a5caa187123.png)

I’ll add this to the debug roadmap.

Thanks!
