### ISSUE TITLE
Availability messages are changing simultaneously

### ISSUE THREAD

**Issue by dali-rajab** [PrestaShop/PrestaShop#21167]
Hello guys, here is a bug :

When we are in an X product page, and if there is another Y product in that same page (like related products, same category products ..), if we open the quickview modal of the Y product (we are always in the X product page), and make some ajax by changing some attributes, the two availability blocks ( `.product-add-to-cart #product-availability` ) are changing together simultaneously (shown by the red arrow). 

![ajax_bug](https://user-images.githubusercontent.com/39015823/94323859-ac0e8a00-ff97-11ea-8723-f64df603df4d.jpg)

and this is because of the   `.product-add-to-cart #product-availability` selector, which is a result of this code :

```js
  const $addProductToCart = $('.product-add-to-cart');
  const productAvailabilitySelector = '.add';
  const productAvailabilityMessageSelector = '#product-availability';
  const productMinimalQuantitySelector = '.product-minimal-quantity';

...(some skipped lines)

  replaceAddToCartSection({
    $addToCartSnippet: $productAddToCart,
    $targetParent: $addProductToCart,
    targetSelector: productAvailabilityMessageSelector,
  });

...(some skipped lines)

function replaceAddToCartSection(replacement) {
  const destinationObject = $(replacement.$targetParent.find(replacement.targetSelector));
  ...(some skipped lines)
}
```

So the responsible here is this line :
https://github.com/PrestaShop/PrestaShop/blob/08119ad4c1c5b88d2afe088951ae44c19df77440/themes/_core/js/product.js#L249

it should be more selective (inside/outside) the quickview modal, so like many other selectors, it must be some thing like :
```js
const $addProductToCart = $('.quickview .product-add-to-cart, .page-product:not(.modal-open) .row .product-add-to-cart'); 
```

But since Prestashop is progressing in these selectors, the best solution is to make two changes :
1- Replacing this line :
https://github.com/PrestaShop/PrestaShop/blob/08119ad4c1c5b88d2afe088951ae44c19df77440/themes/_core/js/selectors.js#L39
to become :
```js
addToCart: '.quickview .product-add-to-cart, .page-product:not(.modal-open) .row .product-add-to-cart, .page-product:not(.modal-open) .product-container .product-add-to-cart',
```
2- Replacing this line :
https://github.com/PrestaShop/PrestaShop/blob/08119ad4c1c5b88d2afe088951ae44c19df77440/themes/_core/js/product.js#L249
to become :
```js
const $addProductToCart = $(prestashop.selectors.product.addToCart); 
```

**Comment by khouloudbelguith** [comment]
Hi @dali-rajab,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8 and develop branch (1780)
I attached a screen record
https://drive.google.com/file/d/1HKnBqHPNzFvOFxiTAI-BEpjBcfviR90Z/view?usp=sharing
It is related to this PR: https://github.com/PrestaShop/PrestaShop/pull/20556, ping @NeOMakinG 
I’ll add this to the debug roadmap so that it’s fixed.

Thanks!

**Comment by dali-rajab** [comment]
@khouloudbelguith thank you, may be i forgot to mention that i had already made a PR for this issue https://github.com/PrestaShop/PrestaShop/pull/21169
