### ISSUE TITLE
Enable tax breakdown switch inversion

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#21165]
Hello,

I think that the "enable tax breakdown switch" behaviour is not correct.

<img width="1111" alt="Capture d’écran 2020-09-25 à 23 22 26" src="https://user-images.githubusercontent.com/167037/94317161-0272cd00-ff86-11ea-947f-65162a89ff50.png">

When set to "no" (off) I do have the "base price" column in my invoices:

<img width="439" alt="Capture d’écran 2020-09-25 à 23 23 40" src="https://user-images.githubusercontent.com/167037/94317260-3221d500-ff86-11ea-9e1f-0ca621d56363.png">

When set to "yes" (on) this amount is hidden:

<img width="416" alt="Capture d’écran 2020-09-25 à 23 24 35" src="https://user-images.githubusercontent.com/167037/94317297-4bc31c80-ff86-11ea-9c7c-9aac9e6aff20.png">

Can you reproduce this problem?

Regards,

David.

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

Thanks for your report.
We have related issues:
https://github.com/PrestaShop/PrestaShop/issues/14646
https://github.com/PrestaShop/PrestaShop/issues/9920

Could you please check if your issue is similar to this ticket: #14646 and feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
