### ISSUE TITLE
Adding a color picker throws an undefined index notice

### ISSUE THREAD

**Issue by bpato** [PrestaShop/PrestaShop#21173]
#### Describe the bug

I made a module that has a color picker at the configuration using the ModuleAdminController and it throw an undefined index notice.

The thing is that i tested this module that is like the one i made and it didn't throw any notice.
https://github.com/PrestaShopCorp/pscartbanner

**Screenshots**

![Screenshot_2020-09-26 Notice Undefined index size (500 Internal Server Error)](https://user-images.githubusercontent.com/28157986/94348432-91422100-003c-11eb-8ec4-5e1946b05cb7.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @bpato,

I did not manage to reproduce the issue with PS1.7.6.8 using this module: [pscartbanner](https://github.com/PrestaShopCorp/pscartbanner/blob/2df81d6a88d923bdb86c76083bf1e940483858e9/controllers/admin/AdminPsCartBannerController.php#L20 ) and this module: [ps_faviconnotificationbo](https://github.com/PrestaShop/ps_faviconnotificationbo/blob/dev/controllers/admin/AdminConfigureFaviconBoController.php#L20)

So, isn't a module issue? I don't think is related to PrestaShop Core.
Thanks to check and feedback.

**Comment by bpato** [comment]
@khouloudbelguith 
I uploaded this module for test it, this throw me the notice, i don't know what is the difference with the others, maybe i am doing something wrong.

https://github.com/bpato/test-color-picker

**Comment by khouloudbelguith** [comment]
@bpato, I have the same exception using your module.
On this GitHub repository, there is no software support. This is an open-source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!

**Comment by NeOMakinG** [comment]
I think not providing the default value should not crash at all, it looks relevant to me
