### ISSUE TITLE
Labels are not well displayed  

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#21189]
#### Describe the bug

Some labels are wrongly displayed

![image](https://user-images.githubusercontent.com/43613217/94454265-f0757200-01b1-11eb-87d8-40e3228c024a.png)

#### Expected behavior

Here the expected layout

![image (1)](https://user-images.githubusercontent.com/43613217/94454295-fd926100-01b1-11eb-8dfd-1f71a53e3d73.png)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by NeOMakinG** [comment]
PrestaShop/prestashop-ui-kit#107 doesn't fix the whole PR, we'll have to add the "status" class on every badges where the style differ

**Comment by NeOMakinG** [comment]
Opening it again as the class should be added to every labels after the next release UIKit

**Comment by LouiseBonnard** [comment]
Wait for the UI kit release and list where it appears.

**Comment by LouiseBonnard** [comment]
Hi @NeOMakinG, should I move this issue to the _to do_ column?

**Comment by MatShir** [comment]
Pages not exhaustive (need a second check):

Page to apply the new labels:
- [ ] Merchandise Returns (migrated but hidden)
- [ ] Logs (migrated)
- [ ] Customers - [Outstanding](https://github.com/PrestaShop/PrestaShop/pull/20288) (almost finished)
- [x] Order list
- [x] Order status

**Comment by NeOMakinG** [comment]
To be applied, all PRs needs to be merged into develop (related to currently getting migrated pages), and it can be applied to migrated pages only (otherwise we need to add some style to the legacy project)

I think it can be in "To Do" @LouiseBonnard

**Comment by NeOMakinG** [comment]
Did look and looks fixed!
