### ISSUE TITLE
BO - States page - Add new states button is not displayed after incorrect Save

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21183]
#### Describe the bug

In the BO > International > Locations > States page, when we try to save incorrect data => redirection to the states page but the "Add new states button" is not displayed
![image](https://user-images.githubusercontent.com/16067358/94419652-61516580-0183-11eb-8e46-4c7aaaf72c6c.png)

#### Expected behavior

It should be displayed
![image](https://user-images.githubusercontent.com/16067358/94419745-79c18000-0183-11eb-889d-c97e338b16ec.png)

#### Steps to Reproduce

1. Go to BO > International > Locations > States page
2. Click on Add new state
3. Try to create invalid states

#### Additional information

* PrestaShop version: 1.7.6.8, develop(1780)
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/qa-automation

**Comment by khouloudbelguith** [comment]
Ping @matks @PrestaShop/product-team this issue could be fixed in this [ticket](https://github.com/PrestaShop/PrestaShop/issues/10606)?

Thanks!

**Comment by LouiseBonnard** [comment]
It'd be awesome, I add it to the ticket, thanks @khouloudbelguith!
