### ISSUE TITLE
BO - Stats page - No module has been installed.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21186]
#### Describe the bug

In the BO > Stats page, we have an error
`No module has been installed.`
![image](https://user-images.githubusercontent.com/16067358/94451134-565ffa80-01ae-11eb-852c-ea1e5452de19.png)

#### Expected behavior

It should be 
![image](https://user-images.githubusercontent.com/16067358/94451177-637ce980-01ae-11eb-869b-5a7c69db5e13.png)

#### Steps to Reproduce

1. Go to bo > stats page

#### Additional information

* PrestaShop version: 1.7.7.x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @matks in #21195
