### ISSUE TITLE
FO - No product picture display of ID image greater than 9999999

### ISSUE THREAD

**Issue by Paman65** [PrestaShop/PrestaShop#21181]
#### Describe the bug

Good morning everyone

When the 10 millionth product image is entered, the system does not display it anymore while all the other images with a lower ID keep being displayed with no problem

If I disable the URL REWRITE, all the photos are correctly displayed

I already made sure that in .htaccess there's the picture display with ID greater than 7 numbers, and it's present

`# Images RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L] RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L] RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]`

As if prestashop didn't take into consideration this instruction

----------------------------------------------------------------------

I did a clean install of version 1.7.6.8
I took the Image ID counter over 10 million
The same bug also occurs on 1.7.6.8 - see attached image

![image2](https://user-images.githubusercontent.com/47444576/94408777-8e971700-0175-11eb-9009-4d412331c363.jpg)

----------------------------------------------------------------------

If I disable the URL REWRITE, all the photos are correctly displayed - see attached image

![image3](https://user-images.githubusercontent.com/47444576/94408856-ac647c00-0175-11eb-829c-9ee761ea1a36.jpg)

Any tips?

Thanks you all

#### Additional information

* PrestaShop version:1.7.6.8
* PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @Paman65,

I manage to reproduce the issue with PS1.7.6.8 & 1.7.7.x.
BO
![image](https://user-images.githubusercontent.com/16067358/94427785-eb073000-018f-11eb-995c-9f7450ca50aa.png)
FO
![image](https://user-images.githubusercontent.com/16067358/94427870-10943980-0190-11eb-83ef-65c061ba8a15.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Paman65** [comment]
Good morning

Thanks for your answer
I’m sorry but I didn’t manage to solve the problem. It seems that prestashop does not take into consideration the instruction contained in the file .htaccess for the product image greater than 7 numbers

B regards

**Comment by ghost** [comment]
Prestashop close this https://github.com/PrestaShop/PrestaShop/issues/14695 i hope you can find the fix

https://github.com/PrestaShop/PrestaShop-1.6/issues/12

**Comment by Paman65** [comment]
With the change reported in this post

https://github.com/PrestaShop/PrestaShop/issues/14695

now view product images with ID greater than 7 numbers

Thank you

**Comment by ghost** [comment]
@panam65 

You can add this ( override ) when you generate the htaccess the change are not deleted : 

https://github.com/okom3pom/PrestaShop/commit/efba21277c9ee8ebd900e892b6f6b0b467eade21

**Comment by PierreRambaud** [comment]
I'm not able to reproduce, which version of Apache are you using?

**Comment by ghost** [comment]
https://github.com/okom3pom/PrestaShop/commit/78f86713e7d094c58ab7a5cedb2b68a2abf71feb

**Comment by ghost** [comment]
For me : 
:~# apache2 -v
Server version: Apache/2.4.25 (Debian)

**Comment by Paman65** [comment]
> 
> 
> @panam65
> 
> You can add this ( override ) when you generate the htaccess the change are not deleted :
> 
> [okom3pom@efba212](https://github.com/okom3pom/PrestaShop/commit/efba21277c9ee8ebd900e892b6f6b0b467eade21)

Thank you

**Comment by PierreRambaud** [comment]
Thanks, I manage to reproduce the issue :+1:

**Comment by ghost** [comment]
I propose two ways : 

Prestashop say 10M id_image :

https://github.com/PrestaShop/PrestaShop/pull/21196

Prestashop say 100 M id_image

https://github.com/okom3pom/PrestaShop/commit/bb2094152cc5d67f1a5e3e4a79c6f1d2fc118281

Say me what the best

Finaly i think i have to add troubleshooting  in the devdoc ?

**Comment by viv3s** [comment]
Made a workarround for older ps versions
upload a file named rewrite.php with this content to your / 

```
<?php
ini_set("soap.wsdl_cache_enabled", "0");
ini_set('memory_limit', '2048M');
ini_set('max_execution_time', 500);

session_start();

function separarNumeros($cadena) {
    if (!preg_match('/^\d+$/', $cadena)) {
        return 0;
    }
    $separado = implode('/', str_split($cadena));
    return $separado;
}
if ( $_GET['number'] ){
	
	$numero = $_GET['number'];

	$resultado = separarNumeros($numero);
    if ($resultado > 0 ){
	$final = '/img/p/'.$resultado.'/'.$numero.$_GET['name'].$_GET['ext'];

	header("Location: ".$final);
				die();
	}
}

header("Location: /404");
die();
```

add this line after the img rules rewrite in the htaccess:

```
RewriteCond %{HTTP_HOST} ^YOURURL$
RewriteRule ^(\d+)(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}/rewrite.php?number=$1&name=$2&ext=$3.jpg [L]

```
