### ISSUE TITLE
Favicon preview not showing new favicon after upload

### ISSUE THREAD

**Issue by despokd** [PrestaShop/PrestaShop#21204]
#### Description

After uploading a favicon in the BackOffice the favicon preview shows  still the default PrestaShop penguin logo.
When I upload the missing "app_icon.png" from "prestashop/img" the preview shows.

#### Expected behavior

After uploading it show the preview of the new favicon.

#### Steps to Reproduce

1. Go to BackOffice > Design > Template and Logo
2. Choose & upload a new favicon
3. Wait for page refresh and see the previous favicon

**Screenshots**
1. After uploading the favicon
![Screenshot 2020-09-29 123118](https://user-images.githubusercontent.com/23119848/94547684-e73ae280-024f-11eb-8570-5b560aeff309.jpg)
2. After adding an "app_icon.png" in"prestashop/img"
![Screenshot 2020-09-29 123411](https://user-images.githubusercontent.com/23119848/94547821-194c4480-0250-11eb-904e-ae42840a5d86.jpg)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @despokd,

I did not manage to reproduce the issue with PS1.7.6.8 & PS1.7.6.7 & 1770beta2.
https://drive.google.com/file/d/1t5zQLrtmzfMyJq2l8ARyHdIzAKtYlZtR/view?usp=sharing
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by despokd** [comment]
Thanks for the reply @khouloudbelguith 

Preview is now right after force refresh. Maybe there is a workaround in future versions of PS.

Thank you for your time.

**Comment by khouloudbelguith** [comment]
@despokd, 
>Preview is now right after force refresh. Maybe there is a workaround in future versions of PS.

It is a browser cache, not related to PrestaShop.
I close the issue, feel free to open a new one when needed.

Thanks!
