### ISSUE TITLE
Prestashop 1.7.6.7  wrong mapping on Tab Entity

### ISSUE THREAD

**Issue by Daddaniele** [PrestaShop/PrestaShop#21205]
is

/**
 * @ORM\OneToMany(targetEntity="PrestaShopBundle\Entity\TabLang", mappedBy="tab")
 */
private $tabLangs;

should be

/**
 * @ORM\OneToMany(targetEntity="PrestaShopBundle\Entity\TabLang", mappedBy="id")
 */
private $tabLangs;

ad defined on TabLang
/**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="PrestaShopBundle\Entity\Tab", inversedBy="tabLangs")
     * @ORM\JoinColumn(name="id_tab", referencedColumnName="id_tab", nullable=false)
     */
    private $id;

**Comment by khouloudbelguith** [comment]
Hi @Daddaniele,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
