### ISSUE TITLE
Installation problem using git clone

### ISSUE THREAD

**Issue by ThanasisMpalatsoukas** [PrestaShop/PrestaShop#21216]
After installing Prestashop on Ubuntu 20.04 distribution using lampp.

1. git clone https://github.com/PrestaShop/PrestaShop.git
2. sudo chmod -R 777 PrestaShop/ (just for testing purposes)
3. visiting the localhost/Prestashop file
4. Continuing the procedure of installation using the wizard.
5. After everything is completed (100%) without any issues and visiting the homepage at http://localhost/PrestaShop/en/ i get the following error:
![image](https://user-images.githubusercontent.com/43223812/94598981-75d35200-0298-11eb-83bf-5941442d40a2.png)
6. When visiting the backend at http://localhost/PrestaShop/admin-dev/index.php i get a view that seems broken ( i assume the css is not properly configured ) 
![image](https://user-images.githubusercontent.com/43223812/94599215-d06cae00-0298-11eb-8325-9092e4b77ffb.png)

#### Additional information

* PrestaShop version: 1.7.8.0 ( the latest version on github )
* PHP version: 7.4.10
* OS: Ubuntu 20.04

**Comment by PululuK** [comment]
Do not forget to compile assets and clear the browser cache ! 
See https://devdocs.prestashop.com/1.7/basics/installation/localhost/#javascript-and-css-dependencies

**Comment by ThanasisMpalatsoukas** [comment]
Right thank you i will look into it in a bit and close the issue if that was the case!

**Comment by ThanasisMpalatsoukas** [comment]
i would like to add that running this query helped me solve the issue on the front-end of the website:

query by @khalidumarr

INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
VALUES
	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);

**Comment by matks** [comment]
Thank you for the informations @ThanasisMpalatsoukas and thank you for the help @PululuK 😉
