### ISSUE TITLE
Issue with Total number of elements on category page

### ISSUE THREAD

**Issue by krupers** [PrestaShop/PrestaShop#21222]
I tried to find a solution, but I couldn't - so I decided to write this issue here :(

My page is showing pagination with selected number of 12 elements per page.

Then I am switching between i.e. 4 pages with total 40 products and I see:
- Page 1: Products 1 to 12 of total **12**
- Page 2: Products 13 to 24 of total **12**
- Page 3: Products 25 to 36 of total **12**
- Page 4: Products 37 to 40 of total **4**

I verified file: _/themes/child_classic/templates/_partials/pagination.tpl_ and I see:
`{l s='Showing %from%-%to% of %total% item(s)' d='Shop.Theme.Catalog' sprintf=['%from%' => $pagination.items_shown_from ,'%to%' => $pagination.items_shown_to, '%total%' => $pagination.total_items]}`
which is currently correct, but showing total of elements on actual page, not in selected category.

What is wrong?

**Comment by florine2623** [comment]
Hi @krupers ,
Yes that's correct.
If you want to show more articles in the category page, you can do so in your BO > Shop Parameters > Products > scroll down  and change number of products to show.
Thanks!

**Comment by krupers** [comment]
I think it is NOT correct.. total elements (last number) should be a number of total elements of category so 40 not 12.

On other store I see it correct:
- Page 1: 1 to 12 of total 40
- Page 2: 13 to 24 of total 40
- Page 3: 25 to 36 of total 40
- Page 4: 37 to 40 of total 40

And why you closed it if it is not a correct solution :/

**Comment by krupers** [comment]
Incorrect on one shop:
![image](https://user-images.githubusercontent.com/9113275/94668870-dc945200-0310-11eb-9779-e861c5e8c371.png)

Correct on the other:
![image](https://user-images.githubusercontent.com/9113275/94668986-f9308a00-0310-11eb-9719-10eabcf4f5dc.png)
