### ISSUE TITLE
shipping cost according weight not work

### ISSUE THREAD

**Issue by shikotakcom** [PrestaShop/PrestaShop#21229]
Hi,
I set a carrier rule according to weight. It applies on all the zones and with fix price but in front office I just see free shipping.
The shipping cost does not apply on products.
I check the database and the cost is displayed in ps_delivery table. I even create  another carrier but it is still displayed free shipping.
![1-1 (2)](https://user-images.githubusercontent.com/48174981/94691838-aec60200-033e-11eb-9e6a-0f75ee90157b.png)
![1-1 (1)](https://user-images.githubusercontent.com/48174981/94691849-b08fc580-033e-11eb-9240-d3a6ef981cd6.png)

**Comment by SimonGrn** [comment]
Dear @shikotakcom 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by shikotakcom** [comment]
I miss prestashop version. It is 1.7.50 and PHP version is 7.1
What information do you need to help me? because it needs to test. I tried to describe the problem.

**Comment by shikotakcom** [comment]
@SimonGrn Could you please update the topic and say why you close the topic?
I have really problem with this feature and I think it should be tested before you close the topic.

**Comment by SimonGrn** [comment]
Hello @shikotakcom 
please read my last comment, everything is explained.
