### ISSUE TITLE
Registration/Login through checkout keeps loosing customer session - PRESTASHOP 1.7.6.4

### ISSUE THREAD

**Issue by charlieHos** [PrestaShop/PrestaShop#21230]
I am facing the following issue; not logged customers can't complete order during checkout because after step of LOGIN/REGISTRATION customer gets logged out immediately, probably because session get wiped out for some reason.

Consider that registration and login works correctly in authentication page but it does not during checkout.

I think it could be some bug of 1.7.6.4. 

Is someone else encountering this problem?

**Comment by SimonGrn** [comment]
Dear @charlieHos 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
