### ISSUE TITLE
FO - Product page - Incorrect image is displayed when we select a combination 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21236]
#### Describe the bug

In the FO => Product details page > when we select a combination, the cover image is displayed although is not selected.
As detailed [here](https://github.com/PrestaShop/prestashop-specs/blob/master/front-office/Product-images.md)
>If only one photo is chosen for a specific combination, then when going to the combination URL, only this image will be displayed.

#### Expected behavior

Follow specific [spec](https://github.com/PrestaShop/prestashop-specs/blob/master/front-office/Product-images.md)

#### Steps to Reproduce

1. Go to FO > Click on the first product to display the product page
2. The combination selected is the "White" color
3. Zoom the image, incorrect image is displayed'

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/94785120-6dc9fe00-03cf-11eb-90ea-9c55a75a818c.png)

#### Additional information

* PrestaShop version: 1770rc1build1
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
I think is related to this PR: https://github.com/PrestaShop/PrestaShop/pull/15748

**Comment by ngodefroy** [comment]
TEST OK 
Thank you  @atomiix & @khouloudbelguith 

<img width="1234" alt="Capture d’écran 2020-10-06 à 16 49 37" src="https://user-images.githubusercontent.com/69145330/95217887-fee80d00-07f3-11eb-8486-7c11e55d0f4d.png">

**Comment by Progi1984** [comment]
Fixed by #21266
