### ISSUE TITLE
product-variants.tpl not updated when javascript cache is enabled

### ISSUE THREAD

**Issue by xiropot** [PrestaShop/PrestaShop#21233]
#### Describe the bug

When the Smart cache for JavaScript is enabled, the product-variants.tpl is not refreshed on ipa update (let's say when I choose a pair of shoes and select for my size black instead of white.

#### Expected behavior

I made a module for putting an X over a sold-out color (footwear store). Long story short, from the ipa (id_product_attribute) or the group[x] respectively (initial/ajax load) it grabs the selected size and for the size checks the availability for any color assigned to the product.

But if for example Small & White is sold-out (default combination or initial load) it shows the X as expected. If I click in Small & Black (the available one) the X remains. If I refresh on small & black the X goes away (as expected). When I disabled the js cache, it worked even on ajax (re)load.

#### Steps to Reproduce

1. Make some minor modification in the product-variants.tpl where you will update the li class with something dynamic (eg current date)
2. For the selected size, change color with smart cache for javascript enabled.
3. The date will probably not be updated.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.3.22

**Comment by florine2623** [comment]
Hi @tapandagr ,
Could you try to do the same steps with PHP 7.2. HP 7.3 is not compatible with your version of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @tapandagr,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
