### ISSUE TITLE
PROBLEM WITH PRESTASHOP X ERP TINY INTEGRATION

### ISSUE THREAD

**Issue by kalina-lina** [PrestaShop/PrestaShop#21247]
Hello good day.

I'm trying to integrate the site with ERP Tiny (https://tiny.com.br/), I generated a key (token) inside PrestaShop and tried to activate the system, but the following error appears:

** _ Configuration problem.
This call to PrestaShop Web Services returned an unexpected HTTP status of: 302 _ **

I don't know how to proceed.

**Comment by florine2623** [comment]
Hi @kalina-lina ,

The GitHub platform is for bugs found on PrestaShop.

If you have any question regarding any external modules for integration or other, please contact the developer of that module of a [partner agency](https://www.prestashop.com/en/experts) ou the [support-team](https://addons.prestashop.com/en/388-support).

Thanks!
