### ISSUE TITLE
google sitemap 500 server error

### ISSUE THREAD

**Issue by mapi96** [PrestaShop/PrestaShop#21242]
Hello,

I am trying to create my website's sitemap with the Google Sitemap module. I fill in all the data and when I click "generate sitemap", I get a screen with the 500 server error.

Does anyone know how I can fix it?

Thank you very much

**Comment by florine2623** [comment]
Hi @mapi96 ,
With PS 1.7.6.8 ad PS 1.7.7.0, using module Google Sitemap v4.2.0, I can't reproduce your issue.
You can enable debug mode to see where the error comes from.
Please contact the [support-team](https://addons.prestashop.com/en/388-support) to get help on that topic.
Thanks!
