### ISSUE TITLE
BO Free Shipping Discount wrongly calculated

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21254]
#### Describe the bug

In BO, adding a "free shipping" voucher on an order whose carrier has been changed in BO (thus changing the shipping costs), the voucher value is set at the previous shipping costs, not the new one.

#### Expected behavior

Free shipping voucher value should be calculated with current carrier cost, and not the original one.

#### Steps to Reproduce

0. Go to FO, make an order with a free carrier
1. Go to BO > Orders > Open order > Change carrier for a carrier with a fee
2. Add a "Free Shipping" voucher : It's value is at 0€ instead of being at the actual shipping cost

**Screenshots**

https://drive.google.com/file/d/1-zd3aFeN56iz_dlJkwLyeTRVf9hwUDpM/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build1
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #20903
