### ISSUE TITLE
 BO - Shopping carts - Sort by Order ID=>  NOK.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21251]
#### Describe the bug

AIn the BO > Shopping carts > Sort by Order ID > NOK.
You must have a lot of shopping carts to visualize the issue.

#### Steps to Reproduce

1. Go to  BO > Shopping carts > You must have a lot of shopping carts to visualize the issue.
2. sort by Order ID
4. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/94828176-7f2ffc00-0409-11eb-88ae-3fd127518274.png)

#### Additional information

* PrestaShop version: 1.7.6.8, 177X
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/qa-automation

**Comment by khouloudbelguith** [comment]
Ping @matks @PrestaShop/product-team this issue could be fixed [here?](https://github.com/PrestaShop/PrestaShop/issues/10584)

**Comment by SimonGrn** [comment]
Looks like a sorting by alphabetical order instead of numerical order.

**Comment by roncarino** [comment]
Has been changed something in 1.7.6.8? 🤔  I have a 1.7.6.4 with some shopping carts which doesn't seem to have the same problem honestly. And a 1.7.5.2 with 25142 shopping carts which do not have that problem either.

**Comment by khouloudbelguith** [comment]
Hi @roncarino ,

Same issue with PS1768
![image](https://user-images.githubusercontent.com/16067358/94920291-4f8afd80-04b6-11eb-820f-bff3ca3f016d.png)

Thanks!

**Comment by roncarino** [comment]
Hi @khouloudbelguith, yes 1.7.6.8 was the same version you mentioned when you opened this issue.
My question was if you had the same problem with other versions (before 1.7.6.8). Because I tried with 1.7.6.4 and 1.7.5.2 and I couldn't reproduce the problem. thanks

**Comment by khouloudbelguith** [comment]
Hi @roncarino,

I tried with PS1751 => same issue
![image](https://user-images.githubusercontent.com/16067358/95092618-22458600-0728-11eb-8d35-d95f2bf11936.png)

Thanks!

**Comment by Progi1984** [comment]
@boubkerbribri Fix is merged ;)
