### ISSUE TITLE
BO - Features page - No alert displayed when we click on "Save then add another value" button

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21252]
#### Describe the bug

In the BO > Catalog > Features page, there is no green alert when we click on "Save then add another value" button.
In the attribute page => ok

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/94831042-84427a80-040c-11eb-9a1e-c21f3a7b6b72.png)

#### Steps to Reproduce

1. Go to BO > Catalog > Features page
2. Click on 'Add new feature value'
3. Set date
4. click on "Save then add another value" button

#### Additional information

* PrestaShop version: 1770rc1, 1.7.6.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @matks @PrestaShop/product-team this issue could be fixed [here](https://github.com/PrestaShop/PrestaShop/issues/10510)?

Thanks!

**Comment by LouiseBonnard** [comment]
Sure, thanks @khouloudbelguith!
