### ISSUE TITLE
LDAP/AD (ActiveDirectory) Authentication

### ISSUE THREAD

**Issue by BloodyIron** [PrestaShop/PrestaShop#21257]
Any chance we can get LDAP/AD (ActiveDirectory) Authentication implemented please? People have been asking about it elsewhere for years, figured I should post it on github now.

**Comment by SimonGrn** [comment]
Hello,

It would be nice to respect the template.

I'll ping the Product Team to let them know about your improvement idea.

@PrestaShop/product-team what do you think ?

**Comment by LouiseBonnard** [comment]
Hi @BloodyIron, and thanks @SimonGrn! Could you please let us know why do you need LDAP/AD on your PrestaShop store? It will help us learn more about your problems or needs.

**Comment by Hlavtox** [comment]
+1 on this.

We migrated to Office 365 recently and if employees could log in to prestashop by their Microsoft account, it would be cool.

**Comment by matks** [comment]
A contributor [mentioned that hook displayAdminLogin](https://github.com/PrestaShop/PrestaShop/issues/19124#issuecomment-634000123) is enough to implement external authentication 🤔 so there's nothing that prevent you from building it.

**Comment by BloodyIron** [comment]
> Hi @BloodyIron, and thanks @SimonGrn! Could you please let us know why do you need LDAP/AD on your PrestaShop store? It will help us learn more about your problems or needs.

To interface with existing central authentication systems so users don't need to make additional accounts, they can use existing accounts.

**Comment by BloodyIron** [comment]
> A contributor [mentioned that hook displayAdminLogin](https://github.com/PrestaShop/PrestaShop/issues/19124#issuecomment-634000123) is enough to implement external authentication  so there's nothing that prevent you from building it.

Well if that's the attitude to a feature request I might as well just build my own eCommerce tool.

**Comment by SimonGrn** [comment]
> Well if that's the attitude to a feature request I might as well just build my own eCommerce tool.

PrestaShop is an open source project, anyone can help building it. If you can't, you can either wait for someone to do it for you for free, or pay somebody to do it and enhance the project as a whole.

Your choice.

**Comment by BloodyIron** [comment]
I can wait. But a response like that to a feature _request_ really is not welcoming. I'm not new to open source projects, hence asking for it. I'm not demanding it.

For those who clearly seem to be unfamiliar with them, LDAP and AD (ActiveDirectory) are the two most used central authentication systems on the planet. This kind of interfacing is used by countless software and systems globally. Integrating with them means more adoption for environments that already have these central authentication systems. I'm asking for one of the most common authentication features implemented in software today.

**Comment by matks** [comment]
> > A contributor [mentioned that hook displayAdminLogin](https://github.com/PrestaShop/PrestaShop/issues/19124#issuecomment-634000123) is enough to implement external authentication  so there's nothing that prevent you from building it.
> 
> Well if that's the attitude to a feature request I might as well just build my own eCommerce tool.

Hi @BloodyIron I think you mistake my answer so I will provide a more detailed one:

PrestaShop does not aim to build everything. That is why you will not find inside PrestaShop things like 3rd-party authentication for Facebook or Gmail or Twitter even though these are classic 3rd party authentication providers. However PrestaShop must be _open to welcome such extensions_. PrestaShop must not _block_ people who want to build extensions, be it themes, 3rd party authentication systems, ERP bridges ... however we cannot put everything in the Core. PrestaShop is a CMS and as such, it aims to be used as a foundation on which users can plug or build extensions that fit their needs.

So what I wanted to say is: even if we consider the feature request interesting and decide to build and release something that allow LDAP/AD authentication, it will be a _module_ that will be pluggable on PrestaShop but it will not go into the Core. However we will make sure that the Core provides everything needed to plug it.

**Comment by SimonGrn** [comment]
And I'll complete the answer from @matks by saying that this kind of answer is not acceptable here:
>Well if that's the attitude to a feature request I might as well just build my own eCommerce tool.

I'm then closing this issue as it's not going in the right direction.

Feel free to open a new one (following the template this time, since you're "not new to open source" you know how important it is to help maintainers doing their job) if you have more informations or a more convincing use case, and we'll be happy to review it with you.

Regards

**Comment by BloodyIron** [comment]
Well that speaks volumes. 🤦
