### ISSUE TITLE
[BO][Permissions][Database] An exception is displayed when the user has only READ rights

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21261]
#### Describe the bug

In TEAM, I edited the permission of one profile and set it all to "Read Only"
When I go to Database section, try to create a new backup, I get an exception while I should have the following message:
"You do not have permission to create this."

#### Expected behavior

The following message should be displayed: "You do not have permission to create this." or "Access denied"

![Capture d’écran 2020-10-02 à 10 07 22](https://user-images.githubusercontent.com/69145330/94901533-12fbd980-0497-11eb-833f-358a172ce884.png)

#### Steps to Reproduce

1. Go to Team
2. Edit a profile and set his rights to read only
3. Connect with that user in BO
4. Go to Database
5. Click on On Db Backup > Create a backup
6. See the exception

An exception is also displayed when trying to delete a database, switch the YES/NO  buttons under backup options:
![Capture d’écran 2020-10-02 à 10 37 02](https://user-images.githubusercontent.com/69145330/94904174-36c11e80-049b-11eb-8285-547eb81f2b82.png)

https://drive.google.com/file/d/1AiTV1BVsvv7I7MYumK8nsBnplzxjZZxm/view

**Screenshots**

https://drive.google.com/file/d/15AUOwqGzr0MLqHF3b3UF3UTNUmr_rwhk/view

#### Additional information

* PrestaShop version: RC1 & 1768
* PHP version: 7.2

**Comment by matks** [comment]
Assigned to @Amoifr
