### ISSUE TITLE
BO - Order statuses - an alert is not displayed when deleting an order status

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21269]
#### Describe the bug

In the BO > Order Settings > Statuses page, When we try to delete an order status, there is no alert displayed.

It was ok with PS1768

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/94915150-a7bd0200-04ac-11eb-8e9f-9f8cd6fea9f1.png)
.

#### Steps to Reproduce

1. Go to BO > Order Settings > Statuses page
2. Try to delete an order status
4. See error "No alert"

#### Additional information

* PrestaShop version: 1770rc1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21310
