### ISSUE TITLE
BO - Order page - Recalculate shipping costs option enabled - the Shipping price not instantly updated

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21267]
#### Describe the bug

When setting the "Recalculate shipping costs after editing the order" option to Yes, the shipping cost are recalculated when editing the order in BO when the price of the order exceeds the carrier's "limit" but not instantly, we need to refresh the page
![image](https://user-images.githubusercontent.com/16067358/94910988-c10e8000-04a5-11eb-9f7c-d20a4161568f.png)

When we **refresh** the page
![image](https://user-images.githubusercontent.com/16067358/94910925-adfbb000-04a5-11eb-9953-4c173d514e9c.png)

#### Steps to Reproduce

1. Have a carrier set up with a fee below a certain amount, free above it (For example "My Cheap carrier")
![image](https://user-images.githubusercontent.com/16067358/94911588-aab4f400-04a6-11eb-9225-a51887d17a20.png)
2. Go to BO > Shop Parameters > Order Settings
3. Set "Recalculate shipping costs after editing the order" to Yes
4. On FO, make an order with this carrier, under the limit amount
5. On BO, edit the order to make it exceed the limit

#### Additional information

* PrestaShop version: 1770rc1
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/pull/20798
Related to: https://github.com/PrestaShop/PrestaShop/issues/21099

**Comment by khouloudbelguith** [comment]
Ping @jolelievre could be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/20903?

Thanks!

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

it is not directly related, I think what is missing here is just an ajax update of this carrier tab.
But yes, I think it's pertinent to add this small fix to the already existing PR indeed, I have to finish fixing another tricky bug but I'll add this to the PR right after.

Thank you

**Comment by jolelievre** [comment]
Hi @khouloudbelguith,

I looked into the carrier update to see if I could integrate it easily in my PR, but no ajax update
of this part of the page exists currently. So it requires a bit of additional javascript and probably
a new Controller to fetch the appropriate formatted data.

So I think it's safer to handle this bug in a dedicated PR. Although it should probably be done
after the #20903 is merged.

**Comment by LouiseBonnard** [comment]
For a patch version instead of 1.7.7.

**Comment by khouloudbelguith** [comment]
Hi!

Other steps to reproduce the issue:

1. Create order from the FO with only one product
2. In the Shipping steps " choose a carrier with fees (not free)"
3. Delete the product
4. Click on the Carriers Tab 
5. See error
![image](https://user-images.githubusercontent.com/16067358/100102381-d085c600-2e63-11eb-8dbc-6c9d45a947a1.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #22367
