### ISSUE TITLE
Wrong url in credit-slip e-mail

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21272]
#### Is your feature request related to a problem?

When you create a credit slip the url is not correct on the mail

![avoir](https://user-images.githubusercontent.com/5064590/94925384-6bdf6800-04bf-11eb-9066-4c52fc4e75ab.png)

**Comment by florine2623** [comment]
Hi @okom3pom ,
I manage to reproduce the issue with PrestaShop versions 1.7.7.0 and PS 1.7.6.8.
I’ll add this to the debug roadmap so that it’s fixed. Thank you for your pull request!
Thanks!
