### ISSUE TITLE
The status name is not visible in the listing when the colors field is empty.

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21283]
## Is your feature request related to a problem?

The status name is not visible in the listing when the colors field is empty.

## Describe the solution you'd like

Define a default color when the colors field is empty.

| Before      | After |
| ----------- | ----------- |
| ![Capture du 2020-10-03 16-42-00 (1)](https://user-images.githubusercontent.com/16455155/94994427-cd730580-0597-11eb-820c-a468a0368965.png) | ![image](https://user-images.githubusercontent.com/16455155/94994377-7705c700-0597-11eb-8a50-fdb3137b5efa.png)|

## Alternatives you've considered

The color field must be required in `OrderState` and `OrderReturnState` objects definition :

```php
'color' => [
 'type' => self::TYPE_STRING, 
 'validate' => 'isColor',
 'required' => true // Here
],
```
⚠️  This may introduce BC. Ex.: _imagine modules that create statuses without the color field_

### 🎥 [Click to see screen record](https://drive.google.com/file/d/1DQhDONBigtrS_seWSDWf9UtIgtzrkaJS/view)

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20442 to fix the issue.
Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20441.
Can we close the ticket?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

About this issue, do you think, it is different from this ticket: https://github.com/PrestaShop/PrestaShop/issues/20441?
In this issue, you are implementing a fallback mechanism where, if there is no color available, it provides a relevant fallback color?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

As discussed with @matks it seems your issue is not duplicate to his. 
So thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by MatShir** [comment]
@NeOMakinG what do you think of @PululuK suggestion?

**Comment by NeOMakinG** [comment]
@MatShir It's a go for me, but @PrestaShop/ux-team should validate or provide the UX behavior

**Comment by prestascott** [comment]
Hello everyone,

Thank you for your report @PululuK :)

It's also a go for me. If we decide to put a default color it needs to be "neutral", like grey. 
For example, we can re-use the secondary color from the BO which is #6C868E or a lighter grey #F8F8F8 (used for the background).

**Comment by NeOMakinG** [comment]
@PululuK I tried it on develop, I've got an exception while adding a status without color :

![image](https://user-images.githubusercontent.com/14963751/100988246-ce9cc080-354f-11eb-8441-6daa3af0a640.png)

**Comment by MatShir** [comment]
@NeOMakinG I think your bug is related to https://github.com/PrestaShop/PrestaShop/issues/20441.
Here, only the default color with a white background is changed.

**Comment by Progi1984** [comment]
Should be fixed in #27590

**Comment by hibatallahAouadni** [comment]
@Progi1984 so should we add it in the **Fixed ticket** row?

**Comment by Progi1984** [comment]
@hibatallahAouadni You're right.
