### ISSUE TITLE
Bağlantı linkleri ve kategorilerin kayması

### ISSUE THREAD

**Issue by pontean** [PrestaShop/PrestaShop#21288]
![Ekran görüntüsü 2020-10-04 205143](https://user-images.githubusercontent.com/32788556/95023044-7a767c80-0683-11eb-8ede-de2c0ba2fa34.png)
![Ekran görüntüsü 2020-10-04 205056](https://user-images.githubusercontent.com/32788556/95023045-7ba7a980-0683-11eb-92c2-f6b68f7630da.png)

Buradaki değişiklikten sonra işlemleri geri almama rağmen kaymalar oluştu. Eklenen linkleri silsem dahi düzelmiyor. Yardımlarınızı bekliyorum.

**Comment by SimonGrn** [comment]
Hello,
Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by SimonGrn** [comment]
Hello,

please write your issue in english and **follow the template**. I close this issue, feel free to create a new one, following the rules.

Thank you.
