### ISSUE TITLE
BO - Payment Methods - Special characters are not displayed correctly

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21298]
#### Describe the bug

Special characters are not displayed correctly using 1.7.7.x.
Ok using develop branch

#### Steps to Reproduce

1. Go to BO -> payment
2. Click on payment methods
3. Scroll down to the bottom of the page

**Screenshots**

<img width="1279" alt="Capture d’écran 2020-10-05 à 11 42 47" src="https://user-images.githubusercontent.com/3034677/95069261-b868b480-0706-11eb-90ba-95c09b7d5695.png">

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by marionf** [comment]
Duplicate of #22272
