### ISSUE TITLE
CI : Lock PR if PR contains "Merge commits"

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#21294]
#### Is your feature request related to a problem?

A Pull Request should not contains merge commits.

#### Describe the solution you'd like

Lock PR if PR contains "Merge commits"

**Comment by kpodemski** [comment]
@Progi1984 

I think we can use this one:
https://github.com/z3by/block-merge-commits-action

?

**Comment by Progi1984** [comment]
Great idea @kpodemski

**Comment by kpodemski** [comment]
@Progi1984 is there any reason to assign me after something is merged? 🤔
