### ISSUE TITLE
Product feature error when lenght is long

### ISSUE THREAD

**Issue by langziyang** [PrestaShop/PrestaShop#21292]
version: prestashop1.7.6.7

when Feature group lenght is very long(but i do not know how long). add it to product error.

right: after "Choose a feature" options li id is "select2-form_step1_features_0_feature-result-oapg-1",the last char is 1
![right](https://user-images.githubusercontent.com/2345387/95049501-70548c80-071c-11eb-8ab5-1735590828da.png)

but when i have very more feature group,the after "Choose a feature" options li id is "select2-form_step1_features_0_feature-result-kb26-0",the last char is 0. so can not get right feature value of select feature group

![error](https://user-images.githubusercontent.com/2345387/95049791-0983a300-071d-11eb-87f5-84c70a8f9fd2.png)

please tell me how can fix it.

**Comment by langziyang** [comment]
i find why,it is not bug,some feature group not have language

**Comment by khouloudbelguith** [comment]
Hi!

Thanks for your issue.
Please in the next time you need to follow the GitHub issue's template.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
