### ISSUE TITLE
Bad variable name in order_customer_comment.html.twig

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21296]
#### Describe the bug

Bad variable name in order_customer_comment.html.twig

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1) Make an Order
2) Go to Order Detail
3) Send a comment on the order
4) Check Mail from owner shop

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0 nightly
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I manage to reproduce the issue with 1770rc1build1.
In fact, In the BO > Design > Email theme > `order_customer_comment`
![image](https://user-images.githubusercontent.com/16067358/95072107-fd8ee580-070a-11eb-8e7e-992608d43ef7.png)

I checked the ps1768
![image](https://user-images.githubusercontent.com/16067358/95072177-17c8c380-070b-11eb-8b7b-010d566d2ed3.png)

It is a regression.
I’ll add this to the debug roadmap.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #21297
