### ISSUE TITLE
BO - Missing Gift and Recycled Paper in Create Order migrated page

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21300]
#### Describe the bug

On Create Order migrated page, when "Gift Wrapping" and "Recycled packaging" options are ON, these options are not displayed, so it's not possible to add them to the orders.

It was displayed in 176.

Edit : When reusing, in BO > Create order, an order made from FO with recycled packaging, Gift, and Gift message, theses options are not displayed due to the bug, BUT the Gift price is added in total at the end of the order. When order is created, the two options are displayed, and so is the gift message.
So there is no "calculations" missing from the page, just the display of these 3 options (two checkboxes and one text field).

#### Expected behavior

We should have the following options displayed in 177 migrated page : 

* Checkbox for "Recycled packaging"
* Checkbox for "Gift" (which had the "Gift-wrapping price" included in the total at the end of the order)
* Gift Message

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Order Settings > Gift Options > Set Gift Wrapping and Recycled Packaging to YES
2. Go to BO > Orders > Add new order > Select a customer
3. Add a product, see Shipping block : There is no Gift of recycled packaging options displayed, there should be.

**Screenshots**

On 1.7.6.8 : 
![create order no gift recycled options](https://user-images.githubusercontent.com/55688534/95084672-7d727b00-071e-11eb-89f5-291bec874c97.png)

On 1.7.7 RC1 :
![create order no gift recycled options 177](https://user-images.githubusercontent.com/55688534/95084668-7cd9e480-071e-11eb-9747-665f6ee7b2c3.png)

#### Additional information

* PrestaShop version: 1770rc1build1
* PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21331
