### ISSUE TITLE
main_variants always empty in templates/catalog/_partials/miniatures/product.tpl

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#21306]
1. Create a product with some product attributes (shirt with S/M/L sizes for example)
2. Associate this product with a category
3. Visit the category 

=> $product.main_variants variable in "templates/catalog/_partials/miniatures/product.tpl" seems to be always empty. 
=> Variants are not shown :( 

Why ?

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.25

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

If you try to create a product with color attributes, are they displayed?
I tried with PS1751, PS1768
If I have Color attributes =>
![image](https://user-images.githubusercontent.com/16067358/95091570-e827b480-0726-11eb-8fb4-c2652ba29fe6.png)
=> ok
If I have other attributes => Not displayed
![image](https://user-images.githubusercontent.com/16067358/95091683-0a213700-0727-11eb-8ddb-89c876f368d5.png)
![image](https://user-images.githubusercontent.com/16067358/95091713-13120880-0727-11eb-9e1a-f57651cb9d5f.png)

Thanks to check and feedback.

**Comment by Daaaaad** [comment]
Hi @khouloudbelguith,

Thank you for your time 👍

Yes color attributes are displayed but not others (select or radio). Is this the expected behavior? 

Regards,

David.

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,


Yes, this is the expected behavior.
https://github.com/PrestaShop/prestashop-specs/blob/master/front-office/products-list.md
I close the issue, feel free to open a new one when needed.

Thanks!
