### ISSUE TITLE
Product sort order not sanitized

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#21312]
#### Describe the bug

In category page, sort order can be changed in the url for an unexpected value : this generate a php notice in debug mode et an 500 error without.
Sort order has to be sanitized, it's not secure like this.

#### Expected behavior

Sort order in the url has to be sanitized.

#### Steps to Reproduce

by example, expected value in category page : 
/3-vetements?order=product.position.asc

Just remove .asc : 
/3-vetements?order=product.position.asc

You will see the php notice.

#### Additional information

* PrestaShop version: develop, 1.7.6, 1.7.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1, PS1.7.6.8, and 1770rc1build1.
![image](https://user-images.githubusercontent.com/16067358/95173340-d2fb6600-07b8-11eb-9e63-f494dc5ddb3c.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by jf-viguier** [comment]
@khouloudbelguith I've made a PR

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21313

**Comment by Progi1984** [comment]
Ping @PrestaShop/product-team for specs

**Comment by topfuel75** [comment]
It seems like this only do a check to see of the sort parmateters contain three instances.

Wouldnt it be better to do someting like this:

```
    public static function newFromString($sortOrderConfiguration)
    {
        $sortParams = explode('.', $sortOrderConfiguration);

        if (count($sortParams) !== 3 || 
            $sortParams[0] !== 'product' || 
            !in_array(strtolower($sortParams[2]), ['asc', 'desc'])) {

            return new static('product', 'name', 'asc');
        }

        list($entity, $field, $direction) = $sortParams;

        return new static($entity, $field, $direction);
    }
```
Edit: Change the code a bit.
