### ISSUE TITLE
As a merchant, I should be able to do important adjustments from the order page

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#21319]
After years of using Prestashop, these are the most frustrating things related to the order page - encountered as a merchant, that should be addressed.
#### Is your feature request related to a problem?

As a merchant, I often need to make some adjustmens to the orders, after they heve been placed.

#### Describe the solution you'd like

As a merchant, I should be able to do the following adjustments from the order page:
- **Change the carrier, even with an inactive carrier.** I want to have some carriers that are not available for customers in the FO, but I can choose to use them for a specific order.
- **Change payment method** (and send payment link). Often times, a customer asks to pay in a diffrent way than the payment method selected at checkout. For example, the client selected COD but then asks me to pay by credit card, paypal or wire transfer. I need to be able to change the payment method and sent the customer a link to finish the payment.
- **Charge an additional payment.** The customer pays with Credit Card (for example), then asks me to add another product to the order. I need to be able to generate a new payment link in order for the customer to go and pay the difference.
- **Add shipping cost to order.** The client places an order that exceeds the "free shipping" ammount, so he gets free shipping. Then, he asks me to edit his order and remove a product he no longer wants. If the edited order falls below the free shipping threshold, we need to add the payment cost to the order. **This is not currently possible and it is very important.** On the other hand:
- **Remove shipping cost from order**, whithout the need of a discount code
- **Leave order notes that are only visible on that order.** Currently, if you leave a comment on one order, it is visible on all orders belonging to the same customer

**Comment by khouloudbelguith** [comment]
Hi @rdy4ever,

Thanks for your report.
Ping @MatShir @PrestaShop/product-team what do you think?

Thanks!

**Comment by SimonGrn** [comment]
Hello @rdy4ever 
did you try the new order page in the 1.7.7.0 beta 2 ?

**Comment by florine2623** [comment]
Hello @rdy4ever ,
since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
