### ISSUE TITLE
[Product - Combination or modify quantity] An error occurred while processing your request

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21342]
Hi, I have this error when I try to modify quantity or combination :
<img width="611" alt="Capture d’écran 2020-10-07 à 16 12 11" src="https://user-images.githubusercontent.com/43704805/95342589-e04b4a00-08b7-11eb-9d80-9d8d73a77ed7.png">

I get this error in console 
<img width="954" alt="Capture d’écran 2020-10-07 à 16 14 05" src="https://user-images.githubusercontent.com/43704805/95342838-23a5b880-08b8-11eb-9947-d38294527fe7.png">

The complete URL seems strange :

https://www.jeu-montessori.fr/index.php?controller=product&token=862663642d129da3af1e6d22fd50815f&id_product=463&id_customization=0&group%5B27%5D=296&qty=2&token=862663642d129da3af1e6d22fd50815f&id_product=17&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=125&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=96&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=50&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=503&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=117&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=16&id_customization=0&token=862663642d129da3af1e6d22fd50815f&id_product=570&id_customization=0

There is a lot of Id_product not related to the product on which I am making test :
https://www.jeu-montessori.fr/accueil/463-arc-en-ciel-montessori-en-bois.html

I would like to know if a Mass edition module could be responsible for this actual problem or if can't be related... 
If it can be related to a mass editor module, then I could contact the developper and ask him to solve the problem. If you think it can't be related, tell me. 

Thank you

EDIT : Here the error with native url debug (pagespeed and cache disabled): 

<img width="1553" alt="Capture d’écran 2020-10-07 à 16 26 09" src="https://user-images.githubusercontent.com/43704805/95344437-f0642900-08b9-11eb-866f-ecb37e1577d2.png">

The only fact of select an other quantity or select an other declination can display a picture of an other product (not related to the actual product... the url of product is modified)... The request sent to my prestashop seems have become crazy...

**Comment by SimonGrn** [comment]
Dear @passio777x 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
