### ISSUE TITLE
Product Comment module throw error when posting the comment without criterion

### ISSUE THREAD

**Issue by Hydrog3n** [PrestaShop/PrestaShop#21347]
#### Describe the bug

In the log, we see this error 
```
Type error: Argument 2 passed to ProductCommentsPostCommentModuleFrontController::addCommentGrades() must be of the type array, boolean given, called in modules/productcomments/controllers/front/PostComment.php on line 87
```

#### Expected behavior

It should not throw an error. 

#### Steps to Reproduce

I didn't manage to found a way of reproducing this error but the main problem comes from the `criterion` in the POST is not defined. `Tools::getValue` return mixed value it's a boolean when the error throw. 

https://github.com/PrestaShop/productcomments/blob/master/controllers/front/PostComment.php#L58

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 7.2
* Module version: 4.1.0

**Comment by florine2623** [comment]
Hi @Hydrog3n ,
I couldn't reproduce your error. I successfully managed to post a comment on my PS 1.7.6 shop using Product Comment v4.1.0.

When you find the steps to reproduce the issue, feel free to open a new issue.

Thanks!

**Comment by Hydrog3n** [comment]
@florine2623 serious... Yes because we just saw log so the bug exists not closing just because you can reproduce. I see the bug in the code so it's can really happen
