### ISSUE TITLE
The product variations.

### ISSUE THREAD

**Issue by Freiezonemarket** [PrestaShop/PrestaShop#21349]
Good evening,
When adding a product with a combination, when I choose the colors and then click on "Generate", the combinations are not generated automatically. I get an error message.
I am a beginner and I could provide you with my back office information so you can see this.
Waiting to read you quickly.
Mrs Jolanda
Email: admin@freie-zone-market.de

**Comment by SimonGrn** [comment]
Dear @Freiezonemarket 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
