### ISSUE TITLE
[BO] Avatar photo is broken

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21358]
#### Describe the bug

Go to BO
->Click on your avatar, yo should see the picture isnt loaded
-> Go to Team>employees, click on an employee, the picture isnt loaded.

#### Steps to Reproduce

1. Go to your avatar in corner right
2. See avatar photo is broken
3. Go into Advanced Param>Team>Employees and select an employee
4. See avatar photo is broken

**Screenshots**
<img width="1133" alt="Capture d’écran 2020-10-08 à 10 22 30" src="https://user-images.githubusercontent.com/69145330/95433410-2ce26400-0950-11eb-9c89-cde2496d543b.png">

![Capture d’écran 2020-10-08 à 10 12 31](https://user-images.githubusercontent.com/69145330/95433366-1e944800-0950-11eb-9cda-35d41a1b5352.png)

**Might have a link with:** https://github.com/PrestaShop/PrestaShop/pull/20207

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by marionf** [comment]
@ngodefroy Is it a regression compared to 1.7.7.X ?

**Comment by ngodefroy** [comment]
@marionf yes, it's a regression, couldnt reproduce it in 1.7.7.x

**Comment by LouiseBonnard** [comment]
Surely a consequence of #18622, but might be fixed with https://github.com/PrestaShop/PrestaShop/pull/20430. @Progi1984, can you confirm?

**Comment by Progi1984** [comment]
I think so. I could check when #20430 will be checked by QA Team.

**Comment by MatShir** [comment]
The issue has been moved on the blocked since it needs to wait for #20430 to be merged first

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-qa  I didn't reproduce this bug. Could you check too ?

**Comment by SimonGrn** [comment]
@khouloudbelguith could you take a look please ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I manage to reproduce the issue with the develop branch following these steps:

1. Go to BO > Advanced Parameters > Team > Employees page
2. Create a new employee with setting only required fields
2.1 Don't attach a file
2.2 Don't enable gravatar
3. Save
4. Try to log in with the new employee
5. Go to a page migrated (for example orders/products)
6. Click on your profile
7. see error

![image](https://user-images.githubusercontent.com/16067358/98714822-a6270980-2389-11eb-8393-fa015e6d0825.png)

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Sorry : But I just tried (with the latest version of develop branch) and no problem 

![image](https://user-images.githubusercontent.com/1533248/100112431-80146580-2e6f-11eb-9f4b-6dfcdd32010e.png)
![image](https://user-images.githubusercontent.com/1533248/100112468-8c98be00-2e6f-11eb-8473-4738ccd0fdfb.png)

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Yes, it is ok now
![image](https://user-images.githubusercontent.com/16067358/100125273-e358c480-2e7c-11eb-8c1f-ef7ebd10c511.png)

I will close the issue.
Thank you!
