### ISSUE TITLE
The product quantity in backoffice / products list table in not corresponding to the stock/quantity of each products attributes

### ISSUE THREAD

**Issue by Christophe-re** [PrestaShop/PrestaShop#21354]
#### Describe the bug

The product quantity in backoffice / products list table in not corresponding to the stock/quantity of each products attributes. (déclinaison produit in french) 

For illustrate some screenshots with a product which has for ID 42. 
 
The quantity of the product attribute (16  in total) : 
![image](https://user-images.githubusercontent.com/22072618/95425556-c0ae3300-0944-11eb-971f-a8611d261ad8.png)

My stock  (16  in total) :
![image](https://user-images.githubusercontent.com/22072618/95425468-9d838380-0944-11eb-9731-28be6779b6fc.png)

Quantity in the product list table (36) :
![image](https://user-images.githubusercontent.com/22072618/95424935-c6574900-0943-11eb-9c43-9c09143345e3.png)

#### Expected behavior

The quantity in the BO / product list should be equal to the total of product attributes (16 for this example)

#### Steps to Reproduce

1. Add attributes on a product with a quantity and save
2. Remove attribute(s) and save 
3. Add others attribute(s) and save 

I think that ps_stock_available is not cleaned when a product attribute is removed.
In this picture of my ps_stock_available table, we can see that there are lines for the product attributes with Id 148 / 149 /  150 / 151 / 153 but they are not longer existing. 

![image](https://user-images.githubusercontent.com/22072618/95424549-1681db80-0943-11eb-826f-316b6a2a3bae.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2.31

**Comment by florine2623** [comment]
Hi @Christophe-re ,
I can't reproduce your issue in PS 1.7.8.
Here are my result after following your steps on a product with combinations :
![Capture d’écran 2020-10-08 à 09 32 53](https://user-images.githubusercontent.com/16019289/95428530-68c5fb00-0949-11eb-95d5-cc2d6f57e127.png)
![Capture d’écran 2020-10-08 à 09 33 00](https://user-images.githubusercontent.com/16019289/95428535-6b285500-0949-11eb-921f-018ebf597898.png)
![Capture d’écran 2020-10-08 à 09 33 05](https://user-images.githubusercontent.com/16019289/95428536-6d8aaf00-0949-11eb-9829-d441b1fe5de4.png)

If you have more info on how to reproduce the issue, feel free to open a new issue.
Thanks!
