### ISSUE TITLE
Added category in products BO does not work

### ISSUE THREAD

**Issue by laurentmacca** [PrestaShop/PrestaShop#21356]
Hello

Recently, I try to attach a new category to my product on BO and cannot save change.
More precisely, when I click on save button the green alert "changes updated" appears but when I refresh the product page the category still remains unattached.
No problem with REF length or SEO length as mentionned on previous issues.
The main category is also selected.

Prestashop 1.7.2.3
PHP 7.1.32

Thanks for your help.

**Comment by florine2623** [comment]
Hi @laurentmacca ,

I can't reproduce your issue.

If you changed the main category, you can refresh the product page to see the URL change.
If you just add a category to the product without changing its main category, you will need to check the said category.

Thanks!

**Comment by laurentmacca** [comment]
Hi Florine
Thanks for your answer.
I try to change the main category (despite it was already checked).
Because I cannot save changes nothing works ! I tried several browsers. Same problem appear.
Is there any config info you need to check this ?
Thanks.
