### ISSUE TITLE
Error on Module Manager

### ISSUE THREAD

**Issue by ylazy** [PrestaShop/PrestaShop#21353]
#### Describe the bug

Module Manager didn't work.

#### Expected behavior

When I'm using module manager to upload and install a new module (printify_module_1.7 download here https://printify.com/plugins/prestashop/printify-17.zip), an error occured during upload:

```
Compile Error: Declaration of Printify::getContainer() must be compatible with ModuleCore::getContainer(): Symfony\Component\DependencyInjection\ContainerInterface

[Symfony\Component\Debug\Exception\FatalErrorException 0]
```

Then I refresh the page and now the module manager show up the error again, even I didn't upload anything. Now whenever I clicked on the module manager menu, the error show up.

**Screenshots**

![image](https://user-images.githubusercontent.com/6010183/95408971-e3dbe100-094a-11eb-8504-9596b2c5e63d.png)

#### Additional information

* PrestaShop version: 1.7.7.0 Beta 2
* PHP version: 7.4

**Comment by SimonGrn** [comment]
Hello,

Your problem must be addressed to the module developer itself.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
