### ISSUE TITLE
Page Performances in Advanced parameters loads fine but is empty

### ISSUE THREAD

**Issue by MultiTech-MS** [PrestaShop/PrestaShop#21364]
Hi everyone,

I have this issue on our site and I can't figure out why. I'm using 1.7.4.4
The Page Performances _(to configure cache parameters)_ is **lauching fine** _(no error in console or Prestashop)_, 
no white page BUT.... **is totaly empty**. 

![Screenshot_2020-10-08 Performances • Tissus Eychenne](https://user-images.githubusercontent.com/51752454/95459028-552f8a00-0973-11eb-9800-5e4a2dc482e8.png)

Since the admin menu configuration is no longer there on 1.7, I can't check the controller. Furthermore, in my files,
in the repository "controllers>admin>..." there is no "AdminPerformanceController.php" to be found. Is it normal ?

I saw that in the changelog of the 1.7.1
– #7428: Update wording AdminPerformanceController.php

Do you have an idea where it might come from ?

Thank you

**Comment by florine2623** [comment]
Hi @MultiTech-MS ,
I can't reproduce your issue in PS 1.7.4.4.

There are multiple things you can check :
- check error log
- disable all overrides
- enable debug mode
- check what files have been changed in Advanced Parameters > Information
- restore your site if needed

There is no  in PS 1.7.4.4 :
https://github.com/PrestaShop/PrestaShop/tree/1.7.4.4/controllers/admin

Or you could contact the [support-team](https://addons.prestashop.com/en/388-support) of a [partner agency](https://www.prestashop.com/en/experts) to troubleshoot your issue.

Thanks!

**Comment by MultiTech-MS** [comment]
Hi @florine2623 ,

Thank you for your answer.  I did check and : 

-     check error log
There is no indications of any error that could have done this in the prestashop logs.
As far as the server logs are concerned I really wouldn't know what I'm looking for.

-     disable all overrides 
I don't have any customed overrides in /override

-     enable debug mode
The only warnings and error while on the Performance Controller page deals with translations.

-     check what files have been changed in Advanced Parameters > Information
Only the robot.txt (but with FTP, I see that it has been last modified more than 2 years ago)

-     restore your site if needed
I can't really do that on an online shop.

I can't seem to find where the error might come from. Can you help me ?
I can give you (in private message or something else) acces to the admin of the concerned site + ftp access too.
