### ISSUE TITLE
The escape function causes unreadable text in some languages, such as Slovak or Czech.

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#21363]
#### Describe the bug

The escape function causes unreadable text in some languages, such as Slovak or Czech.
adminps/themes/default/template/controllers/customer_threads/helpers/view/message.tpl:58
`<p class="message-item-text">{$message.message**|escape:'html':'UTF-8'**|nl2br}</p>`

The result of the escape function (after its use) is the following : **`Pros&iacute;m o umožnenie platby kartou pri dobierke`**
The correct text is : **Prosím o umožnenie platby kartou pri dobierke**

**Screenshots**
![2020-10-08_11-44-33](https://user-images.githubusercontent.com/1309982/95448379-8e5ffe00-0963-11eb-9a6a-f6ac48aeea28.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @elrosi ,
I can't reproduce the issue in PS 1.7.6.7 :
![Capture d’écran 2020-10-08 à 14 10 43](https://user-images.githubusercontent.com/16019289/95456774-24018a80-0970-11eb-9755-de3714bcc25d.png)
![Capture d’écran 2020-10-08 à 14 10 52](https://user-images.githubusercontent.com/16019289/95456778-25cb4e00-0970-11eb-870e-f3f3bfbf5241.png)

**Comment by elrosi** [comment]
Hi @florine2623 
The problem still exists and I managed to replicate it directly in the official demo of PrestaShop https://demo.prestashop.com/
https://share.vidyard.com/watch/NmMiXgkcDzpYkshMvrFaFA?

I used the following text: `Ak by ste chceli pridať poznámku k Vašej objednávke, prosím, poznačte ju nižšie.`
The character encoding in the database is **utf8_general_ci**

![2020-10-22_16-53-00](https://user-images.githubusercontent.com/1309982/96889818-470b5e80-1487-11eb-89d8-fb2819aac300.jpg)

**Comment by elrosi** [comment]
The result in the back office:

![2020-10-22_17-05-21](https://user-images.githubusercontent.com/1309982/96891411-ee3cc580-1488-11eb-99bb-acab0f2fb304.jpg)
