### ISSUE TITLE
Display the overrides list in the Informations tab

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#21368]
#### Is your feature request related to a problem?

When debugging a PrestaShop installation, it's would be nice to know if a PrestaShop behavior is overridden 

#### Describe the solution you'd like

A list of overrides is displayed in the Informations tab

#### Alternatives you've considered

I look in the ftp which is cumbersome as you have to check many many folders

#### Additional context

Many times, a customer contacts me having an issue with some PrestaShop aspect like the order page for example.
I eventually discover the source of the issue which is most of the time a module override that isn't compatible with the current ps version... 
It would be a time saver to just glance over the overrides list and determine the suspect directly
I can try to implement it, just tell me if it's interesting to you as well

**Comment by florine2623** [comment]
Hi @unlocomqx ,
Thanks for the suggestion, I will ping our product team to see what they think about that.
If you have a PR available, do not hesitate to link it here !
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/product-team ,
What do you think about putting all overrides in the BO Information tab ?
Thanks!

**Comment by unlocomqx** [comment]
I made a PR the easy way, it's simply showing the php file list from the override folder. If there's a better way, please let me know.
