### ISSUE TITLE
Breaking change in product blocks and classic theme

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#21366]
#### Describe the bug

Breaking change because of the assumption that any module will have correct `{foreach}` structure.

#### Expected behavior

We shouldn't have notice after module installation, most of core modules have no `$key` in `{foreach}`, we need to check if we can use `position`...

#### Steps to Reproduce

1. Install this module: https://www.dropbox.com/s/j0mtr46xnnwu0y4/ps_randomproducts.zip?dl=0
2. Go to homepage

Should be fixed thanks to this:
https://github.com/PrestaShop/PrestaShop/pull/20927

**Screenshots**

https://www.dropbox.com/s/gduk0wyy4dt5uly/Zrzut%20ekranu%202020-10-8%20o%2015.01.17.png?dl=0

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @kpodemski ,
Thanks for the module.
I managed tor reproduce the issue in PS 1.7.7.
I'll add this to the debug roadmap !
Thanks for the PR.

**Comment by khouloudbelguith** [comment]
Hi @florine2623,

Did you reproduce the issue with PS1.7.6.8?
Is it a regression?

Thanks!

**Comment by florine2623** [comment]
Hello @khouloudbelguith ,
No it is not.
In PS 1.7.6.8, there's no error, the module shows normally :
![Capture d’écran 2020-10-08 à 17 03 52](https://user-images.githubusercontent.com/16019289/95477104-46070700-0988-11eb-8122-ce5f5ff4e854.png)

**Comment by khouloudbelguith** [comment]
Thanks @florine2623 !

**Comment by Progi1984** [comment]
Fixed by #20927
