### ISSUE TITLE
Product Controller: Refresh uses wrong title for meta_title of page.

### ISSUE THREAD

**Issue by Dakror** [PrestaShop/PrestaShop#21378]
At: https://github.com/PrestaShop/PrestaShop/blob/b70d51837420275c5ad8c717162ddddb169e00d1/controllers/front/ProductController.php#L458

it needs to use $product['meta_title'] instead of $product['title']

**Comment by florine2623** [comment]
Hi @Dakror ,

Please follow the [improvement template](https://github.com/PrestaShop/PrestaShop/issues/new?template=2_feature_request.md) so we can get more details on what you need.
I close your issue, if you have more info feel free to open a new one.
Thanks!
