### ISSUE TITLE
GDPR module is not working for Ukrainian or Russian and this prevents PrestaShop from being installed using Ukrainian or Russian

### ISSUE THREAD

**Issue by githubitlive** [PrestaShop/PrestaShop#21374]
#### Describe the bug
prestashop_1.7.6.8
psgdpr1: Невозможно установить модуль "psgdpr",Длина свойства Tab->name составляет 70 симв. Должно быть между 0 и 64 симв.

https://www.prestashop.com/forums/topic/1028184-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-psgdpr1/

#### Expected behavior

Fix bug with russian lang. 4 month! Shame! What you do there?

#### Steps to Reproduce

Chose Russial lang-Next-Next-Installation-Bug...
Then delete prestashop and never use it.
Guys - Shop is a bisiness. Bisiness not a game. 

#### Additional information
English version install withou this bug...but you can not log in as admin!
My email/pass - error. Reinstall - write email/pass on paper. Try again - error!

Server admin/PHP developer/ about 5 years. Do you test you product?

**Comment by florine2623** [comment]
Hi @githubitlive 
Please follow the code of conduct when creating an issue : https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md
Thanks!

**Comment by matks** [comment]
@githubitlive Also the right place to submit a bug report is directly on the module https://github.com/PrestaShopCorp/psgdpr/issues/new as this module is not part of the OSS project

**Comment by evgenij-sobolev** [comment]
> 
> 
> @githubitlive Also the right place to submit a bug report is directly on the module https://github.com/PrestaShopCorp/psgdpr/issues/new as this module is not part of the OSS project

Hello!
psgdpr module is included in the standard prestashop installation package.
It is impossible to install prestashop if you choose Ukrainian or Russian language during installation.
Please do not close this issue!

**Comment by evgenij-sobolev** [comment]
This issue is described in more detail here:
https://github.com/PrestaShop/PrestaShop/issues/20519

**Comment by matks** [comment]
> > @githubitlive Also the right place to submit a bug report is directly on the module https://github.com/PrestaShopCorp/psgdpr/issues/new as this module is not part of the OSS project
> 
> Hello!
> psgdpr module is included in the standard prestashop installation package.
> It is impossible to install prestashop if you choose Ukrainian or Russian language during installation.
> Please do not close this issue!

That is a very valid reason to reopen the issue, thank you 😉 I also change the title of the issue then

**Comment by matks** [comment]
Well, actually, since https://github.com/PrestaShop/PrestaShop/issues/20519 is already open there is no need to keep 2 bug reports about the same thing, it would be a duplicate 🤔 ?
