### ISSUE TITLE
PHPStan GitHub Action fails since 07/10/2020 following GitHub Action upgrade of Virtual Env

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#21373]
#### Describe the bug

We have multiple PRs that are rejected by CI because our PHPStan GitHub Action is failing although the code is correct.

It seems these failures started to happen since 07/10/2020.
When I look at PRs that passed CI before, I notice that the **Virtual Environment** being used by GitHub runner has changed:
PRs that fail are running https://github.com/actions/virtual-environments/blob/ubuntu18/20201004.1/images/linux/Ubuntu1804-README.md
while PR that passed were running https://github.com/actions/virtual-environments/blob/ubuntu18/20200920.1/images/linux/Ubuntu1804-README.md

The new 20201004 image seems to be the root cause.

Here is a failing PR https://github.com/PrestaShop/PrestaShop/pull/21369
Here is a PR that passes when GA is run using Ubuntu 2004 instead of Ubuntu 1804 https://github.com/PrestaShop/PrestaShop/pull/21370
Here is a PR that passes when GA is run using Ubuntu 1604 https://github.com/PrestaShop/PrestaShop/pull/21371

**Comment by matks** [comment]
@PierreRambaud Here is the diff of what has been changed https://github.com/actions/virtual-environments/pull/1728/files

**Comment by matks** [comment]
Bug reported to GA https://github.com/actions/virtual-environments/issues/1773

**Comment by PierreRambaud** [comment]
> @PierreRambaud Here is the diff of what has been changed https://github.com/actions/virtual-environments/pull/1728/files

I don't understand why it's broken with these changes :sweat: 
Could be because of the Ubuntu version which is adding all the things without tests (a reason why Debian is more stable)

**Comment by matks** [comment]
Issue "fixed" in `develop` by using Ubuntu 20.04 instead of Ubuntu 18.04 => I close this issue
