### ISSUE TITLE
[Webservice] - Comma on filter value

### ISSUE THREAD

**Issue by pc3b3r** [PrestaShop/PrestaShop#21388]
#### Describe the bug

Using the [webservice filters](https://devdocs.prestashop.com/1.7/webservice/getting-started/#control-returned-items-with-filter)
it' not possible to get attributes (and other resources in general?!) containing comma in the name like `filter[name]=[42,2]`.
Is there a way to escape it?

#### Expected behavior

Retrieve the attribute named 42,2.

#### Steps to Reproduce

1. Create an attribute with value 42,2
2. GET req to `api/product_option_values?filter[name]=[42,2]`
3. No results

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @pc3b3r,

I did not manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/95723592-98d90b00-0c75-11eb-8984-a76abcbe84d5.png)

I used this link: `shop.com/api/product_option_values?display=full&filter[name]=42,2` and it is ok.

Thanks to check and feedback.

**Comment by pc3b3r** [comment]
@khouloudbelguith thanks for the answer, using it without square brackets is working fine. 
It was a strange case: normally I have multiple values to compare.

**Comment by khouloudbelguith** [comment]
@pc3b3r, thanks!
Feel free to open a new one when needed.
