### ISSUE TITLE
Issue with getting proper cover image, invalid cache key

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#21389]
#### Describe the bug

Ok, first of all, this is really tricky error and it's kinda hard to prepare entire scenario for test.

I'm asking @jolelievre to take a look at this Issue as He was working on implementation of getting custom cover 😎 

When we have a module where we need to get list of products, and we want to make sure that cover image is displayed in relation to chosen product attribute, **and** same product is in our cart, or any other module **before** ours, our cover cannot be used.

#### Expected behavior

We need to be able to alter cover image, individually for every module/mechanism using `Product::getProductProperties`, without racing condition 👎 

#### Steps to Reproduce

Entire test scenario is related to `blockwishlist` module where I wanted to add proper cover image displayed, for chosen combination. You need to have module installed from this branch: 
https://github.com/PrestaShop/blockwishlist/tree/new-module

This is how module looks by default:

![image](https://user-images.githubusercontent.com/2137763/95639886-78088e00-0a9a-11eb-92e7-2bef570d448e.png)

I wanted to make it a bit more clear for people, to look like this:
![image](https://user-images.githubusercontent.com/2137763/95639914-9078a880-0a9a-11eb-8579-6553288ac96a.png)

It's better to see chosen color, right? I've changed blockwishlist module, this is my file:
https://gist.github.com/kpodemski/7567a9ac574ff2c4a484f176e691a1ac

This is part of the code where I'm forcing `Product::getProductProperties` to display my cover instead of default one.
https://gist.github.com/kpodemski/7567a9ac574ff2c4a484f176e691a1ac#file-wishlistproductsearchprovider-php-L177

This is code where it's happening:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5569

Logic is simple, if we don't provide `cover_image_id`, PrestaShop will handle this and display cover selected by merchant (without taking care of combination images etc.)

Now, this is how wishlist product list is looking after my modification:
![image](https://user-images.githubusercontent.com/2137763/95639914-9078a880-0a9a-11eb-8579-6553288ac96a.png)

This is same product but with different combinations, now, lets add this product to cart, refresh... and...

![image](https://user-images.githubusercontent.com/2137763/95640164-ba7e9a80-0a9b-11eb-9513-f32e0d873372.png)

Complete mess, why? Because by default cover is black, and cached version from `Product::getProductProperties` is getting only first needed result from the page, `Cart` is first, so we're looking at black cover instead of our selected one.

PR to follow 😎 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for your report.
I think your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/12241 which fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/15748, it is fixed in the PS1770.
Is it similar?

I tried with the module, but it is not compatible with PS1.7 yet.
In the FO, we are blocked, we can't click on some links.

Thanks to check and feedback.

**Comment by kpodemski** [comment]
Hey @khouloudbelguith 

This issue is not related I think because I've tested it on 1.7.7.

> I tried with the module, but it is not compatible with PS1.7 yet.
In the FO, we are blocked, we can't click on some links.

It's because you need to run:
`composer install`
`yarn`
`yarn run build`

in module folder, to make module ready to use.

**Comment by khouloudbelguith** [comment]
@kpodemski, Great!
I manage to reproduce the issue with 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/95755654-f8024400-0ca4-11eb-9fe0-147dc6b2ebb1.png)

It was ok with PS1768
![image](https://user-images.githubusercontent.com/16067358/95755727-09e3e700-0ca5-11eb-9ab5-29117837cab9.png)

I’ll add this to the debug roadmap.


Thanks!

**Comment by Progi1984** [comment]
Fixed by #21390
