### ISSUE TITLE
[BO] [Modules] Confirmation of changes message is not displayed 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21381]
#### Describe the bug

On module contactform and ps_shoppingcart, when I switch the toggles to YES / NO then click save, I don't have the confirmation message on top 

#### Expected behavior

A confirmation message as follow "The settings have been successfully updated."
![Capture d’écran 2020-10-09 à 14 41 08](https://user-images.githubusercontent.com/69145330/95584199-95f3d580-0a3d-11eb-9f5a-475d4fb82303.png)

#### Steps to Reproduce

1. Search for contactform & ps_shoppingcart
2. Switch the toggles YES / NO
=> The confirmation message doesnt appear

#### Additional information

* PrestaShop version: 1.7.8.x & 1.7.7.x
* PHP version: 7.2

**Comment by kpodemski** [comment]
I can handle this.

**Comment by kpodemski** [comment]
@ngodefroy done 👍
