### ISSUE TITLE
FO - The product meta-title is incorrect after changing a combination

### ISSUE THREAD

**Issue by Dakror** [PrestaShop/PrestaShop#21391]
#### Describe the bug

the automatic page reload on product detail pages causes the meta title to get replaced with the product name

Issue is this line:
https://github.com/PrestaShop/PrestaShop/blob/b70d51837420275c5ad8c717162ddddb169e00d1/controllers/front/ProductController.php#L458

it needs to use $product['meta_title'] instead of $product['title']

#### Expected behavior

meta title should stay as it is

#### Steps to Reproduce

1. Have a product with a meta title != its name
2. Go to that product's front page
3. Either wait for the initial reload or change a combination or the quantity to cause one

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by kpodemski** [comment]
Hey @Dakror 

makes sense! I've created a PR: https://github.com/PrestaShop/PrestaShop/pull/21394

thanks!

**Comment by khouloudbelguith** [comment]
Hi @Dakror,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8 and 1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/95737208-9bdcf700-0c87-11eb-8e07-d76f1fdac456.png)
![image](https://user-images.githubusercontent.com/16067358/95737226-a1d2d800-0c87-11eb-8e74-aecd4f18b06f.png)
I’ll add this to the debug roadmap.
Thanks @kpodemski for the fix:slightly_smiling_face: 

Thank you!
