### ISSUE TITLE
PS 1.7.5.2 upgrade with module 1 Click Upgrade to 1.7.6.8

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#21392]
#### Describe the bug
1 Click U pgrade (latest version), SP 1.7.5.2 with custom modules, but not caused this problem.
I have upgraded localy my prestashop from 1.7.5.2 to 1.7.6.8 (current) version and it look like all finished with success (prestashop works after that) but with one error:
**Error during database upgrade. You may need to restore your database.
Masz już wersję 1.7.6.8.**

#### Expected behavior

I want to know if i can do some database check if all needed updates are processed on my DB. All frontend action are done with success.

#### Steps to Reproduce

Upgrade PS from 1.7.5.2. to 1.7.6.8

**Screenshots**

![obraz](https://user-images.githubusercontent.com/11571787/95679276-f9167100-0bd1-11eb-83a0-08500631d9af.png)
![obraz](https://user-images.githubusercontent.com/11571787/95679295-16e3d600-0bd2-11eb-93c3-8333ef698734.png)

#### Additional information

PS 1.7.5.2
PHP 7.2

Any ideas here?

**Comment by khouloudbelguith** [comment]
Hi @madkot,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.2 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1SOtkVYMxHbqxqOqutxyJFhccA2L1GjTQ/view?usp=sharing

In the BACKUP OPTIONS, did you disable "Back up my images"?
In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```
Thanks to check & feedback

**Comment by madkot** [comment]
My bad.. (i restore my local DB from my production) and i have other problem.
![obraz](https://user-images.githubusercontent.com/11571787/95788955-d8870d80-0cdc-11eb-936c-fd7d580a137c.png)

**Comment by khouloudbelguith** [comment]
@madkot, can you provide me the log file.
You can find it into `/PrestaShopFolder/admin-dev/autouprade/tmp/log.txt`.

Thanks!

**Comment by madkot** [comment]
@khouloudbelguith thanks for answering my problem, here is log file:
[log.txt](https://github.com/PrestaShop/PrestaShop/files/5371674/log.txt)

**Comment by khouloudbelguith** [comment]
@madkot, have you any custom modules?
The upgrade of Database => ok
The upgrade process is stopped when upgrading the Addons modules.

Thanks to check and feedback.

**Comment by madkot** [comment]
@khouloudbelguith yes, i have a few custom modules, can i check with one is problem?
The upgrade process is stopped when upgrading the Addons modules. - What is exactly mean? presta try to upgrade official modules?

**Comment by khouloudbelguith** [comment]
@madkot, here's my log file during the upgrade from PS1752 to PS1768
[log.txt](https://github.com/PrestaShop/PrestaShop/files/5372143/log.txt)
You can check the section `Database upgraded. Now upgrading your Addons modules... ` in my case.
Thanks to check and feedback.

**Comment by madkot** [comment]
@khouloudbelguith actualy i have no idea how to solve this problem, i check option to disable all non-included modules and problem  with cacheCore still exists.

UPDATE:
i put some logs into module core and i found that it stoped after
modules/autoupgrade-nienienie/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php->doUpgrade in method $this->generateHtaccess(); (i put log after this method and this log are not logged.)

**Comment by khouloudbelguith** [comment]
@madkot, did you make a new upgrade?
If yes, can you please provide me the new log file generated?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @madkot ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
