### ISSUE TITLE
I install newest version of prestashop two times and get same bug with field (CLEAR prestashop)

### ISSUE THREAD

**Issue by loco378** [PrestaShop/PrestaShop#21393]
![Screenshot_8](https://user-images.githubusercontent.com/72695838/95679592-85c62c80-0bdc-11eb-8d89-f92ce1537609.png)

**Comment by SimonGrn** [comment]
Dear @loco378 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 
Thank you

**Comment by matks** [comment]
@loco378 The last time I saw this kind of display errors, the php version used was wrong. If you use PS 1.7.6 you must php7.1 or php7.2 ; not php7.3 or php7.4
