### ISSUE TITLE
Changing access in AdminAccess gives false positive while ajax really results in 500 error with exception

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#21418]
I had a problem with a module admin controller that i got "no access" for. (even for SuperAdmin)
I found in AdminAccess that the module admin controller was not checked.
When I checked all boxes, I got "Settings updated", but when refreshing the page, the checkboxes are still unchecked.

So I researched some more and found that the ajax calls to `action=updateAccess` results in 500 Uncaught exception where `ROLE_MOD_TAB_DEFAULT_CREATE`, `ROLE_MOD_TAB_DEFAULT_READ`, `ROLE_MOD_TAB_DEFAULT_UPDATE`, `ROLE_MOD_TAB_DEFAULT_DELETE` was not found in the `ps_authorization_role` table.

After creating the roles manually in the database, I was able to save AdminAccesses roles as well as accessing the module admin controller with SuperAdmin.

```
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_DEFAULT_CREATE');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_DEFAULT_READ');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_DEFAULT_UPDATE');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_DEFAULT_DELETE');

INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_ADMINSTBLOG_CREATE');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_ADMINSTBLOG_READ');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_ADMINSTBLOG_UPDATE');
INSERT INTO `ps_authorization_role` (`id_authorization_role`, `slug`) VALUES (NULL, 'ROLE_MOD_TAB_ADMINSTBLOG_DELETE');
```

**I see two, possible three issues:**

1. When the ajax-call fails, we get false positive. 
2. When a role is not found, we should get a clear error message for this, and event better, the roles should be created. (autoheal)
3. Why the roles was not created in the first place I dont know. I can see that one of the roles that was not created was actually the `DEFAULT` tab. I belive this is the main admin menu aka "no parent". Should'nt there be roles for `DEFAULT`?

**Comment by SimonGrn** [comment]
Dear @onklmaps 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
