### ISSUE TITLE
Cache clear issue after optimization

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#21413]
#### Describe the bug

The way PrestaShop clears Symfony cache has been modified by this PR https://github.com/PrestaShop/PrestaShop/pull/20942

Although it is more performant, it also doesn't clear everything we need because the container is not rebuilt.
Among the things that I fear might be involved:
- Symfony routing updated
- Doctrine entities management
- Module's services updated

At least the routing has been proved to be failing with the module `ps_linklist` the other two remain to be confirmed, `productcomments` which uses both seemed to be fine but it's hard to tell if it's because the container was fully rebuilt after its installation.

The `Cache clear` feature is also impacted since it relies on the same method `SymfonyCacheClearer::clear`

#### Expected behavior

The Symfony cache should be completely cleared to ensure the container is correctly rebuilt with up to date information. However we must keep in mind that these two issues are still correctly handled:
https://github.com/PrestaShop/PrestaShop/issues/20852
https://github.com/PrestaShop/PrestaShop/issues/11105

#### Steps to Reproduce

Steps to reproduce the behavior (bug for routing at least):

1. Go to Module Manager
2. Uninstall `ps_linklist`
3. Remove the cache manually: `rm -fR ./var/cache/*`
4. Go to Module Catalog
5. Refresh the page so that the menu is updated (this should be handled by MBO)
6. Click on Design > LinkWidget
7. See the error from screenshot, the url should be managed by Symfony router via the `_legacy_link` property but since the Router info were not updated it tries to access the legacy controller which does not exist any more

**Screenshots**

![Capture d’écran 2020-10-13 à 12 31 01](https://user-images.githubusercontent.com/13801017/95851809-13c42380-0d53-11eb-9576-55bd161ef3f1.png)

#### Potential solution

We need to revert the command used back to `cache:clear` however it cause some issues because the memory limit was reached So one possibility is to dynamically force the memory_limit when we perform this command

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I manage to reproduce the issue with develop branch
![image](https://user-images.githubusercontent.com/16067358/95852664-68b46980-0d54-11eb-9c61-767c5ca4533f.png)
I’ll add this to the debug roadmap.

Thanks!
