### ISSUE TITLE
Error update with module autoupgrade

### ISSUE THREAD

**Issue by thierry-laval** [PrestaShop/PrestaShop#21414]
Do you have any idea about this error ?
I try to update my version 1.7.6.5 with the official module .

Ajax / Server Error for action upgradeDb textStatus: error  errorThrown:Service Unavailable  jqXHR

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @thierry-laval,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report in the next time
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

What is the exact version of the module 1-click upgrade did you use?
Did you try to make an upgrade from PS1.7.6.5 to PS1768?
Thanks to provide us the log file into `/Prestashop_Folder/autoupgrade/tmp/`

Thanks!

**Comment by thierry-laval** [comment]
Ok, understand, i see for give a new forulation more complete 👍 
And first i try to update directly from my ftp.
Thank, have a good day and i will comeback with new info...

**Comment by khouloudbelguith** [comment]
@thierry-laval, thanks!
Waiting for your feedback.

**Comment by thierry-laval** [comment]
Hi

Here I have just tried again and it does not work. Always the same mistake
Version du module Autoupgrade the last one
Upgrade Prestashop from 1.7.6.5 to 1.7.6.8
[Ajax / Server Error for action upgradeFiles] textStatus: "error " errorThrown:" " jqXHR: " "

**Comment by khouloudbelguith** [comment]
@thierry-laval,

 Unfortunately, there is not enough information provided to reproduce it and work on it.
What is the exact version of the module 1-click upgrade did you use?
Thanks to provide us the log file into `/Prestashop_Folder/admin-dev/autoupgrade/tmp/`

Thanks!

**Comment by thierry-laval** [comment]
1-Click Upgrade
v4.10.1 - par PrestaShop

i don't have the log because i install manually all the file of prestashop. I don't use the module.
Maybe it' a problem with Ionos... I don't know.

**Comment by khouloudbelguith** [comment]
@thierry-laval,

>i don't have the log because i install manually all the file of prestashop.

About Installing PrestaShop, you need to follow this link
http://doc.prestashop.com/display/PS17/Installing+PrestaShop+on+your+computer
What is the exact way did you use it?

> I don't use the module.

Are you using the 1-click upgrade module is it?
Did you install it from the BO > Modules > Module Catalog page? is it?

You can find the file into `/PrestaShop_Folder/admin_folder/tmp/`

Thanks!

**Comment by thierry-laval** [comment]
So.

I have the 1-click upgrade v4.10.1 module installed from the prestashop store.
from the BO> Modules> Module Catalog page

Thank you for the prestashop installation document, I know how to install it :-)

I used the 1-click upgrade update module like this one explains to do it.
And the ajax error arrived at the end ...
I had already had the same problem on another version of prestashop.

I also carried out tests on a version of prestashop installed locally via Mamp and your module works well.
Apparently it's a server update problem. This one does not seem to accept the work of your module.
But Ionos refuses to communicate on this subject ...

This "Ajax / Server Error for action upgradeDb textStatus: error errorThrown: Service Unavailable jqXHR" issue has been around for a long time and we find requests on the forums.
Check that by google.... :-)

After several attempts and replacing my store with the backups, I decided to install Prestashop directly by replacing the files in my directory.

I know where to find the log of your module (you are wrong).
/ PrestaShop_Folder / admin_folder / autoupgrade / tmp /
I no longer have the log of your module because I redid a clean installation by replacing my files as indicated above.
Which is an efficient method.
Thank you
Good day to you

**Comment by khouloudbelguith** [comment]
@thierry-laval, 

Thanks for these clarifications.

This error is unclear.
`Ajax / Server Error for action upgradeDb textStatus: error errorThrown: Service Unavailable jqXHR.`

However, the file `<admin folder>/autoupgrade/tmp/log.txt` should bring us more details. Can you please have a look at it?

If you don't have it.
Try to re-install the 1-click upgrade module and try to make the upgrade again.

Thanks!

**Comment by thierry-laval** [comment]
You joke with me ;-) I say that i update already but without your module and it's work...
I don't have time to downgrade again all my prestashop for try this module...
thank, have a nice day
