### ISSUE TITLE
Allow merchant to modify displayed fields in default forms

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#21410]
#### Is your feature request related to a problem?

I think there is not a single merchant who would utilize all the fields in Prestashop forms (adress, customer etc.). For example. Almost nobody uses gender, birthday, second adress, second phone number.

These fields are only bloating BO and FO fields.

#### Describe the solution you'd like

Allow merchant (without programming knowledge) to customize, what data he wants to collect and see in front office and backoffice forms.

#### Screenshot

![forms](https://user-images.githubusercontent.com/6097524/95839459-567dff80-0d43-11eb-953a-6893f17cca20.PNG)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

Thanks!

**Comment by juraj1000** [comment]
Hello,
I agree with @Hlavtox, usually the merchant would like to hide these fields. The fields like birthday, gender can also irritate the customers.
