### ISSUE TITLE
Prestashop 1.7 override form-fields.tpl 

### ISSUE THREAD

**Issue by Grazulex** [PrestaShop/PrestaShop#21424]
One of the customer ask me to change the layout of the "guest" form. I need to change the class of the field tag (col-md-6 to col-md-8) and of the comment  tag (col-md-3 to col-md-1).
My idea was to override the form-fields.tpl to change the class into this new version of form-fields.tpl and to extend or include this new tpl file into the themes/x/templares/checkout/_partials/steps/personnal-information.tpl but I don't fond the way to used this new form-fields.tpl (override) template file.
can somebody help me ?

JMS

**Comment by khouloudbelguith** [comment]
Hi @Grazulex,

On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!
