### ISSUE TITLE
Twig version upgrade throws exception

### ISSUE THREAD

**Issue by didacrios** [PrestaShop/PrestaShop#21427]
#### Describe the bug

Twig version upgrade cause an error entering to products list in backoffie

#### Expected behavior

No exception thrown

#### Steps to Reproduce

1. composer install (twig version install v2.13.1)
2. Enter backoffice
3. Go to catalogue > Products

**Screenshots**

![image](https://user-images.githubusercontent.com/211009/95879022-30258780-0d76-11eb-89f9-e9e6dd6127a2.png)

#### Additional information

* PrestaShop version: 1.7.4.1
* PHP version: 7.2.25
* Twig version in composer: "twig/twig": "^1.0||^2.0"

**Comment by khouloudbelguith** [comment]
Hi @didacrios,

I think your issue is similar to this ticket https://github.com/PrestaShop/PrestaShop/issues/17300. 

Thanks to check and feedback.

**Comment by didacrios** [comment]
Thanks @khouloudbelguith but I don't see they gave a solution in the other issue. 

We solved by limiting the use of version 1 of `twig` changing the composer to `"twig/twig": "^1.0"` otherwise the composer install or update will lead to this problem.

Would you that I open a Pull request?

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Unfortunately, we don't support Twig 2 yet as you can see here: https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json#L122

So if you use composer update you will update dependencies and the composer.lock file. The problem with this is, PrestaShop is an application which is working with specific dependencies and not a package.

**Comment by PierreRambaud** [comment]
I'm closing this issue since we have nothing to do here.
