### ISSUE TITLE
PROBLEME POUR ACHATS DE CERTAINS PRODUITS POUR STOCK+LIVRAISONS 

### ISSUE THREAD

**Issue by motosquads** [PrestaShop/PrestaShop#21421]
Bonjour,

Je rencontre un souci sur la majorité des produits de mon shop, lorsque l'on veut passer commande, il indique qu'il n'y a pas assez de produits en stock qu'il faut donc réajuster les stocks pour continuer, hors les stocks sont bien disponible.

de plus je rencontre un souci sur la livraison. 
En effet, quand d'autres produits "fonctionnes" le problème vient ensuite sur le mode de livraison, il indique qu'aucun transporteur n'est disponible, hors il y en a 3 différents de disponible,

Quelqu'un a déjà eu le cas ?? pouvez vous m'aidez svp j'ai tout essayé et rien a faire je désespère.....

Dans l'attente d'un retour,

Salutations

**Comment by khouloudbelguith** [comment]
Hi @motosquads,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
