### ISSUE TITLE
Activating AdminAccess roles gives false positive

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#21436]
#### Describe the bug

I go to Back office > AdminMyModuleController I get "No access", even for SuperAdmin.
![Screenshot 2020-10-14 at 10 56 30](https://user-images.githubusercontent.com/30602638/95966913-f43d0180-0e0b-11eb-883d-e9701c8f9ea3.png)
When I go to AdminAccess I see that the modules admin controller is unchecked, so I check all 4 checkboxes. I get green confirmation "Settings updated".

#### What happened
However, when I refresh the page, the checboxes are unchecked again. 
Further on I tried again, but this time I opened the js console, and noticed that the ajax calls get 500 error.
When I opened the ajax calls urls directly in the browser I got more clear input on what was wrong (while debug-mode is on).
It seems that the authorization role slugs are not found in the database.

#### Steps to Reproduce
It might be hard to reproduce since I don't know why the module admin controller authorization role slugs are not there in the first place, but I see two issues that are reproducable:

1. Delete some roles
2. Try to activate them in AdminAccess and observe that you get false positive. It should give a clear error-message what went wrong and with what module and what controller. 

#### Furthermore
Maybe there should also be some "autoheal" functionality here? If somehow an authorization role is non-exsistent in the database, why not just create it?

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

About the first step:
>Delete some roles

Are trying to delete some line from Database > table `ps_authorization_role` manually, is it?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
