### ISSUE TITLE
BO - Order - An exception displayed when removing a discount (gift)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21438]
#### Describe the bug

In the BO > Order detail page > when we try to delete a discount ( amount of a gift) => an exception is displayed

#### Expected behavior

Option 1:
Delete the gifted product after deleting the voucher
Option 2 ISO:
Keep the product

The option 1 is preferred but depending on the complexity the option 2 could be chosen.
 
#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page 
2. Create a cart rule "free gift "demo_6 60*90"
![image](https://user-images.githubusercontent.com/16067358/95971957-29e4e900-0e12-11eb-80c2-b596ba90e387.png)

3. Go to FO > Add demo_6 "40*60" to cart
4. Apply the discount
5. Continue checkout
6. don't close the Order_confirmation page
6. in the BO > Order detail page > delete the discount => exception
![image](https://user-images.githubusercontent.com/16067358/95971595-b511af00-0e11-11eb-813d-2991221fd702.png)
7. go back to the FO > Order confirmation page and reload the page => see error
![image](https://user-images.githubusercontent.com/16067358/95976972-8d721500-0e18-11eb-957f-ef7c69540851.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21447
