### ISSUE TITLE
Remove inline style on default datas descriptions

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#21441]
#### Is your feature request related to a problem?

On clean install of PS, default datas descriptions contains inline style.
For example: `<span style="font-size:10pt;font-style:normal;">...</span>`

#### Describe the solution you'd like

Please remove inline style on default datas :

- short description of products
- long description of products
- description of categories / manufacturers / suppliers

**Comment by sarahdib** [comment]
Hello @micka-fdz 

Thank you for your feedback!

@NeOMakinG could you check this :) Thank you

**Comment by micka-fdz** [comment]
I can make a PR if needed. I wait approval of @NeOMakinG.

**Comment by NeOMakinG** [comment]
@micka-fdz if you want to do it, go for it ! :)

Ping me if you prefer me to do it

**Comment by micka-fdz** [comment]
I'll make a PR soon.

**Comment by micka-fdz** [comment]
Hi @NeOMakinG, my PR is available.
