### ISSUE TITLE
Cart 

### ISSUE THREAD

**Issue by skrime** [PrestaShop/PrestaShop#21445]
Bonjour,

Je me rends compte que j'ai des soucis d'arrondi sur certaines commandes ce qui décalent de quelques centimes les prix réels.

Je suis Prestashop 1.7.6.5, règle d'arrondi  : Arrondir vers l'infini quand valeur à mi-chemin (recommandé) et type d'arrondi : Arrondir le total

ex de souci :

Produit A  - Prix unitaire HT : 3,38 - Prix unitaire TTC : 4.06 - Quantité commandée : 37 - Total HT : 125,06 - Total TTC : 150,22
Produit B  - Prix unitaire HT : 8,25 - Prix unitaire TTC :  8,70 - Quantité commandée : 1 - Total HT : 8,25 - Total TTC : 8,70

TOTAL PRODUITS HT : 133.38 (faux devrait être 125.06+88.25 = 133.31)
Produits : 158.86 (faux, devrait être 150.22+8.70 = 158.92)
Livraison : 0.00
Total HT  : 133.38
Total : 158.86

On a donc un souci d'arrondi au niveau du total qui semble illogique. Si quelqu'un a une idée...

Pour précision mon produit A a un prix de base de 4.57€ HT avec une réduction à 26%, ce qui donne 3.3818€ (donc bien mon 3.8€ affiché)

Merci d'avance !

**Comment by SimonGrn** [comment]
Hello,
Please send your request in English. English is the norm on GitHub.

Thank you
