### ISSUE TITLE
Help button doesn't work as expected in Create an order

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#21448]
#### Describe the bug

When I click on the "Help" button in Create an order, the help section is taking the whole page.

#### Expected behavior

The help section should slide from the right and not without covering the entire page.

#### Steps to Reproduce

1. Go to Create an order
2. Click on the "Help" button
3. See the help page taking the whole screen

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.3

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21467
