### ISSUE TITLE
Problem with ps_crossselling

### ISSUE THREAD

**Issue by DRFrank89** [PrestaShop/PrestaShop#21444]
Hello everyone, I am writing to you because I recently encountered an error similar to one that I had already encountered but solved thanks to this topic:

[https://github.com/PrestaShop/PrestaShop/issues/9652](url)

to see the problem: https://ibb.co/f8nV2LF

The crossseling module does not allow me to view the description and price of the products, these parameters are shown only for the first product.

I kindly ask if anyone has modified the following ps_crosselling.php file. to correct the problem.

Thank you

PHP: 7.2.34
PrestaShop: 1.7.6.8
Warehouse theme:  4.3.2
Language: italian

**Comment by SimonGrn** [comment]
Dear @DRFrank89 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
