### ISSUE TITLE
Prestashop unable to check server configuration for Friendly URL's

### ISSUE THREAD

**Issue by CTSol186** [PrestaShop/PrestaShop#21455]
#### Prestashop v1.6.1.24

Under the 'SEO & URL' section, trying to setup "Friently URL" for the domain - I see a message `URL rewriting (mod_rewrite) is not active on your server, or it is not possible to check your server configuration. If you want to use Friendly URLs, you must activate this mod.`

I am using other domains [most of them using WordPress], so am sure that the mod_rewrite is enabled BUT somehow Prestashop [the only Prestashop install on this server]is not able to check it from the server.

#### Expected behavior

The settings on that page are used to recreate the .htaccess in the root folder, which is not being generated due to the problem as stated above.

#### Steps to Reproduce

1. Go to 'Back end of your Prestashop Installation'
2. Click on 'Preferences' and then on 'SEO & URL'
3. Scroll down to 'SET UP URLS'

**Screenshots**

![image](https://user-images.githubusercontent.com/46317722/96086313-937cfa00-0edb-11eb-8a63-b20ba080455e.png)

#### Additional information

* PrestaShop version: 1.6.1.24
* Server information Linux #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64
* Server software version Apache
* PHP version 7.2.34

**Comment by florine2623** [comment]
Hello,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

If you need specific support, you can contact the[ support team](https://addons.prestashop.com/en/388-support) or a [partner agency](https://www.prestashop.com/en/experts).

Thank you

**Comment by CTSol186** [comment]
> Hello,
> PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
> Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.
> 
> If you need specific support, you can contact the[ support team](https://addons.prestashop.com/en/388-support) or a [partner agency](https://www.prestashop.com/en/experts).
> 
> Thank you

Thanks for the response, I will certainly consider that as well.

Actually, I have an old site which I will soon be upgrading to the latest build v1.7.6.8 as well, but am trying to make it work on the older version - as it should, I mean be able to auto generate .htaccess file.

**Comment by CTSol186** [comment]
Interesting I was able to upgrade it to v1.7.6.8 and the issue still remains .. even in this build I am unable to generate the .htaccess file.
