### ISSUE TITLE
PS_Faceted_Search - Filter is not displayed

### ISSUE THREAD

**Issue by kld1228** [PrestaShop/PrestaShop#21454]
#### Describe the bug

The Faceted Search is not displayed on the front store. None of the filter options are available for the customer to select. 

#### Expected behavior

I am expecting the Faceted Search filter options to appear on the front store.

#### Steps to Reproduce

1. Go to 'http://s845872027.onlinehome.us/128-in-stock/'
2. See error - Faceted Search is not displayed

**Screenshots**
![ProductPage](https://user-images.githubusercontent.com/72894409/96052786-3a19ba00-0e4c-11eb-96c7-862e78833a57.JPG)
![1Tempate](https://user-images.githubusercontent.com/72894409/96052787-3ab25080-0e4c-11eb-8b8e-1a10fc0b72ee.JPG)
![Database](https://user-images.githubusercontent.com/72894409/96052788-3ab25080-0e4c-11eb-8e68-2255c4931a48.JPG)
![Module](https://user-images.githubusercontent.com/72894409/96052789-3ab25080-0e4c-11eb-976b-1a4a9f6ab160.JPG)
![Positions](https://user-images.githubusercontent.com/72894409/96053658-edcf7980-0e4d-11eb-9d44-9278b3098aec.JPG)

#### Additional information
This issue has been reported several times on the PS Forums by other users.

This module used to work in July 2020 but I had to remove the module because the database table (ps_layered_filter_block) increased to 465mb automatically.

#### Attempted Troubleshooting Steps
* Clear cache (in Faceted Search module & Performances, & browser cache)
* Empty ps_layered_product_attribute table & rebuild attributes
* Delete ps_facetedsearch directory from Modules directory & reinstall using directory included in PS 1.7.6.8 zip file
* Verify Faceted Search appears in 8 hooks on Design > Position pages (including displayLeftColumn & changed position to #1)
* Create new filter templates
* Disable & reenable some products
* Use various combination of module settings

#### Versions
* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* PS_Faceted_Search version: 3.5 & 3.6

**Comment by florine2623** [comment]
Hi @kld1228 ,
I can't reproduce your issue using PS 1.7.6.7 and faceted module v3.5.0 and v3.6.0.
![Capture d’écran 2020-10-15 à 09 23 26](https://user-images.githubusercontent.com/16019289/96090277-417ea900-0ec8-11eb-8620-78f38b280b4c.png)
![Capture d’écran 2020-10-15 à 09 23 38](https://user-images.githubusercontent.com/16019289/96090282-43e10300-0ec8-11eb-90a0-15aa243d8a3a.png)

As you are not using PrestaShop classic theme, I suggest you to contact the developer of the theme you are using.
Of contact the support team : https://addons.prestashop.com/en/388-support
Thanks!
