### ISSUE TITLE
Two time actionAdminLoginControllerResetBefore

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21457]
#### Describe the bug

Since : https://github.com/PrestaShop/PrestaShop/pull/21435 There are two times << actionAdminLoginControllerResetBefore >>

#### Steps to Reproduce

Open : install-dev/data/xml/hook.xml

Check  how many times is present actionAdminLoginControllerResetBefore

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello @okom3pom 
could you add  a simple list of steps to reproduce ? We will need it when testing.
Thank you !

**Comment by Progi1984** [comment]
Fixed by #21458
