### ISSUE TITLE
INSTALL.txt instructions are wrong

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21463]
#### Is your feature request related to a problem?

Install.txt instructions are wrong, index.html don't exist 

#### Describe the solution you'd like

Install.txt instructions are wrong

#### Alternatives you've considered

Remove text or Change by index.php

**Comment by florine2623** [comment]
Hi @okom3pom ,
Thanks for noticing it !
I will put it in the debug roadmap.
Thanks
