### ISSUE TITLE
Reorder cart from history with deleted carrier

### ISSUE THREAD

**Issue by Ludhiel** [PrestaShop/PrestaShop#21465]
#### Describe the bug

When a customer try to reorder an old order with a carrier that had been deleted, the customer cannot select a new one. Instead the message "no carrier available" is shown.

#### Expected behavior

If carrier is not available, other carriers should show

#### Steps to Reproduce

Order made in 1.7.3
Upgrade Prestashop to 1.7.6
Delete and add carrier
Reorder from an 1.7.3 order with deleted carrier (from history or BO)
Cannot choose a new carrier

I do not know if the upgrade is important

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Ludhiel ,
Following your steps I couldn't reproduce your issue.
Order made with old carrier :
![Capture d’écran 2020-10-15 à 15 28 44](https://user-images.githubusercontent.com/16019289/96136347-0f873a00-0efc-11eb-952f-e1e92817e29d.png)
After the successful upgrade from PS 1.7.3.4 to PS 1.7.6.8 :
![Capture d’écran 2020-10-15 à 15 28 11](https://user-images.githubusercontent.com/16019289/96134440-8d971100-0efb-11eb-985c-d5e8d5aab7fe.png)
Reorder button available linking to order process with the same product as first order:  
![Capture d’écran 2020-10-15 à 15 34 30](https://user-images.githubusercontent.com/16019289/96135901-f3839880-0efb-11eb-913a-3867b17ebf01.png)

New carrier available :
![Capture d’écran 2020-10-15 à 15 36 18](https://user-images.githubusercontent.com/16019289/96136804-304f8f80-0efc-11eb-8b7f-5f12d818dab4.png)

I suggest you to check first if the update was complete and successful. You can also contact the [support-team](https://addons.prestashop.com/en/388-support) of a [partner agency](https://www.prestashop.com/en/experts) to fix your issue !
Thanks!
