### ISSUE TITLE
Bug in installation: ps-customtext1: cannot install module ps_customtext

### ISSUE THREAD

**Issue by Zonnepaneel** [PrestaShop/PrestaShop#21466]
The installation of Prestashop gets stuck. I get the error "ps-customtext1: cannot install module ps_customtext". And then I am unable to complete the installation.

**Comment by florine2623** [comment]
Hi @Zonnepaneel ,

We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

I'll close your issue for now, when you gather all details, feel free to open a new one.
Thanks
