### ISSUE TITLE
Not functioning hook AdminProductsMainStepLeftColumnBottom

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#21475]
#### Describe the bug

The hook AdminProductsMainStepLeftColumnBottom is not working.
According to the docs it should be located in: /src/PrestaShopBundle/Resources/views/Admin/Product/form.html.twig
But it's located in: Located in: /src/PrestaShopBundle/Resources/views/Admin/Product/PorductPage/Panels/essentials.html.twig

#### Expected behavior

When registering the hook in module like so:
$this->registerHook('displayAdminProductsMainStepLeftColumnBottom')

It should display whatever is return like so:
public function hookAdminProductsMainStepLeftColumnBottom(){
}

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @NKoonen ,

Indeed according to https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/, the location of the hook is incorrect.

Do you have any module on which we can test that ?
What are the steps to reproduce ?

Thanks!

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

The list of hooks in [devdocs](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/), regarding displayAdminProductsMainStepLeftColumnBottom is not up-to-date : 
It is supposed to be Located in: /src/PrestaShopBundle/Resources/views/Admin/Product/form.html.twig
But form.html.twig is not present : https://github.com/PrestaShop/PrestaShop/tree/develop/src/PrestaShopBundle/Resources/views/Admin/Product

Could you take a look please ?
Thanks!

**Comment by Progi1984** [comment]
Updated documentation : PrestaShop/docs#1077
