### ISSUE TITLE
I am unable to create a new account on your forum

### ISSUE THREAD

**Issue by Temepest74** [PrestaShop/PrestaShop#21474]
#### Describe the bug

I cannot create an account on your forum. I tried with multiple email adresses but I never get the confirmation email. I let it over night and canceled it. I try to open an account with the email: catalin@sendsms.ro but I cannot do that.
My forum will stay blocked in "Waiting aproval" state until i cancel my account creation.

**Comment by florine2623** [comment]
Hi @Temepest74 ,
I successfully created an account on the forum and received the confirmation email :
![Capture d’écran 2020-10-15 à 18 23 16](https://user-images.githubusercontent.com/16019289/96158251-a0b5db00-0f13-11eb-9f19-1e0e660e2fdd.png)

Please make sure your email address is valid and that you are able to receive email.

**Comment by SimonGrn** [comment]
This github repository is only for the PrestaShop solution. We cannot offer any help regarding the forum. You can howver contact forum@prestashop.com to get some help.
