### ISSUE TITLE
Wrong availability message on cart

### ISSUE THREAD

**Issue by soulardromain** [PrestaShop/PrestaShop#21477]
#### Describe the bug

If you want to display product availability in the cart, and show availability_message, it returns the wrong text. Like it always has the in-stock product, it doesn't show the message for available_later text. (#18225)

If the stock is 2 and quantity in cart is 1 or 2, it displays an "in stock" label instead "Last items in stock".
If the stock is 2 and quantity in cart is 3, it displays an "in stock" label instead "Label when out of stock".

#### Expected behavior

In cart show product availability when **out of stock** or **last items in stock** with the allowed order option.

#### Steps to Reproduce
> Edited by Khouloud

0. add these lines in `templates/checkout/_partials/cart-detailed-product-line.tpl`
```php
   {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
```
1. Create a product with quantity =2, Allow orders
![image](https://user-images.githubusercontent.com/16067358/97326110-f2475980-1873-11eb-9e63-79cf33b30b1a.png)
2. In the FO, Add the product to the cart and Go to the cart page
We have different availability label
2.1 Quantity product =2, quantity in the cart =1
2.1.1 Product details page
![image](https://user-images.githubusercontent.com/16067358/97326400-42262080-1874-11eb-9916-2b4bca189d9f.png)
2.1.2 Cart page
![image](https://user-images.githubusercontent.com/16067358/97326463-51a56980-1874-11eb-9524-2ac0d35b2689.png)
2.2 Quantity product =2, quantity in the cart =2
2.2.1 Product details page
![image](https://user-images.githubusercontent.com/16067358/97326585-6da90b00-1874-11eb-9040-40cf84f02375.png)
2.2.2 Cart page
![image](https://user-images.githubusercontent.com/16067358/97326615-77327300-1874-11eb-8db1-fadea1154692.png)

------------------------------------------------------------------------------------------------
Add product with 2 quantity, select Allow orders.
Set Label when out of stock.
Add
```
{block name='product_availability'}
  <span id="product-availability">
    {if $product.show_availability && $product.availability_message}
      {if $product.availability == 'available'}
        <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
      {elseif $product.availability == 'last_remaining_items'}
        <i class="material-icons product-last-items">&#xE002;</i>
      {else}
        <i class="material-icons product-unavailable">&#xE14B;</i>
      {/if}
      {$product.availability_message}
    {/if}
  </span>
{/block}
```
in `templates/checkout/_partials/cart-detailed-product-line.tpl`

#### Additional information

PrestaShop version: 1.7.6, 1.7.7, develop

**Comment by florine2623** [comment]
Hello @soulardromain ,
This has been added in PS 1.7.8 as said in the issue you mentioned.
So I'll close your issue.
Thanks!

**Comment by soulardromain** [comment]
Hello @florine2623,
The issue #18225 is incomplete (fix when the stock is **0**):
If the stock is **2** and quantity in cart is **1 or 2**, it displays an "in stock" label instead "Last items in stock".
If the stock is **2** and quantity in cart is **3**, it displays an "in stock" label instead "Label when out of stock".

**Comment by marionf** [comment]
@hibatallahAouadni @khouloudbelguith 
I think this issue needs to be reproduced, qualified and specify in the top of the issue the steps to reproduce it

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I followed these steps with 178 (develop branch) and 1768:
0. add these lines in `templates/checkout/_partials/cart-detailed-product-line.tpl`
```php
   {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
```
1. Create a product with quantity =2, Allow orders
![image](https://user-images.githubusercontent.com/16067358/97326110-f2475980-1873-11eb-9e63-79cf33b30b1a.png)
2. In the FO, Add the product to the cart and Go to the cart page
We have different availability label
2.1 Quantity product =2, quantity in the cart =1
2.1.1 Product details page
![image](https://user-images.githubusercontent.com/16067358/97326400-42262080-1874-11eb-9916-2b4bca189d9f.png)
2.1.2 Cart page
![image](https://user-images.githubusercontent.com/16067358/97326463-51a56980-1874-11eb-9524-2ac0d35b2689.png)
2.2 Quantity product =2, quantity in the cart =2
2.2.1 Product details page
![image](https://user-images.githubusercontent.com/16067358/97326585-6da90b00-1874-11eb-9040-40cf84f02375.png)
2.2.2 Cart page
![image](https://user-images.githubusercontent.com/16067358/97326615-77327300-1874-11eb-8db1-fadea1154692.png)

I’ll add this to the debug roadmap.

Thanks!

**Comment by kpodemski** [comment]
I've tested it and created PR.

The problem was with `quantity_wanted` properly which was not read properly by `ProductLazyArray`
