### ISSUE TITLE
Prestashop 1.7.5.2

### ISSUE THREAD

**Issue by bonneva** [PrestaShop/PrestaShop#21489]
Hello,

Via the OVH host, I just installed the Prestashop module. It was done easily, version 1.7.5.2

But when I look in "Advanced settings" "Information" of the installation I just did, at the very bottom of the page there is a section called "List of modified files" and with the following written:

Changes to your files have been detected.

Missing files (3)

.eslintrc.js

.eslintignore

.php_cs.dist

 
How is it possible ?
What does that mean ?
Is it a problem ?

What should be done ?

Hoping someone can answer me. cordially

**Comment by SimonGrn** [comment]
Hello, 
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I can however tell you that this is not really a problem, these files are not important (these are mainly dev files).

Thank you
