### ISSUE TITLE
Admin Panel - cannot reach some properties

### ISSUE THREAD

**Issue by DesantBucie** [PrestaShop/PrestaShop#21486]
#### Describe the bug

I'm using prestashop on mac XAMPP VM. When i use admin and i try to add product, form is bugged, i need to downscale my browser window in half or something like that.

#### Expected behavior

I've expected it to be reachable :)

#### Steps to Reproduce

1. Open admin panel and log in
2. Try to add product

**Screenshots**
<img width="1440" alt="Screenshot 2020-10-17 at 01 02 31" src="https://user-images.githubusercontent.com/46130107/96321146-a9420a80-1014-11eb-899c-1111dafba8a1.png">
<img width="1440" alt="Screenshot 2020-10-17 at 01 04 32" src="https://user-images.githubusercontent.com/46130107/96321184-c2e35200-1014-11eb-9aed-5d53da99f489.png">

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7
* Language is polish, but I think it doesn't change much in layout

**Comment by kpodemski** [comment]
Hello,

you are probably using PHP 7.4, this version is not compatible with it, PrestaShop 1.7.6.8 supports up to PHP 7.2.

More informations: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by DesantBucie** [comment]
Oh yes, my bad I had php 7.2 on my hosting while 7.4 on my computer. Thanks and sorry for taking time on such easy fix
