### ISSUE TITLE
Today my page is showing up with an HTTP 500 error and I can't access the Prestashop my admin page 

### ISSUE THREAD

**Issue by smcgcustoms** [PrestaShop/PrestaShop#21487]
This evening I went to check on some new customer orders to find my Prestashop admin page and website doesn't come up.  It is receiving an HTTP 500 error code.  The hosting provider is up and did their check and they seem to think that my files may not be directing properly today for some reason.  
Sounds like a permission/redirect issue?

**Comment by SimonGrn** [comment]
Dear @smcgcustoms 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by matks** [comment]
> This evening I went to check on some new customer orders to find my Prestashop admin page and website doesn't come up. It is receiving an HTTP 500 error code. The hosting provider is up and did their check and they seem to think that my files may not be directing properly today for some reason.
> Sounds like a permission/redirect issue?

If it is a permission/redirect issue, only the hosting provider can tell you.
They might for example compare the current state of your shop with a backup done some hours/days ago if they believe something changed in the files.

But there is nothing we can do for help 🤔 on this repository.

If you need further help with your shop, please consider the PrestaShop Company support plans: https://www.prestashop.com/support
