### ISSUE TITLE
Error from import due to Quantity column in Prestashop Multishop

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21480]
Hi, i would like to warn you about an error.
I have a multishop. Quantity are merged between 2 shop. When I try to import a CSV from Mulstihop, I got an error : 
<img width="761" alt="Capture d’écran 2020-10-16 à 16 45 50" src="https://user-images.githubusercontent.com/43704805/96276053-cd7cf780-0fd2-11eb-8d68-446f382f394d.png">
After many try, I realized it comes from quantity, if I remove quantity column, it works : 
<img width="891" alt="Capture d’écran 2020-10-16 à 16 47 15" src="https://user-images.githubusercontent.com/43704805/96276109-de2d6d80-0fd2-11eb-9403-5ad94d562f6a.png">

**Comment by florine2623** [comment]
Hi @passio777x ,
Please follow the template of bug with the steps to reproduce and the version of PS you are using.
When all details are available, feel free to open a new issue.
Thanks!
