### ISSUE TITLE
Error after update welcome module

### ISSUE THREAD

**Issue by oliwier93** [PrestaShop/PrestaShop#21496]
![Error](https://user-images.githubusercontent.com/52152331/96443464-ed97fb00-120c-11eb-8aff-12ebecff2c69.png)

Version of prestashop: 1.7.6.7
Language: Polish
Cause: After update welcome module.

Can you help me fix it?

**Comment by khouloudbelguith** [comment]
Hi @oliwier93,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached a screen record
https://drive.google.com/file/d/1J_ggvR2JK5RpiCKy8GykjQL2BFdD-s_o/view?usp=sharing

Thanks to check and feedback.

**Comment by oliwier93** [comment]
I can't even disable this module. It's not listed. Trying upgrade to PHP 7.2 and 1.7.6.8 atm.

**Comment by oliwier93** [comment]
Issue dissapeard after update. Can be closed.
