### ISSUE TITLE
Webservice - Enable key by hosts name or IP

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21493]
## Is your feature request related to a problem?

Improve the security of Web Services. In some cases a key is not enough to secure access to the API. It would be interesting to have the possibility of limiting accesses by IP address or Domain name.

See : https://devdocs.prestashop.com/1.7/webservice/getting-started/
![Capture du 2020-10-19 00-49-15 (1)](https://user-images.githubusercontent.com/16455155/96387824-36b46480-11a5-11eb-8a71-976a9c19fcf5.png)

## Describe the solution you'd like

- Ability to enable or disable host or IP check.
- When verification is enabled, only declared IPs and hosts can access the API for this key.

![image](https://user-images.githubusercontent.com/16455155/96387856-7bd89680-11a5-11eb-8ea6-ff8a8ecfd2b0.png)

## Specs
**Form**
A toggle "**Host check**" is displayed at the end of the form. By default, the toggle is disabled. 
If enabled, a text area "**Host allowed**" is displayed to enter all the allowed IPs. They must be split by a comma. 

If the user has enabled the "**Host check**" and saves the form without entering any IP, then an error is thrown, the user stays on the current page and the saving is canceled. 

After been saved when the user edits the web service key from the list, all the information (list of IPS allowed and the saved configuration) must be displayed.

If the text area contains URLs and the user disables the "**Host check**", on the reactivation of the "**Host check**" the old URLs are displayed again in the text area. (Bonus, if it can't be done: the text area is cleared each time it is deactivated)

**List**
The list displays the "Check Host" status (enabled or disabled). It can't be edited from the list, since it has to add the URL to save the changes.

**Missing wording or wording to be challenged:**
- Host check is it enough explicit
- small text bellow the toggle "Host check"
- small text bellow the text is "Host allowed" if needed

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

Thanks!

**Comment by MatShir** [comment]
Hi @PululuK,
For a better understanding, I suggest exchanging to the two new input and display hosts allowed when the toggle of "host check" is enable. What do you think?

**Comment by PululuK** [comment]
> Hi @PululuK,
> For a better understanding, I suggest exchanging to the two new input and display hosts allowed when the toggle of "host check" is enable. What do you think?

Hi @MatShir 
if I understood correctly you want **Enable hosts check** input to be displayed before **Hosts allowed**, right ?

**Comment by MatShir** [comment]
Yes, It will make more sense, then we could add some wording below the toggle "**Host check**" to explain the feature. 
Because If the user adds a list of the URL but doesn't activate the "**Host check**", the user will be confused why it didn't work or why he has to add the URL.

**Comment by PululuK** [comment]
> Yes, It will make more sense, then we could add some wording below the toggle "**Host check**" to explain the feature.
> Because If the user adds a list of the URL but doesn't activate the "**Host check**", the user will be confused why it didn't work or why he has to add the URL.

I agree with you ! Thank you very much @MatShir .

**Comment by MatShir** [comment]
I edit the first post with the explicit behavior to follow for the QA and the core dev review. The specs must be followed for the PR to be merged. The specs can be challenged :)

The last thing I wondering is, should we display the list of IPs allowed on the web service list page. I don't really know the usual quantity of URL saved so can't tell if it would fit into the list. But we could at least, display the "Check Host" is enabled or disabled from the list (It can't be edited from the list, since it has to add the URL to save the changes)

What do you think @PululuK or @PrestaShop/prestashop-core-developers if you have more insight to share?

**Comment by PierreRambaud** [comment]
Watch out with the Host check, how do you plan to retrieve the Host?

**Comment by PululuK** [comment]
> Watch out with the Host check, how do you plan to retrieve the Host?

@PierreRambaud  can you see please https://github.com/PrestaShop/PrestaShop/pull/21494/files#diff-88589a528aa8ebde652694f792599830573ca95dc95589e38f3a537ba6e523a1

**Comment by PierreRambaud** [comment]
> > Watch out with the Host check, how do you plan to retrieve the Host?
> 
> @PierreRambaud can you see please https://github.com/PrestaShop/PrestaShop/pull/21494/files#diff-88589a528aa8ebde652694f792599830573ca95dc95589e38f3a537ba6e523a1

It's because you can manipulate HTTP headers in order to change the `X Forwarded For`

**Comment by PululuK** [comment]
> It's because you can manipulate HTTP headers in order to change the `X Forwarded For`

Do you have any suggestions?

**Comment by PierreRambaud** [comment]
Use another system to be able to connect through the API :sweat_smile: 
This one is not secure and using Host will not be more secure :/

**Comment by MatShir** [comment]
It means the "hacker" need the key and the IP, is it not more secure?

@PierreRambaud Are you suggesting to close this improvement?

**Comment by PierreRambaud** [comment]
The IP will always be 127.0.0.1, or the domain name, this is something you can easily spoof. So there is not really any benefits on it.
I'm more in favor of doing #14889 and #11053

**Comment by PierreRambaud** [comment]
X-Forwarded-For HTTP header should not be used for any Access Control List (ACL) checks because it can be spoofed by attackers. Use the real IP address for this type of restrictions.
But if the visitor is using a proxy, the REMOTE_ADDR field will contain the address of the proxy instead of the visitor. To be able to see the address of the visitor, many proxies add a header to the request with this address.
It's the same with the Host header, we can't trust it since you can easily spoof it.

I'm sorry but I'm against adding code/complexity for something that is not a security improvement.

**Comment by PululuK** [comment]
@PierreRambaud you are against the idea in itself, or the solution proposed in PR?

**Comment by PierreRambaud** [comment]
The idea itself :sweat_smile:

**Comment by MatShir** [comment]
@PierreRambaud @PululuK since there is no long term viable solution here. I suggest closing this issue. The specs will be updated. Don't hesitate to exchange on the slack open-source and create a new issue if you have a new idea. Cheers! :)

**Comment by PululuK** [comment]
ping @PrestaShop/prestashop-maintainers

**Comment by kpodemski** [comment]
I see no benefit to using this security layer after reading Pierre's response, as the attacker can easily omit it.

There's an ongoing discussion about the new PrestaShop API, so it's probably something to handle then.

cc @eshraw @MatShir

**Comment by PululuK** [comment]
> I see no benefit to using this security layer after reading Pierre's response, as the attacker can easily omit it.

@kpodemski you assume that the attacker knows the IP address ? How then ?
