### ISSUE TITLE
Bug on "reset url" button of the product pages when "Accented URLs" is enabled and there are special characters in the product name

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#21495]
Hi
I've inderstood the reason of this problem and it is possible to reproduce it
it is present in all prestashop 1.7 versions

![1](https://user-images.githubusercontent.com/653230/96386842-382e5e80-119e-11eb-8e12-703ea4389172.png)

it happens when it is active the option "Accented URLs"
when this option is active the function
Tools::link_rewrite
works well with special characters removing it excepts accented characters, instead from the product page pushing on the button "reset url" from seo tab, it does not work adding the special characters like quotes or ² or ³ ...

so to reproduce it following this steps:
1) active the option "Accented URLs"
2) go in an admin product page and set a name like:

Pantalon de travail multipoches en T/C canvas 260 g/m², empiècements en Oxford, gris - Beta 7900E

3) push on the "reset url" button

this problem is not present with disabled the option "Accented URLs", the "reset url" button remove the special characters

![2](https://user-images.githubusercontent.com/653230/96387066-d40c9a00-119f-11eb-8dc8-c9017f1706a3.png)
![3](https://user-images.githubusercontent.com/653230/96387068-d53dc700-119f-11eb-8e30-4e79f87c2cdd.png)

it is a javascript bug, the "reset url" button active a javacript cleaning, it should use an ajax solution to use Tools::link_rewrite

bye

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8 and 1770rc1build2.
![image](https://user-images.githubusercontent.com/16067358/96429085-d3f0b680-1200-11eb-8e1c-4c5e1fe3ff9b.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Maofree** [comment]
thanks

**Comment by Betafer** [comment]
' in product name also cause url rewrite problem

**Comment by AlexTechDev** [comment]
I'm working on it :)

**Comment by davidglezz** [comment]
@AlexTechDev What is the status of this? can I help with something?

**Comment by AlexTechDev** [comment]
> @AlexTechDev What is the status of this? can I help with something?

@davidglezz  It's done :) I will update the pull request in a few days
