### ISSUE TITLE
error when adding a product to the cart and closing the ajax menu

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#21492]
#### Describe the bug

When I add a product to the cart from the home page and close the ajax menu there is a url change that should not happen.
The url that is put has nothing to do with the url of the product added to the cart

#### Expected behavior

Close the menu without changing the url

#### Steps to Reproduce

See the video

**Screenshots**

https://youtu.be/7ag1YoJ_tNk

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.34

**Comment by SimonGrn** [comment]
Hello,

I'm not able to reproduce using the Classic Theme with the 1.7.6.4 version. This is probably related to the theme you're using so I suggest you contact the theme developer directly.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you for your understanding.
