### ISSUE TITLE
BO - Order page - When we update a product quantity, the gift product is not added to the order

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21501]
Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)

#### Describe the bug

When we have an old order, we try to update a quantity's product which has a specific discount, the Gift product is not added to the order

#### Expected behavior

1/ If the cart rule specifically applies a reduction on a product, it uses the rule defined for when the product is added in the order. 2/ If the cart rule adds a free gift to the order
[Spec](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/orders/orders/Order%20Page%20View.md)

#### Steps to Reproduce

0. Create an order that contains the demo_6 product
1. Create a cart rule 
1.1 Informations: without code
1.2 Conditions: Product selection demo_6
1.3 Actions: Free shipping + discount amount = 1euro tax included + Free gift (demo_11)
2. In the BO > Order page > View the last order created
3. Update the quantity's product
4. see the error, the discount is applied but the gift product is not added

**Screenshots**

https://drive.google.com/file/d/1D45x6Y1finlS9zftEZWQPd00vGFnX7ES/view?usp=sharing

PS: With PS1768, No the cart rule is not applied (the free gift is not added / discount is not added)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by jolelievre** [comment]
I believe the gift product is only handled when we add the product I'm not sure though this will need to be checked in the code
However I wonder what is the behaviour in 176, it's highly possible that this bug already existed, in which case it should be fixed in 178 as it might not be a regression.

**Comment by florine2623** [comment]
This issue is fixed in PS 9.0.0

When I change quantity in my order, I have my discount with 1 euro discount and a free product :

<img width="1228" alt="Image" src="https://github.com/user-attachments/assets/b67f0fe9-f685-4748-81b2-9ab1ec5f772f" />
