### ISSUE TITLE
BO - Order page - the Selection page is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21504]
Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)
#### Describe the bug

In the BO > Order detail page, after canceling order and re-adding products.
The selection page is NOK

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO > Order detail page
2. Delete all products
3. add a new product
4. See the error

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/96454221-d90f2f00-121b-11eb-8a59-f60717ad0cd2.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #21557
