### ISSUE TITLE
id_product_attribute is missing in email $product

### ISSUE THREAD

**Issue by IAmWebSA** [PrestaShop/PrestaShop#21518]
#### Is your feature request related to a problem?

There is no id_product_attribute available in the $product variable used in the order_conf.

This is needed for modules with custom hook in the mail tpl which use the attribute.

#### Describe the solution you'd like

Add id_product_attribute to order conf mails

**Comment by khouloudbelguith** [comment]
Hi @IAmWebSA,

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

Thanks!
