### ISSUE TITLE
BO - Order page - An error 500 is displayed when adding a product with a min quantity

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21525]
#### Describe the bug

In the BO > New Order page > when we try to add a product with quantity < minimal quantity, we have an exception not clear
![image](https://user-images.githubusercontent.com/16067358/96579235-cd347300-12d6-11eb-9639-793b0a5f4ce0.png)

#### Expected behavior

Should be like 1768 "clear alert"
![image](https://user-images.githubusercontent.com/16067358/96579117-99f1e400-12d6-11eb-9419-6347f2b16615.png)

#### Steps to Reproduce

1. Create a product ProductA with quantity=20 and minimal quantity=10
2. Go to BO > Add new order page
3. Search for the last product created
4. Add it to the order with quantity = 1
5. See an error

Debug mode disabled
![image](https://user-images.githubusercontent.com/16067358/96582046-05d64b80-12db-11eb-8ef8-5b8cd05042f2.png)

With PS1770rc1build2, when debug mode enabled
![image](https://user-images.githubusercontent.com/16067358/96581152-ae83ab80-12d9-11eb-8713-18f2764d803e.png)

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/20671 & https://github.com/PrestaShop/PrestaShop/issues/18568

**Comment by khouloudbelguith** [comment]
As discussed with @Robin-Fischer-PS, it is a major regression because it is an issue reproduced in the order page
merchants do not use debug mode usually.

Thanks!

**Comment by Progi1984** [comment]
Fixed #21526
