### ISSUE TITLE
Remove ID from category/cms/product url for best SEO practice

### ISSUE THREAD

**Issue by rederijker** [PrestaShop/PrestaShop#21535]
#### Is your feature request related to a problem?

ID in url category/product/cms page ecc. make url not seo friendly.

#### Describe the solution you'd like

Delete id or hide id from url

**Comment by khouloudbelguith** [comment]
Hi @Cricchio,

Thanks for your report.
Ping @PrestaShop/product-team what do you think of this improvement?
In our case, the Id is required
![image](https://user-images.githubusercontent.com/16067358/96692505-64a4cf00-1386-11eb-9b8b-2a2e7cbe09d7.png)

Related to:

- https://github.com/PrestaShop/PrestaShop/issues/20677
- https://github.com/PrestaShop/PrestaShop/issues/9784
- https://github.com/PrestaShop/PrestaShop/issues/18402

Thanks!

**Comment by eternoendless** [comment]
PrestaShop needs the ID to find the related product. Rest assured, even though the presence of the ID in the URL can arguably be "ugly", it has no impact on SEO.

**Comment by khouloudbelguith** [comment]
Hi @Cricchio,

Your ticket is a duplicate of #20677
Please follow #20677.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #20677

**Comment by rederijker** [comment]
I'm sorry for duplicate issue. But i'm not agree with @eternoendless.

A seo friendly url is easy to remember for the user. Even if I moved the ID to the end of the uri, it wouldn't make things easier.
Thank you to all!

**Comment by eternoendless** [comment]
You're free to disagree, but that's not the definition of SEO.

**Comment by Javiercc78** [comment]
> PrestaShop needs the ID to find the related product. Rest assured, even though the presence of the ID in the URL can arguably be "ugly", it has no impact on SEO.

I think a vague answer.
This would be a very common case, if the site urls are already indexed and do not contain product id, category, etc.
When creating a new site, either by updating the version of Prestashop or migrating from another manager, be it Woocommerce, Magento, etc., the URL problem arises.

I think it would be nice to be able to choose whether to add the id or not to the urls and therefore it is a problem to not be able to do so.

Greetings
