### ISSUE TITLE
Dashproduct not working

### ISSUE THREAD

**Issue by liloubio** [PrestaShop/PrestaShop#21538]
I cannot get stats in the Dashboard.

How to reproduce:
1. Go to 'Dashboard’
2. Scroll down to 'Dashproduct'
3. Dashproduct doesn’t display anything.

**Comment by SimonGrn** [comment]
Dear @liloubio,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
