### ISSUE TITLE
The design of the 1.7.6 site is broken with php7.4

### ISSUE THREAD

**Issue by YehudaEi** [PrestaShop/PrestaShop#21541]
#### Describe the bug

I attach screenshots of the store in both Hebrew and English.
All select components do not work and are displayed incorrectly.
Plus, when you add a sample product the CSS goes completely crazy and the page is displayed completely incorrectly!
Also, due to this glitch, settings cannot be saved (note that the settings are saved but are not actually saved)

**Screenshots**
Hebrew Settings:
![image](https://user-images.githubusercontent.com/32451776/96692904-48f1f680-138f-11eb-9b49-b4e114715ab5.png)

English Settings:
![image](https://user-images.githubusercontent.com/32451776/96693720-417f1d00-1390-11eb-9b6e-7ef1dafbc2ac.png)

English new product:
![image](https://user-images.githubusercontent.com/32451776/96693815-5c519180-1390-11eb-8f4d-e625ad238fad.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.4

**Comment by khouloudbelguith** [comment]
HI @YehudaEi,

PrestaShop is not compatible with PHP 7.3/PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
The next Major release PS1.7.7 will be compatible with PHP7.3.
PS1.7.8.0 will be compatible with PHP7.4.
You need to downgrade your PHP version.

I close the issue, feel free to open a new one when needed.

Thanks!
