### ISSUE TITLE
BO - Orders page - Vouchers block - Voucher line is not added when a cart rule "Discount for a country selection" is applied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21548]
#### Describe the bug

In the BO => Orders => New Order page, the "Discount" line is not added to the Vouchers block when a cart rule "Discount for a country selection" is applied

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

You have at least France and United States countries enabled

1. Go to BO => Catalog => Discounts page
2. Create a cart rule Discount amount with a country selection "The United States"
 ![image](https://user-images.githubusercontent.com/16067358/96705548-bc970200-1395-11eb-913a-20571eb8f63d.png)
4. Go to BO => Orders => Add new order page for "John Doe"
5. add some product to the order
6. Select the address "My address (United states country)" 
7. See an error, the Discount line is not added to Voucher Block
8. In the Summary Block => ok

![image](https://user-images.githubusercontent.com/16067358/96706213-945bd300-1396-11eb-8384-60c68f781447.png)

**Other steps to reproduce the issue:**

1. Go to BO => Catalog => Discounts page
2. Create a cart rule Discount amount with a country selection "The United States"
![image](https://user-images.githubusercontent.com/16067358/96705548-bc970200-1395-11eb-913a-20571eb8f63d.png)
4. Go to BO => Orders => Add new order page for "John Doe"
5. Select a "My address (United states country)" 
6. add some product to the order
7. The Voucher well added 
8. Try to change the address selected to France
9. See the error "The voucher line is not removed
10. In the Summary block, Total voucher = 0 (well updated)

![image](https://user-images.githubusercontent.com/16067358/96707152-c91c5a00-1397-11eb-9604-c5156b379b01.png)

PS1.7.6.8 => ok

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/20667

**Comment by Progi1984** [comment]
Fixed by #21568
