### ISSUE TITLE
BO - Order page - The Voucher "Free shipping " value is not updated when changing an address

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21549]
#### Describe the bug

The Voucher "Free shipping " value is not updated when changing an address
![image](https://user-images.githubusercontent.com/16067358/96711342-b147d480-139d-11eb-8732-5b061cd3b104.png)

#### Steps to Reproduce

1. Create a Free shipping cart rule with a code
2. Enable the Carrier "My light carrier"
3. Go to BO > Add new Order page (For John Doe)
4. Add "demo_11" with quantity = 8 to the cart
5. Apply the discount
4. Change Address
5. see the error the Voucher value is incorrect
![image](https://user-images.githubusercontent.com/16067358/96711759-595d9d80-139e-11eb-83d5-b075e40cacf5.png)

#### Additional information

* PrestaShop version: 1.7.7.0rc1build2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/21548
https://github.com/PrestaShop/PrestaShop/pull/20903

**Comment by Progi1984** [comment]
Fixed by #21568
