### ISSUE TITLE
Missing fields in Add new Feature in BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21546]
#### Describe the bug

On BO > Catalog > Attributes and Features > Features > Add new feature form, in 1.7.7 RC1 Build 2, there are 3 fields missing :
- URL
- Meta Title
- Indexable

This is probably related to a bug in faceted search module.

#### Expected behavior

There fields should be displayed in the form

#### Steps to Reproduce

1. Go to BO > Catalog > Attributes and Features > Features
2. Add new feature
3. Only "Name" field is displayed, the three others are missing

**Screenshots**

In 176 : 
![missing fields features 176](https://user-images.githubusercontent.com/55688534/96703471-2b269080-1393-11eb-9a2a-5b4fe7c4b087.png)

In 177 : 
![missing fields features 177](https://user-images.githubusercontent.com/55688534/96703490-3083db00-1393-11eb-8eca-2d464b291d56.png)

#### Additional information

* PrestaShop version: 1.7.7 RC1 Build 2
* PHP version: N/A

**Comment by spkbyspk** [comment]
I have exactly the same issue, please how did you fixed it ? 
I can’t create new features because only the name field is showing. 
Thank you

**Comment by Robin-Fischer-PS** [comment]
Hi @spkbyspk ,

This PR has been released in V3.7.0 of the module, so if you upgrade your module it should be fixed.

If you still encounter this bug, could you please [create an issue](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md) providing all needed details ?

Thanks ;)

**Comment by spkbyspk** [comment]
Hi @Robin-Fischer-PS,  
It’s OK now ! Thanks a lot. 
my module is on v3.7.1 so I just have to reset it and it works. 
Thanks 🙏
