### ISSUE TITLE
AZURE PrestaShop's Marketplace Template "Prestashop Performance Template" not working

### ISSUE THREAD

**Issue by evmimagina** [PrestaShop/PrestaShop#21551]
Hi,

#### Describe the bug

Unable to provision, process stuck on "Running Final Validation...."

#### Expected behavior

Next step of the Wizard

#### Steps to Reproduce

Just try to create a deployment using the Marketplace Prestashop's template

**Screenshots**

![image](https://user-images.githubusercontent.com/56918327/96715701-464dcc00-13a4-11eb-8298-9c91cab97168.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @evmimagina,

This is an open source project Related to PrestaShop Core.

You can find help here: https://addons.prestashop.com/en/contact-us

Thanks!

**Comment by evmimagina** [comment]
Hi @khouloudbelguith ,

Ok, I will contact through that method. 
FYI, the support on Marketplace template points to this site.

Thanks,

**Comment by SimonGrn** [comment]
Hello @evmimagina 
your problem is not related to PrestaShop, you will not be able to get help here or on Addons. You must contact the Azure team directly as they are responsible for their product.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

Is this the product you were trying to use ? https://azuremarketplace.microsoft.com/en/marketplace/apps/prestashop.prestashop-performance-starter?tab=Overview

Their "Support" link is misleading, they are responsible for this implementation, we have litteraly no control on how this was designed and developed.

**Comment by evmimagina** [comment]
Hi @SimonGrn ,

Microsoft states that the support related to the product offered by publishers on their Azure marketplace, is on publisher's responsibility:

"Who's responsible for supporting customers?"

**Commercial marketplace publishers are responsible for supporting their software,** and Microsoft is responsible for supporting the purchase, billing, payments, and subscription management experiences.

https://docs.microsoft.com/es-es/azure/marketplace/marketplace-faq-publisher-guide#whos-responsible-for-supporting-customers

In this case, Prestashop is the publisher.

![image](https://user-images.githubusercontent.com/56918327/96846932-d9ddd600-1452-11eb-8cf3-6fcc1ff850a5.png)



But no worries, I will contact Microsoft and see with what they come with. In the past, due other issues with other templates, they didn't help and pointed to the publisher as well.

Regards,

**Comment by SimonGrn** [comment]
Yes obviously they reject the responsibility, but the thing is : PrestaShop is working well here. We have absolutely no idea how Azure works, how the infrastructure works, and we can't act on it.
This Github repository is also aimed only at bugs and new features in the project itself, not in installations or environment problems, these being the responsibility of the person creating the shop.

If you want some advice about setting up PrestaShop (regardless of the environment) you can ask in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you for your understanding.

**Comment by matks** [comment]
@evmimagina we are not PrestaShop SA representatives 😄 we are PrestaShop Open Source project representatives - I understand it's ambiguous. Just like WordPress is a project and the related company is Automattic.

If PrestaShop company is the publisher, you need to reach out to the PrestaShop company to see if you can get some help about this topic 🤔 . However please note that - if I read it correctly - this Azure App Template is [licensed under the Open Software License version 3.0](https://mprpdfartifactstore.azureedge.net/publicartifacts/prestashop.prestashop-90d3ef60-d069-468f-ab52-e00852514dfd/termsOfUse.html) so I'm not sure there is support in this license. But the best people to answer are the team that put this on Azure marketplace, not us 😄 .

**Comment by evmimagina** [comment]
Hi @matks ,

Thanks for your answer.
I see the problem here... but, how could I contact them if they point on that site to you? (:
@khouloudbelguith pointed me to contact though a website, on that website they told me to call a phone number... on a phonecall, they say I must buy a support add-on if I need someone look into this... and, honestly, I don't know why should we pay for something is on Prestashop's interest! 

In any case, no worries ;), clear enough this is not the path to get support on this matter.

Many thanks and regards,

**Comment by matks** [comment]
@evmimagina I will try to find out which PrestaShop team put this into the team and ask them whether some kind of support is planned or not. The least we can do is clarify this matter on Azure marketplace.

**Comment by evmimagina** [comment]
Sounds great! Thank you @matks

**Comment by SimonGrn** [comment]
> @khouloudbelguith pointed me to contact though a website, on that website they told me to call a phone number... on a phonecall, they say I must buy a support add-on if I need someone look into this... and, honestly, I don't know why should we pay for something is on Prestashop's interest!

Sadly Khouloud made a mistake, you can forget this solution.

**Comment by evmimagina** [comment]
Hi @SimonGrn ,

This is were the person on the phone guided me:

https://addons.prestashop.com/en/support/16298-prestashop-support-plan.html

Did you mean I can forget about the prestashop's support addon? they won't solve anything about this?


Thanks,

**Comment by SimonGrn** [comment]
Yes, they're definitely not the correct interlocutor for this. We will check with our teams and find who exactly can answer to you, however I'm convinced it's highly dependant on Azure's infrastructure...

**Comment by evmimagina** [comment]
Hi @SimonGrn , @matks , 

We've found this;

https://github.com/PrestaShop/azure-template-performance

seems nobody is doing anything on that project? :D

**Comment by evmimagina** [comment]
Hi again, 

Good news, forget it, I've just tryed the manual template from that branch and it seems that now is showing which might be the related issue.
Looks like it was due Azure's subscription restrictions (CSP)... I've tryied the deployment to different sort of subscription (Visual Studio) and it works!  So @SimonGrn , you were right :), it was an issue on Azure's side!

In any case, it might be worth to talk to the team that manages that and tell them to reference support in a more acurate way :)

Thank you very much for your time and best regards,

**Comment by evmimagina** [comment]
> Hi again,
> 
> Good news, forget it, I've just tryed the manual template from that branch and it seems that now is showing which might be the related issue.
> Looks like it was due Azure's subscription restrictions (CSP)... I've tryied the deployment to different sort of subscription (Visual Studio) and it works! So @SimonGrn , you were right :), it was an issue on Azure's side!
> 
> In any case, it might be worth to talk to the team that manages that and tell them to reference support in a more acurate way :)
> 
> Thank you very much for your time and best regards,

Well! I said victory too soon :( ... Still there's a problem, and now I can tell that must be with the template....

![image](https://user-images.githubusercontent.com/56918327/96866088-174e5d80-146b-11eb-88bc-568536a4b4fb.png)

**So if you still could find who could help, would be much appreciated :).**

Thanks!


The detailed message is;
```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'installAnsible'. Error message: \"Command returned an error.
				---stdout---
				and 12 not upgraded.
Need to get 1307 kB of archives.
After this operation, 2086 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython-all-dev amd64 2.7.12-1~16.04 [1006 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python-all amd64 2.7.12-1~16.04 [996 B]
Get:3 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python-all-dev amd64 2.7.12-1~16.04 [1016 B]
Get:4 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python-pip-whl all 8.1.1-2ubuntu0.6 [1112 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python-pip all 8.1.1-2ubuntu0.6 [144 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu xenial/universe amd64 python-wheel all 0.29.0-1 [48.0 kB]
Fetched 1307 kB in 0s (9228 kB/s)
Selecting previously unselected package libpython-all-dev:amd64.\r
(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 67472 files and directories currently installed.)\r
Preparing to unpack .../libpython-all-dev_2.7.12-1~16.04_amd64.deb ...\r
Unpacking libpython-all-dev:amd64 (2.7.12-1~16.04) ...\r
Selecting previously unselected package python-all.\r
Preparing to unpack .../python-all_2.7.12-1~16.04_amd64.deb ...\r
Unpacking python-all (2.7.12-1~16.04) ...\r
Selecting previously unselected package python-all-dev.\r
Preparing to unpack .../python-all-dev_2.7.12-1~16.04_amd64.deb ...\r
Unpacking python-all-dev (2.7.12-1~16.04) ...\r
Selecting previously unselected package python-pip-whl.\r
Preparing to unpack .../python-pip-whl_8.1.1-2ubuntu0.6_all.deb ...\r
Unpacking python-pip-whl (8.1.1-2ubuntu0.6) ...\r
Selecting previously unselected package python-pip.\r
Preparing to unpack .../python-pip_8.1.1-2ubuntu0.6_all.deb ...\r
Unpacking python-pip (8.1.1-2ubuntu0.6) ...\r
Selecting previously unselected package python-wheel.\r
Preparing to unpack .../python-wheel_0.29.0-1_all.deb ...\r
Unpacking python-wheel (0.29.0-1) ...\r
Processing triggers for man-db (2.7.5-1) ...\r
Setting up libpython-all-dev:amd64 (2.7.12-1~16.04) ...\r
Setting up python-all (2.7.12-1~16.04) ...\r
Setting up python-all-dev (2.7.12-1~16.04) ...\r
Setting up python-pip-whl (8.1.1-2ubuntu0.6) ...\r
Setting up python-pip (8.1.1-2ubuntu0.6) ...\r
Setting up python-wheel (0.29.0-1) ...\r
Collecting azure-storage
  Downloading https://files.pythonhosted.org/packages/5d/cd/cac628adf6cb0086a24c20d76609445f1bf841483d56ec9f5645bbaa9ab7/azure-storage-0.37.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File \"<string>\", line 1, in <module>
      File \"/tmp/pip-build-UKdlrD/azure-storage/setup.py\", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    
    Here's a non-exhaustive list of common packages:
    
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
    
    
    ----------------------------------------

---errout---
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
gpg: keyring `/tmp/tmpbt7j8tyu/secring.gpg' created
gpg: keyring `/tmp/tmpbt7j8tyu/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpbt7j8tyu/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key \"Launchpad PPA for Ansible, Inc.\" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-UKdlrD/azure-storage/
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File \"WriteSSHToPrivateStorage.py\", line 4, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: No module named azure.storage.blob

\"\r
\r
```
