### ISSUE TITLE
Ps_faceted module override 

### ISSUE THREAD

**Issue by ashishsh1984** [PrestaShop/PrestaShop#21552]
Hi,
i asm using prestashop 1.7.6.7 version
I tried some filteration of product before rendering product result & facet.
 i tried "hookFilterProductSearch" in my custom module, it filtered the product result but cause wrong facet filter.

I tried Ps_faceted override too in oerride/modules/src/product/searchprovider.php but unable to override.

How can i achieve this?

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ashishsh1984** [comment]
Hi,
I can't override prestashop ps_facetedsearch..so its a issue/bug or what?

**Comment by PierreRambaud** [comment]
> Hi,
> I can't override prestashop ps_facetedsearch..so its a issue/bug or what?

Hi, 
There is no hook in faceted search module. If something is missing in the module it's maybe easier to create a feature request in order to add what you need in this module :)

**Comment by ashishsh1984** [comment]
can you advice how to i filter products with some where clause & in same time product result should be sync be facet too?

**Comment by SimonGrn** [comment]
Hello @ashishsh1984,

you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you for your understanding.
