### ISSUE TITLE
Disabled voucher not displayed on customer panel in BO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21556]
#### Describe the bug

On BO > Customers > Customer View, the "Vouchers" block is set to display all vouchers limited to this customer. But only the enabled vouchers ("Status" to "Yes") are displayed.

The vouchers which are disabled are not displayed.

Edit : To reproduce it, you must have no other active cart rules. As soon as you have another active cart rules, the bug is not present anymore (even on 1.7.7.x). (Thanks @atomiix for the investigation)

#### Expected behavior

All vouchers limited to a customer should be displayed on the customer page, even if they are disabled.

#### Steps to Reproduce

0. Have no discount on BO
1. Go to BO > Catalog > Discount
2. Create a discount with Status at "Yes", and limited to Customer A
3. Go to BO > Customers > Customer A details page
4. Check Vouchers block : The voucher is displayed
5. Click on "Edit" the voucher, set Status to "No" and Save
6. Customer A details page is shown again, the voucher is not longer displayed even if it still exist and is still limited to this customer

**Screenshots**

https://drive.google.com/file/d/1ZpKfl5cOO2iJ6YUKUsVqn0OQPGQdtkAj/view?usp=sharing

#### Additional information

* PrestaShop version: presta1770rc1build2
* PHP version: N/A

**Comment by atomiix** [comment]
@Robin-Fischer-PS I don't think this issue is a regression, I have been able to reproduce it on 1.7.6.x. To reproduce it, you must have no other active cart rules. As soon as you have another active cart rules, the bug is not present anymore (even on 1.7.7.x).

**Comment by Robin-Fischer-PS** [comment]
You're right, it's just a weird bug, but not a weird regression, so it's OK for the RC1 :tada:

**Comment by kpodemski** [comment]
PR available, sorry @atomiix I didn't notice that you're already assigned :(

**Comment by atomiix** [comment]
No worries, it's all yours now 😄
