### ISSUE TITLE
Update PS 1.6.1.6 to new version 1.7.3.2

### ISSUE THREAD

**Issue by Dezyderyjczyk** [PrestaShop/PrestaShop#21564]
I get an error in the database update step:

PHP Fatal error:  Class 'PrestaShopBundle\
\Install\\Upgrade' not found in /[...]/httpdocs/install/upgrade/upgrade.php on line 42

PHP 5.6

**Comment by florine2623** [comment]
Hi @Dezyderyjczyk ,
Please be more precise on the error you are having with steps to reproduce and screenshots.
If you need help to upgrade your shop, please contact the [support team](https://addons.prestashop.com/en/support/18689-upgrade-pack-prestashop.html).

I'll close your issue for now.

**Comment by Dezyderyjczyk** [comment]
On the screen, after calling http://localhost/install/upgrade/upgrade.php, I have an error 500 and the above message in the appache logs.

I do this howto https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

**Comment by florine2623** [comment]
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
