### ISSUE TITLE
Front office blocked for each action in the back office

### ISSUE THREAD

**Issue by spezia38** [PrestaShop/PrestaShop#21572]
Hi,

I am having a problem loading category pages (FO). They are completely blocked for 3-4 minutes for each modification, even minor on a product in the back office.
The category pages are completely accessible in normal times.
After looking for a long time, I can't find a solution. The problem happened overnight without any updates. The number of products in the database has increased but that's it (2400 products today).

I think the database is in question.
The validation of a product page or any action in a product page (adding a combination ...) generate many requests which saturate the database.
After a few minutes Front Office works.

From there it seems complicated to be able to work in Back Office if we block the Front Office for each modification.

* PrestaShop version: 1.6.0.5
* PHP version: 5.6
* MYSQL v.5.6 
* Server: OVH perf2014x1

**Comment by florine2623** [comment]
Hi @spezia38 ,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

If you need support or help for a migration, you can contact the [support team](https://addons.prestashop.com/en/388-support) or any [partner agencies](https://www.prestashop.com/en/experts).

Thank you

**Comment by spezia38** [comment]
ok but who can help me

**Comment by SimonGrn** [comment]
@spezia38 Florine gave you a few links, you can follow them to get help.

I close this issue.
