### ISSUE TITLE
BO - Shipping - Carriers - No alert displayed when changing the Free shipping status or changing the status's carrier with bulk action

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21571]
#### Describe the bug

In the BO > Carriers page, No alert displayed when changing the Free shipping status or changing the status's carrier with bulk action

#### Steps to Reproduce

1. Go to BO > Carriers page 
2. Try to Enable/Disable Carriers with bulk action
4. See error: No alert displayed
4. Try to Enable/disable Free Shipping => No alert displayed

**Screenshots**

https://drive.google.com/file/d/1oNNDJd8iDgY-gmjWxf8ONJEIDexpRSJp/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build2, 1768
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/qa-automation

**Comment by khouloudbelguith** [comment]
Hi @matks!

This issue could be fixed during migration?
https://github.com/PrestaShop/PrestaShop/issues/10585

Thanks!

**Comment by PululuK** [comment]
> Hi @matks!
> 
> This issue could be fixed during migration?
> #10585
> 
> Thanks!


@khouloudbelguith  FYI this affects all legacy controllers. You can check `AdminCarriers`
Thanks !

**Comment by sowbiba** [comment]
https://github.com/PrestaShop/PrestaShop/pull/21576#issuecomment-715410371
@khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

In fact, the issue is that the successful alert is not displayed when changing the Free shipping status or changing the status's carrier with a bulk action.
for example 
![image](https://user-images.githubusercontent.com/16067358/97024874-9ae57880-1557-11eb-9a53-1f4098a5a056.png)
Thanks!
