### ISSUE TITLE
Correction with assignment of order reference

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#21584]
#### Describe the bug

Faced the problem that at some point the code between the creation of the order reference and the creation of the order itself took a long time, which is why two customers received two identical order references

#### Steps to Reproduce

1. Create delay 20 seconds between the creation of the order reference and the creation of the order in PaymentModule class
2. Create first order, while there is a delay, create a second order at this time

**Screenshots**
https://prnt.sc/v57wll

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @dariusakafest ,

Thanks for the suggestion and the PR.
Regarding the first step, could you send the modification to be done to the file for creating the 20 second delay ?
We will do some tests before approving your PR.

Thanks!

**Comment by fest73** [comment]
Need add sleep(20);

**Comment by florine2623** [comment]
Which file ?

**Comment by fest73** [comment]
PaymentModule class, I wrote in issue where

**Comment by florine2623** [comment]
Ok thank you
The file is 1000 lines, could you give me a hint ?
Thanks

**Comment by fest73** [comment]
@florine2623 

Find the line:
      $this->currentOrderReference = $reference;
add after it:
     sleep(20);

**Comment by khouloudbelguith** [comment]
Hi @dariusakafest,

Thanks for your feedback.
Is your issue similar to this ticket: #11115 ?

Thanks!

**Comment by fest73** [comment]
@khouloudbelguith yes

**Comment by fest73** [comment]
I suggested a solution in the fix, works fine for me now

**Comment by hibatallahAouadni** [comment]
Hi @dariusakafest 

This issue is a duplicate of #11115. So I close this one.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #11115
