### ISSUE TITLE
Fatal error on FO & BO > Modules manager after a fresh install on develop

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#21587]
#### Describe the bug

Fatal error on FO & BO > Modules manager after a fresh install on develop

#### Expected behavior

No error

#### Steps to Reproduce

1. Install on develop branch
2. Enable debug mode
3. Open FO & BO > Module manager 

**Screenshots**

![capture d'écran_2832](https://user-images.githubusercontent.com/13449658/97003888-79c35e80-153c-11eb-8b50-09b8c4637a63.png)

![capture d'écran_2833](https://user-images.githubusercontent.com/13449658/97003918-834cc680-153c-11eb-9f97-80c0fad197ee.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by marionf** [comment]
@PrestaShop/prestashop-qa Could you try to reproduce this issue ?

**Comment by ngodefroy** [comment]
@marionf I just did a fresh install and couldnt reproduce your issue in FO & BO:
![Capture d’écran 2020-10-23 à 16 52 04](https://user-images.githubusercontent.com/69145330/97018998-1511ff00-1550-11eb-8ff8-036c8880ee67.png)
&
![Capture d’écran 2020-10-23 à 16 52 21](https://user-images.githubusercontent.com/69145330/97019037-1f33fd80-1550-11eb-9e6c-713f1f7e3b10.png)

**Comment by marionf** [comment]
Fixed after a composer update, thank for the tip @atomiix :)
