### ISSUE TITLE
Forward all email to a specific address

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#21586]
We have test and preprod environments and we would like to prevent emails sent from them to be received by our customers.

Is it possible to prevent emails to be sent but instead redirect all emails to a specific email address?

Can we use the `delivery_addresses` swiftmailer config?
https://symfony.com/doc/3.4/email/dev_environment.html

Or maybe Prestashop already provide an easier way to implement this?

Thank you

**Comment by florine2623** [comment]
Hi @Seb33300 ,
Please stay tuned as I ping our dev team on it.
Thanks!

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
Could you take a look at @Seb33300 question please ?
Thanks!

**Comment by matks** [comment]
@Seb33300

In PrestaShop we use Swiftmailer. I testing environment the configuration of Swiftmailer can be overriden to achieve what you say

For example here is our testing setup: https://github.com/PrestaShop/PrestaShop/blob/develop/app/config/config_test.yml

In this setup we disable the mail sending but Swiftmailer allows the "Forward all email to a specific address" feature https://symfony.com/doc/current/email.html#sending-to-a-specified-address-es

I checked, it seems most legacy code in PrestaShop that do send emails (especially the class Mail https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php) use Swiftmailer as well) so modifying Swiftmailer configuration should do the job for you 👍 

So what you need to do is, for preprod environments, modify PrestaShop symfony config to use https://symfony.com/doc/current/email.html#sending-to-a-specified-address-es

I never tried it before so please try it and tell us if it works 😉 it might be something that we could add in the documentation

**Comment by matks** [comment]
Oups, just read again your question and you already mentioned

> Can we use the delivery_addresses swiftmailer config?
> https://symfony.com/doc/3.4/email/dev_environment.html

So, yes, you can 😄

**Comment by Progi1984** [comment]
@Seb33300 We are opened to contributions on documentation ;)

**Comment by matks** [comment]
@Seb33300 What I said however needs testing because even if all mail sending in PrestaShop rely on Swiftmailer, I am not sure there a single instance of Swiftmailer (and that modifying Symfony config for Swiftmailer will impact it all).

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
