### ISSUE TITLE
Bad URL for module catalog page after disabling MBO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#21588]
#### Describe the bug

If you disable MBO and refresh the page, the URL for Module catalog tab is 
http://localhost/presta_177x/admin-dev/index.php?controller=AdminParentModulesCatalog
instead of http://localhost/presta_177x/admin-dev/index.php/improve/modules/catalog

#### Expected behavior

Display the page without error

#### Steps to Reproduce

1. Go to Modules > Modules manager
2. Disable MBO module
3. Refresh the page
4. Click on Modules > Module catalog
5. See error

**Screenshots**

![capture d'écran_2834](https://user-images.githubusercontent.com/13449658/97007456-b9407980-1541-11eb-94b4-2e7d4b409b54.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by marionf** [comment]
I close the issue as it's fixed in the MBO module
I think we will need to do a new release of the module @atomiix ?

**Comment by atomiix** [comment]
@marionf yes!
