### ISSUE TITLE
Add new Modules in Prestashop 1.6.1.24

### ISSUE THREAD

**Issue by morethangifts** [PrestaShop/PrestaShop#21599]
I need help to know how to install the Zip files I downloaded according to your recommendation in another ticket '' Google Maps '' and '' Watermark ''.
 my version version of PrestaShop 1.6.1.24
When on my Prestashop I add a new module, it gives the file as downloaded but then in the list / menu of addons it does not appear for installation and configuration. I need to know if the file is downloaded because it is not visible and how to overcome this error.
Thank you!

**Comment by SimonGrn** [comment]
Hello,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
