### ISSUE TITLE
How I can install modules after Add New Module in Prestashop?

### ISSUE THREAD

**Issue by morethangifts** [PrestaShop/PrestaShop#21595]
Hello

I made download of zip files : 
https://github.com/PrestaShop/watermark
https://github.com/PrestaShop/gsitemap 

When I Upload them in PRESTASHOP the Addons doesn't appear for instalation ... 
![modulo](https://user-images.githubusercontent.com/73289823/97033511-5cea5380-155b-11eb-9d44-8d07d6ea14fc.JPG)
![modulo](https://user-images.githubusercontent.com/73289823/97033529-64a9f800-155b-11eb-9247-1ff2bc3b7cc7.JPG)

**Comment by SimonGrn** [comment]
Dear @morethangifts ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
