### ISSUE TITLE
Google Sitemap and Watermark is not able for install in Prestashop

### ISSUE THREAD

**Issue by morethangifts** [PrestaShop/PrestaShop#21594]
![google](https://user-images.githubusercontent.com/73289823/97027089-2fe57300-1552-11eb-9bad-c5e141a95774.JPG)

How I can solve this bug in Google Sitemap and Watermark addons ?

**Comment by florine2623** [comment]
Hi @morethangifts ,
You can download the modules from your Modules catalog.
If needed you can download them through GitHub directly :
https://github.com/PrestaShop/watermark
https://github.com/PrestaShop/gsitemap
Thanks!
