### ISSUE TITLE
How a product in PrestaShop can be uniquely identified?

### ISSUE THREAD

**Issue by confusedatma9** [PrestaShop/PrestaShop#21596]
How a product in PrestaShop can be uniquely identified? Can **reference** be used as unique identifier for a product.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
