### ISSUE TITLE
I am unable to import localisation pack in my prestashop store. Whenever I am trying to import localisation pack, it shows invalid selection. Please help.

### ISSUE THREAD

**Issue by amarkumar1234** [PrestaShop/PrestaShop#21598]
I am unable to import localisation pack in my prestashop store. Whenever I am trying to import localisation pack, it shows invalid selection. Please help.

**Comment by SimonGrn** [comment]
Dear @amarkumar1234 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by amarkumar1234** [comment]
hey, I have added an attachment of the issue. Please look into this once

**Comment by SimonGrn** [comment]
@amarkumar1234 you posted a screenshot with a link to your admin area. I removed it. You **NEED** to change the admin folder name right now, because this is a security issue.
Please read my precedent comment and recreate an issue, **following the template**.

I close this one.
