### ISSUE TITLE
Unable to import localisation pack in prestashop store.

### ISSUE THREAD

**Issue by amarkumar1234** [PrestaShop/PrestaShop#21603]
Whenever I am trying to import localisation pack in prestashop to change language, tax etc. It shows some invalid selection everytime. I have tried lot of time but unable to complete the process, please look into this. 

1. Go to dashboard of the prestashop store
2. Click on International on the left of the dashboard
3. Try to import localization pack
4. See error (invalid selection)

**Screenshot**

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.6

**Comment by SimonGrn** [comment]
Hello @amarkumar1234 
once again you submitted a screenshot with your admin link. Anybody can see what it is. This is a **SERIOUS SECURITY ISSUE. You need to change your admin folder name right now**.

As for your problem, I'm still not able to reproduce it. What is the exact localization pack you were trying to import ? What country ?

PrestaShop 1.7.6.8 is not compatible with PHP 7.3 as you can see [in the documentation](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart). Please downgrade your PHP version and try again.

**Comment by hibatallahAouadni** [comment]
Hello @amarkumar1234 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
