### ISSUE TITLE
Filter order by date using the webservice api

### ISSUE THREAD

**Issue by fredericoregateiro** [PrestaShop/PrestaShop#21604]
#### Is your feature request related to a problem?

I need to filter the orders by date using the webservice api

#### Describe the solution you'd like

Add a filter key that allow filtering like >, >=, <=, < using a given field

#### Alternatives you've considered

filter[field_gt]=[value], filter[field_get]=[value], filter[field_let]=[value],filter[field_lt]=[value]

#### Additional context

gt: grater than......

**Comment by khouloudbelguith** [comment]
Hi @fredericoregateiro,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10822
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #10822
