### ISSUE TITLE
 SmartyException  Unable to load template 'file:checkout/_partials/login-form.tpl'

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21606]
#### Describe the bug
If I use a customer with created customer's account in FO then everything works correctly. But if I use a guest user without customer account in FO then after pressing the button "Process to checkout" PS generates smarty exception:
Unable to load template 'file:checkout/_partials/login-form.tpl'

#### Steps to Reproduce
1. Work as a guest in FO
2. Add any item to the shopping cart
3. Press button "Proceed to checkout" > the shopping cart is correctly displayed
4. Press button "Proceed to checkout" > the smarty exception is generated
![image](https://user-images.githubusercontent.com/33311857/97150846-02c1dc00-176f-11eb-9f28-9d892ac98d8b.png)

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32-1

**Comment by khouloudbelguith** [comment]
Hi @juraj1000,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached the screen record
https://drive.google.com/file/d/1T73z2UQNRaYKl7NR5HVrMGB5ro0wc6d2/view?usp=sharing
Thanks to check and feedback.

**Comment by juraj1000** [comment]
Hello @khouloudbelguith,
it seems I found the cause of the exception. There was renamed the file from login-form.tpl to login.tpl in the folder /themes/classic/templates/checkout/_partials/. I don't understand it because I didn't do any manual changes in the folder with ftp.

**Comment by khouloudbelguith** [comment]
@juraj1000, since it is not a PrestaShop core issue.
I close the ticket, feel free to open a new one when needed.

Thanks!
