### ISSUE TITLE
Smarty cache issue with getDevice() and isMobile()

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21614]
#### Describe the bug

Smarty conditions Context::getContext()->isMobile() and getDevice() dont work when smarty cache is enabled

#### Expected behavior

In my template i use condition {if Context::getContext()->isMobile() == 1} and i want show different text for mobile and dekstop.
When smaty cache is disabled everything works perfect.

#### Steps to Reproduce

1. Set smarty cache to disabled
2. Make condition in template e.g. /themes/classic/templates/index.php
```
{if Context::getContext()->isMobile() == 1}
    mobile
{else}
    desktop
{/if}
```
3. Check if working. Should display 'mobile' on mobile device and 'desktop' on dekstop.
4. Set smarty cache to on, clear it and refresh page on both devices.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @simon12q,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached a screen record
https://drive.google.com/file/d/1Gb8UdND5v64sX-x95-WqVJGoPpZdVwSU/view?usp=sharing
When Smarty cache is enabled, the Template compilation is set to "Force compilation" in my case.
![image](https://user-images.githubusercontent.com/16067358/97177096-3b28e080-1796-11eb-80dd-cc4fecd0d547.png)

Thanks to check and feedback.

**Comment by ghost** [comment]
Thank you @khouloudbelguith for your time.

I check it one more time on my other hosting and it works as expected.

I suspect that the problem in the first case may be nginx. Do i need any extra config for it?

//edit ok i get it finaly. There is no problem with server or prestashop - i have made this bug for my own

**Comment by szykuc** [comment]
Hello, @khouloudbelguith 
i have a very simillar problem but when i make such a condition in module.

For example i add same condition
```
{if Context::getContext()->isMobile() == 1}
    mobile
{else}
    desktop
{/if}
```
into module template /modules/ps_newproducts/views/templates/hook/ps_newproducts.tpl

If cache is enabled condition not working.

**Comment by khouloudbelguith** [comment]
Hi @szykuc,

When Smarty cache is enabled, the Template compilation is set to "Force compilation" or "Recompile templates if the files have been updated"?
If No, thanks to change it.

Thank you!

**Comment by szykuc** [comment]
@khouloudbelguith i checked all combinations of cache settings on two different servers (apache and nginx) and im sure that is not working as should.
Should i open a new issue?

**Comment by SimonGrn** [comment]
> //edit ok i get it finaly. There is no problem with server or prestashop - i have made this bug for my own

@szykuc could you explain what was your problem exactly and how you solved it ? It might help people who have the same issue. Thank you !

**Comment by szykuc** [comment]
@SimonGrn the point was that when the condition is placed in index.tpl or any other theme file it works fine with cache enabled.
But when condition is placed in module .tpl file there is problem.
