### ISSUE TITLE
Uncaught TypeError: can't access property "quantityWanted", _prestashop2.default.selectors is undefined

### ISSUE THREAD

**Issue by alfiosalanitri** [PrestaShop/PrestaShop#21618]

**Comment by khouloudbelguith** [comment]
Hi @alfiosalanitri,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
