### ISSUE TITLE
Extra post array are deleted in AdminStoresController::postProcess

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#21624]
#### Describe the bug

Any array extra post vars are deleted on save by AdminStoresController::postProcess

#### Steps to Reproduce

1. Create a module or an override
2. Add a new HelperForm field in AdminStoreController, by example a select with 'multiple' => true
3. Try to save or dump this field : it's always empty

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by jf-viguier** [comment]
I've posted a PR https://github.com/PrestaShop/PrestaShop/pull/21625

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I manage to reproduce the issue with PS1.7.5.1, PS1.7.6.8 and PS1770rc1buid2.
I used this form:
```php
                array(
                    'type' => 'select',
                    'label' => $this->trans('multiple select', array(), 'Admin.Global'),
                    'name' => 'multiple_select',
                    'required' => true,
		    'multiple' => true,
                    'default_value' => (int) $this->context->country->id,
                    'options' => array(
                        'query' => Country::getCountries($this->context->language->id),
                        'id' => 'id_country',
                        'name' => 'name',
                    ),
                ),
```
![image](https://user-images.githubusercontent.com/16067358/97277509-dc687300-1838-11eb-8568-be8fb5989bfb.png)

Thank you!
