### ISSUE TITLE
Unable to download file in HTTP/2

### ISSUE THREAD

**Issue by sylwit** [PrestaShop/PrestaShop#21629]
#### Describe the bug

In SQL manager, if the data to download reaches a certain size, the download is corrupted.
Issue described here : https://community.cloudflare.com/t/files-can-not-be-downloaded/5598/16

#### Expected behavior

Download should work

#### Steps to Reproduce

1. Go to SQL Manager
2. Add a query which return more than 100Ko of data
3. Download the file via HTTP/2

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7.x

**Comment by khouloudbelguith** [comment]
Hi @sylwit,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached a screen record
https://drive.google.com/file/d/1uFgdHeRLfCqNnNQ6Uk1dYC0iACZksw2e/view?usp=sharing
![image](https://user-images.githubusercontent.com/16067358/97282111-90b8c800-183e-11eb-9bf1-097d46287d49.png)

Thanks to check and feedback.

**Comment by sylwit** [comment]
Hi @khouloudbelguith 
Do you have a website behind CloudFlare to make a test with a full encryption ? It can also be related to the gzip configuration which corrupt the filesize. 
I did the test on 3 servers, 2 at planet hosters with failure, 1 at OVH and it was OK.

Actually the file is downloaded but never ends because it's expecting another "filesize" so the browser cancel the download.

**Comment by khouloudbelguith** [comment]
@sylwit,

>I did the test on 3 servers, 2 at planet hosters with failure, 1 at OVH and it was OK.

So, it is a server issue and not a PrestaShop issue? isn't it?
Have you tried to contact the host?

Thanks!

**Comment by sylwit** [comment]
no it's about the way BinaryFileResponse handle http2 streaming. Please
have a look about the link I posted on the doc of HttpFoundation.
Anyway, the PR has already been accepted.

**Comment by khouloudbelguith** [comment]
Hi!

Ping @atomiix.

Thank you!
