### ISSUE TITLE
Unable to resolve Composer constraints on develop for Composer v2

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#21621]
I merge `1.7.7.x` that brings the latest changes to be compliant Composer v2 into `develop`

I get the following **constraints conflict**: 🔴 
```
  Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - doctrine/orm v2.7.3 requires ocramius/package-versions ^1.2 -> satisfiable by ocramius/package-versions[1.4.2].
    - doctrine/orm is locked to version v2.7.3 and an update of this package was not requested.
```

#### Why no issue on 1.7.7.x ?

On `1.7.7.x` we do not require ocramius/package-versions. This dependency was brought in by doctrine/orm 2.7.3 . On `1.7.7.x` we use doctrine/orm 2.7.0 that does not require ocramius/package-versions so no issue.

#### What is the issue of ocramius/package-versions  ?

On `develop` doctrine/orm 2.7.3 requires ocramius/package-versions.

On `develop` we use ocramius/package-versions 1.4.2 that [requires Composer v1](https://packagist.org/packages/ocramius/package-versions#1.4.2) because of constraint `composer-plugin-api: ^1.0.0`

#### Can we upgrade this dependency to a version compliant with Composer v2 ?

Any more recent version of ocramius/package-versions drops php7.1 compatibility 🤯  so we're stuck with v1.4.2 . For example v1.5.0 is compatible with php7.3 only and v2.2.0 is php8 only.

## Summary

So here we are:
- stuck with ocramius/package-versions 1.4.2 because we dont want to drop php7.3
- but ocramius/package-versions is not compatible with Composer v2

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/21622

**Comment by matks** [comment]
Thanks to @jolelievre upgrading to doctrine/orm 2.7.4 solves the issue as it does handle this compatibility issue.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21622
