### ISSUE TITLE
[BO][Products][Product customization] checkbox replace switch only after saving

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21633]
#### Describe the bug

Go to Catalog>Product>Options>customization
When you add a new field (text or file) the tick box "required" is replacing the new "required" switch
it's only after you save that the new switch gets taken into account.

#### Expected behavior

When the user add new customization, the new field should display a switch for the required field.

#### Steps to Reproduce

1. Go to BO>Catalog>Product>Options>customization
2. Click on customization
3. add a new field 
4. See difference between required tick box and required switch:

**Screenshots**

<img width="905" alt="Capture d’écran 2020-10-27 à 11 37 09" src="https://user-images.githubusercontent.com/69145330/97290417-d24e7080-1848-11eb-965c-31f7b54dfdc6.png">

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ngodefroy,

I manage to reproduce the issue with PS1.7.5.1, PS1.7.6.8, and PS1770rc1build2.

Thanks!

**Comment by PululuK** [comment]
I think we need to either remove the switch or use it all over the product page to keep this consistent ... Is there a special reason why the switch is only used in custom fields?

ping @PrestaShop/product-team

**Comment by LouiseBonnard** [comment]
@marionf, @PrestaShop/ux-team, does it ring a bell to you? I didn't manage to reproduce this issue nor find it in the specifications... 🤔

**Comment by MatShir** [comment]
The issue happens when you add a new customization field, it shows a checkbox for the new custom field. Then if you save and reload the page, the checkbox becomes toggles. We could work on the issue during the migration. We just need the confirmation from the UX team wants the toggle rather than the checkbox.
But this issue is not a duplicate or maybe we have talked of this issue @matks? 🤔

**Comment by prestascott** [comment]
Hello everyone!

Thanks @ngodefroy for your report. 

I can confirm with you @MatShir that we want to use toggles rather than checkboxes because there is a single selection that is required, and we want to offer two options for an on/off type of decision.
