### ISSUE TITLE
PaymentModule.php validate order undefined offset drive crazy

### ISSUE THREAD

**Issue by psppro26** [PrestaShop/PrestaShop#21638]
hi ive coded a custom moduel who use validateOrder() function and i have a problem with these lines 

Classes/PaymentModule.php line 286

```
foreach ($cart_delivery_option as $id_address => $key_carriers) {
                foreach ($delivery_option_list[$id_address][$key_carriers]['carrier_list'] as $id_carrier => $data) {
                    foreach ($data['package_list'] as $id_package) {
                        // Rewrite the id_warehouse
                        $package_list[$id_address][$id_package]['id_warehouse'] = (int) $this->context->cart->getPackageIdWarehouse($package_list[$id_address][$id_package], (int) $id_carrier);
                        $package_list[$id_address][$id_package]['id_carrier'] = $id_carrier;
                    }
                }
            }
```

when i comment them it's working but if i dont i have an error on validateOrder.. The crazy thing is it's working on a brand new Prestashop , but when i install a custom theme and nothing else it's not working anymore ? i dont know what to do ? 
i tried delete cache , reinstall the clean database but once i changed the theme , even if i delete it and go back to classic one the problem still occurs ?! what kind of sorcery is it ? do prestashop store special files idk

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
