### ISSUE TITLE
BO - Carriers page - The sort by Name is not working correctly

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21640]
#### Describe the bug

In the BO > Shipping > Carriers page > the sort by name is not working correctly.
In fact, sorting by Name is reversed comparing the sort by ID (for example)

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/97413768-7ac10b00-1903-11eb-83d3-a62cab691d17.png)

#### Steps to Reproduce

1. Go to BO > Shipping > Carriers page
2. sort by name
4. See the error

#### Additional information

* PrestaShop version: Develop (178)
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/qa-automation

**Comment by khouloudbelguith** [comment]
Hi @matks!

This issue could be fixed during migration?
#10585

Thanks!

**Comment by matks** [comment]
> Hi @matks!
> 
> This issue could be fixed during migration?
> #10585
> 
> Thanks!

Yes, fixing the sort is something we can embed :D
