### ISSUE TITLE
Errors in Prestashop Upgrade

### ISSUE THREAD

**Issue by deliciousvinos** [PrestaShop/PrestaShop#21647]
Hello! Sorry for my english, I'am spanish.

I've recently upgrade prestashop from 1.7.2.4 to 1.7.6.8. The upgrade finish successfully. It's runs in PHP 7.1.
Now I can enter the backend correctly, and navigate everywhere correctly, but de web don't runs.

Website can runs in maintenance mode, but not online.

I've solved some errors and now I'm stuck on the following error:

![image](https://user-images.githubusercontent.com/73553826/97434812-dac5aa80-191f-11eb-9795-85369d811299.png)

Can you help me, please?

**Comment by hibatallahAouadni** [comment]
Hello @deliciousvinos 

Please next time follow the Github template. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/)

Could you please specify the version of autoupgrade module and provide the log file: `/admin-dev/autoupgrade/tmp/`

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @deliciousvinos ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
