### ISSUE TITLE
Select not working on Backend Missing blank space between select and id

### ISSUE THREAD

**Issue by luciochavez** [PrestaShop/PrestaShop#21657]
In Admin backend prints (in html source code) "<selectid=..." instead of "<select id=..." (notice the blank space missing) which makes selects unusable

On fresh install of PrestaShop:1.7.6.8 with Theme: classic 

Tested on
Linux #1 SMP Tue Dec 4 03:50:32 EST 2018 x86_64 
Apache/2.4.46 (cPanel) OpenSSL/1.1.1g mod_bwlimited/1.4 
PHP:7.4.11 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0 
AND
Chromium Versión 86.0.4240.111 (Build oficial) snap (64 bits)

![imagen](https://user-images.githubusercontent.com/32309375/97460951-d9d25000-1902-11eb-928d-b25fe99c687b.png)

**Comment by hibatallahAouadni** [comment]
Hi @luciochavez 

Thanks for your issue. You must follow the template to submit a complete bug report.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

And PrestaShop 1.7.6.8 doesn't support PHP 7.4 ([see PHP compatibility chart](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
You need to downgrade your PHP version to 7.2.

So, I close it.

Thank you.

**Comment by luciochavez** [comment]
Thanks! and sorry for the trouble :(
I've downgraded to PHP 7.2 and problem solved.

Have a nice day!
