### ISSUE TITLE
ps_emailsubscription captcha

### ISSUE THREAD

**Issue by tonnick** [PrestaShop/PrestaShop#21650]
#### Is your feature request related to a problem?

ps_emailsubscription has no native captcha security. newsletter form is spammed and website is sending tons of mails with optin is activated. this is conducing to backlist website server.

#### Describe the solution you'd like

a native captcha to ps_emailsubscription

#### Alternatives you've considered

no alternative

thx.

**Comment by hibatallahAouadni** [comment]
Hi @tonnick 

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

**Comment by kpodemski** [comment]
I don't think it's a good idea, would be better to try some kind of honey pot hack, and maybe form flooding security mechanism, captcha should be last option for this kind of issue

**Comment by tonnick** [comment]
you are probably right, I do not know which is the best solution, captcha was just an idea. Anyway, this part of prestashop should be improved in a native way to avoid this kind of issue.

**Comment by kpodemski** [comment]
Yes, agree, let's wait for an opinion from @PrestaShop/product-team

**Comment by LouiseBonnard** [comment]
Hi @tonnick, thanks for your improvement idea but I'm afraid we will decline it. Even if CAPTCHA systems are very efficient to fully protect stores from spamming, it has been decided a few years ago not to offer this feature natively because it could complicate the installing and setting process.

However, if we decided not to integrate it to 300,000 stores in order to keep them performant, many modules exist on our marketplace that could be installed on individual shops when merchants are looking for this kind of solution. I invite you to read more about it on Build: https://build.prestashop.com/news/fighting-against-spamming

**Comment by SimonGrn** [comment]
Thank you @LouiseBonnard !

I close this issue.

**Comment by tonnick** [comment]
ok so you are aware that there is an issue on the newsletter form, but you prefer let the people pay to add captcha when most of any CMS have it for free ? security improvment is not an option for prestashop ?

**Comment by tonnick** [comment]
prestashop team decided years ago to do not improve security of newsletter form, and won't even re-consider it ? prestashop remains in same position than years ago, and just close any improvment suggestion ? is that real ?

**Comment by SimonGrn** [comment]
Hello, thank you for your inputs. 
May I remind you of our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md) ?
Please remember you're talking to humans.

I close this issue as it's going nowhere.

Thank you for your understanding.

**Comment by matks** [comment]
> ok so you are aware that there is an issue on the newsletter form, but you prefer let the people pay to add captcha when most of any CMS have it for free ? security improvment is not an option for prestashop ?

Hi,

I would like just to answer this nevertheless interesting question.

The goal of PrestaShop is not to provide all the features that everybody wants. It is to address the needs of most of our users.

As far as we know, as of today, most users that want to add a captcha to their subscription form are confortable with paying the (small) fee for such modules on Addons marketplace or implementing themselves (if you are a developer, adding a captcha on this form is not very complex). So it does not seem to be an important or urgent matter.

If tomorrow "having a free captcha inside PrestaShop" becomes one of the top ten priorities and requests of users, our answer might be different. But so far what is available seems to be satisfying for a large quantity of user although it is not for you.

Also captchas are not very fitted for an open source solution. The best captchas I know are proprietary which means they cannot be integrated into the software (license issues) or depend on external system. There's also captchas that only work for an area for the world (remember PrestaShop aims to be used by anybody in the world, you cannot include in it something that only works for EU or USA for example), captchas that require a specific setup ... so the topic is not an easy one to integrate in a global and worldwide solution as PrestaShop. Doing it might result in something quite disappointing.

So when we consider these 2 facts : 1) not easy to do, and end result might be disappointing + 2) current (paying) solutions seem to address quite well user needs ; you can see it does not seem wise to include it inside the open source project.
