### ISSUE TITLE
BO - Order page - Incorrect total when updating a quantity's product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21659]
Thanks to @florine2623 

#### Describe the bug

In the BO > Order detail page > When Updating a quantity's product, the total is incorrect.

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/97462166-bd540900-193e-11eb-900a-554ca502210d.png)

#### Steps to Reproduce

1. Go to BO > International > Taxes page and Enable "Display tax in the shopping cart"  
2. In Shop Parameters > Custom Settings > Groups > Edit Customer "Price display method" => tax excluded
3. Create a productA with 21% tax , €7.8 tax excluded
4. Go to FO > Add productA to cart with quantity = 70
5. Continue checkout
6. Go to BO > Order page > update the quantity to 80 => see error
7. Total is NOK

PS: 1770rc1 => FO => ok

**Screenshots**

1770rc1build2/1770rc1buil3
![image](https://user-images.githubusercontent.com/16067358/97463314-e923be80-193f-11eb-8981-84636adb3823.png)

1768
![image](https://user-images.githubusercontent.com/16067358/97462935-87fbeb00-193f-11eb-846d-759e40bad112.png)

#### Additional information

* PrestaShop version: 1770rc1build2/1770rc1build3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @marionf @Robin-Fischer-PS what do you think of the severity?

Thank you!

**Comment by Robin-Fischer-PS** [comment]
It's a rounding issue that can happen with these three conditions :
- Customer group is tax excluded
- The "tax included" price of the product has more than 2 decimals (so not only with 21% tax)
- Edit the quantity in BO

This can happens with low quantity too (with an edit to 3 of a product at 7,8€ tax excluded, with 2,1% tax).

I don't know what the percentage risk of having these three conditions is, so I'm not sure for the severity, if it is Major or Critical...

**Comment by Progi1984** [comment]
Fixed in #21666
