### ISSUE TITLE
Not getting 'search_query_builder' in params of hook actionOrderGridDefinitionModifier in PS 1.7.7.0 beta version

### ISSUE THREAD

**Issue by neerajwebkul** [PrestaShop/PrestaShop#21668]
Hello,

I am not getting 'search_query_builder' in params of hook actionOrderGridDefinitionModifier in PS 1.7.7.0 beta version just like we can get in hook actionCustomerGridQueryBuilderModifier

https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/

#### Expected behavior

Expecting $params['search_query_builder'] in hook actionOrderGridDefinitionModifier params

#### Additional information

* PrestaShop version: 1.7.7.0 beta

**Comment by hibatallahAouadni** [comment]
Hi @neerajwebkul 

We need more details to understand how we can reproduce your issue.
Could you please provide the steps to reproduce your issue?

Thanks!

**Comment by neerajwebkul** [comment]
Hello,

As we know in PS version 1.7.7.0 (beta), Backoffice order list page has been changed.

Now I want to filter order list in my module using grid query builder. So I have used this hook 'actionOrderGridDefinitionModifier'
like we can see in dev docs -
https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/
Here docs mentioned for customer listing.
https://prnt.sc/v9z7l1
Here you can see, params has 'search_query_builder' index. So in hook 'actionCustomerGridQueryBuilderModifier' it is working properly.
But while I am using this hook 'actionOrderGridDefinitionModifier' for orders then I am not getting search_query_builder in params and that's why I am not able to modify query.

I hope now you got it.

Thanks,

**Comment by matks** [comment]
@neerajwebkul You should use the equivalent hook `actionOrderGridQueryBuilderModifier` instead of `actionOrderGridDefinitionModifier` . These are not the same hooks, not the same parameters, not the same purpose.

**Comment by hibatallahAouadni** [comment]
Thanks @matks for your quick answer.

@neerajwebkul if you @matks answer solve your problem, please let me know to close the issue.

Thanks!

**Comment by neerajwebkul** [comment]
Hello,

Its working.

Thanks,
