### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by Aidam-puk** [PrestaShop/PrestaShop#21663]
#### Describe the bug

When i tried to upload my logo and press save, error page appears: 
Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

#### Expected behavior

Upload logo into site

#### Steps to Reproduce

1. Go to 'appearence'
2. Click on themes and logo
3. Browse my logo
4. Upload logo into all sections
5. Press Save
6. See error

**Screenshots**

![Screenshot 2020-10-28 at 22 44 13](https://user-images.githubusercontent.com/73615026/97494244-ba710c80-196e-11eb-964f-ae9299f32510.png)
![Screenshot 2020-10-28 at 22 44 39](https://user-images.githubusercontent.com/73615026/97494259-be049380-196e-11eb-9cd2-f4a826b792fc.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by matks** [comment]
@Aidam-puk it is most likely to be an issue in your server configuration, possibly a server issue permission.
I suggest contacting your host provider about it

**Comment by florine2623** [comment]
Hi @Aidam-puk ,
Indeed it seems like a server configuration issue.
If you need any help, please contact the [support team](https://addons.prestashop.com/en/388-support) or a [partner agency](https://www.prestashop.com/en/experts).
Thanks!
