### ISSUE TITLE
Problem with product declinations

### ISSUE THREAD

**Issue by onopko81** [PrestaShop/PrestaShop#21670]
Problem with product combination in order confirmation page. Total product is 0.

how resolve it?

**Screenshots**
 http://orchideabomboniere.it/bug-orchidea.jpg

#### Additional information

* PrestaShop version:  1.7.6.5
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hi @onopko81 ,
I can't reproduce your issue on PS 1.7.6.5. It must be a configuration issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
