### ISSUE TITLE
Store should know which currency it uses, not requiring to provide it every time.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21685]
#### Is your feature request related to a problem?

When I want to use Product::convertPrice() to get price of the product, why do I have to know the currency ID? We have two stores, both have only one currency, one $ the other €. convertPrice() should get the store currency automatically itself instead of requiring me to know it. Of course if your store has multiple currencies it is a different story, but these are a "big minority" I guess.

**Comment by grzegorzgit** [comment]
If anyone has similar problem, there's a value: Configuration::get('PS_CURRENCY_DEFAULT')
but it is not working, it gives me this error:

![image](https://user-images.githubusercontent.com/24461669/97708329-e8fafe80-1ab8-11eb-96ac-19cf539701dd.png)

**Comment by florine2623** [comment]
Hi @grzegorzgit ,

Thanks for the suggestion. I'll ping dev and product team to have their input on that.
Please stay tuned !

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers and @PrestaShop/product-team ,

Is this doable and relevant ? What do you think about it ?
Thanks!

**Comment by matks** [comment]
@grzegorzgit Actually I believe it's better this way.

> convertPrice() should get the store currency automatically

At 1st glance, this looks something desirable, because it's easier to use.

But this would actually become a _trap_. Automatic fetching of necessary data is a pitfall because you think it's great while it serves you until at some point you are doing some stuff in your store and _the currency picked automatically is not the one you wanted_. Worse: since this function is now **stateful** it might happen that you call the same function 3 times and obtain 3 different results because "the currency that is fetched automatically behind the curtain has changed in the meantime".

This can be linked to the more global topic of stateless operations VS stateful, you can read more about it here https://stackoverflow.com/questions/35660938/why-is-passing-stateful-objects-to-constructor-a-bad-thing

So it looks like a good idea (because it increases usability) but it actually decreases stability and maintainability.

Today when we are rewriting PrestaShop code we are _removing_ all of the statements where such data is automatically fetched from somewhere to make it explicit ... and this simple move solves a lot of bugs that were introduced due to stateful functions or classes 😉 

Note: this issue has also been described in https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/#global-state

**Comment by matks** [comment]
@grzegorzgit I see you opened multiple issues about same topic. Please do not do that.

We can continue the discussion in this issue 😉  (a closed issue does not mean we cannot discuss further)

**Comment by grzegorzgit** [comment]
Well in that case if I want to use different currency then I will provide it, cause I know I need to use specific one. You are using exceptional behaviour as it would be a standard. Majority of cases I don't care which currency is used by the store, and in the small percentage of cases when I want not to use the default, then I should be able to specify it.

**Comment by grzegorzgit** [comment]
_**Today when we are rewriting PrestaShop code we are removing all of the statements where such data is automatically fetched from somewhere**_

Seriously? This sounds like a horrible move, Prestashop should automatically take all the default information as far as it can, and only **require** user / programmer to specify things when it is impossible to use default. Leaving always the way to change and not use the default.

**Comment by matks** [comment]
> Well in that case if I want to use different currency then I will provide it, cause I know I need to use specific one. You are using exceptional behaviour as it would be a standard. Majority of cases I don't care which currency is used by the store, and in the small percentage of cases when I want not to use the default, then I should be able to specify it.

We follow a best practice in software development: "consider the N=1 usecase to be a sub-usecase of N>1"

See the following example: let's say most of the time a Product has 1 image. We could simply decide to link Product and its image with a 1-1 relationship ; and for "all the other usecases where there are multiple images we handle it differently".

That would probably be very user-friendly for the people having 1 image per product. **But for software stability and maintainability, it would be a mess**. Trust me on this 😉  it's better to have a single system/convention able to handle multiple items (so when there is a single item you consider a collection with only 1 item in it) than to have 2 different system, one for N=1 and one another for every other usecase.

I am not inventing things here. These are best practices taught to us by software development experts through the world 😄  we're just following the wise words of people better than us.

**Comment by matks** [comment]
> _**Today when we are rewriting PrestaShop code we are removing all of the statements where such data is automatically fetched from somewhere**_
> 
> Seriously? This sounds like a horrible move, Prestashop should automatically take all the default information as far as it can, and only **require** user / programmer to specify things when it is impossible to use default. Leaving always the way to change and not use the default.

It might sound an horrible move to you, but it will greatly increase the stability of the codebase. This means **reduce greatly the number of bugs**, that is something important, isn't it ? 😄 

Being explicit is always clearer and more maintainable than being implicit. Once again, this is what software development best practices have taught us, not something we decided to invent. It has proven for the industry to be a valuable strategy to increase software stability and maintainability and today _PrestaShop needs stability and maintainability_.

**Comment by grzegorzgit** [comment]
Ok, I understand that sometimes it would require more coding to write a class: one part to go with defaults, and the other for other cases.

But in this case, it is only currency, it is something so basic. Why do I have to put PS_CURRENCY_DEFAULT into the method parameter, when it could be written in the class itself? And it is important, because PrestaShop doesn't really have good documentation or tutorials on how to use it. Today I found PS_CURRENCY_DEFAULT in Google by a chance, tomorrow you will change it to PS_CURRENCY and I will have to Google again. 

I get it that here comes the contradiction of usage ease and maintance/development ease. But it looks like you PS developers think that more people work here on PS development rather than on using and configuring it everyday

**Comment by matks** [comment]
> But in this case, it is only currency, it is something so basic. Why do I have to put PS_CURRENCY_DEFAULT into the method parameter, when it could be written in the class itself? And it is important, because PrestaShop doesn't really have good documentation or tutorials on how to use it. Today I found PS_CURRENCY_DEFAULT in Google by a chance, tomorrow you will change it to PS_CURRENCY and I will have to Google again.

You said it yourself: with a good documentation, there is no issue that `Product::convertPrice()` requires you to provide the currency ID. If the documentation makes it very clear how to retrieve the currency object, then it's solved.

So I think it's better to keep the code into a state where things are clear and explicit _but_ improve the documentation to avoid the confusion.

And I've got some good news: PrestaShop documentation is also open source 😉  this means you can _contribute to make it better_ by submitting Pull Requests to fill the gaps you might find in it. It's all there https://github.com/prestashop/docs

We are aware that documentation is not complete. To be frank, 3 years ago it was very very small. https://devdocs.prestashop.com/ was started for PS 1.7 and has improved tremendously both the quantity of quality of the documentation, but the debt is still quite huge. We try to improve it little by little but it will be so much faster if everybody help us in this 😉  by submitting
- issues in the doc "Topic X is not well explained / is missing" (so we have a "roadmap of what's missing")
- pull requests to fix the issues

<hr>

As for this

> I get it that here comes the contradiction of usage ease and maintainance/development ease.

We actually have a plan for that, and it's all explained here https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/

The idea is to keep a deep core component very robust, very stable, which means explicit statements, no "magic", no "shortcut" becauses we aim for maximum maintainance/development ease ; and **wrap it with a developer-friendly API** . This concept is being implemented thanks to a QueryBus following CQRS pattern. It allows you to ignore the complexity of the code used under and simply focus and what you want to call.

See this controller for example https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php

In this controller, when you want to get _all_ the order data you do this:
```
$orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
```

You don't know what service is called behind that. You don't know what services or whatever else logic is being run. What you know is:
- you need to "view the order X"
- so you dispatch a GetOrderForViewing query to the CommandBus
- it does its work
- it gets you the data

Simple. This is how we plan to have both of the worlds: developer-friendly code through this API based on [Commands and Queries](https://devdocs.prestashop.com/1.7/development/architecture/domain/cqrs/) that do rely on developer-unfriendly-but-very-robust-and-controlled layer below.

That's the plan we are currently following, and the code you mentioned belongs to this "below layer" that we want to keep very explicit 😄

**Comment by grzegorzgit** [comment]
Thanks a lot for your explanation, the last message did calm me a little :)
It only seems like total new way of writing modules, this might be a little concerning, but I guess that's the issue with every new major version.

And getting product's price is seriously a deep core coding?

**Comment by jolelievre** [comment]
Hi @grzegorzgit 

although I tend to share @matks vision regarding stateful calls that are literally a hell to debug and maintain, I'm not sure I understand your use case. You talk about `Product::convertPrice` which forces you to define the currency but when I look at this method it seems to use the context currency automatically:

https://github.com/PrestaShop/PrestaShop/blob/3cc8f2646400361587bfcba8a7463ac8dca94818/classes/Product.php#L4054

So you can't specify any currency 🤔   or I don't understand how Besides it doesn't seem to convert anything it simply formats the output but no conversion computing is applied I don't think you should actually use this method it doesn't seem to be used anywhere else.

To really convert prices you'd better use `Tools::convertPrice` which really performs computing (not just display them with appropriate format), and allows you to specify both the input currency and the output currency (default behaviour is to convert from context currency to default currency). This method is only used for conversion, not formatting, so you would need to format the result for appropriate display.

To format your price you can either use:
`Context::getContext()->getCurrentLocale()->formatPrice($dollarPrice, $dollarCurrency);`

Or maybe in your case using `Tools::displayPrice($dollarPrice);` Although this method is deprecated and will likely disappear someday (in favor of `PrestaShop\PrestaShop\Core\Localization\Locale::formatPrice()`


I hope this can help you, don't hesitate to detail your use case a bit more if you're still blocked as I'm not sure to grasp the whole picture. Don't hesitate to discuss on our [community slack](https://github.com/PrestaShop/open-source/blob/master/slack/readme.md) as well to find help with other community members.

**Comment by grzegorzgit** [comment]
This is exactly the case, Tools::displayPrice(123.456) was an amazing and super easy to use thing. Now I see it is deprecated, so instead I am trying to use the Locale::formatPrice() :
Context::getContext()->getCurrentLocale()->formatPrice($dollarPrice, $dollarCurrency);

The problem is not only that I don't want to hardcode the currency, but when I use Configuration::get('PS_CURRENCY_DEFAULT') it shows an (very unclear) error.

So here I have basically two problems, first is why the configuration constant doesn't work? 
And why did you decide to remove this amazing Tools::displayPrice() that required me to only put number inside and I got my formatted price? This is very basic thing to get product's price, it should be as easy as getting the product's name.

This is a store software we are talking about and I am having so many problems to display price on my template :(

edit: Thanks jolelievere, the issue was currency iso code and not id coming from PS_CURRENCY_DEFAULT (which I was using). Your answer works.
