### ISSUE TITLE
Breadcrumb issue on Homepage

### ISSUE THREAD

**Issue by RaymondST1985** [PrestaShop/PrestaShop#21696]
Hi,

Since a couple of days I have an issue on the homepage with Breadcrumbs. On all the other pages the breadcrumbs are working fine. Im using Prestashop 1.7.5 but I used, the breadcrumb.tpl file of 1.7.x 

In the google search console I see the following error:

Missing field ItemElementList 

> <ol itemscope itemtype="http://schema.org/BreadcrumbList">
    <li>
              <span>Inicio</span>
     </li>
 </ol>

And this is the HTML from the homepage where the Search Console is referring to:

I also experienced it in the past in the catalog page, but after using the breadcrumb.tpl from 1.7.x the problem was solved. Unfortunately this issue is now on the homepage.

**Comment by SimonGrn** [comment]
Hello @raymondst1985
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 
Thank you
