### ISSUE TITLE
Cache modules should not be able to override everything

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#21704]
I am puzzled that Prestashop is selling cache modules that contain overrides to popular files like productController. It looks like that this is at the moment the number 1 cause of problems on the forum. 

Overriding such files should be reserved for modules bringing relevant functional changes.

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
Hi @musicpanda the team in charge of this github repository does not handle addons.prestashop.com (basically here it's about the project, not the company).

You can reach out to them at https://addons.prestashop.com/en/contact-us 😉
