### ISSUE TITLE
BO - Order page - Incorrect Total's product line when Round type = "Round on each item"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21708]
#### Describe the bug

In the BO > Shop Parameters > General page > Round type = "Round on each item".
When creating an order from the BO > The product's total line is NOK.
![image](https://user-images.githubusercontent.com/16067358/97862011-f1e01000-1d04-11eb-8f0e-ca9a700e8d38.png)

#### Steps to Reproduce

0. In Shop Parameters > Custom Settings > Groups > Edit Customer "Price display method" => tax included
1. Create a productA with 21% tax, €7.8 tax excluded
2. Go to BO > Order page > Add new order
3. Add the product with quantity =80
4. Create the order
5. see the error: the Total Tax included for the Product detail line is NOK

PS: reproduced when shipping is free or not.
when `Round on each line` or `Round on the total` is applied => ok (no issue)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/97862671-07096e80-1d06-11eb-9157-30bc455e4f31.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

#### Specs
Round on each item = product unit price rounded
Round on each line = total of the line rounded
https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/price-calculation-rules.md

**Comment by icemansparks** [comment]
Rounding on each line is the only working option when using the PayPal module. If another option is selected, carts with multiple items will lead to errors on the order process. 

Keeping this in mind I would hope for a fix since using PayPal as payment option is probably rarely to be considered an „edge case“.

**Comment by Gipielle** [comment]
I am touched that you have noticed this error, it has been present since prestashop 1.4 if I remember correctly.

**Comment by marionf** [comment]
To be specified:
Round on each item = product unit price rounded
Round on each line = total of the line rounded

**Comment by khouloudbelguith** [comment]
Hi!

I did not manage to reproduce the issue with PS1768
![image](https://user-images.githubusercontent.com/16067358/99260117-42825d80-281b-11eb-973e-8e9b6db008a7.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #22126
