### ISSUE TITLE
UPS Module Creates UPS --  About,  Country Setting, Terms and Conditions that send to  "500 Internal Server Error"

### ISSUE THREAD

**Issue by marciahrn** [PrestaShop/PrestaShop#21700]
Enjoying setting up a new PrestaShop, however, I have noticed a few bugs.  One that is clearly an error on the server side refers to the UPS module that install just fine.  In fact, the UPS module, after installation, creates side bar links that would become very handy.

However, the side bar links titled: 
About
Country Setting 
Terms and Conditions 

ALL go to an error page that reads:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Hoping that PrestaShop can resolve this issue.  That "something is broken" is stated really indicates that this error is on their end.

For troubleshooting, I uninstalled and reinstalled.  

Hope you can help. 

Thanks

**Comment by SimonGrn** [comment]
Hello,

please think about following the template when you submit an issue.
The problem you're facing must be addressed to the module developer.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
