### ISSUE TITLE
Edit quantity and deletion in order in BO in Multishop context : Totals are not updated

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21706]
#### Describe the bug

In a multishop context : 
If a merchant edit the quantity of a product in an order in BO, in "All shops" context, an error is displayed and nothing is changed immediately.
After refresh, the quantity is updated, but not the "Summary" part of the product block, with the totals : "Products", "Taxes" and "Total".

When adding a product : It's OK.

On 176 : Adding or editing a product : OK.

Edit : The error is "An unexpected error occurred. [PrestaShopBundle\Exception\NotImplementedException code 0]: Shop context types other than "single shop" are not supported"

Edit 2 : 
When deleting a product, the same behaviour is happening, excepted there is no error displayed. But the deletion appears at first not to be working (nothing is changed), but after refresh, the product is indeed deleted, but the totals are not updated.

#### Expected behavior

 As a user, when I am in "all shop" I can edit an order.

#### Steps to Reproduce

0. Have an install with Multishop enabled and at least two active shops
1. Go to BO > Orders > Order details
2. Edit the quantity of a product in the order : An error message is displayed and the edition is not validated
3. Refresh the page : The quantity is updated in the product line, so is the price. But the summary is not updated.
4. Change the status of the order to "Payment accepted" : The invoice only has the quantity updated, but not the total prices
5. Go to FO > Customer orders > Order details : The quantity is updated, but not the total prices.

**Screenshots**

Screenrecord : 
https://drive.google.com/file/d/1H_Y-5-eZ1zGotXcmEdz_wEFMtpqoyjz4/view?usp=sharing

Resulting invoice : 
![edit quantity multishop invoice](https://user-images.githubusercontent.com/55688534/97861994-e856a800-1d04-11eb-8961-48503560784b.png)

Order on the customer account in FO : 
![edit quantity multishop customer view](https://user-images.githubusercontent.com/55688534/97862000-eab90200-1d04-11eb-9b3d-d3ca1409b3b0.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by jolelievre** [comment]
Closed by #21721
