### ISSUE TITLE
Unable to Configure Presta Shop with Pay Pal Payment Options

### ISSUE THREAD

**Issue by marciahrn** [PrestaShop/PrestaShop#21701]
Hoping to use the PrestaShop Pay Pal payment option as it presents credit cards and, I feel, would be a better user experience than the simple Pay Pal button.

Right now we have the simple Pay Pal Button.

The module for the PrestaShop Pay Pal option allows me to connect to the PrestaShop account, however, the Pay Pal login just keeps "loading...."

The link for Pay Pal login in this module doesn't appear to be connected.  

The prerequisite for the connect is as stated, "You need to connect to both PrestaShop Checkout and PayPal accounts to activate all payment methods"  However, without the Pay Pal link enabled, that is an impossibility.

Please could you fix this?

Your help is very much appreciated.

**Comment by SimonGrn** [comment]
Dear @marciahrn 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
