### ISSUE TITLE
"The value of the PHP.ini setting "max_input_vars" must be......

### ISSUE THREAD

**Issue by marciahrn** [PrestaShop/PrestaShop#21702]
**"The value of the PHP.ini setting "max_input_vars" must be increased to 2000 in order to be able to submit the product form.**"**

Tried to find an answer to this on You Tube where I found video tutorials for PrestaShop in previous versions and foreign languages.
I was happy to find that others had had the same problem I am having.  I became elated.

I went into the root folder and found 5 php.ini files.  Each had a block of text. 

The actual php script, however, appears to be hidden.

Please could you help me with the steps to increase the "max_input_vars" to 2000 as the above instruction appears very frequently with product inclusions that include many combinations.

Important question-- may I increase the "max_input_vars" to 5,000 or 10,000-- or is it that I may only increase the "max_input_vars" to 2,000?

Also- if you could tell me how this notification could simply not appear, that would also be helpful.
My preference is, however, to increase the site's capacity.

Please help.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by SharakPL** [comment]
@marciahrn you need to update php configuration (php.ini file). Sometimes servers allow configuration by domain so you could simply create eg. `.user.ini` file in your shop domain and change your configuration there. First you need to check which paths is server checking for configuration. then simply change (create if not there) value of `max_input_vars`. This is default:

> max_input_vars = 1000

**Comment by marciahrn** [comment]
I found five php.ini files in the template download.  All five open with "right click" (Go Daddy hosting folder" > edit,  However, there are simply a few paragraphs that appear.  The php script is hidden.  How do you open the php.ini file in the hosting root folder. I have it opened to the paragraph text?
Thanks-
    On Wednesday, November 11, 2020, 07:25:58 AM EST, Sharak <notifications@github.com> wrote:  
 
 


@marciahrn you need to update php configuration (php.ini file). Sometimes servers allow configuration by domain so you could simply create eg. .user.ini file in your shop domain a change your configuration there. First you need to check which paths is server checking for configuration. then simply change (create if not there) value of max_input_vars. This is default:


max_input_vars = 1000
