### ISSUE TITLE
Dashboard "Visitors" is stuck on 31

### ISSUE THREAD

**Issue by marciahrn** [PrestaShop/PrestaShop#21703]
Enjoying the PrestaShop e-commerce build.  The dashboard is, in fact, a state of the art solution, except that-- Visitors won't increase past 31.

There have been more than 31 visitors to the site, I am sure.  

While the site is new, I am building a site for a domain name that had previously been in use for a popular sports retail store.
Within a short time the visitation went to 31 - and has remained there since.

I believe this is a PrestaShop bug.  

Please let me know if you need further information.

Thank you for your help.

**Comment by SimonGrn** [comment]
Dear @marciahrn 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
