### ISSUE TITLE
BO - Order page - An exception is displayed when changing the invoice address in the second time - Round mode = Round on each item 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21717]
#### Describe the bug

An exception is displayed when changing the invoice address the second time.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Download the United States pack from BO > International > Localization page
2. In the BO > Shop Parameters > General > set Round type = **Round on each item**
3. Create a Tax with 21% for France country
4. Create a product with Tax excluded = 7.8 euro / Tax = 21%
5. Go to FO > Add the product to the cart with quantity = 80
6. Continue checkout with `pub@prestashop.com` customer
7. In the Address step, select "My Address" (United States)
8. Place the order
9. Go to BO > Order page > view last order created
10. Change the Shipping address to "Mon addresse" (Paris)
11. Change the Invoice address to "Mon addresse" (Paris)
12. Change invoice address to "My address" (United States)
13. see the error
![image](https://user-images.githubusercontent.com/16067358/97895702-6aaa9080-1d34-11eb-8de1-b8ead0f9c751.png)

PS: if you try to add a discount / add a product / update the product ordered => error
![image](https://user-images.githubusercontent.com/16067358/97895811-8dd54000-1d34-11eb-8981-f89d374dea3c.png)

PS: 1768 => ok
#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21988
