### ISSUE TITLE
Customer name format: allow dot between characters (eg.:  Dr.med.)

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21713]
#### Describe the bug

I am importing clients from WooCommerce to Prestashop and I get error by name where someone registered as "Dr.med." 

#### Expected behavior

If someone in the imported file has Dr.med. before his name, the import will break and say the name is invalid. Of course there should be a space between Dr. and med. but since this is an import from other system, this restriction of name format should not break the import. In general the import tool is very buggy, when I was importing combinations it broke cause I had : in the combination name, I wasted a lot of time because the error was not saying where exactly and what wrong (the script didn't locate the wrong cell correctly).

There should be only necessary restrictions in the importing fields' formats, some of clients in WoooCommerce put number in their names cause they were registering as a company or something like this, all these break the import making the import process painfully long and frustrating.

#### Steps to Reproduce

Prepare csv file with fields:

- email: test@email.com
- password: testpassword
- last name: House
- first name: Dr.med. Gregory

1. Go to advanced parameters -> import
2. Choose 'customers' as import, select the created csv
3. Click next step
4. Remember to set the first row skipping accordingly to your csv.

#### Additional information

* PrestaShop version:  1.7.6.7

**Comment by matks** [comment]
Hi @grzegorzgit the dot is refused because before saving, PrestaShop checks whether this is a valid firstname and ... I have to agree that `Dr.med. Gregory` is not a customer firstname 😄 

You can simply disable this validation by rule by overriding the constraints for customer firstname to suit your needs.

Even if you disable the validation at import step, if you open later the BO "Edit a customer" page and attempt to modify something, the form will reject the data because it's not valid. So it's not a good idea to modify the validation constraints whether the data come from import or from web sign-up form. The rule must be global else you'll get inconsistencies.

**Comment by SimonGrn** [comment]
Thank you @matks !

I close this issue, you can still answer and discuss.

**Comment by grzegorzgit** [comment]
I can't believe you just replied this way and closed the ticket! Of course Dr.med. is not a part of the name, but this makes Prestashop import totally useless! How can you not see this is a serious issue of a store when it doesn't give an option for people to put their degree like this? Our clients are mostly people working on universities, and such thing can happen, PS should be prepared for this, and not get broken because of this!

Can you please tell me, what is the advantage of not allowing the dot there like this? What is this such important thing that requires this restriction? System should be prepared for such situations, and PS not only is not, but you say that it is totally fine...

**Comment by kpodemski** [comment]
You can create your own validation rules by editing Validate class.

To be honest I've never seen store with people registering with their degree, those strict rules about dots are related to spam issues from recent years, it's almost impossible to handle every scenario here, but this is software with open source and you can easily change validation method however you like.

**Comment by matks** [comment]
> I can't believe you just replied this way and closed the ticket! Of course Dr.med. is not a part of the name, but this makes Prestashop import totally useless! How can you not see this is a serious issue of a store when it doesn't give an option for people to put their degree like this? Our clients are mostly people working on universities, and such thing can happen, PS should be prepared for this, and not get broken because of this!

@grzegorzgit PrestaShop aim is to be a eCommerce CMS targeting a large audience. Most "regular" customers do not use a dot inside firstname.

Maybe in your usecase your clients are mostly people working on universities, but as you said it's _your_ usecase. You must understand this software has not been built for you specifically. This software has been built to be used by thousand of people with a lot of different usecases, so it aims at being generic.

Obviously when the target is to be generic, it does not fit everybody's usecase. But this is why PrestaShop is extensible: through modules, overrides, themes, decorations you can customize PrestaShop behavior to fit your needs. But the main software will remain generic, to accommodate the needs of many.

> Can you please tell me, what is the advantage of not allowing the dot there like this? What is this such important thing that requires this restriction? System should be prepared for such situations, and PS not only is not, but you say that it is totally fine...

You will find details here https://github.com/PrestaShop/PrestaShop/pull/13604

@kpodemski oh, we said the same thing 😄

**Comment by grzegorzgit** [comment]
@matks OMG man, seriously? Because PS is used by many people all over the world it should be flexible and universal! And not tailored only for teenagers selling t-shirts to their friends! People with degrees are regular clients who are major customers of many industries. This is so disrespectful what you just wrote, it should be stated on PrestaShop homepage so people know what approach creators of this software have - to avoid it. 

@kpodemski if you have degree then you usually type it before your name. As I said, just because you use online shopping only to buy your t-shirt it doesn't mean that this is how everybody else use it. There are many industries aiming people with higher degree and such thing can happen - it is nothing exceptional. Also, I could change the store, thank you for assuming my coding skills... But why would I have to? My job can't focus on constant changing PS code (which I do a lot, cause you guys want to make money on modules).

And about the case of url in the name. In our store people can't write public comments, and in plenty of other stores publishing content is not allowed, therefore the name isn't shown anywhere - the issue of spam doesn't exist.  So the smart solution would be to put the name validation so strict only when customers can publish something (which in my opinion is minority of stores). The stupid solution would be to say "let's block it and refuse a lot of industries to use Prestashop".

**Comment by SimonGrn** [comment]
Hello @grzegorzgit 
please remember we have a Code of Conduct which you are clearly violating right now.
Your behavior is not acceptable, you're talking to real humans. You also seem missing the point of Open Source and the open community as a whole.
As a result, I lock this thread to prevent it from drifting further.

Thank you for your understanding.
