### ISSUE TITLE
Order paypal issue 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#21711]
Hello

the costumer did pay on the website i received the money on paypal but the order has not been placed on the backoffice 

This is not the first i checked even the abandoned order does not show it

Version de PrestaShop : 1.7.6.6
Version du logiciel serveur : Apache
Version de PHP : 7.2.34
Limite de mémoire : 100128M
Temps maximal d'exécution : 9000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

It seems that your issue is not a PrestaShop core bug. 
If your module is PayPal Official, please contact support team on [Addons](https://addons.prestashop.com/en/contact-us?id_product=1748)

We will close this issue.

Thanks!
