### ISSUE TITLE
Avoid global markup duplicate in checkout.tpl

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#21719]
#### Is your feature request related to a problem?

In classic theme, `templates/checkout/checkout.tpl` file redefine global markup (`<html><head>...</head><body>....</body></html>`) instead of use Smarty template inheritance.

#### Describe the solution you'd like

Use Smarty template inheritance to avoid duplicate of global markup. I'll make a PR soon.

**Comment by hibatallahAouadni** [comment]
Hi @micka-fdz 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

Thanks!

**Comment by marionf** [comment]
I think it's rather a question for @PrestaShop/prestashop-core-developers and maybe @NeOMakinG

**Comment by Progi1984** [comment]
@marionf : @NeOMakinG has discussed with @micka-fdz on the PR

**Comment by NeOMakinG** [comment]
It's a great improvement that should be done and shouldn't introduce BC change at all
