### ISSUE TITLE
FO - The precision of Discounts NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21720]
#### Describe the bug

In the FO > Cart detail page > The precision of Discounts NOK

#### Steps to Reproduce

0. Round mode = same issue in all cases
1. Go to BO > International > Currencies > change currency euro **precision =3** 
2. Create a Tax 22% / Create a Tax 21%
3. Create a ProductA => tax excluded = 29 euro / tax =22%
4. Create a ProductB => tax excluded =7.8 euro / tax = 21%
5. Create a cart rule  with a code "Free shipping + 1.5677 euro tax included + gift product( = 7.8 tax excluded ProductB)
![image](https://user-images.githubusercontent.com/16067358/97897608-02a97980-1d37-11eb-983c-8e532e9f753c.png)
6. Go to FO > Select Euro as a currency
7. add a productA to the cart
8. apply the discount
9. see error
![image](https://user-images.githubusercontent.com/16067358/97898548-4a7cd080-1d38-11eb-8823-784177454014.png)

1768
![image](https://user-images.githubusercontent.com/16067358/97898644-6b452600-1d38-11eb-9baa-e58062cd95e0.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by marionf** [comment]
@khouloudbelguith Are you ok to close this issue as the discount amount is the good one ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes!
As discussed in the meeting.
`11.006` is the best one.
Discount total = round (total amount discount + Shipping fee + Total of the gift product )
`11.006 = round (1.5677 + 0 + 9.438) = round (11.0057) = 11.006`

Thanks!
