### ISSUE TITLE
Cart to to zero -- Empty basket -- cannot log in BUG Prestashop 1.6.1.17

### ISSUE THREAD

**Issue by Guillermo580** [PrestaShop/PrestaShop#21723]
1. We have a random bug problem since 1.5 year ago in our prestashop 1.6.1.17.  The console , after the bug reproduce show us the following ( image attached):

![image](https://user-images.githubusercontent.com/73864603/97945752-33a1a280-1d67-11eb-9895-aa7fc1547f7b.png)

****_**__Set-Cookie header is ignored in response from url: https://www.elcontainer.cl/?rand=1602073743731. Cookie length should be less than or equal to 4096 characters._**_**_** 

When this bug reproduce into a client, also dont let him LOG IN.

The bug its documented here, but for us the solution didnt work. https://www.prestashop.com/forums/topic/621360-solved-conflicting-cookies-cant-login-or-add-to-cart/

From a prestashop agency told us the following:, they put a cookie log capturer and they said that this cookies are generating the problem: https://prnt.sc/uymtgp  . 
"_I think these cookies are generating issue because I have remove the code of generating this cookie and replied you in the morning. See the second array there are no random cookie there_.  "

After they made that, the bug dissappear but after browsing for a while, bad request 400 appear, so the executive has to roll back that change.

They said: **_Your prestashop file system have many core files, code modified which is not the proper way, I can see many files on your side is renamed having backup, in your cookie.php file many codes are commented._**

**_You have applied inappropiate cache which is failing on code modifying._**

**_Your site is having many issues for a developer to work, I can not touch your server now without any idea or information._**

The bug its very random, and in incognito mode didnt reproduce. So its a cookie issue.

If its a core issue, from Chile its almost impossible to fix it. There is no specialist on Prestahop Here.

Any help guys?
I will apretiatte.

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @Guillermo580 ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

PS: You're absoluty not allowed to rewrite Core files, you need to override it ([see the document](https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/))

Thank you

**Comment by davidcylke** [comment]
I had the same issue in 1.7.7.5...
Did you find the solution @Guillermo580  ?
