### ISSUE TITLE
Cover photo not used for /img/tmp/product_mini_

### ISSUE THREAD

**Issue by zzzZZZzzz9** [PrestaShop/PrestaShop#21731]
**Describe the bug**
In both of my shops, PS uses /img/tmp/product_mini_ images for cart and order view in the backend as well as invoices.
However, this image is not the cover image selected by me but always the image with the lowest image ID.

E.g. for [this item](http://test.littlepippa.de/baden-wickeln/200-835-mushie-stapelturm-becher.html#/97-farbe-pastell), the frontend cart correctly shows [this image](http://test.littlepippa.de/1476-cart_default/stapelturm-becher.jpg). product_mini, however, looks [like this](http://test.littlepippa.de/img/tmp/product_mini_200_835.jpg) because it is generated from the product image [with the lowest ID ](http://test.littlepippa.de/1472-cart_default/stapelturm-becher.jpg).

All my products are combinations. The view in Catalog -> any product -> Combinations is correct as it uses small_default.jpg.

**Expected behavior**
I would expect product_mini to be generated from the products' respective cover images

**Steps to Reproduce**
- Find a product (ideally a combination product) where you have a cover image that is NOT the one with the lowest ID
- Check product_mini_ image in order or cart view containing this product

**What I have tried:**
- empty /img/tmp/ -> newly generated images are wrong again
- change cover image -> no effect, still lowest ID chosen for product_mini

PS 1.7.6.7 | Classic Theme | PHP 7.2 | MySQL 5.7

**Comment by hibatallahAouadni** [comment]
Hello @zzzZZZzzz9 

I managed to reproduce your issue with PS1.7.6.8 but I didn't reproduced with PS1.7.7.0_beta1 and PS1.7.7.0_beta2.
I've attached a screen record:

https://drive.google.com/file/d/1mlYt7tZd4xV4TL2i2tJ70FDeeDG3dL_y/view

So it seems fixed with our newest version.
Could you please check and feedback.

Thanks!

**Comment by zzzZZZzzz9** [comment]
Hi @hibatallahAouadni 

Yes, I can confirm this seems to be fixed in 1.7.7.0 - thank you for checking.

Can you provide any insights regarding the release timeline?

**Comment by hibatallahAouadni** [comment]
Hi @zzzZZZzzz9 

To be informed when it get released, subscribe to this issue #18647 
So, I close this ticket.
