### ISSUE TITLE
Input lag in BO > Create order > Cart

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21734]
#### Describe the bug

On BO > Create order, in the cart, when updating the quantity of a product using the "up/down arrow" with consecutive hits on the same input, it's not acknowledged correctly.

For example, I'm at 6. I hit 3 times the "up" arrow, the counter goes up to 9 and then goes back to 7.

It's OK when adding the product

#### Expected behavior

All inputs should be taken into account

#### Steps to Reproduce

1. Go to BO > Create Order
2. Select and customer and add a product
3. Increase the quantity by clicking multiple times on the "up" arrow, fast enough
4. The quantity is not well updated

**Screenshots**

https://drive.google.com/file/d/1e0fqUhsqojurQ_xbQdUwAY1m54wzT0Tu/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.0 RC1 Build 4
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

I manage to reproduce the issue with PS1770rc1build1 also.

Thanks!

**Comment by Progi1984** [comment]
Fixed by #21977
