### ISSUE TITLE
Cannot receive blank schemas for resources

### ISSUE THREAD

**Issue by Wilczur07** [PrestaShop/PrestaShop#21748]
#### Bug description

Getting error [PHP Notice # 8] Trying to access array offset on value of type null (D:\presta\htdocs\classes\webservice\WebserviceOutputBuilder.php, line 716)

#### Expected behavior

Receive a blank body of resource

#### Steps to Reproduce

1)Make GET call to an PrestaShop api : api/products?schema=blank
2)See error

#### Additional information

Same thing happening for other resources, almost all to be honest. Only some of them work for me, for example i'm able to get the blank schema for "configurations".

* PrestaShop version:  1.7.6.8
* PHP version: 7.4.11

**Comment by hibatallahAouadni** [comment]
Hello @SzooX 

Please downgrade your PHP version to 7.2 cause PS1.7.6.8 is not compatible with PHP 7.4 (as you can see in our system requirement [document](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/))

Please check and feedback.

Thanks!

**Comment by Wilczur07** [comment]
Downgrading php resolved an issue. Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @SzooX 

It seems your issue has been solved. So, I close the issue.

Thanks!
