### ISSUE TITLE
Shopping cart doesn't update product number badge (ajax) when updating product quantity in cart product line

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#21749]
#### Describe the bug

Shopping cart doesn't update product number badge (ajax) when updating product quantity in cart product line.

#### Steps to Reproduce

1. Add a product to the cart
2. Go to cart page and update the product quantity or remove the product from the cart.
3. The product number badge in the top right corner [Cart (1)] doesn't update the number of products. Ajax cart is enabled.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* ps_shoppingcart version: 2.0.3
* PHP version: 7.2.3.4

**Comment by rdy4ever** [comment]
https://github.com/PrestaShop/ps_shoppingcart/pull/68/commits/71642574e43a293e3ddc6a559ed7464db740e62c

**Comment by hibatallahAouadni** [comment]
Duplicate of #19733
