### ISSUE TITLE
Validation message not displayed when Enable/Disable webservice keys by bulk actions

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#21745]
#### Describe the bug

There is no validation message when Enable/Disable webservice keys by bulk actions

#### Expected behavior

Validation message should be displayed after enabling or disabling a webservice key

#### Steps to Reproduce

1. Go to 'Advanced parameters>Webservice'
2. Click on 'Add new webservice key'
3. Select the created webservice key  
4. Click on 'Bulk actions button> Enable or Disable'
5. There is no validation message

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0 -  1.7.6.8
* PHP version: 7.2

**Comment by matks** [comment]
Hello @Progi1984 I see you assigned yourself in November 2020. Did you do something? Will you continue to work on it?

**Comment by Progi1984** [comment]
Yeap
