### ISSUE TITLE
Multistore - Stocks page - The message is not well displayed in all shops or in a group context

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21741]
#### Describe the bug

Currently, the stocks page isn't working in all shops or in a group context.
We have an alert when we select all shops or in a group context.
This alert is not well displayed.

![image](https://user-images.githubusercontent.com/16067358/98087179-04cb1f80-1e80-11eb-8624-9b8e2eae1fd4.png)

#### Steps to Reproduce

Enable multistore
create a second shop
go to Catalog > Stocks page
select all shops context / a group context 
see error

#### Additional information

* PrestaShop version: 1.7.6.8, 1.7.7.0rc1build4, develop(1780)
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
Looks fixed
