### ISSUE TITLE
Product Combination Prestashop 1.7.6.8

### ISSUE THREAD

**Issue by finawebshop** [PrestaShop/PrestaShop#21757]
Hi Friends, I need help in creating Product with Combinations. I am new to prestashop and just installed version 1.7.6.8.

The shop URL is https://shopnew.fina.org/
For the product 'NF Affiliation Fee'; i selected the combinations option.
I have an attribute called 'Year' with values 2015, 2016, 2017, 2018, 2019, 2020 and 2021 (in dropdown field).

Now, within the combinations tab when I select all the attribute values and click on Generate; on top right the notification displayed is 'Unable to update settings' in red background instead of 'settings updated' in green background.

In the debug mode, within the AJAX requests (validator section on right menu of symfony profiler); I see that

For paths-
children[combination_68].children[attribute_ecotax].data
children[combination_68].children[attribute_minimal_quantity].data

the message is "This value should not be blank."
This is repeated 7 times for the 7 different attribute values of Year.

1) What is that am missing here?

Please note that the "save" action for saving this combination details just shows the spinning blue circle but the product is not saved with the dropdown values of year on the front end.

Further, the details within the tab "Bulk actions (0/0 combination(s) selected)keyboard_arrow_down" even after saving the value for 'minimal quantity' value as 1 does not get saved.
2) what is wrong here?

3) Finally, how can I maintain the stock for each of this combination?

Please help me. If such an issue is already tackled previously for the same version of Prestashop, then I request someone to redirect me to the particular issue number.

Let me know if more information is required from my end. Attached screenshot is from the debug mode.

![Screenshot 2020-11-04 at 18 03 42](https://user-images.githubusercontent.com/73956282/98142465-1df7be80-1ec8-11eb-8889-2bdfd49800c7.png)

![Screenshot 2020-11-04 at 18 04 43](https://user-images.githubusercontent.com/73956282/98142598-48497c00-1ec8-11eb-8959-478b601fd257.png)

regards
Pritam

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
