### ISSUE TITLE
Blockreassurance - URL not available in front office

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#21752]
#### Describe the bug

in the module https://github.com/PrestaShop/blockreassurance v5.0.0, the URL of one element is not available in the front office and in the `$elements` variable, when used as a widget.

#### Expected behavior

Get all informations of fields available in backoffice in the front office

#### Steps to Reproduce

Install the module in the last version, 
create one or many block reassurance elements with a link of CMS page (for exemple).

Display them on front office by using the module like a widget.

**Screenshots**

dump of `$elements`variable:
![Capture d’écran 2020-11-04 à 17 01 41](https://user-images.githubusercontent.com/4788787/98134897-84c4aa00-1ebf-11eb-9fee-f1654290a716.png)

Table `ps_psreassurance`:
<img width="1296" alt="Capture d’écran 2020-11-04 à 17 04 01" src="https://user-images.githubusercontent.com/4788787/98135106-c05f7400-1ebf-11eb-891b-7b904bb8aad3.png">

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by matks** [comment]
Hi @PrestaSafe I changed your issue a little because this only applies to the usecase "where the blockreassurance module v5.0.0 is used as a widget". When using regular hooks, full informations are available as Smarty variables.

I checked the code, I dont know why but indeed only few informations are built as Widget variables. For hooks full informations are provided. As it was fast to fix, I did the PR https://github.com/PrestaShop/blockreassurance/pull/60/

**Comment by matks** [comment]
Note: it's not a bug 😛 as nothing is failing. It's rather a limitation of the module (and it will be nice to remove the limitation ^^)

**Comment by Progi1984** [comment]
@matks I take the issue. I discuss it with @PrestaSafe on FoP ;)

**Comment by matks** [comment]
> @matks I take the issue. I discuss it with @PrestaSafe on FoP ;)

All right 😉  be my guest!

You can use PR https://github.com/PrestaShop/blockreassurance/pull/60 or make your own. But you'll need, like I found out, to fix blockreassurance first - it seems to fail because of Composer v2 😞

**Comment by matks** [comment]
PR started in https://github.com/PrestaShop/blockreassurance/pull/60 but I could not push it to the merge

**Comment by matks** [comment]
PR by @leemyongpakvn for this issue ;) https://github.com/PrestaShop/blockreassurance/pull/455/
