### ISSUE TITLE
Impossible to add a cache server 

### ISSUE THREAD

**Issue by awerner25** [PrestaShop/PrestaShop#21768]
Hello,

I use the prestashop docker image.
I want to add a memcached server.

![Capture d’écran du 2020-11-05 11-52-11](https://user-images.githubusercontent.com/59097333/98232146-98265280-1f5d-11eb-9d33-ba102b3218ff.png)

But when I clic on "Test the server", I have an exception :
![Capture d’écran du 2020-11-05 11-51-21](https://user-images.githubusercontent.com/59097333/98232236-b429f400-1f5d-11eb-9830-f6370f4acde4.png)

Stacktrace : 
```
Symfony\Component\Debug\Exception\UndefinedFunctionException:
Attempted to call function "memcache_connect" from namespace "PrestaShop\PrestaShop\Adapter\Cache".

  at src/Adapter/Cache/MemcacheServerManager.php:95
  at PrestaShop\PrestaShop\Adapter\Cache\MemcacheServerManager->testConfiguration('cache', 11211)
     (src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/MemcacheServerController.php:71)
  at PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\MemcacheServerController->testAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin465hsmfd4/index.php:86)
```

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by kpodemski** [comment]
@darkvodka 

You just don't have proper extension installed on your server
