### ISSUE TITLE
Error Bono descuento, valor minimo envio gratis y calculo de valor descuento con impuestos excluidos

### ISSUE THREAD

**Issue by barbosatrix** [PrestaShop/PrestaShop#21760]
1. Creo un bono de bienvenida con valor de $25000 pesos. Envío incluido, impuestos incluidos 

2. Tengo un transportista con envío gratis después de $100000

3. Cuando el importe lo dejo de 25000 impuestos incluidos aparece el valor correcto en el carro pero no deja realizar la compra si es mayor a $100000, se devuelve a la pantalla home del      sitio.

4. Cuando el importe lo dejo de 25000 impuestos excluidos, aparece un valor distinto, superior a $25000, variable según el valor de los impuestos

    ,y con un rango entre los $1500 a $2000 si hago compras de 100mil a 200 mil,

    Aunque de esta forma si me deja realizar el pago.

5. No entiendo porque sucede esto. La pagina es cmerka-qa.cclcloud.co 

Estas son las imagenes de las configuraciones:

https://prntscr.com/vcnzep

https://prntscr.com/vcnz5a

https://prntscr.com/vcnz0h

https://prntscr.com/vcnyba

**Comment by matks** [comment]
Hi @barbosatrix I'm sorry but we only speak/write English here, could you please translate your issue ?

**Comment by SimonGrn** [comment]
Hello,
Please send your request in English. English is the norm on GitHub. Please also follow the template.

Thank you
