### ISSUE TITLE
When stock management is disabled, the available quantity in order detail is displayed

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#21767]
#### Describe the bug

When stock management is disabled, the available quantity in order detail is displayed

#### Expected behavior

When stock management is disabled, the available quantity in order detail shouldn't be displayed

#### Steps to Reproduce

1. Go to Shop parameters > Product settings
2. Disable stock management
3. Go to Orders > Orders > View an order
4. The "available" quantity is displayed while it shouldn't

**Screenshots**

**1.7.7**
![capture d'écran_2851](https://user-images.githubusercontent.com/13449658/98228253-a1f98700-1f58-11eb-9b8f-f6c6fe0b6725.png)

**1.7.6**
![capture d'écran_2852](https://user-images.githubusercontent.com/13449658/98228378-cd7c7180-1f58-11eb-9a96-8bb64e42d1e9.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #22082
