### ISSUE TITLE
Disable automatic backorder status.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21766]
#### Is your feature request related to a problem?

Prestashop automatically set "on backorder" status when someone bought products out of stock. 
It should not happen, our payment module sets the status of "paid with card" or "awaiting bank transfer", but when product is out of stock PrestaShop forces to change the status of "backorder" which for us is totally useles.

I know I can disable the mail sending, or change the name of this status. But this is not a solution. Our modules depend on exact statuses they set, PrestaShop cannot decide itself whether to set desired by module status or its own "on back order".

Method ValidateOrder() should always accept the status that is provided in its arguments, and not any other.
#### Describe the solution you'd like

Class PaymentModule should not have automatic switching to onbackorder status. Maybe give the method additional argument with boolean "check product stock"? It is line 560 of class PaymentModule.php

**Comment by hibatallahAouadni** [comment]
Hello @grzegorzgit 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by LouiseBonnard** [comment]
What do you think, @PrestaShop/prestashop-core-developers?

**Comment by PierreRambaud** [comment]
> What do you think, @PrestaShop/prestashop-core-developers?

It's up to you to answer :sweat_smile:

**Comment by Hlavtox** [comment]
I would do this configurable and add a new toggle to Prestashop Order settings. "Change order status to backorder if ordered products are not in stock".

The first thing I removed from a fresh PS install. :-)

**Comment by kpodemski** [comment]
Updating the label as it was accepted inside the related Pull Request too.
