### ISSUE TITLE
BO product list column Final Price with active discount impact

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21774]
Guys im struggling with that feature to display product prices with active discount impact (retail final price for customer including current specific prices/discounts)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by matks** [comment]
@PrestaShark it will be easier to discuss it on Slack 😉  come join us ! https://join.slack.com/t/prestashop/shared_invite/zt-dkmbz5qf-I~FlEWwmRUOXunc5ui0Ucg
