### ISSUE TITLE
FO - Product with combinations - Incorrect image displayed 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21775]
#### Describe the bug

In the FO, when we add a product with combinations to the cart, the cover image is displayed instead of the Product's image selected.
![image](https://user-images.githubusercontent.com/40635814/107627559-c3f15c80-6c5f-11eb-9440-7e2e0eaceb28.png)
This issue occurs in 

- ~~Product successfully added to your shopping cart Pop up~~ => Fixed
- ~~Shopping cart page~~ => Fixed https://github.com/PrestaShop/PrestaShop/pull/24248
- Checkout page ( cart summary details)
- Order final summary
- Order confirmation page

#### Steps to Reproduce

1. Go to FO
2. Select first product "Hummingbird Printed T-Shirt"
3. Add the Combination  Size-S, Color-Wite
4. Go to cart (or cart summary in checkout page, order final summary or order confirmation page)
5. See an error

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by SD1982** [comment]
Not fixed i reopen the issue
![image](https://user-images.githubusercontent.com/40635814/107627549-bdfb7b80-6c5f-11eb-89e8-b76f75de6b78.png)
![image](https://user-images.githubusercontent.com/40635814/107627559-c3f15c80-6c5f-11eb-9440-7e2e0eaceb28.png)

**Comment by SD1982** [comment]
This issue is not fixed i reopen it
![image](https://user-images.githubusercontent.com/40635814/107627656-e8e5cf80-6c5f-11eb-85d5-4a4b441a65ce.png)

![image](https://user-images.githubusercontent.com/40635814/107627646-e3888500-6c5f-11eb-8177-64551f5522dc.png)

**Comment by alfonsolr09** [comment]
https://youtu.be/vJC36vfO0OM

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud  in #24430
