### ISSUE TITLE
Customer view addresses & vouchers tables are not display well

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#21778]
#### Describe the bug

There is a gap between the table head and the table body and a border on the page customer view, in the *vouchers* & *addresses* table.
![Capture d’écran 2020-11-05 à 16 51 48](https://user-images.githubusercontent.com/2168836/98264956-c40afd80-1f88-11eb-9c19-ce4cd784892f.png)

#### Expected behavior

It should be looking like that instead:
![Capture d’écran 2020-11-05 à 16 54 13](https://user-images.githubusercontent.com/2168836/98264804-958d2280-1f88-11eb-9a43-005e768aa235.png)

#### Steps to Reproduce

1. Go to BO > Discounts page
2. Create a Voucher for a specific customer (for example "John Doe")
3. Go to Customers > Customers
4. Select the customer "John Doe" and go to the customer detail page
5. See the *Vouchers* table and the *Addresses* table

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @atomiix 

I managed to reproduce the issue with Develop but with PS1.7.7.0-rc.1+build.4 seems displayed well

![image](https://user-images.githubusercontent.com/23308427/98266142-3d572000-1f8a-11eb-9fe2-b69e6439978b.png)

I think it's regression.

Thanks!
