### ISSUE TITLE
Module Avis clients introuvable

### ISSUE THREAD

**Issue by RachelB34** [PrestaShop/PrestaShop#21772]
Bonjour, je ne retrouve plus ce module sur ma version 1.7.5.2 ?
Comment faire pour le re installer? 

Merci

**Comment by hibatallahAouadni** [comment]
Hello @RachelB34 ,

Please send your request in English. English is the norm on GitHub.

Thanks!

**Comment by RachelB34** [comment]
Customer reviews module not found
Hello, I no longer find this module on my version 1.7.5.2?
How to re-install it?

**Comment by hibatallahAouadni** [comment]
Hi @RachelB34 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You
must follow the template to submit a complete bug report*.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bugreports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
@RachelB34 this might be what you are looking for https://github.com/PrestaShop/productcomments

**Comment by RachelB34** [comment]
@matks Thank you, I downloaded and installed it on my FTP but it still does not appear in my module manager.

**Comment by khouloudbelguith** [comment]
Hi @RachelB34,

The productcomments module is compatible minimum with PS1.7.6.0
https://github.com/PrestaShop/productcomments/blob/dev/productcomments.php#L61

Thanks!
