### ISSUE TITLE
Customer reviews module not found

### ISSUE THREAD

**Issue by RachelB34** [PrestaShop/PrestaShop#21773]
Hello, I no longer find this module on my version 1.7.5.2?
How to re-install it?

**Comment by hibatallahAouadni** [comment]
Hello @RachelB34 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
