### ISSUE TITLE
Consider configuration PS_ATTRIBUTE_ANCHOR_SEPARATOR in BO when building combination name

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#21788]
This is a reminder issue for Product page migration issued here https://github.com/PrestaShop/PrestaShop/pull/20518#discussion_r517874837

When generating BO combination names the `PS_ATTRIBUTE_ANCHOR_SEPARATOR` config was not taken into account up until now. Should we add it?
Discussed in slack with @MatShir @matks @jolelievre

**Comment by PierreRambaud** [comment]
Afaik, we should add and use it like it's used in the CartPresenter.
