### ISSUE TITLE
Error in Custom Fields

### ISSUE THREAD

**Issue by dgonzalez-conex** [PrestaShop/PrestaShop#21785]
Hi.
I have an online store in Prestashop 1.7.6.0
I have created several products for sale.
In the product file I have added numerous "custom fields" to collect buyer data.
The problem is that in the front office, in addition to the fields, the data of a previous buyer is displayed under the fields.
This is a violation of the GDPR.
We are reviewing the code to hide this sensitive information, but I need urgent help so that it does not happen again.
Thank you.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
Hi @dgonzalez-conex if this is a bug could you explain how to reproduce it following [this template](https://github.com/PrestaShop/PrestaShop/issues/new?template=1_bug_report.md) 😉
