### ISSUE TITLE
BO - Order page - An exception is displayed in the console when adding a product out of stock 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21794]
#### Describe the bug

In the BO > Orders > Add new order page > when we try to add a product out of stock (which is not allowed) => an exception is displayed in the console
![image](https://user-images.githubusercontent.com/16067358/98386519-91c4d300-2050-11eb-8ba5-bb029e30cfbb.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/98386799-e6684e00-2050-11eb-8441-251bc8728d4c.png)

#### Steps to Reproduce

1. Create a product out of stock (Deny orders)
2. Go to BO > Orders page > Add new order page
3. Add the last product created to the cart

PS:1770rc1build4 => ok
#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21830
