### ISSUE TITLE
Customer Groups Members list search

### ISSUE THREAD

**Issue by baskettcase** [PrestaShop/PrestaShop#21791]
#### Describe the bug

When searching Customers within Customer Groups it takes you back to the groups instead of staying within the list of customers in that group page.

#### Expected behavior

I expected that it would stay on the same page with the search results.

#### Steps to Reproduce

1. Go to "Shop Parameters" > "Customer Settings"
2. Click on "Groups" tab
3. Click on any "Group name"
4. You should see a list of customers within that group, do a search using any field

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @baskettcase ,
This bug has been fixed in PS 1.7.7. Please check the screen record : https://drive.google.com/file/d/1BOGrUCHZNLku7KXEqoaN1DHmq3KoX4eW/view
So I'll close your issue.
Thank you for your understanding !
