### ISSUE TITLE
ps_linklist creates orphan blocks

### ISSUE THREAD

**Issue by danielkauffman** [PrestaShop/PrestaShop#21802]
#### Describe the bug

When using ps_linklist to create blocks of links, it is possible to create orphan blocks that can not be deleted from the BO.

#### Expected behavior

It should not be possible to create orphan blocks of links. The database should roll back to a consistent state when one step in a process fails.

#### Steps to Reproduce

1. Go to BO > Improve > Design > Link Widget.
2. New Block. Enter a short title. Click save.
3. New Block. Enter a very long title. Click save. Note the error message.
4. New Block. Enter a short title. Click save.
5. Note that the position skips a number. This is because there are orphan blocks in the database.
6. Check the database and confirm that ps_link_block has more entries than ps_link_block_lang. Note that these additional entries are not accessible in the BO.

#### Additional information

* PrestaShop version: 1.7.7.0 RC 1

**Comment by SimonGrn** [comment]
Hello,

Could you explain the consequences of this issue? Is the second block in your example visible from the FO?

**Comment by danielkauffman** [comment]
@SimonGrn The second block is partially visible from the FO: The fields that are part of the ps_link_block table are visible while the fields that are part of the ps_link_block_lang table are not visible. If you look at the tables in the database, the record exists in the ps_link_block table but not the ps_link_block_lang table. I think when the record is saved, the fields are saved to the ps_link_block table, and then when the extra long title is saved to the ps_link_block_lang table, an error is thrown that prevents that record from being saved, but the first record isn't deleted. So the record ends up being saved to only one table instead of to both tables.

**Comment by danielkauffman** [comment]
@SimonGrn more seriously, because the record is not saved to the ps_link_block_lang table, the orphan record can not be deleted from the ps_link_block table using the BO. So the partial record exists, affects the FO, and can not be edited or deleted from the BO. The only way to delete this record is directly in the database.

**Comment by hibatallahAouadni** [comment]
Hello @danielkauffman 

I managed to reproduce your issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.4 (see screen record below)

https://drive.google.com/file/d/18Jqkjb2nDNOXodg9dZQIicr2xbpswRq7/view

I attached also a screen shot of ps_link_block table: 

![image](https://user-images.githubusercontent.com/23308427/98532547-22362a00-2282-11eb-9771-217411e42489.png)

As we can see the link with long name was already created on this table, but not created in the ps_link_block_lang table:

![image](https://user-images.githubusercontent.com/23308427/98532887-940e7380-2282-11eb-9fa4-d3d3f0ae1a2c.png)

We only can see the links created with short names.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by matks** [comment]
> It should not be possible to create orphan blocks of links. The database should roll back to a consistent state when one step in a process fails.

@zuk3975 @jolelievre are currently pushing forward the idea of supporting InnoDB transactions in PrestaShop 😛

**Comment by zuk3975** [comment]
> > It should not be possible to create orphan blocks of links. The database should roll back to a consistent state when one step in a process fails.
> 
> @zuk3975 @jolelievre are currently pushing forward the idea of supporting InnoDB transactions in PrestaShop

https://github.com/PrestaShop/PrestaShop/pull/21740 here is the PR with some discussions inside

**Comment by hibatallahAouadni** [comment]
@kpodemski is this bug fixed or not yet?

**Comment by kpodemski** [comment]
@hibatallahAouadni it's part of v5, https://github.com/PrestaShop/ps_linklist/pull/118

I guess it needs to be validated and then we can close this PR, I closed it earlier by mistake.

**Comment by hibatallahAouadni** [comment]
@kpodemski ok thanks :relaxed:

**Comment by hibatallahAouadni** [comment]
This issue will be closed when ps_linklist v5 is released
