### ISSUE TITLE
Unhook module through Theme.yml

### ISSUE THREAD

**Issue by alouimohamedhabib** [PrestaShop/PrestaShop#21805]
The requested featured is to add the possibility to unhook modules from certain hooks through the **theme.yml** .
` hooks:

    modules_to_unhook:
      displayTop:
        - ps_searchbar 
`

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report or an improvement**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
