### ISSUE TITLE
Differnet PayPal Transaction ID

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21801]
#### Describe the bug
I use the PayPal module for checkout. After checkout there is displayed PayPal transaction ID in order confirmation page. But in the PayPal merchant account there is displayed other number as PayPal transaction ID. Why isn't  the same ID?

#### Expected behavior
The same PayPal transaction ID should be used in PS and PayPal

#### Steps to Reproduce
1. Create an order in FO and checkout with PayPal
2. Compare PayPal transaction ID in order confirmation page with transaction ID in the merchant PayPal account 

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment]
Hello @juraj1000 

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on [Addons](https://addons.prestashop.com/en/contact-us?id_product=1748)

We will close this issue.

Thanks!
