### ISSUE TITLE
Image titles are empty, if image legend is empty - FO

### ISSUE THREAD

**Issue by Peter-Liska** [PrestaShop/PrestaShop#21806]
#### Describe the bug

HTML image TITLE is empty, if image legend is empty.

#### Expected behavior

HTML image TITLE should not be empty, if image legend is empty.
It should be filled with product name.

#### Steps to Reproduce

1. Go to product listing (for example) and view page source.
2. Check the product image with empty image legend.
3. You can see, that only ALT attribute is filled.
4. If you check product image with legend instead - you can see that both  ALT and TITLE attributes are filled

### Additional infos
* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Peter-Liska 

I managed to reproduce the issue with PS1.7.6.5, Ps1.7.6.8 and PS1.7.7.0-rc.1+build.4.
I attached a screen record below:

https://drive.google.com/file/d/1rYIs6ukR8XgNnntMV4oDcj6Ut-r7Vz_e/view

And could you please check if your issue is similar to this one #10236

I don't know if it is a bug or PrestaShop limintation (it means what you proposed it's an improvement).
So, ping @PrestaShop/prestashop-core-developers wdyt?

Thanks!

**Comment by rdy4ever** [comment]
> Hello @Peter-Liska
> 
> I managed to reproduce the issue with PS1.7.6.5, Ps1.7.6.8 and PS1.7.7.0-rc.1+build.4.
> I attached a screen record below:
> 
> https://drive.google.com/file/d/1rYIs6ukR8XgNnntMV4oDcj6Ut-r7Vz_e/view
> 
> And could you please check if your issue is similar to this one #10236
> 
> I don't know if it is a bug or PrestaShop limintation (it means what you proposed it's an improvement).
> So, ping @PrestaShop/prestashop-core-developers wdyt?
> 
> Thanks!

I don't think it is a bug, or even a needed improvement. Actually, I don't think it should be implemented at all. The image "title" attribute is not required. It's not used by screen readers or search spiders. It's just a tooltip that can add more information to a picture. If you want to display more information about the product picture, then you use the image legend field in the BO. If you don't need to display more info, you leave it empty. 

[From yoast seo:](https://yoast.com/image-seo-alt-tag-and-title-tag-optimization/)
> Each image should have an alt text. Not just for SEO purposes, but also because blind and visually impaired people won’t otherwise know what the image is about. A title attribute is not required. What’s more, most of the time it doesn’t make sense to add it. They are only available to mouse (or other pointing devices) users and the only one case where the title attribute is required for accessibility is on <iframe> and <frame> tags.
If the information conveyed by the title attribute is relevant, consider making it available somewhere else, in plain text and if it’s not relevant, consider removing the title attribute entirely.

**Comment by Peter-Liska** [comment]
> And could you please check if your issue is similar to this one #10236

#10236 is in PrestaShop administration, but this issue is in customer catalog .

**Comment by PierreRambaud** [comment]
> I don't think it is a bug, or even a needed improvement. Actually, I don't think it should be implemented at all. The image "title" attribute is not required. It's not used by screen readers or search spiders. It's just a tooltip that can add more information to a picture. If you want to display more information about the product picture, then you use the image legend field in the BO. If you don't need to display more info, you leave it empty.

I agree with @rdy4ever :+1:

**Comment by Hlavtox** [comment]
This must be fixed, every image should have an ALT tag. If the legend is not filled in backoffice, it should fallback on object name, but it's overwritten by empty legend inside ImageRetriever. I will fix it. 👍

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/33387
