### ISSUE TITLE
The prices of the product combinations do not change on the product page!

### ISSUE THREAD

**Issue by mapsfood** [PrestaShop/PrestaShop#21809]
Hi, I have a problem with my store. 

By changing the combination of products, the price is not updated, but if I add the product to the cart, the price is right in the cart! I think the settings are set correctly because it works correctly on the AMP mobile theme.

![Prod 908](https://user-images.githubusercontent.com/71649669/98529955-95d63800-227e-11eb-8a9d-e9106d885d0b.png)

![Prod 2kg](https://user-images.githubusercontent.com/71649669/98529966-9969bf00-227e-11eb-9cf7-482139d3efaf.png)

* PrestaShop version: 1.7.6.8
* PHP version: 7.1.33

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by mapsfood** [comment]
Hi, I have a problem with my store.

By changing the combination of products, the price is not updated, but if I add the product to the cart, the price is right in the cart! I think the settings are set correctly because it works correctly on the AMP mobile theme.


Steps to reproduce the behavior:

1. Go to the product page
2. Click on the product
3. Click on the combination you prefer (in this case there are 2 combinations, produced by 900gr and produced by 2kg)
*combinations prices: 900gr = 43,99€ | 2kg = 85,99€
4. error: even changing the combination the price does not change

![Prod 908](https://user-images.githubusercontent.com/71649669/98532260-c1a6ed00-2281-11eb-89ce-4aca36416ea2.png)
![Prod 2kg](https://user-images.githubusercontent.com/71649669/98532272-c5d30a80-2281-11eb-928a-a9657f5e35d2.png)

the combinations of the products are configured correctly, because the mobile website in the amp version works without problems.
![908gr](https://user-images.githubusercontent.com/71649669/98532361-e0a57f00-2281-11eb-9ec5-433c9feeba1b.png)
![2kg](https://user-images.githubusercontent.com/71649669/98532368-e307d900-2281-11eb-88ec-48b6b351aef9.png)

#### Additional information

server Linux #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64

Versione software del server: Apache

Versione di PHP: **7.1.33**

Limit  memory: **256M**

Tempo di esecuzione massimo: 900

Dimensione Max. dei file da caricare: 50M

PrestaShop: **1.7.6.8**

**Comment by SimonGrn** [comment]
Please create a new issue.
