### ISSUE TITLE
BO - Order page - Try to remve a Voucher (gift) => an error is displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21810]
#### Describe the bug

An error is displayed when removing a voucher (gift) with no code

#### Expected behavior

The Voucher line should be removed

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page
2. Create a cart rule:
2.1 Informations: No code
2.2 Conditions: No conditions
2.3 Actions: send a gift
![image](https://user-images.githubusercontent.com/16067358/97991111-45279080-1de1-11eb-8f0a-62eb83e89c34.png)
3. Go to BO > Order page > Add a new order for "John Doe"
4. Add a product to the cart (the cart rule well applied)
5. Try to remove the cart rule
6. see the error
![image](https://user-images.githubusercontent.com/16067358/98531531-c0c18b80-2280-11eb-9fed-9325ef46ba8c.png)

Same issue with 1770rc1build3

1770rc1build2 => ok

#### Additional information

* PrestaShop version: 1.7.7.0rc1build4
* PHP version: 7.2

**Comment by marionf** [comment]
This error should be fixed is ps_checkout module

**Comment by Progi1984** [comment]
**Information :**
> It comes from modules/ps_checkout/ps_checkout.php in the method hookActionCartUpdateQuantityBefore where the variable $this->context->cart->id is not checked.

**Comment by marionf** [comment]
@khouloudbelguith Can you tell me what is the version of ps_checkout in your shop ?

**Comment by marionf** [comment]
Fixed by: https://github.com/PrestaShopCorp/ps_checkout/pull/614
