### ISSUE TITLE
Multistore - BO - Order page - All languages are available in the dropdown for Language in the Add new Order page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21817]
#### Describe the bug

Multistore is enabled.
We have 2 shops, for each shop, we have 1 different currency and 1 different language
In the BO > Add new Order page > All languages are available in the dropdown for Language

#### Steps to Reproduce

1. You must have 2 languages (English, French)
2. Enable Multistore context 
3. Create a new shop shop2
4. Edit languages (English is associated with the shop1 only) / (French is associated with shop2 only)
![image](https://user-images.githubusercontent.com/16067358/98561513-45c09b00-22a9-11eb-9dd0-45b0eb8bf0ac.png)
5. Go to BO > Order page > select shop2
6. Click add new Order
7. Choose a customer
8. In the cart section => see error (All languages are available in dropdown for Language)
![image](https://user-images.githubusercontent.com/16067358/98561720-81f3fb80-22a9-11eb-9623-d5e6fc5c50a8.png)

PS: 1768 => ok
#### Additional information

* PrestaShop version: 1770rc1build4
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #22020
