### ISSUE TITLE
The prices of the product combinations do not change on the product page!

### ISSUE THREAD

**Issue by mapsfood** [PrestaShop/PrestaShop#21811]
Hi, I have a problem with my store.

By changing the combination of products, the price is not updated, but if I add the product to the cart, the price is right in the cart! I think the settings are set correctly because it works correctly on the AMP mobile theme.

Go to the product page
Click on the product
Click on the combination you prefer (in this case there are 2 combinations, produced by 900gr and produced by 2kg)
*combinations prices: 900gr = 43,99€ | 2kg = 85,99€
error: even changing the combination the price does not change

you can do a test on this link: https://www.myfitnutrition.es/inicio/23-85-namedsport-super-100-whey-proteina.html

![Prod 908](https://user-images.githubusercontent.com/71649669/98533338-20209b00-2283-11eb-9fda-c47694fcb556.png)
![Prod 2kg](https://user-images.githubusercontent.com/71649669/98533345-21ea5e80-2283-11eb-9f8f-b306c99a7d08.png)

the combinations of the products are configured correctly, because the mobile website in the amp version works without problems.

![908gr](https://user-images.githubusercontent.com/71649669/98533354-2878d600-2283-11eb-922d-5da5db003913.png)
![2kg](https://user-images.githubusercontent.com/71649669/98533361-2adb3000-2283-11eb-8b24-f6d7073554e7.png)

**Additional information**

Versione software del server: Apache

Versione di PHP: **7.1.33**

Limit memory: 256M

Tempo di esecuzione massimo: 900

Dimensione Max. dei file da caricare: 50M

PrestaShop: **1.7.6.8**

**Comment by SimonGrn** [comment]
Hello,

I'm not able to reproduce your issue. Your problem is most likely linked to your theme. You must contact the developer of your theme directly and ask him to fix this issue.

Thank you for your understanding.
