### ISSUE TITLE
BO - Order page - The voucher line is not removed when the Order's total < Minimum amount for cart rule

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21812]
#### Describe the bug

In the BO > Order page, the voucher line is not removed when the Order's total < Minimum amount for cart rule.

#### Expected behavior

The voucher line should be removed

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page
2. Create a cart rule:
2.1 Informations: With a code
2.2 Conditions: Minimum amount = 50euro, tax excluded, shipping excluded
2.3 Actions: Apply a discount amount = 1 euro tax included
![image](https://user-images.githubusercontent.com/16067358/98532786-74774b00-2282-11eb-965e-e21acca48394.png)
3. Go to BO => Orders => Add new order page for "John Doe"
4. add some product to the order
5. Add demo_6 to the cart with quantity =1 (29 euro tax excluded)
6. Add demo_21 to the cart with quantity = 1 (35 euro tax excluded)
7. Search the discount and apply it => ok
8. remove the product demo_21
9. see error => the voucher line is not removed
10. In the summary block, the voucher is applied => NOK

![image](https://user-images.githubusercontent.com/16067358/98533881-e13f1500-2283-11eb-8203-eca43f3d0379.png)

PS1768 => ok

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #22077
