### ISSUE TITLE
Generate invoice indicates : 500 Internal Server Error

### ISSUE THREAD

**Issue by Kahiogoo** [PrestaShop/PrestaShop#21813]
Hello,
When I click on the icon to open an invoice linked to an order, a new window opens and indicates the following error message: Internal Server Error.
Cannot also display invoices in the invoices menu.

I tried to downgrade PHP version 7.3 to 7.2, nothing change.

PrestaShop version: 1.7.6.8
PHP version: 7.2

Thank you for your help !

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
