### ISSUE TITLE
BO - Order page - Debug mode enabled - an exception is displayed when ordering a product with a file customization - the label contains a space

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21815]
#### Describe the bug

We create a product with a customization

- Type: **file**
- Label: Must contain a **space** for example (Please attach a file)
- Required (yes/No) => Same issue

When we order this product, we have an error is the BO > Order page

If the debug Mode enabled => exception
![image](https://user-images.githubusercontent.com/16067358/98551731-ec06a380-229d-11eb-9ed7-90128d712047.png)
If the debug Mode disabled => the order can be viewed but, if you download the attached file => NOK (detected by @Robin-Fischer-PS )
![image](https://user-images.githubusercontent.com/16067358/98551991-40aa1e80-229e-11eb-9a21-1df03b65ba4c.png)

#### Steps to Reproduce

1. Create a product with customization
1.1 Type: **file**
1.2 Label: Must contain a **space** for example (Please attach a file)
1.3 Required (yes/No) => Same issue
![image](https://user-images.githubusercontent.com/16067358/98552189-751dda80-229e-11eb-93e4-bc806584785c.png)
2. Go to FO  > Product details page
3. Choose a file and save a customization
4. add to cart
5. Continue checkout
6. Go to BO > Order page > View the last order created 
7. see error

#### Additional information

* PrestaShop version: 1770rc1build4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/product-team what do you think, it is `must-to-have` or `nice-to-have`?

**Comment by matks** [comment]
PR to fix this bug https://github.com/PrestaShop/PrestaShop/pull/21816/

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21816
