### ISSUE TITLE
Shipping VAT are false in credit SLIP

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#21826]
When I do a credit slip, shipping are false.

Exemple for an order : 
shipping without tax = 2.5€
VAT 20% = 0.5€
Total with tax = 3€

If I do a credit slip
shipping without tax = 3€ (amount with VAT is took)
VAT 20% = 0.6€
Total with tax = 3.6€

(easy to change in database... but it's a bug)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment]
Hi @pppplus I know it's unrelated to the bug but I just wanted to tell you PS 1.7.6.7 is not compatible with php7.3 😉  so you better downgrade your php version else you might encounter some buggy usecases

**Comment by pppplus** [comment]
Yes, sorry, it's 7.2 !!
I've edited my post

**Comment by hibatallahAouadni** [comment]
Hello @pppplus 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report.**

So, could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report]
(http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @pppplus 

I didn't manage to reproduce your issue with PS1.7.6.7 and PS1.7.6.8, see the attached screenshot of the credit slip below:

![image](https://user-images.githubusercontent.com/23308427/98672426-161b9c80-2356-11eb-8d75-87cadc4a608e.png)

Could you please provide more infos.

Thanks!

**Comment by pppplus** [comment]
Hi,

Sorry, the bugs does not come from credit slip !
The bug is in orders created by Web Services ! Prices are very badly reported.

I've applied corrections, but forgot some features... 
Not visible, except when I do a credit slip.

Thanks for your time.
