### ISSUE TITLE
Upgrade 1.7.6.4 to 1.7.6.8 cant login backoffice, or client login 

### ISSUE THREAD

**Issue by jpcoke** [PrestaShop/PrestaShop#21823]
I´ve upgraded from 1.7.6.4 to 1.7.6.8 on two websites in the same server... (1-click upgrade 4.10.1 version module - 

one went fine.... the other, i cant login in backoffice.... 

when i try to access only get this: 
![image](https://user-images.githubusercontent.com/74207519/98707442-f4331180-2377-11eb-8b78-bdef1305f055.png)

Front office apparently works well... until i try to login as a costumer...

When i do, i get a 500 blank page...

Activated "PS_MODE_DEV_', true", and when i do the costumer login i get this:
![Inked98584079-4c590d80-22bd-11eb-8a41-30eb5404e4ff_LI](https://user-images.githubusercontent.com/74207519/98707227-b504c080-2377-11eb-9b41-ad434bef98e9.jpg)

I've tried multiple solutions after searching online, such as the one of creating ps_employee_session and ps_customer_session, they we´re there...
 emptied the chache folder
accessed through incognito... 
nothing worked...

The website only haved the prestashop modules activated, the upgrade on 1-click  didn´t show any errors.. there are no errors related to this on cpanel error log...

Here are the settings used ( used on both sites and removed from the other site i upgrade with no issues - i use the same settings on both)

![image](https://user-images.githubusercontent.com/74207519/98586333-79f38600-22c0-11eb-8b99-32afa13ceed0.png)

Please help...

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hi @jpcoke 

Please next time follow the Github template. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/)

Could you please provide the log file: /admin-dev/autoupgrade/tmp/

Thanks!

**Comment by matks** [comment]
@jpcoke I notice you have a limited memory size of 128M

We recommend allocating 256M for PrestaShop (see https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/)

**Comment by matks** [comment]
@jpcoke Your error message says "Failed opening required ...SessionInterface"

Class SessionInterface is a new php class introduced in PS 1.7.6.6 to fix a security issue. Can you check it is on your shop ? In folder src/Core/Session

see https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/src/Core/Session/SessionInterface.php

**Comment by jpcoke** [comment]
Hi

Thank you so much for the attention and help

It was indeed the "session" folder and the php file missing... It should be created by the upgrade... i guess...

Also increased the memory limit, but it wasn't whats causing the issue, because i increased it after solving the issue.

Thank you so much once again.

Hope it helps it others with same issue.
