### ISSUE TITLE
BO - Order page - Private note containing problematic characters

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21829]
#### Describe the bug

In the BO > Orders > Order page > the private not working correctly with problematic characters: "toto & tata"
![image](https://user-images.githubusercontent.com/16067358/98653755-b44f3880-233d-11eb-9be9-b93289ff7b0f.png)

#### Expected behavior

It should be well displayed

#### Steps to Reproduce

1. Go to BO > Orders page
2. Open an order
3. In the Private note set this expression "toto & tata"
4. Save

![image](https://user-images.githubusercontent.com/16067358/98654225-540cc680-233e-11eb-96ce-9e7389caf770.png)

PS: 1768 => ok
![image](https://user-images.githubusercontent.com/16067358/98654261-6129b580-233e-11eb-963f-2484bb0c0459.png)

#### Additional information

* PrestaShop version: 1.7.7.0rc1build4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/9726

**Comment by Progi1984** [comment]
Fixed by #21992
