### ISSUE TITLE
Configuration button no longer appears after installation

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21825]
#### Describe the bug

configuration button no longer appears after installation in catalog module.

#### Expected behavior

Button should be appear.

#### Steps to Reproduce

1. Go to BO -> Modules -> Catalog module
2. Click on "Install"
3. See error

**Screenshots**
<img width="1075" alt="Capture d’écran 2020-11-10 à 09 25 22" src="https://user-images.githubusercontent.com/3034677/98648529-b235ab80-2336-11eb-88a8-e1084c8a8369.png">

https://drive.google.com/file/d/1yCwvE2ja8srE3BhP6Z-wT9meFsVCJJOL/view

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24286
