### ISSUE TITLE
[UI-KIT] -  Rounding is missing on some buttons

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21831]
#### Describe the bug

Rounding is missing on some buttons

- Order Page
<img width="1280" alt="02 - Round" src="https://user-images.githubusercontent.com/3034677/98653339-34c16980-233d-11eb-8277-928b61561651.png">

- Order Detail Page
<img width="1280" alt="01 - Round" src="https://user-images.githubusercontent.com/3034677/98653179-004dad80-233d-11eb-9d75-d076bd66c74a.png">
<img width="699" alt="03_round" src="https://user-images.githubusercontent.com/3034677/98655197-7d7a2200-233f-11eb-9056-fa7ddb3e375e.png">

- Stock management 
<img width="1280" alt="Capture d’écran 2020-11-06 à 17 17 04" src="https://user-images.githubusercontent.com/3034677/98655523-de095f00-233f-11eb-9f26-17d6879aecf9.png">
<img width="1280" alt="Capture d’écran 2020-11-06 à 17 14 02" src="https://user-images.githubusercontent.com/3034677/98655595-eeb9d500-233f-11eb-9a89-1ec101eb0ee6.png">
<img width="1280" alt="Capture d’écran 2020-11-06 à 17 17 44" src="https://user-images.githubusercontent.com/3034677/98655933-596b1080-2340-11eb-87cd-f230744194af.png">

- Theme & Logo 
<img width="1280" alt="Capture d’écran 2020-11-10 à 12 19 14" src="https://user-images.githubusercontent.com/3034677/98667672-0482c680-234f-11eb-997e-321eedf6fb2f.png">
<img width="1280" alt="Capture d’écran 2020-11-10 à 12 19 59" src="https://user-images.githubusercontent.com/3034677/98667708-14020f80-234f-11eb-89d9-fe0a6f183944.png">

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

**Comment by NeOMakinG** [comment]
Theme & logo pages are legacy, doesn't concern this :)
