### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MartaLin** [PrestaShop/PrestaShop#21837]
#### Describe the bug

My Back Office gives me problems. When I try to access modules it returns this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

#### Expected behavior

I want to access modules.

#### Steps to Reproduce

1. Go to 'modules'
2. Click on 'Modules and Services'
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/74241752/98663403-59234300-2349-11eb-84f3-f740a19d716e.png)

#### Additional information

* PrestaShop version: 1.7.5.0

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
