### ISSUE TITLE
Error during big cart checkout

### ISSUE THREAD

**Issue by szykuc** [PrestaShop/PrestaShop#21833]
When i add many product to cart (over 100-120) and i try go to checkout all product are deleted from cart and i am signed off from my client account.

When i reach about 104 different unique products i could not add any more (jquery 500 error in console)

I find my orders->carts in admin and when i try use "Create an order from this cart." there is jquery 500 error.

#### Steps to Reproduce

1. Add as many unique product to cart as you can - i could add max 104
2. Go to checkout

**Screenshots**

![500](https://user-images.githubusercontent.com/39799737/98655901-4eb07b80-2340-11eb-99ff-4ce881dbc3b4.jpg)

* PrestaShop version: 1.7.6.8
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @szykuc 

I didn't manage to reproduce your issue with PS1.7.6.8 (see screen record below)

https://drive.google.com/file/d/18Q9CB5UoGlUtmhNUWiC0mhDJfwiMmh_s/view

Please check and feedback.

PS: You may forgot some details, please provide as many reliable informations as you can.

Thanks!

**Comment by szykuc** [comment]
@hibatallahAouadni can you test how many different product you can add to cart? Is tere any kind of limit?

Whats your php enviroment settins? memory_limit, timeout etc?

**Comment by hibatallahAouadni** [comment]
Hello @szykuc 

> Is tere any kind of limit?

There is no limit for the quantity / number of products added to the cart, you can add as many as you want.

> Whats your php enviroment settins? memory_limit, timeout etc?

I attached a screenshot of my shop Advanced Parameters below:

![image](https://user-images.githubusercontent.com/23308427/98668496-4102f200-2350-11eb-81ab-0a6d8528c27b.png)

And my PHP version is 7.2.

Please check and feedback.

PS: Ping @PrestaShop/product-team please correct me if I'm wrong ;-)

**Comment by hibatallahAouadni** [comment]
@szykuc Could you please check if your issue is similar to this one #14979
Please check and feedback.

Thanks!

**Comment by szykuc** [comment]
@hibatallahAouadni no it isn't  similar.

I checked my shop on different hosting and it works ok. 

Neither me nor the administrators found the cause of the problem in the first hosting.
