### ISSUE TITLE
Create Order - Minimal quantity is not respected

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#21838]
#### Describe the bug

In create order, you can add any quantity of a product with minimal quantity required

#### Expected behavior

If the product has minimal quantity, you cannot order less than the quantity required

#### Steps to Reproduce

https://drive.google.com/file/d/1vHKrs1IX8O2IA_gnUfr2gr4iYifqBal-/view

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2.34

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

I think that it is normal behavior as reported [here](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/orders/orders/Order%20Page%20View.md): 
_`If the product has a Minimum quantity for sale higher than 1, defined in the Product quantity tab. In this situation, when trying to add a product with less than the minimum quantity, an error will be displayed with the required minimum quantity. Then, by editing this quantity, the merchant can enter any quantity, the verification is done only when adding.`_

Ping @MatShir what do you think?

Thanks!

**Comment by MatShir** [comment]
@khouloudbelguith exactly! 
@sowbiba, continue to look for flaws, like if @khouloudbelguith was not enough :smile:
