### ISSUE TITLE
BO - Customer Groups - Enable/Disable selection do not work

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21847]
#### Describe the bug

In the BO > Shop Parameters > Customer Settings > Groups Tab > View Customer Group.
If you try to `Enable/Disable` selection with bulk action or just for a line, nothing happens.

#### Steps to Reproduce

0. Create a new customer 
1. Go to BO > Shop Parameters > Customer Settings > Groups Tab > View Customer Group.
2. Try to  `Enable/Disable` selection or just a line

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/98684470-80d4d400-2366-11eb-9093-681a7110abd9.png)

#### Additional information

* PrestaShop version: 1770rc1build4, 1768
* PHP version: 7.2

**Comment by LouiseBonnard** [comment]
Hey, what's the status of this issue, why is it already in _to do_?
