### ISSUE TITLE
Lines in User review for product are not separated with CR/LF (2)

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21848]
#### Describe the bug
I've installed the newest version of the module "Product Comments" from github and still there is not fixed the bug with CR/LF as it is described in the issue #20343. The issue #20343 is closed as fixed.
Could you check it once again? 

User review - Display
![image](https://user-images.githubusercontent.com/33311857/98686463-e7f38800-2368-11eb-8f55-32997d7c1e77.png)

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by SimonGrn** [comment]
The issue has been fixed but there hasn't been any new release so that's normal. We will release a new version when we have the time and we have enough fixes for it to be worthwile.
Thank you for your understanding.
