### ISSUE TITLE
Onglet Personnaliser

### ISSUE THREAD

**Issue by HYankees49** [PrestaShop/PrestaShop#21844]
#### Describe the bug

L'onglet "Personnaliser" ainsi que tout ce qui appartient à cet onglet mènent à une erreur, je ne peux donc pas accéder aux modes de paiements et aux autres pages.

#### Expected behavior

Je m'attends à ce que les pages s'affiche correctement et ne produisent pas d'erreurs

#### Steps to Reproduce

1. Go to 'Personnaliser'
2. Click on 'Modes de paiements' ou les autres 

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @HYankees49 ,

Please send your request in English. English is the norm on GitHub.
 Feel free to create a new issue, we will be glad to investigate it.

Thanks!

**Comment by HYankees49** [comment]
**Describe the bug**

The "Customize" tab as well as everything that belongs to this tab lead to an error, so I cannot access the payment methods and other pages.


**Expected behavior**

I expect the pages to display correctly and do not produce errors.

**Steps to Reproduce**

Steps to reproduce the behavior:

1. Go to 'Personalize'
2. Click on 'Payment methods' or others
3. See error

**Comment by SimonGrn** [comment]
Please create a new issue and give us more details, as is it should work because we cannot reproduce your issue. And please fill the template correctly (we don't know your PS and PHP versions !).

Thank you.
