### ISSUE TITLE
[UI-KIT] - On-Off switch does not display

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21842]
#### Describe the bug

On-Off switch does not display

- Currencies : 
https://drive.google.com/file/d/1k_8vpXKEvTcesttVTfkUVwTBK6WxoGsd/view

- Team : 
https://drive.google.com/file/d/1dfVcfbrGdrLCbPa6pFa1GBmduLugpdK5/view

- SEO & URL
https://drive.google.com/file/d/1Q-ih5Ax3nZu0Vbwu0y2lyMt_naoW01x6/view?usp=sharing

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

**Comment by NeOMakinG** [comment]
Fixed on the UIKit side, btw, it's pretty strange that some inputs doesn't have default values, that would be fixed by this on the core side

@PrestaShop/prestashop-maintainers could someone check if it's not possible to put default values on every form fields in the BO ?
