### ISSUE TITLE
[UI-KIT] - Align icon with text in email theme 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21843]
#### Describe the bug

Align icon with text in email theme 

#### Steps to Reproduce

1. Go to BO -> email theme
2. See error

**Screenshots**
<img width="1280" alt="Capture d’écran 2020-11-06 à 17 46 45" src="https://user-images.githubusercontent.com/3034677/98669311-87a51c00-2351-11eb-9e6b-aa58e5b6a8bf.png">

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

**Comment by NeOMakinG** [comment]
Wdyt @PrestaShop/ux-team ? It's clearly because the help box doesn't have enough space to be at right, so we need to think about his placement

**Comment by prestascott** [comment]
Is there any possibility to place this icon next to the text? @NeOMakinG

**Comment by NeOMakinG** [comment]
Should we collapse it on the top ? or should we align the text and icons horionzontally ? I think this is possible !

**Comment by prestascott** [comment]
Imo we should align the icon horizontally with the first text line :)
