### ISSUE TITLE
Error 500 when accessing the "Payment" tab

### ISSUE THREAD

**Issue by HYankees49** [PrestaShop/PrestaShop#21851]
#### Describe the bug

On my website Yankees the "Customize" tab as well as everything that belongs to this tab lead to a server error, so I cannot access the payment methods and other pages.

#### Expected behavior

I expect the pages to display correctly and do not produce errors. And be able to change payment methods on my website Yankees.

#### Steps to Reproduce

1. Go to 'Custom'
2. Click on 'Payment'
3. Scroll down to 'Payment methods'
4. See error : HTTP Error 500

#### Additional information

* PrestaShop version: 1.7.1.2
* PHP version: 5.5.38

**Comment by SimonGrn** [comment]
Hello @HYankees49 

Could you please provide a screenshot ?
Which payment modules are installed ?

**Comment by HYankees49** [comment]
![Capture](https://user-images.githubusercontent.com/74248263/98916849-f1e1cc00-24cb-11eb-8046-5df5e32e4cc2.PNG)

This page does not work
Unable to process this request via yankees-football.fr at the moment.

HTTP ERROR 500

Refresh

Payment Modules : Paypal, bank transfer, cheque

**Comment by hibatallahAouadni** [comment]
Hello @HYankees49 

Please activate the debug mode, if the displayed problem is Paypal problem, please contact the Paypal module developer.
If no, could you please upgrade your PHP version to 7.2 and your shop to 1.7.6.8.
Check and feedback.

Thanks!

**Comment by HYankees49** [comment]
![Capture 1](https://user-images.githubusercontent.com/74248263/98921392-8995e900-24d1-11eb-9b4b-29bf5a7a3dba.PNG)
![Capture 2](https://user-images.githubusercontent.com/74248263/98921393-8ac71600-24d1-11eb-9997-92ebc9e3d7a0.PNG)
![Capture 3](https://user-images.githubusercontent.com/74248263/98921396-8ac71600-24d1-11eb-9935-3adb8dc0eb38.PNG)
![Capture 4](https://user-images.githubusercontent.com/74248263/98921398-8b5fac80-24d1-11eb-82f1-974fb07c194e.PNG)
![Capture 5](https://user-images.githubusercontent.com/74248263/98921400-8b5fac80-24d1-11eb-9df4-80e615a4aa70.PNG)
![Capture 6](https://user-images.githubusercontent.com/74248263/98921401-8b5fac80-24d1-11eb-83c7-a5c00823eb36.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @HYankees49 ,

You need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
I close this issue.

PS: you may need to clear your cache.

Thank you.
