### ISSUE TITLE
Open access to Prestashop Validator sources

### ISSUE THREAD

**Issue by presteus** [PrestaShop/PrestaShop#21868]
#### Is your feature request related to a problem?

Developing a PrestaShop module is a pain and the validator is far too naive!
if you really want to develop a module, forget any version of php > 5.6.

Example: not allowing the use of the base64_encode function is really incomprehensible (workaround need to pass by url oO)

#### Describe the solution you'd like

Open access to Prestashop Validator sources

#### Alternatives you've considered

No alternative

#### Additional context

Example of problem:
 - PHP Trait is not supported
 - "There must be exactly one blank line after the file comment" do not respect PHP CS Fixer fixes (after License)

**Comment by hibatallahAouadni** [comment]
Hi @presteus 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.  If you have questions or suggestion about using PrestaShop or third-party modules, please consider one of our [community forums](https://www.prestashop.com/forums/) or our [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by SimonGrn** [comment]
Hello,

the Validator is part of the PrestaShop company (not PrestaShop the software), which operates the Addons Marketplace. This is not linked in any way with this repository.
You can contact the team responsible for Addons [here](https://addons.prestashop.com/fr/contactez-nous).

Thank you.
