### ISSUE TITLE
Key in tr exists, but null

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#21864]
#### Describe the bug

Key in tr exists, but null

#### Steps to Reproduce

1. Create admin controller controller
2. Create in fields_list column and add in select

$this->_select .= ' NULL as `callback`'

$this->fields_list = array(
    'callback' => array(
         'title' => $this->l('Api configuration'),
         'callback' => 'getListItems'
    )
);

3. Add function in controller

public function getListItems()
{
}

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could you please check this issue.
Thanks!

**Comment by PierreRambaud** [comment]
Could you please provide us an example (zip containing what you did)?

**Comment by hibatallahAouadni** [comment]
Hello @dariusakafest 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
