### ISSUE TITLE
The order comment is badly coded for Central European languages

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#21862]
**Describe the bug**
The order comment is badly coded for Central European languages.

Text used: **Ak by ste chceli pridať poznámku k Vašej objednávke, prosím, poznačte ju nižšie.**
Saved text: `Ak by ste chceli pridať pozn&aacute;mku k Va&scaron;ej objedn&aacute;vke, pros&iacute;m, poznačte ju niž&scaron;ie.`

I replicated the problem at demo.prestashop.com

**Screenshots**
https://share.vidyard.com/watch/mxgyvvk2f35RZLVTHyfqLo?

#### Additional information
* PrestaShop version: 1.7.6.8.

**Comment by hibatallahAouadni** [comment]
Hello @elrosi ,

This issue has been fixed with our next release PS1.7.7.0, please check the attached screen record below:

https://drive.google.com/file/d/1HRjn6sZ5puf6hlL9ZA3H6of8S1LunPji/view

We will close this issue.

Thank you.
