### ISSUE TITLE
"PaymentModule::validateOrder - Secure key does not match" how to resolve this problem, the mailchimp module developer didn't reply us

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#21871]
Dear staff,
we have a PS 1.7.6.8, we migrated from PS 1.6 to PS 1.7 (clean install) in July.
The problem we encounter is the following, partly similar to this #12669, but we have more information:
We use this module to connect PrestaShop to mailchimp:
https://addons.prestashop.com/it/newsletter-sms/26957-mailchimp.html
Mailchimp is using old carts that it sends to customers. 
When the customer clicks on the abandoned cart, they proceed with the purchase, if he chooses a payment such as Paypal, or any other method that requires you to leave the site, he returns to the site but the order key generated by the payment module does not match with the key generated by the abandoned cart, this misalignment prevents, perhaps for security reasons, Prestashop to generate the order.
Therefore: we have the payment, but we do not have the order.
The customer is confused and frustrated and does not understand why he didn't find the paid order in his account.
Is it a mailchimp problem?
Maybe, but the developer didn't respond to our requests, we tried many times.
Is it a PrestaShop problem?
Also, because PrestaShop should check if the carts are correct or not, it should also check if the mailchimp module has compatibility problems.
Is it possible that in the Prestahop addons no one has asked the developer to verify this problem?
We asked it to the chat of prestashop addons, they tell us that the developer is not required to provide assistance because the module is free.
Also Mailchimp support write that this module is not created by them so they cannot give assistance on problems concerning external products.
Why then is this module still present into the addons if it does not provide assistance?
With whom should we discuss this problem?
Thanks for the support.
Balla

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

It seems that your issue is not a PrestaShop core bug.
If your module is MailShimp Official, please contact support team on [Addons](https://addons.prestashop.com/)

PS: re-send again your issue to the mailchimp module developer.

We will close this issue.

Thanks!

**Comment by ballashop** [comment]
Hi @hibatallahAouadni thanks to replied us.
I think the cart problem is PrestaShop problem, not mailchimp one.
Until the developer responds we will not know, we have been looking for him for months, the latest response is in July. in the meantime a president of the U.S.A. has changed and many other things.
This is not serious from PrestaShop addons.
Thanks a lot.
Balla

**Comment by SimonGrn** [comment]
Hello,

this is the repository for the PrestaShop software, this is not linked in any way with Addons. You can't get any support related to any external or third-party module here.

Please follow the link in @hibatallahAouadni 's comment.
