### ISSUE TITLE
"Related Product" section of product page is not showing images and references

### ISSUE THREAD

**Issue by LucaMozzo** [PrestaShop/PrestaShop#21872]
I coulnd't find this issue anywhere on Github, I'm running Prestashop 1.7.6.0

In the backoffice I add a related product, it looks fine (with image, title and reference), however once I save, close the product page and reopen it, I get the related products displayed this way
<img width="680" alt="immagine" src="https://user-images.githubusercontent.com/8259971/98833206-0b3c3700-243e-11eb-8e2e-61316a87c56e.png">

sometimes it also says "copy of ..."
![immagine](https://user-images.githubusercontent.com/8259971/98833839-cfee3800-243e-11eb-90a4-1978bb645f86.png)

the view that I see (just reference, no reference, or photo & title with "copy of") is completely random, but it never displays correctly

On the front office it looks fine (all 4 products are displayed correctly), however I can't really see what is going on from the backoffice. What could cause this?

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
