### ISSUE TITLE
[FO] Pack of products - Incorrect image displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#21875]
#### Describe the bug

In the FO, when we open the Product Pack page, we see the selecteds products, for exemple, the color of the product is "white", instead of displaying the product's image, the cover image of the original product is displayed (color is black). 

![image](https://user-images.githubusercontent.com/23308427/98832519-36725680-243d-11eb-8b0f-f5c2e3166b9f.png)

#### Expected behavior

Displaying the product's image

#### Steps to Reproduce

1. Go to BO > Catalog > Products
2. Create a Pack
3. Search Product with combinations
4. Select one combination (ex: t-shirt with white color)
5. Add it to the Pack
6. Go to FO > Pack page
7. See error

**Screenshots & ScreenRecord**

https://drive.google.com/file/d/1DX6qX21-QPUDH8gFa4na76RdT2i0xgQo/view

#### Additional information

* PrestaShop version: 1.7.7.0-rc.1+build.4
* PHP version: 7.2

**Comment by jolelievre** [comment]
Solution might have influence or fix this issue https://github.com/PrestaShop/PrestaShop/issues/21775

**Comment by hibatallahAouadni** [comment]
related to #21775

**Comment by Progi1984** [comment]
Fixed by #22103
