### ISSUE TITLE
BO - Order page - The minimum quantity of a combination is not correct

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21873]
#### Describe the bug

In the BO > Orders > Add new order page > the minimum quantity of a combination is not correct.

#### Expected behavior
![image](https://user-images.githubusercontent.com/16067358/98836552-1a24e880-2442-11eb-911d-f25b2580a3b2.png)

#### Steps to Reproduce

1. Go to BO > Products page > Create a new product with combinations
3. For each combination set the Min. quantity for sale > 1
![image](https://user-images.githubusercontent.com/16067358/98835990-6cb1d500-2441-11eb-8503-a09512652c5e.png)
3. Go to BO > Order page > Add new Order
4. choose a customer
5. search the last product created
6. Try to add it to the cart
7. an alert is displayed, but the minimum quantity is NOK.

![image](https://user-images.githubusercontent.com/16067358/98836705-4a6c8700-2442-11eb-9891-2f8d88af589c.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21980
