### ISSUE TITLE
No puedo traducir al español arg. versión 1.7.6.8

### ISSUE THREAD

**Issue by glpccreaciones** [PrestaShop/PrestaShop#21881]
Hola, no puedo traducir al español ni hacer modificaciones porque la lista desplegable queda inhabilitada 

![image](https://user-images.githubusercontent.com/74337334/98890434-b834a500-247a-11eb-89e4-b0996c143d6f.png)

**Comment by matks** [comment]
Hello @glpccreaciones usually when I see this type of weird display it's because you use php7.3 or php7.2 . PS 1.7.6.8 needs php7.2 maximum.

**Comment by hibatallahAouadni** [comment]
Hello @glpccreaciones ,

Please send your request in English. English is the norm on GitHub.
Like @matks said, please check your PHP version (see [System requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/))

Thank you

**Comment by glpccreaciones** [comment]
sorry, thanks I'll change the php

**Comment by glpccreaciones** [comment]
perfect, if that was the solution
