### ISSUE TITLE
Problem with admin login - default Admin Login URL is http but our server needs https

### ISSUE THREAD

**Issue by rcbiz5000** [PrestaShop/PrestaShop#21882]
After a fresh install of Prestashop, many people have been complaining about being unable to login to the ADMIN page. 
The reason is that the URL that the site tries to automatically open doesn't have (HTTPS) in it... it's still setup for (HTTP) which will make the login crash. Please fix this! We have to go into the URL bar and MANUALLY add (httpS) to the address. - Not good! 

Yeah, we can just make a bookmark with the HTTPS in there, but it's better & more professional if it works right out of the box. 
Thanks

**Comment by matks** [comment]
@rcbiz5000 if your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/10482 you might want to try the solution provided by @alx741 to enable SSL mode in your shop

```sql
update ps_configuration set value=1 where name like '%PS_SSL_ENABLED%';
```

The right fix is already done for PS 1.7.8.0 https://github.com/PrestaShop/PrestaShop/pull/19791

**Comment by hibatallahAouadni** [comment]
Hello @rcbiz5000 

Please next time **follow the template to submit a complete bug report**.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Please check and feedback if your issue is similar to #10482 like @matks mention.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @rcbiz5000 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
