### ISSUE TITLE
Registration of a new client 

### ISSUE THREAD

**Issue by nathanboschi25** [PrestaShop/PrestaShop#21885]
I'm always frustrated when i create a client manually i have to enter a password. It's not for me to do that!
It would be a small implementation to send a password to the client, with request for modification or a request for registration.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
