### ISSUE TITLE
BO - Import File / The "delete all XXX before import" toggle button has no effect data are always deleted even if button is set to no

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#21895]
## Describe the bug

In the import file page, if you try to import customers or addresses and if the button " delete all customers/addresses before import" is set to NO the defaults customers/addresses are still deleted

#### Expected behavior

The already existing datas should not be deleted if the button is set to NO

#### Steps to Reproduce

1. Go to Advandced parameters/ import file
2. set the parameters to import customers or addresses
3. set the "delete all" toggle button to no
4. finish the file import
5. go to the customers list page and see error => the default customers are deleted 

#### Additional information

* PrestaShop version: 1.7.6.x // 1.7.7.x // develop
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I think it is similar to this https://github.com/PrestaShop/PrestaShop/issues/21565.

Is it?

**Comment by SimonGrn** [comment]
In #21565 it's for the similar IDs. @SD1982 could you try to change IDs in your database OR in the CSV file to verify it really deletes everything in the database and not just overwrite the existing entries ?

**Comment by SD1982** [comment]
Hi @khouloudbelguith & @SimonGrn after more investigation yes it's totally related to #21565 
I close this one ! 
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #21565
