### ISSUE TITLE
Color Picker With Lang PS 1.7.6.1

### ISSUE THREAD

**Issue by Noido** [PrestaShop/PrestaShop#21890]
Hello, i got a problem with PS1.7.6.1 if i choose lang true   on render form input name is bg_color  and not bg_color_1 2 3 etc for each language

`array(       
					   'type' => 'color', 
					   'label' => 'BG COLOR', 
					   'name' => 'bg_color', 
					   'lang' => true,
					), `

on render html i got 

`<input type="text" data-hex="true" class="color mColorPickerInput mColorPicker" name="bg_color" value="" id="color_0" style="color: black;">`

Problem when i want save in database not work like bg_color dont have lang extension 

Thanks for your help

**Comment by hibatallahAouadni** [comment]
Hello,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- host
- server setup and configuration
- debug mode report
- PHP version
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

And please next time *follow the template to submit a complete bug report*.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Thanks!

**Comment by Noido** [comment]
Hi @hibatallahAouadni  
So
php 7.0 , just create admin form with lang true    and add this in fieldsform of renderForm  

`array( 'type' => 'color', 'label' => 'BG COLOR', 'name' => 'bg_color', 'lang' => true, ),`

And you will get error

Debug mode say that when i go on form : 

Warning at line 39 /*****/vendor/smarty/smarty/libs/plugins/modifier.escape.php
[2] htmlspecialchars() expects parameter 1 to be string, array given


if i remove that : 

`array( 'type' => 'color', 'label' => 'BG COLOR', 'name' => 'bg_color', 'lang' => true, ),`

Debug mode don t give error

**Comment by hibatallahAouadni** [comment]
Hello @Noido 

It seems to me you're facing this problem cause you didn't override/code correctly.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the
[public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you.
