### ISSUE TITLE
Add subject to email / no object for ... found inside db

### ISSUE THREAD

**Issue by laurentmacca** [PrestaShop/PrestaShop#21901]
#### Describe the bug

When I create a new transactionnal email no input for subject is available inside Translation email/theme/lang.
Thank you.

#### Expected behavior

Change/modify email subject

#### Steps to Reproduce

1. Go to 'Translation'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/72545009/99048032-5321a200-2595-11eb-93f7-0ecf945350bb.png)

#### Additional information

* PrestaShop version: 1.6.1.3
* PHP version: 7

**Comment by florine2623** [comment]
Hello,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
