### ISSUE TITLE
[Multi-invoices] BO - Order page - When canceling Products - the total invoice is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21903]
#### Describe the bug

When we cancel an order with multi-invoices, only one invoice is ok

#### Steps to Reproduce

1. Create order from the FO with only one product
2. Go to BO > Customer Service > Marchandise return > Enable returns
3. Go to BO > Order page > Last order created
4. In the Documents tab > generate an invoice
5. Add a product to the order with creating a new invoice
6. Click on the cancel products button
7. Select the second product
8. Click on cancel products
9. Click on the cancel products button again
10. Select the first product (the only product)
11. Click on cancel products
12. Click on the Documents Tab
13. see error => the total of the first invoice => NOK
![image](https://user-images.githubusercontent.com/16067358/99066002-90435f80-25a8-11eb-8a6a-cc4c723f7123.png)
14. Download the first invoice => Incorrect information
![image](https://user-images.githubusercontent.com/16067358/99066015-976a6d80-25a8-11eb-84b5-fa3ad571a51f.png)

#### Additional information

* PrestaShop version: 1.7.6.8, 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi!

As discussed with @marionf, this is not a regression.
I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/99243060-61272b00-2800-11eb-86a5-2ca0c1a89533.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #21994
