### ISSUE TITLE
PrestaShop Validator do not respect PHP CS Fixer fixes

### ISSUE THREAD

**Issue by presteus** [PrestaShop/PrestaShop#21900]
#### Describe the bug

The tools PHP CS Fixer complains about **no_blank_lines_after_phpdoc** when you fix it, PrestaShop validator complains to remove the blank line after License.

#### Expected behavior

Validator must respect PHP CS Fixer.

#### Steps to Reproduce

1. Create a file without space after License.
2. Run PHP CS Fixer tool to fix the problems
3. Submit zip file to Validator
4. See error about new line after License

**Screenshots**

Non screenshot available

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* PrestaShop Dev Tools: 3.10

**Comment by SimonGrn** [comment]
The Validator is not part of the Open Source Project, it is a closed source software ran by the PrestaShop company.
It is in no way linked to this repository.

You can contact the Addons team [here](https://addons.prestashop.com/en/contact-us).

Thank you for your understanding.

**Comment by SimonGrn** [comment]
The Validator is not part of the Open Source Project. It is in no way linked to this repository.

You can contact the Addons team [here](https://addons.prestashop.com/en/contact-us).
you can also contact the Validator team directly through [this email](mailto:validator@prestashop.com).

Thank you for your understanding.
