### ISSUE TITLE
Probleme ID produits sur module best sellers

### ISSUE THREAD

**Issue by remidu66** [PrestaShop/PrestaShop#21914]
Bonjour , je rencontre un problème que je pense minime mais étant novice je n'arrive pas a le résoudre !!

Sur ma page d'accueil de Prestashop j'ai un module TT-Best sellers ( meilleures ventes ) mais j'ai un produit qui s'affiche en défaut alors que je n'ai plus ce produit.( Voir fichier joint ) . Quant je clique sur le produit cela m'envoie sur une page produit ou il est à 0,00€ , sans image et sans reference comment puis je le supprimer sachant qu'il n'apparait pas dans mes produits actuels ? De plus la page sur laquelle je suis renvoyée m'indique l'ID du produit en premier ( 109 voir la photo ) et celui ci ne correspond à rien dans mon catalogue produit. Ou existe t'il un moyen de mettre à jour les ID produits qui ne sont plus dans le catalogue ? 
J'ai bien activé dans les paramètres la mise à jour des URL simplifiées.
Merci d'avance
<img width="1213" alt="probleme produits" src="https://user-images.githubusercontent.com/74424422/99103877-89d0da00-25e0-11eb-843d-87b5436a1d8f.png">
<img width="1770" alt="url" src="https://user-images.githubusercontent.com/74424422/99104294-24311d80-25e1-11eb-9cb1-bcdb5219b568.png">

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
**Your issue MUST BE written in English**.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
