### ISSUE TITLE
Issue coupon discount with tax excluded

### ISSUE THREAD

**Issue by barbosatrix** [PrestaShop/PrestaShop#21911]
Describe the bug

I created a $25000 pesos coupon for every user on the platform. When the user goes to pay, prestashop add some value to the coupon just if I set tax-excluded option on the Back office discount page.
I have free delivery when the order is up to $100000. If I let the coupon with tax included and the order is up to $100000, it not finish the chekout. If I let the coupon with tax excluded, prestashop finish the chekout but increase the coupon value in some way relate to producto tax

Expected behavior
Not to add some value to the coupon when I choose tax excluded on the coupon.

Steps to Reproduce
Steps to reproduce the behavior 1:

Create a $25000 coupon for any user
On coupon actions set tax excluded
On Carrier set $0 to orders up to $100000
From a user account make an order for more tan $100000 without count tax, goes to the checkout page and check the coupon value.

Screenshots

![condiciones del descuento](https://user-images.githubusercontent.com/15943150/99098250-bec03b00-25a6-11eb-9c89-c098426c0cf5.png)

![importedescuento](https://user-images.githubusercontent.com/15943150/99098280-ca136680-25a6-11eb-9529-1b7b4c16ffdc.png)

![importedescuento](https://user-images.githubusercontent.com/15943150/99098384-ec0ce900-25a6-11eb-8b91-416795769756.png)

![importedescuentoexcluidoimpuestos](https://user-images.githubusercontent.com/15943150/99098330-dbf50980-25a6-11eb-87f9-362611133de2.png)

Additional information
• PrestaShop version: 1.7.6.5
• PHP version: 7.2.28

**Comment by HartLarsson** [comment]
If you specify a voucher ammount without tax and your cart add the tax, the voucher will be incremented by the tax itself.
if you want to discount the total cart (tax included) by your voucher value the voucher must be set to be tax included.
In case your customer have no tax bonus (export) the voucher will be decrased by the same % of tax too.

**Comment by hibatallahAouadni** [comment]
Hello @barbosatrix 

Like @HartLarsson said, that's the normal behavior. 
I attached a screen record for you to understand better the process:

https://drive.google.com/file/d/1P673tR20jhSy9_lnH43ALrwi1n8Chs5k/view

So, please change the voucher tax to **tax included** to have your 25000$ discount, see the attached screen record below:

https://drive.google.com/file/d/1CTaGonHHtazzNmd2ppnOSXfVASWFXLwx/view

Please check and feedback.

Ping @PrestaShop/product-team , please check if I miss something.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @barbosatrix 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
