### ISSUE TITLE
Cannot import the template

### ISSUE THREAD

**Issue by freepandagraphist** [PrestaShop/PrestaShop#21918]
![prestashop bug](https://user-images.githubusercontent.com/74464778/99152580-eb597d00-26a2-11eb-983a-2baf8bd8ff87.JPG)
 As you can see in the image, i cannot import from the FTP, i can see the file's name on the list but there's a problem with the scroll, i cannot select anything......
I think it's a prestashop problem, i sent an email but got no answer.....

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by freepandagraphist** [comment]
i don't see how to explain it better...... there is a problem in the field adding a theme, "import from FTP"  as you can see in the picture, I cannot choose anything, the scroll window doesn't open. It is a bug from the website prestashopp.....

**Comment by SimonGrn** [comment]
Hello,

we have a template to fill up when you click on "New Issue". You deleted it all, and now we don't have crucial information like your PrestaShop version, or your PHP version, or what steps you used exactly.
We are not machines, we are real humans and using the template is the fastest and most efficient way to help us help you. We spend our time to answer and help people, we just ask for a little respect for our processes.

Your problem probably lies in the fact that you're using the wrong PHP version: did you follow correctly the [requirements ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)?

**Comment by freepandagraphist** [comment]
hello, I don't think it is my theme that is wrong, because i can't even select the included ones in the list... I'm gonna call prestashop directly i think, thank you for trying to help anyway...

**Comment by SimonGrn** [comment]
There is nothing wrong with your theme, the problem is your PHP version. Please read my comment again.

**Comment by freepandagraphist** [comment]
I'm working on MAMP and my version of PHP is 7.4.1, and in the requirements it is written 7.1 or later....So it should work then....

**Comment by freepandagraphist** [comment]
Ok, i went to the 7.3 version and it works so thank you a lot :D

**Comment by SimonGrn** [comment]
If you're using 1.7.6.8 (you didn't say), PHP must be 7.2 maximum.
![image](https://user-images.githubusercontent.com/49909275/99156650-d987d200-26c2-11eb-9ed7-9430dd446e11.png)
