### ISSUE TITLE
erreurs rich snippets in google search console in productcomments module 

### ISSUE THREAD

**Issue by Brunettib78** [PrestaShop/PrestaShop#21927]
Hello, the "Avis Customer V4.1.0" module generates google errors. How to solve this problem?
thks
see result google rich snippets testing tool
https://search.google.com/test/rich-results?id=Y05sc4-Mxxav1rdO22Q7LA

Version de PrestaShop : 1.7.6.8
Version de PHP : 7.2.34

URL de la boutique : http://stagereiki.com/boutique/
Thème actif : classic

**Comment by hibatallahAouadni** [comment]
Hello @Brunettib78 ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- steps to reproduce
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report]
(http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

PS: Please change the issue's title into English, cause English is the norm on GitHub.

Thanks!

**Comment by Brunettib78** [comment]
Hi,
thanks for your reply.
I change the title post in english
please find more informations

URL shop : http://stagereiki.com/boutique/
Thème classic

about server setup and configuration :
serveur Linux 1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64
in Apache/2.4.25 (Debian), PHP version : 7.2.34

about SQL:
Version de MySQL : 10.3.22-MariaDB-0+deb10u1
Serveur MySQL : 91.216.107.164 
browser Chrome/86.0.4240.183

There is no bug on prestashop. The reviews entered online work perfectly. 
all customer review settings are enabled, and everything is displayed perfectly. 

The problem is on the google search console which detects warning and errors on the products 
**_" You must indicate "offers", "review", or "aggregateRating"_**"  errors 
and and in case of several comments: **_contains several cumulative scores_**

here find an exemple of google search console report product:
[google example report ](https://search.google.com/test/rich-results?id=vjQ0_78ngjOGs0_ecm5Ukw)

I hope my english is understandable
thanks for your help
Bruno

**Comment by matks** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/18692

**Comment by Brunettib78** [comment]
thanks matks.
but no change with the productcomment-dev module
any other idea?
[see result google](https://search.google.com/test/rich-results?id=AOsrvXm8qtj5Lp2EU9zlVQ)

**Comment by hibatallahAouadni** [comment]
Hello @Brunettib78 

I didnt't manage to reproduce your issue, could you please check the attached screen record below:

https://drive.google.com/file/d/12xOt_WF6uDjHk8seZYFuLBStjPAscNJI/view

Please check and feedback.

Thanks!

**Comment by Brunettib78** [comment]
Hello @hibatallahAouadni 
I've changed the product.tpl file, on  "_**/boutique/themes/classic/templates/catalog/_partials/miniatures**_" folder.
and now there's **just 1 Error** et 2 warning instead of 7

the error is stil the same "The notice contains several cumulative ratings" or L'avis contient plusieurs notes cumulées in french.
[see report here](https://search.google.com/test/rich-results?id=pJOP-o56ReHfGGAes3qhhA)

I'm making progress but the error is still there

Any idéas?

**Comment by hibatallahAouadni** [comment]
Hello @Brunettib78 

Could you please check if your issue is similar to this one #12687

Thanks!

**Comment by Brunettib78** [comment]
HI @hibatallahAouadni 

I've tried to make change with this #12687 with little results on google warnings, but not for this same error repeated " L'avis contient plusieurs notes cumulées" ( the review contains several cumulative ratings) 

[google console test result here](https://search.google.com/test/rich-results?id=JdHjqVoodRArxuu1H4E0Lg)

thanks

**Comment by Brunettib78** [comment]
HI @matks @hibatallahAouadni 

After uninstall and reinstall module productcomments, Errors are gone :)
the "L'avis contient plusieurs notes cumulées" errors were resulted from a double data setting, and therefore one too many...   thanks for your help
bruno

**Comment by hibatallahAouadni** [comment]
Hello @Brunettib78 

You're welcome,glad to hear your problem is solved.
So, I close this issue.

Thanks!

**Comment by Jojo-Kaly** [comment]
> HI @matks @hibatallahAouadni
> 
> After uninstall and reinstall module productcomments, Errors are gone :)
> the "L'avis contient plusieurs notes cumulées" errors were resulted from a double data setting, and therefore one too many... thanks for your help
> bruno

I also have the error "L'avis contient plusieurs notes cumulées". How are you fixed this problem precisely ?
Thank you.
