### ISSUE TITLE
When I toggle product status from search page it overrides previously set redirection options

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#21929]
#### Describe the bug

When I toggle product status from search page it overrides previously set redirection options, wether you enable or disable the product it uses `Product::toggleStatus`
https://github.com/PrestaShop/PrestaShop/blob/59f2ca0e1ec873195be0a3d879415c273b7d126a/classes/Product.php#L1129

This method forces the reset of the redirection options, so any configuration previously set in the product page will be erased/overridden. When you toggle the status from the product page, or from the product list it doesn't happen, it keeps the configuration set in product page just as expected?

#### Expected behavior

When I toggle the status from search list the redirect options are not modified.

#### Steps to Reproduce

1. Go to a product page edition in the BO
2. Go in the SEO tab and change its redirection options from the default ones (for example redirect to a product and select a product)
3. In the FO go to the product page which should be correctly displayed
4. Disable the product from the BO product page
5. You should copy the FO product page link as it will be useful for further tests
6. Refresh the FO product page you should be redirect to the other selected product
7. Go the the BO product list, enable the product and the disable it again
8. Check on the FO the product page is still correctly redirected to the selected product
9. Enable the product again so it is accessible in the FO
10. Now in the BO make a search in the top bar for the modified product, you should see a list which allows you to toggle the product status
11. Disable the product
12. Go to the FO and try to access the product page, you are redirect to a category page (default redirect options) which is not the expected configured behaviour
13a. Alternatively you can check in the BO product page that the redirection configuration has been modified
13b. Alternatively you can check in the database that the fields `redirect_type` and `id_type_redirected` have been modified

**Screenshots**

Configuration:

![Capture d’écran 2020-11-16 à 11 38 51](https://user-images.githubusercontent.com/13801017/99243050-5d93a400-2800-11eb-8285-e1c75f48cdff.png)

#### Additional information

* PrestaShop version: develop (at least)
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @jolelievre 

I managed to reproduce the issue with develop. With PS1.7.6.8 and PS1.7.7.0-rc.1+build.4, it couldn't be reproduce it cause of another issue #18708.
See the attached screen record below:

https://drive.google.com/file/d/1AuVUZ8cXczh5611K1--LlphHSeyUPA5Z/view

Thanks!
