### ISSUE TITLE
CSV PRESTASHOP CANT MATCH COLUMNS

### ISSUE THREAD

**Issue by devillers** [PrestaShop/PrestaShop#21920]
### Hello
I facing an issue when importing my product_items.csv file.
I can't match each column of my source file to one of the destination columns. Most of the fields names have disappeared , 

Names as **category(x,y,z) reference** etc are missing...

link to my screenshot[https://drive.google.com/file/d/1VOUlXwAcI7txejjazbUsojSYxf9CjXmJ/view?usp=sharing](url)

could you please help 👍 

Thanks David

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
