### ISSUE TITLE
Release 1.7.6.9 🚀

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#21926]
This issue tracks the status of the PrestaShop 1.7.6.9 release

The 1.7.6.9 version will be a security fixes release only.

### Information

Q | A
--|--
**Type** | Patch version
**Estimated release** | 2020-11-**
**Delivery date** | 2020-11-16

### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] [Release](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.9)
- [x] Available for upgrade
- [x] Docker image

**Comment by PierreRambaud** [comment]
Docker images are available: https://hub.docker.com/repository/docker/prestashop/prestashop/tags?page=1&name=1.7.6.9

**Comment by atomiix** [comment]
PrestaShop 1.7.6.9 is now available on [Github](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.9), [prestashop.com](prestashop.com) and through the 1-Click upgrade plugin!

**Comment by matks** [comment]
Congratulations @atomiix and thanks for the hard work
