### ISSUE TITLE
Pre-filled registeration form with previous customer data

### ISSUE THREAD

**Issue by rithiksachdev** [PrestaShop/PrestaShop#21925]
It does not happen all the time, sometimes it is an issue with google chrome.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
