### ISSUE TITLE
ps_facetedsearch: hide products that are not in stock

### ISSUE THREAD

**Issue by Spir** [PrestaShop/PrestaShop#21936]
Customers are complaining because they see results for products that are not in stock when some filters have been selected (ie: for shoes the size of the foot). It would be great to hide the products that have no stocks without having to check the "In stock" button. To have this option by default.

Il serait vraiment intéressant d'avoir la possibilité de ne pas avoir le bouton "en stock" / "non disponible" avec la navigation a facette mais de caché les produits qui ne sont pas en stock par défaut.

I'm using the version 3.6.0 of Ps_Facetedsearch with Prestashop 1.7.6.8.

**Comment by hibatallahAouadni** [comment]
Hello @Spir 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

>Il serait vraiment intéressant d'avoir la possibilité de ne pas avoir le bouton "en stock" / "non disponible" avec la navigation a facette mais de caché les produits qui ne sont pas en stock par défaut.

Please submit your request next time in English, English is the norme of Github.

Thanks!
