### ISSUE TITLE
When all products have the exact same date_add/date_upd, the pagination doesn't work properly

### ISSUE THREAD

**Issue by Jeremy-VERNET** [PrestaShop/PrestaShop#21933]
#### Describe the bug

In order to fix [this bug](https://github.com/PrestaShop/PrestaShop/issues/21707), I had to apply the current date to the _date_add_ and _date_upd_ fields, for all my products, in the _ps_product_ and _ps_product_shop_ tables.

This triggered another problem. Product pagination was set based on the date the product was added, and since all products had the exact same date, pagination no longer worked.

That is, in page 2 of a category, it was showing products already shown on page 1. Therefore, some products were never displayed.

To solve this problem, I had to loop in the base by adding a second to the date of addition of each product so that all the dates are different.

#### Idea to fix

I did not look into the core file but I guess that the pagination is based on a single criteria (_date_add_), maybe we coul also add a second criteria (the _id_product_).

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by SimonGrn** [comment]
Hello,

I'm not sure I follow, because the initial issue you pointed (#21707) is the result of a manipulation you made yourself where you broke the integrity of your database.
So in this issue you're asking for an improvement to fix a problem introduced by your initial mistake, that wouldn't exist if you didn't make this manipulation ?

I don't recall somebody else having this problem and since it's the sole result of a wrong manipulation I'm not sure it qualifies as an issue or even an improvement.

Could you explain to us exactly what it is you're trying to improve here ?

**Comment by Jeremy-VERNET** [comment]
The first problem is indeed due to a migration and, still, I broke nothing, it was not really my fault since I only followed the guide. The main thing is to have found a solution.

The problem here is that, for safety's sake, in case someone changes the _date_add_/_date_upd_ (manually or through plugins to handle the New label, for example - those plugins exist), it seems to create pagination problems.

It's usually safer to add a second sort criterion. This is generally what is done everywhere, at least on the different Symfony applications I've been working on.

**Comment by matks** [comment]
@Jeremy-VERNET if I am not wrong, you can _choose_ what criterion is used for pagination 🤔  ?

> This triggered another problem. Product pagination was set based on the date the product was added, and since all products had the exact same date, pagination no longer worked.

By using the "sort by X" feature you can modify it ? 🤔

**Comment by Jeremy-VERNET** [comment]
> if I am not wrong, you can _choose_ what criterion is used for pagination 🤔 ?
> By using the "sort by X" feature you can modify it ? 🤔

@matks Sure, but I was specifically referring to default sorting by date which, in the current case, prevents pagination from working properly if all products have the exact same _date_add_/_date_upd_.

Adding a second criterion (by id_product) to this specific sorting option will solve this issue. This is a very specific problem but it is still a problem. Just because all products have the same date should not prevent something from working properly.

**Comment by SimonGrn** [comment]
>Just because all products have the same date

If I understand correctly, that shouldn't happen normally ? It's just when you update stuff manually in the base ?

**Comment by Jeremy-VERNET** [comment]
That is correct. But there may be cases where the user performs this kind of manipulation. It can be during a migration from an old version of Prestashop (as was my case), it can also be with plugins which modify the behavior of the "New" label etc...

It is a very small fix but it allows PrestaShop to take these possible changes into account and make sure the pagination will always work correctly (if the sorting is set by date, by default in the BO).
