### ISSUE TITLE
PHP 8 issue: Compile Error: Class PrestaShop\PrestaShop\Adapter\Entity\Attribute may not inherit from final class (Attribute)

### ISSUE THREAD

**Issue by teemumantynen** [PrestaShop/PrestaShop#21930]
This isn't a bug of PrestaShop but a compatibility problem rising from the new features of PHP 8 even when not trying to run PrestaShop on PHP 8. But I thought I should write about my findings in case someone else is in trouble with the same error. And  maybe someone has a more sustainable solution than my quick fix which I describe in the end.

**The problem:**

While trying to open BO orders view (menu /Order/Orders) or invoices view (menu /Order/Invoices) an exception is thrown:
Compile Error: Class PrestaShop\PrestaShop\Adapter\Entity\Attribute may not inherit from final class (Attribute)

.../var/log.dev:
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Class PrestaShop\PrestaShop\Adapter\Entity\Attribute may not inherit from final class (Attribute)" at /var/www/ps177rc1/var/cache/dev/namespaced_class_stub.php line 132 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Class PrestaShop\\PrestaShop\\Adapter\\Entity\\Attribute may not inherit from final class (Attribute) at /var/www/ps177rc1/var/cache/dev/namespaced_class_stub.php:132)"} []

.../var/cache/dev/namespaced_class_stub.php line 132:
class Attribute extends \Attribute {};

![Screenshot_20201116_115747](https://user-images.githubusercontent.com/40071674/99239012-2672c200-2803-11eb-9122-85297c85665f.png)

**The fix**

I have a module that has the following chain of library dependencies: php-http/client-common requires symfony/options-resolver  requires symfony/polyfill

Since a resently updated version 1.19.0 symfony/polyfill has included symfony/polyfill-php80 which now defines a "final class Attribute" in global name space:
https://github.com/symfony/polyfill/blob/main/src/Php80/Resources/stubs/Attribute.php

PrestaShop defines a (non-final) "class Attribute" also in global name space:
.../var/cache/prod/class_stub.php line 131:
class Attribute extends AttributeCore {};

So PrestaShop\PrestaShop\Adapter\Entity\Attribute is trying to extend PrestaShops's non-final \Attribute class but symfony/polyfill-php80's final \Attribute class conflicts with it.

To quickly fix the problem for now I ended up spesifying the highest allowed symfony/polyfill version by adding this line to my module's require-section in composer.json:
"symfony/polyfill-php80": "<=1.18.1"

PrestaShop 1.7.7 RC1
PHP 7.3.24
Apache 2.4.46
MySQL 8.0.22
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0

**Comment by matks** [comment]
Hi @teemumantynen ! thanks for the report

We already know that, indeed, PHP8 has not made things easy for us 😅 

A contributor started something to solve it in https://github.com/PrestaShop/PrestaShop/pull/20710

We aim for php8 compatibility for PS 1.7.9.
- PS 1.7.7 brings php7.3 compatibility
- PS 1.7.8 brings php7.4 compatibility

**Comment by teemumantynen** [comment]
Great! Thank you. I'll close this issue.

**Comment by amery** [comment]
I'm having this problem with 1.7.7.x with 7.2.33
`"symfony/polyfill-php73": "^1.10",`

please advice

**Comment by GabrieleMartini** [comment]
Found also on Prestashop 1.7.8.2 with PHP 7.4

**Comment by GabrieleMartini** [comment]
Found also on Prestashop 1.7.8.2 with PHP 7.4
`"symfony/polyfill-php73": "^1.10",`

**Comment by GabrieleMartini** [comment]
Found the same also on Prestashop 1.7.8.2 with php 7.4 
`"symfony/polyfill-php73": "^1.10",`

**Comment by npotier** [comment]
Hello @teemumantynen thank you for the tip.

`composer require "symfony/polyfill-php80:<=1.18.1"` worked like a charm and solved the issue

**Comment by abdullacm** [comment]
> Found the same also on Prestashop 1.7.8.2 with php 7.4 `"symfony/polyfill-php73": "^1.10",`

@GabrieleMartini were you able to fix this?

**Comment by giovkanata** [comment]
Same problem today with PrestaShop 1.7.8.4 with php 7.4.30 and `"symfony/polyfill-php73": "^1.10"`
Solved with `"symfony/polyfill-php80": "<=1.18.1"`

**Comment by matks** [comment]
> Hi @teemumantynen ! thanks for the report
> 
> We already know that, indeed, PHP8 has not made things easy for us 😅
> 
> A contributor started something to solve it in #20710
> 
> We aim for php8 compatibility for PS 1.7.9.
> 
> * PS 1.7.7 brings php7.3 compatibility
> * PS 1.7.8 brings php7.4 compatibility

Note: PrestaShop 8 introduces PHP8 and PHP8.1 compatibility https://build.prestashop.com/news/prestashop-feature-freeze-v8/
