### ISSUE TITLE
[UI-KIT] - BO - Order page - The Modal of updating a carrier is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21943]
#### Describe the bug

In the BO > Orders > Order details page > when we try to edit a carrier, the modal is not well displayed
![image](https://user-images.githubusercontent.com/16067358/99362753-2a125180-28b4-11eb-83d0-39554607735e.png)

#### Expected behavior

It should be 
![image](https://user-images.githubusercontent.com/16067358/99362847-44e4c600-28b4-11eb-893b-34034bda662f.png)

#### Steps to Reproduce

1. Go to BO > Orders > Order details page
2. Click on the Carriers Tab
3. Click on the Edit button

PS1.7.7.x => ok

#### Additional information

* PrestaShop version: develop(1780)
* PHP version: 7.2

**Comment by fire2** [comment]
This is still an issue on a fresh PrestaShop 1.7.8 install (I tried on 3 different installations). The modal is still showing incorrectly and it is impossible to put the tracking number. 

Browser: Safari. It works fine in Chrome but not in Safari.
Issue should be reopened.

**Comment by NeOMakinG** [comment]
Hey @fire2, thanks for the info

@hibatallahAouadni or anyone from @PrestaShop/qa-team could test on safari and adjust the issue regarding the ending? :)

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

It's true! I reproduce the issue with PS 1.7.8.0 and Safari (iPhone):

![image](https://user-images.githubusercontent.com/23308427/137901272-9426a5d2-dd42-45cb-996b-1bb6484c0f1c.png)

Reopen it as it's not fully fixed.
Thanks!

**Comment by hibatallahAouadni** [comment]
FYI: reproduce the issue with chrome 73 & related to #22315

**Comment by fire2** [comment]
afaik this issue was fixed on 1.7.8.1 and can be closed.

**Comment by hibatallahAouadni** [comment]
@fire2 thanks for the tip :wink: 
Indeed this issue has been fixed, cause I didn't encountered it with PS1782, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/149795758-b6a0fe7f-a4a7-4b11-85f3-90647818aa7e.png)

This issue is a duplicate of this one #22315 (as both has been fixed with the same PR).

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22315
