### ISSUE TITLE
Stats panel shows today earnings incorrectly

### ISSUE THREAD

**Issue by CraZzier** [PrestaShop/PrestaShop#21942]
Stats panel suggests that succesfull payment has been made today, however in orders tab there is no order today.
What can be reason for that?
Thanks for help and ideas

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
