### ISSUE TITLE
Install prestashop 1.7.6.9 on Deian

### ISSUE THREAD

**Issue by Aodren92** [PrestaShop/PrestaShop#21941]
Hi guys i had trouble to install Prestashop on a vps.
I had an Error about pelago.
Unfortunately  i didn't make a screenshot.
The only way to correct the error was to do this:
`$converter = CssToAttributeConverter::fromHtml($templateContent);  `
on file src/Core/MailTemplate/Transformation/CSSInlineTransformation.php line 70.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Aodren92** [comment]
Ok, i understand, So i leave some intructions to reproduce the bug:
Server configuration :
 - debian 10.6
 - kernel 4.19
 - php v7.2.34
 - "pelago/emogrifier": "^2.1.1" ( it's vendor lib who mke it breaks, i aslo tried with 2.1"
I install the latest version found on this repo : PrestaShop-1.7.6.9.tar.gz.
At the last step of the installation i got a big FATAL error because on file  src/Core/MailTemplate/Transformation/CSSInlineTransformation.php, it call a private construct of CssToAttributeConverter.

**Comment by SimonGrn** [comment]
Please open a new issue and **fill the template** (do **NOT** delete it).

Thank you.
