### ISSUE TITLE
New Hook title is greater than 64

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21951]
#### Describe the bug

New Hooks titles is greater than 64, during an upgrade 1769 to 177RC i have this errors

 Warning: #1265 Data truncated for column 'title' at row 21
 Warning: #1265 Data truncated for column 'title' at row 22
 Warning: #1265 Data truncated for column 'title' at row 23
 Warning: #1265 Data truncated for column 'title' at row 24
 Warning: #1265 Data truncated for column 'title' at row 25
 Warning: #1265 Data truncated for column 'title' at row 26

I can do a PR but what's the best way ? increase var_char of title or edit title ?

#### Steps to Reproduce

Made an update and check SQL waring or error

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Could you please modify original issue #21948 as there is no need to open a new one as long as all issues you are having are related. So, I close this ticket.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #21948

**Comment by ghost** [comment]
Hi @hibatallahAouadni it's not the same issue; it's a new issue after fixing the first one, for the change log we need 3 issues

**Comment by ghost** [comment]
Here (#21948) it's bit  Specified key was too long; max key length is 767 bytes

Here (#21951) it's the var_char size 64

**Comment by hibatallahAouadni** [comment]
@okom3pom I know its not the same problem but you encountered this problem after your fix. So to understand the whole problem, we need the whole process in the same ticket.

Thanks for your understanding.

**Comment by hibatallahAouadni** [comment]
Ping @matks wdyt?

**Comment by matks** [comment]
@okom3pom if I understand, during upgrade process, a new hook was supposed to be inserted but it failed because the name was too long?

**Comment by ghost** [comment]
@matks i found 3 problems during the upgrade for me we can't say is the same or duplicate :)

**Comment by matks** [comment]
@okom3pom yes I got this, I'm speaking about this exactly 😉  .

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

As discussed with @PierreRambaud it seems this topic is totally different from this issue #21948
So I reopen it.

PS: sorry for the misunderstanding.

Thanks!

**Comment by ghost** [comment]
@matks 

`@okom3pom if I understand, during upgrade process, a new hook was supposed to be inserted but it failed because the name was too long?`

Yes the name it's truncate on my config it's possible in another config the insert fails

**Comment by ghost** [comment]
This one can be closed because when i doing the test the upagrade failed and when upgrade is ok it's work because

```
ALTER TABLE `PREFIX_hook` CHANGE `name` `name` VARCHAR(191) NOT NULL;
ALTER TABLE `PREFIX_hook` CHANGE `title` `title` VARCHAR(255) NOT NULL;
```

**Comment by ghost** [comment]
I test towmorrow with the nightly build to be sure

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

> I test towmorrow with the nightly build to be sure

Should I leave it closed or reopen it and add the label **`waiting for author`**?

Thanks!
