### ISSUE TITLE
FO - An exception is displayed in the guest-tracking controller (when logged out) and in order details when logged in

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21950]
#### Describe the bug

In the FO > When we try to access to "the guest-tracking" page with a different language than the language used by the guest => an exception is displayed

![image](https://user-images.githubusercontent.com/16067358/99382814-5b4b4b80-28cd-11eb-9dfb-3d4ff403d461.png)

Edit by @Robin-Fischer-PS : 

Other way to have this error : 
On FO, if I try to access an order (in which there is a product with combination) in a different language than the one selected when placing the order, I have an exception.

This happens with demo product **and with newly created product and customer, so it's probably not linked to the demo data.**

#### Steps to Reproduce

1. Install PS with English language & France country
2. Go to FO with **French** selected as a language
3. Add demo_6 to the cart
4. Go to Checkout 
5. On the Personnel information page "order as a **guest**"
6. Complete Order
7. At this step: try to navigate to "Guest Order Tracking" using this URL: `shop.com/en/guest-tracking`
8. Set the `Order Reference:` of the last order
9. Set the `Email:` of the last guest added
10. Click Send
11. See error

PS: if you try with this URL: `shop.com/fr/suivi-commande-invite` => ok
In the 1770rc1build4 => ok

Edit by @Robin-Fischer-PS :

#### Other way to Reproduce

1. Install PS in English, select "France" as a country
2. On BO, create attributes and a product with combination using these attributes
3. On FO, create a customer and place an order with the newly created product (FO should be in French by default)
4. Go to customer account > Order History
5. Change language to "English"
6. Open the order created before : An exception is displayed

**Screenshots**

Screenrecord :
https://drive.google.com/file/d/1sAkCBfYN_6-3HfAx3_cOBRxCpL2gMkiG/view?usp=sharing

Screenshot of the exception : 
![exception fo combination product](https://user-images.githubusercontent.com/55688534/117296014-d9e47700-ae74-11eb-86d5-90aa2a934237.png)

#### Additional information

* PrestaShop version: 1.7.8.x, develop
* PHP version: 7.2

**Comment by matks** [comment]
@khouloudbelguith We merged `develop` into `1.7.7.x` [this morning](https://github.com/PrestaShop/PrestaShop/pull/21940). Would it be possible to check again if issue is still there?

**Comment by khouloudbelguith** [comment]
Hi @matks,

No, I still have the same issue: https://drive.google.com/file/d/1ETuyqDE6RgHZwsHVnaCUQj6T7AgQV5ZT/view?usp=sharing

Thanks!

**Comment by Robin-Fischer-PS** [comment]
Hi,

I can reproduce it with an install in English, and Country = France. On FO in French, after install, login with pub@prestashop.com. Go to any demo order : The error is displayed.

When changing the install in English : OK.

**Comment by Robin-Fischer-PS** [comment]
I edited the issue with a new, more obvious way to reproduce this issue, so I upgraded the sverity to Critical.

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24379
