### ISSUE TITLE
FO - Checkout page - the "cart-summary-products" is removed after adding a cart rule or removing it

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21961]
#### Describe the bug

In the FO > Checkout page > the the "cart-summary-products" is removed after adding a voucher or removing it
**Step1**
![image](https://user-images.githubusercontent.com/16067358/99412700-50a4ac80-28f5-11eb-81a3-968f40d9bb09.png)
**Step2**
![image](https://user-images.githubusercontent.com/16067358/99412861-79c53d00-28f5-11eb-8436-f4b6b7c7158b.png)
**Step3**
![image](https://user-images.githubusercontent.com/16067358/99413078-af6a2600-28f5-11eb-9053-afd94b9ff3d8.png)

#### Expected behavior

Fix the total price.

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page > Create a new cart rule
1.1 Information: with a code / Highlight = enabled
![image](https://user-images.githubusercontent.com/16067358/99413378-ffe18380-28f5-11eb-992c-296c748fb150.png)
1.2 No conditions
1.3 Any action, for example, free shipping
2. Go to FO > sign in
3. Add a product to the cart
4. Go to the checkout page
5. Add the promo code => see the error
6. Refresh the page => ok
7. Remove the cart rule 
8. see the error

PS177x branch => ok
https://drive.google.com/file/d/1QLXkqQdijEQhfX9w7VeK5Ip-r7PYbcCj/view?usp=sharing
**Screenshots**
https://drive.google.com/file/d/1Ron5lAlu17YRxgQzJ0zpt5KIqBrp-4Af/view?usp=sharing

#### Additional information

* PrestaShop version: develop(1780)
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24795
