### ISSUE TITLE
Bug in DeliveryOptionsFinderCore

### ISSUE THREAD

**Issue by nihad-alic** [PrestaShop/PrestaShop#21966]
Hi I would like to report a bug in DeliveryOptionsFinderCore, where translation of price with/without tax is not shown properly  due to $include_taxes variable not checking carrier selected/configured tax. 

`$include_taxes = !Product::getTaxCalculationMethod((int) $this->context->cart->id_customer) && (int) Configuration::get('PS_TAX');`

To my understanding this variable should be set to check carrier tax options and not product or global tax configuration...
`$include_taxes = Carrier::getIdTaxRulesGroupByIdCarrier((int)$carrier['id']) != '0';` where 0 is default for no tax at all...

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
