### ISSUE TITLE
How application administrator pay for platforms that serve customer on the application?

### ISSUE THREAD

**Issue by rawan321** [PrestaShop/PrestaShop#21964]
if there was an app that has multiple shops on it for printing services, how the printing shop provider get their money from the application admin? by using what method? the application has driver also to deliver the printing papers to customer; so that it will be cash on delivery payment method.
please share your idea with me!

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
