### ISSUE TITLE
PS 1.7.6.9 multistore Notice: Undefined index: iso_code error on second store

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#21970]
Try to installa a ps 1.7.6.9 multistore , after adding second store in debug mode this error are generated on frontend

(1/1) ContextErrorExceptionNotice: Undefined index: iso_code
--
in Tools.php line 774
at ToolsCore::displayPrice(0.0, array())in PriceFormatter.php line 55
at PriceFormatter->format(0.0)in CartPresenter.php line 336
at CartPresenter->present(object(Cart))in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 548
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

ps 1.7.6.9
apache2 php 7.2

**Comment by matteolavaggi** [comment]
Default currencies are not attached to new created store if not "imported" really complicated

To fix -> need to go localization - currency - open EVERY currencies and attach to new created store.

**Comment by hibatallahAouadni** [comment]
Hello @matteolavaggi 

I didn't manage to reproduce your issue with PS1.7.6.9. 
Even you fixed, could you please provide the **steps to reproduce** your issue, is there any particular details you didn't mention above? 
Cause we need to figure it out if there's a bug or not with the new release.

Thanks!
