### ISSUE TITLE
Logo, favicon and stores icon are not displayed in the 1.7.7.0-RC.1

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#21979]
#### Describe the bug

Since the latest changes on 1.7.7.x, themes are broken after an upgrade.

For example in the classic theme we now have:
```html
  <link rel="icon" type="image/vnd.microsoft.icon" href="{$urls.img_ps_url}{$shop.favicon}?{$shop.favicon_update_time}">
```
When it should be 
```html
  <link rel="icon" type="image/vnd.microsoft.icon" href="{$shop.favicon}?{$shop.favicon_update_time}">
```

#### Expected behavior

We should be able to reach `logo`, `stores_icon`, `favicon` without having to put the `_PS_IMG_` constant before.

#### Steps to Reproduce

Use a theme that is not the classic theme
For example: https://github.com/prestarocket-agence/classic-rocket

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by ghost** [comment]
@PierreRambaud you don't have to use an other theme juste skip update theme during install it's easier for test :)

**Comment by PierreRambaud** [comment]
> @PierreRambaud you don't have to use an other theme juste skip update theme during install it's easier for test :)

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud, @okom3pom,

I manage to reproduce the issue with the 177x branch
![image](https://user-images.githubusercontent.com/16067358/99545313-8b6e1980-29b5-11eb-9e43-be7bfbd7a1b0.png)

Ok with PS1768
![image](https://user-images.githubusercontent.com/16067358/99545370-9b85f900-29b5-11eb-8444-8e04e33b1fa8.png)


Thanks!

**Comment by ghost** [comment]
All credits to @micka-fdz  for this issue

**Comment by micka-fdz** [comment]
Thanks @okom3pom for credits and @PierreRambaud for your issue and PR. You rocks!

**Comment by sotirisa** [comment]
Hi,

I still have this problem with 1.7.7.0 is this because of my theme or because of the new prestashop?

**Comment by ghost** [comment]
Hi,

I think it's you theme or an override.

U can compare your files with this PR https://github.com/PrestaShop/PrestaShop/pull/21981/files
