### ISSUE TITLE
Allow friendly URLs to turn Greek into Latin characters

### ISSUE THREAD

**Issue by georgelouk** [PrestaShop/PrestaShop#21978]
#### Is your feature request related to a problem?

It's not a problem actually, but it's frustrating if you work with Greek language.

When you create a new category or a new product using Greek language it doesn't autocomplete the friendly URL field like it does in English

#### Describe the solution you'd like

Greek characters can be automatically translated to english / latin characters using ELOT 743 which is officially used by greek authorities in such cases.

#### Alternatives you've considered

The alternative is to stay as it is

**Comment by hibatallahAouadni** [comment]
Hello @georgelouk 

Thanks for the suggestion, it seems a good idea. The Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by georgelouk** [comment]
I have the JavaScript function ready if you want to adapt it.

**Comment by hibatallahAouadni** [comment]
Hello @georgelouk 

If you have already fixed it on your end, please do send us a pull request!
And fill the description and how to test the PR, like the screenshot below:

![image](https://user-images.githubusercontent.com/23308427/99541049-a12d1000-29b0-11eb-9c62-944930ab892a.png)

(1) => Improvement
(2) => mention this ticket (#21978)
Thanks!

**Comment by georgelouk** [comment]
@hibatallahAouadni sorry misunderstanding.
I don't have implemented at PrestaShop, i have implemented it at another project, so the JS function that does the job is ready and i can provide it.

**Comment by LouiseBonnard** [comment]
Hi @georgelouk, and thanks @hibatallahAouadni. Could you tell me which version of PrestaShop do you use? If you go to the Shop Parameters > Product Settings page and set the 'Force update of friendly URL' option to 'Yes', then updating the name of your product (even in Greek) should automatically update the friendly URL.

<img width="800" alt="Capture d’écran 2020-11-19 à 18 07 29" src="https://user-images.githubusercontent.com/32565890/99699326-1de3eb00-2a92-11eb-93ae-89104637da5c.png">

**Comment by georgelouk** [comment]
Hi @LouiseBonnard 
I'm using version 1.7.6.8 and with force update friend url to YES didn't work for me. I've saved, i've modified the title but nothing. I also tried English version of backend instead of Greek, but didn't added the greek characters at the friendly url (check screenshot).

But even if it works i was actually talking to automatically transform greek characters to latin characters in order the friendly URL to not have any Greek character.

So at your example should display hello-geia instead hello-γεια

![Screenshot 2020-11-20 at 10 20 25 AM](https://user-images.githubusercontent.com/388961/99777875-98a51880-2b1b-11eb-9c4c-47904253c3d8.png)

**Comment by LouiseBonnard** [comment]
Okay @georgelouk, thanks a lot for your explanation, I'll just edit the title of this feature request to make it clearer. But if you can provide the JS function that worked for another project, please share it here, I'm sure it will help other Greek users. ;-)

**Comment by georgelouk** [comment]
@LouiseBonnard Ok i will provide it. I wrote that title because i didn't know that it can automatically show greek chars at friendly url. I use presta from version 1.4 and never show that and actually all the e-shops i work are in greek lang.

**Comment by jf-viguier** [comment]
@georgelouk you have to activate Accented URL in SEO & URLs menu.
With this parameter you will have greek characters in url. IMO it's the best way.
Prestashop don't have to manage characters conversions nativelly : it's a custom need, not a generic one. WDYT @LouiseBonnard ?

**Comment by georgelouk** [comment]
@jf-viguier ok i understand that. It works. But in general, as greeks, we don't use greek characters at the urls, the strategy is to avoid them, but it's not a need/requirement in order to work, it's a custom need as you said.

Thanks for replying.

**Comment by info264** [comment]
> I have the JavaScript function ready if you want to adapt it.

Hi, could you please share this JS with me?
