### ISSUE TITLE
Remote payment accepted but PrestaShop does not see the order as paid...

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#21974]
Hi,
the customer placed an order with bank transfer payment.
The order entered regularly.
The payment went into the bank after two days
We changed the payment status to "remote payment accepted"
But PrestaShop did not register the payment so the order was still € 0
We believe it is an anomaly only of this order, how can we see the reason for this with debugging?
Currently debugging does not return any errors.

We tried to change status many times without success:
![order-problem](https://user-images.githubusercontent.com/28685316/99516919-0839cd00-298f-11eb-8ad6-6f45b08451d1.png)

Can we manage it manually?
Thanks.
Balla

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

I didn't manage to reproduce your issue with PS1.7.6.8, see the attached screen record below:

https://drive.google.com/file/d/1zv4LkTVrvQoOUUGeUjUNB4bfNghZ6mZ4/view

Please check and feedback.
> We believe it is an anomaly only of this order

What did you mean by that?

Thanks!

**Comment by ballashop** [comment]
Hi @hibatallahAouadni 
thanks to replied me, I mean that the problem happened just for this order, i wanted to ask you if there is a way to see debug or log file to check where the error is.
Furthermore, if we can manually indicate to PrestaShop that the payment has entered.
Thanks for any reply.
Balla

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

If this order's payment was made via **Paypal** module, you didn't have to change the status. The Paypal module will automatically change it to **Remote Payment Accepted**.

Whatever the module you use for the payment please contact the module developper to solve your problem.
**Again, you shouldn't change the order's status manually, when you use a payment module**

If the module's developper doesn't respond, please report your issue in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack). They can help you to solve your problem manually.

I'm closing this issue cause it's not a PrestaShop Core bug.

PS: this bug is similar to yours, it may helps you, checkout it out #15639

Thanks!

**Comment by ballashop** [comment]
Hi @hibatallahAouadni 
payment was made via the native bank transfer prestashop module, no paypal or other methods.
Is there a PrestaShop debug or log that can show why this happened?
How should we intervene to tell PrestaShop to accept the payment?
Thanks a lot.
Balla

**Comment by ballashop** [comment]
Hi @hibatallahAouadni 
unfortunately link #15639 does not help us, thanks anyway for trying.
balla

**Comment by hibatallahAouadni** [comment]
Hi @ballashop 

Could you please activate the debug mode, like the screenshot below:

![image](https://user-images.githubusercontent.com/23308427/99538515-5a89e680-29ad-11eb-9132-9f5c565df38b.png)

Please check and feedback.
Thanks!

**Comment by ballashop** [comment]
Yes @hibatallahAouadni , 
we did, but the debug didn't show any error message.
When the debug is active, then I have to do change status orders to show errors? 
Thanks a lot.
Balla

**Comment by hibatallahAouadni** [comment]
Yes, please enable the debug mode, then change the status order and let's if there's a bug.

**Comment by ballashop** [comment]
Hi @hibatallahAouadni 
debugging found no errors! :(
I don't know whether to be happy or not!

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

Could you please follow my steps in the screen record below:

https://drive.google.com/file/d/1HN87QR3_2ci9PF-xy32Nf5GCGx2UEzXx/view

Please check and feedback.
Thanks!

**Comment by ballashop** [comment]
Hi @hibatallahAouadni 
Unfortunately it didn't work :(
Thanks

**Comment by ballashop** [comment]
Dear @hibatallahAouadni 
when the order has been delivered, the status is changed, so I would ask you to close this issue since the problem is solved, honestly we have not done anything. Perhaps a temporary bug of something that is beyond of comprehension at the moment.
Thanks a lot for your support.
Balla

**Comment by hibatallahAouadni** [comment]
@ballashop Good to know, you're welcome!
