### ISSUE TITLE
[Multistore] - BO - Order page - An alert "Error! There are not enough products in stock." is displayed when updating the product quantity

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21987]
#### Describe the bug

"Share available quantities to sell" option is enabled, "All shops" is selected, in the BO > Orders > Order page > when we try to update the product quantity => an alert "Error! There are not enough products in stock." but the Available quantity > 0

#### Steps to Reproduce

1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
![image](https://user-images.githubusercontent.com/16067358/98949230-b957e780-24f7-11eb-895a-5f53c37e7085.png)
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
![image](https://user-images.githubusercontent.com/16067358/98949184-a9400800-24f7-11eb-96b9-b3ac63e8c1e4.png)
5. Create a `productA` in all shops 
6. Quantity of the `productA` in the shopA = 12
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
![image](https://user-images.githubusercontent.com/16067358/98950543-6da63d80-24f9-11eb-991b-4667e76042b0.png)
11. Go Back to the Order => last order created => All shops selected
12. Try to increase the quantity => you have an alert 
```php
"Error!
There are not enough products in stock."
```
But the **Available quantity > 0**
![image](https://user-images.githubusercontent.com/16067358/99557902-77c9af80-29c3-11eb-8509-b8c62a703f97.png)

If you select the shopA => ok

PS: 1768: https://drive.google.com/file/d/1Q7ScfJ51BsYZWb8cMJA8pIuPeiN5H4si/view?usp=sharing => ok 

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #22228
