### ISSUE TITLE
[Multistore] - BO - Order page - All shops selected - cannot return products 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21990]
#### Describe the bug

"All shops" is selected, in the BO > Orders > Order page > when we try to return products => An exception is displayed
![image](https://user-images.githubusercontent.com/16067358/99559255-de030200-29c4-11eb-9eca-948fc19f5806.png)

#### Steps to Reproduce

Enable Multishop Context.
Create a new shop `ShopA` related to the `Default` Group
Create an Order from the FO in any shop 
Go to BO > Customer Service > Merchandise Returns > Enable returns in all shops
Go Back to the Order => last order created => All shops selected
Change the status of the Order to Shipped 
Click on "Return Products"
Select Products
Click on Return products
See error
![image](https://user-images.githubusercontent.com/16067358/99560085-c0826800-29c5-11eb-9cbc-6cc4661e8560.png)

PS: 1768 => ok
https://drive.google.com/file/d/1Fy1srxxiYJ1ucIh9hGPlRSXuxtVfsfR_/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/21905

**Comment by Progi1984** [comment]
@marionf #21905 existed in 1768, so this issue is not a regression, but a duplicate. Isn't it ?

**Comment by marionf** [comment]
The scenario to reproduce the issue in #21905 is different and is when we try to cancel a product
Here it's when we try to return products and it's a regression as it was working without errors in 1.7.6.8

**Comment by Progi1984** [comment]
Fixed by #22246
