### ISSUE TITLE
Bug fix with check usedKeys

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#21999]
#### Describe the bug

I use webp photo generation and stack next to jpeg file. That is, I always have two files on the server. xxxx.jpg and xxxx.jpg.webp. The second time I added the menu thumbnail to the category, I ran into such a problem that it started creating a file with index 1, although it should have created a file with index 0

#### Steps to Reproduce

1. Add thumbnail menu to any category, for example category id 10
2. Go on server in folder /img/c/10-0_thumb.jpg => /img/c/10-0_thumb.jpg.webp
3. Again add thumbnail menu to category id 10
4. An image will be created with the path: /img/c/10-1_thumb.jpg.webp

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @dariusakafest 

It's not a bug, you didn't click on delete button to delete the first thumbnail as you can see in the attached screen record below:

https://drive.google.com/file/d/1QSwnQ1etP2pMzkSiQ_G7AARZ299cwVh2/view

So, if you didn't delete the thumbnail, the system just add another one with index **id_category-1**.

![image](https://user-images.githubusercontent.com/23308427/99775378-7e653d80-2b0f-11eb-9901-d53ef5b4aade.png)

Please check and feedback

Thanks!

**Comment by fest73** [comment]
@hibatallahAouadni In fact, I don't have an image on the server. He will have to load it with index 0, but since the regular expression searches by an entry and not by the end of the path, such a problem arises!

**Comment by fest73** [comment]
@hibatallahAouadni Please check carefully

**Comment by hibatallahAouadni** [comment]
@dariusakafest could you please attach a screen record, thanks!

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team what do you think? is this the normal behavior or is it a bug?

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

I followed these steps: 

1. Add thumbnail menu to any category, for example category id 10
2. Go on server in folder /img/c/10-0_thumb.jpg => /img/c/10-0_thumb.jpg.webp
3. Again add thumbnail menu to category id 10
4. An image will be created with the path: /img/c/10-1_thumb.jpg.webp

And that was the result, I have two thumbnails for a category:

https://drive.google.com/file/d/1QSwnQ1etP2pMzkSiQ_G7AARZ299cwVh2/view

![image](https://user-images.githubusercontent.com/23308427/99775378-7e653d80-2b0f-11eb-9901-d53ef5b4aade.png)

So, I reproduced his issue but my question is:
Is this the normal behavior or is it a bug? can a category have two thumbnails or should have only one?

---
**Edit: I didn't manage to reproduce the issue with PS1.7.7.1, see the attached screen record below:**

https://drive.google.com/file/d/1iyD-b5Ii9iTT2QUanL8xuukcqCCeIGWz/view

Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @marionf as you can see in my last comment: 

> I didn't manage to reproduce the issue with PS1.7.7.1, see the attached screen record below:
https://drive.google.com/file/d/1iyD-b5Ii9iTT2QUanL8xuukcqCCeIGWz/view

So, what's the issue status? is it **`To Do`**?
Ping @dariusakafest could you please check my screen record with PS1.7.7.1 and check if the issue still persist or no?
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @dariusakafest ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
