### ISSUE TITLE
BO - Order page - when deleting all products - the total invoice is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21991]
#### Describe the bug

BO - Order page - when deleting all products - the total invoice is NOK

#### Steps to Reproduce

1. Create order from the FO with only one product
2. In the Documents tab > generate an invoice
3. Try to delete the product
4. In the Documents tab => the total is not updated / invoice => nok
![image](https://user-images.githubusercontent.com/16067358/99561365-28857e00-29c7-11eb-9341-d3766153beaf.png)
5. Download the invoice => NOK
![image](https://user-images.githubusercontent.com/16067358/99561423-376c3080-29c7-11eb-896f-2501f39e290e.png)

PS1.7.6.8 => ok 
https://drive.google.com/file/d/1JKleufKGySk1LHpJ7ORf9lMYCP2iEU5X/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/21903

**Comment by jolelievre** [comment]
Is it really related to #21903 ? Cancel and delete product are two different actions which do not have the same consequences
So in this issue what was done delete (with the trash icon) or cancel (with the cancel button when merchandise return is enabled)?

**Comment by jolelievre** [comment]
Ok I understand why it was related, because there was the same mistake on invoice totals I fixed both issues in the same PR anyway

**Comment by Progi1984** [comment]
Fixed by #21994
