### ISSUE TITLE
 Prestashop Order Status Message 

### ISSUE THREAD

**Issue by cakir59** [PrestaShop/PrestaShop#21997]
I want to show a special message on the order history page based on the order status. But I couldn't find their shortcode. For example, if the order placed is "preparing", I want to show the message that your order is being prepared on the order history page. I want it not to write anything if it is on the way or is delivered or canceled. How can I get the order status in tpl file?

I try

        {if $orders.detail.preparing}
        <p>your order preparing click here to view live cam</p>
{else}
-
        {/if}

but this code not working. I want order status short code.

**Comment by hibatallahAouadni** [comment]
Hello @cakir59 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help (**for free**) in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
