### ISSUE TITLE
Contactform confirmation mail problem

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#22003]
Hello,

When confirmation email is activated in contactform module configuration: 

<img width="1349" alt="Capture d’écran 2020-11-19 à 10 00 14" src="https://user-images.githubusercontent.com/167037/99644329-169aee00-2a4e-11eb-9b13-5038f72d64bf.png">

Some variables are not converted: 

<img width="558" alt="Capture d’écran 2020-11-19 à 10 01 43" src="https://user-images.githubusercontent.com/167037/99644542-5d88e380-2a4e-11eb-8981-67d50b9662a9.png">

* PrestaShop version: 1.7.6.7
* Contactform module version: v4.1.1 
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

Please edit your issue report, **you must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Thanks!

**Comment by hibatallahAouadni** [comment]
Could you please check if your issue is similar to this one #16563

Thanks!

**Comment by Daaaaad** [comment]
Hi @hibatallahAouadni, 

No that was not related to uppercase characters... BUT the v4.3.0 upgrade seems to fix the problem 😉

**Comment by hibatallahAouadni** [comment]
@Daaaaad Good to hear! So can we close this issue?

**Comment by Daaaaad** [comment]
@hibatallahAouadni Yes 👍
