### ISSUE TITLE
Dead JS dependency in admin-dev/filemanager/dialog.php

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22002]
#### Is your feature request related to a problem?

The very old code `admin-dev/filemanager/dialog.php` has an option that rely on 2 JS scripts that are no longer there.

https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/filemanager/dialog.php#L216

```
<?php
        if ($aviary_active) {
            if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) {
                ?>
				<script type="text/javascript" src="https://dme0ih8comzn4.cloudfront.net/js/feather.js"></script>
			<?php
            } else {
                ?>
				<script type="text/javascript" src="http://feather.aviary.com/js/feather.js "></script>
			<?php

            }
        }
    ?>
```

https://dme0ih8comzn4.cloudfront.net/js/feather.js => dead
http://feather.aviary.com/js/feather.js => dead

So this option cannot work as the source code is long gone.

#### Describe the solution you'd like

Remove this option (or restore it using a good source)

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by PrestaEdit** [comment]
Hi,

This was neved used, I think. The aviary_active is set to false, there is no option about this.
