### ISSUE TITLE
Prestashop Forum Signup Verification Not Received! 

### ISSUE THREAD

**Issue by naveensrinivas-in** [PrestaShop/PrestaShop#22009]
I have been trying to join the Prestashop community forum to ask my questions but unfortunately, I am unable to receive verification emails at all. I have tried changing multiple emails but no good luck. 

Please help me resolve this. 

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
You need to contact forum@prestashop.com or [contact](https://www.prestashop.com/forums/contact/)

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you.
