### ISSUE TITLE
BO - Order page - An error is displayed when decreasing the gifted product quantity "Could not find the product in cart, meaning Order and Cart are out of sync"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22004]
#### Describe the bug

In the BO > Orders page > Order details page > An error is displayed when decreasing the gifted product quantity "Could not find the product in the cart, meaning Order and Cart are out of sync"

#### Steps to Reproduce

1. Create a cart rule "free gift demo_12" without code
![image](https://user-images.githubusercontent.com/16067358/99645729-dc325080-2a4f-11eb-8a7d-3f3fdaab6922.png)
2. Go to FO
3. Add demo_12 to the cart (free gift well added)
![image](https://user-images.githubusercontent.com/16067358/99645794-f3713e00-2a4f-11eb-92ca-58640acae900.png)
4. Continue checkout
5. Place Order
6. Go to BO > Order page >Last order created
![image](https://user-images.githubusercontent.com/16067358/99645877-0edc4900-2a50-11eb-9cdf-26e844d8afd0.png)
7. Decrease the quantity of the product from 2 to 1 and save
8. See error
![image](https://user-images.githubusercontent.com/16067358/99646036-464af580-2a50-11eb-821c-687d46b90f54.png)
9. Refresh the page: The quantity is updated in the product line, so is the price. But the summary is not updated.
10. Change the status of the order to "Payment accepted": The invoice only has the quantity updated, but not the total prices
11. Go to FO > Customer orders > Order details: The quantity is updated, but not the total prices.

PS:1768 => ok 
https://drive.google.com/file/d/1zokwIsVqnDwie65aI_tUcm8E1_5E15Ct/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build4, 177x
* PHP version: 7.2

**Comment by jolelievre** [comment]
Actually in this case since there is no other product in the order the quantity will be 0, the cart rule can't apply on an empty cart/order I guess that's where the bug comes from

**Comment by Progi1984** [comment]
Fixed by #22013
