### ISSUE TITLE
BO - Order page - Adding a product on empty order : Invoice NOK

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22008]
#### Describe the bug

When I add a product on an empty order (for example, an order with one product, the product is deleted, and a new product is added), the tax block in the generated invoice is NOK : It only contains the Shipping tax and not the Product tax 

#### Expected behavior

Tax block should also contain the product tax.

#### Steps to Reproduce

1. Create order from the FO with only one product
2. Delete the product and refresh : The order is empty, status changed to "canceled"
3. Add a product to the order and refresh
4. Generate the invoice or change status of the order to Payment accepted
5. Download the invoice : The taxes block is NOK : Only the Shipping tax in displayed but not the product tax. Rest of the invoice is OK.

**Screenshots**

![no tax on product](https://user-images.githubusercontent.com/55688534/99655585-30433200-2a5c-11eb-9f69-53cbd063f406.png)

https://drive.google.com/file/d/1jVBtdnBrcsIagBDg6ARgKS1WjzXTnchy/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x, 177RC1Build4
* PHP version: N/A

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/22018/

**Comment by Progi1984** [comment]
Fixed by #22018
