### ISSUE TITLE
Delete all the products shouldn't change the status

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#22010]
#### Describe the bug

When I delete all the products, the status is changed to canceled.

#### Expected behavior

When I delete all the products, the status remains the same.

#### Steps to Reproduce

1. Open an order
2. Delete all the products
3. Status change to canceled

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #21994
