### ISSUE TITLE
When the order status is changed in the webservice, the OrderHistory instance is duplicated

### ISSUE THREAD

**Issue by jordiweblidera** [PrestaShop/PrestaShop#22011]
#### Describe the bug

When the order status is changed by WebService to the same one that is configured, an OrderHistory instance of the same order status is generated again:
![imagen](https://user-images.githubusercontent.com/49748656/99661867-bfecde80-2a64-11eb-92d5-c4eae0983479.png)

#### Expected behavior

Do not duplicate the OrderHistory instance

#### Steps to Reproduce

As the `setCurrentState` method used for the WebService (redirected by `setWsCurrentState`) is the same one that generated this issue: https://github.com/PrestaShop/PrestaShop/issues/15513, I used the same module to reproduce this bug.

1. We installed the module that comments @khouloudbelguith https://github.com/PrestaShop/PrestaShop/issues/15513#issuecomment-534964591
2. We run the webhook: `https://prestashop.local/es/module/fgorderstate/webhook?order_id=23&token=abracadabra&method=task_status_change` changing the order id to the one we want to change the order status
3. The order will have changed status:
![imagen](https://user-images.githubusercontent.com/49748656/99663201-87e69b00-2a66-11eb-919b-c9b0b8a3ec53.png)
4. If we run the webhook again, it has created another instance of OrderHistory:
![imagen](https://user-images.githubusercontent.com/49748656/99663489-fcb9d500-2a66-11eb-9532-6ac39ba27a3e.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @jordiweblidera 

I managed to reproduce your issue with PS1.7.6.9, PS1.7.7.0-rc.1+build.4 but on develop I couldn't reproduced, see the attached screen record below:

https://drive.google.com/file/d/1SADc95lrxwgMeMy3rkzucIp8WshUBTK_/view

I fired the WS three times and yet, it didn't duplicate the order status in order history.
It seems the problem has been fixed on devlop.
Please check and feedback.

Thanks!

**Comment by jordiweblidera** [comment]
> 
> 
> Hello @jordiweblidera
> 
> I managed to reproduce your issue with PS1.7.6.9, PS1.7.7.0-rc.1+build.4 but on develop I couldn't reproduced, see the attached screen record below:
> 
> https://drive.google.com/file/d/1SADc95lrxwgMeMy3rkzucIp8WshUBTK_/view
> 
> I fired the WS three times and yet, it didn't duplicate the order status in order history.
> It seems the problem has been fixed on devlop.
> Please check and feedback.
> 
> Thanks!

I'm sorry. I just saw that the bug was already corrected in `develop`: https://github.com/PrestaShop/PrestaShop/pull/20622. I close the issue and the PR.
