### ISSUE TITLE
emails with placeholder

### ISSUE THREAD

**Issue by morange** [PrestaShop/PrestaShop#22023]
#### Describe the bug
In our shop, orders with empty e-mails or with e-mails with placeholder texts are sent to the customer.

#### Expected behavior
A complete e-mail with the customer name for the respective process (order with details of bank details, cancellation, shipping, contact form, etc.).

#### Steps to Reproduce

1. With several visitors (these were already created in the shop system PS 1.6.1.24) different devices ordered products
2. Design> Email Theme changed the theme several times, selected language, selected theme overwrite & generated emails
3. click on the magnifying glass to test the individual functions
4. Clear PS & browser cache
5. New order created with the existing users
6. E-mails without content for the order or with placeholder texts
7. New order placed with a completely new user
8. Delivery of the order email with the expected information of the order

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
* Start from sratch with 1.7.6.8
* german Shop language
* import our old products and orders from PS 1.6.1.24
* PrestaShop version: 1.7.6.9
* PHP version: PHP 7.2.34
![order](https://user-images.githubusercontent.com/8067083/99776971-efa5f000-2b11-11eb-9f2e-6beb606a74a1.png)

**Comment by florine2623** [comment]
Hi @morange ,
I can't reproduce your issue with the same configuration as yours.

Please check if all your files have been updated correctly. You can see changed or missing files in Advanced Parameters > Informations. Or is your used 1-click upgrade, you can check the log file of the module your_admin > autoupgrade > tmp > log.txt

I'll close your issue as it is not reproducible.
Feel free to check on the [forum](https://www.prestashop.com/forums) and [Slack](http://prestashop.slack.com/) for more info.

**Comment by morange** [comment]
Hello florine2623,
thank you for your replay.

Yes, i'm using an 1-click install. In the logfile i see a lot of entries, but no error line.

Do you have an idea how i can fix it?


Many thx, Steffen

**Comment by morange** [comment]
Hello @florine2623,

i found at the forum an tip for that problem. :) It seems so that mails with capital letter are the problem. 

Do you know that problem and have maybe an fix for that?

Many thx, Steffen
