### ISSUE TITLE
Drop downs not working in CMS plus hidden content

### ISSUE THREAD

**Issue by amydaynes** [PrestaShop/PrestaShop#22021]
**Describe the bug**
Many drop downs on the Add New Product page are unusable. They are already expanded and the options are unclickable. 

**Expected behavior**
I should be able to click the drop-down list to bring up the options and select them. 

**Steps to Reproduce**
Go to New Product, try and select the product type (can't see if this is the correct name, I'm guessing) dropdown to select an option.

**Additional information**
This is a fresh install and my first time using PrestaShop. There is also an issue with content being hidden under the sidebar. 
I've attached a screen recording of what I'm seeing. 
[PrestaShop Issues.zip](https://github.com/PrestaShop/PrestaShop/files/5568531/PrestaShop.Issues.zip)

**Comment by matks** [comment]
Hi if your BO look like this:

<img src="https://user-images.githubusercontent.com/74337334/98890434-b834a500-247a-11eb-89e4-b0996c143d6f.png">

It's probably because you use a php version too high like php7.3 or php7.4 . Latest prestashop version 1.7.6.9 supports php7.2 maximum

**Comment by hibatallahAouadni** [comment]
Hello @Insynco 

Like @matks mention above, the problem is with your PHP version. Please downgrade your PHP version to 7.2.

And please, next time when you open issue, write the additional information (PrestaShop version and PHP version).

Please check and feedback.

Thanks!

**Comment by amydaynes** [comment]
Hi @hibatallahAouadni and @matks 
That has fixed the issue. Thank you so much for your help. 
I will be sure to include this information next time. Apologies.
