### ISSUE TITLE
BO - ORDER / the focus of the button changes when you click quickly

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22026]
#### Describe the bug

In create order after adding a product, if you click quickly, the focus change between the "up" arrow and the "down" arrow

#### Expected behavior

The focus should stay on the selected button

#### Steps to Reproduce

1. Go to BO / order / create order
2. Add a product
3. Try to quickly update the product quantity

**Screenshots**

https://drive.google.com/file/d/1e0fqUhsqojurQ_xbQdUwAY1m54wzT0Tu/view

#### Additional information

* PrestaShop version: 1.7.7.x & develop
* PHP version: N/A

**Comment by SD1982** [comment]
ping 
@hibatallahAouadni

**Comment by marionf** [comment]
@SD1982 Cold you please add the severity ?
Is it a regression compared to 1.7.6.9 ?

**Comment by hibatallahAouadni** [comment]
I will do it @marionf ;-)

**Comment by hibatallahAouadni** [comment]
Hello @SD1982 

I manage to reproduce the issue only with PS1.7.7.0-rc.1 and develop, it means that only occured with the new migrated order page, so it's a regression.

Thanks!

**Comment by SD1982** [comment]
Hi @marionf  yes it's a regression because in 1.7.6.9 the buttons were not laid out the same way it was side by side so the mouse cursor could not hover over the two buttons simultaneously

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
I can't find a way of fixing this, it's a default component of the browser and it looks like we can't change focus on the fly... I don't know what to do on this one :/

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers if someone wants to check it, I can't find a way of doing this without reworking the feature

**Comment by PierreRambaud** [comment]
I'm not able to reproduce the issue :thinking:

**Comment by NeOMakinG** [comment]
Add 2 products on you'r order create page, then up or down the quantity, wait for it to be updated and you'r mouse won't be focusing the arrow you were focusing before @PierreRambaud

**Comment by PierreRambaud** [comment]
> Add 2 products on you'r order create page, then up or down the quantity, wait for it to be updated and you'r mouse won't be focusing the arrow you were focusing before @PierreRambaud

Still not able to reproduce the issue :sweat_smile:

**Comment by NeOMakinG** [comment]
Which browser ? I reproduced it on chrome :/

**Comment by PierreRambaud** [comment]
Chrome on Linux :thinking:

**Comment by NeOMakinG** [comment]
I reproduced it, it just unfocus the arrow button of the integer input

**Comment by MatShir** [comment]
Already fixed https://github.com/PrestaShop/PrestaShop/pull/21977

**Comment by hibatallahAouadni** [comment]
Duplicate of #21734

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

This issue still exists in the 177x branch.
This issue is not a duplicate of https://github.com/PrestaShop/PrestaShop/issues/21734.
https://drive.google.com/file/d/1HmT1CVtvANZUnkNAzQBG50sgW6iFNq3o/view?usp=sharing
In fact, the button increasing is changed to decreasing when we click quickly.
I think we should re-open the issue.
Can you confirm me @SD1982 ?

Thank you!

**Comment by SD1982** [comment]
Hi @khouloudbelguith  yes i confirm the problem is still there :+1:

**Comment by PierreRambaud** [comment]
> Hi @MatShir,
> 
> This issue still exists in the 177x branch.
> This issue is not a duplicate of #21734.
> https://drive.google.com/file/d/1HmT1CVtvANZUnkNAzQBG50sgW6iFNq3o/view?usp=sharing
> In fact, the button increasing is changed to decreasing when we click quickly.
> I think we should re-open the issue.
> Can you confirm me @SD1982 ?
> 
> Thank you!

I see the problem on your screen because you don't move your cursor. When rebuilding the form, the focus is on the decrease button, I manage to reproduce it, but it can't be fixed, it's because of the browser, not the PrestaShop implementation.

We can close it as we can't do anything.
