### ISSUE TITLE
[BUG] SpecificPrice calculated for customer groups instead of default_group_id

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#22036]
#### Describe the bug

I'm not sure if it is a bug or just PS logic, but it is not clear at al.
Calculation of specific price rule uses customer default group, but (in my opinion) should use a list of assigned groups to customer instead.

#### Expected behavior

\SpecificPrice::getSpecificPrice should use id list of user assigned groups instead of $id_group (customer default group id).

#### Steps to Reproduce

1. Create new customer group X, and assigne it to your account, but not as a default
2. Go to AdminSpecificPriceRule and prepare rule for customers in created group X
3. Check if the store has price reductions while logged in to the customer with group X (Front office)
4. There will be no price reductions.

#### Additional information

* PrestaShop version: 1.7.*
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @madkot 

Could you please check if your issue is similar to this one #13705?
Please provide your PrestaShop and PHP version.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @madkot ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
