### ISSUE TITLE
No logo on invoice PDF

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#22030]
#### Describe the bug

Hello, on a fresh install of PrestaShop 1.7.6.5 (local using Docker) the shop logo is not displayed on PDF invoices.

#### Expected behavior

Product images are correctly displayed if I check this option:

<img width="898" alt="Capture d’écran 2020-11-20 à 14 30 44" src="https://user-images.githubusercontent.com/167037/99805531-feee6300-2b3c-11eb-9df1-df73fe056326.png">

But not shop logo 😔

#### Steps to Reproduce

1. Install a fresh PrestaShop 1.7.6.5
2. Go to orders list
3. Choose one and set it status to "payment accepted"
4. Click on "view invoice" button

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1.33

**Comment by florine2623** [comment]
Hi @Daaaaad ,

I can't reproduce your issue on PS 1.7.6.5.
The option you showed is for product images not the logo.
On my case both logo and product images are displayed :
![Capture d’écran 2020-11-20 à 14 47 51](https://user-images.githubusercontent.com/16019289/99807216-77562380-2b3f-11eb-9b61-30a7a8c60424.png)

![Capture d’écran 2020-11-20 à 14 45 36](https://user-images.githubusercontent.com/16019289/99807005-1fb7b800-2b3f-11eb-9d50-ee6e6e5c16ea.png)

You can check if image exists.
You can regenerate thumbnail.
You can clear cache.

Lastly, if none of the above work, you can check the [forum](https://www.prestashop.com/forums/) or the PrestaShop [Slack](https://prestashop.slack.com/).

Thanks!

**Comment by Daaaaad** [comment]
Hi @florine2623,

I know for the option... That's only to show you that product images are displayed but not shop logo 😉

The logo present in your screenshot is not the default PrestaShop 1.7.6.5 logo 🤔 Have you changed it?

Are you testing locally on a mac?
