### ISSUE TITLE
bug prestashop checkout

### ISSUE THREAD

**Issue by sousousm** [PrestaShop/PrestaShop#22031]
#### Describe the bug

Bonjour, impossible d'utiliser prestashop checkout.

#### Expected behavior

Je suis bien connectée à mon compte prestashop checkout mais je n'arrive pas à lier paypal correctement.  Lorsque le compte est lié, ce n'est pas mon e-mail qui apparaît mais un e-mail inconnu!

#### Steps to Reproduce

1. Go to 'prestashop checkout'
2. Click on 'configure'
3. Scroll down to 'compte paypal'
An error during configuration was detected. Please reset the PrestaShop Checkout module and configure it again.

**Screenshots**

**Lorsque j'accède à la configuration de prestashop checkout :**   

![Capture erreur](https://user-images.githubusercontent.com/74777477/99807223-7b824100-2b3f-11eb-9b48-b1441a6dbcb0.PNG)

**Liaison avec mon compte paypal :**    

![Capture paypal](https://user-images.githubusercontent.com/74777477/99807278-93f25b80-2b3f-11eb-9a4a-d5252668644f.PNG)

**lorsque je retourne sur le site après avoir lié paypal j'ai celà :**  

![Capture apres paypal](https://user-images.githubusercontent.com/74777477/99807343-b2f0ed80-2b3f-11eb-9ea0-dd82f5774be2.PNG)

**Ce n'est pas mon e-mail du compte paypal qui est renseigné ici :**  

![Capture paypal2](https://user-images.githubusercontent.com/74777477/99807369-bd12ec00-2b3f-11eb-81a8-8b6c78c632c0.PNG)

#### Additional information

* PrestaShop version: PS 1.7.6.9
* PHP version: 7.1 (j'étais à 7.3 et je suis redescendue à 7.1 pour tenter de résoudre le bug mais pas de changement)

Merci d'avance pour votre aide, j'ai demandé de l'aide sur le forum prestashop mais je n'ai pas eu de réponses concluantes...J'ai parcouru plusieurs forums, sans succès.

**Comment by florine2623** [comment]
Hello,

This platform is for PrestaShop solution bugs only.

If you have an issue with PS Checkout please contact the support of PS Checkout directly through the module !

Thank you, I will close your issue.
