### ISSUE TITLE
can we customise the prestsahop 1.7 stocks dashbaord ?

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#22038]
Prestashop 1.7.6.8

Can we customize  /stocks/ grid by adding more columns?

how can we override src folder

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
As mentioned by @SimonGrn these questions will indeed find a lot better answer in the Slack channel 😉 come to ask it => [here](https://github.com/PrestaShop/open-source/tree/master/slack)
