### ISSUE TITLE
Duplicated information about tracking

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#22035]
#### Describe the bug
There is duplicated information about track number in one screen. It takes only space and it is not necessary to see it twice.

#### Expected behavior
Remove whole section "Click the following link...." also with url "https://www....." for track number. The user shouldn't see directly the url link on the screen. Tracking number is displayed down at right corner and it is sufficient, after clicking tracking number the link works correctly. 

#### Steps to Reproduce
1. Create an order in FO as a registered customer
2. Add tracking number to the order in BO
3. Go to FO and logon as registered customer
4. Go to order history and display details for the order

![image](https://user-images.githubusercontent.com/33311857/99871523-cb164a80-2bdb-11eb-8080-1c6107f4a5ef.png)

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment]
Hello @juraj1000 

What you mentioned above, it's not a bug. That's the normal behavior!
But if you sugguest to improve this behavior, please open a new issue as feature request (like the screenshot below)

![image](https://user-images.githubusercontent.com/23308427/99942623-43ae1000-2d70-11eb-911b-12d5d26f7c6b.png)

Thanks!

**Comment by juraj1000** [comment]
Hello @hibatallahAouadni,
still I think it is a bug. As I wrote, there is duplicated information in one screen/ But there is also visible whole URL link "https://www....." and it is not correct from UI perspective. The URL link should be hidden because it is not readable for the users. Could you check it once again with your colleagues?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team what do you think about @juraj1000 suggestion? Is it a bug or improvement ? 

Like @matks used to said
> it's a PrestaShop limitation

That's I why I said it's an improvement not a bug.

**Comment by LouiseBonnard** [comment]
I agree with @hibatallahAouadni, it's an improvement. It might be a bad UI practice to have this information duplicated in a plaintext link but it is the current expected behavior... So let's turn this issue into an improvement in order to suggest a different behavior!

**Comment by hibatallahAouadni** [comment]
Thanks @LouiseBonnard :) 
@juraj1000 I believe you have to open a new issue as feature request like I mentioned above.
Thanks in advance.
