### ISSUE TITLE
productcomments v4.2.0 -  Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#22044]
#### Describe the bug

I've updated the Product comments to v4.2.0 and when i enter in any prroduct page the function paginateComments(page) show up a console error:

`VM341:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.success (bottom-65b1e2380.js:formatted:17208)
    at u (bottom-65b1e2380.js:formatted:1364)
    at Object.fireWith [as resolveWith] (bottom-65b1e2380.js:formatted:1415)
    at S (bottom-65b1e2380.js:formatted:3603)
    at XMLHttpRequest.<anonymous> (bottom-65b1e2380.js:formatted:3776)`

the code involved is:

`function paginateComments(page) {
        $.get(commentsListUrl, {
            page: page
        }, function(result) {
            const jsonResponse = JSON.parse(result); <--`

Comments not appearing on the product page.

#### Expected behavior

Usually if comments are present in the page they are printed out.

#### Steps to Reproduce

1. Upodate module productcomments to v4.2.0
2. visit aproduct page with comments 
3. Scroll down and erach the comments area: no comments appearing
4. See error in console

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by num47** [comment]
I have faced this types of problem as well. i found a temporary work around for my problem. All i had to change is the "www" from the domain. As in "https://www.yourdomain.com/" to "https://yourdomain.com". See if this works for you. If not then you are probably facing something different than i was.

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

I didn't manage to reproduce your issue with PS1.7.6.7 and ProductComments v4.1.0, see the attached screen record below:

https://drive.google.com/file/d/10w33uGHJZqm7tLk4q_ql3wvgCtXpcyc_/view

As you can see in the screen record above, I upgraded my ProductComments version from 4.1.0 to 4.2.0, and all approved comments are well displayed.
Could you please provide your ProductComments version (the previous one).

Please check and feedback.

Thanks!

**Comment by HartLarsson** [comment]
> Hello @HartLarsson
> 
> I didn't manage to reproduce your issue with PS1.7.6.7 and ProductComments v4.1.0, see the attached screen record below:
> 
> https://drive.google.com/file/d/10w33uGHJZqm7tLk4q_ql3wvgCtXpcyc_/view
> 
> As you can see in the screen record above, I upgraded my ProductComments version from 4.1.0 to 4.2.0, and all approved comments are well displayed.
> Could you please provide your ProductComments version (the previous one).
> 
> Please check and feedback.
> 
> Thanks!

have you checked the console for errors too?

with 4.1.0 no problem at all

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

As you can see in the screenshot bleow, there's no errors in the console and the comments are well displayed.

![image](https://user-images.githubusercontent.com/23308427/99991332-30716380-2db5-11eb-926a-e2f42c429d3c.png)

Please check and feddback.

Thanks!

**Comment by HartLarsson** [comment]
> Hello @HartLarsson
> 
> As you can see in the screenshot bleow, there's no errors in the console and the comments are well displayed.
> 
> ![image](https://user-images.githubusercontent.com/23308427/99991332-30716380-2db5-11eb-926a-e2f42c429d3c.png)
> 
> Please check and feddback.
> 
> Thanks!

thank you for your reply i will check better why i've this problem on my side and let you know :)

**Comment by kpodemski** [comment]
Hello @HartLarsson 

You probably have an override for list-comments.js file in your theme, could you check this?

**Comment by HartLarsson** [comment]
After some test i discovered that probably is a theme problem (warehouse).
I've already open a ticket with the developer that have a theme/module personalization not compatible with the new version, and is why that json error appear probably.

I will keep you informed on the evolution.

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

Do you still encounter this issue?

Thanks!

**Comment by HartLarsson** [comment]
hi @hibatallahAouadni 
i've finally solved the problem was related to a theme module tpl not compatible with the new version of the official module.
I close the thread ;)
Ty for the support
