### ISSUE TITLE
Broken selects in BO after fresh install

### ISSUE THREAD

**Issue by yvan02** [PrestaShop/PrestaShop#22049]
Prestahsop version : 1.7.6.9 
PHP Version : 7.4.12

Hi,

A lot of the BO's select input are broken for me on a fresh install of 1.7.6.9 : there is a a missing space in the tag structure between the tag's name and the id property resulting in broken forms and unability to change settings : 

`<selectid="form_stock_pack_stock_management" name="form[stock][pack_stock_management]" class="custom-select">
    <option value="0" selected="selected">Décrémenter uniquement le pack.</option
    <option value="1">Décrémenter uniquement les produits du pack.</option>
    <option value="2">Décrémenter les deux.</option>
</selectid="form_stock_pack_stock_management">`

Inputs impacted are found in the Shop's config section and Advanced parameters section

Best regards

**Comment by SimonGrn** [comment]
Hello,

Your PHP version is too high. Please follow the [requirements ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)and downgrade to PHP 7.2.
**Please follow the template when you create an issue.**

Thank you, I close this issue.
