### ISSUE TITLE
CHECKOUT ERROR module/ps_wirepayment/validation

### ISSUE THREAD

**Issue by C00SEVEN** [PrestaShop/PrestaShop#22047]
Am getting this error after upgrade, and now am stuck!
in last step on checkout process after i select the payment and proceed this error 500 came up.

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

This is what show up in debug mode:

(1/1) UndefinedFunctionExceptionAttempted to call function "idn_to_ascii" from the global namespace.
--
in Mail.php line 898
at MailCore::toPunycode('c_cesar007@hotmail.com')in Mail.php line 323
at MailCore::send(3, 'bankwire', 'A aguardar tranferência bancária', array('{lastname}' => 'AL', '{firstname}' => 'CA', '{id_order}' => 44, '{order_name}' => 'CPIRGFCEP', '{followup}' => '', '{shipping_number}' => '', '{bankwire_owner}' => 'Machado e Almeida, Lda', '{bankwire_details}' => 'Bai 32940209503950429', '{bankwire_address}' => 'Bai 0593409320r94', '{total_paid}' => 'Kz 18.400,22'), 'c_cesar007@hotmail.com', 'CA AL', 'apoio@mambbus.com', 'mambbus', null, null, '/hermes/bosnacweb05/bosnacweb05bd/b2758/ipg.ticlicks/mambbus1/mails/', false, 1)in OrderHistory.php line 552
at OrderHistoryCore->sendEmail(object(Order), array('{bankwire_owner}' => 'Machado e Almeida, Lda', '{bankwire_details}' => 'Bai 32940209503950429', '{bankwire_address}' => 'Bai 0593409320r94'))in OrderHistory.php line 468
at OrderHistoryCore->addWithemail(true, array('{bankwire_owner}' => 'Machado e Almeida, Lda', '{bankwire_details}' => 'Bai 32940209503950429', '{bankwire_address}' => 'Bai 0593409320r94'))in PaymentModule.php line 557
at PaymentModuleCore->validateOrder(116, '10', 18400.22, 'Pagamento por transferência bancária', null, array('{bankwire_owner}' => 'Machado e Almeida, Lda', '{bankwire_details}' => 'Bai 32940209503950429', '{bankwire_address}' => 'Bai 0593409320r94'), 4, false, '9e8d18af356fec5fbd2a8af96b6d7103')in validation.php line 58
at Ps_WirepaymentValidationModuleFrontController->postProcess()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

help guys please.

**Comment by hibatallahAouadni** [comment]
Hello @Carlos007007cmca 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

**PS:** you need to define what did you upgrade (your shop or the ps_wirepayment module) and the version of the used module.

Thanks!
