### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by thierry-laval** [PrestaShop/PrestaShop#22041]
#### Is your feature request related to a problem?

the customer posts a notice and does not receive a thank you email

When a notice is posted, the store administrator does not receive an email to warn him

#### Describe the solution you'd like

A clear and concise description of what you'd want to happen.

#### Alternatives you've considered

Be able to receive an email that notifies the administrator that a review has been posted by a customer ...

Make sure that an email is also sent to the customer to thank them for their opinion ...

**Comment by hibatallahAouadni** [comment]
Hello @thierry-laval 

We are aware of this issue (feature), it is already in our debug backlog. This issue is a duplicate of #17837. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #17837

**Comment by thierry-laval** [comment]
Thank a lot, have a nice day
