### ISSUE TITLE
Call to undefined method PrestaShop\PrestaShop\Adapter\MailTemplate\MailPreviewVariablesBuilder::trans()

### ISSUE THREAD

**Issue by evahyw** [PrestaShop/PrestaShop#22040]
#### Describe the bug

Hi
I was testing all emails themes and found that all themes worked except for " new-order(ps_emailalerts)", in all 3 themes (classic, modern and my personalised theme) that I installed on my website, it shows a page that says:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

So I tried to solve problem with debug mode, and that says : 

Call to undefined method PrestaShop\PrestaShop\Adapter\MailTemplate\MailPreviewVariablesBuilder::trans()

I saw this page https://github.com/PrestaShop/php-ps-info, and tried to test if this problem comes with the Php version or some value in Php version, but I can't get it work ,because of the window asking for login and password kept coming out, I just couldn't go through this step. ( I tried prestashop & prestashop, leave empty, but can't get overing it at all)

Could you pls help me pls? Thank you in advance

#### Expected behavior

When clicking on "test", one page of the new_order notification mail should show up so that I can send a test email and when I get a new order I can get a notification email for that.

#### Steps to Reproduce

1. Go to ' Apparence - Thèmes d'e-mail'
2. Click on 'my theme'
3. Scroll down to 'new_order  '
4. click on 'http'
5. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/74829698/99882678-95e11b00-2c22-11eb-80e1-90c1994b2e73.png)
![image](https://user-images.githubusercontent.com/74829698/99882745-19027100-2c23-11eb-9ebb-6d63484eb912.png)
![image](https://user-images.githubusercontent.com/74829698/99882766-3e8f7a80-2c23-11eb-82cd-5f474b0f2451.png)
![image](https://user-images.githubusercontent.com/74829698/99882797-5666fe80-2c23-11eb-8212-1d0266f994a3.png)
![image](https://user-images.githubusercontent.com/74829698/99882803-641c8400-2c23-11eb-838a-fb8e7968eda6.png)
![image](https://user-images.githubusercontent.com/74829698/99882811-73033680-2c23-11eb-89c6-757bf22469aa.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34
Version de MySQL : 5.7.30-log
Version du logiciel serveur : Apache
Version de PHP : 7.2.34
Limite de mémoire : -1
Temps maximal d'exécution : 50000
Taille max. pour envoi de fichiers : 64M
@prestonBot

**Comment by matks** [comment]
Hey, thanks for the detailed bug report 😉

**Comment by evahyw** [comment]
> Hey, thanks for the detailed bug report 😉

Thank you for your comment, I hope some one could help me out with this issue. 
Have a nice day

**Comment by hibatallahAouadni** [comment]
Hello @evahyw 

I didn't manage to reproduce your issue with PS1.7.6.8, see the attached screen record below:

https://drive.google.com/file/d/1CGTt1F58lsVXOQUnBpQzbLFZPhoBYK-u/view

> I tried prestashop & prestashop

About PhpPsInfo, that's weird! normaly, all you need to do is **Type in the login and password if prompted (use prestashop for both).** Could you please check your server configuration?

Please check and feedback.

Thanks!

**Comment by evahyw** [comment]
Hi 

> Hello @evahyw
> 
> I didn't manage to reproduce your issue with PS1.7.6.8, see the attached screen record below:
> 
> https://drive.google.com/file/d/1CGTt1F58lsVXOQUnBpQzbLFZPhoBYK-u/view
> 
> > I tried prestashop & prestashop
> 
> About PhpPsInfo, that's weird! normaly, all you need to do is **Type in the login and password if prompted (use prestashop for both).** Could you please check your server configuration?
> 
> Please check and feedback.
> 
> Thanks!

Hi thank you for your reply. 

I created another website and tried the procedure, il worked on that new website. 
Maybe I have touched some code I shouldn't have for my first website? 
Which file could be affected to cause " called an undefined method named "trans" of class" error? 
Is there any possibility that I just reset the new_order theme? maybe by copying all the files that contain codes relative to new_order mail alert?

Thank you in advance.

**Comment by hibatallahAouadni** [comment]
Hello @evahyw ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
