### ISSUE TITLE
Dont is a bug I need info for cookie and dont found it anywere Prestashop-xxxxxxxxx

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#22048]
Hi, I dont found info in anywere and I need to know the reason for this cookie in Prestashop 1.7.7 to acomplish the Cookie Policy of the AEPD Very thanks.

https://cookiepedia.co.uk/cookies/PrestaShop-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (Cookie pro gave that info)

bout this cookie:

This cookie is owned by PrestaShop, an open source e-commerce solution. It helps to provide themes using a web template system.  (I Blocked this cookie and the themes work fine... :s)

The main purpose of this cookie is: Functionality

Any people can tell me for what prestashop uses this cookie?
Very very thanks.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
@TecnoHands As explained on [this page](https://devdocs.prestashop.com/1.7/faq/i-need-help/),

"If you are a developer and you think there is a missing item in the Developer documentation, consider creating an issue on the [Documentation Repository](https://github.com/prestashop/docs). This will help us discuss what to do to improve it."

😉
