### ISSUE TITLE
Does not work with the "www" before domain name. 

### ISSUE THREAD

**Issue by num47** [PrestaShop/PrestaShop#22042]
Hello, 

I have freshly installed Prestashop in a subfolder of my domain. I have use https://www.mydomain.com/prestashop to check about it. But, after installing few modules in the prestashop the Product Comments section stoped showing any comment. But, it was showing the number of the comment/s and the summarized ratings. I could write a review but if i was trying to submit the review then it was showing me "Your review cannot be sent. Sorry, your review cannot be posted." but i could see the submitted review in the back office to review and approve it. Funny thing is when i have changed the domain name in the back office from "https://www.mydomain.com/prestashop" to "https://mydomain.com/prestashop" then it started to work nicely. Hope you fix the issue in your next update. 

Thanks

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
