### ISSUE TITLE
Attributes for combination are incorrectly selected

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#22052]
#### Describe the bug

It turned out that the attributes for the combinations were not loaded correctly, i chose one and in fact the system said that I chose another

#### Steps to Reproduce

1. Create many combinations for products
2. Create specific prices 
https://prnt.sc/vocaap
3. After adding a discount, I saw that I added a discount to another combination
https://prnt.sc/vocaqa 🤯

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @dariusakafest 

This issue has been fixed with PS1.7.6.9, see the attached screen below:

https://drive.google.com/file/d/15_lQoI9XwK69LKKNzTzxnvEZM8tRZm0i/view

I'm closing this issue.

Thanks!
