### ISSUE TITLE
Error displaying discounts in table product discount

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#22058]
Hello,

There is an issue when placing discounts based on purchase quantity. I have attached an image within this post as I think is pretty self explanatory. In my example, the product has 3 discounts: 

Purchase 1 unit = 10% off
Purchase 2 units = 20% off
Purchase 3 units = 30% off

As soon as the customer adds 2  units to the cart, you can see that the discount in the cart does not match the one within the table product discount.

#### Expected behavior

Expected behaviour is that the discount within the cart matches with the ones within the table product discount.

#### Steps to Reproduce

1. Go to edit a product
2. Under the prices tab, add 3 specific prices: 1 with 10% impact for 1 unit, 1 with 20% impact for 2 units, 1 with 30% impact for 3 units.
3. Save changes and try to add 2 or 3 units of the product into a cart in the frontoffice.

**Screenshots**

![Captura de pantalla 2020-11-23 a las 13 42 58](https://user-images.githubusercontent.com/31283004/99973224-73bcd980-2d97-11eb-9bc8-6be2067339ff.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34
* MariaDB version: 10.1.47

**Comment by hibatallahAouadni** [comment]
Hello @demperador 

Could you please check of your problem is similar to #15835
Please check and feedback.

Thanks!

**Comment by demperador** [comment]
Hello @hibatallahAouadni 

Perhaps it is similar but not exactly the same. In our case we do not work with taxes and in the case #15835 I do not know why they set a discount to 0€.

Regards.

**Comment by hibatallahAouadni** [comment]
Hello @demperador 

I beleive it's the same, if we fix these two issues #15866 & #15835 your problem will be resolved.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @demperador ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
