### ISSUE TITLE
DISCOUNT ERROR invalid date_to field

### ISSUE THREAD

**Issue by keosite** [PrestaShop/PrestaShop#22051]
#### Describe the bug

I can't change a period for discounts in Cart Rules and Catalog Price Rules.

#### Expected behavior

Change validity period of discounts.

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts
2. Create or edit a Cart Rule or Catalog Price Rule
3. Change the validity period of the rule by clicking on the date calendar
4. Save
5. See error : "The date_to field is invalid.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.29

**Comment by hibatallahAouadni** [comment]
Hello @keosite 

I didn't manage to reproduce your issue with PS1.7.6.8, see the attached screen record below:

https://drive.google.com/file/d/10VwvA_afKTyJiqzH8YQTxEqRKKzgchKE/view

Please check and feedback.

Thanks!

**Comment by SimonGrn** [comment]
Hello, 

Please think about following the template (I specifically asked you to not do that [here](https://github.com/PrestaShop/PrestaShop/issues/22050#issuecomment-732060623)).
We need at least more information about your exact steps and some screenshots.

**Comment by keosite** [comment]
Hello,

Thank you for your responses.
I'm sorry I don't understand what I'm doing wrong with the template.

Here a screenshot when the error appears
![Capture d’écran 2020-11-25 à 11 50 21](https://user-images.githubusercontent.com/74903139/100218277-d38cbf00-2f14-11eb-934a-4162788aa695.png)

When I change the date of the period the date format changes from
2020-11-25 11:00:00
to 
2020/11/25 11:50

**Comment by SimonGrn** [comment]
Can you please provide a screenshot of the calendar you're using ? As I see here the format is indeed invalid, probably because you didn't use the PrestaShop calendar but a browser calendar, which will then override the format by using your local format.

**Comment by keosite** [comment]
Here is the calendar I use 

![Capture d’écran 2020-11-25 à 13 53 13](https://user-images.githubusercontent.com/74903139/100230309-dc39c100-2f25-11eb-95f6-2b5e0c503bda.png)

Even if I change the date by writing the number, without using the calendar, the format changes.

**Comment by SimonGrn** [comment]
What browser and version do you use ? Do you have any extensions ? What is your OS and what language do you use ?

**Comment by keosite** [comment]
I use :
- Google Chrome v.87.0.4280.67
- I don't have any extension
- OS : maOS Catalina 10.15.7
- Language : french

But it don't work with Firefox, Opera browsers too and with windows 10.

When I add a specific price in a product, it works but the calendar don't look the same as the calendar in discounts page : 
![Capture d’écran 2020-11-25 à 14 29 01](https://user-images.githubusercontent.com/74903139/100233989-bcf16280-2f2a-11eb-9949-7760302a61bb.png)

**Comment by SimonGrn** [comment]
It seems something is interfering with the `date` field and blocking the PrestaShop calendar. What is your Front-Office theme ? Do you use a module that use custom `datepicker` elements and thus could interfere with the official one ?
This is kind of a weird thing, honestly since we're absolutely not able to reproduce it (even when changing browsers and stuff) I'm afraid the issue might lie in your own configuration.

As you may know we cannot offer support here, this is not the place.

I would suggest to ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by keosite** [comment]
All right, thank you for your responses, I'll look into it.

I use avenira theme, I will look for extensions

**Comment by Jaimetonala** [comment]
Hello Keosite
I have read your case and I have exactly the same problem as you. I have been trying for several months to find a solution without success.
Could you solve it?
If so, I would appreciate it if you could tell me how.

Thank you very much for your cooperation

Greetings Jaime
