### ISSUE TITLE
DISCOUNT ERROR invalid date_to field

### ISSUE THREAD

**Issue by keosite** [PrestaShop/PrestaShop#22050]
I can't save a period for discounts in Cart Rules and Catalog Price Rules.

In Backoffice when I change date by clicking on the date calendar and save this error appears : 
"The date_to field is invalid."

It work only if I don't change the valid period of the discount.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.22

**Comment by SimonGrn** [comment]
Hello,

Your PHP version is too high. Please follow the [requirements ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)and downgrade to PHP 7.2.
**Please follow the template when you create an issue.**

Thank you, I close this issue.
