### ISSUE TITLE
When the module is upgraded and the module only has logo.png, an infinite loop error occurs.

### ISSUE THREAD

**Issue by letwang** [PrestaShop/PrestaShop#22067]
## Describe the bug
When the module is upgraded and the module only has logo.png, an infinite loop error occurs.
```
[Tue Nov 24 12:20:16.308356 2020] [php7:warn] [pid 20716] [client 127.0.0.1:61164] PHP Warning:  file_put_contents(/Users/workspace/prestashop/img/tmp/797f21405b2ff29e3e72acbe308b679a.jpg): failed to open stream: No such file or directory in /Users/workspace/prestashop/classes/module/Module.php on line 1596, referer: http://www.ps.com/prestashop/admin/index.php/improve/modules/manage?_token=1fsvrzvWUp-v4DJaMq9-RgtG9P9CJRGqD2DRpDwKXXQ
[Tue Nov 24 12:20:16.308566 2020] [php7:warn] [pid 20716] [client 127.0.0.1:61164] PHP Warning:  copy(/Users/workspace/prestashop/img/tmp/797f21405b2ff29e3e72acbe308b679a.jpg): failed to open stream: No such file or directory in /Users/workspace/prestashop/classes/module/Module.php on line 1597, referer: http://www.ps.com/prestashop/admin652oemvfi/index.php/improve/modules/manage?_token=1fsvrzvWUp-v4DJaMq9-RgtG9P9CJRGqD2DRpDwKXXQ
```
#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.4

**Comment by SimonGrn** [comment]
Hello,

**Please follow the template when reporting an issue**. Please also provide an example of a module with only logo.png.

PrestaShop 1.7.6.8 is only [compatible up to PHP 7.2](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
Please downgrade and try again.

**Comment by hibatallahAouadni** [comment]
Hello @letwang ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
