### ISSUE TITLE
When the module is upgraded, the override folder in the module will not be overwritten to the override under the root directory.

### ISSUE THREAD

**Issue by letwang** [PrestaShop/PrestaShop#22068]
#### Describe the bug

When the module is upgraded, the **override folder in the module** will not be overwritten to the **override under the root directory**.
This led to the invalidation of the override file upgrade, and eventually the module function could not be used normally, and the customer complained.

#### Expected behavior

When the module is upgraded, the **override folder in the module** is automatically updated to **override under the root directory**.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.4

**Comment by SimonGrn** [comment]
Hello,

**Please follow the template when reporting an issue**. Please also provide an example of a module with an override folder.

PrestaShop 1.7.6.8 is only [compatible up to PHP 7.2](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
Please downgrade and try again.

**Comment by hibatallahAouadni** [comment]
Hello @letwang ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
