### ISSUE TITLE
[BO] Moving the default page after the permission profile

### ISSUE THREAD

**Issue by Arman-Hosseini** [PrestaShop/PrestaShop#22065]
#### Describe the issue

Profiles can access pages that are selected in the ACL.
On the employee page, when an employee wants to be created, first profile should be selected, then the default page should be selected according to the profile.

PR is avaliable here #22034

#### Expected behavior

 In fact, the selection of the default page should be after selecting the profile.

#### Steps to Reproduce

Create/Edit employee in the admin BO

**Comment by hibatallahAouadni** [comment]
Hello @Arman-Hosseini ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce (detailed and clear)
- PrestaShop version (source)
- PHP version
- debug mode report
- PHP error logs
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by Arman-Hosseini** [comment]
Hey @hibatallahAouadni,
Sorry for delay.

In fact, it does not logically cause bugs.
This will only improve the user experience.

**Comment by hibatallahAouadni** [comment]
Hello @Arman-Hosseini 

> This will only improve the user experience.

So, could you please change the template of your issue from Bug template to Feature template.

Thanks!

**Comment by marionf** [comment]
As the "default page" drop-down content is updated according to the profile (and its permissions) selected, I think it makes more sense to put the "default page" drop-down under the "permission profile" drop-down
