### ISSUE TITLE
Add "Disable on Desktop" on Modules management

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#22066]
#### Is your feature request related to a problem?

On PS 1.7.x is possible to hide a module only on Mobile devices, while on PS 1.6 was possible to specify also Mobile, Tablet and Desktop

#### Describe the solution you'd like

Should be great to have at last the Disable on Desktop option.

#### Additional context

on 1.6 branch
![image](https://user-images.githubusercontent.com/16102074/100000326-bdbab500-2dc1-11eb-975a-8c4d2bf0e8ed.png)

on 1.7 branch
![image](https://user-images.githubusercontent.com/16102074/100000467-ee025380-2dc1-11eb-9e80-71885b9c2fc4.png)

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by Hlavtox** [comment]
IMHO, I think this is kinda obsolete. Shouldn't everything be responsive these days?

**Comment by HartLarsson** [comment]
> IMHO, I think this is kinda obsolete. Shouldn't everything be responsive these days?

true but for some module that are not need to be used on mobile is better to not load a module with its code then filtering out after with a responsive css/js code.

**Comment by Hlavtox** [comment]
@HartLarsson Do you have an example of such a module? I cannot think of any... 60% of access to ecommerce stores these days are from mobile devices, the user should have the same experience regardless his screen size. 😉

**Comment by HartLarsson** [comment]
> @HartLarsson Do you have an example of such a module? I cannot think of any... 60% of access to ecommerce stores these days are from mobile devices, the user should have the same experience regardless his screen size. 😉

sure like Revolution Slider.
Revolution Slider have also a mobile feature but is very heavy and is better to avoid to use it on mobile.

**Comment by Debreceno** [comment]
Great idea! Waiting

**Comment by Hlavtox** [comment]
Feature removed in v9
