### ISSUE TITLE
BO - Order details - In the info block - The shipping is not refreshed after adding a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22071]
#### Describe the bug

In the BO > Orders > Order detail page > when adding a product to an empty order, the Shipping is not updated in the info block
![image](https://user-images.githubusercontent.com/16067358/100095883-78e35c80-2e5b-11eb-9081-32e481e618ec.png)
When we refresh the page => ok
![image](https://user-images.githubusercontent.com/16067358/100096046-bf38bb80-2e5b-11eb-9b8a-6fb8b11f6f80.png)

#### Steps to Reproduce

1. Create order from the FO with only one product
2. In the Shipping steps " choose a carrier with fees (not free)"
3. Delete the product and refresh: The order is empty
4. Add a product to the order => NOK
![image](https://user-images.githubusercontent.com/16067358/100095883-78e35c80-2e5b-11eb-9081-32e481e618ec.png)
5. Refresh => ok
![image](https://user-images.githubusercontent.com/16067358/100096046-bf38bb80-2e5b-11eb-9b8a-6fb8b11f6f80.png)

ps1.7.6.9 => OK
https://drive.google.com/file/d/1FURxcTRChiD9l5LLCChmaDD1vaha1oPq/view?usp=sharing

#### Additional information

* PrestaShop version: 1770Build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #22171
