### ISSUE TITLE
BO - Logs - Filters / The filter by employee does not work

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22078]
#### Describe the bug

The logs filter by employee has not effect

#### Expected behavior

Every filters should work correctly

#### Steps to Reproduce

1. Go to BO and add 1 or more employee
2. Login to BO with the previously created employee and make enough actions to generate some logs
3. Logout with the employee and login with the admin account
4. Go to Advanced parameters / logs
5. Try to filter logs by employee
6. See error => The logs are not filtered

#### Additional information

* PrestaShop version: 1.7.7.x & develop
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #22099
