### ISSUE TITLE
IQITReviews

### ISSUE THREAD

**Issue by tomduebaeck** [PrestaShop/PrestaShop#22070]
Hi, the Iqitreviews module has a bug, the name on product pages show the code!

I fixed by changing the code in the php file:

From:
 ->setTitle('<span class="iqitreviews-title float-left">'. $this->trans('Reviews', [], 'Modules.Iqitreviews.Iqitreviews') . '</span> <span class="iqitreviews-nb">(' . $assign['snippetData']['reviewsNb'] . ')</span>')

to:
                ->setTitle( $this->trans('Reviews', [], 'Modules.Iqitreviews.Iqitreviews') . ' (' . $assign['snippetData']['reviewsNb'] . ')')

Please change in next update.

thanks

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by SimonGrn** [comment]
You need to contact the module developer directly. This is not the proper place for a third party module.

**Comment by tomduebaeck** [comment]
Thanks. Tried and it is impossible Sendt fra min Galaxy

**Comment by SimonGrn** [comment]
Since this is a module developed by someone from the community, we have absolutely no power here, sorry.

Maybe try to insist ?

Good luck.

**Comment by matks** [comment]
If this is a module you bought on addons.prestashop.com there should be a link on their Marketplace page.

**Comment by tomduebaeck** [comment]
Thanks. Was just trying to help others as i already fixed the problem on my shopSendt fra min Galaxy

**Comment by tomduebaeck** [comment]
Part if warehouse themeBut guys, no worries. I fixed it, was just trying to help others Sendt fra min Galaxy
