### ISSUE TITLE
BO - Order page - The characters limit is wrongly calculated when choosing a predefined message

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22086]
#### Describe the bug

In the BO > Orders > Order details page > Messages block, the characters limit is wrongly calculated when choosing a predefined message

#### Steps to Reproduce

1. Go to BO > Orders > Open any order
2. In the Message block, choose a predefined message
3. See error the characters limit is not decreasing
![image](https://user-images.githubusercontent.com/16067358/100200026-56eee600-2efe-11eb-93b4-cbb3f1953406.png)

In the PS1768 => it is not displayed when choosing the message
![image](https://user-images.githubusercontent.com/16067358/100200264-a3d2bc80-2efe-11eb-979c-249f06422c0d.png)

#### Additional information

* PrestaShop version: 1770stableBuild1
* PHP version: 7.2

**Comment by Progi1984** [comment]
@khouloudbelguith I just tested with a fresh install. And with the initial message, and a predefined message, the counter is ok :

![image](https://user-images.githubusercontent.com/1533248/100744197-b86ef300-33dd-11eb-9347-5d3132915515.png)

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

This issue occurs only when choosing the order message predefined without editing it.
I attached a screen record
https://drive.google.com/file/d/13ZG9DQ0qQST0oVqpe8wCgQMsHFM46CCK/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith and the fix is done :heavy_check_mark:

**Comment by Progi1984** [comment]
Fixed by #22189
