### ISSUE TITLE
Product quantity badge logic is different on migrated order page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22080]
# Describe the bug

The quantity badge is not following the same logic in 1.7.7.0: I have 2 products with 2 items, in 1.7.6.x it only shows the badge for the first product, in 1.7.7.0 it shows for both products.

#### 1.7.6
![176](https://user-images.githubusercontent.com/6097524/100127473-6ed35500-2e7f-11eb-9aa1-4448b627c2c3.JPG)
#### 1.7.7
![177](https://user-images.githubusercontent.com/6097524/100127488-71ce4580-2e7f-11eb-860e-cda8d9680002.JPG)
#### Product stock before ordering
Brown bear notebook - 2
Hummingbird notebook - 1
Customizable mug - 0

#### Additional information
* PrestaShop version: 1.7.7.0 RC1
* PHP version: 7.2

**Comment by SimonGrn** [comment]
Hello,

I'm not sure I understand the issue here. The page was migrated, and the design slightly changed, but the data seems to be correct ?
Is there a problem with the new badge ?

Thank you.

**Comment by Hlavtox** [comment]
@SimonGrn No, but what is the logic of the badge, if it behaves differently on both versions?

**Comment by SimonGrn** [comment]
It's showing 2 in both versions, right ?
Are you saying that the interface should never evolve, never change ?

I'm genuinely curious as to why this is a deal big enough to deserve an issue. This is a real question.

**Comment by SimonGrn** [comment]
Oh so you mean that the badge now shows in both lines (in 1.7.7.0) instead of the first one only (in 1.7.6.9) ? It wasn't clear, could you please elaborate by editing your issue ?

Thank you.

**Comment by Hlavtox** [comment]
@SimonGrn Edited. I was testing some logic between versions and stumbled upon it. Just curious of the logic behind it, nothing more.

PS: I have email notifications enabled for comments. :-)

**Comment by SimonGrn** [comment]
The thing is I didn't understand what you were talking about because it's not written anywhere in your issue. Nowhere you mention the problem is that the badge is not showing for both the lines like before so I was just comparing screenshots and wondering wth was I missing 😅 
That's why I asked you to edit the body to make it more clear, but I'll do it directly.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

As @SimonGrn mentioned above, we need to know if this is the normal behavior or it's a bug.
Ping @PrestaShop/product-team could you please explain to us, is this the new wanted behavior or it's a bug (regression)?

Thanks!

**Comment by MatShir** [comment]
Hi @Hlavtox,
We receive a lot of feedback from our merchants on order preparations. Indeed, their carts of different products are in most cases products with only one quantity. And a single highlighted line was confusing, so for any product with a quantity greater than or equal to 2, PrestaShop highlights them. We hope that with the new design and color, merchants will be helped in their daily life.

**Comment by Hlavtox** [comment]
@MatShir OK, so it works as it should now ;-) Closing @hibatallahAouadni
