### ISSUE TITLE
Orders are not syncing with Ebay

### ISSUE THREAD

**Issue by Tattiii** [PrestaShop/PrestaShop#22088]
Orders on Ebay are stopped syncing with Prestashop. Catalogue syncs with no problem.
There was a notification, that authentication token has expired. 
New token has been generated, but problem with syncing is still there.

What else needs to be done?
Thanks

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by SimonGrn** [comment]
Hello,

you need to contact the module developer directly.
Please also **follow the template**, if you delete everything we will have no choice but to close your issue.
