### ISSUE TITLE
Problem with enabling CacheMemcached, the cache does not clear

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#22094]
Dear staff,
we asked to the server support to enable cache memcached, but when we try to clear the cache, the site didn't response as we guess.
I'd like to ask you if this cache is compatible and how can we clear manually from PresaShop if is possibile.
We didn't receive any error message from debug.
Does the memcached cache empty normally?
like the smarty one?
Thanks a lot.
Balla

How to enable the cache memcached:
1) Click on Advanced Parameters
2) Click on Performance
3) Scroll down to Caching
4) Enable CacheMemcached
5) Add the IP and the port address from server
6) Change something on the site
7) Repeat step from 1 to 2
8) Empty the cache using the empty cache button

![memcached](https://user-images.githubusercontent.com/28685316/100214491-3fb8f400-2f10-11eb-8ff2-ce7f02515492.jpg)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 
Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by ballashop** [comment]
Dear @hibatallahAouadni 
ok, I do some more detailed local server tests to possibly replicate the problem, thanks a lot.
Balla

**Comment by ballashop** [comment]
Dear @hibatallahAouadni 
in those links I found the same problem: 
https://www.prestashop.com/forums/topic/542108-prestashop-bugs-with-memcached/
https://www.prestashop.com/forums/topic/1022242-problem-with-prestashop-and-memcached
Balla
