### ISSUE TITLE
In Shop Parameters > Search > Tag, Edit list of product KO

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22092]
#### Describe the bug

When editing the list of product linked to a tag in BO > Shop Parameters > Search > Tag, and removing only one product, all linked product are removed.

#### Expected behavior

Only the selected product should be removed from the tag.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Search > Tag
2. Add a tag with several product linked to the tag
3. Edit the tag, remove only one product from the ones linked to the tag, and save
4. See on tag list : The tag is now linked to 0 product
5. Open the tag again : There is no product selected.

**Screenshots**

https://drive.google.com/file/d/1Flz6C4U6e7bltlTH9EBAZ5ASkLybSm-o/view?usp=sharing

#### Additional information

* PrestaShop version: presta1770stable1
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #22101
