### ISSUE TITLE
Multicurrencies - BO - Order page - Incorrect Product's total when it is in a category discount for the customer Group

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22096]
#### Describe the bug

This issue occurs only with a different currency than the default one.
A customer Group has a discount category for example 50% for the Art category
![image](https://user-images.githubusercontent.com/16067358/100217285-95db6680-2f13-11eb-9d5b-924206987557.png)
In the BO > Orders > Order page > when we Update a product(which is in the category discount) => the product's price is NOK.
If we generate the invoice => total incorrect

#### Steps to Reproduce

1. Go to BO > International > Localization page
2. Import the United States pack
3. Go to the currencies page
4. Edit the $ currency with exchange = 10 (only to visualize the issue)
5. Go shop Parameters > Customer Settings > Groups Tab
6. Edit the customer Group, Add a discount 50% for the Art category
![image](https://user-images.githubusercontent.com/16067358/100223190-6f212e00-2f1b-11eb-909f-15f382806ea7.png)
7. Go to FO > Art category > Select `$` currency > Add the product `demo_18`to the cart
8. Continue checkout
9. Go to BO > Orders > Open last Order created
![image](https://user-images.githubusercontent.com/16067358/100223425-c4f5d600-2f1b-11eb-9980-d493d6e027c4.png)
10. EDit the quantity of the product ordered ( from 1 to 2 form example)
11. Save
12. See error => the product's total is NOK
![image](https://user-images.githubusercontent.com/16067358/100223533-ea82df80-2f1b-11eb-9ae7-12acabab18cf.png)
13. Change the status of the Order to Payment accepted
14. Download the invoice
15. See the error
![image](https://user-images.githubusercontent.com/16067358/100223794-42214b00-2f1c-11eb-8bf4-04995c56b57a.png)

1770finalbuild => NOK: https://drive.google.com/file/d/1IYCHdcMkUTZ_G_1K7QsWMywcziDSSc-x/view?usp=sharing

PS:1769 => ok: https://drive.google.com/file/d/1dojva4t7oLJDFw1ZLxiV7RbfzmRCIZUy/view?usp=sharing

#### Additional information

* PrestaShop version: 1770finalbuild1
* PHP version: 7.2

**Comment by jolelievre** [comment]
@sowbiba I'm not sure but I believe this should also be fixed by this PR https://github.com/PrestaShop/PrestaShop/pull/22299

Since the product prices no longer change dynamically once the cart is ordered, changing the product quantity will only rely on the product price when ordered and multiply it by the appropriate amount It is also a bit related to this issue https://github.com/PrestaShop/PrestaShop/issues/22192

**Comment by marionf** [comment]
@khouloudbelguith Could you please verify if this issue is fixed by #22299 ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, it is ok :heavy_check_mark: 
https://drive.google.com/file/d/11RBsVF9PrsHO2H04Wjfs1XxWRoS5CMHB/view?usp=sharing

Thanks!
