### ISSUE TITLE
Wrong amount paid

### ISSUE THREAD

**Issue by squinquis** [PrestaShop/PrestaShop#22104]
#### Describe the bug

All is in the title, I have 2 orders that are overpriced. The orders were in "payment error" even though we received the payment.
Example : The total is 56.90 € and the customer paid 57.90 €. Taxes are correctly configured it seems to me.

#### Expected behavior

Pay the right price.

#### Steps to Reproduce

No idea unfortunately. I have 2 orders with this error (not the same customer) a few days apart and since everything is fine.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

[screencapture-lessaveursdenoemie-fr-admin151vzbbiq-index-php-2020-11-25-16_20_42.pdf](https://github.com/PrestaShop/PrestaShop/files/5597617/screencapture-lessaveursdenoemie-fr-admin151vzbbiq-index-php-2020-11-25-16_20_42.pdf)
[screencapture-lessaveursdenoemie-fr-admin151vzbbiq-index-php-2020-11-25-16_23_20.pdf](https://github.com/PrestaShop/PrestaShop/files/5597619/screencapture-lessaveursdenoemie-fr-admin151vzbbiq-index-php-2020-11-25-16_23_20.pdf)

#### Additional information

* PrestaShop version: 1.6.1.11
* PHP version: 5.6

**Comment by hibatallahAouadni** [comment]
Hello @squinquis ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
