### ISSUE TITLE
BO > Create Order : No limitation on quantity when out of stock

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22109]
#### Describe the bug

In BO > Orders > Add new order : For a product with a "Deny out of stock order" behavior, it is possible to add more product than available (only by editing quantity). The total are however OK : Only the available quantity is counted for Total, Discount, Shipping...

There is also an error message displayed.

Once the order is created, only the available quantity is in the order, so it's only a trivial bug.

In 176x, it was not possible to add more than the available quantity.

#### Expected behavior

Label in stock is displayed in the product list.

If the product quantity selected by the user is higher than the stock available and the stock behavior when out of stock is deny orders 
Then
Keep the stock selected by the user in the input and the error message but the button create order is disabled. 

(Not ISO)
#### Steps to Reproduce

1. Have a Product A with quantity = 2, and "Deny out of stock order"
2. Go to BO > Create Order > Add new order, choose a customer
3. Add product A, try to add more than available quantity : It is not possible.
4. Once Product A is added, try to edit quantity over the available quantity : It is possible (but a warning is displayed and the totals are not updated)

**Screenshots**

Screenrecord : 
https://drive.google.com/file/d/1WMHUAq1EkjMSZ2XW2T8ICU78Y-WvTwO1/view?usp=sharing

![screencapture-localhost-prestabeta17702-admin9418pfie6-index-php-sell-orders-orders-new-2020-11-25-16_31_21](https://user-images.githubusercontent.com/55688534/100250568-17e08500-2f3e-11eb-9a6d-052e3e6e4faf.png)

#### Additional information

* PrestaShop version: presta1770stable1
* PHP version: N/A

**Comment by MatShir** [comment]
Be careful, logic verification of stock is not the same with pack, simple product and combination.

**Comment by Progi1984** [comment]
Fixed by #22920
