### ISSUE TITLE
BO - Order page - Details modal for carts - the Refresh button is not working

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22105]
#### Describe the bug

In the BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > the refresh button doesn't work.
![image](https://user-images.githubusercontent.com/16067358/100247474-ae12ac00-2f3a-11eb-8d0c-cb7dc1035dcf.png)

PS 1768 => the refresh button doesn't exist
![image](https://user-images.githubusercontent.com/16067358/100248007-4577ff00-2f3b-11eb-86b0-9efb4b3ec823.png)

#### Steps to Reproduce

1. Go to FO > Sign in with a customer for example "John Doe", add a product to the cart
2. Don't close the tab window
3. Go to BO > Orders > Add new Order > Search the customer "John Doe" > Choose it
4. Click on the details for the last Cart (the modal is opened)
5. Go back to the FO > Add another product to the cart or just update the quantity
6. In the BO > Orders > Add new Order > Cart details modal > Click on Refresh 
7. See error > Nothing happens

PS: if you close the Modal and open it again => OK

**Screenshots**

https://drive.google.com/file/d/1iwjYEFv70elQ4V_qZu-9guwkKP_CjH_w/view?usp=sharing

#### Additional information

* PrestaShop version: 1770stablebuild1.
* PHP version: 7.2

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
@sowbiba what's left ? I don't remember if we're blocked or no

**Comment by sowbiba** [comment]
I take it ;)
