### ISSUE TITLE
Amount at BO/Orders is the double of the total_spent order

### ISSUE THREAD

**Issue by salvacal** [PrestaShop/PrestaShop#22115]
I found an issue at BO/Orders/ViewOrder/View Full Details
In this page I found that customer Orders and total spent is exactly the double of the order or real payment received. The issue is that the total value of the order does not correspond to the total spent payment, it is always double. This would means that the total_spent variable is read twice. This only happens with PayPal and Cash on delivery, with other types of payment seems does not happen, the total is right!
I didn’t find any error at log and, fortunately, the payment in PayPal directly is correct.
The problem for us is only administrative, we cannot sell the product for € 1, collect € 1 but record € 2.
You find attached two screenshots about the issue.
I thought that the issue was from Paypal module and I asked to their developers and this is their reply:
Hi! Our developer checked your issue and it seems not to be connected with our module. 
He thinks that there is a problem with your environment. I advise you to contact PS dev.
Regards,
Daria – 202 ecommerce

Then I asked to Panda theme dev. and this is their reply:
HI, It seems the problem was due to Prestashop, as my theme doesn’t change any Prestashop checkout process.

As you see, everyone says it’s not their fault but the problem remains for me !!!
I cloned the site and used the default theme, also I upgraded the to PS v1.6.9 but the issue remains.
It started with an upgrade to 1.6.8. Could this issue come from a problem in BO / Order Setting / status?
Why this issue change the total value of the order and does not correspond to the total spent payment? It is always double!

Has anyone had the same problem and how is it resolved?
Thank you. Regards.
<img width="1087" alt="Schermata 2020-11-25 alle 19 53 41" src="https://user-images.githubusercontent.com/52864388/100270417-5a16c000-2f58-11eb-896c-9cac547311da.png">

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
