### ISSUE TITLE
Multistore - BO - Order page - An unexpected error occurred when adding a product with customization

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22110]
#### Describe the bug

When multishop is enabled, a new shop is created => Customized products are imported in the second shop but without customization as reported [here](https://github.com/PrestaShop/PrestaShop/issues/18919)
This issue will occur a problem in the Add new Order page
![image](https://user-images.githubusercontent.com/16067358/100257057-c9cf7f80-2f45-11eb-918e-6643c12b5f96.png)

#### Steps to Reproduce

1. Enable Multishop context 
2. Create a new shop with importing all data
3. `Shop2` is selected Go to BO > Orders > Add new order page 
4. Choose a customer
5. Search for the product `demo_14` "Customizable mug"
6. Click Add
7. See error
![image](https://user-images.githubusercontent.com/16067358/100257057-c9cf7f80-2f45-11eb-918e-6643c12b5f96.png)

PS1768
![image](https://user-images.githubusercontent.com/16067358/100257572-57ab6a80-2f46-11eb-8498-e6e2b358ba31.png)

#### Additional information

* PrestaShop version: 1770stablebuild1
* PHP version: 7.2

**Comment by Progi1984** [comment]
@Julievrz What is the wording for the error which must be displayed when when the customization of a product is not found

**Comment by Julievrz** [comment]
@Progi1984 I found this string : "The product customization picture could not be found." in Admin.Notification.Error

If you are not talking about the picture, then we would need to create a new string such as : 

"The product customization could not be found." in Admin.Notification.Error

Do we know why such an error is displayed? Maybe it could be good to explain the error to the user.

**Comment by Progi1984** [comment]
@Julievrz It's not about the product customization picture, it's about the product customization.

> When multishop is enabled, a new shop is created => Customized products are imported in the second shop but without customization as reported [here](https://github.com/PrestaShop/PrestaShop/issues/18919)
This issue will occur a problem in the Add new Order page
![image](https://user-images.githubusercontent.com/16067358/100257057-c9cf7f80-2f45-11eb-918e-6643c12b5f96.png)

**Comment by Julievrz** [comment]
@Progi1984 

Here you are: "Product customization could not be found. Go to Catalog > Products to customize the product." in Admin.Catalog.Notification

**Comment by Progi1984** [comment]
Fixed by #22175
