### ISSUE TITLE
Amount at BO/Orders is the double of the total_spent order

### ISSUE THREAD

**Issue by salvacal** [PrestaShop/PrestaShop#22118]
**Describe the bug**

I found an issue or a bug at BO/Orders/ViewOrder/View Full Details from v1.7.6.8
In this page I found that customer Orders and total spent is exactly the double of the order or real payment received. The issue is that the total value of the order does not correspond to the total spent payment, it is always double. This would means that the total_spent variable is read twice. This only happens with PayPal, with other types of payment seems does not happen, the total is right!
I didn’t find any error at log and, fortunately, the payment in PayPal directly is correct.
It's not right sell the product for € 1, collect € 1 but record € 2.
I thought that the issue was from Paypal module and I asked to their developers and this is their reply:
Hi! Our developer checked your issue and it seems not to be connected with our module.
I advise you to contact PS developers.
Regards,
Daria – 202 ecommerce

Then I asked to Panda theme dev. and this is their reply:
HI, It seems the problem was due to Prestashop, as my theme doesn’t change any Prestashop checkout process.

I cloned the site and used the default PS theme, also I upgraded the to PS v1.6.9 but the issue remains.

**Expected behavior**

The correct behavior is that the total spent at Orders must be the total of Total of the Carts
<img width="856" alt="Schermata 2020-11-25 alle 20 59 16" src="https://user-images.githubusercontent.com/52864388/100276779-5ee07180-2f62-11eb-8ddd-b60cd4f652ae.png">

**Steps to Reproduce**

Unfortunately the issue occurs only when customers pay with PayPal.

**Screenshots**

<img width="1083" alt="Schermata 2020-11-25 alle 20 57 06" src="https://user-images.githubusercontent.com/52864388/100276736-4d976500-2f62-11eb-9fd6-6ebb8f0810f2.png">
<img width="884" alt="Schermata 2020-11-25 alle 21 05 06" src="https://user-images.githubusercontent.com/52864388/100276753-55efa000-2f62-11eb-980a-dd5fea1d8fc2.png">

**Additional information**

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @salvacal 

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on [Addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748)

We will close this issue.

Thanks!
