### ISSUE TITLE
BO - Order page - The shipping block is not instantly updated when updating the Address

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22124]
#### Describe the bug

In the BO > Orders > Add new Order page, The shipping block is not instantly updated when updating the Address.

#### Steps to Reproduce

0. Install PS with English language & France country (The United States country is not displayed by default)
1. Go to BO => Orders => Add new order page for "John Doe", choose him.
2. Select the address "My address (United states country)"
3. add some product to the order
![image](https://user-images.githubusercontent.com/16067358/100337014-29c23680-2fd7-11eb-8fc5-b4bd427f50c5.png)
4. Try to Edit the Address with France country
5. Save
6. See error
7. The Shipping block is not updated
![image](https://user-images.githubusercontent.com/16067358/100336961-14e5a300-2fd7-11eb-8586-03b9ccd0b8aa.png)
PS: if you change the selected address => it will be ok
![image](https://user-images.githubusercontent.com/16067358/100337138-50806d00-2fd7-11eb-9312-1c72381529de.png)

**Screenshots**

PS1769 => ok https://drive.google.com/file/d/1S4zkzTfZGj456oINqQWjvDu6KjCpoIv1/view?usp=sharing
PS1770stablebuild1 => NOK: https://drive.google.com/file/d/1W4wk-gIL-BOirm3YrrvbWAqLlxIMRIG5/view?usp=sharing

#### Additional information

* PrestaShop version: 1770stablebuild1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #21568
