### ISSUE TITLE
BO - Modules - Modules catalog / The recommended modules list is not complete after a addons marketplace login

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22125]
#### Describe the bug

If we login to the addons marketplace the list of recommended modules only contains a few items

#### Expected behavior

The recommended modules list should be complete

#### Steps to Reproduce

1. Go to BO / Modules / Modules catalog
2. Check the number of recommended modules ( ~ 150 )
3. Login in the addons marketplace
4. Check the number of recommended modules ( ~ 6 )
5. Logout of the addons marketplace
4. See error => still only 6 recommended module

PS => We need to clear the prestashop cache and it's ok the recommended modules list is complete again

**Screenshots**

https://drive.google.com/file/d/1OLBzTtZnPhKWg4j3p2iCaj9o74AYNuAi/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x && develop
* PHP version: 7.1

**Comment by SD1982** [comment]
Ping @hibatallahAouadni :+1:

**Comment by hibatallahAouadni** [comment]
@SD1982 it seems the PR is merged, so shall we close the issue?

**Comment by SD1982** [comment]
Hi @hibatallahAouadni sorry i just see your comment .
Yes if the PR is merged this issue can be closed.
Thanks !!
