### ISSUE TITLE
Log of Contact Form / Contact Form IP Saving

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#22127]
Thanks to the arbitrariness of SimonGrn I am supposed to do his work and reopen a ticket, that was already open before. https://github.com/PrestaShop/PrestaShop/issues/22111

I will open this ticket again and again if he continues to claim it is about Captcha Systems when it clearly was just ONE PROPOSED SOLUTION!

Here you go:

Hello,
#### Is your feature request related to a problem?

I receive Spam by the Contact Form in the Webshop. Sadly, all Captcha Addons do charge money and this feature is not integrated.
If you like to add some Captcha System that would be great.
In the meantime, I just wanted to check the logs of the PS for the IP for the Spamer. PS does not save this level of log, and you can not set it to do so.
The contact form itself does not log the IP of an inquery too, so that was no help either.

##### Describe the solution you'd like

       - Integrate some Open Source Captcha System
       - Extend the Log Feature for logging contact form events
       - Rework the Contact Form to save more Meta Data, maybe user selectable to comply with GDPR laws.

Used PS 1.7.6.9

Thanks

**Comment by SimonGrn** [comment]
Hello,

please think about our Code of Conduct.
We do not accept tickets written with such a tone of voice.

I'm closing this ticket, please open a new one, following the template and not harassing people fixing the software you're using for free.

Thank you.
