### ISSUE TITLE
Multicurrencies - BO - Order page - when we add a product to an old order -  price is changed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22138]
#### Describe the bug

In the BO > Order detail page, when adding a product to an old order, an incorrect value is displayed and an incorrect amount calculated.

#### Steps to Reproduce

1. Go to BO > International > Upload United states pack
2. Change the currency "US Dollar" Exchange rate = 10, Decimals =2
3. Go to FO > Create a new order with currency $ selected(for example add demo_11 to the cart (142.8$) > continue checkout)
4. Go to the BO => Orders > last order created
5. Update the price of the product to 71.4 $
6. Change the currency to the euro (in the block Payment)
7. Add a product (demo_12) to the order
 => **see error the price is changed of the first product**
8. change the status of the order to payment accepted
9. Download the invoice
10. See errror

PS1.7.7.0stablebuild2 => nok: https://drive.google.com/file/d/1qFfDLOVMD_g1cI_x_jTiff1BQfg_TSx-/view?usp=sharing
PS1769 => ok: https://drive.google.com/file/d/1QWT9utsp61PBGJ-nApbe_x3tGknOprAe/view?usp=sharing

#### Additional information

* PrestaShop version: 1770stablebuild2
* PHP version: 7.2

**Comment by Progi1984** [comment]
@jolelievre Is it me or your PR with OrderDetail will fix this issue ? Linked to this Issue https://github.com/PrestaShop/PrestaShop/issues/22263
