### ISSUE TITLE
BO / Error displayed when connecting to addons with false credentials but connected anyway

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22133]
#### Describe the bug

If you tried to connect to addons with wrong credentials an error is displayed by cons addons is still "connected" to the wrong account

#### Expected behavior

We should not be considered connected if the credentials are wrong

#### Steps to Reproduce

1. Go to BO / dashbord
2. Click on "connect to prestashop market place"
3. try to connect with this credentials => demo@prestashop.com / azertyuiop
4. Click on "let's go" => an error message is displayed
5. Go to Modules / Modules catalog
4. See error => We are connected with the demo@prestashop.com account

**Screenshots**

https://drive.google.com/file/d/1BZBH7m-P__ya3vCmGo19yzrA6AABDPJZ/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x && develop
* PHP version: 7.1

**Comment by SD1982** [comment]
Ping @hibatallahAouadni

**Comment by PierreRambaud** [comment]
Isn't a duplicate of #9721 ?

**Comment by SD1982** [comment]
@PierreRambaud yes indeed it's a duplicate :+1: 
I close this one !

**Comment by SD1982** [comment]
Duplicate of #9721
