### ISSUE TITLE
Paypal error to set the order status in "refunded" when the order is already refunded from Paypal's panel

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#22134]
Hi
I alert you about a a problem on the paypal module.
the problem happens when the refunded is made on paypal'panel and not from prestashop

1)
refunded an order on Paypal's panel (many shops prefer to do it on Paypal to avoid possible errors)

2)
go to prestashop to the order page and change the order status to "refunded" or "canceled", you will get an error

and it is not possible to change the order status

can you fix this problem? they should change the order status even if the order has already been refunded on paypal

bye

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/100379562-64e35a80-3015-11eb-90c1-fcaf2bf095e1.png)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2
* Paypal version: v5.2.1

**Comment by florine2623** [comment]
Hi @maofree ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, please contact directly the developer of the module.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
