### ISSUE TITLE
ps_facetedsearch regex does not properly handle spaces on Weight

### ISSUE THREAD

**Issue by neonVoice** [PrestaShop/PrestaShop#22135]
#### Describe the bug

Regex `/([^\d]*)(?:[\d .,]+)([^\d]+)(?:[\d .,]+)(.*)/` in file `\modules\ps_facetedsearch\_dev\front\slider.js` on line 29 uses character `' '` instead of `'\s'` for space, which leads to incorrect group matching behavior in situations where you use space-separated product properties like weight/price, for example: `1 234` (Notice space between 1 and 2). I dont know exactly why, because i'm not a JS-geek or smth, i was just doing my site and wasted good 8 hours diggin into code trying to understand why after enabling filter in my website i see some extra numbers for weight/price filter label. Suddenly i have no time currently to make a proper pull request, because i am only focusing on making theme for my website currently.

Consider this:
```
min = 180,
max = 24568
unit = "g"
```

This is displayed as `180g - 24568 568g`.
Also, moving slider changes value 24568 instantly, and when finaly mousehold is over, last value also updated, but i believe it had nothing to do with the initial bug and it is just a consequence.

#### Expected behavior

I expected to see range slider with this filter label:
`180g - 24 568g`

#### Steps to Reproduce

1. Set weight property for 1-2 products
2. Enable weight range filter in `Facetedsearch module` for main catalogue page
3. Go to main catalogue page and try to use filter.

**Screenshots**

Before changing regex pattern:
![before](https://user-images.githubusercontent.com/21147332/100386613-e992a080-3036-11eb-85f4-b21ecc275323.gif)

After changing regex pattern to `/([^\d]*)(?:[\d\s.,]*)([^\d]*)(?:[\d\s.,]*)([^\d].*)/` directly inside `modules\ps_facetedsearch\views\dist\front.js`
![after](https://user-images.githubusercontent.com/21147332/100386622-f3b49f00-3036-11eb-8c1f-a48ef905c07f.gif)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.19-Win32-VC15-x64 (using Laragon environment on windows)

**Comment by matks** [comment]
I have to say that is one of the most complete bug reports I have ever seen 👏

**Comment by florine2623** [comment]
Hi @neonVoice ,
Thanks for the report.

I manage to reproduce this using PS 1.7.6.8 and faceted_search module v3.5.0 and v3.6.0.
![Capture d’écran 2020-11-27 à 10 02 09](https://user-images.githubusercontent.com/16019289/100431166-11662080-3098-11eb-8228-02161f8d3d71.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!
