### ISSUE TITLE
BO - Can't create category on product page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22144]
#### Describe the bug

In the BO > Catalog > Products page > Create a new Product, when we try to create a new category, we have an exception in the console.
![image](https://user-images.githubusercontent.com/16067358/100468091-04ffb900-30d4-11eb-8a08-d041e1d1b7a5.png)

#### Expected behavior

In the 177x => OK

#### Steps to Reproduce

1. Go to BO > Catalog > Product page
2. Add a new product
3. Scroll down to create a new category

#### Additional information

* PrestaShop version: develop (1780)
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Related to this: https://github.com/PrestaShop/PrestaShop/issues/9752 (this a multilanguage issue)

**Comment by hibatallahAouadni** [comment]
Related to #9752

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25082
