### ISSUE TITLE
Customers can't checkout, causing abandoned baskets

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22155]
#### Describe the bug

Very high severity bug causing revenue loss..

Adding an address in the second part of the checkout form, removes the address and asks the customer to add it again. The address does actually seem to be saved in the database, but not showing for customers.

#### Expected behavior

I expect the address to be saved and step 3 of the checkout to open.

#### Steps to Reproduce

NOTE: happens 80% of the time for me, on firefox & chrome 

1. Go to https://pureelegance.co.uk
2. add an item to the basket
3. go to cart
4. checkout
5. add first, lastname and email
6. navigate to next step
7. add the required fields of the address
8. click continue
9. the page will refresh and the address is gone, prompting you to add it again

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version 7.3

**Comment by hibatallahAouadni** [comment]
Hello @marcydude 

I didn't manage to reproduce your issue with PS1.7.6.9, PS1.7.7.0-rc.1 and develop, see the attached screen record below:

https://drive.google.com/file/d/16DUKIJsYYOn0Osb0VIaV0mwm2NIVzKyl/view

PS: I didn't even managed to reproduce it on your website, see attached screen record below:
https://drive.google.com/file/d/17uln48OV548sqENUo8QWh7vw3AWp3XFc/view

Please check and feedback.
And could you please provide your PHP version in **Additional information** block.

Thanks!

**Comment by ghost** [comment]
https://drive.google.com/file/d/1CQPJoH5TWNkeZhIfePJyGBogCGd13tis/view?usp=sharing

Hi, thanks for testing. I've reproduce and taken a screenrecording (link above)

the php version of the server is 7.3

something is really funky with the checkout forms

**Comment by hibatallahAouadni** [comment]
Hello @marcydude 

You need to downgrade your PHP version to 7.2 cause it's not compatible with PS1.7.6.9, see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements).
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
I have just updated the php version to 7.2 , then cleared the cache and double checked all extensions are installed as recommended.

it all seems to be configured correctly now but still seeing the problem even testing on a new device after clearing the cache

**Comment by ghost** [comment]
Ive just had a comment from the theme developer that the problem doesn't lay within the theme, we activated the classic theme and observe the same issues

**Comment by ghost** [comment]
there are also no console errors when enabling debug mode

however I do seem some translation errors and a doctrine error in the symphony profiler

below is the entity mappign error (under the doctrine header)

image.thumb.png.0a8bbeb82c8a664b0bf4ebc40b723ccf.png

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/75242807/101260417-01051400-3730-11eb-9567-5b37c1a47854.png)

**Comment by hibatallahAouadni** [comment]
Hello @marcydude 

Thanks for you feedback!
Ping @PrestaShop/prestashop-core-developers has anyone encounter this problem or had an idea about this issue source?

Thanks in advance!

**Comment by PierreRambaud** [comment]
> Hello @marcydude
> 
> Thanks for you feedback!
> Ping @PrestaShop/prestashop-core-developers has anyone encounter this problem or had an idea about this issue source?
> 
> Thanks in advance!

This message refers to a doctrine error, which isn't related to the Front Office.
I don't manage to reproduce the issue too.

**Comment by hibatallahAouadni** [comment]
@PierreRambaud thanks for your quick reply :rocket:  

@marcydude It seems your issue is related to your database, yet neither me nor @PierreRambaud could reproduce it.
So, I'm closing this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
