### ISSUE TITLE
[IMPROVEMENT][COMBINATIONS] Display Id product attribute in combinations list

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#22150]
# Is your feature request related to a problem?

Display Id product attribute in combinations list.
In some cases it is very useful to have the combinations id.

# Describe the solution you'd like

Add Id product attribute in combinations list

## After 

![Capture du 2020-11-28 02-17-05](https://user-images.githubusercontent.com/16455155/100491036-fab7dc00-3120-11eb-96e3-5c6ec2077b9f.png)

## Before

![Capture du 2020-11-28 02-15-26](https://user-images.githubusercontent.com/16455155/100491032-f7245500-3120-11eb-8281-0691d3399a1c.png)

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by LouiseBonnard** [comment]
Hi @PululuK, thanks for your improvement idea! Please do not add improvements to the kanban before it has been reviewed and prioritized by the @PrestaShop/product-team. I know our process might still be a bit unclear at the moment. We are working on documenting it and should have it published in the devdocs very soon. Thank you!

**Comment by PululuK** [comment]
> Hi @PululuK, thanks for your improvement idea! Please do not add improvements to the kanban before it has been reviewed and prioritized by the @PrestaShop/product-team. I know our process might still be a bit unclear at the moment. We are working on documenting it and should have it published in the devdocs very soon. Thank you!

I'm very sorry ! Thanks @LouiseBonnard

**Comment by MatShir** [comment]
close by #23581

**Comment by hibatallahAouadni** [comment]
@MatShir does the @PrestaShop/qa-functional tested the PR? if you're sure that PR #23581 fix this issue, please add the label **`Fixed`** :wink: 
Thanks in advance.
