### ISSUE TITLE
Unable to disable Autocomplete search on ps 1.7.6.1

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#22163]
Try to disable module autocomplete and internal search result in a empty box autocomplete loaded on FO. How to complete remove the autocomplete function from default theme and installation?

**Comment by hibatallahAouadni** [comment]
Hello @matteolavaggi 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: if you have a question, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
