### ISSUE TITLE
BO - Modules catalog / "Configure" button is missing

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22170]
#### Describe the bug

After a module installation there is no "Configure" button displayed

#### Expected behavior

The "Configure" button should be displayed

#### Steps to Reproduce

1. Go to BO/Modules/Modules Catalog
2. Install any free module
3. See error => No "Configure" button

**Screenshots**

**Before in 1.7.7**
![image](https://user-images.githubusercontent.com/40635814/100752242-a6468200-33e8-11eb-99f1-3b3773147365.png)

**In Develop**
![image](https://user-images.githubusercontent.com/40635814/100752578-0dfccd00-33e9-11eb-9674-a10294bb4110.png)

**Screenrecord**
https://drive.google.com/file/d/19rZrevMi3gdr2LGSSBDqkXSIlqaxOU9_/view?usp=sharing

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by SD1982** [comment]
Ping @hibatallahAouadni :+1:

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

Isn't a duplicate of https://github.com/PrestaShop/PrestaShop/issues/21825?

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #21825

**Comment by SD1982** [comment]
Hi @khouloudbelguith 
Yes you are right it is clearly a duplicate
