### ISSUE TITLE
Problem with the visualization of products fields

### ISSUE THREAD

**Issue by apfrezza** [PrestaShop/PrestaShop#22176]
Hi,
when I go on a product from my catalogue (when I am in my control panel), I can't see all boxes of all fields. This is quite difficult to explain but very understandable from the picture I attact to this thread. I have tried using Chrome, Firefox and Edge, but the problem is always the same. 
Please help me.
![example1](https://user-images.githubusercontent.com/65793175/100785545-136e0d80-3411-11eb-9802-ec5f662151f0.JPG)
![example2](https://user-images.githubusercontent.com/65793175/100785546-1406a400-3411-11eb-8232-e4dbaf45d835.JPG)

**Comment by SimonGrn** [comment]
Hello,

wrong PHP version.
Please check the [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

Also, **please follow the template** because you didn't provide your PHP version and your PS version and your issue would have been closed anyway, you're lucky I recognized the problem.

Thank you, I close this.

**Comment by apfrezza** [comment]
> Hello,
> 
> wrong PHP version.
> Please check the [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
> 
> Also, **please follow the template** because you didn't provide your PHP version and your PS version and your issue would have been closed anyway, you're lucky I recognized the problem.
> 
> Thank you, I close this.

Hi,
previously I had PHP version 8.0. I downgraded to version 7.4 but the problem is still there. This is very annoying since I can't see many fields on my products.

**Comment by SimonGrn** [comment]
Once again, please read the [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

PHP 7.4 is only compatible with the `develop` branch. Are you using the `develop` branch ?

**Comment by apfrezza** [comment]
How can I check this? My internet hosting service is One.com. I can choose only PHP 7.3, 7.4 or 8.0. I can't see any mention to develop branch. Can you please help me?

**Comment by SimonGrn** [comment]
What version of PrestaShop are you using ?

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by apfrezza** [comment]
Hi,
Prestashop version is 1.7.6.8
I think is something concerning the left  Navigation toolbar... 
![Cattura](https://user-images.githubusercontent.com/65793175/100894289-9ef0a880-34bc-11eb-94cf-8de6a5e99c77.JPG)
![Cattura2](https://user-images.githubusercontent.com/65793175/100894292-a021d580-34bc-11eb-9d65-c483029d665b.JPG)

**Comment by SimonGrn** [comment]
Hello,

Did you open the [link ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)I sent you three times ? [This link](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart). [Here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

In this link, you can see that PrestaShop 1.7.6.8 is compatible up to PHP 7.2 : 
![image](https://user-images.githubusercontent.com/49909275/100895123-803ee180-34bd-11eb-81c8-9ab042a52db6.png)

If you run PHP 7.3, 7.4 or 8.0, **it will not work**.

Once again, you can find the [compatibility chart](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart) here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

I'm really sorry, I can no longer answering this thread.

If you need support for your shop, you can follow the link I gave you in my precedent comment.

Thank you for your understanding.
