### ISSUE TITLE
Upgrade to 1.7.7.0 stable build from 1.7.5.x and previous versions : Currency precision is set to 6 by default

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22177]
#### Describe the bug

When making an upgrade from 1.7.5.x and previous version to 1.7.7.0 build stable, the precision of each currency installed is set to 6, leading to unwanted display on FO, and invoices.

#### Expected behavior

After upgrade, the precision of the currency should be the one set by default (2 decimals for example for Euro) instead of 6.

#### Steps to Reproduce

1. Install 1.7.5.x version with Euro installed and autoupgrade module
2. Make an upgrade to 1.7.7.0 stable build
3. Go to International > Localization > Currencies and open Euro parameters : Decimals is set to 6 instead of 2
4. Go to FO > Clothes : Demo Product prices are displayed on 3 digits
5. Make an order with these products, confirm the order and generate invoice in BO : Invoices has 3 digits.

**Screenshots**

Currency Euro in BO : decimals set to 6 after upgrade : 

![decimel set to 6 1](https://user-images.githubusercontent.com/55688534/100788101-e9b6e580-3414-11eb-80a7-d21010752fed.png)

Display on FO with 3 digits (with demo product) : 

![decimel set to 6 2](https://user-images.githubusercontent.com/55688534/100788135-f6d3d480-3414-11eb-8005-37264f89c8e7.png)

Invoice with 3 digits in Euro : 

![decimel set to 6 3](https://user-images.githubusercontent.com/55688534/100788162-ff2c0f80-3414-11eb-9a10-e70de2092300.png)

#### Additional information

* PrestaShop version: 1770 stable build 5
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #22178
