### ISSUE TITLE
can not connect to back office, no error

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#22179]
#### Describe the bug

Can not connect to back office

#### Expected behavior

after writting my login and password, nothing happens

#### Steps to Reproduce

1. Go to backoffice
2. Write login and password
2. Click on connect

**Screenshots**
![ScreenShot010](https://user-images.githubusercontent.com/50581985/100801704-a5354500-3428-11eb-9397-411f137f82f8.jpg)
![ScreenShot011](https://user-images.githubusercontent.com/50581985/100801705-a5cddb80-3428-11eb-80fd-1f1c45b809ee.jpg)
![ScreenShot012](https://user-images.githubusercontent.com/50581985/100801708-a6ff0880-3428-11eb-9c6f-1ab295d80208.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment]
Hi @Jerome08 there is an issue on your prestashop installation. Standard login process works fine as you can see on http://demo.prestashop.com/ . This is not an issue from the code.

**Comment by SimonGrn** [comment]
All the directories are not writable, that might be a problem to have all red maybe, don't you think ?

**Comment by Jerome08** [comment]
Hello

Thanks to help me

i seen that but i have 7 prestashop installed on my host

i compared to my others prestashop and it was same, 6 others prestashop 
have same directories not writable too, so i tought it was normal

6 are still working normaly only this one i can't connect

and this prestashop was working fine from a few month, i didn't changed 
anything

do u think i have to modify the rights on this directories?

Jerome

Le 01/12/2020 à 23:54, Simon G. a écrit :

**Comment by SimonGrn** [comment]
Sadly, if all your other installations are working fine and we're not able to reproduce, that means it's a problem on your end: you have a difference in your environment/configuration.
We won't be able to help you here.

Thank you for your understanding.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Jerome08** [comment]
it's solved

the problem was during time for cookie too big (cookie.php)
it's totally stupid that prestashop allow to put a big value and then it's totally blocked

someone helped me and changed in ps_configuration table

PS_COOKIE_LIFETIME_BO
PS_COOKIE_LIFETIME_FO

value to 480 

now it's solved

**Comment by Jerome08** [comment]
so it's a bug to authorize a incorrect value !
you should put a warning or not authorize a too big value....

**Comment by SimonGrn** [comment]
Hello,

as you may or may not know, this is an open source project: you are totally welcome to help improving it, since it is provided to you for free. This is a nice gesture, really appreciated.

Thank you for your understanding.
