### ISSUE TITLE
PaySera module - error when making a "full refund" of a cancelled order that is paid via PaySera module

### ISSUE THREAD

**Issue by VidarPc** [PrestaShop/PrestaShop#22180]
Oops! An Error Occurred The server returned a "500 Internal Server Error". Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.                                                                      racinghorses.eu | Oops! An Error Occurred The server returned a "500 Internal Server Error". Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. | racinghorses.eu | racinghorses.eu

#### Expected behavior

When making a full refund for an order that is paid via PaySera module, I am getting the above-mentioned error message. PrestaShop is supposed to make a credit-invoice for the actual transaction and make a full refund via the PaySera module to the payer. But it fails with the above-mentioned message. Also, every time I am repeating to make a full refund on this order, the counter of available quantities for the actual product to be refunded, is increasing with the actual amount of the product to be refunded. But I am not getting any credit-invoice produced and PaySera does not get a request to refund the payment to the user from the "PaySera" module.

#### Steps to Reproduce

1. Go to "Orders"
2. Click on 'the actual order that shall be refunded"
3. Choose "Standard refund"
4. Click on the refund box
5. Click on the "Generate a credit slip" option.
6. Click on the "Refund products"
4. See error "500 internal Server error" above.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

PS : mentioning your PS/PHP version is mandatory. Please follow the template next time, thank you.
