### ISSUE TITLE
BO - Currencies page - An exception is diplayed when creating a currency  with invalid name 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22188]
#### Describe the bug

IN the BO > International > Localization > Currencies page, when we try to add a new alternative currency with an invalid name `<>` => an exception is displayed
Try to Go to BO => NOK
Try to go to FO => NOK
The shop is totally broken

#### Steps to Reproduce

1. Go to BO > International > Localization > Currencies page
2. Click on Add new currency 
3. Select "Create an alternative currency"
4. Set an invalid currency name
4.1 for example `<> ` reproduced by me & @Robin-Fischer-PS 
4.2 for example `=test` reproduced by @Robin-Fischer-PS 
5. Click save
6. see => error 
7. Go to BO => NOK
![image](https://user-images.githubusercontent.com/16067358/100870412-dea89780-349e-11eb-9908-01b7588018a9.png)
8. Go to FO > NOK
https://drive.google.com/file/d/17pFLeaYg66d9XnS8sbVAgcOuU-CuEI2O/view?usp=sharing
Ps: with PS1.7.6.8 => we cannot created an alternative currency
![image](https://user-images.githubusercontent.com/16067358/100870251-9db08300-349e-11eb-8b4d-521558828db7.png)

**Screenshots**
https://drive.google.com/file/d/17pFLeaYg66d9XnS8sbVAgcOuU-CuEI2O/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by jolelievre** [comment]
Closed by #22191
