### ISSUE TITLE
Nothing changes when displaying or hiding the "add to cart" button for product with attributes

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#22187]
#### Describe the bug

In Shop Parameters > Product Settings > Whether you display or hide the "add to cart" button for products who have attributes, nothing seems to change on the front office.

#### Steps to Reproduce

1. Go to Shop Parameters > Product Settings > Display the "add to cart" button when a product has attributes
2. Choose "No", save, and check front office
3. Then, choose "Yes", save, and check front office
3. Nothing changes 

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Julievrz 

I managed to reproduce the issue with PS1.7.6.9 and PS1.7.7.0-rc.1 (even with PS1.7.4.1), see the attached screen record below:

https://drive.google.com/file/d/1EO4L9LbgoUkRrz-0hx7QFQvKphVacTab/view

I’ll add this to the debug backlog so that it’s fixed.

Thanks!

**Comment by Julievrz** [comment]
https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/shop-parameters/product-settings/product-settings-page.md

Hi @hibatallahAouadni. It seems that this feature is actually not available for the classic theme (see the specs: https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/shop-parameters/product-settings/product-settings-page.md) 

I am therefore closing this issue.
