### ISSUE TITLE
BO - Credit Slips - An exception is displayed when downloading a credit Slip

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22186]
#### Describe the bug

This issue occurs when debug mode is enabled.
An exception is displayed when downloading a Credit Slip.
![image](https://user-images.githubusercontent.com/16067358/100864447-4a3a3700-3496-11eb-9a35-99d9d303567f.png)
=>
![image](https://user-images.githubusercontent.com/16067358/100864385-34c50d00-3496-11eb-9247-a30569b921e4.png)

#### Steps to Reproduce

0. Enable debug mode
1. Create an Order from FO
2. Go to the orders page
3. Go to the created order page
4. Change the order status to 'Shipped'
5. Add a partial refund
6. Go to Credit slips page
7. Download the first credit slip => see error
8. Generate PDF file by date => see error

PS:177x => ok

#### Additional information

* PrestaShop version: develop(1780)
* PHP version: 7.2

**Comment by ghost** [comment]
This issue is fixed by : https://github.com/PrestaShop/PrestaShop/commit/c1b64fb0dc6e016d3c55a9d2d8c32360a8640989

**Comment by marionf** [comment]
@khouloudbelguith Could you please verify if this issue is well fixed on 1.7.8.x branch ?

**Comment by ghost** [comment]
It's a duplicate https://github.com/PrestaShop/PrestaShop/issues/23422

**Comment by marionf** [comment]
Thank you for your input @okom3pom :+1:

**Comment by marionf** [comment]
Duplicate of #23422

**Comment by khouloudbelguith** [comment]
Thank you @okom3pom
