### ISSUE TITLE
ps_facetedsearch subcategories filter is not working as expected

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#22195]
#### Describe the bug

Hello, I have categories and subcategories : 

2. Home (root)
--> 7. Nos produits
----> 3. Salaisons
--------> 8. Jambons
--------> 9. Saucissons
--------> 10. Colis
--------> 11. Saucisses
--------> 12. Autres produits
... etc

When visiting category page "Nos produits", the faceted search is showing subcategories from multiple levels:

<img width="308" alt="Capture d’écran 2020-12-02 à 16 46 39" src="https://user-images.githubusercontent.com/167037/100895613-0d823600-34be-11eb-815e-8a7d4002c75f.png">

#### Expected behavior

Only "Salaisons" should be displayed and if the customer clicks on the "Salaisons" checkbox "Jambons", "Saucissons", "Colis", "Saucisses" and "Autres produits" should then appear 🤔

#### Steps to Reproduce

1. Create multiple levels of categories and subcategories
2. Associate product with those freshly created categories and subcategories
3. Show the subcategory filter in ps_facetedsearch 
4. Visit the main category page

**Screenshots**

Here is my current configuration : 

<img width="701" alt="Capture d’écran 2020-12-02 à 16 52 37" src="https://user-images.githubusercontent.com/167037/100896346-cea0b000-34be-11eb-8a28-7746daceeb32.png">

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34
* ps_facetedsearch version : v3.6.0

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

Could you please check if your issue is similar to this one #20385

Thanks!

**Comment by PierreRambaud** [comment]
Hi, the problem is here:
![image](https://user-images.githubusercontent.com/1462701/100923678-d58bea80-34df-11eb-88fb-7a66e2972324.png)
You should keep the 1 as default value

**Comment by Daaaaad** [comment]
Hi @PierreRambaud,

Thank you for your answer 👍 I already tried that and here is what I get : 

<img width="326" alt="Capture d’écran 2020-12-02 à 21 02 55" src="https://user-images.githubusercontent.com/167037/100925078-cc038200-34e1-11eb-8bae-534ffa11c682.png">

No subcategories filter anymore 😢

**Comment by PierreRambaud** [comment]
Yes because you have only one subcategory :thinking:

**Comment by Daaaaad** [comment]
I do have multiple subcategories (see etc) 😉 

But you're kinda right @PierreRambaud that was because I only had products in one subcategory 😀 

Thank you everybody 👏
