### ISSUE TITLE
Prestashop 1.6 : can't select any of my carrer option.. Fall down on error message !

### ISSUE THREAD

**Issue by noiwid** [PrestaShop/PrestaShop#22190]
Hi,

I'm about to deploy for a customer a new store on Prestashop 1.6.1 that already use multistore mode.
My customer already have a **BRAND A** that has 2 shops, one for **EU**, one for **US**.
For the new **BRAND B**, we have same objective, launch one store for **EU**, one for **US**.

We've built a new theme for **BRAND B** and set up the EU version (catalog, modules, etc...) then use the multistore system to build the US store of **BRAND B** and deploy all contents needed. 
Everything is ready to launch but we just discover a big issue on the US version of this new store that make me mad since 2 days !

**There is no way to select the CARRER OPTIONS, and we fall down on an error message :**

```
**_There is 1 error
This carrier has not been configured yet; please contact the merchant._**
```

This US store use a USPS module that calculate the shipping price (exactly the same that already works for the **BRAND A US** store).
We use the 5 step cart process. 
In my cart the carrers are here, : the 2 options offered are shown properly with the good price, but no way to pick one of the two options offered.

I've try to disable the USPS module and set up manually  a new carrier not linked to a module, with a flat price... but I keep falling on the same issue.
Any idea what can cause such issue ?!? I'm a bit confused (and desperate 😅)
Thanks a lot for your support 🙏

Ben

**Comment by matks** [comment]
Hi, if you have questions or need help, please do not open a GitHub issue as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

You can follow the steps in https://devdocs.prestashop.com/1.7/faq/i-need-help/ to find help

**Comment by SimonGrn** [comment]
Hello, I would like to add that we don't support 1.6 anymore.
