### ISSUE TITLE
Behat tests: Reset static cache of all object models between feature tests (clearCacheBeforeFeature) 

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#22197]
#### Is your feature request related to a problem?

Sometimes, we add behat tests, it works fine, but then it fails when we execute our test amongst the other behat tests.

That's because there are some static caches from previous tests messing with the tests we added. When it happens we have to debug, find which previous test makes our test fails, it's annoying and a loss of time.

#### Describe the solution you'd like

The idea is to reset the static caches of ALL object models between behat feature tests instead of resetting the cache of object models one by one as we encounter problems. There are parts of the software that are not covered by behat tests yet, and these issues will happen again for sure as we migrate new pages, integrate new CQRS commands, etc...

**Comment by hibatallahAouadni** [comment]
Hello @matthieu-rolland 

Thanks for your sugguestion and your PR :sweat_smile: 
Ping @PrestaShop/prestashop-core-developers wdyt?

**Comment by matthieu-rolland** [comment]
@hibatallahAouadni well I discussed it with @eternoendless already, and the pr is ready for review 👍

**Comment by Progi1984** [comment]
Fixed by #22198
