### ISSUE TITLE
Customzation lost when order is placed

### ISSUE THREAD

**Issue by zzzZZZzzz9** [PrestaShop/PrestaShop#22196]
#### Describe the bug

Sometimes on orders containing a customizable items more than one time, the customization text is "lost" as soon as the order is placed. The cart looks as expected until this point but changes when the order is placed.

Recent example:
For a cart that was ordered from, ps_customization looks like this (5 x item 156 with different texts, 2 x 175  and 1 x 165):
![image](https://user-images.githubusercontent.com/49036578/100900787-7e781c80-34c3-11eb-87db-a0fc516c9242.png)

In ps_customization_field_lang there are contents for all of these customizations:
![image](https://user-images.githubusercontent.com/49036578/100900713-67392f00-34c3-11eb-9405-e9c7a5c73253.png)

All good so far. But when the order was placed, I ended up with this:
![image](https://user-images.githubusercontent.com/49036578/100900847-8fc12900-34c3-11eb-940b-a59770025434.png)

For each item ordered multiple times, I see the customization text only for one. The others are just there. In ps_cart and ps_order_detail it looks like this:
![image](https://user-images.githubusercontent.com/49036578/100900983-b1221500-34c3-11eb-8e07-05d694d7e294.png)

![image](https://user-images.githubusercontent.com/49036578/100901024-b7b08c80-34c3-11eb-9e31-edc4b1db84c5.png)

#### Expected behavior

For multiple instances of a customizable item with different texts, I would expect one line per item with the respective customization text.

#### Steps to Reproduce

I have not been able to reproduce this consistenly. I don't see any causality regarding specific products.
Try adding a customizable product to the cart multiple time with different texts...

#### Additional information

PS 1.7.6.7 | Classic Theme | PHP 7.2 | MySQL 5.7

**Comment by hibatallahAouadni** [comment]
Hello @zzzZZZzzz9 

Unfortunately, we need a scenario that allows us to reproduce 100%. 

I'm really sorry but we use GitHub issues only to discuss about bugs (that are 100% reproducible) and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
