### ISSUE TITLE
Editing of deleting a currency KO after upgrade from 176 to 1770 if currency was modified in 176

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22208]
#### Describe the bug

When a currency was modified in 176, if I upgrade to 1770, the currency can no longer be modified or deleted in 1770 BO, an error is displayed. There is also an error if I try to upload again the currency using the "localization pack".

According to investigation with some devs, it's linked to the numeric iso which is saved as "12" after edit, but should be at "012". That explains why this bug only happens on currencies with numeric iso code < 100, such as Algerian Dinar (code 012) or Argentine Pesos (code 032).

See Wikipedia page for numeric iso code of currencies : 

https://en.wikipedia.org/wiki/ISO_4217#Active_codes

#### Expected behavior

Numeric iso code should be saved on 3 digits and not 2.

#### Steps to Reproduce

1. Install 1.7.6.x version
2. In BO, add localization pack (for example, Algeria) in order to have the DZD currency
3. Edit the currency (for example, change exchange rate)
4. Upgrade to 1.7.7.0
5. Go to BO > International > Localization > Currencies > Edit DZD currency : The following error is displayed : 
`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Currency\Exception\CurrencyException code 0]: An error occurred when deleting Currency object with id "2"`
6. Try to delete the currency : Same error
7. Go to "Localization" tab, try to add Algeria Pack : An exception is displayed `Property Currency->numeric_iso_code is not valid
`

**Screenshots**

Screenrecord of behavior after upgrade : 

https://drive.google.com/file/d/1jID2MoVJbeTcK0TaR3q8IVi4B47Md1fP/view?usp=sharing

Screenshot of exception : 

![edit currency after upgrade 2](https://user-images.githubusercontent.com/55688534/100996489-64891900-3559-11eb-9f1f-41dca839216f.png)

Screenshot of the database : Value for DZD is "12", should be "012"

![edit currency after upgrade db 1](https://user-images.githubusercontent.com/55688534/100996456-5b984780-3559-11eb-8296-91a6f116b292.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixes #22214
