### ISSUE TITLE
No shipping and payment methods available

### ISSUE THREAD

**Issue by diyan1234** [PrestaShop/PrestaShop#22205]
Hi all, 

I have an issue with displaying shipping and payment method for my One Page Checkout module. I tried 2 different one page checkout modules and for both of them shipping and payment method are not displaying. I have installed Cash on delivery module and I created 3 shipping options. None of them is displaying. 

[https://prnt.sc/vuvoz4](url)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.0.33

**Comment by HartLarsson** [comment]
these payment methods appear in normal 4 step checkout? If yes you need to contact the OPC developer and ask for a fix.
If your payment methos not appear also on normal checkout the problem could be the visibility of the payment methods.

go to Payments > Preferences and check the payments are enabled in all the countries, currencies and groups.

**Comment by hibatallahAouadni** [comment]
Hello @diyan1234 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
