### ISSUE TITLE
1.7.7.0 upgrade fail - download 1.7.0.0 instead (fixed, bad link)

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#22200]
Can not upgrade to the new 1.7.7.0

I think this is because of the link for the download, it show 1.7.0.0.com

Some has issue appears

**Comment by SimonGrn** [comment]
Hello,

we need more information, we don't have enough details to even begin to investigate. What link are you talking about ? Are you talking about autoupgrade ? The article on Build ?
Please provide enough details.

Thank you in advance.

**Comment by jolelievre** [comment]
Hello,

yes I made a mistake in the channel the wrong archive was downloaded.

It is correctly updated and I wen through the whole upgrade process, it works now! 👍

**Comment by 01park** [comment]
I tried, but still get the same issue

<img width="1936" alt="Screenshot 2020-12-02 at 19 01 08" src="https://user-images.githubusercontent.com/46492443/100918818-e1bc7b80-34d0-11eb-96e9-d93e7be499c1.png">

**Comment by 01park** [comment]
I pressed update page and now it is upgrading. Thank you!
