### ISSUE TITLE
Exception Attempted to call function "p" from the global namespace.

### ISSUE THREAD

**Issue by robertosanval** [PrestaShop/PrestaShop#22206]
#### Describe the bug

Error 500 when execute the cron, no problem generating sitemap manually.

#### Expected behavior

Get the sitemap

#### Steps to Reproduce

Click on the URL to generate the sitemap via Cron

**Error**

(1/1) UndefinedFunction
Exception Attempted to call function "p" from the global namespace.
--
in gsitemap-cron.php line 56

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by SimonGrn** [comment]
Hello,

PrestaShop 1.7.6.7 is not compatible with PHP 7.3 as you can see in the [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).

Thank you.
