### ISSUE TITLE
Link list warning in upgrade from previous versions to 1.7.7.0

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#22203]
#### Describe the bug

Reported here:
https://github.com/PrestaShop/PrestaShop/issues/18647#issuecomment-737682051

Update for linkblock module is failing because module is not installed

#### Expected behavior

We shouldn't have update of module tables inside core upgrade file.

#### Steps to Reproduce

1. Install fresh 1.7.6
2. Make sure that `ps_linklist` is uninstalled
3. Try to update to 1.7.7.0

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello @kpodemski,

thank you for your issue. Just a quick question: is it blocking the upgrade or just failing for `ps_linklist` ?

**Comment by kpodemski** [comment]
@SimonGrn I will rename this issue. This is not critical error.

**Comment by Progi1984** [comment]
A PR has been done for ps_linklist : https://github.com/PrestaShop/ps_linklist/pull/105. But we should remove bad sql request for `1.7.7.0.sql`.

**Comment by Progi1984** [comment]
Fixed by #22289
