### ISSUE TITLE
actionCartUpdateQuantityBefore not return $date

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#22210]
Hello. Please add the ability for the hook to return data: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L1411

**Comment by hibatallahAouadni** [comment]
Hello @TemKaSD 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
