### ISSUE TITLE
PS 1.7.6.9 : Activation of CCC + clear cache: slow front, loading more than 25s

### ISSUE THREAD

**Issue by dngraphisme** [PrestaShop/PrestaShop#22213]
Hello all,

I find myself with a rather annoying problem on a PS 1.7.6.9 > When I activate the CCC CSS and JS, that I empty the cache the front takes more than 25s to load ....

Then the navigation is slow on 2/3 pages and afterwards the site returns to normal. When emptying the cache we noticed  that the CPU cracks completely on the server. 

**Has anyone ever had this problem ?**

Thanks in advance

1.Go to performance
2.CCC enabled on CSS and JS
3.Cleared the cache
4.Go to the front > The DOM is blocked and the site is displayed in 25s ...

![FireShot Capture 524 - PHP PrestaShop Info - dev canebiera com](https://user-images.githubusercontent.com/5530905/101015760-2b0bda00-3568-11eb-93bb-01138753a809.png)

<img width="1413" alt="Capture d’écran 2020-12-03 à 13 07 49" src="https://user-images.githubusercontent.com/5530905/101016114-9ce42380-3568-11eb-98d2-35df454e9cd2.png">

**Comment by hibatallahAouadni** [comment]
Hello @dngraphisme 

You must change the access permission to writable for all those directories:

![image](https://user-images.githubusercontent.com/23308427/101017750-cdc55800-356a-11eb-9ec8-f4e3b0a26c68.png)

Please check and feedback.

Thanks!

**Comment by SimonGrn** [comment]
Sounds also like a performance problem if your CPU skyrockets. Are you sure your server is properly dimensioned ?

**Comment by dngraphisme** [comment]
> Hello @dngraphisme
> 
> You must change the access permission to writable for all those directories:
> 
> ![image](https://user-images.githubusercontent.com/23308427/101017750-cdc55800-356a-11eb-9ec8-f4e3b0a26c68.png)
> 
> Please check and feedback.
> 
> Thanks!

Hello @hibatallahAouadni ,

Thank you for the return, the files are well in writing access, it is a beug of the report I think ....

@SimonGrn At the moment I can't tell you more ... I'm trying to see this with my host too. This prestashop really doesn't have much on it.

**Comment by hibatallahAouadni** [comment]
Hello @dngraphisme 

I didn't manage to reproduce your issue with PS1.7.6.9 and PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1iMSIP6kXG2eFaxtpGFdauEiDVcGiAYcl/view

The site is displayed in 3s!
Please check and feedback.

Thanks!

**Comment by dngraphisme** [comment]
Hello @hibatallahAouadni ,

Thanks for you feedback.

I also have this problem on an earlier version of PS 1.7.6.4 ... (the production version of my client's site)

I still don't know if this is coming from the server or if a module is causing the store to be slow. I have yet deactivate reactivate modules 1 by 1 and no viable solution to date..

Thanks again

**Comment by hibatallahAouadni** [comment]
Hello @dngraphisme 

I think your issue is related to your host/server, cause everyone can't manage to reproduce your issue.

I'm really sorry but we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
