### ISSUE TITLE
BO - Credit slip - The pagination doesn't work correctly

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22216]
#### Describe the bug

In the BO > Orders > Credit slips page, you must have more then 10 credit slip, if you try to change, the pagination (item per page) => Nothing happens.

#### Steps to Reproduce

1. Go to BO > Orders > Credit Slips > You must have more than 10 credit slips
2. Try to change item per page 
4. See error => Nothing happens

https://drive.google.com/file/d/1UI4FA2pOknR5mnAkWE_cej8ejAstxXbt/view?usp=sharing
PS1.7.6.9 => ok
https://drive.google.com/file/d/1iTpRHuR57-O9HQQOn6JJsbilfx9XATNP/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, develop
* PHP version: 7.2

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/22291
