### ISSUE TITLE
Null is displayed instead of Deleted account when option to anonymize is set to Yes in product comment

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22222]
#### Describe the bug

Null display instead of Deleted account when option to anonymize is set to Yes in product comment

#### Expected behavior

Should be deleted account 

#### Steps to Reproduce

1. Install product comment and set "Anonymize the user's last name" to Yes 
2. Create an account in FO
3. Add a comment to a product and approuve it
4. Delete the customer
5. See that is "null" instead of "Deleted account"

**Screenshots**
<img width="1173" alt="Capture d’écran 2020-12-03 à 16 01 00" src="https://user-images.githubusercontent.com/3034677/101045855-e3de1300-3580-11eb-80d6-fc1e9e58f54a.png">

#### Additional information

* PrestaShop version: 1.7.7.0, 1.7.6.0
* Module version : 4.2.0 et 4.2.1
* PHP version: 7.1

**Comment by Progi1984** [comment]
(Respect for the #22222)

**Comment by SimonGrn** [comment]
#22222 nice
