### ISSUE TITLE
After upgrade to 1.7.7.0 - Mobile devices displays images to the left instead of being placed in the center

### ISSUE THREAD

**Issue by VidarPc** [PrestaShop/PrestaShop#22221]
#### Describe the bug

I discovered that on an android mobile device, the images of the product listing in categories were centered to the very left side of the screen on my android phone. Before, they were nicely centered on my android screen when browsing the shop categories. I have not been able to solve this issue with displaying images correctly, not being in the center of the screen when listing a category in my shop. When clicking on a specific product, it is centered correctly on the screen and looks like it had been displayed before the upgrade to 1.7.7.0. But the listing of categories looks ugly when centered to the left of the screen. Any advice on how to solve this would be highly appreciated.

#### Expected behavior

I was expecting that product listing on an android phone, would display the images of the product in the center of the screen as before the upgrade.

#### Steps to Reproduce

Browse your shop on your android phone and choose any category of products. You will see the product images are misplaced to the left of your screen, instead of as in the previous PrestaShop release, they were nicely centered on your screen. 

A solution on how to solve the center of the images on the android screen when listing a category is not clear for me. Click on the image below and you will see the product images are centered to the left instead of nicely centered in the middle of your screen.

**Screenshots**

![Screenshot_20201204-105230_Edge](https://user-images.githubusercontent.com/18537770/101143370-77feb780-361f-11eb-9f9d-8688f785ea16.jpg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello @VidarPc 
Your screenshots show your admin URL, please remove them.

**Comment by VidarPc** [comment]
Oh, thank you removed the screenshots!

**Comment by hibatallahAouadni** [comment]
Hello @VidarPc 

I managed to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1OzLdcnjJiqCyDpTv5UsZqtNcsWZlJiBs/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by SimonGrn** [comment]
Hello @VidarPc,

Please make one issue per problem, we have two issues in the same post and that will make things harder for us.
Could you please keep this one only about the images not centered and create another issue for Faceted Search ?

I'll let you edit your issue.
Thank you in advance

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/22296
