### ISSUE TITLE
Allow html when displaying customizations in the backoffice order page

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#22220]
#### Describe the bug

Customizations displayed by a module are not displayed correctly

#### Expected behavior

HTML should be allowed when displaying customizations because the customization is sanitized on save anyway and modules hooked to `displayCustomization` would need to display a html summary in most cases

#### Steps to Reproduce

You will need a module that is hook to displayCustomization and which is returning a html summary of the customization
- Install Sample module [customization_hook.zip](https://github.com/PrestaShop/PrestaShop/files/5636807/customization_hook.zip)
- Add a customization to cart and proceed with the order normally
- Change id_module in ps_customized_data to the id of the customization_hook module (can be found in ps_module)
- The customization will be displayed like this 
![image](https://user-images.githubusercontent.com/793712/101043561-bd1edd00-357e-11eb-93c5-c46355efd204.png)
But it should be like this
![image](https://user-images.githubusercontent.com/793712/101043646-d162da00-357e-11eb-8daa-d1963470aead.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/793712/101042218-36b5cb80-357d-11eb-9e0f-166ba24e7589.png)

It should be

![image](https://user-images.githubusercontent.com/793712/101042295-53520380-357d-11eb-914a-c2e2ed900ee5.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

I will submit a PR to fix this

**Comment by hibatallahAouadni** [comment]
Hello @unlocomqx 

> Change id_module in ps_customized_data to the id of the customization_hook module (can be found in ps_module)

What do you mean by that? you mean I have to change id_module from the database?
Did you upgrade your shop? if so, could you please tell which PS version you had and if this bug occured with your previous shop?

Thanks!

**Comment by unlocomqx** [comment]
@hibatallahAouadni Yes, it's normally done by a module where the module saves its ID in the the table ps_customized_data when it saves the customization.
Then based on that ID, the displayCustomization hook is called and thus only the concerned module is invoked.

My PrestaShop version is 1.7.7.0
The bug didn't occur in the previous versions because html was allowed in the previous templates
With the new twig templates, html is filtered when it comes to displaying customizations in the backoffice

**Comment by hibatallahAouadni** [comment]
Hello @unlocomqx 

Well, I installed your module in PS1.7.6.9 and PS1.7.7.0, and I didn't see the difference.
First, I couldn't add html code in Customization field (if it was text/file), see the attached screen record below:

**- Text:**
https://drive.google.com/file/d/1n_99YP3oxNVfrfjxz7ZRJ_WXvn7jIdMS/view

**- File:**
![image](https://user-images.githubusercontent.com/23308427/101370273-9546b680-38a9-11eb-9a45-e72511810e8d.png)

Second, I couldn't understand how your module works, could you please provide screen record.

Thanks!

**Comment by unlocomqx** [comment]
@hibatallahAouadni It's okay, we discussed the PR and it wasn't accepted, so I will close this issue
I found another way to avoid this problem
Kind regards
