### ISSUE TITLE
subcategories don't work in module (ps_facetedsearch)

### ISSUE THREAD

**Issue by MadArtOrigin** [PrestaShop/PrestaShop#22230]
#### Describe the bug

Hi, I've done several test but I have problems with categories of profondity > 1
In other terms: it filters only for main category (profondity 1) but not for the others subcategories..
I tried also with default theme but it still doesn't work
Maybe I'm missing something..
Please help me out.

* PrestaShop version: 1.7.7.0

**Comment by casadavinci** [comment]
I think you just need to activate the faceted search on those subcategories:

Go to Modules > Module Manager > Faceted Search - Configure > Template - Edit

Click Expand All and Check All, and then scroll down until the bottom and Save the changes. Delete the Cache and Reconstruct the Price Index. 

Tell me if this works.

**Comment by florine2623** [comment]
Hi @MadArtOrigin and @casadavinci ,

Please do like @casadavinci said :
![Capture d’écran 2020-12-04 à 09 59 06](https://user-images.githubusercontent.com/16019289/101143574-5ef20880-3617-11eb-8f17-3475f02d59c3.png)

All categories need to be checked like so.
Here's the result (subcategories are showing correctly) : 
![Capture d’écran 2020-12-04 à 09 58 52](https://user-images.githubusercontent.com/16019289/101143581-631e2600-3617-11eb-9eeb-6ca886f8a587.png)

I can't reproduce your issue on my end so I close your issue.
Thanks.

**Comment by MadArtOrigin** [comment]
ty for your response, but ...
maybe I haven't explained myself.

I have already activated the subcategories. With the check.
But it's the filter that doesn't work in the front-end.

There is a bug whit the filter. 

Solution ?
