### ISSUE TITLE
Prices not correctly defined after import

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#22235]
On prestashop 1.7.6.8, php 7.2

- Import a CSV in a multishop
- Set priceHT -> 9.99 and price TTC -> 9.99 (no taxes) on my shop
After import, look at the result :
<img width="808" alt="Capture d’écran 2020-12-04 à 03 28 59" src="https://user-images.githubusercontent.com/43704805/101114242-5e3e7f80-35e1-11eb-82c5-dac93c3fa629.png">
<img width="539" alt="Capture d’écran 2020-12-04 à 03 29 08" src="https://user-images.githubusercontent.com/43704805/101114250-61397000-35e1-11eb-9181-bc17f28fc7de.png">

If you open the product and Save, the problem is solved. However, very long when you add hundreds of products.

I would like to say I posted an error some weeks ago about the impossibility to import quantity with .CSV in multishop. Problem still occur and I had to define manualy hundred of quantity after import in EACH language...

**Comment by ghost** [comment]
You have a line to test ?

I think you forget to put 0 in the csv file ? Or another value

**Comment by passio777x** [comment]
2first lines of the CSV :

```
nom produit;Catégories;Méta-titre;méta-description;Resume;Reférence;prixAchatTTC;prixVenteHT;prixVenteTTC;Quantité;poids;features;EAN;imgDescr;imgUrl;1;active
Perles en bois - Grand coffret;Créativité;Perles en bois - Jouet enfant - Jeu de créativité Montessori;Perles en bois multicouleurs - Perles pour enfants - Jeu créatif pour la conception de bijoux, colliers, bracelets. Matériel Montessori;Ce coffret de perles en bois comporte des perles pour les enfants avec des couleurs vives et chatoyantes pour la confection de magnifiques bijoux, bracelets, colliers... Le coffret des perles de formes variables et certains motifs tels que des fleurs ou des papillons. La cordelette de couleur assortie aux perles est également inclue.;REFL10735;11.08;26.99;26.99;3;0.45;Dimensions:30 x 28 x 2,5 cm,Poids:0.41 kg,Âge:à partir de 3 ans;4020972107350;Perles en bois - Grand coffret Montessori,Perles en bois - Grand coffret Montessori,Perles en bois - Grand coffret Montessori;;3;0
```

I forgot nothing, this problem always happen. Maybe it's due to the fact i put the HT and TTC price, should I only set the TTC PRICE ? If I do, the HT price is calculated and this HT value has no meaning for my business.

**Comment by florine2623** [comment]
Hi @passio777x ,
Can you send the csv related to the product you mentioned ? Prices are different.

Also, share the configuration of you multistore please (without any admin url). (how many store, if data is shared, same group or not, etc)

Thanks.

**Comment by ghost** [comment]
U need to set an taxe rule id

**Comment by passio777x** [comment]
Hi Florine, the product doesnt matter,  bug occur for all lines. 
<img width="1901" alt="Capture d’écran 2020-12-04 à 13 10 55" src="https://user-images.githubusercontent.com/43704805/101162099-2b70a780-3632-11eb-9b54-b25fe69f0e3b.png">

okom3pom, How ?

**Comment by florine2623** [comment]
@passio777x 
In your CSV you need to specify the Tax RuleS ID / Règle de tax column.
`Product ID | Active (0/1) | Name * | Categories (x,y,z...) | Price tax excluded | Tax rules ID `

In your screenshot Règle de Taxe is empty. If the tax is specified, the price will be correct.

**Comment by passio777x** [comment]
Thank you very very much Florine :)  ! ! !

**Comment by hibatallahAouadni** [comment]
Hello @passio777x 

It seems your problem is fixed :slightly_smiling_face: 
So, I close the issue. 
If you encounter any other problems, feel free to open a new issue, we will gladly investigate it.

**PS:** Thanks @okom3pom & @florine2623 :wink: 

Thanks!
