### ISSUE TITLE
 No update proposed for PSGDPR

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22232]
#### Describe the bug

There is no update proposed for the psgdpr module

#### Expected behavior

Normaly the last version fix : https://github.com/PrestaShop/PrestaShop/issues/18776 but actually we need to download the github version and make a manual update.

#### Steps to Reproduce

1. Install 1770 
2. Go to module -->> update
3. You see only two modules to update

**Screenshots**

![Capture d’écran de 2020-12-04 02-03-15](https://user-images.githubusercontent.com/5064590/101108623-4103b400-35d5-11eb-9727-75f11914f70a.png)

#### Additional information

* PrestaShop version: 1.7.7.0 ( new install ) 
* PHP version: 7.3.25

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for the report. 
I was able to reproduce the issue with PrestaShop version 1.7.7.0. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Indeed, module PS GRDP upgrade to v1.2.1 is not available automatically in the module section of the BO.
![Capture d’écran 2020-12-04 à 09 37 33](https://user-images.githubusercontent.com/16019289/101141531-b5117c80-3614-11eb-905c-9e34d5aead37.png)
Upgrade needs to be done manually.
https://github.com/PrestaShopCorp/psgdpr/releases/tag/v1.2.1

**Comment by ghost** [comment]
`If you have already fixed it on your end or if you think you can do it, please do send us a pull request`

I can't do something for this, it's a file from prestashop or addons.prestashop

I don't know if we can ask addons team here

**Comment by eternoendless** [comment]
I can confirm that the latest version is not available on Addons for some reason. We're investigating.

**Comment by matks** [comment]
This has been fixed a week ago 🎉

**Comment by ghost** [comment]
Bump :) this is not fixed

**Comment by okom3pom** [comment]
[Uploading screencapture-ee-wtf-1770-admin647ebehxb-index-php-improve-modules-updates-2020-12-16-10_41_30.pdf…]()

**Comment by ghost** [comment]
[screencapture-ee-wtf-1770-admin647ebehxb-index-php-improve-modules-updates-2020-12-16-10_41_30.pdf](https://github.com/PrestaShop/PrestaShop/files/5701702/screencapture-ee-wtf-1770-admin647ebehxb-index-php-improve-modules-updates-2020-12-16-10_41_30.pdf)

**Comment by matks** [comment]
@okom3pom I install fresh 1.7.8, I install GDPR module v1.2.0 and I have the following display
![Capture d’écran 2020-12-16 à 15 01 49](https://user-images.githubusercontent.com/3830050/102358408-c2811c00-3faf-11eb-9f8c-47d21242db58.png)

**Comment by ghost** [comment]
It's very strange.

No update in 177X?

**Comment by ghost** [comment]
@matks 

I install fresh 1.7.8, an i have the 1.2.1  already installed

![Capture d’écran de 2020-12-16 15-51-23](https://user-images.githubusercontent.com/5064590/102366051-7be3ef80-3fb8-11eb-84bd-b18cdc832bf8.png)

I  install a new fresh 1.7.7.0  and i have the 1.2.1  already installed

![Capture d’écran de 2020-12-16 15-59-08](https://user-images.githubusercontent.com/5064590/102366081-830afd80-3fb8-11eb-8ecc-c3fe21937bf7.png)

The bug is for people  who installed 1.7.7 before the fix i think it's very minor.
