### ISSUE TITLE
500 Error after successful installation of 1.7.7.0 

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#22245]
#### Describe the bug
I have tried twice to do a clean installation of 1.7.7.0 into subdomain test.myshop.com The whole installation was without a single issue or warning, however after the shop is installed, I'm unable to access either FO or BO, receiving error: This page isn’t working test.myshop.com is currently unable to handle this request.
HTTP ERROR 500

I have enabled debug, this is the error: Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 135168 bytes) in /home/yyy/public_html/test/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/FilesystemTrait.php on line 98

I had previously installed 1.7.6.8 in the same subdomain without any issues. So my question is obvious, why was it working fine with 1.7.6.8 and it is not working with 1.7.7.0? As mentioned no warnings prior or after installation!

Also, the admin folder was not renamed after installation, remains /admin

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by SimonGrn** [comment]
Hello @mrabsinthe,

`Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 135168 bytes) in /home/yyy/public_html/test/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/FilesystemTrait.php on line 98`

Looks like a performance issue, you don't seem to have enough memory on your server. How much RAM do you allow for PHP ? If you read the [requirements ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/)we recommend 256 Mo, or if I'm not mistaken 33554432 bytes is 32 Mo, which is significantly lower.

Please check.

Thank you !

**Comment by mrabsinthe** [comment]
Hi @SimonGrn I was caused by RAM, thank you. But my main concern is a/ 1.7.6.8 was running just fine b/ there should be warning at the beginning of installation, don't you think?

**Comment by SimonGrn** [comment]
It was working with 1.7.6.8 because this version was less hungry on RAM. You were probably very, very close because I've never heard of any PrestaShop > 1.7 being able to run with less than 128Mo so I'm kinda skeptical it was the same configuration with 1.7.6.8.
Anyway, I close this issue.

For the warning, we have requirements that people are expected to read. We cannot protect against everything and every configuration people may use, sadly.

Thank you for your understanding.
