### ISSUE TITLE
Upgrade from 1.7.6.9 to 1.7.7.0 – PHP issue

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#22242]
#### Describe the bug

Hello,
How can I safely upgrade prestashop.
First, I updated module autoupgrade to version 4.11.0. and start upgrade:

…
All files upgraded. Now upgrading database...

_[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: " Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.1.3". {"nextQuickInfo":["[SKIP] directory \"\/app\/cache\/\" does not exist and cannot be emptied.","[CLEANING CACHE] File prod removed"],"nextErrors":["[INTERNAL] \/home\/www\/domain.cz\/www\/test.domain.cz\/vendor\/composer\/platform_check.php line 24 - Composer detected issues in your platform: Your Composer dependencies require a PHP version \">= 7.1.3\". You are running 7.0.33-0+deb9u10."],"error":true,"next":"error"}"_

ok, the problem is obvious. I rollback PS and send question my hosting provider about install PHP version 7.1.3 or 7.2.
Answer was, sorry we are not able install this PHP version, because we use OS Debian where was PHP 7.1 and 7.2 dropped (disabled).

PS:  1.7.6.9 support PHP 5.6 – 7.2
PS: 1.7.7.0 support PHP 7.1 – 7.3 but I have 7.0…

How can I update correctly?:

A)
Update PHP on the server to PHP 7.3 (**this PHP is unsupported for PS1.7.6.9**)
and now update PS to 1.7.7.0? or

B)	
Change something in the autoupgrade module for **allow lower PHP** (from supported range)?
update PS 1.7.6.9 to 1.7.7.0
update PHP version on the server from 7.0.33-0+deb9u10 to PHP 7.3

or different way?

Thank you
Best regards

PN

#### Expected behavior

Allow upgrade prestashop from supported PHP versions (1.7.6 support PHP 5.6 – 7.2).
[https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/](url)
#### Steps to Reproduce

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.0.33-0+deb9u10

**Comment by florine2623** [comment]
Hello @PeNov ,

If I understand well, you need to upgrade your shop on 1.7.6.9 to 1.7.7.0.
But PHP 7.2 is not available anymore in your hosting services.

There should be a way in your hosting provider to get PHP 7.2 to work (purchase a time extension of php 7.2 availability). If that's the case you can proceed with the upgrade (of course, you need to do a backup of both DB and files of your shop).

If that is not possible, you will need to get another server do the migration or you can migrate directly on your localhost.

If you need help with your upgrade, please consider one of our [support plans](https://addons.prestashop.com/en/598-migration-upgrade).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks

**Comment by matks** [comment]
@PeNov so today you use php7.0 and your provider says "I cannot provide you php7.1 or php7.2" 😅  your host provider is not nice...

A workaround would be to copy your shop (files + database) into another server with php7.2, perform the upgrade then copy the updated version into your server. For example Ubuntu Bionic is supported until April 2023, and it gives you php7.2

**Comment by PeNov** [comment]
Hi @matks,

yes, it is bad. Hosting provider offer only 7.0 or 7.3. I waited on the PS 1.7.7.0 which fully support PHP 7.3. But I am not able upgrade now by standard way.

Is it possible change something in code for allow lower PHP version?
I think upgrade should available because PS 1.7.6.9 support PHP 7.0 (https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/)

I have more PS installations on the server and upgrade as you mentions is a lot of work :-(.

As second option: I can change PHP to version 7.3 and start upgrades.

What is your opinion?

Start upgrade on the PHP 7.3 with not supported PS 1.7.6.9 or after upgrade PHP to version 7.3 start upgrade PS?

Are you able make test upgrade PS 1.7.6.9 to 1.7.7.0 on the server with PHP 7.3?
Do you know some wrong behaviors (bugs) on PS 1.7.6.9 running on the PHP 7.3?

Thank you
Best regards
PN
