### ISSUE TITLE
BO - Add new Order page - The gift block is not updated when changing the Address - A cart rule "Discount for a country selection" is applied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22243]
#### Describe the bug

_Originally posted here_ : https://github.com/PrestaShop/PrestaShop/pull/21568#issuecomment-734300305
In the BO => Orders => New Order page, the gift block is not updated when changing the Address

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts page
2. Create a cart rule with a country selection "The United States" with an action "Free gift"
3. Go to BO => Orders => Add new order page for "John Doe"
4. Select "Mon address (France country)"
5. add some product to the order
6. try to **edit** the address selected to Country United States / or **select** another address "My address (United states country)"
7. see error => the discount is applied => but the gift is not added to the cart. 

![image](https://user-images.githubusercontent.com/16067358/101157983-4986d980-362b-11eb-97ae-fef49196c587.png)

Similar steps to reproduce the issue

1.Go to BO => Catalog => Discounts page
2. Create a cart rule with a country selection "The United States" with an action "Free gift"
3. Go to BO => Orders => Add new order page for "John Doe"
4. Select the address "My address (United states country)"
5. add some product to the order (the discount well updated)
6. try to **edit** the address selected to Country United States / or **select** another address "(France country)"
7.see error => the discount is removed => but the gift still displayed
![image](https://user-images.githubusercontent.com/16067358/101158018-599eb900-362b-11eb-9b2d-bc4a526889ea.png)

PS1.7.6.9 => ok: https://drive.google.com/file/d/1cdN_PxJZ5299r1hk3iiSrlmqhJ5P34Gp/view

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #22909
