### ISSUE TITLE
1.7.7.0 BO Product Page multiple errors (cannot save)

### ISSUE THREAD

**Issue by OriginNRG** [PrestaShop/PrestaShop#22255]
#### Describe the bug

The product page in BO regardless what type of product shows the details as if its a pack of products. With a wide variety of JS errors in console. I was trying to change the quantity of items in stock and realised it was not saving, then started noticing the issues. 

#### Expected behavior

Change QTY of items, press save, saved

#### Steps to Reproduce

0. Open console
1. Go to product page
2. Click on any product
3. Try to edit anything
4. Try to save the product
5. See error

**Screenshots**

https://i.origin.sh/shot_201204_210835.png

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

* Console Logs
```
form.js?1.7.7.0:1440 Uncaught TypeError: formZoneElem.magnificPopup is not a function
    at form.js?1.7.7.0:1440
    at form.js?1.7.7.0:1536

jquery-3.4.1.min.js:2 jQuery.Deferred exception: $(...).modal is not a function TypeError: $(...).modal is not a function

jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).tokenfield is not a function


jquery-3.4.1.min.js:2 Uncaught Error: No Dropzone found for given element. This is probably because you're trying to access it before Dropzone had the time to initialize. Use the `init` option to setup any additional observers on your Dropzone.
    at Function.u.forElement (main.bundle.js:277)
    at HTMLDocument.<anonymous> (product_page.bundle.js?1.7.7.0:12)
    
form.js?1.7.7.0:634 Uncaught TypeError: Cannot read property 'onSave' of undefined
    at send (form.js?1.7.7.0:634)
    at HTMLButtonElement.<anonymous> (form.js?1.7.7.0:859)
    at HTMLButtonElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.4.1.min.js:2)
```

I've truncated the logs, as theres a tonne of jquery typeerrors for `toolip`, `popover`, `model` etc.

**Comment by matks** [comment]
Hi @OriginNRG so I'm quite sure this comes from a JS issue.

I dont observe this on my 1.7.7.0 shop. Is it a fresh install 1.7.7.0 or did you upgrade? Can you check if clearing the browser cache helps? Do you have modules that customize your Product Page?

**Comment by OriginNRG** [comment]
I did an upgrade @matks and some things did break along the way. I did the usual clearing cache and browser cache. Ive gone through and disabled all modules that might interfere with the product page? There is no module tab on the product page anymore https://i.origin.sh/shot_201204_220517.png

**Comment by matks** [comment]
When I open the Product Page, I can see that for half a second the "Add products to your pack" form appears and then it's replaced by "standard product" Basic Settings. So I can see that, before the JS loads, I see what you have on your screenshot, and then JS loads and shows the right interface.

I am out of ideas now :/ 

But when I google "TypeError: formZoneElem.magnificPopup is not a function" I find this https://www.prestashop.com/forums/topic/620304-js-erors-on-product-edit-page/ which look very close to yoour description

**Comment by OriginNRG** [comment]
Thanks for sharing that post @matks really helpful. Turns out it was an OOD module I need to repurchase. Just unhooked everything from the BOHeader and slowly added everything back. Changing the load order does not solve the issue so guess just incompatible withj 1.7.7.0. 

Shall close as not vanilla related

**Comment by ProteanCode** [comment]
For tryharders - rename the jquery-1.11.min.js in /js directory to jquery-1.11.min.js-juck-fquery

A way around tons of plugins that may be faulty or not
