### ISSUE TITLE
Missing files after update 1.7.6.9 to 1.7.7.0

### ISSUE THREAD

**Issue by Stephane1874** [PrestaShop/PrestaShop#22253]
#### Describe the bug

Hello,

I have updated from 1.7.6.9 to 1.7.7.0 and from the information page it seems to be missing files.

Do I have to add them manually  or is it normal?

**Screenshots**

![Capture](https://user-images.githubusercontent.com/46202635/101197928-05afc680-3663-11eb-9cef-d9b397cd6100.PNG)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.34

**Comment by tklivan** [comment]
I had exact same list. I have reverted to 1.7.6.4 and will reattempt in 24 hours

**Comment by matks** [comment]
Hi, we got multiple reports about this so this is likely to be confirmed.

Good news however: these files are internal to [Composer](https://getcomposer.org/) so PrestaShop does not need them, they just come bundled with it. So there is no issue if you dont have them.

However PrestaShop detects they have changed so it looks like an issue => we need to fix that

**Comment by hibatallahAouadni** [comment]
Hello @straitskapitan 

I didn't manage to reproduce your issue while upgrading from PS1.7.6.9 to PS1.7.7.0, the only issue I encountred is this one #22250

Could you please provide more infos to reproduce the issue, so we could fix it. 

Thansk!

**Comment by Kerami82** [comment]
Hello. I have the same problem. I had this problem also when upgrade to 1.7.6.8 and now when upgrade to 1.7.7.0.
![composer1](https://user-images.githubusercontent.com/37613614/101942560-04921280-3bea-11eb-91ad-2943ad7e0bf2.jpg)
<img width="929" alt="composer" src="https://user-images.githubusercontent.com/37613614/101942562-065bd600-3bea-11eb-9919-8d29f4e03f1b.png">

**Comment by Kerami82** [comment]
Can I copy this files from orginal package of prestashop 1.7.7.0 to my composer folder? or it doesn`t help?

**Comment by hibatallahAouadni** [comment]
> Can I copy this files from orginal package of prestashop 1.7.7.0 to my composer folder? or it doesn`t help?

@matks does copying all these files fix the problem?

**Comment by WartoWiedziec** [comment]
@Kerami82 @hibatallahAouadni 
I did this and the message disappears from the "Information" tab. These files are on the so-called "supply".

**Comment by Kerami82** [comment]
@WartoWiedziec can you tell me where I should looking for this files? I copy this files from vendor/composer/installers/src/Composer/Installers/ form Prestashop 1.7.7.0 folder and it dosnt help.

**Comment by WartoWiedziec** [comment]
@WartoWiedziec can you tell me where I should looking for this files? I copy this files from vendor/composer/installers/src/Composer/Installers/ form Prestashop 1.7.7.0 folder and it dosnt help.

I found them in the installation file after unpacking. Then I copied them to the production folder.

**Comment by Kerami82** [comment]
Now it is ok. Previous when I copy files Total Commander change names to lowercase.

**Comment by hibatallahAouadni** [comment]
Hello @Stephane1874 

Do you still encounter this issue? 
@Kerami82 & @WartoWiedziec  can you confirm that copying files resolve the issue?

Thanks!

**Comment by WartoWiedziec** [comment]
> Hello @Stephane1874
> 
> Do you still encounter this issue?
> @Kerami82 & @WartoWiedziec can you confirm that copying files resolve the issue?
> 
> Thanks!

@Stephane1874 
I can confirm that it helped in my case.

**Comment by hibatallahAouadni** [comment]
Hello @WartoWiedziec 

Thanks for your confirmation!

**Comment by hibatallahAouadni** [comment]
Hello @Stephane1874 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Stephane1874** [comment]
Hello,

thank you @hibatallahAouadni @WartoWiedziec, I added the files manually and everything is fixed.

Thanks

**Comment by musicpanda** [comment]
I had the same problem after an upgrade from 1.7.3 to 1.7.7.4. When I looked closer it appeared that when I compared the upgraded shop with a fresh 1.7.7.4 installation (with Winmerge) there were also quite a few cases where the files had a different content. This concerned several directories under /vendor. 

I ended up replacing the whole vendor directory of the upgrade with that of the fresh installation. This not solved the missing files problem but also another problem.

My guess is that the underlying problem in this case is that the upgrade routine does not or not completely upgrade the /vendor directory.

**Comment by garbus2** [comment]
similar problem occuerd after upgrading from 1.7.7.8 to 1.7.7.9:

Missing files (7)

    vendor/composer/installers/phpstan.neon.dist
    vendor/composer/installers/src/Composer/Installers/MiaoxingInstaller.php
    vendor/composer/installers/src/Composer/Installers/WinterInstaller.php
    vendor/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php
    vendor/composer/installers/src/Composer/Installers/ProcessWireInstaller.php
    vendor/composer/installers/src/Composer/Installers/StarbugInstaller.php
    vendor/composer/installers/src/Composer/Installers/PantheonInstaller.php

Updated files (10)

    vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
    vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
    vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
    vendor/composer/installers/src/Composer/Installers/Installer.php
    vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
    vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
    vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
    vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
    vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
    vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
