### ISSUE TITLE
Translation for email in nrtsociallogin-account, editor not work for 1.7.4.4

### ISSUE THREAD

**Issue by BigBro25** [PrestaShop/PrestaShop#22256]
#### Describe the bug

Nrtsociallogin-account, editor not work for 1.7.4.4, is 2 section with same name ( nrtsociallogin-account and Default email messages-account), wysiwyg not working for nrtsociallogin-account the problem occurs for both themes and core emails!

#### Expected behavior

I expected to be able to edit the email.

#### Steps to Reproduce

1. Go to 'BO'
2. Click on 'email Translation'
3. Scroll down to 'your theme or core, does not matter'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![Editor-problem](https://user-images.githubusercontent.com/75504407/101217042-4de1df80-3689-11eb-8d3f-26f11684eeeb.jpg)

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: PHP 7.1

**Comment by matks** [comment]
Hi, what is Nrtsociallogin-account ? it looks like a 3rd party module

If you have questions about a PrestaShop module or theme you have downloaded or bought on the PrestaShop Addons Marketplace, you can contact its developers through the link provided on their Marketplace page. We cannot help you with a module that is outside of this project scope.

**Comment by BigBro25** [comment]
I understand, so it's not a module of prestashop core?
Yes, I have installed a theme where I encounter the problem.
In this case there is no problem, I will ask the theme developer.

Thank you very much!

**Comment by matks** [comment]
Indeed the theme developer is responsible for its code. He might not have done the necessary steps to make sure it is compliant with PS 1.7.4.4 . But he should 😄 else he'll lose business!
