### ISSUE TITLE
Wrong entry in the must_have_modules_list.xml file => error updating modules

### ISSUE THREAD

**Issue by IJVo** [PrestaShop/PrestaShop#22267]
The file must_have_modules_list.xml contains the entry of the module 'id' = 29992, which does not have the field 'name' filled in. Because of this, any module update crashes. Please fix it.

The error is reflected in the class ModuleCore function getModulesOnDisk() where $modaddons->name from the $xml file is not checked.
This calls with an error when calling Module::isModuleTrusted(), which calls Module::checkModuleFromAddonsApi(), which calls Module::getInstanceByName ($ module_name).
There it will be a error.
Please fix it. Thank you.

**Comment by IJVo** [comment]
In the class ModuleCore, add after 
```
if ($xml && isset($xml->module)) {
    foreach ($xml->module as $modaddons) {

```        
    this code
    
```
        if (($modaddons->name == '') || (!Validate::isModuleName($modaddons->name))) {
            continue;
        }

```

**Comment by matks** [comment]
Hi @IJVo thank you for the bug report! We are going to fix this misconfiguration.

However I dont understand

> Because of this, any module update crashes. Please fix it.

I just upgraded 2 modules in my PS 1.7.7.0 shop without issues.  Maybe only some modules do crash, if they meet some requirements?

**Comment by IJVo** [comment]
This will only take effect if the PrestaShop administrator is logged in to Addons and the updated file containing the error is downloaded.

**Comment by leekung** [comment]
When in dev mode, the ModuleCore throw error and die, this error prevent any module to upgrade. even if the upgrading module doesn't have any error.

```
    public static function getInstanceByName($module_name)
    {
        if (!Validate::isModuleName($module_name)) {
            if (_PS_MODE_DEV_) {
                die(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', array(Tools::safeOutput($module_name)), 'Admin.Modules.Notification')));
            }
            return false;
        }

```

**Comment by matks** [comment]
Hi everybody, the issue in must_have_modules_list.xml has been fixed. Be aware that this file is stored in cache by your shop so you need to clear it, and PrestaShop will download the new (fixed) version 😉

**Comment by hibatallahAouadni** [comment]
Hello @leekung 

Thanks @matks for your quick replies and fix :wink: 

@leekung it seems your issue is fixed.
So I close this issue, feel free to open a new one if you encounter another problem.

Thanks!
