### ISSUE TITLE
Availability preferences is edited in All Shop mode and shouldn't be.

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#22261]
Hi... My multishop with shared quantity become everyday a biggest nightmare.. They is bugs everywhere.
then, I finally found the reason of a bug I got from a long time about Availability preferences.

So, with prestashop 1.7.6.8 : You can only access to stock if you are in a special shop (not all shop).
The problem occurs in availability preferences of a product : "default" or "accept orders" is selected.
If i edit the product and click on save from the secifical shop, no problem.
However, If i edit the product from "all shop", then the availibility preferences is modified as "refuse" become selected.

**If there anyway to remove the multishop once it's activated ???? Or could it create more problem ?**

<img width="1893" alt="Capture d’écran 2020-12-05 à 11 17 04" src="https://user-images.githubusercontent.com/43704805/101240023-ca59da00-36ec-11eb-808e-d6639c27f0db.png">

**Comment by SimonGrn** [comment]
Hello @passio777x 

I am very curious as to why you don't want to follow the issue template. This is not the first time if I recall correctly. Is there a good reason ?
Everybody lose time when we have to ask you the informations you should give when you follow the template. Could you please think about the people who will have to look into your issue and try to fix them, for free ?
Thank you in advance.

Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
