### ISSUE TITLE
 I can't see the orders after updating to Prestashop 1.7.7.0 - Unable to load template file helpers Twig

### ISSUE THREAD

**Issue by Fer5320** [PrestaShop/PrestaShop#22266]
After updating to Prestashop 1.7.7.0 from 1.7.6.9 I cannot see the orders, since I get this error
An exception has been thrown during the rendering of a template ("Unable to load template 'file: helpers / list / list_header.tpl '").
[Twig \ Error \ RuntimeError 0]

Does anyone know how it can be solved? I had to reinstall version 1.7.6.9
Thanks

**Comment by matks** [comment]
Do you have modules hooked on Order page?

**Comment by SimonGrn** [comment]
Hello @Fer5320 
could you please think about following the template for issue ?
We don't have precise steps or informations about your environment !

We usually close issues when people don't follow the template but we'll make an exception because it's about the update.

Thank you for your understanding.

**Comment by Fer5320** [comment]
> Do you have modules hooked on Order page?

I have these modules in the hooks:
DisplayOrderConfirmation: Paypal, Google Analytics, Easy Google Customer Reviews y WhatsApp Chat
DisplayOrderConfirmation1: Paypal
DisplayOrderConfirmation2: Customer Reassurance

Thanks!

**Comment by matthieu-rolland** [comment]
Could you disable these modules, and see if your orders appear again ? Then, if it does come from a module: re-enable those modules one by one to see which one is breaking the order page ?

**Comment by hibatallahAouadni** [comment]
Hello @Fer5320 

Could you please follow the steps listed by @matthieu-rolland above, and check if the problem is launched by a module.

Thanks!

**Comment by tenenick** [comment]
Hi @Fer5320:
Please check if  you have the following folder in your install: 
/your root folder/Backoffice/themes/new-theme//template/helpers.
If not copy it fromhere and btw all the other eventually missing folders and files:
/your root folder/Backoffice/themes/default//template/helpers
Hope it does it.
Regards

**Comment by hibatallahAouadni** [comment]
Hello @tenenick 

Thanks for your contribution and your reply :wink: 
We hope your quick fix helps @Fer5320 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Fer5320  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
