### ISSUE TITLE
Cart totals and tax fix needed for US vendors who must charge tax on shipping

### ISSUE THREAD

**Issue by ForagerFinds** [PrestaShop/PrestaShop#22268]
Using Ver. 1.6.1.24 , default template, shop fully functional, over 100 products. I like the program generally. Closing many sales with PayPal. There are two shopping cart problems I cannot overcome:
1) Tax computes properly to the "Tax" line, but it is not added to the "TOTAL" line, so when the order arrives at the customer's paypal it is higher than the "TOTAL" reflected in the cart.

2) In NY we have to charge tax on shipping, but here's the problem. When tax is enabled on a carrier it is computed properly and added to the "tax" line total, but when the order arrives at the customer's paypal the tax on shipping has been doubled, and the cost of shipping reflected on the Paypal receipt is higher by the amount of tax on shipping. I.E. Shipping is $4.40 but appears as $4.76 on the paypal receipt. The total charged is also 36 cents higher than it should be. The 36 cents extra being the tax on the shipping that's charged twice. ($4.40 x .0825 = .36)
![2presta-bug](https://user-images.githubusercontent.com/75579199/101290235-e5047f80-37ce-11eb-96db-3a4a219db544.jpg)
In the example above "product" + "shipping" = $19.40. "tax" = 19.40 x .0825 = 1.60 so the "TOTAL" should read $21.00 and that should be the amount that paypal will charge, but somehow an additional 36 cents is added. (4.40 x .0825 = .36) 
The 2nd graphic shows the amount that PayPal wants to charge. Of course the larger the amounts, the larger the error will be.
![1presta-bug](https://user-images.githubusercontent.com/75579199/101290234-e46be900-37ce-11eb-8341-236da180fee4.jpg)
This would be an extremely beneficial repair to users in big cities like NYC. 
If the issues can be addressed I would also suggest changing the first "Total" to read "Sub-Total" instead.
Then you'd show the sub-total of "product cost" + "shipping cost" and then "TOTAL" would be the "sub-total" + "tax"
The resulting total would be the same as what the customer then expects to see in PayPal.
Thanks for considering. If it can't be fixed I will have to abandon prestashop. From looking at your forums I have also seen others who have abandoned it for similar reasons.

**Comment by SimonGrn** [comment]
Hello @ForagerFinds 

PrestaShop 1.6 is no longer supported. You can read more [here](https://build.prestashop.com/news/1.6.1.x-what-s-next/).

I close this issue as we cannot do anything more here. Thank you for your understanding.

**Comment by ForagerFinds** [comment]
Thank you for the reply. Do you know if any of the issues were dealt with in version 1.7?
