### ISSUE TITLE
Payment Step not working....

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#22276]
Customers end up using chat as after they..
1) place an order
2) create acount
3) add address
4) Choose shipping option
instead of moving to next step which is payment option i get the following page
Which is a page for the client to check his info or return back to shopping..
![Untitled-2](https://user-images.githubusercontent.com/53015902/101375612-481e1100-38b8-11eb-9885-870cff49eb24.jpg)

What is going on guys ... this update has toooo many bugs!!
My prestashop version is 1.7.7 PHP: 7.3.23
Activating debug mode i get the followng error..

#########################################

(1/1) FatalThrowableErrorType error: Argument 1 passed to PrestaShop\PrestaShop\Core\Payment\PaymentOption::convertLegacyOption() must be of the type array, string given
--
in PaymentOption.php line 337
at PaymentOption::convertLegacyOption('')
at array_map(array('PrestaShop\\PrestaShop\\Core\\Payment\\PaymentOption', 'convertLegacyOption'), array('paypal' => ''))in PaymentOptionsFinder.php line 46
at PaymentOptionsFinderCore->find()in PaymentOptionsFinder.php line 82
at PaymentOptionsFinderCore->present(false)in CheckoutPaymentStep.php line 87
at CheckoutPaymentStepCore->render(array('identifier' => 'checkout-payment-step', 'position' => 4, 'ui' => object(RenderableProxy)))in RenderableProxy.php line 52
at RenderableProxy->render(array('identifier' => 'checkout-payment-step', 'position' => 4, 'ui' => object(RenderableProxy)))in smartyfront.config.inc.php line 98
at smartyRender(array('identifier' => 'checkout-payment-step', 'position' => 4, 'ui' => object(RenderableProxy)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyRender', array(array('identifier' => 'checkout-payment-step', 'position' => 4, 'ui' => object(RenderableProxy)), object(SmartyDevTemplate)))in f2a55a7fc9e5236d44df137c0d31313883329ffd_2.file.checkout-process.tpl.php line 28
at content_5fce54ab5b4087_48228955(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in CheckoutProcess.php line 112
at CheckoutProcessCore->render(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)))in RenderableProxy.php line 52
at RenderableProxy->render(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)))in smartyfront.config.inc.php line 98
at smartyRender(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyRender', array(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)), object(SmartyDevTemplate)))in 959ca7b63d850f8cefa3af4ad1f14223a26ca7ca_2.file.checkout.tpl.php line 178
at Block_16838936005fce54ab586344_84298612->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_16838936005fce54ab586344_84298612), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_16838936005fce54ab586344_84298612))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_16838936005fce54ab586344_84298612', 'cart_summary', 4)in 959ca7b63d850f8cefa3af4ad1f14223a26ca7ca_2.file.checkout.tpl.php line 217
at Block_2236328035fce54ab585f07_39364047->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_2236328035fce54ab585f07_39364047), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_2236328035fce54ab585f07_39364047))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_2236328035fce54ab585f07_39364047', 'content')in 959ca7b63d850f8cefa3af4ad1f14223a26ca7ca_2.file.checkout.tpl.php line 71
at content_5fce54ab58bd11_14497542(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('checkout/checkout.tpl', null, 'MegaShoplayouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 116
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'checkout/checkout.tpl')in 6a1a17dc2b06281ca713b7626fe8520f77e07a91_2.file.hookDisplayOverrideTemplateFooter.tpl.php line 31
at content_5fce54ab571a63_34376056(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'MegaShoplayouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('modules/ps_legalcompliance/views/templates/hook/hookDisplayOverrideTemplateFooter.tpl', null, 'MegaShoplayouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('modules/ps_legalcompliance/views/templates/hook/hookDisplayOverrideTemplateFooter.tpl', null, 'MegaShoplayouts/layout-full-width.tpl')in FrontController.php line 704
at FrontControllerCore->smartyOutputContent('modules/ps_legalcompliance/views/templates/hook/hookDisplayOverrideTemplateFooter.tpl')in FrontController.php line 686
at FrontControllerCore->display()in Controller.php line 326
at ControllerCore->run()in Dispatcher.php line 518
at DispatcherCore->dispatch()in index.php line 28

#####################################

**Comment by DPStudioGR** [comment]
I also deactivated paypal and the error was cleared and payment options were available (without paypal)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
