### ISSUE TITLE
Payment step not working

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#22273]
Customers end up using chat as after they..
1) place an order
2) create acount
3) add address
4) Choose shipping option 
instead of moving to next step which is payment option i get the following page 
Which is a page for the client to check his info or return back to shopping..
![Untitled-2](https://user-images.githubusercontent.com/53015902/101361454-a989b400-38a7-11eb-92c2-b05ac71a0e9a.jpg)

What is going on guys ... this update has toooo many bugs!!

**Comment by hibatallahAouadni** [comment]
Hello @Stampa-Stampa 

Could you please provide your **PS** version and **PHP** version. And if you upgraded your shop to 1.7.7.0, please provide your old version PS.
Please next time **follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by knopfen** [comment]
I have the same issue. It seems to be a problem of the PayPal Module / AddOn … after deactivating it, the check out process works fine - well, without offering PayPal as payment method - which is bad.
(Prestashop 1.7.6.4 and 1.7.7.0, Multishop, PayPal Module v5.3.0, PHP 7.3)

**Comment by SimonGrn** [comment]
Hello @Stampa-Stampa,
You're still not following the template. Please follow the template so we can get all the informations we need at first glance.

I close this issue, please be aware we will not be accepting more issue like this.

Thank you for your understanding.

**Comment by matks** [comment]
> Customers end up using chat as after they..
> 
> 1. place an order

> What is going on guys ... this update has toooo many bugs!!

Well, we released a [Beta 1](https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/) then a [Beta 2](https://build.prestashop.com/news/prestashop-1-7-7-0-beta2-release/) then a [Release Candidate 1](https://build.prestashop.com/news/prestashop-1-7-7-0-rc-release/) over half a year so that everybody could test this version and tell us about the bugs ... looks like it was not enough 😅 

Did you test the Beta 1, the Beta 2 and the RC 1 ?
