### ISSUE TITLE
Error Upgrading from 1.6.1.24 to 1.7.7.0 - PrestaShopObjectNotFoundException: The hook id does not exist

### ISSUE THREAD

**Issue by meirrod** [PrestaShop/PrestaShop#22279]
Hi,
I tried to upgrade using the devdocs migration 1.7 guide, executing the steps as mentioned. I solved some errors before regarding the missing table ps_translation which i inserted without any content. Then relauching  **php install/upgrade/upgrade.php** produce:

PHP Fatal error:  Uncaught PrestaShopObjectNotFoundException: The hook id #%s does not exist in database in /var/www/html/classes/Hook.php:225
Stack trace:
#0 /var/www/html/classes/Hook.php(658): HookCore::getNameById(0)
#1 /var/www/html/classes/module/Module.php(1000): HookCore::unregisterHook(Object(BankWire), 0, NULL)
#2 /var/www/html/classes/module/Module.php(712): ModuleCore->unregisterHook(0)
#3 /var/www/html/classes/PaymentModule.php(92): ModuleCore->uninstall()
#4 /var/www/html/modules/bankwire/bankwire.php(91): PaymentModuleCore->uninstall()
#5 /var/www/html/src/Adapter/Module/Module.php(267): BankWire->uninstall()
#6 /var/www/html/src/PrestaShopBundle/Install/Upgrade.php(568): PrestaShop\PrestaShop\Adapter\Module\Module->onUninstall()
#7 /var/www/html/src/PrestaShopBundle/Install/Upgrade.php(820): PrestaShopBundle\Install\Upgrade->disableIncompatibleModules()
#8 /var/www/html/install/upgrade/upgrade.php(93): PrestaShopBundle\Install\Upgrade->run()
#9 {main}
  thrown in /var/www/html/classes/Hook.php on line 225

Thank you for your help.

PHP: 7.2.24
MARIADB: 10.5.6-MariaDB
PS: 1.6.1.24

**Comment by hibatallahAouadni** [comment]
Hello @meirrod 

It seems your issue is duplicate to this one #22237
Could you please check and feedback.

PS: please next time **follow the template to submit a complete bug report**.

Thanks!

**Comment by matks** [comment]
Hi, the stack trace seems to indicate the process fails to uninstall module [Bankwire](https://github.com/prestashop/bankwire).

The module [bankwire](https://github.com/prestashop/bankwire) has been rebuilt for PS 1.7 (so there's a new module) and I dont think it was built with php7.2 compatibility (PS 1.6.1.24 is not supposed to run with php7.2 either). I suggest to uninstall it before performing the upgrade.

As PS 1.6.1.24 is not supposed to run with php7.2, I think it would be more safe to use php7.1 to perform the upgrade, to be sure this does not bring php compatibility issues in this quite complex process.

**Comment by hibatallahAouadni** [comment]
Hello @meirrod  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
