### ISSUE TITLE
Error updating from 1.7.6.5 to 1.7.7

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#22281]
Hi, after updating from 1.7.6.5 to 1.7.7, the module manager stop working, no error during update, no error on logs, no error on PHP

-if you try to update a module -> not work, start working, never ends
-if your try to upload a module -> not working, select file link or drop the module on the windows 
-BackOffice very slow
-update tab -> not working

PHP V. 7.2
Server : Apache - Litespeed with CPanel

**Comment by tklivan** [comment]
Things maybe you can check.

- Check for ownership issues on cache directory.
- Check db to make sure the two new session tables (in 1.7.6.6) was created.

**Comment by msaustral** [comment]
Hi file ownership or cache, is not the problem, we had to update to 1.7.6.9 without problem.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
