### ISSUE TITLE
Prestashop 1.7.7.0 Admin login page only showing Store name

### ISSUE THREAD

**Issue by fjoralbmuca** [PrestaShop/PrestaShop#22286]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
![Capture](https://user-images.githubusercontent.com/46874375/101482762-76066280-3957-11eb-82e2-510dc5208ed6.JPG)

**Comment by fjoralbmuca** [comment]
php version 7.3

**Comment by matks** [comment]
@fjoralbmuca new shop or did you upgrade?

Note: issue reported by 2 other people.

**Comment by fjoralbmuca** [comment]
new shop
manually installed

**Comment by SimonGrn** [comment]
Hi @fjoralbmuca,

please edit your first post and fill the corresponding sections by replacing the text. Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @fjoralbmuca 

I didn't manage to reproduce your issue with fresh install PS1.7.7.0 and my PHP version is 7.2, see the attched screenshot below:

![image](https://user-images.githubusercontent.com/23308427/101512455-5123e680-397b-11eb-97cb-c93bb7eab525.png)

Could you please provide more infos to reproduce the issue.
Like @SimonGrn mentioned above please **fill the corresponding sections**, cause without these infos, we can not help you.

Thanks!

**Comment by fjoralbmuca** [comment]
Resolved, SQL database issue

**Comment by hibatallahAouadni** [comment]
Hello @fjoralbmuca 

Thanks for your feedback!
So, I close the issue.

**Comment by SimonGrn** [comment]
Thank you ! I close this issue.

**Comment by matks** [comment]
Hi @fjoralbmuca that is great to know!

Could you please tell us what was the issue?

**Comment by fjoralbmuca** [comment]
SQL Database was not connected on the third step of prestashop installing
