### ISSUE TITLE
After click on the left arrow starts auto infiniti scroll of thumbnails on the product page in Crome browser  

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#22287]
When i click on the left arrow starts auto infiniti scroll of thumbnails on the product page in Crome browser.
I recorded a video with a bug in the Google Chrome browser:
 https://www.awesomescreenshot.com/video/1996036?key=f624e14fe78b2b7b7801a302ad54f942

PrestaShop 1.7.7.0 and previous version 1.7 too.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
