### ISSUE TITLE
I have installed, deleted, and reinstalled prestashop 6 times and admin will not load

### ISSUE THREAD

**Issue by simondavidson1970** [PrestaShop/PrestaShop#22307]
I have installed, deleted, and reinstalled prestashop 6 times and admin will not load

when I go to the admin page, I get the box to enter user name and password, once I have punched this in and hit enter, it goes to a page with the penguin on and a box around it, and nothing else..

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots** You can see a screenshot of the page I end up with after trying to log into the admin.
[Screenshot](http://classictypewriters.com/images/prestashop.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.0

**Comment by matks** [comment]
Hello @simondavidson1970 is it the same issue that https://github.com/PrestaShop/PrestaShop/issues/22300 ?

If yes, solution seems to be that your PHP comes with an outdated version of ICU (I see you use php7.0 so this seems likely). I suggest using newer version of PHP (php7.3 for example) with an up-to-date version of ICU

**Comment by simondavidson1970** [comment]
I uninstalled prestashop, changed to PHP 7.3, tried to re-install and now I get this error message

**_The following errors were found :**

**Unable to generate new_cookie_key, hence can not install Prestashop 1.7_**

**Comment by simondavidson1970** [comment]
so I reverted back to the original PHP as it screwed up the wordpress website that I am currently using... 

I was trying to install prestashop in a sub folder

**Comment by hibatallahAouadni** [comment]
Hello @simondavidson1970 

**Please follow the template to submit a complete bug report**.
We need these infos to help you!

As @matks said, your issue is duplicate to #22300 
> tried to re-install and now I get this error message

You mean fresh install of PS1.7.7.0?

Thanks!

**Comment by BaraqdaPL** [comment]
If you have a shop under subdomen you can add domain with your hosting provider (I had same issue, where my company page was on lower php and subdomain shop on higher - it did not work like this) So I added new domain in my hosting company as my subdomain name. Now, in hosting panel I have two domains - one main domain, second is my subdomain. After doing it, I can set up different php to my main page and different php to shop.

**Comment by hibatallahAouadni** [comment]
Hello @simondavidson1970  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: Thanks @BaraqdaPL for your quick reply :wink: Hope your tip could help @simondavidson1970 

Thanks!
