### ISSUE TITLE
Rules tax issue

### ISSUE THREAD

**Issue by massha** [PrestaShop/PrestaShop#22305]
#### 

When I set up the VAT rules on the BO , it applies only one rule ( french one ) 

#### Expected behavior

When I buy something , with an monegasque adresse , I'm supposed to get 20% of VAT but I have no VAT .. 

#### Steps to Reproduce

1. Go to 'International '
2. Click on 'Taxes'
3. Scroll down to 'Monaco'

![image](https://user-images.githubusercontent.com/48324964/101631448-9ea85e00-3a24-11eb-8abb-5586c56e484d.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @massha 

Could you please change the issue title in English, cause **English is the norm on GitHub**.
I didn't manage to reproduce your issue with PS1.7.6.9, see the attached screen record below:

https://drive.google.com/file/d/1nmaUyAjiPf5j4q7wHKIAwRmrS2_Fp6Og/view

Please check and feedback.

Thanks!

**Comment by massha** [comment]
Thanks a lot

But we are obliged to set only ONE rule tax for the products ?

If I am in France , I have to pay 20% of VAT , like in Monaco
But if I set up French rules , it won't apply it with a monagasque adress ,
and it is an issue

[image: image.png]
[image: image.png]

**Comment by hibatallahAouadni** [comment]
Hello @massha 

The link of the attached images is broken :confused: 
And could you please provide clear steps to reproduce your issue.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @massha  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
