### ISSUE TITLE
Cannot login to BO after update from 1.7.6.5 to 1.7.7.0 with ICU < 4.6

### ISSUE THREAD

**Issue by BaraqdaPL** [PrestaShop/PrestaShop#22300]
Hi,
I've just update my PS. Before there was no problem. Now, after putting my mail and password, I see blank page. 
What could go wrong?
During update, there was no errors (I used 1- click). Then system asked me to reboot and log in again. And now there is no response.
![image](https://user-images.githubusercontent.com/75696855/101534756-ed5be680-3997-11eb-96da-8c12faa5c25a.png)
I've seen some topics to check SQL base to check if there is no missing 
ps_employee_session but there are...
After chcecing website, it shows error 500. In some more deep information, problem might be connected with jquery-3.4.1.min.js
?
What might be a solution?

**Comment by BaraqdaPL** [comment]
on website console:
```
pl/adminszefu/index.php?rand=              500
send @ jquery-3.4.1.min.js:2
ajax @ jquery-3.4.1.min.js:2
(anonymous) @ login.js?v=1.7.7.0:186
r.complete @ jquery-3.4.1.min.js:2
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
u @ jquery-3.4.1.min.js:2
k.fx.tick @ jquery-3.4.1.min.js:2
lt @ jquery-3.4.1.min.js:2
k.fx.start @ jquery-3.4.1.min.js:2
k.fx.timer @ jquery-3.4.1.min.js:2
dt @ jquery-3.4.1.min.js:2
a @ jquery-3.4.1.min.js:2
dequeue @ jquery-3.4.1.min.js:2
(anonymous) @ jquery-3.4.1.min.js:2
each @ jquery-3.4.1.min.js:2
each @ jquery-3.4.1.min.js:2
queue @ jquery-3.4.1.min.js:2
animate @ jquery-3.4.1.min.js:2
k.fn.<computed> @ jquery-3.4.1.min.js:2
doAjaxLogin @ login.js?v=1.7.7.0:185
submitHandler @ login.js?v=1.7.7.0:14
s @ jquery.validate.js:2
(anonymous) @ jquery.validate.js:2
dispatch @ jquery-3.4.1.min.js:2
v.handle @ jquery-3.4.1.min.js:2
```

**Comment by matks** [comment]
@BaraqdaPL could you give us a screenshot of your console error?

By the way someone reported a similar issue on https://github.com/PrestaShop/PrestaShop/issues/22286 and said it was a database issue.

**Comment by JBWModules** [comment]
This issue is reported by a lot of people in multiple threads in the forum e.g.
https://www.prestashop.com/forums/topic/1037764-upgrade-1765-to-1770-failed-cannot-log-into-admin/

**Comment by hibatallahAouadni** [comment]
Hello @BaraqdaPL 

We need your PHP version, database (MariaDB or MySQL) version.
And could you please attach your log file, you can find it under your admin folder in your PrestaShop project:

**`admin > autoupgrade > tmp > log.txt`**

We need these informations to figure out the cause of your issue.

Thanks!

**Comment by BaraqdaPL** [comment]
![image](https://user-images.githubusercontent.com/75696855/101605379-642dc980-3a02-11eb-8c7b-ffbcac8e1e4e.png)
![image](https://user-images.githubusercontent.com/75696855/101605444-760f6c80-3a02-11eb-8204-59bdfe123a9c.png)
PHP 7.2
MySQL
my log : https://drive.google.com/file/d/1r1eLj_vAqfbQLIviRPS5u70VWF2UgPOK/view?usp=sharing

**Comment by BaraqdaPL** [comment]
> @BaraqdaPL could you give us a screenshot of your console error?
> 
> By the way someone reported a similar issue on #22286 and said it was a database issue.

I was not changing anything with database. It was upgrade not new install.

**Comment by BaraqdaPL** [comment]
My dev.log after login attempt:

```
[2020-12-09 09:56:13] doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []
[2020-12-09 09:56:13] translation.WARNING: Translation not found. {"id":"PrestaShop Marketplace in your Back Office","domain":"messages","locale":"pl-PL"} []
[2020-12-09 09:56:13] translation.WARNING: Translation not found. {"id":"Discover the best PrestaShop modules to optimize your online store.","domain":"messages","locale":"pl-PL"} []
[2020-12-09 09:56:35] doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []
[2020-12-09 09:56:35] php.CRITICAL: Type error: idn_to_utf8() expects parameter 3 to be integer, string given {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: idn_to_utf8() expects parameter 3 to be integer, string given at /home/ceram3/domains/ceramizer.pl/public_html/sklep/src/Core/Util/InternationalizedDomainNameConverter.php:47)"} []
[2020-12-09 09:56:35] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: idn_to_utf8() expects parameter 3 to be integer, string given" at /home/ceram3/domains/ceramizer.pl/public_html/sklep/src/Core/Util/InternationalizedDomainNameConverter.php line 47 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: idn_to_utf8() expects parameter 3 to be integer, string given at /home/ceram3/domains/ceramizer.pl/public_html/sklep/src/Core/Util/InternationalizedDomainNameConverter.php:47)"} [] 
```

I'm not a CODE guy and I don't understand what I need to fix...

**Comment by hibatallahAouadni** [comment]
Thanks @BaraqdaPL 

Ping @PrestaShop/prestashop-core-developers Could someone check what is the issue's source :pray:

**Comment by matks** [comment]
This error `idn_to_utf8 ()` was also mentioned on [Build](https://build.prestashop.com/news/prestashop-1-7-7-0-available/#comment-5175549340)

**Comment by matks** [comment]
@BaraqdaPL Can you tell us what hosting provider you use, and if you are using http or https?

**Comment by BaraqdaPL** [comment]
So, I tryed https:// ... nothing have changed

My hosting provider - https://cyberfolks.pl/

In my case both http and https should work.
My main company site works on php 5.6.31, but subdomen with shop is set up in 7.2.11 php

**Comment by matks** [comment]
So if we look at the code of [InternationalizedDomainNameConverter.php](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.0/src/Core/Util/InternationalizedDomainNameConverter.php) we see
```
        return $parts[0] . '@' . idn_to_utf8($parts[1], 0, INTL_IDNA_VARIANT_UTS46);
```

Error says ` Type error: idn_to_utf8() expects parameter 3 to be integer, string given` which means it thinks `INTL_IDNA_VARIANT_UTS46` is a string, not an integer.

The root cause might be what is discussed in https://github.com/guzzle/guzzle/issues/2448 : a version of ICU too old that does not provide this constant.

**Comment by BaraqdaPL** [comment]
OMG i read but not understand... I'm not a skill IT. 
So it might be a problem with hosting setup of a shop domen?

**Comment by matks** [comment]
@BaraqdaPL is it possible for you to check the **[ICU](http://site.icu-project.org/home) version of your hosting setup**?

**Comment by BaraqdaPL** [comment]
will try to find it

**Comment by BaraqdaPL** [comment]
ICU version => 4.4.1
--
ICU Data version => 4.4.0.1
ICU TZData version => 2010i
ICU Unicode version => 5.2

**Comment by BaraqdaPL** [comment]
OK -problem solved - PHP version.
I switch to php 7.3

ICU version => 58.2
--
ICU Data version => 58.2
ICU TZData version => 2016j
ICU Unicode version => 9.0

and now is working!!!

Thank you for tips

**Comment by matks** [comment]
@BaraqdaPL great to know! indeed if ICU is below 4.6 there's a known issue. In theory modern hosting environments have an ICU version way higher, but some old environments are stuck with outdated ICU.

**Comment by BaraqdaPL** [comment]
I'm checking shop. Why I have problem with module presta shop?
![image](https://user-images.githubusercontent.com/75696855/101637249-cbf90a00-3a2c-11eb-85e1-ba000ee9e01b.png)
Is there any other traps I can find in 1.7.7.0? I thought, that releasing new version everything will be checked...

**Comment by matks** [comment]
@PrestaShop/qa-functional Would it be possible to test 1.7.7 with a php7.1 with ICU < 4.6 to validate it is impossible to login (then we can make a fix)?

**Comment by BaraqdaPL** [comment]
Ive chcecked - with php 7.1 

version => 1.1.0
--
ICU version => 4.4.1
ICU Data version => 4.4.0.1

page not load - BO is not working

**Comment by BaraqdaPL** [comment]
Now is not working adding pictures to product.
Buttons are not active (after click - nothing happens). Drag&drop also not working...
why I made this update :( is there any safe way to downgrade it back - this version is a mess...
![image](https://user-images.githubusercontent.com/75696855/101646687-2186e400-3a38-11eb-88b6-143338ad27c4.png)

**Comment by BaraqdaPL** [comment]
Why I cannot go back to previous version usin 1-ckick? (button powrót "return" is not active)...

**Comment by BaraqdaPL** [comment]
![image](https://user-images.githubusercontent.com/75696855/101655439-e8ec0800-3a41-11eb-90a0-6633f85097ac.png)

**Comment by SimonGrn** [comment]
Hello @BaraqdaPL,
You can use the backup you made before upgrading.
Also please try not to spam multiple messages, use only one, thank you.
>this version is a mess

We tried dozen of upgrades from differents versions to 1.7.7.0 without any trouble. The only thing we cannot test is the different configurations merchants can have, with 3rd-party modules or custom code modification. Theses installations can easily break because sometime 3rd-party developers don't follow good practices.

Also did you take some time to test the 2 beta versions we released, and the RC one month ago ? That could have helped this Open Source project find this bug.

**Comment by BaraqdaPL** [comment]
My college made an update by coping all files from shop FTP catalogue, but I think just copy/paste those files won't work.
Also, as I wrote before 1-click don't aloud me to backup from data backup during upgrade. 
Sorry - I'm not developer. I'm just trying to manage company shop page as good as I can. I wanted to install newest stable version to proceed with lots of other setups (products, layouts etc). I did not expect any troubles with "tested" version. 
I hope it's just a small change to be done to work perfect, but each time I click something in BO its shows some troubles (as mention few post before ...such as unable to add a picture to a product?). 
Is there anything more to do/check to made my shop at list same efficient and smooth as my previous version 1.7.6.5 ?  
Is upgrading it now to 1.7.7.0.1 would be a good idea?
Also I'm not an specialize IT guy so I won't be much help to you all. 
Sorry for my multiposts - I'm so excited during this update and my company/producer shop need to be fully operational ASAP (pression) thats why I'm putting it maybe in haotic way

**Comment by SimonGrn** [comment]
Hello,

when I said
>You can use the backup you made before upgrading.

I meant the backup you made yourself. As far as I know the module strongly advise you to do so ?
To make a complete backup you need all the files and the database.

This is an Open Source project, meaning everyone can and should help. We have limited firepower, we cannot fix everything and test everything, so we warmly welcome any contribution (code, test, documentation, etc).

>Sorry - I'm not developer

PrestaShop is not a "simple software", despite what people can tell, and it's not a bad idea to have a dedicated person to ask for support (freelance specialist, web agency, etc) so you can outsource this kind of operation.

As far as I can tell, your problems are probably tied to some modules or some modifications made that prevent the upgrade to work properly. We test upgrading with "simple" shops as we cannot test every configuration and we can only guarantee the upgrade works with a vanilla installation (no 3rd-party modules for example), because we don't control their code. We make our maximum to "protect" the upgrade process, by verifying the environment and the libraries and such but it's a gigantic task and sadly some things pass through.

We although welcome any help to improve this project, as for a reminder it is totally free.

**Comment by BaraqdaPL** [comment]
I think problem with adding pictures to products from BO or missing prestashop module shop, from BO, is not a third party modules installed...
I'm fully appreciated all developers creating this project and I'm far of blaming anyone. I just need to fix it ASAP because this is company brand store and it needs to run 24/7. Now I know, that I shouldn't upgrade to newest version (it was working ok at that point). I've just follow tempting upgrade notification :)
At this moment I need to do everything to fix it up. And two possibilities: Me forgot to backup database. We have all files from FTP for the shop. If we just copy all backuped files to directory without doing anything with database it will work? (or installation changed database the way it won't work with version 1.7.6.5)
Second option is to fix what is wrong with this 1.7.7.0 (main problems I see now are this pictures, but probably there is more to fix. Maybe i need to activate something? Thats why I need your help) Or maybe will be good solution to upgrade again to 1.7.7.0.1 and it possibly will fix my problems?
Whats your suggestions?

**Comment by BaraqdaPL** [comment]
> I think problem with adding pictures to products from BO or missing prestashop module shop, from BO, is not a third party modules installed...
> I'm fully appreciated all developers creating this project and I'm far of blaming anyone. I just need to fix it ASAP because this is company brand store and it needs to run 24/7. Now I know, that I shouldn't upgrade to newest version (it was working ok at that point). I've just follow tempting upgrade notification :)
> At this moment I need to do everything to fix it up. And two possibilities: Me forgot to backup database. We have all files from FTP for the shop. If we just copy all backuped files to directory without doing anything with database it will work? (or installation changed database the way it won't work with version 1.7.6.5)
> Second option is to fix what is wrong with this 1.7.7.0 (main problems I see now are this pictures, but probably there is more to fix. Maybe i need to activate something? Thats why I need your help) Or maybe will be good solution to upgrade again to 1.7.7.0.1 and it possibly will fix my problems?
> Whats your suggestions?

**Comment by hibatallahAouadni** [comment]
Hello @BaraqdaPL 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you!

**Comment by SimonGrn** [comment]
Hello @BaraqdaPL,
sadly your problem seems to be related to your environment. As @hibatallahAouadni said we cannot offer support here, this is not the place.

You can follow the links she posted to get dedicated help, or community help.

Thank you.

**Comment by BaraqdaPL** [comment]
To sum up topic problem.
After changing from php 7.2 to php 7.3 I was manage to enter BO. I've spoted some problems with working in BO (I will add new issue in separate topic). There might be a problem with php versions. Just to check, i've switch back to php 7.2. 

![image](https://user-images.githubusercontent.com/75696855/101782569-78a0bd80-3af9-11eb-9a99-ac760538715e.png)

BO was working. I could move between sections, check products, see modules etc.. but after login out and login in again, problem occurred again (no BO page, so same as the beginning) 
Now I'm back to 7.3 php.
![image](https://user-images.githubusercontent.com/75696855/101783564-b5b97f80-3afa-11eb-93fc-45c96c02e8c3.png)

maybe it's just a problem with login in to BO, but after this obstacle BO will be working on 7.2 php?...

**Comment by doekia** [comment]
Problem is here
`[PrestaShopDatabaseException]

Table 'c2_andeo17.ps_employee_session' doesn't exist<br /><br /><pre>INSERT INTO `ps_employee_session` (`id_employee`, `token`) VALUES ('7', 'a9fde65149c017544c61c1ccd801d5175045f00b')</pre>
at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
`

**Comment by BaraqdaPL** [comment]
Hmm. I have in my database id_employee 7 with token... different but still...
also classes/db/Db.php looks the same as you wrote.
What shall I do with it?

**Comment by simbus82** [comment]
> @BaraqdaPL great to know! indeed if ICU is below 4.6 there's a known issue. In theory modern hosting environments have an ICU version way higher, but some old environments are stuck with outdated ICU.

I have a PHP 7.3 with old ICU and php 7.4 with supported ICU.

It's a standard CPanel/Cloudlinux server with the famous PHP Selector and EasyApache 4.
PHP 7.3 is compiled with an ICU <4.6, why Prestashop did this thing?
90% of PHP 7.x early adopter have ICU <4.6.

And this in not mentioned in requirements, and we don't see any warning during installation.

Now i have a shop with 1.7.7.1 that i can't login to Backend if i have PHP 7.3 (old ICU) and out customer can't register when, to let me access to BO, i switch to PHP 7.4 (new ICU).

Any workaround that not is the recompile of a production stable PHP 7.3?

**Comment by matks** [comment]
@simbus82

> 90% of PHP 7.x early adopter have ICU <4.6.

Do you have official informations about this ? Because ICU 4.6 was released in 2011. 10 years ago. I am very surprised you say 90% of PHP 7.x early adopter have ICU <4.6.

We rely on INTL_IDNA_VARIANT_UTS46 which is a constant used by PHP. See the details on https://www.php.net/manual/en/function.idn-to-ascii.php . Previous constant INTL_IDNA_VARIANT_2003 has been deprecated.

Today, any version of php < 7.3 is deprecated (https://www.php.net/supported-versions.php) so it is important to follow up-to-date php versions, not old php versions. Security is critical.

**Comment by giles247** [comment]
@matks 

Our hosting provider has informed us:

PHP 7.3
======
ICU version => 4.2.1
ICU TZData version => 2009j
ICU Unicode version => 5.1

PHP 7.4
======
ICU version => 68.2
ICU Data version => 68.2
ICU TZData version => 2020d
ICU Unicode version => 13.0

and that ICU can't be changed for PHP 7.3. So what are we supposed to do?

**Comment by matks** [comment]
Hi @redactuk you have multiple roads ahead of you.

1. You can change hosting provider. I might be wrong but if I read it correctly

> ICU TZData version => 2009j

This indicates this ICU component uses data from 2009 while the year is 2021? If yes it's _very_ outdated then so your hosting provider is telling you that you can only have a php7.3 version with 2009 settings 😅  ? However I am not expert in such things, maybe it would be best to reach out to a hosting expert with better knowledge.

2. PrestaShop 1.7.8 is expected to be released in summer 2021 with php7.4 support. If you can wait until then you might upgrade directly to PS 1.7.8 and benefit from a recent ICU version.

3. You can hire a PrestaShop developer to customize your shop behavior and work around this issue. I believe it is possible to build a quick fix for file https://github.com/PrestaShop/PrestaShop/blob/1.7.7.0/src/Core/Util/InternationalizedDomainNameConverter.php to handle ICU versions < 4.6 . So it would be "hire a developer with PrestaShop knowledge to customize my PrestaShop 1.7.7 version and make it work with ICU < 4.6".

There might be more solutions, this is what I can think of :)

**Comment by giles247** [comment]
@matks 

Thank you for reply. I found the following thread on your forums with a suggested fix, which appears to work!
https://www.prestashop.com/forums/topic/1027541-cannot-login-to-my-shop-backend/

Can you comment on this? I mean if that fixes issue without any side effects, should this not be a PR?

**Comment by Varkeychen** [comment]
> 
> 
> Hi,
> I've just update my PS. Before there was no problem. Now, after putting my mail and password, I see blank page.
> What could go wrong?
> During update, there was no errors (I used 1- click). Then system asked me to reboot and log in again. And now there is no response.
> ![image](https://user-images.githubusercontent.com/75696855/101534756-ed5be680-3997-11eb-96da-8c12faa5c25a.png)
> I've seen some topics to check SQL base to check if there is no missing
> ps_employee_session but there are...
> After chcecing website, it shows error 500. In some more deep information, problem might be connected with jquery-3.4.1.min.js
> ?
> What might be a solution?

Finally I have got a wayout from this problem. Just install for US, means never change the country or region during installation. You can then easily access BO and FO. After successful installation you can change the country and currency etc. from BO into yours.
