### ISSUE TITLE
[Shopping carts] - Duplicated display of fixtures

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#22304]
#### Describe the bug

Demo shopping are duplicated in listing page after new Order

#### Expected behavior
No duplicates

#### Steps to Reproduce

On a fresh install, you have 5 demo shopping carts 

1. Create an order in FO
2. Go to BO 'Sell -> Orders -> Shopping carts'
3. See error : fixtures are duplicated

**Screenshots**

![image](https://user-images.githubusercontent.com/48441421/101612602-1b2e4300-3a0b-11eb-918b-93663c104b3b.png)

PS : Database table ps_cart seems to be good
![image](https://user-images.githubusercontent.com/48441421/101612722-3ef18900-3a0b-11eb-9002-4f1fd5b6a684.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.3

**Comment by PululuK** [comment]
Hi @boubkerbribri 
Why Critical ?

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

It is a critical because it breaks the automatic tests.
This regression is detected by the nightly.

https://build.prestashop.com/news/severity-classification/

Thanks!

**Comment by SimonGrn** [comment]
Hello @PululuK,

A bug breaking nightlies has always a critical priority as it's a regression, regardless of its severity :)
This is a rule we had for a few months now.

**Comment by PululuK** [comment]
Thanks @SimonGrn  @khouloudbelguith

**Comment by boubkerbribri** [comment]
Since I don't have the exact scenario to reproduce this issue, and @Progi1984 was not able to reproduce it, I'm closing it
