### ISSUE TITLE
Better error message on invalid image upload request

### ISSUE THREAD

**Issue by KminekMatej** [PrestaShop/PrestaShop#22313]
When there is an invalid request during Image upload, prestashop returns only general error code 500 / 66: Unable to save this image, response should be bit more detailed

**Comment by hibatallahAouadni** [comment]
Hello @KminekMatej 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
