### ISSUE TITLE
[UI-KIT] - size of searchbox with a research is too small 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22319]
#### Describe the bug

 size of searchbox with a research is too small 

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to admin > modules
2. Search a module
3. See error

**Screenshots**

![Capture d’écran 2020-12-09 à 18 31 02](https://user-images.githubusercontent.com/3034677/101665509-594c5680-3a4d-11eb-96ad-2d320b30b76c.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by Hlavtox** [comment]
@sarahdib Why is it bad? If it's full width, user who does not use his _enter_ key has to move his mouse far right.

And I have never searched more than 1 word on module page...

**Comment by NeOMakinG** [comment]
@Hlavtox you miss understood the issue :p

It's buggy atm

**Comment by Hlavtox** [comment]
@NeOMakinG Aaaaaaah I see it now 😄 sorry
