### ISSUE TITLE
[UI-KIT] - BO - Order page - The Modal of adding a discount is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22315]
#### Describe the bug

n the BO > Orders > Order details page > when we try to add a new discount, the modal is not well displayed
![image](https://user-images.githubusercontent.com/16067358/101652285-5b5ae900-3a3e-11eb-8ae1-819c99844389.png)

#### Steps to Reproduce

1. Go to BO > Orders > Order details page
2. Click on the Add a discount button
3. See error

#### Additional information

* PrestaShop version: develop(1780)
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
Hello @khouloudbelguith 

I can't reproduce it ever using 1.2.0 of the UIKit or the local on develop, are you sure ?

![image](https://user-images.githubusercontent.com/14963751/102097261-f6c8d100-3e25-11eb-9610-1fe32574fae9.png)

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Yes, you are right!
![image](https://user-images.githubusercontent.com/16067358/102988579-63be2400-4514-11eb-9567-42b545624dca.png)

Thank you :slightly_smiling_face:

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

I reproduce the issue with PS1.7.8.0 and Safari 14(iPhone):

![image](https://user-images.githubusercontent.com/23308427/138908412-8a0dc064-650d-4410-b9a2-d69fbc614029.png)

So, I reopen the issue :wink: 
By the way @nesrineabdmouleh reproduced the issue with chrome 73.

Thanks!

**Comment by NeOMakinG** [comment]
I fixed it on view order page, but depending of what developers did on other pages, this could happen on some other pages that I'm not aware of

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #26465
