### ISSUE TITLE
Help in prestashop 1.7.6.2 in the categories 

### ISSUE THREAD

**Issue by gabgustavo** [PrestaShop/PrestaShop#22318]
Hello, I have a requirement in prestashop 1.7.6.2 in the categories, which is that when you update the image of "Category cover image" do not want to change the "Category thumbnail", ie they want to be independent in the update, but I do not know what to change in the code or where, could help me please. Thank you

**Comment by hibatallahAouadni** [comment]
Hello @gabgustavo 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12760. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #12760
