### ISSUE TITLE
Cannot extend CartSummary form in OrderCreate page

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#22321]
#### Describe the bug

In summary.html.twig the form_rest is missing so when extended, the input renders after submit button.(screenshot1).
Also order creation from a cart summary could be handled by FormHandler, this way taking advantage of form handler hooks

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Add additional field in CartSummaryType
2. Go to BO orders > add new order
3. Fill information until summary block shows up and see that added input is shown in wrong place (bellow submit button) due to missing form_rest.
4. There is no way to extend handling of the field in server side either.

**Screenshots**
![Screenshot from 2020-12-09 18-52-09](https://user-images.githubusercontent.com/31609858/101675069-f913df80-3a61-11eb-904a-b64474339996.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

@matks said that this is not a bug but it's an improvement.
So, thanks for the suggestion, the Developer Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers , what do you think about this issue? why when you add additional field in CartSummaryType doesn't show up in the summary block?

**Comment by Progi1984** [comment]
In this case, it's an improvement : it should target the `develop` branch.

**Comment by hibatallahAouadni** [comment]
@Progi1984 shall we add the **`To Do`** label?

**Comment by Progi1984** [comment]
@hibatallahAouadni Yes

**Comment by zuk3975** [comment]
well yes, technically its improvement, because previous order page wasn't extendable at all, but it could be considered as a bug too because we didn't apply all our migration conventions which would allow extending part of page as it is described in devdocs. (furthermore there is very little code, but it brings a great value :stuck_out_tongue: )
