### ISSUE TITLE
Unable to open cart: Tools::getAdminTokenLite error

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#22323]
#### Describe the bug

In file https://github.com/PrestaShop/PrestaShop/blob/cc0fd12edd388805ccd82c6756d0e2f947215aa8/classes/Tools.php#L1360-L1367

value of `$context->employee` should be wrapped in if statement:

```
        $employeeId = 0;
        if ($context->employee) {
            $employeeId = (int)$context->employee->id;
        }

        return Tools::getAdminToken($tab . (int)Tab::getIdFromClassName($tab) . $employeeId);
```

#### Steps to Reproduce

1. Enable `_PS_MODE_DEV_` mode.
2. Go to front office.
3. With multistore add product to cart.
4. Go to cart.
5. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/3767861/101698205-6848fe00-3a79-11eb-9934-6bb92dc0584b.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.24

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

I didn't manage to reproduce your issue with PS1.7.7.0 and develop, with PHP v7.2 and PHP v7.3.
See attached screen record below:

https://drive.google.com/file/d/1q530rE7yxYgFpSRmV9MD0CLh9csWUfU-/view

Please check and feedback.

Thanks!

**Comment by Flower7C3** [comment]
You are testing in BO, my problem is in FO. In addition You are using PS 1.7.8.0, while I am using 1.7.7.0.

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

Here's the screen record with PS1.7.7.0:

https://drive.google.com/file/d/1vLqEbnfV5QQeS0XySe81qRdKhHfVgB7A/view

As I said above I have tested with both version and I had no error.
Again did you change any of the Core files? if so, please use the override cause **you're not allow to change any of the Core files**, here's the link to learn how to use the [Overrides](https://devdocs.prestashop.com/1.7/modules/concepts/overrides/).

Thanks!

**Comment by Flower7C3** [comment]
I do not changed core files. I have used overrides directory to fix this problem on my instance. So if error occurs only on my server I will keep this override.
Thanks.
