### ISSUE TITLE
Carriers never found for new Order in BO

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#22325]
#### Describe the bug
Available carrier options not found when  creating order from BO

#### Expected behavior
I expect the list of available carriers to allow finish order creation (because now you cannot progress further and its impossible to create order)

#### Steps to Reproduce

Go to Orders > Add new order,
Fill required information (add some products, have an address that are supported by your carriers)
Still see "No carrier can be applied to this order "

**Screenshots**

![Screenshot from 2020-12-10 10-27-24](https://user-images.githubusercontent.com/31609858/101741124-59db0080-3ad2-11eb-8db2-8e992c5297be.png)

#### Additional information

* PrestaShop version: develop (might be on 1.7.7.x too)
* PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I think it is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/22124 which fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/21568

Thanks to check and feedback.

**Comment by zuk3975** [comment]
Actually it was caused by the fact that Countries of all the addresses were disabled in `International > Locations > Countries`
Once I enable related countries, it works. Sorry false alarm :stuck_out_tongue:

**Comment by matks** [comment]
@zuk3975 Would it be useful to display a warning message when this happens?

"Hello, no carriers are available in the country where you want to ship"

**Comment by zuk3975** [comment]
This wouldn't differ too much from existing message. Maybe its not a problem, merchants might most of the time have correct settings of their countries :man_shrugging: 
If we still want to add a message that should mention "International -> Location -> Countries" to make it clear
