### ISSUE TITLE
prestashop 1.7.7.0, bug : Installation impossible with different prefix in database

### ISSUE THREAD

**Issue by fanny300** [PrestaShop/PrestaShop#22326]
Hello,

I'm french. I try this morning to install a new prestashop in 1.7.7.0.
On the Installation assistant : 
1/ I add the store information.
2/ I defined the parameters of the database and i I change prefix ps in blabla for example.
3/ At "Création de la boutique par défaut et des langues" = Creation of the default store and languages this error : 
Impossible de créer le groupe de boutiques / Table 'cartes_remerciements_deuil.blabla_shop_group' doesn't exist
In english : Cannot create store group / Table 'cartes_remerciements_deuil.blabla_shop_group' doesn't exist

In the database all this tables are with prefix ps_ instead of blabla_
ps_admin_filter 
ps_attribute 	  	
ps_attribute_group 
ps_attribute_group_lang
ps_attribute_group_shop
ps_attribute_lang
ps_attribute_shop
ps_lang 	
ps_lang_shop 
ps_module_history 
ps_product_download 
ps_shop 	  
ps_shop_group 
ps_stock_mvt 
ps_tab 	  	
ps_tab_lang 
ps_translation 

I try to change in database the prefix, but in reload install same bug.

**Comment by masiorama** [comment]
I just tried the same thing (custom table prefix) and in my case it did work correctly, so all the tables are prefixed as I wanted.

**Comment by fanny300** [comment]
Hello, ok i have try with the 1.7.6.9 same error.
I have recreate a new database for retest but same bug.
I use php 7.3

**Comment by masiorama** [comment]
I use php 7.3 too, apache 2.4 and MySQL 5.7.... maybe you could try to check if your server requirements are met via https://github.com/PrestaShop/php-ps-info, if you haven't tried yet.

**Comment by hibatallahAouadni** [comment]
Hello @fanny300 

I didn't manage to reproduce your issue with PS1.7.7.0 avec PHP v7.2 and PHP v7.3:

## PS1.7.7.0 with PHP 7.2:

https://drive.google.com/file/d/11MAqNK4qfyaoGTjBfKbHKsNH_s7hh85F/view

![image](https://user-images.githubusercontent.com/23308427/101768228-99f7ae80-3ae5-11eb-9beb-ea5efe5ec4aa.png)

## PS1.7.7.0 with PHP 7.3:

![image](https://user-images.githubusercontent.com/23308427/101768275-a8de6100-3ae5-11eb-962b-64bf80ba065d.png)

![image](https://user-images.githubusercontent.com/23308427/101768365-c27fa880-3ae5-11eb-8dce-19717db884a7.png)

So, I close the issue, and please next time **respect the template to submit a complete bug report**.

Thanks!

**Comment by masiorama** [comment]
@hibatallahAouadni ok, but I had no issue, the opener was @fanny300 :)

**Comment by hibatallahAouadni** [comment]
Thanks @masiorama I edit my comment :sweat_smile:

**Comment by fanny300** [comment]
Hello,
Thanks all, sorry for the incomplete debug, i will do best the next time.
I have tried to install in a new folder, today, it work. Strange but there is a bug on the first folder. I close the issue.
