### ISSUE TITLE
Error during manual order state change

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#22322]
#### Describe the bug

When I manually change order state an error occurs:

```[Symfony\Component\Debug\Exception\ContextErrorException kod 0]: Notice: Trying to get property 'id' of non-object```

#### Expected behavior

Method \OrderCore::getCurrentOrderState:
https://github.com/PrestaShop/PrestaShop/blob/cc0fd12edd388805ccd82c6756d0e2f947215aa8/classes/order/Order.php#L2332-L2339 should have following code:
```
    public function getCurrentOrderState()
    {
        if ($this->current_state !== "") {
            return new OrderState($this->current_state);
        }

        return null;
    }
```

#### Steps to Reproduce

1. Go to orders list
2. Change order status to cancelled
3. See error on top

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.24

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1Uf2yTmgH3G5R1s69W6CVLkUIQQYe29xU/view

Please check and feedback.

Thanks!

**Comment by Flower7C3** [comment]
@hibatallahAouadni do You have same PHP version?

**Comment by hibatallahAouadni** [comment]
No my PHP version is 7.2 :sweat_smile:

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

Is this the error that you encountred? 

![image](https://user-images.githubusercontent.com/23308427/101758564-c48f3a80-3ad8-11eb-8cd3-bb94247e0be7.png)

Thanks for your feedback!

**Comment by Flower7C3** [comment]
No, I have got other message:
```
[Symfony\Component\Debug\Exception\ContextErrorException kod 0]: Notice: Trying to get property 'id' of non-object
```

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

Did you change some Core files? Cause it seems your issue is not related neither to PS version nor PHP version.

Thanks!

**Comment by Flower7C3** [comment]
I have changed **classes/order/Order.php** file as described in issue description.

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

You shouldn't change any of Core files! If you want to change some behavior of Core, you just need to override the Controller ([see link](https://devdocs.prestashop.com/1.7/modules/concepts/overrides/)).

So, I close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by rbeau** [comment]
Hi @Flower7C3,  
Post #24097 
I have same issue. Your bug is fixed ? Could you please explain me how to resolve this bug ? There is no change if I try your solution. 
Thanks

**Comment by Flower7C3** [comment]
Hi @rbeau, I have fixed this problem using `overrides` directory. All described in 1st comment https://github.com/PrestaShop/PrestaShop/issues/22322#issue-760677563

**Comment by rbeau** [comment]
You are right @Flower7C3 , 

I understand now, if I still turn Prestashop on mode debug solution doesn't work. Now debug mode is off and it work prefectely.

I thank you so much !

**Comment by HartLarsson** [comment]
i've the same problem whren i try to convert a cart to an order wirth PS 1.7.8.7


any fix?
