### ISSUE TITLE
SmartyException Unable to load template 'module:ps_brandlist/views/templates/_partials/.tpl'

### ISSUE THREAD

**Issue by Dav1dNL** [PrestaShop/PrestaShop#22328]
I get the following error when opening a catagory from the main menu.

![error](https://user-images.githubusercontent.com/45255518/101762152-58630580-3add-11eb-9406-224f17a48663.PNG)

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.18
* MySQL versie: 5.5.41-MariaDB-log
* thema: classic

**Comment by hibatallahAouadni** [comment]
Hello @Dav1dNL 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
