### ISSUE TITLE
API display=full return only id on 1 item

### ISSUE THREAD

**Issue by homer8173** [PrestaShop/PrestaShop#22333]
#### Describe the bug

when calling API on an item (ex /products/1) if you ask display=full it return only the id

#### Expected behavior

the details of the item

#### Steps to Reproduce

1. Go to https://xxxx.fr/api/products/1563/?ws_key=MYKEY&display=full

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @homer8173 

AFAIK, the use of **`display`** parameter is like mentioned in our [addtional list parameters](https://devdocs.prestashop.com/1.7/webservice/tutorials/advanced-use/additional-list-parameters/#display-parameter)

![image](https://user-images.githubusercontent.com/23308427/101793315-f074e500-3b05-11eb-882e-67894c6e8c3a.png)

So, I beleive with your exemple, you need to use the display parameter like this:

- to display all the fields of all Products:

**`http://xxx.fr/api/products/?display=full`**

- to display all the fields of the product with id=1

**`http://xxx.fr/api/products/1/`**

- to display only the IDs of all products:

**`http://xxx.fr/api/products/?display=[id] `**

Please check and feedback.

Thanks!

**Comment by homer8173** [comment]
Hello @hibatallahAouadni
No I'm really saying that display feature is destroying the output of a single object

Maybe It's not supposed to work on a single object but if you use it, it hides the object of the api output 
Check on your api
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @homer8173 

> when calling API on an item (ex /products/1) if you ask display=full it return only the id

Ping @PrestaShop/prestashop-core-developers, is this the expected behavior when you use display=full with a single product? or it's a bug?

**Comment by PierreRambaud** [comment]
I manage to reproduce the issue.
Here's the pull request fixing the issue: #22413
