### ISSUE TITLE
Not active buttons - adding pictures to a product PS 1.7.7.0 after upgrade

### ISSUE THREAD

**Issue by BaraqdaPL** [PrestaShop/PrestaShop#22338]
#### Describe the bug

After updating PS 1.7.6.5 to 1.7.7.0 and switching php from 7.2 to 7.3, in BO i spotted some problems.
My main problem at this point is editing products. Problem is the same if I would like to edit existing product or add a new one.
Buttons are not active. I cannot add any picture, I cannot edit pictures already in the system, cannot drug&drop any picture. I cannot also add for example brand (buttons are not active - they blink when pointed, but after click there is no any reaction.

#### Expected behavior

Add picture, add brand,

#### Steps to Reproduce

1. Go to katalog/products
2. Chouse produkt to edit
3. Try to press button add picture / try to press button add brand
4. See error - nothing happens

**Screenshots**

![image](https://user-images.githubusercontent.com/75696855/101784346-ae46a600-3afb-11eb-8c98-4d9311c26e46.png)

#### Additional information
Some debug errors:
![image](https://user-images.githubusercontent.com/75696855/101784543-f1087e00-3afb-11eb-929a-1f647adec41a.png)
![image](https://user-images.githubusercontent.com/75696855/101785171-bb17c980-3afc-11eb-9a21-bea8f6534860.png)

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @BaraqdaPL 

PLEASE RESPECT OUR TEMPLATE, **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Please edit your issue, we will be glad to investigate it.

Thanks!

**Comment by BaraqdaPL** [comment]
> Hello @BaraqdaPL
> 
> PLEASE RESPECT OUR TEMPLATE, **You must follow the template to submit a complete bug report**.
> 
> Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).
> 
> Please edit your issue, we will be glad to investigate it.
> 
> Thanks!

Hope now my issue is more clear

**Comment by BaraqdaPL** [comment]
Any idea what have happened?

**Comment by cleocreations** [comment]
Same problem

**Comment by BaraqdaPL** [comment]
> Same problem

Did you also upgrade from php 7.2, BO did not work and switch to 7.3?

**Comment by cleocreations** [comment]
> > Same problem
> 
> Did you also upgrade from php 7.2, BO did not work and switch to 7.3?

I only upgrade the PS from 1.7.6.9 to 1.7.7.0 and still use PHP 7.2. The problem of pictures, category,... is the same.

**Comment by hibatallahAouadni** [comment]
Hello @BaraqdaPL 

The only issue that I encountred while upgrading my shop from PS1.7.6.5 to PS1.7.7.0 is #22250
From your screenshot I can see you got an errror about Entity tab which is similar to this #22248
Even whith the left menu disappeared, I can add a photo/brand to any product without any error, see the attached screen record below:

https://drive.google.com/file/d/1aomzrwJHclL4lM1Utcj-oJ3ojOdb61sU/view

Please check and feedback.
Thanks!

**Comment by BaraqdaPL** [comment]
Ok I found my issue. The problem was is external modules installed on my shop. After switching it off - back office came back to normal... Problem is that this modules are very important (delivery carriers)... but - I will bother now their developers :)

**Comment by cleocreations** [comment]
> Ok I found my issue. The problem was is external modules installed on my shop. After switching it off - back office came back to normal... Problem is that this modules are very important (delivery carriers)... but - I will bother now their developers :)

Hello @BaraqdaPL 

Wich carrier was it?

Regards

**Comment by hibatallahAouadni** [comment]
@BaraqdaPL Glad to hear :tada: So, I close the issue :wink: 

@cleocreations @BaraqdaPL 's issue was with an external module (delivery carriers) not with a carrier :wink: 
Hope you solve your issue, I advise you to disable your modules one by one to figure out which module is causing your problem.

**Comment by BaraqdaPL** [comment]
My Inpost module (most popular carrier in Poland nowadays) developed by PrestaHELP (i've just contact them - they will have time to fix it to 1.7.7.0 maybe in January. They was not ready.. he told me that lots o modules will have issues... )
and Polish Post module called e-nadawca (developed by polish post themselves). Version 1.1.5 , in description is dedicated to 1.6.x and 1.7.x but in this 1.7.7.0 crashes... 
If you would like to see crash effect, install this module (from official post page:
https://e-nadawca.poczta-polska.pl/?action=GetIntegration
direct link: https://e-nadawca.poczta-polska.pl/download/poczta-polska-en-v.1.1.5.zip
many developers have modules for 1.7.x ... they might be not aware of beeing not compatibile

**Comment by cleocreations** [comment]
> e-nadawca

Thanks @BaraqdaPL 

@hibatallahAouadni  I do not use that module and still have the problem... maybe not close to fast

**Comment by hibatallahAouadni** [comment]
Hello @cleocreations 

You need to disable your modules one by one to figure out which module is causing your problem.
Sometimes, it's Theme problem :wink: 
So you need to check.

Thanks!

**Comment by cleocreations** [comment]
> Hello @cleocreations
> 
> You need to disable your modules one by one to figure out which module is causing your problem.
> Sometimes, it's Theme problem 😉
> So you need to check.
> 
> Thanks!

Thanks @hibatallahAouadni 

It was the module pre-order notification. I upgrade it to the latest version and all works fine.

**Comment by hibatallahAouadni** [comment]
Glad to hear @cleocreations :tada:
