### ISSUE TITLE
/controllers/admin/AdminOrdersController.php gone

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#22337]
#### /controllers/admin/AdminOrdersController.php gone...

/controllers/admin/AdminOrdersController.php file is gone, either update the docs or get it back.
Example of the hook "actionAdminOrdersTrackingNumberUpdate" still pointing to that file according to the [docs](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/) 

#### Additional information

* PrestaShop version: 1.7.7

**Comment by SimonGrn** [comment]
>either update the docs or get it back.

Hello, 
please remember that you're talking to real humans. This is an Open Source project with real contributors.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @NKoonen 

Yes, this file has been removed with PS1.7.7.0.
And thank you for pointing to the Docs, we need to update these docs.

Thanks!

**Comment by matks** [comment]
See https://github.com/PrestaShop/docs/pull/828/

**Comment by Henrik41** [comment]
Nkoonen is right. How are we suppose to troubleshoot existing modification of AdminOrdersController.php if it doesn't exist anymore. Doc should be updated and explained. What happened to it. Why was it removed. What is it replace with. Going through the code without guidance is a nightmare. Please document well.

**Comment by matks** [comment]
> Nkoonen is right. How are we suppose to troubleshoot existing modification of AdminOrdersController.php if it doesn't exist anymore. Doc should be updated and explained. What happened to it. Why was it removed. What is it replace with. Going through the code without guidance is a nightmare. Please document well.

The file was removed as part of the migration to Symfony project.

We try to document changes in the doc, but writing good documentation is hard and our resources are limited.
See our work for 1.7.7:
- https://build.prestashop.com/news/prestashop-1-7-7-0-available/
- https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/
- https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/

But here's the good news: the documentation is also an open source project so you can contribute to it ! You can help making the documentation more clear for newcomers. See https://devdocs.prestashop.com/1.7/contribute/documentation/
