### ISSUE TITLE
Same string multiple times doesn't translate

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#22332]
In my template I have multiple times the string
{l s='proceed to checkout' d='Shop.Theme.Actions'}

There is a translation given in the backoffice. However, this is not visible on the front side. 

The only explanation I can think of is that the translation system doesn't know how to handle multiple strings with the same text.

* PrestaShop version: 1.7.6.1

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
