### ISSUE TITLE
Order - Email / html tag in the email sent to customer when a product have customisation

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#22330]
#### Describe the bug

There is html tag in the order confirmation email sent to customer when the order contain a product with customisation

#### Expected behavior

No html tag should be in the mail send to customers
#### Steps to Reproduce

1. Setup the smtp parameters to correctly send / receive email
2. Go to FO and crate an order with a customizable product
3. Finish the order
4. Go to your mail box and check the received mail
5. See error => html tags are in the email

**Screenshots**
![image](https://user-images.githubusercontent.com/40635814/101762791-27370500-3ade-11eb-9825-bcc3b488ce4c.png)

#### Additional information

* PrestaShop version: 1.7.6.x // 1.7.7.x // develop
* PHP version: php 7.1

**Comment by SD1982** [comment]
Ping @hibatallahAouadni I don't know if there is an epic that this issue could be related to ?

**Comment by radioeventos** [comment]
On Bank Wire template on 1.7.7 does not show IBAN and merchant information from module, only shows the short codes to the customers. I have to put the data directly on template.

**Comment by matks** [comment]
I'm wondering if it's really an issue 🤔  this customization field can accept HTML ? it's not just text?

**Comment by MorSeRNa** [comment]
Solved!

Search  mails/_partials/order_conf_product_list.tpl

Change
{$customization['customization_text']}
to
{$customization['customization_text'] **nofilter**}

**Comment by Zulgrib** [comment]
Hello, still facing this problem with a fresh install of 1.7.8.7, it makes no sense it was not resolved upstream seeing @MorSeRNa 's solution is a on one line.

**Comment by Prestaworks** [comment]
> I'm wondering if it's really an issue 🤔 this customization field can accept HTML ? it's not just text?

it's not possible to type html into the fields. if it was and there is no filtering, would it not be really easy to email scripts?
I don't think adding this nofilter is a good idea, if PS is adding the strong tag, then that should be in the tpl file for the product rows and not from the code. 
just my 2 cents :)

**Comment by Zulgrib** [comment]
@Prestaworks Valid

**Comment by ingridusta** [comment]
Closing in favor of https://github.com/PrestaShop/PrestaShop/issues/36795.

Thanks :)
