### ISSUE TITLE
The FR 20 % tax rule is not taken into account. 

### ISSUE THREAD

**Issue by massha** [PrestaShop/PrestaShop#22339]
#### rule tax doesn't work 
I set up the FR 20% tax rule for all countries ( taxe rules table)  ( cf screenshot ) 
Then , on my product page , I set up my price HT , but the price TTC is the same 

#### Expected behavior
I am supposed to have 2 differents prices ( 1 HT and the other TTC ) 

#### Steps to Reproduce

1. Go to 'product page '
2. Click on 'Price'
3. Click on 'Rule tax'
4. Choose FR 20% 
5. The price doesn't change 
6. Click on Monaco 20% 
7. The price changes 

![image](https://user-images.githubusercontent.com/48324964/101788600-945b9200-3b00-11eb-9863-57859da9ec9c.png)
![image](https://user-images.githubusercontent.com/48324964/101788787-ca007b00-3b00-11eb-95a6-6d3031afee27.png)

#### Additional information

* PrestaShop version: VERSION 1.7.6.8
* PHP version: N/A

**Comment by massha** [comment]
![image](https://user-images.githubusercontent.com/48324964/101790453-beae4f00-3b02-11eb-80a7-89e572b75ac4.png)

**Comment by hibatallahAouadni** [comment]
Hello @massha 

>Choose FR 20%
The price doesn't change
Click on Monaco 20%
The price changes

That's because your default country is Monaco, just change it to France, then check the price :wink: 
To change your default country, BO > IMPROVE > International > Localization, then go to Configuration block (see the attached screenshot below):

![image](https://user-images.githubusercontent.com/23308427/101799327-53697a80-3b0c-11eb-99bb-f76101e1f35f.png)

And I believe your issue is the same as yours #22305, is it the same?

Please check and feedback.

Thanks!

**Comment by massha** [comment]
Thanks a lot !!
now I have differents prices HT and TTC
[image: image.png]

But I still have my issue with the tax.
I mean , with a monegasque address => no tax
[image: image.png]

With a french one => tax
[image: image.png]

And I'm supposed to have tax also in Monaco

**Comment by florine2623** [comment]
Hi @massha 
Can you answer via GitHub directly and not by email ?
The images you sent can't be seen.
Thanks

**Comment by massha** [comment]
Thanks a lot !! 
now I have differents prices HT and TTC 
![image](https://user-images.githubusercontent.com/48324964/101897498-ed800000-3baa-11eb-9694-815e2876770b.png)
But I still have my issue with the tax.
I mean , with a monegasque address => no tax
![image](https://user-images.githubusercontent.com/48324964/101897532-fcff4900-3baa-11eb-9888-4f9d7127c9a0.png)
With a french one => tax 
![image](https://user-images.githubusercontent.com/48324964/101897560-0983a180-3bab-11eb-83dd-bcc50fc19084.png)
Abd I'm supposed to have taxes also in  Monaco

**Comment by florine2623** [comment]
Hello again @massha ,

You need to create a tax rule of your TAX (ex 20%) for all countries :
![Capture d’écran 2020-12-11 à 16 28 59](https://user-images.githubusercontent.com/16019289/101922191-1796e980-3bce-11eb-8c21-965379765f60.png)
Set the correct tax to the product :
![Capture d’écran 2020-12-11 à 16 29 08](https://user-images.githubusercontent.com/16019289/101922205-19f94380-3bce-11eb-8c49-a0704fb1285c.png)
In the purchase tunnel :
![Capture d’écran 2020-12-11 à 16 28 22](https://user-images.githubusercontent.com/16019289/101922231-2087bb00-3bce-11eb-8090-b00b3f4b2dd6.png)

I'll close your issue !
If you need more help, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
