### ISSUE TITLE
[CO] Unable to change existing CMS Page's category association (EASY FIX)

### ISSUE THREAD

**Issue by Perfecticus** [PrestaShop/PrestaShop#22340]
#### Describe the bug

Impossible to change CMS Category on a CMS Page

#### Why

Regression introduced in 1.7, in eb4cba2, see https://github.com/PrestaShop/PrestaShop/commit/eb4cba22bd5769a16c147626c5ea9dc53a545f4e#r44998939
assertCmsCategoryExists has **no return statement**
still used in if clause asking for **true**

The AbstractCmsPageHandler.assertCmsCategoryExists() never returns a value.
See AddCmsPageHandler implementation (not using if clause).

Either move assertion inside if statement or add return statement to AbstractCmsPageHandler.assertCmsCategoryExists().

https://github.com/PrestaShop/PrestaShop/blob/1c565a28540b55e11b07c69905dbb1014ea162dd/src/Adapter/CMS/Page/CommandHandler/EditCmsPageHandler.php#L82

#### Expected behavior

Should be possible to change CMS Category on a CMS Page

#### Steps to Reproduce

1. Try to reassign category on an existing CMS Page
2. Save, see that it was not persisted

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Perfecticus 

I believe what you sugguest is an improvement! 
Please edit your issue, **you must follow the template to submit a complete feature report**.

As you can see in the attached screenshot below, click on **Get started** button of **Feature Request** 

![image](https://user-images.githubusercontent.com/23308427/101800596-be678100-3b0d-11eb-9e85-83bd5ae04174.png)

Then, we offer you a template to follow and we specify each block cause we need it :wink: (see attached screenshot below):

![image](https://user-images.githubusercontent.com/23308427/101800746-e5be4e00-3b0d-11eb-844c-30e9f6202be7.png)

Thanks!

**Comment by Perfecticus** [comment]
@hibatallahAouadni, no it's not an improvement, it's a **bug** and **regression**.

The code for the function is there, but the logic is flawed.

**Comment by hibatallahAouadni** [comment]
Hello @Perfecticus 

Thanks for the clarification! 
I manage to reproduce your issue only with PS1.7.7.0 and develop, see the attached screen record below:

**PS1.7.6.9:**
https://drive.google.com/file/d/1wPpgKS1xTdVNw7ZUigNVVU3ajFq5yn-h/view

**PS1.7.7.0:**
https://drive.google.com/file/d/1fpMFjWaEzzQ_LgVNiTVcAx2gse1gdcVV/view

It's a **regression**! I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by marionf** [comment]
I reopen the issue as the PR has been merged in develop instead of 1.7.7.x

**Comment by Progi1984** [comment]
Fixed by #22535
