### ISSUE TITLE
Connections source / http referrer database index

### ISSUE THREAD

**Issue by vavrecan** [PrestaShop/PrestaShop#22341]
#### Describe the bug
PREFIX_connections_source table has index on http_referrer which slows down insert queries and database performance. Dropping this index could increase database performance a lot!

#### Expected behavior

The index on http_referrer is not really needed and if necessary there should be separate table that does not have index on varchar column. 

#### Steps to Reproduce

n/a 

**Screenshots**

n/a

#### Additional information

* PrestaShop version: 1.7 - Latest - since beginning
* PHP version: all

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

what fo you think about that ?
Thanks!

**Comment by PierreRambaud** [comment]
There is an index on this field because it's used in `getOrderSources`, if we remove the index, we'll slow the select query.
Could you provide us a bench with/without the index in the table, and with/without a ton of data?

**Comment by hibatallahAouadni** [comment]
Hello @vavrecan,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by vavrecan** [comment]
its bad idea to do index on varchar column in this case, as this table has very frequent writes on high visitor load. Solution would be to index using CRC32 or create separate table for listing unique sources
