### ISSUE TITLE
Fuzzy Search - not working

### ISSUE THREAD

**Issue by SlaVkos** [PrestaShop/PrestaShop#22348]
Hello,
I updated my PS from 1.7.6.4 to 1.7.7.0. When i check fuzzy search i saw that she not working. In options (Preference -> Search) fuzzy search IS ON. My shop is cover4u.pl. Please help.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
