### ISSUE TITLE
Error during upgrade - Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#22347]
#### Describe the bug
I tried to upgrade from 1.7.6.9 to 1.7.7.0 with the module 1-Click Upgrade and PS generates the error: 
Maximum execution time of 30 seconds exceeded

![image](https://user-images.githubusercontent.com/33311857/101805641-469c5500-3b13-11eb-9139-2ea57b0dd16a.png)

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.32
* 1-Click Upgrade 4.11.0

**Comment by SimonGrn** [comment]
Hello @juraj1000,

your server seems to be under-dimensioned (it takes too long to extract the Zip). You should check if you can upgrade it. So far this is not related to a problem in the Core of PrestaShop.

You can alternatively try to set up a bigger limit for PHP by setting up [set_time_limit](https://www.php.net/manual/fr/function.set-time-limit.php) in you PHP configuration.

Thank you.
