### ISSUE TITLE
Error backend menu after upgrade 1.7.7.0

### ISSUE THREAD

**Issue by madito** [PrestaShop/PrestaShop#22350]
#### Describe the bug

After upgrade the menu of bakend is missing.

Error log:

Notice en línea 2083 en archivo [PATH_PRIVATE]/classes/controller/AdminController.php
[8] Undefined index: enabled

request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /configure/advanced/employees/toggle-navigation": Method Not Allowed (Allow: POST)" at [PATH_PRIVATE]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 141 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /configure/advanced/employees/toggle-navigation\": Method Not Allowed (Allow: POST) at [PATH_PRIVATE]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:141, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at [PATH_PRIVATE]/var/cache/prod/appProdProjectContainerUrlMatcher.php:6502)"} []

#### Steps to Reproduce

1. Upgrade 1.7.7.0

**Screenshots**

Image:

![menu](https://user-images.githubusercontent.com/5938785/101816108-e4e2e780-3b20-11eb-8d72-b1449a8d47e1.JPG)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: PHP 7.2.24

**Comment by SimonGrn** [comment]
Hello @madito,

thank you for your issue. This is a duplicate of #22250.

I close this issue, if you are interested you can subscribe on the issue linked above.

Thank you !

**Comment by SimonGrn** [comment]
Duplicate of #22250
