### ISSUE TITLE
Error in Checkout after Upgrade from  1.7.6.7 to 1.7.7 INTL_IDNA_VARIANT_UTS46 not defined

### ISSUE THREAD

**Issue by Kreysh** [PrestaShop/PrestaShop#22353]
**Describe the bug**

After the update any attempt to enter an order or payment ends with a page on this error shown below.

Error in: /order page

My current PHP version is 7.1, I tried 7.2 and 7.3 without success.
I assume this is an error in the update, it was previously updated from PrestaShop 1.6

**Steps to Play**

Update prestashop from version 1.7.6.7 to 1.7.7

![imagen](https://user-images.githubusercontent.com/40643252/101847873-fb923a00-3b32-11eb-9477-be0635dae83f.png)

NOTE: I have the files saved in case I have to regress, but I will lose the last state of the database, I would appreciate a tip or help.

PrestaShop version: 1.7.7.0
PHP version: 7.1

**Comment by Kreysh** [comment]
SOLVED - Just need a new library

**Comment by SimonGrn** [comment]
Hello @Kreysh,

thank you for your issue and your comment about the resolution, happy to hear it's working now.

**Comment by carribas1** [comment]
@Kreysh I have the same problem, what library have you used?

**Comment by matks** [comment]
@carribas1 ICU.

The error above is because the php version used by @Kreysh was using an old version ( lower than 4.6) of ICU http://site.icu-project.org/download/46

**Comment by carribas1** [comment]
@matks my php version is 7.3.25, I don´t know what kind of problem i have if my php version is the highest


![image](https://user-images.githubusercontent.com/75978432/102069852-9b371d00-3dfe-11eb-9d41-ec01d626db45.png)

**Comment by SimonGrn** [comment]
Hello @carribas1 
@matks was not talking about the PHP version but the ICU version. You can check what version you have through a `phpinfo()` page or ask your hosting provider.

**Comment by matks** [comment]
@carribas1 it's not the php version which is an issue, it's the ICU version.

You can have a recent ICU version with an old php version, you can have an old ICU version with a recent php version. It's 2 different things.

You need to upgrade your ICU version of your environment.

**Comment by nassssima** [comment]
I have the same pb !!! Plzzzzz help.

PS1.7.7.0 work only with php7.3 

And my  provider said "We have ICU version 4.21. with PHP 7.3 and below and ICU 68.2 with PHP 7.4."

So if I need ICU > 4.2 i must swish to php7.4 (where PS don't work)

I fixed the BO issues with the solution "INTL_IDNA_VARIANT_UTS46  to    intval(INTL_IDNA_VARIANT_UTS46)"

But still have pb FO  (costumer login), I'm really stuck in between , my shop not working more than 1 month... relaly need your help.
![Screenshot_1](https://user-images.githubusercontent.com/80653398/111088329-f627ff80-8526-11eb-98e7-749605e057b8.png)
