### ISSUE TITLE
[RESPONSIVE - BO] Order status pan on order view is overflowing his container

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22364]
#### Describe the bug

When you're on order view, status pan is too wide, it should be set as overflow scroll

#### Expected behavior

It should be set a overflow scroll

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Are you talking about Products tab and Status tab in Order page? If so, I did manage to reproduce the issue with develop, see the attached screen record below:

https://drive.google.com/file/d/1wbFhimJ3B_a3sYn_PLRH3nemJgRd_kuU/view

Thanks @NeOMakinG for the issue :wink:

**Comment by NeOMakinG** [comment]
Exactly @hibatallahAouadni :)
