### ISSUE TITLE
Wrong display of characters in headings backoffice

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#22366]
#### Describe the bug

Headings in PrestaShop BO is using font: **ubuntu-condensed_latin**

The version of the font, by PrestaShop 1.7.7 is **1.43.0**

This version does not include all polish characters. These are missing: ń ę ą ć ź ż

This cause a fallback to an other font.

The font must be updated to newest version: https://libraries.io/npm/@openfonts%2Fubuntu-condensed_latin/1.44.2

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.x

**Comment by florine2623** [comment]
Hi @MathiasReker ,
Thanks for the report.

There's indeed an issue in some area in the BO.
Example in dashboard :
![Capture d’écran 2020-12-11 à 14 48 12](https://user-images.githubusercontent.com/16019289/101911888-48245680-3bc1-11eb-98e1-02e4652ed763.png)

Please stay tuned !

**Comment by MathiasReker** [comment]
Thanks @NeOMakinG :-)

**Comment by NeOMakinG** [comment]
You're welcome!
