### ISSUE TITLE
Docker compose not working on 1.7.7.X 

### ISSUE THREAD

**Issue by Gerardlc** [PrestaShop/PrestaShop#22360]
#### Describe the bug

docker-compose up gets stuck 

#### Expected behavior

Finish the"docker-compose up" process successfully

#### Steps to Reproduce

1. Clon Prestashop repo
2. execute docker-compose up
3. Wait
4. Get stuck on 
```
prestashop-git    | >>> Building admin default theme...
prestashop-git    | ~/html/admin-dev/themes/default ~/html
npm WARN tarball tarball data for material-design-icons@2.2.3 (sha1-toFzZKeAOwUJqAAjBbf+IBsP2p8=) seems to be corrupted. Trying one more time.
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5434642/101893156-a68f0c00-3ba4-11eb-936d-59f79760a034.png)

#### Additional information

* PrestaShop version: 1.7.7-develop
* PHP version: >=7.2

**Comment by SimonGrn** [comment]
Hello @Gerardlc, why did you close this issue ? Did you find a solution ?

Thank you
