### ISSUE TITLE
[RESPONSIVE - BO] form-control-label has a padding on mobile causing wront styling

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22370]
#### Describe the bug

Every .form-control-labels got padding-left on mobile, causing form elements not being aligned with it

#### Expected behavior

Not having any padding-left

#### Steps to Reproduce

1. Go to Configurations pages, wherever you've a form, on mobile view

**Screenshots**

![image](https://user-images.githubusercontent.com/14963751/101913955-fd580e00-3bc3-11eb-84a8-04290953ff65.png)

#### Additional information

* PrestaShop version: develop

**Comment by prestascott** [comment]
Hey,

I thought about putting all the toggles on the right side of the screen like this so it's easier to read and manage:


![tooltips 14px](https://user-images.githubusercontent.com/54888056/102375403-c5d1d300-3fc2-11eb-83d6-03f241d1c965.png)

Also, we need to make sure that the tooltips can be closed by retaping on the icon: 
![tooltips touch 14px](https://user-images.githubusercontent.com/54888056/102375422-cbc7b400-3fc2-11eb-9d54-d31aa32fffe8.png)
