### ISSUE TITLE
Could you give us the ability to override pdf templates via theme?

### ISSUE THREAD

**Issue by ioweb-gr** [PrestaShop/PrestaShop#22387]
#### Is your feature request related to a problem?

We're trying to edit the invoice templates and order slip templates for PDFs but currently there seems to not be a way to override them in our theme or at least it's not documented in any way

#### Describe the solution you'd like

We would like to be able to follow a similar structure as we do for other templates, to override the core templates on the theme directory so it's upgrade-safe

#### Alternatives you've considered

Currently the only way to do this is to edit directly the templates or buy a marketplace addon to build all templates from scratch. However either way is too much cost in time and moeny to implement. Instead it should be a core function to edit these templates since they are not good for every country's laws and purposes.

**Comment by ioweb-gr** [comment]
Closing this issue because it's indeed possible but not documented. You can do in /themes/<yourtheme>/pdf directory. 
Please add this in documentation

**Comment by SimonGrn** [comment]
> Closing this issue because it's indeed possible but not documented. You can do in /themes//pdf directory.
> Please add this in documentation

Hello,

this is an open source project, you are welcome to help the maintainers by doing so 😄 

Thank you

**Comment by ioweb-gr** [comment]
What's the repo for docs?

**Comment by matks** [comment]
@ioweb-gr it's https://github.com/prestashop/docs 😉  it's using Hugo and Markdown
