### ISSUE TITLE
Specific price date format error

### ISSUE THREAD

**Issue by kalukramer** [PrestaShop/PrestaShop#22383]
#### Describe the bug

When I select a specific price on a product the prestashop automatic change the date form, from YYYY-MM-DD to DD/MM/YYYY and give an Error "The from/to date is invalid."
I have chenge the date format in language for the correct format, this stop working after change language to Portuguese

#### Expected behavior
Make a promotion (All versions of prestashop don't show to client thedate of begining and endig of promotion, in europe is a crime)

#### Steps to Reproduce

1. Go to 'specific price, select dates (start and ending)'
2. Click on 'Applay'
4. See error  "The from/to date is invalid"

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1.33

**Comment by SimonGrn** [comment]
Hello @kalukramer,

the datepicker you show on your screenshot is not the correct datepicker from PrestaShop (it looks like the jQueryUI one here). You may have a module that integrate a datepicker and this module breaks the official datepicker.
Try to disable your 3rd party modules one at a time to see if you can get the normal datepicker.

**Comment by kalukramer** [comment]
> Hello @kalukramer,
> 
> the datepicker you show on your screenshot is not the correct datepicker from PrestaShop (it looks like the jQueryUI one here). You may have a module that integrate a datepicker and this module breaks the official datepicker.
> Try to disable your 3rd party modules one at a time to see if you can get the normal datepicker.

WRong... This is a fresh instalation, don't have any 3th part module and use the classic theme too.
Note this is the 1.7.7 and I don't have install module yet this instslation have 3 days only.

**Comment by SimonGrn** [comment]
I understand. Can you try to quit the welcome module (Click on the link on the bottom left) ?
By the way I hope this is not a screenshot of your production shop because you showed everybody your admin url.

**Comment by SimonGrn** [comment]
OK so I tested on [demo.prestashop.com](http://demo.prestashop.com/) (you can try yourself) and I don't reproduce, so I'm pretty sure this is not a "fresh install". You can see for yourself:
![image](https://user-images.githubusercontent.com/49909275/101985726-07dcdb00-3c8a-11eb-8e24-030a91dc5b30.png)

Something is messing up your datepicker by including the jQueryUI one instead of the official from PrestaShop.

**Comment by kalukramer** [comment]
> OK so I tested on [demo.prestashop.com](http://demo.prestashop.com/) (you can try yourself) and I don't reproduce, so I'm pretty sure this is not a "fresh install". You can see for yourself:
> ![image](https://user-images.githubusercontent.com/49909275/101985726-07dcdb00-3c8a-11eb-8e24-030a91dc5b30.png)
> 
> Something is messing up your datepicker by including the jQueryUI one instead of the official from PrestaShop.

Nope wrong again, if you read again you will see, this appened after I change language to Portugese, in demo site you can't change the language.

And NO that address not exist. :) .... you can try acess. is a Sandbox with one IP connection.
And is a fresh instalation. Nothing instaled

**Comment by SimonGrn** [comment]
I'm sorry, I'm reading the "steps to reproduce" again and I don't see where you say we need to change the language ?
I'm providing a screenshot :
![image](https://user-images.githubusercontent.com/49909275/101987083-2fd03c80-3c92-11eb-93ae-9031144ddf32.png)

You need to be very specific and exhaustive. If you're skipping steps, we can't work correctly.

If you're talking about this line:
>I have chenge the date format in language for the correct format, this stop working after change language to Portuguese

I didn't understand what you were saying.

By the way, starting every comment with "wrong" is not very compliant with our Code of Conduct. Please remember you're talking to humans.

Edit:

I tried locally with a fresh install : 
![image](https://user-images.githubusercontent.com/49909275/101987283-6eb2c200-3c93-11eb-89a2-79963ee3e904.png)

It works perfectly. This problem is related to your environment or your configuration. 

Since I'm not able to reproduce, I close this issue. Feel free to open a new one if you have more information, we will be glad to investigate it.

**Comment by kalukramer** [comment]
> I'm sorry, I'm reading the "steps to reproduce" again and I don't see where you say we need to change the language ?
> I'm providing a screenshot :
> ![image](https://user-images.githubusercontent.com/49909275/101987083-2fd03c80-3c92-11eb-93ae-9031144ddf32.png)
> 
> You need to be very specific and exhaustive. If you're skipping steps, we can't work correctly.
> 
> If you're talking about this line:
> 
> > I have chenge the date format in language for the correct format, this stop working after change language to Portuguese
> 
> I didn't understand what you were saying.
> 
> By the way, starting every comment with "wrong" is not very compliant with our Code of Conduct. Please remember you're talking to humans.
> 
> Edit:
> 
> I tried locally with a fresh install :
> ![image](https://user-images.githubusercontent.com/49909275/101987283-6eb2c200-3c93-11eb-89a2-79963ee3e904.png)
> 
> It works perfectly. This problem is related to your environment or your configuration.
> 
> Since I'm not able to reproduce, I close this issue. Feel free to open a new one if you have more information, we will be glad to investigate it.

Thank for you help, but the problem presist, if I put prestashop in English the issue gone, if I put In Portuguese the Issue of date is present.
thank's again.

**Comment by cmcp-pt** [comment]
I have the same problem, after change to Portuguese, the specific price stop working.

**Comment by kalukramer** [comment]
> I have the same problem, after change to Portuguese, the specific price stop working.

I'm gonna send a message to "Vekia" if resolve I share with you.

**Comment by SimonGrn** [comment]
The issue you're facing is something is breaking the datepicker and reverting to some sort of old jQueryUI fallback. Is your cache cleared ? Can you try in incognito ? With another browser ?
Do you have any error in the Javascript console ?

**Comment by cmcp-pt** [comment]
Hi Simon
I have open a issue, here: https://github.com/PrestaShop/PrestaShop/issues/22390
This topic is confuse
Yes I used Crhome, opera and Maxthron.
I think is something with this new version, because I have other Store with ver 1.7.5 and date picker is different.

Thanks

**Comment by kalukramer** [comment]
Some one with the same problem

https://www.prestashop.com/forums/topic/520499-solved-datepicker-uses-wrong-date-format/

**Comment by kalukramer** [comment]
Hi.
By indication of Other user, I have errase the folder modules and copy folder from a fresh instalation, now everythink comes to normal, no error and date picker become normal too.
They said some native modules from prestashop get corrupted sometimes, and prestashop goes mad.
SOLVED
