### ISSUE TITLE
After upgrade to 1.7.7 clicking on any order in BO result in a symfony error - OrderShippingAddressForViewing construct must be of the type string, null given

### ISSUE THREAD

**Issue by mvanas** [PrestaShop/PrestaShop#22386]
#### Describe the bug

After update to 1.7.7. When clicking on an order in BO an error is the following error is received:
Type error: Argument 6 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderShippingAddressForViewing::__construct() must be of the type string, null given, called in /home/clients/de1d841a007f7bf58025eade33ee48e1/sites/dv0.zionburg.ch/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 269

#### Expected behavior

When clicking on an order in BO I should see all the order details including ordered products, shipping address, payment info.

#### Steps to Reproduce

1. Logon to BO
2. Select orders from the left pane
3. Click on any order

**Screenshots**
![image](https://user-images.githubusercontent.com/75885835/101983610-7155ed00-3c7c-11eb-9f1e-1047d0ab7705.png)
![image](https://user-images.githubusercontent.com/75885835/101983890-ff7ea300-3c7d-11eb-96b4-26d83755be29.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 2.7.34

**Comment by matks** [comment]
A bit similar to https://github.com/PrestaShop/PrestaShop/issues/22215

It looks like you have an address with undefined phone so the Order cannot be displayed

**Comment by hibatallahAouadni** [comment]
Hello @mvanas 

Could you please check if your issue is duplicate to this one #22215
And could you please provide your previous PrestaShop verion.

Thanks!

**Comment by ryan-wo-3t** [comment]
I also have this issue.  Upgrade from PS 1.7.6.5 to 1.7.7.0.  Some addresses for some customers produce an error like this where a string is expected but null is given.  

I have had some success by printing the invoice, then deleting the customer's address and re creating it.

This issue seems to only affect customers who created accounts that are several years old that were created in much earlier versions of ps...  likely 1.6.x.x

**Comment by hibatallahAouadni** [comment]
Hello @mvanas & @ryan-wo-3t 

I didn't manage to reproduce your issue with my shop PS1.7.6.5 upgraded to PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1-llvr7SrkC0mqNnIHLpA0A5qR5HdrMi9/view

I even edit the customer address and I didn't encounter any problem.
Please check and feedback.

Thanks!

**Comment by AldeaG** [comment]
I´m not a developer, just a plain user of Prestashop.
I had Prestashop 1.7.6.3 and just updated to 1.7.7 with 1-click module. 
I´m getting the same problems when clicking in backoffice orders
![Captura de pantalla 2020-12-31 a las 11 27 12](https://user-images.githubusercontent.com/61842395/103410910-d4e18500-4b6d-11eb-9e32-f5af7675a809.png)

**Comment by sergeksl** [comment]
to reproduce the error, it suffices to create a new customer and in the address not to encode anything in "mobile phone".
Version 1.7.7.0 does not support a null in this field.

**Comment by AldeaG** [comment]
so what is the solution, force to add the mobile phone?

**Comment by sergeksl** [comment]
yes it is a solution or automatically add a " " in this field

**Comment by hibatallahAouadni** [comment]
Hello @sergeksl 

Thanks for helping @AldeaG :slightly_smiling_face: 
> to reproduce the error, it suffices to create a new customer and in the address not to encode anything in "mobile phone".
Version 1.7.7.0 does not support a null in this field.

I tried creating a new customer with an address without "mobile phone" in BO and FO, and in both I didn't manage to reproduce your issue.
Could you please list step by step with every tiny detail to help me reproducing the issue.

Thanks in advance.

**Comment by neich78** [comment]
Happened the same to me when update to Prestashop 1.7.70. Now I cannot edit some orders, I get this message: 

![Captura de pantalla 2021-01-03 a las 21 18 05](https://user-images.githubusercontent.com/11721870/103487992-9831ba00-4e09-11eb-9aa0-9722c9367476.png)

**Comment by AldeaG** [comment]
Check if this helps:
https://github.com/PrestaShop/PrestaShop/issues/22215

**Comment by hibatallahAouadni** [comment]
Hello @neich78 

If your issue is similar to this #22611
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mvanas 

Could you please check if your issue is similar to this one #22611
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mvanas ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by obeba** [comment]
Hello after a fresh 1.7.7.2 install, import all old order, it's impossible to open old orders.

![bug ancienne commande prestashop](https://user-images.githubusercontent.com/5269037/109508555-42436080-7aa0-11eb-9c13-322c1dbaffbc.jpg)

The problem is solved when I comment:

foreach ($history as $item) {
            $statuses[] = new OrderStatusForViewing(
                (int) $item['id_order_history'],
                (int) $item['id_order_state'],
                $item['ostate_name'],
                $item['color'],
              new DateTimeImmutable($item['date_add']),
                (bool) $item['send_email'],
                $item['employee_firstname'],
                $item['employee_lastname'] 
            );
        }

in /public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php

**Comment by nikos83** [comment]
I have the same error after update from 1.7.5 to 1.7.7.2 
![image](https://user-images.githubusercontent.com/4093704/112128999-3e9a8980-8bc7-11eb-9f8f-314f3101faba.png)
Is that can be fixed by modify something in db ?  From where this $item['employee_lastname'] come from in db?
Comment on this @obeba  suggested helped but is it right solution for this?

**Comment by critiks** [comment]
This error happen when you change your configuration in the admin for country, deliveries, zones. This new configuration modify your adress id et country id. So, all adresses and customers bills appears in error.
Solution is to : delete wrong adresses in Admin > Customer > adress to regenerate them next time with good one IDs.

**Comment by nikos83** [comment]
In my case it looks like is related to the employee - assigned to the status change on order status change history. I have deleted some employee in the past. After dig in database I can see employee -with id 1 was assigned to the status change my order - but there is no employee with ID 1 it was deleted long time ago. Is there any other way to fix that issue?

**Comment by abcreationIT** [comment]
Already present in PrestaShop 1.7.7.4

Some fix???

**Comment by jatniel** [comment]
Hi, I have the same problem, in Prestashop 1.7.7.4

![Capture d’écran de 2021-06-14 16-13-23](https://user-images.githubusercontent.com/1070744/121906682-a1fe0880-cd2b-11eb-9f04-ca80a400b579.png)

**Comment by jatniel** [comment]
> This error happen when you change your configuration in the admin for country, deliveries, zones. This new configuration modify your adress id et country id. So, all adresses and customers bills appears in error.
> Solution is to : delete wrong adresses in Admin > Customer > adress to regenerate them next time with good one IDs.

I tested your idea, but it doesn't work!

**Comment by Achille616** [comment]
I solved it by going to Customers>Addresses> and select the customer name you are having the problem with from the address list, then select the three dots and "delete" deleting the address.
Then go into Customers and enter the customer that was giving you problems, scroll down and click + to add an address. In the form enter all the data, including phone and cell phone (maybe repeat the landline twice) and save it. Now try to see his order and you'll see that he won't give you any more problems :)   



Italian lenguage:  
Ho risolto, andando in Clienti>Indirizzi> e seleziona il nome cliente con cui si riscontra il problema dall'elenco degli indirizzi, poi seleziona i tre puntini e "elimina" cancellando l'indirizzo.
Poi vai in Clienti e entra nel cliente che ti dava problemi, scorri verso il basso e fai clic su + per aggiungere un indirizzo. Nel modulo inserisci tutti i dati, compreso il telefono e il cellulare (magari ripeti due volte il numero fisso) e salva il tutto. Ora prova a vedere il suo ordine e vedrai che non ti darà più problemi :)

**Comment by Davidorul** [comment]
Yeah. Everyone has his own workarounds or SQL hotfixes to address these issues.

Why does nobody suggest fixing the code ?

**Comment by Rogerfog** [comment]
In my case it was an automatic order status issue. I found that when migrating from 1.6 to 1.7, within ps_order_history one of the states (id_order_state) had ID 0. I changed the ID for all orders that failed from phpMyAdmin and now they all work.

**Comment by Gaja-A** [comment]
Hi,

I have the same problem in PS version 8.1.2

![image](https://github.com/PrestaShop/PrestaShop/assets/51961329/37e43dc8-aee1-429f-a3d7-ee817f85fc2e)

Any solution ?

Regards,
Gaja

**Comment by procent85** [comment]
Hello,
I have the same problem in 8.1.4 only if I have Memcached (Memcached via PHP::Memcached) turned on and connected to the server.

**Comment by marcodefelice** [comment]
The same problem exist on prestashop 9.2, I solved with these patch on Adapter/Order/QueryHandler/GetOrderForViewingHandler.php

`        return new OrderShippingAddressForViewing(
            $address->id,
            $address->firstname,
            $address->lastname,
            $address->company ?? '',
            $address->address1 ?? '',
            $address->address2 ?? '',
            $stateName,
            $address->city,
            $country->name[(int) $order->getAssociatedLanguage()->getId()],
            $address->postcode,
            $address->phone,
            $address->phone_mobile,
            $address->vat_number,
            $dni
        );
`
