### ISSUE TITLE
Customer Group Discounts are not showned since migration to 1.7.7.0

### ISSUE THREAD

**Issue by cleocreations** [PrestaShop/PrestaShop#22397]
#### Describe the bug

Special discounts are sets for each group of customer. Since the migration to 1.7.7.0, the discounts are not anymore showned on the frontend account page of each customer (it works if the discount is espacially done for the customer).

#### Expected behavior

Discounts have to be showned in each customer's "My discounts" page if he/she is a member of the group that can have the discount

#### Steps to Reproduce

1. **BO** > **SELL** > **Catalog** > **Discounts** > **Add a new cart rule**
2. In the **Conditions** tab, check the **Customer group selection** in the **Restrictions** section
3. Choose **Customer** as **Selected groups** and (for exemple) choose **Free shipping** in the **Actions** tab, then **Save**
4. Go to **FO** and access with the credentials of a customer that is a member the "Customer" group. 
5. Go to account page **Vouchers**
6. See that the discount is not shown there

#### Screenshots & screen records

**PS1.7.6.9:**
https://drive.google.com/file/d/1pNO0hS7UPnjgR-q7EdLjTmL13T0ekJ7A/view

**PS1.7.7.0:**
https://drive.google.com/file/d/18PBGO4_AEJCYGMXO1UCSka72L0-EpeQW/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @cleocreations 

I managed to reproduce the issue only with PS1.7.7.0, see the attached screen record:

https://drive.google.com/file/d/18PBGO4_AEJCYGMXO1UCSka72L0-EpeQW/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by marionf** [comment]
Hello @hibatallahAouadni 

Step 1 isn't very clear: "Create a discount for a group (for example discount for "Customer")" as there are different ways to create a discount for a group: with cart rules, with specific price and directly by applying a % discount for the customer group through shop paramters > customer settings > groups > edit.

Could you please specify this step and add your video in the first message ?
Could you please also specify the settings of the cart rule and what was the behavior in 1.7.6.x ?

Thank you

**Comment by cleocreations** [comment]
> specific

Sorry for being unclear... hibatallahAouadni did exactely as I have done.

**Comment by hibatallahAouadni** [comment]
Thanks @cleocreations for the clarification.
@marionf I just edit the issue and add videos with PS1.7.6.9 and PS1.7.7.0 to see the regression.

**Comment by Progi1984** [comment]
Fixed by #22518
