### ISSUE TITLE
[HOOK | IMPROVEMENT] Add a displayHeaderCategory hook

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#22392]
Recently you added back hook displayFooterCategory 
Please add also displayHeaderCategory hook. It would be great for my module which displays top sellers for each category and I believe that also for other modules.

**Comment by Hlavtox** [comment]
@web-plus Hi, I will do it.

I think it will be better to make the hooks universal - displayBeforeProductList and displayAfterProductList, so we can use it also on bestsellers page, search etc.

**Comment by web-plus** [comment]
Ahoj Danieli :-)

great news, thank you. Also, good idea making it more universal!

**Comment by hibatallahAouadni** [comment]
Hello @web-plus 

Thanks for the suggestion, the Dev Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers, do you think adding displayHeaderCategory hook will be convenient like @Hlavtox mentioned?

**Comment by PierreRambaud** [comment]
Both can be done :+1:

**Comment by hibatallahAouadni** [comment]
@PierreRambaud so you see it's good to accept @web-plus improvement and add the **`ToDo`** label ?

**Comment by Hlavtox** [comment]
@web-plus @hibatallahAouadni Done 👍
https://github.com/PrestaShop/PrestaShop/pull/22447

**Comment by web-plus** [comment]
Thank you! @Hlavtox
