### ISSUE TITLE
Problems with fuzzy search feature of 1.7.7.0

### ISSUE THREAD

**Issue by joaolago1113** [PrestaShop/PrestaShop#22393]
#### Describe the bug

The new fuzzy search function fails to search a specific product.

When I search for a product with reference "G2K108-AA13-10" in the products name, the search result fails to bring up any result, but if I search ""G2K108-AA13-1" instead (same refence but without last character) I get the product in the search result.

#### Expected behavior

Searching "G2K108-AA13-10" should bring up "EXTRACTOR FAN EBMPAPST G2K108-AA13-10", instead it doesn't find anything.

#### Steps to Reproduce

1. Search for product with the string "G2K108-AA13-10" in the name, using only the string "G2K108-AA13-1".
2. Should be able to find the product.
3. Search for the product using the full string ""G2K108-AA13-10".
4. Finds nothing.

**Screenshots**

Searching product using full reference string: 
![image](https://user-images.githubusercontent.com/22820692/101999425-d2a9aa80-3cd4-11eb-9589-364e8a3db2d5.png)

Searching product using only partially the reference string: 
![image](https://user-images.githubusercontent.com/22820692/101999427-d9382200-3cd4-11eb-9789-4dfeb1f9f70c.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @joaolago1113 

Could you please check if your issue is similar to this one #22081

Thanks!

**Comment by joaolago1113** [comment]
@hibatallahAouadni No, doesn't look like the same problem. The fact is the product doesn't show at all when I search for its full reference. 
I've seen a bug issue of this new fuzzy search function before it was released for the 1.7.7.0 version, which reported a problem with using characters like "-", and it could be related but I'm having trouble finding that issue now somehow.

PS: The max number of chars on a word is set to 30.

**Comment by joaolago1113** [comment]
@hibatallahAouadni 
I just fixed it!
I just recreated the entire index from the BO and it's alright now.
The index didn't miss any product, but recreating it fixed this issue somehow... maybe it's a good idea for people to recreate the index after updating to the new 1.7.7.0 version and using fuzzy search.

**Comment by hibatallahAouadni** [comment]
@joaolago1113 Thanks for your tip and glad to hear that your issue is fixed :tada:
