### ISSUE TITLE
[SOLVED] Specific price "The from/to date is invalid."

### ISSUE THREAD

**Issue by cmcp-pt** [PrestaShop/PrestaShop#22390]
#### Describe the bug

After change prestashop from English to Portuguese the specific price stop working and give an error "The from/to date is invalid."

#### Expected behavior

After configure a specific price and save, expect to work, but give error

#### Steps to Reproduce

1. Go to 'International, change language to Portuguese'
2. Click on 'products, select a product, price, specific price'
3. Add new specific price start from yyyy-mm-dd to yyyy-mm-dd, here after save it, they change automatic to dd-mm-yyyy
4. See error  "The from/to date is invalid."

I try to change the date format but still give an error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by cmcp-pt** [comment]
Hi Simon.
This is the error on console:
[NoPlugin] Searching for plugin objects...
/xxxx/xxxx/index.php/sell/catalog/products/specific-prices/add?_token=RhdPIjebnadyQ4orelyGVXXQO-9JBFKJk_-0p8YRpxA:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
DevTools failed to load SourceMap: Could not load content for chrome-extension://lpkmfpohnemhibkpgimjiamolggbfmpb/js/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by SimonGrn** [comment]
Hello,

Do you have Chrome extensions ? Can you try to disable them one by one and refresh the page ? The [NoPlugin] thingy is maybe related to the NoPlugin extension in your browser.

**Comment by cmcp-pt** [comment]
Hi Simon.

I think my problema is on date picker, they change the format if date after save.

**Comment by hibatallahAouadni** [comment]
Hello @cmcp-pt 

I didn't manage to reproduce with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/16oDLDSCUqq8VzsSOpPF2WCoGqkzVfYKd/view

Please check and feedback.
Thanks!

**Comment by kalukramer** [comment]
> Hello @cmcp-pt
> 
> I didn't manage to reproduce with PS1.7.7.0, see the attached screen record below:
> 
> https://drive.google.com/file/d/16oDLDSCUqq8VzsSOpPF2WCoGqkzVfYKd/view
> 
> Please check and feedback.
> Thanks!

Hi.
By indication of Other user, I have errase the folder modules and copy folder from a fresh instalation, now everythink comes to normal, no error and date picker become normal too.
They said some native modules from prestashop get corrupted sometimes, and prestashop goes mad.
SOLVED

**Comment by cmcp-pt** [comment]
> > Hello @cmcp-pt
> > I didn't manage to reproduce with PS1.7.7.0, see the attached screen record below:
> > https://drive.google.com/file/d/16oDLDSCUqq8VzsSOpPF2WCoGqkzVfYKd/view
> > Please check and feedback.
> > Thanks!
> 
> Hi.
> By indication of Other user, I have errase the folder modules and copy folder from a fresh instalation, now everythink comes to normal, no error and date picker become normal too.
> They said some native modules from prestashop get corrupted sometimes, and prestashop goes mad.
> SOLVED

I have Tried your Solution and it work's, many thanks
Obrigado pela ajuda

**Comment by hibatallahAouadni** [comment]
Thanks @kalukramer 
@cmcp-pt Glad to hear :tada:

**Comment by shana0780** [comment]
I have the same problem.  I replace the folder Module with a fresh but still the same.
![image](https://user-images.githubusercontent.com/59194234/103167879-44363c80-482f-11eb-86cd-1251e6129df0.png)

Prestashop 1.7.7
English to French

**Comment by kalukramer** [comment]
Can you show the date picker? What is format of date on employes? Lang?

**Comment by shana0780** [comment]
employee :

![image](https://user-images.githubusercontent.com/59194234/103168092-a80d3500-4830-11eb-86d4-34581c198900.png)

Language :

![image](https://user-images.githubusercontent.com/59194234/103168099-b9eed800-4830-11eb-94a9-1ef9ad7e5c64.png)

**Comment by shana0780** [comment]
Parameters

![image](https://user-images.githubusercontent.com/59194234/103168155-0e925300-4831-11eb-8a23-7baac872daef.png)

**Comment by kalukramer** [comment]
And date picker on specific price?

**Comment by shana0780** [comment]
And specific price

![image](https://user-images.githubusercontent.com/59194234/103168161-3386c600-4831-11eb-92f4-339cf7f8349e.png)

and if I pick a date

![image](https://user-images.githubusercontent.com/59194234/103168177-4f8a6780-4831-11eb-99df-7c006fab038a.png)

**Comment by kalukramer** [comment]
Try to change on employe the format date to Y/m/d
I still can't see the all date picker on specifc price

**Comment by shana0780** [comment]
> And specific price
> 
> ![image](https://user-images.githubusercontent.com/59194234/103168161-3386c600-4831-11eb-92f4-339cf7f8349e.png)
> 
> and if I pick a date
> 
> ![image](https://user-images.githubusercontent.com/59194234/103168177-4f8a6780-4831-11eb-99df-7c006fab038a.png)

It's not possible to change something on employee. I don't have a date format. I only have this

![image](https://user-images.githubusercontent.com/59194234/103168293-16062c00-4832-11eb-8223-9c8fe7b77b64.png)

and if I look in another shop, it's the same. I don't have this information on employee but there it works

**Comment by shana0780** [comment]
If I look the console, I have this error

No route found for "GET /sell/catalog/products/specific-prices/add": Method Not Allowed (Allow: POST)

[Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException 0]

**Comment by kalukramer** [comment]
![image](https://user-images.githubusercontent.com/17726525/103168467-6332cf80-482b-11eb-89f8-6146e79c0624.png)
Is in language

**Comment by shana0780** [comment]
> employee :
> 
> ![image](https://user-images.githubusercontent.com/59194234/103168092-a80d3500-4830-11eb-86d4-34581c198900.png)
> 
> Language :
> 
> ![image](https://user-images.githubusercontent.com/59194234/103168099-b9eed800-4830-11eb-94a9-1ef9ad7e5c64.png)

**Comment by shana0780** [comment]
d/m/Y like above

**Comment by kalukramer** [comment]
Do you have third part modules?

**Comment by kalukramer** [comment]
I don't see the all calandar on date picker

**Comment by shana0780** [comment]
> Do you have third part modules?

The module with PS 1.7.7 and I'm using the Cosmetic & Spa Store.

**Comment by shana0780** [comment]
![image](https://user-images.githubusercontent.com/59194234/103168558-6ed6c400-4834-11eb-94e6-9cd2caa41f81.png)

**Comment by kalukramer** [comment]
No, do you have installed a extra modules in 1.7.7?

**Comment by shana0780** [comment]
No only module from the Market place like Mondial Relay, RGPD, Crontab, Prestashop Checkout

**Comment by kalukramer** [comment]
![image](https://user-images.githubusercontent.com/17726525/103168618-9a55b080-482c-11eb-84ec-91a0b060dea4.png)
This is the correct datepicker on 1.7.7

**Comment by kalukramer** [comment]
Try do deactivate your extra mudules

**Comment by shana0780** [comment]
I have desactivated all the module from the themes, nothing change.  Still the same error.
In Debug Mode, I have this 

![image](https://user-images.githubusercontent.com/59194234/103169120-54ebb000-4839-11eb-85cd-2dc8f5d6c11f.png)


I try to reupload the file Vendor with a fresh one, but still the same error

**Comment by kalukramer** [comment]
In your other store, the datepicker is difrent, wright? The correct datepicker don't have slider for minutes and hours. In ver 1.7.7 only have the calendar. After I copy a fresh folder (from a fresh install) my problem was solved, and datepicker become correct, the problem is a module conflit for shure.

**Comment by shana0780** [comment]
> In your other store, the datepicker is difrent, wright? The correct datepicker don't have slider for minutes and hours. In ver 1.7.7 only have the calendar. After I copy a fresh folder (from a fresh install) my problem was solved, and datepicker become correct, the problem is a module conflit for shure.

Yes I have the minutes and hours. I will try to reinstall PS

**Comment by kalukramer** [comment]
Your prestashop is a fresh install or a upgrade from a previus version?

**Comment by shana0780** [comment]
> Your prestashop is a fresh install or a upgrade from a previus version?

A fresh one with the theme Spa & Cosmetic Store.  
And I have a second shop (but for the moment I have only installed the same module like Mondial Relay, Prestashop Checkout, Mollie... but with the original theme) and there it works.

**Comment by kalukramer** [comment]
> > Your prestashop is a fresh install or a upgrade from a previus version?
> 
> A fresh one with the theme Spa & Cosmetic Store.
> And I have a second shop (but for the moment I have only installed the same module like Mondial Relay, Prestashop Checkout, Mollie... but with the original theme) and there it works.

You have a conflit with theme, in my case, I have rename de module folder an copy a new one from a fresh install, if you rewrite the old one, wont work. Try it.

**Comment by shana0780** [comment]
I also think it's the theme.  First I try to reinstall PS.  If it doesn't work, I will try your solution ;)

**Comment by shana0780** [comment]
I have found the problem.  In the theme, there is a module "psproductcountdown" .
I delete the module and now it works well.

**Comment by kalukramer** [comment]
> I have found the problem. In the theme, there is a module "psproductcountdown" .
> I delete the module and now it works well.

Like I said, module problems, in this case is a module from theme.
Glad you solve you problem.

**Comment by douleal** [comment]
Hello,

I know that this issue has already been resolved, but I find myself in a similar situation. I use prestasho 1.7.7 in the Brazilian Portuguese language, I need the input format to be "d-m-Y". However, the default prestashop entry in the "specific price" field is "y-m-d". I already configured the format in languages, but it didn't work. I use a countdown module that uses the datepicker in the format I need "d-m-y", but since the prestashop in this field only receives "y-m-d" I believe it creates a conflict and I get the error "The from / to date is invalid."

Would anyone have a solution for this case?

![Captura da Web_14-2-2021_154937](https://user-images.githubusercontent.com/61319570/107886107-7cc3cf80-6edc-11eb-9728-a473e0e6745d.jpeg)

**Comment by kalukramer** [comment]
> Hello,
> 
> I know that this issue has already been resolved, but I find myself in a similar situation. I use prestasho 1.7.7 in the Brazilian Portuguese language, I need the input format to be "d-m-Y". However, the default prestashop entry in the "specific price" field is "y-m-d". I already configured the format in languages, but it didn't work. I use a countdown module that uses the datepicker in the format I need "d-m-y", but since the prestashop in this field only receives "y-m-d" I believe it creates a conflict and I get the error "The from / to date is invalid."
> 
> Would anyone have a solution for this case?
> 
> ![Captura da Web_14-2-2021_154937](https://user-images.githubusercontent.com/61319570/107886107-7cc3cf80-6edc-11eb-9728-a473e0e6745d.jpeg)

Se ler em cima vai entender que o seu datepicker está errado, esse formato é incorreto, voçê tem um modulo "estragando" o datepicker, vai ter que ir desativando um modulo de cada vez até encontrar o responsável, por ex o utilizador shana0780 tinha um modulo "psproductcountdown" a interferir com o datepicker.

**Comment by AlkhalidiAhmed** [comment]
Hi 
Please i have same problem , can i have help please 
![1](https://user-images.githubusercontent.com/105896049/221403496-75c274a3-a819-4c00-92ba-2629c65aadb6.png)
please im not devloper i need someone can help me 
Thank you

**Comment by kalukramer** [comment]
> Hi Please i have same problem , can i have help please ![1](https://user-images.githubusercontent.com/105896049/221403496-75c274a3-a819-4c00-92ba-2629c65aadb6.png) please im not devloper i need someone can help me Thank you

Hi.
You have a Module with problems and messing with de Datepicker, you must test by disabeling modules in folder modules.

**Comment by AlkhalidiAhmed** [comment]
Hi kalukramer
Thanks for helping , i try to disabeling all modules 1 by 1 but and still same problem 
please if i give you username and password for admin can you help me to fix this problem please 
Thank you

**Comment by AlkhalidiAhmed** [comment]
> > Hi Please i have same problem , can i have help please ![1](https://user-images.githubusercontent.com/105896049/221403496-75c274a3-a819-4c00-92ba-2629c65aadb6.png) please im not devloper i need someone can help me Thank you
> 
> Hi. You have a Module with problems and messing with de Datepicker, you must test by disabeling modules in folder modules.

Hi kalukramer
Thanks for helping , i try to disabeling all modules 1 by 1 but and still same problem
please if i give you username and password for admin can you help me to fix this problem please
Thank you

**Comment by kalukramer** [comment]
Hi...
the problem only can be solved by ftp and back office acess, if you have a new folder of modules to test like this user have do: https://github.com/PrestaShop/PrestaShop/issues/22390#issuecomment-751454560

**Comment by AlkhalidiAhmed** [comment]
> Hi... the problem only can be solved by ftp and back office acess, if you have a new folder of modules to test like this user have do: [#22390 (comment)](https://github.com/PrestaShop/PrestaShop/issues/22390#issuecomment-751454560)

Please Kalukramer , can you give me your email , i will send you FTP Username and Pass help me to solv this problem 
Thank you

**Comment by kalukramer** [comment]
my email is my nick  and gmail address

**Comment by kalukramer** [comment]
Problem solved. 😁

**Comment by Wanerys** [comment]
Hi all,
We have exactly same problem after a prestshop update (1.7.7 to 1.7.8.10). 
We try to desactivate modules but no effects.
We try to use old js datepicker files but no effects.

Do you have another idea? 
Thank you for your help.

**Comment by kalukramer** [comment]
> Hi all, We have exactly same problem after a prestshop update (1.7.7 to 1.7.8.10). We try to desactivate modules but no effects. We try to use old js datepicker files but no effects.
> 
> Do you have another idea? Thank you for your help.

This only can be fixed with acess by FTP and backoffice of prestashop

**Comment by Wanerys** [comment]
I have FTP access but how ?

**Comment by kalukramer** [comment]
You have to go via ftp to the module folder and rename it one folder at a time until you find out which one interferes with DatPicker
