### ISSUE TITLE
Cannot delete / edit product images

### ISSUE THREAD

**Issue by Gregg212x** [PrestaShop/PrestaShop#22409]
I have prestashop version 1.7.7.0.
When i wont edit or delete product img i not have a button and form in image product for delete image.

Scren:
![Screenshot_1](https://user-images.githubusercontent.com/61781333/102094465-a4d27c00-3e22-11eb-98ad-f2ba4c8d4206.jpg)

I use php 7.1
Presta is a fresh installation
I found bugs in debug mode: 

Could not load type "form": class does not exist.
Exception

Symfony\Component\Form\Exception\
InvalidArgumentException
in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php (line 86)

![Screenshot_2](https://user-images.githubusercontent.com/61781333/102095093-69847d00-3e23-11eb-9ef5-92dbab8ea81c.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/61781333/102095155-7acd8980-3e23-11eb-99e3-ed9e8c060bfb.jpg)

anyone knows how to fix it ?

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Gregg212x** [comment]
What information do you need ?

Prestashop wer. 1.7.7.0.
PHP : 7.1
The error appears when editing product photos
