### ISSUE TITLE
BreadCrumbList missing itemListElement

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#22404]
"itemListElement" in breadcrumblist is missing on some pages (seems it is fine on the product pages):

Example of the startpage:

<ol itemscope itemtype="https://schema.org/BreadcrumbList">
<li>
<span>Início</span>
</li>
</ol>

* PrestaShop version: 1.7.7
* PHP version: 7.3
* Multilanguage
* Multishop

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
