### ISSUE TITLE
BUG/Question of cms page additional fields

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#22415]
#### Describe the bug

In PS 1.7.5.4 i have one more field "page_type" in CMS.php and AdminCmsController.php 
and it works perfect in admin and available in template on front.
after migrate to 1.7.6.8 this does not work (i see some deprecated info and comment "With ps1.7.6.0, the Design => Pages page is migrated to Symfony." in #14536 
So.. this solution are not work since 1.7.6.* ? Or there is some change to do?

#### Expected behavior

CMS Page additional field added in CMS.php and AdminCmsController to works before 1.7.6 version.

#### Steps to Reproduce
described

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @madkot 

Let's ping the Developer team to answer your question.
Ping @PrestaShop/prestashop-core-developers could someone please tell us why he can't use additional field added in CMS.php and AdminCmsController like it was used be with PS1.7.5.4?

**Comment by matks** [comment]
Hi @madkot yes, when pages are migrated from the legacy framework of PrestaShop to Symfony, it might impact the modules hooked on the page. The system has changed.

Moreover if you had modified the code of AdminCmsController.php, this file was _removed_ from PS 1.7.6 and replaced with a Symfony Controller.

When a BO page is switched from legacy framework of PrestaShop to Symfony, the customizations need to be redone.

**Comment by madkot** [comment]
Which hook should I use? @matks

**Comment by matks** [comment]
@madkot there are generic hooks for this purpose, that must be something like `actionCMSFormBuilderModifier` or `actionCMSPageFormBuilderModifier`

See the documentation https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/#adding-new-form-field-to-customer-form

**Comment by madkot** [comment]
@matks thank you.
```
            && $this->registerHook('actionCMSPageFormBuilderModifier')
            && $this->registerHook('actionAfterCreateCMSPageFormHandler')
            && $this->registerHook('actionAfterUpdateCMSPageFormHandler');
```
These hooks do the trick.
