### ISSUE TITLE
Inconsistent schema.org usage of http:// and https://

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#22418]
#### Describe the bug

In pr #22417 review @PululuK noticed the usage of http:// in shema.org itemtype definition.

Both are fine but it is nice to be consistent: https://schema.org/docs/faq.html#19

#### Expected behavior

All schema.org itemtypes consistently use https:// 

#### Steps to Reproduce

```
git grep schema.org | grep 'http:'
git grep schema.org | grep 'https:'
```

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

Thanks for your issue and PR :smile: 

Ping @PrestaShop/prestashop-core-developers do you agree with @PululuK about replacing **`http://`** by **`https://`**?

**Comment by PierreRambaud** [comment]
Yes it's a good idea

**Comment by tswfi** [comment]
@PierreRambaud should the label be "pr available" (or whatever it was) as #22419 fixes this.

Actually is the labeling documented somewhere? might help new people (I know it would help me) to know what all of these labels mean to you :)

**Comment by PierreRambaud** [comment]
I don't know if the label is needed since GitHhub provides a way to find related PR:
![image](https://user-images.githubusercontent.com/1462701/102362504-c06d8c00-3fb4-11eb-85b7-433b9fdbe324.png)

**Comment by PierreRambaud** [comment]
But for labels, you should see with @PrestaShop/product-team :sweat_smile:

**Comment by LouiseBonnard** [comment]
Hi @tswfi, thanks for your contribution! As far as I know, there is no public documentation to introduce to the different labels used on this repository but what we could do is at least add and/or improve their descriptions [here](https://github.com/PrestaShop/PrestaShop/labels). :-)
