### ISSUE TITLE
SEO-Problem: Breadcrumblist error & "Offers", "review" or "aggregateRating" must be specified

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#22416]
#### Describe the bug
**itemListElement** in breadcrumblist is missing on some pages (seems it is fine on the product pages).
With the update to 1.7.7 google is showing a problem with missing **itemListElement** and some other bugs like:

`"Offers", "review" or "aggregateRating" must be specified`

 on some pages, it seems basically on the startpage and also some other category pages

#### Expected Behaviour 
would be to have full breadcrumblist with **itemListElement** and **Offers**, **review** or **aggregateRating** had to be specified on all pages available

#### Steps to reproduce
You would need to check the code, please also check my screenshot from the startpage of my prestashop installation, which is showing the "missing **itemListElement**" bug and displaying "**Offers**, **review** or **aggregateRating** must be specified" bug

1. Open this site https://search.google.com/test/rich-results
2. Paste your FO link
3. See errors

#### Screenshots
**"Offers", "review" or "aggregateRating" must be specified** bug:

https://drive.google.com/file/d/16aBG8tfPRGuo6XpHqh-C7k3E62p6sLLY/view

**missing "itemListElement"** bug:

https://drive.google.com/file/d/1kerCmPxQkaJ-wuP6Hs-pMnLFTwVfYH9T/view

![ps177_breadcrumbserror](https://user-images.githubusercontent.com/31710761/102126266-20e0ba00-3e4b-11eb-867d-bb82e9506c46.JPG)

#### Additional infos

- PrestaShop version: 1.7.7
- PHP version: 7.3
- Multilanguage
- Multishop

--> there is no technical problem - this is a SEO topic!
--> it seems also to be connected to multishops - as i did check it with another shop which is also mulitlanguage with the same languages, just not multishop installation.

**Comment by tswfi** [comment]
Google tool for testing rich results: https://search.google.com/test/rich-results

My 1.7.7.0 test shop which has multistore and multiple languages configured

Frontpage: 
![image](https://user-images.githubusercontent.com/1352132/102131339-ba639800-3e5a-11eb-8052-9fa2729de009.png)

First level category:
![image](https://user-images.githubusercontent.com/1352132/102131393-d5360c80-3e5a-11eb-9b33-d552e6283af5.png)

Second level category: 
![image](https://user-images.githubusercontent.com/1352132/102131510-fb5bac80-3e5a-11eb-8427-572fc1b5d3ad.png)

Product page:
![image](https://user-images.githubusercontent.com/1352132/102131642-2cd47800-3e5b-11eb-843e-0bb63812ac0e.png)

Discount products page:
![image](https://user-images.githubusercontent.com/1352132/102131827-78872180-3e5b-11eb-931e-6f7a9b436654.png)

Breadcrumbs all come from here: https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/themes/classic/templates/_partials/breadcrumb.tpl#L26

Your screenshot shows a `<div` before the `ol` which theme is this?

Looks like the `elseif` section is used on the homepage which does have some issues with not having enough data defined.

**Comment by decom-media** [comment]
the frontpage is having that problem, that is correct, but i am seeing the problem also on few other pages, like

* https://www.domain.com/en/sitemap (and of course all the other languages)
* on other root categories as well


![ps177_breadcrumbserror_2](https://user-images.githubusercontent.com/31710761/102199184-98523000-3ec3-11eb-82b9-6b9f460f4ede.JPG)

**Comment by tswfi** [comment]
@tom75 which theme?

And can you test my pr? The pr fixes all the pages in elseif section which includes sitemap page also.

**Comment by Hlavtox** [comment]
I think there are two problems:
- There is missing breadcrumb on sitemap page
- The main `<ol>` sitemap tag should not be displayed on homepage at all, becuase the homepage should not have no breadcrumb

**Comment by hibatallahAouadni** [comment]
Hello @tom75 

That's weird! I didn't manage to reproduce your issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/102227687-24774e00-3eea-11eb-9ed2-a5a7b47ddd2c.png)

Well, let's ping the Developers to check this out :wink: 

Ping @PrestaShop/prestashop-core-developers do you see this issue as a bug or an improvement?

**Comment by PierreRambaud** [comment]
> Hello @tom75
> 
> That's weird! I didn't manage to reproduce your issue, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/102227687-24774e00-3eea-11eb-9ed2-a5a7b47ddd2c.png)
> 
> Well, let's ping the Developers to check this out 
> 
> Ping @PrestaShop/prestashop-core-developers do you see this issue as a bug or an improvement?

It's up to the @PrestaShop/product-team to define it :)

**Comment by decom-media** [comment]
Well, as this is happening just with the update of 1.7.7 and with old versions it was no problem, i would consider it as a bug ;-)

**Comment by decom-media** [comment]
@PierreRambaud did you check it with a multistore and multilanguage installation?

**Comment by LouiseBonnard** [comment]
It looks like a bug to me as well, @tom75 and @hibatallahAouadni. :-)

**Comment by hibatallahAouadni** [comment]
Hello @tswfi & @tom75

Do you encounter this problem with fresh install 1.7.7.0 or with an upgraded shop? if with an upgraded shop could you please provide your previous shop version and the 1-click autoupgrade module version.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni It's a problem in the template. The problem is, that the last element of the breadcrumbs do not contain the structured data.

On home page, there is only 1 element in the breadcrumbs, so, the parent `<ol itemscope itemtype="http://schema.org/BreadcrumbList">` element exists, but has no children with `<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">`.

There are two possible fixes, both relatively easy:
1) Add this data to the last child of the breadcrumbs, if it is the correct way.
2) Remove breadcrumbs from index controller (homepage), because it does not make sense to have breadcrumbs, when you are on homepage.

**Comment by Hlavtox** [comment]
Breadcrumb list should contain the last item - https://schema.org/BreadcrumbList

> A BreadcrumbList is an ItemList consisting of a chain of linked Web pages, typically described using at least their URL and their name, and typically ending with the current page.

Small tweak to breadcrumb.tpl and all is fine:
![Výstřižek](https://user-images.githubusercontent.com/6097524/103882628-6441e780-50dc-11eb-80f2-dfb08eb8033c.JPG)

**Comment by decom-media** [comment]
@Hlavtox - whats the tweak exactly, as i could include it then as well as a workaround.

thanks

**Comment by Hlavtox** [comment]
themes/classic/templates/_partials/breadcrumb.tpl
I will make a PR if green light from PS team:-)

```
<nav data-depth="{$breadcrumb.count}" class="breadcrumb hidden-sm-down">
  <ol itemscope itemtype="http://schema.org/BreadcrumbList">
    {block name='breadcrumb'}
      {foreach from=$breadcrumb.links item=path name=breadcrumb}
        {block name='breadcrumb_item'}
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            {if not $smarty.foreach.breadcrumb.last}
                <a itemprop="item" href="{$path.url}"><span itemprop="name">{$path.title}</span></a>
            {else}
                <span itemprop="name">{$path.title}</span>
            {/if}
            <meta itemprop="position" content="{$smarty.foreach.breadcrumb.iteration}">
          </li>
        {/block}
      {/foreach}
    {/block}
  </ol>
</nav>

```

**Comment by tswfi** [comment]
there is already one pr #22417

**Comment by tswfi** [comment]
correction: two pull requests #22607 :D

**Comment by decom-media** [comment]
@Hlavtox thanks for that!

**Comment by Hlavtox** [comment]
@tswfi That PR is wrong, I will comment there ;-)

**Comment by Hlavtox** [comment]
https://github.com/PrestaShop/PrestaShop/pull/22607/ is good, but still does not fix, that there is no structured data for the last element.

https://github.com/PrestaShop/PrestaShop/pull/22417 - This is completely wrong. It changes the last element back to link and it messes up the position of breadcrumbs, because there is position=1 hardcoded.

**Comment by tswfi** [comment]
> #22417 - This is completely wrong. It changes the last element back to link and it messes up the position of breadcrumbs, because there is position=1 hardcoded.

it only happens when there is one element so the position is always one.

**Comment by Hlavtox** [comment]
@tswfi No, look what it does
![Výstřižek](https://user-images.githubusercontent.com/6097524/103888121-76c01f00-50e4-11eb-9b50-e87550d375ff.JPG)

**Comment by tswfi** [comment]
@Hlavtox hmm, I didn't catch that in my tests for some reason.

**Comment by tswfi** [comment]
oh, interesting. Google rich data checked does not complain about it https://search.google.com/test/rich-results

**Comment by tswfi** [comment]
@Hlavtox fixed the position and removed link from the last element.

but about the link.. I think there is another case here. On sitemap page the breadcrumbs only have one element which is the frontpage. It should have two elements, frontpage and sitemap page (without the link) (I think this is where I went south with the linking, I was checking the sitemap page...)

**Comment by Hlavtox** [comment]
@tswfi Yes, that's another bug, work has been done on breadcumbs, they are fixed almost everywhere, we forgot about sitemap page. :-)

EDIT: It's already fixed in develop 🚀

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Finally I reproduced it with PS1.7.7.0 and develop, see the attached screenshot below:

https://drive.google.com/file/d/1kerCmPxQkaJ-wuP6Hs-pMnLFTwVfYH9T/view

I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by marionf** [comment]
@hibatallahAouadni Is it a regression of the 1.7.7 ?

**Comment by hibatallahAouadni** [comment]
@marionf I didn't manage to reproduce it with PS1.7.6.5 the Breadcrump List issue but I did manage to reproduce this one #18692 , see the attached screen record below:

https://drive.google.com/file/d/16aBG8tfPRGuo6XpHqh-C7k3E62p6sLLY/view

IMHO, I think I should edit this issue to regroup these two issues in this one, wdyt?

**Comment by jimmydupre** [comment]
Hello everyone,

I join this issue because I encountered the same problem. For my part, I encountered this problem on the pages where there are product listings.

I removed the "itemscope" and "itemtype" attributes from the product.tpl file in the folder to fix the problem:
themes> classic> templates> catalog> _partials> miniatures

I therefore followed the instructions of Google which does not recommend the use of microdata in listings.
Here is the link as source:
[https://developers.google.com/search/docs/data-types/product#guidelines](https://developers.google.com/search/docs/data-types/product#guidelines)

I just wanted to attach my solution. Have a good day

**Comment by hibatallahAouadni** [comment]
Thanks @jimmydupre

**Comment by alfonsolr09** [comment]
> #### Describe the bug
> With the update to 1.7.7 google is showing a problem with missing (****itemListElement**** _fixed_for_1.7.7.2_) and some other bugs like:
> `"Offers", "review" or "aggregateRating" must be specified`
> 

this other bug was fixed?

**Comment by hibatallahAouadni** [comment]
> `"Offers", "review" or "aggregateRating" must be specified`

Not yet, here's the link of that issue #22962
