### ISSUE TITLE
BO - Order page - Ajax issue - when deleting the first product from an order, all other products will be removed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22424]
#### Describe the bug

In the BO > Orders > Old order > when deleting the first product from an order, all other products will be removed

#### Steps to Reproduce

1. Create an order from the FO with only one product
2. Go to BO > Orders > Last order created > Delete the product( without refresh)
3. Add demo_19 to the empty order
4. Add demo_1 or any other product to this order also
5. Delete the demo_19 => see error

https://drive.google.com/file/d/1KiDrVihz0agVsYHFbGi7aWfsdaSOemr7/view?usp=sharing

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/102202810-10225980-3ec8-11eb-89ce-cd8fb4953a3d.png)

PS: ok with PS1769: https://drive.google.com/file/d/1wup0qRMWMAECJlZu2_99l1DdY6UA2duF/view

#### Additional information

* PrestaShop version: 1770/177x
* PHP version: 7.2

**Comment by atomiix** [comment]
Hi @khouloudbelguith, It seems that this issue has been fixed by #21692. Can you confirm that you don't have the error anymore?

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Yes!
I did not manage to reproduce the issue with 1771build1
https://drive.google.com/file/d/1oLOTisGp1Jm-aBMJG9LDIMSBe22zrR4n/view?usp=sharing

I close the issue :smile: 
Thank you!
