### ISSUE TITLE
Module Manager not opening

### ISSUE THREAD

**Issue by fjoralbmuca** [PrestaShop/PrestaShop#22426]
PrestaShop 1.7.7.0 was in the middle of a module installation and then the module manager didn work.
Compile Error: Cannot declare class Mobile_Detect, because the name is already in use

[Symfony\Component\Debug\Exception\FatalErrorException 0]

I asked a backup restore on cpanel from 2 days ago (module manager was working) and still cant open it. Even module catalog shows error.
* PrestaShop version: 1.7.7.0
* PHP version: 7.1

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by kpodemski** [comment]
@fjoralbmuca 

> Compile Error: Cannot declare class Mobile_Detect, because the name is already in use

Error says that `Mobile_Detect` class is loaded twice in your store, I suggest to remove module you installed before error directly from FTP server, that might help.

**Comment by fjoralbmuca** [comment]
Removed in the Cpanel folder modules

**Comment by SimonGrn** [comment]
Hello,

please reopen an issue and follow the template, providing as much information as you can, and a 100% reproducible scenario.

Thank you.
