### ISSUE TITLE
[RESPONSIVE - BO] KPIs pan is sometime taking too much place on the page on mobile

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22422]
#### Describe the bug

KPIs pan is sometime taking too much place on the page on mobile

#### Expected behavior

Having an horizontal scroll, and the refresh button should be smaller

#### Steps to Reproduce

1. Go to sell/orders/
2. See KPIs pan height, it's taking too much place

#### Additional information

* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

You got a point :+1: reducing font-size and padding of these elements will be great :rocket: 
At least, the KPIs pan should only displayed two lines with Mobile device that is 375px wide:

![image](https://user-images.githubusercontent.com/23308427/102209776-92634b80-3ed1-11eb-945a-aec3454e7564.png)

Thanks for your issue and PR!

**Comment by prestascott** [comment]
Hello everyone,

How about horizontal scrolling through cards like this? 

![categories 4 (1)](https://user-images.githubusercontent.com/54888056/102375021-4c39e500-3fc2-11eb-804d-9faad1803f0f.png)
