### ISSUE TITLE
[RESPONSIVE - BO] TinyMCE is not responsive on migrated pages

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22420]
#### Describe the bug

TinyMCE is overflowing the content on mobile view

#### Expected behavior

TinyMCE icons adapt depending on the width they have free

#### Steps to Reproduce

1. Go to /sell/catalog/categories/
2. Edit any Category
3. Open mobile responsive mode, see the TinyMCE block

#### Additional information

* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks for your issue and PR :sweat_smile: 
Yes, I managed to reproduce with PS1.7.7.0 and PS1.7.6.9 (well with PS1.7.5.2 I didn't manage to reproduce, there's scrollbar)

![image](https://user-images.githubusercontent.com/23308427/102208425-b0c84780-3ecf-11eb-81ed-b9c0470d9138.png)

Thanks!
