### ISSUE TITLE
[Legacy default theme] - Improve style consistency of legacy pages

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22435]
#### Is your feature request related to a problem?

Legacy pages have old styles, while new theme received recent update (UIKit), which could be a bit improved in order to win some consistency, even if they are temporary

#### Describe the solution you'd like

We would require to change some styles :

- Buttons
- Forms
- Alerts
- Inputs
- Cards

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks for your issue and your PR.
Ping @prestascott we need your approval :sweat_smile:

**Comment by NeOMakinG** [comment]
I open it again, as It could be really improved, the first PR was a "first shot"

**Comment by hibatallahAouadni** [comment]
@NeOMakinG Should I change its position in Backlog from column **`Done`** to column **`To Do`**?

**Comment by NeOMakinG** [comment]
I did it @hibatallahAouadni
