### ISSUE TITLE
delivery note amount not correct in order view

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#22437]
#### Describe the bug

Order Amount is wrong on the order page, compared to the invoice amount - invoice is showing correct amount, deliver note is showing just the transport costs -->in the order page (not in the pdf documents itself)

#### Expected behavior

Amount should be same as invoice

#### Steps to Reproduce

1. Open an order
2. change the status to "processing in progress" (to generate the delivery note)
3. click on "documents" 
4. there is now one line for invoice and one for delivery note and the amount in the line of invoice is correct, but, the amount in the line of the delivery note is just the transport costs

![ps177_bug-wrongDeliveryNoteAmount](https://user-images.githubusercontent.com/31710761/102241370-2bf22380-3ef9-11eb-8b13-14b6a538dd66.JPG)

* PrestaShop version: 1.7.7
* PHP version: 7.3
* Multishop
* Multilanguage

**Comment by hibatallahAouadni** [comment]
Hello @tom75 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1nr0yOwUFZAHrMdBTFDX3-P_JTFIedjkU/view

Please check and feedback.

Thanks!

**Comment by decom-media** [comment]
Hello Hibatallah,

Your video shows exactly the same problem in your installation – as it is just not ok to just have the shipping costs in the line of the delivery note.

Best Regards
Thomas

**Comment by hibatallahAouadni** [comment]
Hello @tom75 

The amount of Delivery is new feature added to PS1.7.7.0, as you can see the amount is equal to shipping cost.
Ping @MatShir I believe the amount of Delivery is supposed to be equal to shipping cost, is that so?

![image](https://user-images.githubusercontent.com/23308427/102324481-360c3480-3f82-11eb-932b-eb96dd3f497c.png)

Thanks!

**Comment by decom-media** [comment]
Well, that would be strange, as the line is about the delivery slip, which is also linked there and also showing then (when you open it) not just the shipping costs - therefore (and also i think in older versions it was not like this) at least for me it would be just not logically

**Comment by hibatallahAouadni** [comment]
Hello @tom75 

With the oldest version, there's no amount displayed just "--", see the attached screenshot below (PS1.7.6.9):

![image](https://user-images.githubusercontent.com/23308427/102336378-627b7d00-3f91-11eb-81dd-9614e7cc7585.png)

Thanks!

**Comment by florine2623** [comment]
Hello ,

It is fixed on 9.0.0.

![Image](https://github.com/user-attachments/assets/7ffb0307-7a8e-4692-86a5-0e7898fb8b40)

I'm closing the issue.
Thanks!
