### ISSUE TITLE
Last Chrome browser version display security alert when creating new customer account

### ISSUE THREAD

**Issue by ludoc** [PrestaShop/PrestaShop#22430]
#### Describe the bug

Last Chrome browser version display security alert when creating new customer account

#### Expected behavior

There shouldn't be an alert that scares the visitor

#### Steps to Reproduce

1. Install the last version of Google Chrome, install PrestaShop 1.7.7 with HTTPS enabled
2. Go to https://shop_url/connexion?create_account=1
3. Fill the form and submit
4. See error (The information you’re about to submit is not secure)

![image](https://user-images.githubusercontent.com/1206153/102214813-1f5dd300-3ed9-11eb-93f8-fb48983cff8a.png)

#### Additional information

* PrestaShop version: 1.7.6.8 (and below maybe) to 1.7.7.0 
* PHP version: 7.3
* SSL and SSL everywhere On

**Comment by hibatallahAouadni** [comment]
Hello @ludoc 

I didn't manage to reproduce your issue with PS1.7.7.0 and the latest verion of Google Chrome:

![image](https://user-images.githubusercontent.com/23308427/102242774-b8e9ac80-3efa-11eb-9351-d37ea4be65be.png)

See the attached screen record below:

https://drive.google.com/file/d/15jtVy0rcp_1XWNn0WQyLJDGI35MxRjKM/view?usp=sharing

Please check and feedback.

Thanks!

**Comment by ghost** [comment]
Hello @hibatallahAouadni 
thank for your interest,

when I was notified of this issue by a customer (yesterday), I was not able to reproduce the issue on my computer with the same version of Chrome but today, I have the issue with a lot of Prestashop websites.

I rarely use Chrome, maybe it was not totally up to date, I don't know.
Try tomorow maybe or restart your computer, and tell me if you can reproduce the issue.


here is a video of the problem : https://www.youtube.com/watch?v=AIZvlzFZsiE&feature=youtu.be
Thanks

Ludovic

**Comment by kpodemski** [comment]
I can confirm this issue on PrestaShop 1.7.6.x and Chrome 87.0.4280.88

**Comment by matks** [comment]
It seems it is not 100% clear how Chrome displays its warning (some people have the scary info message, some have not) but nonetheless the root issue us clear: following a successfull customer creation, user is redirected to homepage without https even if the shop is full https.

So I suggest the following bug scenario instead:

1. Install the last version of Google Chrome, install PrestaShop 1.7.7 with HTTPS enabled
2. Go to https://shop_url/connexion?create_account=1 => _you're on HTTPS_
3. Fill the form and submit
4. You are redirected to homepage and _you're on http_

**Comment by ghost** [comment]
Some hosting company use reverse proxy and it could explain why some websites are not affected by this issue

I installed nginx in front of my web server and with this parameter : 
`proxy_redirect http:// $scheme://;`
alert is not displayed because the Location header of the backend response is rewrited to https

**Comment by ghost** [comment]
and : 

> The rollback configuration has been sent out, but it might take a couple of hours for it to reach clients. After that, restarting Chrome should disable the warning.

https://bugs.chromium.org/p/chromium/issues/detail?id=1158169

and indeed, the alert is no longer displayed on my computer.
Off topic but anyone know how they push new config without upgrading binaries ? (no change of version number / 87.0.4280.88)

**Comment by matks** [comment]
> and :
> 
> > The rollback configuration has been sent out, but it might take a couple of hours for it to reach clients. After that, restarting Chrome should disable the warning.
> Off topic but anyone know how they push new config without upgrading binaries ? (no change of version number / 87.0.4280.88)

Sorry, I can't tell you about Google secret backdoors on your computer 👀
