### ISSUE TITLE
Upgrade from 1.7.6.9 to 1.7.7.0 orders problem

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#22439]
Hi, after the upgrade in the orders section I see the orders like that and this is not right I think.
![orders](https://user-images.githubusercontent.com/54579601/102266272-e21d3380-3f20-11eb-9b62-930bc9a2e037.png)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by matks** [comment]
@sotirisa looks like a CSS issue.
I would suggest
- clear browser cache
- check there is no module plugged on Order page that would not be compatible with PS 1.7.7
- are you using php7.4 or php8 ? if yes, PrestaShop is not compatible with them (not yet)

**Comment by sotirisa** [comment]
Hi and thank you for your answer

I clear the browser cache
I didn't have any module on order
I had php 7.2

The post was wrong I try to make the upgrade from 1.7.6.7 to 1.7.7.0.
