### ISSUE TITLE
ps_newproducts is missing in 1.7.7.0, and stopped to work after upgrade from 1.7.6.4

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#22440]
#### Describe the bug

After upgrading to 1.7.7.0 from 1.7.6.4 the newest products dissapeared from the main page.

During digging I have noticed that ps_newproducts is nor present in a new prestashop installation, nor I can install it from the marketplace.

#### Expected behavior

Well, we want to have the newest products on main page...

#### Steps to Reproduce

Upgrade from 1.7.6 to 1.7.7?

#### Additional information

* PrestaShop version: 1.7.7.0 (bitnami docker image)
* PHP version: 7.3.25

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

I upgraded from 1.7.6.4 to PS1.7.7.0, go to **BO** > **IMPROVE** > **Module Catalog**, make a search by **ps_newproducts** and the module will be displayed, then install it:

![image](https://user-images.githubusercontent.com/23308427/102329611-e4b37380-3f88-11eb-94ea-245a07b4376e.png)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
