### ISSUE TITLE
[FO] Make a search with Alias composed with two words doesn't show any results

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#22444]
#### Describe the bug

After creating a new alias composed with two words (**tee shirt => sweater**), I tried to make a search in **FO** by the newly created alias (**tee shirt**), but there's no product displayed.

With **PS1.7.6.9**, it works perfectly (see the attached screen record below)

#### Expected behavior

Display the product contain the search term (**sweater**)

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Shop Parameters** > **Search**
2. Click on **Add new** alias button
3. Write **"tee shirt"** in **Alias** input and **"sweater"** (or **"t-shirt"**) in **Result** input, then **Save**
4. **FO** > make a search by **"tee shirt"**, there's no result

**Screenshots**

**PS1.7.6.9:**
https://drive.google.com/file/d/1Oa2a5H9NGHCWcY-Zbv2CAtaY8SbCRTCY/view

**PS1.7.7.0:**
https://drive.google.com/file/d/1xMsFjeVDWsXaCbvarI_pyD9ompaMZ6jI/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

_This bug is originally reported by @MatShir_

**Comment by ghost** [comment]
Héhé if you don't re index files it's normal :rofl:

**Comment by okom3pom** [comment]
![Uploading Capture d’écran de 2020-12-16 12-47-01.png…]()

**Comment by okom3pom** [comment]
![Uploading Capture d’écran de 2020-12-16 12-47-01.png…]()

**Comment by ghost** [comment]
![Capture d’écran de 2020-12-16 12-47-01](https://user-images.githubusercontent.com/5064590/102345562-e0de1c00-3f9d-11eb-96c2-b4cbfeea982f.png)

**Comment by ghost** [comment]
An other test with **okom3pom**

![Capture d’écran de 2020-12-16 13-02-14](https://user-images.githubusercontent.com/5064590/102353721-beea9680-3fa9-11eb-9830-5f4b83bdc52c.png)

**Comment by MatShir** [comment]
It's weird to have different behavior on the 2 versions 🤔

**Comment by ghost** [comment]
I think on prestashop 176 when you add an alias the shop reindex but is not a good way

On 177 the shop dont reindex u need to do manualy

Why not add a warning after adding ?

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Even after reindex manualy, I still manage to reproduce the issue :confused:

**Comment by ghost** [comment]
I use PHP 7.3 

https://cloud.ee.wtf/index.php/s/AdnYNWAD6Aa2r5j

**Comment by Progi1984** [comment]
Fixed by #22528
