### ISSUE TITLE
purge cache - error 500 (memcache)

### ISSUE THREAD

**Issue by mmangione-dev** [PrestaShop/PrestaShop#22445]
#### Describe the bug

#smarty: #
template compilation: force
cache: yes
cache type: filesytem
purge cache: clear cache everytime something has been modified

# cache #
cache type: CacheMemcache
Server: i added a memcache server that reside on the same web server.

When I go to click on "clear cache"
I get a 500 error back and the cache does NOT clear. To do this I have to manually restart memcache.

Here is the error.

[Wed Dec 16 11:04:35.121622 2020] [proxy_fcgi:error] [pid 30759:tid 47715123820288] [client 94.46.149.32:49942] AH01071: Got error 'PHP message: PHP Fatal error:  require(): Failed opening required '/home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/var/cache/prod/ContainerJihsaof/removed-ids.php' (include_path='/home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/vendor/pear/pear_exception:/home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/vendor/pear/console_getopt:/home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/vendor/pear/pear-core-minimal/src:/home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/vendor/pear/archive_tar:.:/usr/local/php73/lib/php') in /home/xxxxxxxxx/domains/xxxxxxxxx.xx/public_html/var/cache/prod/ContainerJihsaof/appProdProjectContainer.php on line 1627', referer: https://xxxxxxxxx.xx/adminxxxxx/index.php/configure/advanced/performance/?_token=aFXvhty2YlxUo4ogiK6Tb3dax1rdV6y3C1xdmxwmxP4bY

* PrestaShop version: 1.7.6.5
* PHP version: 7.3.14

**Comment by hibatallahAouadni** [comment]
Hello @mmangione-dev 

you should downgrade your PHP version to 7.2 cause PS1.7.6.5 is not compatible with PHP7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mmangione-dev ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
