### ISSUE TITLE
Update notification for Prestashop Checkout

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#22457]
#### Describe the bug
I use the module PrestaShop Checkout and notification doesn't work notification in BO if there is published a new version of this module. It means that a merchant doesn't see anything about new version in BO.
I've already reported this issue to the support of the module PrestaShop Checkout and here is their answer:

"This is indeed a behavior of the PrestaShop software. ... The cause of the updates not being correctly displayed is the script that empties updates' cache. This script should be executed every day normally. Most of the merchants can see the updates within 1 to 2 days of the release date."

I've also manually cleared the cache in BO (Advanced parameters > Performance > Empty cache) but "Module manager > Updates" didn't show any new update. 
If I manually download the new version of the module from addons.prestashop.com and then manually upload the new version to PS in BO then it works.

For other modules (e.g. Faceted search) update notification works correctly.

#### Expected behavior
If there is an update for the module PrestaShop Checkout it should be visible in BO. 

#### Steps to Reproduce
1. Go to BO > Modules > Module manager > Update => update is not visible

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.32

**Comment by florine2623** [comment]
Hi @juraj1000 ,

In PS 1.7.6.9, the update for PS Checkout is available in Module Manager > Checkout :
Before upgrade v2.2.0 :
![Capture d’écran 2020-12-17 à 11 14 53](https://user-images.githubusercontent.com/16019289/102474642-2ca1cb80-4059-11eb-85d5-6ce181c85ca1.png)
After upgrading -> v2.3.0 :
![Capture d’écran 2020-12-17 à 11 17 31](https://user-images.githubusercontent.com/16019289/102474877-7985a200-4059-11eb-9e0d-a2fd40fb4738.png)

Latest version available of the module is v2.3.0 :
![Capture d’écran 2020-12-17 à 10 31 31](https://user-images.githubusercontent.com/16019289/102474968-94581680-4059-11eb-8f29-0cce0568f86d.png)

**Comment by juraj1000** [comment]
Hello @florine2623,
I know there is the new version PS Checkout 2.3.0. But the issue is that there is no information about this new version in BO. As I wrote there is no notification about updated version in Module Manager > Checkout. This notification works correctly for all other modules but it doesn't work for PS Checkout.

![image](https://user-images.githubusercontent.com/33311857/102481776-7d69f200-4062-11eb-85aa-bd1c416c94f6.png)
