### ISSUE TITLE
error installl Prestashop 1.7.7.0 on xampp

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22450]
Hello i installing prestashop on Xampp and i have this error when i enter button named test your db...
![obrazek](https://user-images.githubusercontent.com/47187978/102350198-d4a98d00-3fa4-11eb-9238-7e1e90028a13.png)

**Comment by ghost** [comment]
I have Apache and MySQL ON

**Comment by matks** [comment]
@michalmichalcz Hi, it seems there is an error with your XAMPP setup. "An error occurred": is not something very accurate 😅  it's not possible to look for a bug with this.

You might find help here https://devdocs.prestashop.com/1.7/faq/i-need-help/

**Comment by SimonGrn** [comment]
I second @matks, please follow the template when reporting an issue. It's kinda rude to delete everything.
