### ISSUE TITLE
Cannot log into BO after upgrade from 1.7.6.7 to 1.7.7.0

### ISSUE THREAD

**Issue by nateBitworks** [PrestaShop/PrestaShop#22463]
#### Describe the bug

After upgrade to 1.7.7 cannot log in as customer or on backend

Expected to log in.

Front office:

1. Go to https://dev.centrevilletrailer.com
2. Try to sign in or create an account

**Screenshots**
This is a screen shot of the error that is given on the admin, and then the error on the front end is the same.
![image](https://user-images.githubusercontent.com/56446569/102415385-ae441b80-3fbd-11eb-9947-f0737c7b0139.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3.2
* I also read that it could be missing ps_customer_session or employee tables, I have both of those tables, I have emptied them and reinserted them, neither worked. There are NO remaining PHP errors as well. I read it could be a js issue so I tried to replace the js with the 1.7.6.7 js and that did not work either. 
*

**Comment by kpodemski** [comment]
Hey,

1. your store is in maintenance mode
2. if you see this error in back-office, you should enable developer mode, and check for Network tab (if you're using Chrome dev tools) and then see if there are any errors in XHR requests

**Comment by SimonGrn** [comment]
Hello @nateBitworks,

I see this error 
![image](https://user-images.githubusercontent.com/49909275/102461882-5eab3180-4049-11eb-82f2-e27d54154750.png)

which seems to indicate a wrong PHP version. Are you sure you're using PHP 7.3 ?

**Comment by nateBitworks** [comment]
I am using 7.3, I also tried on 7.1 as well. Both had the same results. My apologies as to the maintenance mode, that slipped my mind. I will check the Xhr requests.

**Comment by nateBitworks** [comment]
This is what is under xhr:
![image](https://user-images.githubusercontent.com/56446569/102505114-3c181900-4047-11eb-8578-27b60694d678.png)

**Comment by nateBitworks** [comment]
Hello, I have a new error:
Type error: idn_to_utf8() expects parameter 3 to be int, string given
![image](https://user-images.githubusercontent.com/56446569/102506009-4a1a6980-4048-11eb-8464-a534606eac95.png)

**Comment by matks** [comment]
> Hello, I have a new error:
> Type error: idn_to_utf8() expects parameter 3 to be int, string given
> ![image](https://user-images.githubusercontent.com/56446569/102506009-4a1a6980-4048-11eb-8464-a534606eac95.png)

Hi then you have the same issue as https://github.com/PrestaShop/PrestaShop/issues/22300

Solution is to upgrade your ICU version (see details in issue)

**Comment by nateBitworks** [comment]
If I return to 7.1 PHP will that work?

**Comment by hibatallahAouadni** [comment]
Hello @nateBitworks 

Your issue is a duplicate of #22300
Please upgrade your ICU version as @matks mentionned above.
So, I close the issue.
Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22300
