### ISSUE TITLE
Multistore - BO - Add new Order page - Cannot search a product when a shop from different Group is selected

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22460]
#### Describe the bug

In the BO > Orders > Add new order page > when a shop from a different group is selected, the search for Product is blocked
>I found this issue while testing this PR: https://github.com/PrestaShop/PrestaShop/pull/22020

#### Steps to Reproduce

1. Enable Multistore context
2. Create a new Group `Group2` (all options are enabled)
3. Create a new shop `shop2` associated with this Group
4. Go to BO > Orders > Add new Order page (shop2 is selected
5. Choose a customer
6. Search a product
7. See error in the console

**Screenshots**

177x, 1770: https://drive.google.com/file/d/1ub21MgbjosjH1AYxl2SRdQdrARn5qbye/view?usp=sharing
1769 => ok : https://drive.google.com/file/d/1-O6QaUr1q3SwuCpqbMsoyr8qlgjry5Hc/view

#### Additional information

* PrestaShop version: 177x, 1770
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @MatShir what do you think of the severity of this issue?

Thank you!

**Comment by emanborg** [comment]
Same issue here

**Comment by Progi1984** [comment]
Fixed by #22542
