### ISSUE TITLE
As a visitor: When you make a selection of new products, no products will appear

### ISSUE THREAD

**Issue by deepdishchase** [PrestaShop/PrestaShop#22467]
Basic prestashop theme.
When you click on a catagory (as a visitor)
You get a lot of selection boxes to make a selection of products.

Also: new / used etc. "Used" works fine, but "new" don't work, there will be no products shown.
Is this a common and known problem of Prestashop? Can this bug be fixed?

I'm just a Prestashop user.

**Comment by florine2623** [comment]
Hi @deepdishchase ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by deepdishchase** [comment]
Hi Florine,

 

Thanks for the information. First of all, English is not my native language so I can only explain myself in a simple way and it’s difficult to understand things on Github etc. The Prestashop website is also in Dutch, buth the other sites are not. Second of all, I don’t know anything about programming and stuff.
What I know, is that I have discovered a bug in a Prestashop template (the classic one, didn’t change it) made by the prestashop team (I think it is the template, but I’m not sure, I’m not a programmer). It’s like a jungle to tell about this bug. Maybe you can help me. If you don’t speak the language of programmers, how do I have to know what they want to know and what’s relevant and where the bug is coming from.

 

Met vriendelijke groet,

 

 

Jean-Pierre Timmermans

 

Mobiel | 06 504 72 221
E-mail | jean-pierre@palletvoorthuis.nl

Internet | www.palletvoorthuis.nl

 

 



 

Postadres | Bandoengstraat 50, 3531RN Utrecht

Afhaallocatie | Huurweerstraat 25, 3513EX Utrecht

 

Van: florine2623 <notifications@github.com> 
Verzonden: donderdag 17 december 2020 13:30
Aan: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
CC: deepdishchase <info@palletvoorthuis.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [PrestaShop/PrestaShop] As a visitor: When you make a selection of new products, no products will appear (#22467)

 

Hi @deepdishchase <https://github.com/deepdishchase>  ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report.
Read more about how we expect the issues to be handled here <https://build.prestashop.com/news/how-bug-reports-are-handled/> . Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
