### ISSUE TITLE
Prestashop registers more orders just having 1 unit in stock and not allowing sales out of stock

### ISSUE THREAD

**Issue by daniel-lineaymedia** [PrestaShop/PrestaShop#22478]
#### Describe the bug

Hello

I have a problem with the orders.

In the store with ps 1.7.6 if we don't have stock prestashop registers orders.

It happens to me that I have the last unit in stock but people buy it at the same time or have it in the cart and they can buy.

In the attached image you can see how 3 orders entered in the same minute for a product that only had one unit in stock. Prestashop by default lets you place the order and pay it to the customer and puts the stock at -2. 
The first of the orders is marked in correct but the rest are marked as paid and pending stock.

I have disabled everywhere that the store allows to sell if I do not have stock.

It is not the first time that happens to me.

![screenshot-www wanderlove es-2020_12 14-15_52_32 png fe9bc7ada12e30a8d81130ee085b62c1](https://user-images.githubusercontent.com/11094154/102512519-6c34db80-408a-11eb-995d-1ba8ee1ba956.png)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
