### ISSUE TITLE
Customization of description for categories is not responsive

### ISSUE THREAD

**Issue by Roomsmaniia** [PrestaShop/PrestaShop#22470]
#### Describe the bug

The display for changing color / adding a link / adding an image / adding a video in the description of a category is not responsive

#### Expected behavior

They are suitable for responsive display

#### Steps to Reproduce

1. On mobile go to BO > SELL > Catalog > Categories 
2. Edit a categorie > Description
3. Change text color / add a link / add an image / add a video

**Screenshots**

![image (2)](https://user-images.githubusercontent.com/73104293/102496953-5d452d80-4078-11eb-9027-d6e8b38b9907.png)
![image (3)](https://user-images.githubusercontent.com/73104293/102497002-69c98600-4078-11eb-9663-8b65e9f15810.png)
![image (4)](https://user-images.githubusercontent.com/73104293/102497032-71892a80-4078-11eb-94a5-2db0ed0fab97.png)
![image (5)](https://user-images.githubusercontent.com/73104293/102497035-72ba5780-4078-11eb-939e-b1f7cfe996fd.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by NeOMakinG** [comment]
Sadly it looks like it's a TinyMCE issue itself, it's really minor as you can move the window as you want tu use it, and if we want to change it ourself, that would be in a really unmaintainable way :/

**Comment by LouiseBonnard** [comment]
@NeOMakinG, are you suggesting nothing can be done on our end to fix it? If yes, I'll add the _won't fix_ label and close this issue, thanks!

**Comment by NeOMakinG** [comment]
We're blocked by TinyMCE on this yes, but it's not critical as it's usable, this modal is moovable :/
