### ISSUE TITLE
Filter options goes wrong. When choose new products menu disappear and no products show up

### ISSUE THREAD

**Issue by deepdishchase** [PrestaShop/PrestaShop#22475]
#### Describe the bug

I use some Dutch words because I don't know the exact translation. It's also in Dutch on the website.
When a visitor of the site choose a category of products, a page will open and the visitor can use "filteren op".
When you choose "gebruikt/used" under "staat" it will filter and show alle the used products. But when the visitor choose "nieuw/new" a part of the menu disappear and no product show up. 
Behind "nieuw/new" and "gebruikt/used" you see the right amount of products that has to show up.

#### Expected behavior

The same as the visitor choose "gebruikt/used". A selection of the right products and the menu "filteren op" stays the same.

#### Steps to Reproduce

The site is offline at the moment. But when it is online
1. Go to 'www.palletvoorthuis.nl
2. Click on 'pallets'
3. Choose 'nieuw' in the menu 'filteren op' > 'staat'

**Screenshots**

'gebruikt' works in the right way
![afbeelding](https://user-images.githubusercontent.com/76161889/102505696-997d8b80-4082-11eb-9591-bfc1051b9a64.png)

'nieuw' a lot disappears, no products show up
![afbeelding](https://user-images.githubusercontent.com/76161889/102505748-a8fcd480-4082-11eb-801a-6551266597f8.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* Theme: classic Versie 1.0.0 ontworpen door PrestaShop Team

**Comment by florine2623** [comment]
Hello @deepdishchase ,

I can't reproduce your issue on your shop (maintenance mode) or a test shop using PS 1.7.6.9. It seems like your issue comes from a configuration setting. Please make sure your faceted search module is well configured.

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by deepdishchase** [comment]
Hi Florine,

Thanks for the reply. I’m quiet sure that it isn’t a configuration problem. I didn’t change anything and also the menu disappears. 
I can add your IP to the maintenance IP, then you can experience the problem in an easy way, is that an option?

 

Met vriendelijke groet,

 

 

Jean-Pierre Timmermans

 

Mobiel | 06 504 72 221
E-mail | jean-pierre@palletvoorthuis.nl

Internet | www.palletvoorthuis.nl

 

 



 

Postadres | Bandoengstraat 50, 3531RN Utrecht

Afhaallocatie | Huurweerstraat 25, 3513EX Utrecht

 

Van: florine2623 <notifications@github.com> 
Verzonden: vrijdag 18 december 2020 09:51
Aan: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
CC: deepdishchase <info@palletvoorthuis.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [PrestaShop/PrestaShop] Filter options goes wrong. When choose new products menu disappear and no products show up (#22475)

 

Hello @deepdishchase <https://github.com/deepdishchase>  ,

I can't reproduce your issue on your shop (maintenance mode) or a test shop using PS 1.7.6.9. It seems like your issue comes from a configuration setting. Please make sure your faceted search module is well configured.

If you need help with your shop, please consider one of our support plans <https://www.prestashop.com/support> .

Alternatively, you can also ask for help in the community forums <https://www.prestashop.com/forums/>  or in the public Slack channel <https://github.com/PrestaShop/open-source/tree/master/slack> .

Thanks!
