### ISSUE TITLE
Faceted Search - Facet filters disappear and won’t come back after filter reset

### ISSUE THREAD

**Issue by sowebdev** [PrestaShop/PrestaShop#22488]
#### Describe the bug

During faceted search, when filtering on a feature with one value and no other filters can be shown, facet filters disappear and don't come back even after current filter reset.

#### Expected behavior

I expect the filters block to show up again when I reset my filter. Right now I have to refresh the page.

#### Steps to Reproduce

1. Go to backoffice and create a new feature and one new feature value
2. Add this feature and value to a product
3. Configure faceted search to enable the new feature as a filter. Disable some other filters like price or size that might always be available.
4. Go to frontoffice and select the category having the product
5. Filter on the new feature. The filter block should have disappeared (if not, disable remaining filters in the backoffice).
6. Try resetting the current filter. After reset the filters block is still missing and won't come back until you refresh the page.

**Screenshots**

![before_filtering](https://user-images.githubusercontent.com/3420316/102593712-7f40bd80-4115-11eb-80de-d46b030772bd.png)

![after_filtering](https://user-images.githubusercontent.com/3420316/102593731-85369e80-4115-11eb-9e44-8d38f6e82f67.png)

![after_reset](https://user-images.githubusercontent.com/3420316/102593756-8b2c7f80-4115-11eb-8cb8-0f90f168914e.png)

Screencast : https://drive.google.com/file/d/1V3Dao7COCSxKNmrPFD6YnqJ2I8hTtQJu/view?usp=sharing

#### Additional information

Tested on :
- Prestashop 1.7.6.9 + Facetedsearch 3.5
- Prestashop 1.7.7.0 + Facetedsearch 3.6

**Comment by florine2623** [comment]
Hi @sowebdev ,

I reproduced your issue using PS 1.7.7.0 and faceted_search module v3.6.0 and v3.7.0.
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by sowebdev** [comment]
@florine2623 I submitted a fix.

**Comment by ghost** [comment]
I submitted a fix for this because the previous PR was not followed up with for some reason.

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni  I made a PR for this issue. Please check.

**Comment by lalainarahajason** [comment]
This is resolved ? it appears with PS v8 and classic theme, the search column disappear after checking any checkbox and not come back until page refresh.

**Comment by lalainarahajason** [comment]
After some debug, the $listing variable is empty after ajax call in ps_facetedsearch.tpl even there is a results :
`{**
 * Copyright since 2007 PrestaShop SA and Contributors
 * ...
 *}


{$listing|@dump} <==== this is empty after ajax call ??

{if $listing.rendered_facets}
 ....
{/if}
`
