### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22484]
Hello, i type to browser localhost and the webpage say:
We can't start installation :(

    PrestaShop installation needs to write critical files in the folder var/cache. Please review the permissions on your server.

You can contact your web host provider to fix theses requirements.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
