### ISSUE TITLE
error "Cannot download language pack" during prestashop 1.7.7.0 installation

### ISSUE THREAD

**Issue by deman42** [PrestaShop/PrestaShop#22489]
When installing, I choose a Turkish language and the language pack cannot be downloaded. this error only occurred in the latest version. I had no such problem in previous prestashop versions.

![image](https://user-images.githubusercontent.com/76203825/102595966-896cb700-4129-11eb-96af-f8724458927a.png)

**Comment by florine2623** [comment]
Hello @deman42 ,

What language pack are your trying to download ?

Thanks

**Comment by deman42** [comment]
Hello @florine2623 ,
Turkish language pack. but even if i choose english it gives the same error

**Comment by deman42** [comment]
it says like this on error. I think there is a problem with ssl or certificate

file_get_contents_curl failed to download https://i18n.prestashop.com/translations/1.7.7.0/tr-TR/tr-TR.zip : (error code 77) error setting certificate verify locations:
CAfile: /home/babussif/public_html/var/cache/dev/cacert.pem
CApath: none

**Comment by florine2623** [comment]
You should be able to create your shop even without a SSL certificate.

I successfully created a new shop in English and in Turkish with PS 1.7.7.0.
![Capture d’écran 2020-12-18 à 14 48 30](https://user-images.githubusercontent.com/16019289/102621651-2b979980-4140-11eb-8fb0-18edc305e111.png)
![Capture d’écran 2020-12-18 à 14 51 16](https://user-images.githubusercontent.com/16019289/102621858-803b1480-4140-11eb-997e-effc6fad36c0.png)


You must check your server configuration. More info here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ 

I close your issue as it is a server config issue.
Thanks

**Comment by deman42** [comment]
When I try to install other versions on the same server, it does not give any error. it only gives error in 1.7.7.0 version. why could it be?

**Comment by deman42** [comment]
help me?

**Comment by mekamak** [comment]
The same problem happens with me.

**Comment by matks** [comment]
@deman42 Hi, I just completed successfully an install of PS 1.7.7.0 with Turkish language pack.

I am sorry but the issue is on your setup 😞 .

You try to install PS 1.7.7.0 with Turkish language pack, it fails.
I try to install PS 1.7.7.0 with Turkish language pack, it works. It's the same code.

We cannot help you as the issue only happen on your side 👎  if we cannot observe it, we cannot explore it.

Maybe you can have a look at the PrestaShop Company’s [support plans](https://www.prestashop.com/support), that's the only thing I suggest.

**Comment by deman42** [comment]
When I install it on localhost, I have no problem either. but when i install on hosting it fails. where are you installing?
