### ISSUE TITLE
Starnge behaviour when adding new cart rule and deleting, it's appears again

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#22486]
1. Unable to edit existing codes. Can't delete codes either. If you do, they will come back.
2. Also problems to post new codes.

See the attached video recording: https://youtu.be/bRe-EaAIeeU

PrestaShop version:  1.7.6.8
PHP version: 7.3.25

**Comment by florine2623** [comment]
Hi @dineshbadrukhiya ,

I can't reproduce the issue you're having.

PrestaShop 1.7.6.8 is not compatible with PHP 7.3, you need to downgrade to 7.2 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Also, *you must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thanks!

**Comment by dineshbadrukhiya** [comment]
I have downgrade PHP version: 7.2.34 but still same issue. I had attached video and I can also share the access details in private mail if you want to check.
