### ISSUE TITLE
Cannot save an old address after making the DNI mandatory for that country

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#22480]
PRESTASHOP VERSION 1.7.6.7

If you try to update (adding the DNI) or delete an address that has been previously used in an order and at the time of creation of the addess the dni was not required but now the dni is required for that country there will be an error and the address cant be updated or deleted and even worse a new address copy of the original will be created every time you attempt to update or delete the address.

**To reproduce the issue;**

1. In the front office create a new customer account, insert a test address WITHOUT the dni (usinga country that have dni _not_ mandatory ex:France) and complete an order. 
2. After the order is completed go in the back office in the section "International->Locations" and select the tab "Countries".
3. Find the country of the address you use on the order in point 1) ex:France and click "Edit"
4. At the bottom of the page on "Do you need a tax identification number?" select "YES" and the save the changes.
5. ![image](https://user-images.githubusercontent.com/9608268/102510665-2b3bc780-4088-11eb-812d-4f23da7221c3.png)
6. In the front office go to the "Home  Your account" section and enter in the "ADDRESSES" page.
7. ![image](https://user-images.githubusercontent.com/9608268/102511102-ac935a00-4088-11eb-9fa3-54b018f4f627.png)
8. Select the address you use for the order at point 1) and click "Update".
9. Insert a DNI and click "Save"
10. Now you get an Error "_address->dni is empty_"
11. If you return to the address list you will find a new address that has been created. Every time the error at point 10) happen a new address will be created.
12. The error happen also if you try to delete the original address without dni instead of edit it.

I've find the cause in `CustomerAddressPersister` in `function save(Address $address, $token)`.
If an address is used in an order it is not update or deleted but instead a new address is created and the old address is deleted. But  if the old address has been used previously in and order the old address is not deleted from the database but is flagged as "deleted" and so updated using `update()` function of `ObjectModel`. But as the old address has no DNI, because the dni was not required and mandatory at the time of the creation, the operation of update fail.

I've have modified the code of `function delete()` of the class `AddressCore` like in the image:
![image](https://user-images.githubusercontent.com/9608268/102514034-48729500-408c-11eb-9720-4b6d5b728418.png)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by abramofranchetti** [comment]
@SimonGrn But what information is missing?

**Comment by SimonGrn** [comment]
>You must follow the template to submit a complete bug report.

Please follow the template, do not delete everything. This is a lot of work to handle issues for an Open Source project, please respect us.

Thank you for your understanding.
