### ISSUE TITLE
ps_mainmenu problem

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#22492]
Hello,

I have had a problem for some time with the creation of CMS pages and the ps_mainmenu module. Indeed, I manage to create CMS pages with my first store but when I try to do it with my second store, I cannot access the page (ERR_TOO_MANY_REDIRECTS).
I have the lastest version of the module.

When I work around the error by creating my page through the first store and equating it to the second, the CMS page category and CMS page do not appear in the main menu module as if they did not exist.

 1- Create a CMS page on the store 1
 2- Create another CMS page on store 2 (I cannot access this tab on my side)
 3- Install the ps_mainmenu module on the two stores
 4- Integrate the CMS page into the main menu on each store

Here are screenshots of the situation.

I think this problem is linked to Prestashop multistore because everything works fine in single store. Is it possible to have a screenshot of cms tables in multistore? Indeed, I made a Prestashop update just before the multistore (to go to version 1.7.6.8).

Prestashop 1.7.6.8
PHP : 7.2.31
 Template store 1 : classic-child
 Template store 2 : classic-child

Thanks for your help.

**Comment by florine2623** [comment]
Hi @Amulliez ,

I can't reproduce your issue.
After creating a CMS page for each shop (shop 1 and shop 2) and adding their link to the main menu, it shows correctly on the front office :
**Shop 1 menu :**
![Capture d’écran 2020-12-18 à 11 10 29](https://user-images.githubusercontent.com/16019289/102602372-bb7a1b00-4121-11eb-8609-0c9fb8b528bd.png)

**Shop 2 menu :**
![Capture d’écran 2020-12-18 à 11 10 24](https://user-images.githubusercontent.com/16019289/102602340-b1581c80-4121-11eb-80ef-f35746b16cf7.png)

It seems like a configuration issue.
 If you have questions about using PrestaShop, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by Amulliez** [comment]
Hi @florine2623 ,

Thanks for your help. 
Is it possible to have the tables file concerning the CMS pages in multistore mode? Maybe it's due to the update I made.

Thanks.
