### ISSUE TITLE
Fatal error in module file - unable to access modules

### ISSUE THREAD

**Issue by ColbellHHS** [PrestaShop/PrestaShop#22493]
Good Morning,

I am unable to access modules from the Prestashop dashboard. When I click on the modules tab I am given a screen with the following error;

**[PrestaShop] Fatal error in module file :/var/www/vhosts/hhands.co.uk/httpdocs/modules/autoupgrade/upgrade/install-4.9.0.php:
Call to private method Autoupgrade::registerHookAndSetToTop() from context ''**

At this point I have to reload the Dashboard.

This is repeatable.

All other area of the dashboard work with no issues.

Kind Regards

**Comment by florine2623** [comment]
Hello @ColbellHHS ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thanks
