### ISSUE TITLE
Error sending email in prestahop 1.7.7.0

### ISSUE THREAD

**Issue by estenolotienenadie** [PrestaShop/PrestaShop#22504]
Hello everyone, I am trying to configure the office365 email of my Godaddy hosting and it is impossible, apparently it is because it is not to select the STARTTLS encryption tip.
I have tried TLS encryption and SSL encryption and it doesn't work, STARTTLS encryption is not on the list. Please can you tell me what the problem is?
Thank you.
Alberto.
![ERROR](https://user-images.githubusercontent.com/64229330/102644977-02880080-4162-11eb-91b7-88e6d1b57659.png)
![131945682_459761715013537_8425455600202043064_n](https://user-images.githubusercontent.com/64229330/102645061-277c7380-4162-11eb-850e-1271b2ad8400.jpg)
![131155280_727242811247236_7536312439957022223_n](https://user-images.githubusercontent.com/64229330/102645068-28150a00-4162-11eb-8d26-d8b0ccb914e6.jpg)
![131703171_1029420764224095_8879371866595107458_n](https://user-images.githubusercontent.com/64229330/102645069-28ada080-4162-11eb-8dfb-96c64ce2f46f.jpg)

**Comment by SimonGrn** [comment]
Hello,

Please use the template, do not delete everything, instead fill the sections. We cannot accept issues where the template was deleted.

Moreover, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
