### ISSUE TITLE
Prestashop logo 

### ISSUE THREAD

**Issue by estenolotienenadie** [PrestaShop/PrestaShop#22505]
Hello, good afternoon, I have installed prestahop 1.7.7.0 and the emails that are received, the position of the logo is no longer centered on the page, it is on one side. Could you inform me if it will be like this in this version? I attach a photo.
Regards,
Alberto.
![logooo](https://user-images.githubusercontent.com/64229330/102645956-91e1e380-4163-11eb-82f8-6a058876c68f.jpg)

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @estenolotienenadie 

> I have installed prestahop 1.7.7.0

Do you mean you already had a shop and you upgraded to 1.7.7.0 or just fresh install? And could you please edit your issue and fill these blocks (Steps to Reproduce, Additional information, ...).

_PS:_ **You must follow the template to submit a complete bug report**. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Thanks!

**Comment by estenolotienenadie** [comment]
Good morning, thanks for your replay, for instance in my domain fabricantedelsofa.com with prestashop 1.7.5.2 when I place an order or send a message from the contact form, i receive a confirmation message and the logo of the store is in the center of the screen as you can see in the first photo
![1](https://user-images.githubusercontent.com/64229330/102768091-e01ffe00-4380-11eb-8a31-e94a02b1f714.png)

and the black line covers the entire length and the text below says: SU MESSAGE TO THE SOFA MANUFACTURER'S CUSTOMER SERVICE.

As you can see in this other photo that corresponds to the update.fabricantedelsofa.com store with version 1.7.7.0, when a message is sent from the customer service center or an order is placed in the store, the message received comes with the logo on the left, it is not centered, and the informative text only says ..... Hello ..... and the black bar below the text is short

![2](https://user-images.githubusercontent.com/64229330/102768209-16f61400-4381-11eb-9723-1d48aa3725ad.png)

![3](https://user-images.githubusercontent.com/64229330/102768224-1bbac800-4381-11eb-95a1-e9375cddd364.png)

Please feel free to contact me if you need any further information.
Regards,
Alberto.

**Comment by hibatallahAouadni** [comment]
Hello @estenolotienenadie 

Sorry for the late response, it's not a bug it's the modern email theme :wink: 
You just need to set your email configuration. So, please follow these steps:

1. **BO**>**IMPROVE**>**Design**>**Email Theme**
2. **Configuration**> Select **Classic** as **your default email theme**, then **Save**
3. **Generate emails**> Select **Classic** as **your email theme** and your language 
4. Then **Classic** as **Select the theme you want to overwrite**
5. Check the **Overwrite templates** option 
6. Click on **Generate emails** button
7. Test the emails => Ok 

See my attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103139030-433ec700-46d8-11eb-93e4-a2d6bd21b768.png)

Please check and feedback.
Thanks!

**Comment by estenolotienenadie** [comment]
Hello, thanks for your replay, now is working.
Regards,
Alberto.
