### ISSUE TITLE
Adding invalid parameter to Language form and "No picture" image causes a crash.

### ISSUE THREAD

**Issue by JevgenijVisockij** [PrestaShop/PrestaShop#22500]
#### Describe the bug

When you enter invalid parameters to language(whether add or edit) and add a new "No Picture" image you get a crash, but "No Picture" image saves anyway. 

#### Expected behavior

When adding an invalid parameter to language proper error should be shown and not an exception. Also, it shouldn't save "No Picture" image if form is invalid.

#### Steps to Reproduce

1. International -> Language
2.  Edit Your primary language
3. Add invalid value( for exampel name = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ).
4. Add "No picture" image.
5. Save (Should get crash here)
6. Check products in front office, products with no image should have the image you have added (which should have not happened). 

**Screenshots**

![image](https://user-images.githubusercontent.com/47781757/102630621-7243be80-4155-11eb-83c9-5cefaa348025.png)

#### Additional information

* PrestaShop version: 1.7.8(develop).
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @JevgenijVisockij ,
Can you specify which PS version you are using ?
Thanks!

**Comment by JevgenijVisockij** [comment]
> Hello @JevgenijVisockij ,
> Can you specify which PS version you are using ?
> Thanks!

Oh sorry forgot it. Updated the bug report.

**Comment by florine2623** [comment]
Thanks !

I managed to reproduce the bug :
![Capture d’écran 2020-12-18 à 17 38 33](https://user-images.githubusercontent.com/16019289/102638707-39591900-4158-11eb-90a1-b88eb9b6c74f.png)

After encountering the bug, no-image image still shows :
![Capture d’écran 2020-12-18 à 17 41 27](https://user-images.githubusercontent.com/16019289/102638765-50980680-4158-11eb-89a6-474cf844e1a5.png)

So I will add this to the debug roadmap.

Thanks!

**Comment by marionf** [comment]
@florine2623 @hibatallahAouadni  Is it a regression compared to 1.7.7.x ?

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

No, it's a not regression cause I reproduced it with PS1.7.6.7, PS1.7.6.9 and PS1.7.7.0.
But, this issue is only occured while creating a new language with name: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

> Edit Your primary language

I didn't reproduce it while editing my default language or any other language, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/102767105-61769100-437f-11eb-955e-248f2c142c35.png)

I just had an error message **`Cannot add language with invalid data`** even with debug mode enabled.

Thanks!

**Comment by JevgenijVisockij** [comment]
> Hello @marionf
> 
> No, it's a not regression cause I reproduced it with PS1.7.6.7, PS1.7.6.9 and PS1.7.7.0.
> But, this issue is only occured while creating a new language with name: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> 
> > Edit Your primary language
> 
> I didn't reproduce it while editing my default language or any other language, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/102767105-61769100-437f-11eb-955e-248f2c142c35.png)
> 
> I just had an error message **`Cannot add language with invalid data`** even with debug mode enabled.
> 
> Thanks!

I am able to reproduce this fully on fresh PS1.7.6.9. I wonder what could we do diffrently.

Product without image(but uses default "No picture" image.
![image](https://user-images.githubusercontent.com/47781757/102773691-5711c280-4392-11eb-89ef-b49493be40c6.png)

Attempting to save primary Language. Changed name to aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa and added different "No picture" image.
![image](https://user-images.githubusercontent.com/47781757/102773747-6b55bf80-4392-11eb-9c95-7af700809e57.png)

Result from save(Debug mode is off by default).
![image](https://user-images.githubusercontent.com/47781757/102773787-7c063580-4392-11eb-9dce-bc7f9058ab6a.png)

Same product with,  "No picture" image changed successfully despite form crashing.
![image](https://user-images.githubusercontent.com/47781757/102773835-8d4f4200-4392-11eb-9f04-de82bd5b4799.png)

**Comment by hibatallahAouadni** [comment]
Hello @JevgenijVisockij 

Could you please confirm if this PR #21878 could fix this issue or no?

Thanks!

**Comment by JevgenijVisockij** [comment]
Yes it would

**Comment by hibatallahAouadni** [comment]
ok thx :slightly_smiling_face:

**Comment by JevgenijVisockij** [comment]
Hey!

Yes it would.

EDIT: This was supposed to be before
> ok thx slightly_smiling_face

But I deleted it since I wanted to modify it slightly, but wasn't fast enough.
