### ISSUE TITLE
Problem with emails

### ISSUE THREAD

**Issue by AdrienLps** [PrestaShop/PrestaShop#22513]
Hello,

I encountered a rather annoying problem on Prestashop 1.7.7.1! I no longer receive any email when there is an order on my site. When I change the order status, my customers no longer receive the email and also when I reply to a service message.

**Comment by matks** [comment]
Sounds similar to https://github.com/PrestaShop/PrestaShop/issues/22262

**Comment by AdrienLps** [comment]
Problem solved thanks anyway

**Comment by SimonGrn** [comment]
Duplicate of #22262
