### ISSUE TITLE
npm run build in Classic theme themes/classic/_dev/ not correct in windows

### ISSUE THREAD

**Issue by FabioFormenti** [PrestaShop/PrestaShop#22511]
#### Describe the bug

In windows 10 i have an error using:
npm run build
in Classic theme themes/classic/_dev/

In C:\wamp64\www\PrestaShop\themes\classic\_dev\package.json
 "scripts": {
    "build": "NODE_ENV=production webpack --progress --colors --debug --display-chunks",
is not correct for windows.
#### Expected behavior

This is correct
    "build": "set NODE_ENV=production & webpack --progress --colors --debug --display-chunks",

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello,

As far as I know we don't officially support windows as a development platform.

Can you confirm this @matks or @PierreRambaud?

**Comment by matks** [comment]
I think we support Windows as development platform, but not as production platform 🤔  .

Ping @NeOMakinG can you please help us?

**Comment by PierreRambaud** [comment]
You can use [Git for Windows](https://gitforwindows.org/) and everything will be working well.

We can't change the build command because it's how Unix/Linux systems are working, but with Git Bash, you can use the same syntax in Windows :)

**Comment by NeOMakinG** [comment]
I would recommend to use Git Bash too

**Comment by hibatallahAouadni** [comment]
Hello @FabioFormenti 

I agree with @PierreRambaud & @NeOMakinG, you should use Git Bash and you will not face any problem.
After download [Git](https://gitforwindows.org/), click on Git icon with the (mouse) right button and choose open **Git Bash** and then execute the command:

`npm run build`

_**PS:** Don't forget to check if the npm is installed_ :wink: 

So, I close the issue cause it's not related to the PrestaShop Core.
Thanks guys for your quick replies :rocket: 

Thanks!
