### ISSUE TITLE
Order by customer with account before upgarde throws address error sometimes.

### ISSUE THREAD

**Issue by ryan-wo-3t** [PrestaShop/PrestaShop#22510]
>  Oops... looks like an unexpected error occurred.
> 
> Type error: Argument 4 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderShippingAddressForViewing::__construct() must be of the type string, null given, called in /var/www/domain.com/public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 269
> 
> [Symfony\Component\Debug\Exception\FatalThrowableError 0]

Please let me know what further information to include.

PS Version 1.7.7.0

**Comment by ryan-wo-3t** [comment]
Here's the stack trace:

> Symfony\Component\Debug\Exception\FatalThrowableError:
> Type error: Argument 4 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderShippingAddressForViewing::__construct() must be of the type string, null given, called in /var/www/domain.com/public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 269
> 
>   at src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php:90
>   at PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderShippingAddressForViewing->__construct(85, 'dalene', 'leneve', null, '3052Nazko rd', null, 'British Columbia', 'Quesnel', 'Canada', 'V2J7E9', '250-249-5594', null)
>      (src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:269)
>   at PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderForViewingHandler->getOrderShippingAddress(object(Order))
>      (src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:186)
>   at PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderForViewingHandler->handle(object(GetOrderForViewing))
>      (vendor/league/tactician/src/Handler/CommandHandlerMiddleware.php:71)
>   at League\Tactician\Handler\CommandHandlerMiddleware->execute(object(GetOrderForViewing), object(Closure))
>      (vendor/league/tactician/src/CommandBus.php:62)
>   at League\Tactician\CommandBus->League\Tactician\{closure}(object(GetOrderForViewing))
>      (src/Core/CommandBus/Middleware/CommandRegisterMiddleware.php:79)
>   at PrestaShop\PrestaShop\Core\CommandBus\Middleware\CommandRegisterMiddleware->execute(object(GetOrderForViewing), object(Closure))
>      (vendor/league/tactician/src/CommandBus.php:62)
>   at League\Tactician\CommandBus->League\Tactician\{closure}(object(GetOrderForViewing))
>      (vendor/league/tactician/src/CommandBus.php:42)
>   at League\Tactician\CommandBus->handle(object(GetOrderForViewing))
>      (src/Core/CommandBus/TacticianCommandBusAdapter.php:54)
>   at PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter->handle(object(GetOrderForViewing))
>      (src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:401)
>   at PrestaShopBundle\Controller\Admin\Sell\Order\OrderController->viewAction(7217, object(Request))
>      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
>   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
>      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
>   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
>      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
>   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
>      (admin/index.php:82)

**Comment by SimonGrn** [comment]
Hello,

> Please let me know what further information to include.

try to follow the template you get when you click on "New Issue", and don't delete everything. There is not enough information provided to reproduce your issue and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by jf-viguier** [comment]
Duplicate of issue https://github.com/PrestaShop/PrestaShop/issues/22386
