### ISSUE TITLE
Error sending emails - STARTTLS not supported

### ISSUE THREAD

**Issue by estenolotienenadie** [PrestaShop/PrestaShop#22517]
#### Describe the bug

Is imposible to send emails from office 365 account, in encryption only apear TLS and SSL, and not apear STARTTLS and apear this error.

![33](https://user-images.githubusercontent.com/64229330/102777126-48c2a700-4390-11eb-8b91-f995f2b4ceda.png)

#### Expected behavior

It should say message sent and receive it correctly

If prestashop is not working with STARTTLS encryption just let me know.
If i use one email from gmail this one works fine, but when i recieve the email this email apear as unsafe.
If this is not posible please let me know which payment email i have to buy to use it in Prestashop to work without problems by means of SMTP.

**Screenshots**

![11](https://user-images.githubusercontent.com/64229330/102777145-50824b80-4390-11eb-8fd1-5444c40575f5.png)
![22](https://user-images.githubusercontent.com/64229330/102777154-5415d280-4390-11eb-8b98-86f44b9758e2.png)
![44](https://user-images.githubusercontent.com/64229330/102777169-58da8680-4390-11eb-98dd-562d0e2f1d47.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3
Thank you very much.

**Comment by SimonGrn** [comment]
Hello,

Please change your screenshots, they show everything including your admin URL which is a huge security risk.

**Comment by estenolotienenadie** [comment]
Hello, sorry, I have already deleted the information.
Regards,
Alberto.

**Comment by matks** [comment]
Hello @estenolotienenadie so if I try to summarize your post, it is "PrestaShop allows the use of SMTP with SSL, TSL but STARTTLS is not available"?

**Comment by hibatallahAouadni** [comment]
Hello @estenolotienenadie 

Could you please confirm that your issue is that **STARTTLS is not available** as @matks mentionned?
If so, it's not a bug, it's an improvement :wink: 
Waiting for your confirmation.

Thanks!

**Comment by estenolotienenadie** [comment]
Hello, sorry for delay, yes, my hosting Goddady give me one office365 email and in the configuration apear encryption STARTTLS and i think this is the problem thats why apear this error:
Connection could not be established with host smtp.office365.com :stream_socket_client(): unable to connect to smtp.office365.com:587 (Network is unreachable)
Could you suggest me where I can buy an email service so that I can configure it with my prestashop store so I don't have to use gmail? 
Thank you.

**Comment by estenolotienenadie** [comment]
I have already solved the problem.
Thank you.

**Comment by soufyan** [comment]
@estenolotienenadie could you tell us how you resolved your issue ? I'am in the same situation with a office365 smtp using STATTLS encryption

Thanks

**Comment by alt126je** [comment]
@estenolotienenadie como lo resolviste finalmente para configurar con STATTLS
Gracias

**Comment by estenolotienenadie** [comment]
Hola, no usé STATTLS, después de muchas conversaciones con el proveedor de hosting, agregamos este TXT a las DNS y de esta forma puede enviar correos normalmente con la configuración predeterminada de Prestashop.

v=spf1 include:spf.protection.outlook.com include:secureserver.net -all

Espero que le ayude.
Un saludo,
Alberto.

**Comment by 1linkmega** [comment]
> 

Hola, que configuración utilizaste para registrar este txt en los DNS?

**Comment by estenolotienenadie** [comment]
Hola, utilice la siguiente configuración:

v=spf1 include:spf.protection.outlook.com include:secureserver.net -all

Espero te funcione.
Saludos.
