### ISSUE TITLE
RTL language currency name problem

### ISSUE THREAD

**Issue by javadalmasi** [PrestaShop/PrestaShop#22522]
In rtl stores, the currency symbol is on the right, but this is if the currency symbol should be on the left
Note the image below
https://s17.picofile.com/file/8418381342/Screenshot_2020_12_21_%D9%BE%D9%88%D8%B3%D8%AA%D8%B1_%D9%87%D9%85%D8%B1%D8%A7%D9%87_%D8%A8%D8%A7_%D9%82%D8%A7%D8%A8_%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86_%D9%87%D8%A7_%D8%AF%D8%B1_%D8%B1%D8%A7%D9%87%D9%86%D8%AF_%D8%A7%D8%A8%D8%B9%D8%A7%D8%AF_40x60_%D8%B3%D8%A7%D9%86%D8%AA%DB%8C_%D9%85%D8%AA%D8%B1.png

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
