### ISSUE TITLE
Increase the key description of the webservice account

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#22536]
#### Is your feature request related to a problem?

A current limitation of the key description is 32 characters on the webservice page.

#### Describe the solution you'd like

I suggest to increase it to 256 characters.

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

Do we need the **Product Team** or **Core Developers** approval for this one? or should I add the label **`To Do`**?
