### ISSUE TITLE
Return a useful message when "page not found" happens for AJAX calls

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22538]
#### Is your feature request related to a problem?

When user tries to use a route that does not exist like `/aka?a=aididpsop` he is displayed the "Not Found" FO page.
But if he tries to reach a _ajax route of a module that does not exist_ the user only gets a blank page. Example `/aka?a=aididpsop&fc=module&module=blockreassurance&controller=d&action=RecordJSHookExecution&ajax=true`

#### Describe the solution you'd like

When user tries to reach a ajax route of a module that does not exist the user only gets a helpful message.

I submit a PR.

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your issue and your PR.
Do you need the **Product Team** approval?
