### ISSUE TITLE
Prestashop 1.7.7 admin panel unable to login

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/PrestaShop#22544]
#### Describe the bug

Cannot login to the management panel. 500 error returns.

#### Expected behavior

I cannot login and I want to be able to login.

#### Steps to Reproduce

**Screenshots**

https://prnt.sc/w7x9k5

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1.33

**Comment by matks** [comment]
Hi this is probably the bug reported on https://github.com/PrestaShop/PrestaShop/issues/22300

Please check your ICU version and upgrade if it's below 4.6 😉

**Comment by aytekinazmi12** [comment]
> 
> 
> Hi this is probably the bug reported on #22300
> 
> Please check your ICU version and upgrade if it's below 4.6 😉

Hello, thank you. the problem is fixed.
