### ISSUE TITLE
Cannot add an official currency when an non-CLDR compatible language exists

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#22545]
#### Describe the bug

When a non-CLDR compatible language exists (for instance, a manually added language with iso_code = aa & language = en-TS) and you try to add an Official currency, an error is displayed.

#### Expected behavior

You should be able to add a currency even with a non-official language.

#### Steps to Reproduce

1. Add a non-existing language in International > Localization > Languages (iso code: aa, language: en-TS)
2. Try to add a new Currency, DZD for instance. You'll get an error that says Can not find CLDR data for currency DZD

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @atomiix 

I managed to reproduce the issue with develop, but I didn't reproduce it with 1.7.7.x
So, it's a regression :wink: 

Thanks for your issue!

**Comment by atomiix** [comment]
I'm not able to reproduce this issue anymore, I think #24274 fixed it
