### ISSUE TITLE
Error in Product::setWsProductBundle

### ISSUE THREAD

**Issue by pakka63** [PrestaShop/PrestaShop#22551]
https://github.com/PrestaShop/PrestaShop/blob/153d72457a1f37eb9acd04542876dde5063a7059/classes/Product.php#L7946
The label id of product_attribute is "**id_product_attribute**" and not "**product_attribute_id**" as the "schema=synopsis" said in the api XML of product resource (line 632)

**Comment by matks** [comment]
Hi @pakka63 it's a little bit short 😅  if you want to report a bug, can you please use the template? https://github.com/PrestaShop/PrestaShop/issues/new?template=1_bug_report.md

It's very important for us 😉

**Comment by hibatallahAouadni** [comment]
Hello @pakka63 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
