### ISSUE TITLE
[BO - Products] while adding two specific prices in row the user is selected

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#22552]
#### Describe the bug

Try to add a specific price to a product, then add another one, you will see that the selected user for the previous specific price is already selected

#### Expected behavior

When creating a new specific price for a product all the form should be reset.

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**>edit product
2. Go to **Pricing** tab
3. Click on **Add a specific price** button
4. Fill in the fields and click on **Apply** button
5. Click on **Add a specific price** button again
6. See the error, the **Customer** is not reset in the new form

**Screenshots**

https://drive.google.com/file/d/145wtc_hF3kRppknyNCzSl9gzo4hH0sN_/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by MatShir** [comment]
Fixed on the new product page on PS 8.1
