### ISSUE TITLE
Not enough data provided in hookActionProductCancel

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22569]
#### Describe the bug

I wanted to fix https://github.com/PrestaShop/ps_googleanalytics/issues/84, but I cannot get enough information from the hook in 1.7.7. There is only **id_order_detail**.

#### Expected behavior

The hook should provide information about:
- What product is getting cancelled. ✔️ 
- How many pieces are cancelled ❌
- What amount of money is refunded ❌

#### Steps to Reproduce

1. Hook any module to hookActionProductCancel.
2. add `print_r($params);` and `die;` to this hook.
3. Go to any order, do partial refund.
4. See that only id_order_detail is present.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Following your steps, that's what I got:

![image](https://user-images.githubusercontent.com/23308427/103020671-1dcf8300-4549-11eb-9973-89488c89a8e4.png)

I believe what you're asking for is an improvement, cause it's not a bug, it's just PrestaShop limitation :wink: 
So, ping @PrestaShop/prestashop-core-developers would you like the idea of adding more infos than **id_order_detail**?

PS: @Hlavtox why I couldn't trigger this hook with PS1.7.6.9? :confused: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni I don't know, I also could not make it work... :-D

**Comment by PierreRambaud** [comment]
I didn't manage to reproduce the issue too, I've got the same result as @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@PierreRambaud exactly :wink: @Hlavtox is asking to provide more infos within this hook

**Comment by PierreRambaud** [comment]
@Hlavtox You're already able to retrieve such information via the `id_order_detail`

**Comment by Hlavtox** [comment]
@PierreRambaud You can't (if I am not missing something), because during the canceling, the merchant can enter how many pieces and how much money he wants to "refund".

If it was just Cancel product = cancel whole id_order_detail, then it would be fine of course.

**Comment by PierreRambaud** [comment]
You're also able to reach data with the ObjectModel listener which will tell you the new value.
If you think it's too complicated and is not suitable for what you're needed, we accept to add parameters in the hook call :) $
Feel free to create a pull request :+1:

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/22686
