### ISSUE TITLE
Module statsbestcategories  total sales is bad

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22563]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Make on order with a discounted product 
2. Check the total on a category 

**Screenshots**

![Capture d’écran de 2020-12-23 12-22-26](https://user-images.githubusercontent.com/5064590/102991539-ae8e6a80-4519-11eb-9ac3-6d9cc3bf51d6.png)
![Capture d’écran de 2020-12-23 12-22-00](https://user-images.githubusercontent.com/5064590/102991540-afbf9780-4519-11eb-9375-0fc240a4a575.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR :slightly_smiling_face: 
I managed to reproduce it with PS1.7.6.9 and PS1.7.7.0.

Thanks!
