### ISSUE TITLE
BO - Webservice - Webservice key is empty

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22565]
#### Describe the bug

In the BO > Advanced Parameters > Webservice page, when we try to add a web service key with special characters, it will be empty

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Webservice page 
2. Create a webservice key with this `<LDEXRUXFJHJI69FZWBXHNRKQ3W6VFU>` Key
3. Save
4. See the error
5. Select All => Try to disable with bulk action
6. See exception

![image](https://user-images.githubusercontent.com/16067358/103008895-1baff900-4536-11eb-8cfb-88f72cf5b19e.png)

#### Additional information

* PrestaShop version: 1769, 1770, develop (1780)
* PHP version: 7.1

**Comment by dborovsky** [comment]
@LouiseBonnard  yea I reproduced this issue too. I would like to help fixing it.

**Comment by LouiseBonnard** [comment]
Hi @dborovsky, thanks for your help on this! You can read the [CONTRIBUTING.md](https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTING.md) to get a few information about the PrestaShop contribution. :-)

**Comment by agostinofiscale** [comment]
Hi guys! I would like to help you with this problem. 

I found where the problem arises:

```
  case self::TYPE_STRING:
    default:
      if ($with_quotes) {
          return '\'' . pSQL($value) . '\'';
      }
  
  return pSQL($value);
```

What's happen here is that the string get sanitized from pSQL() function and will return an empty value, indeed if we pass it like:

```
  case self::TYPE_STRING:
    default:
      if ($with_quotes) {
          return '\'' . pSQL($value) . '\'';
      }
  
  return pSQL($value, true);
```

Where "true" set the $htmlOK parameter, it will work fine.

We could blacklist some characters to avoid this happen but i'm not sure it's the best solution, we could also put the type of the key on "TYPE_NOTHING" and use the validate "isCleanHtml".

Just like:

`'key' => ['type' => self::TYPE_NOTHING, 'required' => true, 'size' => 32, 'validate' => 'iscleanhtml'],`

@LouiseBonnard, what do you think about it?

**Comment by agostinofiscale** [comment]
Should I ping anyone? @khouloudbelguith

**Comment by matks** [comment]
Hi @agostinofiscale it looks like `pSQL()` does something wrong for me 🤔 .

There must be a way to store characters like `<` and `>` in SQL in a safe way? Like escape them?

**Comment by agostinofiscale** [comment]
> Hi @agostinofiscale it looks like `pSQL()` does something wrong for me 🤔 .
> 
> There must be a way to store characters like `<` and `>` in SQL in a safe way? Like escape them?

Hi @matks, it could be a good solution, there is already a function called bqSQL() to escape backticks before call pSQL() but how can we choose which characters to let use?

**Comment by PrestaEdit** [comment]
Hi all.

I can confirm this is still here and true on PS8 (develop branch) at this day.

**Comment by marsaldev** [comment]
@PrestaShop/prestashop-maintainers Can I work on it?

**Comment by laurentrousseau918** [comment]
+1

**Comment by Progi1984** [comment]
@marsaldev With please. Let's go :)
