### ISSUE TITLE
Module statsbestproduct total sales is bad

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22574]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Make on order with a discounted product 
2. Check the total on a best product sales

**Screenshots**

![Capture d’écran de 2020-12-24 07-01-35](https://user-images.githubusercontent.com/5064590/103065091-ff53a100-45b5-11eb-96bc-a92cf8279955.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR. I managed to reproduce the issue with PS1.7.6.9 and PS1.7.7.0.
I’ll add this to the debug backlog :wink: 

Thanks!
