### ISSUE TITLE
Module statssales turnover must be without tax

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22577]
#### Describe the bug

Turnover must be without taxe

#### Steps to Reproduce

1. Check the total on statssales 

**Screenshots**

![Capture d’écran de 2020-12-24 07-57-58](https://user-images.githubusercontent.com/5064590/103068644-da632c00-45bd-11eb-9140-c65449ef55a6.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR, I manage to reproduce your issue with PS1.7.7.0.
I’ll add this to the debug backlog :slightly_smiling_face: 

Thanks!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/statssales#17
