### ISSUE TITLE
Module statsbestmanufacturer total sales is bad

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22576]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Install the module because is not present
1. Make on order with a discounted product 
2. Check the total on a best manufacturer

**Screenshots**

![Capture d’écran de 2020-12-24 07-38-04](https://user-images.githubusercontent.com/5064590/103067393-15b02b80-45bb-11eb-89d0-b64202582eaa.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR, I manage to reproduce your issue with PS1.7.7.0.
I’ll add this to the debug backlog :slightly_smiling_face: 

Thanks!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/statsbestmanufacturers#10
