### ISSUE TITLE
Module statsbestsupplier total sales is bad

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22575]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Make on order with a discounted product 
2. Check the total on a best supplier

**Screenshots**

![Capture d’écran de 2020-12-24 07-15-43](https://user-images.githubusercontent.com/5064590/103065868-eea42a80-45b7-11eb-94c7-930f51a68974.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR, I manage to reproduce your issue with PS1.7.7.0.
I’ll add this to the debug backlog :slightly_smiling_face: 

Thanks!

**Comment by Progi1984** [comment]
Fixed by https://github.com/PrestaShop/statsbestsuppliers/pull/10
