### ISSUE TITLE
Module statsforecast total sales by category is wrong: should use unit_price_tax_excl instead of product_price

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22582]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Make on order with a discounted product 
2. Click on stats
3. Check the stats

**Screenshots**

![Capture d’écran de 2020-12-24 11-55-49](https://user-images.githubusercontent.com/5064590/103084361-178be600-45df-11eb-8443-90a652da40bf.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your issue and your PR. I managed to reproduce the issue with PS1.7.6.9 and PS1.7.7.0.
I’ll add this to the debug backlog :wink: 

Thanks!

**Comment by ghost** [comment]
@hibatallahAouadni 

It's the last ! Thank you and Merry Christmas

**Comment by matks** [comment]
https://github.com/PrestaShop/statsforecast/pull/19 has been merged. The fix will be released with module statsforecast v2.0.2
