### ISSUE TITLE
BO - Order page - Unclear alert when adding a payment with invalid payment method 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22587]
#### Describe the bug

In the BO > Orders > Order view page > when we add a payment with invalid payment => an Unclear error is displayed 

#### Steps to Reproduce

1. Go to BO > Orders > Old order page
2. Add payment with "Payment method" `Paym>>ents by check`
3. Add
4. See an error

![image](https://user-images.githubusercontent.com/16067358/103093496-c0940a00-45fa-11eb-8e93-a752a8f89e3b.png)

PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/103093514-d275ad00-45fa-11eb-8bd5-e5a23427a101.png)

#### Additional information

* PrestaShop version: 1770, 1771build1
* PHP version: 7.0

**Comment by Progi1984** [comment]
Fixed by #22791
