### ISSUE TITLE
After 1.7.7.0 upgrade

### ISSUE THREAD

**Issue by xkadirx39** [PrestaShop/PrestaShop#22597]
Prestashop gives this error after updating to the latest version

**Screenshots**

![esa](https://user-images.githubusercontent.com/49781434/103153859-cc233480-47a4-11eb-8194-527ba6285dc4.PNG)

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
