### ISSUE TITLE
CSS is not rendering

### ISSUE THREAD

**Issue by jrckmcsb** [PrestaShop/PrestaShop#22593]
#### Describe the bug

I try to install the latest version and according to my installer I used the ``1.7.8.0`` 

After installing I encounter the same [issue](https://github.com/PrestaShop/PrestaShop/issues/17539) but I solved it base on the comments. However after installation the site doesn't rendered the CSS properly but visiting the source code of CSS file, the CSS file is already included but it doesn't render on the site

![image](https://user-images.githubusercontent.com/62977259/103137996-ea3b5700-4708-11eb-897e-4138c67bbb10.png)

#### Expected behavior

The CSS apply properly

1. Install the latest version
2. You will probably get an error like on [this](https://github.com/PrestaShop/PrestaShop/issues/17539) issue
3. Solved it via running the SQL query included on the comment section
4. Go to site and you can see the site but the CSS is not rendering properly

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/62977259/103137998-f3c4bf00-4708-11eb-854c-eb653a5a86f5.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version:  7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @jrckmcsb 

Thanks for your first issue :tada: 
Well, on the develop branch you need to install the assets by executing this line on console:

`make install`

Please check and feedback.
Thanks!

**Comment by jrckmcsb** [comment]
![image](https://user-images.githubusercontent.com/62977259/103144318-6ca43500-4762-11eb-8336-34004ef092ad.png)

Now it returns a new error

**Comment by jrckmcsb** [comment]
I was able to run the ``make install`` however the result is still the same.

**Comment by hibatallahAouadni** [comment]
Hello @jrckmcsb 

> Install the latest version

Do you mean install a stable version from [PrestaShop site](https://www.prestashop.com/fr/versions-precedentes) or clone PrestaShop from Github?

Thanks!

**Comment by jrckmcsb** [comment]
Apologize, I just clone it from Github, I solved this issue by running it on VM

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: 
So, I close this issue :wink:
