### ISSUE TITLE
Address Format not found in tools

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#22596]
Hello

we are facing this issue 
`Fatal error: Uncaught Error: Class 'AddressFormat' not found in /var/www/vhosts/playstore.ma/httpdocs/classes/Tools.php:3376 Stack trace: #0 /var/www/vhosts/playstore.ma/httpdocs/classes/db/Db.php(794): ToolsCore::nl2br('configuration') #1 /var/www/vhosts/playstore.ma/httpdocs/config/alias.php(47): DbCore->escape('configuration', false) #2 /var/www/vhosts/playstore.ma/httpdocs/config/alias.php(52): pSQL('configuration') #3 /var/www/vhosts/playstore.ma/httpdocs/classes/Configuration.php(155): bqSQL('configuration') #4 /var/www/vhosts/playstore.ma/httpdocs/classes/Configuration.php(209): ConfigurationCore::loadConfiguration() #5 /var/www/vhosts/playstore.ma/httpdocs/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...') #6 /var/www/vhosts/playstore.ma/httpdocs/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex() #7 [internal function]: PrestaShopAutoload->load('AddressFormat') #8 /var/www/vhosts/playstore.ma/httpdocs/classes/Tools.php(3376): spl_autoload_call('AddressFormat') # in /var/www/vhosts/playstore.ma/httpdocs/classes/Tools.php on line 3376`

Version de PrestaShop : 1.7.6.9
Version du logiciel serveur : Apache
Version de PHP : 7.2.34
Limite de mémoire : 100128M
Temps maximal d'exécution : 9000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by paulius-bulotas** [comment]
Hi, does anyone know how to solve same issue with prestashop 1.7.6.5?

**Comment by ComonSoft** [comment]
Hi, same issue on PS 1.7.6.4 PHP 7.2
How to reproduce the bug
1/ goto back office orders
2/ select one order in pending status (wire, check...)
3/ Click button "Add new discount"
4/ select 'Amount"
4/ Enter a title and a value and click "Add button"
5/ Error occurred

Nb: the voucher is created, you can see it if you go back to the order detail
Same error occurred if you try to delete the voucher.
