### ISSUE TITLE
An error is displayed in the console when adding a voucher on the order page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22590]
#### Describe the bug

In the BO > Orders > Add new Order page > an error is displayed in the console when we try to add a voucher
![image](https://user-images.githubusercontent.com/16067358/103131234-3a320380-46a0-11eb-9175-63d46241d0e2.png)

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page
2. Choose a customer
3. Add some products
4. Click on add a voucher
![image](https://user-images.githubusercontent.com/16067358/103131283-6ea5bf80-46a0-11eb-963c-8e3bdaedc8cc.png)
5. see error in the console
![image](https://user-images.githubusercontent.com/16067358/103131234-3a320380-46a0-11eb-9175-63d46241d0e2.png)

PS: 1769 => ok
https://drive.google.com/file/d/1LSpSfMbJrY9ZxXQQ1YasvCky_Q1tnvpD/view?usp=sharing
#### Additional information

* PrestaShop version: 1770, 1771build1
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #22673
