### ISSUE TITLE
Installazione Aggiornamento PrestaShop 1.7.7.0

### ISSUE THREAD

**Issue by Lui72** [PrestaShop/PrestaShop#22599]
#### Describe the bug  Dopo l'aggiornamento non vedo il menù sulla Sinistra

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A 1.7.7.0
* PHP version: N/A  PHP 7.0

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Lui72** [comment]
Buongiorno Gent.mo Sig. Simon,

Grazie per la preziosa e gentile risposta, provvederò subito a riformulare un nuovo problema completo in ogni sua parte.
Grazie e Buon Santo Natale
Luigi

**Comment by hibatallahAouadni** [comment]
Hello @Lui72 ,

Please write in english. English is the norm on Github.
As @SimonGrn mentionned above you need to create a new issue **following the template to submit a complete bug report** and write it in **English** :wink: 

Thanks!
