### ISSUE TITLE
Fwd: Customer message - the thread link is incorrect

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22592]
#### Describe the bug

In the Email Fwd: Customer message, when we click on this link: `View this thread`, we are redirected to an incorrect URL.

#### Steps to Reproduce

1. You must send a message to customer service from FO using the order.
2. Go to BO > Customer Service Page > Open the message
3. forward this discussion to another address email/employee
4.Check the email
5. Click on "View this thread"
6. See error: redirection to this link `http://presta/1771build1/admin-dev/http://presta/1771build1/admin-dev/index.php?controller=AdminCustomerThreads&token=b5d9b8f5810a04e1ab1bbbdc404a611b&id_customer_thread=3&viewcustomer_thread=1`

#### Additional information

* PrestaShop version: 1769/1770/1771build1
* PHP version: 7.1

**Comment by dborovsky** [comment]
Hi Guys. I am php/c# developer. have experience with symfony too. I would like to contribute(help) with Prestashop. Which tasks are more priority now and I can start to help? Thanks.

**Comment by matks** [comment]
Hi @dborovsky I think a good starting point would be the `major` bugs known and not yet fixed. You can find them using github filters https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3AMajor

Just be sure not to pick an issue which is already assigned to someone 😉  if it is already assigned, it means someone is working on it already

**Comment by matks** [comment]
You also have https://build.prestashop.com/news/a-definition-of-the-good-first-issue-label/ which are good first topics to dive into PrestaShop codebase

**Comment by dborovsky** [comment]
Ok, all clear. Should I inform you before which task I would like to assign?

**Comment by matks** [comment]
It's best indeed 😄  because we cannot assign people that are not a PrestaShop member (it's a limitation from github). You just write a comment on the related issue.

Also if you'd like to discuss with us about the process, the issues, the topics you can join our Slack channel https://github.com/PrestaShop/open-source/blob/master/slack/readme.md
