### ISSUE TITLE
Exception thrown when creating order programmatically: Shop context types other than "single shop" are not supported

### ISSUE THREAD

**Issue by carlosul** [PrestaShop/PrestaShop#22601]
#### The bug

I was able to create orders programmatically on a custom module until 1.7.7.0 update. Now this exception is thrown:
Shop context types other than "single shop" are not supported

I tried adding this code lines without success

```
$shop = new Shop(1);
$employee = new Employee(1); 
$this->context->employee = $employee;
$this->context->shop = $shop;
Shop::setContext(Shop::CONTEXT_SHOP, $shop->id);
```

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.25

Thx for any help given!

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
