### ISSUE TITLE
Scomparsa Menù Laterale di PrestaShop

### ISSUE THREAD

**Issue by Lui72** [PrestaShop/PrestaShop#22600]
#### Describe the bug Dopo aver eseguito il nuovo aggiornamento PrestaShop 1.7.7.0 è scomparsa la barra laterale del mesù di sinistra

A clear and concise description of what went wrong.

#### Expected behavior

Ho eseguito il comando di aggiornamento della nuova versione di PrestaShop da V.1.6.9 a versione V.1.7.7.0 

Explain what you expected to happen instead. Speravo che tutto funzionasse secondo ogni nuovo aggiornamento

#### Steps to Reproduce
Ho visto la possibilità di una nuova versione

1. Go to '...'  PRESTASHOP UPDATES
2. Click on '....' Modulo 1-Click Upgrade

**Screenshots** 
https://microscopilubi.it/admin123/index.php?controller=AdminDashboard&token=d535b97a70cb6008c6030624a85ea872

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A 1.7.7.0
* PHP version: N/A 7.0
[27122020 1435 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5744599/27122020.1435.-.Ritaglio.di.schermata.pdf)

**Comment by SimonGrn** [comment]
Hello,

please write your issue in english. English is the norm on Github.

Thank you.
