### ISSUE TITLE
cannot access to BO

### ISSUE THREAD

**Issue by spodra** [PrestaShop/PrestaShop#22609]
Can you help me with admin login problems? login and then log out on next step. Frequent problem as I see.

**Comment by Prestaworks** [comment]
I think you have a browser cache issue, the browser has cached the redirect so you just get a redirect instead of the page load.

Try to add this to the htaccess file in your **admin** folder and clear all browser cache. Then try again.

```# DISABLE CACHING
<IfModule mod_headers.c>
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Pragma "no-cache"
    Header set Expires 0
</IfModule>

<FilesMatch "\.(css|flv|gif|htm|html|ico|jpe|jpeg|jpg|js|mp3|mp4|png|pdf|swf|txt)$">
    <IfModule mod_expires.c>
        ExpiresActive Off
    </IfModule>
    <IfModule mod_headers.c>
        FileETag None
        Header unset ETag
        Header unset Pragma
        Header unset Cache-Control
        Header unset Last-Modified
        Header set Pragma "no-cache"
        Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
        Header set Expires "Thu, 1 Jan 1970 00:00:00 GMT"
    </IfModule>
</FilesMatch>
```

**Comment by spodra** [comment]
I tried 3 browsers. The same hapens on all browsers.  Sorry, I am not programmer and cannot do ant changes.

**Comment by PululuK** [comment]
Hi @spodra 
If you have access to your phpmyadmin (or another tool), in `ps_configuration` table update `PS_COOKIE_CHECKIP` **1** to **0**.

![image](https://user-images.githubusercontent.com/16455155/103227383-898d6380-492e-11eb-83c3-96ff14cf8d81.png)

**Comment by hibatallahAouadni** [comment]
Hello @spodra 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report.**

Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
