### ISSUE TITLE
[Multi Store] Not all categories are showing in the category tree on BO product page for  "All Shops" 

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#22610]
#### Describe the bug

In the BO on the product page, a lot of the categories are listed in the category tree 
They all have only visibility in shop 2  

#### Expected behavior

All categories should be visible

#### Steps to Reproduce

Create 4 categories, 
All only visible in id_shop = 2
2 have id_shop_default = 1 (probably make the category for all shops and then change it to only 2 )
and 2 have id_shop_default = 2

Only categories with both id_shop =2 and id_shop_default = 2 are showing in all shops

What is the use of id_shop_default?
Where can you change it for a category?

This will probably also cause it to loose the default category for shop 2 if the product is saved in all shops.

**Screenshots**

PS: to reproduce the issue follow the steps in the screen record below:
https://drive.google.com/file/d/1bNrlnfaDVOKoJMzaLF7sBR-acSOpZ0u_/view
The results:

![image](https://user-images.githubusercontent.com/23308427/103441027-3b88a080-4c4b-11eb-96d1-a4cc480284d0.png)

#### Additional information

* PrestaShop version: 1.7.5.2

**Comment by hibatallahAouadni** [comment]
Hello @sickboards 

Your issue seems similar to this one #13468
Could you please check and feedback.

Thanks!

**Comment by sickboards** [comment]
@hibatallahAouadni 
It looks a bit similar but I don't think it is the same, related at best.
My issue is for all shops in the back office, while that issue is for a specific shop in the front office.

**Comment by hibatallahAouadni** [comment]
Hello @sickboards 

All right I got your point but could you please tell me where's the bug :confused: 
Cause it seems that there's no error launched cause of this.
IMHO, I think that id_shop_default it's the shop id where the category was created.
I will ping the Developers to answer your questions :wink: 

> What is the use of id_shop_default?
Where can you change it for a category?

Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could anyone please asnswer @sickboards questions mentionned above, thanks in advance :slightly_smiling_face: 

---
PS: to reproduce the issue follow the steps in the screen record below:
https://drive.google.com/file/d/1bNrlnfaDVOKoJMzaLF7sBR-acSOpZ0u_/view
The results:

![image](https://user-images.githubusercontent.com/23308427/103441027-3b88a080-4c4b-11eb-96d1-a4cc480284d0.png)

**Comment by sickboards** [comment]
The bug is manifesting itself in the BO on the product edit page
[image: image.png]
Not all categories are showing here, if you are in all shops.
causing the default category to be lost for shop 2 if you save in all shops.
It might be that in the code there is something that it still has an
id_shop_default = 1 in the SQL when it is in 'all shops'

**Comment by thomaskramer76** [comment]
Did you find the solution for this? I have the excact same problem, and it is driving me crazy

**Comment by kpodemski** [comment]
@MatShir 

Since there's no "All shops" on the new product page, I think we can close this issue.

**Comment by MatShir** [comment]
Seems to be fixed on the new product page (PS 8.1) !
From the product page on a shop view, I can see only categories associated to the shop or the group shop associated to the shop. "All view" for category doesn't exist anymore for data consistencies, since tree can be different by shop.
