### ISSUE TITLE
Translation into different languages customization of product fields

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#22613]
#### Describe the bug

If the store has different translation languages, then in the product settings customization field can not be translated into all languages, translation is possible only from the language of the installed administrator.

#### Expected behavior

Select language and add translation

#### Steps to Reproduce

1. The store must have more than one language
2. Editing the product
3. Settings tab
4. Customization

**Comment by hibatallahAouadni** [comment]
Hello @dmitrij1988 

Could you please provide your PrestaShop version and your PHP version.

Thanks!

**Comment by ewonta** [comment]
Version PrestaShop - 1.7.7.0
Version php - 7.2.33

It doesn't depend on the version

**Comment by hibatallahAouadni** [comment]
Hello @dmitrij1988 

> the product settings customization field can not be translated into all languages

Well that's not true! Of course, we can :wink: you just need to switch the language on the select besides the product title input and submit the customization's translation. See the attached screen record below:

https://drive.google.com/file/d/1OV4ROhPH8wXqD1stV6KXffCN5zelBKlm/view

Please check and feedback.
Thanks!
