### ISSUE TITLE
Discount - Incorrect display on FO with free gift + percentage cart rule

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22615]
#### Describe the bug

On FO, when a cart rule with a free gift + percentage discount is added to the cart, the discount displayed on the line of this cart rule is incorrect, because the percentage discount is calculated also on gifted product price.
The Total discount is OK, and on BO all is OK too.

Might be related to #20690 and to #16673.

It was OK in 1.7.6.9.

#### Expected behavior

See step 5.

#### Steps to Reproduce

1. In BO > Catalog > Discounts, add a new cart rule
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included). Save the cart rule.
3. Go to FO, add to the cart another product (at 100€ tax included too in my case)
4. In the cart, add the discount
5. Check the discount line : Discount is wrong (130€ instead of 115€), the percentage part of the discount is calculated on both paid AND gifted product (2x15€). It should be calculated only on the paid product (1x15€).
Note that the total discount is OK, so the total tax included of the order is also OK.

**Screenshots**

Cart rules Actions: 
![bug discount percentage and gift cart rule](https://user-images.githubusercontent.com/55688534/103278402-b3e12e80-49cb-11eb-9469-1725f53cfb97.png)

Display KO in FO: 130€ instead of 115€.
![bug discount percentage and gift FO](https://user-images.githubusercontent.com/55688534/103277977-9eb7d000-49ca-11eb-92b2-2f3640154c4a.png)

OK in BO, on order and in invoice:
![bug discount percentage and gift invoice](https://user-images.githubusercontent.com/55688534/103277994-aaa39200-49ca-11eb-9121-73f7ad29038f.png)
![bug discount percentage and gift BO order](https://user-images.githubusercontent.com/55688534/103277997-aaa39200-49ca-11eb-8839-22d304a97762.png)

#### Additional information

* PrestaShop version: 1.7.7.0, 1.7.7.1 build 1
* PHP version: 7.2

**Comment by PierreRambaud** [comment]
It also occurs in the Shopping Cart admin page: 
![image](https://user-images.githubusercontent.com/1462701/103760750-dac7e200-5015-11eb-858c-2c635acafd2b.png)

**Comment by PierreRambaud** [comment]
> It also occurs in the Shopping Cart admin page:
> ![image](https://user-images.githubusercontent.com/1462701/103760750-dac7e200-5015-11eb-858c-2c635acafd2b.png)

I also see the Total cost of products is not the good one :sweat_smile: Or if it's ok here, I've got a fix for the rest =)

**Comment by Progi1984** [comment]
@PierreRambaud This PR #22768 fixes this issue ?

**Comment by PierreRambaud** [comment]
I think yes ^^

**Comment by Progi1984** [comment]
@khouloudbelguith Is it ok for you (I see you adding and removing the "Fixed" label) ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Yes! https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-765317554
As discussed with @PierreRambaud.
I created some issues related to this ticket:
#22946
#22948 reported here: https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-759388271
#22951 reported here: https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-765324937

Thank you!
