### ISSUE TITLE
Contact form inactive with Privacy checkbox present

### ISSUE THREAD

**Issue by CJH297** [PrestaShop/PrestaShop#22616]
Prestashop contact form inactive (send button does not work) if consent checkbox is active

#### Expected behavior

Turn on Consent checkbox in GDPR module and this should appear on the Contact form, only allowing message to be sent if checked by the customer to accept policy

#### Steps to Reproduce

1. Turn on Contact Form in GDPR module
2. No checkbox is observed on Contact Form
3. But Send button is never active and no message can be sent (presumed because checkbox is not visible and cannot be checked)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0 (clean install)
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @CJH297 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1pIRu3J4tKOPisSmyj3pdHyOVu47dPJzd/view

Please check and feedback.
Thanks!

**Comment by CJH297** [comment]
I just tried it again. Turned on the checkbox, no checkbox appears on the contact form, but it is evidently actively working because the send button remains inactive. But there is an oddity here. Because you confirmed your system works, I checked on a different computer as well, and there the checkbox appears and works correctly. 

I will try to investigate further, though time is limited. Evidently, something is interfering on one of my computers and the checkbox never appears (cache, /var, browser cache all cleared). On both, this is Firefox latest build, so it isn't the browser itself.

I think you have to consider this an oddity on my system, unless someone else reports something similar. Apologies for using your time.

**Comment by hibatallahAouadni** [comment]
Hello @CJH297 

Thanks for your feedback!
Well then, I close this issue cause it seems that's a problem from your system like you said.
Please note that you can always create a new issue if further information pops up.

Thanks!
