### ISSUE TITLE
Fehler Prestashop 1.7.7.0 und DHL-Modul v1.02

### ISSUE THREAD

**Issue by JoergDrees** [PrestaShop/PrestaShop#22612]
Hallo zusammen

Ich habe die Prestashop V1.7.7.0 installiert.
Dazu das DHL - Modul v1.02 von Silbersaiten

Auf den neuen konfigurierten Bestellseiten der Prestashop V1.7.7.0 sind die DHL-Button "Zusätzliche Leistungen", "Lieferadresse aktualisieren" und "Dokumente exportieren" außer Betrieb
[Fehler Prestashop 1.7.7.0 - DHL GK-Modul 1.02.docx](https://github.com/PrestaShop/PrestaShop/files/5748978/Fehler.Prestashop.1.7.7.0.-.DHL.GK-Modul.1.02.docx)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. Your report **MUST** be in English.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
