### ISSUE TITLE
Breadcrumbs : Either "name" or "item.name" should be specified

### ISSUE THREAD

**Issue by MisterDuval** [PrestaShop/PrestaShop#22626]
#### Describe the bug

Google search console error: Breadcrumbs : Either "name" or "item.name" should be specified.
This error occurs on single item page (like homepage)

#### Expected behavior

No error

#### Steps to Reproduce

Have a look at you Google search console

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A
* More info at: https://www.prestashop.com/forums/topic/1002989-breadcrumbs-either-name-or-itemname-should-be-specified/

**Comment by hibatallahAouadni** [comment]
Hello @MisterDuval 

Thanks for your issue and your PR :slightly_smiling_face: 
Could you please check if your issue is a duplicate to #22416

Thanks!

**Comment by MisterDuval** [comment]
yep, that's a duplicate :-)

**Comment by hibatallahAouadni** [comment]
Hello @MisterDuval 

Well then, it is already in our debug backlog.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22416

**Comment by Prime110** [comment]
EDITED by @matks SPAM
