### ISSUE TITLE
BO - Orders page - Cannot delete a product when debug mode is enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22625]
#### Describe the bug

In the BO > Orders > Order view page > we cannot delete a product when debug mode is enabled after removing some discounts

#### Steps to Reproduce

1. Enable debug mode
2. Create a cart rule: 
2.1 No code
2.2 **conditions**:  [Product selection + Number of products required in the cart to enjoy the discount =2 + Product selection = demo_6] 
![image](https://user-images.githubusercontent.com/16067358/103359327-ff710680-4ab7-11eb-925a-3209a2ba7230.png)
2.3 discounts = 50%
3. Create a cart rule : No cade + no conditions + free gift = demo_6
4. Go to FO => add demo_6 to the cart => all cart rules are applied => continue checkout
5. In the BO > Orders > last order created > delete the first cart rule (50%)
6. Delete the second cart rule (gift)
7. Delete the product => see the error (the product cannot be deleted)
![image](https://user-images.githubusercontent.com/16067358/103359382-1ca5d500-4ab8-11eb-8ae6-9e1530ee12f4.png)

**Screenshots**

PS1770 => NOK
PS1771 => NOK: https://drive.google.com/file/d/1YIByHLmcKyapRyjSORWLS7ADryKHrsu_/view?usp=sharing
PS1769 => ok: https://drive.google.com/file/d/13pC-3lVUz56Jl7QXVCz3HheOIN54RBIJ/view?usp=sharing

#### Additional information

* PrestaShop version: 1771build1, 1770
* PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/22805
