### ISSUE TITLE
Faceted search Module - Future filter multiplied for number of items

### ISSUE THREAD

**Issue by Sg-nipe** [PrestaShop/PrestaShop#22620]
Prestashop 1.7.6.9 with Faceted search Module v3.7.0 
(all requested from https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ it's ok)

We have 2 feature's filter actavated, the first it's ok and report all related products if we apply filters... for second (composition of item) the module return any values of feature for multiplied for any article presents in result (if we have 4 items correspondig to search filter, we have 4 time's the same composition checkbox displayed in module).
![2020-12-29 16_09_29-Window](https://user-images.githubusercontent.com/57758981/103293535-632ffc80-49f0-11eb-8447-bb72284317e2.png)

In backend module configuration, on template, we see the correct number of future's values (title of filter switch).
![2020-12-29 15_57_46-Window](https://user-images.githubusercontent.com/57758981/103293375-164c2600-49f0-11eb-88e4-e1d00e49a3f2.png)

We try to disabled cache (module and site, and flush cache), nothing change...

**Comment by Demacri** [comment]
It happens when you write custom value for feature/attribute instead of choosing them from dropdown menu in product page. Try to create "viscosa","cotone" etc. as predefined value for your "Composizione" feature and then in your product page select those values from dropdown menu.

Hope I helped you.

Ciao!

**Comment by Sg-nipe** [comment]
Thanks, you fix my problem.
May be nice if inserting custom value, when description inserted combine with a pre-defined value description, auto select a predefined value (sometimes users write because it's more easy than search in a combo box).

**Comment by hibatallahAouadni** [comment]
Thanks @Demacri for your quick reply and fix :rocket: 
@Sg-nipe glad to hear that your problem is fixed :tada:
