### ISSUE TITLE
Error when change order status

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#22623]
My version 1.7.7.0
Call to a member function getMessage() on null

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

**Comment by hibatallahAouadni** [comment]
Hello @centoasa 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by centoasa** [comment]
(1/1) ContextErrorExceptionWarning: putenv() has been disabled for security reasons
--
in Kernel.php line 122
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request), 1, false)in index.php line 82
