### ISSUE TITLE
Category search doesn't work for me

### ISSUE THREAD

**Issue by raulstrappa** [PrestaShop/PrestaShop#22633]
I am testing my prestashop and the search by facets works well for me, except for the category section, I am attaching a video.
Thank you very much for the help

https://user-images.githubusercontent.com/66635575/103414585-58df4100-4b5d-11eb-9bec-17bfe81482a7.mp4

**Comment by hibatallahAouadni** [comment]
Hello @raulstrappa 

Could you please provide your PrestaShop version, PHP version and FacetedSearch version.
And please **follow the provided template to submit a complete bug report**.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @raulstrappa ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
