### ISSUE TITLE
After click many time on continue, it creates multiple addresses

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#22635]
Hi on PS 1.7.7.0 on checkout process if you click many time on continue btn when your are creating a new address, it creates multiple addresses on DB for the client.

**Comment by hibatallahAouadni** [comment]
Hello @msaustral 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

_PS: even thought there's not enough infos, I tried it but I didn't reproduce your issue: [see screen record](https://drive.google.com/file/d/1Mos2aWm8zJ1PmuWw-tSrm9zyrCvKNcGM/view)_ 

Thanks!
