### ISSUE TITLE
BO ORDER CREATE - Display customer's company, if B2B enabled

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22643]
#### Is your feature request related to a problem?

When you create an order in BO and searching for a customer, there is no other info than his name and email.

#### Describe the solution you'd like

It would be good to display customer's company, if B2B mode is enabled. (In addition to user group - https://github.com/PrestaShop/PrestaShop/issues/15954)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think about adding the Customer company (and type:Guest/Customer like mentionned in #15954) ?

PS: @Hlavtox Great job :clap: You have tested the **BO>Order** page (every inch of it :sweat_smile: ) Thanks :relaxed:

**Comment by Hlavtox** [comment]
@hibatallahAouadni 🤣🤣

**Comment by LouiseBonnard** [comment]
Hi there! I think it could be a great idea, thanks!

When the B2B mode is enabled in the BO, it adds several fields to the customer profile in the BO and FO, among which the 'Company' field. So it makes sense to have it displayed in the customer card when creating a BO order. I'll add it to the specifications: https://github.com/PrestaShop/prestashop-specs/pull/186/commits/bdff00500307b048ddf19c93fbf3085d0047a9cd.
