### ISSUE TITLE
Module name length over 50 chars

### ISSUE THREAD

**Issue by linuxatico** [PrestaShop/PrestaShop#22640]
#### Describe the bug
A module with name length > 50 characters can be installed but not associated to a Webservice API key permission.

#### Expected behavior

One of the following:
1. An error in installing the module explaining that the module name is too long.
2. An usable webservice API for the module with name length > 50

#### Steps to Reproduce

1. Install a module with name length > 50 characters (develop a basic one if none available)
2. Go to "Advanced Parameters" -> "Webservice" and try to assign it a webservice api key permission
3. Re open for editing the newly created webservice key
4. Notice that the permissions are not checked
5. Look into table ps_webservice_permission and notice the truncated module name in ps_webservice_permission.resource.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @linuxatico 

> A module with name length > 50 characters can be installed

How it can be installed, cause I couldn't :confused: 
I create a dummy module with a long name and I get an error: 

![image](https://user-images.githubusercontent.com/23308427/103545179-80a61000-4ea1-11eb-9b0c-30d04ac209f6.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @linuxatico ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
