### ISSUE TITLE
Add ability to create and edit guest accounts in back office

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22645]
#### Is your feature request related to a problem?
When you are making a BO order, most of the times, you don't need to register a customer, you just want to help him with the order. Now, you must register him, add a password, set proper groups etc. No possibility to create a guest.

#### Solution
We need to be able to properly create and edit guests.

#### How guests differ from customers
**Guest**
- is_guest = 1
- default customer group = 2
- assigned groups = 2
- has no or automatically generated nonsense password, does not need one
- can have the same email as any customer or guest

**Customer**
- is_guest = 0
- default customer group = 3
- assigned groups = 3
- needs to have a proper password
- only one customer with the same email can exist

#### Specifications - form
- On the top of the customer form, a toggle "Registered as a Guest" is displayed. Default value is **NO**. Field name is (is_guest).

**If is_guest is 1**
- The password input is disabled and not required.
- The "Guest" in the Group access is checked and can't be unchecked. The field will be disabled.
- The default group is set at Guest and can't be editable. The field will disabled.

**Default**
![default](https://user-images.githubusercontent.com/6097524/126978702-a5816f4d-e23b-4ed9-b848-a24941084939.JPG)

**Guest checked**
![enabled](https://user-images.githubusercontent.com/6097524/126978724-6a0525b0-4600-441d-af54-a5f0003e3fc1.JPG)

#### Submitting the form
- Password won't be required and set to automatically generated one, the same in FO.
- is_guest = 1 must be saved to database for this customer.
- Email won't be checked against existence, there can be thousands of guests with the same email.
- Groups submit will be ignored and customer will only belong to PS_GUEST_GROUP from PS configuration.
- Default group submit will be ignored and customer's default group will be PS_GUEST_GROUP from PS configuration.

#### Technical details
- Provide the form with data - isGuest will be available after this is merged https://github.com/PrestaShop/PrestaShop/pull/25686
- We add a new form input is_guest to the form.
- We will make some visual changes to the form so they don't have to fill the info that is fixed and not required.
- After submitting, do we make two commands - AddCustomerCommand and AddGuestCommand or we just alter the current command with a few conditions? ping @jolelievre

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , when you try creating a guest account from BO, it's totally impossible cause the password input is required, I think it's a bug more than improvement, wdyt?

**Comment by MatShir** [comment]
Indeed, the Guest group is a special group that should not be at the same table as the other customer group. The guest group is more like a state. The Guest becomes a Customer when they create an account with a password.

One solution will be a toggle to create the customer as a guest customer that will hide the Customer group in the customer group association. 

Could you share us a case where you want only to create a guest customer and not a customer?

**Comment by Hlavtox** [comment]
@MatShir Hi Mateus! We would do it in almost every order we make from the BO.

In B2C enviroment, you use backoffice to create customers and orders:
- When you have the customer on the phone - an old lady calls “Please young man, would you create order for me?” So the employee goes through the order process with the customer. These are 90% one time orders, when the user does not need and does not want a registration.
- When the customer physically comes to our store. You show him your products, he chooses and decides to buy immediately. So you go to your PC or a public terminal we have on a desk and you make the order with them. And again, no way to make a customer  as a guest.

__________
I think a good solution would be a new switch un the customer creation form, called “Customer type”, with values “Registered customer”/“Guest customer”. When you click guest customer, it hides the password and customer groups fields. Wdyt?

**Comment by hibatallahAouadni** [comment]
@MatShir so this issue still needs specs? otherwise we have to remove the **`TBS`** label and add the **`To Do`** label :wink:

**Comment by kpodemski** [comment]
Good idea 👍

**Comment by MatShir** [comment]
Sounds good!

**Specs:**
Bellow the enable field on the customer form, a toggle "Registered as a Guest" is displayed.
- if Yes, the password input is replaced with an information text. (to be defined)
The "Guest" in the Group access is checked and can't be unchecked if the toggle is set to Yes. 
The default group is set at Guest. And The default group can't be editable if the toggle is set to Yes. 

- If No, the form remains the same.

I suggest the default value to be to No. 
I still wondering if a Guest customer can still be part of another group customer. For ex: at an exhibition/Show, differents buyers could part of different groups. Wdyt ?
_The wording we will be review by our Product Content_

**Comment by Hlavtox** [comment]
@MatShir His default group must be 2, thats for sure.

He must allowed be in a group 2, to simulate front-office behaviour. Technically, he can have an access to other groups, but I am worried if it would not confuse some modules, that expect the guests to “come in some way”, so to say. 🤣

I think a way that would introduce no BC breaks is to hide customer group inputs (along with the pass), to completely simulate the behavior in front office, so there are no differences. (and no employee could screw it up😁😁)

**Comment by MatShir** [comment]
I see what you mean, It could be confusing. Maybe there is some more we could do on the design to avoid this confusion.
I did a small update on the specs. Tell me WDYT ?

**Comment by Hlavtox** [comment]
@MatShir I think it's absolutely fine! ;)
