### ISSUE TITLE
Watermark module by Prestashop error 500 in FO

### ISSUE THREAD

**Issue by mklimkiew** [PrestaShop/PrestaShop#22649]
After (just) installing Watermark module by Prestashop FO becomes unavailable - ERROR 500. 
BO is still OK. But after generating new pictures BO has also error 500. 
Setting to Debugging mode show noting - just error 500.

* PrestaShop version: 1.7.7.0
* PHP version: 7.3
* Installed on Plesk

**Comment by hibatallahAouadni** [comment]
Hello @mklimkiew 

It seems that your issue is not a PrestaShop core bug.
If your module is Watermark Official, please contact support team on [Addons](https://addons.prestashop.com/fr/).

We will close this issue.

Thanks!
