### ISSUE TITLE
[RESPONSIVE - BO] Order page buttons are taking too much height on mobile

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22660]
#### Describe the bug

Order page buttons are taking too much height on mobile

#### Expected behavior

![image](https://user-images.githubusercontent.com/14963751/103549947-74718100-4ea8-11eb-8959-3dd8c59dc151.png)

#### Steps to Reproduce

1. Go to Order page

**Screenshots**

![image](https://user-images.githubusercontent.com/14963751/103550021-923ee600-4ea8-11eb-85ab-1addc0d3e299.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

I managed to reproduce your issue with PS1.7.7.0 and PS1.7.7.1, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103551995-7e48b380-4eab-11eb-8a50-584b3a27ee2a.png)

As you can see there's another issue (pointed by the red arrow), the payment select is a little bit hidden by the header toolbar.

Thanks!

**Comment by NeOMakinG** [comment]
I can't manage to reproduce the other issue, but let's wait for the PR to see if it's fixed on not

**Comment by hibatallahAouadni** [comment]
I reproduced the second issue only with PS1.7.7.1_build1 :wink:

**Comment by Hlavtox** [comment]
@NeOMakinG @hibatallahAouadni Hi everyone, what if you put just "Update" to the button label on mobile? Longer status names would fit to the dropdown ;-)

**Comment by NeOMakinG** [comment]
> @NeOMakinG @hibatallahAouadni Hi everyone, what if you put just "Update" to the button label on mobile? Longer status names would fit to the dropdown ;-)

I don't get it, what do you mean ? @prestascott

**Comment by prestascott** [comment]
Hey @Hlavtox, 

So you want to change the wording in the button and replace "Update status" by "Update"?
Like this:
![image](https://user-images.githubusercontent.com/54888056/103634432-53ac3880-4f47-11eb-9ecf-25dd38c1d3aa.png)

It can work but I'm afraid users can be confused by thinking that this button will update the entire page because it's less specific than previous wording.
Since most of our users manage their website from the desktop view, I think it won't be a problem when they will switch on the mobile view.

It's a go for me. 👍  

Let's wait what @Julievrz thinks about this change.

**Comment by NeOMakinG** [comment]
We should change it on desktop too then, right ?

**Comment by prestascott** [comment]
Nope, we only change the wording on the mobile view to gain more space.

**Comment by Hlavtox** [comment]
@prestascott Yes, just like this. It was just a thought :-) What do you guys think?

**Comment by NeOMakinG** [comment]
@prestascott Then we don't change the wording, if we begin to use JS to change some wordings, it will lead to unmaintainable things, and I can't do it using CSS as it would lead to the same problem

**Comment by hibatallahAouadni** [comment]
I agree with @NeOMakinG cause if we use CSS like hide-os for the word status, it will be messy with other translation (that's my thought but it's your desicion :sweat_smile: )

**Comment by prestascott** [comment]
Okay. Shorten the wording isn't worth it, we can leave as it is.

**Comment by Hlavtox** [comment]
What if you name the button "Change"? 😎 
_____

> It can work but I'm afraid users can be confused by thinking that this button will update the entire page because it's less specific than previous wording.

Don't be so scared of merchants Scott, they are not as stupid as the customers, most of the time... 😄

**Comment by Julievrz** [comment]
> @prestascott Then we don't change the wording, if we begin to use JS to change some wordings, it will lead to unmaintainable things, and I can't do it using CSS as it would lead to the same problem

Removing the label then, but do not hesitate to ping me again if you need to. ☺️
