### ISSUE TITLE
Leading zero on BO css should be forced

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22669]
#### Is your feature request related to a problem?

In order to respect best practices, we should force the lint rule for leading zero in BO SCSS

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !
PS: could you please provide more infos :sweat_smile: for the product team to understand better the improvement :wink: 

Ping @PrestaShop/product-team , what do you think?

**Comment by atomiix** [comment]
@hibatallahAouadni it's more of a technical issue, product-team won't help on that 😅
