### ISSUE TITLE
AdminStats Controller KPI best category is bad 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22671]
#### Describe the bug

KPI best category is bad when product with reduction.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Make an order with one product ( **category vêtement** ) 35€ but with 50% reduction
Make an order with one product ( **category art** )  30€ no reduction 
Go to stats to update KPI 
Go to category page check the best category

**Screenshots**

With Change 

![Capture d’écran de 2021-01-05 10-59-54](https://user-images.githubusercontent.com/5064590/103633074-81907d80-4f45-11eb-99d2-3f79bc23178f.png)

Without change

![Capture d’écran de 2021-01-05 11-00-20](https://user-images.githubusercontent.com/5064590/103633090-87865e80-4f45-11eb-8243-fdda1e0eda69.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I was able to reproduce the issue with PrestaShop version 1.7.7.0. 
I’ll add this to the debug backlog.
Thanks for your PR :rocket: 

Thank you
