### ISSUE TITLE
1.7.7.0 Orders Page Header Broken Since Upgrade from 1.7.6.7

### ISSUE THREAD

**Issue by TangoDownUK** [PrestaShop/PrestaShop#22690]
Any help resolving this? Can't seem to find what the problem is and it's driving me mad.

Upgraded manually from 1.7.6.7 to 1.7.7.0 yesterday as one click upgrade didn't work. Since then the Order detail page has been like the attached screenshot. All other pages working fine.

Also when trying to edit the order and add products to it in the BO nothing works.

![image](https://user-images.githubusercontent.com/77059826/103775928-a4df2980-5026-11eb-896d-d5c87da73952.png)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
