### ISSUE TITLE
Registration form accepted spaces on (First Name, Last Name, Password)

### ISSUE THREAD

**Issue by ManeeshTiwari01** [PrestaShop/PrestaShop#22699]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @ManeeshTiwari01 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report and fill the blocks**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
