### ISSUE TITLE
Hook displayAdminProductsSeoStepBottom : issue on 1.7.7.0

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#22695]
hi
I've made a module to add a field into the seo step in the product page (admin side)

    public function hookDisplayAdminProductsSeoStepBottom($params)
    {
        $id_product = (int) $params['id_product']; // or Tools::getValue('id_product');
        $productAdapter = $this->get('prestashop.adapter.data_provider.product');
        $product = $productAdapter->getProduct($id_product);
        $formData = array();
        $formData['meta_keywords'] = $product->meta_keywords;
        $formFactory = $this->get('form.factory');
        $form = $formFactory->createBuilder(FormType::class, $formData)
        ->add('meta_keywords', TranslateType::class, array(
            'required' => false,
            'label' => 'Meta Keywords',
            'locales' => Language::getLanguages(),
            'hideTabs' => true,
        ))
        ->getForm();
        $maoform = array();
        $maoform['form'] = $form->createView();
        $path = dirname(__FILE__).'/views/templates/display-admin-products-extra.html.twig';
        return $this->get('twig')->render($path, $maoform);
    }

    public function hookActionAdminProductsControllerSaveBefore()
    {
        $id_product = (int) $_REQUEST['form']['id_product'];
        $productAdapter = $this->get('prestashop.adapter.data_provider.product');
        $product = $productAdapter->getProduct($id_product);

        foreach (Language::getLanguages() as $language) {
            $product->meta_keywords[$language['id_lang']] = $_REQUEST['form']['meta_keywords'][$language['id_lang']];
        }
        $product->save();
    }

on 1.7.7.0 doesn't work anymore
`$this->get('prestashop.adapter.data_provider.product');`
and
`$this->get('form.factory');`

is it a bug or now there is a new solution to manage product fields ?

thanks

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/103812135-53529100-505e-11eb-9f76-f80883d7a9c1.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by PululuK** [comment]
Hi @maofree 
Can you check please https://github.com/PrestaShop/docs/issues/301

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Thanks @PululuK for your quick reply :wink: I hope it helps @maofree 

Cause I'm not an expert with hooks, I will ping the Core Developers.
Ping @PrestaShop/prestashop-core-developers could someone answer @maofree question :sweat_smile:

**Comment by Maofree** [comment]
Hi
thanks to your infos I have understood how to fix the container problem
```
    public function hookDisplayAdminProductsSeoStepBottom($params)
    {
        global $kernel;
        $id_product = (int) $params['id_product']; // or Tools::getValue('id_product');
        $productAdapter = $kernel->getContainer()->get('prestashop.adapter.data_provider.product');
        $product = $productAdapter->getProduct($id_product);
        $formData = array();
        $formData['meta_keywords'] = $product->meta_keywords;
        $formFactory = $kernel->getContainer()->get('form.factory');
        $form = $formFactory->createBuilder(FormType::class, $formData)
        ->add('meta_keywords', TranslateType::class, array(
            'required' => false,
            'label' => 'Meta Keywords',
            'locales' => Language::getLanguages(),
            'hideTabs' => true,
        ))
        ->getForm();
        $maoform = array();
        $maoform['form'] = $form->createView();
        $path = dirname(__FILE__).'/views/templates/display-admin-products-extra.html.twig';
        return $this->get('twig')->render($path, $maoform);
    }
```

it works also using
```
use PrestaShop\PrestaShop\Adapter\SymfonyContainer;

$this->getSymfonyContainer()->get('prestashop.adapter.data_provider.product');
$this->getSymfonyContainer()->getContainer()->get('form.factory');
```

now I need to understand the part of service, because I get this error

`An exception has been thrown during the rendering of a template ("You have requested a non-existent service "twig".").
`
I understand that it is necessary to add a yml file to set the service but what I write in the file to use twig ?

thanks

**Comment by Maofree** [comment]
so now on 1.7.7 how is it possible to use twig to render a twig file?

return $this->get('twig')->render($path, $maoform);

**Comment by Maofree** [comment]
solved

it is necessary to use the same solution
return $this->get('twig')->render($path, $maoform);
to
return $kernel->getContainer()->get('twig')->render($path, $maoform);

or
$this->getSymfonyContainer()->getContainer()
if you use the other solution

**Comment by Maofree** [comment]
now all works well
thanks for your infos
and to this page
https://gitmemory.com/issue/PrestaShop/PrestaShop/20505/673505701

bye

**Comment by hibatallahAouadni** [comment]
@maofree Glad to hear that you resolved your issue :tada:
