### ISSUE TITLE
Running CLI autoupgrade 1.6.1.24 to 1.7.7 error ; unknown locale code: sv-SE

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#22697]
#### Describe the bug

Fresh install of Prestashop 1.6.1.24
Running cli upgrade from prompt
php cli-upgrade.php --dir=administration --channel=major
Result
INFO - Alla filer uppgraderade. Uppgraderar nu databasen...
INFO - Restart requested. Please run the following command to continue your upgrade:
(All is ok, i am asked to restart, no reason given as to why)
I run next command
 cli-upgrade.php --dir=administration --channel=major --action=upgradeDb --data=LOTS OF CHARS
It goes to a prompt, no message as to what happened or if it's done.
This error is given on admin login
 Oops... looks like an unexpected error occurred
Unknown locale code: sv-SE
[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]

#### Expected behavior

An working 1.7.7.0 should be available.

#### Steps to Reproduce

1. Fresh install a 1.6 Prestashop.
2. Login and install the autoupgrade module. (I got 4.11.0)
3. Run autoupgrade from CLI 
php cli-upgrade.php --dir=administration --channel=major
and follow the instructions.

#### Additional information

* PrestaShop version: 1.6.1.24
* PHP version: 7.3

**Comment by matks** [comment]
> (All is ok, i am asked to restart, no reason given as to why)

When the process is long, autoupgrade CLI attempts to "split" the processing into little chunks in order to avoid timeouts (like SQL connection timeout)... I think 😅 

> [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]

Could you tells us the "configuration" of your PS 1.6 fresh install ? I mean country, language, currencies. If error is LocalizationException it could happen for a specific set of localized settings.

**Comment by matks** [comment]
(also I'm surprised you could perform the upgrade with php7.3 because PS 1.6.1.24 is not supposed to run correctly with php7.3 ?)

**Comment by Prestaworks** [comment]
sure.
Swedish language and location was selected during installation.

**Comment by matks** [comment]
Also 1.7.7.1 is not released yet so the final target should be 1.7.7.0 if I am not wrong ?

**Comment by Prestaworks** [comment]
Yes you are correct, v1.7.7.0 - (2020-12-02) was downloaded.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

> We tried an upgrade like that last week. 1.7.7.0 require php 7.2 so the upgrade failed due to php compatibility issues.
What we did was.
upgrade 1.6 to 1.7.6.8 using php 5.6
change to php 7.x
upgrade 1.7.6.8 to 1.7.7.0

@matks I believe this comment answer your question about PHP version (see the original comment [here](https://github.com/PrestaShop/PrestaShop/issues/22668#issuecomment-755952584))

I tried to upgrade from PS1.6.1.20 (this version is compatible with PHP7.2) to PS1.7.7.0 and I got a lot of errors and all were related to this one #22237 and this bug is already fixed with the next patch 1.7.7.1 :wink: 

Please check my screen record below and feedback:

https://drive.google.com/file/d/1njpII8biSiErHAsxUvrySPM2fPbJ4Z-J/view

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by pkirk** [comment]
Gentlemen,
I've just encountered this problem and it was because I use memcached. You should put on [your update guide](https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/) that the user have to restart it. Or disable the cache before upgrading.
Thanks for your time.

**Comment by matks** [comment]
Hi @pkirk thanks for telling us !

The guide is open source you can contribute to it on https://github.com/prestashop/docs . Would it be possible for you to submit a contribution ? that would credit you 🎉

**Comment by tolomir** [comment]
Hi,
I need some hlep. I'm wondering how to upgrade from 1. 6.24 to 1.7.0 in PHP 7.0. I've tried many times but with no result. Where could I get a Prestashop 1.7.0 version?

Thanks in advance,
Tolo

**Comment by hibatallahAouadni** [comment]
@tolomir here's the link to [PS1.7.0.0](https://www.prestashop.com/fr/versions?version=1.7.0.0&status=&sort_by=field_version_number_value&sort_order=DESC#release-search-version) 
Download the stable version :wink:

**Comment by tolomir** [comment]
Thanks @hibatallahAouadni! Any recommended tutorial to upgrade from 1.6.1.24 to 1.7.0?

**Comment by hibatallahAouadni** [comment]
@tolomir https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/ :wink: enjoy it

PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by hibatallahAouadni** [comment]
PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
