### ISSUE TITLE
Email Configurations

### ISSUE THREAD

**Issue by nickbethke** [PrestaShop/PrestaShop#22706]
SMTP Settings
---
"Use SMTP" settings in the **advanced settings** do not save when changing mail settings to it.
Also the select from above that setting is always empty. Am I missing something in the configurations?

PrestaShop Version: 1.7.7.0
PHP Version: 7.4.13

**Comment by matks** [comment]
Hi @nickbethke PS 1.7.7.0 is not compatible with php7.4, that could create issues. Can you check with php7.3 ?

**Comment by nickbethke** [comment]
I tested it with version 7.3.25 but still no changes with my problem.

**Comment by florine2623** [comment]
Hello @nickbethke ,
I can't reproduce your issue.
Please check your server config https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
