### ISSUE TITLE
Product page - tech/product task - Allow to switch between Product page 1.7.7 or 1.7.8

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22701]
We aim to deliver for PS1.7.8 a new "Add/Edit a Product" page, but in beta phase. This means in 1.7.8 users will be able to use either the current Product page and the new one.

We need to allow users to switch between 'Page V1' and 'Page V2'. This should be done by a button inside a new BO Page, a "feature flag".

However clicking on this button has multiple consequences that we must list.

1. When V1 page is enabled, V2 page should be hidden. If user attempts to reach V2 page, do we redirect him to V1 page or do we return a HTTP 404 response? (ping @PrestaShop/product-team)

2. Links to product page must reach the "active page". For example in Order page you can click on links on product list (or even in products listing) that bring user to Product page. These links should redirect user to the active page, sometimes V1, sometimes V2.

**Comment by jolelievre** [comment]
About question 1. imho the feature flag should influence which page is used by default So it adapts the buttons and links in the list (like you mention in point 2. if I get it right) But I'm not sure we should force the redirection, this way the merchant can use either of the pages (or both) regardless on how the shop is configured

This way if several people use the BO they also can choose which version they prefer.

And finally I would add a suggestion:

3. we could add in the product page a button "Switch to beta page/Switch to regular page" which allows to switch between each version (only present when the feature flag has been enabled)

**Comment by MatShir** [comment]
I guess it is done ;)
