### ISSUE TITLE
Module statsproduct total cross selling sales is bad

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22705]
#### Describe the bug

The row product_price is the price without reduction so the stats are bad

#### Steps to Reproduce

1. Make on order with a discounted product and an other
2. Go to catalog
3. Open a product ordered
4. At the top click on Sales
5. Check the total cross selling product in stats --> stats product

**Screenshots**

![Capture d’écran de 2021-01-07 13-22-32](https://user-images.githubusercontent.com/5064590/103893218-34e7a680-50ed-11eb-8f43-e34a742669c8.png)

#### Additional information

* PrestaShop version: 1770
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

> Check the total cross selling product in stats --> stats product

Could you please specify exactly where I can find this stats (which tab) cause I didn't get the same interface as yours :sweat_smile: Sorry 

![image](https://user-images.githubusercontent.com/23308427/103894519-56499200-50ef-11eb-992e-b2df17d48a14.png)

Thanks!

**Comment by ghost** [comment]
Go to catalog
Open a product
At the top click on Sales

I update the issue

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for the clarification :smile: I managed to reproduce the issue with PS1.7.6.9 and PS1.7.7.0, the product price is the base price without tax.
Thanks again for your PR :rocket: 
I’ll add this to the debug backlog :wink: 

Thanks!

**Comment by Minervavr** [comment]
En el prestashop 1.7 no presenta la bondad de generar los datos de subtotal y descuentos en las estadisticas en una multitienda?. he tratado de generar dichos resultados para cada tienda del sistema, a traves de pruebas en los pedidos que se generan en un carrito de compra , verificando el coto real de la venta y el subtotal. Agradezco su ayuda para poder solventar esta gestiòn.

**Comment by ghost** [comment]
Hi @Minervavr 

For the moment I am correcting all the stats modules.

Then I would watch the multistore work

**Comment by Progi1984** [comment]
Fixed PrestaShop/statsproduct#20
