### ISSUE TITLE
Problem with sessions cookies for SameSite issue

### ISSUE THREAD

**Issue by AliShareei** [PrestaShop/PrestaShop#22711]
#### Describe the bug

As you know, the issue of SameSite in PR #20601 has been resolved. But my concern is that session cookies do not behave in the same way as cookies. PrestaShop uses very few sessions in notifications, admin, and during installation. But many modules may use sessions, especially payment modules. They have set session cookie parameters themselves, otherwise, they will probably have a payment transaction error. My suggestion is to do this next to the cookie params.

I made this PR #22709 for this issue.

#### Expected behavior

I think we expected the behavior of session cookies exactly like normal cookies.

#### Steps to Reproduce

1. remove all cookies from inspect element (Application Tab on chrome)
2. Refresh the page
3. Compare cookie params with sessions.

**Screenshots**

In this screenshot, the first part is related to the current behavior of PrestaShop. The second part of the image is related to the behavior we expect to have.

I made this PR #22709 for this issue.

Video: https://drive.google.com/file/d/1-b9PK1gBZF3MHyQGhFDAUN_vh25pntzq/view

<img width="962" alt="ps-sessions" src="https://user-images.githubusercontent.com/9982451/103901793-da5f4200-510e-11eb-8c96-39c789b0c1f4.png">

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1

**Comment by matks** [comment]
Hi @AliShareei ! thanks for the feedback

As you say

> But many modules may use sessions, especially payment modules. 

Do you have an example of such a module ? Because if we see a module sample we'll be able to explore this issue in details and check this PR covers all the usecases. Also the sample could be used by QA team to explore and validate the PR.

**Comment by AliShareei** [comment]
Hi @matks,

After forcing the SameSite attribute by browsers (especially Chrome), There was a wave of unsuccessful transactions in my country (IRAN) for PrestaShop and other CMS.

The problem arose because the module stored the transaction key in a cookie or session and entered the payment website.
It was redirected to the store after payment was made, but the browser could not read the cookie or session. It was even seen in cases where the user was logged out. (I did not come across this, but some people did.)

We have such a module, but it does not work for you, which means you can not test because you have to have a payment gateway.

But maybe I can talk to the manager of a store in Iran so that we can test on their store together at a specific time, or I can take a video of the procedure for you.

**Comment by Arman-Hosseini** [comment]
> Hi @AliShareei ! thanks for the feedback
> 
> As you say
> 
> > But many modules may use sessions, especially payment modules.
> 
> Do you have an example of such a module ? Because if we see a module sample we'll be able to explore this issue in details and check this PR covers all the usecases. Also the sample could be used by QA team to explore and validate the PR.

@matks, this is almost very important for Iran. I do not know about other countries.

Most payment gateways in Iran have faced this problem and still don't even know how to solve this problem!
I encountered this problem here: https://www.apple-service.ir/, however, I fixed it.
If you want, I can record a video to show its behavior.

**Comment by PierreRambaud** [comment]
Don't forget the SameSite cookie will be automatically settled to Lax in few days/months and a cookie shouldn't be used to store data, if you put too many data in it, it will break everything. Use database or PHP sessions instead :thinking:

**Comment by AliShareei** [comment]
Dears @matks, @Arman-Hosseini, and @PierreRambaud.

I spoke to a store manager today and got permission to make a video.
This test was performed 7 times and the SameSite Attribute problem for Session Cookie is clearly visible.

Tested on PrestaShop 1.7.6.4 and PHP 7.2.33
I apologize for the annoying explanatory boxes in the video.

https://drive.google.com/file/d/1-b9PK1gBZF3MHyQGhFDAUN_vh25pntzq/view

**Comment by Arman-Hosseini** [comment]
> Don't forget the SameSite cookie will be automatically settled to Lax in few days/months and a cookie shouldn't be used to store data, if you put too many data in it, it will break everything. Use database or PHP sessions instead thinking

@PierreRambaud, Of course that the session must be used and sensitive data must be included within the session.
But the SameSite is true not only for cookie but also for session! **The SameSite for session must also be specified.**

**Comment by PierreRambaud** [comment]
> Dears @matks, @Arman-Hosseini, and @PierreRambaud.
> 
> I spoke to a store manager today and got permission to make a video.
> This test was performed 7 times and the SameSite Attribute problem for Session Cookie is clearly visible.
> 
> Tested on PrestaShop 1.7.6.4 and PHP 7.2.33
> I apologize for the annoying explanatory boxes in the video.
> 
> https://drive.google.com/file/d/1-b9PK1gBZF3MHyQGhFDAUN_vh25pntzq/view

Afaik, after seeing your video, you're relying on PHP sessions, not the Cookie, and how PrestaShop manages it.
In the past, only the FrontController used PHP sessions to display notifications.
But since we include Symfony, this one now uses sessions for CSRF token, but this is a different session, not the same one as the Cookie and this one needs can be configured with [session_set_cookie_params](https://www.php.net/session_set_cookie_params). I discourage editing the Cookie class for something related to the PHP configuration.
I'm working on a pull request to properly adding the support of cookie configuration for sessions for PHP7.1+

**Comment by AliShareei** [comment]
Dear @PierreRambaud,
I do not have a specific opinion on where to set the session parameters. I used the cookie class because first the session key is stored by the cookie and secondly because all the values and parameters I needed were already there. And less code means easier review and faster conclusion.

Since I think PrestaShop if has a solution for sessions as well as cookies and it is better to manage it as well because there will be a better standard in the modules.

This is good news is that you are working on this issue and I hope this issue will be resolved as soon as possible in future versions.

I have spoken 😁
