### ISSUE TITLE
Order Notifications on the Favicon misfunction

### ISSUE THREAD

**Issue by CJH297** [PrestaShop/PrestaShop#22716]
Notification of a new order, registration or message all appear correctly with an icon within Prestashop itself, but do not appear in the browser tab in 1.7.7.0 (php 7.3)

Expected that 1.7.7.0 the indication would appear as it did in 1.7.6.x

Order or message comes in, the browser tab does not indicate any activity. Checked on two computers and in Firefox and Edge.

Module is 2.1.0 and all three options are configured to be used

**Comment by hibatallahAouadni** [comment]
Hello @CJH297 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **YOU MUST FOLLOW THE TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
