### ISSUE TITLE
Bug on crossselling bloc in FO 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22715]
#### Describe the bug
using ps_crossselling 2.0.1 bug on the prodcut page in the FO 

#### Steps to Reproduce

1. Go to fo 
2. Click on a product
3. Scroll down to the crossselling bloc

**Screenshots**
https://drive.google.com/file/d/1Yg4QBeRSD2l7uYtvU5_-ME2UJIerczvd/view
<img width="721" alt="Capture d’écran 2021-01-07 à 16 05 51" src="https://user-images.githubusercontent.com/3034677/103911166-fca09200-5105-11eb-861e-568e39fe9eee.png">
<img width="1373" alt="Capture d’écran 2021-01-07 à 16 06 11" src="https://user-images.githubusercontent.com/3034677/103911174-00341900-5106-11eb-99f1-c4b4dd980cee.png">

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sarahdib,

I have the same issue following these steps:
1. Go to BO > Shop Parameters > Product Settings page
2. Enable Catalog mode
3. Go to FO 
4. See an error

![image](https://user-images.githubusercontent.com/16067358/104012463-20201700-51b0-11eb-993d-a7d064397843.png)

I think it is a regression on the develop branch.

PS1771build1 => ok

**Comment by NeOMakinG** [comment]
@khouloudbelguith I can't manage to reproduce like you did

and @sarahdib I can't manage to see the block at all on my shop, is there a specific thing to do to install the crossselling module ? I'm using the dev branch of the module :/

**Comment by sarahdib** [comment]
@NeOMakinG did you enable catalogue mode ?

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I attached a screen record
https://drive.google.com/file/d/1fxcUvWiotCqKbmwaR6h7az7i93ShTb84/view?usp=sharing

Thank you!

**Comment by NeOMakinG** [comment]
Yes I did it :/
