### ISSUE TITLE
500 error in the "all shop" view of combinations for products

### ISSUE THREAD

**Issue by Argez** [PrestaShop/PrestaShop#22710]
#### Describe the bug

Hello I'm having an error in the "all shops" view when editing a product. This view is empty despite having combinations for that product in all stores

I get the 500 error followed by the message Notice: Undefined offset: 0

What could be the cause of this? This error is making it difficult for me to find a solution.
```

Symfony\Component\Debug\Exception\ContextErrorException
in src/Adapter/CombinationDataProvider.php (line 107)
102.	     * @param $product
103.	     * @return array
104.	     */
105.	    public function completeCombination($attributesCombinations, $product)
106.	    {
107.	        $combination = $attributesCombinations[0];
108.	
109.	        $attribute_price_impact = 0;
110.	        if ($combination['price'] > 0) {
111.	            $attribute_price_impact = 1;
112.	        } elseif ($combination['price'] < 0) {

CombinationDataProvider->completeCombination(array(), object(Product))in src/Adapter/CombinationDataProvider.php (line 89)
84.	        $product = new Product($productId);
85.	        $combinations = array();
86.	
87.	        foreach ($combinationIds as $combinationId) {
88.	            $combinations[$combinationId] = $this->completeCombination(
89.	                $product->getAttributeCombinationsById(
90.	                    $combinationId,
91.	                    $languageId
92.	                ),
93.	                $product
94.	            );

CombinationDataProvider->getFormCombinations(array('25420', '25421', '25422', '25423', '25424', '25425', '26579', '26580', '26581', '26582', '26583', '26584'), 3)in src/PrestaShopBundle/Controller/Admin/CombinationController.php (line 45)
40.	        if ($combinationIds === false || count($combinationIds) == 0) {
41.	            return $response;
42.	        }
43.	
44.	        $combinationDataProvider = $this->get('prestashop.adapter.data_provider.combination');
45.	        $combinations = $combinationDataProvider->getFormCombinations($combinationIds, (int) $this->getContext()->language->id);
46.	
47.	        $formFactory = $this->get('form.factory');
48.	        foreach ($combinations as $combinationId => $combination) {
49.	            $forms[] = $formFactory->createNamed(
50.	                "combination_$combinationId",
```

Level | Channel | Message
-- | -- | --
INFO06:46:55 | request | Matched route "admin_combination_generate_form".
DEBUG06:46:55 | security | Read existing security token from the session.
DEBUG06:46:55 | security | User was reloaded from a user provider.
DEBUG06:46:55 | doctrine | SELECT name FROM ps_module WHERE active = 1
INFO06:46:55 | php | User Deprecated: Implementing   "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface"   without the "reset()" method is deprecated since Symfony 3.4 and   will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".
CRITICAL06:46:55 | php | Uncaught Notice: Undefined   offset: 0
CRITICAL06:46:55 | request | Uncaught PHP Exception   Symfony\Component\Debug\Exception\ContextErrorException: "Notice:   Undefined offset: 0" at   /home/vqcdckio/public_html/src/Adapter/CombinationDataProvider.php line 107

#### Steps to Reproduce

1. Go to dashboard
2. Select a product to edit
3. Select the combinations tab

**Screenshots**

![image](https://user-images.githubusercontent.com/11688488/103901833-0ad3bb80-50d0-11eb-8b35-96845fb1e202.png)
![image](https://user-images.githubusercontent.com/11688488/103901872-1b843180-50d0-11eb-96c5-6a1cc1ecf4c1.png)
![image](https://user-images.githubusercontent.com/11688488/103901945-38206980-50d0-11eb-9048-2c95d53278f9.png)
![image](https://user-images.githubusercontent.com/11688488/103901993-42dafe80-50d0-11eb-90b2-9fe0495adfb1.png)

#### Additional information

* PrestaShop version: 1.7.4.3
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Argez 

Could you please downgrade your PHP version to 7.2 cause your PS version is not compatible with PHP 7.3, see our system requirements [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).

Please check and feedback.
Thanks!

**Comment by Argez** [comment]
Good morning. I tried switching to php 7.2, however I still get the same error.

Level | Channel | Message
-- | -- | --
INFO12:16:00 | request | Matched route "admin_combination_generate_form".
DEBUG12:16:00 | security | Read existing security token from the session.
DEBUG12:16:00 | security | User was reloaded from a user provider.
DEBUG12:16:00 | doctrine | SELECT name FROM ps_module WHERE active = 1
INFO12:16:00 | php | User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".
CRITICAL12:16:00 | php | Uncaught Notice: Undefined offset: 0
CRITICAL12:16:00 | request | Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined offset: 0" at /home/vqcdckio/public_html/src/Adapter/CombinationDataProvider.php line 107

**Comment by Argez** [comment]
php 7.1, does it also work for prestashop 1.7.4.3?

**Comment by hibatallahAouadni** [comment]
@Argez you can check the PHP compatibility with PS version [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) :slightly_smiling_face: 

>php 7.1, does it also work for prestashop 1.7.4.3?

Yes :wink:

**Comment by Argez** [comment]
Good morning, I already did all the tests with the version and it still generates the same error

I have been following line by line and apparently in this part of the GameObject.php the problem is being generated

        if ($this->isMultishop() && !$this->id_shop) {
            $this->id_shop = Context::getContext()->shop->id;
        }

**Comment by hibatallahAouadni** [comment]
Hello @Argez 

I tried with PS1.7.7.0 to create a product while "all shops" selected and generate combinations, all went successfully.
Then, when I try to edit the combinations quantity I got an exception thrown :sweat_smile: 
So, I went to every shop and I added the combinations quantity and when I selected "all shops" all the combinations are well displayed, see the attached screen record below:

https://drive.google.com/file/d/1YwhFKR1THf8ePaX8DMTpaopWT-2bm6ZF/view

Please check and feedback.
_PS: your issue is related to this one_ #9664

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Argez ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
