### ISSUE TITLE
when we create a certain number of categories and subcategories (a very large number) the editing of the products stops working to make modifications

### ISSUE THREAD

**Issue by Hugh1975** [PrestaShop/PrestaShop#22724]
Hello Good afternoon, we need technical support for our prestashop website.

Our website is for motorbike spare parts and when we create a certain number of categories and subcategories (a very large number) the editing of the products stops working to make modifications, it remains blank or does not finish loading.

We need your help.

Thank you and Greetings.

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
