### ISSUE TITLE
Price specification not found for currency: "".

### ISSUE THREAD

**Issue by ADQS-FR** [PrestaShop/PrestaShop#22733]
Hello,

I am having a problem that I cannot resolve.

When I go to Brands and Suppliers and I want to view the details of my supplier I have this error message (See image n ° 1);

An unexpected error has occurred. [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0] : Price specification not found for currency: "".

I have already tried to solve the problem by doing:

reinstallation of the French language + Currency from "localization" but nothing to do with the problems and still present.

I also looked in the database but everything looks correct to me (See image n ° 2)

 

Here is a list of information from my Prestashop

Information about your server Linux #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
Server software version : Apache
PHP version : 7.2.34
Memory limit : 2048M
Maximum execution time : 400
Max size for sending files : 2M
MySQL version : 10.3.27-MariaDB-0+deb10u1
MySQL engine : InnoDB
MySQL connector : DbPDO
PrestaShop version : 1.7.7.0

https://zupimages.net/up/21/01/7w6u.png
https://zupimages.net/up/21/01/dmbf.png
https://zupimages.net/up/21/01/yn0s.png
https://zupimages.net/up/21/01/6415.png
https://zupimages.net/up/21/01/qf5q.png

**Comment by florine2623** [comment]
Hello @Soowarez ,

Please modify your request in English. English is the norm on GitHub.
Please include the steps to reproduce your issue as well.

Thank you

**Comment by ADQS-FR** [comment]
> Hello @Soowarez ,
> 
> Please modify your request in English. English is the norm on GitHub.
> Please include the steps to reproduce your issue as well.
> 
> Thank you

It's OK for you ?

**Comment by florine2623** [comment]
Please check in Localization > Configuration :
![Capture d’écran 2021-01-08 à 10 19 16](https://user-images.githubusercontent.com/16019289/103997169-0aecbd80-519b-11eb-9fc2-9e0e0bb3f181.png)
Try to  Import the "France" (your country) pack, clear cache, check & feedback.

**Comment by ADQS-FR** [comment]
I just applied what you advised me to do.
I have deleted the cache (Domain / var / cache)
But the error and always the

**Comment by ADQS-FR** [comment]
<img width="1268" alt="Capture d’écran 2021-01-08 à 10 26 45" src="https://user-images.githubusercontent.com/29873403/103998510-62d7f400-519c-11eb-9c23-abc9915da435.png">

<img width="906" alt="Capture d’écran 2021-01-08 à 10 26 07" src="https://user-images.githubusercontent.com/29873403/103998587-71bea680-519c-11eb-968e-75210e5c0a08.png">

**Comment by florine2623** [comment]
Can you try to delete the French language and import the language pack once again ?

**Comment by ADQS-FR** [comment]
I have just deleted the French language then reinstalled.
But the problem and still the ... I would say that he cannot find the EUR device which however and by default.

**Comment by florine2623** [comment]
Could you please follow this comment [#14595 (comment)](https://github.com/PrestaShop/PrestaShop/issues/14595#issuecomment-510884182), try with this solution and feedback.

**Comment by florine2623** [comment]
Hi @Soowarez ,
since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!
