### ISSUE TITLE
Responsive - BO - Multistore - Icon View my shop is not display and cannot be selected

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22739]
#### Describe the bug

While testing this [PR](https://github.com/PrestaShop/PrestaShop/pull/22526), I found this regression:
In the BO, when the multishop context is enabled, we have some issues with icon view my shop when using mobile or size window `1298 * 982 px`

On the **migrated page**: it is not displayed, but we can click on it
![image](https://user-images.githubusercontent.com/16067358/104019501-f371fc80-51bb-11eb-8a03-a67334f68c96.png)
![image](https://user-images.githubusercontent.com/16067358/104019628-2ddb9980-51bc-11eb-8d6f-2727836380f1.png)

On the **legacy page**, it is displayed, but we can't click on it.
![image](https://user-images.githubusercontent.com/16067358/104019721-5cf20b00-51bc-11eb-9283-ae5e9d6e6528.png)
![image](https://user-images.githubusercontent.com/16067358/104019757-6a0efa00-51bc-11eb-82b1-e7aa98d4623d.png)

#### Steps to Reproduce

1. Go to BO > Shop Parameters > General page
2. Enable multishop context
3. Create a new shop
4. Using a mobile > go to the Dashboard page
5. Try to click on view my shop 
6. See the error
7. Go to the BO > Orders page
8. Try to click on view my shop 
9. See the error

#### Additional information

* PrestaShop version: develop (1780)
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
Gonna check it out
