### ISSUE TITLE
Useless redirection on shop logo in multilingual context

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#22748]
#### Describe the bug
In multilingual context, the shop logo link to the home page doesn't have the lang prefix (/en).
So, a redirection takes places on every click. Google doesn't like redirection so much.

#### Expected behavior

Link to the home page should contains the lang prefix (/en)

#### Steps to Reproduce

1. Install at least two lang
2. Hover shop logo
3. See that lang prefix is missing
4. Click and see the redirection

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thanks for your issue and your PR :wink: 
Your suggestion looks as an improvement more than a bug and it's a kind of similar to this one #16865.
Could you please check and feedback.

Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni issue #16865 is not the same problem.

**Comment by hibatallahAouadni** [comment]
@jf-viguier Well then, I managed to reproduce your issue but let's ping the product team to see if it's a bug or an improvement :wink: 

Ping @PrestaShop/product-team do you think what @jf-viguier suggest is a bug or an improvement? cause I see there's no error or exception thrown, so IMHO I think it's an improvement (to add the lang prefix) :sweat_smile:

**Comment by MatShir** [comment]
IMO it is an improvement and relevant one. Thanks, @jf-viguier for the feedback
