### ISSUE TITLE
Redirect to Dashboard when you try to access the Module Catalog after uninstalling the MBO module

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#22740]
#### Describe the bug

After uninstalling the **MBO** module, I tried to navigate to the **BO**>**Modules**>**Module Catalog** page. The system redirect me to **BO**>**Dashboard**.

#### Expected behavior

Redirect to **BO**>**Modules**>**Module Catalog**

#### Steps to Reproduce

1. **BO**>**Modules**>**Module Manager**
2. Uninstall the **MBO** module
3. Go to the **Module Catalog** page
4. See error: the system will redirect you to **Dashboard**

**Screenshots**

https://drive.google.com/file/d/1RZl1Oa0cGXDR-UGaaRQCt6gLBNOrGZ3R/view

#### Additional information

* PrestaShop version: 1.7.7.0 & 1.7.7.1
* PHP version: 7.2

**Comment by eternoendless** [comment]
Fixed by https://github.com/PrestaShopCorp/ps_mbo/pull/102

**Comment by hibatallahAouadni** [comment]
Duplicate of #21588
