### ISSUE TITLE
Decimal separator not standardized.

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#22750]
Hello,

decimal separator not standardized.

as you can see from this image the decimal separator in the price tab is not the same in all fields, commas and periods alternate.

In the price of the product there is the point while in the special prices the comma.

Kind regards

PS Version: 1.7.6.8

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Betafer** [comment]
Hello, 

I don't think there is much to explain,

also on the product page and not only on the pricing page there is the problem: the price without taxes uses the comma as a separator, while the price including taxes uses the period.

Come da immagine di seguito

<img width="385" alt="Schermata 2021-01-12 alle 11 03 26" src="https://user-images.githubusercontent.com/5024055/104299934-1b1bda00-54c6-11eb-933c-772d32cbab8b.png">

**Comment by SimonGrn** [comment]
We need you to follow the template. Please open a new issue and fill the corresponding sections.
Thank you.
