### ISSUE TITLE
The ps_product table duplicates columns from ps_product_shop

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#22757]
#### Describe the bug

Long time ago prestashop went to multishop version (afaik since 1.5), and now when I am creating a migration script for products from one source to the 1.7.7.0 and I am very confused about that.

I honestly do not expect any kind of fix to it (since this may not be a bug, and even if then there are probably some backward compatibility reasons), but for the love of god I starve for something that at looks like a documentation / explanation for it.

These columns are present **only** in **ps_product**, but **not** in **ps_product_shop**

* id_supplier
* id_manufacturer
* id_shop_default
* ean13
* isbn
* upc
* mpn
* quantity
* reference
* supplier_reference
* location
* width
* height
* depth
* weight
* out_of_stock
* additional_delivery_times
* quantity_discount
* cache_is_pack
* cache_has_attachments
* is_virtual
* state

Does it mean that quantity is shared across all shops, but the name of the product may be different in each of them?

Right now when I look at these fields I have a feeling like a multishop instance is kind'ish of a one warehouse + multiple frontends. So we have on example a sticker product with the same quantity across many UIs (hence one warehouse, the location stays the same, ean code etc), but we can name that product differently in every UI. Ie. In one shop the sticker will be called dragon, and in other it will be a dinosaur. This is the only way I can think of it.

So the best way I can form a question is if there is any reason (other than backward compatibility with plugins for v1.5 that if exists will never be updated by a man with any non-freezing IQ level) to keep duplicated columns both in ps_product and ps_product_shop? 

Why would I need on example a "on_sale" flag both in ps_product and ps_product_shop tables?

**Comment by matks** [comment]
> but for the love of god I starve for something that at looks like a documentation / explanation for it.

Haha we wish we had this too 😄  the people who built multishop did not leave a documentation behind. We are left to reverse-engineer this stuff.

Good news: since we also need this doc, we started doing the tiresome work of reverse-engineering the multistore system to find out how it works, what is good, what is wrong, what needs to be fixed. A 1st Pull Request for documentation was landed 6 days ago https://github.com/PrestaShop/docs/pull/843 . But before we have a complete understanding of all of this, many more PRs will be needed.

Feel free to have a look 😉  maybe you'll even have some hints you can share

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
