### ISSUE TITLE
[PS 1.7.5.1] Il carrello non può essere caricato o un ordine è già stato creato con questo carrello

### ISSUE THREAD

**Issue by Gae-arredi** [PrestaShop/PrestaShop#22751]
Salve a tutti e grazie anticipate per il vostro aiuto.
Da qualche giorno ho riscontrato un problema su un sito prestashop già attivo da oltre 1 anno, senza aver effettauto nessuna operazione di modifica particolare (installazioni, aggiornamenti,ecc), e precisamente dopo aver scelto il metodo di pagamento di un ordine e cliccato per pagare l'ordine, invece di restituire la conferma dell'ordine, (dopo essere trascorso del tempo in cui la rotellina continua a girare) restituisce il seguente messaggio di errore "**Il carrello non può essere caricato o un ordine è già stato creato con questo carrello**" con qualsiasi metodo di pagamento sempre nella pagina “validation” esempio 
 https://www.XXXXXXX.com/it/module/XXXXXXXXXXXX/validation (non so se si può scrivere l'indirizzo del sito per esteso).

Ho già provato a ripristinare il database a prima del problema, ma non è cambiato nulla.
Ho ache provato a tornare a versioni precedenti di PHP, ma il problema persiste.

Qualcuno ha avuto lo stesso problema e ha trovato la soluzione?

* PrestaShop version: 1.7.5.1
* PHP version: 7.0

Grazie ancora e saluti

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. **Your request MUST BE in English.**
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
