### ISSUE TITLE
Backoffice Login page stuck after upgrading 1.7.6.8 to 1.7.7.0

### ISSUE THREAD

**Issue by Dar-us-Salam** [PrestaShop/PrestaShop#22758]
When upgrade from 1.7.6.8 to 1.7.7.0, I get the following 3 errors and I am not able to login to the admin panel any more. It gives a blank login screen as shown here (no matter if login is correct or not): https://prnt.sc/wjxs3w . I turned on DEBUG but don't see any error.

Screenshot for the errors: https://prnt.sc/wjxtbo
```
SQL 1.7.7.0 1146 in ALTER TABLE `link_block` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'dusp_Elementor.link_block' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `link_block_lang` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'dusp_Elementor.link_block_lang' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `link_block_shop` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'dusp_Elementor.link_block_shop' doesn't exist
```

I tried to locate the 3 tables mentioned but couldn't find them in the database. I only found these similar ones: field_htmlblock_lang and field_htmlblock_shop . 

I tried the upgrade process twice and both times the same result so now I am not upgrading until a fix is done. Please let me know if additional information is needed. Thanks.

#### Additional information

* PrestaShop store: https://elm.dusp.org/
* PHP version: 7.1 and also tried 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Dar-us-Salam 

These tables belong to ps_linklist (Link Widget) Module.
So could you please check in your **BO**>**IMPROVE**>**Module Manager** if this module is installed.

![image](https://user-images.githubusercontent.com/23308427/104166905-cad84580-53fb-11eb-89ef-12dd9b3fc5d0.png)

Please check and feedback.

Thanks!

**Comment by Dar-us-Salam** [comment]
Thank you for the response. Yes, I had uninstalled the module as it wasn't being used. I just reinstalled it and the errors went away and it says successfully updated but I still get stuck at the login screen: https://prnt.sc/wjxs3w . It doesn't make a difference if the pw is correct or not, still same screen comes up. I couldn't figure it out even with the debug on, it doesn't give any errors nor could I find anything in the error_log. Any particular place I should look to resolve this situation or help support fix this bug? 

You can try the login and see the issue in action
I have another install on the same server and it is having the exact same issue.

**Comment by hibatallahAouadni** [comment]
Hello @Dar-us-Salam 

Unfortunally I didn't manage to reproduce it, so I can't help anymore :confused: 
If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: next time don't post your shop url for security reason :wink: 

Thanks!

**Comment by Dar-us-Salam** [comment]
I upgraded to the latest Upgrade Module v4.11 and tried to update to the new 1.7.7.1 but still I cannot login to the admin: https://prnt.sc/wlaxt2

Overall website is working after I turned off maintenance mode from MySQL. The issue is similar to people posting on this thread: https://www.prestashop.com/forums/topic/1027039-update-1766-problem-backoffice/

Nevermind, I think I will just download and install a fresh 1.7.7.1 install and then copy the theme over. Hopefully won't have this issue again.

**Comment by Dar-us-Salam** [comment]
I installed a fresh copy of PS 1.7.7.1 and it is doing the same thing so it has to do with the new 1.7.7 update. I contacted hosting tech support but they weren't able to help. Everything looks okay on the server side: https://dusp.org/phpinfo.php but there is definitely something in the update that needs fixing. If Prestashop can't fix this bug, I will just have to wait for them to figure it out from other complaints.

**Comment by Dar-us-Salam** [comment]
I just got a comment on [my post](https://www.prestashop.com/forums/topic/1040099-cant-login-to-backoffice-in-ps-1771/) in the forums in which JBW told me about [this post ](https://github.com/PrestaShop/PrestaShop/issues/22300) which explains that an old ICU version is causing this issue. I will upgrade my ICU 4.2 to finally fix this issue.

**Comment by hibatallahAouadni** [comment]
@Dar-us-Salam glad to hear :tada:

**Comment by simbus82** [comment]
> I just got a comment on [my post](https://www.prestashop.com/forums/topic/1040099-cant-login-to-backoffice-in-ps-1771/) in the forums in which JBW told me about [this post ](https://github.com/PrestaShop/PrestaShop/issues/22300) which explains that an old ICU version is causing this issue. I will upgrade my ICU 4.2 to finally fix this issue.

Hi @Dar-us-Salam, how did you upgrade ICU?

In standard servers with CPanel, changing the default ICU of php 7.3 (icu 4.x) is impossibile, it is tied to the system and it is needed a new compile of php (that can't be done so easely in a production server).

I don't understand why Prestashop 1.7.7.x need an ICU that can't be found "standard" in PHP 7.3 and PHP 7.2, the only ICU supported is in PHP 7.4, that is not compatible with Prestashop 1.7.7x

My problem is that with Prestahop 1.7.7.1 i need to use PHP 7.4, so the FO customer registration doesn't work. (the customer registration in checkout is working instead)
But if i switch to PHP 7.3 with the old ICU, i can't access  to backend.

It's loop!

**Comment by giles247** [comment]
> 
> 
> > I just got a comment on [my post](https://www.prestashop.com/forums/topic/1040099-cant-login-to-backoffice-in-ps-1771/) in the forums in which JBW told me about [this post ](https://github.com/PrestaShop/PrestaShop/issues/22300) which explains that an old ICU version is causing this issue. I will upgrade my ICU 4.2 to finally fix this issue.
> 
> Hi @Dar-us-Salam, how did you upgrade ICU?
> 
> In standard servers with CPanel, changing the default ICU of php 7.3 (icu 4.x) is impossibile, it is tied to the system and it is needed a new compile of php (that can't be done so easely in a production server).
> 
> I don't understand why Prestashop 1.7.7.x need an ICU that can't be found "standard" in PHP 7.3 and PHP 7.2, the only ICU supported is in PHP 7.4, that is not compatible with Prestashop 1.7.7x
> 
> My problem is that with Prestahop 1.7.7.1 i need to use PHP 7.4, so the FO customer registration doesn't work. (the customer registration in checkout is working instead)
> But if i switch to PHP 7.3 with the old ICU, i can't access to backend.
> 
> It's loop!

Did you find any solution for this? 

We are now locked out of upgrading to PrestaShop 1.7.7.3 because hosting provider tells us ICU v4.2.1 can't be upgraded on PHP 7.3 and PS is not yet compatible with PHP 7.4! What are we supposed to do?

**Comment by Dar-us-Salam** [comment]
Sorry, I just saw your message. Our previous host was going to upgrade our
VPS to fix the issue but we ended up switching hosting companies altogether
and everything is working okay now. They didn't just upgrade the ICU but
the whole OS system.

Thanks,
Omar Waheed
Dar-us-Salam Publications
http://dar-us-salam.com
