### ISSUE TITLE
[ps_linklist] Multilanguage - The block name must be set in all language to be created

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#22755]
#### Describe the bug

Issue moved from https://github.com/PrestaShop/ps_linklist/issues/

original message from @khouloudbelguith 

```
With the last version of the ps_linklist v3.0.1, PS1.7.5.0beta1 with multilanguage, to add a new block, we must set all the block name in all language to create this block, which is unnecessary, we need just to verify that the block name in the default language is not blank.
I attached a video record.
https://drive.google.com/file/d/1q1MuiGuUGQ-0zAIehiEbamegkQNmf-Bm/view
```

#### Expected behavior

From @jolelievre 

```
This seems legit! I will had the precisions about what we discussed:

you can add a block name/links without filling all the languages
the default language is mandatory though
if a language has not been set then we must fallback to the default language
```

#### Steps to Reproduce

https://drive.google.com/file/d/1q1MuiGuUGQ-0zAIehiEbamegkQNmf-Bm/view

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I reproduced the issue with PS1.7.7.1 and ps_linklist v3.2.0. I’ll add this to the debug backlog so that it’s fixed.
Waiting for your PR :wink: :rocket: 

Thanks!
