### ISSUE TITLE
Presta shop problem 1.7 login user

### ISSUE THREAD

**Issue by przemexm** [PrestaShop/PrestaShop#22759]
#### Describe the bug

the upgrade from 1.7.5.2 to the newest 1.7.7.0 with the 1-click module was 100% correct without error
the whole store runs orders, create a user account, send e-mails order, etc. admin login OK

the problem appears when you try to log in the user despite entering the correct login and password the page seems to be reloading but logging in does not go, only the user has a problem, admin to the admin panel log in without a problem

#### Expected behavior
The customer could log in successfully

#### Steps to reproduce

1. Upgrade your shop 1.7.5.2 to 1.7.7.0
2. FO, try to connect as a customer
3. See error => the page seems to be reloading but logging in does not go

#### Additional informations
PS version: 1.7.7.0
PHP version: 

---
table in the database are
`ps_customer_session` and `ps_employee_session`

So that's not the problem

deleting temporary files, changing browser another computer does not help.

**Comment by hibatallahAouadni** [comment]
Hello @przemexm 

I already edit your issue so could you please confirm the steps to reproduce and provide the PHP version.
And **PLEASE NEXT TIME FOLLOW THE TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**, we provide this template to make it easy to reproduce your issue and to help you ASAP :wink: 

Thanks!

**Comment by waschier-design** [comment]
Same Error here

**Reproduce ERROR:**
Upgrade from PS 1.7.6 to 1.7.7.0 --> Customer can't sign in.
Then Upgraded to PS 1.7.7.1 --> Error stays the same.

PHP Version 7.2.34
Mysql 5.7 (InnoDb)
