### ISSUE TITLE
Request AJAX edit Product (very slow) and Import product (error 404) - 1.7.7

### ISSUE THREAD

**Issue by Ctek59** [PrestaShop/PrestaShop#22767]
Hello,

I have a problem with the ajax requests for products edition and products import :

**Edition products:**
All manipulation for edit/save product is very slow, in the page product edit, the button save is disabled during 80sec minimum but if i refresh after 3sec the product is good edit.

The button "enable / disable" product do same thing.

In list product, enable the selection is very slow too.

I haven't error, no log ...

**Import products**

The first request of 0 to 5 product is ok, after i have error 404 ( in request AJAX).

* PrestaShop version: 1.7.7
* PHP version: 7.3.23

Thank you

**Request call stack:**
```
Send: Main.bundle.js:formatted: 33316  -> 
`o.send(e.hasContent && e.data || null)`

Ajax: Main.bundle.js:formatted: 33182   ->
` s.send(b, n)`

Send: From.js?1.7.7.0:648  ->
`$.ajax({
      type: 'POST',
      data: data,
      beforeSend: function() {
        $('#submit', elem).attr('disabled', 'disabled');
        $('.btn-submit', elem).attr('disabled', 'disabled');
        $('ul.text-danger').remove();
        $('*.has-danger').removeClass('has-danger');
        $('#form-nav li.has-error').removeClass('has-error');
        updateDisplayGlobalErrors(null);
      },`

Anonymous: From.js?1.7.7.0:842 ->
`      elem.submit(function(event) {
        event.preventDefault();
        send();
      });`

dispatch: Main.bundle.js:formatted: 31869  -> 
`void 0 !== (n = ((De.event.special[r.origType] || {}).handle || r.handler).apply(s.elem, l)) && !1 === (o.result = n) && (o.preventDefault(),`

_.handle: Main.bundle.js:formatted: 31801  -> 
`return void 0 !== De && De.event.triggered !== t.type ? De.event.dispatch.apply(e, arguments) : void 0`

```

**Comment by hibatallahAouadni** [comment]
Hello @Ctek59 

I didn't manage to reproduce your issue :confused: 
Could you please check your store configuration, **BO**>**CONFIGURE**>**Advanced Parameters**>**Information**:

![image](https://user-images.githubusercontent.com/23308427/104189443-f28ad600-541a-11eb-86da-fe14ea78f1a9.png)

Check your **Memory limit**, **Max execution time** and **Upload Max File size** and feedback.

Thanks!

**Comment by Ctek59** [comment]
Thank you for answer.

Limite de mémoire : 4096M
Temps maximal d'exécution : 360
Taille max. pour envoi de fichiers : 512M

**Comment by hibatallahAouadni** [comment]
Hello @Ctek59 

Unfortunally I didn't manage to reproduce your issue with fresh install 1.7.7.0
Did you upgrade you shop lately? if so, could you please provide your previous version.

Thanks!

**Comment by Ctek59** [comment]
My previous version is 1.7.6.9, i have retrograded, very bad idea, I had a lot of mistakes, I had to delete or overwrite files.
With the version 1.7.6.9, i haven't problem
Now, I have upgraded with 1.7.7.1, i have again the problem ...

**Comment by kpodemski** [comment]
It's probably related to some third party modules you have in your store, hooked into those actions like saving the product etc. Maybe you have some advanced search module or something like that?

**Comment by Ctek59** [comment]
That's right, when I deactivate the module "Advanced Search 4", i haven't problem. 
I contact the support of module.

Thank you.

**Comment by hibatallahAouadni** [comment]
@Ctek59 glad that your issue is solved :tada: 
@kpodemski thanks for helping :wink: 

I close this issue cause it's not related to the PrestaShop Core.
Thanks!
