### ISSUE TITLE
API /orders endpoint inconsistent return format of JSON

### ISSUE THREAD

**Issue by Morph21** [PrestaShop/PrestaShop#22760]
#### Describe the bug

Endpoint /orders have 2 different formats of json returned based on quantity of orders which will be fetched.

#### Expected behavior

I expect it to returns orders in same format, or different HTTP status code for empty list. The first one is a preffered

#### Steps to Reproduce

1. Call api /orders?output_format=JSON&display=full
2. It will be in format
`{
    "orders": [
        {
        ...
}
]}`
3. Call api /orders?output_format=JSON&display=full&limit=100000,20 (or other limit number which will return empty list)
4. Response will be in format
`[]`

That format is wrong, if you look at xml response you can see that it always returns format
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <orders></orders>
</prestashop>
```

Preffered format of json for empty list of orders should be like this:
```
{
    "orders": []
}
```
Now you clearly see that base object is an Object not a List/Array of objects and that orders are empty

**Screenshots**
![image](https://user-images.githubusercontent.com/38075691/104166784-95cbf300-53fb-11eb-99bc-47fb6a4ca500.png)
![image](https://user-images.githubusercontent.com/38075691/104166799-9c5a6a80-53fb-11eb-8b33-f8faaa3475b5.png)

XML screenshots
![image](https://user-images.githubusercontent.com/38075691/104166915-cf046300-53fb-11eb-893c-cb8c232bd037.png)
![image](https://user-images.githubusercontent.com/38075691/104166959-df1c4280-53fb-11eb-8ff5-abbe8aeb960a.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

**Comment by hibatallahAouadni** [comment]
Hello @Morph21 

Thanks for your issue :wink: 
I reproduced your issue with PS1.7.7.0, see the attached screen record below:

- JSON format

![image](https://user-images.githubusercontent.com/23308427/104172772-10e5d700-5405-11eb-8604-410994a1ada1.png)

- XML format

![image](https://user-images.githubusercontent.com/23308427/104172795-1b07d580-5405-11eb-8e1a-6e2fd5e699da.png)

> Preffered format of json for empty list of orders should be like this:
{     "orders": [] }
Now you clearly see that base object is an Object not a List/Array of objects and that orders are empty

We need the Developer opinion about that :sweat_smile: 

Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers can someone please specify this bug :wink:

**Comment by PierreRambaud** [comment]
I confirm it's a bug, we have to be consistent between returns.

**Comment by Kyaary** [comment]
Hello,
I'd like to start contributing to Prestashop.
Can I work on this issue ?

Thank you in advance

**Comment by PierreRambaud** [comment]
> Hello,
> I'd like to start contributing to Prestashop.
> Can I work on this issue ?
> 
> Thank you in advance

Anyone can work on it,  just be the first to create the pull request :wink:

**Comment by Kyaary** [comment]
'Does it look like what you were expecting ?
My PR is ready to review ! :smile_cat: 

![PR](https://user-images.githubusercontent.com/22498741/105637064-b3717180-5e6b-11eb-87e2-e8c7e7f87b22.png)
![PR2](https://user-images.githubusercontent.com/22498741/105637065-b4a29e80-5e6b-11eb-82ec-94c0ce957c86.png)

**Comment by Morph21** [comment]
@Kyaary Yea, that's good, even response like this would be good "{}" it's just a matter with difference in parsing JSON between object ("{}") and array/list ("[]")

Every parser by default would print an error :)

**Comment by camillo777** [comment]
Hello, is there any ETA for this bug corrected in Prestashop stable release?

**Comment by matks** [comment]
@camillo777 there is no ETA for this bug.

If you find that this issue is important for you, you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. This will be the quickest way to obtain the fix.
