### ISSUE TITLE
Can not access old orders after upgrading from 1.7.6 yo 1.7.7.

### ISSUE THREAD

**Issue by idiamin777** [PrestaShop/PrestaShop#22770]
#### Describe the bug

Upgrading to 1.7.7.0 went well some 2 month ago - now when I want to access old orders I get a fatal error 

#### Expected behavior

The order should be seen for download or print

#### Steps to Reproduce

1. Go to order
2. Click on open order
3. See error page

**Screenshots**
![image](https://user-images.githubusercontent.com/69144740/104218062-7ef9c080-543c-11eb-82f2-f6b5ff2b320e.png)

#### Additional information

The issue https://github.com/PrestaShop/PrestaShop/issues/22386 did help on our testshop which has the same configuration but the newest orders are missing

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @idiamin777 

I'm sorry but I couldn't manage to reproduce your issue, could you please check these issues #22611 & #22215 
Please check and feedback.

Thanks!

**Comment by idiamin777** [comment]
Thanks Hibatallah,

Like I wrote I had the fault on test and live shop after upgrading – but I first found the fault 1 month later as a customers asked for an old invioice.

After working with the hack proposed in issue #22611 the testshop works fine but the live shop gives this new / similar error. 

Hope somebody find a solution - Ar

**Comment by idiamin777** [comment]
In the meantime the error was solved. The problem came through an upgrade of a design modul same time with upgrading to 1.7.7. The modul designer/programmer went all the way and more to find and change the fault i code. 

Thanks a lot

**Comment by hibatallahAouadni** [comment]
Hello @idiamin777 

Glad to hear that problem is not from PS Core :tada: 
I close this issue. If you encounter any other problem with your shop, feeel free to open a new issue.
We will be glad to investigate it.

Thanks!

**Comment by idiamin777** [comment]
Thanks 😊
