### ISSUE TITLE
Google Maps backoffice order page

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#22776]
#### Is your feature request related to a problem?

After updating from 1.7.6 to 1.7.7 I no longer have Google Maps in my back office order page. I find this handy.

I know Google Maps is not standaard showing in 1.7.6 or lower, but by adding your API key manually in AdminOrdersController

:  $this->addJS('https://maps.googleapis.com/maps/api/js?v=3.exp'); it worked.

I tried the same fix in 1.7.7.X and it no longer works.

#### Describe the solution you'd like

I would like to know how get this to work again.

#### Alternatives you've considered

Prestashop offering a build-in solution for this like in PS 1.6.

This is how it looked in 1.7.6

<img width="800" alt="Screenshot 2021-01-11 at 20 10 31" src="https://user-images.githubusercontent.com/46492443/104233094-31d01b80-5449-11eb-8e03-9cc467d5a7f0.png">

This is what I would like in 1.7.7x

<img width="633" alt="Screenshot 2021-01-11 at 20 15 53" src="https://user-images.githubusercontent.com/46492443/104233641-216c7080-544a-11eb-948e-13ab3508aab5.png">

**Comment by matks** [comment]
Hi, GoogleMaps changed is free plan pricing and usage so it could not be used like before, see details in https://github.com/PrestaShop/PrestaShop/issues/10393

We could not find a suitable free and opensource replacement for GoogleMaps so we removed it. It was better than leaving a broken feature.

If you like it, you can develop a module that embed a GoogleMap widget inside Order page. There are plenty hooks available in the Order page where you can plug such a module. The module will need to use your own API key for Google.
