### ISSUE TITLE
Cart Rules section has a broken view - all tabs are on one page instead of divided into 3 sections

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#22773]
**Describe the bug**

Hello,
I wanted to create a discount code for a customer and I have noticed that Discounts -> New Cart Rules section is not working properly. All 3 sections (Information, Conditions, Actions) are appearing on one page (take a look on the attached screenshot) instead of being divided into 3 separate sections. Some of the buttons are not working anymore (like Generate button or calendar buttons). Also at the bottom save buttons are not working. It's like something happened with the CSS. I have cleared cache, cleared browser cache, checked on a different and unused browser, removed manually all files in var/cache category, replaced all files in admin folder with the the files from freshly downloaded PS. Nothing helped. I do not know where to look for the problem anymore. I have noticed the issue on PS 1.7.6.8. After upgrading to 1.7.6.9 the New Cart Rules section started to work properly for about 2 days and the problem appeared again. 3 days ago I have updated my shop to 1.7.7.0. The problem disappeared but re-appeared today. I do not know how to solve that. I have also noticed that while I am in Dashboard section and click on the notification bell the popup with latest orders, customers and messages does not appear but after refreshing the page numbers shown on the bell are changing (It looks like I have read the notifications). When I go to a different section (for example Catalog ->products) then the bell works with no problem and the pop-up with all notifications appears with no problem. Does anyone know what could happen and how to solve it?

**Steps to Reproduce**

1. Go to Catalogs -> Discounts -> Basket Rules -> Add new
2. That's it. Once the page is opened all sections are on one page instead o divided into 3 sections.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/48493952/104221901-dc444080-5441-11eb-8dec-b7e318e6a2bf.png)

**Additional information**

Server information Linux #1 SMP Thu Sep 17 06:10:33 EDT 2020 x86_64
Server software version: Apache
PHP version: 7.2.34
Memory limit: 800M
Max execution time: 600
Upload Max File size: 200M
MySQL version: 10.4.17-MariaDB-cll-lve
MySQL engine: InnoDB
MySQL driver: DbPDO

**Comment by Hlavtox** [comment]
@banan44 If you open your browser console (F12 maybe), there should be some errors, copy them here.

**Comment by hibatallahAouadni** [comment]
Hello @banan44 

Thanks for your issue but could you please edit your issue **following the provided template to submit a complete bug report**.
We provide these blocks (**describe the bug**, **expected behavior**, **steps to reproduce**, ...) cause we need it to help you resolve your issue :wink: 

Thanks!

**Comment by banan44** [comment]
@hibatallahAouadni hi, I have updated my first post.

@Hlavtox thank you for information. I have opened console. I have not thought to check that as well. Here are the faults I have

```
This page uses the custom property "zoom". Consider using calc() in appropriate property values or using "transform" together with "transform-origin: 0 0". index.php
Uncaught DOMException: String contains an invalid character rocket-loader.min.js:1
    g https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
    forEach self-hosted:206
    g https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
    forEach self-hosted:206
    g https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1
```

My domain is linked with CloudFlare services.

**Comment by Hlavtox** [comment]
@banan44 These errors are caused by cloudflare. However, I use it too in free edition and everything is fine.

Try to clear cache in CF dashboard and if it does not help, try to disable CF caching and speedup options one by one and see if it fixes the issue. 👍

**Comment by banan44** [comment]
@Hlavtox thank you so much for your help. I did what you wrote. It turns out the Rocket Loader function was causing the problem. Once I turned it off the Discount page works correctly :)

**Comment by hibatallahAouadni** [comment]
@banan44 glad to hear that @Hlavtox helps you resolving your issue :tada: 
Thanks @Hlavtox :wink:

**Comment by Hlavtox** [comment]
@banan44 Goood!!!
@hibatallahAouadni No prob 😎 

@matks Hey, what about adding a section to Prestashop documentation aboud Cloudflare? Write there, that you need to disable IP adress checking in backoffice, that rocket loader does problems and stuff like this. It can be found on the internet forums, but if the first result was official documentation, even better. Wdyt? :-)

**Comment by matks** [comment]
@Hlavtox it could be great indeed to mention it in the docs. I dont know if there is a good location for this, but we can always add it to "Frequently Asked Questions" https://devdocs.prestashop.com/1.7/faq/
