### ISSUE TITLE
Type error: Return value of CartCore::getCartPriceFromCatalog() must be of the type float, null returned

### ISSUE THREAD

**Issue by WartoWiedziec** [PrestaShop/PrestaShop#22784]
After the last update from 1.7.7.0 to 1.7.7.1, I cannot open and view what is happening in the shopping carts. You will get the error as shown in the attached screenshots.
Does anyone know what to enter and where this error would disappear?
![2021-01-12](https://user-images.githubusercontent.com/6594124/104303117-f45fa280-54c9-11eb-9cbc-e809b422bc36.png)
![2021-01-12 (1)](https://user-images.githubusercontent.com/6594124/104303144-00e3fb00-54ca-11eb-95c6-7a580fc09a0c.png)

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.17

**Comment by hibatallahAouadni** [comment]
Hello @WartoWiedziec 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by malcek** [comment]
Same here, we are having same issue. If you click on the name of customer you get this error, but if you click on any other part of order you can go to order detail.
![image](https://user-images.githubusercontent.com/54998637/106572403-a8d46d80-6538-11eb-9991-8df450d65be2.png)

Prestashop: ver 1.7.7.1
PHP version: 7.3.23
MySql: 10.1.48-MariaDB-cll-lve

**Comment by hibatallahAouadni** [comment]
Hello @malcek 

We need steps to reproduce the issue, cause with the provided details by @WartoWiedziec I didn't manage to reproduce.
So could you please provide more clear and detailed steps to reproduce.

Thanks!

**Comment by malcek** [comment]
sorry i have update my post :)

**Comment by malcek** [comment]
also whan you are in order detail any if you want to go to full detail about customer you also ger this error

![image](https://user-images.githubusercontent.com/54998637/106572985-62334300-6539-11eb-8a0e-2f3447dcec14.png)

**Comment by hibatallahAouadni** [comment]
Did you upgrade your store lately? If so, what was your old version?

**Comment by malcek** [comment]
Yes I have update last week.
My old version was 1.7.6.4 and after that i have made first manual update to 1.7.6.9 and than with autoupdate from 1.7.6.9 to latest 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @malcek 

I just upgrade my shop from 1.7.6.9 to 1.7.7.1 and I didn't manage to reproduce your issue:

https://drive.google.com/file/d/1mu_m_RtxsZO-Twk9UkvoBHQH5MKA-kqT/view

Please check and feedback.
Thanks!

**Comment by malcek** [comment]
Hello @hibatallahAouadni 
I don't know why is at your setup everything fine, but for me i still get this error. And this is core error and i don't think it's related to any additional modul

Type error: Return value of CartCore::getCartPriceFromCatalog() must be of the type float, null returned
[Symfony\Component\Debug\Exception\FatalThrowableError 0]

best regards
martin

**Comment by hibatallahAouadni** [comment]
Did you encounter any issues with your upgrade?

**Comment by malcek** [comment]
@hibatallahAouadni 
it was some warning with yellow background, nothing serious.

**Comment by claireb25** [comment]
Hi @malcek, did you find a solution to your issue ? I'm having the same problem here..

**Comment by mathieucm** [comment]
Same for us, any solution ?

**Comment by DonDiegoDeLasVegas** [comment]
Hi, same problem but just with one customer...

**Comment by Fourmarketing360** [comment]
same here
