### ISSUE TITLE
Duplicate address after editing an address (Prestashop 1.7.6.9)

### ISSUE THREAD

**Issue by valentintur** [PrestaShop/PrestaShop#22781]
Bug like https://github.com/PrestaShop/PrestaShop/issues/18100

Not fixed

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
