### ISSUE TITLE
How to add a customer phone number in admin order grid - Prestashop 1.7.7.1

### ISSUE THREAD

**Issue by aruneaskan** [PrestaShop/PrestaShop#22787]
I tried a custom module to add a column in the admin order grid. 

Unfortunately, hookActionOrderGridDefinitionModifier is not working. I'm not able to add a column.

Please let me know how to do that. I need a detailed explanation.

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
