### ISSUE TITLE
Add custom module fields in ProductCombination form

### ISSUE THREAD

**Issue by Renrhaf** [PrestaShop/PrestaShop#22788]
#### Describe the bug

For a client, I wanted to display additional fields into the Product and ProductCombination forms.
For the product one, no problem using the `displayAdminProductsExtra` and `actionProductUpdate` hooks.
For the combination one, I encountered issues dealing with form submission after using `displayAdminProductsCombinationBottom` hook. Symfony complained about extra fields submitted and thrown an exception. Thus the `actionProductAttributeUpdate` was never called.

#### Expected behavior

Allowing extra fields in the ProductCombination form to allow modules to alter the form.

#### Steps to Reproduce

1. Create a module.
2. Use the `displayAdminProductsCombinationBottom` hook inside.
3. Use a template and add a field like `<input type="text" class="form-control" name="combination_{{ id_product_attribute }}[attribute_xyz]" id="combination_{{ id_product_attribute }}_attribute_xyz" value="{{ attribute_xyz }}" />`
4. Edit a product with a combination, edit the combination, save it.
5. See the error.

**Screenshots**

![image](https://user-images.githubusercontent.com/690629/104320066-d127f980-54af-11eb-8444-c274054bb252.png)
![image](https://user-images.githubusercontent.com/690629/104320092-dab16180-54af-11eb-8b35-749372f12620.png)
![image](https://user-images.githubusercontent.com/690629/104320133-ec930480-54af-11eb-8ec3-92ef86db9550.png)

With the fix

![image](https://user-images.githubusercontent.com/690629/104320183-00d70180-54b0-11eb-9540-44997c24a1b1.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Renrhaf 

Thanks for your issue and your PR :rocket: 
But I think this is not a bug, it's an improvement (cause it looks more like a PrestaShop limitation)

So, lets ping the Developers Team to approve your suggestion :wink: 
Ping @PrestaShop/prestashop-core-developers  do you think what @Renrhaf suggests is a bug or an improvement?

**Comment by khouloudbelguith** [comment]
Hi @hibatallahAouadni,

I manage to reproduce the issue with PS1771.
![image](https://user-images.githubusercontent.com/16067358/104435326-8b8d2e80-558c-11eb-8586-3504f06ef9c5.png)

I think, it is a bug, as detailed here: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/
```php
displayAdminProductsCombinationBottom
Located in: /src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_combination.html.twig
```
>Edit

@Renrhaf, I don't have any Validator calls
![image](https://user-images.githubusercontent.com/16067358/104436774-48cc5600-558e-11eb-87cf-9c05e5660148.png)

Thank you!

**Comment by hibatallahAouadni** [comment]
Thanks @khouloudbelguith :wink:

**Comment by Renrhaf** [comment]
Hi @khouloudbelguith, 

Thank you for reproducing the bug.
I'll put the whole code I used below to demonstrate the validator issue.

In `modulename.php` : 

```
   ....
   
   /**
     * Display of additional fields on product combination entities.
     *
     * @param array $params
     *   Product combination parameters.
     */
    public function hookDisplayAdminProductsCombinationBottom(array $params)
    {
        $idProductAttribute = _PS_VERSION_ < '1.7' ? (int) Tools::getValue('id_product_attribute') : (int) $params['id_product_attribute'];
        $custom_var = 'Something random';

        return $this->get('twig')->render('@Modules/modulename/views/admin-combination-custom-tab.twig', [
            'id_product_attribute' => $idProductAttribute,
            'attribute_custom_var' => $custom_var,
        ]);
    }

    /**
     * Save additional fields on product combination entities.
     *
     * @param array $params
     *   Product combination parameters.
     */
    public function hookActionProductAttributeUpdate(array $params)
    {
        $idProductAttribute = $params['id_product_attribute'];
        $combinations = Tools::getValue('combinations');
        if (!empty($combinations['combination_'.$idProductAttribute])) {
            $custom_var = $combinations['combination_'.$idProductAttribute]['attribute_custom_var'] ?? NULL;
            // Do something
        }
    }
    
    ...
```

In `modulename/views/admin-combination-custom-tab.twig` : 

```
<div class="row">
    <div class="col-md-12">
        <h2>{{ 'Custom attributes'|trans }}</h2>
    </div>
</div>

<div class="row">
    <fieldset class="col-md-4 form-group">
        <label class="form-control-label" for="combination_{{ id_product_attribute }}_attribute_custom_var">
            {{ 'Custom var'|trans }}
        </label>

        <input type="text" class="form-control" name="combination_{{ id_product_attribute }}[attribute_custom_var]" id="combination_{{ id_product_attribute }}_attribute_custom_var" value="{{ attribute_custom_var }}" />
    </fieldset>
</div>
```

I do not know from where the Error 500 you got came otherwise.
Have a nice day

**Comment by khouloudbelguith** [comment]
Hi @Renrhaf,

Thanks for your feedback.
I manage to reproduce the issue using this module
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/5809064/mymodule.zip)

Thank you!

**Comment by itsmelata21** [comment]
![Screenshot from 2023-01-18 12-05-53](https://user-images.githubusercontent.com/86701083/213101398-51656373-599c-411d-81bb-c9641c886da9.png)
getting error while saving fields please check screenshot on 1.7.6.8

**Comment by JoseManuelFV** [comment]
> ![Screenshot from 2023-01-18 12-05-53](https://user-images.githubusercontent.com/86701083/213101398-51656373-599c-411d-81bb-c9641c886da9.png) getting error while saving fields please check screenshot on 1.7.6.8

The changes are from 1.8 onwards.
You can make the changes manually

https://github.com/PrestaShop/PrestaShop/pull/22777/commits/65fc80bc33194767f7e5063646565245caca7795
