### ISSUE TITLE
PS 1.7.7.0 Address coming automatically

### ISSUE THREAD

**Issue by dhanpreet452** [PrestaShop/PrestaShop#22799]
Using prestashop 1.7.7.0 PHP version 7.3.25

1. Add product to cart
2. Click on checkout
3. Checkout as guest
4. Put personal details and click next . Address coming automatically 

store url : ondafloral.com 
Tried with classic theme , same error persist[
![Untitled](https://user-images.githubusercontent.com/62125896/104363348-0a2d9180-54e3-11eb-9208-5a43da2b2205.png)

**Comment by hibatallahAouadni** [comment]
Hello @dhanpreet452 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/10C4doBwORSslFj86uPsp7LQR1WkeR-Ji/view

I think your issue is related to a cache issue or some module issue.
Please check and feedback.

Thanks!

**Comment by dhanpreet452** [comment]
HELLO @hibatallahAouadni  , there is not even single module installed outside of what is created by prestashop . Cache is deleted many times. Tried in multiple computers at multiple location and same issue persist.

**Comment by dhanpreet452** [comment]
I truncated ps_address table and issue went away

**Comment by hibatallahAouadni** [comment]
Hello @dhanpreet452 

Glad that you solved your issue but it's weird behavior 😕 
Did you upgrade your shop lately? 

Please check and feedback.
Thanks!

**Comment by dhanpreet452** [comment]
@hibatallahAouadni no i am developing new shop :/ . I am not able to reproduce as well so i am closing it .

**Comment by hibatallahAouadni** [comment]
Hello @dhanpreet452 

>  I am not able to reproduce as well

Glad to know :tada: 
If you encounter any other issue with your PS shop please feel free to open a new one :wink: 

Thanks!
