### ISSUE TITLE
Missing localization pack for Monaco

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#22790]
#### Describe the bug

Orders placed to Monaco do not contain any tax.

#### Expected behavior

Orders placed to Monaco must respect the French VAT.

#### Steps to Reproduce

1. Place an order with delivery in Monaco
2. Prices are exclusive of VAT

I'll make a PR soon.

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

Could you please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/22339#issuecomment-742627545) cause it seems your issue is a duplicate to this one #22339 and please provide your PS and PHP versions :confused: 

Please check and feedback.
Thanks!

**Comment by micka-fdz** [comment]
Hi @hibatallahAouadni, my issue is not a duplicate of #22339.

My issue is about default tax rules inside localization packages. I'll make a PR.

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

In reality I manage to reproduce your issue, but it seems for me it's not a bug as Monaco and France are different countries :sweat_smile: I thought that the normal behavior.

> Orders placed to Monaco must respect the French VAT.

Ping @PrestaShop/product-team any idea about this topic? :confused:

**Comment by micka-fdz** [comment]
PR available here : #22811

**Comment by hibatallahAouadni** [comment]
Thanks for your quick fix :clap: 
But we need the Product team approval :wink:

**Comment by LouiseBonnard** [comment]
> Ping @PrestaShop/product-team any idea about this topic? 😕

You're right, @hibatallahAouadni, it's not a bug but a feature request: there are no VAT rates available for Monaco since there is no localization pack. You can either add them manually in the BO or create the Monaco localization pack. :-)

Regarding the PR, thanks @micka-fdz, I'm not sure about adding the reference to the tax rates without stocking it in a dedicated localization file, it might complicate the update if the tax rate evolves. What's your recommendation, @PrestaShop/prestashop-core-developers?

**Comment by PierreRambaud** [comment]
> > Ping @PrestaShop/product-team any idea about this topic? confused
> 
> You're right, @hibatallahAouadni, it's not a bug but a feature request: there are no VAT rates available for Monaco since there is no localization pack. You can either add them manually in the BO or create the Monaco localization pack. :-)
> 
> Regarding the PR, thanks @micka-fdz, I'm not sure about adding the reference to the tax rates without stocking it in a dedicated localization file, it might complicate the update if the tax rate evolves. What's your recommendation, @PrestaShop/prestashop-core-developers?

AFAIK, Monaco has nothing related to France, even if the VAT is the same :thinking: 
If yes, it has to be managed like any other country zone.

**Comment by LouiseBonnard** [comment]
@PierreRambaud, thank you, it confirms my doubt. @micka-fdz, do you feel like creating the Monaco localization pack?

**Comment by micka-fdz** [comment]
Yes @LouiseBonnard I can try to create Monaco localization pack but I don’t understand why.

In my PR, I just added Monaco country inside tax rules of all European countries. In this way, if we import French localization pack (for example) or install PS in French, orders to Monaco will have the VAT applied.

**Comment by Progi1984** [comment]
@micka-fdz As said by @PierreRambaud `Monaco has nothing related to France, even if the VAT is the same thinking` so it needs to be managed like any other country zone. And it's why, we ask you to add the Monaco localization pack in your PR.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

I changed this issue status to **`To Do`** as an improvement to add the **Monaco** localization pack.

Thanks!

**Comment by micka-fdz** [comment]
Hi @PierreRambaud @LouiseBonnard @Progi1984,

I updated my PR to add Monaco localization pack. Can you have a look?

**Comment by Progi1984** [comment]
@micka-fdz Could you do your PR on https://github.com/PrestaShop/LocalizationFiles too ?

**Comment by micka-fdz** [comment]
Yes @Progi1984 I'll do that.

**Comment by micka-fdz** [comment]
@Progi1984 done ✅
