### ISSUE TITLE
Shadows harmonizations

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#22806]
#### Is your feature request related to a problem?

The new design of the Theme Classic isn't applied on some components, especially on shadows. It needs to be consistent.

#### Describe the solution you'd like

Remove shadows so our components use the new design like the checkout in flat design style. 

Related PR: https://github.com/PrestaShop/PrestaShop/pull/20775

**Comment by LouiseBonnard** [comment]
Hi @prestascott, @NeOMakinG, what's the status of this issue? Is it already a work in progress?

**Comment by prestascott** [comment]
@LouiseBonnard Hey, @NeOMakinG did a PR and it seems good to me 👍
