### ISSUE TITLE
Cannot install on Oracle MySQL 5.6

### ISSUE THREAD

**Issue by barda** [PrestaShop/PrestaShop#22809]
#### Describe the bug

Cannot install on Oracle MySQL 5.6
Prestashop version: 1.7.7.1 (also development branch is affected)            
                                                                             
Installation blocks at the create table step with:                           
                                                                             
> Index column size too large. The maximum column size is 767 bytes.           

#### Expected behavior

Installation goes forward creating MySQL tables.

#### Steps to Reproduce

1. Start installation
2. Configure connection to an Oracle MySQL 5.6
3. See error

#### Additional information

* PrestaShop version: >=1.7.7.1
* MySQL version: Oracle MySQL 5.6

### Suggestion

To allow a bigger index prefix the InnoDB `ROW_FORMAT=DYNAMIC` must be used but in MySQL 5.6 the default is COMPACT and cannot be changed at server or session level but only when creating table.
`innodb_large_prefix=ON` and `innodb_file_format = Barracuda` are not enough.         

https://dev.mysql.com/doc/refman/5.6/en/innodb-row-format.html                              
> The default row format for InnoDB tables is COMPACT
> ...
> The DYNAMIC row format is supported by the Barracuda file format.
> ...
> The DYNAMIC row format supports index key prefixes up to 3072 bytes. This feature is controlled by the innodb_large_prefix variable, which is disabled by default. See the innodb_large_prefix variable description for more information.
                                                                             
So at least for tables:                                                      
- ps_customer                                                                
- ps_employee                                                                
- ps_admin_filter                                                            
- ps_shop_url                                                                
- ps_connections_source                                                      
- ps_smarty_lazy_cache                                                       
- ps_order_state                                                             
- ps_page_type                                                               
- ps_smarty_cache                                                            
- ps_configuration                                                           
                                                                             
File `install-dev/data/db_structure.sql` must be changed with:               
                                                                             
```
CREATE TABLE ()...                                                           
...  ) ENGINE=ENGINE_TYPE ROW_TYPE=DYNAMIC ...  
```                            
                                                                             
When the installation has been completed with `ROW_TYPE=DYNAMIC` you can verify
the size of indexes built on characters columns:

```
mysql> USE mydb;                                                   
mysql> select S.TABLE_SCHEMA,S.TABLE_NAME,S.INDEX_NAME,SUM(CHARACTER_OCTET_LENGTH) size from information_schema.statistics S join information_schema.columns C USING (TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME) where TABLE_SCHEMA=DATABASE() GROUP BY S.TABLE_SCHEMA,S.TABLE_NAME,S.INDEX_NAME HAVING size > 767 ORDER BY size desc;
+--------------+-----------------------+----------------------------+------+
| TABLE_SCHEMA | TABLE_NAME            | INDEX_NAME                 | size |
+--------------+-----------------------+----------------------------+------+
| mydb         | ps_customer           | customer_login             | 2040 |
| mydb         | ps_employee           | employee_login             | 2040 |
| mydb         | ps_admin_filter       | admin_filter_search_id_idx | 1404 |
| mydb         | ps_shop_url           | full_shop_url              | 1112 |
| mydb         | ps_shop_url           | full_shop_url_ssl          | 1112 |
| mydb         | ps_connections_source | http_referer               | 1020 |
| mydb         | ps_smarty_lazy_cache  | PRIMARY                    | 1020 |
| mydb         | ps_order_state        | module_name                | 1020 |
| mydb         | ps_customer           | id_customer_passwd         | 1020 |
| mydb         | ps_connections_source | request_uri                | 1020 |
| mydb         | ps_page_type          | name                       | 1020 |
| mydb         | ps_employee           | id_employee_passwd         | 1020 |
| mydb         | ps_customer           | customer_email             | 1020 |
| mydb         | ps_smarty_cache       | cache_id                   | 1016 |
| mydb         | ps_configuration      | name                       | 1016 |
+--------------+-----------------------+----------------------------+------+
```
                                                                   
Building indexes on columns using `utf8mb4` charset is likely to exceed the 
maximum length of 767 bytes because in example `customer_login` index on
`ps_customer` table is on columns `(email, passwd)` which are `utf8mb4` (=max 4 
bytes) and `varchar(255)` (=max 255 characters) so the index prefix reaches
`255*2*4=2040` bytes.                                                
                                                                   
This issue does not affect Oracle MySQL 5.7 which has `ROW_FORMAT=DYNAMIC` by
default and also the `innodb_default_row_format` variable to change it at
global or session level.                                           
                                                                   
https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_default_row_format

The same issue is likely present in MariaDB <=10.2.1 because 
https://mariadb.com/kb/en/innodb-dynamic-row-format/           
> In MariaDB 10.2.1 and before, the default row format is COMPACT.
...                                                       
> In MariaDB 10.2.2 and later, the default row format is DYNAMIC, as long as the innodb_default_row_format system variable has not been modified. Therefore, in these versions, the easiest way to create an InnoDB table that uses the DYNAMIC row format is by not setting the ROW_FORMAT table option at all in a CREATE TABLE or ALTER TABLE statement.

**Comment by hibatallahAouadni** [comment]
Hello @barda 

Could you please provide your PHP version and check our system requirements [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/).
Please check and feedback.

Thanks!

**Comment by barda** [comment]
PHP 7.3.24.
I think the relevant requirements are meet:
![phppsinfo](https://user-images.githubusercontent.com/440593/104560575-5ba26180-5646-11eb-81e4-ddb123d4bd54.png)

**Comment by hibatallahAouadni** [comment]
Hello @barda 

To be honest they're not exactly "meet" 😅 you need to maximize your PHP configuration to meet the recommended values and to give fully access to the Directories mentioned above (var/cache, var/logs, ...).

Could you please check and feedback.
Thanks!

**Comment by matks** [comment]
Hi @hibatallahAouadni from the bug report I believe it might be interesting to check whether @barda buggy behavior can be reproduced 😉 

> Building indexes on columns using utf8mb4 charset is likely to exceed the
maximum length of 767 bytes because in example customer_login index on
ps_customer table is on columns (email, passwd) which are utf8mb4 (=max 4
bytes) and varchar(255) (=max 255 characters) so the index prefix reaches
255*2*4=2040 bytes.

> This issue does not affect Oracle MySQL 5.7 which has ROW_FORMAT=DYNAMIC by
default and also the innodb_default_row_format variable to change it at
global or session level.

May I suggest we add the `waiting-for-dev` label?

**Comment by hibatallahAouadni** [comment]
Thanks @matks already done :heavy_check_mark: 
Ping @PrestaShop/prestashop-core-developers could you please reproduce @barda issue :wink: 
Thanks in advance.

**Comment by PierreRambaud** [comment]
It's more like a bug because `email`, and `passwd` fields should be in `191` because of utf8mb4, this is what we do for indexes. But weird that nothing occurred on `KEY`

**Comment by hibatallahAouadni** [comment]
@PierreRambaud did you reproduce the issue?

**Comment by PierreRambaud** [comment]
No, I'm not able to install Oracle MySQL 5.6 on my machine. Too old for my computer

**Comment by peterpeter** [comment]
Same error here on a clients hosting. Occurs with PS 1.7.7.0 and 1.7.7.1, the same error while installing. 
As I can't attach a screenshot, the system check as link:
https://tessinerspezialitaeten.ch/mhp/phppsinfo.php

**Comment by nicohery** [comment]
I reproduce this bug on multiple hosting or local configs using MySQL < 5.7 or MariaDB < 10.2.
Prestashop team should at least update [https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ ](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ )
Adding database requirement with a beautiful chart as like as PHP one.

**Comment by hibatallahAouadni** [comment]
Hello @nicohery 

> Prestashop team should at least update https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Adding database requirement with a beautiful chart as like as PHP one.

You're right we should.
@matks can we update this doc?

Thanks!

**Comment by matks** [comment]
I don't understand what we should update?

Be careful: on https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ we are talking about standard MySQL database. Oracle MySQL is a different database. As far as I know, the docs says nothing about Oracle MySQL compatibility.

**Comment by barda** [comment]
"Standard MySQL" does not mean anything.

MySQL flavours are (at least):
- Oracle MySQL = https://dev.mysql.com/
- MariaDB = https://mariadb.com/
- Percona = https://www.percona.com/software/mysql-database

Here we are stating this bug is affecting Oracle MySQL < 5.7 and MariaDB < 10.2 due the missing row format in SQL file used during the installation.

**Comment by matks** [comment]
@barda it's not even that simple 😛  as "Oracle MySQL" used to be "Oracle" or "MySQL" and some people used "Oracle MySQL" as an alias for "Oracle".

There is indeed a need for disambiguation. I use "Standard MySQL" to refer to https://dev.mysql.com/ as there was a time MySQL was not affiliated to Oracle 😄  .

**Comment by hibatallahAouadni** [comment]
Hello @barda 

Since we had no news from you for over a year, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
