### ISSUE TITLE
WebService: Adding product image fails, when another image is set as cover

### ISSUE THREAD

**Issue by KminekMatej** [PrestaShop/PrestaShop#22803]
#### Describe the bug

I have a product on PS. This product has already some images attached to it. One of these images is marked with cover=1 in DB, table ps_image.

![image](https://user-images.githubusercontent.com/16462921/104464305-12550200-55b3-11eb-9872-410a5607eaa3.png)

The I try to load another image. Using webservice request POST: /api/images/products/1326 , data:

```
{
   "image":{
      "name":"\/var\/www\/vhosts\/kminet.eu\/subdomains\/boost.kminet.eu\/api\/www\/images\/file\/focjivjnh1v0kq99",
      "mime":"image\/png",
      "postname":"profilovka_xs.png"
   }
}
```
That returns error:

97: [SQL ERROR] DUPLICATE ENTRY '1326-1' FOR KEY 'ID_PRODUCT_COVER'. FROM DBCORE->INSERT() QUERY WAS : INSERT INTO `PS_IMAGE` (`ID_PRODUCT`, `POSITION`, `COVER`) VALUES ('1326', '3', '1')

#### Expected behavior

Image added

#### Steps to Reproduce

Described up

**Screenshots**

dtto

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by KminekMatej** [comment]
What is the actual problem? WebService is using `Image::getCover($productId)` function to check if there is any cover set, but based on different table (**ps_image_shop**) than table to which it actually inserts data (**ps_image**). So, in **ps_image_shop** it finds out, there is no cover image. Cover property gets set to 1. And then it tries to add new record to **ps_image** table with cover = 1. And thats the moment where it fails, due to (correct) unique key **_idx_product_image_**

https://github.com/PrestaShop/PrestaShop/blob/0f079f07693fcb2eb192c5fe31ad3aaafdcccff4/classes/Image.php#L348-L351

Possible solution would be to check existing cover based on table **ps_image** instead of **ps_image_shop**. Or - as it seems to me - not to have duplicate column **cover** in both tables - **ps_image** and **ps_image_shop**.

Since I am not actually sure what is the purpose of having two tables **ps_image** and **ps_image_shop**, I wont rather create pull-request

**Comment by hibatallahAouadni** [comment]
Hello @KminekMatej 

You need to downgrade your PHP version cause PS1.7.6.8 is not compatible with PHP 7.4 see our system requirements [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements).
Please check and feedback.

Thanks!

**Comment by KminekMatej** [comment]
Youre absolutely right. Sorry , I didnt realize that Im using PHP-FPM with different PHP versions - everything runs on PHP7.4, but prestashop runs on php 7.2. Without that, almost nothing would work :)

**Comment by KminekMatej** [comment]
But during another tests, I realized another thing. When I uploaded another image, column cover got checked i both tables - **ps_image** and **ps_image_shop**. So probably, some error happened before this attempt, leading to current issue.

Which is not surprising as I am trying everything with api.

So far Im closing this issue as the problem probably lies elsewhere.

**Comment by hibatallahAouadni** [comment]
@KminekMatej Glad to hear :tada:

**Comment by germain-italic** [comment]
I would like to reopen the issue because I am facing the same problem while migrating a shop from PS1.5 to PS1.7 using the MigrationPro addon (yes I'm using PHP7.2 and MySQL 5.7).

I've noticed that the DB schema on PS1.5 is:
![](https://files.italic.fr/chrome_oJBwA075J6.png)

While on PS1.7 it is:
![](https://files.italic.fr/chrome_2QS3F5GJC1.png)

The same change also applies to the index `ps_image_shop.id_product`.

I don't see the point on setting them uniques.
How does one migrate an old shop with these freshly unique keys?

**Comment by KminekMatej** [comment]
@Germain-Italic - Setting key id_product_cover to UNIQUE in my opinion totally makes sense - there can be only one image, marked as cover for each id_product.
What doesnt make sende is to hold this information in both tables - ps_image and ps_image_shop. That can lead to unexpected behaviour, when in one table is set another cover than in other table (which was my main problem).

I have no experiences with the MigrationPro addon you mentioned, however adding UNIQUE constraint in Migration, must be prepended by ensuring proper conditions for this key to set - in this case, that there is one cover for one product. I guess this operation os not there, leading to failure during migration.

I think the actual question raised from this issue is - Why are there two tables, holding the same information (id_product_cover)?
For you, I would suggest you check your DB if you have duplicate covers set on one product - cleaning these may help the migration to process flawlessly

**Comment by germain-italic** [comment]
Thanks @KminekMatej the operation is there but failed because of duplicates that where introduced in PS1.5.

I have found  8,882 duplicates (on 34,044 products) using;

```sql
SELECT 
    id_product, COUNT(id_product),
    cover, COUNT(cover)
FROM
    ps_image
GROUP BY 
    id_product, 
    cover
HAVING 
       (COUNT(id_product) > 1) AND 
       (COUNT(cover) > 1)
```

Therefore it was much easier to remove the UNIQUE condition than modify all the product page.

I'll comment if my shop fails once the migration is complete.
