### ISSUE TITLE
Autoupgrade is unusable

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#22817]
In Addons 1-click upgrade is not available. The page is there nut you cannot download anything.

Using PS 1.7.6.1 I have version 3.0.3 of 1-click upgrade. When I click on the Upgrade button I get an error message and nothing is upgraded. 

So I went to Github and downloaded the latest version (4.11.0) there. But when I try to install it I get an error. See the attached image.
![upgrade](https://user-images.githubusercontent.com/13930107/104481852-8baa2000-55c6-11eb-8038-eb177c4bbd6c.jpg)

**Comment by matks** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22819

**Comment by hibatallahAouadni** [comment]
Thanks @matks :wink:
