### ISSUE TITLE
Issue when sending email TO customer FROM the order details page. link to reply link not included in footer

### ISSUE THREAD

**Issue by forkyboy** [PrestaShop/PrestaShop#22810]
I am not sure if the issue was describe before, i will do a proper report if it is new:

Issue:

when sending email TO customer **FROM the order details page**.
the email received by the customer do not contain the link to reply, nor the text 

it should be like this in the footer :

Please do not reply directly to this email, we will not receive it. In order to reply, click on the following link: https://URL.com/en/contact-us?id_customer_thread=3&token=rXXCCX

EDIT: will apply the last PS patch and check again
my current PS version is 1.7.7.

**Comment by hibatallahAouadni** [comment]
Hello @forkyboy 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
