### ISSUE TITLE
Custom store url by each language

### ISSUE THREAD

**Issue by ruchus** [PrestaShop/PrestaShop#22824]
I can't custom different storeurl by each store language on PS in differents domain. Is common for large websites need to install each language of the store in a country specific domain TLD .... es .... fr .... co.uk.

I find that it is a basic functionality MUST HAVE, that it should have a serious multi-store ecommerce and not too complicated to implement. Other ecommerce software does and we need to migrate to Prestashop.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report or a feature request**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
