### ISSUE TITLE
Adding Tracking-Number/-Code doesn't work & only one shipping-method shown

### ISSUE THREAD

**Issue by sebastian-marinescu** [PrestaShop/PrestaShop#22826]
#### Describe the bug

We have an irregular bug, which consists of following behaviors.

A) On some orders, when editing the shipping / wanting to add an tracking-code, it only shows 1 shipping-method. 

In the order-overview it shows the correctly chosen shipping-method of the client: 

![image](https://user-images.githubusercontent.com/3798871/104570804-a9bd6200-5652-11eb-8e65-6ecd886fdcf3.png)

But when pressing on _edit_ it only shows one/the first method: 

![image](https://user-images.githubusercontent.com/3798871/104570920-c6f23080-5652-11eb-952c-4298f247b989.png)

B) On this _broken_ orders, when editing shipment and adding a tracking-code, after saving, it says something like:

> PrestaShopException Code 0: `Cart->id_currency` is empty

And it didn't save the tracking, nor did it send the email.

#### Expected behavior

Editing shipping-methods and adding tracking-numbers should always work, as it's part of daily operation.

**Screenshots**

Shipping-Methods:
![image](https://user-images.githubusercontent.com/3798871/104571544-80e99c80-5653-11eb-89ca-f43e9397a898.png)

Shipping-Preferences:
![image](https://user-images.githubusercontent.com/3798871/104571657-a4144c00-5653-11eb-9a48-96becb83f762.png)

#### Additional information

* PrestaShop version: v1.6.x - v1.7.x
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @sebastian-marinescu ,

I can't reproduce your issue on PS 1.7.7.0.
I can choose the carrier on editing mode :
![Capture d’écran 2021-01-14 à 12 16 35](https://user-images.githubusercontent.com/16019289/104584246-92867080-5662-11eb-88dc-2c0c6592d9cf.png)
You need to make sure the carrier is available for the address of the order and that the carrier is enabled.

I can also add the tracking number of my choice :
![Capture d’écran 2021-01-14 à 12 18 59](https://user-images.githubusercontent.com/16019289/104584332-b649b680-5662-11eb-86d1-ff4d17471fa0.png)

As I can't reproduce your issue, I will close your issue. 

Please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by sebastian-marinescu** [comment]
Like I said in the beginning, this bug is irregular. 
Meaning, that there are some orders where editing/adding shipping works flawlessly, but others where I have this issue. 

I made sure the carriers are available for the country. Actually only one country allowed. 

Any tips on how one would debug this are appreciated. 
Setting the shop into dev_mode doesn't give me a stacktrace of that error.

**Comment by ubergenki** [comment]
@sebastian-marinescu I'm having the exact same issue with my shop right now. Did you ever find a solution to this problem?
