### ISSUE TITLE
Gift-wrapping line is displayed in order confirmation emails even if the gift option is disabled

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#22825]
### Describe the bug

I disabled the gift option from our shop settings because we don't provide this service, but emails still displays the `Gift-wrapping` line in the summary which is confusing.

### The expected behavior
Emails template should be updated to hide this line if the option is disabled (or if the value of this line is 0):
https://github.com/PrestaShop/PrestaShop/search?l=Twig&q=Gift-wrapping

### Steps to reproduce

1. **BO** > **CONFIGURE** > **Shop Parameters** > **Order Settings**
2. Scroll down to **Gift options** block
3. Disable the **Offer gift wrapping** option 
4. Save
5. FO > create an order
6. Open the **Order Confirmation** mail > See error

![image](https://user-images.githubusercontent.com/23308427/163824357-a6eb9e4e-a348-47c0-9cf6-4e4f43567bab.png)

### Specs
When the option Offer gift wrapping is disabled on the Order Settings > Order settings page, the Gift-wrapping line in order_conf template is hidden.

### Additional infos
- PS version: 1.7.8.5
- PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Seb33300 ,
Thanks for the suggestion.
Please stay tuned !

**Comment by florine2623** [comment]
Hi @PrestaShop/product-team ,

What do you think about @Seb33300 's idea on the order email templates ? (order_conf & new_order)

Thanks!

**Comment by MatShir** [comment]
I was able to reproduce the issue with PrestaShop version 1.7.7.
I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please don't hesitate to propose a Pull Request. We will be happy to review your contribution.
Thank you!

**Comment by ghost** [comment]
Hi @MatShir,

It's possible to fix this issue, but if a merchant enable or disable Gift Wrapping he need to re-generate template e-mail. 

I don't know if it's a good idea ? 

You can test with ; https://github.com/PrestaShop/PrestaShop/pull/24331

**Comment by Seb33300** [comment]
Is it not possible to regenerate automatically this specific email template when enabling / disabling Gift Wrapping feature?

**Comment by ghost** [comment]
Hi @Seb33300 ,

If a merchant made modification; the template is erase ... so i need PM feedback

**Comment by kpodemski** [comment]
Hey @okom3pom 

Do you want to continue your work with this Issue?

**Comment by marsaldev** [comment]
I'm on it 👍🏻
