### ISSUE TITLE
Upgrading from 1.7.7.0 to 1.7.7.1, require(/var/www/html/vendor/composer/platform_check.php) failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#22839]
During update of stock prestashop 1.7.7.0 to 1.7.7.1 i have lot of these warnings.
Dunno if I should bother, but these warning exists so I post this as an issue.

Built with PHP 7.4 alpine 3.12 docker image (not prestashop one)

**Comment by ProteanCode** [comment]
Aaaaaaaaaaaaaaaaaaand I do have PHP_WARNING after the update

Warning: require(/var/www/html/vendor/composer/platform_check.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 25
Call Stack
#	Time	Memory	Function	Location
1	0.0001	413032	{main}( )	.../index.php:0
2	0.0001	415944	require( '/var/www/html/config/config.inc.php' )	.../index.php:40
3	0.0002	421128	require_once( '/var/www/html/config/autoload.php' )	.../config.inc.php:35
4	0.0002	421368	require_once( '/var/www/html/vendor/autoload.php' )	.../autoload.php:26
5	0.0003	422024	ComposerAutoloaderInit5be19a0f132450c4cc323315cc885ffc::getLoader( )	.../autoload.php:7

**Comment by ProteanCode** [comment]
Ok. Thanks to my git repository I can see that these files were updated:
* LICENSE
* composer.lock
* vendor/autoload.php

Why on the earth upgrading prestashop (even the stock version) never goes fluent

**Comment by ProteanCode** [comment]
https://php.watch/articles/composer-platform-check

I have Composer version 2.0.8 2020-12-03 17:20:38 installed on my server in my /usr/local/bin

I guess this is a problem for prestashop. Does it use a some composer phar library running as version 1.0?

**Comment by florine2623** [comment]
Hello @ProteanCode ,

PHP 7.4 is not compatible with PrestaShop 1.7.7.1.
Please check the server config requirements here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ 

Please revert changes and do it again with PHP 7.3.

Thanks
