### ISSUE TITLE
Contact form: hide subject/contact if there is only one

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#22834]
#### Is your feature request related to a problem?

On the contact form, I only have one contact, the field brings no added value.

#### Describe the solution you'd like

Hide the field is there is only one contact.

#### Alternatives you've considered

Have an option to show / hide the field.

#### Additional context

PrestaShop 1.7.7.0

**Comment by florine2623** [comment]
Hello @yannicka ,
Please stay tuned as the product team will decide on that matter.
Thanks!

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,

@yannicka would like to have this field hidden on the contact form when only one contact exists :
![Capture d’écran 2021-01-14 à 17 21 25](https://user-images.githubusercontent.com/16019289/104618507-16ede900-568d-11eb-9f03-6c613be8fb0e.png)
What do you think ?

**Comment by LouiseBonnard** [comment]
Hi @yannicka, thanks for your improvement idea! If you have only one contact set in Shop Parameters > Contact, then the visitor/customer should have no other selecting option than the one you configured in the BO. Not two like in the screenshot.

As for disabling this field in the FO when only one contact is available for the visitors/customers, I got the idea but this feature actually does not work without this field. For example: delete all contacts in the BO and try to use the contact form = it's impossible! Also, I see it as an element of reassurance for the visitors/customers to picture whom they are writing to.

**Comment by yannicka** [comment]
The screenshot is not mine, I have the same rendering but with a single choice.

**Comment by LouiseBonnard** [comment]
Right, thanks for the reply, @yannicka! For the reasons previously evoked, this idea does not fit in with the PrestaShop context nor the user experience we want for the FO, therefore I close this issue and set it as _No change required_. :-)

**Comment by yannicka** [comment]
Would it be possible to add a configuration to do that?
