### ISSUE TITLE
Missing VAT number in Order view

### ISSUE THREAD

**Issue by mateusz-szafraniec** [PrestaShop/PrestaShop#22830]
#### Describe the bug

In new version - 1.7.7.1 VAT number in OrderPreview is not dispalyed.

#### Expected behavior

There should be a VAT number in Invoicing Address

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on 'Order detail (loupe with + sign)'
3. See  VAT number is missing

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @mateusz-szafraniec ,

DO you have a screenshot of the VAT not displaying ?
Thanks!

**Comment by mateusz-szafraniec** [comment]
Sure,
In this example VAT no is 12345678
![Zrzut ekranu 2021-01-14 141710](https://user-images.githubusercontent.com/6404022/104595970-9cfd3600-5673-11eb-92b9-27fec92848b3.png)
![Zrzut ekranu 2021-01-14 141736](https://user-images.githubusercontent.com/6404022/104595973-9d95cc80-5673-11eb-95d4-d3781c691171.png)

**Comment by kpodemski** [comment]
It seems like VAT is missing on order view page, not in order preview?

**Comment by mateusz-szafraniec** [comment]
> It seems like VAT is missing on order view page, not in order preview?

Yes, correct

**Comment by kpodemski** [comment]
Ok, you're right. I'll take on this. 

cc @florine2623 @khouloudbelguith @hibatallahAouadni 

I suggest to add this to 1.7.7.2 as it's quite important and it's regression from 1.7.6

**Comment by florine2623** [comment]
Thanks @kpodemski , I'll add this to the debug roadmap !

**Comment by Progi1984** [comment]
Fixed by #22841
