### ISSUE TITLE
Missing field 'price' in google search Prestashop 1.7.7.x

### ISSUE THREAD

**Issue by KrisDV-GH** [PrestaShop/PrestaShop#22832]
Since the upgrade to prestashop version 1.7.7.x using default theme Google search reported missing field 'price'

This code in product-prices.tpl returns an empty value for the content on the product page;

      <div class="current-price">
          <span itemprop="price" content="{$product.rounded_display_price}">{$product.price}</span>

  =>

      <div class="current-price">
          <span itemprop="price" content="">€ 14,95</span>

                  </div>

If the code gets updated to;

        <div class="current-price">
          <span itemprop="price" content="{$product.price_amount}">{$product.price}</span>

the return is correct

      <div class="current-price">
          <span itemprop="price" content="14.95">€ 14,95</span>

                  </div>

**Comment by florine2623** [comment]
Hello @KrisDV-GH ,
Could you send a screenshot of the issue on the shop ?
In my case, prices are displayed in product page.
Thanks

**Comment by KrisDV-GH** [comment]
Correct, prices are properly displayed in the shop but in the page source the value for content is empty => ("")

**Comment by florine2623** [comment]
OK, do you have the steps so I can reproduce the issue ?

**Comment by KrisDV-GH** [comment]
Steps to reproduce the issue are, open any prestashop demo using 1.7.7.x and open a product page, right click on blank space on the page and view page source. The source will contain below code;

<div class="current-price">
      <span itemprop="price" content="">€ 14,95</span>

              </div>

Note that content="" has no value inside, the corrct value would be content="14.95"

**Comment by hibatallahAouadni** [comment]
Hello @KrisDV-GH 

Could you please check these issues cause it seems similar to yours #22416 & #22636
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @KrisDV-GH 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10206. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #10206
