### ISSUE TITLE
VAT number in OrderPreview is missing

### ISSUE THREAD

**Issue by mateusz-szafraniec** [PrestaShop/PrestaShop#22831]
#### Describe the bug

In new version - 1.7.7.1 VAT number in OrderPreview is not dispalyed.

#### Expected behavior

There should be a VAT number in Invoicing Address

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on 'Order detail (loupe with + sign)'
3. See  VAT number is missing

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/

**Comment by florine2623** [comment]
Duplicate of #22830
