### ISSUE TITLE
Hooks before and after Grid table

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#22848]
#### Is your feature request related to a problem?

Avoid overrides.

#### Describe the solution you'd like

For developers. I want to be able to add dynamic content in selected places.

![image](https://user-images.githubusercontent.com/2137763/104723239-42291480-572f-11eb-9557-f5461314263d.png)

#### Alternatives you've considered

- overrides, but you need to maintain it from version to version
- js inject 🤮 

#### Additional context

Flexibility 🚀 

What about?

`{{ renderhook('displayAdminGridTableBefore', { 'grid': grid }) }}`
`{{ renderhook('displayAdminGridTableAfter', { 'grid': grid }) }}`

cc @PrestaShop/prestashop-maintainers

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers & @PrestaShop/product-team 

@kpodemski is suggesting adding new hooks, what do you think ?

**Comment by PululuK** [comment]
Nice idea 💡 
Thanks @kpodemski 
Maybe add controller name in hook params ?

**Comment by PierreRambaud** [comment]
@MatShir adds the To Do label, so maintaners have nothing to do :sweat_smile:
