### ISSUE TITLE
Problem with faceted search module, no appear the second image product

### ISSUE THREAD

**Issue by Marta99** [PrestaShop/PrestaShop#22846]
#### Describe the bug

I've implemented an overmouse to see a second product image. In the main menu works correctly, but in the categories there is a problem when the faceted search is active, so with the overmouse the second image is not shown. 
When I disable the module, it works correctly.

#### Expected behavior

With the faceted search module active i want to see the second image when the mouse is over the product image.

#### Steps to Reproduce

1. Go to "http://www.printerchef.com"
2. Put the mouse over any product image on main menu (See how works correctly)
3. Go to "https://printerchef.com/16-camiseta-manga-corta-unisex"
4. Put the mouse over any product image
5. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.1.33

**Comment by florine2623** [comment]
Hello @Marta99 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
