### ISSUE TITLE
I want to have class or data-attribute with identifier value in Grid table row 

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#22847]
#### Is your feature request related to a problem?

It's addition for module developers.

#### Describe the solution you'd like

`data-identifier="foo"` or `class="identifier_foo"`

![image](https://user-images.githubusercontent.com/2137763/104718570-5ec34d80-572b-11eb-8e06-4ea8fc97f491.png)
 
#### Alternatives you've considered

n/a

#### Additional context

I'd like to trigger some JS actions on specific record in the table.

cc @PrestaShop/prestashop-maintainers  what do you guys think?

I think I could add it directly into `src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig`, check for `column.type is 'identifier'`?

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team & @PrestaShop/prestashop-core-developers ,

What do you think about @kpodemski 's idea ?
Thanks!

**Comment by PierreRambaud** [comment]
If you want to retrieve the `tr` element based on an identifier you can use js to get the closest parent :thinking:

**Comment by kpodemski** [comment]
@PierreRambaud we would need to get all rows where `td` **content** is equal to what we're looking for, not sure if that's a best solution, also it's quite easy change so maybe I'll just create PR? 😅

**Comment by PierreRambaud** [comment]
Why not if this is something you really need :sweat_smile: 

But if this is an identifier you want to pass inside the HTML element, use `data-identifier=MY_VALUE` which is more logic than creating a useless class.

**Comment by kpodemski** [comment]
@PrestaShop/qa-team this has been done in #24952

We can close this issue.
