### ISSUE TITLE
Tests must not rely on hardcoded "test_" database prefix

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#22840]
#### Describe the bug

Tests must not rely on hardcoded "test_" database prefix. In some enviroments, even locally/for testing, database name can not be choosen by developer and thus any modification like adding a prefix is not possible.

#### Expected behavior

Configured database name is used 1:1.

#### Steps to reproduce
Dockerfile to replicate:
```
FROM atk4/image:7.4

RUN git clone https://github.com/PrestaShop/PrestaShop.git
WORKDIR PrestaShop
RUN git reset --hard 0f079f07693fcb2eb192c5fe31ad3aaafdcccff4
RUN composer install

ENV CI_MYSQL_HOST="REPLACE_ME"
ENV CI_MYSQL_PORT="3306"
ENV CI_MYSQL_DBNAME="REPLACE_ME"
ENV CI_MYSQL_USER="REPLACE_ME"
ENV CI_MYSQL_PASSWORD="REPLACE_ME"

RUN cp .github/workflows/phpunit/parameters.yml app/config/parameters.yml
RUN sed -E -i 's~(database_host: ).*~\1'"$CI_MYSQL_HOST"'~' app/config/parameters.yml
RUN sed -E -i 's~(database_port: ).*~\1'"$CI_MYSQL_PORT"'~' app/config/parameters.yml
RUN sed -E -i 's~(database_name: ).*~\1'"$CI_MYSQL_DBNAME"'~' app/config/parameters.yml
RUN sed -E -i 's~(database_user: ).*~\1'"$CI_MYSQL_USER"'~' app/config/parameters.yml
RUN sed -E -i 's~(database_password: ).*~\1'"$CI_MYSQL_PASSWORD"'~' app/config/parameters.yml
RUN sed -E -i 's~(dbname: ")test_(%database_name%")~\1\2~' app/config/config_test.yml
RUN sed -E -i "s~(define\('_DB_NAME_', )'test_' *\. *~\1~" config/bootstrap.php
RUN sed -E -i "s~(define\('_DB_SERVER_', )[^()]+~\1\$configuration['parameters']['database_host']~" tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
RUN sed -E -i "s~(define\('_DB_NAME_', )'test_' *\. *~\1~" tests-legacy/PrestaShopBundle/Controller/ControllerTest.php

ENV SYMFONY_DEPRECATIONS_HELPER=disabled

# delete all tables
RUN mysql --host=$CI_MYSQL_HOST --user=$CI_MYSQL_USER --password=$CI_MYSQL_PASSWORD --database=$CI_MYSQL_DBNAME -e 'show tables' | while read p; do mysql --host=$CI_MYSQL_HOST --user=$CI_MYSQL_USER --password=$CI_MYSQL_PASSWORD --database=$CI_MYSQL_DBNAME -e 'drop table if exists `'"$p"'`' ; done

# install
RUN php install-dev/index_cli.php --language=en --country=fr --domain=localhost --db_server="$CI_MYSQL_HOST:$CI_MYSQL_PORT" --db_user="$CI_MYSQL_USER" --db_password="$CI_MYSQL_PASSWORD" --db_name="$CI_MYSQL_DBNAME" --db_create=1 --name=prestashop.unit.test --email=demo@prestashop.com --password=prestashop_demo


RUN php ./tests-legacy/create-test-db.php
```
#### Screenshots
I am getting the following error:
```
Fatal error: Uncaught PrestaShopException: Property Profile->name is empty. in /PrestaShop/classes/ObjectModel.php on line 1076

PrestaShopException: Property Profile->name is empty. in /PrestaShop/classes/ObjectModel.php on line 1076

Call Stack:
    8.2633  107998840   1. Symfony\Component\Debug\ErrorHandler->handleException($exception = class PrestaShopException { protected $message = 'Property Profile->name is empty.'; private ${Exception}string = ''; protected $code = 0; protected $file = '/PrestaShop/classes/ObjectModel.php'; protected $line = 1076; private ${Exception}trace = [0 => [...], 1 => [...], 2 => [...], 3 => [...], 4 => [...], 5 => [...], 6 => [...], 7 => [...], 8 => [...], 9 => [...], 10 => [...]]; private ${Exception}previous = NULL; public $xdebug_message = '\nPrestaShopException: Property Profile->name is empty. in /PrestaShop/classes/ObjectModel.php on line 1076\n\nCall Stack:\n    0.0001     391288   1. {main}() /PrestaShop/tests-legacy/create-test-db.php:0\n    0.0003     407832   2. LegacyTests\\PrestaShopBundle\\Utils\\DatabaseCreator::createTestDB() /PrestaShop/tests-legacy/create-test-db.php:6\n    8.1836  107338552   3. PrestaShopBundle\\Install\\Install->populateDatabase($entity = ???) /PrestaShop/tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.ph' }, $error = ???) /PrestaShop/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0

The command '/bin/sh -c php ./tests-legacy/create-test-db.php' returned a non-zero code: 255
```

#### Additional information

- PS version: develop
- PHP version: 7.4

see/related with https://github.com/PrestaShop/PrestaShop/pull/22823

**Comment by florine2623** [comment]
Hello @mvorisek ,
What are the steps to reproduce your issue ?
Thanks!

**Comment by mvorisek** [comment]
> What are the steps to reproduce your issue ?

Create a user and grant permissions to one specific database name. Currently, PrestaShop prefix this database name which leads to permission issue (as the new database name is not allowed to be accessed by that user).

**Comment by florine2623** [comment]
After doing "Create a user and grant permissions to one specific database name."
What are the next steps ?

**Comment by mvorisek** [comment]
@florine2623 set that database name to config - nothing more :)

**Comment by florine2623** [comment]
Ok, so where is the issue ?
Sorry, i'm not sure I understand.
How do you implement the tests ?

**Comment by mvorisek** [comment]
@florine2623 the tests currently modifies the database name which is not ok (as different database name can not be accessible in general, even impossible to grant in some enviroments with generated database names)

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

Let's define the steps to reproduce the issue:

1. Create a user -> customer or employee or ... ?
2. grant permissions to one specific database name -> how?
3. set that database name to config -> you mean that I have to change the DB name in config.yml

is that so? If so, could you please provide the command lines that I need to execute.

Thanks!

**Comment by mvorisek** [comment]
@hibatallahAouadni sure, see https://github.com/PrestaShop/PrestaShop/pull/22823#issuecomment-766252249 . Creating the user is simple - create one user named UUU and database named DDD. Then grant all priviledges for DDD database to user UUU.

**Comment by hibatallahAouadni** [comment]
@mvorisek thanks for the infos :wink: 
Your PHP version is 7.4? just to make sure :sweat_smile:

**Comment by mvorisek** [comment]
yes, 7.4

**Comment by hibatallahAouadni** [comment]
Thanks @mvorisek I will try to reproduce it.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could anyone try to reproduce the issue.
Thanks in advance!

**Comment by mvorisek** [comment]
@hibatallahAouadni my PR at the latest/current state already reproduces it in CI: https://github.com/PrestaShop/PrestaShop/pull/22823 , see https://github.com/PrestaShop/PrestaShop/actions/runs/506442829 `PHPUnit Tests (With DB) (x.y)` job output.

**Comment by PierreRambaud** [comment]
I'm still convinced we will not accept your pull request until the Symfony migration is ended or you properly split the database settings per environment.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Due to inactivity of this issue (it's been over 9 months) I'm closing this issue.

Thanks for your understanding pray

**Comment by mvorisek** [comment]
@hibatallahAouadni this is valid issue
