### ISSUE TITLE
1.7.7.0 redisplay cart at login - lastNoneOrderedCart function

### ISSUE THREAD

**Issue by pytelCZ** [PrestaShop/PrestaShop#22850]
After enable redisplay cart at login, it doesn't work for me.

I was digging at it and i think, it can't work, because in function lastNoneOrderedCart  in SQL there is condition c.`id_guest` != 0

How can be the id_guest != 0 if customer exists and id_customer is filled? Don't have any one record in ps_cart table, where id_customer !=0 and id_guest !=0

It doesn't make sense, or am I missing something?

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
