### ISSUE TITLE
Checkout not worcking after upgrade (Uncaught TypeError)

### ISSUE THREAD

**Issue by jean-io** [PrestaShop/PrestaShop#22857]
Hi

After upgrading from 1.7.6 to 1.7.7 I got a HTTP 500 error on checkout. In logs I get the following error:

```
[Fri Jan 15 10:36:16.980182 2021] [php7:error] [pid 41] [client XXX] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Payment\\PaymentOption::convertLegacyOption() must be of the type array, string given in /var/www/html/src/Core/Payment/PaymentOption.php:337\nStack trace:\n#0 [internal function]: PrestaShop\\PrestaShop\\Core\\Payment\\PaymentOption::convertLegacyOption('')\n#1 /var/www/html/classes/checkout/PaymentOptionsFinder.php(46): array_map(Array, Array)\n#2 /var/www/html/classes/checkout/PaymentOptionsFinder.php(82): PaymentOptionsFinderCore->find()\n#3 /var/www/html/classes/checkout/CheckoutPaymentStep.php(87): PaymentOptionsFinderCore->present(false)\n#4 /var/www/html/src/Core/Foundation/Templating/RenderableProxy.php(52): CheckoutPaymentStepCore->render(Array)\n#5 /var/www/html/config/smartyfront.config.inc.php(98): PrestaShop\\PrestaShop\\Core\\Foundation\\Templating\\RenderableProxy->render(Array)\n#6 /var/www/html/classes/Smarty/SmartyLazyRegister.php(83): smartyRender(Array, Object(Smarty_Internal_Template))\n#7 /var/www/html/var/cache/prod/smarty/compile/d5/e1/ in /var/www/html/src/Core/Payment/PaymentOption.php on line 337, referer: XXX /panier?action=show
```

The strange thing is that even if the server return a 500 error, it still sends the whole page but there is no space for payment information so clients cannot proceed to checkout:
![image](https://user-images.githubusercontent.com/4070933/104749854-95ad5980-5753-11eb-87b9-0d4f1a49a4d8.png)

I tried to empty cache, to re-install payment module, to search google... nothing helped.

Expected behavior: not having the check out page return a 500 error.

PHP version: 7.3.24

I have to do a roll-back on this upgrade since the shop is not working because of this issue 😢

**Comment by hibatallahAouadni** [comment]
Hello @jean-io 

Could you please specify which version you updated to, 1.7.7.0 or 1.7.7.1? 

Did you encounter any warnings or errors while upgrading? And which 1-click upgrade module version did you use? 

Please check and feedback.
Thanks!

**Comment by jean-io** [comment]
Hi @hibatallahAouadni 

I upgraded to 1.7.7.1. I did it manually, to do so I used this documentation: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

They were some warnings when I upgraded the database but nothing looked critical, I did not keep these messages.

Thank for the help 🍺

**Comment by hibatallahAouadni** [comment]
Hello @jean-io 

Could you please check **BO>IMPROVE>Modules>Module Manager** all your payment modules if they need to be upgraded, then upgrade it and check if the issue still persist. 

If so, please disable all your payment modules but the default ones (Payment by Bank Wire, Payment on Delivery, ...) and then check if the problem still persist. 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @jean-io ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
