### ISSUE TITLE
Search by ISBN

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#22869]
#### Describe the bug

It looks like the search form is not able to find product when searching by ISBN.

We are creating an online shop to sell books and entering an existing ISBN number in the search form return no result.

#### Expected behavior

When searching for products, if you know the ISBN and enter it in the search bar, you can find the product.

#### Steps to Reproduce

1. Create a new product with an ISBN reference.
2. Reindex search from Back Office. ISBN is now indexed.
3. GO on FO, input the chosen isbn in the search box
4. The product is not found.

Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/23006

#### Additional information

* PrestaShop version: 1.7.7

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
Hi @hibatallahAouadni since user @Seb33300 opened PR https://github.com/PrestaShop/PrestaShop/pull/23006 related to issue, I completed the template for him 😉  can you please re-evaluate this github issue?

**Comment by hibatallahAouadni** [comment]
@matks yep with pleasure :wink:

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

I reproduced your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/10WPY3_-0PDmp2miTch1caikDa-PJ5mAC/view

I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR :wink: 

**PS:** please next time when you open a new issue **respect the provided template to submit a complete bug report**.

Thank you
