### ISSUE TITLE
i set price show only for user registred group but show on google images

### ISSUE THREAD

**Issue by rb101010** [PrestaShop/PrestaShop#22860]
#### Describe the bug

hi, i have set customer group in way that only registred user can view price, and this works fine on site, but i noted that when i search product on google images it show also price...

how i can fix this ?

i have ps  1.6  (at this moment i cant update to 1.7) 

thanks for all support
#### Expected behavior

hide price in google images search

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.6
![Cattura](https://user-images.githubusercontent.com/77512116/104777399-dfaa3580-577b-11eb-8fc8-4d1625f629d3.JPG)

* PHP version: N/A

**Comment by SimonGrn** [comment]
Hello,

PrestaShop 1.6 is no longer supported.

Thank you for your understanding.

**Comment by rb101010** [comment]
ok, thanks for your reply!
there is a section for ps 1.6 with old problem where i can search if there are some similar to my problem?

> Hello,
> 
> PrestaShop 1.6 is no longer supported.
> 
> Thank you for your understanding.
