### ISSUE TITLE
Move structured data to a separate file

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22867]
#### Is your feature request related to a problem?

Currently, all microdatas are managed in their respective templates of the markup they aim to enrich, this leads to several things :
- It's harder to maintain, because there are a lot of files to inspect in order to change these
- It's harder to override from a template, because the template needs to override tons of tpl files, and it leads to maintainability problems because when we update the classic theme, you need to update several templates only because of microdatas
- It's not respecting seperation of concern as you've a mix between "Shown markup" and "SEO Microdatas" which make templates harder to read and understand

#### Describe the solution you'd like

Having one file, containing every microdatas of the classic theme, that you could override on your template in order to personnalize it way more, fix theme-sided changes.

Example :
https://github.com/prestarocket-agence/classic-rocket/blob/master/templates/_partials/microdata-jsonld.tpl

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, the Developer Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers  , like the idea to have clearer code that's easy to edit and debug, but if we apply what @Hlavtox suggest will there be a BC?

**Comment by matks** [comment]
ping @NeOMakinG

**Comment by Hlavtox** [comment]
@NeOMakinG @matks Should I close this? :D https://github.com/PrestaShop/PrestaShop/issues/23046

**Comment by NeOMakinG** [comment]
Oh damn, I didn't find this one !

**Comment by khouloudbelguith** [comment]
Hi!

As commented here: https://github.com/PrestaShop/PrestaShop/pull/23042#issuecomment-769758614 fixed by https://github.com/PrestaShop/PrestaShop/pull/23055.
Don't close this issue until this PR: https://github.com/PrestaShop/PrestaShop/pull/23042 is merged.

Thank you!

**Comment by marionf** [comment]
This issue seems to be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15783 ?

**Comment by hibatallahAouadni** [comment]
@marionf maybe related but I don't think it's a duplicate :wink:

**Comment by matks** [comment]
(github closed the issue upon merge of https://github.com/PrestaShop/PrestaShop/pull/23094, I reopen it)
