### ISSUE TITLE
Carrier limit do not work

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#22877]
#### Describe the bug

When using the depth, height and width limits on the carriers they do not work as expected.
If any value is "ok" the carrier will show up.

#### Expected behavior

If one of the values is exceeding the carrier limit, the carrier should not show up in the checkout.

#### Steps to Reproduce

1. Go to product, set values height, depth and width to 1, 1 and 5 and save
2. Go to carriers, activate the light carrier.
3. In front office, add product to the cart and go to checkout all the way to the carrier step.
4. Light carrier should show up.
5. Go back to editing the light carrier in BO, set height, depth and width max values to 20, 20 and 2 and save.
6. Reload the checkout, light carrier still shows up, even if the product in the cart is exceeding the maximum width of the carrier.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by Prestaworks** [comment]
The cause seems to be

rsort($carrier_sizes, SORT_NUMERIC);
rsort($product_sizes, SORT_NUMERIC);

on lines 1599 and 1600 i carrier class.
since the arrays are used to compare the values
if (($carrier_sizes[0] > 0 && $carrier_sizes[0] < $product_sizes[0])
but the keys are sorted so the order is wrong.

I think maybe that entire check should be rewritten to not use an array? but rather the product and carrier values? it would make the code easier to read?

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

I managed to reproduce your issue with PS1.7.6.7 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1K3_bkTTC7c8IPPO-RP0Uqry5uZf9jtSO/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Prestaworks** [comment]
@hibatallahAouadni I added a PR to fix the issue

**Comment by hibatallahAouadni** [comment]
@Prestaworks Thanks :rocket:
