### ISSUE TITLE
Form problem with PSDGDPR module

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#22880]
#### Describe the bug

This bug is related with modules `psgdpr` and `ps_emailalerts`, but I think that the solution should be taken in PS template, that's why I open the issue here.

#### Steps to Reproduce

1. Install `psgdpr` module

2. Install `ps_emailalerts` and enable `Product availability` option: 
![image](https://user-images.githubusercontent.com/15104724/104941820-d9060300-59b3-11eb-9d9a-f0d2a24325d8.png)

3. Set a product without stock and deny orders:
![image](https://user-images.githubusercontent.com/15104724/104944696-ddccb600-59b7-11eb-9a02-0538a823b7be.png)

4. Open the product in the store. `Add to cart` button is disabled:
![image](https://user-images.githubusercontent.com/15104724/104943229-b5dc5300-59b5-11eb-92dc-13fad5a07bb9.png)

5. When you enable GDPR checkbox, `Add to cart` button is enabled.
![image](https://user-images.githubusercontent.com/15104724/104943280-d0aec780-59b5-11eb-9d26-e3e8f2a27187.png)

6. `Add to cart` button should not modify it state depending on the GDPR checkbox value.

**Why does this happen?**

Template `\modules\ps_emailalerts\views\templates\hook\product.tpl` is a form:
![image](https://user-images.githubusercontent.com/15104724/104943448-14093600-59b6-11eb-9072-09c975bb619b.png)

But when it's displayed in the frontoffice, the `<form>` tag is stripped:
![image](https://user-images.githubusercontent.com/15104724/104943654-5f234900-59b6-11eb-952e-9cdf64d1d5a7.png)

Because it's already appended in another form:
![image](https://user-images.githubusercontent.com/15104724/104943673-66e2ed80-59b6-11eb-939a-ede72a962d34.png)

And it's not allowed a `form` inside a `form`.

On the other side. `psgdpr` module searches the closest form and disable/enable the submit button:
https://github.com/PrestaShopCorp/psgdpr/blob/3b5240b662962cd7d158bc7d438e2b730d7df97e/views/templates/hook/displayGDPRConsent.tpl#L40
It should disable/enable `Notify me when available` button, but there's not a `form`.

Although in this case PS doesn't allow you to add the product to the cart even if the button is enabled, this is just an example to reproduce the issue.
The main problem is with custom modules. 
For example if you display a block to subscribe to a newsletter, and you attach the GDPR checkbox, the `Add to cart` button is disabled unless you check the GDPR checkbox, which has no sense.

**Possible solutions:**

1. Move `displayProductAdditionalInfo` hook outside `form`:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-additional-info.tpl
https://github.com/PrestaShop/PrestaShop/blob/30b84c54dda4bce40d1a7b8cb04a8590d88e5ddc/themes/classic/templates/catalog/product.tpl#L127
2. Create a new hook and move `ps_emailalerts` to this new hook.

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

Thanks for the detailed issue :wink:  I managed to reproduce the issue with:

- `PS`: 1.7.7.1 
- `ps_emailalerts`: 2.2.1
- `psgdpr`: 1.2.1

See the attached screen record below:

https://drive.google.com/file/d/1wVoXWA-Q97EfQeKQqrevlrbbVVdwV8nw/view

Fortunally, if we try add the product to the cart an error is displayed. So, the issue is that when we checked the `psgdpr` option, the button **Add to cart** become enbled :sweat: 

I’ll add this to the debug backlog so that it’s fixed.
I see that you have already explained how to fix the issue on your end, so please do send us a pull request!

Thanks!

**Comment by idnovate** [comment]
`Fortunally, if we try add the product to the cart an error is displayed. So, the issue is that when we checked the psgdpr option, the button Add to cart become enbled sweat`

Although in this case PS doesn't allow you to add the product to the cart even if the button is enabled, this is just an example to reproduce the issue.
The main problem is with custom modules.
For example if you display a block to subscribe to a newsletter, and you attach the GDPR checkbox, the Add to cart button is disabled unless you check the GDPR checkbox, which has no sense.
**We have developed a module and `Add to cart` button should be enabled always. Unfortunately it isn't because GDPR module disabled it.**

`I see that you have already explained how to fix the issue on your end, so please do send us a pull request!`
Could you ping someone to know which would be the best solution?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could someone please help him to choose the best solution and create his PR :wink: 

Thanks in advance!

**Comment by davidglezz** [comment]
More information: https://github.com/PrestaShop/PrestaShop/issues/23749

**Comment by idnovate** [comment]
> Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could someone please help him to choose the best solution and create his PR 😉
> 
> Thanks in advance!

Waiting for this :)

**Comment by kpodemski** [comment]
Hey @idnovate 

you can check my solution here: https://github.com/PrestaShop/ps_emailalerts/pull/86

**Comment by idnovate** [comment]
> Hey @idnovate
> 
> you can check my solution here: [PrestaShop/ps_emailalerts#86](https://github.com/PrestaShop/ps_emailalerts/pull/86)

But I think it doesn't solve the main problem: form inside a form

**Comment by kpodemski** [comment]
@idnovate hmm, I think it does? I just removed `form` as we don't need it in `ps_emailalerts`, we can even get rid off those hidden inputs and replace them with `data-X`

**Comment by idnovate** [comment]
> @idnovate hmm, I think it does? I just removed `form` as we don't need it in `ps_emailalerts`, we can even get rid off those hidden inputs and replace them with `data-X`

I didn't see it :man_facepalming:
I'll check it.

**Comment by kpodemski** [comment]
Hey @idnovate 

could you test my modifications?

**Comment by idnovate** [comment]
> Hey @idnovate
> 
> could you test my modifications?

Yes! It fixes the issue :partying_face::partying_face:

**Comment by idnovate** [comment]
But please note that I reported this problem because I had a problem with another module which also uses a form, although I used module `ps_emailalerts` to reproduce it, because it's a core module. 

I think that this should be considered anyway:


<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Possible solutions:</strong></p><ol style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Move<span>&nbsp;</span><code style="box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-markdown-code-bg); border-radius: 6px;">displayProductAdditionalInfo</code><span>&nbsp;</span>hook outside<span>&nbsp;</span><code style="box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-markdown-code-bg); border-radius: 6px;">form</code>:<br style="box-sizing: border-box;"><a href="https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-additional-info.tpl" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;">https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-additional-info.tpl</a><br style="box-sizing: border-box;"><div class="border rounded-1 my-2" style="box-sizing: border-box; border: 1px solid var(--color-border-primary) !important; border-radius: 6px !important; margin-top: 8px !important; margin-bottom: 8px !important;"><div class="f6 px-3 py-2 lh-condensed border-bottom color-bg-secondary" style="box-sizing: border-box; border-bottom: 1px solid var(--color-border-primary) !important; background-color: var(--color-bg-secondary) !important; padding: 8px 16px !important; font-size: 12px !important; line-height: 1.25 !important;"><p class="mb-0 text-bold" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; font-weight: 600 !important;"><a href="https://github.com/PrestaShop/PrestaShop/blob/30b84c54dda4bce40d1a7b8cb04a8590d88e5ddc/themes/classic/templates/catalog/product.tpl#L127" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;">PrestaShop/themes/classic/templates/catalog/product.tpl</a></p><p class="mb-0 color-text-tertiary" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: var(--color-text-tertiary) !important;">Line 127 in<span>&nbsp;</span><a data-pjax="true" class="commit-tease-sha" href="https://github.com/PrestaShop/PrestaShop/commit/30b84c54dda4bce40d1a7b8cb04a8590d88e5ddc" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-primary); text-decoration: none; display: inline-block; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 10.8px;">30b84c5</a></p></div><div itemprop="text" class="blob-wrapper blob-wrapper-embedded data" style="box-sizing: border-box; overflow: auto; max-height: 240px;"> {include file='catalog/_partials/product-additional-info.tpl'} </div></div></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Create a new hook and move<span>&nbsp;</span><code style="box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-markdown-code-bg); border-radius: 6px;">ps_emailalerts</code><span>&nbsp;</span>to this new hook.</li></ol>

**Comment by kpodemski** [comment]
@idnovate 

thanks, maybe dedicated hook after the form would be a good idea, though we need to remember that product card is refreshed after combination change, we need to have that in mind to not break anything working with combinations

I think it's an improvement or feature request than bug report so maybe I'll create new Issue

**Comment by kpodemski** [comment]
@idnovate take a look https://github.com/PrestaShop/PrestaShop/issues/24807
