### ISSUE TITLE
[BO] Default theme has no specific SCSS rules

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22885]
#### Is your feature request related to a problem?

Everything folders on the project has Stylelint enabled, while default theme is chaotic!

#### Describe the solution you'd like

Having default theme with stylelint, with at least important rules enabled

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks for your issue and your PR :rocket:
