### ISSUE TITLE
Cart rules are not removed from cart if they are disabled

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#22893]
#### Describe the bug

While you add a cart rule on your shop and add it into the cart, if you disable the cart rule (active column), the cart rule will remain available into the cart having added it previously.

#### Expected behavior

Cart rules validity need to check the state of the cart rule, I'm suppose.

#### Steps to Reproduce

1. Go to Cart Rules management
2. Add one (with or without code)
3. Add it to the cart
4. Disable (toggle the active) the cart rule
5. Refresh the cart
6. See it's still there

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by PrestaEdit** [comment]
I know that inside the CartRule validity method, we bypass this for somes reasons: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/CartRule.php#L682

But I'm not sure it's the right method, if you disable a cart rule, I think you are simply disable for all of furthers orders, isn't it ?

**Comment by hibatallahAouadni** [comment]
Hello @prestamodule 

Could you please check this issue #19393 I think it's similar to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @prestamodule ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
