### ISSUE TITLE
Order informations at top of View an Order BO page are not aligned correctly

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22891]
#### Describe the bug

Order informations at top of View an Order BO page are not aligned correctly (see screenshot) in `develop`. On 1.7.7.1 they are aligned correctly.

#### Expected behavior

Order informations at top of View an Order BO page should be aligned like in 1.7.7

#### Steps to Reproduce

1. Install 1.7.8
2. Open an Order in BO
3. See order informations at top of View an Order BO page

**Screenshots**

![Capture d’écran 2021-01-19 à 09 48 53](https://user-images.githubusercontent.com/3830050/105025635-e66fcb80-5a4d-11eb-9a6e-2b3ae3c9d976.png)

#### Additional information

* PrestaShop version: `develop` branch
* PHP version: 7.3.19

**Comment by hibatallahAouadni** [comment]
Thanks @matks for the issue :slightly_smiling_face: 
Ping @NeOMakinG could you please check it :wink:
