### ISSUE TITLE
Bad display on blockreassurance configuration page

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22892]
#### Describe the bug

Bad display on blockreassurance configuration page

#### Steps to Reproduce

1. Go to admin -> modules 
2. Search blockreassurance 
3. Click on configure 

**Screenshots**

<img width="1440" alt="Capture d’écran 2021-01-18 à 12 25 47" src="https://user-images.githubusercontent.com/3034677/105027862-93e3de80-5a50-11eb-9dd5-3b8b11380c4f.png">

#### Additional information

* PrestaShop version: 1.7.7, develop
* PHP version: 7.1

**Comment by NeOMakinG** [comment]
The module's css is loaded before the core one

**Comment by kpodemski** [comment]
PR for you to check @NeOMakinG :)

https://github.com/PrestaShop/blockreassurance/pull/209

**Comment by hibatallahAouadni** [comment]
_Origanlly posted by @amaury-hanser_

The fix might be done in both files:
- `PrestaShop/admin-dev/themes/default/scss/partials/_nav.scss`
- `PrestaShop/admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss`

Should I make a PR with a change in `scss` files only or also with the compiled files ?

---
Ping @NeOMakinG could you please answer @amaury-hanser question :pray:

**Comment by hibatallahAouadni** [comment]
PS: this issue occurs not only with blockreassurance module but with Metrics also.

**Comment by amaury-hanser** [comment]
> PS: this issue occurs not only with blockreassurance module but with Metrics also.

I would add that it occurs on every page where a module loads material-icons by itself. (Metrics, Marketing with Google, Facebook, Ps Accounts are some example)

**Comment by NeOMakinG** [comment]
> > PS: this issue occurs not only with blockreassurance module but with Metrics also.
> 
> I would add that it occurs on every page where a module loads material-icons by itself. (Metrics, Marketing with Google, Facebook, Ps Accounts are some example)

I didn't dive deep today, but before, I noticed that the CSS from this module was loaded before the core one, causing this issue, if you have a better solution than just loading the CSS after the core, don't hesitate to provide a PR so I can get a look at the fix implementation

**Comment by matks** [comment]
@NeOMakinG check https://github.com/PrestaShop/PrestaShop/pull/27813 😄
