### ISSUE TITLE
Price Ordering in Category Page

### ISSUE THREAD

**Issue by dtagkalos93** [PrestaShop/PrestaShop#22894]
#### Describe the bug

When i am trying to order the products list carousel category page by price and the price of producets is in sale then the ordering from "lowest to highest" is based on sale price but when i am put from "highest to lowest" then the ordering is based on initial price

#### Expected behavior

The ordering in products list carousel category by price from "highest to lowest" price should be made on the active price if it is in sale order by sale price otherwise with the initial price

#### Steps to Reproduce

1. Go to a category
2. Click on price highest to lowest
3. And check the price order

**Screenshots**

![εικόνα](https://user-images.githubusercontent.com/14951404/105044894-ec76a400-5a6f-11eb-8100-00e2beea7c20.png)

#### Additional information

* PrestaShop version: 1.7.70
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @dtagkalos93 

Could you please check this issue #22621 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @dtagkalos93 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
