### ISSUE TITLE
[RESPONSIVE - BO] - Advertising page needs to be redesigned

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#22896]
Epic: https://github.com/PrestaShop/PrestaShop/issues/22358 

[Link to Figma prototype](https://www.figma.com/proto/b2sVogt6tyvB5EIkVmTAdP/PrestaShop-Responsive?node-id=466%3A2370&scaling=min-zoom)

#### Describe the bug

This page has spacing issues and needs to be redesigned to be responsive.

#### Expected behavior

Advertising page being responsive.

**Screenshots**

Before
![Capture d’écran 2021-01-19 à 16 18 47](https://user-images.githubusercontent.com/54888056/105054225-074a1800-5a72-11eb-8238-8f312c0863a4.png)

After
![advertising](https://user-images.githubusercontent.com/54888056/105054303-221c8c80-5a72-11eb-8b61-3073371860cd.png)
![advertising floating button](https://user-images.githubusercontent.com/54888056/105054308-234db980-5a72-11eb-9b10-759073b8859d.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by matks** [comment]
@prestascott "PrestaShop Ads" is a module being installed by the API. It is not handled by us.
