### ISSUE TITLE
PhpEncryptionEngine class mcrypt error

### ISSUE THREAD

**Issue by md2158** [PrestaShop/PrestaShop#22901]
#### Describe the bug

I updated prestashop to 1.7.7.0 version and php to 7.2 version where mcrypt function deprecated. PhpEncryptionEngine class uses mcrypt for encryption and decryption and some modules using this class stoped working, In my case iqit wishlist module not working and don't know other conséquences yet

#### Expected behavior

Class have to edited to use openssl

**Screenshots**

![image](https://user-images.githubusercontent.com/13145310/105070619-9cf69f00-5a94-11eb-8fb1-adc5fe6dd7f4.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by matks** [comment]
Hi @merick2158 as you have said, mcrypt is deprecated in PHP. Modules must be updated to stop using it and rely on safe solutions instead. This is an update that need to be done by module developer of IQIT Wishlist module, not PrestaShop.

So I don't understand why you submit a bug report? 😅

**Comment by matks** [comment]
This is the bug tracker of the PrestaShop project, 3rd party modules are not in our scope (and we actually cannot modify 3rd party modules). You must contact the module developer

**Comment by md2158** [comment]
Well problem is not with modules. Module uses prestashop core php class PhpEncryptionEngine. And this class uses deprecated php function. I think this is a bug or not?

**Comment by HartLarsson** [comment]
> Well problem is not with modules. Module uses prestashop core php class PhpEncryptionEngine. And this class uses deprecated php function. I think this is a bug or not?

seem the Warehouse wishlist module.
There is a new version of warehouse 4.4.1 for PS 1.7.7.x, you can contact the theme designer for a feedback ad @matks already told.

**Comment by matks** [comment]
> Well problem is not with modules. Module uses prestashop core php class PhpEncryptionEngine. And this class uses deprecated php function. I think this is a bug or not?

Hi, are you mentioning `mcrypt_create_iv()` used in `randomCompat()` ?
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PhpEncryptionEngine.php#L135

I think it is not executed unless `openssl_random_pseudo_bytes()` fails 🤔  .

Do you have a reproductible usecase we can apply to see the issue? It can be a demo module 😊  .

**Comment by hibatallahAouadni** [comment]
Hello @merick2158 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: Thanks @matks & @HartLarsson for your quick replies :rocket: 

Thanks!

**Comment by md2158** [comment]
Hi @matks 
Here is used mcrypt:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PhpEncryptionLegacyEngine.php

**Comment by md2158** [comment]
Hi @hibatallahAouadni 
[https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/)
Here in documentation it's written new version of prestashop 1.7.7 is fully compatible with php version 7.3. But in core classes used deprecated php function that removed in php version 7.2. It's nothing to do with third-party modules. 

Here you can find that mcrypt function is removed in PHP 7.2.0.
[https://www.php.net/manual/en/intro.mcrypt.php](https://www.php.net/manual/en/intro.mcrypt.php)

**Comment by hibatallahAouadni** [comment]
what do you think @matks :confused:

**Comment by matks** [comment]
@merick2158 Look at

```
public static function resolveEngineToUse()
    {
        if (false === in_array(\Defuse\Crypto\Core::CIPHER_METHOD, openssl_get_cipher_methods())) {
            return self::LEGACY_ENGINE;
        }

        return self::ENGINE;
    }
```
Class PhpEncryptionLegacyEngine is only used when aes-256-ctr cipher algorithm is not available.

It seems to be a fallback mechanism. Maybe we can improve the documentation to make clear that `Your OpenSSL version must provide aes-256-ctr cipher algorithm`.

Notice: PS 1.7.7 is compatible with php7.1 to php7.3 so having code that is compatible only with php7.1 is not an issue. What however must be done is that such a code is never run in production if php version is not compatible, providing the right server settings are enabled.

**Comment by md2158** [comment]
Hi @matks 
My server OpenSSL version already provide aes-256-ctr cipher algorithm but still not running.
