### ISSUE TITLE
Emails sent from contact form module to office365 accounts do not get delivered

### ISSUE THREAD

**Issue by FreelanceComputing** [PrestaShop/PrestaShop#22907]
**Using contact form v4.3 with prestashop v1.7**. 
The module has been configured as follows

![image](https://user-images.githubusercontent.com/20488497/105114548-fc69a480-5abe-11eb-82af-b7ea7db39dad.png)

When the form is submitted, a copy of the email is successfully received by the Customer service and Webmaster email addresses. 
If the sender's email is not from an office365 domain, the sender also receives a copy of the email. I have tested this with gmail.com, outlook.com, mail.com etc.

![image](https://user-images.githubusercontent.com/20488497/105115842-7e5acd00-5ac1-11eb-8354-aeae98fa41a9.png)

If the sender's email is from an office365 domain e.g. .ac.uk domains, a copy of the email is neither received in the inbox nor spam eventhough the backoffice email log shows that this has been sent. (The ones highlighted in red were never received)

![image](https://user-images.githubusercontent.com/20488497/105115392-9c73fd80-5ac0-11eb-9e6d-fd286e7214f5.png)

When using the test email functionality, emails to office365 accounts are received successfully as shown below

![image](https://user-images.githubusercontent.com/20488497/105115554-ed83f180-5ac0-11eb-96eb-48ff6de81305.png)

**Comment by matks** [comment]
@FreelanceComputing thanks for the detailed feedback 😉 

If only office365 domain do not work we can guess office365 has an extra need compared to other mail providers :/ but I am not sure this can be solved on prestashop side.

For example I noticed that, with gmail, to use SMTP I had to enable a "password for applications only". Maybe there is a similar setting needed by Office365?

**Comment by Hlavtox** [comment]
@FreelanceComputing @matks Microsoft has a very strict rule regarding delivery quota of all new servers. If you have delivery problems to their mailboxes, you need to contact them. They will check it manually and raise the quota. I needed to do it on both hosting providers we used for our stores.

And yes, they just ditch the email completely, no spam folder, no message, the email is just lost. :-)

Also check your SPF, DKIM and DMARC records.

**Comment by Hlavtox** [comment]
@FreelanceComputing Make a support request here - https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

They will contact you

**Comment by hibatallahAouadni** [comment]
Hello @FreelanceComputing 

It seems your issue related to Microsoft mailbox as @matks and @Hlavtox mentioned above, and we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
So, please contact their support :wink: 

I'm closing this issue.

Thanks!
