### ISSUE TITLE
hook DisplayAdminListBefore stopped working in update 1.7.7.0

### ISSUE THREAD

**Issue by matowuut** [PrestaShop/PrestaShop#22910]
After updating my prestashop local instalation on xampp from 1.7.6.3 to 1.7.7.0, the hook for displaying admin buttons before admin orders list is not being called anymore. The hook in question is called "DisplayAdminListBefore". I checked hook documentation and no changes are reported in this hook in 1.7.7.0 version.

I tried to add logger in hook to test if hook is reached and the logger doesnt fire.

1. Install prestashop version 1.7.7.0 on xampp
2. Create test module with "DisplayAdminListBefore" hook activated
3. Create a logger message inside this hook with PrestaShopLogger::addLog
4. See that this hook isnt being called

Prestashop 1.7.6.3:

![presta1](https://user-images.githubusercontent.com/44699377/105155735-d960e400-5b02-11eb-97e3-ca222fe9ac31.png)

Prestashop 1.7.7.0:

![presta2](https://user-images.githubusercontent.com/44699377/105155880-0c0adc80-5b03-11eb-9129-1a5f124af81c.PNG)

 PrestaShop version: 1.7.7.0
 PHP version: 7.4.2

**Comment by hibatallahAouadni** [comment]
Hello @matowuut 

Could you please downgrade your PHP version to 7.3 cause PS1.7.7.0 is not compatible with PHP 7.4 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).
Please check and feedback.

Thanks!

**Comment by matowuut** [comment]
Hello @hibatallahAouadni !

First of all I would like to thank you for taking the time to help out. I followed your suggestion and downgraded my PHP version to 7.3.26. The same problem remains the hook is not reached.

**Comment by hibatallahAouadni** [comment]
Hello @matowuut 

You're right this hook hasn't be registred in the file hook.xml (even on develop branch)
Sorry for the inconvenience :confused: 
Your issue is related to this one #17606.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Progi1984** [comment]
Fixed by #22980.
