### ISSUE TITLE
BO - Order page - An error is displayed when changing the addresses for the second time

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22917]
#### Describe the bug

During testing this PR: https://github.com/PrestaShop/PrestaShop/pull/22909
An exception is displayed when changing the Shipping address the second time.
`Could not find the product in cart, meaning Order and Cart are out of sync`

#### Expected behavior

Remove all the gifts (and the cart rules) that do not match the shipping country and the cart rule country restriction.

#### Steps to Reproduce

0. Upload the United states pack
1. Go to BO => Catalog => Discounts page
2. Create a cart rule with a country selection "The United States" with an action "Free gift" 
3. Go to FO > sign in with John DOE, add any product **different from the gift**
4. Continue checkout > in the Address step: select "My address" (United states country) > Place Order
5. In the BO > Orders > Last order Created
6. Try to change the Shipping address to "Mon addresse" (France country) => ok
7. Try to change again the Shipping address to "Mu address" (United States country) => NOK
8. See error
![image](https://user-images.githubusercontent.com/16067358/105186191-bd286b80-5b31-11eb-89de-bc70e9b61273.png)

1769=> ok: https://drive.google.com/file/d/1olnhZoBnSexUERFT_z4muLwlO7rtY1VF/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, 1771
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Maybe related to this: https://github.com/PrestaShop/PrestaShop/issues/22004

**Comment by Progi1984** [comment]
Fixed by @atomiix in #23138
