### ISSUE TITLE
No entries in database table ps_order_slip_detail_tax  PS 1.7.x.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#22914]
Hello, 

I am now using Prestashop 1.7.x.x since 2017 and I have generated a lot of orderslips during the years but I have no entries in the database table ps_order_slip_detail_tax. Is this just me or do you know about that? 

![image](https://user-images.githubusercontent.com/44971218/105174529-fb6a5e80-5b22-11eb-8fa7-27754623142a.png)

Thank you very much in advance for your answer.

PS 1.7.x.x
current PHP version 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @didi-2018 

Well that's a good question :wink: 

![image](https://user-images.githubusercontent.com/23308427/105176816-0d99cc00-5b26-11eb-89c2-592e3bcb62af.png)

But it's not a bug and you shouldn't post it right here, next time please ask in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack). We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

Ping @PrestaShop/prestashop-maintainers @PrestaShop/prestashop-core-developers does anyone know what the purpose of this table `ps_order_slip_detail_tax` is?

PS: I put it as an improvement cause may be we delete this table if we don't need/use it anymore.

Thanks!

**Comment by didi-2018** [comment]
@hibatallahAouadni  Hi! How should I know if it is a bug or not before getting an anwser here? If a existing database table is not filled, for me that´s a bug. 🤷‍♀️

This table should be filled for orderslips as the table ps_order_invoice_tax. None of the orderslip tables include any tax amounts.

**Comment by PierreRambaud** [comment]
I don't know what is the aim of this table, I see nothing related to it in the source, it has been added in 1.6.0.10, this is all I know :sweat_smile:

**Comment by hibatallahAouadni** [comment]
> it has been added in 1.6.0.10

@kpodemski any idea ??

@PierreRambaud @kpodemski 

- If it should be filled for orderslips as the table ps_order_invoice_tax (as @didi-2018 mentioned above) so it's a bug. (IMHO it's more logic)
- If it should be deleted and there's no use of it, it's an improvement.

So , what do you saying?

**Comment by kpodemski** [comment]
It must've been some kind of mistake, like, we have `order_detail`, `order_detail_tax` and probably because of it we have `_tax` for `order_slip_detail` 🤔 

Either it's mistake or it never been implemented, I don't see any code related to this table

**Comment by hibatallahAouadni** [comment]
So, it's your call @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers

**Comment by PierreRambaud** [comment]
For me it's not a bug, because it has never been implemented.
let @PrestaShop/product-team decide what we should do

**Comment by LouiseBonnard** [comment]
Hi there! If it is not used and nothing in the code is referring to it, then my opinion is: it should be deleted. 😄

**Comment by hibatallahAouadni** [comment]
Well then we had the approval :tada: changing the label to **`To Do`** :wink:

**Comment by kpodemski** [comment]
My suggestion is to remove it from installer but don't touch with update script, what do you think @PierreRambaud ?

**Comment by PierreRambaud** [comment]
I agree, don't remove a table, it's maybe used by someone :sweat_smile:

**Comment by Varindien** [comment]
Hello,
Does it has been remove officially from 1.7.8 installer?

**Comment by kpodemski** [comment]
Hello @Varindien 

Yes, it has been removed

**Comment by kpodemski** [comment]
@hibatallahAouadni it's fixed, here's PR: https://github.com/PrestaShop/PrestaShop/pull/24118

**Comment by PierreRambaud** [comment]
Closed by #24118

**Comment by hibatallahAouadni** [comment]
Thanks @kpodemski for the tip :wink:
