### ISSUE TITLE
[RESPONSIVE - BO] Fix spacing, padding and bugs

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#22911]
Epic: https://github.com/PrestaShop/PrestaShop/issues/22358 

#### Describe the bug

Theses pages have spacing and padding issues and need to be fixed.

#### Expected behavior

Fix spacing and padding in order to keep consistency between BO pages. 

SELL - Catalog > Products: 
- [x] Add a 12px spacing between _"Filter by category button"_ and _"Bulk actions"_ 
![product](https://user-images.githubusercontent.com/54888056/105158447-43cb5180-5b0e-11eb-8e18-c93740e986d4.png)
- [x] Enlarge placeholder in the table because it can't be read sometimes
_Add screenshots_

SELL - Catalog > Categories:
- [x] Fix bug on KPIs pan size
- [x] Enlarge placeholder in the table

IMPROVE - Module Catalog:
- [x] Add a 12px spacing between the search bar and the _"Category"_ select
- [x] Fix tooltips display and place it right next to the subtitle
- [x] Make the _"Categories" select" on full width
- [x] Add a 8px spacing between the module rating and the _"Install"_ block button
- [x] Add padding of 16px on _"Install"_ block button
![module catalog](https://user-images.githubusercontent.com/54888056/105161258-7591e780-5b11-11eb-94bf-0887e54f6197.png)

IMPROVE - Design > Theme & Logo
- [x] Fix tabs display

IMPROVE - Payment > Payment Methods
- [ ] Use UI Kit because the info alert design at the bottom of this page _"More modules on addons.prestashop.com"_ is wrong => Module issue, not core

IMPROVE - International > Localization
- [ ] Use UI Kit because the checkbox design in _"Content to import"_ section is wrong => Backend issue

CONFIGURE - Shop Parameters > Traffic & SEO: 
- [x] Add a 12px spacing between _"Learn more"_ and _"Configure index page"_ button

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by NeOMakinG** [comment]
Some things can't be done by myself, did my best for the moment
