### ISSUE TITLE
Category update problem in the API

### ISSUE THREAD

**Issue by MatteoCout** [PrestaShop/PrestaShop#22918]
#### Describe the bug
We have in place a prestashop using the multistore.
We want to change the assignment of stores to the category in our prestashop using the API on /categories with the PUT method, we add in the url  : '?id_shop=example of id shop wish'.
Even if we do not put the parameter we still have the problem.
In body we have this : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <category>
        <id>7</id>
        <id_parent>2</id_parent>
        <active>1</active>
        <id_shop_default>1</id_shop_default>
        <is_root_category>0</is_root_category>
        <position>1</position>

        <name>
            <language id="1">TEST</language>
            <language id="2">TEST</language>
            <language id="3">TEST</language>
            <language id="4">TEST</language>
            <language id="5">TEST</language>
        </name>
        <link_rewrite>
            <language id="1">TEST</language>
            <language id="2">TEST</language>
            <language id="3">TEST</language>
            <language id="4">TEST</language>
            <language id="5">TEST</language>
        </link_rewrite>
       
     
    </category>
</prestashop>
```
the category we want to modify is assigned to 1 store but once we have updated the category it will be assigned to all stores.
the response to our API call is correct.

#### Steps to Reproduce

1. Enable multishop into your prestashop
2. Create a category and assign it to a single store
3. Update it via the API (example: name)
4. Return to see the parameters of the category, it will be active on all shops

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7

**Comment by hibatallahAouadni** [comment]
Hello @MatteoCout 

Thanks for your detailed issue :clap: 
It seems your issue is similar to this one #13987 could you please check :wink: 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @MatteoCout ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
