### ISSUE TITLE
Symfony Security Checker will end on January 2021

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22924]
We use [Symfony Security Checker](https://github.com/sensiolabs/security-checker) to search for vulnerable dependencies when building a release
```
php bin/console security:check
```

However as stated on their [github repository](https://github.com/sensiolabs/security-checker), this tool will not be usable in February 2021 as "the underlying web service will stop working at the end of January 2021."

Some alternatives are mentioned. I also know https://github.com/Roave/SecurityAdvisories does a similar job. And maybe dependabot is actually doing the same? (ping @PierreRambaud)

**Comment by PierreRambaud** [comment]
Why not using https://github.com/fabpot/local-php-security-checker which use the same database (https://twitter.com/fabpot/status/1349986053738934277) 
I'm not a huge fan of using a tool manage by Ocramus, don't forget he's the one who break everything, everytime :sweat_smile:

**Comment by Progi1984** [comment]
Please not a OCramius tool. I prefer the fabpot tool.

**Comment by matks** [comment]
> Why not using https://github.com/fabpot/local-php-security-checker

It's a go tool 😅  . I will try to make it work nonetheless.

Btw `php bin/console security:check` is broken as expected.

**Comment by PierreRambaud** [comment]
> I will try to make it work nonetheless

Feel free to directly download an archive: https://github.com/fabpot/local-php-security-checker/releases :)

**Comment by matks** [comment]
Looks like the good binary for MacOSX is `local-php-security-checker_1.0.0_darwin_amd64`
