### ISSUE TITLE
Trouble with buttons

### ISSUE THREAD

**Issue by dalmas-fred** [PrestaShop/PrestaShop#22926]
#### Describe the bug
I, just install 1.7.7.1 version of prestashop.  with php 7.3.7
since i got a big problem with the buttons they dont's work properly.
for example, if i try to add a new product.
and try to import a new picture the add a picture the (+) button do not open a dialog file to choose my picture.
on the same screen if i try to add a nex category nothing append.

#### Expected behavior
The buttons works

#### Steps to Reproduce

1. BO>Catalog>Products
2. Create a new product
3. Try to add a picture
4. See error => the (+) button do not open a dialog file to choose my picture.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
* PrestaShop version: 1.7.7.1
* PHP version: 7.3.7

best regards
fred

**Comment by hibatallahAouadni** [comment]
Hello @dalmas-fred 

That's extremly weird :thinking: 
Could you please provide a screen record or screenshot of your console.

PS: I edit your issue :wink: please next time **respect the provided template to submit a complete bug report**.

Thanks!

**Comment by dalmas-fred** [comment]
Sorry, i don't realise i don't respect the template .

here is the screenshot.

![image](https://user-images.githubusercontent.com/77782063/105354118-66359b80-5bf0-11eb-9680-409289895d3a.png)

Expected behavior
The buttons works

Steps to Reproduce
Steps to reproduce the behavior:

BO>theme and logo>theme
use this theme
try to change the theme
See error => the (use this theme) button do not have any actions.

Screenshots

![image](https://user-images.githubusercontent.com/77782063/105354693-35099b00-5bf1-11eb-8de0-61b4265adf61.png)


Additional information
PrestaShop version: 1.7.7.1
PHP version: 7.3.7

**Comment by hibatallahAouadni** [comment]
Hello @dalmas-fred 

SO you encounter this issue only when this theme is applied?
Please check and feedback.

Thanks

**Comment by dalmas-fred** [comment]
Sorry but I'm not able to go back, I mean the button to change the theme doesn't work anymore.
By the way my installation is local so how could I give you access to it?

Thanks.
Best regards

**Comment by hibatallahAouadni** [comment]
Hello @dalmas-fred 

As you can see in the attached screen record below I can add a pictures to product and I can change he Theme: 

https://drive.google.com/file/d/1ZPXF9lr8l_KEntdS7vSSE5zYDuzrEcYi/view

Please check and feedback.
Thanks!

**Comment by dalmas-fred** [comment]
I have no doubt about it but in my case it doesn't work. What do you use to capture the screen in video?. I can do the same and send it to you.

⁣Télécharger BlueMail pour Android ​

Le 22 janv. 2021 à 14:59, à 14:59, Hibatallah Aouadni <notifications@github.com> a écrit:

**Comment by hibatallahAouadni** [comment]
Hello @dalmas-fred 

 > I can do the same and send it to you.

Install the Screencastify Chrome extension:

![image](https://user-images.githubusercontent.com/23308427/105503006-58524a00-5cc6-11eb-91f3-f8d9aabdba1d.png)

And it seems like you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm really sorry I have to close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

Thanks!
