### ISSUE TITLE
Order detail page not loading correctly

### ISSUE THREAD

**Issue by Myrjam** [PrestaShop/PrestaShop#22928]
#### Describe the bug

Order detail page in backoffice is not loading the top bar correctly
![image](https://user-images.githubusercontent.com/52692922/105350732-e279b000-5beb-11eb-9d71-38b46442fbb6.png)

#### Expected behavior

https://build.prestashop.com/assets/images/2020/05/order_details_hooks.jpg

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Myrjam 

Yeh I got the issue at first time after upgrading my shop to 1.7.7.1 but after refreshing my page multiple times, it's gone :sweat_smile: 
So, could you please refresh your page and clear your cache and then feedback.

Thanks!

**Comment by Myrjam** [comment]
Thanks @hibatallahAouadni, I tried that, but the problem unfortunately is more persistent than that!

**Comment by Myrjam** [comment]
What? ! never mind... it did help... thank you!

**Comment by hibatallahAouadni** [comment]
@Myrjam Glad that it works for you :sweat_smile:
