### ISSUE TITLE
Prestashop 1.7.6.8 can't change attributes position 

### ISSUE THREAD

**Issue by Audiojungle** [PrestaShop/PrestaShop#22939]
HEllo,

I have huge problems with attributes positions.

I'm not able to change any attribute position, when i change position, it saves, then when i refresh it go back as it was before.

I've noticed that 3 of my attributes have exact same id position!!

Check this video please, i show that i can't change attribute position:
https://gyazo.com/80c07bbac930a09a459631f53d75b790

Anch check this screenshot i've made, i show that 6 attributes have same position id
https://prnt.sc/xe39hw

Please help!

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Audiojungle ,
I can't reproduce your issue, please check my screen record : https://drive.google.com/file/d/1Zk4f9WugCFbbmYQZJ3QU_W7jIhMz-K2g/view

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by Audiojungle** [comment]
hello,

if someone have the same problem, here is the solution

it's a prestashop bug, i've fixed it like this:
1.create one useless attribute to delete
2.change attributes positions
3.delete useless attribute
