### ISSUE TITLE
Fuzzy search - plural form doesn't fetch any results

### ISSUE THREAD

**Issue by joaolago1113** [PrestaShop/PrestaShop#22931]
#### Describe the bug

Searching the plural form of words yields no results for products with the singular form of the word in the name. For example, "thermostats" doesn't fetch results for products with the word "thermostat", or "pumps" doesn't find the same results as searching for the singular "pump". But if I search for thermostats or pumps while replacing the last character 's' with any other character the results are delivered correctly, so if I search "thermostatf" I get results with the word "thermostat", and the same happens with "pumpf".

#### Expected behavior

Searching for plurals "thermostats" or "pumps" should deliver results with "thermostat" and "pump" in the products name respectively. Otherwise, a client might type a product's name in plural, like "pumps", in hopes of finding what pumps the store was selling, but finding none because the store used the singular word "pump" to describe each product.

#### Steps to Reproduce

1. Add products to the store with "pump" in the name;
2. Use Fuzzy Search to search for "pumps";
3. No product with the word "pump" in the name are found.

**Screenshots**

Searching "pump":
![pump](https://user-images.githubusercontent.com/22820692/105384903-aace3080-5c0a-11eb-8e5c-0870145412c0.png)

Searching "pumps":
![pumps](https://user-images.githubusercontent.com/22820692/105384396-0f3cc000-5c0a-11eb-9703-4e4ae5f63550.png)

Searching "pumpf":
![pumpf](https://user-images.githubusercontent.com/22820692/105384392-0d72fc80-5c0a-11eb-90ac-dfc03814755b.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26
* Search bar Module: v2.0.1

**Comment by hibatallahAouadni** [comment]
Hello @joaolago1113 

Thanks for your issue but could please follow and respect the provided template to submit a bug report :wink: 
I need your PS, PHP and Fuzzy search versions to be able to reproduce your issue.

Thanks!

**Comment by joaolago1113** [comment]
@hibatallahAouadni Sorry, I clicked the "report a problem" link from the BO and the template didn't show up. 🤔 Thought it wasn't needed.
I have PHP 7.3.26, Prestashop 1.7.7.1, and I'm guessing the latest stable fuzzy search version but I'll check.

**Comment by joaolago1113** [comment]
How do you check fuzzy search version?

**Comment by hibatallahAouadni** [comment]
hello @joaolago1113 

> the template didn't show up. thinking Thought it wasn't needed.

Of course it's needed, next time follow the steps of the screenshots below to submit a bug report :wink: 

![image](https://user-images.githubusercontent.com/23308427/105378583-3f855e00-5c0c-11eb-84fb-c83a1989b397.png)

---
![image](https://user-images.githubusercontent.com/23308427/105378597-44e2a880-5c0c-11eb-8333-365d5a2d1598.png)

---
![image](https://user-images.githubusercontent.com/23308427/105378610-49a75c80-5c0c-11eb-9a59-cc762417122b.png)

Well, as you see those blocks in the template (steps to reproduce, additional infos, ...) we need it, to make it esay to help you.
About the Fuzzy search version:

1. BO>IMPROVE>Modules>Module Manager
2. search the term "search bar"
3. Then you can see the version mentioned just below the module name (see screenshot below):

![image](https://user-images.githubusercontent.com/23308427/105380405-2087cb80-5c0e-11eb-8fad-651a40ae28ed.png)

Please check and feedback.
Thanks!

**Comment by joaolago1113** [comment]
#### Describe the bug

Searching the plural form of words yields no results for products with the singular form of the word in the name. For example, "thermostats" doesn't fetch results for products with the word "thermostat", or "pumps" doesn't find the same results as searching for the singular "pump". But if I search for thermostats or pumps while replacing the last character 's' with any other character the results are delivered correctly, so if I search "thermostatf" I get results with the word "thermostat", and the same happens with "pumpf".

#### Expected behavior

Searching for plurals "thermostats" or "pumps" should deliver results with "thermostat" and "pump" in the products name respectively. Otherwise, a client might type a product's name in plural, like "pumps", in hopes of finding what pumps the store was selling, but finding none because the store used the singular word "pump" to describe each product.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Add products to the store with "pump" in the name;
2. Use Fuzzy Search to search for "pumps";
3. No product with the word "pump" in the name are found.

**Screenshots**

Searching "pump":
![pump](https://user-images.githubusercontent.com/22820692/105384903-aace3080-5c0a-11eb-8e5c-0870145412c0.png)

Searching "pumps":
![pumps](https://user-images.githubusercontent.com/22820692/105384396-0f3cc000-5c0a-11eb-9703-4e4ae5f63550.png)

Searching "pumpf":
![pumpf](https://user-images.githubusercontent.com/22820692/105384392-0d72fc80-5c0a-11eb-90ac-dfc03814755b.png)


#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26
* Search bar Module: v2.0.1

**Comment by hibatallahAouadni** [comment]
Hello @joaolago1113 

Sorry for the late response.
Could you please try to re-build the entire index, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/105763126-adf05600-5f55-11eb-98f9-65b065225138.png)

Please check and feedback.
Thanks!

**Comment by joaolago1113** [comment]
I've tried that, still the same problem :/ @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
Hello @joaolago1113 

I don't know if it's possible to have results with the word **pump** if you make a search with **pumps**.
Let's ask the Product Team, please stay tuned!

Ping @PrestaShop/product-team following these steps:

1. Add products to the store with **pump** in the name;
2. Use Fuzzy Search to search for **pumps**;
3. No product with the word **pump** in the name are found.

Is that the expected behavior? or we should have results with the word **pump** when we make a search with **pumps**?

**Comment by florine2623** [comment]
It seems to be fixed :

I searched for Mug/Mugs and Vector/Vectors, the products found are the same.

![Image](https://github.com/user-attachments/assets/6848729e-363f-4be1-93af-ac95211080e1)
![Image](https://github.com/user-attachments/assets/d501a89e-7704-4309-a7bd-06fdc77972d7)

![Image](https://github.com/user-attachments/assets/04ad1174-30e3-4a17-91b0-a75f13c8bc3b)
![Image](https://github.com/user-attachments/assets/c9278ae5-1b01-4158-9331-eccee2ef8925)

I'm closing this issue.
Thanks!
