### ISSUE TITLE
Prestashop 1.6.1.24

### ISSUE THREAD

**Issue by w3bissime** [PrestaShop/PrestaShop#22933]
#### Describe the bug

There are errors while saving queries in the sql manager.
Some simple queries are saved, other more complex are not.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to SQL Manager
2. Click on 'Add a new query.'
3. Add a name (whaterver) and copy-paste this code (without quotes):

SELECT * FROM `ps_orders`
INNER JOIN `ps_customer`
ON `ps_orders`.`id_customer` = `ps_customer`.`id_customer`

4. An error occurs

* PrestaShop version: 1.6.1.24
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @w3bissime ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
