### ISSUE TITLE
1.7.7.1 - lazyarray prevents from access product in $params in hook filterProductContent

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#22938]
#### Describe the bug

I'm trying to use the hook `filterProductContent`. I'd like to format the description and add some custom properties.
In my module I define this function

    public function hookFilterProductContent($params){
        $object = $params['object'];
        var_dump($object); // this shows me that $object['product']['description'] contains what I need, but product is protected
        var_dump($object['product']); // this is an empty array
        var_dump($object['product']['description']); // This throws an Undefined index error
    }

This is similar to  #12396. I had a look at the example module provided there, but as far as I understand there is no relevant difference with my code above.

#### Expected behavior

I expect to be able to access product properties in the hook `filterProductContent`. I also expect to be able to modifiy ('filter') properties and even add a new property.

I'm not sure if I understand well the `LazyArray` object. There must be possibilities to access and modify its properties, otherwise, the existence of this hooks makes no point.

#### Documentation
This dev doc page talks about the access https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.5/#lazyarrays of LazyArrays, but it does not talk about the issue of `protected` vs `public` properties.

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Could you take a look at this please ?
Thanks!

**Comment by kpodemski** [comment]
Hello @lmeyer1 

Take a look. https://gist.github.com/kpodemski/0d2e8171e5b954b687bbc35a6fab63ee

**Comment by lmeyer1** [comment]
Thank you. This works. I didn't understand `LazyArray` well enough.

    public function hookFilterProductContent($params){
        $object = $params['object'];
        var_dump($object);
        var_dump($object['description']);
    }

The first `var_dump` shows:

    object(PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductLazyArray)
        protected 'product' => 
            array (size=121)
                'description' => '...'

 $object['product']['description'] contains what I need, but product is protected.

The second `var_dump` returns the product description by the means of `LazyArray` which implements `ArrayAccess`.

**Comment by hibatallahAouadni** [comment]
@lmeyer1 Glad that you figure it out :tada: 
@kpodemski Thanks for helping :rocket:
