### ISSUE TITLE
FO - Discount - Incorrect display on FO with free gift + percentage cart rule

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22946]
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-759388271
On FO, when a cart rule with a free gift + percentage discount is added to the cart, the discount displayed on the line of this cart rule is incorrect **only** when the gift is ordered also because the percentage discount is calculated also on the gifted product price.
The Total discount is OK

#### Steps to Reproduce

1. In BO > Catalog > Discounts, add a new cart rule
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included). Save the cart rule.
3. Go to FO, add to the cart the same gifted product
4. In the cart, add the discount => The discount line => NOK ![image](https://user-images.githubusercontent.com/16067358/105477795-a35a6600-5ca2-11eb-9bae-8e0de42f3c5e.png)
5. Click on Proceed to checkout ![image](https://user-images.githubusercontent.com/16067358/105478048-f7654a80-5ca2-11eb-80b6-8d19fac9c7d2.png)
6. See error

PS:1769 => ok
![image](https://user-images.githubusercontent.com/16067358/105478977-334cdf80-5ca4-11eb-9cb7-b4c1aa5413b3.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi!

This issue will be fixed with this PR: 
https://github.com/PrestaShop/PrestaShop/pull/24088

Thank you!

**Comment by Progi1984** [comment]
Fixed by #24088
