### ISSUE TITLE
Bad number of visits on module statsbestcustomers

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22943]
#### Describe the bug

there is a regression maybe linked to the fix of the PR PrestaShop/statsbestcustomers#16
The visits counter is incremented even if the customers is not logged
See the video I create an order from FO when I change the status order visits change. I create an order from the BO the visits status is incremented

**Screenshots**
https://drive.google.com/file/d/1E1fuphQoIwOb-XYFICAkBLMP5UiOoSjn/view

#### Additional information

* PrestaShop version: 1.7.7 / 1.7.6
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed in PrestaShop/statsbestcustomers#21
