### ISSUE TITLE
multiple CMS blocks

### ISSUE THREAD

**Issue by dali-rajab** [PrestaShop/PrestaShop#22949]
Hello everyone !
Can this module create more than one CMS block ? because it's strange for me to use the object model for just only one record.

**Comment by florine2623** [comment]
Hi @dali-rajab ,

If you're talking about Link Widget module, yes you can create multiple blocks.
![Capture d’écran 2021-01-22 à 12 26 43](https://user-images.githubusercontent.com/16019289/105485397-1a94f780-5cad-11eb-8b58-2acd889ffd9a.png)

If you're talking about CMS Pages, you can add categories and pages :
![Capture d’écran 2021-01-22 à 12 26 33](https://user-images.githubusercontent.com/16019289/105485416-22ed3280-5cad-11eb-8159-4ef584fd8c3f.png)

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
I'll close your issue.
Thanks!

**Comment by dali-rajab** [comment]
thank you @florine2623 for your quick response. I was'nt clear because i didn't realize  ps_customtext repository redirected me here In fact i'm talking about CMS blocks (https://github.com/PrestaShop/ps_customtext), i'm not talking about CMS pages. So for exemple, let's say we have this block 1 in home page :

![custom_text_1](https://user-images.githubusercontent.com/39015823/105511762-905e8a80-5cd0-11eb-9502-b23ff6c8dbdb.jpg)

And let's say we have to put another custom block 2 in another hook, product page for exemple, **with different content** ! , what should we do in this situation ?

I'm asking about this situation because the module use the ObjectModel class for the text ( https://github.com/PrestaShop/ps_customtext/blob/master/classes/CustomText.php) , so logically many records can be added, or else what it is the benefit of using the ObjectModel class.

Another thing i want to mention, clicking this button (return to the list) just reload the page :
![click](https://user-images.githubusercontent.com/39015823/105513747-f9df9880-5cd2-11eb-814a-b6c90bea3b56.jpg)
