### ISSUE TITLE
Prestashop Checkout configuration page not opened

### ISSUE THREAD

**Issue by UnclePetros** [PrestaShop/PrestaShop#22940]
#### Description

Prestashop checkout module (latest versione v2.5.0) not usable.
After installation, when clicking on the configure button, an empty page is showed.

#### Expected behavior

Configuration page is showed and module can be configured correctly.

#### Steps to Reproduce

1. Go to Prestashop administration module
2. Install Prestashop Checkout latest version
3. Click on Configure Button after installation
4. See the problem on the configuration page

**Screenshots**

![ps_checkout_configuration](https://user-images.githubusercontent.com/4788674/105464204-70f43d00-5c91-11eb-994d-d0b90b589c1f.png)

### Note

The only main difference with a basic Prestashop v1.7.7.0 installation is the use of a custom theme bought on prestashop site.
This theme is the following:
https://addons.prestashop.com/it/temi-elettronica-high-tech/29992-electron-mega-electronics-high-tech-super-store.html

Maybe this theme conflicts with ps_checkout module?

#### Additional information

* PrestaShop version: v1.7.7.0
* PHP version: v7.2

**Comment by florine2623** [comment]
Hi @UnclePetros ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules. For Checkout, there's an email address where you can explain your problem : support-checkout-download@prestashop.com

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
