### ISSUE TITLE
BO - Add new Order page & Shopping cart page - Discount - Incorrect display on FO with free gift + percentage cart rule

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22948]
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-759388271
In the BO > Add new Order page & Shopping cart page, when a cart rule with a free gift + percentage discount is added to the cart, the discount displayed on the line of this cart rule is incorrect because the percentage discount is calculated also on the gifted product price.
The Total discount is OK.

#### Steps to Reproduce

- [x] #27192

1. In BO > Catalog > Discounts, add a new cart rule
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included). Save the cart rule.
3. Go to FO, add to the cart another product (at 100€ tax included too in my case)
4. In the cart, add the discount
5. Go to BO > Orders > Shopping cart page >View the last shopping cart
6. See error (It should be 115 Euro)

![image](https://user-images.githubusercontent.com/16067358/105479893-52983c80-5ca5-11eb-988c-d16d3a2b324b.png)

- [x] **Second issue**

1. In BO > Catalog > Discounts, add a new cart rule
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included). Save the cart rule.
3. Go to FO, add to the cart the same product gifted
4. In the cart, add the discount
5. Go to BO > Orders > Shopping cart page >View the last shopping cart
6. See error (It should be 115Euro)

![image](https://user-images.githubusercontent.com/16067358/105480080-92f7ba80-5ca5-11eb-86bd-3fe6cc655bfb.png)

- [x] **Third issue**

1. In BO > Catalog > Discounts, add a new cart rule
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included). Save the cart rule.
3. Go to BO > Orders > Add new Order > Choose a customer
4. add to the cart another product (at 100€ tax included too in my case) / or the same product gifted
5. Apply discount
6. See error (It should be 115Euro)

![image](https://user-images.githubusercontent.com/16067358/105480371-f681e800-5ca5-11eb-8538-920071eeea9c.png)

PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/105480600-3d6fdd80-5ca6-11eb-946f-1aabe41a6c3d.png)
![image](https://user-images.githubusercontent.com/16067358/105480772-70b26c80-5ca6-11eb-97b6-98eb6906bb90.png)
In the BO > Orders > Add new Order page (Strange price)
![image](https://user-images.githubusercontent.com/16067358/105481138-eddde180-5ca6-11eb-8e7e-2ddcb8d9d379.png)

#### Additional information

* PrestaShop version: 1771
* PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith Could you please tell us if the 3 issues described are still there or if some are already corrected ?

**Comment by khouloudbelguith** [comment]
HI @marionf,

I manage to reproduce the three issues with the 177x branch (PS1773).
https://drive.google.com/file/d/1aIEMW-czc6A72Ns0_e2426ky4FXKJbSV/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Fixed by #24088
