### ISSUE TITLE
missing Hook in database

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#22959]
#### Describe the bug
Just a small problem :
The hook displayBanner is missing in database.
And is present in default template (/classic/templates/_partials/header.tpl)

#### Additional information

* PrestaShop version: 1.7.7.1

**Comment by pppplus** [comment]
duplicate, sorry
https://github.com/PrestaShop/PrestaShop/issues/17606

**Comment by SimonGrn** [comment]
Duplicate of #17606
