### ISSUE TITLE
FO - Discount - Incorrect display on FO with free gift + percentage cart rule with Exclude discounted products is enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22951]
#### Describe the bug

Thanks to @kpodemski Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22768#issuecomment-765324937
On FO, when a cart rule with a free gift + percentage discount is added to the cart, the discount displayed on the line of this cart rule is incorrect when  **Exclude discounted products enabled**.

#### Steps to Reproduce

1. Create a product with price = 120Euro & specific price =20Euro tax included
![image](https://user-images.githubusercontent.com/16067358/105482800-31394f80-5ca9-11eb-9ea5-51967b9e5e21.png)
2. In the "Actions" part, set a percentage discount (15%) and a free gift (in my case, a mug at 100€ tax included) and Enable the "Exclude discounted products
" option. Save the cart rule.
![image](https://user-images.githubusercontent.com/16067358/105482908-5cbc3a00-5ca9-11eb-8ee5-8656bd405b09.png)
3. Go to FO > Add the last product created to the cart
4. Add any other product not discounted
4. Apply discount
5. See the error
5. Delete the not discounted product from the cart
5. See error
![image](https://user-images.githubusercontent.com/16067358/105483048-8c6b4200-5ca9-11eb-84da-6b6d366a4ece.png)
6. Continue checkout > See error
![image](https://user-images.githubusercontent.com/16067358/105483118-a1e06c00-5ca9-11eb-9380-8fb79d3d056a.png)

I attached a screen record
https://drive.google.com/file/d/10zN4wyPFSYSAjYBFVnJp7uMEOnAVsZWO/view?usp=sharing

With PS1769, the discount line => ok (But the total is nok) (it is the opposite)
![image](https://user-images.githubusercontent.com/16067358/105500124-b67d2e00-5cc2-11eb-8423-3eea5f903f48.png)
![image](https://user-images.githubusercontent.com/16067358/105500297-01974100-5cc3-11eb-9f92-a7a194ca2085.png)

Related
https://github.com/PrestaShop/PrestaShop/issues/11722
https://github.com/PrestaShop/PrestaShop/issues/16673
https://github.com/PrestaShop/PrestaShop/issues/20690
https://github.com/PrestaShop/PrestaShop/issues/22615

#### Additional information

* PrestaShop version: 1771
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi!

I manage to reproduce the issue with the 177x branch (1773).

Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith I just tested on 177x branch and I didn't reproduce the bug : 

![image](https://user-images.githubusercontent.com/1533248/117824205-92902900-b26e-11eb-9c0d-173d974a6377.png)
![image](https://user-images.githubusercontent.com/1533248/117824248-9cb22780-b26e-11eb-891e-de248f6401f4.png)

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Yes!
I did not manage to reproduce the issue with 177x and 178x
https://drive.google.com/file/d/166IVHWwsMRKugBknAcmUVOVc1-1XXGWI/view?usp=sharing

Thank you!
