### ISSUE TITLE
Dependencies issue : composer require --dev prestashop/php-dev-tools

### ISSUE THREAD

**Issue by fdonnet** [PrestaShop/PrestaShop#22950]
#### Describe the bug

Fresh git clone, installation ok.
Cannot run "composer require --dev prestashop/php-dev-tools", issue with nikic/php-parser

#### Expected behavior

Dev-tools correctly installed

#### Steps to Reproduce

Composer v1

1. Clone repo
2. Composer install
3. Install presta via instal-dev
4. Go to root folder
5. Run composer require --dev prestashop/php-dev-tools => failed to build

Issue :
    - Installation request for prestashop/php-dev-tools ^3.14 -> satisfiable by prestashop/php-dev-tools[v3.14].
    - Can only install one of: nikic/php-parser[3.x-dev, v4.3.0].
    - Can only install one of: nikic/php-parser[v4.3.0, 3.x-dev].
    - Can only install one of: nikic/php-parser[3.x-dev, v4.3.0].
    - Conclusion: install nikic/php-parser 3.x-dev
    - Installation request for nikic/php-parser (locked at v4.3.0, required as ^4.0) -> satisfiable by nikic/php-parser[v4.3.0].

Dont'kown how to solve this denpendency issue.

#### Additional information

* PrestaShop version: 1.7.7.x branch
* PHP version: 7.2
* Ubuntu 20.04 via wsl2

**Comment by matks** [comment]
Hi @fdonnet prestashop/php-dev-tools is a tooling kit for modules, not PrestaShop Core.

Indeed it cannot be installed on PS Core but it's not something we want to happen ? 🤔

**Comment by fdonnet** [comment]
Ok, my bad, I was trying to follow some docs because in my personal github repo I had an issue with the php-cs fixer in the github commit actions (exit code 8) in dry run (i just play on theme for the moment, so ti was strange). 

But, i solved this github issue... bad .gitignore def on my side.

Thx a lot for the return. I m closing the issue.
