### ISSUE TITLE
Product title should be able to have the "=" character

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#22952]
#### Is your feature request related to a problem?

In PS 1.7.7.1, I can't create a product with a title containing an equal (=) character.

#### Describe the solution you'd like

I would like to be able to create a product name with a "=" sign.

#### Screenshots
![Capture d’écran 2021-01-22 à 15 07 46](https://user-images.githubusercontent.com/16019289/105500744-9ac65780-5cc3-11eb-80d1-1501d792e8c5.png)

#### Additional context

This character is very important due to the nature of the products sold (medical products for animals)

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,
A PrestaShop Agency has requested this, do you think it would be possible to implement this ?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @florine2623, thanks for the feedback! Could you share an example?

**Comment by matks** [comment]
It has to be confirmed, but I think characters such as "=" are not accepted because they create unreliable/unusuable product URLs. If we want to accept such characters, we have to verify URLs for the related product page work fine.

**Comment by LouiseBonnard** [comment]
Thank you, @matks, how complex can this be? I can't really imagine in which case the use of the '=' character is required...

**Comment by florine2623** [comment]
It is the expected behavior :

![Image](https://github.com/user-attachments/assets/8dbdee53-165e-4e8e-8edb-bdf65e715000)
