### ISSUE TITLE
Payment Stripe  Error when First and Last name longer then 30 character  

### ISSUE THREAD

**Issue by nisteria** [PrestaShop/PrestaShop#22963]
#### Describe the bug

its only when the First and Last name is longer then 30 Character 

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Pay with Stripe Sofort
2. Login Bank
3. Paymant ok and go back to Shop

**Screenshots**
https://domain.at/module/stripe_official/validation?client_secret=src_client_secret_IWh4jZlSeOJ2CGNRXXXXKL3&livemode=true&redirect_status=pending&source=src_1ICtAgEBInmJgt2exXXXXXXX

[PrestaShopException]
Sie haben 37 Zeichen in Feld StripePayment->name eingegeben (Nur Eingaben zwischen 0 und 30 Zeichen möglich).
at line 1027 in file classes/ObjectModel.php

1022.             }
1023. 
1024.             $message = $this->validateField($field, $this->$field);
1025.             if ($message !== true) {
1026.                 if ($die) {
1027.                     throw new PrestaShopException($message);
1028.                 }
1029. 
1030.                 return $error_return ? $message : false;
1031.             }
1032.         }
ObjectModelCore->validateFields - [line 292 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 559 - classes/ObjectModel.php]
ObjectModelCore->add - [line 516 - classes/ObjectModel.php] - [2 Arguments]
ObjectModelCore->save - [line 346 - modules/stripe_official/classes/actions/ValidationOrderActions.php]
ValidationOrderActions->addTentative - [line - ]
call_user_func_array - [line 132 - modules/stripe_official/vendor/totpsclasslib/src/Actions/ActionsHandler.php] - [2 Arguments]
Stripe_officialClasslib\Actions\ActionsHandler->process - [line 83 - modules/stripe_official/controllers/front/validation.php] - [1 Arguments]
stripe_officialValidationModuleFrontController->initContent - [line 306 - classes/controller/Controller.php]
ControllerCore->run - [line 518 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by matks** [comment]
Hi @nisteria this repository accepts bug reports for the project itself. I am sorry but the Stripe module is out of the scope.

You need to reach out to the module developer. If this module has been bought on the PrestaShop Addons Marketplace, you can contact the developer through the link provided on their Marketplace page.
