### ISSUE TITLE
Backoffice access error after updating to 1.7.7.1

### ISSUE THREAD

**Issue by CISKITO93** [PrestaShop/PrestaShop#22960]
Hello guys,

I have updated from 1.7.6.9 to 1.7.7.1 and at the end of the update it has given me these errors:

> SQL 1.7.7.0 1709 in ALTER TABLE `ps_configuration` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_connections_source` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_customer` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_employee` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_order_state` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_page_type` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.
SQL 1.7.7.0 1709 in ALTER TABLE `ps_smarty_cache` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Index column size too large. The maximum column size is 767 bytes.

The problem is that now when I try to access the backoffice, I enter my email and password and when I enter, they remove the access fields, I attach a screenshot.

<a href="https://ibb.co/gFqP1R3"><img src="https://i.ibb.co/sJx6SV2/Sin-t-tulo.png" alt="Sin-t-tulo" border="0"></a>

That could be happening? How can I solve that? Anyone else has happened?

I wait for answers.
A GREETING!

**Comment by matks** [comment]
Hello, the error message seems very similar to https://github.com/PrestaShop/PrestaShop/issues/22809 . Do you use Oracle MySQL?

**Comment by guicunha87** [comment]
Estou com o mesmo problema, porém baixei uma image limpa direto do site.

**Comment by hibatallahAouadni** [comment]
Hello @guicunha87 

Please use English! English is the norm on GitHub.
I can see that you have the same error but you had a fresh install, a fresh install of what? 1.7.6.9 or 1.7.7.1?
So could you please answer @matks question
> Do you use Oracle MySQL?

**PS: next time respect and follow the provided template to submit a bug report** :wink: 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @CISKITO93 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
