### ISSUE TITLE
Categories page in BO doesn't show categories list

### ISSUE THREAD

**Issue by iliankirov** [PrestaShop/PrestaShop#22964]
#### Describe the bug

The categories page on BO doesn't show the categories, that are created. I cleared the cashe and refresh many times but there is no result. 

#### Expected behavior

The page have to display available categories, and they have to be able to be edited.

#### Steps to Reproduce

- Go to 'BO'
- Click on 'Catalog > Categories'
- See error, that I described, the page loads but there is no categories displayed.

**Screenshots**

Here is the view of the problem page:

![New Picture (6)](https://user-images.githubusercontent.com/65872504/105615157-2381e800-5dd7-11eb-94e4-eb2b11f852ef.jpg)

The page can't be loaded with "Debug mode" activated, here is the screen:

![New Picture (7)](https://user-images.githubusercontent.com/65872504/105615169-35fc2180-5dd7-11eb-8f01-740ca50ef03e.jpg)

Here is the screen on BO > Advanced parameters > Information:

![104784443-f3ac6200-5790-11eb-9e74-558409e7badd](https://user-images.githubusercontent.com/65872504/105615198-6e9bfb00-5dd7-11eb-9403-7d21b0e41f96.jpg)

Here is the screen on GitHub page:

![104784438-ef804480-5790-11eb-96c8-1e6fb6bafe0a](https://user-images.githubusercontent.com/65872504/105615276-0568b780-5dd8-11eb-923b-ef56a68562ca.jpg)
 

Here is error log file:

[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/5861177/error_log.txt)

#### Additional information

- PrestaShop version: 1.7.6.5
- PHP version: 7.2.34

Thank you!

**Comment by SimonGrn** [comment]
Hello,

The "out of memory" error means your server doesn't have enough memory to handle rendering the categories.
I suggest you contact your hosting provider to upgrade your memory.

Since this is not linked to the Core, I close this issue. Feel free to answer the thread if you have new informations.

Thank you !

**Comment by iliankirov** [comment]
Hello! Ok, but why it happened, when the "memory_limit" directive is set on 512M (it's shown on the srceenshots), the server has pretty enought memory - 4GB ?

**Comment by SimonGrn** [comment]
We can't know for you. It's working well in our tests, so it's coming from either your configuration or your shop. If you have thousands of categories, your server will need **A LOT** of memory to display them all.

**Comment by iliankirov** [comment]
The categories are only 6 .

**Comment by SimonGrn** [comment]
Sadly, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
