### ISSUE TITLE
Split payment amount 1.6.1.24

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#22972]
Hi,

We have a payment issue on the shop. This happens whatever the payment method, being Payzen or Paypal.

When a customer places an order, the order value sent to payment portal is randomly reduced. The customer pays then only part of the order.

The successful payment comes back to the shop and the order is created, logging the reduced amount paid.

When we change the order status to "order being prepared", a new line is automatically added in the order payment log with the missing amount. But it has never been paid. It's just Prestashop that adds this line.

This happens randomly, not to every order.

Thanks

![Screen Shot 2021-01-04 at 11 34 05](https://user-images.githubusercontent.com/71735/105687931-ef9ae580-5ef0-11eb-97ed-49ce17ec6bb7.png)
![Screen Shot 2021-01-06 at 17 47 05](https://user-images.githubusercontent.com/71735/105687933-f0cc1280-5ef0-11eb-88c0-5db7efb6245d.png)

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
