### ISSUE TITLE
Missing column in ps_tab

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#22971]
*** Issue ***
After updating from 1.7.6.x to 1.7.7.x the column "route_name" is missing in table ps_tab, but it's in the Tab.php class.
The script allowing to add this column is not in the "install" folder, and it's not added by 1 click upgrade.
So, it's no more possible to manipulate tabs.

*** Way to reproduce ***
Update any 1.7.6.x shop to 1.7.7.0 or 1.7.7.1.

*** Expected behavior ***
Have a ps_tab table containing the "route_name" field

*** Fix ***
Add the "route_name" creation to the next prestashop \install\upgrade\sql\1.7.7.2.sql file.

**Comment by kpodemski** [comment]
Hello,

firstly, this column is added via Doctrine so if you don't see it it might be related to some issues during upgrade.

secondly, please follow the template to submit a complete bug report and fill the blocks that we provided in the template (describe the bug, expected behavior, steps to reproduce, ..).

Thank you 👍

**Comment by Prestaplugins** [comment]
Seriously... you close it because it doesn't respect the template ?
You should give some interest to an issue even if it doesn't look like what you expected.

I described the bug... and the way to reproduce is to update any 1.7.x shop (not 1.7.7.x) to 1.7.7.0 or 1.7.7.1.

The Tab.php class has been modified in 1.7.7.0 and this field has been added.
So it should be added by \prestashop 1.7.7.1\install\upgrade\sql\1.7.7.0.sql, but it's not !

Or there's a new way to add missing fields ? I don't know anything about doctrine, but I'm quite sure that field are still added by a SQL script during an update, as I can see from beginning to 1.7.7.0...

**Comment by Prestaplugins** [comment]
Better now ?

**Comment by kpodemski** [comment]
It is better, thank you ;)

Do you have any warnings during upgrade?

**Comment by Prestaplugins** [comment]
I can't tell you, I'm not the one who made the update. But that column is not in the SQL script executed during update, so I don't think the problem is related to any warning. It seems it has just been forgotten by the prestashop team...

**Comment by Prestaplugins** [comment]
No news ?
“No change required“ label, what does that means? 
Issue still closed???

I just found another customer having the same issue.

**Comment by Prestaplugins** [comment]
Is this issue fixed in 1.7.7.2 ?

**Comment by matks** [comment]
@Prestaplugins I just performed an upgrade from PS 1.7.6 to PS 1.7.7.2 . I have the `route_name` column. But nothing has been changed in PS 1.7.7.2 regarding your issue.

The `route_name` column is added by Doctrine upgrade process (https://www.doctrine-project.org/). If during your upgrade process, the `route_name` column has not been added, something went wrong which prevented the column creation. But on my environment it works.

If you want this issue to be added into the roadmap, we need you to explore and find what settings resulted in Doctrine not being able to add the column. We dont have your computer so we cannot test it. It is likely to be related to a specific setting in your server configuration.

**Comment by Prestaplugins** [comment]
Hello @matks,
Ok, so if I understand clearly, it doesn't need to be in the 1.7.7.2 sql update files ?
It was on my customer's shops, and I was not here when they did the upgrade, so I have no log for the errors or anything else.
But I found that problem already in 2 shops in a few days... so maybe you should investigate.

**Comment by matks** [comment]
> Hello @matks,
> Ok, so if I understand clearly, it doesn't need to be in the 1.7.7.2 sql update files ?

Indeed, it will be added automatically.

> But I found that problem already in 2 shops in a few days... so maybe you should investigate.

I already investigated it, and I found nothing 😬  so ... I dont think I will get different results by doing the same 😅  ?

What is likely to happen is
- on your environments the issue appears
- on my environment the issue cannot be seen

Unless you ship your computer / server to me I dont see how I can explore this topic 😉  this is why I said

> we need you to explore and find what settings resulted in Doctrine not being able to add the column. We dont have your computer so we cannot test it. It is likely to be related to a specific setting in your server configuration.
