### ISSUE TITLE
Missing DNI Number in BO > Order View

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22979]
#### Describe the bug

In 1.7.7.0 and 1.7.7.1 versions, the Identification number ("DNI") is not displayed in BO > Orders details > Address block. This field is mandatory for some countries, like Spain for example.

The info is also missing in the "Preview" of the order in Orders List.

The DNI is however displayed in the invoice.

#### Expected behavior

Identification number should be displayed in the Shipping Address and Invoice Address, in Customer block in BO > Orders details

#### Steps to Reproduce

0. Add "Spain" as a country in the shop
1. Go to FO, connect with a customer
2. Add an address in Spain, with an Identification Number
3. Make an order
4. Go to BO > Orders > Last order
5. Check Customer block : Address dos not contains the "Identification Number"

**Screenshots**

Address in FO : 
![177 regression missing DNI address](https://user-images.githubusercontent.com/55688534/105717954-078a5d80-5f21-11eb-88f5-168c1294fb9d.png)

Display of order details page in 176 : 
![177 regression missing DNI address block 176](https://user-images.githubusercontent.com/55688534/105717947-05280380-5f21-11eb-8d6a-5a4b70e84872.png)

Display of order details page in 177 : 
![177 regression missing DNI address block 177](https://user-images.githubusercontent.com/55688534/105717940-02c5a980-5f21-11eb-9684-5bfb2350f142.png)

Missing info in Preview Order too : 

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A
![177 regression missing DNI address block 177 preview](https://user-images.githubusercontent.com/55688534/105724027-b762c980-5f27-11eb-90f9-a50786ad5ee5.png)

**Comment by Robin-Fischer-PS** [comment]
Ping @MatShir for the update of the specifications :)

**Comment by maxadp** [comment]
I confirm the issue. DNI it's also mandatory for Italy and is missing, same as Vat Number. I hope there will be hope a fix for both Vat and DNI, cause it's importat for website customer check those fields on order view, also from email notifications.

**Comment by Progi1984** [comment]
Fixed by #23040
