### ISSUE TITLE
[BO - Responsive] Header buttons text is not hidden on mobile

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22987]
#### Describe the bug

Header buttons looks broken on mobile

#### Expected behavior

Having no text under tablet width

#### Steps to Reproduce

1. Go to any migrated pages, and see header buttons on mobile

**Screenshots**

![image](https://user-images.githubusercontent.com/14963751/105731092-4fb07c80-5f2f-11eb-8ebd-d7f1556272e1.png)

#### Additional information

* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

I manage to reproduce the issue with develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/105736111-bc7a4580-5f34-11eb-8d7e-9d70fa703bec.png)

Thanks for your issue and your PR :slightly_smiling_face:
