### ISSUE TITLE
Generic hooks being fired for forms are not fired after migration

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22981]
#### Describe the bug

Bug reported by @Progi1984 for listing (hooks `displayAdminListAfter` and `displayAdminListBefore`). It applies for option forms and CRUD forms too.

On legacy page,
- when you open an "option" form, a hook `DisplayAdminOptions` is dispatched
- when you open an "CRUD" form, a hook `DisplayAdminForm` is dispatched

When page has been migrated, these 2 hooks are not dispatched anymore.
- when you open an "option" form on Symfony page, **no hook** `DisplayAdminOptions` is dispatched
- when you open an "CRUD" form on Symfony page, a hook `DisplayAdminForm` is dispatched **twice** and I don't think it's dispatched in the same location

#### Expected behavior

There should be equivalents to these hooks in the new pages.

#### Steps to Reproduce

1. Use module ps_qualityassurance to monitor hooks `DisplayAdminOptions` and `DisplayAdminForm`
2. Open a page with "option" form and "CRUD" form before and after migration. See hook calls being performed.

#### Additional information

* PrestaShop version: 1.7.7

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your issue!
I managed to reproduce the issue with 1.7.7.1 and 1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1qgwMw0JZ7BQ0H0Yv2TNcCNUsUG__Pn2t/view

This issue is related to this one #22910
I’ll add this to the debug backlog so that it’s fixed.

Thanks!

**Comment by Progi1984** [comment]
@matks Sorry. I don't reproduce. Could you give me some example of target page with the problem ?

**Comment by matks** [comment]
@Progi1984 Here is a scenario for Edit BO Page

1. Open BO, install module ps_qualityassurance, register hooks `DisplayAdminOptions` and `DisplayAdminForm`
<img width="863" alt="Capture d’écran 2021-02-03 à 10 26 42" src="https://user-images.githubusercontent.com/3830050/106726705-fc16f080-660a-11eb-8c6d-9a4109c2b5cf.png">
2. Open BO page International > Locations > Zones > Edit
3. In tab "Hook call logs" of ps_qualityassurance, you can witness the call to `DisplayAdminOptions`
<img width="848" alt="Capture d’écran 2021-02-03 à 10 28 45" src="https://user-images.githubusercontent.com/3830050/106726842-1fda3680-660b-11eb-9c14-e7b702029756.png">
4. Now let's compare it to BO page Customers > Adresses > Edit
5. In tab "Hook call logs" you can see hook has been called 4 times. If you look at where the hook is being called, the location is very different.

**Comment by Progi1984** [comment]
@matks Great. That helps me.

I may have an idea : gamification.

This url called only on migrated pages : `http://127.0.0.1/PrestaShop/admin-dev/index.php/configure/shop/modules/gamification/views/img/badges/index.php?controller=AdminDashboard&token=MYTOKEN` called the dashboard... and triggers `dashboardZoneOne` and triggers 
```
[hooks] => Array ([modules_to_hook] => Array ([displayAfterBodyOpeningTag] => Array ([0] => blockreassurance),[displayNavFullWidth] => Array ([0] => blockreassurance),[displayNav1] => Array ([0] => ps_contactinfo),[displayNav2] => Array ([0] => ps_languageselector,[1] => ps_currencyselector,[2] => ps_customersignin,[3] => ps_shoppingcart),[displayTop] => Array ([0] => ps_mainmenu,[1] => ps_searchbar),[displayHome] => Array ([0] => ps_imageslider,[1] => ps_featuredproducts,[2] => ps_banner,[3] => ps_customtext),[displayFooterBefore] => Array ([0] => blockreassurance,[1] => ps_emailsubscription,[2] => ps_socialfollow),[displayFooter] => Array ([0] => ps_linklist,[1] => ps_customeraccountlinks,[2] => ps_contactinfo),[displayFooterAfter] => Array ([0] => blockreassurance),[displayLeftColumn] => Array ([0] => ps_categorytree,[1] => ps_facetedsearch),[displaySearch] => Array ([0] => ps_searchbar),[displayProductAdditionalInfo] => Array ([0] => ps_sharebuttons),[displayReassurance] => Array ([0] => blockreassurance),[displayOrderConfirmation2] => Array ([0] => ps_featuredproducts),[displayCrossSellingShoppingCart] => Array ([0] => ps_featuredproducts))),
```

**Comment by Progi1984** [comment]
I find.

> GET | http://127.0.0.1/PrestaShop/admin-dev/index.php/configure/shop/modules/gamification/views/img/badges/39_1.png
> GET | http://127.0.0.1/PrestaShop/admin-dev/index.php/configure/shop/modules/gamification/views/img/badges/40_0.png

As images doesn't exist, PS loads the dashboard. And that generates calls to the hook.
![image](https://user-images.githubusercontent.com/1533248/106756282-6b064080-662f-11eb-9f0c-95f7102c438c.png)

:exploding_head:

**Comment by Progi1984** [comment]
And that confirms :

**Legacy Page:**
![image](https://user-images.githubusercontent.com/1533248/106757243-67bf8480-6630-11eb-8af7-d77534a5161f.png)

**Migrated Page:**
![image](https://user-images.githubusercontent.com/1533248/106757295-74dc7380-6630-11eb-9512-5ce1dc23d859.png)

**Comment by Progi1984** [comment]
So it's a gamification bug.
