### ISSUE TITLE
Missing B2B info in Orders Details > Customer Block

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22983]
#### Describe the bug

In 1.7.7.0 and 1.7.7.1 versions, when the shop is in B2B mode, some infos are missing in BO > Orders details > Customer Block : 
- Company name before the name of the customer
- SIRET and APE numbers in Customer Summary

In Orders List, the Company Name is displayed in 177 :heavy_check_mark: 

 
#### Expected behavior

The B2B info should also be displayed in 1.7.7 Order Details Page.

#### Steps to Reproduce

1. Go to Shop Parameters > Customer Settings > Enable B2B Mode
2. Go to Customers > Customers > Edit any customer (John DOE for example)
3. Add the B2B Info (Company, SIRET, APE...)
4. Go to an order of this customer, check the detail

**Screenshots**

Customer B2B Info added : 
![177 regression SIRET APE missing customer](https://user-images.githubusercontent.com/55688534/105726069-f6921a00-5f29-11eb-8aed-aea29c79b933.png)

Display in 176 : 
![177 regression SIRET APE missing in 176](https://user-images.githubusercontent.com/55688534/105726074-f85bdd80-5f29-11eb-8c12-f4b2ad2e9ac2.png)

Display in 177 : 
![177 regression SIRET APE missing in 177](https://user-images.githubusercontent.com/55688534/105726094-fc87fb00-5f29-11eb-8590-e98df9594d9d.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Robin-Fischer-PS** [comment]
Ping @MatShir for the update of the specifications :)

**Comment by TristanLDD** [comment]
Hello, here is the display for B2B informations: 

<img width="467" alt="Capture d’écran 2021-02-01 à 14 52 59" src="https://user-images.githubusercontent.com/27484094/106467642-395d7000-649d-11eb-9aae-53f539a58172.png">

In mobile display, SIRET and APE should both appear between "Account registered" and "Valid orders placed" infos in order to facilitate reading.

**Comment by Progi1984** [comment]
Fixed by #23078
