### ISSUE TITLE
Login to BO in 1.7.7.1 does not work

### ISSUE THREAD

**Issue by multiarts** [PrestaShop/PrestaShop#22991]
#### Describe the bug
As per title, when I try to login into my BO this not work. If I put a wrong password prestashop correctly tells me I'm wrong but if I use the correct data nothing happens.

#### Expected behavior
Redirect to back office

#### Steps to Reproduce

1. Go to https://yourshop/folder/index.php
2. Insert username and password
3. Click ENTRA (I'm from Italy, I think the EN version says LOGIN)
4. Here is nothing

#### Additional information

- PrestaShop version: 1.7.7.1
- PHP version: 7.3
- LiteSpeed (hosting): Latest version
- No extra Apache/PHP modules installed
- No extra customization about session and No memcached
- Very plain installation

Excludes the gamming directory from the cache and also did not resolve, I cleared the browser cache, open in anonymous mode and also did not resolve.

The tips in this issue #20079 did not resolve. 
Edit
I found out that even the customer access to the My Account area in the front end are compromised. They are redirected to a blank page and they can't do anything.

**Comment by hibatallahAouadni** [comment]
Hello @multiarts 

I'm a little bit confused :confused: your wrote in the title that you encounter this problem with 1.7.6.7 but you wrote in the **Additional information** block that your PrestaShopo version is 1.7.7.1 :open_mouth: 
So, could you please specify your PrestaShop version.

Well, I didn't manage to reproduce the issue with PS1.7.6.7 and PS1.7.7.1 even when I changed the language to Italian, see the attached screen re'cord below:

https://drive.google.com/file/d/1YHAqTG8h2ljym9keBjtuvN6f85U6-cG_/view

Did you upgrade your shop? Did you change your password lately? or your account permissions?
Please check and feedback.

Thanks!

**Comment by multiarts** [comment]
@hibatallahAouadni 

"Did you upgrade your shop? Did you change your password lately? or your account permissions?" - No.

Sorry, I already fixed the title, I did a clean install.

**Comment by hibatallahAouadni** [comment]
@multiarts could you please check your console, if there are any errors thrown.

**Comment by hibatallahAouadni** [comment]
Hello,

Could you please re-install the shop and check if you still encounter the same problem. If so, you have a problem with your configuration.

Sorry, but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
