### ISSUE TITLE
"Esperanto" doesn't appear in the language list

### ISSUE THREAD

**Issue by axel584** [PrestaShop/PrestaShop#22992]
#### Describe the bug

In the International / Translations admin, I would like to add "esperanto" as language for the front office, but I didn't find it in the list.

#### Expected behavior

I expect to find "esperanto" in the list of available language when I filter with "esp"

#### Steps to Reproduce

1. Go to "International" / "Translation"
2. Click on 'add update a language'
3. Scroll down and the list don't show "esperanto"

**Screenshots**
![image](https://user-images.githubusercontent.com/1334088/105773137-b18ad980-5f63-11eb-80f2-3b5e12e1bd22.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.21

**Comment by hibatallahAouadni** [comment]
Hello @axel584 

I reproduce your issue with PS1.7.4.1, PS1.7.7.1 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/105817512-00615f00-5fb6-11eb-9d7a-c02186653c1d.png)

This language use to be in the list with PS1.6, see the attached screenshot below with PS1.6.1.20:

![image](https://user-images.githubusercontent.com/23308427/105817625-2b4bb300-5fb6-11eb-9fc7-3b4f3827d883.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by SimonGrn** [comment]
This is a Crowdin issue, right ?
Poke @LouiseBonnard maybe ?

**Comment by LouiseBonnard** [comment]
For international issues (translations, localization packs, languages, and so on), you should ping @Julievrz. ;-)

**Comment by Julievrz** [comment]
Hi! The issue does not seem to come from Crowdin. @eternoendless told me that the problem comes from our side. He thinks that the script is not cleaning its folder after an import.

**Comment by axel584** [comment]
@Julievrz : Which script do you mean ?

And other question : do you know how the file : http://i18n.prestashop.com/translations/1.7.7.1/available_languages.json is generated ?

**Comment by eternoendless** [comment]
It's here: https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/available_languages.json

I think you need to add Esperanto there to make it available.

**Comment by axel584** [comment]
The project "TranslationFiles" is describe as :
`[READ-ONLY] This repo contains all the necessary files to generate translation packs for PrestaShop 1.6 and 1.7. It's updated automatically.`
Can I change the file "available_languages.json" ? Or is it generate by a script ?

**Comment by axel584** [comment]
I just see that the script is changed :) Thank you.

**Comment by Julievrz** [comment]
Yes, I opened a pull request for that. We'll have to wait for it to be merged and see if it solves the issue!

**Comment by Julievrz** [comment]
@hibatallahAouadni @eternoendless Shouldn't we reopen this issue? Indeed, even after the merge of the PR, I still cannot see the Esperanto language in the software...
![image](https://user-images.githubusercontent.com/70583503/107746551-49cfdf00-6d16-11eb-9bc1-84b8ec068d12.png)

**Comment by hibatallahAouadni** [comment]
@Julievrz I think so, @eternoendless it's your call :wink:

**Comment by Julievrz** [comment]
Esperanto is finally available in the BO. ✨
