### ISSUE TITLE
prestashop 1-click upgrade Rollback problem - some tables do not exist after rollback

### ISSUE THREAD

**Issue by crabbi33** [PrestaShop/PrestaShop#22995]
#### Describe the bug

Got a problem when i try to upgrade my shop from 1.7.4.2 to 1.7.7 with 1-click upgrade module :
thx

>Edit by Khouloud

After Rollback, some tables are not recovered

- ps_guest
- ps_connections
- ps_connections_page
- ps_connections_source
- ps_statssearch

#### Steps to reproduce the issue:

1. Install autoupgrade module
2. Make an upgrade
3. Do a rollback
4. Enable debug mode
5. Try to navigate to the BO > Customers page => see error
6. Try to navigate to FO => See error
7. Try to search a product in the FO => See error

You can check also in the Database that those tables do not exist.

**Screenshots**
https://drive.google.com/file/d/1PvSoA8FvVZR3I_n8z6EuzrRuEZjbj9so/view

Javascript error (parseJSON) detected for action "upgrademodules".

with that :

```
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'db745838102.ps_connections' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_page` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'db745838102.ps_connections_page' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_source` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'db745838102.ps_connections_source' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_guest` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'db745838102.ps_guest' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_statssearch` CHANGE `keywords` `keywords` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL: Table 'db745838102.ps_statssearch' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections` CHANGE `http_referer` `http_referer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL: Table 'db745838102.ps_connections' doesn't exist 
```

![image](https://user-images.githubusercontent.com/23308427/105875684-6376e400-5ffe-11eb-98a3-b759897ee53b.png)

#### Additionnal infos
* PrestaShop version: 1.7.4.2
* PHP version: 7.1
* 1-click upgrade 4.11.0

**Comment by hibatallahAouadni** [comment]
Hello @crabbi33 

Before upgrading your shop to 1.7.7.1, did you upgraded your shop and then rollback? 
Cause it seems your issue has been thrown only if you do these steps:

1. Upgrade PS1.7.x => PS1.7.y
2. Rollback PS1.7.y => PS1.7.x
3. Upgrade PS1.7.x => PS1.7.z
4. See your error

Please check and feedback.
Thanks!

**Comment by biotradmeding** [comment]
hi; how to rollback please.
i did the laste upgrade and from that i've got symphony error 3/3

**Comment by crabbi33** [comment]
> 
> 
> Hello @crabbi33
> 
> Before upgrading your shop to 1.7.7.1, did you upgraded your shop and then rollback?
> Cause it seems your issue has been thrown only if you do these steps:
> 
>     1. Upgrade PS1.7.x => PS1.7.y
> 
>     2. Rollback PS1.7.y => PS1.7.x
> 
>     3. Upgrade PS1.7.x => PS1.7.z
> 
>     4. See your error
> 
> 
> Please check and feedback.
> Thanks!

yes exactly i tried a first time .....failed rollback and tried another time ....failled again

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @crabbi33 

When you fail to rollback, what a kind of error has been thrown? is it like this one:

![image](https://user-images.githubusercontent.com/23308427/105854338-14718480-5fe7-11eb-8358-8ef3b71720f4.png)

Ping @khouloudbelguith could you please try to reproduce the issue, cause I couldn't reproduce :confused: 

Please check and feedback.
Thanks!

**Comment by crabbi33** [comment]
> 
> 
> Hello @crabbi33
> 
> When you fail to rollback, what a kind of error has been thrown? is it like this one:
> 
> ![image](https://user-images.githubusercontent.com/23308427/105854338-14718480-5fe7-11eb-8358-8ef3b71720f4.png)
> 
> Ping @khouloudbelguith could you please try to reproduce the issue, cause I couldn't reproduce 😕
> 
> Please check and feedback.
> Thanks!

I'm not sure but i think not .....sorry

thanks you

**Comment by khouloudbelguith** [comment]
Hi @hibatallahAouadni, @crabbi33,

I manage to reproduce the issue after a rollback from 177x branch( 1772) => PS1741.
I attached a screen record
https://drive.google.com/file/d/1PvSoA8FvVZR3I_n8z6EuzrRuEZjbj9so/view?usp=sharing
This is an old issue.
After Rollback, some tables are not recovered

- ps_guest
- ps_connections
- ps_connections_page
- ps_connections_source
- ps_statssearch

Steps to reproduce the issue:

1. Install autoupgrade module
2. Make an upgrade
3. Do a rollback
4. Enable debug mode
5. Try to navigate to the BO > Customers page => see error
6. Try to navigate to FO => See error
7. Try to search a product in the FO => See error

You can check also in the Database that those tables do not exist.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by hibatallahAouadni** [comment]
Thanks @khouloudbelguith :rocket:

**Comment by crabbi33** [comment]
> 
> 
> Hi @hibatallahAouadni, @crabbi33,
> 
> I manage to reproduce the issue after a rollback from 177x branch( 1772) => PS1741.
> I attached a screen record
> https://drive.google.com/file/d/1PvSoA8FvVZR3I_n8z6EuzrRuEZjbj9so/view?usp=sharing
> This is an old issue.
> After Rollback, some tables are not recovered
> 
>     * ps_guest
> 
>     * ps_connections
> 
>     * ps_connections_page
> 
>     * ps_connections_source
> 
>     * ps_statssearch
> 
> 
> Steps to reproduce the issue:
> 
>     1. Install autoupgrade module
> 
>     2. Make an upgrade
> 
>     3. Do a rollback
> 
>     4. Enable debug mode
> 
>     5. Try to navigate to the BO > Customers page => see error
> 
>     6. Try to navigate to FO => See error
> 
>     7. Try to search a product in the FO => See error
> 
> 
> You can check also in the Database that those tables do not exist.
> I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
> Thanks!

ok 
yes i can do this 
i ll inform u as soon as possible 

thanks a lot

**Comment by crabbi33** [comment]
So i recovered missing tables
I tried tu upgrade with 1-click upgrade module and again the same error.....
Javascript error (parseJSON) detected for action "upgrademodules"
....
I hate that......

https://zupimages.net/viewer.php?id=21/04/2fgi.png

https://zupimages.net/viewer.php?id=21/04/3qml.png

Nicolas

**Comment by tswfi** [comment]
Just got bit by this also.

1.7.7.1 => 1.7.7.2 failed and after rollback some of the tables were missing and I had to recreate the tables manually. On the bright side those tables don't contain anything important :)

**Comment by papich06** [comment]
> Just got bit by this also.
> 
> 1.7.7.1 => 1.7.7.2 failed and after rollback some of the tables were missing and I had to recreate the tables manually. On the bright side those tables don't contain anything important :)

Hello @tswfi how do you recreate the missing tables ?

do you try with this plugin https://github.com/PrestaShop/pscleaner ?

**Comment by tswfi** [comment]
> Hello @tswfi how do you recreate the missing tables ?

IIRC I checked `show create table ps_whatever` from a clean install and just copy pasted the create statement to the broken db

**Comment by Quetzacoalt91** [comment]
I tried reproducing this issue, without success.
Actually this is because it was being fixed at the moment you reported it with https://github.com/PrestaShop/autoupgrade/pull/369.

Uprading the module to v4.14.1 prevents the tables to be removed.
