### ISSUE TITLE
Register Form on Order Confirmation

### ISSUE THREAD

**Issue by MassimoGS3** [PrestaShop/PrestaShop#22990]
#### Describe the bug

The registration form on order confirmation not work and redirect the user on login page.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.36

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
