### ISSUE TITLE
Unable to create Guest order in Frontoffice is emails addres is already used as account.

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#23007]
#### Describe the bug
If a customer allready have an account in the webshop but the customer wants to checkout with the option "Order as a guest" on the checkout page the page gives the error "The email is already used, please choose another one or sign in" But the customer doesn't want to sign in.

#### Expected behavior
Place an order with the guest account.

#### Steps to Reproduce

1. Creat an accoutn with your email addres
2. Log off
3. Add a product to your cart
4. Try to do a guest chekout with the same emailaddress.

**Screenshots**

<img width="1314" alt="Schermafbeelding 2021-01-27 om 09 36 37" src="https://user-images.githubusercontent.com/6554157/105965020-3f111b00-6083-11eb-8468-ce7e7b67a802.png">

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @mark-app 

This is not a bug! this is the expected behavior!
If the customer is already registred, he should to login not as a guest but as a customer :wink: 
Unless you want to suggest this behavior as a new improvement. If so, I will ping the Product Team.

Please check and feedback.
Thanks!

**Comment by ruchus** [comment]
Hello @hibatallahAouadni,

May be in this case, when a customer try to order as a guest, the alert message could be a bit more exact ?
As for example, "The email belongs to a customer. Please, login."

**Comment by mark-app** [comment]
Hi @hibatallahAouadni ,

My client uses this functionality in there old webshop.

I created a Fix already for myself. Maybe good to implement as new functionality in a new version. Because it's used in other webshop systems too.

In /classes/form/CustomerForm.php in function validate() line 101

Replace 
`$id_customer = Customer::customerExists($emailField->getValue(), true, true);`


For:
```
$passwordField = $this->getField('password');
        if( !$this->guest_allowed || !empty($passwordField->getValue()))  {
            $id_customer = Customer::customerExists($emailField->getValue(), true, true);
        }else {
            $id_customer = 0;
        }
```
        
In /classes/form/CustomerPersister.php funtion create() line 154

Replace 

```
if (Customer::customerExists($customer->email, false, true)) {
            $this->errors['email'][] = $this->translator->trans(
                'An account was already registered with this email address',
                [],
                'Shop.Notifications.Error'
            );

            return false;
        }
```
        
For:

```
if( !$customer->is_guest)  {
            if (Customer::customerExists($customer->email, false, true)) {
                $this->errors['email'][] = $this->translator->trans(
                    'An account was already registered with this email address',
                    [],
                    'Shop.Notifications.Error'
                );

                return false;
            }
        }
```

**Comment by hibatallahAouadni** [comment]
Hello @mark-app & @ruchus 

> May be in this case, when a customer try to order as a guest, the alert message could be a bit more exact ?
As for example, "The email belongs to a customer. Please, login."

@ruchus This is a good idea for an improvement :clap: Could you please submit a new issue (feature), so I can treat it :wink: 
@mark-app could you please make a PR that fix this issue and I will ping the Product Team to study your proposition :wink: 

Thanks guys @mark-app & @ruchus 

Ping @PrestaShop/product-team @mark-app suggest if we can allow the customer to order as guest, is it a good idea?

**Comment by LouiseBonnard** [comment]
Hi there! Why would a customer (with an account already registered) place an order as a guest?

**Comment by ruchus** [comment]
Hi @LouiseBonnard,

I can imagine just a case. When customer doesn't remember that is already customer.
Are you agree?

**Comment by mark-app** [comment]
@LouiseBonnard 

> Hi there! Why would a customer (with an account already registered) place an order as a guest?

When a customer is too lazy to reset his/her password and wants to order with a guest account. It happens all the time in the Netherlands ;)

**Comment by Hlavtox** [comment]
+1 to this one.
I can make a million orders with the same email as a guest, but as soon as I register with it, I suddenly can't.
Same situation when chaging customer's email in BO...

**Comment by ghost** [comment]
> I can make a million orders with the same email as a guest

You just CAN'T do that ... Unfortunately... That's another bug - CAN'T place new order as guest if You already place order in the same shop... 

It's just insane how this software is bugged and developer can't rely on it....

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/issues/10122

**Comment by Hlavtox** [comment]
@PrestaShark Looking into it, shouldn't be hard to fix ;-)

**Comment by Hlavtox** [comment]
@PrestaShark @mark-app @ruchus Done, can you test the PR guys?

Then we would just need to solve:
- That we can't create a guest from BO - https://github.com/PrestaShop/PrestaShop/issues/22645
- That you cannot set an email on a guest account to a registered one, even though these guests can exist just fine - https://github.com/PrestaShop/PrestaShop/issues/25355

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team @Hlavtox provide a PR, so could you please specify this issue ASAP :pray:

**Comment by mark-app** [comment]
Hi,

I missed the update function.

In /classes/form/CustomerPersister.php function update() line 63

Replace : 
```
if ($customer->is_guest || $guest_to_customer) {
            // guest cannot update their email to that of an existing real customer
            if (Customer::customerExists($customer->email, false, true)) {
                $this->errors['email'][] = $this->translator->trans(
                    'An account was already registered with this email address',
                    [],
                    'Shop.Notifications.Error'
                );

                return false;
            }
        }
```
For:


```
if (($customer->is_guest && $clearTextPassword) || $guest_to_customer) {
            // guest cannot update their email to that of an existing real customer
            if (Customer::customerExists($customer->email, false, true)) {
                $this->errors['email'][] = $this->translator->trans(
                    'An account was already registered with this email address',
                    [],
                    'Shop.Notifications.Error'
                );

                return false;
            }
        }
```

**Comment by MatShir** [comment]
@mark-app have a look at @Hlavtox's PR: https://github.com/PrestaShop/PrestaShop/pull/25353
