### ISSUE TITLE
Ambiguous Symfony debug toolbar title for hooks

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#23001]
#### Describe the bug

In DEV mode, the Symfony debug toolbar is available.
In the Symfony debug toolbar, a useful "Hooks" tab has been added. The title for this tab is "hooks called".

For example if you open the "Add/Edit a Brand" Back-Office page, the "Hooks called" tab contains 5 rows:
- actionAdminControllerSetMedia
- displayBackOfficeHeader
- displayDashboardTop
- displayAdminNavBarBeforeEnd
- displayAdminAfterHeader

![Capture d’écran 2021-01-26 à 16 20 02](https://user-images.githubusercontent.com/3830050/105865276-09bcec80-5ff3-11eb-9316-bcbf3a3fe243.png)

A newcomer in PrestaShop ecosystem might think "all right, these are the hooks that are being called on this Back Office page".

⚠️ But **actually what is being displayed here is not "Hooks called".** ⚠️ 

It's rather "Hooks that have a modules listening to them".

A lot more than these 5 hooks are being called. Twenty-three more actually. But these other twenty-three hook calls have no modules "listening" to them.

You can see the "called" and "not called" hooks by clicking on the tab. This will open Symfony debug page for this tab.

So the information is accurate, but the title can be improved.

#### Expected behavior

The tab title should be improved so that people who are new to PrestaShop understand that these are hooks _that have modules plugged on_ (but there is more hooks being called)

#### Steps to Reproduce

1. Go to "Add/Edit a brand" Back Office page.
2. Expand the Symfony debug bar at the bottom (if it has been collapsed) by clicking on it.
3. Move your cursor on the "Hooks" tab to expand it.
4. See, as the screenshot above, in the "Hooks tab" the 5 hooks mentioned "called". This is the issue.
5. You can click on the tab to see all the hooks, the ones "called" and "not called" although these words are not accurate.
 
#### Additional information

* PrestaShop version: 1.7.7

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your issue!
I reproduce the issue with 1.7.7.1 and develop. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request :wink: 

Thanks!

**Comment by matks** [comment]
@hibatallahAouadni I can easily submit a Pull Request to change the name, but I need to know what name should replace the current one.

"Hooks called and received by modules" is explicit but a little long.

Another options is to modify what is being displayed here, and only show 2 numbers: "Hooks called and received by modules"  and "Hooks called and but no modules are plugged on them". Then user must open the tab to see the detailed listing.

Multiple solutions are possible, I just need one to be picked.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers what we should do? rename tha tab to **Hooks called and received by modules** or add another tab **Hooks called and but no modules are plugged on them**?

**Comment by PierreRambaud** [comment]
`Hooks called and received by modules` is a good idea :)
