### ISSUE TITLE
Cant see my var_dump  on admin product page with hookActionProductUpdate

### ISSUE THREAD

**Issue by webconcept06400** [PrestaShop/PrestaShop#23019]
Hi i want debug my code but i cant see any var_dump on this page,

After installing the module and add and save a product

I test with log and the serialize good appear on logs so the hook was trigger, tks for you replys

code : 
public function hookActionProductUpdate($params)
{	
	if (!$this->createProducts($params, 'A'))
		return false;
	return True;
}

public function createProducts($params, $action)
{	
	Logger::addLog(serialize($params), 1, null, null,  null, true);
	var_dump($params);	

}

**Comment by matks** [comment]
Hello, this repository is not a place to ask questions. Please read https://github.com/PrestaShop/PrestaShop/issues/new/choose and follow "I need help" link.
