### ISSUE TITLE
Error on all pages with products  : Undefined index: c_tree_path

### ISSUE THREAD

**Issue by Bahwaimongars** [PrestaShop/PrestaShop#23011]
When I try to browse a page that displays products, I get this error: Undefined index: c_tree_path.

Only when debug is enabled.

Start : 
I click on store > error

Here is a capture of the bug:
![image](https://user-images.githubusercontent.com/62238066/105984267-252f0280-609a-11eb-8dd7-fad5fdb3547f.png)

https://gyazo.com/70e03338705c0973938f0502073e030e

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.23

**Comment by hibatallahAouadni** [comment]
Hello @Bahwaimongars 

Did you delete a root category? 
Please check and feedback.

Thanks!
