### ISSUE TITLE
[UIKit] Switch button behavior is wrong when Yes is checked and button is disabled

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#23021]
#### Describe the bug

![image](https://user-images.githubusercontent.com/14963751/106019043-7e129100-60c2-11eb-97b3-9886419fc39c.png)

When the true input is checked and the button is disabled, you see Yes and No at the same time

#### Expected behavior

Having Yes or No disabled, but not both at same time

#### Steps to Reproduce

1. Go to /configure/shop/preferences/preferences
2. See the yes no switch

* PrestaShop version: develop

**Comment by SimonGrn** [comment]
I don't understand the problem, this quantic button looks perfectly fine to me :trollface:
