### ISSUE TITLE
After collapsing navbar, if I go to legacy BO page and expand navbar, navbar entries have no titles

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#23026]
#### Describe the bug

After collapsing navbar, if I go to legacy BO page and expand navbar, navbar entries have no titles.
![Capture d’écran 2021-01-27 à 18 25 27](https://user-images.githubusercontent.com/3830050/106029166-1c0b5900-60cd-11eb-81eb-c84ed9b9efeb.png)

Symfony pages are OK.

#### Expected behavior

When navbar is collapsed then expanded, no matter what path the user has followed, the navbar should be displayed correctly.

#### Steps to Reproduce

1. Go to Dashboard. Collapse navbar by hitting the top arrow
![Capture d’écran 2021-01-27 à 18 25 12](https://user-images.githubusercontent.com/3830050/106029212-275e8480-60cd-11eb-82f3-2d72aa907916.png)

2. Then go on a legacy (not Symfony) BO page, like "Statistics" or "Carriers".
3. Expand the navbar by hitting the top arrow
![Capture d’écran 2021-01-27 à 18 25 23](https://user-images.githubusercontent.com/3830050/106029350-478e4380-60cd-11eb-853b-43a1c6cbf28c.png)

4. Navbar is expanded, but navbar entries have no titles 😆 
![Capture d’écran 2021-01-27 à 18 25 27](https://user-images.githubusercontent.com/3830050/106029377-4e1cbb00-60cd-11eb-9aed-766873f9fbde.png)

#### Additional information

* PrestaShop version: `develop` branch

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your issue!
I reproduced only with develop. I’ll add this to the debug backlog so that it’s fixed.

Thanks!
