### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#23027]
Fresh install V.4.2.0

After configuration (check and uncheck what we want) the return is error 500

I know it´s relative to theme installed, but even removed every module related, it returns 500

![2](https://user-images.githubusercontent.com/54105234/106038117-6ee61000-60cf-11eb-86a3-2422f52a77f4.JPG)
![3](https://user-images.githubusercontent.com/54105234/106038123-70173d00-60cf-11eb-89bd-7bd3597a2886.JPG)
![Capturar](https://user-images.githubusercontent.com/54105234/106038125-70afd380-60cf-11eb-9a8a-573917fdc228.JPG)

* PrestaShop version: 1.7.6.5
* PHP version:

**Comment by Borgas** [comment]
It´s relative to gsitemap, not prestashop

**Comment by erwansimplon** [comment]
C'est relatif à gsitemap, j'ai eu le même problème.
Dans la fonction getContent la variable de configuration : GSITEMAP_DISABLE_LINKS, ajoute les lien cocher.
Alors que dans la fonction getMetaLink on créé les liens pour les éléments non cochés.
Le correctif pour m'a part à était de changer la ligne 352 sur la version 4.2.0.

j'ai changer cette ligne :
`if (!in_array($meta['id_meta'], explode(',', Configuration::get('GSITEMAP_DISABLE_LINKS')))) {`

En cette ligne : 
`if (in_array($meta['id_meta'], explode(',', Configuration::get('GSITEMAP_DISABLE_LINKS')))) {`
