### ISSUE TITLE
Feature helpbox under faceted search filters

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23032]
#### Context

We could help customers choose and filter the right product, if we provide them a little hint with tips how to choose it, or what that feature means.

#### Solution

We could display a little hint `How to choose` under the filter in faceted search. After click, it would open a popup or un-collapse a text or HTML content.
The user would fill this information in feature or attributte settings in BO, in the specified textarea.
We can also allow him to set up specific title, like **How to choose material**, **What does this mean** , instead of generic **How to choose**.

#### Technical

- Faceted search already adds some inputs to feature form in BO. We would just extend this hooking functionality and add one or two textareas.
- We would add two new columns to **layered_indexable_feature_lang_value**.
- Then, it would be displayed in the template in front office.
  a) Get data in `Block.php` - fetch it in `getFeatureLayeredInfos` and add it to output in `getFeaturesBlock`.
  b) If not empty, pass it through the filter in `Converter.php` - `$facet->setProperty('hint', $filterBlock['hint']);`
  c) Add `{$facet.properties.hint}` to template.
- It would introduce no BC breaks, because older templates would just not display this information.

I would be able to implement it, if @PierreRambaud checks my work, @prestascott says how to implement it (boostrap collapse or popup) and @Julievrz provides proper wording. 🍺😊

#### FO design
![106130928-4d823400-6162-11eb-95d6-4f8ec679aa86](https://user-images.githubusercontent.com/6097524/106135749-a359da80-6168-11eb-8641-5dac99cf8bc9.jpg)

#### BO design
![edit](https://user-images.githubusercontent.com/6097524/106130417-9980a900-6161-11eb-9f23-4b105fcf45a8.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Well done @Hlavtox :clap: this is really great and well detailed improvement report :rocket: 
Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , it would be great if we could add this feature, it will help the client to search with faceted search and the message will be customizable from BO, and it will not introduce any BC. So, do you agree with me?

**Comment by Hlavtox** [comment]
Found a nice example of what it can look like. See the buttons in Product Details section here - https://www.powersupplyshop.co.uk/brands/dell/televisions/81407/adapter-UK-0/

![HELP BOX](https://user-images.githubusercontent.com/6097524/118682909-2b8bea80-b801-11eb-8331-a6f80a45e7ff.JPG)

Ping @marionf :-)
