### ISSUE TITLE
firstname and lastname in address are the same

### ISSUE THREAD

**Issue by KevinDev00** [PrestaShop/PrestaShop#23035]
Hi, 

After updating from 1.7.6 to 1.7.7, an issue came up. When ordering, some clients have the same firstname and surname in the delivery address (example : John John). I made sure they filled the fields correctly. Any idea why this issue came up ?
After some research, I don't think it's an autocompletion issue.

Thanks

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
