### ISSUE TITLE
Problem with rounding after payment via Paypal

### ISSUE THREAD

**Issue by Portolopser23** [PrestaShop/PrestaShop#23041]
#### Describe the bug

This happens in PrestaShop 1.6.0.9
When a customer makes an order via Paypal that involves some products with a large amount of combinations decimal rounding doesn't calculate properly (1 or 2 cents up or down) and the order is set as "Payment error". 
We already fixed the issue on Paypal module editing proccess.php and the payment done by the customer is fine, amounts and everything, but in the orders tab the order status is set as "Payment error" and the customer is sent a "Payment error" email even though he paid the right amount.

Does anyone know how to fix this problem in this PS version? Preferably without updating to newest versions and without changing the rounding selector option.

#### Expected behavior

Payment and order status correctly done and purchase confirmation email being sent to the customer

#### Steps to Reproduce

1. Go to any product that has some combinations and attributes
2. Make order and payment via Paypal
3. Get email error from website as customer and get order status "Payment error" as PrestaShop admin

* PrestaShop version: 1.6.0.9
* PHP version: 5.4.36

**Comment by hibatallahAouadni** [comment]
Hello @Portolopser23 ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by Portolopser23** [comment]
Thanks for the reply!

**Comment by hibatallahAouadni** [comment]
Really sorry :confused: you can also ask for help in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by Portolopser23** [comment]
No worries! I'll send a message in Slack hoping that someone helps. Have a nice day and stay safe!
