### ISSUE TITLE
Add ability to hide or customize KPIs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23047]
#### Is your feature request related to a problem?

KPI bar on top of pages (orders) is taking a lot of space and only some users are interested in it.

#### Describe the solution you'd like

What would you say about an ability to:
- completely hide it
- add a collapse icon so users can hide it when they don't need it
- customize what data users want to see there?

**Comment by florine2623** [comment]
Hi @Hlavtox ,
Thanks for the suggestion, please stay tuned as I ping our product team.
Thank you !

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,
What do you think about @Hlavtox 's suggestion regarding the KPI bar on Order :
![Capture d’écran 2021-01-29 à 11 08 52](https://user-images.githubusercontent.com/16019289/106261836-6a7e3c00-6222-11eb-8a96-eb5f7819f134.png)

Thanks!
