### ISSUE TITLE
Disable/Enable product images

### ISSUE THREAD

**Issue by itsvahid** [PrestaShop/PrestaShop#23045]
#### Is your feature request related to a problem?

It is difficult to delete and upload product images every time instead of disabling/enabling them.

#### Describe the solution you'd like

A button or checkbox to enable/disable the product images. A new field is needed in the ps_image table e.g. is_active. The new field goes into Image.php class and to get only the active images in the FO for the product, the query in getImages() in Product.php needs to filter for is_active field in the where clause.

#### Additional context

I've already implemented this functionality in our company with ajax in the BO in 1.6 but I've checked and the implementation is not different for the PHP and Database. I think it would be a nice feature to have in the Prestashop by default. What do you think?

**Comment by florine2623** [comment]
Hi @itsvahid ,
Thanks for the suggestion.
I'll ping our product team, in the mean time, please stay tuned !
If you have this feature ready, please do send us a pull request!
Thanks!

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,
@itsvahid is suggesting a new feature for the product image, what do you think ?

Thanks!

**Comment by MatShir** [comment]
Now, you can replace an image in the new product page. It is something could solve your pb. 
Could you explain a bit deeper why you prefer disabling them ? Are you still going to use them ?

**Comment by Hlavtox** [comment]
Hi @itsvahid, replacing images should be sufficent. You can open a discussion if needed. Thank you. :-)
