### ISSUE TITLE
Centralize classic microdatas in a file using JSON-LD

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#23046]
#### Is your feature request related to a problem?

Currently, all microdatas are managed in their respective templates of the markup they aim to enrich, this leads to several things :
- It's harder to maintain, because there are a lot of files to inspect in order to change these
- It's harder to override from a template, because the template needs to override tons of tpl files, and it leads to maintainability problems because when we update the classic theme, you need to update several templates only because of microdatas
- It's not respecting seperation of concern as you've a mix between "Shown markup" and "SEO Microdatas" which make templates harder to read and understand

#### Describe the solution you'd like

Having one file, containing every microdatas of the classic theme, that you could override on your template in order to personnalize it way more, fix theme-sided changes.

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers It's an open discuss, because the community submit a PR about this, wdyt ?

I feel like it's a really good improvement for microdatas management of the classic theme

**Comment by NeOMakinG** [comment]
Closing in favor of #22867.

**Comment by hibatallahAouadni** [comment]
Duplicate of #22867
