### ISSUE TITLE
[BO - Responsive] Bad responsivity of customer block

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23053]
#### Describe the bug

Content of customer block in order BO is not very responsive.

#### Expected behavior

It should be readable and scale good. Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/23052

**Screenshots**

![responsive](https://user-images.githubusercontent.com/6097524/106267452-f21b7900-6229-11eb-872e-0240d45cfdba.JPG)

#### Additional information

* PrestaShop version: .1.7.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox 

I was able to reproduce the issue with PrestaShop version 1.7.7.1. I’ll add this to the debug backlog so that it’s fixed.
Thank you for your PR.

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 Thanks!! I made the issue only because @prestonBot was complaining 😄
