### ISSUE TITLE
Let the module set an error message while the upgrade fail

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#23054]
#### Is your feature request related to a problem?

When you try to make an upgrade script for a module, if it's fail, you don't know why.

#### Describe the solution you'd like

Let the upgrade file make something as setError('The error message'); return false; in order to allow the back office show the errors.

#### Alternatives you've considered

No one, there is no one. Make 45 minutes with die() inside my code to have the error, it's was not to be considered. Really not :)

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Do you think that this could be implemented ?

Thanks!

**Comment by PierreRambaud** [comment]
Could you provide use an example, a module to be able to reproduce and be sure we are talking about the same thing? :)

**Comment by PrestaEdit** [comment]
Hi @PierreRambaud ,

There is an example. Add firstly the v1.0.0: 
[pm_example-v1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/5903293/pm_example-v1.0.0.zip)

After that, try to install the v1.0.1 inside the Back Office.
[pm_example-v1.0.1.zip](https://github.com/PrestaShop/PrestaShop/files/5903294/pm_example-v1.0.1.zip)

The goal is to have the error message show in this box, for example:
![Screenshot_2021-02-01 Gestionnaire de modules • 1 7 7 0](https://user-images.githubusercontent.com/2631425/106445147-f2608200-647e-11eb-8e2a-a290a6459002.png)

**Comment by PierreRambaud** [comment]
Thank you @PrestaEdit we will investigate to improve the behaviour

**Comment by kpodemski** [comment]
@PrestaEdit you can throw an Exception. You can find an example module in the attachment.

[dummyupgrade.zip](https://github.com/PrestaShop/PrestaShop/files/6602461/dummyupgrade.zip)

![image](https://user-images.githubusercontent.com/2137763/120890307-1933ee00-c602-11eb-9cf1-cc5a8b713589.png)

**Comment by kpodemski** [comment]
@hibatallahAouadni 

I think no change needed here, and `To Do` to be removed.

**Comment by PierreRambaud** [comment]
Exceptions are not user-centric :thinking:

**Comment by kpodemski** [comment]
Sure but as a module developer there's 99% chance that I need to investigate this issue on Customer's request, all they need to know is that something went wrong with an update, Exception is showing clear message - the only difference would be to remove "Exception thrown by %s" I guess?

**Comment by PrestaEdit** [comment]
You're right, the error will be shown as it.
![image](https://user-images.githubusercontent.com/2631425/120922327-cbce8400-c6c8-11eb-8786-64a1bee9df6f.png)

The only issue with that is that you will not execute the rest of the upgrade file and if the exception occurs at the middle, it could be a mess.
Or, the developper will need to handle it to throw it on the very end in order to make it's exception. It could be a use case, yes.

**Comment by hibatallahAouadni** [comment]
@kpodemski Thanks :slightly_smiling_face: closing the issue as no change is required
