### ISSUE TITLE
Barcode validation uses wrong regexes

### ISSUE THREAD

**Issue by MatTheCat** [PrestaShop/PrestaShop#23058]
#### Describe the bug

I can enter any numeric value as a product barcode as long as it has at most the expected number of digits and it will validate.
Take `1` for example. As per current validation rules it is a valid EAN 13, a valid UPC and valid ISBN.

#### Expected behavior

I cannot enter a barcode in an invalid format.

**Comment by florine2623** [comment]
Hello @MatTheCat ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

I'll close your issue for now, please feel free to open anew one with all details.

Thank you
