### ISSUE TITLE
error with welcome module

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23067]
#### Describe the bug

in a new installation of prestashop 1.7.7.1 the module does not work, it cannot be stopped by clicking on any of the two buttons.
you have to go to deactivate it in the modules tab

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/106403683-2e202b00-6430-11eb-9ca9-d825b8bf8965.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I didn't manage to reproduce your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1KamTBc1z-RRA9Tl2eNn4Cbf1OVk20q3k/view

Please check and feedback.
Thanks!

**Comment by alfonsolr09** [comment]
I still have the same problem, what data can I give you?
I have prestashop in a subdirectory, I don't know if that influences

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

> I have prestashop in a subdirectory, I don't know if that influences

It doesn't! But could you please check your console if there's errors.
Please check and feedback.

Thanks!

**Comment by alfonsolr09** [comment]
How can I do that?

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 just click on **`F12`** button on your keyboard :sweat_smile:

**Comment by alfonsolr09** [comment]
https://youtu.be/lj7h_HcFCPo

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

It seems your issue related to https, could you please check if these options are enabled in your BO:

![image](https://user-images.githubusercontent.com/23308427/106884075-22a75b00-66e1-11eb-9e89-5bc63f02e43e.png)

Please check and feedback.
Thanks!

**Comment by alfonsolr09** [comment]
Are enabled...

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I'm really sorry I can not help you anymore cause I didn't manage to reproduce your issue :confused: 

Sorry, but I have to close the issue, cause, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. And it seems you need help with your shop, so please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by alfonsolr09** [comment]
it's true, the problem was mine. I already solved it, thanks
