### ISSUE TITLE
Update a combination via webservice, it disappears from the carts

### ISSUE THREAD

**Issue by fabiovannini** [PrestaShop/PrestaShop#23060]
1) Create a product
2) Create some combinations
3) Insert a combination in the cart on public side
4) Read this combination from web service 
5) Update read combination from web service (changing something or ANYTHING)
6) This combination left the cart (ALWAYS)

can anyone reproduce this behavior? Is it a problem with myclient or on the web service?

I look in Combination.php class on method deleteAssociations() can be the only responsable, but i don't know why.

Is a bug?

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
