### ISSUE TITLE
error color text in product description

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23064]
#### Describe the bug

when I activate the bullet list the text color changes in the classic theme

#### Expected behavior

same colour

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Edit your product
3. Add a bullet list to your product's summary
4. **Save**
5. Click on **Preview**
6. FO, you can see the bullet list in product page with different color

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/106372327-d66dbb00-636e-11eb-8ec0-fe37bfe96714.png)

#### Additional information

* PrestaShop version:1.7.7.0
* PHP version: 7.2.29

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I reproduced this issue with PS1.7.6.7, PS1.7.7.0 and PS1.7.7.1. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by alfonsolr09** [comment]
in my store I fixed it, I was going to make a pull request, but someone already did it
