### ISSUE TITLE
Webservice: Combination disappear from carts on update

### ISSUE THREAD

**Issue by fabiovannini** [PrestaShop/PrestaShop#23061]
#### Describe the bug

When you read a combination via webservice and update it without any changes (same dto), if this combination is in any Customer cart, it disappear from cart (always). The combination is updated right. Any error is trigged by webservice. Any message displayed to the customer.

#### Expected behavior

The combination must be remain in the cart (respecting business rules and domain logics)

#### Steps to Reproduce

1) Create a product
2) Create some combinations
3) Insert a combination in the cart on public side
4) Read this combination with web service 
5) Update read combination from web service (same read dto unchanged)
6) This combination left the cart (ALWAYS)

---

1. FO> add the **Hummingbird cushion** with **Black** color in the cart
2. In Postman, choose the **PUT** method
3. For the **request URL**, paste this link http://your_site/api/combinations/27 (need to change your_site by yours)
4. Click on the **Authorization** tab
5. Choose **Basic Auth** and paste the WS key in the **Username** and **password**, Save

![image](https://user-images.githubusercontent.com/23308427/106504612-776f8980-64c7-11eb-9650-896fd50502f2.png)

6. Click on **Body** tab and paste this structure

```
<prestashop>
    <combination>
    	<id>27</id>
        <id_product>11</id_product>
        <quantity>300</quantity>
        <reference>17</reference>
        <quantity>300</quantity>
        <minimal_quantity>1</minimal_quantity>
        <associations>
            <product_option_values nodeType="product_option_value" api="product_option_values">
                <product_option_value>
                    <id>11</id>
                </product_option_value>
            </product_option_values>
        </associations>
    </combination>
</prestashop>
```

![image](https://user-images.githubusercontent.com/23308427/106504363-2364a500-64c7-11eb-9f96-b8cb04a1edfe.png)

7. Click on **Send** button
8. Check the FO and refresh
9. See error => the cart has been emptied

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.34

**Comment by fabiovannini** [comment]
#### Read Request

Request method: GET
Request URL: http://mysecretapikey@192.168.1.46/api/combinations/397
Request Body: [empty]

#### Read Response

Response Status: 200
Response body:

**Comment by fabiovannini** [comment]
### GET Request
Method: GET
URL: http://mysecretkey@192.168.1.46/api/combinations/397
Body: 

### GET Response
Status: 200
Body:
````
<?xml version="1.0" encoding="UTF-8" ?>
<prestashop>
<combination>
<id>
<![CDATA[
397
]]>
 </id>
<id_product xlink:href="http://192.168.1.46/api/products/608">
<![CDATA[
608
]]>
 </id_product>
<location />
<ean13 />
<isbn />
<upc />
<mpn />
<quantity>
<![CDATA[
0
]]>
 </quantity>
<reference>
<![CDATA[
Z12072
]]>
 </reference>
<supplier_reference />
<wholesale_price>
<![CDATA[
0.000000
]]>
 </wholesale_price>
<price>
<![CDATA[
24.000000
]]>
 </price>
<ecotax>
<![CDATA[
0.000000
]]>
 </ecotax>
<weight>
<![CDATA[
0.148800
]]>
 </weight>
<unit_price_impact>
<![CDATA[
0.000000
]]>
 </unit_price_impact>
<minimal_quantity>
<![CDATA[
1
]]>
 </minimal_quantity>
<low_stock_threshold />
<low_stock_alert>
<![CDATA[
0
]]>
 </low_stock_alert>
<default_on />
<available_date>
<![CDATA[
0000-00-00
]]>
 </available_date>
<associations>
<product_option_values nodeType="product_option_value" api="product_option_values">
<product_option_value xlink:href="http://192.168.1.46/api/product_option_values/23">
<id>
<![CDATA[
23
]]>
 </id>
</product_option_value>
</product_option_values>
<images nodeType="image" api="images/products" />
 </associations>
 </combination>
</prestashop>
````
### PUT Request (the same read DTO)
Method: PUT
URL: http://mysecretkey@192.168.1.46/api/combinations/397
Body:
````
<?xml version="1.0" encoding="UTF-8"?>
<prestashop>
   <combination>
      <id>397</id>
      <id_product>608</id_product>
      <location />
      <ean13 />
      <isbn />
      <upc />
      <mpn />
      <quantity>0</quantity>
      <reference>Z12072</reference>
      <supplier_reference />
      <wholesale_price>0.000000</wholesale_price>
      <price>24.000000</price>
      <ecotax>0.000000</ecotax>
      <weight>0.148800</weight>
      <unit_price_impact>0.000000</unit_price_impact>
      <minimal_quantity>1</minimal_quantity>
      <low_stock_threshold />
      <low_stock_alert>0</low_stock_alert>
      <default_on />
      <available_date>0000-00-00</available_date>
      <associations>
         <product_option_values nodeType="product_option_value" api="product_option_values">
            <product_option_value>
               <id>23</id>
            </product_option_value>
         </product_option_values>
         <images nodeType="image" api="images/products" />
      </associations>
   </combination>
</prestashop>
````
### PUT Response
Status: 200
Body:
````
<?xml version="1.0" encoding="UTF-8" ?>
<prestashop>
<combination>
<id>
<![CDATA[
397
]]>
 </id>
<id_product xlink:href="http://192.168.1.46/api/products/608">
<![CDATA[
608
]]>
 </id_product>
<location />
<ean13 />
<isbn />
<upc />
<mpn />
<quantity>
<![CDATA[
0
]]>
 </quantity>
<reference>
<![CDATA[
Z12072
]]>
 </reference>
<supplier_reference />
<wholesale_price>
<![CDATA[
0.000000
]]>
 </wholesale_price>
<price>
<![CDATA[
24.000000
]]>
 </price>
<ecotax>
<![CDATA[
0.000000
]]>
 </ecotax>
<weight>
<![CDATA[
0.148800
]]>
 </weight>
<unit_price_impact>
<![CDATA[
0.000000
]]>
 </unit_price_impact>
<minimal_quantity>
<![CDATA[
1
]]>
 </minimal_quantity>
<low_stock_threshold />
<low_stock_alert>
<![CDATA[
0
]]>
 </low_stock_alert>
<default_on />
<available_date>
<![CDATA[
0000-00-00
]]>
 </available_date>
<associations>
<product_option_values nodeType="product_option_value" api="product_option_values">
<product_option_value xlink:href="http://192.168.1.46/api/product_option_values/23">
<id>
<![CDATA[
23
]]>
 </id>
</product_option_value>
</product_option_values>
<images nodeType="image" api="images/products" />
 </associations>
 </combination>
</prestashop>
````

**Comment by fabiovannini** [comment]
If I change this line in this file, the system behaves as expected (the combination remains in the cart). But not knowing the logic applied on Prestashop well, I ask the support team on this change.

**Is this modification safe?!?**

**File:** classes/Combination.php
````
[....]

/**
     * Delete associations.
     *
     * @return bool Indicates whether associations have been successfully deleted
     */
    public function deleteAssociations()
    {
        if ((int) $this->id === 0) {
            return false;
        }
        $result = Db::getInstance()->delete('product_attribute_combination', '`id_product_attribute` = ' . (int) $this->id);
       // why remove the combination from cart?!?
       // $result &= Db::getInstance()->delete('cart_product', '`id_product_attribute` = ' . (int) $this->id);
        $result &= Db::getInstance()->delete('product_attribute_image', '`id_product_attribute` = ' . (int) $this->id);

        if ($result) {
            Hook::exec('actionAttributeCombinationDelete', ['id_product_attribute' => (int) $this->id]);
        }

        return $result;
    }

[....]
````

**Comment by hibatallahAouadni** [comment]
Hello @fabiovannini 

> Update read combination from web service (same read dto unchanged)

You mean after reading the combination by WS, you update it, is that so?

> If I change this line in this file, the system behaves as expected (the combination remains in the cart). But not knowing the logic applied on Prestashop well, I ask the support team on this change.

Could you please made a Pull Request:

![image](https://user-images.githubusercontent.com/23308427/106463296-876f7500-6497-11eb-846d-ded80e47a683.png)

Please check and feedback.
Thanks!

**Comment by fabiovannini** [comment]
> You mean after reading the combination by WS, you update it, is that so?

Exactly

> Could you please made a Pull Request:

A pull request has been opened: https://github.com/PrestaShop/PrestaShop/pull/23081

**Comment by hibatallahAouadni** [comment]
Hello @fabiovannini 

Thanks for the clarification, I reproduced your issue with PS1.7.6.7 and PS1.7.7.0.
I use Postman to launch my WS request and I used the **Hummingbird cushion** with **Black** color in my exmple :wink: 

Here's the steps to reproduce:

1. FO> add the **Hummingbird cushion** with **Black** color in the cart
2. In Postman, choose the **PUT** method
3. For the **request URL**, paste this link http://your_site/api/combinations/27 (need to change your_site by yours)
4. Click on the **Authorization** tab
5. Choose **Basic Auth** and paste the WS key in the **Username** and **password**, Save

![image](https://user-images.githubusercontent.com/23308427/106504612-776f8980-64c7-11eb-9650-896fd50502f2.png)

6. Click on **Body** tab and paste this structure

```
<prestashop>
    <combination>
    	<id>27</id>
        <id_product>11</id_product>
        <quantity>300</quantity>
        <reference>17</reference>
        <quantity>300</quantity>
        <minimal_quantity>1</minimal_quantity>
        <associations>
            <product_option_values nodeType="product_option_value" api="product_option_values">
                <product_option_value>
                    <id>11</id>
                </product_option_value>
            </product_option_values>
        </associations>
    </combination>
</prestashop>
```

![image](https://user-images.githubusercontent.com/23308427/106504363-2364a500-64c7-11eb-9f96-b8cb04a1edfe.png)

7. Click on **Send** button
8. Check the FO and refresh
9. See error => the cart has been emptied

I’ll add this to the debug backlog so that it’s fixed.
Thanks for your pull request :tada: 

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/23081
