### ISSUE TITLE
save customization in themes

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23066]
#### Is your feature request related to a problem?

It is hateful to update prestashop since every time I update I have to apply all the customizations to the theme again

#### Describe the solution you'd like

There should be an option so that the theme does not restart when updating or changing the theme for another theme

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

> I have to apply all the customizations to the theme again

Are you talking about overrides? or you mean that everytime before you upgrade your shop, you need to toggle from your theme to Classic theme, and then after the upgrade you toggle to your theme, is that so?

Thanks!

**Comment by alfonsolr09** [comment]
When you change the theme, all the modifications deleted

**Comment by SimonGrn** [comment]
Do not modify directly the Classic Theme. Use a child theme. Modifying directly the theme is a bad practice as explained in [the documentation](https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/).

The problem you encounter is not an issue from PrestaShop.

**Comment by dennispw** [comment]
> Do not modify directly the Classic Theme. Use a child theme. Modifying directly the theme is a bad practice as explained in [the documentation](https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/).
> 
> The problem you encounter is not an issue from PrestaShop.

I'm pretty sure @alfonsolr09 are experiencing similar issues as reported in https://github.com/PrestaShop/PrestaShop/issues/12933

**Comment by alfonsolr09** [comment]
> > Do not modify directly the Classic Theme. Use a child theme. Modifying directly the theme is a bad practice as explained in [the documentation](https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/).
> > 
> > The problem you encounter is not an issue from PrestaShop.
> 
> I'm pretty sure @alfonsolr09 are experiencing similar issues as reported in https://github.com/PrestaShop/PrestaShop/issues/12933


Just this...
@SimonGrn

**Comment by SimonGrn** [comment]
So it's a duplicate.
I'll close it. If you want informations about this issue, please subscribe to the issue #12933.

Thank you.

**Comment by SimonGrn** [comment]
Duplicate of #12933

**Comment by alfonsolr09** [comment]
Yes, the other request has not been updated for a long time
@SimonGrn

**Comment by SimonGrn** [comment]
> Yes, the other request has not been updated for a long time
> @SimonGrn

This is an open source project, if you feel you can help it, please open a Pull Request.

Thank you !

PS : you don't need to tag me in every message, I receive notifications. Thank you.

**Comment by alfonsolr09** [comment]
Ok thanks
