### ISSUE TITLE
Prestashop features are not being recognized anymore

### ISSUE THREAD

**Issue by Myrjam** [PrestaShop/PrestaShop#23071]
#### Describe the bug
After upgrading from 1.6 to 1.7.7.1 I am not able to save products in the backoffice as features are not being recognised. Features values selected from the dropdownlist are not recognized see image. When selecting a feature the feature values are empty while the are filled in in the Features and Atributes section. In this section I am able to change and save attributes, for non of the exsisting features the values are listed in the product page.
Also newly added features are not shown in de feature list.
#### Steps to Reproduce

1. Go to 'product'
2. change anything
3. click save
4. feature error as shown
**Screenshots**

![image](https://user-images.githubusercontent.com/52692922/106463400-a79f3400-6497-11eb-8bd7-a78c2c1a55f2.png)

#### Additional information

* PrestaShop version: 1.7.71
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Myrjam 

Did you encounter any issue while upgrading?
Please check and feedback.

Thanks!

**Comment by Myrjam** [comment]
No, I don't recall seeing any in the log file.

**Comment by hibatallahAouadni** [comment]
Hello @Myrjam 

While upgrading my shop from 1.6.1.20 to 1.7.7.1, I encountred this issue:

![image](https://user-images.githubusercontent.com/23308427/106482679-f952b900-64ad-11eb-97e8-30e1aa1025cd.png)

After the upgrade process, the store is well upgraded. 
But, unfortunally I enountred a lot of issues:

1. **Problem 1:** I can not access to the BO Products page => resolved when 
2. **Problem 2:** Can not access to FO => #22668
3. **Problem 3:** when I try to access to some pages, an error "Access denied" is displayed => #9513
4. **Problem 4:** it's impossible to access to the Order page or to the Localization page => redirect to Dashboard page

---
Well for your issue, when I tried to edit the product refrence and Save, an error is displayed:

![image](https://user-images.githubusercontent.com/23308427/106484220-b1349600-64af-11eb-8101-4fd08aee6c31.png)

IMO, it's better to ping the Developer Team to invistigate these problems :sweat_smile: 

Ping @PrestaShop/prestashop-core-developers could you please check all these issues :sweat:

**Comment by khouloudbelguith** [comment]
Hi @hibatallahAouadni,

About the third problem access denied, it is reported here: #9513, to fix it: https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961

Thank you!

**Comment by hibatallahAouadni** [comment]
Thanks @khouloudbelguith I updated my comment :wink: 
But I think it's quite impossible to execute that command without bc :confounded:

**Comment by Myrjam** [comment]
I went to the upgrade proces a few times (rolling back in between). I found that it was important upgrading while using the right PHP version...

**Comment by hibatallahAouadni** [comment]
> I found that it was important upgrading while using the right PHP version...

Of course :wink:

**Comment by matks** [comment]
Hi I'm sorry I dont understand what developers are supposed to look at 😅

**Comment by Hlavtox** [comment]
@MatShir Given a goulash that has been made out of this issue, I think we can close it no? :D

The original issue was for upgrades, then some faceted search weird issue was blended in.
