### ISSUE TITLE
Make AdminPatterns controller for migrated page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23077]
#### Is your feature request related to a problem?

This page **/admin/index.php?controller=AdminPatterns** is a huge help when making any form in Prestashop BO.

#### Describe the solution you'd like

I think all devs would be glad to have example of everything, so they don't have to hit-and-miss or search the code for places where it is used in the core.

![test](https://user-images.githubusercontent.com/6097524/106476189-15069100-64a7-11eb-9d79-b58e0692dfe6.JPG)

**Comment by kpodemski** [comment]
Agree, would be great to have these examples based on modern controller.

**Comment by PierreRambaud** [comment]
I think this page should to be removed and we should rely on the [PrestaShop UI Kit](https://build.prestashop.com/prestashop-ui-kit/)

**Comment by Hlavtox** [comment]
@PierreRambaud I did not even know that page exists... nice!

BUT, I still don't know how to generate the resulting code. When I was doing something, it took me 100 years to find out how to select a default key for selectbox, how to set which checkboxes would be checked by default and stuff like this. I knew what I want to do and how the resulting HTML should look like, but I did not know how to throw it to the form generator.

**Comment by PierreRambaud** [comment]
This page doesn't show you how to add form elements :thinking: . With Symfony forms, you have nothing to do ^^

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, I think what you're suggestion is to improve this page **AdminPatterns** to include the implemented UI Kit :wink:  Is that so?

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Hi! It's more for a module developers. So you don't have to search prestashop original forms for a type of field that would suit you. You just open AdminPatters -> find what you want -> look to the code and find that upload field is added by this:

```
            $formBuilder
                ->add('image_file', CustomContentType::class, [
                    'required' => false,
                    'template' => '@Modules/demoextendsymfonyform2/src/View/upload_image.html.twig',
                    'data' => [
                        'supplierId' => $params['id'],
                        'imageUrl' => self::SUPPLIER_EXTRA_IMAGE_PATH . $supplierExtraImage->getImageName(),
                    ],
                ]);
```

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , I think it'll quite useful for the developers to improve this page, wdyt?

**Comment by matks** [comment]
Would https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform be a suitable replacement @Hlavtox ? This is a module you can install, and it creates a BO page where "every possible input you can use with Symfony and PrestaShop" will be displayed.

It's a work in progress.

**Comment by Hlavtox** [comment]
@matks I think that would be exactly what AdminPatterns page did in the past. So, should I close this? :-) I think it would be good if you put it somewhere to the documentation - **"All the available form input types and their respective options are shown in our example module here"**

**Comment by matks** [comment]
We can close it, and indeed when we are done building this module, we'll be able to mark this in every relevant part of the doc 😉

**Comment by hibatallahAouadni** [comment]
@matks @Hlavtox I'm closing this issue :wink:
