### ISSUE TITLE
In multi-store environment, employee permissions incorrectly apply to cart rules

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23082]
#### Describe the bug

Given a multishop-setup with an employee that has access to only one shop and has permissions to create cart rules,
When that employee creates a cart rule,
- he cannot configure shop restrictions for that cart rule (this is ok, since he only has access to one shop)
- the cart rule he created has no shop restriction and is thus valid in all shops

#### Expected behavior

I expect that an employee that is restricted himself to only one shop, only can create cart rules that are restricted to the shop he is assigned to.

#### Additional information

* PrestaShop version: 1.6.1.1 and 1.7.7.1 (and certainly any version in between)
* PHP version: N/A

**Comment by lmeyer1** [comment]
This bug also happens in this case:
- An employee has access to some shop, but not all
- He has permissions to create cart rules in his shops

When he creates a new cart rule and does not select 'shop restriction', 
then the cart rule is valid in every shop.

This is a permission escalation. The cart rules any employee creates should be restricted to the shops he has access to.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

> When that employee creates a cart rule,
> - he cannot configure shop restrictions for that cart rule (this is ok, since he only has access to one shop)
> - the cart rule he created has no shop restriction and is thus valid in all shops

That's true, but I think this is not a bug, it's just PrestaShop limitation :wink: 
Also, the SuperAdmin can always edit the cart rule and add the Shop restruction. But it's super annoying to do this everytime an employee create cart rule :confused: 

So, do you suggest that if an employee only has access to one shop, by default when he create a cart rule, this cart rule will be restricted only to this shop?

Thanks!

**Comment by lmeyer1** [comment]
Yes, a cart rule created by an employee limited to a set of shops should be restricted by default to the same set of shops.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your feedback!
So, your issue is an improvement :wink: 
Let's ping the Product Team. Please stay tuned !

> a cart rule created by an employee limited to a set of shops should be restricted by default to the same set of shops.

Ping @PrestaShop/product-team , what do you think about @lmeyer1 suggestion?

**Comment by lmeyer1** [comment]
I close in favor of #28148, which gives more details and reproducible use cases.

**Comment by hibatallahAouadni** [comment]
Duplicate of #28148
