### ISSUE TITLE
Add a common rich-text class to every tinymce output in FO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23085]
#### Is your feature request related to a problem?

There are a lot of issues and tweaks like this needed. Every field like short decription, long description, cms pages, page category is styled separately.
https://github.com/PrestaShop/PrestaShop/pull/23074/
https://github.com/PrestaShop/PrestaShop/pull/23073/

#### Describe the solution you'd like

Add common class like **rte** or **rich-text** to all fields, that use TinyMCE in BO.
- Product short description
- Product long description
- Category description
- CMS content
etc.

We can unify, tweak and simplify the styling for this content. Properly style lists and headers, add default spacing for paragraphs and headers, make all images responsive automatically, without img-fluid, make nice default styling for tables etc.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

It seems a good idea that the merchant can manage these fields style.
Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , do you think is doable to implement @Hlavtox idea?

**Comment by Hlavtox** [comment]
@hibatallahAouadni Hi! It's not exactly meant at merchants, more to developers.

Now, if you want to style how common paraphraph in merchant's text should look, you need to add CSS separately to short description, long description, cms page, category description etc. If they had one common selector, it would simplify things. :-)

**Comment by NeOMakinG** [comment]
I agree, but there are more problems about this : 

Different list styling are inlined styles on TinyMCE side, and after saving it, it's parsed from PHP and the style is no more present, this means that you can't use every list styles for the moment anyway :/

**Comment by Hlavtox** [comment]
@NeOMakinG Just disable HTML purifier and solved. It does not delete anything from my inputs then...
I would say it's merchants responsibility if he types nonsense and nonvalid code to his inputs. WDYT?

**Comment by NeOMakinG** [comment]
I agree, but I'm not alone to decide on this, @PrestaShop/prestashop-maintainers

**Comment by Hlavtox** [comment]
@NeOMakinG @hibatallahAouadni Already done in theme-refacto

**Comment by NeOMakinG** [comment]
@Hlavtox shouldn't we do it on classic?

**Comment by Hlavtox** [comment]
Nah its dead

**Comment by hibatallahAouadni** [comment]
@Hlavtox could you please mention the PR that fix this issue in the new theme :pray:

**Comment by Hlavtox** [comment]
@hibatallahAouadni Integrated in https://github.com/PrestaShop/theme-refacto/pull/88
