### ISSUE TITLE
DISCOUNT CODE not visible in the backend

### ISSUE THREAD

**Issue by Vo1tech** [PrestaShop/PrestaShop#23089]
Hello,

there is a problem in. If you place a discount code (DC), there is no problem for the customer. DC can be seen on the front end, also can be used, BUT, there is no info in the backend when the order is completed. E.g. The customer bought a coffee, placed voucher called "lotus" so he will recieve LOTUS cookies for free, but I can not see the code in the order so I do not know if this customer used or did not used the voucher. Where is the problem?

Thank you in advance

Regards
Vojtěch from the CZE

**Comment by hibatallahAouadni** [comment]
Hello @Vo1tech 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by Vo1tech** [comment]
Lol, thank you for nothing.
