### ISSUE TITLE
Translation doesn't open 1.7.7.1

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#23086]
#### Describe the bug

When I go to the translation page, I select "Theme translation" and the dropdown menu to choose the theme doesn't show up.

#### Expected behavior

the dropdown menu to choose the theme work 

#### Steps to reproduce

1. BO>Improve>International>Translations
2. In **Modify translations** block
3. Try to open the select => See error

**Screenshots**
Here is a video to show you: https://www.loom.com/share/d65fb300ef8d49bda266f0555adaf401

#### Additional infos
PS version: 1.7.7.1
PHP version: 

It's a fresh installation of 1.7.7.1.

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

Could you please specify your PHP version.
And please next **respect and follow the provided template to submit a complete bug report**.
As you can see I edit your issue :wink:
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
