### ISSUE TITLE
problem update php 7.3 with backoffice prestashop 1.7.0.4

### ISSUE THREAD

**Issue by arg73** [PrestaShop/PrestaShop#23095]
hi

i have a probleme when i update php 7.1 to php 7.3 my backoffice prestashop 1.7.0.4 do not appear 
just a white page
my front office is ok

can you resolve this problem ?

thanks

**Comment by SimonGrn** [comment]
Hello,

PrestaShop 1.7.0.4 is only compatible with PHP 7.1 at most, as you can see in the [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

Please think about following the template next time.

Thank you for your understanding.
