### ISSUE TITLE
Shop associations inconsistent in multi-store environment for Super Admin user, e.g. in cart rules

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23091]
#### Describe the bug

In Prestashop, in an multi-store environment, while creating or editing a user, we can give him access to some shops using the *Shop association* settings in the user profile. For users with a *Permission profile* set to *Super Admin*, the *Shop association* is disabled.

This makes sense the most of the time, since a Super Admin has access to all shops. But in Prestashop exist features that directly rely on the *Shop association* of the employee, and that do not take into account the "special powers" of a Super Admin.

In particular, when creating a cart rules, the shop association is important:
- Only an employee with access to more than one shop has the possibility to select shops in *Restrictions: Shop selection*
- In *Restrictions: Shop selection*, an employee can only select shops to which he has access

All these ways of working together lead to this bug:

The default employee with super admin permission profile lacks the ability to create cart rules restricted to one shop or to a set of shops.

#### Expected behavior

A super admin must be able to create cart rules and have access to all features.

There are two ways to solve the issue:
- The display of shop restrictions in cart rules take into account the fact that a Super Admin has access to all shops, and treats him as if he would be associated with all shops
- In a multi-shop environment, the super admins automatically are associated with all shops (through the table `employee_shop`)

#### Steps to Reproduce

1. Enable *Multistore* in *Shop parameters - General*
2. Create a new shop
2. As an *Super Admin* user go to * Catalog - discounts - Basket rules*
3. Click on *Add new cart rule*
4. On the tab *Conditions*, under *Restrictions*, the option *Shop selection* is missing

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by lmeyer1** [comment]
Related to #23082

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

> The default employee with super admin permission profile lacks the ability to create cart rules restricted to one shop or to a set of shops.

That's not true! Of course the SuperAdmin has the bility to create cart rules restricted to one shop or to a set of shops.

![image](https://user-images.githubusercontent.com/23308427/106582682-8e07f600-6544-11eb-8503-4d0e0143060b.png)

Please check and feedback.
Thanks!

**Comment by lmeyer1** [comment]
You are right, this bug is not reproducible when executing the steps above manually in the backoffice.

The bug happened in my case, because I created the stores with an automatic script, that did not take into account the association between employees and shops.

Sorry for reporting this bug here by mistake.
