### ISSUE TITLE
Unused file ?

### ISSUE THREAD

**Issue by dali-rajab** [PrestaShop/PrestaShop#23104]
i'm just wondering if this file is still used anywhere ??§§??§§ I can't find any call for it in the whole project :
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/facets.tpl

**Comment by matks** [comment]
@dali-rajab I think it's an override of https://github.com/PrestaShop/ps_facetedsearch/tree/dev/views/templates/front/catalog

**Comment by hibatallahAouadni** [comment]
Hello @dali-rajab 

Could you please ask your question in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack) :sweat_smile:  
Cause, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project.
Sorry, I close this issue :wink: 

PS: Thanks @matks for your quick reply :wink: 

Thanks!
