### ISSUE TITLE
"You may be not allowed to download this module." in a local installation

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#23103]
#### Describe the bug

I can't upgrade bought modules on a local installation. I'm logged with the same Addons account as the production site.

#### Expected behavior

As stated here : 
"The module or theme you bought is sold with a single licence, you can use it on one website only. Please fill the field below with the website URL on which the module / theme will be installed. You can install it on a test shop, but this must be the URL of the final website."
I should be able to use the modules in a local copy of the site, so to upgrade them.

#### Steps to Reproduce

1. Install PrestaShop on a local environment.
2. Go to "Modules Manager" on the back-office.
3. Log in with an account on which you have purchased modules.
4. Install a previous version of a bought module (I don't know if this is even possible).
5. Try to update the installed module.

**Screenshots**

![image](https://user-images.githubusercontent.com/48719560/106625572-12736c80-6577-11eb-9716-d7d4ad599d14.png)

#### Additional information

* PrestaShop version: 1.7.5.0
* PHP version: 7.2.33

**Comment by hibatallahAouadni** [comment]
Hello @Kaudaj 

It seems that your issue is not a PrestaShop core bug.
If your module is Ebay Official, please contact support team on [Addons](https://addons.prestashop.com/fr/) or the module Developer.

We will close this issue.

Thanks!

**Comment by tom-combet** [comment]
Actually, my issue occurs with every bought module. The picture with ebay module upgrade was just an example.
Maybe I wasn't clear enough, but that being said, I don't see how this wouldn't concern PrestaShop?

**Comment by matks** [comment]
H @Kaudaj the error says "Error sent from Addons" so it seems the source of the issue is from addons.prestashop.com which is a platform outside of our control. Maybe if you reach out to Addons salespeople they will be able to tell you if there is an issue? 😉

**Comment by hibatallahAouadni** [comment]
Hello @Kaudaj 

Could you please try to upgrade any native module without being connected to Addons MarketPlace and check if you have this issue?
Please check and feedback.

Thanks!

**Comment by tom-combet** [comment]
@matks I have already contacted the PrestaShop Addons chat room who told me to come here.
Maybe I can ask a seller about one of the modules I bought, but I don't really see the point since it's not module specific. I doubt what he will answer me...

@hibatallahAouadni I confirm that I can upgrade the native modules properly without being connected to Addons MarketPlace.
![image](https://user-images.githubusercontent.com/48719560/106634130-c37e0500-657f-11eb-9ded-b67ff5e5deb2.png)

**Comment by hibatallahAouadni** [comment]
@Kaudaj So I think you have an issue either with your connection to Addons MarketPlace or with the module that you are trying to upgrade :wink:

**Comment by tom-combet** [comment]
I also noticed that I can't log in to PrestaShop via this button in the employee form : 

![image](https://user-images.githubusercontent.com/48719560/106718258-177cfe00-6601-11eb-8e44-106c6a8777e2.png)

Once I enter my credentials and I confirm, I get a 405 error and the loading is infinite : 

![image](https://user-images.githubusercontent.com/48719560/106718370-46936f80-6601-11eb-96ec-0ef53f024741.png)

I get this result whether my credentials are correct or not. 
It occurs on the local installation AND on the production site (online).

Could you try it on a fresh PrestaShop 1.7.5.0 install please ?

**Comment by hibatallahAouadni** [comment]
@Kaudaj That bug has been fixed since 1.7.6 :wink: but remember you're always able to connect from **IMPROVE**>**Modules**>**Module Manager** :slightly_smiling_face:

**Comment by tom-combet** [comment]
Okay, thanks for your help.
For bought modules, I will just download them on PrestaShop Addons and upgrade them manually until I manage to fix the issue.

Have a great day.
