### ISSUE TITLE
PrestaShop / ps_socialfollow issue

### ISSUE THREAD

**Issue by mint0r** [PrestaShop/PrestaShop#23111]
#### Describe the bug

The problem with this module is that you can't see all the icons and most of them relate to facebook as you can see in the attached photo

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.34
![err](https://user-images.githubusercontent.com/78450043/106671101-3d2ce780-65ae-11eb-8054-273e455b679a.png)

Please help fix this error

**Comment by hibatallahAouadni** [comment]
Hello @mint0r 

I'm really sorry to inform you that this module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

Thanks!
