### ISSUE TITLE
Unneeded margin on Status, delivery, documents tab

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23112]
#### Describe the bug

On status, delivery, documents tab etc. on order page, there is a hidden card for print purposes. However, it produces unwanted margin on screen.

#### Expected behavior

There should be no extra space produced by `.card`.

**Screenshots**

![card](https://user-images.githubusercontent.com/6097524/106713011-16949e00-65fa-11eb-8b48-9d4875ca8c30.jpg)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
@hibatallahAouadni I added PM and UX label because these things may needs to be specified or designed, it depends!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your issue :sweat_smile: I reproduced the issue with develop and 1.7.7.1
As @NeOMakinG mentioned above this issue need specs :wink: 

Ping @PrestaShop/product-team @PrestaShop/ux-team is it possible to change the style of this card and minimize the margin-bottom?

**Comment by Hlavtox** [comment]
@NeOMakinG @hibatallahAouadni Bump, so it does not make it into 1.7.8 ;-)

**Comment by prestascott** [comment]
Hey everyone!

Thanks for your request @Hlavtox :)

I agree with you, this is 30px extra space for nothing that we can remove.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team waiting for your approval :pray:
