### ISSUE TITLE
Change order status dropdown has bad styling

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23114]
#### Describe the bug

Order status change button on order page has bad styling.

#### Expected behavior

Button text should be centered and proper margins/paddings set. `display: flex; align-items: center;` on parent, some margins on the select inside.

**Screenshots**
Wrong
![button](https://user-images.githubusercontent.com/6097524/106713417-b8b48600-65fa-11eb-9818-b68b56666c88.JPG)

OK
![ok](https://user-images.githubusercontent.com/6097524/106713741-295ba280-65fb-11eb-9352-690e5e430154.JPG)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
@hibatallahAouadni I added PM and UX label because these things may needs to be specified or designed, it depends!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your issue! I only reproduced it with develop. So it's a regression!
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!
