### ISSUE TITLE
Categories have disappeared 1.7.6.9

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#23110]
**Describe the bug**
The categories have disappeared from the admin.

**Expected behavior**
Seeing the categories listed.

**Steps to reproduce**
BO>Catalog>Categories => See error

**Screenshots**
https://prnt.sc/y1w2nz

Additional infos
PS version: 1.7.6.9

**Comment by SimonGrn** [comment]
Hello @ced--ced 
categories don't disappear by themselves. You must have done something. Your issue report is incomplete, please provide more information.

**Comment by matks** [comment]
@ced--ced Reporting a bug is not simply saying "Hi, I see an error in my backoffice" 😉 there is nothing we can do with that. We are not going to login on your backoffice and track the issue behind your empty categories.

If you don't have a reproductible bug like "I install PS 1.7.6.9, I do A then B then C then categories disappear" there is nothing we can do.

**Comment by ced--ced** [comment]
If I had more information or if I was able to tell you what action was taken leading to this, I would have told you.

Can you maybe tell me what file that lists the category need to be checked? Anything that could put me on the track to figure out the problem?

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

Could you please provide your PHP version.
Did you upgrade your shop lately? If so, could you please provide your old version.
And please check your console if there's an error thrown.

Thanks!

**Comment by ced--ced** [comment]
Hi @hibatallahAouadni,

PHP version is 7.3.

The shop has not been updated lately.

I don't have any error in the console, only this text:

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
category.bundle.js?1.7.6.9:108 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

which sends to line 108 of themes/new-theme/public/category.bundle.js?1.7.6.9 in the admin folder.

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

You need to downgrade your PHP version, cause PS1.7.6.9 is not compatible with PHP 7.3 (see our [sysem requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).
Please check and feedback.

Thanks!

**Comment by ced--ced** [comment]
Hi @hibatallahAouadni,

I have got down to PHP 7.2 but the problem is still there.

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

Could you please check your table `ps_category` in your database? if there's no record in this table, it means you delete all your categories by mistake :sweat_smile: 
So, please check and feedback.

Thanks!

**Comment by ced--ced** [comment]
Hi @hibatallahAouadni,

The categories are all there in the database: https://prnt.sc/zd0xsu

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

Sorry for the late response.
I'm really sorry but I didn't manage to reproduce the issue and I can't help you anymore :confounded: 
You seems need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Sorry but I have to close the issue.

Thank you
