### ISSUE TITLE
Page content is covered by header and menu

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23113]
#### Describe the bug

On smaller screens, order buttons are covered by the sticky header. On even smaller resolution, part of the page is covered by the left menu.

#### Expected behavior

This should not happen.
The sticky header in BO is dangerous. It should be remade to use `position: sticky` or something more reliable.

**Screenshots**

![overflow2](https://user-images.githubusercontent.com/6097524/106713162-552a5880-65fa-11eb-978a-a56e6c38ecf5.JPG)
![missing button](https://user-images.githubusercontent.com/6097524/106713166-55c2ef00-65fa-11eb-8121-32a375d60eb3.JPG)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
@hibatallahAouadni I added PM and UX label because these things may needs to be specified or designed, it depends!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your issue. Unfortunally, I didn't manage to reproduce the issue with develop, see the attached screen record below:

https://drive.google.com/file/d/19HLru8bJP1aSxh5f6hMdO4nBUWjfYxoe/view

Did you pull your develop recently, if so, please execute this command:

`cd admin-dev/themes/new-theme && rm -rf node_modules && npm i && npm run build`

Then, clear cache on your Navigator.
Please check and feedback.

Thanks!

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/106721279-bd7e3780-6604-11eb-8a2b-499bee6bb3ce.png)

I still reproduced a strange behavior, I think we should ask for @PrestaShop/ux-team to test it and think about it, @prestascott can we test it and see if we can't improve the responsive of this page on multiple tablets ?

**Comment by Hlavtox** [comment]
@hibatallahAouadni @NeOMakinG Maybe something is wrong with my install. I will keep it open, because you reproduced it in some way. Ok?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Do you still reproduce the issue? Cause I can't.
Could you please check and feedback.

Thanks!
