### ISSUE TITLE
BO responsivity - small header tweaks and bugs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23117]
#### Describe the bug
Header buttons should be aligned to the right. `margin-left: auto; `to the first icon.
There is unnecessary space under the page titlebar.
There is unnecesary space under the header
There is unnecessary scrollbar on the right.
Prestashop logo in the header is covered by the icons on smallest screens - will be a problem on 1st gen iPhone SE and possibly a 12 mini.

**Screenshots**
![responsive](https://user-images.githubusercontent.com/6097524/106718260-18159480-6601-11eb-9542-fd5428aeba33.JPG)
![overflow](https://user-images.githubusercontent.com/6097524/106718262-18ae2b00-6601-11eb-8169-3c9c0f7a4db5.JPG)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

It seems that your develop branch is not updated, cause I didn't manage to reproduce your issue with develop:

**iPhone 6/7/8**

![image](https://user-images.githubusercontent.com/23308427/106732047-831a9780-6610-11eb-9137-f1207c21ca27.png)

**iPhone5/SE**

![image](https://user-images.githubusercontent.com/23308427/106732161-a5acb080-6610-11eb-88ce-afeb8081dda0.png)

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni ok maybe something was badly built 😁 closing
