### ISSUE TITLE
FO - Product / Lower greek list type is not interpreted

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#23124]
#### Describe the bug

In FO the lower greek list type is not correctly interpreted

#### Expected behavior

Every list type should be correctly displayed

#### Steps to Reproduce

1. Go to BO/Product
2. Go to the detail of a product
3. In the summary section add a lower greek list type with two element minimum
4. Click on save and go to the preview of the product
5. See error 

**Screenshots**

lower greek list type applied in BO
![image](https://user-images.githubusercontent.com/40635814/106759875-84a98700-6633-11eb-94b5-65933b74ac4a.png)
But not applied in FO
![image](https://user-images.githubusercontent.com/40635814/106759953-99861a80-6633-11eb-93f6-60e22973e339.png)

#### Additional information

* PrestaShop version: 1.7.6.x, 1.7.7.x, develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
I think a backend dev should look at it, as it looks like tiny mce styles are not saved when submit the product to save, also maybe we'll need to output raw html inside classic

**Comment by hibatallahAouadni** [comment]
Hello @SD1982 

I didn't reproduce the issue with PS1778 and PS1782, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/146399872-aca0f39b-141b-4ff1-9006-e925a4c81e60.png)

![image](https://user-images.githubusercontent.com/23308427/146400376-93af50fc-8e88-4d34-bf08-2e14993a2452.png)

Closing this issue.
Thanks!
