### ISSUE TITLE
[swedish language] Can't save combinations with negative impact on price

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#23120]
#### Describe the bug

When using the swedish language, the negative sign is a − instead of a -
This cause the combinations being unable to save if the price is negative.
Invalid argument: "−20,800000" cannot be interpreted as a number

from /src/PrestaShopBundle/Utils/FloatParser.php line 91

#### Expected behavior

The combination is saved.

#### Steps to Reproduce

1. Make sure to have the shop installed with swedish language
2. Go to product with combination
3. change price to a negative price change on one of the combinations
4. Go back to catalogue
5. go back to product,
6. click save.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Even if you store installed with English language, you're not able to add negative amount/impact price.

If you want to sell a combination with a price less than the original product, you should create a specific price for that combination 😉 

Please check and feedback. 
Thanks!

**Comment by Prestaworks** [comment]
it works prefectly fine to have a negative price inpackt on combinations as long as the - sign works.
I can manually correct the sign in the input box and the save is done as it should. But I don't want to change all the prices to change the stock.

**Comment by Prestaworks** [comment]
I can add that triggering 

$.each($('input.attribute_priceTE'), function () {
          $(this).change();
        });

before submitting the form (save button) will work as the change event on these inputs seems to do something to the data.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Even with Swedish installation, I didn't manage to reproduce your issue with PS1.7.7.1:

https://drive.google.com/file/d/1x_pumO7HGvCPprFn_1AevIyUjYr1mPpq/view

![image](https://user-images.githubusercontent.com/23308427/106760021-a9056380-6633-11eb-9d81-4a55ced00324.png)

Please check and feedback.
Thanks!

**Comment by Prestaworks** [comment]
Hello @hibatallahAouadni 
If you go back to the same product again. (go to product list, and click on the product again to get a page reload) and then try to change the stock. That's when the issue shows up.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Thanks for your feedback!
I reproduced the issue with PS1.7.6.9 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1DK-W9-cZpT0ayeChpK0aefv_cjclJh2j/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Prestaworks** [comment]
This is a suggestion
https://github.com/PrestaShop/PrestaShop/pull/23137
it is ofcourse better to fix the localization packs but this will work until that is done :)

**Comment by jonasburneika** [comment]
@khouloudbelguith hi, sorry but on 1.7.7.8 version we have the same bug on LT language.

**Comment by khouloudbelguith** [comment]
Hi @jonasburneika,


The issue is fixed in PS1780.
Could you please check if you have the same issue with PS1780?

Thanks!

**Comment by jonasburneika** [comment]
hi, @khouloudbelguith 
sorry, I didn't notice that the newer version has a solution. I will check with newest version
