### ISSUE TITLE
New hooks in Admin Order Index

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#23134]
I have some suggestions for hooks on the new Admin Order Index page **(introduced in 1.7.7.X).**

- Modules should be able to do order bulk actions.
- Modules should be able to hook things in order index header and footer
- Modules should be able to add/remove/modify order list cols

Yes, there is an option to override the admin templates, but I belive hooks is easier and should be an option. Hooks also makes it possible to have multiple modules working together. (not overriding the same template etc.)

**Hook positions to be considered:**

![Screenshot 2021-02-04 at 08 42 37](https://user-images.githubusercontent.com/30602638/106864305-f7fdd800-66c9-11eb-96e5-5c6b42f9c32e.png)

PS 1.7.7 and above

**Comment by kpodemski** [comment]
Hey @onklmaps 

> Modules should be able to do order bulk actions.

https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/work-with-bulk-actions/#how-to-add-bulk-actions-from-module

> Modules should be able to hook things in order index header and footer

https://github.com/PrestaShop/PrestaShop/pull/22980

> Modules should be able to add/remove/modify order list cols

https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/modify-grid-in-module/

Everything is available 😎

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Thanks for your issue! But it seems everything you asked for it is available as @kpodemski mentioned above :wink: 
So, I close this issue :slightly_smiling_face: 

@kpodemski thanks for your quick reply :rocket: 

Thanks!
