### ISSUE TITLE
Encoding error on autoupgrade module

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23147]
#### Describe the bug

![image](https://user-images.githubusercontent.com/62474824/106955006-e3a2f500-6734-11eb-8217-22375b26fc3f.png)
![image](https://user-images.githubusercontent.com/62474824/106955011-e6054f00-6734-11eb-87e7-6f1062ee044d.png)

#### Steps to Reproduce

1. Go to autoupgrade module
2. Click on local file
3. See error

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
Thanks for your report.
I have reproduced this encoding issue in PS 1.7.7.1, 1.7.7.0 and 1.7.6.5.
I'll add this to the debug roadmap.
Thanks!

**Comment by NeOMakinG** [comment]
Should be done backend side

**Comment by marionf** [comment]
Hello @alfonsolr09 

We are currently working on the new version of the upgrade module and this sentence will be removed, so I close your issue.

Thank you for raising this problem
