### ISSUE TITLE
Google Sitemap Module - URLs in sitemap created - consisting of -.html Only

### ISSUE THREAD

**Issue by ecojo** [PrestaShop/PrestaShop#23150]
#### Describe the bug

GSC is reporting that my sitemaps have -.html URLs generated from google sitemap module (attached below)

#### Expected behavior

Urls having unknown source and have not added any URLs with '-'.html as their only format.

#### Steps to Reproduce

1. Go to site map URL -https://wesupplement.com/1_en_0_sitemap.xml
2. Search for com/en/-.html
3. View URL entry error
<url>
<loc>
<![CDATA[ https://wesupplement.com/en/-.html ]]>
</loc>
<changefreq>daily</changefreq>
<priority>0.9</priority>
</url>

**Screenshots**

![image](https://user-images.githubusercontent.com/3776258/107005495-b0d61c80-6787-11eb-8a7b-ea26cf0f98c4.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hi @ecojo ,
Can you give more info about the affected product ?
And the steps to reproduce the issue ?
Thanks!

**Comment by ecojo** [comment]
Hi @florine2623 

I am unsure where there url entries in the sitemap occured from 

It is possible that the URL entries like **com/en/-.html**  occurred when 

- a product was added to prestashop in offline mode
- switched to online mode to save
- and then deleted a blank product record that was generated by the above first two steps was deleted from the ps_products table manually
- then ran generate sitemap to generate listings

This was the last known work I was doing on store.

I have reinstalled googlesitemap module and the same **-.html** url entries still occur. 
I am unable to replicate more URLs being generated like this currently though.

Best Regards
David

**Comment by florine2623** [comment]
Thanks for the steps.

I have reproduce the issue.
Deleting a product via the database is not secure and should be done. Next time, please delete the product directly from the product page in BO.

To fix this :
you need to add again the product to your database with the affected ID
delete the product from your BO
regenerate sitemap
see sitemap doesn't have the -.html url

I'll close your issue.
Thanks!

**Comment by ecojo** [comment]
Thanks @florine2623 unfortunately I don't have the product ids of the entries that were deleted.
