### ISSUE TITLE
CMS pages are not orders properly in sitemap

### ISSUE THREAD

**Issue by JevgenijVisockij** [PrestaShop/PrestaShop#23168]
#### Describe the bug

CMS categories are not ordered correctly in sitemap page.

#### Expected behavior

They should be ordered correctly.

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/47781757/107146697-78366e80-6952-11eb-9247-a569aa2437c6.png)

As found by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/22476#issuecomment-773217278
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8(develop)
* PHP version: 7.2

**Comment by alfonsolr09** [comment]
i can't reproduce it on 1.7.6.4 
![image](https://user-images.githubusercontent.com/62474824/107152324-99ee2080-6967-11eb-92a0-fe03041e2463.png)
![image](https://user-images.githubusercontent.com/62474824/107152325-9c507a80-6967-11eb-927e-0a0b32a2ef00.png)

**Comment by JevgenijVisockij** [comment]
Hey, it seems you tried it with CMS pages, but the issue is specifically with CMS Categories not displaying in the correct order.

**Comment by hibatallahAouadni** [comment]
Hello @JevgenijVisockij 

I reproduced the issue with develop, PS1.7.6.7 and PS1.7.7.1, see the attached screenshots below:

- **BO:**

![image](https://user-images.githubusercontent.com/23308427/107201270-0ebd6b00-69f9-11eb-97ac-ca2cf55892bf.png)

- **FO:**

![image](https://user-images.githubusercontent.com/23308427/107201283-11b85b80-69f9-11eb-8165-dc03ad5290e9.png)

It seems the system display the Categories Pages ordered by their ids and not by their positions.
I'll add this to our debug backlog and thanks for your PR.

Thank you
