### ISSUE TITLE
The left menu in BO disappeared after upgrade to 1.7.7.1

### ISSUE THREAD

**Issue by conderus** [PrestaShop/PrestaShop#23166]
#### Describe the bug

After upgrading Prestashop from 1.7.6.8 to 1.7.7.1 by 1-Click Upgrade (the newest version), left admin BO menu disappeared. It happened when I turned on cache again. It was not possible to turn if off, as there was no menu. I use CacheApc. The only solution was to go to parameters.php and set 'ps_cache_enable' => false, . Then menu works again. Please fix this. 

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.23

BR,

**Comment by conderus** [comment]
Hm, and when I turned it off, and tried to turn it on again, I can't log in at all to BO, even if it's turned off now. I have Internal Server Error 500, I have this below .. 

```
(1/1) ContextErrorExceptionWarning: Use of undefined constant _PS_ENV_ - assumed '_PS_ENV_' (this will throw an Error in a future version of PHP)
--
in index.php line 74
```

**Comment by hibatallahAouadni** [comment]
Hello @conderus 

That's weird, this bug has been fixed with PS1.7.7.1, see #22250
Before upgrade, didn't you disable the CacheApc (from BO)?

Thanks!

**Comment by conderus** [comment]
I disabled CacheApc before upgrade, and I tried twice to upgrade this. I have now downgraded this and I don't know what is the problem in my case.

**Comment by hibatallahAouadni** [comment]
Hello @conderus 

What was your PHP version before upgrade?

Thanks!

**Comment by conderus** [comment]
I didn't change it, and it was before and after 7.3.23

**Comment by hibatallahAouadni** [comment]
Hello @conderus 

Well, as you can see in our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) PS1.7.6.8 is not compatible with PHP 7.3
You should downgrade your PHP version to 7.2 cause it's compatible with both 1.7.6.8 and 1.7.7.1

But, I'm not sure that the PHP version is the cause of problem.
So, let's ping the Developer Team :wink: 

Ping @PrestaShop/prestashop-core-developers could you please check this issue, is the PHP version the cause of this problem?

**Comment by conderus** [comment]
Ok thank you I didn't notice this, so now I have 7.2.34 , but I am afraid to try upgraded this 3rd time shop has 12GB and I have to delete all and upload again all after each failed upgrade xd, maybe I will wait for dev team if it could be the problem

**Comment by matks** [comment]
@conderus APC messes up the upgrade process.

The upgrade process takes the php files of your 1.7.6.8 shop, and replace them with the files for a 1.7.7.1 shop. After the upgrade, some of these new 1.7.7.1 php files need to be run.

However when you have APC turned on ; **the new version of the php files is not acknowledged**. Because APC Cache has stored the old version of the php files and so your application tries to run "1.7.7.1 logic" while using the 1.7.6.8 files. So it messes up your shop.

I strongly recommend disabling APC before doing the upgrade, then perform the upgrade, then clear APC cache (if there is still one) and turn it on again.

**Comment by hibatallahAouadni** [comment]
Hello @conderus 

Could you please diable the APC before the upgrade (as @matks mentioned above) and try to upgrade.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @conderus ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by MouadhAouitiDev** [comment]
i have the same prob on 1.7.8 (  BO not found after 1.7.8 )migration) `
![tetest](https://user-images.githubusercontent.com/39631392/177329030-1a635678-551d-4fc7-bf3f-0945fb70257f.PNG)
`
