### ISSUE TITLE
Improve watermark performance

### ISSUE THREAD

**Issue by mojtabamalaekeh** [PrestaShop/PrestaShop#23164]
https://github.com/PrestaShop/PrestaShop/blob/a83d9eadfaac3d031b545fdac42615b2983e0c83/controllers/admin/AdminImportController.php#L1284

Hello,
I think calling actionWatermark hook should be moved outside of the images_types foreach.
Because:
1. id_image_type has not been sent as a parameter.
2. Watermark module - itself - will loop through all image types in hookActionWatermark function.
So there is no need to call actionWatermark hook for each image type and it's enough to call it once after all image types have been generated.
![actionWatermark](https://user-images.githubusercontent.com/18350986/107114806-042a9680-687e-11eb-8929-53c631ea4ae4.png)

Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @mojtabamalaekeh 

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.

Also let us know if you are voluntary to maintain this module.

Thanks!

**Comment by mojtabamalaekeh** [comment]
Thanks for your attention.
I'm not talking about watermark module. But about calling actionWatermark hook in "AdminImportController.php".
This hook may be used in commercial image regenerator modules and it's better to called in proper place.
Regards.

**Comment by hibatallahAouadni** [comment]
Hello @mojtabamalaekeh 

I'm really sorry for closing your issue.
So, what you suggest is to call the hook outside of the loop, is that so?
If you apply this change, is there any BC (break changes)?
Please check and feedback.

Thanks!

**Comment by mojtabamalaekeh** [comment]
Hello and thank you again.
Yes, I suggest that.
I'd tested this change with PrestaShop 1.7.6.2 and 1.7.6.7 and no problem found.
Regards.

**Comment by hibatallahAouadni** [comment]
Hello @mojtabamalaekeh 

All right then, thanks again for your suggestion.
The Developer Team will take a look, please stay toned.

Ping @PrestaShop/prestashop-core-developers I think it's a great suggestion cause it will reduce the execution time, do you agree with me?

**Comment by PierreRambaud** [comment]
I agree, the hook call has nothing to do in the foreach :thinking:

**Comment by hibatallahAouadni** [comment]
@PierreRambaud Great :tada: so shall I change the label to **`To Do`** or we need approval from the Product Team?

**Comment by jonasburneika** [comment]
Hi @hibatallahAouadni I want to point out, that the watermark regeneration method `_regenerateWatermark ` https://github.com/PrestaShop/PrestaShop/blob/4e0d57b00ea36af5b3db14a9aab4d5d29c8b090f/controllers/admin/AdminImagesController.php#L610 will not happen if the method  `_regenerateNewImages` https://github.com/PrestaShop/PrestaShop/blob/4e0d57b00ea36af5b3db14a9aab4d5d29c8b090f/controllers/admin/AdminImagesController.php#L675 returns any errors. This was in my case when one of the products didn't have an image file.
