### ISSUE TITLE
Nginx Failed opening required '/home/nginx/domains/asd.ro/public/var/cache/dev/appParameters.php'

### ISSUE THREAD

**Issue by dandumit** [PrestaShop/PrestaShop#23163]
#### Describe the bug
I have installed and was working for some basic steps presta 1.7.7.1 
After this I get this error 

Warning: require_once(/home/nginx/domains/asd.ro/public/var/cache/dev/appParameters.php): failed to open stream: Permission denied in /home/nginx/domains/asd.ro/public/config/bootstrap.php on line 87

Fatal error: require_once(): Failed opening required '/home/nginx/domains/asd.ro/public/var/cache/dev/appParameters.php' (include_path='/home/nginx/domains/asd.ro/public/vendor/pear/pear_exception:/home/nginx/domains/asd.ro/public/vendor/pear/console_getopt:/home/nginx/domains/asd.ro/public/vendor/pear/pear-core-minimal/src:/home/nginx/domains/asd.ro/public/vendor/pear/archive_tar:.:/usr/local/lib/php') in /home/nginx/domains/asd.ro/public/config/bootstrap.php on line 87

file appParameters.php it's there but has no permission. I don't know how to investigate this ...

 

I have tried 

chown nginx:nginx /home/nginx/domains/yourdomain.com/public/ chown -R nginx:nginx /home/nginx/domains/yourdomain.com/public/

 but after some time happened again. I guess that it's being rewritten that file

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.29
* NGINX

**Comment by PierreRambaud** [comment]
Hi,
Did you check if your php-fpm user is the same as Nginx?
Did you also check what is your umask settings?

Kind regards

**Comment by hibatallahAouadni** [comment]
Hello @dandumit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
