### ISSUE TITLE
Error at order page

### ISSUE THREAD

**Issue by anthus0204** [PrestaShop/PrestaShop#23162]
prestashop 1.7.7.1 php7.4

I get this error when i get to the order page

(1/1) ContextErrorExceptionNotice: Trying to access array offset on value of type null
--
in 35655e6409b6198f29dd6e732ef9598dec599880_2.module.psshoppingcartpsshoppingc.php line 118
at content_601db31c093a07_51229141()in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode()in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render()in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute()in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch()in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in Module.php line 2480
at ModuleCore->fetch()in ps_shoppingcart.php line 99
at Ps_Shoppingcart->renderWidget()in Hook.php line 995
at HookCore::coreRenderWidget()in Hook.php line 947
at HookCore::exec()in smarty.config.inc.php line 167
at smartyHook()in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call()in 2ae29e696ce79279c148b361b153bebd51a990af_2.file.header.tpl.php line 136
at Block_1882398205601db31bf3aa74_05441267->callBlock()in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock()in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process()in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock()in 2ae29e696ce79279c148b361b153bebd51a990af_2.file.header.tpl.php line 37
at content_601db31bf3e3d2_43691015()in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode()in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render()in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender()in e76890f8553df724b4d19aa59a1f41021121775a_2.file.header.tpl.php line 43
at Block_1190873583601db31bf31671_77018887->callBlock()in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock()in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process()in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock()in e76890f8553df724b4d19aa59a1f41021121775a_2.file.header.tpl.php line 27
at content_601db31bf32058_08171122()in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode()in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render()in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender()in f30a8288b6e6ac1a09d430b5b6fef59dbd9f841c_2.file.checkout.tpl.php line 154
at Block_206436008601db31bee7ce5_34612322->callBlock()in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock()in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process()in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock()in f30a8288b6e6ac1a09d430b5b6fef59dbd9f841c_2.file.checkout.tpl.php line 56
at content_601db31bef0e45_47201700()in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode()in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render()in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute()in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch()in SmartyDev.php line 40
at SmartyDev->fetch()in FrontController.php line 704
at FrontControllerCore->smartyOutputContent()in FrontController.php line 686
at FrontControllerCore->display()in Controller.php line 326
at ControllerCore->run()in Dispatcher.php line 518
at DispatcherCore->dispatch()in index.php line 28

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @anthus0204 

Please downgrade your PHP version to 7.3, cause PS1.7.7.1 is not compatible with PHP 7.4 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).
And please next time, **don't just paste your error leaving the provided template empty, you need to fill these blocks** :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @anthus0204 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
