### ISSUE TITLE
can't change theme on dev

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23170]
#### Describe the bug

when i try to change the theme i get an error
when you install the store you can change from the classic theme to another, but when you try to change from that other theme to the classic the error occurs

#### Steps to Reproduce

1. Go to design
2. Click on change theme
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/107157083-6bca0a00-6982-11eb-95b3-8701f34a2cdd.png)
![image](https://user-images.githubusercontent.com/62474824/107157105-87351500-6982-11eb-8bb5-47a2f24d7fb9.png)
![image](https://user-images.githubusercontent.com/62474824/107157106-89976f00-6982-11eb-9969-5423cfe6d621.png)

#### Additional information

* PrestaShop version: 1.7.8 (develop)
* PHP version: 7.3.26

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I didn't manage to reproduce your issue with develop, see the attached screen record below:

https://drive.google.com/file/d/1J8723WCk-W5fa94UobI_GwPwJWbPn8HN/view

It seems your develop branch is not updated or you applied some change on it :wink: 
Please check and feedback.

Thanks!

**Comment by alfonsolr09** [comment]
I think the error appears when theme has some modules ...

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Could you please specify which modules?

Thanks!

**Comment by alfonsolr09** [comment]
the error occurs when the active template has specific modules.

the theme is purchased through addons

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

> the error occurs when the active template has specific modules.
the theme is purchased through addons

So, it's not a Core bug, it's related to your theme and you should to contact the Theme developer.
Try to disable the modules and then change the theme, I think it won't throw any error :wink: 

Well, I have to close the issue cause it's not related to Core :slightly_smiling_face: 
Feel free to open a new issue, if you encounter any other problem with PS Core :wink: 

Thanks!

**Comment by alfonsolr09** [comment]
the error happens with all the themes that I have, it is rare that it is a problem with all the themes (in the current versions they work perfectly)
@hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 ok :confused: did you try to disable these modules (related to theme) before changing the theme?

**Comment by alfonsolr09** [comment]
This night i will try and tomorrow say to you

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 thanks :wink:
