### ISSUE TITLE
Ubable to edit order in BO

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#23189]
#### Describe the bug

I am unable to edit order due the error in `\PrestaShop\PrestaShop\Core\Cart\Calculator::__construct`

#### Expected behavior

Edit without error.

#### Steps to Reproduce

1. Go to Back Office and list orders.
2. Try to edit order.
3. See error.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/3767861/107359830-73e68e80-6ad5-11eb-95a2-3815b9856ab2.png)

#### Steps to fix

Force `int` value of `$currency->precision` in https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/src/Core/Cart/Calculator.php#L104 because \PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision requires an `int` in first argument (https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/src/Core/Localization/CLDR/ComputingPrecision.php#L41).
```
$computePrecision = (new ComputingPrecision())->getPrecision((int)$currency->precision);
```

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

Did you upgrade your shop lately? if so, what was your PS version?
And did you delete some currencies?
Please check and feedback.

Thanks!

**Comment by Flower7C3** [comment]
I have updated PS yesterday to 1.7.7.1 version. Bug was also in 1.7.7.0. My client did not deleted any currencies recently.

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 

The error in your screenshot indicates that you had an issue with the Localization, which means that you removed a language or a currency that was in use.
Could you please check this issue #22611 cause it seems similar to yours.

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @Flower7C3 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by lthienard** [comment]
I have the same problem on my PS 1.7.7.7

`Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision() must be of the type int, null given, called in /classes/Context.php on line 467`

The customer has no baskets due to the use of a basket cleaning module ... can it come from there? 

This error appears when I want to add a reduction to the order

**Comment by lthienard** [comment]
If i force getPrecision(2) i have this message: "**Could not find the product in cart, meaning Order and Cart are out of sync**"

**Comment by Laimonas-Mituzas** [comment]
Check the 'ps_cart' does the 'id_currency' has valid values. In my case it was "0". Changed to "1" - fixed. See your values according to 'ps_currency' table.
