### ISSUE TITLE
Missing VAT Number at order detail backoffice 1.7.7.1 

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23193]
To Reproduce
Go to orders
Click an order.
At the left you'll get the customer address.
On 1.7.6 you were able to see vat number.
On 1.7.7.1 it doesn't show up.

I understand that it's missing on:
/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig

What can I do to bring VAT back?

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22830. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22830
