### ISSUE TITLE
schema.org error in products out of stock when stock management is disabled

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23199]
#### Describe the bug

schema.org error in products out of stock when stock management is disabled.

When you deactivate the stock management and a product is in negative stock, instead of showing this
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/InStock" />
```

this other wrong code is shown
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/PreOrder" />
```

#### Expected behavior

I think the product should be shown in stock

#### Steps to Reproduce

1. Go to disable stock management
2. Increase stock on a product
3. See good on source code

4. Reduce the stock of the same product to 0
5. See error on source code

**Screenshots**

https://youtu.be/ogvmNO3m7SY

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.1, develop (1.7.8.0)
* PHP version: 7.2, 7.3

**Comment by alfonsolr09** [comment]
![image](https://user-images.githubusercontent.com/62474824/107446861-8e555200-6b3f-11eb-9d0e-52a0d8639870.png)
I added that code that makes pre-order only trigger if stock management is on.

I need to make it show 'in stock' when stock below 0 is met and stock management is disabled, but I don't know how to do it. (strikethrough)

I would like to create a pr, but I don't understand much of programming

**Comment by alfonsolr09** [comment]
ok i tried and fixed it, you can try it.
If you authorize me, I can create a pr

![image](https://user-images.githubusercontent.com/62474824/107448745-919e0d00-6b42-11eb-8a3c-fa223858bc6b.png)

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I reproduced the issue with PS1.7.7.1 and develop. I’ll add this to the debug backlog so that it’s fixed.
But I think we may need The Product Team to specify the value of this attribute **seoAvailability**. Let's ping them :wink: 

Ping @PrestaShop/product-team what do you think about @alfonsolr09 proposition? setting the **seoAvailability** value to **outOfStock**?

> If you authorize me, I can create a pr

Ofc, you can :rocket: , please do send us a pull request!

Thanks!

**Comment by alfonsolr09** [comment]
I don't know if `Configuration::get('PS STOCK_MANAGEMENT '))` its correct or not. 

it is working with that solution but i dont know if it is the right thing

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/29411
