### ISSUE TITLE
Copying language to new created one 1.7.7.1

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#23196]
Hi,

A new theme has been installed.

I go to the translations page and I want to copy the French language pack from the classic theme to the new theme.

I get the error:

Cannot copy ".../public_html/themes/classic/lang/fr.php" to ".../public_html/themes/my_new-theme/lang/fr. php ".
Only part of the data was copied, one or more translation files were not found or copied

If I look in the classic theme folder, there isn't any lang folder.

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16132. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #16132

**Comment by ced--ced** [comment]
Thanks @hibatallahAouadni, I have subscribed.

Although this other ticket has been open in Oct 2019. That's a long time ago.
