### ISSUE TITLE
Webservice not respecting explicit order_row prices

### ISSUE THREAD

**Issue by dvalenzuela-com** [PrestaShop/PrestaShop#23197]
#### Describe the bug

When creating a new order via the WebService API, prestashop does NOT respect the given prices and instead uses the ones internally stored by prestashop. They also cannot be updated using a PUT request.

#### Expected behavior

If an Order is created (or updated via a PUT request) and a unit_price is given for one or more order_rows, they should be included in the order.

#### Steps to Reproduce

1. Create a cart
2. Create an order for the given cart, where at least one product has the fields unit_price defined with an X price, different than the one stored in prestashop
3. POST the new order
4. See the returned XML or go to the order in the back office and see the price NOT being used.

**Screenshots**

<img width="636" alt="Captura de Pantalla 2021-02-09 a la(s) 15 50 57" src="https://user-images.githubusercontent.com/12001900/107412672-a355c500-6aee-11eb-81b9-06645b1abc87.png">

#### Additional information

This issue happens to other people too, e.g. https://www.prestashop.com/forums/topic/1026087-add-order-by-webservice-forcing-product-prices/ 

* PrestaShop version: 1.6
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
