### ISSUE TITLE
No  Read more description of the category in prestashop 1.7.7

### ISSUE THREAD

**Issue by Gregg212x** [PrestaShop/PrestaShop#23208]
@SimonGrn I have a question  Do you think adding a function where you can hide part of the category description can be useful for users?
This functionality was in the old version of prestashop 1.6

In prestashop 1.7 you can display only the whole description of the category, which is problematic because with a long description to see the product you have to scroll the page for a long time.

Why do you automatically close a thread that may be important to some users?

If you don't want to work on this feature to solve the problem, let others do it.

`{if $category.description} 
<div id="category-description" class="text-muted">{$category.description nofilter}</div>
{/if} 
{if $category.image.large.url} <div class="category-cover"> 
<img src="{$category.image.large.url}" alt="{$category.image.legend}"> </div>
 {/if}`

**Comment by SimonGrn** [comment]
Hello,

please use the template.
