### ISSUE TITLE
No puedo guardar los productos

### ISSUE THREAD

**Issue by YerayC78** [PrestaShop/PrestaShop#23203]
Tengo instalada la versión 1.7.7.1 del Prestashop, y cuando intento guardar un cambio en un producto, se queda bloqueado con el icono circular que indica que está guardando (adjunto archivo)
![Fallo al guardar un producto](https://user-images.githubusercontent.com/78850868/107497795-e82f3980-6b8a-11eb-83dd-e0afcdc772ee.jpg)
.
Tampoco me permite eliminar características.
Ruego me ayuden, porque tengo mi tienda bloqueada debido a este problema

Gracias y un saludo

**Comment by hibatallahAouadni** [comment]
Hello @YerayC78 ,

Please send your request in English. English is the norm on GitHub.
And **you must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
