### ISSUE TITLE
How add read more description of the category  in prestashop 1.7.7

### ISSUE THREAD

**Issue by Gregg212x** [PrestaShop/PrestaShop#23207]
How can I add "read more" button in description of the category  in prestashop 1.7.7
I want to hide 80% of the text under the button

/templates/catalog/listing/category.tpl   
its only 

`   {if $category.description}
         **<div id="category-description" class="text-muted">{$category.description nofilter}</div>**
      {/if}
      {if $category.image.large.url}
        <div class="category-cover">
          <img src="{$category.image.large.url}" alt="{$category.image.legend}">
        </div>
    {/if}`

In the older version of prestashop there was such a possibility

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Gregg212x** [comment]
@SimonGrn SimonGrn In your opinion this is not a new feature??
This functionality was in version 1.6
