### ISSUE TITLE
Stylesheets and Javascripts missing!! help me!!!!!

### ISSUE THREAD

**Issue by matteocostantini** [PrestaShop/PrestaShop#23202]
#### Describe the bug

I've upgrade a test  environment from 1.7.7.0beta1 to 1.7.7.1. following manual upgrades. It's ok, but I've  troubles about module' stylesheets and javascripts references. Are not present. Not overrides!!
For example not present the shopping cart ajax javascript and others references. I delete all cache folders and browser cache. but no results . Are present only default references inserted from FrontControllerCore class (core.js, theme.js, theme.css).

####Please Help Me!!

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by matks** [comment]
Hi @matteocostantini if you need help, please follow the link https://devdocs.prestashop.com/1.7/faq/i-need-help/
