### ISSUE TITLE
Comment no longer appear after upgrading from 1.6.1.24 to 1.7.7.x

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#23218]
#### Describe the bug
Comment no longer appear after upgrading from 1.6.1.24 to 1.7.7.x

#### Steps to Reproduce

Step to reproduce :

1. Install prestashop 1.6.1.24
2. Install module product comment 3.6.0
3. Add a comment
4. Upgrade prestashop
5. Upgrade the porduct comment module to the last version
6. Go to FO
7. See error

![107024041-c65b3e80-67a7-11eb-8e98-5fdf7df4ee29](https://user-images.githubusercontent.com/3034677/107557705-3d466c00-6bda-11eb-894c-db8d810e8050.png)

After adding a new comment the message doesn't appear 
<img width="1233" alt="107024114-e5f26700-67a7-11eb-8c1e-d029c3b936e5" src="https://user-images.githubusercontent.com/3034677/107557656-315aaa00-6bda-11eb-934d-7d22c3c866da.png">

#### Additional information

* PrestaShop version: 1.6.1.24 -> 1.7.7.2
* PHP version: 7.1

**Comment by jf-viguier** [comment]
@sarahdib I can't reproduce this bug because I don't have step 5 "Upgrade the porduct comment module to the last version"
I have a hook issue: no review is displayed at all nor the review block.

**Comment by SamusUA** [comment]
I confirm, there is such a bug: 
Prestashop: 1.7.8.1
PHP: 7.3.33
Memory: 512M
Update: Prestashop: 1.7.8.0 ->  1.7.8.1

![image](https://user-images.githubusercontent.com/41996277/146953328-4ad3bce6-35af-4c13-84a4-b61a4e0a90fa.png)
![image](https://user-images.githubusercontent.com/41996277/146953556-ecd25e30-947d-43e7-9c1f-d43c8c67ec27.png)
