### ISSUE TITLE
Console error in when trying to use list in formatted text area

### ISSUE THREAD

**Issue by JevgenijVisockij** [PrestaShop/PrestaShop#23213]
#### Describe the bug

Console errors when trying to add bullet list or numbered list.

#### Expected behavior

There should not be a console error in such case.

#### Steps to Reproduce

1. Go to any page that has text area which can be formatted (Sell -> Category -> Add -> Description, Design -> CMS -> Pages -> Add new page -> Description,  Catalog -> Brands & Suppliers -> Descripion and Short Description). 
2. Click on bullet list or numbered list. 
![image](https://user-images.githubusercontent.com/47781757/107530911-fbf79180-6bc4-11eb-8c8e-681ee915cf83.png)
3. See error

As first found by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/22476#issuecomment-773217278 (6th issue).

**Screenshots**
![image](https://user-images.githubusercontent.com/47781757/107530978-0f0a6180-6bc5-11eb-8742-acd0f0bbefa6.png)

#### Additional information

* PrestaShop version: 1.7.8(develop).
* PHP version: 7.2

As far as I can tell problem originates from TinyMCE plugin which is used to render the from. So I am not sure what's the best way to solve it. Fix plugin, update it or just leave it be?

**Comment by hibatallahAouadni** [comment]
Hello @JevgenijVisockij 

I reproduced the issue only with develop, so it's a regression.
Thanks for your PR and your issue. I’ll add this to the debug backlog.

Thank you

**Comment by matks** [comment]
Makes me think of https://github.com/PrestaShop/PrestaShop/issues/19761

**Comment by NeOMakinG** [comment]
The update should fix this bug, also I noticed that TinyMCE has a mobile mode which is not used on prestashop, maybe we could use it
