### ISSUE TITLE
[BO] qty_in_stock label is displayed on Order page while the stock management is disabled

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#23216]
#### Describe the bug

After disabling the feature Stock Management in BO, when I try to create an Order from BO, the **qty_in_stock** label is still displayed.

#### Expected behavior

 the **qty_in_stock** label is hidden.

#### Steps to Reproduce

1. **BO**>**CONFIGURE**>**Product Settings**
2. Scroll down to **Products stock** block
3. Disable the **Enable stock management** option
4. Save
5. **BO**>**SELL**>**Orders**>**Orders**
6. Create an Order
7. Choose a customer and select it
8. Choose a product
9. See error => the label is displayed

>Edit by Khouloud
Thanks to check this [comment](https://github.com/PrestaShop/PrestaShop/issues/23216#issuecomment-780608674).

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/107541209-2f3b2000-6bc7-11eb-9e22-5717f7767da8.png)

https://drive.google.com/file/d/18afY2LcaNcfRSRThs8itzNFroVW60Wgr/view

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.0, 1.7.7.1 & develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi!

If this PR is merged: https://github.com/PrestaShop/PrestaShop/pull/22920
We should also remove the quantity label in the BO > Orders > Add new Order page > Cart block
![image](https://user-images.githubusercontent.com/16067358/108221219-d5db6f80-7137-11eb-8bf8-b8dd8fc9a70d.png)

Thank you!
