### ISSUE TITLE
ContextErrorException Warning: Declaration of Cart::getOrderTotal

### ISSUE THREAD

**Issue by arpanjain100** [PrestaShop/PrestaShop#23212]
Prestashop 1.7.7 
When i switch on debug mode and load any product page, I receive the error as per the attached image:

(1/1) ContextErrorException
Warning: Declaration of Cart::getOrderTotal($withTaxes = true, $type = self::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = true) should be compatible with CartCore::getOrderTotal($withTaxes = true, $type = Cart::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = false, bool $keepOrderPrices = false)
<img width="1038" alt="Screenshot 2021-02-10 at 8 47 21 PM" src="https://user-images.githubusercontent.com/53334564/107529734-2eaf8300-6be1-11eb-9653-531a912ed673.png">

All the pages load normally, however it is a bit slower than Prestashop v1.7.5 from which I recently upgraded with no upgradation errors. Also the MySQL usage shoots upto 200%.

I have no overrides. Using a Zone Theme. No cache modules being used.
MySQL latest version, Apache.

**Comment by hibatallahAouadni** [comment]
Hello @arpanjain100 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
