### ISSUE TITLE
Products API not compatible with PHP7.4

### ISSUE THREAD

**Issue by EtoileFilante** [PrestaShop/PrestaShop#23211]
Hello,

When trying to access the API at myurl/api/products?display=full on a fresh install of prestashop, I get the following error : 

` Trying to access array offset on value of type bool (...myprestashop/classes/Product.php, line 6258`

With php 7.4. Switching to php 7.2 made it work.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.4

**Comment by kpodemski** [comment]
Hello,

PrestaShop 1.7.7 is not compatible with PHP 7.4

https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by EtoileFilante** [comment]
Well that would explain it. So late in PHP compatibility... thanks!
