### ISSUE TITLE
Add TinyMCE mobile mode

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#23225]
#### Describe the solution you'd like

Add TinyMCE mobile mode for a better UX

**Comment by marionf** [comment]
@NeOMakinG Could you tell me what is the behavior if a feature used in desktop mode is unavailable in mobile mode ?

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/108384112-b8c3a100-720a-11eb-8f62-5de188cc7f76.png)

For example, you can't create new tables in mobile, but you are able to edit content inside an already existing table

**Comment by marionf** [comment]
Sounds great :+1:
