### ISSUE TITLE
Wrong payment data for specific price product - 1.7.7.1

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23228]
To Reproduce:
A product costs for instance 10 euro. 

- Put a **specific price** on a product that starts today and ends tomorrow to discount 2 euro.
- Buy that product **today** and pay it.
- At the backoffice, Change the status of the order for **paid status when the specific price is not active** (after tomorrow)
- The order will change it's value for the original 10euro and will count as the product was paid two times (first time the specific price, second time the rest of the money that was initially discounted)

Attaching print screen. In the example the correct value would be 11,40euro. It's now 15,20euro
![specific price ended](https://user-images.githubusercontent.com/3126847/107693629-4ac92800-6ca6-11eb-918b-7bca78c48ea3.jpg)
![backoffice wrong value specific price](https://user-images.githubusercontent.com/3126847/107693642-4e5caf00-6ca6-11eb-8429-a742ddf940c1.jpg)

**Comment by florine2623** [comment]
Hello @seederp2p ,
I can't reproduce your issue in PS 1.7.7.1.
I tried with the 2-euro discount as you said in the comment and the -25% as it is on your screenshot, and also added the cost price as it is on your screenshot, but I can't reproduce the issue.
The price is still the one with discount after the status changed and specific price not available :
![Capture d’écran 2021-02-12 à 09 39 06](https://user-images.githubusercontent.com/16019289/107746486-2e64d400-6d16-11eb-8f32-57255fa0652b.png)

Please check if you have overrides, conflicts with other modules, or any custom development.
I will close your issue.
Thanks!

**Comment by seederp2p** [comment]
@florine2623 I enabled dev mode at prestashop and I got this error at backoffice order list:

'PHP message: PHP Warning:  Declaration of Cart::getOrderTotal($with_taxes = true, $type = Cart::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = true) should be compatible with CartCore::getOrderTotal($withTaxes = true, $type = Cart::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = false, bool $keepOrderPrices = false) in /var/www/XXXXXX/override/classes/Cart.php on line 56\n'

After I disabled a module that I bought at addons.prestashop.com called advanced payment rules, the error went away. Might be the cause?
