### ISSUE TITLE
Unknown locale code: en-US [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0] - 1.7.7.1

### ISSUE THREAD

**Issue by ahtokren** [PrestaShop/PrestaShop#23229]
#### Describe the bug

After update from v1.7.6.x to v1.7.7.1 with module 1-Click Upgrade, throws an error: "Unknown locale code: en-US [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]"

#### Expected behavior

Need to just an update from 1.7.6.x to 1.7.7.1

#### Steps to Reproduce

1. Go to '1-Click Upgrade module'
2. Update to 1.7.7.1
3. After an update BO throws an error:
"Unknown locale code: en-US [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]"

and debug shows:
- "Uncaught Exception: An exception has been thrown during the rendering of a template ("Unknown locale code: en-US")."
- "Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unknown locale code: en-US")." at /...../htdocs/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig line 37"

**Screenshots**

![warnings](https://user-images.githubusercontent.com/78935269/107702280-b15c3f00-6cc2-11eb-860a-f273d45b6f29.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by florine2623** [comment]
Hello @ahtokren ,
Can you check you database, in table ps_currency and ps_currency_lang, make sure all your currencies and languages are present.
Example, in my case I'm using Euro and USD as currencies and English Spanish and French as languages on my shop :
![Capture d’écran 2021-02-12 à 10 55 47](https://user-images.githubusercontent.com/16019289/107753847-f0b97880-6d20-11eb-8382-1c79778aad97.png)

**Comment by ahtokren** [comment]
It looks like it doesn`t depend from this tables (all currencies and lang. are present).
I have made this tests for update to v1.7.7.1 from 2 ver: 1.7.2.1 and 1.7.6.4 on 2 different servers, both have this issue.
Also played with PHP versions.
![error](https://user-images.githubusercontent.com/78935269/108004223-e4257080-6ffd-11eb-9b19-42e8877f04bd.png)

**Comment by hibatallahAouadni** [comment]
Hello @ahtokren 

Sorry for the late response.
Could you please check this issue #22697 cause it seems similar to yours.

Thanks!

**Comment by ahtokren** [comment]
I see that issue #22697 is still not resolved.
Just for case, there is no "ps_currency_lang" table in the database in 2 different versions 1.7.2.1 and 1.7.6.4 on 2 different servers, only "ps_currency". Aand after update all is the same. Should I?

**Comment by hibatallahAouadni** [comment]
Hello @ahtokren 

> I see that issue #22697 is still not resolved.

Cause I couldn't reproduce it :confused:
I followed your steps and I couldn't reproduce the issue.
Could you please provide more infos,was your shop originally 1.6? if so, could you please check these issues #22668 & #22237

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ahtokren ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by alisamie97** [comment]
I have the same issue with `fr-FR`
![image](https://user-images.githubusercontent.com/23106000/218015831-627d4d14-e63a-45e5-be12-5b46c3f82a18.png)
This is my table `ps_currency_lang`
![image](https://user-images.githubusercontent.com/23106000/218015916-86373b14-6c8a-408b-ab32-b1a03aa2c839.png)
I imported the `fr` language from back office and I think it has issues to add the currency language correctly

**Comment by alisamie97** [comment]
I deleted the `fr` language from BO and imported it again from BO > International Localization and now my table looks like this
![image](https://user-images.githubusercontent.com/23106000/218017006-a8b0903f-bf49-4c0d-8d05-14e07ca46194.png)
But when I change language it shows another error
![image](https://user-images.githubusercontent.com/23106000/218017127-abec86ed-5159-4abc-ad4e-5bb650f395b2.png)
I cleared the cache and checked, not working

**Comment by alisamie97** [comment]
The issue comes from here. https://github.com/PrestaShop/PrestaShop/blob/e664e3d4cd5d59695d207ec186296a1857297da4/classes/controller/FrontController.php#L1677

The country which is selected for customer has no translation in `fr` language and so it does not show up
But the issue is that I get a new error now :))))
I just edited the country and set a name in `fr` language
Then came to FO and tried to change language
Now it is stuck and does not load the website in new language :))))

**Comment by alisamie97** [comment]
I even tried this:
![image](https://user-images.githubusercontent.com/23106000/218019178-1aac86a1-2a44-47bf-b413-a3d494369bf3.png)
no change

**Comment by alisamie97** [comment]
Also tried to copy from english to french but no fix
I tried to update file access and again no change
i know its very simple but I can not find it :)))

**Comment by maryano** [comment]
I had a similar problem in PS 8.0.4 and i solved it adding the proper information in database, ps_lang table, column locale.
For example for spanish: column "locale" would be **es-ES**

**Comment by jcantonio** [comment]
You can solve this by adding in the ps_currency_lang table 

`INSERT INTO ps_currency_lang (`id_currency`, `id_lang`, `name`, `symbol`, `pattern`) VALUES ('1', '2', 'euro', '€', NULL);
`
where '2' is the id of the language. Prestashop tries to find the currency based on the chosen language.
