### ISSUE TITLE
FO - OrderConfirmation for free order doesn't display, display login/history page

### ISSUE THREAD

**Issue by sgluca** [PrestaShop/PrestaShop#23230]
#### Describe the bug

When I create a free order, after the payment, I expect to show also the confirmation order page and not redirect to history controller.

#### Steps to Reproduce

1. Create a product
2. Add a Cart Rule or a Specific Price to a product to make it free
3. Add the product to cart
4. Complete the order
5. See the login page or history order and not the confirmation order

#### Additional information
In other order that are not free the confirmation page is show, i see, **but is only a supposition**, that when order is free ps will call the controller with only the param 'free-order=1' and doesn't go to initContent function because the param are null or 0.

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @sgluca ,
Thanks for the report.

I was able to reproduce the issue with PrestaShop versions 1.7.7.1, 1.7.6.9 and 1.7.52. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by kpodemski** [comment]
Hello @florine2623 

This has been fixed as a side effect of this PR:
https://github.com/PrestaShop/PrestaShop/pull/25395

**Comment by Hlavtox** [comment]
@kpodemski Nice! 3 birds 1 stone :D I added the issue to PR description.

**Comment by kpodemski** [comment]
cc @florine2623 @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
So, I close the issue as it has been fixed with this PR #25395
