### ISSUE TITLE
PROBLEM WITH UNIT PRICE IN CART

### ISSUE THREAD

**Issue by manuelm97** [PrestaShop/PrestaShop#23237]
#### Describe the bug

I have problems with the unit price of the products. On the product page it is shown correctly, but when I go to the cart it shows a totally different unit price that has nothing to do with the one I put in. I have tried other versions of prestashop and the same thing always happens.

#### Expected behavior

The normal thing would be for the unit prices to be shown the same in all the places where this product or any other is placed.

#### Steps to Reproduce

1. Create a product with combinations.
2. Give a different weight and price than that of the original product.
3. Go to the product file and show a unit price different from the one in the cart.
4. This only happens in the cart.

**Screenshots**

![precio1](https://user-images.githubusercontent.com/44256754/107767172-e0ab9400-6d34-11eb-80c0-3eb06daccd96.jpg)
![precio_unitario_2](https://user-images.githubusercontent.com/44256754/107767183-e3a68480-6d34-11eb-8301-f31b824c09ec.JPG)

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @manuelm97 ,

I can't reproduce your issue in PS 1.7.7.1, please take a look at my screenshots :
![Capture d’écran 2021-02-12 à 13 45 44](https://user-images.githubusercontent.com/16019289/107769786-c2479780-6d38-11eb-89db-b620a92d8f56.png)
![Capture d’écran 2021-02-12 à 13 45 53](https://user-images.githubusercontent.com/16019289/107769791-c4115b00-6d38-11eb-89b3-0837dce66dec.png)

Please check if you have any overrides, external modules that conflict with the feature, check your template too.

As this is not a core PrestaShop bug, I'll close your issue.
If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
