### ISSUE TITLE
PROBLEMAS CON PRECIO UNITARIO EN CARRITO

### ISSUE THREAD

**Issue by manuelm97** [PrestaShop/PrestaShop#23231]
#### Describe the bug

Tengo problemas con el precio unitario de los productos. En la página del producto se muestra correctamente, pero cuando voy al carrito muestra un precio unitario totalmente distinto y que no tiene nada que ver con el que puse. He probado en otras versiones de prestashop y pasa siempre lo mismo.

#### Expected behavior

Lo normal sería que se mostraran los precios unitarios igual en todos los lugares donde se ponga este producto o cualquier otro.

#### Steps to Reproduce

1. Crear un producto con combinaciones.
2. Dar un peso y precio distinto al que hay en el producto original.
3. Ir a la ficha del producto y muestra un precio unitario distinto del que hay en el carrito.
4. Esto solo pasa en el carrito.

**Screenshots**

Os dejo aquí capturas de a lo que me refiero.
![precio1](https://user-images.githubusercontent.com/44256754/107751156-50ae2000-6d1d-11eb-90b2-8ed778539fa8.jpg)
![precio_unitario_2](https://user-images.githubusercontent.com/44256754/107750897-f01ee300-6d1c-11eb-82c3-4a21c2f04aa5.JPG)

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello,

English is the norm, please translate it.

Thanks.

**Comment by florine2623** [comment]
Please create a new issue in English, I'll close this one.
Thanks
