### ISSUE TITLE
New hook for product price

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#23246]
#### Is your feature request related to a problem?

As a module developer I have a need to set the product price to what I want.

Having a hook `actionGetProductPrice` that could return new price for the product could open quite a few possibilities for modules without using overrides.
* realtime pricing from erp
* totally new discount processes
* etc

#### Describe the solution you'd like

Something like this:

```php
    public function getPrice(
        $tax = true,
        $id_product_attribute = null,
        $decimals = 6,
	$divisor = null,
        $only_reduc = false,
        $usereduc = true,
	$quantity = 1
    ) {
        $origprice = Product::getPriceStatic((int) $this->id, $tax, $id_product_attribute, $decimals, $divisor, $only_reduc, $usereduc, $quantity);
       $hooked_price = Hook::exec('actionGetPrice', ['product'=>$this->id, 'tax'=>$tax, 'id_product_attribute'=>$id_product_attribute, 'decimals'=>$decimals, 'divisor'=>$divisor, 'only_reduc'=>$only_reduc, 'usereduc'=>$usereduc, 'quantity'=>$quantity, 'origprice'=>$origprice];
);
       if($hooked_price) {
          return $hooked_price;
       }

        return $origprice;
    }
```

Totally untested code, just the idea.

Ideally the hook should also have the possible customer and cart objects (if the price of the product depends on other stuff in the cart that can be calculated also).

#### Alternatives you've considered

At the moment override seems to be the only way to affect product pricing in anyway from a module.

#### Additional context

The cart should also take these calculations in to account for this to be usefull.

Another similar attribute is stock level...

**Comment by Hlavtox** [comment]
I would make a general hook to ProductLazyArray, so we can override everything, everywhere.
And specifically price, you can hook to actionGetProductPropertiesAfter and do whatever.

**Comment by tswfi** [comment]
hmmm

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductPresenter.php#L95

**Comment by tswfi** [comment]
I have to test this, thanks for the hint @Hlavtox

**Comment by Hlavtox** [comment]
@tswfi Ok we were both blind, nice hook you found!!! :D

**Comment by tswfi** [comment]
This is the pr that introduced it, https://github.com/PrestaShop/PrestaShop/pull/17203 it will be available from 1.7.8.0 (it seems)

**Comment by florine2623** [comment]
Hello @tswfi ,
Did you find what you were searching for ? Can I close the issue ?
Thanks!

**Comment by tswfi** [comment]
@florine2623 sorry, didn't have time to play with this before.

Just tested the actionPresentProduct now and 
1) it is not used in cart (well obviously it is now a orderdetail object)
2) I cant see of a way for this to change the basket calculation (or I'm blind).

(Also I'm looking for solution that works with 1.7.7.1 because that is the current release :)

**Comment by Hlavtox** [comment]
@tswfi actionGetProductPropertiesAfter

**Comment by tswfi** [comment]
@Hlavtox that gets cached pretty hard so not possible to use for making prices different for different customers for example. (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L5522)

`actionGetProductPropertiesAfterUnitPrice` looks promising also, but this does not change product price in cart

```php
    public function HookActionGetProductPropertiesAfterUnitPrice($params) {
           $params['product']['unit_price'] = 10;
           $params['product']['price'] = 10;
    }
```

Cart gets the price directly by calling Product::getPriceStatic (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L1073)

Overwriting that will give correct price for the cartline but the total calculation is still wrong. The cart uses `Calculator` for the total calculation which keeps a collection of `CartRowCollection`. Those have a `PriceCalculator` which does call Product::getPriceStatic (https://github.com/PrestaShop/PrestaShop/blob/ee1a52288af32878333982a1c721e1fa56c2223d/src/Adapter/Product/PriceCalculator.php#L65)

The calculators don't seem to have hooks in them..

(sorry, this comment is also just for me to keep track of what happens where so it became a bit long :)

If I've understood symfony correctly one might be able to decorate the calculators? (still finding all the ins and outs about symfony while learning prestashop).

On a related note, that new unit price from my test hook is actually showing up bit strange in the cartline template (it shows the 10 as a new info instead of overwriting the existing value):

![image](https://user-images.githubusercontent.com/1352132/108327416-0ffa4f00-71d4-11eb-93ad-44ceb6e19b34.png)

**Comment by kpodemski** [comment]
Thing is that some parts of PrestaShop use `priceCalculation` where others some method on top of it 🙄 

It would be easier for you to keep it as an override because without rewriting some `Cart` components it's hard to make those hooks aware of everything what's going on, especially if you have a product with discount.

**Comment by tswfi** [comment]
yup, so it seems..

@florine2623  please do not close. I think this FR is valid and there should be a hook that allows module to overwrite the price so that the cart calculation can do its magic correctly.

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

Thanks for the suggestion, the Developer Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers  , what do you think?

**Comment by matks** [comment]
Hello, I think @kpodemski makes a point

> Thing is that some parts of PrestaShop use `priceCalculation` where others some method on top of it 🙄
> 
> It would be easier for you to keep it as an override because without rewriting some `Cart` components it's hard to make those hooks aware of everything what's going on, especially if you have a product with discount.

**Comment by tswfi** [comment]
Why not fix the core to use "one source of truth" for prices and allow module developers to extend to it?

**Comment by titodevera** [comment]
I´m exactly under the same situation as @tswfi described. We need to modify some product prices by custom rules in execution time, without modify the product price inself (at the db level). I think a new hook that allows modify the price in all sources at the same time (product page, cart...) is the solution for this cases... Thanks

**Comment by jolelievre** [comment]
I think `Product::getPriceStatic` or `Product::priceCalculation` would be the best candidate for such hook

Because ProductLazyArray or ProductPresenter are mainly used for presentation in front, you need to be able to change the whole price everywhere in cart computing, order computing and so on so for that `Product::getPriceStatic` and `Product::priceCalculation` are the lowest and most adapted methods to change

**Comment by MatShir** [comment]
It looks like a nice feature ! Maybe If one of you guys is motivated, we can help you with @jolelievre on your contribution. Lets us know, we are available on Slack or GitHub ;)

**Comment by carmas123** [comment]
I think that a simple solution like this can solve the problem:

```
    private function getCartPriceFromCatalog(
        int $productId,
        int $combinationId,
        int $customizationId,
        bool $withTaxes,
        bool $useReduction,
        bool $withEcoTax,
        int $productQuantity,
        ?int $addressId,
        Context $shopContext,
        &$specificPriceOutput
    ): ?float {
        $value = Product::getPriceStatic(
            $productId,
            $withTaxes,
            $combinationId,
            6,
            null,
            false,
            $useReduction,
            $productQuantity,
            false,
            (int) $this->id_customer ? (int) $this->id_customer : null,
            (int) $this->id,
            $addressId,
            $specificPriceOutput,
            $withEcoTax,
            true,
            $shopContext,
            true,
            $customizationId
        );

        Hook::exec('actionGetCartPriceFromCatalogInCart', [
            'id_product' => $productId,
            'id_combination' => $combinationId,
            'id_customization' => $customizationId,
            'with_taxes' => $withTaxes,
            'use_reduction' => $useReduction,
            'product_quantity' => $productQuantity,
            'id_address' => $addressId,
            'specific_price_output' => &$specificPriceOutput,
            'value' => &$value,
            'context' => $shopContext,
        ]);

        return $value;
    }
```

With this hook we can handle this Hook and replace the returned price with the customized customer price also into the cart.
Than using "actionGetCartPriceFromCatalogInCart" and "actionGetProductPropertiesAfterUnitPrice" can solve all problems for now.

**Comment by carmas123** [comment]
This is also another useful hook directly into the PriceCalculation

```
    public function priceCalculation(
        $idShop,
        $idProduct,
        $idProductAttribute,
        $idCountry,
        $idState,
        $zipCode,
        $idCurrency,
        $idGroup,
        $quantity,
        $useTax,
        $decimals,
        $onlyReduc,
        $useReduc,
        $withEcotax,
        &$specificPrice,
        $useGroupReduction,
        $idCustomer = 0,
        $useCustomerPrice = true,
        $idCart = 0,
        $realQuantity = 0,
        $idCustomization = 0
    )
    {
        $value = Product::priceCalculation(
            $idShop,
            $idProduct,
            $idProductAttribute,
            $idCountry,
            $idState,
            $zipCode,
            $idCurrency,
            $idGroup,
            $quantity,
            $useTax,
            $decimals,
            $onlyReduc,
            $useReduc,
            $withEcotax,
            $specificPrice,
            $useGroupReduction,
            $idCustomer,
            $useCustomerPrice,
            $idCart,
            $realQuantity,
            $idCustomization
        );

        \Hook::exec('actionPriceCalculation', [
            'id_product' => $idProduct,
            'id_product_attribute' => $idProductAttribute,
            'id_customization' => $idCustomization,
            'id_country' => $idCountry,
            'id_state' => $idState,
            'zip_code' => $zipCode,
            'id_currency' => $idCurrency,
            'id_group' => $idGroup,
            'id_cart' => $idCart,
            'id_customer' => $idCustomer,
            'use_customer_price' => $useCustomerPrice,
            'quantity' => $quantity,
            'real_quantity' => $realQuantity,
            'use_tax' => $useTax,
            'decimals' => $decimals,
            'only_reduc' => $onlyReduc,
            'use_reduc' => $useReduc,
            'with_ecotax' => $withEcotax,
            'specific_price' => &$specificPrice,
            'use_group_reduction' => $useGroupReduction,
            'value' => &$value,
        ]);

        return $value;
    }

```

**Comment by hibatallahAouadni** [comment]
@carmas123 could you please create a Pull Request :pray: 
Can't wait for your PR :rocket:

**Comment by carmas123** [comment]
@hibatallahAouadni you can solve this problem by overriding the Cart and Product class.
The only problem without this hook is that when the Cart summary is calculated there is no way to change the prices.
