### ISSUE TITLE
Bug with setting BYN currency

### ISSUE THREAD

**Issue by Seempai** [PrestaShop/PrestaShop#23249]
it is impossible to set the currency BYN (933) Belarusian ruble. Loading screen freezes endlessly. There are no problems with other currencies. What could be the problem?
![RiW7EP_CR2E](https://user-images.githubusercontent.com/29523132/107843428-fcb64080-6ddb-11eb-97c1-24ca3a38e835.jpg)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
