### ISSUE TITLE
Move upgrade scripts to the autoupgrade module

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#23240]
#### Is your feature request related to a problem?

- The Core shouldn't be aware of the upgrade process.
- Putting the incremental upgrade scripts (SQL, PHP) in the core means that fixing them requires a new release.

#### Describe the solution you'd like

Everything related to upgrade should be removed from the core and handled by the module itself.
 
#### Additional context

This might require the module to stop behaving like a module, at least during the upgrade process.

**Comment by Progi1984** [comment]
@PierreRambaud PrestaShop/autoupgrade#395 is merged.

**Comment by Progi1984** [comment]
@marionf I reopened because  scripts have not been removed in Core. They are just moved in autoupgrade.
