### ISSUE TITLE
BO - Customer Settings - An exception is displayed when editing a category discount for customer Group

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23244]
#### Describe the bug

In the BO > Shop Parameters > Customer Settings > Customer Group > when we try to edit a category discount => an exception is displayed

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Customer Settings page
2. Edit a customer Group
3. Add a category discount for the Clothes category
4. Try to click on the "Edit" button
![image](https://user-images.githubusercontent.com/16067358/107796781-86252e80-6d5a-11eb-826b-40807d083cfb.png)
5. See the error 

![image](https://user-images.githubusercontent.com/16067358/107796823-90dfc380-6d5a-11eb-972b-c6c96eecfc7c.png)

#### Additional information

* PrestaShop version: develop, PS1769, PS1771
* PHP version: 7.1

**Comment by florine2623** [comment]
Fixed on 8.0.x, 8.1.x, 9.0.x. Although when changing page, the category discount is not saved.


https://github.com/PrestaShop/PrestaShop/assets/16019289/73bab177-45d3-426c-9983-a478d7f9649f



I'm closing the issue.
