### ISSUE TITLE
[SOLVED] Unable to generate a URL for the named route "admin_link_block_list" as such route does not exist

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#23258]
#### Describe the bug

No longer able to login to backoffice, frontoffice is still working.

Errormessage when trying to open the login page:
Unable to generate a URL for the named route "admin_link_block_list" as such route does not exist.
[Symfony\Component\Routing\Exception\RouteNotFoundException 0]

#### Expected behavior

Backoffice Login Page should open

#### Steps to Reproduce

1. www.domain.com/backoffice
2. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/31710761/107885528-21eda080-6efb-11eb-8072-9ff8f154b8ff.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

Deleting cache has been tried already, no change.
In another bug report for a similar problem (#14799), it is asked about an output of "select * from ps_configuration where name LIKE 'PS_ROUTE%'" - here is my output:

![grafik](https://user-images.githubusercontent.com/31710761/107885681-ffa85280-6efb-11eb-9c17-eefe8c3e297a.png)

---
> Originally posted by @TomanDesign

I had the same problem and followed the steps below to solve the problem:

1. changed enabled parameter 0 to 1 in ps_tab table for ps_linklist module
2. updated prestashop engine from 1.7.7.1. to 1.7.7.2
3. reset Link List module
4. update option appeared, so I did it
5. enabled the Link List module

**Comment by TGD001** [comment]
Same issue for me. PS 1.7.7.1 - PHP 7.3

**Comment by florine2623** [comment]
Hello @tom75 ,
I can't reproduce the issue in PS 1.7.7.1.
Is it a fresh install ? an upgrade ? Other ?
Thanks.

**Comment by TGD001** [comment]
> 
> 
> Hello @tom75 ,
> I can't reproduce the issue in PS 1.7.7.1.
> Is it a fresh install ? an upgrade ? Other ?
> Thanks.

if it can help you, I noticed this problem suddenly in two different old installations in same time. Same provider (aruba.it) A tiket has open from his side too.

**Comment by decom-media** [comment]
Hello @TGD001, 

well, my installation is upgraded since many versions, now this shop is 1.7.7.0 and i would be happy to try to update to 1.7.7.1, but as i am not able to login i cannot even update the shop (Multishop, Multilanguage). 

Basically it happened "out of nothing", as i did not do any changes directly before it happened, just checked again my orders, but, i am logged in all the time, therefore, maybe it just did not happen because i was logged in before. Only things i did hours before it happened was updating the prestashop checkout module and the (included) link list module - but, again, the shop was working after that without a problem for hours.

Also, i tried already with an old backup from a week ago, same (just the files, not the database), so, i assume the problem is more related to anything in the database.

**Comment by TGD001** [comment]
Also my two sites derive from many updates up to the last 7.7.1 and also to me since yesterday, the error has popped up on both out of nowhere. Browsing I found no reference, other than clearing the cache, (var / chache) which I did without getting any benefit. At that point I restored the backup, but still nothing; I then changed the PHP version (7.2-> 7.3) to no avail. I have opened a ticket with the provider, but am waiting for a response. However the two sites work perfectly, it is only the back office side that does not work

**Comment by florine2623** [comment]
Hello @tom75 ,
Please enable your debug mode to have more info about the error.

**Comment by decom-media** [comment]
@florine2623 here are the screenshots from the debug mode (cache cleaning has been tried already, file restore as well - just to mention again)

![grafik](https://user-images.githubusercontent.com/31710761/107932029-5dc94a00-6f7d-11eb-9080-aa7f4692bbd1.png)
![grafik](https://user-images.githubusercontent.com/31710761/107932243-9ff28b80-6f7d-11eb-9a24-eca888c19bde.png)

**Comment by TGD001** [comment]
This is mine
![errore_url](https://user-images.githubusercontent.com/41903971/107934911-ed242c80-6f80-11eb-9d3b-d98e531ad75d.JPG)

**Comment by florine2623** [comment]
Can you try to comment module ps_linklist ?

**Comment by decom-media** [comment]
@florine2623 well, happy to do that, but, what you mean exactly with "comment module ps_linklist" - removing the module directory (just as i mentioned, even with a restore from a week ago it is still the same problem)?

**Comment by florine2623** [comment]
Yes change `ps_linklist` to `_ps_linklist` and refresh your page.

**Comment by decom-media** [comment]
@florine2623  done - still the same problem (as mentioned, it is nearly impossible that it is depending on some files, as a weeks old backup did result in the same error, only thing is the database which is all the time the same)

**Comment by TGD001** [comment]
I did also, both in PS\molules and Theme\modules.   No result

**Comment by matks** [comment]
@tom75 @TGD001 The issue is likely to come since you upgrade ps_linklist to recent v4.0.0 . I dont know why, I tried to reproduce your issue but I cant. It can be because of specific environment settings.

The issue is that the code in charge of computing URLs is unable to read the file content of https://github.com/PrestaShop/ps_linklist/blob/master/config/routes.yml (this is where the admin_link_block_list route is configured). Moreover the result of reading is merged with other configuration files and dumped inside var/cache indeed.

The issue with reading can come from many root causes: read/write permissions being wrong, wrong folders, wrong upgrade... but I'm afraid unless you find a very accurate series of steps to reproduce it we cant help you.

**Comment by decom-media** [comment]
@matks well, thanks for pointing in the direction of the ps_linklist

could you maybe let me know what the update process of the ps_linklist module version 4.0.0 is doing exactly, as with that information i would be able to find out what has been changed and i can also try to return it (mainly interested in db changes, as it still seems to be db related). 

wrong update cannot be the problem, as this module was updated always and before the update the last available version was installed

any hint to get access again to the backoffice would be great - also if you have the information how to disable the module in the db, i could give that a try

i would also assume that as soon as more people did update more will have the same problem then

**Comment by matks** [comment]
> @matks well, thanks for pointing in the direction of the ps_linklist

You can use the following items to find what you are looking for:
- comparison of tags https://github.com/PrestaShop/ps_linklist/compare/v3.2.0...v4.0.0
- changelog of the release https://github.com/PrestaShop/ps_linklist/releases/tag/v4.0.0

**Comment by decom-media** [comment]
@matks, @florine2623 Well, it is definitely related to the ps_linklist v4.0.0 module, as i did disable it directly in the db and since that time it is again possible for me to login in the backoffice - so, for this moment i will leave it disabled, but it is definitely a bug of that module, maybe connected to prestashops updated since many versions - at least that is what it seems both my shop and @TGD001  shops seem to have in common

**Comment by TGD001** [comment]
can someone kindly tell me how to disable the ps_linklist.php module?  Thank you

**Comment by decom-media** [comment]
@TGD001 you need to do it in the db, table "tab" (with prefix you did choose, of course, default should be "ps_tab") and set "enabled" to 0

![grafik](https://user-images.githubusercontent.com/31710761/107985725-ea4e2980-6fca-11eb-99b2-0d390998b63f.png)

**Comment by TGD001** [comment]
@tom75, 
![admin](https://user-images.githubusercontent.com/41903971/108025848-87d74680-7027-11eb-976d-85877284255f.JPG)
Thank you very much for the explanation. Open the database I noticed that there were two ps_linklists (see the screenshot). I deleted one, disabled the other as suggested and everything started working again. and this problem was for both e-commerce that I own. I hope my experience will help you better understand the origin of the problem.

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

Could you try now to enable the module `ps_linklist` from BO (not from database) and see if you still encounter the issue with BO.
So, you upgraded your shop to PS1.7.7.0, then you upgrade the `ps_linklist` module and then you encounter this issue, is that so? If so, please provide your previous PS version and the previous `ps_linklist` module version.

Thanks!

**Comment by TGD001** [comment]
Hi @hibatallahAouadni 

I took the test you requested, and the problem returns. Consider that I have release 1.7.7.1 for both sites, installed  just released new version, and issue raised yesterday.

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

Ok, thanks for your feedback.
Could you please provide your previous PS version (before upgrade) and the previous version of the module `ps_linklist`.

Thanks!

**Comment by TGD001** [comment]
Hi @hibatallahAouadni 
We generally keep our installations up to date, so we went from 1.7.7.0 to 1.7.7.1. Enclosed you will find the PS_linklist
 from the backup of a week ago

[ps_linklist.zip](https://github.com/PrestaShop/PrestaShop/files/5995131/ps_linklist.zip)

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 & @tom75 

I upgraded my shop 1.7.7.0 with the module ps_linklist v3.2.0 to PS1.7.7.1 and then I upgraded my module ps_linklist to 4.0.0.
As you can see in the attached screen record below, I didn't encounter any issue with BO access and in the DB the module is active and enabled: 

https://drive.google.com/file/d/1R16j4CI1RUSeT66a8oozuWL3EalWH2R8/view

Please check and feedback.
Thanks!

**Comment by TGD001** [comment]
@hibatallahAouadni 
To tell the truth I use the Z.One theme which has its own link list, so keeping the original module activated does not change or limit the use of the site. This error will probably be fixed with the next release, I prefer to wait, avoiding experiments.

**Comment by hibatallahAouadni** [comment]
@TGD001 so the issue is not related to PS Core.
@tom75 do you use another theme as @TGD001 ?

**Comment by TGD001** [comment]
@hibatallahAouadni 
hope they will focalize the problem, by themselves.. As I noticed surfing on the net, just @tom75  and me raised that issue. Very strange.

**Comment by hibatallahAouadni** [comment]
@TGD001 it may be related to the theme, if you both have the same theme.
Well let's wait for @tom75 feedback.

Thanks!

**Comment by decom-media** [comment]
@hibatallahAouadni no, i am using a different theme (warehouse) which is also having its own link list included, therefore it is no problem for me at this moment as i can keep it disabled.
maybe the problem is then related to themes which include seperate link list modules or to shops which have been installed with a specific (older) version of prestashop and upgraded since then

**Comment by TGD001** [comment]
@hibatallahAouadni @tom75 

It must be remembered that at least to me, the error appeared suddenly, without having carried out any update of any module, theme included

**Comment by hibatallahAouadni** [comment]
Hello @tom75 & @TGD001 

Thanks for your feedback!
So the issue is related when you install a theme which include seperate link list modules.
Well, could you please provide your themes names.

Thanks!

**Comment by decom-media** [comment]
Hi @hibatallahAouadni 

that seems possible - my theme name is "warehouse", don´t want to make more advertising here where to find it, but, however, if you want to know more details or i can offer you also the files for checking just let me know (should be no problem for the license if not used for production)

**Comment by hibatallahAouadni** [comment]
@tom75 thanks :slightly_smiling_face: I will try to reproduce it and I will feedback :wink:

**Comment by jpcoke** [comment]
In my case, i have default theme, and updated 4 modules, sadly i can only tell for sure that one them was 1 click upgrade...

I have 2 websites pretty similar and happened only on one of them.

Used the solution above in desabling ps_linklist on database, and apparently solved, at least i can access the BO...

**Comment by TGD001** [comment]
@hibatallahAouadni  @tom75  
Updated to 1.7.7.2 , PS_link same 4.0 release. same error raised.

**Comment by hibatallahAouadni** [comment]
@TGD001 thanks!
But could you please switch to the Classic theme and check if the issue still persist?

**Comment by TGD001** [comment]
@hibatallahAouadni 
unfortunately I' ve not classic theme installed.

**Comment by hibatallahAouadni** [comment]
@TGD001 I just attached :wink: 
[classic.zip](https://github.com/PrestaShop/PrestaShop/files/6035555/classic.zip)

**Comment by TGD001** [comment]
@hibatallahAouadni 
thank you for theme. Test done.  Switching from ZOne theme to classic theme did not give any problems and after loading it the automatic refesh returned the BO normally. the link module 4.0 appeared immediately activated (while with the other theme it was deactivated). I then clicked on "configure" and the same error raised. Once the theme was changed again, everything returned to normal operation with the 4.0 link disabled. Hope it can help you.

**Comment by decom-media** [comment]
@hibatallahAouadni i was not 100% sure about it, but, i was pretty sure also that i had this module disabled before updating it and it was enabled then after the update - as i was not sure about it, i did not mention it before, but, now, as @TGD001 mentions that it is automatically enabling itself i just want to mention that as well.

**Comment by TomanDesign** [comment]
I had the same problem and followed the steps below: 

- changed enabled parameter 0 to 1 in ps_tab table for ps_linklist module
- updated prestashop engine from 1.7.7.1. to 1.7.7.2
- reset Link List module
- update option appeared, so I did it
- enabled the Link List module

Problem disappeared

**Comment by TGD001** [comment]
@TomanDesign 
I confirm your procedure. Problem disappared after module reset.

**Comment by hibatallahAouadni** [comment]
Thanks @TomanDesign :rocket: 
So resetting the module solve the issue :tada:

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Despite our efforts, we were not able to reproduce your issue. We will close this issue.
@tom75 & @TGD001 thanks for the details and your patience :pray: 
Thanks @TomanDesign for your solution :rocket: I will add your solution to the issue description, to help anyone with this problem.

Thanks!

**Comment by Dumidu** [comment]
I'm having similar issue in my prestashop. I disabled the linklist from the db and deleted the cache. But still getting the error.
PrestaShop 1.7.7.8
PHP version 7.2.34

![image](https://user-images.githubusercontent.com/5407540/147390409-710a6fe9-c67d-4e9e-9acc-49d1afee7ff0.png)
![image](https://user-images.githubusercontent.com/5407540/147390418-5734aa2e-cab9-48f3-883a-ef3d147ffb40.png)

**Comment by bigbrainou** [comment]
> I'm having similar issue in my prestashop. I disabled the linklist from the db and deleted the cache. But still getting the error. PrestaShop 1.7.7.8 PHP version 7.2.34
> 
> ![image](https://user-images.githubusercontent.com/5407540/147390409-710a6fe9-c67d-4e9e-9acc-49d1afee7ff0.png) ![image](https://user-images.githubusercontent.com/5407540/147390418-5734aa2e-cab9-48f3-883a-ef3d147ffb40.png)

Hei, i have same, did you fix this?

**Comment by metalicaruz** [comment]
> > I'm having similar issue in my prestashop. I disabled the linklist from the db and deleted the cache. But still getting the error. PrestaShop 1.7.7.8 PHP version 7.2.34
> > ![image](https://user-images.githubusercontent.com/5407540/147390409-710a6fe9-c67d-4e9e-9acc-49d1afee7ff0.png) ![image](https://user-images.githubusercontent.com/5407540/147390418-5734aa2e-cab9-48f3-883a-ef3d147ffb40.png)
> 
> Hei, i have same, did you fix this?

This worked for me:

Delete the content of /var/cache/ 

Enable ps_linklist (if you disabled it)

**Comment by calimero1123** [comment]
Bonjour,
moi pour réparer l'erreur je suis aller dans ma base de données , j'ai accéder a la table tab et j'ai supprimer la ligne ps_linklists ensuite j'ai réinitialiser le module Liste de liens
