### ISSUE TITLE
404 on Product Variantes change with multi-languages on classic theme

### ISSUE THREAD

**Issue by oopen** [PrestaShop/PrestaShop#23250]
#### Describe the bug
The BUG is in PRODUCTION !
When you use multi-languages, with classic theme, reveled by using product variants.

#### Steps to reproduce

1. just download the last version V1.7.7.1,
2. install, unable multi-language
3. add product variant
4. go to product page
5. select variant
6. the request return 404 with front message: An error occurred while processing your request

**Screenshots**
In browser JS `prestashop.urls.pages` all URLs to index.php are invalids; because locales is set as root dir.

```
prestashop.urls.pages
{
    address: "https://domain.com/fr/adresse",
    addresses: "https://domain.com/fr/adresses",
    authentication: "https://domain.com/fr/connexion",
    cart: "https://domain.com/fr/panier",
    category: "https://domain.com/fr/index.php?controller=category",
    cms: "https://domain.com/fr/index.php?controller=cms",
    contact: "https://domain.com/fr/nous-contacter",
    discount: "https://domain.com/fr/reduction",
    guest_tracking: "https://domain.com/fr/suivi-commande-invite",
    history: "https://domain.com/fr/historique-commandes",
    identity: "https://domain.com/fr/identite",
    index: "https://domain.com/fr/",
    my_account: "https://domain.com/fr/mon-compte",
    order: "https://domain.com/fr/commande",
    order_confirmation: "https://domain.com/fr/confirmation-commande",
    order_detail: "https://domain.com/fr/index.php?controller=order-detail",
    order_follow: "https://domain.com/fr/suivi-commande",
    order_login: "https://domain.com/fr/commande?login=1",
    order_return: "https://domain.com/fr/index.php?controller=order-return",
    order_slip: "https://domain.com/fr/avoirs",
    pagenotfound: "https://domain.com/fr/page-introuvable",
    password: "https://domain.com/fr/recuperation-mot-de-passe",
    pdf_invoice: "https://domain.com/fr/index.php?controller=pdf-invoice",
    pdf_order_return: "https://domain.com/fr/index.php?controller=pdf-order-return",
    pdf_order_slip: "https://domain.com/fr/index.php?controller=pdf-order-slip",
    prices_drop: "https://domain.com/fr/promotions",
    product: "https://domain.com/fr/index.php?controller=product",
    register: "https://domain.com/fr/connexion?create_account=1",
    search: "https://domain.com/fr/recherche",
    sitemap: "https://domain.com/fr/plan-site",
    stores: "https://domain.com/fr/magasins",
    supplier: "https://domain.com/fr/fournisseur"
​}
```

As you can see, `category, cms, order_detail, order_return, pdf_invoice, pdf_order_return, pdf_order_slip, product` are invalids URLs, many bugs :1st_place_medal:

#### Additional infos

In your case of product variantes, this is product the wrong url.
URL is : https://domain.com/fr/index.php?controller=product
But must be : https://domain.com/index.php?controller=product
without locale !

Ajax request when selection a product variation, return 404. [themes/_core/js/product.js](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/themes/_core/js/product.js#L154)

Templated in [themes/classic/templates/_partials/javascript.tpl](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/themes/classic/templates/_partials/javascript.tpl#L37)

Set by `$pages[$index] = $this->context->link->getPageLink($page_name, $this->ssl);` in [classes/controller/FrontController.php](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/classes/controller/FrontController.php#L1521)

[function getPageLink() in class Link.php](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.1/classes/Link.php#L1100) always return locale :-1: 
`return $this->getBaseLink($idShop, $ssl, $relativeProtocol) . $this->getLangLink($idLang, null, $idShop) . ltrim($uriPath, '/');`
which should not be the case, with links that start by index.php

* PrestaShop version: 1.7.7.1

**Comment by oopen** [comment]
Production bug fixed !
Please merge.

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

Could you check @oopen 's issue please ?
Thanks

**Comment by florine2623** [comment]
Hello @oopen ,
Could you check those 2 issues : #16865 & #22748 ?
It seems like they are similar.

**Comment by oopen** [comment]
Hi @florine2623 
Yes, this bug also concerns this issue https://github.com/PrestaShop/PrestaShop/issues/22667 there is possibly other reported issues that are in this scope.
Many impact in front, due to this bug, need to be imperatively merge for v17.7.2 !
Front error on variants changes, reported : `An error occurred while processing your request`

**Comment by hibatallahAouadni** [comment]
Hello @oopen 

Thanks for your feedback and your PR :rocket: 
Could you please provide clear steps to reproduce your issue :pray: 

Thanks in advance.

**Comment by oopen** [comment]
Hi @hibatallahAouadni 
Step to reproduce:
just download the last version V1.7.7.1, 
install, unable multi-language 
add product variant 
go to product page
select variant
the request return 404 with front message: An error occurred while processing your request
this is due to post URL contain local

**Comment by hibatallahAouadni** [comment]
Hello @oopen 

Sorry, but I didn't manage to reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1mbGrhJsQpzAhVLA1c7Jj3oN1cLGTRvir/view

Please check and feedback.
Thanks!

**Comment by oopen** [comment]
Can you make a console log `prestashop.urls.pages` on your product page ?

[The bug in video](https://drop.infini.fr/r/Rc5WEq5rLY#sKPofjAFJEkg4VduJyJBK8+5vTBv35cfaAqwiwbrJmM=)

**Comment by hibatallahAouadni** [comment]
Hello @oopen 

Here's the screenshots with differents languages and combinations:

![image](https://user-images.githubusercontent.com/23308427/108383773-5ff40880-720a-11eb-846b-3bd5729b897d.png)

![image](https://user-images.githubusercontent.com/23308427/108383812-697d7080-720a-11eb-92c1-0f4ee0c282cc.png)

Please check and feedback.
Thanks!

**Comment by oopen** [comment]
My conf :
- HTTPS
- Rewrite
- Full domain, root path install

Your conf :
- HTTP
- no rewrite
- relative or sub dir install

Maybe the bug is related to that.

**Comment by oopen** [comment]
Close the PR, because like as said @matks [in the PR](https://github.com/PrestaShop/PrestaShop/pull/23270#pullrequestreview-594595699) it will be better to keep the locale on all pages, when we are in multi-lang.

We need to correct the 404 no routed with locale.

**Comment by oopen** [comment]
Close Issue, this was done by fixing `httpd.conf` fcgi configuration (php-fpm) ... sorry for inconvenient, this is not a Prestashop bug.

```
-  ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://fpm:9000/var/www/html/$1
+  <FilesMatch \.php$>
+    SetHandler proxy:fcgi://fpm:9000
+  </FilesMatch>
```

**Comment by hibatallahAouadni** [comment]
@oopen Glad to hear :tada:

**Comment by matks** [comment]
@oopen I am not a nginx expert but would this change be valuable to add to our doc about nginx config https://devdocs.prestashop.com/1.7/basics/installation/nginx/ ? 😄 

It can be a "troubleshooting" line below the main config

**Comment by Ken-vdE** [comment]
I have this same issue using version 8.0.x and nginx. I'm using the example nginx config: https://devdocs.prestashop-project.org/8/basics/installation/nginx/

Any ideas?

I do see these suggestions: https://stackoverflow.com/a/56262733/3017716 & https://stackoverflow.com/a/56288878/3017716
I'm going to try them now. If they work, maybe we should update the nginx docs to reflect the required multilang additions.
