### ISSUE TITLE
Error while upgrading from 1.7.6.7 to 1.7.7.1

### ISSUE THREAD

**Issue by cocolate13** [PrestaShop/PrestaShop#23257]
Hi,
I saw lots of subjectson prestashop/github about this but I don't find a solution.
After an upgrade from 1.7.6.7 to 1.7.7.1 I had the following error :

`[INTERNAL] /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/home/barthele/www/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/home/barthele/www/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /home/barthele/www/app/config/config.yml (which is being imported from "/home/barthele/www/app/config/config_prod.yml"). #0 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/home/barthele/...', NULL, false, '/home/barthele/...') #1 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/home/barthele/...') #2 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/barthele/...') #3 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/barthele/...', NULL) #4 /home/barthele/www/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/barthele/...') #5 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /home/barthele/www/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/barthele/www/admin***/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

I saw some issue about it but no resolution. All modules have been updated before 1clickupgrade and cache has been deleted.
PHP version 7.3.20.

Thanks in advance et sorry for my bad english.

**Comment by florine2623** [comment]
Hello @cocolate13 ,
I did an upgrade with one-click upgrade, from 1.7.6.7 to 1.7.7.1, but I can't reproduce your issue.
When using PS 1.7.6.7, you need to use PHP 7.2.

I suggest you restore your site with your back-up.
Thanks.

**Comment by cocolate13** [comment]
Thanks a lot for your response. I'm going to change PHP version 7.3 to 7.2
and retry upgrade.
Have a nice day.
