### ISSUE TITLE
Does not detect checkboxes in multistore

### ISSUE THREAD

**Issue by Daxtermania** [PrestaShop/PrestaShop#23256]
#### Describe the bug

Does not detect checkboxes in multistore

#### Expected behavior

Remove deselected pages from the sitemap

#### Steps to Reproduce

1. Go to module configuration
2. Uncheck page 404
3. Generate Sitemap in multistore
4. Open sitemap and the 404 still there

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @Daxtermania ,
Please include screenshots as your steps are not clear.
Thanks
