### ISSUE TITLE
BO - Order page - Ajax issue - The Discount Block is not automatically updated when updating / adding a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23266]
#### Describe the bug

In the BO > Orders page > Order details page > when we update the quantity of the product => the discount value is not automatically updated 
We should refresh the page to be ok

#### Steps to Reproduce

1. Create a cart rule with free shipping
2. In the BO > Shipping > Carriers page > Enable `My cheap carrier`
3. Go to FO > Add `demo_5` (The adventure begins Framed poster) to the cart 
4. Apply the discount
4. Continue checkout
5. In the Shipping method step > select `My cheap carrier` > Place Order
6. Go to BO > Orders > Last order created 
7. Increase the quantity of the product to `2`
8. Save
9. See the error: the discount value is not updated => it is `-€6` instead of `-€3.60`
10. If you refresh the page => ok
**Screenshots**

PS1771 => ok https://drive.google.com/file/d/18Dh8cqrEjl62GOJM-6VOr2niJPdp-dDw/view?usp=sharing
PS1772build1 => NOK https://drive.google.com/file/d/1p9RJjiPty8Z1mD0XASM-gEdrivrn08mo/view?usp=sharing 

#### Additional information

* PrestaShop version: 1772build1
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
I found other steps to reproduce the issue:
1. Create an order from the FO
2. Go to BO > Catalog > Discounts page 
3. Create a cart rule without code
4. Go to BO > Orders > Last order created
5. Add a product
6. See the error > the discount block is not added 
![image](https://user-images.githubusercontent.com/16067358/107976702-42306480-6fba-11eb-8c85-a5d9a66ff390.png)
7. If you refresh the page => ok
![image](https://user-images.githubusercontent.com/16067358/107976769-5d02d900-6fba-11eb-9a2f-bad6190bacdc.png)

PS: 1771 => ok

Thank you!

**Comment by Progi1984** [comment]
Fixed by @atomiix in #23138
