### ISSUE TITLE
Missing '$template' parameter - smarty_internal_templatebase.php on line 177

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23262]
Hi,

So my server logs are getting this error:

 Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/XXXXXXXXXXX/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://xxxxxxx.xxx/en/order

TBH I don't really know how to reproduce the error. I just can see at server logs that from times to times are getting this at the "order" process.

Everything seems working, just would like to report you this.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
