### ISSUE TITLE
when a product has several combinations no reference is assigned

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23260]
#### Describe the bug

when a product has several combinations no reference is assigned

#### Steps to Reproduce

1. create a product with multiple combinations
2. write reference in each of the combinations
3. see error

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/107893598-5e85c000-6f2c-11eb-859b-5e1c3f754b0d.png)
![image](https://user-images.githubusercontent.com/62474824/107893600-604f8380-6f2c-11eb-854f-0e49833ea92e.png)

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.0, 1.7.7.1, 1.7.8.0
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@alfonsolr09 The reference field shows the "base" reference of the product, which is used, when the combination does not have reference specified.

I just tested it and it works fine:
- Click create new product.
- Set a name
- Generate two combinations, assign references to them.
- Save product
- Refresh, combination references are still there, as they should. :-)

**Comment by alfonsolr09** [comment]
Ok, base of reference
