### ISSUE TITLE
BO - Order page - Property Customization->quantity is not valid - Updating the quantity of customized product NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23265]
#### Describe the bug

In the BO > Orders > Order details page > when we try to update the quantity of the customized product for the second time => it will be NOK

#### Steps to Reproduce

1. Go to FO > Add a customized product `demo_14` to the cart with quantity = 1 > process to checkout
2. BO > Orders > View last order created
3. Increase the quantity of the product to 3 => save
4. Increase the quantity again to 4 => save 
5. See the error: the quantity ordered is NOK, it is displayed `2` instead of `4` with errors in the console
6. If you try to update it again you have different errors 
![image](https://user-images.githubusercontent.com/16067358/107960812-60d83080-6fa5-11eb-9205-8332d226c169.png)

PS: PrestaShop1769 => ok
**Screenshots**

https://drive.google.com/file/d/1cd4N5geO3hLc-wvU2webw11IujgnewNj/view?usp=sharing

#### Additional information

* PrestaShop version: 1770 / 1171 / 1772build1
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #23601
