### ISSUE TITLE
[Autoupgrade] - Cannot view suppliers after an upgrade from PS16 to PS177

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23278]
#### Describe the bug

After an upgrade from PS16124 to PS1772build1, we cannot view the list of suppliers, an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/108097973-1dec8a80-7083-11eb-9e71-ef59ee488007.png)

It is ok after an upgrade from PS16124 to PS1769

#### Expected behavior

Can view the list of products selected to the supplier

#### Steps to Reproduce

1. Install PS16124
2. Install the auto-upgrade module v4.12.0
3. Enable the button "Switch to the default theme"
4. Make an upgrade to PS1772build1
5. After upgrade complete
6. Goto BO > Catalog > Suppliers page
7. View supplier
8. See error

![image](https://user-images.githubusercontent.com/16067358/108098583-d61a3300-7083-11eb-9fc3-6b6fca50075b.png)

Upgrade from PS16124 to PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/108098740-0530a480-7084-11eb-8cd9-f145749143bf.png)

#### Additional information

* PrestaShop version: 1772build1
* PHP version: 7.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/23289
