### ISSUE TITLE
BO - Exception in Category Edit after upgrade from 1.6.1.24

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#23275]
#### Describe the bug

After upgrade from a 1.6.1.24 to 1.7.7.2 build 1, when I edit a category, I have an exception. This occurs even on category created when I was already in 1.7.7.2.

This could not be reproduced on upgrades from recent versions (1.7.2.x, 1.7.4.x, 1.7.5.x, 1.7.6.x).

#### Steps to Reproduce

1. Install a 1.6.1.24 version
2. Using autoupgrade, upgrade to 1.7.7.2 build 1.
3. After upgrade (that should be fine), go to BO > Category
4. Try to edit a category : See error

**Screenshots**

Exception : 
![update 16 to 1772 exception category](https://user-images.githubusercontent.com/55688534/108071181-b70ca880-7065-11eb-9cac-2ab380b40b15.png)

Complete exception here : 
[exception edit category 16124 upgrade.pdf](https://github.com/PrestaShop/PrestaShop/files/5988938/exception.edit.category.16124.upgrade.pdf)

#### Additional information

* PrestaShop version: 1772build1
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #23276
