### ISSUE TITLE
BO - Orders page - An exception is displayed when adding only a space in the payment method

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23287]
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22791#issuecomment-778078472
An exception is displayed when adding a payment method with an only space ` `

#### Expected behavior

Ping @PrestaShop/product-team what do you think?
In PS1769, we can successfully add this payment
![image](https://user-images.githubusercontent.com/16067358/108201293-ef70bd00-711f-11eb-9928-8b1db37dc0e5.png)

#### Steps to Reproduce

1. Go to BO > Orders > Old order page
2. Add payment with "Payment method" only space:  ` `
3. Click on Add
4. See an error

![image](https://user-images.githubusercontent.com/16067358/108201423-14fdc680-7120-11eb-86f4-4e91c0e1924e.png)

#### Additional information

* PrestaShop version: 1770, 177x
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #23694
