### ISSUE TITLE
FO - Error after upgrade from 1.6 in debug mode - Module socialsharing

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#23282]
#### Describe the bug

After upgrade from a 1.6.1.24 to 1.7.6.9 or 1.7.7.2 build 1 (maybe previous versions, did not tested all versions), when on debug mode, FO has an error when trying to access a product page.

This is linked to the obsolete socialsharing module that is not uninstalled when upgrading.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Install a 1.6.1.24 version
2. Using autoupgrade, upgrade to 1.7.6.9 or 1.7.7.2 build 1.
3. After upgrade, enable Debug mode and go to FO, try to open any product page

Works fine without debug mode enabled.

**Screenshots**

![social sharing bug](https://user-images.githubusercontent.com/55688534/108179315-c3e0d900-7105-11eb-8093-1025682477ea.png)

#### Additional information

* PrestaShop version: 1.7.6.9, 1772build1
* PHP version: N/A

**Comment by Robin-Fischer-PS** [comment]
After re-test, this bug also occurs wuth upgrade to 1.7.6.9 so it's not a regression, therefore not needed for 1.7.7.2 release.

**Comment by gericfo** [comment]
Hello, 
Version 1.6 is no longer actively supported with the **Autoupgrade module** ([see this announcement](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)). I therefore close this ticket.
Thanks!
