### ISSUE TITLE
termsAndConditions hook, checkbox not required in front

### ISSUE THREAD

**Issue by rseon** [PrestaShop/PrestaShop#23306]
#### Describe the bug

Thanks to the new `termsAndConditions` hook I added a condition with my module but the checkbox is not required during payment validation.

#### Expected behavior

The custom checkbox must be validated.

#### Steps to Reproduce

Create the new term from module :

```php
public function hookTermsAndConditions()
{
  $termsAndConditions = new TermsAndConditions();
  $termsAndConditions
    ->setText(
      'Acceptez les [conditions de location] pour continuer',
      '/conditions-locations.html'
    )
    ->setIdentifier('leasing-terms-and-conditions');
  
  return [$termsAndConditions];
}
```

#### Cause and solution

PHP cause : Necessity to set the identifier different of the original `terms-and-conditions`, because it said in the `/classes/checkout/ConditionsToApproveFinder.php` file that _If two TermsAndConditions objects have the same identifier, the one at the end of the list overrides the first one. This allows a module to override the default checkbox in a consistent manner._
[Source](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/checkout/ConditionsToApproveFinder.php#L84)

JS cause : From selector `termsCheckboxSelector` located in `/themes/_core/js/selectors.js` file.
[Source](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/selectors.js#L75)

You have to replace it from  `termsCheckboxSelector: '#conditions-to-approve input[name="conditions_to_approve[terms-and-conditions]"]'` to `termsCheckboxSelector: '#conditions-to-approve input[name^="conditions_to_approve"]'` because the id `terms-and-conditions` is different for my own checkbox.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.5

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Could you take a look at this Hook issue please ?
Thanks!

**Comment by PierreRambaud** [comment]
Did you try to change the id of your checkbox instead?

**Comment by rseon** [comment]
> Did you try to change the id of your checkbox instead?

The bug is still present whatever the id used.
Obviously it works if id is `terms-and-conditions` but in this case it will override the default behavior.

**Comment by hibatallahAouadni** [comment]
Hello @rseon 

Do you still encounter the same issue with 8.1.x?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @rseon 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
