### ISSUE TITLE
Javascript (parseJSON) 1-click error

### ISSUE THREAD

**Issue by arthurhalifax** [PrestaShop/PrestaShop#23301]
When I click upgrade prestashop now in 1-click update module I have an error:
Javascript error (parseJSON) detected for action upgradeNow"Starting restoration..."

So cannot update prestashop.

#### Additional information
<img width="1739" alt="presta" src="https://user-images.githubusercontent.com/79280230/108410831-2e8a3580-7228-11eb-860e-053b0e489f25.png">

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @arthurhalifax ,

Please check your permissions from your hosting provider :
folders: 755
files: 644
.htaccess: 664

Use this [file](https://github.com/PrestaShop/php-ps-info) to make sure your server config is compatible PrestaShop.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by arthurhalifax** [comment]
Permissions are ok and server config too.
