### ISSUE TITLE
1-click upgrade & Javascript (parseJSON) error.

### ISSUE THREAD

**Issue by arthurhalifax** [PrestaShop/PrestaShop#23300]
Hi. I have Presta 1.7.6.5 and 1-click upgrade 4.12.0 but can't making the upgrade because having an error: Error Javascript (parseJSON). Can't figure it out :/

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
