### ISSUE TITLE
You have requested a non-existent service "mbo.tab.collection.provider".

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#23305]
#### Describe the bug

Fresh install 1.7.7.1, first connection to the admin : 

You have requested a non-existent service "mbo.tab.collection.provider".
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]

#### Expected behavior

no bug

#### Steps to Reproduce

1. Install prestashop 1.7.7.1
2. Go to /admin
3. Connect

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27

**Comment by florine2623** [comment]
Hello @rflorent ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

You can also check your server configuration here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thank you

**Comment by rflorent** [comment]
I must enable the dev mode to see admin.
Trying to clear cache : 

 (1/1) FatalErrorException

Compile Error: ContainerYotegem\appDevDebugProjectContainer::load(): Failed opening required '/xxxxxxxx/var/cache/dev/ContainerYotegem/getPrestashop_RouterService.php' (include_path='/xxxxxxxxxx/vendor/pear/pear_exception:/xxxxxxxxx/vendor/pear/console_getopt:/xxxxxxxxxxxx/vendor/pear/pear-core-minimal/src:/xxxxxxxxxxx/vendor/pear/archive_tar:.:/opt/plesk/php/7.3/share/pear')

**Comment by rflorent** [comment]
> Hello @rflorent ,
> 
> Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. _You must follow the template to submit a complete bug report_.
> Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
> 
> You can also check your server configuration here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> Thank you

I follow the template. Server configuration is ok.
You have closed the issue ???

**Comment by hibatallahAouadni** [comment]
Hello @rflorent 

We close your issue cause it's not well detailed :sweat_smile: 
Could you please check this issue #22740 cause it seems similar to yours :wink: 
Please check and feedback.

PS: even when we close the issue, we always answer your questions.

Thanks!
