### ISSUE TITLE
Carrier Tracking link issues in PS1.7.7.0+

### ISSUE THREAD

**Issue by kmorgen** [PrestaShop/PrestaShop#23307]
After BO Order Admin has been migrated to Symphony, a few issues related to the Carrier tracking numbers have appeared

1. The Carrier tracking link no longer opens in a new tab in BO **Order Details** page, but in self-page.
2. The Tracking number is not a link on the **Order List** page (dropdown), which could be very convenient.

Confirmed in PS 1.7.7.1 as well.

**Comment by florine2623** [comment]
Hello @kmorgen ,

If you want to suggest any improvement to the Order page, please follow the improvement template provided.
I'll close your issue, feel free to open a new one when you gather all information.
Thanks

**Comment by kmorgen** [comment]
Since it was working in PS 1.7.6.8 (tracking links opened in new tab), I considered it a bug.
I will create it again in Feature Request then...
