### ISSUE TITLE
Add feature in ps_gdpr module for PS 1.7

### ISSUE THREAD

**Issue by goncalosribeiro** [PrestaShop/PrestaShop#23313]
**Is your feature request related to a problem? Please describe.**
The Official GDPR Compliance by PrestaShop module for PS 1.7. allows for a registered client to download the saved personal information (PDF or CSV), in their personal information page. How about for not registered clients?

**Describe the solution you'd like**
In the module configuration page, in the second item "Manage personal data" (or some similar translation), by searching for a client, and clicking on it, it is possible to see below all the saved data of that client (registered or unregistered). It should be also possible to download that information, in PDF or CSV, of that specific client, in the Backoffice module configuration page. There can be clients asking fot that information.

---
I suggest is to have a data download button on the backoffice, in the module configuration page, where the guest client information is presented, in case that client wants the data. In these cases the client must ask for the information via email or contact form.

The only buttons available, when searching for a client, is to delete data or download invoices, on each client found in the search. Click on one client and below this it is presented the same information that is downloaded when a registered client downloads on its personal information page. 

The button I suggest should appear somewhere over this information or on each client window.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team friendly reminder :wink:
