### ISSUE TITLE
Problem to upgrade Official GDPR compliance  v1.1.0 to v1.1.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#23318]
Hi

I cannot upgrade the module "Official GDPR compliance" from v1.1.0 to v1.1.1
I've tried to login to addons but nothing, the same problem with other sites

![11](https://user-images.githubusercontent.com/653230/50282159-2076d980-0452-11e9-8b60-f65fb7e24c05.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

It seems the issue has been fixed, I upgraded GDPR v1.1.0 with PS1.7.4.1 to GDPR v1.2.1 without any error.
See the attached screen record below:

https://drive.google.com/file/d/1tA5UzYARTQ4-tXXvIqL1DjwiCeAEE356/view

I close this issue cause it's fixed :wink: 
PS: thanks @pablopolyte for the fix :tada: 

Thanks!
