### ISSUE TITLE
Official GDPR module and Invalid supply argument for foreach()

### ISSUE THREAD

**Issue by loulou2852** [PrestaShop/PrestaShop#23317]
**Describe the bug**
When I try to edit the profile, I've got this error:
Warning: Invalid argument supplied for foreach() in /home/kairos/public_html/oligo/classes/form/CustomerFormatter.php on line 266
This was solved on this threat but in PM : http://forge.prestashop.com/browse/NM-982

Could you give us the correction you made.

**To Reproduce**
1. When logged and going to the identity controller (profile)
2. The error appear, on top of the page

**Screenshots**
The same case as in the threat URL

**Additionnal information**
PrestaShop version: 1.7.1.2
PHP version: 7.1.25
GDPR version: 1.1.0

Thanks in advance. If you need some acces, tell me.

**Comment by loulou2852** [comment]
Oki thanks, it's keeping a warning message on production version. Thanks in advance.

**Comment by khouloudbelguith** [comment]
@loulou2852, if you disable the debug mode on your production version, this warning will be displayed.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @loulou2852 

Sorry for the late response :sweat: 
Do you stil encounter the same issue with GDPR v1.2.1
Please check and feedback.

Thanks!

**Comment by loulou2852** [comment]
Hello @[**hibatallahAouadni**](https://github.com/hibatallahAouadni)

**I'm not working for this company anymore.**

**I don't know if it was corrected or not.** 

**Regards**
