### ISSUE TITLE
Unchecked checkboxes leaving buttons active

### ISSUE THREAD

**Issue by lesept12** [PrestaShop/PrestaShop#23319]
Hello, 

I have activated the checkboxes in the account creation form, in the client account and in the contact form. However I have a problem with the checkboxes in the account creation form and in the client account, so I need your help.
I have indeed noted that theses checkboxes leave the "Register / Save" buttons active if they are not checked whereas it's not the case for the contact form where it's not possible to click on the "Send" button until the checkbox is checked. I would like then these buttons are locked as long as the checkboxes are not checked.

Thanks a lot.

GDPR Compliance Module PS 1.7
PrestaShop version: 1.7.5.1
PHP version: 7.1.26

**Comment by hibatallahAouadni** [comment]
Hello @lesept12 

Sorry for the late response :sweat: 
I didn't manage to reproduce your issue with PS1.7.7.2 and GDPR v1.2.1, see the attached screen record below :

https://drive.google.com/file/d/1lhibkcXZ_MPLDM-Zm7MkvAA0N8qBO0VE/view

I close the issue :slightly_smiling_face: 
Thanks!
