### ISSUE TITLE
GDPR remove privacy information bottom email

### ISSUE THREAD

**Issue by jflaque** [PrestaShop/PrestaShop#23316]
Hi.

How can I remove the policy text that is inserted at the bottom of the emails? Or put a link to the policy page?

I use a PrestaShop 1.7.4.3 and the RGDP 1.1.0 module

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @jflaque 

Since we had no news from you for more than 1 year, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
