### ISSUE TITLE
ps_emailalerts with GDPR acrive checkbox behaviour

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#23324]
When the ps_emailalert module is active and the GDPR is active on the modulo too, when the user insert its email and chck the privacy checkbox both ADD TO CART and "notivy me when available" buttons will be acttivated.

https://gyazo.com/00b7632ebfdfd8bcdc920c9b5c7d2082

PS 1.7.6.7
ps_emailalerts v2.2.1
psgdpr v1.2.0

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by HartLarsson** [comment]
was a typo the version of PS is 1.7.6.7

**Comment by hibatallahAouadni** [comment]
@HartLarsson I think it's a duplicate of this one #22880 :wink:

**Comment by HartLarsson** [comment]
> @HartLarsson I think it's a duplicate of this one #22880 😉

yes is due to the same problem... thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22880
