### ISSUE TITLE
psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#23322]
psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

**Comment by hibatallahAouadni** [comment]
Hello @dariusakafest 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20519. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Thanks @evgenij-sobolev :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20519
