### ISSUE TITLE
Checkbox Not Working

### ISSUE THREAD

**Issue by artizch** [PrestaShop/PrestaShop#23326]
Hello,

Contact form is still sending even if the checkbox is unchecked.

PrestaShop ver 1.7.6.4
psgdpr 1.2.0

**Comment by hibatallahAouadni** [comment]
Hello @artizch 

Could you please provide steps to reproduce and screenshots, please.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #23319
