### ISSUE TITLE
Specific price on a product + group discount: price on FO isn't right

### ISSUE THREAD

**Issue by mcaldex** [PrestaShop/PrestaShop#23345]
#### Describe the bug

Price / discount label isn't right on the FO when you apply a specific price for a product and a discount for a certain customer group

#### Expected behavior

Price / discount label is displayed correctly: Discounted price + amount on the discount label = crossed out price (base price)

#### Steps to Reproduce

- Create a customer group "Reseller" with 20% discount on a specific category Art
- Log into the customer account
- On a product, add a specific price -> 0.29€ cents discount
- Check the product, the product doesn't have a correct price :

**Screenshots**

![Capture d’écran 2021-02-18 à 10 58 10](https://user-images.githubusercontent.com/79152536/108715806-9e940680-751b-11eb-92a3-d9cfea2d3f49.png)

#### Additional information

* PrestaShop version: 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @MHostinato 

Could you please check this issue #9966 cause it seems similar to yours.
Your issue is related to this one #23219
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @MHostinato ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
