### ISSUE TITLE
CombinationCore getIdByReference uses LIKE instead of =

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#23346]
function getIdByReference located in classes/Combination.php uses SQL LIKE instead of = when selecting IDs from the database: 

`$query->where('pa.reference LIKE \'%'.pSQL($reference).'%\'');`

I have two combinations on a single product.  One with reference "50031 BLACK-GREY" and another with reference "50031 BLACK" 

I am using this function in an override to get the combination ID and it is returning the value for the "50031 BLACK-GREY" entry when "50031 BLACK"  is being passed to $reference because the `LIKE` SQL operator is being used.

I would suggest this line is changed to

`$query->where('pa.reference = \''.pSQL($reference).'\'');`

**Comment by hibatallahAouadni** [comment]
Hello @haveyougotanypets 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
