### ISSUE TITLE
It is not possible (yet) to rebuild exactly the same ZIP using git tag

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#23342]
## What should be possible in theory

1. PrestaShop maintainers publish PrestaShop 1.7.7.1
- a downloadable ZIP
- a git tag on this repository

2. A user wants to validate the integrity of a 1.7.7.1 ZIP he has found.

He checkouts this repository, the 1.7.7.1 tag and runs `php tools/build/CreateRelease.php --version="1.7.7.1"` This creates a new ZIP.

3. Since the user has checked out the git tag, the ZIP being distributed by PrestaShop and the ZIP being rebuild should be identical.

**But these ZIP are not identical**. Because the 2 following files are randomly generated every time:
- autoload_real.php
- autoload.php

## What needs to be fixed

We need to fix Composer configuration to make the generation of Composer autoload classes _predictable_ .

**Comment by atomiix** [comment]
Fixed by #23343
