### ISSUE TITLE
Discounts (promo codes) - multiple errors

### ISSUE THREAD

**Issue by IvoRabush** [PrestaShop/PrestaShop#23358]
#### Describe the bug

Hello,
I'm writing regarding previous reported bug and not fixed issue #10465 bause of incorrect research.

#### Expected behavior
No matter if you make the order from the front office or back office, no matter what cart rules and conditions you make, even with only 1 cart rule (promo code) the discount amount is NEVER UPDATED when you update an order from the back office no matter if the promocode is for the whole order or is for a specific product restriction and even if you remove the product itself

#### Steps to Reproduce

1. Make a simple cart rule (promocode)
2. from the front office make an order, for example with 2 products
3. in the back office edit the order products:

- Remove 1 quantity => the discount amount remain the same - WRONG
- add quantity => the discount amount remain the same - WRONG
- add a new product => the discount amount remain the same - WRONG
- remove a product => the discount amount remain the same - WRONG

As of PS v1.7.6 when you delete a product from the order, it deletes the cart rules used in the cart from the table cart_cart_rule. In previous versions this relation was not touched.

#### Additional information
* PrestaShop version: tested on version from 1.7.5.1 and all above

#### Expected behavior
When you create 2 cart rules (product restriction), the discount is calculated correctly on the cart - front office.
When you return/refund the order, the discounts in the Credit note are summed and it's not correct. The amount of the credit note is higher then the invoice amount => refund more then what was paid

#### Steps to Reproduce

1. Create cart rule 1 PROMOCODE1 for product1 and product2
2. Create cart rule 2 PROMOCODE2 for product1
3. make a new order from the front office with product1 and product2 and use both PROMOCODE1 and PROMOCODE2
In the back office, when you open to view the order, in the discount section you will see 2 discounts. The problem here is that the discounts are calculated separately and independently without taking in consideration the second one.
If you calculate the sum of discount1 + discount2 it's different then the total discount amount in the order totals
![image](https://user-images.githubusercontent.com/32366618/108827607-816c4000-75ce-11eb-9515-2a7041437a10.png)

As you can see on the screenshot, the sum of all the discounts is: 8.7 + 6 + 7.5 + 61.24 + 104.77 = 188.21
But in the totals summary, the discount amount is 171.52
In some orders the difference is much higher
4. Create a return/refund and include all the discounts . The amount of the credit note is higher then the amount of the invoice.
It appears that we have to pay the customer

**Comment by hibatallahAouadni** [comment]
Hello @IvoRabush 

Thanks for the detailed bug report :rocket: 
Could you please check this issue #23266 cause it seems similar to your first issue and I think this issue #18319 is related to your second issue.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @IvoRabush ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
