### ISSUE TITLE
Classic theme lighthouse and accessibility could be improved

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#23352]
#### Describe the bug

The classic theme could be a bit more improved regarding lighthouse and accessibility improvements

#### Expected behavior

Some aria labels are missing, some images doesn't have any sizes in markup

#### Steps to Reproduce

1. Go to any page on the classic theme
2. Open the chrome console
3. Launch a lighthouse test, that would be enough to see some errors (we can't fix these all)

#### Additional information

* PrestaShop version: develop

**Comment by fdonnet** [comment]
@NeOMakinG for the images it can be super great to use the img theme configuration to get width and height (without px). example=> width="446" height="350" and be sure we have height  on auto in the css. 

If the shop owner put width 100% for img in his CSS and with that kind of definitions, the target browser will be able to book empty space for the images before the content is rendered.
It's a immediate gain in the Lighthouse CLS score (used in the page speed test for Google).

Maybe it can be an additionnal improvement that can be integrated with webp support 1.7.8 (take care of Google new KPIs)... ?

**Comment by NeOMakinG** [comment]
@fdonnet Can you check the PR and tell me if it's right ? :)

I plan to add src-sets myself but webp will need some backend devs :)

**Comment by fdonnet** [comment]
@NeOMakinG seems good but maybe it will have strange side effects if shop owners change their image generation parameters and regenarate their pictures. If the proportion (aspect ratio) changes they need to change the .tpl(s) to hard code their width and height (new aspect ratio)... I don't know if a lot of people change image aspect ratio when they use classic or classic_child themes... 
But maybe it can cause some issues compared to specify nothing and have a bad CLS score...
If it's not too heavy it can be useful to retrieve the aspect ratio from the image configuration ?

**Comment by NeOMakinG** [comment]
@fdonnet I tried but every sizes are not fine enough :/
