### ISSUE TITLE
BO - The browser is unable to show the error message on an hidden element.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23365]
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22942#issuecomment-781249540
As commented [here](https://github.com/PrestaShop/PrestaShop/pull/22942#issuecomment-781380741) by @NeOMakinG 
An error displayed in the console when creating category,  it's due to radio elements which are inside a `display: none;` property. so the browser is unable to show the error message on an hidden element.

#### Expected behavior

Select the highest parent category automatically .

#### Steps to Reproduce

1. If this [PR](https://github.com/PrestaShop/PrestaShop/pull/22942) is merged
2. Use this PR: https://github.com/PrestaShop/prestashop-ui-kit/pull/137
3. Enable Multistore Context
4. Create a new shop
5. Go to BO > Catalog > Categories page
6. Add a new root category > Save
7. At this step, you are in the Root category list 
![image](https://user-images.githubusercontent.com/16067358/108875893-f145ef00-75fd-11eb-81a4-af10fd40e955.png)
8. Select only the first shop/second shop
10. Add a new category > the Parent category is not selected
11. Set only the Name & save
12. See the error on the console

![image](https://user-images.githubusercontent.com/16067358/108875952-01f66500-75fe-11eb-8548-2554786a814a.png)

Previously we have this alert 
![image](https://user-images.githubusercontent.com/16067358/108876012-1175ae00-75fe-11eb-8c91-05dbacd45c6c.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by atomiix** [comment]
@khouloudbelguith I've not been able to reproduce the issue, I'm maybe missing something but if I try to save without selecting a parent category, I got this:
<img width="831" alt="Capture d’écran 2021-06-08 à 14 32 19" src="https://user-images.githubusercontent.com/2168836/121185758-b1321180-c866-11eb-908e-efb104e51001.png">

And if I remove the `required` attribute of the input and hit save, I got this:
<img width="840" alt="Capture d’écran 2021-06-08 à 14 33 12" src="https://user-images.githubusercontent.com/2168836/121185887-cdce4980-c866-11eb-93cf-14843833046d.png">

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Yes, there is an Html alert now, but there are some errors in the console
https://drive.google.com/file/d/1qc1Jr3Uychg_5pLZG5ZLi29JZaYtG_Ds/view?usp=sharing

What do you think?

Thank you!

**Comment by NeOMakinG** [comment]
> https://drive.google.com/file/d/1qc1Jr3Uychg_5pLZG5ZLi29JZaYtG_Ds/view?usp=sharing

It's due to the fact that hidden checkboxes are required, as they are hidden, the browser can't focus it to display errors

I doubt we can deal with it, except maybe not make it required but deal with it using JS

It's not blocking by the way

**Comment by khouloudbelguith** [comment]
Hi @atomiix, @NeOMakinG,

So why do you think, the error is the console: it is a bug that can be fixed?

Thank you!

**Comment by NeOMakinG** [comment]
Pretty hard to fix tbh, and can introduce a lot of bugs (it's basically developing a browser basic functionality :( )

**Comment by Progi1984** [comment]
Fixed in #25046 by me
