### ISSUE TITLE
Erreur d'encodage des caractères htmls s'affichent dans l'avis client

### ISSUE THREAD

**Issue by 01design** [PrestaShop/PrestaShop#23361]
#### Describe the bug

Sur la page produit, les avis client s'affichent avec des caractères html (<br /> ...) 

#### Expected behavior

Quel est le fix à apporter pour formater correctement les messages et ne plus voir les avis déformés par ces caractères

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: Prestashop 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.
Please next time, fill all the blocks in the provided **template to submit a complete bug report**.

Thank you

**Comment by 01design** [comment]
Hello

sorry for the inconvenience, I did a new issue in english trying to give all the details of my Prestashop bug.

Thanks

Yvan
