### ISSUE TITLE
Products not centered in home with default theme

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#23372]
#### Describe the bug

Products are not centered correctly in the home container

#### Steps to Reproduce

1. Install PS
2. Check home product block

![image](https://user-images.githubusercontent.com/5071263/108965174-cbabfa80-767c-11eb-9f78-34c04fecc7a9.png)

#### Additional information

* PrestaShop version: PS 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

Thanks for your issue! 
I reproduced with PS1.7.7.0, 1.7.7.1 and 1.7.7.2. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: related to #22221

Thank you

**Comment by matks** [comment]
@NeOMakinG there's a PR https://github.com/PrestaShop/PrestaShop/pull/23381 from @idnovate 😄

**Comment by Progi1984** [comment]
Fixed by #23388
