### ISSUE TITLE
BO - Order statuses - An error is displayed when deleting an order status with French language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23379]
#### Describe the bug

After fresh install PS with English language & France country, when we try to delete a new order status with french language => an error is displayed
![image](https://user-images.githubusercontent.com/16067358/108981633-32d1ab00-768d-11eb-9e4a-780ed2843cc4.png)

#### Steps to Reproduce

Install PS with English language & France country
Go to your profile > change the employee language to french
Go to BO > Shop Parameters > Order Settings > Statuses page
Create new Order status 
Try to delete it
See error

**Screenshots**

PS177 => NOK
![image](https://user-images.githubusercontent.com/16067358/108981965-952aab80-768d-11eb-81cc-0a5010dfcd2d.png)

PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/108981934-89d78000-768d-11eb-8457-68601d90b756.png)

#### Additional information

* PrestaShop version: 1770, 1772, 177x
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #24094
