### ISSUE TITLE
Undefined _PS_ADMIN_DIR_ in welcome module

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#23370]
#### Describe the bug

The `welcome` module is producing PHP warning related to the `_PS_ADMIN_DIR_` constant which is not defined.

> PHP Warning:  Use of undefined constant _PS_ADMIN_DIR_ - assumed '_PS_ADMIN_DIR_' (this will throw an Error in a future version of PHP) in /home/www-data/prestashop/modules/welcome/OnBoarding/Configuration.php on line 281

#### Expected behavior

No PHP warning.

#### Steps to Reproduce

This issue happens when installing/upgrading a module (can be any module) from command line:
```
php bin/console prestashop:module install modulename -q --no-debug;
php bin/console prestashop:module upgrade modulename -q --no-debug;
```

#### Additional information

* PrestaShop version: 1.7.7.1

**Comment by matks** [comment]
Hi @Seb33300 I think this is similar to https://github.com/PrestaShop/PrestaShop/issues/14173

Basically the Symfony Commands do not load/setup all items needed by PrestaShop legacy framework to function.

A first step is here https://github.com/PrestaShop/PrestaShop/pull/21125 to fix it but looks like there are other things we need to add.

A workaround for you would be to require the defines files:

```
        require_once __DIR__ . '/../../config/defines.inc.php';
```

**Comment by marionf** [comment]
Hello, 

The welcome module will be archived with the V8.0.0, so I close this issue.

**Comment by Seb33300** [comment]
@marionf this issue is still valid on PrestaShop 8.1

This is not related to the welcome module but to the command line `php bin/console prestashop:module`
The welcome module was just an example.

I can still reproduce the error for example with:
```
php bin/console prestashop:module uninstall autoupgrade
```

Note that a workaround is to force the prod env:
```
php bin/console prestashop:module uninstall autoupgrade --env=prod
```
If you force the prod env, warning are ignored and the command doesn't crash.

**Comment by Seb33300** [comment]
@AureRita please reopen
