### ISSUE TITLE
No me cargan los comentarios en versión 1.7.6.8

### ISSUE THREAD

**Issue by mgonzalez88** [PrestaShop/PrestaShop#23383]
#### Describe the bug

He instalado el módulo Comentarios sobre el producto (v.4.2.1).

Me he traído los comentarios de la antigua versión de mi tienda (Preshop 1.6) y me cargan bien en el módulo y se asocian correctamente con los productos pero, no me pinta nada en la pestaña comentarios.

No tengo la web correctamente maqueetada aún pero no cargan los comentarios en la pestaña "Comentarios".

Me da error JSON. 

Paso capturas de todo.

¿Podrían darme una idea de qué puede estar pasando?

Muchas gracias.

**Screenshots**

![Captura de pantalla 2021-02-24 a las 12 57 11](https://user-images.githubusercontent.com/79579137/108997515-f8253e00-769f-11eb-8976-58e24fdeb136.png)
![Captura de pantalla 2021-02-24 a las 12 57 22](https://user-images.githubusercontent.com/79579137/108997530-fa879800-769f-11eb-8705-dd77a85303bf.png)
![Captura de pantalla 2021-02-24 a las 12 57 32](https://user-images.githubusercontent.com/79579137/108997532-fb202e80-769f-11eb-9407-3c0d4e2829a4.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @mgonzalez88 ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by mgonzalez88** [comment]
Hello!

I have installed the Product Feedback module (v.4.2.1). Link below:

 https://www.prestashop.com/es/blog/comentarios-de-clientes

I have download the comments from old version of my store (Preshop 1.6) to the new version.

They load well in the module and are correctly associated with the products but it doesn't paint anything in the comments tab.

I do not have the website properly formatted yet but in the captura you can see they do not load the comments in the "Comments" tab.

I get JSON error.

I send you captures of everything.

Can you help me with this trouble?

Thanks a lot. 

Regards.
![Captura de pantalla 2021-02-24 a las 12 57 11](https://user-images.githubusercontent.com/79579137/109005176-f52f4b00-76a9-11eb-9221-fc090025163d.png)
![Captura de pantalla 2021-02-24 a las 12 57 22](https://user-images.githubusercontent.com/79579137/109005178-f5c7e180-76a9-11eb-9587-c844ea08a542.png)
![Captura de pantalla 2021-02-24 a las 12 57 32](https://user-images.githubusercontent.com/79579137/109005180-f6607800-76a9-11eb-977a-ef48426ed090.png)

**Comment by hibatallahAouadni** [comment]
Hello @mgonzalez88 

Could you please check these issues #23218 & #22481 cause it seems similar to yours.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #23218
