### ISSUE TITLE
Add "show products" switch to category settings

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23387]
#### Is your feature request related to a problem?

When dealing with bigger stores with with wide range of products, the root categories start to act as some kind of a router to deeper categories. Example - category **Garden** - you open the category and you have 10000 products on one pile. Stuff for cutting grass, grills, pools, whatever.

People wouldn't really browse this category and it's better to route them directly to some of the subcategories.
Loading of these big categories takes extremely long, you need to create specific faceted search filters in order not to have one big pile of filters, etc.

#### Describe the solution you'd like

I think it would be good to add an option to category settings called "Show products". The merchant could disable the product list for this selected category and make the user go right to one of the subcategories.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

It seems a little bit complicated :sweat_smile: 
Could you please provide some screenshots or maybe a real exemple :sweat_smile: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Ok, imagine you are expanding and expanding your product portfolio. Suddenly, you get to a point where the amount of products in categories is attacking thousands. The whole store slows down.

So you start organizing your products to big categories like **Sport & Outdoor**.
In this category, there are winter sports, fitness, camping stuff, cyclist stuff, ball sports, tennis stuff, swimming stuff. Just everything.

Is there really a point in showing 15000 products on one pile, when you open **Sport & Outdoor**?

See an example on one of the biggest czech ecommerce stores:
- https://www.mall.cz/sport - Sport, no products
- https://www.mall.cz/zimni-sporty - Winter sport, no products
- https://www.mall.cz/sjezdove-lyzovani - Downhill skiing - no products (still no point in showing boots, skis, mounts on one pile)
- https://www.mall.cz/lyze - Skis - finally a list of products

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I can see what you mean :wink: 
But in reality, the system doesn't display 15000 products on one pile when you open **Sport & Outdoor** (for exmple).
Cause, there's pagination and it will only display 20 (or 12 in my case) products :wink: 

![image](https://user-images.githubusercontent.com/23308427/109817976-cd546000-7c32-11eb-9eeb-1a2a001a809d.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni See a real example
https://www.dobracena.cz/570-kuchyn - 8959 products, 5188 ms load time
https://www.dobracena.cz/22-odpadkove-kose - 162 products, 381 ms load time

I think pagination does not help so much, when the time loads 13x slower. 😄 If I was the customer, I would leave the store and shop elsewhere... And this time is on 12 core Ryzen with nVme SSDs, on a common hosting, the page would like like 10 seconds.
