### ISSUE TITLE
Chrome issue bloced google analitycs 

### ISSUE THREAD

**Issue by kwiatkowska** [PrestaShop/PrestaShop#23384]
I started identifying traffic for my page and I have a issue in chrome developer console (ctrl + shift + I)
The problem is on every page, 

ERRORS: 
v_64_e13c4629507637141815de2610769b2f.js:648 Uncaught ReferenceError: com is not defined

0 {[comms init: ], [} ],} 
api.js:5770 No lang code, default [en] used
DevTools failed to load SourceMap: Could not load content for https://cashierui-api.secure.eservice.com.pl/sm/d5e23329d3db3a6335d7dccd01ed5def4ac9aa67db7db3d287d19298b9fa5e3b.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
api.js:6367 365 error parsing received postMessage: SyntaxError: Unexpected token o in JSON at position 1; SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at receive (https://cashierui-api.secure.eservice.com.pl/js/api.js:5274:21)
api.js:6367 3448 error parsing received postMessage: SyntaxError: Unexpected token o in JSON at position 1; SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at receive (https://cashierui-api.secure.eservice.com.pl/js/api.js:5274:21)

ERRORS: 
v_64_e13c4629507637141815de2610769b2f.js:648 Uncaught ReferenceError: com is not defined

0 {[comms init: ], [} ],} 
api.js:5770 No lang code, default [en] used
DevTools failed to load SourceMap: Could not load content for https://cashierui-api.secure.eservice.com.pl/sm/d5e23329d3db3a6335d7dccd01ed5def4ac9aa67db7db3d287d19298b9fa5e3b.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
api.js:6367 365 error parsing received postMessage: SyntaxError: Unexpected token o in JSON at position 1; SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at receive (https://cashierui-api.secure.eservice.com.pl/js/api.js:5274:21)
api.js:6367 3448 error parsing received postMessage: SyntaxError: Unexpected token o in JSON at position 1; SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at receive (https://cashierui-api.secure.eservice.com.pl/js/api.js:5274:21)

Best regards,

**Comment by hibatallahAouadni** [comment]
Hello @kwiatkowska 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
@kwiatkowska it's probably due to the code of  for cashierui, not PrestaShop.
