### ISSUE TITLE
Cant found PS_COOKIE_CHECKIP on phpadmin

### ISSUE THREAD

**Issue by ryukuroha** [PrestaShop/PrestaShop#23395]
#### Describe the bug

Heyy well i had this prob like prestashop keep logging me out so i've decided to set up the  value to 0 in the cookies part but couldn't found th file on phpadmin
anyone knows how to find it or upload it on phpadmin from cpanel 
thaaanks!!!

**Screenshots**

![rrtrr](https://user-images.githubusercontent.com/79607558/109068889-50ab0a00-76a5-11eb-9e07-643838671459.png)

#### Additional information

* PrestaShop version: 1.7.7.1

**Comment by SimonGrn** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
