### ISSUE TITLE
New message notification count never got reset

### ISSUE THREAD

**Issue by ant0nioli** [PrestaShop/PrestaShop#23399]
#### Describe the bug

As I can see the Total number of customer messages in Customer Service are counted for the notifications, whether they were already handled or not.

The issue, in my case, is visible in the top right corner notification area, and also in the favicon if the Order Notifications on the Favicon module is activated.

Basically the number of the incoming messages notification never goes down. Keeps growing.

The options the that triggers the problem are:

- Advanced Parameters > Administration > Show notifications for new messages
- Order Notifications on the Favicon module > New messages

#### Expected behavior

Only the not handled messages should count for generating notifications

#### Steps to Reproduce

1. Configure imap for Customer Service (screenshot attached)
2. Activate the option: Advanced Parameters > Administration > **Show notifications for new messages**
3. And/Or activate the option in the module configuration: Order Notifications on the Favicon module > **New messages**
4. Receive an email to the address configured for Customer Service
5. The notification number will grows to 1 (if it is the first message) on right corner notification area (case step 3), and in the favicon (case step 4).
6. Handle the received message in the Customer Service and mark the thread as handled
7. The notification will **not** go back to 0, the number keeps being the same it was before the marking the thread as handled.

![image](https://user-images.githubusercontent.com/1677823/109158727-0a70ac00-7774-11eb-85c4-227caebae790.png)

#### Additional information

* PrestaShop version: 1.7.7.1 
* PHP version:  7.3

**Comment by hibatallahAouadni** [comment]
Hello @ant0nioli 

Could you please provide clear and concise steps to reproduce, because it's a bit blurry :sweat_smile: 
And provide your PHP version and your PS exact version.
Please edit your issue content and notify me.

Thanks!

**Comment by ant0nioli** [comment]
Hi @hibatallahAouadni I edited my submission, I hope it's clearer now. Do you? :smile: 

Thanks!

**Comment by florine2623** [comment]
Hi @ant0nioli ,

I can't reproduce your issue with PS 1.7.7.0, PHP 7.3. Please check my screen record : https://drive.google.com/file/d/1jZfQeVtBRZUr25qu0N7hIsraN2KAfnAe/view 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ant0nioli** [comment]
Hi @florine2623 thank you for your reply.

Actually something weird just happened.

To reproduce exactly what you did in your video, I disabled the **Order Notifications on the Favicon module** and activated back the **Advanced Parameters > Administration > Show notifications for new messages** that is the configuration I was using before submitting the issue. 

When I saved this configuration I got an error message `The limit chosen is larger than the server's maximum upload limit. Please increase the limits of your server.` Never had this error response before.

After that I sent an email via form (as you did) and the problem magically seems to be resolved... Maybe something changed with the last system update, I don't know.

Thank you, if I got any news I'll keep you posted.
