### ISSUE TITLE
[BO] Can't create Order

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23397]
#### Describe the bug

Can't create order, Because we can't add product to cart.

#### Expected behavior

Creation should be fine

#### Steps to Reproduce

1. Go to orders -> new order
2. Choose customer
3. Search a product and click on add to cart
4. Product not added to cart

![image](https://user-images.githubusercontent.com/48441421/109130650-44c95180-7752-11eb-844c-1f6049437903.png)

PS : a jQuery exception is displayed after clicking on add to cart
![image](https://user-images.githubusercontent.com/48441421/109130787-69252e00-7752-11eb-8095-c89b66071b49.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.4

**Comment by NeOMakinG** [comment]
Gonna take a look
