### ISSUE TITLE
When a customer edits an used delivery address: no shipping methods are available

### ISSUE THREAD

**Issue by valentin-anamorphik** [PrestaShop/PrestaShop#23398]
#### Describe the bug

When a customer edits an used delivery address: no shipping methods are available.
`ps_cart` table: `id_address_delivery`/`id_address_invoice` columns were updated to new address ID
**But**  `id_address_delivery` column in `ps_cart_products` table did not update

I think the problem is here
```
# classes/Cart.php

/**
     * Update the Address ID of the Cart.
     *
     * @param int $id_address Current Address ID to change
     * @param int $id_address_new New Address ID
     */
    public function updateAddressId($id_address, $id_address_new)
    {
        $to_update = false;
        if (!isset($this->id_address_invoice) || $this->id_address_invoice == $id_address) {
            $to_update = true;
            $this->id_address_invoice = $id_address_new;
        }
        if (!isset($this->id_address_delivery) || $this->id_address_delivery == $id_address) {
            $to_update = true;
            $this->id_address_delivery = $id_address_new;
        }
        if ($to_update) {
            $this->update();
        }

        $sql = 'UPDATE `' . _DB_PREFIX_ . 'cart_product`
        SET `id_address_delivery` = ' . (int) $id_address_new . '
        WHERE  `id_cart` = ' . (int) $this->id . '
            AND `id_address_delivery` = ' . (int) $id_address;
        Db::getInstance()->execute($sql);

        $sql = 'UPDATE `' . _DB_PREFIX_ . 'customization`
            SET `id_address_delivery` = ' . (int) $id_address_new . '
            WHERE  `id_cart` = ' . (int) $this->id . '
                AND `id_address_delivery` = ' . (int) $id_address;
        Db::getInstance()->execute($sql);
    }
```

I applied this fix #15399 but i still have the problem

#### Expected behavior

Update `id_address_delivery` column in `ps_cart_products` table with new address ID.

#### Steps to Reproduce

1. customer added products to the cart
2. customer updated/deleted his address (during checkout) (ID: 1)
3. customer create a new address (ID: 2)
4. In the database `ps_cart` table: `id_address_delivery`/`id_address_invoice` columns were updated to new address ID (ID: 2)
5. `ps_cart_products` table: `id_address_delivery` did not update (ID: 1).

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-728140707

**Comment by hibatallahAouadni** [comment]
Hello @valentin-anamorphik 

As you know you issue is a duplicate of #9932 and it's already fixed with PS1.7.7.0

> I applied this fix #15399 but i still have the problem

Well, I can't tell where is the problem, cause it works for me with PS1.7.7.0 :confused: 

Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could someone please help @valentin-anamorphik to fix his problem :pray: thanks in advance.

**Comment by kpodemski** [comment]
I suggest to upgrade to 1.7.7 and just have it fixed as it should be :)

**Comment by valentin-anamorphik** [comment]
It's complicated to update PrestaShop !

Maybe a solution without updating ?


https://github.com/orgs/PrestaShop/teams/prestashop-core-developers
https://github.com/orgs/PrestaShop/teams/prestashop-maintainers

**Comment by matks** [comment]
> It's complicated to update PrestaShop !
> 
> Maybe a solution without updating ?

It can be complicated but it is necessary to benefit from essential deliverables such as security issue patches and php compatibility increase 😉 

If you want to venture into the world of "modifying my PS 1.7.6 to benefit from bugfixes from PS 1.7.7 without updating" you can but I will close this issue 😉  as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project (and this issue is not a bug or a new feature).

You might find people to help you
- on Slack https://github.com/PrestaShop/open-source/blob/master/slack/readme.md
- on PrestaShop community forums https://www.prestashop.com/forums/

**Comment by valentin-anamorphik** [comment]
This issue is not a bug ???? 😂

**Comment by matks** [comment]
@valentin-anamorphik this issue is fixed on PS 1.7.7 😉  https://github.com/PrestaShop/PrestaShop/issues/9932

**Comment by valentin-anamorphik** [comment]
@matks Thank you to release a version with bug...

**Comment by matks** [comment]
@valentin-anamorphik I think you dont understand how a massive software like PrestaShop evolves 😄  . No worries, a lot of people are confused.

Everything is explained here https://m.signalvnoise.com/software-has-bugs-this-is-normal/

**Comment by valentin-anamorphik** [comment]
I understand perfectly !!

But PrestaShop 1.7.6 has many bug ...

**Comment by matks** [comment]
If you want less bugs in PrestaShop, the best way is to contribute to the project, helping to make it better.

PrestaShop is an open source, community project. If you find that PrestaShop has issues, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.
