### ISSUE TITLE
Disappearance of the cronjob module and impossibility to update the exchange rates.

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#23404]
#### Describe the bug

The Cronjob module is no longer available for download from the PrestaShop back office.

The exchange rate updates being based on the specific use of this module, then it is a major regression preventing the basic operation of PrestaShop 1.7 by questionable development choices.

#### Expected behavior

to be able to use a historical module essential to the good functioning of PrestaShop by the choices of historical development of the 1.7, because the 1.6 is absolutely not impacted.

#### Steps to Reproduce

https://youtu.be/oARIiod1qtE

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

AFAIK this module will be archived soon, it’s no longer maintained.
But you still can fork it from [here](https://github.com/PrestaShopCorp/cronjobs) if you need it for your shop.

Let's confirm it with the Product Team :wink: 
Ping @PrestaShop/product-team am I right? will this module be archived soon?

Thanks!

**Comment by jeckyl** [comment]
So, if this module is brought to disappear PrestaShop is no longer able to propose the automatic update of exchange rates.
It would be a good idea to inform the users and remove this option from all versions 1.7 available to date.

**Comment by ttoine** [comment]
Please have a look here:
https://github.com/PrestaShopCorp/cronjobs

**Comment by marionf** [comment]
Hello @jeckyl 

This module has not been archived. It is pushed by API for the versions from 1.5 to 1.6.1.24 and is not compatible with 1.7, that is the reason why you can't find it in 1.7

You can find cronjob module compatible with 1.7 on the marketplace like this one for example: https://addons.prestashop.com/fr/outils-administration/48669-sht-cronjobs.html

As this module isn't included in the core and not maintained by the core team but by PrestaShop Corp, I close this issue

**Comment by jeckyl** [comment]
> Hello @jeckyl
> 
> This module has not been archived. It is pushed by API for the versions from 1.5 to 1.6.1.24 and is not compatible with 1.7, that is the reason why you can't find it in 1.7
> 
> You can find cronjob module compatible with 1.7 on the marketplace like this one for example: https://addons.prestashop.com/fr/outils-administration/48669-sht-cronjobs.html
> 
> As this module isn't included in the core and not maintained by the core team but by PrestaShop Corp, I close this issue

is it a joke ?

**Comment by marionf** [comment]
You can submit an issue or PR for this module here: https://github.com/PrestaShopCorp/cronjobs

**Comment by jeckyl** [comment]
> You can submit an issue or PR for this module here: https://github.com/PrestaShopCorp/cronjobs

realy ?

Your only answer to a blocking error on the functioning of Prestashop that makes it obsolete to the new European regulations and the international market is that I can correct a module that you considered out of date even though you based part of the solution's functioning on it in 1.7.

I produced a video to make the worry jump out at you, to avoid language misunderstandings, but no, I think the worry is deeper.


Vraiment ?

Votre seule réponse à une erreur bloquante sur le fonctionnement de Prestashop et qui le rend caduc aux nouvelles réglementations Européennes et au marché internationale est que je peux corriger un module que vous avez estimé périmé alors que vous avez basé une partie du fonctionnement de la solution dessus en 1.7.

J'ai produit une vidéo pour que le souci vous saute aux yeux, pour éviter els incompréhensions de langage, mais non, je crois que le souci est plus profond.

**Comment by marionf** [comment]
> Your only answer to a blocking error on the functioning of Prestashop that makes it obsolete to the new European regulations and the international market is that I can correct a module that you considered out of date 

That's not the only answer and not blocking, as I said, you can buy and install a cron module on the marketplace
You can also configure a cron task through your hosting provider

> even though you based part of the solution's functioning on it in 1.7.

That should not be the case, since cronjob module is a service provided by PrestaShop Corp, the core should not have any dependency with it. Please see https://github.com/PrestaShop/PrestaShop/issues/23412

**Comment by jeckyl** [comment]
Thank you in any case for taking the time to answer me.

**Comment by HartLarsson** [comment]
if the currency are updated automatically only by the cronjob module not available anymore on 1.7 version how we can do that job? Manually every day?

![image](https://user-images.githubusercontent.com/16102074/111365106-5f785180-8692-11eb-8bc1-08411655e1a0.png)

if we purchase another module for cronjob will not enable the currency update so we need to push the UPDATE button every day manually??

**Comment by jeckyl** [comment]
> if the currency are updated automatically only by the cronjob module not available anymore on 1.7 version how we can do that job? Manually every day?

You can get my free module to k,ow the cron url https://www.prestashop.com/forums/topic/1043726-free-module-know-the-url-to-call-to-update-the-currency-exchange-rate-on-prestashop-17/

> if we purchase another module for cronjob will not enable the currency update so we need to push the UPDATE button every day manually??

You can use a free cron module for that https://www.prestatoolbox.com/free-prestashop-modules/115-crontab.html

**Comment by matks** [comment]
> if the currency are updated automatically only by the cronjob module not available anymore on 1.7 version how we can do that job? Manually every day?
> 
> ![image](https://user-images.githubusercontent.com/16102074/111365106-5f785180-8692-11eb-8bc1-08411655e1a0.png)
> 
> if we purchase another module for cronjob will not enable the currency update so we need to push the UPDATE button every day manually??

The cronjobs module is only a mean to automatically refresh live exchanges, badly explained in the interface (this will be fixed). As mentioned by @jeckyl any other cron module can do the job, and you don't need to use a module ; you can also use a crontab. You can see an example here https://www.prestashop.com/forums/topic/1012820-solved-create-a-cronjob-to-auto-update-exchange-rate/

**Comment by matks** [comment]
I wrote a [short explanation](https://github.com/PrestaShop/docs/pull/894/) in the devdocs for this topic 😊  it's not merged yet but you can read it here https://github.com/PrestaShop/docs/blob/511438335340b94aae338af4f2a37bb8764c00ec/src/content/1.7/faq/pricing.md
