### ISSUE TITLE
[BO] Carrier Tracking URLs in PS 1.7.7.0+

### ISSUE THREAD

**Issue by kmorgen** [PrestaShop/PrestaShop#23401]
**Describe the Bug:**
After BO Order Admin has been migrated to Symphony, a few issues related to the Carrier tracking numbers have appeared

1. The Carrier tracking link no longer opens in a new browser tab ("target="_blank") in BO **Order Details** page, but in self-page.
2. The Tracking number is not a link on the **Order List** page (dropdown)

**Expected Behavior:**
1. Carrier tracking links in BO **Order Details** page should open in new browser tab ("target="_blank")
ex on PS 1.6.1.24 :
![Capture d’écran 2021-02-26 à 17 51 54](https://user-images.githubusercontent.com/16019289/109329975-7da11d80-785b-11eb-8349-a85742f7a1cc.png)

2. The Tracking number on the **Order List** page (dropdown) should also be the same url as well, and also open in new browser tab ("target="_blank") as well.
![Capture d’écran 2021-02-26 à 17 51 14](https://user-images.githubusercontent.com/16019289/109329760-429eea00-785b-11eb-967d-071c64ef5684.png)

**Steps to reproduce:**
- Add a Carrier tracking number to an order (from a carrier with a pre-defined tracking URL included an @ to represent the tracking number).
- Click on the Carrier tracking url in BO Order page (will open in same window/tab).

**Additional Information:**
Prestashop version: 1.7.7.2
PHP Version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @kmorgen 

Please edit your issue description and **follow the provided template to submit a complete bug report** and fill all the blocks.

![image](https://user-images.githubusercontent.com/23308427/109145225-806c1780-7762-11eb-9ad5-2aea4857a055.png)

We need those details to reproduce the issue and fix it ASAP :wink:

Thanks!

**Comment by kmorgen** [comment]
Changed it now.

**Comment by florine2623** [comment]
Hi @kmorgen ,
Can you send a screenshot of Carrier tracking url in BO Order page in previous version of PS (1.7.6.8), and current version of PS (1.7.7.2) ?

**Comment by kmorgen** [comment]
**PS 1.7.6.8:**
![Order-details-tracking-PS1768](https://user-images.githubusercontent.com/4300688/109291903-e1125780-7829-11eb-8abd-ff411bb6b695.jpg)

**PS 1.7.7.2:**
Order details:
![Order-details-tracking-PS1772](https://user-images.githubusercontent.com/4300688/109291970-f4252780-7829-11eb-966a-26644c4bbdd0.jpg)

Order list (here the tracking number is not a URL):
![Order-list-tracking-PS1772](https://user-images.githubusercontent.com/4300688/109293352-f5efea80-782b-11eb-98f3-401f665c026c.jpg)

**Comment by florine2623** [comment]
Hello,

Thanks.
In previous PS version, there was no link on the tracking number :
example in PS 1.7.6.5 :
![Capture d’écran 2021-02-26 à 15 13 38](https://user-images.githubusercontent.com/16019289/109310836-54759280-7845-11eb-9614-55673a9e1182.png)
In PS 1.7.7.0 : 
![Capture d’écran 2021-02-26 à 15 15 13](https://user-images.githubusercontent.com/16019289/109310939-70793400-7845-11eb-9d91-7c741e642eb3.png)
The link is present, but opens on the same page.

Do you mean you want the link to be a "target="_blank" to the link ?

**Comment by kmorgen** [comment]
Hello

Previous versions always had link on tracking number opening in new browser tab ("target="_blank"). Even PS 1.6 did :-)
However the tracking link will of course only appear, if a URL is pre set for each particular carrier. So maybe was not set in the store/ carrier you used.

Here is a screenshot from another PS 1.7.6.5 store too (this also have link and opens in new browser tab):
![Order-details-tracking-PS1765](https://user-images.githubusercontent.com/4300688/109314456-ac15fd00-7849-11eb-903c-2b6bb3404f96.jpg)

Here from a PS 1.6 store:
![Order-details-tracking-PS16124](https://user-images.githubusercontent.com/4300688/109317617-2f851d80-784d-11eb-9d67-733ce4663158.jpg)
So the "target="_blank" disappeared with the symphony update in PS 1.7.7.0+

Anyway, yes all it need is to get the **"target="_blank"** back again, so you will not leave BO.
(and and then also add the same url with "target="_blank" to the Order List page too)

Then it should be solved, thanks :-)

**Comment by florine2623** [comment]
I was able to reproduce the issue with PrestaShop version 1.7.7.2. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

---
> Hiba edit: 

PS: I didn't manage to reproduce it with PS1.7.6.8 / PS1.7.6.9

**Comment by Progi1984** [comment]
Fixed by #23819

**Comment by kmorgen** [comment]
Just updated a dev site to PS 1.7.7.4, and noticed the tracking url on the **Order List** page (dropdown) seems incorrect :-(

The url is supposed to contain the actual tracking number, like on the **Order details** page (where the @ from the carrier url settings represents the tracking number).


**Steps to reproduce the fix is not working as intended;**

Add a Carrier tracking number to an order.
(from a carrier with a pre-defined tracking URL containing the @ which represent the tracking number part).

Compare the Carrier tracking url in BO Order page vs, the Order List page.
(the url on the Order List does not contain the tracking number, but only the raw pre-set url from Carrier settings. It should be identical to the Order details page, which now works fine)
