### ISSUE TITLE
Bug in cache price

### ISSUE THREAD

**Issue by idiatech** [PrestaShop/PrestaShop#23414]
#### Describe the bug

The concern is I following. We make a price change
$product->price = 10;
$product->save();
At first, the change seems to have been taken into account.
But then we will have another $product->save(); which will happen after a new $ product = new Product($id_product); and hand over the old price!
We do not understand where this strange behavior is coming from. We tried everything on your code and we did a lot of reverse engineering but we still don't understand.

#### Expected behavior

$product=new Product(25); //the current price is 15€
$product->price = 10;
$product->save();

//Here the price of the product has become 10 €

$product=new Product(25);
$product->save();

//Here, in some cases the product remains at 10 € and sometimes, it goes back to 15 € !!!!

This commented code, shows you what problem we are doing.
It seems that there is a bug in the management of the price cache. We only see this problem in the latest versions of Prestashop (only on 1.7)

#### Steps to Reproduce

This bug append not with all products and not with all shops !! We have 5 customers where there is this problem.

#### Additional information

* PrestaShop version: tested on PS 1.6.1.9 and 1.7.5.2
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @idiatech ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
