### ISSUE TITLE
Multistore monitoring problem

### ISSUE THREAD

**Issue by costads** [PrestaShop/PrestaShop#23415]
#### Describe the bug

'List of products without combinations and without available quantities for sale'

is always 0 when a shop in multistore is selected. I have to switch to 'All shops' to see products in that table.

#### Expected behavior

I expected to see my out of stock products, like I could in 1.7.6 and previous years versions.

#### Steps to Reproduce

Select a Shop in multistore mode.

Go to Catalogue -> Monitoring  

**Screenshots**

#### Additional information

* PrestaShop 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @costads ,

In PS 1.7.7.1, multistore mode, PHP 7.3, I can't reproduce your issue. I still see all out-of-stock product for the store :

Multistore mode, no shop selected : 
![Capture d’écran 2021-02-26 à 09 46 06](https://user-images.githubusercontent.com/16019289/109277455-a56e9200-7817-11eb-92f2-55960c45b04e.png)

Multistore mode, when a specific store is selected :
![Capture d’écran 2021-02-26 à 09 45 49](https://user-images.githubusercontent.com/16019289/109277576-cfc04f80-7817-11eb-982e-1e748397d90f.png)


I'll close your issue, thanks!

**Comment by costads** [comment]
So, what you are saying is that there's a bug in the 1.7.6.1 upgrader to 1.7.7.1?
It was working fine before I upgraded, which I did without errors with the 1-click upgrade module.
