### ISSUE TITLE
Adding a CartRule to an order not added correctly

### ISSUE THREAD

**Issue by lozal2244** [PrestaShop/PrestaShop#23419]
Tested on Prestashop 1.7.7.0, 1.7.7.1 and 1.7.7.2

For example:  An order:
- products: 25€ 
- Shipping: 10€

I add a voucher of 30€

The total only includes the discount of 25€ instead of 30€. The discount is never applied to the shipping. In older versions it was working

**Comment by florine2623** [comment]
Hi @lozal2244 ,

Even in version PS 1.7.5.2, the discount is not applied to shipping :
![Capture d’écran 2021-02-26 à 09 09 52](https://user-images.githubusercontent.com/16019289/109273378-6ab62b00-7812-11eb-84bd-f1c6d14caffb.png)

You might need to use an specific module for that feature.
Thanks
