### ISSUE TITLE
Update from 1.7.6.9 to 1.7.7.2 - Can't save or duplicate products, messy categories

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#23420]
#### Describe the bug

Can't save or duplicate products, the category showing in the product page is messy, picture attached.
I have a 3rd party module that can save most important details of the products.

#### Steps to Reproduce

Upgrading from 1.7.6.9 to 1.7.7.2
Warning detected during upgrade - I have the log

**Screenshots**

![Screenshot_2021-02-25 Produs • GPG Mobile2](https://user-images.githubusercontent.com/5030991/109269621-6a6b5f00-7815-11eb-8c6a-bc31245f3bce.jpg)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @jajarom ,

After upgrading my shop from PS 1.7.6.9 to 1.7.7.2, I did not encounter the same issue as you did.

Upgrade went well :
![Capture d’écran 2021-02-26 à 12 11 36](https://user-images.githubusercontent.com/16019289/109293873-b249b080-782c-11eb-9d07-2c134d9c0779.png)

When refreshing the site and login back to my upgraded shop 1.7.7.2, my categories in my product sheet displays correctly :
![Capture d’écran 2021-02-26 à 12 16 37](https://user-images.githubusercontent.com/16019289/109293946-cb526180-782c-11eb-812b-d967a91114bf.png)

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks !

**Comment by jajarom** [comment]
Maybe from a celan 1.7.6.9.
Any other suggestions?
With an 3rd module i can modify the stock and the informations of any products.
