### ISSUE TITLE
Upgrade error form 1.7.6.9 to 1.7.7.2

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#23427]
#### Describe the bug
I did upgrade from 1.7.6.9 to 1.7.7.2 and I got warning and error messages:

 [WARNING] SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections' doesn't exist
[WARNING] SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_page` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections_page' doesn't exist
[WARNING] SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_source` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections_source' doesn't exist

SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_page` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections_page' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections_source` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_connections_source' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_guest` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'q10_testpp.ps_guest' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_statssearch` CHANGE `keywords` `keywords` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL: Table 'q10_testpp.ps_statssearch' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_connections` CHANGE `http_referer` `http_referer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL: Table 'q10_testpp.ps_connections' doesn't exist

#### Expected behavior
The upgrade should finish without warning and error messages

#### Additional information

* PrestaShop version: 1.7.6.9 > 1.7.7.2
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hello @juraj1000 ,
I can't reproduce your issue.
After upgrading my shop from 1.7.6.9 to 1.7.7.2, I haven't encounter any errors. Please check the screenshot :
![Capture d’écran 2021-02-26 à 12 11 36](https://user-images.githubusercontent.com/16019289/109293479-220b6b80-782c-11eb-963c-f367a4612636.png)

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
