### ISSUE TITLE
Product Out of stock email : Missing product name and firstname/lastname

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#23424]
#### Describe the bug
When checking the option "Send me an email when the quantity is below or equals this level" on a product, when a client order a product below the low level, the email alert we are getting (as admin) doesn't have the product name neither firstname.lastname (see screenshot).

#### Expected behavior

Have the product name..

#### Steps to Reproduce

1. Check the box "Send me an email when the quantity is below or equals this level" on a product
2. Save this product (having quantity below low level)
3. Order the product

**Screenshots**
![image](https://user-images.githubusercontent.com/1193727/109289090-fbe2cd00-7825-11eb-8eb4-79c2f184958c.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: php 7.2

**Comment by florine2623** [comment]
Hi @arirangz ,

PrestaShop 1.7.6.5 is not available with PHP 7.3. Please check this link for more info : 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by arirangz** [comment]
@florine2623 Sorry it was just a mistake. I double checked and we are with php 7.2.

Could you please re-open the ticket?

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @arirangz 

I didn't manage to reproduce the issue with PS1.7.6.5 and MailAlerts v2.2.1, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/109347582-aaf9c580-7873-11eb-904c-e38b9ca5b5d3.png)


Thanks!

**Comment by arirangz** [comment]
Hello @hibatallahAouadni 

Thanks for your reply.

Your email is referring to Mail Alert module but my issue is with the core email : 
mais/en/productoutofstock

You will see that it's not the same alert. Your alert comes from the mail alert module but my alert comes from the core system.

Please see bellow how the core email looks like. You will see there is no product name in it :
` Hi {firstname} {lastname},

There are now less than {last_qty} items in stock.

Remaining stock: {qty}
`
Thanks

**Comment by arirangz** [comment]
@hibatallahAouadni  I also check in the twig template in:
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/mails/themes/modern/core/productoutofstock.html.twig

As you can see, there is no product in the template.

But I can see this has been solved in 1.7.7 : https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/mails/themes/modern/core/productoutofstock.html.twig

**Comment by hibatallahAouadni** [comment]
@arirangz glad to hear :tada:
