### ISSUE TITLE
[BO] Can't access view customer page

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23426]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO customers page
2. Create new customer
3. Click on view customer

**Screenshots**

![image](https://user-images.githubusercontent.com/48441421/109290897-81677c80-7828-11eb-9875-ce72efb77b7a.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.4 (works on 7.3)

**Comment by PierreRambaud** [comment]
The problem has alreadyu been fixed in the 1.7.8.x :thinking:

**Comment by boubkerbribri** [comment]
Yeah fixed.
