### ISSUE TITLE
Can't go back when navigate from category product page.

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#23439]
Hi,
On a fresh installation of PrestaShop, with demo product installed : 
- Go to category Home (http://mydomain.com/2-home)
- Click on page 2
- Click on prev button from navigator.
- Nothing happend, can't get my product from page 1

If we go on page 2 or 3 or 4 and right after i want to go back with the prev button of chrome or firefox, the page won't reload the product.

Here a short video to reproduce the problem
https://drive.google.com/file/d/1CxFjvYUwH1CaUDZnsyurWMbMREoWzMKv/view
#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @azralth ,

I reproduced your issue on PS 1.7.7.2, 1.7.6.7 and 1.7.5.2.
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by florine2623** [comment]
Issue is fixed in 1.7.8.
https://drive.google.com/file/d/1a8f7uggSs-OTyEPZVwKxSRCIPh6uArDs/view
