### ISSUE TITLE
Call to a member function compile() on null

### ISSUE THREAD

**Issue by md2158** [PrestaShop/PrestaShop#23431]
#### Describe the bug

Upgraded from 1.7.3.4 to 1.7.7.2 and now can't access to advanced setting, showing this error:
Call to a member function compile() on null. What's wrong?

**Screenshots**

![image](https://user-images.githubusercontent.com/13145310/109299989-fc3f9000-7846-11eb-913e-5575186ffee0.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @merick2158 ,

PrestaShop version 1.7.3.6. does not exists, so I can't reproduce your issue.
So I close it.
Thanks

**Comment by md2158** [comment]
@florine2623 sorry, correct version is 1.7.3.4

**Comment by hibatallahAouadni** [comment]
Hello @merick2158 

Could you please check these issues #10655 & #10176.
It seems similar to yours, you may find some answers could help you to solve your issue :wink: 

Thanks!
