### ISSUE TITLE
prestashop 1.7 search block isnt work

### ISSUE THREAD

**Issue by sakurakary** [PrestaShop/PrestaShop#23438]
only find a few or none of the products active, the indexation has been done several times but still is not searching products (active and visible for search)

**Comment by florine2623** [comment]
Hello @sakurakary 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
