### ISSUE TITLE
[BO] Warning display after creating Store (or view it)

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23430]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO -> shop parameters -> contact -> Store
2. Click on New Store
3. Fill **all inputs** in form and click on save 
4. Edit the store, see errors

**Screenshots**

![image (3)](https://user-images.githubusercontent.com/1784781/117984968-97211400-b338-11eb-9ac3-104ac2917b07.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by #24479
