### ISSUE TITLE
[BO] Error when creating new currencies

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23434]
#### Describe the bug
Error on create some official currencies

#### Expected behavior

Currency created

#### Steps to Reproduce

1. Go to International currencies
2. Click on Add new currency 
3. Choose official currency like (ADB Unit of Account (XUA), Algerian Dinar (DZD), Moroccan Dirham (MAD)) works with some currencies

**Screenshots**

![image](https://user-images.githubusercontent.com/48441421/109305026-70753600-783d-11eb-9505-d3f603e511f7.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.4

**Comment by atomiix** [comment]
Fixed by #24274
