### ISSUE TITLE
[BO] Warning displayed on multistore add new shop page

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23432]
#### Describe the bug

A warning is displayed on Multistore -> add new shop page 

#### Expected behavior

No warning

#### Steps to Reproduce

1. Activate multistore on Shop parameters -> General
2. Go to Advanced parameters -> Multistore
3. Click on 'Add new shop'

**Screenshots**

![image](https://user-images.githubusercontent.com/48441421/109300733-3739c780-7837-11eb-97d6-9b4003d916c5.png)

#### Additional information

* PrestaShop version: develop Branch
* PHP version: 7.4

**Comment by PierreRambaud** [comment]
I did not manage to reproduce the issue. I think it has already been fixed :thinking:

**Comment by boubkerbribri** [comment]
It seems so, Nightly does not find the error anymore.
Closing the issue.
