### ISSUE TITLE
Attribute in Multistore -Admin wrong

### ISSUE THREAD

**Issue by novallis** [PrestaShop/PrestaShop#23445]
Attributes in Multistore are not assigned to specific shop. Bug known at least from April 2020. See: 

https://www.prestashop.com/forums/topic/1021118-multistore-different-attributes-for-shops-issue/

Prestashop 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @novallis 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
