### ISSUE TITLE
MultiStore With Multi Currency Exchange Rate Manual Update

### ISSUE THREAD

**Issue by ricardoceci** [PrestaShop/PrestaShop#23447]
#### Describe the bug

When you have multistore enabled, and different stores with different Default Currency, once you update the exchange manually in any store, it overrides the other stores exchange rate.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Let's say we have 3 Stores:
All Shops in Localization says that the default currency is Argentine Peso
Store A => Default Currency: Argentine Peso 
Store B => Default Currency USD
Store C => Default Currency EUR

Initial All Shops exchange rate for example: Peso => 1, USD => 0.01 => EUR => 0.009 ( This is the same as saying: 100 Pesos = 1 USD 110 pesos = 1 EUR)

1. Go to All Shops => Update USD => 0.02
2. Go to Store B => ( the default currency is USD for this store) it has to show 1 and you can see that it shows 0.02
3. Go to Store C => (The default currency is EUR for this store ) it has to show 2 and you can see that it shows 0.02

Same happens if you make an update in Any store if you change any conversion values it gets replicated without being recalculated on the remaining stores.

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by matks** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/12025

**Comment by hibatallahAouadni** [comment]
Hello @ricardoceci 

Could you please check this issue #17663 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ricardoceci ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
