### ISSUE TITLE
Admin Order Edit - Changing Carrier - Not showing all carriers

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23459]
Hi!
#### Describe the bug
So I upgraded from 1.7.6.9 to 1.7.7.1 and I just noticed that when I try to change an order that was made on the previous version, only 2 carriers are shown at the admin order page -> carriers -> edit.

All the new ones show all the carriers it's supposed to show.

#### Steps to Reproduce

1. Make an order with 1.7.6.9.
2. Upgrade to 1.7.7.1
3. Try to change the carrier of that order on the new upgraded version.
4. You won't see all carriers.
5. In my case I can only see two carriers that are FREE shipping. But the new ones show all carriers.

#### Additional information

- Server information Linux Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64
- Server software version: Apache
- PHP version: 7.2.24-0ubuntu0.18.04.7
- Memory limit: 1024M
- Max execution time: 600
- Upload Max File size: 128M

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

I didn't manage to reproduce your issue. I upgraded my shop 1.7.6.9 to 1.7.7.1 after creating another carrier and new order. After the upgrade, I edit my Order and I change the carrier (all available carriers are well displayed), see the attached screen record below:

https://drive.google.com/file/d/1UAFAEdv4znjTmbybYRQrnpHZXotlbNGg/view

Please check and feedback.

Thanks!

**Comment by seederp2p** [comment]
Hi!

I can see that.

However the two common things here is:
1 - Date : everything before the upgrade don't show all the carriers
2 - The carriers :  the ones I can see on those orders are only the "free shipping" ones. If I change them to paid it won't appear anymore.

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Thanks for your quick feedback.
> The carriers : the ones I can see on those orders are only the "free shipping" ones

In my case, I can see all carriers, whether free or paid. It seems you issue related to some third module or an override.
Please check and feedback.

Thanks!

**Comment by seederp2p** [comment]
Hi!
Well I just disabled all overrides and non native modules, and I get the same behaviour.

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Unfortunally the PS options **Disabled non PrestaShop modules** and **Disabled all overrides** is not working :sweat: 
You can check these issues #14596 & #9965

So, you need to disabled (comment) all your override manually and to disabled all you non PS modules one by one (**BO**>**IMPROVE**>**Modules**>**Module Manager**).
Please check and feedback.

Thanks!

**Comment by seederp2p** [comment]
Ok. 

What would be the best way to disable the overrides?

**Comment by seederp2p** [comment]
Ok.

I just disabled all non native modules and deleted overrides.

Same thing.

Can you enlighten me, what kind of query does prestashop to show the carriers? I find it very odd that only free carriers show up.

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Could you please provide a screen record showing your carriers and the Order.

Thanks!

**Comment by seederp2p** [comment]
Sure.

Carrier list:
https://recordit.co/wOEdJCIT3R

Order edit showing only 3 free shipping carriers:
https://recordit.co/Dzbq8YLRdU

**Comment by seederp2p** [comment]
FYI yesterday I upgraded to 1.7.7.2 but this issue is still present.

All the orders older than 27 of february only show free carriers.

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a related to your store.

We will close this issue.

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
