### ISSUE TITLE
Clear Cache issue after upgrade 1.7.7.1 to 1.7.7.2

### ISSUE THREAD

**Issue by mmursalov** [PrestaShop/PrestaShop#23454]
Hi,

Performed upgrade using 1-Click Upgrade tool and it was successful. However, every time I clear the server cache via Admin, all Product images in the Front page gets corrupted. I can get them back if I regenerate, but the issue reappears if I clear the cache again.

Did not have this issue in the earlier release.

Any thoughts?

Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @mmursalov 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
