### ISSUE TITLE
Logger Issue

### ISSUE THREAD

**Issue by MassimoGS3** [PrestaShop/PrestaShop#23457]
#### Describe the bug

Prestashop Log page stop to work ex

#### Expected behavior

The log page stopped working unexpectedly

#### Steps to Reproduce

I can't reproduce the step for this bug

**Screenshots**

![image](https://user-images.githubusercontent.com/76114491/109503744-ef1adf00-7a9a-11eb-8425-9064a9d017dc.png)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello,

I didn't manage to reproduce your issue. And it seems you need help with your shop, so please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
