### ISSUE TITLE
AdminAccesses select-boxes greyed out if not found in database

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#23460]
#### Describe the bug
For some modules checkboxes in `AdminAccessController` are `disabled` and therefore not possible to select:

![Screenshot 2021-03-01 at 14 54 24](https://user-images.githubusercontent.com/30602638/109507338-ec21ed80-7a9e-11eb-959d-9f449f98c10d.png)

This can be any modules, also native ones like `ps_faceted_search`.

#### Expected behavior
All checkboxes should be selectable.

#### Steps to Reproduce
Remove table rows from `ps_module_access` that belongs to a module. 
Observe checkboxes becoming disabled.

I managed to fix the issue with one of the modules by inserting the missing rows in the table like this:

#### Steps to fix temporarily

```
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('1', '1674');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('2', '1674');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('1', '1675');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('2', '1675');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('1', '1676');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('2', '1676');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('1', '1677');
INSERT INTO `ps_module_access` (`id_profile`, `id_authorization_role`) VALUES ('2', '1677');

```

#### Reason behind the missing table rows
Unknown, but has occurred  in many shops I host.

#### Proposal

Couldn't missing rows in `ps_module_access` *autoheal* if for some reason it's missing?
By *autoheal*, I mean, create the missing rows in `ps_module_access`

#### Related issue 
The following issue is the same but in *reverse*, where rows in the same table, but where the module is deleted causes blank rows and _undefined index module name and id_module_:
https://github.com/PrestaShop/PrestaShop/issues/23461

#### Additional information
PS 1.7.7.1
PHP 7.2

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Could you reproduce the issue with any native modules?
Please check and feedback.

And please next time **respect and follow the provided template to submit a complete bug report**.

Thanks!

**Comment by hibatallahAouadni** [comment]
Related to #23461

**Comment by madsoliver** [comment]
Hi,
Yes, I had this problem with ps_faceted_search.

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Thanks for your feedback.
So, could you please edit your issue description following the template :wink: 

Thanks!

**Comment by madsoliver** [comment]
Hi @hibatallahAouadni 🙂

Edited.

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Thanks for editing your issue :clap: 

> For some modules checkboxes in AdminAccessController are disabled and therefore not possible to select:
This can be any modules, also native ones like `ps_faceted_search`.

Well, if you don't manipulate your DB, you will have all your checkbox enabled:

![image](https://user-images.githubusercontent.com/23308427/109789330-86ee0980-7c10-11eb-89e7-f7b358f8824a.png)

> Remove table rows from ps_module_access that belongs to a module.

Why you need to remove these rows??
Please check and feedback.

Thanks!

**Comment by madsoliver** [comment]
Hi @hibatallahAouadni  🙂

> Well, if you don't manipulate your DB, you will have all your checkbox enabled

I didn't. But I don't know the underlying reason that those rows was deleted/never inserted. 
Deleting them manually was just a way to reproduce the problem. 
Considering #23420, it's clear that the listing of checkboxes gets it's input from ´ps_module_access´ without validating it.

**This issue:** If (for some reason or another) the module in question does not have the rows, well then create them.
#23420 : If (for some reason or another) there are rows from  ´ps_module_access´ that belongs to non-existing modules, well, then ignore them.

That's my suggestion anyways :-)

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

> I didn't. But I don't know the underlying reason that those rows was deleted/never inserted.
Deleting them manually was just a way to reproduce the problem.

I see :thinking: it's a quite confusing that there's those rows was deleted/never inserted in `ps_module_access`  for some module.
Well, thanks for your solution nad I hope it helps people who face this problem.
Till then, I think we can close the issue cause we do not know the real reason that trigger the issue :wink: 

PS: if you would like I may ping the Developer Team, if you encounter the issue with a native module (cause as I mentioned above, I didn't encounter the issue with `ps_faceted_search`).

Many thanks :rocket:

**Comment by madsoliver** [comment]
Ok, I will try to figure out what the root cause is and reply here if found. I  hope it is possible to reopen this ticket if root cause is found / issue is reproducable?

**Comment by hibatallahAouadni** [comment]
@onklmaps ofc we will reopen this ticket if root cause is found and the issue is reproducable :wink:
