### ISSUE TITLE
Migrate tests-legacy directory to tests directory

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#23462]
- [x] Migrate create-test-db command
  - #25843
- [x] Migrate `phpunit-legacy` (Tests: 948, Assertions: 3219) => :wave:
  - #24095
  - #24121
  - #24188
  - #25127
  - #25238
- [x] Migrate `phpunit-admin` (Tests: 155, Assertions: 275) => :wave:
  - #25238
- [x] Migrate `phpunit-sf` (Tests: 25, Assertions: 104) => :wave: 
  - #25127
- [x] :x: Migrate `phpunit-endpoints` (Tests: 16, Assertions: 31)
- [x] Migrate `phpunit-controllers` (Tests: 28, Assertions: 28) => :wave: 
    - #25196
- [x] Clean modules ressources
- [x] Remove tests with gamification
    - #25721
- [x] Update docs
    - PrestaShop/docs#1244
- [x] Move LegacyContext in Integrations Tests directory
    - #26533

**Comment by matks** [comment]
Hi @Progi1984 what does it mean "Migrate tests-legacy directory to tests directory" ?

You can find in https://github.com/PrestaShop/PrestaShop/blob/develop/tests-legacy/README.md the reason why we have `tests-legacy` and `tests`. We wanted to keep them split. Do you want to merge them? 😄
