### ISSUE TITLE
Modules showing up as blank rows in AdminAccessController for deleted modules

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#23461]
I don't know what has caused it, if the modules were deleted without being uninstalled, or what happened, but in many PrestaShop installations I have seen the following: blank lines in `AdminAccessController`, and if you turn on debug, you get undefined indexes: `id_module` and `name`. 

![Screenshot 2021-03-01 at 14 54 15](https://user-images.githubusercontent.com/30602638/109507777-5d61a080-7a9f-11eb-81df-bbe4733f8415.png)

This is probably because `Module::getModulesAccessesByIdProfile($profile['id_profile'])` returns ModuleAccesses for modules that not longer exsists.

I managed to get rid of them by doing this (dirty) filter in `AdminAccessController::renderForm()`, just before smarty-variables are assigned:

```
        foreach ($modules as $i_profile => $modules_in_profiles) {
            foreach ($modules_in_profiles as $i_module => $module) {
                if(!isset($module['id_module'])) {
                    unset($modules[$i_profile][$i_module]);
                }
            }
        }

```

... But I guess it would be better if a search for no longer relevant rows in `ps_module_access` could be deleted by the `ps_cleaner` module? 

PS 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **YOU MUST FOLLOW THE TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
