### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by MAramex** [PrestaShop/PrestaShop#23474]
#### Describe the bug
I'm currently facing "Invalid Security Token" issue, this problem arise whenever I try to use a shipping module functionalities, 
this module functionalities are located in the order page and when I try to use them this issue occur.

#### Expected behavior
The expected behavior is to be able to use this module to create shipments for the orders without getting the "Ivalid Security Token" issue. I tried couple of solutions from my side such as: changing PHP version/ Changing the way this module store the token/ Clearing cache and more, with no success.

#### Steps to Reproduce
1. login to Admin backoffice.
2. Go to orders.
3. Select an order.
4. Click Prepare Shipment (one of the module functionalities).
5. Click Create Shipment button.
6. See the "Invalid Security Token" error.

**Screenshots**

![InvalidToken](https://user-images.githubusercontent.com/79833135/109633579-eb499400-7b50-11eb-85ee-929009f738f9.png)

#### Additional information
* Prestashop version: 1.7.7.0 & 1.7.7.1
* PHP version: 7.3.25

**Comment by hibatallahAouadni** [comment]
Hello @MAramex 

Could you please edit your issue description **following the provided template to submit a complete bug report**. Follow these steps to find the template:

1. Click on **New issue** button

![image](https://user-images.githubusercontent.com/23308427/109639615-af61ff00-7b4f-11eb-9568-1f2c3780b6e1.png)

2. Click on the **Get Started** of **Bug Report**

![image](https://user-images.githubusercontent.com/23308427/109639643-b5f07680-7b4f-11eb-857e-f5559e0a5953.png)

3. Fill all the blocks mentioned in the template and please make the **steps to reproduce** clear :wink: 

![image](https://user-images.githubusercontent.com/23308427/109639661-bbe65780-7b4f-11eb-9c73-6ffc765de00f.png)

Then notify me :wink: 
Thanks!

**Comment by MAramex** [comment]
Hello,

Can you please check now.

Thank you

**Comment by MAramex** [comment]
Hello,
All done can you check it now please.
Thank you.

**Comment by PierreRambaud** [comment]
The problem probably come from your `Click Prepare Shipment (one of the module functionalities).` the module generate URL without considering the token in the URL (I think)

**Comment by hibatallahAouadni** [comment]
Hello @MAramex 

@PierreRambaud thanks for your quick reply :rocket: 

Your issue is related to your module and not to PS Core.
Please check your module and feedback.

Thanks!

**Comment by MAramex** [comment]
Thanks @PierreRambaud and @hibatallahAouadni for you support,
I tried to compare the tokens before and after clicking the button and they appear to be the same,
just to make sure is this issue only related to the token? or could it be triggered from something else?
thank you

**Comment by hibatallahAouadni** [comment]
Hello @MAramex 

Well, I have no idea. Maybe @PierreRambaud could give you hint to solve the issue.
But your issue is not related to PS Core, so I close the issue :wink: 

PS: even when the issue is closed, we will answer your question if we could help you :slightly_smiling_face: 

Thanks!
