### ISSUE TITLE
500 Internal Server Error - when trying to fetch currencies from API

### ISSUE THREAD

**Issue by Morph21** [PrestaShop/PrestaShop#23472]
#### Describe the bug

I called an API endpoint "api/currencies?output_format=JSON&display=full"

Which resulted in HttpStatus code: 500. Response body message looks like that:

```
{
    "currencies": [
        {
            "id": 1,
            "name": "złoty polski",
            "iso_code": "PLN",
            "conversion_rate": "1.000000",
            "deleted": "0",
            "active": "1"
        },
        {
            "id": 2,
            "name": "funt szterling",
            "iso_code": "GBP",
            "conversion_rate": "0.208882",
            "deleted": "1",
            "active": "0"
        },
        {
            "id": 3,
            "name": "dolar amerykański",
            "iso_code": "USD",
            "conversion_rate": "0.265789",
            "deleted": "1",
            "active": "0"
        }
    ],
    "errors": [
        {
            "code": 3,
            "message": "[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable ([hidden for security]/public_html/classes/webservice/WebserviceOutputJSON.php, line 153)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable ([hidden for security]/public_html/classes/webservice/WebserviceOutputJSON.php, line 153)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable ([hidden for security]/public_html/classes/webservice/WebserviceOutputJSON.php, line 153)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable ([hidden for security]/public_html/classes/webservice/WebserviceOutputJSON.php, line 153)"
        }
    ]
}
```

Full url was hidden by me for security reasons.

#### Expected behavior

I expect that this endpoint will work. (If you drop the output_format parameter then the response body don't have any errors and status code is 200.

#### Steps to Reproduce

Call an API "api/currencies?output_format=JSON&display=full"

I don't know what causes this error but it's not replicable for me on clean installation.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Morph21 

Could you please check these issues #18865 & #16760 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Morph21** [comment]
Hello @hibatallahAouadni 

I don't see how these issues are similar to mine.
I'm getting errors with different status code, caused in different files (WebserviceOutputJSON.php vs PSWebServiceLibrary.php)

And I'm getting the result which I want which is in currencies in response body. But also I'm getting status code 500 which I'm not getting while parameter output_format=JSON is not there.

**Comment by Morph21** [comment]
I looked into that code and it's possible that this bug was fixed in this commit: https://github.com/PrestaShop/PrestaShop/commit/6c9decc5c9c0b8f43ad10b057ebd088646001447

I will close this issue if it will happen to be true (once a client of mine will upgrade his version)

**Comment by hibatallahAouadni** [comment]
Hello @Morph21 

I didn't reproduce it with PS1.7.6.7 and PS1.7.7.2, see the attached screenshots below:

###  1.7.6.7
![image](https://user-images.githubusercontent.com/23308427/109642212-f4d3fb80-7b52-11eb-8d73-69931d66ebb3.png)

### 1.7.7.2
![image](https://user-images.githubusercontent.com/23308427/109642245-ff8e9080-7b52-11eb-8edc-e28ce852d00f.png)

I only reproduce it with PS1.7.5.2, it means that the issue has been fixed:

### 1.7.5.2
![image](https://user-images.githubusercontent.com/23308427/109642311-17661480-7b53-11eb-9227-d2e8f8f5f59e.png)

So, I close the issue cause it has been fixed, please upgrade your shop.
Thanks!

**Comment by hibatallahAouadni** [comment]
Edit: I think it has been fixed while migration, see the attached screenshot below:

### 1.7.6.1
![image](https://user-images.githubusercontent.com/23308427/109642712-9eb38800-7b53-11eb-8b18-883044f9c5d4.png)

Thanks!

**Comment by Morph21** [comment]
Thank you for your help. Keep up the good work :)
