### ISSUE TITLE
Admin Order Edit - Changing Carrier - Not showing all carriers if you remove associated Cart

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23481]
Hi!

### Steps to Reproduce

1. Delete a cart that is associated with a order
2. Try to change the carrier of that order.
3. You won't see all carriers.
4. You'll get carriers that are FREE shipping. 

There are LOTS of paid modules that remove old carts. So I think the behaviour of this feature should be to allow the admin to change the carrier for whatever carrier he wants and NOT validate anything related to the ps_cart table.

### Additional information

- Server information Linux Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64
- Server software version: Apache
- PHP version: 7.2.24-0ubuntu0.18.04.7
- Memory limit: 1024M
- Max execution time: 600
- Upload Max File size: 128M

---
Related to #23459

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Could you please provide your PS version? was it 1.7.6.7 or 1.7.7.1?

Thanks!

**Comment by seederp2p** [comment]
Sorry 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

> Delete a cart that is associated with a order

How did you delete a cart whose already validated by an Order?? You can't do that: 

![image](https://user-images.githubusercontent.com/23308427/109970809-c9d5dd00-7cf5-11eb-9030-6ab7891364b6.png)

Please check and feedback.
Thanks!

**Comment by seederp2p** [comment]
There are paid modules (at addons.prestashop.com) that allow that.

Also, it's not documented that you can't get rid of carts associated with orders.

So yes, if you assume that you can't delete at the backoffice and that's it, then there's not a problem.

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

> There are paid modules (at addons.prestashop.com) that allow that.

You need to contact the module Developer.
So, I close the issue cause it's not related to PS Core :wink: 

Thanks!
