### ISSUE TITLE
Customer registration error

### ISSUE THREAD

**Issue by md2158** [PrestaShop/PrestaShop#23484]
#### Describe the bug

Customer registration has a bug. If a new customer registered, the page goes to an infinite loop. The console network shows the post request as pending, while customer data already saved in the database.  But if a customer already exists it responds immediately. I had tested this in the default PrestaShop theme.

#### Steps to reproduce

1. Go to create a new customer/user page.
2. Fill the form and submit it.
3. Page will infinite load and in the console network will show post request pending. But the data already saved in database

**Screenshots**

![image](https://user-images.githubusercontent.com/13145310/109721227-23d28780-7bbc-11eb-945b-b056b839de89.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @merick2158 

Could you please provide clear and concise steps to reproduce your issue.

Thanks!

**Comment by md2158** [comment]
Steps to reproduce:

1. Go to create a new customer/user page.
2. Fill the form and submit it.
3. Page will infinite load and in the console network will show post request pending. But the data already saved in database

**Comment by hibatallahAouadni** [comment]
Hello @merick2158 

I didn't reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1pN16Ja-lenuPIykICk60ptpcO6x46avf/view

It seems your issue is related to some third-party modules.
Please check and feedback.

Thanks!

**Comment by md2158** [comment]
Hi @hibatallahAouadni.
Thanks for your support. It was because of an error in my email server. Solved, thanks!
