### ISSUE TITLE
Wrong cover image for product in block wishlist

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#23486]
#### Describe the bug

Block wishlist has wrong cover images for products added to wish list

#### Expected behavior

We should see cover respecting selected combination

#### Steps to Reproduce

1. Install blockwishlist v2.0.0 (dev branch)
2. composer install
3. yarn
4. Add T-shirt white to wishlist
5. Add T-shirt black to wishlist
6. See that cover images are wrong

> Edit: hiba
to install the module WishList

1. clone blockwishlist directly into `/modules/`
2. make sure that you’re on `dev` branch
3. `composer install`
4. `npm install`
5. `npm run build`
6. head to Modules catalog and search for the “wishlist”, install it from there

**Screenshots**

https://www.dropbox.com/s/ou7lc0iuwa07b3g/Zrzut%20ekranu%202021-03-3%20o%2009.16.45.png?dl=0

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by matks** [comment]
Isn't it the same topic that https://github.com/PrestaShop/PrestaShop/issues/21389 ? 😄  but for the module ?

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thanks for your issue and your PR :rocket: 
I manage to reproduce the issue with 1.7.7.2 and wishlist v2.0.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/109785050-0200f100-7c0c-11eb-90bb-e24dc0ff9a69.png)

Thanks!

**Comment by Sykoku** [comment]
Wrong again now. Tested on demo.prestashop.com

**Comment by hibatallahAouadni** [comment]
Hello @Sykoku 

It seems good with PS1780 and Wishlist v2.0.1, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/131470078-cbd48d6e-99b6-43eb-8437-715bb1f9717e.png)

![image](https://user-images.githubusercontent.com/23308427/131470060-ec4dd316-1cb3-45dc-9242-a44851796216.png)

Thanks!

**Comment by Sykoku** [comment]
It is a two different goods. I'm talking about one product with two colors.
PrestaShop 1.7.8.0 is a beta only. Thank's. Not on my watch.
When you select a product by category (color or size), the basic combination is displayed.
[<img src="https://i.ibb.co/vHZsRHD/Presta-Bags-01.jpg">](https://ibb.co/g3zvh36)
[<img src="https://i.ibb.co/413Dnw5/Presta-Bags-02.jpg">](https://ibb.co/cYVpSK7)
