### ISSUE TITLE
 Création de produits vide

### ISSUE THREAD

**Issue by shortymc** [PrestaShop/PrestaShop#23485]
Franchement ce bug est insupportable.
J'espère que vous allez vite le régler car il décridibilise prestashop
 Des produis vides apparaissent sur la page d'accueil et il est impossible de les enlever.
Et ce bug persiste versions après versions.

https://www.prestashop.com/forums/topic/997748-bug-cr%C3%A9ation-produits-vides/

**Comment by matks** [comment]
Bonjour, si ce bug vous est insupportable, alors vous ne verrez pas de problème à payer un professionnel pour le corriger et soumettre un correctif à ce projet opensource ? Je pense que c'est la manière la plus efficace de le corriger.

Par ailleurs je suis désolé mais sur ce repository GitHub, nous devons utiliser l'anglais afin que les utilisateurs de PrestaShop du monde entier puissent participer. Je ferme cette issue, n'hésitez pas à en réouvrir une en anglais en suivant le modèle pour les bugs : https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md

**Comment by matks** [comment]
@shortymc Je suis désolé mais sur ce repository GitHub, nous devons utiliser l'anglais afin que les utilisateurs de PrestaShop du monde entier puissent participer. Je ferme cette issue, n'hésitez pas à en réouvrir une en anglais en suivant le modèle pour les bugs : https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md
