### ISSUE TITLE
 Decimals of prices are always zero

### ISSUE THREAD

**Issue by etsmes** [PrestaShop/PrestaShop#23482]
#### Describe the bug

The decimals of the prices are shown wrong, it only shows two zeros, but in the database it is fine.

For example, in the database I have a shipping cost of 2,47 €, if we add 21% VAT it results in 2,99 €. But on the web, in the shopping cart, shows 2,00 €

The same thing happens in the 3 languages ​​that I have configured.
It happens with the prices of the products. With the prices of the carriers...
In BO and FO. Always.

In the editable fields the price is shown well, with all the decimals.

#### Expected behavior

It should show the actual decimals, not two zeros.

I have a test server with apparently the same configuration, but the test server works fine and the production one does not.

#### Steps to Reproduce

I updated to the latest version of Prestashop 1.7.7.2. and since then the prices are not shown well. 
I have two servers, one for testing and one for production. The test server does not have this problem.

I have temporarily fixed it by forcing the formatPrice function of locale.php
return number_format($number, 2, ',', '.').' €';

_Image with the prices shown wrong, with zeros in the decimals_

<img width="206" alt="Captura" src="https://user-images.githubusercontent.com/19926260/109685489-983c0500-7b81-11eb-86d8-83c500303800.PNG">

_Image with the prices that should be shown, the correct ones_

<img width="232" alt="Captura6" src="https://user-images.githubusercontent.com/19926260/109786200-36c17800-7c0d-11eb-8c28-428763350fe6.PNG">

_Back Office configuration_

<img width="530" alt="Captura2" src="https://user-images.githubusercontent.com/19926260/109687870-f79b1480-7b83-11eb-9581-548dfa2ff07e.PNG">

<img width="547" alt="Captura7" src="https://user-images.githubusercontent.com/19926260/109787511-98361680-7c0e-11eb-8943-2253cfdafaa3.PNG">

_In the editable fields the price is shown well, with all the decimals._

<img width="593" alt="Captura3" src="https://user-images.githubusercontent.com/19926260/109688208-52347080-7b84-11eb-867a-8f693333e500.PNG">

<img width="590" alt="Captura4" src="https://user-images.githubusercontent.com/19926260/109688209-52cd0700-7b84-11eb-82b7-023b6362c865.PNG">

#### Additional information

Prestashop 1.7.7.2
PHP 7.2

**Comment by etsmes** [comment]
I have temporarily fixed it by forcing the formatPrice function of locale.php

return number_format($number, 2, ',', '.').' €';

**Comment by hibatallahAouadni** [comment]
Hello @etsmes 

Please edit your issue description **following the provided template to submit a complete bug report**.

Thanks!

**Comment by etsmes** [comment]
thanks for answering. I have edited the ticket following the template

**Comment by etsmes** [comment]
thanks for answering @hibatallahAouadni . I have edited the ticket following the template

**Comment by hibatallahAouadni** [comment]
Hello @etsmes 

Thanks for your feedback.
I didn't manage to reproduce your issue with PS1.7.7.2 and it seems your issue is similar to this one #22653
Could you please check your **Round mode** and **Round type**:

![image](https://user-images.githubusercontent.com/23308427/109972575-c4799200-7cf7-11eb-81c1-f373aed816ff.png)

And check your **Decimals**:

![image](https://user-images.githubusercontent.com/23308427/109972710-ea069b80-7cf7-11eb-9ad5-2bbacf48e50c.png)

Please check and feedback.
Thanks!

**Comment by etsmes** [comment]
Sorry, it is not working

<img width="167" alt="Captura" src="https://user-images.githubusercontent.com/19926260/109973641-f6d7bf00-7cf8-11eb-91b0-9480adb21792.PNG">

**Comment by hibatallahAouadni** [comment]
Hello @etsmes 

Could you please make a screenshots (like the ones that I attached above).

Thanks!

**Comment by etsmes** [comment]
<img width="490" alt="Captura" src="https://user-images.githubusercontent.com/19926260/109974578-01468880-7cfa-11eb-8d89-74014a4a237b.PNG">

<img width="517" alt="Captura2" src="https://user-images.githubusercontent.com/19926260/109974582-01df1f00-7cfa-11eb-95b7-377da6c06b05.PNG">

**Comment by etsmes** [comment]
if it can help, and as I said in the first message:

I can temporarily fix it by forcing the formatPrice function of locale.php
return number_format($number, 2, ',', '.').' €';

**Comment by florine2623** [comment]
Hello @etsmes ,
I can't reproduce your issue on 1.7.7.2 as you can see in the screenshots below :
![Capture d’écran 2021-03-05 à 15 25 31](https://user-images.githubusercontent.com/16019289/110128512-2654fd00-7dc7-11eb-9bb8-c9a9585ace49.png)
![Capture d’écran 2021-03-05 à 15 25 46](https://user-images.githubusercontent.com/16019289/110128522-294fed80-7dc7-11eb-8bf0-30bb7f3b8087.png)

In my test shop 1.7.7.2, it behaves correctly.
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
