### ISSUE TITLE
Undefined index: reduction_with_tax

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#23493]
Hello.

Error:

> PHP message: PHP Notice:  Undefined index: reduction_with_tax in /classes/product/SpecificPriceFormatter.php on line 147

![image](https://user-images.githubusercontent.com/6318282/109797261-f55cb700-7c64-11eb-8c5b-92f2ae86a21b.png)

reduction_with_tax set in line 131 in the condition

`if ($this->specificPrice['reduction_type'] == 'amount') {`

need set reduction_with_tax after

`            } else {
                $this->specificPrice['real_value'] = $this->specificPrice['reduction'] * 100;`

**Comment by hibatallahAouadni** [comment]
Hello @TemKaSD 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
