### ISSUE TITLE
Added slide expiration date

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23495]
https://github.com/PrestaShop/ps_imageslider/pull/59

**PierreRambaud commented 1 hour ago**
Hey I think it's a good idea, but could you please create an issue on https://github.com/PrestaShop/PrestaShop/issues/new/choose
IN order to be sure the behavior is ok :)

**Comment by alfonsolr09** [comment]
@PierreRambaud

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Ok I see that @PierreRambaud ask you to create a new issue.
But I need to reproduce it. So, please edit your issue description **following the provided template to submit a complete bug report**.

Thanks!

**Comment by alfonsolr09** [comment]
you have to change the files of the PR and check

**Comment by PierreRambaud** [comment]
The aim of an issue is to explain what you're trying to do and why you need this change or this feature.
Please explain us :)

**Comment by alfonsolr09** [comment]
> A veces nos olvidamos de las diapositivas caducadas en nuestra tienda. Esto ayudará a evitar viejos anuncios deslizantes no deseados.
> 
> Sometimes we forget about expired slides in our store. This will help to avoid old unwanted sliding ads.
> 
> ![vencimiento](https://user-images.githubusercontent.com/8243273/54746424-6f0c4f00-4bcc-11e9-9397-91ff704063b3.png)

**Comment by kpodemski** [comment]
My proposition would be to add:

`date_from` `date_to` to slider module, this would allow you to display banners for a specific time period.

What do you think?

**Comment by alfonsolr09** [comment]
You know how to do it?

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12991. 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #12991

**Comment by alfonsolr09** [comment]
thats true... but nothing was done

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 just link your PR to the issue #12991

**Comment by alfonsolr09** [comment]
I already did, check it

**Comment by hibatallahAouadni** [comment]
done :wink: thanks!
