### ISSUE TITLE
Provide an add-to-cart button for product lists

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23496]
#### Is your feature request related to a problem?

Several clients want to have an add to cart button with a quantity input on product lists, so clients can add it to cart without opening the product page.

Adding the button and even the quentity input itself is easy, but a problem arises when you have backorder disabled. Then we face a simmilar problem as in https://github.com/PrestaShop/PrestaShop/issues/23187.

#### Describe the solution you'd like

I think basic feature like adding products to cart should be implemented in-house for classic theme - profesionally. Users can always disable it or remove it from the template.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

> Several clients want to have an add to cart button with a quantity input on product lists, so clients can add it to cart without opening the product page.

But we already have this option: 

![image](https://user-images.githubusercontent.com/23308427/109815416-e7407380-7c2f-11eb-895c-c85cbce233eb.png)

I may misunderstand you but could you please explain to me.
Thanks!

**Comment by alfonsolr09** [comment]
i think @Hlavtox mean this 
![image](https://user-images.githubusercontent.com/62474824/109818476-5075b600-7c33-11eb-9bcb-7e8e1cdcf7dd.png)

**Comment by Hlavtox** [comment]
@hibatallahAouadni @alfonsolr09 Exactly ;-)

![add to cart](https://user-images.githubusercontent.com/6097524/109819078-f6c1bb80-7c33-11eb-8e3c-8ff483b3e68e.JPG)

**Comment by alfonsolr09** [comment]
but if a product have cominations.... what?

**Comment by alfonsolr09** [comment]
the idea is so good

**Comment by Hlavtox** [comment]
Then change it to "Select variant", like it was in 1.6 :-)

![addtocart](https://user-images.githubusercontent.com/6097524/109820119-ff66c180-7c34-11eb-933c-e8d11f082b88.png)

**Comment by alfonsolr09** [comment]
its a very good idea

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox & @alfonsolr09 

But when we hover the product, it won't display the **add to cart** button, it will only display the product combinations and a link **Suick view**:

![image](https://user-images.githubusercontent.com/23308427/109821377-338eb200-7c36-11eb-9a29-7370ecde984c.png)

@Hlavtox the photo that you use is from 1.6 :sweat_smile: 

![add to cart](https://user-images.githubusercontent.com/6097524/109819078-f6c1bb80-7c33-11eb-8e3c-8ff483b3e68e.JPG)

is that so?

**Comment by Hlavtox** [comment]
@hibatallahAouadni Yes the photo was from 1.6. You can take it as an inspiration... 😛

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

ok :sweat_smile: thanks for your suggestion. 
The Product Team will take a look. Please stay tuned !

Ping @PrestaShop/product-team , @Hlavtox propose if we could add the **Add to cart** button and the **quantity** input to the displayed products in the Product list, wdyt?

### 1st proposal:

![image](https://user-images.githubusercontent.com/23308427/110125778-fd7f3880-7dc3-11eb-90d1-7b782185a949.png)

### 2nd proposal:

![image](https://user-images.githubusercontent.com/23308427/110126586-dbd28100-7dc4-11eb-875d-04f785b04244.png)

**Comment by Hlavtox** [comment]
@hibatallahAouadni There is even a related PS setting that wasn't removed. People who started 1.7 back then really wanted to kill Prestashop with it. 🙄

![addtocart](https://user-images.githubusercontent.com/6097524/111595321-4d9ac980-87cc-11eb-9d64-2483a8f6cf2d.JPG)

**Comment by NeOMakinG** [comment]
@prestascott I think we need you a bit there :)

**Comment by prestascott** [comment]
Hello @Hlavtox, 

Thank you for your suggestion, it's a nice idea!

No, I don't think that people who started 1.7 back then wanted to kill Prestashop with this option. It simply because merchants that sell products with a lot of combinations might not want to provide "Add to basket" button and prefer to provide the product details on "Quick View". 

Just imagine customers struggling with choosing more than 2 combinations before adding the product in their baskets, it's too complicated. Plus it's on hover, there's a lot of chance that customers will fail adding the product in their baskets by moving the mouse outside of the product hover zone. This is why this option has been created, allowing merchants to choose wether or not they want to enable the "Add to basket" button. 

I understand that this option can be reworked. 
For example, by allowing merchants to choose from how many combination they want to apply this option:

**Display the "Add to basket" button when the maximum number of combinations a product has is:**
- [ ] **[Insert max combinations]**
- [ ] **Always display**

This is an example but we can also work on the wording to integrate this feature.

**Comment by Hlavtox** [comment]
@prestascott I meant 1.7 as a whole. Lot of useful features were removed and are slowly added back...

Why not just do it the same as it used to be in 1.6. Even woocommerce has it the same. :-)

No combinations or 1? = **Add to cart**
More than 1 combination? = **Select option**

**Comment by matks** [comment]
> @prestascott I meant 1.7 as a whole. Lot of useful features were removed and are slowly added back...

I just wanted to give some insights about this :)

Although all peope who built 1.7.0 are gone so we cannot be sure, I think in PS 1.7.0 some features were removed in an attempt to make the software simpler and lighter.

If you keep adding feature to a software, and more, and more, and more, the software starts to suffer from [feature bloating](https://www.productplan.com/glossary/feature-bloat/) and the maintainance costs explodes. At some point there is so many things to keep working with every change that each new little addition takes months to be validated 😄  . So I would not be surprised that the people who built PS 1.7.0 decided to _intentionally_ remove the features they thought were the least useful for merchants.

Obviously "the least useful" is a very complex statement 😄 . Recently we did the same for modules: PrestaShop open source project was bloated with free modules and we could not keep up with the maintainance cost. So we surveyed more than 600 PS users and asked them what modules were essentials and what modules were not. Then, using this list, [we decided to stop maintaining the least useful modules](https://build.prestashop.com/news/focusing-on-essential-modules/).

Obviously 3 days after this, we had people telling us we were doing a very bad business move and that we "killed the most important modules, and that nobody an run PS 1.7 without these modules". That is what is amazing with a userbase as large as PrestaShop (300,000 shops): whatever you remove from the software, you're sure it was the key feature for someone 😅  .

However you know what they say about bugs? 😉  Having bugs in a software is inevitable, **what is important is how quick you can fix them**. Same for removing features in PS: everytime we remove a bunch of features, we have people complain and this is where we can see if the feature was indeed not important... or it was a mistake 😄  (and mistakes happen !)

I expect that, when we build PrestaShop 8, _we will again remove some features_. And there will be people telling us that "there was a really cool feature in PS 1.7 and in PS 8.0 it's gone, you are doing a very bad job !" but delivering a major version is the most suitable moment to make the software a bit lighter by removing the (what we believe) unnecessary things. It's the most suitable moment to fight against feature bloating. It's just software lifecycle 😄  . Also when we build PrestaShop 8.0.0 there will be Beta periods and Release Candidates: so it will the best moment for people to check what it looks like and tell us if we removed something that they believe was a core feature in the project.

So, to make it short: it's OK to remove features in software. It's even _necessary_ if you want to keep the project maintainable over years: remove the stuff almost nobody uses, focus on the stuff everybody relies on. I'm quite sure the needs of people in 2010 and the needs of people in 2020 are different so a key feature in PS 1.2 might be a cheap and useless setting in PS 1.7, and it's OK to remove it*. It's a matter of balance, value, and maintainance cost.

*Obviously if there was someone running PS 1.2 and then he upgrades to PS 1.7 he's going to shout at us "why did you make me upgrade if PS 1.7 is worse than PS 1.2 !!!" 😅

**Comment by jf-viguier** [comment]
@matks Do you mean that "Add to cart" button on product list is a feature from the past or it's about "1.7 as a whole" ?

**Comment by alfonsolr09** [comment]
> Then change it to "Select variant", like it was in 1.6 :-)
> 
> ![addtocart](https://user-images.githubusercontent.com/6097524/109820119-ff66c180-7c34-11eb-933c-e8d11f082b88.png)
> 

What if the product has 3 different categories?

**Comment by matks** [comment]
I'm not sure to understand the question.

What I wanted to say, 9 months ago 😛  is that "removing features in a software" is normal, and should not be considered "a will to kill the free software and sell more modules". It's part of a never-ending improvement process and sometimes to improve an application you remove some stuff.

As for the "Add to cart" button I have no idea 🤷‍♀️  I'm no PM nor UX, and I dont know merchants enough to say what they really need.

What I know is that:
- I trust my peers to do what they believe is the right thing
- if my peers did a mistake, it happens, I trust them to be listening to feedbacks and change their mind

**Comment by jf-viguier** [comment]
Thanks @matks, i'm talking about this comment from @Hlavtox here:
https://github.com/PrestaShop/theme-refacto/issues/132#issuecomment-985592536
"I would like to do it and many merchants want it, but product team has the final word, unfortunately."

@Hlavtox can you tell us if you where talking about this Matks comment as "the final word" or is it elsewhere ?

Can we have an PM update on this ?

**Comment by Hlavtox** [comment]
@jf-viguier Nono, just as the situation a whole.


**You know, we can't just have a simple solution:**
- No combinations? = Add to cart (directly)
- Combination? = Select option (link to product page)


**We need to create some imaginary problems:**
> Just imagine customers struggling with choosing more than 2 combinations before adding the product in their baskets, it's too complicated. Plus it's on hover, there's a lot of chance that customers will fail adding the product in their baskets by moving the mouse outside of the product hover zone.

**Comment by jf-viguier** [comment]
> @jf-viguier Nono, just as the situation a whole.
> 
> **You know, we can't just have a simple solution:**
> 
> * No combinations? = Add to cart (directly)
> * Combination? = Select option (link to product page)

I do it like that for all my customers since years, I've no issue.

**Comment by Hlavtox** [comment]
@jf-viguier My solution on one of my customer's store. If Prestashop should be an awesome platform with solid base for everyone, it should have this implemented - and possibly disabled by default or just commented out in the template, but ready to go.

![Výstřižek](https://user-images.githubusercontent.com/6097524/144941447-c31ed8ca-cac3-4853-825b-06117fd93ea1.JPG)

**Comment by SharakPL** [comment]
> **You know, we can't just have a simple solution:**
> 
>     * No combinations? = Add to cart (directly)
>     * Combination? = Select option (link to product page)
> 
Why not? This is obvious way of using add to cart button on product list. In your example there's even a place for +/- buttons, Although __Buy__ sounds too definitive. You're not buying, you're only adding product to the cart.

IMO only con of this is SEM. Clicks matter and this way you would rarely open product page when you could just buy it straight from the category list or homepage.

Would be best to add configuration for that in the admin:

- *Enable **Add to cart** button on product list: YES | NO*
  - *Allow changing amount: YES | NO* 

Some shops have only simple products and these could use it the most and some have mostly/only combined products so they could turn it off.

**Comment by ttoine** [comment]
Hello @hlavtox

Your [answer](https://github.com/PrestaShop/PrestaShop/issues/23496#issuecomment-986808099) is again disrespectful of the [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md). Of course, we are not creating imaginary problems. As already explained in [another issue](https://github.com/PrestaShop/PrestaShop/issues/25313), the role of Product Managers and Product Designers is to find solutions that meet everyone's needs (300000 merchants, not just your workflow).

**Comment by alfonsolr09** [comment]
I believe that at no time did he violate the code of conduct, I believe that he is simply giving his opinion in a discussion of a problem.

**Comment by Hlavtox** [comment]
Inspiration: https://www.prusa3d.com/

![57EBFC18-AC53-4A67-8FE2-BBF123695CB3](https://user-images.githubusercontent.com/6097524/147345698-db62f00e-d648-41b7-8af4-bdd2e02f1631.png)

**Comment by NeOMakinG** [comment]
Closing in favor of https://github.com/PrestaShop/hummingbird/issues/347
