### ISSUE TITLE
FO - An exception is displayed when when selecting a language with incorrect data - ps_linklist

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23506]
#### Describe the bug

This issue is reproduced with ps_linklist v4.0.0 only which is compatible with min PS1770
 When we create a language with incorrect data, An exception is displayed when selecting  this language

#### Expected behavior

FO should be well displayed

#### Steps to Reproduce

0. check that the module ps_linlist is v4.0.0, if no try to upgrade the module
1. Go to BO > International > Localization > Languages Tab
2. Create a language with incorrect data, for example: 
![image](https://user-images.githubusercontent.com/16067358/109637339-f5699380-7b4c-11eb-9f52-f0b30b17f6bf.png) 
3. Go to FO > select the language created => see error 
![image](https://user-images.githubusercontent.com/16067358/109637422-1205cb80-7b4d-11eb-8dff-366786097dac.png)

If ps_linklist is v3.2.0 => OK

#### Additional information

* PrestaShop version: 1772, 177x, 1770
* PHP version: 7.1
* ps_linklist version: 4.0.0

**Comment by Progi1984** [comment]
Fixed by #23925
