### ISSUE TITLE
PDF - Delivery slip not printing carrier 

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#23500]
Hi

Prestashop Version tested 1.7.7.2 (i´m using 1.7.6.5 and facing this issue)

Fresh Install

In delivery slip, the pdf it´s not printing the carrier.

tpl file as table for carrier, but is not showing/printing

![Capturar](https://user-images.githubusercontent.com/54105234/109823823-2ff82c80-7c30-11eb-8041-913ec7468fe4.JPG)
![Capturar](https://user-images.githubusercontent.com/54105234/109823979-51591880-7c30-11eb-93e0-802795bbf195.JPG)

Version 1.7.6.5
![Capturar](https://user-images.githubusercontent.com/54105234/109836363-fc230400-7c3b-11eb-9b5c-02bf0b9730e9.JPG)

delivery-slip.shipping-tab.tpl
```
<table id="shipping-tab" width="100%">
	<tr>
		<td class="shipping center small grey bold" width="44%">{l s='Carrier' d='Shop.Pdf' pdf='true'}</td>
		<td class="shipping center small white" width="56%">{$carrier->name}</td>
	</tr>
</table>
```

`<table id="shipping-tab" width="100%">
	<tr>
		<td class="shipping center small grey bold" width="44%">{l s='Carrier' d='Shop.Pdf' pdf='true'}</td>
		<td class="shipping center small white" width="56%">{$carrier->name}</td>
	</tr>
</table>`

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

Could you please edit your issue description **following the provided template to submit a complete bug report**.
Please edit and notify me.

Thanks!

**Comment by Borgas** [comment]
> 
> 
> Hello @Borgas
> 
> Could you please edit your issue description **following the provided template to submit a complete bug report**.
> Please edit and notify me.
> 
> Thanks!

Hi @hibatallahAouadni 

Fresh install of 1.7.7.2 - File delivery-slip.shipping-tab.tpl missing (pdf folder)

**Comment by florine2623** [comment]
Hi @Borgas ,

You can see here the official files in PS 1.7.6.5 :
https://github.com/PrestaShop/PrestaShop/tree/1.7.6.5/pdf
![Capture d’écran 2021-03-04 à 15 21 01](https://user-images.githubusercontent.com/16019289/109977572-3d2f1d00-7cfd-11eb-8b0e-df5520883ab7.png)

There's no delivery-slip.shipping-tab.tpl

The carrier is specified on top of the document :
![Capture d’écran 2021-03-04 à 15 21 53](https://user-images.githubusercontent.com/16019289/109977766-749dc980-7cfd-11eb-9cd3-8c659dbdfc0c.png)

So I close your issue.
Thanks
