### ISSUE TITLE
actionAdminOrdersListingFieldsModifier Hook is broken in 1.7.7

### ISSUE THREAD

**Issue by yayolius** [PrestaShop/PrestaShop#23513]
I was informed that a custom module that i created stopped working in 1.7.7, started to check and the problem seems to be that the hook is simply not been called after the redesign of the Orders View.

There is nothing in this version release doc that points to it: https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/

There are also people in stackoverflow (https://stackoverflow.com/questions/65297235/adding-a-new-column-in-the-list-of-orders-prestashop-1-7-7-0) and this forum that has the same issue.

Is this a bug or a undocumented change or side effect?

**Comment by florine2623** [comment]
Hello @yayolius ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thanks!

**Comment by matks** [comment]
Hi @yayolius every time a Back Office page is migrated from PrestaShop legacy framework to Symfony, all the hooks related to the legacy architecture are modified, replaced by new hooks related to Symfony architecture.

The hook `action{Controller}ListingFieldsModifier` is available in all legacy admin controllers, so everytime a Back Office page is not powered anymore by it, they cease to function.

But you'll find equivalent hooks in Symfony architecture, see https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/modify-grid-in-module/ for example
