### ISSUE TITLE
"pagesnotfound" module is not working

### ISSUE THREAD

**Issue by bullmade** [PrestaShop/PrestaShop#23512]
#### Describe the bug

The module "pagesnotfound" which is part of the statistics is not working for PrestaShop 1.7. We have tested on multiple installations (1.7.7.0, 1.7.6.5, 1.7.6.3) and they are all not working.

I assume the module is outdated (last release 2017), but then it should either be fixed or removed. The former is obviously preffered.

#### Expected behavior

Should log 404 hits.

#### Steps to Reproduce

1. Go to any 404 page.
2. See if the page is logged.

**Comment by florine2623** [comment]
Hi @bulldesign ,

I can't reproduce your issue 1.7.7.0 and 1.7.7.2.
Pages not found module is enabled, I have access to the not pages in statistics :
![Capture d’écran 2021-03-04 à 09 03 02](https://user-images.githubusercontent.com/16019289/109930946-82852780-7cc8-11eb-8536-735adb0a3b6c.png)
![Capture d’écran 2021-03-04 à 09 05 36](https://user-images.githubusercontent.com/16019289/109931220-dbed5680-7cc8-11eb-90d5-aa81be90454b.png)
![Capture d’écran 2021-03-04 à 09 05 45](https://user-images.githubusercontent.com/16019289/109931224-de4fb080-7cc8-11eb-9703-1c194778ef84.png)

Please make sure your data range is correct :
![Capture d’écran 2021-03-04 à 09 06 42](https://user-images.githubusercontent.com/16019289/109931290-f58e9e00-7cc8-11eb-852b-062b1fb8e72c.png)

Thanks!

**Comment by matks** [comment]
Hi @bulldesign, just like @florine2623 I dont reproduce.

1. Install PS 1.7.7
2. Go to FO, visit pages that dont exist like `/aa` or `/abb`
3. I can see the logs correctly registered in my MySQL database
![Capture d’écran 2021-03-04 à 09 10 14](https://user-images.githubusercontent.com/3830050/109931734-7d74a800-7cc9-11eb-8457-60c40063dda7.png)
4. Go to BO, open Statistics page, make sure you are looking at the right range of date
5. See data
