### ISSUE TITLE
We found suspicious file ".listing" into the Prestashop 1.7.6.9 core

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#23517]
Dear staff 
we found a suspicious files called **.listing**, I wanted to ask you if these files are part of the Prestashop 1.7 core.
Thanks for any replying.
Balla

**Comment by matks** [comment]
Hi @ballashop you can find the official 1.7.6.9 ZIP there https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.9. You can open the ZIP to compare with your shop.

Although some files are added by the install process, I dont think there is `.listing` files that should be there. I think you're safe to remove them.

**Comment by ballashop** [comment]
Hi @matks,
thanks a lot for your message.
I'll let you know.
Balla

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

Any news about your issue?

Thanks!

**Comment by ballashop** [comment]
Hi @hibatallahAouadni,
sorry for my deley.
I have no news about it, I deleted the files as suggested by @matks.
Thanks a lot.
Balla

**Comment by hibatallahAouadni** [comment]
Hello @ballashop 

Thanks for your feedback!
So, I close this issue :wink: 

Thanks!
