### ISSUE TITLE
Date setting with order confirmation

### ISSUE THREAD

**Issue by christianHMK** [PrestaShop/PrestaShop#23524]
After the order has been placed, the customer receives a confirmation by email, here is under {date} Y-m-d H: i: s. It would be good to show the date here as just. Or optionally to store a {date2} which only contains the date and could then also be included in other confirmations. Many Thanks.

**Comment by florine2623** [comment]
Dear @christianHMK ,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

If it is a new feature or an improvement you want to suggest, please follow the right template too.

Thank you
