### ISSUE TITLE
Linklist - Make the listing multistore compliant

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#23521]
As a merchant I want to be able to see a list of my blocks according to the context selected, so I can easily manage my blocks

[Specifications of the listing](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#actions-in-the-lisitngs-grids)

[Specs for ps_linklist module](https://github.com/PrestaShop/prestashop-specs/blob/master/modules/ps_linklist.md)

**Comment by matks** [comment]
Pull Request https://github.com/PrestaShop/ps_linklist/pull/114 has been merged. The fix for this issue is expected to be delivered with v5.0.0 of Linklist module.
