### ISSUE TITLE
Error 500 after discount coupon for free shipping applied on cart

### ISSUE THREAD

**Issue by diegofrancesco** [PrestaShop/PrestaShop#23529]
**Describe the bug**

I get an error after applying a discount coupon to the cart, but only if the coupon gives free shipping. When I apply the coupon, nothing seems to happen. Then if I update the browser tab or click on the site I have a blank page.
All other types of coupons do not generate errors. 

In debug mode I see the error:

<img width="1037" alt="http error" src="https://user-images.githubusercontent.com/80057578/109997312-5d1c0c00-7d10-11eb-8d6d-6fdc1548cfd3.png">

**Steps to Reproduce**

Basket rules -> Free shipping: yes

![discount](https://user-images.githubusercontent.com/80057578/109997819-e4697f80-7d10-11eb-8b57-617fa7ae885e.png)

**Additional information**

* PrestaShop version: 1.7.2.4
* PHP version: 7.1.33

**Comment by florine2623** [comment]
Hello @diegofrancesco ,

I can't reproduce your issue in PS 1.7.2.4.
![Capture d’écran 2021-03-05 à 17 23 54](https://user-images.githubusercontent.com/16019289/110143475-95d2e880-7dd7-11eb-9a2c-37d950cf27ea.png)


If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
