### ISSUE TITLE
BO / Cart rule / Improve product selection

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#23526]
#### Is your feature request related to a problem?

On a large catalog, product and category selection is messy on cart rule condition tab :
- Fancy box is too small
- If an item is too long to fit in the select, there is no way to see the end : no horizontal scrollbar

![Capture d’écran 2021-03-04 à 16 59 40](https://user-images.githubusercontent.com/16019289/109992204-53dc7080-7d0b-11eb-8552-f3489765029d.png)

#### Describe the solution you'd like

Use overflow:auto on select[multiple]

![image](https://user-images.githubusercontent.com/23308427/110013897-74fc8b80-7d22-11eb-8714-e763f8730422.png)

![image](https://user-images.githubusercontent.com/23308427/110013949-82197a80-7d22-11eb-8d42-627833885504.png)

**Comment by florine2623** [comment]
Hello @jf-viguier 

In BO > Discounts > Cart Rules > Add new cart rule > Go to Condition tab,
when category/product name is too long, the user can't see the whole title :
![Capture d’écran 2021-03-04 à 16 59 40](https://user-images.githubusercontent.com/16019289/109992204-53dc7080-7d0b-11eb-8552-f3489765029d.png)

~What do you think we can implement to make it more visible ?~
> Edit hiba

Thanks @jf-viguier for your improvement and your PR :wink:  
The Product Team will take a look. Please stay tuned!

Ping @PrestaShop/product-team ,I think it'll be great if we could implement what @jf-viguier proposed, but I don't know if it could impact other multiple select, I guess we should check with @NeOMakinG :wink:

**Comment by jf-viguier** [comment]
@florine2623 I've posted a PR that solve the two issues.
