### ISSUE TITLE
PrestoChango UPS module not charging enough on certain products.

### ISSUE THREAD

**Issue by nateBitworks** [PrestaShop/PrestaShop#23532]
#### Describe the bug
When a customer orders certain products the Presto Changeo UPS module configures the wrong price, almost 2/3 what the UPS charges.
A clear and concise description of what went wrong.

#### Expected behavior
Charge correct shipping
Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to centrevilletrailer.com
2. Search for product # BHM-BK-349-PVC-P
3. Add to cart and order as a guest
4. for an address put in the following 2169 Hester Rd, Creedmoor, NC, USA 27522
5. Select UPS ground
6. The shipping should be $71, you will notice shipping is 29.71

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.1.33

**Comment by florine2623** [comment]
Hello @nateBitworks ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
