### ISSUE TITLE
BO - The gamification icon is not displayed after disabling all notifications

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23537]
#### Describe the bug

In the BO > Advanced Parameters > Administration page, when we disable all notifications (new orders, new customers, new messages), the icon of the gamification module is not displayed anymore with errors in the console

#### Expected behavior

It should be displayed

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Administration page
2. Disable all notifications (new orders, new customers, new messages)
3. See error: the icon of the gamification module is not displayed anymore when errors in the console

![image](https://user-images.githubusercontent.com/16067358/110110615-64debd80-7daf-11eb-9ffd-d4d1fa5e2726.png)

#### Additional information

* PrestaShop version: 1.7.6.5, 1772, develop
* PHP version: 7.1

**Comment by Progi1984** [comment]
@khouloudbelguith Sorry the module `gamification` is now managed by the `PrestaShopCorp` organization. Could you create a new issue on their issues board : https://github.com/PrestaShopCorp/gamification/issues/new ? Thank you for your help.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Done: https://github.com/PrestaShopCorp/gamification/issues/97

Thanks!
