### ISSUE TITLE
Orders brothers (with same reference)

### ISSUE THREAD

**Issue by mathieuhen** [PrestaShop/PrestaShop#23535]
Hi, 

Sometimes we have an order that splits into 2 orders (brothers, with same reference).
After analysis, we realize that these are the orders whose cart has the delivery_option column with 2 values.
Why 2 values in this column (as in the picture below) ? 
How to prevent this?

![Capture](https://user-images.githubusercontent.com/43207184/110099111-3b1e9a00-7da1-11eb-8753-1dfb2196a3b1.PNG)

**Comment by florine2623** [comment]
Hello @mathieuhen ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by mathieuhen** [comment]
Thank you for reply @florine2623! 
But I never said it was a bug. I'm just asking in which cases we have 2 values in this column and how to avoid it? (if there is an option in admin for example ?)
