### ISSUE TITLE
Add an option to keep inactive products enabled

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23533]
## Is your feature request related to a problem?

When you disable a product, these are options of we can do with them.
- 404
- 410
- 301 product redirect
- 302 product redirect
- 301 category redirect
- 302 category redirect

None of these options tell the customer what happened, why they cannot reach the page or why they are not shown the product they clicked on on google. 404 is something like a plague, it should be avoided at all costs and incredibly hurts the site's SEO.

## Describe the solution you'd like

Add an option not to return anything and just display the page. This is done by Amazon, eBay and all the big sellers.
User would land on the product page, see add-to-cart disabled and he would know what happened and would not be confused.
We can also display other products from the default category of this product.

The modification would not be difficult and would require only small tweak in ProductController and the template.

## Design proposition

![Výstřižek](https://user-images.githubusercontent.com/6097524/110091253-8ed8b580-7d98-11eb-832b-e4c41c3c8b30.JPG)

### 1. New options on product page
- 200 (keep product displayed as discontinued)
- 404 (keep product displayed as discontinued)
- 410 (keep product displayed as discontinued)
- default (as set in prestashop settings)

### 2. Helper text under these options
![Snímek obrazovky 2022-09-22 131014](https://user-images.githubusercontent.com/6097524/191731793-cb9809bc-a073-4826-be60-c0ec5b955e59.jpg)

### 3. New option in prestashop settings called `Default behavior for disabled products`. You could select a default state that all products will have. Options:
- 404
- 410
- 200 (keep product displayed as discontinued)
- 404 (keep product displayed as discontinued)
- 410 (keep product displayed as discontinued)

```sql
ALTER TABLE `ps_product` CHANGE `redirect_type` `redirect_type` ENUM('404','410','301-product','302-product','301-category','302-category','200-displayed','404-displayed','410-displayed','default') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'default';
```

**Comment by florine2623** [comment]
Hi @Hlavtox ,

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team ,
What do you think ? Could this be implemented ?
Thanks !

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,
What do you think ? Could this be implemented ?
Thanks !

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I like the idea to display the disabled product with a message clearing the situation. 
But what if we had more than 100 disabled product? :thinking: 

Ping @PrestaShop/product-team I think it'll be better if the product is disabled, we add another option for the merchant to choose if he want to display the product wih a link to the parent category, wdyt?

**Comment by Hlavtox** [comment]
@florine2623 @hibatallahAouadni We can also add a switch for default behavior - 404 or keep enabled. 

The same as we do for backorders - “default as in ps settings” or manually specify in product options. :)

**Comment by Hlavtox** [comment]
@kpodemski @tswfi @lmeyer1 @jf-viguier 

Guys, is it something you also went across? I would like to spec it up and implement. All big players like eBay do it like this. 👍

It's not gonna be difficult:
- One extra option in selectbox on product edit page.
- One option to PS settings to select default behavior - Do you want 404 or keep it displayed?
- Small ProductController modification and template tweak. I have it finished on my Prestashop.

**Comment by MatShir** [comment]
It would be interesting to find a way when the product is unavailable to highlight the cross-selling/upselling/related product modules

**Comment by Hlavtox** [comment]
Yes, but I think we could do it as a module, if people want. See my solution. :-) But for the base, I think the message could be enough.

![www dobracena cz_plynove-grily_930567-gril-campingaz-4-series-onyx-s-3138522119294 html_adtoken=3c4d2f05bc8887fcfad31a62bc30d767 ad=id_product id_employee=4 preview=1](https://user-images.githubusercontent.com/6097524/148397838-a11c155c-2091-40ab-bd8b-c0c03c34fef5.png)

**Comment by MatShir** [comment]
Thanks now, I want a BQQ ! Yes, you are right, then it would be the theme or module dev to bring customization.

**Comment by jf-viguier** [comment]
Can be solved with visibility settings like this: 
![image](https://user-images.githubusercontent.com/16720275/148399915-102e2d86-ffae-4b33-9473-8e0c69eced72.png)

**Comment by Hlavtox** [comment]
@MatShir 🤣🤣 I will give you discount ❤️

@jf-viguier You cannot. If the customer gets to this page from google, he will still be able to order it. Also, the product will be visible in your active products listings etc.

**Comment by lmeyer1** [comment]
@Hlavtox In our case, we are selling books. It is very important, that `Out of print` books stay on the website, but without the possibility to order. We display `Out of print` as availability text, and do not allow it to be added to the cart.

The properties are in the table `product_shop`, fields `availability`, `available_now` and `available_later`. We update these fields with a synchronisation with our ERP system. We don't use BO product page at all.

**Comment by Hlavtox** [comment]
@MatShir @kpodemski A real life example I stumbled upon right now, not the best looks, but does the job. :-) If I came on this page on Prestashop shop, I would get 404 and leave the page.

![discarded](https://user-images.githubusercontent.com/6097524/191715034-b3de4d34-3bcd-42d4-968a-f84c520d92a2.jpg)

**Comment by marsaldev** [comment]
Agree with @Hlavtox, it happens very often in the car spare parts shops.
Give the option to "follow" the new product, having the old one still active but not orderable, will preserve the positioning in the search engines
