### ISSUE TITLE
Could not find control by type: button on create or edit Product

### ISSUE THREAD

**Issue by oalija** [PrestaShop/PrestaShop#23536]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

When try create or edit Product, summary and description fields not show for javascript error "Uncaught Error: Could not find control by type: button"

#### Steps to Reproduce

1. Go to create or edit product
2. See error

**Screenshots**

![imagen](https://user-images.githubusercontent.com/7903249/110107176-dbc58780-7daa-11eb-8510-3faf76011823.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello,

I can't reproduce your issue in PS 1.7.8.0 :
Edit product :
![Capture d’écran 2021-03-05 à 12 46 49](https://user-images.githubusercontent.com/16019289/110111587-dcf9b300-7db0-11eb-85e2-2ba574ecc368.png)
Create Product :
![Capture d’écran 2021-03-05 à 12 47 55](https://user-images.githubusercontent.com/16019289/110111688-04508000-7db1-11eb-9087-29c16dc481f1.png)
