### ISSUE TITLE
Wrong definition of Schema.org availability for out-of-stock products.

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23534]
#### Describe the bug

Structured data availability (used by search engines to display rich snippets in results) is defined in ProductLazyArray.

```
if ($this->product['quantity'] > 0) {
    $seoAvailability .= 'InStock';
} elseif ($this->product['quantity'] <= 0 && $this->product['allow_oosp']) {
    $seoAvailability .= 'PreOrder';
} else {
    $seoAvailability .= 'OutOfStock';
}
```

Preorder should not be there, OutOfStock should be used instead.

> Note: The preorder value should only be used for new products and shouldn't be used for existing products that are out of stock and will be back in stock at a later date.​

Source: https://support.google.com/merchants/answer/6324448?hl=en

#### Expected behavior

```
if ($this->product['quantity'] > 0) {
    $seoAvailability .= 'InStock';
} else {
    $seoAvailability .= 'OutOfStock';
}
```

#### Steps to Reproduce

1. FO, in the product page template, put {$product.seo_availability} anywhere
2. Check it out for products with available quantity
3. Then with 0 quantity and OOSP enabled
4. And with 0 quantity and OOSP disabled

#### Additional information
* PrestaShop version: 1.7

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Could you take a look at this please ?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Could you please check this issue #23199 it seems similar to yours :wink: 
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Simmilar point in code, but different problem

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

So we should delete these lines:

```
elseif ($this->product['quantity'] <= 0 && $this->product['allow_oosp']) {
    $seoAvailability .= 'PreOrder';
}
```

Cause the PreOrder definition is: 

> You’re currently taking orders for this product, but it’s not yet been released for sale. You can use the **availability_date** attribute to indicate the day that the product becomes available for delivery.
> 
> **Note**: The **preorder** value should **only be used for new products** and **shouldn't be used for existing products** that are out of stock and will be back in stock at a later date.​

(originally posted [here](https://support.google.com/merchants/answer/6324448?hl=en))

It seems to me this issue is an improvement more than a bug :wink: 
Let's see with the Product Team, stay tuned!

Ping @PrestaShop/product-team I think it'll be better if we only assign the **`PreOrder`** value to the `$seoAvailability` when the product is new and not yet been released for sale, wdyt?

**Comment by alfonsolr09** [comment]
@Hlavtox pls check this  https://github.com/PrestaShop/PrestaShop/pull/23248

**Comment by Hlavtox** [comment]
@alfonsolr09 Let's make a new PR that implement both your fix and the issue I described here ;-)

**Comment by alfonsolr09** [comment]
my solution is not the best way to fix the error as well matks said in my thread

**Comment by idnovate** [comment]
Same problem here :blush: (https://github.com/PrestaShop/PrestaShop/issues/28552)

We have set stock for all products to `999999` to display the status as `InStock`, and we don't have to modify the code then.

**Comment by alfonsolr09** [comment]
> We have set stock for all products to `999999` to display the status as `InStock`, and we don't have to modify the code then.

same "solution" to me

**Comment by Hlavtox** [comment]
@idnovate @alfonsolr09 It's gonna be fixed, I will finish my PR regarding this. 👍

**Comment by alfonsolr09** [comment]
And what happens with this??, its similar issue @Hlavtox 
https://github.com/PrestaShop/PrestaShop/pull/23248

**Comment by Hlavtox** [comment]
@alfonsolr09 Also fixed don't worry

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/29411
