### ISSUE TITLE
Wrong Multistore context displayed in migrated page Shop Parameters > Order Settings > Order Status

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#23538]
#### Describe the bug

With Multistore ON : On the migrated Shop Parameters > Order Settings > Order Status page (http://localhost/psdevelop/develop/admin-dev/index.php/configure/shop/order-states/), the context displayed in the header should be always "All shops". Currently, the context can be modified by shop and group of shop (but the actions are in fact made in all shops context, it's just the display in the header that is wrong).

It's a regression since on Legacy page, the context is forced to All Shops.

#### Expected behavior

On Order Status page the context displayed in the header should be always "All shops". See [specification](https://github.com/PrestaShop/prestashop-specs/pull/207)

#### Steps to Reproduce

0. Activated Multistore and create groups and shops
1. Go to BO > http://localhost/psdevelop/develop/admin-dev/index.php/configure/shop/order-states/
2. See in the header : The context can be modified from "All Shops" to group of shop context, it should not.

**Screenshots**

![page status multistore context](https://user-images.githubusercontent.com/55688534/110110302-e6821b80-7dae-11eb-8250-0797c7153ea9.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by kpodemski** [comment]
@matthieu-rolland 

I think you need to see this, this is related to your PR I guess 🤔 
https://github.com/PrestaShop/PrestaShop/pull/23292/

**Comment by Progi1984** [comment]
Fixed in #24527 by @Progi1984
