### ISSUE TITLE
BO / Cart rule / titles not neutralized 

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#23540]
#### Describe the bug

Minor display and security issue : title are not neutralized on product or category selection.

#### Expected behavior

Product or category should be displayed correctly.

#### Steps to Reproduce

1. Go to category
2. Add a category named with a " like Art et "essai
3. Add a category restriction to a cart rule
4. See error : title is truncated

This could be a security issue if you inject a <script>tag after the "

**Screenshots**

![image](https://user-images.githubusercontent.com/16720275/110138129-ef381900-7dd1-11eb-91c2-9eddbf69cdf3.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by florine2623** [comment]
Hello @jf-viguier ,

I can't reproduce your issue on develop, I tried multiple combinations :
![Capture d’écran 2021-03-05 à 17 03 01](https://user-images.githubusercontent.com/16019289/110140777-bcdbeb00-7dd4-11eb-8d46-d2846bf8b461.png)
![Capture d’écran 2021-03-05 à 17 01 13](https://user-images.githubusercontent.com/16019289/110140787-bf3e4500-7dd4-11eb-9dd0-58775a8b0125.png)
![Capture d’écran 2021-03-05 à 17 00 38](https://user-images.githubusercontent.com/16019289/110140799-c2393580-7dd4-11eb-9627-87a10ada088a.png)

Am i missing something ?
Thanks

**Comment by PierreRambaud** [comment]
I manage to reproduce the issue. I complete the PR the be sure all data are correctly escaped. Thanks you @jf-viguier :wink:

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

I manage to reproduce the issue with PS1.7.6.7, PS1.7.7.2 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110147352-df253700-7ddb-11eb-9cd8-a73d8ca3999d.png)

Thanks for your issue and your PR :rocket: 

PS: thanks @PierreRambaud for reproducing the issue :wink:
