### ISSUE TITLE
Problem open historic orders from before upgrade to version 1.7.7.2

### ISSUE THREAD

**Issue by Kaktusodlarn** [PrestaShop/PrestaShop#23549]
#### Describe the bug

On the order tab in BO it is not possible to open some of the historic orders from before the upgrade to version 1.7.7.2. It fails with a 500 error

#### Expected behavior

Expected result is that the historic order open.

#### Steps to Reproduce

1. Go to orders -> new order
2. Click on any historic order either the magnifying glass or the arrow by the order id number
3. Fails with 500 error - see attached screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/80204246/110241783-f5a1ce80-7f52-11eb-8fd6-a20b3418675f.png)
![image](https://user-images.githubusercontent.com/80204246/110241828-3ef21e00-7f53-11eb-9644-19508c8bc14f.png)
![image](https://user-images.githubusercontent.com/80204246/110241758-c12e1280-7f52-11eb-83e0-8d349b4495f8.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1 and 7.3

**Comment by matks** [comment]
It sounds similar to https://github.com/PrestaShop/PrestaShop/issues/23336

**Comment by hibatallahAouadni** [comment]
Hello @Kaktusodlarn 

Could you please check this issue #23336 it seems similar to yours..
Please check and feedback.

PS: Thanks @matks :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Kaktusodlarn ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
