### ISSUE TITLE
hook "actionObjectOrderDetailUpdateAfter" not executed on "Partial Refund" action or "Return product" action

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#23559]
#### Describe the bug

When a partial refund, or product return is made from the order detail page, I think all the necessary hooks should be called on the OrderDetail object, since it is updated by these actions.
Actually, only the "productCancel" hook is called.

#### Expected behavior

I hope to have all the object updated by these actions properly calling their own update hooks.

#### Steps to Reproduce

1. Enter an order detail view in admin
2. Switch the status to "Delivered".
3. Try to make a partial refund, or product return

#### Additional information

* PrestaShop version: at least 1.7.7.0, but probably many others

**Comment by hibatallahAouadni** [comment]
Hello @Prestaplugins 

Could you please provide a screen record or screenshot of the issue.

Thanks!

**Comment by Prestaplugins** [comment]
How could I provide a screenshot of something that is not called ?
The order_detail table is updated in database when you return or refund a product, so I just think the actionObjectOrderDetailUpdateAfter hook should be called on those actions (and so the actionObjectOrderDetailUpdateBefore too).

**Comment by hibatallahAouadni** [comment]
Hello @Prestaplugins 

> How could I provide a screenshot of something that is not called ?

Please enable the debug mode and open the Symfony bar, then when it suppose to call the hook, just take a screenshot (like this one):

![image](https://user-images.githubusercontent.com/23308427/110448008-1720c880-80c1-11eb-9f6f-09102f34f236.png)

I just need to confirm the list of called hooks :wink: 

Please check and feedback.
Thanks!

**Comment by Prestaplugins** [comment]
Sorry... I just realised my test was done on 1.7.7.0 and not 1.7.7.1 as mentioned.
It works on 1.7.7.1 so it has probably already been fixed ;-)

About the screenshot, I couldn't do it, the page is reloaded when you do a refund, so the list of hooks is just the one used to display the order detail page.

I think you can close the issue. Sorry.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaplugins 

Glad to hear :tada: 
And thanks for your feedback!
