### ISSUE TITLE
Danish language error: Indkøbsindkøbskurv (shoppingshoppingcart)

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#23552]
#### Describe the bug

In the Danish translation of the current version of Prestashop, there are quite a few occurances of "indkøbsindkøbskurv" (note that "indkøbs" is written twice). Directly translated to English, this means "shoppingshoppingcart" and the extra "indkøbs" (shopping) is every bit as redundant as it would be in English. The correct Danish word for "shoppingcart" is simply "indkøbskurv".

#### Expected behavior

I would have expected the Danish translation to be correct. and thus I would expect the word "shoppingcart" to be correctly translated into "indkøbskurv" (not "indkøbsindkøbskurv").

#### Steps to Reproduce

1: Install the current version of Prestashop with Danish language.
2: Check the translations - you will see quite a few occurances of "indkøbsindkøbskurv".

![image](https://user-images.githubusercontent.com/26773745/110251236-f00ead80-7f7f-11eb-83ef-6d14ce25e821.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.4

**Comment by matks** [comment]
Hi @LarsGMortensen PrestaShop translations are done through an open Translation project https://crowdin.com/project/prestashop-official .

If you think you have found a mistake, we would be very happy to welcome your suggestion, could you please submit the needed change into the project? This will help us go through the proofreading process.

We cannot really verify if your report is true or wrong because... 😅 we do not speak Danish. That is why we need you to use the Crowdin process where Danish proofreaders will be able to discuss with you and verify the statement.

**Comment by hibatallahAouadni** [comment]
Hello @LarsGMortensen 

I reproduce your issue with PS1.7.6.7 and PS1.7.7.2, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110306181-d318bf80-7ffd-11eb-8769-4e8b55c07bab.png)

> We cannot really verify if your report is true or wrong because... sweat_smile we do not speak Danish.

That's true but we can verify with translate google :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/110306371-09563f00-7ffe-11eb-9ef4-2f13fe150b2a.png)

Ping @Julievrz what we should so with this bug? is it better that @LarsGMortensen fix the problem in Crowdin as @matks suggest?

**Comment by Julievrz** [comment]
Hi @hibatallahAouadni 
I agree with @matks, the best thing to do is to go on Crowdin and suggest this translation. @LarsGMortensen Please do not hesitate to contact me on Crowdin (https://crowdin.com/profile/julievrz) if you have any questions!

**Comment by hibatallahAouadni** [comment]
Hello @LarsGMortensen 

Thanks @Julievrz for your response :relaxed: 
So, I close this issue and @LarsGMortensen please reach @Julievrz on Crowdin and suggest this translation.

Thanks!
