### ISSUE TITLE
[swedish language] BO - Product page - Negative specific price cannot be saved with an exception

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23562]
#### Describe the bug

This issue is reported previously [here](https://github.com/PrestaShop/PrestaShop/pull/23137#issuecomment-776657793)
The Swedish language is selected, In the BO > Catalog > Product details page, when we try to update a specific price with negative impact, an exception is displayed

#### Expected behavior

We should have a clear alert as in English `Invalid price/discount amount`
![image](https://user-images.githubusercontent.com/16067358/110313600-f5630b00-8006-11eb-8e27-0a6cca884daa.png)

#### Steps to Reproduce

1. Install shop with English language & France country
2. Go to BO > International > Localization page > Upload Sweden pack
3. Go to BO > Your profile > change the language of the employee to Swedish
4. Go to BO > Catalog > Add a new product
5. Add a specific price with impact on price = -2  ![image](https://user-images.githubusercontent.com/16067358/110313663-0c096200-8007-11eb-8219-f4367f891703.png)
6. Update this specific price by applying a discount of -2 euro  ![image](https://user-images.githubusercontent.com/16067358/110313699-16c3f700-8007-11eb-94e9-aaca797f08f1.png)
7. Save => see error 500 in the console
![image](https://user-images.githubusercontent.com/16067358/110313741-27746d00-8007-11eb-93c2-1b8b7565fc59.png)

#### Additional information

* PrestaShop version: develop, PS1769
* PHP version: 7.2

**Comment by florine2623** [comment]
This is fixed. So I'm closing the issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/ec4c271a-f179-4899-8a2d-41caf721c1ef

<img width="1439" alt="Screenshot 2023-12-27 at 15 03 37" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/965e0541-4711-4758-904d-f7c3c0ad2717">
