### ISSUE TITLE
Add the custom fields to the customer registration form when creating a new customer from the order form in admin

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#23565]
#### Is your feature request related to a problem?

When creating an order from admin, and creating a new customer from that page, the standard customer form is displayed without taking in account any modules using the "additionalCustomerFormFields" hook, which allows to add new custom fields to the registration form.

#### Describe the solution you'd like

It would be nice to include that fields also into admin form, so the employee can set everything at the same place when creating the order.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaplugins 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , is it doable to take in account any modules using the "additionalCustomerFormFields" hook while creating a customer from **BO**>**Orders**>**Orders**>**Create an Order**?

**Comment by Hlavtox** [comment]
@Prestaplugins Hi, this form can be modified via form modification hooks. ;-) https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/actioncontrollerformmodifier/

You can achieve anything with this hook.

**Comment by Prestaplugins** [comment]
There's already a hook specifically made for that, that we can call with 2 lines to add a field to the customer form, and you tell me to use another one which is probably much more complicated ?
I think that's just something forgotten when you added this hook, and now you prefer to close the issue than to improve the backend... :-(

**Comment by Hlavtox** [comment]
@Prestaplugins I know, but it's just two completely different things. The FO form is a weird old front form. The BO is a symfony form like all other forms in the backoffice.

Good thing is that ALL forms in backoffice behave the same way, so if you learn how to use that hook, you can do it everywhere.

Check out the example form here - https://github.com/PrestaShop/example-modules/tree/master/demoextendsymfonyform2

> I think that's just something forgotten when you added this hook, and now you prefer to close the issue than to improve the backend... :-(

What we can do is improve the frontend with a simmilar hook. ;-)
