### ISSUE TITLE
Error whit the Search bar module

### ISSUE THREAD

**Issue by Diegocanet** [PrestaShop/PrestaShop#23563]
Describe the bug

En mi página puedo ver la barra de búsqueda pero no puedo escribir nada, al hacer click no sucede nada. Ya he desintalado e instalado varias veces el módulo pero el problema persiste, fue de un momento a otro ya que al principio funcionaba bien

Expected behavior

Use the search bar without problems

#### Steps to Reproduce

1. Go to 'https://laminibakery.com/'
2. Click on 'search bar'
3. See error
4. 
Additional information

* PrestaShop version: 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @Diegocanet 

> En mi página puedo ver la barra de búsqueda pero no puedo escribir nada, al hacer click no sucede nada. Ya he desintalado e instalado varias veces el módulo pero el problema persiste, fue de un momento a otro ya que al principio funcionaba bien

Please send your request in English. English is the norm on GitHub.

Thank you
