### ISSUE TITLE
Cannot save product after deleting language

### ISSUE THREAD

**Issue by futurehousestore** [PrestaShop/PrestaShop#23571]
#### Describe the bug

I had 2 languages EN-US and EN-GB after changing the default language from EN-US to EN-GB and deleting EN-US I am not able to save changes of any product. I had a look at previous related issues and solutions but nothing has helped.  

#### Steps to Reproduce

1. Create a second language
2. Switch the default language to the new one
3. Remove the previous language
4. Go to any product and save changes 

**Screenshots**

![error](https://user-images.githubusercontent.com/28427270/110396556-1dcf2180-8068-11eb-84a2-d7232de7702b.PNG)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment]
Hello @futurehousestore 

I didn't manage to reproduce the issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1Eo9ILd9bgzQG71swmqs5HipUvipnay5U/view

Could you please enable the **debug mode** and make a screenshot of the **500 error** (to understand better the problem).
Please check and feedback.

Thanks!

**Comment by futurehousestore** [comment]
Hi @hibatallahAouadni 
Thank you for your assistance. I'm not sure if this is all that you need. After enabling the debug mode 
1. the front office crashed 
[front.office.pdf](https://github.com/PrestaShop/PrestaShop/files/6107710/front.office.pdf)

2. Debug has flagged up these issues
![error2](https://user-images.githubusercontent.com/28427270/110455189-06238780-80c0-11eb-8381-627d88108b6d.PNG)


'group' => ($specific_price['id_group'] ? $groups[$specific_price['id_group']]['name'] : $this->translator->trans('All groups', [], 'Admin.Global')),

**Comment by futurehousestore** [comment]
I just realised that I'm also not able to open previous orders in the orders tab. Every order before 0.8.03.2021 gives me this error
![error3](https://user-images.githubusercontent.com/28427270/110457201-4b48b900-80c2-11eb-91fd-e516300e4efe.PNG)

Orders placed after changing and deleting the previous language are accessible.

**Comment by matks** [comment]
@futurehousestore see https://github.com/PrestaShop/PrestaShop/issues/22215

**Comment by hibatallahAouadni** [comment]
Hello @futurehousestore 

Thanks for your feedback!
@matks thanks for the hint :wink: 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22611. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22611

**Comment by futurehousestore** [comment]
Thanks, guys I managed to solve the problem with the viewing orders using @javierrojas10 method from issue #22215 but the main problem regarding saving products still exist. I'm still unable to save the changes.

**Comment by futurehousestore** [comment]
@hibatallahAouadni could you reopen my ticket, please? My ticket is not a duplication of #22611 the #22611 ticket is regarding orders and not the products. My issue is related to #22611 (because the problem appears after deleting the default language) but the problem exists elsewhere and requires a different fix.

**Comment by hibatallahAouadni** [comment]
Hello @futurehousestore 

As I mentioned above I didn't manage to reproduce your issue with the provided informations.
So, could you please provide more infos to help me reproducing the issue.
When, I'll be able to reproduce, then, I will reopen the issue :wink: 

Thanks!

**Comment by futurehousestore** [comment]
Solved. I needed to regenerate webservices key for a module that syncs products from Prestashop to Dolibarr. I just wish the Prestashop error message would at least give a clue what is wrong instead of saying that the settings cannot be saved.

**Comment by hibatallahAouadni** [comment]
Hello @futurehousestore 

> I just wish the Prestashop error message would at least give a clue what is wrong instead of saying that the settings cannot be saved.

Could you please open a new issue as a feature and suggest to improve the error message in this step.

Thanks in advance!
