### ISSUE TITLE
Can't translate a child theme in PrestaShop 1.7.7.2

### ISSUE THREAD

**Issue by jordiweblidera** [PrestaShop/PrestaShop#23574]
#### Describe the bug

After installing a PrestaShop with version 1.7.7.2 and installing a child theme, the child theme cannot be translated.

#### Steps to Reproduce

1. Install a fresh 1.7.7.2
2. Create a child theme (https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/)
3. Go to International > Translations
4. Try to translate the child theme:
![imagen](https://user-images.githubusercontent.com/49748656/110435429-4cbeb500-80b3-11eb-9c03-23f0320583ac.png)
5. The spinner keeps spinning endlessly and shows the error `The "/var/www/vhosts/xxx.xxx/xxx.xxx.xxx/var/cache/prod/themes/childtheme/translations/es-ES" directory does not exist.`:
![imagen](https://user-images.githubusercontent.com/49748656/110435859-d1a9ce80-80b3-11eb-97be-f33789ee91fc.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3.25

**Comment by hibatallahAouadni** [comment]
Hello @jordiweblidera 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15268. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15268

**Comment by jordiweblidera** [comment]
> 
> 
> Hello @jordiweblidera
> 
> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15268.
> To be informed when it's fixed, please subscribe to the issue mentioned above.
> 
> Thanks!

Sorry, I tried to find before without luck 😔. Thanks 😉
