### ISSUE TITLE
Back office - Jquery error

### ISSUE THREAD

**Issue by Bahwaimongars** [PrestaShop/PrestaShop#23577]
**Describe the bug**

When i go to back office, direct in my Dashboard i go this error and in all pages from back office too :

Products
Categories
...

So i cant add products, images .... when i click, nothing happen

I changed nothing since 1 week and this appears.

**Steps to Reproduce**

1. Go to dashboard ( inspect tools and errors show up )
2. In all pages errors occures

**Screenshots**
On dashboard : 
![errorPresta](https://user-images.githubusercontent.com/62238066/110481067-7560a200-80e7-11eb-8e27-31d90d5d0fa3.jpg)

On product's page :
![errorPresta1](https://user-images.githubusercontent.com/62238066/110481102-801b3700-80e7-11eb-9c64-d809b0d854ec.jpg)

Header loading files :
![errorPresta2](https://user-images.githubusercontent.com/62238066/110481119-827d9100-80e7-11eb-80a7-280915c614a1.jpg)

#### Additional information

* PrestaShop version: 1.7.1.1
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @Bahwaimongars 

Is this a fresh install? or did you upgrade lately?
Please check and feedback.

Thanks!

**Comment by Bahwaimongars** [comment]
This is a " fresh " i mean 2 weeks maybe...
The install zip was in 1.7.1.1 no upgraded version if is that you mean

**Comment by NeOMakinG** [comment]
Did you mean : 1.7.7.1?

**Comment by Bahwaimongars** [comment]
Sorry you can close, 
webmaster error.

He use provider optimisation ( compress all files ) >_<

ty
