### ISSUE TITLE
Upgraded to 1.7.7.2 version and can't access Shop Parameters and Advanced Parameters.

### ISSUE THREAD

**Issue by md2158** [PrestaShop/PrestaShop#23575]
#### Describe the bug

Upgraded to 1.7.7.2 version and can't access Shop Parameters and Advanced Parameters. Getting these errors:
Call to a member function compile() on null
Undefined class constant 'Doctrine\Common\Collections\Expr\Comparison::STARTS_WITH'

Please help, how to solve this?

**Screenshots**

![image](https://user-images.githubusercontent.com/13145310/110440397-a8943880-80c9-11eb-89c2-78396b512f09.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @merick2158 

What was your previous version (before upgrade)?
And did you encounter any issue while upgrading?
Please check and feedback.

Thanks!

**Comment by md2158** [comment]
The previous version was 1.7.3.4.

**Comment by md2158** [comment]
Upgraded 1-Click upgrade module and it works. Really strange that the upgrading module itself making errors.

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: 
Thanks for your feedback!
