### ISSUE TITLE
error en categoria , uso mucho entre diferente productors -categorias

### ISSUE THREAD

**Issue by Braian70** [PrestaShop/PrestaShop#23578]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'productos'
2. Click on 'filtrar por categorias'
3. Scroll down to 'elegir categoria, sale bien , si quiero cambiar otra categoria , otra vez tengo que abrir categoria uno a uno '
4. See error ： antes categoria esta expandir en tercera categoria , asi ahorrar mucho tiempo.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Braian70 

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by Braian70** [comment]
Describe the bug
A clear and concise description of what went wrong.

Expected behavior
Explain what you expected to happen instead.

Steps to Reproduce
Steps to reproduce the behavior:

Go to 'products'
Click on 'filter by categories'
Scroll down to 'choose category, it works fine, if I want to change another category, again I have to open category one by one'
See error ： Before category is expand into third category, so save a lot of time.
Screenshots

If applicable, add screenshots or screen recordings to help explain your problem.

Additional information
PrestaShop version: 1.7.6.1
PHP version: N/A
