### ISSUE TITLE
[BO] - Navbar menu - missing css

### ISSUE THREAD

**Issue by flexcodenet** [PrestaShop/PrestaShop#23576]
#### Describe the bug

Navbar menu in back office disappears if other modules in their code have css with class d-none. Layout use bootstrap class, but it is not used in this view. So d-md-block don't work.

#### Expected behavior

If we use class from bootstrap in view, it should be included in the view.

#### Steps to Reproduce

1. Go to Admin DashBoard.
2. Check used class by navbar menu in devtools browser.
3. Check styles in devtools. The classes used do not have their own css code(d-none, d-md-block).

**Screenshots**

![Zrzut ekranu 2021-03-09 110231](https://user-images.githubusercontent.com/47887928/110461590-edbb6900-80cf-11eb-8249-0f205055dfe2.png)
![Zrzut ekranu 2021-03-09 110859](https://user-images.githubusercontent.com/47887928/110461593-ee53ff80-80cf-11eb-895c-d98f334f5aa8.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @flexcodenet 

Could you please **follow the provided template to submit a complete bug report** and provide steps to reproduce the issue.

> Layout use bootstrap class, but it is not used in this view.

Could you please provide more details about your issue, is there any Front-end breaks??
Please check and feedback.

Thanks!

**Comment by flexcodenet** [comment]
#### Describe the bug

Navbar menu in back office disappears if other modules in their code have css with class d-none. Layout use bootstrap class, but it is not used in this view. So d-md-block don't work.

#### Expected behavior

If we use class from bootstrap in view, it should be included in the view.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to Admin DashBoard.
2. Check used class by navbar menu in devtools browser.
3. Check styles in devtools. The classes used do not have their own css code(d-none, d-md-block).
4. See error

**Screenshots**

![Zrzut ekranu 2021-03-09 110231](https://user-images.githubusercontent.com/47887928/110461590-edbb6900-80cf-11eb-8249-0f205055dfe2.png)
![Zrzut ekranu 2021-03-09 110859](https://user-images.githubusercontent.com/47887928/110461593-ee53ff80-80cf-11eb-895c-d98f334f5aa8.png)


#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by flexcodenet** [comment]
> Hello @flexcodenet
> 
> Could you please **follow the provided template to submit a complete bug report** and provide steps to reproduce the issue.
> 
> > Layout use bootstrap class, but it is not used in this view.
> 
> Could you please provide more details about your issue, is there any Front-end breaks??
> Please check and feedback.
> 
> Thanks!

@hibatallahAouadni done

**Comment by flexcodenet** [comment]
> > Hello @flexcodenet
> > Could you please **follow the provided template to submit a complete bug report** and provide steps to reproduce the issue.
> > > Layout use bootstrap class, but it is not used in this view.
> > 
> > 
> > Could you please provide more details about your issue, is there any Front-end breaks??
> > Please check and feedback.
> > Thanks!
> 
> @hibatallahAouadni done

**Comment by flexcodenet** [comment]
> Hello @flexcodenet
> 
> Could you please **follow the provided template to submit a complete bug report** and provide steps to reproduce the issue.
> 
> > Layout use bootstrap class, but it is not used in this view.
> 
> Could you please provide more details about your issue, is there any Front-end breaks??
> Please check and feedback.
> 
> Thanks!

Frontend work correct. Just BO.

**Comment by hibatallahAouadni** [comment]
Hello @flexcodenet 

You said that you encounter the issue with PS1.7.7.2, but your screenshot shows that 1.7.7.1 :wink: 
It seems you have been overrides your dashboard, is that so?
And could you please check this issue #22250 is similar to yours. 

Well, in my case I didn't encounter your issue with 1.7.7.1 and 1.7.7.2, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110469734-4b54b300-80da-11eb-88c6-5eb94173c78f.png)

Please check and feedback.
Thanks!

**Comment by flexcodenet** [comment]
Hello @hibatallahAouadni 
Yes 1.7.7.2, and 1.7.7.1 too. But I reported the problem in the latest version because I think it will be better and it doesn't matter.

#22250 - This is something else, these reports are not helping. I gave an example of the problem from the official demo store.

There is also an error in your screenshot.
As you can see, you have two classes: d-none and d-md-block.

The first and second class should have the css code displayed in the window devtools - styles. And he's not. Css does not appear for these classes.
So if someone creates a module that has a css for the "d-none" class it will hide the menu, because the css code for d-md-block does not work.

**Comment by NeOMakinG** [comment]
Hello @flexcodenet 

Thanks for reporting this issue.

Default theme doesn't have the version of bootstrap compatible with d-none and d-block.

These classes have been introduced in this commit : https://github.com/PrestaShop/PrestaShop/commit/f6a82b28d891a3b0a5330abf30bbb8e567201555#diff-6103fe4110d9b95679ba9804ca33d7151f213547511222816dc5ad3853d4111aR1

I think this is a mistake from a copy paste in the past. We need to remove these classes !

I already provided a PR!

Also, as it's here since 2018, it's not considered as a regression, so we should do it on the develop branch!
