### ISSUE TITLE
Sorting issue on Stock and Movement pages

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#23592]
#### Describe the bug
Sorting alphabetically does not work on `Stock and Movements Pages`.
Please see screenshot:
![Screenshot 2021-03-10 at 10 04 45](https://user-images.githubusercontent.com/30602638/110604770-b8268680-8188-11eb-82db-c32ac3475af0.png)

#### Expected behavior
Compared to the same listing under `Catalog>Products` you can see the sorting for the same product how it's supposed to be:
![Screenshot 2021-03-10 at 10 09 01](https://user-images.githubusercontent.com/30602638/110605205-28cda300-8189-11eb-8f8c-a1794918a27d.png)

If it was not clear: sorting should be: 
A, B, C, Copy of A, Copy of A, Copy of A, Copy of B, Copy of B, Copy of B, Copy of C, Copy of C, Copy of C.

#### Steps to Reproduce

1. Make 3 products: A, B, C.
2. Duplicate all products several times so that you have for example 12 products in total.
3. Sort alphabetically on `Catalog>Products` and see it sorts correctly.
4. Sort alphabetically on `Stock and Movements Pages` and observe it does not sort correcly.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

I don't think that the product list in **Stock and Movements** pages are sorted alphabetically, it seems to me that they're sorted by the products ids. See the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110610538-a0520100-818e-11eb-822d-988f8d3f8a37.png)

---
### Product page sorted by id

![image](https://user-images.githubusercontent.com/23308427/110611127-36862700-818f-11eb-9889-822a800e7240.png)

Could you please check if your products are sorted too by their ids?
Please check and feedback.

Thanks!

**Comment by madsoliver** [comment]
@hibatallahAouadni Please check my screenshots for selected sorting: alphabetically for both of them 👍

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

I manage to reproduce the issue with PS1.7.4.1, PS1.7.6.7, PS1.7.7.2 and develop, see the attached screen record below:

https://drive.google.com/file/d/1hZx5N4CvWHJkF859uwPYBHRWxcX6N5Nq/view

As you can see the filter doesn't sort the products by their names but with their ids :confused: 
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9629
Please follow https://github.com/PrestaShop/PrestaShop/issues/9629
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9629
