### ISSUE TITLE
Login to the BO don't work

### ISSUE THREAD

**Issue by cbatista8a** [PrestaShop/PrestaShop#23596]
don't login with my credentials after clean install and show me only the name of my shop [screenshot](https://drive.google.com/file/d/1W55T44ABSZDpzflFzk4Hp_xvQjeCkRCt/view?usp=sharing).

The Front work normally

Prestashop: 1.7.7.2
PHP: 7.3.24
MySQL: 8.0
Server: Apache

**Comment by hibatallahAouadni** [comment]
Hello @cbatista8a 

I think you may need to reinstall your shop cause it seems you miss something while installing, and check if you encounter any warning or error while installing.

Sorry but I have to close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
