### ISSUE TITLE
404 appears on product img

### ISSUE THREAD

**Issue by chenhaichen1002** [PrestaShop/PrestaShop#23591]
When I upload photos through the background.
Found that the photo shows 404.
His address is wrong, it will be displayed as /.jpg
Can you help confirm or repair
I have tried to clear the cache, but to no avail

![スクリーンショット 2021-03-03 103759](https://user-images.githubusercontent.com/45970452/110574723-08a9de00-81a1-11eb-9df6-8b1352d6a3d5.jpg)

**Comment by chenhaichen1002** [comment]
> When I upload photos through the background.
> Found that the photo shows 404.
> His address is wrong, it will be displayed as /.jpg
> Can you help confirm or repair
> I have tried to clear the cache, but to no avail
> 
> ![スクリーンショット 2021-03-03 103759](https://user-images.githubusercontent.com/45970452/110574505-93d6a400-81a0-11eb-9288-6e7f798df27c.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @chenhaichen1002 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**PS:** Please next time **follow the provided template to submit a complete bug report**. Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
