### ISSUE TITLE
Vatnumber module

### ISSUE THREAD

**Issue by lordchukz** [PrestaShop/PrestaShop#23595]
Hi, 

I know this module has been archived, but still hope I can get support for it.

Needing to exempt vat for European Union customers, I searched the whole web unfortunately not being able to find a configuration solution.

Luckily I came up with the Vatnumber ( https://github.com/PrestaShop/vatnumber ) module but to my disappointment it does not work on my prestashop version.

Actually, when I add an European vat number, the attached error appears blocking the whole process.

Also, if I add the vat number before enabling it, it does not apply the vat expedition from cart total.

All cache are disabled.

1, install module
2, add product to cart
3, fill in delivery address
4, see error/vat exemption does not work.

prestashop version is 1.7.7.1.
PHP version: 7.3.27
Memory limit: 4G

Video link: **https://www.dropbox.com/s/l9qrij1e2108hpk/Screen%20Recording%202021-03-10%20at%2013.40.09.mov?dl=0
**
![Screenshot 2021-03-10 at 13 16 22](https://user-images.githubusercontent.com/36967295/110631788-32fe9a00-81a7-11eb-89f2-51f5036566f0.png)

**Comment by hibatallahAouadni** [comment]
Hello @lordchukz 

I'm really sorry but as you know this module has been archived and it’s no longer maintained :confused: 
But you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

> I know this module has been archived, but still hope I can get support for it.

Sorry again, I cannot provide support. So if you need help, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
