### ISSUE TITLE
BO : AdminCategoriesControllerCore renderList error

### ISSUE THREAD

**Issue by grazius** [PrestaShop/PrestaShop#236]
The call to asort($categories_tree) in this method badly reorder the list.
If the id of a subcategory is less than the parent id, the cat_bar2 is not in the correct order.

Replace asort with natsort to correct this bug.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
