### ISSUE TITLE
BO - Multistore - Merchandise Returns - An exception is displayed when we select a shop 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23609]
#### Describe the bug

Multistore enabled, In the BO > `admin-dev/index.php/sell/customer-service/merchandise-return/` page when we select a shop, an exception is displayed

#### Steps to Reproduce

1. Enable Multistore Context
2. Create a new shop
3. In the BO > Select All shops
4. BO > `admin-dev/index.php/sell/customer-service/merchandise-return/` page (All shops is selected)
5. Enable returns
6. Save
7. Select any shop 
8. See error
![image](https://user-images.githubusercontent.com/16067358/110772393-dad59f80-825b-11eb-8b02-7ef7a832f88c.png)

Reproduced with PS1772 also
Related to this PR: #15022
#### Additional information

* PrestaShop version: PS1772, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional  Could you check this issue ? I didn't reproduce it in `develop` branch.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I did not manage to reproduce the issue with develop branch

https://user-images.githubusercontent.com/16067358/154430574-b0804d57-dd0b-4bed-adbb-7210d0bd498e.mp4

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #25674
