### ISSUE TITLE
Customer can register with invalid email

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#23600]
#### Describe the bug

The registration form allow customer to enter invalid email addresses.
For example, if you try to register using the email `test@email`, it works.

#### Expected behavior

Registration form should display an error message.
A valid email address should be `test@email.com`.

#### Steps to Reproduce

1. Go to account creation form
2. Fill the form using `test@email` as value for the email
3. Submit the form
4. The account is created...

#### Additional information

* PrestaShop version: 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

Could you please check this issue #22131 you may find your answer :wink: 
This issue is a duplicate of #22131. 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22131

**Comment by Seb33300** [comment]
The ticket you linked said it will be fixed in 1.7.7.0 but I am able to reproduce the issue in 1.7.7.1

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

I think you misunderstood, @matks said that:

> As discussed in Slack, I believe 1.7.6.9 behavior is faulty while 1.7.7.0 behavior is correct
> 
> According to https://en.wikipedia.org/wiki/Email_address the email address demo@prestashop is valid. It should not be rejected by PrestaShop.

It doesn't mean that the issue will be fixed with PS1.7.7.0, but it means that's the intended behavior: 

- **demo@prestashop** is a valid mail :wink: 

_PS: please read the comments on that issue to better understand._

Thanks!

**Comment by matks** [comment]
Confirmed. @Seb33300 You can add more validation rules in your shop to reject `test@email` but in the Core we must handle all possible usecases and not restrict usages. So we must accept `test@email`.

**Comment by Seb33300** [comment]
Is there any way to do this without adding an override class?
