### ISSUE TITLE
BO - Merchandise Returns - Cannot save Merchandise return (RMA) options

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23606]
#### Describe the bug

In the BO > Merchandise Returns migrated page, In the `Merchandise return (RMA) options`, we cannot save any option, it is not possible to enable Merchandise return and we can't change the `Time limit of validity` and `Return prefix` values

#### Steps to Reproduce

1. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page
2. In the `Merchandise return (RMA) options` section
3. Try to enable returns
4. Set the `Time limit of validity` and `Return prefix` values
5. Save
6. A green alert is well displayed
7. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page 
8. See error: No option is saved
https://drive.google.com/file/d/1WnWmDEi8HBU7lcgr_7Vo_qDaXRr10rcB/view?usp=sharing

It is ok with the PS1772 migrated page

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by marionf** [comment]
@khouloudbelguith I removed critical as the symfony page is hidden

**Comment by eternoendless** [comment]
To be assigned to @JevgenijVisockij
