### ISSUE TITLE
BO - Merchandise Returns - The help button is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23605]
#### Describe the bug

In the Migrated page `Merchandise Returns`, the help button is NOK
Some errors are displayed in the console
![image](https://user-images.githubusercontent.com/16067358/110769805-e1164c80-8258-11eb-9373-d1594f898fc0.png)

#### Expected behavior

The help modal should be well displayed

#### Steps to Reproduce

1. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page
2. Click on the Help button
3. See errors in the console

Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/15022

#### Additional information

* PrestaShop version: PS1.7.7.2, develop
* PHP version: 7.2

**Comment by WebHelpersPau** [comment]
What about adding https://github.com/padolsey-archive/jquery.fn/blob/master/cross-domain-ajax/jquery.xdomainajax.js to the admin pages in symfony migration ? Would it be allowed ? If not it would be a modification in .htaccess...
