### ISSUE TITLE
reporte de version no compatible

### ISSUE THREAD

**Issue by jose2344** [PrestaShop/PrestaShop#23619]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello,
Please send a complete request in English. English is the norm on GitHub.

Thank you
