### ISSUE TITLE
BO - Multistore - Merchandise Returns - The Multistore block & checkboxes are not displayed when selecting a shop

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23610]
#### Describe the bug

Multistore enabled, In the BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page when we select a shop, The multistore block and checkboxes are not displayed

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/110772979-84b52c00-825c-11eb-9baa-ac681f32c8f5.png)

#### Steps to Reproduce

1. Enable Multistore Context
2. Create a new shop
3. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/
4. Select a shop
5. See error: The multistore block and checkboxes are not displayed

Related to this PR: #15022
**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/110773215-c940c780-825c-11eb-989e-641ec3d80204.png)

#### Additional information

* PrestaShop version: PS1772, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional  Could you check this issue ? I didn't reproduce it in `develop` branch.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I still have the same issue with develop branch
![image](https://user-images.githubusercontent.com/16067358/154434670-db60a75a-41a0-44ba-b88a-d80085e80ce7.png)

Thanks!
