### ISSUE TITLE
"Re-display cart at login" bug in 1.7.7.2

### ISSUE THREAD

**Issue by 4itsoft** [PrestaShop/PrestaShop#23635]
#### Describe the bug
The "Re-display cart at login" option no longer works in 1.7.7.2

#### Expected behavior
The "Re-display cart at login" option works

#### Steps to Reproduce
The steps I reproduced:
1. Clean Prestashop installation 1.7.7.2
2. Activate option in BO
3. Create test account, add product to cart, disconnect and reconnect to account. The basket no longer exists.

**Screenshots**

Fix:

Class/Cart.php

```
    /**
     * Last abandoned Cart.
     *
     * @param int $id_customer Customer ID
     *
     * @return bool|int Last abandoned Cart ID
     *                  false if not found
     */
    public static function lastNoneOrderedCart($id_customer)
    {
        $sql = 'SELECT c.`id_cart`
                FROM ' . _DB_PREFIX_ . 'cart c
                WHERE NOT EXISTS (SELECT 1 FROM ' . _DB_PREFIX_ . 'orders o WHERE o.`id_cart` = c.`id_cart`
                                    AND o.`id_customer` = ' . (int) $id_customer . ')
                AND c.`id_customer` = ' . (int) $id_customer . '
                               ' . Shop::addSqlRestriction(Shop::SHARE_ORDER, 'c') . '
                ORDER BY c.`date_upd` DESC';

        if (!$id_cart = Db::getInstance()->getValue($sql)) {
            return false;
        }

        return (int) $id_cart;
    }
```

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by 4itsoft** [comment]
Fix:

Class/Cart.php

    /**
     * Last abandoned Cart.
     *
     * @param int $id_customer Customer ID
     *
     * @return bool|int Last abandoned Cart ID
     *                  false if not found
     */
    public static function lastNoneOrderedCart($id_customer)
    {
        $sql = 'SELECT c.`id_cart`
                FROM ' . _DB_PREFIX_ . 'cart c
                WHERE NOT EXISTS (SELECT 1 FROM ' . _DB_PREFIX_ . 'orders o WHERE o.`id_cart` = c.`id_cart`
                                    AND o.`id_customer` = ' . (int) $id_customer . ')
                AND c.`id_customer` = ' . (int) $id_customer . '
                               ' . Shop::addSqlRestriction(Shop::SHARE_ORDER, 'c') . '
                ORDER BY c.`date_upd` DESC';

        if (!$id_cart = Db::getInstance()->getValue($sql)) {
            return false;
        }

        return (int) $id_cart;
    }

**Comment by hibatallahAouadni** [comment]
Hello @4itsoft 

I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1gm3bLk0GrA9EYe0dKSdjmCLT5XfXXHss/view

Please check and feedback.

_PS: Please next time, **respect and follow the provided template to submit a complete bug report** (as you can see I just edit your issue description)._

Thanks!

**Comment by andrebritocoelho** [comment]
I'm having the same problem in 1.7.6.5, no cart after client registration, and some times the order process gives a redirection to homepage.

Any help?

**Comment by florine2623** [comment]
Hello,

I also tried in PS 1.7.7.3, I can't reproduce the issue : 
https://drive.google.com/file/d/1xSkkpU5hae_spHc115BgjEng56a5ybII/view
This bug is fixed.

@andrebritocoelho
I reproduced the issue in PS 1.7.6.5, so I suggest upgrading your shop to PS 1.7.7.3 version.

Thanks!
