### ISSUE TITLE
Wrong rewrite url on category page

### ISSUE THREAD

**Issue by Rus-Design** [PrestaShop/PrestaShop#23632]
#### Describe the bug

If I add my text to the link (for example, /test) on the category page, error 404 should appear, but instead the link is overwritten and the product filter is included. nothing is happening on the page at this moment.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to category page and add your text with slash for example /test
2. You can see url rewrite to ?selected_filters=test 
I believe that in this case, error 404 should appear. It is important.

**Screenshots**
First step https://drive.google.com/file/d/1RZG0FIJwg2AO1RuGmLp_CA-y_S3y6QMF/view?usp=sharing
Result https://drive.google.com/file/d/185Nkz7Zt942jXt2zqjvx3BrYJmu2Yi9Y/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Rus-Design 

I didn't manage to reproduce the issue with PS1.7.7.1 and PS1.7.7.2, see the attached screen record below:

https://www.awesomescreenshot.com/video/3057657?key=b1ba88d41fb86ec479a6a933f31e8551

Please check and feedback.
Thanks!

**Comment by Rus-Design** [comment]
> Hello @Rus-Design
> 
> I didn't manage to reproduce the issue with PS1.7.7.1 and PS1.7.7.2, see the attached screen record below:
> 
> https://www.awesomescreenshot.com/video/3057657?key=b1ba88d41fb86ec479a6a933f31e8551
> 
> Please check and feedback.
> Thanks!

Hi @hibatallahAouadni 
you do not need to create a new category.
just look at these links:
https://addons.prestashop.com/en/431-data-migration-backup/test
https://rus-design.com/demo-1-7/en/3-clothes/test

case in file/classes/Dispatcher.php line 136

**Comment by hibatallahAouadni** [comment]
Hello @Rus-Design 

Could you please provide clearer steps to reproduce the issue.
Cause I need to reproduce it on my side not just with your shop :wink: 

Thanks!

**Comment by Rus-Design** [comment]
> Hello @Rus-Design
> 
> Could you please provide clearer steps to reproduce the issue.
> Cause I need to reproduce it on my side not just with your shop 😉
> 
> Thanks!

https://www.awesomescreenshot.com/video/3082967?key=681ed7c9a484d41e16a7c3f72bcf3f23
go to the category page and just add slash and any word to the url

**Comment by hibatallahAouadni** [comment]
Hello @Rus-Design 

Thanks for the clarifications!
I was able to reproduce the issue with PS1.7.4.1, PS1.7.6.7 and PS1.7.7.2. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you
