### ISSUE TITLE
Problem after update ps 1.7.6.8 to 1.7.7.2

### ISSUE THREAD

**Issue by RicRey1988** [PrestaShop/PrestaShop#23637]
#### Describe the bug

after updating prestashop from 1.7.6.8 to 1.7.7.2 it presents me with a bug, in some pages such as orders, modules, performance does not load well so the options cannot be used. "look at attached image"

#### Steps to Reproduce

1) update ps 1.7.6.8 to 1.7.7.2
2) check that it does not load the pages correctly from orders, modules, performance

**Screenshots**

![image](https://user-images.githubusercontent.com/44790517/111083181-36ad5c00-84da-11eb-9f90-90e8bdc65258.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @RicRey1988 

I didn't manage to reproduce your issue, see the attached screen record below:

https://drive.google.com/file/d/1Tlo5TlAucvGjq0cAv2tzCBbBsp5ECI8x/view

Please check and feedback.
Thanks!

**Comment by RicRey1988** [comment]
I discovered the module that produces the error, what version of jquery could I put in it to make it compatible with ps 1.7.7.2?

**Comment by hibatallahAouadni** [comment]
Hello @RicRey1988 

Thanks for your feedback!
> I discovered the module that produces the error, what version of jquery could I put in it to make it compatible with ps 1.7.7.2

Well, you need to contact the module developer and ask about the JQuery version :wink:
I close this issue cause it's not related to PS Core :slightly_smiling_face: 

Thanks!
