### ISSUE TITLE
Error update version Multistore

### ISSUE THREAD

**Issue by 4ngeluxpunk** [PrestaShop/PrestaShop#23639]
Hello good evening, I am having an error when updating a Multistore, I have carried out all the steps to update the main store, it updates me without problems but the virtual store gives me an error: "Trying to get property 'precision' of non-object" the Prestashop version I am using is 1.7.7.1 and PHP 7.2. Greetings.

![Error](https://user-images.githubusercontent.com/22511504/111097842-49428800-8510-11eb-8c26-71a67318cb53.png)

**Comment by hibatallahAouadni** [comment]
Hello @4ngeluxpunk 

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by 4ngeluxpunk** [comment]
@hibatallahAouadni Ok, edited the text to English, please open the topic again. Greetings.

**Comment by hibatallahAouadni** [comment]
Sorry @4ngeluxpunk but you need to edit the issue description **following the provided template to submit a complete bug report**.
