### ISSUE TITLE
1-click update error 1.7.6.x to 1.7.7.x

### ISSUE THREAD

**Issue by iShamsah** [PrestaShop/PrestaShop#23641]
i am running php 7.3 prestashop 1.7.6.9
when i use 1-click upgrade i get a connection timeout while upgrading the database ..
and the upgrade stops ..
and i have to restore the backup ..

how could i fix this issue and upgrade to 1.7.7 .. ??

**Comment by hibatallahAouadni** [comment]
Hello @iShamsah 

You need to downgrade your PHP version to 7.2 cause PrestaShop 1.7.6.9 is not compatible to PHP 7.3 (see our system [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
I close this issue cause it's not a PS Core bug.
Please next time when you create an issue, **respect and follow the provided template to submit a complete bug report**.

Thanks!

**Comment by iShamsah** [comment]
> 
> 
> Hello @iShamsah
> 
> You need to downgrade your PHP version to 7.2 cause PrestaShop 1.7.6.9 is not compatible to PHP 7.3 (see our system [requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
> I close this issue cause it's not a PS Core bug.
> Please next time when you create an issue, **respect and follow the provided template to submit a complete bug report**.
> 
> Thanks!

i have downgraded the php version to 7.2
still having the same issue ..

This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

**Comment by hibatallahAouadni** [comment]
@iShamsah I think you need to contact your host.

**Comment by iShamsah** [comment]
> @iShamsah I think you need to contact your host.

contact my host provider about what .. ??
it’s on a private dedicated server

**Comment by matks** [comment]
@IAmWebSA about this

> This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

**Comment by iShamsah** [comment]
> @IAmWebSA about this
> 
> > This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

php max execution time is set to 3600
even it i increase higher
i get the same error
