### ISSUE TITLE
Wrong sales total in the dashtrends module in back-office

### ISSUE THREAD

**Issue by RHermant** [PrestaShop/PrestaShop#23648]
#### Describe the bug

The sales total does not take in account the discounts, it only uses the products total. So the amount displayed on the back-office is wrong and does not match with the amounts paid (without shipping charges). 

Here it is the query in the file AdminStatsController.php, in the function getTotalSales : 
```
'SELECT LEFT(`invoice_date`, 10) AS date, SUM(total_products / o.conversion_rate) AS sales
FROM `' . _DB_PREFIX_ . 'orders` o
LEFT JOIN `' . _DB_PREFIX_ . 'order_state` os ON o.current_state = os.id_order_state
WHERE `invoice_date` BETWEEN "' . pSQL($date_from) . ' 00:00:00" AND "' . pSQL($date_to) . ' 23:59:59" AND os.logable = 1
' . Shop::addSqlRestriction(false, 'o') . '
GROUP BY LEFT(`invoice_date`, 10)'
```

#### Expected behavior

The module should deduct the discounts from the sales total, by using the total_discounts_tax_excl field for example, to get something like this : 
```
'SELECT LEFT(`invoice_date`, 10) AS date, SUM( ( total_products / o.conversion_rate ) - total_discounts_tax_excl ) AS sales
FROM `' . _DB_PREFIX_ . 'orders` o
LEFT JOIN `' . _DB_PREFIX_ . 'order_state` os ON o.current_state = os.id_order_state
WHERE `invoice_date` BETWEEN "' . pSQL($date_from) . ' 00:00:00" AND "' . pSQL($date_to) . ' 23:59:59" AND os.logable = 1
' . Shop::addSqlRestriction(false, 'o') . '
GROUP BY LEFT(`invoice_date`, 10)'
```

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @RHermant 

Could you please provide steps to reproduce the issue.
Please notify me when you add the steps :wink: 

Thanks!

**Comment by ghost** [comment]
It's possible it's fixed her :

https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+author%3Aokom3pom+label%3Afixed+

I think i update all stats modules

**Comment by ghost** [comment]
Oups not this one

**Comment by hibatallahAouadni** [comment]
Hello @RHermant ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
