### ISSUE TITLE
ps_facetedsearch - BO - an exception is dipslayed when we check update

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23642]
#### Log

- [ ] Investigation to understand where the problem come from
- [ ] Fix it

#### Describe the bug

In the BO > ps_facetedsearch configuration page, when we click to check update => en exception is displayed

#### Expected behavior

Redirection to the module manager page

#### Steps to Reproduce

1. Go to back-office -> Modules -> Module manager and search ps_facetedsearch
2. Click on "Configure"
3. Click on "Check update"
4. Se error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/111127589-4aa59c00-8574-11eb-91c2-2771b2a575ba.png)

It is ok with branch 177x, PS1769

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1
* ps_facetedsearch: v3.6.0, v3.7.0, v3.7.1

**Comment by PierreRambaud** [comment]
It's not related to the faceted search module but to all modules when clicking on this button.
It's related to this pull request #19944
