### ISSUE TITLE
Is there any way to resend new_order mail template ?

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#23655]
Hi,

I need to add a feature to the back office order page, like resend email. 

When I click a button, I need to resend the **new_order** email template to the merchant. Is it possible to do this ?

Can anyone help me to solve this ?

_PS version: 1.7.6.5_

Thanks,
Gaja

**Comment by Hlavtox** [comment]
@Gaja-A Use this: https://github.com/PrestaShop/PrestaShop/issues/14754#issuecomment-623364507

**Comment by Gaja-A** [comment]
@Hlavtox Thanks for your reply. I will try it. 

Is it possible to send a mail to the merchant instead of sending it to the customer ?

**Comment by Hlavtox** [comment]
@Gaja-A Yes, just change $this->context->customer->email after Mail::Send( to 'your@email.com' and are done :)

**Comment by hibatallahAouadni** [comment]
Hello @Gaja-A 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: @Hlavtox thanks for your quick replies and your help :superhero_man: 

Thank you
