### ISSUE TITLE
Improve wording << Install demo products >>

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#23651]
#### Is your feature request related to a problem?

When you install a new shop you can select  << Install demo products >> but it's not only the products it's all demo data ( category, suplier, manufacturer, order  and more ... ) 

The best wording is << Install demo data  >> ?

#### Describe the solution you'd like

Change the wording 

#### Additional context

![install-without-data-min](https://user-images.githubusercontent.com/5064590/111167136-14cadc80-85a1-11eb-9261-33ef10902bfd.png)

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , I think this improvement is kind of a **must have**, wdyt? shall we change the wording?

**Comment by ghost** [comment]
To complete it's for harmonize with : https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/migration/#preparing-the-destination-shop

**Comment by MatShir** [comment]
That makes sense, WDYT @Julievrz ? 😄

**Comment by Julievrz** [comment]
I agree, it does make sense and this will improve the wording consistency. 👍 

We already have an existing string: 'Install demonstration data' in Install.
