### ISSUE TITLE
FO - Shopping cart page & shopping cart-modal - A product with Color combination is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23660]
#### Describe the bug

In the FO > when we add a product with a color combination to the cart, in the shopping cart page & in the shopping cart-modal, this product is not well displayed
![image](https://user-images.githubusercontent.com/16067358/111297384-da6b4900-864d-11eb-90bb-76f19890974d.png)
![image](https://user-images.githubusercontent.com/16067358/111297910-75fcb980-864e-11eb-848d-88ac47b0d2cb.png)

#### Steps to Reproduce

1. Go to FO > Add a product with color combination to the cart
2. The shopping cart-modal is displayed
3. Change the cursor near the color
![image](https://user-images.githubusercontent.com/16067358/111298122-b78d6480-864e-11eb-9760-8ed93c91dbad.png)
5. Click on proceed to checkout
6. Shopping cart page is displayed
7. Change the cursor near the color
8. See error 
![image](https://user-images.githubusercontent.com/16067358/111298241-d0961580-864e-11eb-9c91-23a7f2f39f26.png)

#### Additional information

* PrestaShop version: 1.7.7.x ( 1773)
* PHP version: 7.1
* Shopping cart v2.0.4

**Comment by Progi1984** [comment]
Fixed by #23688
