### ISSUE TITLE
Faceted Search - The price filter is not working when using a non default currency (PEN - S/)

### ISSUE THREAD

**Issue by herneygr11** [PrestaShop/PrestaShop#23676]
#### Describe the bug

When you search for a currency that is not the default, the price filter does not work
example : PEN - S/.

#### Screenshots

PEN symbol if it  #works
![Captura de pantalla de 2021-03-17 08-32-23](https://user-images.githubusercontent.com/51766595/111475717-638c8980-86fb-11eb-9124-f62306087e87.png)

S / symbol does not work
![Captura de pantalla de 2021-03-17 08-28-11](https://user-images.githubusercontent.com/51766595/111475670-55d70400-86fb-11eb-9c0e-2ef413a91172.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* Faceted Search:  3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @herneygr11 

Could you please provide steps to reproduce the issue.

Thanks!

**Comment by herneygr11** [comment]
Hello @hibatallahAouadni 

Yes.

1. Internalization -> Localization
2. Import a localization package (Perú)
3. Currency (Sol Peruano)
4. Check filter

Thanks!

**Comment by florine2623** [comment]
Hi @herneygr11 ,

I can't reproduce your issue using PS 1.7.7.2, module faceted_search v.3.7.1.
![Capture d’écran 2021-03-18 à 09 48 09](https://user-images.githubusercontent.com/16019289/111598007-0e21ac80-87cf-11eb-99fd-efb552c3a6ff.png)

Please check my screen record :
https://drive.google.com/file/d/1i0cXBKAGym1Qcs2wGtdC_MUf-LOsw4gu/view

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
