### ISSUE TITLE
Add GHA Annotations to CI

### ISSUE THREAD

**Issue by ks129** [PrestaShop/PrestaShop#23671]
#### Is your feature request related to a problem?

To make it easier to find out where exactly CI is failing, we should add GitHub Annotations to some CI jobs (PHPStan, ESLint, and maybe more).

#### Describe the solution you'd like

We should add formatters to lint runs and output them using `::error` or `::warning`.

#### Alternatives you've considered

Another solution for this is using matcher, but this is not suggested any more.

**Comment by hibatallahAouadni** [comment]
Hello @ks129 

Thanks for the suggestion, the Developer Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers  , what do you think?

**Comment by matks** [comment]
Hi @ks129 we already have GHA annotations for phpstan and eslint if I am not wrong.

So the only missing GHA annotation would be php-cs-fixer, right ?

But it seems PHP CS Fixer does not have this feature https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5534

**Comment by ks129** [comment]
@matks I don't think PHPStan and ESLint have annotations. I can't find them in workflow command arguments and also if my PR PHPStan failed, then this didn't produce annotations.

**Comment by matks** [comment]
@ks129 Here is an example of PR where PHPStan outputs GHA annotations

https://github.com/PrestaShop/PrestaShop/pull/22547/

![Capture d’écran 2021-03-22 à 13 39 49](https://user-images.githubusercontent.com/3830050/111991026-23bb0d00-8b14-11eb-801c-2192eaf52eae.png)

**Comment by matks** [comment]
Hi @ks129 I'm quite certain that we have GHA annotations for phpstan and eslint 😄  so I close the issue. If however you think I was wrong please tell me, I can reopen the issue.
