### ISSUE TITLE
Products images bug

### ISSUE THREAD

**Issue by ryukuroha** [PrestaShop/PrestaShop#23673]
#### Describe the bug

Heyy well while adding products on prestashop it always ends up not showing in the shop any solutions? tnx!!
ps : i'm sure it's not a network problem
#### Expected behavior

the pics to show up

**Screenshots**
![22](https://user-images.githubusercontent.com/79607558/111461515-85294900-86da-11eb-9a81-e993316ba35d.png)
![eroor1](https://user-images.githubusercontent.com/79607558/111461533-8a869380-86da-11eb-8ac7-ce805391d43a.png)

#### Additional information

* PrestaShop version: 1.7

**Comment by Hlavtox** [comment]
@ryukuroha PS seems to have a problem with generating thumbnails for this image.

- Try to upload the image in different format. 
- Check your error logs. Is there anything?
- Try to go to img/p/XXXXX/ and check if there are all thumbnails generated.
- Try to disable and enable friendly URLs, maybe there is a problem with htaccess file.

**Comment by ryukuroha** [comment]
> @ryukuroha PS seems to have a problem with generating thumbnails for this image.
> 
> * Try to upload the image in different format.
> * Check your error logs. Is there anything?
> * Try to go to img/p/XXXXX/ and check if there are all thumbnails generated.
> * Try to disable and enable friendly URLs, maybe there is a problem with htaccess file.

all 3 first are checked i guess its the thacces file that cause this prob do u have any idea on how to fix it thanks in advance!!!

**Comment by ryukuroha** [comment]
> @ryukuroha PS seems to have a problem with generating thumbnails for this image.
> 
> * Try to upload the image in different format.
> * Check your error logs. Is there anything?
> * Try to go to img/p/XXXXX/ and check if there are all thumbnails generated.
> * Try to disable and enable friendly URLs, maybe there is a problem with htaccess file.

it was really an htaccess file problem it's all solved now thank u so much!!

**Comment by hibatallahAouadni** [comment]
Hello @ryukuroha 

Thanks to @Hlavtox efforts your problem is solved :tada: 
And because it's not a PS Core bug, I close this issue :wink: 

PS: Thank you so much @Hlavtox :superhero: 

Thanks!
