### ISSUE TITLE
The spinner is not displayed on the product quantity field and the thumbnails clicks are not operating

### ISSUE THREAD

**Issue by lyordey** [PrestaShop/PrestaShop#23683]
A javascript error in the theme.js file of the classic theme creates a missfunction of the product quantity spinner and clicks of the thumbnails.

The spinner is not rendered on the product page and the it's not possible to select a picture by clicking on its thumbnail.

PrestaShop version: 1.7.7.2 #

**Comment by florine2623** [comment]
Hello @lyordey ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
