### ISSUE TITLE
Bug Mail Alerts v2.2.2 - Impossible de mettre à jour les paramètres / impossible to update the settings

### ISSUE THREAD

**Issue by AzTeK23** [PrestaShop/PrestaShop#23682]
Bonjour / Hello

**Description du bug - bug description**

Depuis la dernière mise à jour du module "Mail alerts par Prestashop" (v2.2.2), nous obtenons le message "impossible de mettre à jour les paramètres" lors de l'édition d'une page / fiche produit. La désactivation du module suffit à reprendre la main sur les modifications des fiches produits.

La mise à jour des informations s'effectue néanmoins mais pas systématiquement / de manière partielle (en rafraichissant la page). Ex : titre du produit > Oui I Type de  règlement pour les déclinaisons > non

Il semblerait qu'il y ait également un impact sur les informations retournées par le serveur bancaire lors du passage d'une commande (erreur 500 également) mais je n'ai pas encore vérifié (je m'apprête à le faire).

Since the last update of the module "Mail alerts by Prestashop" (v2.2.2), we get the message "impossible to update the settings" when editing a page / product sheet. The deactivation of the module is enough to take control of the modifications of the product sheets.

Informations are updated nevertheless but not systematically or partially (by refreshing the page). Ex: product title > Yes I Settlement type for declinations > no

It seems that there is also an impact on the information returned by the bank server when placing an order (also error 500) but I have not yet checked (I am about to do so).

**Comportement attendu - Expected behavior**

Que ça fonctionne normalement / That it works normally ^

**Messages d'erreurs remontés - Error messages reported**

Method POST - HTTP Status 500 - ProductController :: formAction

Level 		Channel 	Message
INFO		request 	Matched route "admin_product_form"
CRITICAL	        php 	Call to undefined method Language::getLocale()
CRITICAL 	request 	Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getLocale" of class "Language". Did you mean to call "getLocaleByIso"?" at .../dev/modules/ps_emailalerts/ps_emailalerts.php line 552

**Captures d'écran - Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![mail_alerts_bug-screenshot_01](https://user-images.githubusercontent.com/80841356/111506326-cefd4800-8749-11eb-8915-bf2d0260a5c0.jpg)
![mail_alerts_bug-screenshot_02](https://user-images.githubusercontent.com/80841356/111506348-d3c1fc00-8749-11eb-8e94-d7a6c9b58330.jpg)

Informations additionnelles - Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2
* Mail alerts: 2.2.2

Tous les modules sont à jour / all modules are up to date

**Comment by florine2623** [comment]
Hello @AzTeK23 ,

I manage to reproduce your issue in 1.7.5.2 with Mail Alert module V.2.2.2.
![Capture d’écran 2021-03-18 à 11 07 06](https://user-images.githubusercontent.com/16019289/111609975-213a7980-87db-11eb-8cfc-3a5ab46c7aec.png)

But this bug is fixed in 1.7.7.2 as you can see from my screen record :
https://drive.google.com/file/d/1fjOxbRnc3MIkolV52BFVBMxMEk6cSnCi/view

You can update your shop to latest version of PS available.

I'll close your issue as it is fixed.
Thanks!
