### ISSUE TITLE
usage of theme.yml use_parent_assets

### ISSUE THREAD

**Issue by dpodwaln** [PrestaShop/PrestaShop#23686]
#### Describe the bug

It seems to `use_parent_assets: true` in assets section of theme.yml doesn't work at all. \PrestaShop\Core\Addon\Theme\Theme::__construct using array_merge overwrites all parent values and there is not any place in the code where `use_parent_assets` will be checked and implement some action or I'm missing something. 

#### Expected behavior

Using `use_parent_assets: true` in theme.yml loads the parent theme assets.

#### Steps to Reproduce

1. Create child template to parent one with `assets` section including some js or css files.
2. Set `use_parent_assets: true` in `assets` section of theme.yml in child theme (follow the instruction from https://build.prestashop.com/news/Child-Themes-Feature/#set-up)
3. Switch on the new template
4. The assets js and css files from the parent theme will not be loaded as expected.

#### Additional information

* PHP version: 7.0.9
* PrestaShop version: 1.7.6.9

**Comment by florine2623** [comment]
Hello @dpodwaln ,

Thanks for your issue but could you please edit your issue description following the provided template to submit a complete bug report. And please fill in all the blocks.

![Capture d’écran 2021-03-18 à 13 55 32](https://user-images.githubusercontent.com/16019289/111629470-9dd85280-87f1-11eb-8d89-0a796ae947e8.png)

Please edit and notify me.

Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @florine2623 @dpodwaln already edit his issue description :wink: 
So could you please try to reproduce the issue :pray: 

Thanks in advance.

**Comment by florine2623** [comment]
Hello @dpodwaln ,

I created a child template on my test shop. It is working as expected :
![Capture d’écran 2021-03-25 à 16 03 56](https://user-images.githubusercontent.com/16019289/112494937-b7dedb80-8d83-11eb-8d62-bee7b297e98e.png)


The assets from the parent theme are automatically taken into account, the JS and CSS file from the child theme are for overrides.

Am I missing something ?
Do you have any concrete example ?

Thanks

**Comment by dpodwaln** [comment]
Hello @florine2623 ,
please make sure you have the https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/config/theme.yml#L31 line uncommented in you child template and no any additional assets definitions. No any js css files in child one. To get refresh the theme configs you need to clean  /config/themes/[your_theme_folder] folders first.
I hope it helps you to reproduce it.
Thanks

**Comment by florine2623** [comment]
Yes this line is uncommented. My file looks like this :
![Capture d’écran 2021-03-25 à 17 12 39](https://user-images.githubusercontent.com/16019289/112505742-5de31380-8d8d-11eb-90d4-5e6e7e1da026.png)
[theme.yml.zip](https://github.com/PrestaShop/PrestaShop/files/6206205/theme.yml.zip)

No any js css files in child one.
-> I used the classic template from PrestaShop fresh install, no change made on it > created one child theme from it.

To get refresh the theme configs you need to clean /config/themes/[your_theme_folder] folders first.
-> I deleted all folders in /config/themes
deleted cache
hard refreshed my shop
I still see the same display as I mentioned in my previous message.

**Comment by florine2623** [comment]
Hello @dpodwaln ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
