### ISSUE TITLE
BO : Categories unusable with many categories

### ISSUE THREAD

**Issue by grazius** [PrestaShop/PrestaShop#237]
(with more than 4500 categories on 5 level depth)

When updating a position of a category, the entire tree is recalculated by the call of regenerateEntireNtree in processPosition.

The process time of the calculation make the update position unusable.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
