### ISSUE TITLE
Wrong discounts in cart with combinaisons and specific prices

### ISSUE THREAD

**Issue by dirtyFerret** [PrestaShop/PrestaShop#23704]
#### Describe the bug

When a specific price or more apply to combinaisons, combined quantity works fine for displayed prices, but the discount is wrong in the cart.

#### Steps to Reproduce

I made a test with two specifics prices but actually one is enought.

1. Install presta 1.7.7.0
2. Create a product with combinaisons
3. Add two specific prices with min units condition (apply for all combinaisons)
![screen-bug-01](https://user-images.githubusercontent.com/22002647/111800280-157ab000-88cc-11eb-9bec-738f4a6b846c.png)

4. Go to FO product page
5. Add one combinaison to cart, then a different combinaison to cart
6. Go to shopping cart
![screen-bug-02](https://user-images.githubusercontent.com/22002647/111800524-54a90100-88cc-11eb-8a98-4c14ff1cdb1b.png)

7. Set quantity for one article to 2. Displayed price is good for both but the discount won't show up.
![screen-bug-03](https://user-images.githubusercontent.com/22002647/111801339-25df5a80-88cd-11eb-9f9a-8058851c7088.png)

8. Set quantity to 3. Discount is shown but just for one article, even if discount is applied for both
![screen-bug-04](https://user-images.githubusercontent.com/22002647/111801644-6ccd5000-88cd-11eb-907c-a901d3d901c7.png)

9. Set quantity to 3 for the other article. Price for both is still good (6 units so a 20% discount is apply) but only -10% discount is displayed.
![screen-bug-05](https://user-images.githubusercontent.com/22002647/111802115-eebd7900-88cd-11eb-95e0-006c487a2812.png)

10. To have the good discount displayed, you have to set both quantity to 6
![screen-bug-06](https://user-images.githubusercontent.com/22002647/111802287-19a7cd00-88ce-11eb-8e6e-7dcafbbbddff.png)

#### Expected behavior

When combined quantity is 3 (eg 1+2) , reduction shown for both articles should be -10%. Same thing with any other quantity rule like the previous example.

**Comment by florine2623** [comment]
Hello @dirtyFerret ,

It seems like your issue is related to : https://github.com/PrestaShop/PrestaShop/issues/15463 ?
Can you check and feedback ?

Thanks!

**Comment by dirtyFerret** [comment]
@florine2623 Yes indeed ! Seems that this issue haven't been fixed yet..

**Comment by florine2623** [comment]
Duplicate of #15463
