### ISSUE TITLE
Incorrect attribute order

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#23700]
#### Describe the bug

For example if I have a size attribute and I change the order based on the number in an increasing way like 36, 36.5, 37, 37.5, 39, 40 ... this is not maintained but I get 37.5, 36.5, 40, 36, 37, 39...

**Screenshots**
![taglia](https://user-images.githubusercontent.com/11728231/111780688-04c03f00-88b8-11eb-8321-9d17a41a4dec.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27

**Comment by florine2623** [comment]
Hi @kenlog ,
I can't reproduce your issue in PS 1.7.7.2 :
In BO :
![Capture d’écran 2021-03-19 à 14 30 57](https://user-images.githubusercontent.com/16019289/111787925-d6def880-88bf-11eb-8b1e-d7acf91ac86a.png)

In product page front :
![Capture d’écran 2021-03-19 à 14 51 47](https://user-images.githubusercontent.com/16019289/111790600-a8aee800-88c2-11eb-816a-5d0ab65c26c8.png)

In category page front :
![Capture d’écran 2021-03-19 à 14 31 12](https://user-images.githubusercontent.com/16019289/111787959-de060680-88bf-11eb-8f51-b88f927a3b0e.png)

You can change the position of the attributes directly in BO in column Position :
![Capture d’écran 2021-03-19 à 14 53 00](https://user-images.githubusercontent.com/16019289/111790758-d562ff80-88c2-11eb-901a-aaf86fc5023d.png)

**Comment by kenlog** [comment]
Hi @florine2623 I tried on v1.7.7.2 and the problem is not found. I'm updating to the latest version, I'll let you know if the problem is fixed.

**Comment by kenlog** [comment]
I updated to the latest version but found that the bug occurs when the `-` character is present

**Comment by hibatallahAouadni** [comment]
Hello @kenlog 

> I updated to the latest version but found that the bug occurs when the - character is present

So why you closed the issue if you still encounter the issue?

---
EDIT:
I didn't manage to reproduce your issue even when I add the "-", see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/112013231-2de80600-8b2a-11eb-8a1b-5feb863d48e7.png)

Thanks!
