### ISSUE TITLE
Error generating invoice

### ISSUE THREAD

**Issue by maniot** [PrestaShop/PrestaShop#23711]
Ps version 1.7.7.1, When a product has specific price, i'm unable to generate the invoice. Prestashop shows error:
Invalid $number parameter: "" cannot be interpreted as a number [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]

I managed to generate the pdf for this invoice by editing the database ps_order_detail by deleting the discount.
Best regards
Nicolas

**Comment by hibatallahAouadni** [comment]
Hello @maniot 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems that you deleted the currency used in the Order

Thanks!
