### ISSUE TITLE
category api returns name null

### ISSUE THREAD

**Issue by tahsin352** [PrestaShop/PrestaShop#23710]
`/prestashop/api/categories?language=1&output_format=JSON&display=full` gives below
```json
active: "1"
associations: {products: Array(1)}
date_add: "2021-03-17 10:21:48"
date_upd: "2021-03-17 10:21:48"
description: null
id: 4
id_parent: "3"
id_shop_default: "1"
is_root_category: "0"
level_depth: "3"
link_rewrite: null
meta_description: null
meta_keywords: null
meta_title: null
name: null
nb_products_recursive: "1"
position: "0"
```
here name is null. how to fix it?

**Comment by hibatallahAouadni** [comment]
Hello @tahsin352 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by tahsin352** [comment]
@hibatallahAouadni I made the above api request and i found the `name` field is always null. how to fix it?

**Comment by hibatallahAouadni** [comment]
Check this doc https://devdocs.prestashop.com/1.7/webservice/resources/categories/

**Comment by tahsin352** [comment]
@hibatallahAouadni Yes, I have followed those guide exactly. Please see the attached image. I called the categories api, but name, description, link_rewrite are null. how to fix it?
<img width="897" alt="Screen Shot 2021-03-22 at 8 06 05 PM" src="https://user-images.githubusercontent.com/1106654/112002486-22a4d280-8b4a-11eb-9070-ef3e3b5f0437.png">

**Comment by hibatallahAouadni** [comment]
Hello @tahsin352 

I didn't manage to reproduce your issue with PS1.7.7.1 and PS1.7.7.2, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/112161262-4409cb00-8beb-11eb-8821-e466808324ae.png)

As you can see the name is well displayed with all installed languages: 

```
           <name>
                <language id="1" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/1">
                    <![CDATA[Root]]>
                </language>
                <language id="2" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/2">
                    <![CDATA[Racine]]>
                </language>
                <language id="3" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/3">
                    <![CDATA[Root]]>
                </language>
                <language id="4" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/4">
                    <![CDATA[الجذر]]>
                </language>
                <language id="5" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/5">
                    <![CDATA[Kořen]]>
                </language>
                <language id="6" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/6">
                    <![CDATA[Baza]]>
                </language>
                <language id="7" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/7">
                    <![CDATA[Root]]>
                </language>
                <language id="8" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/8">
                    <![CDATA[Raíz]]>
                </language>
                <language id="9" xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/9">
                    <![CDATA[Raíz]]>
                </language>
            </name>
```
Please check and feedback.

Thanks!
