### ISSUE TITLE
PrestaShop validator bug

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#23716]
#### Describe the bug

I get this error in PrestaShop validator:  `Module class must extend one of these classes: Module, PaymentModule, CarrierModule`.

I want to extend to `PrestaShop\Module\SecurityPro\Bootstrap`. Then in my Bootstrap file, I want to extend to Module: `class Bootstrap extends Module{}`.

Here is my file:

```
<?php
/**
 * This file is part of the securitypro package.
 *
 * @author Mathias Reker
 * @copyright Mathias Reker
 * @license Commercial Software License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (!\defined('_PS_VERSION_')) {
    exit;
}

$autoloadPath = _PS_MODULE_DIR_ . 'securitypro/vendor/autoload.php';
if (\file_exists($autoloadPath)) {
    require_once $autoloadPath;
}

class SecurityPro extends PrestaShop\Module\SecurityPro\Bootstrap
{
    public function __construct()
    {
        $this->name = 'securitypro';
        $this->tab = 'administration';
        $this->version = '8.7.10';
        $this->author = 'Mathias Reker';
        $this->module_key = '71a0dda36237f958642fb61a15ccc695';
        $this->need_instance = 1;
        $this->ps_versions_compliancy = [
            'min' => '1.6.1',
            'max' => _PS_VERSION_,
        ];
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Security Pro');
        $this->description = $this->l('This module increases the overall security of your PrestaShop website.');

        $this->confirmUninstall = $this->l('Are you sure you want to uninstall?');
    }
}
```

The problem is that I want my module to be compatible with both PrestaShop 1.6 of PrestaShop 1.7 and I want to use composer and namespaces.

As PrestaShop 1.6 is not compatible with namespaces in the main class, but only in subclasses, I will have to extend the main class into a bootstrap class etc. This design is not compatible with the current ruleset.

#### Expected behaviour

`Module class must extend one of these classes: Module, PaymentModule, CarrierModule`. should be a warning, not an error.

What do you think? As I am about to rewrite my project I want to make sure this is allowed, before spending a lot of time rewriting everything into a new design of subclasses. :-)

**Comment by hibatallahAouadni** [comment]
Hello @MathiasReker 

The Validator is not part of the Open Source Project. It is in no way linked to this repository.

You can contact the Addons team [here](https://addons.prestashop.com/en/contact-us).
You can also contact the Validator team directly through [this email](mailto:validator@prestashop.com).

Thank you for your understanding.
