### ISSUE TITLE
Index controller not being matched in frontend after upgrading from 1.6.x to 1.7.7.2

### ISSUE THREAD

**Issue by logosur** [PrestaShop/PrestaShop#23712]
#### Describe the bug

After an (traumatic) upgrade, all categories and custom friendly urls works fine. All except home page, which throws 404 exception.

After a deep research, I've found that Dispatcher isn't matching the url '/' for his regex ( "regexp" => "#^/$#u" ) within getController() method. In fact this is not that it doesn't match, but that '/' route also matches the route regex for "category_rule" ( regexp" => "#^/(?P<rewrite_category>[_a-zA-Z0-9-\pL]*)$#u" )  which is sorted before the index one in the routes array.

*** See screenshot for current sorted routes array ***

I've fixed it by moving the "custom routes" code within loadRoutes() method before the code for "default routes". This way, the index controller is checked before the categories one.
![bg1](https://user-images.githubusercontent.com/22943974/111874114-f8a9af80-8993-11eb-8d77-9539dc9f741d.jpg)

#### Expected behavior

It should check for a match in the index / homepage route before doing it in the category_rule route regex.

#### Steps to Reproduce

1. Install prestashop 1.6 (any minor version)
2. Upgrade it (if you can) to 1.7.7.2
3. Go to homepage
4. See error 404

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1.3

**Comment by hibatallahAouadni** [comment]
Hello @logosur 

I upgrade my shop from 1.6.1.20 to 1.7.7.2 and I didn't encounter any issue besides this one #23277. 
See the attached screen record below:

https://drive.google.com/file/d/1_Wst2G92nnRen-Or84UCaKqRsHbkE01O/view

Please check and feedback.

_**PS:** are you talking about 1.7.2.2 or 1.7.7.2? :sweat_smile: if it's 1.7.2.2, could you please upgrade to 1.7.7.2 and check if you still encounter the issue._

Thanks!

**Comment by logosur** [comment]
Hi Hibatallah,

Sure, sorry for the typo! it is 1.7.7.2 hehe

I got even more issues, I had, for example to run this SQL before migration:
UPDATE ps_attribute SET color = '' WHERE color IS NULL;

This is because this error during upgrade:
ALTER TABLE ps_attribute CHANGE color color VARCHAR(32) NOT NULL, CHANGE position position INT NOT NULL DEFAULT '0'
`SQLSTATE[01000]: Warning: 1265 Data truncated for column 'color' at row 1" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => """ An exception occurred while executing 'ALTER TABLE ps_attribute CHANGE color color VARCHAR(32) NOT NULL, CHANGE position position INT NOT NULL DEFAULT '0' ':\n \n SQLSTATE[01000]: Warning: 1265 Data truncated for column 'color' at row 1 """]`

And after sucessfully upgrade, I had even 500 error trying to access the location settings in BE, and couln't even load the friendly_url configuration page in backend.

Regarding this 404 error in homepage, could you please go to Dispatcher.php and put a dump($this->routes); at the end of loadRoutes() method ?

This way we could see which order are routes sorted at your end.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @logosur 

Could you please check this issue #11629 you may find some answers.
It seems your issue will be fixed if you execute the command mentioned in this [comment](https://github.com/PrestaShop/PrestaShop/issues/11629#issuecomment-444849864).
Please check and feedback.

Thanks!

**Comment by logosur** [comment]
Hello @hibatallahAouadni,

thank you, yes, you're right, one of my issues is just this one ;)

I'm sorry because I've mixed up some issues in the same comment and it may be confusing.

Regarding this current issue:

_Regarding this 404 error in homepage, could you please go to Dispatcher.php and put a dump($this->routes); at the end of loadRoutes() method ?

This way we could see which order are routes sorted at your end and compare it with the one sorted at my end that I've put in the issue description._

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @logosur 

I upgraded my shop 1.6.1.20 to 1.7.7.2 (with multistore enabled) and the only issue I enounter is #23652
And yes I can't not access to the default shop FO but I can access to the second shop FO.

> _Regarding this 404 error in homepage, could you please go to Dispatcher.php and put a dump($this->routes); at the end of loadRoutes() method ?

Here's my screenshot below:

![image](https://user-images.githubusercontent.com/23308427/112359789-edc38780-8cd1-11eb-8bed-0f880625638e.png)

Please check and feedback.
Thanks!

**Comment by logosur** [comment]
Hello,

Thank you very much for this screenshot. I can see that you even haven't any 'index' route. At my side, if I remove the index route within friendly-url page and even the module routes, it doesn't work too for homepage...
( adminXXX/index.php/configure/shop/seo-urls/ )

Still thinking about it.

![image](https://user-images.githubusercontent.com/22943974/112368826-ca053f00-8cdb-11eb-82b7-43025252a0c3.png)

Regards.

**Comment by logosur** [comment]
Please unfold the first "category_rule" array and take a new screeenshot.
Also it may help if you make another dump($this->routes);  at classes/Dispatcher:1052 line

![image](https://user-images.githubusercontent.com/22943974/112374784-cf19bc80-8ce2-11eb-8609-6ce536895a5f.png)

Just to see the final order and where is finally placed the 'index' route.

**Comment by hibatallahAouadni** [comment]
Hello @logosur 

Thanks for your patience, I just followed your steps and here's the results:

> Please unfold the first "category_rule" array and take a new screeenshot.

![image](https://user-images.githubusercontent.com/23308427/112972981-212e6800-9151-11eb-87b1-8bf64bd6933b.png)

> Also it may help if you make another dump($this->routes); at classes/Dispatcher:1052 line

![image](https://user-images.githubusercontent.com/23308427/112973477-a9147200-9151-11eb-8290-178eb5939499.png)

Please check and feedback.
Thanks!

**Comment by logosur** [comment]
Oh, I can see it clear now. The regex for category is not the same at my end. I've been digging into this and I've found that it came modified from 1.6, so the issue was still present in 1.6 too. So the (wrong) regex that I have, is matching the url / in the categories route too by error, this is because I can't load the homepage.

![image](https://user-images.githubusercontent.com/22943974/113031170-a6843d80-918e-11eb-9a53-888ed9bb0b39.png)

So yes, this is not an 1.7 bug ;)

Thank you for your time!

**Comment by hibatallahAouadni** [comment]
Glad to hear @logosur 
Thanks for your feedback.

I close this issue :wink:
