### ISSUE TITLE
Add checkout message from API

### ISSUE THREAD

**Issue by Vallekano** [PrestaShop/PrestaShop#23718]
#### Describe the bug

I have been creating orders in different Prestashop installations since time ago but now I would like to add a checkout message to the orders and I cannot find the proper way to do this.

After creating the order in the system I am creating a "customer_thread" setting the "id_order" and the "id_customer". After that, I add a message to this thread.

The thread is created properly but I cannot see it from order details page. It still says 0 messages.

If I go to the customer details page, I can see the message there.

#### Expected behavior

I would like to see the message in the order details page, associated with the order.

#### Steps to Reproduce

```
// Create a customer thread setting the order id
var thread = customerThreadFactory.Add(new customer_thread()
{
	id_order = idOrder,
	id_customer = idCustomer,
	id_lang = 1,
	id_contact = 2,
	token = "xxxxxxxx"
});

// Add a message to the thread
var msg = messageCustomerFactory.Add(new customer_message()
{
	message = comments,
	id_customer_thread = thread.id
});
```

**Comment by hibatallahAouadni** [comment]
Hello @Vallekano 

Thanks for your issue!
Could you please provide your PrestaShop version and your PHP version, and maybe clearer steps to reproduce :sweat_smile:  

Thanks!

**Comment by Vallekano** [comment]
Hello @hibatallahAouadni 

Sorry, I will try to explain the issue a more.

The issue is happening in a PrestaShop 1.6.0.5, PHP: 5.6.40-0+deb8u7

I have tested the same code today in a Prestashop 1.7.7.2 PHP: 7.3.5 and it is working fine.

The steps to reproduce the issue are:
1. Create an order in the system
2. Use the API to create a customer thread (customer_threads resource) setting this properties:
        id_order = id order created in point 1,
	id_customer = id customer of the order created in point 1,
	id_lang = 1, -> Spanish
	id_contact = 2, -> A valid contact id
	token = "xxxxxxxx" -> Random string

3. Use the API to create a customer message (customer_messages resource) setting this properties:
        message -> Random message,
        id_customer_thread -> Id of the customer thread created in the point 2

After that, the message does not appears in orders detail page.

Do you think is there any way to make this working in Prestashop 1.6.0.5 / PHP 5.6.40?

**Comment by hibatallahAouadni** [comment]
Hello @Vallekano 

What you're asking for is kind of mission impossible :sweat_smile: 
Searching for the PR fixing the issue from 1.6.0.5 to 1.7.7.2 :sweat: but I did my best and found these tw:
- #3745 - [*]WS: Adding Message to the API
- #7833 - Added message delivery information on checkout process

Hope it helps! Well, I have to close this issue :wink:

_**PS:** it will be better if you upgrade your shop._

Thanks!
