### ISSUE TITLE
BO - Orders page  - Multi-invoice issue - Customized product cannot be added to multi-invoice

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23734]
#### Describe the bug

In the BO >  Order details page, when we have multi-invoices, adding a customized product is NOK.

#### Steps to Reproduce

1. Create an order from BO/FO with a customized product for example "demo_14"
2. Generate an invoice for this order
3. Go to BO > Orders > last order details page
4. Add the same customized product "demo_14" with creating a new invoice
5. See error: the invoice is created with 0 total, the customized product is not added

**Screenshots**

PS1773build1: https://drive.google.com/file/d/1_w37zZ7nJz5GSbqhNsX83ZwZVYqRTf8H/view?usp=sharing
PS1769 => OK: https://drive.google.com/file/d/1eH--nxu2m9csud9NDhgS3i_BrrImWX3n/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, 1773build1
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/23902
