### ISSUE TITLE
Shop logo width and height are not updated

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#23733]
#### Describe the bug

SHOP_LOGO_WIDTH and SHOP_LOGO_HEIGHT configuration vars are set in prestashop install, in web service logo update but not in SF Theme controller.
It was there in AdminThemeController before SF migration.
#### Steps to Reproduce

1. Note SHOP_LOGO_WIDTH  and SHOP_LOGO_HEIGHT in configuration table
2. Go to theme configuration
3. Change shop logo
4. See in base that  SHOP_LOGO_WIDTH  and SHOP_LOGO_HEIGHT are not changed

#### Additional information

* PrestaShop version: 1.7.8 (develop)
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

> Note SHOP_LOGO_WIDTH and SHOP_LOGO_HEIGHT in configuration table

You meant changing these attributes values in the configuration table (in the data base)?
Please check and feedback.

Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni no, I mean, write values on a paper (sorry for my poor english)

**Comment by florine2623** [comment]
Hello @jf-viguier ,

Thanks for the report, I manage to reproduce your issue in develop back to 1.7.6.0. 
This is a regression.
It worked correctly in PS 1.7.5.2 :
Before logo change :
![Capture d’écran 2021-03-25 à 14 25 53](https://user-images.githubusercontent.com/16019289/112481632-806a3200-8d77-11eb-9894-abe7b0364d5e.png)
After the logo change :
![Capture d’écran 2021-03-25 à 14 36 07](https://user-images.githubusercontent.com/16019289/112481658-87914000-8d77-11eb-941b-846abe842778.png)

I will add this to the debug roadmap.
Thanks!

**Comment by marionf** [comment]
Hello @florine2623 @hibatallahAouadni 

It's a regression of the 1.7.6.0 ?

**Comment by jf-viguier** [comment]
@marionf yes

**Comment by Progi1984** [comment]
Fixed by #24017

**Comment by jf-viguier** [comment]
Thanks @atomiix
