### ISSUE TITLE
Contextual information messages in multistore context

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#23739]
Following the [multistore header specifications](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#multistore-header-only-from-178) and the [multistore checkbox specifications](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes), we must add two information messages, that are displayed contextually depending on the user and the context:

Multistore header information message:

> If the shop or the group selected doesn't have yet a color configured, the default color is light grey #EBEBEB.
> In this case, an information message is displayed on the page to prompt the user to define a color with a link opening the store's or group's page edition: "Customize your multistore header, follow the link to pick a color for this shop context" in Admin.Navigation.Header
> The user can close the information message. The message is closed only for the selected context and it will not be redisplayed if the user refreshes or returns to this page later.
> 

Multistore checkbox information message:

> An information message is displayed on all pages where there are checkboxes, to indicate what they are used for.
> The user can close the information message. The message is closed only for the selected context and it will not be redisplayed if the user refresh or return on this page later.
> "If you want to apply specific settings to a store or a group of shops, you need to select the parameter to modify, bring your modifications and then save."
> 
>

**Comment by matks** [comment]
This feature is now scoped for 1.7.9 ?

**Comment by marionf** [comment]
@matks Yes because it's a new feature and 1.7.8 is frozen
