### ISSUE TITLE
Payment method not translated in case of order made from adming page

### ISSUE THREAD

**Issue by dutyhook** [PrestaShop/PrestaShop#23735]
PS 1.7.7.2
PHP 7.1

When order is made by customer, then payment method field gets translated in order conformation e-mail and invoice. If similar order is made from Admin panel and chosen language requires translation, the same field is not translated and also status is not translated (while all the rest is translated and/or correct templates are used):

Example of not translate value: Bank transfer (waiting for validation). At the same time seems, that default notice: Manual order -- Employee: is not translated either, if notice field is used for invoice (as I do)

So, can be that either language or translation is not correctly or is insufficiently defined in some translational php files or in /classes/PaymentModule.php

Currently there is for the field in PaymentModule.php only line:
'{payment}' => Tools::substr($order->payment, 0, 255) . ($order->hasBeenPaid() ? '' : '&nbsp;' . $this->trans('(waiting for validation)', [], 'Emails.Body')),

**Comment by hibatallahAouadni** [comment]
Hello @dutyhook 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
