### ISSUE TITLE
[ps_emailalerts] HTML validator: Nested forms are not allowed

### ISSUE THREAD

**Issue by Peter-Liska** [PrestaShop/PrestaShop#23744]
#### Describe the bug

FO product page contains not valid HTML "error: Nested forms are not allowed"

#### Expected behavior

HTML page should contain valid HTML. It's important for quality and it can make browsers behavior wrong.

#### Steps to Reproduce

It is needed to have ps_emailalerts installed.

1. In module page, turn on the option for customers to get notification for sold out products.

2. Module ps_emailalerts will hook its content to `{block name='product_additional_info'}` in `<div class="product-additional-info">`)

3. Go on FO product page, look at a product which has quantity zero (out of stock !)

3. Analyze the page with [HTML W3 validator](https://validator.w3.org/nu/)
and you can see the **error: Nested forms are not allowed**

#### Solution ?

Maybe this can be solved only in PrestaShop main project by moving `</form>` sooner in `{block name='product_buy'}` in file \themes\classic\templates\catalog\product.tpl

**Comment by hibatallahAouadni** [comment]
Hello @Peter-Liska 

Thanks for your patience :pray: 
Could you please provide your PrestaShop version and ps_emailalerts version.
If you could provide a screenshot, it will be a great :pray: 

Thanks!

**Comment by Peter-Liska** [comment]
In this file:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/product.tpl
is `<form>`
```
<form action="{$urls.pages.cart}" method="post" id="add-to-cart-or-refresh">
...
                  {block name='product_additional_info'}
                    {include file='catalog/_partials/product-additional-info.tpl'}
                  {/block}

                  {* Input to refresh product HTML removed, block kept for compatibility with themes *}
                  {block name='product_refresh'}{/block}
</form>
```
Module ps_emailalerts will hook its content to block "product_additional_info".
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-additional-info.tpl

This is what is hooked:
https://github.com/PrestaShop/ps_emailalerts/blob/dev/views/templates/hook/product.tpl
You can see `<form>` again. 

So there are nested forms. 

You can download latest versions, go to product page with product not in stock, test with validator and you will see the Error.
**Nested forms are not allowed**

**Comment by hibatallahAouadni** [comment]
Hello @Peter-Liska 

> Could you please provide your PrestaShop version and ps_emailalerts version.

I need this informations to reproduce the issue :pray: 

Thanks!

**Comment by Peter-Liska** [comment]
As I wrote (and showed) in a previous comment:
You can download **latest versions**, go to product page with product not in stock, test with validator and you will see the Error.
_**Nested forms are not allowed**_

**Comment by florine2623** [comment]
Hello @Peter-Liska ,

Indeed there are nest forms in the module ps_emailalert.
I'll ping our developers to have their view on that.

Thanks!

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers 

https://github.com/PrestaShop/PrestaShop/issues/23744#issuecomment-833505351
@Peter-Liska has explained that there are nested forms when using module ps_emailalerts.

https://www.w3.org/MarkUp/html3/forms.html
"There can be several forms in a single document, but the FORM element can't be nested"

**Comment by matks** [comment]
I confirm the issue. Indeed ps_emailalerts inserts a `<form>` inside another `<form>` when used on FO product page for a out_of_stock product.

This is a bug that needs to be fixed.

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

This has been done in https://github.com/PrestaShop/ps_emailalerts/pull/86

We can close this issue.

**Comment by hibatallahAouadni** [comment]
@kpodemski Glad to hear :tada: thanks for your PR!
Fixed by https://github.com/PrestaShop/ps_emailalerts/pull/86
