### ISSUE TITLE
[ps_emailalerts] Add ActionProductUpdate hook also to send email

### ISSUE THREAD

**Issue by BlackKerio** [PrestaShop/PrestaShop#23746]
Unfortunately, when you update the product using the API webservice, no mail is sent. Actual hooks are only triggered by a change in BO. I suggest you add Hook ActionProductUpdate.

**Comment by matks** [comment]
Hi @BlackKerio would it be possible to help us reproduce this issue by filling this template? https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md

**Comment by hibatallahAouadni** [comment]
Hello @BlackKerio 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
