### ISSUE TITLE
[ps_emailalerts] specify foreach Merchant Notification an admin mail

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#23745]
Hey,

#### Is your feature request related to a problem?

I've noticed that the module does allow multiple e-mails, but don't let you choose what is sent to each e-mail.
One, or more e-mails for stock and another different one for new orders.
I'm not really into this module but can help with some code if I knew where to edit the files.

#### Describe the solution you'd like

1. Download ps_emailalerts
2. Click on setup
3. If you want to add an administrator to receive all the emails, just duplicate the emails for each field or just use what's already created to leave it.

See attachment to see what we should have.
<img width="886" alt="Screen Shot 2021-03-23 at 22 44 07" src="https://user-images.githubusercontent.com/7015860/112279923-bbd80400-8c84-11eb-98e5-753c08862a51.png">

#### Additional context

* PrestaShop version: 1.7.7.2
* PHP version: 7.2-7.3

Regards

**Comment by matks** [comment]
Hi @ChineseNorris sorry for late answer, can you explain more what you are talking about ? Sending different email for different recipients?

**Comment by ChineseNorris** [comment]
Hi @matks ,

yes, It's very simple, you can't separate the notifications e-mails for their purposes, for instance if you want to send stock emails to something like stocks@domain.com and new orders to new_orders@domain.com, you can't separate the notifications for different persons/teams

**Comment by matks** [comment]
@ChineseNorris Ah, I think I understand.

By "separate" you mean "each of them receive _a different email_" (they are not in CC) ? So it would be "one email per recipient"

While today, it's a single mail with multiple recipients, and consequently each recipient can see other recipients?

**Comment by hibatallahAouadni** [comment]
Hello @ChineseNorris 

I just modified your issue by adding some blocks to fill in, so could you please provide steps to reproduce the issue, your PrestaShop version and your PHP version.

Thanks!

**Comment by ChineseNorris** [comment]
@matks 

By "separate" I mean that for instance warehouse guys should receive stock notifications for re-supply purpose while office team should be receiving the new orders, I think you should be able to separate the e-mail for their specific purpose.

This is great if we are 1 or 2 people team doing everything, but when the e-commerce grows up to 3 or 10 employees it's more difficult to separate the jobs.

**Comment by ChineseNorris** [comment]
> Hello @ChineseNorris
> 
> I just modified your issue by adding some blocks to fill in, so could you please provide steps to reproduce the issue, your PrestaShop version and your PHP version.
> 
> Thanks!

Thank you, I've updated the post with a screenshot where I think you all can relate what I'm talking abut to make things more simpler.

**Comment by hibatallahAouadni** [comment]
Hello @ChineseNorris 

Thanks for your feedback!
So, what you're asking is kind of a new feature :wink: could you please check this issue #22974
It seems similar to yours.
Please check and feedback.

Thanks!

**Comment by ChineseNorris** [comment]
@hibatallahAouadni thanks for the link, I was suggesting that I can help making changes to the module if it's possible but would need a little bit of info to do so and upload the features/improvements. However issue #22974 seems more complicated that what I'm trying to do, because he wants to do it from employee profile instead from the module itself

**Comment by hibatallahAouadni** [comment]
Hello @ChineseNorris 

> I was suggesting that I can help making changes to the module

Of course you can, juste create a Pull Request in this repository [PrestaShop/ps_emailalerts](https://github.com/PrestaShop/ps_emailalerts).

As mush as I understand, you're suggesting to add an email input for every option:

![image](https://user-images.githubusercontent.com/23308427/112344463-66234c00-8cc4-11eb-8e11-343fe31292b8.png)

Please check and feedback.
Thanks!

**Comment by ChineseNorris** [comment]
Hello @hibatallahAouadni 

Yes! That's the idea, how can I help to make this happen?

**Comment by hibatallahAouadni** [comment]
Hello @ChineseNorris 

Thanks for your feedback and your suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , do you think it's a good idea to assign for each option a different email (employee)?

PS: Ping @matks I couldn't find the doc "How to contribute / create a PR", could you please attach the link for @ChineseNorris to create a PR :pray: Thanks in advance.

**Comment by matks** [comment]
> PS: Ping @matks I couldn't find the doc "How to contribute / create a PR", could you please attach the link for @ChineseNorris to create a PR 🙏 Thanks in advance.

https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/

Very happy to see you motivated 😊 @ChineseNorris

**Comment by ChineseNorris** [comment]
Thanks @matks , I'm going to read all the documents before creating a PR pull =)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/ux-team could you please check this improvement :wink: 
I made a modest mockup :sweat_smile: (hope it helps to understand the customer need):

![image](https://user-images.githubusercontent.com/23308427/117242445-91f22f80-ae35-11eb-8868-25c825656c4c.png)

Thanks in advance!

**Comment by prestascott** [comment]
Hello everyone, 

Thanks for your request @ChineseNorris and @hibatallahAouadni for your mockup!

Sorry for the late reply 😅

Adding an input on the right side of the toggle is new for the back office, also this input seems pretty difficult to understand because of a missing label. This mockup makes us not very clear about the purpose of these inputs and this forces users think about what to do.

What I suggest is:

- Only display the input when toggle is enabled
- Placing the input under the toggle (a behavior we already have in the back office)
- Adding a label for the input "Send to:" 
- Being able to select multiple emails in the input
- Being able to remove easily email(s) in the input
- Removing the "Email addresses" input because it will not be useful with those improvements

Here is my design proposition:
![image](https://user-images.githubusercontent.com/54888056/117268386-84e63800-ae57-11eb-9961-f67f5bd0a738.png)

We don't have the input from my mockup yet, but we have [something that looks like it (with search)](https://build.prestashop.com/prestashop-ui-kit/?path=/docs/ps-tags--ps-tags).

Let me know what you think! 🙂

**Comment by hibatallahAouadni** [comment]
@prestascott you're a genius :rocket: :clap:

**Comment by Sybrenb** [comment]
Is it possible to change the e-mail on which the notification arrives after the order when the user chooses to pick up or delivery?

I've downloaded the mail alerts plug-in but I can only add a line of e-mails to where the notifications will send after an order, but I want the system to send an email to (for example) test@test.com when the user chooses to pickup and example@example.com when he chooses for delivery.
<img width="779" alt="Mail alerts" src="https://user-images.githubusercontent.com/21313464/148403681-f53636ef-c323-49b5-b7b8-5b7c18bf7e11.png">
<img width="1247" alt="pickup and delivery" src="https://user-images.githubusercontent.com/21313464/148403708-f866ab7f-5fce-401b-9a88-cc6706f03a72.png">

**Comment by micka-fdz** [comment]
Hi, any news here?

**Comment by marsaldev** [comment]
@micka-fdz I'm on it 👍🏻
