### ISSUE TITLE
[ps_emailalerts] Cannot send test email for layout new_order

### ISSUE THREAD

**Issue by matwong56** [PrestaShop/PrestaShop#23747]
I installed but cannot receive the order notification, after that tried to send test email from email theme, but it doesn't work
got error msg "Cannot send test email for layout new_order"

Any idea what to do?

Thanks!

**Comment by matks** [comment]
Hi @matwong56 would it be possible to help us analyze this issue by filling the template https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md ?

**Comment by hibatallahAouadni** [comment]
Hello @matwong56 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
