### ISSUE TITLE
[ps_emailalerts] Invalid html in hook displayProductAdditionalInfo: form inside form

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#23749]
Hook [displayProductAdditionalInfo](https://github.com/PrestaShop/PrestaShop/blob/441b7e8f87488a2df334ef3213b8441b1d2b8a9d/themes/classic/templates/catalog/_partials/product-additional-info.tpl#L26) is rendered inside form tag [in product.tpl](https://github.com/PrestaShop/PrestaShop/blob/89fc1396b8a972b718146b9b253805de904a91e6/themes/classic/templates/catalog/product.tpl#L96) with the block `{block name='product_additional_info'}`.

By other hand, some modules render forms in this hook like `psgdpr` and [ps_emailalerts in hook/product.tpl](https://github.com/PrestaShop/ps_emailalerts/blob/b8846d40958e0d4f1c979bd08d14f341dd59f542/views/templates/hook/product.tpl#L27) which contains the "form" tag.

The solution is to put the `product_additional_info` block of classic theme out of the `<form id="add-to-cart-or-refresh">`

OR

Fix all modules that add `<form>` to this hook and deny the use of `<form>` inside this hook

To clarify: having forms within forms is not valid html

**Comment by hibatallahAouadni** [comment]
Hello @davidglezz 

Could you please check this issue #22880 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by davidglezz** [comment]
Oops Sorry, I forgot to answer you. The problem is the same. The hook is inside a "form" tag, so modules cannot add form tags to this hook.
I recommend reopening the issue

**Comment by davidglezz** [comment]
https://github.com/PrestaShop/PrestaShop/issues/22880 looks like a duplicate of this issue.

**Comment by hibatallahAouadni** [comment]
Duplicate of #22880
