### ISSUE TITLE
1-Click Upgrade v4.12.0 - Upgrade fail

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#23750]
I'm unable to upgrade from PS 1.7.4.2 to PS1.7.7.2 using 1-Click Upgrade module v4.12.0.

**While running the upgrade, the fist block of the page with upgrade status show:**
   All files upgraded. Now upgrading database...
   Database upgraded.
   Now upgrading your Addons modules...

**But on the second field, at the bottom of the list of updated file i found these error messages:**
Database upgrade OK
Avviso rilevato durante l'aggiornamento.
[INTERNAL] /var/www/vhosts/nomesito.it/httpdocs/override/classes/Cart.php line 0 - Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)
[INTERNAL] /var/www/vhosts/nomesito.it/httpdocs/override/classes/Cart.php line 0 - Declaration of Cart::deleteProduct($id_product, $id_product_attribute = NULL, $id_customization = NULL, $id_address_delivery = 0, $auto_add_cart_rule = false) should be compatible with CartCore::deleteProduct($id_product, $id_product_attribute = 0, $id_customization = 0, $id_address_delivery = 0, bool $preserveGiftsRemoval = true)
[INTERNAL] /var/www/vhosts/nomesito.it/httpdocs/override/classes/Cart.php line 0 - Declaration of Cart::getOrderTotal($with_taxes = true, $type = Cart::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = true) should be compatible with CartCore::getOrderTotal($withTaxes = true, $type = Cart::BOTH, $products = NULL, $id_carrier = NULL, $use_cache = false, bool $keepOrderPrices = false)
[INTERNAL] /var/www/vhosts/nomesito.it/httpdocs/override/classes/Cart.php line 0 - Declaration of Cart::getPackageShippingCost($id_carrier = NULL, $use_tax = true, ?Country $default_country = NULL, $product_list = NULL, $id_zone = NULL) should be compatible with CartCore::getPackageShippingCost($id_carrier = NULL, $use_tax = true, ?Country $default_country = NULL, $product_list = NULL, $id_zone = NULL, bool $keepOrderPrices = false)

**And on the third box with errors wrote in red it show**
errori
SQL 1.7.5.0 1071 in ALTER TABLE `ps_customer` CHANGE `company` `company` VARCHAR(255), CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes
SQL 1.7.5.0 1071 in ALTER TABLE `ps_employee` CHANGE `firstname` `firstname` VARCHAR(255) NOT NULL, CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL, CHANGE `lastname` `lastname` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes
SQL 1.7.7.0 1071 in ALTER TABLE `ps_shop_url` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Specified key was too long; max key length is 767 bytes
SQL 1.7.7.0 1146 in ALTER TABLE `ps_statssearch` CHANGE `keywords` `keywords` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL: Table 'sito_store.ps_statssearch' doesn't exist
[ERROR] PHP 1.7.7.1 /* PHP:ps_1771_update_customer_note(); */
[INTERNAL] /var/www/vhosts/nomesito.it/httpdocs/modules/lgsitemaps/classes/LGTools.php line 0 - Declaration of LGTools::getMediaServer($filename, $id_shop = NULL) must be compatible with ToolsCore::getMediaServer(string $filename): string

**After the upgrade the back office login page show the upgraded version 1.7.7.2, but after login the back office it's not working and show this errore message:**
FatalErrorException
HTTP 500 Internal Server Error
Compile Error: Declaration of LGTools::getMediaServer($filename, $id_shop = NULL) must be compatible with ToolsCore::getMediaServer(string $filename): string

This is what showed with debug mode enabled:
![Immagine 2021-03-24 005855](https://user-images.githubusercontent.com/42684711/112234404-c4a4e780-8c3c-11eb-8613-55021f727aef.png)

#### Steps to Reproduce

Install 1-Click Upgrade v4.12.0 and launch automatic upgrade

#### Additional information

* PrestaShop version: 1.7.4.2
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

I didn't manage to reproduce your issue with PS1.7.4.2 upgrading to 1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1a-NmNAkwtV6ZUVxU91r8_vj95DaOCbAT/view

As you can see, I created two cart rules and two orders with differents currencies and after upgrade, I disabled a one of the currencies and change the order status and I didn't encounter any issue. 
In the other hand, I deleted one of the cart rules whiche is applied to one of the orders and changed the order status, I didn't encounter any issue.
So, could you please specify what you have done to encounter this issue.

> /var/www/vhosts/nomesito.it/httpdocs/override/classes/Cart.php line 0

This error is pointing to some overrides you applied trigger some errors, so please comment all your overrides and check if you still encounter this issue :wink: 
Please check and feedback.

Thanks!

**Comment by matks** [comment]
As @hibatallahAouadni the error clearly indicates in issue in your override `override/classes/Cart.php` .

**Comment by darkf3d3** [comment]
I didn't think it could be caused by that, because override was disable.
I tried removing that file and it started working.

Since I was using a custom module, and it didn't working correctly after upgrade, I went to themplate page and enabled ps classic theme. Then Prestashop showed and error, but I closed by mistake that page without saving a screen, and now both front office and back office show 500 error with no details because debug mode was disabled and I'm no more able to enable it.

I tried remaning the classic template folder to disable it, and also to replace it with the classic theme folder taken from last prestashop version, but with no success.

From server error log I have these:
2021-03-24 12:06:00	Error	500	GET / HTTP/1.1
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: PHP Fatal error: Uncaught Symfony\\Component\\Yaml\\Exception\\ParseException: A YAML file cannot contain tabs as indentation at line 69 (near "\t- ps_shoppingcart"). in /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:202
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: Stack trace:
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #0 /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php(142): Symfony\\Component\\Yaml\\Parser->doParse(Array, 0)
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #1 /var/www/vhosts/miosito.it/httpdocs/src/Core/Addon/Theme/ThemeRepository.php(151): Symfony\\Component\\Yaml\\Parser->parse('parent: classic...')
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #2 /var/www/vhosts/miosito.it/httpdocs/src/Core/Addon/Theme/ThemeRepository.php(66): PrestaShop\\PrestaShop\\Core\\Addon\\Theme\\ThemeRepository->getConfigFromFile('/var/www/vhosts...')
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #3 /var/www/vhosts/miosito.it/httpdocs/classes/shop/Shop.php(491): PrestaShop\\PrestaShop\\Core\\Addon\\Theme\\ThemeRepository->getInstanceByName('dott')
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #4 /var/www/vhosts/miosito.it/httpdocs/classes/shop/Shop.php(133): ShopCore->setTheme()
2021-03-24 12:06:01	Warning		mod_fcgid: stderr: #5 /var/www/vhosts/miosito.it/httpdocs/classes/sho in /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php on line 202

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

> I didn't think it could be caused by that, because override was disable.

That button "Disabled the overrides" is not working #14596, so you should disable all your overriddes manually :confused: 

> Since I was using a custom module, and it didn't working correctly after upgrade, I went to template page and enabled ps classic theme. Then Prestashop showed an error, but I closed by mistake that page without saving a screen, and now both front office and back office show 500 error with no details because debug mode was disabled and I'm no more able to enable it.

Ouch :confounded: I think you messed up and you despertaly need help with your shop that I'm not abled to afford it.
Please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack). You can find some expert contributors that can help you.

Unfortunally, I have to close the issue, I'm really sorry :confused: 

Thank you

**Comment by darkf3d3** [comment]
But the website stopped working after I enabled the classis Prestashop theme. I can also restore the plevious template folder.
There's no way to manually enable debug mode without access to back office? For example from database?

**Comment by darkf3d3** [comment]
I just managed to enable debug mode using config/defines.inc.php, but the error showed are the same of error log:
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: A YAML file cannot contain tabs as indentation at line 69 (near " - ps_shoppingcart"). in /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:202 Stack trace: #0 /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php(142): Symfony\Component\Yaml\Parser->doParse(Array, 0) #1 /var/www/vhosts/miosito.it/httpdocs/src/Core/Addon/Theme/ThemeRepository.php(151): Symfony\Component\Yaml\Parser->parse('parent: classic...') #2 /var/www/vhosts/miosito.it/httpdocs/src/Core/Addon/Theme/ThemeRepository.php(66): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getConfigFromFile('/var/www/vhosts...') #3 /var/www/vhosts/miosito.it/httpdocs/classes/shop/Shop.php(491): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getInstanceByName('dottor') #4 /var/www/vhosts/miosito.it/httpdocs/classes/shop/Shop.php(133): ShopCore->setTheme() #5 /var/www/vhosts/miosito.it/httpdocs/classes/sho in /var/www/vhosts/miosito.it/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php on line 202
