### ISSUE TITLE
BO - Add new Order page - The gift block is not updated when changing the Address - A cart rule "Discount for a carrier selection" is applied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23751]
#### Describe the bug

In the BO => Orders => New Order page, the gift block is not updated when changing the carrier.
Related to this: https://github.com/PrestaShop/PrestaShop/issues/22243

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts page
2. Create a cart rule with a carrier selection "My carrier" with an action "Free gift"
3. Go to BO => Orders => Add new order page for "John Doe"
4. add some product to the order
5. Try to change the carrier from "PrestaShop" pick up in-store" to "My carrier"
6. see error => the discount is applied => but the gift is not added to the cart.
![image](https://user-images.githubusercontent.com/16067358/112287516-bed6f280-8c8c-11eb-8f65-1e7aa3f8bf75.png)
7. If you change the quantity of the first product => ok
![image](https://user-images.githubusercontent.com/16067358/112287643-e037de80-8c8c-11eb-9d6c-ef5d6baa2c21.png)

PS1769 => OK: https://drive.google.com/file/d/1FeQ_yfun74cDfmeqlIlsvG5JuZU7GtEd/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, 1773build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #24015
