### ISSUE TITLE
BO - Cart rules - No alert displayed when enabling/disabling with bulk action without selection

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23755]
#### Describe the bug

In the BO > Catalog > Discounts > Cart rules page => when we try to Enable/Disable with bulk action without selecting one element, the page is just refreshed without alert
#### Expected behavior

An alert should be displayed `You must select at least one element to enable/disable.`

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts > Cart rules page, you have more than 2 cart rules 
2. Click on Bulk actions
3. Click on Enable selection
4. See error: the page is just refreshed without displaying any alert

**Screenshots**

https://drive.google.com/file/d/1oUqRD2PZISOlivtnIEYnqOmxENT4PiCm/view?usp=sharing

#### Additional information

* PrestaShop version: 1773build1, 1769
* PHP version: 7.1

**Comment by ghost** [comment]
Hello @khouloudbelguith 

This issue seems to be fixed

https://www.okom3pom.com/videos/cart-rules-bulk.webm

Regards

**Comment by kpodemski** [comment]
I can confirm this issue is fixed.
