### ISSUE TITLE
BO - Multistore - The trophy of the gamification module is not displayed after enabling multistore

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23754]
#### Describe the bug

AIn the BO > When we enable multishop, the trophy of the gamification module is not displayed

#### Steps to Reproduce

1. Go to BO > General page -> Enable multistore context
2. Select all shops
3. See the error, the trophy of the gamification module is not displayed
![image](https://user-images.githubusercontent.com/16067358/112316174-26039f80-8cab-11eb-86e4-15a1452a7fe5.png)

#### Additional information

* PrestaShop version: 1773build1, PS1769
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi!

This issue is fixed.

Thank you!

**Comment by khouloudbelguith** [comment]
Still reproduced with PS178_rc1
![image](https://user-images.githubusercontent.com/16067358/124470992-9fc42280-dd9c-11eb-97c6-679da0bea147.png)

**Comment by Progi1984** [comment]
@khouloudbelguith Sorry the module `gamification` is now managed by the `PrestaShopCorp` organization. Could you create a new issue on their issues board : https://github.com/PrestaShopCorp/gamification/issues/new ? Thank you for your help.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Done: https://github.com/PrestaShopCorp/gamification/issues/98

Thanks!
