### ISSUE TITLE
As a user, I shouldn't be able to select a shop as default if it doesn't have an URL configured.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23753]
#### Describe the bug

In the BO -> Advanced Parameters -> Multistore page -> when we set a shop (without main URL) as a default shop, then if we disable the multistore, the FO can't be displayed.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > General page & Enable multistore 
2. Go to BO -> Advanced Parameters -> Multistore page 
3. Create a new shop without adding an URL
4. In the AdminShopGroup controller > Multistore Option, select the shop without URL & save
5. Go to BO > Shop Parameters > General page & disable the multistore
6. Click View my shop
7. See error:  FO can't be opened because there is no URL for this shop

#### Screenrecord

https://drive.google.com/file/d/1iGV2jzXKlZSmHeSWsQl2clu4KrhhTNNa/view?usp=sharing

#### Wanted behavior

As a user, I shouldn't be able to select a shop as default if it doesn't have an URL configured.

#### Specs
In the AdminShopGroup controller, if I select a shop as default and if it doesn't have an URL configured, when I click on "Save" an error message is displayed "You must configure the URL of this store before you can set it as default." in _Admin.Advparameters.Notification_ and the shop selected isn't defined as default.

#### Additional information

* PrestaShop version: 1.7.7.3build1, 1769
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @khouloudbelguith 

I was able to reproduce the issue with PS1.7.4.1 and PS1.7.5.1, I can't access to the FO and a lot of BO pages as **Catalog>Attributes&Features**, **Advanced Parameters>Multistore**, ...
Cause, the url is missing and the system call only admin-dev/.... without the domain

Thanks!

**Comment by marionf** [comment]
Hello @khouloudbelguith 

> In the Multistore Option, select the new shop & save

I am not sure to understand what is this step, could you please add a screenrecord of the whole steps ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I attached a screen record
https://drive.google.com/file/d/1iGV2jzXKlZSmHeSWsQl2clu4KrhhTNNa/view?usp=sharing

Thank you!

**Comment by Julievrz** [comment]
Hi @khouloudbelguith, I suggest the following wording:
'You must configure the URL of this store before you can set it as default.' in Admin.Advparameters.Notification
