### ISSUE TITLE
Shipping amount Error when using Currencies

### ISSUE THREAD

**Issue by hugolin69** [PrestaShop/PrestaShop#23768]
#### Describe the bug

When having 2 currencies in a multistore, with a conversion rate for the secondary currency, sometimes, the amount for carrier is incorrect in the ps_orders and ps_orders_carrier table, but is correct in the ps_orders_invoice.

#### Expected behavior

Shipping amount should be the same everywhere, and should be in the currency of the order.

#### Steps to Reproduce

I can not reproduce it.
But here is the result.

Multistore with EUR and GBP, with a rate of 0.9 for GBP.
Default store is EUR only.
Secondary store is EUR +  GBP.
Carrier is 16.6667 (EUR then) to get a 15 GBP amount.
Sometimes, the amount ps_orders and ps_orders_carrier are 16.6667, but it is 15 in ps_orders_invoice. Most of the time it is not.
Seems it did not saw it was with currency, of maybe the format of 0.9 is not recognize, and it use 1.
I look for my module, but can not figure out.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @hugolin69 ,

Following your steps with an order using GBP, I can't reproduce your issue :
![Capture d’écran 2021-03-25 à 09 49 37](https://user-images.githubusercontent.com/16019289/112445548-89470d80-8d4f-11eb-85ed-b34fad983b59.png)
In database :
![Capture d’écran 2021-03-25 à 09 49 46](https://user-images.githubusercontent.com/16019289/112445579-9532cf80-8d4f-11eb-92cf-d194c84a05dc.png)
In Invoice :
![Capture d’écran 2021-03-25 à 09 51 31](https://user-images.githubusercontent.com/16019289/112445764-c7443180-8d4f-11eb-9c76-b7108eb62e81.png)

So I close your issue.
Thanks!

**Comment by hugolin69** [comment]
Hi,
I think I found a first information to reproduce. But I can not always reproduce.
I am in a multistore.
Main shop is EUR only.
Secondary shop is EUR + GBP.

I think the fact that the main shop is only 1 currency, can cause sometimes this problem.
Because when working in All Shops context, it do not find GBP.
Maybe some works made by tiers module could reach a problem with that.

I am not sure, but I think there is something around the fact that the main shop must have all currencies of all shops.
