### ISSUE TITLE
Faceted Search: a heavy SQL query slows down the website

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#23773]
#### Describe the bug
I have the "Faceted Search" (version 3.7.0) module enabled and it seems to slow down the website.
Since there is a lot of data, the execution time is not necessarily surprising. However, every request on the website seems to repeat this SQL query, which with heavy traffic tends to overload the server's CPU.
The module's caching system is enabled, but that doesn't seem to change anything. How can performance be improved?

#### Steps to Reproduce

1. Create 4200 products
2. Each of its products has 24 combinations
3. These products are classified in 176 different categories
4. There is only one shop, one currency and one language.
5. There are 64 features for a total of 5091 feature values.
6. Go to FO
7. When a category loads, it runs a query which is as follows (parameters may change): (see the attached code below)
8. See error > This query has an execution time of 0.7 seconds on my server.

**Screenshots**

```sql
SELECT p.id_product
FROM
  (SELECT p.id_product,
          p.id_manufacturer,
          SUM(sa.quantity) AS quantity,
          p.condition,
          p.weight,
          p.price,
          psales.quantity AS sales,
          cp.position
   FROM dd42_product p
   LEFT JOIN dd42_product_attribute pa ON (p.id_product = pa.id_product)
   LEFT JOIN dd42_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute)
   LEFT JOIN dd42_stock_available sa ON (p.id_product = sa.id_product
                                         AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute
                                         AND sa.id_shop = 1
                                         AND sa.id_shop_group = 0)
   LEFT JOIN dd42_product_sale psales ON (psales.id_product = p.id_product)
   INNER JOIN dd42_category_product cp ON (p.id_product = cp.id_product)
   INNER JOIN dd42_category c ON (cp.id_category = c.id_category
                                  AND c.active=1)
   INNER JOIN dd42_product_shop ps ON (p.id_product = ps.id_product
                                       AND ps.id_shop = 1
                                       AND ps.active = TRUE)
   WHERE p.visibility IN ('both',
                          'catalog')
     AND c.nleft>=246
     AND c.nright<=265
     AND ps.id_shop='1'
   GROUP BY p.id_product) p
INNER JOIN dd42_category_product cp ON (p.id_product = cp.id_product)
GROUP BY p.id_product
ORDER BY p.position ASC,
         p.id_product DESC
LIMIT 0,
      33;
```
(we find the fields loaded in the file `/modules/ps_facetedsearch/src/Adapter/MySQL.php`)

#### Additional information

* PrestaShop version: 1.7.7.0
* Faceted Search version: 3.7.0
* PHP version: N/A

**Comment by florine2623** [comment]
hello @yannicka ,
Your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/19095 ?
Can you confirm ?

Thanks!

**Comment by yannicka** [comment]
My problem is not the same. The problem I mentioned occurs when the product is saved, whereas mine seems to occur when the faceted navigation is generated.

**Comment by hibatallahAouadni** [comment]
Hello @yannicka 

Could you please check this issue #17318, I think the cause of your problem is that the  table `ps_layered_filter_block` is growing fast and you need to add the clear-cache script in a cron (as mentioned in this [comment](https://github.com/PrestaShop/PrestaShop/issues/17318#issuecomment-590389474)).
Please check and feedback.

Thanks!

**Comment by yannicka** [comment]
I already have a clear-cache script in a cron, and it doesn't solve the problem. I'm not sure it's the same issue.

**Comment by hibatallahAouadni** [comment]
Hello @yannicka 

Thanks for your patience :pray: 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is related to #19095 and IMHO I think your issue will be fixed when we fix this one #19095.

So, I will notify the Developer Team about this issue :wink: 

PS: I just update your issue, please check it :wink: and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @yannicka ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by eveneme** [comment]
I have this problem. PrestaShop 1.7.8.7, please repair this module!

**Comment by kellian84** [comment]
Do you have solution?

**Comment by Laimonas-Mituzas** [comment]
> Do you have solution?

In my opinion, solution is too use another module for this function, when a catalog has many products, attributes or combinations.

**Comment by skutovamir** [comment]
I stumbled upon this problem a while ago and again when updating this module. You can read my comment on this query on another issue [#28759](https://github.com/PrestaShop/PrestaShop/issues/28759) or take a look on this [module](https://github.com/skutovamir/ppfacetedsearchoverride).

**Comment by LorenzoMinciotti** [comment]
The problem is when you have a lot of combinations and ps_product_attribute and ps_product_attribute_combination have a lot of rows. To calc product quantity the query joins ps_product_attribute, ps_product_attribute_combination and ps_stock_available, in this way the query slows down. 
Quantity information is not always necessary (eg when stocks are disabled), but seems that is always retrieved. I don't use quantity information, so I found this workaround to remove this join and speed up query, simply remove quantity from select in `PrestaShop\Module\FacetedSearch\Adapter\MySQL`:

```
public function useFiltersAsInitialPopulation()
    {
        $this->setLimit(null);
        $this->setOrderField('');
        $this->setSelectFields(
            [
                'id_product',
                'id_manufacturer',
                // 'quantity',
                'condition',
                'weight',
                'price',
                'sales',
            ]
        );
        $this->initialPopulation = clone $this;
        $this->resetAll();
        $this->addSelectField('id_product');
    }
```

**Comment by revori** [comment]
> The problem is when you have a lot of combinations and ps_product_attribute and ps_product_attribute_combination have a lot of rows. To calc product quantity the query joins ps_product_attribute, ps_product_attribute_combination and ps_stock_available, in this way the query slows down. Quantity information is not always necessary (eg when stocks are disabled), but seems that is always retrieved. I don't use quantity information, so I found this workaround to remove this join and speed up query, simply remove quantity from select in `PrestaShop\Module\FacetedSearch\Adapter\MySQL`:
> 
> ```
> public function useFiltersAsInitialPopulation()
>     {
>         $this->setLimit(null);
>         $this->setOrderField('');
>         $this->setSelectFields(
>             [
>                 'id_product',
>                 'id_manufacturer',
>                 // 'quantity',
>                 'condition',
>                 'weight',
>                 'price',
>                 'sales',
>             ]
>         );
>         $this->initialPopulation = clone $this;
>         $this->resetAll();
>         $this->addSelectField('id_product');
>     }
> ```

Many thanks for the tip. In my case, this has helped a lot. In addition I disabled id_manufacturer, condition and weight since I don't need them.

**Comment by eveneme** [comment]
> The problem is when you have a lot of combinations and ps_product_attribute and ps_product_attribute_combination have a lot of rows. To calc product quantity the query joins ps_product_attribute, ps_product_attribute_combination and ps_stock_available, in this way the query slows down. Quantity information is not always necessary (eg when stocks are disabled), but seems that is always retrieved. I don't use quantity information, so I found this workaround to remove this join and speed up query, simply remove quantity from select in `PrestaShop\Module\FacetedSearch\Adapter\MySQL`:
> 
> ```
> public function useFiltersAsInitialPopulation()
>     {
>         $this->setLimit(null);
>         $this->setOrderField('');
>         $this->setSelectFields(
>             [
>                 'id_product',
>                 'id_manufacturer',
>                 // 'quantity',
>                 'condition',
>                 'weight',
>                 'price',
>                 'sales',
>             ]
>         );
>         $this->initialPopulation = clone $this;
>         $this->resetAll();
>         $this->addSelectField('id_product');
>     }
> ```

Solved my problem. PrestaShop mayby update module?

**Comment by rpereira3** [comment]
> The problem is when you have a lot of combinations and ps_product_attribute and ps_product_attribute_combination have a lot of rows. To calc product quantity the query joins ps_product_attribute, ps_product_attribute_combination and ps_stock_available, in this way the query slows down. Quantity information is not always necessary (eg when stocks are disabled), but seems that is always retrieved. I don't use quantity information, so I found this workaround to remove this join and speed up query, simply remove quantity from select in `PrestaShop\Module\FacetedSearch\Adapter\MySQL`:
> 
> ```
> public function useFiltersAsInitialPopulation()
>     {
>         $this->setLimit(null);
>         $this->setOrderField('');
>         $this->setSelectFields(
>             [
>                 'id_product',
>                 'id_manufacturer',
>                 // 'quantity',
>                 'condition',
>                 'weight',
>                 'price',
>                 'sales',
>             ]
>         );
>         $this->initialPopulation = clone $this;
>         $this->resetAll();
>         $this->addSelectField('id_product');
>     }
> ```

I’m using PrestaShop 8.2.2, and this change fixed the issue for me.

Would it make sense to reopen the issue to work toward a fix ?
