### ISSUE TITLE
I am getting this problem, trying to install it from softaculous. Unable to generate new_cookie_key

### ISSUE THREAD

**Issue by diegodp-zz** [PrestaShop/PrestaShop#23779]
problem - Unable to generate new_cookie_key, hence can not install Prestashop 1.7 
I think is a database problem.. I have already tried to install manually, with no success, because i can't set up database, can't connect. I using hostgator.

**Comment by florine2623** [comment]
Hello @diegodp-zz ,
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
