### ISSUE TITLE
Flashing long messages of different types causes the last type to override the previous ones

### ISSUE THREAD

**Issue by ppisecky** [PrestaShop/PrestaShop#23774]
#### Describe the bug

When trying to flash multiple messages of different types (`error` , `success`) the output of the last message will override the previous message. I have observed this behavior in a custom controller when trying to handle a bulk action. In my scenario the action was applicable to some records but not to others and I wanted to notify the user of the outcome per each selected item. 

#### Expected behavior

The expected behavior is that the text of the messages printed to screen will not overwrite.

#### Steps to Reproduce

By far the easiest way to reproduce this bug is to flash two different types of messages with at least 5 messages/lines per type. For a quick *hacky* way of reproducing:

1. Navigate to `src/PrestaShopBundle/Controller/Admin/Sell/Order/OrdersController.php`
2. Find the `indexAction` around line ~140
3. Add the following snippet to the function body:

```php
for ($i = 0; $i < 6; $i++) {
    $this->addFlash('error', 'Error message');
    $this->addFlash('success', 'Success message');
}
```

4. Navigate to the orders admin index page

**Screenshots**

![image](https://user-images.githubusercontent.com/10659431/112464043-4c851180-8d63-11eb-97ab-0e5eccc230e7.png)

#### Additional information

This is a JavaScript bug - disabling JavaScript in the console prevents the text override from happening.

The flash messages are being rendered using the `alert` macro in `src\PrestaShopBundle\Resources\views\Admin\layout.html.twig`. 

I have tested dumping the contents of the `flashbag` and it is in fact correct. 

The issue likely originates in `admin/themes/new-theme/main.bundle.js`. There is a snippet of code there that introduces the `Read more` button in an attempt to collapse messages longer than 5 lines in a function called `initAlerts`. 

```javascript
// -- snippet --
initAlerts=function(){jQuery(".alert-text").each(function(){var e=jQuery(this),t=e.height(),i=parseFloat(e.css("lineHeight")),n=t/i;if(Math.ceil(n)>5)
// -- snippet --
```

I am not sure where the bundle originates but this should probably be enough information to adjust the implementation so that only the text of the parent alert wrapper is being worked with / modified when collapsing longer messages. 

As a side note it seems like the long message collapse is initially rendered expanded which seems to rather defeat the point of it.

* PrestaShop version: 1.7.7.2
* PHP version: 7.2.11

**Comment by florine2623** [comment]
Hello @ppisecky ,

Thanks for the report.
Let me ping the dev team !
please stay tuned.

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

By adding 
```
for ($i = 0; $i < 6; $i++) {
    $this->addFlash('error', 'Error message');
    $this->addFlash('success', 'Success message');
}
```
only the messages sould be displayed, not the Read More Block.

Can this be changed/overriden in JS files ? If so, how ?

Thanks !

**Comment by ppisecky** [comment]
Just to be clear: I'm not necessarily saying that I wouldn't want the Read More block displayed but with the current implementation:

- [bug] The various message types will have their message contents replaced by each other if they are longer than 5 lines (probably because the core JS is trying to wrap the message text in an element but ends up replacing the text contents of all message elements that are longer than 5 lines)
- Displays the message collapse expanded to begin with which doesn't make sense for 2 reasons: 
1. The "Read more" button will actually close the message collapse rather than expand it (so you actually _Read less_)
2. You're not actually saving any space on the page because you end up seeing more than 5 lines at the page load anyway

But my only real issue is the first [bug] point. The other point about the collapse is just something to consider to make the feature make a little more sense in the context of the UI.

**Comment by matks** [comment]
Hello ! Thanks for the very detailed bug report @ppisecky I think this is a bug as explained.

> Can this be changed/overriden in JS files ? If so, how ?

The function `initAlert()` is being defined in `PrestaShop UI Kit` https://github.com/PrestaShop/prestashop-ui-kit/

We could fix the issue in next version of the UI Kit ping @NeOMakinG 

https://github.com/PrestaShop/prestashop-ui-kit/blob/develop/js/prestashop-ui-kit.js#L82

**Comment by hibatallahAouadni** [comment]
@matks so shall we change the status of this issue to **`To Do`**?

**Comment by NeOMakinG** [comment]
This is definitely a todo, thanks for the report @ppisecky

**Comment by NeOMakinG** [comment]
@ppisecky I fixed it : https://github.com/PrestaShop/prestashop-ui-kit/pull/147

It will be fixed in the next UIKit release :)
