### ISSUE TITLE
Multistore - Issues when a shop without URL is selected as context

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#23785]
#### Describe the bug

Following [the comment](https://github.com/PrestaShop/PrestaShop/pull/23292#issuecomment-808203554) of @Robin-Fischer-PS 

When a store without URL is selected as context the following issues appears:

1) On migrated pages, in the new multistore header, the "Configure URL" link redirects to the listing page with all the shops' URLs instead of redirecting to the shop URL edit page

2) On migrated & legacy pages, the icon of the Gamification module is broken
![pr 23292 broken display no url](https://user-images.githubusercontent.com/55688534/112635804-8d048e00-8e3c-11eb-8b6a-d4b9ef211f53.png)

3) On legacy pages, the multistore dropdown (allowing to select the context) is no longer displayed 

#### Expected behavior

As a merchant I should not be able to select as context a shop without URL defined

**Screenshots**

https://drive.google.com/file/d/1ALc8s3duL-vMPPsIPKzjo6fiNC6pmAiA/view?usp=sharing

#### Specs

https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @marionf,

About the second issue, I created previously an issue: https://github.com/PrestaShop/PrestaShop/issues/23754.
Do I need to close my issue as it will be fixed here?

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I think this issue is related to this ticket: https://github.com/PrestaShop/PrestaShop/issues/23753
What do you think?

Thanks!
