### ISSUE TITLE
Validate::isArrayWithIds method issue

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#23791]
## Describe the bug

The method `Validate::isArrayWithIds` return `true` when array is empty instead of  `false`.

## Expected behavior

The method should return `false` when `$ids` param is empty

## Steps to Reproduce

- Create `issue_23791.php` file in you root dir and put the following code 

```php

<?php 

    require(dirname(__FILE__).'/config/config.inc.php');
    $myEmptyArray = [];
    echo Validate::isArrayWithIds($myEmptyArray); // it will display 1
```
- Call `https://mytesstsite.com/issue_23791.php`

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thanks for your issue and your PR :rocket: 
I reproduced the issue with PS1.7.6.7, PS1.7.7.2 and PS1.7.7.3_build.1. 
I’ll add this to the debug backlog so that it’s fixed.

Thank you
