### ISSUE TITLE
ContextErrorException on 1.7.7.2 with PHP7.3

### ISSUE THREAD

**Issue by cdbrkfxrpt** [PrestaShop/PrestaShop#23796]
Hello,

I'm getting the error "ContextErrorException - Notice: Undefined offset: 1" from a PrestaShop 1.7.7.2 and I believe this is a bug somewhere in the context of PrestaShop - PHP version 7.3 - theme - else. However, I can't figure out exactly what it is / where to look.

The shop was at version 1.7.2.0 on another server with Apache, I migrated it, switched it to nginx and upgraded it to a newer version. Everything seems working, aside from this error which was not present before the version upgrade.

The shop is using a JMS theme, from which I believe the error originates somehow but I'm not sure as I'm not a PrestaShop specialist and as far as I can see there is some overlap between the additional and the built-in theming.

Find attached the debug output from the shop. The shop is available at https://whataeco-backstage.de, which is a migration domain.

Any help is greatly appreciated. 

PrestaShop 1.7.7.2, PHP 7.3, nginx, Ubuntu 20.04 LTS

debug output: [dump.zip](https://github.com/PrestaShop/PrestaShop/files/6214684/dump.zip)

**Comment by hibatallahAouadni** [comment]
Hello @cdbrkfxrpt 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: your issue is related to JMSPageBuilder module, so disable the module and switch to the default theme and check if you still encounter the issue.

![image](https://user-images.githubusercontent.com/23308427/112832955-545ff100-9096-11eb-81bf-1cec8fe91a1f.png)

Thanks!

**Comment by cdbrkfxrpt** [comment]
Hello @hibatallahAouadni,

> Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report.

I didn't use the template since it didn't fit the use case here; it's not a reproducible bug per se. That said, I did provide all the information you're asking in the template, specifically

- a description
- a log
- versions of all setup components

> Read more about how we expect the issues to be handled here. Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

I read that now, not earlier, but I still think that my filing fits the criteria and provides all necessary information. As I've said, "is reproducible" is not a good category in this case; it's a backend bug. Short of setting up the exact same shop and configuration, there is no guarantee it will reproduce.

> your issue is related to JMSPageBuilder module, 

Yes, that is what I said in the original issue.

> so disable the module and switch to the default theme and check if you still encounter the issue.

That is clearly not an option, lest I would have tried that already. The shop is in production and in need of a migration and subsequent update, and if the recommended setup of 1.7.7.2 with PHP7.3 breaks because one the of the more popular themes (potentially) does not support it, that is not going to be possible.

Thanks for your response. I will be reverting the shop and the PHP to the earlier version which is known to be working and abandon the matter.

Cheers
