### ISSUE TITLE
[BO] Link View my shop is not displayed on Symfony pages

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23804]
#### Describe the bug

On Symfony pages, The link `View my Shop` is not displayed

#### Expected behavior

Link is always displayed on BO

#### Steps to Reproduce

1. Go to BO
2. Sign in 
3. Go to a symfony page (Orders for example)
4. See error => NO link on the page

**Screenshots**
![image](https://user-images.githubusercontent.com/48441421/112833807-89b90e80-9097-11eb-9e9c-c5f4c9a3a906.png)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.2

**Comment by Robin-Fischer-PS** [comment]
Probably linked to the merge of https://github.com/PrestaShop/PrestaShop/issues/23292
