### ISSUE TITLE
AdminOrders slow

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#23809]
When I open AdminOrders page and I search for an order or I click on an order, it takes 10 to 20 seconds to load.
It seems to be because it's waiting for AdminStats completely loaded : 
![image](https://user-images.githubusercontent.com/44002621/112871078-2cd14e80-90bf-11eb-8397-675b4ac35fa7.png)

index.php?controller=AdminStats&token=fba97670eaf0edc0c5c2e8dd7950d75a&ajax=1&action=getKpi&kpi=netprofit_visit&rand=1617036350705&_=1617036350548

Can I deactivate these AdminStats ?

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @guigplt 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
