### ISSUE TITLE
Fatal error: Uncaught Error: Class 'AppKernel' not found in /var/www/config/autoload.php:28 Stack trace:

### ISSUE THREAD

**Issue by sextoysunivers** [PrestaShop/PrestaShop#23807]
#### Describe the bug
Hi, After deleting the logo of the site via sftp at the img folder I get this fatal error 👍 
Warning: include(/var/www/vendor/composer/../../app/AppKernel.php): failed to open stream: No such file or directory in /var/www/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/var/www/vendor/composer/../../app/AppKernel.php' for inclusion (include_path='/var/www/vendor/pear/pear_exception:/var/www/vendor/pear/console_getopt:/var/www/vendor/pear/pear-core-minimal/src:/var/www/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/vendor/composer/ClassLoader.php on line 444

**Fatal error: Uncaught Error: Class 'AppKernel' not found in /var/www/config/autoload.php:28 Stack trace: #0 /var/www/config/config.inc.php(35): require_once() #1 /var/www/index.php(27): require('/var/www/config...') #2 {main} thrown in /var/www/config/autoload.php on line 28**

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by sextoysunivers** [comment]
Sorry to have open this issue, the problem was a misplaced file.

I do apologize

Best regards,

**Comment by hibatallahAouadni** [comment]
Hello @sextoysunivers 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

> deleting the logo of the site via sftp at the img folder I get this fatal error

This isn't the safe way to delete or change the logo :wink: if you could try to undo the logo delete, and check if you still encounter the issue

Thanks!

**Comment by sextoysunivers** [comment]
HI hibatallahAouadni,

I recovered the sites but the logo still there. 

If

**Comment by sextoysunivers** [comment]
Thank you
