### ISSUE TITLE
Duplicate address in checkout Address step on address edition

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23808]
#### Describe the bug
In the FO, when we try to change the country of an address, a duplicate address is created instead of updating the selected address

#### Steps to Reproduce

Steps to reproduce the issue:

1. Enable France & United states countries in the BO > International > Location > Countries page
2. Go to FO > Sign in with John Doe
3. Add a product to the cart
4. Click on Proceed to checkout
5. In the Address step: Edit the country from France to "United States"
6. Click "Save"
7. Click on the "Address step" => Duplicated Address

**Screenshots**

https://drive.google.com/file/d/1YwU4rUQaNV3B6qel0Z43SWDS_5Z00uT9/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.2, 1773build1, 1769
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @marionf this issue is created as commented here: https://github.com/PrestaShop/PrestaShop/issues/18072#issuecomment-809510861

Thank you!

**Comment by fedeanimation** [comment]
Hope this issue will be fixed soon. It create a big confusion for the customers

**Comment by DelecroixQuentin** [comment]
Possible fix, change this: 
https://github.com/PrestaShop/PrestaShop/blob/8a745499c50fce465e088d7cd49efe30aae6f779/themes/classic/templates/checkout/_partials/steps/addresses.tpl#L29-L33

to this:
```
<form
      method="POST"
      data-id-address="{$id_address}"
      action="{url entity='order' params=['id_address' => $id_address]}"
      data-refresh-url="{url entity='order' params=['ajax' => 1, 'action' => 'addressForm']}"
    >
```
