### ISSUE TITLE
FO - The search popup don't display completly

### ISSUE THREAD

**Issue by aDamelincourt** [PrestaShop/PrestaShop#23817]
#### Describe the bug

The search result popup, from the front office, is not displayed completely.
The beginning of the popup is hidden under the header-top

#### Expected behavior

See the entire search result

#### Steps to Reproduce

1. Go to front office
2. Click on search zone, tape a search, waiting for result
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/79843007/112985217-33fc6900-9160-11eb-8ec5-e094f1bae5f3.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @aDamelincourt 

Thanks for your issue :clap: 
I reproduced the issue only with develop, see the attached screen record below:

https://www.awesomescreenshot.com/video/3224621?key=597f9ca72e4f39c1aa789cdb9f2154b6

I’ll add this to the debug backlog so that it’s fixed.

Thank you
