### ISSUE TITLE
Get refund amount in order_row detail

### ISSUE THREAD

**Issue by KminekMatej** [PrestaShop/PrestaShop#23814]
#### Is your feature request related to a problem?

I need to see order_rows that has been already refunded from API. Internally, I need this in order to properly recount stock amounts on synchronized system

#### Describe the solution you'd like

In API request for order, in section: associations->order_rows->order_row display also fields:
`product_quantity_in_stock`
`product_quantity_return`
`product_quantity_refunded`
`product_quantity_reinjected`

#### Alternatives you've considered

I guess this update is pretty simple and useful, I didnt even think about any workarounds.

**Comment by hibatallahAouadni** [comment]
Hello @KminekMatej 

Thanks for the suggestion!
Could you please check this feature #23245 seems similar to yours.
Please check and feedback.

Thanks!

**Comment by KminekMatej** [comment]
@hibatallahAouadni I dont think thats related. My issue is solely about API (as my issues usually are). I just need to display some additional fields in XML API response

**Comment by hibatallahAouadni** [comment]
Hello @KminekMatej 

Thanks for your quick feedback!
AFAIK, these fields are provided in the WS Order_details, see this [link](https://devdocs.prestashop.com/1.7/webservice/resources/order_details/):
```
product_quantity_in_stock
product_quantity_return
product_quantity_refunded
product_quantity_reinjected
```
Could you please check and feedback.
Thanks!

**Comment by KminekMatej** [comment]
Thx @hibatallahAouadni , you are right, those neccessary details were there, silly me.

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback and glad that you find what you need 😉
