### ISSUE TITLE
ps_facetedsearch sub-categories filter doesn't work if category name contains slash or hyphen

### ISSUE THREAD

**Issue by KristianFilo** [PrestaShop/PrestaShop#23815]
#### Important update

Turned out it is not as random as I thought. The category filter simply does not work, if category name contains some special characters (e.g. slash or hyphen). See [this comment](https://github.com/PrestaShop/PrestaShop/issues/23815#issuecomment-814781805) for more information.

#### Describe the bug

I have many categories, all of them are enabled, contain various active products, are enabled in Faceted Search and everything really seem to be the same. However, some categories can be selected (using checkboxes) as active filters, some can not.

#### Expected behavior

All enabled categories should work the same way.

#### Steps to Reproduce

As this seems to be really random, I can't describe the steps to reproduce the issue.

**Screenshots**

In the video example I am trying to check all 8 available sub-categories, but only 4 of them are added to active filters. They are all the same, all of them contain active products. I am also attaching the screenshots of ps_facetedsearch settings.

#### Additional information

* PrestaShop version: 1.7.5.0
* PHP version: 7.2
* Module version: 3.7.1

* https://user-images.githubusercontent.com/18458128/112974221-833b9d00-9152-11eb-863e-3c657b8b120b.mp4
* ![presta_facet_category_list](https://user-images.githubusercontent.com/18458128/112974792-255b8500-9153-11eb-8aa2-0e0f8ac003a3.jpg)
* ![presta_facet_global_config](https://user-images.githubusercontent.com/18458128/112974794-25f41b80-9153-11eb-8b96-20ea65ba1da4.jpg)
* ![presta_facet_category_settings](https://user-images.githubusercontent.com/18458128/112974795-25f41b80-9153-11eb-9e13-a5174a0c1498.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @TinoArts 

> As this seems to be really random, I can't describe the steps to reproduce the issue.

Could you please try to provide steps to reproduce even it seems random.
And could you please switch your theme to the default one and check if you still encounter the issue.

Please check and feedback.

Thanks!

**Comment by ghost** [comment]
I had such a problem with categories where all products where imported using files.
Try to manually add one product in a category which not work with faceted search. 
Then refresh (ctrl-F5) front office, and try again. 
Then the category probably appears.
If not, try to reindex.

**Comment by KristianFilo** [comment]
@jemm971 Didn't work, I've added a test product, the number of products in faceted filter got increased, but I still couldn't activate the filter. Rebuilding the index didn't work either. Thank you anyway.

**However I believe I found the problem. It does NOT work, if category name contains characters like "/" (slash) or "-" (hyphen).**

To reproduce:

1. I click on category "G36 / G3" filter, preloaders shows for a split second, nothing happens
2. If I rename the category to "G36 G3" (removed slash), it works well
3. If I rename the category back to "G36 / G3", or "G36 - G3", it doesn't work

At this point I am not sure whether this is a bug on module's side, or on my side though.

This is the `q` parameter the module is trying to add when I click 'G36 / G3' category:
`?q=Categories-G36+%5C/+G3`

I've tried escaping the slash as `%2F` and/or escaping spaces with `%20`. As a result I've tried these URL queries:
`?q=Categories-G36+%2F+G3`
`?q=Categories-G36%20%2F%20G3`
`?q=Categories-G36+%20+%2F+%20+G3`

But no luck.

If I change the category name to 'G36 G3', the `q` parameter looks like this:
`?q=Categories-G36+G3`

and everything works well.

**Comment by florine2623** [comment]
Hello @TinoArts ,

I can't reproduce your issue in PS 1.7.73 with module Faceted Search v3.7.0 :
![Capture d’écran 2021-04-09 à 15 16 30](https://user-images.githubusercontent.com/16019289/114185944-931f6200-9946-11eb-8574-4cdd4a1538e6.png)

All the categories show :
![Capture d’écran 2021-04-09 à 15 11 25](https://user-images.githubusercontent.com/16019289/114185903-8733a000-9946-11eb-8dc5-4ec9438c827e.png)
The categories should have products in.

Thanks!

**Comment by KristianFilo** [comment]
Hello @florine2623 ,

are you able to actually activate the "G36 / G3" category filter by clicking on it? You should then see only the products from that category.

If that works on your side, could you post the `q` URL params when the filter is active?

Thank you.

**Comment by florine2623** [comment]
Hello @TinoArts ,

Yes, please check my screen record : https://drive.google.com/file/d/1lr8g10QxHS43eZKaEFsQmjM-NUHiqWhI/view 
![Capture d’écran 2021-04-14 à 16 57 08](https://user-images.githubusercontent.com/16019289/114731994-761dd100-9d42-11eb-8ad3-20befa9a629f.png)
Here it is : q=Size-L

**Comment by KristianFilo** [comment]
Hello @florine2623 ,

thank you very much for your time. It seems like your category filter is not set to checkbox type - when you clicked on "G4 - G5" category, it didn't set an active filter for that category, instead it redirected you to a category page and then you set the dynamic filter for the L size. Hence the `q=Size-L` parameter in your URL.

What I need is to set the categories to be an `AND` type checkbox type filters in Faceted Search. With that use case you should be able to check both size `L` and `G4 - G5` as checkboxes and they both should appear in your active filters and in `q` parameter of your URL.

**Comment by florine2623** [comment]
Hello @TinoArts ,

That's already the case as you can see from my screenshots :
![Capture d’écran 2021-04-16 à 11 44 38](https://user-images.githubusercontent.com/16019289/115006442-2dccf300-9ea9-11eb-90a4-acc2e6734c91.png)
![Capture d’écran 2021-04-16 à 11 44 23](https://user-images.githubusercontent.com/16019289/115006450-30c7e380-9ea9-11eb-8515-9ce77bfa0753.png)

Here the URL : `q=Categories-G4+%5C-+G5/Size-L`

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

As I am unable to reproduce your issue, I will close your issue.
Thanks!

**Comment by KristianFilo** [comment]
@florine2623 Hi, could you please try again with `slash` instead of `hyphen` ? Turned out hyphen works for me as well, it is apparently only slash that is causing such issues.

Category name to try: `G36 / G3`

Thank you very much.
