### ISSUE TITLE
Front Office - Multistore in PS 1.7.6.8 - attribute doesn't change and goes back to default

### ISSUE THREAD

**Issue by oubihis** [PrestaShop/PrestaShop#23826]
#### Describe the bug

I have this problem in PS. 1.7.6.8  - Multistore, when I choose an attribute for the first time I get this URL (2-1218-demo-product.html#/84-demo_1-3) like ({category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html).

my Qs is why I get this ( #/84-demo_1-3 ) in my URL?
and When I change the attribute for the second time, the attribute doesn't change and goes back to default (2-1216-demo-product.html#/82-demo_1-1)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* Multistore

**Comment by florine2623** [comment]
Hello @oubihis ,

 #/84-demo_1-3 is the combination of the product.

When you change your attribute the second time, the combination changes to : /82-demo_1-1.
82 is the ID
demo is the name of your attribute
1-1 is the value of the attribute

Please see my screen record :
https://drive.google.com/file/d/1PNscP1yto1QkI0EkPnqsgqesy8-EP4nF/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
