### ISSUE TITLE
BO - Multistore - Orders - Cannot increase the quantity product when Allow ordering out of stock is enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23824]
#### Describe the bug

"Share available quantities to sell" option is enabled, "All shops" is selected, "Allow ordering" out of stock is enabled, in the BO > Orders > Order page > when we try to update the product quantity > quantity total => the save button is disabled

#### Expected behavior

 "Allow ordering" out of stock is enabled, we can increase the quantity > quantity total

#### Steps to Reproduce

1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
![image](https://user-images.githubusercontent.com/16067358/98949230-b957e780-24f7-11eb-895a-5f53c37e7085.png)
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
![image](https://user-images.githubusercontent.com/16067358/98949184-a9400800-24f7-11eb-96b9-b3ac63e8c1e4.png)
5. Create a `productA` in all shops 
6. Quantity of the `productA` in the shopA = 12
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
![image](https://user-images.githubusercontent.com/16067358/98950543-6da63d80-24f9-11eb-991b-4667e76042b0.png)
11. Go to BO > Shop Parameters > Product Settings > All shops selected > Enable `Allow ordering of out-of-stock products` 
12. Go Back to the Order => last order created => All shops selected
12. Try to increase the quantity > 12 => you can not save 
![image](https://user-images.githubusercontent.com/16067358/113013298-e2fa6e00-917b-11eb-935a-ca715acf18fe.png)

When ShopA is selected => ok

PS1769 => ok
https://drive.google.com/file/d/15agdzPj6QqeCW197ieE5mHkHrl0GDlP8/view?usp=sharing
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.1

**Comment by atomiix** [comment]
@khouloudbelguith I think it depends on the order you perform all these operations. I've been able to reproduce the "bug" but that was because in "All shops" context, the `Behavior when out of stock` was set to `Deny orders`. As soon as I changed it to `Use default behavior` it worked. Can you check if it's the same on your side?

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Yes, you are right.
I changed the behavior
![image](https://user-images.githubusercontent.com/16067358/114836974-7e721c80-9dd3-11eb-96c4-3a913c63a0c6.png)
![image](https://user-images.githubusercontent.com/16067358/114837383-ede80c00-9dd3-11eb-9110-9835c5ff7149.png)

So, it is not an issue.
I will close the issue.

Thanks!
