### ISSUE TITLE
PrestaShop Metrics Jquery issue on 1.7.7.2

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#23822]
Hello 

I installed the module PrestaShop Metrics on a fresh PS version 1.7.7.2 and I configured it but the i'm getting a jquery message in console  

https://pastebin.com/k9T0tm6Y

Explain what you expected to happen instead.

**Screenshots**

![image](https://user-images.githubusercontent.com/11594433/113011627-e25cda00-9171-11eb-997d-55a84d8511d6.png)

* PrestaShop version: 1.7.7.2
* PHP version:  7.2.34

Regards

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

the PrestaShop Metrics is part of the PrestaShop company (not PrestaShop the software), which operates the Addons Marketplace. This is not linked in any way with this repository.
You can contact the team responsible for Addons [here](https://addons.prestashop.com/fr/contactez-nous).

Thank you.
