### ISSUE TITLE
Credit invoice different from invoice

### ISSUE THREAD

**Issue by dutyhook** [PrestaShop/PrestaShop#23821]
Conditions:
A. use rounding method: Round on the total, 
B. use taxation for products vat added some % (in my case 20%)
C. set product prices so, that price with or without the tax is not round-able to cent precision (in my case price with vat is set as 0.04 EUR, without VAT it is 0.03333...)

For creating the bug:
1. Create order for customer (where taxation is applied in status where invoice is generated.
2. Add some hundred products to the order
3. Add taxable shipping to the order
4. Create credit note for customer with all the products and max shipping
5. Compare invoice and credit note

EXPECTED is that all sums are matching and credit note is negative replica of invoice. Expected is that whatever rounding method is used, then the same method is used for credit note calculation.

ERROR:
Sums in credit note do not match the invoice and also do not match taxation.
Invoice:
![pilt](https://user-images.githubusercontent.com/15160522/113007735-24d8e380-917f-11eb-8357-27bafd26d71e.png)
Credit note:
![pilt](https://user-images.githubusercontent.com/15160522/113007907-489c2980-917f-11eb-8328-229a36bc6bae.png)

As you can see, different are:
1. product line sum in product list
2. products tax calculated in taxation tab
3. Total (tax excl.) in summary
4. Total tax in summary

Also, if product price set 0.03 EUR without VAT the total is different also:
Invoice:
![pilt](https://user-images.githubusercontent.com/15160522/113009764-ec3a0980-9180-11eb-8e6a-896434fb124b.png)
Credit note:
![pilt](https://user-images.githubusercontent.com/15160522/113009856-01af3380-9181-11eb-9e7b-133b7a06c0f6.png)

This is serious issue, as well for customers trust as well for taxation authorities!

#### Additional information
* Fresh prestashop installation without any additional modules or modifications
* PrestaShop version: 1.7.7.2
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @dutyhook 

I just followed your steps and here's the results:

### The Invoice:

![image](https://user-images.githubusercontent.com/23308427/113029741-172a5a80-918d-11eb-8435-0f1157b41c7d.png)

### The credit slip:

![image](https://user-images.githubusercontent.com/23308427/113029756-1b567800-918d-11eb-82e5-5eea07f13d28.png)

The only diffrence I could see is the **Total tax** in the summary:

- In the invoice: Total Tax = 14.73
- In the credit slip: Total Tax = 21.40

Could you please confirm that this is the issue, if so, I manage to reproduce even with PS1.7.6.7.
Please check and feedback.

Thanks!

**Comment by dutyhook** [comment]
Thank you for confirming - this is one of the issues. 
In my live site and development site there are more differences. 
So, I wanted to check it and made fresh pure installation of PS 1.7.7.2. 
All the images are posted from this fresh and pure installation. 

So, whatever you are able to reproduce or not, they are still there. 
As this credit slip errors are really erratic, I am sure you will find more if you do more tests. 
Also, I have not tested all the rest of rounding options and how credit slip will behave in these situations. 

Hopefully there is somebody who knows the architecture and can evaluate quickly what needs to be done for keeping invoicing and credit slip generation as single two sided system reflecting the rounding options in one way.

**Comment by hibatallahAouadni** [comment]
Hello @dutyhook 

Could you please check this issue #16879 and this one #9779 too.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @dutyhook ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
