### ISSUE TITLE
Error upgrading Prestashop 1.7.5.2 to 1.7.7.3

### ISSUE THREAD

**Issue by estenolotienenadie** [PrestaShop/PrestaShop#23833]
#### Describe the bug
Hello, I am trying to update prestashop 1.7.5.2 to 1.7.7.3 through 1 click upgrade and it is not possible, the process begins but for some reason it does not advance and it stays in the same place.

![UPGRADE ](https://user-images.githubusercontent.com/64229330/113115785-146f4a00-920d-11eb-9fdd-b57a4dcbe31a.png)

![upgrade 1](https://user-images.githubusercontent.com/64229330/113115808-1933fe00-920d-11eb-97b2-af26de2eb81c.png)

A clear and concise description of what went wrong.
As you can see in the images, the last thing that happens is this:

img/admin/add_stock.png added to archive. 57575 files left.

Then nothing happens and therefore the update does not finish.

#### Expected behavior
The update is supposed to continue and not progress

Explain what you expected to happen instead.

the update must continue to finish and this does not happen

#### Steps to Reproduce

1. Go to '...'1-Click Upgrade
2. Click on '....'put shop in maintenance mode
3. Scroll down to '....' the blue bottom UPGRADE PRESTASHOP NOW!
4. LAST PROGRESS IS JUST img/admin/add_stock.png added to archive. 57575 files left.

**Screenshots**

![UPGRADE ](https://user-images.githubusercontent.com/64229330/113118078-674a0100-920f-11eb-897e-95914b0c581e.png)

![upgrade 1](https://user-images.githubusercontent.com/64229330/113118206-88125680-920f-11eb-9dff-106893b58528.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @estenolotienenadie ,

Is there any error ?
Can you share the error + error log ?
Did you refresh your page ?

Thanks!

**Comment by estenolotienenadie** [comment]
Hello.
The error is precisely that nothing happens, the update does not advance.
The error is precisely that nothing happens, the update does not progress.
I have tried to do the update many times and it always stays there
img/admin/add_stock.png added to archive. 57575 files left.

**Comment by estenolotienenadie** [comment]
If you need any other information let me know becouse i dont know how to send you the error log, but if you tell me how i will do it.
Regards,
Alberto.

**Comment by hibatallahAouadni** [comment]
Hello @estenolotienenadie 

I upgraded my shop from 1.7.5.2 to 1.7.7.3 without any problem. Could you please click on the button refresh before upgrading, cause in your screenshot it seems your shop can't find the latest available version:

![image](https://user-images.githubusercontent.com/23308427/113272131-99289980-92db-11eb-8749-eab4acac9f20.png)

Please check and feedback.
Thanks!

**Comment by estenolotienenadie** [comment]
Hello, thanks for your email.
My prestashop is in Spnish and i dont have this button refresh,  in my spanish version apear like this:

![no disponible](https://user-images.githubusercontent.com/64229330/113274392-f02f6e00-92dd-11eb-98dc-9abd241ddf15.png)


check if a new version is available and it still looks like no version is available. You can see at the time i do click to check it, was just now now.
Please In this case what should i do?
Regards,
Alberto.

**Comment by estenolotienenadie** [comment]
I have clicked refresh the page as you can see the time and it still shows that there is no update available.

![Sin título](https://user-images.githubusercontent.com/64229330/113276701-63d27a80-92e0-11eb-8c22-1abccbe04d17.png)

Regards,
Alberto.

**Comment by estenolotienenadie** [comment]
I have clicked refresh the page as you can see the time and it still shows that there is no update available

![Sin título](https://user-images.githubusercontent.com/64229330/113277311-e2c7b300-92e0-11eb-9ac8-df127f8cd413.png)

**Comment by estenolotienenadie** [comment]
Hello, when i do click in ... Refresh page .... apear this:

The status has been successfully updated.

![Sin título](https://user-images.githubusercontent.com/64229330/113280632-d47b9600-92e4-11eb-888e-601ca55903f4.png)

But still not update available.
Thank you.
Regards,
Alberto.

**Comment by estenolotienenadie** [comment]
When i do click in ... Refresh page.... apear :  The status has been successfully updated....  but still not update available.

![Sin título](https://user-images.githubusercontent.com/64229330/113280929-3d630e00-92e5-11eb-895b-32763ac0d4a3.png)

Regards,
Alberto.

**Comment by florine2623** [comment]
Hello @estenolotienenadie ,
What is the version of 1-click upgrade tou are using ? I'm using v4.12.0
In Spanish, I have the refresh button :
![Capture d’écran 2021-04-02 à 11 58 11](https://user-images.githubusercontent.com/16019289/113405822-bbd5b380-93aa-11eb-8a84-e65336ef6c6a.png)

**Comment by estenolotienenadie** [comment]
Hello, I had already found it, look at the image and you will see that the Refresh page button appears but still apear..... 

Latest official version for directory channel.: No disponible

![Sin título](https://user-images.githubusercontent.com/64229330/113407624-f4c35780-93ad-11eb-9946-c1db6794d165.png)

I have already refreshed the page and you can see the date and time that I have done it and it still shows that there is no update available.
The problem I have is not that it shows the refresh button or not, the problem is that I refresh the page and it still tells me that there is no update available, it cannot find the update.
Regards,
Alberto

**Comment by florine2623** [comment]
You can choose the local archive option and add the ZIP of PS 1.7.7.3 in admin/autoupgrade/download :
![Capture d’écran 2021-04-02 à 15 10 53](https://user-images.githubusercontent.com/16019289/113418398-b3d73d00-93c5-11eb-8c61-e8dff397e03d.png)
Add the zip file :
![Capture d’écran 2021-04-02 à 15 13 53](https://user-images.githubusercontent.com/16019289/113418566-0add1200-93c6-11eb-8315-ae8e32fabbb6.png)

**Comment by estenolotienenadie** [comment]
Thanks for your message, as you can see, I have done what you have indicated and I send you a screenshot, the problem continues, the update does not advance, it always stays in:

img/700X450.jpg added to archive. 57577 files left.

![Sin título](https://user-images.githubusercontent.com/64229330/113422685-6ced4580-93cd-11eb-9ecd-56217914779a.png)

![Sin título 2](https://user-images.githubusercontent.com/64229330/113422695-71196300-93cd-11eb-8bee-3f0532d46aa8.png)

I dont understand what is the problem with this 
Regards,
Alberto.

**Comment by florine2623** [comment]
Hello @estenolotienenadie ,

I can't reproduce your issue using the local archive method :
![Capture d’écran 2021-04-02 à 16 38 32](https://user-images.githubusercontent.com/16019289/113425842-d6238780-93d2-11eb-960f-d76b5a7f8b57.png)
![Capture d’écran 2021-04-02 à 16 38 48](https://user-images.githubusercontent.com/16019289/113425848-d885e180-93d2-11eb-9b3a-6d62e14b74c4.png)
![Capture d’écran 2021-04-02 à 16 44 50](https://user-images.githubusercontent.com/16019289/113425854-dae83b80-93d2-11eb-8f7c-f14b4a92d2ac.png)

Upgrade has been successful from 1.7.5.2 to 1.7.7.3 :
![Capture d’écran 2021-04-02 à 16 56 32](https://user-images.githubusercontent.com/16019289/113426967-7e861b80-93d4-11eb-931b-de7101753e24.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

I close your issue.
Thanks!

**Comment by estenolotienenadie** [comment]
Thank you for your help.
Regards,
Alberto.

**Comment by estenolotienenadie** [comment]
Hello, I have deactivated the 1 click upgrade module and I have activated it again and it works now correctly.

![Sin título 4](https://user-images.githubusercontent.com/64229330/113429676-3a494a00-93d9-11eb-8dad-dfd5a2a922ea.png)

Thank you.

**Comment by hibatallahAouadni** [comment]
@estenolotienenadie Glad to hear :tada:
