### ISSUE TITLE
Product image "no image available" incorrect in German

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23836]
#### Describe the bug

The texts on the German default images are incorrect.
/img/p/de.jpg has the text "No image available"
/img/p/de-*-default.jpg have the text "Kein bild verfügbar"

#### Expected behavior

The correct text would be: "Kein Bild verfügbar", 'B' in upper case.

#### Steps to reproduce

1. Install German language
2. Create a product
3. Do not put an image in the product
4. See the product in front

#### Additional information

* PrestaShop version: 1.7.7.2

I'm not sure if this is the correct place to submit this issue, since it is related to localisation.

**Comment by florine2623** [comment]
Hello,

Thanks for the report. I reproduced your issue in PS 1.7.7.3 :
![Capture d’écran 2021-03-31 à 12 23 29](https://user-images.githubusercontent.com/16019289/113130060-e80efa00-921b-11eb-93ea-4475bb5ad8d8.png)
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by lmeyer1** [comment]
I can't make a pull request for two reasons:
- The images are not in this repo
- I ignore which font to use

Sorry for that.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your issue! I manage to reproduce the issue with PS1.7.6.7 and PS1.7.7.3.
> I can't make a pull request for two reasons

But I believe you could help us improving the translations in [Crowdin](http://crowdin.com/translate/prestashop-official/).

Ping @PrestaShop/product-team @Julievrz I tried to translate this sentence with Translate Google and here's the result:

![image](https://user-images.githubusercontent.com/23308427/113321035-7b772680-9313-11eb-9d1a-c945ce960ed5.png)

Could @lmeyer1 change the translation on Crowdin? 
IMHO, I think this is an improvement and not a bug, wdyt?

**Comment by Julievrz** [comment]
Hi @hibatallahAouadni the translation cannot be modified on Crowdin as it appears on an image. But I have the confirmation from a German proofreader that the translation should indeed be "Kein Bild verfügbar" with the B in upper case.

Here is the repo where the image should be updated: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/de/img/de-default-home.jpg

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Julievrz 

Thanks for your confirmation!
> Here is the repo where the image should be updated: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/de/img/de-default-home.jpg

@lmeyer1 now you know what you have to fix the issue, so could you please create a pull request :muscle: 

Thanks in advance!

**Comment by marionf** [comment]
@prestascott 

Do you feel to update the text of [this image](https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/de/img/de-default-home.jpg) for "Kein Bild verfügbar" ?

**Comment by lmeyer1** [comment]
Thanks, @hibatallahAouadni. I'll create the pull request.
What font to use ? The font in the German image is not good neither, but I don't recognize the font used for English and French.
I could use *Noto Sans*, since this is the font of the classic theme, or what's correct?

**Comment by hibatallahAouadni** [comment]
@prestascott could you please answer @lmeyer1 question :pray: 
Thanks in advance :relaxed:

**Comment by prestascott** [comment]
Hello, everyone.

Thanks for your request @lmeyer1! 

The font used is surprisingly "Franklin Gothic Book" which is weird because we're using "Open Sans" in our back office.

Here is the fixed image:
![de-default-home](https://user-images.githubusercontent.com/54888056/113691646-f1d9a700-96cc-11eb-8ecd-106c292bc09c.jpg)

**Comment by lmeyer1** [comment]
@Progi1984 Thank you for merging my first pull request.

**Comment by Progi1984** [comment]
@lmeyer1 The first but not the last one ;)
