### ISSUE TITLE
[BO] Filter by Category - the chosen category is not selected after filtering the products

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#23847]
#### Describe the bug

When I filter the products by Category, the product got filtred perfectly but when I click on **Filter by Category**, the selected category is not selected.

#### Expected behavior

The selected category is selected

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Click on **Filter by category**
3. Select a category
4. The list of products whose belong to the selected category is well displayed =>OK
5. Click on **Filter by category**
6. The selected category is not selected in the tree => NOK => it's a **regression** of PS1.7.7.0

**Screenshots**

https://www.awesomescreenshot.com/video/3221596?key=8ead019929db71ff76bb1c9268b1f4d7

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #24072
