### ISSUE TITLE
registration form don`t work ps 1.7.7.1

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#23845]
PS 1.7.7.1 Don`t work registation form
https://te.com.ua
Every time theese notifications
![image](https://user-images.githubusercontent.com/50954519/113173887-874ee400-9252-11eb-84d8-fc6696dda497.png)
 In the Debug mode
![image](https://user-images.githubusercontent.com/50954519/113173796-6c7c6f80-9252-11eb-9904-56f38d621d25.png)

**Comment by matks** [comment]
@photinia73 the errors with Debug mode on your screenshot indicate that the error comes from SeosaProductLabels module

**Comment by photinia73** [comment]
If I turn off this module nothing change ((

**Comment by photinia73** [comment]
I can't see any errors in the Debug mode but the result the same
![image](https://user-images.githubusercontent.com/50954519/113175354-042e8d80-9254-11eb-9f48-22254174239b.png)

**Comment by alfonsolr09** [comment]
i can register on your web

**Comment by photinia73** [comment]
Yes, thank you for check. It was the problem with cache after Facebook login... Can you close the issue? Thank you

**Comment by alfonsolr09** [comment]
You can answer and close

**Comment by photinia73** [comment]
Close
