### ISSUE TITLE
Can't login prestashop backoffice

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#23851]
I'm trying to login in back office since last 3 days but not able to login. Only page refreshed without error.

1. Go to Backoffice login page
2. Enter email and password, click on login
3. Page will be refreshed without error

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by Pinidou** [comment]
Bonjour, je ne sais pas si je suis au bon endroit. Je cherche depuis 3 jours également. Je ne sais plus du tout aller sur mon back office. En fait je n'accède même pas à la page de connexions puisque j'atteris direct sur une page d'erreur '' http erreur 500 '' je ne sais pas quoi faire (je ne suis pas super douée en informatique et programmation. Merci

**Comment by hibatallahAouadni** [comment]
Hello @dineshbadrukhiya & @Pinidou 

I didn't manage to reproduce your issue with PS1.7.6.7 and PS1.7.7.3. It seems that you have made a terrible mistake in your store that your BO becomes inaccessible.

Sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. And it seems you need help with your shop, so please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: @Pinidou you have to speak English, cause English is the norm on Github

Thank you
