### ISSUE TITLE
Cannot update some of the modules from Prestashop (ie. GDPR)

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#23850]
#### Describe the bug

I cannot update the GDPR module ( https://github.com/PrestaShop/psgdpr/releases/tag/v1.2.1 ) even if I remove it totally and then try to install it again, the module stays in old version (1.1.3) instead of the one form the zip release.

The problem also occurs for some of the other modules

#### Expected behavior

Module get updated version

#### Steps to Reproduce

0. Enable opcache with validate_timestamps=0 and revalidate_path=0
1. **BO**>**IMPROVE**>**Modules**>**Module Manager**
2. Upgrade **GDPR** module
3. See error
4. Uninstall the module
5. Re-install the module with the latest version
6. See error > the module stays in old version (1.1.3)

File permissions are right, no error logs are being thrown. Cache is disabled
The plugin files are correctly uploaded since the version of the plugin in psgdpr.php is 1.2.1, so it has to be something with database
The ps_module table stores the old version of the loaded module

#### Additional information

The problem could probably be resolved by placing a call to opcache reset method

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by ProteanCode** [comment]
Okay I see this is something wrong with opcache enabled...
Upgrading module works fine after disabling opcache.

Please make a call to opcache reset after module upgrade

**Comment by PierreRambaud** [comment]
You should make sure you follow these instructions: 
https://devdocs.prestashop.com/1.7/scale/optimizations/#opcache

**Comment by ProteanCode** [comment]
> You should make sure you follow these instructions:
> https://devdocs.prestashop.com/1.7/scale/optimizations/#opcache

> Also, your favorite ecommerce project made sure it’s fully compatible with OPCache.
> 
> Isn’t it nice?

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

I just edit your issue description adding the steps to reproduce, could you please check and feedback.
Did you update your shop lately? if so, what was your previous PrestaShop version?

Thanks!

**Comment by ProteanCode** [comment]
> Hello @ProteanCode
> 
> I just edit your issue description adding the steps to reproduce, could you please check and feedback.
> Did you update your shop lately? if so, what was your previous PrestaShop version?
> 
> Thanks!

Yup, it is fine. I will add a note that with opcache disabled the problem does not occur

**Comment by florine2623** [comment]
Thanks for the update @ProteanCode .
I'll close this issue as it is fixed !
