### ISSUE TITLE
Update the name of Mexico City

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#23860]
```javascript
-    <state id="DIF" id_country="MX" id_zone="North_America" iso_code="DIF" tax_behavior="0" active="1">
-      <name>Distrito Federal</name> 
+    <state id="CMX" id_country="MX" id_zone="North_America" iso_code="CMX" tax_behavior="0" active="1">
+      <name>Ciudad de México</name>
```

name tag Distrito Federal to Ciudad de México
and its state tag properties id= and iso_code= to "CMX" according to its iso3166-2 code.

On 29 January 2016, Mexico City ceased to be the Federal District (Spanish: Distrito Federal or D.F.), and was officially renamed "Ciudad de México" (or "CDMX")

Source:
https://www.iso.org/obp/ui/#iso:code:3166:MX
https://en.wikipedia.org/wiki/Mexico_City#20th_century_to_present

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/23828
