### ISSUE TITLE
SMTP Outgoing Server prompts invalid credentials due to password lenght / special characters with SMTP Errorcode 535 5.7.8

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#23864]
#### Describe the bug

If the SMTP Passwort for the Email Setup is too long, or contains some special characters, PrestaShop isnt supporting this password, causing for example a 535 5.7.8. error feedback.

#### Expected behavior

PrestaShop mustnt limit any character type or length. Its up to the provider to limit these parameters, and therefor should never expirience a second bottle neck by PS.

#### Steps to Reproduce

1. Go to Backend - Menu - Configure - Advanced Parameter - Email
2. Enter valid credentials, use Plain 25, TLS 587 or SSL 465
3. If the password exceeds some length, or contains some special letters, it wont establish a connection.
4. send a test email and receive the 535 5.7.8 SMTP Error Code

#### Additional information

* PrestaShop version: 1.7.6.x & 1.7.7.3
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @6xthFNGR ,
Could you specify which PrestaShop version is affected ?
Thanks

**Comment by pitkz** [comment]
Since 1.7.6 for minimum, up to the latest stable release 1.7.7.3

**Comment by hibatallahAouadni** [comment]
Hello @6xthFNGR 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22540. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22540
