### ISSUE TITLE
Translation - Search in Translations Tree without result not disabled

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#23876]
#### Describe the bug

When making a search in the translation, the "leaves" of the tree that does not include the searched term were disabled in 1.7.7, it's no longer the case in 1.7.8.

#### Expected behavior

The "leaves" on the Translations tree should appear disabled.

#### Steps to Reproduce

0. Have a shop with BO in English, and French language installed
1. Go to International > Translations 
2. In "Modify Translations" select "back office translations" and "French" as a language, then click the "Modify" button
3. In the search bar, search for "Order" : All the items of the list on the left are displayed as clickable links.
4. Try to click on "Login" : Nothing happens because there is no translation with "Order" in the "Login" directory.
5. On 1.7.7, with the same steps, the "Login" directory was disabled.

**Screenshots**

In 1.7.7 : 
![translation disabled search 177](https://user-images.githubusercontent.com/55688534/113428733-9ca14b00-93d7-11eb-98df-f2987add889e.png)

In 1.7.8 : 
![translation disabled search 178](https://user-images.githubusercontent.com/55688534/113428739-a165ff00-93d7-11eb-815a-aef6d23f34f6.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @sowbiba in #24882
