### ISSUE TITLE
Translatations - Error in Email - Body Translations

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#23878]
#### Describe the bug

On 1.7.8, when I modify translations of Email Body, an error is displayed. There was no error in 1.7.7.

Content of the error : "Email subject translation file not found in _[PATH]_/mails/fr/"

#### Expected behavior

No error :smile: 

#### Steps to Reproduce

1. Go to International > Translations
2. In "Modify Translations" select "Email translations", then "Body" and any theme or language, then click the "Modify" button
3. An error is displayed at the top of the page

**Screenshots**

![translation error in body translation](https://user-images.githubusercontent.com/55688534/113432200-3b7c7600-93dd-11eb-81b6-3d2b2e3406a2.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @sowbiba in #24899
