### ISSUE TITLE
AdminOrders loading slow in back office

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#23873]
When I open AdminOrders page and I search for an order or I click on an order, it takes 10 to 20 seconds to load.
It seems to be because it's waiting for AdminStats completely loaded :
![image](https://user-images.githubusercontent.com/44002621/113414001-3c50e000-93bc-11eb-8aae-234b77d74c7f.png)

index.php?controller=AdminStats&token=fba97670eaf0edc0c5c2e8dd7950d75a&ajax=1&action=getKpi&kpi=average_order_value&rand=1617364944202&_=1617364943875
index.php?controller=AdminStats&token=fba97670eaf0edc0c5c2e8dd7950d75a&ajax=1&action=getKpi&kpi=conversion_rate&rand=1617364944193&_=1617364943873
index.php?controller=AdminStats&token=fba97670eaf0edc0c5c2e8dd7950d75a&ajax=1&action=getKpi&kpi=netprofit_visit&rand=1617364944204&_=1617364943876

Can I deactivate these AdminStats ?

To reproduce :
1. Go on Orders > Orders
2. Click on an order
3. The page is waiting complete loading before open the clicked order
![image](https://user-images.githubusercontent.com/44002621/113413885-f267fa00-93bb-11eb-9b3e-b78b59641fe9.png)

PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by florine2623** [comment]
Hello @guigplt ,

I can't reproduce your issue, please check my screen record :
https://drive.google.com/file/d/1BIM6MD-1LRAgp-Tm0hvBuGIiRB-PedTq/view

Can I deactivate these AdminStats ?
If you deactivate the stats, you won't be able to see the statistics in Statistics Tab :
![Capture d’écran 2021-04-02 à 14 30 02](https://user-images.githubusercontent.com/16019289/113415635-ebdb8180-93bf-11eb-919d-adab0401e143.png)

Make sure your server is powerful enough. You have the system requirements for your server's configuration here :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ 

I close your issue as I can't reproduce it.

**Comment by guigplt** [comment]
The problem is not on statistics tab, it's kpi statistics on Orders page :
![image](https://user-images.githubusercontent.com/44002621/113416474-b9328880-93c1-11eb-9fa6-3f4c012a51fa.png)

Is it possible to deactivate it ?
Because it's useless.

The problem does not come from our server, I already checked.

**Comment by hibatallahAouadni** [comment]
Hello @guigplt 

You can override it (for exemple: add a class with css `display: none;`):

![image](https://user-images.githubusercontent.com/23308427/113436420-f8260580-93e4-11eb-9f24-1eb754a96644.png)

Thanks!

**Comment by guigplt** [comment]
Hi,
CSS rule display:none won't avoid these js kpi stats to be loaded.

**Comment by guigplt** [comment]
Is it possible to disable these js loading ?

**Comment by chrisvanberg** [comment]
Hi,

I'm experiencing the same problem on one of our PrestaShop. It's impossible to access an order while the browser is waiting for the AdminStats.

@guigplt have you found any solution ? 

If I find any useful information/solution, I'll post it there.

PS 1.7.6.4
PHP  7.3

**Comment by chrisvanberg** [comment]
Hi,

It seems (for us) that the problem was caused by a massive `ps_connections` table (+2.000.000 rows). After a deletion of the rows, the speed of the order page was a lot faster than before.

I hope this could help !

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/18956 and fixed in 1.7.7

**Comment by guigplt** [comment]
Hi @chrisvanberg,

Thanks for the tip, I have deleted ps_connections rows and the order page speed is much better !

I already noticed slow loadings in the past caused by the massive size of this table, but since few months we have routine that keeps only last 30 days data in ps_connections, ps_connections_source and ps_guest tables.

I will reduce the number of days stored in these tables.

**Comment by chrisvanberg** [comment]
@guigplt Happy that I could help!

We have a similar routine but the Bingbot is crawling the website like crazy. It generates +53.000 connections in 24h which is problematic. However, this is another problem.

Can't wait to update to 1.7.7 to use the new order page.

**Comment by guigplt** [comment]
Yes we just had this problem too.
I solved it by adding this line in robots.txt file : 
Disallow: /*&q=

**Comment by hibatallahAouadni** [comment]
Duplicate of #18956

**Comment by Betafer** [comment]
> Yes we just had this problem too. I solved it by adding this line in robots.txt file : Disallow: /*&q=

Hello, I have the same problem with prestashop 1.7.8.8
can you please explain to me what this command does

Thank you
