### ISSUE TITLE
Lost link widget

### ISSUE THREAD

**Issue by Maaarija90** [PrestaShop/PrestaShop#23880]
Hi,

I create link widget on home page/footer for Facebook but as I want now to remove it, I can not find it anywhere?

Pls asap respond

Marija

**Comment by hibatallahAouadni** [comment]
Hello @Maaarija90 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
