### ISSUE TITLE
Fields Siret and Company are showed in login form

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#23881]
#### Describe the bug

In checkout process, at first step, login, when B2B is enabled, the fields company and siret are shows. But this is not correct for all contries.

#### Expected behavior

Company and Siret not displayed in login form

#### Steps to Reproduce

1. enable B2B option
2. insert product in cart
3. click on checkout
4. See the login form: the are siret and company.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: >= 1.7.7.2
* PHP version: >= 
![screenshot-localhost_4343-2021 04 03-22_18_33](https://user-images.githubusercontent.com/186556/113490664-ce93d980-94cb-11eb-8fd1-ab6986638a7d.jpg)
7.2

**Comment by hibatallahAouadni** [comment]
Hello @luigimassa 

Do you mean that you encounter this issue only with PS1.7.7.2 and PS1.7.7.3? And you didn't encountered with PS1.7.7.1? Is that so?
Please check and feedback.

Thanks!

**Comment by luigimassa** [comment]
Yes, correct
Only from 1.7.7.2

**Comment by florine2623** [comment]
Hello @luigimassa ,
For which countries is it incorrect ?
Is the wording of the field that is incorrect ?
Thanks!

**Comment by luigimassa** [comment]
I saw for Italy

**Comment by florine2623** [comment]
What exactly is the issue ?
The wording of these 2 fields ?

**Comment by hibatallahAouadni** [comment]
Hello @luigimassa ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
