### ISSUE TITLE
prestashop 1.7 barre de recherche ne fonctionne pas ( version mobile )

### ISSUE THREAD

**Issue by narven-luxe** [PrestaShop/PrestaShop#23883]
Bonsoir,

 La barre de recherche fonctionne correctement sur PC main non pas sur smart phone :(  je ne peux même pas appuyer, pas de curseur, ni de clavier.

Prestashop 1.7.7

Informations sur votre serveur Linux #1 SMP Mon Mar 22 12:49:19 UTC 2021 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.3.27

Merci pour Votre aide.

**Comment by narven-luxe** [comment]
Good evening,

 Search bar works fine on PC hand not on smart phone :( I can't even press, no cursor, no keyboard.

Prestashop 1.7.7

Information about your Linux server # 1 SMP Mon Mar 22 12:49:19 UTC 2021 x86_64

Server software version: Apache

PHP Version: 7.3.27

Thanks for your help.

**Comment by hibatallahAouadni** [comment]
Hello @narven-luxe 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
