### ISSUE TITLE
[Bug] bin/console cache:clear open connection to database

### ISSUE THREAD

**Issue by ybenhssaien** [PrestaShop/PrestaShop#23887]
# Bug

Clearing cache without database connection open throw exception (screenshot below)
![image](https://user-images.githubusercontent.com/7301643/113562895-326eed00-9607-11eb-86b5-fc0e03cb92ea.png)

# To reproduce
1. Shut down database server
2. execute `bin/console cache:clear` or `bin/console cache:clear --no-warmup`

> The cache clear shouldn't open connection to database unless if necessary to do some operations !

**Comment by hibatallahAouadni** [comment]
Hello @ybenhssaien 

Could you please provide your PrestaShop version and your PHP version.
Please check and feedback.

Thanks!

**Comment by matks** [comment]
Hi @ybenhssaien it's because of how the application is bootstrapped, as the Console loads the application. It's a minor issue indeed.

**Comment by hibatallahAouadni** [comment]
Hello @ybenhssaien ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
