### ISSUE TITLE
Erreur fatale: Erreur non interceptée: Classe 'ComposerAutoloaderInit8923787e706e2b767e22977c65950cb6' introuvable dans /homepages/1/d729209043/htdocs/2020/modules/ps_emailalerts/vendor/autoload.php

### ISSUE THREAD

**Issue by elodie66000** [PrestaShop/PrestaShop#23882]
Bonjour 

Prestashop 1.7.7.0

après la désinstallation du module ps_alert j'ai ce message erreur 500 et voici le message ressorti apres activation des bugs;

Erreur fatale: Erreur non interceptée: Classe 'ComposerAutoloaderInit8923787e706e2b767e22977c65950cb6' introuvable dans /homepages/1/d729209043/htdocs/2020/modules/ps_emailalerts/vendor/autoload.php

voici cote admin;

(1/1) ClassNotFoundException

Tentative de chargement de la classe «ComposerAutoloaderInit8923787e706e2b767e22977c65950cb6» à partir de l'espace de noms global.
Avez-vous oublié une déclaration «utiliser»?

dans autoload.php ligne 7

à include_once ()dans AppKernel.php ligne 189

à AppKernel -> enableComposerAutoloaderOnModules ( array('dashactivity', 'dashtrends', 'dashgoals', 'dashproducts', 'graphnvd3', 'gridhtml', 'ps_categorytree', 'ps_checkpayment', 'ps_contactinfo', 'ps_currencyselector', 'ps_customeraccountlinks', 'dans ps_customeraccountlinks', 'dans ps_customeraccountlinks' ps_customtext ',' ps_emailsubscription ',' ps_facetedsearch ',' ps_languageselector ',' ps_linklist ',' ps_mainmenu ',' ps_searchbar ',' ps_sharebuttons ',' ps_shoppingcart ',' ps_socialfollow ',' ps_wirekeyfoundpayment ' , 'statsbestcategories', 'statsbestcustomers', 'statsbestproducts', 'statsbestsuppliers', 'statsbestvouchers', 'statscarrier', 'statscatalog', 'statscheckup ',' statsdata ',' statsequipment ',' statsforecast ',' statslive ',' statsnewsletter ',' statsorigin ',' statspersonalinfos ',' statsproduct ',' statsregistrations ',' statssales ',' statssearch ',' statsstock ' , 'statsvisits', 'welcome', 'gamification', 'cronjobs', 'psaddonsconnect', 'blockreassurance', 'ps_newproducts', 'ps_specials', 'ps_dataprivacy', 'atos', 'paypal', 'uecookie', ' ps_cashondelivery ',' htmlbox ',' verticalblockcategories ',' freelivery ',' seosaproductlabels ',' protect ',' psgdpr ',' pspixel ',' homeproducttabs ',' ps_banner ',' eicaptcha ','facebookchat ',' ps_googleanalytics ',' carteminder ',' ntstats ',' psgiftcards ',' flashsalepro ',' cron ',' thumbgenerator ',' gmcrop ',' ps_imageslider ',' ps_legalcompliance ',' autoupgrade ',' bonbanner ' , 'bongdpr', 'bongooglemap', 'bonhtmlcontent', 'boninstagramslick', 'bonnewsletter', 'bonnotice', 'bonorder', 'bonpromotion', 'bontab', 'bontheme', 'bonthumbnails', 'customtab', ' facebookwidget ',' productcomments ',' productcountdown ',' productyoutube ',' bonzoom ',' ps_categoryproducts ',' ps_bestsellers ',' ps_featuredproducts ',' bonjavascript ',' imageregenerator ',' bonslick ','exportcustomers', 'bridgeconnector', 'deleteordersfree', 'bonban', 'ppbrandslider', 'everpsimgimport', 'sitologapplicationconnect', 'likeboxfree', 'ec_attribute_display', 'migrationpro', 'colissimo', 'bonsearch', 'mondialrelay ',' ooscombinationchange ',' ps_emailalerts '))dans AppKernel.php ligne 79

sur AppKernel -> registerBundles ()dans Kernel.php ligne 493

au noyau -> initializeBundles ()dans Kernel.php ligne 132

au noyau -> boot ()dans Kernel.php ligne 195

au noyau -> handle ( object ( Request ), 1, false )dans index.php ligne 82

 

erreur 500 sur vitrine et backend

Que pensez-vous que je dois faire?

MERCI C'est urgent la boutique n'est plus disponible.

**Comment by hibatallahAouadni** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
