### ISSUE TITLE
BO - Product page - Product list quick navigation cannot be opened 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23898]
#### Describe the bug

In the BO > Catalog > Products > Product details page, when we click on the "Product list" => the quick navigation modal is not opened & an error is displayed in the console
![image](https://user-images.githubusercontent.com/16067358/113714005-3a528e00-96e8-11eb-922e-da88986af78a.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/113713847-11ca9400-96e8-11eb-9757-a7b0c2783357.png)

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Add/Edit a product
3. Click on Product list

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
Already fixed by https://github.com/PrestaShop/PrestaShop/pull/23846
