### ISSUE TITLE
New product button does not work on iOS Safari

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23892]
#### Steps to Reproduce

1. Get your hands on any iPhone. Open Safari.
2. Go to BO, Catalog, Products.
3. Click on Add new product.
4. Does not work.

#### Workarounds

- Double click the button fast
- Rotate phone to landscape
- Force touch the button and select "Open in new tab"

#### Additional information

- PrestaShop version: 1.7.6.2, 1.7.6.5 and 1.7.7.3
- Devices: iPhone XS, iPhone 11, iPhone 12 Pro

**Comment by NeOMakinG** [comment]
Hey @Hlavtox, did you test on 1.7.8 ? I think it works as the button changed, but not sure :)

**Comment by Hlavtox** [comment]
@NeOMakinG Yes, fixed! ;-)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Sorry, I have to close this issue cause it's already fixed on develop branch, please check my screen record below:

https://drive.google.com/file/d/1KxwB89VC_6-_iZntXRwGcIckxdaShex1/view

Thanks @NeOMakinG for the tip :wink:
