### ISSUE TITLE
BO - Product details page - an error is displayed in the console

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23899]
#### Describe the bug

In the BO > Catalog > Products > Products details page > an error is displayed in the console
![image](https://user-images.githubusercontent.com/16067358/113714544-cbc20000-96e8-11eb-84df-e02157d7b711.png)

#### Expected behavior

No error displayed

#### Steps to Reproduce

1. Go to BO > Catalog > Product list page
2. Add/Edit a product

PS1773 => OK

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
It's a problem inside ps_mbo, it shouldn't include module_card file as it's already included in the core

**Comment by MatShir** [comment]
To moved to the MBO repo !

**Comment by softhightech** [comment]
Hello,
i fixed the issue by deleting the module ps_mbo.

Thanks
