### ISSUE TITLE
BO - Edit product page v2 - An error is displayed when saving image settings

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23897]
#### Describe the bug

In the BO > Catalog > Product Edit page v2 > when we click on "save image settings" for  selected images (2 images or more) => an alert is displayed
![image](https://user-images.githubusercontent.com/16067358/113712984-1773aa00-96e7-11eb-9479-72e38571a70e.png)

#### Expected behavior

Ping @PrestaShop/product-team what do you think?
This button should be displayed?

#### Steps to Reproduce

1. Go to BO > Catalog > Product list page
2. Edit a product with 2 images or more: for example `demo_1`
3. Click on Edit product V2
4. Select images (2 images or more)
5. Click on "save image settings" 
6. See error

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
Fixed here : https://github.com/PrestaShop/PrestaShop/pull/23672

The button should not be displayed at all as there are no action with it for the moment

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

The specs are defined in this issue: https://github.com/PrestaShop/PrestaShop/issues/12773
https://projects.invisionapp.com/share/FNUG4HDJRVH#/screens/389372882

Thank you!

**Comment by MatShir** [comment]
It will be implemented for the 1.7.9.0. Nice catch, you don't miss any details ;)

**Comment by florine2623** [comment]
Fixed on 8.1.x.

I'm closing the issue.
