### ISSUE TITLE
BO - Edit product page - all categories have already expanded automatically in product page

### ISSUE THREAD

**Issue by fyndpriser** [PrestaShop/PrestaShop#23909]
Hi,

I have more than 1500 categories and all categories have already expanded automatically in product page we cannot click any button.

A clear and concise description of what went wrong.

The problem appeared after upgrading to 1.7.7

1. Go to Catalog > Product list page
2. Click on save

https://drive.google.com/file/d/19iQV0NnhpJEI8-Ma0CozFkmhIx7eavuB/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

Thanks 🙏

**Comment by florine2623** [comment]
Hello @fyndpriser ,

I couldn't reproduce your issue.
I upgraded from 1.7.6.9 to 1.7.7.3.
In my product page, the categories are displayed like the usual :
![Capture d’écran 2021-04-07 à 12 25 08](https://user-images.githubusercontent.com/16019289/113851953-4d269a80-979c-11eb-884f-b779632f8fe0.png)

What version did you upgrade from ?

**Comment by fyndpriser** [comment]
I upgraded from 1.7.7.0 to 1.7.7.1. and  from 1.7.7.1 to 1.7.7.2 then from 1.7.7.2 to from 1.7.7.3 
The problem appeared after upgrading to 1.7.7.0

**Comment by florine2623** [comment]
_The problem appeared after upgrading to 1.7.7.0_
-> What version did you have previous to 1.7.7.0 ?

**Comment by Betafer** [comment]
i always had this problem, on ps 1.5 1.6 many version and also 1.7

**Comment by florine2623** [comment]
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

**Comment by Betafer** [comment]
Hello, i don't think is a server configuration problem because i had it with more server configuration, with debian, ubuntu, both ispconfig and plask, many different apache config.

Maybe the problem is present with large catalog with many categories as i can see in @fyndpriser video. we also have many categories

**Comment by fyndpriser** [comment]
I usually don't change anything in the server configuration so I don't think it's related to the problem.

**Comment by fyndpriser** [comment]
> _The problem appeared after upgrading to 1.7.7.0_
> -> What version did you have previous to 1.7.7.0 ?

from 1.7.6.9 to 1.7.7.0
I always update the version as soon as it is released.

**Comment by fyndpriser** [comment]
A new video I hope this helps to understand the cause of the problem. Thanks!
https://drive.google.com/file/d/17U_J0D8YE6VsAtPFvb8Uo-hNyBR4T1kH/view?usp=sharing
