### ISSUE TITLE
[Stripe module] Encountered some incorrect charges

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#23915]
#### Describe the bug

Hi guys, I have encountered some incorrect charges, specifically in one case greater than the order amount and in another case lower. The version of the [Stripe module](https://github.com/202-ecommerce/stripe_official) used 2.3.1
If you provide me with information on how to proceed to identify the cause of the bug we could investigate further.
Thanks

#### Additional information

* PrestaShop version: v1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @kenlog ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support) or you can contact directly the developer of the module.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
