### ISSUE TITLE
https://partners-subscribe.prestashop.com/ not working

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#23917]
--> it is an important bug within the prestashop "cloud", but, tried already to address this topic to the prestashop support and does not seem to change anything - please forward to the responsible person/team

#### Describe the bug

https://partners-subscribe.prestashop.com/ is not working

--> this subdomain is used to connect stripe module to stripe within the connection process (and maybe also used by other modules)

#### Expected behavior

Should be possible to connect the stripe module to stripe

#### Steps to Reproduce

1. install stripe module
2. go to the config of stripe module
3. click on "connect with stripe"
4. follow the connection process and before it is finished there is a forward included to that url: https://partners-subscribe.prestashop.com/ which is showing the error message and blocking from successfully connecting:

Error: Server Error
The server encountered a temporary error and could not complete your request.

Please try again in 30 seconds.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![grafik](https://user-images.githubusercontent.com/31710761/113842988-81498d80-9793-11eb-904f-c239f0ddda4e.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by matks** [comment]
Hi @tom75 the people in charge have been informed

**Comment by matks** [comment]
Hi @tom75 it seems it is expected that `/` on this server is not working, however multiple other endpoints on this server are being used and, as far as we can tell, are working fine. We see no issues in how the service answers incoming requests.

The people in charge of this service will reach out to the Module developer team of the Stripe module to sort this out.

**Comment by decom-media** [comment]
Well - still not possible to connect the stripe module with the stripe service - as it seems to try to use only / on that server - therefore, this needs to be changed then within the module or stripe or whereever - could you please try to find someone who is interested to fix that - as mentioned it is now not possible to have stripe connected for payments in prestashop
