### ISSUE TITLE
Using `png_all` option in BO, all images should have transparent background in FO

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23920]
#### Describe the bug

This is somewhere between a bug and an improvement.

When choosing `Use PNG for all images` (`png_all`) as Image format (in menu *Design - Image Settings*), the background is transparent when the original image is in png format and white otherwise.

#### Steps to reproduce
1. Use these two images. [test_images.zip] One is in png format, and one is in jpg format (https://github.com/PrestaShop/PrestaShop/files/6279138/test_images.zip)
2. In menu *Improve - Design - Image Settings*, under *Image generation options*
    for *Image format* choose *Use PNG for all images*
    for *Generate images based on one side of the source image* choose *Automatic (longest size)*
3. Upload both images into a product.
4. Go to the image folder and inspect the generated images.

#### Observed behavior
The resulting resized images are different. Even though they are both saved as png, one is transparent and the other is not (the added border is white, when the original file was in jpg format, and it is transparent when the original was in png format.
a) The original was jpg. The result is a png with a white border (`cart_default` size).
![62673-cart_default](https://user-images.githubusercontent.com/7520695/115393433-faa89d80-a1e1-11eb-8fbd-df532c7537fe.jpg)
b) The original was png. The result is a png with a transparent border (`cart_default` size).
![83771-cart_default](https://user-images.githubusercontent.com/7520695/115393505-114ef480-a1e2-11eb-874d-ac3aa101ac25.jpg)
Change github.com to dark mode to see the difference immediately. Or see below https://github.com/PrestaShop/PrestaShop/issues/23920#issuecomment-822564239 for a screenshot.

#### Expected behavior
I expect both images to be visually the same, with a transparent border. The output format is png for both, because we 
have choosen *Use PNG for all images* (`png_all`), therefore both should have a transparent border.

This would allow for more flexibility for the design of the templates. Also it makes more sense to always make use of the advantages the png format offers when we choose *Use PNG for all images* (`png_all`), and not make the use of transparency dependent on the source format.

#### Backwards compatibility

This should be backwards compatible, since images whose original format is png are already transparent.
It removes the constraint that a template must give a white background to the image in order to hide the difference between a jpg and a png image.

#### Additional information

* PrestaShop version: 1.6.1.1 and 1.7.7.3
* PHP version: any

**Comment by florine2623** [comment]
hello @lmeyer1 ,
For what type of images do you reference to ?

For example, for the logo, the image chosen is already transparent :
![Capture d’écran 2021-04-07 à 17 07 15](https://user-images.githubusercontent.com/16019289/113889649-b7066a80-97c3-11eb-9bd4-3f5bc9bec812.png)
![Capture d’écran 2021-04-07 à 17 07 30](https://user-images.githubusercontent.com/16019289/113889673-be2d7880-97c3-11eb-9ea0-6095cae20183.png)

For the product, it is white for more visibility :
![Capture d’écran 2021-04-07 à 17 07 47](https://user-images.githubusercontent.com/16019289/113889716-c980a400-97c3-11eb-9169-dd1dae401fa4.png)

Image used : 
[PNG_transparency_demonstration_1.png.zip](https://github.com/PrestaShop/PrestaShop/files/6272613/PNG_transparency_demonstration_1.png.zip)


Also, what you're saying is that when the background of an image is white, after regenerating the image with option "Use PNG for all images", you want the background to be transparent ?
![Capture d’écran 2021-04-07 à 17 09 10](https://user-images.githubusercontent.com/16019289/113889921-f92fac00-97c3-11eb-92cd-9dac857cc4c4.png)

Please check and feedback.
Thanks!

**Comment by lmeyer1** [comment]
Sorry, I was not quite clear, and the explanation was not complete.

Your demonstration picture is in PNG format, so it is not possible to show the point with it.

I mean this:
- Given *Image format* is *Use PNG for all images* in menu *Image Settings*
- Given *Generate images based on one side of the source image* is *Automatic (longest size)* in menu *Image Settings*
- Given a light template with a light gray css background behind the image or a dark template with a dark css background
- If I import a rectangular product image in **png** format, the resulting image is square with transparent borders. The template's css background shine through and gives a nice effect. 
   **PNG in, PNG out => everything OK**
- If I import a rectangular product image in **jpg** format, the resulting image is square with white borders (saved as png). The template's css background is hidden behind the images white borders, not so nice.
   **JPG in, *opaque* PNG out => too bad !**

Here is a screenshot of our template: On the left the original image is png. On the right it is a jpg. Without the correction I suggest, there would be a white bar over und under the book. Thanks to the suggested improvement, the light gray css background with a nice hover effect is visible even though the original image was a jpg.
![image](https://user-images.githubusercontent.com/7520695/113896096-e6b87100-97c9-11eb-9570-606b49b4f6c2.png)

I already corrected this (mis-)behavior years ago in v1.6.1.1. It always seemed to me like a bug, that it is not possible to use a css background on product images like in the screenshot, just because jpg files are not well converted to pngs.
I raised this issue, because I'd like to provide a merge request that solves it (with just one changed line). I'm sure that other will be happy when this bug finally disappears.

**Comment by alfonsolr09** [comment]
I did not understand the problem well, can you make a video?

**Comment by lmeyer1** [comment]
I don't think a video is worth it.

If the explanation above is not enough, try it yourself: make the settings I suggest, prepare 2 rectangular images, a jpg and a png, then import them.
In the HTML of the product image add `style="background:#eee;"` :
`<img src="https://fr.ps.sbgmb.net/62673-home_default/colorie-les-psaumes-livre-1-direction.jpg" alt="Colorie les Psaumes - Livre..." data-full-size-image-url="https://fr.ps.sbgmb.net/62673-large_default/colorie-les-psaumes-livre-1-direction.jpg">` => `<img src="https://fr.ps.sbgmb.net/62673-home_default/colorie-les-psaumes-livre-1-direction.jpg" alt="Colorie les Psaumes - Livre..." data-full-size-image-url="https://fr.ps.sbgmb.net/62673-large_default/colorie-les-psaumes-livre-1-direction.jpg" style="background:#eee;">`

This is what you'll get :
![2021-04-08_083927](https://user-images.githubusercontent.com/7520695/113979766-fa092200-9845-11eb-836c-77bc82279622.png)

I can't understand, nobody never noticed this bug. ***Use PNG for all images*** means all imported files will be saved as png. Because of this bug, it forces the shop owner to convert every image to png before importing it. With this bug corrected, Prestashop will take care of converting every image to png correctly, using the transparency feature of the png format.

**Comment by florine2623** [comment]
Hello @lmeyer1 ,
Could you send both of your pictures for test ?
I tested with my dice image in PNG and JPG, the result is the same :
![Capture d’écran 2021-04-08 à 15 27 53](https://user-images.githubusercontent.com/16019289/114034990-fd6ccf80-987e-11eb-8565-1841aeaaf7c7.png)
[PNG_transparency_demonstration_1.png.zip](https://github.com/PrestaShop/PrestaShop/files/6278964/PNG_transparency_demonstration_1.png.zip)
[PNG_transparency_demonstration_1.jpg.zip](https://github.com/PrestaShop/PrestaShop/files/6278966/PNG_transparency_demonstration_1.jpg.zip)

**Comment by lmeyer1** [comment]
Is your image rectangular ? A square picture will not show the problem.
Did you change the inline styles as indicated ? If you dont change the CSS or the inline styles, you won't see the problem.

The point of this bug correction (or feature as you call it) is : custom themes are no longer restricted to white image background. 
[test_images.zip](https://github.com/PrestaShop/PrestaShop/files/6279138/test_images.zip)

**Comment by florine2623** [comment]
Hello @lmeyer1 ,
Thanks for the test images.
Here's the result, they're the same :
![Capture d’écran 2021-04-16 à 16 57 12](https://user-images.githubusercontent.com/16019289/115043843-376c5000-9ed5-11eb-9986-2d6e41a5098a.png)

The `background:#eee;` you add doesn't make the background transparent, it just adds the grey colour.

**Comment by lmeyer1** [comment]
I'm sorry, that my first post was not clear, in fact there were missing the exact steps to reproduce. I have now updated the first post above to include example test images, a clear an complete *Steps to reproduce* section, and the resulting resized images produced by Prestashop:
- original is jpg => resized with white border
- original is png => resized with transparent border.

Set github to dark mode to instantly see the difference. Then there is no need to fiddle with `background-color:` anymore. This is how this looks in my github account. The two images are clearly NOT the same, but are expected to be the same. I hope now everything is clear. 
![2021-04-20_141114](https://user-images.githubusercontent.com/7520695/115393756-52df9f80-a1e2-11eb-8805-63448eee6da8.png)

**Comment by florine2623** [comment]
Thanks for the details @lmeyer1 

@hibatallahAouadni could you try to reproduce the issue please ? On my end, I am unable to do so.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your issue and your PR :rocket: 
I manage to reproduce the issue with PS1.7.7.3 and PS1.7.6.7, see the attached screen record below:

https://drive.google.com/file/d/1lz0NK38Kuy0-8-7jLIATi_fxxUmPD7P8/view

I’ll add this to the debug backlog so that it’s fixed.

Thanks!

**Comment by lmeyer1** [comment]
Thank you @hibatallahAouadni

**Comment by matks** [comment]
Fixed on https://github.com/PrestaShop/PrestaShop/pull/24119
