### ISSUE TITLE
GIFT Product issue on PrestaShop

### ISSUE THREAD

**Issue by Lorenz-00** [PrestaShop/PrestaShop#23928]
I have to give a free product pack when any 4 products are in the cart .. I put 4 products A in the cart and the free product B appears (and therefore they become 5 products in the cart). The problem starts when I remove 1 package of product A from the cart, the free product B is still free because there are actually always 4 products in the cart ..

I hope I have explained .. do you know how to unmark this problem?

* PrestaShop version: 1.7.5.0
* PHP version: 7

**Comment by florine2623** [comment]
Hello @Lorenz-00 ,
In PS 1.7.7.3, this no longer happens. Please check my screen record : https://drive.google.com/file/d/1JRExTpyCms9bZLte6Ctp4QDmIyC70Y7F/view

This is fixed, so I close this issue.
Thanks!
