### ISSUE TITLE
The decimal of wholesale prices on attributes is lost when editing the product

### ISSUE THREAD

**Issue by andromaque** [PrestaShop/PrestaShop#23922]
#### Describe the bug

The decimal of the attributes wholesale prices is lost when the product is edited, and then the calculations of profits are wrong.

#### Expected behavior

The wholesale price should stay the same when the product is edited.

#### Steps to Reproduce

1. From the Back-Office: Catalog / Products, click to edit a Product with attributes
2. Go to the Attributes tab, and then edit an attribute
3. Enter a wholesale price for the attribute (e.g. 1,55)
4. Save and go back to the product listing
5. Click to edit the same product
6. Click on Save and go back to the product listing
7. Click to edit the same product (for the 3rd time), go to the Attributes tab and click on the attribute : the wholesale price has been rounded, the decimal is lost
PS : make sure the decimal used in price is a comma (,) not a point (.)

**Screenshots**

https://drive.google.com/file/d/1ftmGmgHwTNXUNSaZVNcdhtcXVnNE1N1a/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @andromaque ,
I can't reproduce your issue in PS 1.7.7.3.
Please check my screen record and feedback : https://drive.google.com/file/d/1gzE7P0gQDIJZ-qho3O-ax_5gCArmWf6d/view

Thanks!

**Comment by andromaque** [comment]
Hi @florine2623 , maybe it has to do with the fact that you have an English locale where I have a French one. The decimal in English is a point (.) so you encounter no issue, whereas in French the decimal is a comma (,), which raises an issue.

**Comment by alfonsolr09** [comment]
https://youtu.be/yXKb9vbAO8M
I could reproduce the problem

**Comment by alfonsolr09** [comment]
I think it is because if you do not enter the "combinations" tab and save the product, the decimals are reset

**Comment by florine2623** [comment]
Hello @andromaque ,

Default language is French, my BO language is English :
![Capture d’écran 2021-04-08 à 09 24 33](https://user-images.githubusercontent.com/16019289/113985800-d2698800-984c-11eb-83f3-11c4f98e0fe3.png)
I tested again multiple time. I entered the Combination tab, I stayed out, when in again, I can't reproduce your issue.
Please check my screen record :
https://drive.google.com/file/d/1MVmU0yphIXAO-OUKX3R0azwE6SuFfRs6/view

**Comment by andromaque** [comment]
Hi @florine2623,

Once again, I think it comes from your locale. In your BO, the decimal is a point, not a comma.
In my case, and also @alfonsolr09, the decimal is a comma, which causes the trouble (it's not recognized, then the decimal part is truncated).

Change your locale to a country where the decimal is a comma, and you'll experience the same issue.

**Comment by florine2623** [comment]
Hello @andromaque ,

Sorry, I managed to reproduce your issue in PS 1.7.7.3 when the decimal is separated by a comma (,). 
https://drive.google.com/file/d/1MYjewnexjyKPLd0NGgJ_46uPYV5THHZf/view

Your issue is a know issue, the original issue : https://github.com/PrestaShop/PrestaShop/issues/9972 is already in our debug roadmap.
The PR : https://github.com/PrestaShop/PrestaShop/pull/20144

I'll close your issue as it is a duplicate.
Thanks!

**Comment by florine2623** [comment]
Duplicate of #9972

**Comment by andromaque** [comment]
Hi @florine2623,

well... I can see that the issue has been opened in 2018, and the PR is pending since August 2020.
@matthieu-rolland said the PR #20144 was not resolving the issue it was addressed to. 

Unless I'm wrong, the PR #23929 is solving the issue, and the #20144 is stuck and maybe for a while... So I don't know what should be done, but maybe we need the input of @matthieu-rolland first?

EDIT: After a verification, this issue is NOT a duplicate of #9972

**Comment by alfonsolr09** [comment]
@florine2623 reopen this

**Comment by matthieu-rolland** [comment]
I reopened this issue after @andromaque's statement that it is not a duplicate of #9972, I'm not sure myself, so I specified in the PR that it could also fix #9972, just in case...

**Comment by andromaque** [comment]
> I reopened this issue after @andromaque's statement that it is not a duplicate of #9972, I'm not sure myself, so I specified in the PR that it could also fix #9972, just in case...

Thank you! I think these 2 issues are not related, because one is caused by the comma being misinterpreted and truncating the decimals, while the other one is a problem of calculation due to a library (or a lack of a specific library for handling prices and rounding) that will be addressed in a future release... I think I heard @eternoendless speaking of this bad rounding issue for the rewrite of the Product page in the BO
