### ISSUE TITLE
CI must warn if composer.lock does not satisfy composer.json

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#23930]
#### Describe the bug

see title

#### Expected behavior

CI must detect the issue

#### Steps to Reproduce

see https://github.com/PrestaShop/PrestaShop/pull/23896/commits/57386655354d935f013b2bcf55d708604ee41a1f and related CI results

#### Additional information

* PrestaShop version: develop

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers 
Should I add the To Do label ?

Thanks !

**Comment by mvorisek** [comment]
@florine2623 not waiting for dev, I already submitted a PR :)
