### ISSUE TITLE
BO - Products page - Multistore header not displayed on Product Add / Edit page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23937]
#### Describe the bug

In the BO > Catalog > Products > Product Add and Product Edit page, the multistore header is not displayed

#### Expected behavior

It should be displayed as in PS177
![image](https://user-images.githubusercontent.com/16067358/114020594-0e621480-9870-11eb-9903-28c981479080.png)

#### Steps to Reproduce

1. Enable multistore in shop parameters > general
2. Advanced parameters > multistore > add a new shop
3. Set an URL for this shop
4. Go to BO > Catalog > Product page
5. Select a shop or "All shops"
6. Click on "Add a product" or "Edit a product"
7. See error
8. The multistore header is not displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/114020965-731d6f00-9870-11eb-98d5-10db96f55418.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment]
@matthieu-rolland told me it is because the Product Page is missing the right HTML `container`

**Comment by Progi1984** [comment]
Fixed in #24469 by @matthieu-rolland
