### ISSUE TITLE
Merchant is unable to determine which customer is registered

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23936]
#### Is your feature request related to a problem?

When searching for a customer account, the merchant is unable to see which customer from the list is registered, and which are guest accounts.

#### Describe the solution you'd like

Display "Registered" YES/NO in the list. Maybe along with a customer group - related to: https://github.com/PrestaShop/PrestaShop/issues/23116

**Screenshots**

![Výstřižek](https://user-images.githubusercontent.com/6097524/114009460-73633d80-9863-11eb-869a-0ceb0590abd1.JPG)

**Comment by florine2623** [comment]
Hello @Hlavtox ,
Thanks for the suggestion, i'll ping PS product team !
Stay tuned!

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,

Can this new feature be added to the Customer Page ?

Thanks!

**Comment by fabienvallon** [comment]
LGTM
