### ISSUE TITLE
Presta - Premium Google Tag Manager - Google Analytics - doubled revenue

### ISSUE THREAD

**Issue by KFTE** [PrestaShop/PrestaShop#23944]
Hi guys,

I have an issue in Google Analytics I see all values in revenue doubled compare to real amount.
Orders are imported correctly in GA ecommerce - numbers, products everything OK only amount by each order is doubled. Please see attached screenshot from Presta and GA ecommerce.
PrestaShop 1.7.6.4.
Premium Google Tag Manager 2.5.1
Google Analytics universal free version

Do you have any idea what could be wrong, please?
Thank you.
Kind regards,
Zuzana
![Issue - revenue - GA](https://user-images.githubusercontent.com/82026208/114035321-47ee4c00-987f-11eb-8e4f-225eb518b76e.jpg)

**Comment by ghost** [comment]
Check if the module is not hooked two time.

But the best way is ask the developer, here it's for prestashop core

**Comment by KFTE** [comment]
Hi @okom3pom, thank you, I contacted Customer Service - PrestaShop Addons and they recommended me to create an issue here on GitHub. Module is hooked only once... :/

**Comment by ghost** [comment]
It's this link to contact the module developer :

https://addons.prestashop.com/fr/contactez-nous?id_product=27146

**Comment by KFTE** [comment]
Yeap exactly:
![image](https://user-images.githubusercontent.com/82026208/114038622-50945180-9882-11eb-8753-f9c44eb29caf.png)

**Comment by ghost** [comment]
ps_googleanalytics is disabled on your shop ?

**Comment by KFTE** [comment]
yes

**Comment by florine2623** [comment]
Hello @KFTE ,

Can you go to your database, in table ps_ganalytics and check if the orders are correct of if they are doubled ?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @KFTE 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
