### ISSUE TITLE
shop email address is not displayed at the Contact Us page 

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#23976]
#### Describe the bug

shop email address cannot be found by a customer among the contacts information

#### Expected behavior

shop email address can be found by a customer

#### Steps to Reproduce

1. Go to BO Shop parameters ->Contact->Stores page
2. Fill in the Shop email field with a valid email address
3. Save changes
4. Go to FO  Contact Us page and see that email address in not displayed. 
5. Go to FO Home Page Store Information section and see that everything but email address is displayed. 
6. 
![Screenshot 2021-04-09 200634 -2 (2)](https://user-images.githubusercontent.com/11665990/114219693-aa287900-9973-11eb-817c-79ca534c69d1.png)

**Screenshots**

Added 1

#### Additional information

* PrestaShop version: every version starting since 1.7.7.0
* PHP version: PHP version: 7.2.34

**Comment by alfonsolr09** [comment]
![Captura](https://user-images.githubusercontent.com/62474824/114235171-15784800-9980-11eb-8e04-14e28cc7661f.JPG)
i can´t reproduce your problem...

**Comment by AndreyOgleznev** [comment]
Sounds strange. Whatever I do I can't get it to be displayed.

**Comment by alfonsolr09** [comment]
have you try to upgrade to 1.7.7.3??

**Comment by AndreyOgleznev** [comment]
Yes, I have. Nothing has changed :(

**Comment by pablomartin89** [comment]
It's the 'classic' theme? 

It's on the module: 'ps_contactinfo' configuration:  the switch:  'Show Email Address' active?
![image](https://user-images.githubusercontent.com/16488733/114240027-2b3d3b80-9987-11eb-8ed2-9715d798ee1d.png)

**Comment by AndreyOgleznev** [comment]
Oh, thank you! the switch: 'Show Email Address' was inactive (default value?).
I enabled it and now the email address is displayed!
