### ISSUE TITLE
Fatal:  Edit customer address error when no company-name is given. 

### ISSUE THREAD

**Issue by jerryhopper** [PrestaShop/PrestaShop#23986]
#### Edit customer address error when no company-name is given. 

A customer with no company-name is not able to edit his address.
In the backend, its not possible to edit client-adress.

Type error: Argument 11 passed to PrestaShop\PrestaShop\Core\Domain\Address\QueryResult\EditableCustomerAddress::__construct() must be of the type string, null given, called in /var/www/html/src/Adapter/Address/QueryHandler/GetCustomerAddressForEditingHandler.php on line 95

#### Expected behavior

You should be presented the 'edit-adress' page (https://xxx/admin/index.php/sell/addresses/3/edit)

#### Steps to Reproduce

1. create a user without a company name.
2. goto administration, and try edit the adress of this user.
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/1160857/114277298-e79c0d80-9a2a-11eb-8281-f69980c87219.png)

#### Additional information

* PrestaShop version: 1.7.7.3

**Comment by sarahdib** [comment]
Hello @jerryhopper,

I do not reproduce this issue. 
I activate B2B
Create a customer (FO and BO)
Add addresses (FO and BO)
Try to edit the addresses (From BO and FO)

Maybe there is a step missing ? 

Thank you

**Comment by jerryhopper** [comment]
Hello Sarahdib.

I must admit this happened with a modified 'classic' theme.
After testing with a fresh-demoshop, switching to the original 'classic' theme - and clearing the cache - everything worked as expected.

thanks for your time.
