### ISSUE TITLE
Accidentally change product order quantity when swipe on touchspin

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#23989]
When using Prestashop on smartphone/tablet or any other device with touchscreen.
If while you're on cart page you scroll the page swiping finger on the touchspin "+" and "-" the product quantity will change, like if you clicked on it.
This can cause to accidentally change product quantity.

I think that "+" and "-" button should increase (or decrease) product quantity only when you click on it, and not just swiping on it.
In particular on smarphone, because the position it's very close to where you normally swipe with thumb when using it with one hand.

1. Go to front office using a device with touchscreen display
2. Add anything to the cart
3. Open cart
4. scroll up and down swiping finger on the touchspin "+" and "-"

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by sarahdib** [comment]
Hello @darfk3d3,

Thank you for this report.

I was able to reproduce the issue with PrestaShop version 1.7.7.3, so I can confirm that this behavior is indeed a bug.
