### ISSUE TITLE
[Add support for experimental features] Handle Product Page V2 flag setup

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#23999]
This issue is an item in the [Add support for experimental features](https://github.com/PrestaShop/PrestaShop/issues/23235) project

You can read about the project [here](https://github.com/PrestaShop/PrestaShop/issues/23235).

### Handle Product Page V2 flag setup at install

AS a merchant
WHEN I Install PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page after the install process was successfull
THEN I see only one Feature flag: the one used for 'Experimental Product Page'

### Handle Product Page V2 flag setup at upgrade

AS a merchant
WHEN I upgrade from PrestaShop < 1.7.8 to PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page after the install process was successfull
THEN I see only one Feature flag: the one used for 'Experimental Product Page'

## Needed

- the _exact_ wording for Product Page V2 flag: content and translation domain
- the _exact_ help text for Product Page V2 flag: content and translation domain

![tdg](https://user-images.githubusercontent.com/3830050/114372043-6c00a480-9b81-11eb-9a38-f0ff193c4f19.png)

The exact wording is item A.

The exact help text is item B.

**Comment by matks** [comment]
@eternoendless I can implement this simply using a `INSERT INTO` but is that a satisfying implementation?

**Comment by eternoendless** [comment]
You could, but is it the best implementation? We probably should be moving towards [Doctrine fixtures](https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html), right?

**Comment by matks** [comment]
@eternoendless Doctrine fixtures provide a standardized way to load a specific data set, but actually we have the following usecases:

1. Load Product Page V2 Feature flat for 1.7.8 install
=> can be done using Doctrine fixtures

2. Remove the flag in 1.7.9
=> cannot be done using Doctrine fixtures

3. Load Product Page V2 Feature flat for 1.7.x -> 1.7.8 upgrade (x < 8)
=> can be done using Doctrine fixtures but we need some logic to avoid inserting duplicates

So now that I think about it, it seems we need a system
- to load some fixtures but only if needed (add a look-for-duplicates logic)
- be able to remove them during upgrade steps
- maybe be able to modify existing fixtures (for example we rename the flag between 1.7.8 and 1.7.9 ?)
- can be used in both install and upgrade

I could create a PHP class to handle this but it would make the Upgrade process once more dependent on the code it is modifying.

So SQL queries might be the best compromise

**Comment by eternoendless** [comment]
I'm under the impression that currently there's no system to run SQL queries during install.

**Comment by matks** [comment]
> I'm under the impression that currently there's no system to run SQL queries during install.

@eternoendless there is one ... 😅 

https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/db_structure.sql

**Comment by eternoendless** [comment]
> @eternoendless there is one ... 😅
> 
> [https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/db_structure.sql](https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/db_structure.sql?rgh-link-date=2021-04-12T15%3A11%3A44Z)

That one is meant to create tables, not insert data. 

But not all is lost. There is a mythical feature I have heard about in songs. A mighty code that can save us, forged aeons ago, hidden in the deepest corner of the install source by the First Committers. For generations, it has been waiting for the Worthy One to find it, and use it to deliver us from the tyranny of the Fixtures. You have to find it, and save us all from despair. 

Godspeed @matks, and may the code be with you.

**Comment by Julievrz** [comment]
### Name of the page:

‘Experimental Features’ in Admin.Navigation.Menu

### Name of the section:

‘Experimental features’ in Admin.Advparameters.Feature

Label (A)

‘Experimental product page’ in Admin.Advparameters.Feature
Help text (B)

‘This page is a work in progress. It includes new combination management features and other features under development (virtual products, packs, etc.)’ in Admin.Advparameters.Help

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/24037
