### ISSUE TITLE
PAYMENTS 

### ISSUE THREAD

**Issue by lazyfubia** [PrestaShop/PrestaShop#23993]
#### Steps to Reproduce
pay with direct debit sepa, I do not have this active module and continues to appear at the end, and stopped giving the payment for paypal

**Screenshots**
https://prnt.sc/11aasyq

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by sarahdib** [comment]
Hello @lazyfubia,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
