### ISSUE TITLE
[Add support for experimental features] Implement Product Page V2 flag behavior

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24001]
This issue is an item in the [Add support for experimental features](https://github.com/PrestaShop/PrestaShop/issues/23235) project

You can read about the project [here](https://github.com/PrestaShop/PrestaShop/issues/23235).

Following the introduction of the [Product Page V2 flag](https://github.com/PrestaShop/PrestaShop/issues/23999) BO users will be able to enable/disable the flag from the Back Office.

**We need to make sure that, when the flag is disabled, the Product Page BO page V2 is not available.**

**We need to make sure that, when the flag is enabled, the Product Page BO page V2 is available from multiple CTA.**

### Cannot access v2 Page when flag is disabled

Scenario: Cannot see 'New product on experimental page' button in Product Catalog
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is disabled
THEN on the BO listing page 'Product Catalog' I cannot see the 'New product on experimental page' button

Scenario: Cannot see 'Edit on experimental page' button in 'Edit product' v1 page
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is disabled
WHEN I open a 'Edit Product' BO page
THEN I cannot see the 'Edit on experimental page' button

Scenario: Redirect user from v2 page to v1 page
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is disabled
WHEN I attempt to visit the BO page v2 using the URL `/admin-dev/index.php/sell/catalog/products-v2/{PRODUCT-ID}/edit?_token={TOKEN}`
THEN I am redirected to BO page v1
AND a flash message tells me why I was redirected

**Screenshot**
<img width="1216" alt="Capture d’écran 2021-04-13 à 23 01 31" src="https://user-images.githubusercontent.com/3830050/114622381-2c83a680-9cae-11eb-91a9-95ea0c2855cb.png">

### Can access v2 Page when flag is enabled

Scenario: Can see 'New product on experimental page'  button in Product Catalog
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is enabled
THEN on the BO listing page 'Product Catalog' I can see the 'New product on experimental page'  button

**Screenshot**
![Capture d’écran 2021-04-14 à 16 15 59](https://user-images.githubusercontent.com/3830050/114727965-f0e4ed00-9d3e-11eb-97c1-b258f399e77d.png)

Scenario: Can see 'Edit on experimental page' button in 'Edit a product' v1 page
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is enabled
WHEN I open a 'Edit product' BO page
THEN I can see the 'Edit on experimental page' button

Scenario: Can see 'Edit on experimental page' button in Product Catalog
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is enabled
WHEN I open the Product Catalog BO page and I click on the `dots menu` on the right of a product
THEN I can see a link to Page v2 with name 'Edit on experimental page'

**Screenshot**
<img width="300" alt="Capture d’écran 2021-04-13 à 22 28 54" src="https://user-images.githubusercontent.com/3830050/114622262-06f69d00-9cae-11eb-83e9-9534d379572d.png">

Scenario: Can see 'Back to standard page' button in Product Catalog
AS a merchant
WHEN I Install PrestaShop 1.7.8
PROVIDED the Product Page V2 feature flag is enabled
WHEN I open a Product Page V2 page
THEN I can see a link to Page v1 with name 'Back to standard page'

**Comment by matks** [comment]
@Julievrz Summary of items for which I need wordings and domains

- Add new product button

![Capture d’écran 2021-04-13 à 10 03 11](https://user-images.githubusercontent.com/3830050/114518633-da0ba100-9c3f-11eb-8e2f-301c9a25e293.png)

- Edit button from listing

![Capture d’écran 2021-04-13 à 10 02 46](https://user-images.githubusercontent.com/3830050/114518674-e42d9f80-9c3f-11eb-9da7-3d33d5bd5d6e.png)

- Edit button in V1 Page

![Capture d’écran 2021-04-13 à 10 03 37](https://user-images.githubusercontent.com/3830050/114518695-e98aea00-9c3f-11eb-8e58-eacd78e7ce0a.png)

- Message being displayed when merchant attempts to visit V2 Page (using URL) but V2 page is disabled ; so we redirect him to V1 page and display the message

![Capture d’écran 2021-04-13 à 10 04 57](https://user-images.githubusercontent.com/3830050/114518772-fdcee700-9c3f-11eb-8cdd-6aaec5ebfa5b.png)

**Comment by Julievrz** [comment]
@matks Here is my suggestion:

### Add new product button:

‘New product’ in Admin.Catalog.Feature => This wording already exists in Admin.Actions but I created a new one with a new domain so that the two strings can be translated differently if needed.

As discussed with Pablo and Mateus, we can use the “science” icon instead of the “+”. 
To make sure it is clear enough for the user, a message appears when hovering.
‘Create a new product on the experimental product page’ in Admin.Catalog.Help

![image](https://user-images.githubusercontent.com/70583503/114585224-b5d1b380-9c83-11eb-8bb9-25b4c5d9cd15.png)


Color to be used for the button : outline blue. To easily differentiate it from the "normal" Add new button.
This allows us to have a short but clear button.

### Edit button from listing + Edit button in V1 page (same wording)

‘Edit on experimental page’ in Admin.Catalog.Feature

### The message being displayed when merchant attempts to visit V2 Page (using URL) but V2 page is disabled:

‘The experimental product page is not enabled. To enable it, go to the [1]Experimental Features[/1] page.’ in Admin.Catalog.Notification

**Comment by matks** [comment]
### Forgot 1 wording: "back to product page"

@Julievrz I'm sorry I forgot 1 wording.

On the BO Page V1, which is the current Product Page, we have a button that enables merchant to _go back to V1 page_. So the usecase is "I enable Experimental Product Page, I open the Experimental Product Page and now I wish to go back to V1 page from where I am."

<img width="363" alt="Capture d’écran 2021-04-13 à 22 55 54" src="https://user-images.githubusercontent.com/3830050/114620922-5fc53600-9cac-11eb-87ca-346acd16681e.png">

So far we named it "Back to product page". Do you have a better name in mind?

Also I have 2 bad news

### Cannot use science icon

1. You said

> As discussed with Pablo and Mateus, we can use the “science” icon instead of the “+”.

It seems I cannot use the science icon 🤔 . I am limited to all the icons in https://materializecss.com/icons.html and it does not contain _all_ Material icons by Google. Tomorrow I can ask @NeOMakinG if I can workaround it. In the meantime I used the `new_releases` icon.

### What is outline blue

2. You said

> Color to be used for the button : outline blue.

What is "outline blue" color ?

Do you mean this style

<img width="168" alt="Capture d’écran 2021-04-13 à 22 53 53" src="https://user-images.githubusercontent.com/3830050/114621240-bfbbdc80-9cac-11eb-85fe-8b44a1336729.png">

That is what I think is "outline blue". Can you validate?
