### ISSUE TITLE
Should update all Order fields from webservice before sending order status mail

### ISSUE THREAD

**Issue by N-Wouda** [PrestaShop/PrestaShop#24007]
#### Describe the bug

When updating fields including the current order status via the webservice, emails are sent before all other fields have been updated. This means it is not possible to e.g. use the shipping number in shipping emails (via the `actionGetExtraMailTemplateVars` hook), because that shipping number is not yet available on the order/in the database.

#### Expected behavior

An email should be sent _last_, that is, if the current status is updated in the webservice call, the `current_status` field should be processed last.

This is easily achieved by moving the relevant entry in `$webserviceParameters` down to the end of the array. E.g.:

https://github.com/PrestaShop/PrestaShop/blob/115e6ea4ac73b96b305ec8b998ae3acf886d0e6a/classes/order/Order.php#L249-L252

Should be the last entry in the array.

#### Steps to Reproduce

1. Create a new order
2. Create a module inserting the `invoice_date` or `shipping_number` in an email template triggered by some order status (via `actionGetExtraMailTemplateVars`). Any such field is fine, as long as it is processed after `current_state` in the `$webserviceParameters` array.
2. Update the current order status to the order status with the email template having the new variable. Do this via the webservice API, where you also specify a new value for, say, `invoice_date` or `shipping_number`.
3. Observe that the sent email does not contain the new value.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: since at least 1.6.0
* PHP version: N/A

**Comment by N-Wouda** [comment]
In a sense, too, sending an email in the `current_state` setter is a somewhat unexpected side effect. It might be better to refactor this to the `update` or `add` methods. I'd expect those to do such work.

**Comment by N-Wouda** [comment]
Might relate to #13912, but not sure. That one does not appear to update the current order state, only the tracking number (in which case you can force a resend).

**Comment by sarahdib** [comment]
@N-Wouda 

Thanks for the report.

I think this problem is the same as #13802 there is no email sent using Webservice API/

Could you check and feedback ?

Thank you

**Comment by N-Wouda** [comment]
@sarahdib thanks for your response! As far as I can see that one is unrelated. 

In this issue, an email is sent (when the order status is updated), but the email is sent before the rest of the order update is processed completely (for example, a new invoice date or tracking number have not yet been set). That means the information sent via the order status update email is incomplete, or wrong.

In my particular use case I'm receiving a new current order state (shipped) and shipping number from an external service via the PS webservice API. I want to insert that shipping number into the `shipped` email template via the `actionGetExtraMailTemplateVars` hook. This hook is called when the email for the order status is sent out, and then retrieves the shipping number from the database. But there it is not yet available because the webservice updates the order status (and thus sends the email) before all other fields on the order have been updated.

**Comment by hibatallahAouadni** [comment]
Hello @N-Wouda 

Thanks for your patience!
Could you please provide the WS that you use to update your order.

Thanks!

**Comment by N-Wouda** [comment]
@hibatallahAouadni do you mean the XML file?

It's something like:

```xml
<prestashop>
	<order>
		<id_order>1</id_order>
		<current_state>4</current_state>
		<shipping_number>123456</shipping_number>
	</order>
</prestashop>
```

What happens is that the update to `current_state` is processed before `shipping_number` has been processed. That state update also sends the `shipped` email. As a consequence, I cannot add the shipping number into the `shipped` template, because it hasn't been set by the time the email is sent out.

A quick fix to my issue would be if the current state were the last thing that's updated in the order. That might be achieved by moving it to the end of the `Order`'s `webserviceParameters` array.

---

Additionally, but perhaps I should open a new issue for this, I would like a hook at the end of each webservice update. Something like `actionWebserviceUpdateAfter`, or the like. That way I can hook into anything being created once it has been created fully, including all its associations. I find that to be quite difficult to achieve right now.

**Comment by hibatallahAouadni** [comment]
Hello @N-Wouda 

Thanks for your patience :pray: 
> Create a module inserting the invoice_date or shipping_number in an email template triggered by some order status (via actionGetExtraMailTemplateVars). Any such field is fine, as long as it is processed after current_state in the $webserviceParameters array.

Without following this step, I didn't manage to reproduce the issue :confused: 
So, could you please provide a test module to help me up reproducing the issue.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @N-Wouda ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by thbl** [comment]
+1 seams to still be a issue @hibatallahAouadni  please reopen

**Comment by hibatallahAouadni** [comment]
Hello @thbl 

> Without following this step, I didn't manage to reproduce the issue confused
So, could you please provide a test module to help me up reproducing the issue.

Could you please provide a test module to reproduce the issue, otherwise I can't reopen it with reproducing the issue :disappointed: 

Thanks for understanding!
