### ISSUE TITLE
The "Link Widget" in the menu can't be translated

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#24010]
#### Describe the bug

The "Link Widget" in the menu can't be translated

#### Expected behavior

"Link Widget" menu should be available under Admin.Navigation.Menu to be translated
In order to be translatable, this tab must be recorded in the database with the corresponding translation wording and translation domain. The fix must be done in the module itself.

#### Steps to Reproduce

1. Go to International > Translations
2. Select Back office translations, select a language and click on modify
3. Click on Admin > Navigation > Menu
4. There is no "link widget" so you can't translate it

#### Additional information

* PrestaShop version: all
* PHP version: N/A

**Comment by eternoendless** [comment]
Fixed by https://github.com/PrestaShop/ps_linklist/pull/116
