### ISSUE TITLE
Can't update store address in invoice header - Version 1.7.5.0

### ISSUE THREAD

**Issue by GFcreative** [PrestaShop/PrestaShop#24018]
My client wanted me to update the address for his store in his invoices. I went into the Shop Parameters > Contact > Stores and edited his info. It's been. few days and the old address is still appearing on new invoices. I can't find the address anywhere else. 

Does anyone have a workaround? Thanks!

**Comment by florine2623** [comment]
Hello @GFcreative ,

I can't reproduce your issue in PS 1.7.7.3.
Invoice before :
![Capture d’écran 2021-04-14 à 10 46 09](https://user-images.githubusercontent.com/16019289/114681718-b5cac580-9d0e-11eb-80d3-85c6876b95e2.png)
Changes made :
![Capture d’écran 2021-04-14 à 10 45 50](https://user-images.githubusercontent.com/16019289/114681727-b82d1f80-9d0e-11eb-8051-16acaa3e0a2f.png)
Invoice Result :
![Capture d’écran 2021-04-14 à 10 45 42](https://user-images.githubusercontent.com/16019289/114681741-ba8f7980-9d0e-11eb-8207-6ca6c8b2f080.png)

**Comment by GFcreative** [comment]
In the stores I updated my client's address to a new one. It appears in the contact section and the footer of the site. Yet if I go to any new order and view the invoice it still has the old address. I can't figure out where to switch this. I even cleared the site's cache.
