### ISSUE TITLE
Commands prestashop:update:sql-upgrade-file-hooks-listing and prestashop:update:configuration-file-hooks-listing broken on develop

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24023]
#### Describe the bug

CLI commands prestashop:update:sql-upgrade-file-hooks-listing and prestashop:update:configuration-file-hooks-listing broken on `develop` . When they are run, an error message is output.

#### Expected behavior

When commands are run, no error message.

#### Steps to Reproduce

1. Install PrestaShop using `develop` branch
2. Run `php bin/console prestashop:update:configuration-file-hooks-listing`
3. See error
4. Run `php bin/console prestashop:update:configuration-file-hooks-listing 1.7.8.0`
5. See error

![Capture d’écran 2021-04-13 à 11 36 05](https://user-images.githubusercontent.com/3830050/114531757-79369580-9c4c-11eb-844d-850cf84c836f.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by sarahdib** [comment]
@matks is it a regression ?

**Comment by matks** [comment]
@sarahdib Yes unfortunately.

I am working on the fix 😄

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24821
