### ISSUE TITLE
No combination reference on invoice PDF or order history -> detail -> order detail

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#24020]
Hi when you work with combination and buy one, on the invoice PDF you get the base product reference and not the combination reference that you bought.

![image](https://user-images.githubusercontent.com/46203943/114470922-b43db800-9bbd-11eb-8a28-e8825c8d9332.png)

Same happen on customer -> order history -> details -> order details

![image](https://user-images.githubusercontent.com/46203943/114470852-92443580-9bbd-11eb-87b3-243e71e3494d.png)

On the catalogue TPL we use {$product.reference_to_display} but on the order-detail-no-return.tpl $product object has no reference_to_display

array (size=120)
  'id_order_detail' => string '8' (length=1)
  'id_order' => string '6' (length=1)
  'id_order_invoice' => string '1' (length=1)
  'id_warehouse' => string '0' (length=1)
  'id_shop' => string '1' (length=1)
  'product_id' => string '20' (length=2)
  'product_attribute_id' => string '40' (length=2)
  'id_customization' => string '0' (length=1)
  'product_name' => string 'GUANTE ALTO RIESGO DE NITRILO HEALTH TOUCH® NO ESTÉRIL EXTRA LARGO 40CM - Tamaño : S' (length=87)
  'product_quantity' => string '1' (length=1)
  'product_quantity_in_stock' => string '1' (length=1)
  'product_quantity_refunded' => string '0' (length=1)
  'product_quantity_return' => string '0' (length=1)
  'product_quantity_reinjected' => string '0' (length=1)
  'product_price' => float 1261
  'reduction_percent' => string '0.00' (length=4)
  'reduction_amount' => string '0.000000' (length=8)
  'reduction_amount_tax_incl' => string '0.000000' (length=8)
  'reduction_amount_tax_excl' => string '0.000000' (length=8)
  'group_reduction' => string '0.00' (length=4)
  'product_quantity_discount' => string '0.000000' (length=8)
  'product_ean13' => string '' (length=0)
  'product_isbn' => string '' (length=0)
  'product_upc' => string '' (length=0)
  'product_mpn' => string '' (length=0)
  'product_reference' => string 'guante' (length=6)
  'product_supplier_reference' => string '' (length=0)
  'product_weight' => string '0.000000' (length=8)
  'id_tax_rules_group' => string '1' (length=1)
  'tax_computation_method' => string '0' (length=1)
  'tax_name' => string '' (length=0)
  'tax_rate' => float 19
  'ecotax' => string '0.000000' (length=8)
  'ecotax_tax_rate' => string '0.000' (length=5)
  'discount_quantity_applied' => string '0' (length=1)
  'download_hash' => string '' (length=0)
  'download_nb' => string '0' (length=1)
  'download_deadline' => string '0000-00-00 00:00:00' (length=19)
  'total_price_tax_incl' => string '1500.000000' (length=11)
  'total_price_tax_excl' => string '1261.000000' (length=11)
  'unit_price_tax_incl' => string '1500.000000' (length=11)
  'unit_price_tax_excl' => string '1260.504202' (length=11)
  'total_shipping_price_tax_incl' => string '0.000000' (length=8)
  'total_shipping_price_tax_excl' => string '0.000000' (length=8)
  'purchase_supplier_price' => string '0.000000' (length=8)
  'original_product_price' => string '1260.504202' (length=11)
  'original_wholesale_price' => string '0.000000' (length=8)
  'total_refunded_tax_excl' => string '0.000000' (length=8)
  'total_refunded_tax_incl' => string '0.000000' (length=8)
  'id_product' => string '20' (length=2)
  'id_supplier' => string '0' (length=1)
  'id_manufacturer' => string '3' (length=1)
  'id_category_default' => string '10' (length=2)
  'id_shop_default' => string '1' (length=1)
  'on_sale' => string '0' (length=1)
  'online_only' => string '0' (length=1)
  'ean13' => string '' (length=0)
  'isbn' => string '' (length=0)
  'upc' => string '' (length=0)
  'mpn' => string '' (length=0)
  'quantity' => string '1' (length=1)
  'minimal_quantity' => string '1' (length=1)
  'low_stock_threshold' => null
  'low_stock_alert' => string '0' (length=1)
  'price' => string '$ 1.500' (length=8)
  'wholesale_price' => string '0.000000' (length=8)
  'unity' => string '' (length=0)
  'unit_price_ratio' => string '0.000000' (length=8)
  'additional_shipping_cost' => string '0.000000' (length=8)
  'reference' => string 'guante' (length=6)
  'supplier_reference' => string '' (length=0)
  'location' => string '' (length=0)
  'width' => string '0.000000' (length=8)
  'height' => string '0.000000' (length=8)
  'depth' => string '0.000000' (length=8)
  'weight' => string '0.000000' (length=8)
  'out_of_stock' => string '2' (length=1)
  'additional_delivery_times' => string '1' (length=1)
  'quantity_discount' => string '0' (length=1)
  'customizable' => string '0' (length=1)
  'uploadable_files' => string '0' (length=1)
  'text_fields' => string '0' (length=1)
  'active' => string '1' (length=1)
  'redirect_type' => string '301-category' (length=12)
  'id_type_redirected' => string '0' (length=1)
  'available_for_order' => string '1' (length=1)
  'available_date' => string '0000-00-00' (length=10)
  'show_condition' => string '0' (length=1)
  'condition' => string 'new' (length=3)
  'show_price' => string '1' (length=1)
  'indexed' => string '1' (length=1)
  'visibility' => string 'both' (length=4)
  'cache_is_pack' => string '0' (length=1)
  'cache_has_attachments' => string '1' (length=1)
  'is_virtual' => string '0' (length=1)
  'cache_default_attribute' => string '40' (length=2)
  'date_add' => string '2020-12-17 12:12:26' (length=19)
  'date_upd' => string '2021-01-21 16:38:56' (length=19)
  'advanced_stock_management' => string '0' (length=1)
  'pack_stock_type' => string '3' (length=1)
  'state' => string '1' (length=1)
  'image' => ........

This is the combination reference:

![image](https://user-images.githubusercontent.com/46203943/114471121-13033180-9bbe-11eb-86e7-9719d3eb4236.png)

#### Expected behavior

If we buy a combination, we expect the reference of that combination to be shown

#### Steps to Reproduce

Just buy a combination product, then go to customer -> order history -> detail button -> products details (reference)

#### Workaround

on the order-detail-no-return.tpl line 45 we add
{assign var='combination' value=Product::getAttributeCombinationsById((int)$product.product_attribute_id,$this->context->language->id)}

***BUT*** on the SQL of the function getAttributeCombinationsById on the "where" it asks for pa.`id_product` = ' . (int) $this->id . ' but $this->id is not pass on the function so it gives an error.

To not touch the core we copy the class Product.php on the override folder and erase pa.`id_product` = ' . (int) $this->id . ' like this:
Line 2466:

$sql = 'SELECT pa.*, product_attribute_shop.*, ag.`id_attribute_group`, ag.`is_color_group`, agl.`name` AS group_name, al.`name` AS attribute_name,
                    a.`id_attribute`, a.`position`
                FROM `' . _DB_PREFIX_ . 'product_attribute` pa
                ' . Shop::addSqlAssociation('product_attribute', 'pa') . '
                LEFT JOIN `' . _DB_PREFIX_ . 'product_attribute_combination` pac ON pac.`id_product_attribute` = pa.`id_product_attribute`
                LEFT JOIN `' . _DB_PREFIX_ . 'attribute` a ON a.`id_attribute` = pac.`id_attribute`
                LEFT JOIN `' . _DB_PREFIX_ . 'attribute_group` ag ON ag.`id_attribute_group` = a.`id_attribute_group`
                LEFT JOIN `' . _DB_PREFIX_ . 'attribute_lang` al ON (a.`id_attribute` = al.`id_attribute` AND al.`id_lang` = ' . (int) $id_lang . ')
                LEFT JOIN `' . _DB_PREFIX_ . 'attribute_group_lang` agl ON (ag.`id_attribute_group` = agl.`id_attribute_group` AND agl.`id_lang` = ' . (int) $id_lang . ')
                WHERE pa.`id_product_attribute` = ' . (int) $id_product_attribute . '
                GROUP BY pa.`id_product_attribute`' . ($groupByIdAttributeGroup ? ',ag.`id_attribute_group`' : '') . '
                ORDER BY pa.`id_product_attribute`';

And now IT WORKS!!!, we have the combination details on the history -> product details and only rest to modify the 
{l s='Reference' d='Shop.Theme.Catalog'}: {$product.product_reference}<br/> by

{l s='Reference' d='Shop.Theme.Catalog'}: {$combination[0]['reference']}<br/>

now we have the combination reference

![image](https://user-images.githubusercontent.com/46203943/114472502-5494dc00-9bc0-11eb-995c-8de095d188d1.png)

the final code will look like this:

`{if $product.reference}
              {if $product.product_attribute_id}
                {assign var='combination' value=Product::getAttributeCombinationsById((int)$product.product_attribute_id,$this->context->language->id)}
                {l s='Reference' d='Shop.Theme.Catalog'}: {$combination[0]['reference']}<br/>
              {else}
                {l s='Reference' d='Shop.Theme.Catalog'}: {$product.product_reference}<br/>
              {/if}
            {/if}`

Note: you have to repite this code on line 130 for mobile and on the file order-detail-return.tpl line 67 and 184, also note that the PDF template also need to be modify.

We know that by modifying the core class order-> OrderDetail.php adding the combination reference, all this will be much simpler

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.27

**Comment by florine2623** [comment]
Hello @msaustral ,

I can't reproduce your issue in PS 1.7.7.3.

Please check the screenshots below.

In product page base product :
![Capture d’écran 2021-04-14 à 10 57 19](https://user-images.githubusercontent.com/16019289/114683384-4655d580-9d10-11eb-9b27-f19ea53677b3.png)
Combination :
![Capture d’écran 2021-04-14 à 10 57 35](https://user-images.githubusercontent.com/16019289/114683365-435ae500-9d10-11eb-8cb6-e60d23d42755.png)

In order :
![Capture d’écran 2021-04-14 à 10 55 39](https://user-images.githubusercontent.com/16019289/114683426-4fdf3d80-9d10-11eb-8439-34b1ea6c4db5.png)
![Capture d’écran 2021-04-14 à 10 54 08](https://user-images.githubusercontent.com/16019289/114683530-65ecfe00-9d10-11eb-9873-dce9f5d80e88.png)
![Capture d’écran 2021-04-14 à 10 53 45](https://user-images.githubusercontent.com/16019289/114683540-684f5800-9d10-11eb-85d6-eff183c376c9.png)

In invoice :
![Capture d’écran 2021-04-14 à 10 55 05](https://user-images.githubusercontent.com/16019289/114683506-5f5e8680-9d10-11eb-94b8-11c8d6e85b76.png)

I'll close your issue.
Thanks!

**Comment by msaustral** [comment]
Hi that is correct, it is solved on the 1.7.7.3, thank you!! :)
