### ISSUE TITLE
BO - Order / Impossible to make partial refund if the product has more than 9 unit

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#24033]
#### Describe the bug
In a order If a product have more than 9 unit it's not possible to set an amount of product for a partial refund

#### Expected behavior

we must be able to make a refund regardless of the number of products

#### Steps to Reproduce

1. Go to FO and make an order with 15 units of the same product
2. Go to BO and try to make a partial refund for this order
3. See error => impossible to set the amount of product

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by #24266
