### ISSUE TITLE
Cierre de Sesión - Backoffice ( Login Admin Loop) - Prestashop 1.6.1.5

### ISSUE THREAD

**Issue by alevazke** [PrestaShop/PrestaShop#24039]
Buenos días,
Estoy usando: Prestashop, 1.6.1.5, y me he dado cuenta, que al entrar en el listado de módulos, y clicar sobre "Configurar", "Desactivar" u otra función en dicho listado. Prestashop me cierra automáticamente la sesión, haciendo imposible que pueda configurar nada dentro de Prestashop.
Hace tiempo, realicé la migración de prestashop hacia este hosting, pero el error lo hemos detectado hace poco.

**Comment by florine2623** [comment]
Hello @alevazke ,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
