### ISSUE TITLE
slow queries in PS 1.7.7.2

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#24044]
#### Describe the bug

From time to time we encounter some strange behavior..
Mostly the following query slows down our machine (8 cores, 64GB RAM):

`
SELECT p.id_product
FROM (SELECT p.id_product, p.id_manufacturer, SUM(sa.quantity) as quantity, p.condition, p.weight, p.price, psales.quantity as sales, cp.position
FROM ps_product p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product)
LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute)
LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1 AND sa.id_shop_group = 0 )
LEFT JOIN ps_product_sale psales ON (psales.id_product = p.id_product)
INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product)
INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1)
INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE)
WHERE p.visibility IN ('both', 'catalog') AND c.nleft>=456 AND c.nright<=457 AND ps.id_shop='1' GROUP BY p.id_product) p
INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) GROUP BY p.id_product ORDER BY p.position ASC, p.id_product DESC LIMIT 0, 12
`

it seems as if some event triggers this query several times (10-20, sometimes even more..), until they block each other, so that our server is 100% busy processing (or waiting) these queries. This situations last several minutes up to 1 hour.
While we have 100k + items in over 100 categories, for the most part that doesn't create this problem. But since recently (after an update from 1.7.5 to 1.7.7 some weeks ago) the problem occurs more often.

#### Expected behavior

hmm.. being much more faster!?

#### Steps to Reproduce

it looks like it is a similar problem as with #23773 (slow queries with facet navigation)

#### Additional information

* PrestaShop version: 1.7.7.2 / Z.One templates
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @x2wr0 ,

I can't reproduce your issue in PS 1.7.7.3. It never goes up to 10-20 sec or 1 hour.
Please make sure you are following the system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
You can also check if you have modules that have queries running in the background.

The more products you have, the greater your memory should be.

I suggest checking this [link](https://www.prestashop.com/fr/professional-services), it might be useful for you.
Thanks!

**Comment by eveneme** [comment]
I have this problem, please open and repair. as there are many products and combinations it takes 30-40 seconds to load and sometimes it causes mysql crash.
