### ISSUE TITLE
Prestashop add to cart terribly slow (6 sec plus) 

### ISSUE THREAD

**Issue by Leo-pold-02** [PrestaShop/PrestaShop#24048]
Hello.

I have a Pestashop 1.7.6.1 running on 7.2 php.
Ita an update from a 1.6 presta version that got verified and was runnign smoothly on a subdomain. 
I moved it th the main / root domain today. Works pretty well. But i have a big issu that adding to cart takes forever now. Like 6 sec or so. Shop is : shop.neunvonfrisch.com 

I tried disabeling cache 
Deavtivate Overrides and 3rd party plugins 
Deactivate Apache optimisation

```
Preforming this to the Database via myphp - sql query:
# 404 erors
DELETE FROM `ps_pagenotfound` WHERE `date_add` < '2021-04-10' ;
# Sent mails
DELETE FROM `ps_mail` WHERE `date_add` < '2021-04-10';
# Searched keywors ???
DELETE FROM `ps_statssearch` WHERE `date_add` < '2021-04-10';
# Connection page (ps_connections_page.id_connections - ps_connections.id_connections)?
DELETE FROM ps_connections_page;
```

The ahot itself runs quick, only the add top cart is an issue so far.
Any ideas and help much aprreciated.

Ps.: im not a database ot prestashop expert :) 

Best
Leo

**Comment by Leo-pold-02** [comment]
Might any of this tables be an issue? should i clean them too? 
If so what code to use? 

![Bildschirmfoto 2021-04-14 um 16 34 12](https://user-images.githubusercontent.com/57262480/114728447-63ee6380-9d3f-11eb-9e6f-71fcf43fa4cc.jpg)

**Comment by giuseppelucchese** [comment]
I have the same problem.. 1.7.7 version running on php 7.3

**Comment by pablomartin89** [comment]
How many active Cart Rules do you have, without 'code' ? 
Sometimes if there's a lot of cart rules that have to check the validity of the cart_rule, it can result on a lower performance.

**Comment by florine2623** [comment]
Hello @Leo-pold-02 ,

I upgraded my shop 1.6.1.24 to 1.7.6.1 like you did.
![Capture d’écran 2021-04-16 à 16 03 05](https://user-images.githubusercontent.com/16019289/115036085-7ac2c080-9ecd-11eb-825a-f2a21c57047f.png)
![Capture d’écran 2021-04-16 à 16 22 21](https://user-images.githubusercontent.com/16019289/115038550-ef96fa00-9ecf-11eb-8f40-bdf5ba0e7674.png)
The add to cart button doesn't take longer than usual.

I suggest checking your template for compatibility with PS 1.7.6.1.
You can also update your system requirement to match PS 1.7.6.1 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ 

You can check this [link](https://www.prestashop.com/fr/professional-services) for an audit of your site performance.

As I can't reproduce your issue, I'll close it.
Thanks!
