### ISSUE TITLE
Force All Shops context for Experimental Features Back Office page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24059]
#### Describe the bug

The Experimental Features Back Office page behavior works for the full system. It's a system-wide setting. It cannot be modified for a single shop or a group of shop (when Multistore mode is enabled).

But nothing indicates this. We should add the following behavior:

When BO user visits the Experimental Features Back Office page, if his shop context is not "All shops" we force the shop context to "All shops". A message explains to user that his shop context was changed to "All shops" because the page only supports "All shops" mode.

#### Steps to Reproduce

1. Install 1.7.8.0 . Go to BO
2. Visit Configure > Adv Parameters > Experimental Features
3. All the changes you can do on this page are for all shops, but there is no indication for the user.

#### Additional information

* PrestaShop version: develop (1.7.8)

**Comment by Robin-Fischer-PS** [comment]
Ping @marionf : Could you confirm that the proposed behavior is OK ? (we discussed it with @matks but we would like to have a PM validation :smile: )

**Comment by marionf** [comment]
> When BO user visits the Experimental Features Back Office page, if his shop context was not "All shops" before, we force the shop context to "All shops" 

We should also display only the "all shops" context in the header to not let the user select a specific shop or group.

> A message explains to user that his shop context was changed to "All shops" because the page only supports "All shops" mode

As described in [the multistore specs](https://github.com/PrestaShop/prestashop-specs/blob/9783996765a46d3d7197e4f7cd7098ffb7e37ff2/content/1.7/broader-topics/multistorespecialsspecs.md#list-of-specific-cases), the message should be: "Note that this page is available in all shops context only, this is why your context has just switched."

**Comment by Progi1984** [comment]
Fixed by #24128
