### ISSUE TITLE
JavaScript error in console using multistore

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#24057]
#### Describe the bug

Js error in console using multistore

#### Steps to Reproduce

1. Go to BO
2. Activate Multistore
3. Add a store
4. Configure new store
5. Open console browser
6. See error

**Screenshots**

<img width="1435" alt="Capture d’écran 2021-04-14 à 22 38 44" src="https://user-images.githubusercontent.com/3034677/114825431-824b7200-9dc6-11eb-8841-ff8b5d47dd90.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed in #24456 by @matthieu-rolland
