### ISSUE TITLE
Ps_metrics error

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24050]
Hi
I'm going to report some errors get from the module ps_metrics

`[2021-04-14 09:50:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShop\Module\Ps_metrics\Helper\DataHelper::modifyArrayMainKeys() must be of the type array, null given, called in /home2/dklgasto/public_html/modules/ps_metrics/src/Kpi/VisitsKpi.php on line 162" at /home2/dklgasto/public_html/modules/ps_metrics/src/Helper/DataHelper.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to PrestaShop\\Module\\Ps_metrics\\Helper\\DataHelper::modifyArrayMainKeys() must be of the type array, null given, called in /home2/dklgasto/public_html/modules/ps_metrics/src/Kpi/VisitsKpi.php on line 162 at /home2/dklgasto/public_html/modules/ps_metrics/src/Helper/DataHelper.php:34)"} []`

I continue to get email from the log events due from that error
from the backoffice all seems to be ok

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/114733272-7d91aa00-9d43-11eb-91c6-aad4839c8456.png)
![2](https://user-images.githubusercontent.com/653230/114733287-7ec2d700-9d43-11eb-805d-5fe0b54930ce.png)
![3](https://user-images.githubusercontent.com/653230/114733770-eed15d00-9d43-11eb-8eb4-0820b678ab37.png)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2
* ps_metrics version: 1.3.3

**Comment by sarahdib** [comment]
Hello @maofree,

Thanks for this report ! 
We are working on a new version of ps_metrics ! 

For ps_metrics you can report bugs using the contact us button in the module.

Thank you
