### ISSUE TITLE
Wrong button name for Experimental Product page button on Standard Add page

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24068]
#### Describe the bug

When on the "Add a product" page (standard), the button redirecting to the experimental product page wording is "Edit on experimental page". It should be "New product on experimental page" (Admin.Catalog.Feature)
#### Expected behavior

Hi, this suggestion looks good to me. However, we have to make sure this will apply only if creating a new product.

This should not modify the edit buttons in the listing and on an existing product page (V1) that should remain 'Edit on experimental page'.
@Julievrz 

#### Steps to Reproduce

1. Go to Advanced Parameters > Experimental Features
2. Enable the "Experimental product page"
3. Go to Catalog > Products > Click on "+ New product"
4. See button on bottom right : "Edit on experimental page"

**Screenshots**

![edit experimal page](https://user-images.githubusercontent.com/55688534/114851141-c9932c00-9de1-11eb-8b83-ab2821d17947.png)

#### Additional information

* PrestaShop version: develop (1.7.8)
* PHP version: N/A

**Comment by Julievrz** [comment]
Hi, this suggestion looks good to me. However, we have to make sure this will apply only if creating a new product. 

This should not modify the edit buttons in the listing and on an existing product page (V1) that should remain 'Edit on experimental page'. 

Thanks :)

**Comment by hibatallahAouadni** [comment]
FYI @marionf 
So, what is the status of this issue? Is it **To Do** or **TBS**?

**Comment by marionf** [comment]
I don't know, let's ask to @MatShir

**Comment by Julievrz** [comment]
As @jolelievre suggested, we could keep the existing wording "New product on experimental page".

**Comment by matthieu-rolland** [comment]
I think it was not only the label being wrong, it's also the link (it's an edition URL instead of a creation URL )

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24892
