### ISSUE TITLE
Multistore dropdown not displayed when a group is selected as context

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#24066]
#### Describe the bug

I realized that a behavior is not correct in the current multistore dropdown implementation:

The specific settings drop-down isn't displayed when a group is selected as context and If a parameter has a specific value for at least one shop of the group selected

#### Expected behavior

The specific settings drop-down should be displayed when a group is selected as context and If a parameter has a specific value for at least one shop of the group selected

#### How to test
1/ Enable multistore
2/ Create at least one other shop "shop2" in the default group
3/ Go to the configuration > maintenance page, select "shop2" as context, customize the maintenance message and save
3/ Go to the configuration > maintenance page, select the default group as context, the dropdown should be displayed for the field you modified, and the "shop2" should have the "customized" label

#### Specs

https://github.com/PrestaShop/prestashop-specs/blob/9783996765a46d3d7197e4f7cd7098ffb7e37ff2/content/1.7/back-office/multistoregeneralspecs.md#specific-settings-drop-down-only-from-178

**Comment by atomiix** [comment]
Fixed by #24211
