### ISSUE TITLE
Error to edit invoice from PS1.7.6.7 to 1.7.7.3 : [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]

### ISSUE THREAD

**Issue by kolorslab** [PrestaShop/PrestaShop#24070]
#### Describe the bug

Hi i made an update in August on the "production" website to PS 1767 (and yesterday to to 1773) and since this two upgrades i always have an error to edit invoice from Orders and the mail to customer has no invoice.

Yesterday i dit the same process on the "test" website and all is working well in 1773. I can edit the invoice, and i receive the invoices during the order process.

#### Expected behavior

On production website i have this error : `[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]`

#### Steps to Reproduce

I look on the 2 SQL DB but i don't see any differences.

**Screenshots**

If i click on an order picto to get the invoice i got the error! `[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]`

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.2.7
I have to resolve this bug as soon as possible if someone had this bug and could help i would be happy!

Best!

**Comment by florine2623** [comment]
Hello @kolorslab ,

Editing invoices is not a native feature in PrestaShop, you must be using an external module.

So I suggest contacting the developer of the module directly.
Thanks!

**Comment by kolorslab** [comment]
Hi @florine2623 the invoice .pdf edition works well on a copy of the website it's native like other documents.

I got 4 problems on the production website but not on the test website exactly same version PS1.7.7.3 : 

1 -the shopping cart with this error `Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart `
2 - print an invoice `[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException code 0]`
3 - the invoice isn't send by mail to the customer even if parameters are ok in "orders / state orders"
4 - I don't show the the Modal popup when i had a product in the cart and it doesn't refresh directly the number of items in the cart

I don't understant all this bug with 2 shops on 2 different MySQL DB

If you got an idea?

I don't need an invoice pdf generator cause it works well on the other site.

Best

**Comment by kolorslab** [comment]
It was just the columns of MySQL table who wasn't uptaded, a speciality since the 1.6. And no need an addon to generate pdf invoices! Best @florine2623
