### ISSUE TITLE
Internal server error ps1.7.7.3

### ISSUE THREAD

**Issue by jordi-art** [PrestaShop/PrestaShop#24078]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version:1.7.7.3
* PHP version: 7.3.27
* Hello dear prestashop  team, form we have upgrade to this new version we have the following error , we need information to get resolve it problem. You can see the screenshot. Thank you !!! best regards!
![Captura error ps](https://user-images.githubusercontent.com/82602687/114905709-88b70980-9e19-11eb-9687-e41b251e345c.PNG)
![Captura error ps 2](https://user-images.githubusercontent.com/82602687/114905762-9b314300-9e19-11eb-819b-9b6e6adeef5f.PNG)
![Capturaerror ps3](https://user-images.githubusercontent.com/82602687/114905814-ab492280-9e19-11eb-9b87-d57ece35a857.PNG)
![Capturaerror ps 4](https://user-images.githubusercontent.com/82602687/114905843-b603b780-9e19-11eb-8e96-b376af8c1fd2.PNG)

**Comment by florine2623** [comment]
Hello @jordi-art ,
Please add the steps to reproduce your issue.
Version of shop before upgrading.
What module you used to upgrade your shop + version of module
What page has this error.

I'll close your issue for now. Feel free to open a new one with all info so we can reproduce your issue and help you out.
Thanks!

**Comment by jordi-art** [comment]
Hello i don't understand what do you meant, because i put versión ps 1.7.7.3 and it was from 1.7.7.2 i always use 1 clickupgrade module last version.
Sorry!!
Thank you

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
