### ISSUE TITLE
Hook actionAdminOrdersListingFieldsModifier

### ISSUE THREAD

**Issue by lozal2244** [PrestaShop/PrestaShop#24082]
Hello,
The hook actionAdminOrdersListingFieldsModifier is not working in the 1.7.7.x versions, the module that I send [here](https://tiendaprest.com/wp-content/uploads/2019/01/columnas.zip) should work because it works on Prestashop 1.7.6.x

Steps to reproduce:
1- Install this module 
2, Go to orders list and see that the column is not being showed

Tested on Pretsashop 1.7.7.3

**Comment by matks** [comment]
Hello @lozal2244 this is expected, the Orders Back Office pages have been migrated to Symfony in PrestaShop 1.7.7 .

New replacement hooks are detailed on https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/

**Comment by kpodemski** [comment]
There's more, new orders page, as well as other migrated pages, uses `Grid` component, you can read more about it, and how to work with it in modules here:

https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/modify-grid-in-module/
