### ISSUE TITLE
Upgrade to 1.7.7.3 Error: Class 'League\Tactician\Bundle\TacticianBundle'

### ISSUE THREAD

**Issue by carras** [PrestaShop/PrestaShop#24098]
After trying to upgrade from PS 1.7.6.8 to PS 1.7.7.3, using 1-click-upgrade module,  I get this following error:

Can somebody tell me what is wrong?

[INTERNAL] /public_html/app/AppKernel.php line 59 - Error: Class 'League\Tactician\Bundle\TacticianBundle' not found 
#0 /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles() 
1 /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles() 
#2 /public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() 
#3 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() 
#4 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 
#5 /public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#6 /public_html/controlador/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#7 {main}

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @carras 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
