### ISSUE TITLE
Internal serever error in PS1.7.7.3

### ISSUE THREAD

**Issue by jordi-art** [PrestaShop/PrestaShop#24093]
Hi there ,
I need help with this problem we do not know what it can be. I Update prestashop from version 1.7.7.2 to 1.7.7.3 with the module 1-click Upgrade v4.12.0. Every time I enter the backoffice it gives me this error in logs Internal server error 127 and sends me email alerts. Everything else works fine. Attached images, I hope you can help me to correct this error as soon as possible. Thank you.
![Captura error ps](https://user-images.githubusercontent.com/82602687/115032357-81e7cf80-9ec9-11eb-8e9e-19795c81cb91.PNG)
![Captura error ps 2](https://user-images.githubusercontent.com/82602687/115032415-91671880-9ec9-11eb-8df9-1d18f2691846.PNG)
![Capturaerror ps3](https://user-images.githubusercontent.com/82602687/115032454-9d52da80-9ec9-11eb-83e1-8936259b1e81.PNG)
![Capturaerror ps 4](https://user-images.githubusercontent.com/82602687/115032478-a643ac00-9ec9-11eb-8682-edaf795a81f9.PNG)

**Comment by florine2623** [comment]
Hello @jordi-art ,

After upgrading from PS 1.7.7.2 to 1.7.7.3 with module 1-click upgrade v4.12.0, I have access to the back-office.
I can't reproduce your issue as you can see from my screenshot.
![Capture d’écran 2021-04-16 à 16 20 04](https://user-images.githubusercontent.com/16019289/115038259-a646aa80-9ecf-11eb-95a0-f127277c7168.png)


If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by jordi-art** [comment]
Florine the problem is a bug from prestashop New upgrade 1.7.7.3  i ready working with a prestashop expert and him told me to report you in github, but is ok if you don't know why appear this error ok. Will investigate us.
Thank you

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jordi-art** [comment]
The i see don't serve of nothing github

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jordi-art** [comment]
Is second time that you close my report with nothing ,This is very bad.

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
