### ISSUE TITLE
Impossioble to change order status (approved,delivered etc)

### ISSUE THREAD

**Issue by rbeau** [PrestaShop/PrestaShop#24097]
Hi !

Recently, I updated Prestashop from 1.7.5 to 1.7.7 a three weeks ago. It is since unfortunately it is impossible for us to change the status of recent orders (after update).

**Prestahop Dashboard-> Orders -> Selecting a order -> Change its status**

There is an error line always like the following: 

> Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0] : Notice: Trying to get property 'id' of non-object.

For old deliveries made if I change the status of the order; I have another error: 

> Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0] : Notice: Undefined variable: id_address.

1 - Bug image
![prestashop1](https://user-images.githubusercontent.com/13245810/115057110-f0d22200-9ee3-11eb-8921-1e1fb3092015.png)

2 - Frozen orders status :(
 

![prestashop2](https://user-images.githubusercontent.com/13245810/115057114-f0d22200-9ee3-11eb-989e-39169289c0ae.png)

Please, could you help me to solve this problem.

**Comment by hibatallahAouadni** [comment]
Hello @rbeau 

I didn't manage to reproduce your issue and it seems you have a problem with some missing id_address.
Please check these issues, you may find some answers:
#22215
https://tecserve.eu/prestashop17/prestashop-error-after-upgrading-1-7-7-1/
#23336
#22611

We will close this issue.

Thanks!

**Comment by rbeau** [comment]
Dear hibatallahAouadni,

I applied some proposition but there is any change. I getting same error when I change order status.

Could you, please explain me more about relation of id_address with this bug to solve its ? Please see in the first exemple error code was :

`Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0] : Notice: Trying to get property 'id' of non-object.`



Thanks !

**Comment by hibatallahAouadni** [comment]
Hello @rbeau 

Could you please post your question in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack)
You may get some help from our contributors or our developers :wink: 

Thank you
