### ISSUE TITLE
BO - Translations page - Theme translations select is empty when we we have only Classic theme

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24090]
#### Describe the bug

This issue is reproduced only when this PR: https://github.com/PrestaShop/PrestaShop/pull/24049 is merged
The New spec: https://github.com/PrestaShop/PrestaShop/pull/24049
In the BO > International > Translations page > when we have only the Classic theme, the "Theme translations" select is empty.
If you try to click on "Export" => alert 

#### Expected behavior

Ping @eternoendless @PrestaShop/product-team what do you think, we can just hide the option `Theme translations` when we have only the Classic theme

#### Steps to Reproduce

1. Go to BO > International > Translations page
2. In the "Export a language " section > Select the option `Theme translations`
3. See error: The select is empty 
![image](https://user-images.githubusercontent.com/16067358/115018790-98395f80-9eb8-11eb-8318-b2c5b43ec00c.png)
4. Click on Export > alert => ok 
![image](https://user-images.githubusercontent.com/16067358/115018834-a6877b80-9eb8-11eb-880f-d9eecf53e406.png)

#### Additional information

* PrestaShop version: develop (1780)
* PHP version: 7.2

**Comment by eternoendless** [comment]
IMO we can add a default value like "select a theme". You can't go on until you select one. This should be pretty much the same with modules actually

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24268
