### ISSUE TITLE
Install the wislist module

### ISSUE THREAD

**Issue by Link-1110** [PrestaShop/PrestaShop#24100]
* PrestaShop version: 1.7.7.3
* PHP version: 7.3

* Hello, can you tell me how to install the wislist module because I can't do it like all my other modules? at the installation it indicates an error.
![Capture](https://user-images.githubusercontent.com/77692194/115107467-44d41980-9f6b-11eb-9bca-a2f9e4a9fbe4.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @Rantanplan1110 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
