### ISSUE TITLE
Move email confirmation logic to separate function in Order.php

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24123]
#### Is your feature request related to a problem?

In order to implement ability to resend order confirmation (https://github.com/PrestaShop/PrestaShop/issues/14754), it would be good to separate the logic that sends order confirmation to a separate function, so we can reuse it whenewer we can.

#### Describe the solution you'd like

Extract all the logic that sends email confirmation from [PaymentModule](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php)`->validateOrder()` to a new function `sendConfirmation()` in [Order](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php) class.

**I will do it if I get a green light.** 👍 
Ping @eternoendless

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by eternoendless** [comment]
From what I understand this is a refactoring issue, not a feature request. I totally agree that the confirmation email part should be extracted from the PaymentModule – I think it would be best to put it in a new SendOrderConfirmationCommand within the Order domain, and not within the Order class. That said, I'm not sure if the CommandBus is available in FO, so you might end up having to set up that as well 😅

**Comment by Hlavtox** [comment]
@eternoendless Unfortunately, that's not in my skill range. 😞 
Can I do the nice work and move it to Order class, and then you can play with this CommandBus stuff? 😁

**Comment by Prestaworks** [comment]
Will the CommandBus be available in FO for PS9?

**Comment by Hlavtox** [comment]
I think only if you enable experimental full FO container. Otherwise, I have a PR ready with the command finished. ;) But works in BO now only.

**Comment by Prestaworks** [comment]
would have been nice to have it in the order class two years ago :P 
But if the PR is ready for BO, then I guess it will be ok when it's merged (hopefully for PS 9 release) and maybe we can add it to the experimental FO also.
