### ISSUE TITLE
BO - Products page - Summary & Description - the line break is calculated for allowed characters

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24131]
#### Describe the bug

In the BO > Catalog > Products page > in the summary & the description block the line break is calculated for allowed characters

#### Expected behavior 

The error alert should be displayed with the error message at the bottom of the field. The product can't be saved

<img width="1163" alt="Capture d’écran 2021-06-02 à 18 45 29" src="https://user-images.githubusercontent.com/43613217/120519387-d6400380-c3d2-11eb-945b-cd1f37a9afc5.png">

#### Steps to Reproduce

1. Go to BO -> Products page -> New product page
2. In the Summary & Description  -> set a paragraph with multiple line break 
3. Characters **>** allowed characters (=800)
4. Save => a green alert is displayed => NOK: we should have This value is too long. It should have 800 characters or less. Or The line break should not be calculated as in PS1773

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/115417770-31d67900-a1f9-11eb-8022-b403cc82f74b.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25038 by @jolelievre
