### ISSUE TITLE
ps_emailalerts doing infinite loop in the hook rendering

### ISSUE THREAD

**Issue by josguein** [PrestaShop/PrestaShop#24137]
When is the turn call to render the hookdisplayadditionalinfo on the ps_emailalerts module, he tries to call it but it just doing  an infinite loop and the page is loading until he gives a timeout error, this is only happen when the "Product Availability" option is on.

**Comment by florine2623** [comment]
Hello @josguein ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
