### ISSUE TITLE
tracking front stats error

### ISSUE THREAD

**Issue by etsmes** [PrestaShop/PrestaShop#24136]
#### Describe the bug

When i go on https://www.nummulit.com/modules/trackingfront/stats.php
I have a error 
Fatal error: Uncaught --> Smarty: Unable to load template 'file:./errors.tpl' in '/usr/home/nummulit.com/web/modules/trackingfront/views/templates/front/login.tpl' <-- thrown in /usr/home/nummulit.com/web/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195

#### Expected behavior

view affiliate statistics

**Screenshots**

![Captura](https://user-images.githubusercontent.com/19926260/115506585-4eb39080-a27b-11eb-8ea6-6457bc0a11eb.PNG)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hello @etsmes ,

This is a nexternal module issue.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by etsmes** [comment]
Hi @florine2623,

Thank you for the answer
It is not an external module. Is a native module.

![Captura](https://user-images.githubusercontent.com/19926260/115515186-2d57a200-a285-11eb-8fd9-453f1db7bc4f.PNG)

Multiple requests have been opened about this module, but it has not been fixed yet. 
#18007
#15830
#9780
...

Kind regards,
Josep

**Comment by hibatallahAouadni** [comment]
Hello @etsmes ,

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

Thanks!
