### ISSUE TITLE
No Carriers Available

### ISSUE THREAD

**Issue by matt-cloudconstruct** [PrestaShop/PrestaShop#24138]
#### Describe the bug

A lot of customers are reporting they are being shown the message "Unfortunately, there are no carriers available for your delivery address.", even though there are carriers for their zone. Logging out and back in resolves the issues and carriers are then shown correctly.

#### Expected behavior

Would expect a list of carriers to be shown based on the customers delivery address

#### Steps to Reproduce

I have managed to replicate this by doing the following:

1. Add item to your basket and go to checkout
2. Log in and proceed until the addresses section
3. Click to add new address
4. Filling in the form as normal and ensure it validates correctly
5. Press the submit button multiple times (this will cause the address to be added to list multiple times)
6. If you select any of the new addresses and go next you will get the "no carriers" message

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by matt-cloudconstruct** [comment]
This forum entries appears to resolve the issue:

https://www.prestashop.com/forums/topic/1027497-fix-for-unfortunately-there-are-no-carriers-available-for-your-delivery-address/

**Comment by florine2623** [comment]
Hello @mattpbs ,

I can't reproduce your issue. Please check my screen record :
https://drive.google.com/file/d/1HOSmjQp07sOV5mbrvfibUDDicHnT7R8m/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
