### ISSUE TITLE
BO - Simple Product -Specific price - Warning is empty when we try to remove a customer from a specific price and when we try to remove a product from a pack

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24142]
#### Describe the bug

- [ ] **First issue**

In the BO > Catalog > Products > Product details page, when we try to remove a customer from a specific price => the warning is empty
![image](https://user-images.githubusercontent.com/16067358/115550295-fa73d500-a2a9-11eb-9fac-0a83ae81658f.png)

#### Expected behavior
177x we have this
![image](https://user-images.githubusercontent.com/16067358/115550370-0f506880-a2aa-11eb-83f0-50b6b0880bcc.png)

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Add/Edit a product
3. In the pricing Tab > Add a specific price for "John Doe"
4. Edit the specific price
5. Try to remove the customer "John DOE"
6. See error
![image](https://user-images.githubusercontent.com/16067358/115551444-5ee36400-a2ab-11eb-8b79-c4da2962954f.png)

- [ ] **Second issue**
When we try to remove a product from a pack, a warning empty is displayed
1. Go to BO > Catalog > Products page
2. Add a pack product
3. Add a product to this pack
4. Try to remove it
5. See error 
![image](https://user-images.githubusercontent.com/16067358/115583712-6fef9d80-a2ca-11eb-9536-3daf3b09b68a.png)

#### Additional information

* PrestaShop version: 178x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #24696 by @jolelievre
