### ISSUE TITLE
FO - Missing 404 for disabled category page

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24143]
#### Describe the bug

On the FO, when trying to access a disabled category, an error/exception is displayed instead of a 404 page (exception in debug mode, error message without debug mode).

#### Expected behavior

When accessing any disabled category page on FO we should have a 404 page and not an error.

#### Steps to Reproduce

1. Enable debug mode
2. Create a category
3. Disable the category
4. In FO, try to access the disabled category by URL : The following exception is displayed : 

![image](https://user-images.githubusercontent.com/55688534/115555989-7113d100-a2b0-11eb-8988-23ca05b3d854.png)

On 1.7.7 we are redirected to the 404 page : [URL]/fr/index.php?controller=404

**Screenshots**

See above

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by NeOMakinG** [comment]
Maybe related to https://github.com/PrestaShop/PrestaShop/pull/22908, gonna take a look

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24270
