### ISSUE TITLE
Release 1.7.7.4

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#24164]
This issue tracks the status of the PrestaShop 1.7.7.4 release

### Information

Q                                    | A
-----------------------|---------------
**Type**                        | Patch version
**Estimated build**  | 2021-04-28
**Milestone** | [1.7.7.4](https://github.com/PrestaShop/PrestaShop/milestone/72)
**Kanban** | [1.7.7.4](https://github.com/PrestaShop/PrestaShop/projects/14)
**Delivery date**          | 2021-05-03

### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] Release
- [x] Available for upgrade
- [x] Docker image

**Comment by matks** [comment]
## 🚧 Status update

The build has been created and submitted today to QA for validation.

**Comment by marionf** [comment]
[Release note PR](https://github.com/PrestaShop/prestashop.github.io/pull/890)

**Comment by matks** [comment]
Release has been done by @matthieu-rolland https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.4

**Comment by matks** [comment]
Release is now available for upgrade thanks to @matthieu-rolland

**Comment by PierreRambaud** [comment]
Docker images have been built and pushed on Docker Hub.
