### ISSUE TITLE
Will prestashop work with PHP Swoole?

### ISSUE THREAD

**Issue by IsaiChristian** [PrestaShop/PrestaShop#24166]
#### Is your feature request related to a problem?
"Swoole enhances the efficiency of your PHP applications and brings you out of the traditional stateless model, enabling you to focus on the development of innovative products at high scale, brining event loops and asynchronous programming to the PHP language."
https://www.swoole.co.uk/
PHP swoole benchmarks seems impressive, 
it allows php to work closer to Nodejs in a event driven and async 
will this technology work with Prestahop?

They already offer a plugin for Symfony https://www.swoole.co.uk/article/symfony-swoole that I believe can be the starting point for any change that is needed. 

#### Alternatives you've considered

It can be a module that overrided the models.

#### Additional context

Given the benchmarks, this could really improve the performance in big stores. 

is this something feasible? where I would have to start if i want to try to make this happen?

Thx in advance

**Comment by florine2623** [comment]
Hello @IsaiChristian ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by matks** [comment]
@florine2623 as Swoole seems to be a solution that aims to replace Apache and Nginx I dont think Product Team will be able to tell us 😉  it's very technical 😞  .

Hello @IsaiChristian I did not know about Swoole before. If I get it right, it aims to be a replacement for Apache and Nginx?

I dont know whether PrestaShop can work with Swoole today (without changes or with minor changes) but I dont think we will invest time to make it work. Swoole might be an interesting path, however we aim to solve the needs of a majority of users, and if I am not wrong, the majority of users today use Apache or Nginx.

If Swoole became a challenger of Apache and Nginx and it was a lot easier to find a hosting setup to make it work, it would become interesting. However if this is only available for a few skilled developers and sysadmins, it would not be a good investment for us to work (then maintain) compatibility between PrestaShop and Swoole. I am sorry 😅  it's just we have so many things to do, we have to focus on the ones that can be useful for our majority of users.

If you are interested in this topic, feel free to explore it 😉  but I dont think we would merge Pull Requests adding logic that only serve PrestaShop<->Swoole compatibility.

That being said, we'll keep an eye on it 😉  it could become a major game-changer in PHP and when this day come, maybe we'll change our mind. But for now Apache and Nginx are the main players.

**Comment by matks** [comment]
@IsaiChristian Following my answer I close the issue for the reasons explained above ⬆️

**Comment by IsaiChristian** [comment]
Thanks for the time you took answering.! is very much appreciated.

**Comment by matks** [comment]
Unfortunately the latest news from Swoole are a bit scary 😱 

https://news-web.php.net/php.pecl.dev/17446

https://github.com/swoole/swoole-src/blob/1bc39175acb7d339a9d2d046e031dd9561adb1eb/ext-src/php_swoole_library.h#L7260-L7283
