### ISSUE TITLE
Prestashop 1.7.7.2 BO find product by specific ID not range

### ISSUE THREAD

**Issue by patrys666** [PrestaShop/PrestaShop#24167]
#### Describe the bug

It is a pain when I search for a product by ID and get a lot of results

#### Expected behavior

 I'm wondering if it's possible to change filter form from searching by ID MIN-MAX to one field where i can type specific ID.

#### Steps to Reproduce

1. Go to Catalog->Products

#### Additional information

* PrestaShop version: 1.7.7.2

Can someone suggest a temporary solution?

**Comment by florine2623** [comment]
Hello @patrys666 ,

This is a wanted feature.
If you want to show only one product, you can put the same id in both fields :
![Capture d’écran 2021-04-23 à 09 33 02](https://user-images.githubusercontent.com/16019289/115835740-e8637500-a416-11eb-8a1f-2a6355f44f81.png)

Only one result will show.
Thanks!
