### ISSUE TITLE
changing price range from an exixting carrier is not possible PS 1.7.7.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#24178]
#### Describe the bug

Changing the price range from a existing carrier is not saved.

#### Expected behavior

Changing the price range from a existing carrier should besaved.

#### Steps to Reproduce

1. Go to 'Shipping -> Carriers'
2. Click on a carrier with price range rule and save
3. Go back to that carrier 
4. See error that the price range is not saved

**Screenshots**

https://drive.google.com/file/d/1D3EllOmOC68n9uBhFdeszZTY-WT40iY4/view

#### Additional information

Upgrade from PS 1.7.6.9 to 1.7.7.3

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @didi-2018 ,
I can't reproduce your issue.
Please check my screen record :
https://drive.google.com/file/d/14FLfz5b181tK_dqGUp-E67agSeuV4ISQ/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
