### ISSUE TITLE
changing price range from an exixting carrier is not possible PS 1.7.7.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#24171]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @didi-2018 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by didi-2018** [comment]
@florine2623 It has not saved my Template SORRY
