### ISSUE TITLE
Cannot translate menu item "Experimental Features"

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24186]
#### Describe the bug

The new Back Office page "Experimental features" can be visited through the menu item "Experimental Features"

![Capture d’écran 2021-04-23 à 15 48 15](https://user-images.githubusercontent.com/3830050/115880781-62adec80-a44b-11eb-9c09-5bb4c93ef778.png)

But this menu entry cannot be translated in the Translations interface. This is because menu entries are not controlled by code.

#### Expected behavior

The menu entry should be translatable in the Translations interface.

#### Steps to Reproduce

1. Open Back Office, choose French language
2. The menu entry "Experimental Features" is not translated and it cannot be found in the Translations interface.

#### Additional information

* PrestaShop version: 1.7.8.x

**Comment by Progi1984** [comment]
Fixed by #24187
