### ISSUE TITLE
1.7.7.3 Webservices issue on PUT with HTML/CData

### ISSUE THREAD

**Issue by erwanregnier** [PrestaShop/PrestaShop#24194]
#### Describe the bug

404 error for Webservices PUT request when sending HTML (even an empty CDATA element) in the description field
The error is not present in POST, only when updating

#### Expected behavior
Should update the product

#### Steps to Reproduce
Using the [Prestashop Webservices Library][1] to create and update products.

I'm able to update the product if I remove the html, but it should work with HTML code too
I [extended SimpleXMLElement to add a CDATA][2] in the Prestashop Library, but the result is the same

```
require_once('class/PSWebServiceLibrary.php');


try {
     
        $webService = new PrestaShopWebservice('https://mywebsite', 'MYKEY', false);

        $idProduct = 30;
 
        $xmlResponse = $webService->get(['resource' => 'products', 'id' => $idProduct]);
 
        $updateProductXML = $xmlResponse->product[0]; 
        unset($updateProductXML->manufacturer_name); //Not writable, remove them
        unset($updateProductXML->position_in_category);
        unset($updateProductXML->quantity);

        $updateProductXML->name->language[0][0] = "TEST";
        $updateProductXML->description->language[0][0] = "This is not working if I add this: &amp; ";
 
        $response = $webService->edit([
            'resource' => 'products',
            'id' => (int) $updateProductXML->id,
            'putXml' => $xmlResponse->asXML(),
        ]);
 
    } catch ( PrestaShopWebserviceException $e){
        echo $e->getMessage();
    }
```
if I remove the `&amp;` in the description field it works and update the product, else it returns a 404 error even if the description is in a CData node or if the CData node is empty:

Not working as well:

`$updateProductXML->description->language[0][0]->addCData('test &amp: test');`
`$updateProductXML->description->language[0][0]->addCData('juste normal text but in cdata');`

  [1]: https://github.com/PrestaShop/PrestaShop-webservice-lib
  [2]: https://github.com/fawno/SimpleXMLExtended

#### Additional information
- Prestashop version: 1.7.7.3, fresh install

**Comment by erwanregnier** [comment]
Two additional notes:

- The 404 error doesn't come from the WebserviceRequest.php class ( I logged all of them and the debug mode just return a 404 without a specific message)
- It works when doing an urlencode of the description field, then doing a specific urldecode around line 1594 of the WebserviceRequest.php

So the problem seems to come earlier in the process, but only for PUT requests...

**Comment by hibatallahAouadni** [comment]
Hello @cryonos 

I just use the same code and the product has been updated, check my code:

```
<?php

require_once('./PSWebServiceLibrary.php');

try {

        $webService = new PrestaShopWebservice('http://prestashop/prestashop_1.7.7.3_b1', 'W28BAMUM39R65L24XS1ZLE2ZB3F8CVII', false);

        $idProduct = 45;

        $xmlResponse = $webService->get(['resource' => 'products', 'id' => $idProduct]);

        $updateProductXML = $xmlResponse->product[0];
        unset($updateProductXML->manufacturer_name); //Not writable, remove them
        unset($updateProductXML->position_in_category);
        unset($updateProductXML->quantity);

        $updateProductXML->name->language[0][0] = "TEST";
        $updateProductXML->description->language[0][0] = "This is not working if I add this: &amp; ";

        $response = $webService->edit([
            'resource' => 'products',
            'id' => (int) $updateProductXML->id,
            'putXml' => $xmlResponse->asXML(),
        ]);

    } catch ( PrestaShopWebserviceException $e){
        echo $e->getMessage();
    }

?>
```
For the results, check my screenshot:

![image](https://user-images.githubusercontent.com/23308427/116112153-98efa400-a6b7-11eb-9463-fb5b3793787b.png)

And I got an error on my console:

```
Uncaught Error: Syntax error, unrecognized expression: This is not working if I add this: &amp;
    at Function.t.error (main.bundle.js:277)
    at t.tokenize (main.bundle.js:277)
    at t.select (main.bundle.js:277)
    at Function.t [as find] (main.bundle.js:277)
    at De.fn.init.find (main.bundle.js:277)
    at new De.fn.init (main.bundle.js:277)
    at De (main.bundle.js:277)
    at t.value (product_page.bundle.js?1.7.7.3:12)
    at t.value (product_page.bundle.js?1.7.7.3:12)
    at new t (product_page.bundle.js?1.7.7.3:12)
```
Well, I didn't get 404 error but I got this error, so did you encounter the same error when you check the product in BO?
Please check and feedback.

Thanks!

**Comment by erwanregnier** [comment]
Hello @hibatallahAouadni 
I didn't checked this error in BO, but making some tries I maybe resolved the issue:
if I modify the PSWebServiceLibrary.php adding a Content-type header like this, it works without giving the 404 error, I don't know why this is working without this header for the POST but not for the PUT, but it seems to solve the problem:

`CURLOPT_HTTPHEADER => array(
                'Expect:',
                'Content-Type: application/xml',
              ),`

I will send this modification to the PSWebServiceLibrary library, I don't know if there is also a modification to do in the Prestashop webservices process to avoid this.

thanks!

**Comment by hibatallahAouadni** [comment]
Hello @cryonos 

So, is there any other infos that you could provide to help me reproducing the issue?
If there's not, I have to close the issue :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @cryonos ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
