### ISSUE TITLE
Wrong price in the document list for the delivery slip in the admin order page

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24197]
Hi

#### Describe the bug

if you go into an order page where the delivery slip is generated, the document list shows an amount different from that one shown in its pdf

#### Expected behavior

the amount associated to the delivery slip should be the same of its pdf

#### Steps to Reproduce

go to an order page from BO and look the document list, the delivery slip shows a different price of its pdf

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/115958269-0d371580-a507-11eb-8348-2e29a447a306.png)
![2](https://user-images.githubusercontent.com/653230/115958270-0e684280-a507-11eb-9074-dd1c8dfdd9e4.jpg)
![3](https://user-images.githubusercontent.com/653230/115958271-0f00d900-a507-11eb-8bfd-c6223a33d7b1.jpg)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

bye

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Thanks for your issue!
With PS1.7.6.7, the amount was not displayed, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116071723-83b24f80-a68e-11eb-99e3-982198d6fbab.png)

With PS1.7.7.3, the amount displayed is the the shipping price and not the order's total, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116071932-c116dd00-a68e-11eb-98d2-48180c5db4ba.png)

But, let's ask the Product Team to check if this is the wanted behavior :wink: 
Ping @PrestaShop/product-team displaying the amount of shipping in the amount column is the wanted behavior or it's a bug?

**Comment by Maofree** [comment]
Hi
yes but inside the pdf of delivery slip it is not present 7€ but the total amount
try to ask to them to know if it is ok or not

**Comment by hibatallahAouadni** [comment]
@MatShir @marionf any idea? :pray:

**Comment by MatShir** [comment]
It's a bug. It displays the wrong the price here as @maofree says.

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

I think this issue is related to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20409
What do you think?

Thanks!

**Comment by Progi1984** [comment]
Fixed by #24427
