### ISSUE TITLE
#hasbiallah 

### ISSUE THREAD

**Issue by Kucing121** [PrestaShop/PrestaShop#24199]
#### Is your feature request related to a problem?

A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."

#### Describe the solution you'd like

A clear and concise description of what you'd want to happen.

**Comment by Kucing121** [comment]
#hasbiallah

**Comment by hibatallahAouadni** [comment]
Hello @Kucing121 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
