### ISSUE TITLE
Prestashop 1.7.7.0 runs very slowly untimely

### ISSUE THREAD

**Issue by elodie66000** [PrestaShop/PrestaShop#24193]
Hello,

on a prestashop 1.7.7.0 with purchased theme.

The site is abnormally between each category but a few times during the day otherwise it is untimely.

https://hkboutik.fr/

After multiple tests on one discovered that it came from initcontent and too important mysql requests.

thank you

php 7.3
![INDEX](https://user-images.githubusercontent.com/29275423/115931352-43cf4a80-a48b-11eb-9837-9c9d96cc2d0b.png)
![inicontent trop lent](https://user-images.githubusercontent.com/29275423/115931355-4467e100-a48b-11eb-9f6d-a81ce7aed48b.png)
![init](https://user-images.githubusercontent.com/29275423/115931357-45007780-a48b-11eb-8a1a-0768cc4d100a.png)
![lenteur](https://user-images.githubusercontent.com/29275423/115931358-45007780-a48b-11eb-8fcd-b928189eaa1b.png)
![screen droite 1](https://user-images.githubusercontent.com/29275423/115931360-45990e00-a48b-11eb-8dab-aefb98d44fae.png)

**Comment by hibatallahAouadni** [comment]
Hello @elodie66000 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by CarlysG** [comment]
Hola  @elodie66000  encontraste solucion??
