### ISSUE TITLE
Change wording when editing the price of a product  that appears multiple time in an order

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#24191]
#### Is your feature request related to a problem?

The same products but with a different customization can appear multiple times in an order.
If the user edits the price of one of the products, it will apply to all identical products.
Right now, the wording is not clear enough as it mentions 'invoices'. But the situation can happen too even if no invoices has been generated yet. 

See https://github.com/PrestaShop/PrestaShop/pull/23902#issuecomment-821232486

#### Describe the solution you'd like

Change the wording to let the merchant know that editing the price of a product will apply to all identical products of the order.

title= 'Edit the price' in Admin.OrdersCustomers.Feature
confirm_message= 'Are you sure you want to edit this product price? It will be applied to all identical products in this order.'
Exit buttons: 'Cancel' in Admin.Global and 'Edit' in Admin.Global

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24253
