### ISSUE TITLE
Problème page produit qui n'apparaît plus

### ISSUE THREAD

**Issue by patricecarrier** [PrestaShop/PrestaShop#24192]
Bonjour la communauté,

Site : https://lepetitfreshy.fr/

Problème :
Tout fonctionnait bien puis d'un coup la page boutique espace pro n'est plus accessible.
Dans les logs, il y a des fichiers qui ont été modifiés, pas par moi pour le coup :
LICENSES
classes/Product.php
classes/Cookie.php
classes/module/ModuleGraph.php
controllers/front/OrderController.php
js/jquery/plugins/jquery.validate-creditcard.js
js/jquery/plugins/alerts/jquery.alerts.css
js/jquery/plugins/alerts/jquery.alerts.js
js/jquery/plugins/jstree/jquery.jstree.js
js/jquery/plugins/jstree/themes/apple/style.css
js/jquery/plugins/jstree/themes/classic/style.css
js/jquery/plugins/jstree/themes/default/style.css
js/jquery/plugins/jstree/themes/default-rtl/style.css
js/jquery/plugins/smartWizard/jquery.smartWizard.js
js/jquery/plugins/treeview-categories/jquery.treeview-categories.async.js
js/jquery/plugins/treeview-categories/jquery.treeview-categories.sortable.js
src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php
vendor/doctrine/orm/lib/Doctrine/ORM/Query/AST/Functions/ConcatFunction.php
vendor/mrclay/minify/min/builder/jquery-1.6.3.min.js
vendor/mrclay/minify/min/lib/Minify/DebugDetector.php
vendor/mrclay/minify/min/lib/Minify/CSSmin.php
vendor/mrclay/minify/min/lib/Minify/CSS.php
vendor/mrclay/minify/min/lib/Minify/HTML.php
vendor/mrclay/minify/min/lib/Minify/ImportProcessor.php
vendor/mrclay/minify/min/lib/Minify/CSS/Compressor.php

Avant les appels css et js étaient basiques. Maintenant, concaténation des js et des scripts et depuis j'ai l'impression que ça déconne. Quand on clique sur espace pro, on devrait arriver au formulaire de connexion (ce qui était le cas). Maintenant, ça renvoie vers mon compte et la boutique pro n'affiche plus rien.

Si quelqu'un a une idée je suis preneur.

Cordialement

Patrice

Regardez le lien en bas de la page (celle vers laquelle on devrait aller) :
![Capture d’écran 2021-04-23 à 18 41 38](https://user-images.githubusercontent.com/80974055/115903284-b3314400-a463-11eb-89da-d361f552f736.png)

On est envoyé sur le compte et lma boutique pro est inaccessible.
![Capture d’écran 2021-04-23 à 18 41 51](https://user-images.githubusercontent.com/80974055/115903311-b62c3480-a463-11eb-8370-a2692bf8a6b7.png)

**Comment by matks** [comment]
Bonjour @patricecarrier 

Je suis désolé, ce repository GitHub est utilisé uniquement pour soumettre des rapports de bug ou des demande de nouvelles fonctionnalités, pas pour des demandes d'aide.

Je vous recommande de rechercher de l'aide sur le forum communautaire https://www.prestashop.com/forums/forum/18-forum-francophone/ ou à souscrire à une offre de support de la société de PrestaShop https://www.prestashop.com/fr/support

Bonne soirée,
