### ISSUE TITLE
Same carrier name is not included in payment preferences which causes "No payment method available message"

### ISSUE THREAD

**Issue by arturas-bes** [PrestaShop/PrestaShop#24190]
Related issue: #20023
#### Describe the bug

I was investigating an issue when while selecting some country, payment method are not available
When going deeper I figured that its not a preference settings problem
After that I noticed that, carrier is missing in my payment preferences which had a duplicate name(as carrier name is not translatable)
After I changed carrier name It appeared in payment preferences and payments started to work in front office aswell

Other notes:

I'm not sure if it is related but before migrating shop to new server everything worked correctly and after that it broke down
We were discussing that it could be related to different database previous server had mysql 8 which worked perfectly and migrated server has 5.7, but overall it is not related as carrier name does not have requirement to be unique

#### Expected behavior

Carriers are visible in payment preferences
Payment methods are available in front office

#### Steps to Reproduce

1. create carriers with the same name(in my case it was DPD module which has pickup and courier, both of them were named DPD)
2. go to payment preferences and notice that one of the carriers is missing
3. go to front office and switch between addresses(different countries, in my case most of the countries were disabled and only few were enabled, aswell custom carrier zones created)

**Screenshots**

As issue is fixed now, I do not have any screenshots

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2/7.1 tried both

Related issue: #20023

**Comment by hibatallahAouadni** [comment]
Hello @arturas-bes 

I didn't manage to reproduce your issue with PS1.7.7.3, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116066854-cec96400-a688-11eb-90ff-2c4d59a9a3a4.png)

It seems this issue has been fixed #11379. So, I close this issue :wink: 

Thanks!
