### ISSUE TITLE
statsforecast shows no data

### ISSUE THREAD

**Issue by axl89** [PrestaShop/PrestaShop#24206]
#### Describe the bug

When visiting the `index.php?controller=AdminStats&module=statsforecast&token=xx` section of the BO (named Panel de control de Estadísticas in Spanish, Statistics Dashboard in English I guess), I've got a weird behavior since a couple of months where the **Views** and **Registrations** columns shows zero, but I know this info is not correct because I still have purchases (see the **2021-02-09 day** in the screenshots section), and are shown in the other columns.

#### Expected behavior

The BO should be able to display info on the first two columns (Visits and Registers) or to provide some troubleshooting links if they are zero, since it's not really clear how to troubleshoot this.

#### Steps to Reproduce

1. Log in to the back office
2. On the left menu, go to the Statistics section (I have it in Spanish, so I believe it should be statistics; it shows `subtab-AdminStats` in the HTML if it can help)
3. Click on Statistic Panel Control (again, I have it in Spanish, and the HTML section is `index.php?controller=AdminStats&token=xx&module=statsforecast`
4. See zero data since a specific data (6th Feb 2021)

**Screenshots**

![image](https://user-images.githubusercontent.com/939418/116009183-6478db00-a618-11eb-8f79-daa22beb79b7.png)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment]
Hello @axl89 

You need to downgrade your PHP version to 7.2 cause PS1.7.6.1 is not compatible with PHP 7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).
Please check and feedback.

Thanks!

**Comment by axl89** [comment]
Hi @hibatallahAouadni , thank you for the quick response! I guess it's either that or upgrading Prestashop to the 1.7.7 version. I'll check the CHANGELOG's to see if there are any breaking changes and take a decision based on that :)

**Comment by hibatallahAouadni** [comment]
@axl89 ok waiting for your feedback :wink:

**Comment by hibatallahAouadni** [comment]
Hello @axl89 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
