### ISSUE TITLE
1-Click Upgrade Module 

### ISSUE THREAD

**Issue by Addsuk** [PrestaShop/PrestaShop#24205]
Hi,
I'm looking for the link to download the 1-Click Upgrade Module however it's not found on the website https://addons.prestashop.com/en/data-migration-backup/5496-1-click-upgrade.html?_ga=2.105628100.632139739.1619355143-2109554453.1619355143 

How can I download this?

**Comment by matks** [comment]
@Addsuk you can download it from your Back office (visit the page Modules Catalog). Else here https://github.com/PrestaShop/autoupgrade/releases/tag/v4.12.0 it's ZIP autoupgrade-v4.12.0.zip

**Comment by hibatallahAouadni** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: Thanks @matks for your quick reply :rocket: 

Thank you
