### ISSUE TITLE
Error when using delete request in back office

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#24209]
#### Describe the bug

Error when using delete request in back office

#### Expected behavior
It shouldn't be possible to delete something using sql manager in back office

#### Steps to Reproduce

1. Go to admin -> database (with mode debug off)
2. Add a sql request using delete and save
3. Execute this request
4. See error and check in database that the request is executed.
--------------------------------------------------------------------------
1. Go to admin -> database (with mode debug on)
2. Add a sql request using delete and save
3. Execute this request
4. See error and check in database that the request isn't executed.

Before the migration it wasn't possible to save delete request.

**Screenshots**

Before migration (<1.7.6.0)  : https://drive.google.com/file/d/1QY8vPiWKlDbHPiwScdxyPk7ztL4Uoe-a/view
After migration (>1.7.6.0) : https://drive.google.com/file/d/17PTrAf2gqiM7dyQ_x1gJScsVrZXW44nZ/view

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.3, 1.7.8.x, develop
* PHP version: 7.1

**Comment by marionf** [comment]
@sarahdib I am not sure about the critical severity here, if it's critical it means we should fix it in 1.7.7.4

**Comment by PierreRambaud** [comment]
FYI, the main problem was about it was allowed to create request other than a SELECT.
Before the migration you were only able to execute SELECT as it is defined in the notice inside the page. I restore the normal behaviour.

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #24217
