### ISSUE TITLE
ps_shoppingcart: backdrop click and keymap

### ISSUE THREAD

**Issue by matteocostantini** [PrestaShop/PrestaShop#24208]
Hi,
I've a problem. the ajax shopping cart feature is enabled. I'm using a classic_child theme.

When click add-to-cart button , modal is open, perfect!! but i want to costraint press buttons, avoiding close modal by clicking background or by pressing keyboard.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @matteocostantini 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
