### ISSUE TITLE
Impossible to create a refund

### ISSUE THREAD

**Issue by copostic** [PrestaShop/PrestaShop#24210]
#### Describe the bug

I'm trying to refund a product on an order that I created on my BO and that is on "Payment accepted" status (same for "Shipped") but I have an error:

> Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0] : Warning: Invalid argument supplied for foreach().

#### Expected behavior

Item should be refunded.

#### Steps to Reproduce

1. Create an order from backoffice with one product.
2. Go to this order's details page.
3. Click on "Standard refund" button.
4. Check the product to set Quantity to 1.
5. (Checkbox "Generate a refund slip" should be checked) - Click on "Standard refund"
6. Error mentionned above is shown and order is not refunded

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

Thanks !

**Comment by copostic** [comment]
I disabled debug mode and deleted logs and it works...
Is this a known issue ?

**Comment by hibatallahAouadni** [comment]
Hello @copostic 

I didn't manage to reproduce your issue with PS1.7.7.3 but it seems a cache problem.
Well, glad to hear that it works for you now after deleting logs :tada: 
I close this issue :wink: 

Thanks!
