### ISSUE TITLE
Issue with prices rounding & the differences in prices when placing an order

### ISSUE THREAD

**Issue by pearpl** [PrestaShop/PrestaShop#24216]
#### Describe the bug & Steps to Reproduce

The issue is related to how presta handle prices. 
Presta store product price as net price
We have two type of products but the bug appear in both cases 
Example 

Product net price is: 103.930000
Product gorss price is: 127.8339  (calculated by presta)
TAX 23%

The client order 19 pcs of  the product
As result in summary for the order is: 2 428,84 
The amount is based on [product net] x [amount] x [tax] = [total]
Data to that calculation are from ps_product or ps_product_lang which store value with more than 2 decimals

Also in the order summary, we have a list of purchased items with a summary which is from 
ps_order_details where product prices are stored in 2 decimals only. 
That's why instead of 2 428,84 we get 2 428,77  = where we have 0,07 difference. 

The same issue happens if instead of the net price you use gross price adding new product
ps_product and ps_product_lang store the price with more than two decimals where the ps_order and ps_order_details store only 2 decimals yes it add more zeros after the last number but it cut everything after the second decimal 

#### Steps to Reproduce
Add the product that has 

> Product net price is: 103.930000
> Product gorss price is: 127.8339  (calculated by presta)
> TAX 23%

Order 19 items of the product

#### Additional information

* PrestaShop version:  1.7.6.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @pearpl 

It seems your issue similar to these #9815 & #9779 and we're already have a whole EPIC #19445 for the rounding issues.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @pearpl ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
