### ISSUE TITLE
Purchase order module is not displaying in PS 1.7.7.3

### ISSUE THREAD

**Issue by Dinesh-Gunasekaran** [PrestaShop/PrestaShop#24214]
#### Describe the bug

I implemented a module called Purchase Order which contains an input field and when it's filled, it will be written in the product bill. The module was available on AdminOrder. It was working until 1.6.6.9 version, but since the PS 1.7.7.3 update, the module is not displaying anymore. I tried to use all the listed AdminOrder hooks for positioning in PS 1.7.7x but none seem to work and the content always goes to the bottom of the AdminOrder section. The hooks in AdminOrder are not working. 

#### Expected behavior

I don't have any screenshots of previous module but there should be an input field with a button and the submitted value should be displayed on the purchase invoice. 

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on any order
3. Scroll down to the bottom

**Screenshots**
![2021-04-20_10h36_08](https://user-images.githubusercontent.com/83217747/116085011-acdadc00-a69e-11eb-9101-ac17e595a08b.png)

I tried to display a simple message instead of the module itself but it always displays here, I tried to move it with `displayAdminOrderSideBottom` and `displayAdminOrderMainBottom`.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7

**Comment by matks** [comment]
Hello @Dinesh-Gunasekaran  this is expected, the Orders Back Office pages have been migrated to Symfony in PrestaShop 1.7.7 .

New replacement hooks are detailed on https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/

New orders listing page, as well as other migrated pages, uses `Grid` component, you can read more about it, and how to work with it in modules here:

https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/modify-grid-in-module/

**Comment by hibatallahAouadni** [comment]
Hello @Dinesh-Gunasekaran 

I think you've got your answer from the expert :wink: 
So, I close this issue. Feel free to open a new one when it's needed.

PS: thanks @matks for your quick reply :superhero: 

Thanks!
