### ISSUE TITLE
Unable to login to backend panel

### ISSUE THREAD

**Issue by jayamarunr** [PrestaShop/PrestaShop#24218]
#### Describe the bug

Unable to log in to the backend panel of the website. Here is the link.
https://mydreambath.co.uk/bathstore/index.php?controller=AdminDashboard&token=d68496b377b9aa6177581c0237fa4d1b

We tried updating a couple of plugins and all of us sudden the website stopped working. Its been more than 5 days we are getting HTTP ERROR 500

#### Expected behavior

We want to log in and update products and check out orders received. Our business is stuck.

#### Steps to Reproduce

1. Go to 'https://mydreambath.co.uk/bathstore/index.php?controller=AdminDashboard&token=d68496b377b9aa6177581c0237fa4d1b'
2. Click on 'HTTP 500 ERROR'

**Screenshots**

<img width="1278" alt="Screenshot 2021-04-26 at 11 17 53 PM" src="https://user-images.githubusercontent.com/83112248/116127586-a3289700-a6e5-11eb-9057-7bc4f865b583.png">

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @jayamarunr 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you!
