### ISSUE TITLE
 Prestashop backend shows blank page

### ISSUE THREAD

**Issue by kernig** [PrestaShop/PrestaShop#24226]
Hello,

we have occasional problems to reach our Prestashop backend. 
When calling the backend, we are shown a white page. We have noticed that empty index.php files are created repeatedly. If these are removed, we can access the backend as usual. 
In the log we get the following error.
PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: Expected to find class "PrestaShopBundle\\Controller\\Admin\\Sell\\index" in file "URLPLACEHOLDER/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "URLPLACEHOLDER/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource. in URLPLACEHOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:157
Stack trace:
#0 URLPLACEHOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(57): Symfony\\Component\\DependencyInjection\\Loader\\FileLoader->findClasses('PrestaShopBundl...', '/var/www/vhosts...', '/var/www/vhosts...')
#1URLPLACEHOLDER/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 168
We are currently using Prestashop version 1.7.7.3 with the Leoneons theme.

**Comment by hibatallahAouadni** [comment]
Hello @kernig 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
