### ISSUE TITLE
Add customers invoice and delivery phone number to the email-alerts

### ISSUE THREAD

**Issue by drwebbe** [PrestaShop/PrestaShop#24224]
#### Is your feature request related to a problem?

Customers often make mistakes when ordering. We need to go to the backoffice to find the customers phone numbers to contact them.

#### Describe the solution you'd like

Would be easier if the customers phonenumbers would be added to the email-alerts.

#### Alternatives you've considered

None
#### Additional context

None

**Comment by hibatallahAouadni** [comment]
Hello @drwebbe 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Hlavtox** [comment]
Hi, this feature is already implemented in ps_emailalerts. If you don't see phone number in your addresses, adjust the address format in country settings and you will see it. ;-)
