### ISSUE TITLE
Admin Error 500, Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#24238]
Hi!
Suddenly I have an issue, I can't access Admin -> Customers on Prestashop 1.7.6, this is the route of the link in the admin:
...admin/index.php/sell/customers/?_token=-xxx

When I try to access it returns an Erro 500. so I asked my hosting to give me more details and this is what they sent me:

```
[client] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /admin/override/controllers/admin/AdminStatsController.php on line 594\n', referer: https://.....admin/index.php?controller=AdminOrders&token=xxx
[Thu Apr 15 11:36:29.770906 2021] [proxy_fcgi:error] [pid 1795737] [client] AH01071: Got error 'PHP message: PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /admin/var/cache/prod/smarty/compile/38/04/d6/3804d6501a11bd32c1cc4ca6489fb41ee534109b_0.file.view.tpl.php on line 1811\nPHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /admin/var/cache/prod/smarty/compile/38/04/d6/3804d6501a11bd32c1cc4ca6489fb41ee534109b_0.file.view.tpl.php on line 1816\nPHP message: PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /admin/var/cache/prod/smarty/compile/38/04/d6/3804d6501a11bd32c1cc4ca6489fb41ee534109b_0.file.view.tpl.php on line 1819\n'
```

My hosting trying clearing cache but didn't solve the issue

The files affected on this error report (which I'm not sure they have anything to do with the actual problem) are an override of AdminStatsController (where I only replaced "invoice_date" with "date_add" for [this reason](https://www.prestashop.com/forums/topic/367885-dashboard-stats-are-empty-after-upgrading-to-1609/)). And then the other file I just renamed /admin/var/cache/ and nothing happens

Hope somebody knows what's going on! thanks for the help

**Comment by hibatallahAouadni** [comment]
Hello @omar2886 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you check this [link](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+%22PHP+Warning%3A+Invalid+argument+supplied+for+foreach%28%29%22+is%3Aclosed), it list all the issues similar to yours, you may find some infos that could help you :wink: 

Thanks!
