### ISSUE TITLE
New blockwishlist module website performance problem

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#24255]
#### Is your feature request related to a problem?

New wishlist module contains huge javascript bundles that hurt website performance.

#### Describe the solution you'd like

We can extract big vendors from bundles into separate files.

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
And thanks for your PR :rocket: 

Ping @kpodemski wdyt of this issue and the PR?

Thank you

**Comment by kpodemski** [comment]
@hibatallahAouadni we talked with @Oksydan about this issue some time ago, what Oksydan did is definitely worth to have in module, PR is now on QA so let's hope for good feedback from them 👍
