### ISSUE TITLE
[Experimental product page] Fix user interface

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24259]
### Describe the bug

The UX team explored the experimental product page and reported many issues. We need to fix them.

Items to be fixed have been provided to @NeOMakinG.

#### Additional information

* PrestaShop version: `1.7.8.x`

**Comment by jolelievre** [comment]
Here is some feedback from @TristanLDD that need to be addressed in this PR:

- [x] Aligner champs prix -> onglet basic
- [x] Aligner tooltip product type
- [x] Bouton edit on expérimental product page -> primary outline
- [x] Agrandir champs prix pour harmoniser avec champs texte
- [x] Ajouter 15px d’espacement entre message d’info et champs associé
- [x] Ajouter message info sous Target category
- [x] Ajouter la possibilité d'avoir des alertes expandable
- [ ] Bug affichage input texte tiny MCE
- [x] Place holder vide dans options > dropdown visibility
- [x] Corriger espace entre champ tags et sélecteur de langues
- [x] Switcher la langue par défaut dans customization 
- [x] Ajouter le confirm de delete customization
- [x] Ajouter un tooltip sur l’icône delete customization 
- [x] Remettre un tooltip sur l’icône delete combination
- [x] Empty State -> bouton generate (après le merge du generateur)  
- [x] Passer en bleu le bouton de confirm du changement de type
- [x] Passer tous les tooltips en hover 
- [x] Passer les messages info en 2/3 du full width 
- [x] Footer réussir à aligner les boutons correctement à gauche et à droite (si possible grâce à une classe qu'on pourrait utiliser dans le FormType pour avoir autant d'éléments que l'on veut à droit et à gauche)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24076

@jolelievre can you confirm all the items in the list above are fixed?

**Comment by jolelievre** [comment]
@matks everything listed has been fixed yes, except the tinymce bug But it's not related to the form theme, so it should be fixed in a dedicated PR
