### ISSUE TITLE
[Experimental product page] Fix raw bugs

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24258]
### Describe the bug

The QA team explored the experimental product page and reported many raw bugs. We need to fix them.

#### In Edit a Product experimental BO page

When saving the form in product not virtual an error related to virtual_product_file_id always popped
When switching to combination type and error related to missing stock form always popped
When switching types to combination an error indicating that extra fields were present prevented from validating the form and really save the modification

#### In Create a Product experimental BO page

All fields should ne correctly prefilled so the only error you should have when creating a new product is the missing default name (if absent of course)
When you switch the type in creation you should have a modal to force you to submit the form to confirm this modification (unlike the edition page no extra warning is displayed as it's not useful for an empty/new product)

#### Additional information

* PrestaShop version: `1.7.8.x`

**Comment by Progi1984** [comment]
Fixed by #24168
