### ISSUE TITLE
"Display tax in the shopping cart" setting should also affect 

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#24256]
If you want to use taxes on your shop, but you don't want to show "tax incl." or "tax excl." text next to prices, you have to set this setting to NO:
International >> Taxes >> Tax options >> Display tax in the shopping cart >> NO

But the carrier section on checkout page ignore this setting, so next to the carrier prices, you'll see tax incl. and tax excl. labels, despite what your configuration..

The only way to hide them it's to modify core file "/classes/checkout/DeliveryOptionsFinder.php" because these texts are hardcoded into it (f.e. %price% tax incl.).

I think you should consider make this setting affect on taxes displayed on checkout carrier section.

* PrestaShop version: all 1.7 versions
* PHP version: -

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
