### ISSUE TITLE
[Add support for experimental features] Fix modal behavior in Experimental Features BO Page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24267]
This issue is an item in the [Add support for experimental features](https://github.com/PrestaShop/PrestaShop/issues/23235) project

You can read about the project [here](https://github.com/PrestaShop/PrestaShop/issues/23235).

There is a confirmation modal that opens when you modify the BO Experimental Features page buttons.

## Stories

Updated after discussions https://github.com/PrestaShop/PrestaShop/pull/24052

#### Scenario X1: disable 'save' button until something has been modified
AS a merchant
WHEN I Install PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page
AND there is 2 feature flags on the page, one enabled `Feature Flag A` and one disabled `Feature Flag B`
THEN SAVE button is disabled

#### Scenario X2: do not show the confirmation modal if flags were disabled
AS a merchant
WHEN I Install PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page
AND there is 2 feature flags on the page, one enabled `Feature Flag A` and one disabled `Feature Flag B`
WHEN I disable `Feature Flag A`
AND I click SAVE
THEN the confirmation modal should not open

#### Scenario X3: show the confirmation modal if flags were enabled
AS a merchant
WHEN I Install PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page
AND there is 2 feature flags on the page, one enabled `Feature Flag A` and one disabled `Feature Flag B`
WHEN I enable `Feature Flag B`
AND I click SAVE
THEN the confirmation modal should open

#### Scenario X4: do not show the confirmation modal if flags were enabled then disabled again before submit button is clicked
AS a merchant
WHEN I Install PrestaShop 1.7.8
AND I open the Back Office 'Experimental Features' BO page
AND there is 2 feature flags on the page, one enabled `Feature Flag A` and one disabled `Feature Flag B`
WHEN I enable `Feature Flag A`
THEN I disable again `Feature Flag A` so I restore the flags situation to the initial state
AND I click SAVE
THEN SAVE button is disabled

**Comment by MatShir** [comment]
LGTM !

**Comment by matks** [comment]
> LGTM !

Hello @MatShir we have a question about this issue. @atomiix and I disagree about the desired behavior for the following usecase:

What happens if user opens the page, then wants to submit? This means he did not modify any data, he just opens the page then clicks the "save" button although he did not modify the settings?

- should the user be prompted the modal or not?
- should we allow the user to hit "save" and should we disable the "save" button until the user modifies something in the page?

You can see different opinions on https://github.com/PrestaShop/PrestaShop/pull/24052#discussion_r623858314 we are waiting for the Product Team answer

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24052
