### ISSUE TITLE
[Experimental product page] Add missing 'Remove' feature for combinations listing

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24260]
### Describe the bug

The QA team explored the experimental product page and reported that 'Remove' feature for combinations listing is missing.

You should be able to click on the remove icon. A confirm modal will ask you if you are sure, if you click on yes the combination is removed and the list is updated.

If you remove the default combination the first one in the list is the new one

#### Additional information

* PrestaShop version: `1.7.8.x`

**Comment by Progi1984** [comment]
Fixed by #24134
