### ISSUE TITLE
Problems with scaled discounts

### ISSUE THREAD

**Issue by kernig** [PrestaShop/PrestaShop#24264]
Hello,
we are currently using Prestashop version 1.7.7.3 with the Leoneons theme.
We noticed that when a new reduced price is created for a quantity of one item (this new price is a limited time offer), 
the reduced prices for e.g. a quantity of five items is no longer displayed correctly in the quantity discount table in the frontend.
The error always occurs when we use discounts excl VAT.

To replicate:

In the item, under Price, a gross price of 12€ is set. In the Net price field, the value of 10.084034€ is now displayed.
After clicking on the "Special prices" button, the checkmark "Keep price" will be removed when the price is affected. 
In the field Net item price the new reduced price is shown. In our case a price of 9.663866€.
A current date is entered in the "available from" and "to" fields. No change is made under Apply discount.
Then click on the "Apply" button. 

In the next step, the "Add special prices" button is clicked again.
The new net price and a quantity of 5 is entered. 
For the discount, a value of 1€ is entered and for the VAT the option "plus VAT" is selected.  

In the frontend, however, there are inconsistencies in the display of the price and the display in the quantity discount table.
The price for 5 pieces is shown with 10,31€, but in the table there is a value of 8,82€.

Our question now would be how does this error occur and how can it be fixed.

**Comment by hibatallahAouadni** [comment]
Hello @kernig 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
