### ISSUE TITLE
Problem with email translations, every time I modify an email the system loads the emails of the core and not of the currently used theme

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#24278]
Hi,
every time I modify an email content the system loads the emails of the core and not of the currently used theme
Go to...
1 - International
2 -Translations

<img width="365" alt="Schermata 2021-04-30 alle 11 16 10" src="https://user-images.githubusercontent.com/28685316/116675314-fe88ac80-a9a5-11eb-81ba-9c6fad013b7e.png">

3 - Type of translation: **email translations**
4 - Select the type of email content: **Body**
5 - Select your theme: **theme currently in use**
6 - Select your language: **language currently in use on the site**

<img width="1128" alt="Schermata 2021-04-30 alle 11 18 24" src="https://user-images.githubusercontent.com/28685316/116676017-c766cb00-a9a6-11eb-9e2e-974651d41be0.png">

Click on **Modify**
Now choose any **core emails** to edit, for example **preparation** 
7 -  **preparation** 
8 - click on **Edit HTML version**

<img width="1195" alt="Schermata 2021-04-30 alle 11 19 01" src="https://user-images.githubusercontent.com/28685316/116676439-44924000-a9a7-11eb-9c45-786fea7b428f.png">

9 - Just put some text
10 - Save and stay

<img width="1351" alt="Schermata 2021-04-30 alle 11 19 13" src="https://user-images.githubusercontent.com/28685316/116676640-83c09100-a9a7-11eb-9c13-0ed872e3e719.png">

After that, reloaded the page, click again on
11 - **core emails**

<img width="1386" alt="Schermata 2021-04-30 alle 11 31 37" src="https://user-images.githubusercontent.com/28685316/116677206-398bdf80-a9a8-11eb-88a6-2eb2f6037a03.png">

12 - scroll to choose the mail **preparation** template again
13 - no changes appears meaning that the system did not leave us on the theme mail templates in use but took us to the core one.

<img width="1329" alt="Schermata 2021-04-30 alle 11 36 14" src="https://user-images.githubusercontent.com/28685316/116677700-ccc51500-a9a8-11eb-9ead-ab89ff12210a.png">

I'm waiting for your kind response.
Thanks a lot.
Balla

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @ballashop ,

Your issue is similar to be : https://github.com/PrestaShop/PrestaShop/issues/14182
It is fixed in PS 1.7.8.

Please check and feedback.

**Comment by ballashop** [comment]
Ok thanks a lot.
Balla

**Comment by florine2623** [comment]
Duplicate of #14182
