### ISSUE TITLE
Module `dashtrends` position during install

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#24271]
#### Describe the bug

The `dashtrends` module is displayed last in the home page on the backoffice.

#### Expected behavior

The `dashtrends` module must be displayed first

![image](https://user-images.githubusercontent.com/16455155/116564266-18be7e00-a905-11eb-93e0-aa5cb84b6046.png)

#### Steps to Reproduce

1. Go to Admin dashboard controller
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16455155/116563490-5c64b800-a904-11eb-9811-d1d0ae44e4e5.png)

#### Additional information

* PrestaShop version: `>= 1.7.7.x`
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thanks for your issue and your PR :rocket: 
I manage to reproduce the issue with PS1.7.7.3 and PS1.7.7.0 but I didn't manage to reproduce with PS1.7.6.7.
So, it's a regression!

Thanks!

**Comment by Progi1984** [comment]
Fixed by @PululuK in #24272
