### ISSUE TITLE
BO - Add new Order page - We can add to the cart an out of stock not allowed customized product 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24281]
#### Describe the bug

In the BO > Add new orders page > we can create an order with customized product with quantity ordered > Quantity total, but It is not allowed.

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page
2. Choose a customer
3. Try to add the demo customized product (demo_14) with quantity = 200
4. Click add to cart again 
![image](https://user-images.githubusercontent.com/16067358/116693804-b1fd9b00-a9be-11eb-8460-d38c6b592197.png)
5. See error => product successfully added to the cart
![image](https://user-images.githubusercontent.com/16067358/116693942-e3766680-a9be-11eb-86e2-e36b621671cd.png)
6. Choose a payment and status and create the order
7. The order well created and the available of the product < 0 => NOK
![image](https://user-images.githubusercontent.com/16067358/116694032-0739ac80-a9bf-11eb-80a2-b692211a8603.png)

#### Additional information

* PrestaShop version: 1.7.6.9, 1774build1
* PHP version: 7.2

**Comment by Hlavtox** [comment]
Hi @khouloudbelguith, this is expected behavior. Limitations do not apply to backoffice order to allow merchant overcoming what customer can't do.
