### ISSUE TITLE
FO - the error alert is not well displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24284]
#### Describe the bug

the error alert is not well displayed and it seems the header overlap the alert

#### Expected behavior

it should be well displayed as 1.7.7.3 (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/116699897-6c44d080-a9c6-11eb-85cf-5bdce318990f.png)

#### Steps to Reproduce

1. in BO, create a product with available qty 50
2. Access to this product's page in FO
3. Set the qty to 50 and add to the cart 
4. Proceed to checkout
5. Try to increment the product qty
6. See error (see the attached screenshot below)

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/116700178-c9d91d00-a9c6-11eb-9cc7-7a6d8edb1038.png)

#### Additional information

* PrestaShop version: develop & 1.7.8.x
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Ping @prestascott as discussed on Slack, here's the issue :wink:

**Comment by prestascott** [comment]
Hey @hibatallahAouadni,

Thanks for your report! 

In 1.7.7.3 version, it seems that the alert is placed in the header... It shouldn't. The alert should be place between the header and the shopping cart container. 

The height of the header doesn't change.

**Comment by hibatallahAouadni** [comment]
Hello @prestascott 

> In 1.7.7.3 version, it seems that the alert is placed in the header... It shouldn't.

Even with PS1.7.6.7 and PS1.7.4.1, the alert has been always placed in the header :sweat_smile: 

> The alert should be place between the header and the shopping cart container.

You're right! So, it should be displayed like this (for exemple, I'm not a pro :sweat_smile: ):

![image](https://user-images.githubusercontent.com/23308427/116865275-9df9a980-ac09-11eb-8fa8-8f657de1f57b.png)

Please check and feedback.
Thanks!

**Comment by prestascott** [comment]
@hibatallahAouadni Great mockup! 

I forgot to mention, but the sticky alert must have the same width than your previous screenshots. 
It needs to be aligned with the "Shopping cart" container.
