### ISSUE TITLE
Not all products are indexed

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24299]
Hello,

There is 10011 products in my shop, only half part are indexed.

![image](https://user-images.githubusercontent.com/4645967/116823747-84fbe480-ab86-11eb-908e-6f8217a68e47.png)

I tried both options, "Add to the index, the missing products", and "Rebuild the whole index", both operation succeed but they are still many missing products.

 

In all cases, i got only 4444 articles in the index. They are all visible  ( i did a `SELECT * FROM ps_product WHERE visibility = 'none';` ).

 

Did i miss something ?
 
I tried to enable debug mode but they are nothing relevant.

## Stranger things
However, WHEN i go on an no-indexed product, and i click to the save button WITHOUT CHANGE ANYTHING, the product is added to the index.

Then the indexed article up to 4445. 

But when ia click on "rebuild index", the product disapear from the index and the count go down to 4444.

 
What are your suggestion to make the indexer works ?

## Environment

PHP: 7.3
Prestashop version: 1.7.7.3

![image](https://user-images.githubusercontent.com/4645967/116823790-d2785180-ab86-11eb-8d6d-1c28f5626257.png)

Thank you for your answers.

## Tested environment

MySQL 5.6 & 5.7
PHP: 7.3 & 7.4

Best regards

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

Could you please check this issue #15640 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by henri9813** [comment]
Hello,

Thanks for your answer,

In the product, there is a supplier:
![image](https://user-images.githubusercontent.com/4645967/116863356-77863f00-ac06-11eb-800f-c807e24a6bd7.png)

What can i check to help you in your research ?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

> If a product is indexed and we assign a default supplier it disappears from the index, if we reconstruct the index and in the same product we make a preview it also disappears.

It seems your products are not indexed cause they are assigned to a default supplier.
So, your issue is a duplicate to this one #15640

> What can i check to help you in your research ?

Try removing the default supplier assignment from a product, then reindex and check if the product has been added to the index.
Please check and feedback.

Thanks!

**Comment by henri9813** [comment]
Hello,

I removed the supplier from the product: 
![image](https://user-images.githubusercontent.com/4645967/116866265-62f87580-ac0b-11eb-84ac-70626b217c4c.png)

However, after the rebuilt of the whole index, the product is still not indexed.

Thank you

**Comment by henri9813** [comment]
In addition, all my products use the same supplyer, i have only one supplier

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

Thanks for your patience :pray: 
I couldn't reproduce the issue, could you please provide clear and concise steps to reproduce.

Thanks!

**Comment by henri9813** [comment]
Hello,

I produced the problem only with a precise set of prodocts.

Hovewer, i can send you a .sql file to import and to reproducE ?

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

> Hovewer, i can send you a .sql file to import and to reproducE ?

Yes, please :pray: 

Thanks!
