### ISSUE TITLE
date and time error when making refunds

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#24296]
#### Describe the bug

when you make a refund, the date of the refund is wrong

#### Steps to Reproduce

1. Go to make any refund
2. See the error in the date and time

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/116798488-24ba6380-aaf0-11eb-8937-d4ac181f082d.png)

#### Additional information

I made the purchase on 05-02-2021 at 02:27:21 and the refunds the same day on 05-02-2021 at 02:28:48 and the second refund at 02:40:23

* PrestaShop version: 1.7.7.3
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

It seems that your issue is not a PrestaShop core bug.
If your module is PrestaShop Checkout Official, please contact support team on [Addons](https://addons.prestashop.com/fr/contactez-nous?id_product=46347)

We will close this issue.

Thanks!
