### ISSUE TITLE
the product image with combinations is not display correct

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#24292]
#### Describe the bug

The product image that have combinations (different colors) not display accordanly to their colors . Main image display all time when other colors selected. The URL change, the images below main image also change, but not the big image.
In the BO  the relevante images are applied to their colors.
Also if in the in the combinations (BO) was selected like tipical combination the image that not the main (that was apllied like main in the main setup) , in the FO when page load still appear the main image from main setup, not from combinations.
This is not the duplicate of #21775 - there problem in the cart.  

1. Go to FO to the page with combinations (for example https://te.com.ua/uk/navushniki/2649-dali-io-6.html#/6-kolir-satin_blak)
2. Click on color variants

**Screenshots**
FO

![image](https://user-images.githubusercontent.com/50954519/116776544-98695b80-aa71-11eb-8eec-08c498894f70.png)

BO

![image](https://user-images.githubusercontent.com/50954519/116776631-0dd52c00-aa72-11eb-9abd-73b4237f92d3.png)

#### Additional information

* PrestaShop version: 1.7.7.1 and 1.7.7.2
* PHP version:  7.1.33

**Comment by photinia73** [comment]
After investigation it seems that problem in my Theme ((

**Comment by matks** [comment]
> After investigation it seems that problem in my Theme ((

Unfortunately it happens 😞 .

You should reach out to the developer of the theme. It is in his best interest to fix this bug, as any customer using this theme might have it as well.

**Comment by alfonsolr09** [comment]
the problem is with prestashop, same problem in my case

**Comment by alfonsolr09** [comment]
https://youtu.be/vJC36vfO0OM
@matks @hibatallahAouadni

**Comment by photinia73** [comment]
> the problem is with prestashop, same problem in my case

The developer of my theme resolved the problem. Now Combabations work properly

**Comment by alfonsolr09** [comment]
Yes, but its a prestashop bug

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@alfonsolr09 it's not a PrestaShop bug, it's Theme bug :wink: 
Cause with default theme, I couldn't manage to reproduce.
So, please contact your theme's developer.

PS: @photinia73 thanks for your quick reply :rocket: 

Thanks!

**Comment by alfonsolr09** [comment]
@photinia73 Do you know what your template developer did to fix it?
My template developer doesn't want to help me

**Comment by photinia73** [comment]
> @photinia73 Do you know what your template developer did to fix it?
> My template developer doesn't want to help me

I don't know what exactly they did, but I paid for prolong my support, and explained, that in the default theme this bug is absent.

**Comment by photinia73** [comment]
As I can remember in old ps v 1.7.6... thr combination worked properly in my Theme. So I think that in the ps was changes (classes, id, CSS) and in the old Theme version they weren't fix. After payment the new Theme version compatibility with ps 1.7.7.3 became available for me. But I have did a lot of changes, so ask the support to repair my Theme without total upgrade.

**Comment by Oksydan** [comment]
@alfonsolr09 
Your theme probably is missing these changes https://github.com/PrestaShop/PrestaShop/commit/3ba983baa97704339c4c803e1ca6a9c97ca286d4#diff-32dcd11236f968fb8f8f7c5e410932c3cea3bf4703533e7d233061734c0234a1

**Comment by alfonsolr09** [comment]
why is the file modified?  what error was there?
@Oksydan

**Comment by Oksydan** [comment]
@alfonsolr09 
There was no error. 
Cover is not equal default_image. 
Cover always stays as cover but default_image is based on combination

**Comment by alfonsolr09** [comment]
@Oksydan in version 1.7.6.4 everything worked fine for me.
why not now if my template files haven't changed?

**Comment by alfonsolr09** [comment]
> @ alfonsolr09
> Es probable que a tu tema le falten estos cambios [3ba983b # diff-32dcd11236f968fb8f8f7c5e410932c3cea3bf4703533e7d233061734c0234a1](https://github.com/PrestaShop/PrestaShop/commit/3ba983baa97704339c4c803e1ca6a9c97ca286d4#diff-32dcd11236f968fb8f8f7c5e410932c3cea3bf4703533e7d233061734c0234a1)

@Oksydan 
it's true, that was the problem.
Thank you so much
