### ISSUE TITLE
FO - Quick view - The product image is displayed incorrectly

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24306]
#### Describe the bug

Access to FO and click on quick view, the product image is not well displayed, the width is 95% and not 100%

#### Expected behavior

the product image's width is 100%

#### Steps to Reproduce

1. Go to **FO**
2. Click on **Quick view**
3. See error => the product image looks compressed (width = 95%)

**Screenshots**

1.7.7.3 :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/116860093-4f481180-ac01-11eb-9760-44db577e7fcd.png)

1.7.8.x & develop

![image](https://user-images.githubusercontent.com/23308427/116860216-85859100-ac01-11eb-9e7e-9b75c4006f1b.png)

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
Fixing it today

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24315
