### ISSUE TITLE
actionEmailSendBefore hook can trigger infinite loop

### ISSUE THREAD

**Issue by Morerice** [PrestaShop/PrestaShop#24302]
#### Describe the bug

When a module attempts to execute this hook, there is a risk of causing an infinite loop. Consider the following flow:

1. Hook::exec()
2. Module::getInstanceByName()
3. Module::coreLoadModule()
4. ServiceLocator::get()
5. Container::doMake()
6. Container::makeInstanceFromClassName() 
7. New module instance is created.

However, if during module creation (step 7) a new log should be added, and the prestashop environment is currently configured to [send an email](https://github.com/PrestaShop/PrestaShop/blob/5d615aa6e4fca8a80929223aade271237d98c62a/classes/PrestaShopLogger.php#L172) notifying the admin about a new log, the `actionEmailSendBefore` will be called again, which will then restart this flow from the `Hook::exec()` call. This cycle will keep on going and cause an infinite loop.

#### Expected behavior
Infinite loop does not occur. This may be done by accepting another `objectType` parameter in `PrestaShopLogger::addLog`, which does not trigger the process of sending an email.

#### Steps to Reproduce

1. Enable sending emails when a new log is inserted on PrestaShop
2. Install module which registers the `actionEmailSendBefore` hook (possibly all other email hooks)
3. Call the `PrestashopLogger::addLog` function in the module's constructor
4. Infinite Loop occurs

#### Additional information

* PrestaShop version: 1.7.6.9 (All versions offering this hook should be affected)
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

Thanks for your detailed bug report!
Could you please provide a simple module which registers the `actionEmailSendBefore` hook and call the `PrestashopLogger::addLog` function, it will be easier to repropduce the issue :pray: 

Thanks in advance!

**Comment by Morerice** [comment]
Use this branch of the adyen official payment module: https://github.com/Adyen/adyen-prestashop/tree/PW-4368
To trigger the issue:
1. Install the plugin
2. Set the final parameter of [this function](https://github.com/Adyen/adyen-prestashop/blob/43fc6c91b4072e1a342f4a6db2fa5fc2ae427785/service/Client.php#L67) to `true`
3. Access the Design > Positions tab

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

I just clone the reporsitory under /modules/, then I excute this command:
`composer install --no-dev`

BO > IMPROVE > Payment > Payment methods > install adyen module
when I tried to follow this step:
> Set the final parameter of this function to true

In my file, I didn't find this parameter in this function (see my code):
```
catch (MissingDataException $e) {
            $logger->error('The API key configuration value is missing');
        }
```
Should I add it?
Please check and feedback.

Thanks!

**Comment by Morerice** [comment]
Hi @hibatallahAouadni 

Thanks for following up. You shouldn't need to add this function. Could you please confirm that you are on the branch which I linked in the previous comment? This is required since I added this function only in that specific branch for now.

Best regards,
Jean
Adyen

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

Thanks for your feedback.

1. Checkout to PW-4368 branch 
2. `composer install --no-dev`
3. Install adyen module
4. Design > Positions
5. No issues (check the screen record and screenshot below)

![image](https://user-images.githubusercontent.com/23308427/118562256-a0611500-b76c-11eb-8899-06e2bd822399.png)
https://www.awesomescreenshot.com/video/3774534?key=b074525b3afedffbe6b6cdb06c5227e6

Please check and feedback.
Thanks!

**Comment by Morerice** [comment]
Hi @hibatallahAouadni 

Thanks for providing your clear steps and and other resources. Just to be sure that everything was setup correctly on your end when the issue didn't occur, could you please verify that the `actionEmailSendBefore` hook was correctly registered by the Adyen module?

Best regards,
Jean
Adyen

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

![image](https://user-images.githubusercontent.com/23308427/118678447-51af8b80-b7fd-11eb-9a56-7d297627b8e7.png)

Should I reinstall the module?
Please check and feedback.

Thanks!

**Comment by Morerice** [comment]
Hi @hibatallahAouadni 

Sorry for not being too clear. What I meant was, in the Design > Positions page, could you check if the Adyen module is registered to the `actionEmailSendBefore` hook?

Best regards,
Jean
Adyen

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

No, it's not, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118680134-c1724600-b7fe-11eb-93b8-c8ae7248dd27.png)

Did I miss something?
Please check and feedback.

Thanks!

**Comment by Morerice** [comment]
Hi @hibatallahAouadni 

I think that in order to check for the `actionEmailSendBefore` hook you are required to select the *Display non-poisitionable hooks* checkbox.

Best regards,
Jean
Adyen

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

Thanks for your patience!
Yes, when I check **Display non-poisitionable hooks** the **Adyen** module is registered to the `actionEmailSendBefore` hook.

![image](https://user-images.githubusercontent.com/23308427/119487446-ac933680-bd59-11eb-9d60-ffdc2c64b98a.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Morerice 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
