### ISSUE TITLE
Can not add or edit product with "," on product page V2

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#24301]
#### Describe the bug
Can not add or edit product with "," on product page V2

#### Steps to Reproduce

1. Go to 'BO -> activate experimental feature
2. Click on catalog -> Product and edit a product
3. Change for exemple 13,10  by adding a number 
Same for create a new product when we add a number with ","

**Screenshots**

https://drive.google.com/file/d/12a4sOpSktwmfartXN5zA4g1Oaaal4jUh/view

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @sarahdib 

This issue has been fixed on develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/149412223-abc7beb6-882c-441a-af77-93d62da16fdc.mp4

Closing this issue!
Thanks!
