### ISSUE TITLE
BO - Orders page - The order carrier ID is invalid.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24307]
#### Describe the bug

In the BO > Orders > Order detail page, after updating a product ordered (price or quantity or price & quantity), then we try to edit the carrier => an error is displayed `The order carrier ID is invalid.`

#### Steps to Reproduce

1. Greate an order from FO and select as a carrier "My carrier" for example
2. Go to BO > Orders > View last order created
3. Try to update the product ordered (price or quantity or price & quantity)
4. In the Carriers tab, click edit the carrier and try to add a tracking number or select another carrier
5. See an error 
![image](https://user-images.githubusercontent.com/16067358/116862088-84a22e80-ac04-11eb-9f38-8d5d6684dedf.png)

PS: 1771 => ok
https://drive.google.com/file/d/1oUhekGQp-3HiIg6KMOhy8vWSDT4AzC_3/view?usp=sharing
**Screenshots**
https://drive.google.com/file/d/1jwrUL52CrWJS9UPvR6wc30uiGFmLGHLd/view?usp=sharing

#### Additional information

* PrestaShop version: 1772, 1773, 1774build1
* PHP version: 7.2, 7.1

**Comment by Progi1984** [comment]
@khouloudbelguith I don't reproduce this bug on 1.7.7.x branch. Could you check it ?

**Comment by jolelievre** [comment]
I tested to reproduce the problem on 1.7.7.x but I couldn't reproduce it (didn't test the 1.7.7.4 build though)

**Comment by khouloudbelguith** [comment]
Hi @Progi1984, @jolelievre,

I did not manage to reproduce the issue with 177x branch (1750) and 178x branch.
https://drive.google.com/file/d/1V48fToDKf9iWkXoUqES1-dy5oh7DNYW9/view?usp=sharing
It is fixed.
I will close the issue.

Thank you!
