### ISSUE TITLE
Impossible d'avoir le Calcul des frais de Port dans le panier - Liste des transporteur visible dans le panier

### ISSUE THREAD

**Issue by prestaprojet** [PrestaShop/PrestaShop#24311]
Bonjour,

Voici ma configuration actuelle 
Windows 7 + DUC 4.1.1 + BOX MIAMI + wamp apache 2.4.37 + MYSQL 5.7.24 + PRESTASHOP 1.7.7.3
Theme : classic dupliqué en child.

Voici la description du BUG

J'ai installé Boxtal pour les livraisons des colis ; 
J'ai réalisé un test de commande pour valider le fonctionnement mais malheureusement les frais de livraison liés au transporteur n'apparaissent pas dans le total de mon panier ; cependant la liste des transporteurs est bien visible avec les montants liés au frais de port.

J'ai contacté Boxtal en passant que le problème viendrait de ce coté et leur technicien valide que tout fonctionne correctement sur son module.

Il me dit rien pouvoir faire à son niveau et de contacter PRESTASHOP pour ce Bug.
Le technicien a même désinstaller Boxtal et les frais de port dans le Panier n'étaient pas visible.
Il a vérifier également le paramétrage et les transporteurs créés tout est Ok.

Voici en pj les print écran du panier

Pourriez-vous svp m'aider car Prestashop semble avoir un Beug à mon niveau pour le calcul des frais de port au niveau du Panier ;

Merci d'avance pour votre aide

:-)

![Capture panier frais de livraison](https://user-images.githubusercontent.com/83583065/116868504-29c20480-ac0f-11eb-91b1-a212130fc800.JPG)
![Capture mode livraison](https://user-images.githubusercontent.com/83583065/116868682-802f4300-ac0f-11eb-8ab1-e4e4d752dbac.JPG)
![Capture mode livraison](https://user-images.githubusercontent.com/83583065/116868722-93daa980-ac0f-11eb-95aa-dbdc62976e7b.JPG)

**Comment by matks** [comment]
Hi @prestaprojet would it be possible to use English 😉 ? This is a worldwide project we have to use English for every users so that anybody can understand 😄

**Comment by matks** [comment]
That being said, if you need help, GitHub issues are used only to discuss about bugs and new features for the PrestaShop project.
You will probably find some help in https://devdocs.prestashop.com/1.7/faq/i-need-help/

**Comment by hibatallahAouadni** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you
