### ISSUE TITLE
Currency sign too close from price on invoice

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#24316]
#### Describe the bug

When opening an invoice on **MAC OS** default viewer, the currency sign is covering the price (see screenshot attached).

I did some testing changing the default pdf fonts and it's working good with the other fonts (free, dejavu). So the issue is with Helvetica not handled the same way on mac.

#### Expected behavior
To have a bit more space between the currency signe and the price maybe using freesans instead (but causing issue in pagination)

#### Steps to Reproduce

1. Go to Orders
2. Click on Invoice
3. See the invoice on Mac OS

**Screenshots**
![image](https://user-images.githubusercontent.com/1193727/116885639-651cfd00-ac28-11eb-88af-e7f7404c4c19.png)

#### Additional information

- PrestaShop version: 1.7.6.7 (as well as on 1.7.7)
- PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @arirangz 

I didn't manage to reproduce the issue with PS1.7.6.7 on Mac OS Safari 14, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116960538-f3cd6080-aca0-11eb-9824-d6d10af4ccdf.png)

Please check and feedback.
Thanks!

**Comment by arirangz** [comment]
hello @hibatallahAouadni 
The test shouldn't be done with Safari, but opening the PDF with the pdf viewer.
Thanks

**Comment by hibatallahAouadni** [comment]
Duplicate of #20633
