### ISSUE TITLE
Increase the amount of that can be sorted - 1.7.7.3

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#24326]
In 1.7.6 it was possible to export up to 1000 orders or sort by. In 1.7.7 this has been reduced to 100

Describe the solution you'd like

Increase back to the old standaars or higher. Makes it better for exporting.

Prestashop 1.7.6.3

**Comment by alfonsolr09** [comment]
this is your solution 
https://youtu.be/qsNtGU-IJkY

**Comment by hibatallahAouadni** [comment]
Hello @01park 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @alfonsolr09 for your quick reply :wink: 

Thanks!
