### ISSUE TITLE
slowness of the order validation page

### ISSUE THREAD

**Issue by plepicier** [PrestaShop/PrestaShop#24322]
Hello

#### Describe the bug

I have a problem with the order validation page being too slow. After filling in the form on the order page with the delivery and payment method, the validation page is very slow. 

For example for a payment by cheque, it takes me 3 - 4 minutes for the order to be validated. The same goes for Monetico, I cannot validate the production TPE because the loading time is too long.

On the shop there are only two simple products with no variations. We have tried with the basic Prestashop theme and we still have the same problem of slowness, the same with the modules, we have all deactivated and there is no change. There is no problem in the console either

We have upgraded Prestashop from 1.7.7.0 to 1.7.7.3 and there is no change, the order validation page is still slow.

This problem of slowness occurs only on the order validation page, on the rest of the site the pages load very well and quickly.

#### Expected behavior

I would like to find a solution to the problem of slowness, we have several Prestashops and this is the first time this bug has happened to us. 

#### Steps to Reproduce

1. Fill in the information on the order page
2. Click on "Order".
3. The validation page may take up to 3 - 4 minutes to load

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @plepicier 

> For example for a payment by cheque, it takes me 3 - 4 minutes for the order to be validated. The same goes for Monetico, I cannot validate the production TPE because the loading time is too long.

That's not normal!!! In my case, I can't reproduce the issue.
Well, it also depends on your server, on your SQL content, ...

I'm really sorry but I can't help you cause I can't manage to reproduce the issue :confounded: 
It seems you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
