### ISSUE TITLE
Multistore dropdown - In Group Context, display only the shops of the group

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24334]
#### Describe the bug

In Multistore, when we have several group with shops inside, if I'm in a Group Context in a page where the multistore dropdown can be displayed, I want the dropdown to display only the shops inside the group, not all the shops.

#### Expected behavior

Display only the shops inside the group in Multistore Dropdown

#### Steps to Reproduce

0. Have Multistore ON, have at least 2 groups with 2 shops in each (shops A & B in Group 1, shops C & D in Group 2)
1. Go to Shop Parameters > General > Maintenance
2. Set a specific parameter in shop A (shop in Group 1), and a specific parameter in shop C (shop in group 2)
3. Change context to "Group 2"
4. Open the Multistore dropdown : All the shops are displayed, only the one inside the group 2 should be displayed.

**Screenshots**

![multistore dropdown group ocntext](https://user-images.githubusercontent.com/55688534/116987200-0c546f80-accf-11eb-9f0a-deedb97b2920.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by atomiix** [comment]
Fixed by #24355
