### ISSUE TITLE
Missing scrollbar in Multistore dropdown

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24333]
#### Describe the bug

When we have a lot of shop (in Multistore), the multistore dropdown does not have a scrollbar, the display is not OK

#### Expected behavior

There should be a scrollbar inside the dropdown to easily navigate through the multiple shops (like in the multistore header)

#### Steps to Reproduce

0. Have Multistore ON, add at least 30-40 shops
1. Go to Shop Parameters > General > Maintenance
2. Set a specific parameter in a shop context
3. Change context to "All Shops"
4. Open the dropdown : There in no scroll bar, and the top of the dropdown is hidden under the header.

**Screenshots**

![multistore dropdown no scroll](https://user-images.githubusercontent.com/55688534/116986197-c4811880-accd-11eb-8c6d-b0d3bbbad8e0.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### Mock-up

https://projects.invisionapp.com/share/QPWKQY5DV79#/screens/410367397_All_Shops_Specific_Set-_Dropdown

![capture d'écran_3070](https://user-images.githubusercontent.com/13449658/116986858-96500880-acce-11eb-8c93-f5158deaf55a.png)

**Comment by Progi1984** [comment]
Fixed by @micka-fdz in #24713
