### ISSUE TITLE
AutoUpgrade module backup every file in the root directory, including folders that do not belong to prestashop

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#24351]
#### Describe the bug

When using 1-Click Upgrade module to upgrade Prestashop, the module backup every folder in the root directory, including folder not used by Prestashop.

For example if you have Prestashop installed into main "httpdocs" folder, and into a subfolder there's installed a wordpress website, 1-Click Upgrade module will backup these files too.

This is a problem, because it will backup not needed files, and this increase a lot the time required to do the upgrade.

In my case the module takes about 5/6 hours to backup everything, because of a wordpress install with thousands of images and other files.

#### Expected behavior

1-Click Upgrade should backup only Prestashop files, and exclude any folder not related to Prestashop.

#### Steps to Reproduce

1. Open "1-Click Upgrade" module
2. Click on "Upgrade PrestaShop now!" button

#### Additional information

* PrestaShop version: all 1.7 versions
* 1-Click Upgrade: v4.12.0
* PHP version: PHP7.1/PHP7.2/PHP7.3

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

> For example if you have Prestashop installed into main "httpdocs" folder, and into a subfolder there's installed a wordpress website, 1-Click Upgrade module will backup these files too.

So, do you mean that **1-Click Upgrade** module backup even folders aren't inside PrestaShop folder?
is this your **httpdocs** tree structure:

-- httpdocs
------ PrestaShop
------ Wordpress

Please check and feedback.
Thanks!

**Comment by darkf3d3** [comment]
No, wordpress folder it's in the same folder as Prestashop.
Here's an example:
www.buyshoes.net (prestashop)
www.buyshoes.net/blog (wordpress)

In this case prestashop it's installed directly into httpdocs folder, and wordpress blog it's into a subfolder:
-- httpdocs
------ admin
------ app
------ bin
------ blog <-- wordpress
------ cache
------ cgi-bin
------ ...
------ ...
------ ...

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers is this normal to have such tree structure? 
IMHO I think it's wrong to paste all PrestaShop content/files under **httpdocs** alongside other projects, wdyt?

**Comment by matks** [comment]
> Ping @PrestaShop/prestashop-core-developers is this normal to have such tree structure?
> IMHO I think it's wrong to paste all PrestaShop content/files under **httpdocs** alongside other projects, wdyt?

Hello, I think this is the normal behavior.

PrestaShop does not acknowledge that something else was installed in its root directory 😄  and there is no check to verify whether a folder is expected to be inside its root folder or not.

This is quite a edge-case 😄  . It could be avoided by adding the option to select what folders should be backed-up, but that is an improvement that would not benefit a lot of people I think.

@PierreRambaud tell me if I am wrong but having such a structure is not a very good security practice, I think? 🤔  because if for example an attacker is able to slip in the PrestaShop folder using a security leak, then the Wordpress would become also compromised.

**Comment by darkf3d3** [comment]
But installing Prestashop into httpdocs/prestashop folder doesn't mean having the folder name into the website url, for example: "www.buyshoes.net/prestashop/"?
I always installed prestashop directly into httpcods without any additional folder to avoid this.

**Comment by kpodemski** [comment]
It is a correct behavior since it wouldn't make sense to back up only PS directories as some third-party modules can use others. I'm closing this issue.
