### ISSUE TITLE
Sort the release note 

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24367]
#### Is your feature request related to a problem?

IT's very annoying to have the older version on the top of the upgrade page. i have to scroll down to see the new things.

![image](https://user-images.githubusercontent.com/4645967/117270556-a0524280-ae59-11eb-9228-13aae1676ac0.png)

I'm in the v2.15.1version and i upgrade to  v2.15.2,  then i should only see 2.15.2 release note part.

#### Describe the solution you'd like

I would like to have only the 2.15.2, and the version are sorted in the release note to have the last notes in top

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

You're right! it's quite annoying to scroll down from v1.4.0 down to 2.15.2
But I don't know if it should be fixed in PS Core or in Module side.

Ping @PrestaShop/prestashop-core-developers any idea in which side it should be fixed? PS Core or Module?

**Comment by matks** [comment]
@hibatallahAouadni Someone needs to explore how this release note is fetched from API and see whether content is already sorted from source, or if sort happens after data has been fetched

**Comment by kpodemski** [comment]
No longer relevant for the open-source project. Changelog comes from the ps_mbo module.
