### ISSUE TITLE
[Experimental product page] History of edited combinations

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#24368]
#### Describe the solution you'd like

This feature aim to add some history on the edit combination modal of product page v2

#### Alternatives you've considered

Go on product page v2 on a product with combinations, click on edit a combination and try to play with the history feature! It should have a pagination after 14 edit history and the pagination should works as expected.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/23948
