### ISSUE TITLE
prestashop_checkout translation front office modal

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24369]
#### Expected behavior
the text which is in the modal should be in french

#### Steps to Reproduce

1. Setup and configure the module
2. Set your shop in french
3. make a purchases
4. All modals are in english.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
prestashop_checkout

![image](https://user-images.githubusercontent.com/4645967/117272540-95001680-ae5b-11eb-9404-0b6fc1817082.png)

#### Additional information

* PrestaShop version:1.7.7.4
* Prestashop checkout: 2.15.2
* PHP version: N/A

**Comment by matks** [comment]
Hello,

This platform is for PrestaShop project bugs only. PrestaShop Checkout is a module provided by PrestaShop company.

If you have an issue with PS Checkout please contact the support team of PS Checkout directly through the module 😉 .

Thank you, I will close your issue.
