### ISSUE TITLE
BO - Theme & Logo - changing the header logo will also change Mail logo

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24365]
_Originally posted [here](https://github.com/PrestaShop/PrestaShop/pull/23959#issuecomment-824013253)_

#### Describe the bug

When you change the header logo, the mail logo has also been changed

#### Expected behavior

If you upload a file for the header logo, then the email & invoice logos should not be changed and should not use the uploaded file for the header logo

#### Steps to Reproduce

1. BO > IMPROVE > Design > Theme & Logo
2. Change the header logo
3. Save
4. See error > the mail logo has also been changed

**Screenshots**

https://www.awesomescreenshot.com/video/3642980?key=d32d3d8d054a7a7e1f1ae19be9483042

#### Additional information

* PrestaShop version: 1.7.6.7 & 1.7.7.3 & develop
* PHP version: 7.2

**Comment by jf-viguier** [comment]
@hibatallahAouadni is product team ok with this beaviour ?

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier,

@marionf said in your PR:

> If you upload a file with .svg for the header logo, then the email & invoice logos should not be changed and should not use the uploaded .svg for the header logo

So, I believe the Product Team is ok with this proposed behavior.

Thanks!

**Comment by jf-viguier** [comment]
Is it ok for any image type or only svg ? @marionf ?

**Comment by marionf** [comment]
Hello,

I was talking only of SVG :)

**Comment by hibatallahAouadni** [comment]
Great! Thanks @marionf 
I close this issue.
@jf-viguier you have PM answer :tada: **it's ok only for SVG**
