### ISSUE TITLE
FO - confusing error message when we access to disabled category or a category page that does not exist

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24370]
_Originally posted [here](https://github.com/PrestaShop/PrestaShop/pull/24270#issuecomment-830483500)_

#### Describe the bug

In FO, if you try to access a disabled category or a category page that does not exist, a wrong error will be displayed (see the attached screenshot n°1)

#### Expected behavior

It should display this page is not found (see the attached screenshot n°2)

#### Steps to Reproduce

1. Go to FO
2. Try to access a category that does not exist URL (for example : [URL]/fr/18-test)
3. See error > it display the wrong error message **No products available**
4. Create a category 
5. Disable the category
6. In FO, try to access the disabled category by URL
7. See error > it display the wrong error message **No products available**

**Screenshots**

https://drive.google.com/file/d/1FXBS2yphcE1OkdgLo0nnk-A2y_JyZ8OC/view

- Screenshot n°1

![image](https://user-images.githubusercontent.com/23308427/117268179-4cdef500-ae57-11eb-8b83-17c9b54b05ce.png)

- Screenshot n°2

![image](https://user-images.githubusercontent.com/23308427/117273213-371ffe80-ae5c-11eb-8421-aa7bba4c3583.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

---
_PS: on develop, we still have these issues #24145 & #24143_

**Comment by jf-viguier** [comment]
Is this issue fixed by https://github.com/PrestaShop/PrestaShop/pull/24270 ?

**Comment by hibatallahAouadni** [comment]
@jf-viguier no! After fixing these issues #24145 & #24143 by the PR #24270 I encountred this issue

**Comment by jf-viguier** [comment]
In branch  PrestaShop:1.7.8.x ? @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@jf-viguier Yessss :wink:

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24852
