### ISSUE TITLE
Invalid inline style in PrestaShop UI Kit symfony form theme

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#24376]
#### Describe the bug

In the prestashop UI kit form theme some inline code has been added in. the `form_row` block:

```twig
    <div class="{{ block('form_row_class') }}{{ block('widget_type_class') }}{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}"{% if (attr.visible is defined and not attr.visible) %} style="display: none;"{% endif %}>
```

This part in particular `{% if (attr.visible is defined and not attr.visible) %} style="display: none;"{% endif %}` we should use a class instead (like `d-none`) This option seems to be only used in `PrestaShopBundle\Form\Admin\Sell\Address\CustomerAddressType` (strangely not in the other address types).

This should be fixed in the theme, but maybe also in the js of the customer address (if we use a class the js might just use `.show()/.hide()` and it won't work any more).

#### Expected behavior

Same behaviour but with clean theme without hard coded inline style.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by PululuK** [comment]
Fixe https://github.com/PrestaShop/PrestaShop/pull/24541
