### ISSUE TITLE
Error 500 page - 500.html is not used

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24388]
#### Describe the bug

I didn't find anything in the documentatoin explaning how customize error page.

I found the 404 and maintenance.tpl files

However, the 500.html file is not used.
  

How can i make it works ?

Here is what i observed:

- error500.html is used when mysql is down; this is quite perfect.
- themes/X/templates/errors/static/500.html is never used, why? 

#### Expected behavior

I would like to either the error500.html is loaded, or the 500.html be served.

Maybe the error500.html from the root directory should be a symlink to the 500 error of the used theme ?

#### Steps to Reproduce

1. Fill the themes/X/templates/errors/static/500.html with beautifull html.
2. Explode the index.tpl to force a beautifull error.

**Screenshots**

![image](https://user-images.githubusercontent.com/4645967/117421944-5895ee80-af1f-11eb-88bc-74b03cdb875d.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @henri9813 ,

Indeed I can't make the 500.html page work after adding html to the file.
[500.html.zip](https://github.com/PrestaShop/PrestaShop/files/6440484/500.html.zip)
The error 500 is still the same in my shop : 
![Capture d’écran 2021-05-07 à 11 20 11](https://user-images.githubusercontent.com/16019289/117428266-32c01800-af26-11eb-8a2b-3209b686525b.png)

Sometimes this error shows (file error500.html), but it depends on what kind of error you get.
![Capture d’écran 2021-05-07 à 11 23 40](https://user-images.githubusercontent.com/16019289/117428875-c09c0300-af26-11eb-8b8f-76b47eec2285.png)

Thanks!

**Comment by henri9813** [comment]
Yes, 

Thank you for your quick answer !

**Comment by jf-viguier** [comment]
@henri9813 @florine2623 if mysql is down, the 500.html theme template can't be loaded because the theme is saved to the database. So the current theme can't be retreive.
I suggest to remove this 500.html page that is useless.

**Comment by henri9813** [comment]
May this can be included in `htaccess`? 

```
ErrorDocument 500 /error/internal-server-error.html
```

**Comment by jf-viguier** [comment]
@henri9813 the file /error500.html is already served by prestashop, there is no need for an extra internal-server-error.html file. Please explain.
Something like this ?
`ErrorDocument 500 /error500.html`

I've tested this line and it doesn't work

**Comment by henri9813** [comment]
Indeed, this doesn't works.

However, maybe a solution could be setup to manage this case and use the 500 error page ?

I know that symfony is able to manage 500 errors.
