### ISSUE TITLE
docker-windows-wsl2: recreating all themes & assets on each container restart

### ISSUE THREAD

**Issue by Ploppy3** [PrestaShop/PrestaShop#24381]
#### Describe the bug

All themes and assets are generated every single time the container restarts, which takes a long time.

#### Expected behavior

All themes and assets should be generated only once when the container is created.

#### Steps to Reproduce

1. Setup Docker with WSL2 and Linux distro
2. Within the linux distro: clone repo
3. `docker-compose up`
4. restart container

#### Additional information

Could it be caused by this warning?
```
* Running composer ...
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

**Comment by PululuK** [comment]
Hi @Ploppy3 

Can you please check https://devdocs.prestashop.com/1.7/basics/installation/localhost/#setting-up-file-rights

**Comment by hibatallahAouadni** [comment]
Hello @Ploppy3 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Ploppy3** [comment]
@hibatallahAouadni aggressively closing issues is not a solution, the problem is still there.

**Comment by hibatallahAouadni** [comment]
Hello @Ploppy3 

I didn't aggressively close the issue :wink: 
As you can see, @PululuK asked you to check the doc and you didn't even feedback for more than 20 days.
So, if we don't receive any answer from the issue's author, we close the issue.

Thanks!
