### ISSUE TITLE
https is not forced in the Back Office while logging in

### ISSUE THREAD

**Issue by num47** [PrestaShop/PrestaShop#24383]
#### Describe the bug

This might be a negligible issue but while i was trying to login to the back office i have noticed that the https wasn't forced. At first, it forces to the https but later if you manually remove the 's' from 'https' then it does not force it to https again. This is not a problem when you try to login to your back office where you are not already logged in. But, in a logged in one, it sometimes load the url without 'https' which is a potential threat to expose my admin folder. 

#### Expected behavior

It does not affect any other activity except when you try to visit your dashboard. I have tried to check if it happens the same for the front office but it works perfectly in the front office. The problem seems to be only happens in the back office. 

#### Steps to Reproduce

1. Go to 'Visit back office'
2. login to your back office
3. Change the url manually from 'https' to 'http'
4. press enter key on your keyboard and wait until the page load. 

**Screenshots**
I am sending the screenshot from your prestashop demo website. 

![Untitled](https://user-images.githubusercontent.com/33420890/117358093-8e16e980-aed7-11eb-915d-b0b2e7e2b062.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4 but it happens with version 1.6.1.24; 1.7.7.2 

* PHP version: N/A

**Comment by florine2623** [comment]
Hello @num47 ,
You need to check these 2 elements :
![Capture d’écran 2021-05-07 à 10 03 35](https://user-images.githubusercontent.com/16019289/117418259-7e20f900-af1b-11eb-905d-5628c5f65be4.png)

Once done, when you log into your back-office in http, you will see :
![Capture d’écran 2021-05-07 à 10 10 07](https://user-images.githubusercontent.com/16019289/117419028-67c76d00-af1c-11eb-90ff-c6913a9cae63.png)

Thanks!
