### ISSUE TITLE
BO - Open a combination that has been deleted on product V2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#24389]
@MatShir @TristanLDD I encountered a problem we didn't think about when trying to access a combination that doesn't exist any more in the modal (because it was deleted in another page). I had a big ugly error, so this is fixed but don't have a regular not found template, so I made one inspired by the 500 one but it's worth some additional love from both of you ^^

Especially regarding:
- the wording
- the error image
- do we keep the same buttons as CTA
- one thing weird (already present in the previous 500 page) The "Enable debug mode" button is always present if if the debug mode is enabled

Here's the look of what I did for now:

![Capture d’écran 2021-05-06 à 19 01 18](https://user-images.githubusercontent.com/13801017/117337598-d87b7480-ae9d-11eb-95d5-2eaccf35a391.png)

To avoid blocking this PR too long (and the QA for 178), if it needs a deep reflection I'd suggest merging this for now and improve it in another PR.
## Specs

For me here the best solution would be: 
**IF**

- the user clicks on a combination from the list that doesn't exist anymore

- the user has already the pop in opened, but the combination doesn't exist and saves his edited

- the user goes to the next combination that was deleted before or the user does to the combination selected from the history

**THEN** 

It opens an error modal with an error message and the button 'close and refresh' (on top of the combination modal or close the combination modal first).
## Design 

Hello, here is the link for the modal's mockups: 

https://www.figma.com/file/aCBf2HlypjT0ZxP2XcsT68/Core-Github-issues?node-id=1507%3A11496

I would prefer to avoid overlapping modals, this one should replace the combination modal as it would be confusing to have both modals action buttons in the same time. We can reopen the combination modal after the user closed this one

<img width="980" alt="comb_doesnt_exist" src="https://user-images.githubusercontent.com/27484094/163415891-d6f662ee-d8f8-4402-bd07-273f6be5a495.png">

_Originally posted by @jolelievre in https://github.com/PrestaShop/PrestaShop/issues/24076#issuecomment-833691573_

**Comment by MatShir** [comment]
For me here the best solution would be: 
**IF**

- the user clicks on a combination from the list that doesn't exist anymore

- the user has already the pop in opened, but the combination doesn't exist and saves his edited

- the user goes to the next combination that was deleted before or the user does to the combination selected from the history

**THEN** 

It opens an error modal with an error message and the button 'close and refresh' (on top of the combination modal or close the combination modal first).

**Comment by Julievrz** [comment]
I suggest: "This combination doesn't exist anymore." in Admin.Catalog.Notification

+ button: "Close and refresh" in Admin.Actions

@MatShir Do we need another wording?

**Comment by TristanLDD** [comment]
Hello, here is the link for the modal's mockups: 

https://www.figma.com/file/aCBf2HlypjT0ZxP2XcsT68/Core-Github-issues?node-id=1507%3A11496

I would prefer to avoid overlapping modals, this one should replace the combination modal as it would be confusing to have both modals action buttons in the same time. We can reopen the combination modal after the user closed this one

<img width="980" alt="comb_doesnt_exist" src="https://user-images.githubusercontent.com/27484094/163415891-d6f662ee-d8f8-4402-bd07-273f6be5a495.png">

**Comment by florine2623** [comment]
As discussed previously, when modifying a combination that has been deleted, there's an exception :

https://user-images.githubusercontent.com/16019289/166456437-a1a5d7d9-5d04-46e3-8aca-3f76bbfe81e9.mov


<img width="946" alt="Screenshot 2022-05-03 at 14 52 56" src="https://user-images.githubusercontent.com/16019289/166456328-9043dd3f-59d3-4663-a716-b5b06666f264.png">

**Comment by AureRita** [comment]
Fixed by #29066
