### ISSUE TITLE
Wishlist color inheritance

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24392]
#### Describe the bug

Hello :-)

Thanks for the module, it works pretty well.
All links colors are overrided in the module.
That easily break custom themes colors

#### Expected behavior

There should not have 
```
color: XXXX
```
on the module CSS.

#### Steps to Reproduce

1. Create a theme
2. Set color of all links to red
3. Setup the module
4. the modules "<a>" are in blue

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by henri9813** [comment]
Hello,

I Purpose a merge request here: https://github.com/PrestaShop/blockwishlist/pull/112

**Comment by florine2623** [comment]
Hello @henri9813 ,

Which version of PS and of the module you are using ?

Thanks!

**Comment by henri9813** [comment]
1.7.7.4 and the v2.0.0 for the module.

Thank you

**Comment by lmeyer1** [comment]
I think the best solution to solve this color problem is using the color classes of bootstrap.
In any PS template, the classes `text-primary`, `bg-primary`, `text-secondary` and `bg-secondary` give the theme's colors to the text/background.

blockwishlist should make use of these classes and not introduce it's own color code.

**Comment by henri9813** [comment]
I agree with you @lmeyer1

**Comment by florine2623** [comment]
Hello @henri9813 @lmeyer1 ,

This is more an improvement suggestion than a bug in my opinion.

The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by lmeyer1** [comment]
@florine2623 Choosing between *improvement* and *bug* is difficult here. If the latest version of a module breaks all templates but those that use a specific blue as primary color, in my humble opinion, this is an important regression.
Calling it a bug is obvious. Calling it 'improvement' is an euphemism 😃

**Comment by matks** [comment]
To be defined as a bug, this behavior should have been expected.

If we want to build a v2 of module Foo with features A, B and C
and after we release v2.0.0 we find A is not working as expected, it is a bug.

But I dont know whether "use the theme defined colors" has been defined and stated as a feature of v2 of Blockwishlist. So it's a possible improvement.

> blockwishlist should make use of these classes and not introduce it's own color code.

Not sure about that 🤔  . Themes can override module templates, but module cannot override theme templates.

**Comment by lmeyer1** [comment]
Sorry @matks, maybe my answer was a little too harsh.

**Comment by henri9813** [comment]
@matks , Hello, the override doesn't work, it works only when i change priorities of the module assets, things i do in my PR.

**Comment by NeOMakinG** [comment]
The PR is merged, this has also been facilitated on https://github.com/PrestaShop/blockwishlist/pull/114

Thanks @henri9813

**Comment by hibatallahAouadni** [comment]
@NeOMakinG the PR still not merged :sweat_smile: it's waiting for QA

**Comment by NeOMakinG** [comment]
@hibatallahAouadni initial PR is this one : https://github.com/PrestaShop/blockwishlist/pull/112

And I added more about this subject but not only this one inside the current linked PR

**Comment by Progi1984** [comment]
Fixed in PrestaShop/blockwishlist#114 by @NeOMakinG
