### ISSUE TITLE
Pages editor white space problem

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24391]
#### Describe the bug

I wrote content and i want to "make space" between paragraphs, then i press enter many times to make "blank lines"

It's doesn't works because the paragraphe styles is "margin-top: 0 && margin-bottom: 0".

#### Expected behavior

An empty paragraph should be converted to a <br/>

#### Steps to Reproduce

1. Create page with many paragraphs with many blank lines
**Screenshots**

![image](https://user-images.githubusercontent.com/4645967/117441444-a7e71980-af35-11eb-833b-0353af08c2b4.png)

![image](https://user-images.githubusercontent.com/4645967/117441469-afa6be00-af35-11eb-944d-a73b38effde0.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @henri9813 ,
You can use the tag <br> :
![Capture d’écran 2021-05-07 à 15 47 39](https://user-images.githubusercontent.com/16019289/117459371-9b6dbb80-af4b-11eb-824a-7c7e19c99fd7.png)

![Capture d’écran 2021-05-07 à 15 47 03](https://user-images.githubusercontent.com/16019289/117459299-8a24af00-af4b-11eb-9d98-3df36405e9ab.png)

![Capture d’écran 2021-05-07 à 15 46 53](https://user-images.githubusercontent.com/16019289/117459283-86912800-af4b-11eb-9701-944737150411.png)

**Comment by henri9813** [comment]
Hello,

Thank you, but that doesn't solve my problem.

I couldn't pass my time to go in the html code editor to add br.

Why did you close this issue ? The problem came from the editor.

**Comment by henri9813** [comment]
A random and potentially non techincal user will never know how do this
