### ISSUE TITLE
Warning: escapeshellcmd() has been disabled for security reasons

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24395]
Hi
today I get this error to complete an order
Warning: escapeshellcmd() has been disabled for security reasons

do you have some notices about it?

I've not done any changes from yesterday, only to upgrade paypal and payplug modules
the order is created but without products in the order, with all payment methods

bye

**Screenshots**

![5](https://user-images.githubusercontent.com/653230/117458487-a4aa5880-af4a-11eb-9b1d-69c0ebc90f55.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by matks** [comment]
Hello @maofree look at https://github.com/PHPMailer/PHPMailer/issues/966 ;)

**Comment by Maofree** [comment]
Hi @matks 
thanks
which type of solution can I do to fix it?
yesterday was ok, today not, it is a big caos :(

**Comment by Maofree** [comment]
is it necessary to use the smtp solution?

**Comment by florine2623** [comment]
Hello @maofree ,
Could you share the steps to reproduce the issue please ?
Thanks!

**Comment by Maofree** [comment]
Hi
nothing of special, active the debug and create an order
at this moment I don't know the motive, it happens only in one site, it gets many orders every days, and today I didn't do any of special

I've asked to the hosting

**Comment by Maofree** [comment]
I've solved the problem using SMTP solution instead of normal php mail()
it is the same solution used by others

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Glad to hear that you solve the problem by using SMTP solution instead of normal php mail() :tada: 
> at this moment I don't know the motive, it happens only in one site, it gets many orders every days, and today I didn't do any of special

As you mentioned, it's hard to reprpduce :confused: 
So, I close this issue.

Thanks!
