### ISSUE TITLE
Cart shop admin beuguée 

### ISSUE THREAD

**Issue by r4dhwene** [PrestaShop/PrestaShop#24406]
Bonsoir, 
j'ai un problème lors l'ajout d'un produit dans la panier dans partie admin, il m'affiche cette erreur : 
"Une erreur inattendue s'est produite. [PrestaShop\PrestaShop\Core\Domain\Cart\Exception\CartException code 0] : Order for cart with id "3" already exists.."
![cart](https://user-images.githubusercontent.com/39316906/117510722-dd6b2180-af8c-11eb-8506-e649c6470ba0.jpg)

Meme quand je supprime les donner de la table " ps_cart" le problème persiste 

Comment je corrige cette erreur s'il vous plait ?
Version : 1.7.7.3

Merci

**Comment by hibatallahAouadni** [comment]
Hello @r4dhwene ,

Please send your request in English. English is the norm on GitHub.

Thank you
