### ISSUE TITLE
[BlockWishlist] Usage of edit pencil on wishlist view

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24400]
#### Describe the bug

On the wishlist list view, i see products which are in my wishlist. On products, there is a "pencil" button.
what is his usage ? when i click on it, i just go the product page.

#### Expected behavior

~The pencil should have a usage or dissapear~
>Edit by @hibatallahAouadni 

### SPECS
**US3 : Edit and delete a favorite product** (by @lolath-presta)
As a logged user, I can modify and delete a favorite product. Different cases:

- Products with stock
- Products without stock
- from the product page
- from the favorites list

**_Functional rules_**
I can modify the quantity, the combination as well as the customization of all my favorite products (in stock, out of stock) by clicking on the Pencil from my list of favorite products.

When I click on the Pencil, I am redirected to the product page in order to make my modifications. Once the modifications have been made, you will have to click on the heart to add the new product to your favorites. At this time, the new size or combination or customization overwrites the initial product present in the list of favorites.

#### Steps to Reproduce

1. go to a product page
2. Add product to a wishlist
3. Go to see the wishlist (url should be something like: http://127.0.0.1:8000/module/blockwishlist/view?id_wishlist=1 )
4. Click on pencil

**Screenshots**

 
![image](https://user-images.githubusercontent.com/4645967/117485610-da5e3a00-af68-11eb-92b7-d28ad8e12f6a.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* BlockWishlist: 2.0.0

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

> On the wishlist list view, i see products which are in my wishlist.
On products, there is a "pencil" button.
what is his usage ? when i click on it, i just go the product page.

@lolath-presta @kpodemski any idea what's the use of this pencil?

**Comment by kpodemski** [comment]
I'm pretty sure it's used to edit product quantity, for example you saved 2 qty of Product X into your wish list, and then you decided to have only 1. Not sure if it's needed but this is how it worked in 1.6.

**Comment by hibatallahAouadni** [comment]
Hello,

@kpodemski thanks for your quick reply :wink: 
@henri9813 so you've got your answer, as this button's function is to edit the product qty, so it should redirect you to the product page. 
I close this issue, cause this the wanted behavior.

Thanks!

**Comment by henri9813** [comment]
Hello,

So, i do not see the interest of this button because image + name of the product are already links of the product page. @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@henri9813 we still working on this module, the Product Team may add a functionality to this button. So, let's wait :wink:

**Comment by henri9813** [comment]
Okay, i have 2-3 Pr to do for this module  ;-)

**Comment by hibatallahAouadni** [comment]
FYI @kpodemski I just edit the expected behavior according to specifications ;)
