### ISSUE TITLE
Inject firstname and lastname to ps_customersignin

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24405]
#### Is your feature request related to a problem?

I want to have the firstname of the user, currently i have only $customerName variable.

Is it possible to have the $customerFirstname and $customerLastname ,

#### Describe the solution you'd like

	<span class="hidden-sm-down">{$customerFirstname}</span>

#### Additional context

I will do a merge request for this if you accept

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by kpodemski** [comment]
You can access all customer informations using global Smarty variable `$customer`, for example `$customer.lastname`, `$customer.email`.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@kpodemski Thanks for your quick reply :rocket: 
So, no need for this improvement :tada: 

I close this issue!
Thanks!

**Comment by henri9813** [comment]
oh okay, thank you so much !
