### ISSUE TITLE
[Wishlist] Remove article from wishlist message is quite strange

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24402]
#### Describe the bug

The message is not very accurate, it could be better in my opinion

#### Expected behavior

"Remove this article from wishlist ?" instead of "Remove"

#### Steps to Reproduce

1. Add a product to your wishlist
2. Go to your wishlist view
3. Click on remove the product from wishlist

I know i made lot's of issue, sorry for that :-)

**Screenshots**

![image](https://user-images.githubusercontent.com/4645967/117486739-5016d580-af6a-11eb-9e8c-c5f200d90c41.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* BlockWishlist 2.0.0

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

I reproduced the issue, but I don't know if it's the right wording or no!
@kpodemski @Julievrz any idea about this wording?

![image](https://user-images.githubusercontent.com/23308427/117627041-0d2a4d00-b178-11eb-974b-6c6035ee04e0.png)

Thanks!

**Comment by Julievrz** [comment]
Hello @hibatallahAouadni 

I haven't worked on the Wishlist module's wording. I need to talk about it with the product managers next week to know if I should take care of the wording of this module. I will let you know asap.

**Comment by henri9813** [comment]
If needed, i can make PR, but i need to learn how translation are managed inside prestashop ( i'm a prestashop dev beginner :D )

**Comment by matks** [comment]
> If needed, i can make PR, but i need to learn how translation are managed inside prestashop ( i'm a prestashop dev beginner :D )

😉  https://devdocs.prestashop.com/1.7/development/internationalization/translation/

**Comment by NeOMakinG** [comment]
> If needed, i can make PR, but i need to learn how translation are managed inside prestashop ( i'm a prestashop dev beginner :D )

I think this chain is just a data-attr inside a smarty template

**Comment by Julievrz** [comment]
Hi @henri9813 
Thank you for opening this issue. I agree with you that the wording could be better and less alarming! I suggest the following wording, which fits better the template we are trying to follow throughout the software:

title: 'Remove product from wishlist?'
confirm_message: 'The product will be removed from "%nameofthewishlist%".'
buttons: 'Cancel'
              'Remove'

**Comment by henri9813** [comment]
Looks better!

**Comment by Julievrz** [comment]
Hi @henri9813 

Thanks! I modified it just a little after thinking about it to avoid the 'Are you sure you want..." that creates unnecessary doubt in the user. :)
