### ISSUE TITLE
Stock movement registered as "Employee Edition" when order is created on BO 

### ISSUE THREAD

**Issue by sanji-japan** [PrestaShop/PrestaShop#24419]
Hello,
When an order is created by an admin on the BO, the stock variation associated with that order is registered as "Employee Edition" - the same as a manual modification of the stock.
As a result, for a shop where many orders are created on the BO, it is impossible to differentiate orders from manual stock changes.
Any other labelling for admin orders would be favourable - e.g. "Employee Order"...
Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @sanji-japan 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
