### ISSUE TITLE
$logger in ps_accounts and ps_checkout must be protected not private

### ISSUE THREAD

**Issue by simoutn** [PrestaShop/PrestaShop#24418]
#### Describe the bug

when i install prestashop 1.7.7.3 , and i installed some modules , i found that i can't access to my modules manager and i get this message

Compile Error: Access level to Ps_accounts::$logger must be protected (as in class Module) or weaker
I can't make an override because the variable is private

#### Expected behavior

I want that you change $logger from private to protected

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @simoutn 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
