### ISSUE TITLE
Ability to add versions to js and css files

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#24410]
Hello guys,
#### Describe the bug
when we change css and js files for a module, we need to add a version to update clients caches to get up to dated files.
There is a need to specify the version when we register js and css files with these methods in controllers: 

- **registerJavascript**
- **registerStylesheet**

#### Steps to reproduce

1. Fresh install
2. Make sure the CCC is disabled
3. Enable Debug mode
4. Change anything in CSS/JS
5. Changes aren't visible on front for client

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.3

**Comment by Triloworld** [comment]
Do this patch support debug mode? 
In this mode, developer experience working with client will be improved.
I have same problem before enabling CCC as files don't update on frontend in mobile view.

**Comment by samberrry** [comment]
@Triloworld 
yes it works with debug mode and also with CCC.
An explanation for CCC:
as the reducer uses hash for all assets' file names, so it works fine with CCC. 

CCC file name generation:
**hash**(list of js/css file names => "themes/classic/assets/js/theme.js?v1.2")

So, when we update version for your js/css files, the code for your js/css will be regenerated, and the client gets the up to dated file.

**Comment by samberrry** [comment]
@Triloworld 
but if you use CCC there is an option already. You can update the following configuration in ps_configuration to update your cache file names, this will trigger your clients to update their cache.

**PS_CCCJS_VERSION**

**Comment by samberrry** [comment]
@Triloworld 
if you have enabled CCC, to regenerate cache file names try to clear Presta **Cache** through BO.

**Comment by hibatallahAouadni** [comment]
Hello @Triloworld 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

_PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack)._

Thanks!

**Comment by Triloworld** [comment]
@samberrry yes, but CCC is mode design for production.
When I work on website i disable it and query versions will bust cache in client end. 
@hibatallahAouadni It's not only my issue. Pleas re-enable. What is needed? THIS IS NOT A BUG, a FEATURE REQUEST ! :)
With pull request as well from fellow @samberrry to give all details that is required in guide. 

I can reproduce as well:

1. Fresh install
2. Make sure the CCC is disabled
3. Enable Debug mode
4. Change anything in CSS/JS
5. Changes aren't visible on front for client

**Comment by Triloworld** [comment]
@samberrry Pleas, add in title that is "Feature: " as well because clearly is that type of solution there. 
Versions aren't needed on CCC as files have unique names and change base on modification of content and clearing cache.

**Comment by hibatallahAouadni** [comment]
@Triloworld could you please provide your PrestaShop and PHP version :pray:

**Comment by Triloworld** [comment]
@hibatallahAouadni Of course. I will provide all details:

PHP: 
> PHP 7.3.27-9+0 ~ 20210227.82+debian10 ~ 1.gbpa4a3d6 (cli) (built: Feb 27 2021 15:50:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.27-9+0 ~ 20210227.82+debian10~1.gbpa4a3d6, Copyright (c) 1999-2018, by Zend Technologies

PrestaShop:
> 1.7.7.2

It is not in any way connected to PHP version, but new Presta 1.7 don't support that solution right now

**Comment by hibatallahAouadni** [comment]
Hello @Triloworld 

Thanks for all the infos :relaxed: 
Could you please provide a screenshot of your Smarty Performance (like this one):

![image](https://user-images.githubusercontent.com/23308427/117657235-9c942800-b199-11eb-8479-4acf17a42d2e.png)

Thanks!

**Comment by samberrry** [comment]
@Triloworld 
yes the mentioned PR - patch (https://github.com/PrestaShop/PrestaShop/pull/24409), will fix your issue, this works when CCC is disabled, as when it's enabled we do not need versioning.

**Comment by Triloworld** [comment]
<img width="1227" alt="Zrzut ekranu 2021-05-10 o 14 18 47" src="https://user-images.githubusercontent.com/2671726/117658127-a9654b80-b19a-11eb-924f-7131096f2247.png">

CSS/JS files in this scenario are required to be updated . They aren't as there no option to force flush cache on frontend. Query will fix it

**Comment by Triloworld** [comment]
@samberrry This query version by default is null (https://github.com/PrestaShop/PrestaShop/pull/24409/commits/67620047f4f1a5d6738131d82ab717c1946d1ed1#diff-e9c654ff3fbf8e3c8df70b0016b88b26b9cb148f4575a53e42a1a52977395d3aR55). 
Maybe create by date of file modification or some time() value? 
Every change will generate new query and flush frontend without additional work or flush in any request

**Comment by samberrry** [comment]
@Triloworld 
it should be set when you call the registerJavascript or registerStylesheet

```
$this->context->controller->registerJavascript(
				'modules/'.$this->name.'/views/js/javascriptjs',
				[
				  'priority' => 200,
				  'attribute' => 'async',
				  'position' => 'bottom',
				  'inline' => false,
                                  **'version' => 'v1.2'**
				] 
			);
```
you should just change the version here when you register your js/css

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone please reproduce the issue :pray:

**Comment by Triloworld** [comment]
In my dev env if I change "js" file then i need to remember to update version. It's like one step, my answer to this is  automation. It will ensure that query is change according to change in content.

This is how in Magento this can be done: https://github.com/jreinke/magento-suffix-static-files
It generate query version by taking change in file and use it as a hash for query. You don't touch configuration file, you don't compress file and you get fresh ones on front if any change occur. 
Two option, your and mine is on this line: https://github.com/jreinke/magento-suffix-static-files/blob/2bda7884c6ee5ef9f8e41fc5682d34dd08d6ece6/app/code/community/Bubble/Queryfier/Block/Page/Html/Head.php#L56

In Prestashop, along with CCC this can be in core as DX improve and fix many issue of "not see actual version" syndrome in front view

**Comment by jolelievre** [comment]
Thank you @samberrry
