### ISSUE TITLE
Getting this message when viewing orders with Customized product.

### ISSUE THREAD

**Issue by MattC1984** [PrestaShop/PrestaShop#24414]
#### Describe the bug

Getting this message when viewing orders with Customized product.
Oops... looks like an unexpected error occurred.

Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderProductCustomizationForViewing::__construct() must be of the type string, null given, called in /homepages/28/d852021950/htdocs/test/src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php on line 118

[Symfony\Component\Debug\Exception\FatalThrowableError 0] 

I tried to look up a fix but have not had any luck

#### Steps to Reproduce

once a Customized product has been placed into order.

click on orders then got to orders. click on order with Customization you get this message.
![screencapture-blueline-design-direct-co-uk-dbm1k6uxjsb2snxv-index-php-sell-orders-1-view-2021-05-09-12_07_11](https://user-images.githubusercontent.com/83906551/117569749-1c00f900-b0bf-11eb-8aed-bbce94372ce1.png)

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/83906551/117569431-887af880-b0bd-11eb-8bd7-f9cbdd79af58.jpg)
![screencapture-blueline-design-direct-co-uk-dbm1k6uxjsb2snxv-index-php-sell-orders-1-view-2021-05-09-12_01_22](https://user-images.githubusercontent.com/83906551/117569585-4aca9f80-b0be-11eb-8a42-65b2d637e345.png)
![screencapture-blueline-design-direct-co-uk-dbm1k6uxjsb2snxv-index-php-sell-orders-1-view-2021-05-09-12_01_11](https://user-images.githubusercontent.com/83906551/117569589-4d2cf980-b0be-11eb-89d0-dd2644edf68c.png)
![screencapture-blueline-design-direct-co-uk-dbm1k6uxjsb2snxv-index-php-sell-orders-1-view-2021-05-09-12_00_36](https://user-images.githubusercontent.com/83906551/117569592-4ef6bd00-b0be-11eb-8601-031facca2eaa.png)

#### Additional information

* PrestaShop version: 1.774
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @MattC1984 

Did you upgrade your shop lately or it's a fresh install?
Could you please provide a screenshot of the customized product :pray: 
If you upgraded your shop lately, so could you please check this issue #24158 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @MattC1984 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
