### ISSUE TITLE
[BlockWishlist] Module not visible when installed manually

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24411]
#### Describe the bug

I have a versionned prestashop, i install it in my dev environment, git commit & push
I pull on the prod, module not visible, the module appear as a "Theme module" is it related ?

#### Expected behavior

The module should be visible

#### Steps to Reproduce

1. Setup a prestashop in a git repo
2. Setup the module
3. Git commit & push
4. Setup the prestashop in another server, git pull, the module not appear.
5. To make it appear, i have to install it from the module page via 'install module" and drag drop the zip.

The problem could maybe be reproductible by installing module via ftp client

**Screenshots**

![image](https://user-images.githubusercontent.com/4645967/117539304-552b6180-b00a-11eb-8e68-1a2cb891e71e.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

To install the blockwishlist module, you need to follow these steps:

1. clone `blockwishlist` directly into `/modules/`
2. make sure that you’re on `dev` branch
3. `composer install`
4. `npm install`
5. `npm run build`
6. head to **Modules catalog** and search for the “**wishlist**”, install it from there

Please check and feedback.

Thanks!

**Comment by henri9813** [comment]
Hello,

My question is more, why the module appear as theme module and not for a global module ?

I setup the module via the form on the module page.

I git push

and on the prod, the git pulll doesn't permit to view the module installed.

I didn't make any excludes.

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

I see, could you please post your problem on the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack), our developers and contributors will help you to solve your problem :wink: 
Sorry, but I have to close the issue cause it's not a PrestaShop Core bug :pray: 

Thanks for understanding!

**Comment by henri9813** [comment]
Hello @hibatallahAouadni .

If i can't open issue here, can you allow us to open issue on the project page ?

Best regards

**Comment by matks** [comment]
> If i can't open issue here, can you allow us to open issue on the project page ?

Hello, we use GitHub issues only to discuss about bugs and new features for the PrestaShop project. This repository is a bug tracker and a feature tracker, this is why we ask discussions do not happen here.

As mentioned by @hibatallahAouadni we have a Slack channel for discussions 😉  . https://github.com/PrestaShop/open-source/tree/master/slack
