### ISSUE TITLE
$logger in ps_accounts and ps_checkout must be protected not private

### ISSUE THREAD

**Issue by simoutn** [PrestaShop/PrestaShop#24420]
#### Describe the bug

when i install prestashop 1.7.7.3 , and i installed some modules , i found that i can't access to my modules manager and i get this message

Compile Error: Access level to Ps_accounts::$logger must be protected (as in class Module) or weaker
I can't make an override because the variable is private

#### Expected behavior

I want that you change $logger from private to protected

#### Steps to Reproduce

1- install module paypal
2- Go to "Modules manager"

**Screenshots**
Error Message
Compile Error: Access level to Ps_accounts::$logger must be protected (as in class Module) or weaker
![Error private logger variable](https://user-images.githubusercontent.com/15145202/117629716-be31e700-b17a-11eb-8ff5-21d826f1e137.JPG)

#### Additional information
Link of error : admin_123/index.php/improve/modules/manage
* PrestaShop version: 1.7.7.3
* PHP version: 7.2.32

**Comment by matks** [comment]
Hello @simoutn 

This is very strange because class Module has no property `$logger`, you can verify https://github.com/PrestaShop/PrestaShop/blob/1.7.7.3/classes/module/Module.php

Maybe your `Module` class is overriden or customized?

**Comment by hibatallahAouadni** [comment]
Hello @simoutn 

Thanks for respecting the template :clap: 
It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on [Addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748)

We will close this issue.

Thanks!
