### ISSUE TITLE
Wrong canonical url into paginations like for category pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24439]
Hi
Today a seo agency reports to my customer a problem with canonical urls present into category pages when there are paginations

#### Describe the bug

In the category pages, if there are some paginations, the canonical url from the second page onwards report the parameter of the page, instead it should reports the url of the first page.

#### Expected behavior

all paginations should report the same canonical url
it should like this one

`<link rel="canonical" href="http://domain.com/prestashop/prestashop17xx/6-accessori">`
and not like this
`<link rel="canonical" href="http://domain.com/prestashop/prestashop17xx/6-accessori?page=2">`

instead it is set as the canonical url the url of selected pagination. In this mode these canonical urls are useless.
The canonical url should avoid the content duplications, because each paginations have the same meta title, meta description, the same h1, the same category description ...

#### Steps to Reproduce

go into the second page of a category with paginations

**Screenshots**
![2](https://user-images.githubusercontent.com/653230/117733555-0dffc500-b1f2-11eb-8d6e-130cdbfbc615.png)
![1](https://user-images.githubusercontent.com/653230/117733562-12c47900-b1f2-11eb-8db6-1ac1db9ec174.png)
![7](https://user-images.githubusercontent.com/653230/117733564-13f5a600-b1f2-11eb-9351-5dabf9510134.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

this is a big seo problem, reported 1-2 years ago, and now also notified by an agency specializing in seo
for this bug is it possible to fix it quickly?

thanks

bye

**Comment by matks** [comment]
Hi @maofree 

> Today a seo agency reports to my customer a problem with canonical urls present into category pages when there are paginations

SEO is unfortunately a complex area where it can happen that, if you ask 3 SEO experts the same question, you are provided 3 different answers 😅  .

We also have a SEO agency that does audits for PrestaShop project. Please understand we'll have to validate this with them, because of the chaos around SEO topics. SEO is more about reverse-engineering Google algorithms than a set of clear rules 😞  so it's hard to have a clear vision of it.

**Comment by kpodemski** [comment]
I don't agree with you @maofree - it's not a bug :)

You don't want to index other products from your categories? Ok, that's fine, canonical should point to first page, but I read reports from some SEO agencies where canonical should point to subpages and all pages from categories should be indexed. 

Like @matks said, three seo experts, three different opinions.

**Comment by Maofree** [comment]
Hi @matks  and @kpodemski 
I know about the lack of clarity on the seo that many say different things even on the same points, but let's try to use logic, I think we can even get there by ourselves to analyze this thing.

1) the current solution is not good for google because in the search console it reports content duplications.
2) the fact of warning google that it has to index only the first page of a pagination, I don't think it means denying the crawl of all the pages of the pagination. I believe that the links to the product pages, present in the product blocks, will always be considered and this will always lead google to consider the various product pages and then to scan them.
with the canonical link all you do is tell google, look do not index them because they have the same contents and do not consider them as duplications, everything else will always be scanned and incited, I do not think google is stupid, indeed over time it has a quality better scan.

it is simple to check what is the true about this point, I take a big site made with magento and I check how to manage this seo point.

go here, this site is one of the most important in Italy on bio
https://www.farmae.it/dietetici.html
here use this canonical url
`<link rel="canonical" href="https://www.farmae.it/dietetici.html" />`

for the second page use the same url and not `https://www.farmae.it/dietetici.html?p=2`
`<link rel="canonical" href="https://www.farmae.it/dietetici.html" />`

trust me these paginations should be managed in the same mode, because it is logic, used by other cms, remove errors from google search console and does not prevent the scanning of the products in the various paginations, otherwise all the sites made with magento and other cms would all be avoided by those who want strong sites on seo

bye

**Comment by Maofree** [comment]
I check a site made with shopify and it use your solution

https://www.workshopitaly.net/collections/antinfortunistica

**Comment by Maofree** [comment]
magento instead use my solution

`https://www.masterfer.it/aria-compressa?p=2`

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Related to #13737
Could you please check this issue #18109 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Maofree** [comment]
Hi
yes #13737 is the same, the other speak something about the pagination but I'm not sure, it explain also other things

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Thanks for your feedback!
As we are aware of this issue and it is already in our debug backlog, this issue is a duplicate of #13737. 
Well, I will ping the product team on the original issue :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #13737
