### ISSUE TITLE
Fatal error from ps_metrics

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#24438]
DO NOT force install **ps_metrics** module on fresh Prestashop 1.6 installations. Trying to uninstall it always ends with fatal error

> PHP Fatal error:  Uncaught PrestaShop\PsAccountsInstaller\Installer\Exception\ModuleNotInstalledException: Module not installed : ps_accounts in (...)\modules\ps_metrics\vendor\prestashop\prestashop-accounts-installer\src\Installer\Facade\PsAccounts.php:51

Clearly this module was made for 1.7, so why is it forced on 1.6?

#### Steps to Reproduce

1. Install fresh Prestashop 1.6 (ps_metrics will be installed automatically)
2. Go to Modules and try to uninstall ps_metrics
3. Module gets uninstalled, but the result is always fatal error

#### Additional information

* PrestaShop version: 1.6
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

PS: FYI @RomainBocheux 

Thank you

**Comment by SharakPL** [comment]
@hibatallahAouadni Please read issue description more carefully. I'm well aware 1.6 is not maintained. This issue is about the **bug in ps_metrics**, not in Prestashop 1.6 (it's simply affected by it).

Bug is still there so why did you close it?

**Comment by matks** [comment]
@SharakPL ps_metrics is not a module provided by PrestaShop company, not PrestaShop open source project. So @hibatallahAouadni is right to close this issue because it does not belong to this repository scope.

**Comment by matks** [comment]
@SharakPL I checked the module and the Addons data, ps_metrics is compatible with PS 1.6
https://addons.prestashop.com/fr/analyses-statistiques/49583-prestashop-metrics-beta.html

So if there is a bug (it happens !) with the module, you can report it to the PS Metrics team using the "Help" tab in the module (you can reach them by email). 😉

**Comment by SharakPL** [comment]
> 
> 
> ps_metrics is not a module provided by PrestaShop company

Clearly it is 
![obraz](https://user-images.githubusercontent.com/5007456/117776580-05cc7780-b23c-11eb-908a-a9c283562633.png)

1.6 not maintained anymore was not a problem when Prestashop created a module in 2021 for 1.6 and forces it there on new installations so why the problem this module caused there is suddenly ignored. That's just bad policy 😬

**Comment by matks** [comment]
> and forces it there on new installations

The module is not forced on installations, it is pushed to be available but still needs to be installed by user.

> so why the problem this module caused there is suddenly ignored

Because you are reporting the issue on the wrong place.

If tomorrow you go complain to Microsoft Skype team about an issue in Windows, they will ask you to report it to Windows team, it's simple.

The people that built PS Metrics are great people 😉  you just need to contact them. We are not linked to them which is why we close this issue.

**Comment by SharakPL** [comment]
> 
> > and forces it there on new installations
> 
> The module is not forced on installations, it is pushed to be available but still needs to be installed by user.
> 

No, it is forced. Agency I build shops to still wants only PS 1.6 so I install them a lot and lately all new installations have Metrics installed by default and all of them throw fatal error when trying to uninstall it which is quite obvious since PS 1.6 doesn't have **ps_accounts** module AFAIK

> > so why the problem this module caused there is suddenly ignored
> 
> Because you are reporting the issue on the wrong place.
> 
> If tomorrow you go complain to Microsoft Skype team about an issue in Windows, they will ask you to report it to Windows team, it's simple.
> 
> The people that built PS Metrics are great people 😉 you just need to contact them. We are not linked to them which is why we close this issue.

I get that and I completely agree. Simply couldn't find any specific repository for it like it is for all other free modules so I figured it's part of Prestashop 1.7 since it's made by Prestashop and is installed by default.

I'll follow your advice and report it from addons page then.
Thanks
