### ISSUE TITLE
theme/XXX/templates/catalog/_partials/facets.tpl is not used

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24432]
#### Describe the bug

Read this https://github.com/PrestaShop/PrestaShop/issues/23104

Hovewer, if i a place this file in the `themes/XXXX/modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl` the override works !

#### Expected behavior

When i edit the templates/catalog/_partials/facets.tpl  file, it should override the default tpl.

#### Steps to Reproduce

1. Create a theme
2. Change facets.tpl content !
3. Look, no effect.

#### Possible solution

Move the file to the `themes/XXX/modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl` to avoid confusion.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.4

**Comment by henri9813** [comment]
PR here: https://github.com/PrestaShop/PrestaShop/pull/24433

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

Could you please provide your PrestaShop and PHP versions. By the way we already discussed about this file's purpose [here](https://prestashop.slack.com/archives/CTKHSPWPM/p1612429273073400).
But I forget what we decided to do :sweat_smile: @PierreRambaud @Hlavtox could someone remind me :sweat_smile: 

Thanks!

**Comment by henri9813** [comment]
Hello @hibatallahAouadni  :-) 

Prestashop 1.7.4 php 7.4 

Indeed, but at this time, the theme has a useless file which is now used if the file is in the good place. :-)

**Comment by hibatallahAouadni** [comment]
> Prestashop 1.7.4 php 7.4

Ping @henri9813 you mean 1.7.7.4 or 1.7.4.x?

**Comment by henri9813** [comment]
1.7.7.4 Sorry :-)

**Comment by kpodemski** [comment]
Following the discussion from PR, it doesn't make sense to delete this file as Faceted search system **is not** only related to the Faceted Search module. Facets can be implemented by third-party solutions and their may use this default file.
