### ISSUE TITLE
An error when debug mod is enabled and an error when maintenance mod is enabled

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#24431]
#### Describe the bug

When i active maintenance mod i have an error

#### Expected behavior

No error 

#### Steps to Reproduce

1. Active Maintenance mod
2. Go on your shop 

**Screenshots**

![Capture d’écran de 2021-05-10 16-58-32](https://user-images.githubusercontent.com/5064590/117680780-c5c0b280-b1b1-11eb-9d32-4b977c1c1fc1.png)

#### Additional information

* PrestaShop version: dev
* PHP version: 7.7.3

**Comment by PierreRambaud** [comment]
> #### Describe the bug
> When i active maintenance mod i have an error
> 
> #### Expected behavior
> No error
> 
> #### Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Active Maintenance mod
> 2. Go on your shop
> 
> **Screenshots**
> 
> ![Capture d’écran de 2021-05-10 16-58-32](https://user-images.githubusercontent.com/5064590/117680780-c5c0b280-b1b1-11eb-9d32-4b977c1c1fc1.png)
> 
> #### Additional information
> * PrestaShop version: dev
> * PHP version: 7.7.3

Hi @okom3pom 
You probably install prestashop without building asset (which is require when using source instead of archive zip).

I don't manage to reproduce the issue.

**Comment by ghost** [comment]
I have two ways,  i will close and open new issue when is clarified

In 178X i don't have style when maintenance mode enabled

![Capture d’écran de 2021-05-10 17-17-38](https://user-images.githubusercontent.com/5064590/117682770-b3477880-b1b3-11eb-985b-6af7825f5d41.png)

In dev i have an error when debug is enabled.

![Capture d’écran de 2021-05-10 17-14-44](https://user-images.githubusercontent.com/5064590/117682567-7e3b2600-b1b3-11eb-943b-e8e7ea0ad6f8.png)

**Comment by ghost** [comment]
I just  try  a nightly now and i don't have the error but i have don't style.

I made new tests tomorrow

**Comment by arouiadib** [comment]
@okom3pom Just a note a about the error , it is related to image types not installed in database.
The fix is here: https://github.com/PrestaShop/PrestaShop/issues/17539

**Comment by ghost** [comment]
Thank you
