### ISSUE TITLE
Two translations are not executed.

### ISSUE THREAD

**Issue by pixmax** [PrestaShop/PrestaShop#24446]
The bug I would like to report concerns two sentences in the checkout process in the personal data that are not translated. This problem also existed last year with previous versions. The described error is also included on Prestashop.com in the demo version. For this you have to select German in the language selection.
It is the sentences:

_"The personal data you provide is used to answer queries, process orders or allow access to specific information. You have the right to modify and delete all the personal information found in the "My Account" page."_

and

_"I agree to the terms and conditions and the privacy policy"._

I was able to **find the first sentence in 9 files** using Notepad. In almost all of them the correct German translation was also included, except in **ps_dataprivacy,php**.
In two translation files in **App/Resources/** it is noticeable that in **ModulesDataprivacyAdmin.de-DE.xlf** the translation is included. but not in **ModulesDataprivacyShop.de-DE.xlf**. This is strange, since the checkout is a process in the shop and not in the back office.

The **second sentence is found in only one file**. In **psgdpr.php in modules/psgdpr**. This file also contains a German translation. But it cannot be executed for some reason. Also mind the second screenshot.

By the way, for Brazil, the Portuguese translation would be better than the current Spanish one, right?

Anyway, it is beyond my abilities to find the error. Last year I used another checkout module to replace this part. But it is not possible to open the store if these sentences are not translated and the customer is told this important information only in English. That would be grounds for an expensive warning from a lawyer. 

#### Expected behavior

It would be very good to finally find and eliminate this bug.

#### Steps to Reproduce

1. Go to https://demo.prestashop.com/#/en/front
2. Switch to language "Deutsch"
3. put a product in your shopping cart.
4. Go to the checkout.

![Screenshot_2021-05-10 amthof art(1)](https://user-images.githubusercontent.com/22912788/117793794-dbcf8100-b24c-11eb-8c89-9bf0ec64aa53.png)

![psgdpr](https://user-images.githubusercontent.com/22912788/117794407-8182f000-b24d-11eb-9965-a337ef4fa3f3.jpg)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by pixmax** [comment]
It seems the **first step** is done. Great. What was the problem?


![first_step](https://user-images.githubusercontent.com/22912788/117814195-493adc00-b264-11eb-92d0-f9b38c802622.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @pixmax 

About the module traduction, you have two methods to change the translations:

1. **BO**>**IMPROVE**>**International**>**Translations**
2. Select **Installed modules translations** as **Type of translation**
3. Select the module
4. Select your language
5. Click on **Modify**
6. Enjoy it :wink: 

Or:

1. **BO**>**IMPROVE**>**Modules**>**Module Manager**
2. Search your module
3. Click on **Configure**
4. Enjoy it :tada: 

Check the attached screen record below:

https://drive.google.com/file/d/1ONrLHRLq18oWtzrivuu_sG8ojMb5Og2l/view

Please check and feedback.
Thanks!

**Comment by pixmax** [comment]
Hi Hibatallah, 
great video. Many thanks for that. In the meantime I could changed also the long sentence. Also only in the module manager. In translation is nothing to found. 
But it is eally strange when all translations are there, but they could not be used. What you and I did now ist a change. so I think there is still a bug, and it wil happen again that someone did not know how to change these sentences.

Anyway I'm very thankful for your great support. And I'm happy I could learn something new.
Kind regards
Michael

**Comment by hibatallahAouadni** [comment]
it's my pleasure :relaxed:
