### ISSUE TITLE
Cannot override a Cart method getPackageShippingCost

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#24440]
#### Describe the bug

According to docs I could do it in my module by making a Cart class that extends CartCore by putting Cart.php inside modules/<modulename>/override/classes directory.

My specific goal is to make this method return zero if a current order value is above the free shipping price, and the country of the delivery address is different than Y.

#### Expected behavior

Make this code to call die() when we open a cart steps form / checkout form

```
<?php

class Cart extends CartCore
{
    public function getPackageShippingCost(
        $id_carrier = null,
        $use_tax = true,
        Country $default_country = null,
        $product_list = null,
        $id_zone = null,
        bool $keepOrderPrices = false
    ) {
        die();
    }
}
```

#### Steps to Reproduce

Make any module that tries to override Cart class that way

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

I know that there is something something about Symfony containers and such, but none of them actually touches that method so I am pretty much deeply stucked with that issue

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

Could you please check this issue #13669 it seems similar to yours.
If, it's not, could you please provide a module to help me reproduce the issue.

Thanks!

**Comment by ProteanCode** [comment]
> Hello @ProteanCode
> 
> Could you please check this issue #13669 it seems similar to yours.
> If, it's not, could you please provide a module to help me reproduce the issue.
> 
> Thanks!

Hmm I do not see much of a correlation with my case, or at least I didn't reach that point yet.
I just want to override the body of that method

**Comment by ProteanCode** [comment]
I do think about using runkit7 as a workaround

**Comment by ProteanCode** [comment]
runkit seems to be glitchy with dockerized prestashop so this is not an option

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

> Make any module that tries to override Cart class that way

Could you please provide clear and concise steps to reproduce the issue :pray:

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
