### ISSUE TITLE
Total Products Price doesn’t Show in the Confirmation page

### ISSUE THREAD

**Issue by num47** [PrestaShop/PrestaShop#24444]
#### Describe the bug

I was demo creating an order with a product that has product customization option. After confirming the order, the price of the product was not being shown in the "Total Products" Section. But, the total price at the bottom was showing right. 

#### Expected behavior

The price of the product should have been shown in that section. 

#### Steps to Reproduce

1. Create an order of this product - https://beefy-whistle.demo.prestashop.com/en/home-accessories/19-customizable-mug.html
2. You will see after order confirmation in the order confirmation page that the price of the product is shown '0.00' in the 'Total Products' section. 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
<img width="1131" alt="1" src="https://user-images.githubusercontent.com/33420890/117785463-6bcdf480-b266-11eb-8e29-62312c87d6af.png">

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @num47 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10912. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #10912
