### ISSUE TITLE
AdminSpecificPriceRule Not working properly on Safari. 1.7.7.3  

### ISSUE THREAD

**Issue by nervusdm** [PrestaShop/PrestaShop#24448]
Hey,

 

It seems that AdminSpecificPriceRule does not work fine on Safari. (Mac M1 ARM).
I guess it's about javascript, even there is no obvious error.

 

Condition group saved does not load (it's always the first category for example).
Same for attributes, features, supplier...

In fact, on Safari, the "condition" group seems buggy.

 
Works fine on Chrome.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @nervusdm 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24147. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #24147
