### ISSUE TITLE
Bug sort by price products frontend

### ISSUE THREAD

**Issue by sergiobm3** [PrestaShop/PrestaShop#24451]
You cannot sort by product price in frontend whose price is 0, but the combination has the value.

**Comment by hibatallahAouadni** [comment]
Hello @sergiobm3 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
