### ISSUE TITLE
Update issue in 1.7.7.4

### ISSUE THREAD

**Issue by Tejobolten** [PrestaShop/PrestaShop#24453]
#### Describe the bug
/var/www/mixje.com/public_html/src/Adapter/EntityMapper.php line 99 - array_key_exists() [function.array-key-exists]: Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

A clear and concise description of what went wrong.
The iclick update went ok till the moment when the database is updated. I get the above line several times  and then the update goes on.  After reconnecting to the backoffice it gives the Prestashop 1.7.7.4   the website is not reachable after this update with a page 500 error After this I have to role back to the 1.7.7.3 version.
#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce
only by udating again

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Tejobolten 

Could you please provide more details, clear and concise steps to reproduce and a screenshot of the error.
Please check and feedback.

Thanks!

**Comment by antho-girard** [comment]
Hi

I've got the same error but with **PHP 7.4** which is normal as it is not supported on PrestaShop 1.7.7.3.
Otherwise, everything looks good with PHP 7.3.

I think this ticket is related to https://github.com/PrestaShop/PrestaShop/issues/19463#issuecomment-636715107

**Comment by Tejobolten** [comment]
Hello @ hibatallahAouadni ,

I couldn't write earlier back. I had to restore my back-up to have the possibility to go on. I will do the update again and  give the needed information here.

**Comment by Tejobolten** [comment]
Hello @hibatallahAouadni ,
I have to close this item. I did the update again, cleared the cash, cleared the browser. Restart the browser, logged in to the back office., undo the shop in maintenance. Test de shop  and everything is working fine... 
Still i get this line a lot:
/var/www/mixje.com/public_html/src/Adapter/EntityMapper.php line 99 - array_key_exists() [function.array-key-exists]: Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead
I give here the info and images of back office while updating also the log.
![1click01](https://user-images.githubusercontent.com/84019200/118411147-66701000-b693-11eb-98fe-da541ac43096.JPG)
![1click02](https://user-images.githubusercontent.com/84019200/118411148-6708a680-b693-11eb-9841-f6b862ffa36e.JPG)
![1click03](https://user-images.githubusercontent.com/84019200/118411149-6708a680-b693-11eb-8fb0-a665c7022a8d.JPG)
[log of update.txt](https://github.com/PrestaShop/PrestaShop/files/6489948/log.of.update.txt)

**Comment by hibatallahAouadni** [comment]
@Tejobolten Glad that your issue is solved :tada: 
Closing the issue.
