### ISSUE TITLE
?filter[name] bug

### ISSUE THREAD

**Issue by sergiobm3** [PrestaShop/PrestaShop#24452]
#### Describe the bug

I have a product option called "Size [mm]", but when I use the http web service filter ... / product_features /? Filter [name] = [Size [mm]] returns all options. 

#### Expected behavior
 How can I arrange for only that option to be returned?

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.3

**Comment by hibatallahAouadni** [comment]
Hello @sergiobm3 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
