### ISSUE TITLE
FO - Checkout page - incorrect redirection when we use another address for invoice as a guest

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24465]
#### Describe the bug

In the FO > checkout page, when we use another address for the invoice as a guest, we are redirected to the Information step instead of the Shipping method step

#### Expected behavior

After submitting the address, the user should be redirected to the shipping step

#### Steps to Reproduce

1. Go to FO and add a product to the cart
2. Click on "proceed to checkout"
3. Fill out the first form (information) **without** filling in the password
4. Click on continue
5. Fill out the second form (address)
6. **Uncheck** "use this address for the invoice"
7. Click on continue
8. Click on "Add an address"
9. Create a new address
10. Click on "continue"
11. See error => redirection to the Personal information step instead of Shipping method step => NOK
12. Click on the Address again (the invoice address selected is the same for shipping address selected => NOK

https://drive.google.com/file/d/1fXLp4rdBqyhGAESs3c4sLm7zoqsuQgzt/view?usp=sharing
In the 1774 => ok
https://drive.google.com/file/d/1F8GnXVwiEsyERV-eIdry0pefGv9VP-HI/view?usp=sharing

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2

**Comment by atomiix** [comment]
@khouloudbelguith I've not been able to reproduce this issue 🤔

I tried clicking on "Add an address":

https://user-images.githubusercontent.com/2168836/121057502-a5d7db00-c7bf-11eb-87f7-ae6407300e66.mov

and without clicking:

https://user-images.githubusercontent.com/2168836/121057527-ad977f80-c7bf-11eb-9823-b2c1842eb488.mov

**Comment by marionf** [comment]
@hibatallahAouadni Could you please try to reproduce this issue ?

**Comment by Robin-Fischer-PS** [comment]
Hi there,

I'm not able to reproduce the error at step 11. I can reproduce the one at step 12, but I can also reproduce it on 1.7.7 and 1.7.6, so it's not a regression

**Comment by khouloudbelguith** [comment]
Hello :slightly_smiling_face:

Sorry for the delay.
In fact, the issue is fixed with another PR I think :tada: 
178_11_mai was NOK: https://drive.google.com/file/d/1_QzL9zLTMFX0hMMnLOuQjmigouFep1nn/view?usp=sharing
178x => ok: https://drive.google.com/file/d/1vbuwl570sC0CSdNS1bWf9ktniuNPrusy/view?usp=sharing

I will close the issue.

Thank you!
