### ISSUE TITLE
FO - Create Account / Checkout page - Order as a guest / Adresses step - Exception displayed when Firstname, Lastname or City are invalid

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24464]
#### Describe the bug

In the FO > Checkout page > Order as a guest part, when we set the firstname & lastname with invalid data, an exception is displayed
Also, when we create an address in the checkout page with invalid firstname & lastname & City => an exception is displayed.

Edit by @Robin-Fischer-PS : In FO > Create an account, an exception is also displayed when the firstname and/or lastname fields contain invalid characters.

#### Expected behavior

We should have an alert as in PS1774
![image](https://user-images.githubusercontent.com/16067358/117840616-9f1b7e00-b27c-11eb-8db7-91f51589b3a9.png)
![image](https://user-images.githubusercontent.com/16067358/117842777-8b711700-b27e-11eb-9721-ae9a3b4cd9f5.png)

#### Steps to Reproduce

1. Go to FO
2. Add a product to the cart and proceed to checkout
3. In the Checkout page > Create a customer or a guest with invalid firstname & lastname
4. Set other required fields and click continue
5. See error
6. In the addresses step: create a new address with invalid firstname & lastname & city
7. Click continue
8. See error

Other steps : 

1. Go to FO > Create an account
2. Fill in the fields, with invalid character in "firstname" or "lastname" fields (for example "lastname1"
3. Save : An exception is displayed.

**Screenshots**
1. lastname
![FO_guest_lastname](https://user-images.githubusercontent.com/16067358/117840928-dc800b80-b27c-11eb-9332-dc0a5acb0b6b.png)
2. Firstname
![FO_guest_firsname](https://user-images.githubusercontent.com/16067358/117840930-dc800b80-b27c-11eb-9177-e2062749e465.png)
3. City
![FO_address_city](https://user-images.githubusercontent.com/16067358/117843033-c3785a00-b27e-11eb-8fea-93245017e259.png)
4. address firstname & lastname
![FO_address_lastname](https://user-images.githubusercontent.com/16067358/117843103-d25f0c80-b27e-11eb-932e-3206b7e0c305.png)
![FO_address_firstname](https://user-images.githubusercontent.com/16067358/117843108-d3903980-b27e-11eb-9f53-c6f67998a9d8.png)

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2 & 7.4

**Comment by Robin-Fischer-PS** [comment]
Hi,

I edited the issue to add another way to reproduce this bug (initially reported in #24502 , which is now closed and tag as duplicate).
