### ISSUE TITLE
FO - Order confirmation page - cannot add a popular product to the wishlist

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24467]
#### Describe the bug
In the FO > Order confirmation page, when we try to add a popular product to the wishlist => the modal is not displayed

#### Steps to Reproduce

1. Greate an order from the FO with a customer
2. On the Order confirmation page, the list of popular products is displayed
3. try to add the first to the wishlist
4. See error: nothing happens when we click on the favorite icon
![FO_order_confirmation_wishlist](https://user-images.githubusercontent.com/16067358/117844157-bf007100-b27f-11eb-8970-f32c5c01bc77.png)

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.4, 1.7.8.x
* PHP version: 7.2
* Wishlist: 2.0.0

**Comment by NeOMakinG** [comment]
Duplicate and fixed in another PR
