### ISSUE TITLE
BO - Welcome module - Th pop up onboarding is not displayed in the step3/6 "step1" &  step4/6 "step2"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24463]
#### To do 
Fix the issue on the module and release it 

#### Describe the bug

When the `ps_mbo` module is installed, the popup onboarding is not displayed at step 4/6 "Get your shop ready for Payment" step2
![on_boarding_no_pop_up](https://user-images.githubusercontent.com/16067358/117839119-32ec4a80-b27b-11eb-9d48-26459cdaadae.png)
Version ps_mbo =2.0.1.
 the popup onboarding is not displayed at step 3/6 "Give your shop its own identity" step1 when ps_mbo installed and uninstalled

#### Expected behavior

The popup onboarding should be displayed

#### Steps to Reproduce

1. Fresh install 178 with English language & France country
2. Go to BO
3. Follow the welcome instructions
4. See error ate step 3/6 & step4/6

PS 1774 + Welcome v6.0.4 => ok

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2
* Welcome: v6.0.4

**Comment by jolelievre** [comment]
@atomiix this PR has been merged https://github.com/PrestaShop/PrestaShop/pull/24869 But it seems it's only a part of this issue so I guess we can't close it already
Is the missing part in the welcome module?

**Comment by atomiix** [comment]
@jolelievre Yes we can, the module has been fixed as well: https://github.com/PrestaShop/welcome/pull/116
