### ISSUE TITLE
Product V2 page - Indexation of product not done after creation

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24460]
#### Describe the bug

When creating a product fully on Product V2 page, the product is not automatically indexed. It is correctly indexed in classic Product page.

#### Expected behavior

The page should be indexed when created on Product V2 page

#### Steps to Reproduce

1. Go to Advanced Parameters > Experimental features
2. Enable Experimental Product Page
3. Go to Catalog > Products, click on "New product on experimental page"
4. Fill all needed fields, save the product
5. Go to FO, search for the product : The product is not displayed in the search
6. On another tab, go to BO > Catalog > Products > Edit product on classic product page, and just save the product on classic product page
7. Refresh the search on FO : The product is now displayed in the search

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed in #24774 by @matthieu-rolland
