### ISSUE TITLE
Combination product dont work

### ISSUE THREAD

**Issue by sergiobm3** [PrestaShop/PrestaShop#24475]
#### Describe the bug

I have many different combinations for a product and not all of them share the option. When I select a non-share option it is redirected to the first combination created. 

#### Expected behavior

That the options are updated depending on the combination that is chosen 

#### Steps to Reproduce

1. Create combinations that do not repeat option. for example this product in screenshots:
2. Add combinations like the screenshots.
3. Try to choose this combination

**Screenshots**

![image](https://user-images.githubusercontent.com/43613649/117947595-a2604980-b310-11eb-8051-363e30c145b1.png)
![image](https://user-images.githubusercontent.com/43613649/117947717-c3289f00-b310-11eb-8c8f-59ebcf045a64.png)
![image](https://user-images.githubusercontent.com/43613649/117947809-d63b6f00-b310-11eb-9f29-40022889ceea.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43613649/117948829-cd976880-b311-11eb-80ed-69f1b7a7679a.gif)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.33

**Comment by sergiobm3** [comment]
I found this bug, It's because there are character like '[', ']', '-'. Why not use there?

**Comment by hibatallahAouadni** [comment]
Hello @sergiobm3 

I didn't manage to reproduce the issue with PS1.7.7.4, see the attached screenr record below:

https://drive.google.com/file/d/1Z30x4ITYRp4ozTLHx6J6_PwIxbqV_qrY/view

Please check and feedback.
Thanks!

**Comment by sergiobm3** [comment]
Sorry, '-' is succesfull, try the product_option_value with ',' this is the one that fails

**Comment by florine2623** [comment]
Hello @sergiobm3 ,

I couldn't reproduce your issue in PS 1.7.7.4.
I used comma ,
hyphen -
and a mix of both.

Please check my screen record : 
https://drive.google.com/file/d/1wdErCW_M5x2QR9RNHgKUSDyu-CZFNEoW/view

Thanks!

**Comment by sergiobm3** [comment]
Sorry finally was my error I post other issue with the problem #24458. When I create multiple products, they rewrite id and generate this error.

**Comment by hibatallahAouadni** [comment]
@sergiobm3 Thanks for your feedback!
