### ISSUE TITLE
Blocking the new product edition page when multistore is used

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#24471]
Currently, when multistore is enabled, the product page is disabled in group shop context.

In the new experimental product page, multistore has not been tested yet, we don't know if it works properly even in all shop and single shop context.

So with @jolelievre we thought it would be a good idea to block the page and display a message if there is more than one shop enabled, until we make this page thoroughly multistore compatible.

@MatShir what do you think ?

Solution:

Display the following message:
'Note that this page is available in a single shop context only. Switch context to work on it.' in Admin.Notifications.Info

**Comment by Julievrz** [comment]
UPDATE: The domain was changed, so the following wording can be used without having to create a new one:
**'Note that this page is available in a single shop context only. Switch context to work on it.'** in **Admin.Notifications.Info**

Hi, to avoid creating a new string, I suggest using the following existing wording:

'Note that this page is available in a single shop context only. Switch context to work on it.' in Admin.Payment.Notification

The domain is not the good one, it should be in **Admin.Notifications.Info**: We can either change the domain during the next catalog push if possible (@jolelievre) or modify the domain for this string in the next minor or major version.

**Comment by jolelievre** [comment]
If the PR for this issue is done quickly I think it could enter in the last modifications on the catalog yes. So we can change the namespace indeed.

**Comment by Julievrz** [comment]
> If the PR for this issue is done quickly I think it could enter in the last modifications on the catalog yes. So we can change the namespace indeed.

@jolelievre Couldn't we change the namespace of the original wording, so that this PR can use the right domain later even if the catalog is already pushed?

**Comment by jolelievre** [comment]
Closed by #25039
