### ISSUE TITLE
BO - Design - Theme Customization - Page configuration - we cannot enable mobile module when it is disabled on desktop

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24470]
#### Describe the bug

When we disable a module from the desktop, we cannot enable it on mobile

#### Steps to Reproduce

1. Go to BO > Design > Theme & Logo > Pages configuration page
2. Disable the main menu module => ok
3. Click on the drop-down list to "Enable mobile"
![image](https://user-images.githubusercontent.com/16067358/117848746-dfcac580-b283-11eb-95bf-ef3ff868f4c9.png)
4. Go and check if the module is enabled when using mobile => NOK
![image](https://user-images.githubusercontent.com/16067358/117848940-1accf900-b284-11eb-9423-d20ca499f7ba.png)

With PS1769 and Theme Customization: v1.2.1: the button "Enable mobile" doesn't exist
![image](https://user-images.githubusercontent.com/16067358/117850033-34bb0b80-b285-11eb-9887-4de1136858db.png)

**Screenshots**

https://drive.google.com/file/d/1saT4fphnSofDp5Pa96mDBuEEUvGkAMWG/view?usp=sharing

#### Additional information

* PrestaShop version: 1774, 178x
* PHP version: 7.2
* Theme Customization: v1.2.1

**Comment by Progi1984** [comment]
@PrestaShop/product-team For the dropdown, what are the actions when the module is disabled ?
(No specs for Theme Customization https://github.com/PrestaShop/prestashop-specs/tree/master/content/1.7/modules)
