### ISSUE TITLE
actionOrderStatusPostUpdate hook should have the old order status in params

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#24474]
#### Is your feature request related to a problem?

The actionOrderStatusPostUpdate hook have only newOrderStatus parameter but the order state has already been changed in the order.
#### Describe the solution you'd like

Add the old order state in params of the hook.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by hibatallahAouadni** [comment]
@matthieu-rolland so shall we change the issue status to **`Ready`**?

**Comment by matthieu-rolland** [comment]
yes I think so 👍  @hibatallahAouadni , even in QA (the PR is in QA, it's a hook to be tested)
