### ISSUE TITLE
BO - Design - Theme Customization - Page configuration - A front-end issue when we try ro disable / reset / uninstall a module 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24472]
#### Describe the bug
In the BO > Theme & Logo > Pages configuration page >When wtry to disable /reset / Uninstall a module => The modal have a front-end issue
![bo-uninstall-front_end_issue](https://user-images.githubusercontent.com/16067358/117851211-61bbee00-b286-11eb-97b9-28ced658b3dd.png)
![BO_reset_front_end](https://user-images.githubusercontent.com/16067358/117851215-62ed1b00-b286-11eb-8e1f-21e6f154b59e.png)
![BO_front_end_disable_module](https://user-images.githubusercontent.com/16067358/117851218-6385b180-b286-11eb-83f9-66c3f5634325.png)
 
In the PS1774 => ok
![image](https://user-images.githubusercontent.com/16067358/117851356-844e0700-b286-11eb-81bb-6a4917493df6.png)

#### Steps to Reproduce

1. Go to BO > Design > Theme & Logo > Pages configuration page
2. Try to disable / reset / Uninstall a module
3. See error

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2
* Theme Customization: v1.2.1

**Comment by Progi1984** [comment]
@khouloudbelguith I didn't reproduce it on 178x : 
![image](https://user-images.githubusercontent.com/1533248/118509639-81449200-b730-11eb-9234-ce699639717a.png)
![image](https://user-images.githubusercontent.com/1533248/118509721-97525280-b730-11eb-9cef-704d0dfb8374.png)

**Comment by Progi1984** [comment]
Ping @khouloudbelguith Have you got more informations about this issue ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry for this delay, yes, the issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/24596
https://drive.google.com/file/d/1TkA4Kv3gUBNzWAfS-cXz_Z6voX3ygc_O/view?usp=sharing

Thanks @Progi1984, @NeOMakinG :smile:

**Comment by Progi1984** [comment]
Good news. Thanks @khouloudbelguith
