### ISSUE TITLE
Add loading spinner when clicking on add to cart button

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#24488]
I f think that would be useful showing a loading spinner when clicking on add to cart button.
In particular on low tier device or on slow internet connection where the modal cart or cart page could take a while to be showed.
Showing the loading spinner will avoid multiple click on add to cart button, because customer can see that the button has beeen clicked and the website it's loading.

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
