### ISSUE TITLE
BO - Orders list - Preview order - Invoice details is missing the address mail of the customer

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24482]
#### Describe the bug

In the BO > Orders > Order list page, when we try to preview an order, the invoice details is missing the address mail of the customer
![BO_order_preview_invoic details](https://user-images.githubusercontent.com/16067358/118000761-634ceb00-b346-11eb-990f-b0347b23fae0.png)

In PS1774 we have
![1774_preview_BO_order](https://user-images.githubusercontent.com/16067358/118000796-69db6280-b346-11eb-9e36-90f16930d87b.png)

#### Steps to Reproduce

1. Go to BO > Orders > Orders list page
2. Click on 'arrow_down' to preview any order
4. See error: the address mail is missing the invoice details

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
@MatShir Could you help on this PR : On 177x, we have applied the address format for the address so we have only used values from address format. 

On 178x, what is the waited behavior ?
- The user changes its address format for displaying the email address
- We display the email address 

Thanks

**Comment by khouloudbelguith** [comment]
Hi @Progi1984, @MatShir,

I manage to reproduce the issue with PS1775build1.
![image](https://user-images.githubusercontent.com/16067358/120300726-7a8b5280-c2cc-11eb-91ab-11a632009a68.png)

It was ok with PS1774
![image](https://user-images.githubusercontent.com/16067358/120300903-a8709700-c2cc-11eb-81b0-fd805b55abc1.png)

So it is a regression in the PS1775.
I will change the Projects.

Thanks!

**Comment by MatShir** [comment]
**Specs:**
The email of the customer is displayed above the invoice detail.
The new filed has the icon material design 'email' filled and the label 'Email:' in Admin.Global.

**Comment by Progi1984** [comment]
Fixed in #24773 by @Progi1984
