### ISSUE TITLE
BO - Orders list page - An error is displayed in the console when changing the order status

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24481]
#### Describe the bug

In the BO > Orders list page > when we try to change the order status with the dropdown list, an error is displayed in the console
![bo_order_change_status](https://user-images.githubusercontent.com/16067358/118000045-bffbd600-b345-11eb-8b95-eab457b51d3b.png)
It was ok with PS1774

#### Steps to Reproduce

1. Go to BO > Orders > Orders list page
2. Try to change the status of any order with the drop-down list
4. See error in the console

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by matks** [comment]
Pull Request available https://github.com/PrestaShop/PrestaShop/pull/24485 by @arouiadib

**Comment by Progi1984** [comment]
Fixed by @arouiadib in #24485
