### ISSUE TITLE
BO - Orders list - The tracking URL is NOK in the preview order

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24483]
#### Describe the bug

Related to this issue: https://github.com/PrestaShop/PrestaShop/issues/23401
In the BO > Orders > Order list page > in the preview order section: when we click on the tracking URL, the URL is NOK.

#### Steps to Reproduce

1.Go to BO > Shipping > Carriers page
2. Edit a carrier (My carrier for example) and add a Tracking URL `http://example.com/track.php?num=@`
3. Create an order by selecting `My carrier` as a shipping method
4. Go to BO > Orders > last order created
5. In the carrier Tab > EDit the carrier and add a tracking number = 12 for example
6. Go to BO > Orders > Orders list page > Preview last order
7. Click on the tracking number URL
8. Redirection to `http://example.com/track.php?num=@` instead of `http://example.com/track.php?num=12`

https://drive.google.com/file/d/16LnG2A8n33GJsUfbiX8YX8OGhIdZLN6M/view?usp=sharing

#### Additional information

* PrestaShop version:  178x, 1774
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #24568
