### ISSUE TITLE
After upgrade from 1.6 to 1.7.7.4 module install hangs

### ISSUE THREAD

**Issue by logosur** [PrestaShop/PrestaShop#24493]
Hello,

I cant't install any module, it hangs every time.

I can even see in logs this error:
[2021-05-13 18:49:21] php.DEBUG: Warning: file_get_contents(/home/.../public_html/config/xml/must_have_modules_list.xml): failed to open stream: No such file or directory [] []

I think this file doesn't exist anymore in Prestashop 1.7.7.x right?

Any help would be appreciated.

Regards.

**Comment by florine2623** [comment]
Hello @logosur ,

Here are the files present in folder your_shop/config/xml : https://github.com/PrestaShop/PrestaShop/tree/1.7.7.x/config/xml

After upgrading from 1.6.1.24 to 1.7.7.4, i didn't encounter this error.
![Capture d’écran 2021-05-14 à 11 02 23](https://user-images.githubusercontent.com/16019289/118248000-1d0d9e00-b4a4-11eb-8f0b-cc6788f8e03d.png)
![Capture d’écran 2021-05-14 à 11 03 45](https://user-images.githubusercontent.com/16019289/118248019-21d25200-b4a4-11eb-8f8e-8961c4b1b919.png)


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
