### ISSUE TITLE
Order messages not in customers languages 1.7.7.3

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#24499]
#### Describe the bug
Since we migrated from 1.7.6 to 1.7.7.3 sending order messages to customer are always in English, even when the customer has a selected a different language.
At first I thought, maybe something was wrongly imported during the migration, but when I deleted a order message and created a new one, also the new message is in default English in our case.

#### Expected behavior
I would like that the order messages are send in the customers language

![image](https://user-images.githubusercontent.com/23308427/122771246-8acc9700-d2a6-11eb-864b-b25f8adf2cf8.png)

#### Steps to reproduce

1. We have a site with multiple languages. 
2. FO > change your language to Arabic (for exemple)
3. Create an Order
4. BO > **SELL** > **Orders** > Edit last Order 
5. try to send the delay message
6. See error, the delay message is with Admin language (English) and not Client language (Arabic)

Reproduce by having multiple language messages and customers.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @01park ,

Can you specify the languages available on your site ? And what is the default language ?

Thanks!

**Comment by 01park** [comment]
Hi @florine2623 

Our backoffice language is English and front office has English, Spanish, Germany, Dutch, Italian, French and more.

**Comment by hibatallahAouadni** [comment]
Hello @01park 

Thanks for your feedback!
Could you please provide clear and concise steps to reproduce the issue.

Thanks!

**Comment by 01park** [comment]
Hi,

We have a site with multiple languages. The order messages are translated into the specific language. No matter what language the customer selects, the back office always selects the default languages English to reply to their message.

Reproduce by having multiple language messages and customers. 

Update:

I updated a second store to 1.7.7.4 and also this store has the same issue. Could it be Multi-store related?

**Comment by hibatallahAouadni** [comment]
Hello @01park 

Thanks for your issue! Yes I reproduce the issue, but I think we never work on this.
So, ping @PrestaShop/product-team wdyt? is better to treat this issue as a bug or as an improvement? if as an improvement, I suggest we add this language select in Order page:

![image](https://user-images.githubusercontent.com/23308427/121562362-a8ce0800-ca19-11eb-87b9-927ff5cdc771.png)

Wdyt?

**Comment by 01park** [comment]
Hi,

I would like it to be just like in previous PS version, that the language is selected automatic based on customers language. Adding is box is an option, but the you would still need to know the language the customer speaks.

**Comment by hibatallahAouadni** [comment]
Related to #10258

**Comment by hibatallahAouadni** [comment]
FYI: I reproduce the same issue with PS1.7.8.0 and 1.7.8.x

**Comment by Progi1984** [comment]
Fixed in #25059 by @Progi1984
