### ISSUE TITLE
Catalog Price Rule not working with multi shop when on a specific category

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#24490]
#### Describe the bug

When creating a catalog specific price rule **_using conditions_**, the rule is not working as expected if you choosed the second shop on a multi shop installation of prestashop.

#### Expected behavior

The conditions should target the selected shop.

#### Steps to Reproduce

1. Configure a multi shop with 2 shops
2. Create a category available only in the second shop
3. Create a product available only in the second shop (shop id 2)
4. Create a catalog specific price rule (`/admin/index.php?controller=AdminSpecificPriceRule`) and select the second shop in the shop dropdown
5. Add a condition to target the category of the product.
6. Save he rule
7. See that the discount is not applied to the product. (table `ps_specific_price` is empty)

#### Additional information

The problem happens because `getAffectedProducts` method uses `Context::getContext()->shop->id` instead of the selected shop id.

**Comment by florine2623** [comment]
Hello @Seb33300 ,

I tested with PS 1.7.7.4, I can't reproduce your issue.

My product only available in shop2 :
![Capture d’écran 2021-05-14 à 10 17 37](https://user-images.githubusercontent.com/16019289/118242590-cbfaab80-b49d-11eb-90ea-6d8b1a56b813.png)

The catalog price rule :
![Capture d’écran 2021-05-14 à 10 22 32](https://user-images.githubusercontent.com/16019289/118243143-64912b80-b49e-11eb-8de6-4cea9900805c.png)

The product page in front-office :
![Capture d’écran 2021-05-14 à 10 19 51](https://user-images.githubusercontent.com/16019289/118242846-095f3900-b49e-11eb-81cc-92546a2fe1b5.png)

Am I missing something ?
Thanks!

**Comment by Seb33300** [comment]
You need to create a category that exist only in shop 2.

**Comment by florine2623** [comment]
Thanks for the detail !

I was able to reproduce the issue with PrestaShop version 1.7.7.4, so I can confirm that this behavior is indeed a bug.

In develop branch, I can't reproduce the issue as I have to choose the default category for my product :
![Capture d’écran 2021-05-14 à 15 10 59](https://user-images.githubusercontent.com/16019289/118275582-e8f7a480-b4c6-11eb-82e1-add210e87b90.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.

Thank you

**Comment by Seb33300** [comment]
> Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.

I have submitted a PR to fix this issue already.

**Comment by florine2623** [comment]
Thanks ! The developers will take a look.
