### ISSUE TITLE
Wishlist overly uses fixed sizes and therefore breaks on translations

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24503]
#### Describe the bug

blockwishlist uses fixed sizes that break when translated strings do not have the same size.

While the style `width: 79px;` is flagrant, it has no effect for the `classic` theme, because the element itself has `display: inline;`

#### Expected behavior

The css styles should allow different sizes of texts.

#### Steps to Reproduce

1. Install PS with French language
2. Install blockwishlist
3. Click on a wishlist icon to add an article to the wishlist
4. Inspect the **Create new list* link: you will see css `width: 79px;` 😢 

**Screenshots**

![2021-05-14_114204](https://user-images.githubusercontent.com/7520695/118252848-8217c280-b4a9-11eb-8fe9-ba547c50deb6.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

I installed block wishlist module v2.0.0 in PS 1.7.7.4. Indeed the width is fixed.

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by SharakPL** [comment]
This should be fixed in https://github.com/PrestaShop/blockwishlist

**Comment by NeOMakinG** [comment]
@lmeyer1 I think it's fixed now right? Overwise feel free to open it again if you find some wrong fixed values
