### ISSUE TITLE
FO - Several pages URL and names are not translated

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24508]
#### Describe the bug

When I have several languages available on FO, the names and URL of some pages (user account pages, links in footer...) are not translated and are in English whatever the language selected.

In Shop Parameters > Traffic & SEO, the URL are indeed not translated (they were translated in 1.7.7.x), if I modify the URL or the name, it's indeed modified in FO.

#### Expected behavior

URL and pages name should be translated.

#### Steps to Reproduce

1. Install PS in English, with country France.
2. Add "Austria" Localisation Pack
3. Go to FO, login, select "French" as a language
4. Go to the user account : The URL and the name are in English ("My account" and "my-account") instead of French ("Mon compte and "mon-compte" in 1.7.7.x)
5. Check in German : Same issue.

**Screenshots**

![my account](https://user-images.githubusercontent.com/55688534/118288822-07649c80-b4d5-11eb-8f63-c1aaf1885d7f.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #24525
