### ISSUE TITLE
BO - Attributes and Features - Display NOK

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24504]
#### Describe the bug

On different Legacy pages, the alignment of buttons, labels and fields are NOK (see screenshots below)

#### Expected behavior

Alignment should be OK

#### Steps to Reproduce

1. Go to BO > Catalog > Attributes and features
2. Add a new attribute / attribute value / feature / feature value : See the fields non aligned.
3. On attribute, feature list (but also on all lists in Legacy), open the "more actions" button at the right of an item in the list : The "Edit" or "Delete" buttons does not takes the full width of the popin.

**Screenshots**

Add feature value :
![add features values display](https://user-images.githubusercontent.com/55688534/118255193-3f0b1e80-b4ac-11eb-8ce4-b7f86db7c830.png)

Add feature :
![add featues display](https://user-images.githubusercontent.com/55688534/118255197-3fa3b500-b4ac-11eb-86ba-c89ef8acdd41.png)

Add attribute :
![add attributes display](https://user-images.githubusercontent.com/55688534/118255199-403c4b80-b4ac-11eb-82cd-fdba6d499721.png)

Add attribute value :
![add attributes values display](https://user-images.githubusercontent.com/55688534/118255201-403c4b80-b4ac-11eb-831b-8de06a53d3bc.png)

Small buttons in list : 
![small buttons in Legacy](https://user-images.githubusercontent.com/55688534/118255203-403c4b80-b4ac-11eb-9dd7-aef23642cbc9.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by ghost** [comment]
Hey @Robin-Fischer-PS i made this PR https://github.com/PrestaShop/ps_facetedsearch/pull/433  he fix partially the issue.

For the texture columns it's in the core.

**Comment by Progi1984** [comment]
Fixed in #24580 by @okom3pom
