### ISSUE TITLE
Prestashop 1.7.7.4 Stock Management poor performance in Catalog > Stock

### ISSUE THREAD

**Issue by alejandrogarciahenao** [PrestaShop/PrestaShop#24517]
#### Describe the bug

Poor performance in Catalog - Stock with prestashop 1.7.7.4 with 1000 products and 4000 combinations. It delays around 15 seconds 

#### Expected behavior

Get an answer less than 3 seconds.

#### Steps to Reproduce

Go to Catalog - Stock with more than 4000 combinations.

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28

Thank you for your help.

**Comment by hibatallahAouadni** [comment]
Hello @alejandrogarciahenao 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server problem.

We will close this issue.

Thanks!

**Comment by alejandrogarciahenao** [comment]
HI @hibatallahAouadni  , it's a prestahosp core bug. I have the but in two sites with differents servers. Did you try to reproduce it in a store with +4000 combinations? 
Thank you so much

**Comment by alejandrogarciahenao** [comment]
Finally, I could solve it adding

        if ($idProduct === null && $idOrder === null) {
            return;
        }

at the top updateReservedProductQuantity method in /src/Adapter/StockManager.php

Thank you so much

**Comment by jf-viguier** [comment]
I've faced this bug too. @alejandrogarciahenao have you figured out if this sql in usefull ?
