### ISSUE TITLE
Backoffice Auto log out in module gestion PS 1.7.7.4

### ISSUE THREAD

**Issue by nidal2020** [PrestaShop/PrestaShop#24512]
Im on PS 1.7.7.4 , when i'm logged to the backoffice and try to navigate to Module Management menu i'm disconnected and I should log in again
 
I tried to increase the admin Back-office cookie session life to 1000 but same issue when i can't acces to module menu 

I see no error on apache Log it returs 200 acces so it seems good.

Here is my Server Informations 
VPS SSD
Panel:  Plesk Obsidian Version 18.0.35
OS CentOS Linux 7.9.2009 (Core)
Version de PrestaShop : 1.7.7.4
Version du logiciel serveur : Apache
Version de PHP : 7.2.34
Limite de mémoire : 100128M
Temps maximal d'exécution : 1000
Taille max. pour envoi de fichiers : 200M

 Liste des fichiers modifiés
Aucun changement n'a été détecté sur vos fichiers.
Paramètres requis : ok
Paramètres optionnels : ok

```

jquery-3.4.1.min.js | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 17 ms | public, max-age=14400, must-revalidate, proxy-revalidate
jquery.validate.js | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 15 ms | public, max-age=14400, must-revalidate, proxy-revalidate
messages_fr.js | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 15 ms | public, max-age=14400, must-revalidate, proxy-revalidate
spin.js | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 17 ms | public, max-age=14400, must-revalidate, proxy-revalidate
ladda.js | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 16 ms | public, max-age=14400, must-revalidate, proxy-revalidate
login.js?v=1.7.7.4 | 200 | script | index.php?controller=AdminLogin&token=2d04c47… | (disk cache) | 16 ms | public, max-age=14400, must-revalidate, proxy-revalidate

```
Regards

**Comment by hibatallahAouadni** [comment]
Hello @nidal2020 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
