### ISSUE TITLE
Filtering in catalog does not work separately for Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by kratekk** [PrestaShop/PrestaShop#24523]
Hi,
I have a problem with product filtering in Prestashop 1.7.5.0 in multistore configuration.
When I filter the list of products in one store, e.g. in terms of quantity, and switch to another store, this filter remains and spoils my list of products because in the other store I have disabled warehouse support and I cannot turn off this filter.

Have any of you encountered this problem? How to fix it and separate filtering for different stores?

**Comment by hibatallahAouadni** [comment]
Hello @kratekk 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by kratekk** [comment]
@hibatallahAouadni 

**Bug description**

Create multistore ( shops e.g.)
Go to Warehouse in first store and disable warehouse management 
Switch to second store and go to product list (catalog)
Add new product for both stores with quantity = 800
Go to product list and filter product list by quantity e.g. = 100 (your product what you added shouldn't be wisible on this list
Switch now to first store and go to product list (now this product will not be able to find because filter by quantity is also working for first store and you will not have influence to change condition of search in this case)

**Additional information**

    PrestaShop version: 1.7.5.0
