### ISSUE TITLE
BO - Orders - addProductNewInvoiceInfo should not be displayed when we try to add a product to an order without invoices

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24532]
#### Describe the bug

In the BO > Orders > Order details page, the `addProductNewInvoiceInfo` block should not be displayed when we add a product without invoices
![image](https://user-images.githubusercontent.com/16067358/118519356-56ab0700-b739-11eb-9660-66086a2580c2.png)

#### Expected behavior

177x, we have
![image](https://user-images.githubusercontent.com/16067358/118519465-717d7b80-b739-11eb-8b48-6c86d879b96c.png)

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. View any demo order
3. Try to add a product

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by matthieu-rolland** [comment]
So I closed my PR:  https://github.com/PrestaShop/PrestaShop/pull/24718 because @PierreRambaud fixed it in another PR for issue #24533
