### ISSUE TITLE
BO - Orders - Order note with invalid data

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24534]
#### Describe the bug

In the BO > Orders > Order details page > when we add an order note with invalid, a `Update successful` alert is displayed by the note is empty.

#### Expected behavior

The user should be able to save any value.

#### Steps to Reproduce

1. Go to BO > Orders > Orders list page
2. View any order
3. In the Status Tab, add a note with `<hello>` and save
4. See error: the order not is still empty

**Screenshots**
https://drive.google.com/file/d/1UZ1D4yhc5hkD4cxkt94NRkckRpFHwdZt/view?usp=sharing

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by matks** [comment]
Probably similar to https://github.com/PrestaShop/PrestaShop/issues/9574

**Comment by Progi1984** [comment]
Fixed in #24867 by @matthieu-rolland
