### ISSUE TITLE
Cannot login to BO after installing 1.7.7.4

### ISSUE THREAD

**Issue by colormartinez** [PrestaShop/PrestaShop#24538]
#### Describe the bug

Hi,
I just install the last PrestaShop (V 1.7.7.4) with no problems during the installation, but once I got to the admin login and put my user and pass, I get this screen and can go any further.
The client section is working OK.

I have Debug turn ON but get no errors.
The only error that I'm getting is in the CONSOLE : 
Failed to load resource: the server responded with a status of 500 (Internal Server Error) 

Website admin URL: http://gatesecuritystore.com/gss/admin798kftdbq

**Screenshots**

![image](https://user-images.githubusercontent.com/69478577/118566999-64698800-b74b-11eb-837d-7032a8307c0b.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3 (ea-php73)

**Comment by arouiadib** [comment]
Before support team intervene, I suggest you activate debug mode and send the 500 error details

**Comment by colormartinez** [comment]
> Before support team intervene, I suggest you activate debug mode and send the 500 error details

As I initially mentioned, I have already activated debug mode and it does not show me any errors.

**Comment by arouiadib** [comment]
Do you access other pages in BO like products page ( `/index.php/sell/catalog/products`)?

or  http://gatesecuritystore.com/gss/admin798kftdbq/index.php/configure/advanced/performance/ ?

BTW you should change the admin79... in future

**Comment by colormartinez** [comment]
> Do you access other pages in BO like products page ( `/index.php/sell/catalog/products`)?
> 
> or http://gatesecuritystore.com/gss/admin798kftdbq/index.php/configure/advanced/performance/ ?
> 
> BTW you should change the admin79... in future

No. I can't access any admin page.
And now I realized that at the FO is a new client trying to register it gets the following error:
![image](https://user-images.githubusercontent.com/69478577/118576408-d4353e00-b75e-11eb-8661-fd445d41bb66.png)

**Comment by arouiadib** [comment]
Did you tried with PHP 7.2?

I think the issue related to `INTL_IDNA_VARIANT_UTS46` is already somewhere here in the Prestashop repository.

**Comment by matks** [comment]
Thank you @arouiadib for the help 😉  . You are right: the error seems very close to https://github.com/PrestaShop/PrestaShop/issues/22300

**Comment by hibatallahAouadni** [comment]
Hello @colormartinez 

As @matks mentioned your issue is related to #22300 so please check it out, you might find some answers :wink: 

Since, we are using GitHub issues only to discuss about bugs and new features in the PrestaShop project, I close this issue. 
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by colormartinez** [comment]
Problem Solved.
A solution for PHP 7.3from another forum:

There is a problem with constant **INTL_IDNA_VARIANT_UTS4**6 in the file **"src/Core/Util/InternationalizedDomainNameConverter.php"**
It needs to be modified as follows. The constant INTL_IDNA_VARIANT_UTS46 needs to be converted to int type explicitelly by intval() on the line 47.
**FROM:**
return $parts[0] . '@' . idn_to_utf8($parts[1], 0, (INTL_IDNA_VARIANT_UTS46));
**TO:**
return $parts[0] . '@' . idn_to_utf8($parts[1], 0, intval(INTL_IDNA_VARIANT_UTS46));

**Comment by arouiadib** [comment]
@colormartinez Thank you very much for investigating and posting details in ticket .
