### ISSUE TITLE
BO - Orders - The discount block is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24536]
#### Describe the bug
In the BO > Orders > Order view page, the discount block is not well displayed
![image](https://user-images.githubusercontent.com/16067358/118529447-cd4d0200-b743-11eb-8d7b-1365d60f41ee.png)

#### Expected behavior

It was ok with 177x
![image](https://user-images.githubusercontent.com/16067358/118529525-e48bef80-b743-11eb-92f3-e18f3779e9c7.png)

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. View any order
3. Add discount

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24447
