### ISSUE TITLE
BO - View Order - Design of the Header NOK

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24548]
#### Describe the bug

On BO > Orders > View an order, the header is NOK.

#### Expected behavior

Header should be like in 177. See screenshots for details.

#### Steps to Reproduce

1. Go to BO > Orders > View an order
2. Check the display of the header

**Screenshots**

**In 1.7.8 : Order Reference, Name, Price and Date/Time have huge gap between each item**

![header view order 178](https://user-images.githubusercontent.com/55688534/118655469-dee8e500-b7e9-11eb-9c4e-7d879b735ce3.png)

**In 1.7.7 : The items have no gap**

![header view order 177](https://user-images.githubusercontent.com/55688534/118655182-93363b80-b7e9-11eb-8833-dae1a22916f7.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed in #24573 by @NeOMakinG
