### ISSUE TITLE
BO - Add new Order page - Pack - an exception is displayed when we add a pack

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24553]
#### Describe the bug

In the BO > Orders > Add new Order page, when we add a pack product out of stock; Pack quantities: Decrement both, Decrement products in the pack only.), an exception is displayed.
![image](https://user-images.githubusercontent.com/16067358/118692719-a279b100-b80a-11eb-964e-aa74dea8093c.png)

#### Expected behavior

We should have a clear alert:
```php
There are not enough products in stock.
```
![image](https://user-images.githubusercontent.com/16067358/118693049-ff756700-b80a-11eb-9700-67c56fef12fb.png)

#### Steps to Reproduce

1. Create two products with quantity = 0 (order not allowed)
2. Create a pack product that contains the two products created with quantity = 1
3. Pack quantities = Decrement both, Decrement products in the pack only. 
![image](https://user-images.githubusercontent.com/16067358/118693431-511df180-b80b-11eb-9ce3-c4c549564881.png)
4. Go to BO > Orders > Add new order > choose a customer
5. Try to add the pack product
6. see error
![image](https://user-images.githubusercontent.com/16067358/118692719-a279b100-b80a-11eb-964e-aa74dea8093c.png)

PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/118694252-2d0ee000-b80c-11eb-8850-56442ad02eef.png)

#### Additional information

* PrestaShop version: 1.7.8.x, 1774
* PHP version: 7.4, 7.2

**Comment by Progi1984** [comment]
@MatShir What is the expected behavior when 

> I add to a cart a pack (with stock 1) of two products (with stock 0)
> Bearing in mind that the decrementation of pack's stock is done on two products

:question:

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #24657
