### ISSUE TITLE
Admin menu does not change the language 

### ISSUE THREAD

**Issue by leskam** [PrestaShop/PrestaShop#24558]
#### Describe the bug

After clicking **My preferences** and changing Language the interface language changes halfway - menu remains in the old language. Re-login or clearing cache not working.

#### Expected behavior

Complete language change? 

#### Steps to Reproduce

1. Login to admin area
2. Click My Preferences
3. Scroll down to Language select box and change to another
4. Save
5. Look at the interface

**Screenshots**

![lang](https://user-images.githubusercontent.com/33346738/118710476-a0b9e880-b81e-11eb-815f-b31c8b75f86a.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @leskam 

Thanks for respecting the provided template :clap: 
Did you change the default language just in block **Configuration** under **BO** > **IMPROVE** > **International** > **Localisation**?
Cause you mentioned that you change it in **My preferences** and to be honest we have two preferences:

- BO > IMPROVE > Shipping > Preferences
- BO > IMPROVE > Payment > Preferences

In both, there's no Language select box.
So, to change the Admin language, you need to access to **Your profile**, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118745467-8ac81a00-b856-11eb-834c-64555dd18a07.png)

then change the **Language** and **Save**.
Please check and feedback.

Thanks!

**Comment by leskam** [comment]
I changed the language like you said: account icon -> Your profile -> Language (select box) and Save. After that language in admin panel changes halfway (as I attached in first post - menu in Polish language, rest in English)

**Comment by kpodemski** [comment]
You could try to update your translations from "Międzynarodowy -> Tłumaczenia"

**Comment by leskam** [comment]
> 
> 
> You could try to update your translations from "Międzynarodowy -> Tłumaczenia"

Still no changes

**Comment by hibatallahAouadni** [comment]
Hello @leskam 

Could you please provide a screen record (video), definitely there's some detail you missed to provide :wink: 
Please feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @leskam ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
