### ISSUE TITLE
BO - Add new Order page - Changing the Product quantity freeze the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24554]
#### Describe the bug

In the BO > Orders > Add new Order page > When we try to change the product quantity (increase/decrease/change manually) freeze the page

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order
2. Choose a customer
3. Try to change the quantity of the product
4. See an error: the page is frozen, we can't add a product, we can't remove the product.....
![image](https://user-images.githubusercontent.com/16067358/118695827-e7ebad80-b80d-11eb-85ba-745d1d3d8401.png)

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24594
