### ISSUE TITLE
BO - Install modules via Recommended Modules NOK

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24550]
#### Describe the bug

When installing (or uninstall, reset, etc...) a modules via the "Recommended Modules and Services" popin, or via the " Recommended Modules and Services" block on some pages (Shipping > Carrier or Payment > Payment Methods for example), the notification is not displayed correctly (a green alert in top right of the page) but in HTML instead.

Please note that I also add an exception, but I can no longer reproduce the exception (see screenshot and steps for details).

#### Expected behavior

Notification should be displayed as in 1.7.7.

#### Steps to Reproduce

1. Go to Customer Service > Customer Service
2. Click on "Recommended Modules and Services", install a module : The notification is displayed in HTML, NOK.
3. Go back, click again on "Recommended Modules and Services", then on "Installed" modules : The module we just installed is listed here.
4. Still in the "Recommended Modules and Services" popin, uninstall the module : The notification is again displayed in HTML, NOK.

Other steps: 

1. Go to Shipping > Carrier
2. In "Recommended Modules and Services" block, install a module : The notification is displayed in HTML. NOK.

Steps for the exception (I can no longer reproduce the exception) : 
1. In PHP 7.4, in php.ini file, I had this parameter : `post_max_size = 8M`
2. When trying to install a module via the "Recommended Modules and Services", I had an exception (see screenshot below)
3. After updating and saving the php.ini file with this parameter : `post_max_size = 20M`, restarting apache, then updating again to `post_max_size = 8M` and re-restarting apache, I no longer have the exception.

**Screenshots**

How to reproduce: 
![install module from recommended modules](https://user-images.githubusercontent.com/55688534/118664896-22dfe800-b7f2-11eb-834c-80e892d2215b.png)

After Install: 
![after install module from recommended modules](https://user-images.githubusercontent.com/55688534/118665245-72beaf00-b7f2-11eb-8b40-f2278b5a58ee.png)

After uninstall:
![uninstall module from recommended modules](https://user-images.githubusercontent.com/55688534/118665086-4efb6900-b7f2-11eb-838c-433b043cb6c3.png)

The exception:
![exception recommended modules](https://user-images.githubusercontent.com/55688534/118665123-5589e080-b7f2-11eb-9923-f9066be7878f.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by PierreRambaud** [comment]
Using the recommended modules:
![image](https://user-images.githubusercontent.com/1462701/120195691-5aea2080-c21f-11eb-8ccb-3997e68ab4e5.png)

In shipping carrier:
![image](https://user-images.githubusercontent.com/1462701/120195881-866d0b00-c21f-11eb-9c42-fca692703de9.png)


I'm sorry, I'm not able to reproduce this issue :(

**Comment by Robin-Fischer-PS** [comment]
Hi @PierreRambaud !

I cannot reproduce it either, on fresh install from branch or from the nightly build. It was probably fixed somehow by a PR.

I close this ticket, thanks !
