### ISSUE TITLE
BO - Add new Order page - an error is displayed in the console when adding a voucher

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24556]
#### Describe the bug

In the BO > Orders > Add new Order page, when we add a voucher => an error is displayed in the console.
![BO_order_add_voucher](https://user-images.githubusercontent.com/16067358/118697129-436a6b00-b80f-11eb-98f8-48fb9c068668.png)

#### Expected behavior

No error in the console should be displayed

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page
2. Choose a customer & choose a product
3. Click "Add new voucher" > Set required field > Click save

It was ok with 1774
#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24794 :tada:
