### ISSUE TITLE
BO - Add new Order page - An error is displayed when creating an order with a pack & total =0 (order total =0 or a cart rule - PHP7.4)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24557]
#### Describe the bug

With PHP7.4, when we create an order with a cart rule & pack => An error is displayed
![image](https://user-images.githubusercontent.com/16067358/118698115-52055200-b810-11eb-8e1e-b683deb699b2.png)

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page 
2. Choose a customer
3. Search a pack product
4. Change a product price to 0 + choose a free carrier
5. **Or** create a cart rule with discount amount > Total + free shipping
4. Create the Order
5. See error
![image](https://user-images.githubusercontent.com/16067358/118700345-d9ec5b80-b812-11eb-9ad2-f7b391e4955a.png)
6. Go to View last Order created > See error
![image](https://user-images.githubusercontent.com/16067358/118700428-f4bed000-b812-11eb-97ed-00eba6eed296.png)
7. Try to edit a customer or view full details or delete the customer from BO
8. See Error 
![image](https://user-images.githubusercontent.com/16067358/118700569-1c159d00-b813-11eb-8f37-6863f89fdd43.png)
9. Try to create an order from the BO with the same customer > see error
![image](https://user-images.githubusercontent.com/16067358/118700893-6ac33700-b813-11eb-93a5-561806e26984.png)
10. Go to FO > Order details page of the customer > see error 
![image](https://user-images.githubusercontent.com/16067358/118701020-8b8b8c80-b813-11eb-9010-6b3fd6d19cf9.png)

This is only reproduced with php7.4, php7.2 => ok

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.4

**Comment by PululuK** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/24611
