### ISSUE TITLE
Password required property a has bug in Customer Persister - v1.7.x

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#24559]
#### Describe the bug

When we want to try to save a customer through `CustomerPersister` class ->save() method, the last parameter is passwordRequired. When we set it to false, we expect to not have any password. But within this class (CustomerPersister) in line 81 we have this:
```
 if (!$customer->is_guest) {
            $customer->passwd = $this->crypto->hash(
                $newPassword ? $newPassword : $clearTextPassword,
                _COOKIE_KEY_
            );
        }  
```

CustomerPersister path: `classes/form/CustomerPersister.php`

when we do not provide `newPassword`, the `clearTextPassword` will be used to create the password, but as we did not want to provide the password the `clearTextPassword` will be empty. So, the hash method will generate a password from an empty string. Notice that we do not have the plain text password, as we did not ask the customer to enter the password (password is not required). This will cause that the customer to have new pass and will not be able to login in the future (with his/her previous pass).

If you confirm the issue, the PR is ready. 
Thanks guys

#### Expected behavior

To update customer without password when passwordRequired is false.

#### Steps to Reproduce

Try to save a customer with CP with `passwordRequired` set to false and you will see that the password will change. 

* PrestaShop version: v1.7.7.x

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could you please try to reproduce the issue :pray: please :pray:

**Comment by samberrry** [comment]
I checked it again, and I realized that it works well, because the customer will be registered as guest, and he/she can create account later. 
thanks

**Comment by hibatallahAouadni** [comment]
@samberrry Glad to hear :tada: and thanks for your feedback!
