### ISSUE TITLE
Update stock via webserivice with memcache exception and memory leak

### ISSUE THREAD

**Issue by sanctusmob** [PrestaShop/PrestaShop#24567]
#### Describe the bug
When i am updating stock via web service with memcached enable i am getting exception and also i have memory leak (ram 128GB)
When memcached is disabled everything works as expected. 

#### Expected behavior
update stock

#### Steps to Reproduce

1. Enable memcached cache
2. Try to update stock via web service
3. HttpStatusCode: InternalServerError
4. Invalid argument supplied for foreach() (.../httpdocs/ps1772/classes/cache/Cache.php  line 567

**Screenshots**
Request:
```
<?xml version="1.0" encoding="utf-8"?>
<prestashop>
<stock_available>
  <id>52920</id>
  <id_product>1024345</id_product>
  <id_product_attribute>0</id_product_attribute>
  <id_shop>1</id_shop>
  <id_shop_group>0</id_shop_group>
  <quantity>1</quantity>
  <depends_on_stock>0</depends_on_stock>
  <out_of_stock>2</out_of_stock>
</stock_available>
</prestashop>
```

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[3]]></code>
<message><![CDATA[[PHP Warning #2] Invalid argument supplied for foreach() (/var/www/vhosts/xxx/httpdocs/ps1772/classes/cache/Cache.php, line 567)]]></message>
</error>
</errors>
</prestashop>
  HttpStatusCode: InternalServerError
```
#### Additional information

- Web server Apache + NGINX Reverse proxy + php fpm on apache.
- PrestaShop version: 1.7.7.2 
- Server information Linux #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64
- Server software version: Apache
- PHP version: 7.3.28
- Memory limit: 512M
- Max execution time: 300
- Upload Max File size: 24M
- MySQL version: 10.3.27-MariaDB-0+deb10u1

**Comment by hibatallahAouadni** [comment]
Hello @sanctusmob 

Could you please check this issue #15976 it seems similar to yours.
And please fill the blocks (expected behavior, steps to reproduce).
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @sanctusmob 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
