### ISSUE TITLE
[Module - statsdata] FO - An exception is displayed when Save global page views is enabled - PHP7.4

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24563]
#### Describe the bug

An exception is displayed in the FO when we enable Save global page views.
![image](https://user-images.githubusercontent.com/16067358/118782849-cda5e400-b88e-11eb-9703-a26928e9a885.png)
![image](https://user-images.githubusercontent.com/16067358/118782892-d696b580-b88e-11eb-9d86-9273f0a0706d.png)

#### Steps to Reproduce

1. Go to BO > Module Manager page & Search for the statsdata module
2. Click on Configure
3. Enable "Save global page views " and save
4. Click View my shop
5. See error

With PHP7.2 => ok
#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by PululuK** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/24611
