### ISSUE TITLE
BO - Add new Order page - Gift message cannot be removed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24562]
#### Describe the bug

In the BO > Orders > Add new Order page > When we set a gift message, then we try to delete it, it is not possible to remove it.
It is always displayed

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Order Settings page
2. Enable `Offer gift wrapping`
3. Go to BO > Orders > Add new Order page 
4. Choose a customer & choose a product
5. In the Shipping block, Enable gift & set a gift message
6. Try to remove the gift message
7. Click outside or (disable/enable gift)
8. See error => message is back

**Screenshots**

https://drive.google.com/file/d/1CwasVUJjF5oIl0uxAj-kE6scMIernP8f/view?usp=sharing

with PS1769 => ok

#### Additional information

* PrestaShop version: 1774, 178x
* PHP version: 7.2, 7.4

**Comment by Progi1984** [comment]
Fixed in #24576
