### ISSUE TITLE
Explore why our CLI autoupgrade tests did not fail although the 1.7.8.0 upgrade SQL file contained invalid queries

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24561]
In Pull Request https://github.com/PrestaShop/PrestaShop/pull/24242/ @atomiix fixes missing comma for the `INSERT IGNORE INTO `PREFIX_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES ...` SQL statement

=> https://github.com/PrestaShop/PrestaShop/pull/24242/files#diff-2ab29e497243cd89a7b49b94a35a33d9ca879e40ed9a3cf48853535ec304c423

This SQL query is invalid, and yet our autoupgrade CLI nightly tests did not fail. This is because this error raises a warning instead of an error.

#### Expected behavior

When a SQL upgrade file is not valid, the nightly CI of the autoupgrade tool should fail.

The key to solve this might be to modify the upgrade tool behavior, in order that when SQL upgrade file is not valid, it throws an error instead of a warning (at least in our test pipeline) which will be marked as a CI issue. This will allow us to be notified of the issue early and fix it before the next release.

**Comment by matks** [comment]
@atomiix I think this is now fixed thanks to autoupgrade nightly runs? Wdyt ? Can we close this issue ?

**Comment by atomiix** [comment]
@matks I don't think so, I didn't change the way errors are reported, it should still be only a warning

**Comment by gericfo** [comment]
We are currently redefining the tests for autoupgrade and the associated parameters. I therefore close this ticket.
