### ISSUE TITLE
BO - Customer Service page - A title section is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24575]
#### Describe the bug

In the BO > Customer Service > Customer service page, when we try to view a message, the title of the "Your answer" is not well displayed
![image](https://user-images.githubusercontent.com/16067358/118849779-5abd5d00-b8d0-11eb-97d9-f6506398a0d8.png)

#### Expected behavior

1774 => ok
![image](https://user-images.githubusercontent.com/16067358/118849875-745ea480-b8d0-11eb-9b19-0b8779a448e5.png)

#### Steps to Reproduce

1. Go to FO > Contact us
2. Send a message
3. Go to BO > Customer Service > Customer service page and view the last message

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2, 7.4

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24577
