### ISSUE TITLE
FO - An exception is displayed in the category page when creating new category - PHP7.4

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24574]
#### Describe the bug

In the FO, an exception is displayed after creating a category or sub-category
![image](https://user-images.githubusercontent.com/16067358/118848208-d3231e80-b8ce-11eb-9af8-abe61d868db4.png)

#### Steps to Reproduce

1. Go to BO > Catalog > Categories page
2. Create a new category with parent category = Home
3. Go to FO > Click on "All products
5. In the BO > Create a new category with parent category = Clothes
6. Go to FO > Clothes category page
7. See error

With PHP7.2 => ok

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by PierreRambaud** [comment]
I did not manage to reproduce the issue after a fresh install, the only thing is I have no addons modules installed.

**Comment by PululuK** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/24610
