### ISSUE TITLE
Ps Facebook Exception

### ISSUE THREAD

**Issue by GTAssist** [PrestaShop/PrestaShop#24585]
Hi,
I have a problem: when i try to install the facebook prestashop module I got an exception error (as you can see in pictures) and the entire site go down. 

![error2](https://user-images.githubusercontent.com/84515216/118992519-032cf900-b985-11eb-8c95-2ec8d9ffa36d.jpg)
![error1](https://user-images.githubusercontent.com/84515216/118992522-045e2600-b985-11eb-967f-366124e1d75c.jpg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment]
Hello @GTAssist 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules (You can contact PS Facebook Support directly support-facebook@prestashop.com), or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
