### ISSUE TITLE
BO - Orders -Prices are not well calculated when Recalculate shipping costs option is set to NO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24598]
#### Describe the bug

When setting the "Recalculate shipping costs after editing the order" option to No, the shipping cost are not recalculated when editing the order in BO when the price of the order exceeds the carrier's "limit", but the discount free shipping is recalculated  

#### Steps to Reproduce

1. Have a carrier set up with a fee below a certain amount/weight, free above it (in my case, I used `My cheap carrier)`
2. Create a cart rule Free shipping
3. Go to BO > Shop Parameters > Order Settings
4. Set "Recalculate shipping costs after editing the order" to No
5. On FO, make an order with this carrier, under the limit amount (50€)
6. Select My cheap carrier as a shipping method
7. Go to BO > Orders > Last Order created > generate an ivoice
8. EDit the quantity of the product to `2`
9. See error: `An unexpected error occurred. [Symfony\Component\Debug\Exception\ContextErrorException code 0]: Notice: Undefined property: OrderInvoice::$total_paid`, 
10. Refresh the page =>  discount is updated => it shouldn't: the total is NOK, invoice NOK

**Screenshots**
177x(1775): https://drive.google.com/file/d/1X_sx3j52QflnmnsCIdooilhbX490dWUN/view?usp=sharing
1769 => ok: https://drive.google.com/file/d/1PpYOxC8o-O11akUTSb3DWCZ_E432PTyH/view?usp=sharing

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24679
