### ISSUE TITLE
carrier module - getOrderShippingCostExternal does not get called

### ISSUE THREAD

**Issue by mschiele** [PrestaShop/PrestaShop#24591]
#### Describe the bug
I am building a custom shipping cost module. I want to load the shipping costs for my cart from an external api. The getOrderShippingCostExternal function does never get called. If I implement getPackageShippingCost or getOrderShippingCost the functions get called immediately.
After debugging, I found the reason why getOrderShippingCostExternal is not getting called. I need to set need_range in the carrier table to true. This is related to the snippet in Carrier::getCarriersForOrder()

```
if (is_array($groups) && !empty($groups)) {
            $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, $groups, self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
        } else {
            $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, [Configuration::get('PS_UNIDENTIFIED_GROUP')], self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
        }
```

So only modules that need_range set to true are taken.

It is not possible to call getOrderShippingCostExternal($params) having is_module = 1 and need_range = 0. If this is the case, the wohle mechanism of shipping carrier modules with external does not make sense to me.
A clear and concise description of what went wrong.

#### Expected behavior
Expected behaviour is that the getOrderShippingCostExternal gets called without using ranges.

#### Steps to Reproduce

1. Build a customer carrier module
2. create a carrier and set need_range to 0
3. load cart or checkout page
4. getOrderShippingCostExternal never gets called

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @mschiele ,

Can you send the module you're talking about so we can test ?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mschiele ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
