### ISSUE TITLE
Mimetype for svg is wrong in the filemanager configuration. It doesn't allow to upload svg files

### ISSUE THREAD

**Issue by Shagshag** [PrestaShop/PrestaShop#24597]
#### Describe the bug

Mimetype for svg is wrong in the filemanager configuration. It doesn't allow to upload svg files

```
//**********************
//Allowed mime types
//**********************
$mime_img = array('image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/tiff', 'image/svg');
$mime_file = array('application/pdf');
$mime_video = array('video/mpeg', 'video/mp4', 'video/x-msvideo', 'audio/x-ms-wma', 'video/x-flv', 'video/webm');

$mime = array_merge($mime_img, $mime_file, $mime_video);
```

SVG mimtype is "image/svg+xml" https://www.w3.org/TR/SVG11/mimereg.html

#### Expected behavior

The file manager should allow to upload SVG files but it doesn't.

#### Steps to Reproduce

1. Go to a product in admin
2. Click on description
3. add an image in the editor
3. Upload a SVG file

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by matks** [comment]
> #### Expected behavior
> The file manager should allow to upload SVG files but it doesn't.

This might be because SVG is not supported yet https://github.com/PrestaShop/PrestaShop/issues/10600

**Comment by Shagshag** [comment]
> This might be because SVG is not supported yet #10600

I should have be more clear, this issue is about the configuration of [responsivefilemanager](https://www.responsivefilemanager.com/) the filemanager used with TinyMCE. Not about ImageManager.

**Comment by florine2623** [comment]
Hello @Shagshag ,

Are you talking about this part in BO > Product > Description :
![Capture d’écran 2021-05-21 à 14 26 21](https://user-images.githubusercontent.com/16019289/119143422-de4d8a00-ba47-11eb-98d0-2780546a8896.png)

Thanks!

**Comment by Shagshag** [comment]
Yes, you should allow the two mimetype 'image/svg' and 'image/svg+xml'

**Comment by florine2623** [comment]
Hello @Shagshag ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4 and develop, so I can confirm that this behavior is indeed a bug.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.

Thanks for the PR!
