### ISSUE TITLE
Changing share_stock for a shop group make stock updates impossible via Webservice

### ISSUE THREAD

**Issue by web-cooking-factory** [PrestaShop/PrestaShop#24593]
Hi everyone !

I'm developping a module to synchronize stocks from Dolibarr to PrestaShop and i'm struggling with an issue. I think it has not been reported yet.

If you change the share_stock parameter for a shop group, there is a reset of quantities for already existing lines in database. But if the lines don't exist, they're not created. So stock update via Webservice becomes impossible (and POST is forbidden, there's also a mention of an addWs function in $webserviceParameters for class StockAvailable wich does not exist).

In my opinion, the resetProductFromStockAvailableByShopGroup function should go further and create the non-existing lines in database.

Steps to reproduce:
- create a shop group with share_stock to 1 and at least one shop inside
- create a product
- update the stock via Webservice => it works
- change share_stock to 0
- update the stock via Webservice => it does not work

Of course, if you manually change the quantity in back office, it solves the problem for the product you edit but it's not a solution if you want the stock to be handled from elsewhere.

It's a very specific case, I thing it does'nt occur often because it's only when you change share_stock but it's annoying. Please let me know if you need more information.

Have a good day !

* PrestaShop version: 1.7.6.5
* PHP version: 7.3.27

**Comment by florine2623** [comment]
Hello @web-cooking-factory ,

Can you downgrade your PHP version to 7.2 and try again ?
PS 1.7.6.5 is compatible up to PHP 7.2 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by web-cooking-factory** [comment]
Hello @florine2623,

unfortunately I can't sorry :/. Anyway I'm not sure it would change anything to the problem...

Btw Prestashop works pretty well on 7.3 !

**Comment by hibatallahAouadni** [comment]
Hello @web-cooking-factory 

Could you please provide some screenshots of this steps:
> change share_stock to 0

Did you change it via webservice or in BO?
And could you please provide the web service that you use to update the stocks :pray: 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @web-cooking-factory ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
