### ISSUE TITLE
carrier module - getOrderShippingCostExternal does not get called

### ISSUE THREAD

**Issue by mschiele** [PrestaShop/PrestaShop#24590]
I am building a custom shipping cost module. I want to load the shipping costs for my cart from an external api. The getOrderShippingCostExternal function does never get called. If I implement getPackageShippingCost or getOrderShippingCost the functions get called immediately.
After debugging, I found the reason why getOrderShippingCostExternal is not getting called. I need to set need_range in the carrier table to true. This is related to the snippet in Carrier::getCarriersForOrder()

```
if (is_array($groups) && !empty($groups)) {
            $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, $groups, self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
        } else {
            $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, [Configuration::get('PS_UNIDENTIFIED_GROUP')], self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
        }
```

So only modules that need_range set to true are taken.

It is not possible to call getOrderShippingCostExternal($params) having is_module = 1 and need_range = 0. If this is the case, the wohle mechanism of shipping carrier modules with external does not make sense to me.

PrestaShop version: 1.7.7.4
PHP version: 7.2

Thanks in advance

**Comment by hibatallahAouadni** [comment]
Hello @mschiele 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
