### ISSUE TITLE
[productcomments] Use circuit-breaker v4

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#24606]
To be compatible with the next verison of PrestaShop that will use Symfony 4.4, circuit breaker should be updated to v4

**Comment by PrestaEdit** [comment]
As I see, this could be closed due to the remove of Circuit-breaker : https://github.com/PrestaShop/productcomments/commit/b2568908bcae71087cf00ef1c562011f4b3ff038

**Comment by PrestaEdit** [comment]
As I see, this could be closed due to the remove of Circuit-breaker : https://github.com/PrestaShop/productcomments/pull/108
