### ISSUE TITLE
Rewrite rule not valid in .htaccess

### ISSUE THREAD

**Issue by mserramanxa** [PrestaShop/PrestaShop#24602]
#### Describe the bug

When use friendly URLs option, the images of a product with 8 digits or more in **id_product** are not displayed.

If I look at the **ps_product** table, the **id_product** field is defined as INT(10), for this reason, I understand that values such as 12345678 and 123456789 can be used.

I know it's really rare a shop with this high **id_product** values, but possible.

I think there is a problem with one of the rewrite rules generated by prestashop:

`RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]`

As you can read here:
https://stackoverflow.com/questions/5848962/rewriterule-using-10-11-12-and-so-on/5849017
https://stackoverflow.com/questions/715069/mod-rewrite-number-of-parameters-back-references-limitation
https://serverfault.com/questions/63068/modrewrite-9-back-reference-limit

There is a limit of 9 variables in back reference on mod_rewrite. So the described rewrite rule is not possible because **$10** is rewrited to **10** only until **$9** are valid.

By now, I solved the problem changing from this...

`RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]`

to this...

for **8** digits **id_product**:

`RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9.jpg`

for **9** digits **id_product**:

`RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$9/$1$2$3$4$5$6$7$8$9.jpg [L]`

Seems this works.

#### Expected behavior

View the images correctly.

#### Steps to Reproduce

Create a lot of products so that the product code reaches more than 7 digits and attach an image to this product. Or change the id_product autoincrement value to 12345678 before adding a new product with images.

* PrestaShop version: 1.7.7.2
* PHP version: 7.3.28

As I can see there is an old error because I have a couple of 1.6 installation with the same bad rule.

**Comment by florine2623** [comment]
Hello @mserramanxa ,

Your issue is related to https://github.com/PrestaShop/PrestaShop/issues/21181
It is fixed in version 1.7.8 of PrestaShop !

So I close your issue.

**Comment by mserramanxa** [comment]
> It is fixed in version 1.7.8 of PrestaShop !

Great news!

> So I close your issue.

Thank's
