### ISSUE TITLE
BO - Logs - There is no email address check

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24616]
#### Describe the bug

In the BO > Advanced Parameters > Logs page, in the logs by email section, there is no check of a valid address mail or not

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Logs page
2. In the logs by email section > set the field `Send emails to` to `test`
3. Save
4. See error: no validation (the type of the field should be email and not text)

This field is an improvement in 178x

**Screenshots**

#### Additional information![BO_log](https://user-images.githubusercontent.com/16067358/119168715-802da080-ba61-11eb-8fb2-a610462daa94.png)
* PrestaShop version: 178x
* PHP version: 7.4

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24620
