### ISSUE TITLE
BO -  Employee options are NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24615]
#### Describe the bug

In the BO > Advanced Parameters > Team > Employees page, Try to change `Password regeneration` to 5 min, enable `Memorize the language used in Admin panel forms` and click on save, a green alert is displayed but no update saved

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Team > Employees page
2. Try to change `Password regeneration` to 5 min, enable `Memorize the language used in Admin panel forms`
3. Save
4. See error: no data saved
5. try to Sign out from the BO 
6. Click `I forget my password` and reset it
7. Try to reset it again => See error
![image](https://user-images.githubusercontent.com/16067358/119167689-5fb11680-ba60-11eb-8416-23554dc887aa.png)

It should be` You can reset your password every 5 minute(s) only. Please try again later.`

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #24632
