### ISSUE TITLE
Remove marketplace from core

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24639]
#### Is your feature request related to a problem?

This Feature is a part of split between corporate prestashop/Open-sour prestashop.
Goal is to provide a full "non corporate" project.

Remove the module & theme catalog
Remove update API

#### Describe the solution you'd like

A clear and concise description of what you'd want to happen.
Remove all the call and implement an empty skeleton for the new API 

#### Tasks

- [x] #24739
- [x] #24740
- [x] #24741
- [x] #24742
- [x] #24743
- [x] #24744
- [x] #24746
- [x] #24747
- [x] #24748
- [x] #24749
- [x] #24750
- [x] #24751
- [x] #24752
- [x] #25028
- [x] #25030
- [x] #25033
- [x] #25008
- [x] #25457
- [x] Docs
  - PrestaShop/docs#1108
  - PrestaShop/docs#1088

**Comment by marionf** [comment]
Please note that the "module catalog" page should not be removed from the core: https://github.com/PrestaShop/PrestaShop/issues/25978

**Comment by Progi1984** [comment]
It's finished for the moment.
