### ISSUE TITLE
Create PS distribution build process

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24637]
#### Is your feature request related to a problem?

This Feature is a part of split between corporate prestashop/Open-sour prestashop.
Goal is to provide a full "non corporate" project. 

#### Describe the solution you'd like

- [x] ZIP downloaded from .com is different from the one on github, includes more features.
- [ ] Define build and test strategy
- [x] #26321

**Comment by MatShir** [comment]
To check during the freeze to see if all the docs and the build process are in order for the build of a new distribution

**Comment by eternoendless** [comment]
Defining the process to build a distribution is something we'll definitely work on in partnership with other PrestaShop teams, but I think it's beyond this project's scope, and shouldn't be tracked here.

Closing it to avoid adding up to an overwhelming number of stale issues.
