### ISSUE TITLE
Create install / update API for native modules

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24645]
## Is your feature request related to a problem?

This Feature is a part of split between corporate prestashop/Open-sour prestashop.
Goal is to provide a full "non corporate" project.

How to reinstall / update modules without addons

## Describe the solution you'd like

- [x] PrestaShop/PrestaShop#27428
- [x] PrestaShop/PrestaShop#27427

**Comment by madsoliver** [comment]
This is a great idea!
Please allow this to be used for non-native modules as well ❤️


**Update modules from external sources**
I would love to see a built in option to pull updates from an API specified in the module.
I am just throwing out some suggestions:

A module could hook into a new hook: `actionModuleUpdateCheck`

..And in the module one could do something like this:


    public function hookActionModuleUpdateCheck(&$params) {
        if($module_needs_update = $this->checkTheThirdPartyApiForLatestVersion($this->version)) {
            $params['downloadable_updates'][] = $module_needs_update;
        }
    }



**Install modules from third party sources**
For installing modules from non-native sources, I suggest an option in back-office to add more urls to the array of update repos. Like the way one would add more sources to apt, yum etc. in order to install the software you want, in addition to the one(s) that are preset from the os/prestashop installation.

Such third party apis could return a json-array of downloadable module zips, and voila!

**Comment by matks** [comment]
# Build a new API for native modules

## Needs

Build a PHP application that will allow shops to

1. know whether a module is available for a given shop version

Example: myshop.com v1.7.6 needs to fetch the API to know if it can download module autoupgrade

2. know what is the latest version for a given module, given a shop version

Example: myshop.com v1.7.6 has module welcome v4.2.1, needs to fetch the API to know what is latest version available for module v4.2.1

3. can be notified to fetch the needed data from github for a given module

Example: API can be notified that it has to refresh API data for module welcome

4. a CRON job can refresh all native modules data

5. an administrator must be able to modify/delete a module data

## Stack

Symfony 5, PHP8.0
Persistence: rely on Doctrine, can be plugged on sqlite or PostgreSQL

## Expected developments

- have a configuration list that provides the list of native modules
- build API endpoints for items 1 and 2
- build parsing logic that allows API to fetch the needed data from Github
- build API endpoint for item 3, that will trigger above logic for 1 module
- enable app to be run as CLI for item 4 to perform parsing logic for all modules
- allow above CLI process to report success or failures
- build a small Back-Office for item 5
- deploy a preprod environment
- deploy a prod environment

**Comment by matks** [comment]
## Suggestion of routing

**Route `GET /modules?shopVersion={...}`**
Returns whether a module is available for a given shop version
Expected JSON response: nil or a module version number

**Route `GET /version?moduleName={...}shopVersion={...}`**
Returns the latest version of module `moduleName` compatible with shop version `shopVersion`
Expected JSON response: nil or a module version number

**Route `GET /download?moduleName={...}&version={...}`**
Download module for given version

**Route `POST /refresh?moduleName={...}`**
Refresh API data for module `moduleName`
Expected JSON response: success or failure

**Comment by PierreRambaud** [comment]
## Suggestion of routing

**Route `GET /modules`**
Returns all modules and their related versions / PrestaShop version
Expected JSON response: nil or a module version number

**Route `GET /modules/{shopVersion}`**
Returns all available modules for a shop version
Expected JSON response: nil or a module version number

**Route `GET /module/{moduleName}/version[/{shopVersion}]`**
Returns the latest version of module `moduleName` compatible with shop version `shopVersion`
`shopVersion` is optional
Expected JSON response: nil or a module version number

**Route `GET /module/{moduleName}/download/{version}`**
Download module for given version, if version is not specify, get the latest.

**Route `POST /module/{moduleName]/refresh`**
Refresh API data for module `moduleName`
Expected JSON response: success or failure

**Route `POST /modules/refresh`**
Refresh API data for modules
Expected JSON response: success or failure

**Comment by madsoliver** [comment]
I might be over simplifying things now but, what about just using github to host the modules/releases? Github allready has releases built-in (and pre-releases), and maybe release metadata (such as recommended shop_version) can be added as a json/yaml-file relase asset alog with a downloadable zip-file for the module itself? Or maybe the release metadata can be added in the top/bottom of the release description (like jekyll front matter). 

The list of upgradable modules could either be hosted as a single-file repository with a yaml-file of module names and their repository url, or this list can be hard-coded in the upgrade-module.

If this is enough, it eliminates the need for a separate hosted module update api. Also as a bonus, it makes it simple for third party devs to add their modules to the upgrade module.

**Comment by matks** [comment]
> I might be over simplifying things now but, what about just using github to host the modules/releases? Github allready has releases built-in (and pre-releases), and maybe release metadata (such as recommended shop_version) can be added as a json/yaml-file relase asset alog with a downloadable zip-file for the module itself? Or maybe the release metadata can be added in the top/bottom of the release description (like jekyll front matter).

We think  if we use GitHub directly we will reach GitHub API rate very soon 😅 https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by madsoliver** [comment]
.. Right... That's a point 😅

**Comment by PierreRambaud** [comment]
@onklmaps we will use GitHub API of course, but add a cache system to be sure no one will encounter any issues
