### ISSUE TITLE
Make it possible to install MBO

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24640]
#### Is your feature request related to a problem?

This Feature is a part of split between corporate prestashop/Open-sour prestashop.
Goal is to provide a full "non corporate" project.

MBO is no longer pushed, so there must be an easy way to install it

#### Describe the solution you'd like

A clear and concise description of what you'd want to happen.

**Comment by MatShir** [comment]
MBO should be downloaded from the addons store 😄
