### ISSUE TITLE
Modules pushed by addons API become part of the zip (natives)

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24643]
#### Is your feature request related to a problem?

This Feature is a part of split between corporate prestashop/Open-sour prestashop.
Goal is to provide a full "non corporate" project.

### Module of the OS project included in the ZIP (natives):

- [x] - blockreassurance
- [x] - ps_bestsellers 
- [x] - ps_brandlist
- [x] - ps_cashondelivery
- [x] - ps_categoryproducts 
- [x] - ps_emailalerts
- [x] - ps_googleanalytics
- [x] - ps_newproducts 
- [x] - ps_specials
- [x] - ps_supplierlist
- [x] - ps_viewedproduct 
- [x] - productcomments
- [x] - psgdpr

#### Blockers

- [x] #27039
- [x] #27037
- [x] #27040
- [x] #27909
- [x] #27910
- [x] #27911

### Part of the OS project but not included in the ZIP

**The auto-upgrade**
This module is part of the OS project but is not included in the ZIP because:
- it should not be installed by default (the native modules are modules used in production and the upgrade module must not be used in production)
- This would pose problems with the composer dependencies which would be merged with the core.

-> The auto-upgrade module must be downloadable on prestashop-project.org (must have for the V8)

### To archive

- [x] - ps_buybuttonlite - This module can be archived
- [x] - welcome - This module is currently native but can be archived

**Comment by MatShir** [comment]
Check if all the module are native !

**Comment by PierreRambaud** [comment]
I think we have to remove `ps_buybuttonlite` from this list, it shouldn't be a module manage by the community, Otherwise, if we decide to take it, we assume we can improve it, and allow contribution from the community to add whatever they want.

**Comment by marionf** [comment]
About the auto-upgrade, we have decided that it will not be native but pushed in the new "module catalog" BO page by the new OS project's API. The module could also be downloaded from the project's page and uploaded through the BO (usefulll if deleted) @eternoendless

**Comment by PierreRambaud** [comment]
Could you please tell us what's the latest list you want?
Keep in mind, all modules store in the modules directory are automatically installed. We are also not able to keep ps_buttonlyte into the organization.

**Comment by PierreRambaud** [comment]
The welcome module has been archived as demand

**Comment by PierreRambaud** [comment]
I found some issues with modules:
- [ps_emailsmanager](https://github.com/PrestaShopCorp/ps_emailsmanager)  is not in this organization and has no change since 6 years  
- [psgdpr](https://github.com/PrestaShop/psgdpr) is not on packagist
- [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics) is not on packagist
- [ps_emailalerts](https://github.com/prestashop/ps_emailalerts) is not compatible with the latest develop version

**Comment by marionf** [comment]
> ps_emailsmanager is not in this organization and has no change since 6 years

You are right, and it can stay in PrestaShopCorp as it allows to import, preview and edit the packs of email templates sell on the marketplace (I edited the issue to remove it)

> psgdpr is not on packagist
ps_googleanalytics is not on packagist

Can we add them on packagist if it's required to add them in the zip ?

> ps_emailalerts is not compatible with the latest develop version

What is the problem and can we fix it to make it compatible ?

**Comment by PierreRambaud** [comment]
> > ps_emailsmanager is not in this organization and has no change since 6 years
> 
> You are right, and it can stay in PrestaShopCorp as it allows to import, preview and edit the packs of email templates sell on the marketplace (I edited the issue to remove it)
> 
> > psgdpr is not on packagist
> > ps_googleanalytics is not on packagist
> 
> Can we add them on packagist if it's required to add them in the zip ?
> 
> > ps_emailalerts is not compatible with the latest develop version
> 
> What is the problem and can we fix it to make it compatible ?

Yes we can add them on packagist and yes we can make the other module compatible. 
My message was more a note in order to let other developpers work on it :sweat_smile:

**Comment by eternoendless** [comment]
What's left to do for this issue?

**Comment by PierreRambaud** [comment]
> What's left to do for this issue?

Add packages on packagist and make ps_emailalerts compatible with latest version.

**Comment by Progi1984** [comment]
* `blockreassurance`
![image](https://user-images.githubusercontent.com/1533248/145216555-550d3504-eb30-4c7a-a81a-6bb88e17065a.png)

* :heavy_check_mark:  `productcomments`
![image](https://user-images.githubusercontent.com/1533248/145216608-b29d145a-9430-43a5-9d24-9844aee57438.png)

* :heavy_check_mark:  `ps_emailalerts`
![image](https://user-images.githubusercontent.com/1533248/145216886-89ba26f0-dc43-4718-ab74-788e41ad5f4d.png)

* :heavy_check_mark: `ps_googleanalytics`
![image](https://user-images.githubusercontent.com/1533248/145216841-60edeca3-d8fc-46db-b23f-2a403a2563a7.png)

* :heavy_check_mark: `psgdpr`
![image](https://user-images.githubusercontent.com/1533248/145216668-fabff761-e7a2-47ab-8aa7-1a0e021a4450.png)

**Comment by eternoendless** [comment]
The PR #27036 is blocked until ps_googleanalytics is fixed

**Comment by Progi1984** [comment]
@PrestaShop/product-team & @eternoendless : :heavy_check_mark:
