### ISSUE TITLE
The configuration adapter cannot retrieve data from a specific store.

### ISSUE THREAD

**Issue by Dreimus** [PrestaShop/PrestaShop#24647]
#### Describe the bug

Following the symfony way for adding a configuration page into a module, I've realized that the ConfigurationInterface and the Configuration Adapter don't allow to specify a shop.

`src/Core/ConfigurationInterface.php`
```php
interface ConfigurationInterface
{
    public function get($key);

    public function set($key, $value);
}
```

`src/Adapter/Configuration.php`
```php

public function get($key, $default = null)
{
    if (defined($key)) {
        return constant($key);
    }

    //If configuration has never been accessed it is still empty and hasKey/isLangKey will always return false
    if (!ConfigurationLegacy::configurationIsLoaded()) {
        ConfigurationLegacy::loadConfiguration();
    }

    // if the key is multi lang related, we return an array with the value per language.
    if (ConfigurationLegacy::isLangKey($key)) {
        return $this->getLocalized($key);
    }

    if (ConfigurationLegacy::hasKey($key)) {
        return ConfigurationLegacy::get($key);
    }

    return $default;
}
```

#### Expected behavior

Configuration Interface and Configuration Adapter must follow `classes/Configuration.php` get function declaration : 

```php

public static function get($key, $idLang = null, $idShopGroup = null, $idShop = null, $default = false)
{
    if (defined('_PS_DO_NOT_LOAD_CONFIGURATION_') && _PS_DO_NOT_LOAD_CONFIGURATION_) {
        return false;
    }

    // Init the cache on demand
    if (!self::$_initialized) {
        Configuration::loadConfiguration();
    }
    $idLang = (int) $idLang;

    if (!self::isLangKey($key)) {
        $idLang = 0;
    }

    if (self::$_new_cache_shop === null) {
        $idShop = 0;
    } else {
        if ($idShop === null || !Shop::isFeatureActive()) {
            $idShop = Shop::getContextShopID(true);
        }
    }

    if (self::$_new_cache_group === null) {
        $idShopGroup = 0;
    } else {
        if ($idShopGroup === null || !Shop::isFeatureActive()) {
            $idShopGroup = Shop::getContextShopGroupID(true);
        }
    }

    if ($idShop && Configuration::hasKey($key, $idLang, null, $idShop)) {
        return self::$_new_cache_shop[$key][$idLang][$idShop];
    } elseif ($idShopGroup && Configuration::hasKey($key, $idLang, $idShopGroup)) {
        return self::$_new_cache_group[$key][$idLang][$idShopGroup];
    } elseif (Configuration::hasKey($key, $idLang)) {
        return self::$_new_cache_global[$key][$idLang];
    }

    return $default;
}

```

#### Steps to Reproduce

1. Follow [symfony configuration form example](https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform)
2. Enable Multishop context
3. Try to get a specific value from a Command
4. get null as result

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

#### Workaround

**Easy Way**

1. Do not implement ConfigurationInterface neither get ConfigurationAdapter
2. add shop parameters in `getConfiguration` function :
```php
/**
 * {@inheritdoc}
 */
public function getConfiguration($id_lang = null, $shop_group_id = null, $shop_id = null): array
{

    $return = [];

    if ($shop_id !== null && $shop_group_id === null){

        /** @var Shop $shop */

        if ($shop_infos = Shop::getShop($shop_id)) {
            $shop_group_id = $shop_infos['id_shop_group'];
        }
    }

    if ($ftp_url = Configuration::get(self::FTP_URL, $id_lang, $shop_group_id, $shop_id)) {
        $return[self::FORM_NAME]['ftp_url'] = $ftp_url;
    }

    return $return;
}
```
3. Get the right information

**Complexe Way**
1. Add a new Configuration service symfony like with a Configuration Class which magically call static LegacyConfiguration functions : 
```php

public function __call($method, array $arguments)
{
    return call_user_func(Configuration::$method,$arguments);
}
```
2. Call your new configuration service in your configurationDataConfiguration Class
3. Use the configuration with the new available arguments

**Comment by hibatallahAouadni** [comment]
Hello @Dreimus 

Thanks for your issue!
Ping @PrestaShop/prestashop-core-developers could someone please try to reproduce the issue :pray:  (it's too technical for me :sweat_smile: )

Thanks in advance!

**Comment by ghost** [comment]
Bonjour @Progi1984 , @matks ,

Any thoughts on this issue ?

Cheers,
Luc Michalski

**Comment by kpodemski** [comment]
Here you can find more informations about using new methods in configuration form:
https://devdocs.prestashop.com/1.7/development/multistore/configuration-forms/

Getting values:
https://devdocs.prestashop.com/1.7/development/multistore/shops-configuration/#usage

👍

Important: it's available since 1.7.7

@hibatallahAouadni it's not a bug, it's just a missing feature which was added from 1.7.7

**Comment by Dreimus** [comment]
Interesting ! I've missed this, and will try it out asap.

Thanks !

**Comment by hibatallahAouadni** [comment]
Thanks @kpodemski for your quick reply :rocket: 
So, I close the issue.
