### ISSUE TITLE
Adapt the 'Help' window in the back office so that it fetches information from GitBook instead of Confluence.

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#24651]
Right now, the Help" window in the back office fetches information from the documentation hosted on Confluence. When we start using GitBook, this help window should fetch information from GitBook. 

As requested by @Progi1984, I have created this mapping for the 1.7 version, replacing Confluence IDs with Github paths.
[mappinggitbook.txt](https://github.com/PrestaShop/user-documentation-en/files/6538157/mappinggitbook.txt)

For the PrestaShop 8 version, we'll have one space on GitBook for the PrestaShop 8 documentation. Each space will be synchronized with one repository on GitHub. The Help window should fetch information from either the English or the French space depending on the language of the store. 

We will need a new mapping for the V8 documentation, as it will be on a different repo.

- [x] https://github.com/PrestaShop/user-documentation-landing/issues/68
- [x] https://github.com/PrestaShop/contextual-help-api/issues/2
- [x] https://github.com/PrestaShop/PrestaShop/issues/27189

**Comment by MatShir** [comment]
Status:
Blocked, need to create a server for the project. We are waiting SysAdmin authorization :)
