### ISSUE TITLE
Create 301 redirections from Confluence to Gitbook

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#24650]
PrestaShop user documentation will soon no longer be hosted on Confluence but on GitBook. To avoid weakening our SEO, we would like to set up 301 redirections. For example,

http://doc.prestashop.com/display/PS17/What+you+need+to+get+started will have to redirect to https://docs.prestashop-project.org/1-7-documentation/getting-started/what-you-need-to-get-started

We made a mapping on Google Sheets with old and new URLs accessible here :

https://docs.google.com/spreadsheets/d/1aFf4wNbti7zRIbuUFtuuel-Z2gbuHEnoXkgbeIYmBoo/edit#gid=1993002961

These redirections have to be done for the following languages: English, French, Spanish, Dutch, and Italian. 

I am available if you have any questions.☺️

**Comment by eternoendless** [comment]
May I suggest `docs.prestashop-project.org`?

**Comment by Progi1984** [comment]
@eternoendless `docs.prestashop-project.org` is for user docs or dev docs ?

**Comment by eternoendless** [comment]
We'll use `devdocs.prestashop-project.org` for devdocs

**Comment by Julievrz** [comment]
This suggestion sounds good to me. :-)

**Comment by Progi1984** [comment]
@Julievrz Issue created for the IT team for the first migration test : https://forge.prestashop.com/browse/INFRA-189

**Comment by Progi1984** [comment]
Set in Blocked

**Why ?** We are waiting for the @prestashopCorp IT Team :muscle:

**Comment by atomiix** [comment]
Status update: doc for PS 1.4 and PS 1.5 are now redirected to docs.prestashop-project.org.

**Comment by matks** [comment]
@atomiix What is the status of this topic? Is there something left to be done?

**Comment by Julievrz** [comment]
The status of the issue can be followed here: https://forge.prestashop.com/browse/INFRA-133 

We are still missing some redirections.

**Comment by nicosomb** [comment]
I read "all is done" on JIRA side
@Julievrz could you confirm that this issue can be close?

**Comment by Progi1984** [comment]
(Ping @atomiix on the dev side)

**Comment by Julievrz** [comment]
Seems good to me :)

**Comment by atomiix** [comment]
Seems all good to me too! Thanks a lot @djodjo3
