### ISSUE TITLE
Docker support for ARMv7

### ISSUE THREAD

**Issue by NajibNour** [PrestaShop/PrestaShop#24655]
#### Is your feature request related to a problem?

Issue is cannot run on an ARM based system.

#### Describe the solution you'd like

Could a docker image be built towards ARMv7 arch?

#### Alternatives you've considered

I have considered building it my self but it seems that your build files always start with a default AMD64 Prestashop Image.

#### Additional context
 Please? <3

**Comment by hibatallahAouadni** [comment]
Hello @NajibNour 

Thank you for your suggestion. The Developer Team will take a look. Please stay tuned!
> Could a docker image be built towards ARMv7 arch?

Ping @PrestaShop/prestashop-core-developers could someone please answer @NajibNour question :pray: 

Thank you

**Comment by matks** [comment]
Hello @NajibNour the https://github.com/prestashop/docker images aim to provide general-usecase images for webservers. If I am no wrong, most webservers run on AMD, not ARM 🤔  ? Then we will probably not do it.

> Please? <3

I'm sorry 😅  we do not provide tools just to please people, we try to provide what we need for ourselves and that can be used by the majority of our users. But if you are wanting to build it for yourself, don't hesitate to share it with the community 👍  some people might be interested in it.

**Comment by hibatallahAouadni** [comment]
Hello,

Thanks @matks for your quick reply :wink: 
Well, the Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you
