### ISSUE TITLE
Product page v2 image dropzone have some design issues

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#24664]
#### Describe the bug

When you've more than 2 images, some design issues appears :
![image](https://user-images.githubusercontent.com/14963751/119667393-898a8480-be36-11eb-81b3-e58e8e52c653.png)

#### Expected behavior

The photo icon should have a fixed width and images should to at the line when they've no spaces

#### Steps to Reproduce

1. Go to Product page v2 and add multiple ### images

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.x

**Comment by hibatallahAouadni** [comment]
as discussed in Slack, here's the screenshot of the bug that @jolelievre and I reproduce it:

![image](https://user-images.githubusercontent.com/23308427/119855867-92e91f00-bf12-11eb-8d7a-5ace61b34239.png)

PS: I think it's related to this PR #24572

**Comment by jolelievre** [comment]
@hibatallahAouadni indeed the bug you are showing came from a problem with one of our dependency and was fixed by #24572

You should be able to test the problem @NeOMakinG mentioned correctly now

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24665
