### ISSUE TITLE
ps_checkout CDN image should be moved into the repo

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#24674]
#### Is your feature request related to a problem?

Image from https://github.com/PrestaShopCorp/ps_checkout/search?q=amazonaws should be moved into the repo directly.

**Comment by matks** [comment]
@mvorisek PrestaShop Checkout https://github.com/PrestaShopCorp/ps_checkout/ is a module built and distributed by PrestaShop company and consequently is out of the scope of the OSS project 😉  . It is not in the PrestaShop GitHub organization.

**Comment by mvorisek** [comment]
But it is installed by default, thus this should be fixed. The only non-local resource aftern an installation. Makes Behat testing unstable. As there the project has no issues, I find this ticket 100% legit 8-)
