### ISSUE TITLE
Default category checkbox is not visible

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24671]
### Describe the bug
Radio button to select default category of a product is not visible, if some categories with longer names are created, or just generally, you have a lot of categories.

The radio button is on the left, but it's outside of the categories window 😄  .

I had some clients contacting me and not knowing, how they could select the default category. It gets hidden and due to no scrollbars or shadows visible, it's not very clear there is something next to the category tree.

### How to reproduce

0. Use some normal display, not 2560 or 4K.
1. Make some categories with longer names.
2. Open BO > Product and edit some product.
3. See (or not see in this case) 😄

### Screenshots
Screenshots from 2 different stores attached. It starts to get visible on circa 2300px+ screen width. Even on 1920, it's hidden.

![cat1](https://user-images.githubusercontent.com/6097524/119799526-716d4080-bedc-11eb-8203-0c1df2b32878.JPG)

### Cause
`category-tree-overflow` class

### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Could you pelase provide steps to reprodcue the issue.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

You're right, you need to scroll to see the checkbox in PS1.7.6.7 and PS1.7.7.4:

https://www.awesomescreenshot.com/video/3953760?key=2adf3a4f315ea5ea39aacd1980d5e5bc

But, on develop, when you try to open the category tree, the scroll will be automatique active and you will see the checkboxes:

https://drive.google.com/file/d/17VwNS7Y5v3-Y2DBrd7nBzG06NTMRohpZ/view

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Welll, both are wrong, it should be visible both, and the category name should be wrapped. 😛

**Comment by hibatallahAouadni** [comment]
@Hlavtox well, I think what you're asking for is an improvement :wink: 

So, thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Socrapop** [comment]
Hello ! 
I tried to improve this by removing the nowrap on each category label, so the scrollbar doesn't appear at all and we can always see it.
I made a PR :
https://github.com/PrestaShop/PrestaShop/pull/24808

I don't know why this nowrap was there, because it seems very unfriendly when you have a long list of categories, with long names, and a small screen.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24808

**Comment by matks** [comment]
@Hlavtox you might want to have a look at https://github.com/PrestaShop/PrestaShop/pull/24808 😉
