### ISSUE TITLE
Precise product weight is not correctly displayed in back-office

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#24687]
#### Describe the bug

Title says it all.

#### Expected behavior

We should see precise weight correctly.

#### Steps to Reproduce

1. Go to Catalog -> Product
2. Edit product
3. Go to 'Shipping' tab
4. Set 'weight' to `0,01731`
5. As you can see, in BO it shows us only `0,017` but in database value is correct

**Screenshots**

https://www.dropbox.com/s/wljgcmiatg9w2d7/Nagranie%20z%20ekranu%202021-05-28%20o%2010.29.32.mov?dl=0

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @kpodemski ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4 and develop, so I can confirm that this behavior is indeed a bug.

Thank you for the PR!
