### ISSUE TITLE
Template hierarchy doesn't work with CMS Category

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#24683]
#### Is your feature request related to a problem?

Yes. Template hierarchy doesn't work with CMS categories

#### Describe the solution you'd like

Make a proper improvements to TemplateFinder to allow developers to use template hierarchy for CMSCategory

#### Alternatives you've considered

n/a

#### Additional context

n/a

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Is it possible to get your insight on that ? 
Thanks!

**Comment by matks** [comment]
Thanks for the ping @florine2623 😉 

@kpodemski feature idea is relevant I think 👍
