### ISSUE TITLE
[Multi-invoices] BO - Orders - A modal should'nt be displayed when we add the same product to a specific invoice with updating price

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24691]
#### Describe the bug

Reported [here](https://github.com/PrestaShop/PrestaShop/pull/24253#issuecomment-849614195)
This issue occurs when we have multi-invoice (more than 2 invoices created).
When we try to add the same product to a specific invoice, a modal is displayed.
It shouldn't, we need to have only alert `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

#### Steps to Reproduce

1. Create an order
2. Go to BO > Orders > View last order created with `Product1`
3. Generate an invoice
4. Add the same product `Product1` with creating a new invoice
5. Add the same product to any invoice with changing the product price 
6. See error: a modal `Edit the price` is displayed => it shouldn't, we should have `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

**Another case**

1. Create an order
2. Go to BO > Orders > View last order created with `Product1`
3. Generate an invoice
4. Add the same product `Product1` with creating a new invoice
5. Edit the product price and confirm the update
5. Add the same product to any invoice without changing the product price 
6. See error: a modal `Edit the price` is displayed => it shouldn't, we should have `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

![image](https://user-images.githubusercontent.com/16067358/119973446-c7f97e00-bfb3-11eb-9684-1637ad766e4c.png)

With PS176 => we can add the same product without any alert

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24765
