### ISSUE TITLE
Route to products : -{id}{-:id_product_attribute} position changed to end issues . 

### ISSUE THREAD

**Issue by Brothely** [PrestaShop/PrestaShop#24693]
Hi,

BO: In the Shop Parameters=>SEO & URLS page , when we change the route to products :
Example : default is {category:/}-{id}{-:id_product_attribute}{rewrite}{-:ean13}.html changed to => {category:/}{rewrite}{-:ean13}-{id}{-:id_product_attribute}.html  ( changed -{id}{-:id_product_attribute} to after {-:ean13}) .

![Schema of URLS changed Route to products](https://user-images.githubusercontent.com/63552105/119975850-40f5d700-bfae-11eb-807c-79b695fb4d8e.png)

After makes this changes all works normal in the front page of website.  
In the Front page ( website ) already we see URLS with products id  after {-:ean13} . 
![Font page id](https://user-images.githubusercontent.com/63552105/119976186-a34ed780-bfae-11eb-9af8-66ab61fd3d26.png)

-  but if now we add for one new product combination for product , 
![Example new product combination](https://user-images.githubusercontent.com/63552105/119976363-e7da7300-bfae-11eb-8f27-28432358929e.png)

- on the front page of website when click to go product page will be redirect to https://domain.com/pt/index.php?controller=404#/2-tamanho-m ( not found product ).
![front page Error](https://user-images.githubusercontent.com/63552105/119976763-81098980-bfaf-11eb-9d22-3c2727846149.png)

- But if we remove product combinations for this product , will be works normal again.

Someone can help me ?  Please...

thanks so much!

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @Brothely ,

I managed to reproduce your issue in PS 1.7.6.5.
But I can't reproduce your issue in PS 1.7.7.4 as you can see from my screen record : 
https://drive.google.com/file/d/1X2EXSgQkH8pUUgQKVXL77mRQ_lxwrfyH/view 

It has been fixed in PS 1.7.7.X
So I'll close your issue.
Thanks!

**Comment by Brothely** [comment]
Hi, @florine2623 

Do you test this issue with product existing before and it already have product combination added ?   Because that issue just happen when you add combination for new product.  

I was testing in the PS 1.7.6.9 , products already existing before with combination , can´t reproduce this issue .  
![test1](https://user-images.githubusercontent.com/63552105/119998656-d00fe880-bfc8-11eb-8c49-dcc00510825b.png)

After added New combination for another procdut , when opened will shown as below:
![test2](https://user-images.githubusercontent.com/63552105/119998993-2aa94480-bfc9-11eb-8363-45459acce474.png)

Thanks so much!
