### ISSUE TITLE
Bank transfer module shows amount 0

### ISSUE THREAD

**Issue by javierVP** [PrestaShop/PrestaShop#24705]
The bank transfer module shows amount 0 when placing the order.
The module version is v2.1.0
PrestaShop version 1.7.7.4
PHP Version: 7.3.27
Link capture: https://www.awesomescreenshot.com/image/8837076?key=29cc5674804e9b12086b1bbb6ca0fab9

**Comment by hibatallahAouadni** [comment]
Hello @javierVP 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by javierVP** [comment]
Ok I better explain the problem.

0. I have the Classic template.
1. I place a normal order.
2. I select the bank transfer payment method.
3. When the confirmation is made, the module shows the amount 0 in the order confirmation instead of the order amount.

The module ps_wirepayment version is v2.1.0
PrestaShop version 1.7.7.4
PHP Version: 7.3.27
![ps_wirepayment_order](https://user-images.githubusercontent.com/42347565/120177002-33d42480-c208-11eb-9b29-b14d117f2120.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @javierVP 

Thanks for the steps but I didn't manage to reproduce the issue with PS1.7.7.4 and Bank transfer v2.1.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/120181657-ac89af80-c20d-11eb-9f7d-6e2aa07c4262.png)

Thanks!

**Comment by javierVP** [comment]
Well, it is a clean installation, there are no updates involved.

**Comment by javierVP** [comment]
What file controls the order variable in the module?

**Comment by javierVP** [comment]
I was able to solve it thanks to this solution in the forum
https://www.prestashop.com/forums/topic/1041745-solved-no-amount-in-bankwire-summary-on-confirmation-page/
