### ISSUE TITLE
Product Reference and Product Quantity not updating

### ISSUE THREAD

**Issue by num47** [PrestaShop/PrestaShop#24700]
#### Describe the bug

I was trying to edit the a default product that comes after installation whose product ID number 1. I was trying to update the Reference number of the product but i could not update it unless i have deleted all the combinations of the product. And, after deleing all the combinations of the product, i was trying to update the product quantity and i could not update it any way. 

#### Expected behavior

Expected behavior is simple - Anyone would like to update their product reference and available quantities anytime they want to without facing any trouble. 

#### Steps to Reproduce

1. Go to Back Office
2. Click on Catalog > Products 
3. Scroll down to 'Hummingbird printed t-shirt (ID number 1)'
4. Try to edit the Reference number with something else.
5. Click "Save".
6. Check the front office of the product page and check the section of "Product Details" Tab and you will see that the 'reference' is not changed. 
7. Go back to Back Office. 
8. Then, delete the combinations of the products. 
9. Then change the product quantities.
10. Click 'Save'
11. Check the front office of the product page and check the section of "Product Details" Tab and you will see that nothing is changing. 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by aespasa** [comment]
Hello, I'm not sure that is a bug. I suppose, those "demo_1" references are assigned to the product's combinations, which are not visible directly in the BO. I guess the product details section is displaying the selected combination. 

I also have tried to switch the "Product with combination" option to the "Simple product" one before updating the quantity, and my FO is now displaying the proper details (custom product reference and the new quantity).

Let me know if I'm wrong ...

Do you have any bugs with some references or quantities in a production environment?

Regards,

**Comment by num47** [comment]
Hello,
I was trying everything to update the product quantity and no way i could do it. But, suddenly it is working now well and good. Can’t really figure what prevented it to work few hours ago. I must be missing something. I will research more about it. Thank you bro.
