### ISSUE TITLE
Error on Customer Page

### ISSUE THREAD

**Issue by EDV4BIZ** [PrestaShop/PrestaShop#24703]
Since the update to Version: 1.7.7.4
At some Customers when we try to open the Customer Page we got this error:
![image](https://user-images.githubusercontent.com/31078768/120080868-0037b400-c0bb-11eb-8d47-231892922eb9.png)
Whats the mistake?

**Comment by hibatallahAouadni** [comment]
Hello @EDV4BIZ 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems your issue related to customer's address, you could enable the debug mode to understand better the issue. (you may find some answers in this thread #22215)

Thanks!
