### ISSUE TITLE
Link to products in order details for client

### ISSUE THREAD

**Issue by marekjedrzejewski** [PrestaShop/PrestaShop#24702]
#### Is your feature request related to a problem?

In order details in customer account page product section only has name and reference number. Would be nice to also have link to product page there to see what it actually is.

#### Describe the solution you'd like

Name of product, when inspected already is an `a` element, but is missing `href`, looks like feature already was planned, did not make it in its entirety.

**Comment by hibatallahAouadni** [comment]
Hello @marekjedrzejewski 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by marekjedrzejewski** [comment]
I'm not sure if I found the right place, but looks like the one I was looking for:
https://github.com/PrestaShop/PrestaShop/blob/3b6de77522aad17a38b1adbfcb4a4fb143c0d376/themes/classic/templates/customer/_partials/order-detail-no-return.tpl#L40-L42

Looks like link is reserved for downloadable products. In my opinion it would be better if there was link to product page there, and download link would appear as separate thing, but it's not up to me to decide, though I'll try to implement it this way.

**Comment by hibatallahAouadni** [comment]
@marekjedrzejewski thanks for your PR :rocket:
