### ISSUE TITLE
IDE stubs for XxxCore classes

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#24709]
This is technical question/feature request.

What is the best approach currently to get IDE understand the XxxCore classes as Xxx? Is there any existing code to generate stubs for them?

**Comment by PierreRambaud** [comment]
Hi,

There is a file named `class_stub.php` that is automatically created by the PrestaShopAutoload class. AFAIK, it's working automatically for all recent IDE, even on VIM or Emacs :)

**Comment by mvorisek** [comment]
I have an issue with it as when I click a class name (excl. known method/prop), I end up in that stub file instead of wanted class.

What about putting the stubs directly above the XxxCore classes?

Example:

![image](https://user-images.githubusercontent.com/2228672/120178585-f2dd0f80-c209-11eb-81e2-4ebec864184b.png)

Please let me know if a PR like this is wanted. It is safe, as the if cond can be executed by php at compile time, but not by IDE, thus even no unreachable warning is printed.

This solution also does not require install (running `PrestaShopAutoload`) which is usefull for the community when creating a PR.

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

You can post your question on Slack, why you use Github?
As you know we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, you can ask for help in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

So, no offense :pray: sorry but I have to close the issue.
Thanks @PierreRambaud for your quick reply :rocket: 

Thank you

**Comment by mvorisek** [comment]
Because it is a feature request and I wanted to validate first if PR for the change will be accepted.

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

I see :slightly_smiling_face: 
So, please next time validate (while discussing with developers on Slack) then submit your feature request here :wink: 
And don't forget to respect and to follow the provided template to submit a complete feature request :pray: 

Well, you can continue discuss with @PierreRambaud here now :wink: 
When you validate your feature, modify your the original post (don't forget to follow the feature template) :wink: 
Then ping me to reopen the issue :ok_hand: 

Thanks for your understanding :relaxed:

**Comment by PierreRambaud** [comment]
> I have an issue with it as when I click a class name (excl. known method/prop), I end up in that stub file instead of wanted class.
> 
> What about putting the stubs directly above the XxxCore classes?
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/2228672/120178585-f2dd0f80-c209-11eb-81e2-4ebec864184b.png)
> 
> Please let me know if a PR like this is wanted. It is safe, as the if cond can be executed by php at compile time, but not by IDE, thus even no unreachable warning is printed.
> 
> This solution also does not require install (running `PrestaShopAutoload`) which is usefull for the community when creating a PR.

I think it's up to you to properly configure your IDE as the sub is already created by the autoloader.
