### ISSUE TITLE
Drop DbMySQLi

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#24714]
#### Is your feature request related to a problem?

PDO is mandatory [1], no need for Mysqli class.

#### Describe the solution you'd like
Drop DbMySQLi

[1] https://github.com/doctrine/dbal/blob/v2.10.1/composer.json#L36

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: could you please descibe the solution you would like in your post :pray: 

Thank you

**Comment by mvorisek** [comment]
see title :)

**Comment by matks** [comment]
I guess this should be discussed and voted by maintainers 🤔  . The question behind is "Should we keep MysQLi implementation inside PS scope or push it out of scope?"

I agree that PDO is more popular and more widely used than MySQLi although MySQLi brings some features PDO does not have. So pushing MySQLi out of PrestaShop (= decrease the maintenance burden) might be interesting.

ping @PrestaShop/prestashop-maintainers ?

**Comment by mvorisek** [comment]
Please start the voting :)

If async queries are wanted, then mysqli is the only option, otherwise I do not see any advantage over PDO which Doctrine DBAL requires anyway.

**Comment by PierreRambaud** [comment]
PDO is mandatory, but it doesn't mean MySQLi shouldn't be supported :thinking: 
Even if we are not using some mysqli features, maybe modules developers do. 
I see no valid reason to drop it right now in fact

**Comment by mvorisek** [comment]
Ok to deprecate `DbMySQLi` class? This allows to simplify the return phpdocs a lot, phpstan found already one error.

**Comment by PierreRambaud** [comment]
Deprecated means it's not supported anymore and will be removed in the next major.

**Comment by mvorisek** [comment]
Yes, which I belive the wanted state - can we agree on it?

**Comment by PierreRambaud** [comment]
No, because as I said above, I see no valid reason to drop mysqli support :thinking:

**Comment by mvorisek** [comment]
There is, that ext may be unavailable and there is no reason to support it except BC, which we can deprecate now.

**Comment by PierreRambaud** [comment]
The extension may not be available but it doesn't mean we have to remove the support.

**Comment by matks** [comment]
Hello @mvorisek 

In order to have a voting, we would need to go through the ADR process. However this is a very time-consuming process (you can read about it here https://github.com/PrestaShop/ADR/issues/18).

If you are very motivated, you can try 😄  but I'm not sure if such a topic that is not critical will be able to go through all maintainers attention. As you have noticed, we are very very busy so we focus a lot on critical topics and topics not critical do not get enough attention 😥  (that's not a good thing but it's how it is).

I close the issue for now as it cannot go further without a vote. We can reopen it later if a positive vote happens and we decide to drop MySQLi.
