### ISSUE TITLE
http_build_url can not be no longer required from tools/

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#24722]
#### Describe the bug

Requires must be removed, see https://github.com/PrestaShop/PrestaShop/search?q=http_build_url

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by mvorisek** [comment]
see title - "can not be no longer required" is full information

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24760
