### ISSUE TITLE
Customer Thread with no message inside creates exception. 

### ISSUE THREAD

**Issue by bastienuh** [PrestaShop/PrestaShop#24726]
#### Describe the bug

When I go on an order page, I have this error message :
```
Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderMessageForViewing::__construct() must be of the type string, null given, called in /src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 682
```

It seems to be linked to #22215 but behavior are slightly differents, and it's not a bug with some column set to null instead of empty.

#### Expected behavior

The order page correctly displayed.

#### Steps to Reproduce

I don't know how it happened, because it's a very recent order (yesterday) and not due to a migration.

I have make some debug in the database.

The order is 78279. I went to my database to search some thread with this id_order, I found two :
![Capture d’écran 2021-06-01 à 11 49 46](https://user-images.githubusercontent.com/1685778/120303909-93e1ce00-c2cf-11eb-941a-8c95d43a09af.png)

I have, so, two id_customer_thread : 40117 and 40118.

So, I'm going to look in the ps_customer_message table : 
```sql
SELECT * FROM `ps_customer_message` WHERE `id_customer_thread` IN (40117,40118)
```

And here is the bug:
![Capture d’écran 2021-06-01 à 11 52 07](https://user-images.githubusercontent.com/1685778/120304192-dacfc380-c2cf-11eb-8c82-0c1e863db9b7.png)

I have messages **ONLY** for id_customer_thread 40117.

So in GetOrderForViewingHandler.php file, at line 671, when the foreach is on id_customer_thread 40118, the message is of course NULL (last block, red border, shows it) :

![Capture d’écran 2021-06-01 à 11 58 07](https://user-images.githubusercontent.com/1685778/120305267-d9eb6180-c2d0-11eb-9587-982176c401e6.png)

**I don't know where is the bug**, but the problem, here, is that a thread without message is queried. I don't know why the thread exists if it has any message, but it's a fact, and OrderMessageForViewing needs a string, not null for parameter 2.

I will add a `if` in the method, but it's a hot fix, not very relevant.

**Screenshots**
![Capture d’écran 2021-06-01 à 11 47 33](https://user-images.githubusercontent.com/1685778/120303520-3483be00-c2cf-11eb-8570-8f3dbd3d2722.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

Thanks for the details :pray: 
Did you upgrade your shop lately? and did you encounter any issues while upgrading? any warning?
About the order with id = 78279, is it created by the customer with id = 40118? 
If so, was this order created before the upgrade or after the upgrade?
Please check and feedback.

Thanks!

**Comment by bastienuh** [comment]
The shop was upgraded last week, before this order. The order was made yesterday evening.

The order id is 78279, the customer id is 2808 (as you can see it on screenshot) and the id_customer_thread are 40117 and 40118.

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

> The shop was upgraded last week, before this order. The order was made yesterday evening.

So your issue is not related to the upgrade :wink: 
Well, I tried to reproude your issue following these steps:

1. FO > the Customer H create an Order and send a message (in the delivery step) 
2. BO > the Admin responds
3. FO > Customer H send two message successively
4. BO > I have no error (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/120347338-79721980-c2fc-11eb-8887-2a311c53ef4e.png)

Please check and feedback.
Thanks!

**Comment by ngourle** [comment]
Hello
I've got similar problem in 1.7.7.1.
Two threads for one order and only messages in the first thread (who is status closed)

If you need information, I will send it you.

**Comment by bastienuh** [comment]
Thanks @ngourle !

**Comment by hibatallahAouadni** [comment]
Hello @bastienu @ngourle 

Could you guys please try to reproduce it again while screen recording, cause I didn't manage to reproduce it and it means that something is missing.
Please check and feedback.

Thanks!

**Comment by bastienuh** [comment]
Mmmmh... I do **NOT** know how it happens. 
The only thing I see is that, sometimes, I can't access to order page in the back office because I have a thread without any message inside. I did not make it myself : the customer made the order. I don't know, so, how to reproduce it.

**Comment by matks** [comment]
> Mmmmh... I do **NOT** know how it happens.
> The only thing I see is that, sometimes, I can't access to order page in the back office because I have a thread without any message inside. I did not make it myself : the customer made the order. I don't know, so, how to reproduce it.

I have seen some payment modules creating customer threads at step `validatePayments()` in an attempt to persist some data from the payment gateway inside the order (such as payment confirmation). It could be one source of such threads.

**Comment by khouloudbelguith** [comment]
Hi @bastienu,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank you, Khouloud
