### ISSUE TITLE
Bug order print

### ISSUE THREAD

**Issue by Ideoclic** [PrestaShop/PrestaShop#24733]
#### Describe the bug

Bug when the text is too long.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

3. Print order (long title product)

**Screenshots**

![0ed39a8440d4a253ee12fc08893c147c](https://user-images.githubusercontent.com/80488574/120401498-5701ef80-c340-11eb-9d0b-54a2872b32a4.png)
)

#### Additional information

* PrestaShop version: 1.7.6.9

**Comment by hibatallahAouadni** [comment]
Hello @Ideoclic 

That issue has been fixed with PS1.7.7.0 (while migrating the Order page), see the attached screenshots below:

**Print Order**
![image](https://user-images.githubusercontent.com/23308427/120443012-876c7c80-c386-11eb-9070-704cddae3f9b.png)

So, I close the issue :wink: 
Thanks!

**Comment by Ideoclic** [comment]
Hey!

Any fix for my version ? i dont wan't migrate.

Thx

**Comment by matks** [comment]
When 1.7.7.0 was released, branch `1.7.6.x` became EOL (see https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/supported-branches/) so no more releases will be done and released for 1.7.6 by the PrestaShop official project

https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/supported-branches/
