### ISSUE TITLE
[BO - Mobile] some Frontend regressions in View Order Page

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24732]
#### Describe the bug

some Frontend regressions in Order Page

#### Expected behavior

nice and neat responsive display

#### Steps to Reproduce

1. Go to Orders > Orders
2. Click on **View** Order
3. See error > Update order status select & button is not well fit (see screenshot n°1)
4. Change the status to payment accepted
5. See error > all buttons are not well fit (see screenshot n°2)
6. Scroll down to **Products** bloc (add a cart rule to the order)
5. See error (see the screenshot n°3, the cart rule table is misplaced even with 1.7.7.4)

**Screenshot n°1**

![image](https://user-images.githubusercontent.com/23308427/120283152-2cba1e80-c2bb-11eb-99b8-9c9553bbf8fa.png)

**Screenshot n°2**

![image](https://user-images.githubusercontent.com/23308427/120284711-d3eb8580-c2bc-11eb-816b-6980dcb2e814.png)

**Screenshot n°3**

![image](https://user-images.githubusercontent.com/23308427/120291710-e6b58880-c2c3-11eb-81b7-1f74e29d002b.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #24890 by @NeOMakinG
