### ISSUE TITLE
BO - Orders page - Cannot add free shipping discount when Total products = 0

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24753]
#### Describe the bug

In the BO > Orders > Orders details page, when Total products = 0, we cannot add a discount for free shipping.
But The inverse OK: we have shipping = 0, we can add a discount 100% 

#### Expected behavior

With PS1769 => ok

#### Steps to Reproduce

1. Create an order with product price = 0 ( **or** a discount amount > Total **or** discount percent = 100% )
2. Choose a **carrier not free** 
![image](https://user-images.githubusercontent.com/16067358/120461286-29e22b00-c39a-11eb-865e-a781e266612f.png)
3. Go to BO > Orders > Last Order created
4. Try to add a free shipping discount
![image](https://user-images.githubusercontent.com/16067358/120461434-4aaa8080-c39a-11eb-9d6f-5a9d1ef4e77e.png)
5. See error 
![image](https://user-images.githubusercontent.com/16067358/120461539-60b84100-c39a-11eb-8aa2-91dd629d6c80.png)

With PS1769 => ok
https://drive.google.com/file/d/1_v0Mkg3Jpe4jy6dZIiaMvOJtYQT71lq0/view?usp=sharing

#### Additional information

* PrestaShop version: 1774, 1775build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #24762 by @Progi1984
