### ISSUE TITLE
Hook on address update or create

### ISSUE THREAD

**Issue by bastienuh** [PrestaShop/PrestaShop#24756]
#### Describe the bug

I tried to use a hook on `actionObjectCustomerAddressUpdateAfter` or `actionObjectAddressUpdateAfter` (as described in the documentation with `actionObject<ObjectName>UpdateAfter`, [here](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/)), but none of them is working.

#### Expected behavior

I want to have a hook when a customer is updating or adding an address.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by olecorre** [comment]
In 1.7.7.2 i use : actionObjectAddressUpdateAfter

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

If this is a bug, could you please provide steps to reproduce. If it's an improvement (I see you're asking to create a new hook) so you need to change the template.
So please decide :pray: is it a bug or a feature?

Thanks!

**Comment by bastienuh** [comment]
Hello,

I don't know if it's a bug or an improvement because I don't know if there is a hook after update address. 
If there is no hook, then it's an improvement to make. If it exists, then I will try it and hope there is no bug.

@hibatallahAouadni : do you confirm what @olecorre just said?

Thanks.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone answer @bastienu question :pray: 

Thanks in advance.

**Comment by atomiix** [comment]
Hey @bastienu, yes, @olecorre should be right, `actionObjectAddressUpdateAfter` is called when a customer updates its addresses

**Comment by bastienuh** [comment]
Thanks a lot @atomiix. I already tried it few days ago, but I'm going to try it again.

I guess the object passed in the params variable is the address updated?

**Comment by atomiix** [comment]
@bastienu actually, there is more than just the address in the params. An easy way to play with hooks and see what is in the params is by installing the [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance) module.

I'm closing the issue as it doesn't seem to be one in the end but feel free to re-open it if you think there's something we missed

**Comment by bastienu** [comment]
Hi @atomiix,
The hook `actionObjectAddressCreateAfter` does not seems to work...
Can you confirm it should be called?
Thanks.
