### ISSUE TITLE
Reorganize fields in product settings page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#24769]
#### Is your feature request related to a problem?

For a better architecture, reorganize fields in BO > shop parameters > product settings page in the following order:

![product settings](https://user-images.githubusercontent.com/13449658/120500402-1bf3d080-c3c1-11eb-97d9-70b631a805a6.png)

**Comment by lfga98** [comment]
Hi everyone!
I would like to work on this issue! 
Thank you!

**Comment by kpodemski** [comment]
@lfga98 that's great! :) you can create a PR on `develop` branch :)

**Comment by marionf** [comment]
Hello @lfga98 

That's great to hear :+1: 
You can make your pull request [here](https://github.com/PrestaShop/PrestaShop/tree/develop)
Let me know if you have any question :)

Thank you!
