### ISSUE TITLE
faceted search shows products from wrong category

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#24764]
#### Describe the bug

Filter products from sub category, products from another category with the same name shows instead.

#### Expected behavior

Products from the actual sub category should show.

#### Steps to Reproduce

1. Create two new categories in the shop, both names "Pants" and both having "pants" as seo friendly url. Place one of these as a sub category to Clothes -> Men and the other as a sub category to Clothes -> Women.
2. Add one product to the one under Men and another product to the one under Women.
3. Rebuild the index for the filter.
4. Go to both Women and Men category in the front office and filter on "Pants" you now get the same product for both filters, but it should be different ones.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.21
* Module version: 3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

I didn't manage to reproduce your issue with PS1.7.7.4, see the attached screen record below:

https://drive.google.com/file/d/1AkpNd2pAfo1Dh2-rAEbYcL3O5M9Dm6RC/view

Please check and feedback.
Thanks!

**Comment by Prestaworks** [comment]
> 
> 
> Hello @Prestaworks
> 
> I didn't manage to reproduce your issue with PS1.7.7.4, see the attached screen record below:
> 
> https://drive.google.com/file/d/1AkpNd2pAfo1Dh2-rAEbYcL3O5M9Dm6RC/view
> 
> Please check and feedback.
> Thanks!

Click on subcategory "Men" and filter on "Pants" then go to subcategory Women and filter on "Pants".

**Comment by cyrius** [comment]
The problem is located in the src/Filters/Converter.php near line 390

               case self::TYPE_CATEGORY:
                    if (isset($facetAndFiltersLabels[$filterLabel])) {
                        foreach ($facetAndFiltersLabels[$filterLabel] as $queryFilter) {
                            $categories = Category::searchByName($idLang, $queryFilter, true); // THIS LINE
                            if ($categories) {
                                $searchFilters[$filter['type']][] = $categories['id_category'];
                            }
                        }
                    }
                    break;
                  
As you can see the function used is Category::searchByName

I solved the problem on my side by changing the line to :
`$categories = Category::searchByNameAndParentCategoryId($idLang, $queryFilter, (int) $query->getIdCategory());`

This solution might not be the perfect one, but it seems to work on my use case.

**Comment by Prestaworks** [comment]
@cyrius I made a PR for this, it solved my issue also.

**Comment by uruk-hai-21** [comment]
Doesn't work for me
PS 1.7.7.5 - 1.7.7.3
Module version: 3.7.1

https://drive.google.com/file/d/14yHqFDWmfU6QL_TNCbbEJ1K-sVRUOgbv/view

**Comment by hibatallahAouadni** [comment]
Hello @uruk-hai-21 

Of course it doesn't, cause this issue will be fixed with Faceted search v3.7.2 as you can see in the PR https://github.com/PrestaShop/ps_facetedsearch/pull/449 (check the milestone)

Thanks!

**Comment by uruk-hai-21** [comment]
> Hello @uruk-hai-21
> 
> Of course it doesn't, cause this issue will be fixed with Faceted search v3.7.2 as you can see in the PR [PrestaShop/ps_facetedsearch#449](https://github.com/PrestaShop/ps_facetedsearch/pull/449) (check the milestone)
> 
> Thanks!

Hello @hibatallahAouadni 
I meant the patch doesn't work for me

**Comment by Prestaworks** [comment]
You are going to many levels, the patch fixes the search for subcategories on the current category. If you filter from "all" or a top level where there are multiple names two or more levels down in the three, the issue will still show up since the system can't know what of those categories it wants to filter from.

**Comment by Prestaworks** [comment]
Maybe we can change this instead to 
$categories = Category::searchByName($idLang, $queryFilter, false);
that will get all categories in the shop with a matching name.
Neither solution is perfect :)

**Comment by uruk-hai-21** [comment]
> $categories = Category::searchByName($idLang, $queryFilter, false);


With this change the filter does not show any results.
In my opinion it should filter by category ID and not by category name, is it possible?

**Comment by Prestaworks** [comment]
No there are more changes needed to get it to work with multiple matches on the next couple of rows.

**Comment by matrixino** [comment]
@Prestaworks @uruk-hai-21 @hibatallahAouadni 
Here is a very dirty fix for both situations. I used the category class getParentsCategories() method because i was in a hurry, but you can change it with the proper query directly, taken from the getParentsCategories() method, without the need of the category instance.
I can't create a clean and correct pull request right now, maybe some of you can adjust the code below for a proper pull.
```
case self::TYPE_CATEGORY:
    if (isset($facetAndFiltersLabels[$filterLabel])) {
        foreach ($facetAndFiltersLabels[$filterLabel] as $queryFilter) {
            $categories = Category::searchByName($idLang, $queryFilter, false);
            if ($categories) {
                foreach ($categories as $key => $category) {
                    $c = new Category ($category["id_category"]);
                    $parents = $c->getParentsCategories();
                    $search = array_search((int) $query->getIdCategory(), array_column($parents, "id_category"));
                    if ($search !== false) $categories = $category;
                }
                $searchFilters[$filter['type']][] = $categories['id_category'];
            }
        }
    }
    break;
```
