### ISSUE TITLE
the resume of the Orders is a completely mess + the Print the Order table is cut in half

### ISSUE THREAD

**Issue by milla-dev** [PrestaShop/PrestaShop#24779]
#### Describe the bug

Hello, we have just updated my boutique to the PS 1.7.7.4. What I can see is that the Orders are completely mess. The presentation is not nice and the fields are randomly placed on the screen. The descriptions of the fields are also in disorder.
Beside that, when I click on the "Print the order" - the print page is completely mess and unreadable. The table is cut in the half as well.

#### Expected behavior

The fields should be arranged and described properly.

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on ' one of the orders'
3. You will see the problem directly

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version:  7.3.20

**Comment by hibatallahAouadni** [comment]
Hello @milla-dev 

I couldn't reproduce your issue with PS1.7.7.4, could you pelase check the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/120599070-57d17900-c447-11eb-9228-49ea5bf21196.png)

Could you please provide screenshots.
Please check and feedback.

Thanks!

**Comment by milla-dev** [comment]
Hello

here is the screen shot:

[image: image.png]

After checking, on the Edge it works fine ! I have the problems on Chrome:

Google Chrome is up to date
Version 91.0.4472.77 (Official Build) (64-bit)

thank You for your help and reply.

cheers
Michal

**Comment by hibatallahAouadni** [comment]
Hello @milla-dev 

Could you please respond on Github and ot via mail :wink: cause the screenshot that you attached is unaccessible.
If you encounter the problem only on Chrome, so it's a cache problem.
You need to clear the PrestaShop cache and your navigator cache :wink: 

Hope it helps.
Thanks!

**Comment by milla-dev** [comment]
Yes, exactly !! It worked after the cache clean :) Thx !!!

**Comment by hibatallahAouadni** [comment]
@milla-dev Perfect :tada: 
Thanks for your feedback!
