### ISSUE TITLE
FO - Discounts - The discount detail is NOK when we the product selected has an ecotax

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24788]
#### Describe the bug

In the FO > Shopping cart page and checkout page, when we apply a cart rule "percent discount on a selected product that has an ecotax, the discount line s NOK.

#### Steps to Reproduce

1. Go to BO > International > Taxes & Enable Ecotax
2. Create a product with ecotax, in my case  ![image](https://user-images.githubusercontent.com/16067358/120637576-5d42b980-c46f-11eb-8b04-15f7ca2eb7cc.png)
3. Go to BO > Catalog > Cart rules page and create a cart rule:
3.1 Product Selection: select the ecotax product 
![image](https://user-images.githubusercontent.com/16067358/120637695-82372c80-c46f-11eb-8537-f96eb5a1469a.png)
3.2 a percent discount, in my case 50% & Apply a discount to Selected Products 
![image](https://user-images.githubusercontent.com/16067358/120637806-a09d2800-c46f-11eb-9ccd-b593a4bbf527.png)
4. Go to FO > Add the last product created to the cart
5. Apply the discount
6. See error: the discount line = 6.2 => NOK, it should be 6
![image](https://user-images.githubusercontent.com/16067358/120637995-df32e280-c46f-11eb-97f8-66dcbc60799a.png)

If we place the order => the discount is ok on the Order details page
![image](https://user-images.githubusercontent.com/16067358/120638058-f2de4900-c46f-11eb-8245-3de121fb51dd.png)

In the PS1769, we have this
![image](https://user-images.githubusercontent.com/16067358/120638133-0e495400-c470-11eb-97a4-08075fc631ba.png)

#### Additional information

* PrestaShop version: 1775build1, 1774
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #24868 by @Progi1984
