### ISSUE TITLE
cookie.php getSession not checking that $session is defined before using it

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#24781]
#### Describe the bug

In Cookie.php $session is used before checking if it is defined or not. This leads to crash if for example logout is called without checking if the session is alive.

https://github.com/PrestaShop/PrestaShop/blob/5f7367fc84c09dfee1306de149737b0316362bc5/classes/Cookie.php#L584

```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in ..../classes/Cookie.php:548
```

#### Expected behavior

No crash when calling logout without session.

#### Steps to Reproduce

call logout twice..

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

That method is added here: https://github.com/PrestaShop/PrestaShop/commit/3ef3b64d27b7d248bbd2f92289f11369b3dbbafa#diff-98d8ae92e3bdf87d1bd72ab244ca1619cb90f3fa8d0ed9a4c462ce1b929092b4R540

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone please check it :pray: cause in my case I duplicate the line:

`$this->context->employee->logout();`

When I try to logout from BO, I logout successfully with no errors. Thanks in advance :slightly_smiling_face:

**Comment by PierreRambaud** [comment]
> Ping @PrestaShop/prestashop-core-developers could someone please check it  cause in my case I duplicate the line:
> 
> `$this->context->employee->logout();`
> 
> When I try to logout from BO, I logout successfully with no errors. Thanks in advance

We can add a check in order to be sure everything is ok for him.
