### ISSUE TITLE
Access Modifiers methods in ps_specials module

### ISSUE THREAD

**Issue by thomasnavarro** [PrestaShop/PrestaShop#24793]
Hi !

#### Is your feature request related to a problem?

In the Ps_Specials class, the [getSpecialProducts](https://github.com/PrestaShop/ps_specials/blob/master/ps_specials.php#L215) method is private and so inaccessible if you want to extend it for the override.

#### Describe the solution you'd like

The solution would be to change the accessibility of the getSpecialProducts method from private to protected to have access to it if we want to extend the class ;)

Thank you! Thomas

**Comment by matks** [comment]
Hello @ThomasNavarro 

If I am not wrong, you can override the function `getWidgetVariables` that use `getSpecialProducts`, there's just 3 more lines of code in it compared to `getSpecialProducts()`?

Also why would you override this module? It's not native 🤔 .

**Comment by thomasnavarro** [comment]
Hi! 

I understand, I managed to do what I wanted to do. 
Sorry, I'm new to prestashop.

Thanks a lot! ;)

**Comment by matks** [comment]
No worries 😉  welcome to PrestaShop have a nice day
