### ISSUE TITLE
Wrong tab showed after changing combination on product page in the FO

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#24800]
#### Describe the bug

When you change combination, add product to cart etc. tabs below are not properly reloaded

#### Expected behavior

Reload tabs properly

#### Steps to Reproduce

1. Go to the FO
2. Go to Product with combinations page
3. Switch to second tab, probably "Product details"
4. Change combination
5. See error, "Product details" is now with product description

Unfortunately this is regression as we don't have such an issue on 1.7.7.x

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.8 and develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Yes indeed it's a regression!
I was able to reproduce the issue with PrestaShop version 1.7.8.x and develop. I’ll add this to the debug backlog so that it’s fixed.
If you manage to get the problem fixed, then please create a PR :pray: 

Thanks!

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24849
