### ISSUE TITLE
[BO - reponsive] - the fixed height in `.page-head.with-tabs` hide the `panel-heading`

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24804]
#### Describe the bug

BO Attributes page (for exemple), you can see a white blank hide the panel-heading, which prevent from access to the pabel-heading buttons.

PS: this issue exist in multiple pages (ex: Discounts, ...)

#### Expected behavior

Add this style:

```
@media(max-width: 1023px) {
  .page-head.with-tabs {
      height: auto;
  }
}
```

#### Steps to Reproduce

1. on mobile devise
2. BO > SELL > Catalog > Attributes and Features
3. See error > the fixed height in `.page-head.with-tabs` hide the `panel-heading`

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/120763446-81f26c00-c517-11eb-81d1-49b9c395a735.png)

#### Additional information

* PrestaShop version: develop & 1.7.8.x
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24813
