### ISSUE TITLE
New hook in product.tpl after product_buy block

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#24807]
#### Is your feature request related to a problem?

As discussed here:
https://github.com/PrestaShop/PrestaShop/issues/22880

It would be good for theme developers to have dynamically refreshed hook after the `<form>`

#### Describe the solution you'd like

Something like:

```
{block name='hook_display_after_buy_block'}
{capture name='displayAfterBuyBlock'}{hook h='displayAfterBuyBlock'}{/if}
{if $smarty.capture.displayAfterBuyBlock != ''}
<div class="after-buy-block">{$smarty.capture.displayAfterBuyBlock nofilter}</div>
{/block}
```

#### Alternatives you've considered

n/a

#### Additional context

All described in #22880

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @kpodemski did you add the proposed new hook in your PR https://github.com/PrestaShop/ps_emailalerts/pull/86 ?
If yes, shall we close this issue as `Fixed`?
