### ISSUE TITLE
The element height which contains Product images is not calculated when you access to product edit by clicking on price or qty in the Products list

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#24809]
#### Describe the bug

When I access the details of a product by clicking on the **product quantity** or **product price** in the product list, I arrive to the quantity or price tab. Going then to the **Basic Settings** tab, the element height is not calculated. I need to refresh the page.

#### Expected behavior

The element height should be calculated

![image](https://user-images.githubusercontent.com/23308427/120874065-2373cf00-c5a5-11eb-8c0f-bd3976b610bd.png)

#### Steps to Reproduce

1. Go to admin > Catalogue > Products
2. Click on a product quantity in the list
3. From the tab where you arrive in the product page, go to the essential tab
4. See error > the height is not calculated)

**Screenshots**
https://www.awesomescreenshot.com/video/4016852?key=845385fb30ee981e0928c692b6ec31ab

![image](https://user-images.githubusercontent.com/23308427/120874045-09d28780-c5a5-11eb-9951-29a6e43a8521.png)

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

I reproduce the issue with PS1.7.6.7 and PS1.7.7.4 but I think it has been fixed on develop (1.7.8.x): 

https://www.awesomescreenshot.com/video/4016852?key=845385fb30ee981e0928c692b6ec31ab

But, I notice that some JS are not called to calculate the height:

![image](https://user-images.githubusercontent.com/23308427/120874045-09d28780-c5a5-11eb-9951-29a6e43a8521.png)

In the other hand, when we click on edit product, the height is well calculated:

![image](https://user-images.githubusercontent.com/23308427/120874065-2373cf00-c5a5-11eb-8c0f-bd3976b610bd.png)

Ping @NeOMakinG wdyt?

**Comment by hibatallahAouadni** [comment]
As discussed with @NeOMakinG on Slack, I changed the issue title and description

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24848
