### ISSUE TITLE
Allow to filter available fields on import page

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#24802]
#### Is your feature request related to a problem?

I'm always frustrated when I need to map available field to column from CSV file, especially if there are a lot of fields.

#### Describe the solution you'd like

Use jquery chosen to allow quickly search field

### Proposed solution

Before:
https://www.dropbox.com/s/o431vfqy46gp07f/Nagranie%20z%20ekranu%202021-06-4%20o%2000.19.27.mov?dl=0

After:
https://www.dropbox.com/s/n0biyurcwr9t1oh/Nagranie%20z%20ekranu%202021-06-4%20o%2000.20.45.mov?dl=0

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
And thank for your PR and the proposed solution :rocket: :superhero: 

Thank you
