### ISSUE TITLE
Bad redirection on shop context links in BO

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#24818]
#### Describe the bug

In BO, when the shop is configured not to use url tokens, clicking on a shop context link will redirects to the BO's home page.

#### Expected behavior

It should switch context and redirect to the same page.

#### Steps to Reproduce

- Disable URL tokens, by writing `SetEnv _TOKEN_ disabled` in your `.htaccess` file, at the root of your prestashop project
- Activate multistore
- Add at least one shop
- Go on a page where the multistore header will appear, ex: maintenance configuration page
- In the multistore header dropdown, click on a shop's link to switch context, you will be redirected to BO's home page

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #24851
