### ISSUE TITLE
FO - Checkout page - Number of items is not updated when adding or removing a discount free gift 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24817]
#### Describe the bug

In the FO > Checkout page > the number of items is not updated when adding or removing a discount free gift
#### Expected behavior

1. Create cart rule with code Free gift
2. Go to FO > Sign in > Add a product to the cart and proceed to checkout
3. In the Checkout page > apply the discount
4. See error: the number of items is not updated
5. Refresh the page => ok
6. Remove the discount
7. See error: the number of items is not decreased

**Screenshots**

https://drive.google.com/file/d/1gHDqz4-uR139wPsdmozzDR5DHmEMdtMA/view?usp=sharing

#### Additional information

* PrestaShop version: 1769, 1775build1
* PHP version: 7.1, 7.2

**Comment by jf-viguier** [comment]
@khouloudbelguith is this bug fixed by this pr https://github.com/PrestaShop/PrestaShop/pull/24795 ?

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your feedback.
Yes, It could be fixed with this PR because they are related.
I will check this issue when testing the PR.

Thank you!

**Comment by khouloudbelguith** [comment]
This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/24795

**Comment by jf-viguier** [comment]
good news
