### ISSUE TITLE
Productcomments : remove useless upgrade file

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#24814]
#### Is your feature request related to a problem?

Productcomments : remove useless upgrade file

#### Describe the solution you'd like

Remove useless upgrade file

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: all

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks for your PR.

**Comment by jf-viguier** [comment]
I've hired myself ;-)

**Comment by jf-viguier** [comment]
@hibatallahAouadni please don't advertise prestashop corp partner program, you are here in open source space.

**Comment by hibatallahAouadni** [comment]
@jf-viguier it's an automatic response and I do not advertise prestashop corp partner program :wink:

**Comment by jf-viguier** [comment]
@hibatallahAouadni have a nice week-end

**Comment by hibatallahAouadni** [comment]
@jf-viguier you too :slightly_smiling_face:
