### ISSUE TITLE
Multistore configuration key is not valid html

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#24812]
#### Describe the bug

Multistore configuration key is set as an html attribute `multistore_configuration_key` which is not valid HTML (it should be `data-multistore_configuration_key` 

#### Expected behavior

Since this attribute is not used in front end we decided to pass this value as an option.

See PR:  https://github.com/PrestaShop/PrestaShop/pull/24811

It must be fixed in 1.7.8 overwise fixing it later will be a breaking change.

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @matthieu-rolland in #24811
