### ISSUE TITLE
CA Bundle file for database connection

### ISSUE THREAD

**Issue by BartoszCoyote** [PrestaShop/PrestaShop#24810]
Is there any option to use certificate file to the database using parameters?

**Comment by hibatallahAouadni** [comment]
Hello @BartoszCoyote 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
