### ISSUE TITLE
[BO - desktop] - Email themes loops are misplaced & `.dropdown-menu>li a` width is not 100%

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24826]
#### Describe the bug 

**1st issue:** Email themes loops are aligned in `Center` 
**2nd issue:** `.dropdown-menu>li a` width only fit the link content, so we can only click on link when we hover on the word

#### Expected behavior

**1st issue:** Email themes loops should be aligned to the `right`
**2nd issue:** `.dropdown-menu>li a` width should be 100%

#### Steps to Reproduce

**1st issue:**
1. BO > IMPROVE > Design > Email Theme
2. Scroll down to **Email themes**
3. See error > the loops are aligned center 

**2nd issue:**
1. BO > SELL > Catalog > Attributes & Features (or Brands, Discounts, ....)
2. Click on **dropdown-toggle** button 
3. See error > you can only click on the link when you hover over the word

**Screenshots**

- 1st issue:

![image](https://user-images.githubusercontent.com/23308427/120874942-57e98a00-c5a9-11eb-9895-c744988b94f8.png)

- 2nd issue:

https://drive.google.com/file/d/1K2J_4N9uePlqPzyyEJ8_MiKnQHwPPMoI/view

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24837
