### ISSUE TITLE
Use language code instead of ISO code in HTML lang

### ISSUE THREAD

**Issue by bimlas** [PrestaShop/PrestaShop#24833]
#### Describe the bug

If I create a language with the ISO code `AT` for Austria, it will show `<html lang="at">` on the front office, but this is not a real ISO code that should be included here.

#### Expected behavior

`<html lang="de">` would be the right value according to https://www.w3schools.com/tags/ref_language_codes.asp

#### Steps to Reproduce

1. Go to BO -> International -> Localization -> Languages
2. Add a new language with the `at` ISO code and `de-AT` language code
3. Go to FO, view the HTML code and notice the `<html lang="at">` on the top

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment]
Hello @bimlas 

Could you please check these issues #24254 & #16070 cause it seems similar to yours.
Please check and feedback.

PS: I manage to reproduce the issue but I think this is the expected behavior, see the attached screen record below:
https://drive.google.com/file/d/1j1cw2pPl7iGjExg5jhweD_bEoI51F5op/view

Thanks!

**Comment by bimlas** [comment]
@hibatallahAouadni,

The aim would be to be able to add 3 German translations to products that target a specific area (Germany, Austria, Switzerland with language codes `de-DE`, `de-AT`, `de-CH`). With the current behaviour, they should get different ISO codes (`DE`, `AT`, `CH`), but these cannot be included in the `<html lang="...">` parameter because `AT` and `CH` are not valid ISO codes. Therefore, I would like you to extract the ISO code for `<html lang="...">` from the language code which is `de` in all cases. Language codes are listed as alternate links, so search engines will find pages for the appropriate country and the language markup on the page will remain valid.

```html
<html lang="de">
  <!-- ... -->
  <link rel="alternate" href="..." hreflang="de-at">
```

**Comment by PierreRambaud** [comment]
I agree with @hibatallahAouadni seems to be the expected behaviour. If you want something special for your theme, you can do it directly on it.

**Comment by bimlas** [comment]
Ok, thanks for the advice!
