### ISSUE TITLE
Change GB zone to Europe (non-EU)

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#24842]
#### Describe the bug
There are incorrect country attributes for the Great Britain and North Macedonia.

#### Expected behavior
Great Britain: Zone = Europe (non-EU)
Macedonia: country is renamed to North Macedonia => Fixed on 1.7.8.0

#### Steps to Reproduce

1. BO > International > Locations > Countries
2. Select country Great Britain
3. See error > Zone should be Europe (non-EU)

#### Additional information
* PrestaShop version: 1.7.7.4
* PHP version:  7.3.28

**Comment by hibatallahAouadni** [comment]
Hello @juraj1000 

Could you please specify the bug that you encountered 🙏  
To reproduce the issue, do we need to install the shop with **Macedonia** as a country?
Please check and feedback.

Thanks!

**Comment by juraj1000** [comment]
Hello @hibatallahAouadni,
there is Macedonia in the list of countries: BO > International > Locations > Countries > select  country with the ISO code = MK.
But the correct name is North Macedonia.

**Comment by hibatallahAouadni** [comment]
@matks what's happening here?

**Comment by matks** [comment]
@hibatallahAouadni unwanted side-effect of GitHub management of issues and Pull Request 😛

**Comment by hibatallahAouadni** [comment]
> there is Macedonia in the list of countries: BO > International > Locations > Countries > select country with the ISO code = MK.
But the correct name is North Macedonia.

Ping @Julievrz could you please confirm that the right ISO code of **North Macedonia** is **MK** or **NM**?

**Comment by Julievrz** [comment]
> > there is Macedonia in the list of countries: BO > International > Locations > Countries > select country with the ISO code = MK.
> > But the correct name is North Macedonia.
> 
> Ping @Julievrz could you please confirm that the right ISO code of **North Macedonia** is **MK** or **NM**?

I had a look on the internet and multiple websites say it is "MK". It seems that "NM" is only for car license plates.

**Comment by Julievrz** [comment]
> Hello @hibatallahAouadni,
> there is Macedonia in the list of countries: BO > International > Locations > Countries > select country with the ISO code = MK.
> But the correct name is North Macedonia.

Hi @juraj1000 
It seems that "Macedonia" was already changed to "North Macedonia" in 1.7.8. Regarding the ISO code, I think it shouldn't be modified. Indeed, based on the research I did, "MK" is still the official ISO code for North Macedonia. Only the code on license plates changed.

**Comment by hibatallahAouadni** [comment]
Thanks @Julievrz I updated the issue description to fix only the issue about GB :slightly_smiling_face:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24866
