### ISSUE TITLE
Product Flag 

### ISSUE THREAD

**Issue by yiohan** [PrestaShop/PrestaShop#24855]
* PrestaShop version: 1.7.6
Hello i need help . I insert a flag for "Sold Out" but i have problem with some products . More products have attributes and you changes this attributes on product list like that https://prnt.sc/14kh5wm and the problem is the red attribute have 4 pieces and the white attribute havent pieces but if you choose the red color the flag with "sold out" dont dissapear

**Comment by hibatallahAouadni** [comment]
Hello @yiohan 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
>   Hello i need help

Then you should visit https://devdocs.prestashop.com/1.7/faq/i-need-help/
