### ISSUE TITLE
Bestsellers and special offers links in Prestashop HTML sitemap page

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#24856]
Hi,

The link to the bestsellers page is not listed in the sitemap page managed by Prestashop (not the xml sitemap from the module).

So I looked in the file /controllers/front/SitemapController.php and at line 154 we have the condition:
if (Configuration::isCatalogMode() && Configuration::get('PS_DISPLAY_BEST_SELLERS'))

Why is there "Configuration::isCatalogMode()" in the condition? Doesn't this mean "if the catalog mode is activated..."?

What would be the purpose to show the bestsellers page if the shop is on catalog mode? Could this be a mistake?

#### Additional information

* PrestaShop version: 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ced--ced** [comment]
Hi @hibatallahAouadni,

I follow all the points raised in the "Good bug report" part of the documentation you mention: https://build.prestashop.com/news/how-bug-reports-are-handled/#1-good-bug-reports

The problem:
The bestsellers page link does not show in the sitemap file managed by Prestashop: i.e. www.yoursite.com/sitemap.

The reason:
The code on line 154 in /controllers/front/SitemapController.php has a condition:
if (Configuration::isCatalogMode() && Configuration::get('PS_DISPLAY_BEST_SELLERS'))

The Prestashop version:
PrestaShop version: 1.7.7.2

My query:
Why having a condition to show this link only if the catalog mode is on?

The solution to help you:
Delete the condition.

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

> Why having a condition to show this link only if the catalog mode is on?

Well, I believe this is the expected behavior. So, it's not a bug.

Thanks!
